### ISSUE TITLE
`service.selector.link` on a rancher LB doesn't update haproxy.conf when linked service is recreated

### ISSUE THREAD

**Issue by ndelitski** [rancher/rancher#2556] opened 2015-11-05 14:10 UTC
The link is appeared but haproxy entry for this service wasn't created, then any sense in selector linking on LB-side?
```
Rancher	v0.44.0
Cattle	v0.107.0
User Interface	v0.65.0
Rancher Compose	v0.5.1
```

**Comment by ndelitski** [comment] 2015-11-05 14:15
I have multiple services connected to the same LB using V7 routing, sometimes i have to recreate services in order to change it's configuration(add labels and etc) and don't wanna to recreate LB from a scratch due to other services become inaccessible too. Upgrade is kinda buggy and i don't use it.

**Comment by ndelitski** [comment] 2015-11-05 14:20
And if LB handle the situation when target service is deleted why it don't react when target service is recreated? This is my point

**Comment by deniseschannon** [comment] 2015-11-09 19:08
It sounds like you're facing this issue: https://github.com/rancher/rancher/issues/2288

But honestly, I don't completely follow what you're trying to say. 

When you say "recreated", what does that mean? Are you scaling up/down? Creating a new service with same labels/names?

**Comment by ndelitski** [comment] 2015-11-09 19:13
No scaling. Remove and create service which matches link expression on LB-side. Initially this service should be linked in LB's docker-compose file in `external_links` section

**Comment by deniseschannon** [comment] 2015-11-09 19:14
Can you provide a docker-compose.yml that has the LB and steps that you took? I cannot follow what you are describing.

**Comment by ndelitski** [comment] 2015-11-09 19:18
In other words: I have linked service to LB both with `externals_links: frontend/frontend-app` section and `sevice.selector.link: service=frontend/frontend-app`. Recreated `frontend/frontend-app` and expected that LB would work as previously

**Comment by ndelitski** [comment] 2015-11-09 19:30
Try this
stack: frontend
docker-compose.yml
```yml
frontend-app:
  image: nginx:1.9.4
  labels:
    service: frontend/frontend-app
```
stack: lb
docker-compose.yml
```yml
lb:
  image: rancher/load-balancer-service
  ports:
    - 8400
  external_links:
    - frontend/frontend:frontend
  labels:
    io.rancher.scheduler.global: 'true'
    io.rancher.loadbalancer.target.frontend/frontend-app: sub.domain.com:8400=80
```

**Comment by ndelitski** [comment] 2015-11-09 19:32
1) curl from the host `curl -H"Host: sub.domain.com" <lb-ip>:8400` - Work
2) remove, create frontend-app
3) curl from the host `curl -H"Host: sub.domain.com" <lb-ip>:8400` - Don't work

**Comment by ndelitski** [comment] 2015-11-09 22:05
Very strange problems... Currently i have launched this template from UI, remove then create frontend-app and LB picked incorrect port for backend target(8400 instead of 80):

copied templates from UI for doublecheck
```yml
lb:
  ports:
  - '8400'
  external_links:
  - frontend/frontend-app:frontend-app
  labels:
    io.rancher.scheduler.global: 'true'
    io.rancher.service.selector.link: service=frontend/frontend-app
    io.rancher.service.hash: fcb1ced8451f6624f57759fbd1dd8bafb7c0413c
    io.rancher.loadbalancer.target.frontend/frontend-app: sub.domain.com:8400=80
  image: rancher/load-balancer-service
```
```yml
frontend-app:
  restart: always
  labels:
    service: frontend/frontend-app
  tty: true
  image: nginx:1.9.4
  stdin_open: true
```
on lb instance
```
$ cat /etc/haproxy/haproxy.cfg
...
frontend 57f6158f-013c-40ff-af1f-a0b84b300612_frontend                          
        bind 10.42.118.191:8400                                                 
        mode http                                                               
                                                                                
        default_backend 57f6158f-013c-40ff-af1f-a0b84b300612_0_backend          
                                                                                
backend 57f6158f-013c-40ff-af1f-a0b84b300612_0_backend                          
        mode http                                                              
        balance roundrobin                                                      
        server 95460157-4137-4c9e-ba64-2224ed6b6d93 10.42.63.59:8400     << here should be 80
```
<img width="381" alt="screenshot 2015-11-10 01 03 55" src="https://cloud.githubusercontent.com/assets/3070298/11048093/f39bc604-8746-11e5-8707-7f043e68b8ab.png">

**Comment by ndelitski** [comment] 2015-11-09 22:17
1) Then remove, create lb stack
on lb
```
$ cat /etc/haproxy/haproxy.cfg
...
frontend 3cc7b359-9577-4dec-bdb3-4b59f4ef500b_frontend                          
        bind 10.42.144.181:8400                                                 
        mode http                                                               
                                                                                
        acl 0_host hdr(host) -i sub.domain.com                                  
        acl 0_host hdr(host) -i sub.domain.com:8400                             
        use_backend 3cc7b359-9577-4dec-bdb3-4b59f4ef500b_0_backend if 0_host    
                                                                                
backend 3cc7b359-9577-4dec-bdb3-4b59f4ef500b_0_backend                          
        mode http                                                               
        balance roundrobin                                                      
        server d93d8ea5-ad0d-4890-ab54-e81967bb0b80 10.42.151.105:80   << normal port
```
Looking good.

2) Remove frontend stack:
```
$ cat /etc/haproxy/haproxy.cfg
...
                                                                                
listen web 0.0.0.0:9  
```
Nothing to listen, no links, ok.

3) Create frontend stack again:
```
$ cat /etc/haproxy/haproxy.cfg
...
frontend 3cc7b359-9577-4dec-bdb3-4b59f4ef500b_frontend                          
        bind 10.42.144.181:8400                                                 
        mode http                                                               
                 << nothing here
        default_backend 3cc7b359-9577-4dec-bdb3-4b59f4ef500b_0_backend          
                                                                                
backend 3cc7b359-9577-4dec-bdb3-4b59f4ef500b_0_backend                          
        mode http                                                               
        balance roundrobin                                                      
        server 5925da62-0497-41cb-85ce-706e88112e67 10.42.244.244:8400   << wrong port
```
Compare with config on step 1.

**Comment by ndelitski** [comment] 2015-11-09 22:49
![gatto-pop-corn](https://cloud.githubusercontent.com/assets/3070298/11048937/cb2e0808-874b-11e5-8238-fd7aa026eaa2.png)
Ohhh sorry me @deniseschannon Another program error when created lb stack after frontend and backend stacks created.
![screenshot 2015-11-10 01 29 56](https://cloud.githubusercontent.com/assets/3070298/11049002/31295ca2-874c-11e5-800d-a248df17f806.png)
logs in rancher server:
```
2015-11-09 22:30:20,055 ERROR [:] [] [] [] [p1860112097-151] [i.g.i.g.r.handler.ExceptionHandler  ] Exception in API for request [io.github.ibuildthecloud.gdapi.request.ApiRequest@8f67f1] org.jooq.exception.InvalidResultException: Cursor returned more than one result
	at org.jooq.impl.Utils.fetchOne(Utils.java:950) ~[jooq-3.3.0.jar:na]
	at org.jooq.impl.AbstractResultQuery.fetchOne(AbstractResultQuery.java:470) ~[jooq-3.3.0.jar:na]
	at org.jooq.impl.SelectImpl.fetchOne(SelectImpl.java:2372) ~[jooq-3.3.0.jar:na]
	at io.cattle.platform.object.impl.JooqObjectManager.findOne(JooqObjectManager.java:339) ~[cattle-framework-object-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.object.impl.JooqObjectManager.findOne(JooqObjectManager.java:345) ~[cattle-framework-object-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.servicediscovery.dao.impl.ServiceConsumeMapDaoImpl.findNonRemovedMap(ServiceConsumeMapDaoImpl.java:64) ~[cattle-iaas-service-discovery-server-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.servicediscovery.dao.impl.ServiceConsumeMapDaoImpl.createServiceLink(ServiceConsumeMapDaoImpl.java:161) ~[cattle-iaas-service-discovery-server-0.5.0-SNAPSHOT.jar:na]
	at sun.reflect.GeneratedMethodAccessor2372.invoke(Unknown Source) ~[na:na]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.7.0_85]
	at java.lang.reflect.Method.invoke(Method.java:606) ~[na:1.7.0_85]
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:317) ~[spring-aop-3.2.5.RELEASE.jar:3.2.5.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:183) ~[spring-aop-3.2.5.RELEASE.jar:3.2.5.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:150) ~[spring-aop-3.2.5.RELEASE.jar:3.2.5.RELEASE]
	at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:96) ~[spring-tx-3.2.4.RELEASE.jar:3.2.4.RELEASE]
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:260) ~[spring-tx-3.2.4.RELEASE.jar:3.2.4.RELEASE]
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:94) ~[spring-tx-3.2.4.RELEASE.jar:3.2.4.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172) ~[spring-aop-3.2.5.RELEASE.jar:3.2.5.RELEASE]
	at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:91) ~[spring-aop-3.2.5.RELEASE.jar:3.2.5.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172) ~[spring-aop-3.2.5.RELEASE.jar:3.2.5.RELEASE]
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:204) ~[spring-aop-3.2.5.RELEASE.jar:3.2.5.RELEASE]
	at com.sun.proxy.$Proxy39.createServiceLink(Unknown Source) ~[na:na]
	at io.cattle.platform.servicediscovery.api.service.impl.ServiceDiscoveryApiServiceImpl.addLoadBalancerServiceLink(ServiceDiscoveryApiServiceImpl.java:81) ~[cattle-iaas-service-discovery-api-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.servicediscovery.api.action.SetServiceLinksActionHandler.createNewServiceMaps(SetServiceLinksActionHandler.java:98) ~[cattle-iaas-service-discovery-api-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.servicediscovery.api.action.SetServiceLinksActionHandler.access$100(SetServiceLinksActionHandler.java:28) ~[cattle-iaas-service-discovery-api-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.servicediscovery.api.action.SetServiceLinksActionHandler$1.doWithLockNoResult(SetServiceLinksActionHandler.java:65) ~[cattle-iaas-service-discovery-api-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.lock.LockCallbackNoReturn.doWithLock(LockCallbackNoReturn.java:7) ~[cattle-framework-lock-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.lock.LockCallbackNoReturn.doWithLock(LockCallbackNoReturn.java:3) ~[cattle-framework-lock-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.lock.impl.AbstractLockManagerImpl$3.doWithLock(AbstractLockManagerImpl.java:40) ~[cattle-framework-lock-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.lock.impl.LockManagerImpl.doLock(LockManagerImpl.java:33) ~[cattle-framework-lock-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.lock.impl.AbstractLockManagerImpl.lock(AbstractLockManagerImpl.java:13) ~[cattle-framework-lock-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.lock.impl.AbstractLockManagerImpl.lock(AbstractLockManagerImpl.java:37) ~[cattle-framework-lock-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.servicediscovery.api.action.SetServiceLinksActionHandler.perform(SetServiceLinksActionHandler.java:58) ~[cattle-iaas-service-discovery-api-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.api.resource.AbstractObjectResourceManager.resourceActionInternal(AbstractObjectResourceManager.java:363) ~[cattle-framework-api-0.5.0-SNAPSHOT.jar:na]
	at io.github.ibuildthecloud.gdapi.request.resource.impl.AbstractBaseResourceManager.resourceAction(AbstractBaseResourceManager.java:414) ~[cattle-framework-java-server-0.5.0-SNAPSHOT.jar:na]
	at io.github.ibuildthecloud.gdapi.request.resource.AbstractResourceManagerFilter.resourceAction(AbstractResourceManagerFilter.java:58) ~[cattle-framework-java-server-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.servicediscovery.api.filter.ServiceSetServiceLinksValidationFilter.resourceAction(ServiceSetServiceLinksValidationFilter.java:63) ~[cattle-iaas-service-discovery-api-0.5.0-SNAPSHOT.jar:na]
	at io.github.ibuildthecloud.gdapi.request.resource.impl.FilteredResourceManager.resourceAction(FilteredResourceManager.java:86) ~[cattle-framework-java-server-0.5.0-SNAPSHOT.jar:na]
	at io.github.ibuildthecloud.gdapi.request.resource.AbstractResourceManagerFilter.resourceAction(AbstractResourceManagerFilter.java:58) ~[cattle-framework-java-server-0.5.0-SNAPSHOT.jar:na]
	at io.github.ibuildthecloud.gdapi.request.resource.impl.FilteredResourceManager.resourceAction(FilteredResourceManager.java:86) ~[cattle-framework-java-server-0.5.0-SNAPSHOT.jar:na]
	at io.github.ibuildthecloud.gdapi.request.handler.ResourceManagerRequestHandler.generate(ResourceManagerRequestHandler.java:43) ~[cattle-framework-java-server-0.5.0-SNAPSHOT.jar:na]
	at io.github.ibuildthecloud.gdapi.request.handler.AbstractResponseGenerator.handle(AbstractResponseGenerator.java:14) ~[cattle-framework-java-server-0.5.0-SNAPSHOT.jar:na]
	at io.github.ibuildthecloud.gdapi.request.handler.write.DefaultReadWriteApiDelegate.handle(DefaultReadWriteApiDelegate.java:27) ~[cattle-framework-java-server-0.5.0-SNAPSHOT.jar:na]
	at io.github.ibuildthecloud.gdapi.request.handler.write.DefaultReadWriteApiDelegate.write(DefaultReadWriteApiDelegate.java:22) ~[cattle-framework-java-server-0.5.0-SNAPSHOT.jar:na]
	at sun.reflect.GeneratedMethodAccessor629.invoke(Unknown Source) ~[na:na]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.7.0_85]
	at java.lang.reflect.Method.invoke(Method.java:606) ~[na:1.7.0_85]
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:317) ~[spring-aop-3.2.5.RELEASE.jar:3.2.5.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:183) ~[spring-aop-3.2.5.RELEASE.jar:3.2.5.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:150) ~[spring-aop-3.2.5.RELEASE.jar:3.2.5.RELEASE]
	at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:96) ~[spring-tx-3.2.4.RELEASE.jar:3.2.4.RELEASE]
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:260) ~[spring-tx-3.2.4.RELEASE.jar:3.2.4.RELEASE]
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:94) ~[spring-tx-3.2.4.RELEASE.jar:3.2.4.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172) ~[spring-aop-3.2.5.RELEASE.jar:3.2.5.RELEASE]
	at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:91) ~[spring-aop-3.2.5.RELEASE.jar:3.2.5.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172) ~[spring-aop-3.2.5.RELEASE.jar:3.2.5.RELEASE]
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:204) ~[spring-aop-3.2.5.RELEASE.jar:3.2.5.RELEASE]
	at com.sun.proxy.$Proxy43.write(Unknown Source) ~[na:na]
	at io.github.ibuildthecloud.gdapi.request.handler.write.ReadWriteApiHandler.handle(ReadWriteApiHandler.java:19) ~[cattle-framework-java-server-0.5.0-SNAPSHOT.jar:na]
	at io.github.ibuildthecloud.gdapi.servlet.ApiRequestFilterDelegate.doFilter(ApiRequestFilterDelegate.java:86) ~[cattle-framework-java-server-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.api.servlet.ApiRequestFilter$1.runInContext(ApiRequestFilter.java:79) [cattle-framework-api-0.5.0-SNAPSHOT.jar:na]
	at org.apache.cloudstack.managed.context.ManagedContextRunnable$1.run(ManagedContextRunnable.java:49) [cattle-framework-managed-context-0.5.0-SNAPSHOT.jar:na]
	at org.apache.cloudstack.managed.context.impl.DefaultManagedContext$1.call(DefaultManagedContext.java:55) [cattle-framework-managed-context-0.5.0-SNAPSHOT.jar:na]
	at org.apache.cloudstack.managed.context.impl.DefaultManagedContext.callWithContext(DefaultManagedContext.java:108) [cattle-framework-managed-context-0.5.0-SNAPSHOT.jar:na]
	at org.apache.cloudstack.managed.context.impl.DefaultManagedContext.runWithContext(DefaultManagedContext.java:52) [cattle-framework-managed-context-0.5.0-SNAPSHOT.jar:na]
	at org.apache.cloudstack.managed.context.ManagedContextRunnable.run(ManagedContextRunnable.java:46) [cattle-framework-managed-context-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.api.servlet.ApiRequestFilter.doFilter(ApiRequestFilter.java:72) [cattle-framework-api-0.5.0-SNAPSHOT.jar:na]
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652) [jetty-servlet-9.2.11.v20150529.jar:9.2.11.v20150529]
	at org.eclipse.jetty.servlets.UserAgentFilter.doFilter(UserAgentFilter.java:83) [jetty-servlets-9.2.11.v20150529.jar:9.2.11.v20150529]
	at org.eclipse.jetty.servlets.GzipFilter.doFilter(GzipFilter.java:300) [jetty-servlets-9.2.11.v20150529.jar:9.2.11.v20150529]
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652) [jetty-servlet-9.2.11.v20150529.jar:9.2.11.v20150529]
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:585) [jetty-servlet-9.2.11.v20150529.jar:9.2.11.v20150529]
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143) [jetty-server-9.2.11.v20150529.jar:9.2.11.v20150529]
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:577) [jetty-security-9.2.11.v20150529.jar:9.2.11.v20150529]
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:223) [jetty-server-9.2.11.v20150529.jar:9.2.11.v20150529]
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1127) [jetty-server-9.2.11.v20150529.jar:9.2.11.v20150529]
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:515) [jetty-servlet-9.2.11.v20150529.jar:9.2.11.v20150529]
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185) [jetty-server-9.2.11.v20150529.jar:9.2.11.v20150529]
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1061) [jetty-server-9.2.11.v20150529.jar:9.2.11.v20150529]
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141) [jetty-server-9.2.11.v20150529.jar:9.2.11.v20150529]
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97) [jetty-server-9.2.11.v20150529.jar:9.2.11.v20150529]
	at org.eclipse.jetty.server.Server.handle(Server.java:499) [jetty-server-9.2.11.v20150529.jar:9.2.11.v20150529]
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:310) [jetty-server-9.2.11.v20150529.jar:9.2.11.v20150529]
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:257) [jetty-server-9.2.11.v20150529.jar:9.2.11.v20150529]
	at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:540) [jetty-io-9.2.11.v20150529.jar:9.2.11.v20150529]
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635) [jetty-util-9.2.11.v20150529.jar:9.2.11.v20150529]
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555) [jetty-util-9.2.11.v20150529.jar:9.2.11.v20150529]
	at java.lang.Thread.run(Thread.java:745) [na:1.7.0_85]

time="2015-11-09T22:30:20Z" level=error msg="Failed Creating lb : Bad response statusCode [500]. Status [500 Internal Server Error]. Body: [message=Internal Server Error, code=Internal Server Error] from [http://192.168.99.100/v1/projects/1a5/loadbalancerservices/1s17/?action=setservicelinks]" 
time="2015-11-09T22:30:20Z" level=error msg="Failed to start: lb : Bad response statusCode [500]. Status [500 Internal Server Error]. Body: [message=Internal Server Error, code=Internal Server Error] from [http://192.168.99.100/v1/projects/1a5/loadbalancerservices/1s17/?action=setservicelinks]" 
time="2015-11-09T22:30:20Z" level=error msg="Stack Create Event Failed: Bad response statusCode [500]. Status [500 Internal Server Error]. Body: [message=Internal Server Error, code=Internal Server Error] from [http://192.168.99.100/v1/projects/1a5/loadbalancerservices/1s17/?action=setservicelinks]" eventId=2dc2bb95-7d8b-44a1-a559-7a464f18b017 resourceId=1e15 
time="2015-11-09T22:30:20Z" level=info msg="[lb:]: Project created " eventId=2dc2bb95-7d8b-44a1-a559-7a464f18b017 resourceId=1e15
```

stacks configs(this are examples and only designed to illustrate a problem)
frontend
```
frontend-conf:
  image: debian
  command: 'sleep infinity'
  volumes:
    - /tmp
frontend-app:
  image: nginx:1.9.4
  volumes_from:
    - frontend-conf
  labels:
    io.rancher.scheduler.global: 'true'
    service: frontend/frontend-app
    io.rancher.sidekicks: frontend-conf
```
backend
```
backend-conf:
  image: debian
  command: 'sleep infinity'
  volumes:
    - /tmp
backend-app:
  image: nginx:1.9.4
  volumes_from:
    - backend-conf
  labels:
    io.rancher.scheduler.global: 'true'
    service: backend/backend-app
    io.rancher.sidekicks: backend-conf
```
lb
```
lb:
  image: rancher/load-balancer-service
  ports:
    - 8400
  external_links:
    - frontend/frontend-app:frontend
    - backend/backend-app:backend
  labels:
    io.rancher.scheduler.global: 'true'
    io.rancher.loadbalancer.target.frontend/frontend-app: sub.domain.com:8400=80
    io.rancher.loadbalancer.target.backend/backend-app: backend.domain.com:8400=80
    io.rancher.service.selector.link: service in (frontend/frontend-app, backend/backend-app)
```
Steps:
1) Create frontend and backed from UI
2) Launch LB
3) See error in rancher-server

**Comment by deniseschannon** [comment] 2015-11-11 22:26
For your first issue, I have finally understood your steps and it's a duplicate of https://github.com/rancher/rancher/issues/2288. Essentially, there is no way to have hostname routing rules applied to services that are joining a LB through a selector link. Even if you had your service set up as a target service with hostname routing rules previously, these rules won't get re-created.

Now, the most recent issue I have been unable to reproduce.

I'm going to close this issue as it's a duplicate of the feature request of #2288.

**Closed by deniseschannon** 2015-11-11 22:26 UTC
