### ISSUE TITLE
Create doesn't create all circular links so starting in UI will not work, but starting in CLI does work

### ISSUE THREAD

**Issue by vincent99** [rancher/rancher#1851] opened 2015-08-21 18:11 UTC
Given this [docker-compose.yml](https://gist.github.com/vincent99/c4a4a74bdf0ae91bcb20), `rancher-compose up` will create all the links correctly:

![image](https://cloud.githubusercontent.com/assets/753917/9415513/c2643274-47f4-11e5-989f-ff4aa85ece9f.png)

Whilst `rancher-compose create` (+ optionally `start`) will not:

![image](https://cloud.githubusercontent.com/assets/753917/9415501/b7addb3c-47f4-11e5-9f04-0041b5edb046.png)

**Comment by JamesBarwell** [comment] 2015-08-25 09:47
Just a note to say that I am also losing circular linking when using ```rancher-compose upgrade```. So in the example below I can build my V2 services with circular links using ```up```. But then when I upgrade, if foo is upgraded first, it will not be linked to bar - but bar will be linked to foo.

```
fooV2:
  image: tutum/hello-world
  links:
    - barV2:bar

barV2:
  image: tutum/hello-world
  links:
    - fooV2:foo

fooV3:
  image: tutum/hello-world
  stdin_open: true
  links:
    - barV3:bar

barV3:
  restart: always
  tty: true
  image: tutum/hello-world
  links:
    - fooV3:foo
```

**Comment by ibuildthecloud** [comment] 2015-09-14 21:50
I believe this is an issue that was there with circular linking.  Circular links work in v0.2.5, but I just added another test https://github.com/rancher/rancher-compose/pull/86 to ensure that this [specific compose](https://gist.github.com/vincent99/c4a4a74bdf0ae91bcb20) file works.

**Comment by ibuildthecloud** [comment] 2015-09-14 22:01
Just to clarify.  The problem is that on circular dependencies create doesn't complete all the links.  An `up` or `start` from the CLI will complete the links.  We should probably fix this so that all links are created on `create`

**Comment by deniseschannon** [comment] 2015-09-14 22:13
@JamesBarwell For `upgrade`, you need to upgrade each individual service at a time. You can't do a generic upgrade and except all services to be upgraded. 

The syntax is `rancher-compose upgrade service1 service2`

When you do them individually, the circular links are still in tact.

**Comment by JamesBarwell** [comment] 2015-09-24 07:58
Thanks for the reply. I think the issue I've had comes from how I've scripted the upgrade process. We're auto-generating the *compose files and looping over each service, running ```rancher-compose upgrade```. I'll provide an update when I've had a chance to rework these scripts, but please ignore for now. Cheers.

**Comment by JamesBarwell** [comment] 2015-09-24 14:16
Confirmed that this was an error with our approach to scripting, and to the structure of our environment. The complication was that we had multiple versioned services linking to each other and our script wasn't clever enough. It would create a definition for the original state and the final state (as seen in my previous comment), but this meant that the first service to be upgraded from v1 to v2 couldn't see upgraded v2 services to link to, so it dropped the links.

We now do not link any two versioned services, i.e. we only connect through unversioned load-balancers. This avoids having to introduce a lot of complexity in our script, as the load-balancer links get auto-updated as part of the upgrade.

**Comment by deniseschannon** [comment] 2015-10-08 16:32
@sangeethah Merged in our forked branch of Libcompose.
https://github.com/docker/libcompose/pull/65

**Comment by deniseschannon** [comment] 2015-10-09 20:05
@ibuildthecloud Taking @vincent99 docker-compose.yml doesn't work when you do a `rancher-compose create`. Links are still not made in the UI.

**Comment by deniseschannon** [comment] 2015-10-21 20:26
Unable to use the docker-compose.yml file to do a `rancher-compose create` using rancher-compose-v0.4.3. The merged code in libcompose did not resolve the issue.

**Comment by deniseschannon** [comment] 2015-10-22 19:28
Verified with Master with version/commit 4cd0088.

Will be released in the next version of rancher-compose.

**Closed by deniseschannon** 2015-10-22 19:28 UTC
Labels: area/rancher-compose, kind/bug, status/blocker, status/reopened
