### ISSUE TITLE
Add SLE BCI image for istio-installer

### ISSUE THREAD

**Issue by rayandas** [rancher/rancher#35704] opened 2021-12-01 08:13 UTC
Add SLE BCI image in Dockerfile of istio-installer (https://github.com/rancher/istio-installer)

**Comment by rayandas** [comment] 2022-02-18 06:26
We need to create a new tag from master. (e.g.: `1.11.4-rancher2`)

**Comment by rayandas** [comment] 2022-02-21 05:14
Testing steps:
https://github.com/rancher/istio-installer#manual-tests
Use the latest image `1.11.4-rancher2` to test the changes. Also test Istio using the normal test plan to validate everything.
cc: @rishabhmsra

**Comment by rishabhmsra** [comment] 2022-02-21 12:26
Tried validating this on rancher v2.6-head (e55a04c) but could not proceed because of the issue #36588.

Rancher Server:
- v2.6-head (e55a04c)
- docker install

Validation steps :
- Created a AWS node driver downstream cluster (1-cp, 1-etcd, 2-worker).
- Rancher server got crashed and became inaccessible #36588.
- Also tried creating custom cluster using (1-cp, 1-etcd, 2-worker), but after running the registration commands on nodes Rancher server got crashed with same error.

**Comment by rishabhmsra** [comment] 2022-02-24 13:08
**Re-opening this issue :**

The manual testing step mentioned [here](https://github.com/rancher/rancher/issues/35704#issuecomment-1046482389) is failing for this [test case](https://github.com/rancher/istio-installer#test-image-mirror-works-in-rancher-istio-chart).

**Rancher Server :**
- v2.6-head(8c785a1)
- docker install

**Steps to reproduce :**
- Provision AWS node driver cluster `(1-cp, 1-etcd, 2-worker)`, using k8s `v1.22.6-rancher1-2`
- Install monitoring `100.1.1+up19.0.3` chart
- Install Istio `100.1.2+up1.11.4`, enable Kiali, Jaeger and Egress gateway.
- Follow the steps mentioned [here](https://github.com/rancher/istio-installer#test-image-mirror-works-in-rancher-istio-chart).
- The chart update fails.
- istioctl logs:
```
setting up kubeconfig
Switched to context "rancher-istio-context".
generating ssl certs
Generating a RSA private key
..........................+++++
...........+++++
writing new private key to '/etc/ssl/private/github.com.key'
-----
running nginx
2022/02/24 11:56:58 [notice] 52#52: using the "epoll" event method
2022/02/24 11:56:58 [notice] 52#52: nginx/1.19.8
2022/02/24 11:56:58 [notice] 52#52: built by gcc 7.5.0 (SUSE Linux)
2022/02/24 11:56:58 [notice] 52#52: OS: Linux 5.11.0-1022-aws
2022/02/24 11:56:58 [notice] 52#52: getrlimit(RLIMIT_NOFILE): 1048576:1048576
2022/02/24 11:56:58 [notice] 53#53: start worker processes
2022/02/24 11:56:58 [notice] 53#53: start worker process 54
2022/02/24 11:56:58 [notice] 53#53: start worker process 55
2022/02/24 11:56:58 [notice] 53#53: start worker process 56
2022/02/24 11:56:58 [notice] 53#53: start worker process 57
starting sleep for 30 seconds
starting istioctl commands
client version: 1.11.4
control plane version: 1.11.4
Info [IST0102] (Namespace istio-system) The namespace is not enabled for Istio injection. Run 'kubectl label namespace istio-system istio-injection=enabled' to enable it, or 'kubectl label namespace istio-system istio-injection=disabled' to explicitly mark it as not needing injection.
Info [IST0118] (Service jaeger-collector.istio-system) Port name jaeger-collector-grpc (port: 14250, targetPort: 14250) doesn't follow the naming convention of Istio port.
Info [IST0118] (Service jaeger-collector.istio-system) Port name jaeger-collector-http (port: 14268, targetPort: 14268) doesn't follow the naming convention of Istio port.
running istioctl upgrade
2022-02-24T11:57:32.033596Z info proto: tag has too few fields: "-"
Control Plane - istio-egressgateway pod - istio-egressgateway-7b8554fc78-bmpwq - version: 1.11.4
Control Plane - istio-ingressgateway pod - istio-ingressgateway-5659c66658-dndh8 - version: 1.11.4
Control Plane - istiod pod - istiod-5b4d98d68d-7hvwd - version: 1.11.4
Upgrade version check passed: 1.11.4 -> 1.11.4.
2022/02/24 11:57:32 [error] 54#54: *1 open() "/opt/istio-releases/1.11.4/istio-1.11.4-linux-amd64.tar.gz" failed (2: No such file or directory), client: 127.0.0.1, server: github.com, request: "GET /istio/istio/releases/download/1.11.4/istio-1.11.4-linux-amd64.tar.gz HTTP/1.1", host: "github.com"
127.0.0.1 - - [24/Feb/2022:11:57:32 +0000] "GET /istio/istio/releases/download/1.11.4/istio-1.11.4-linux-amd64.tar.gz HTTP/1.1" 404 125 "-" "Go-http-client/1.1"
2022/02/24 11:57:32 [info] 54#54: *1 client 127.0.0.1 closed keepalive connection
2022-02-24T11:57:32.530810Z info Error: failed to generate Istio configs from file [/app/istio-base.yaml] for the current version: 1.11.4, error: failed to fetch URL https://github.com/istio/istio/releases/download/1.11.4/istio-1.11.4-linux-amd64.tar.gz : 404 Not Found
Error: failed to generate Istio configs from file [/app/istio-base.yaml] for the current version: 1.11.4, error: failed to fetch URL https://github.com/istio/istio/releases/download/1.11.4/istio-1.11.4-linux-amd64.tar.gz : 404 Not Found
error found during istioctl upgrade
```


**Note :** Tested below scenarios for istio `100.1.2+up1.11.4` and it's working as expected.
- Fresh install checks
- Upgrade istio from 100.1.1+up1.11.4 —> 100.1.2+up1.11.4 (after upgrade deployed book app and validated traffic and traces through kiali and jaeger)
- Upgrade with custom overlay
- Kiali
- Jaeger traces
- Reinstall with Kiali and Jaeger enabled
- Fresh install with modified ingress gateway
- Unistall/reinstall checks
- Istio pointing to externally-installed Prometheus
- Multiple ingress
- Egressgateway
- Validated weighted book demo app.

**Comment by rishabhmsra** [comment] 2022-03-02 12:39
blocked on monitoring chart installation : https://github.com/rancher/rancher/issues/36639#issuecomment-1056878526

**Comment by rishabhmsra** [comment] 2022-03-08 09:19
Re-validated on rancher v2.6-head(f2a4147). Created a k8s `v1.22.6-rancher1-2` cluster -> `4 node(1-cp, 1-etcd, 2-worker)`. Monitoring chart installed successfully. Validated the test steps as mentioned [here](https://github.com/rancher/rancher/issues/35704#issuecomment-1046482389), it's working as expected, hence closing the issue.

**Closed** 2022-03-08 14:28 UTC
Labels: kind/task, priority/1, [zube]: QA Working, QA/S, team/area3, team/infracloud
