### ISSUE TITLE
Rancher networking is slow

### ISSUE THREAD

**Issue by yuyi** [rancher/rancher#7907] opened 2017-02-21 18:26 UTC
There are a very big performance gap in Rancher overlay network.

This is my rancher configure:
![image](https://cloud.githubusercontent.com/assets/614797/23178314/e6bc4afa-f8a4-11e6-8a07-4700b1e322c6.png)

Bandwidth between ros-02 <-> ros-03 by private ip
```
iperf3 -c 192.168.133.195
Connecting to host 192.168.133.195, port 5201
[  4] local 10.42.89.41 port 48226 connected to 192.168.133.195 port 5201
[ ID] Interval           Transfer     Bandwidth       Retr  Cwnd
[  4]   0.00-1.00   sec   238 MBytes  1.99 Gbits/sec  6390    900 KBytes
[  4]   1.00-2.00   sec   119 MBytes   996 Mbits/sec  3789    494 KBytes
[  4]   2.00-3.00   sec   118 MBytes   986 Mbits/sec  3146    954 KBytes
[  4]   3.00-4.00   sec   125 MBytes  1.05 Gbits/sec  5455    373 KBytes
[  4]   4.00-5.00   sec   110 MBytes   923 Mbits/sec  3194    688 KBytes
[  4]   5.00-6.00   sec   111 MBytes   933 Mbits/sec  7845    790 KBytes
[  4]   6.00-7.00   sec   116 MBytes   975 Mbits/sec  3785    818 KBytes
[  4]   7.00-8.00   sec   119 MBytes   996 Mbits/sec  3756   1.53 MBytes
[  4]   8.00-9.00   sec   125 MBytes  1.05 Gbits/sec  3339    322 KBytes
[  4]   9.00-10.00  sec   119 MBytes   996 Mbits/sec  3276    654 KBytes
- - - - - - - - - - - - - - - - - - - - - - - - -
[ ID] Interval           Transfer     Bandwidth       Retr
[  4]   0.00-10.00  sec  1.27 GBytes  1.09 Gbits/sec  43975             sender
[  4]   0.00-10.00  sec  1.27 GBytes  1.09 Gbits/sec                  receiver

iperf Done.
```

Bandwidth between ros-02 <-> ros-03 by overlay ip
```
iperf3 -c iperf1
Connecting to host iperf1, port 5201
[  4] local 10.42.89.41 port 33482 connected to 10.42.122.98 port 5201
[ ID] Interval           Transfer     Bandwidth       Retr  Cwnd
[  4]   0.00-1.00   sec  56.5 MBytes   474 Mbits/sec  973    354 KBytes
[  4]   1.00-2.00   sec  39.6 MBytes   332 Mbits/sec  1167    962 KBytes
[  4]   2.00-3.00   sec  40.0 MBytes   335 Mbits/sec  4529    266 KBytes
[  4]   3.00-4.00   sec  40.0 MBytes   336 Mbits/sec  2841    673 KBytes
[  4]   4.00-5.00   sec  40.0 MBytes   335 Mbits/sec  3941   2.63 KBytes
[  4]   5.00-6.00   sec  41.2 MBytes   346 Mbits/sec  2610   2.63 KBytes
[  4]   6.00-7.00   sec  43.8 MBytes   367 Mbits/sec  3605   55.3 KBytes
[  4]   7.00-8.00   sec  41.2 MBytes   346 Mbits/sec  2802    675 KBytes
[  4]   8.00-9.00   sec  42.5 MBytes   357 Mbits/sec  4199   22.4 KBytes
[  4]   9.00-10.00  sec  42.5 MBytes   357 Mbits/sec  3283   51.3 KBytes
- - - - - - - - - - - - - - - - - - - - - - - - -
[ ID] Interval           Transfer     Bandwidth       Retr
[  4]   0.00-10.00  sec   427 MBytes   358 Mbits/sec  29950             sender
[  4]   0.00-10.00  sec   425 MBytes   356 Mbits/sec                  receiver

iperf Done.
```

I tried both IPSec and VXLAN. 
Any ideas?

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v1.4.1` Cattle: `v0.176.9` UI: `v1.4.6` |
|Access|`localauth` `admin`|
|Orchestration|`Cattle`|
|Route|`authenticated.project.help`|

**Comment by henrypfhu** [comment] 2017-03-18 16:02
I have same issue.

**Comment by ptcuops** [comment] 2017-03-24 14:34
For reference, I'm seeing different results but interesting for other reasons. In my case, the overlay network seems pretty quick when I'm talking to containers on a different hosts, but much, much slower (although probably still acceptable) when talking to a container on the same host.

Between containers on same host:
```
Connecting to host 10.42.149.99, port 5201
[  4] local 10.42.149.99 port 56606 connected to 10.42.149.99 port 5201
[ ID] Interval           Transfer     Bandwidth       Retr  Cwnd
[  4]   0.00-1.00   sec  5.01 GBytes  43.0 Gbits/sec    0   1.87 MBytes
[  4]   1.00-2.00   sec  4.92 GBytes  42.3 Gbits/sec    0   3.12 MBytes
[  4]   2.00-3.00   sec  4.99 GBytes  42.8 Gbits/sec    0   3.12 MBytes
[  4]   3.00-4.00   sec  5.00 GBytes  43.0 Gbits/sec    0   3.12 MBytes
[  4]   4.00-5.00   sec  4.92 GBytes  42.2 Gbits/sec    0   3.12 MBytes
[  4]   5.00-6.00   sec  4.85 GBytes  41.7 Gbits/sec    0   3.12 MBytes
[  4]   6.00-7.00   sec  5.05 GBytes  43.4 Gbits/sec    0   3.12 MBytes
[  4]   7.00-8.00   sec  5.02 GBytes  43.1 Gbits/sec    0   3.12 MBytes
[  4]   8.00-9.00   sec  4.98 GBytes  42.8 Gbits/sec    0   3.12 MBytes
[  4]   9.00-10.00  sec  4.94 GBytes  42.4 Gbits/sec    0   3.12 MBytes
- - - - - - - - - - - - - - - - - - - - - - - - -
[ ID] Interval           Transfer     Bandwidth       Retr
[  4]   0.00-10.00  sec  49.7 GBytes  42.7 Gbits/sec    0             sender
[  4]   0.00-10.00  sec  49.7 GBytes  42.7 Gbits/sec                  receiver
```
Between containers on different hosts:
```
Connecting to host 10.42.149.99, port 5201
[  4] local 10.42.148.2 port 39724 connected to 10.42.149.99 port 5201
[ ID] Interval           Transfer     Bandwidth       Retr  Cwnd
[  4]   0.00-1.00   sec  60.2 MBytes   505 Mbits/sec   46    270 KBytes
[  4]   1.00-2.00   sec  59.2 MBytes   497 Mbits/sec    0    397 KBytes
[  4]   2.00-3.00   sec  61.1 MBytes   513 Mbits/sec    0    497 KBytes
[  4]   3.00-4.00   sec  61.0 MBytes   512 Mbits/sec    0    577 KBytes
[  4]   4.00-5.00   sec  58.5 MBytes   491 Mbits/sec    0    646 KBytes
[  4]   5.00-6.00   sec  62.5 MBytes   524 Mbits/sec   18    525 KBytes
[  4]   6.00-7.00   sec  60.4 MBytes   506 Mbits/sec    0    602 KBytes
[  4]   7.00-8.00   sec  62.2 MBytes   522 Mbits/sec   11    512 KBytes
[  4]   8.00-9.00   sec  61.5 MBytes   516 Mbits/sec   10    451 KBytes
[  4]   9.00-10.00  sec  61.4 MBytes   515 Mbits/sec    0    541 KBytes
- - - - - - - - - - - - - - - - - - - - - - - - -
[ ID] Interval           Transfer     Bandwidth       Retr
[  4]   0.00-10.00  sec   608 MBytes   510 Mbits/sec   85             sender
[  4]   0.00-10.00  sec   607 MBytes   509 Mbits/sec                  receiver
```

This was in AWS. All hosts were the same size and on the same private subnet.

**Comment by vincent99** [comment] 2017-03-24 16:03
@ptcuops You know it says **gigabits** for the same host output, right?

**Comment by daymien** [comment] 2017-07-21 01:03
I have the same issue. Can't use the available bandwidth minus ~15% in the overlay network. Just about 45-50% oft 1Gbit/sec

Results between r01 <-> r02 overlay IP is around 450/MBits/sec in controled dedicated 1GBit fullduplex environment hosts and switch with 40GBit/sec backplane.

r01 <-> r02 private IP is 980 MBit/sec

Bandwith d01 <-> d01 (same host) overlay IP is 10Gbit/sec as virtual eth devices are configured.

Currently this issue is the limiting factor in applications performance. The issue is host related. The overall performance between to host is limitited to arround 450Mbit/sec even with 10Gbit/sec net cards. Interisting part is that softinterupts are quite high during the tests.

**Comment by leodotcloud** [comment] 2017-07-21 01:04
> Interisting part is that softinterupts are quite high during the tests.
can you please share more details on this?

**Comment by daymien** [comment] 2017-07-21 01:10
@leodotcloud I'm going to do more tests the upcomimg week and share my results. Thx

**Comment by leodotcloud** [comment] 2017-08-17 06:21
Ping @daymien.

**Comment by daymien** [comment] 2017-08-22 19:20
In the meanwhile I switched form IPSEC to VXLAN overlay network.
This gave us about 60-65% of the 1 Gbit/s and further research lead me to softirq balancing with `/proc/irq/$irq/smp_affinity` We now use [irqbalance](https://github.com/Irqbalance/irqbalance) daemon to balance the network related soft interrupts to multiple CPUs. It looks like this is not installed per default on Ubuntu 16.04 LTS.

This topic is related to the iptables/netfilter implementation of the kernel network stack and goes down to device driver level of the network card. You'll find a very good article about this topic here: [https://www.privateinternetaccess.com/blog/2016/01/linux-networking-stack-from-the-ground-up-part-1/](https://www.privateinternetaccess.com/blog/2016/01/linux-networking-stack-from-the-ground-up-part-1/) 

Right know we get about 90% of the 1 Gbit/s and this is good enough for our purpose.  
I'm not sure anymore if this issue is related to rancher networking implementation at all. 

It looks like an issue on OS configuration and network driver level.
It would be great if someone could verify my assumption on this topic.

**Comment by sirius1024** [comment] 2017-09-18 06:03
same here. really bad network

**Comment by willtcarey** [comment] 2017-09-20 17:29
We're having the same issue over here. Rancher v1.6.7 using IPSec for networking.

Host <-> Host communication
```
host to host
Connecting to host 192.241.190.69, port 5201
[  4] local 162.243.25.227 port 37392 connected to 192.241.190.69 port 5201
[ ID] Interval           Transfer     Bandwidth       Retr  Cwnd
[  4]   0.00-1.00   sec   121 MBytes  1.01 Gbits/sec    2    438 KBytes
[  4]   1.00-2.00   sec   169 MBytes  1.42 Gbits/sec    0    662 KBytes
[  4]   2.00-3.00   sec   160 MBytes  1.35 Gbits/sec   18    634 KBytes
[  4]   3.00-4.00   sec   161 MBytes  1.35 Gbits/sec    0    806 KBytes
[  4]   4.00-5.00   sec   180 MBytes  1.51 Gbits/sec   56    758 KBytes
[  4]   5.00-6.00   sec   173 MBytes  1.45 Gbits/sec   53    724 KBytes
[  4]   6.00-7.00   sec   168 MBytes  1.41 Gbits/sec    4    689 KBytes
[  4]   7.00-8.01   sec   176 MBytes  1.47 Gbits/sec   57    650 KBytes
[  4]   8.01-9.00   sec   163 MBytes  1.38 Gbits/sec   28    615 KBytes
[  4]   9.00-10.00  sec   203 MBytes  1.71 Gbits/sec   24    618 KBytes
- - - - - - - - - - - - - - - - - - - - - - - - -
[ ID] Interval           Transfer     Bandwidth       Retr
[  4]   0.00-10.00  sec  1.64 GBytes  1.41 Gbits/sec  242             sender
[  4]   0.00-10.00  sec  1.63 GBytes  1.40 Gbits/sec                  receiver
```

container <-> container
```
Connecting to host 10.42.164.238, port 5201
[  4] local 10.42.141.153 port 39704 connected to 10.42.164.238 port 5201
[ ID] Interval           Transfer     Bandwidth       Retr  Cwnd
[  4]   0.00-1.00   sec  25.7 MBytes   215 Mbits/sec   24    129 KBytes
[  4]   1.00-2.00   sec  27.4 MBytes   230 Mbits/sec   35    149 KBytes
[  4]   2.00-3.00   sec  22.1 MBytes   186 Mbits/sec   34    149 KBytes
[  4]   3.00-4.00   sec  19.5 MBytes   164 Mbits/sec   68    116 KBytes
[  4]   4.00-5.00   sec  22.3 MBytes   187 Mbits/sec   28    136 KBytes
[  4]   5.00-6.00   sec  18.8 MBytes   158 Mbits/sec   61    116 KBytes
[  4]   6.00-7.00   sec  18.5 MBytes   155 Mbits/sec   34    167 KBytes
[  4]   7.00-8.00   sec  21.4 MBytes   180 Mbits/sec   77    146 KBytes
[  4]   8.00-9.00   sec  20.0 MBytes   168 Mbits/sec   23    192 KBytes
[  4]   9.00-10.00  sec  24.3 MBytes   204 Mbits/sec  118   75.1 KBytes
- - - - - - - - - - - - - - - - - - - - - - - - -
[ ID] Interval           Transfer     Bandwidth       Retr
[  4]   0.00-10.00  sec   220 MBytes   185 Mbits/sec  502             sender
[  4]   0.00-10.00  sec   220 MBytes   184 Mbits/sec                  receiver
```

We're losing nearly 90% of our bandwidth when communicating between containers

And we did a final test of container <-> host
```
Connecting to host 192.241.190.69, port 5201
[  4] local 10.42.164.238 port 45986 connected to 192.241.190.69 port 5201
[ ID] Interval           Transfer     Bandwidth       Retr  Cwnd
[  4]   0.00-1.00   sec   102 MBytes   853 Mbits/sec   66    377 KBytes
[  4]   1.00-2.00   sec   158 MBytes  1.32 Gbits/sec    0    610 KBytes
[  4]   2.00-3.00   sec   126 MBytes  1.05 Gbits/sec    2    567 KBytes
[  4]   3.00-4.00   sec   133 MBytes  1.12 Gbits/sec   22    515 KBytes
[  4]   4.00-5.00   sec   123 MBytes  1.03 Gbits/sec    0    668 KBytes
[  4]   5.00-6.00   sec  88.8 MBytes   745 Mbits/sec    7    583 KBytes
[  4]   6.00-7.00   sec   141 MBytes  1.18 Gbits/sec   14    555 KBytes
[  4]   7.00-8.00   sec   158 MBytes  1.32 Gbits/sec    3    547 KBytes
[  4]   8.00-9.00   sec   112 MBytes   943 Mbits/sec    0    678 KBytes
[  4]   9.00-10.00  sec   114 MBytes   960 Mbits/sec   22    617 KBytes
- - - - - - - - - - - - - - - - - - - - - - - - -
[ ID] Interval           Transfer     Bandwidth       Retr
[  4]   0.00-10.00  sec  1.23 GBytes  1.05 Gbits/sec  136             sender
[  4]   0.00-10.00  sec  1.22 GBytes  1.05 Gbits/sec                  receiver
```

The loss of bandwidth is less severe but still losing nearly 1/3rd of it.

We initially noticed this by having a containerized database inside Rancher and seeing a definite drop in performance when app containers were communicating with it vs having an externally hosted database.

**Comment by jimaek** [comment] 2017-11-08 16:33
Same problem. Is this going to be addressed by Rancher 2 at least?

**Comment by loganhz** [comment] 2018-10-12 02:27
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.

**Closed by loganhz** 2018-10-12 02:27 UTC
Labels: area/networking, kind/bug, kind/performance, version/1.6
