### ISSUE TITLE
vSphere Node Template -> Deploy from template: Content Library -> "Name" -> items not showing..

### ISSUE THREAD

**Issue by hornet83** [rancher/rancher#32570] opened 2021-05-06 07:45 UTC
**What kind of request is this (question/bug/enhancement/feature request):**
bug / question

**Steps to reproduce (least amount of steps as possible):**
Rancher v2.5.7
vSphere v7.0.0

In vSphere:
1. Create a new Content Library, in our case we used "Frames UBUNTU 2004" as name
2. Import the following item "https://cloud-images.ubuntu.com/focal/current/focal-server-cloudimg-amd64.ova"
3. I also manually create a VM from that ova, never turned it on and converted it to a template which was loaded into the same content Library
4. I also loaded another item: https://cloud-images.ubuntu.com/focal/current/focal-server-cloudimg-amd64.vmdk - just to test everything

In Rancher:
1. Create a new Node Template with the vSphere Node Driver
2. Select a vSphere Cloud Provider that connects to vSphere with the previously setup Content Library
3. Creation Method: "Deploy from template: Content Library"
4. Select the Content Library
5. The Library Template should be empty and not showing the vmdk, ova or vm template

**Result:**
We can't use the Content Library feature for deployments, which makes it much harder to automate the template management.

**Other details that may be helpful:**

**Environment information**
- Rancher version: 2.5.7
- Installation option: HA - 3 VMs on RKE
- vSphere Version: 7.0.0

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported):
- Machine type (cloud/VM/metal) and specifications (CPU/memory):
- Kubernetes version (use `kubectl version`):

```
(paste the output here)
```

- Docker version (use `docker version`):

```
(paste the output here)
```

**Comment by janeczku** [comment] 2021-05-06 11:23
Thanks for the report @hornet83. Can you confirm whether the VM template stored in the Content Library is showing when you select the creation method `Deploy from template: Datacenter` ?

**Comment by hornet83** [comment] 2021-05-06 13:44
Hi, yes it is showing there. Not sure if it gets that from the CL though, as that template is just sitting in a vm folder and the CL is a link to it, from how I understand it.

**Comment by janeczku** [comment] 2021-05-06 14:27
@hornet83  I am closing this as duplicate of https://github.com/rancher/rancher/issues/32120
Please subscribe to that issue to follow along.

**Closed by janeczku** 2021-05-06 14:27 UTC
