### ISSUE TITLE
rancher doesnt detect chart updates on harbor

### ISSUE THREAD

**Issue by aemneina** [rancher/rancher#23540] opened 2019-10-18 11:39 UTC
**What kind of request is this (question/bug/enhancement/feature request):**
bug

**Steps to reproduce (least amount of steps as possible):**
1. update a chart on a harbor hosted helm repo
2. click refresh on the catalog within rancher

**Result:**
Rancher doesnt detect a hash change on harbor side, so doesnt think there are any new changes to pull. The workaround was to delete the local caches and pull again. Not sure if there are any better work arounds but thats tough in terms of having an automated process.

**Comment by izaac** [comment] 2019-12-10 20:50
Rancher version: `2.4 master-head (12/10/2019)`
Rancher version: `2.3.0`
Harbor Version: `v1.9.3-c80751b8`

I tried this by creating a public repo with one helm chart. Pushing new versions and updating from the Rancher catalog UI at Global level.

I wasn't able to reproduce.

**Comment by brendarearden** [comment] 2019-12-16 20:50
**Status Update**: We have added debug logging to help troubleshoot issues with helm charts. We are still working to track down this specific issue so this will remain open until we gather additional information.

**Comment by maggieliu** [comment] 2019-12-31 21:27
Status Update: Since the ZD ticket is closed & we cannot reproduce, moving this issue to unschedule, until customer creates another ZD ticket.

**Comment by izaac** [comment] 2023-02-22 02:29
Please open a new issue if a new ZD is created.

**Closed by izaac** 2023-02-22 02:29 UTC
Labels: area/catalog, internal, status/more-info, [zube]: Unscheduled, team/mapps
