### ISSUE TITLE
Cloning a service doesn't clone all of its labels

### ISSUE THREAD

**Issue by gordontyler** [rancher/rancher#2875] opened 2015-12-02 15:55 UTC
I have a service created using rancher-compose that has a "io.rancher.container.hostname_override: container_name" label defined in the compose file. When I clone this service in the Rancher UI and inspect the resulting config, the cloned service does not include that label.

--
Rancher	v0.44.0
Cattle	v0.107.0
User Interface	v0.65.0
Rancher Compose	v0.5.1

**Comment by deniseschannon** [comment] 2015-12-02 16:37
Duplicate of https://github.com/rancher/rancher/issues/2342

Should fixed with this: https://github.com/rancher/rancher/issues/2550

**Closed by deniseschannon** 2015-12-02 16:37 UTC

**Comment by gordontyler** [comment] 2015-12-02 17:08
Thanks. I saw #2342 when searching but it didn't click in my brain that it was related.
