### ISSUE TITLE
Local k3s upgrade should not be allowed on single node install

### ISSUE THREAD

**Issue by anupama2501** [rancher/rancher#30977] opened 2021-01-25 19:02 UTC
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
Versions seen: 
**v2.5-ac483705ad321e9bdfc868bcf72a0c6ca167d7e1-head** and **v2.5.5**
1. Spin up a rancher single install on 2.5.5 and 2.5-head
2. Once the rancher is active, from the local cluster, edit and upgrade the k3s to the newer version and save.
3. The local cluster is in updating state forever.

**Result:**
Local cluster upgrading should be disabled.

**Other details that may be helpful:**
https://github.com/rancher/rancher/issues/29412

![Screen Shot 2021-01-25 at 10 53 29 AM](https://user-images.githubusercontent.com/38144301/105752718-815c2000-5efc-11eb-8799-cb8a99f421d1.png)
<img width="1383" alt="Screen Shot 2021-01-25 at 10 40 02 AM" src="https://user-images.githubusercontent.com/38144301/105752731-85883d80-5efc-11eb-9541-5952a96eccbd.png">
<img width="1304" alt="Screen Shot 2021-01-25 at 10 39 46 AM" src="https://user-images.githubusercontent.com/38144301/105752884-b5374580-5efc-11eb-984f-7f80f77b308c.png">

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): v2.5-ac483705ad321e9bdfc868bcf72a0c6ca167d7e1-head and v2.5.5
- Installation option (single install/HA): Single

Component | Version
Rancher | v2.5.5
User Interface | v2.5.4
Helm | v2.16.8-rancher1
Machine | v0.15.0-rancher49

Rancher | v2.5-ac483705ad321e9bdfc868bcf72a0c6ca167d7e1-head
User Interface | v2.5-dev
Helm | v2.16.8-rancher1
Machine | v0.15.0-rancher49

**Comment by hornbech** [comment] 2021-01-27 09:30
I see this problem as well... It just keeps running a ugprading cycle

**Comment by cbron** [comment] 2021-02-03 23:21
As linked in description, this looks like a regression of: https://github.com/rancher/rancher/issues/29412

**Comment by hornbech** [comment] 2021-02-04 07:24
@cbron looks like it. 

But how do I set it back to the original version, so it dosen 't enter the endless upgrade loop?

**Comment by cbron** [comment] 2021-02-04 15:30
@hornbech I haven't looked into this specific case yet but there are some comments on the various issues about solving it.
Otherwise you can always try reloading from a backup.

**Comment by rmweir** [comment] 2021-02-05 00:05
I believe this problem is specific to embedded k3s that comes with docker installs, as was https://github.com/rancher/rancher/issues/29412. It seems like it may be related to the UI, I don't see anything that would caused that is different in the backend. When I run a docker install of v2.5.5, then set `ui-offline-preferred` to false, then set `ui-index` to `https://releases.rancher.com/ui/2.5.3/index.html`, upgrade options no longer appear. My assumption is that the UI used to check if the cluster had a k3sConfig (the embedded cluster does not on startup), but no longer does so the upgrade options appear. Once submitted the cluster does have this field.

**Comment by sowmyav27** [comment] 2021-02-10 04:44
**On master-head - commit id: `eac20a5ee` and 2.5-head - commit id: `761c805d`**

- Local cluster --> Edit --> K8s version dropdown is not available.

**Comment by cbron** [comment] 2021-04-05 17:58
https://github.com/rancher/rancher/issues/29412#issuecomment-813526642

**Comment by gaktive** [comment] 2021-04-05 18:19
Even though this is listed as a UI issue, it's possible Ricky may be able to sort out something on the backend.

**Comment by westlywright** [comment] 2021-04-07 21:14
The UI fix for clusters that have a `null` `k3sConfig` (only way to tell this is a docker installed cluster) have been merged. K3s clusters that meet this criteria will no longer see the cluster options section that allows  users to change the version, drain options, and concurrency options. The user can still save the cluster to change fields not on the `k3sConfig`. 

I believe there are some backend changes incoming as well that will prevent editing a null config at the api level as well. @rmweir is this correct?

**Comment by rmweir** [comment] 2021-04-09 00:01
**Testing:**
Will want to make sure the option to upgrade does not appear in the UI and that it is not possible to add a k3sConfig to an embedded cluster through the API.

**Comment by thehejik** [comment] 2021-04-09 12:52
**Test report:**
* I was able reproduce the issue on rancher:2.5.5 (infinite loop of upgrades)

* Fix validated on singlenode docker k3s deployment by using image `rancher/rancher:v2.5-head` commit `9b0058c` (docker image id: `88ba240394dc`)

**UI Test:**
The option for k8s upgrade disappeared from Edit Cluster Dialog:
- **Before** (2.5.5): ![k3s_k8s_versions_255](https://user-images.githubusercontent.com/12828077/114175611-6bc29800-993a-11eb-8ce6-4b9d98037db0.png)
- **After** (v2.5-head): ![k3s_k8s_versions_25head](https://user-images.githubusercontent.com/12828077/114175625-6feeb580-993a-11eb-81b8-f6e54a69142c.png)
---
**API Test:**
The upgrade over k3sConfig key in API is not possible anymore:
- **Before** (2.5.5):
Request over API Edit:
```
k3sConfig: {
  "kubernetesVersion": "v1.19.9+k3s1",
  "type": "/v3/schemas/k3sConfig"
}
```
Response 200 OK -> infinite loop of upgrade visible in Ember UI
- **After** (v2.5-head):
Request over API Edit:
```
k3sConfig: {
  "kubernetesVersion": "v1.20.5+k3s1",
  "type": "/v3/schemas/k3sConfig"
}
```
Response 422 Error -> Upgrade not triggered:
```
{
"baseType": "error",
"code": "InvalidBodyContent",
"message": "k3sConfig cannot be changed from nil",
"status": 422,
"type": "error"
}
```

@rmweir It works as expected, but I have two questions:
- Is the Error 422 from API when trying upgrade ok?
- Is it desired that the k3sConfig value field is "null" but still editable in API Edit? Shouldn't be the field imutable/inactive instead? ![k3sConfig_value_editable](https://user-images.githubusercontent.com/12828077/114177324-8eee4700-993c-11eb-81f3-81e85c534ec5.png)

**Comment by thehejik** [comment] 2021-04-09 14:07
Also the upgrade is now **not possible** on k3s `rancher/rancher:master-head` commit `698590b` (docker image id: `654ff50c873e`)
* Fields for upgrade over UI not visible anymore
* Upgrade over API:

Request (current k8s version `v1.19.8+k3s1`):
```
k3sConfig: {
  "kubernetesVersion": "v1.20.5+k3s1",
  "type": "/v3/schemas/k3sConfig"
}
```
Response Error 422 -> Upgrade not triggered:
```
{
"baseType": "error",
"code": "InvalidBodyContent",
"message": "k3sConfig cannot be changed from nil",
"status": 422,
"type": "error"
}
```

**Comment by thehejik** [comment] 2021-04-13 07:53
According to Ricky the Error 422 is fine (from Slack). Closing.

**Closed** 2021-04-13 07:53 UTC
Labels: QA/S, [zube]: QA Working, kind/bug-qa, team/ui
