### ISSUE TITLE
Unable to manage users within cluster when assigned role "clusterroletemplatebindings-manage" from CLI

### ISSUE THREAD

**Issue by adingilloRancher** [rancher/rancher#12892] opened 2018-04-19 21:15 UTC
**Rancher versions:**
Master 4/19/210

Steps:
Create a new cluster.
Create a new local user.
Using CLI - Assign local user to the cluster with the role of "clusterroletemplatebindings-manage".
Create a second local user.
Login as user with ability to manager cluster members.
Attempt to assign the second user to the cluster with the role of "Member"
Select save.

Results:
Unable to save.
![screen shot 2018-04-19 at 2 11 18 pm](https://user-images.githubusercontent.com/38012481/39018808-fc248aa0-43db-11e8-93b0-29e7f81c0d8f.png)

**Comment by cjellick** [comment] 2018-04-21 01:57
Duplicate of https://github.com/rancher/rancher/issues/11116 ?

**Comment by deniseschannon** [comment] 2018-04-23 22:03
Closing in favor of https://github.com/rancher/rancher/issues/11116. Will ask to test this use case as part of testing that issue.

**Closed by deniseschannon** 2018-04-23 22:03 UTC
Labels: area/rbac, kind/bug, priority/0, version/2.0
