### ISSUE TITLE
Turn Linode on as default driver

### ISSUE THREAD

**Issue by deniseschannon** [rancher/rancher#21300] opened 2019-07-03 04:00 UTC
Things to check:
* airgapped setups - we will not support linode working for airgapped setups
  - what shows up in the UI when airgapped?
  - will the icon appear? should we move the icon directly into rancher (probably will solve https://github.com/rancher/rancher/issues/20524)?
  - what happens in the logs? will it continually try to get the data?

**Comment by kinarashah** [comment] 2019-07-17 23:14
@alena1108 @deniseschannon 

For airgapped setups - 
- UI shows icon on cluster page only when driver is active, so nothing would show up because driver would be stuck in `downloading` state 

- Icon would show up only if they've set up mirror, currently it is in linode's repo. I'm not sure of the root cause of the above mentioned issue, but we should move it to rancher since we're officially turning it ON by default? 

- yes, it'll continuously try to fetch the url to download binary. they can just deactivate the driver in that case, is that good enough workaround if we document it?

**Comment by alena1108** [comment] 2019-07-22 16:49
As a part of the fix, we have to make sure that it doesn't break airgap and dev local setup. In airgap setup @vincent99 suggested including the driver to the rancher image, similar to how we do Packet.

**Comment by kinarashah** [comment] 2019-07-29 23:20
@alena1108 

The UI code for Linode doesn't follow the same logic as other builtin drivers. It needs to go through the `/meta/proxy` link, this has two benefits: 
- The whitelisted domains mentioned for the driver get respected 
- We can make use of cloud credentials support instead of actual passing of secret data from ui to linode api. 
https://github.com/rancher/ui/blob/master/lib/global-admin/addon/components/cru-cloud-credential/component.js#L188

**Comment by alena1108** [comment] 2019-07-29 23:48
@kinarashah missing UI functionality will be tracked in https://github.com/rancher/rancher/issues/21838

**Comment by alena1108** [comment] 2019-07-29 23:51
The scope of this issue is limited to:

* Making Linode driver enabled in UI by default.
* In airgapped setups, make data to be pulled from cache, with no error is presented in the UI/Rancher server logs

Those should be the steps to validate for qa in order to close the issue. For all other issues found along the way, new bugs have to be opened.

**Comment by jiaqiluo** [comment] 2019-07-30 21:04
> The scope of this issue is limited to:
> - Making Linode driver enabled in UI by default.
> - In airgapped setups, make data to be pulled from cache, with no error is presented in the UI/Rancher server logs

The first part is validated in Rancher:master-head 51769836 
<img width="1451" alt="Screen Shot 2019-07-30 at 2 02 58 PM" src="https://user-images.githubusercontent.com/6218999/62165209-c76a0080-b2d2-11e9-8017-467c7f75c0ea.png">

The second part will be validated when an RC is available

**Comment by jiaqiluo** [comment] 2019-07-31 21:01
per the conversion with @sangeethah : 

For Linode and airgap setups, we don't have to test the driver itself. But we need to make sure that the Linode driver is able to get to “Active” state automatically and that the icon for it is rendered correctly
Previously we were downloading the binary for this driver on request which should not be the case anymore

**Comment by jiaqiluo** [comment] 2019-08-01 00:21
The following tests are done in Rancher: master-head ef42cc4 

- add a Linode node template  
- provision an RKE cluster using the Linode node template 
- scale up the worker-node pool, seeing new instances are created in Linode 
- scale down the worker-node pool, seeing existing instances are deleted in Linode
- set the root password in the Linode node template, make sure we can ssh into the nodes using the password

**Comment by jiaqiluo** [comment] 2019-08-21 18:27
Tested in Rancher:v2.3.0-alpha7

Results:
- see the Linode node drive is active 

<img width="1462" alt="Screen Shot 2019-08-21 at 11 21 38 AM" src="https://user-images.githubusercontent.com/6218999/63457578-2a4c4480-c406-11e9-967d-6972e27fd002.png">

- the Linode's icon shows properly

<img width="1494" alt="Screen Shot 2019-08-21 at 11 21 00 AM" src="https://user-images.githubusercontent.com/6218999/63457730-61baf100-c406-11e9-815d-1fe2b441db69.png">

<img width="1878" alt="Screen Shot 2019-08-21 at 11 26 06 AM" src="https://user-images.githubusercontent.com/6218999/63457868-98910700-c406-11e9-8a23-b6b1b6f89843.png">

**Closed** 2019-08-21 18:39 UTC
Labels: [zube]: To Test, area/air-gapped, area/rke, internal, kind/enhancement, team/ca
