### ISSUE TITLE
Support for docker-compose v2 volumes

### ISSUE THREAD

**Issue by deniseschannon** [rancher/rancher#5714] opened 2016-08-12 21:59 UTC
In rancher-compose, we've added in support for v2 services, but need to add in v2 volumes support.

**Comment by EugenMayer** [comment] 2016-08-31 09:18
what is the current alternative to `volumes` - i guess actually nothing, you just use named volumes as if they would exist, right?

**Comment by tiangolo** [comment] 2016-08-31 14:01
@EugenMayer it'll work if you just name your volumes, but the volumes will be in the specific host that ran your container. 

Also, container names in Rancher are prefixed with `r-` and the name of the stack, so if you have a service `web` in a stack `myproject` it will be renamed to something like `r-myproject_web_1`. That's very similar to what Docker Compose does. But Rancher won't use that same kind of namespace for your volumes, it won't namespace them at all. So if you name your volume `data`, and different services in different stacks have a volume `data` they will all share the same volume. 

My suggestion is to namespace the volumes yourself, with something like the name of the project, name of service and name of volume.

Also, if you want to use Docker Compose V2 in development and convert it to V1 for Rancher you can try this program (although it's still in aplha), it will also remove `build` options and make sure you have an `image` option in each service: https://pypi.python.org/pypi/compose-to-rancher

**Comment by EugenMayer** [comment] 2016-08-31 16:20
@tiangolo thank you

> So if you name your volume data, and different services in different stacks have a volume data they will all share the same volume.
> My suggestion is to namespace the volumes yourself, with something like the name of the project, name of service and name of volume.

thats very worrying though. If i have a project and i want to run 4 stacks on my rancher, i am screwed since preifxing data_myproject works, but since its static, it will be shared, right? Thats a huge deal breaker, or i misunderstood you?

**Comment by EugenMayer** [comment] 2016-08-31 16:24
i just confirmed it and you are right, those volume names are not prefixed. If that did yet not change with 1.2.0 this is not like a bummer, this is a reason to uninstall rancher since it is basically useless for me. How did i happen to see that only now

**Comment by sangeethah** [comment] 2016-10-05 17:21
Rancher compose Version: rancher-compose-v0.11.0-rc1 has support for docker-compose v2 volumes .
Issues found when testing this feature are tracked as separate issues. Some of them found so far:
https://github.com/rancher/rancher/issues/6138
https://github.com/rancher/rancher/issues/6140
https://github.com/rancher/rancher/issues/6141
https://github.com/rancher/rancher/issues/6142
https://github.com/rancher/rancher/issues/6144
https://github.com/rancher/rancher/issues/6146

**Closed by sangeethah** 2016-10-05 17:21 UTC
Labels: area/cli, area/rancher-compose, kind/enhancement, status/resolved, status/to-test

**Comment by EugenMayer** [comment] 2016-10-05 17:27
Those are great news, thank you a lot!

**Comment by tiangolo** [comment] 2016-10-05 17:39
Excellent!
