### ISSUE TITLE
rancher-compose have a status option

### ISSUE THREAD

**Issue by mrproper** [rancher/rancher#3620] opened 2016-02-16 01:45 UTC
pr to have rancher-compose also have a status of the stack to see both the individual service health and the overall stack health

**Comment by mrproper** [comment] 2016-02-16 01:46
also a non 0 exit code if the overall stack health is not healthy

**Comment by tombmurphy** [comment] 2016-02-16 01:48
+1

**Comment by andyshinn** [comment] 2016-02-17 02:01
Possible duplicate of https://github.com/rancher/rancher/issues/2958.

**Comment by deniseschannon** [comment] 2016-02-22 05:27
Similar to #2958, but it sounds like it would be an individual command to check on services/stack status

**Comment by deniseschannon** [comment] 2016-08-22 20:21
Instead of adding this into Rancher Compose, we recommend using the new [Rancher CLI](http://docs.rancher.com/rancher/cli/) which supports `rancher stacks`, which would show the stack status and `rancher ps` would show service status. 

```
$ rancher stacks
ID           NAME      STATE     CATALOG   SYSTEM    DETAIL
1e364     Default   healthy             false     
$ rancher ps
rancher ps
ID           TYPE      NAME           IMAGE            STATE     SCALE     ENDPOINTS   DETAIL
1s722     service   Default/test   ubuntu:14.04.3   healthy  
```

**Closed by deniseschannon** 2016-08-22 20:21 UTC
Labels: area/rancher-compose, kind/enhancement
