### ISSUE TITLE
Remove deprecated setting rancher-webhook-min-version

### ISSUE THREAD

**Issue by maxsokolovsky** [rancher/rancher#41561] opened 2023-05-15 18:04 UTC
**Is your feature request related to a problem? Please describe.**
The `rancher-webhook-min-version` setting must no longer be functional and thus needs to be removed.

**Describe the solution you'd like**
Remove the setting and any handling code from rancher/rancher.

**Describe alternatives you've considered**
In addition, we might want to remove the setting resource from etcd on initial Rancher startup.

**Additional context**
Instead of `rancher-webhook-min-version`, there is already `rancher-webhook-version`.

**Comment by JonCrowther** [comment] 2023-09-05 14:58
# Validation

## Root Cause

The setting `rancher-webhook-min-version` was set to be deprecated 2 minor versions ago and is set to be removed. 

## What was fixed, or what change has occurred

The `rancher-webhook-min-version` setting has been removed. It can no longer be found in the Global Settings, and can't be set via command line option when building rancher.

## Areas or cases that should be tested

Create a rancher instance and see that the `rancher-webhook-min-version` option is not present.

## What areas could experience regressions

The most likely issue is if any testing setups were making use of the `rancher-webhook-min-version` setting to specify a webhook version for testing. They will need to be changed to just make use of `rancher-webhook-version` instead.

## Are the repro steps accurate/minimal?

Yes

**Comment by dasarinaidu** [comment] 2023-10-13 17:29
Validated this issue on `v2.8-6376016a309a166c50fe6203b2e97dae0b90c89c-head` ; I am seeing below observations.

**Observation 1: Downstream clusters always created with Latest Version of Webhook only**

**Scenario 1:**
1. Provision rancher (v2.8-head)
2. Check for the local webhook version (Currently it is `rancher/rancher-webhook:v0.4.0-rc10)`
3. Downgrade the webhook version to `rancher/rancher-webhook:v0.3.6`
4. Create a downstream cluster
5. Check for the webhook version it is installed with `rancher/rancher-webhook:v0.4.0-rc10)`

**Scenario 2:**
1. Provision rancher (v2.7.8)
2. Check for the local webhook version (Currently it is `rancher/rancher-webhook:v0.3.6)`
3. Upgrade the rancher to v2.8-head by passing the `CATTLE_RANCHER_WEBHOOK_VERSION=2.0.6+up0.3.6`
4. Check for local webhook version & the webhook version to `rancher/rancher-webhook:v0.3.6`
5. Create a downstream cluster
7. Check for the webhook version it is installed with `rancher/rancher-webhook:v0.4.0-rc10`

**Actual:**
a. In both scenarios the Downstream clusters always created with latest version of webhook only.

**Observation 2: Upgrade rancher : Downstream cluster not installed with CATTLE_RANCHER_WEBHOOK_VERSION**

**Steps:**

1. Provision rancher (v2.7.2 any of the 2.7.x)
2. Create a downstream cluster
3. Check for the local & downstream webhook versions (Currently it is `rancher/rancher-webhook:v0.3.2`
4. Upgrade rancher to v2.8-head by passing the webhook version `CATTLE_RANCHER_WEBHOOK_VERSION=2.0.6+up0.3.6`
5. Check for the webhook version on both Local and Downstream clusters

**Actual:**
a. Local clusters webhook version : `rancher/rancher-webhook:v0.3.6`
b. Downstream clusters webhook version : `rancher/rancher-webhook:v0.4.0-rc10`

**Comment by maxsokolovsky** [comment] 2023-10-13 17:53
It's normal when users run main Rancher by specifying `CATTLE_RANCHER_WEBHOOK_MIN_VERSION`, the local cluster has the webhook of that version, while a downstream cluster's webhook has a different one.

The webhook version in the remote cluster is determined by the agent. The agent is like a special Rancher build that runs in the remote cluster. Currently, devs need to manually update the env var in main Rancher Dockerfile and agent's Dockerfile. This will change soon, so the update needs to happen in one place.
When users run main Rancher passing in the env var, only local webhook will be affected. Agent is built and run separately, and its value of the variable is fixed and specified in its Dockerfile.

**Comment by dasarinaidu** [comment] 2023-10-13 18:26
I have completed validations and closing this card. 

Below test cases validated and passed on `v2.8-6376016a309a166c50fe6203b2e97dae0b90c89c-head`:
![image](https://github.com/rancher/rancher/assets/22034884/2dc38a96-d797-4df0-99d6-e4ccc5fd1f34)

**Closed by dasarinaidu** 2023-10-13 18:26 UTC
Labels: kind/enhancement, [zube]: QA Working, QA/S, team/area1
