### ISSUE TITLE
[BUG] v2.8.0-rc1 helm-operation error

### ISSUE THREAD

**Issue by taehwanlee** [rancher/rancher#43183] opened 2023-10-17 04:55 UTC
**Rancher Server Setup**
- Rancher version: v2.8.0-rc1
- Rancher Installation option (Docker install/Helm Chart): Docker
- kubernetes version: eks 1.27
- error message:

![image](https://github.com/rancher/rancher/assets/20853900/889bce8f-9dc7-40a6-ba82-503679355bcb)

**Comment by valaparthvi** [comment] 2023-10-17 05:55
I tested EKS on 2.8.0-alpha2 yesterday, and EKS 1.27 was supported then.

**Comment by taehwanlee** [comment] 2023-10-17 05:57
@valaparthvi Can you install helm like me?

**Comment by valaparthvi** [comment] 2023-10-17 06:14
> @valaparthvi Can not you install helm like me?

Ah, my bad. I used helm to install Rancher but on k3s 1.26.9+k3s1. I thought the issue was about Rancher not supporting the downstream EKS 1.27 version.

**Comment by anupama2501** [comment] 2023-10-17 08:18
@taehwanlee Could you elaborate on the steps? You mentioned the install option is docker but the helm chart is also mentioned. Could you confirm if rancher was installed on an EKS cluster using helm chart or if it was a docker install?

**Comment by anupama2501** [comment] 2023-10-17 16:32
Hello @lukinko thank you for the information. Here's what I tried and not able to reproduce the issue so far. could you tell me if there's something else that you have in your setup other than the steps mentioned below that might be causing the issue:
1. Created a GKE cluster with k8s `v1.27.3-gke.100`
2. Installed rancher by following the docs [here](https://ranchermanager.docs.rancher.com/getting-started/installation-and-upgrade/install-upgrade-on-a-kubernetes-cluster/rancher-on-gke)
3. Did not notice any panics
4. Installed logging v2 chart in the local cluster once the rancher server is active 
5. Chart was installed successfully
6. Created a downstream EKS cluster on k8s `v1.27.6-eks-f8587cb`
7. Installed logging chart v2 and did not notice any errors in the helm pods for this installation as well.

**Comment by taehwanlee** [comment] 2023-10-18 01:11
@anupama2501 Sorry, I installed rancher using docker and am using it by importing the eks service cluster.
When importing the eks cluster into the rancher and installing the chart using helm-operation run within the rancher, an error occurs as shown above.

**Comment by taehwanlee** [comment] 2023-10-18 05:44
As a result of the test, when importing the cluster into Rancher with eks 1.26 => 1.27 upgrade, the following error occurs. However, after creating a new Eks cluster with version 1.27 and importing the cluster into Rancher, the error does not occur. The difference when comparing the two clusters is the version upgrade EKS => 1.27.4 1.27 EKS creation cluster version => 1.27.6

**Comment by anupama2501** [comment] 2023-10-18 13:21
thank you for the info, and also based on the linked ticket seems like a problem with installing charts on hosted clusters.

**Comment by taehwanlee** [comment] 2023-10-19 02:09
If I also remove the monitoring chart and import the eks cluster into the rancher, helm works normally. I found that a problem occurs when I install another chart after installing the monitoring chart.

**Comment by rohitsakala** [comment] 2023-10-19 20:23
@taehwanlee Can you retry to install rancher with v2.8-head rancher image ?

**Comment by taehwanlee** [comment] 2023-10-19 22:26
@rohitsakala As you said, after reinstalling the rancher with v2.8-head, an error still occurs when importing the eks cluster. However, if you remove the monitor chart and register it again, the cluster is registered normally.
![image](https://github.com/rancher/rancher/assets/20853900/8e7bf6cd-f5be-4c72-9716-a29a9663083b)

**Comment by rohitsakala** [comment] 2023-10-19 23:47
@taehwanlee Apologies, the v2.8-head was not updated due to a CI failure. I have now ensured that v2.8-head is updated. Can you test now?

**Comment by taehwanlee** [comment] 2023-10-20 01:32
@rohitsakala exorcism!! If you upgrade to the 2.8-head version you mentioned and import the eks cluster, it will be installed normally without any helm-operation errors! Even if a monitoring chart is installed, errors do not occur! What is the cause?

![image](https://github.com/rancher/rancher/assets/20853900/e4e16919-40f8-4e6e-af95-da928c8877c7)

**Comment by rohitsakala** [comment] 2023-10-20 16:42
@taehwanlee 2.8.0-rc2 will be released soonish and it will have the fix. 

The issue was https://github.com/kubernetes/kubernetes/issues/119840

I am closing this.

**Closed by rohitsakala** 2023-10-20 16:42 UTC
Labels: kind/bug, [zube]: To Test, team/mapps
