### ISSUE TITLE
Machine pools page is not seen on an RKE1 cluster initially during provisioning

### ISSUE THREAD

**Issue by sowmyav27** [rancher/rancher#35641] opened 2021-11-23 06:11 UTC
**Rancher Server Setup**
- Rancher version: 2.6-head `744f32f`
- Installation option (Docker install/Helm Chart): Helm
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): RKE1

**Information about the Cluster**
- Kubernetes version: 1.22.3-rancher1-1
- Cluster Type (Local/Downstream): Azure rke1 cluster

**Describe the bug**
Machine pools page is not seen on an RKE1 cluster initially during provisioning

**To Reproduce**

- Deploy an RKE1 Azure cluster
- Machine pools page isnt available for sometime before its seen in the cluster details page.

<img width="1663" alt="Screen Shot 2021-11-22 at 9 01 35 PM" src="https://user-images.githubusercontent.com/26032343/142978178-e0180bfa-8d29-41f0-8c66-71da5ffe7cc6.png">

**Note:**

- Does not happen always. Tried 2 more times, and did not see this happen
- EDIT on 11/23 
- Hit this issue again.
- View in API of nodepools for this cluster gave me 2 items in Data - `https://url/v1/management.cattle.io.nodepools/c-sb9hc`

**Comment by jakefhyde** [comment] 2021-12-03 23:11
@sowmyav27 ss there anymore info available regarding this issue (what kind of load rancher was under, etc.)? I've provisioned about 20 or so azure rke1 1.22.3 clusters and haven't been able to reproduce this on release/v2.6 yet. I'm going to try on 744f32f as well and see if it is reproducible there and under what circumstances.

**Comment by sowmyav27** [comment] 2021-12-04 23:58
I see this issue on a fully provisioning EKS/AKS cluster also on 2.6.3-rc4

**Comment by jakefhyde** [comment] 2021-12-07 20:04
This was likely a UI issue as it is present in release/2.6 and 2.6.3-rc4:
![release-2 6-no-pools](https://user-images.githubusercontent.com/33796120/145097273-eebcddd8-e5cc-4e15-a4cd-7a049346f1bd.png)
But not in https://github.com/rancher/dashboard/commit/61b7fe935e31493ad140fbb072f154486b4869db:
![dashboard-master-pools](https://user-images.githubusercontent.com/33796120/145097984-881a4f44-dbbc-4fee-a4bc-9e78e4616ca8.png)
Looks like it may have been resolved by this dashboard PR: https://github.com/rancher/dashboard/pull/4713

Note: I spun up a vue frontend pointed at the same rancher instance using `API=`, so the only difference here is the ui.

**Comment by jakefhyde** [comment] 2021-12-08 17:51
Moving to test, however it's important to note this does require using at least  rancher/dashboard@61b7fe9 for the UI.

**Comment by sowmyav27** [comment] 2021-12-09 00:27
**On 2.6-head commit id: `77392a6`**

AKS clusters's machine pools page shows data ![Screen Shot 2021-12-08 at 4.26.50 PM.png](https://zube.io/files/rancher/37954432bb0f520333862ce3fc33f633-screen-shot-2021-12-08-at-4-26-50-pm.png)

**Closed** 2021-12-09 00:27 UTC
Labels: kind/bug-qa, [zube]: QA Next up
