### ISSUE TITLE
rancher-agent screws up iptables

### ISSUE THREAD

**Issue by DanielBodnar** [rancher/rancher#3538] opened 2016-02-05 15:58 UTC
There's a nasty bug in the rancher-agent registration process when it attempts to configure host-iptables that we've run into twice now. 

We're running RHEL 6.6

I'm not entirely sure how or why, but when the [host-iptables/apply.sh](https://github.com/rancher/cattle/blob/master/resources/content/config-content/host-iptables/apply.sh#L13) attempts to assign the MASQ to a variable, it produces something like this:

```
MASQ='-s 172.17.0.0/16 ! -o docker0 -j MASQUERADE
-s 172.17.0.0/16 ! -o docker0 -j MASQUERADE
-s 172.17.0.0/16 ! -o docker0 -j MASQUERADE
-s 172.17.0.0/16 ! -o docker0 -j MASQUERADE
-s 172.17.0.0/16 ! -o docker0 -j MASQUERADE
-s 172.17.0.0/16 ! -o docker0 -j MASQUERADE
-s 172.17.0.0/16 ! -o docker0 -j MASQUERADE'
```

and every time the rancher-agent is ran again, it adds another `-s 172.17.0.0/16 ! -o docker0 -j MASQUERADE` to that, which produces this  [iptables-save](https://gist.github.com/DanielBodnar/8dbe36937e98d9e97c8e):

```
# Generated by iptables-save v1.4.7 on Fri Feb  5 03:38:03 2016
*mangle
:PREROUTING ACCEPT [2677699:382708357]
:INPUT ACCEPT [2642907:360435547]
:FORWARD ACCEPT [34582:22257518]
:OUTPUT ACCEPT [1415284:5834808616]
:POSTROUTING ACCEPT [1449866:5857066134]
COMMIT
# Completed on Fri Feb  5 03:38:03 2016
# Generated by iptables-save v1.4.7 on Fri Feb  5 03:38:03 2016
*filter
:INPUT ACCEPT [54659:20021201]
:FORWARD ACCEPT [0:0]
:OUTPUT ACCEPT [68028:17271989]
:CATTLE_POSTROUTING - [0:0]
:CATTLE_PREROUTING - [0:0]
:DOCKER - [0:0]
-A FORWARD -o docker0 -j DOCKER 
-A FORWARD -o docker0 -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT 
-A FORWARD -i docker0 ! -o docker0 -j ACCEPT 
-A FORWARD -i docker0 -o docker0 -j ACCEPT 
-A DOCKER -d 172.17.0.22/32 ! -i docker0 -o docker0 -p tcp -m tcp --dport 4001 -j ACCEPT 
-A DOCKER -d 172.17.0.1/32 ! -i docker0 -o docker0 -p udp -m udp --dport 4500 -j ACCEPT 
-A DOCKER -d 172.17.0.1/32 ! -i docker0 -o docker0 -p udp -m udp --dport 500 -j ACCEPT 
-A DOCKER -d 172.17.0.4/32 ! -i docker0 -o docker0 -p udp -m udp --dport 4500 -j ACCEPT 
-A DOCKER -d 172.17.0.4/32 ! -i docker0 -o docker0 -p udp -m udp --dport 500 -j ACCEPT 
COMMIT
# Completed on Fri Feb  5 03:38:03 2016
# Generated by iptables-save v1.4.7 on Fri Feb  5 03:38:03 2016
*nat
:PREROUTING ACCEPT [815:64764]
:POSTROUTING ACCEPT [4776:324682]
:OUTPUT ACCEPT [4776:324682]
:CATTLE_POSTROUTING - [0:0]
:CATTLE_PREROUTING - [0:0]
:DOCKER - [0:0]
-A PREROUTING -j CATTLE_PREROUTING 
-A PREROUTING -m addrtype --dst-type LOCAL -j DOCKER 
-A POSTROUTING -s 172.17.0.0/16 ! -o docker0 -j MASQUERADE 
-A POSTROUTING -s 172.17.0.0/16 ! -o docker0 -j MASQUERADE 
-A POSTROUTING -s 172.17.0.0/16 ! -o docker0 -j MASQUERADE 
-A POSTROUTING -s 172.17.0.0/16 ! -o docker0 -j MASQUERADE 
-A POSTROUTING -s 172.17.0.0/16 ! -o docker0 -j MASQUERADE 
-A POSTROUTING -s 172.17.0.0/16 ! -o docker0 -j MASQUERADE 
-A POSTROUTING -s 172.17.0.0/16 ! -o docker0 -j MASQUERADE 
-A POSTROUTING -j CATTLE_POSTROUTING 
-A POSTROUTING -s 172.17.0.0/16 ! -o docker0 -j MASQUERADE 
-A POSTROUTING -s 172.17.0.22/32 -d 172.17.0.22/32 -p tcp -m tcp --dport 4001 -j MASQUERADE 
-A POSTROUTING -s 172.17.0.1/32 -d 172.17.0.1/32 -p udp -m udp --dport 4500 -j MASQUERADE 
-A POSTROUTING -s 172.17.0.1/32 -d 172.17.0.1/32 -p udp -m udp --dport 500 -j MASQUERADE 
-A POSTROUTING -s 172.17.0.4/32 -d 172.17.0.4/32 -p udp -m udp --dport 4500 -j MASQUERADE 
-A POSTROUTING -s 172.17.0.4/32 -d 172.17.0.4/32 -p udp -m udp --dport 500 -j MASQUERADE 
-A OUTPUT ! -d 127.0.0.0/8 -m addrtype --dst-type LOCAL -j DOCKER 
-A CATTLE_POSTROUTING -s 10.42.0.0/16 -d 169.254.169.250/32 -j ACCEPT 
-A CATTLE_POSTROUTING -s 10.42.0.0/16 ! -d 10.42.0.0/16 -p tcp -j MASQUERADE --to-ports 1024-65535 
-A CATTLE_POSTROUTING -s 10.42.0.0/16 ! -d 10.42.0.0/16 -p udp -j MASQUERADE --to-ports 1024-65535 
-A CATTLE_POSTROUTING -s 10.42.0.0/16 ! -d 10.42.0.0/16 -j MASQUERADE 
-A CATTLE_POSTROUTING -s 172.17.0.0/16 ! -o docker0 -p tcp -j MASQUERADE --to-ports 1024-65535 
-A CATTLE_POSTROUTING -s 172.17.0.0/16 ! -o docker0 -p udp -j MASQUERADE --to-ports 1024-65535 
-A CATTLE_PREROUTING -p tcp -m addrtype --dst-type LOCAL -m tcp --dport 443 -j DNAT --to-destination 10.42.42.53:443 
-A DOCKER ! -i docker0 -p udp -m udp --dport 4500 -j DNAT --to-destination 172.17.0.4:4500 
-A DOCKER ! -i docker0 -p udp -m udp --dport 500 -j DNAT --to-destination 172.17.0.4:500 
COMMIT
# Completed on Fri Feb  5 03:38:03 2016
```

I think this is another example: https://github.com/rancher/rancher/issues/3457

We have fixed this by manually running iptables-save and removing all references to cattle, and then re-running the host registration.

**Comment by deniseschannon** [comment] 2016-02-08 19:11
Are you running puppet or something? You might be hitting this issue:

https://github.com/rancher/rancher/issues/2347

**Comment by ibuildthecloud** [comment] 2016-02-08 22:17
@DanielBodnar I believe this commit fixes this issue https://github.com/rancher/cattle/commit/b96d389fe2fd6e1a5268d17678a3c4df2141b672 which will be included in the next Rancher release.

**Comment by ibuildthecloud** [comment] 2016-02-08 22:21
@DanielBodnar Actually I think I misspoke.  I don't think the commit I referred to will fix you issue.  I believe this is caused by a combination of a Docker bug and some logic we have.  The problem though is we don't support RHEL 6.6 because Docker doesn't support it.  I believe this bug has been fixed in newer versions of Docker.

**Comment by deniseschannon** [comment] 2016-02-16 22:31
@DanielBodnar With our latest release (v0.59.0), we will only be supporting Docker 1.9.1+ and will no longer be able to look into issues with older versions of Docker. As these versions of Docker don't support RHEL 6.6, I'll be closing this issue. 

If you upgrade to RHEL 7 and a later version of Docker and still face this issue, please re-open with new details.

https://github.com/rancher/rancher/releases/tag/v0.59.0

**Closed by deniseschannon** 2016-02-16 22:31 UTC
Labels: kind/bug
