### ISSUE TITLE
[SURE-6522] Rancher deployment consuming more memory when tokens generate new kubeconfigs

### ISSUE THREAD

**Issue by gaktive** [rancher/rancher#41890] opened 2023-06-20 21:08 UTC
Internal reference: [SURE-6522](https://jira.suse.com/browse/SURE-6522)
Reported in 2.7.3 & 2.7.4

Issue description:

Rancher deployment increases the Memory amount until OOM kills it. Tested with test image provided as part of instructions, but still in this environment, rancher pods getting crashed every 4 hours. 

![Image](https://github.com/rancher/rancher/assets/11466788/186aa545-d955-4609-863a-a8c9df6c06cf)

It was later determined that an automation script created a lot of tokens (~180k as of writing) by generating a new kubeconfig every 5 minutes. Cleanup underway.

**Comment by rmweir** [comment] 2023-06-22 02:17
Have discussed this else where but it is highly probably that memory usage is caused by script. Will re-evaluate after that has been cleaned up.

**Comment by moio** [comment] 2023-07-18 12:34
Reportedly the issue got addressed after the upgrade to Rancher 2.7.5, closing

**Closed by moio** 2023-07-18 12:34 UTC
