### ISSUE TITLE
Errors relating to renewing fqdn in rancher-server logs.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#16199] opened 2018-10-18 16:16 UTC
Rancher server version - v2.1.1-rc6
Had few DO clusters with few workloads and ingress deployed in them.

Following errors seen in logs:

```
2018/10/17 23:52:27 [ERROR] renew fqdn [] to server [https://api.lb.rancher.cloud/v1] error
```

**Comment by alena1108** [comment] 2018-10-18 16:18
duplicate of https://github.com/rancher/rancher/issues/16194

**Closed by alena1108** 2018-10-18 16:18 UTC
Labels: kind/bug
