### ISSUE TITLE
Rancher failed to find a placement - Better messaging would be helpful

### ISSUE THREAD

**Issue by feliksik** [rancher/rancher#173] opened 2015-03-08 14:26 UTC
Sometimes my containers don't seem to start, or they start incredibly slowly. Even when the image (I think?) was already pulled. 

I do see some error in the server log. I'm not sure if this is related to my problems, but it is maybe important enough to show an error in UI and to have a clear msg in the logs of what it means. 

```
2015-03-08 13:37:07,159 ERROR [:] [] [] [] [cutorService-62] [i.c.p.a.s.ping.impl.PingMonitorImpl ] Failed to get ping from agent [2] count [3] 
2015-03-08 13:37:07,160 ERROR [:] [] [] [] [cutorService-76] [i.c.p.a.s.ping.impl.PingMonitorImpl ] Failed to get ping from agent [3] count [3] 
2015-03-08 13:37:12,158 ERROR [:] [] [] [] [cutorService-78] [i.c.p.a.s.ping.impl.PingMonitorImpl ] Failed to get ping from agent [4] count [4] 
2015-03-08 13:37:12,158 ERROR [:] [] [] [] [cutorService-75] [i.c.p.a.s.ping.impl.PingMonitorImpl ] Failed to get ping from agent [2] count [1] 
2015-03-08 13:37:12,159 ERROR [:] [] [] [] [cutorService-76] [i.c.p.a.s.ping.impl.PingMonitorImpl ] Failed to get ping from agent [5] count [4] 
2015-03-08 13:37:12,158 ERROR [:] [] [] [] [cutorService-65] [i.c.p.a.s.ping.impl.PingMonitorImpl ] Failed to get ping from agent [7] count [1] 
2015-03-08 13:37:17,160 ERROR [:] [] [] [] [cutorService-79] [i.c.p.a.s.ping.impl.PingMonitorImpl ] Failed to get ping from agent [5] count [5] 
2015-03-08 13:37:17,160 ERROR [:] [] [] [] [cutorService-65] [i.c.p.a.s.ping.impl.PingMonitorImpl ] Failed to get ping from agent [4] count [5] 
2015-03-08 13:37:22,160 ERROR [:] [] [] [] [cutorService-64] [i.c.p.a.s.ping.impl.PingMonitorImpl ] Failed to get ping from agent [4] count [1] 
2015-03-08 13:37:22,161 ERROR [:] [] [] [] [cutorService-50] [i.c.p.a.s.ping.impl.PingMonitorImpl ] Failed to get ping from agent [5] count [1] 
2015-03-08 13:42:02,224 ERROR [:] [] [] [] [cutorService-79] [i.c.p.a.s.ping.impl.PingMonitorImpl ] Failed to get ping from agent [11] count [1] 
2015-03-08 13:42:03,575 ERROR [31b920c5-b975-4022-94c9-7b7e46f02a66:553] [instance:39] [instance.start->(InstanceStart)->instance.allocate->(InstanceAllocate)] [] [cutorService-85] [c.p.a.e.i.AllocatorEventListenerImpl] No allocator handled [EventVO [id=a08f6710-c631-4c08-bb1a-1f90217a6583, name=instance.allocate, previousNames=null, replyTo=reply.8525061809052791520, resourceId=39, resourceType=instance, publisher=null, transitioning=null, transitioningMessage=null, transitioningInternalMessage=null, previousIds=null, data={}, time=Sun Mar 08 13:42:03 UTC 2015, listenerKey=null, transitioningProgress=null]] 
2015-03-08 13:42:03,581 ERROR [31b920c5-b975-4022-94c9-7b7e46f02a66:553] [instance:39] [instance.start->(InstanceStart)->instance.allocate] [] [cutorService-12] [c.p.e.p.i.DefaultProcessInstanceImpl] Unknown exception io.cattle.platform.eventing.exception.EventExecutionException: Failed to find a placement
	at io.cattle.platform.eventing.impl.AbstractEventService.callSync(AbstractEventService.java:265) ~[cattle-framework-eventing-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.process.common.handler.EventBasedProcessHandler.handle(EventBasedProcessHandler.java:82) ~[cattle-iaas-logic-common-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl.runHandler(DefaultProcessInstanceImpl.java:434) [cattle-framework-engine-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl$4.execute(DefaultProcessInstanceImpl.java:373) [cattle-framework-engine-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl$4.execute(DefaultProcessInstanceImpl.java:370) [cattle-framework-engine-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.engine.idempotent.Idempotent.execute(Idempotent.java:43) [cattle-framework-engine-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl.runHandlers(DefaultProcessInstanceImpl.java:370) [cattle-framework-engine-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl.runLogic(DefaultProcessInstanceImpl.java:498) [cattle-framework-engine-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl.runWithProcessLock(DefaultProcessInstanceImpl.java:315) [cattle-framework-engine-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl$2.doWithLockNoResult(DefaultProcessInstanceImpl.java:259) [cattle-framework-engine-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.lock.LockCallbackNoReturn.doWithLock(LockCallbackNoReturn.java:7) [cattle-framework-lock-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.lock.LockCallbackNoReturn.doWithLock(LockCallbackNoReturn.java:3) [cattle-framework-lock-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.lock.impl.AbstractLockManagerImpl$3.doWithLock(AbstractLockManagerImpl.java:40) [cattle-framework-lock-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.lock.impl.LockManagerImpl.doLock(LockManagerImpl.java:33) [cattle-framework-lock-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.lock.impl.AbstractLockManagerImpl.lock(AbstractLockManagerImpl.java:13) [cattle-framework-lock-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.lock.impl.AbstractLockManagerImpl.lock(AbstractLockManagerImpl.java:37) [cattle-framework-lock-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl.acquireLockAndRun(DefaultProcessInstanceImpl.java:256) [cattle-framework-engine-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl.runDelegateLoop(DefaultProcessInstanceImpl.java:187) [cattle-framework-engine-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl.executeWithProcessInstanceLock(DefaultProcessInstanceImpl.java:160) [cattle-framework-engine-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl$1.doWithLock(DefaultProcessInstanceImpl.java:109) [cattle-framework-engine-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl$1.doWithLock(DefaultProcessInstanceImpl.java:106) [cattle-framework-engine-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.lock.impl.AbstractLockManagerImpl$3.doWithLock(AbstractLockManagerImpl.java:40) [cattle-framework-lock-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.lock.impl.LockManagerImpl.doLock(LockManagerImpl.java:33) [cattle-framework-lock-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.lock.impl.AbstractLockManagerImpl.lock(AbstractLockManagerImpl.java:13) [cattle-framework-lock-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.lock.impl.AbstractLockManagerImpl.lock(AbstractLockManagerImpl.java:37) [cattle-framework-lock-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl.execute(DefaultProcessInstanceImpl.java:106) [cattle-framework-engine-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.process.common.handler.AbstractObjectProcessLogic.execute(AbstractObjectProcessLogic.java:95) [cattle-iaas-logic-common-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.process.instance.InstanceStart.allocate(InstanceStart.java:169) [cattle-iaas-logic-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.process.instance.InstanceStart.handle(InstanceStart.java:57) [cattle-iaas-logic-0.5.0-SNAPSHOT.jar:na]

```

**Comment by ibuildthecloud** [comment] 2015-03-08 16:15
Is it possible your agents are flapping?  Restarting, having connection issues, etc?  There is a bug at the moment where the agent state is not dynamically reflected on the UI.  You have to refresh.  So it could be that your agent is not connected.

Pretty much the only way to get the error "failed to find a placement" is that you have told rancher to deploy to a server that is detected as unavailable.

Could this be related to your issue with the "Bad Status Line"?  I wonder if that is the root cause.

Also they would start really slow if the agent events are not getting to the Python agent on the node.  So timeouts will happen.

**Comment by feliksik** [comment] 2015-03-09 19:42
@ibuildthecloud you say "you have told rancher to deploy to a server that is detected as unavailable", I assume with server you mean the host that runs the agent. 

I think this may be related to #170 , which looks very familiar to me . Not sure though.

**Comment by deniseschannon** [comment] 2015-06-02 16:21
@feliksik Are you still seeing this issue? We've fixed #170 and made many changes with Rancher over the last several months. If it's no longer an issue, I'd like to close it.

**Comment by geekscrapy** [comment] 2015-06-16 15:52
I'd like to pull this back up. Deploying on a docker image on DigitalOcean and immediately running the rancher server, then trying to run a container comes up with this error.

**Comment by sonchang** [comment] 2015-06-16 15:59
@geekscrapy does the container still start up on the host?  or are you just seeing this in the logs?

**Comment by deniseschannon** [comment] 2015-06-16 16:06
@geekscrapy how big is the host that you have for rancher server? we recommend at least 1 GB. also, are you using 1 DigitalOcean machine for rancher server AND your host? 

If so, did you add `-e CATTLE_AGENT_IP=<management_server_ip>` so the host is showing the same IP as the management server?

**Comment by geekscrapy** [comment] 2015-06-16 16:16
@deniseschannon I did originally start it on the smaller tier (512MB) but then after the container crashed a few times I bumped it up.

Yes, using the same machine for both but I didn't use those extra arguments... I'll have a look again tomorrow to see if thats the problem.

**Comment by flaccid** [comment] 2015-07-16 05:20
I run into this too with the same conditions. I will test if it is the lack of `-e CATTLE_AGENT_IP=<management_server_ip>` being used.
Although that is mentioned on http://docs.rancher.com/rancher/rancher-ui/infrastructure/hosts/custom/ it isn't on http://my-rancher:8080/static/infra/hosts/add/custom in the UI (which is where I copy the command from). Would be great if we could improve the usability there.

**Comment by flaccid** [comment] 2015-07-16 06:04
Well the 'slow' or containers not running seems to be active still. First container in a service went ok, second one is stuck in Message: Networking. I don't see the second one in the agent log either.

**Comment by deniseschannon** [comment] 2015-07-20 17:31
@flaccid The request to make the info about `-e CATTLE_AGENT_IP=<management_server_ip>` is an enhancement request for the UI. https://github.com/rancher/rancher/issues/872

**Comment by flaccid** [comment] 2015-07-20 23:45
Awesome thanks @deniseschannon.

**Comment by ebuildy** [comment] 2015-07-22 07:50
I got this error sometimes, but after some retries it's gone away.

**Comment by flaccid** [comment] 2015-07-23 06:50
I have this issue again. My rancher host is another machine, has run up stacks without issue recently and its health looks healthy in the UI under Hosts. I also restarted the agent container on the host, nothing is hitting its log. Large tail of the rancher server's log when I run up a stack with a container service in it (the service sits in activating/in progress in the UI): https://gist.github.com/flaccid/67bf395d9e3827a7606e.

The EC2 security groups are adequate. Rancher server is in 1 availability zone, the host in another of the same EC2 region.

**Comment by vincent99** [comment] 2015-07-23 07:23
@flaccid "failed to find placement" means there is no valid place to put the container on any of the active hosts.  Search for "Checking candidate" in your logs, but the crux is

    checking candidate [false] : host needs ports
        {public: ipAddressId=null, port=443; private: ipAddressId=null, port=443; protocol=tcp}
        {public: ipAddressId=null, port=5000; private: ipAddressId=null, port=5000; protocol=tcp}
        {public: ipAddressId=null, port=5001; private: ipAddressId=null, port=5001; protocol=tcp}
        {public: ipAddressId=null, port=5002; private: ipAddressId=null, port=5002; protocol=tcp}
        {public: ipAddressId=null, port=80; private: ipAddressId=null, port=80; protocol=tcp}
        {public: ipAddressId=null, port=8081; private: ipAddressId=null, port=8081; protocol=tcp}
    available 

The `[false]` means that condition was not met.  There will be one set of those "Checking candidate" lines for each host until it finds one that meets all the conditions.  So you just don't have a host on which all of those public ports are available where the container could be put..

**Comment by flaccid** [comment] 2015-07-23 10:31
Ok cool thanks @vincent99 that makes sense, I did have a port usage overlook in this case. Would it be possible to regard that as a usability bug and look at a fix to provide the user with adequate feedback in the UI and if possible stdout in rancher-compose?
I also just raised https://github.com/rancher/rancher/issues/1628 which is obviously not high priority but has some great eye candy value.

**Comment by rmwpl** [comment] 2015-08-17 03:22
While faced with the same issue I found out that the problem was in the default ulimits configuration, namely too low open file descriptor limit (this became clear after checking /var/log/docker.log).
The workaround was to use `ulimit -n` in the shell and restart dockerd, but I can't help to wonder where did `/etc/limits.conf` go? What is the preferred way of setting system parameters like that (or sysctl.conf for that matter) in RancherOS?

**Comment by bymodude** [comment] 2015-09-03 06:52
just wanted to strongly echo @flaccid 
I just came across this "failed to find placement" issue due to ports usage and the lack of feedback in the UI (just shows "In Progress" and never times out) as well as stdout of rancher-compose is a major pain.

also in general when I use rancher-compose i am missing feedback like basic progress of pull operations (can take quite a while for large images, doesnt have to be fancy but any sort of "hey I am still alive and working" type of thing would really help). Also it seemed to me that when containers start and fail immediately I never get to see that output in stdout of rancher-compose, e.g I was starting a container which wanted to open a public port using host networking that was already in use, so docker failed to start the container and I never saw that error anywhere in rancher-compose or UI.

**Comment by flaccid** [comment] 2015-09-03 09:18
I also accidentally ran into this again today then realized I hadn't yet placed a needed label on a host. The cool thing is if we had feedback showing what is missing, one you fix that up it moves on and completes so you feel like you successfully solved a problem on the ranch 😅

**Comment by deniseschannon** [comment] 2015-12-04 18:46
Pre-duplicate of https://github.com/rancher/rancher/issues/820

**Closed** 2015-12-04 18:47 UTC
Labels: area/container, area/scheduler, kind/bug
