### ISSUE TITLE
Rancher Authentication Add Gmail 

### ISSUE THREAD

**Issue by sjkeerthi** [rancher/rancher#17196] opened 2018-12-20 12:30 UTC
Hi 

It will be great that if you could add a features under the Authentication to Add gmail sign in as Options since now all are commonly use gmail in the organization. 

Under Authentication 

GitHub / LDAP /  <ADD Gmail Sign up>

**Comment by sjkeerthi** [comment] 2019-02-22 06:27
It's terrible to have to manage user access manually. Having Google Auth would solve this problem for many of us.

**Comment by sjkeerthi** [comment] 2019-02-22 06:29
Will it be available on 2.2 label

**Comment by vincent99** [comment] 2019-04-01 03:47
Duplicate of #1411

**Closed by vincent99** 2019-04-01 03:47 UTC
Labels: area/access-control, area/authentication, kind/feature, version/2.0
