### ISSUE TITLE
Improve slow performing kube-apiserver-availability.rules

### ISSUE THREAD

**Issue by axeal** [rancher/rancher#31865] opened 2021-03-31 09:33 UTC
**What kind of request is this (question/bug/enhancement/feature request):**

Bug

**Steps to reproduce (least amount of steps as possible):**

In a longer running v2.5 cluster with monitoring v2 deployed prometheus record rules in the kube-apiserver-availability.rules group take an increased amount of time to evaluate, as a result of the number of series they are attempting to operate on, and can exceed the 2min timeout. Symptoms include AlertManager alerts of the following format:

```
alertname = PrometheusRuleFailures
endpoint = nginx-http
instance = 100.67.129.159:8080
job = rancher-monitoring-prometheus
namespace = cattle-monitoring-system
pod = prometheus-rancher-monitoring-prometheus-0
prometheus = cattle-monitoring-system/rancher-monitoring-prometheus
rule_group = /etc/prometheus/rules/prometheus-rancher-monitoring-prometheus-rulefiles-0/cattle-monitoring-system-rancher-monitoring-kube-apiserver-availability.rules.yaml;kube-apiserver-availability.rules
service = rancher-monitoring-prometheus
severity = critical
Annotations
description = Prometheus cattle-monitoring-system/prometheus-rancher-monitoring-prometheus-0 has failed to evaluate 1 rules in the last 5m.
summary = Prometheus is failing rule evaluations.
```

Affected rules will show timeouts within the Prometheus UI:

![image](https://user-images.githubusercontent.com/9771530/113119692-07545a00-9211-11eb-9e31-885f8852a3af.png)

And warning messages for these failing evaluations are see in the Prometheus Pod logs:

```
level=warn ts=2021-03-31T08:01:20.587Z caller=manager.go:577 component="rule manager" group=kube-apiserver-availability.rules msg="Evaluating rule failed" rule="record: apiserver_request:availability30d\nexpr: 1 - ((sum(increase(apiserver_request_duration_seconds_count{verb=~\"POST|PUT|PATCH|DELETE\"}[30d]))\n  - sum(increase(apiserver_request_duration_seconds_bucket{le=\"1\",verb=~\"POST|PUT|PATCH|DELETE\"}[30d])))\n  + (sum(increase(apiserver_request_duration_seconds_count{verb=~\"LIST|GET\"}[30d]))\n  - ((sum(increase(apiserver_request_duration_seconds_bucket{le=\"0.1\",scope=~\"resource|\",verb=~\"LIST|GET\"}[30d]))\n  or vector(0)) + sum(increase(apiserver_request_duration_seconds_bucket{le=\"0.5\",scope=\"namespace\",verb=~\"LIST|GET\"}[30d]))\n  + sum(increase(apiserver_request_duration_seconds_bucket{le=\"5\",scope=\"cluster\",verb=~\"LIST|GET\"}[30d]))))\n  + sum(code:apiserver_request_total:increase30d{code=~\"5..\"} or vector(0))) / sum(code:apiserver_request_total:increase30d)\nlabels:\n  verb: all\n" err="context deadline exceeded" 
```

```
level=warn ts=2021-03-31T08:07:21.660Z caller=manager.go:577 component="rule manager" group=kube-apiserver-availability.rules msg="Evaluating rule failed" rule="record: code_verb:apiserver_request_total:increase30d\nexpr: sum by(code, verb) (increase(apiserver_request_total{code=~\"2..\",job=\"apiserver\",verb=\"LIST\"}[30d]))\n" err="context deadline exceeded" 
```

Suggest to remove the apiserver_request:availability30d rules, per other projects, and to incorporate improvements to code_verb:apiserver_request_total:increase rules per upstream (https://github.com/kubernetes-monitoring/kubernetes-mixin/issues/411 and https://github.com/kubernetes-monitoring/kubernetes-mixin/pull/537)

**Environment information**
- Rancher v2.5.5 / monitoring 9.4.202

gz#16124

**Comment by cocampbe** [comment] 2021-06-21 13:06
Is there a work around for this? I get these alerts quite frequently. I was thinking of adding a silence for summary=Prometheus is failing rule evaluations.

**Comment by scbay** [comment] 2022-02-21 11:07
Any news on that?

**Comment by junkiebev** [comment] 2022-03-17 22:15
This issue is caused by the `apiserver_request_duration_seconds_bucket` having extremely high cardinality

The fix to reduce that is in this merged PR from last November: https://github.com/kubernetes/kubernetes/pull/106306

I'm not certain which versions of K8s have that fix though

**Comment by junkiebev** [comment] 2022-03-17 22:17
Example for running `topk(10, count by (__name__)({__name__=~".+"}))`

![image](https://user-images.githubusercontent.com/6684332/158903498-4b3a7345-4237-4030-848a-5d8286988189.png)

**Comment by east4ming** [comment] 2022-05-12 07:12
I have same error, and I delete this rule:

```yaml
        - alert: AggregatedAPIDown
          annotations:
            description: >-
              An aggregated API {{ $labels.name }}/{{ $labels.namespace }} has
              been only {{ $value | humanize }}% available over the last 10m.
            runbook_url: >-
              https://github.com/kubernetes-monitoring/kubernetes-mixin/tree/master/runbook.md#alert-name-aggregatedapidown
            summary: An aggregated API is down.
          expr: >-
            (1 - max by(name,
            namespace)(avg_over_time(aggregator_unavailable_apiservice[10m]))) *
            100 < 85
          for: 5m
          labels:
            severity: warning
```

from 
```
Kind:
PrometheusRule
Name:
rancher-monitoring-kubernetes-system-apiserver
Namespace:
cattle-monitoring-system
```

**Comment by jbiers** [comment] 2024-07-24 15:38
The behavior described in the issue could no longer be replicated in the latest Rancher version v2.8.5. This issue was very likely related to some Kubernetes metrics previously having very high cardinality in the past, leading to a cardinality explosion when the cluster had a reasonable amount of resources, like the **apiserver_request_duration_seconds_bucket** resolved in [this 2022 PR](https://github.com/kubernetes/kubernetes/pull/106306). Since these improvements were made to the apiserver metrics endpoint over two years ago, they are of course supported by RKE2 currently.

**Closed** 2024-07-30 15:36 UTC
Labels: kind/bug, internal, area/monitoring, status/to-reproduce, team/observability&backup, priority/4
