### ISSUE TITLE
Unable to install current version of cert-manager

### ISSUE THREAD

**Issue by dnauck** [rancher/rancher#21242] opened 2019-06-30 15:11 UTC
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
1. Add jetstack helm repository to cluster's catalog: https://hub.helm.sh/charts/jetstack/cert-manager
2. try to install cert-manager in System project

**Result:**
Wait helm template failed. Error: stat /cert-manager: no such file or directory : exit status 1

**Other details that may be helpful:**

its also not possible to install the latest helm version due: https://github.com/jetstack/cert-manager/issues/1380

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): 2.2.4
- Installation option (single install/HA): single install

**Comment by superseb** [comment] 2019-06-30 15:20
Duplicate of https://github.com/rancher/rancher/issues/18535

**Closed by superseb** 2019-06-30 15:20 UTC
