### ISSUE TITLE
[2.4.X] Node Stuck Deleting if Node Template was already deleted

### ISSUE THREAD

**Issue by mitchellmaler** [rancher/rancher#26456] opened 2020-04-02 20:02 UTC
**What kind of request is this (question/bug/enhancement/feature request):**
bug

**Steps to reproduce (least amount of steps as possible):**
Using the rancher terraform provider I create a node_template and a node_pool. Then I run a destroy and the node_template is deleted along with the node_pool. 

**Result:**
The nodes are still being processed by the node controller and start to error that the node_template does not exist anymore and is not deleted.

**Other details that may be helpful:**

Few options to fix this:
- Rancher should reject a node_template delete so that it can't be removed when nodes are still referencing it 
- The nodes should hold a copy of the last used node_template version so that way if it is deleted it can still processed.

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI):
- Installation option (single install/HA): HA

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): vSphere
- Machine type (cloud/VM/metal) and specifications (CPU/memory): VM
- Kubernetes version (use `kubectl version`): 1.17

gzrancher/rancher#9546

**Comment by mitchellmaler** [comment] 2020-04-02 20:03
The only work around is to manually delete the nodes and update the node object in rancher cluster and remove the node controller finalizer.

**Comment by izaac** [comment] 2020-04-03 00:25
Rancher version: `v2.4.2`
Using `terraform destroy -target=rancher2_node_template.foo`

Here I see this behavior. In the Rancher UI the cluster will be in a Red `Updating` state with NodeController errors in the Rancher logs.

Deleting the node_template resource from Terraform will also trigger the deletion of node pools as dependencies.

Deleting Manually from UI

Also if done quick enough to delete the node pools and then the Node Template the cluster ends up in a similar Failed state, but it could also be because the etcd node and other nodes were deleted here is a screenshot:

![Screen Shot 2020-04-02 at 5 03 15 PM](https://user-images.githubusercontent.com/27659/78311737-7ae06000-7506-11ea-8262-70dc8ab24168.png)

```
Cluster health check failed: Failed to communicate with API server: Get https://157.245.176.14:6443/api/v1/namespaces/kube-system?timeout=30s: waiting for cluster [c-txnxx] agent to connect; waiting for etcd and controlplane nodes to be registered
```

```
E0403 00:03:17.286921       7 reflector.go:153] github.com/rancher/norman/controller/generic_controller.go:229: Failed to list *v1.Endpoints: Get https://157.245.176.14:6443/api/v1/namespaces/cattle-prometheus/endpoints?limit=500&resourceVersion=0&timeout=30s: waiting for cluster [c-txnxx] agent to connect
```

The cluster will keep failing unless I delete it.

**Comment by juanpecatala** [comment] 2020-04-21 14:57
Same here, I have rancher 2.3.6.

Steps to reproduce from the UI:

1. Assing a new node template to a existing node pool.
2. Delete old node template while nodes keep running.
3. Delete one node on the node pool to recreate with the new template.

The node stuck in "Removing" state with the following error:

`Unable to refresh config for node m-gz2r6: nodetemplates.management.cattle.io "nt-76gkj" not found; waiting on node-controller	`

**Comment by rodcloutier** [comment] 2020-04-21 22:12
With rancher 2.3.6, another side effect, is that when using the Terraform provider 1.8.2, with dedicated node pool for etcd, if we do not create a direct dependency between the node template and the cluster, destroying the cluster and all resources will succeed with no error but etcd nodes will be left in the backing cloud (in our case openstack).

**Comment by angeloudy** [comment] 2020-06-22 06:37
I have tried adding `depends_on` and it didn't work for me. Part of the reason could be that I am using a mixture of Amazon EC2 and Custom nodes, though I am not sure why would that make a difference.

**Comment by superseb** [comment] 2020-07-01 16:44
Summary of investigating this:

The first cause seems to be that nodes are deleted later than the API returns that parent resources are deleted, meaning that when a cluster and/or nodepool is deleted (as in, confirmed by API response from Rancher), the nodes are not actually deleted yet using the backed node driver. The controller will start taking care of that, but at that point, the parent resource is already deleted and returned by the API. This means that the state that the caller (using API/UI or Terraform) gets is valid for that resource, but not dependent resources. This means that nodes still need the node template when they are actually deleted, but based on the response (and the missing check for node references to the node template), the node template is deleted before the nodes are removed. The second part is that the check when deleting a node template is only done on node pools referencing the node template. As node pools can be deleted at any time (and the nodes will be deleted after the controller and backed node driver took care of it), the node template needs to be present as long as nodes are referencing it (and not just node pools). The node config is refreshed using the node template, so it needs to be present at the time of deletion.

The least intrusive way to fix this issue in my opinion is to extend the check on node template deletion from just checking node pools referencing it to also include checking the nodes referencing it (https://github.com/rancher/rancher/blob/release/v2.4/pkg/api/store/nodetemplate/store.go#L119). The API will return the same response as when node pool(s) is/are referencing it, namely MethodNotAllowed. The reason why this is least intrusive is that its reusing the logic for node pools referencing the node template, and we make the caller in a similar way responsible for retrying to delete it when its not referenced anymore. (in the example of Terraform, the logic needs to adjusted to retry on this response). This could be made configurable so that when backing node driver takes longer to delete, the retries can be extended.

The reason this behavior is not seen "by default", is because when you delete a cluster in the UI, we don't delete the node template. In case of terraform, all resources are in scope (being created and destroyed).

Other options might be:
- Introduce a dependency on the nodes when deleting nodepool (which would basically include a dependency from cluster->nodepool->nodetemplate). This is part of why the option above is less intrusive, as we retain most of the current logic and add another check. If we add a dependency check in either of those, the API call will be blocked until everything is done (which can be a long time if any of the dependencies is slow to delete). I also dont like creating a chain of dependencies that can be blocking (and also defers from the way it is now)
- Save a copy of the nodetemplate when creating the node so its always available for deletion. This is a change that needs migration for existing setups (if even properly possible) and possible sync issues between the copy and the changed nodetemplate.
- Mark the nodes for deletion and return success if node template is deleted without nodes referencing it or only with nodes referencing that are marked for deletion. This won't work as it needs it on deletion.

**Comment by izaac** [comment] 2020-07-16 21:54
Reproduced with terraform in Rancher `v2.4.5`, some nodes were left in the infrastructure provider as well as errors with node template references.


Rancher `v2.4-head (07/16/2020)` _e28427e4a_
Rancher `master-head (07/16/2020)` _e4e2a13da_


Standard user used for creating and destroying the cluster in all Rancher versions.

- All the nodes were removed from the infrastructure provider
- No 405 errors if the build with the new retry logic is used.

**Closed by izaac** 2020-07-16 21:54 UTC
Labels: [zube]: To Test, internal
