### ISSUE TITLE
LDAP: Organizational Unit not found.

### ISSUE THREAD

**Issue by ltutar** [rancher/rancher#8270] opened 2017-03-22 14:51 UTC
**Rancher Versions:**
Server: v1.5.2 (also the same with v1.4.1)
healthcheck: v0.2.3
ipsec: net:holder
network-services: metadata:v0.8.11 and network-manager:v0.5.3
scheduler: v0.7.5
kubernetes (if applicable):

**Docker Version:**
1.12.1
**OS and where are the hosts located? (cloud, bare metal, etc):**
Red Hat Enterprise Linux Server release 7.2 and VMWare

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
One Rancher server and three Rancher agents, internal DB

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle
**Steps to Reproduce:**
1) Configure OpenLDAP with the options shown in the attachment. 
2) Log in and log out
3) Log in as somebody else. He will get the organizational unit not found error.
4) Log in again and you will get the error also.
5) Wait some time or restart rancher server again. You can log in again.
[rancher-ldap-error.txt](https://github.com/rancher/rancher/files/861780/rancher-ldap-error.txt)
![grabberraster 0059](https://cloud.githubusercontent.com/assets/7237078/24203936/530991e4-0f17-11e7-94f7-ad47b78d8e5d.jpg)
![grabberraster 0060](https://cloud.githubusercontent.com/assets/7237078/24203944/55a31b64-0f17-11e7-9307-9879064c4300.jpg)
![grabberraster 0061](https://cloud.githubusercontent.com/assets/7237078/24203949/57c07af4-0f17-11e7-9b78-1d207d7065ac.jpg)

**Results:** 
1) Organizational Unit not found error at the login page.
2) Errors in the rancher server logs.

**Comment by gerardborst** [comment] 2017-04-06 15:00
This gives the following stacktrace in the rancher server log:

2017-04-06 14:39:21,085 ERROR [:] [] [] [] [qtp9847853-12  ] [i.a.a.i.l.O.OpenLDAPIdentityProvider] When searching ldap from /v1/identity Failed to search: (&(uid=borstg)(objectClass=inetOrgPerson)) scope:o=rabobank,c=nl javax.naming.CommunicationException: connection closed
    at com.sun.jndi.ldap.LdapCtx.doSearch(LdapCtx.java:2002) ~[na:1.8.0_51]
    at com.sun.jndi.ldap.LdapCtx.searchAux(LdapCtx.java:1844) ~[na:1.8.0_51]
    at com.sun.jndi.ldap.LdapCtx.c_search(LdapCtx.java:1769) ~[na:1.8.0_51]
    at com.sun.jndi.toolkit.ctx.ComponentDirContext.p_search(ComponentDirContext.java:392) ~[na:1.8.0_51]
    at com.sun.jndi.toolkit.ctx.PartialCompositeDirContext.search(PartialCompositeDirContext.java:358) ~[na:1.8.0_51]
    at com.sun.jndi.toolkit.ctx.PartialCompositeDirContext.search(PartialCompositeDirContext.java:341) ~[na:1.8.0_51]
    at javax.naming.directory.InitialDirContext.search(InitialDirContext.java:267) ~[na:1.8.0_51]
    at io.cattle.platform.iaas.api.auth.integration.ldap.LDAPIdentityProvider.searchLdap(LDAPIdentityProvider.java:253) ~[classes/:na]
    at io.cattle.platform.iaas.api.auth.integration.ldap.OpenLDAP.OpenLDAPIdentityProvider.getIdentities(OpenLDAPIdentityProvider.java:157) [classes/:na]
    at io.cattle.platform.iaas.api.auth.integration.ldap.OpenLDAP.OpenLDAPTokenCreator.getLdapToken(OpenLDAPTokenCreator.java:43) [classes/:na]
    at io.cattle.platform.iaas.api.auth.integration.ldap.OpenLDAP.OpenLDAPTokenCreator.getToken(OpenLDAPTokenCreator.java:60) [classes/:na]
    at io.cattle.platform.iaas.api.auth.identity.TokenResourceManager.createToken(TokenResourceManager.java:65) [classes/:na]
    at io.cattle.platform.iaas.api.auth.identity.TokenResourceManager.createInternal(TokenResourceManager.java:49) [classes/:na]
    at io.github.ibuildthecloud.gdapi.request.resource.impl.AbstractBaseResourceManager.create(AbstractBaseResourceManager.java:115) [classes/:na]
    at io.github.ibuildthecloud.gdapi.request.handler.ResourceManagerRequestHandler.generate(ResourceManagerRequestHandler.java:40) [classes/:na]
    at io.github.ibuildthecloud.gdapi.request.handler.AbstractResponseGenerator.handle(AbstractResponseGenerator.java:14) [classes/:na]
    at io.github.ibuildthecloud.gdapi.request.handler.write.DefaultReadWriteApiDelegate.handle(DefaultReadWriteApiDelegate.java:27) [classes/:na]
    at io.github.ibuildthecloud.gdapi.request.handler.write.DefaultReadWriteApiDelegate.write(DefaultReadWriteApiDelegate.java:22) [classes/:na]
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_51]
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_51]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_51]
    at java.lang.reflect.Method.invoke(Method.java:497) ~[na:1.8.0_51]
    at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:333) [spring-aop-4.3.2.RELEASE.jar:4.3.2.RELEASE]
    at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:190) [spring-aop-4.3.2.RELEASE.jar:4.3.2.RELEASE]
    at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157) [spring-aop-4.3.2.RELEASE.jar:4.3.2.RELEASE]
    at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:99) [spring-tx-4.3.2.RELEASE.jar:4.3.2.RELEASE]
    at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:280) [spring-tx-4.3.2.RELEASE.jar:4.3.2.RELEASE]
    at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:96) [spring-tx-4.3.2.RELEASE.jar:4.3.2.RELEASE]
    at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179) [spring-aop-4.3.2.RELEASE.jar:4.3.2.RELEASE]
    at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:92) [spring-aop-4.3.2.RELEASE.jar:4.3.2.RELEASE]
    at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179) [spring-aop-4.3.2.RELEASE.jar:4.3.2.RELEASE]
    at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:213) [spring-aop-4.3.2.RELEASE.jar:4.3.2.RELEASE]
    at com.sun.proxy.$Proxy66.write(Unknown Source) [na:na]
    at io.github.ibuildthecloud.gdapi.request.handler.write.ReadWriteApiHandler.handle(ReadWriteApiHandler.java:19) [classes/:na]
    at io.github.ibuildthecloud.gdapi.servlet.ApiRequestFilterDelegate.doFilter(ApiRequestFilterDelegate.java:99) [classes/:na]
    at io.cattle.platform.api.servlet.ApiRequestFilter$1.runInContext(ApiRequestFilter.java:96) [classes/:na]
    at org.apache.cloudstack.managed.context.ManagedContextRunnable$1.run(ManagedContextRunnable.java:49) [classes/:na]
    at org.apache.cloudstack.managed.context.impl.DefaultManagedContext$1.call(DefaultManagedContext.java:55) [classes/:na]
    at org.apache.cloudstack.managed.context.impl.DefaultManagedContext.callWithContext(DefaultManagedContext.java:108) [classes/:na]
    at org.apache.cloudstack.managed.context.impl.DefaultManagedContext.runWithContext(DefaultManagedContext.java:52) [classes/:na]
    at org.apache.cloudstack.managed.context.ManagedContextRunnable.run(ManagedContextRunnable.java:46) [classes/:na]
    at io.cattle.platform.api.servlet.ApiRequestFilter.doFilter(ApiRequestFilter.java:106) [classes/:na]
    at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652) [jetty-servlet-9.2.11.v20150529.jar:9.2.11.v20150529]
    at org.eclipse.jetty.servlets.UserAgentFilter.doFilter(UserAgentFilter.java:83) [jetty-servlets-9.2.11.v20150529.jar:9.2.11.v20150529]
    at org.eclipse.jetty.servlets.GzipFilter.doFilter(GzipFilter.java:300) [jetty-servlets-9.2.11.v20150529.jar:9.2.11.v20150529]
    at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652) [jetty-servlet-9.2.11.v20150529.jar:9.2.11.v20150529]
    at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:585) [jetty-servlet-9.2.11.v20150529.jar:9.2.11.v20150529]
    at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143) [jetty-server-9.2.11.v20150529.jar:9.2.11.v20150529]
    at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:577) [jetty-security-9.2.11.v20150529.jar:9.2.11.v20150529]
    at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:223) [jetty-server-9.2.11.v20150529.jar:9.2.11.v20150529]
    at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1127) [jetty-server-9.2.11.v20150529.jar:9.2.11.v20150529]
    at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:515) [jetty-servlet-9.2.11.v20150529.jar:9.2.11.v20150529]
    at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185) [jetty-server-9.2.11.v20150529.jar:9.2.11.v20150529]
    at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1061) [jetty-server-9.2.11.v20150529.jar:9.2.11.v20150529]
    at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141) [jetty-server-9.2.11.v20150529.jar:9.2.11.v20150529]
    at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97) [jetty-server-9.2.11.v20150529.jar:9.2.11.v20150529]
    at org.eclipse.jetty.server.Server.handle(Server.java:499) [jetty-server-9.2.11.v20150529.jar:9.2.11.v20150529]
    at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:310) [jetty-server-9.2.11.v20150529.jar:9.2.11.v20150529]
    at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:257) [jetty-server-9.2.11.v20150529.jar:9.2.11.v20150529]
    at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:540) [jetty-io-9.2.11.v20150529.jar:9.2.11.v20150529]
    at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635) [jetty-util-9.2.11.v20150529.jar:9.2.11.v20150529]
    at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555) [jetty-util-9.2.11.v20150529.jar:9.2.11.v20150529]
    at java.lang.Thread.run(Thread.java:745) [na:1.8.0_51]
Caused by: java.io.IOException: connection closed
    at com.sun.jndi.ldap.LdapClient.ensureOpen(LdapClient.java:1591) ~[na:1.8.0_51]
    at com.sun.jndi.ldap.LdapClient.search(LdapClient.java:532) ~[na:1.8.0_51]
    at com.sun.jndi.ldap.LdapCtx.doSearch(LdapCtx.java:1985) ~[na:1.8.0_51]
    ... 62 common frames omitted

According to this text https://coderanch.com/t/583234/Tomcat-LDAP-authentication this could be caused because the LDAP server side is closing the connection. I don't how the pooling works in Rancher but it was advised to close the connection after each login and I think also LDAP query.

**Comment by gerardborst** [comment] 2017-04-07 10:18
At this moment the ldap context is defined with the following properties:

09:58:15.364 [main] INFO  io.cattle.platform.pool.PoolConfig - Setting Pool [ldap.context.pool] property [jmxNameBase=org.apache.commons.pool2:type=GenericObjectPool,name=]

09:58:15.365 [main] INFO  io.cattle.platform.pool.PoolConfig - Setting Pool [ldap.context.pool] property [jmxNamePrefix=ldap.context.pool]

09:58:15.365 [main] INFO  io.cattle.platform.pool.PoolConfig - Setting Pool [ldap.context.pool] property [maxIdle=50]

09:58:15.365 [main] INFO  io.cattle.platform.pool.PoolConfig - Setting Pool [ldap.context.pool] property [maxTotal=1000]

09:58:15.365 [main] INFO  io.cattle.platform.pool.PoolConfig - Setting Pool [ldap.context.pool] property [maxWaitMillis=1000]

09:58:15.365 [main] INFO  io.cattle.platform.pool.PoolConfig - Setting Pool [ldap.context.pool] property [minEvictableIdleTimeMillis=300000]

09:58:15.365 [main] INFO  io.cattle.platform.pool.PoolConfig - Setting Pool [ldap.context.pool] property [testOnBorrow=false]

09:58:15.365 [main] INFO  io.cattle.platform.pool.PoolConfig - Setting Pool [ldap.context.pool] property [testWhileIdle=true]

09:58:15.365 [main] INFO  io.cattle.platform.pool.PoolConfig - Setting Pool [ldap.context.pool] property [timeBetweenEvictionRunsMillis=60000]

Is it not possible to overrule this with

minEvictableIdleTimeMillis=25000
timeBetweenEvictionRunsMillis=15000
minIdle=0

This because nsslapd-idletimout on the ldap server is 30 secs

**Comment by gerardborst** [comment] 2017-04-10 15:11
I have set the environment variable `-e JAVA_OPTS=-Dldap.context.pool.testonborrow=true` on the rancher-server and it looks as if this solved the problem.

There are a lot of messages in the log but I think this isn't that important in this case.

2017-04-10 15:02:23,965 INFO  [:] [] [] [] [tp859417998-273] [.i.l.a.LdapServiceContextPoolFactory] Failed to validate an existing ldap service context.

2017-04-10 15:02:23,965 INFO  [:] [] [] [] [tp859417998-273] [.i.l.a.LdapServiceContextPoolFactory] connection closed

2017-04-10 15:02:23,965 INFO  [:] [] [] [] [tp859417998-273] [.i.l.a.LdapServiceContextPoolFactory] Failed to validate an existing ldap service context.

2017-04-10 15:02:23,965 INFO  [:] [] [] [] [tp859417998-273] [.i.l.a.LdapServiceContextPoolFactory] connection closed

2017-04-10 15:02:23,965 INFO  [:] [] [] [] [tp859417998-273] [.i.l.a.LdapServiceContextPoolFactory] Failed to validate an existing ldap service context.

2017-04-10 15:02:23,965 INFO  [:] [] [] [] [tp859417998-273] [.i.l.a.LdapServiceContextPoolFactory] connection closed

**Comment by janeczku** [comment] 2017-04-14 21:53
**Similar issue here with an AD LDAP backend**

Authentication suddenly stopped working on one of the HA production clusters (Rancher v1.4.1) and the "Organizational Unit not found" error was shown to users trying to login.

Nothing surfaced in the error logs but the following exceptions were logged to the debug (see related ticket #8513 ) log every time a user tried to login:

```
2017-04-14 10:15:06,821 INFO  [:] [] [] [] [qtp5592464-4116] [i.c.p.i.a.a.i.l.a.ADIdentityProvider] Failed to search: (sAMAccountName=XXXX)with DN=DC=XXXX,DC=com as the scope. javax.naming.CommunicationException: Connection timed out
	at com.sun.jndi.ldap.LdapCtx.doSearch(LdapCtx.java:2002) ~[na:1.8.0_72]
	at com.sun.jndi.ldap.LdapCtx.searchAux(LdapCtx.java:1844) ~[na:1.8.0_72]
	at com.sun.jndi.ldap.LdapCtx.c_search(LdapCtx.java:1769) ~[na:1.8.0_72]
(...)

```
2017-04-14 20:30:09,424 INFO  [:] [] [] [] [qtp5592464-4919] [i.c.p.i.a.a.i.l.a.ADIdentityProvider] Failed to search: (sAMAccountName=XXXX)with DN=DC=XXXX,DC=com as the scope. javax.naming.CommunicationException: Connection reset
	at com.sun.jndi.ldap.LdapCtx.doSearch(LdapCtx.java:2002) ~[na:1.8.0_72]
	at com.sun.jndi.ldap.LdapCtx.searchAux(LdapCtx.java:1844) ~[na:1.8.0_72]
	at com.sun.jndi.ldap.LdapCtx.c_search(LdapCtx.java:1769) ~[na:1.8.0_72]
```

We verified that this was not a network or AD server side issue by continuously running both TCP connection and LDAP query checks from the affected Rancher servers. They all checked out.

We noticed that the affected server nodes had just one established TCP connection to the AD server, while another HA cluster with identical configuration and Rancher version showed that a permanent pool of around 30 connections was maintained with the AD server even at idle times (no users logged in).

netstat from Rancher HA cluster nodes with crippled authentication:

```
root@node-001.prod.xxx:/# netstat | grep "ldap"
tcp6       0      0 1e9715e557ab:47280      ds.XXXX.com:ldaps  ESTABLISHED
```

and the netstat from the Rancher HA cluster with working authentication:

root@node-001.stage.xxx:/# netstat | grep "ldap"
tcp6       0      0 137762a9ab19:55426      ds.XXXX.com:ldaps  ESTABLISHED
tcp6       0      0 137762a9ab19:55438      ds.XXXX.com:ldaps  ESTABLISHED
tcp6       0      0 137762a9ab19:55460      ds.XXXX.com:ldaps  ESTABLISHED
tcp6       0      0 137762a9ab19:55440      ds.XXXX.com:ldaps  ESTABLISHED
tcp6       0      0 137762a9ab19:55406      ds.XXXX.com:ldaps  ESTABLISHED
tcp6       0      0 137762a9ab19:55400      ds.XXXX.com:ldaps  ESTABLISHED
tcp6       0      0 137762a9ab19:55410      ds.XXXX.com:ldaps  ESTABLISHED
tcp6       0      0 137762a9ab19:55414      ds.XXXX.com:ldaps  ESTABLISHED
tcp6       0      0 137762a9ab19:55420      ds.XXXX.com:ldaps  ESTABLISHED
tcp6       0      0 137762a9ab19:55428      ds.XXXX.com:ldaps  ESTABLISHED
tcp6       0      0 137762a9ab19:55408      ds.XXXX.com:ldaps  ESTABLISHED
tcp6       0      0 137762a9ab19:55446      ds.XXXX.com:ldaps  ESTABLISHED
tcp6       0      0 137762a9ab19:55418      ds.XXXX.com:ldaps  ESTABLISHED
tcp6       0      0 137762a9ab19:55448      ds.XXXX.com:ldaps  ESTABLISHED
tcp6       0      0 137762a9ab19:55454      ds.XXXX.com:ldaps  ESTABLISHED
tcp6       0      0 137762a9ab19:55404      ds.XXXX.com:ldaps  ESTABLISHED
tcp6       0      0 137762a9ab19:55450      ds.XXXX.com:ldaps  ESTABLISHED
tcp6       0      0 137762a9ab19:55430      ds.XXXX.com:ldaps  ESTABLISHED
tcp6       0      0 137762a9ab19:55416      ds.XXXX.com:ldaps  ESTABLISHED
tcp6       0      0 137762a9ab19:55462      ds.XXXX.com:ldaps  ESTABLISHED
tcp6       0      0 137762a9ab19:55422      ds.XXXX.com:ldaps  ESTABLISHED
tcp6       0      0 137762a9ab19:55424      ds.XXXX.com:ldaps  ESTABLISHED
tcp6       0      0 137762a9ab19:55456      ds.XXXX.com:ldaps  ESTABLISHED
tcp6       0      0 137762a9ab19:55412      ds.XXXX.com:ldaps  ESTABLISHED
tcp6       0      0 137762a9ab19:55442      ds.XXXX.com:ldaps  ESTABLISHED
tcp6       0      0 137762a9ab19:55436      ds.XXXX.com:ldaps  ESTABLISHED
tcp6       0      0 137762a9ab19:55458      ds.XXXX.com:ldaps  ESTABLISHED
tcp6       0      0 137762a9ab19:55402      ds.XXXX.com:ldaps  ESTABLISHED
tcp6       0      0 137762a9ab19:55452      ds.XXXX.com:ldaps  ESTABLISHED
tcp6       0      0 137762a9ab19:55444      ds.XXXX.com:ldaps  ESTABLISHED
```

We could temporarily resolve the issue by restarting all HA cluster nodes, after which they showed 30 active connections to the AD server and no login issues so far.

**Comment by janeczku** [comment] 2017-04-16 01:43
Observations:

1. First of all, there is a bug in the [LDAPIdentityProvider](https://github.com/rancher/cattle/blob/v0.178.4/code/iaas/auth-logic/src/main/java/io/cattle/platform/iaas/api/auth/integration/ldap/LDAPIdentityProvider.java#L355-L356):
     The `init()` method's `config.setTestOnBorrow(true);` is immediately overwritten by `PoolConfig.setConfig(...);` which sets the ObjectPoolConfig `testOnBorrow` property back to `false` based on the [defaults.properties](https://github.com/rancher/cattle/blob/v0.178.4/code/packaging/app-config/src/main/resources/META-INF/cattle/defaults/defaults.properties#L23).

     The result of this is that broken LDAP context instances (e.g. where underlying connection has been closed on the LDAP server side after idle timeout or server restart) are not detected before checking them out to clients from the ObjectPool.

2) Secondly, instead of invalidating those LDAP context instances as soon as they yield a `CommunicationException` (which with high probability means the are not usable anymore), they are returned back to the ObjectPool. Example [here](https://github.com/rancher/cattle/blob/v0.178.4/code/iaas/auth-logic/src/main/java/io/cattle/platform/iaas/api/auth/integration/ldap/LDAPIdentityProvider.java#L255-L261).

The combination of 1. and 2. results in these broken context instances to be checked out to clients and then returned to the pool indefinitely or until the LDAP query rate decreases enough for them to become idle for at least `global.pool.minevictableidletimemillis=300000` at which point the idle evictor takes care of evicting them.

**Comment by galal-hussein** [comment] 2017-04-25 20:04
Rancher Server: master build

Steps to validate:

- Enable LDAP authentication.
- Log in/out couple of times.
- Restart LDAP authentication and try to log in afterwards.
- Repeat the previous step multiple times.

I can't see any failed logins when restarting the LDAP server, and i was able to login successfully.

**Closed by galal-hussein** 2017-04-25 20:04 UTC
Labels: area/access-control, kind/bug, status/resolved, status/to-test

**Comment by galal-hussein** [comment] 2017-05-02 17:20
Rancher server: v1.5.8-rc1

@deniseschannon Verified the steps in this version as well.
