### ISSUE TITLE
[BUG] Fleet-agent panics on k3s node driver cluster and doesn't recover 

### ISSUE THREAD

**Issue by anupama2501** [rancher/rancher#43012] opened 2023-09-29 15:17 UTC
Information about the Cluster
**Rancher Server Setup**
- Rancher version: `v2.8.0-alpha1`, Fleet version `103.1.0+up0.9.0-rc.3`
- Installation option (Docker install/Helm Chart): `Helm Chart`
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): `RKE1`, `v1.27.6-rancher1-1`, `1.5.0-rc5`
- Proxy/Cert Details: `Self-signed`

**Information about the Cluster**
- Kubernetes version: `v1.27.5+k3s1`
- Cluster Type (Local/Downstream): `Infrastructure provider  3 worker, 1 etcd, 1 cp k3s`

**Describe the bug**
Fleet-agent panics on k3s node driver cluster and doesn't recover. Its stuck on updating state.

**To Reproduce**

1. Create a rancher HA server with 3 nodes on an rke1 server
2. Create a downstream k3s node driver with 5 nodes.
3. 2017 users were created and added in the downstream cluster as a cluster-owner and the crashloop is noticed.

**Result**
Fleet-agent pod is in crash-loop back off with the following panic:
```
I0928 18:14:53.356518       1 leaderelection.go:245] attempting to acquire leader lease cattle-fleet-system/fleet-agent-lock...
2023-09-28T18:14:53.390312936Z I0928 18:14:53.390199       1 leaderelection.go:255] successfully acquired lease cattle-fleet-system/fleet-agent-lock
2023-09-28T18:14:53.395045943Z time="2023-09-28T18:14:53Z" level=warning msg="Cannot find fleet-agent secret, running registration"
2023-09-28T18:14:53.680689231Z panic: assignment to entry in nil map
2023-09-28T18:14:53.680732312Z 
2023-09-28T18:14:53.680736843Z goroutine 52 [running]:
2023-09-28T18:14:53.681029990Z github.com/rancher/fleet/internal/cmd/agent/register.runRegistration({0x2cca1d8, 0xc0001185f0}, {0x2cd7a08, 0xc0004d8390}, {0xc00005800a, 0x13}, {0x0, 0x0})
2023-09-28T18:14:53.681036620Z 	/go/src/github.com/rancher/fleet/internal/cmd/agent/register/register.go:169 +0x4e5
2023-09-28T18:14:53.681038880Z github.com/rancher/fleet/internal/cmd/agent/register.tryRegister({0x2cca1d8, 0xc0001185f0}, {0xc00005800a, 0x13}, {0x0, 0x0}, 0x17fa000010000?)
2023-09-28T18:14:53.681040971Z 	/go/src/github.com/rancher/fleet/internal/cmd/agent/register/register.go:79 +0x313
2023-09-28T18:14:53.681042551Z github.com/rancher/fleet/internal/cmd/agent/register.Register({0x2cca1d8, 0xc0001185f0}, {0xc00005800a, 0x13}, {0x0, 0x0}, 0x41c4de0?)
2023-09-28T18:14:53.681044060Z 	/go/src/github.com/rancher/fleet/internal/cmd/agent/register/register.go:51 +0x88
2023-09-28T18:14:53.681045571Z github.com/rancher/fleet/internal/cmd/agent.start.func1({0x2cca1d8, 0xc0001185f0})
2023-09-28T18:14:53.681047991Z 	/go/src/github.com/rancher/fleet/internal/cmd/agent/start.go:58 +0x92
2023-09-28T18:14:53.681049480Z created by github.com/rancher/wrangler/pkg/leader.run.func1 in goroutine 50
2023-09-28T18:14:53.681050980Z 	/go/pkg/mod/github.com/rancher/wrangler@v1.1.1/pkg/leader/leader.go:58 +0x90
```
**Following logs were noticed in the rancher pods:**
```
2023/09/28 18:25:55 [INFO] [planner] rkecluster fleet-default/anuk3snewperf - machine fleet-default/anuk3snewperf-w-585db4f7cxhsw64-5p8cc - previous join server () was not valid, using new join server (https://[2600:3c01::f03c:93ff:fe00:698a]:6443)
2023/09/28 18:25:55 [INFO] [planner] rkecluster fleet-default/anuk3snewperf: waiting for machine fleet-default/anuk3snewperf-w-585db4f7cxhsw64-5p8cc driver config to be saved
2023/09/28 18:25:55 [INFO] [planner] rkecluster fleet-default/anuk3snewperf - machine fleet-default/anuk3snewperf-w-585db4f7cxhsw64-5p8cc - previous join server () was not valid, using new join server (https://[2600:3c01::f03c:93ff:fe00:698a]:6443)
2023/09/28 18:25:55 [INFO] [planner] rkecluster fleet-default/anuk3snewperf: waiting for machine fleet-default/anuk3snewperf-w-585db4f7cxhsw64-5p8cc driver config to be saved
2023/09/28 18:25:56 [INFO] [planner] rkecluster fleet-default/anuk3snewperf - machine fleet-default/anuk3snewperf-w-585db4f7cxhsw64-5p8cc - previous join server () was not valid, using new join server (https://[2600:3c01::f03c:93ff:fe00:698a]:6443)
2023/09/28 18:25:56 [INFO] [planner] rkecluster fleet-default/anuk3snewperf: waiting for machine fleet-default/anuk3snewperf-w-585db4f7cxhsw64-5p8cc driver config to be saved


I0928 18:48:20.966148      33 trace.go:236] Trace[2097947468]: "DeltaFIFO Pop Process" ID:fleet-default/crt-anuk3snewperf-crtb-grb-44p9v-rrptdbdmsf,Depth:9968,Reason:slow event handlers blocking the queue (28-Sep-2023 18:48:20.838) (total time: 128ms):
I0928 18:48:21.683776      33 trace.go:236] Trace[1394317482]: "DeltaFIFO Pop Process" ID:fleet-default/crt-anuk3snewperf-crtb-grb-zwrvf-cn6behj35g,Depth:9967,Reason:slow event handlers blocking the queue (28-Sep-2023 18:48:20.966) (total time: 717ms):
I0928 18:48:22.447887      33 trace.go:236] Trace[516340835]: "DeltaFIFO Pop Process" ID:fleet-default/crt-anuk3snewperf-crtb-grb-4vlpx-j4vb7lcspe,Depth:9964,Reason:slow event handlers blocking the queue (28-Sep-2023 18:48:22.195) (total time: 252ms):
I0928 18:48:24.431746      33 trace.go:236] Trace[1537574149]: "DeltaFIFO Pop Process" ID:fleet-default/crt-anuk3snewperf-crtb-grb-2csml-buttzmfwgc,Depth:9948,Reason:slow event handlers blocking the queue (28-Sep-2023 18:48:24.243) (total time: 187ms):
```

**Expected Result**
fleet-agent pod does not panic and not stuck in `updating` state with the pods in crash loop backoff

**Additional context**
Unable to reproduce the issue retracing the steps on another setup.
Adding additional nodes to the cluster and creation of deployment works after the pod is stuck in the crashloop back off

**Comment by shfy70** [comment] 2023-09-30 05:56
This is my setup, I have the same issue:
1). containerd ver: 1.7.6,  one master nodes and 3 worker nodes deployed manually. 
2). Rancher ver is v1.26.9, deployed using latest docker version (onto Ubuntu 22.04 LTS server)
3). k8s ver is v1.26.8

when running "kubectl get pods -A", I get ( irrevelant pods ommitted)

shoufeng@master:~$ kubectl get pods -A

NAMESPACE             NAME                                        READY   STATUS             RESTARTS        AGE
cattle-fleet-system   fleet-agent-855db48487-qlx5g                0/1     CrashLoopBackOff   25 (2m9s ago)   69m
cattle-system         cattle-cluster-agent-648bc86879-kz4zs       1/1     Running            7 (12m ago)     69m
cattle-system         cattle-cluster-agent-648bc86879-pd857       1/1     Running            7 (13m ago)     70m
cattle-system         rancher-webhook-85b57d6bf8-mvgmb            1/1     Running            2 (14m ago)     68m


When running "kubectl -n cattle-fleet-system logs fleet-agent-855db48487-qlx5g", I got the following:
shoufeng@bastion:~$ kubectl -n cattle-fleet-system logs fleet-agent-855db48487-qlx5g
I0930 05:43:31.668177       1 leaderelection.go:248] attempting to acquire leader lease cattle-fleet-system/fleet-agent-lock...
I0930 05:43:31.708129       1 leaderelection.go:258] successfully acquired lease cattle-fleet-system/fleet-agent-lock
time="2023-09-30T05:43:31Z" level=warning msg="Cannot find fleet-agent secret, running registration"
panic: assignment to entry in nil map

goroutine 37 [running]:
github.com/rancher/fleet/internal/cmd/agent/register.createAgentSecret({0x2b21500, 0xc00056d6d0}, {0x0, 0x0}, {0x2b2dd90, 0xc000509250}, 0xc00078f7c0)
        /go/src/github.com/rancher/fleet/internal/cmd/agent/register/register.go:174 +0x3dc
github.com/rancher/fleet/internal/cmd/agent/register.runRegistration({0x2b21500, 0xc00056d6d0}, {0x2b2dd90?, 0xc000509250?}, {0xc00005800a, 0x13}, {0x0, 0x0})
        /go/src/github.com/rancher/fleet/internal/cmd/agent/register/register.go:118 +0x1af
github.com/rancher/fleet/internal/cmd/agent/register.tryRegister({0x2b21500, 0xc00056d6d0}, {0xc00005800a, 0x13}, {0x0, 0x0}, 0x1?)
        /go/src/github.com/rancher/fleet/internal/cmd/agent/register/register.go:81 +0x325
github.com/rancher/fleet/internal/cmd/agent/register.Register({0x2b21500, 0xc00056d6d0}, {0xc00005800a, 0x13}, {0x0, 0x0}, 0x3ea4a20?)
        /go/src/github.com/rancher/fleet/internal/cmd/agent/register/register.go:53 +0x97
github.com/rancher/fleet/internal/cmd/agent.start.func1({0x2b21500, 0xc00056d6d0})
        /go/src/github.com/rancher/fleet/internal/cmd/agent/start.go:58 +0x9e
created by github.com/rancher/wrangler/pkg/leader.run.func1
        /go/pkg/mod/github.com/rancher/wrangler@v1.1.1/pkg/leader/leader.go:58 +0x98
shoufeng@bastion:~$ Cannot find fleet-agent secret, running registration
WARNING:root:could not open file '/etc/apt/sources.list'

**Comment by rishabhmsra** [comment] 2023-10-04 12:02
Facing same issue on k8s v1.26.9 RKE1 downstream cluster as well.

- On rancher v2.8.0-alpha2, provisioned k8s v1.26.9-rancher1-1 rke1 cluster (2-cp, 3-e, 3-w)
- Once the cluster came up Active -> checked the pods
- fleet-agent pod remains in CrashLoopBackOff with below error :
```
I1004 11:56:22.236912       1 leaderelection.go:245] attempting to acquire leader lease cattle-fleet-system/fleet-agent-lock...
2023-10-04T11:56:22.273564689Z I1004 11:56:22.273435       1 leaderelection.go:255] successfully acquired lease cattle-fleet-system/fleet-agent-lock
2023-10-04T11:56:22.281166361Z time="2023-10-04T11:56:22Z" level=warning msg="Cannot find fleet-agent secret, running registration"
2023-10-04T11:56:22.323106897Z panic: assignment to entry in nil map
2023-10-04T11:56:22.323143192Z 
2023-10-04T11:56:22.323150580Z goroutine 50 [running]:
2023-10-04T11:56:22.323155484Z github.com/rancher/fleet/internal/cmd/agent/register.runRegistration({0x2cca1d8, 0xc000175e50}, {0x2cd7a08, 0xc000022180}, {0xc00005800a, 0x13}, {0x0, 0x0})
2023-10-04T11:56:22.323156684Z 	/go/src/github.com/rancher/fleet/internal/cmd/agent/register/register.go:169 +0x4e5
2023-10-04T11:56:22.323343637Z github.com/rancher/fleet/internal/cmd/agent/register.tryRegister({0x2cca1d8, 0xc000175e50}, {0xc00005800a, 0x13}, {0x0, 0x0}, 0x1000000000001?)
	/go/src/github.com/rancher/fleet/internal/cmd/agent/register/register.go:79 +0x313
2023-10-04T11:56:22.323367027Z github.com/rancher/fleet/internal/cmd/agent/register.Register({0x2cca1d8, 0xc000175e50}, {0xc00005800a, 0x13}, {0x0, 0x0}, 0x41c4de0?)
2023-10-04T11:56:22.323372570Z 	/go/src/github.com/rancher/fleet/internal/cmd/agent/register/register.go:51 +0x88
2023-10-04T11:56:22.323377592Z github.com/rancher/fleet/internal/cmd/agent.start.func1({0x2cca1d8, 0xc000175e50})
2023-10-04T11:56:22.323382295Z 	/go/src/github.com/rancher/fleet/internal/cmd/agent/start.go:58 +0x92
created by github.com/rancher/wrangler/pkg/leader.run.func1 in goroutine 32
2023-10-04T11:56:22.323415816Z 	/go/pkg/mod/github.com/rancher/wrangler@v1.1.1/pkg/leader/leader.go:58 +0x90
```

**Comment by EutiziStefano** [comment] 2023-10-04 13:09
Hi,
we experimented the same issue on:
Kubernetes 1.23.7
Rancher 2.7.6
fleet-agent 0.8.0

LOGS:
```
I1004 13:04:59.907282       1 leaderelection.go:248] attempting to acquire leader lease cattle-fleet-system/fleet-agent-lock...
I1004 13:04:59.942974       1 leaderelection.go:258] successfully acquired lease cattle-fleet-system/fleet-agent-lock
time="2023-10-04T13:04:59Z" level=warning msg="Cannot find fleet-agent secret, running registration"
panic: assignment to entry in nil map

goroutine 51 [running]:
github.com/rancher/fleet/internal/cmd/agent/register.createAgentSecret({0x2b21500, 0xc00035b450}, {0x0, 0x0}, {0x2b2dd90, 0xc000412300}, 0xc0009788c0)
	/go/src/github.com/rancher/fleet/internal/cmd/agent/register/register.go:174 +0x3dc
github.com/rancher/fleet/internal/cmd/agent/register.runRegistration({0x2b21500, 0xc00035b450}, {0x2b2dd90?, 0xc000412300?}, {0xc00005800a, 0x13}, {0x0, 0x0})
	/go/src/github.com/rancher/fleet/internal/cmd/agent/register/register.go:118 +0x1af
github.com/rancher/fleet/internal/cmd/agent/register.tryRegister({0x2b21500, 0xc00035b450}, {0xc00005800a, 0x13}, {0x0, 0x0}, 0x459c05?)
	/go/src/github.com/rancher/fleet/internal/cmd/agent/register/register.go:81 +0x325
github.com/rancher/fleet/internal/cmd/agent/register.Register({0x2b21500, 0xc00035b450}, {0xc00005800a, 0x13}, {0x0, 0x0}, 0x478837?)
	/go/src/github.com/rancher/fleet/internal/cmd/agent/register/register.go:53 +0x97
github.com/rancher/fleet/internal/cmd/agent.start.func1({0x2b21500, 0xc00035b450})
	/go/src/github.com/rancher/fleet/internal/cmd/agent/start.go:58 +0x9e
created by github.com/rancher/wrangler/pkg/leader.run.func1
	/go/pkg/mod/github.com/rancher/wrangler@v1.1.1/pkg/leader/leader.go:58 +0x98
```
Temporary resolved downgrading fleet agent to 0.7.1, that runs without problems.

**Comment by snasovich** [comment] 2023-10-04 16:10
My understanding it should be ready to test as https://github.com/rancher/charts/pull/3097 got merged.
@weyfonk , please correct me if I'm wrong and if not move it to test.
@rishabhmsra, I believe you should be unblocked now cc: @mitulshah-suse @Sahota1225

**Comment by weyfonk** [comment] 2023-10-04 16:12
@snasovich I am monitoring CI on https://github.com/rancher/rancher/pull/43056 to merge it ASAP and make Fleet `0.9.0-rc.4`, which should fix the issue, available to Rancher.

**Comment by snasovich** [comment] 2023-10-04 16:15
@weyfonk , my bad - forgot that in addition to pushing it to charts it must be bumped in `rancher/rancher`, including increasing `CATTLE_FLEET_MIN_VERSION`.

**Comment by weyfonk** [comment] 2023-10-04 17:08
Fleet `0.9.0-rc.4` now released.

**Comment by jonathon2nd** [comment] 2023-10-12 17:39
Just occurred for us upgrading to rancher 2.7.6 

Deploying 0.7.1 fleet as stated [above](https://github.com/rancher/rancher/issues/43012#issuecomment-1746846950) fixes the issue by fetching the secret.

**Comment by slickwarren** [comment] 2023-10-12 23:39
rancher 2.8-head as of today is still using rc3. Do we need a rancher ticket to get this bumped on the rancher side?

**Comment by sbulage** [comment] 2023-10-16 08:50
> rancher 2.8-head as of today is still using rc3. Do we need a rancher ticket to get this bumped on the rancher side?

@slickwarren I can see the `Fleet version: 0.9.0-rc.4` is available in the `2.8-head` --> https://github.com/rancher/charts/tree/dev-v2.8/assets/fleet

**Comment by sbulage** [comment] 2023-10-18 08:22
System information:
```
Rancher Version: 2.8-head
Fleet version: 0.9.0-rc.4
```

I have followed the steps mentioned in the description. I didn't see any warning or error logs in the `fleet-agent` or `fleet-controller` pods.

Also, performed sanity testing around it by creating GitRepo which installs application from helm as well normal app deployment. Applications are deployed successfully without any error.

**Closed** 2023-10-18 08:32 UTC
Labels: kind/bug, kind/bug-qa, [zube]: Done, status/release-blocker, team/fleet

**Comment by h0jeZvgoxFepBQ2C** [comment] 2023-11-27 14:36
So how can I install 0.9 in 2.7.9?

**Comment by nturnet** [comment] 2023-12-21 01:27
> So how can I install 0.9 in 2.7.9?

### Install the Fleet Helm charts (there's two because we separate out CRDs for ultimate flexibility.

helm -n cattle-fleet-system install --create-namespace --wait \
    fleet-crd https://github.com/rancher/fleet/releases/download/v0.9.0/fleet-crd-0.9.0.tgz
helm -n cattle-fleet-system install --create-namespace --wait \
    fleet https://github.com/rancher/fleet/releases/download/v0.9.0/fleet-0.9.0.tgz

**Comment by mohag** [comment] 2023-12-28 13:13
> **Install the Fleet Helm charts (there's two because we separate out CRDs for ultimate flexibility.**
> 

This fails with `Error: UPGRADE FAILED: "fleet-crd" has no deployed releases` (and similar for the other one) for thefleet deployed by cattle-cluster agent...

(`--install` will make that error go away, but won't Rancher / cattle-cluster-agent downgrade the agent / experience conflicts with a helm-deployed one?)

(Not using Rancher to deploy clusters, so the versions are often higher than what Rancher supports deploying...)

**Comment by rverchere** [comment] 2024-01-05 15:07
> > **Install the Fleet Helm charts (there's two because we separate out CRDs for ultimate flexibility.**
> 
> This fails with `Error: UPGRADE FAILED: "fleet-crd" has no deployed releases` (and similar for the other one) for thefleet deployed by cattle-cluster agent...
> 
> (`--install` will make that error go away, but won't Rancher / cattle-cluster-agent downgrade the agent / experience conflicts with a helm-deployed one?)
> 
> (Not using Rancher to deploy clusters, so the versions are often higher than what Rancher supports deploying...)

Got the same issue, initial setup does not have the helm chart installed. I just updated the fleet image version in the deployment (from 0.8.0 to 0.7.1) and the pod started correctly, then updated.

**Comment by chiukapoor** [comment] 2024-02-05 04:35
The issue is intermittent, occurring 1 in 5 times in the test deployments.

**Root Cause Analysis:**
A race condition between [cluster](https://github.com/chiukapoor/fleet/blob/23e1c146755af159dafd3c88d4b92094772c99fc/internal/cmd/controller/controllers/cluster/import.go#L309-L310) and [kubernetesprovider](https://github.com/chiukapoor/rancher/blob/dd164f760ef4c3ab57c3b73729e2d4cae4ddde07/pkg/controllers/dashboard/kubernetesprovider/kubernetesprovider.go#L75) controller has been identified. In the case where the fleet pod fails with `panic: assignment to entry in nil map`, it is observed that the config-map named `fleet-agent` lacks the label field `"labels":{"http://provider.cattle.io/":"rke"}`. This explains the intermittent nature of the problem.

**Workaround:**
Add the "labels" field to the fleet-agent config map to address this issue. For example:
```
  "labels": {
    "provider.cattle.io": "rke"
  },
```

**Comment by h0jeZvgoxFepBQ2C** [comment] 2024-06-26 13:51
> The issue is intermittent, occurring 1 in 5 times in the test deployments.
> 
> **Root Cause Analysis:** A race condition between [cluster](https://github.com/chiukapoor/fleet/blob/23e1c146755af159dafd3c88d4b92094772c99fc/internal/cmd/controller/controllers/cluster/import.go#L309-L310) and [kubernetesprovider](https://github.com/chiukapoor/rancher/blob/dd164f760ef4c3ab57c3b73729e2d4cae4ddde07/pkg/controllers/dashboard/kubernetesprovider/kubernetesprovider.go#L75) controller has been identified. In the case where the fleet pod fails with `panic: assignment to entry in nil map`, it is observed that the config-map named `fleet-agent` lacks the label field `"labels":{"http://provider.cattle.io/":"rke"}`. This explains the intermittent nature of the problem.
> 
> **Workaround:** Add the "labels" field to the fleet-agent config map to address this issue. For example:
> 
> ```
>   "labels": {
>     "provider.cattle.io": "rke"
>   },
> ```

Doesn't work for me @chiukapoor :

```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: fleet-agent
  namespace: cattle-fleet-system
  uid: 123-123-123-123-
  resourceVersion: '617348187'
  creationTimestamp: '2023-02-22T12:14:39Z'
  labels:
    k8slens-edit-resource-version: v1
    objectset.rio.cattle.io/hash: 13123123123123123
    provider.cattle.io: rke
  annotations:
    objectset.rio.cattle.io/applied: >-
      -.....
    objectset.rio.cattle.io/id: fleet-agent-bootstrap
data:
  config: >-
    {"agentCheckinInterval":"0s","clientID":"123123123123","bootstrap":{}}

```

Or should it be applied in a different way?

**Comment by ofloxacin** [comment] 2024-07-15 07:36
> The issue is intermittent, occurring 1 in 5 times in the test deployments.
> 
> **Root Cause Analysis:** A race condition between [cluster](https://github.com/chiukapoor/fleet/blob/23e1c146755af159dafd3c88d4b92094772c99fc/internal/cmd/controller/controllers/cluster/import.go#L309-L310) and [kubernetesprovider](https://github.com/chiukapoor/rancher/blob/dd164f760ef4c3ab57c3b73729e2d4cae4ddde07/pkg/controllers/dashboard/kubernetesprovider/kubernetesprovider.go#L75) controller has been identified. In the case where the fleet pod fails with `panic: assignment to entry in nil map`, it is observed that the config-map named `fleet-agent` lacks the label field `"labels":{"http://provider.cattle.io/":"rke"}`. This explains the intermittent nature of the problem.
> 
> **Workaround:** Add the "labels" field to the fleet-agent config map to address this issue. For example:
> 
> ```
>   "labels": {
>     "provider.cattle.io": "rke"
>   },
> ```

Not work

```
I0715 07:33:17.661862       1 leaderelection.go:248] attempting to acquire leader lease cattle-fleet-system/fleet-agent-lock...
I0715 07:34:03.127891       1 leaderelection.go:258] successfully acquired lease cattle-fleet-system/fleet-agent-lock
time="2024-07-15T07:34:03Z" level=warning msg="Cannot find fleet-agent secret, running registration"
time="2024-07-15T07:34:03Z" level=info msg="Creating clusterregistration with id 'ftv69tfzdbnl2tw8t8x265dbxltrftbpwgxxxxxxxxxxxxxxx' for new token"
time="2024-07-15T07:34:06Z" level=error msg="Failed to register agent: registration failed: cannot create clusterregistration on management cluster for cluster id 'ftv69tfzdbnl2tw8t8x265dbxltrftbpwgxxxxxxxxxxxxxxx': Unauthorized"
```

**Comment by realhuseyn** [comment] 2025-07-17 04:57
> The issue is intermittent, occurring 1 in 5 times in the test deployments.
> 
> **Root Cause Analysis:** A race condition between [cluster](https://github.com/chiukapoor/fleet/blob/23e1c146755af159dafd3c88d4b92094772c99fc/internal/cmd/controller/controllers/cluster/import.go#L309-L310) and [kubernetesprovider](https://github.com/chiukapoor/rancher/blob/dd164f760ef4c3ab57c3b73729e2d4cae4ddde07/pkg/controllers/dashboard/kubernetesprovider/kubernetesprovider.go#L75) controller has been identified. In the case where the fleet pod fails with `panic: assignment to entry in nil map`, it is observed that the config-map named `fleet-agent` lacks the label field `"labels":{"http://provider.cattle.io/":"rke"}`. This explains the intermittent nature of the problem.
> 
> **Workaround:** Add the "labels" field to the fleet-agent config map to address this issue. For example:
> 
> ```
>   "labels": {
>     "provider.cattle.io": "rke"
>   },
> ```

thanks
