### ISSUE TITLE
Load Balancer 404 when querying the metadata service

### ISSUE THREAD

**Issue by psychotechnik** [rancher/rancher#7060] opened 2016-12-14 19:33 UTC
Load Balancer container starts. Yet the services cannot be initialized. 

error message from container: **_Failed to get lb config: Error 404 accessing /self/service path_**

**Rancher Version:**
1.2.0

**Docker Version:**
1.12.3

**OS and where are the hosts located? (cloud, bare metal, etc):**
boot2docker

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
single node rancher
**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle

**Steps to Reproduce:**
add Load Balancer service to a stack. 

**Results:** 
service is stuck in _Initializing_ state

Failed to get lb config: Error 404 accessing /self/service path

**Expected:**
active Load Balancer service

**Comment by TriPSs** [comment] 2017-01-07 15:30
Having the same problem here!

**Comment by aemneina** [comment] 2017-05-12 18:28
@psychotechnik is this issue present in modern versions of rancher? I'm going to close this out, let me know if you still face this issue with a newer version of rancher. The load balancer and metadata have been improved dramatically since 1.2.x

**Closed by aemneina** 2017-05-12 18:28 UTC
Labels: kind/question

**Comment by oskarpearson** [comment] 2017-08-22 08:03
Could we re-open this, please? I've received this message today on Rancher v1.6.2. Thanks!

**Comment by superseb** [comment] 2017-08-22 12:54
Hi @oskarpearson , can you open a new issue with the issue template, version of lb-service-haproxy and steps to reproduce so we can investigate?
