### ISSUE TITLE
Nodes that don't fully provision won't delete

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#11277] opened 2018-02-02 17:32 UTC
**Rancher versions:** 2.0 master 2/3

**Steps to Reproduce:**
1.  Create a cluster
2.  Create a RKE cluster with AWS and check on the private IP (so the nodes won't fully provision)
3.  Delete cluster

**Results:**  Cluster deletes but the nodes get stuck in removing.  Looks like the nodes won't delete unless it can find the cluster.  If no cluster exist, it should just delete.
Error from logs
E0202 00:37:46.571923       1 generic_controller.go:191] MachineController cluster-r5bbm/machine-mg26n [machine-controller] failed with : cluster.management.cattle.io "cluster-r5bbm" not found

**Comment by StrongMonkey** [comment] 2018-02-02 17:47
@tfiduccia this should be fixed in the latest master. Can you repull master image and try again?

**Comment by tfiduccia** [comment] 2018-02-02 18:17
@StrongMonkey - nodes still stuck removing

**Comment by StrongMonkey** [comment] 2018-02-02 20:36
This is because when using private ip to provision ec2 instances, it will get stuck at provisioning for while(can't ssh into private ip), once provisioning errors out the instance should be purged.

**Comment by tfiduccia** [comment] 2018-02-02 21:30
Once we delete thou, we should stop trying to provision and just delete the instances.  Yes?

**Comment by StrongMonkey** [comment] 2018-02-03 00:18
@tfiduccia yes, but but it need more effort to do this...

**Comment by zionwu** [comment] 2018-03-27 10:27
@vincent99, if the "private IP" option prevents the node from provisioning and there is no any other use case that need it,  shouldn't we remove the option from UI?

**Comment by vincent99** [comment] 2018-03-27 10:46
It doesn't necessarily prevent the host from provisioning.  Machine needs to be able to open connections to the host, and if the host only has private IPs that implies that the server needs to be on the same subnet (or routing is in place to similar effect).

**Comment by deniseschannon** [comment] 2018-04-20 23:42
I haven't tested this, but I believe node pools were refactored a bit (again). @tfiduccia can you re-test? 

I think proper behavior should be that when the provisioning finally errors out, there will only be one node that is in error state. It will continue being in error state until you delete it. When you delete the node, it will try to provision another node (with the same node template). So the only way to fix this case would be to edit the node template to fix it and then try deleting the node.

**Comment by zionwu** [comment] 2018-04-21 12:45
I have investigated this issue. The root cause is that when use the private ip for the aws instance, docker-machine stucks and the lifecycle func `Create` stucks.  When the cluster is deleted, it equeque the node obj the for lifecycle handler.  If the obj is dequeue then the lifecycle func `Delete` will be called. However, the `Create` func stucks and the obj is never dequeque so the `Delete` method is never called.

To fix this issue, we should add a timeout for the docker machine.

**Comment by StrongMonkey** [comment] 2018-08-23 17:43
@cjellick This is already verified by https://github.com/rancher/rancher/issues/13882. Can we close it?

**Comment by cjellick** [comment] 2018-09-01 04:39
Will allow QA to verify and close then @StrongMonkey

**Comment by sangeethah** [comment] 2018-09-06 20:37
This issue is still reproducible when testing with latest master builds.

**Comment by StrongMonkey** [comment] 2018-09-06 23:01
Noticed in @sangeethah's setup, the instance was provisioned with private IP address only, thus causing `docker-machine` hang on `waiting for ssh` because it can't ssh into the private IP address. 
The potential fix is to add a timeout to `docker-machine` command, so when it failed to create it timeouts out and go through delete process.
@cjellick do you think we should add timeout for this special case? The timeout value should be big enough to prevent the situation where provisioning really takes a long time.

**Closed** 2019-04-04 04:58 UTC
Labels: area/cluster, area/host, kind/bug, priority/1, status/autoclosed, status/discussion, team/az, version/2.0
