### ISSUE TITLE
Rancher 1.6.17 networking unstable, ipsec becomes unhealthy regularly

### ISSUE THREAD

**Issue by ryanwalls** [rancher/rancher#13559] opened 2018-05-17 13:37 UTC
**Rancher versions:**
rancher/server or rancher/rancher:  1.6.17
rancher/agent or rancher/rancher-agent: 1.2.10

**Infrastructure Stack versions:**
healthcheck: rancher/healthcheck:v0.3.6
ipsec: rancher/net:v0.13.11
network-services: rancher/network-manager:v0.7.20
scheduler: 
kubernetes (if applicable): rancher/k8s:v1.10.0-rancher1-2

**Docker version: (`docker version`,`docker info` preferred)**
```
Containers: 18
 Running: 16
 Paused: 0
 Stopped: 2
Images: 14
Server Version: 1.12.6
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 133
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: overlay bridge null host
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: apparmor seccomp
Kernel Version: 4.4.0-1052-aws
Operating System: Ubuntu 16.04.4 LTS
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 1.952 GiB
Name: ip-172-31-10-8
ID: ULOU:NSM2:BAB5:UMGR:FRKV:2G6Z:DH2W:ITIX:4IW3:ZMAB:HDWV:YL6K
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Insecure Registries:
 127.0.0.0/8
```

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
```
NAME="Ubuntu"
VERSION="16.04.4 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.4 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial
```
**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
AWS

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
single node rancher with external DB

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**
Kubernetes

**Steps to Reproduce:**
Run 1.6.17 server.  Choose k8s 1.10.0.  Scale up and scale down hosts.  

**Results:**
ipsec becomes unhealthy after a period of time and never recovers.  Have to restart network manager to get ipsec happy again.  Happens every few days.

**Comment by superseb** [comment] 2018-05-17 13:42
Can you check https://github.com/rancher/rancher/issues/13176 and https://github.com/rancher/rancher/issues/13272 (where you also replied, is this the same?)

**Comment by zukokolkka** [comment] 2018-05-18 13:41
Copy that, right now facing #13176, using Rancher Server v1.6.17 and rancher/net:v0.13.11

**Comment by fatalsaint** [comment] 2018-05-22 15:27
Also experience this issue.  

rancher/server or rancher/rancher: 1.6.17
rancher/agent or rancher/rancher-agent: 1.2.10

I upgraded the ipsec to rancher/net:v0.13.13 a couple of days ago to see if that would help and it still failed today.  

In this environment there are jenkins slaves that get created and deleted fairly frequently, same concept as scaling up and down hosts, and eventually all ipsec's in the environment turn red and communication between hosts fail.

**Comment by superseb** [comment] 2018-05-22 15:33
I've seen more issues that used to get a lot of responses with a lot of different causes. This issue is a duplicate of https://github.com/rancher/rancher/issues/13176, as the nil pointer exception is shown in the environment. If you don't see the nil pointer exception, please file a new issue describing the situation and versions used.

**Closed by superseb** 2018-05-22 15:33 UTC
