### ISSUE TITLE
Space in Catalog name is creating problems

### ISSUE THREAD

**Issue by leodotcloud** [rancher/rancher#7939] opened 2017-02-23 18:08 UTC
**Rancher Versions:**
Server: 1.4.1

**Docker Version:** 1.12.3

**OS and where are the hosts located? (cloud, bare metal, etc):**
Virtualbox

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
Single Node

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle

**Steps to Reproduce:**
- In settings, add an infra catalog with a space in the name, say: "bad catalog name".
- Create a new environment template with catalog items from this catalog
- Create an environment using this template.
- None of the infrastructure stacks start.

See this in the logs:
```
2017-02-23 18:00:11,216 ERROR [:] [] [] [] [ecutorService-1] [o.a.c.m.context.NoExceptionRunnable ] Uncaught exception java.lang.IllegalStateException: Failed to invoke method [public void io.cattle.platform.systemstack.listener.SystemStackUpdate.globalServiceUpdate(io.cattle.platform.configitem.events.ConfigUpdate)] for event [EventVO [id=d0317a33-0453-49ef-acc2-1853c3e96d67, name=global.service.update, previousNames=null, replyTo=reply.7264546898239869625, resourceId=7, resourceType=account, publisher=null, transitioning=null, transitio
ningMessage=null, transitioningInternalMessage=null, previousIds=null, data={configUrl=http://172.22.101.1:8080/v1, items=[{name=system-stacks, requestedVersion=null, apply=false, increment=false, checkInSyncOnly=true}]}, time=Thu Feb 23 17:59:55 UTC 2017, listenerKey=nul
l, transitioningProgress=null]
        at io.cattle.platform.eventing.annotation.MethodInvokingListener.onEvent(MethodInvokingListener.java:88) ~[cattle-framework-eventing-0.5.0-SNAPSHOT.jar:na]
        at io.cattle.platform.eventing.impl.AbstractThreadPoolingEventService$2.doRun(AbstractThreadPoolingEventService.java:141) ~[cattle-framework-eventing-0.5.0-SNAPSHOT.jar:na]
        at org.apache.cloudstack.managed.context.NoExceptionRunnable.runInContext(NoExceptionRunnable.java:15) ~[cattle-framework-managed-context-0.5.0-SNAPSHOT.jar:na]
        at org.apache.cloudstack.managed.context.ManagedContextRunnable$1.run(ManagedContextRunnable.java:49) [cattle-framework-managed-context-0.5.0-SNAPSHOT.jar:na]
        at org.apache.cloudstack.managed.context.impl.DefaultManagedContext$1.call(DefaultManagedContext.java:55) [cattle-framework-managed-context-0.5.0-SNAPSHOT.jar:na]
        at org.apache.cloudstack.managed.context.impl.DefaultManagedContext.callWithContext(DefaultManagedContext.java:108) [cattle-framework-managed-context-0.5.0-SNAPSHOT.jar:na]
        at org.apache.cloudstack.managed.context.impl.DefaultManagedContext.runWithContext(DefaultManagedContext.java:52) [cattle-framework-managed-context-0.5.0-SNAPSHOT.jar:na]
        at org.apache.cloudstack.managed.context.ManagedContextRunnable.run(ManagedContextRunnable.java:46) [cattle-framework-managed-context-0.5.0-SNAPSHOT.jar:na]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_72]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_72]
        at java.lang.Thread.run(Thread.java:745) [na:1.8.0_72]
Caused by: java.lang.IllegalArgumentException: Illegal character in path at index 47: http://localhost:8088/v1-catalog/templates/flat networking:infra*vxlan?minimumRancherVersion_lte=v1.4.1
        at java.net.URI.create(URI.java:852) ~[na:1.8.0_72]
        at org.apache.http.client.methods.HttpGet.<init>(HttpGet.java:69) ~[httpclient-4.3.1.jar:4.3.1]
        at org.apache.http.client.fluent.Request.Get(Request.java:80) ~[fluent-hc-4.3.1.jar:4.3.1]
        at io.cattle.platform.systemstack.catalog.impl.CatalogServiceImpl.getTemplate(CatalogServiceImpl.java:125) ~[cattle-system-stack-0.5.0-SNAPSHOT.jar:na]
        at io.cattle.platform.systemstack.catalog.impl.CatalogServiceImpl.resolveUsingCatalog(CatalogServiceImpl.java:96) ~[cattle-system-stack-0.5.0-SNAPSHOT.jar:na]
        at io.cattle.platform.systemstack.catalog.impl.CatalogServiceImpl.resolveExternalId(CatalogServiceImpl.java:70) ~[cattle-system-stack-0.5.0-SNAPSHOT.jar:na]
        at io.cattle.platform.systemstack.catalog.impl.CatalogServiceImpl.resolvedExternalIds(CatalogServiceImpl.java:59) ~[cattle-system-stack-0.5.0-SNAPSHOT.jar:na]
        at io.cattle.platform.systemstack.listener.SystemStackUpdate.createStacks(SystemStackUpdate.java:233) ~[cattle-system-stack-0.5.0-SNAPSHOT.jar:na]
        at io.cattle.platform.systemstack.listener.SystemStackUpdate.process(SystemStackUpdate.java:176) ~[cattle-system-stack-0.5.0-SNAPSHOT.jar:na]
        at io.cattle.platform.systemstack.listener.SystemStackUpdate$1.run(SystemStackUpdate.java:104) ~[cattle-system-stack-0.5.0-SNAPSHOT.jar:na]
        at io.cattle.platform.configitem.version.impl.ConfigItemStatusManagerImpl$1.doWithLock(ConfigItemStatusManagerImpl.java:92) ~[cattle-config-item-common-0.5.0-SNAPSHOT.jar:na]
        at io.cattle.platform.lock.impl.AbstractLockManagerImpl$4.doWithLock(AbstractLockManagerImpl.java:50) ~[cattle-framework-lock-0.5.0-SNAPSHOT.jar:na]
        at io.cattle.platform.lock.impl.LockManagerImpl.doLock(LockManagerImpl.java:33) ~[cattle-framework-lock-0.5.0-SNAPSHOT.jar:na]
        at io.cattle.platform.lock.impl.AbstractLockManagerImpl.tryLock(AbstractLockManagerImpl.java:25) ~[cattle-framework-lock-0.5.0-SNAPSHOT.jar:na]
        at io.cattle.platform.lock.impl.AbstractLockManagerImpl.tryLock(AbstractLockManagerImpl.java:47) ~[cattle-framework-lock-0.5.0-SNAPSHOT.jar:na]
        at io.cattle.platform.configitem.version.impl.ConfigItemStatusManagerImpl.runUpdateForEvent(ConfigItemStatusManagerImpl.java:85) ~[cattle-config-item-common-0.5.0-SNAPSHOT.jar:na]
        at io.cattle.platform.systemstack.listener.SystemStackUpdate.globalServiceUpdate(SystemStackUpdate.java:100) ~[cattle-system-stack-0.5.0-SNAPSHOT.jar:na]
        at sun.reflect.GeneratedMethodAccessor1095.invoke(Unknown Source) ~[na:na]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_72]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_72]
        at io.cattle.platform.eventing.annotation.MethodInvokingListener$1.doWithLockNoResult(MethodInvokingListener.java:76) ~[cattle-framework-eventing-0.5.0-SNAPSHOT.jar:na]
        at io.cattle.platform.lock.LockCallbackNoReturn.doWithLock(LockCallbackNoReturn.java:7) ~[cattle-framework-lock-0.5.0-SNAPSHOT.jar:na]
        at io.cattle.platform.lock.LockCallbackNoReturn.doWithLock(LockCallbackNoReturn.java:3) ~[cattle-framework-lock-0.5.0-SNAPSHOT.jar:na]
        at io.cattle.platform.lock.impl.AbstractLockManagerImpl$3.doWithLock(AbstractLockManagerImpl.java:40) ~[cattle-framework-lock-0.5.0-SNAPSHOT.jar:na]
        at io.cattle.platform.lock.impl.LockManagerImpl.doLock(LockManagerImpl.java:33) ~[cattle-framework-lock-0.5.0-SNAPSHOT.jar:na]
        at io.cattle.platform.lock.impl.AbstractLockManagerImpl.lock(AbstractLockManagerImpl.java:13) ~[cattle-framework-lock-0.5.0-SNAPSHOT.jar:na]
        at io.cattle.platform.lock.impl.AbstractLockManagerImpl.lock(AbstractLockManagerImpl.java:37) ~[cattle-framework-lock-0.5.0-SNAPSHOT.jar:na]
        at io.cattle.platform.eventing.annotation.MethodInvokingListener.onEvent(MethodInvokingListener.java:72) ~[cattle-framework-eventing-0.5.0-SNAPSHOT.jar:na]
        ... 10 common frames omitted
```

**Results:** 
- Either no error creating the environment.
- Or disable using spaces in the UI, so we don't create a catalog with a name with spaces.

**Comment by mrajashree** [comment] 2017-02-23 19:03
@leodotcloud since @joshwget is working on catalog-service I'm removing myself and assigning it to him.

**Comment by joshwget** [comment] 2017-02-23 19:09
We shouldn't allow spaces in catalog names. They're used as part of the URL route to fetch templates/versions. @vincent99 Let me know if you want me to add this validation server side.

**Comment by leodotcloud** [comment] 2017-02-23 23:40
@joshwget I guess we would need validation both in UI and also on backend as well. Because some of the users might be using our API to add a catalog bypassing the UI.

**Comment by vincent99** [comment] 2017-02-24 22:54
Why not?  Space is a perfectly cromulent character, it just has to be escaped as `+` or `%20`.  How do you handle any other special characters?

**Comment by zambon** [comment] 2017-08-18 21:42
This used to be a problem for "regular" templates too (#3124).

**Comment by loganhz** [comment] 2018-10-05 02:01
I can not reproduce this issue in v1.6.22
Please let us know in a comment if you can still reproduce the issue, and we'll reopen it

**Closed by loganhz** 2018-10-05 02:01 UTC
Labels: area/catalog, area/catalog-service, kind/bug
