### ISSUE TITLE
Links tab on service page

### ISSUE THREAD

**Issue by kaos** [rancher/rancher#3684] opened 2016-02-24 11:27 UTC
Rancher Version: 0.59.1

Docker Version: n/a

OS: RedHat

Steps to Reproduce:

Create a bunch identical stacks, with a dummy service in each.
Add a LB service and link each service from the dummy stacks to it.
View the links on the links tab on the LB service page.

Results: 

Something like:
![image](https://cloud.githubusercontent.com/assets/72965/13283983/89ffc476-daf1-11e5-9092-01ca98b7f9dc.png)

Expected:

As above, but including the stack name (at least when different from that of the LB service itself). And in case the link is aliased, the alias as well.

It used to present the service links with alias nicely in the old ui.

**Comment by deniseschannon** [comment] 2016-02-24 14:53
Duplicate of https://github.com/rancher/rancher/issues/2823

@kaos it looks like you gave it a +1 the issue last time. :)

**Closed by deniseschannon** 2016-02-24 14:53 UTC

**Comment by kaos** [comment] 2016-02-24 16:04
lol, will have to plead amnesia :p
