### ISSUE TITLE
Edit from main environment page doesn't allow me to add members

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#1471] opened 2015-07-09 22:09 UTC
v0.27.0-rc1
Steps:
1.  Authenticate
2.  Go to Manage Environments page
3.  Add a Environment
4.  Refresh the page
5.  Click on edit for one of the environments in your list
6.  Try to add a member

Results:  Error saying user or organization not found
![image](https://cloud.githubusercontent.com/assets/11514927/8608038/1b73dd12-264c-11e5-999f-13454330a1a3.png)

Expected: Should add member

**Comment by deniseschannon** [comment] 2015-07-31 18:44
Pre-duplicate of https://github.com/rancher/rancher/issues/1590 which has a video. This is only valid for the first time.

**Closed by deniseschannon** 2015-07-31 18:44 UTC
Labels: area/environment, area/ui, kind/bug
