### ISSUE TITLE
[2.6.4] node driver provisioning of RKE clusters fails in certain use-cases when using a private CA and proxy 

### ISSUE THREAD

**Issue by rosskirkpat** [rancher/rancher#37392] opened 2022-04-18 22:47 UTC
**Rancher Server Setup**
- Rancher version: v2.6.4
- Installation option (Docker install/Helm Chart): helm
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): any
- Proxy/Cert Details: downstream proxy required as well as private CA for Rancher

Certain airgap environments may be unable to provision RKE node driver clusters due to a bug in rancher-machine where it does not use the NO_PROXY environment variable when running in a Rancher jail. This causes node driver provisioning of RKE clusters to fail in certain use-cases, specifically with the use of a private CA for Rancher as well as requiring a proxy to be configured for downstream RKE node-driver clusters. End-users with a similar environment setup should not upgrade to 2.6.4 or attempt to provisiong new clusters at this time.

**Comment by jiaqiluo** [comment] 2022-04-19 18:02
same issue as https://github.com/rancher/rancher/issues/37295

**Comment by snasovich** [comment] 2022-04-21 18:13
Per the comment above the issue is a duplicate. Closing.

**Closed** 2022-04-21 18:13 UTC
Labels: kind/bug, area/machine, area/rke, [zube]: Done, alpha-priority/0
