### ISSUE TITLE
Internal/External ipaddress missing for hosts in rhel clusters.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#14600] opened 2018-07-17 23:29 UTC
Steps to reproduce the problem:

Create a kubernetes cluster (defaults to k8s 1.10) with 3 rhel 7.5 hosts with native docker 1.12(or docker 1.13)

Upgrade cluster to k8s 1.11.

After upgrading the cluster , I was able to see all the hosts in the setup have the Internal/External ipaddress set.

But after a while i see that 1 of the nodes is missing ipaddress.

```
> kubectl get node ip-172-16-100-8.us-west-2.compute.internal  -o json | jq ".status.addresses"
[
  {
    "address": "ip-172-16-100-8.us-west-2.compute.internal",
    "type": "Hostname"
  }
]
```

**Comment by galal-hussein** [comment] 2018-10-05 22:43
the issue is related to the kubernetes issue: https://github.com/kubernetes/kubernetes/issues/68270

**Comment by alena1108** [comment] 2018-10-22 18:46
https://github.com/rancher/rke/issues/860

**Comment by alena1108** [comment] 2018-10-22 18:46
The issue is only fixed with k8s 1.12

**Comment by alena1108** [comment] 2019-01-04 21:47
Can be tested with `rancher/server:v1.6.26-rc1` and k8s 1.11.6

**Comment by soumyalj** [comment] 2019-01-08 00:58
Tested with rancher/server:v1.6.26-rc1 and k8s 1.11.6. 
Created a K8s setup with RHEL 7.6 and native Docker 1.13.1. 
All the nodes had the internal and external IP addresses intact. Example below:
```
[
  {
    "address": "a.b.c.d.e",
    "type": "InternalIP"
  },
  {
    "address": "f.g.h.i.k",
    "type": "ExternalIP"
  },
  {
    "address": "ip-abcde.us-east-2.compute.internal",
    "type": "Hostname"
  }
]

```
Automation runs were successful on this setup.

**Closed by soumyalj** 2019-01-08 00:58 UTC
Labels: internal, kind/bug, status/has-dependency, status/resolved, status/to-test, version/1.6

**Comment by mrmason** [comment] 2019-01-11 20:02
We've been running this for a few days now and can confirm it's all working correctly.
