### ISSUE TITLE
Keys in API & Keys cannot be deleted.

### ISSUE THREAD

**Issue by mysim1** [rancher/rancher#12306] opened 2018-03-27 07:01 UTC
**Rancher server version -** 
DockerHub: master (27 march 2018)

**Rancher agent version -**
DockerHub: master (27 March 2018)

**Steps to reproduce the problem:**
- Navigate to API & Keys
- Add new Key
- Delete newly created key

**User is presented with this error message:**
```
Error deleting
no token store available
```

**Docker version: (`17.03.2`)**

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
ubuntu 16.04 LTS

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
Bare-metal

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
Single Node Rancher

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**
Default RKE

**Comment by superseb** [comment] 2018-03-27 07:38
Thanks for reporting, duplicate of https://github.com/rancher/rancher/issues/12138

**Closed by superseb** 2018-03-27 07:38 UTC
