### ISSUE TITLE
Monitoring v2 14.5.100-rcx fails to install with error "Error: configmaps "rancher-monitoring-etcd" already exists" 

### ISSUE THREAD

**Issue by slickwarren** [rancher/rancher#32024] opened 2021-04-09 20:32 UTC
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
* deploy downstream linux cluster
* install monitoring v2 with default settings

**Result:**
* install of monitoring v14.5.100-rc3 fails with error "Error: configmaps "rancher-monitoring-etcd" already exists"

**Other details that may be helpful:**
* a reinstall of monitoring using the same settings will deploy monitoring
* does not 
**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): v2.5.8-rc2
- Installation option (single install/HA): HA

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): Linode
- Machine type (cloud/VM/metal) and specifications (CPU/memory): 12 vCPU (3 nodes, 4 vCPU each)
- Kubernetes version (use `kubectl version`):1.20.5

- Docker version (use `docker version`):20.10.5

**Comment by aiyengar2** [comment] 2021-04-12 23:41
This is a simple fix caused by the fact that https://github.com/rancher/charts/blob/771a8d4616b58901408752b0429daf622c2e5cb0/charts/rancher-monitoring/rancher-monitoring/14.5.100-rc05/templates/rancher-monitoring/dashboards/rancher/etcd-dashboards.yaml#L6 and https://github.com/rancher/charts/blob/771a8d4616b58901408752b0429daf622c2e5cb0/charts/rancher-monitoring/rancher-monitoring/14.5.100-rc05/templates/grafana/dashboards-1.14/etcd.yaml#L13 have the same name.

**Comment by thehejik** [comment] 2021-04-14 16:39
**Test report:**
I was able reproduce this issue on `rancher:2.5.8-rc3` with v2 `rancher-monitoring-14.5.100-rc03` chart from `dev-v2.5` repo. 

I verified the problem is solved in `rancher-monitoring-14.5.100-rc07` - I tried fresh installation and also installation over "leftover" resources after uninstalling -rc03

Closing.

**Closed by thehejik** 2021-04-14 16:39 UTC
Labels: [zube]: QA Working, kind/bug-qa, priority/0

**Comment by thehejik** [comment] 2021-04-15 12:36
In addition I did try also upgrade from `9.4.202` to `14.5.100-rc07` on Linux cluster with `rancher:2.5.8-rc4`. It's working ok.
