### ISSUE TITLE
Rancher Server Web UI does not show logging content of any pod in the log panel

### ISSUE THREAD

**Issue by madhosoi** [rancher/rancher#37820] opened 2022-05-25 09:30 UTC
**Rancher Server Setup**
- Rancher version: 2.6.5
- Installation option (Docker install/Helm Chart): Helm RKE1
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): v.1.20 RKE1
- Proxy/Cert Details: Nginx Ingress behind F5 bigIP as Load balancer

**Information about the Cluster**
- Kubernetes version: 1.20
- Cluster Type (Local/Downstream): Local/Imported
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider):

**User Information**
- What is the role of the user logged in? Admin/Cluster Owner
   
**Describe the bug**
After almost 3 years of upgrades (from 2.5 to 2.6.5) and usage with very good feedback, I want your help to solve this issue that only happens to some users. The error is that the log panel is not fully loaded (it does not show the bottom status bar where we can select the container or the logging conditions) when open any logging (View Logs option of any pod) or upgrade any Application. What is worrying me more is the fact that only happens to some users.

**To Reproduce**
Login with user credentials
Go to workloads, pods of, per example, System Namespaces
Open "View Logs" of any pod of the list

**Result**
<img width="777" alt="image" src="https://user-images.githubusercontent.com/5636474/170229865-2ce6aa2c-2a45-4df2-8124-f3c77c9cb1cb.png">

**Expected Result**
<img width="731" alt="image" src="https://user-images.githubusercontent.com/5636474/170230311-c9a82cd3-ab8d-47ef-bf0f-ed8a0c45d2c7.png">

**Comment by madhosoi** [comment] 2022-05-25 09:32
Here you have a clue, related to the frontend:
<img width="924" alt="image" src="https://user-images.githubusercontent.com/5636474/170231003-fe4198ee-8987-4f97-b836-849f87a3a4e0.png">

**Comment by MaxenceAdnot** [comment] 2022-05-25 14:16
Seems like a duplicate of : https://github.com/rancher/rancher/issues/37819

**Comment by madhosoi** [comment] 2022-05-26 07:49
Thanks for the workaround @MaxenceAdnot !
Works like a charm!

**Comment by richard-cox** [comment] 2022-06-23 08:42
Closing as duplicate of https://github.com/rancher/dashboard/issues/5984.

A fix is coming in 2.6.6, including a change to automatically update the bad settings.

Until then there are two workarounds
- via kubectl - https://github.com/rancher/rancher/issues/37820#issuecomment-1137311698
- via browser - https://github.com/rancher/dashboard/issues/6122#issuecomment-1152394027

**Closed by richard-cox** 2022-06-23 08:42 UTC
