### ISSUE TITLE
Support for extra args and extra binds in UI

### ISSUE THREAD

**Issue by galal-hussein** [rancher/rancher#13165] opened 2018-04-27 19:31 UTC
Currently there is no way in the UI to add extra_args and extra_binds to cluster service configuration, is there a way to pass these options to the services on starting a new cluster

**Comment by superseb** [comment] 2018-04-27 19:33
Duplicate of https://github.com/rancher/rancher/issues/13076, I'll add the extra binds

**Closed by superseb** 2018-04-27 19:33 UTC
Labels: kind/enhancement, version/2.0
