### ISSUE TITLE
"io.rancher.loadbalancer.target" label in API and metadata service

### ISSUE THREAD

**Issue by shotai** [rancher/rancher#2990] opened 2015-12-10 22:05 UTC
So I found the problem is not rancher deleted target label.

If create load balancer through UI, the  "io.rancher.loadbalancer.target" label  cannot be found in metadata service. But if create through rancher compose, that label will be added. (I think because of the docker compose file specified that label)
If edit the load balancer during run time, the target label will not update.

The same thing happens in API, too.

**Comment by shotai** [comment] 2015-12-14 17:07
update issue detail

**Comment by alena1108** [comment] 2015-12-14 17:16
@shotai this would be a duplicate of https://github.com/rancher/rancher/issues/2446. "io.rancher.loadbalancer.target" label gets translated to loadBalancerService "ports" field when executed from rancher-compose; and the label still get propagated and set on the service, so its not missing from the metadata. When executed from the UI, UI translated user input to "ports" field directly, so the labels are not set.

Thats something we are going to refactor in the future as this label-to-parameter conversion introduces a need for reverse conversion when it comes to exporting Rancher objects back to docker-compose.yml as well as propagating this info to rancher metadata.

**Comment by deniseschannon** [comment] 2015-12-14 19:33
i'm going to close in favor of #2446. @shotai Please watch that issue if you'd like updates on it.

**Closed by deniseschannon** 2015-12-14 19:33 UTC
