### ISSUE TITLE
GitHub authentication not working after upgrade

### ISSUE THREAD

**Issue by mimizone** [rancher/rancher#14142] opened 2018-06-22 00:09 UTC
**Rancher versions:**
rancher/server or rancher/rancher: v2.0.3-rc2

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
Bare-metal

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
single node

**Steps to Reproduce:**
- have a `rancher/server:preview` running (version 2.0.0)
- configure GitHub authentication
- have a few users configured, using the cluster
- upgrade to version `rancher/rancher:v2.0.3-rc2` keeping the same volume
- logout of the UI
- try to login again

**Results:**
Attempting to login using GitHub doesn't work and returns that log in the rancher docker container
```
2018/06/21 23:36:07 [ERROR] Received Error from github bad_verification_code, description from github The code passed is incorrect or expired.
2018/06/21 23:36:07 [INFO] Error generating accessToken from github Received Error from github bad_verification_code, description from github The code passed is incorrect or expired.
2018/06/21 23:36:07 [ERROR] API error response 500 for POST /v3-public/githubProviders/github?action=login. Cause: Received Error from github bad_verification_code, description from github The code passed is incorrect or expired.
```

**Solution:**
rolling back to `rancher/rancher:v2.0.2` with the same volume fixes the problem

**Comment by cjellick** [comment] 2018-06-22 01:03
going to close as dupe of https://github.com/rancher/rancher/issues/14143

**Closed by cjellick** 2018-06-22 01:03 UTC
