### ISSUE TITLE
Dnsmasq running on the host will result in Rancher DNS container fail to do recursive DNS query

### ISSUE THREAD

**Issue by aemneina** [rancher/rancher#9562] opened 2017-08-03 02:31 UTC
Network services weren't coming up, and timeout getting IP is a generic error message. Turns out dnsmasq was running on the agent host and bound to port 53. 

metadata-1 logs
```
8/2/2017 7:21:33 PMtime="2017-08-03T02:21:33Z" level=info msg="Subscribing to events"
8/2/2017 7:21:33 PMtime="2017-08-03T02:21:33Z" level=fatal msg="Failed to subscribeGet https://<myRancherURI>/v2-beta: dial tcp: lookup <myRancherURI> on 127.0.0.1:53: read udp 127.0.0.1:38353->127.0.0.1:53: read: connection refused"
8/2/2017 7:21:38 PMtime="2017-08-03T02:21:38Z" level=info msg="Subscribing to events"
8/2/2017 7:21:38 PMtime="2017-08-03T02:21:38Z" level=fatal msg="Failed to subscribeGet https://<myRancherURI>/v2-beta: dial tcp: lookup <myRancherURI> on 127.0.0.1:53: read udp 127.0.0.1:57495->127.0.0.1:53: read: connection refused"
```
metadata-dns logs were empty

seems dns binds 6060, 80 and 53... we should also document those in the agent host docs.

**Comment by yasker** [comment] 2017-09-15 05:46
@aemneina I don't understand. Our metadata DNS service should only use port inside the container. Why is it affected by the ports on the host?

**Comment by yasker** [comment] 2017-09-19 05:43
@aemneina Seems we cannot reproduce this issue. Should we mark this as `status/working`?

**Comment by aemneina** [comment] 2017-09-20 07:27
I was able to reproduce the issue with rancher 1.6.5 and network services 0.2.0 and 0.2.3. Using ubuntu 16.04 as the agent host.

**Comment by aiwantaozi** [comment] 2017-09-20 07:47
@aemneina Cool, thanks a lot, will troubleshoot with the version you just mentioned soon

**Comment by aiwantaozi** [comment] 2017-09-21 09:32
@yasker @aemneina  the dnsmasq change the file /etc/resolv.config in the host, before `172.31.0.2` after `nameserver 127.0.0.1`, and the rancher/metadata just inherit the file to metadata and dns container, it still happens in 1.16.10(rancher server), it doesn't happen in my env because I just use the IP, not domain. It could be easily reproduced by getting inside the metadata or dns container and ping a domain, it will fail. And when we manually change the resolv.conf file inside the container to `172.31.0.2`, it will back to work. 

Here is some wired thing about ping www.baidu.com inside container, after start the dnsmasq, the resolv.conf change to 127.0.0.1, but 

| version | dnsmasq start | dnsmasq stop |
| ------| ------ | ------ |
| 1.6.5 dns | OK | OK |
| 1.6.5 metadata | unknown host |OK |
| 1.6.10 dns | unknown host | OK |
| 1.6.10 metadata | unknown host | OK |

the 1.6.5 dns container could ping some domain, like baidu, qq. but can't ping ahmad-ha.rancher.space

**Comment by aiwantaozi** [comment] 2017-09-22 09:17
@aemneina @yasker In this case, the metadata and dns container could not run, the sequence is the metadata should running first and then the dns use the metadata container network. When we run a dnsmasq on the host, it changes the host /etc/resolv.conf file and then the metadata inherit this file. When metadata try to get up, it just uses the /etc/resolv.conf inherit from the host directly, not our rancher dns. So to fix this problem we can add default nameserver 8.8.8.8 and nameserver 8.8.4.4 to the metadata container /etc/resolv.conf. Then whatever dnsmasq change the host /etc/resolv.conf file will not affect the communication between metadata and server. How do u think?

**Comment by yasker** [comment] 2017-09-24 11:20
@aiwantaozi

We cannot set any arbitrary DNS for the customer.

Let's take a look like what we have now.


What we observed:
1. No DNSMASQ, no problem at all.
2. Start DNSMASQ after Rancher DNS/Metadata service, no problem.
3. Start DNSMASQ before Rancher DNS/Metadata service, and Rancher server is configured using IP as the endpoint of the website, no issue.
4. Start DNSMASQ before Rancher DNS/Metadata service, and Rancher server is configured using a DNS name as the endpoint, metadata service reports error.


Analysis:
1. The issue happens because of DNSMASQ service on the host. But it's not due to port conflict since every port we're running DNS service on is in the container, not on the host. So there won't be a port conflict.
2. The reason for the issue is that DNSMASQ on the host changed the `/etc/resolv.conf`. Since DNSMASQ server is running, `/etc/resolv.conf` will be modified to point to `127.0.0.1`
3. After `rancher-dns` service started, it will pick up the `/etc/resolv.conf` in the host, and use it inside the container. It is the standard behavior of Docker container (unless someone like Rancher update it later). So it will use `127.0.0.1` inside the container network namespace, and it won't work because the host DNS server is in another network namespace.
4. It's also interesting that `127.0.0.1` can be rancher-dns itself if it listens to all IPs. I think the behavior of listening address has changed in 1.6.10.


Solution:

We can prohibit using `127.0.0.1` in the host `/etc/resolv.conf` by checking it when rancher-dns started.

If the user wants to use DNSMASQ on the host, it seems we can recommend user to add `DNSMASQ_EXCEPT=lo` to `/etc/defaults/dnsmasq` to avoid DNSMASQ make itself as the only DNS server on the host. Reference: https://superuser.com/questions/894513/resolv-conf-keeps-getting-overwritten-when-dnsmasq-is-restarted-breaking-dnsmas

**Comment by aiwantaozi** [comment] 2017-09-26 01:33
@yasker There are two containers metadata and dns, the metadata start first and the dns second, the dns container will use the same network with metadata, like config this network, container:metadata. The /etc/resolv.conf in the metadata have changed, we failed in the first container, and the 127.0.0.1 is the only nameserver at that file, we prohibit using 127.0.0.1, it still can't work.

**Comment by yasker** [comment] 2017-09-26 01:54
@aiwantaozi Just make both DNS and metadata container fail if they detect that `resolv.conf` is `127.0.0.1` only. Make sure it applies to `127.0.0.1` only, since if there are other nameservers available along with `127.0.0.1` they will be used as well.

**Comment by aiwantaozi** [comment] 2017-09-26 01:55
Finally: will fail directly if the dns nameserver in resolv.conf can't be used.

**Comment by aiwantaozi** [comment] 2017-09-26 15:05
@yasker  in the absence of the --dns=IP_ADDRESS..., --dns-search=DOMAIN..., or --dns-opt=OPTION... options, docker will filter all localhost addresses, after this filtering, if there are no more nameserver entries left in the container’s /etc/resolv.conf file, the docker daemon adds public Google DNS nameservers (8.8.8.8 and 8.8.4.4).

Because we have the config --dns-search flag, so docker will not do the above for metadata container. the 8.8.8.8 and 8.8.4.4 will not be added.

**Comment by yasker** [comment] 2017-09-27 08:14
Even docker's behavior is to add 8.8.8.8 and 8.8.4.4, it won't work with the customers inside GFW.

**Comment by yasker** [comment] 2017-10-09 22:22
@alena1108 suggested that we should stop the rancher-agent from starting, rather than dealing with separate containers. @vincent99 and I agreed.

@StrongMonkey suggested that we can put the fix in https://github.com/rancher/agent/blob/v1.6/apply.sh#L70-L83 , which will run to kick start agent. 

`
@StrongMonkey : 
that start function is how we start the go-agent binary and should have the bind mount of `resolve.conf` available in there. we can add check on that to prevent launching agent process
`

**Comment by aiwantaozi** [comment] 2017-10-10 17:38
Thanks, I used to want to check this in the agent, but afraid that when we do this on the agent, it will block all the container to start, it that ok? @StrongMonkey If we change in the apply.ch, can the user know the error in the UI?

**Comment by StrongMonkey** [comment] 2017-10-10 17:52
@aiwantaozi This would prevent agent(host) from registering to the rancher server. If you are adding custom hosts, it should fail with repeated error but UI is not able to show it. If you are adding hosts through machine driver, the host will fail and UI can show it. However, i would like to let @cjellick know the design to see if he is ok with it.

**Comment by cjellick** [comment] 2017-10-10 19:10
I'm ok with the approach. GMS does some amount of reporting on the agent's status. I don't know if that includes transferring its logs back.

But, there are other checks we do in the agent. This is fine to add

**Comment by yasker** [comment] 2017-10-10 19:40
@vincent99 suggested that:
1. We just check if any entry in the `resolv.conf` is localhost or `127.x.x.x`.
2. Print a big ASCII art warning for the error.

**Comment by kingsd041** [comment] 2017-10-18 17:33
Tested with rancher-server version v1.6.11-rc4 with rancher/agent:v1.2.7-rc2

When the host starts dnsmasq service after adding the host, rancher/agent can see the error log
Other agent services will not be started.

rancher/agent logs:
```
ERROR: DNS Checking loopback IP address 127.0.0.0/8, localhost or ::1 configured as the DNS server on the host file /etc/resolv.conf, can’t accept it
```

**Comment by deniseschannon** [comment] 2018-03-08 22:39
We have another use case where a customer wants to be able to skip this check. Is it possible to add a flag on the agent so that we can skip the check for those users?

@aiwantaozi

**Comment by aiwantaozi** [comment] 2018-03-12 11:23
@deniseschannon Do we need to skip this check? We use this to check whether user config loopback dns nameserver, if user config loopback dns nameserver and then skip the validate, the metadata could not get up because this container inherited the bad nameserver, when it try to communicate with rancher server and go to nameserver like 127.0.0.1 inside to container will failed.

**Comment by deniseschannon** [comment] 2018-03-12 17:14
@aiwantaozi We need an option to be able to skip the check. I have a customer that specifically wants this check to be skipped.

**Comment by aiwantaozi** [comment] 2018-03-13 05:50
Create two PR for this issue:
https://github.com/rancher/agent/pull/276
https://github.com/rancher/rancher/pull/12085

**Comment by deniseschannon** [comment] 2018-03-13 17:39
In order to skip the default check, you'll need to run the `docker run rancher/agent` command with `-e CATTLE_CHECK_NAMESERVER=false`

**Comment by galal-hussein** [comment] 2018-03-14 19:50
Rancher server: v1.6.15-rc7
Rancher agent: v1.2.10-rc6

I was able to test with and without the flag, the agent showed an error when ran with no flag an it ran successfully with the flag and i can see dns service started successfully.

**Closed by galal-hussein** 2018-03-14 19:50 UTC
Labels: area/agent, area/dns, area/metadata, priority/-1, status/resolved, status/to-test, team/cn
