### ISSUE TITLE
Current install docs say to use "latest" docker tag which hangs

### ISSUE THREAD

**Issue by jeffvictor-tas** [rancher/rancher#4779] opened 2016-05-12 13:40 UTC
The current documentation says to start up a rancher server as:

sudo docker run -d --restart=always -p 8080:8080 rancher/server

This will pull the "latest" which just hangs at "Setting up database".  Specifying tag v1.0.1 allows the install to finish successfully.

Steps to reproduce:

- Create a new ec2 instance from the standard ubuntu ami
- Install docker as: sudo wget -qO- https://get.docker.com/ | sh
- Run: sudo docker run -d --restart=always -p 8080:8080 rancher/server
- Tail the rancher container logs and you'll see it hanging

**Comment by aemneina** [comment] 2016-05-18 21:04
Hi @jeffvictor-tas , I ran the same thing on ec2 and managed to get this up and running, using the same steps you provided. I think one thing to note is that docker 1.11 was installed for me, and I dont  believe thats supported fully by rancher yet. You might want to give this another go and see if you get further this time.

**Comment by jeffvictor-snaphire** [comment] 2016-05-19 01:11
I'm still seeing the same issue.  It just hangs forever at "Setting up database".  See below.  The issue that Rucknar created and linked I think would be a sufficient fix - basically just updating the set up instructions to use the "stable" docker tag rather than "latest" as this does work without issue.

`ubuntu@ip-10-70-4-42:~$ sudo docker run -d --restart=always -p 8080:8080 rancher/server
sudo: unable to resolve host ip-10-70-4-42
Unable to find image 'rancher/server:latest' locally
latest: Pulling from rancher/server
5a132a7e7af1: Pull complete 
fd2731e4c50c: Pull complete 
28a2f68d1120: Pull complete 
a3ed95caeb02: Pull complete 
3286c13024db: Pull complete 
4a932879a44c: Pull complete 
cc288fcde4a5: Pull complete 
1eede30473ee: Pull complete 
19af6415e6c0: Pull complete 
21c5793c8c45: Pull complete 
65657e21c312: Pull complete 
a758a93b12b2: Pull complete 
ab8ccf7a5715: Pull complete 
1be543dfcf53: Pull complete 
Digest: sha256:0cdb03dd5609a09a8b13b51175ec11292d6aa891ce8c41a80a3996e8a8a9bb68
Status: Downloaded newer image for rancher/server:latest
7d6db606472453269167b922a68a4640158c84592c93765f9cb0426127f34007
ubuntu@ip-10-70-4-42:~$ sudo docker version
sudo: unable to resolve host ip-10-70-4-42
Client:
 Version:      1.11.1
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   5604cbe
 Built:        Tue Apr 26 23:30:23 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.11.1
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   5604cbe
 Built:        Tue Apr 26 23:30:23 2016
 OS/Arch:      linux/amd64
ubuntu@ip-10-70-4-42:~$ sudo docker ps -a
sudo: unable to resolve host ip-10-70-4-42
CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS              PORTS                              NAMES
7d6db6064724        rancher/server      "/usr/bin/s6-svscan /"   15 seconds ago      Up 13 seconds       3306/tcp, 0.0.0.0:8080->8080/tcp   serene_panini
ubuntu@ip-10-70-4-42:~$ sudo docker logs -f serene_panini
sudo: unable to resolve host ip-10-70-4-42
160519  1:07:32 [Note] /usr/sbin/mysqld (mysqld 5.5.47-0ubuntu0.14.04.1) starting as process 23 ...
Uptime: 2  Threads: 1  Questions: 2  Slow queries: 0  Opens: 33  Flush tables: 1  Open tables: 26  Queries per second avg: 1.000
Setting up database

`

**Comment by vincent99** [comment] 2016-05-19 02:46
The equivalent of the weekly released we've traditionally done is `latest`, currently `v1.1.0-dev1`, and that is the recommended tag for most people to use because of things like it includes the features that are shown in monthly meetups that would not normally be in `stable` yet.  So it is not an accident that the docs say `latest`.

This particular issue is that the MySQL daemon is just crashing on first run in some circumstance.  I've seen it before once, we haven't figured out the cause yet but I'm sure it will be a packaging issue that has very little to do with the actual version of the Rancher software that would eventually be run.  The time I saw it just `docker start`ing the container again worked.

**Comment by deniseschannon** [comment] 2016-05-26 05:23
@jeffvictor-snaphire We just released a new release yesterday. Let me know if you are still facing the same issues. 

We haven't seen anyone else face this issue, so it would be good to know if you continue to see it on our current latest (v1.1.0-dev2).

Alternatively, you could do what @vincent99 suggested, which is to use our `:stable` tag.

**Comment by legoheld** [comment] 2016-06-14 07:17
I had the same issue with 1.0.2 (:stable) as also with 1.1.0-dev4 (:latest)
With 1.0.1 it was working.
My /var/lib/mysql was mounted from the host and empty.

**Comment by deniseschannon** [comment] 2016-06-20 21:28
@legoheld Can you share the docker command you used to start your instance?

**Comment by legoheld** [comment] 2016-06-22 06:33
Yes sure:
`docker run -d -v /docker/rancher:/var/lib/mysql --restart=always -p 8080:8080 --name rancher-server rancher/server:stable`
Some infos about my host:
> Docker version 1.10.1, build 9e83765
> Ubuntu 14.04.3 LTS

**Comment by deniseschannon** [comment] 2016-06-24 18:45
And does your database already have Rancher running on it or is it a new setup?

@legoheld Can you open a new issue for yours? It sounds as if you're having issues with a bind mount for sql versus the original user.

@jeffvictor-snaphire I'll close this issue and if you still have issues. Please open a new ticket.

**Closed by deniseschannon** 2016-06-24 18:45 UTC
Labels: kind/question
