### ISSUE TITLE
HTTP download within container pauses for 2 minutes on specific URLs (on VirtualBox)

### ISSUE THREAD

**Issue by hendryluk** [rancher/rancher#4285] opened 2016-04-04 14:09 UTC
Rancher Version: v.1.0.0

Docker Version: 1.9.1, build a34a1d5

OS: Ubuntu 14.04.3 LTS inside VirtualBox (on OSX 10.11.3)

Steps to Reproduce: 
- Start a rancher stack with an ubuntu image, e.g. docker-compose.yml:

```
test:
  log_driver: ''
  labels:
    io.rancher.container.pull_image: always
  tty: true
  log_opt: {}
  image: ubuntu:14.04.3
  stdin_open: true
```
- From within the container (e.g. via docker exec, or rancher's execute shell), curl or wget to https://registry.npmjs.org/kew

Results: 
It responds quickly, but then abruptly pauses when it reaches about 32kb (the total size of the response is ~35k) for around 2 minutes 40 seconds, before proceeding to download the rest of it. The pause always happens at exactly the same byte.

This problem does not happen when the same docker-compose.yml is started up using docker-compose directly (without rancher). The same wget/curl returns immediately (0.02s), returned by exactly the same remote IP (103.245.222.162:443).
Traceroute and ping do not reveal anything different between when the container is started from rancher or docker-compose, which indicates that it may not be related to dns or network topology issue.
Also, if I start the service on rancher with net:host, the problem goes away.

Oddly, it's totally fine on much bigger files from the same web-server, e.g. https://registry.npmjs.org/phantomjs (107kb from 103.245.222.162:443). In general, most URLs are fine. There are specific URLs where this mysterious pause happens, which causes a lot of npm installs and apt-get installs to be extremely slow to complete.

Expected:
wget and curl should complete immediately, just as it does on a container that's stood up by docker-compose directly.

**Comment by deniseschannon** [comment] 2016-04-08 17:03
Using v1.0.0 and v1.0.1-rc1 I am unable to reproduce this issue.

I followed your steps exactly as you listed but did not get any delay/pause. 

I am running my setup in GCE on ubuntu 14.04 with Docker 1.10.3.

**Comment by hendryluk** [comment] 2016-04-09 14:46
Thanks Denise for looking into it.
I can confirm that this problem only occurs on VirtualBox (both on 5.0.8 r103449 and latest 5.0.16 r105871). 
To make this consistently reproducible, I tried using this vagrant: https://github.com/hendryluk/os-vagrant, and it does reproduce the problem.
Same symptom: when I use rancher to start the ubuntu container, I'm getting a network problem. But no issue when it's started up without rancher.
I noticed from ifconfig that I'm getting a lot of dropped packets:
```
root@c45f10ea6d8e:/# ifconfig
eth0      Link encap:Ethernet  HWaddr 02:f3:da:e7:7b:99
          inet addr:172.17.0.5  Bcast:0.0.0.0  Mask:255.255.0.0
          inet6 addr: fe80::f3:daff:fee7:7b99/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1402  Metric:1
          RX packets:26 errors:0 dropped:26 overruns:0 frame:0
          TX packets:28 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0
          RX bytes:2930 (2.9 KB)  TX bytes:2110 (2.1 KB)

lo        Link encap:Local Loopback
          inet addr:127.0.0.1  Mask:255.0.0.0
          inet6 addr: ::1/128 Scope:Host
          UP LOOPBACK RUNNING  MTU:65536  Metric:1
          RX packets:0 errors:0 dropped:0 overruns:0 frame:0
          TX packets:0 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0
          RX bytes:0 (0.0 B)  TX bytes:0 (0.0 B)
```

Whereas with normal docker-compose, I get "dropped:0".
```
root@199ccfc2c56a:/# ifconfig
eth0      Link encap:Ethernet  HWaddr 02:42:ac:11:00:04
          inet addr:172.17.0.4  Bcast:0.0.0.0  Mask:255.255.0.0
          inet6 addr: fe80::42:acff:fe11:4/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:1472 errors:0 dropped:0 overruns:0 frame:0
          TX packets:751 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0
          RX bytes:1107923 (1.1 MB)  TX bytes:41429 (41.4 KB)

lo        Link encap:Local Loopback
          inet addr:127.0.0.1  Mask:255.0.0.0
          inet6 addr: ::1/128 Scope:Host
          UP LOOPBACK RUNNING  MTU:65536  Metric:1
          RX packets:0 errors:0 dropped:0 overruns:0 frame:0
          TX packets:0 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0
          RX bytes:0 (0.0 B)  TX bytes:0 (0.0 B)
```
I can't quite see the reason why the different outcomes between the two.
Could you provide any pointer on anything different with the network settings between rancher and normal docker-compose that could potentially be causing this problem on VirtualBox? Would really appreciate any advice on diagnosing this further, or if you could confirm whether you could reproduce this on VirtualBox.

**Comment by aemneina** [comment] 2016-11-04 15:34
hey @hendryluk can you try changing out the nic driver for the VM? I'll close this out, feel free to reopen if you think this is a rancher specific issue.

**Closed by aemneina** 2016-11-04 15:34 UTC
Labels: kind/question
