### ISSUE TITLE
Machine resource stuck in state "Resource scheduled for deletion"

### ISSUE THREAD

**Issue by InterFelix** [rancher/rancher#35148] opened 2021-10-16 20:07 UTC
**Rancher Server Setup**
- Rancher version: 2.6.0
- Installation option (Docker install/Helm Chart): Helm Chart
   - If Helm Chart, Kubernetes Cluster and version: k3s, version unknown
- Proxy/Cert Details: NGINX reverse proxy with Let'sEncrypt cert

**Information about the Cluster**
- Kubernetes version: v1.18.20
- Cluster Type (Local/Downstream): Downstream
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider): Custom

**Describe the bug**

A machine resource in the cluster management section is stuck in state "Resource scheduled for deletion" and has been for over a month now.
All attempts at getting rid of it have failed.
The corresponding K8s Node Resource is gone, there is no trace left.
However, when I try to add the node back after reinstalling the OS, it does not reappear, in fact, nothing happens.

**To Reproduce**
 
I don't have any clue how it ended up in this state.

**Result**

**Expected Result**

**Screenshots**

![grafik](https://user-images.githubusercontent.com/29462559/137600892-ac5a2ef8-03bb-4461-9cb2-fefb64b35abe.png)
Node resources in cluster view
![grafik](https://user-images.githubusercontent.com/29462559/137600897-cc1c4a5f-7e64-4c3d-bacd-f4c2f4c09dd4.png)
Machine resources in cluster management view

**Additional context**

SURE-3708

**Comment by waster** [comment] 2021-11-09 09:49
Agree, the same thing.

**Comment by goodpp** [comment] 2021-11-16 03:33
I have the same thing...
>>> That's how I handled it
bash: kubectl get job
NAME                        COMPLETIONS   DURATION   AGE
cattle-node-cleanup-2zngd   0/1           17m        17m
cattle-node-cleanup-888c9   1/1           11m        12d
cattle-node-cleanup-fx8zv   0/1           19m        19m

bash: kubectl delete job cattle-node-cleanup-2zngd  cattle-node-cleanup-fx8z
v  cattle-node-cleanup-888c9
job.batch "cattle-node-cleanup-2zngd" deleted
job.batch "cattle-node-cleanup-fx8zv" deleted
job.batch "cattle-node-cleanup-888c9" deleted

>>> done <<<

>>> Cause：Node-Selectors can't schedule to kubernetes.io/hostname=node-name-001
kubectl describe pods cattle-node-cleanup-2zngd
 
 Node-Selectors:  kubernetes.io/hostname=node-name-001
Tolerations:     node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
Events:
  Type     Reason            Age        From  Message
  ----     ------            ----       ----  -------
  Warning  FailedScheduling  <unknown>        0/7 nodes are available: 7 node(s) didn't match Pod's node affinity.
  Warning  FailedScheduling  <unknown>        0/7 nodes are available: 7 node(s) didn't match Pod's node affinity.

**Comment by eumel8** [comment] 2021-11-16 23:41
@goodpp good catch! Most of the job completion is 0/1 in your example, so the job couldn't get an end. No nodes available could be an option. Or any kind of PodSecurityPolicy, in our case `restricted` psp as cluster default in default namespace, where the job will running:
```
0s          Warning   FailedCreate              job/cattle-node-cleanup-6xc9h             Error creating: pods "cattle-node-cleanup-6xc9h-" is forbidden: PodSecurityPolicy: unable to admit pod: [spec.volumes[0]: Invalid value: "hostPath": hostPath volumes are not allowed to be used spec.volumes[0]: Invalid value: "hostPath": hostPath volumes are not allowed to be used]
```
We can edit some fancy stuff to the Rancher default psp, or use a RoleBinding to run the pod for the job in unrestricted-psp:

```
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  annotations:
    serviceaccount.cluster.cattle.io/pod-security: unrestricted
  name: cattle-node-cleanup
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: unrestricted-clusterrole
subjects:
- kind: ServiceAccount
  name: default
  namespace: default
```

this works as a workaround, but this kind of job should be moved to system namespace to get the right permissions there
ref code: https://github.com/rancher/rancher/blob/release/v2.6/pkg/controllers/management/node/cleanup.go

@InterFelix another option to cleanup nodes is to remove the finalizers in local cluster context:

```
kubectl -n <cluster-id> edit nodes.management.cattle.io m-3ea5d66b70fd
```

The node will disappear from nodes.management.cattle.io. This fancy machine-id is based on the node name, so you will not able to join the cluster this node again while this machine-id is still in the cluster management. On Rancher API you should see something with error 409 or 500, because Rancher refused the connection with the same node name.

**Comment by thedadams** [comment] 2022-04-04 16:08
### Root cause
It is possible for the v3 Node to go through the controllers one last time after we have deleted the v1 Node from the downstream cluster. This issue can also be reproduce by powering down the VM from the cluster before deleting the VM from Rancher.

### What was fixed, or what changes have occurred
When the control plane of the downstream cluster is not able contact the node (like it is shutdown), then the cleanup job will get created and the pod for that job will get scheduled, but the pod will remain in a Pending state. This means that the pod may have to force-deleted in order for it to get cleaned. Rancher will now do that.

### Areas or cases that should be tested
1. Create a custom RKE1 cluster with Kubernetes version v1.21.10 (I don't know if the Kubernetes version is important, but I was able to reproduce this issue with that version).
2. Provision three custom nodes: one with all roles and two with a worker-only role.
3. Once all nodes are active, turn the VM off one of the worker nodes.
4. Once this worker node is unavailable in the Rancher UI, delete the node from the Rancher UI. It should be deleted.
5. Without turning the VM off, delete the second worker-only node. It should be deleted.

### What areas could experience regressions?
Deleting nodes from custom RKE1 clusters.

### Are the repro steps accurate/minimal?
Yes

**Comment by Josh-Diamond** [comment] 2022-04-07 23:02
Ticket #35148 - Test Results - [Duplicate of [#37063](https://github.com/rancher/rancher/issues/37063)]

With Docker on single-node instance:

Reproduction Failure on rancher `v2.6-9ef92c2168bd91ce6b05734731d9c2c21c42a5f4-head`:
1. Unable to reproduce; I have experienced this error first hand and am able to ensure quality verification provided below


Verified on rancher `v2.6-6955cebc208a925e3e6f42a3a7f5d24dcd7d2585-head`:
1. Fresh install of rancher `v2.6-head`
2. Provision an RKE1 Custom downstream cluster, k8s `v1.21.10`, with 3 nodes; One with all 3 roles [etcd, cp, wkr], and two as dedicated worker nodes
3. Once cluster is `Active` and stable, turn off VM of one of the dedicated worker nodes
4. Once the node becomes `Unavailable`, delete it from the rancher UI - [SUCCESSFULLY_DELETED]
5. With both remaining nodes in an `Active` state, delete the remaining dedicated worker node - [SUCCESSFULLY_DELETED]
6. Verified - All steps are executed successfully; No nodes caught in "hang" state and unable to be removed

**Closed by Josh-Diamond** 2022-04-07 23:02 UTC
Labels: internal, [zube]: QA Working, QA/XS, team/area2
