### ISSUE TITLE
Switching between authentication type shows all accounts regardless of authentication type

### ISSUE THREAD

**Issue by deniseschannon** [rancher/rancher#2013] opened 2015-09-10 05:05 UTC
v0.37.0-rc1

Steps to Reproduce

1. Enable Github. 
2. Add another user to access control and default environment and have them login so they show up on the Accounts tab. 
3. Deactivate user. 
4. Disable GitHub.
5. Enable local auth. 
6. Go to Accounts tab. 

Result: Deactivated user still shows up in account list. 

Expected Result: Since I switched from GitHub to Local auth, I'd assume any accounts from GitHub would not show up as it doesn't make sense.

**Comment by hibooboo2** [comment] 2015-09-10 05:19
Accounts page shows all accounts we do not delete accounts or resources when auth types are changed. This is not a bug it is by design weather this is the behavior we want to keep or not is up for discussion with @ibuildthecloud @will-chan and @vincent99

**Comment by tfiduccia** [comment] 2016-07-15 23:17
Closing and added to #5450 for single point of reference

**Closed by tfiduccia** 2016-07-15 23:17 UTC
Labels: area/access-control, kind/enhancement
