### ISSUE TITLE
Drop k8s 1.9 and 1.10 from Rancher cluster provisioning

### ISSUE THREAD

**Issue by cjellick** [rancher/rancher#17399] opened 2019-01-11 13:37 UTC
With 1.13 being the new default in v2.2 and k8s's policy of supporting 3 releases, we should drop 1.9 and 1.10 from new cluster provisioning.
If this is a dupe, feel free to close it @alena1108

**Comment by alena1108** [comment] 2019-01-13 05:08
https://github.com/rancher/rke/issues/1075

**Comment by alena1108** [comment] 2019-01-13 05:08
Closing as a duplicate of rke issue

**Closed by alena1108** 2019-01-13 05:08 UTC
Labels: kind/task, team/ca
