### ISSUE TITLE
helm + watch closed before Until timeout

### ISSUE THREAD

**Issue by scd-systems** [rancher/rancher#9847] opened 2017-09-08 07:34 UTC
Hi,

we got reproducable error messages from tiller/helm during helm install process of a job chart.
The job it self gets finished successfully in kubernetes, but helm/tiller dies with the error message from above.

kube-apiserver reports very often:
> 8.9.2017 09:16:03E0908 07:16:03.467638       1 watch.go:228] unable to encode watch object: write tcp 10.42.188.75:6443->10.42.51.83:36618: write: connection reset by peer (&streaming.encoder{writer:(*framer.lengthDelimitedFrameWriter)(0xc4206ebbc0), encoder:(*versioning.codec)(0xc425b55b90), buf:(*bytes.Buffer)(0xc421a29ea0)})
> 8.9.2017 09:16:03E0908 07:16:03.467674       1 watch.go:228] unable to encode watch object: write tcp 10.42.188.75:6443->10.42.51.83:36618: write: connection reset by peer (&streaming.encoder{writer:(*framer.lengthDelimitedFrameWriter)(0xc4217c2760), encoder:(*versioning.codec)(0xc422ce5050), buf:(*bytes.Buffer)(0xc421962230)})

Tiller log:

> 8.9.2017 09:16:35[tiller] 2017/09/08 07:16:35 preparing install for jobx
8.9.2017 09:16:35[storage] 2017/09/08 07:16:35 getting release history for "jobx"
8.9.2017 09:16:35[tiller] 2017/09/08 07:16:35 rendering postinstall chart using values
8.9.2017 09:16:352017/09/08 07:16:35 info: manifest "postinstall/templates/configure-storage-nfs.yaml" is empty. Skipping.
8.9.2017 09:16:35[tiller] 2017/09/08 07:16:35 performing install for jobx
8.9.2017 09:16:35[tiller] 2017/09/08 07:16:35 executing 5 pre-install hooks for jobx
8.9.2017 09:16:35[kube] 2017/09/08 07:16:35 building resources from manifest
8.9.2017 09:16:35[kube] 2017/09/08 07:16:35 creating 1 resource(s)
8.9.2017 09:16:35[kube] 2017/09/08 07:16:35 Watching for changes to Job configure-buckets with timeout of 5m0s
8.9.2017 09:16:35[kube] 2017/09/08 07:16:35 Add/Modify event for configure-buckets: ADDED
8.9.2017 09:16:35[kube] 2017/09/08 07:16:35 configure-buckets: Jobs active: 1, jobs failed: 0, jobs succeeded: 0
8.9.2017 09:17:06[tiller] 2017/09/08 07:17:06 warning: Release jobx pre-install postinstall/templates/couchbase-buckets.yaml could not complete: watch closed before Until timeout
8.9.2017 09:17:06[tiller] 2017/09/08 07:17:06 failed install perform step: watch closed before Until timeout

Tiller version: 2.6.1

`helm version:`
> Client: &version.Version{SemVer:"v2.6.1", GitCommit:"bbc1f71dc03afc5f00c6ac84b9308f8ecb4f39ac", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.6.1", GitCommit:"bbc1f71dc03afc5f00c6ac84b9308f8ecb4f39ac", GitTreeState:"clean"}

**Rancher versions:**
rancher/server: 1.6.8
rancher/agent: 1.2.6

**Infrastructure Stack versions:**
healthcheck: 0.3.3
ipsec: 0.1.4
network-services: 0.2.6
scheduler: 0.8.2
kubernetes (if applicable): 1.7.4

**Docker version: (`docker version`,`docker info` preferred)** 
1.12.6

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)** 
Container Linux by CoreOS 1465.6.0

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)** 
vSphere

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)** 
single rancher

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**
Kubernetes

**Steps to Reproduce:**
helm install --tiller-namespace anyname -n jobx -f values.yaml --namespace anyname jobs/

**Results:**
Error: watch closed before Until timeout

**Comment by dbason** [comment] 2017-11-03 03:56
We also see this issue.  At the same time we get timeouts from things trying to communicate with the apiserver, they all get connection reset by peer errors (have seen this from multiple services when we get the error described above).

We are also using vSphere but are using Centos7.  This is sporadic but does seem to happen frequently.

**Comment by scd-systems** [comment] 2017-11-23 10:33
Hi dbason,

Ok, do you plan to fix that issue ?

Kind Regards,

**Comment by dbason** [comment] 2017-11-24 01:51
I think our issue ended up being slightly different to this one.  We are still working on resolving the timeouts to the API server.

**Comment by superseb** [comment] 2017-11-24 14:35
`Connection reset by peer` means some interruption on the network. When this happens, is the overlay network still functioning properly (pings work, ipsec-router/network-manager log nothing about disconnects?).

Is it triggerable by executing certain actions? How many hosts are there in an environment, do they all log connection problems to the API at the same time or at different times? Or not all hosts log connection problems?

**Comment by scd-systems** [comment] 2017-11-27 09:48
Hi superseb,

"Is it triggerable by executing certain actions?", not really.
We just run the helm chart.
The environment have 5 nodes and they log differ.
We also don't have often "Connection reset by peer". Could be related or just be a coincident.

Kind Regards

**Comment by leodotcloud** [comment] 2018-01-03 22:45
```
8.9.2017 09:16:03E0908 07:16:03.467638 1 watch.go:228] unable to encode watch object: write tcp 10.42.188.75:6443->10.42.51.83:36618: write: connection reset by peer 
```

This line sounds similar to: https://github.com/rancher/rancher/issues/10288

**Comment by leodotcloud** [comment] 2018-01-03 22:49
Similar symptoms reported upstream: https://github.com/kubernetes/helm/issues/3273

**Comment by superseb** [comment] 2018-01-27 14:06
Closing as duplicate of https://github.com/rancher/rancher/issues/10288, please re-test when the fix linked in there is released.

**Closed by superseb** 2018-01-27 14:06 UTC
Labels: area/kubernetes, area/networking, status/more-info
