### ISSUE TITLE
[2.5] Backport Kubernetes component status filter

### ISSUE THREAD

**Issue by paynejacob** [rancher/rancher#32607] opened 2021-05-06 23:46 UTC
https://github.com/rancher/rancher/issues/11496

The changes from this pr need to be backported to 2.5: https://github.com/rancher/rancher/pull/32277

**Comment by deniseschannon** [comment] 2021-05-07 15:27
@paynejacob please make sure this is resolved for imported clusters and newly provisioned AKS clusters.

**Comment by slickwarren** [comment] 2021-06-09 16:55
closing as dupe of https://github.com/rancher/rancher/issues/32905

**Closed by slickwarren** 2021-06-09 16:55 UTC
Labels: [zube]: To Test, internal, kind/bug, release-note
