### ISSUE TITLE
NO_PROXY in agent container setting cannot use wildcard

### ISSUE THREAD

**Issue by JayHaoDing** [rancher/rancher#6960] opened 2016-12-07 05:00 UTC
**Rancher Version:**
1.1.4

**Docker Version:**
1.10.3

**OS and where are the hosts located? (cloud, bare metal, etc):**
RHEL 7.2

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle

**Steps to Reproduce:**
start agent container in remote host with command

```
sudo docker run -d --privileged -e http_proxy=http://proxy.domain.com:8080/ -e https_proxy=http://proxy.domain.com:8080/ -e 'NO_PROXY=*.domain.com,localhost,127.0.0.1' -v /var/run/docker.sock:/var/run/docker.sock -v /var/lib/rancher:/var/lib/rancher rancher/agent:v1.0.2 http://rancher.domain.com/v1/scripts/B635DE4F16DF7978F605:1481083200000:N6yRTOfEtvxuZZkUOMbPUs8C6W4
```

Note: `-e 'NO_PROXY=.domain.com,localhost,127.0.0.1'` has also been tried

**Results:** 
Host cannot register to Rancher server, error code

```
time="2016-12-07T04:34:51Z" level="info" msg="Starting event router."
time="2016-12-07T04:34:51Z" level="info" msg="Watching state directory: /var/lib/rancher/state/containers"
time="2016-12-07T04:34:51Z" level="info" msg="Host not registered yet. Sleeping 1 second and trying again." Attempt=0 reportedUuid="cc8e58c8-581c-4489-aaaa-9e976e7b357c"
2016-12-07 04:34:51,776 ERROR root [140238311666704] [_logging.py:54] Received websocket error: [cannot concatenate 'str' and 'int' objects]
```

**Workaround:**
Whole Rancher server address needs to be specified in the NO_PROXY environment variable. i.e.

`-e 'NO_PROXY=rancher.domain.com,localhost,127.0.0.1'`

**Comment by aemneina** [comment] 2016-12-15 22:58
@JayHaoDing the fix for the issue is here: https://github.com/rancher/rancher/issues/7019 it will go out with v1.2.1. I'll close this ticket out.

**Comment by StrongMonkey** [comment] 2016-12-20 02:33
i was able to pass wildcard to agent using the command `docker run -e "NO_PROXY=*.rancher.com" -d --privileged -v /var/run/docker.sock:/var/run/docker.sock -v /var/lib/rancher:/var/lib/rancher rancher/agent:v1.0.2 http://192.168.42.118:8080/v1/scripts/24714367FBE116C844E6:1482192000000:fdECfxSQWU5ZfcVjdcqVCjQJvyA`. In docker inspect i was able to get `"NO_PROXY=*.rancher.com",
                "no_proxy=*.rancher.com",`.

**Comment by deniseschannon** [comment] 2016-12-20 02:46
@JayHaoDing Can you retry with 1.2.1?

**Comment by JayHaoDing** [comment] 2017-01-08 23:55
@deniseschannon sorry for late response, I was on holiday. I just tried 1.2.1 and looks good. We will upgrade to 1.3.0 soon.

**Comment by StrongMonkey** [comment] 2017-01-12 21:00
@deniseschannon I ll close this issue

**Closed by StrongMonkey** 2017-01-12 21:00 UTC
Labels: kind/bug, priority/-1
