### ISSUE TITLE
Bad chart in repo causes constant refresh in UI and logs

### ISSUE THREAD

**Issue by dnoland1** [rancher/rancher#23368] opened 2019-10-11 00:34 UTC
**What kind of request is this (question/bug/enhancement/feature request):**
bug

**Steps to reproduce (least amount of steps as possible):**
Create a git repo with a chart that has a bad chart name, for example (Chart.yaml):
```yaml
name: trying-a-name_with_underscores-and_dashes
version: 1.0.0
appVersion: 1.0.0
description: Blah blah
icon: 
keywords:
- testing
home: https://rancher.co/
```
Add the catalog with this chart. I used https://github.com/dnoland1/testcatalog.git master branch, global.

**Result:**
Catalog is stuck in "Refreshed" state and UI is constantly reporting it is syncing templates:
<img width="1260" alt="image" src="https://user-images.githubusercontent.com/468462/66615823-22e22580-eb83-11e9-8243-7027f8d058b3.png">

Logs show the chart error (expected), but reports templates are updated when they have not changed:
```
2019/10/10 23:51:04 [INFO] Updating global catalog testing
2019/10/10 23:51:14 [INFO] Catalog sync done. 1002 templates created, 0 templates updated, 0 templates deleted
2019/10/10 23:51:14 [ERROR] CatalogController testing [catalog] failed with : failed to update templates. Multiple error occurred: [failed to create template testing-trying-a-name_with_underscores-and_dashes: CatalogTemplate.management.cattle.io "testing-trying-a-name_with_underscores-and_dashes" is invalid: metadata.name: Invalid value: "testing-trying-a-name_with_underscores-and_dashes": a DNS-1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*')]
2019/10/10 23:51:15 [INFO] Updating global catalog testing
W1010 23:52:21.422624       6 reflector.go:270] github.com/rancher/norman/controller/generic_controller.go:175: watch of *v1.Endpoints ended with: too old resource version: 10713 (11164)
2019/10/10 23:53:08 [INFO] Catalog sync done. 1 templates created, 1001 templates updated, 0 templates deleted
2019/10/10 23:53:08 [ERROR] CatalogController testing [catalog] failed with : failed to update templates. Multiple error occurred: [failed to create template testing-trying-a-name_with_underscores-and_dashes: CatalogTemplate.management.cattle.io "testing-trying-a-name_with_underscores-and_dashes" is invalid: metadata.name: Invalid value: "testing-trying-a-name_with_underscores-and_dashes": a DNS-1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*')]
2019/10/10 23:53:08 [INFO] Updating global catalog testing
I1010 23:54:41.711999       6 trace.go:76] Trace[1094921731]: "List /apis/management.cattle.io/v3/catalogtemplates" (started: 2019-10-10 23:54:41.080239232 +0000 UTC m=+10981.764869239) (total time: 631.717702ms):
2019/10/10 23:54:56 [INFO] Catalog sync done. 1 templates created, 1001 templates updated, 0 templates deleted
2019/10/10 23:54:56 [ERROR] CatalogController testing [catalog] failed with : failed to update templates. Multiple error occurred: [failed to create template testing-trying-a-name_with_underscores-and_dashes: CatalogTemplate.management.cattle.io "testing-trying-a-name_with_underscores-and_dashes" is invalid: metadata.name: Invalid value: "testing-trying-a-name_with_underscores-and_dashes": a DNS-1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*')]
2019/10/10 23:54:57 [INFO] Updating global catalog testing
I1010 23:55:42.849791       6 trace.go:76] Trace[995313607]: "List /apis/management.cattle.io/v3/catalogtemplates" (started: 2019-10-10 23:55:42.299470268 +0000 UTC m=+11042.984100276) (total time: 550.273996ms):
Trace[995313607]: [179.523781ms] [179.46153ms] Listing from storage done
Trace[995313607]: [550.270726ms] [366.598986ms] Writing http response done (1040 items)
2019/10/10 23:56:42 [INFO] Catalog sync done. 1 templates created, 1001 templates updated, 0 templates deleted
2019/10/10 23:56:42 [ERROR] CatalogController testing [catalog] failed with : failed to update templates. Multiple error occurred: [failed to create template testing-trying-a-name_with_underscores-and_dashes: CatalogTemplate.management.cattle.io "testing-trying-a-name_with_underscores-and_dashes" is invalid: metadata.name: Invalid value: "testing-trying-a-name_with_underscores-and_dashes": a DNS-1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*')]
2019/10/10 23:56:42 [INFO] Updating global catalog testing
```

**Other details that may be helpful:**
If the bad chart is removed, catalog is not stuck in Refreshed state and UI is not constantly cycling through all the charts in the repo.

May be related to 
https://github.com/rancher/rancher/issues/23256

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI):
v2.2.7

- Installation option (single install/HA):
single install

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported):
Custom
- Machine type (cloud/VM/metal) and specifications (CPU/memory):
AWS EC2 t3a.medium

**Comment by alena1108** [comment] 2019-10-30 00:00
@dnoland1 subsequent catalog refresh on error is by design. On every catalog refresh, we go over the templates and see if any of them need to be updated. If there was an error during this process, it will be retried.

What we'll have to fix though is `Logs show the chart error (expected), but reports templates are updated when they have not changed`. By looking at the code I see that we are not updating the template unless they are changed, but the count gets increased anyway.

**Comment by brendarearden** [comment] 2019-11-18 22:04
@alena1108 for each catalog refresh do we want to add a backoff or an increase to the retry wait time to help decrease the catalog refresh error logging?

**Comment by kandeshvari** [comment] 2019-11-26 16:46
I have the same problem but I have valid semver 2.0 chart name `service-name-0.2.7+1.25.8-5`. Why rancher treats this name as invalid?

**Comment by brendarearden** [comment] 2019-12-04 20:16
@kandeshvari each chart is turned into a new kubernetes object and named `template name + template version` to ensure that it is unique. Since the [allowed characters](https://kubernetes.io/docs/concepts/overview/working-with-objects/names/) for kubernetes object names are: `digits (0-9), lower case letters (a-z), -, and .`  it is erroring even when you have proper semver because of how the name assignment is occurring.

**Comment by kandeshvari** [comment] 2019-12-05 06:17
@brendarearden, thank you for answer, it helps.
So, the next question is - how to get it working in my case with semver? Can I disable object creating, or replace invalid chars, or apply some other workaround to get it working?

**Comment by dramich** [comment] 2019-12-05 16:10
@kandeshvari The name of the chart has to be updated if you want it to be used in Rancher.

**Comment by sangeethah** [comment] 2019-12-05 20:14
Reopening this issue to get fix merged in release branch.

**Comment by aaronRancher** [comment] 2019-12-05 21:15
Tested with Rancher server `rancher\rancher:master-head` `version 5adba24c3`

Complete steps as above.
Initial UI:
![Screen Shot 2019-12-05 at 2 01 25 PM](https://user-images.githubusercontent.com/57409052/70274536-88a8f300-1769-11ea-9354-bafc1d49ef1e.png)
UI no longer reports that templates are being synced.
![Screen Shot 2019-12-05 at 2 07 03 PM](https://user-images.githubusercontent.com/57409052/70274584-a413fe00-1769-11ea-8b1c-e3be4ede3d6b.png)

Logs no longer report that templates are being updated.
```
2019/12/05 21:01:34 [INFO] Updating global catalog test
2019/12/05 21:01:34 [INFO] Catalog sync done. 0 templates created, 0 templates updated, 0 templates deleted, 1 templates failed
2019/12/05 21:01:34 [ERROR] CatalogController test [catalog] failed with : failed to create templates. Multiple error(s) occured: [failed to create template test-trying-a-name_with_underscores-and_dashes: CatalogTemplate.management.cattle.io "test-trying-a-name_with_underscores-and_dashes" is invalid: metadata.name: Invalid value: "test-trying-a-name_with_underscores-and_dashes": a DNS-1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*')]
2019/12/05 21:01:43 [INFO] Updating global catalog test
2019/12/05 21:01:43 [INFO] Catalog sync done. 0 templates created, 0 templates updated, 0 templates deleted, 1 templates failed
2019/12/05 21:01:43 [ERROR] CatalogController test [catalog] failed with : failed to create templates. Multiple error(s) occured: [failed to create template test-trying-a-name_with_underscores-and_dashes: CatalogTemplate.management.cattle.io "test-trying-a-name_with_underscores-and_dashes" is invalid: metadata.name: Invalid value: "test-trying-a-name_with_underscores-and_dashes": a DNS-1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*')]
2019/12/05 21:02:00 [INFO] Updating global catalog test
2019/12/05 21:02:00 [INFO] Catalog sync done. 0 templates created, 0 templates updated, 0 templates deleted, 1 templates failed
2019/12/05 21:02:00 [ERROR] CatalogController test [catalog] failed with : failed to create templates. Multiple error(s) occured: [failed to create template test-trying-a-name_with_underscores-and_dashes: CatalogTemplate.management.cattle.io "test-trying-a-name_with_underscores-and_dashes" is invalid: metadata.name: Invalid value: "test-trying-a-name_with_underscores-and_dashes": a DNS-1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*')]
2019/12/05 21:02:27 [INFO] Catalog-cache removed 1 entries from disk
2019/12/05 21:02:33 [INFO] Updating global catalog test
2019/12/05 21:02:33 [INFO] Catalog sync done. 0 templates created, 0 templates updated, 0 templates deleted, 1 templates failed
2019/12/05 21:02:33 [ERROR] CatalogController test [catalog] failed with : failed to create templates. Multiple error(s) occured: [failed to create template test-trying-a-name_with_underscores-and_dashes: CatalogTemplate.management.cattle.io "test-trying-a-name_with_underscores-and_dashes" is invalid: metadata.name: Invalid value: "test-trying-a-name_with_underscores-and_dashes": a DNS-1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*')]
```

**Comment by brendarearden** [comment] 2019-12-06 16:32
@aaronRancher The UI sync message was changed intentionally. To show each template syncing in the UI, we were previously calling an update method. This was causing the excessive logging that was occurring. To reduce logging, I reduced the number of times  update was being called which resulted in only being able to display "syncing catalog" in the ui. 

What changes did you make to the template that you were expecting to trigger an update?

**Comment by aaronRancher** [comment] 2019-12-06 16:44
@brendarearden This is completely fine. Just as long as an error is reflected in UI.

**Comment by aaronRancher** [comment] 2019-12-06 16:54
Bus is reproduced with Rancher server `rancher\rancher:v2.2.7`

Complete steps as above.
UI:
![Screen Shot 2019-12-06 at 9 50 06 AM](https://user-images.githubusercontent.com/57409052/70340436-06bed580-180e-11ea-9c75-b603cf8993c6.png)
Logs:
```
2019/12/06 16:49:58 [INFO] Updating global catalog test
2019/12/06 16:50:32 [INFO] Catalog sync done. 1002 templates created, 0 templates updated, 0 templates deleted
2019/12/06 16:50:32 [ERROR] CatalogController test [catalog] failed with : failed to update templates. Multiple error occurred: [failed to create template test-trying-a-name_with_underscores-and_dashes: CatalogTemplate.management.cattle.io "test-trying-a-name_with_underscores-and_dashes" is invalid: metadata.name: Invalid value: "test-trying-a-name_with_underscores-and_dashes": a DNS-1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*')]
2019/12/06 16:50:33 [INFO] Updating global catalog test
I1206 16:50:37.215058       6 trace.go:76] Trace[999056747]: "Update /apis/management.cattle.io/v3/catalogs/test" (started: 2019-12-06 16:50:36.63908731 +0000 UTC m=+247.724030825) (total time: 575.829225ms):
```

Bug fix is validated with Rancher server `rancher\rancher:master-head` `version 5adba24c3`

Complete steps as above.
UI:
![Screen Shot 2019-12-06 at 9 45 10 AM](https://user-images.githubusercontent.com/57409052/70340412-00305e00-180e-11ea-99fb-19ef6fed6254.png)
Logs:
```
2019/12/06 16:34:59 [INFO] Updating global catalog test2
2019/12/06 16:34:59 [INFO] Catalog sync done. 0 templates created, 0 templates updated, 0 templates deleted, 1 templates failed
2019/12/06 16:34:59 [ERROR] CatalogController test2 [catalog] failed with : failed to create templates. Multiple error(s) occured: [failed to create template test2-trying-a-name_with_underscores-and_dashes: CatalogTemplate.management.cattle.io "test2-trying-a-name_with_underscores-and_dashes" is invalid: metadata.name: Invalid value: "test2-trying-a-name_with_underscores-and_dashes": a DNS-1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*')]
```

**Closed by aaronRancher** 2019-12-06 16:54 UTC
Labels: [zube]: To Test, kind/bug, team/az
