### ISSUE TITLE
Automate setting up Rancher/server in HA mode via meta-rancher

### ISSUE THREAD

**Issue by sabiodelhielo** [rancher/rancher#9404] opened 2017-07-20 16:57 UTC
Validation tests only run against a non-HA rancher/server. Need to add automation scripts to assisting Jenkins jobs in setup and running HA for the support versions of os/docker.

**Comment by cjellick** [comment] 2017-08-16 20:16
Dupe of #9588?

**Closed** 2018-10-12 06:56 UTC
Labels: kind/ci-improvements, kind/task, status/autoclosed, version/1.6
