### ISSUE TITLE
[GKE V2] Importing Cluster Fails with Duplicate Secret Message

### ISSUE THREAD

**Issue by westlywright** [rancher/rancher#31952] opened 2021-04-06 21:32 UTC
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
Create a GKE cluster via the Google Console UI or CLI (I did UI, and didn't change many of the defaults except network and cluster release channel)
Create a new imported GKE cluster (will have to be done through the API UI until UI is merged) and save the cluster resource.

**Result:**
Cluster transitions to an error state with the message `Secrets "c-7qvfx" already exists`

**Other details that may be helpful:**
I passed the logs from my machine to @cmurphy offline.

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): 2.5-head
- Installation option (single install/HA): HA

**Comment by aaronRancher** [comment] 2021-04-07 22:39
Reproduced on Rancher `master-head` `version f5393c2` with the following steps.

From GKE console, create a default cluster.
Create a google cloud credential.
From `https://.../v3/clusters`, create an imported GKE cluster with the following `gkeclusterconfigspec`:
```
{
  "clusterName": "aaron-test2",
  "displayName": "aaron-test2",
  "googleCredentialSecret": "cattle-global-data:cc-2jpk5",
  "imported": true,
  "projectID": "...",
  "region": "us-central1-c"
}
```
Result:
Cluster provisioning errors with `Pending; secrets "c-qvfld" already exists`
GKE operator version: `v1.0.1-rc4`

This fix is in `gke-operator:v1.0.1-rc6`. Will wait for RC6 to be tagged before validating.

**Comment by aaronRancher** [comment] 2021-04-07 22:41
While testing on Rancher `v2.5-head` `version ebee7eb`, I encountered a different error.

Cluster provisioning errors with `Unexpected end of JSON input`

**Comment by aaronRancher** [comment] 2021-04-08 00:47
Tested on `master-head` `version f5393c2`
EKS-Operator version `gke-operator:v1.0.1-rc6`

The imported cluster was provisioned successfully, but became stuck in updating state: `Waiting for nodes`

Tested on `v2.5-head` `version 7426ba8 `
EKS-Operator version `gke-operator:v1.0.1-rc6`

Cluster provisioning fails with known issue: #31958

**Comment by aaronRancher** [comment] 2021-04-09 23:29
The `Unexpected end of JSON input` behavior has been fixed and was due to this issue: https://github.com/rancher/rancher/issues/31983
This issue is currently waiting on a fix for this blocker: https://github.com/rancher/rancher/issues/31986

**Comment by cbron** [comment] 2021-04-12 15:57
Adding this back to test, lmk if we should chat.

**Comment by aaronRancher** [comment] 2021-04-14 18:28
This issue is validated on Rancher and `v2.5-head` `version 4e70ed2` and `master-head` `version 39d572a`
GKE operator version: `gke-operator:v1.0.1-rc6`

Imported cluster is provisioned successfully through the API without error.

**Closed by aaronRancher** 2021-04-14 18:28 UTC
Labels: QA/XS, [zube]: QA Working, area/gke
