### ISSUE TITLE
Rescheduling containers - not all hosts seen as viable candidates

### ISSUE THREAD

**Issue by LLParse** [rancher/rancher#7444] opened 2017-01-17 18:53 UTC
**Rancher Versions:**
Server: 1.3.0
healthcheck: 0.2.0
ipsec: 0.8.1
metadata: 0.7.0
dns: 0.13.0
network-manager: 0.4.0
scheduler: n/a (cattle)
kubernetes (if applicable): 1.5.1-rancher1-7

**Docker Version:** 1.12.3

**OS and where are the hosts located? (cloud, bare metal, etc):** GCE, Ubuntu 16.04.1 LTS

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)** single node, internal DB

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)** Kubernetes

**Steps to Reproduce:**
1. Create a kubernetes environment
2. Add 5 hosts, wait for stack to settle
3. Label a host *orchestration=true*
4. Delete kubectld, addon-starter, scheduler, controller-manager, ingress-controller, kubernetes-agent

**Results:** Some (but not all) containers are rescheduled to the *orchestration=true* host.
From rancher-server debug logs:
```
2017-01-17 18:21:54,747 INFO  [fbb4661a-c0ce-4216-a366-c39b141047fd:1679] [instance:93] [instance.start->(InstanceStart)->instance.allocate->(InstanceAllocate)] [] [ecutorService-5] [i.c.p.a.service.AbstractAllocator   ] [331857f2-6427-4c20-8d16-3c2023dd3e40] Attempting allocation for:
  [331857f2-6427-4c20-8d16-3c2023dd3e40] instance [[93]]
  [331857f2-6427-4c20-8d16-3c2023dd3e40] volume [177]
  [331857f2-6427-4c20-8d16-3c2023dd3e40] constraints:
  [331857f2-6427-4c20-8d16-3c2023dd3e40]   account id must be 7
  [331857f2-6427-4c20-8d16-3c2023dd3e40]   valid host(s) [1]
  [331857f2-6427-4c20-8d16-3c2023dd3e40]   volume [177] must be one of pool(s) [1]
  [331857f2-6427-4c20-8d16-3c2023dd3e40]   storage pool for volume 177 must be one of kind [sim, docker]
  [331857f2-6427-4c20-8d16-3c2023dd3e40]   needs host with label orchestration_soft: true 
```
Only valid host is the hostId where the container was initially scheduled.

**Expected:** All k8s components with appropriate label affinity are rescheduled to the *orchestration=true* host

**Comment by LLParse** [comment] 2017-01-17 18:59
I also noticed that the new addon_starter service is missing the *orchestration=true* soft affinity. That will need to fixed as well.

Temporary workaround for other components is to deactivate the host on which the containers currently reside before deleting them. This will force the scheduler to consider other hosts as viable candidates.

**Comment by LLParse** [comment] 2017-01-17 19:11
Also present in Rancher 1.3.1

**Comment by StrongMonkey** [comment] 2017-02-14 01:30
@cjellick  @LLParse I think the problem happens in here. https://github.com/rancher/cattle/blob/master/code/iaas/allocator/src/main/java/io/cattle/platform/allocator/constraint/BaseConstraintsProvider.java#L55-L66 This block of code is responsible to populate the ValidHostConstraints, and it will append the hostId which is initially scheduled to the constraint. That is why it always return the same valid host once the hostID is set in AllocationAttempt.

**Comment by cjellick** [comment] 2017-02-21 16:13
We're going to wait to see if this is addressed by @alena1108's refactoring to service scheduling.

**Comment by cjellick** [comment] 2017-02-21 16:14
@alena1108 I'm going to assign you as well just so you see this in your issue list. I don't think you need to take any explicit action on  it. We just need to re-evaluate the bug after your service scheduling PR is merged.

**Comment by alena1108** [comment] 2017-02-22 17:19
@cjellick the refactoring had been rescheduled to 1.6. Should we move this bug there, or are there any new findings on a potential fix?

**Comment by will-chan** [comment] 2017-02-22 22:18
Moving to 1.6 as this requires the refactoring work.

**Comment by deniseschannon** [comment] 2017-02-25 07:19
Outside of the service scheduling issues, the overall issue for how to run k8s using resiliency planes has been updated with the latest template (v1.5.2-rancher1-3).

**Comment by StrongMonkey** [comment] 2017-03-17 00:17
Seems to be fixed by alena's refactoring PR. I can't reproduce it in master now. @LLParse Can you plz re-test it using `rancher/server:master`?

**Comment by LLParse** [comment] 2017-03-17 01:13
@StrongMonkey Reproduced it on master container, built about 30 minutes ago. I have preserved the environment if you would like to inspect it.

**Comment by LLParse** [comment] 2017-03-17 03:10
I was able to reproduce this bug by upgrading from no plane isolation -> required. The etcd gets stuck and can't be scheduled. @StrongMonkey

**Comment by deniseschannon** [comment] 2017-06-02 03:53
@galal-hussein Can you test this on rancher/server:master with the new container refactoring?

**Comment by deniseschannon** [comment] 2018-01-29 22:32
Due to changes in 2.0 architecture, closing old issues that were to be tested with the original 2.0 refactoring.

**Closed by deniseschannon** 2018-01-29 22:32 UTC
Labels: area/container-refactoring, area/scheduler, kind/bug, priority/-1, status/to-test, version/2.0
