### ISSUE TITLE
Upgrade of downstream cluster does not start if other (completed) plans exist in the cluster

### ISSUE THREAD

**Issue by Martin-Weiss** [rancher/rancher#36607] opened 2022-02-23 08:40 UTC
We are using system-upgrade-controller to patch and upgrade the OS and due to that our downstream clusters have system-upgrade-controller and plans deployed, already before upgrading RKE2. The "other plans and other system-upgrade-controllers are NOT in the cattle-system namespace2.

It seems that rancher looks into ALL namespaces for Plans 

https://github.com/rancher/rancher/blob/d5a943b427776922c6f163623738bbda3e12e9b2/pkg/controllers/management/k3sbasedupgrade/deployPlans.go#L58

and if it finds one - we see this error in the rancher logs:

`022/02/23 08:10:58 [ERROR] error syncing 'c-jrh4v': handler k3s-upgrade-controller: an empty namespace may not be set when a resource name is provided, requeuing`

-> any idea why Rancher checks for plans in "all" namespaces?

-> could we get this "fixed" in a way that Rancher just looks into "cattle-system" namespace for other plans? 

SURE-4141

**Comment by jakefhyde** [comment] 2022-04-29 16:12
Moved to Blocked because the issue does not seem reproducible with _just_ completed plans in separate namespaces, waiting for additional info.

**Comment by markusewalker** [comment] 2022-05-20 17:58
Verified this has been resolved in `v2.6-head` https://github.com/rancher/rancher/commit/0e2fdc8060bc74c278d7f043c7846297577fb92c.

**ENVIRONMENT DETAILS**
- Rancher HA
- Rancher version
     - Reproduced version: `v2.6.4`
     - Verified version: `v2.6-head https://github.com/rancher/rancher/commit/0e2fdc8060bc74c278d7f043c7846297577fb92c`
- Browser: Chrome

**TEST RESULT**
PASS

**REPRODUCTION STEPS**
1. Setup Rancher `v2.6.4` and navigated to Rancher UI in a browser.
2. Created a standard user and logged in to Rancher as that user.
3. On a separate client machine, provisioned an k3s cluster at version v1.21.12+k3s1.
4. Ran the following command to install the system-upgrade-controller: `kubectl apply -f https://github.com/rancher/system-upgrade-controller/releases/latest/download/system-upgrade-controller.yaml`
5. Configured a server and agent plan into the resulting `system-upgrade` namespace; verified the K8s cluster was updated to the version specified in the plan.
6. Navigated back to Rancher and imported the provisioned k3s cluster.
7. Perform an upgrade on the cluster and verify that it is successful and `system-upgrade-controller` is being checked against only the `cattle-system` namespace.
     - This FAILED. The upgrade hangs forever and never finishes upgrading.

**VERIFICATION STEPS**
1. Setup Rancher `v2.6-head https://github.com/rancher/rancher/commit/0e2fdc8060bc74c278d7f043c7846297577fb92c` ` and navigated to Rancher UI in a browser.
2. Created a standard user and logged in to Rancher as that user.
3. On a separate client machine, provisioned an k3s cluster at version v1.21.12+k3s1.
4. Ran the following command to install the system-upgrade-controller: `kubectl apply -f https://github.com/rancher/system-upgrade-controller/releases/latest/download/system-upgrade-controller.yaml`
5. Configured a server and agent plan into the resulting `system-upgrade` namespace; verified the K8s cluster was updated to the version specified in the plan.
6. Navigated back to Rancher and imported the provisioned k3s cluster.
7. Perform an upgrade on the cluster and verify that it is successful and `system-upgrade-controller` is being checked against only the `cattle-system` namespace.
     - This PASSED. The upgrade quickly went through and all of the nodes had the upgraded version as expected.

**Closed by markusewalker** 2022-05-20 17:58 UTC
Labels: internal, [zube]: QA Working, QA/S, feature/imported-rke2-k3s, team/area2
