### ISSUE TITLE
Containers on separate hosts can't access/ping each other.  (CoreOS, Docker 1.10.3)

### ISSUE THREAD

**Issue by fbrbovic** [rancher/rancher#4874] opened 2016-05-20 22:03 UTC
**Rancher Version:**
Rancher	v1.1.0-dev1

**Docker Version:**
Docker version 1.10.3

**OS and where are the hosts located? (cloud, bare metal, etc):**
CoreOS beta (1010.3.0) | Bare Metal 

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
Single node Rancher , external DB

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle

**Steps to Reproduce:**
Start two hosts  and create a service with scale 2 ( this way both containers go on different hosts)
Exec into one of the hosts and try to ping the other

**Results:** 
Containers started on different hosts can't ping each other while containers on the same host can ping each other. 

**Expected:**
Should be able to ping containers on the hosts. 

Can someone help me with this, I can't seem to understand why it's not working. 
Hosts can ping each other no problem  and udp 500 and 4500 are open, but containers on different hosts can't access each other.

**Comment by sshipway** [comment] 2016-05-23 01:42
We had this problem as well; went back to using CoreOS Stable (Docker 1.9.1) and it solved the problem.  Seems to be an incompatibility between Docker 1.10, CoreOS and Rancher.

**Comment by deniseschannon** [comment] 2016-05-23 04:20
As @sshipway mentioned, this is a duplicate of #4238, where this is something going on with Docker 1.10, CoreOS and Rancher.

**Closed by deniseschannon** 2016-05-23 04:20 UTC
