### ISSUE TITLE
Failed to start certificate controller when start the rancher/rancher container

### ISSUE THREAD

**Issue by vincentchen** [rancher/rancher#13330] opened 2018-05-07 11:39 UTC
**Rancher versions:** v2.0.0
rancher/rancher:
E0507 11:20:59.763995       1 certificates.go:48] Failed to start certificate controller: error reading CA cert file "/etc/kubernetes/ca/ca.pem": open /etc/kubernetes/ca/ca.pem: no such file or directory
E0507 11:20:59.777507       1 core.go:70] Failed to start service controller: WARNING: no cloud provider provided, services of type LoadBalancer will fail.

**Docker version: (`docker version`,`docker info` preferred)**
Client:
 Version:	18.04.0-ce
 API version:	1.37
 Go version:	go1.9.4
 Git commit:	3d479c0
 Built:	Tue Apr 10 18:20:32 2018
 OS/Arch:	linux/amd64
 Experimental:	false
 Orchestrator:	swarm

Server:
 Engine:
  Version:	18.04.0-ce
  API version:	1.37 (minimum version 1.12)
  Go version:	go1.9.4
  Git commit:	3d479c0
  Built:	Tue Apr 10 18:18:40 2018
  OS/Arch:	linux/amd64
  Experimental:	false
**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
4.4.0-91-generic
**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
single node rancher 
**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**

**Steps to Reproduce:**

**Results:**

**Comment by wwlyzzyorg** [comment] 2018-05-07 13:30
我导入证书的时候提示无效的私钥文件，请问有没有遇到过呢

**Comment by superseb** [comment] 2018-05-07 14:54
This is a harmless log message, but we should look at removing it as it may confuse users. Again, no functional impact is expected because of this error.

**Comment by superseb** [comment] 2018-05-08 15:05
Closing as duplicate of https://github.com/rancher/rancher/issues/12710

**Closed by superseb** 2018-05-08 15:05 UTC
Labels: kind/enhancement, version/2.0

**Comment by krishofmans** [comment] 2018-05-15 19:47
![image](https://user-images.githubusercontent.com/999774/40079715-0fa0535e-5889-11e8-8917-8ae654bba9f9.png)
@superseb I'm not sure it's harmless, I have 2 clusters now that have become unusable.

The logfile looks like this:
`554582 I | etcdserver: snapshot count = 100000
2018-05-15 19:15:31.554598 I | etcdserver: advertise client URLs = https://127.0.0.1:2379,https://127.0.0.1:4001
2018-05-15 19:15:31.952145 I | etcdserver: restarting member e92d66acd89ecf29 in cluster 7581d6eb2d25405b at commit index 1006163
2018-05-15 19:15:31.952517 I | raft: e92d66acd89ecf29 became follower at term 5
2018-05-15 19:15:31.952540 I | raft: newRaft e92d66acd89ecf29 [peers: [e92d66acd89ecf29], term: 5, commit: 1006163, applied: 1000010, lastindex: 1006163, lastterm: 5]
2018-05-15 19:15:31.952698 I | etcdserver/api: enabled capabilities for version 3.2
2018-05-15 19:15:31.952718 I | etcdserver/membership: added member e92d66acd89ecf29 [https://127.0.0.1:2380] to cluster 7581d6eb2d25405b from store
2018-05-15 19:15:31.952725 I | etcdserver/membership: set the cluster version to 3.2 from store
2018-05-15 19:15:31.954737 I | mvcc: restore compact to 992784
2018-05-15 19:15:31.960394 W | auth: simple token is not cryptographically signed
2018-05-15 19:15:31.963521 I | etcdserver: starting server... [version: 3.2.13, cluster version: 3.2]
2018-05-15 19:15:31.964480 I | embed: ClientTLS: cert = /etc/kubernetes/ssl/kube-etcd-127-0-0-1.pem, key = /etc/kubernetes/ssl/kube-etcd-127-0-0-1-key.pem, ca = , trusted-ca = /etc/kubernetes/ssl/kube-ca.pem, client-cert-auth = true
[restful] 2018/05/15 19:15:32 log.go:33: [restful/swagger] listing is available at https://10.43.0.1:6443/swaggerapi
[restful] 2018/05/15 19:15:32 log.go:33: [restful/swagger] https://10.43.0.1:6443/swaggerui/ is mapped to folder /swagger-ui/
2018-05-15 19:15:32.353067 I | raft: e92d66acd89ecf29 is starting a new election at term 5
2018-05-15 19:15:32.353131 I | raft: e92d66acd89ecf29 became candidate at term 6
2018-05-15 19:15:32.353170 I | raft: e92d66acd89ecf29 received MsgVoteResp from e92d66acd89ecf29 at term 6
2018-05-15 19:15:32.353187 I | raft: e92d66acd89ecf29 became leader at term 6
2018-05-15 19:15:32.353195 I | raft: raft.node: e92d66acd89ecf29 elected leader e92d66acd89ecf29 at term 6
2018-05-15 19:15:32.354607 I | embed: ready to serve client requests
2018-05-15 19:15:32.354721 I | etcdserver: published {Name:etcd-master ClientURLs:[https://127.0.0.1:2379 https://127.0.0.1:4001]} to cluster 7581d6eb2d25405b
2018-05-15 19:15:32.354926 I | embed: serving client requests on [::]:2379
2018/05/15 19:15:32 [INFO] Waiting for server to become available: Get https://127.0.0.1:6443/version: dial tcp 127.0.0.1:6443: getsockopt: connection refused
[restful] 2018/05/15 19:15:32 log.go:33: [restful/swagger] listing is available at https://10.43.0.1:6443/swaggerapi
[restful] 2018/05/15 19:15:32 log.go:33: [restful/swagger] https://10.43.0.1:6443/swaggerui/ is mapped to folder /swagger-ui/
2018/05/15 19:15:33 [INFO] Waiting for server to become available: Get https://127.0.0.1:6443/version: dial tcp 127.0.0.1:6443: getsockopt: connection refused
2018/05/15 19:15:33 [INFO] Waiting for server to become available: Get https://127.0.0.1:6443/version: dial tcp 127.0.0.1:6443: getsockopt: connection refused
2018/05/15 19:15:34 [INFO] Waiting for server to become available: Get https://127.0.0.1:6443/version: dial tcp 127.0.0.1:6443: getsockopt: connection refused
2018/05/15 19:15:35 [INFO] Waiting for server to become available: Get https://127.0.0.1:6443/version: dial tcp 127.0.0.1:6443: getsockopt: connection refused
2018/05/15 19:15:35 [INFO] Waiting for server to become available: Get https://127.0.0.1:6443/version: dial tcp 127.0.0.1:6443: getsockopt: connection refused
2018/05/15 19:15:36 [INFO] Running kube-scheduler --leader-elect=true --v=2 --address=0.0.0.0 --kubeconfig=/etc/kubernetes/ssl/kubecfg-kube-scheduler.yaml -v=1 --logtostderr=false --alsologtostderr=false
2018/05/15 19:15:37 [INFO] Running kube-controller-manager --address=0.0.0.0 --allow-untagged-cloud=true --enable-hostpath-provisioner=false --service-account-private-key-file=/etc/kubernetes/ssl/kube-apiserver-key.pem --v=2 --allocate-node-cidrs=true --kubeconfig=/etc/kubernetes/ssl/kubecfg-kube-controller-manager.yaml --service-cluster-ip-range=10.43.0.0/16 --node-monitor-grace-period=40s --cluster-cidr=10.42.0.0/16 --configure-cloud-routes=false --leader-elect=true --pod-eviction-timeout=5m0s --cloud-provider= --root-ca-file=/etc/kubernetes/ssl/kube-ca.pem --use-service-account-credentials=true -v=1 --logtostderr=false --alsologtostderr=false
Flag --allow-untagged-cloud has been deprecated, This flag is deprecated and will be removed in a future release.  A cluster-id will be required on cloud instances
E0515 19:15:37.550815       1 controllermanager.go:117] unable to register configz: register config "componentconfig" twice
2018/05/15 19:15:37 [INFO] Starting API controllers
2018/05/15 19:15:37 [INFO] Syncing SecretController Controller
2018/05/15 19:15:37 [INFO] Syncing ClusterRoleTemplateBindingController Controller
2018/05/15 19:15:37 [INFO] Syncing ListenConfigController Controller
2018/05/15 19:15:37 [INFO] Syncing ProjectRoleTemplateBindingController Controller
2018/05/15 19:15:37 [INFO] Syncing ProjectController Controller
2018/05/15 19:15:37 [INFO] Syncing ClusterController Controller
2018/05/15 19:15:37 [INFO] Syncing GroupMemberController Controller
2018/05/15 19:15:37 [INFO] Syncing TokenController Controller
2018/05/15 19:15:37 [INFO] Syncing GroupController Controller
2018/05/15 19:15:37 [INFO] Syncing NodeController Controller
2018/05/15 19:15:37 [INFO] Syncing AuthConfigController Controller
2018/05/15 19:15:37 [INFO] Syncing RoleBindingController Controller
2018/05/15 19:15:37 [INFO] Syncing SourceCodeCredentialController Controller
2018/05/15 19:15:37 [INFO] Syncing ClusterRegistrationTokenController Controller
2018/05/15 19:15:37 [INFO] Syncing SourceCodeRepositoryController Controller
2018/05/15 19:15:37 [INFO] Syncing NodeDriverController Controller
2018/05/15 19:15:37 [INFO] Syncing PipelineController Controller
2018/05/15 19:15:37 [INFO] Syncing SettingController Controller
2018/05/15 19:15:37 [INFO] Syncing ClusterRoleBindingController Controller
2018/05/15 19:15:37 [INFO] Syncing ClusterPipelineController Controller
2018/05/15 19:15:37 [INFO] Syncing ClusterRoleController Controller
2018/05/15 19:15:37 [INFO] Syncing NodeController Controller
2018/05/15 19:15:37 [INFO] Syncing DynamicSchemaController Controller
2018/05/15 19:15:37 [INFO] Syncing UserController Controller
2018/05/15 19:15:37 [INFO] Syncing RoleController Controller
2018/05/15 19:15:37 [INFO] Syncing SecretController Controller Done
2018/05/15 19:15:37 [INFO] Syncing ClusterController Controller Done
2018/05/15 19:15:37 [INFO] Syncing NodeController Controller Done
2018/05/15 19:15:37 [INFO] Syncing SettingController Controller Done
2018/05/15 19:15:37 [INFO] Syncing ClusterRoleController Controller Done
2018/05/15 19:15:37 [INFO] Syncing RoleController Controller Done
2018/05/15 19:15:37 [INFO] Syncing ListenConfigController Controller Done
2018/05/15 19:15:37 [INFO] Syncing ClusterRoleTemplateBindingController Controller Done
2018/05/15 19:15:37 [INFO] Syncing ProjectController Controller Done
2018/05/15 19:15:37 [INFO] Syncing ProjectRoleTemplateBindingController Controller Done
2018/05/15 19:15:37 [INFO] Syncing TokenController Controller Done
2018/05/15 19:15:37 [INFO] Syncing GroupController Controller Done
2018/05/15 19:15:37 [INFO] Syncing AuthConfigController Controller Done
2018/05/15 19:15:37 [INFO] Syncing RoleBindingController Controller Done
2018/05/15 19:15:37 [INFO] Syncing ClusterRegistrationTokenController Controller Done
2018/05/15 19:15:37 [INFO] Syncing SourceCodeCredentialController Controller Done
2018/05/15 19:15:37 [INFO] Syncing NodeDriverController Controller Done
2018/05/15 19:15:37 [INFO] Syncing PipelineController Controller Done
2018/05/15 19:15:37 [INFO] Syncing SourceCodeRepositoryController Controller Done
2018/05/15 19:15:37 [INFO] Syncing GroupMemberController Controller Done
2018/05/15 19:15:37 [INFO] Syncing ClusterRoleBindingController Controller Done
2018/05/15 19:15:37 [INFO] Syncing ClusterPipelineController Controller Done
2018/05/15 19:15:37 [INFO] Syncing NodeController Controller Done
2018/05/15 19:15:37 [INFO] Syncing DynamicSchemaController Controller Done
2018/05/15 19:15:37 [INFO] Syncing UserController Controller Done
2018/05/15 19:15:37 [INFO] Listening on :443
2018/05/15 19:15:37 [INFO] Listening on :80
2018/05/15 19:15:37 [INFO] Event(v1.ObjectReference{Kind:"ConfigMap", Namespace:"kube-system", Name:"cattle-controllers", UID:"369bd6da-50a5-11e8-9f4e-0242ac110008", APIVersion:"v1", ResourceVersion:"993472", FieldPath:""}): type: 'Normal' reason: 'LeaderElection' d9ba2363ec32 became leader
2018/05/15 19:15:37 [INFO] Starting catalog controller
2018/05/15 19:15:37 [INFO] Starting management controllers
2018/05/15 19:15:37 [INFO] Syncing RoleController Controller
2018/05/15 19:15:37 [INFO] Syncing NodeController Controller
2018/05/15 19:15:37 [INFO] Syncing ProjectController Controller
2018/05/15 19:15:37 [INFO] Syncing RoleBindingController Controller
2018/05/15 19:15:37 [INFO] Syncing ClusterRoleBindingController Controller
2018/05/15 19:15:37 [INFO] Syncing PodSecurityPolicyTemplateController Controller
2018/05/15 19:15:37 [INFO] Syncing ClusterEventController Controller
2018/05/15 19:15:37 [INFO] Syncing ClusterController Controller
2018/05/15 19:15:37 [INFO] Syncing DynamicSchemaController Controller
2018/05/15 19:15:37 [INFO] Syncing GlobalRoleController Controller
2018/05/15 19:15:37 [INFO] Syncing NodeDriverController Controller
2018/05/15 19:15:37 [INFO] Syncing NodePoolController Controller
2018/05/15 19:15:37 [INFO] Syncing ProjectRoleTemplateBindingController Controller
2018/05/15 19:15:37 [INFO] Syncing SecretController Controller
2018/05/15 19:15:37 [INFO] Syncing ClusterRoleTemplateBindingController Controller
2018/05/15 19:15:37 [INFO] Syncing UserController Controller
2018/05/15 19:15:37 [INFO] Syncing ClusterRoleController Controller
2018/05/15 19:15:37 [INFO] Syncing TokenController Controller
2018/05/15 19:15:37 [INFO] Syncing NamespaceController Controller
2018/05/15 19:15:37 [INFO] Syncing RoleTemplateController Controller
2018/05/15 19:15:37 [INFO] Syncing GlobalComposeConfigController Controller
2018/05/15 19:15:37 [INFO] Syncing PodSecurityPolicyTemplateProjectBindingController Controller
2018/05/15 19:15:37 [INFO] Syncing ProjectAlertController Controller
2018/05/15 19:15:37 [INFO] Syncing GlobalRoleBindingController Controller
2018/05/15 19:15:37 [INFO] Syncing CatalogController Controller
2018/05/15 19:15:37 [INFO] Syncing ClusterRoleController Controller Done
2018/05/15 19:15:37 [INFO] Syncing UserController Controller Done
2018/05/15 19:15:37 [INFO] Syncing DynamicSchemaController Controller Done
2018/05/15 19:15:37 [INFO] Syncing TokenController Controller Done
2018/05/15 19:15:37 [INFO] Syncing NodePoolController Controller Done
2018/05/15 19:15:37 [INFO] Syncing NodeController Controller Done
2018/05/15 19:15:37 [INFO] Syncing RoleController Controller Done
2018/05/15 19:15:37 [INFO] Syncing ProjectRoleTemplateBindingController Controller Done
2018/05/15 19:15:37 [INFO] Syncing GlobalComposeConfigController Controller Done
2018/05/15 19:15:37 [INFO] Syncing RoleBindingController Controller Done
2018/05/15 19:15:37 [INFO] Syncing GlobalRoleBindingController Controller Done
2018/05/15 19:15:37 [INFO] Syncing NodeDriverController Controller Done
2018/05/15 19:15:37 [INFO] Syncing ProjectController Controller Done
2018/05/15 19:15:37 [INFO] Syncing ClusterEventController Controller Done
2018/05/15 19:15:37 [INFO] Syncing SecretController Controller Done
2018/05/15 19:15:37 [INFO] Syncing ClusterController Controller Done
2018/05/15 19:15:37 [INFO] Syncing ClusterRoleBindingController Controller Done
2018/05/15 19:15:37 [INFO] Syncing ProjectAlertController Controller Done
2018/05/15 19:15:37 [INFO] Syncing PodSecurityPolicyTemplateController Controller Done
2018/05/15 19:15:37 [INFO] Syncing PodSecurityPolicyTemplateProjectBindingController Controller Done
2018/05/15 19:15:37 [INFO] Syncing NamespaceController Controller Done
2018/05/15 19:15:37 [INFO] Syncing ClusterRoleTemplateBindingController Controller Done
2018/05/15 19:15:38 [INFO] Syncing GlobalRoleController Controller Done
2018/05/15 19:15:38 [INFO] Syncing RoleTemplateController Controller Done
2018/05/15 19:15:38 [INFO] Syncing CatalogController Controller Done
2018/05/15 19:15:38 [INFO] Reconciling GlobalRoles
2018/05/15 19:15:38 [INFO] Reconciling RoleTemplates
E0515 19:15:38.187572       1 generic_controller.go:204] ClusterController c-ddkxr [cluster-agent-controller] failed with : could not contact server: Get https://10.0.0.112:6443/version: waiting for cluster agent to connect
E0515 19:15:38.195114       1 generic_controller.go:204] ClusterController c-xx7lm [cluster-agent-controller] failed with : could not contact server: Get https://10.0.0.190:6443/version: waiting for cluster agent to connect
E0515 19:15:38.713763       1 generic_controller.go:204] ClusterController c-ddkxr [cluster-agent-controller] failed with : could not contact server: Get https://10.0.0.112:6443/version: waiting for cluster agent to connect
E0515 19:15:38.718437       1 generic_controller.go:204] ClusterController c-xx7lm [cluster-agent-controller] failed with : could not contact server: Get https://10.0.0.190:6443/version: waiting for cluster agent to connect
E0515 19:15:39.728230       1 generic_controller.go:204] ClusterController c-ddkxr [cluster-agent-controller] failed with : could not contact server: Get https://10.0.0.112:6443/version: waiting for cluster agent to connect
E0515 19:15:39.734392       1 generic_controller.go:204] ClusterController c-xx7lm [cluster-agent-controller] failed with : could not contact server: Get https://10.0.0.190:6443/version: waiting for cluster agent to connect
E0515 19:15:41.743293       1 generic_controller.go:204] ClusterController c-ddkxr [cluster-agent-controller] failed with : could not contact server: Get https://10.0.0.112:6443/version: waiting for cluster agent to connect
E0515 19:15:41.746411       1 generic_controller.go:204] ClusterController c-xx7lm [cluster-agent-controller] failed with : could not contact server: Get https://10.0.0.190:6443/version: waiting for cluster agent to connect
E0515 19:15:45.756622       1 generic_controller.go:204] ClusterController c-ddkxr [cluster-agent-controller] failed with : could not contact server: Get https://10.0.0.112:6443/version: waiting for cluster agent to connect
E0515 19:15:45.761834       1 generic_controller.go:204] ClusterController c-xx7lm [cluster-agent-controller] failed with : could not contact server: Get https://10.0.0.190:6443/version: waiting for cluster agent to connect
E0515 19:15:49.122243       1 core.go:70] Failed to start service controller: WARNING: no cloud provider provided, services of type LoadBalancer will fail.
E0515 19:15:49.164290       1 certificates.go:48] Failed to start certificate controller: error reading CA cert file "/etc/kubernetes/ca/ca.pem": open /etc/kubernetes/ca/ca.pem: no such file or directory
E0515 19:15:53.769006       1 generic_controller.go:204] ClusterController c-ddkxr [cluster-agent-controller] failed with : could not contact server: Get https://10.0.0.112:6443/version: waiting for cluster agent to connect
E0515 19:15:53.776607       1 generic_controller.go:204] ClusterController c-xx7lm [cluster-agent-controller] failed with : could not contact server: Get https://10.0.0.190:6443/version: waiting for cluster agent to connect
E0515 19:16:09.781717       1 generic_controller.go:204] ClusterController c-ddkxr [cluster-agent-controller] failed with : could not contact server: Get https://10.0.0.112:6443/version: waiting for cluster agent to connect
E0515 19:16:09.790996       1 generic_controller.go:204] ClusterController c-xx7lm [cluster-agent-controller] failed with : could not contact server: Get https://10.0.0.190:6443/version: waiting for cluster agent to connect
E0515 19:16:41.795547       1 generic_controller.go:204] ClusterController c-ddkxr [cluster-agent-controller] failed with : could not contact server: Get https://10.0.0.112:6443/version: waiting for cluster agent to connect
E0515 19:16:41.805583       1 generic_controller.go:204] ClusterController c-xx7lm [cluster-agent-controller] failed with : could not contact server: Get https://10.0.0.190:6443/version: waiting for cluster agent to connect
E0515 19:17:45.808658       1 generic_controller.go:204] ClusterController c-ddkxr [cluster-agent-controller] failed with : could not contact server: Get https://10.0.0.112:6443/version: waiting for cluster agent to connect
E0515 19:17:45.820395       1 generic_controller.go:204] ClusterController c-xx7lm [cluster-agent-controller] failed with : could not contact server: Get https://10.0.0.190:6443/version: waiting for cluster agent to connect
E0515 19:19:53.820658       1 generic_controller.go:204] ClusterController c-ddkxr [cluster-agent-controller] failed with : could not contact server: Get https://10.0.0.112:6443/version: waiting for cluster agent to connect
E0515 19:19:53.831601       1 generic_controller.go:204] ClusterController c-xx7lm [cluster-agent-controller] failed with : could not contact server: Get https://10.0.0.190:6443/version: waiting for cluster agent to connect
E0515 19:21:58.827991       1 streamwatcher.go:109] Unable to decode an event from the watch stream: json: cannot unmarshal string into Go struct field dynamicEvent.Object of type v3.SourceCodeRepositoryStatus
E0515 19:22:47.814812       1 streamwatcher.go:109] Unable to decode an event from the watch stream: json: cannot unmarshal string into Go struct field dynamicEvent.Object of type v3.ClusterRegistrationTokenStatus
E0515 19:24:09.834756       1 generic_controller.go:204] ClusterController c-ddkxr [cluster-agent-controller] failed with : could not contact server: Get https://10.0.0.112:6443/version: waiting for cluster agent to connect
E0515 19:24:09.842883       1 generic_controller.go:204] ClusterController c-xx7lm [cluster-agent-controller] failed with : could not contact server: Get https://10.0.0.190:6443/version: waiting for cluster agent to connect
2018-05-15 19:25:31.839886 I | mvcc: store.index: compact 993953
2018-05-15 19:25:31.845090 I | mvcc: finished scheduled compaction at 993953 (took 3.97503ms)
2018-05-15 19:30:31.845359 I | mvcc: store.index: compact 994440
2018-05-15 19:30:31.849768 I | mvcc: finished scheduled compaction at 994440 (took 3.37013ms)
E0515 19:32:41.846479       1 generic_controller.go:204] ClusterController c-ddkxr [cluster-agent-controller] failed with : could not contact server: Get https://10.0.0.112:6443/version: waiting for cluster agent to connect
E0515 19:32:41.853934       1 generic_controller.go:204] ClusterController c-xx7lm [cluster-agent-controller] failed with : could not contact server: Get https://10.0.0.190:6443/version: waiting for cluster agent to connect
2018-05-15 19:34:40.567941 I | wal: segmented wal file /var/lib/rancher/etcd/member/wal/000000000000000b-00000000000f61a5.wal is created
2018-05-15 19:35:01.990399 I | pkg/fileutil: purged file /var/lib/rancher/etcd/member/wal/0000000000000006-000000000008b720.wal successfully
2018-05-15 19:35:31.851012 I | mvcc: store.index: compact 994925
2018-05-15 19:35:31.855341 I | mvcc: finished scheduled compaction at 994925 (took 2.352008ms)
2018-05-15 19:40:31.858178 I | mvcc: store.index: compact 995413
2018-05-15 19:40:31.861126 I | mvcc: finished scheduled compaction at 995413 (took 2.190636ms)`

But just curl'ing from the host to the kubernetes hosts returns this:
`dockervm:~$ curl -k https://10.0.0.112:6443/version
{
  "major": "1",
  "minor": "10",
  "gitVersion": "v1.10.1",
  "gitCommit": "d4ab47518836c750f9949b9e0d387f20fb92260b",
  "gitTreeState": "clean",
  "buildDate": "2018-04-12T14:14:26Z",
  "goVersion": "go1.9.3",
  "compiler": "gc",
  "platform": "linux/amd64"
}`

Do you prefer a new ticket instead?

**Comment by niranjan94** [comment] 2018-07-04 20:34
@krishofmans did you resolve this issue ? Because I'm now facing the exact same issue

**Comment by niranjan94** [comment] 2018-07-05 06:13
Hi @superseb I'm facing the same issue faced by @krishofmans . Any suggestions on how to resolve this ?

**Comment by superseb** [comment] 2018-07-05 06:18
There isn't a cluster-agent connecting to Rancher that can be used. As this issue is closed, open a new issue with the steps to reproduce (see https://rancher.com/docs/rancher/v2.x/en/faq/contributing/#bugs-issues-or-questions) and we can investigate.

**Comment by niranjan94** [comment] 2018-07-05 06:41
@krishofmans @superseb I ended up fixing it by SSH'ing into the nodes and restarting the rancher-agent container. All is well now. Thanks :)
