### ISSUE TITLE
[rancher-dns] Service without a pod is not resolved (SkyDns resolves those)

### ISSUE THREAD

**Issue by Bekt** [rancher/rancher#6301] opened 2016-10-17 20:13 UTC
**Rancher Version:** 1.1.4
**Docker Version:** 1.10.3
**OS and where are the hosts located?:** CoreOS, EC2
**Setup Details:** Multi-node
**Environment Type:** Kubernetes 1.2
**Steps to Reproduce:** Create a service ([demo](http://pastebin.com/raw/rUppw6bg)), but don't create a pod
**Results:** 
The hostname is not resolved.

```
root@xxx:/# wget demo:44444
converted 'http://demo:44444' (ANSI_X3.4-1968) -> 'http://demo:44444' (UTF-8)
--2016-10-17 19:57:20--  http://demo:44444/
Resolving demo (demo)... failed: No address associated with hostname.
wget: unable to resolve host address 'demo'
```

**Expected:**
SkyDNS actually resolves the hostname even though there are no associated pods. 

```
root@xxx:/# wget demo:44444
converted 'http://demo:44444' (ANSI_X3.4-1968) -> 'http://demo:44444' (UTF-8)
--2016-10-17 19:56:52--  http://demo:44444/
Resolving demo:44444 (demo:44444)... x.x.x.186
Connecting to demo:44444 (demo:44444) | x.x.x.x|:44444... failed: Connection timed out.
Retrying.

--2016-10-17 19:59:00--  (try: 2)  http://demo:44444/
```

Rancher DNS claims it is a drop-in replacement for SkyDNS. One immediate problem I am having is that nginx upstreams do not resolve with Rancher DNS, thus nginx does not start at all if one service is not up (ala the demo services above). With SkyDNS, this issue does not exist since the service hostname always resolves.

**Comment by imikushin** [comment] 2016-11-04 01:58
Looks like a duplicate of #5948. When #5948 is implemented, there will be an option to use KubeDNS (aka SkyDNS) vs Rancher DNS in Kubernetes environments.

**Comment by galal-hussein** [comment] 2016-12-07 00:30
with the added support for skydns, i was able to resolve the name for service to the clusterIP with no pods.

Rancher version: master build

**Closed by galal-hussein** 2016-12-07 00:30 UTC
Labels: area/kubernetes, kind/enhancement, status/resolved, status/to-test
