### ISSUE TITLE
Not able to connect to swarm using generated config.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#4145] opened 2016-03-25 23:37 UTC
Rancher Version:v1.0.0-rc3

Created a swam environment with 2 hosts.
Go to Swarm->cli and do "Generate Config".
Follow the instruction provided for getting connected to swarm from local machine.

Not able to execute docker commands . Getting the following errors:

```
Sangeethas-MBP:.docker sangeethahariharan1$ export DOCKER_HOST=tcp://<ipaddress>:8080 DOCKER_TLS_VERIFY=1
Sangeethas-MBP:.docker sangeethahariharan1$ docker ps
An error occurred trying to connect: Get https://<ipaddress>:8080/v1.21/containers/json: x509: certificate is valid for 127.0.0.1, not <ipaddress>
```

Note - When rancher-server is ssl enabled , we are able to connect to swam client as expected.

**Comment by ibuildthecloud** [comment] 2016-03-28 19:13
Once the users sets the "Host registration" URL in the UI they must restart Rancher to generate the right SSL certificate.  We will make this dynamic in the next release.

**Comment by npcode** [comment] 2016-03-30 13:35
Same error even after restarting rancher/server.

**Comment by deniseschannon** [comment] 2016-03-30 17:26
@npcode Did you make sure to set the [host registration](http://docs.rancher.com/rancher/configuration/settings/#host-registration) located in Settings -> Host Registration before restarting rancher/server?

**Comment by npcode** [comment] 2016-03-31 01:13
@deniseschannon  Yes I did. And I tried it again but it still not work.

Should I use `https://` for the address to access rancher server by docker client in my workstation?

**Comment by deniseschannon** [comment] 2016-03-31 18:08
Can you check if `<server>:8080/v1/settings/api.host` has something set? 

Apologies for not clarifying, but you'll need to go to "Add Host" to get the "Host Registration" page to save the setting. Actually going into the Settings -> Host Registration -> Save will not have updated the API setting. 

After it's set, can you restart rancher server?

**Comment by npcode** [comment] 2016-04-01 07:39
`curl server:8000/v1/settings/api.host` returns:
```
{"id":"1as1","type":"activeSetting","links":{"self":"http://server:8080/v1/activesettings/1as1"},"actions":{},"name":"api.host","activeValue":"http://server:8080","inDb":true,"source":"Database","value":"http://server:8080"}
```
> Apologies for not clarifying, but you'll need to go to "Add Host" to get the "Host Registration" page to save the setting.

I couldn't find "Host Registration" link in "Add Host" page(http://server:8080/env/1a39/infra/hosts/add/custom).

**Comment by vovimayhem** [comment] 2016-04-01 14:53
Same here. Set up the host registration URL. Restarted Rancher. Added two hosts successfully. Downloaded the swarm config & used the certificates. Same output from [server]/v1/settings/api.host. Same Error :(

**Comment by deniseschannon** [comment] 2016-04-01 16:38
@npcode @vovimayhem Can both of you provide the error after you try to connect to TLS and then do a `docker ps`?

**Comment by dadicool** [comment] 2016-04-03 21:54
stuck with that same reported error :
```export DOCKER_HOST=tcp://11.22.33.44:8080 DOCKER_TLS_VERIFY=1```
```Mohameds-MacBook-Pro:~ dali$ docker ps
An error occurred trying to connect: Get https://11.22.33.44:8080/v1.22/containers/json: x509: certificate is valid for 127.0.0.1, not 11.22.33.44```

I also restarted rancher to no effect ...

**Comment by npcode** [comment] 2016-04-04 01:24
@deniseschannon Here is my error:
```
$ docker ps
An error occurred trying to connect: Get https://10.123.123.12:8080/v1.22/containers/json: x509: certificate is valid for 127.0.0.1, not 10.123.123.12
```

**Comment by vovimayhem** [comment] 2016-04-04 18:20
@deniseschannon that's exactly the same error I was getting... `certificate is valid for 127.0.0.1, not X.X.X.X`

**Comment by FrancescoFreder** [comment] 2016-04-05 08:31
Reproducible with the attached vagrant configuration. Steps:

- start vagrant which installs docker on ubuntu trusty on each host and installs rancher server on 172.28.128.20
- open rancher on http://172.27.128.20:8080
- add and select swarm environment
- add new host on the swarm environment
- confirm host registration server url to http://172.27.128.20:8080
- install rancher agent for the two agents
- once installed properly download swarm configuration from the cli page
- configure docker on swarm master to use the tls files
- use provided environment settings (export DOCKER_HOST=tcp://172.28.128.20:8080 DOCKER_TLS_VERIFY=1)
- docker ps on master:
--> error: 
An error occurred trying to connect: Get https://172.28.128.20:8080/v1.22/containers/json: x509: certificate is valid for 127.0.0.1, not 172.28.128.20

same when restarting server or rancher-server

Hope this is helpful

[Vagrantfile.txt](https://github.com/rancher/rancher/files/204059/Vagrantfile.txt)

**Comment by deniseschannon** [comment] 2016-04-05 21:30
Apologies to everyone. It looks as if it was working with the rancher server restart, but it's currently no longer working. We are investigating it.

Note: This works in SSL setups of Rancher, so this is only if don't have Rancher server set up with SSL.

**Comment by pascalandy** [comment] 2016-05-09 15:45
Thanks for the follow up. Can't wait to be able to use my docker-compose setup as usual via Swarm managed by Rancher!

> Apologies to everyone. It looks as if it was working with the rancher server restart, but it's currently no longer working. We are investigating it. Note: This **works in SSL setups of Rancher**, so this is only if don't have Rancher server set up with SSL.

Do you guys have an out of the box SSL solution to start Rancher Server SSL ?

Cheers!

**Comment by bradjones1** [comment] 2016-06-02 06:02
I have Rancher proxied behind Nginx for SSL termination, so by replacing the `ca.pem` that came with the Rancher download with the cert of the reverse proxy cert (but keeping `key.pem` and `cert.pem`) I was able to get a bit further, but then came up with:

```
Error response from daemon: {"id":"066d347e-96a6-4d24-ba24-11f11bdd2a0e","type":"error","links":{},"actions":{},"status":401,"code":"Unauthorized","message":"Unauthorized","detail":null}
```

Which looks like the same issue as https://github.com/rancher/rancher/issues/4844

**Comment by bradjones1** [comment] 2016-06-10 04:23
The CLI tab in the Swarm drop-down appears to be gone in the -dev4 UI.

**Comment by bradjones1** [comment] 2016-06-10 04:38
Confirmed the error is the same in -dev4.

**Comment by todd-alexion** [comment] 2016-08-08 19:20
Also looking forward to a solution (like @pascalandy my co-workers need to use the CLI from their laptops). I am behind an SLL terminated AWS ELB, so I am hoping the Rancher folks can come up with a quick solution.

**Comment by deniseschannon** [comment] 2016-10-04 14:41
As we move to swarmkit, the existing swarm solution will no longer be used, but assigning to @LLParse to confirm.

**Comment by LLParse** [comment] 2016-10-04 17:21
We don't plan to support swarm as it's been deprecated in favor of swarmkit. That being said, this may still be an issue when interacting with a swarm manager via the rancher CLI - so should remain open until we prove otherwise.

**Comment by deniseschannon** [comment] 2017-01-31 19:32
No longer valid due to swarm changes introduced with Docker 1.12.

**Closed by deniseschannon** 2017-01-31 19:32 UTC
Labels: kind/bug
