### ISSUE TITLE
RHEL 8 Support with Docker CE

### ISSUE THREAD

**Issue by cloudnautique** [rancher/rancher#23045] opened 2019-09-24 04:29 UTC
Validate RHEL 8 with Docker CE support.

* Validate Rancher HA
* Validate Rancher Custom Clusters
* Validate Rancher Node drivers with RHEL 8 AMI

gzrancher/rancher#9277         gzrancher/rancher#11129

**Comment by ekarlso** [comment] 2019-12-01 00:29
This should e linked to RKE 1788

**Comment by soumyalj** [comment] 2019-12-20 18:45
Created RHEL8 instances in AWS((ami-0663557a71df84272) and installed docker using the below steps:
```
dnf config-manager --add-repo=https://download.docker.com/linux/centos/docker-ce.repo
dnf list docker-ce
dnf install docker-ce --nobest -y
systemctl start docker
systemctl enable docker
docker --version
docker run hello-world
```
Deployed rancher server using RHEL8 machine and created a custom cluster using RHEL8 node.
Cluster creation failed with the below error:
```
2019/12/20 17:35:16 [ERROR] ClusterController c-kbgrx [cluster-provisioner-controller] failed with : [workerPlane] Failed to bring up Worker Plane: [Failed to verify healthcheck: Service [kube-proxy] is not healthy on host [a.b.c.d]. Response code: [503], response body: {"lastUpdated": "2019-12-20 04:42:52.920242235 +0000 UTC m=+0.112474336","currentTime": "2019-12-20 17:35:11.116694619 +0000 UTC m=+46338.308926872"}, log: Perhaps iptables or your kernel needs to be upgraded.]



```

**Comment by Oats87** [comment] 2020-01-13 19:59
With `iptables` deprecated in RHEL 8, I believe `nftables` will potentially pose problems for us.

**Comment by khushboo-rancher** [comment] 2020-02-10 21:51
Tested on Rancher with RHEL8 instance (64-bit (x86), Virtualization type: hvm) from AWS.

Tried creating custom cluster using RHEL8 instance but failed to create it.
Error:
```
2020/02/10 21:21:23 [ERROR] cluster [c-x4877] provisioning: Failed to get job complete status for job rke-network-plugin-deploy-job in namespace kube-system
2020/02/10 21:21:23 [INFO] kontainerdriver rancherkubernetesengine stopped
2020/02/10 21:21:23 [ERROR] ClusterController c-x4877 [cluster-provisioner-controller] failed with : Failed to get job complete status for job rke-network-plugin-deploy-job in namespace kube-system
```

Logs from node:
```
W0210 21:34:42.206282   23758 iptables.go:508] Could not set up iptables canary mangle/KUBE-KUBELET-CANARY: error creating chain "KUBE-KUBELET-CANARY": exit status 3: modprobe: ERROR: ../libkmod/libkmod.c:586 kmod_search_moddep() could not open moddep file '/lib/modules/4.18.0-80.4.2.el8_0.x86_64/modules.dep.bin'
modprobe: FATAL: Module ip_tables not found in directory /lib/modules/4.18.0-80.4.2.el8_0.x86_64
iptables v1.6.0: can't initialize iptables table `mangle': Table does not exist (do you need to insmod?)
Perhaps iptables or your kernel needs to be upgraded.
E0210 21:34:42.580142   23758 kubelet.go:2183] Container runtime network not ready: NetworkReady=false reason:NetworkPluginNotReady message:docker: network plugin is not ready: cni config uninitialized
W0210 21:34:47.156424   23758 cni.go:237] Unable to update cni config: no networks found in /etc/cni/net.d
```

**Comment by superseb** [comment] 2020-02-11 17:29
Things discovered while working on this:

- Kernel modules are compressed, making `kube-proxy` unable to load them as `modprobe` in the hyperkube image does not support that (https://github.com/kubernetes/kubernetes/issues/60869). To work around this, load the modules yourself. This will be fixed when we move to the new Buster based images.
- As there is no official upstream packages, we install the `centos` Docker repo, add `module_hotfixes=True` to the section in `/etc/yum.repos.d/docker-ce.repo` (to make sure the latest packages can be installed, else the package will be stuck at `18.09.1`), and use `--nobest` to `dnf install`.
- Making sure `net.ipv4.ip_forward = 1` is enabled on boot to make Docker not default to DROP on the FORWARD chain to make sure the pods can connect to the outside.
- Disabling NetworkManager as that is still advised by Docker: https://success.docker.com/article/should-you-use-networkmanager

This is what was used to prepare a host (RHEL 8.1 AMI, also tested on CentOS 8.1 droplet):

```
#!/bin/bash
sudo dnf config-manager --add-repo=https://download.docker.com/linux/centos/docker-ce.repo
sudo sed -i '/^gpgkey=https:\/\/download.docker.com\/linux\/centos\/gpg/a module_hotfixes=True' /etc/yum.repos.d/docker-ce.repo
sudo dnf install docker-ce --nobest -y
sudo systemctl start docker
sudo systemctl enable docker
sudo usermod -aG docker ec2-user || true
for mod in ip_tables ip_vs_sh ip_vs ip_vs_rr ip_vs_wrr; do sudo modprobe $mod; echo $mod | sudo tee -a /etc/modules-load.d/iptables.conf; done
echo "net.ipv4.ip_forward = 1" | sudo tee -a /etc/sysctl.d/50-docker-forward.conf
sudo iptables -P FORWARD ACCEPT
sudo dnf -y install network-scripts
sudo systemctl enable network
sudo systemctl disable NetworkManager
reboot
```

- As there is no `iptables-legacy` mode, you can't really debug iptables on the host. The best way is to use `iptables` binary from the hyperkube container, e.g. `docker exec kube-proxy iptables-save`.

**Comment by deniseschannon** [comment] 2020-02-12 18:09
Summary: Using the script above, if you prep the nodes for either Rancher HA or custom nodes, you can get RHEL8 with Docker CE support, but Docker CE doesn't have install scripts for RHEL 8.

**Comment by ibuildthecloud** [comment] 2020-02-12 22:48
@superseb I'm confused about the iptables-legacy comment.  Is RHEL8 running nftables or iptables?  If they are running nftables, how does kube-proxy work as we have the old iptables binary.

**Comment by The-Loeki** [comment] 2020-02-12 22:53
> 
> @superseb I'm confused about the iptables-legacy comment. Is RHEL8 running nftables or iptables? If they are running nftables, how does kube-proxy work as we have the old iptables binary.

It's using nftables with iptables binaries shimmed as compatibility layers, that's why the 'native' iptables binaries from the hyperkube image are no good

**Comment by ibuildthecloud** [comment] 2020-02-12 23:04
@The-Loeki right, so doesn't that mean that RKE on RHEL8 will be broken for sure?  kube-proxy can not manage the iptables because it's use the iptables from the hyperkube image which is the wrong iptables implementation.

**Comment by superseb** [comment] 2020-02-13 10:17
It is running nftables and does not include the `iptables-legacy` fallback, which for example Debian Buster does. This doesn't mean it cannot work, when we are loading the needed kernel modules, and `kube-proxy` uses its `iptables` binary to program the rules, it still functions. The only issue is that from the host, you cannot interfere with that as you only want to use one framework at a time. So basically what is happening is that we are using the old method, and because `hyperkube` gives us the legacy iptables binary, this can work. As this image does not contain `firewalld`, which normally manages the firewall rules (using nftables), it doesn't interfere. It needs to be disabled if it is running. I also found this Red Hat KB article on using iptables: https://access.redhat.com/solutions/3897641

If this is a feasible solution, that's another discussion but technically this can work and it works, as these steps have been validated in our validation tests for both custom cluster and RKE. The main reason for falling back to the old iptables way is because of the hyperkube image with the older iptables version, thats why the reference is there to the new images which are based on Buster with the needed iptables version to support nftables (apart from all the other components we have to check if they support it, either based on a specific configuration or auto-detect, as we need to support existing OS's and new ones).

**Comment by ibuildthecloud** [comment] 2020-02-14 02:21
@superseb sorry, I'm missing a lot of background knowledge on iptables/nftables. I'll try to do more research so I can better understand this.

**Comment by ibuildthecloud** [comment] 2020-02-14 15:34
@superseb I think we should find an approach where our image has iptables and iptables-legacy and as part of an entrypoint detect and switch to the appropriate one the host is using.  I believe just checking `nft list ruleset` works and doesn't give a blank output is sufficient to detect which one.  But their probably a better approach as I know this is a common problem and k8s has an upstream issue about that I can't find.

**Comment by maggieliu** [comment] 2020-03-19 22:00
@Oats87 Is looking into what's required and the recommendations for RHEL 8 support.

**Comment by Oats87** [comment] 2020-03-23 18:57
I'm not sure that running mixed-mode (`nf_tables` and `ip_tables`) is a good idea for production support, given issues around operating in such a manner like: https://github.com/kubernetes/kubernetes/issues/71305#issuecomment-448052889

In the k/k project, logic was added into the Debian buster-based images (direct images, not hyperkube) to attempt to detect the nft, specifically logic similar to: https://github.com/kubernetes/kubernetes/pull/82966/files#diff-c60536f6b948668f1b8aa52529a35f5aR28 like what @ibuildthecloud has mentioned.

The hyperkube images don't seem to have received these fixes, and are not operating with Debian buster, but instead, still using stretch.

Would it make sense for us to start the ball rolling of managing our own hyperkube images, especially due to the fact that hyperkube was removed in 1.19?

**Comment by Oats87** [comment] 2020-03-23 19:00
One issue of note as well is with the CNI drivers. Flannel does not today support nftables, but could also be updated with logic to check, similar to how we would outfit hyperkube.

**Comment by Oats87** [comment] 2020-06-24 00:38
Attempts to "vanilla" install `docker-ce` without `module_hotfixes=yes` lead to the following results:

```
[root@ck-centos8 ~]# yum install docker-ce
Last metadata expiration check: 0:53:30 ago on Tue 23 Jun 2020 04:39:24 PM PDT.
Error:
 Problem: package docker-ce-3:19.03.12-3.el7.x86_64 requires containerd.io >= 1.2.2-3, but none of the providers can be installed
  - cannot install the best candidate for the job
  - package containerd.io-1.2.10-3.2.el7.x86_64 is filtered out by modular filtering
  - package containerd.io-1.2.13-3.1.el7.x86_64 is filtered out by modular filtering
  - package containerd.io-1.2.13-3.2.el7.x86_64 is filtered out by modular filtering
  - package containerd.io-1.2.2-3.3.el7.x86_64 is filtered out by modular filtering
  - package containerd.io-1.2.2-3.el7.x86_64 is filtered out by modular filtering
  - package containerd.io-1.2.4-3.1.el7.x86_64 is filtered out by modular filtering
  - package containerd.io-1.2.5-3.1.el7.x86_64 is filtered out by modular filtering
  - package containerd.io-1.2.6-3.3.el7.x86_64 is filtered out by modular filtering
(try to add '--skip-broken' to skip uninstallable packages or '--nobest' to use not only best candidate packages)
[root@ck-centos8 ~]#
```

The root cause for why the `docker-ce` package from download.docker.com does not work out of box with CentOS 8/RHEL 8 is due to modularity, namely conflicts between:
```
runc
container-selinux
```

Both of these packages belong to the `container-tools` module, yet are required by `containerd`. The `containerd` package brings a `runc` to the table, which conflicts with the `runc` that is installed/part of `container-tools`. If you attempt to `dnf module disable container-tools` you'll then get conflicts as `container-selinux` is a specific module-included package and is thus filtered out as such:

```
[root@ck-centos8 ~]# yum install docker-ce
Last metadata expiration check: 0:54:33 ago on Tue 23 Jun 2020 04:39:24 PM PDT.
Error:
 Problem: package docker-ce-3:19.03.12-3.el7.x86_64 requires container-selinux >= 2:2.74, but none of the providers can be installed
  - cannot install the best candidate for the job
  - package container-selinux-2:2.124.0-1.gitf958d0c.module_el8.2.0+303+1105185b.noarch is filtered out by modular filtering
  - package container-selinux-2:2.124.0-1.module_el8.2.0+304+65a3c2ac.noarch is filtered out by modular filtering
  - package container-selinux-2:2.124.0-1.module_el8.2.0+305+5e198a41.noarch is filtered out by modular filtering
(try to add '--skip-broken' to skip uninstallable packages or '--nobest' to use not only best candidate packages)
[root@ck-centos8 ~]#
```

Upstream, a patch was made to the `containerd.spec` to not include `runc` as a `provides` but this seems dangerous as it could cause actual conflicts with the `runc` package that is installed by default on CentOS etc. Regardless, there is merged support for building a `centos-8` `rpm` but these are not currently published to the public `download.docker.com` repo (https://github.com/docker/containerd-packaging/pull/148/files).

**Comment by Oats87** [comment] 2020-06-25 18:35
Hyperkube images `v1.16.12`, `v1.17.8`, and `v1.18.5` have been bumped to `debian-hyperkube-base` `v1.1.0` which includes the `iptables-detect` script. This means that Kubernetes itself (namely the Kubelet/Kube-proxy) can operate with `nf_tables`, but we still need to figure out how to reliably install `docker-ce` and repackage the `flannel`/`calico` images for `iptables-detect`

**Comment by Oats87** [comment] 2020-08-12 20:33
Interestingly, if you disable the `container-tools` module, you are able to cleanly install `docker-ce` on CentOS 8.

```
[root@ck-centos-8-base ~]# dnf module disable container-tools
CentOS-8 - AppStream                                                                         58 kB/s | 4.3 kB     00:00
CentOS-8 - AppStream                                                                        973 kB/s | 5.8 MB     00:06
CentOS-8 - Base                                                                              12 kB/s | 3.9 kB     00:00
CentOS-8 - Base                                                                             1.7 MB/s | 2.2 MB     00:01
CentOS-8 - Extras                                                                           3.6 kB/s | 1.5 kB     00:00
CentOS-8 - Extras                                                                            12 kB/s | 6.7 kB     00:00
Dependencies resolved.
============================================================================================================================
 Package                      Architecture                Version                        Repository                    Size
============================================================================================================================
Disabling modules:
 container-tools

Transaction Summary
============================================================================================================================

Is this ok [y/N]: y
Complete!
[root@ck-centos-8-base ~]# wget -O /etc/yum.repos.d/docker-ce.repo https://download.docker.com/linux/centos/docker-ce.repo
--2020-08-12 13:30:26--  https://download.docker.com/linux/centos/docker-ce.repo
Resolving download.docker.com (download.docker.com)... 13.227.75.73, 13.227.75.47, 13.227.75.5, ...
Connecting to download.docker.com (download.docker.com)|13.227.75.73|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 2424 (2.4K) [binary/octet-stream]
Saving to: ‘/etc/yum.repos.d/docker-ce.repo’

/etc/yum.repos.d/docker-ce.rep 100%[====================================================>]   2.37K  --.-KB/s    in 0s

2020-08-12 13:30:26 (23.8 MB/s) - ‘/etc/yum.repos.d/docker-ce.repo’ saved [2424/2424]

[root@ck-centos-8-base ~]# yum install docker-ce
Docker CE Stable - x86_64                                                                   236 kB/s |  25 kB     00:00
Dependencies resolved.
============================================================================================================================
 Package                      Architecture          Version                           Repository                       Size
============================================================================================================================
Installing:
 docker-ce                    x86_64                3:19.03.12-3.el7                  docker-ce-stable                 24 M
Installing dependencies:
 containerd.io                x86_64                1.2.13-3.2.el7                    docker-ce-stable                 25 M
     replacing  runc.x86_64 1.0.0-65.rc10.module_el8.2.0+305+5e198a41
 docker-ce-cli                x86_64                1:19.03.12-3.el7                  docker-ce-stable                 38 M
 libcgroup                    x86_64                0.41-19.el8                       BaseOS                           70 k

Transaction Summary
============================================================================================================================
Install  4 Packages

Total download size: 88 M
Is this ok [y/N]: y
Downloading Packages:
(1/4): libcgroup-0.41-19.el8.x86_64.rpm                                                     575 kB/s |  70 kB     00:00
(2/4): docker-ce-19.03.12-3.el7.x86_64.rpm                                                   14 MB/s |  24 MB     00:01
(3/4): containerd.io-1.2.13-3.2.el7.x86_64.rpm                                               14 MB/s |  25 MB     00:01
(4/4): docker-ce-cli-19.03.12-3.el7.x86_64.rpm                                               18 MB/s |  38 MB     00:02
----------------------------------------------------------------------------------------------------------------------------
Total                                                                                        34 MB/s |  88 MB     00:02
warning: /var/cache/dnf/docker-ce-stable-091d8a9c23201250/packages/containerd.io-1.2.13-3.2.el7.x86_64.rpm: Header V4 RSA/SHA512 Signature, key ID 621e9f35: NOKEY
Docker CE Stable - x86_64                                                                    67 kB/s | 1.6 kB     00:00
Importing GPG key 0x621E9F35:
 Userid     : "Docker Release (CE rpm) <docker@docker.com>"
 Fingerprint: 060A 61C5 1B55 8A7F 742B 77AA C52F EB6B 621E 9F35
 From       : https://download.docker.com/linux/centos/gpg
Is this ok [y/N]: y
Key imported successfully
Running transaction check
Transaction check succeeded.
Running transaction test
Transaction test succeeded.
Running transaction
  Preparing        :                                                                                                    1/1
  Installing       : docker-ce-cli-1:19.03.12-3.el7.x86_64 [========================         Installing       : docker-ce-cli-1:19.03.12-3.  Installing       : docker-ce-cli-1:19.03.12-3.el7.x86_64                                                                             1/5
  Running scriptlet: docker-ce-cli-1:19.03.12-3.el7.x86_64                                                                             1/5
  Installing       : containerd.io-1.2.13-3.2.el7.x86_64                                                                               2/5
  Running scriptlet: containerd.io-1.2.13-3.2.el7.x86_64                                                                               2/5
  Running scriptlet: libcgroup-0.41-19.el8.x86_64                                                                                      3/5
  Installing       : libcgroup-0.41-19.el8.x86_64                                                                                      3/5
  Running scriptlet: libcgroup-0.41-19.el8.x86_64                                                                                      3/5
  Installing       : docker-ce-3:19.03.12-3.el7.x86_64                                                                                 4/5
  Running scriptlet: docker-ce-3:19.03.12-3.el7.x86_64                                                                                 4/5
  Obsoleting       : runc-1.0.0-65.rc10.module_el8.2.0+305+5e198a41.x86_64                                                             5/5
  Running scriptlet: runc-1.0.0-65.rc10.module_el8.2.0+305+5e198a41.x86_64                                                             5/5
  Verifying        : libcgroup-0.41-19.el8.x86_64                                                                                      1/5
  Verifying        : containerd.io-1.2.13-3.2.el7.x86_64                                                                               2/5
  Verifying        : runc-1.0.0-65.rc10.module_el8.2.0+305+5e198a41.x86_64                                                             3/5
  Verifying        : docker-ce-3:19.03.12-3.el7.x86_64                                                                                 4/5
  Verifying        : docker-ce-cli-1:19.03.12-3.el7.x86_64                                                                             5/5
Installed products updated.

Installed:
  containerd.io-1.2.13-3.2.el7.x86_64 docker-ce-3:19.03.12-3.el7.x86_64 docker-ce-cli-1:19.03.12-3.el7.x86_64 libcgroup-0.41-19.el8.x86_64

Complete!
[root@ck-centos-8-base ~]#
```

**Comment by Oats87** [comment] 2020-08-12 20:48
Ah. Red herring, as the `container-selinux` package seems to have been already installed on the system already.

**Comment by Oats87** [comment] 2020-08-14 20:13
So, there are a few ways to get `docker-ce` installed, but none of them are particularly ideal. The root crux of the problem as to why you cannot simply consume the `el7` packages from `download.docker.com` for CentOS 8/RHEL 8 is due to the fact that the containerd RPM "provides" `runc`, which conflicts with the `runc` that comes out of the `container-tools` module. On the same strain however, you need `container-selinux` which is a part of the `container-tools` module... This leaves us with the following choices:

1. Disable the `container-tools` module but still install `container-selinux` from the module as an RPM/manually, which satisfies the requirement for it. This is dirty, and leaves `container-selinux` open to potentially not being updated down the line.
2. Install the RPM's directly, bypassing the package manager. This is a bad option.
3. "Modularize" `docker-ce`. Due to complexities in the way `docker-ce` and `containerd` are packaged, this is a non-trivial task and will require a very hard fork of packaging, thus leaving Rancher responsible for maintaining the packages fully.
4. Enable the `container-tools` module, but `yum remove runc` or make sure the modular `runc` is not installed. Then, recompile the `containerd.io` rpm and provide it via a Rancher-created yum repository, which then allows `yum install docker-ce` to proceed as it will resolve the containerd.io requirement to "our" RPM.

**Comment by joelrebel** [comment] 2020-08-27 13:43
Just in case its useful, these were the steps that worked for me,
```
dnf module enable container-tools && \
dnf install container-selinux && \
dnf module disable container-tools && \
dnf install docker-ce
```

**Comment by superseb** [comment] 2020-09-22 12:09
Docker 19.03.13 seems to have packages available for RHEL/CentOS8, https://download.docker.com/linux/centos/8/x86_64/stable/Packages/

**Comment by ryebread157** [comment] 2020-10-07 15:26
> Docker 19.03.13 seems to have packages available for RHEL/CentOS8, https://download.docker.com/linux/centos/8/x86_64/stable/Packages/

This Rancher support article references Docker CE 20.03 on RHEL/CentOS8, a release that is not visible at the public sources for CentOS7 or 8. Now that a stable 19.03 release is available on CentOS8 just as it is for CentOS7, will this also be supported? https://support.rancher.com/hc/en-us/articles/360045055172-How-and-when-will-Rancher-support-RHEL-CentOS-8-

**Comment by superseb** [comment] 2020-10-07 16:15
No, many observations have been posted in this issue but as long as official articles are not updated/this GitHub issue is not validated/closed, it's not supported. In this case, this is scoped to RKE.

**Comment by Oats87** [comment] 2020-10-16 21:42
Now that Docker `19.03.13` has corresponding packages for el8, we can look at bringing in support for CentOS 8/RHEL 8 for Rancher when using RKE K8s 1.19 and above.

**Comment by Oats87** [comment] 2020-10-16 23:51
The Docker `19.03.13` `el8` `rpm`'s require a minor change to the `install-docker` script to use as `makecache fast` is not supported on the system, as well as cannot have a pre-existing `runc` on the system as the `containerd` package will conflict.

Interestingly, when observing CentOS 8, there are different "stock" configurations.

An AMI from: https://wiki.centos.org/Cloud/AWS does not have `runc` installed, but you will need to manually `yum|dnf install iptables` in order to allow our `https://releases.rancher.com/install-docker/19.03.sh` script to work. 

A `CentOS 8` install from ISO has `runc` installed on it so you will need to `yum|dnf remove runc`

**Comment by bashofmann** [comment] 2020-10-19 14:22
I was able to successfully create a cluster on AWS and CentOS 8 with making these changes in the 19.03.13.sh install script. If you want, I can create a PR for this. Though there are maybe some more changes needed for RHEL 8. My current diff:

```
diff --git a/19.03.13.sh b/19.03.13.sh
index e1a4013..ac4fb42 100644
--- a/19.03.13.sh
+++ b/19.03.13.sh
@@ -443,7 +443,14 @@ do_install() {
 					$sh_c "$config_manager $enable_channel_flag docker-ce-$CHANNEL"
 				fi
 				adjust_repo_releasever "$dist_version"
-				$sh_c "$pkg_manager makecache fast"
+                               if [ "$dist_version" -lt "8" ]; then
+  				     $sh_c "$pkg_manager makecache fast"
+  			        else
+                                   $sh_c "$pkg_manager makecache"
+                                   if $sh_c "$pkg_manager list installed -q runc"; then
+                                       $sh_c "$pkg_manager remove -y -q runc"
+                                   fi
+				fi
 				$sh_c "$pkg_manager install -y -q docker-ce-${docker_version} docker-ce-cli-${docker_version}"
 				if [ -d '/run/systemd/system' ]; then
 					$sh_c 'service docker start'
```

**Comment by Oats87** [comment] 2020-10-19 18:03
@bashofmann 

The logic proposed in that script makes sense, although I'd be hesitant to auto-remove `runc` as it is normally installed as dependency for a ton of other things on an EL8 system, like `podman` etc. There is also additional logic that is required for RHEL systems, as the current `install-docker` appears to ensure that a few RHEL 7 repositories are enabled before allowing installation. These can be seen here: https://github.com/rancher/install-docker/blob/master/19.03.13.sh#L17 and are enabled here: https://github.com/rancher/install-docker/blob/master/19.03.13.sh#L429

A PR into `install-docker` would be welcome

**Comment by bashofmann** [comment] 2020-10-20 11:00
Should the script then just fail if runc is already present in a conflicting version and we document this?

For RHEL8 it seems that the repository structure changed quite a bit (https://access.redhat.com/discussions/4171061#comment-1531531). It sounds like we don't have to enable any additional ones. But I have no way of testing this at the moment.

**Comment by maggieliu** [comment] 2020-10-22 17:59
@aaronRancher please take a look at the comment [here](https://github.com/rancher/install-docker/pull/56#issuecomment-714615113). There are some pre-requisites for testing this. Please reach out to @chrisreed87  if there is any questions. We will be documenting the pre-requisites in the release notes.

**Comment by aaronRancher** [comment] 2020-10-28 00:13
Validated with Rancher server `rancher\rancher:master-head` `version 3d755ff` and `rancher\rancher:v2.5-head` `version 7eb1792`
Installed docker with:
```
curl -L https://releases.rancher.com/install-docker/19.03.sh | sh
```

Validated Rancher HA install
```
INFO[0133] [addons] Executing deploy job rke-ingress-controller
INFO[0139] [ingress] ingress controller nginx deployed successfully
INFO[0139] [addons] Setting up user addons
INFO[0139] [addons] no user addons defined
INFO[0139] Finished building Kubernetes cluster successfully
```
```
$ kubectl -n cattle-system rollout status deploy/rancher
Waiting for deployment "rancher" rollout to finish: 0 of 3 updated replicas are available...
Waiting for deployment "rancher" rollout to finish: 1 of 3 updated replicas are available...
Waiting for deployment "rancher" rollout to finish: 2 of 3 updated replicas are available...
Waiting for deployment spec update to be observed...
Waiting for deployment "rancher" rollout to finish: 2 of 3 updated replicas are available...
deployment "rancher" successfully rolled out
```
Validated Rancher Custom Clusters

Validated Rancher Node drivers with RHEL 8 AMI
![Screen Shot 2020-10-27 at 5 05 08 PM](https://user-images.githubusercontent.com/57409052/97374882-a0ec9980-1876-11eb-904d-318a1cfd1682.png)

**Closed by aaronRancher** 2020-10-28 00:13 UTC
Labels: [zube]: To Test, alpha-priority/1, internal, kind/task
