### ISSUE TITLE
Ability to schedule containers across pools of hosts (ie. zones/regions)

### ISSUE THREAD

**Issue by deniseschannon** [rancher/rancher#7253] opened 2017-01-03 04:40 UTC
Add ability to tag pools of hosts (i.e. as a zone or region) and be able to schedule containers evenly across those pool of hosts.

**Comment by cjellick** [comment] 2017-02-06 21:19
Implement using labels.

Semantically, should work like this:
Schedule 50% of the containers for this service to hosts who have label `io.rancher.hosts.group=us-west-1a` and 50% to hosts who have a label `io.rancher.hosts.group=us-west-1b`.

The scheduling rule should be defined as a label on the service like this:
`io.rancher.scheduler.spread.host_label=io.rancher.hosts.group=us-west-1a,50;io.rancher.hosts.group=us-west1b,50`

The number of labels that you spread across must be arbitrary.

Implement in the external scheduler.

### Questions
- What if the % is out of whack or we are unable to comply?
  - What if there are no hosts matching one of the labels and the service is scaled up? Do we fail to schedule or do we schedule to hosts out of the first host group?
  - What about when we are deploying the very first container of the service? The second? The % spread is a thing achieved over time and will be wrong until everything is settled.

**Comment by sangeethah** [comment] 2017-02-07 01:13
@cjellick , In the above example you have provided , would we strive to keep the container deployments with in the hosts having the label - ```io.rancher.hosts.group=us-west-1a``` even ? For example , I have a service with scale 12 and 6 have gone to hosts with ```io.rancher.hosts.group=us-west-1a``` and 6 have gone to ```io.rancher.hosts.group=us-west-1b```. If there were 2 hosts with label ```io.rancher.hosts.group=us-west-1a``` , should we expect each of these hosts to have 3 containers in them ?  

Also, when we add new host to the setup with these labels , will these host start being used for service spread over the other existing hosts with same labels?

**Comment by vincent99** [comment] 2017-02-07 03:31
I'll just throw in my usual we've gone mad with labels and there should be real typed api for this instead of semicolon comma equal separated strings...

**Comment by vincent99** [comment] 2017-02-07 03:39
Why would there label being spread on be `io.rancher` instead of arbitrary user string?

The scores should be weights instead of percentages so that they don't have to say up to any particular number.  I.e.  A=1, B=2, C=3 means 1/(1+2+3)=1/6th  go on A.

You really want to support multiple labels instead of one label with varying values?  What weight/% does a host that has 2 different matching labels get?

Rounding is going to be very weird with either weights or percentage for any low number of scale.  Would just an explicit scale per label value make more sense?

**Comment by StrongMonkey** [comment] 2017-02-09 18:33
My inputs:
Scheduler has a zone map. Key is the name of zone, and value is a struct contains the hosts belongs to the zone and the total number of instance launched per service in the zone. I assume a zone can have multi-host on it, but one host can't have more than one zone label. So according the ratio which user puts in labels and the instance already launched in the zone, scheduler decides which zone to put for that  instance. Inside the zone, scheduler prioritize the hosts according to the resource requests. So, short story, i am working on the assumption:
1. A host can not have more than one host zone label. There is no host overlapping
2. User will put weights instead of percentage(vince's suggestion)
3. We will never achieve perfect spread as user may put arbitrary percentage, or service upgrade.

**Comment by StrongMonkey** [comment] 2017-03-01 18:49
I am reconstructing my design for this feature:
Let's say that Service A has a scale of 10 and user wants to distribute the service across zones(West 1, West2, West3). So:

1.  Users must provide a label like `io.rancher.service.scale_per_zone: West1=3, West2=4, West3=3` to explicitly assign instances to specific zone. This will cause 3 of the instances landing on the host labeled as `AZ=West1`, 4 of the instances landing on the host `AZ=West2` and the rest landing on the host `AZ=West3`.
2.  If Users want to scale or descale the instances, they must explicitly redistribute the instances across different zones. For example, if they want to add one instance, they must specify the zone they want to increase. For example, increase the West1 by one. The label `io.rancher.service.scale_per_zone: West1=3, West2=4, West3=3`  should be changed to `io.rancher.service.scale_per_zone: West1=4, West2=4, West3=3` so that the label always matches the total scale of the instances.
3. By putting hard affinity constraints to force the instances goes to different zones. This should probably handle the upgrade scenario.
4. Failure scenario. What if West-1 hosts go down? should we schedule the instance of West-1 to the other two zone or leave as it is? My thought was to leave it as it is and still keeps the schedule `West2=4, West3=3` and let users change the label to reassign instances.

**Comment by StrongMonkey** [comment] 2017-03-01 18:57
@cjellick This could possibly be implemented in cattle side. Almost of them are done in the service side and Doing that in external scheduler seems to be prone to erroneous.

**Comment by cjellick** [comment] 2017-03-01 20:53
@vincent99 replies to your points:

> I'll just throw in my usual we've gone mad with labels and there should be real typed api for this instead of semicolon comma equal separated strings...
I agree! Soooo, can we just do it as a field or would we then need to completely refactor all service scheduling to fields? Would the incompatibility with docker-compose make it a non-starter?

> Why would the label being spread on be io.rancher instead of arbitrary user string? Are we managing that value from machine providers? Custom hosts added from clouds that have a zone/region concept?
While my example used an `io.rancher`, my intent was for it to be any arbitrary label. I used that example label because talked about a possible "next step" being to create a hostScalingGroup type resouce in cattle, which would translate to adding a io.rancher label to hosts for traking purposes.

The scores should be weights instead of percentages so that they don't have to add up to any particular number. I.e. A=1, B=2, C=3 means 1/(1+2+3)=1/6th go on A.
> Yes, weights seem to be a better.

> You really want to support multiple labels instead of one label with varying values? What weight/% does a host that has 2 different matching labels get?
No, I'd prefer to do it as you suggest with just a single label with different values. Not sure if I made that requirement up or got it from somewhere. I generally try to strawman requirements that I'm unsure of, so maybe that's what I did here.

> Rounding is going to be very weird with either weights or percentage for any low number of scale. Would just an explicit scale per label value make more sense?
Explicit scale seems less usable.

**Comment by cjellick** [comment] 2017-03-01 21:03
@StrongMonkey your scale_per_zone idea is basically the same as @vincent99's `Would just an explicit scale per label value make more sense?` question.

When presented as a scale per zone, it makes more sense to me. I guess with this solution we would have to then ignore the scale field? We should probably think through the impacts of having the two conflicting ways of setting scale.

**Comment by StrongMonkey** [comment] 2017-03-01 22:20
After discussion with Craig, we came out the following implementation:
1. Implemented in service level. Which means we set RequestedHostId to container when we decide to spread container cross different zones. Pros: easy to implement. Cons: will skip all the existing external scheduler logic.
2. Implemented in container allocation level. When scaling the instance, label different hard affinity constraints so they can go to different zones. Pros: can go through existing allocation logic. Cons: need to deal with service upgrade and scaling or descaling.
3. Implemented in external scheduler. Keeping an in-memory map in scheduler to decide which zone to put. Pros: Go code. Cons: too complicated to implement.

**Comment by StrongMonkey** [comment] 2017-03-02 00:55
After Discussion with Craig, we came up with the following solution:
1. Implemented this in external scheduler. 
2. There will be a framework change in cattle.  When the service come with a scale_per_zone label, we send those allocation to external scheduler. Because there is no global lock in scheduler, the hosts returned by scheduler.priortize may be erroneous. In order to avoid the incorrect allocation, we will add a check in scheduler.reserve to check if the allocation follows the weight which user specified. If not, return a lock key in cattle, and cattle use the lock key to lock the instance and then recall the external scheduler. the rest of the instance share the same lock key. The instance will fail after the third retry.
Scenario:
Service A comes with scale of 4 and a label to distribute instance 2 to Zone A , 2 to Zone B. All of 4 go to scheduler.priortize at the same time, and because of the race condition, scheduler returns Zone A. Then all of them go to scheduler.reserve for Zone A. According to the algorithm, the first one should pass cause it should land on Zone A. But the second one will fail because it should go to Zone B. Then scheduler give instance 2 to lock key and send it back to cattle. Cattle get the key and retry the instance 2 with lock key to prevent instance 3 and 4 go through the scheduler at the same time. Then instance 2 succeed. Then instance 3 acquire the lock and succeed. Then instance 4 succeed. All of 4 will land on the correct host eventually.
So, changes need to be made:
1. Cattle. Change the framework to retry three times with lock returned by scheduler if it is a scale_per_zone service. 
2. Scheduler. Implementing algorithms to distribute instances across different zones and weights. return lock key if  failed to reserve for scale_per_zone service.

**Comment by cjellick** [comment] 2017-03-02 16:26
@StrongMonkey that seems pretty correct. Can you now write up the use cases describing how this will be used? Cover both the single-host scenario (from issue #2558) and multi-host zones. Go into detail of what the UX would be. Exactly what the label will be name and the format of its value.

**Comment by StrongMonkey** [comment] 2017-03-02 17:04
Here are some possible label names for that:
Service A has 4 instances and wants to distribute instances to:
1. equally cross the zone. For example, service A has a label named `io.rancher.scheduler.scale_per_zone: even`. We have two hosts 1, 2. Host 1 has a label `io.rancher.scheduler.host_scale_group: west1` and Host 2 has a label `io.rancher.scheduler.host_scale_group: west2`. Then 2 instances will land on host 1 and 2 instances will land on host 2.
2. equally cross the zone. For example, service A has a label named `io.rancher.scheduler.scale_per_zone: even`. We have three hosts 1, 2 and 3. Host 1 has a label `io.rancher.scheduler.host_scale_group: west1` , Host 2 has a label `io.rancher.scheduler.host_scale_group: west2` and Host 3 has a label `io.rancher.scheduler.host_scale_group: west2`. Then 2 instances will land on host 1 and 2 instances will land on either host2 or host3(they are in the same group).
3. Special weight distribution across the zones. For example, service A has a label named `io.rancher.scheduler.sclae_per_zone: west1=1, west2=3`. We have two hosts 1, 2. Host 1 has a label `io.rancher.scheduler.host_scale_group: west1` and Host 2 has a label `io.rancher.scheduler.host_scale_group: west2`. Then 1 instances will land on host 1 and 3 instances will land on host 2.
4. Special weight distribution across the zones. For example, service A has a label named `io.rancher.scheduler.sclae_per_zone: west1=1, west2=3`. We have three hosts 1, 2 and 3. Host 1 has a label `io.rancher.scheduler.host_scale_group: west1` , Host 2 has a label `io.rancher.scheduler.host_scale_group: west2` and Host 3 has a label `io.rancher.scheduler.host_scale_group: west2`. Then 1 instances will land on host 1 and 3 instances will land on either host2 or host3(they are in the same group).

**Comment by cjellick** [comment] 2017-03-02 18:29
I think you've not made the even concept clear and it may not even be needed, but my idea there was to give the user some way to just say "i want even spread across the zones, as simply as possible." To me this mean not having to specify each "zone" value (ie west1, west2).

In all your examples, since the label key denoting the group is arbitrary, you are missing the label key.
Should it be something like: `io.rancher.scheduler.host_scale_group: 'key=zone;west1=1,west2=1`? Where key denotes the label key we'll use?

**Comment by StrongMonkey** [comment] 2017-03-02 20:34
@cjellick Yeah, i missed that part. Will update comments.

**Comment by sangeethah** [comment] 2017-03-11 00:42
@StrongMonkey @cjellick , Have the following questions after initial review of the design.

Assume we have 4 hosts in setup with following host labels for the scenarios discussed below:

Host1 with label - zone1=east
Host2 with label - zone1=west
Host3 with label - zone2=east,west
Host4 with label - zone2
Host5 with label - zone2=east
Host6 with label - zone2=west


1. How are hosts that have no value for labels handled like host4 ?
Create service with scale 4 with label io.rancher.scheduler.host_scale_group: key=zone2
 What is the expected distribution in this case?

2. How are hosts that have multiple values for labels handled like host3 ?
Create service with scale 4 with label io.rancher.scheduler.host_scale_group: key=zone2
What is the expected distribution in this case?

3. Do we expect redistribution of service containers to happen in the following scenario?

Scenario 1:
Create service with scale 4 with label io.rancher.scheduler.host_scale_group: key=zone1
 Add a new host with  label - zone1=north
Scenario 2:
Create service with scale 4 with label io.rancher.scheduler.host_scale_group: key=zone1
Edit an existing host with  label - zone1=east and make it zone1=west
Scenario 3:
Create service with scale 4 with label io.rancher.scheduler.host_scale_group: key=zone1
Edit an existing host with  label - zone1=east and remove the label zone1

In all the above scenarios:
Should we expect service reconcile get triggered automatically which should result in equal distribution on containers as per the current host labels ?
Or would there need to be a manual trigger for service reconcile(like service scale up/service instance deletion)  which would eventually catch up to the required distribution model?

4. When there are services with sidekicks  , we expect io.rancher.scheduler.host_scale_group set in primary services to be inherited to all the sidekicks ? It does not make sense to have different  io.rancher.scheduler.host_scale_group set for primary vs side kick services ?

5. In case of services with exposed ports/service labels , will not being able to satisfy the distribution rule result in containers not being deployed?

Have 3 hosts (he1,he2,he3) with label - zone1=east , 1 host (hw1) with label - zone1=west and 1 host(h1) with no label
Create service with scale 4 with exposed ports and label io.rancher.scheduler.host_scale_group: key=zone1

What should be the expected behavior in this case ? Will all the 4 instances get created 1 each in he1,he2,he3 and hw1. Or will only 2(or 3) instances get created since the equal distribution rule cannot be satisfied after this?  

6. Create health check enabled  service with scale 4 with label io.rancher.scheduler.host_scale_group: key=zone1
2 instances land on Host1 and 2 instances in Host2.
Power down Host1 (which is the only host in east zone) .  We mark the current instances in host1 for deletion and try to start a new instance in Host2. Will "east" zone still be considered a valid zone since we do not have any healthy host with this label , in which case instances will not be able to start in Host2 . Or will   "east" zone still be considered not a valid zone and instances get created in Host1.

**Comment by brutus333** [comment] 2017-03-13 09:00
Any news on that? It would be a really useful feature (+10).

**Comment by StrongMonkey** [comment] 2017-03-13 17:07
@sangeethah 
Answer for the Q1 and Q2: We don't handle the case `zone2=`, If no value is given, it will not be chosen as a valid candidate. Also we do not handler the case `zone2=east,west`, which the underlying assumption is that a host can't have multi-zone assigned to it. So `east, west` will be considered as a zone(i am grouping them by value). Then a scale of 4 will be distributed across three different zones, which are `east`, `west`, `east,west`.

> Should we expect service reconcile get triggered automatically which should result in equal distribution on containers as per the current host labels ?
Service reconcile will get triggered but afaik, service reconcile doesn't move the existing running container. So It will not rebalance the number until you add more instance into the service.

> Or would there need to be a manual trigger for service reconcile(like service scale up/service instance deletion) which would eventually catch up to the required distribution model?
This might be related to another issue https://github.com/rancher/rancher/issues/2558. We can keep track on this but i believe this is a different issue. I think changing instance to another host to rebalance the distribution is more like a service upgrade, where you deleted the old instance and launch new instance on instance. We don't know the impact of this but may need to discuss with @alena1108 to see how this could implemented.

> When there are services with sidekicks , we expect io.rancher.scheduler.host_scale_group set in primary services to be inherited to all the sidekicks ? It does not make sense to have different io.rancher.scheduler.host_scale_group set for primary vs side kick services
Sickkicks containers will always go to the same host where primary container landed, no matter what label it has. Otherwise it will be a conflict in scheduler framework.

> In case of services with exposed ports/service labels , will not being able to satisfy the distribution rule result in containers not being deployed?
If there is a conflict for the distribution rule and other constraints(like ports and require_any labels), it will raise an error in scheduling phase and instance will not be launched.

> What should be the expected behavior in this case ? Will all the 4 instances get created 1 each in he1,he2,he3 and hw1. Or will only 2(or 3) instances get created since the equal distribution rule cannot be satisfied after this?
2 instances should be launched on hw1 and 2 instance will be launched between he1, he2, he3.

> Power down Host1 (which is the only host in east zone) . We mark the current instances in host1 for deletion and try to start a new instance in Host2. Will "east" zone still be considered a valid zone since we do not have any healthy host with this label , in which case instances will not be able to start in Host2 . Or will "east" zone still be considered not a valid zone and instances get created in Host1.
It will not consider east as valid host if the host is **really** deleted.(not showing in the metadata)

**Comment by StrongMonkey** [comment] 2017-03-13 21:00
@brutus333 This feature is in `Working In Progress`. It should be available in 1.6.

**Comment by soumyalj** [comment] 2017-04-13 19:05
@StrongMonkey : Need some more clarification for the following question from Sangeetha:
"Power down Host1 (which is the only host in east zone) . We mark the current instances in host1 for deletion and try to start a new instance in Host2. Will "east" zone still be considered a valid zone since we do not have any healthy host with this label , in which case instances will not be able to start in Host2 . Or will "east" zone still be considered not a valid zone and instances get created in Host1.

It will not consider east as valid host if the host is really deleted.(not showing in the metadata)"

What will happen to the instances, when host1 is powered down? (Since host with east zone is not available) Will they be deployed ?

**Comment by StrongMonkey** [comment] 2017-04-13 20:54
@soumyalj I think the right behavior is that the instance should be created on host2 since host1 is not available any more

**Comment by jeanlouisboudart** [comment] 2017-05-22 20:03
Any update on this ? 
This would save us hours on our projects.

**Comment by HcgRandon** [comment] 2017-08-28 23:21
any news on this. would save me a lot of effort to have this

**Comment by kimberlad** [comment] 2017-10-24 08:53
So if this has been removed from Rancher 2.0 ; when is it scheduled? This is pretty fundamental for AWS users as multi-az is a prereq for 99.95% SLA on AWS.

**Comment by HcgRandon** [comment] 2017-10-25 09:15
This really needs to stop being moved back, this is a *extremely* important feature and should be treated as such. I have to run four of the same services with a number tacked on the end to get them to balance to the proper servers due to the fact that load doesn't occur till several minutes after the container starts. 

If left unchecked all of the 128 containers I'm running would end up on a server or two and proceed to crash said server(s) after load hits them.

**Comment by kimberlad** [comment] 2017-10-25 09:24
Looking into this more it would seem that Kubernetes 1.2 provides support https://kubernetes.io/docs/admin/multiple-zones/ and Rancher 2.0 will be built on Kubernetes 1.2 https://rancher.com/rancher2-0/ is the answer wait for Rancher 2.0 ?

**Comment by aemneina** [comment] 2017-10-25 18:03
@HcgRandon you should be able to schedule containers with anti affinity, so they dont schedule with other containers of the same service. The doc's for this are [here](http://rancher.com/docs/rancher/v1.6/en/cattle/scheduling/#table-of-scheduling-labels)

One could also label hosts per az and create a service per az... there are ways to overcome this creatively with a little overhead. Hope that helps.

**Comment by jimethn** [comment] 2018-08-08 14:17
Any news on multi-AZ support within the same template?

**Closed** 2018-08-21 22:15 UTC
Labels: area/scheduler, kind/enhancement, priority/-1, status/autoclosed, version/2.0

**Comment by jgoerz** [comment] 2023-10-19 21:38
Posting this here in case anyone else is still maintaining rancher 1.6 while prepping for upgrade to rancher 2.X.   I'm not sure when it became available, but you can balance across hosts using a combination of labels and resource limits.

1. Label the hosts you want to balance across.  e.g. io.rancher.scheduler.affinity:host_label: 'Type=API'
2. Go to the host and edit it so you can see the Memory and mCPU limits.
