### ISSUE TITLE
Add EC2 tags to nodes

### ISSUE THREAD

**Issue by ballerabdude** [rancher/rancher#13127] opened 2018-04-26 19:26 UTC
**Rancher versions:**
rancher/server or rancher/rancher: v2.0.0-beta4-rc4
rancher/agent or rancher/rancher-agent:

**Infrastructure Stack versions:**
healthcheck:
ipsec:
network-services:
scheduler:
kubernetes (if applicable):

**Docker version: (`docker version`,`docker info` preferred)**

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**

**Steps to Reproduce:**

**Results:**

I would like to make a pull request to give me the ability to tag my instances on aws from the cluster configuration/creation page. Where in the code can I make this change?

**Comment by superseb** [comment] 2018-04-26 19:27
Duplicate of https://github.com/rancher/rancher/issues/13069

**Closed by superseb** 2018-04-26 19:27 UTC
