### ISSUE TITLE
[Logging v1] Support logging v1 on Windows 1909 SAC

### ISSUE THREAD

**Issue by maggieliu** [rancher/rancher#30279] opened 2020-12-01 00:22 UTC
Focus on elasticSearch first. 

Helpful info:
* Logging v1 does work on regular Windows Server
* Could be similar to monitoring issue commented [here](https://github.com/rancher/rancher/issues/27911#issuecomment-734035961)

gz#13619

gz#14046

**Comment by sowmyav27** [comment] 2020-12-03 19:10
**Steps to reproduce (least amount of steps as possible):**

- Deploy a windows (1903) `Windows_Server-1903-English-Core-Base` nodes cluster - 1 etcd+control and 3 linux worker nodes and 3 windows worker nodes.
- Enable logging using fluentd on the cluster.
- rancher-logging-fluentd-windows workload fails to come 
- Error seen in pods: `CreateContainerError: Error response from daemon: invalid volume specification: 'c:/var/lib/rancher/rke/log:c:/var/lib/rancher/rke/log': invalid mount config for type "bind": bind source path does not exist: c:\var\lib\rancher\rke\log`


**Other details that may be helpful:**
- On windows 1909 cluster, it fails with error:
<img width="1286" alt="Screen Shot 2020-11-30 at 6 57 40 PM" src="https://user-images.githubusercontent.com/26032343/100680410-78f1c980-333f-11eb-87d1-7cedbc0ac936.png">
- Happens on 2.5.2 also

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): 2.5-head - commit id: `9ee39b9`
- Installation option (single install/HA): single



**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): windows custom
- Kubernetes version (use `kubectl version`):

```
1.19.4
```

**Comment by nickgerace** [comment] 2020-12-07 22:49
Official support matrix: https://kubernetes.io/docs/setup/production-environment/windows/intro-windows-in-kubernetes/

Kubernetes version | Windows Server LTSC releases | Windows Server SAC releases 
-- | -- | --
v1.14 | Windows Server 2019 | Windows Server ver 1809  
v1.15 | Windows Server 2019 | Windows Server ver 1809 
v1.16 | Windows Server 2019 | Windows Server ver 1809 
v1.17 | Windows Server 2019 | Windows Server ver 1809 
v1.18 | Windows Server 2019 | Windows Server ver 1809, Windows Server ver 1903, Windows Server ver 1909  
v1.19 | Windows Server 2019 | Windows Server ver 1909, Windows Server ver 2004

Consideration while triaging: "Windows containers with process isolation have strict compatibility rules, where the host OS version must match the container base image OS version. Once we support Windows containers with Hyper-V isolation in Kubernetes, the limitation and compatibility rules will change."

**Comment by nickgerace** [comment] 2020-12-14 20:34
Moving to review since waiting on re-review: https://github.com/rancher/configmap-reload/pull/3

Will move back to "Working" afterwards.

**Comment by nickgerace** [comment] 2020-12-18 19:05
Validating for Windows Server 2019 LTS (based on 1809, but not the same as 1809 SAC) _and_ 1909 SAC. 
We are validating these two releases since they are supported by MSFT.
https://docs.microsoft.com/en-us/windows-server/get-started/windows-server-release-info

**Comment by nickgerace** [comment] 2020-12-18 22:48
Moved to "To Test" early since 2.5 chart has priority. 2.4 backport is coming soon.

**Comment by sangeethah** [comment] 2020-12-18 23:26
@nickgerace Could you log an issue for 2.5.4 to track the merges done in 2.5  dev branches ?

**Comment by nickgerace** [comment] 2020-12-18 23:46
@sangeethah sure thing

**Comment by brianharwell** [comment] 2020-12-21 15:16
A solution for the path issue is described here: https://support.rancher.com/hc/en-us/requests/14046

**Comment by nickgerace** [comment] 2020-12-21 18:25
Thanks @brianharwell. Fortunately, we have this in our merged PRs and thank you for the idea. Looking forward to getting the new chart out.

**Comment by sadiapoddar** [comment] 2020-12-23 20:08
The fix on 2.4-head was verified.
Test1
         Created Two clusters one for window 1909 SAC and other for a windows 2019 LTSC. 
         Both cluster sepec
              -  3 etcd nodes
              -   1 control plane nodes
              -    3 ubuntu worker +worker(3 windows and 3ununtu)

        Created the cluster with Network configuration Flanned backend with VXLAN (overlay)
        Once the cluster up is running, enabled fluentd logging and noticed that all the logging containers were created successfully. 
        Created projects and worklaods
        Verifeid:
            1. logging containers got created successfully for both the windows and linux
           
        <img width="1338" alt="Screen Shot 2020-12-23 at 11 54 10 AM" src="https://user-images.githubusercontent.com/72409237/103032800-cfed5780-4515-11eb-95dc-a221a9509698.png">
        
           2. The fluentd log servers was receiving logs form cluster, and project
           3. version was Version 0.2.3

Test2
          The above configuration was repeated for both the window versions the following configuration variations. 
               
                  -  Network configuration:  Flannel Backend Host Gateway (L2bridge)
                  -  Logging:  Elasticsearch
          
          Created two clusters with the same spec in test1.
          Once the cluster up is running, enabled elasticsearch logging and noticed that all the logging containers were created successfully. 
          Created some projects and worklaods within the projects. 
          Verifeid:
             1. logging containers got created successfully for both the windows 
             2. Enabled cluster level logging and verified that elasticsearch server was recieving logs
             3.Enabled project level logging and verified that elasticsearch server was recieving workload related logs
            4. version was Version 0.2.3
Both elasticserarch and fluentd logging was working as expected on 2.4-head
![image](https://user-images.githubusercontent.com/72409237/103033551-87369e00-4517-11eb-8c2f-7b1f26f45914.png)

**Closed** 2020-12-23 20:17 UTC
Labels: [zube]: QA Working, area/windows, internal

**Comment by sadiapoddar** [comment] 2020-12-23 21:43
Rancher	v2.4-4531-head
User Interface	v2.4-dev
Helm	v2.16.8-rancher1
Machine	v0.15.0-rancher49
