### ISSUE TITLE
Nodes won't start in vSphere after v2.3.3 update

### ISSUE THREAD

**Issue by jtruxon** [rancher/rancher#24304] opened 2019-11-28 01:54 UTC
pulled a fresh copy of rancher/rancher:latest this evening, provisioned a cluster in our vSphere environment with an iso node template: "https://releases.rancher.com/os/latest/rancheros-vmware.iso".   The only customization of the template was an insecure registry entry.

Provisioning a new single-node cluster with this configuration resulted in error: 
>"Error creating machine: Error in driver during machine creation: vm '[vsphere folder path]/test1' not found"

the node vm is being created and loaded with the boot2docker iso, but it's not being turned on after vsphere performs its initial configuration steps.   this behavior is new, relative to the previous version, which I'd pulled earlier today - the same configuration earlier today resulted in a successful provisioning of the cluster.

**Comment by jtruxon** [comment] 2019-11-28 03:42
confirmed that pulling rancher/rancher:v2.3.2 returned my installation to a state where the cluster provisioning was successful

**Comment by bevank** [comment] 2019-11-29 02:16
same but only if I use a new template cloned from a template pre 2.3.3 upgrade

**Comment by luthermonson** [comment] 2019-12-18 20:51
@jtruxon could this be a dupe of this: https://github.com/rancher/rancher/issues/24315 ?

**Comment by jtruxon** [comment] 2019-12-20 14:48
@luthermonson  I think yes, based on a read-through -- will fire up an instance of 2.3.3 and confirm

thx!

**Comment by luthermonson** [comment] 2019-12-20 19:12
@jtruxon closing as a dupe of https://github.com/rancher/rancher/issues/24315

please reopen if you disagree.

**Closed by luthermonson** 2019-12-20 19:12 UTC
Labels: [zube]: Next Up
