### ISSUE TITLE
Upgrade K8s cluster fails after rancher upgrade when hostname is in Upper Case

### ISSUE THREAD

**Issue by david-maumenee** [rancher/rancher#16541] opened 2018-11-11 09:45 UTC
**What kind of request is this :** bug/enhancement

**Steps to reproduce :**
- init a Rancher 2.0.8 server (not HA)
- create a K8s cluster with all roles on single machine **with an upper case hostname** (work fine, Rancher v2.0.8 don't worry about hostname validation during cluster creation)
- upgrade Rancher from 2.0.8 to 2.1.1
- try to upgrade the K8s cluster from v1.11.2-rancher1-1 to v1.11.3-rancher1-1

**Result:**
Upgrade fail
```
2018/11/09 16:32:06 [ERROR] ClusterController c-lh9vx [cluster-provisioner-controller] failed with : 
Failed to validate cluster: Hostname_override [VERD897] for host (1) is not valid: 
[a DNS-1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', 
regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*')]
```
**Other details :**
On my ubuntu host, I change the hostname to make it complient with validation.
After that a try to validate again the upgrade but it doesn't solve the issues

I also tried to update the  hostnameOverride field via Rancher API but I am unable to do this neither on cluster resource or on node resource 

Is there a way to fix the situation ?

**Comment by superseb** [comment] 2018-11-11 10:30
Duplicate of https://github.com/rancher/rancher/issues/16294

**Closed by superseb** 2018-11-11 10:30 UTC

**Comment by david-maumenee** [comment] 2018-11-12 09:39
my issue is a Duplicate of #16508 not exactly of #16294.

The workaround for #16294 don't seem to apply in case of upgrade.

https://github.com/rancher/rancher/issues/16294#issuecomment-437814971

**Comment by jiaqiluo** [comment] 2018-11-15 17:14
### Validation 
**Rancher version**: v2.1.2-rc12
**Installation option**: single
**Step**: 
Step 1: created a Rancher 2.0.8 server
Step 2: added a custom cluster with all roles on single machine **with an upper case hostname**
  <img width="1692" alt="screenshot 4" src="https://user-images.githubusercontent.com/6218999/48568935-c5cfe800-e8bd-11e8-94c8-9ead703b7588.png">
  <img width="555" alt="screenshot 5" src="https://user-images.githubusercontent.com/6218999/48568941-c8cad880-e8bd-11e8-8957-f9a562ea6a39.png">

Step 3: upgraded Rancher from v2.0.8 to v2.1.2-rc12
<img width="1701" alt="screenshot 6" src="https://user-images.githubusercontent.com/6218999/48568961-d97b4e80-e8bd-11e8-9996-53b799ad60cc.png">

Step 4: upgraded the K8s cluster from v1.11.2-rancher1-1 to v1.11.3-rancher1-1
<img width="1719" alt="screenshot 7" src="https://user-images.githubusercontent.com/6218999/48569247-6aeac080-e8be-11e8-92fd-66eba34020d4.png">

Step 5: upgraded the K8s cluster from v1.11.3-rancher1-1 to v1.12.1-rancher1-1
<img width="1796" alt="screenshot 8" src="https://user-images.githubusercontent.com/6218999/48569501-29a6e080-e8bf-11e8-99ea-4284737a81c3.png">

**Result**:
Successfully updated and the cluster worked with no problem.

Bug fixed verified.

**Comment by david-maumenee** [comment] 2018-11-15 19:37
Thanks @jiaqiluo !
Great job !
