### ISSUE TITLE
Can't edit hosted cluster created from custom kontainer driver

### ISSUE THREAD

**Issue by janeczku** [rancher/rancher#18406] opened 2019-02-26 17:36 UTC
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
1. Create a custom cluster driver in the GUI Custom Drivers -> Cluster Drivers -> Add
2. Add any custome driver or use the following parametersr:
URL: https://github.com/barpilot/kontainer-engine-driver-aks2/releases/download/v0.0.0-associate/kontainer-engine-driver-aks2
UI URL: https://github.com/barpilot/ui-cluster-driver-aks2/releases/download/v0.0.0/component.js
3. Start creation of a new hosted AKS cluster using that driver
4. Check the Provider type of the new cluster under Global -> Clusters
5. Try editing the cluster (e.g. upgrade K8s version)

**Result:**
Cluster type is set to `imported`. Editing is not possible.

**Other details that may be helpful:**

<img width="1341" alt="screenshot 2019-02-26 at 18 34 12" src="https://user-images.githubusercontent.com/3813921/53434282-881f4700-39f6-11e9-88ba-a1e6e2772d7b.png">

```
"agentImage": "",
"aks2EngineConfig": {
"aadClientAppId": "",
"aadServerAppId": "",
"aadServerAppSecret": "",
"aadTenantId": "",
"adminUsername": "azureuser",
"agentDnsPrefix": "",
"agentOsdiskSize": 100,
"agentPoolName": "rancher",
"agentStorageProfile": "ManagedDisks",
"agentVmSize": "Standard_D2_v2",
"authBaseUrl": "https://login.microsoftonline.com/",
"baseUrl": "https://management.azure.com/",
"clientId": "cc388926-cfc1-4XXXXXXX",
"count": 3,
"(TRUNCATED)
"annotations": {
"authz.management.cattle.io/creator-role-bindings": "{\"created\":[\"cluster-owner\"],\"required\":[\"cluster-owner\"]}",
"lifecycle.cattle.io/create.cluster-agent-controller-cleanup": "true",
"lifecycle.cattle.io/create.cluster-scoped-gc": "true",
"lifecycle.cattle.io/create.mgmt-cluster-rbac-remove": "true"
},
"(TRUNCATED)
"type": "/v3/schemas/localClusterAuthEndpoint"
},
"type": "/v3/schemas/clusterSpec"
},
"authImage": "",
"baseType": "cluster",
"capabilities": {
"loadBalancerCapabilities": {
"enabled": true,
"healthCheckSupported": true,
"protocolsSupported": [ 2 items
"TCP",
"UDP"
],
"provider": "Azure L4 LB",
"type": "/v3/schemas/loadBalancerCapabilities"
},
(TRUNCATED)
"conditions": [ 10 items
{
(TRUNCATED),
"created": "2019-02-26T17:34:02Z",
"createdTS": 1551202442000,
(TRUNCATED)
"desiredAuthImage": "",
"dockerRootDir": "/var/lib/docker",
"driver": "aks2",
(TRUNCATED)
```

**Environment information**
- Rancher version: 2.2.0-rc2, alpha6
- Installation option (single install/HA): Standalone or HA

**Comment by westlywright** [comment] 2019-02-26 19:00
@cjellick this is a UI issue, its trying to load the `import` cluster component instead of the custom component.

**Comment by westlywright** [comment] 2019-02-27 18:24
@rancher/qa I've made updates to the google-gke-example branch for [ui-cluster-driver-skel](https://github.com/rancher/ui-cluster-driver-skel/tree/google-gke-example) that make reproducing this much easier. Github doesn't serve files with the correct headers so you have to jump through some hoops to get the repro working. Using the example branch to repro tests the same scenario as it wasn't an issue with this particular skel-driver code, it was all 3rd party drivers.

**Comment by davidnuzik** [comment] 2019-02-28 16:12
Note to self - waiting on backend cluster driver fix (gke example) so I can fully test and run test plan against custom kontainer driver again.

**Comment by davidnuzik** [comment] 2019-03-01 21:57
@westlywright 
I am not able to edit the cluster. I can say when I edit I am indeed not taken back to import I am taken back to the custom UI as expected. Perhaps this issue is not related but I cannot perform the actual Edit action and save. Unlike a GKE cluster I see that everything is editable but I tried to just edit the nodecount which I know is permitted and I get an HTTP 422 with this in the UI:

![image](https://user-images.githubusercontent.com/45179589/53668747-074c8f00-3c32-11e9-803c-da6f8d200103.png)

Maybe this is a backend issue? / Completely unrelated? Perhaps I can close the issue since I did indeed get back to the UI for edit instead of import?
```
2019/03/01 21:53:07 [INFO] kontainerdriver kd-sz448 listening on address 127.0.0.1:10135
2019/03/01 21:53:07 [WARNING] could not convert <nil> taints=<nil>
2019/03/01 21:53:07 [WARNING] could not convert <nil> locations=<nil>
2019/03/01 21:53:07 [WARNING] could not convert <nil> resourceLabels=<nil>
2019/03/01 21:53:07 [WARNING] could not convert <nil> labels=<nil>
2019/03/01 21:53:07 [INFO] kontainerdriver kd-sz448 stopped
2019/03/01 21:53:32 [ERROR] API error response 422 for PUT /v3/clusters/c-kwzqw?_replace=true. Cause: taints=NotNullable 422:
```

**Comment by westlywright** [comment] 2019-03-04 21:15
@davidnuzik I think it is a problem with the driver not the UI. I am seeing the same error and one with locations on occasion. If you watch the network log and look at the payload out and the response in you'll see `taints` is sent with an empty array and comes back from the api as null when the resource is saved. Then on edit it's failing because it's not-nullable in the driver. I don't know if this is a limitation of the dynamic schemas but when you look at `v3/schemas/exampleEngineConfig` I don't see those fields being set with non-nullable (if its not there its assumed false I believe) so the UI doesn't error out.

**Comment by davidnuzik** [comment] 2019-03-04 22:13
Version: Master 2.2 (3/4/19)
Confirmed UI fix. I tested with the google-gke-example https://github.com/rancher/kontainer-engine-driver-example/releases and with UI https://github.com/rancher/ui-cluster-driver-skel/tree/google-gke-example

When I create the cluster it no longer shows as imported, it will only briefly show this and it will then show as Provider type "Example"
![image](https://user-images.githubusercontent.com/45179589/53765855-6b6b8f00-3e8e-11e9-93a7-3b4830f1c78a.png)

When I edit, I am able to edit the cluster in the UI, rather than get the edit import screen.
![image](https://user-images.githubusercontent.com/45179589/53765888-850cd680-3e8e-11e9-933f-88c3808e968b.png)

I can submit the edit and the UI looks correct. As Wes mentioned the UI is sending everything correctly; thus I consider the issue is resolved. There is an unrelated backend issue with our test kontainer-driver or the API per Wes' comment above. I have opened an issue for this here: #18555 (Thanks Wes!)

**Closed by davidnuzik** 2019-03-04 22:13 UTC
Labels: area/kontainer-engine, area/ui, kind/bug-qa, status/ready-for-review, status/resolved, status/to-test, status/working, team/az
