### ISSUE TITLE
Exiting scheduler with error: Metadata watcher exited:

### ISSUE THREAD

**Issue by thebalaa** [rancher/rancher#7890] opened 2017-02-20 06:03 UTC
**Rancher Versions:**
Server: 1.4.1
healthcheck: v0.2.3
ipsec: net:holder / v0.8.7
network-services: v0.4.5
scheduler: v0.6.3

**Docker Version:**
1.12.6
**OS and where are the hosts located? (cloud, bare metal, etc):**
Rancher OS v0.8.0 / Virtual Hyper-V Windows 10 Pro Host
**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
Single node internal db
**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle
**Steps to Reproduce:**
After clean install of rancher server launch rancher-agent to same machine as rancher server
**Results:** 
Scheduler container continuously flip-flops between running and reinitializing state

Scheduler logs:
```
2/19/2017 9:54:22 PMtime="2017-02-20T05:54:22Z" level=info msg="Listening for health checks on 0.0.0.0:80/healthcheck"
2/19/2017 9:54:22 PMtime="2017-02-20T05:54:22Z" level=info msg="Connecting to cattle event stream."
2/19/2017 9:54:22 PMtime="2017-02-20T05:54:22Z" level=info msg="Subscribing to metadata changes."
2/19/2017 9:54:22 PMtime="2017-02-20T05:54:22Z" level=info msg="Adding resource pool [cpuReservation] with total 6000 and used 0 for host  7c2ccac0-3bed-4849-a09e-df8c3df34c0a"
2/19/2017 9:54:22 PMtime="2017-02-20T05:54:22Z" level=info msg="Adding resource pool [memoryReservation] with total 8363442176 and used 0 for host  7c2ccac0-3bed-4849-a09e-df8c3df34c0a"
2/19/2017 9:54:22 PMtime="2017-02-20T05:54:22Z" level=info msg="Adding resource pool [storageSize] with total 118392799 and used 0 for host  7c2ccac0-3bed-4849-a09e-df8c3df34c0a"
2/19/2017 9:54:22 PMtime="2017-02-20T05:54:22Z" level=info msg="Adding resource pool [instanceReservation] with total 1000000 and used 10 for host  7c2ccac0-3bed-4849-a09e-df8c3df34c0a"
2/19/2017 9:54:22 PMtime="2017-02-20T05:54:22Z" level=info msg="Adding resource pool [portReservation], ip set [0.0.0.0], ports map tcp map[0.0.0.0:map[8080:e23702a9-82c3-4c81-8235-ea99de6df795]], ports map udp map[0.0.0.0:map[]] for host 7c2ccac0-3bed-4849-a09e-df8c3df34c0a"
2/19/2017 9:54:22 PMtime="2017-02-20T05:54:22Z" level=info msg="Initializing event router" workerCount=100
2/19/2017 9:54:22 PMtime="2017-02-20T05:54:22Z" level=info msg="Connection established"
2/19/2017 9:54:22 PMtime="2017-02-20T05:54:22Z" level=info msg="Starting websocket pings"
2/19/2017 9:54:30 PMtime="2017-02-20T05:54:30Z" level=info msg="Received event: Name: scheduler.release, Event Id: 62c18d45-1bdb-446f-83d7-fee8dd1a64a4, ResourceId : 1iir9"
2/19/2017 9:54:30 PMtime="2017-02-20T05:54:30Z" level=info msg="Releasing [] for 7c2ccac0-3bed-4849-a09e-df8c3df34c0a"
2/19/2017 9:54:30 PMtime="2017-02-20T05:54:30Z" level=info msg="New pool amounts on host 7c2ccac0-3bed-4849-a09e-df8c3df34c0a:"
2/19/2017 9:54:30 PMtime="2017-02-20T05:54:30Z" level=info msg="Reply: Name: reply.7943640287351764028, PreviousIds: [62c18d45-1bdb-446f-83d7-fee8dd1a64a4], ResourceId: 1iir9, Data: map[]."
2/19/2017 9:55:20 PMtime="2017-02-20T05:55:20Z" level=error msg="Exiting scheduler with error: Metadata watcher exited: Get http://rancher-metadata/2016-07-29/version?wait=true&value=49-5cc6db6887beb3525be1bd696730805e&maxWait=5: net/http: request canceled"
2/19/2017 9:55:21 PMtime="2017-02-20T05:55:21Z" level=info msg="Listening for health checks on 0.0.0.0:80/healthcheck"
2/19/2017 9:54:22 PMtime="2017-02-20T05:54:22Z" level=info msg="Listening for health checks on 0.0.0.0:80/healthcheck"
2/19/2017 9:54:22 PMtime="2017-02-20T05:54:22Z" level=info msg="Connecting to cattle event stream."
2/19/2017 9:54:22 PMtime="2017-02-20T05:54:22Z" level=info msg="Subscribing to metadata changes."
2/19/2017 9:54:22 PMtime="2017-02-20T05:54:22Z" level=info msg="Adding resource pool [cpuReservation] with total 6000 and used 0 for host  7c2ccac0-3bed-4849-a09e-df8c3df34c0a"
2/19/2017 9:54:22 PMtime="2017-02-20T05:54:22Z" level=info msg="Adding resource pool [memoryReservation] with total 8363442176 and used 0 for host  7c2ccac0-3bed-4849-a09e-df8c3df34c0a"
2/19/2017 9:54:22 PMtime="2017-02-20T05:54:22Z" level=info msg="Adding resource pool [storageSize] with total 118392799 and used 0 for host  7c2ccac0-3bed-4849-a09e-df8c3df34c0a"
2/19/2017 9:54:22 PMtime="2017-02-20T05:54:22Z" level=info msg="Adding resource pool [instanceReservation] with total 1000000 and used 10 for host  7c2ccac0-3bed-4849-a09e-df8c3df34c0a"
2/19/2017 9:54:22 PMtime="2017-02-20T05:54:22Z" level=info msg="Adding resource pool [portReservation], ip set [0.0.0.0], ports map tcp map[0.0.0.0:map[8080:e23702a9-82c3-4c81-8235-ea99de6df795]], ports map udp map[0.0.0.0:map[]] for host 7c2ccac0-3bed-4849-a09e-df8c3df34c0a"
2/19/2017 9:54:22 PMtime="2017-02-20T05:54:22Z" level=info msg="Initializing event router" workerCount=100
2/19/2017 9:54:22 PMtime="2017-02-20T05:54:22Z" level=info msg="Connection established"
2/19/2017 9:54:22 PMtime="2017-02-20T05:54:22Z" level=info msg="Starting websocket pings"
2/19/2017 9:54:30 PMtime="2017-02-20T05:54:30Z" level=info msg="Received event: Name: scheduler.release, Event Id: 62c18d45-1bdb-446f-83d7-fee8dd1a64a4, ResourceId : 1iir9"
2/19/2017 9:54:30 PMtime="2017-02-20T05:54:30Z" level=info msg="Releasing [] for 7c2ccac0-3bed-4849-a09e-df8c3df34c0a"
2/19/2017 9:54:30 PMtime="2017-02-20T05:54:30Z" level=info msg="New pool amounts on host 7c2ccac0-3bed-4849-a09e-df8c3df34c0a:"
2/19/2017 9:54:30 PMtime="2017-02-20T05:54:30Z" level=info msg="Reply: Name: reply.7943640287351764028, PreviousIds: [62c18d45-1bdb-446f-83d7-fee8dd1a64a4], ResourceId: 1iir9, Data: map[]."
2/19/2017 9:55:20 PMtime="2017-02-20T05:55:20Z" level=error msg="Exiting scheduler with error: Metadata watcher exited: Get http://rancher-metadata/2016-07-29/version?wait=true&value=49-5cc6db6887beb3525be1bd696730805e&maxWait=5: net/http: request canceled"
2/19/2017 9:55:21 PMtime="2017-02-20T05:55:21Z" level=info msg="Listening for health checks on 0.0.0.0:80/healthcheck"
```

**Comment by bseng** [comment] 2017-02-21 03:39
+1

**Comment by etherai** [comment] 2017-02-21 23:23
This issue is blocking our evaluation of Rancher. We'd appreciate some direction on troubleshooting this issue. Thanks.

**Comment by cjellick** [comment] 2017-02-22 15:53
@bseng @etherai are you similarly running rancher/server and rancher/agent on the same host?
Just trying to find some commonality between your three setups.

**Comment by bseng** [comment] 2017-02-22 23:26
I'm running agent on the same server as the host.

I've tried the following

running Rancher HA, rancher url as internal ip and port 8080.
running Rancher standalone, rancher url as external ip and port 80, with advertising port flag.

both having the same issue.

thanks

**Comment by cjellick** [comment] 2017-02-23 17:22
@bseng are you similarly on a hyper-v host? Is there error message in scheduler exactly the same?
What version of rancher are you running?

**Comment by StrongMonkey** [comment] 2017-02-23 18:42
@cjellick I also saw this on QA's setup. Wondering if the rancher-metadata is not healthy at this time. Cause we are now using the OnchangeWithError(), any error from metadata would cause a restart on scheduler.

**Comment by bseng** [comment] 2017-02-23 23:29
@cjellick  my local environment is on hyper-v which I use rancherOS 0.8.0 and rancher 1.4.1 which I don't see the issue.

On production environment (centOS 7.2, docker 1.12.1, rancher HA 1.2.x with external mariadb cluster), I saw this issue when first upgrade to 1.3.4.

**Comment by cjellick** [comment] 2017-02-24 04:28
@bseng could you try exec into the scheduler container and doing either a `curl http://rancher-metadata` or `ping rancher-metadata`?

As @StrongMonkey suggested, maybe the issue is that scheduler cannot reach the metadata service.

**Comment by cj-anthony** [comment] 2017-02-24 04:52
Having the same issue here with one Docker server in Azure. Other servers in our HQ (Hyper-V) and Azure don't seem to be affected. Server is running Ubuntu 16.04.2 LTS.

Scheduler v0.6.3
Docker 1.13.1 (Unsupported)

Rancher Server is 1.4.1 and is hosted on Hyper-V in our HQ while the Docker Server is hosted in Azure AUS.

I've done both the tests that cjellick asked for:

`root@52b17ef15c9d:/# ping rancher-metadata
PING rancher-metadata.rancher.internal (169.254.169.250) 56(84) bytes of data.
64 bytes from 169.254.169.250: icmp_seq=1 ttl=63 time=0.056 ms
64 bytes from 169.254.169.250: icmp_seq=2 ttl=63 time=0.059 ms


root@52b17ef15c9d:/# curl http://rancher-metadata
2015-07-25
2015-12-19
2016-07-29
latest`

I'll update this post with more information as I collect it.

**Comment by bseng** [comment] 2017-02-24 06:45
hum I've restarted my rancherOS (0.8.0) vm on may machine and I'm having issues with meta-data, 
>2/24/2017 5:41:41 PM/rancher-entrypoint.sh: line 3: /usr/bin/update-rancher-ssl: No such file or directory
>2/24/2017 5:41:41 PM/rancher-entrypoint.sh: line 5: exec: start.sh: not found

and scheduler, healthcheck error
> timeout getting IP address.

ipsec 2nd sidekick is red too.

running rancher 1.3.3 fine before stopped and run 1.4.1

**Comment by cjellick** [comment] 2017-02-28 16:52
@StrongMonkey can you get a rancher/master setup working with an azure host to see if you can reproduce?

**Comment by StrongMonkey** [comment] 2017-02-28 16:54
@cjellick sure

**Comment by cj-anthony** [comment] 2017-02-28 21:11
Just an update, we did some test here to try and mitigate the issue and I have some second hand information that rancher performs normally prior to an apt-get upgrade on Ubuntu 16.0.4. We threw up a RHEL 7.2 server and have not experienced the problem yet.

**Comment by StrongMonkey** [comment] 2017-03-01 16:27
@sangeethah Can you get a setup from Azure to see if this one is fixed?

**Comment by tfiduccia** [comment] 2017-03-01 23:54
@StrongMonkey - Setup an environment with Azure and the scheduler loaded and working.  Was there something specific you wanted me to look at.

**Comment by StrongMonkey** [comment] 2017-03-02 00:17
@tfiduccia Thanks for testing that. It should fix the problem. I also tested that on Azure. Close this issue. This fix should be in 1.5.

**Closed by StrongMonkey** 2017-03-02 00:17 UTC
Labels: status/resolved, status/to-test

**Comment by calexandre** [comment] 2017-03-06 10:14
I'm also getting affected by this issue. Is it confirmed to be fixed in 1.5.0?
I'm running a rancher "farm" on multiple hosts in Azure. All of them with Ubuntu 16.04 LTS.

I had to stop the scheduler service, because it was just on restart loops...Just wondering, what is this service for?

**Rancher Versions:**
Server: 1.4.1
healthcheck: v0.2.3
ipsec: net:holder / v0.8.7
network-services: v0.4.5
scheduler: v0.6.3

**Comment by StrongMonkey** [comment] 2017-03-06 16:55
@calexandre It is fixed in 1.5. Please let us know if it is not fixed and feel free to reopen this ticket.

**Comment by calexandre** [comment] 2017-03-06 16:57
Thanks. I'm just waiting for a stable release...
Any chance that there will be a 1.4.2 ?

**Comment by deniseschannon** [comment] 2017-03-06 17:22
@calexandre We are not expecting to release a 1.4.2, but as 1.5 has been released, a stable version should be released within the next week or two. 

The scheduler from the catalog is primarily used for additional scheduling features, like resource based scheduling, special scheduling. Most of the core scheduling logic is embedded in Rancher, so you could not run this infrastructure stack.
