### ISSUE TITLE
Error getting container info

### ISSUE THREAD

**Issue by yuanzougaofei97** [rancher/rancher#3747] opened 2016-03-03 09:44 UTC
Rancher Version:
Rancher Release - v0.59.1 

Docker Version:
1.10.2

OS: 
centos7.1

Steps to Reproduce: 
Click on the container to view information for cpu , memory,network,storage

Results: 
page show Connecting...

Expected:

log
time="2016-03-03T10:26:50Z" level="error" msg="Error getting container info." error="request \"http://127.0.0.1:9344/api/v1.3/containers/system.slice/docker-87aaf750a3137041411eb607042d7a2270018191e2158614866adf3c55648065.scope\" failed with error: \"failed to get container \\\"/system.slice/docker-87aaf750a3137041411eb607042d7a2270018191e2158614866adf3c55648065.scope\\\" with error: unknown container \\\"/system.slice/docker-87aaf750a3137041411eb607042d7a2270018191e2158614866adf3c55648065.scope\\\"\"" id="87aaf750a3137041411eb607042d7a2270018191e2158614866adf3c55648065

**Comment by deniseschannon** [comment] 2016-03-03 14:46
Duplicate of https://github.com/rancher/rancher/issues/3615

**Closed by deniseschannon** 2016-03-03 14:46 UTC
