### ISSUE TITLE
Error in networking agent

### ISSUE THREAD

**Issue by wesleylancel** [rancher/rancher#2024] opened 2015-09-11 08:59 UTC
I'm having issues with starting containers from the UI. The networking agent seems to keep crashing. Some logs:

```
9/11/2015 10:57:51 AM[[[scripts.sh:19] '[' -e /.dockerenv ']'
9/11/2015 10:57:51 AM[[[scripts.sh:20] cat /proc/1/environ
9/11/2015 10:57:51 AM[[[scripts.sh:20] xargs -0 '-I{}' echo export '"{}"'
9/11/2015 10:57:51 AM[[[scripts.sh:20] grep CATTLE_
9/11/2015 10:57:51 AM[[scripts.sh:27] eval export '"CATTLE_CONFIG_URL=http://playground:8080/v1"' export '"CATTLE_AGENT_INSTANCE_AUTH=Basic' 'OUQyOTM0MkU0RjQyMjdBNUQyOEU6eGZ2d2llOFV4SGE3eUVUMzNaS1AyZFRIOEhxMnFoWXNwOTNYaERkdw=="' export '"CATTLE_HOME=/var/lib/cattle"'
9/11/2015 10:57:51 AM[[[scripts.sh:27] export CATTLE_CONFIG_URL=http://playground:8080/v1 export 'CATTLE_AGENT_INSTANCE_AUTH=Basic OUQyOTM0MkU0RjQyMjdBNUQyOEU6eGZ2d2llOFV4SGE3eUVUMzNaS1AyZFRIOEhxMnFoWXNwOTNYaERkdw==' export CATTLE_HOME=/var/lib/cattle
9/11/2015 10:57:51 AM[[[scripts.sh:27] CATTLE_CONFIG_URL=http://playground:8080/v1
9/11/2015 10:57:51 AM[[[scripts.sh:27] CATTLE_AGENT_INSTANCE_AUTH='Basic OUQyOTM0MkU0RjQyMjdBNUQyOEU6eGZ2d2llOFV4SGE3eUVUMzNaS1AyZFRIOEhxMnFoWXNwOTNYaERkdw=='
9/11/2015 10:57:51 AM[[[scripts.sh:27] CATTLE_HOME=/var/lib/cattle
9/11/2015 10:57:51 AM[[scripts.sh:199] script_env
9/11/2015 10:57:51 AM[[scripts.sh:123] '[' -n http://playground:8080/v1 ']'
9/11/2015 10:57:51 AM[[scripts.sh:124] return
9/11/2015 10:57:51 AM[[scripts.sh:201] export CATTLE_HOME=/var/lib/cattle
9/11/2015 10:57:51 AM[[scripts.sh:201] CATTLE_HOME=/var/lib/cattle
9/11/2015 10:57:51 AM[[scripts.sh:202] export CATTLE_CONFIG_URL=http://playground:8080/v1
9/11/2015 10:57:51 AM[[scripts.sh:202] CATTLE_CONFIG_URL=http://playground:8080/v1
9/11/2015 10:57:51 AM[[scripts.sh:203] export CATTLE_STORAGE_URL=
9/11/2015 10:57:51 AM[[scripts.sh:203] CATTLE_STORAGE_URL=
9/11/2015 10:57:51 AM[config.sh:18] trap cleanup EXIT
9/11/2015 10:57:51 AM[config.sh:20] LOCK_DIR=/var/lib/cattle/locks
9/11/2015 10:57:51 AM[config.sh:21] LOCK=/var/lib/cattle/locks/config.lock
9/11/2015 10:57:51 AM[config.sh:22] DOWNLOAD=/var/lib/cattle/download
9/11/2015 10:57:51 AM[config.sh:23] UPTODATE=false
9/11/2015 10:57:51 AM[config.sh:25] URL=http://playground:8080/v1
9/11/2015 10:57:51 AM[config.sh:26] AUTH=:
9/11/2015 10:57:51 AM[config.sh:27] URL_SUFFIX=/configcontent/
9/11/2015 10:57:51 AM[config.sh:29] '[' '!' -x /var/lib/cattle/config.sh ']'
9/11/2015 10:57:51 AM[config.sh:33] '[' '!' -d /var/lib/cattle/locks ']'
9/11/2015 10:57:51 AM[config.sh:37] '[' true '!=' true ']'
9/11/2015 10:57:51 AM[config.sh:52] '[' /var/lib/cattle/locks/config.lock '!=' /var/lib/cattle/locks/config.lock ']'
9/11/2015 10:57:51 AM[config.sh:232] mkdir -p /var/lib/cattle
9/11/2015 10:57:51 AM[config.sh:233] mkdir -p /var/lib/cattle/download
9/11/2015 10:57:51 AM[config.sh:235] opts=()
9/11/2015 10:57:51 AM[config.sh:236] '[' 2 -gt 0 ']'
9/11/2015 10:57:51 AM[config.sh:237] case $1 in
9/11/2015 10:57:51 AM[config.sh:239] FORCE=true
9/11/2015 10:57:51 AM[config.sh:271] shift 1
9/11/2015 10:57:51 AM[config.sh:236] '[' 1 -gt 0 ']'
9/11/2015 10:57:51 AM[config.sh:237] case $1 in
9/11/2015 10:57:51 AM[config.sh:260] info Updating hosts
9/11/2015 10:57:51 AM[scripts.sh:33] echo INFO: Updating hosts
9/11/2015 10:57:51 AM[config.sh:261] UPTODATE=false
9/11/2015 10:57:51 AM[config.sh:262] download hosts
9/11/2015 10:57:51 AM[config.sh:82] cleanup
9/11/2015 10:57:51 AM[config.sh:9] EXIT=0
9/11/2015 10:57:51 AM[config.sh:11] '[' -e '' ']'
9/11/2015 10:57:51 AM[config.sh:15] return 0
9/11/2015 10:57:51 AMINFO: Updating hosts
9/11/2015 10:57:51 AM[[config.sh:84] mktemp -d /var/lib/cattle/download.XXXXXXX
9/11/2015 10:57:51 AM[config.sh:84] DOWNLOAD_TEMP=/var/lib/cattle/download.STbBUiy
9/11/2015 10:57:51 AM[config.sh:86] '[' -z http://playground:8080/v1 ']'
9/11/2015 10:57:51 AM[config.sh:86] '[' -z : ']'
9/11/2015 10:57:51 AM[config.sh:92] local name=hosts
9/11/2015 10:57:51 AM[config.sh:93] local current
9/11/2015 10:57:51 AM[config.sh:94] local archive_version
9/11/2015 10:57:51 AM[config.sh:96] purge_old /var/lib/cattle/download/hosts
9/11/2015 10:57:51 AM[config.sh:63] local exclude=current
9/11/2015 10:57:51 AM[config.sh:64] local dir=/var/lib/cattle/download/hosts
9/11/2015 10:57:51 AM[config.sh:66] '[' '!' -d /var/lib/cattle/download/hosts ']'
9/11/2015 10:57:51 AM[config.sh:67] return 0
9/11/2015 10:57:51 AM[config.sh:98] '[' true '!=' true ']'
9/11/2015 10:57:51 AM[config.sh:102] DOWNLOAD_URL=http://playground:8080/v1//configcontent//hosts
9/11/2015 10:57:51 AM[config.sh:104] local get_opts
9/11/2015 10:57:51 AM[config.sh:105] local archive_version
9/11/2015 10:57:51 AM[config.sh:106] '[' -n '' ']'
9/11/2015 10:57:51 AM[config.sh:118] info Downloading http://playground:8080/v1//configcontent//hosts current=
9/11/2015 10:57:51 AM[scripts.sh:33] echo INFO: Downloading http://playground:8080/v1//configcontent//hosts current=
9/11/2015 10:57:51 AM[config.sh:120] get 'http://playground:8080/v1//configcontent//hosts?current='
9/11/2015 10:57:51 AM[scripts.sh:57] '[' 'http://playground:8080/v1//configcontent//hosts?current=' = --no-auth ']'
9/11/2015 10:57:51 AM[scripts.sh:61] call_curl -L 'http://playground:8080/v1//configcontent//hosts?current='
9/11/2015 10:57:51 AM[scripts.sh:43] local 'curl=curl -s --connect-timeout 20'
9/11/2015 10:57:51 AM[scripts.sh:44] '[' '' = false ']'
9/11/2015 10:57:51 AM[scripts.sh:46] '[' -n 'Basic OUQyOTM0MkU0RjQyMjdBNUQyOEU6eGZ2d2llOFV4SGE3eUVUMzNaS1AyZFRIOEhxMnFoWXNwOTNYaERkdw==' ']'
9/11/2015 10:57:51 AM[scripts.sh:47] curl -s --connect-timeout 20 -H 'Authorization: Basic OUQyOTM0MkU0RjQyMjdBNUQyOEU6eGZ2d2llOFV4SGE3eUVUMzNaS1AyZFRIOEhxMnFoWXNwOTNYaERkdw==' -L 'http://playground:8080/v1//configcontent//hosts?current='
9/11/2015 10:57:51 AMINFO: Downloading http://playground:8080/v1//configcontent//hosts current=
9/11/2015 10:57:51 AM[[config.sh:121] cat /var/lib/cattle/download.STbBUiy/download
9/11/2015 10:57:51 AM[[config.sh:121] head -n1
9/11/2015 10:57:51 AM[config.sh:121] HEADER='���
 �Om7��7��'\''('
9/11/2015 10:57:51 AM[config.sh:122] [[ ���
 �Om7��7��'( =~ version:* ]]
9/11/2015 10:57:51 AM[config.sh:126] tar xzf /var/lib/cattle/download.STbBUiy/download -C /var/lib/cattle/download.STbBUiy
9/11/2015 10:57:51 AM[config.sh:128] rm /var/lib/cattle/download.STbBUiy/download
9/11/2015 10:57:51 AM[[[config.sh:130] ls -1 /var/lib/cattle/download.STbBUiy
9/11/2015 10:57:51 AM[[config.sh:130] basename
9/11/2015 10:57:51 AMbasename: missing operand
9/11/2015 10:57:51 AMTry 'basename --help' for more information.
9/11/2015 10:57:51 AM[config.sh:130] local dir=
9/11/2015 10:57:51 AM[config.sh:131] '[' '!' -e /var/lib/cattle/download.STbBUiy/ ']'
9/11/2015 10:57:51 AM[config.sh:138] cd /var/lib/cattle/download.STbBUiy
9/11/2015 10:57:51 AM[config.sh:140] '[' '!' -e /SHA1SUMSSUM ']'
9/11/2015 10:57:51 AM[config.sh:141] error 'Missing SHA1SUMS files, invalid download'
9/11/2015 10:57:51 AM[scripts.sh:38] echo ERROR: 'Missing SHA1SUMS files, invalid download'
9/11/2015 10:57:51 AMERROR: Missing SHA1SUMS files, invalid download
9/11/2015 10:57:51 AM[config.sh:142] exit 1
9/11/2015 10:57:51 AM[config.sh:1] cleanup
9/11/2015 10:57:51 AM[config.sh:9] EXIT=1
9/11/2015 10:57:51 AM[config.sh:11] '[' -e /var/lib/cattle/download.STbBUiy ']'
9/11/2015 10:57:51 AM[config.sh:12] rm -rf /var/lib/cattle/download.STbBUiy
9/11/2015 10:57:51 AM[config.sh:15] return 1
9/11/2015 10:57:51 AM
The system is going down NOW!
9/11/2015 10:57:51 AM
Sent SIGTERM to all processes
9/11/2015 10:57:52 AM
Sent SIGKILL to all processes
9/11/2015 10:57:52 AM
Requesting system reboot
```

**Comment by deniseschannon** [comment] 2015-09-11 16:17
Can you provide more details?

Rancher version (click on upper lefthand cow)
Docker version on host
Any steps taken on host before network agent had these issues?
Can you do a `docker ps` on the host? Is docker still working properly?

**Comment by wesleylancel** [comment] 2015-09-11 16:41
I don't have the exact versions at hand seeing I can't exact the server from remote, but it's the latest Docker and the Rancher images we're pulled today.

I created the services through `rancher-compose create` and then tried to start one through the web UI. Docker was still function correctly seeing the server runs on the same Docker.

**Comment by lkm** [comment] 2015-09-15 10:12
I'm experiencing the exact same problem when creating a new DigitalOcean host.

Rancher	v0.37.0
Cattle	v0.91.0
User Interface	v0.47.0

DigitalOcean host is running Docker 1.8.2

I've been using Rancher since v16 or so, and it's been upgraded quite a few times.

**Comment by deniseschannon** [comment] 2015-09-17 05:28
@lkm If you have a setup that has been upgraded a lot, the networking agent is a component that doesn't automatically get upgraded (like rancher agents). in v0.37.0, the most recent network agent is v0.4.0. If you have other hosts running older versions, I wonder if there is a compatibility problem. 

To get the latest one, I believe you could just stop and remove the networking agent from the UI. That will cause a new one to spin up, which would pull the most recent image.

**Comment by deniseschannon** [comment] 2015-09-17 05:31
@wesleylancel Is your an upgraded setup? Or a fresh install? If upgraded, what version?

Also, what is your docker-compose file? There was an issue with rancher-compose and using links and the sidekick label that just got fixed. That woudl cause services to be stuck in networking. 

We released a v0.37.1 to fix it.

**Comment by lkm** [comment] 2015-09-17 08:25
@deniseschannon Thank you for the quick answer. I've tried upgrading to v0.37.1, and remove one of the network agents on the old hosts, this causes the new agent (rancher/agent-instance:v0.4.1) to enter an eternal reboot loop sending this to the logs: 

```
9/17/2015 9:17:00 AM[[config.sh:121] head -n1
9/17/2015 9:17:00 AM[config.sh:121] HEADER='���
 �Om7��7��'\''('
9/17/2015 9:17:00 AM[config.sh:122] [[ ���
 �Om7��7��'( =~ version:* ]]
9/17/2015 9:17:00 AM[config.sh:126] tar xzf /var/lib/cattle/download.Zlw9IIu/download -C /var/lib/cattle/download.Zlw9IIu
9/17/2015 9:17:00 AM[config.sh:128] rm /var/lib/cattle/download.Zlw9IIu/download
9/17/2015 9:17:00 AM[[[config.sh:130] ls -1 /var/lib/cattle/download.Zlw9IIu
9/17/2015 9:17:00 AM[[config.sh:130] basename
9/17/2015 9:17:00 AMbasename: missing operand
9/17/2015 9:17:00 AMTry 'basename --help' for more information.
9/17/2015 9:17:00 AM[config.sh:130] local dir=
9/17/2015 9:17:00 AM[config.sh:131] '[' '!' -e /var/lib/cattle/download.Zlw9IIu/ ']'
9/17/2015 9:17:00 AM[config.sh:138] cd /var/lib/cattle/download.Zlw9IIu
9/17/2015 9:17:00 AM[config.sh:140] '[' '!' -e /SHA1SUMSSUM ']'
9/17/2015 9:17:00 AM[config.sh:141] error 'Missing SHA1SUMS files, invalid download'
9/17/2015 9:17:00 AM[scripts.sh:24] echo ERROR: 'Missing SHA1SUMS files, invalid download'
9/17/2015 9:17:00 AMERROR: Missing SHA1SUMS files, invalid download
9/17/2015 9:17:00 AM[config.sh:142] exit 1
9/17/2015 9:17:00 AM[config.sh:1] cleanup
9/17/2015 9:17:00 AM[config.sh:9] EXIT=1
9/17/2015 9:17:00 AM[config.sh:11] '[' -e /var/lib/cattle/download.Zlw9IIu ']'
9/17/2015 9:17:00 AM[config.sh:12] rm -rf /var/lib/cattle/download.Zlw9IIu
9/17/2015 9:17:00 AM[config.sh:15] return 1
```

And this remains in the rancher/server output logs:

```
2015-09-17 08:05:45,180 ERROR [:] [] [] [] [cutorService-38] [.p.c.v.i.ConfigItemStatusManagerImpl] Failed null, exit code [1] output [INFO: Updating hosts
INFO: Downloading http://rancher.bookbooncloud.com:8080/v1//configcontent//hosts current=hosts-21521-256d5e84d0d14b6fafb7adee4ecf4bbd598caffc2d2810fab610f75a277ab696
basename: missing operand
Try 'basename --help' for more information.
ERROR: Missing SHA1SUMS files, invalid download
] 
```

It also has the unfortunate consequence that mysql bin log get filled with updates to process_instance, it looks like. I my case my binlogs are 6 GB over 5 days.

**Comment by lkm** [comment] 2015-09-18 11:00
@wesleylancel Is there anything I can try in the interim? It seems the api endpoint `/v1/configcontent/hosts` is sitting out an empty though valid gzip and that that is unexpected.  

It's all pretty broken here and the database filling up the disk with junk. Any help would be appreciated.

**Comment by lkm** [comment] 2015-09-18 12:24
Sorry to be banging on about this, here the full  *more revealing* rancher/server log:

```
2015-09-18 11:48:58,384 ERROR [:] [] [] [] [qtp24497024-480] [i.g.i.g.r.handler.ExceptionHandler  ] Exception in API for request [io.github.ibuildthecloud.gdapi.request.ApiRequest@7614de68] java.lang.NullPointerException: null
	at io.cattle.platform.configitem.context.dao.impl.DnsInfoDaoImpl.getHostContainerIpData(DnsInfoDaoImpl.java:609) ~[cattle-config-item-server-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.configitem.context.dao.impl.DnsInfoDaoImpl.getInstanceWithHostNetworkingToIpMap(DnsInfoDaoImpl.java:585) ~[cattle-config-item-server-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.configitem.context.dao.impl.DnsInfoDaoImpl.getServiceHostDnsData(DnsInfoDaoImpl.java:136) ~[cattle-config-item-server-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.configitem.context.impl.DnsInfoFactory.populateContext(DnsInfoFactory.java:41) ~[cattle-config-item-server-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.configitem.context.impl.AbstractAgentBaseContextFactory.populateContext(AbstractAgentBaseContextFactory.java:69) ~[cattle-config-item-server-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.configitem.server.model.impl.AbstractArchiveBasedConfigItem.handleRequest(AbstractArchiveBasedConfigItem.java:56) ~[cattle-config-item-server-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.configitem.server.impl.ConfigItemServerImpl.handleDownload(ConfigItemServerImpl.java:97) ~[cattle-config-item-server-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.configitem.server.impl.ConfigItemServerImpl.handleRequest(ConfigItemServerImpl.java:40) ~[cattle-config-item-server-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.configitem.api.manager.ConfigContentManager.handle(ConfigContentManager.java:80) ~[cattle-config-item-api-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.configitem.api.manager.ConfigContentManager.getByIdInternal(ConfigContentManager.java:49) ~[cattle-config-item-api-0.5.0-SNAPSHOT.jar:na]
	at io.github.ibuildthecloud.gdapi.request.resource.impl.AbstractBaseResourceManager.getById(AbstractBaseResourceManager.java:61) ~[cattle-framework-java-server-0.5.0-SNAPSHOT.jar:na]
	at io.github.ibuildthecloud.gdapi.request.handler.ResourceManagerRequestHandler.generate(ResourceManagerRequestHandler.java:49) ~[cattle-framework-java-server-0.5.0-SNAPSHOT.jar:na]
	at io.github.ibuildthecloud.gdapi.request.handler.AbstractResponseGenerator.handle(AbstractResponseGenerator.java:14) ~[cattle-framework-java-server-0.5.0-SNAPSHOT.jar:na]
	at io.github.ibuildthecloud.gdapi.request.handler.write.DefaultReadWriteApiDelegate.handle(DefaultReadWriteApiDelegate.java:27) ~[cattle-framework-java-server-0.5.0-SNAPSHOT.jar:na]
	at io.github.ibuildthecloud.gdapi.request.handler.write.DefaultReadWriteApiDelegate.read(DefaultReadWriteApiDelegate.java:17) ~[cattle-framework-java-server-0.5.0-SNAPSHOT.jar:na]
	at sun.reflect.GeneratedMethodAccessor418.invoke(Unknown Source) ~[na:na]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.7.0_79]
	at java.lang.reflect.Method.invoke(Method.java:606) ~[na:1.7.0_79]
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:317) ~[spring-aop-3.2.5.RELEASE.jar:3.2.5.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:183) ~[spring-aop-3.2.5.RELEASE.jar:3.2.5.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:150) ~[spring-aop-3.2.5.RELEASE.jar:3.2.5.RELEASE]
	at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:96) ~[spring-tx-3.2.4.RELEASE.jar:3.2.4.RELEASE]
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:260) ~[spring-tx-3.2.4.RELEASE.jar:3.2.4.RELEASE]
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:94) ~[spring-tx-3.2.4.RELEASE.jar:3.2.4.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172) ~[spring-aop-3.2.5.RELEASE.jar:3.2.5.RELEASE]
	at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:91) ~[spring-aop-3.2.5.RELEASE.jar:3.2.5.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172) ~[spring-aop-3.2.5.RELEASE.jar:3.2.5.RELEASE]
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:204) ~[spring-aop-3.2.5.RELEASE.jar:3.2.5.RELEASE]
	at com.sun.proxy.$Proxy42.read(Unknown Source) ~[na:na]
	at io.github.ibuildthecloud.gdapi.request.handler.write.ReadWriteApiHandler.handle(ReadWriteApiHandler.java:21) ~[cattle-framework-java-server-0.5.0-SNAPSHOT.jar:na]
	at io.github.ibuildthecloud.gdapi.servlet.ApiRequestFilterDelegate.doFilter(ApiRequestFilterDelegate.java:86) ~[cattle-framework-java-server-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.api.servlet.ApiRequestFilter$1.runInContext(ApiRequestFilter.java:60) [cattle-framework-api-0.5.0-SNAPSHOT.jar:na]
	at org.apache.cloudstack.managed.context.ManagedContextRunnable$1.run(ManagedContextRunnable.java:49) [cattle-framework-managed-context-0.5.0-SNAPSHOT.jar:na]
	at org.apache.cloudstack.managed.context.impl.DefaultManagedContext$1.call(DefaultManagedContext.java:55) [cattle-framework-managed-context-0.5.0-SNAPSHOT.jar:na]
	at org.apache.cloudstack.managed.context.impl.DefaultManagedContext.callWithContext(DefaultManagedContext.java:108) [cattle-framework-managed-context-0.5.0-SNAPSHOT.jar:na]
	at org.apache.cloudstack.managed.context.impl.DefaultManagedContext.runWithContext(DefaultManagedContext.java:52) [cattle-framework-managed-context-0.5.0-SNAPSHOT.jar:na]
	at org.apache.cloudstack.managed.context.ManagedContextRunnable.run(ManagedContextRunnable.java:46) [cattle-framework-managed-context-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.api.servlet.ApiRequestFilter.doFilter(ApiRequestFilter.java:53) [cattle-framework-api-0.5.0-SNAPSHOT.jar:na]
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652) [jetty-servlet-9.2.11.v20150529.jar:9.2.11.v20150529]
	at org.eclipse.jetty.servlets.UserAgentFilter.doFilter(UserAgentFilter.java:83) [jetty-servlets-9.2.11.v20150529.jar:9.2.11.v20150529]
	at org.eclipse.jetty.servlets.GzipFilter.doFilter(GzipFilter.java:364) [jetty-servlets-9.2.11.v20150529.jar:9.2.11.v20150529]
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652) [jetty-servlet-9.2.11.v20150529.jar:9.2.11.v20150529]
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:585) [jetty-servlet-9.2.11.v20150529.jar:9.2.11.v20150529]
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143) [jetty-server-9.2.11.v20150529.jar:9.2.11.v20150529]
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:577) [jetty-security-9.2.11.v20150529.jar:9.2.11.v20150529]
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:223) [jetty-server-9.2.11.v20150529.jar:9.2.11.v20150529]
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1127) [jetty-server-9.2.11.v20150529.jar:9.2.11.v20150529]
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:515) [jetty-servlet-9.2.11.v20150529.jar:9.2.11.v20150529]
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185) [jetty-server-9.2.11.v20150529.jar:9.2.11.v20150529]
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1061) [jetty-server-9.2.11.v20150529.jar:9.2.11.v20150529]
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141) [jetty-server-9.2.11.v20150529.jar:9.2.11.v20150529]
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97) [jetty-server-9.2.11.v20150529.jar:9.2.11.v20150529]
	at org.eclipse.jetty.server.Server.handle(Server.java:499) [jetty-server-9.2.11.v20150529.jar:9.2.11.v20150529]
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:310) [jetty-server-9.2.11.v20150529.jar:9.2.11.v20150529]
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:257) [jetty-server-9.2.11.v20150529.jar:9.2.11.v20150529]
	at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:540) [jetty-io-9.2.11.v20150529.jar:9.2.11.v20150529]
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635) [jetty-util-9.2.11.v20150529.jar:9.2.11.v20150529]
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555) [jetty-util-9.2.11.v20150529.jar:9.2.11.v20150529]
	at java.lang.Thread.run(Thread.java:745) [na:1.7.0_79]

2015-09-18 11:48:58,415 ERROR [:] [] [] [] [utorService-360] [.p.c.v.i.ConfigItemStatusManagerImpl] Failed null, exit code [1] output [INFO: Updating hosts
INFO: Downloading http://rancher.bookbooncloud.com:8080/v1//configcontent//hosts current=hosts-22160-256d5e84d0d14b6fafb7adee4ecf4bbd598caffc2d2810fab610f75a277ab696
basename: missing operand
Try 'basename --help' for more information.
ERROR: Missing SHA1SUMS files, invalid download
] 
```

Could be it related to this PR: https://github.com/rancher/cattle/pull/820

**Comment by ibuildthecloud** [comment] 2015-09-18 13:53
Thanks, that error message is quite useful.  I'll look into that today.

**Comment by lkm** [comment] 2015-09-19 13:04
Cheers @ibuildthecloud! I can send you a DB dump if that'll make it easier to debug?

**Comment by alena1108** [comment] 2015-09-22 20:09
@lkm could you please share the db dump + mention the id of the host(s) hitting the problem?

**Comment by lkm** [comment] 2015-09-22 20:48
@alena1108 Thank you. I've sent you an email to avoid exposing all sorts of interesting stuff here.

**Comment by alena1108** [comment] 2015-09-22 21:13
@ibuildthecloud one of the accounts in the system is missing networks

1) All instances are owned by account_id=5

```
mysql> select account_id from instance where removed is null group by account_id;
+------------+
| account_id |
+------------+
|          5 |
+------------+
1 row in set (0.00 sec)
```

2) There are no networks for account_id=5:

```
mysql> select account_id, kind, removed from network;
+------------+-----------------+---------+
| account_id | kind            | removed |
+------------+-----------------+---------+
|          2 | network         | NULL    |
|          2 | hostOnlyNetwork | NULL    |
|         87 | hostOnlyNetwork | NULL    |
|         87 | dockerHost      | NULL    |
|         87 | dockerNone      | NULL    |
|         87 | dockerContainer | NULL    |
|         87 | dockerBridge    | NULL    |
+------------+-----------------+---------+
```

3) Account id=5 was created some time in may:

mysql> select id, name, created from account where id=5;
+----+------------+---------------------+
| id | name       | created             |
+----+------------+---------------------+
|  5 | production | 2015-05-19 14:13:55 |
+----+------------+---------------------+
1 row in set (0.00 sec)


The commit introducing docker host/none/container network modes (e383f962feac7b2660957d427ab7ec654bef97db) was merged in 2015-05-17, so most likely account in @lkm system was created before this check came in.

Now there are couple of ways to fix things:

* handle missing networks creation for the account of a type "project" as a part of the DB upgrade.
* fix DnsInfoDao code to skip host network programming when the hostNetwork can't be located for the account. This would be an easiest fix, but I wonder if missing networks can cause any other issues besides dns programming, and whether the previous fix solution would be necessary if so. Also if account_id=5 has networks missing, you won't be able to start instances with network model other than docker native/managed. @ibuildthecloud let me know what you think.

**Comment by alena1108** [comment] 2015-09-23 17:35
@sangeethah we have to run the upgrade test to verify this bug. The initial version should be the one from the first week of May. Deploy a couple of instances on the managed network, then upgrade to the latest. Try to restart existing instance, and deploy a new one.

**Comment by deniseschannon** [comment] 2015-09-24 21:52
Verified with v0.39.0-rc1.

Reproduced with v0.38.1 and was able to upgrade from using the same old version to v0.39.0-rc1 with no issues.

v0.19.2 -> v0.38.1 (broken)
same v0.19.2 -> v0.39.0-rc1 works

**Closed by deniseschannon** 2015-09-24 21:52 UTC
Labels: kind/bug, status/blocker, status/to-test
