### ISSUE TITLE
lb-controller support for scheduling labels

### ISSUE THREAD

**Issue by fabionitto** [rancher/rancher#6155] opened 2016-10-05 14:26 UTC
**Rancher Version: v1.1.4**  

**Docker Version: v1.10.3**

**Using CoreOS 1122.2.0**

**Environment Type: Kubernetes**

I couldn't figure out how to automatically schedule loadbalancers pods on selected nodes using Ingress and lb-controller.  Am I missing something?

There could be a way to utilize annotations to manage this. Something like:

```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: tls-loadbalancer
  annotations:
    host_label: "key=value"
```

That way it would be possible to fire up LBs on specific hosts using rancher labels.

**Comment by alena1108** [comment] 2016-11-23 18:01
Duplicate of https://github.com/rancher/rancher/issues/4849

**Closed by alena1108** 2016-11-23 18:01 UTC
Labels: area/kubernetes, kind/feature
