### ISSUE TITLE
Project level members view no longer displays Members from GitHub auth

### ISSUE THREAD

**Issue by ChrisMcKee** [rancher/rancher#21526] opened 2019-07-15 12:12 UTC
Component | Version
-- | --
Rancher | v2.2.4
User Interface | v2.2.70
Helm | v2.10.0-rancher11
Machine | v0.15.0-rancher8-1

At a cluster level viewing members I can see the teams I've added (from github). Which is correct behaviour.

At a Project -> Members level I can only see local users. (logged in via github / admin user)

I'd assumed this was a glitch affecting our UK setup but it appears to have affected multiple separate rancher clusters.

**Comment by superseb** [comment] 2019-07-15 17:18
This sounds as a duplicate of https://github.com/rancher/rancher/issues/20760, let me know if it isn't.

**Closed by superseb** 2019-07-15 17:18 UTC
