### ISSUE TITLE
Update CIS Profiles for RKE2

### ISSUE THREAD

**Issue by nwmac** [rancher/rancher#40435] opened 2023-01-27 14:02 UTC
On the custom cluster creation page for RKE2, we need to update the list of CIS Profiles and add some logic.

- Remove CIS Profile 1.5
- Add CIS Profile 1.23
- Add logic so CIS Profile 1.6 is shown only when the Kubernetes version is 1.21-1.24 (inclusive)
- Add logic so CIS Profile 1.23 is shown when the Kubernetes version is >= 1.25

## Misc
Parent Issue: https://github.com/rancher/rancher/issues/38701

**Comment by cwayne18** [comment] 2023-02-07 20:50
@jiaqiluo @snasovich Is this rest of this work on your team's plate, or is everything set once KDM is merged?

**Comment by snasovich** [comment] 2023-02-09 04:50
@cwayne18 , there are no changes to be done on Rancher backend for it. I'm creating a UI issue to deal with an issue when k8s versions is changed and previously selected profile is no longer available. This specific issue is now ready to test.

**Comment by vivek-infracloud** [comment] 2023-02-17 12:40
Tested the issue on rancher v2.7.2-rc3.
CIS profile 1.5 is not yet removed. It is still visible when k8s version `v1.24.10+rke2r1` and `v1.23.16+rke2r1` is selected.

Hence, reopening the issue.

**Comment by cnotv** [comment] 2023-02-17 12:47
The list of CIS profiles come from the server configuration when selecting the k8s version and is not hardcoded in the UI. This has been mentioned several times, why is now reopenes?
@vivek-infracloud @snasovich @nwmac

**Comment by markusewalker** [comment] 2023-02-17 16:57
@cnotv to clarify my understanding, CIS profile 1.5 & 1.6 appears in the UI as it is part of the `profile` enumeration that is picked up from the `/v1-rke2-release/releases`, correct?

If so, then I don't believe this is an issue with UI as it seems to be functioning as expected.

**Comment by Sahota1225** [comment] 2023-02-21 23:19
@vivek-infracloud - Can we close this if the issue is functioning as expected ?

**Comment by markusewalker** [comment] 2023-02-22 18:45
Yesterday, I validated and closed https://github.com/rancher/dashboard/issues/8032, which appears to be covering the same test cases in this issue.

As a result, I'll close this issue.

**Closed by markusewalker** 2023-02-22 18:45 UTC
Labels: kind/enhancement, [zube]: Reopened, area/k8s-support, area/provisioning-rke2, feature/provisioned-rke2-k3s, team/area2, team/infracloud, team/rke2
