### ISSUE TITLE
Button missing after the "reset" action.

### ISSUE THREAD

**Issue by BalaBalaYi** [rancher/rancher#13327] opened 2018-05-07 06:27 UTC
**Rancher versions:**
rancher/server or rancher/rancher: v2.0.0
rancher/agent or rancher/rancher-agent:v2.0.0

**Infrastructure Stack versions:**
healthcheck: OK!
ipsec: OK!
network-services: OK!
scheduler: OK!
kubernetes (if applicable): OK!

**Docker version: (`docker version`,`docker info` preferred)**
17.03.2 ce
**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
centos7.2 
**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
virtual machine
**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
single node rancher
**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**
Kubernetes-1.10.1-rancher2
**Steps to Reproduce:**
1. global -> settings ->edit system-default-registry:
![image](https://user-images.githubusercontent.com/23303886/39687709-36afe6c2-5202-11e8-973e-1761c7711326.png)
2.edit system-default-registry again and reset:
![image](https://user-images.githubusercontent.com/23303886/39687751-5de65640-5202-11e8-89ab-8844f1d1957e.png)

**Results:**
The system-default-registry 's edit button is gone:
![image](https://user-images.githubusercontent.com/23303886/39687814-95997e0a-5202-11e8-9016-9ddf5648263c.png)

Restart rancher-server can solve this problem.

**Comment by loganhz** [comment] 2018-05-07 08:01
FYI, reset button has been removed in latest Rancher UI.
https://github.com/rancher/ui/commit/023961fd6ba32f35d4f139bad0af698fe7cc9e22

**Comment by superseb** [comment] 2018-05-07 08:05
Duplicate of https://github.com/rancher/rancher/issues/13225

**Closed by superseb** 2018-05-07 08:05 UTC
