### ISSUE TITLE
Edit Environment causes uncaught type error

### ISSUE THREAD

**Issue by epelc** [rancher/rancher#1780] opened 2015-08-12 12:33 UTC
When I try to change the name of an environment after clicking edit I get the following error in chrome `44.0.2403.130 m (64-bit)` on Windows 10

```
Uncaught TypeError: Cannot read property 'filterProperty' of undefined(anonymous function) @ edit-project.js:43f.get @ vendor.js:8s @ vendor.js:9e.default.o.Mixin.create.get @ vendor.js:13e.default.t.default.Mixin.create.validate @ edit-project.js:50n @ vendor.js:10e.default.t.default.Mixin.create.willSave @ new-or-edit.js:96m @ vendor.js:9e.default.t.default.Component.extend.willSave @ component.js:24n @ vendor.js:10e.default.t.default.Mixin.create.actions.save @ new-or-edit.js:79i.default.extend.send @ vendor.js:15n @ vendor.js:10(anonymous function) @ vendor.js:10a.run @ vendor.js:3u @ vendor.js:9h.push.handler @ vendor.js:10(anonymous function) @ vendor.js:15J.event.dispatch @ vendor.js:2g.handle @ vendor.js:2
```

**Comment by deniseschannon** [comment] 2015-08-12 21:05
This is a duplicate of https://github.com/rancher/rancher/issues/1590. The workaround is to click on the name of the environment and then Edit from that view. Instead of clicking on the edit from the drop down of the "Manage Environments" page.

**Closed by deniseschannon** 2015-08-12 21:05 UTC
