### ISSUE TITLE
[UI] EKS - unable to create EKS cluster in us-east-2

### ISSUE THREAD

**Issue by davidnuzik** [rancher/rancher#22150] opened 2019-08-13 17:42 UTC
Version: master-head (v2.3) (8/13/19)

**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
Create an EKS cluster in us-east-2 region

**Result:**
Worker node does not get created. The EKS cluster is active and working when check aws console, but no worker node was created. Rancher reports this error in the UI:
![image](https://user-images.githubusercontent.com/45179589/62964060-175ac400-bdb7-11e9-8cea-9c8d09e3143f.png)

**Comment by cbron** [comment] 2019-08-20 20:43
@davidnuzik Any other steps to reproduce ? I'm not able to so far, tried with m4 and t3 instances and both worker and cluster spun up fine for me.

**Comment by davidnuzik** [comment] 2019-08-21 16:06
@cbron there are no other steps required. Perhaps our QA aws account is missing something? maybe it's just a config issue on aws side -- not certain. If it worked for you it's unlikely this is a real rancher issue...

**Comment by cbron** [comment] 2019-08-21 16:17
Can you still replicate ? If so we can try to look at configs/logs and see what it's requesting from AWS thats causing crash. It's possible you just requested an [instance type](https://forums.aws.amazon.com/thread.jspa?threadID=109894) or resource that wasn't available in us-east-2, which if we can find it we might want to call out in UI at least.

**Comment by davidnuzik** [comment] 2019-08-21 17:46
Assigning to me to test again and get more info. I'll get rancher server logs and try to see if I can get a better idea on the cause. Thanks! I will try to get this back to you by EOD friday.

**Comment by davidnuzik** [comment] 2019-08-21 22:32
Version: master-head (v2.3) (8/21/19) ``

I tried again, this time taking a closer look at the frontend and the rancher server logs.

frontend http:
- query to get aws roles works without any issues I see the list of roles.
- query to get key pairs works without any issues I see the list of keypairs for the region.
- query to get vpcs works without any issues I see the list of vpcs for the region.
- I created with defaults but otherwise chose m3.medium instance type (this should not matter, works fine in any other region) I also tried the default and this too fails.
- POST to create cluster looks good. amazonElasticContainerServiceConfig looks good form what I can tell.

rancher server logs observations:
- Right after clicking the button to create the EKS cluster I see no errors while tailing rancher server logs.
- Backend successfully brings up vpc (according to logs no issues with this it seems)
- Backend successfully creates service role (according to logs no issues with this it seems)
- Backend attempts to create eks cluster (this always takes a long time as we wait for AWS to fully provision cluster)
While this is happening, we see many log lines indicating "Waiting for cluster to finish provisioning"
- After some time, the cluster will be up and EKS cluster seems good when we check the AWS web console; this seems to prove to me our config and permissions are good. We see 
![image](https://user-images.githubusercontent.com/45179589/63472839-3d700c00-c428-11e9-9c03-47ceb73e3b67.png)

So, I'm pretty sure something funky is going on in the backend. I'm not sure what else to check. Permissions seem good to me and we seem to have the config correct.

**Comment by cbron** [comment] 2019-08-22 18:29
Recreated locally and found the problem, us-east-2 doesn't support m3 instances. Currently the only offerings for that region are: `t2, t3a, t3, m5ad, m5a, m5d, m5, m4`. Officially the m3 class is regarded as a _"Previous Generation"_, they aren't listed on [primary instance-types page](https://aws.amazon.com/ec2/instance-types/), which means this will occur in other regions soon. 

There is a good discussion here around same topic: https://github.com/kubernetes-incubator/kube-aws/issues/181 

So we have a few options: 
1. Display a note about m3 class not being available in specific regions and leave as default. This will need to get updated in the future as m3 is deprecated in more regions. 
2. Change default to m4.large or m5.large. The official upgrade path is [direct to m5](https://aws.amazon.com/rds/previous-generation/).

I doubt we want to remove m3 as an option entirely.

**Comment by davidnuzik** [comment] 2019-08-22 19:45
I may have actually neglected to try with default... m4.large already is default. I thought I tried it but I must not have.
I think the UI should just warn in my opinion. Perhaps even for each and every region; it could say something generic like this instance type may not work in your region or something.

**Comment by vincent99** [comment] 2019-08-22 20:39
I don't see any real practical way to do something about this with just the UI.  Every type is potentially unusable in some region, it's not as simple as just calling some deprecated.  

The problem goes both ways, you can have types that are old and not supported in newer regions and types that are new and not supported (yet, or ever) in older regions.

You would think there would be an API for "what instance types are available in this region/zone", but this rather famously doesn't really exist.  There is a [pricing API](https://aws.amazon.com/blogs/aws/new-aws-price-list-api/) which does [indirectly list](https://pricing.us-east-
1.amazonaws.com/offers/v1.0/aws/AmazonEC2/current/us-east-1/index.csv) all the types because there's prices for each instance type.  But it's a ~55MB per region download to extract about 2KB worth of instance types, so that's impractical to download and parse in the user's browser.

If you really wanted to address this the best way I can think of would be to add an API call which will do that download and parsing on the backend for a given input region, and cache it for a day-ish so that it's not all being downloaded constantly.

Or do that for all ~20 regions and produces a small map which is hosted on our CDN and updated periodically, and have the server just download that periodically.

**Comment by davidnuzik** [comment] 2019-08-23 16:17
Based on how cumbersome this could be (to do this properly). Perhaps it would be best to have a small ? tooltip that generically mentions something along the lines of: Check to ensure your instance type is supported for your region
(and possibly link to aws pricing docs, etc?)

cc: @tfiduccia

**Comment by cjellick** [comment] 2019-08-23 16:26
moving out. want to do it as part of our provisioning refactor in v2.4. i have a note to potentially add it as a release note, but as Vincent says, this is not new.

**Comment by deniseschannon** [comment] 2019-10-05 15:45
Closing as part of https://github.com/rancher/rancher/issues/23244

**Closed by deniseschannon** 2019-10-05 15:45 UTC
Labels: [zube]: To Triage, area/kontainer-engine, kind/bug-qa, team/ui
