### ISSUE TITLE
kubectl delete node - not working with Rancher Server

### ISSUE THREAD

**Issue by frekele** [rancher/rancher#15039] opened 2018-08-10 21:04 UTC
**Rancher versions:**
rancher/rancher:v2.0.8
rancher/rancher-agent:v2.0.8

**Infrastructure Stack versions:**
kubernetes V1.11.2-rancher1-1

**Docker version:**
```
Client:
 Version:      17.03.2-ce
 API version:  1.27
 Go version:   go1.7.5
 Git commit:   f5ec1e2
 Built:        Tue Jun 27 02:31:19 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.03.2-ce
 API version:  1.27 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   f5ec1e2
 Built:        Tue Jun 27 02:31:19 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

**Operating system and kernel:**

```
Debian 9.5 - stretch
PRETTY_NAME="Debian GNU/Linux 9 (stretch)"
NAME="Debian GNU/Linux"
VERSION_ID="9"
VERSION="9 (stretch)"
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"

Debian Kernel: 4.9.0-8-amd64
```

**Type/provider of hosts:**
AWS EC2

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
Single Node Rancher Server and added agent in my own existing nodes (Custom).

**Environment Template:**
Kubernetes

**Steps to Reproduce:**
When the instance is checked to finish, I run a script to do drain and delete the node.
It works perfectly with only kubernetes, but rancher server does not delete the node.

**Results:**
The node is marked with cordon but not deleted in rancher server, but in kubernetes cluster was removed perfectly.

**Expected behavior:**
If a node is removed in the kubernetes cluster, the rancher server should also delete it node.

My cluster aws ec2 has:
1 instance with single node **rancher-server**.
3 instances with **etcd** and **control**.
5 spot instances with **worker**.
All behind AWS ALB.

When an instance is terminated I have a script to do drain and delete node. This works perfectly with cluster kubernetes, but inside the rancher-server painel it is not deleted.

In all my nodes I have the following LSB script /etc/init.d/a1-kubectl-drain-node which is added automatically with cloud-init when the instance is launched (Debian 9.5).
```
#!/bin/bash
### BEGIN INIT INFO
# Provides:           a1-kubectl-drain-node
# Required-Start:     $syslog $network $remote_fs
# Required-Stop:      $syslog $network $remote_fs
# Should-Start:       docker
# Should-Stop:        docker
# Default-Start:      2 3 4 5
# Default-Stop:       0
# Short-Description:  Kubernetes Drain Node before instance terminate.
# Description:
#  Kubernetes Drain Node before instance terminate, Run kubectl command.
#  Author: frekele
### END INIT INFO

## For configuration:
## Add file 'a1-kubectl-drain-node' into /etc/init.d/
## chmod 775 /etc/init.d/a1-kubectl-drain-node
## systemctl daemon-reload
## update-rc.d a1-kubectl-drain-node defaults
## update-rc.d a1-kubectl-drain-node enable
## service a1-kubectl-drain-node start
##
## Others commands:
## update-rc.d a1-kubectl-drain-node disable
## update-rc.d a1-kubectl-drain-node remove
## service a1-kubectl-drain-node start|stop|status

set -e

export PATH=/sbin:/bin:/usr/sbin:/usr/bin:/usr/local/sbin:/usr/local/bin

# Get lsb functions
. /lib/lsb/init-functions

function spotTerminationBackgroundListener(){
    echo "spotTerminationBackgroundListener Started."
    #Sleep 3 minutes.
    sleep 180
    
    HOSTNAME_FQDN=$(hostname --fqdn)
    KUBE_CONFIG=/root/.kube/aws-cloud
    KDRAIN_LOGFILE=/var/log/a1-kubectl-drain-node.log
    
    kubectl get node ${HOSTNAME_FQDN} --kubeconfig=${KUBE_CONFIG} --insecure-skip-tls-verify=true >> "$KDRAIN_LOGFILE" 2>&1 | true
    while true
        do
            if [ -z $(curl -Is http://169.254.169.254/latest/meta-data/spot/termination-time | head -1 | grep 404 | cut -d \  -f 2) ]
                then
                    echo "Spot Instance marked for termination!"
                    kubectl get node ${HOSTNAME_FQDN} --kubeconfig=${KUBE_CONFIG} --insecure-skip-tls-verify=true >> "$KDRAIN_LOGFILE" 2>&1 | true
                    kubectl drain ${HOSTNAME_FQDN} --kubeconfig=${KUBE_CONFIG} --insecure-skip-tls-verify=true >> "$KDRAIN_LOGFILE" 2>&1 | true
                    kubectl drain ${HOSTNAME_FQDN} --kubeconfig=${KUBE_CONFIG} --insecure-skip-tls-verify=true >> "$KDRAIN_LOGFILE" 2>&1 | true
                    kubectl delete node ${HOSTNAME_FQDN} --kubeconfig=${KUBE_CONFIG} --insecure-skip-tls-verify=true >> "$KDRAIN_LOGFILE" 2>&1 | true
                    break
                else
                    #echo "Spot instance not yet marked for termination."
                    sleep 5
            fi
        done
    echo "spotTerminationBackgroundListener Stopped."
}

HOSTNAME_FQDN=$(hostname --fqdn)
KUBE_CONFIG=/root/.kube/aws-cloud
KDRAIN_LOGFILE=/var/log/a1-kubectl-drain-node.log

case "$1" in
        start)
                echo "Starting a1-kubectl-drain-node" >> "$KDRAIN_LOGFILE" 2>&1
                touch "$KDRAIN_LOGFILE"
                chown root:root "$KDRAIN_LOGFILE"
                export -f spotTerminationBackgroundListener
                nohup bash -c spotTerminationBackgroundListener >> "$KDRAIN_LOGFILE" 2>&1 &
                echo "Started a1-kubectl-drain-node" >> "$KDRAIN_LOGFILE" 2>&1
                ;;

        stop)
                echo "Stoping a1-kubectl-drain-node" >> "$KDRAIN_LOGFILE" 2>&1
                kubectl get node ${HOSTNAME_FQDN} --kubeconfig=${KUBE_CONFIG} --insecure-skip-tls-verify=true >> "$KDRAIN_LOGFILE" 2>&1 | true
                kubectl drain ${HOSTNAME_FQDN} --kubeconfig=${KUBE_CONFIG} --insecure-skip-tls-verify=true >> "$KDRAIN_LOGFILE" 2>&1 | true
                kubectl drain ${HOSTNAME_FQDN} --kubeconfig=${KUBE_CONFIG} --insecure-skip-tls-verify=true >> "$KDRAIN_LOGFILE" 2>&1 | true
                kubectl delete node ${HOSTNAME_FQDN} --kubeconfig=${KUBE_CONFIG} --insecure-skip-tls-verify=true >> "$KDRAIN_LOGFILE" 2>&1 | true
                echo "Stopped a1-kubectl-drain-node" >> "$KDRAIN_LOGFILE" 2>&1
                ;;

        status)
                echo "Status a1-kubectl-drain-node" >> "$KDRAIN_LOGFILE" 2>&1
                ;;

        *)
                echo "Usage: service a1-kubectl-drain-node {start|stop|status}" >&2
                exit 1
                ;;
esac

```
Reference: https://github.com/frekele/kubectl-drain-node

**AWS EC2 has 3 ways to terminate an instance**
 - [Spot instances Termination](https://aws.amazon.com/pt/blogs/aws/new-ec2-spot-instance-termination-notices/): The Termination Notice is accessible to code running on the instance via the instance’s metadata at http://169.254.169.254/latest/meta-data/spot/termination-time 

 - [Auto Scaling Termination](https://docs.aws.amazon.com/autoscaling/ec2/userguide/AutoScalingGroupLifecycle.html): The EC2 instances in an Auto Scaling group have a path, or lifecycle, that differs from that of other EC2 instances

- User request Termination: When the user terminates an instance manually.

My script 'a1-kubectl-drain-node' launches a listener in backgroud that ends the instance in advance when its is marked as spot termination through the url  http://169.254.169.254/latest/meta-data/spot/termination-time .

If it is not terminated in advance, it can also be terminated when the instance is already in the process of closing, so it runs the script at level 0 (/etc/rc0.d/K01a1-kubectl-drain-node).

When I run the following commands:

```
#Works with kubernetes and rancher.
kubectl drain my-node-host --kubeconfig=my-config --insecure-skip-tls-verify=true
```

```
# Works only with kubernetes and not with rancher.
kubectl delete node my-node-host --kubeconfig=my-config --insecure-skip-tls-verify=true
```

this problem exists in rancher/rancher: version **2.0.6, 2.0.7 and 2.0.8**.

Hope this helps.

**Comment by frekele** [comment] 2018-08-14 17:45
@kinarashah @cjellick @ibuildthecloud  - We can consider this critical issue!

**Comment by cjellick** [comment] 2018-08-14 19:26
Was this cluster provisioned through the rancher UI or was it provisioned outside of rancher and then imported?

**Comment by frekele** [comment] 2018-08-14 20:53
Hi @cjellick ,

The cluster was created within the Rancher server and rancher agents deployed inside the ec2 instances launched with cloud-init.

Into cloud-init:

Single Rancher Server:
```
docker run -d --restart=unless-stopped \
--name 'rancher-server' \
-p 9999:80 -p 9998:443 \
-v /opt/rancher-data:/var/lib/rancher \
rancher/rancher:${RANCHER_SERVER_VERSION} 
```

Node Rancher Agents:
```
docker run -d --privileged --restart=unless-stopped \
--name 'rancher-agent' \
--net=host -v /etc/kubernetes:/etc/kubernetes \
-v /var/run:/var/run rancher/rancher-agent:${RANCHER_AGENT_VERSION} \
--server ${RANCHER_SERVER_HOST} \
--token ${RANCHER_TOKEN} \
--ca-checksum ${RANCHER_CA_CHECKSUM} \
--worker \
--label aws-zone=${INSTANCE_ZONE} \
--label node-type=${LABEL_NODE_TYPE}
```

single node rancher-server - 1 instance  on-demand.
Node etcd + control - 1 instance on-demand + 2 spot instances.
Node worker - 5 spot instances.
AWS Region: sa-east-1
All behind AWS ALB.
All launched with auto scaling + cloud-init.

**Comment by frekele** [comment] 2018-08-14 21:15
I launch using an already pre-configured AMI with docker.

My cloud-config rancher-server.yml:
```
#cloud-config

package_update: true
locale: en_US.UTF-8
timezone: UTC
resize_rootfs: true

bootcmd:
 - echo "Init bootcmd"
 
runcmd:
 - echo "Init runcmd"
 - [ systemctl, daemon-reload ]
 - [ systemctl, enable, docker.service ]
 - [ systemctl, start, --no-block, docker.service ]
 - [ systemctl, is-active, docker ]
 - docker version
 
 - export RANCHER_DATA_PERSISTENT_VOLUME_ID=vol-xxxxxxxx
 - export RANCHER_SERVER_VERSION=v2.0.7
 
# Github credentials.
 - aws s3 cp s3://xxxxxxxxxxx/cloud-init/github-auth.sh /root/github-auth.sh
 - chmod +x /root/github-auth.sh
 - sed -i 's/\r$//' /root/github-auth.sh
 - export $(./root/github-auth.sh)
 
# Attached o EBS rancher-data.
 - curl https://${GITHUB_USER}:${GITHUB_TOKEN}@raw.githubusercontent.com/xxxxxxxxx/cloud-init-xxxxxx/master/sh/mount-volume/pv-rancher-data.sh -o /root/pv-rancher-data.sh
 - chmod +x /root/pv-rancher-data.sh
 - sed -i 's/\r$//' /root/pv-rancher-data.sh
 - sh -c ./root/pv-rancher-data.sh
 
# Add aws-scripts-mon for CloudWatch.
 - mkdir /cloudwatch
 - rm -rf /var/tmp/aws-mon
 - curl http://aws-cloudwatch.s3.amazonaws.com/downloads/CloudWatchMonitoringScripts-1.2.1.zip -o /cloudwatch/CloudWatchMonitoringScripts-1.2.1.zip
 - unzip /cloudwatch/CloudWatchMonitoringScripts-1.2.1.zip -d /cloudwatch/
 - chmod +x /cloudwatch/aws-scripts-mon/mon-put-instance-data.pl
 - /cloudwatch/aws-scripts-mon/mon-put-instance-data.pl --auto-scaling=only --mem-util --disk-space-util --disk-path=/ --disk-path=/mnt/ebs-volume-rancher/
 - echo "*/5 * * * * root /cloudwatch/aws-scripts-mon/mon-put-instance-data.pl --auto-scaling=only --mem-util --disk-space-util --disk-path=/  --disk-path=/mnt/ebs-volume-rancher/ --from-cron" > /etc/cron.d/scheduler-cloud-watch-monitor
 
 - printenv
 
# Run docker.
 - docker pull rancher/rancher:${RANCHER_SERVER_VERSION}
 - docker run -d --restart=unless-stopped -p 9999:80 -p 9998:443 --name 'rancher-server' -v /mnt/ebs-volume-rancher/rancher-data:/var/lib/rancher  rancher/rancher:${RANCHER_SERVER_VERSION}
 
 - echo "END runcmd"

final_message: "$UPTIME segs END."
```


My cloud-config k8s-etcd-control-multi-az.yml:
```
#cloud-config

package_update: true
locale: en_US.UTF-8
timezone: UTC
resize_rootfs: true

bootcmd:
 - echo "Init bootcmd"

runcmd:
 - echo "Init runcmd"
 - [ systemctl, daemon-reload ]
 - [ systemctl, enable, docker.service ]
 - [ systemctl, start, --no-block, docker.service ]
 - [ systemctl, is-active, docker ]
 - docker version
 
 - export RANCHER_AGENT_VERSION=v2.0.7
 - export RANCHER_TOKEN=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
 - export KUBERNETES_NODE_VERSION=v1.11.1
 - export INSTANCE_REGION=sa-east-1
 - export INSTANCE_PRIVATE_IP=$(curl http://169.254.169.254/latest/meta-data/local-ipv4)
 - export INSTANCE_PUBLIC_IP=$(curl http://169.254.169.254/latest/meta-data/public-ipv4)
 - export INSTANCE_ZONE=$(curl http://169.254.169.254/latest/meta-data/placement/availability-zone)
 - export RANCHER_SERVER_HOST=https://rancher.xxxxx.xxx:9999
 - export RANCHER_CA_CHECKSUM=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
 - export LABEL_NODE_TYPE=etcd-control
 
# Github credentials.
 - aws s3 cp s3://xxxxxxxxxxx/cloud-init/github-auth.sh /root/github-auth.sh
 - chmod +x /root/github-auth.sh
 - sed -i 's/\r$//' /root/github-auth.sh
 - export $(./root/github-auth.sh)
 
# Install kubectl-drain-node.
 - curl https://${GITHUB_USER}:${GITHUB_TOKEN}@raw.githubusercontent.com/xxxxxxxxxxxxxx/cloud-init-xxxxxxxxxx/master/sh/install-config/configure-kubectl-drain-node.sh -o /root/configure-kubectl-drain-node.sh
 - chmod +x /root/configure-kubectl-drain-node.sh
 - sed -i 's/\r$//' /root/configure-kubectl-drain-node.sh
 - sh -c ./root/configure-kubectl-drain-node.sh
 
# Add aws-scripts-mon for CloudWatch.
 - mkdir /cloudwatch
 - rm -rf /var/tmp/aws-mon
 - curl http://aws-cloudwatch.s3.amazonaws.com/downloads/CloudWatchMonitoringScripts-1.2.1.zip -o /cloudwatch/CloudWatchMonitoringScripts-1.2.1.zip
 - unzip /cloudwatch/CloudWatchMonitoringScripts-1.2.1.zip -d /cloudwatch/
 - chmod +x /cloudwatch/aws-scripts-mon/mon-put-instance-data.pl
 - /cloudwatch/aws-scripts-mon/mon-put-instance-data.pl --auto-scaling=only --mem-util --disk-space-util --disk-path=/
 - echo "*/5 * * * * root /cloudwatch/aws-scripts-mon/mon-put-instance-data.pl --auto-scaling=only --mem-util --disk-space-util --disk-path=/ --from-cron" > /etc/cron.d/scheduler-cloud-watch-monitor

- printenv
 
# Run docker.
 - docker pull rancher/rancher-agent:${RANCHER_AGENT_VERSION}
 - export COMMAND_RANCHER_AGENT="docker run -d --privileged --restart=unless-stopped --name 'rancher-agent' --net=host -v /etc/kubernetes:/etc/kubernetes -v /var/run:/var/run rancher/rancher-agent:${RANCHER_AGENT_VERSION} --server ${RANCHER_SERVER_HOST} --token ${RANCHER_TOKEN} --ca-checksum ${RANCHER_CA_CHECKSUM} --etcd --controlplane --label aws-zone=${INSTANCE_ZONE} --label node-type=${LABEL_NODE_TYPE}"
 - docker ps
 - echo "Executa COMMAND_RANCHER_AGENT-->  $COMMAND_RANCHER_AGENT"
 - docker top 'rancher-agent' || sh -c "$COMMAND_RANCHER_AGENT"
 
final_message: "$UPTIME segs END."
```

My cloud-config k8s-etcd-control-multi-az.yml:
```
#cloud-config

package_update: true
locale: en_US.UTF-8
timezone: UTC
resize_rootfs: true

bootcmd:
 - echo "Init bootcmd"

runcmd:
 - echo "Init runcmd"
 - [ systemctl, daemon-reload ]
 - [ systemctl, enable, docker.service ]
 - [ systemctl, start, --no-block, docker.service ]
 - [ systemctl, is-active, docker ]
 - docker version
 
 - export RANCHER_AGENT_VERSION=v2.0.7
 - export RANCHER_TOKEN=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
 - export KUBERNETES_NODE_VERSION=v1.11.1
 - export INSTANCE_REGION=sa-east-1
 - export INSTANCE_PRIVATE_IP=$(curl http://169.254.169.254/latest/meta-data/local-ipv4)
 - export INSTANCE_PUBLIC_IP=$(curl http://169.254.169.254/latest/meta-data/public-ipv4)
 - export INSTANCE_ZONE=$(curl http://169.254.169.254/latest/meta-data/placement/availability-zone)
 - export RANCHER_SERVER_HOST=https://rancher.xxxxx.xxx:9999
 - export RANCHER_CA_CHECKSUM=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
 - export LABEL_NODE_TYPE=worker
 
# Github credentials.
 - aws s3 cp s3://xxxxxxxxxxx/cloud-init/github-auth.sh /root/github-auth.sh
 - chmod +x /root/github-auth.sh
 - sed -i 's/\r$//' /root/github-auth.sh
 - export $(./root/github-auth.sh)
 
# Install kubectl-drain-node.
 - curl https://${GITHUB_USER}:${GITHUB_TOKEN}@raw.githubusercontent.com/xxxxxxxxxxxxxx/cloud-init-xxxxxxxxxx/master/sh/install-config/configure-kubectl-drain-node.sh -o /root/configure-kubectl-drain-node.sh
 - chmod +x /root/configure-kubectl-drain-node.sh
 - sed -i 's/\r$//' /root/configure-kubectl-drain-node.sh
 - sh -c ./root/configure-kubectl-drain-node.sh
 
# Add aws-scripts-mon for CloudWatch.
 - mkdir /cloudwatch
 - rm -rf /var/tmp/aws-mon
 - curl http://aws-cloudwatch.s3.amazonaws.com/downloads/CloudWatchMonitoringScripts-1.2.1.zip -o /cloudwatch/CloudWatchMonitoringScripts-1.2.1.zip
 - unzip /cloudwatch/CloudWatchMonitoringScripts-1.2.1.zip -d /cloudwatch/
 - chmod +x /cloudwatch/aws-scripts-mon/mon-put-instance-data.pl
 - /cloudwatch/aws-scripts-mon/mon-put-instance-data.pl --auto-scaling=only --mem-util --disk-space-util --disk-path=/
 - echo "*/5 * * * * root /cloudwatch/aws-scripts-mon/mon-put-instance-data.pl --auto-scaling=only --mem-util --disk-space-util --disk-path=/ --from-cron" > /etc/cron.d/scheduler-cloud-watch-monitor

- printenv
 
# Run docker.
 - docker pull rancher/rancher-agent:${RANCHER_AGENT_VERSION}
 - export COMMAND_RANCHER_AGENT="docker run -d --privileged --restart=unless-stopped --name 'rancher-agent' --net=host -v /etc/kubernetes:/etc/kubernetes -v /var/run:/var/run rancher/rancher-agent:${RANCHER_AGENT_VERSION} --server ${RANCHER_SERVER_HOST} --token ${RANCHER_TOKEN} --ca-checksum ${RANCHER_CA_CHECKSUM} --worker --label aws-zone=${INSTANCE_ZONE} --label node-type=${LABEL_NODE_TYPE}"
 - docker ps
 - echo "Executa COMMAND_RANCHER_AGENT-->  $COMMAND_RANCHER_AGENT"
 - docker top 'rancher-agent' || sh -c "$COMMAND_RANCHER_AGENT"
 
final_message: "$UPTIME segs END."
```

**Comment by superseb** [comment] 2018-09-10 07:35
Duplicate of https://github.com/rancher/rancher/issues/14184

**Closed by superseb** 2018-09-10 07:35 UTC
Labels: kind/bug, version/2.0
