### ISSUE TITLE
globalDns TTL default should not be zero

### ISSUE THREAD

**Issue by davidnuzik** [rancher/rancher#18349] opened 2019-02-22 23:45 UTC
Version: Master 2.2 (2/22/19)

**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
- Inspect v3/schemas/globalDns
- Notice ttl default is zero
- In the UI create a DNS entry and the UI will show 0 as default (expected since API says default is 0). In Route53 you'll actually get 300 not zero.

**Result:**
TTL is not zero it's 300. Presumably api is either sending nothing and so R53 does default of 300 or something in backend is telling R53 to use 300 when default TTL is used (zero).

**Other details that may be helpful:**
Perhaps the default should be 300 instead to avoid confusion?

**Comment by alena1108** [comment] 2019-02-23 00:40
A duplicate of https://github.com/rancher/rancher/issues/18198

**Closed by alena1108** 2019-02-23 00:40 UTC
Labels: area/api, kind/bug-qa, team/ca, version/2.0
