### ISSUE TITLE
[Backport] Remove EKS deprecated k8s version 1.17

### ISSUE THREAD

**Issue by Jono-SUSE-Rancher** [rancher/rancher#33826] opened 2021-07-29 15:36 UTC
This is a backport of rancher/rancher#33825 - Amazon EKS is deprecating support on k8s 1.17 and this is a backport ticket to support it in the 2.5.x line.

**Comment by aiyengar2** [comment] 2021-11-18 21:33
@Jono-SUSE-Rancher closing as this is a duplicate of an already closed ticket in https://github.com/rancher/rancher/issues/35515. Feel free to re-open if you disagree!

**Closed by aiyengar2** 2021-11-18 21:33 UTC
Labels: [zube]: RT - Sprint Ready
