### ISSUE TITLE
Errors relating to token deletion seen in logs when project is deleted.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#12266] opened 2018-03-26 03:48 UTC
Rancher server version - Build from master

Steps to reproduce the problem:
Create a cluster with few projects having namespace and workloads.
Delete the project.

Following errors seen in logs:

```
2018/03/26 03:43:32 [INFO] Deleting secret [default-token-gt9rm] in namespace [mytest1]
E0326 03:43:32.201608       1 tokens_controller.go:259] error synchronizing serviceaccount project-kndpx/default: secrets "default-token-w47kc" is forbidden: unable to create new content in namespace project-kndpx because it is being terminated.
E0326 03:43:32.214874       1 tokens_controller.go:259] error synchronizing serviceaccount project-kndpx/default: secrets "default-token-2t4gf" is forbidden: unable to create new content in namespace project-kndpx because it is being terminated.
E0326 03:43:32.232363       1 tokens_controller.go:259] error synchronizing serviceaccount project-kndpx/default: secrets "default-token-zq66j" is forbidden: unable to create new content in namespace project-kndpx because it is being terminated.
E0326 03:43:32.260339       1 tokens_controller.go:259] error synchronizing serviceaccount project-kndpx/default: secrets "default-token-86jch" is forbidden: unable to create new content in namespace project-kndpx because it is being terminated.
```

**Comment by kinarashah** [comment] 2018-09-12 17:17
(Similar to cluster delete issue) 
@alena1108 @sangeethah It looks like that it's not us who call this sync for serviceaccounts. It is coming from Kubernetes, where on every serviceaccount sync, it ensures that the token exists for it, and if it doesn't (in this case, it might have been deleted on namespace delete) - it tries to create a new secret. And this fails because no new content is allowed to be created when namespace is in terminating phase.  For reference, https://github.com/kubernetes/kubernetes/blob/master/pkg/controller/serviceaccount/tokens_controller.go#L259 is the function and 261 is where it just logs the error. 

I think currently we just log whatever Kubernetes logs, so we might need to have a better filtering for these kind of messages since they add no value to user at this point.

**Comment by alena1108** [comment] 2018-09-12 17:19
Moving out as the issue is intermittent and recoverable from. Need more debugging and the fix most likely will be in the framework as the error is thrown by k8s, and we just bubble it up.

**Closed** 2019-04-08 22:55 UTC
Labels: kind/enhancement, priority/0, status/autoclosed, team/ca
