### ISSUE TITLE
[BUG] Rancher did not know "etcd status condition" introduced in K3s

### ISSUE THREAD

**Issue by Delta1977** [rancher/rancher#43715] opened 2023-12-07 13:41 UTC
**Rancher Server Setup**
- Rancher version: 2.8.0
- Installation option (Docker install/Helm Chart):
- Helm on K3s 1.26.11 and 1.27.8

3 weeks ago K3s introduced  "Etcd status condition"  which now arrive in newer build from K3s:
1.27: https://github.com/k3s-io/k3s/pull/8821 introduced in [v1.27.8+k3s1](https://github.com/k3s-io/k3s/releases/tag/v1.27.8%2Bk3s1)
1.26: https://github.com/k3s-io/k3s/pull/8820 introduced in  [v1.26.11+k3s1]https://github.com/k3s-
io/k3s/releases/tag/v1.26.11%2Bk3s1
1.25: https://github.com/k3s-io/k3s/pull/8819 introduced in [v1.25.16+k3s3](https://github.com/k3s-io/k3s/releases/tag/v1.25.16%2Bk3s3)

Rancher doesnt know this condition and complains about it in events
Unknown condition true of kubernetes node NODENAME: condition type is EtcdIsVoter, reason is MemberNotLearner, message is Node is a voting member of the etcd cluster

**Comment by brandond** [comment] 2023-12-09 00:44
> Rancher doesnt know this condition and complains about it in events

Events on the node do not generally come from rancher itself, the event is most likely coming from a controller somewhere. What else do you have deployed to the cluster in question?

**Comment by brandond** [comment] 2023-12-09 00:49
The event is coming from Longhorn; closing this issue - please track on the LH side.
* https://github.com/longhorn/longhorn/issues/7290

**Closed by brandond** 2023-12-09 00:49 UTC
Labels: kind/bug

**Comment by Delta1977** [comment] 2023-12-09 01:18
@brandond no, This event come from K3s ( see K3s Commits above ) and not from Longhorn. Longhorn also complains about this new "unknow" condition from k3s. 
My cluster is a simple standard K3s with rancher and longhorn

**Comment by brandond** [comment] 2023-12-09 01:23
No, the event does not come from K3s or Rancher. The event comes from Longhorn when it sees a node condition that it does not expect. This will need to be fixed on the LH side. Please see the LH issue for more information on the root cause.
