### ISSUE TITLE
The specified port becomes a random port

### ISSUE THREAD

**Issue by boot-vue** [rancher/rancher#24501] opened 2019-12-10 08:33 UTC
rancher 2.3.3

deploy Workload   , input  port  30001,  after deploy, the port becomes a random port such as 30123

**Comment by Nicknack1234** [comment] 2019-12-10 13:14
Also experience this, new cluster latest versions. 

Any NodePort defined on a container, with a port manually defined inside the approved range it changes to random in the gui and assigns a random port.

**Comment by loganhz** [comment] 2019-12-12 07:24
Reproduced in  2.3.3

Steps:

1. Deploy a workload with NodePort `On listening port` `30001`
2. Click Deploy 
3. Check the auto generated svc.

Results:

Instead of using `30001` as nodeport , it changed to use a random port. It looks like UI passed the correct sourcePort field but server didn't populate it correctly.

![image](https://user-images.githubusercontent.com/21168270/70687442-29f3f400-1cea-11ea-9611-d46ba5af18e6.png)
![image](https://user-images.githubusercontent.com/21168270/70687506-5b6cbf80-1cea-11ea-872e-91a6f86d9aa2.png)
![image](https://user-images.githubusercontent.com/21168270/70687655-c3230a80-1cea-11ea-8ae9-e8ca28991eb2.png)

**Comment by loganhz** [comment] 2019-12-13 10:29
Close in favor of https://github.com/rancher/rancher/issues/24551

It will be fixed in 2.3.4

**Closed by loganhz** 2019-12-13 10:29 UTC
Labels: kind/bug, team/cn
