### ISSUE TITLE
"Reuse IP addresses" option ignored

### ISSUE THREAD

**Issue by bradjones1** [rancher/rancher#5732] opened 2016-08-16 02:21 UTC
Creating/upgrading a service, selecting the "Reuse IP addresses..." option on the Network tab has no effect. The IP is selected at random, and when attempting to re-upgrade, the checkbox does not retain its state (that is, it shows as un-checked.)

As a UI improvement, as well, it seems that this checkbox should probably be disabled if a specific IP is requested.
---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v1.2.0-pre1` Cattle: `v0.167.5` UI: `v1.2.5` |
|Access|`github` `admin`|
|Orchestration|`Swarm`|
|Route|`service.new`|

**Comment by tfiduccia** [comment] 2016-08-16 17:36
duplicate of #5410

**Closed by tfiduccia** 2016-08-16 17:36 UTC
