### ISSUE TITLE
Custom catalog doesn't support ssh way to clone git repo

### ISSUE THREAD

**Issue by wahyd4** [rancher/rancher#5400] opened 2016-07-12 07:19 UTC
**Rancher Version:**
1.1.0
**Docker Version:**
1.11.2
**OS and where are the hosts located? (cloud, bare metal, etc):**
Linux version 3.10.0-123.el7.x86_64 (builder@kbuilder.dev.centos.org) (gcc version 4.8.2 20140120 (Red Hat 4.8.2-16) (GCC) )  Located in China Telecom Chengdu
**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
HA rancher
**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle
**Steps to Reproduce:**
* Go to Admin -> Settings page 
* Add a custom catalog with url equals to git@github.com:yunlzheng/rancher-catalog.git
* Then go the catalog you created
**Results:** 
* There is nothing in the catalog
**Expected:**
* You should see something items in the catalog

**Comment by deniseschannon** [comment] 2016-07-12 18:15
Duplicate of https://github.com/rancher/rancher/issues/3147

**Closed by deniseschannon** 2016-07-12 18:15 UTC
