### ISSUE TITLE
Able to add the same user members multiple times to a given project / cluster

### ISSUE THREAD

**Issue by ilyesFh** [rancher/rancher#39634] opened 2022-11-17 08:30 UTC
**Rancher Server Setup**
- Rancher version: 2.6.9
- Installation option (Docker install/Helm Chart): Helm Chart
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): RKE2, v1.21.12
- Proxy/Cert Details:

**Information about the Cluster**
- Kubernetes version: v1.21.12
- Cluster Type (Local/Downstream): Local

**User Information**
- What is the role of the user logged in? Admin

**Describe the bug**

we can add the same role to the same user several times on a project
On the old version of Rancher 2.5x this was not possible.

**To Reproduce**

add user1 as a member to project1 twice

**Result**

user has 2 times the same role on the same project

**Screenshots**
<img width="877" alt="image" src="https://user-images.githubusercontent.com/24758568/202395498-12587075-6879-4415-8a6b-45c0a2fcb17b.png">

**Comment by slickwarren** [comment] 2022-11-17 21:32
This is reproducible on v2.7.0. Repro steps:
* as admin, create a new standard user
* as admin, navigate to a cluster's projects
* edit the config of a project
* add the new standard user as a member to the project
  * before clicking save, add the same user again as a member
* save the changes to the project
* observe the config of the project and note that the user is listed 2x as a member


affected functionality:
a member with multiple roles will have access to the highest access listed, or what looks like a combination of the assigned roles. So this could affect admins who are trying to demote a user's permissions who do not remove the existing user

**Comment by anupama2501** [comment] 2022-11-22 17:38
Dup of https://github.com/rancher/dashboard/issues/3344

**Comment by slickwarren** [comment] 2022-11-29 18:54
closing in favor of the above linked issue

**Closed by slickwarren** 2022-11-29 18:54 UTC
Labels: kind/bug, area/rbac, kind/bug-qa, [zube]: To Triage, team/area1
