### ISSUE TITLE
Default Local Admin is demoted to Standard User when Auth Provider is registered

### ISSUE THREAD

**Issue by maxsokolovsky** [rancher/rancher#37057] opened 2022-03-25 23:48 UTC
**Rancher Server Setup**
- Rancher version: v2.6.4-rc5
- Installation option (Docker install/Helm Chart):
   Local and Docker

**Information about the Cluster**
- Kubernetes version: 1.23 and possibly 1.22
- Cluster Type (Local/Downstream): Local

**User Information**
- What is the role of the user logged in? (Admin/Cluster Owner/Cluster Member/Project Owner/Project Member/Custom) Admin 

   
**Describe the bug**
When I import an auth provider and authenticate as an admin user from that auth provider, the default local admin user is demoted to a Standard User. Also, there are two DefaultAdmin users instead of one.

This means that users may get locked out of Rancher, if there is a problem with the auth provider, and they had logged out. Because the default admin user does not have admin permissions anymore, users cannot regain control of the cluster. 

**To Reproduce**
1. Register an auth provider, get authenticated as an admin user from the auth provider.
2. Log out.
3. Log back in as the local admin. 
4. Observe that you're suddenly a Standard User, so can't see the local cluster, and there are now two Default Admin users (this can be seen from the view of the auth provider admin user).

**Result**

**Expected Result**
 The local admin should retain admin permissions after an auth provider is registered. And there must be **one** Rancher user with two principals – local and that of the auth provider, like before.

**Screenshots**

<img width="975" alt="Screen Shot 2022-03-26 at 11 42 35" src="https://user-images.githubusercontent.com/17733533/160246892-26a2db5a-73a6-4cb3-ab2e-1438e66dcb23.png">

**Additional context**

**Comment by MbolotSuse** [comment] 2022-03-26 00:52
With a local cluster of RKE1 version `v1.20.12-rancher1-1` and `v1.22.4-rancher1-1` this is an issue. So this doesn't just affect k8s versions 1.23.

Core issue seems to be related to rancher/rancher#36525 .

I would hazard a guess that the core issue was caused by [this change](https://github.com/rancher/client-go/commit/dd67a97c45a49e995e8552b04541a79c1a792044) in rancher/client-go. In this case, the indexer failed to find the admin user, so it tried to default to using a label on the user which had the hash of the principal ID. This occurs [in the user-manager](https://github.com/rancher/rancher/blob/release/v2.6/pkg/auth/providers/common/usermanager.go#L725). But we don't set that value for the admin user (see the [role-data](https://github.com/rancher/rancher/blob/release/v2.6/pkg/data/management/role_data.go#L533)), so a separate user is created on login. 

The larger concern here is how these indexers may be malfunctioning elsewhere. This could be fixed in this case by properly applying the labels, but other indexers may fail and not have the redundancy to call out to the k8s api in place like this does.

**Comment by MbolotSuse** [comment] 2022-03-26 00:53
@kinarashah Any thoughts on the above?

**Comment by kinarashah** [comment] 2022-03-26 01:23
[This change](https://github.com/rancher/client-go/commit/dd67a97c45a49e995e8552b04541a79c1a792044) was carried forward in the new tag for 1.23 for our custom fork, but it also existed for older versions like [1.22](https://github.com/rancher/client-go/commit/6c1ed77b010c10d12f6f1e5ec2bc4a97b2c61492) and even [1.20](https://github.com/rancher/client-go/commit/2ce1f1f297e24e94533628ca88d583d32cc070cc). This is not to say this is 100% not the root cause, but just that it wasn't introduced for 1.23 as a new change. (maybe we are now able to reproduce it more consistently due to other changes around 1.23)

**Comment by MbolotSuse** [comment] 2022-03-26 21:04
# Validation Template

## Root cause
`EnsureUser` attempts to grab the user from a principal from an indexer upon user login. If it fails, this operations then attempts to use a label with the following key/value `base32EncodePrincipalName: "hashed-principal-name"` to retrieve the user. Unfortunately, the admin user did not have these values set. This causes EnsureUser to create a new user (which is assigned the default roles for the user - standard user in the case of a fresh install) since it is unable to find a user for the principal logging in.

## What was fixed, or what changes have occurred
The admin user was updated to contain the proper key/value pairs. Upon creation, the admin user is retrieved and the labels are added. In addition, on upgrade the existing admin user is retrieved and the labels are added to this user. 

There's also an [ensure-default-admin](https://rancher.com/docs/rancher/v2.6/en/faq/technical/) binary which re-creates/fixes default admins which have been deleted or altered to remove the features required by rancher. This was updated to apply this label as well.

## Areas or cases that should be tested

Test Case 1 (Fresh install):
- Run rancher v2.6.4
- Add a new auth provider (any should work)
- Ensure that the default admin has the labels described above
- Log out
- Click `Log in as local user`
- Log in as the admin user
- Ensure that there is only one user in rancher, and that you can still see all clusters/resources in the UI

Test Case 2 (Upgrade):
- Run rancher v2.6.3
- Add a new auth provider (any should work)
- Upgrade to rancher v2.6.4
- Ensure that the default admin has the labels described above
- Log out
- Click `Log in as local user`
- Log in as the admin user
- Ensure that there is only one user in rancher, and that you can still see all clusters/resources in the UI

Test Case 3 (ensure-default-admin-re-create):
- Run rancher v2.6.4
- Delete the admin user (`kubectl delete user $USER`)
- Exec into the rancher pod/container 
- Run the `ensure-default-admin` tool (`ensure-default-admin`)
- Using the new password and `admin` as the username, log into rancher
- Ensure that the user was recreated, has the label as expected, and has admin permissions

Test Case 4 (ensure-default-admin-fix):
- Run rancher v2.6.4
- Remove the label described above (`base32EncodePrincipalName: "hashed-principal-name"`)
- Exec into the rancher pod/container
- Run the `ensure-default-admin` tool (`ensure-default-admin`)
- Using the new password and `admin` as the username, log into rancher
- Ensure that the user was recreated, has the label as expected, and has admin permissions


## What areas could experience regressions ?

The admin user, and user labels in general.

##Are the repro steps accurate/minimal ?
Yes. They are included here for convenience.

1. Run rancher:v2.6.4-rc13
2. Integrate an auth provider (any should work)
3. Log out of rancher
4. Click `Log in as local user`
5. Login using the admin user
6. Observe that the admin user can no longer view the local cluster
7. Log back in as the openldap admin
8. Observe that there are now two users

**Comment by brudnak** [comment] 2022-03-28 21:00
# :white_check_mark: PASSED

## Reproduction Environment

| Component               | Version / Type                          |
| ----------------------- | --------------------------------------- |
| Rancher version         | 2.6.4-rc13                              |
| Installation option     | Docker                                  |
| Docker version          | 20.10.7, build 20.10.7-0ubuntu5~20.04.2 |
| Helm version            | v2.16.8-rancher1                        |
| Downstream cluster type | not applicable                          |
| Downstream K8s version  | not applicable                          |
| Browser type            | Google Chrome                           |
| Browser version         | 99.0.4844.83 (Official Build) (x86_64)  |

## Reproduction steps

1. Starting from the **default** Rancher homepage `/dashboard/home`
2. Click `Hamburger Menu` -> `Users & Authentication` -> `Auth Provider` -> `OpenLDAP` (or any auth provider) -> fill out the OpenLDAP configuration form
3. Once OpenLDAP is setup, log out
4. Log back in as the local admin user

## Additional Info

When running:

```shell
kubectl get users
```

You can see an additional unwarranted user was created when enabling an auth provider

## RESULTS

#### :white_check_mark: Expected
Able to login as the local admin user

#### :x: Actual
When logging in as the local admin after setting up the auth provider, access to the local cluster is lost

<hr>
  
## Validation Environment

| Component               | Version / Type                                     |
| ----------------------- | -------------------------------------------------- |
| Rancher version         | v2.6-64e916abfb885c136626ed90c657701a7015953f-head |
| Installation option     | Docker                                             |
| Docker version          | 20.10.7, build 20.10.7-0ubuntu5~20.04.2            |
| Helm version            | v2.16.8-rancher1                                   |
| Downstream cluster type | not applicable                                     |
| Downstream K8s version  | not applicable                                     |
| Browser type            | Google Chrome                                      |
| Browser version         | 99.0.4844.83 (Official Build) (x86_64)             |

## Validation steps

1. Starting from the **default** Rancher homepage `/dashboard/home`
2. Click `Hamburger Menu` -> `Users & Authentication` -> `Auth Provider` -> `OpenLDAP` (or any auth provider) -> fill out the OpenLDAP configuration form
3. Once OpenLDAP is setup, log out
4. Log back in as the local admin user

## Additional Info

## RESULTS

#### :white_check_mark: Expected
When logging in as a local admin after enabling an auth provider I expect to see the local cluster

#### :white_check_mark: Actual
When logging in as a local admin after enabling an auth provider the local cluster is visible and the admin, has admin access

**Closed by brudnak** 2022-03-28 21:00 UTC
Labels: kind/bug-qa, [zube]: QA Working, status/final-release-blocker, team/area1
