### ISSUE TITLE
VolumeMounts are not shown in StatefulSet

### ISSUE THREAD

**Issue by k8w** [rancher/rancher#13430] opened 2018-05-11 05:54 UTC
I have a StatefulSet with a `volumeMounts` `redis-data`
```yaml
apiVersion: apps/v1beta2
kind: StatefulSet
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1beta2","kind":"StatefulSet","metadata":{"annotations":{},"labels":{"app":"redis","chart":"redis-3.0.1","heritage":"Tiller","release":"redis"},"name":"redis-master","namespace":"redis"},"spec":{"selector":{"matchLabels":{"app":"redis","release":"redis","role":"master"}},"serviceName":"redis-master","template":{"metadata":{"labels":{"app":"redis","release":"redis","role":"master"}},"spec":{"containers":[{"env":[{"name":"REDIS_REPLICATION_MODE","value":"master"},{"name":"REDIS_PASSWORD","valueFrom":{"secretKeyRef":{"key":"redis-password","name":"redis"}}},{"name":"REDIS_DISABLE_COMMANDS","value":"FLUSHDB,FLUSHALL"}],"image":"docker.io/bitnami/redis:4.0.9","imagePullPolicy":"Always","name":"redis","ports":[{"containerPort":6379,"name":"redis"}],"resources":null,"volumeMounts":[{"mountPath":"/bitnami/redis/data","name":"redis-data","subPath":null}]}],"securityContext":{"fsGroup":1001,"runAsUser":1001}}},"volumeClaimTemplates":[{"metadata":{"labels":{"app":"redis","chart":"redis-3.0.1","component":"master","heritage":"Tiller","release":"redis"},"name":"redis-data"},"spec":{"accessModes":["ReadWriteOnce"],"resources":{"requests":{"storage":"8Gi"}},"storageClassName":"managed-nas-storage"}}]}}
  creationTimestamp: 2018-05-11T04:17:40Z
  generation: 1
  labels:
    app: redis
    chart: redis-3.0.1
    heritage: Tiller
    io.cattle.field/appId: redis
    release: redis
  name: redis-master
  namespace: redis
  resourceVersion: "566089"
  selfLink: /apis/apps/v1beta2/namespaces/redis/statefulsets/redis-master
  uid: 3edda78c-54d2-11e8-9e5c-00163e0ecbe1
spec:
  podManagementPolicy: OrderedReady
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: redis
      release: redis
      role: master
  serviceName: redis-master
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: redis
        release: redis
        role: master
    spec:
      containers:
      - env:
        - name: REDIS_REPLICATION_MODE
          value: master
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              key: redis-password
              name: redis
        - name: REDIS_DISABLE_COMMANDS
          value: FLUSHDB,FLUSHALL
        image: docker.io/bitnami/redis:4.0.9
        imagePullPolicy: Always
        name: redis
        ports:
        - containerPort: 6379
          name: redis
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /bitnami/redis/data
          name: redis-data
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        fsGroup: 1001
        runAsUser: 1001
      terminationGracePeriodSeconds: 30
  updateStrategy:
    rollingUpdate:
      partition: 0
    type: RollingUpdate
  volumeClaimTemplates:
  - metadata:
      creationTimestamp: null
      labels:
        app: redis
        chart: redis-3.0.1
        component: master
        heritage: Tiller
        release: redis
      name: redis-data
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 8Gi
      storageClassName: managed-nas-storage
    status:
      phase: Pending
status:
  collisionCount: 0
  currentReplicas: 1
  currentRevision: redis-master-f864b75fb
  observedGeneration: 1
  readyReplicas: 1
  replicas: 1
  updateRevision: redis-master-f864b75fb
```

But nothing at workload detail page:
![C02c60.png](https://s1.ax1x.com/2018/05/11/C02c60.png)

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v2.0.0` UI: `v2.0.41` | 
|Access|`local` `admin`|
|Route|`workload`|

**Comment by loganhz** [comment] 2018-05-11 06:43
I can reproduce it by deploying a redis app from `Helm Stable`.

The workload of `redis-master` doesn't have `volumes` fields. Show UI can not show it.

I guess we need to fix this issue in backend.

**Comment by guangbochen** [comment] 2018-05-11 07:12
@k8w  The Redis app in the `helm stable` has persistent volume enabled on default `master.persistence.enabled: true`, so you must have PV provisioner support in the underlying infrastructure or disable the pvc by `master.persistence.enabled: false`.

**Comment by k8w** [comment] 2018-05-11 07:15
I'm sure I have `master.persistence.enabled: true`.
And I have checked the PV and PVC works well.
It just cannot see it in the workload detail page.

**Comment by mrfelton** [comment] 2018-08-10 08:07
Same issue using the example:
https://raw.githubusercontent.com/kubernetes/website/master/content/en/examples/application/web/web.yaml

from
https://kubernetes.io/docs/tutorials/stateful-application/basic-stateful-set/

Persistent volumes are created, but the volumes section on the workload edit form shows blank.

**Comment by guangbochen** [comment] 2018-08-10 08:12
this is known UI issue #5278, and you can find the bounded PVc through Volumes tab under the project level menu.

**Comment by Terminator637** [comment] 2018-08-20 12:07
When this bug will be fixed? It makes Rancher UI forms useless for the StatefulSets with volumeClaimTemplates, because creating/editing such StatefulSets through the UI forms gives an error when creating/saving the changes. Editing  through the yaml option works, but UI is more convinient.

**Comment by loganhz** [comment] 2018-08-24 05:26
We will track this issue with https://github.com/rancher/rancher/issues/13374

Moved it to milestone 2.2 (Code freeze for 2.1 is coming soon)

**Closed by loganhz** 2018-08-24 05:26 UTC
Labels: kind/bug, version/2.0
