### ISSUE TITLE
Host Stuck Indefinitely in Removing State

### ISSUE THREAD

**Issue by goffinf** [rancher/rancher#5953] opened 2016-09-12 13:26 UTC
**Rancher Version:**

1.1.0

**Docker Version:**

1.10.3

**OS and where are the hosts located? (cloud, bare metal, etc):**

RHEL 7.2 / AWS

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**

HA
External Db (RDS)

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**

Cattle

**Steps to Reproduce:**

Unknown. The sequence of events was that a host went into 'ReConnecting' state (reason unknown) and on trying to deactivate and then delete that host it has entered 'Removing' state, apparently indefinitely.

**Results:** 

This Rancher forum post (raised by me) explains the situation : https://forums.rancher.com/t/host-stuck-in-removing-state/3878

As mentioned by in another forum post (https://github.com/rancher/rancher/issues/3506), another Rancher user decided to hack the Rancher Db to resolve the same problem. I could try that, but I’m a bit reluctant to do so unless there is no other choice.

The host in 'Removing' state has now been so for more than a week and it has become a high priority problem, hence escalating as an issue rather than just a forum topic.

**Expected:**

Clean removal of the Rancher host.

**Comment by ibuildthecloud** [comment] 2016-09-12 22:29
Can you go to `Admin->Process` in the UI and look for a `host.remove` process that has been running for a long time.  If you click on it the next screen should show a bunch of executions.  If you click expand all on one of them you should get the call tree of what it was doing.  Also click the "hazard" looking icon and it should show an exception.  Can you send screen shots of that stuff?

**Comment by goffinf** [comment] 2016-09-13 00:09
Hey Darren,

please find attached screen shots -

- Hosts_Demo.jpg

This shows the hosts from the demo environment. I have highlighted the host (one of the LOAD-BALANCER) that is stuck in the Removing state (its been like that for over a week).  The other hosts (HOST_TYPE=HOST) I guess are shown as re-connecting because they are stopped overnight on a schedule (note all are EC2 instancs in AWS) and will come back up again in the morning. TBH its the first time I have seen this !

- processes.jpg

From Admin -> Processes  (again a first for me). I hadn't realised there would as many (probably around 40 !) I have highlighted the 3 that relate to the host.remove per your request. As you can see they are 11 days old. Only the third had any detail (the first 2 just reported the process id). 

- Stack_Trace.jpg

There are a LOT of child execution details here albeit the last suggests is was a 'day ago' so I don't know if they rotate ?. Anyway, there were only 2 which showed up as RED and both appeared to have the same stack trace.

The cause was : io.cattle.platform.engine.process.impl.ProcessExecutionExitException

PROCESS_ALREADY_IN_PROGRESS ?

HTHs

Fraser.


![hosts_demo](https://cloud.githubusercontent.com/assets/2772752/18457163/4e7b1288-794e-11e6-9126-7f9ab8d44707.jpg)

![processes](https://cloud.githubusercontent.com/assets/2772752/18457164/53b690ba-794e-11e6-81ff-f6c09a05385e.jpg)

![stack_trace](https://cloud.githubusercontent.com/assets/2772752/18457168/598b4a4e-794e-11e6-96d4-0358d26d391a.jpg)

**Comment by goffinf** [comment] 2016-09-13 00:09
Sorry didn't mean to close it !

**Comment by goffinf** [comment] 2016-09-13 22:22
Hey Darren, yeah sure :-)

![stack_trace2](https://cloud.githubusercontent.com/assets/2772752/18493528/f3d894a2-7a08-11e6-88fb-04b8849cf6fe.jpg)

**Comment by goffinf** [comment] 2016-09-16 07:17
Any further information or advice ? This issue is now blocking all deployments using Rancher and we have been forced to just use native Docker.

**Comment by ibuildthecloud** [comment] 2016-09-16 12:57
@goffinf This is an odd one.  The best thing would be if you can send me a DB dump.  That might have more information in it that you care to share.  In that case if you could just share the process_execution and process_instances tables that would help.  Those tables don't have any sensitive info in them.  You can email the dump directly to me darren@rancher.com

Full Dump

    mysqldump -ucattle -p cattle  > dump.sql

Just the two tables

    mysqldump -ucattle -p cattle process_execution process_instance > dump.sql

**Comment by sangeethah** [comment] 2016-09-20 22:26
@ibuildthecloud, could you let me know the exact steps that can cause the host to be stuck in "removing" state ?

**Comment by ibuildthecloud** [comment] 2016-09-20 23:04
@sangeethah The situation is when the network agent is in a restarting state and you go to remove a host.  I'm not sure how to exactly reproduce it.  I just know a restarting network agent is stuck because the host is removing and the host is stuck removing because the network agent is restarting.

**Comment by sangeethah** [comment] 2016-09-22 04:54
Tested with rancher-server version - v1.1.4-rc3

Tested the following scenario multiple times and host got to "removed" state without being stuck in "removing" state forever:

Restart network Agent. When Network agent is still in restarting state , remove the host.
Host removal was successful.

Closing this issue for now.

@goffinf: This issue should be fixed with v1.1.4-rc3 . Could you please upgrade to 1.1.4 (should be available in the next few days)  and see if this issue is not seen anymore for you.

**Closed by sangeethah** 2016-09-22 04:54 UTC
Labels: kind/bug, status/to-test

**Comment by goffinf** [comment] 2016-09-22 07:21
Indeed, we are eagerly awaiting the 1.14 drop (can't go with release candidates other than in our sandbox).

On a more general note, the whole experience of working thru this issue has been very positive. Not only has the principle problem been resolved but also a couple of other pending issues identified and remedied. I would encourage anyone using Rancher to contribute, you are likely to get more than you bargained for ... in a good way :-)
