### ISSUE TITLE
Rancher crashes after adding a catalog containing a chart with missing name and version

### ISSUE THREAD

**Issue by axeal** [rancher/rancher#28776] opened 2020-09-07 13:40 UTC
**What kind of request is this (question/bug/enhancement/feature request):**

Bug

**Steps to reproduce (least amount of steps as possible):**

1. Provision a Rancher v2.4.8 instance with a single all role node custom cluster (I used https://github.com/superseb/tf-do-rancher2/)
2. Add a cluster-scoped catalog containing a chart with a missing name and version in the Chart.yaml file (I used https://github.com/axeal/rancher-catalog/tree/noversion)

**Result:**

Rancher containers enters a crash loop with the following error in the logs:

```
2020/09/07 12:09:33 [ERROR] ClusterCatalogController c-79crj/test-catalog [clusterCatalog] failed with : failed to update templates. Multiple error(s) occurred: [CatalogTemplateVersion.management.cattle.io "test-catalog-" is invalid: metadata.name: Invalid value: "test-catalog-": a DNS-1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*')];
panic: interface conversion: interface {} is nil, not string

goroutine 9683 [running]:
github.com/rancher/rancher/pkg/api/customization/catalog.(*templateStore).extractVersionLinks(0xc00043d480, 0xc0045cc000, 0xc007db21b0, 0xc0065c5db8)
	/go/src/github.com/rancher/rancher/pkg/api/customization/catalog/store.go:59 +0x5bb
github.com/rancher/rancher/pkg/api/customization/catalog.GetTemplateStore.func1(0xc0045cc000, 0xc0009c6b40, 0xc007db21b0, 0xc005e40380, 0xc0074cefa8, 0xcfa401, 0x101)
	/go/src/github.com/rancher/rancher/pkg/api/customization/catalog/store.go:39 +0x42
github.com/rancher/rancher/vendor/github.com/rancher/norman/store/transform.(*Store).Watch.func1(0xc007db21b0, 0xc0074cefa8)
	/go/src/github.com/rancher/rancher/vendor/github.com/rancher/norman/store/transform/transform.go:58 +0x4e
github.com/rancher/rancher/vendor/github.com/rancher/norman/types/convert.Chan.func1(0xc0071a5980, 0xc006b71080, 0xc0071a59e0)
	/go/src/github.com/rancher/rancher/vendor/github.com/rancher/norman/types/convert/convert.go:21 +0x65
created by github.com/rancher/rancher/vendor/github.com/rancher/norman/types/convert.Chan
	/go/src/github.com/rancher/rancher/vendor/github.com/rancher/norman/types/convert/convert.go:19 +0x7f
```

**Environment information**
- Reproduced in Rancher v2.4.4 (user version) and v2.4.8

gz#12104

**Comment by axeal** [comment] 2020-11-16 08:59
Reproduced error with above steps in the Cluster Manager UI using Rancher v2.5.2. Issue does not occur when adding the catalog with the erroneous chart via the Cluster Explorer UI (https://rancher.com/docs/rancher/v2.x/en/helm-charts/apps-marketplace/) in v2.5.2.

**Comment by Jono-SUSE-Rancher** [comment] 2021-03-30 17:59
To whoever picks this up, you might want to follow-up with @brendarearden as we believe that she did something similar in the past when a catalog was added with something invalid within one of the charts.

**Comment by hoang-hai** [comment] 2021-05-29 08:30
hi, is there any way to fix this issue?

**Comment by Tejeev** [comment] 2021-08-24 10:07
We see the exact same issue where someone had added a blank chart (directory with a blank chart.yaml) to the repo in GitLab. 
This was worked around by filling in the chart.yaml with real values, but could have presumably been "resolved" by removing the blank chart from the repo as well.
We are currently seeing that we can not upgrade any apps in Manager but not yet sure if this is related.  
Rancher containers are crashlooping with the below error:
```
2021/08/24 09:40:32 [INFO] Starting rbac.authorization.k8s.io/v1, Kind=RoleBinding controller
2021/08/24 09:40:32 [INFO] Starting cluster agent for c-48tzt [owner=false]
2021/08/24 09:40:32 [INFO] Starting rbac.authorization.k8s.io/v1, Kind=Role controller
2021/08/24 09:40:32 [INFO] Starting /v1, Kind=Endpoints controller
2021/08/24 09:40:32 [INFO] Starting cluster agent for c-wfqrm [owner=false]
2021/08/24 09:40:32 [INFO] Starting /v1, Kind=Namespace controller
2021/08/24 09:40:32 [INFO] Starting /v1, Kind=Service controller
2021/08/24 09:40:32 [INFO] Starting apiregistration.k8s.io/v1, Kind=APIService controller
2021/08/24 09:40:32 [INFO] Starting rbac.authorization.k8s.io/v1, Kind=RoleBinding controller
2021/08/24 09:40:32 [INFO] Starting /v1, Kind=Pod controller
2021/08/24 09:40:32 [INFO] Starting rbac.authorization.k8s.io/v1, Kind=ClusterRole controller
2021/08/24 09:40:32 [INFO] Starting /v1, Kind=Endpoints controller
2021/08/24 09:40:32 [INFO] Starting rbac.authorization.k8s.io/v1, Kind=Role controller
2021/08/24 09:40:32 [INFO] Starting rbac.authorization.k8s.io/v1, Kind=ClusterRoleBinding controller
goroutine 32407 [running]:
github.com/rancher/rancher/pkg/api/norman/customization/catalog.(*templateStore).extractVersionLinks(0xc007b18630, 0xc02732bd40, 0xc006853d70, 0xc012139588)
       /go/src/github.com/rancher/rancher/pkg/api/norman/customization/catalog/store.go:62 +0x642
github.com/rancher/rancher/pkg/api/norman/customization/catalog.GetTemplateStore.func1(0xc02732bd40, 0xc00a9bcb40, 0xc006853d70, 0xc0129baa80, 0xc00c0d1fa8, 0x13a1e01, 0x101)
       /go/src/github.com/rancher/rancher/pkg/api/norman/customization/catalog/store.go:42 +0x42
github.com/rancher/norman/store/transform.(*Store).Watch.func1(0xc006853d70, 0xc00c0d1fa8)
       /go/pkg/mod/github.com/rancher/norman@v0.0.0-20210225010917-c7fd1e24145b/store/transform/transform.go:58 +0x4e
github.com/rancher/norman/types/convert.Chan.func1(0xc027323500, 0xc027365110, 0xc027323560)
       /go/pkg/mod/github.com/rancher/norman@v0.0.0-20210225010917-c7fd1e24145b/types/convert/convert.go:21 +0x65
created by github.com/rancher/norman/types/convert.Chan
       /go/pkg/mod/github.com/rancher/norman@v0.0.0-20210225010917-c7fd1e24145b/types/convert/convert.go:19 +0x7f
```

**Comment by genexpr** [comment] 2021-09-15 21:10
Reproduced under 2.4.17 and 2.5.9 both locally and in Docker containers.
Cannot reproduce under 2.6.0 neither locally nor in Docker.

The `extractVersionLinks` method on `TemplateStore` is the same in versions 2.4, 2.5, 2.6.
If a `version` field is missing in a `Chart.yaml` file, there is a runtime panic, since the code assumes the field always exists and attempts to perform a type assertion without checking if it succeeds. This method is never run on catalog add in 2.6, hence there is no panic.

We can fix type assertion checks in the method, but it would be good to understand first how 2.6 works when it creates a chart repository and why there are no errors. Will try to find the portion of the code which runs in this situation under 2.6. Will also have to add a check to ensure the `name` field exists. We don't seem to check it, but the name must be required.

**Comment by genexpr** [comment] 2021-09-15 23:13
In 2.6, adding a repo with a blank chart does not trigger a panic. There aren't even logged errors. The blank chart will simply not appear in a list of charts belonging to the repo. Whether a user should be alerted to this is probably another issue. But the bug is not found in 2.6. The code handling adding a new chart repo is different from that in 2.5.

The panic occurs in 2.4 and 2.5. This hasn't been marked as critical for 2.4, so the fix could target only 2.5. However, the code handling the old behavior still exists in 2.6, even if it's not run in this situation, so it might be useful to fix it in 2.6 as well, to prevent issues in the future, if that `extractVersionLinks` method gets called elsewhere.

**Comment by genexpr** [comment] 2021-09-17 00:07
Turns out, the issue appears in the old UI, so it's reproducible in 2.4, 2.5, 2.6. We should ignore charts that don't have the `version` field. 

Currently, we also don't check if the `name` field is present. But there are no errors or unexpected behavior because of it, as I verified. Spoke with @StrongMonkey and concluded that we should only modify the existing behavior of `version` extraction for each chart on repo addition.

**Comment by genexpr** [comment] 2021-09-20 18:30
### QA testing

Go to the old UI: `https://{your-cluster-url}/g`.
In the context of any cluster, add a new catalog. Give it a name and choose a repository that contains a bad chart definition. A bad chart definition in this case is one whose `Chart.yaml` is missing the `version` field. There is one that is good for testing: https://github.com/axeal/rancher-catalog

Use the above Catalog URL and select a branch that has an invalid `Chart.yaml`. In this case, the branch `noversion`. Then click Create and observe that there are no errors in the cluster. The catalog is added. It only contains one chart, and this chart is invalid. This means that when you try to add an App to a Project, this repository (catalog) you had added will not appear in the list of available catalogs, since it does not have any valid charts.

Add another catalog. Use the same Catalog URL but choose a branch that contains that same chart definition but in a valid form - the `master` branch. When you Create the new catalog, you will also not see any errors. But when you try to add an App, you will see your catalog with its charts (one, in this case) listed in the list of available catalogs.

**Comment by ryansann** [comment] 2021-09-28 00:54
I've validated that we are no longer displaying apps that have an invalid chart on v2.6-head (`06e19b0`). 

Steps followed:
1. Create cluster scoped catalog with https://github.com/axeal/rancher-catalog and branch=`noversion`
2. Observe no catalog related error logs
3. Observe no `json-exporter` app when navigating to launch an app in the cluster
4. Edit previously created catalog and change to branch=`master`
5. Observe the app now appears in the catalog

**Closed** 2021-09-29 22:49 UTC
Labels: kind/bug, priority/0, internal, [zube]: QA Working, status/dev-validate, kind/good-first-issue
