### ISSUE TITLE
concurrent map read/write in authprovisoningv2 controller

### ISSUE THREAD

**Issue by rosskirkpat** [rancher/rancher#37536] opened 2022-04-29 16:55 UTC
Drone provisioning tests are failing due to a concurrent map read/write. https://drone-pr.rancher.io/rancher/rancher/22127/1/2

**Rancher Server Setup**
- Rancher version: v2.6-head

Command used to extract the panic: 
`for CHUNK in $(grep -A1 LOG-DUMP-START Downloads/logs_rancher_rancher_22127_1_2.log | grep -v LOG-DUMP); do echo -e "\n---\nSTART LOG DUMP\n---\n"; echo -n "${CHUNK}" | base64 -d | zcat; done | less -S`

```console
2022/04/29 15:50:35 [ERROR] error syncing 'p-8hn85/creator-project-owner': handler mgmt-auth-prtb-controller: users.management.cattle.io "system:admin" not found, requeuing
fatal error: concurrent map read and map write

goroutine 31626 [running]:
runtime.throw({0x4057ac5, 0x110})
        /usr/lib64/go/1.17/src/runtime/panic.go:1198 +0x71 fp=0xc004bc9648 sp=0xc004bc9618 pc=0x4371f1
runtime.mapaccess2_faststr(0x8fe532, 0xc004bc9748, {0x3fd9225, 0xa})
        /usr/lib64/go/1.17/src/runtime/map_faststr.go:116 +0x3d4 fp=0xc004bc96b0 sp=0xc004bc9648 pc=0x412ed4
k8s.io/apimachinery/pkg/apis/meta/v1/unstructured.NestedFieldNoCopy(0x46b4c7, {0xc004bc9820, 0x1, 0x1})
        /go/pkg/mod/k8s.io/apimachinery@v0.23.3/pkg/apis/meta/v1/unstructured/helpers.go:61 +0xdf fp=0xc004bc9738 sp=0xc004bc96b0 pc=0xcd01bf
k8s.io/apimachinery/pkg/apis/meta/v1/unstructured.NestedString(0xed9fe004b, {0xc004bc9820, 0x1, 0x1})
        /go/pkg/mod/k8s.io/apimachinery@v0.23.3/pkg/apis/meta/v1/unstructured/helpers.go:75 +0x35 fp=0xc004bc97b0 sp=0xc004bc9738 pc=0xcd0375
k8s.io/apimachinery/pkg/apis/meta/v1/unstructured.getNestedString(0x4021501, {0xc004bc9820, 0x0, 0xc004bc9838})
        /go/pkg/mod/k8s.io/apimachinery@v0.23.3/pkg/apis/meta/v1/unstructured/helpers.go:278 +0x1e fp=0xc004bc97e0 sp=0xc004bc97b0 pc=0xcd1afe
k8s.io/apimachinery/pkg/apis/meta/v1/unstructured.(*Unstructured).GetAPIVersion(...)
        /go/pkg/mod/k8s.io/apimachinery@v0.23.3/pkg/apis/meta/v1/unstructured/unstructured.go:218
k8s.io/apimachinery/pkg/apis/meta/v1/unstructured.(*Unstructured).GroupVersionKind(0xc005047230)
        /go/pkg/mod/k8s.io/apimachinery@v0.23.3/pkg/apis/meta/v1/unstructured/unstructured.go:426 +0x7c fp=0xc004bc98a0 sp=0xc004bc97e0 pc=0xcd64dc
github.com/rancher/rancher/pkg/controllers/management/authprovisioningv2.getObjectClusterNames({0x47b8f28, 0xc005047230})
        /go/src/github.com/rancher/rancher/pkg/controllers/management/authprovisioningv2/indexer.go:33 +0x1ce fp=0xc004bc9a10 sp=0xc004bc98a0 pc=0x24a578e
github.com/rancher/rancher/pkg/controllers/management/authprovisioningv2.(*handler).OnClusterObjectChanged(0xc00379f760, {0x47b8f28, 0xc005047230})
        /go/src/github.com/rancher/rancher/pkg/controllers/management/authprovisioningv2/role.go:109 +0x4e fp=0xc004bc9ab0 sp=0xc004bc9a10 pc=0x24a88ce
github.com/rancher/rancher/pkg/controllers/management/authprovisioningv2.(*handler).OnClusterObjectChanged-fm({0x47b8f28, 0xc005047230})
        /go/src/github.com/rancher/rancher/pkg/controllers/management/authprovisioningv2/role.go:108 +0x39 fp=0xc004bc9ad8 sp=0xc004bc9ab0 pc=0x24aaeb9
github.com/rancher/lasso/pkg/dynamic.wrap.func1({0x28fae79a, 0x10a4fd39618}, {0x47b8f28, 0xc005047230})
        /go/pkg/mod/github.com/rancher/lasso@v0.0.0-20220412224715-5f3517291ad4/pkg/dynamic/controller.go:400 +0x116 fp=0xc004bc9b88 sp=0xc004bc9ad8 pc=0x1b95f96
github.com/rancher/lasso/pkg/controller.SharedControllerHandlerFunc.OnChange(0x3f86080, {0xc002cc9e00, 0x3fddaec}, {0x47b8f28, 0xc005047230})
        /go/pkg/mod/github.com/rancher/lasso@v0.0.0-20220412224715-5f3517291ad4/pkg/controller/sharedcontroller.go:29 +0x38 fp=0xc004bc9bb8 sp=0xc004bc9b88 pc=0x1288718
github.com/rancher/lasso/pkg/controller.(*SharedHandler).OnChange(0xc000292378, {0xc002cc9e00, 0x4a}, {0x47b8f28, 0xc005047230})
        /go/pkg/mod/github.com/rancher/lasso@v0.0.0-20220412224715-5f3517291ad4/pkg/controller/sharedhandler.go:75 +0x23f fp=0xc004bc9ce0 sp=0xc004bc9bb8 pc=0x128b9bf
github.com/rancher/lasso/pkg/controller.(*controller).syncHandler(0xc000e3c630, {0xc002cc9e00, 0x4a})
        /go/pkg/mod/github.com/rancher/lasso@v0.0.0-20220412224715-5f3517291ad4/pkg/controller/controller.go:220 +0x93 fp=0xc004bc9d30 sp=0xc004bc9ce0 pc=0x1287ab3
github.com/rancher/lasso/pkg/controller.(*controller).processSingleItem(0xc000e3c630, {0x35bb8c0, 0xc0016c7c40})
        /go/pkg/mod/github.com/rancher/lasso@v0.0.0-20220412224715-5f3517291ad4/pkg/controller/controller.go:201 +0x10e fp=0xc004bc9e08 sp=0xc004bc9d30 pc=0x128776e
github.com/rancher/lasso/pkg/controller.(*controller).processNextWorkItem(0xc000e3c630)
        /go/pkg/mod/github.com/rancher/lasso@v0.0.0-20220412224715-5f3517291ad4/pkg/controller/controller.go:178 +0x46 fp=0xc004bc9e50 sp=0xc004bc9e08 pc=0x1287566
github.com/rancher/lasso/pkg/controller.(*controller).runWorker(...)
        /go/pkg/mod/github.com/rancher/lasso@v0.0.0-20220412224715-5f3517291ad4/pkg/controller/controller.go:167
github.com/rancher/lasso/pkg/controller.(*controller).runWorker-fm()
        /go/pkg/mod/github.com/rancher/lasso@v0.0.0-20220412224715-5f3517291ad4/pkg/controller/controller.go:166 +0x32 fp=0xc004bc9e70 sp=0xc004bc9e50 pc=0x128c7b2
k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0x7fa1786e1978)
        /go/pkg/mod/k8s.io/apimachinery@v0.23.3/pkg/util/wait/wait.go:155 +0x67 fp=0xc004bc9eb0 sp=0xc004bc9e70 pc=0xc89dc7
k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0x3533240, {0x4785f00, 0xc008d62bd0}, 0x1, 0xc002114960)
        /go/pkg/mod/k8s.io/apimachinery@v0.23.3/pkg/util/wait/wait.go:156 +0xb6 fp=0xc004bc9f30 sp=0xc004bc9eb0 pc=0xc89c36
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0x0, 0x3b9aca00, 0x0, 0x1, 0x440c45)
        /go/pkg/mod/k8s.io/apimachinery@v0.23.3/pkg/util/wait/wait.go:133 +0x89 fp=0xc004bc9f80 sp=0xc004bc9f30 pc=0xc89b29
k8s.io/apimachinery/pkg/util/wait.Until(0x0, 0xc0086b3ec0, 0x0)
        /go/pkg/mod/k8s.io/apimachinery@v0.23.3/pkg/util/wait/wait.go:90 +0x25 fp=0xc004bc9fb8 sp=0xc004bc9f80 pc=0xc89a65
github.com/rancher/lasso/pkg/controller.(*controller).run·dwrap·2()
        /go/pkg/mod/github.com/rancher/lasso@v0.0.0-20220412224715-5f3517291ad4/pkg/controller/controller.go:135 +0x2e fp=0xc004bc9fe0 sp=0xc004bc9fb8 pc=0x128702e
runtime.goexit()
        /usr/lib64/go/1.17/src/runtime/asm_amd64.s:1581 +0x1 fp=0xc004bc9fe8 sp=0xc004bc9fe0 pc=0x46b381
created by github.com/rancher/lasso/pkg/controller.(*controller).run
        /go/pkg/mod/github.com/rancher/lasso@v0.0.0-20220412224715-5f3517291ad4/pkg/controller/controller.go:135 +0x2c6
```

**Comment by brandond** [comment] 2022-04-29 16:59
something in the path from
https://github.com/rancher/rancher/blob/a01b164f2e371f04aea7c0c1864c687b8ad70cca/pkg/controllers/management/authprovisioningv2/role.go#L108-L109 to
https://github.com/rancher/rancher/blob/a01b164f2e371f04aea7c0c1864c687b8ad70cca/pkg/controllers/management/authprovisioningv2/indexer.go#L33
is causing a crash... not sure if there's a missing nil check, or perhaps the handler is running before the indexer is syncd, or what.

**Comment by kinarashah** [comment] 2022-04-29 17:42
https://github.com/rancher/rancher/issues/36845

**Comment by kinarashah** [comment] 2022-04-29 17:44
Duplicate of https://github.com/rancher/rancher/issues/36845.

**Closed by kinarashah** 2022-04-29 17:44 UTC
Labels: area/authentication, kind/bug-qa, area/provisioning-v2, team/area2, area/clusterprovisioningv2
