### ISSUE TITLE
Can't access load balancer in UI, but can via compose

### ISSUE THREAD

**Issue by ndarilek** [rancher/rancher#2211] opened 2015-10-01 19:54 UTC
If I click on a load balancer that has been activated, I get an "Unknown link" error. I can successfully interact with the balancer via rancher-compose, but not via the link to it in the UI.

If I create the balancer and click on it before it is activated, I can reach it. But as soon as it is active, the page reports the error and I can no longer examine it via the web UI.

**Comment by deniseschannon** [comment] 2015-10-01 21:54
@ndarilek Can you confirm that you are logged in as a user and not an admin?

**Comment by ndarilek** [comment] 2015-10-01 21:58
I'm confused, aren't all admins users, so I couldn't be logged in as an 
admin if I wasn't a user?

I can probably still answer this question. My installation only has a 
single user at this time, my own, and it is an admin. I was able to do 
this under 0.37, but not under 0.39.1. And it can access an inactive 
load balancer, but as soon as that balancer is active, the link to it 
errors out. If I then deactivate the balancer via `rancher-compose 
down`, I can visit the link again.

**Comment by deniseschannon** [comment] 2015-10-01 22:06
we have users and admins that have different access. admins get access ot the admin tab. 

But @aruneli has confirmed that it's for all users/admins. @ndarilek Sorry for the confusion. 

@aruneli will provide more details on how to reproduce.

**Comment by deniseschannon** [comment] 2015-10-01 22:16
Issue reproduced in v0.40.0 -rc1 
Steps to Reproduce:

1. Create a LB
2. Start the LB
3. Click on LB name

Result: Directed to "Error, Unknown Link" page (outside of Rancher)

Expected Result: Details of LB page

**Comment by vincent99** [comment] 2015-10-01 22:54
This is blowing up because there are no `containerStats` available for balancer services for some reason.  Changed to not blow up for now, but the stats should be added as a followup.

**Comment by aruneli** [comment] 2015-10-02 16:39
```
Component 	Version
Rancher 	v0.40.0-rc2
Cattle 	v0.96.0
User Interface 	v0.54.0
Rancher Compose 	beta/latest
```
Verified that I can access load balancer page but since stats is empty, assigning it to @wlan0 for the fix.

**Closed** 2015-10-02 16:43 UTC
Labels: area/ui, kind/bug, status/resolved, status/to-test
