### ISSUE TITLE
Auto creation of xip.io sub domains break when vsphere cloud-provider is specified 

### ISSUE THREAD

**Issue by svagml** [rancher/rancher#15353] opened 2018-08-31 17:51 UTC
**Rancher versions:**
rancher/server or rancher/rancher:
rancher/rancher:latest

rancher/agent or rancher/rancher-agent:
?
rancher/rke-tools:v0.1.13

**Infrastructure Stack versions:**
healthcheck: ?
ipsec: ?
network-services: ?
scheduler: ?
kubernetes (if applicable):
v1.11.1-rancher1-1

**Docker version: (`docker version`,`docker info` preferred)**
Client:
 Version:      17.03.2-ce
 API version:  1.27
 Go version:   go1.7.5
 Git commit:   f5ec1e2
 Built:        Tue Jun 27 01:35:00 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.03.2-ce
 API version:  1.27 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   f5ec1e2
 Built:        Tue Jun 27 01:35:00 2017
 OS/Arch:      linux/amd64
 Experimental: false

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
RancherOS v1.4.0
4.14.32-rancher2

NAME="RancherOS"
VERSION=v1.4.0
ID=rancheros
ID_LIKE=
VERSION_ID=v1.4.0
PRETTY_NAME="RancherOS v1.4.0"
HOME_URL="http://rancher.com/rancher-os/"
SUPPORT_URL="https://forums.rancher.com/c/rancher-os"
BUG_REPORT_URL="https://github.com/rancher/os/issues"
BUILD_ID=

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
vsphere 6.7
single esxi host 6.5

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
single node rancher

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**
rancher 2, so kubernetes

**Steps to Reproduce:**
Creating or editing a cluster to add vsphere cloud_providor.

My stanza added via clicking on "edit yaml":
cloud_provider: 
  name: "vsphere"
  vsphereCloudProvider: 
    global: 
      insecure-flag: true
      soap-roundtrip-count: 0
    virtual_center: 
      10.0.0.21: 
        datacenters: "Cybertron"
        password: "password"
        soap-roundtrip-count: 0
        user: "administrator@vsphere.local"
    workspace: 
      datacenter: "Cybertron"
      default-datastore: "P410_SSD_RAID5"
      folder: "/"
      server: "vcenter.transformers.lan"

(I never added the soup directives as they were auto added by the system)

**Results:**
Breaks auto creation of xip.io sub domains.  It doesn't break existing apps/workload, after adding the stanza and deploying a new app, no more auto creation.  It appears to still make the discoveries though.

**Comment by deniseschannon** [comment] 2019-04-12 00:19
DUplicate of https://github.com/rancher/rancher/issues/14960

**Closed by deniseschannon** 2019-04-12 00:19 UTC
Labels: area/vsphere, status/investigate
