### ISSUE TITLE
"Unexpected end of JSON input" error seen when deploying a GKE v2 cluster through API

### ISSUE THREAD

**Issue by sowmyav27** [rancher/rancher#31958] opened 2021-04-07 00:52 UTC
**What kind of request is this (question/bug/enhancement/feature request):** bug

**Steps to reproduce (least amount of steps as possible):**

- Deploy a GKE v2 cluster using Rancher API -- `/v3/clusters` --> create
- Give in the follwing in gkeConfig, a cluster name and deploy

[gke.json.zip](https://github.com/rancher/rancher/files/6268206/gke.json.zip)
[gke.json 2.zip](https://github.com/rancher/rancher/files/6268478/gke.json.2.zip)

- GKE-operator throws error
```
time="2021-04-07T00:41:02Z" level=error msg="error syncing 'cattle-global-data/c-hlt2g': handler gke-controller: unexpected end of JSON input, requeuing"
time="2021-04-07T00:43:46Z" level=error msg="error syncing 'cattle-global-data/c-hlt2g': handler gke-controller: unexpected end of JSON input, requeuing"
time="2021-04-07T00:49:14Z" level=error msg="error syncing 'cattle-global-data/c-hlt2g': handler gke-controller: unexpected end of JSON input, requeuing"
```
- Cluster is stuck in provisioning with error `Unexpected end of JSON input`

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): 2.5-head commit id: `4115dee` and `rancher/gke-operator:v1.0.1-rc4`
- Installation option (single install/HA): Single

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): Hosted GKEv2

**Comment by cmurphy** [comment] 2021-04-07 16:56
Can you check what version of gke-operator is running:

`kubectl -n cattle-system get deploy gke-config-operator -o jsonpath='{.spec.template.spec.containers[0].image}'`

**Comment by aaronRancher** [comment] 2021-04-08 00:28
Tested on Rancher `v2.5-head` `version 7426ba8`
GKE operator: `v1.0.1-rc6`

Deploy a GKE v2 cluster using Rancher API -- /v3/clusters --> create
Give in the following in gkeConfig, a cluster name and deploy hosted GKE v2 cluster
[gke 4.json.zip](https://github.com/rancher/rancher/files/6275176/gke.4.json.zip)

For imported GKE cluster, provide the following in gkeConfig:
```
{
  "clusterName": "aaron-test",
  "displayName": "aaron-test",
  "googleCredentialSecret": "cattle-global-data:cc-dg229",
  "imported": true,
  "projectID": "rancher-qa",
  "region": "us-central1-c"
}
```


Errors from Rancher server while provisioning both imported and hosted cluster:
```
2021/04/08 00:22:38 [INFO] waiting for cluster GKE [c-bh5cl] pre-create failure to be resolved
W0408 00:22:39.589838      10 warnings.go:80] apiextensions.k8s.io/v1beta1 CustomResourceDefinition is deprecated in v1.16+, unavailable in v1.22+; use apiextensions.k8s.io/v1 CustomResourceDefinition
2021/04/08 00:22:39 [INFO] waiting for cluster create [c-b7bzq] to start
2021/04/08 00:22:39 [INFO] waiting for cluster GKE [c-b7bzq] pre-create failure to be resolved
2021/04/08 00:22:43 [INFO] waiting for cluster import [c-bh5cl] to start
2021/04/08 00:22:43 [INFO] waiting for cluster GKE [c-bh5cl] pre-create failure to be resolved
2021/04/08 00:22:44 [INFO] waiting for cluster create [c-b7bzq] to start
```

**Comment by aaronRancher** [comment] 2021-04-08 00:40
Tested on Rancher `master-head` `version f5393c2`. GKE operator version `v1.0.1-rc6`
Ran the same steps as above for hosted and imported GKE v2 cluster. And saw different results.

The imported cluster was provisioned successfully, but became stuck in updating state: `Waiting for nodes`
The hosted cluster errors with: `Field [management] cannot be nil for nodepool [example-node-pool] in non-nil cluster [aaron-gke]` (cluster id: c-w4rqk)

Rancher server logs:
```
2021/04/08 00:37:24 [INFO] waiting for cluster GKE [c-w4rqk] pre-create failure to be resolved
I0408 00:37:28.433628      28 topology_manager.go:221] [topologymanager] RemoveContainer - Container ID: 3d03b042dd68bad367cbdd2f84dca560d81e477e9272f225912bc8354ac924e6
2021/04/08 00:37:29 [INFO] waiting for cluster create [c-w4rqk] to start
2021/04/08 00:37:29 [INFO] waiting for cluster GKE [c-w4rqk] pre-create failure to be resolved
W0408 00:37:34.105321      11 warnings.go:80] extensions/v1beta1 Ingress is deprecated in v1.14+, unavailable in v1.22+; use networking.k8s.io/v1 Ingress
2021/04/08 00:37:34 [INFO] waiting for cluster create [c-w4rqk] to start
2021/04/08 00:37:34 [INFO] waiting for cluster GKE [c-w4rqk] pre-create failure to be resolved
2021/04/08 00:37:39 [INFO] waiting for cluster create [c-w4rqk] to start
2021/04/08 00:37:39 [INFO] waiting for cluster GKE [c-w4rqk] pre-create failure to be resolved
I0408 00:37:44.733064      28 request.go:645] Throttling request took 1.041176253s, request: GET:https://127.0.0.1:6444/apis/management.cattle.io/v3?timeout=32s
2021/04/08 00:37:44 [INFO] waiting for cluster create [c-w4rqk] to start
2021/04/08 00:37:44 [INFO] waiting for cluster GKE [c-w4rqk] pre-create failure to be resolved
2021/04/08 00:37:49 [INFO] waiting for cluster create [c-w4rqk] to start
2021/04/08 00:37:49 [INFO] waiting for cluster GKE [c-w4rqk] pre-create failure to be resolved
```

GKE operator logs:
```
time="2021-04-08T00:32:55Z" level=error msg="error syncing 'cattle-global-data/c-w4rqk': handler gke-controller: field [management] cannot be nil for nodepool [example-node-pool] in non-nil cluster [aaron-gke], requeuing"
time="2021-04-08T00:33:36Z" level=error msg="error syncing 'cattle-global-data/c-w4rqk': handler gke-controller: field [management] cannot be nil for nodepool [example-node-pool] in non-nil cluster [aaron-gke], requeuing"
time="2021-04-08T00:34:58Z" level=error msg="error syncing 'cattle-global-data/c-w4rqk': handler gke-controller: field [management] cannot be nil for nodepool [example-node-pool] in non-nil cluster [aaron-gke], requeuing"
time="2021-04-08T00:37:42Z" level=error msg="error syncing 'cattle-global-data/c-w4rqk': handler gke-controller: field [management] cannot be nil for nodepool [example-node-pool] in non-nil cluster [aaron-gke], requeuing"
```

**Comment by sowmyav27** [comment] 2021-04-08 01:28
@aaronRancher [this](https://github.com/rancher/rancher/issues/31958#issuecomment-815364584) is expected as per discussion with @cmurphy because the json file (gkeConfig) has to be updated.

**Comment by aaronRancher** [comment] 2021-04-09 23:27
This issue was caused by the way Google cloud credentials were being created. In 2.5-head, Google cloud credential was not available because of this issue: https://github.com/rancher/rancher/issues/31983
Creating a Google cloud credential through the API UI would result in this behavior. This issue is no longer seen when using Google cloud credentials created through the UI form.
Closing issue.

**Closed by aaronRancher** 2021-04-09 23:27 UTC
Labels: [zube]: Next Up, area/gke, kind/bug-qa, status/blocker
