### ISSUE TITLE
Provide the way of removing PODs along with Replication controller removal

### ISSUE THREAD

**Issue by alena1108** [rancher/rancher#4398] opened 2016-04-13 20:58 UTC
```
kubectl delete <rep controller name>
```
deletes the RC as well as all the pods associated with the RC. That's the default kubectl behavior. If only RC needs to be removed, flag --cascade=false should be passed explicitly to the command.

In the UI, PODs always have to be cleaned separately. We should provide a way to cleanup corresponding pod resources the way kubectl does (steps kubectl makes, are listed by the link below):

http://kubernetes.io/docs/user-guide/replication-controller/, "Deleting a Replication Controller and its Pods" section

@vincent99

**Comment by sangeethah** [comment] 2016-04-13 21:41
Duplicate of https://github.com/rancher/rancher/issues/4359

**Closed** 2016-04-19 16:10 UTC
Labels: area/kubernetes, area/ui
