### ISSUE TITLE
Default namespace isn't present when trying to add a new workload

### ISSUE THREAD

**Issue by adingilloRancher** [rancher/rancher#12529] opened 2018-04-05 17:13 UTC
Rancher versions: 2.0

Steps to Reproduce:
Create a new cluster.
Navigate to workloads when spun up.
Add new workload.

Results:

<img width="1037" alt="screen shot 2018-04-05 at 10 08 02 am" src="https://user-images.githubusercontent.com/38012481/38380688-5dcfd990-38b9-11e8-8466-b3bfeeb0c2a4.png">

Default isn't present immediately. Took 10~ minutes to show up the few instances I was able to reproduce. Happened 2/3 attempts. Verified that default was present in the project view.

**Comment by deniseschannon** [comment] 2018-04-06 19:56
Duplicate of https://github.com/rancher/rancher/issues/12432

**Closed by deniseschannon** 2018-04-06 19:56 UTC
Labels: kind/bug, version/2.0
