### ISSUE TITLE
Not able to upgrade a service with sidekick.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#4159] opened 2016-03-27 02:07 UTC
Rancher Version:v1.0.0-rc4

Steps to reproduce the problem:
Create a service with sidekick.
Upgrade this service.

User is presented with the error message - "<sidekick name>: "Environment Id" is required"

This error is seen with/ with out selecting sidekick service when upgrading.

<img width="1105" alt="screen shot 2016-03-26 at 7 05 08 pm" src="https://cloud.githubusercontent.com/assets/4266958/14063434/fd4ccd3c-f385-11e5-88af-5fa7d5684434.png">

<img width="1230" alt="screen shot 2016-03-26 at 7 04 00 pm" src="https://cloud.githubusercontent.com/assets/4266958/14063435/044eba14-f386-11e5-8cac-e874c77d5800.png">

**Comment by deniseschannon** [comment] 2016-03-27 04:40
Looks like a duplicate of https://github.com/rancher/rancher/issues/4154. @vincent99 Can you confirm the fix that you put in will solve this issue?

**Comment by vincent99** [comment] 2016-03-27 04:42
No, this is different..

**Comment by tfiduccia** [comment] 2016-03-28 01:39
Version - master 3.27
Verified fixed

**Comment by tfiduccia** [comment] 2016-03-28 01:43
Version - master 3.27
Verified fixed

**Closed** 2016-03-28 01:43 UTC
Labels: area/ui, kind/bug, status/resolved, status/to-test
