### ISSUE TITLE
when I click the cpu input box, the default value had changed and I can't submit the form 

### ISSUE THREAD

**Issue by Tracy1994** [rancher/rancher#9766] opened 2017-08-28 08:04 UTC
**Rancher versions:**
rancher/server: stable
rancher/ui: 1.6-dev
host api: http://120.78.12.209:8000/v2-beta/projects/1a5/host

**Steps to Reproduce:**
1.click cpu input box
2.click create

**Results:**
Remind: Validation failed in API: milliCpu
post request value: milliCpu:""

**expectation：**
1.according to instance type, send the default values of memory and cpu to host api
2. show the default value in the input box
3.if the value is none ,remind the user the value of memory or cpu can't be none

#9575 
@yasker @orangedeng

**Comment by loganhz** [comment] 2017-09-13 04:57
Rancher versions:
rancher/server: 1.6.9

Steps to Reproduce:

1. try to add a new host with machine driver from UI
2. click advanced options and input cpu limit field
3. clear the cpu limit field

Results:

User can not submit the form

Expectation：

User should be able to submit the form

**Comment by yasker** [comment] 2017-09-13 05:03
Mark as duplicate of #9765

**Closed** 2017-09-13 05:03 UTC
Labels: area/machine, area/ui, kind/bug, team/cn, version/1.6
