### ISSUE TITLE
Wrong redirection on grafana in monitoring

### ISSUE THREAD

**Issue by wirwolf** [rancher/rancher#30990] opened 2021-01-26 09:28 UTC
**bug:**

**Steps to reproduce (least amount of steps as possible):**
* Setup cluster monitoring
![image](https://user-images.githubusercontent.com/8457572/105823474-dca61500-5fc5-11eb-8a7d-8ae38ed2adbc.png)
* Waiting for success
* Click on any icon grafana in rancher dashboard
![image](https://user-images.githubusercontent.com/8457572/105823679-1e36c000-5fc6-11eb-838a-fcb1cdb7664f.png)

**Expected:**
Open dashboard with context
![image](https://user-images.githubusercontent.com/8457572/105824495-1a576d80-5fc7-11eb-8684-3e5c4de87ae5.png)

**Actual:**
Display grafana index page
![image](https://user-images.githubusercontent.com/8457572/105824635-4a9f0c00-5fc7-11eb-9d33-588f57296f52.png)
only if cluster name ```local```
and when i click by icon system redirect to another page

https://rancher/k8s/clusters/local/api/v1/namespaces/cattle-prometheus/services/http:access-grafana:80/proxy/d/FnxG5TYiz/nodes
https://rancher/api/v1/namespaces/cattle-prometheus/services/http:access-grafana:80/proxy/?orgId=1

redirect code: https://github.com/rancher/rancher/blob/master/pkg/api/steve/proxy/proxy.go#L39

**Other details that may be helpful:**

**Environment information**
- Rancher version: v2.5.5
- Installation option: install a cluster with rke

**Cluster information**
- Cluster type: Imported
- Machine type (cloud/VM/metal) and specifications (CPU/memory):
- Kubernetes version (use `kubectl version`):

```
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.3", GitCommit:"1e11e4a2108024935ecfcb2912226cedeafd99df", GitTreeState:"clean", BuildDate:"2020-10-14T12:50:19Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.2", GitCommit:"59603c6e503c87169aea6106f57b9f242f64df89", GitTreeState:"clean", BuildDate:"2020-01-18T23:22:30Z", GoVersion:"go1.13.5", Compiler:"gc", Platform:"linux/amd64"}

```

- Docker version (use `docker version`):

```
Client: Docker Engine - Community
 Version:           20.10.2
 API version:       1.41
 Go version:        go1.13.15
 Git commit:        2291f61
 Built:             Mon Dec 28 16:17:43 2020
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.2
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       8891c58
  Built:            Mon Dec 28 16:15:19 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.3
  GitCommit:        269548fa27e0089a8b8278fc4fc781d7f65a939b
 runc:
  Version:          1.0.0-rc92
  GitCommit:        ff819c7e9184c13b7c2607fe6c30ae19403a7aff
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

**Comment by wirwolf** [comment] 2021-02-01 08:30
@izaac @SvenDowideit @gliptak

**Comment by wirwolf** [comment] 2021-02-15 08:29
@sowmyav27 

https://github.com/rancher/rancher/pull/31171

**Comment by jiaqiluo** [comment] 2021-03-12 19:27
The bug is reproduced on rancher v2.5.6 HA setup with Montiroing v1 chart 0.2.1

Steps:
- install Rancher v2.5.6 in HA mode 
- enable monitoring v1 0.2.1 on the local cluster
- Click on the Grafana icon on the node 
<img width="1092" alt="Screen Shot 2021-03-12 at 12 24 14 PM" src="https://user-images.githubusercontent.com/6218999/110988602-ff01b100-832d-11eb-8117-ba40ba1df336.png">

Results:
- the Grafana Home page shows instead of the Node page 

![screencapture-jq256-qa-rancher-space-api-v1-namespaces-cattle-prometheus-services-http-access-grafana-80-proxy-2021-03-12-12_26_36](https://user-images.githubusercontent.com/6218999/110988793-3e300200-832e-11eb-8a4b-db3790460ac8.png)

**Comment by jiaqiluo** [comment] 2021-03-12 22:55
Reopen the issue because the bug still exists on the latest v2.5-head

**Comment by westlywright** [comment] 2021-03-15 15:59
After digging into this change a bit more and digging into the UI code deeper, the UI change that was put in won't fix this issue. The change put in will only effect the `istio-nav` on the project level istio page. The images shown in the issue reference the `k8s-component-status` component which pulls the urls off the current clusters `monitoringStatus.grafanaEndpoint` property. I'm not sure why the `istio-nav` component references statically built URL's but I suspect it may need to be updated to pull the url from the current clusters `monitoringStatus.grafanaEndpoint`. 

After talking with @aiyengar2 offline I think agree with his sentiment that the change for this may be better suited for the backend.  @aiyengar2 can I get your thoughts on this?

**Comment by wirwolf** [comment] 2021-06-03 11:26
Any updates on this issue?

**Closed** 2022-02-07 21:02 UTC
Labels: [zube]: Unscheduled
