### ISSUE TITLE
[BUG] RKE2 custom cluster stuck in Updating state after a Rancher backup restore upgrade rollback from 2.6.6 to 2.6.7-rc5 to 2.6.6 in the same Rancher server

### ISSUE THREAD

**Issue by sowmyav27** [rancher/rancher#38474] opened 2022-07-30 00:09 UTC
**Rancher Server Setup**
- Rancher version: 2.6.6 to 2.6.7-rc5 to 2.6.6
- Installation option (Docker install/Helm Chart): RKE1 Helm

**Information about the Cluster**
- Kubernetes version: `v1.23.7+rke2r2`
- Cluster Type (Local/Downstream): Custom RKE2 - 1 etcd, 2 cp and 4 worker nodes

**User Information**
- What is the role of the user logged in? (Admin/Cluster Owner/Cluster Member/Project Owner/Project Member/Custom) clusters deployed using Restricted Admin access

**Describe the bug**

**To Reproduce**
- Deployed the following clusters in the rancher server in 2.6.6 version
```
- 1 custom RKE2 1 etcd, 2 cp and 4 worker nodes `v1.23.7+rke2r2`
- 1 custom RKE1 cluster - 1 etcd, 1 cp and 3 worker nodes - 1.23 k8s version
- 1 AWS node driver cluster - 1 etcd/cp, 3 worker nodes - v1.23.7+rke2r2
```
- Deploy Rancher backup 2.1.2 app and take a backup in S3 location
- Upgrade to rancher to 2.6.7-rc5
- Run clean up scripts on the local HA cluster using these - https://github.com/rancher/rancher-cleanup
- Create an S3 credential
- Create cattle-system namespace kubectl create namespace cattle-system
- Install Rancher backup - 2.1.2 verision
- Create a resource.yaml file from here - https://rancher.com/docs/rancher/v2.6/en/backups/restoring-rancher/
- Add in details about S3 location and S3 backup file name
- Do a kubectl apply -f <resource.yaml> 
- Restore happens
- Install rancher - `helm install rancher rancher-latest/rancher --version 2.6.6 --namespace cattle-system --set hostname=<hostname> `
- In the Rancher server, RKE2 node driver cluster goes into Updating state and comes back up Active.
- RKE1 cluster is Unavailable and comes back up Active
- Custom RKE2 cluster is stuck in `Updating` state 

**Result**
- `journalctl -u rancher-system-agent`
```
Jul 29 23:57:22 ip-172-31-13-45 rancher-system-agent[15978]: time="2022-07-29T23:57:22Z" level=info msg="[d0b26abb655df6746dda34f638284439b9afa1246f06d19e6d82ddcbf79934d0_2:stdout]: etcd-snapshot-ip-172-31-13-45-1659124800 file:///var/lib/rancher/rke2/server/db/snapshots/etcd-snapshot-ip-172-31-13-45-1659124800 14467104 2022-07-29T20:00:00Z"
Jul 29 23:57:22 ip-172-31-13-45 rancher-system-agent[15978]: time="2022-07-29T23:57:22Z" level=info msg="[Applyinator] Command sh [-c rke2 etcd-snapshot list --etcd-s3=false 2>/dev/null] finished with err: <nil> and exit code: 0"
Jul 29 23:57:23 ip-172-31-13-45 rancher-system-agent[15978]: time="2022-07-29T23:57:23Z" level=error msg="error syncing 'fleet-default/custom-db70e177ea17-machine-plan': handler secret-watch: Unauthorized, requeuing"
Jul 29 23:57:27 ip-172-31-13-45 rancher-system-agent[15978]: time="2022-07-29T23:57:27Z" level=info msg="[Applyinator] No image provided, creating empty working directory /var/lib/rancher/agent/work/20220729-235727/d0b26abb655df6746dda34f638284439b9afa1246f06d19e6d82ddcbf79934d0_0"
Jul 29 23:57:27 ip-172-31-13-45 rancher-system-agent[15978]: time="2022-07-29T23:57:27Z" level=info msg="[Applyinator] Running command: sh [-c curl -f --retry 100 --retry-delay 5 --cacert /var/lib/rancher/rke2/server/tls/server-ca.crt https://localhost:9345/db/info | grep 'clientURLs']"
Jul 29 23:57:27 ip-172-31-13-45 rancher-system-agent[15978]: time="2022-07-29T23:57:27Z" level=info msg="[d0b26abb655df6746dda34f638284439b9afa1246f06d19e6d82ddcbf79934d0_0:stderr]:   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current"
Jul 29 23:57:27 ip-172-31-13-45 rancher-system-agent[15978]: time="2022-07-29T23:57:27Z" level=info msg="[d0b26abb655df6746dda34f638284439b9afa1246f06d19e6d82ddcbf79934d0_0:stderr]:                                  Dload  Upload   Total   Spent    Left  Speed"
Jul 29 23:57:27 ip-172-31-13-45 rancher-system-agent[15978]: time="2022-07-29T23:57:27Z" level=info msg="[d0b26abb655df6746dda34f638284439b9afa1246f06d19e6d82ddcbf79934d0_0:stderr]: \r  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0\r100   158  100   158    0     0  17555      0 --:--:-- --:--:-- --:--:-- 17555"
Jul 29 23:57:27 ip-172-31-13-45 rancher-system-agent[15978]: time="2022-07-29T23:57:27Z" level=info msg="[d0b26abb655df6746dda34f638284439b9afa1246f06d19e6d82ddcbf79934d0_0:stdout]: {\"members\":[{\"ID\":175376674253942530,\"name\":\"ip-172-31-13-45-62602deb\",\"peerURLs\":[\"https://172.31.13.45:2380\"],\"clientURLs\":[\"https://172.31.13.45:2379\"]}]}"
Jul 29 23:57:27 ip-172-31-13-45 rancher-system-agent[15978]: time="2022-07-29T23:57:27Z" level=info msg="[Applyinator] Command sh [-c curl -f --retry 100 --retry-delay 5 --cacert /var/lib/rancher/rke2/server/tls/server-ca.crt https://localhost:9345/db/info | grep 'clientURLs'] finished with err: <nil> and exit code: 0"
Jul 29 23:57:27 ip-172-31-13-45 rancher-system-agent[15978]: time="2022-07-29T23:57:27Z" level=info msg="[Applyinator] No image provided, creating empty working directory /var/lib/rancher/agent/work/20220729-235727/d0b26abb655df6746dda34f638284439b9afa1246f06d19e6d82ddcbf79934d0_1"
Jul 29 23:57:27 ip-172-31-13-45 rancher-system-agent[15978]: time="2022-07-29T23:57:27Z" level=info msg="[Applyinator] Running command: sh [-c cat /var/lib/rancher/rke2/server/db/etcd/name]"
Jul 29 23:57:27 ip-172-31-13-45 rancher-system-agent[15978]: time="2022-07-29T23:57:27Z" level=info msg="[d0b26abb655df6746dda34f638284439b9afa1246f06d19e6d82ddcbf79934d0_1:stdout]: ip-172-31-13-45-62602deb"
Jul 29 23:57:27 ip-172-31-13-45 rancher-system-agent[15978]: time="2022-07-29T23:57:27Z" level=info msg="[Applyinator] Command sh [-c cat /var/lib/rancher/rke2/server/db/etcd/name] finished with err: <nil> and exit code: 0"
Jul 29 23:57:27 ip-172-31-13-45 rancher-system-agent[15978]: time="2022-07-29T23:57:27Z" level=info msg="[Applyinator] No image provided, creating empty working directory /var/lib/rancher/agent/work/20220729-235727/d0b26abb655df6746dda34f638284439b9afa1246f06d19e6d82ddcbf79934d0_2"
Jul 29 23:57:27 ip-172-31-13-45 rancher-system-agent[15978]: time="2022-07-29T23:57:27Z" level=info msg="[Applyinator] Running command: sh [-c rke2 etcd-snapshot list --etcd-s3=false 2>/dev/null]"
Jul 29 23:57:28 ip-172-31-13-45 rancher-system-agent[15978]: time="2022-07-29T23:57:28Z" level=info msg="[d0b26abb655df6746dda34f638284439b9afa1246f06d19e6d82ddcbf79934d0_2:stdout]: Name                                     Location                                                                                  Size     Created"
Jul 29 23:57:28 ip-172-31-13-45 rancher-system-agent[15978]: time="2022-07-29T23:57:28Z" level=info msg="[d0b26abb655df6746dda34f638284439b9afa1246f06d19e6d82ddcbf79934d0_2:stdout]: etcd-snapshot-ip-172-31-13-45-1659124800 file:///var/lib/rancher/rke2/server/db/snapshots/etcd-snapshot-ip-172-31-13-45-1659124800 14467104 2022-07-29T20:00:00Z"
Jul 29 23:57:28 ip-172-31-13-45 rancher-system-agent[15978]: time="2022-07-29T23:57:28Z" level=info msg="[Applyinator] Command sh [-c rke2 etcd-snapshot list --etcd-s3=false 2>/dev/null] finished with err: <nil> and exit code: 0"
Jul 29 23:57:28 ip-172-31-13-45 rancher-system-agent[15978]: time="2022-07-29T23:57:28Z" level=error msg="error syncing 'fleet-default/custom-db70e177ea17-machine-plan': handler secret-watch: Unauthorized, requeuing"
```

**Comment by jiaqiluo** [comment] 2022-08-03 17:50
The rancher-cleanup script wipes out everything rancher creates on the cluster. 
The secret containing the kubeconfig file is not in the backup files, so it is recreated by rancher after the reinstallation. 
By following the same steps, I could not reproduce the error. 
Moving this to to-test for QA to try it again.

**Comment by jiaqiluo** [comment] 2022-08-03 18:01
If this error happens, a potential workaround is to delete the existing secret named `<your-cluster-name>-kubeconfig` from the local cluster and let rancher reconcile the cluster.	 (I found the workaround to fix another thing I broke during the investigation, but it also fix the original error reported by this issue)

**Comment by anupama2501** [comment] 2022-08-03 22:53
Verified from v2.6.6 >> v2.6.7-rc5 >> v2.6.6

- Deployed the following clusters in the rancher server in 2.6.6 version
```
- 2 custom RKE2 1 etcd, 2 cp and 4 worker nodes `v1.23.7+rke2r2`
- 1 custom RKE1 cluster - 1 etcd, 1 cp and 3 worker nodes - 1.23 k8s version
- 1 AWS node driver RKE1 - 1 etcd, 1 cp, 3 worker nodes - v1.23.7+rke2r2
- 2 Node driver RKE2 - [AWS] -1 etcd, 2 cp, 4 worker, [Linode] - 3 worker, 2cp, 3 etcd
```

- Deploy Rancher backup app `2.1.2` version and take a backup in S3 location
- Upgrade to rancher to 2.6.7-rc5
- Run clean up scripts on the local HA cluster using these - https://github.com/rancher/rancher-cleanup
- Create an S3 credential
- Create cattle-system namespace `kubectl create namespace cattle-system`
- Install Rancher backup app - `2.1.2` version
- Create a resource.yaml file from here - https://rancher.com/docs/rancher/v2.6/en/backups/restoring-rancher/
- Add in details about S3 location and S3 backup file name
- Do a kubectl apply -f <resource.yaml>
- Restore happens
- Install rancher - helm install rancher rancher-latest/rancher --version 2.6.6 --namespace cattle-system --set hostname=<hostname>
- In the Rancher server, RKE2 node driver cluster goes into Updating state and comes back up Active.
- RKE1 cluster is Unavailable and comes back up Active
- Custom RKE2 cluster goes into Updating state and comes back up active as well.

**Comment by anupama2501** [comment] 2022-08-03 22:54
Closing this issue for now. Will re open the issue if we see it again.

**Closed** 2022-08-03 22:55 UTC
Labels: kind/bug-qa, [zube]: To Test, area/rke2, status/release-blocker, team/area2, v2.6.7
