### ISSUE TITLE
GKEv2 cluster when provisioning says "Provisioned"

### ISSUE THREAD

**Issue by sowmyav27** [rancher/rancher#32165] opened 2021-04-15 20:38 UTC
**What kind of request is this (question/bug/enhancement/feature request):** bug

**Steps to reproduce (least amount of steps as possible):**

- Create a hosted GKE cluster (Default values)
- When the cluster is in Provisioning state, the message appearing below it reads `Provisioned`.
- Can it also be made as `Provisioning` ? or if this is redundant can something be introduced? Because the cluster is provisioning in GCE console also and from Rancher.
<img width="423" alt="Screen Shot 2021-04-15 at 1 29 19 PM" src="https://user-images.githubusercontent.com/26032343/114945317-f5bca600-9dfd-11eb-92dd-82f6d39d4489.png">

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): v2.5-41f173ae93
- Installation option (single install/HA):Single

**Comment by cmurphy** [comment] 2021-04-15 21:34
> the message appearing below it reads Provisioned.

I'm not sure what you mean by this, could you include a screenshot? I only see "Provisioning":

![image](https://user-images.githubusercontent.com/1220710/114940913-51376580-9df7-11eb-889a-d89fb17ba20f.png)
![image](https://user-images.githubusercontent.com/1220710/114940982-66ac8f80-9df7-11eb-873e-317e2d7476d6.png)
![image](https://user-images.githubusercontent.com/1220710/114941015-7330e800-9df7-11eb-9967-1851eb89e9f0.png)

**Comment by sowmyav27** [comment] 2021-04-19 14:10
Now i see this on master-head commit id: `1c3629f` and not on 2.5-head commit id: `31f00c15`

**Comment by cmurphy** [comment] 2021-04-19 17:08
I can now see it on master as well. I think it has to do with the UI reading the `Conditions` on the cluster object, and one of them is `type: Provisioned`. During the provisioning phase Rancher sets the `value` of this condition to `Unknown`. The other possible values for this condition are `false` (if there's an error) or `true` (if it's completed). I'm not able to pinpoint where in the UI it is happening but I guess it's reading this condition while it's in the `Unknown` state and it shouldn't be displaying that. @westlywright can you take a look and let me know if I need to change something on the backend for this to work right?

**Comment by cbron** [comment] 2021-04-20 15:24
Moving to 2.6 since this is not reproducible in 2.5.8-rc's.

**Comment by westlywright** [comment] 2021-04-20 22:27
@cmurphy We're not reading off the conditions in this case. I could not reproduce this but as far as I can tell what you're seeing is a transitioning message as seen [here in the cluster-row -> error-sub-row component](https://github.com/rancher/ui/blob/master/lib/global-admin/addon/components/cluster-row/template.hbs#L122-L124). The component name is a bit confusing as it doesn't only show errors. `Provisioning` is a transitioning state which would cause the `showTransitioningMessage` flag on the cluster object to be set true exposing the `error-sub-row`. Then I suspect the API object has `transitioningMessage: "Provisioned"` on it, which would show up [here](https://github.com/rancher/ui/blob/master/lib/shared/addon/components/error-sub-row/template.hbs#L6). Its possible I am missing something, if you have a cluster where this is actively presenting I would love to look at it to get to the bottom of it.

**Comment by cmurphy** [comment] 2021-04-23 04:20
I tracked this down to changes in wrangler that are only used on master:

https://github.com/rancher/wrangler/commit/3eba78f45e7d61364efd11d73334641c17305b4c
https://github.com/rancher/wrangler/commit/3533ace946aaf8cc64ae4be9ead3221c35975884

Here's one option to handle it (kind of) in the  backend: https://github.com/rancher/rancher/pull/32309

**Comment by cmurphy** [comment] 2021-04-26 17:51
This should be fixed in master now

**Comment by kravciak** [comment] 2021-04-29 11:31
I could not reproduce on v2.5-41f173a, but I reproduced on master-1c3629f

`Provisioned` message is not present on master-head (7e5ad7f). Adding hosted GKE cluster went through:
- provisioning
- waiting (waiting for api to become available)
- active

**Closed by kravciak** 2021-04-29 11:31 UTC
Labels: [zube]: To Test, area/gke, kind/bug-qa
