### ISSUE TITLE
Weird etcdHighNumberOfFailedGRPCRequests prometheus rule in v2.5 rancher-monitoring

### ISSUE THREAD

**Issue by gmintoco** [rancher/rancher#29939] opened 2020-10-09 03:08 UTC
I just was trying out the v2.5 monitoring chart and noticed that I was getting a large number of alerts for
`etcdHighNumberOfFailedGRPCRequests for kube-etcd (alertname="etcdHighNumberOfFailedGRPCRequests", grpc_method="Watch", grpc_service="etcdserverpb.Watch", prometheus="monitoring/monitoring-rancher-monitor-prometheus", severity="critical")` 

I took a look at the rules and something struck me as odd. This is the expression used to determine this alert: `100 * sum(rate(grpc_server_handled_total{job=~".*etcd.*", grpc_code!="OK"}[5m])) BY (job, instance, grpc_service, grpc_method) / sum(rate(grpc_server_handled_total{job=~".*etcd.*"}[5m])) BY (job, instance, grpc_service, grpc_method)`

Which seems to result in garbage data: 
![image](https://user-images.githubusercontent.com/50625416/95537068-68f0f400-0a38-11eb-9efd-a4f1a14829b9.png)  

However changing `BY (job, instance, grpc_service, grpc_method)` with simply `BY (instance)` seems to produce a much more meaningful metric (% grpc failed per node) 
![image](https://user-images.githubusercontent.com/50625416/95537117-950c7500-0a38-11eb-9569-e109488257ac.png)

From my perspective, it seems like it should be changed to BY (instance) as this seems to make more sense but not 100% sure. I am very new to Prometheus in general.

gz#14464
gz#14015

gz#14746

gz#15416

gz#16124
gz#16211

**Comment by aiyengar2** [comment] 2020-11-05 01:59
@gmintoco thanks for calling this out! Based on https://github.com/etcd-io/etcd/pull/12122/files#diff-051b19bef7add661d9678608040a89efaead1aa9d3063323effdfedae11c9978R76-R100, it seems like you are correct, although the etcd team seems to replace `BY (job, instance, grpc_service, grpc_method)` with `without (grpc_type, grpc_code)` instead. Can you see if that also works for you?

With respect to bringing this change into Rancher, Rancher pulls these rules from the upstream Prometheus community Helm chart [`kube-prometheus-stack`](https://github.com/prometheus-community/helm-charts/tree/main/charts/kube-prometheus-stack), which has an open issue out w.r.t. trying to update the etcd alerts in https://github.com/prometheus-community/helm-charts/issues/225. Once that is resolved, we can pull in the latest etcd alerts to get those changes in.

**Comment by gmintoco** [comment] 2020-11-05 03:25
Hi @aiyengar2 yeah I realised that after digging into things a little deeper. I actually opened that issue :) but yes just waiting to see what happens there. Thanks for the response

**Comment by immanuelfodor** [comment] 2020-12-12 18:53
This alert started to rain down on me today after a node memory pressure event, and it is firing constantly even though all the nodes were rebooted. Latest RKE with latest Rancher 2.5 and Monitoring V2 stack. Can it be supressed somehow until it is fixed in upstream? 

```yaml
alerts:
- annotations:
    message: 'etcd cluster "kube-etcd": 100% of requests for Watch failed on etcd
      instance 192.168.1.100:2379.'
  endsAt: '0001-01-01T00:00:00Z'
  fingerprint: bce5342bd6fd6152
  generatorURL: http://rancher-monitoring-prometheus.cattle-monitoring-system:9090/graph?g0.expr=100+%2A+sum+by%28job%2C+instance%2C+grpc_service%2C+grpc_method%29+%28rate%28grpc_server_handled_total%7Bgrpc_code%21%3D%22OK%22%2Cjob%3D~%22.%2Aetcd.%2A%22%7D%5B5m%5D%29%29+%2F+sum+by%28job%2C+instance%2C+grpc_service%2C+grpc_method%29+%28rate%28grpc_server_handled_total%7Bjob%3D~%22.%2Aetcd.%2A%22%7D%5B5m%5D%29%29+%3E+5&g0.tab=1
  labels:
    alertname: etcdHighNumberOfFailedGRPCRequests
    grpc_method: Watch
    grpc_service: etcdserverpb.Watch
    instance: 192.168.1.100:2379
    job: kube-etcd
    prometheus: cattle-monitoring-system/rancher-monitoring-prometheus
    severity: critical
  startsAt: '2020-12-12T18:45:10.979Z'
  status: firing
commonAnnotations:
  message: 'etcd cluster "kube-etcd": 100% of requests for Watch failed on etcd instance
    192.168.1.100:2379.'
commonLabels:
  alertname: etcdHighNumberOfFailedGRPCRequests
  grpc_method: Watch
  grpc_service: etcdserverpb.Watch
  instance: 192.168.1.100:2379
  job: kube-etcd
  prometheus: cattle-monitoring-system/rancher-monitoring-prometheus
  severity: critical
externalURL: http://rancher-monitoring-alertmanager.cattle-monitoring-system:9093
groupKey: '{}:{job="kube-etcd"}'
groupLabels:
  job: kube-etcd
receiver: matrix
status: firing
truncatedAlerts: 0
version: '4'
```

**Comment by immanuelfodor** [comment] 2020-12-13 05:25
After another 109 alerts over the night, I added a silence for `etcdHighNumberOfFailedGRPCRequests` in AlertManager.

**Comment by m4r1u2** [comment] 2020-12-17 13:32
Can confirm we also have the same issue in our v2.5 rancher-monitoring rke setup.. 
Are we all waiting on upstream fixes or any updates to this issue?

**Comment by jonathon2nd** [comment] 2021-01-12 16:49
Still happens after the 2.5.5 update. 

Rancher | v2.5.5
User Interface | v2.5.4
Helm | v2.16.8-rancher1
Machine | v0.15.0-rancher49

**Comment by vitobotta** [comment] 2021-01-17 18:39
Hi, I set up a new instance of Rancher 2.5.5 and a new RKE cluster and am getting these alerts. Do I need to worry about the health of the cluster? I literally just started setting things up and there are plenty of resources / low load on the servers. Thanks

**Comment by immanuelfodor** [comment] 2021-01-17 18:47
My cluster is healthy and fairly sable, and I also get these constantly. I eventually silenced them through the alertmanager secret (under `alertmanager.yaml`): 

```yaml
route:
...
  # temporarily silence this alert until it's fixed upstream                         
  - match:                                                                               
      alertname: etcdHighNumberOfFailedGRPCRequests                                    
    receiver: "null"
... 
```

**Comment by vitobotta** [comment] 2021-01-17 18:52
> My cluster is healthy and fairly sable, and I also get these constantly. I eventually silenced them through the alertmanager secret (under `alertmanager.yaml`):
> 
> ```yaml
> route:
> ...
>   # temporarily silence this alert until it's fixed upstream                         
>   - match:                                                                               
>       alertname: etcdHighNumberOfFailedGRPCRequests                                    
>     receiver: "null"
> ... 
> ```

Is it safe to silence/ignore them? I also don't see any problems at all with the cluster itself.

**Comment by immanuelfodor** [comment] 2021-01-17 18:56
If safe is equivalent to sleeping well while the cluster purring like a cat and no late night calls while this alert is somehow involved with a crashing service, yes, it's fairly safe 😃

**Comment by vitobotta** [comment] 2021-01-17 21:32
> If safe is equivalent to sleeping well while the cluster purring like a cat and no late night calls while this alert is somehow involved with a crashing service, yes, it's fairly safe 😃

I've silenced it for now :)

**Comment by axeal** [comment] 2021-01-19 12:38
The cause of the frequent etcdHighNumberOfFailedGRPCRequests alarms is not the metric expression itself.

The output of the existing expression with [`by`](https://github.com/etcd-io/etcd/blob/v3.3.14/Documentation/op-guide/etcd3_alert.rules.yml):

`100 * sum by(job, instance, grpc_service, grpc_method) (rate(grpc_server_handled_total{grpc_code!="OK",job=~".*etcd.*"}[5m])) / sum by(job, instance, grpc_service, grpc_method) (rate(grpc_server_handled_total{job=~".*etcd.*"}[5m]))`

does not differ from the new expression using [`without`](https://github.com/etcd-io/etcd/blob/master/Documentation/etcd-mixin/mixin.libsonnet):

`100 * sum(rate(grpc_server_handled_total{job=~".*etcd.*", grpc_code!="OK"}[5m])) without (grpc_type, grpc_code) / sum(rate(grpc_server_handled_total{job=~".*etcd.*"}[5m])) without (grpc_type, grpc_code)`

The high number of alerts is caused by the upstream etcd issue tracked in https://github.com/etcd-io/etcd/issues/10289, with PR https://github.com/etcd-io/etcd/pull/12196 open to address this. Until this is fixed, silencing or removing this specific alert will address the alert noise.

**Comment by ccittadino-ctic** [comment] 2021-03-12 15:10
Can we get an update on when this merge will happen please? It looks like the [upstream changes are closed out](https://github.com/prometheus-community/helm-charts/issues/225)?

**Comment by Tejeev** [comment] 2021-03-15 11:18
Hi @ccittadino-ctic, maybe I misunderstand something about the issue or you linked the wrong issue? I'm not sure how prometheus-community/helm-charts/225 is related.  I do however see that the PR that Alex linked, which is the root cause of this issue, has been merged for etcd v3.5.0-alpha and may be backported to v3.4.x
When this is done, we should see these alerts clear up.  In the meantime, a good workaround would be to silence or remove this alert and make sure you have other alerts set up to track etcd health.

**Comment by aiyengar2** [comment] 2021-03-15 17:24
@ccittadino-ctic the issue was closed out in upstream without resolution. As @Tejeev mentioned, the upstream chart is still out of date at etcd v3.4.x: https://github.com/prometheus-community/helm-charts/blob/8318ce1d92e8c3dd487d89066d0f7b2405c65653/charts/kube-prometheus-stack/templates/prometheus/rules-1.14/etcd.yaml#L2

**Comment by ccittadino-ctic** [comment] 2021-03-15 19:16
@aiyengar2 So are we just waiting for 3.5 of prometheus to release before Rancher can take it in?

**Comment by aiyengar2** [comment] 2021-03-15 19:55
We are waiting on `kube-prometheus-stack` to absorb the latest dashboards from etcd; once `kube-prometheus-stack` has made the changes, we'll rebase on the latest upstream chart to get in the fix.

**Comment by aiyengar2** [comment] 2021-07-06 18:53
Update: upstream still has not updated their dashboards primarily because etcd has not updated the dashboards published on their website.

To get this change from the upstream chart:
- A user must submit a PR to etcd-io/etcd at `contrib/mixin/mixin.libsonnet` - [DONE](https://github.com/etcd-io/etcd/blob/f4fad92e0d0240d1495cc6bf9d2f4d1fbeab4e4b/contrib/mixin/mixin.libsonnet#L89-L120)
- The contents of etcd-io/website at `content/en/docs/v3.4/op-guide/etcd3_alert.rules.yml` must be manually synced based on the above merged contents - [NOT DONE](https://github.com/etcd-io/website/blob/253bd600a28bf2cf2a28251a69d7def82f29512a/content/en/docs/v3.4/op-guide/etcd3_alert.rules.yml#L32-L55)
- kube-prometheus-stack must run a script to update etcd dashboards - BLOCKED
- Rancher must rebase to the latest upstream chart - BLOCKED

cc: @Jono-SUSE-Rancher @snasovich it may make sense to prioritize this issue as a patch on Monitoring directly since it's been over a year since the original PR was merged in.

**Comment by kbreit** [comment] 2021-11-02 19:23
Has this been resolved? I'm seeing errors in my environment but the system seems fine.

**Comment by DanSibbernsen** [comment] 2021-11-05 16:24
> Has this been resolved? I'm seeing errors in my environment but the system seems fine.

I don't think so. I'm running Rancher 2.5.9, fresh install of the monitoring solution, and I'm seeing this alert on clusters running 3 etcd instances. I'm silencing it for now, hoping we don't need to in the future.

**Comment by kbreit** [comment] 2021-11-05 16:29
I'm not running rancher but I was looking. Seems the k8s version starting at 1.22 will upgrade to a version of etcd that fixes this bug.

**Comment by jiaqiluo** [comment] 2021-11-11 21:45
Let me try to summarize the issue:
- The problem of the expression comes from the `grpc_code!="OK"` part: it treats other non-error codes (canceled, invalidArgument, notFound, and etc) as errors so the expression reports a high rate of errors  (see GRPC standard [here](https://grpc.github.io/grpc/core/md_doc_statuscodes.html)) thus triggers too many alerts. 
- The above problem in the expression has been fixed in the upstream etcd repo: https://github.com/etcd-io/etcd/pull/13127
- But the above fix is not synced to the `kube-prometheus-stack` repo: notice that the wrong expression is still in [the main branch ](https://github.com/prometheus-community/helm-charts/blob/a9ee21df9bf490d73997b9efcdbca522778dddb3/charts/kube-prometheus-stack/templates/prometheus/rules-1.14/etcd.yaml#L61)

For rancher-monitoring charts, I think we can patch the expression instead of waiting for the upstream’s fix.

**Comment by adamrossmusic** [comment] 2021-11-14 22:25
So this means in the current versions these are expected "issues"...

So "best option until fix" is to..silence alerts coming from etcd?

**Comment by korenlev** [comment] 2022-05-01 11:47
seeing the same issue , we adjust alerting to ignore this until fixed

**Comment by MKlimuszka** [comment] 2022-05-11 17:59
@geethub97 , please check if this is reproducible in monitoring v2. 
SURE-2721

**Comment by AndrewSav** [comment] 2022-05-12 20:34
@MKlimuszka Could you please link the commit where this is fixed?

**Comment by R-Studio** [comment] 2022-05-23 08:51
same issue here, we silenced alerting to ignore this until fixed

**Comment by vishnoisuresh** [comment] 2022-05-24 07:26
Its the same situation with  rancher-monitoring 100.1.2+up19.0.3 .

**Comment by klauserber** [comment] 2022-07-23 13:27
For kube-prometheus-stack user that are coming along this issue.

I put this in the helm values.yml file for a temporary fix:

```
defaultRules:
  disabled:
    # the results of this rule are not accurate: https://github.com/rancher/rancher/issues/29939
    etcdHighNumberOfFailedGRPCRequests: true
  
additionalPrometheusRulesMap:
  additional-rules:
    groups:
      # fix etcdHighNumberOfFailedGRPCRequests alerting rules from above, adapted from: https://github.com/etcd-io/etcd/pull/13127
      - name: etcd-additional
        rules:
          - alert: etcdHighNumberOfFailedGRPCRequestsWarning
            annotations:
              message: >-
                etcd cluster "{{ $labels.job }}": {{ $value }}% of requests for {{
                $labels.grpc_method }} failed on etcd instance {{ $labels.instance
                }}.
            expr: >-
              100 * sum(rate(grpc_server_handled_total{job=~".*etcd.*",
                grpc_code=~"Unknown|FailedPrecondition|ResourceExhausted|Internal|Unavailable|DataLoss|DeadlineExceeded"}[5m])) 
              / 
              sum(rate(grpc_server_handled_total{job=~".*etcd.*"}[5m]))
              > 1
            for: 10m
            labels:
              severity: warning
          - alert: etcdHighNumberOfFailedGRPCRequestsCritical
            annotations:
              message: >-
                etcd cluster "{{ $labels.job }}": {{ $value }}% of requests for {{
                $labels.grpc_method }} failed on etcd instance {{ $labels.instance
                }}.
            expr: >-
              100 * sum(rate(grpc_server_handled_total{job=~".*etcd.*",
                grpc_code=~"Unknown|FailedPrecondition|ResourceExhausted|Internal|Unavailable|DataLoss|DeadlineExceeded"}[5m])) 
              / 
              sum(rate(grpc_server_handled_total{job=~".*etcd.*"}[5m]))
              > 5
            for: 5m
            labels:
              severity: critical
```
The queries do not include the 'without' clauses, but the results are looking good to me:

<img width="1517" alt="Bildschirmfoto 2022-07-23 um 15 25 05 PM" src="https://user-images.githubusercontent.com/9998995/180607060-e95cdd63-2d9a-4f76-bc76-edd773094095.png">

**Comment by MKlimuszka** [comment] 2022-09-22 16:11
QA, please check if this is fixed in 2.7.0, monitoring v2.

**Comment by ronhorton** [comment] 2022-11-02 18:08
**Pass** Verified in `2.7.0-rc8`
1. created downstream rke1 cluster
2. installed rancher-monitoring
3. checked prometheus UI for etcdHighNumberOfFailedGRPCRequests - 0 active
4. manually ran query for etcdHighNumberOfFailedGRPCRequests alert, decreased check to 1 second: 0 results

`no longer receiving high number of alerts for etcdHighNumberOfFailedGRPCRequests`

**Closed** 2022-11-02 18:09 UTC
Labels: internal, area/monitoring, [zube]: QA Working, status/dev-validate, team/area3

**Comment by Giancarlo1974** [comment] 2022-11-04 09:25
same issue here with RKE rancher-monitoring 100.1.3+up19.0.3
