### ISSUE TITLE
[agent][coreos] Some point looses connection to server

### ISSUE THREAD

**Issue by fentas** [rancher/rancher#3006] opened 2015-12-11 10:51 UTC
Hey there,
this error/problem occurred within the last updates i guess before it worked like a charm.
After some point the agent kills (itself?) and tries to reconnect which fails of unauthorized.
Here are the logs.
```logs
time="2015-12-11T07:08:29Z" level="info" msg="Processing event: &docker.APIEvents{Status:\"die\", ID:\"9545a9a331e9aed21230b644631775caad5107634288151d242fe47cc13ab8e7\", From:\"rancher/agent-instance:v0.6.0\", Time:1449817709}" 
time="2015-12-11T07:08:29Z" level="info" msg="Processing event: &docker.APIEvents{Status:\"stop\", ID:\"9545a9a331e9aed21230b644631775caad5107634288151d242fe47cc13ab8e7\",From:\"rancher/agent-instance:v0.6.0\", Time:1449817709}" 
time="2015-12-11T07:08:34Z" level="info" msg="Processing event: &docker.APIEvents{Status:\"kill\", ID:\"88686a0210d7a91346b99b51c83b830562e769084b05430341f14d03fb3bcd55\",From:\"rancher/agent:v0.8.2\", Time:1449817714}" 
INFO: Starting agent for key
INFO: Access Key: key
INFO: Config URL: https://.../v1
INFO: Storage URL: https://.../v1
INFO: API URL: https://.../v1
INFO: IP: 104.155.71.126
INFO: Port:
INFO: Required Image: rancher/agent:v0.8.2
INFO: Current Image: rancher/agent:v0.8.2
INFO: Using image rancher/agent:v0.8.2
INFO: Downloading agent https://.../v1/configcontent/configscripts
gzip: stdin: not in gzip format
tar: Child returned status 1
tar: Error is not recoverable: exiting now
INFO: Starting agent for key
INFO: Access Key: key
INFO: Config URL: https://.../v1
INFO: Storage URL: https://.../v1
INFO: API URL: https://.../v1
INFO: IP: 104.155.71.126
INFO: Port:
INFO: Required Image: rancher/agent:v0.8.2
INFO: Current Image: rancher/agent:v0.8.2
INFO: Using image rancher/agent:v0.8.2
INFO: Downloading agent https://.../v1/configcontent/configscripts
{"id":"28cde8ed-0c6e-4190-8596-e680fd824270","type":"error","links":{},"actions":{},"status":401,"code":"Unauthorized","message":"Unauthorized","detail":null}
```
The last couple of messages keeps then on repeating.
What is the best way to solve this?

```
Rancher	v0.47.0
Cattle	v0.115.0
User Interface	v0.68.0
Rancher Compose	v0.5.3
```
```sh
$ uname -a
Linux ... 4.3.0-coreos #2 SMP Thu Nov 26 02:49:19 UTC 2015 x86_64 Intel(R) Xeon(R) CPU @ 2.30GHz GenuineIntel GNU/Linux
```

**Comment by RVN-BR** [comment] 2015-12-16 02:29
I noticed something similar when trying to add a coreos cluster of 3 nodes to rancher... the nodes would go to reconnecting at different times and not recover...  As a weird thing to point out, the 3 nodes registered with the rancher server, but all showed up as a single IP address (same IP address on each host)... is this expected in some way?

**Comment by deniseschannon** [comment] 2015-12-29 17:44
I have a fresh setup with v0.51.0 and added a CoreOS agent. I'm going to see if anything happens with it, but so far it's been connecting fine. When the next release upgrades, I'll keep monitoring it.

@fentas Is your setup a coreOS cluster or single coreOS agent?

@RVN-BR What IP address is being shown? Is it the actual IP address of the machine or is it a different one?

**Comment by RVN-BR** [comment] 2015-12-31 07:19
Any ideas here? @deniseschannon did you get any progress?

When using  the rancher vagrant example, anything I try running on it will cause the 2 vagrant vms (rancher-01 and rancher-server) to just stop communicatingand stop responding on their IPs...

I added a single rancher-server, and 4 unit coreos cluster... as you can see all coreos hosts are showing thesame ip...
![image](https://cloud.githubusercontent.com/assets/1218902/12062129/c5c7a838-af64-11e5-847d-f0b1df268f46.png)

Fleetctl doesnt seem to agree that those are the IPs.... 

```
core@core-01 ~ $ fleetctl list-machines
MACHINE		IP		METADATA
37d26d06...	172.17.8.103	-
9c61a1ec...	172.17.8.104	-
e0dc67a4...	172.17.8.101	-
ec159fa5...	172.17.8.102	-
```

**Comment by RVN-BR** [comment] 2015-12-31 07:21
And just a few moments after starting up the service from the catalog... bam... the server looses connectivity.... cant even load rancher server anymore :(

![image](https://cloud.githubusercontent.com/assets/1218902/12062156/2bfe63d0-af65-11e5-8a64-bd8bab6b93e9.png)

**Comment by RVN-BR** [comment] 2015-12-31 07:48
I finally removed the agent from the Rancher vagrantfile... leaving it start as only the server... I then added a global fleet unit to run the rncher agent, and finally I was able to get services and stacks running... (so theres one for rancheros or the vagrant config... who knows... hard to debug with so many moving parts updated all at the same time)...

Anyways, the coreos cluster is on the 172.17.8.x netowkr, and the rancher server is at 172.19.8.100...

As you can see Rancher UI is reporting incorrectly...  All servers are showing up wrong IPs...  Even if I go onto the kopf server (after launching the elasticsearch stack from catalog), it gives it a wrong ip... the link therefore doesn work... loging in to the coreos node from vagrant, getting the correct up, and typing it in, and bingo... it works... something is definitely a miss....

Out of curiosity, is anything using this stuff in QA? Production? or even in development?  I've been "playing" but its been quite a rollercoster ride....

If anyone has other suggestions I'd be glad to hear.... I fear the team has so many differnt fronts (including an entire OS!) that rancher and *allllll* of its promise may never come to maturity... Its really one of the most polished docker all-in-one interfaces, but its muddled with issues so far... If anyone has any other suggestions I can look into, Idont need someone who is re-writing an entire os... Tectonic looks even less stable, but they are doing progress very quickly... I think I may have to go to something fully cli such as deis+kubernetes? who knows...

anyways, thanks for any help... I still like playing with rancher, despite it being very "all over the place".... (sorry but I'm being honest... I see great anouncements on the blog about wonderful features, but what about the basics??)

![image](https://cloud.githubusercontent.com/assets/1218902/12062333/a91dad50-af68-11e5-9bec-6e40ddebb1b1.png)


Also seems like nodes cant communicate within the rancher vpn?? 
![image](https://cloud.githubusercontent.com/assets/1218902/12062337/e6672ea2-af68-11e5-8fa1-9424f8454f6b.png)

This stuff was working a few versions back... such a pitty...

**Comment by deniseschannon** [comment] 2015-12-31 22:11
My CoreOS host is still up and running. But I just launched one up using Digital Ocean and didn't do a cluster or anything special. 

If the IP of the hosts aren't showing up correctly then you can launch the rancher/agent command with an additional `-e CATTLE_AGENT_IP=<ip_of_host>`. I have no issues when running with machines supported in GCE, DO, AWS, etc. I don't do much with trying to launch VMs and using them in Rancher, which may be where the difference is between what you're doing and what I'm doing.

**Comment by ibuildthecloud** [comment] 2015-12-31 23:53
@RVN-BR CoreOS stable is often not the best to run on because they lag pretty far behind in Docker versions.  At this point you're going to get the best experience with Rancher with Docker 1.9.1.  That means you need at least CoreOS 877.1.0 (beta channel).

Docker 1.8 was a very poor release for us.  They had some serious regression in the performance of the API which causes the "reconnecting" issues you are experiencing.  We worked with Docker to fix them and they are all included in 1.9.1, so again, please run CoreOS beta.

We try to autodetect the host IP.  In most realistic deployment scenarios this works well but unfortunately has issues in environments where people often "play" with Rancher, ie your laptop/vagrant.  For these situations you need to tell the rancher agent what IP you want to use.  This is what @deniseschannon mentioned, set `-e CATTLE_AGENT_IP=<ip_of_host>` in the rancher/agent command.

Sorry you are having so much trouble.  We try our best to make this easy, but honestly it's hard sometimes.  We are a startup, so we are a small group of very dedicated people working way too hard, but I wouldn't say we are spread too thin.  We do have plenty of people using Rancher in production and plenty of customers.  The issue with open source is that permutation are too great and change fast.  We have users running Docker 1.6-1.9 (and master builds) on various distributions and clouds.  For example, in November CoreOS stable was Docker 1.7 which was much more stable for us.  So a month ago Rancher on CoreOS would have seemed much better than it is now making it seem like we regressed in quality but in fact Docker changed not us.  You can't really complain, this is open sources and the joys of running bleeding edge.

**Comment by deniseschannon** [comment] 2016-03-04 21:28
@fentas Are you still seeing this issue? I was never able to reproduce it. If not, I'd like to close this issue.

**Comment by deniseschannon** [comment] 2016-03-04 21:58
Please re-open if you are still having these issues.

**Closed by deniseschannon** 2016-03-04 21:58 UTC
Labels: kind/question

**Comment by fentas** [comment] 2016-03-05 12:29
I have general problems CoreOS / RangerOS (mainly communication, cant ping managed containers etc.). I guess I saw already another open issue for this. Meanwhile I switched to Ubuntu (there all issues are gone).
Thanks a lot.
