### ISSUE TITLE
Kubernetes environment stuck at "Starting services (8 of 9)"

### ISSUE THREAD

**Issue by donghui** [rancher/rancher#5972] opened 2016-09-14 07:30 UTC
**Rancher Version:**v1.1.3

**Docker Version:**
1.12.1

**OS and where are the hosts located? (cloud, bare metal, etc):**
VMWare(ubuntu1404 and sentos7) in win7

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
single node rancher

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Kubernetes

**Steps to Reproduce:**Add Host to K8s environment and wait for initialization.

**Results:**
Initialization stuck at "Starting services (8 of 9)"

Log in Kubernetes_rancher-ingress-controller_1:
time="2016-09-14T14:00:38Z" level=error msg="Health check failed: unable to reach Kubernetes. Error: &url.Error{Op:\"Get\", URL:\"http://master/apis/extensions/v1beta1/ingresses\", Err:(*net.OpError)(0xc8201c3720)}"
time="2016-09-14T14:00:38Z" level=error msg="Healtcheck failed for LB controller"

**AND** I find there is a host named 'master' in my intranet network.
when I disconnect my computer 's network with the host named 'master', the setup is ok.

**Expected:**Successfully start K8s environment

**Related Issues:**[#5081](https://github.com/rancher/rancher/issues/5081)

**Comment by aemneina** [comment] 2016-09-16 18:36
kubernetes doesnt support docker 1.12 yet, can you downgrade docker to 1.10.3 and try again?

**Comment by tfiduccia** [comment] 2016-09-16 22:05
Duplicate of #5290

**Closed by tfiduccia** 2016-09-16 22:05 UTC

**Comment by donghui** [comment] 2016-09-18 06:48
**The reason:**
In #5290: kubelet container fails with the following error:
time="2016-06-30T00:56:51Z" level=fatal msg="Failed to find state.json" 

But in #5972 there is no such error. and Kubernetes_rancher-ingress-controller_1 can not start normally.
Log in Kubernetes_rancher-ingress-controller_1:
time="2016-09-14T14:00:38Z" level=error msg="Health check failed: unable to reach Kubernetes. Error: &url.Error{Op:\"Get\", URL:\"http://**master**/apis/extensions/v1beta1/ingresses\", Err:(*net.OpError)(0xc8201c3720)}"
time="2016-09-14T14:00:38Z" level=error msg="Healtcheck failed for LB controller"

I think when rancher-ingress-controller_1 execute health check using above url, it is using wrong ip address of master because there is another host named **master** in my local network. When I close network between my vmware and local network, setup can complete normally.

And i have  downgraded docker to 1.10.3 and try again. it still not working.

**Comment by aemneina** [comment] 2016-09-19 17:54
@donghui you're right in that the k8s stack will look for 'master' which maps to the kubernetes api service.

**Comment by pakuni** [comment] 2017-01-16 07:46
I am also facing similar issue it hangs up in service 2/10, my docker version is 1.12.6
