### ISSUE TITLE
Failed to create an AKS cluster

### ISSUE THREAD

**Issue by sheng-liang** [rancher/rancher#11473] opened 2018-02-17 05:28 UTC
Running the latest rancher/server:master

Create an AKS cluster. If I leave the resource group to the default "docker-machine" I got this error:

containerservice.ManagedClustersClient#CreateOrUpdate: Failure sending request: StatusCode=403 -- Original Error: autorest/azure: Service returned an error. Status=403 Code="AuthorizationFailed" Message="The client '30211224-d916-4684-83b8-655fd6b56001' with object id '30211224-d916-4684-83b8-655fd6b56001' does not have authorization to perform action 'Microsoft.ContainerService/managedClusters/write' over scope '/subscriptions/14a619f7-a887-4635-8647-d8f46f92eaac/resourceGroups/docker-machine/providers/Microsoft.ContainerService/managedClusters/cluster-mrbw9'."

If I change resource group to one I created, I got this error:

containerservice.ManagedClustersClient#CreateOrUpdate: Failure sending request: StatusCode=403 -- Original Error: autorest/azure: Service returned an error. Status=403 Code="AuthorizationFailed" Message="The client '30211224-d916-4684-83b8-655fd6b56001' with object id '30211224-d916-4684-83b8-655fd6b56001' does not have authorization to perform action 'Microsoft.ContainerService/managedClusters/write' over scope '/subscriptions/14a619f7-a887-4635-8647-d8f46f92eaac/resourceGroups/sheng-test/providers/Microsoft.ContainerService/managedClusters/shengaks'."

**Comment by deniseschannon** [comment] 2018-02-22 01:05
Duplicate of this: https://github.com/rancher/rancher/issues/11492

**Closed by deniseschannon** 2018-02-22 01:05 UTC
Labels: area/authentication, kind/bug, version/2.0

**Comment by anilreddy789** [comment] 2021-12-14 22:32
I got the same error do you know how to solve
