### ISSUE TITLE
rancher cluster dashboard status Unknown

### ISSUE THREAD

**Issue by beyondyinjl2** [rancher/rancher#30927] opened 2021-01-21 09:50 UTC
kubectl version --short
Client Version: v1.20.0
Server Version: v1.20.0

 kubectl get nodes
NAME          STATUS   ROLES                  AGE   VERSION
edge-node-1   Ready    agent,edge             26h   v1.19.3-kubeedge-v1.5.0
k8s-master    Ready    control-plane,master   27h   v1.20.0
node-2        Ready    <none>                 68m   v1.20.0

docker version
Version:           20.10.0

The old Rancher UI is in normal state
[https://github.com/beyondyinjl2/bug-images/blob/main/rancher/1611221308796.jpg](url)

The new rancher cluster dashboard status is unknown
[https://github.com/beyondyinjl2/bug-images/blob/main/rancher/1611221363683.jpg](url)
[https://github.com/beyondyinjl2/bug-images/blob/main/rancher/1611221335583.jpg](url)
[https://github.com/beyondyinjl2/bug-images/blob/main/rancher/1611221363683.jpg](url)
[https://github.com/beyondyinjl2/bug-images/blob/main/rancher/1611221384217.jpg](url)
[https://github.com/beyondyinjl2/bug-images/blob/main/rancher/1611221411795.jpg](url)

**Comment by superseb** [comment] 2021-01-21 10:05
Duplicate of https://github.com/rancher/rancher/issues/30556, do not use k8s 1.20 until https://github.com/rancher/rancher/issues/30134 is fixed

**Closed by superseb** 2021-01-21 10:05 UTC
