### ISSUE TITLE
Admin GUI in Chrome shows white page after update. Broken JS load

### ISSUE THREAD

**Issue by vemod** [rancher/rancher#4008] opened 2016-03-17 16:47 UTC
Rancher Version: 0.63.1, 0.63.0
Docker Version: Docker version 1.10.0, build 590d510 
OS: Linux 4.3.0-sabayon
Browser: Chrome 46

Steps to Reproduce: 
1. ```docker run -d --restart=always -p 8080:8080 rancher/server:latest```
2. Go to ```http://localhost:8080```
3. View Developer tools console

Results: 
* White page (because javascript file is not loaded)
* Developers tools Console logged: 
```
Failed to find a valid digest in the 'integrity' attribute for resource 'http://localhost:8080/assets/vendor-ef2d8c0ba9fbead853773dde7e2f49b2.js' with computed SHA-256 integrity 'fQX8Hv5RgYjrpyIvaPgXaP1hQwUmD9WQF50CyKg1qvg='. The resource has been blocked.
ui-ff548e9ae3e48f5760c70836d3559780.js:1 Uncaught ReferenceError: define is not defined
```
Expected:
No error in console
Usual Admin GUI loaded

In version 0.59.1 worked everything fine. After update broken. 
In Firefox 41 it works fine.

**Comment by deniseschannon** [comment] 2016-03-17 23:44
@tfiduccia Does this sound like a duplicate of https://github.com/rancher/rancher/issues/2977?

**Comment by vincent99** [comment] 2016-03-18 18:59
I haven't been able to reproduce this but it sounds like it's related to https://bugs.chromium.org/p/chromium/issues/detail?id=527286 .  Since we're hosting the resources from the rancher/server I don't think SRI is really that valuable and will just turn it off.

**Comment by tfiduccia** [comment] 2016-03-23 19:03
Version - master 3/23
Verified fixed
I also have not been able to reproduce this in latest builds

**Closed by tfiduccia** 2016-03-23 19:03 UTC
Labels: area/ui, kind/bug, status/resolved, status/to-test
