### ISSUE TITLE
Investigate why requests timeout on large objects only in kubernetes v1.19.10+ and v1.20+

### ISSUE THREAD

**Issue by rmweir** [rancher/rancher#32419] opened 2021-04-28 01:09 UTC
**Description:**
Large objects are causing kubernetes 1.20 to timeout and experience cpu spikes. A separate issue for reducing the size of the v3.catalog and v3.app catalogs has been created. This issue is for specifically investigating why this happens in 1.20, and probably versions after, and not 1.19.

**What kind of request is this (question/bug/enhancement/feature request):**
investigation/spike

**To observe an example of this:**
1. Run rancher on a 1.20 management cluster.
2. Enable monitoring.
3. Add bitnami catalog using url: https://charts.bitnami.com/bitnami.

**Result:**
Similar behavior to that described in https://github.com/rancher/rancher/issues/32175. The giant catalog object is causing subsequent updates to timeout and fail after it is created. These requests also seemingly cause kubernetes to have cpu spikes.

**Details:**
I have tested the object in a cluster without rancher installed and encountered the same behavior. I also have tried disabling a feature that is enabled by default in 1.20 and prioritizes api requests, https://kubernetes.io/docs/concepts/cluster-administration/flow-control/#enabling-disabling-api-priority-and-fairness, but it did not resolve the issue.

**Comment by cbron** [comment] 2021-05-06 23:44
We'll likely need to backport this and related issue to 2.5. Waiting to make issue until we have solution.

**Comment by nickgerace** [comment] 2021-05-26 18:03
## Status Summary

**Full summary:** we have not yet located the exact issue, but we have narrowed down where the exact issue may occur, and what effects it does have.
It would be ideal to continue investigation to find the exact cause(s), but from these conclusions, we are able to address https://github.com/rancher/rancher/issues/32418 and provide potential workarounds for other Rancher v2.x CRDs (only v3 Catalogs appear to be affected at the moment) that may run into this problem.

**Compressed summary:** we do not know the exact cause, but we are confident in its effects, so we may be able to provide workarounds.

**Bonus note:** we have also confirmed that issue appears in Kubernetes `v1.19.10`, which narrows our investigation between `v1.19.9` and `v1.19.10` (cross-referencing `v1.20.0` changes as well).

## Technical Details

**Note to readers: proceed to the next major section ("Suspects") if you do not need the technical details leading up to this status report.**

### What We Already Knew

- Attempting to update a large v3 Catalog results in hitting a 34s timeout on Kubernetes `v1.20.x` and `v1.21.x`
- Creating the standard Bitnami catalog (from: `https://charts.bitnami.com/bitnami`) and editing it results in the timeout

### Investigation

Our v3 Catalog payloads were the following (format: `[SIZE] [NAME]`):

- `744K` `bitnami` (matches upstream)
- `156K` `bitnami-medium` (cut down the `helmVersionCommits` field to prove a "delay" exists)
- `12K` `bitnami-small` (cut down the `helmVersionCommits` field to be minimal)

These catalogs were created with `kubectl create` as well as in the Ember UI.
In addition, the timeouts were encountered with `kubectl edit` as well as in the Ember UI.
All catalog creation and deletion requests were successful and completed in the same amount of time (within margin of error).
It its only the update requests that result in timeouts.

With an affected Kubernetes version, update `bitnami-small` took anywhere from 500ms to 1.5s, which is to be expected.
However, with the same version, the `bitnami-medium` updates took about 9s, which is approximately 9 times as long as a standard `bitnami` chart update in Kubernetes `v1.19.9`.
When trying to size down `bitnami-medium`, we tried a `~300K` version of the catalog.
This also encountered the 34s timeout, like the standard `~800K` `bitnami` catalog.
Thus, we can assume that the timeouts occur on an exponential scale relative to `helmVersionCommits` field size.

Our original test environments:
- Rancher `v2.5.7` with Kubernetes `v1.20.6` with [APF](https://kubernetes.io/docs/concepts/cluster-administration/flow-control/) enabled
- Rancher `v2.5.7` with Kubernetes `v1.20.6` with [APF](https://kubernetes.io/docs/concepts/cluster-administration/flow-control/) disabled
- Manual CRD create/update/delete events on Kubernetes `v1.20.6` with [APF](https://kubernetes.io/docs/concepts/cluster-administration/flow-control/) enabled

The original thought was that [APF](https://kubernetes.io/docs/concepts/cluster-administration/flow-control/) enablement may have been the root cause.
However, the issue was encountered on APF-disabled and APF-enabled clusters.
The stack traces looked slightly different due to how timeouts and API requests are handled dependent on feature enablement (i.e. red herring), but the same issue was encountered via the same reproduction method.

> We also looked at updating massive `ConfigMap` objects.
> Catalog v2 objects (API v1 and Dashboard UI) were evaluated as well, but they rely on large `ConfigMap` objects and are not large CRDs.
> In both scenarios, the issue was not able to be reproduced, as expected.

Afterwards, we encountered the issue consistently on Kubernetes `v1.19.10` and did not encounter the issue at all on Kubernetes `v1.19.9`.
Thus, the original test environments were only used for cross referencing for the remainder of the investigation leading to this status update.

Our current test environments used for A/B comparison:
- Rancher `v2.5.7` with Kubernetes `v1.19.10` 
- Rancher `v2.5.7` with Kubernetes `v1.19.9`

Here is an A/B comparison of the issue being encountered with RKE clusters with apiserver trace logging enabled (`v=9`) and `etcd` logging set to `debug`:

**Kubernetes `v1.19.10`: Failure**

```
{"log":"I0524 18:14:58.909153       1 trace.go:205] Trace[517308547]: \"Update\" url:/apis/management.cattle.io/v3/catalogs/bitnami,user-agent:rancher/v0.0.0 (linux/amd64) kubernetes/$Format,client:10.42.0.9 (24-May-2021 18:14:24.776) (total time: 34132ms):\n","stream":"stderr","time":"2021-05-24T18:14:58.909256173Z"}
{"log":"Trace[517308547]: ---\"About to convert to expected version\" 40ms (18:14:00.817)\n","stream":"stderr","time":"2021-05-24T18:14:58.909269518Z"}
{"log":"Trace[517308547]: ---\"Conversion done\" 86ms (18:14:00.904)\n","stream":"stderr","time":"2021-05-24T18:14:58.909274438Z"}
{"log":"Trace[517308547]: ---\"About to store object in database\" 0ms (18:14:00.904)\n","stream":"stderr","time":"2021-05-24T18:14:58.909278538Z"}
{"log":"Trace[517308547]: [34.132646488s] [34.132646488s] END\n","stream":"stderr","time":"2021-05-24T18:14:58.909282645Z"}
{"log":"I0524 18:14:58.909690       1 httplog.go:89] \"HTTP\" verb=\"PUT\" URI=\"/apis/management.cattle.io/v3/catalogs/bitnami\" latency=\"34.134316566s\" userAgent=\"rancher/v0.0.0 (linux/amd64) kubernetes/$Format\" srcIP=\"10.42.0.9:50804\" resp=504

// --snip-- (includes a massive Go stack trace for the 34s timeout)
```

**Kubernetes `v1.19.9`: Success**

```
{"log":"I0524 19:44:38.830372       1 trace.go:205] Trace[1249269041]: \"Update\" url:/apis/management.cattle.io/v3/catalogs/bitnami,user-agent:rancher/v0.0.0 (linux/amd64) kubernetes/$Format,client:10.42.0.9 (24-May-2021 19:44:37.434) (total time: 1395ms):\n","stream":"stderr","time":"2021-05-24T19:44:38.830478906Z"}
{"log":"Trace[1249269041]: ---\"About to convert to expected version\" 90ms (19:44:00.524)\n","stream":"stderr","time":"2021-05-24T19:44:38.830492121Z"}
{"log":"Trace[1249269041]: ---\"Conversion done\" 45ms (19:44:00.570)\n","stream":"stderr","time":"2021-05-24T19:44:38.830495559Z"}
{"log":"Trace[1249269041]: ---\"About to store object in database\" 0ms (19:44:00.570)\n","stream":"stderr","time":"2021-05-24T19:44:38.830498467Z"}
{"log":"Trace[1249269041]: ---\"Object stored in database\" 995ms (19:44:00.565)\n","stream":"stderr","time":"2021-05-24T19:44:38.830501078Z"}
{"log":"Trace[1249269041]: [1.395852414s] [1.395852414s] END\n","stream":"stderr","time":"2021-05-24T19:44:38.830503799Z"}
{"log":"I0524 19:44:38.830603       1 httplog.go:89] \"HTTP\" verb=\"PUT\" URI=\"/apis/management.cattle.io/v3/catalogs/bitnami\" latency=\"1.397209029s\" userAgent=\"rancher/v0.0.0 (linux/amd64) kubernetes/$Format\" srcIP=\"10.42.0.9:50150\" resp=200\n","stream":"stderr","time":"2021-05-24T19:44:38.830673687Z"}
```

Upon inspection, we can see where the error occurs in the apiserver:

```
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/handlers.UpdateResource.func1(0x50bd7a0, 0xc00d35f3a8, 0xc03b4b5300)
    /workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/handlers/update.go:205 +0x185a
```

From the stack trace, we know the following:

- The error is returned here: https://github.com/kubernetes/apiserver/blob/a6a7b4d54bb2e662954d071259e849bb19dd532c/pkg/endpoints/handlers/update.go#L205
- The error is encountered here: https://github.com/kubernetes/apiserver/blob/a6a7b4d54bb2e662954d071259e849bb19dd532c/pkg/endpoints/handlers/update.go#L191-L203
- The anonymous function used is created here: https://github.com/kubernetes/apiserver/blob/a6a7b4d54bb2e662954d071259e849bb19dd532c/pkg/endpoints/handlers/update.go#L173-L190
- Handler that we believe reports the error: https://github.com/kubernetes/apiextensions-apiserver/blob/abdf1a09fb7c600f2355e721d5154142297f243e/pkg/apiserver/customresource_handler.go#L379

The error reported by the apiserver stems from logic added in `v1.19.0`.

**Commit:** https://github.com/kubernetes/apiserver/commit/a87d964ed19cdfa7f190dbdaa9112d4f5725ae5e

We now know where the errors occurs and why it may be generated, but we still need to know what changed between `v1.19.9` and `v1.19.10` (and `v1.20.0` by extension).

> It's worth mentioning that the maximum request size has [remained the same](https://github.com/kubernetes/apiserver/blob/43fcd462edb8e3dc6d376d1798bc6eabaff658ea/pkg/server/config.go#L324) across all versions tested ~(1.3MB).

## Suspects

Most of these were found by performing `git bisect` with the following tree comparisons:
- https://github.com/kubernetes/kubernetes/compare/v1.19.9...v1.19.10
- https://github.com/kubernetes/kubernetes/compare/v1.19.9...v1.20.0

### Structured Merge Diff v4.0.2

The module `structured-merge-diff` handles the logic for server-side apply.
In our case, this module is used for our `Update` request, which uses the `PUT` http method with the following url: `/apis/management.cattle.io/v3/catalogs/<payload>`.
This module was updated to `v4.0.3` between Kubernetes `v1.19.9` (`v4.0.1`) and `v1.19.10`, but it was only updated to `v4.0.2` in Kubernetes `v1.20.0`.
Thus, we performed `git bisect` between `v4.0.1` and `v4.0.2` to investigate the potential cause.

**Comparison:** https://github.com/kubernetes-sigs/structured-merge-diff/compare/v4.0.1..v4.0.2

Potential culprits here include walking and descending on schema fields (potentially exponential) and reconciling managed fields with schema changes.
None of these have been proven to be the culprit.

### Lease Manager Changes in apiserver

Our investigation here did not result in anything conclusive.
There are several lease manager changes to `etcd`, including a decreased default maximum object count.

**Primary commit:** https://github.com/kubernetes/kubernetes/commit/3820a5d819582d4f6b4652757a3cc6c1a04692b4

**Secondary commits:**
- https://github.com/kubernetes/kubernetes/commit/537b8d3c06e869a6c00e9b645607ab03a09c9adb
- https://github.com/kubernetes/kubernetes/commit/42a3d75bf87a59c402ac72dd369ffe898cf8eb7b

This has not been proven to be the culprit.

### Protobuf v1.3.2

We are highly doubtful this is related, but it was investigated to be sure.

**Commit:** https://github.com/kubernetes/kubernetes/commit/15596cedd26c3afacf719a92c79c28e51051a959

This has not been proven to be the culprit.

### Other PRs to Look Into

**PRs:**
- https://github.com/kubernetes/kubernetes/pull/100713/files
- https://github.com/kubernetes/kubernetes/pull/100450/files

None of these have been proven (or are even likely) to be the culprit.

## Next Steps

We may be able to address https://github.com/rancher/rancher/issues/32418 and https://github.com/rancher/rancher/issues/32175 since we do not need to even have a `helmVersionCommits` field in the v3 Catalog status.

> We are able to do this because we have access to fields' contents already [via CatalogTemplates](https://github.com/rancher/rancher/blob/629146a3fbbc8d5677aecece78e627580dd7c95d/pkg/catalog/manager/traverse.go#L57).

It would be ideal to continue investigation to be sure that our fixes will work, and that other Rancher CRDs may not encounter the issue in the future.

> Potential ideas include: creating a new apiserver with `structured-merge-diff v4.0.1`

Yet, we may have enough information to solve the v3 Catalog update timeouts in particular.

**Comment by nickgerace** [comment] 2021-06-09 22:12
File an upstream issue: https://github.com/kubernetes/kubernetes/issues/102749

We hope to potentially find the root cause and provide more information to the upstream issue as investigation progresses.

**Comment by nickgerace** [comment] 2021-06-25 20:13
First part of the upstream fixed has been merged: https://github.com/kubernetes-sigs/structured-merge-diff/pull/200

Second part is yet to be posted: https://github.com/kubernetes-sigs/structured-merge-diff/pull/200#issuecomment-868741632

**Comment by nickgerace** [comment] 2021-06-30 22:00
The upstream issue has been closed. This will move to "To Test" once there are patch releases out containing this change: https://github.com/kubernetes/kubernetes/issues/102749

**Comment by samjustus** [comment] 2021-12-29 21:29
this issue may be able to be closed because other issues have been created to track related bugs, only thing left has been moved to a kubernetes issue

**Comment by brudnak** [comment] 2022-01-06 05:02
# My checks PASSED

## Reproduction Environment


| Component               | Version / Type                          |
| ----------------------- | --------------------------------------- |
| Rancher version         | v2.5.7                                  |
| Rancher cluster type    | HA                                      |
| K8s                     | v1.20.4                                 |
| Helm version            | v2.16.8-rancher1                        |
| Downstream cluster type | N/A                                     |
| Downstream K8s version  | N/A                                     |
| Browser type            | Google Chrome                           |
| Browser version         | 96.0.4664.110 (Official Build) (x86_64) |

## Reproduction steps


Add the Bitnami catalog - Tools -> Catalogs, add URL= as a global catalog. Version =Helm v3


1. Enable v1 monitoring on local cluster (so you can get see CPU graphs)
2. Add the Bitnami catalog
    - Hover over `Tools` -> click `Catalogs` -> click `Add Catalog`
    - Fill out the add catalog form
    - Name: `bitnami`
    - Catalog URL: `https://charts.bitnami.com/bitnami`
    - Branch: `master`
    - Scope: `global`
    - Helm Version: `Helm v3`
    - Click `Create`
3. Wait about an hour, then check the CPU utilization
  
### RESULTS

CPU is maxed out for an hour. Bitnami stays stuck in a state of `Refreshed` in the Catalogs screen. After CPU being maxed for ~60 minutes then it starts having spikes every 15 minutes.
  
<hr>
  
## Validation Environment

| Component               | Version / Type                          |
| ----------------------- | --------------------------------------- |
| Rancher version         | v2.6.3                                  |
| Rancher cluster type    | HA                                      |
| K8s version             | v1.21.7                                 |
| Helm version            | v2.16.8-rancher1                        |
| Downstream cluster type | N/A                                     |
| Downstream K8s version  | N/A                                     |
| Browser type            | Google Chrome                           |
| Browser version         | 96.0.4664.110 (Official Build) (x86_64) |

## Validation steps

1. Enable monitoring on the local cluster
2. Add the Bitnami
3. Wait about an hour, then check the CPU utilization
  
### RESULTS

No CPU spikes were observed.

**Closed by brudnak** 2022-01-06 05:02 UTC
Labels: [zube]: QA Working, QA/XS, release-note
