### ISSUE TITLE
Update Rancher Helm version to v2.14.0

### ISSUE THREAD

**Issue by Wykiki** [rancher/rancher#21041] opened 2019-06-21 08:52 UTC
**What kind of request is this (question/bug/enhancement/feature request):**
Enhancement

**Steps to reproduce (least amount of steps as possible):**
Install Spinnaker 1.12.0 from Stable Helm charts.

**Result:**
```
lastUpdateTime": "2019-06-21T08:24:41Z",
"message": "wait helm template failed. Error: parse error in \"spinnaker/templates/configmap/service-settings.yaml\": template: spinnaker/templates/configmap/service-settings.yaml:37: function \"mergeOverwrite\" not defined\n: exit status 1",
"reason": "Error",
"status": "Unknown",
"type": "Installed"
```

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): v2.2.4
- Installation option (single install/HA): HA

- Docker version (use `docker version`):

```
Client:
 Version:           18.06.1-ce
 API version:       1.38
 Go version:        go1.10.3
 Git commit:        e68fc7a
 Built:             Tue Aug 21 17:20:43 2018
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          18.06.1-ce
  API version:      1.38 (minimum version 1.12)
  Go version:       go1.10.3
  Git commit:       e68fc7a
  Built:            Tue Aug 21 17:28:38 2018
  OS/Arch:          linux/amd64
  Experimental:     false
```

I was unable to install Spinnaker 1.12.0 (first install).
As an alternative, I had to install Spinnaker 1.8.2.

**Comment by superseb** [comment] 2019-06-21 08:58
Duplicate of https://github.com/rancher/rancher/issues/16971

**Closed by superseb** 2019-06-21 08:58 UTC
