### ISSUE TITLE
TF test_app_namespace_annotation 

### ISSUE THREAD

**Issue by alena1108** [rancher/rancher#24365] opened 2019-12-03 19:57 UTC
Following TF was observed on master branch:

```
=================================== FAILURES ===================================
 6376 ________________________ test_app_namespace_annotation _________________________
 6377 [gw4] linux -- Python 3.7.5 /go/src/github.com/rancher/rancher/tests/integration/.tox/py37/bin/python3.7
 6378
 6379 admin_pc = <suite.conftest.ProjectContext object at 0x7f19b203f310>
 6380 admin_mc = <suite.conftest.ManagementContext object at 0x7f19b22be310>
 6381
 6382     def test_app_namespace_annotation(admin_pc, admin_mc):
 6383         client = admin_pc.client
 6384         ns = admin_pc.cluster.client.create_namespace(name=random_str(),
 6385                                                       projectId=admin_pc.
 6386                                                       project.id)
 6387         wait_for_template_to_be_created(admin_mc.client, "library")
 6388         app1 = client.create_app(
 6389             name=random_str(),
 6390             externalId="catalog://?catalog=library&template=mysql&version=0.3.7"
 6391                        "&namespace=cattle-global-data",
 6392             targetNamespace=ns.name,
 6393             projectId=admin_pc.project.id,
 6394         )
 6395         wait_for_workload(client, ns.name, count=1)
 6396
 6397         external_id = "catalog://?catalog=library&template=wordpress" \
 6398                       "&version=1.0.5&namespace=cattle-global-data"
 6399         app2 = client.create_app(
 6400             name=random_str(),
 6401             externalId=external_id,
 6402             targetNamespace=ns.name,
 6403             projectId=admin_pc.project.id,
 6404         )
 6405         wait_for_workload(client, ns.name, count=3)
 6406         ns = admin_pc.cluster.client.reload(ns)
 6407         ns = wait_for_app_annotation(admin_pc, ns, app1.name)
 6408         ns = wait_for_app_annotation(admin_pc, ns, app2.name)
 6409         client.delete(app1)
 6410         wait_for_app_to_be_deleted(client, app1)
 6411
 6412         ns = admin_pc.cluster.client.reload(ns)
 6413         assert app1.name not in ns.annotations['cattle.io/appIds']
 6414         assert app2.name in ns.annotations['cattle.io/appIds']
 6415
 6416         client.delete(app2)
 6417         wait_for_app_to_be_deleted(client, app2)
 6418         ns = admin_pc.cluster.client.reload(ns)
 6419 >       assert 'cattle.io/appIds' not in ns.annotations
 6420 E       assert 'cattle.io/appIds' not in {'cattle.io/appIds': '', 'cattle.io/status': '{"Conditions":[{"Type":"InitialRolesPopulated","Status":"True",      "Message"...":"True","Message":"","LastUpdateTime":"2019-12-03T19:31:43Z"}]}', 'lifecycle.cattle.io/create.namespace-auth': 'true'}
 6421 E        +  where {'cattle.io/appIds': '', 'cattle.io/status': '{"Conditions":[{"Type":"InitialRolesPopulated","Status":"True","Message"...":"True","M      essage":"","LastUpdateTime":"2019-12-03T19:31:43Z"}]}', 'lifecycle.cattle.io/create.namespace-auth': 'true'} = {'actions': {'move': 'https://172.17.0.      3:8443/v3/cluster/local/namespaces/random-40230-1575401502?action=move'}, 'anno...'transitioning': 'no', 'transitioningMessage': '', 'type': 'namespac      e', 'uuid': '88f5a649-1603-11ea-91c9-0242ac110003'}.annotations
 6422
 6423 test_app.py:222: AssertionError
```

**Comment by dramich** [comment] 2019-12-04 00:21
Duplicate of https://github.com/rancher/rancher/issues/24273

**Closed by dramich** 2019-12-04 00:21 UTC
Labels: kind/flaky-test
