### ISSUE TITLE
RKE2 cluster control plane log do not have metadata fields such as "time" and "pod id"

### ISSUE THREAD

**Issue by AmartC** [rancher/rancher#32917] opened 2021-05-26 23:48 UTC
RKE2 cluster on one node is producing control plane log messages which have no "time" field. Rather, the "message" field contains the actual timestamp. 

Example:
```
'message': '[2021/05/26 23:04:04] [error] [io_tls] flb_io_tls.c:359 X509 - Certificate verification failed, e.g. CRL, CA or signature check'
```

**Comment by cbron** [comment] 2021-06-02 20:58
We should be grabbing the rke2 metadata here via the CRI log format, so that users can filter on more data like id or time. There is currently a workaround for this, but now that RKE2 will be natively supported it is more important.

**Comment by cjellick** [comment] 2021-06-04 16:11
I'm editing the title to represent the broader issue caleb called out that other metadata fields are not being captured.

**Comment by dbason** [comment] 2021-06-04 19:33
It also seems that any k8s metadata (labels, namespace, etc) is missing from the RKE2 logs.  When I checked it looks like the Fluentbit Kubernetes plugin is getting an error communication with the API
````
2021-06-03T05:28:52.108105601Z stderr F [2021/06/03 05:28:52] [error] [filter:kubernetes:kubernetes.0] upstream connection error
2021-06-03T05:28:52.185546847Z stderr F [2021/06/03 05:28:52] [error] [io_tls] flb_io_tls.c:359 X509 - Certificate verification failed, e.g. CRL, CA or signature check
```

**Comment by paynejacob** [comment] 2021-06-07 16:12
The missing metadata on pod logs is likely related to https://github.com/k3s-io/k3s/issues/3392

**Comment by paynejacob** [comment] 2021-06-18 21:49
The solution to this is going to be to write custom parsers for all the rke2 system logs.  As of right now I know of the following formats:

- k3s
- klog
- etcd

**Comment by snasovich** [comment] 2021-07-14 22:11
@SheilaghM , assigning it to @nickgerace since he's the other Logging SME and we cannot have it validated by who implemented it (Jacob).

**Comment by brendarearden** [comment] 2021-08-11 01:02
Validation: NOT PASSING - there seems to be issues with some of the logging messages

Steps to recreate:
- From an HA rancher setup ( rancher `version: v2.6-69055ba8d07b05f1c4e632e7f4b2d54a005ec332-head`)
- Deploy a downstream RKE2 cluster with multiple nodes - Digital Ocean, k8s version `v1.21.3-rc4+rke2r2`
- Install rancher-logging v3.9.400
- Install example logging application and flows from `https://github.com/paynejacob/rancher-logging-examples`
- Edit the cluster flow to forward to my local ngrok endpoint `ngrok tcp 24224` that is setup to display the forwarded logs on the stdout of `docker run fluent/fluent-bit -p 24224:24224 /fluent-bit/bin/fluent-bit -i forward -o stdout` 
- See various logs for the different systems running and that they do not have all the metadata on the logs

Steps to Validate:
- From an HA rancher setup ( rancher `version: v2.6-69055ba8d07b05f1c4e632e7f4b2d54a005ec332-head`)
- Deploy a downstream RKE2 cluster with multiple nodes - Digital Ocean, k8s version `v1.21.3-rc4+rke2r2`
- Install rancher-logging v100.0.0+up3.12.0
- Install example logging application and flows from `https://github.com/paynejacob/rancher-logging-examples`
- Edit the cluster flow to forward to my local ngrok endpoint `ngrok tcp 24224` that is setup to display the forwarded logs on the stdout of `docker run fluent/fluent-bit -p 24224:24224 /fluent-bit/bin/fluent-bit -i forward -o stdout` 
- Per dev instructions, I restarted the node to generate logs since logs are not showing up as frequently as they did in previous versions
- Logs show up in weird blocks of text with no formatting
```
??stream?stdout?logtag?F?message?S[2021-08-11T00:09:01Z] @ERROR Carthaginem da da adversis ob pro ita. 941 ::0.243499?kubernetes??pod_name??rancher-logging-example-0-1628639585-log-generator-labeled78zl4?namespace_name?default?pod_id?$b-?labels??app.kubernetes.io/instance?$rancher-logging-example-0-1628639585?app.kubernetes.io/name?log-generator?pod-template-hash?7c875464fc?rancher.logging.example/app?log-generator?annotations??!cni.projectcalico.org/containerID?-?cni.projectcalico.org/podIP?10.42.2.23/32?cni.projectcalico.org/podIPs?10.42.2.23/32?kubernetes.io/psp?global-unrestricted-psp?host?brenda-rke2-pool1-sdjc5?container_name?log-generator?docker_id?-?container_hash?jdocker.io/paynejacob/log-generator@sha256:50be51e7d797faa0e474e1514057c49811175678af431c95249963b4695c5b87?container_image?)docker.io/paynejacob/log-generator:latest??a0n3???stream?stdout?logtag?F?message?O[2021-08-11T00:09:02Z] @WARNING Pulvis ita sui innecto, se dixi. 942 ::0.899625?kubernetes??pod_name??rancher-logging-example-0-1628639585-log-generator-labeled78zl4?namespace_name?default?pod_id?$b8b96d0d-4186-421e-abd5-eea1144c6272?labels??app.kubernetes.io/instance?$rancher-logging-example-0-1628639585?app.kubernetes.io/name?log-generator?pod-template-hash?7c875464fc?rancher.logging.example/app?log-generator?annotations??!cni.projectcalico.org/containerID?@8a9c1a5 
```
I am seeing logs in normal formatting as well: 
```
{"stream":"stdout","logtag":"F","message":"      <match>","kubernetes":{"pod_name":"rancher-logging-fluentd-configcheck-105c47f4","namespace_name":"cattle-logging-system","pod_id":"-","labels":{"app.kubernetes.io/component":"fluentd-configcheck","app.kubernetes.io/managed-by":"rancher-logging","app.kubernetes.io/name":"fluentd"},"annotations":{"cni.projectcalico.org/containerID":"-","cni.projectcalico.org/podIP":"10.42.2.29/32","cni.projectcalico.org/podIPs":"10.42.2.29/32","kubernetes.io/psp":"global-unrestricted-psp"},"host":"brenda-rke2-pool1-sdjc5","container_name":"fluentd","docker_id":"-","container_hash":"-","container_image":"docker.io/rancher/mirrored-banzaicloud-fluentd:v1.12.4-alpine-1"}}
```
and I see more metadata is being captured when the logs are formatting correctly
```
{"stream":"stdout","logtag":"F","message":"        labels rancher.logging.example/app:log-generator","kubernetes":{"pod_name":"rancher-logging-fluentd-configcheck-105c47f4","namespace_name":"cattle-logging-system","pod_id":"5743f6e1-f3e3-4f4b-8bca-f727cc58d47b","labels":{"app.kubernetes.io/component":"fluentd-configcheck","app.kubernetes.io/managed-by":"rancher-logging","app.kubernetes.io/name":"fluentd"},"annotations":{"cni.projectcalico.org/containerID":"0f63b02b8cd1311a551692fed4455f817beaf94c99a5f9efa08db0e79a21f4b0","cni.projectcalico.org/podIP":"10.42.2.29/32","cni.projectcalico.org/podIPs":"10.42.2.29/32","kubernetes.io/psp":"global-unrestricted-psp"},"host":"brenda-rke2-pool1-sdjc5","container_name":"fluentd","docker_id":"2f5f0be6cb8a9f9d85a1c2dba9321cd57b08da27d1767d0440792dbd8681d4db","container_hash":"docker.io/rancher/mirrored-banzaicloud-fluentd@sha256:d56646c8c100eb97cdb2f95bca3aee51a2c08b3a80dda9022bb9cff96ec8bd66","container_image":"docker.io/rancher/mirrored-banzaicloud-fluentd:v1.12.4-alpine-1"}}
```

**Comment by paynejacob** [comment] 2021-08-11 23:49
I dug into this a bit, I think the issue is with the fluentbit the logs are being forwarded to not rancher logging.  If I use an http output it always receives valid messages and if I run a fluentbit container with the stdout format set to json_lines I cannot reproduce the malformed messages.  My guess is this has something to do with fluentbit's stdout fliter displaying messagepack messages.  Fluentd does not report any errors writing the message nor does the fluentbit output log anything about the messages being invalid.

**Comment by brendarearden** [comment] 2021-08-12 15:14
Validation: PASSED

Steps to recreate:

1. From an HA rancher setup ( rancher version: v2.6-69055ba8d07b05f1c4e632e7f4b2d54a005ec332-head)
2. Deploy a downstream RKE2 cluster with multiple nodes - Digital Ocean, k8s version v1.21.3-rc4+rke2r2
3. Install rancher-logging v3.9.400
4. Install example logging application and flows from https://github.com/paynejacob/rancher-logging-examples
5. Edit the cluster flow to forward to my local ngrok endpoint `ngrok tcp 24224` that is setup to display the forwarded logs on the stdout of docker run `fluent/fluent-bit -p 24224:24224 /fluent-bit/bin/fluent-bit -i forward -o stdout -p 'format=json_lines'`
6. See control plane logs with no additional metadata
```
[0] rke2: [1628713785.508274562, {"stream"=>"stderr", "logtag"=>"F", "message"=>"2021-08-11 20:29:45.508050 I | etcdserver/api/etcdhttp: /health OK (status code 200)"}]

[8] rke2: [1628713807.538172617, {"stream"=>"stderr", "logtag"=>"F", "message"=>"I0811 20:30:07.535406       1 client.go:360] parsed scheme: "passthrough""}]
```

Steps to Validate:

1. From an HA rancher setup ( rancher version: v2.6-69055ba8d07b05f1c4e632e7f4b2d54a005ec332-head)
2. Deploy a downstream RKE2 cluster with multiple nodes - Digital Ocean, k8s version v1.21.3-rc4+rke2r2
3. Install rancher-logging v100.0.0+up3.12.0
4. Install example logging application and flows from https://github.com/paynejacob/rancher-logging-examples
5. Edit the cluster flow to forward to my local ngrok endpoint` ngrok tcp 24224` that is setup to display the forwarded logs on the stdout of `docker run fluent/fluent-bit -p 24224:24224 /fluent-bit/bin/fluent-bit -i forward -o stdout -p 'format=json_lines'`
6. Per dev instructions, I restarted the node to generate logs since logs are not showing up as frequently as they did in previous versions
7. See that all control plane logs have metadata included. 
```
{"date":1628750148.314976,"stream":"stderr","logtag":"F","message":"I0812 06:35:48.314927       1 passthrough.go:48] ccResolverWrapper: sending update to cc: {[{https://127.0.0.1:2379  <nil> 0 <nil>}] <nil> <nil>}","kubernetes":{"pod_name":"kube-apiserver-brenda6-rke2-pool1-p4jjb","namespace_name":"kube-system","pod_id":"4be60557-08c5-4282-8538-3b1c0a6effcd","labels":{"component":"kube-apiserver","tier":"control-plane"},"annotations":{"kubernetes.io/config.hash":"51c3f430b6f4c1a1abe4e1f5d4e83248","kubernetes.io/config.mirror":"51c3f430b6f4c1a1abe4e1f5d4e83248","kubernetes.io/config.seen":"2021-08-11T22:51:06.946626661Z","kubernetes.io/config.source":"file","kubernetes.io/psp":"global-unrestricted-psp"},"host":"brenda6-rke2-pool1-p4jjb","container_name":"kube-apiserver","docker_id":"ef4f1a1cf43d5c059b36e8535a5680bc3726703995a2905798247b96ee092384","container_hash":"docker.io/rancher/hardened-kubernetes@sha256:c0c57b2f0cf055e091f25c8f89c992796dee35d0d7c278fe55896abeeee5574b","container_image":"docker.io/rancher/hardened-kubernetes:v1.21.3-rke2r2-build20210809"}}

{"date":1628752800.090297,"stream":"stderr","logtag":"F","message":"2021-08-12 07:20:00.084047 I | etcdserver/api/etcdhttp: /health OK (status code 200)","kubernetes":{"pod_name":"etcd-brenda6-rke2-pool1-p4jjb","namespace_name":"kube-system","pod_id":"2c76b0bb-57fd-4e1c-bfaf-fcf5eb075334","labels":{"component":"etcd","tier":"control-plane"},"annotations":{"etcd.k3s.io/initial":"{\"initial-advertise-peer-urls\":\"https://147.182.203.62:2380\",\"initial-cluster\":\"brenda6-rke2-pool1-p4jjb-7dcd4662=https://147.182.203.62:2380\",\"initial-cluster-state\":\"new\"}","kubernetes.io/config.hash":"0e193b262c2b74e7bc208d9359d10a16","kubernetes.io/config.mirror":"0e193b262c2b74e7bc208d9359d10a16","kubernetes.io/config.seen":"2021-08-11T22:50:55.615606803Z","kubernetes.io/config.source":"file","kubernetes.io/psp":"global-unrestricted-psp"},"host":"brenda6-rke2-pool1-p4jjb","container_name":"etcd","docker_id":"6a06bedafaf450fa4cd431d5420ffaa3dd607bb546a74b545e2be3a4e10c530e","container_hash":"docker.io/rancher/hardened-etcd@sha256:8029d886dc07fa99df5739ca45b42ea443374b59a5ca4811b62f02c685041b27","container_image":"docker.io/rancher/hardened-etcd:v3.4.13-k3s1-build20210223"}}

```
Note: Since logs outputs are different across all pods / cluster resources, it is not possible to guarantee a separate metadata for "time". It will be separated out when possible, but it is not something that can be guaranteed to be there for every log.

**Closed** 2021-08-13 01:25 UTC
Labels: area/logging, [zube]: QA Working, status/dev-validate, QA/XS, release-note
