### ISSUE TITLE
[k8s] Node label set by kubectl can't be synced back to cattle?

### ISSUE THREAD

**Issue by pengjiang80** [rancher/rancher#5751] opened 2016-08-17 10:31 UTC
kubernetes-agent can sync host labels from cattle to k8s successfully. But it seems it can't sync k8s label back to cattle. Step to repro:
1. Use kubectl to set a node label: kubectl label node host01 foo=bar.
2. kubectl describe node host01 and confirmed the label was set successfully
3. In Rancher UI, check the host label and it doesn't update accordingly
---

| Useful | Info |
| :-- | :-- |
| Versions | Rancher `v1.2.0-pre2-rc3` Cattle: `v0.168.2` UI: `v1.2.7` |
| Access | `Disabled` |
| Orchestration | `Kubernetes` |
| Route | `hosts.index` |

**Comment by alena1108** [comment] 2016-10-14 20:19
Labels propagation was added to k8s 1.4 Rancher 1.2. But it works the other way around - you set labels on the hosts in Rancher, not in Kubectl, and then they get propagated to k8s. It is done this way because node object can get changed on host going up/down, and keeping original label info in Rancher is more reliable.

**Comment by alena1108** [comment] 2016-10-14 20:19
Can we make sure this works in Rancher 1.2, k8s 1.4?

**Comment by galal-hussein** [comment] 2016-10-17 23:06
@alena1108 This feature didn't work in k8s 1.4, I tested it on Rancher v1.2.0-pre4-rc4, here are my steps:

1- I added label foo=bar on one of the nodes in Rancher
2- Installed K8S 1.4 environment
3- Checked for nodes labels using kubectl get nodes --show-labels

**Comment by alena1108** [comment] 2016-10-18 00:42
@wlan0 could you take a look

**Comment by wlan0** [comment] 2016-10-18 22:32
This issue is a regression caused by the introduction of a rancher label containing `: (semi-colon)`. Rancher started adding a label to denote the agent version on the host - `"io.rancher.host.agent_image": "rancher/agent:v1.1.0-rc2"`

This label has the `:`, which is not an allowed value in kubernetes. Whenever we add a hostlabel, this label also gets picked up, and an error. Therefore, it also prevents other labels from being added.

I've added a fix https://github.com/rancher/kubernetes-agent/pull/30, that skips invalid labels from being processes, and sends only valid labels to kubernetes

**Comment by deniseschannon** [comment] 2016-11-04 20:57
@pengjiang80 @galal-hussein  We will only support host label propagation from Rancher UI to kubernetes host, but we will not support adding labels to kubernetes hosts using kubectl and syncing to show up in the Rancher UI. 

@galal-hussein It seems like there was a regression found when trying to do host label propagation when set in the Rancher UI and having it show up in the k8s hosts. 

Can you verify the following workflow?

1. Add a label to a host in k8s through Rancher UI
2. Check that the label is on the host using `kubectl describe node`

If that works, can you please close the issue.

**Comment by galal-hussein** [comment] 2016-11-04 21:11
@deniseschannon verified on rc6:

```
kubectl get nodes hussein-catalog-10acre-2.c.rancher-dev.internal --show-labels
NAME                                              STATUS    AGE       LABELS
hussein-catalog-10acre-2.c.rancher-dev.internal   Ready     1h        beta.kubernetes.io/arch=amd64,beta.kubernetes.io/i
nstance-type=rancher,beta.kubernetes.io/os=linux,failure-domain.beta.kubernetes.io/region=Region1,failure-domain.beta.ku
bernetes.io/zone=FailureDomain1,foo=bar,io.rancher.host.docker_version=1.12,io.rancher.host.linux_kernel_version=4.4,kub
ernetes.io/hostname=hussein-catalog-10acre-2.c.rancher-dev.interna
```
You can see foo=bar lablel which i added through Rancher UI.

**Closed by galal-hussein** 2016-11-04 21:11 UTC
Labels: area/host, area/kubernetes, kind/bug, status/reopened, status/resolved, status/to-test
