### ISSUE TITLE
 issue: scheduling update

### ISSUE THREAD

**Issue by jas99** [rancher/rancher#2245] opened 2015-10-07 00:46 UTC
When i update a label on host the container should tear down automatically as per scheduling rule I created. But I think the scheduling logic is not rechecked after label is deleted or edited on host.

Jas

**Comment by deniseschannon** [comment] 2015-10-07 18:52
Deleting a label does not remove the containers of the service, but adding a label **does** work. 

Reproduced  in v0.40.0 that deleting a label does not re-schedule/remove the container. Either with a global service or a service of a specific scale.

**Comment by deniseschannon** [comment] 2015-10-07 18:57
Actually, this is a duplicate of https://github.com/rancher/rancher/issues/1006

**Closed by deniseschannon** 2015-10-07 18:57 UTC
Labels: area/scheduler
