### ISSUE TITLE
Treat "Reconnecting" hosts as "Inactive" on Scheduling process

### ISSUE THREAD

**Issue by cusspvz** [rancher/rancher#2260] opened 2015-10-07 23:44 UTC
As you may know, some of my hosts are being stuck into a "Reconnecting" state (#2196). Problem is that most of my experimental deployments are getting stuck because Containers are being scheduled into those hosts.

In the future, to avoid scheduling containers on machines that went down (maybe because of a machine failure), scheduler shouldn't deploy containers on those.

**Comment by deniseschannon** [comment] 2015-10-08 03:29
This is a duplicate of https://github.com/rancher/rancher/issues/1173

**Comment by cusspvz** [comment] 2015-10-08 11:30
@deniseschannon

**Closed** 2015-10-08 11:30 UTC
