### ISSUE TITLE
User is logged out two times and had to login back after a rancher server upgrade to 2.6

### ISSUE THREAD

**Issue by sowmyav27** [rancher/rancher#34149] opened 2021-08-10 23:24 UTC
**Rancher Server Setup**
- Rancher version: master-head commit id: `723f747b`
- Installation option (Docker install/Helm Chart): HELM
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): RKE1
- Proxy/Cert Details: Rancher generated

**Information about the Cluster**
- Kubernetes version: 1.20.9 (Local cluster) 
- Downstream clusters - GKEv2 and RKE1 Custom cluster

**Describe the bug**
User is logged out two times after a rancher server upgrade to 2.6

**To Reproduce**

- On 2.5.9, HA install, deploy a few downstream clusters
- Upgrade (Helm upgrade) to 2.6-head
- User is redirected to dashboard page but is logged out
- Log back in, and navigate to Home page
- User is logged out one more time.
- After another logging in, user is able to proceed with using Rancher 

**Expected Result**
User be logged out only one time?

**Comment by paynejacob** [comment] 2021-08-12 19:11
@sowmyav27 did you see any pod restarts on the rancher pods in this setup?

**Comment by deniseschannon** [comment] 2021-08-12 20:54
@paynejacob This most likely is due to having HA (multiple Rancher server pods) so when Rancher server starts back up, each node is clearing the UI session tokens.

**Comment by paynejacob** [comment] 2021-08-12 20:56
The migration is only run on the leader pod and is gated by a configuration map after that.  I think what might have happened is the rancher pod crashed for some reason in the middle of the tokens being invalided and on restart it did not see the configmap that says it ran and started again.  I am testing some logic to prevent this.

**Comment by dramich** [comment] 2021-08-13 22:32
@paynejacob We are seeing this being reproduced by restarting rancher in an HA setup running 2.6-head. cc: @git-ival

**Comment by paynejacob** [comment] 2021-08-13 22:38
@dramich ill test my solution with this and see if I can still reproduce

**Comment by dramich** [comment] 2021-08-13 22:43
@paynejacob Repro the issue first, but I am seeing `2021/08/13 22:28:23 [INFO] Detected v2.6.0 upgrade, forcing logout for all web users` in the logs, so definitely hitting this.

**Comment by paynejacob** [comment] 2021-08-18 16:20
Here is the expected behavior:

anytime a helm upgrade occurs and the versions are the same users should not be logged out.

| dev          | dev   | *-head | < v2.6. 0-rc1 | > v2.6.0-rc1 |
|--------------|-------|--------|---------------|--------------|
| *-head       | false | true   | true          | true         |
| < v2.6.0-rc1 | false | true   | true          | -            |
| > v2.6.0-rc1 | false | true   | false         | false        |

**Comment by sowmyav27** [comment] 2021-08-18 22:43
**On 2.6.0-rc4, reproduced the issue**

- deploy a HA
- Set password and login
- restart the leader Rancher pod
- User is logged out

**Comment by paynejacob** [comment] 2021-08-18 22:45
The fix for this is not in 2.6.0-rc4.

**Comment by sowmyav27** [comment] 2021-08-18 22:48
**Upgraded from 2.6.0-rc4 to 2.6-head commit id: `9d5c699`**

- User is seen Logged out right after helm upgrade of rancher.

**Closed** 2021-08-22 17:39 UTC
Labels: kind/bug-qa, [zube]: QA Working
