### ISSUE TITLE
Alerting v1 not triggering/sending notifications on 2.5-head

### ISSUE THREAD

**Issue by slickwarren** [rancher/rancher#31365] opened 2021-02-18 00:34 UTC
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
* setup Rancher v2.5-head 03b8153 single-install
* configure downstream cluster (tested with ubnt 18.04 and centos-8.3.2011)
* add webhook/slack notifier
* add rule that triggers (such as `any pod event`) (should be alerting v0.21.0)

**Result:**
* no alert is triggered through rancher (therefore nothing is sent to the notifier)

* also verified this is still working on 2.5.6-rc4 with the same (v0.21.0) alerting version. 

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): v2.5-head 03b8153
- Installation option (single install/HA): single install

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): linode, aws (node driver)
- Machine type (cloud/VM/metal) and specifications (CPU/memory):
- Kubernetes version (use `kubectl version`):v1.20.2

- Docker version (use `docker version`): 20.10.3

**Comment by angeloudy** [comment] 2021-02-18 01:37
I am seeing the same issue.
Running V2.5.2.
The notification sometimes work sometimes don't.
I do see that the alert was triggered and it was showing red on rancher but somehow not sending notification.

**Comment by aiyengar2** [comment] 2021-02-19 00:13
I was able to reproduce this and found the following relevant log line:
```
2021/02/18 15:50:49 [ERROR] Failed to send alert: Post "http://alertmanager-operated.cattle-prometheus.svc:9093/api/v1/alerts": dial tcp: lookup alertmanager-operated.cattle-prometheus.svc on 67.207.67.2:53: no such host
```

**Comment by aiyengar2** [comment] 2021-02-19 00:17
This seems to be related to https://github.com/rancher/rancher/issues/19688, which also shows similar logs due to being unable to reach the service.

**Comment by aiyengar2** [comment] 2021-02-19 01:22
As suspected in https://github.com/rancher/rancher/issues/31365#issuecomment-781720455, the controller that [sends the alert](https://github.com/rancher/rancher/blob/release/v2.5/pkg/controllers/managementuser/alert/manager/alertmanager.go#L322) cannot resolve the k8s DNS for `http://alertmanager-operated.cattle-prometheus.svc:9093/api/v1/alerts` due to an issue with proxying the request from the controller to the cluster via `cattle-cluster-agent`.

This seems to be due to a change in the default DNS policy of `cattle-cluster-agent`; while before it was set to `""` (which [defaults to `"ClusterFirst"`](https://kubernetes.io/docs/concepts/services-networking/dns-pod-service/#pod-s-dns-policy), it was changed to `"Default"` as part of https://github.com/rancher/rancher/commit/90b90ba4ed9efe87cb4988b148b2b15a155e6b16#diff-b4bd6cbbe08fbeb2e8dee40950e7529314bde076c10ee72a4a3ba97f04a8d3ddR106.

As requested offline, I'm transferring this issue to @luthermonson to take a look at the fix.

#### Workaround

On creating the cluster experiencing this issue:

1. `kubectl edit deployment -n cattle-system cattle-cluster-agent`
2. Modify `spec.template.spec.dnsPolicy` from `Default` to `ClusterFirst` and save
3. Alerts should work as expected

**Comment by izaac** [comment] 2021-02-19 23:39
Reproduced this in the upgrade path: `v2.5.5` -> `v2.5.6-rc5`
loggin chart gets upgraded: `0.2.0` -> `0.2.1`

**Comment by slickwarren** [comment] 2021-02-24 16:45
alerts are now coming through on 2.5-head (87006de30625c046523a329b03ea2580db35fb57)
* add a notifier ( I used slack) 
* add a simple alert (if pod event happens, send alert to your notifier ; if node usage exceeds 10%, send alert)
however on master head (465bb3b80cb9f2d8c002fa9d7c37be20d38ed411) following the same steps as above, alerts are still not coming through

**Comment by aiyengar2** [comment] 2021-02-25 00:16
Root cause is tied to https://github.com/rancher/rancher/issues/31467. The`/yaml` response made to try to update alertmanager is entirely broken in 2.5.6-rc5, so no alerting rules or alerting groups can be added to modify the alertmanager configuration at the moment.

Awaiting fix from https://github.com/rancher/rancher/issues/31467

**Comment by kravciak** [comment] 2021-02-25 12:05
I can confirm this works on v2.5-head (87006de) but it's still broken on master-head (465bb3b).
Notification was sent from master-head once (from ~10 tries).
I used slack and `Pod-Not-Running` notification on default namespace.

**Closed** 2021-02-26 18:16 UTC
Labels: [zube]: QA Next up, kind/bug-qa
