### ISSUE TITLE
Deploy mongodb clustrer

### ISSUE THREAD

**Issue by yankunsam** [rancher/rancher#10384] opened 2017-11-22 06:49 UTC
*Describe your issue here*

' (Failed to allocate instance [container:1i742]: Bad instance [container:1i742] in state [error]: Allocation failed: No healthy hosts meet the resource constraints: [instanceReservation: 1, instanceReservation: 1, 27017:27017/tcp portReservation, instanceReservation: 1].) 

I have tried, by rancher, it only succeed deploy one mongodb node.
---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v1.6.10` Cattle: `v0.183.22` UI: `v1.6.23` |
|Access|`localauth` `admin`|
|Orchestration|`Cattle`|
|Route|`catalog-tab.launch`|

**Comment by superseb** [comment] 2017-11-24 12:53
With what scale did you start the item? By default it is 3, which will need 3 hosts to launch successfully. Closing as not a bug, but we can still discuss.

**Closed by superseb** 2017-11-24 12:53 UTC

**Comment by yankunsam** [comment] 2017-11-26 14:21
You can have a try. I have 4 hosts to match the default 3. So please fix it and then close. Thanks

**Comment by iquizzle** [comment] 2017-12-12 00:57
I have had the same problem. 3 hosts available, only successfully deployed on 1 host. The remaining 2 post the message yankunsam posted above.

**Comment by harrisrobin** [comment] 2017-12-12 06:28
same problem

**Comment by thinhnd8752** [comment] 2017-12-12 10:08
we got the same problem too.

**Comment by mdchao2010** [comment] 2018-01-02 10:59
same problem

**Comment by gkapkowski** [comment] 2018-01-04 11:00
Can we reopen the issue?

I've removed port mapping from mongodb cluster but I'm still unable to setup the cluster

|Versions|Rancher `v1.6.10` Cattle: `v0.183.22` UI: `v1.6.23` |
|Access|`github` `admin`|
|Orchestration|`Cattle`|
|Route|`service.containers`|

My message is now:
```
(Failed to allocate instance [container:1i277331]: Bad instance [container:1i277331] in state [error]: Allocation failed: Host must satisfy resource constraints: [instanceReservation: 1, instanceReservation: 1]. host must not have a container with label io.rancher.stack_service.name=databases/mongo-cluster, host must not have a container with label io.rancher.stack_service.name=databases/mongo-cluster/mongo-base, host must not have a container with label io.rancher.stack_service.name=databases/mongo-cluster/mongo-datavolume) 
```

**Comment by gkapkowski** [comment] 2018-01-04 15:21
### Version 3.4-rancher1 doesn't work for me
### Version 3.2-rancher2 works for me

**Comment by mdchao2010** [comment] 2018-01-05 00:55
modify mongodb clustrer docker compse file

**Comment by mdchao2010** [comment] 2018-01-05 00:55
modify mongodb clustrer docker-compose file:

**Comment by mdchao2010** [comment] 2018-01-05 00:56
modify mongodb clustrer docker-compose file,will be ok

- mongo-datavolume:
    image: busybox
    entrypoint:
    - /bin/true
    **volumes:
    - /data/db**

**Comment by exocode** [comment] 2018-03-14 12:56
some progress on that?

I tried to use @mdchao2010 s attempt, but that failed also with ` No healthy hosts meet the resource constraints: [instanceReservation: 1, instanceReservation: 1, 27017:27017/tcp portReservation, instanceReservation: 1].)`

I hope thats correct:

```yaml

version: '2'
volumes:
  mongodata:
    driver: local
services:
  mongo-datavolume:
    image: busybox
    entrypoint:
    - /bin/true
    volumes:
    - mongodata:/data/db**
    labels:
      io.rancher.scheduler.affinity:host_label: role=database

```

If I get that working: I will give a try to update the Plugin to "MongoDB Version 3.6". So please help us to fix that

**Comment by thbiela** [comment] 2018-03-16 16:09
@exocode try this on your mongodata volume:

```
    volumes:
    - /data/db
```

**Comment by exocode** [comment] 2018-03-21 09:26
for those who run into the same problems. I am experimenting with a own rancher-compose.yml and docker-compose.yml which seems to start successfully (connection to a container not tested yet).

In order to get it working I removed the exposing ports (these made problems) as well I updated the mongodb image to version 3.6. My next steps are to manage a persistent storage based on xfs instead of ext4, which is highly recommended by the mongodb company itself.

Any suggestions are welcome


```yaml
mongo-cluster:
  restart: always
  environment:
    MONGO_SERVICE_NAME: mongo-cluster
    CATTLE_SCRIPT_DEBUG: true
  entrypoint: /opt/rancher/bin/entrypoint.sh
  command:
  - --replSet
  - "rs0"
  image: mongo:3.6
  labels:
    io.rancher.container.hostname_override: container_name
    io.rancher.sidekicks: mongo-base, mongo-datavolume
  volumes_from:
    - mongo-datavolume
    - mongo-base
mongo-base:
  restart: always
  net: none
  labels:
    io.rancher.container.hostname_override: container_name
    io.rancher.container.start_once: true
  image: rancher/mongodb-conf:v0.1.1
  stdin_open: true
  entrypoint: /bin/true
mongo-datavolume:
  net: none
  labels:
    io.rancher.container.hostname_override: container_name
    io.rancher.container.start_once: true
  volumes:
    - /data/db
  entrypoint: /bin/true
  image: busybox
```

```yaml
.catalog:
  name: "MongoDB Replica Set"
  version: "3.2-rancher1"
  description: "MongoDB Replica Set"
  uuid: mongodb-1
  minimum_rancher_version: v0.46.0
mongo-cluster:
  scale: 3
  retain_ip: true
  metadata:
    mongo:
      yml:
        replset.name: "rs0"


```

**Comment by markqiu** [comment] 2018-03-23 08:08
deploy sucessfully. But how to connect to the cluster from outside?

**Comment by exocode** [comment] 2018-03-23 08:32
that's the big question. Create a new service called "test" within this stack with the following settings:

- image: ubuntu -->> 14.04.3
- ports: 27017 -->> 27017
- links: mongo-cluster -->> db
- click "create"
After this service spins up you will be able to go to the hosts, click the "test_1" service and "exec shell" and type "ping -c 3 db".

As you can see the service db pings back.

- My question is now, how to upload existing data? :-)
- How to make the volumes persistent? (I am trying this now with Rexray and Virtualbox) - you can follow the progress here: https://github.com/rexray/rexray/issues/1194

**Comment by markqiu** [comment] 2018-03-23 09:02
thanks @exocode

**Comment by exocode** [comment] 2018-03-24 09:06
Maybe you @galal-hussein can help us to bring the community driven MongoDB up again. It seems that the exposed port 27017 raises that issue. Also a `version 3.6` tag would be nice.

Only one `Stack: MongoDB-community -  mongo-cluster-1` comes up. The cluster-2 and cluster-3 stuck because of the already exposed port. 

```
(Failed to allocate instance [container:1i2665]:
  Bad instance [container:1i2665] in state [error]: 
    Allocation failed:
       No healthy hosts meet the resource constraints:
          [instanceReservation: 1, 
          instanceReservation: 1, 
          27017:27017/tcp portReservation,
          instanceReservation: 1].)
```

Thank you in advance

**Comment by mvittiglio** [comment] 2018-09-14 21:05
Kinda crazy that this seems to still be an issue. Any update would be most appreciated.

**Comment by zou2699** [comment] 2018-12-14 07:52
~~~sh
version: '2'
volumes:
  mongodata:
    driver: local
    per_container: true
services:
  mongo-datavolume:
    image: busybox
    entrypoint:
    - /bin/true
    volumes:
    - mongodata:/data/db
~~~
add **per_container: true** can solve the problem.

**Comment by jlambright** [comment] 2019-04-15 02:59
This still seems to be an issue. Has there been any progress on this?
