### ISSUE TITLE
gke and eks operators api *string type doesn't match at generated rancher go cli

### ISSUE THREAD

**Issue by rawmind0** [rancher/rancher#32440] opened 2021-04-28 21:17 UTC
**What kind of request is this (question/bug/enhancement/feature request):**

Bug

**Steps to reproduce (least amount of steps as possible):**

Use go client API binding to create a GKEv2 cluster, letting `Cluster.GKEConfig.ClusterIpv4CidrBlock` empty

**Result:**

Error creating GKEv2 cluster from google api, saying that `clusterIpv4CidrBlock` can't be nil creating a cluster

**Other details that may be helpful:**

Setting `ClusterIpv4CidrBlock=""` (string) is saved at Rancher API as  `clusterIpv4CidrBlock=nil`  (*string)
Setting `description=""` (string) is saved at Rancher API as `description=""`  (string)

Checked that gke-operator `*string` API type fields are generated as `string` type fields at rancher go cli 
* type [GKEClusterConfigSpec](https://github.com/rancher/gke-operator/blob/master/pkg/apis/gke.cattle.io/v1/types.go#L35) at gke-operator API
* type [GKEClusterConfigSpec](https://github.com/rancher/rancher/blob/master/pkg/client/generated/management/v3/zz_generated_gke_cluster_config_spec.go#L29) at rancher generated go cli 

Same thing happens at eks-operator:
* type [EKSClusterConfigSpec](https://github.com/rancher/eks-operator/blob/master/pkg/apis/eks.cattle.io/v1/types.go#L40) at eks-operator API
* type [EKSClusterConfigSpec](https://github.com/rancher/rancher/blob/master/pkg/client/generated/management/v3/zz_generated_eks_cluster_config_spec.go#L28) at rancher generated go cli 

This is generating an issue when using the Rancher go cli binding,  making that some string values can’t be set as empty string `""`.

**Comment by cbron** [comment] 2021-05-02 20:41
Goal in testing for now is just to ensure common functionality with EKS provider. Then bump it back to reopened.

**Comment by cbron** [comment] 2021-05-14 04:05
For QA: this will specifically need to be tested in GKE, and GKE should be tested again to ensure this doesn't trigger any regression around syncing. I believe same for AKS/EKS, confirming that.

**Comment by cmurphy** [comment] 2021-05-17 23:48
This will need a UI change for at least GKE: `clusterIpv4CidrBlock` and `maintenanceWindow` needs to send `""` instead of `null` in the create request.

**Comment by cmurphy** [comment] 2021-05-19 20:13
Status: changes are merged in norman and gke-operator, gke-operator needs a new tag and added to Rancher go.mod. WIP PR for that is here https://github.com/rancher/rancher/pull/32502 but needs a UI fix before it can be updated and merged.

**Comment by cmurphy** [comment] 2021-06-28 15:47
Since this issue is not user-facing I don't think QA needs to directly validate it, except to make sure that general GKE and EKS functionality works as normal. @rawmind0, can you check that this fixes the client issues for the terraform provider?

**Comment by aaronRancher** [comment] 2021-06-30 00:05
Testing GKE is currently blocked by this issue: https://github.com/rancher/rancher/issues/31592#issuecomment-870997073

**Comment by aaronRancher** [comment] 2021-07-16 23:16
Tested on Rancher `master-head` `version 44bb5b4` with the following steps:
- From Rancher dashboard UI, deploy EKSv2 and GKEv2 clusters.
- Make an edit to the clusters (ex: scale the node pool)
- Import EKSv2 and GKEv2 clusters.
- Make an edit to the clusters (ex: scale the node pool)
- Using Terraform Rancher2 provider version `1.16.0`, deploy EKSv2 and GKEv2 clusters.
- Using Terraform, edit the clusters (ex: scale the node pool)

Result:
EKSv2 clusters can be created from Rancher UI, imported from Rancher UI, and created with Terraform Rancher2 provider. Clusters are available in Rancher and EKS console.
EKS operator version `v1.1.1-rc7`. `k8s version v1.20.4`
Edits made from Rancher and Terraform Rancher2 provider are successful and are reflected in Rancher and EKS console. Clusters were provisioned with Terraform using rancher managed launch templates and with preexisting launch templates.

GKEv2 clusters can be created from Rancher UI, imported from Rancher UI, and created with Terraform Rancher2 provider. Clusters are available in Rancher and GKE console.
GKE operator version `v1.1.1-rc8`. `k8s version 1.19.9-gke.1900`
Edits made from Rancher and Terraform Rancher2 provider are successful and are reflected in Rancher and GKE console.

**Comment by aaronRancher** [comment] 2021-07-19 23:29
Tested on Rancher `master-head` `version d3ad5d3` with the following steps:
- From Rancher Dashboard UI, deploy an AKSv2 cluster
- Import an AKSv2 cluster
- Make an edit to the clusters (ex: add a node pool)

Result:
AKSv2 clusters can be created/imported from Rancher UI. Clusters are available in Rancher and AKS console.
AKS operator version `v1.0.1-rc16`. K8s version `v1.19.9`
Edits made from Rancher are successful and are reflected in Rancher and AKS console.

AKSv2 needs to be tested on Terraform Rancher2 Provider.
Will continue testing when AKSv2 on Terraform provider becomes available: https://github.com/rancher/rancher/issues/31296

**Comment by rawmind0** [comment] 2021-07-29 16:30
AKS support for Rancher2 terraform provider will be added with this PR https://github.com/rancher/terraform-provider-rancher2/pull/711

**Comment by aaronRancher** [comment] 2021-08-03 00:06
Will track AKSv2 testing in this issue: https://github.com/rancher/rancher/issues/33889
EKSv2 and GKEv2 have been validated with the above [steps](https://github.com/rancher/rancher/issues/32440#issuecomment-881766428).
Closing issue.

**Closed by aaronRancher** 2021-08-03 00:06 UTC
Labels: QA/XS, [zube]: QA Next up, area/aks, area/eks, area/gke
