### ISSUE TITLE
RKE Downstream Clusters missing after Upgrade to 2.6.3

### ISSUE THREAD

**Issue by PlayMTL** [rancher/rancher#35956] opened 2021-12-22 21:05 UTC
**Rancher Server Setup**
- Rancher version: 2.6.3
- Installation option (Docker install/Helm Chart):
   - Docker Single Host (Ubuntu)
- Proxy/Cert Details: 
  - HTTP-Proxy & SelfSigned Cert

**Information about the Cluster**
- Kubernetes version: 1.20
- Cluster Type (Local/Downstream):
   - Rancher: local (Single Host k3s)
   - Missing: Downstream-Cluster (Custom, but created by Rancher (RKE1))

**Describe the bug**

- When I upgrade Rancher to Version 2.6.3 (from 2.6.2 or 2.5.9) the Downstream-Clusters are not listed anymore.
- Strange behavior is, that you have to set a new Admin password (maybe the whole configuration is wiped? / I didn't test that)

**To Reproduce**

- You need to have an RKE(1) provisioned Downstream Cluster
- Upgrade the Single Host Docker Rancher Install from 2.5.9 or 2.6.2 to Rancher 2.6.3
- You are forced to create /  read out a new admin password
- In the Cluster-Management the RKE downstream cluster is missing

**Result**

**Expected Result**

- The Downstream Clusters are not "missing" & i don't need to set a new admin password when upgrading

**Screenshots**

**Additional context**

**Comment by l3system** [comment] 2021-12-23 08:28
The exact same thing happened here.
Configured clusters disappear completely from rancher gui (clusters still run as normal though).

**Comment by TechXProd** [comment] 2021-12-23 11:32
Hi,

same thing here : upgraded from 2.6.2 and all the configuration has gone (had ton put a new admin password)

**Comment by niusmallnan** [comment] 2021-12-24 04:12
Please try this: https://github.com/rancher/rancher/issues/35955#issuecomment-1000641550

**Comment by snasovich** [comment] 2021-12-28 00:40
Closing as duplicate of https://github.com/rancher/rancher/issues/35955

**Closed by snasovich** 2021-12-28 00:40 UTC
