### ISSUE TITLE
Upgrade Service Auto Restart is not taken into account

### ISSUE THREAD

**Issue by kevinliteon** [rancher/rancher#4122] opened 2016-03-25 10:45 UTC
When I upgrade a service and I check option Auto Restart "Always", service keeping "never (Start Once)"

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v0.63.0` Cattle: `v0.155.0` UI: `v0.94.0` |
|Access|`localauth` `admin`|
|Route|`service.new`|

**Comment by deniseschannon** [comment] 2016-03-27 04:28
Duplicate of https://github.com/rancher/rancher/issues/3707. Verified fixed in v1.0.0-rc4

**Closed by deniseschannon** 2016-03-27 04:28 UTC

**Comment by kevinliteon** [comment] 2016-03-27 14:44
thank you :+1:
