### ISSUE TITLE
Pod deleted by rancher after scale deployment  with rancher

### ISSUE THREAD

**Issue by colinlabs** [rancher/rancher#13655] opened 2018-05-23 07:44 UTC
**Rancher versions:**
rancher/server or rancher/rancher: v2.0.1
rancher/agent or rancher/rancher-agent: v2.0.1

**Infrastructure Stack versions:**
kubernetes (if applicable): v1.10.1

**Docker version:**
17.03.2-ce

**Operating system and kernel:**
16.04.3 LTS (Xenial Xerus) 
4.4.0-105-generic

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
Alicloud

**Steps to Reproduce:**
deploy kubernetes with **kubespray**
run deployment with cmd `kubectl run test --image=nginx:alpine --port 80 --replicas=2`

**Results:**
scale deployment test  up to `3` pod  with rancher, 2 pod before had delete, and run new 3 pod

![wechatimg8](https://user-images.githubusercontent.com/10361796/40410272-f21060dc-5e9f-11e8-8766-53aecd7e15ca.jpeg)

**Comment by loganhz** [comment] 2018-05-23 08:07
I can reproduce this issue in 2.0.1
The scale function sometimes will remove old pods.
Sometimes works well.

**Comment by alena1108** [comment] 2018-05-26 00:03
@colinlabs there are several issues caused by applying certain defaults for template spec field on deployment update, causing pods upgrade; one for `securityContext` (fixed by https://github.com/rancher/types/pull/453), another fix - this time on rancher side - is needed for ports, will work on that. Those issues are presented when update is run on a deployment started natively, via kubectl.

@loganhz you should see pods recreation only when you change something in spec. Have you done any sort of updates in the UI by any chance, along with the scale? I can easily reproduce the issue by starging the deployment natively, but not via UI (unless again, you make some other changes)

**Comment by loganhz** [comment] 2018-05-26 00:09
@alena1108 no, I just clicked the `plus` button on UI.
It looks like you can reproduce it by creating a new workload and scale it like 3 times.

**Comment by loganhz** [comment] 2018-05-30 09:08
I just added the image name in UI and clicked create. I will try again on master.

**Comment by alena1108** [comment] 2018-05-31 16:28
@ibuildthecloud when natively created deployment, having ports, gets updated in Rancher, annotation `field.cattle.io/ports` gets inserted into the container spec because ports in rancher API is annotation field (to support certain custom parameters). That annotation insertion triggers pods recreate. So we should either:

a) never insert  annotations for annotation fields for objects created natively. We can limit it to deployment/pod/container.spec only as this insertion has the most impact

b) Document the fact that when object is created natively - via kubectl - updating it via Rancher UI/API can trigger pods recreate. I incline towards this option as in most of the cases if user prefers kubectl as a client, he'd use it for all operations. Plus a) would introduce inconsistency in how updates are done for native vs objects created via rancher api.

**Comment by alena1108** [comment] 2018-06-11 18:12
Going with option b), and closing this issue in favor of https://github.com/rancher/docs/issues/278

**Comment by loganhz** [comment] 2018-06-27 04:09
Hi @alena1108 , I still can see this issue in v2.0.4. The deployment is created via UI (not kubectl). Please see the gif

![test](https://user-images.githubusercontent.com/21168270/41952481-ab025f28-7a02-11e8-8927-ab416100d5ce.gif)

**Comment by alena1108** [comment] 2018-06-29 21:23
@loganhz: we have a separate issue for that (https://github.com/rancher/rancher/issues/14171), lets keep this one close as it was filed specifically for created via kubectl -> updated via rancher.

**Closed by alena1108** 2018-06-29 21:23 UTC
Labels: feedback/wechat, kind/bug, version/2.0
