### ISSUE TITLE
Wrong icon for Longhorn app in Apps & Marketplace

### ISSUE THREAD

**Issue by khushboo-rancher** [rancher/rancher#32412] opened 2021-03-18 14:12 UTC
The icon of Longhorn is appearing wrong on the App & Marketplace with master-head `2dca0c6`
<img width="1513" alt="Screen Shot 2021-03-18 at 7 32 52 PM" src="https://user-images.githubusercontent.com/60111667/111639351-2f12ed80-8821-11eb-96a2-25fe30d60ffd.png">

Expected Icon:
<img width="385" alt="Screen Shot 2021-03-18 at 7 40 24 PM" src="https://user-images.githubusercontent.com/60111667/111640039-ced07b80-8821-11eb-81e4-e19fb31ba47c.png">

**Comment by aiyengar2** [comment] 2021-06-09 01:24
#### master-head (`b0c0eb4`)

![Screen Shot 2021-06-08 at 6 20 16 PM](https://user-images.githubusercontent.com/13127443/121277780-2f51e080-c886-11eb-9c93-17f20ac855a5.png)

#### v2.5-head (`d2a5514`)

![Screen Shot 2021-06-08 at 6 23 23 PM](https://user-images.githubusercontent.com/13127443/121277992-9d96a300-c886-11eb-9803-8f6f13cfe6af.png)

@khushboo-rancher since the issue is not reproducible in the latest master-head and v2.5-head, we should be safe to close this out right?

**Comment by jenting** [comment] 2021-06-09 04:54
The issue is not reproducible because, at Longhorn v1.1.1 chart, we change the icon from `.svg` to `.png`.
If you roll back to use the Longhorn v1.1.0 chart, I think the issue is reproducible.

**Comment by khushboo-rancher** [comment] 2021-07-13 17:57
I see https://github.com/rancher/rancher/issues/33100 is not resolved yet, not sure if this is fixed.
Should we change Longhorn icon from `.png` and `.svg` and icon will appear?

**Comment by snasovich** [comment] 2021-07-14 16:51
Since the icon is working in the latest Longhorn chart (as it's PNG), this is bumped out to v2.6.2 milestone.
Followibng the fix for #33100 , we can update the icon back to SVG and that's when this will need to be retested.

**Comment by aiyengar2** [comment] 2021-07-30 16:23
Reproducible by directly requesting the backend API for the icon related to the version of Longhorn that uses PNGs:

`RANCHER_URL/v1/catalog.cattle.io.clusterrepos/rancher-charts?chartName=longhorn&link=icon&version=1.1.001` returns:

![Screen Shot 2021-07-30 at 9 23 26 AM](https://user-images.githubusercontent.com/13127443/127682724-6f8d846d-fdf9-4223-8121-ba05af772836.png)

**Comment by aiyengar2** [comment] 2021-07-30 20:56
Root cause of this issue is https://github.com/rancher/rancher/blob/5e3b154abc2b697bcd4124bfa7a38f0d7398ae5a/pkg/catalogv2/http/download.go#L65.

`path.Ext(u.String())` does not necessarily represent the suffix since a URL with url encoded params can have elements after the file extension. e.g. in this case, the value returned for the suffix was `.svg?sanitize=true`.

The simple fix here is to replace `u.String()` with `u.Path`, which returns just the path without URL-encoded elements.

**Comment by aiyengar2** [comment] 2021-07-30 20:57
Note for QA: This is reproducible by trying to access the URL `RANCHER_URL/v1/catalog.cattle.io.clusterrepos/rancher-charts?chartName=longhorn&link=icon&version=1.1.001` even in master-head.

**Comment by davidnuzik** [comment] 2021-11-17 17:23
**My checks PASSED**
 
**Reproduction Environment:**

Rancher version: v2.6.2
Rancher cluster type: single-node docker install
Docker version: 20.10
 
Downstream cluster type: n/a 
Downstream K8s version: n/a
 
**Reproduction steps:**

1. Reproduce the issue by navigating to `RANCHER_URL/v1/catalog.cattle.io.clusterrepos/rancher-charts?chartName=longhorn&link=icon&version=1.1.001` Notice that when we do this, the server responds to this GET request with a type of plain (plaintext) therefore, it is rendered as plain text of the SVG content in the browser:
![image](https://user-images.githubusercontent.com/45179589/142249630-4c5497b3-ca7c-4b5a-9ea2-8f45cbca05a4.png)
 
-----
 
**Validation Environment:**

Rancher version: v2.6-head `78b25c3` 11/16/2021
Rancher cluster type: single-node docker install
Docker version: 20.10
 
Downstream cluster type: n/a
Downstream K8s version: n/a
 
**Validation steps:**

1. Validate the issue by navigating to `RANCHER_URL/v1/catalog.cattle.io.clusterrepos/rancher-charts?chartName=longhorn&link=icon&version=1.1.001` Notice that when we do this, the server now responds to this GET request with a type of SVG (svg image) therefore, it is rendered properly as an SVG image in the browser:
![image](https://user-images.githubusercontent.com/45179589/142249934-2a850df9-3e70-429a-9971-52a387ee4fec.png)

 
**Additional Info:**

Validation in the UI by actually navigating to the charts will be done via https://github.com/rancher/rancher/issues/33100 at a later time. Once that validation happens the longhorn icon should be switched back to SVG. Currently it is a PNG and thus shows correctly (but does not validate in the UI on the Charts page until that issue is resolved).

**Closed by davidnuzik** 2021-11-17 17:23 UTC
Labels: [zube]: QA Working, QA/XS
