### ISSUE TITLE
[RKE1] Bug in node lookup for external aws cloud provider 

### ISSUE THREAD

**Issue by kinarashah** [rancher/rancher#43624] opened 2023-11-27 18:11 UTC
Steps to Reproduce: 

Rancher v2.8-head 
- Provision v1.27 cluster (will reproduce on any valid k8s version with `external-aws` cloud provider) 
    - 2 controlplane, 1 etcd and 1 worker node 
    - Make sure to meet all prerequisites for setting up aws cloud provider (tags, iam profile etc) 
    - Select `External AWS` option as cloud provider
- Wait for cluster to come up active 
- Download kubconfig of the downstream cluster to run checks during cluster upgrade 
- Upgrade cluster by changing any valid kubelet argument (I added extra_args: max-pods) 
- Check which nodes get cordoned during the upgrade process. Only one node gets cordoned, instead of each node being cordoned when it's picked for processing. 

RKE v1.5.0-rc10 standalone 
- Provision v1.27 cluster 
- 2 controlplane, 1 etcd and 1 worker node 
- Set external-aws in cluster.yml
```
cloud_provider:
  name: external-aws
  useInstanceMetadataHostname: true
  ```
- Run `rke up` 
- Only one node has the assigned role, other nodes have role `none`

**Comment by snasovich** [comment] 2023-11-29 16:04
https://drone-publish.rancher.io/rancher/rancher/11029 progressed far enough so there is now updated `v2.8-head` image on DockerHub and the issue is ready for testing.

**Comment by kinarashah** [comment] 2023-11-29 16:08
RKE standalone version for testing: `v1.5.0-rc11`

**Comment by slickwarren** [comment] 2023-11-30 23:52
tested the following on rancher v2.8-head (337e2c6) on a hardened local cluster running rke2 v1.27.7:
* fresh install of rke1 usnig external-aws cloud provider -- pass
* rke1 cluster using in-tree aws, upgrade to external-aws (observe that throughout the process, cordoned nodes are properly uncordoned) -- pass
* standalone rke1 with external-aws -- pass with workaround [(docs ticket filed here)](https://github.com/rancher/rke/issues/3445)
* etcd snapshot and restore on external-aws cluster (etcd only, k8s upgrade, all) -- pass

@kinarashah I will close this issue since we have the docs request tracked in another ticket.

**Closed by slickwarren** 2023-11-30 23:52 UTC
Labels: area/rke, [zube]: QA Working, status/release-blocker
