### ISSUE TITLE
In the View Config of a stack, values that require $ are not being exported into the yml correctly. 

### ISSUE THREAD

**Issue by sshipway** [rancher/rancher#3244] opened 2016-01-12 22:43 UTC
If your Catalogue template needs to include a '$', then there is no way to do this; the template process assumes this to be a variable expansion.

EG: docker-compose.yml (simplified for clarity)
````
ssl-proxy:
  image: sshipway/nginx:1.9.9
  tty: true
  stdin_open: true
  ports:
    - ${PPORT}:443/tcp
  links:
    - portus:portus
  environment:
    NGINX_CONFIG: proxy_set_header X-Forwarded-Host \$http_host;
````

The `${PPORT}` will be correctly expanded.  We do not want the `$http_host` to be expanded; however the initial backstroke is ignored and this becomes `proxy_set_header X-Forwarded-Host \\;`.

I have tried this with and without a backstroke (no difference).  There is no template variable http_host defined and yet a replacement is attempted anyway.

Possible solutions -
- Require variable name ot be upper case, or require the {} surrounding the variable name
- Allow backstroke escapes to the $ symbol
- Replace templating system with Go Templates (so when in Go mode the $x expansion will not happen) - see #3239

**Comment by deniseschannon** [comment] 2016-01-12 22:47
Have you tried a $$? I know that's what we had used for some other places that required a $, but not sure if that would fix your situation.

**Comment by sshipway** [comment] 2016-01-12 23:19
A `$$` is not replaced by anything, but remains doubled and so is again not working.  I was hoping for `$$foo` to become `$foo`.

Assuming there is no defined variable `$foo` then:
 - `$foo`  becomes blank
 - `\$foo` becomes `\\`
 - `$$foo` becomes `$$foo`

**Comment by joshwget** [comment] 2016-03-08 23:32
@sshipway I tested two different values for `NGINX_CONFIG` with the latest version of Rancher Compose.

`proxy_set_header X-Forwarded-Host \$$http_host;` -> `proxy_set_header X-Forwarded-Host \$http_host;`
`proxy_set_header X-Forwarded-Host $$http_host;` -> `proxy_set_header X-Forwarded-Host $http_host;`

These seem to be correct in both cases. Are you using the latest version of Rancher Compose?

**Comment by sshipway** [comment] 2016-03-09 01:13
This was back on 13Jan; I havent tried it again recently so things may be different now?

**Comment by joshwget** [comment] 2016-03-09 01:18
I think it's likely that this issue isn't present anymore. I'll close this for now. If you are still encountering the problem, feel free to reopen.

**Comment by sshipway** [comment] 2016-03-09 01:19
Running a more comprehensive test against 0.59.1 now

**Comment by sshipway** [comment] 2016-03-09 01:26
The problem still exists (rancher-compose 0.7.2)

With this in the template:
````
  environment:
    NGINX_CONFIG: >
      server {\n
        listen 443 ssl;\n
        ssl_certificate     certs/registry.crt;\n
        ssl_certificate_key certs/registry.key;\n
        location / {\n
          proxy_set_header X-Forwarded-Host-A \$http_host;\n
          proxy_set_header X-Forwarded-Host-B $$http_host;\n
          proxy_set_header X-Forwarded-Host-C $http_host;\n
        }\n
      }\n
````

I end up with a docker-compose that looks like this:
````
ssl-proxy:
  environment:
    NGINX_CERT_FILE: /etc/nginx/certs/registry.crt
    NGINX_CONFIG: |
      server {\n
        listen 443 ssl;\n
        ssl_certificate     certs/registry.crt;\n
        ssl_certificate_key certs/registry.key;\n
        location / {\n
          proxy_set_header X-Forwarded-Host-A \;\n
          proxy_set_header X-Forwarded-Host-B $$http_host;\n
          proxy_set_header X-Forwarded-Host-C ;\n
        }\n
      }\n
````

Note how there is no way to end up with `proxy_set_header X-Forwarded-Host $http_host` since a single `$` is removed, but a double `$$` is left unchanged and an escaped `\` is not honoured.

**Comment by deniseschannon** [comment] 2016-03-09 05:21
Spoke with @joshwget. The containers are started correctly with the correct env variables, but in the UI, the exported docker-compose.yml is not displaying it correctly.

**Comment by prachidamle** [comment] 2016-03-12 02:28
This seems to be more of an issue with rancher-compose tool. I tested the following docker-compose.yml with rancher-compose tool and this is what it prints out:

< docker-compose.yml:

ssl-proxy:
  2   image: sshipway/nginx:${nginx_version}
  3   tty: true
  4   stdin_open: true
  5   environment:
  6     NGINX_CONFIG: proxy_set_header X-Forwarded-Host $$http_host;
>

< 
$ ./rancher-compose --file "docker-compose.yml" --verbose -p testdollar3 create
DEBU[0000] Environment Context from file : map[]        
DEBU[0000] Opening compose file: docker-compose.yml     
DEBU[0000] Looking for stack testdollar3                
INFO[0000] Creating stack testdollar3                   
WARN[0000] The http_host variable is not set. Substituting a blank string. 
DEBU[0000] Opening rancher-compose file: /Users/prachi/rancher/rancher-compose-v0.7.2/rancher-compose.yml 
DEBU[0000] Not found: /Users/prachi/rancher/rancher-compose-v0.7.2/rancher-compose.yml 
WARN[0000] The http_host variable is not set. Substituting a blank string. 
DEBU[0000] [0/1] [ssl-proxy]: Adding                    
DEBU[0000] Launching action for ssl-proxy               
DEBU[0000] Project [testdollar3]: Creating project      
DEBU[0000] Finding service ssl-proxy                    
DEBU[0000] [0/1] [ssl-proxy]: Creating                  
INFO[0000] Creating service ssl-proxy                   
DEBU[0000] Creating service ssl-proxy with hash: digest.ServiceHash{Service:"003e896183b518f9734a94d89cc8fad718cd61b1", LaunchConfig:"b88a824d38f7d3ad5acfdd3133d2efe918631e03", SecondaryLaunchConfigs:map[string]string(nil)} 
DEBU[0000] Finding service ssl-proxy                    
DEBU[0000] Found service ssl-proxy                      
DEBU[0000] [0/1] [ssl-proxy]: Created                   
DEBU[0000] Project [testdollar3]: Project created       
DEBU[0000] Project [testdollar3]: Creating project      
DEBU[0000] Launching action for ssl-proxy               
DEBU[0000] Finding service ssl-proxy                    
DEBU[0000] [0/1] [ssl-proxy]: Creating                  
DEBU[0000] Found service ssl-proxy                      
DEBU[0000] [0/1] [ssl-proxy]: Created                   
>

**Comment by prachidamle** [comment] 2016-03-12 02:32
Also in top of rancher-compose fix, cattle will probably need a small fix to keep the $ to be not replaced by $$. But that should be a small fix on top of compose fix.

**Comment by prachidamle** [comment] 2016-03-12 02:33
@deniseschannon please assign this to rancher-compose owners.

**Comment by prachidamle** [comment] 2016-03-12 02:46
This is ths data cattle gets from rancher-compose. Note the missing $http_host

{"fields":{"scale":1,"launchConfig":{"environment":{**"NGINX_CONFIG":"proxy_set_header X-Forwarded-Host ;"**},"imageUuid":"docker:sshipway/nginx:1.9.9","labels":{"io.rancher.service.hash":"b88a824d38f7d3ad5acfdd3133d2efe918631e03"},"logConfig":{},"networkMode":"managed","startOnCreate":true,"stdinOpen":true,"tty":true,"kind":"container","privileged":false,"publishAllPorts":false,"readOnly":false,"version":"0","vcpu":1},"assignServiceIpAddress":false,"metadata":{"io.rancher.service.hash":"003e896183b518f9734a94d89cc8fad718cd61b1"},"secondaryLaunchConfigs":[],"token":"AfPmytdURztsxY5ahM7xGZhGfW8NprjqatRMbmgy"}}

**Comment by deniseschannon** [comment] 2016-03-12 03:03
@joshwget Can you take a look?

**Comment by joshwget** [comment] 2016-03-12 04:21
@prachidamle Substituting a blank value for missing variables is actually the expected behavior. `$` being replaced by `$$` in Cattle might actually be correct behavior as well. When `$$` occurs in a Compose file, it is replaced with a `$` by Rancher Compsoe. Since Cattle is trying to rebuild what the original configuration looked like, doing the reverse is probably correct.

I agree that it's essentially impossible for Cattle to rebuild a service configuration since variable interpolation is a one way operation. We'll have to think a bit about how Rancher Compose and Cattle can coordinate to keep track of variable interpolations.

**Comment by prachidamle** [comment] 2016-03-12 07:19
Yeah I agree  @joshwget, actually the current design in cattle to replace a $ by $$ is actually intended to keep the compose files intact. This bug and PR explains that:
https://github.com/rancher/cattle/pull/956
https://github.com/rancher/rancher/issues/2351

So I think for now, its not possible to input a $$ in compose file and expect it to turn into a single $ while exporting the config. That replacement if needed will have to be done manually.

**Comment by will-chan** [comment] 2016-03-13 17:59
This may be as designed, but it does not solve the original problem of getting $whatever to show up as-is?  Can we use one of @sshipway proposals?

**Comment by joshwget** [comment] 2016-03-14 17:12
I think @prachidamle is correct that escaping a `$` character is working correctly. Getting `$whatever` to show up in the exported config is tricky because it's replaced with the environment variable value in Rancher Compose before Cattle ever sees the service.

**Comment by deniseschannon** [comment] 2016-03-14 18:15
@sshipway After speaking with the team, this is by design. The exported configuration in Rancher is designed for users to be able to copy and paste the file and use it again in rancher-compose.

If you want to escape the environment interpolation and be able to use `$foo`, it will always be displayed as `$$foo` in the exported config so that you can use the same file in rancher-compose and always be evaluated as `$foo`.

Rancher-compose automatically replaces the `$var` and places the value of the `$var` into the compose.yml file. If no value is found, it will be replaced with a blank space. This is the behavior of libcompose.

**Closed by deniseschannon** 2016-03-14 18:15 UTC
Labels: area/rancher-compose, kind/bug, status/wontfix
