### ISSUE TITLE
Handle a comma separated list with a space in the scheduler while using rancher-compose

### ISSUE THREAD

**Issue by gcallsen** [rancher/rancher#3213] opened 2016-01-08 19:53 UTC
Currently having an issue deploying a service with a scheduling rule that includes more than one host_label key=value pair. i.e.:

    labels:
        io.rancher.scheduler.affinity:host_label: key1=true, key2=true

When deploying with *either* key1=true or key2=true the scheduling works correctly. When we have both rules it fails. 

Tried this when running v0.50.2, just upgraded and tested again with v0.51.0. I recall being able to do this in the past and I believe documentation (http://docs.rancher.com/rancher/rancher-compose/scheduling/) suggests that should work correctly. Am I missing something on this?

Many thanks.

**Comment by deniseschannon** [comment] 2016-01-08 19:59
Currently, for scheduling rules, you can only set one key value pair as the value of the scheduling rule. 

If you want it to match 2 host labels, you'd need to do something like this:

```
labels:
    io.rancher.scheduler.affinity:host_label: key1=true
    io.rancher.scheduler.affinity:host_label: key2=true
```
This is actually a duplicate of https://github.com/rancher/rancher/issues/2601

**Comment by gcallsen** [comment] 2016-01-08 20:02
OK Confirmed, thank you.  Currently the documentation makes it appear as though the comma separated list is correct syntax --> http://docs.rancher.com/rancher/rancher-compose/scheduling/

Many thanks for the quick reply.

**Comment by deniseschannon** [comment] 2016-01-08 21:18
@gcallsen Okay, I was mistaken. You should be able to use a comma separated list for labels. 

I was thinking of the `key in (value1, value2)`.

I just tested this on v0.51.0 and was able to do the comma separated list. 

What are the issues that you have with deploying?

**Comment by gcallsen** [comment] 2016-01-08 22:04
Scenario is: 3 machines, each has 2 labels: `cassandra-server={true || false}` and `cassandra-seed={true || false}`.  All three machines are cassandra servers (so all =true) and two of them are seeds (so two machines =true, the other =false).

In our docker-compose we have:

    labels:
        io.rancher.scheduler.affinity:host_label: cassandra-server=true, cassandra-seed=true

When we try to start the service for the first time (`rancher-compose -p cassandra-staging up -d cassandra-staging-us-west-1-seeds`) it just hangs.  If we use either one of the labels independently, it starts as expected to a machine matching the rule.

In the UI Admin->Processes we see that service.activate exits for TIMEOUT. In the rancher server logs we see 

    2016-01-08 19:44:14,547 ERROR [52119025-e784-4c16-8a27-c8c8e34802f0:382556] [instance:16815] [instance.start->(InstanceStart)] [] [cutorService-17] [i.c.p.process.instance.InstanceStart] Failed to Scheduling for instance [16815]

Not sure what we could be doing wrong with it, we tried multiple times with different variations (including labels with no hyphens just in case) and we saw the same behavior.

**Comment by deniseschannon** [comment] 2016-01-11 18:51
I found the issue, there shouldn't be a space between the comma and the labels. Please try again with no space.

The example in the docs has been corrected, but I think Rancher should be able to handle a comma separated list with spaces.

**Comment by gcallsen** [comment] 2016-01-11 21:27
Confirmed that it works without spaces - thank you for following up on this!

**Comment by will-chan** [comment] 2016-03-08 02:15
closed based on comments

**Closed by will-chan** 2016-03-08 02:15 UTC
Labels: area/scheduler, kind/bug
