### ISSUE TITLE
Agent randomly fails to join when adding a node

### ISSUE THREAD

**Issue by withinboredom** [rancher/rancher#3533] opened 2016-02-05 04:49 UTC
```
INFO: Starting agent for ***
INFO: Access Key: ***
INFO: Config URL: http://***:8080/v1
INFO: Storage URL: http://***:8080/v1
INFO: API URL: http://***:8080/v1
INFO: IP: ***
INFO: Port:
INFO: Required Image: rancher/agent:v0.8.2
INFO: Current Image: rancher/agent:v0.8.2
INFO: Using image rancher/agent:v0.8.2
INFO: Downloading agent http://***:8080/v1/configcontent/configscripts
{"id":"***","type":"error","links":{},"actions":{},"status":401,"code":"Unauthorized","message":"Unauthorized","detail":null}
gzip: stdin: not in gzip format
tar: Child returned status 1
tar: Error is not recoverable: exiting now
```
I deleted the agent and reran the exact same command and everything was fine...

**Comment by deniseschannon** [comment] 2016-02-09 20:40
Duplicate of https://github.com/rancher/rancher/issues/1370

**Comment by deniseschannon** [comment] 2016-02-09 20:40
Please add more details in the other issue.

**Closed by deniseschannon** 2016-02-09 20:40 UTC
