### ISSUE TITLE
Active Directory authentication provider setup gets stuck if service account password field is not filled in

### ISSUE THREAD

**Issue by Overv** [rancher/rancher#12728] opened 2018-04-16 11:58 UTC
**Rancher versions:**
rancher/server: v2.0.0-beta1
rancher/agent: N/A

**Docker version: (`docker version`,`docker info` preferred)** 17.12.0-ce

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)** Ubuntu 16.04.3 LTS

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)** Bare-metal

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)** Single node rancher with internal DB

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)** N/A

**Steps to Reproduce:**

1. Set up Active Directory by filling in all the details on the authentication provider page, but leave out the password for the service account.
2. Click `Authenticate` at the bottom.

**Results:**

The page will get stuck and not issue any requests because the service account password required field is not filled in. However, no error is shown to notify the user of this and they need to reload the page.

**Comment by superseb** [comment] 2018-04-16 12:06
Reproduces on master 04/16

**Comment by deniseschannon** [comment] 2018-04-16 19:31
Duplicate of https://github.com/rancher/rancher/issues/12538

**Closed by deniseschannon** 2018-04-16 19:31 UTC
Labels: area/ui, kind/bug, version/2.0
