### ISSUE TITLE
socket: too many open files in system

### ISSUE THREAD

**Issue by martcastaldo** [rancher/rancher#14987] opened 2018-08-07 13:23 UTC
**Rancher versions:**
rancher/rancher: 2.0.6
rancher/rancher-agent: not sure

**Infrastructure Stack versions:**
kubernetes (if applicable): v1.10.5

Docker version: 17.3.2
Operating system and kernel: Ubuntu 16.04.2 LTS
Type/provider of hosts: AWS

Setup details: 1 Master and 2 Minions
Environment Template: Kubernetes

Steps to Reproduce:

Currently not able to access our cluster as we are getting:

Failed to communicate with API server: Get https://<IP Address>:6443/api/v1/componentstatuses: dial tcp <IP Address>:6443: socket: too many open files in system.

This K8s cluster was created using the Rancher AWS provider so everything including keys is managed by Rancher.

I have tried logging onto the master and minions but the key that I'm provided by Rancher does not work in SSH and I have tried everything to get it working. We have been using this cluster with no issues for the past 3 weeks and then today we get the above error when trying to do anything on a cluster, both the master and minions seem to be unavailable with the minions reporting:

Kubelet stopped posting node status.

Could really do with getting this resolved as I really dont want to start over again after three weeks of using this K8s cluster.

**Comment by superseb** [comment] 2018-08-07 14:14
Can you supply the info requested in the issue template (that is stripped out)? What AMI are you using for the host running `rancher/rancher` and what AMI for the nodes added to the cluster?

The way to access to the node is described here: https://rancher.com/docs/rancher/v2.x/en/faq/technical/#how-can-i-access-nodes-created-by-rancher

**Comment by martcastaldo** [comment] 2018-08-07 14:37
I thought that I did?

rancher/rancher is being ran on:

ubuntu/images/hvm-ssd/ubuntu-xenial-16.04-amd64-server-20180627

This is the only OS that I'm using on all rancher instances and k8s nodes.

I have tried that way to access all the nodes and it doesnt work how many times I try it, as I specified in the opening post. As stated:

"I have tried logging onto the master and minions but the key that I'm provided by Rancher does not work in SSH and I have tried everything to get it working."

It isnt working as the information states in my opening post.

**Comment by superseb** [comment] 2018-08-07 14:41
What `ssh` command are you using to login to the nodes, please provide the exact command you are using when trying to login.

**Comment by martcastaldo** [comment] 2018-08-07 14:45
@superseb Do you want me to raise another separate issue about the keys not working?

**Comment by martcastaldo** [comment] 2018-08-07 14:46
`ssh -vvvv -i /cygdrive/d/K8s/minion-1/id_rsa ubuntu@10.0.24.82`

**Comment by superseb** [comment] 2018-08-08 14:12
This was tracked down to unresponsive hosts due to max open files. Not being able to SSH was also because of this. After rebooting the nodes, it started working again. We are trying to see if the issue can be reproduced and if we can do anything about it.

**Comment by Nir-Tal** [comment] 2018-09-07 20:10
that happens to us as well. Rancher 2.0.8 / Ubuntu 16.04 / Provider is profitbricks. expanding the fd to 100000 reduced the frequency of the nodes going dead but did not solve it. I'm restarting the docker service manually every time a node is stopping to respond. I think that Rancher should at least kill the node and create a new one if it happens otherwise the entire cluster is breaking and when using Longhorn it's practically impossible to recover the volumes without manual work.

**Comment by Dijir** [comment] 2018-10-21 17:51
We're having this issue too. We are using elasticsearch and they become unresponsive.

**Comment by Jonbj** [comment] 2018-10-29 11:43
Same issue. I have message "Failed to communicate with API server" on UI.
If I try to access to etcd server with ssh I have Too many open files in system.
This happen after installaELK stack and activate logging

**Comment by leodotcloud** [comment] 2018-11-20 08:37
I was running docker 1.12.6 and ran into a similar problem.

Got the stacktrace by running `kill -SIGUSR1 <pid of dockerd>` command.

```
goroutine 37072 [semacquire, 3539 minutes]:
sync.runtime_Semacquire(0xc820cffb24)
  /usr/local/go/src/runtime/sema.go:47 +0x26
sync.(*Mutex).Lock(0xc820cffb20)
  /usr/local/go/src/sync/mutex.go:83 +0x1c4
github.com/docker/docker/daemon.(*Daemon).reducePsContainer(0xc8204261a0, 0xc8215b10e0, 0xc8224793e0, 0xc8248d73d0, 0x0, 0x0, 0x0)
  /usr/src/docker/.gopath/src/github.com/docker/docker/daemon/list.go:204 +0x49
github.com/docker/docker/daemon.(*Daemon).reduceContainers(0xc8204261a0, 0xc8236ca140, 0xc8248d73d0, 0x0, 0x0, 0x0, 0x0, 0x0)
  /usr/src/docker/.gopath/src/github.com/docker/docker/daemon/list.go:187 +0x1a5
github.com/docker/docker/daemon.(*Daemon).Containers(0xc8204261a0, 0xc8236ca140, 0x0, 0x0, 0x0, 0x0, 0x0)
  /usr/src/docker/.gopath/src/github.com/docker/docker/daemon/list.go:101 +0x76
github.com/docker/docker/api/server/router/container.(*containerRouter).getContainersJSON(0xc82021a2c0, 0x7f5ea60708b0, 0xc823bdac00, 0x7f5ea6050ab0, 0xc8243cb5f0, 0xc82490c1c0, 0xc823bda3f0, 0x0, 0x0)
  /usr/src/docker/.gopath/src/github.com/docker/docker/api/server/router/container/container_routes.go:51 +0x3ce
github.com/docker/docker/api/server/router/container.(*containerRouter).(github.com/docker/docker/api/server/router/container.getContainersJSON)-fm(0x7f5ea60708b0, 0xc823bdac00, 0x7f5ea6050ab0, 0xc8243cb5f0, 0xc82490c1c0, 0xc823bda3f0, 0x0, 0x0)
  /usr/src/docker/.gopath/src/github.com/docker/docker/api/server/router/container/container.go:44 +0x74
github.com/docker/docker/api/server/middleware.VersionMiddleware.WrapHandler.func1(0x7f5ea60708b0, 0xc823bdac00, 0x7f5ea6050ab0, 0xc8243cb5f0, 0xc82490c1c0, 0xc823bda3f0, 0x0, 0x0)
  /usr/src/docker/.gopath/src/github.com/docker/docker/api/server/middleware/version.go:56 +0x9aa
github.com/docker/docker/api/server/middleware.UserAgentMiddleware.WrapHandler.func1(0x7f5ea60708b0, 0xc823bdabd0, 0x7f5ea6050ab0, 0xc8243cb5f0, 0xc82490c1c0, 0xc823bda3f0, 0x0, 0x0)
  /usr/src/docker/.gopath/src/github.com/docker/docker/api/server/middleware/user_agent.go:45 +0x68e
github.com/docker/docker/api/server.(*Server).makeHTTPHandler.func1(0x7f5ea6050ab0, 0xc8243cb5f0, 0xc82490c1c0)
  /usr/src/docker/.gopath/src/github.com/docker/docker/api/server/server.go:139 +0x138
net/http.HandlerFunc.ServeHTTP(0xc820325760, 0x7f5ea6050ab0, 0xc8243cb5f0, 0xc82490c1c0)
  /usr/local/go/src/net/http/server.go:1618 +0x3a
github.com/gorilla/mux.(*Router).ServeHTTP(0xc82023d040, 0x7f5ea6050ab0, 0xc8243cb5f0, 0xc82490c1c0)
  /usr/src/docker/vendor/src/github.com/gorilla/mux/mux.go:98 +0x29e
github.com/docker/docker/api/server.(*routerSwapper).ServeHTTP(0xc8206de9c0, 0x7f5ea6050ab0, 0xc8243cb5f0, 0xc82490c1c0)
  /usr/src/docker/.gopath/src/github.com/docker/docker/api/server/router_swapper.go:29 +0x72
net/http.serverHandler.ServeHTTP(0xc8203cc080, 0x7f5ea6050ab0, 0xc8243cb5f0, 0xc82490c1c0)
  /usr/local/go/src/net/http/server.go:2081 +0x19e
net/http.(*conn).serve(0xc82112a480)
  /usr/local/go/src/net/http/server.go:1472 +0xf2e
created by net/http.(*Server).Serve
  /usr/local/go/src/net/http/server.go:2137 +0x44e

goroutine 37073 [semacquire, 3537 minutes]:
sync.runtime_Semacquire(0xc820cffb24)
  /usr/local/go/src/runtime/sema.go:47 +0x26
sync.(*Mutex).Lock(0xc820cffb20)
  /usr/local/go/src/sync/mutex.go:83 +0x1c4
github.com/docker/docker/daemon.(*Daemon).reducePsContainer(0xc8204261a0, 0xc8215b10e0, 0xc82160b140, 0xc8248d33d0, 0x0, 0x0, 0x0)
  /usr/src/docker/.gopath/src/github.com/docker/docker/daemon/list.go:204 +0x49
github.com/docker/docker/daemon.(*Daemon).reduceContainers(0xc8204261a0, 0xc823a11d80, 0xc8248d33d0, 0x0, 0x0, 0x0, 0x0, 0x0)
  /usr/src/docker/.gopath/src/github.com/docker/docker/daemon/list.go:187 +0x1a5
github.com/docker/docker/daemon.(*Daemon).Containers(0xc8204261a0, 0xc823a11d80, 0x0, 0x0, 0x0, 0x0, 0x0)
  /usr/src/docker/.gopath/src/github.com/docker/docker/daemon/list.go:101 +0x76
github.com/docker/docker/api/server/router/container.(*containerRouter).getContainersJSON(0xc82021a2c0, 0x7f5ea60708b0, 0xc82492a0c0, 0x7f5ea6050ab0, 0xc8248ec000, 0xc82490c9a0, 0xc82492a030, 0x0, 0x0)
  /usr/src/docker/.gopath/src/github.com/docker/docker/api/server/router/container/container_routes.go:51 +0x3ce
github.com/docker/docker/api/server/router/container.(*containerRouter).(github.com/docker/docker/api/server/router/container.getContainersJSON)-fm(0x7f5ea60708b0, 0xc82492a0c0, 0x7f5ea6050ab0, 0xc8248ec000, 0xc82490c9a0, 0xc82492a030, 0x0, 0x0)
  /usr/src/docker/.gopath/src/github.com/docker/docker/api/server/router/container/container.go:44 +0x74
github.com/docker/docker/api/server/middleware.VersionMiddleware.WrapHandler.func1(0x7f5ea60708b0, 0xc82492a0c0, 0x7f5ea6050ab0, 0xc8248ec000, 0xc82490c9a0, 0xc82492a030, 0x0, 0x0)
  /usr/src/docker/.gopath/src/github.com/docker/docker/api/server/middleware/version.go:56 +0x9aa
github.com/docker/docker/api/server/middleware.UserAgentMiddleware.WrapHandler.func1(0x7f5ea60708b0, 0xc82492a090, 0x7f5ea6050ab0, 0xc8248ec000, 0xc82490c9a0, 0xc82492a030, 0x0, 0x0)
  /usr/src/docker/.gopath/src/github.com/docker/docker/api/server/middleware/user_agent.go:45 +0x68e
github.com/docker/docker/api/server.(*Server).makeHTTPHandler.func1(0x7f5ea6050ab0, 0xc8248ec000, 0xc82490c9a0)
  /usr/src/docker/.gopath/src/github.com/docker/docker/api/server/server.go:139 +0x138
net/http.HandlerFunc.ServeHTTP(0xc820325760, 0x7f5ea6050ab0, 0xc8248ec000, 0xc82490c9a0)
  /usr/local/go/src/net/http/server.go:1618 +0x3a
github.com/gorilla/mux.(*Router).ServeHTTP(0xc82023d040, 0x7f5ea6050ab0, 0xc8248ec000, 0xc82490c9a0)
  /usr/src/doc
```

Possibly hitting this upstream docker bug: https://github.com/moby/moby/issues/28889

More setup info:

```
kubectl get nodes -o wide
NAME             STATUS     ROLES                      AGE       VERSION   EXTERNAL-IP   OS-IMAGE             KERNEL-VERSION   CONTAINER-RUNTIME
10.15.10.173   Ready      controlplane,etcd,worker   48d       v1.10.1   <none>        Ubuntu 16.04.5 LTS   4.4.0-1067-aws   docker://1.12.6
10.15.10.244   Ready      controlplane,etcd,worker   48d       v1.10.1   <none>        Ubuntu 16.04.5 LTS   4.4.0-1067-aws   docker://1.12.6
10.15.10.75    NotReady   controlplane,etcd,worker   48d       v1.10.1   <none>        Ubuntu 16.04.5 LTS   4.4.0-1067-aws   docker://1.12.6

kubectl get pods --all-namespaces
NAMESPACE        NAME                                      READY     STATUS              RESTARTS   AGE
cattle-logging   fluentd-czn26                             2/2       NodeLost            0          12d
cattle-logging   fluentd-rc7kg                             2/2       Running             2          12d
cattle-logging   fluentd-xnq9n                             2/2       Running             2          12d
cattle-logging   log-aggregator-7m8kk                      1/1       Running             1          4d
cattle-logging   log-aggregator-c6lgx                      1/1       NodeLost            0          4d
cattle-logging   log-aggregator-vp5s5                      1/1       Running             1          4d
cattle-system    cattle-cluster-agent-55867876d-nthn5      1/1       Running             4          34d
cattle-system    cattle-node-agent-4jdnk                   1/1       Running             7          34d
cattle-system    cattle-node-agent-dgwpr                   1/1       NodeLost            0          34d
cattle-system    cattle-node-agent-s27gc                   1/1       Running             7          34d
cattle-system    rancher-68c4648996-hzn9c                  1/1       Running             0          4d
cattle-system    rancher-68c4648996-qqrm7                  0/1       Unknown             7          34d
default          dhelmick-6956d5c97-zlhkg                  1/1       Running             1          11d
default          diag-79dbcd76d6-4lwjl                     1/1       Running             1          20d
ingress-nginx    default-http-backend-564b9b6c5b-6gssp     1/1       Running             1          48d
ingress-nginx    nginx-ingress-controller-78ffh            1/1       Running             6          48d
ingress-nginx    nginx-ingress-controller-92vs9            0/1       CrashLoopBackOff    9          48d
ingress-nginx    nginx-ingress-controller-b8v6r            1/1       Running             1          48d
kube-system      canal-b6d8b                               3/3       Running             10         4d
kube-system      canal-xthks                               0/3       NodeLost            0          4d
kube-system      canal-zwqc7                               3/3       Running             0          4d
kube-system      kube-dns-5ccb66df65-b5p2s                 3/3       Running             384        4d
kube-system      kube-dns-5ccb66df65-vnzmn                 1/3       Unknown             20         48d
kube-system      kube-dns-autoscaler-6c4b786f5-md47f       1/1       Running             1          48d
kube-system      rke-ingress-controller-deploy-job-n42jk   0/1       Completed           0          48d
kube-system      rke-kubedns-addon-deploy-job-dbc2v        0/1       Completed           0          48d
kube-system      rke-network-plugin-deploy-job-b2nnl       0/1       Completed           0          48d
kube-system      tiller-deploy-778f674bf5-pvqsw            1/1       Running             1          48d
```

Things to investigate: Does enabling Logging (was forwarding logs to elastic search) on the "local" cluster increase the probability of this issue?

**Comment by leodotcloud** [comment] 2018-11-20 08:39
I was running docker 1.12.6 and ran into a similar problem.

Got the stacktrace by running `kill -SIGUSR1 <pid of dockerd>` command.

```
goroutine 37072 [semacquire, 3539 minutes]:
sync.runtime_Semacquire(0xc820cffb24)
  /usr/local/go/src/runtime/sema.go:47 +0x26
sync.(*Mutex).Lock(0xc820cffb20)
  /usr/local/go/src/sync/mutex.go:83 +0x1c4
github.com/docker/docker/daemon.(*Daemon).reducePsContainer(0xc8204261a0, 0xc8215b10e0, 0xc8224793e0, 0xc8248d73d0, 0x0, 0x0, 0x0)
  /usr/src/docker/.gopath/src/github.com/docker/docker/daemon/list.go:204 +0x49
github.com/docker/docker/daemon.(*Daemon).reduceContainers(0xc8204261a0, 0xc8236ca140, 0xc8248d73d0, 0x0, 0x0, 0x0, 0x0, 0x0)
  /usr/src/docker/.gopath/src/github.com/docker/docker/daemon/list.go:187 +0x1a5
github.com/docker/docker/daemon.(*Daemon).Containers(0xc8204261a0, 0xc8236ca140, 0x0, 0x0, 0x0, 0x0, 0x0)
  /usr/src/docker/.gopath/src/github.com/docker/docker/daemon/list.go:101 +0x76
github.com/docker/docker/api/server/router/container.(*containerRouter).getContainersJSON(0xc82021a2c0, 0x7f5ea60708b0, 0xc823bdac00, 0x7f5ea6050ab0, 0xc8243cb5f0, 0xc82490c1c0, 0xc823bda3f0, 0x0, 0x0)
  /usr/src/docker/.gopath/src/github.com/docker/docker/api/server/router/container/container_routes.go:51 +0x3ce
github.com/docker/docker/api/server/router/container.(*containerRouter).(github.com/docker/docker/api/server/router/container.getContainersJSON)-fm(0x7f5ea60708b0, 0xc823bdac00, 0x7f5ea6050ab0, 0xc8243cb5f0, 0xc82490c1c0, 0xc823bda3f0, 0x0, 0x0)
  /usr/src/docker/.gopath/src/github.com/docker/docker/api/server/router/container/container.go:44 +0x74
github.com/docker/docker/api/server/middleware.VersionMiddleware.WrapHandler.func1(0x7f5ea60708b0, 0xc823bdac00, 0x7f5ea6050ab0, 0xc8243cb5f0, 0xc82490c1c0, 0xc823bda3f0, 0x0, 0x0)
  /usr/src/docker/.gopath/src/github.com/docker/docker/api/server/middleware/version.go:56 +0x9aa
github.com/docker/docker/api/server/middleware.UserAgentMiddleware.WrapHandler.func1(0x7f5ea60708b0, 0xc823bdabd0, 0x7f5ea6050ab0, 0xc8243cb5f0, 0xc82490c1c0, 0xc823bda3f0, 0x0, 0x0)
  /usr/src/docker/.gopath/src/github.com/docker/docker/api/server/middleware/user_agent.go:45 +0x68e
github.com/docker/docker/api/server.(*Server).makeHTTPHandler.func1(0x7f5ea6050ab0, 0xc8243cb5f0, 0xc82490c1c0)
  /usr/src/docker/.gopath/src/github.com/docker/docker/api/server/server.go:139 +0x138
net/http.HandlerFunc.ServeHTTP(0xc820325760, 0x7f5ea6050ab0, 0xc8243cb5f0, 0xc82490c1c0)
  /usr/local/go/src/net/http/server.go:1618 +0x3a
github.com/gorilla/mux.(*Router).ServeHTTP(0xc82023d040, 0x7f5ea6050ab0, 0xc8243cb5f0, 0xc82490c1c0)
  /usr/src/docker/vendor/src/github.com/gorilla/mux/mux.go:98 +0x29e
github.com/docker/docker/api/server.(*routerSwapper).ServeHTTP(0xc8206de9c0, 0x7f5ea6050ab0, 0xc8243cb5f0, 0xc82490c1c0)
  /usr/src/docker/.gopath/src/github.com/docker/docker/api/server/router_swapper.go:29 +0x72
net/http.serverHandler.ServeHTTP(0xc8203cc080, 0x7f5ea6050ab0, 0xc8243cb5f0, 0xc82490c1c0)
  /usr/local/go/src/net/http/server.go:2081 +0x19e
net/http.(*conn).serve(0xc82112a480)
  /usr/local/go/src/net/http/server.go:1472 +0xf2e
created by net/http.(*Server).Serve
  /usr/local/go/src/net/http/server.go:2137 +0x44e

goroutine 37073 [semacquire, 3537 minutes]:
sync.runtime_Semacquire(0xc820cffb24)
  /usr/local/go/src/runtime/sema.go:47 +0x26
sync.(*Mutex).Lock(0xc820cffb20)
  /usr/local/go/src/sync/mutex.go:83 +0x1c4
github.com/docker/docker/daemon.(*Daemon).reducePsContainer(0xc8204261a0, 0xc8215b10e0, 0xc82160b140, 0xc8248d33d0, 0x0, 0x0, 0x0)
  /usr/src/docker/.gopath/src/github.com/docker/docker/daemon/list.go:204 +0x49
github.com/docker/docker/daemon.(*Daemon).reduceContainers(0xc8204261a0, 0xc823a11d80, 0xc8248d33d0, 0x0, 0x0, 0x0, 0x0, 0x0)
  /usr/src/docker/.gopath/src/github.com/docker/docker/daemon/list.go:187 +0x1a5
github.com/docker/docker/daemon.(*Daemon).Containers(0xc8204261a0, 0xc823a11d80, 0x0, 0x0, 0x0, 0x0, 0x0)
  /usr/src/docker/.gopath/src/github.com/docker/docker/daemon/list.go:101 +0x76
github.com/docker/docker/api/server/router/container.(*containerRouter).getContainersJSON(0xc82021a2c0, 0x7f5ea60708b0, 0xc82492a0c0, 0x7f5ea6050ab0, 0xc8248ec000, 0xc82490c9a0, 0xc82492a030, 0x0, 0x0)
  /usr/src/docker/.gopath/src/github.com/docker/docker/api/server/router/container/container_routes.go:51 +0x3ce
github.com/docker/docker/api/server/router/container.(*containerRouter).(github.com/docker/docker/api/server/router/container.getContainersJSON)-fm(0x7f5ea60708b0, 0xc82492a0c0, 0x7f5ea6050ab0, 0xc8248ec000, 0xc82490c9a0, 0xc82492a030, 0x0, 0x0)
  /usr/src/docker/.gopath/src/github.com/docker/docker/api/server/router/container/container.go:44 +0x74
github.com/docker/docker/api/server/middleware.VersionMiddleware.WrapHandler.func1(0x7f5ea60708b0, 0xc82492a0c0, 0x7f5ea6050ab0, 0xc8248ec000, 0xc82490c9a0, 0xc82492a030, 0x0, 0x0)
  /usr/src/docker/.gopath/src/github.com/docker/docker/api/server/middleware/version.go:56 +0x9aa
github.com/docker/docker/api/server/middleware.UserAgentMiddleware.WrapHandler.func1(0x7f5ea60708b0, 0xc82492a090, 0x7f5ea6050ab0, 0xc8248ec000, 0xc82490c9a0, 0xc82492a030, 0x0, 0x0)
  /usr/src/docker/.gopath/src/github.com/docker/docker/api/server/middleware/user_agent.go:45 +0x68e
github.com/docker/docker/api/server.(*Server).makeHTTPHandler.func1(0x7f5ea6050ab0, 0xc8248ec000, 0xc82490c9a0)
  /usr/src/docker/.gopath/src/github.com/docker/docker/api/server/server.go:139 +0x138
net/http.HandlerFunc.ServeHTTP(0xc820325760, 0x7f5ea6050ab0, 0xc8248ec000, 0xc82490c9a0)
  /usr/local/go/src/net/http/server.go:1618 +0x3a
github.com/gorilla/mux.(*Router).ServeHTTP(0xc82023d040, 0x7f5ea6050ab0, 0xc8248ec000, 0xc82490c9a0)
  /usr/src/doc
```

Possibly hitting this upstream docker bug: https://github.com/moby/moby/issues/28889

More setup info:

```
kubectl get nodes -o wide
NAME             STATUS     ROLES                      AGE       VERSION   EXTERNAL-IP   OS-IMAGE             KERNEL-VERSION   CONTAINER-RUNTIME
10.15.10.173   Ready      controlplane,etcd,worker   48d       v1.10.1   <none>        Ubuntu 16.04.5 LTS   4.4.0-1067-aws   docker://1.12.6
10.15.10.244   Ready      controlplane,etcd,worker   48d       v1.10.1   <none>        Ubuntu 16.04.5 LTS   4.4.0-1067-aws   docker://1.12.6
10.15.10.75    NotReady   controlplane,etcd,worker   48d       v1.10.1   <none>        Ubuntu 16.04.5 LTS   4.4.0-1067-aws   docker://1.12.6

kubectl get pods --all-namespaces
NAMESPACE        NAME                                      READY     STATUS              RESTARTS   AGE
cattle-logging   fluentd-czn26                             2/2       NodeLost            0          12d
cattle-logging   fluentd-rc7kg                             2/2       Running             2          12d
cattle-logging   fluentd-xnq9n                             2/2       Running             2          12d
cattle-logging   log-aggregator-7m8kk                      1/1       Running             1          4d
cattle-logging   log-aggregator-c6lgx                      1/1       NodeLost            0          4d
cattle-logging   log-aggregator-vp5s5                      1/1       Running             1          4d
cattle-system    cattle-cluster-agent-55867876d-nthn5      1/1       Running             4          34d
cattle-system    cattle-node-agent-4jdnk                   1/1       Running             7          34d
cattle-system    cattle-node-agent-dgwpr                   1/1       NodeLost            0          34d
cattle-system    cattle-node-agent-s27gc                   1/1       Running             7          34d
cattle-system    rancher-68c4648996-hzn9c                  1/1       Running             0          4d
cattle-system    rancher-68c4648996-qqrm7                  0/1       Unknown             7          34d
default          diag-79dbcd76d6-4lwjl                     1/1       Running             1          20d
ingress-nginx    default-http-backend-564b9b6c5b-6gssp     1/1       Running             1          48d
ingress-nginx    nginx-ingress-controller-78ffh            1/1       Running             6          48d
ingress-nginx    nginx-ingress-controller-92vs9            0/1       CrashLoopBackOff    9          48d
ingress-nginx    nginx-ingress-controller-b8v6r            1/1       Running             1          48d
kube-system      canal-b6d8b                               3/3       Running             10         4d
kube-system      canal-xthks                               0/3       NodeLost            0          4d
kube-system      canal-zwqc7                               3/3       Running             0          4d
kube-system      kube-dns-5ccb66df65-b5p2s                 3/3       Running             384        4d
kube-system      kube-dns-5ccb66df65-vnzmn                 1/3       Unknown             20         48d
kube-system      kube-dns-autoscaler-6c4b786f5-md47f       1/1       Running             1          48d
kube-system      rke-ingress-controller-deploy-job-n42jk   0/1       Completed           0          48d
kube-system      rke-kubedns-addon-deploy-job-dbc2v        0/1       Completed           0          48d
kube-system      rke-network-plugin-deploy-job-b2nnl       0/1       Completed           0          48d
kube-system      tiller-deploy-778f674bf5-pvqsw            1/1       Running             1          48d
```

Things to investigate: Does enabling Logging (was forwarding logs to elastic search) on the "local" cluster increase the probability of this issue?

**Comment by cjellick** [comment] 2018-12-18 18:03
@martcastaldo how did you install docker on the host where this occurred? We found that installing via snap caused the rancher server container to have a very low max-files-open ulimit
Ca you run `ulimit -a` from inside the rancher server container and share the results?

**Comment by such** [comment] 2018-12-18 18:43
@cjellick I've had the same issue (and it appears only when logging is enabled btw) so I'm sharing my own results here:
```
core file size          (blocks, -c) 0
data seg size           (kbytes, -d) unlimited
scheduling priority             (-e) 0
file size               (blocks, -f) unlimited
pending signals                 (-i) 15738
max locked memory       (kbytes, -l) 64
max memory size         (kbytes, -m) unlimited
open files                      (-n) 1024
pipe size            (512 bytes, -p) 8
POSIX message queues     (bytes, -q) 819200
real-time priority              (-r) 0
stack size              (kbytes, -s) 8192
cpu time               (seconds, -t) unlimited
max user processes              (-u) 15738
virtual memory          (kbytes, -v) unlimited
file locks                      (-x) unlimited
```

**Comment by such** [comment] 2018-12-18 18:46
@cjellick I'm having the same issue (only when logging is enabled btw), so I'm sharing my results:
```
# ulimit -a
time(seconds)        unlimited
file(blocks)         unlimited
data(kbytes)         unlimited
stack(kbytes)        8192
coredump(blocks)     unlimited
memory(kbytes)       unlimited
locked memory(kbytes) 64
process              unlimited
nofiles              1048576
vmemory(kbytes)      unlimited
locks                unlimited
rtprio               0
```
`docker` was installed with `apt`.

**Comment by cjellick** [comment] 2018-12-18 18:49
@leodotcloud also sees this when logging is enabled

**Comment by cjellick** [comment] 2018-12-18 18:50
@loganhz can your team investigate if there is a resource leak in the logging logic?

**Comment by cjellick** [comment] 2019-01-14 12:42
@aiwantaozi @loganhz what does this need to move to-test?

**Comment by aiwantaozi** [comment] 2019-01-14 18:07
@cjellick this issue need upgrade fluentd image, we upgrade the fluentd image in system charts, it could be test after these three PR are merged.
https://github.com/rancher/types/pull/661
https://github.com/rancher/system-charts/pull/9
https://github.com/rancher/rancher/pull/17209

**Comment by kingsd041** [comment] 2019-02-02 02:08
Version: master 2.2 (2/1/19) 
Confirmed fix. After logging is enabled, it has been running for 30 hours on my environment. The upgrade fluentd image has resolved this issue.

**Closed by kingsd041** 2019-02-02 02:08 UTC
Labels: kind/bug, kind/performance, priority/0, status/resolved, status/to-test, team/cn, version/2.0

**Comment by CyberPoison** [comment] 2021-02-21 19:42
Failed to communicate with API server: Get https://:6443/api/v1/componentstatuses?timeout=30s: dial tcp 10.0.23.75:6443: socket: too many open files in system

Also getting this issue on rancher 2.4.x and other times i get network requests failed some times, 
I also have installed by Docker container rancher
