### ISSUE TITLE
[backport] 2.1 - Compatibility issues with cert-manager v0.11.0

### ISSUE THREAD

**Issue by drpebcak** [rancher/rancher#23691] opened 2019-10-25 21:38 UTC
backport for issue described in rancher/rancher#23424

**Comment by jiaqiluo** [comment] 2019-12-17 21:32
closed in favor of https://github.com/rancher/rancher/pull/24520

**Comment by jiaqiluo** [comment] 2019-12-17 23:35
Follow the new documentation to install Rancher in HA mode successfully:

- Rancher version: v2.1.14-rc1
- Rancher Chart version: 2.1.14-rc1
- Cert-manager version: v0.12.0
- RKE command-line tool: v0.1.20
- K8s version: v1.13.10

**Comment by sangeethah** [comment] 2019-12-18 15:33
@jiaqiluo `v2.1.14-rc1` had to be retagged since you had tested this issue. Could you please retest with the current RC.

**Comment by jiaqiluo** [comment] 2019-12-18 18:01
Retested v2.1.14-rc1

Follow the new documentation to install Rancher in HA mode successfully:

- Rancher version: v2.1.14-rc1
- Rancher Chart version: 2.1.14-rc1
- Cert-manager version: v0.12.0
- RKE command-line tool: v0.1.20
- K8s version: v1.13.10

Alos, provisioning an ec2 cluster and be able to 
- deploy workloads
- open kubectl via UI

**Comment by jiaqiluo** [comment] 2019-12-18 19:51
The issue is reopened, we need to find the proper upgrading path for upgrading cert-manager and Rancher together

**Comment by jiaqiluo** [comment] 2020-01-13 18:07
The upgrading instruction is logged in the original issue.
This issue can be closed.

**Closed by jiaqiluo** 2020-01-13 18:07 UTC
Labels: [zube]: Reopened
