### ISSUE TITLE
Validate upgrading from docker install to a HA rancher using the backup operator

### ISSUE THREAD

**Issue by sowmyav27** [rancher/rancher#32711] opened 2021-05-13 15:57 UTC
Validate upgrading from docker install to a HA rancher using the backup operator

**Comment by snasovich** [comment] 2021-08-10 01:53
Requires https://github.com/rancher/rancher/issues/32599

**Comment by StrongMonkey** [comment] 2021-08-17 00:29
Did the following testing:

1. Created a single-node docker install setup using docker run. (docker run -d --privileged --restart=unless-stopped -p 8443:443 rancher/rancher:v2.6-head). This is self-signed certs setup.
2. Provisioned a rke2 cluster as a downstream cluster. 
3. Configured backup to upload to S3. Perform backup.
4. Deleted single-node docker container. Created a new k3s cluster.
5. Install backup operator(v2.0.0-rc8), perform the restore.
6. Install rancher HA setup on k3s cluster. Everything came up fine(cattle-cluster-agent and fleet-agent). System agent issue will be fixed by https://github.com/rancher/backup-restore-operator/pull/146 and https://github.com/rancher/rancher/pull/34181

This is ready to be tested.

**Comment by anupama2501** [comment] 2021-08-20 19:58
Re-opening the ticket as the backup file is missing some annotation and the rancher installation fails with error:
` annotation validation error: missing key "meta.helm.sh/release-name": must be set to "rancher"; annotation validation error: missing key "meta.helm.sh/release-namespace": must be set to "cattle-system"`

Steps: 
1. Create a rancher server v2.6.0-rc4 via docker installation.
2. Create 2 downstream rke1 node driver clusters with 3 nodes with 1 role each.
3. Create a workload and a daemon set in each of the clusters.
4. Install backup in the local cluster and set the storage option to S3.
5. Perform a backup with the 2 clusters and verified the backup is saved in S3.
6. Create an rke1 cluster with 3 nodes.
7. Delete the docker container for the single install rancher.
8. Perform restore in the new cluster.
9. Install rancher server in the new rke cluster.
10. Rancher installation fails because of missing annotations.
error: 

```
helm install rancher rancher-latest/rancher --version 2.6.0-rc4 --namespace cattle-system --set hostname=anupama-26.qa.rancher.space
Error: rendered manifests contain a resource that already exists. Unable to continue with install: Secret "bootstrap-secret" in namespace "cattle-system" exists and cannot be imported into the current release: invalid ownership metadata; label validation error: missing key "app.kubernetes.io/managed-by": must be set to "Helm"; annotation validation error: missing key "meta.helm.sh/release-name": must be set to "rancher"; annotation validation error: missing key "meta.helm.sh/release-namespace": must be set to "cattle-system"
```

Additional info:
kubectl describe secret -n cattle-system bootstrap-secret
```
Name:         bootstrap-secret
Namespace:    cattle-system
Labels:       <none>
Annotations:  field.cattle.io/projectId: local:p-tb6n6

Type:  Opaque

Data
====
bootstrapPassword:  54 bytes
```

If the secret bootstrap is deleted from the rke cluster `kubectl delete secret -n cattle-system bootstrap-secret` , the installation goes through fine and the clusters have come up active.

**Comment by StrongMonkey** [comment] 2021-08-20 20:21
@nickgerace What we can do here
1. Not backing up that secret. Which is probably fine if you already reset your password.
2. Add helm annotation to it so helm knows about the resource prehand. This seems hacky.

**Comment by StrongMonkey** [comment] 2021-08-23 16:49
If we don't back up bootstrap secret, what will happen for the user is 
1. User set bootstrap secret(initial password) through `docker run`. 
2. User takes a backup, upgrade to HA.
3. User will lose its initial password.

This looks like a bad user experience if user hasn't reset password and store it somewhere else. They have to reset password. I would probably vote for hacking secret annotations.

**Comment by nickgerace** [comment] 2021-08-23 18:33
Spoke with @StrongMonkey and we believe that option number one is the best: https://github.com/rancher/rancher/issues/32711#issuecomment-902936201

Users can reset the password if forgotten, and keeping the default bootstrap password while performing this migration is likely an uncommon combination: https://rancher.com/docs/rancher/v2.5/en/faq/technical/

_However_, we do believe that we need a release note as well as a docs mention for this particular scenario.

**Comment by deniseschannon** [comment] 2021-08-23 21:24
Since the change is to remove the secret from being generated on single docker install.

Validate there are no regressions in these use cases:

1. Passwords are generated for single docker install
2. Passwords are still secrets for HA install

Validate the upgrade use case (docker install to HA)

**Closed** 2021-08-27 23:21 UTC
Labels: kind/task, area/backup-recover, [zube]: QA Working, status/dev-validate, QA/S
