### ISSUE TITLE
kubelet fails to start on K8s v1.11.8 setup with Docker 18.09

### ISSUE THREAD

**Issue by soumyalj** [rancher/rancher#18572] opened 2019-03-05 04:29 UTC
Version: v1.6.26 with catalog in v1.6-development branch
OS: Ubuntu 16.04
Docker version: 18.09.3

Steps:

1. Create a Kubernetes environment with K8s 1.11.8-rancher1-1 using Docker version 18.09 nodes

Kubelet fails to start with the below error:
```
Activating (Container should have been running but is in error state. Check logs for more information.: Error response from daemon: invalid mount config: must use either propagation mode "rslave" or "rshared" when mount source is within the daemon root, daemon root: "/var/lib/docker", bind mount source: "/var/lib/docker", propagation: "rprivate")

```

<img width="1394" alt="screen shot 2019-03-04 at 8 25 42 pm" src="https://user-images.githubusercontent.com/18536626/53780994-bd76d980-3ebb-11e9-9acc-b10c3c071755.png">

**Comment by alena1108** [comment] 2019-03-05 05:16
Closing as a duplicate of https://github.com/rancher/rancher/issues/17780 (release noted as a part of https://github.com/rancher/rancher/releases/v1.6.26)

**Closed by alena1108** 2019-03-05 05:16 UTC
Labels: kind/bug-qa, version/1.6
