### ISSUE TITLE
Apply scheduling policies to catalog services

### ISSUE THREAD

**Issue by galindro** [rancher/rancher#3314] opened 2016-01-18 00:55 UTC
How could I apply scheduling policies to the Gluster FS Stack deployed from Catalog? 

Is it possible to do this?

**Comment by galindro** [comment] 2016-01-18 16:08
I've made this PR: https://github.com/rancher/rancher-catalog/pull/85 to make possible to the user to choose where to put all of the deployed stack's containers....

**Comment by Verikon** [comment] 2016-03-25 18:41
+1

**Comment by deniseschannon** [comment] 2016-05-26 18:21
Duplicate of https://github.com/rancher/rancher/issues/2852

**Closed by deniseschannon** 2016-05-26 18:21 UTC
Labels: area/catalog, kind/enhancement, release/future
