### ISSUE TITLE
Rancher Backup cannot be upgraded/installed on local cluster 1.22.6+rke2r1

### ISSUE THREAD

**Issue by terickson** [rancher/rancher#37478] opened 2022-04-26 19:39 UTC
**Rancher Server Setup**
- Rancher version: 2.6.4
- Installation option (Docker install/Helm Chart): Helm
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): RKE1
- Proxy/Cert Details:

**Information about the Cluster**
- Kubernetes version: 1.22.6+rke2r1
- Cluster Type (Local/Downstream): local
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider):

**User Information**
- What is the role of the user logged in? (Admin/Cluster Owner/Cluster Member/Project Owner/Project Member/Custom)
  - If custom, define the set of permissions: Admin/Cluster

   
**Describe the bug**
When trying to install or upgrade "Racher Backups" from "Apps Marketplace" in Rancher we receive the following error:
Error: UPGRADE FAILED: current release manifest contains removed kubernetes api(s) for this kubernetes version and it is therefore unable to build the kubernetes objects for performing the diff. error from kubernetes: unable to recognize "": no matches for kind "CustomResourceDefinition" in version "apiextensions.k8s.io/v1beta1"

I think this has to do with the fact that K8's 1.22 removed CustomResourceDefinition apiextensions.k8s.io/v1beta1 and the helm chart must still reference that version.

**To Reproduce**
Install/Upgrade Rancher on  1.22.6+rke2r1 then try to install/upgrade "Racher Backups" from "Apps Marketplace" on that cluster.

**Result**
You will get an error:
Error: UPGRADE FAILED: current release manifest contains removed kubernetes api(s) for this kubernetes version and it is therefore unable to build the kubernetes objects for performing the diff. error from kubernetes: unable to recognize "": no matches for kind "CustomResourceDefinition" in version "apiextensions.k8s.io/v1beta1"

**Expected Result**
No error and the helm chart installs.

**Screenshots**

**Additional context**

**Comment by anupama2501** [comment] 2022-04-27 16:46
Hi @terickson Could please let us the rancher chart backup versions that was used to install?

I tried installing/upgrading the chart versions `2.1.0` and `2.1.1.`
Both of them install successfully without any error but the chart version `2.0.1` is giving me the same result.
```
Error: UPGRADE FAILED: current release manifest contains removed kubernetes api(s) for this kubernetes version and it is therefore unable to build the kubernetes objects for performing the diff. error from kubernetes: unable to recognize "": no matches for kind "CustomResourceDefinition" in version "apiextensions.k8s.io/v1beta1"
```

**Comment by terickson** [comment] 2022-04-27 19:03
Its Rancher Backups (2.1.1) and its a problem with a local cluster that has been upgraded to K8's 1.22.  I tried it again and the error I am getting is: unable to recognize "": no matches for kind "CustomResourceDefinition" in version "apiextensions.k8s.io/v1beta1"  That V1beta1 version was removed in k8s 1.22: https://kubernetes.io/blog/2021/08/04/kubernetes-1-22-release-announcement/#removal-of-several-deprecated-beta-apis

**Comment by anupama2501** [comment] 2022-04-27 22:00
Thank you @terickson for providing the information. Have a few more questions:
1. Was the backup chart installed on the local cluster before the k8s version was upgraded?
2. If so have you tried upgrading the chart to the version v2.1.1 post k8s upgrade?

**Comment by terickson** [comment] 2022-04-28 13:42
So in our production rancher we did have an older version of rancher backups installed on a 1-21 version of of the local cluster.  We have upgraded that recently to 1-22 so I tried the rancher backups upgrade on it to 2.1.1 and it failed with the same error.  So it looks like on a clean install or a upgrade this happens on K8's 1.22.

**Comment by mattskipton** [comment] 2022-08-23 15:11
I work with @terickson In our sand environment we have currently upgraded to rancher 2.6.7 and kube v1.22.11+rke2r1 We are now able to install rancher-backups but it does not show up in the installed apps list after install. We can use rancher-backups but can manage it as an installed app. Not a big issue
![Screen Shot 2022-08-23 at 10 09 56 AM](https://user-images.githubusercontent.com/23554894/186195187-8b74ede5-b793-4f9b-a493-0c4be1440392.png)
 like the issue started out as but still seems like a bug

**Comment by mattskipton** [comment] 2022-08-23 16:30
Doh, that was it, I'll delete my github account now ;) You can close this

**Comment by anupama2501** [comment] 2022-08-24 04:38
Closing as the issue is resolved from the above comments.

**Closed by anupama2501** 2022-08-24 04:38 UTC
