### ISSUE TITLE
Can't use EBS as a Volume for Kubernetes 1.3 Pod

### ISSUE THREAD

**Issue by galal-hussein** [rancher/rancher#5591] opened 2016-07-29 17:51 UTC
**Rancher Version:**
v1.2.0-pre1
**Docker Version:**
1.10.3
**OS and where are the hosts located? (cloud, bare metal, etc):**
Ubuntu
**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
single node rancher
**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Kubernetes 1.3
**Steps to Reproduce:**
- create an instance on aws with VolumeRole access.
- Register an instance on aws to Rancher.
- Label the instance with the following label: provider=aws
- Create a volume on aws in the same availability zone as the instnace/
-  run the following pod:

```
apiVersion: v1
kind: Pod
metadata:
  name: test-ebs
spec:
  nodeSelector:
    provider: aws
  containers:
  - image: nginx
    name: ebs-nginx
    volumeMounts:
    - mountPath: /usr/share/nginx/html
      name: test-volume
  volumes:
  - name: test-volume
    awsElasticBlockStore:
      volumeID: vol-xxxxxx #volume-id
      fsType: ext4
```

**Results:** 
The pod doesn't get created and it times out waiting for volume attachment:

```
  11m       11m     1   {default-scheduler }                Normal      Scheduled   Successfully assigned test-ebs to ip-172-31-8-78
  9m        31s     5   {kubelet ip-172-31-8-78}            Warning     FailedMount Unable to mount volumes for pod "test-ebs_default(3b861bea-55b3-11e6-9909-024f31b825bf)": timeout expired waiting for volumes to attach/mount for pod "test-ebs"/"default". list of unattached/unmounted volumes=[test-volume]
  9m        31s     5   {kubelet ip-172-31-8-78}            Warning     FailedSync  Error syncing pod, skipping: timeout expired waiting for volumes to attach/mount for pod "test-ebs"/"default". list of unattached/unmounted volumes=[test-volume
```

Kubelet logs:

```

7/29/2016 7:28:30 PME0729 17:28:30.066634    7458 goroutinemap.go:155] Operation for "kubernetes.io/aws-ebs/vol-a8f1ae0c" failed. No retries permitted until 2016-07-29 17:28:38.066629981 +0000 UTC (durationBeforeRetry 8s). error: Volume "kubernetes.io/aws-ebs/vol-a8f1ae0c" (spec.Name: "test-volume") pod "d8bc223d-55b1-11e6-9909-024f31b825bf" (UID: "d8bc223d-55b1-11e6-9909-024f31b825bf") is not yet attached according to node status.
7/29/2016 7:28:38 PMI0729 17:28:38.082389    7458 reconciler.go:179] VerifyControllerAttachedVolume operation started for volume "kubernetes.io/aws-ebs/vol-a8f1ae0c" (spec.Name: "test-volume") pod "d8bc223d-55b1-11e6-9909-024f31b825bf" (UID: "d8bc223d-55b1-11e6-9909-024f31b825bf")
7/29/2016 7:28:38 PME0729 17:28:38.180690    7458 goroutinemap.go:155] Operation for "kubernetes.io/aws-ebs/vol-a8f1ae0c" failed. No retries permitted until 2016-07-29 17:28:54.180685521 +0000 UTC (durationBeforeRetry 16s). error: Volume "kubernetes.io/aws-ebs/vol-a8f1ae0c" (spec.Name: "test-volume") pod "d8bc223d-55b1-11e6-9909-024f31b825bf" (UID: "d8bc223d-55b1-11e6-9909-024f31b825bf") is not yet attached according to node status.
7/29/2016 7:28:54 PMI0729 17:28:54.213019    7458 reconciler.go:179] VerifyControllerAttachedVolume operation started for volume "kubernetes.io/aws-ebs/vol-a8f1ae0c" (spec.Name: "test-volume") pod "d8bc223d-55b1-11e6-9909-024f31b825bf" (UID: "d8bc223d-55b1-11e6-9909-024f31b825bf")
7/29/2016 7:28:54 PME0729 17:28:54.314038    7458 goroutinemap.go:155] Operation for "kubernetes.io/aws-ebs/vol-a8f1ae0c" failed. No retries permitted until 2016-07-29 17:29:26.314032505 +0000 UTC (durationBeforeRetry 32s). error: Volume "kubernetes.io/aws-ebs/vol-a8f1ae0c" (spec.Name: "test-volume") pod "d8bc223d-55b1-11e6-9909-024f31b825bf" (UID: "d8bc223d-55b1-11e6-9909-024f31b825bf") is not yet attached according to node status.
7/29/2016 7:29:26 PMI0729 17:29:26.375140    7458 reconciler.go:179] VerifyControllerAttachedVolume operation started for volume "kubernetes.io/aws-ebs/vol-a8f1ae0c" (spec.Name: "test-volume") pod "d8bc223d-55b1-11e6-9909-024f31b825bf" (UID: "d8bc223d-55b1-11e6-9909-024f31b825bf")
7/29/2016 7:29:26 PME0729 17:29:26.472346    7458 goroutinemap.go:155] Operation for "kubernetes.io/aws-ebs/vol-a8f1ae0c" failed. No retries permitted until 2016-07-29 17:30:30.472341228 +0000 UTC (durationBeforeRetry 1m4s). error: Volume "kubernetes.io/aws-ebs/vol-a8f1ae0c" (spec.Name: "test-volume") pod "d8bc223d-55b1-11e6-9909-024f31b825bf" (UID: "d8bc223d-55b1-11e6-9909-024f31b825bf") is not yet attached according to node status.
7/29/2016 7:30:21 PME0729 17:30:21.847131    7458 kubelet.go:1930] Unable to mount volumes for pod "test-ebs_default(d8bc223d-55b1-11e6-9909-024f31b825bf)": timeout expired waiting for volumes to attach/mount for pod "test-ebs"/"default". list of unattached/unmounted volumes=[test-volume]; skipping pod
7/29/2016 7:30:21 PME0729 17:30:21.847192    7458 pod_workers.go:183] Error syncing pod d8bc223d-55b1-11e6-9909-024f31b825bf, skipping: timeout expired waiting for volumes to attach/mount for pod "test-ebs"/"default". list of unattached/unmounted volumes=[test-volume]
7/29/2016 7:30:30 PMI0729 17:30:30.531973    7458 reconciler.go:179] VerifyControllerAttachedVolume operation started for volume "kubernetes.io/aws-ebs/vol-a8f1ae0c" (spec.Name: "test-volume") pod "d8bc223d-55b1-11e6-9909-024f31b825bf" (UID: "d8bc223d-55b1-11e6-9909-024f31b825bf")
7/29/2016 7:30:30 PME0729 17:30:30.634466    7458 goroutinemap.go:155] Operation for "kubernetes.io/aws-ebs/vol-a8f1ae0c" failed. No retries permitted until 2016-07-29 17:32:30.634445804 +0000 UTC (durationBeforeRetry 2m0s). error: Volume "kubernetes.io/aws-ebs/vol-a8f1ae0c" (spec.Name: "test-volume") pod "d8bc223d-55b1-11e6-9909-024f31b825bf" (UID: "d8bc223d-55b1-11e6-9909-024f31b825bf") is not yet attached according to node status.
7/29/2016 7:30:35 PMI0729 17:30:35.039881    7458 reconciler.go:253] MountVolume operation started for volume "kubernetes.io/secret/default-token-gyup7" (spec.Name: "default-token-gyup7") to pod "d8bc223d-55b1-11e6-9909-024f31b825bf" (UID: "d8bc223d-55b1-11e6-9909-024f31b825bf"). Volume is already mounted to pod, but remount was requested.
7/29/2016 7:30:35 PMI0729 17:30:35.149607    7458 operation_executor.go:720] MountVolume.SetUp succeeded for volume "kubernetes.io/secret/default-token-gyup7" (spec.Name: "default-token-gyup7") pod "d8bc223d-55b1-11e6-9909-024f31b825bf" (UID: "d8bc223d-55b1-11e6-9909-024f31b825bf").
7/29/2016 7:30:48 PME0729 17:30:48.226527    7458 container_manager_linux.go:462] error opening pid file /var/run/docker.pid: open /var/run/docker.pid: no such file or directory
7/29/2016 7:32:30 PMI0729 17:32:30.683760    7458 reconciler.go:179] VerifyControllerAttachedVolume operation started for volume "kubernetes.io/aws-ebs/vol-a8f1ae0c" (spec.Name: "test-volume") pod "d8bc223d-55b1-11e6-9909-024f31b825bf" (UID: "d8bc223d-55b1-11e6-9909-024f31b825bf")
7/29/2016 7:32:30 PME0729 17:32:30.783600    7458 goroutinemap.go:155] Operation for "kubernetes.io/aws-ebs/vol-a8f1ae0c" failed. No retries permitted until 2016-07-29 17:34:30.783593242 +0000 UTC (durationBeforeRetry 2m0s). error: Volume "kubernetes.io/aws-ebs/vol-a8f1ae0c" (spec.Name: "test-volume") pod "d8bc223d-55b1-11e6-9909-024f31b825bf" (UID: "d8bc223d-55b1-11e6-9909-024f31b825bf") is not yet attached according to node status.
7/29/2016 7:32:35 PME0729 17:32:35.004695    7458 kubelet.go:1930] Unable to mount volumes for pod "test-ebs_default(d8bc223d-55b1-11e6-9909-024f31b825bf)": timeout expired waiting for volumes to attach/mount for pod "test-ebs"/"default". list of unattached/unmounted volumes=[test-volume]; skipping pod
7/29/2016 7:32:35 PME0729 17:32:35.004758    7458 pod_workers.go:183] Error syncing pod d8bc223d-55b1-11e6-9909-024f31b825bf, skipping: timeout expired waiting for volumes to attach/mount for pod "test-ebs"/"default". list of unattached/unmounted volumes=[test-volume]
7/29/2016 7:32:48 PMI0729 17:32:48.049699    7458 reconciler.go:253] MountVolume operation started for volume "kubernetes.io/secret/default-token-gyup7" (spec.Name: "default-token-gyup7") to pod "d8bc223d-55b1-11e6-9909-024f31b825bf" (UID: "d8bc223d-55b1-11e6-9909-024f31b825bf"). Volume is already mounted to pod, but remount was requested.
7/29/2016 7:32:48 PMI0729 17:32:48.148878    7458 operation_executor.go:720] MountVolume.SetUp succeeded for volume "kubernetes.io/secret/default-token-gyup7" (spec.Name: "default-token-gyup7") pod "d8bc223d-55b1-11e6-9909-024f31b825bf" (UID: "d8bc223d-55b1-11e6-9909-024f31b825bf").
7/29/2016 7:34:30 PMI0729 17:34:30.862813    7458 reconciler.go:179] VerifyControllerAttachedVolume operation started for volume "kubernetes.io/aws-ebs/vol-a8f1ae0c" (spec.Name: "test-volume") pod "d8bc223d-55b1-11e6-9909-024f31b825bf" (UID: "d8bc223d-55b1-11e6-9909-024f31b825bf")
7/29/2016 7:34:30 PME0729 17:34:30.960542    7458 goroutinemap.go:155] Operation for "kubernetes.io/aws-ebs/vol-a8f1ae0c" failed. No retries permitted until 2016-07-29 17:36:30.960524069 +0000 UTC (durationBeforeRetry 2m0s). error: Volume "kubernetes.io/aws-ebs/vol-a8f1ae0c" (spec.Name: "test-volume") pod "d8bc223d-55b1-11e6-9909-024f31b825bf" (UID: "d8bc223d-55b1-11e6-9909-024f31b825bf") is not yet attached according to node status.
7/29/2016 7:34:48 PME0729 17:34:48.009380    7458 kubelet.go:1930] Unable to mount volumes for pod "test-ebs_default(d8bc223d-55b1-11e6-9909-024f31b825bf)": timeout expired waiting for volumes to attach/mount for pod "test-ebs"/"default". list of unattached/unmounted volumes=[test-volume]; skipping pod
7/29/2016 7:34:48 PME0729 17:34:48.009697    7458 pod_workers.go:183] Error syncing pod d8bc223d-55b1-11e6-9909-024f31b825bf, skipping: timeout expired waiting for volumes to attach/mount for pod "test-ebs"/"default". list of unattached/unmounted volumes=[test-volume]
7/29/2016 7:34:49 PMI0729 17:34:49.419093    7458 reconciler.go:138] UnmountVolume operation started for volume "kubernetes.io/secret/default-token-gyup7" (spec.Name: "default-token-gyup7") from pod "d8bc223d-55b1-11e6-9909-024f31b825bf" (UID: "d8bc223d-55b1-11e6-9909-024f31b825bf").
7/29/2016 7:34:49 PMI0729 17:34:49.488490    7458 operation_executor.go:792] UnmountVolume.TearDown succeeded for volume "kubernetes.io/secret/default-token-gyup7" (volume.spec.Name: "default-token-gyup7") pod "d8bc223d-55b1-11e6-9909-024f31b825bf" (UID: "d8bc223d-55b1-11e6-9909-024f31b825bf").
7/29/2016 7:35:48 PME0729 17:35:48.289118    7458 container_manager_linux.go:462] error opening pid file /var/run/docker.pid: open /var/run/docker.pid: no such file or directory
7/29/2016 7:38:17 PMI0729 17:38:17.150983    7458 aws.go:587] Zone not specified in configuration file; querying AWS metadata service
7/29/2016 7:38:17 PME0729 17:38:17.633471    7458 aws.go:704] Tag "KubernetesCluster" not found; Kuberentes may behave unexpectedly.
7/29/2016 7:38:17 PMI0729 17:38:17.633579    7458 aws.go:711] AWS cloud - no tag filtering
7/29/2016 7:38:17 PMI0729 17:38:17.640180    7458 reconciler.go:179] VerifyControllerAttachedVolume operation started for volume "kubernetes.io/aws-ebs/vol-a8f1ae0c" (spec.Name: "test-volume") pod "3b861bea-55b3-11e6-9909-024f31b825bf" (UID: "3b861bea-55b3-11e6-9909-024f31b825bf")
7/29/2016 7:38:17 PME0729 17:38:17.644916    7458 goroutinemap.go:155] Operation for "kubernetes.io/aws-ebs/vol-a8f1ae0c" failed. No retries permitted until 2016-07-29 17:40:17.644903469 +0000 UTC (durationBeforeRetry 2m0s). error: Volume "kubernetes.io/aws-ebs/vol-a8f1ae0c" (spec.Name: "test-volume") pod "3b861bea-55b3-11e6-9909-024f31b825bf" (UID: "3b861bea-55b3-11e6-9909-024f31b825bf") has not yet been added to the list of VolumesInUse in the node's volume status.
7/29/2016 7:38:17 PMI0729 17:38:17.743036    7458 reconciler.go:179] VerifyControllerAttachedVolume operation started for volume "kubernetes.io/secret/default-token-gyup7" (spec.Name: "default-token-gyup7") pod "3b861bea-55b3-11e6-9909-024f31b825bf" (UID: "3b861bea-55b3-11e6-9909-024f31b825bf")
7/29/2016 7:38:17 PMI0729 17:38:17.843290    7458 reconciler.go:253] MountVolume operation started for volume "kubernetes.io/secret/default-token-gyup7" (spec.Name: "default-token-gyup7") to pod "3b861bea-55b3-11e6-9909-024f31b825bf" (UID: "3b861bea-55b3-11e6-9909-024f31b825bf").
7/29/2016 7:38:17 PMI0729 17:38:17.995852    7458 operation_executor.go:720] MountVolume.SetUp succeeded for volume "kubernetes.io/secret/default-token-gyup7" (spec.Name: "default-token-gyup7") pod "3b861bea-55b3-11e6-9909-024f31b825bf" (UID: "3b861bea-55b3-11e6-9909-024f31b825bf").
7/29/2016 7:40:17 PME0729 17:40:17.074192    7458 kubelet.go:1930] Unable to mount volumes for pod "test-ebs_default(3b861bea-55b3-11e6-9909-024f31b825bf)": timeout expired waiting for volumes to attach/mount for pod "test-ebs"/"default". list of unattached/unmounted volumes=[test-volume]; skipping pod
7/29/2016 7:40:17 PME0729 17:40:17.075106    7458 pod_workers.go:183] Error syncing pod 3b861bea-55b3-11e6-9909-024f31b825bf, skipping: timeout expired waiting for volumes to attach/mount for pod "test-ebs"/"default". list of unattached/unmounted volumes=[test-volume]
7/29/2016 7:40:17 PMI0729 17:40:17.742801    7458 reconciler.go:179] VerifyControllerAttachedVolume operation started for volume "kubernetes.io/aws-ebs/vol-a8f1ae0c" (spec.Name: "test-volume") pod "3b861bea-55b3-11e6-9909-024f31b825bf" (UID: "3b861bea-55b3-11e6-9909-024f31b825bf")
7/29/2016 7:40:17 PME0729 17:40:17.841299    7458 goroutinemap.go:155] Operation for "kubernetes.io/aws-ebs/vol-a8f1ae0c" failed. No retries permitted until 2016-07-29 17:42:17.841292546 +0000 UTC (durationBeforeRetry 2m0s). error: Volume "kubernetes.io/aws-ebs/vol-a8f1ae0c" (spec.Name: "test-volume") pod "3b861bea-55b3-11e6-9909-024f31b825bf" (UID: "3b861bea-55b3-11e6-9909-024f31b825bf") is not yet attached according to node status.
7/29/2016 7:40:28 PMI0729 17:40:28.061229    7458 reconciler.go:253] MountVolume operation started for volume "kubernetes.io/secret/default-token-gyup7" (spec.Name: "default-token-gyup7") to pod "3b861bea-55b3-11e6-9909-024f31b825bf" (UID: "3b861bea-55b3-11e6-9909-024f31b825bf"). Volume is already mounted to pod, but remount was requested.
7/29/2016 7:40:28 PMI0729 17:40:28.162395    7458 operation_executor.go:720] MountVolume.SetUp succeeded for volume "kubernetes.io/secret/default-token-gyup7" (spec.Name: "default-token-gyup7") pod "3b861bea-55b3-11e6-9909-024f31b825bf" (UID: "3b861bea-55b3-11e6-9909-024f31b825bf").
7/29/2016 7:40:48 PME0729 17:40:48.318935    7458 container_manager_linux.go:462] error opening pid file /var/run/docker.pid: open /var/run/docker.pid: no such file or directory
```

**Comment by alena1108** [comment] 2016-07-29 17:52
@wlan0 can you please look at it. We would have to release a new template once its's fixed.

**Comment by wlan0** [comment] 2016-08-01 17:15
@galal-hussein Tested this on master, and could not reproduce it. I created a ebs volume in the same zone and used it in the same pod template you've specified. It attached and mounted successfully. 

I checked that the volume status changed to "In-Use" in the EC2 volumes console
I checked that I can read and write to the directory in which the volume is mounted in the container.

**Comment by galal-hussein** [comment] 2016-08-01 18:01
@wlan0 I will re-test and let you know.

**Comment by galal-hussein** [comment] 2016-08-01 18:31
@wlan0 I tested it again, and it still failing, i created the ebs volume in the same AZ and and with the proper IAM role:

```
Name:		test-ebs
Namespace:	default
Node:		ip-172-31-12-86/52.19.232.95
Start Time:	Mon, 01 Aug 2016 20:24:37 +0200
Labels:		<none>
Status:		Pending
IP:		
Controllers:	<none>
Containers:
  ebs-nginx:
    Container ID:		
    Image:			nginx
    Image ID:			
    Port:			
    State:			Waiting
      Reason:			ContainerCreating
    Ready:			False
    Restart Count:		0
    Environment Variables:	<none>
Conditions:
  Type		Status
  Initialized 	True 
  Ready 	False 
  PodScheduled 	True 
Volumes:
  test-volume:
    Type:	AWSElasticBlockStore (a Persistent Disk resource in AWS)
    VolumeID:	vol-185bc4a9
    FSType:	ext4
    Partition:	0
    ReadOnly:	false
  default-token-iuac9:
    Type:	Secret (a volume populated by a Secret)
    SecretName:	default-token-iuac9
QoS Tier:	BestEffort
Events:
  FirstSeen	LastSeen	Count	From				SubobjectPath	Type		Reason		Message
  ---------	--------	-----	----				-------------	--------	------		-------
  2m		2m		1	{default-scheduler }				Normal		Scheduled	Successfully assigned test-ebs to ip-172-31-12-86
  17s		17s		1	{kubelet ip-172-31-12-86}			Warning		FailedMount	Unable to mount volumes for pod "test-ebs_default(3473f1db-5815-11e6-923b-024f316fef39)": timeout expired waiting for volumes to attach/mount for pod "test-ebs"/"default". list of unattached/unmounted volumes=[test-volume]
  17s		17s		1	{kubelet ip-172-31-12-86}			Warning		FailedSync	Error syncing pod, skipping: timeout expired waiting for volumes to attach/mount for pod "test-ebs"/"default". list of unattached/unmounted volumes=[test-volume]
```

**Comment by wlan0** [comment] 2016-08-01 23:05
It's a Kubernetes bug - https://github.com/kubernetes/kubernetes/issues/28643

The fix has been cherry picked in v1.3.4 - https://github.com/kubernetes/kubernetes/issues/28643

**Comment by wlan0** [comment] 2016-10-14 17:52
Will be fixed with flex volumes support.

**Comment by alena1108** [comment] 2016-10-14 20:12
@jimengliu

**Comment by wlan0** [comment] 2016-11-04 17:26
moving to 1.3, 'cos no time

**Comment by superseb** [comment] 2017-11-10 15:14
We can re-open or file a new issue if this is still broken.

**Closed by superseb** 2017-11-10 15:14 UTC
Labels: area/kubernetes, kind/bug
