### ISSUE TITLE
Services won't start if I click on the main Stack start button

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#2757] opened 2015-11-20 20:44 UTC
Version - Master

Steps:
1.  Create a new stack
2.  Add a simple ubuntu service to it and name it Service1
3.  Create another ubuntu service and link it to Service1 as name abc
4.  Create a Load Balancer and link it to Service1
Graph should look like this:
![image](https://cloud.githubusercontent.com/assets/11514927/11311276/03b2cbb2-8f8c-11e5-8b0c-9508cac84582.png)
5.  Now individually start each of these services, wait for them all to be active then stop them.
6.  Once they are all stopped, click the start icon by the Stack Name to start all services at once

Results:
They will not start.  They get stuck in Activating.  I have to click on them a couple of times to get them to stop.  The same if they are all active and I try to deactivate them.  They get stuck Deactivating.

Expected:
If I can start them individually, seems like I should be able to do it with the "all at once" option.

**Comment by alena1108** [comment] 2015-11-20 22:47
@tfiduccia this looks like a duplicate of https://github.com/rancher/rancher/issues/2735

It was fixed with commit 12ac72f9a1331909, could you re-test against the latest?

**Comment by deniseschannon** [comment] 2015-11-25 06:29
Verified with latest UI on v0.47.0-rc2

**Closed by deniseschannon** 2015-11-25 06:29 UTC
Labels: area/service, kind/bug, status/to-test
