### ISSUE TITLE
'spec.storage.volumeClaimTemplate.metadata.creationTimestamp in body must be of type string: "null"' error upgrading cluster-monitoring 0.0.3 with persistent prometheus storage to cluster-monitoring 0.0.5

### ISSUE THREAD

**Issue by axeal** [rancher/rancher#23857] opened 2019-11-04 13:19 UTC
**What kind of request is this (question/bug/enhancement/feature request):**

Bug

**Steps to reproduce (least amount of steps as possible):**

1. Install a simple 3 node all role custom cluster with Rancher v2.2.9 (I used https://github.com/superseb/tf-do-rancher2/)
2. Enable cluster monitoring with persistent storage for Prometheus (I used https://github.com/digitalocean/csi-digitalocean)
3. Observe storage spec of the following format in the prometheus cluster-monitoring object (`kubectl get prometheuses -n cattle-prometheus cluster-monitoring -o yaml`) (full object in attached [prometheus-0.0.3.txt](https://github.com/rancher/rancher/files/3804110/prometheus-0.0.3.txt)):
```
...
  storage:
    resources: {}
    volumeClaimTemplate:
      metadata:
        creationTimestamp: null
      spec:
        accessModes:
        - ReadWriteOnce
        dataSource: null
        resources:
          requests:
            storage: 1Gi
...
```
4. Upgrade Rancher to v2.3.2
5. Upgrade cluster monitoring to chart version 0.0.4, observe this completes successfully (prometheus object attached in [prometheus-0.0.4.txt](https://github.com/rancher/rancher/files/3804113/prometheus-0.0.4.txt)).
5. Upgrade cluster monitoring to chart version 0.0.5, observe this fails with error below (prometheus object attached in [prometheus-0.0.5-not-working.txt](https://github.com/rancher/rancher/files/3804116/prometheus-0.0.5-not-working.txt)).

**Result:**
```
Failed to install app cluster-monitoring. Error: UPGRADE FAILED: Prometheus.monitoring.coreos.com "cluster-monitoring" is invalid: []: Invalid value: map[string]interface {}{"apiVersion":"monitoring.coreos.com/v1", "kind":"Prometheus", "metadata":map[string]interface {}{"annotations":map[string]interface {}{"project.cattle.io/namespaces":"[\"cattle-prometheus\",\"cattle-system\",\"ingress-nginx\",\"kube-node-lease\",\"kube-public\",\"kube-system\"]"}, "creationTimestamp":"2019-11-04T12:50:12Z", "generation":5, "labels":map[string]interface {}{"app":"prometheus", "chart":"prometheus-0.0.1", "heritage":"Tiller", "io.cattle.field/appId":"cluster-monitoring", "release":"cluster-monitoring"}, "name":"cluster-monitoring", "namespace":"cattle-prometheus", "resourceVersion":"3634", "uid":"6c395567-4599-44b2-8b2a-a514536097dd"}, "spec":map[string]interface {}{"additionalAlertManagerConfigs":map[string]interface {}{"key":"additional-alertmanager-configs.yaml", "name":"prometheus-cluster-monitoring-additional-alertmanager-configs"}, "additionalScrapeConfigs":map[string]interface {}{"key":"additional-scrape-configs.yaml", "name":"prometheus-cluster-monitoring-additional-scrape-configs"}, "affinity":map[string]interface {}{"podAntiAffinity":map[string]interface {}{"preferredDuringSchedulingIgnoredDuringExecution":[]interface {}{map[string]interface {}{"podAffinityTerm":map[string]interface {}{"labelSelector":map[string]interface {}{"matchLabels":map[string]interface {}{"app":"prometheus", "prometheus":"cluster-monitoring"}}, "topologyKey":"kubernetes.io/hostname"}, "weight":100}}}}, "baseImage":"rancher/prom-prometheus", "configMaps":[]interface {}{"prometheus-cluster-monitoring-nginx"}, "containers":[]interface {}{map[string]interface {}{"command":[]interface {}{"/bin/sh", "-c", "cp /nginx/run-sh.tmpl /var/cache/nginx/nginx-start.sh; chmod +x /var/cache/nginx/nginx-start.sh; /var/cache/nginx/nginx-start.sh"}, "env":[]interface {}{map[string]interface {}{"name":"POD_IP", "valueFrom":map[string]interface {}{"fieldRef":map[string]interface {}{"fieldPath":"status.podIP"}}}}, "image":"rancher/nginx:1.17.4-alpine", "name":"prometheus-proxy", "ports":[]interface {}{map[string]interface {}{"containerPort":8080, "name":"http", "protocol":"TCP"}}, "resources":map[string]interface {}{"limits":map[string]interface {}{"cpu":"100m", "memory":"100Mi"}, "requests":map[string]interface {}{"cpu":"50m", "memory":"50Mi"}}, "securityContext":map[string]interface {}{"runAsGroup":101, "runAsUser":101}, "volumeMounts":[]interface {}{map[string]interface {}{"mountPath":"/nginx", "name":"configmap-prometheus-cluster-monitoring-nginx"}, map[string]interface {}{"mountPath":"/var/cache/nginx", "name":"nginx-home"}}}, map[string]interface {}{"args":[]interface {}{"--proxy-url=http://127.0.0.1:9090", "--listen-address=$(POD_IP):9090", "--filter-reader-labels=prometheus", "--filter-reader-labels=prometheus_replica"}, "command":[]interface {}{"prometheus-auth"}, "env":[]interface {}{map[string]interface {}{"name":"POD_IP", "valueFrom":map[string]interface {}{"fieldRef":map[string]interface {}{"fieldPath":"status.podIP"}}}}, "image":"rancher/prometheus-auth:v0.2.0", "livenessProbe":map[string]interface {}{"failureThreshold":6, "httpGet":map[string]interface {}{"path":"/-/healthy", "port":"web", "scheme":"HTTP"}, "periodSeconds":10, "successThreshold":1, "timeoutSeconds":10}, "name":"prometheus-agent", "ports":[]interface {}{map[string]interface {}{"containerPort":9090, "name":"web", "protocol":"TCP"}}, "readinessProbe":map[string]interface {}{"failureThreshold":10, "httpGet":map[string]interface {}{"path":"/-/ready", "port":"web", "scheme":"HTTP"}, "periodSeconds":10, "successThreshold":1, "timeoutSeconds":10}, "resources":map[string]interface {}{"limits":map[string]interface {}{"cpu":"500m", "memory":"200Mi"}, "requests":map[string]interface {}{"cpu":"100m", "memory":"100Mi"}}}}, "evaluationInterval":"60s", "externalLabels":map[string]interface {}{"prometheus_from":"custom"}, "listenLocal":true, "logFormat":"logfmt", "logLevel":"info", "nodeSelector":map[string]interface {}{"kubernetes.io/os":"linux"}, "podMetadata":map[string]interface {}{"creationTimestamp":"2019-11-04T13:02:49Z", "labels":map[string]interface {}{"app":"prometheus", "chart":"prometheus-0.0.1", "release":"cluster-monitoring"}}, "replicas":1, "resources":map[string]interface {}{"limits":map[string]interface {}{"cpu":"1", "memory":"1000Mi"}, "requests":map[string]interface {}{"cpu":"750m", "memory":"750Mi"}}, "retention":"12h", "ruleNamespaceSelector":map[string]interface {}{"matchExpressions":[]interface {}{map[string]interface {}{"key":"field.cattle.io/projectId", "operator":"In", "values":[]interface {}{"p-v2428"}}, map[string]interface {}{"key":"field.cattle.io/projectId", "operator":"In", "values":[]interface {}{"p-v2428"}}}}, "ruleSelector":map[string]interface {}{"matchExpressions":[]interface {}{map[string]interface {}{"key":"source", "operator":"In", "values":[]interface {}{"rancher-alert", "rancher-monitoring"}}}}, "scrapeInterval":"60s", "secrets":[]interface {}{"exporter-etcd-cert"}, "securityContext":map[string]interface {}{"fsGroup":2000, "runAsNonRoot":true, "runAsUser":1000}, "serviceAccountName":"cluster-monitoring", "serviceMonitorNamespaceSelector":map[string]interface {}{"matchExpressions":[]interface {}{map[string]interface {}{"key":"field.cattle.io/projectId", "operator":"In", "values":[]interface {}{"p-v2428"}}, map[string]interface {}{"key":"field.cattle.io/projectId", "operator":"In", "values":[]interface {}{"p-v2428"}}}}, "serviceMonitorSelector":map[string]interface {}{}, "storage":map[string]interface {}{"resources":map[string]interface {}{}, "volumeClaimTemplate":map[string]interface {}{"metadata":map[string]interface {}{"creationTimestamp":interface {}(nil)}, "spec":map[string]interface {}{"accessModes":[]interface {}{"ReadWriteOnce"}, "dataSource":interface {}(nil), "resources":map[string]interface {}{"requests":map[string]interface {}{"storage":"1Gi"}}}, "status":map[string]interface {}{}}}, "tolerations":[]interface {}{map[string]interface {}{"effect":"NoSchedule", "key":"cattle.io/os", "operator":"Equal", "value":"linux"}}, "version":"v2.11.1", "volumes":[]interface {}{map[string]interface {}{"emptyDir":map[string]interface {}{}, "name":"nginx-home"}}}}: validation failure list: spec.storage.volumeClaimTemplate.spec.dataSource in body must be of type object: "null" spec.storage.volumeClaimTemplate.metadata.creationTimestamp in body must be of type string: "null" 
```

**Workaround:**

1. Edit the cluster-monitoring prometheus object (`kubectl edit prometheuses -n cattle-prometheus cluster-monitoring`) to remove `spec.storage.volumeClaimTemplate.metadata` and `spec.storage.volumeClaimTemplate.spec.dataSource`.
2. Trigger redeployment, by selecting 'Upgrade' option on the cluster-monitoring app in the System Project and clicking 'Upgrade' (prometheus object attached in [prometheus-0.0.5-working.txt](https://github.com/rancher/rancher/files/3804129/prometheus-0.0.5-working.txt)).

**Comment by superseb** [comment] 2019-11-04 15:26
Sounds like a duplicate of https://github.com/rancher/rancher/issues/22915

**Comment by axeal** [comment] 2019-11-06 13:09
Similar to that issue in as far as Prometheuses validation failing on upgrade, but in this instance cluster-monitoring with persistent storage failing on the upgrade to 0.0.5.

**Comment by guangbochen** [comment] 2019-11-11 06:17
this should be a bug, will fix in the coming releases.
for a workaround, can u please try `kubectl edit prometheuses -n cattle-prometheus cluster-monitoring` and set the `creationTimestamp` to a specific date like "2019-11-08T07:57:59Z" instread of null, then doing the upgrade to check if it will works, thanks.

**Comment by aggyomfg** [comment] 2019-11-28 02:29
> this should be a bug, will fix in the coming releases.
> for a workaround, can u please try `kubectl edit prometheuses -n cattle-prometheus cluster-monitoring` and set the `creationTimestamp` to a specific date like `"2019-11-08T07:57:59Z"` instead of null, then doing the upgrade to check if it will works, thanks.

kubectl reply:
 `error: prometheuses.monitoring.coreos.com "cluster-monitoring" is invalid`

**Comment by loganhz** [comment] 2019-12-10 04:06
link to https://github.com/coreos/prometheus-operator/pull/2857

**Comment by loganhz** [comment] 2019-12-12 05:53
Monitoring 0.0.7 has been merged in dev branch.

**Comment by jiaqiluo** [comment] 2019-12-12 20:06
The bug is reproduced in the upgrade path from v2.2.9 to v2.3.3

The steps are the same as the issue provides.

Results:
<img width="1245" alt="Screen Shot 2019-12-12 at 12 42 52 PM" src="https://user-images.githubusercontent.com/6218999/70744936-075cdd80-1ce0-11ea-94b8-c8756456269c.png">
<img width="1196" alt="Screen Shot 2019-12-12 at 12 42 58 PM" src="https://user-images.githubusercontent.com/6218999/70744937-075cdd80-1ce0-11ea-9a15-b6c87cf1596e.png">

**Comment by jiaqiluo** [comment] 2019-12-12 22:46
The bug fix is validated with the Monitoring template version **0.0.7** in master-head 624460445

Cluster monitoring is upgraded successfully with this upgrade path: **0.0.3 -> 0.0.4 -> 0.0.7** 

----

Cluster monitoring is FAILED to upgrad with this upgrade path: **0.0.3 -> 0.0.7** 

Problem:  the pod `prometheus-cluster-monitoring-0` can not mount the volume after upgrading the cluster monitoring

<img width="1245" alt="Screen Shot 2019-12-12 at 12 42 52 PM" src="https://user-images.githubusercontent.com/6218999/70754925-b2c45d00-1cf5-11ea-9317-5e66fbb452cb.png">

<img width="1225" alt="Screen Shot 2019-12-12 at 3 43 32 PM" src="https://user-images.githubusercontent.com/6218999/70755115-354d1c80-1cf6-11ea-95c4-df8415cbe518.png">


<img width="1279" alt="Screen Shot 2019-12-12 at 3 23 16 PM" src="https://user-images.githubusercontent.com/6218999/70755060-16e72100-1cf6-11ea-9db4-424847c3429f.png">

cc/ @loganhz @guangbochen

**Comment by loganhz** [comment] 2019-12-13 03:07
Hi @jiaqiluo , we can not reproduce it using NFS (in Catalog) as the storage cluster.
Upgrading from 0.0.3 to 0.0.7 works.
Could you file another issue for the PV mount issue, please? It's not related to the change.

**Comment by jiaqiluo** [comment] 2019-12-13 16:36
@loganhz  Thanks for the feedback.

A new issue is made to track the volume issue: https://github.com/rancher/rancher/issues/24582

This issue can be closed.

**Closed by jiaqiluo** 2019-12-13 16:36 UTC
Labels: [zube]: To Test, area/monitoring, internal, kind/bug, team/cn
