### ISSUE TITLE
containers are not scheduled to hosts without label value

### ISSUE THREAD

**Issue by ndelitski** [rancher/rancher#2872] opened 2015-12-02 14:14 UTC
dont work
```
io.rancher.scheduler.affinity:host_label: drone.worker
```
works
```
io.rancher.scheduler.affinity:host_label: drone.worker=true
```

**Comment by ndelitski** [comment] 2015-12-02 14:14
```
Rancher	v0.47.0
Cattle	v0.115.0
User Interface	v0.68.0
```
Using rancher-compose 0.5.2

**Comment by deniseschannon** [comment] 2015-12-02 14:58
Duplicate of https://github.com/rancher/rancher/issues/2601

**Closed by deniseschannon** 2015-12-02 14:58 UTC
