### ISSUE TITLE
When existing managed containers on the host get synced to the server as part of host registration, they are not created as part of managed network.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#1102] opened 2015-06-09 01:10 UTC
When existing managed containers on the host get synced to the server as part of host registration, they are not created as part of managed network.

Steps to reproduce the problem:
Registered a host as part of default environment.
Added few containers in managed network to this host .
Deleted this host from this environment ( Stopped the host VM and deleted the host from rancher server).
Added this host back to a different environment in the same rancher server.

When the host was added , the containers were synced to the server. But they were not deployed as part of managed network.

Expected behavior:
Network agent should be started and the container should get created in this managed network.

Question - docker inspect of the container has managed network ip address published. Will we give the same ip to this container when this container is synced to rancher server?
  
        "Labels": {
            "io.rancher.container.ip": "10.42.227.207/16",
            "io.rancher.container.uuid": "38376511-2ab1-476c-a0a0-ebd1750930ea"
        },

**Comment by cjellick** [comment] 2015-12-04 16:55
Dupe of #929. Closing

**Closed by cjellick** 2015-12-04 16:55 UTC
Labels: area/native-docker, kind/bug
