### ISSUE TITLE
Mismatch between timeout values on loadbalancer between database server and rancher/server blocks operations

### ISSUE THREAD

**Issue by njordr** [rancher/rancher#8370] opened 2017-03-31 06:55 UTC
**Rancher Versions:**
Server: 1.5.3
healthcheck: rancher/healthcheck:v0.2.3
ipsec: rancher/net:holder
network-services: rancher/metadata:v0.8.11, rancher/network-manager:v0.5.3
scheduler: rancher/scheduler:v0.7.5
kubernetes (if applicable): NA (I'm using cattle)

**Docker Version:**
1.12.6
**OS and where are the hosts located? (cloud, bare metal, etc):**
Ubuntu 16.04.2 (VMWare)
**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
HA rancher with external DB
**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle
**Steps to Reproduce:**
Run rancher and wait. Command used to run rancher:
```
docker run -d --restart=unless-stopped -p 8080:8080 -p 9345:9345 --name=rancher-server-01 rancher/server --db-host 10.209.113.25 --db-port 33061 --db-user cattle --db-pass <password> --db-name cattle --advertise-address 10.209.113.25
```
**Results:** 
Before the database migration
```
14:46:01.087 [main] WARN  liquibase - modifyDataType will lose primary key/autoincrement/not null settings for mysql.  Use <sql> and re-specify all configuration if this is the case
```

After a while:
```
[mysql] 2017/03/30 14:51:54 packets.go:130: write tcp 172.17.0.2:37436->10.209.113.25:33061: write: broken pipe
2017-03-30 14:52:14,958 ERROR [:] [] [] [] [ecutorService-3] [o.a.c.m.context.NoExceptionRunnable ] Uncaught exception org.jooq.exception.DataAccessException: SQL [select `process_instance`.`id`, `process_instance`.`start_time`, `process_instance`.`end_time`, `process_instance`.`data`, `process_instance`.`priority`, `process_instance`.`process_name`, `process_instance`.`resource_type`, `process_instance`.`resource_id`, `process_instance`.`result`, `process_instance`.`exit_reason`, `process_instance`.`phase`, `process_instance`.`start_process_server_id`, `process_instance`.`running_process_server_id`, `process_instance`.`execution_count`, `process_instance`.`run_after`, `process_instance`.`account_id` from `process_instance` where `process_instance`.`id` = ?]; (conn:10) Could not read packet: unexpected end of stream, read 0 bytes from 4
Query is: select `process_instance`.`id`, `process_instance`.`start_time`, `process_instance`.`end_time`, `process_instance`.`data`, `process_instance`.`priority`, `process_instance`.`process_name`, `process_instance`.`resource_type`, `process_instance`.`resource_id`, `process_instance`.`result`, `process_instance`.`exit_reason`, `process_instance`.`phase`, `process_instance`.`start_process_server_id`, `process_instance`.`running_process_server_id`, `process_instance`.`execution_count`, `process_instance`.`run_after`, `process_instance`.`account_id` from `process_instance` where `process_instance`.`id` = ?, parameters [126]
	at org.jooq.impl.Utils.translate(Utils.java:1287) ~[jooq-3.3.0.jar:na]
	at org.jooq.impl.DefaultExecuteContext.sqlException(DefaultExecuteContext.java:495) ~[jooq-3.3.0.jar:na]
	at org.jooq.impl.AbstractQuery.execute(AbstractQuery.java:326) ~[jooq-3.3.0.jar:na]
	at org.jooq.impl.AbstractResultQuery.fetchLazy(AbstractResultQuery.java:351) ~[jooq-3.3.0.jar:na]
	at org.jooq.impl.AbstractResultQuery.fetchLazy(AbstractResultQuery.java:341) ~[jooq-3.3.0.jar:na]
	at org.jooq.impl.AbstractResultQuery.fetchOne(AbstractResultQuery.java:470) ~[jooq-3.3.0.jar:na]
	at org.jooq.impl.SelectImpl.fetchOne(SelectImpl.java:2372) ~[jooq-3.3.0.jar:na]
	at io.cattle.platform.object.jooq.utils.JooqUtils.findById(JooqUtils.java:43) ~[cattle-framework-object-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.object.impl.JooqObjectManager.loadResource(JooqObjectManager.java:472) ~[cattle-framework-object-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.object.impl.JooqObjectManager.loadResource(JooqObjectManager.java:457) ~[cattle-framework-object-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.engine.manager.impl.jooq.JooqProcessRecordDao.loadReference(JooqProcessRecordDao.java:261) ~[cattle-iaas-engine-jooq-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.engine.manager.impl.DefaultProcessManager.loadReference(DefaultProcessManager.java:209) ~[cattle-framework-engine-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.engine.eventing.impl.ProcessEventListenerImpl.processExecute(ProcessEventListenerImpl.java:23) ~[cattle-framework-engine-0.5.0-SNAPSHOT.jar:na]
	at sun.reflect.GeneratedMethodAccessor499.invoke(Unknown Source) ~[na:na]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_72]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_72]
	at io.cattle.platform.eventing.annotation.MethodInvokingListener$1.doWithLockNoResult(MethodInvokingListener.java:76) ~[cattle-framework-eventing-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.lock.LockCallbackNoReturn.doWithLock(LockCallbackNoReturn.java:7) ~[cattle-framework-lock-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.lock.LockCallbackNoReturn.doWithLock(LockCallbackNoReturn.java:3) ~[cattle-framework-lock-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.lock.impl.AbstractLockManagerImpl$3.doWithLock(AbstractLockManagerImpl.java:40) ~[cattle-framework-lock-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.lock.impl.LockManagerImpl.doLock(LockManagerImpl.java:33) ~[cattle-framework-lock-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.lock.impl.AbstractLockManagerImpl.lock(AbstractLockManagerImpl.java:13) ~[cattle-framework-lock-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.lock.impl.AbstractLockManagerImpl.lock(AbstractLockManagerImpl.java:37) ~[cattle-framework-lock-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.eventing.annotation.MethodInvokingListener.onEvent(MethodInvokingListener.java:72) ~[cattle-framework-eventing-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.eventing.impl.AbstractThreadPoolingEventService$2.doRun(AbstractThreadPoolingEventService.java:141) ~[cattle-framework-eventing-0.5.0-SNAPSHOT.jar:na]
	at org.apache.cloudstack.managed.context.NoExceptionRunnable.runInContext(NoExceptionRunnable.java:15) ~[cattle-framework-managed-context-0.5.0-SNAPSHOT.jar:na]
	at org.apache.cloudstack.managed.context.ManagedContextRunnable$1.run(ManagedContextRunnable.java:49) [cattle-framework-managed-context-0.5.0-SNAPSHOT.jar:na]
	at org.apache.cloudstack.managed.context.impl.DefaultManagedContext$1.call(DefaultManagedContext.java:55) [cattle-framework-managed-context-0.5.0-SNAPSHOT.jar:na]
	at org.apache.cloudstack.managed.context.impl.DefaultManagedContext.callWithContext(DefaultManagedContext.java:108) [cattle-framework-managed-context-0.5.0-SNAPSHOT.jar:na]
	at org.apache.cloudstack.managed.context.impl.DefaultManagedContext.runWithContext(DefaultManagedContext.java:52) [cattle-framework-managed-context-0.5.0-SNAPSHOT.jar:na]
	at org.apache.cloudstack.managed.context.ManagedContextRunnable.run(ManagedContextRunnable.java:46) [cattle-framework-managed-context-0.5.0-SNAPSHOT.jar:na]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_72]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_72]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_72]
Caused by: java.sql.SQLNonTransientConnectionException: (conn:10) Could not read packet: unexpected end of stream, read 0 bytes from 4
Query is: select `process_instance`.`id`, `process_instance`.`start_time`, `process_instance`.`end_time`, `process_instance`.`data`, `process_instance`.`priority`, `process_instance`.`process_name`, `process_instance`.`resource_type`, `process_instance`.`resource_id`, `process_instance`.`result`, `process_instance`.`exit_reason`, `process_instance`.`phase`, `process_instance`.`start_process_server_id`, `process_instance`.`running_process_server_id`, `process_instance`.`execution_count`, `process_instance`.`run_after`, `process_instance`.`account_id` from `process_instance` where `process_instance`.`id` = ?, parameters [126]
	at org.mariadb.jdbc.internal.util.ExceptionMapper.get(ExceptionMapper.java:137) ~[mariadb-java-client-1.5.8.jar:na]
	at org.mariadb.jdbc.internal.util.ExceptionMapper.getException(ExceptionMapper.java:101) ~[mariadb-java-client-1.5.8.jar:na]
	at org.mariadb.jdbc.internal.util.ExceptionMapper.throwAndLogException(ExceptionMapper.java:77) ~[mariadb-java-client-1.5.8.jar:na]
	at org.mariadb.jdbc.MariaDbStatement.executeQueryEpilog(MariaDbStatement.java:224) ~[mariadb-java-client-1.5.8.jar:na]
	at org.mariadb.jdbc.MariaDbServerPreparedStatement.executeInternal(MariaDbServerPreparedStatement.java:411) ~[mariadb-java-client-1.5.8.jar:na]
	at org.mariadb.jdbc.MariaDbServerPreparedStatement.execute(MariaDbServerPreparedStatement.java:361) ~[mariadb-java-client-1.5.8.jar:na]
	at org.apache.commons.dbcp.DelegatingPreparedStatement.execute(DelegatingPreparedStatement.java:172) ~[commons-dbcp-1.4.jar:1.4]
	at org.apache.commons.dbcp.DelegatingPreparedStatement.execute(DelegatingPreparedStatement.java:172) ~[commons-dbcp-1.4.jar:1.4]
	at org.jooq.tools.jdbc.DefaultPreparedStatement.execute(DefaultPreparedStatement.java:194) ~[jooq-3.3.0.jar:na]
	at org.jooq.impl.AbstractResultQuery.execute(AbstractResultQuery.java:261) ~[jooq-3.3.0.jar:na]
	at org.jooq.impl.AbstractQuery.execute(AbstractQuery.java:322) ~[jooq-3.3.0.jar:na]
	... 31 common frames omitted
Caused by: org.mariadb.jdbc.internal.util.dao.QueryException: Could not read packet: unexpected end of stream, read 0 bytes from 4
Query is: select `process_instance`.`id`, `process_instance`.`start_time`, `process_instance`.`end_time`, `process_instance`.`data`, `process_instance`.`priority`, `process_instance`.`process_name`, `process_instance`.`resource_type`, `process_instance`.`resource_id`, `process_instance`.`result`, `process_instance`.`exit_reason`, `process_instance`.`phase`, `process_instance`.`start_process_server_id`, `process_instance`.`running_process_server_id`, `process_instance`.`execution_count`, `process_instance`.`run_after`, `process_instance`.`account_id` from `process_instance` where `process_instance`.`id` = ?, parameters [126]
	at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.readPacket(AbstractQueryProtocol.java:1031) ~[mariadb-java-client-1.5.8.jar:na]
	at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.getResult(AbstractQueryProtocol.java:1002) ~[mariadb-java-client-1.5.8.jar:na]
	at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.executePreparedQuery(AbstractQueryProtocol.java:588) ~[mariadb-java-client-1.5.8.jar:na]
	at org.mariadb.jdbc.MariaDbServerPreparedStatement.executeInternal(MariaDbServerPreparedStatement.java:399) ~[mariadb-java-client-1.5.8.jar:na]
	... 37 common frames omitted
Caused by: java.io.EOFException: unexpected end of stream, read 0 bytes from 4
	at org.mariadb.jdbc.internal.packet.read.ReadPacketFetcher.getReusableBuffer(ReadPacketFetcher.java:178) ~[mariadb-java-client-1.5.8.jar:na]
	at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.readPacket(AbstractQueryProtocol.java:1022) ~[mariadb-java-client-1.5.8.jar:na]
	... 40 common frames omitted
```

Also
```
[mysql] 2017/03/30 17:56:55 packets.go:130: write tcp 172.17.0.2:51058->10.209.113.25:33061: write: broken pipe
[mysql] 2017/03/30 18:01:55 packets.go:33: unexpected EOF
```

A similar bug was closed: https://github.com/rancher/rancher/issues/5998

Googling it seems that there are some changes to do on go side:
https://github.com/go-sql-driver/mysql/issues/446

MySQL 5.7 deploy directly on ubuntu (not with docker)

A simple way to trigger the exception is to add a service. The exception blocks the delivery of the service.

**Comment by njordr** [comment] 2017-04-06 10:17
Any chance to look into this? I cannot put Rancher in cluster mode in production

**Comment by alexanderdalloz** [comment] 2017-05-22 09:34
I see this too frequently on all 3 rancher-server nodes. Backend is a 2 node MariaDB Galera cluster.  It is Rancher 1.5.9 with fully updated stacks, running on CentOS 7.

`[mysql] 2017/05/22 08:16:47 packets.go:33: unexpected EOF
[mysql] 2017/05/22 08:16:47 packets.go:130: write tcp 172.17.0.2:36576->172.17.0.1:3306: write: broken pipe
[mysql] 2017/05/22 08:18:42 packets.go:33: unexpected EOF
[mysql] 2017/05/22 08:18:42 packets.go:130: write tcp 172.17.0.2:37316->172.17.0.1:3306: write: broken pipe
[mysql] 2017/05/22 08:18:42 packets.go:33: unexpected EOF
[mysql] 2017/05/22 08:18:42 packets.go:130: write tcp 172.17.0.2:37348->172.17.0.1:3306: write: broken pipe
[mysql] 2017/05/22 08:23:12 packets.go:33: unexpected EOF
[mysql] 2017/05/22 08:23:12 packets.go:130: write tcp 172.17.0.2:37692->172.17.0.1:3306: write: broken pipe
[mysql] 2017/05/22 08:28:42 packets.go:33: unexpected EOF
[mysql] 2017/05/22 08:28:42 packets.go:130: write tcp 172.17.0.2:38602->172.17.0.1:3306: write: broken pipe
[mysql] 2017/05/22 08:28:42 packets.go:33: unexpected EOF
[mysql] 2017/05/22 08:28:42 packets.go:130: write tcp 172.17.0.2:38574->172.17.0.1:3306: write: broken pipe
[mysql] 2017/05/22 08:33:42 packets.go:33: unexpected EOF
[mysql] 2017/05/22 08:33:42 packets.go:130: write tcp 172.17.0.2:40048->172.17.0.1:3306: write: broken pipe
[mysql] 2017/05/22 08:38:42 packets.go:33: unexpected EOF
[mysql] 2017/05/22 08:38:42 packets.go:130: write tcp 172.17.0.2:40986->172.17.0.1:3306: write: broken pipe
[mysql] 2017/05/22 08:43:42 packets.go:33: unexpected EOF
[mysql] 2017/05/22 08:43:42 packets.go:130: write tcp 172.17.0.2:41988->172.17.0.1:3306: write: broken pipe
[mysql] 2017/05/22 08:48:42 packets.go:33: unexpected EOF
[mysql] 2017/05/22 08:48:42 packets.go:130: write tcp 172.17.0.2:43072->172.17.0.1:3306: write: broken pipe
[mysql] 2017/05/22 08:50:08 packets.go:33: unexpected EOF
[mysql] 2017/05/22 08:50:08 packets.go:130: write tcp 172.17.0.2:43932->172.17.0.1:3306: write: broken pipe
[mysql] 2017/05/22 08:53:42 packets.go:33: unexpected EOF
[mysql] 2017/05/22 08:53:42 packets.go:130: write tcp 172.17.0.2:44630->172.17.0.1:3306: write: broken pipe
[mysql] 2017/05/22 08:53:42 packets.go:33: unexpected EOF
[mysql] 2017/05/22 08:53:42 packets.go:130: write tcp 172.17.0.2:44648->172.17.0.1:3306: write: broken pipe`

Timestamps are remarkable. So those are not random failures due to network issues. Anything we can tweak?

**Comment by cjellick** [comment] 2017-05-22 16:40
@alexanderdalloz @njordr, per the issue referenced by @njordr, I'm wondering what you wait_timeout is. Can you share the results of
```
show variables like '%timeout%';
```

Also, in interest of disclosure, I tweak your last comment to better format the logs you shared @alexanderdalloz.

**Comment by njordr** [comment] 2017-05-23 07:30
Mine is

```
mysql> show variables like '%timeout%';
+-----------------------------+----------+
| Variable_name               | Value    |
+-----------------------------+----------+
| connect_timeout             | 10       |
| delayed_insert_timeout      | 300      |
| have_statement_timeout      | YES      |
| innodb_flush_log_at_timeout | 1        |
| innodb_lock_wait_timeout    | 50       |
| innodb_rollback_on_timeout  | OFF      |
| interactive_timeout         | 28800    |
| lock_wait_timeout           | 31536000 |
| net_read_timeout            | 30       |
| net_write_timeout           | 60       |
| rpl_stop_slave_timeout      | 31536000 |
| slave_net_timeout           | 60       |
| wait_timeout                | 28800    |
+-----------------------------+----------+

```
I can't replicate the issue anymore, I needed to move to a mysql cluster with pacemaker

**Comment by alexanderdalloz** [comment] 2017-05-23 08:30
```
MariaDB [(none)]> show variables like '%timeout%';
+-----------------------------+----------+
| Variable_name               | Value    |
+-----------------------------+----------+
| connect_timeout             | 10       |
| deadlock_timeout_long       | 50000000 |
| deadlock_timeout_short      | 10000    |
| delayed_insert_timeout      | 300      |
| innodb_flush_log_at_timeout | 1        |
| innodb_lock_wait_timeout    | 50       |
| innodb_rollback_on_timeout  | OFF      |
| interactive_timeout         | 28800    |
| lock_wait_timeout           | 31536000 |
| net_read_timeout            | 30       |
| net_write_timeout           | 60       |
| slave_net_timeout           | 3600     |
| thread_pool_idle_timeout    | 60       |
| wait_timeout                | 28800    |
+-----------------------------+----------+
```
That's mariadb-server-10.1.20-1.el7.x86_64 and no timeout values modified in the configuration so far.

**Comment by superseb** [comment] 2017-06-19 14:02
@njordr @alexanderdalloz Would be nice to get this reproduced, can you share setup details on your MySQL servers/cluster?

**Comment by alexanderdalloz** [comment] 2017-06-19 14:38
My 2 node master-master MariaDB Cluster is based on a fully patched CentOS 7.3 x86_64 install. Separate VMs for the 2 MariaDB server installs.

```# rpm -qa | grep -i "maria"
mariadb-config-10.1.20-1.el7.x86_64
mariadb-libs-10.1.20-1.el7.x86_64
mariadb-server-10.1.20-1.el7.x86_64
mariadb-common-10.1.20-1.el7.x86_64
mariadb-10.1.20-1.el7.x86_64
mariadb-server-galera-10.1.20-1.el7.x86_64
mariadb-errmsg-10.1.20-1.el7.x86_64

# egrep -v '^#|^$' galera.cnf 
[mysqld]
binlog_format=ROW
default-storage-engine=innodb
innodb_autoinc_lock_mode=2
bind-address=0.0.0.0
wsrep_on=1
wsrep_provider=/usr/lib64/galera/libgalera_smm.so
wsrep_cluster_name="prod_cluster"
wsrep_cluster_address="gcomm://10.10.20.105"
wsrep_node_address=10.10.20.104
wsrep_slave_threads=1
wsrep_certify_nonPK=1
wsrep_max_ws_rows=131072
wsrep_max_ws_size=1073741824
wsrep_debug=0
wsrep_convert_LOCK_to_trx=0
wsrep_retry_autocommit=1
wsrep_auto_increment_control=1
wsrep_drupal_282555_workaround=0
wsrep_causal_reads=0
wsrep_notify_cmd=
wsrep_sst_method=rsync
wsrep_sst_auth=root:
```
The mariadb-server RPM (and related packages) comes from http://cbs.centos.org/koji/buildinfo?buildID=15275
There is nothing really special about this part of the setup.
To gain DB backend HA from rancher-server viewpoint the 3 rancher-server VMs do not directly address one of the MariaDB systems but talk to the DB via a local haproxy.

```#---------------------------------------------------------------------
# load balance the mariadb galera cluster
#---------------------------------------------------------------------
listen galera 172.17.0.1:3306
   balance static-rr
   mode tcp
   option tcpka
   option mysql-check user haproxy
   server node1 10.10.20.105:3306 check weight 100
   server node2 10.10.20.104:3306 check weight 10
```
The rancher-server containers are started with "--db-host 172.17.0.1 --db-port 3306".
Example logging on one of the 3 rancher-server hosts into /var/log/haproxy.log:

```Jun 19 15:53:55 localhost haproxy[11252]: 172.17.0.2:60066 [19/Jun/2017:15:52:52.885] galera galera/node1 1/1/62915 8053 cD 4/4/4/3/0 0/0
Jun 19 15:55:12 localhost haproxy[11252]: 172.17.0.2:60274 [19/Jun/2017:15:54:12.305] galera galera/node1 1/1/60079 106616 cD 4/4/4/3/0 0/0
Jun 19 15:58:55 localhost haproxy[11252]: 172.17.0.2:60814 [19/Jun/2017:15:57:52.885] galera galera/node1 1/0/62887 8053 cD 5/5/5/4/0 0/0
Jun 19 16:00:12 localhost haproxy[11252]: 172.17.0.2:32792 [19/Jun/2017:15:59:12.390] galera galera/node1 1/0/60070 106616 cD 5/5/5/4/0 0/0
Jun 19 16:01:05 localhost haproxy[11252]: 172.17.0.2:60618 [19/Jun/2017:15:56:32.900] galera galera/node1 1/1/272707 424605 cD 4/4/4/3/0 0/0
Jun 19 16:03:55 localhost haproxy[11252]: 172.17.0.2:33332 [19/Jun/2017:16:02:52.885] galera galera/node1 1/1/62896 8053 cD 5/5/5/4/0 0/0
Jun 19 16:05:12 localhost haproxy[11252]: 172.17.0.2:33544 [19/Jun/2017:16:04:12.468] galera galera/node2 1/1/60180 106616 cD 5/5/5/1/0 0/0
Jun 19 16:08:55 localhost haproxy[11252]: 172.17.0.2:34078 [19/Jun/2017:16:07:52.886] galera galera/node1 1/1/62919 8053 cD 5/5/5/4/0 0/0
Jun 19 16:10:12 localhost haproxy[11252]: 172.17.0.2:34288 [19/Jun/2017:16:09:12.655] galera galera/node1 1/1/60076 106616 cD 5/5/5/4/0 0/0
Jun 19 16:13:55 localhost haproxy[11252]: 172.17.0.2:34824 [19/Jun/2017:16:12:52.885] galera galera/node1 1/1/62905 8053 cD 5/5/5/4/0 0/0
Jun 19 16:15:12 localhost haproxy[11252]: 172.17.0.2:35034 [19/Jun/2017:16:14:12.737] galera galera/node1 1/1/60072 106616 cD 5/5/5/4/0 0/0
Jun 19 16:17:05 localhost haproxy[11252]: 172.17.0.2:57336 [19/Jun/2017:15:34:31.851] galera galera/node1 1/0/2553778 5686475 cD 4/4/4/3/0 0/0
```
Meanwhile updated to rancher-server 1.6.2 (stable) and still seeing the packets.go errors being logged:

```[mysql] 2017/06/19 14:19:12 packets.go:33: unexpected EOF
[mysql] 2017/06/19 14:19:12 packets.go:130: write tcp 172.17.0.2:35502->172.17.0.1:3306: write: broken pipe
[mysql] 2017/06/19 14:22:52 packets.go:33: unexpected EOF
[mysql] 2017/06/19 14:22:52 packets.go:130: write tcp 172.17.0.2:35682->172.17.0.1:3306: write: broken pipe
[mysql] 2017/06/19 14:24:12 packets.go:33: unexpected EOF
[mysql] 2017/06/19 14:24:12 packets.go:130: write tcp 172.17.0.2:36132->172.17.0.1:3306: write: broken pipe
[mysql] 2017/06/19 14:27:52 packets.go:33: unexpected EOF
[mysql] 2017/06/19 14:27:52 packets.go:130: write tcp 172.17.0.2:36312->172.17.0.1:3306: write: broken pipe
[mysql] 2017/06/19 14:32:52 packets.go:33: unexpected EOF
[mysql] 2017/06/19 14:32:52 packets.go:130: write tcp 172.17.0.2:36764->172.17.0.1:3306: write: broken pipe
[mysql] 2017/06/19 14:34:13 packets.go:33: unexpected EOF
[mysql] 2017/06/19 14:34:13 packets.go:130: write tcp 172.17.0.2:37390->172.17.0.1:3306: write: broken pipe
```

More details of interest?

**Comment by herbertcampelo** [comment] 2017-06-20 18:15
I have the same problem.

**Comment by BasEnem** [comment] 2017-06-21 22:31
Rancher Versions:
Server: 1.6.2
healthcheck: rancher/healthcheck:v0.3.1
ipsec: rancher/net:holderPorts: 500, 4500
network-services: rancher/metadata:v0.9.1, rancher/network-manager:v0.7.1
scheduler: rancher/scheduler:v0.8.0
kubernetes : no, using Cattle

Docker Version: Docker version 17.03.1-ce, build c6d412e

OS and where are the hosts located? (cloud, bare metal, etc):
Ubuntu 16.04.2 (Cloud, Openstack)

Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)
HA rancher with external DB (MariaDB 10.2.6, Galera 3)
Environment Type: (Cattle/Kubernetes/Swarm/Mesos)
Cattle
Steps to Reproduce:
Run rancher and wait. Command used to run rancher:
docker run -d --restart=unless-stopped -p 8080:8080 -p 9345:9345 rancher/server --db-host 192.168.66.13 --db-port 3306 --db-user cattle --db-pass gfbOwW57VrCv52u --db-name cattle --advertise-address 192.168.66.6

All kinds of weird JDBC errors: EOF's mainly.

**Comment by janeczku** [comment] 2017-06-22 22:06
@BasEnem 
You want to make sure HAProxy is configured with idle timeouts that are slightly higher than your MySQL `wait_timeout` configuration option (which defaults to 8 hours).

1. Get your MySQL idle timeout: `MariaDB [(none)]> show variables like '%wait_timeout%';`
2. Assuming it's using the default of 8 hours (28800s) update your haproxy.cfg default section like this:
```
default
    option tcpka
    timeout client 28900s
    timeout server 28900s
```

**Comment by BasEnem** [comment] 2017-06-26 08:02
We have simply followed this configuration instruction: http://galeracluster.com/documentation-webpages/haproxy.html

**Comment by alexanderdalloz** [comment] 2017-06-26 08:22
Hi janeczku,
most valuable contribution, much appreciated.
I have changed the timeout values 3 days ago and the packets.go EOF / pipe failures are gone.

**Comment by BasEnem** [comment] 2017-06-27 08:16
janeczku's solution indeed seems to solve the problem.

Adding a sample configuration for haproxy and galera maybe is a good idea, since a lot of people will be running into this problem. It took us a few days to figure this out :-(

**Comment by janeczku** [comment] 2017-06-27 12:54
^^ @aemneina

**Comment by aemneina** [comment] 2017-06-27 19:21
@njordr do you mind if we change the subject to 'supply galera db cluster config'? Is the thinking here to make this a doc bug @janeczku

**Comment by njordr** [comment] 2017-06-28 02:25
Fine to me

Thanks for sorting it out :)

**Comment by janeczku** [comment] 2017-06-28 15:14
@aemneina 
I don't know if its just a doc issue or if there is anything we should do in Cattle to detect connections in the MySQL connection pool that have become invalid due to the MySQL server being configured with very low idle timeouts (less than 5 minutes).

**Comment by alexanderdalloz** [comment] 2017-06-28 17:21
@janeczku
I feel it should be noted within the docs as a comment to adjust the values.
In a HA setup with external database using haproxy as the interface to a mysql/mariadb cluster seems to be a logical and common choice. mysql/mariadb and haproxy ship with very different default values for timeouts and tuning them to reasonable and coordinated values should be recommended.
I have set the wait_timeout and interactive_timeout to 300 (seconds) and the client and server timeouts for haproxy to 360s.

**Comment by jgreat** [comment] 2017-07-12 04:20
FWIW Azure database for MySQL seems to only allow a maximum wait_timeout setting of 240 seconds.

**Comment by deniseschannon** [comment] 2017-12-18 06:09
Merged docs to clarify.

**Closed by deniseschannon** 2017-12-18 06:09 UTC
Labels: area/database, area/documentation, kind/enhancement
