### ISSUE TITLE
External service hostname does not resolve

### ISSUE THREAD

**Issue by skaggmannen** [rancher/rancher#2705] opened 2015-11-17 14:32 UTC
I've got a problem where I've set up an external service to point to my Amazon RDS database. I link my container with this external service using the internal name "database". But trying to reach it from inside the container will result in a hostname lookup failure.

Example:

    root@4182622a3e0f:/# ping database                                              
    ping: unknown host database

This only seems to happen for external services. Normal services works just fine:

    root@913e3d406f31:/# ping event                                                 
    PING event.rancher.internal (10.42.223.126) 56(84) bytes of data.               
    64 bytes from ip-10-42-223-126.eu-west-1.compute.internal (10.42.223.126): icmp_
    seq=1 ttl=62 time=408 ms                                                        
    64 bytes from ip-10-42-223-126.eu-west-1.compute.internal (10.42.223.126): icmp_
    seq=2 ttl=62 time=0.711 ms                                                      
    64 bytes from ip-10-42-223-126.eu-west-1.compute.internal (10.42.223.126): icmp_
    seq=3 ttl=62 time=1.17 ms                                                       
    ^C                                                                              
    --- event.rancher.internal ping statistics ---                                  
    3 packets transmitted, 3 received, 0% packet loss, time 1999ms                  
    rtt min/avg/max/mdev = 0.711/136.834/408.615/192.178 ms

These are the versions I'm running:

* Rancher: v0.44.0
* Cattle: v0.107.0
* User Interface: v0.65.0
* Rancher Compose: v0.5.1

**Comment by deniseschannon** [comment] 2015-11-17 22:33
Did you activate your external service? If it's not activated, it will not work. :) 

In the next release of Rancher, you won't have to link services to be able to ping. 

#2628 is an enhancement that will no longer require linking.

**Comment by skaggmannen** [comment] 2015-11-18 10:05
Yes, the external service is marked as "Active".

I've noted however, that the UI seems to end up in a bad state when I do "Edit" on the external service. Could this be a bug?

**Comment by deniseschannon** [comment] 2015-11-18 19:55
Yes, there is a known issue with the UI and editing external services. It will be fixed in the next release. https://github.com/rancher/rancher/issues/2534

Would you be willing to try upgrading to v0.46.0 to see if you are able to ping services? With the enhancements (#2628) to internal DNS, you shouldn't see this issue anymore. 

I have been unable to reproduce your issue.

**Comment by skaggmannen** [comment] 2015-11-19 08:14
I've solved the issue now. The problem was of course on my end, I hadn't set up my route53 records properly :)

But the new DNS enhancements in v0.46.0 are nice!

**Closed** 2015-11-19 08:14 UTC
