### ISSUE TITLE
k8s 1.19 removes basic auth but it's in use by kontainer-engine

### ISSUE THREAD

**Issue by daenney** [rancher/rancher#28673] opened 2020-09-01 14:51 UTC
Kubernetes 1.19 is removing support for Basic Auth. However, it looks as though kontainer-engine is actually using it: https://github.com/rancher/kontainer-engine/blob/65780a8839e471d3842580d5d9075ae9a3b70a02/drivers/gke/gke_driver.go#L901-L909 in the GKE driver. This would appear to mean that it won't be possible to use kontainer-engine to create k8s 1.19+ clusters in GCP, as it'll fail to bootstrap its service account.

E-mail from Google:

> We are writing to let you know that upstream Kubernetes open source has removed support for basic authentication in version 1.19 (v1.19). Once Google Kubernetes Engine (GKE) upgrades your clusters to v1.19, you will no longer be able to use basic authentication. You will still be able to authenticate to GKE using other methods.
>
>What do I need to know?
>
> Kubernetes has announced that basic authentication will no longer be available starting with Kubernetes v1.19. GKE clusters will also no longer support basic authentication as they gradually upgrade to Kubernetes v1.19:
>
>    * Clusters subscribed to the rapid release channel will begin upgrades on or after January 2021
>    * Clusters subscribed to the regular release channel will begin upgrades on or after March 2021.
>    * Clusters subscribed to the stable release channel and non-release-channel clusters will be upgraded later in 2021; a reminder will be sent before these clusters are upgraded to v1.19

**Comment by hypnotortoise** [comment] 2020-09-25 09:35
This is also impacting GKE cluster edit operations in my case which are stuck in constant reconciling until I re-enable basic authentication for the cluster via GKE UI / gcloud.  

# Reproducible Test Scenario
1. Disable basic-auth as recommened via `gcloud container clusters update CLUSTER_NAME --no-enable-basic-auth`
2. In Rancher UI -> Edit Cluster (using same SA credentials as on initial cluster setup)
3. Trigger some operational change (e.g. update master cluster version)
4. Rancher will trigger the update (verified in GKE UI), but is stuck with failedSpec error-msg:
`Namespaces is forbidden: User "system:anonymous" cannot create resource "namespaces" in API group "" at the cluster scope`
5. Rancher triggers constant reconciling cluster updates which lead to unavailability of the cluster for management
6. Re-enable basic-auth via `gcloud container clusters update CLUSTER_NAME --enable-basic-auth`
7. Reconciliation stops and Rancher will recover to active state

**Comment by sadiapoddar** [comment] 2020-11-10 04:01
Reproduced the issue with 2.5.1 
repro steps.
1. Disable basic-auth as recommened via gcloud container clusters update CLUSTER_NAME --no-enable-basic-auth
2. In Rancher UI -> Edited the Cluster (using same SA credentials as on initial cluster setup)
3. Triggered the operational (e.g. update master cluster version)
Rancher will trigger the update (verified in GKE UI), but is stuck with failedSpec error-msg:
<img width="1359" alt="Screen Shot 2020-11-09 at 7 23 34 PM" src="https://user-images.githubusercontent.com/72409237/98623804-4bc27600-22c1-11eb-8f1b-912a44fa359d.png">

4. Enable the auth>gcloud container clusters update CLUSTER_NAME --enable-basic-auth --region=us-central1-f
<img width="1325" alt="Screen Shot 2020-11-09 at 7 59 23 PM" src="https://user-images.githubusercontent.com/72409237/98626339-5f241000-22c6-11eb-893a-81b4ed0e1461.png">

5. It took a while for the rancher to reconcile and restored itself to the active state

**Comment by sadiapoddar** [comment] 2020-11-12 21:11
Verified the fix with v2.5-7ef17a7a3c251d3e7d21f4a729edbcdff055e686-head
Steps used to verified.
1. Created gke cluster
2. disable the auth> gcloud container clusters update clustername --no-enable-basic-auth --region=region-name
3. Edit the cluster using the same SA value and perform master cluster update operation by updating Kubernetes verion
4. Notice some intermittent error
<img width="1260" alt="Screen Shot 2020-11-12 at 12 48 06 PM" src="https://user-images.githubusercontent.com/72409237/98996770-4a26c700-24e8-11eb-9cbc-c395a734177f.png">

5. Finally the error went away and the Kubernetes version was updated to the select version. 

<img width="1265" alt="Screen Shot 2020-11-12 at 12 56 22 PM" src="https://user-images.githubusercontent.com/72409237/98996868-73475780-24e8-11eb-818b-51b55a4a956a.png">

@thedadams 
Looks like the fix is working, not sure about the intermittent error, if it's a concern please let me.

**Comment by sowmyav27** [comment] 2020-11-12 21:13
Reopening to validate on master-head

**Comment by sadiapoddar** [comment] 2020-11-14 00:35
Verified the issue with master-head, master-5aa39182429d810be1278b294aeb396a70fe28aa-head
Steps used to verified.

1. Created gke cluster
2. disable the auth> gcloud container clusters update clustername --no-enable-basic-auth --region=region-name
3. Edit the cluster using the same SA value and perform master cluster update operation by updating the Kubernetes version
4. Kubernetes version upgrade was successful. 
After a while seeing an error message on UI that cluster health check is failing. The error message remains persistent on the cluster. 
<img width="1564" alt="Screen Shot 2020-11-13 at 2 40 46 PM" src="https://user-images.githubusercontent.com/72409237/99132932-ede9a300-25cc-11eb-8763-ef9042195dc3.png">

**Comment by cbron** [comment] 2020-11-20 01:04
@thedadams @sadiapoddar after looking into a few things, this will need to get backported to 2.4 also.

**Comment by sadiapoddar** [comment] 2020-11-20 01:09
@cbron @thedadams once you merged the fix with 2.4.x, let me know I will verify on that branch.
Thanks,
-Sadia

**Comment by sadiapoddar** [comment] 2020-12-02 05:00
Tried to reproduce with the same steps, but couldn't repro
v2.5-9ee39b9 and master-a549b47
1. Created gke cluster
2. disable the auth> gcloud container clusters update clustername --no-enable-basic-auth --region=region-name
3. Edit the cluster using the same SA value and perform master cluster update operation by updating the Kubernetes version
4. Kubernetes version upgrade was successful.
5. Noticed this error message, not the cluster authorization 
<img width="849" alt="Screen Shot 2020-12-01 at 8 00 44 PM" src="https://user-images.githubusercontent.com/72409237/100827029-9b074c80-3410-11eb-91f2-a221c6903d04.png">

Eventually, the above error message went away and the cluster became healthy.

**Comment by sadiapoddar** [comment] 2021-01-15 22:25
verified the fix on master-head, 1dbf17f and   2.5-head, be9683f
1. Created gke cluster
2. Disabled the auth> gcloud container clusters update clustername --no-enable-basic-auth --region=region-name
3. Edited the cluster using the same SA value and perform master cluster update operation by updating the Kubernetes version
4. Kubernetes version upgrade was successful.
5. Enabled back the auth and did auto-scaling cluster operation
6. Disabled the auth and created some namespaces, workload, services etc 
7. There was no authorization error. 

Closing the bug as the fix is working.

**Closed by sadiapoddar** 2021-01-15 22:25 UTC
Labels: [zube]: QA Working
