### ISSUE TITLE
Make webhook certificate auto renew ahead of expiration

### ISSUE THREAD

**Issue by maxsokolovsky** [rancher/rancher#36079] opened 2022-01-07 20:18 UTC
Related to an issue from 2.5.x.
https://github.com/rancher/rancher/issues/35068

This is track the same issue but for 2.6.4.
Rancher's webhook needs to be updated. This updated webhook must have an updated version of its dynamiclistener.

As a result, when webhook pod's TLS certificate (completely internal, stored in a secret) is close to expiration (30 days or fewer) or has already expired, the pod renews the certificate and extends its validity period.

**Comment by genexpr** [comment] 2022-01-10 22:01
# QA testing

### Root cause
The webhook's dynamiclistener did not check if webhook's certificate is about to expire, because the certificate value had not
been set properly on the dynamiclistener server listener. 
### What was fixed, or what changes have occurred
The dynamiclistener has had a commit that we cherry-picked into a new version of webhook which is to be used in a new version of Rancher. 
### Areas or cases that should be tested
- Use a new v2.6.4 cluster
- Upgrade from v2.6.3 to v2.6.4

### What areas could experience regressions?
### Testing step
#### Use a new v2.6.4 cluster
Deploy a new v2.6.4 pre-release Rancher container.
Find the secret called `cattle-webhook-tls` in the `cattle-system` namespace.
Copy the certificate contents and decode them. You can use a site like `https://certificatedecoder.dev`.
Observe that `Expires On` shows a date 10 years from today.

You need to test that the webhook pod keeps renewing the certificate if necessary (if it is 30 days or fewer until expiration). Since your current certificate will expire in 10 years, you would have to wait for 10 years minus 30 days to see it renewed before it is set to expire.
Instead, delete the certificate secret (by hand or with `kubectl delete pod -n cattle-system -l app=rancher-webhook`).

Go to the `rancher-webhook` deployment in the `cattle-system` namespace.
Add an environment variable to it called `CATTLE_NEW_SIGNED_CERT_EXPIRATION_DAYS` and set its value to 2.
Save the deployment and observe that its pod is deleted and a new one is created in its place.

Check that the certificate has been recreated. Decode its contents and observe that it is valid for 2 days.
The webhook pod checks in on its certificate expiration every 6 hours. In 6 hours, you can observe that it has
updated (not recreated) the certificate and its `Expires On` date is extended by 2 days again.

Because the certificate is now only valid for 2 days, as you specified, you will see the webhook pod try to update it, extend its validity period by 2 days. It will keep doing this because 2 days is fewer than 30 days, so webhook thinks it's time to update it ahead of expiration.

To get a 10-year certificate, update the deployment again by removing the environment variable and save.
Absence of that variable means the pod should make a cert that is valid for 10 years, the default.

#### Upgrade from v2.6.3 to v2.6.4
Now get a new v2.6.3 cluster and upgrade it to v2.6.4.
The webhook app will be upgraded in a couple of minutes. Therefore, the `rancher-webhook` deployment will also
be upgraded and its pod recreated. However, the certificate will remain the same, since it already exists, has not
expired yet, and isn't 30 days within expiration. You can verify this by checking that the cert contents have not changed at all. But the new pod will now watch it for expiration. And 30 days before expiration, it will renew the cert.

Check the image of the pod made by the `rancher-webhook` deployment, make sure it is `v0.2.4-rc3` (the number after `rc` might be different).

Run the same routine with changing the deployment's `CATTLE_NEW_SIGNED_CERT_EXPIRATION_DAYS` variable to less than 30 and observe that in 6 hours, the secret will be updated (again, not recreated). Check its expiration date and ensure it's 10 years in the future.

**Comment by cbron** [comment] 2022-01-18 18:14
Moving this back to 2.6.4 and backporting to 2.6.3-patch1

**Comment by brudnak** [comment] 2022-01-25 16:14
# My checks PASSED

## Validation Environment

| Component               | Version / Type                                     |
| ----------------------- | -------------------------------------------------- |
| Rancher version         | v2.6-4763f8de071847d4303a610b196120bf26846c4a-head |
| Rancher cluster type    | Docker                                             |
| Docker version          | 20.10.7, build 20.10.7-0ubuntu5~20.04.2            |
| Helm version            | v2.16.8-rancher1                                   |
| Downstream cluster type | N/A                                                |
| Downstream K8s version  | N/A                                                |
| Browser type            | Google Chrome                                      |
| Browser version         | 97.0.4692.99 (Official Build) (x86_64)             |

## Validation steps

1. Find the secret called cattle-webhook-tls in the cattle-system namespace
    1. Starting from the **default** Rancher homepage at `/dashboard/home`
    2. Click `hamburger menu` -> click `local` -> click `Storage` -> click `Secrets` -> set search to `All Namespaces` -> find `cattle-webhook-tls` -> click `ellipsis (three dots)` -> click `Edit Config`
    3. Copy the `Certificate` contents
    4. You can also get the certificate by just running the following command against the local cluster

```shell
kubectl get secrets -n cattle-system cattle-webhook-tls -o json | jq -r ".data.\"tls.crt\"" | base64 -d
```  

2. Copy the certificate contents and decode them. You can use a site like [https://certificatedecoder.dev](https://certificatedecoder.dev)

3. Details about the initial cert:

| Cert                            | Last 10 characters of cert | Issued on                | Expires on               |
| ------------------------------- | -------------------------- | ------------------------ | ------------------------ |
| Initial cert before any changes | B9uB2Cwuxr                 | Mon Jan 24 2022 11:43:30 | Thu Jan 22 2032 11:43:30 |


5. Delete the certificate secret
    - In the UI you can click the `ellipsis (three dots)` and select `Delete`

6. Go to the `rancher-webhook` deployment in the `cattle-system` namespace
    1. Click `hamburger menu` -> click `local` -> click `Workload` -> click `Deployments`
    2. for the `rancher-webhook` deployment listed under Namespace `cattle-system` -> right click & select `Edit Config`
    3. Under `Environment Variables` click `Add Variable` creating one with these details
        - Type: `Key/Value Pair`
        - Variable Name: `CATTLE_NEW_SIGNED_CERT_EXPIRATION_DAYS`
        - Value: `2`
    4. Click `Save`
  
7. Check that the cert has been recreated with a new 2 day expiration, using either method from `step #1`


| Cert                            | Last 10 characters of cert | Issued on                | Expires on               |
| ------------------------------- | -------------------------- | ------------------------ | ------------------------ |
| Initial cert before any changes | B9uB2Cwuxr                 | Mon Jan 24 2022 11:43:30 | Thu Jan 22 2032 11:43:30 |
| Cert after adding 2 day env var | 9VNonZ6poL                 | Mon Jan 24 2022 11:43:30 | Wed Jan 26 2022 11:49:49 |


8. Wait 6 hours then check the cert again

| Cert                            | Last 10 characters of cert | Issued on                | Expires on               |
| ------------------------------- | -------------------------- | ------------------------ | ------------------------ |
| Initial cert before any changes | B9uB2Cwuxr                 | Mon Jan 24 2022 11:43:30 | Thu Jan 22 2032 11:43:30 |
| Cert after adding 2 day env var | 9VNonZ6poL                 | Mon Jan 24 2022 11:43:30 | Wed Jan 26 2022 11:49:49 |
| After waiting 6 hours           | QZrmXkAg==                 | Mon Jan 24 2022 11:43:30 | Thu Jan 27 2022 05:49:49 |

9. To get a 10-year certificate, update the deployment again by removing the environment variable and save

### RESULT 

The cert updates after waiting 6 hours, and deleting the environment variable resets the cert back to 10 years
  
## Additional Info

#### HA Upgrade Checks

| Cert                            | Last 10 characters of cert | Issued on                | Expires on               |
| ------------------------------- | -------------------------- | ------------------------ | ------------------------ |
| Initial cert after upgrade      | sXSDef2w==                 | Mon Jan 24 2022 12:06:56 | Thu Jan 22 2032 12:06:56 |
| Cert after adding 2 day env var | vRrO9GjSJp                 | Mon Jan 24 2022 12:06:56 | Wed Jan 26 2022 13:45:30 |
| After waiting 6 hours           | krE7gvlQ==                 | Mon Jan 24 2022 12:06:56 | Thu Jan 27 2022 07:45:30 |

**Closed by brudnak** 2022-01-25 16:14 UTC
Labels: [zube]: QA Working, feature/webhook, team/area1

**Comment by maxsokolovsky** [comment] 2022-01-27 15:59
### Release Note
New and existing rancher-webhook deployments will automatically renew their TLS certificates when the expiration date is 30 days or less. See #36079.
