### ISSUE TITLE
no template "grafana.fullname" associated with template "gotpl"

### ISSUE THREAD

**Issue by MKlimuszka** [rancher/rancher#38780] opened 2022-08-30 21:16 UTC
@jouve commented on [Mon May 17 2021](https://github.com/rancher/charts/issues/1205)

upgrade to monitoring chart version 14.5.100 fails with this error :
```
---------------------------------------------------------------------
--
SUCCESS:  helm upgrade --history-max=5 --install=true  --namespace=cattle-monitoring-system --timeout=10m0s  --values=/home/shell/helm/values-rancher-monitoring-crd-14.5.100.yaml  --version=14.5.100 --wait=true rancher-monitoring-crd  /home/shell/helm/rancher-monitoring-crd-14.5.100.tgz
---------------------------------------------------------------------
helm  upgrade --history-max=5 --install=true  --namespace=cattle-monitoring-system --timeout=10m0s  --values=/home/shell/helm/values-rancher-monitoring-14.5.100.yaml  --version=14.5.100 --wait=true rancher-monitoring  /home/shell/helm/rancher-monitoring-14.5.100.tgz
Error:  UPGRADE FAILED: template:  rancher-monitoring/templates/rancher-monitoring/clusterrole.yaml:117:13:  executing  "rancher-monitoring/templates/rancher-monitoring/clusterrole.yaml" at  &lt;include "call-nested" (list . "grafana" "grafana.fullname")&gt;:  error calling include: template:  rancher-monitoring/templates/_helpers.tpl:21:4: executing "call-nested"  at &lt;include $template (dict "Chart" (dict "Name" (last $subchart))  "Values" $values "Release" $dot.Release "Capabilities"  $dot.Capabilities)&gt;: error calling include: template: no template  "grafana.fullname" associated with template "gotpl"
--
```

---

@devops-leni commented on [Fri Jun 11 2021](https://github.com/rancher/charts/issues/1205#issuecomment-859406966)

Hello,

I have the same issue with the chart version 14.5.100 but only when I want to disable the Grafana !

My values file : 
```
grafana:
  enable: false

prometheus:
  prometheusSpec:
    evaluationInterval: 1m
    retentionSize: ${prometheus_retention_size}GiB
    scrapeInterval: 1m
    replicas: ${prometheus_replicas}
    resources:
     ...

rkeControllerManager:
  enabled: true

rkeEtcd:
  enabled: true

rkeProxy:
  enabled: true

rkeScheduler:
  enabled: true
```

The error after the helm upgrade log : 
```
Error: template: rancher-monitoring/templates/rancher-monitoring/clusterrole.yaml:117:13: 
executing "rancher-monitoring/templates/rancher-monitoring/clusterrole.yaml" 
at <include "call-nested" (list . "grafana" "grafana.fullname")>: 
error calling include: template: rancher-monitoring/templates/_helpers.tpl:21:4: 
executing "call-nested" at <include $template (dict "Chart" (dict "Name" (last $subchart)) 
"Values" $values "Release" $dot.Release "Capabilities" $dot.Capabilities)>: 
error calling include: template: no template "grafana.fullname" associated with template "gotpl"
```

---

@evoicefire commented on [Wed Jun 30 2021](https://github.com/rancher/charts/issues/1205#issuecomment-871937945)

I am also having the same issue when trying to disable grafana. Same output as above.

---

@nickvth commented on [Thu Jul 08 2021](https://github.com/rancher/charts/issues/1205#issuecomment-876219587)

+1

---

@fplantinga-guida commented on [Thu Jul 08 2021](https://github.com/rancher/charts/issues/1205#issuecomment-876256535)

Experiencing the same issue. I even tried uninstalling and reinstalling. I guess the issue is related to the grafana dependency in this chart. 

---

@gelo22 commented on [Thu Oct 21 2021](https://github.com/rancher/charts/issues/1205#issuecomment-949344584)

I don't know how to make PR properly even with CONTRIBUTING.md, PR got 403, I don't know how to fork it properly.
My solution:
Clone repo, change template, deploy as local chart
 
`diff --git a/charts/rancher-monitoring/rancher-monitoring/14.5.100/templates/rancher-monitoring/clusterrole.yaml b/charts/rancher-monitoring/rancher-monitoring/14.5.100/templates/rancher-monitoring/clusterrole.yaml
index a115de7c..1a712465 100644
--- a/charts/rancher-monitoring/rancher-monitoring/14.5.100/templates/rancher-monitoring/clusterrole.yaml
+++ b/charts/rancher-monitoring/rancher-monitoring/14.5.100/templates/rancher-monitoring/clusterrole.yaml
@@ -114,8 +114,10 @@ rules:
   - "https:{{ template "kube-prometheus-stack.fullname" . }}-prometheus:{{ .Values.prometheus.service.port }}"
   - "http:{{ template "kube-prometheus-stack.fullname" . }}-alertmanager:{{ .Values.alertmanager.service.port }}"
   - "https:{{ template "kube-prometheus-stack.fullname" . }}-alertmanager:{{ .Values.alertmanager.service.port }}"
+{{- if and .Values.grafana.enabled }}
   - "http:{{ include "call-nested" (list . "grafana" "grafana.fullname") }}:{{ .Values.grafana.service.port }}"
   - "https:{{ include "call-nested" (list . "grafana" "grafana.fullname") }}:{{ .Values.grafana.service.port }}"
+{{- end }}
   verbs:
   - 'get'
 - apiGroups:
@@ -123,7 +125,9 @@ rules:
   resourceNames:
   - {{ template "kube-prometheus-stack.fullname" . }}-prometheus
   - {{ template "kube-prometheus-stack.fullname" . }}-alertmanager
+{{- if and .Values.grafana.enabled }}
   - {{ include "call-nested" (list . "grafana" "grafana.fullname") }}
+{{- end }}
   resources:
   - endpoints
`

---

@mikesarfaty commented on [Tue May 10 2022](https://github.com/rancher/charts/issues/1205#issuecomment-1122629601)

bump, issue is a year old and still present in latest version

**Comment by aiyengar2** [comment] 2022-10-18 17:02
Duplicate of https://github.com/rancher/rancher/issues/39090

**Closed by aiyengar2** 2022-10-18 17:02 UTC
Labels: kind/bug, internal, area/monitoring, area/helm3, team/area3, [zube]: Team Area 3
