### ISSUE TITLE
Convoy Gluster FS issues with rancher 1.1  and docker 1.11

### ISSUE THREAD

**Issue by fbrbovic** [rancher/rancher#5465] opened 2016-07-18 15:22 UTC
Currently gluster FS is broken in rancher 1.1 and docker 1.11. 

There have been numerous issues open regarding this but no effective solution yet. 
https://github.com/rancher/convoy/pull/134

https://forums.rancher.com/t/glusterfs-glusterfsvolume-doesnt-have-required-field-name/3417

Any idea when this will be resolved ?

**Comment by deniseschannon** [comment] 2016-07-19 03:50
Duplicate of #4411.

**Closed by deniseschannon** 2016-07-19 03:50 UTC
