### ISSUE TITLE
False Errors in external-dns with rfc2136 connector

### ISSUE THREAD

**Issue by Toonix** [rancher/rancher#6948] opened 2016-12-06 10:57 UTC
1.2.0

1.12.3

RancherOS 0.7.1

Rancher Single Node

Environment Type: Cattle

installed rancher/external-dns with rfc2136 connector.

Results: Working

but annoying False Errors:

6.12.2016 11:54:27time="2016-12-06T10:54:27Z" level=error msg="AXFR envelope error: dns: no SOA"
6.12.2016 11:54:31time="2016-12-06T10:54:31Z" level=error msg="AXFR envelope error: dns: no SOA"
6.12.2016 11:54:32time="2016-12-06T10:54:32Z" level=error msg="AXFR envelope error: dns: no SOA"
6.12.2016 11:54:32time="2016-12-06T10:54:32Z" level=error msg="AXFR envelope error: dns: no SOA"
6.12.2016 11:54:36time="2016-12-06T10:54:36Z" level=error msg="AXFR envelope error: dns: no SOA"
6.12.2016 11:54:37time="2016-12-06T10:54:37Z" level=error msg="AXFR envelope error: dns: no SOA"
6.12.2016 11:54:37time="2016-12-06T10:54:37Z" level=error msg="AXFR envelope error: dns: no SOA"
6.12.2016 11:54:41time="2016-12-06T10:54:41Z" level=error msg="AXFR envelope error: dns: no SOA"
6.12.2016 11:54:42time="2016-12-06T10:54:42Z" level=error msg="AXFR envelope error: dns: no SOA"
6.12.2016 11:54:42time="2016-12-06T10:54:42Z" level=error msg="AXFR envelope error: dns: no SOA"
6.12.2016 11:54:46time="2016-12-06T10:54:46Z" level=error msg="AXFR envelope error: dns: no SOA"
6.12.2016 11:54:47time="2016-12-06T10:54:47Z" level=error msg="AXFR envelope error: dns: no SOA"
6.12.2016 11:54:47time="2016-12-06T10:54:47Z" level=error msg="AXFR envelope error: dns: no SOA"
6.12.2016 11:54:51time="2016-12-06T10:54:51Z" level=error msg="AXFR envelope error: dns: no SOA"
6.12.2016 11:54:52time="2016-12-06T10:54:52Z" level=error msg="AXFR envelope error: dns: no SOA"
6.12.2016 11:54:52time="2016-12-06T10:54:52Z" level=error msg="AXFR envelope error: dns: no SOA"
6.12.2016 11:54:56time="2016-12-06T10:54:56Z" level=error msg="AXFR envelope error: dns: no SOA"
6.12.2016 11:54:57time="2016-12-06T10:54:57Z" level=error msg="AXFR envelope error: dns: no SOA"
6.12.2016 11:54:57time="2016-12-06T10:54:57Z" level=info msg="DNS records to add: [{powerdns.powerdns.example.com. [172.16.16.114] A 60} {gitlab-server.gitlab.example.com. [172.16.16.112] A 60} {external-dns-adminproject.example.com. [powerdns.powerdns.example.com. gitlab-server.gitlab.example.com.] TXT 60}]"
6.12.2016 11:54:57time="2016-12-06T10:54:57Z" level=info msg="Adding dns record: {powerdns.powerdns.example.com. [172.16.16.114] A 60}"
6.12.2016 11:54:57time="2016-12-06T10:54:57Z" level=info msg="Adding dns record: {gitlab-server.gitlab.example.com. [172.16.16.112] A 60}"
6.12.2016 11:54:57time="2016-12-06T10:54:57Z" level=info msg="Adding dns record: {external-dns-adminproject.example.com. [powerdns.powerdns.example.com. gitlab-server.gitlab.example.com.] TXT 60}"
6.12.2016 11:54:57time="2016-12-06T10:54:57Z" level=error msg="AXFR envelope error: dns: no SOA"
6.12.2016 11:54:57time="2016-12-06T10:54:57Z" level=error msg="AXFR envelope error: dns: no SOA"
6.12.2016 11:55:01time="2016-12-06T10:55:01Z" level=error msg="AXFR envelope error: dns: no SOA"
6.12.2016 11:55:02time="2016-12-06T10:55:02Z" level=error msg="AXFR envelope error: dns: no SOA"
6.12.2016 11:55:02time="2016-12-06T10:55:02Z" level=error msg="AXFR envelope error: dns: no SOA"
6.12.2016 11:55:06time="2016-12-06T10:55:06Z" level=error msg="AXFR envelope error: dns: no SOA"
6.12.2016 11:55:07time="2016-12-06T10:55:07Z" level=error msg="AXFR envelope error: dns: no SOA"
6.12.2016 11:55:07time="2016-12-06T10:55:07Z" level=error msg="AXFR envelope error: dns: no SOA"

**Comment by janeczku** [comment] 2017-02-06 21:04
Looks like your PowerDNS server is misbehaving and not sending the SOA record in the AXFR exchange. Did you create a SOA in the `example.com` zone?

**Comment by Toonix** [comment] 2017-02-10 08:26
yes I did

**Comment by janeczku** [comment] 2017-02-18 01:06
Not able to reproduce this. These errors indicate that your DNS server is not properly configured.

`dig SOA <Zone name for rfc2136 service> @<DNS server IP for rfc2136 service>`

**Comment by janeczku** [comment] 2017-03-01 04:17
Duplicate of #6538. Please see my comments there.

**Closed by janeczku** 2017-03-01 04:17 UTC
