### ISSUE TITLE
Automatically have agents update the host to support insecure registries or self-signed certificates

### ISSUE THREAD

**Issue by EliSnow** [rancher/rancher#2112] opened 2015-09-23 18:12 UTC
It would be nice, when adding a custom registry if there were options to have rancher automatically update all agents' hosts so they supported the insecure registry or self-signed certificate (SSC) registry. Also if an insecure registry or SSC registry were already configured on rancher and a new agent is added, it would automatically update the new agent's host.

As these would require the docker daemon to restart, the user should be warned that any running containers on the hosts will be stopped/restarted.

**Comment by deniseschannon** [comment] 2015-09-24 22:47
This is probably a duplicate of https://github.com/rancher/rancher/issues/1853 but includes insecure registries, so I'll keep it open.

**Comment by EliSnow** [comment] 2015-09-25 02:28
This is not a duplicate. This issue is about the process of adding an insecure registry or registry with SSC. #1853 is about the process of adding a new host to a server with a SSC.

**Comment by deniseschannon** [comment] 2015-09-25 02:46
@EliSnow You are correct. Sorry about that. I misinterpreted the other issue.

**Comment by ibuildthecloud** [comment] 2015-09-25 02:49
@EliSnow anything that requires configuring the daemon flags and restarting is difficult for us to support.  This is because it is distro specific.  For this feature requests would we only need to manage certs in etc/docker or are daemon flags required?

**Comment by EliSnow** [comment] 2015-09-25 03:33
@ibuildthecloud perhaps a good start would be to detect the distro and only have this feature work with agents running Rancher OS. Then,perhaps in the future, it could be expanded out to apply the proper commands to other distros.

According to the [registry docs](https://docs.docker.com/registry/insecure/), supporting an insecure registry requires updating the daemon flags, and supporting a SSC requires adding the cert to docker and possibly to the OS's cert store depending on the version of docker (it would be nice if their docks expanded on that last point). Both would require restarting the daemon.

I'm not familiar with your code base or how exactly this feature would be implemented, so forgive me if this is naive, but wouldn't this be a matter of having a mapping of distros to the commands to apply? Or perhaps what you mean by "difficult for us to support" is it would be difficult to maintain tests against a countless number of distros?

**Comment by will-chan** [comment] 2017-01-28 01:26
Closing due to inactivity.

**Closed by will-chan** 2017-01-28 01:26 UTC
Labels: area/agent, kind/feature
