### ISSUE TITLE
Failed to import cluster to Rancher UI.  (Error : failed to call leader func: settings.management.cattle.io "install-uuid" not found" )

### ISSUE THREAD

**Issue by ritheshgm** [rancher/rancher#31938] opened 2021-04-06 14:57 UTC
Hi Team, 

We are creating a RKE cluster and importing it using terraform to rancher UI, The cluster are added but we didn't see the node information in the cluster-manager, Until the nodes are visible in cluster-manager (cattle-cluster-agent is deployed in master node) fleet agent is not getting deployed in the downstream cluster. Since we are using fleet as a CD tool our deployments are not getting sync to the downstream cluster. 

However we can see the node information in cluster-explorer. 

RKE version : 1.1.5
Rancher version : 2.5.7
k8s version : 1.18.16
downstream cluster k8s version 1.18.10
Node count : 1 master and 3 worker nodes 

Error in cattle-cluster-agent 
time="2021-04-06T14:35:33Z" level=info msg="APIVersion management.cattle.io/v3 Kind Preference"
time="2021-04-06T14:35:33Z" level=info msg="APIVersion management.cattle.io/v3 Kind Feature"
time="2021-04-06T14:35:33Z" level=info msg="APIVersion metrics.k8s.io/v1beta1 Kind NodeMetrics"
time="2021-04-06T14:35:33Z" level=info msg="APIVersion metrics.k8s.io/v1beta1 Kind PodMetrics"
time="2021-04-06T14:35:37Z" level=error msg="failed to call leader func: settings.management.cattle.io \"install-uuid\" not found"
time="2021-04-06T14:35:42Z" level=info msg="Starting /v1, Kind=Pod controller"
time="2021-04-06T14:35:42Z" level=info msg="Starting catalog.cattle.io/v1, Kind=App controller"
time="2021-04-06T14:35:42Z" level=info msg="Starting catalog.cattle.io/v1, Kind=Operation controller"
time="2021-04-06T14:48:50Z" level=error msg="Error during subscribe websocket: close sent"
time="2021-04-06T14:49:18Z" level=error msg="namespaceHandler: Sync: error adding project id label to namespace err=Operation cannot be fulfilled on namespaces \"cattle-system\": the object has been modified; please apply your changes to the latest version and try again"

Also seeing install-uuid errors in rancher pod. 
Error in rancher Pod :
2021/04/06 14:41:11 [DEBUG] DesiredSet - No change(2) management.cattle.io/v3, Kind=Setting /system-default-registry for system-default-registry
06/04/2021 20:11:12 2021/04/06 14:41:12 [DEBUG] DesiredSet - No change(2) management.cattle.io/v3, Kind=Setting /install-uuid for install-uuid

![image](https://user-images.githubusercontent.com/50571179/113731483-743a8900-9716-11eb-800d-c24c2acbc2b9.png)

**Comment by vijaytrainer** [comment] 2021-04-06 14:59
+1

**Comment by BrundaBS** [comment] 2021-04-06 15:00
+1

**Comment by rlio** [comment] 2021-04-07 12:24
same problem

**Comment by difrost** [comment] 2021-04-09 11:41
Same problem here with Rancher 2.5.7 and RKE 1.2.7.

**Comment by dramich** [comment] 2021-04-09 14:10
@ritheshgm This is a duplicate of https://github.com/rancher/rancher/issues/31999, closing this issue in favor of that one.

**Closed by dramich** 2021-04-09 14:10 UTC

**Comment by odedonato** [comment] 2021-05-06 06:39
Not sure if related to #31999 but with 2.5.8 got same problem, added an existing EKS cluster, run Registration Command on EKS and on cattle-cluster-agent I've tons of:
`time="2021-05-06T06:36:30Z" level=error msg="failed to call leader func: settings.management.cattle.io \"install-uuid\" not found"`

on agent startup check if my rancher is accessible and it is.

**Comment by 631068264** [comment] 2022-03-23 10:11
I support you @odedonato I  met same error in v2.5.5
