### ISSUE TITLE
node overwrites other node? (video linked for showcase)

### ISSUE THREAD

**Issue by FinlayDaG33k** [rancher/rancher#14912] opened 2018-08-02 18:25 UTC
**Rancher versions:**
rancher/server or rancher/rancher: latest
rancher/agent or rancher/rancher-agent: 2.0.6

**Docker version: (`docker version` used)**
```
Client:
 Version:      17.03.2-ce
 API version:  1.27
 Go version:   go1.7.5
 Git commit:   f5ec1e2
 Built:        Tue Jun 27 01:35:00 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.03.2-ce
 API version:  1.27 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   f5ec1e2
 Built:        Tue Jun 27 01:35:00 2017
 OS/Arch:      linux/amd64
 Experimental: false

```

**Operating system and kernel: (`cat /etc/os-release` used)**
```
NAME="RancherOS"
VERSION=v1.4.0
ID=rancheros
ID_LIKE=
VERSION_ID=v1.4.0
PRETTY_NAME="RancherOS v1.4.0"
HOME_URL="http://rancher.com/rancher-os/"
SUPPORT_URL="https://forums.rancher.com/c/rancher-os"
BUG_REPORT_URL="https://github.com/rancher/os/issues"
BUILD_ID=

```

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
Bare-metal

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
HA rancher(?) as per [Manual Quick Start](https://rancher.com/docs/rancher/v2.x/en/quick-start-guide/deployment/quickstart-manual-setup/#1-provision-a-linux-host)

**Steps to Reproduce:**
1. Install RancherOS to disk (from ISO)
2. run `sudo docker run -d --restart=unless-stopped -p 80:80 -p 443:443 rancher/rancher`
3. Login, create password
4. Add `custom` cluster with `Kubernetes 1.10.5-rancher1-1` and `Canal`, requiring a compatible `docker` version and no cloud provider.
5. enter the command thing into two different nodes
6. bug!

**Results:**
See [this video](https://www.youtube.com/watch?v=SKpFwoXKSd4).
Sorry for doing it with a video, it was the easiest for me to explain and show the bug

**Comment by superseb** [comment] 2018-08-02 18:27
Duplicate of https://github.com/rancher/rancher/issues/13999

**Closed by superseb** 2018-08-02 18:27 UTC

**Comment by FinlayDaG33k** [comment] 2018-08-02 18:34
Did not see that one... whoops
