### ISSUE TITLE
pod-infra-container-image does not take effect when using cri-dockerd

### ISSUE THREAD

**Issue by kingsd041** [rancher/rancher#35555] opened 2021-11-17 03:58 UTC
**Rancher Server Setup**
- Rancher version: v2.6.2
- Installation option (Docker install/Helm Chart): Docker install
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc):
- Proxy/Cert Details:

**Information about the Cluster**
- Kubernetes version: v1.21.6-rancehr1-1
- Cluster Type (Local/Downstream): Custom
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider):

**Describe the bug**

**To Reproduce**
 
1. Create rke1 custom cluster
2. `Edit as YAML` set `enable_cri_dockerd: true`
3. Create a custom cluster of rke1 with the role of `all`

**Result**
After the kubelet is started, you can view the pause image used by the cluster as `k8s.gcr.io/pause:3.1` through kubelet, which proves that the kubelet parameter `--pod-infra-container-image="rancher/mirrored-pause :3.4.1"` did not take effect.

`k8s.gcr.io/pause:3.1` is actually the default value of the cri-dockerd `--pod-infra-container-image` parameter:
```
sh-5.0# /opt/rke-tools/bin/cri-dockerd -h
      --pod-infra-container-image string        The image whose network/ipc namespaces containers in each pod will use (default "k8s.gcr.io/pause:3.1")
```

Moreover, it can be seen from https://github.com/rancher/rke-tools/blob/master/entrypoint.sh#L75 that cri-dockerd does not specify the pause image

**Expected Result**

When using cri-dockerd, you can use rke default pause image `rancher/mirrored-pause:3.4.1`

**Screenshots**

**Additional context**

**Comment by snasovich** [comment] 2022-01-03 19:28
Still need to tag new version for rke-tools and put KDM updates to use newer versions of it.

**Comment by rishabhmsra** [comment] 2022-02-04 13:51
**Re-opening this issue:**

**Validated on rancher v2.6-head (fc01fff)**
- Created a single node downstream custom cluster using k8s : v1.21.9-rancher1-1. Also set this `enable_cri_dockerd: true`
- SSH into the node and found the infra container pods are using default image for pause containers:
```
$ docker ps -a | grep -i pause
6ba48c8eaac8   k8s.gcr.io/pause:3.1                                                       "/pause"                 35 minutes ago   Up 35 minutes                         k8s_POD_fleet-agent-746c5d4cdd-x2jrm_cattle-fleet-system_eba0565d-8b2e-4862-8527-19ebdd730dea_0
206aa8c43d07   k8s.gcr.io/pause:3.1                                                       "/pause"                 36 minutes ago   Up 36 minutes                         k8s_POD_kube-api-auth-fkpn5_cattle-system_500569be-5929-499e-8353-7c99cc4c5856_0
2822cc851d12   k8s.gcr.io/pause:3.1                                                       "/pause"                 36 minutes ago   Up 36 minutes                         k8s_POD_cattle-node-agent-vx42h_cattle-system_9c03aaf7-a0dd-48ec-9c3b-556c696b6a1b_0
aa64abb6e555   k8s.gcr.io/pause:3.1                                                       "/pause"                 36 minutes ago   Up 36 minutes                         k8s_POD_cattle-cluster-agent-6cc956494b-crhgn_cattle-system_e0f7814e-fafb-461a-a19c-3935ec691672_0
...
```
- Also `--pod-infra-container-image=rancher/mirrored-pause:3.4.1` is not set:
```
docker exec -it kubelet bash
# ps -ef |grep cri-dockerd | grep -v grep
root        7270    6931  1 13:01 ?        00:00:49 /opt/rke-tools/bin/cri-dockerd --network-plugin=cni --cni-conf-dir=/etc/cni/net.d --cni-bin-dir=/opt/cni/bin
```

- The issue is still active as the rke-tools version is set to v0.1.78 :

**Comment by kinarashah** [comment] 2022-03-04 16:50
Fix now available to test with the latest k8s versions (which have rke-tools v0.1.79): 
- v1.23.4-rancher1-1 
- v1.22.6-rancher1-2, 
- v1.21.9-rancher1-2, 
- v1.19.16-rancher1-4

**Comment by rishabhmsra** [comment] 2022-03-07 13:32
**Re-opening this issue as the cluster provisioning is failing for `v1.19.16-rancher1-4` k8s cluster when cri_dockerd is enabled**

Verified on rancher v2.6-head(4df2214), docker install

**Validation steps followed:**
- Provisioned 4 downstream cluster(single node), ec2 node driver using k8s version -> `v1.23.4-rancher1-1, v1.22.6-rancher1-2, 
v1.21.9-rancher1-2 and v1.19.16-rancher1-4`

- `v1.19.16-rancher1-4` k8s cluster provisioning is failing with below logs:
```
2022/03/07 13:15:56 [INFO] cluster [c-7cmq4] provisioning: Initiating Kubernetes cluster
2022/03/07 13:15:56 [ERROR] cluster [c-7cmq4] provisioning: Failed to validate cluster: Enabling cri-dockerd for cluster version [v1.19.16-rancher1-4] is not supported
2022/03/07 13:15:56 [ERROR] cluster [c-7cmq4] provisioning: Can not find RKE state file: open /var/lib/rancher/management-state/rke/rke-2340588426/cluster.rkestate: no such file or directory
2022/03/07 13:15:56 [INFO] kontainerdriver rancherkubernetesengine stopped
2022/03/07 13:15:57 [ERROR] Failed to save provisioning log for provisioning-log: <nil>
2022/03/07 13:15:57 [ERROR] error syncing 'c-7cmq4': handler cluster-provisioner-controller: Can not find RKE state file: open /var/lib/rancher/management-state/rke/rke-2340588426/cluster.rkestate: no such file or directory, requeuing
2022/03/07 13:16:27 [INFO] Provisioning cluster [c-7cmq4]
2022/03/07 13:16:27 [INFO] Creating cluster [c-7cmq4]

```
-------------------------------------------------------------------------

- On `v1.21.9-rancher1-2` cluster, SSH'ed into control plane node and the correct image is set for the infra containers:
```
docker ps -a | grep -i pause
581fb03a8a46   rancher/mirrored-pause:3.4.1                                               "/pause"                 About an hour ago   Up About an hour                         k8s_POD_fleet-agent-6cdfd7b77c-zqppc_cattle-fleet-system_83486164-7fb5-4305-b743-6511154cb924_0
7dddf14677e2   rancher/mirrored-pause:3.4.1                                               "/pause"                 About an hour ago   Up About an hour                         k8s_POD_kube-api-auth-tqjbt_cattle-system_dd00ce44-ce25-40f4-b2c8-c46885438e71_0
4794a420690c   rancher/mirrored-pause:3.4.1                                               "/pause"                 About an hour ago   Up About an hour                         k8s_POD_cattle-node-agent-pd96x_cattle-system_2013d183-6937-436f-8c85-691e5fde93b1_0
...
```
- Also --pod-infra-container-image=rancher/mirrored-pause:3.4.1 is set:
```
docker exec -it kubelet bash
root@rishabh-cri-1-21:/# ps -ef |grep cri-dockerd | grep -v grep
root        8935    8604  1 11:47 ?        00:01:22 /opt/rke-tools/bin/cri-dockerd --network-plugin=cni --cni-conf-dir=/etc/cni/net.d --cni-bin-dir=/opt/cni/bin --pod-infra-container-image=rancher/mirrored-pause:3.4.1
```
----------------------------------------------------------------
- On `v1.22.6-rancher1-2`, SSH'ed into control pane node and the correct image is set for the infra containers:
```
docker ps -a| grep -i pause
f7639f92dfe1   rancher/mirrored-pause:3.5                                                 "/pause"                 About an hour ago   Up About an hour                         k8s_POD_fleet-agent-6cdfd7b77c-zfsfx_cattle-fleet-system_1aed8332-baf0-42b5-8c5f-8271c7d7f7e6_0
242f06a0df7b   rancher/mirrored-pause:3.5                                                 "/pause"                 About an hour ago   Up About an hour                         k8s_POD_nginx-ingress-controller-cl8d6_ingress-nginx_5268f4ad-5caa-4608-affe-9ac7087dd02a_0
e181b4701e64   rancher/mirrored-pause:3.5                                                 "/pause"                 About an hour ago   Up About an hour                         k8s_POD_calico-kube-controllers-5685fbd9f7-88xqd_kube-system_a21f6244-d2f5-4f17-a38e-b8010a411620_3
...
```

```
docker exec -it kubelet bash
root@rishabh-cri-1-22:/# ps -ef |grep cri-dockerd | grep -v grep
root        8958    8625  2 11:46 ?        00:01:41 /opt/rke-tools/bin/cri-dockerd --network-plugin=cni --cni-conf-dir=/etc/cni/net.d --cni-bin-dir=/opt/cni/bin --pod-infra-container-image=rancher/mirrored-pause:3.5
```
------------------------------------------------------

- On `v1.23.4-rancher1-1` cluster, SSH'ed into control pane node and the correct image is set for the infra containers:
```
docker ps -a| grep -i pause
280b271c5bc9   rancher/mirrored-pause:3.6                                                 "/pause"                 About an hour ago   Up About an hour                         k8s_POD_nginx-ingress-controller-n4qkd_ingress-nginx_a4c2dfde-fad4-4110-806f-b870218cebe9_0
1fe3dcf34f91   rancher/mirrored-pause:3.6                                                 "/pause"                 About an hour ago   Up About an hour                         k8s_POD_fleet-agent-7bf5b687f5-scflv_cattle-fleet-system_ced3ed78-19eb-479a-84c5-b112ea8150fb_0
633eeabe1b9e   rancher/mirrored-pause:3.6                                                 "/pause"                 About an hour ago   Exited (0) About an hour ago             k8s_POD_fleet-agent-dbc5db4c9-ktxlp_cattle-fleet-system_632679da-e498-4624-91f6-058c46b6677d_0
...
```

```
docker exec -it kubelet bash
root@rishabh-cri-1-23:/# ps -ef |grep cri-dockerd | grep -v grep
root        8949    8603  1 11:44 ?        00:01:38 /opt/rke-tools/bin/cri-dockerd --network-plugin=cni --cni-conf-dir=/etc/cni/net.d --cni-bin-dir=/opt/cni/bin --pod-infra-container-image=rancher/mirrored-pause:3.6
```

**Comment by rishabhmsra** [comment] 2022-03-07 14:19
**Re-opening this as k8s `v1.19.16-rancher1-4` cluster provisioning is failing when cri_dockerd is enabled.**

Verified on rancher v2.6-head(4df2214), docker install.

**Steps followed for validation :**
- Created 4 downstream custom cluster(single node), using k8s version : `v1.23.4-rancher1-1, v1.22.6-rancher1-2, v1.21.9-rancher1-2, v1.19.16-rancher1-4`. Also set this `enable_cri_dockerd: true`

- `v1.19.16-rancher1-4` k8s cluster provisioning is failing with below logs:
```
[INFO ] Initiating Kubernetes cluster
[ERROR] Failed to validate cluster: Enabling cri-dockerd for cluster version [v1.19.16-rancher1-4] is not supported
[ERROR] Can not find RKE state file: open /var/lib/rancher/management-state/rke/rke-1502513793/cluster.rkestate: no such file or directory
```
----------------------------------------------
- On `v1.21.9-rancher1-2` cluster, SSH'ed into control plane node and correct image is used for infra containers :
```
docker ps -a | grep -i pause
4a3a2a23a6de   rancher/mirrored-pause:3.4.1                                               "/pause"                 9 minutes ago    Up 9 minutes                          k8s_POD_fleet-agent-6cdfd7b77c-v4f74_cattle-fleet-system_165b55f5-43a6-41c4-946f-fd41713519de_0
bfb05cca115f   rancher/mirrored-pause:3.4.1                                               "/pause"                 9 minutes ago    Up 9 minutes                          k8s_POD_nginx-ingress-controller-q49v7_ingress-nginx_73bd7036-bf07-49c2-b607-8e32601640a0_0
...
```
Also --pod-infra-container-image arg is set
```
$ docker exec -it kubelet bash
# ps -ef |grep cri-dockerd | grep -v grep
root        6843    6490  1 13:59 ?        00:00:14 /opt/rke-tools/bin/cri-dockerd --network-plugin=cni --cni-conf-dir=/etc/cni/net.d --cni-bin-dir=/opt/cni/bin --pod-infra-container-image=rancher/mirrored-pause:3.4.1
```
-------------------------------------------------------

- On `v1.22.6-rancher1-2,` cluster, SSH'ed into control plane node and correct image is used for infra containers :
```
$ docker ps -a | grep -i pause
cf631916fc07   rancher/mirrored-pause:3.5                                                 "/pause"                 8 minutes ago    Up 8 minutes                         k8s_POD_fleet-agent-6cdfd7b77c-6nmst_cattle-fleet-system_9fb70701-5920-43cd-80df-92e87959bd39_0
9fa5c05a0eda   rancher/mirrored-pause:3.5                                                 "/pause"                 9 minutes ago    Up 9 minutes                         k8s_POD_nginx-ingress-controller-52lfv_ingress-nginx_3ebdab45-0126-47bf-a923-91b749859821_0
...
```
Also --pod-infra-container-image arg is set
```
$ docker exec -it kubelet bash
# ps -ef |grep cri-dockerd | grep -v grep
root        6766    6425  1 14:03 ?        00:00:12 /opt/rke-tools/bin/cri-dockerd --network-plugin=cni --cni-conf-dir=/etc/cni/net.d --cni-bin-dir=/opt/cni/bin --pod-infra-container-image=rancher/mirrored-pause:3.5
...
```
---------------------------------------------------------------

On `v1.23.4-rancher1-1` cluster, SSH'ed into control plane node and correct image is used for infra containers :
```
$ docker ps -a | grep -i pause
8d824fe7b3a7   rancher/mirrored-pause:3.6                                                 "/pause"                 8 minutes ago    Up 8 minutes                          k8s_POD_fleet-agent-7bf5b687f5-56vcz_cattle-fleet-system_2c087789-0f77-4fd4-ab93-bfbab07dba7c_0
8abfcf0f7970   rancher/mirrored-pause:3.6                                                 "/pause"                 9 minutes ago    Exited (0) 8 minutes ago              k8s_POD_fleet-agent-7f86866df5-257n2_cattle-fleet-system_3fe22115-47ab-49a7-82b9-0afc100af16b_0
...
```
Also --pod-infra-container-image arg is set
```
$ docker exec -it kubelet bash
# ps -ef |grep cri-dockerd | grep -v grep
root        6783    6433  1 14:05 ?        00:00:13 /opt/rke-tools/bin/cri-dockerd --network-plugin=cni --cni-conf-dir=/etc/cni/net.d --cni-bin-dir=/opt/cni/bin --pod-infra-container-image=rancher/mirrored-pause:3.6
```

**Comment by kinarashah** [comment] 2022-03-07 17:17
@rishabhmsra Thanks for calling this out, cri-dockerd is not supported for v1.19. It got added to the list because it's one of the new versions we're releasing for new rke-tools. Should see this in the logs when provisioning v1.19, 
```
Failed to validate cluster: Enabling cri-dockerd for cluster version [v1.19.16-rancher1-4] is not supported
```

**Comment by rishabhmsra** [comment] 2022-03-08 13:52
Oh okay @kinarashah, in that case we can close the issue. As on rest of the k8s versions `v1.23.4-rancher1-1, v1.22.6-rancher1-2, v1.21.9-rancher1-2`, pod infra containers are using the image from `rancher/mirrored-pause`, please see the validations [here](https://github.com/rancher/rancher/issues/35555#issuecomment-1060736523).

**Closed** 2022-03-14 17:39 UTC
Labels: [zube]: To Test, feature/provisioned-rke1, team/area2
