### ISSUE TITLE
suggestion about the pop up NOTICE when delete a namespace that contain workloads

### ISSUE THREAD

**Issue by satomic** [rancher/rancher#22381] opened 2019-08-23 09:37 UTC
### normally
if I want to delete a workload, I can delete it on Rancher UI, here
![image](https://user-images.githubusercontent.com/9782493/63581640-1ea97b00-c5ca-11e9-8744-682793b4467a.png)
and it will pop up a notice like this to let me confirm it. that's ok, no problems.
![image](https://user-images.githubusercontent.com/9782493/63581752-53b5cd80-c5ca-11e9-92f6-571fd524cea3.png)

### **the question is**
**but if I click the `···` with a mistake, on the namespace which contains many workloads**
![image](https://user-images.githubusercontent.com/9782493/63581441-a2af3300-c5c9-11e9-99ba-8eee6e7818d5.png)
and it will also give me a notice like this, **the notice format and color is same as the notice when you wanna delete a workload absolutly**, if user do this operation tooo quick, he will do a big mistake. Although the user make up the majority of reason of this mistak, there is room for improvement of Rancher itself.
![image](https://user-images.githubusercontent.com/9782493/63581794-68926100-c5ca-11e9-8bf5-b90b05dc01c5.png)

## suggestion
maybe the pop up notice when delete a namespace can be upgrade like this, and this will give Rancher user a better using experience. reduce the probability of making mistakes
![image](https://user-images.githubusercontent.com/9782493/63582577-e6a33780-c5cb-11e9-9749-0f2c8b58b420.png)

**Comment by tfiduccia** [comment] 2019-09-09 18:59
This is a duplicate of #17619

**Closed** 2019-09-09 19:00 UTC
Labels: kind/enhancement, team/ui
