### ISSUE TITLE
Creating cluster with multiple nodes, some of the nodes remain in Active until the other nodes provision

### ISSUE THREAD

**Issue by sowmyav27** [rancher/rancher#30346] opened 2020-12-04 15:31 UTC
**What kind of request is this (question/bug/enhancement/feature request):** bug

**Steps to reproduce (least amount of steps as possible):**

- On 2.5.3
- Tested using these cluster specs

```
- 3 etcd+control and 3 worker nodes
- 3 etcd+control and 2 worker nodes
- 1 etcd + control and 4 worker nodes
```

- Provision clusters using DO node driver
- 1 node w1 will be Active while the other nodes go into Provisioning state
- w1 goes into provisioning state when the other nodes have gotten an ip address

**Result:**

**Other details that may be helpful:**
- This does not happen on 2.4.8
- 3 etcds and 1 worker node was the cluster spec, 2 etcd+control were in Active state and other nodes started provisioning

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): 2.5.3
- Installation option (single install/HA): HA/sinngle

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): Node driver DO
- Kubernetes version (use `kubectl version`):

```
1.19
```

**Comment by sowmyav27** [comment] 2020-12-04 16:53
Another use case:

**Steps to reproduce (least amount of steps as possible):**

- on 2.5.3
- Deploy a cluster - 3 etcd/control and 2 worker or 1 worker and 3 etcd/control
- All the nodes remain in active state for a minute or two(varies, does NOT happen always) and then the nodes go into Provisioning state. Few nodes still remain in Active state - issue logged - https://github.com/rancher/rancher/issues/30346 


**Note:**
This does not happen always


**Other details that may be helpful:**
Does not happen in 2.4.8

**Comment by janeczku** [comment] 2021-01-22 12:20
Reproduced in v2.5.5: When provisioning a cluster with an infrastructure provider such as DO only the first 5 nodes are provisioned right away and the remaining one are immediately stuck in "active" state until provisioning of the 5 nodes is completed.

This means that total cluster provisioning for clusters with >5 nodes is a multiple of what it was with 2.4.x.

**Comment by dnoland1** [comment] 2021-01-25 17:55
The behavior for DO might to by design due to rate limiting. Had a related issue with deleting larger DO clusters, see https://github.com/rancher/rancher/issues/27010

**Comment by janeczku** [comment] 2021-02-01 14:31
There is no attempt from Rancher to provision the remaining nodes at all, they are simply stuck in `Active` state for a long time before they ever enter the `Provisioning` state.

<img width="1249" alt="Screenshot 2021-01-22 at 12 30 35" src="https://user-images.githubusercontent.com/3813921/106471794-4e88cd80-64a2-11eb-9ffd-f4c33c03a313.png">

**Comment by superseb** [comment] 2021-02-15 09:04
@sowmyav27 @janeczku Please share the setup if you see this behavior (if possible with trace logging enabled)

**Comment by sowmyav27** [comment] 2021-02-15 12:35
@superseb DM ed with setup details

**Comment by Baaamm** [comment] 2021-03-04 21:18
We have the same issue. Upgrading rancher from 2.2.3 to 2.5.6

**Comment by dramich** [comment] 2021-05-11 15:48
QA: To test this issue attempt to create a cluster with any provider that has more than 5 nodes. Rancher was limited to only doing 5 nodes at a time vs rancher 2.4 which was limited to 50.

**Comment by thehejik** [comment] 2021-05-12 06:57
**Test report:**
* Teseted on rancher/rancher:master-head `6030ab5`
* used DO driver for deployment of 3 `worker` nodes and 3 nodes with `control plane` and `etcd` roles from Ember UI
* The deployment was successful and done at once - not in batches of 5 nodes as before

![anim](https://user-images.githubusercontent.com/12828077/117931775-e565f100-b2ff-11eb-90be-071a9bfdc905.gif)

Closing.

**Closed by thehejik** 2021-05-12 06:57 UTC
Labels: QA/XS, [zube]: QA Working, internal, kind/bug-qa
