### ISSUE TITLE
Settings Tab is blank

### ISSUE THREAD

**Issue by bscott** [rancher/rancher#3515] opened 2016-02-03 22:58 UTC
Every so often the Setting tab is completely tab.

![image](https://cloud.githubusercontent.com/assets/191290/12799939/97a2e4c6-ca86-11e5-965e-4f6ab0d041fd.png)

**Comment by vincent99** [comment] 2016-02-03 23:34
Anything in the browser console?

**Comment by bscott** [comment] 2016-02-03 23:37
I'll try and gather more info but it happens at random.

**Comment by tfiduccia** [comment] 2016-02-03 23:44
I've already entered this and showed it to you.  It happens to me as well.  First time in settings it always blank and I have to refresh the browser to get it to show up.

--
Tani

On Feb 3, 2016, at 4:34 PM, Vincent Fiduccia <notifications@github.com<mailto:notifications@github.com>> wrote:


Anything in the browser console?

-

**Comment by tfiduccia** [comment] 2016-02-04 17:25
duplicate of #3061

**Comment by vincent99** [comment] 2016-02-04 18:15
@bscott will look at #3061..

**Closed by vincent99** 2016-02-04 18:15 UTC
