### ISSUE TITLE
tcp-services-configmap and udp-services-configmap upon upgrade to k8s version using nginx-0.49.3-rancher1

### ISSUE THREAD

**Issue by snasovich** [rancher/rancher#35943] opened 2021-12-21 18:22 UTC
**Issue description:**
 Upon upgrade of a Rancher-provisioned Kubernetes cluster to a version that uses rancher/nginx-ingress-controller:nginx-0.49.3-rancher1, e.g. Kubernetes v1.20.12 or v1.19.16, the following args are absent from the nginx-ingress-controller DaemonSet and any configured tcp-services and udp-services will stop working

- --tcp-services-configmap=$(POD_NAMESPACE)/tcp-services
 - --udp-services-configmap=$(POD_NAMESPACE)/udp-services

**Business impact:**
 Any configured tcp-services and udp-services break

**Troubleshooting steps:**
 N/A

**Repro steps:**
 * Provision a Rancher v2.6.2 instance and a single node custom cluster with v1.20.11-rancher1-1 (or v1.19.13-rancher1-1)
 * Add an nginx Deployment to the default Namespace with a ClusterIP service to port 80
 * Add 8080: default/nginx:80 to the tcp-services ConfigMap in the ingress-nginx Namespace
 * Confirm access to nginx works via <node-ip>:8080
 * Upgrade to v1.20.12-rancher1-1 (or v1.19.16-rancher1-1)
 * Confirm access to nginx no longer works via <node-ip>:8080
 * Observe missing args on nginx-ingress-controller DaemonSet 

**Actual behavior:**
 tcp-services and udp-services stop working

**Expected behavior:**
tcp-services and udp-services continue to work

**Files, logs, traces:**
 N/A

**Additional notes:**
 Workaround is to set tcp-services-configmap and udp-services-configmap arguments via extra_args:

ingress:
  extra_args:
    tcp-services-configmap: $(POD_NAMESPACE)/tcp-services
    udp-services-configmap: $(POD_NAMESPACE)/udp-services

JIRA ID: SURE-3636, SURE-3696

**Comment by snasovich** [comment] 2021-12-21 18:29
Could be a regression in nginx-0.49.3-rancher1 compared to nginx-v0.48.1.go (https://github.com/rancher/kontainer-driver-metadata/blob/dev-v2.6/rke/templates/nginx-v0.49.3.go) in which case it should be a higher priority.
Scheduling for 2.6.4 to test this.

**Comment by kinarashah** [comment] 2022-01-20 21:18
**Issue:** 
This is a regression between upstream template [nginx-ingress-v0.30.0](https://github.com/kubernetes/ingress-nginx/blob/nginx-0.30.0/deploy/static/with-rbac.yaml#L35-L36) and [controller-v0.31.0](https://github.com/kubernetes/ingress-nginx/blob/controller-0.31.0/deploy/static/provider/cloud/deploy.yaml#L341). 
Best guess is the flags got removed when upstream refactored the code to maintain charts and static deploy files. 

Current default behavior for charts is the flags get passed by default, 
https://github.com/kubernetes/ingress-nginx/blob/main/charts/ingress-nginx/templates/_params.tpl#L17. 

But RKE1 uses static deploy yaml files where the flags and config maps were removed. 

**Solution** 

- [ ] Fix in KDM would be to add back the config maps and flags to nginx-ingress template. Since we do not update existing templates after they're released, this fix will be available in new templates introduced with the following Kubernetes versions: 

    ```
     1.20.15-rancher1-1
     1.21.9-rancher1-1
     1.22.6-rancher1-1
    ```

- [ ] Release note workaround for existing versions. Workaround mentioned in the issue works as expected - 

    ```
    Workaround is to set tcp-services-configmap and udp-services-configmap arguments via extra_args:

    ingress:
       extra_args:
          tcp-services-configmap: $(POD_NAMESPACE)/tcp-services
          udp-services-configmap: $(POD_NAMESPACE)/udp-services
     ```

**Comment by vivek-infracloud** [comment] 2022-02-02 15:48
### Validated on rancher version v2.6.3

**Observed following results:**

**Validation scenario 1:** k8s cluster use nginx version 0.35-rancher2
- Provision a single node custom cluster with v1.18.20-rancher1-3.
- Added an nginx Deployment to the default Namespace with a ClusterIP service to port 80
- Added 8080: default/nginx:80 to the tcp-services ConfigMap in the ingress-nginx Namespace
- Confirm access to nginx works via :8080
- Upgrade to v1.19.16-rancher1-2
- Access to nginx no longer works via :8080.
- Following arguments are missing on nginx-ingress-controller Daemonset
> -- tcp-services-configmap=$(POD_NAMESPACE)/tcp-services
    -- udp-services-configmap=$(POD_NAMESPACE)/udp-services
- Needs work around to fix the missing access to nginx via :8080.

**Validation scenario 2:** k8s cluster use nginx version 0.49.3-rancher1
- Provision a single node custom cluster with v1.19.16-rancher1-2.
- Added an nginx Deployment to the default Namespace with a ClusterIP service to port 80
- Added 8080: default/nginx:80 to the tcp-services ConfigMap in the ingress-nginx Namespace
- **Access to nginx failed via :8080**
- Added following 2 arguments in the nginx-ingress-controller DaemonSet.

> -- tcp-services-configmap=$(POD_NAMESPACE)/tcp-services
    -- udp-services-configmap=$(POD_NAMESPACE)/udp-services
- Access to nginx works via :8080
- Upgrade to v1.20.14-rancher2-2 (nginx version = 0.49.3-rancher1)
- Access to nginx still works via :8080.

**Validation scenario 3:** k8s cluster use nginx version 1.1.0-rancher1
- Provision a single node custom cluster with v1.19.16-rancher1-3.
- Added an nginx Deployment to the default Namespace with a ClusterIP service to port 80
- Added 8080: default/nginx:80 to the tcp-services ConfigMap in the ingress-nginx Namespace
- Confirm access to nginx works via :8080
- Upgrade to v1.20.14-rancher2-2 (nginx version = 1.1.0-rancher1)
- Access to nginx still works via :8080.
- No need to work around required.

**Comment by sowmyav27** [comment] 2022-02-02 21:40
Waiting on @kinarashah to add this issue to Release note to close it out.

**Comment by sowmyav27** [comment] 2022-02-02 22:06
@vivek-infracloud Can you validate this usecase

- Deploy 1.21 and 1.22 versions on. dev-v2.6 KDM on 2.6.3 and validate `nginx version = 1.1.0-rancher1` and the ConfigMap in the ingress-nginx Namespace is available.

**Comment by vivek-infracloud** [comment] 2022-02-03 14:28
### Validated on rancher version v2.6.3 and KDM pointing to dev-v2.6

**Observed following results:**

- Provision a single node custom cluster with v1.21.9-rancher1-1 and v1.22.6-rancher1-1.
- Validated the nginx version is **1.1.0-rancher1** and ConfigMap are present in the ingress-nginx namespace.
- Added an nginx Deployment to the default Namespace with a ClusterIP service to port 80
- Added 8080: default/nginx:80 to the tcp-services ConfigMap in the ingress-nginx Namespace
- **Access to nginx doesn't work via :8080**

> Modified the nginx-ingress-controller template in order for nginx access to work via :8080
> Added the `hostNetwork: true` and wait for cluster to update.

- Access to nginx works via :8080

**Comment by samkulkarni20** [comment] 2022-02-03 14:35
@kinarashah On inspection of nginx template files in KDM, I noticed that it sets `hostNetwork: true` on the nginx controller, if the `NetworkMode` is set to `hostNetwork`. @vivek-infracloud mentioned he followed the exact same process for the 1.22 & 1.21 clusters as he did to provision 1.19, 120 cluster, but still there's a difference in the final result.

**Comment by kinarashah** [comment] 2022-02-08 01:32
@samkulkarni20 Thanks for looking into it, we changed the network mode to `hostPort` intentionally for k8s >=1.21. For reference, here's the docs issue https://github.com/rancher/docs/issues/3420 and the issue for which we fixed it which has more context: https://github.com/rancher/rancher/issues/33792. So this behavior is expected and can be closed as is. 

Could we test this for dev-2.5 as well? Since the same new template was also introduced for 2.5.x as well. I created a backport issue for the validation. https://github.com/rancher/rancher/issues/36433

**Comment by vivek-infracloud** [comment] 2022-02-08 05:03
Based on Kinara's [comment](https://github.com/rancher/rancher/issues/35943#issuecomment-1032119786) the behaviour mentioned in the [comment](https://github.com/rancher/rancher/issues/35943#issuecomment-1029045500) is expected. 

Hence, closing the issue.

**Closed by vivek-infracloud** 2022-02-08 05:03 UTC
Labels: internal, area/ingress, [zube]: Working, feature/provisioned-rke1, team/area2

**Comment by yingbo-wu** [comment] 2022-02-19 01:29
RKE [v1.3.7]  v1.22.6-rancher1-1 The problem remains.

**Comment by kinarashah** [comment] 2022-02-28 19:23
@samkulkarni20 In reference to the above comment, could we test this on 1.22.6-rancher1-1 with RKE v1.3.7 and make sure it works? cc @slickwarren

**Comment by rishabhmsra** [comment] 2022-03-01 14:40
**Validated [this](https://github.com/rancher/rancher/issues/35943#issuecomment-1054586210) on `k8s 1.22.6-rancher1-1` using `RKE v1.3.7`** 
**observed following results :** 
- Provisioned a single node `v1.22.6-rancher1-1` k8s cluster using `RKE 1.3.7` 
- Imported it in rancher v2.6.3
- Validated the nginx version, it's `nginx-1.1.0-rancher1`
- Created nginx deployment (clusterip port 80) in default ns.
- Added `8080: default/nginx:80` to the tcp-services ConfigMap in the ingress-nginx Namespace
- Access to nginx via `<worker-node-public-ip>:8080` -> Did **NOT** work

**Created another `v1.22.6-rancher1-1` cluster using RKE 1.3.7 by following below steps**
- After `rke config` added `network_mode: hostNetwork`(as mentioned [here](https://github.com/rancher/rancher/issues/35943#issuecomment-1029052052)) under ingress in cluster.yml -> rke up 
- Once the cluster provisioned successfully, imported it in rancher v2.6.3
- Validated the nginx version, it's `nginx-1.1.0-rancher1`
- `hostNetwork: true` was set on the `nginx-ingress-controller` daemon set
- Created nginx deployment (clusterip port 80) in default ns.
- Added `8080: default/nginx:80` to the tcp-services ConfigMap in the ingress-nginx Namespace
- Access to nginx via `<worker-node-public-ip>:8080` -> **Working**
