### ISSUE TITLE
Logging v2 aggregator should not write to the host for rke and rke2

### ISSUE THREAD

**Issue by cbron** [rancher/rancher#31309] opened 2021-02-12 22:16 UTC
As discussed, any aggregators in the logging operator (RKE1/RKE2...) should write to a sidecar container instead of the host. This will avoid needing seLinux policies for that path on the host.

**Comment by cbron** [comment] 2021-03-12 21:08
@izaac this should be tested in coordination with the (linked above) logging charts issue/PR. They can both be tested before the RPM side is done. Lmk if you want to chat.

**Comment by izaac** [comment] 2021-03-17 19:37
An issue with Elasticsearch was found after upgrading to the latest 3.9 RC, #31731 I will use other outputs to test.

**Comment by izaac** [comment] 2021-03-17 20:34
Rancher version `v2.5-head (03/16/2021)` _868c715_
Upgrade from logging chart `3.8.201` to `3.9.002-rc01` In a cluster with Non-SELinux. Worked.

- The `rancher-logging-rke` Logging is not there after upgrade as expected only `rancher-logging` 
  - `kubectl get loggings.logging.banzaicloud.io`
- `rancher-logging-rke-aggregator` is created.
- Existing configuration is used and keeps working after upgrade.

**Comment by izaac** [comment] 2021-03-17 21:23
Rancher version `v2.5-head (03/16/2021)` _868c715_
Install of `3.9.002-rc01` In an RKE1 cluster with SELinux Docker. And the SELinux policies RPM installed. Worked.
https://github.com/rancher/rke2-selinux/releases `v0.5-testing.2`

- The `rancher-logging-rke` Logging is not there after install as expected only `rancher-logging` 
  - `kubectl get loggings.logging.banzaicloud.io`
- A `rancher-logging-rke-aggregator`DeamonSet is created to collect the RKE logs
- Existing configuration is used and keeps working after install.
Output used from the logging examples repo.

**Comment by izaac** [comment] 2021-03-18 00:53
Rancher version `v2.5-head (03/16/2021)` _868c715_
Chart version: `3.9.002-rc01`
https://github.com/rancher/rke2-selinux/releases `v0.5-testing.2`

I tried a slight variation of the scenario mentioned here: https://github.com/rancher/rancher/issues/30949#issuecomment-800549411

- HA Rancher install. (Ubuntu)
- Downstream cluster using a CentOS 7.8 AMI  (Custom cluster)
  - **With** SELinux Enforce and without docker selinux enabled option
- Wait for the cluster to come up active
- SSH into each node and set selinux enabled in docker `/etc/docker/daemon.json` with `{"selinux-enabled": true}`
- Restart Docker
- Install the SELinux RKE policies RPM from [here](https://github.com/rancher/rke2-selinux/releases) `v0.5.testing.2` for Centos 7
- Do the same with all the cluster nodes.
- Deploy the Logging chart `3.9.002-rc01` from dashboard 
  - System project selected
  - _global options below these steps_
- Check the pod logs in the `rancher-logging-rke-aggregator` DaemonSet

```yaml
global:
  cattle:
    systemDefaultRegistry: ''
  dockerRootDirectory: ''
  psp:
    enabled: true
  seLinux:
    enabled: true
  systemDefaultRegistry: ''
```


I am not seeing error in the `rancher-logging-rke-aggregator` Daemonset as previously observed with `3.8.201` but I don't see the RKE log files getting collected.


```
Fluent Bit v1.6.10

* Copyright (C) 2019-2020 The Fluent Bit Authors
* Copyright (C) 2015-2018 Treasure Data
* Fluent Bit is a CNCF sub-project under the umbrella of Fluentd
* https://fluentbit.io

[2021/03/18 00:39:15] [ info] [engine] started (pid=1)
[2021/03/18 00:39:15] [ info] [storage] version=1.0.6, initializing...
[2021/03/18 00:39:15] [ info] [storage] in-memory
[2021/03/18 00:39:15] [ info] [storage] normal synchronization mode, checksum disabled, max_chunks_up=128
[2021/03/18 00:39:15] [ info] [sp] stream processor started
```

**Comment by paynejacob** [comment] 2021-03-18 18:33
It looks like the fluenbit pod is  unable to read the /var/log 

```
❯ kubectl exec -it -n cattle-logging-system rancher-logging-rke-aggregator-2x9hj -- ls /var/lib/rancher/rke/log
ls: /var/lib/rancher/rke/log/nginx-proxy_a8327386f7d567a97d620ce2d1c3115326a63e7d4df80a2c79a7e0bfb9ca6f18.log: Permission denied
ls: /var/lib/rancher/rke/log/kube-proxy_10503cce7c070cfd4dc7afe322d9d14287149a63913bcc627d91052a6f5f9ebb.log: Permission denied
ls: /var/lib/rancher/rke/log/kubelet_3b57d9732b10e38c52df40d5f5843e0bc89b1d030bf863066852efa6ee016487.log: Permission denied
command terminated with exit code 1
```

The location of where the symbolic links resolve is mounted and readable

```
❯ kubectl exec -it -n cattle-logging-system rancher-logging-rke-aggregator-2x9hj -- ls /var/lib/docker/containers
01d264432e119d291fe61ffacfc223514ce7cbcc837d3f173e8a73fc28b2d014
070e9a3a26fb6af32d121a20b4a9c4abab6da70c52c72b6face74cb54dd850f9
0890e4241f964111c060878008d902e2e11eef62894dcfa947de399c7d5a6c5e
...
```

The pod shows the correct mounts

```
    Mounts:
      /fluent-bit/etc/fluent-bit.conf from config (rw,path="fluent-bit.conf")
      /tail-db from positiondb (rw)
      /var/lib/docker/containers/ from containers (rw)
      /var/lib/rancher/rke/log/ from indir (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from rancher-logging-rke-aggregator-token-k8b4n (ro)
Conditions:
  Type              Status
  Initialized       True
  Ready             True
  ContainersReady   True
  PodScheduled      True
Volumes:
  indir:
    Type:          HostPath (bare host directory volume)
    Path:          /var/lib/rancher/rke/log/
    HostPathType:  DirectoryOrCreate
  containers:
    Type:          HostPath (bare host directory volume)
    Path:          /var/lib/docker/containers/
    HostPathType:  DirectoryOrCreate

```

**Comment by izaac** [comment] 2021-03-18 19:20
I am Reopening #30949 for SELinux follow up

**Comment by izaac** [comment] 2021-03-18 20:31
Rancher version `v2.5-head (03/16/2021)` _868c715_
Chart version: `3.9.002-rc01`
Cluster RKE Federal on CentOS 7.8 No-SELinux k8s `v1.19.8+rke2r1`

For RKE2 the aggregator deamonset is using the fluent-bit systemd plugin but I don't think it is collecting the logs as expected.

The journald [documention](https://www.freedesktop.org/software/systemd/man/journald.conf.html) mentions in the **Storage** configuration option a couple of locations to look after logs:

>Controls where to store journal data. One of "volatile", "persistent", "auto" and "none". If "volatile", journal log data will be stored only 
>in memory, i.e. below the /run/log/journal hierarchy (which is created if needed). If "persistent", data will be stored preferably on disk, 
>i.e. below the /var/log/journal hierarchy (which is created if needed), with a fallback to /run/log/journal (which is created if needed), 
>during early boot and if the disk is not writable. "auto" behaves like "persistent" if the /var/log/journal directory exists, and "volatile" 
>otherwise (the existence of the directory controls the storage mode). "none" turns off all storage, all log data received will be dropped 
>(but forwarding to other targets, such as the console, the kernel log buffer, or a syslog socket will still work). Defaults to "auto" in the 
>default journal namespace, and "persistent" in all others.

But I don't see those paths as volumes in the DaemonSet. The only volume in the Daemonset is `config` of type ConfigMap with mount point `/fluent-bit/etc/`

Also checking the logs with `journalctl | grep rke2` and searching the output I see no matches.

Fluent-bit [docs](https://docs.fluentbit.io/manual/pipeline/inputs/systemd) also show an optional `Path` parameter for the [INPUT] configuration block.

**Comment by izaac** [comment] 2021-04-07 20:40
### RKE1 

Tests on `v2.5-head` were done here: https://github.com/rancher/rancher/issues/30949#issuecomment-814453526

### RKE2

Still not luck getting logs collected from Systemd on `v2.5-head` _93d921f_ 
Chart version: `3.9.400-rc02`
Clusters: CentOS based with SELinux  and Ubuntu without SELinux


Reopening.

**Comment by AmartC** [comment] 2021-04-08 17:06
Hello, when working with rancher-logging-3.8.201, I am able to ship over control plane logs from an RKE cluster to an HTTP endpoint setup, but it doesn't seem as if regular etcd logs are being shipped. I did check the docker container for etcd within the node and it does publish some messages but the only time I seem to be receiving log messages for etcd is when I take down a node (being done for experimental purposes to satisfy a use case).

**Comment by nickgerace** [comment] 2021-04-08 17:08
Confirmed with @AmartC and we should test for `etcd` logs in particular when we propose a fix

**Comment by cbron** [comment] 2021-04-11 17:14
Is there a PR for this now ? Needs to get in before noon on Monday.

**Comment by izaac** [comment] 2021-04-12 20:56
Opened #32063 to track `master-head - v2.6` testing
We still need RKE2 fixed on `v2.5-head` to close this issue.

**Comment by paynejacob** [comment] 2021-04-14 18:44
The custom systemd log path works however I had to turn off selinux in centos to get logs.  @cmurphy can we add read only on `/run/log/journal` for fluentbit to our policy?

**Comment by cmurphy** [comment] 2021-04-14 18:48
@paynejacob did you install the rancher-selinux RPM? It should be there https://github.com/rancher/rancher-selinux/blob/d1d63b38ea40b1d459b916e971acdee627893724/policy/centos7/rancher.te#L27-L28

**Comment by paynejacob** [comment] 2021-04-14 18:48
I did not I will test with the rpm

**Comment by izaac** [comment] 2021-04-20 15:55
Rancher version `v2.5.8-rc4`
Logging Chart version `3.9.400-rc04`

Comparing 2 RKE2 clusters with CentOS 8 nodes
- SELinux with Rancher SELinux policies RPM 
- Plain Non-SELinux

systemd logs entries are observed in the ClusterOutput in the Non-SELinux
systemd logs are **not** observed from the SELinux cluster. `systemdLogPath` was set to `/run/log/journal` after conversation with Dev.

Reopening.

**Comment by cmurphy** [comment] 2021-04-22 00:58
The latest rancher-selinux alpha release should fix the issue for CentOS 8 https://github.com/rancher/rancher-selinux/releases/tag/v0.1-alpha3.testing.1

**Comment by izaac** [comment] 2021-04-22 23:55
Rancher version `v2.5.8-rc8`
Logging chart  version `3.9.400`

I've provided feedback to @paynejacob and @cmurphy in a separate conversation on the issues I faced trying to get the journalctl logs in an ES ClusterOutput.

I tried provisioning a few different RKE2 clusters with CentOS 8.3 SELinux ON with Rancher RPM but I still didn't get the logs

Reopening.

**Comment by izaac** [comment] 2021-04-24 16:11
Rancher server: `v2.5.8-rc9` 
Logging Chart version: `3.9.400`

I refresh the charts repos from Dashboard UI but when installing if I use `Edit as YAML` the `systemdLogPath` is still `/var/log/journal`.

Even with this fix merged https://github.com/rancher/charts/pull/1146

**Comment by izaac** [comment] 2021-04-26 16:47
I've checked again today and I see `/run/log/journal` as the default. Will continue with the validation.

**Comment by izaac** [comment] 2021-04-26 19:07
Rancher version: `v2.5.8-rc9`

I am getting logs from RKE2 `/run/log/journal` but not all. I have this entry:

```json
    "hits" : [
      {
        "_index" : "izrke2t2",
        "_type" : "_doc",
        "_id" : "gotdD3kBcv3rcfdnXBH4",
        "_score" : 1.7176046,
        "_source" : {
          "_BOOT_ID" : "1e2fa68a88e74b05bec7ac9d3c677905",
          "_MACHINE_ID" : "662e34579f094f1aac9912d9465e8bee",
          "PRIORITY" : "6",
          "SYSLOG_FACILITY" : "3",
          "_UID" : "0",
          "_GID" : "0",
          "_SYSTEMD_SLICE" : "system.slice",
          "_TRANSPORT" : "stdout",
          "_CAP_EFFECTIVE" : "3fffffffff",
          "_HOSTNAME" : "izcentos83-1",
          "_STREAM_ID" : "0ceff280262e47b68186c7d001fe0538",
          "SYSLOG_IDENTIFIER" : "rke2",
          "_PID" : "14625",
          "_COMM" : "rke2",
          "_EXE" : "/usr/bin/rke2",
          "_SYSTEMD_CGROUP" : "/system.slice/rke2-server.service",
          "_SYSTEMD_UNIT" : "rke2-server.service",
          "_SYSTEMD_INVOCATION_ID" : "178bcdb6049f45f4bf128d5689c11154",
          "_SELINUX_CONTEXT" : "system_u:system_r:container_runtime_t:s0",
          "_CMDLINE" : "/usr/bin/rke2 server",
          "MESSAGE" : "time=\"2021-04-26T16:21:18Z\" level=info msg=\"Running kubelet --address=0.0.0.0 --alsologtostderr=false --anonymous-auth=false --authentication-token-webhook=true --authorization-mode=Webhook --cgroup-driver=cgroupfs --client-ca-file=/var/lib/rancher/rke2/agent/client-ca.crt --cloud-provider=external --cluster-dns=10.43.0.10 --cluster-domain=cluster.local --container-runtime-endpoint=unix:///run/k3s/containerd/containerd.sock --container-runtime=remote --containerd=/run/k3s/containerd/containerd.sock --eviction-hard=imagefs.available<5%,nodefs.available<5% --eviction-minimum-reclaim=imagefs.available=10%,nodefs.available=10% --fail-swap-on=false --healthz-bind-address=127.0.0.1 --hostname-override=izcentos83-1 --kubeconfig=/var/lib/rancher/rke2/agent/kubelet.kubeconfig --log-file-max-size=50 --log-file=/var/lib/rancher/rke2/agent/logs/kubelet.log --logtostderr=false --node-labels= --pod-manifest-path=/var/lib/rancher/rke2/agent/pod-manifests --read-only-port=0 --resolv-conf=/etc/resolv.conf --serialize-image-pulls=false --stderrthreshold=FATAL --tls-cert-file=/var/lib/rancher/rke2/agent/serving-kubelet.crt --tls-private-key-file=/var/lib/rancher/rke2/agent/serving-kubelet.key\""
        }
      }
```

But checking the logs using `journalctl  | grep "rke2\["` from the node shell 


```
Apr 26 16:22:59 izcentos83-1 rke2[14625]: W0426 16:22:59.775953   14625 warnings.go:70] apiextensions.k8s.io/v1beta1 CustomResourceDefinition is deprecated in v1.16+, unavailable in v1.22+; use apiextensions.k8s.io/v1 CustomResourceDefinition
Apr 26 16:22:59 izcentos83-1 rke2[14625]: time="2021-04-26T16:22:59Z" level=info msg="Done waiting for CRD helmchartconfigs.helm.cattle.io to become available"
Apr 26 16:22:59 izcentos83-1 rke2[14625]: time="2021-04-26T16:22:59Z" level=info msg="Failed to get existing traefik HelmChart" error="helmcharts.helm.cattle.io \"traefik\" not found"
Apr 26 16:22:59 izcentos83-1 rke2[14625]: I0426 16:22:59.928958   14625 leaderelection.go:243] attempting to acquire leader lease kube-system/rke2...
Apr 26 16:22:59 izcentos83-1 rke2[14625]: time="2021-04-26T16:22:59Z" level=info msg="Starting k3s.cattle.io/v1, Kind=Addon controller"
Apr 26 16:22:59 izcentos83-1 rke2[14625]: time="2021-04-26T16:22:59Z" level=info msg="Starting /v1, Kind=Node controller"
Apr 26 16:22:59 izcentos83-1 rke2[14625]: time="2021-04-26T16:22:59Z" level=info msg="Waiting for control-plane node izcentos83-1 startup: nodes \"izcentos83-1\" not found"
Apr 26 16:22:59 izcentos83-1 rke2[14625]: time="2021-04-26T16:22:59Z" level=info msg="Cluster dns configmap has been set successfully"
Apr 26 16:23:00 izcentos83-1 rke2[14625]: I0426 16:22:59.999797   14625 leaderelection.go:253] successfully acquired lease kube-system/rke2
Apr 26 16:23:00 izcentos83-1 rke2[14625]: time="2021-04-26T16:23:00Z" level=info msg="Starting helm.cattle.io/v1, Kind=HelmChartConfig controller"
Apr 26 16:23:00 izcentos83-1 rke2[14625]: time="2021-04-26T16:23:00Z" level=info msg="Starting helm.cattle.io/v1, Kind=HelmChart controller"
Apr 26 16:23:00 izcentos83-1 rke2[14625]: time="2021-04-26T16:23:00Z" level=info msg="Starting batch/v1, Kind=Job controller"
Apr 26 16:23:00 izcentos83-1 rke2[14625]: time="2021-04-26T16:23:00Z" level=info msg="Starting /v1, Kind=Service controller"
Apr 26 16:23:00 izcentos83-1 rke2[14625]: time="2021-04-26T16:23:00Z" level=info msg="Starting /v1, Kind=Pod controller"
Apr 26 16:23:00 izcentos83-1 rke2[14625]: time="2021-04-26T16:23:00Z" level=info msg="Starting /v1, Kind=Endpoints controller"
Apr 26 16:23:00 izcentos83-1 rke2[14625]: time="2021-04-26T16:23:00Z" level=info msg="Starting /v1, Kind=Secret controller"
Apr 26 16:23:00 izcentos83-1 rke2[14625]: time="2021-04-26T16:23:00Z" level=info msg="updating namespace: kube-system"
Apr 26 16:23:00 izcentos83-1 rke2[14625]: time="2021-04-26T16:23:00Z" level=info msg="Pod Security Policies applied successfully"
Apr 26 16:23:00 izcentos83-1 rke2[14625]: time="2021-04-26T16:23:00Z" level=info msg="Active TLS secret rke2-serving (ver=263) (count 7): map[listener.cattle.io/cn-10.43.0.1:10.43.0.1 listener.cattle.io/cn-127.0.0.1:127.0.0.1 listener.cattle.io/cn-138.197.11.176:138.197.11.176 listener.cattle.io/cn-kubernetes:kubernetes listener.cattle.io/cn-kubernetes.default:kubernetes.default listener.cattle.io/cn-kubernetes.default.svc.cluster.local:kubernetes.default.svc.cluster.local listener.cattle.io/cn-localhost:localhost listener.cattle.io/fingerprint:SHA1=53DBE04915C910253866FF89A9165C58467426E0]"
Apr 26 16:23:01 izcentos83-1 rke2[14625]: time="2021-04-26T16:23:01Z" level=info msg="labels have been set successfully on node: izcentos83-1"
Apr 26 16:23:03 izcentos83-1 rke2[14625]: time="2021-04-26T16:23:03Z" level=info msg="Stopped tunnel to 127.0.0.1:9345"
Apr 26 16:23:03 izcentos83-1 rke2[14625]: time="2021-04-26T16:23:03Z" level=info msg="Connecting to proxy" url="wss://138.197.11.176:9345/v1-rke2/connect"
Apr 26 16:23:03 izcentos83-1 rke2[14625]: time="2021-04-26T16:23:03Z" level=info msg="Proxy done" err="context canceled" url="wss://127.0.0.1:9345/v1-rke2/connect"
Apr 26 16:23:03 izcentos83-1 rke2[14625]: time="2021-04-26T16:23:03Z" level=info msg="error in remotedialer server [400]: websocket: close 1006 (abnormal closure): unexpected EOF"
Apr 26 16:23:03 izcentos83-1 rke2[14625]: time="2021-04-26T16:23:03Z" level=info msg="Handling backend connection request [izcentos83-1]"
Apr 26 16:23:04 izcentos83-1 rke2[14625]: time="2021-04-26T16:23:04Z" level=info msg="Running cloud-controller-manager with args --profiling=false"
Apr 26 16:23:04 izcentos83-1 rke2[14625]: I0426 16:23:04.330313   14625 controllermanager.go:141] Version: v1.20.6-k3s1
Apr 26 16:23:04 izcentos83-1 rke2[14625]: I0426 16:23:04.330373   14625 leaderelection.go:243] attempting to acquire leader lease kube-system/cloud-controller-manager...
Apr 26 16:23:04 izcentos83-1 rke2[14625]: I0426 16:23:04.350337   14625 leaderelection.go:253] successfully acquired lease kube-system/cloud-controller-manager
Apr 26 16:23:04 izcentos83-1 rke2[14625]: I0426 16:23:04.350623   14625 event.go:291] "Event occurred" object="kube-system/cloud-controller-manager" kind="Lease" apiVersion="coordination.k8s.io/v1" type="Normal" reason="LeaderElection" message="izcentos83-1_706c3c1a-5e70-4b01-ada0-6308fe7896b2 became leader"
Apr 26 16:23:04 izcentos83-1 rke2[14625]: I0426 16:23:04.913686   14625 node_controller.go:115] Sending events to api server.
Apr 26 16:23:04 izcentos83-1 rke2[14625]: I0426 16:23:04.913805   14625 controllermanager.go:258] Started "cloud-node"
Apr 26 16:23:04 izcentos83-1 rke2[14625]: I0426 16:23:04.913881   14625 node_controller.go:154] Waiting for informer caches to sync
Apr 26 16:23:04 izcentos83-1 rke2[14625]: I0426 16:23:04.915486   14625 node_lifecycle_controller.go:77] Sending events to api server
Apr 26 16:23:04 izcentos83-1 rke2[14625]: I0426 16:23:04.915544   14625 controllermanager.go:258] Started "cloud-node-lifecycle"
Apr 26 16:23:05 izcentos83-1 rke2[14625]: I0426 16:23:05.014143   14625 node_controller.go:390] Initializing node izcentos83-1 with cloud provider
Apr 26 16:23:05 izcentos83-1 rke2[14625]: I0426 16:23:05.021145   14625 node_controller.go:454] Successfully initialized node izcentos83-1 with cloud provider
Apr 26 16:23:05 izcentos83-1 rke2[14625]: I0426 16:23:05.021247   14625 event.go:291] "Event occurred" object="izcentos83-1" kind="Node" apiVersion="v1" type="Normal" reason="Synced" message="Node synced successfully"
```

I also tried with how the RKE2 [doc describe](https://docs.rke2.io/install/quickstart/) how to check the logs:

`journalctl -u rke2-server -f`
`journalctl -u rke2-agent -f`

**Comment by paynejacob** [comment] 2021-04-26 20:46
That is expected.  We get those logs from the container aggregator so we don't need to get them from journald as well.

**Comment by izaac** [comment] 2021-04-27 00:25
Rancher version `v2.5.8-rc9`
Logging chart version `3.9.400`
OS versions: `CentOS 7.9` and CentOS `8.3`

RPM version using the rancher-selinux repo #31888

CentOS 7
`rancher-selinux-0.1~alpha4-1.el7.noarch`

CentOS 8
`rancher-selinux-0.1~alpha4-1.el8.noarch`

`/run/log/journal` exists and is used as `Storage=auto` is the default.
`/var/log/journal` exists and is used as `Storage=persistent` is used in the `journald`configuration. `/etc/systemd/journald.conf`


Systemd/journald logs flow to the configured clusteroutput with chart option `global.seLinux.enabled = true`


Sample document observed in all four cases

- Centos8 with logs at  `/run/log/journal` 
- Centos7 with logs at `/run/log/journal` 
- Centos8 with logs at `/var/log/journal` 
- Centos7 with logs at  `/var/log/journal` 


```json
{
  "_index": "izcentos82-2",
  "_type": "_doc",
  "_id": "HoytEHkBcv3rcfdnVBrC",
  "_version": 1,
  "_score": 1,
  "_source": {
    "_BOOT_ID": "72116173f86443289f2e2bc46e0627f3",
    "PRIORITY": "6",
    "SYSLOG_FACILITY": "3",
    "_UID": "0",
    "_GID": "0",
    "_SYSTEMD_SLICE": "system.slice",
    "_TRANSPORT": "stdout",
    "_CAP_EFFECTIVE": "3fffffffff",
    "_MACHINE_ID": "ec261b3405f0f4ab91fc78b5eca967b7",
    "_HOSTNAME": "ip-172-31-35-196.us-east-2.compute.internal",
    "SYSLOG_IDENTIFIER": "rke2",
    "_COMM": "rke2",
    "_EXE": "/usr/bin/rke2",
    "_SYSTEMD_CGROUP": "/system.slice/rke2-server.service",
    "_SYSTEMD_UNIT": "rke2-server.service",
    "_SELINUX_CONTEXT": "system_u:system_r:container_runtime_t:s0",
    "_CMDLINE": "/usr/bin/rke2 server",
    "_STREAM_ID": "c975603616ed421898050d8a7296e0f1",
    "_PID": "29711",
    "_SYSTEMD_INVOCATION_ID": "9c8c43c1b7e6415a8f7578678c84b2da",
    "MESSAGE": "time=\"2021-04-27T00:13:12Z\" level=info msg=\"Shutting down /v1, Kind=Service workers\""
  },
  "fields": {
    "kubernetes.annotations.kubernetes.io/config.seen": []
  }
}
```

**Closed** 2021-04-27 00:26 UTC
Labels: QA/S, [zube]: QA Working, internal, priority/0, release-note
