### ISSUE TITLE
Enabling feature gates via Rancher API

### ISSUE THREAD

**Issue by AmitDJagtap** [rancher/rancher#14548] opened 2018-07-15 08:33 UTC
**Rancher versions:**
Component                 | Version
Rancher                       | v2.0.0
User Interface              | v2.0.41

**Infrastructure Stack versions:**
healthcheck:
 Network Provider : Canal
Kubernetes Version : v 1.10.1-rancher1

**Docker version: (`docker version`,`docker info` preferred)**

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
AWS  : RHEL : t2.medium 

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
Single Node rancher setup.
![rnodes](https://user-images.githubusercontent.com/9251806/42731997-15d14148-8836-11e8-9449-d63d720820af.png)

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**
    https://bpaste.net/show/2a44724dd99b

**Steps to Reproduce:**

-  What do I want to achieve?
   Update the rancherKubernetesEngineConfig to enable the PersistentLocalVolumes & VolumeScheduling flags. And check the status.

- Pre : I followed this guide to get 2 linux VM(RHEL) with docker 17.03.2. 
- step 1: Open Rancher2.0 UI

- step 2: View cluster in API

- step 3: Click edit

- step 4: Copied the curl command

- step 5: Modified to set following :
   - "amazonElasticContainerServiceConfig": null,
   - "azureKubernetesServiceConfig": null,
   - "googleKubernetesEngineConfig": null, 
   -  "kubeApi": {
                "podSecurityPolicy": false,
                "type": "/v3/schemas/kubeAPIService",
                "extraArgs": { "PersistentLocalVolumes": true, "VolumeScheduling": true }
            }
   -  "kubelet": {
                "failSwapOn": false,
                "type": "/v3/schemas/kubeletService",
                "extraArgs": { "PersistentLocalVolumes": true, "VolumeScheduling": true }
            }
- step 6: Performed the curl request.

**Results:**
Received the following error : 

"state":"updating",
"transitioning":"error",
"transitioningMessage":"driver change from rancherKubernetesEngine to amazonElasticContainerService not allowed",
"type":"cluster",
"uuid":"b7436a91-85b9-11e8-a5c9-0242ac110002",
"version":{
 "buildDate":"2018-04-12T14:14:26Z",
 "compiler":"gc",
 "gitCommit":"d4ab47518836c750f9949b9e0d387f20fb92260b",
 "gitTreeState":"clean",
 "gitVersion":"v1.10.1",
 "goVersion":"go1.9.3",
 "major":"1",
 "minor":"10",
 "platform":"linux/amd64",
 "type":"/v3/schemas/info"
}

**Comment by superseb** [comment] 2018-07-15 09:29
The argument is `--feature-gates` and the arguments are comma separated, the snippet you can use is

```
"services":{"etcd":{"type":"/v3/schemas/etcdService"}, "kubeApi":{"podSecurityPolicy":false, "type":"/v3/schemas/kubeAPIService", "extraArgs":{"feature-gates":"PersistentLocalVolumes=true, VolumeScheduling=true"}}, "kubeController":{"type":"/v3/schemas/kubeControllerService"}, "kubelet":{"failSwapOn":false, "type":"/v3/schemas/kubeletService", "extraArgs":{"feature-gates":"PersistentLocalVolumes=true, VolumeScheduling=true"}},
```

Regarding the error, there is an error in your JSON somewhere. You can make it easier by using the Edit function in the API and after Show Request and editing the JSON, hit Send Request.

Also, since v2.0.4 we have an easy Edit functionality in the UI (`Edit as YAML`).

Closing as this is not a bug, let me know if you need more help.

**Closed by superseb** 2018-07-15 09:29 UTC

**Comment by AmitDJagtap** [comment] 2018-07-15 09:56
What about this error .. should I set the azureKubernetesServiceConfig=null
 
```

{
"actions": { },
"baseType": "error",
"code": "InvalidFormat",
"fieldName": "azureKubernetesServiceConfig",
"links": { },
"message": "InvalidFormat 422: Value can not be converted to type azureKubernetesServiceConfig:",
"status": 422,
"type": "error"
}
```

**Comment by superseb** [comment] 2018-07-15 09:58
`amazonElasticContainerServiceConfig`, `azureKubernetesServiceConfig `, `googleKubernetesEngineConfig` all need to `null`

**Comment by AmitDJagtap** [comment] 2018-07-15 10:06
It worked thnx 👍
