### ISSUE TITLE
Unexpected end of JSON input in settings banner UI

### ISSUE THREAD

**Issue by aleksey005** [rancher/rancher#27484] opened 2020-06-08 14:27 UTC
**What kind of request is this (question/bug/enhancement/feature request):** bug

**Steps to reproduce (least amount of steps as possible):** insert incorrect code JSON in settings UI banner and UI not init

**Result:** Not access for UI login

**Other details that may be helpful:** after click button Save insert code for check correct JSON format

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): rancher/rancher:v2.4.5
- Installation option (single install/HA): single

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): Custom
- Machine type (cloud/VM/metal) and specifications (CPU/memory): VM
- Kubernetes version (use `kubectl version`): v1.17.6

- Docker version (use `docker version`): v1.19.11

```
Unexpected end of JSON input
```

**Comment by superseb** [comment] 2020-06-08 20:16
Duplicate of https://github.com/rancher/rancher/issues/26970

**Closed by superseb** 2020-06-08 20:16 UTC
