### ISSUE TITLE
Cloudwatchlogs error

### ISSUE THREAD

**Issue by lester65** [rancher/rancher#11992] opened 2018-03-06 09:29 UTC
Hi, 

I created a cluster using the stable version and integrating containers using cloudwatch logs driver, however i get the following error when enabling cloudwatch logs driver. 

(Expected state running but got error: Error response from daemon: Failed to initialize logging driver: NoCredentialProviders: no valid providers in chain. Deprecated. For verbose messaging see aws.Config.CredentialsChainVerboseErrors)

Here's the sample line below.
logging:
      driver: awslogs
      options:
        awslogs-group: mnl-qa-filesync-app-logs
        awslogs-region: us-west-1
    labels:
      io.rancher.container.pull_image: always

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v1.6.14` Cattle: `v0.183.37` UI: `v1.6.37` |
|Access|`localauth` `admin`|
|Orchestration|`Kubernetes`|
|Route|`stack.index`|

**Comment by superseb** [comment] 2018-03-06 13:08
This is the Docker daemon trying to initialize cloudwatch but failing due to missing permissions, see https://github.com/moby/moby/issues/25468 and https://github.com/moby/moby/issues/16551 for more info how to configure the correct permissions.

Closing as not a bug, let me know if you have any other questions

**Closed by superseb** 2018-03-06 13:08 UTC

**Comment by lester65** [comment] 2018-03-06 13:57
Thanks, i already figure it out. I'm using a different OS.

https://safaribooks.freepaper.me/library/view/infrastructure-as-code/9781786464910/ch10s07.html
