### ISSUE TITLE
[Logging v2] Some log files are not collected and sent to the ClusterOutput

### ISSUE THREAD

**Issue by izaac** [rancher/rancher#32074] opened 2021-04-12 23:59 UTC
**What kind of request is this:**
bug

**Steps to reproduce:**

- Provision a Windows RKE cluster (1809 was used during this test)
- 3 Windows workers
- Enable RKE logs (`values.yaml` on dashboard)
  - https://github.com/rancher/rancher/issues/32070#issue-856427183

**Result:**

Some RKE logs are getting collected right away, but other files are not, or maybe are taking long time to be processed?

**Other details that may be helpful:**

Rancher version `v2.5.8-rc2` 
Logging Chart version: `3.9.400-rc03`
Fluentd ClusterOutput.

`docker logs fluentd 2>&1 | grep -i "/var/lib/rancher/rke/log/kube-proxy_4"` return nothing from the stdout fluentd logs but there are files that match that pattern:

<img width="1368" alt="Screen Shot 2021-04-12 at 4 58 54 PM" src="https://user-images.githubusercontent.com/27659/114477048-63739280-9bb0-11eb-898c-a1d8a1fde6b6.png">

**Environment information**
- Rancher version: `v2.5.8-rc2` 
- Installation option: HA

**Comment by izaac** [comment] 2021-04-13 00:00
https://github.com/rancher/rancher/issues/32021

**Comment by cbron** [comment] 2021-04-14 17:47
Bumping to 2.6, this needs a more long term review.

**Comment by nickgerace** [comment] 2021-05-03 21:25
**Current status:** Unreproducible in backend dev environments with the following:

- Rancher 2.5.8-rc17 (using Dashboard from RC)
- Logging 3.9.4-rc08
- `global.cattle.windows.enabled=true`
- `additionalLoggingSources.rke.enabled=true`
- LTSC Cluster: 1 Ubuntu 20.04 LTS + 3 Windows 2019 LTSC nodes
- SAC Cluster: 1 Ubuntu 20.04 LTS + 3 Windows 2004 SAC nodes

**Next Steps:** Requested cluster from QA environment: 1809 SAC node based. If the issue is still unreproducible at that point, we should descope it from the next release, and close this or pursue another option.

**Comment by nickgerace** [comment] 2021-05-04 21:47
## Investigation Into QA Cluster

With a cluster provided by @izaac with 1809 nodes, this issue was also unreproducible. We see that all kubelet and kube-proxy logs appear in the dashboard, as intended, and delivered cleanly.

![Screen Shot 2021-05-04 at 2 30 25 PM](https://user-images.githubusercontent.com/39320683/117072642-c31c1400-acfe-11eb-8e8a-28106eeace7a.png)

## Side Notes

**Side Issue 1:** There was a side issue when using the `stdout` output for `fluent-bit` where the output would not work properly on RKE nodeAgents only. This was investigated and we've determined that this is likely an upstream `fluent-bit` issue. The `stdout` output for `fluent-bit` may not always work for symlinked Windows logs. The style of the mounted paths may matter (e.g. `\\` vs `\` vs `/` and `C:\` vs `/`). The only way to be sure if logs are being delivered is to use an actual endpoint via an `Output` for `ClusterOutput` CR. Fortunately, regardless of the style changes, the `forward` output does work, even though `stdout` does not always work. Since this does not affect the `forward` output to `fluentd`, this is irrelevant to our chart (unless that changes from user feedback, requests, etc.).

**Side Issue 2:** Sometimes, `fluent-bit` Windows nodeAgent pods logged that some rotated logs could not be processed. Neither backend teams nor QA teams encountered this during Logging v2 testing, which sparked an investigation. Our investigation uncovered that these errors may have been accurate, but the rotated logs were successfully ingested and delivered soon after. This most likely began due to usages of newer Windows Server AMIs since they are updated frequently. Thus, this issue is likely cosmetic or a timing issue. Regardless, this may be another upstream `fluent-bit` issue that is irrelevant to our chart.

**Context:** Upstream Windows `fluent-bit` issues are not provided. They are built in [rancher/fluent-bit-package](https://github.com/rancher/fluent-bit-package).

**Comment by nickgerace** [comment] 2021-05-04 21:48
Closing issue after confirming results with @izaac.

**Summary:** issue was unreproducible in 2004 SAC (backend created), 2019 LTSC (backend created), and 1809 SAC (QA created) clusters.

**Closed by nickgerace** 2021-05-04 21:48 UTC
Labels: [zube]: Working, area/logging, kind/bug
