### ISSUE TITLE
[monitoring v2] sometimes unable to upgrade from 9.4.202 -> 14.5.100, workaround to upgrade a 2nd time

### ISSUE THREAD

**Issue by slickwarren** [rancher/rancher#32025] opened 2021-04-09 21:56 UTC
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**

* deploy monitoring v2 v9.4.202 with default settings
* let deployment finish successfully
* upgrade to latest (currently 14.5.100-rc3)

**Result:**
Monitoring fails to upgrade

**Other details that may be helpful:**
```
  |  
-- | --
Fri, Apr 9 2021 2:49:28 pm | helm upgrade --history-max=5 --install=true --namespace=cattle-monitoring-system --timeout=10m0s --values=/home/shell/helm/values-rancher-monitoring-crd-14.5.100-rc03.yaml --version=14.5.100-rc03 --wait=true rancher-monitoring-crd /home/shell/helm/rancher-monitoring-crd-14.5.100-rc03.tgz
Fri, Apr 9 2021 2:49:29 pm | checking 5 resources for changes
Fri, Apr 9 2021 2:49:29 pm | Looks like there are no changes for ServiceAccount "rancher-monitoring-crd-manager"
Fri, Apr 9 2021 2:49:30 pm | Looks like there are no changes for ClusterRole "rancher-monitoring-crd-manager"
Fri, Apr 9 2021 2:49:30 pm | Looks like there are no changes for ClusterRoleBinding "rancher-monitoring-crd-manager"
Fri, Apr 9 2021 2:49:30 pm | beginning wait for 5 resources with timeout of 10m0s
Fri, Apr 9 2021 2:49:32 pm | Starting delete for "rancher-monitoring-crd-create" Job
Fri, Apr 9 2021 2:49:32 pm | jobs.batch "rancher-monitoring-crd-create" not found
Fri, Apr 9 2021 2:49:32 pm | creating 1 resource(s)
Fri, Apr 9 2021 2:49:32 pm | Watching for changes to Job rancher-monitoring-crd-create with timeout of 10m0s
Fri, Apr 9 2021 2:49:32 pm | Add/Modify event for rancher-monitoring-crd-create: MODIFIED
Fri, Apr 9 2021 2:49:32 pm | rancher-monitoring-crd-create: Jobs active: 1, jobs failed: 0, jobs succeeded: 0
Fri, Apr 9 2021 2:49:42 pm | Add/Modify event for rancher-monitoring-crd-create: MODIFIED
Fri, Apr 9 2021 2:49:42 pm | Starting delete for "rancher-monitoring-crd-create" Job
Fri, Apr 9 2021 2:49:43 pm | Release "rancher-monitoring-crd" has been upgraded. Happy Helming!
Fri, Apr 9 2021 2:49:43 pm | NAME: rancher-monitoring-crd
Fri, Apr 9 2021 2:49:43 pm | LAST DEPLOYED: Fri Apr 9 21:49:28 2021
Fri, Apr 9 2021 2:49:43 pm | NAMESPACE: cattle-monitoring-system
Fri, Apr 9 2021 2:49:43 pm | STATUS: deployed
Fri, Apr 9 2021 2:49:43 pm | REVISION: 2
Fri, Apr 9 2021 2:49:43 pm | TEST SUITE: None
Fri, Apr 9 2021 2:49:43 pm |  
Fri, Apr 9 2021 2:49:43 pm | ---------------------------------------------------------------------
Fri, Apr 9 2021 2:49:43 pm | SUCCESS: helm upgrade --history-max=5 --install=true --namespace=cattle-monitoring-system --timeout=10m0s --values=/home/shell/helm/values-rancher-monitoring-crd-14.5.100-rc03.yaml --version=14.5.100-rc03 --wait=true rancher-monitoring-crd /home/shell/helm/rancher-monitoring-crd-14.5.100-rc03.tgz
Fri, Apr 9 2021 2:49:43 pm | ---------------------------------------------------------------------
Fri, Apr 9 2021 2:49:43 pm | helm upgrade --history-max=5 --install=true --namespace=cattle-monitoring-system --timeout=10m0s --values=/home/shell/helm/values-rancher-monitoring-14.5.100-rc03.yaml --version=14.5.100-rc03 --wait=true rancher-monitoring /home/shell/helm/rancher-monitoring-14.5.100-rc03.tgz
Fri, Apr 9 2021 2:49:46 pm | Error: UPGRADE FAILED: error validating "": error validating data: [ValidationError(Alertmanager.spec): unknown field "alertmanagerConfigNamespaceSelector" in com.coreos.monitoring.v1.Alertmanager.spec, ValidationError(Alertmanager.spec): unknown field "alertmanagerConfigSelector" in com.coreos.monitoring.v1.Alertmanager.spec]

```

* workaround: doing a 2nd upgrade of monitoring allows the install to finish successfully
* different error, but fails at around the same stage as https://github.com/rancher/rancher/issues/32024

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): v2.5.8-rc2
- Installation option (single install/HA): HA

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): Hosted, Linode
- Machine type (cloud/VM/metal) and specifications (CPU/memory): 12vCPU (3 nodes, 4vCPU each)
- Kubernetes version (use `kubectl version`): 1.20.5

- Docker version (use `docker version`): 20.10.5

**Comment by aiyengar2** [comment] 2021-04-13 00:07
Unable to reproduce this upgrade issue in the latest Monitoring chart rc version. Moving back to test.

**Comment by aiyengar2** [comment] 2021-04-13 00:11
Based on the error:
```
Error: UPGRADE FAILED: error validating "": error validating data: [ValidationError(Alertmanager.spec): unknown field "alertmanagerConfigNamespaceSelector" in com.coreos.monitoring.v1.Alertmanager.spec, ValidationError(Alertmanager.spec): unknown field "alertmanagerConfigSelector" in com.coreos.monitoring.v1.Alertmanager.spec]
```

It seems like this was an issue with the CRD chart installation, since the field `alertmanagerConfigSelector` was introduced as part of the new CRDs from the new version of Prometheus Operator packaged into the rebase.

I would think that https://github.com/rancher/charts/pull/1093 would resolve this problem, which is why it's confusing to me that you are seeing this occur in the same rcVersion as the one that contained these changes.

**Comment by thehejik** [comment] 2021-04-13 12:42
I was unable to reproduce this issue, but I'm seeing almost always a similar issue (at the same place as this issue, ~ 9 out of 10 attempts) - Error with `missing required CRDs` during the upgrade ... https://github.com/rancher/rancher/issues/29171

```
helm upgrade --history-max=5 --install=true --namespace=cattle-monitoring-system --timeout=10m0s --values=/home/shell/helm/values-rancher-monitoring-14.5.100-rc03.yaml --version=14.5.100-rc03 --wait=true rancher-monitoring /home/shell/helm/rancher-monitoring-14.5.100-rc03.tgz
Error: UPGRADE FAILED: execution error at (rancher-monitoring/templates/validate-install-crd.yaml:18:7): Required CRDs are missing. Please install the corresponding CRD chart before installing this chart.
```

Tested on `rancher:v2.5-head` `9b0058c` and `7002499` k8s `v1.20.5` on AWS t2.large (t2.medium not sufficient) nodes in region `us-east-2` with 1x master (control-plane + etcd) and 3x worker with SLE15SP1 AMI `ami-014b2be5492b26b99`.

I was trying the following upgrade path - deployed into both default Projects and also out of project (none):
 5x ... 9.4.202 -> `14.5.100-rc05`
 5x ... 9.4.202 -> `14.5.100-rc03`

**Comment by thehejik** [comment] 2021-04-15 12:22
To be on the safe side I did try upgrade from `9.4.202` to `14.5.100-rc07` on Linux cluster with `rancher:2.5.8-rc4`. It's working ok apart the missing CRDs described above.

**Comment by slickwarren** [comment] 2021-04-23 19:59
repro'd on v2.5.8-rc9:
* on v2.5.7 install monitoring v9.4.203
* upgrade rancher
* upgrade monitoring to v14.5.100
maybe this is some sort of race condition?

```


helm upgrade --history-max=5 --install=true --namespace=cattle-monitoring-system --timeout=10m0s --values=/home/shell/helm/values-rancher-monitoring-14.5.100.yaml --version=14.5.100 --wait=true rancher-monitoring /home/shell/helm/rancher-monitoring-14.5.100.tgz
--
Fri, Apr 23 2021 12:34:08 pm | Error: UPGRADE FAILED: error validating "": error validating data: [ValidationError(Alertmanager.spec): unknown field "alertmanagerConfigNamespaceSelector" in com.coreos.monitoring.v1.Alertmanager.spec, ValidationError(Alertmanager.spec): unknown field "alertmanagerConfigSelector" in com.coreos.monitoring.v1.Alertmanager.spec]


```

**Comment by aiyengar2** [comment] 2021-05-14 22:31
### Note for QA:

The fix for this should also test https://github.com/rancher/rancher/issues/29171 as they are related issues.

**Comment by aiyengar2** [comment] 2021-06-03 16:51
Backport is tracked in https://github.com/rancher/rancher/issues/33015.

**Comment by thehejik** [comment] 2021-06-09 15:53
**Test report:**

I was unable to reproduce this issue and also issue with missing CRD #29171 anymore on - I was trying upgrade from 9.4.201, 202 and 203 on current `rancher/rancher:master-head 97ca638` with RKE1 custom cluster with k8s `v1.20.7-rancher1-1`.

The target version for the upgrade of v2 monitoring was always `14.5.101+up14.5.0`  from `dev-v2.6` chart repo `commit: cfd917c824f40d09832595ecddabb4570103aebe`

I did the upgrade 6 times and there was no trace of any of those two issues in helm logs. Only problem was broken "live" helm log due websocket issue https://github.com/rancher/rancher/issues/32657 but I was watching the logs by `kubectl logs helm-operation-9nhkl -n cattle-system -c helm -f` instead.


<details>
<summary>Helm logs for the upgrade</summary>

```
helm upgrade --history-max=5 --install=true --namespace=cattle-monitoring-system --timeout=10m0s --values=/home/shell/helm/values-rancher-monitoring-crd-14.5.101-up14.5.0.yaml --version=14.5.101+up14.5.0 --wait=true rancher-monitoring-crd /home/shell/helm/rancher-monitoring-crd-14.5.101-up14.5.0.tgz
checking 5 resources for changes
Looks like there are no changes for ServiceAccount "rancher-monitoring-crd-manager"
Looks like there are no changes for ClusterRole "rancher-monitoring-crd-manager"
Looks like there are no changes for ClusterRoleBinding "rancher-monitoring-crd-manager"
beginning wait for 5 resources with timeout of 10m0s
Starting delete for "rancher-monitoring-crd-create" Job
jobs.batch "rancher-monitoring-crd-create" not found
creating 1 resource(s)
Watching for changes to Job rancher-monitoring-crd-create with timeout of 10m0s
Add/Modify event for rancher-monitoring-crd-create: MODIFIED
rancher-monitoring-crd-create: Jobs active: 1, jobs failed: 0, jobs succeeded: 0
Add/Modify event for rancher-monitoring-crd-create: MODIFIED
Starting delete for "rancher-monitoring-crd-create" Job
Release "rancher-monitoring-crd" has been upgraded. Happy Helming!
NAME: rancher-monitoring-crd
LAST DEPLOYED: Wed Jun  9 14:36:28 2021
NAMESPACE: cattle-monitoring-system
STATUS: deployed
REVISION: 2
TEST SUITE: None

---------------------------------------------------------------------
SUCCESS: helm upgrade --history-max=5 --install=true --namespace=cattle-monitoring-system --timeout=10m0s --values=/home/shell/helm/values-rancher-monitoring-crd-14.5.101-up14.5.0.yaml --version=14.5.101+up14.5.0 --wait=true rancher-monitoring-crd /home/shell/helm/rancher-monitoring-crd-14.5.101-up14.5.0.tgz
---------------------------------------------------------------------
helm upgrade --history-max=5 --install=true --namespace=cattle-monitoring-system --timeout=10m0s --values=/home/shell/helm/values-rancher-monitoring-14.5.101-up14.5.0.yaml --version=14.5.101+up14.5.0 --wait=true rancher-monitoring /home/shell/helm/rancher-monitoring-14.5.101-up14.5.0.tgz
Starting delete for "rancher-monitoring-admission" PodSecurityPolicy
podsecuritypolicies.policy "rancher-monitoring-admission" not found
creating 1 resource(s)
Starting delete for "rancher-monitoring-admission" ServiceAccount
serviceaccounts "rancher-monitoring-admission" not found
creating 1 resource(s)
Starting delete for "rancher-monitoring-admission" ClusterRole
clusterroles.rbac.authorization.k8s.io "rancher-monitoring-admission" not found
creating 1 resource(s)
Starting delete for "rancher-monitoring-admission" ClusterRoleBinding
clusterrolebindings.rbac.authorization.k8s.io "rancher-monitoring-admission" not found
creating 1 resource(s)
Starting delete for "rancher-monitoring-admission" Role
roles.rbac.authorization.k8s.io "rancher-monitoring-admission" not found
creating 1 resource(s)
Starting delete for "rancher-monitoring-admission" RoleBinding
rolebindings.rbac.authorization.k8s.io "rancher-monitoring-admission" not found
creating 1 resource(s)
Starting delete for "rancher-monitoring-admission-create" Job
jobs.batch "rancher-monitoring-admission-create" not found
creating 1 resource(s)
Watching for changes to Job rancher-monitoring-admission-create with timeout of 10m0s
Add/Modify event for rancher-monitoring-admission-create: MODIFIED
rancher-monitoring-admission-create: Jobs active: 1, jobs failed: 0, jobs succeeded: 0
Add/Modify event for rancher-monitoring-admission-create: MODIFIED
Starting delete for "rancher-monitoring-admission" PodSecurityPolicy
Starting delete for "rancher-monitoring-admission" ServiceAccount
Starting delete for "rancher-monitoring-admission" ClusterRole
Starting delete for "rancher-monitoring-admission" ClusterRoleBinding
Starting delete for "rancher-monitoring-admission" Role
Starting delete for "rancher-monitoring-admission" RoleBinding
Starting delete for "rancher-monitoring-admission-create" Job
checking 209 resources for changes
Looks like there are no changes for Namespace "cattle-dashboards"
Looks like there are no changes for NetworkPolicy "default-allow-all"
Looks like there are no changes for NetworkPolicy "default-allow-all"
Looks like there are no changes for ServiceAccount "pushprox-kube-controller-manager-client"
Looks like there are no changes for ServiceAccount "pushprox-kube-controller-manager-proxy"
Looks like there are no changes for ServiceAccount "pushprox-kube-etcd-client"
Looks like there are no changes for ServiceAccount "pushprox-kube-etcd-proxy"
Looks like there are no changes for ServiceAccount "pushprox-kube-proxy-client"
Looks like there are no changes for ServiceAccount "pushprox-kube-proxy-proxy"
Looks like there are no changes for ServiceAccount "pushprox-kube-scheduler-client"
Looks like there are no changes for ServiceAccount "pushprox-kube-scheduler-proxy"
Looks like there are no changes for ServiceAccount "rancher-monitoring-patch-sa"
Created a new ConfigMap called "rancher-monitoring-ingress-nginx" in cattle-dashboards

Created a new ConfigMap called "rancher-default-dashboards-cluster" in cattle-dashboards

Created a new ConfigMap called "rancher-default-dashboards-home" in cattle-dashboards

Created a new ConfigMap called "rancher-default-dashboards-k8s" in cattle-dashboards

Created a new ConfigMap called "rancher-default-dashboards-nodes" in cattle-dashboards

Created a new ConfigMap called "rancher-default-dashboards-pods" in cattle-dashboards

Created a new ConfigMap called "rancher-default-dashboards-workloads" in cattle-dashboards

Looks like there are no changes for ClusterRole "pushprox-kube-controller-manager-client"
Looks like there are no changes for ClusterRole "pushprox-kube-controller-manager-proxy"
Looks like there are no changes for ClusterRole "pushprox-kube-etcd-client"
Looks like there are no changes for ClusterRole "pushprox-kube-etcd-proxy"
Looks like there are no changes for ClusterRole "pushprox-kube-proxy-client"
Looks like there are no changes for ClusterRole "pushprox-kube-proxy-proxy"
Looks like there are no changes for ClusterRole "pushprox-kube-scheduler-client"
Looks like there are no changes for ClusterRole "pushprox-kube-scheduler-proxy"
Created a new ClusterRole called "monitoring-ui-view" in 

Looks like there are no changes for ClusterRole "rancher-monitoring-patch-sa"
Looks like there are no changes for ClusterRoleBinding "pushprox-kube-controller-manager-client"
Looks like there are no changes for ClusterRoleBinding "pushprox-kube-controller-manager-proxy"
Looks like there are no changes for ClusterRoleBinding "pushprox-kube-etcd-client"
Looks like there are no changes for ClusterRoleBinding "pushprox-kube-etcd-proxy"
Looks like there are no changes for ClusterRoleBinding "pushprox-kube-proxy-client"
Looks like there are no changes for ClusterRoleBinding "pushprox-kube-proxy-proxy"
Looks like there are no changes for ClusterRoleBinding "pushprox-kube-scheduler-client"
Looks like there are no changes for ClusterRoleBinding "pushprox-kube-scheduler-proxy"
Looks like there are no changes for ClusterRoleBinding "rancher-monitoring-patch-sa"
Looks like there are no changes for Service "pushprox-kube-controller-manager-proxy"
Looks like there are no changes for Service "pushprox-kube-controller-manager-client"
Looks like there are no changes for Service "pushprox-kube-etcd-proxy"
Looks like there are no changes for Service "pushprox-kube-etcd-client"
Looks like there are no changes for Service "pushprox-kube-proxy-proxy"
Looks like there are no changes for Service "pushprox-kube-proxy-client"
Looks like there are no changes for Service "pushprox-kube-scheduler-proxy"
Looks like there are no changes for Service "pushprox-kube-scheduler-client"
Created a new Service called "rancher-monitoring-ingress-nginx" in ingress-nginx

Created a new PrometheusRule called "rancher-monitoring-prometheus-operator" in cattle-monitoring-system

Created a new ServiceMonitor called "rancher-monitoring-ingress-nginx" in ingress-nginx

Deleting "rancher-monitoring-home" in cattle-dashboards...
Deleting "rancher-monitoring-kube-prometheus" in cattle-monitoring-system...
beginning wait for 209 resources with timeout of 10m0s
DaemonSet is not ready: cattle-monitoring-system/rancher-monitoring-prometheus-node-exporter. 3 out of 6 expected pods have been scheduled
DaemonSet is not ready: cattle-monitoring-system/rancher-monitoring-prometheus-node-exporter. 3 out of 6 expected pods have been scheduled
DaemonSet is not ready: cattle-monitoring-system/rancher-monitoring-prometheus-node-exporter. 3 out of 6 expected pods have been scheduled
DaemonSet is not ready: cattle-monitoring-system/rancher-monitoring-prometheus-node-exporter. 3 out of 6 expected pods have been scheduled
DaemonSet is not ready: cattle-monitoring-system/rancher-monitoring-prometheus-node-exporter. 4 out of 6 expected pods have been scheduled
DaemonSet is not ready: cattle-monitoring-system/rancher-monitoring-prometheus-node-exporter. 4 out of 6 expected pods have been scheduled
DaemonSet is not ready: cattle-monitoring-system/rancher-monitoring-prometheus-node-exporter. 4 out of 6 expected pods have been scheduled
DaemonSet is not ready: cattle-monitoring-system/rancher-monitoring-prometheus-node-exporter. 4 out of 6 expected pods have been scheduled
DaemonSet is not ready: cattle-monitoring-system/rancher-monitoring-prometheus-node-exporter. 4 out of 6 expected pods have been scheduled
DaemonSet is not ready: cattle-monitoring-system/rancher-monitoring-prometheus-node-exporter. 5 out of 6 expected pods have been scheduled
DaemonSet is not ready: cattle-monitoring-system/rancher-monitoring-prometheus-node-exporter. 5 out of 6 expected pods have been scheduled
DaemonSet is not ready: cattle-monitoring-system/pushprox-kube-proxy-client. 5 out of 6 expected pods have been scheduled
Starting delete for "rancher-monitoring-admission" PodSecurityPolicy
podsecuritypolicies.policy "rancher-monitoring-admission" not found
creating 1 resource(s)
Starting delete for "rancher-monitoring-admission" ServiceAccount
serviceaccounts "rancher-monitoring-admission" not found
creating 1 resource(s)
Starting delete for "rancher-monitoring-admission" ClusterRole
clusterroles.rbac.authorization.k8s.io "rancher-monitoring-admission" not found
creating 1 resource(s)
Starting delete for "rancher-monitoring-admission" ClusterRoleBinding
clusterrolebindings.rbac.authorization.k8s.io "rancher-monitoring-admission" not found
creating 1 resource(s)
Starting delete for "rancher-monitoring-admission" Role
roles.rbac.authorization.k8s.io "rancher-monitoring-admission" not found
creating 1 resource(s)
Starting delete for "rancher-monitoring-admission" RoleBinding
rolebindings.rbac.authorization.k8s.io "rancher-monitoring-admission" not found
creating 1 resource(s)
Starting delete for "rancher-monitoring-admission-patch" Job
jobs.batch "rancher-monitoring-admission-patch" not found
creating 1 resource(s)
Watching for changes to Job rancher-monitoring-admission-patch with timeout of 10m0s
Add/Modify event for rancher-monitoring-admission-patch: MODIFIED
rancher-monitoring-admission-patch: Jobs active: 1, jobs failed: 0, jobs succeeded: 0
Add/Modify event for rancher-monitoring-admission-patch: MODIFIED
Starting delete for "rancher-monitoring-patch-sa" Job
jobs.batch "rancher-monitoring-patch-sa" not found
creating 1 resource(s)
Watching for changes to Job rancher-monitoring-patch-sa with timeout of 10m0s
Add/Modify event for rancher-monitoring-patch-sa: MODIFIED
rancher-monitoring-patch-sa: Jobs active: 1, jobs failed: 0, jobs succeeded: 0
Add/Modify event for rancher-monitoring-patch-sa: MODIFIED
Starting delete for "rancher-monitoring-admission" PodSecurityPolicy
Starting delete for "rancher-monitoring-admission" ServiceAccount
Starting delete for "rancher-monitoring-admission" ClusterRole
Starting delete for "rancher-monitoring-admission" ClusterRoleBinding
Starting delete for "rancher-monitoring-admission" Role
Starting delete for "rancher-monitoring-admission" RoleBinding
Starting delete for "rancher-monitoring-admission-patch" Job
Starting delete for "rancher-monitoring-patch-sa" Job
Release "rancher-monitoring" has been upgraded. Happy Helming!
NAME: rancher-monitoring
LAST DEPLOYED: Wed Jun  9 14:36:51 2021
NAMESPACE: cattle-monitoring-system
STATUS: deployed
REVISION: 2
NOTES:
rancher-monitoring has been installed. Check its status by running:
  kubectl --namespace cattle-monitoring-system get pods -l "release=rancher-monitoring"

Visit https://github.com/prometheus-operator/kube-prometheus for instructions on how to create & configure Alertmanager and Prometheus instances using the Operator.

---------------------------------------------------------------------
SUCCESS: helm upgrade --history-max=5 --install=true --namespace=cattle-monitoring-system --timeout=10m0s --values=/home/shell/helm/values-rancher-monitoring-14.5.101-up14.5.0.yaml --version=14.5.101+up14.5.0 --wait=true rancher-monitoring /home/shell/helm/rancher-monitoring-14.5.101-up14.5.0.tgz
---------------------------------------------------------------------
```

</details>

Close.

**Closed by thehejik** 2021-06-09 15:53 UTC
Labels: [zube]: QA Working, kind/bug-qa
