### ISSUE TITLE
rancher2.6.5 + (v1.23.6+rke2r2) open View Logs failure

### ISSUE THREAD

**Issue by yl-yue** [rancher/rancher#37831] opened 2022-05-26 02:28 UTC
**Rancher Server Setup**
- Rancher version: 2.6.5
- Installation option (Docker install/Helm Chart): Docker install
   - If Helm Chart, Kubernetes Cluster and version: RKE2

**Information about the Cluster**
- Kubernetes version: v1.23.6+rke2r2
- Cluster Type (Local/Downstream): Local
   - If downstream, what type of cluster?: Custom

**User Information**
- What is the role of the user logged in? : Admin

**Describe the bug**
After clicking the View Logs button, the window keeps loading and does not display properly
![image](https://user-images.githubusercontent.com/39790401/170214242-5319dc93-c0d3-42e5-925f-613d094690c3.png)

Click the Execute Shell button to successfully open the correct view
![image](https://user-images.githubusercontent.com/39790401/170214893-34baf66f-4c5a-410c-94b7-36f12f70b0e5.png)

**To Reproduce**
Open multiple pod logs frequently and repeatedly

**Result**
The `View Logs` window is not loading correctly

**Expected Result**
Load the `View Logs` window correctly
![image](https://user-images.githubusercontent.com/39790401/170401628-e811e881-219b-44ce-bd3c-9c234b2a3db9.png)

**Additional context**
> 神奇的是当出现不能正确加载`View Logs`窗口后，这个账号就会一直不能再正确加载了，只有删除这个账号重新创建一个新的，用这个新的账号登录，便又可以在Rancher UI中查看`logs`了。
而且这个新的账号，可能会在一段时间后，或者很快就又不能查看`pod logs`。
我猜想是否是多窗口原因造成的，我找遍了Rancher、集群、`dashboard-shell`等相关日志，但未找到更多有效的错误信息，大致相关错误应该与 websocket id有关。
我也尝试切换了很多浏览器与清空缓存等方案，都不能解决此问题，只能通过重新创建一个新的账号来临时解决。

If the View Logs window does not load properly, the account will not load properly. Delete the account and create a new one. Log in with the new account and you can View Logs in the Rancher UI again.
And this new account may not be able to view 'POD Logs' again after some time, or soon.
I guess it's because of multiple Windows. I searched Rancher, cluster, 'dashboard-shell' and other related logs, but I didn't find more valid error information. Roughly, the error should be related to websocket ID.
I tried many solutions such as switching browsers and clearing the cache, but none of them could solve this problem. I had to create a new account to solve it temporarily.

**Comment by ktj1312** [comment] 2022-05-26 04:58
Seems like a duplicate of : 
- https://github.com/rancher/rancher/issues/37819

You can check the log without deleting the user account using the method below until it is resolved.
[https://github.com/rancher/dashboard/issues/6009](https://github.com/rancher/dashboard/issues/6009#issuecomment-1138013369)

**Comment by jazZcarabazZ** [comment] 2022-05-26 09:05
Hi all, the same behavior as @yl-yue has met with logs..

**Comment by rak-phillip** [comment] 2022-05-27 16:30
@yl-yue thanks for raising this issue and helping to make Rancher better 😁 

It looks like we have several reports for this, so I'm going to close this as a duplicate of #5984 to help us better track and test in a single place. Feel free to reopen this issue if you feel it shouldn't be closed. Otherwise, follow up in #5984 if there's more that needs to be added.

**Closed by rak-phillip** 2022-05-27 16:30 UTC
