### ISSUE TITLE
[feature request] Scale by multiples resource definition

### ISSUE THREAD

**Issue by cusspvz** [rancher/rancher#3379] opened 2016-01-22 00:28 UTC
By default, we can only scale up and down one by one. What if there was a rule where you could set how many times a service must scale (scale by multiples of *n*)?

Imagine a use scenario where you would need to deploy an auto-sharding redis cluster with a 2 replica. If I configure them as a Sidekick, I suppose they're gonna be on the same host, right? In fact that won't really work because inspite the replicas would be on the same host, you couldn't target them because they're sidekicks of a service.

So, on that use case, If we could have a multiple scale definition of 3 (1 Master and 2 Slaves, inspite it won't matter here :D ), scale possibilities would be (3, 6, 9, 12 and so on), which would allow users to automatically set masters and slaves (we already have some features proposals on redis which will simplify cluster scalling).

Would this idea be a nice candidate for a feature request or not at all? :)

**Comment by demarant** [comment] 2016-01-22 09:12
I have a similar need. I want like to say "make sure this service has at least a scale of 2 for each host", so it will be always a multiple of 2. This is not possible right now. And when i scale the service to 2, it will be actually be 4 containers, 2 on each host, very balanced and desired from a HA perspective.
I guess it will also solve the rebalancing use case described here https://github.com/rancher/rancher/issues/2558

**Comment by vincent99** [comment] 2016-01-22 20:13
Duplicate of https://github.com/rancher/rancher/issues/2590, though the discussion got somewhat sidetracked in there.

**Closed by vincent99** 2016-01-22 20:13 UTC
