### ISSUE TITLE
HA airgap - RKE brings extra line in the rancher-image.txt 

### ISSUE THREAD

**Issue by jiaqiluo** [rancher/rancher#21997] opened 2019-08-06 02:20 UTC
Bug. rke version v0.2.6

at step 4:
https://rancher.com/docs/rancher/v2.x/en/installation/air-gap-high-availability/prepare-private-registry/

we run 	
```
rke config --system-images >> ./rancher-images.txt
```
to prepare the image list for the private registry, and the output in `rancher-images.txt` contains the following line:
```
...
time="2019-08-06T01:48:39Z" level=info msg="Generating images list for version [v1.14.3-rancher1-1]:"
...
```
This line will break the `./rancher-save-images.sh` and  `./rancher-load-images.sh` because it is not a valid image name

The workaround is to remove that line from the `rancher-images.txt` file manually.

**Comment by superseb** [comment] 2019-08-06 15:35
Seems duplicate of https://github.com/rancher/rancher/issues/20781

**Comment by deniseschannon** [comment] 2019-08-21 18:29
closing in favor of #20781

**Closed by deniseschannon** 2019-08-21 18:29 UTC
Labels: [zube]: To Triage
