### ISSUE TITLE
Secrets: UI shouldn't enable adding volume through storage page

### ISSUE THREAD

**Issue by galal-hussein** [rancher/rancher#7653] opened 2017-02-02 17:47 UTC
**Rancher Versions:**
Server: 1.4.0-rc7

**Docker Version:**
1.12
**OS and where are the hosts located? (cloud, bare metal, etc):**
Ubuntu 16.04 
**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
single node rancher
**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle

- Deploy the secrets catalog template
- Naviagate to the storage page
- Add new volume

The UI shouldn't enable creating new secret volume.

**Comment by tfiduccia** [comment] 2017-02-02 17:55
Duplicate of #7627

**Closed by tfiduccia** 2017-02-02 17:55 UTC
Labels: area/ui, kind/bug
