### ISSUE TITLE
Removing user gets stuck in state "removing"

### ISSUE THREAD

**Issue by timfallmk** [rancher/rancher#15188] opened 2018-08-22 21:06 UTC
**Rancher versions:**
`rancher/server or rancher/rancher:v2.0.7`

**Infrastructure Stack versions:**
kubernetes (if applicable):`1.11.1`

**Docker version: (`docker version`,`docker info` preferred)**
<details>

```
Containers: 3
 Running: 2
 Paused: 0
 Stopped: 1
Images: 6
Server Version: 17.03.2-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 4ab9917febca54791c5f071a9d1f404867857fcc
runc version: 54296cf40ad8143b62dbcaa1d90e520a2136ddfe
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.15.0-1017-gcp
Operating System: Ubuntu 18.04.1 LTS
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 7.298 GiB
Name: chamber-management
ID: AUJR:BJFP:IUR6:2G7S:5NUE:R7KP:4AL7:LT5Q:K66M:MVYF:BZBP:V5MY
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: No swap limit support
```

</details>

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
<details>

```
uname -r
4.15.0-32-generic
```
```
lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.5 LTS
Release:	16.04
Codename:	xenial
```

</details>

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
`Baremetal`

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
`Single node`

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**
`Kubernetes`

**Steps to Reproduce:**
1. Setup Github Authorization delegation
2. Users login via github auth
3. User record is created (in this case as type "Administrator")
4. Separate admin user goes in to Global/Users and deletes user 1
5. User stuck in "Removing" state

**Results:**
User is not removed, but stuck in "Removing" state. Following line appears multiple times per minute.
```
[ERROR] UserController u-2regvni3oe [mgmt-auth-users-controller] failed with : an empty namespace may not be set when a resource name is provided
```

It is occasionally followed by:
```
[ERROR] UserController u-2regvni3oe [mgmt-auth-users-controller] failed with : an empty namespace may not be set when a resource name is provided
2018/08/22 20:41:06 [INFO] Creating new GlobalRoleBinding for GlobalRoleBinding grb-fcxrz
2018/08/22 20:41:06 [INFO] [mgmt-auth-grb-controller] Creating clusterRoleBinding for globalRoleBinding grb-fcxrz for user u-2regvni3oe with role cattle-globalrole-admin
2018/08/22 20:41:10 [INFO] [mgmt-auth-users-controller] Deleting globalRoleBinding grb-fcxrz for user u-2regvni3oe
2018/08/22 20:41:10 [ERROR] UserController u-2regvni3oe [mgmt-auth-users-controller] failed with : an empty namespace may not be set when a resource name is provided
2018/08/22 20:41:10 [ERROR] GlobalRoleBindingController grb-fcxrz [grb-sync] failed with : failed to remove finalizer on :grb-fcxrz
2018/08/22 20:41:10 [ERROR] GlobalRoleBindingController grb-fcxrz [grb-sync] failed with : failed to remove finalizer on :grb-fcxrz
2018/08/22 20:41:10 [ERROR] GlobalRoleBindingController grb-fcxrz [grb-sync] failed with : failed to remove finalizer on :grb-fcxrz
2018/08/22 20:41:19 [ERROR] UserController u-2regvni3oe [mgmt-auth-users-controller] failed with : an empty namespace may not be set when a resource name is provided
2018/08/22 20:42:22 [INFO] Creating new GlobalRoleBinding for GlobalRoleBinding grb-c48lg
2018/08/22 20:42:22 [INFO] [mgmt-auth-grb-controller] Creating clusterRoleBinding for globalRoleBinding grb-c48lg for user u-thhdm with role cattle-globalrole-admin
2018/08/22 20:44:26 [ERROR] UserController u-2regvni3oe [mgmt-auth-users-controller] failed with : an empty namespace may not be set when a resource name is provided
2018/08/22 20:45:15 [ERROR] UserController u-2regvni3oe [mgmt-auth-users-controller] failed with : an empty namespace may not be set when a resource name is provided
```

Full trace from container restart:
<details>

```
2018/08/22 20:36:29 [INFO] Rancher version v2.0.7 is starting
2018/08/22 20:36:29 [INFO] Rancher arguments {ACMEDomains:[vecmanagement.volutus.tech] AddLocal:auto Embedded:false KubeConfig: HTTPListenPort:80 HTTPSListenPort:443 K8sMode:auto Debug:false NoCACerts:false ListenConfig:<nil> AuditLogPath:/var/log/auditlog/rancher-api-audit.log AuditLogMaxage:10 AuditLogMaxsize:100 AuditLogMaxbackup:10 AuditLevel:0}
2018/08/22 20:36:29 [INFO] Listening on /tmp/log.sock
2018/08/22 20:36:29 [INFO] Activating driver gke
2018/08/22 20:36:29 [INFO] Activating driver gke done
2018/08/22 20:36:29 [INFO] Activating driver aks
2018/08/22 20:36:29 [INFO] Activating driver aks done
2018/08/22 20:36:29 [INFO] Activating driver eks
2018/08/22 20:36:29 [INFO] Activating driver eks done
2018/08/22 20:36:29 [INFO] Activating driver import
2018/08/22 20:36:29 [INFO] Activating driver import done
2018/08/22 20:36:29 [INFO] Activating driver rke
2018/08/22 20:36:29 [INFO] Activating driver rke done
I0822 20:36:29.671243       6 http.go:108] HTTP2 has been explicitly disabled
2018/08/22 20:36:29 [INFO] Waiting for server to become available: Get https://127.0.0.1:6443/version: dial tcp 127.0.0.1:6443: getsockopt: connection refused
2018/08/22 20:36:29 [INFO] Running etcd --peer-client-cert-auth --client-cert-auth --key-file=/etc/kubernetes/ssl/kube-etcd-127-0-0-1-key.pem --data-dir=/var/lib/rancher/etcd/ --name=etcd-master --initial-advertise-peer-urls=https://127.0.0.1:2380 --initial-cluster=etcd-master=https://127.0.0.1:2380 --initial-cluster-state=new --cert-file=/etc/kubernetes/ssl/kube-etcd-127-0-0-1.pem --advertise-client-urls=https://127.0.0.1:2379,https://127.0.0.1:4001 --peer-cert-file=/etc/kubernetes/ssl/kube-etcd-127-0-0-1.pem --peer-key-file=/etc/kubernetes/ssl/kube-etcd-127-0-0-1-key.pem --trusted-ca-file=/etc/kubernetes/ssl/kube-ca.pem --peer-trusted-ca-file=/etc/kubernetes/ssl/kube-ca.pem --initial-cluster-token=etcd-cluster-1 --listen-client-urls=https://0.0.0.0:2379 --listen-peer-urls=https://0.0.0.0:2380
2018-08-22 20:36:29.673743 I | etcdmain: etcd Version: 3.2.13
2018-08-22 20:36:29.673781 I | etcdmain: Git SHA: Not provided (use ./build instead of go build)
2018-08-22 20:36:29.673833 I | etcdmain: Go Version: go1.9.2
2018-08-22 20:36:29.673854 I | etcdmain: Go OS/Arch: linux/amd64
2018-08-22 20:36:29.673871 I | etcdmain: setting maximum number of CPUs to 2, total number of available CPUs is 2
2018/08/22 20:36:29 [INFO] Running kube-apiserver --insecure-port=0 --allow-privileged=true --requestheader-username-headers= --endpoint-reconciler-type=lease --etcd-servers=https://127.0.0.1:2379 --proxy-client-key-file= --tls-cert-file=/etc/kubernetes/ssl/kube-apiserver.pem --service-account-key-file=/etc/kubernetes/ssl/kube-apiserver-key.pem --etcd-cafile=/etc/kubernetes/ssl/kube-ca.pem --kubelet-client-certificate=/etc/kubernetes/ssl/kube-apiserver.pem --etcd-certfile=/etc/kubernetes/ssl/kube-node.pem --etcd-prefix=/registry --insecure-bind-address=127.0.0.1 --secure-port=6443 --storage-backend=etcd3 --client-ca-file=/etc/kubernetes/ssl/kube-ca.pem --tls-private-key-file=/etc/kubernetes/ssl/kube-apiserver-key.pem --tls-cipher-suites=TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305,TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305 --kubelet-preferred-address-types=InternalIP,ExternalIP,Hostname --requestheader-allowed-names= --kubelet-client-key=/etc/kubernetes/ssl/kube-apiserver-key.pem --advertise-address=10.43.0.1 --requestheader-group-headers= --authorization-mode=Node,RBAC --admission-control=ServiceAccount,NamespaceLifecycle,LimitRanger,PersistentVolumeLabel,DefaultStorageClass,ResourceQuota,DefaultTolerationSeconds --service-cluster-ip-range=10.43.0.0/16 --requestheader-client-ca-file= --proxy-client-cert-file= --bind-address=127.0.0.1 --requestheader-extra-headers-prefix= --cloud-provider= --service-node-port-range=30000-32767 --etcd-keyfile=/etc/kubernetes/ssl/kube-node-key.pem -v=1 --logtostderr=false --alsologtostderr=false
2018-08-22 20:36:29.682979 N | etcdmain: the server is already initialized as member before, starting as etcd member...
2018-08-22 20:36:29.683080 I | embed: peerTLS: cert = /etc/kubernetes/ssl/kube-etcd-127-0-0-1.pem, key = /etc/kubernetes/ssl/kube-etcd-127-0-0-1-key.pem, ca = , trusted-ca = /etc/kubernetes/ssl/kube-ca.pem, client-cert-auth = true
2018-08-22 20:36:29.683973 I | embed: listening for peers on https://0.0.0.0:2380
2018-08-22 20:36:29.684041 I | embed: listening for client requests on 0.0.0.0:2379
2018-08-22 20:36:29.701168 I | etcdserver: recovered store from snapshot at index 4700047
2018-08-22 20:36:29.704409 I | mvcc: restore compact to 4629756
2018-08-22 20:36:29.916077 I | etcdserver: name = etcd-master
2018-08-22 20:36:29.916123 I | etcdserver: data dir = /var/lib/rancher/etcd/
2018-08-22 20:36:29.916132 I | etcdserver: member dir = /var/lib/rancher/etcd/member
2018-08-22 20:36:29.916136 I | etcdserver: heartbeat = 100ms
2018-08-22 20:36:29.916139 I | etcdserver: election = 1000ms
2018-08-22 20:36:29.916142 I | etcdserver: snapshot count = 100000
2018-08-22 20:36:29.916169 I | etcdserver: advertise client URLs = https://127.0.0.1:2379,https://127.0.0.1:4001
2018-08-22 20:36:30.508669 I | etcdserver: restarting member e92d66acd89ecf29 in cluster 7581d6eb2d25405b at commit index 4740352
2018-08-22 20:36:30.514219 I | raft: e92d66acd89ecf29 became follower at term 77
2018-08-22 20:36:30.514317 I | raft: newRaft e92d66acd89ecf29 [peers: [e92d66acd89ecf29], term: 77, commit: 4740352, applied: 4700047, lastindex: 4740352, lastterm: 77]
2018-08-22 20:36:30.514502 I | etcdserver/api: enabled capabilities for version 3.2
2018-08-22 20:36:30.514534 I | etcdserver/membership: added member e92d66acd89ecf29 [https://127.0.0.1:2380] to cluster 7581d6eb2d25405b from store
2018-08-22 20:36:30.514558 I | etcdserver/membership: set the cluster version to 3.2 from store
2018-08-22 20:36:30.519610 I | mvcc: restore compact to 4629756
2018-08-22 20:36:30.680563 W | auth: simple token is not cryptographically signed
2018-08-22 20:36:30.686900 I | etcdserver: starting server... [version: 3.2.13, cluster version: 3.2]
2018-08-22 20:36:30.688151 I | embed: ClientTLS: cert = /etc/kubernetes/ssl/kube-etcd-127-0-0-1.pem, key = /etc/kubernetes/ssl/kube-etcd-127-0-0-1-key.pem, ca = , trusted-ca = /etc/kubernetes/ssl/kube-ca.pem, client-cert-auth = true
2018-08-22 20:36:31.115003 I | raft: e92d66acd89ecf29 is starting a new election at term 77
2018-08-22 20:36:31.115060 I | raft: e92d66acd89ecf29 became candidate at term 78
2018-08-22 20:36:31.115086 I | raft: e92d66acd89ecf29 received MsgVoteResp from e92d66acd89ecf29 at term 78
2018-08-22 20:36:31.115137 I | raft: e92d66acd89ecf29 became leader at term 78
2018-08-22 20:36:31.115171 I | raft: raft.node: e92d66acd89ecf29 elected leader e92d66acd89ecf29 at term 78
2018-08-22 20:36:31.116746 I | etcdserver: published {Name:etcd-master ClientURLs:[https://127.0.0.1:2379 https://127.0.0.1:4001]} to cluster 7581d6eb2d25405b
2018-08-22 20:36:31.116791 I | embed: ready to serve client requests
2018-08-22 20:36:31.117090 I | embed: serving client requests on [::]:2379
[restful] 2018/08/22 20:36:31 log.go:33: [restful/swagger] listing is available at https://10.43.0.1:6443/swaggerapi
[restful] 2018/08/22 20:36:31 log.go:33: [restful/swagger] https://10.43.0.1:6443/swaggerui/ is mapped to folder /swagger-ui/
[restful] 2018/08/22 20:36:33 log.go:33: [restful/swagger] listing is available at https://10.43.0.1:6443/swaggerapi
[restful] 2018/08/22 20:36:33 log.go:33: [restful/swagger] https://10.43.0.1:6443/swaggerui/ is mapped to folder /swagger-ui/
2018/08/22 20:36:36 [INFO] Running kube-controller-manager --allow-untagged-cloud=true --pod-eviction-timeout=5m0s --allocate-node-cidrs=true --address=0.0.0.0 --leader-elect=true --node-monitor-grace-period=40s --cloud-provider= --kubeconfig=/etc/kubernetes/ssl/kubecfg-kube-controller-manager.yaml --configure-cloud-routes=false --enable-hostpath-provisioner=false --v=2 --service-account-private-key-file=/etc/kubernetes/ssl/kube-apiserver-key.pem --cluster-cidr=10.42.0.0/16 --service-cluster-ip-range=10.43.0.0/16 --root-ca-file=/etc/kubernetes/ssl/kube-ca.pem --use-service-account-credentials=true -v=1 --logtostderr=false --alsologtostderr=false --controllers * --controllers -resourcequota --controllers -service
E0822 20:36:36.948330       6 leaderelection.go:224] error retrieving resource lock kube-system/kube-controller-manager: endpoints "kube-controller-manager" is forbidden: User "system:kube-controller-manager" cannot get endpoints in the namespace "kube-system": [clusterrole.rbac.authorization.k8s.io "system:kube-controller-manager" not found, clusterrole.rbac.authorization.k8s.io "system:basic-user" not found, clusterrole.rbac.authorization.k8s.io "system:discovery" not found]
2018/08/22 20:36:37 [INFO] Starting API controllers
2018/08/22 20:36:37 [INFO] Listening on :443
2018/08/22 20:36:37 [INFO] Listening on :80
2018/08/22 20:36:37 [INFO] Starting catalog controller
2018/08/22 20:36:37 [INFO] Starting management controllers
2018/08/22 20:36:38 [INFO] Handling backend connection request [m-236a1e1bc4bc]
2018/08/22 20:36:38 [INFO] Handling backend connection request [m-8a561003c329]
2018/08/22 20:36:38 [INFO] Handling backend connection request [m-8a561003c329]
2018/08/22 20:36:39 [INFO] Handling backend connection request [m-a95dcb8aebb2]
2018/08/22 20:36:39 [INFO] Handling backend connection request [c-zfzgc]
2018/08/22 20:36:39 [INFO] Handling backend connection request [m-9de2f0ae0967]
2018/08/22 20:36:39 [INFO] Handling backend connection request [m-62d7d5184b7a]
2018/08/22 20:36:39 [INFO] Handling backend connection request [m-3e7a4a12ee1f]
2018/08/22 20:36:39 [INFO] Handling backend connection request [m-8a561003c329]
2018/08/22 20:36:39 [INFO] Handling backend connection request [c-hz7jw]
2018/08/22 20:36:39 [INFO] Handling backend connection request [m-3e7a4a12ee1f]
2018/08/22 20:36:39 [INFO] Handling backend connection request [m-a95dcb8aebb2]
2018/08/22 20:36:39 [INFO] Handling backend connection request [m-9de2f0ae0967]
2018/08/22 20:36:39 [INFO] Handling backend connection request [m-62d7d5184b7a]
2018/08/22 20:36:39 [INFO] Handling backend connection request [m-8a561003c329]
2018/08/22 20:36:39 [INFO] Handling backend connection request [m-236a1e1bc4bc]
2018/08/22 20:36:39 [INFO] Handling backend connection request [m-62d7d5184b7a]
2018/08/22 20:36:39 [INFO] Handling backend connection request [m-9de2f0ae0967]
2018/08/22 20:36:39 [INFO] Handling backend connection request [c-vrmnv]
2018/08/22 20:36:39 [INFO] Handling backend connection request [m-3e7a4a12ee1f]
2018/08/22 20:36:39 [INFO] Handling backend connection request [m-a95dcb8aebb2]
2018/08/22 20:36:43 [ERROR] UserController u-2regvni3oe [mgmt-auth-users-controller] failed with : an empty namespace may not be set when a resource name is provided
2018/08/22 20:36:43 [INFO] Reconciling GlobalRoles
2018/08/22 20:36:43 [INFO] Reconciling RoleTemplates
2018/08/22 20:36:43 [INFO] Starting cluster agent forc-zfzgc
2018/08/22 20:36:43 [INFO] Registering project network policy
2018/08/22 20:36:43 [INFO] Registering namespaceHandler for adding labels 
2018/08/22 20:36:43 [INFO] registering podsecuritypolicy cluster handler for cluster c-zfzgc
2018/08/22 20:36:43 [INFO] registering podsecuritypolicy project handler for cluster c-zfzgc
2018/08/22 20:36:43 [INFO] registering podsecuritypolicy namespace handler for cluster c-zfzgc
2018/08/22 20:36:43 [INFO] registering podsecuritypolicy serviceaccount handler for cluster c-zfzgc
2018/08/22 20:36:43 [INFO] registering podsecuritypolicy template handler for cluster c-zfzgc
2018/08/22 20:36:43 [INFO] Starting cluster agent forc-hz7jw
2018/08/22 20:36:43 [INFO] Starting cluster controllers for c-zfzgc
2018/08/22 20:36:44 [ERROR] UserController u-2regvni3oe [mgmt-auth-users-controller] failed with : an empty namespace may not be set when a resource name is provided
2018/08/22 20:36:44 [INFO] Updating catalog helm-incubator
2018/08/22 20:36:44 [INFO] Registering project network policy
2018/08/22 20:36:44 [INFO] Registering namespaceHandler for adding labels 
2018/08/22 20:36:44 [INFO] registering podsecuritypolicy cluster handler for cluster c-hz7jw
2018/08/22 20:36:44 [INFO] registering podsecuritypolicy project handler for cluster c-hz7jw
2018/08/22 20:36:44 [INFO] registering podsecuritypolicy namespace handler for cluster c-hz7jw
2018/08/22 20:36:44 [INFO] registering podsecuritypolicy serviceaccount handler for cluster c-hz7jw
2018/08/22 20:36:44 [INFO] registering podsecuritypolicy template handler for cluster c-hz7jw
2018/08/22 20:36:44 [INFO] Starting cluster controllers for c-hz7jw
2018/08/22 20:36:45 [ERROR] UserController u-2regvni3oe [mgmt-auth-users-controller] failed with : an empty namespace may not be set when a resource name is provided
2018/08/22 20:36:45 [INFO] Updating catalog helm
2018/08/22 20:36:45 [INFO] Rancher startup complete
2018/08/22 20:36:46 [INFO] Updating catalog library
2018/08/22 20:36:47 [ERROR] UserController u-2regvni3oe [mgmt-auth-users-controller] failed with : an empty namespace may not be set when a resource name is provided
2018/08/22 20:36:48 [INFO] Catalog sync done. 0 templates created, 2 templates updated, 0 templates deleted
2018/08/22 20:36:49 [INFO] Catalog sync done. 0 templates created, 3 templates updated, 0 templates deleted
2018/08/22 20:36:51 [ERROR] UserController u-2regvni3oe [mgmt-auth-users-controller] failed with : an empty namespace may not be set when a resource name is provided
2018/08/22 20:36:52 [INFO] Catalog sync done. 0 templates created, 25 templates updated, 0 templates deleted
2018/08/22 20:36:59 [ERROR] UserController u-2regvni3oe [mgmt-auth-users-controller] failed with : an empty namespace may not be set when a resource name is provided
2018/08/22 20:37:15 [ERROR] UserController u-2regvni3oe [mgmt-auth-users-controller] failed with : an empty namespace may not be set when a resource name is provided
2018/08/22 20:37:47 [ERROR] UserController u-2regvni3oe [mgmt-auth-users-controller] failed with : an empty namespace may not be set when a resource name is provided
2018/08/22 20:38:51 [ERROR] UserController u-2regvni3oe [mgmt-auth-users-controller] failed with : an empty namespace may not be set when a resource name is provided
2018/08/22 20:40:59 [ERROR] UserController u-2regvni3oe [mgmt-auth-users-controller] failed with : an empty namespace may not be set when a resource name is provided
2018/08/22 20:41:05 [ERROR] UserController u-2regvni3oe [mgmt-auth-users-controller] failed with : an empty namespace may not be set when a resource name is provided
2018/08/22 20:41:06 [INFO] Creating new GlobalRoleBinding for GlobalRoleBinding grb-fcxrz
2018/08/22 20:41:06 [INFO] [mgmt-auth-grb-controller] Creating clusterRoleBinding for globalRoleBinding grb-fcxrz for user u-2regvni3oe with role cattle-globalrole-admin
2018/08/22 20:41:10 [INFO] [mgmt-auth-users-controller] Deleting globalRoleBinding grb-fcxrz for user u-2regvni3oe
2018/08/22 20:41:10 [ERROR] UserController u-2regvni3oe [mgmt-auth-users-controller] failed with : an empty namespace may not be set when a resource name is provided
2018/08/22 20:41:10 [ERROR] GlobalRoleBindingController grb-fcxrz [grb-sync] failed with : failed to remove finalizer on :grb-fcxrz
2018/08/22 20:41:10 [ERROR] GlobalRoleBindingController grb-fcxrz [grb-sync] failed with : failed to remove finalizer on :grb-fcxrz
2018/08/22 20:41:10 [ERROR] GlobalRoleBindingController grb-fcxrz [grb-sync] failed with : failed to remove finalizer on :grb-fcxrz
2018/08/22 20:41:19 [ERROR] UserController u-2regvni3oe [mgmt-auth-users-controller] failed with : an empty namespace may not be set when a resource name is provided
2018/08/22 20:42:22 [INFO] Creating new GlobalRoleBinding for GlobalRoleBinding grb-c48lg
2018/08/22 20:42:22 [INFO] [mgmt-auth-grb-controller] Creating clusterRoleBinding for globalRoleBinding grb-c48lg for user u-thhdm with role cattle-globalrole-admin
2018/08/22 20:44:26 [ERROR] UserController u-2regvni3oe [mgmt-auth-users-controller] failed with : an empty namespace may not be set when a resource name is provided
2018/08/22 20:45:15 [ERROR] UserController u-2regvni3oe [mgmt-auth-users-controller] failed with : an empty namespace may not be set when a resource name is provided
2018-08-22 20:46:31.140123 I | mvcc: store.index: compact 4631144
2018-08-22 20:46:31.369367 I | mvcc: finished scheduled compaction at 4631144 (took 215.594724ms)
E0822 20:48:48.529494       6 watcher.go:208] watch chan error: etcdserver: mvcc: required revision has been compacted
2018-08-22 20:51:31.163065 I | mvcc: store.index: compact 4631682
2018-08-22 20:51:31.389684 I | mvcc: finished scheduled compaction at 4631682 (took 214.787934ms)
2018-08-22 20:56:31.184213 I | mvcc: store.index: compact 4632198
2018-08-22 20:56:31.413328 I | mvcc: finished scheduled compaction at 4632198 (took 214.614988ms)
2018-08-22 21:01:31.211404 I | mvcc: store.index: compact 4632712
2018-08-22 21:01:31.440626 I | mvcc: finished scheduled compaction at 4632712 (took 214.326952ms)
2018/08/22 21:01:55 [ERROR] UserController u-2regvni3oe [mgmt-auth-users-controller] failed with : an empty namespace may not be set when a resource name is provided
E0822 21:03:01.618821       6 watcher.go:208] watch chan error: etcdserver: mvcc: required revision has been compacted
```

</details>

**Comment by dramich** [comment] 2018-08-23 18:00
This appears to be a duplicate of https://github.com/rancher/rancher/issues/15067.

QA: Can you verify this is fixed on master?

**Comment by timfallmk** [comment] 2018-08-24 18:47
@dramich Updated to `master` on this production cluster and users appear removable now.

**Comment by soumyalj** [comment] 2018-08-28 19:29
Reproduced the issue in v2.0.7
```
2018/08/28 19:25:55 [ERROR] UserController u-4cnrgx47ty [mgmt-auth-users-controller] failed with : an empty namespace may not be set when a resource name is provided
2018/08/28 19:25:57 [ERROR] UserController u-4cnrgx47ty [mgmt-auth-users-controller] failed with : an empty namespace may not be set when a resource name is provided

```
Tested with master. 
Logged with github auth as user1 . A user was created. Logged in as another admin and deleted "user1". The user1 got deleted successfully. The error in logs seen in the issue above was not observed

```
2018/08/28 19:08:01 [INFO] [mgmt-auth-users-controller] Deleting token token-h6d7b for user user-bhzgz
2018/08/28 19:08:01 [INFO] [mgmt-auth-users-controller] Deleting token token-sxpf4 for user user-bhzgz
2018/08/28 19:08:01 [ERROR] GlobalRoleBindingController globalrolebinding-7frf6 [grb-sync] failed with : failed to remove finalizer on :globalrolebinding-7frf6
2018/08/28 19:08:01 [INFO] [mgmt-auth-users-controller] Deleting token token-z4svb for user user-bhzgz
2018/08/28 19:08:01 [INFO] [mgmt-auth-users-controller] Deleting namespace backing user user-bhzgz
2018/08/28 19:08:01 [INFO] [mgmt-auth-users-controller] Deleting secret backing user user-bhzgz

```

**Closed by soumyalj** 2018-08-28 19:29 UTC
Labels: area/server, kind/bug, status/resolved, status/to-test, version/2.0
