### ISSUE TITLE
Scheduler hanging, preventing any other containers from coming up in the environment.

### ISSUE THREAD

**Issue by aemneina** [rancher/rancher#10252] opened 2017-10-30 22:05 UTC
**Rancher versions:**
rancher/server: v1.6.2
rancher/agent: 1.2.2

**Results:**
The environment experienced some memory pressure. Metadata keeled over, wasnt recovering as scheduler seems to have died as well.

```10/27/2017 12:51:47 PMtime="2017-10-27T17:51:47Z" level=info msg="Reply: Name: reply.2011518542631162092, PreviousIds: [d90144df-b92a-4cc6-a04e-539caaff7a0b], ResourceId: 1iir52286, Data: map[]."
10/27/2017 12:52:11 PMtime="2017-10-27T17:51:58Z" level=warning msg="websocket closed: write tcp 172.19.252.46:42482->10.49.18.169:443: i/o timeout"
10/27/2017 12:52:22 PMtime="2017-10-27T17:52:10Z" level=info msg="Hit websocket pong timeout. Last websocket ping received at 2017-10-27 17:51:48.36026425 +0000 UTC. Closing connection."
10/27/2017 12:52:26 PMtime="2017-10-27T17:52:13Z" level=error msg="Error 1 getting metadata: Get http://169.254.169.250/2016-07-29/containers: net/http: request canceled (Client.Timeout exceeded while awaiting headers)"
10/27/2017 12:52:28 PMpanic: runtime error: invalid memory address or nil pointer dereference
10/27/2017 12:52:28 PM[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x748675]
10/27/2017 12:52:28 PM
10/27/2017 12:52:29 PMgoroutine 38 [running]:
10/27/2017 12:52:29 PMgithub.com/rancher/scheduler/scheduler.(*PortResourcePool).GetPoolResourceType(0x0, 0xc420010fc0, 0xc420430f30)
10/27/2017 12:52:30 PM	/go/src/github.com/rancher/scheduler/scheduler/types.go:108 +0x5
10/27/2017 12:52:30 PMgithub.com/rancher/scheduler/scheduler.(*Scheduler).UpdateResourcePool(0xc420080820, 0xc420430f30, 0x24, 0xdaa1e0, 0x0, 0xc420430e00)
10/27/2017 12:52:30 PM	/go/src/github.com/rancher/scheduler/scheduler/scheduler.go:173 +0xc2
10/27/2017 12:52:30 PMgithub.com/rancher/scheduler/resourcewatchers.(*metadataWatcher).updateFromMetadata(0xc4200ec190, 0xc4202e1950, 0x26)
10/27/2017 12:52:30 PM	/go/src/github.com/rancher/scheduler/resourcewatchers/metadata.go:109 +0x694
10/27/2017 12:52:31 PMgithub.com/rancher/scheduler/resourcewatchers.(*metadataWatcher).(github.com/rancher/scheduler/resourcewatchers.updateFromMetadata)-fm(0xc4202e1950, 0x26)
10/27/2017 12:52:31 PM	/go/src/github.com/rancher/scheduler/resourcewatchers/metadata.go:23 +0x3e
10/27/2017 12:52:31 PMgithub.com/rancher/scheduler/vendor/github.com/rancher/go-rancher-metadata/metadata.(*client).onChangeFromVersionWithError(0xc420011020, 0xc4203ec690, 0x26, 0x5, 0xc420130100, 0x1, 0xc420130100)
10/27/2017 12:52:32 PM	/go/src/github.com/rancher/scheduler/vendor/github.com/rancher/go-rancher-metadata/metadata/change.go:25 +0x1bb
10/27/2017 12:52:32 PMgithub.com/rancher/scheduler/vendor/github.com/rancher/go-rancher-metadata/metadata.(*client).OnChangeWithError(0xc420011020, 0x5, 0xc420130100, 0x0, 0xc42019c090)
10/27/2017 12:52:32 PM	/go/src/github.com/rancher/scheduler/vendor/github.com/rancher/go-rancher-metadata/metadata/change.go:12 +0x54
10/27/2017 12:52:32 PMgithub.com/rancher/scheduler/resourcewatchers.WatchMetadata(0xdb0840, 0xc420011020, 0xdae0c0, 0xc420080820, 0xc4200dc000, 0x5141dd, 0x896fc0)
10/27/2017 12:52:33 PM	/go/src/github.com/rancher/scheduler/resourcewatchers/metadata.go:23 +0x1c9
10/27/2017 12:52:33 PMmain.run.func2(0xdb0840, 0xc420011020, 0xc420080820, 0xc4200dc000, 0xc420252180)
10/27/2017 12:52:33 PM	/go/src/github.com/rancher/scheduler/main.go:88 +0x59
10/27/2017 12:52:33 PMcreated by main.run
10/27/2017 12:52:34 PM	/go/src/github.com/rancher/scheduler/main.go:90 +0x637```

**Comment by jean-francois-labbe** [comment] 2017-12-01 13:17
I have the same issue. Same error in scheduler logs.

Container placement is messed up

**Comment by glutamatt** [comment] 2018-04-30 16:19
I'm affected with the same issue 😒

component | version
---- | ---
rancher/scheduler | 0.8.3 
Rancher | 1.6.17
Cattle | v0.183.49
rancher/agent | v1.2.10






```
4/30/2018 6:06:46 PMtime="2018-04-30T16:06:46Z" level=info msg="Subscribing to metadata changes."
4/30/2018 6:06:46 PMtime="2018-04-30T16:06:46Z" level=info msg="Connecting to cattle event stream."
4/30/2018 6:06:46 PMtime="2018-04-30T16:06:46Z" level=info msg="Listening for health checks on 0.0.0.0:80/healthcheck"
4/30/2018 6:06:46 PMtime="2018-04-30T16:06:46Z" level=info msg="Initializing event router" workerCount=100
4/30/2018 6:06:46 PMtime="2018-04-30T16:06:46Z" level=info msg="Connection established"
4/30/2018 6:06:46 PMtime="2018-04-30T16:06:46Z" level=info msg="Starting websocket pings"
4/30/2018 6:06:55 PMtime="2018-04-30T16:06:55Z" level=info msg="Adding resource pool [instanceReservation] with total 1000000 and used 55 for host  8e581ba4-e843-4183-891d-c080b6a75931"
4/30/2018 6:06:55 PMtime="2018-04-30T16:06:55Z" level=info msg="Adding resource pool [cpuReservation] with total 4000 and used 0 for host  8e581ba4-e843-4183-891d-c080b6a75931"
4/30/2018 6:06:55 PMtime="2018-04-30T16:06:55Z" level=info msg="Adding resource pool [memoryReservation] with total 17080254464 and used 12528000000 for host  8e581ba4-e843-4183-891d-c080b6a75931"
4/30/2018 6:06:55 PMtime="2018-04-30T16:06:55Z" level=info msg="Adding resource pool [storageSize] with total 206800314 and used 0 for host  8e581ba4-e843-4183-891d-c080b6a75931"
4/30/2018 6:06:57 PMtime="2018-04-30T16:06:57Z" level=info msg="Adding resource pool [portReservation], ip set [0.0.0.0], ports map tcp map[0.0.0.0:map[65530:c2c3ecc7-98e7-448e-9096-2bb1a5b69398 65531:c2c3ecc7-98e7-448e-9096-2bb1a5b69398 65529:43306e8d-4c63-40e8-a143-1b7e7f29655c 60446:0a2f8acc-d495-45e5-9708-e1c6d8420aee 65525:b94d511f-a96c-43e5-961c-a42444ec16bb 7000:b94d511f-a96c-43e5-961c-a42444ec16bb 65527:f5f605f0-b28e-48a6-8152-08996a5370e8 8090:f67371d6-f3c2-4162-86e4-d6e546dd9b61 65528:43306e8d-4c63-40e8-a143-1b7e7f29655c 3306:16010bf9-4592-4839-9d43-495c4079a461 8000:f67371d6-f3c2-4162-86e4-d6e546dd9b61]], ports map udp map[0.0.0.0:map[500:6eea05f3-adf8-4c5f-be08-83b5b242995f 4500:6eea05f3-adf8-4c5f-be08-83b5b242995f]] for host 8e581ba4-e843-4183-891d-c080b6a75931"
4/30/2018 6:06:57 PMtime="2018-04-30T16:06:57Z" level=info msg="Adding resource pool [hostLabels] with label map [map[io.rancher.host.docker_version:17.12 io.rancher.host.linux_kernel_version:4.9 io.rancher.host.os:linux traefik_lb:true io.rancher.host.agent_image:rancher/agent:v1.2.10]]"
4/30/2018 6:06:57 PMtime="2018-04-30T16:06:57Z" level=info msg="Adding resource pool [instanceReservation] with total 1000000 and used 51 for host  aaf6cf80-4a20-4325-9274-35c9aca93d2a"
4/30/2018 6:06:57 PMtime="2018-04-30T16:06:57Z" level=info msg="Adding resource pool [cpuReservation] with total 4000 and used 0 for host  aaf6cf80-4a20-4325-9274-35c9aca93d2a"
4/30/2018 6:06:57 PMtime="2018-04-30T16:06:57Z" level=info msg="Adding resource pool [memoryReservation] with total 17080254464 and used 7760000000 for host  aaf6cf80-4a20-4325-9274-35c9aca93d2a"
4/30/2018 6:06:57 PMtime="2018-04-30T16:06:57Z" level=info msg="Adding resource pool [storageSize] with total 239260372 and used 0 for host  aaf6cf80-4a20-4325-9274-35c9aca93d2a"
4/30/2018 6:07:07 PMtime="2018-04-30T16:07:07Z" level=error msg="Error 1 getting metadata: net/http: request canceled (Client.Timeout exceeded while reading body)"
4/30/2018 6:07:07 PMpanic: runtime error: invalid memory address or nil pointer dereference
4/30/2018 6:07:07 PM[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x748675]
4/30/2018 6:07:07 PM
4/30/2018 6:07:07 PMgoroutine 40 [running]:
4/30/2018 6:07:07 PMgithub.com/rancher/scheduler/scheduler.(*PortResourcePool).GetPoolResourceType(0x0, 0xc420010f90, 0xc4201049f0)
4/30/2018 6:07:07 PM	/go/src/github.com/rancher/scheduler/scheduler/types.go:108 +0x5
4/30/2018 6:07:07 PMgithub.com/rancher/scheduler/scheduler.(*Scheduler).UpdateResourcePool(0xc42008e820, 0xc4201049f0, 0x24, 0xdab1e0, 0x0, 0xc420104900)
4/30/2018 6:07:07 PM	/go/src/github.com/rancher/scheduler/scheduler/scheduler.go:173 +0xc2
4/30/2018 6:07:07 PMgithub.com/rancher/scheduler/resourcewatchers.(*metadataWatcher).updateFromMetadata(0xc420018a00, 0xc420104480, 0x24)
4/30/2018 6:07:07 PM	/go/src/github.com/rancher/scheduler/resourcewatchers/metadata.go:109 +0x694
4/30/2018 6:07:07 PMgithub.com/rancher/scheduler/resourcewatchers.(*metadataWatcher).(github.com/rancher/scheduler/resourcewatchers.updateFromMetadata)-fm(0xc420104480, 0x24)
4/30/2018 6:07:07 PM	/go/src/github.com/rancher/scheduler/resourcewatchers/metadata.go:23 +0x3e
4/30/2018 6:07:07 PMgithub.com/rancher/scheduler/vendor/github.com/rancher/go-rancher-metadata/metadata.(*client).onChangeFromVersionWithError(0xc420010ff0, 0x9797a0, 0x4, 0x5, 0xc42001bac0, 0x1, 0xc42001bac0)
4/30/2018 6:07:07 PM	/go/src/github.com/rancher/scheduler/vendor/github.com/rancher/go-rancher-metadata/metadata/change.go:25 +0x1bb
4/30/2018 6:07:07 PMgithub.com/rancher/scheduler/vendor/github.com/rancher/go-rancher-metadata/metadata.(*client).OnChangeWithError(0xc420010ff0, 0x5, 0xc42001bac0, 0x0, 0xc420011f80)
4/30/2018 6:07:07 PM	/go/src/github.com/rancher/scheduler/vendor/github.com/rancher/go-rancher-metadata/metadata/change.go:12 +0x54
4/30/2018 6:07:07 PMgithub.com/rancher/scheduler/resourcewatchers.WatchMetadata(0xdb1840, 0xc420010ff0, 0xdaf0c0, 0xc42008e820, 0xc4200ea000, 0x0, 0x0)
4/30/2018 6:07:07 PM	/go/src/github.com/rancher/scheduler/resourcewatchers/metadata.go:23 +0x1c9
4/30/2018 6:07:07 PMmain.run.func2(0xdb1840, 0xc420010ff0, 0xc42008e820, 0xc4200ea000, 0xc420130ba0)
4/30/2018 6:07:07 PM	/go/src/github.com/rancher/scheduler/main.go:88 +0x59
4/30/2018 6:07:07 PMcreated by main.run
4/30/2018 6:07:07 PM	/go/src/github.com/rancher/scheduler/main.go:90 +0x637
```

**Comment by nelsonfassis** [comment] 2018-10-09 23:11
I'm also having this issue. Deleting container, removing healthcheck and changing configs did not fix the issue. Did anyone find a workaround?

**Comment by alena1108** [comment] 2019-01-21 22:20
> The environment experienced some memory pressure. Metadata keeled over, wasnt recovering as scheduler seems to have died as well. 

There are 2 parts to the fix. 

1)  In rancher versions < 1.6.18 system containers like metadata, ipsec, scheduler weren't taking precedence over regular containers on start. It could result in the system being overloaded when user containers start was attempted before ipsec or metadata container even had a chance to come up. The issue was addressed by dedicating a threadpool for the system containers (https://github.com/rancher/cattle/pull/2883) and validated on rancher 1.6.18

2) The second issue is with scheduler showing panic in the log. @StrongMonkey fix addresses this particular issue. If metadata fails to be reached, there will be no panic anymore, and the container will just fall back on the failed health check mechanism. Once the metadata is unreachable for 5 consecutive, the container will be reported as unhealthy and recreated by the rancher service reconcile flow.

**Comment by alena1108** [comment] 2019-01-22 01:20
resolved in scheduler build v0.8.6; available in `rancher/server:v1.6.26-rc2`

**Comment by StrongMonkey** [comment] 2019-01-23 22:13
@alena1108 This issue is obvious to fix in the code but hard to validate on the QA side. It is hard for QA to simulate an environment where metadata is overloaded and takes more time to respond. In this case the environment is already unusable and pretty hard to validate anything right now.

**Comment by soumyalj** [comment] 2019-01-23 23:23
@StrongMonkey : Tried to reproduce with 4G hosts on rancher v1.6.2. Created around 1500 containers. Observed that scheduler becomes unhealthy  and restarts and Rancher UI becomes responsive. The nodes go to reconnecting state and the setup is not usable anymore.

**Comment by StrongMonkey** [comment] 2019-01-24 23:10
@soumyalj Tested with private metadata image that sleeps a certain amount of time to simulate the timeout of overloading metadata server. During the validation there is no NPE exception. Other panics are seen because the original design is to make scheduler panic and exit if metadata failed to reach. In such cases scheduler continue to restart until metadata recovers.

**Comment by soumyalj** [comment] 2019-01-25 00:04
Reproduced the issue using v1.6.2 with private image of metadata which has a sleep in metadata as mentioned above . Panic with  NULL pointer exception was observed as below:
```
1/24/2019 1:28:07 PMtime="2019-01-24T21:28:07Z" level=info msg="Listening for health checks on 0.0.0.0:80/healthcheck"
1/24/2019 1:28:07 PMtime="2019-01-24T21:28:07Z" level=info msg="Initializing event router" workerCount=100
1/24/2019 1:28:07 PMtime="2019-01-24T21:28:07Z" level=info msg="Connection established"
1/24/2019 1:28:07 PMtime="2019-01-24T21:28:07Z" level=info msg="Starting websocket pings"
1/24/2019 1:28:11 PMtime="2019-01-24T21:28:11Z" level=info msg="Adding resource pool [storageSize] with total 39727431 and used 0 for host  bad9419b-a7bb-4d28-b2f7-6dbf8ec4a1db"
1/24/2019 1:28:11 PMtime="2019-01-24T21:28:11Z" level=info msg="Adding resource pool [instanceReservation] with total 1000000 and used 9 for host  bad9419b-a7bb-4d28-b2f7-6dbf8ec4a1db"
1/24/2019 1:28:11 PMtime="2019-01-24T21:28:11Z" level=info msg="Adding resource pool [cpuReservation] with total 1000 and used 0 for host  bad9419b-a7bb-4d28-b2f7-6dbf8ec4a1db"
1/24/2019 1:28:11 PMtime="2019-01-24T21:28:11Z" level=info msg="Adding resource pool [memoryReservation] with total 1771044864 and used 0 for host  bad9419b-a7bb-4d28-b2f7-6dbf8ec4a1db"
1/24/2019 1:28:19 PMtime="2019-01-24T21:28:19Z" level=info msg="Adding resource pool [portReservation], ip set [0.0.0.0], ports map tcp map[0.0.0.0:map[]], ports map udp map[0.0.0.0:map[500:9ed38964-dc6a-4da9-ad8f-2560f24b3d3b 4500:9ed38964-dc6a-4da9-ad8f-2560f24b3d3b]] for host bad9419b-a7bb-4d28-b2f7-6dbf8ec4a1db"
1/24/2019 1:28:19 PMtime="2019-01-24T21:28:19Z" level=info msg="Adding resource pool [hostLabels] with label map [map[io.rancher.host.agent_image:rancher/agent:v1.2.2 io.rancher.host.docker_version:1.12 io.rancher.host.linux_kernel_version:4.15]]"
1/24/2019 1:28:29 PMtime="2019-01-24T21:28:29Z" level=error msg="Error 1 getting metadata: Get http://169.254.169.250/2016-07-29/containers: net/http: request canceled (Client.Timeout exceeded while awaiting headers)"
1/24/2019 1:28:29 PMpanic: runtime error: invalid memory address or nil pointer dereference
1/24/2019 1:28:29 PM[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x748675]
1/24/2019 1:28:29 PM
1/24/2019 1:28:29 PMgoroutine 19 [running]:
1/24/2019 1:28:29 PMgithub.com/rancher/scheduler/scheduler.(*PortResourcePool).GetPoolResourceType(0x0, 0xc420010ff0, 0xc4201afa10)
1/24/2019 1:28:29 PM	/go/src/github.com/rancher/scheduler/scheduler/types.go:108 +0x5
1/24/2019 1:28:29 PMgithub.com/rancher/scheduler/scheduler.(*Scheduler).UpdateResourcePool(0xc4200ba6e0, 0xc4201afa10, 0x24, 0xdaa1e0, 0x0, 0xc4201af900)
1/24/2019 1:28:29 PM	/go/src/github.com/rancher/scheduler/scheduler/scheduler.go:173 +0xc2
1/24/2019 1:28:29 PMgithub.com/rancher/scheduler/resourcewatchers.(*metadataWatcher).updateFromMetadata(0xc420018fa0, 0xc4201af6e0, 0x26)
1/24/2019 1:28:29 PM	/go/src/github.com/rancher/scheduler/resourcewatchers/metadata.go:109 +0x694
1/24/2019 1:28:29 PMgithub.com/rancher/scheduler/resourcewatchers.(*metadataWatcher).(github.com/rancher/scheduler/resourcewatchers.updateFromMetadata)-fm(0xc4201af6e0, 0x26)
1/24/2019 1:28:29 PM	/go/src/github.com/rancher/scheduler/resourcewatchers/metadata.go:23 +0x3e
1/24/2019 1:28:29 PMgithub.com/rancher/scheduler/vendor/github.com/rancher/go-rancher-metadata/metadata.(*client).onChangeFromVersionWithError(0xc420011050, 0xc420113470, 0x26, 0x5, 0xc420109870, 0x1, 0xc420109870)
1/24/2019 1:28:29 PM	/go/src/github.com/rancher/scheduler/vendor/github.com/rancher/go-rancher-metadata/metadata/change.go:25 +0x1bb
1/24/2019 1:28:29 PMgithub.com/rancher/scheduler/vendor/github.com/rancher/go-rancher-metadata/metadata.(*client).OnChangeWithError(0xc420011050, 0x5, 0xc420109870, 0x0, 0xc420112ff0)
1/24/2019 1:28:29 PM	/go/src/github.com/rancher/scheduler/vendor/github.com/rancher/go-rancher-metadata/metadata/change.go:12 +0x54
1/24/2019 1:28:29 PMgithub.com/rancher/scheduler/resourcewatchers.WatchMetadata(0xdb0840, 0xc420011050, 0xdae0c0, 0xc4200ba6e0, 0xc4200d0000, 0x0, 0x0)
1/24/2019 1:28:29 PM	/go/src/github.com/rancher/scheduler/resourcewatchers/metadata.go:23 +0x1c9
1/24/2019 1:28:29 PMmain.run.func2(0xdb0840, 0xc420011050, 0xc4200ba6e0, 0xc4200d0000, 0xc420057620)
1/24/2019 1:28:29 PM	/go/src/github.com/rancher/scheduler/main.go:88 +0x59
1/24/2019 1:28:29 PMcreated by main.run
1/24/2019 1:28:29 PM	/go/src/github.com/rancher/scheduler/main.go:90 +0x637
```

**Closed** 2019-01-25 19:40 UTC
Labels: area/scheduler, area/ui, internal, status/ready-for-review, status/resolved, status/to-test, version/1.6
