### ISSUE TITLE
Default Host Labels

### ISSUE THREAD

**Issue by cloudnautique** [rancher/rancher#1901] opened 2015-08-27 17:56 UTC
It would be useful if Rancher created some default host labels/attributes that can be used in scheduling. 
being able to schedule to `must have label hostname=compute-app-*` or be able to specify docker versions, memory, core count.

**Comment by deniseschannon** [comment] 2016-07-13 04:38
Duplicate of https://github.com/rancher/rancher/issues/1742 (which was also created by @cloudnautique :) )

**Closed by deniseschannon** 2016-07-13 04:38 UTC
Labels: area/host, kind/enhancement
