### ISSUE TITLE
UI: bug on any vSphere related setting

### ISSUE THREAD

**Issue by Xat59** [rancher/rancher#30891] opened 2021-01-19 17:45 UTC
**What kind of request is this (question/bug/enhancement/feature request):**
Clearly a bug

**Steps to reproduce (least amount of steps as possible):**
1/ Go to https://<rancher-url>/n/node-templates
2/ Click "Add Template" button
3/ Create a node template for vSphere, then **configure it by replacing any vSphere related default setting by a non-default value**. vSphere related settings, such as : "Data Center", "Resource Pool", "Data Store", "Folder", or "Host".
4/ Save the node template configuration
5/ Now you're come back to https://<rancher-url>/n/node-templates, you should see the newly created node template for vSphere. So, edit it now.
6/ Take a look at the vSphere related settings you've just configured at step 3.

I can also confirm this behavior on following settings in node-templates page : 
- "Networks"
- when you select and configure a "Creation method" that is vSphere based, such as "Deploy from template: Data Center", "Deploy from template: Content Library" or "Clone an existing virtual machine".

**Result:**
We can see the node template has default vSphere settings configured into the node template, even if we've changed default values with non-default values, at step 3.
We should instead see the values we've explicitly configured, not the default ones.

**Other details that may be helpful:**
Anyway, I am able to use the node template and it deploys regarding the saved settings, not the default ones.
So, it seems that the UI does not retrieve saved settings when editing the node template.

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): v2.5.5
- Installation option (single install/HA): single install with docker

Thanks a lot.

**Comment by makeacode** [comment] 2021-02-04 16:14
this is happening to me as well on 2.5.5...pretty annoying

**Comment by eizieizi** [comment] 2021-02-06 23:56
can also confirm

**Comment by stranljip** [comment] 2021-02-22 06:57
Can someone with sufficient permissions please review and close #30910 and #31356 as duplicates of this one? For us, this is a pretty severe bug and it would be nice to make it easier for people to find the main issue and vote for it. Also a triage and estimation from the side of the rancher team would be nice ...

**Comment by depasseg** [comment] 2021-02-24 14:07
I don't think this is just a display issue.  When I try to use the template, the network doesn't get assigned, the Folder isn't used, and the Datastore setting isn't used.

**Comment by stranljip** [comment] 2021-02-25 06:29
> I don't think this is just a display issue. When I try to use the template, the network doesn't get assigned, the Folder isn't used, and the Datastore setting isn't used.

Good catch, I did not see that in the bug description. I just tried that with a cloned template and the VM does not get provisioned because all kinds of things are missing or being reset to the defaults. So - no UI issue for me either.

**Comment by dlhace** [comment] 2021-03-04 19:37
I don't know if this is helpful information.   But ...

I had a single node install on Red Hat that didn't have this problem, but a Ubuntu that did.  I tried a Centos in single mode and it had a problem.  The Redhat was using docker vserion Redhat 1.13.1 and the ubuntu and centos were both using the Community Edition 20.10.3.  So then I tried Ubuntu again using docker.io edition 19.03.8.  I had no problem editing the templates.

**Comment by stranljip** [comment] 2021-03-05 06:23
> I don't know if this is helpful information. But ...
> 
> I had a single node install on Red Hat that didn't have this problem, but a Ubuntu that did. I tried a Centos in single mode and it had a problem. The Redhat was using docker vserion Redhat 1.13.1 and the ubuntu and centos were both using the Community Edition 20.10.3. So then I tried Ubuntu again using docker.io edition 19.03.8. I had no problem editing the templates.

I just tested that and downgraded Docker on our Rancher host to 19.03.15 - without effect.

**Comment by dramich** [comment] 2021-03-08 16:41
Closing as a duplicate of https://github.com/rancher/rancher/issues/30690

**Closed by dramich** 2021-03-08 16:41 UTC
