### ISSUE TITLE
Telemetry's cpu util_min is negative 

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#15394] opened 2018-09-04 19:50 UTC
**Rancher versions:** 2.1 master 9/4

**Steps to Reproduce:**
1.  Setup a GKE cluster and wait for it to be fully active
2.  Go to telemetry results

**Results:**  Minimum utilized is a huge negative number.  Should never be negative.  This is for both the cluster cpu section & the Node cpu section
![image](https://user-images.githubusercontent.com/11514927/45054147-f505e580-b040-11e8-91ed-e5b91f1c68cb.png)

**Comment by cjellick** [comment] 2018-09-12 01:34
@rawmind0 can you provide any insight (or a fix) into this? I believe you had a hand in developing this

**Comment by rawmind0** [comment] 2018-09-12 14:28
It's strange that appears negative values on that. Telemetry is just getting values from rancher v3 API, `allocatable` and `requested` values from Clusters and Nodes.

@cjellick submited PR to telemetry to fix issue, just allowing positive values.
https://github.com/rancher/telemetry/pull/15

**Comment by cjellick** [comment] 2018-12-28 18:55
telemetry PR is merged, but i need to update rancher for the new telem

**Comment by davidnuzik** [comment] 2019-01-21 23:51
Version: master 2.2 (1/21/19)
Confirmed fix. I am not able to reproduce the issue. I tried to smoke test and put a load on a workload or two as well and regardless of what I did I could not reproduce the issue.
Note: The telemetry data can be checked by accessing https://<rancherserver>/v1-telemetry

**Closed by davidnuzik** 2019-01-21 23:51 UTC
Labels: area/telemetry, kind/bug, priority/1, status/resolved, status/to-test, team/az, version/2.0
