### ISSUE TITLE
Stuck in "Purging machine" loop and then fails to re-activate machine driver

### ISSUE THREAD

**Issue by janeczku** [rancher/rancher#8379] opened 2017-03-31 22:37 UTC
**Rancher Versions:**
Server: 1.5.2 Non-HA
Cattle

**Docker Version:**
1.11.2

After adding a custom machine driver, creating a host and then removing that host, purging process is repeated over and over every 2 minutes. Then eventually go-machine-service is restarted and fails to re-activate the driver (showing with "Error" in the UI).

![machine-driver-error](https://cloud.githubusercontent.com/assets/3813921/24571039/205fc088-166f-11e7-9e01-b18c7ea73b85.png)

```
time="2017-03-23T19:20:25Z" level=info msg="Purging Machine" eventId=68a16237-13f0-40dd-8923-718b28e8583c resourceId=1ph5 
time="2017-03-23T19:20:25Z" level=info msg="Extracting /var/lib/cattle/machine/448d361a-a3d4-4989-9e01-c403b782becb/certs" 
time="2017-03-23T19:20:25Z" level=info msg="Extracting /var/lib/cattle/machine/448d361a-a3d4-4989-9e01-c403b782becb/certs/ca-key.pem" 
time="2017-03-23T19:20:25Z" level=info msg="Extracting /var/lib/cattle/machine/448d361a-a3d4-4989-9e01-c403b782becb/certs/ca.pem" 
time="2017-03-23T19:20:25Z" level=info msg="Extracting /var/lib/cattle/machine/448d361a-a3d4-4989-9e01-c403b782becb/certs/cert.pem" 
time="2017-03-23T19:20:25Z" level=info msg="Extracting /var/lib/cattle/machine/448d361a-a3d4-4989-9e01-c403b782becb/certs/key.pem" 
time="2017-03-23T19:20:25Z" level=info msg="Extracting /var/lib/cattle/machine/448d361a-a3d4-4989-9e01-c403b782becb/machines" 
time="2017-03-23T19:20:25Z" level=info msg="Extracting /var/lib/cattle/machine/448d361a-a3d4-4989-9e01-c403b782becb/machines/host0815" 
time="2017-03-23T19:20:25Z" level=info msg="Extracting /var/lib/cattle/machine/448d361a-a3d4-4989-9e01-c403b782becb/machines/host0815/bootstrapped" 
time="2017-03-23T19:20:25Z" level=info msg="Extracting /var/lib/cattle/machine/448d361a-a3d4-4989-9e01-c403b782becb/machines/host0815/ca.pem" 
time="2017-03-23T19:20:25Z" level=info msg="Extracting /var/lib/cattle/machine/448d361a-a3d4-4989-9e01-c403b782becb/machines/host0815/cert.pem" 
time="2017-03-23T19:20:25Z" level=info msg="Extracting /var/lib/cattle/machine/448d361a-a3d4-4989-9e01-c403b782becb/machines/host0815/config.json" 
time="2017-03-23T19:20:25Z" level=info msg="Extracting /var/lib/cattle/machine/448d361a-a3d4-4989-9e01-c403b782becb/machines/host0815/created" 
time="2017-03-23T19:20:25Z" level=info msg="Extracting /var/lib/cattle/machine/448d361a-a3d4-4989-9e01-c403b782becb/machines/host0815/id_rsa" 
time="2017-03-23T19:20:25Z" level=info msg="Extracting /var/lib/cattle/machine/448d361a-a3d4-4989-9e01-c403b782becb/machines/host0815/id_rsa.pub" 
time="2017-03-23T19:20:25Z" level=info msg="Extracting /var/lib/cattle/machine/448d361a-a3d4-4989-9e01-c403b782becb/machines/host0815/key.pem" 
time="2017-03-23T19:20:25Z" level=info msg="Extracting /var/lib/cattle/machine/448d361a-a3d4-4989-9e01-c403b782becb/machines/host0815/server-key.pem" 
time="2017-03-23T19:20:25Z" level=info msg="Extracting /var/lib/cattle/machine/448d361a-a3d4-4989-9e01-c403b782becb/machines/host0815/server.pem" 
time="2017-03-23T19:21:26Z" level=info msg="Machine purged" machineDir="/var/lib/cattle/machine/448d361a-a3d4-4989-9e01-c403b782becb" machineExternalId=448d361a-a3d4-4989-9e01-c403b782becb resourceId=1ph5 
time="2017-03-23T19:23:10Z" level=info msg="Purging Machine" eventId=4589985c-7635-4e1c-9b2c-dd9b74917141 resourceId=1ph5 
time="2017-03-23T19:23:10Z" level=info msg="Extracting /var/lib/cattle/machine/448d361a-a3d4-4989-9e01-c403b782becb/certs" 
time="2017-03-23T19:23:10Z" level=info msg="Extracting /var/lib/cattle/machine/448d361a-a3d4-4989-9e01-c403b782becb/certs/ca-key.pem" 
time="2017-03-23T19:23:10Z" level=info msg="Extracting /var/lib/cattle/machine/448d361a-a3d4-4989-9e01-c403b782becb/certs/ca.pem" 
time="2017-03-23T19:23:10Z" level=info msg="Extracting /var/lib/cattle/machine/448d361a-a3d4-4989-9e01-c403b782becb/certs/cert.pem" 
time="2017-03-23T19:23:10Z" level=info msg="Extracting /var/lib/cattle/machine/448d361a-a3d4-4989-9e01-c403b782becb/certs/key.pem" 
time="2017-03-23T19:23:10Z" level=info msg="Extracting /var/lib/cattle/machine/448d361a-a3d4-4989-9e01-c403b782becb/machines" 
time="2017-03-23T19:23:10Z" level=info msg="Extracting /var/lib/cattle/machine/448d361a-a3d4-4989-9e01-c403b782becb/machines/host0815" 
time="2017-03-23T19:23:10Z" level=info msg="Extracting /var/lib/cattle/machine/448d361a-a3d4-4989-9e01-c403b782becb/machines/host0815/bootstrapped" 
time="2017-03-23T19:23:10Z" level=info msg="Extracting /var/lib/cattle/machine/448d361a-a3d4-4989-9e01-c403b782becb/machines/host0815/ca.pem" 
time="2017-03-23T19:23:10Z" level=info msg="Extracting /var/lib/cattle/machine/448d361a-a3d4-4989-9e01-c403b782becb/machines/host0815/cert.pem" 
time="2017-03-23T19:23:10Z" level=info msg="Extracting /var/lib/cattle/machine/448d361a-a3d4-4989-9e01-c403b782becb/machines/host0815/config.json" 
time="2017-03-23T19:23:10Z" level=info msg="Extracting /var/lib/cattle/machine/448d361a-a3d4-4989-9e01-c403b782becb/machines/host0815/created" 
time="2017-03-23T19:23:10Z" level=info msg="Extracting /var/lib/cattle/machine/448d361a-a3d4-4989-9e01-c403b782becb/machines/host0815/id_rsa" 
time="2017-03-23T19:23:10Z" level=info msg="Extracting /var/lib/cattle/machine/448d361a-a3d4-4989-9e01-c403b782becb/machines/host0815/id_rsa.pub" 
time="2017-03-23T19:23:10Z" level=info msg="Extracting /var/lib/cattle/machine/448d361a-a3d4-4989-9e01-c403b782becb/machines/host0815/key.pem" 
time="2017-03-23T19:23:10Z" level=info msg="Extracting /var/lib/cattle/machine/448d361a-a3d4-4989-9e01-c403b782becb/machines/host0815/server-key.pem" 
time="2017-03-23T19:23:10Z" level=info msg="Extracting /var/lib/cattle/machine/448d361a-a3d4-4989-9e01-c403b782becb/machines/host0815/server.pem" 
time="2017-03-23T19:24:11Z" level=info msg="Machine purged" machineDir="/var/lib/cattle/machine/448d361a-a3d4-4989-9e01-c403b782becb" machineExternalId=448d361a-a3d4-4989-9e01-c403b782becb resourceId=1ph5 
time="2017-03-23T19:25:55Z" level=info msg="Purging Machine" eventId=73d1dc30-6952-4f5e-ae7a-94598a8d2b4f resourceId=1ph5 
time="2017-03-23T19:25:55Z" level=info msg="Extracting /var/lib/cattle/machine/448d361a-a3d4-4989-9e01-c403b782becb/certs" 
time="2017-03-23T19:25:55Z" level=info msg="Extracting /var/lib/cattle/machine/448d361a-a3d4-4989-9e01-c403b782becb/certs/ca-key.pem" 
time="2017-03-23T19:25:55Z" level=info msg="Extracting /var/lib/cattle/machine/448d361a-a3d4-4989-9e01-c403b782becb/certs/ca.pem" 
time="2017-03-23T19:25:55Z" level=info msg="Extracting /var/lib/cattle/machine/448d361a-a3d4-4989-9e01-c403b782becb/certs/cert.pem" 
time="2017-03-23T19:25:55Z" level=info msg="Extracting /var/lib/cattle/machine/448d361a-a3d4-4989-9e01-c403b782becb/certs/key.pem" 
time="2017-03-23T19:25:55Z" level=info msg="Extracting /var/lib/cattle/machine/448d361a-a3d4-4989-9e01-c403b782becb/machines" 
time="2017-03-23T19:25:55Z" level=info msg="Extracting /var/lib/cattle/machine/448d361a-a3d4-4989-9e01-c403b782becb/machines/host0815" 
time="2017-03-23T19:25:55Z" level=info msg="Extracting /var/lib/cattle/machine/448d361a-a3d4-4989-9e01-c403b782becb/machines/host0815/bootstrapped" 
time="2017-03-23T19:25:55Z" level=info msg="Extracting /var/lib/cattle/machine/448d361a-a3d4-4989-9e01-c403b782becb/machines/host0815/ca.pem" 
time="2017-03-23T19:25:55Z" level=info msg="Extracting /var/lib/cattle/machine/448d361a-a3d4-4989-9e01-c403b782becb/machines/host0815/cert.pem" 
time="2017-03-23T19:25:55Z" level=info msg="Extracting /var/lib/cattle/machine/448d361a-a3d4-4989-9e01-c403b782becb/machines/host0815/config.json" 
time="2017-03-23T19:25:55Z" level=info msg="Extracting /var/lib/cattle/machine/448d361a-a3d4-4989-9e01-c403b782becb/machines/host0815/created" 
time="2017-03-23T19:25:55Z" level=info msg="Extracting /var/lib/cattle/machine/448d361a-a3d4-4989-9e01-c403b782becb/machines/host0815/id_rsa" 
time="2017-03-23T19:25:55Z" level=info msg="Extracting /var/lib/cattle/machine/448d361a-a3d4-4989-9e01-c403b782becb/machines/host0815/id_rsa.pub" 
time="2017-03-23T19:25:55Z" level=info msg="Extracting /var/lib/cattle/machine/448d361a-a3d4-4989-9e01-c403b782becb/machines/host0815/key.pem" 
time="2017-03-23T19:25:55Z" level=info msg="Extracting /var/lib/cattle/machine/448d361a-a3d4-4989-9e01-c403b782becb/machines/host0815/server-key.pem" 
time="2017-03-23T19:25:55Z" level=info msg="Extracting /var/lib/cattle/machine/448d361a-a3d4-4989-9e01-c403b782becb/machines/host0815/server.pem" 
time="2017-03-23T19:26:56Z" level=info msg="Machine purged" machineDir="/var/lib/cattle/machine/448d361a-a3d4-4989-9e01-c403b782becb" machineExternalId=448d361a-a3d4-4989-9e01-c403b782becb resourceId=1ph5 
time="2017-03-23T19:28:40Z" level=info msg="Purging Machine" eventId=993fbb94-79f7-4bef-a4ab-7ecd8e0f94f7 resourceId=1ph5
```

After some time the go-machine-service will be restarted at which point it fails to activate the machine driver with `"Failed to download/install driver foo: open /usr/local/bin/docker-machine-driver-foo: text file busy"`

```
time="2017-03-27T19:31:45Z" level=info msg="Purging Machine" eventId=77cb4b31-0078-4065-b03f-3fed09b8c10c resourceId=1ph6 
time="2017-03-27T19:31:45Z" level=info msg="Extracting /var/lib/cattle/machine/b17b3064-3613-4bec-9b5e-33f0131dda52/certs" 
time="2017-03-27T19:31:45Z" level=info msg="Extracting /var/lib/cattle/machine/b17b3064-3613-4bec-9b5e-33f0131dda52/certs/ca-key.pem" 
time="2017-03-27T19:31:45Z" level=info msg="Extracting /var/lib/cattle/machine/b17b3064-3613-4bec-9b5e-33f0131dda52/certs/ca.pem" 
time="2017-03-27T19:31:45Z" level=info msg="Extracting /var/lib/cattle/machine/b17b3064-3613-4bec-9b5e-33f0131dda52/certs/cert.pem" 
time="2017-03-27T19:31:45Z" level=info msg="Extracting /var/lib/cattle/machine/b17b3064-3613-4bec-9b5e-33f0131dda52/certs/key.pem" 
time="2017-03-27T19:31:45Z" level=info msg="Extracting /var/lib/cattle/machine/b17b3064-3613-4bec-9b5e-33f0131dda52/machines" 
time="2017-03-27T19:31:45Z" level=info msg="Extracting /var/lib/cattle/machine/b17b3064-3613-4bec-9b5e-33f0131dda52/machines/host0815" 
time="2017-03-27T19:31:45Z" level=info msg="Extracting /var/lib/cattle/machine/b17b3064-3613-4bec-9b5e-33f0131dda52/machines/host0815/bootstrapped" 
time="2017-03-27T19:31:45Z" level=info msg="Extracting /var/lib/cattle/machine/b17b3064-3613-4bec-9b5e-33f0131dda52/machines/host0815/ca.pem" 
time="2017-03-27T19:31:45Z" level=info msg="Extracting /var/lib/cattle/machine/b17b3064-3613-4bec-9b5e-33f0131dda52/machines/host0815/cert.pem" 
time="2017-03-27T19:31:45Z" level=info msg="Extracting /var/lib/cattle/machine/b17b3064-3613-4bec-9b5e-33f0131dda52/machines/host0815/config.json" 
time="2017-03-27T19:31:45Z" level=info msg="Extracting /var/lib/cattle/machine/b17b3064-3613-4bec-9b5e-33f0131dda52/machines/host0815/created" 
time="2017-03-27T19:31:45Z" level=info msg="Extracting /var/lib/cattle/machine/b17b3064-3613-4bec-9b5e-33f0131dda52/machines/host0815/id_rsa" 
time="2017-03-27T19:31:45Z" level=info msg="Extracting /var/lib/cattle/machine/b17b3064-3613-4bec-9b5e-33f0131dda52/machines/host0815/id_rsa.pub" 
time="2017-03-27T19:31:45Z" level=info msg="Extracting /var/lib/cattle/machine/b17b3064-3613-4bec-9b5e-33f0131dda52/machines/host0815/key.pem" 
time="2017-03-27T19:31:45Z" level=info msg="Extracting /var/lib/cattle/machine/b17b3064-3613-4bec-9b5e-33f0131dda52/machines/host0815/server-key.pem" 
time="2017-03-27T19:31:45Z" level=info msg="Extracting /var/lib/cattle/machine/b17b3064-3613-4bec-9b5e-33f0131dda52/machines/host0815/server.pem" 
time="2017-03-27T19:32:13Z" level=info msg="Exiting go-machine-service" 
time="2017-03-27T19:32:13Z" level=info msg="Exiting rancher-compose-executor" version=v0.13.1 
time="2017-03-27T19:32:15Z" level=info msg="Setting log level" logLevel=info 
time="2017-03-27T19:32:15Z" level=info msg="Starting go-machine-service..." gitcommit=v0.36.1 
time="2017-03-27T19:32:15Z" level=info msg="Waiting for handler registration (1/2)" 
time="2017-03-27T19:32:15Z" level=info msg="Starting rancher-compose-executor" version=v0.13.1 
time="2017-03-27T19:32:16Z" level=info msg="Initializing event router" workerCount=10 
time="2017-03-27T19:32:16Z" level=info msg="Connection established" 
time="2017-03-27T19:32:16Z" level=info msg="Starting websocket pings" 
time="2017-03-27T19:32:16Z" level=info msg="Initializing event router" workerCount=10 
time="2017-03-27T19:32:16Z" level=info msg="Connection established" 
time="2017-03-27T19:32:16Z" level=info msg="Starting websocket pings" 
time="2017-03-27T19:32:16Z" level=info msg="Waiting for handler registration (2/2)" 
time="2017-03-27T19:32:16Z" level=info msg="Initializing event router" workerCount=250 
time="2017-03-27T19:32:16Z" level=info msg="Connection established" 
time="2017-03-27T19:32:16Z" level=info msg="Starting websocket pings" 
time="2017-03-27T19:32:16Z" level=info msg="Installing builtin drivers" 
time="2017-03-27T19:32:16Z" level=info msg="Downloading all drivers" 
time="2017-03-27T19:32:16Z" level=error msg="Failed to download/install driver foo: open /usr/local/bin/docker-machine-driver-foo: text file busy" 
time="2017-03-27T19:32:16Z" level=info msg="Done downloading all drivers" 
time="2017-03-27T19:32:16Z" level=info msg=Event eventId=f28f0dfa-85ab-4ebc-8fb5-77581284caf8 name="machinedriver.reactivate;handler=goMachineService-machine" resourceId=1md14 
time="2017-03-27T19:32:16Z" level=error msg="Error processing event" err="open /usr/local/bin/docker-machine-driver-foo: text file busy" eventId=f28f0dfa-85ab-4ebc-8fb5-77581284caf8 eventName="machinedriver.reactivate;handler=goMachineService-machine" resourceId=1md14 
2017-03-27 19:32:16,612 ERROR [a3ab5bb8-c5f5-4fd1-9254-82ad80c6e81c:2918] [machineDriver:14] [machinedriver.reactivate] [] [cutorService-52] [c.p.e.p.i.DefaultProcessInstanceImpl] Agent error for [machinedriver.reactivate.reply;handler=goMachineService-machine]: open /usr/local/bin/docker-machine-driver-foo: text file busy 
2017-03-27 19:32:16,618 ERROR [:] [] [] [] [cutorService-52] [.e.s.i.ProcessInstanceDispatcherImpl] Agent error for [machinedriver.reactivate.reply;handler=goMachineService-machine]: open /usr/local/bin/docker-machine-driver-foo: text file busy 
time="2017-03-27T19:32:16Z" level=info msg=Event eventId=75043327-75e6-4509-bda8-240c30f13396 name="machinedriver.error;handler=goMachineService-machine" resourceId=1md14 
time="2017-03-27T19:32:46Z" level=info msg="Shutting down backend 2f0055d3-5373-44de-7b26-32e82b3b499c. Connection closed because: websocket: close 1006 unexpected EOF." 
time="2017-03-27T19:32:46Z" level=info msg="Removed backend. Key: 2f0055d3-5373-44de-7b26-32e82b3b499c. Session ID 2155ba6c-e046-44dc-a46c-9b470a7984ae ." 
time="2017-03-27T19:32:51Z" level=info msg="Handling backend connection request." 
time="2017-03-27T19:32:51Z" level=info msg="Registering backend for host 2f0055d3-5373-44de-7b26-32e82b3b499c with session ID 22e669c9-c870-490d-88b7-1f9f37eaf655." 
```

**Comment by cjellick** [comment] 2017-04-27 03:04
There are two issues here: purge not completing and the driver not reinstalling properly. This comment will address the purge not completing issue

The driver in question apparently is always taking a full minute to complete the "purge" cycle. The purge cycle consists of:
1. Extracting the config for the machine (you can see in the logs that this takes less than a second)
2. calling docker-machine ls -q to determine if the machine being purged exists
3. If the machine exists, calling docker-machine rm -f

The logs indicate that the total time is always over a minute:
```
time="2017-03-23T19:20:25Z" level=info msg="Purging Machine" eventId=68a16237-13f0-40dd-8923-718b28e8583c resourceId=1ph5 
time="2017-03-23T19:21:26Z" level=info msg="Machine purged" machineDir="/var/lib/cattle/machine/448d361a-a3d4-4989-9e01-c403b782becb" machineExternalId=448d361a-a3d4-4989-9e01-c403b782becb resourceId=1ph5 
```
Now, we don't know if that time is being chewed up by the `docker-machine ls` command or the `docker-machine rm` command, but the expected behavior is for `ls` to _eventually_ return in under 15 seconds. Its ok if `rm` takes a long time when it is initially deleting the machine because that event will timeout on the cattle side in 15 seconds and eventually be resent. When it is resent, the machine should have been deleted and ls should have returned quickly.

Its possible that somehow this is caused by the driver itself being in a weird state and docker-machine trying for a minute to contact it and then giving up, but I'd expect that to error out. Still we can rule it out.
On the other hand, it could be caused by a bug in either the driver itself or the cloud that the driver is talking to such that either `ls` or `rm` or both is taking over a minute.
@janeczku could you confirm from the command line (using docker-machine directly, not rancher) that docker-machine ls and docker-machine rm completes successfully and under a minute for this particular driver?

**Comment by janeczku** [comment] 2017-04-27 17:55
@cjellick the time is chewed up by the drivers `remove` method. It uses a 1 minute sleep to check the result of the API remove operation before returning. But why is it trying to remove the same machine over and over again? Is that maybe because `docker-machine rm` returned an error that we just don't see in the logs?

Driver here: https://github.com/Huawei/DockerMachineDriver4OTC/blob/54469b9c30dc41df3d0b7ac0eb47bba99b0b2866/otc/ecs.go#L580

**Comment by cjellick** [comment] 2017-04-27 18:00
@janeczku yes, that's my question as well: why is it trying to remove the machine over and over again. If it removed successfully once, then the ls should indicate it is not there and we should circuit.

Could either be a bug in the driver not communicating an error properly or in our remove logic such that errors are not propagated properly.

I'll see if I can force an error in a driver to see what happens.

**Comment by deniseschannon** [comment] 2017-05-03 19:05
Moving to v1.7.0 so that the customer with custom machine driver can test and verify for us.

**Comment by deniseschannon** [comment] 2017-07-17 20:16
@janeczku If a customer hits this with v1.6.0 or above, please re-open.

**Closed by deniseschannon** 2017-07-17 20:16 UTC
Labels: area/machine, kind/bug, status/resolved, status/to-test
