### ISSUE TITLE
Healthcheck container DNS lookup fails

### ISSUE THREAD

**Issue by HardcorEViruS** [rancher/rancher#9226] opened 2017-07-03 16:27 UTC
Sometimes the rancher healthcheck container fails to resolve the IP of the rancher-metadata service which resolves in unhealthy containers not being recognized as such and not being restarted.
Example from within the healthchek container:

```
root@3a323cfd8ff0:/# ping rancher-metadata
ping: unknown host rancher-metadata
```

When this happens, there seems to be no connection to the DNS server at all as neither internal nor external (like google) addresses are resolvable. This also applies to the ipsec containers of Rancher on the same host.

After restarting the DNS service (metadata-dns-*), everything works just fine. This seems to happen regardless of hardware or docker version as:
* a restart fixes the problem (at least temporarily)
* and on another host with the same hard- and software at the same time it works just fine.

It seems to happen from time to time (timeframe of 1-2 hours) on different hosts and without restarting any containers. But I was not able to find a pettern yet.

Here is the resolv.conf of a affected host (although it's the same on the working hosts too):

> search  healthcheck.rancher.internal healthcheck.healthcheck.rancher.internal rancher.internal local
> nameserver 169.254.169.250
---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v1.6.0` Cattle: `v0.179.7` UI: `v1.6.1` Docker: `17.03.1-ce` OS: `Ubuntu 14.04.5 LTS` |
|Access|`localauth` `admin`|
|Orchestration|`Cattle`|
|Route|`hosts.index`|

**Comment by aemneina** [comment] 2017-07-03 16:46
We're targeting fixes for metadata with #9123 . The idea is that metadata should reconnect when it loses connection with the rancher server... there are some cases it tries but fails and stops retrying.

**Comment by aemneina** [comment] 2017-07-03 17:43
@HardcorEViruS when this happens next on your metadata container can you get a thread dump? Doing a `kill -3 1` from within the metadata container should get it to dump to logs then post that... that way we can check if your condition would be covered by the fix.

**Comment by HardcorEViruS** [comment] 2017-07-03 18:17
As it's a lot of output I put it to [Pastebin](https://pastebin.com/dLzMr1dW).

**Comment by HardcorEViruS** [comment] 2017-07-03 18:25
It just happened again. But this time restarting the DNS service didn't help, but restarting the healthcheck service did.

**Comment by janeczku** [comment] 2017-07-04 15:09
@aemneina possibly a duplicate of https://github.com/rancher/rancher/issues/8723

**Comment by loganhz** [comment] 2018-10-05 08:39
Please let us know in a comment if you can still reproduce the issue, and we'll reopen it

**Closed by loganhz** 2018-10-05 08:39 UTC
Labels: area/metadata, area/networking, kind/bug
