### ISSUE TITLE
Dashboard can be slow listing many large resources

### ISSUE THREAD

**Issue by nickgerace** [rancher/rancher#34721] opened 2021-09-14 14:57 UTC
Reproduction steps: https://github.com/rancher/rancher/issues/30718#issuecomment-819560445
Related issue(s): https://github.com/rancher/rancher/issues/30718

SURE-3010

**Comment by aiyengar2** [comment] 2021-09-15 20:34
@paynejacob assigning this to you since you're working on https://github.com/rancher/rancher/issues/30718, which identifies the same root problem.

**Comment by vincent99** [comment] 2021-10-15 02:51
The behavior described was a UI issue fixed in 2.6.1; any changes made to the backend to make it handle many requests better are incidental, because those requests won't be getting made in the first place anymore.

**Comment by paynejacob** [comment] 2021-11-04 18:20
waiting on https://github.com/rancher/dashboard/issues/4512

**Comment by paynejacob** [comment] 2021-11-04 18:27
To test this  we should generate ~200 secrets and 200 configmaps with ~125KB of data each to reproduce the excessive response times. Given this solution changes how both the backend and frontend handle listing resources I do not have a quantitative description of the improvement but we should check that it does not break any resource listing and that is noticeably faster listing many resources.

cc: @sgapanovich

**Comment by paynejacob** [comment] 2021-11-10 17:57
### Root cause
the backend was inefficently serializing large results
 
### What was fixed, or what changes have occurred
the api now supports a new content type that allows the dashboard to consume results before all results are finished being processed
 
### Areas or cases that should be tested
To test this we should generate ~200 secrets and 200 configmaps with ~125KB of data each to reproduce the excessive response times. Given this solution changes how both the backend and frontend handle listing resources I do not have a quantitative description of the improvement but we should check that it does not break any resource listing and that is noticeably faster listing many resources.
 
### What areas could experience regressions?
Any page that lists resources
 
### Are the repro steps accurate/minimal?
Yes

**Comment by sgapanovich** [comment] 2021-11-15 17:50
#### Test Environment: ####
Rancher version: v2.6-78b25c3
Rancher cluster type: HA
Docker version: 20.10

Downstream cluster type: ec2 (two clusters: 3 nodes and 8 nodes)
Downstream K8s version: v1.21.6 
----------

#### Testing: ####
To make sure that API responses return correct information when `application/jsonl` is requested the following API endpoints where tested (see the list below) 
Testing included: 
- making two api calls 
  - accept:  `application/jsonl`
  - accept: `application/json`
- comparing the following from responses:
  - beginning of the responses
  - ending of the responses 
  - data object randomly selected to be compared from both responses:
      - let's say deployments API returned 12 deployments objects I would take a random one from both responses (with jsonl and with json) and compare them using compare tool to validate that the data is the same![compare.jpg](https://zube.io/files/rancher/22d06eb282758fa64f93edd98f43319d-compare.jpg)

How the data is displayed on UI (correctness) is tested here: https://github.com/rancher/dashboard/issues/4512
I didn't see any data missing or being incorrect in any of the API responses when using the new content type 

```
/v1/provisioning.cattle.io.clusters
/v1/management.cattle.io.setting
/v1/management.cattle.io.cluster
/v1/management.cattle.io.clusters
/v1/management.cattle.io.features
/v1/management.cattle.io.nodes
/v1/management.cattle.io.nodepools
/v1/management.cattle.io.nodetemplates
/v1/management.cattle.io.projects
/v1/management.cattle.io.clusterroletemplatebindings
/v1/management.cattle.io.users
/v1/management.cattle.io.roletemplates
/v1/management.cattle.io.podsecuritypolicytemplates
/v1/management.cattle.io.nodedrivers
/v1/management.cattle.io.fleetworkspaces
/v1/cluster.x-k8s.io.machinedeployments
/v1/cluster.x-k8s.io.machinesets
/v1/cluster.x-k8s.io.machines
/v1/fleet.cattle.io.clusters
/v1/fleet.cattle.io.clustergroups
/v1/fleet.cattle.io.gitrepos
/v1/fleet.cattle.io.bundles
/v1/management.cattle.io.project/{{CLUSTER}}
/k8s/clusters/{{CLUSTER}}/v1/counts
/k8s/clusters/{{CLUSTER}}/v1/namespaces
/k8s/clusters/{{CLUSTER}}/v1/nodes
/k8s/clusters/{{CLUSTER}}/v1/events
/k8s/clusters/{{CLUSTER}}/v1/apps.daemonsets
/k8s/clusters/{{CLUSTER}}/v1/apps.deployments
/k8s/clusters/{{CLUSTER}}/v1/apps.statefulsets
/k8s/clusters/{{CLUSTER}}/v1/apps.replicasets
/k8s/clusters/{{CLUSTER}}/v1/batch.jobs
/k8s/clusters/{{CLUSTER}}/v1/batch.cronjobs
/k8s/clusters/{{CLUSTER}}/v1/pods
/k8s/clusters/{{CLUSTER}}/v1/services
/k8s/clusters/{{CLUSTER}}/v1/replicationcontrollers
/k8s/clusters/{{CLUSTER}}/v1/persistentvolumeclaims
/k8s/clusters/{{CLUSTER}}/v1/persistentvolumes
/k8s/clusters/{{CLUSTER}}/v1/configmaps
/k8s/clusters/{{CLUSTER}}/v1/secrets
/k8s/clusters/{{CLUSTER}}/v1/endpoints
/k8s/clusters/{{CLUSTER}}/v1/serviceaccounts
/k8s/clusters/{{CLUSTER}}/v1/ui.cattle.io.navlinks
/k8s/clusters/{{CLUSTER}}/v1/metrics.k8s.io.nodes
/k8s/clusters/{{CLUSTER}}/v1/catalog.cattle.io.clusterrepos
/k8s/clusters/{{CLUSTER}}/v1/catalog.cattle.io.apps
/k8s/clusters/{{CLUSTER}}/v1/catalog.cattle.io.operations
/k8s/clusters/{{CLUSTER}}/v1/autoscaling.horizontalpodautoscalers
/k8s/clusters/{{CLUSTER}}/v1/networking.k8s.io.ingresses
/k8s/clusters/{{CLUSTER}}/v1/networking.k8s.io.networkpolicies
/k8s/clusters/{{CLUSTER}}/v1/storage.k8s.io.storageclasses
/k8s/clusters/{{CLUSTER}}/v1/admissionregistration.k8s.io.validatingwebhookconfigurations
/k8s/clusters/{{CLUSTER}}/v1/apiextensions.k8s.io.customresourcedefinitions
/k8s/clusters/{{CLUSTER}}/v1/flowcontrol.apiserver.k8s.io.flowschemas
/k8s/clusters/{{CLUSTER}}/v1/apps.controllerrevisions
/k8s/clusters/{{CLUSTER}}/v1/crd.projectcalico.org.clusterinformations
/k8s/clusters/{{CLUSTER}}/v1/crd.projectcalico.org.felixconfigurations
/k8s/clusters/{{CLUSTER}}/v1/crd.projectcalico.org.ippools
/k8s/clusters/{{CLUSTER}}/v1/crd.projectcalico.org.kubecontrollersconfigurations
/k8s/clusters/{{CLUSTER}}/v1/cluster.cattle.io.clusterauthtokens
/k8s/clusters/{{CLUSTER}}/v1/cluster.cattle.io.clusteruserattributes
/k8s/clusters/{{CLUSTER}}/v1/coordination.k8s.io.leases
/k8s/clusters/{{CLUSTER}}/v1/discovery.k8s.io.endpointslices
/k8s/clusters/{{CLUSTER}}/v1/policy.poddisruptionbudgets
/k8s/clusters/{{CLUSTER}}/v1/management.cattle.io.authconfigs
/k8s/clusters/{{CLUSTER}}/v1/rbac.authorization.k8s.io.clusterrolebindings
/k8s/clusters/{{CLUSTER}}/v1/rbac.authorization.k8s.io.clusterroles
/k8s/clusters/{{CLUSTER}}/v1/rbac.authorization.k8s.io.rolebindings
/k8s/clusters/{{CLUSTER}}/v1/rbac.authorization.k8s.io.roles
/k8s/clusters/{{CLUSTER}}/v1/scheduling.k8s.io.priorityclasses
/k8s/clusters/{{CLUSTER}}/v1/storage.k8s.io.csinodes
/k8s/clusters/{{CLUSTER}}/v1/storage.k8s.io.storageclasses
```

----

Performance: 
There is a noticeable improvement for ConfigMaps and Secrets (not so much for other areas of the system)
![150.jpg](https://zube.io/files/rancher/94d670e9989c234a63fbd17aa6382cca-150.jpg)![500.jpg](https://zube.io/files/rancher/3fe8c848ace8751f7a74327613481027-500.jpg)

**Closed** 2021-11-15 17:50 UTC
Labels: [zube]: Done, QA/M
