### ISSUE TITLE
[2.5 backport] istio Hardened Cluster Support - CIS scan should pass

### ISSUE THREAD

**Issue by cbron** [rancher/rancher#33174] opened 2021-06-13 23:16 UTC
https://github.com/rancher/rancher/issues/29076

**Comment by dhruvmewada15** [comment] 2022-02-08 14:25
**Steps followed:**

- Rancher Server: 2.5.12
- Created a 3 node single role downstream hardened cluster (1 cp, 1 etcd, 1 worker)
- Installed Monitoring chart from Apps and Marketplace : 16.6.1+up16.6.0
- Installed Istio chart from Apps and Marketplace : 1.10.400
- Set `automountServiceAccountToken: false` on `default` serviceaccount in istio-system namespace OR  `default` serviceaccount in any other namespace created after running the account_update.sh. This is a hardened cluster [requirement](https://rancher.com/docs/rancher/v2.5/en/security/rancher-2.5/1.6-hardening-2.5/). 
- Installed CIS Benchmark chart from Apps and Marketplace : 1.0.600
- Run CIS Scan with profile `rke-profile-hardened-1.6`


**Result:**
The CIS Scan PASSED successfully. The issue is not Active

>  "If you're seeing a failure related to `automountServiceAccountToken: false`, then make sure to run the [account_update.sh](https://rancher.com/docs/rancher/v2.5/en/security/rancher-2.5/1.6-hardening-2.5/) _[This is the script which updates `automountServiceAccountToken: false` on default serviceaccount in all the namespaces]_ before you run the CIS Scan."

**Comment by vivek-infracloud** [comment] 2022-02-10 06:52
**Validated on rancher v2.5.12** 

Steps followed to validate the issue.

1. Created rancher server v2.5.12
2. Created a 3 node single role downstream **hardened cluster** (1 cp, 1 etcd, 1 worker). Followed [this](https://rancher.com/docs/rancher/v2.5/en/security/rancher-2.5/1.6-hardening-2.5/) hardening guide.

- > Make sure worker node amounts to more than 6 CPUs.
3. Installed Monitoring chart from Apps and Marketplace : 16.6.1+up16.6.0
4. Installed Istio chart from Apps and Marketplace : 1.10.400
5. Made sure the Default serviceaccounts in all the name spaces has `automountServiceAccountToken` set to `false`.
6. Installed CIS Benchmark chart from Apps and Marketplace : 1.0.600
7. Ran CIS Scan with profile `rke-profile-hardened-1.6`

**Result:**
**The CIS Scan PASSED successfully.**

**Comment by vivek-infracloud** [comment] 2022-02-10 06:52
Based on above validation, the issue is not active. Hence, closing the issue.

**Closed by vivek-infracloud** 2022-02-10 06:52 UTC
Labels: [zube]: QA Working, team/area3, team/infracloud
