### ISSUE TITLE
Kubernetes rc, pods are lost after turning off and turning on the host

### ISSUE THREAD

**Issue by soumyalj** [rancher/rancher#5258] opened 2016-06-27 21:48 UTC
**Rancher Version:**: Master

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**: Kubernetes

**Steps to Reproduce:**
1. Create a Kubernetes environment with 4 hosts. Use library qa-catalog: https://github.com/rancher/qa-catalog/
2. Create pods, rc
3. Turn off the host on which the pods, etcd exist. The etcd gets created on another host
4. Turn on the host which was switched off in step 3. 

**Results:** 
The pods, rc, service are all lost.  kubectl get rc does not return anything
```
> kubectl get rc
>
```
kubectl get nodes returns only one host instead of 4
```
> kubectl get nodes
NAME                       STATUS    AGE
soumyamasterkubeenvhost1   Ready     36m
```
The following errors are seen in the controller manager:
```
6/27/2016 2:18:42 PMI0627 21:18:42.193864       1 rancher.go:534] ExternalID [soumyamasterkubeenvhost1]
6/27/2016 2:18:42 PMI0627 21:18:42.193973       1 rancher.go:540] InstanceID [soumyamasterkubeenvhost1]
6/27/2016 2:18:47 PMI0627 21:18:47.309505       1 rancher.go:534] ExternalID [soumyamasterkubeenvhost1]
6/27/2016 2:18:47 PMI0627 21:18:47.309603       1 rancher.go:540] InstanceID [soumyamasterkubeenvhost1]
6/27/2016 2:18:52 PMI0627 21:18:52.383838       1 rancher.go:534] ExternalID [soumyamasterkubeenvhost1]
6/27/2016 2:18:52 PMI0627 21:18:52.383865       1 rancher.go:540] InstanceID [soumyamasterkubeenvhost1]
6/27/2016 2:18:57 PMI0627 21:18:57.459911       1 rancher.go:534] ExternalID [soumyamasterkubeenvhost1]
6/27/2016 2:18:57 PMI0627 21:18:57.459941       1 rancher.go:540] InstanceID [soumyamasterkubeenvhost1]
6/27/2016 2:19:02 PMI0627 21:19:02.538104       1 rancher.go:534] ExternalID [soumyamasterkubeenvhost1]
6/27/2016 2:19:02 PMI0627 21:19:02.538136       1 rancher.go:540] InstanceID [soumyamasterkubeenvhost1]
6/27/2016 2:19:07 PMI0627 21:19:07.620104       1 rancher.go:534] ExternalID [soumyamasterkubeenvhost1]
6/27/2016 2:19:07 PMI0627 21:19:07.620140       1 rancher.go:540] InstanceID [soumyamasterkubeenvhost1]
6/27/2016 2:19:12 PMI0627 21:19:12.697697       1 nodecontroller.go:478] Evicting pods on node soumyamasterkubeenvhost1: 2016-06-27 21:19:12.697662593 +0000 UTC is later than 2016-06-27 21:14:48.007726723 +0000 UTC + 4m20s
6/27/2016 2:19:12 PMI0627 21:19:12.697904       1 rancher.go:534] ExternalID [soumyamasterkubeenvhost1]
6/27/2016 2:19:12 PMI0627 21:19:12.697923       1 rancher.go:540] InstanceID [soumyamasterkubeenvhost1]
6/27/2016 2:19:12 PMI0627 21:19:12.778646       1 event.go:211] Event(api.ObjectReference{Kind:"Node", Namespace:"", Name:"soumyamasterkubeenvhost1", UID:"soumyamasterkubeenvhost1", APIVersion:"", ResourceVersion:"", FieldPath:""}): type: 'Normal' reason: 'DeletingAllPods' Node soumyamasterkubeenvhost1 event: Deleting all Pods from Node soumyamasterkubeenvhost1.
6/27/2016 2:19:12 PMI0627 21:19:12.778748       1 event.go:211] Event(api.ObjectReference{Kind:"Pod", Namespace:"default", Name:"k8testrc-eaazc", UID:"9ae67bd0-3cab-11e6-a0d5-02e309181521", APIVersion:"v1", ResourceVersion:"289", FieldPath:""}): type: 'Normal' reason: 'NodeControllerEviction' Marking for deletion Pod k8testrc-eaazc from Node soumyamasterkubeenvhost1
6/27/2016 2:19:12 PMI0627 21:19:12.786550       1 event.go:211] Event(api.ObjectReference{Kind:"Pod", Namespace:"default", Name:"k8testrc-qvdsf", UID:"9ae67cfe-3cab-11e6-a0d5-02e309181521", APIVersion:"v1", ResourceVersion:"290", FieldPath:""}): type: 'Normal' reason: 'NodeControllerEviction' Marking for deletion Pod k8testrc-qvdsf from Node soumyamasterkubeenvhost1
6/27/2016 2:19:12 PMI0627 21:19:12.796410       1 event.go:211] Event(api.ObjectReference{Kind:"Pod", Namespace:"default", Name:"k8testrc1-1o6oc", UID:"9843a14f-3caa-11e6-a0d5-02e309181521", APIVersion:"v1", ResourceVersion:"292", FieldPath:""}): type: 'Normal' reason: 'NodeControllerEviction' Marking for deletion Pod k8testrc1-1o6oc from Node soumyamasterkubeenvhost1
6/27/2016 2:19:12 PMI0627 21:19:12.808196       1 event.go:211] Event(api.ObjectReference{Kind:"ReplicationController", Namespace:"default", Name:"k8testrc", UID:"9ae52d58-3cab-11e6-a0d5-02e309181521", APIVersion:"v1", ResourceVersion:"230", FieldPath:""}): type: 'Normal' reason: 'SuccessfulCreate' Created pod: k8testrc-k5b6j
6/27/2016 2:19:12 PME0627 21:19:12.863320       1 nodecontroller.go:251] unable to evict node "soumyamasterkubeenvhost1": pods "k8testrc1-pnxp2" not found
6/27/2016 2:19:12 PMI0627 21:19:12.866573       1 event.go:211] Event(api.ObjectReference{Kind:"ReplicationController", Namespace:"default", Name:"k8testrc", UID:"9ae52d58-3cab-11e6-a0d5-02e309181521", APIVersion:"v1", ResourceVersion:"230", FieldPath:""}): type: 'Normal' reason: 'SuccessfulCreate' Created pod: k8testrc-ffvby
6/27/2016 2:19:12 PMI0627 21:19:12.867099       1 event.go:211] Event(api.ObjectReference{Kind:"ReplicationController", Namespace:"default", Name:"k8testrc1", UID:"9841eca3-3caa-11e6-a0d5-02e309181521", APIVersion:"v1", ResourceVersion:"164", FieldPath:""}): type: 'Normal' reason: 'SuccessfulCreate' Created pod: k8testrc1-pu4xc
6/27/2016 2:19:12 PMI0627 21:19:12.870594       1 event.go:211] Event(api.ObjectReference{Kind:"Pod", Namespace:"default", Name:"k8testrc1-pnxp2", UID:"984376b5-3caa-11e6-a0d5-02e309181521", APIVersion:"v1", ResourceVersion:"294", FieldPath:""}): type: 'Normal' reason: 'NodeControllerEviction' Marking for deletion Pod k8testrc1-pnxp2 from Node soumyamasterkubeenvhost1
6/27/2016 2:19:17 PMI0627 21:19:17.918805       1 event.go:211] Event(api.ObjectReference{Kind:"Node", Namespace:"", Name:"soumyamasterkubeenvhost2", UID:"soumyamasterkubeenvhost2", APIVersion:"", ResourceVersion:"", FieldPath:""}): type: 'Normal' reason: 'RemovingNode' Node soumyamasterkubeenvhost2 event: Removing Node soumyamasterkubeenvhost2 from NodeController
6/27/2016 2:19:17 PMI0627 21:19:17.918885       1 event.go:211] Event(api.ObjectReference{Kind:"Node", Namespace:"", Name:"soumyamasterkubeenvhost1", UID:"soumyamasterkubeenvhost1", APIVersion:"", ResourceVersion:"", FieldPath:""}): type: 'Normal' reason: 'RemovingNode' Node soumyamasterkubeenvhost1 event: Removing Node soumyamasterkubeenvhost1 from NodeController
6/27/2016 2:19:17 PME0627 21:19:17.926438       1 event.go:193] Server rejected event '&api.Event{TypeMeta:unversioned.TypeMeta{Kind:"", APIVersion:""}, ObjectMeta:api.ObjectMeta{Name:"soumyamasterkubeenvhost1.145c0c946160ee5a", GenerateName:"", Namespace:"default", SelfLink:"", UID:"", ResourceVersion:"4", Generation:0, CreationTimestamp:unversioned.Time{Time:time.Time{sec:0, nsec:0, loc:(*time.Location)(nil)}}, DeletionTimestamp:(*unversioned.Time)(nil), DeletionGracePeriodSeconds:(*int64)(nil), Labels:map[string]string(nil), Annotations:map[string]string(nil)}, InvolvedObject:api.ObjectReference{Kind:"Node", Namespace:"", Name:"soumyamasterkubeenvhost1", UID:"soumyamasterkubeenvhost1", APIVersion:"", ResourceVersion:"", FieldPath:""}, Reason:"RemovingNode", Message:"Node soumyamasterkubeenvhost1 event: Removing Node soumyamasterkubeenvhost1 from NodeController", Source:api.EventSource{Component:"controllermanager", Host:""}, FirstTimestamp:unversioned.Time{Time:time.Time{sec:63602658210, nsec:0, loc:(*time.Location)(0x27c2ee0)}}, LastTimestamp:unversioned.Time{Time:time.Time{sec:63602659157, nsec:918771383, loc:(*time.Location)(0x27c2ee0)}}, Count:2, Type:"Normal"}': 'events "soumyamasterkubeenvhost1.145c0c946160ee5a" not found' (will not retry!)
6/27/2016 2:21:03 PMW0627 21:21:03.797749       1 request.go:344] Field selector: v1 - serviceaccounts - metadata.name - default: need to check if this is versioned correctly.
6/27/2016 2:21:38 PMI0627 21:21:38.222995       1 event.go:211] Event(api.ObjectReference{Kind:"Node", Namespace:"", Name:"soumyamasterkubeenvhost1", UID:"soumyamasterkubeenvhost1", APIVersion:"", ResourceVersion:"", FieldPath:""}): type: 'Normal' reason: 'RegisteredNode' Node soumyamasterkubeenvhost1 event: Registered Node soumyamasterkubeenvhost1 in NodeController
6/27/2016 2:21:38 PME0627 21:21:38.225890       1 event.go:193] Server rejected event '&api.Event{TypeMeta:unversioned.TypeMeta{Kind:"", APIVersion:""}, ObjectMeta:api.ObjectMeta{Name:"soumyamasterkubeenvhost1.145c0ba78ceb87a4", GenerateName:"", Namespace:"default", SelfLink:"", UID:"", ResourceVersion:"167", Generation:0, CreationTimestamp:unversioned.Time{Time:time.Time{sec:0, nsec:0, loc:(*time.Location)(nil)}}, DeletionTimestamp:(*unversioned.Time)(nil), DeletionGracePeriodSeconds:(*int64)(nil), Labels:map[string]string(nil), Annotations:map[string]string(nil)}, InvolvedObject:api.ObjectReference{Kind:"Node", Namespace:"", Name:"soumyamasterkubeenvhost1", UID:"soumyamasterkubeenvhost1", APIVersion:"", ResourceVersion:"", FieldPath:""}, Reason:"RegisteredNode", Message:"Node soumyamasterkubeenvhost1 event: Registered Node soumyamasterkubeenvhost1 in NodeController", Source:api.EventSource{Component:"controllermanager", Host:""}, FirstTimestamp:unversioned.Time{Time:time.Time{sec:63602657192, nsec:0, loc:(*time.Location)(0x27c2ee0)}}, LastTimestamp:unversioned.Time{Time:time.Time{sec:63602659298, nsec:222865241, loc:(*time.Location)(0x27c2ee0)}}, Count:3, Type:"Normal"}': 'events "soumyamasterkubeenvhost1.145c0ba78ceb87a4" not found' (will not retry!)
6/27/2016 2:22:58 PMI0627 21:22:58.486792       1 rancher.go:246] EnsureLoadBalancerDeleted [lb-a9ad257d83cab11e6a0d502e30918152] [Region1]
6/27/2016 2:22:58 PMI0627 21:22:58.488526       1 rancher.go:246] EnsureLoadBalancerDeleted [lb-a982eaaaf3caa11e6a0d502e30918152] [Region1]
6/27/2016 2:22:58 PMI0627 21:22:58.491324       1 servicecontroller.go:298] LB doesn't need update for service default/kubernetes
6/27/2016 2:22:58 PMI0627 21:22:58.531447       1 rancher.go:253] Couldn't find LB %!s(MISSING) to delete. Nothing to do.
6/27/2016 2:22:58 PMI0627 21:22:58.555904       1 rancher.go:253] Couldn't find LB %!s(MISSING) to delete. Nothing to do.
6/27/2016 2:27:01 PMW0627 21:27:01.800336       1 request.go:344] Field selector: v1 - serviceaccounts - metadata.name - default: need to check if this is versioned correctly.
6/27/2016 2:27:57 PMI0627 21:27:57.548599       1 servicecontroller.go:298] LB doesn't need update for service default/kubernetes
6/27/2016 2:27:57 PMI0627 21:27:57.554646       1 rancher.go:246] EnsureLoadBalancerDeleted [lb-a982eaaaf3caa11e6a0d502e30918152] [Region1]
6/27/2016 2:27:57 PMI0627 21:27:57.554679       1 rancher.go:246] EnsureLoadBalancerDeleted [lb-a9ad257d83cab11e6a0d502e30918152] [Region1]
6/27/2016 2:27:57 PMI0627 21:27:57.592781       1 rancher.go:253] Couldn't find LB %!s(MISSING) to delete. Nothing to do.
6/27/2016 2:27:57 PMI0627 21:27:57.594016       1 rancher.go:253] Couldn't find LB %!s(MISSING) to delete. Nothing to do.
6/27/2016 2:32:15 PME0627 21:32:15.140970       1 nodecontroller.go:229] Error monitoring node status: an error on the server has prevented the request from succeeding
6/27/2016 2:32:20 PME0627 21:32:20.180593       1 nodecontroller.go:229] Error monitoring node status: an error on the server has prevented the request from succeeding
6/27/2016 2:32:25 PME0627 21:32:25.185610       1 nodecontroller.go:229] Error monitoring node status: an error on the server has prevented the request from succeeding
6/27/2016 2:32:30 PME0627 21:32:30.190949       1 nodecontroller.go:229] Error monitoring node status: an error on the server has prevented the request from succeeding
6/27/2016 2:32:35 PME0627 21:32:35.195768       1 nodecontroller.go:229] Error monitoring node status: an error on the server has prevented the request from succeeding
6/27/2016 2:32:40 PME0627 21:32:40.201274       1 nodecontroller.go:229] Error monitoring node status: an error on the server has prevented the request from succeeding
6/27/2016 2:32:45 PME0627 21:32:45.206197       1 nodecontroller.go:229] Error monitoring node status: an error on the server has prevented the request from succeeding
6/27/2016 2:32:50 PME0627 21:32:50.269782       1 nodecontroller.go:229] Error monitoring node status: an error on the server has prevented the request from succeeding
6/27/2016 2:32:55 PME0627 21:32:55.274530       1 nodecontroller.go:229] Error monitoring node status: an error on the server has prevented the request from succeeding
6/27/2016 2:32:56 PMI0627 21:32:56.499458       1 servicecontroller.go:298] LB doesn't need update for service default/kubernetes
6/27/2016 2:32:56 PMI0627 21:32:56.501571       1 rancher.go:246] EnsureLoadBalancerDeleted [lb-a982eaaaf3caa11e6a0d502e30918152] [Region1]
6/27/2016 2:32:56 PMI0627 21:32:56.509100       1 rancher.go:246] EnsureLoadBalancerDeleted [lb-a9ad257d83cab11e6a0d502e30918152] [Region1]
6/27/2016 2:32:56 PMI0627 21:32:56.536381       1 rancher.go:253] Couldn't find LB %!s(MISSING) to delete. Nothing to do.
6/27/2016 2:32:56 PMI0627 21:32:56.542205       1 rancher.go:253] Couldn't find LB %!s(MISSING) to delete. Nothing to do.
6/27/2016 2:33:00 PME0627 21:33:00.320778       1 nodecontroller.go:229] Error monitoring node status: an error on the server has prevented the request from succeeding
6/27/2016 2:33:45 PME0627 21:33:45.461303       1 nodecontroller.go:229] Error monitoring node status: an error on the server has prevented the request from succeeding
6/27/2016 2:33:50 PME0627 21:33:50.505646       1 nodecontroller.go:229] Error monitoring node status: an error on the server has prevented the request from succeeding
6/27/2016 2:33:55 PME0627 21:33:55.510021       1 nodecontroller.go:229] Error monitoring node status: an error on the server has prevented the request from succeeding
6/27/2016 2:34:00 PME0627 21:34:00.514406       1 nodecontroller.go:229] Error monitoring node status: an error on the server has prevented the request from succeeding
6/27/2016 2:34:34 PMW0627 21:34:34.804222       1 request.go:344] Field selector: v1 - serviceaccounts - metadata.name - default: need to check if this is versioned correctly.
6/27/2016 2:35:35 PME0627 21:35:35.778797       1 nodecontroller.go:229] Error monitoring node status: an error on the server has prevented the request from succeeding
6/27/2016 2:35:40 PME0627 21:35:40.823169       1 nodecontroller.go:229] Error monitoring node status: an error on the server has prevented the request from succeeding
6/27/2016 2:35:45 PME0627 21:35:45.876936       1 nodecontroller.go:229] Error monitoring node status: an error on the server has prevented the request from succeeding
6/27/2016 2:35:50 PME0627 21:35:50.882134       1 nodecontroller.go:229] Error monitoring node status: an error on the server has prevented the request from succeeding
6/27/2016 2:36:15 PME0627 21:36:15.956173       1 nodecontroller.go:229] Error monitoring node status: an error on the server has prevented the request from succeeding
6/27/2016 2:36:20 PME0627 21:36:20.960586       1 nodecontroller.go:229] Error monitoring node status: an error on the server has prevented the request from succeeding
6/27/2016 2:36:35 PME0627 21:36:35.979712       1 nodecontroller.go:229] Error monitoring node status: an error on the server has prevented the request from succeeding
6/27/2016 2:36:41 PME0627 21:36:41.024454       1 nodecontroller.go:229] Error monitoring node status: an error on the server has prevented the request from succeeding
6/27/2016 2:36:46 PME0627 21:36:46.032171       1 nodecontroller.go:229] Error monitoring node status: an error on the server has prevented the request from succeeding
6/27/2016 2:36:51 PME0627 21:36:51.036356       1 nodecontroller.go:229] Error monitoring node status: an error on the server has prevented the request from succeeding
6/27/2016 2:37:55 PMI0627 21:37:55.506906       1 rancher.go:246] EnsureLoadBalancerDeleted [lb-a982eaaaf3caa11e6a0d502e30918152] [Region1]
6/27/2016 2:37:55 PMI0627 21:37:55.511183       1 servicecontroller.go:298] LB doesn't need update for service default/kubernetes
6/27/2016 2:37:55 PMI0627 21:37:55.512421       1 rancher.go:246] EnsureLoadBalancerDeleted [lb-a9ad257d83cab11e6a0d502e30918152] [Region1]
6/27/2016 2:37:55 PMI0627 21:37:55.542325       1 rancher.go:253] Couldn't find LB %!s(MISSING) to delete. Nothing to do.
6/27/2016 2:37:55 PMI0627 21:37:55.548167       1 rancher.go:253] Couldn't find LB %!s(MISSING) to delete. Nothing to do.
6/27/2016 2:38:06 PME0627 21:38:06.279755       1 nodecontroller.go:229] Error monitoring node status: an error on the server has prevented the request from succeeding
6/27/2016 2:38:11 PME0627 21:38:11.325830       1 nodecontroller.go:229] Error monitoring node status: an error on the server has prevented the request from succeeding
6/27/2016 2:38:26 PME0627 21:38:26.343015       1 nodecontroller.go:229] Error monitoring node status: an error on the server has prevented the request from succeeding
6/27/2016 2:38:31 PME0627 21:38:31.347792       1 nodecontroller.go:229] Error monitoring node status: an error on the server has prevented the request from succeeding
6/27/2016 2:38:36 PME0627 21:38:36.354524       1 nodecontroller.go:229] Error monitoring node status: an error on the server has prevented the request from succeeding
6/27/2016 2:38:41 PME0627 21:38:41.397048       1 nodecontroller.go:229] Error monitoring node status: an error on the server has prevented the request from succeeding
6/27/2016 2:38:46 PME0627 21:38:46.400774       1 nodecontroller.go:229] Error monitoring node status: an error on the server has prevented the request from succeeding
6/27/2016 2:38:51 PME0627 21:38:51.406006       1 nodecontroller.go:229] Error monitoring node status: an error on the server has prevented the request from succeeding
6/27/2016 2:39:16 PME0627 21:39:16.481164       1 nodecontroller.go:229] Error monitoring node status: an error on the server has prevented the request from succeeding
6/27/2016 2:39:21 PME0627 21:39:21.486811       1 nodecontroller.go:229] Error monitoring node status: an error on the server has prevented the request from succeeding
6/27/2016 2:39:36 PMI0627 21:39:36.554508       1 rancher.go:534] ExternalID [soumyamasterkubeenvhost1]
6/27/2016 2:39:36 PMI0627 21:39:36.554627       1 rancher.go:540] InstanceID [soumyamasterkubeenvhost1]
6/27/2016 2:39:41 PMI0627 21:39:41.632146       1 rancher.go:534] ExternalID [soumyamasterkubeenvhost1]
6/27/2016 2:39:41 PMI0627 21:39:41.632231       1 rancher.go:540] InstanceID [soumyamasterkubeenvhost1]
6/27/2016 2:40:06 PME0627 21:40:06.843398       1 nodecontroller.go:229] Error monitoring node status: an error on the server has prevented the request from succeeding
6/27/2016 2:40:11 PME0627 21:40:11.848007       1 nodecontroller.go:229] Error monitoring node status: an error on the server has prevented the request from succeeding
6/27/2016 2:40:16 PME0627 21:40:16.851739       1 nodecontroller.go:229] Error monitoring node status: an error on the server has prevented the request from succeeding
6/27/2016 2:40:21 PME0627 21:40:21.856012       1 nodecontroller.go:229] Error monitoring node status: an error on the server has prevented the request from succeeding
6/27/2016 2:42:54 PMI0627 21:42:54.560133       1 rancher.go:246] EnsureLoadBalancerDeleted [lb-a982eaaaf3caa11e6a0d502e30918152] [Region1]
6/27/2016 2:42:54 PMI0627 21:42:54.560154       1 servicecontroller.go:298] LB doesn't need update for service default/kubernetes
6/27/2016 2:42:54 PMI0627 21:42:54.561666       1 rancher.go:246] EnsureLoadBalancerDeleted [lb-a9ad257d83cab11e6a0d502e30918152] [Region1]
6/27/2016 2:42:54 PMI0627 21:42:54.595029       1 rancher.go:253] Couldn't find LB %!s(MISSING) to delete. Nothing to do.
6/27/2016 2:42:54 PMI0627 21:42:54.598638       1 rancher.go:253] Couldn't find LB %!s(MISSING) to delete. Nothing to do.
6/27/2016 2:42:55 PMW0627 21:42:55.807160       1 request.go:344] Field selector: v1 - serviceaccounts - metadata.name - default: need to check if this is versioned correctly.
```

**Comment by alena1108** [comment] 2016-06-27 21:53
@LLParse not sure what is going on here. etcd1 gets recreated while etcd2/etcd3 keep on running, yet all the information is lost. Previously created Replication controllers are no longer present in the etcd database.

**Comment by LLParse** [comment] 2016-06-27 22:35
@soumyalj I am unable to reproduce - shutting off one host causes etcd to reschedule to the 4th host and all k8s data is preserved.

```
bash-4.3# etcdctl cluster-health
member 95d0726fdbaf025 is healthy: got healthy result from http://10.42.14.231:2
379
member bb411fc35bf55e57 is healthy: got healthy result from http://10.42.162.204
:2379
member e9bb489c39c19fd8 is healthy: got healthy result from http://10.42.36.118:
2379
cluster is healthy
```

```
bash-4.3# etcdctl ls /registry/pods/default
/registry/pods/default/redis-master-lo8ey
/registry/pods/default/redis-slave-gxb3a
/registry/pods/default/frontend-mw496
/registry/pods/default/frontend-b6hqf
/registry/pods/default/frontend-f2nar
/registry/pods/default/mysql
/registry/pods/default/ghost
/registry/pods/default/cassandra-ifwuj
/registry/pods/default/cassandra-kw3ez
/registry/pods/default/cassandra-vo05c
/registry/pods/default/redis-slave-378o8
```

**Comment by alena1108** [comment] 2016-06-27 22:36
@LLParse I believe the error happens when you bring the host that used to be down, back to the pool

**Comment by LLParse** [comment] 2016-06-27 22:43
Done (in GCE), host came back, nothing bad happened. I SSH'd into the restarted VM fast enough to observe the old containers in 'STOPPED' state, I'm guessing where this was tested that was not the case.

**Comment by LLParse** [comment] 2016-06-27 23:41
Re-tested using the [new qa template](https://github.com/rancher/qa-catalog/blob/master/templates/kubernetes/3/rancher-compose.yml) and observed the documented behavior. Since we added scale_policy, we can no longer rely on metadata scale value for decision making. Etcd changes imminent.

**Comment by LLParse** [comment] 2016-07-01 16:58
Duplicate of https://github.com/rancher/rancher/issues/5306

**Closed by LLParse** 2016-07-01 16:58 UTC
Labels: kind/enhancement, status/blocker
