### ISSUE TITLE
[BUG] Migration to cri-dockerd breaks kubelet logrotates

### ISSUE THREAD

**Issue by Heiko-san** [rancher/rancher#39819] opened 2022-12-08 14:16 UTC
**Rancher Server Setup**
- Rancher version: 2.6.8
- Installation option (Docker install/Helm Chart): helm
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): RKE1 v1.23.4 
- Proxy/Cert Details: -

**Information about the Cluster**
- Kubernetes version: v1.23.6  / v1.24.4 
- Cluster Type (Local/Downstream): Downstream
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider):  Infrastructure Provider vSphere

**User Information**
- What is the role of the user logged in? (Admin/Cluster Owner/Cluster Member/Project Owner/Project Member/Custom)
  - If custom, define the set of permissions: admin

**Describe the bug**
After enabling the "cri-dockerd" switch for Downstream clusters, kubelet is not able anymore to rotate container logs:

```
E1205 06:31:07.617923 2342228 container_log_manager.go:266] "Failed to rotate log for container" err="failed to rotate log \"/var/log/pods/harbor_go-harbor-1_7108b6c5-e8d6-4de5-830e-d5f1000c3481/postgres/0.log\": failed to reopen container log \"9c34c87e4c5015dd77c52c6e82d691f109ddc31b6120638dbf550d96204ea847\": rpc error: code = Unknown desc = docker does not support reopening container log files" path="/var/log/pods/harbor_go-harbor-1_7108b6c5-e8d6-4de5-830e-d5f1000c3481/postgres/0.log" containerID="9c34c87e4c5015dd77c52c6e82d691f109ddc31b6120638dbf550d96204ea847"
```
-> "docker does not support reopening container log files"

**To Reproduce**
Enable cri-dockerd in a rke1 Downstream Cluster and have a look into the kubelet logs.

**Result**

We fear it could lead to full discs on small nodes with massively logging workload.

SURE-5919

**Comment by Heiko-san** [comment] 2023-01-16 13:18
Hi, 
is there any update on this?
Since EOL of K8S 1.23 is drawing nearer and this seems to be a real blocker for the upgrade to 1.24 / cri-dockerd!

**Comment by kinarashah** [comment] 2023-02-23 05:45
I don't think this worked with <1.24 clusters either so it's not technically a blocker to move to 1.24 clusters. The only difference is that now the kubelet is constantly logging the errors. 

If container runtime isn't remote (<1.24 clusters), it just uses a stub container log manager that doesn't seem to be doing anything: https://github.com/kubernetes/kubernetes/blob/v1.23.15/pkg/kubelet/kubelet.go#L643  

Now that container runtime is remote with v1.24, it's relying on cri-dockerd which is returning the error 
https://github.com/Mirantis/cri-dockerd/blob/master/core/logs.go#L47 

This should either be fixed in cri-dockerd to no-op or in kubernetes to return a stub container log manager for docker.

**Comment by ofloxacin** [comment] 2023-03-03 10:37
same error

**Comment by ofloxacin** [comment] 2023-03-03 10:37
same issue

**Comment by kinarashah** [comment] 2023-08-25 05:10
Internal dockershim never supported rotating logs for docker, see https://github.com/kubernetes/kubernetes/blob/v1.23.15/pkg/kubelet/kubelet.go#L643. 

With introduction of CRI, it was expected for runtimes to add their own support and kubelet relies on `runtimeService` for the actual log. See https://github.com/kubernetes/kubernetes/blob/84e1fc493a47446df2e155e70fca768d2653a398/pkg/kubelet/logs/container_log_manager.go#L252. 

Because internal dockershim didn't support this feature, cri-dockerd doesn't have support for it either. It logs error that is seen constantly in logs: https://github.com/Mirantis/cri-dockerd/blob/master/core/logs.go#L47 https://github.com/Mirantis/cri-dockerd/issues/35#issuecomment-1365522575

**Comment by kinarashah** [comment] 2023-08-25 05:11
**Workaround:**
As mentioned in https://github.com/rancher/rancher/issues/39819#issuecomment-1472278470, rely on docker's `max-size` flag to perform log rotation. 
Note that it is required for this flag to be <= kubelet's `container-log-max-size` because it controls how often kubelet's rotateLogs is called. https://github.com/kubernetes/kubernetes/blob/v1.26.7/pkg/kubelet/logs/container_log_manager.go#L263 

**Fix**
Use stub log manager for cri-dockerd runtime to maintain the internal dockershim's behavior.

**Comment by kinarashah** [comment] 2023-08-25 05:12
**To test:** 
Ensure the behavior remains same as <v1.24 and users can configure docker daemon's capabilities to rotate logs.

**Comment by kinarashah** [comment] 2023-08-31 16:21
Available to test with August OOB KDM versions: `v1.24.17`, `v1.25.13` and `v1.26.8`

**Comment by vivek-shilimkar** [comment] 2023-09-04 08:25
Tested the issue on rancher v2.7.6 and following k8s versions.
1. v1.24.17
2. v1.25.13
3. v1.26.8

Container logs are rotating as expected and `"Failed to rotate log for container" err="failed to rotate log"` error is not seen in the log anymore.

Since the issue is resolved, closing the ticket.

**Comment by vivek-shilimkar** [comment] 2023-09-05 03:48
After discussion with Kinara, realised that the testing was not complete. Hence reopening the issue to complete the remaining testing.

**Comment by vivek-shilimkar** [comment] 2023-09-05 09:16
Made sure that the logs are rotating after adding the `max-size` for the log file in daemon.json file as [mentioned here](https://github.com/rancher/rancher/issues/39819#issuecomment-1472278470).

Logs do rotate and no error is seen in the logs.
Hence closing the issue.

**Closed by vivek-shilimkar** 2023-09-05 09:16 UTC
Labels: kind/bug, internal, [zube]: QA Working, release-note, team/area2, team/infracloud, JIRA, workaround-available

**Comment by Aaron-ML** [comment] 2024-01-18 00:24
> Made sure that the logs are rotating after adding the `max-size` for the log file in daemon.json file as [mentioned here](https://github.com/rancher/rancher/issues/39819#issuecomment-1472278470).
> 
> Logs do rotate and no error is seen in the logs. Hence closing the issue.

Is the expectation here to manage this outside of the rancher cluster UI? Doesn't appear to have any sane defaults. We are managing a few internal test clusters and this will be painful to go in after rancher and add. 

If there are no defaults for this on install, are there any plans to? Currently seeing this on Rancher v2.7.3 and 1.25.9 clusters.
