### ISSUE TITLE
Docker 1.11 on AWS Linux "unable to get fs usage from thin pool for device"

### ISSUE THREAD

**Issue by kmcgrath** [rancher/rancher#5313] opened 2016-07-01 15:58 UTC
This was originally posted in issue #4491 after that issue was closed.  I did not see an update there, so I'm creating a new issue.

**Rancher Version:** 1.1.0

**Docker Version:** 1.11.1, build 5604cbe/1.11.1

**OS and where are the hosts located? (cloud, bare metal, etc):** AWS Linux

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)** HA

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)** Cattle

**Steps to Reproduce:**

On AWS Linux:

    sudo yum install -y docker
    sudo service start docker
    sudo docker run -d --privileged -v /var/run/docker.sock:/var/run/docker.sock -v /var/lib/rancher:/var/lib/rancher rancher/agent:v1.0.2 https://.....

**Results:** 

@soumyalj Having the same issue as @HackerWilson with AWS Linux

AMI: amzn-ami-hvm-2016.03.2.x86_64-gp2 (ami-f303fb93)
Docker Version: Docker version 1.11.1, build 5604cbe/1.11.1
Rancher Agent: rancher/agent:v1.0.2

I0624 00:46:55.893612 4241 manager.go:198] Version: {KernelVersion:4.4.11-23.53.amzn1.x86_64 ContainerOsVersion:Amazon Linux AMI 2016.03 DockerVersion:1.11.1 CadvisorVersion:0.23.2 CadvisorRevision:}
I0624 00:46:55.897143 4241 factory.go:217] registering Docker factory
E0624 00:46:55.897160 4241 manager.go:240] Registration of the rkt container factory failed: unable to communicate with Rkt api service: rkt: cannot tcp Dial rkt api service: dial tcp 127.0.0.1:15441: getsockopt: connection refused
I0624 00:46:55.897164 4241 factory.go:54] Registering systemd factory
I0624 00:46:55.897414 4241 factory.go:86] Registering Raw factory
I0624 00:46:55.897663 4241 manager.go:1072] Started watching for new ooms in manager
I0624 00:46:55.897728 4241 oomparser.go:200] OOM parser using kernel log file: "/var/log/messages"
I0624 00:46:55.897995 4241 manager.go:281] Starting recovery of all containers
I0624 00:46:55.903072 4241 thin_pool_watcher.go:117] reserving metadata snapshot for thin-pool docker-202:1-263554-pool
E0624 00:46:55.911908 4241 thin_pool_watcher.go:54] encountered error refreshing thin pool watcher: error performing thin_ls on metadata device /dev/loop1: Error running command thin_ls --no-headers -m -o DEV,EXCLUSIVE_BYTES /dev/loop1: exec: "thin_ls": executable file not found in $PATH
output:

I0624 00:46:55.923123 4241 manager.go:286] Recovery completed
I0624 00:46:55.924560 4241 cadvisor.go:151] Starting cAdvisor version: 0.23.2- on port 9344
E0624 00:46:55.924917 4241 handler.go:278] unable to get fs usage from thin pool for device 16: no cached value for usage of device 16
time="2016-06-24T00:46:56Z" level="info" msg="Starting event router." 
time="2016-06-24T00:46:56Z" level="info" msg="Watching state directory: /var/lib/rancher/state/containers" 
E0624 00:46:56.990770 4241 handler.go:278] unable to get fs usage from thin pool for device 16: no cached value for usage of device 16
E0624 00:46:58.147339 4241 handler.go:278] unable to get fs usage from thin pool for device 16: no cached value for usage of device 16
E0624 00:46:59.662532 4241 handler.go:278] unable to get fs usage from thin pool for device 16: no cached value for usage of device 16
E0624 00:47:01.043198 4241 handler.go:278] unable to get fs usage from thin pool for device 16: no cached value for usage of device 16
E0624 00:47:02.326208 4241 handler.go:278] unable to get fs usage from thin pool for device 16: no cached value for usage of device 16

**Comment by deniseschannon** [comment] 2016-07-01 16:02
Duplicate of https://github.com/rancher/rancher/issues/5303

**Closed by deniseschannon** 2016-07-01 16:02 UTC
