### ISSUE TITLE
Cluster is stuck in error state after updating rancher from 2.4.x to 2.5

### ISSUE THREAD

**Issue by sowmyav27** [rancher/rancher#32056] opened 2021-04-12 17:52 UTC
**What kind of request is this (question/bug/enhancement/feature request):** bug

**Steps to reproduce (least amount of steps as possible):**

- Deploy a 1 node - etcd and control and 1 worker node cluster in 2.4.15
- Upgrade rancher to 2.5-head commit id: `6f71d4c73`

**Result:**
Cluster is seen stuck in Updating state with error and the master node - etcd + control plane is seen stuck in `Cordoned` state
```
This cluster is currently Updating; areas that interact directly with it will not be available until the API is ready.

Cluster health check failed: Failed to communicate with API server during namespace check: Get "https://<master-node>:6443/api/v1/namespaces/kube-system?timeout=45s": dial tcp <master-node>:6443: connect: connection refused; Cluster must have at least one etcd plane host: failed to connect to the following etcd host(s) [<master-node>]
```

**Other details that may be helpful:**
- on an upgrade from 2.4.15 to 2.5.7:
- - This issue is not seen - https://github.com/rancher/rancher/issues/32056

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): 2.4.15 to 2.5-head
- Installation option (single install/HA): single

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): RKE DO
- Kubernetes version (use `kubectl version`):

```
v1.18.17
```

**Comment by kinarashah** [comment] 2021-04-13 01:02
This issue will reproduce for the following k8s versions: 
`v1.18.14-rancher1-1`, `v1.18.15-rancher1-1`, `v1.18.16-rancher1-1` and `v1.18.17-rancher1-1`. 

Steps: 
- Any Rancher server version `v2.4.x` (>=`v2.4.5`) 
- Create a RKE cluster with any of the above mentioned k8s versions. 
- Upgrade to Rancher server version `v2.5.x` 
- Observe that the cluster automatically goes into `Updating` state. Also, it goes through all the provisioning steps again before becoming Active. 

This issue will reproduce for the following k8s versions: 
`v1.17.16-rancher1-1`, `v1.17.17-rancher1-1` and. `v1.17.7-rancher2-1`. 

Steps: 
- Any Rancher server version `v2.4.x` (>=`v2.4.4`) 
- Create a RKE cluster with any of the above mentioned k8s versions. 
- Upgrade to Rancher server version `v2.5.x` 
- Observe that the cluster automatically goes into `Updating` state. Also, it goes through all the provisioning steps again before becoming Active. 

Root cause: 
System images were added for these k8s versions in order to introduce support for ACI CNI image. These images are not present in `v2.4.x` but got added for the same version in `v2.5.x`. ACI was first introduced with `v1.17.16` and `v1.18.14`. Since then, we introduced more versions through KDM and Rancher releases. They were all based off the same changes, so this continues till the latest `v1.17.17` and `v1.18.17`.

**Comment by kinarashah** [comment] 2021-04-13 01:38
Note: Code fix isn't enough for this issue, extra step is required to ensure clusters don't update unless required. We'll need to document it.  

Steps: 
- Any Rancher server version v2.4.x (>=v2.4.5) 
- Create a RKE cluster with any of these k8s versions (Use Edit as Yaml on cluster if the version doesn't show up in UI) 
`v1.17.16-rancher1-1`, `v1.17.17-rancher1-1`, `v1.17.7-rancher2-1` 
`v1.18.14-rancher1-1`, `v1.18.15-rancher1-1`, `v1.18.16-rancher1-1` and `v1.18.17-rancher1-1`. 
- Refresh KDM, `dev-v2.4` (after the fix is merged) 

- **Extra step:** **_This is to ensure the version becomes in sync with the v2.5.x versions and doesn't upgrade. Make sure the cluster remains in the Active state after the kubectl edit._** 

    `kubectl edit cluster c-xxxx -o yaml`. Increment the X in `rancher1-X` for the field `kubernetesVersion` in both spec 
     and applied (status). 
     For example, if the cluster version is `v1.18.15-rancher1-1`, change it to `v1.18.15-rancher1-2` in both spec and status. 
     For example, if the cluster version is `v1.17.17-rancher2-1`, change it to `v1.17.17-rancher2-2` in both spec and status. 

- Upgrade to Rancher server version `v2.5.x` 

- Make sure cluster remains in the Active state. 

- If users want to stay with the same exact version (`v1.18.15-rancher1-2` for our example) and still get support for ACI in Rancher `v2.5.x`, they can upgrade to `v1.18.15-rancher1-3` for that purpose).

**Comment by kinarashah** [comment] 2021-04-23 14:04
@sowmyav27 Not able to reproduce this, if you happen to run into it again, please let me know. Removing zube/working for now.

**Comment by cbron** [comment] 2023-10-31 16:26
2.5 no longer supported, closing

**Closed by cbron** 2023-10-31 16:26 UTC
Labels: kind/bug-qa, [zube]: To Triage
