### ISSUE TITLE
when user updates rke-metadata-config on dev-v2.6, refreshing `Kontainer-driver-metadata` does not update available k8s versions

### ISSUE THREAD

**Issue by slickwarren** [rancher/rancher#34473] opened 2021-08-25 22:04 UTC
**Rancher Server Setup**
- Rancher version:v2.6-head(b7c440b)
- Installation option (Docker install/Helm Chart):docker 
   - If Helm Chart, Kubernetes Info:
         Cluster Type (RKE1, RKE2, k3s, EKS, etc):k3s
         Node Setup:single node
         Version:v1.21.3+k3s1
- Proxy/Cert Details:self signed certs

**Describe the bug**

* when the user tries to refresh KDM info via the `refresh Kubernetes Metadata` button (cluster management -> drivers), the response is `null` and the latest versions aren't updated in the rancher setup

**To Reproduce**
 
* ensure there is a mismatch in kdm versions for your 2.6 cluster
* go to cluster management -> drivers and click the `refresh Kubernetes Metadata` button with the console open to view the response

**Result**
response is null, versions are not updated

**Expected Result**

the latest version should be pulled, if any, when the user clicks this button

**Screenshots**

**Additional context**

this is the rke-metadata url:
https://releases.rancher.com/kontainer-driver-metadata/dev-v2.6/data.json

**Comment by kinarashah** [comment] 2021-10-01 17:21
Synced up @slickwarren. I thought the null `response` showed up in UI but that's not the case, it shows up in response under dev tools. We should fix it to send something meaningful than null tho the action by itself isn't supposed to return anything. 

Also, I'd need to create a custom branch for testing k8s versions refresh because right now all versions from dev-v2.6 are released in release-v2.6.

**Comment by kinarashah** [comment] 2021-10-04 23:24
@slickwarren Looks like I'm already sending the correct response, 200 OK. The response in the dev tools usually has the object or list of objects to be returned, but don't have anything to return so would be ok in this case. Also, confirmed this with Rancher v2.5.9, it is the same behavior so it's not a regression. 
<img width="606" alt="Screen Shot 2021-10-04 at 3 56 18 PM" src="https://user-images.githubusercontent.com/16870565/135937305-fde9ab51-ae4e-47ba-a2ce-b4c4b7f85081.png">

Also, to test for RKE2 version refresh: 
- Update setting `rke-metadata-config` url to `https://raw.githubusercontent.com/kinarashah/kontainer-driver-metadata/21812d7e35cdc5a8fcca3b470751500633dbdcd1/data/data.json`. This data has a few fake versions I added for testing purpose, actual cluster provisioning wouldn't work with them but the intent is to just validate the refresh because this doesn't work on v2.6.0 for RKE2 versions. 
- Refresh Kontainer-metadata from cluster management -> Drivers page. 
- Confirm both RKE
<img width="900" alt="Screen Shot 2021-10-04 at 4 24 11 PM" src="https://user-images.githubusercontent.com/16870565/135937507-f8420180-3e45-4178-aa2e-3fd703f30438.png">
2 and k3s have new versions `v1.21.6`:

**Comment by slickwarren** [comment] 2021-10-07 17:14
on v2.6-head (7bc7959):
- Update setting `rke-metadata-config` url to `https://raw.githubusercontent.com/kinarashah/kontainer-driver-metadata/21812d7e35cdc5a8fcca3b470751500633dbdcd1/data/data.json`. 
- Refresh Kontainer-driver-metadata from cluster management -> Drivers page. 
- Confirm both RKE2 and k3s have new versions `v1.21.6` -- pass
- Switch the `rke-metadata-config` back to default, k8s versions should now show only `v1.21.5` -- fail
  - also tried hard refershes, but only the k3s version is changing. RKE2 is not updating back to v1.21.5
<img width="640" alt="Screen Shot 2021-10-07 at 10 12 52 AM" src="https://user-images.githubusercontent.com/16691014/136432371-4cb2c3ef-8518-4379-a6fc-c5d209e9fd74.png">

**Closed as completed** 2021-10-07 23:40 UTC
Labels: kind/bug-qa, QA/XS
