### ISSUE TITLE
[BUG]rancher v1.6.11 start_on_create not work

### ISSUE THREAD

**Issue by anjia0532** [rancher/rancher#10427] opened 2017-11-29 01:30 UTC
by web ui 

![_20171129092703](https://user-images.githubusercontent.com/15098916/33353201-90a87b3c-d4e7-11e7-93b8-8d8cff12d321.png)

by rancher-cli (rancher cli version v0.6.5)

![_20171129092710](https://user-images.githubusercontent.com/15098916/33353241-ce072e2e-d4e7-11e7-90a7-22dd02594736.png)

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v1.6.11` Cattle: `v0.183.30` UI: `v1.6.30` |
|Access|`Disabled`|
|Orchestration|`Cattle`|
|Route|`stacks.index`|

**Comment by superseb** [comment] 2017-11-29 08:27
Duplicate of https://github.com/rancher/rancher/issues/7287

Let me know if you don't agree

**Closed by superseb** 2017-11-29 08:27 UTC

**Comment by anjia0532** [comment] 2017-12-03 03:47
v1.6.12 is not work too.
