### ISSUE TITLE
Monitoring Query fails periodically.

### ISSUE THREAD

**Issue by cloudnautique** [rancher/rancher#19564] opened 2019-04-11 23:01 UTC
When the UI loads it makes 2 query requests when it loads the cluster page to the clustermonitorgraphs resources. It gets a 500 with the following payload:

`{"filters":{"resourceType":"cluster","clusterId":"c-8h7s5"},"metricParams":{},"interval":"5s","isDetails":true,"from":"now-5s","to":"now"}`

There have been some 500s where it gets an error that monitoring server might not be available. This isn't the case as the graphana graphs are still available, and a second call a moment later succeeds. There is no restarting pods.

This has been observed in clusters between 500-1000 nodes. The monitoring server is pinned to a dedicated n1-standard-8 node.

**Comment by loganhz** [comment] 2019-04-12 16:53
Rancher logs
```
2019/04/12 16:41:24 [WARNING] query series failed
2019/04/12 16:42:26 [WARNING] query series failed
2019/04/12 16:42:53 [WARNING] query series failed
2019/04/12 16:43:04 [WARNING] query series failed
2019/04/12 16:44:48 [WARNING] query series failed
2019/04/12 16:46:53 [WARNING] query series failed
2019/04/12 16:47:01 [WARNING] query series failed
2019/04/12 16:49:49 [WARNING] query series failed
```

**Comment by loganhz** [comment] 2019-04-12 19:05
Prometheus auth log

```
2019/04/12 19:04:24 http: proxy error: dial tcp [::1]:9090: connect: connection refused
2019/04/12 19:04:24 http: proxy error: dial tcp [::1]:9090: connect: connection refused
2019/04/12 19:04:24 http: proxy error: dial tcp [::1]:9090: connect: connection refused
2019/04/12 19:04:24 http: proxy error: dial tcp [::1]:9090: connect: connection refused
2019/04/12 19:04:24 http: proxy error: dial tcp [::1]:9090: connect: connection refused
2019/04/12 19:04:24 http: proxy error: dial tcp [::1]:9090: connect: connection refused
2019/04/12 19:04:24 http: proxy error: dial tcp [::1]:9090: connect: connection refused
2019/04/12 19:04:24 http: proxy error: dial tcp [::1]:9090: connect: connection refused
2019/04/12 19:04:24 http: proxy error: dial tcp [::1]:9090: connect: connection refused
2019/04/12 19:04:24 http: proxy error: dial tcp [::1]:9090: connect: connection refused
2019/04/12 19:04:24 http: proxy error: dial tcp [::1]:9090: connect: connection refused
2019/04/12 19:04:24 http: proxy error: dial tcp [::1]:9090: connect: connection refused
2019/04/12 19:04:24 http: proxy error: dial tcp [::1]:9090: connect: connection refused
2019/04/12 19:04:24 http: proxy error: dial tcp [::1]:9090: connect: connection refused
2019/04/12 19:04:24 http: proxy error: dial tcp [::1]:9090: connect: connection refused
2019/04/12 19:04:24 http: proxy error: dial tcp [::1]:9090: connect: connection refused
2019/04/12 19:04:24 http: proxy error: dial tcp [::1]:9090: connect: connection refused
2019/04/12 19:04:24 http: proxy error: dial tcp [::1]:9090: connect: connection refused
2019/04/12 19:04:24 http: proxy error: dial tcp [::1]:9090: connect: connection refused
2019/04/12 19:04:24 http: proxy error: dial tcp [::1]:9090: connect: connection refused
2019/04/12 19:04:24 http: proxy error: dial tcp [::1]:9090: connect: connection refused
2019/04/12 19:04:24 http: proxy error: dial tcp [::1]:9090: connect: connection refused
2019/04/12 19:04:24 http: proxy error: dial tcp [::1]:9090: connect: connection refused
2019/04/12 19:04:24 http: proxy error: dial tcp [::1]:9090: connect: connection refused
2019/04/12 19:04:24 http: proxy error: dial tcp [::1]:9090: connect: connection refused
2019/04/12 19:04:24 http: proxy error: dial tcp [::1]:9090: connect: connection refused
2019/04/12 19:04:24 http: proxy error: dial tcp [::1]:9090: connect: connection refused
2019/04/12 19:04:24 http: proxy error: dial tcp [::1]:9090: connect: connection refused
2019/04/12 19:04:24 http: proxy error: dial tcp [::1]:9090: connect: connection refused
2019/04/12 19:04:24 http: proxy error: context canceled
2019/04/12 19:04:24 http: proxy error: context canceled
2019/04/12 19:04:26 http: proxy error: dial tcp [::1]:9090: connect: connection refused
2019/04/12 19:04:26 http: proxy error: dial tcp [::1]:9090: connect: connection refused
2019/04/12 19:04:26 http: proxy error: dial tcp [::1]:9090: connect: connection refused
2019/04/12 19:04:26 http: proxy error: dial tcp [::1]:9090: connect: connection refused
2019/04/12 19:04:26 http: proxy error: dial tcp [::1]:9090: connect: connection refused
2019/04/12 19:04:26 http: proxy error: dial tcp [::1]:9090: connect: connection refused
2019/04/12 19:04:26 http: proxy error: dial tcp [::1]:9090: connect: connection refused
2019/04/12 19:04:26 http: proxy error: dial tcp [::1]:9090: connect: connection refused
2019/04/12 19:04:26 http: proxy error: dial tcp [::1]:9090: connect: connection refused
2019/04/12 19:04:26 http: proxy error: dial tcp [::1]:9090: connect: connection refused
2019/04/12 19:04:26 http: proxy error: dial tcp [::1]:9090: connect: connection refused
2019/04/12 19:04:26 http: proxy error: dial tcp [::1]:9090: connect: connection refused
2019/04/12 19:04:26 http: proxy error: dial tcp [::1]:9090: connect: connection refused
2019/04/12 19:04:26 http: proxy error: dial tcp [::1]:9090: connect: connection refused
2019/04/12 19:04:26 http: proxy error: dial tcp [::1]:9090: connect: connection refused
2019/04/12 19:04:26 http: proxy error: context canceled
2019/04/12 19:04:27 http: proxy error: dial tcp [::1]:9090: connect: connection refused
2019/04/12 19:04:34 http: proxy error: dial tcp [::1]:9090: connect: connection refused
2019/04/12 19:04:34 http: proxy error: dial tcp [::1]:9090: connect: connection refused
2019/04/12 19:04:34 http: proxy error: dial tcp [::1]:9090: connect: connection refused
2019/04/12 19:04:34 http: proxy error: dial tcp [::1]:9090: connect: connection refused
2019/04/12 19:04:34 http: proxy error: dial tcp [::1]:9090: connect: connection refused
2019/04/12 19:04:34 http: proxy error: dial tcp [::1]:9090: connect: connection refused
2019/04/12 19:04:34 http: proxy error: dial tcp [::1]:9090: connect: connection refused
2019/04/12 19:04:34 http: proxy error: dial tcp [::1]:9090: connect: connection refused
2019/04/12 19:04:34 http: proxy error: dial tcp [::1]:9090: connect: connection refused
2019/04/12 19:04:34 http: proxy error: dial tcp [::1]:9090: connect: connection refused
2019/04/12 19:04:34 http: proxy error: dial tcp [::1]:9090: connect: connection refused
2019/04/12 19:04:34 http: proxy error: dial tcp [::1]:9090: connect: connection refused
2019/04/12 19:04:34 http: proxy error: dial tcp [::1]:9090: connect: connection refused
2019/04/12 19:04:34 http: proxy error: dial tcp [::1]:9090: connect: connection refused
2019/04/12 19:04:34 http: proxy error: dial tcp [::1]:9090: connect: connection refused
2019/04/12 19:04:34 http: proxy error: dial tcp [::1]:9090: connect: connection refused
2019/04/12 19:04:41 http: proxy error: context canceled
2019/04/12 19:04:41 http: proxy error: context canceled
2019/04/12 19:04:41 http: proxy error: context canceled
2019/04/12 19:04:41 http: proxy error: context canceled
2019/04/12 19:04:41 http: proxy error: context canceled
2019/04/12 19:04:41 http: proxy error: context canceled
2019/04/12 19:04:41 http: proxy error: context canceled
2019/04/12 19:04:41 http: proxy error: context canceled
2019/04/12 19:04:41 http: proxy error: context canceled
2019/04/12 19:04:41 http: proxy error: context canceled
2019/04/12 19:04:41 http: proxy error: context canceled
2019/04/12 19:04:41 http: proxy error: context canceled
2019/04/12 19:04:41 http: proxy error: context canceled
2019/04/12 19:04:41 http: proxy error: context canceled
2019/04/12 19:04:41 http: proxy error: context canceled
2019/04/12 19:04:41 http: proxy error: context canceled
2019/04/12 19:04:41 http: proxy error: context canceled
2019/04/12 19:04:41 http: proxy error: context canceled
2019/04/12 19:04:41 http: proxy error: context canceled
2019/04/12 19:04:41 http: proxy error: context canceled
2019/04/12 19:04:41 http: proxy error: context canceled
2019/04/12 19:04:41 http: proxy error: context canceled
2019/04/12 19:04:41 http: proxy error: context canceled
2019/04/12 19:04:41 http: proxy error: context canceled
2019/04/12 19:04:41 http: proxy error: context canceled
2019/04/12 19:04:41 http: proxy error: context canceled
2019/04/12 19:04:41 http: proxy error: context canceled
2019/04/12 19:04:43 http: proxy error: dial tcp [::1]:9090: connect: connection refused
2019/04/12 19:04:43 http: proxy error: dial tcp [::1]:9090: connect: connection refused
2019/04/12 19:04:43 http: proxy error: dial tcp [::1]:9090: connect: connection refused
2019/04/12 19:04:43 http: proxy error: dial tcp [::1]:9090: connect: connection refused
2019/04/12 19:04:43 http: proxy error: dial tcp [::1]:9090: connect: connection refused
2019/04/12 19:04:43 http: proxy error: dial tcp [::1]:9090: connect: connection refused
2019/04/12 19:04:43 http: proxy error: dial tcp [::1]:9090: connect: connection refused
2019/04/12 19:04:43 http: proxy error: dial tcp [::1]:9090: connect: connection refused
2019/04/12 19:04:43 http: proxy error: dial tcp [::1]:9090: connect: connection refused
2019/04/12 19:04:43 http: proxy error: dial tcp [::1]:9090: connect: connection refused
2019/04/12 19:04:43 http: proxy error: dial tcp [::1]:9090: connect: connection refused
2019/04/12 19:04:43 http: proxy error: dial tcp [::1]:9090: connect: connection refused
2019/04/12 19:04:43 http: proxy error: dial tcp [::1]:9090: connect: connection refused
2019/04/12 19:04:43 http: proxy error: dial tcp [::1]:9090: connect: connection refused
2019/04/12 19:04:43 http: proxy error: dial tcp [::1]:9090: connect: connection refused
2019/04/12 19:04:43 http: proxy error: context canceled
```

**Comment by loganhz** [comment] 2019-04-12 19:44
Should be the same issue with https://github.com/rancher/rancher/issues/19243

**Comment by davidnuzik** [comment] 2019-05-07 22:22
@loganhz could you help me understand the changes some more? Regarding `UI issue is it sending too many requests to backend.` I see no change in the interval of the query nor the data transmitted. I don't notice changes in how / where we query.

I compared against v2.2.3-rc6 (before the merge/fix) and see no changes. Further, I do not see us trying to query before monitoring is enabled/ready. I must be missing something - could you help me identify what I am missing?

**Comment by loganhz** [comment] 2019-05-08 00:56
@davidnuzik 

There is a `isMonitoringReady` function in UI. The old logic will re-evaluate when `conditions` filed on cluster changed. However, we only cares about `MonitoringEnabled` condition in `conditions` filed.

When `isMonitoringReady` status changed, UI will send requests to backend. 
In some setup, the `conditions` fields on cluster object keep updating sometimes. 
But `MonitoringEnabled` condition didn't change at all. 
We should not send the requests in this case

**Comment by davidnuzik** [comment] 2019-05-08 22:15
Thanks @loganhz I had misunderstood I for some reason was thinking we were doing something to decrease load such as upping the refresh interval. I understand now.

**Comment by davidnuzik** [comment] 2019-05-08 22:25
Version: Master (v2.3) (5/8/19)

I still observe that when we load the cluster dashboard page we make 2 query requests to `clustermonitorgraphs` but now, we no longer get 503 errors. The queries only start when monitoring is ready. I have tested this several times in order too try to reproduce the issue but no longer can. I can also disable monitoring, watch this page, and still avoid 503 or other errors upon the query. I can re-enable again, still watching the dashboard page and not observe and HTTP errors.

I do observe an unrelated error with HTTP 503 at https://RANCHERSERVER/k8s/clusters/c-zwvbx/api/v1/namespaces/cattle-prometheus/services/http:access-grafana:80/proxy/api/search
With the following console error:
```
Uncaught (in promise) {body: {…}, status: 503, statusText: "", headers: u}

Promise.then (async) |   |  
-- | -- | --
  | r | @ | backburner.js:26
  | n._scheduleAutorun | @ | backburner.js:1227
  | n._end | @ | backburner.js:1021
  | _boundAutorunEnd | @ | backburner.js:653
  | Promise.then (async) |   |  
  | r | @ | backburner.js:26
  | n._scheduleAutorun | @ | backburner.js:1227
  | n._end | @ | backburner.js:1021
  | _boundAutorunEnd | @ | backburner.js:653
  | Promise.then (async) |   |  
  | r | @ | backburner.js:26
  | n._scheduleAutorun | @ | backburner.js:1227
  | n._end | @ | backburner.js:1021
  | _boundAutorunEnd | @ | backburner.js:653
  | Promise.then (async) |   |  
  | r | @ | backburner.js:26
  | n._scheduleAutorun | @ | backburner.js:1227
  | n._end | @ | backburner.js:1021
  | _boundAutorunEnd | @ | backburner.js:653
  | Promise.then (async) |   |  
  | r | @ | backburner.js:26
  | n._scheduleAutorun | @ | backburner.js:1227
  | n._end | @ | backburner.js:1021
  | _boundAutorunEnd | @ | backburner.js:653
  | Promise.then (async) |   |  
  | r | @ | backburner.js:26
  | n._scheduleAutorun | @ | backburner.js:1227
  | n._end | @ | backburner.js:1021
  | _boundAutorunEnd | @ | backburner.js:653
  | Promise.then (async) |   |  
  | r | @ | backburner.js:26
  | n._scheduleAutorun | @ | backburner.js:1227
  | n._end | @ | backburner.js:1021
  | _boundAutorunEnd | @ | backburner.js:653
  | Promise.then (async) |   |  
  | r | @ | backburner.js:26
  | n._scheduleAutorun | @ | backburner.js:1227
  | n._end | @ | backburner.js:1021
  | _boundAutorunEnd | @ | backburner.js:653
  | Promise.then (async) |   |  
  | r | @ | backburner.js:26
  | n._scheduleAutorun | @ | backburner.js:1227
  | n._end | @ | backburner.js:1021
  | _boundAutorunEnd | @ | backburner.js:653
  | Promise.then (async) |   |  
  | r | @ | backburner.js:26
  | n._scheduleAutorun | @ | backburner.js:1227
  | n._end | @ | backburner.js:1021
  | _boundAutorunEnd | @ | backburner.js:653
  | Promise.then (async) |   |  
  | r | @ | backburner.js:26
  | n._scheduleAutorun | @ | backburner.js:1227
  | n._ensureInstance | @ | backburner.js:1218
  | n.schedule | @ | backburner.js:789
  | (anonymous) | @ | rsvp.js:7
  | _ | @ | rsvp.js:445
  | E | @ | rsvp.js:420
  | (anonymous) | @ | rsvp.js:539
  | e.onload | @ | ember-fetch.js:363
  | load (async) |   |  
  | (anonymous) | @ | ember-fetch.js:362
  | (anonymous) | @ | rsvp.js:533
  | e | @ | rsvp.js:1041
  | d | @ | ember-fetch.js:361
  | text | @ | ember-fetch.js:380
  | r | @ | fetch.js:31
  | b | @ | rsvp.js:334
  | k | @ | rsvp.js:507
  | C | @ | rsvp.js:493
  | t.invoke | @ | backburner.js:343
  | t.flush | @ | backburner.js:233
  | t.flush | @ | backburner.js:437
  | n._end | @ | backburner.js:1013
  | _boundAutorunEnd | @ | backburner.js:653
  | Promise.then (async) |   |  
  | r | @ | backburner.js:26
  | n._scheduleAutorun | @ | backburner.js:1227
  | n._end | @ | backburner.js:1021
  | _boundAutorunEnd | @ | backburner.js:653
  | Promise.then (async) |   |  
  | r | @ | backburner.js:26
  | n._scheduleAutorun | @ | backburner.js:1227
  | n._ensureInstance | @ | backburner.js:1218
  | n.schedule | @ | backburner.js:789
  | (anonymous) | @ | rsvp.js:7
  | _ | @ | rsvp.js:445
  | y | @ | rsvp.js:410
  | E | @ | rsvp.js:418
  | (anonymous) | @ | rsvp.js:539
  | o.onload | @ | ember-fetch.js:660
  | load (async) |   |  
  | (anonymous) | @ | ember-fetch.js:652
  | (anonymous) | @ | rsvp.js:533
  | e | @ | rsvp.js:1041
  | E | @ | ember-fetch.js:639
  | n | @ | fetch.js:19
  | rawRequest | @ | store.js:288
  | (anonymous) | @ | service.js:75
  | x | @ | metal.js:288
  | t.flush | @ | metal.js:416
  | H | @ | metal.js:856
  | processQueue | @ | subscribe.js:133
  | setInterval (async) |   |  
  | subscribeConnected | @ | subscribe.js:241
  | (anonymous) | @ | subscribe.js:79
  | x | @ | metal.js:288
  | trigger | @ | evented.js:114
  | _opened | @ | socket.js:151
  | n._run | @ | backburner.js:1064
  | n._join | @ | backburner.js:1040
  | n.join | @ | backburner.js:759
  | h | @ | index.js:165
  | (anonymous) | @ | index.js:269
```

I would assume this is something for a separate issue. Would you agree @loganhz ?
This is not related specifically to the `clustermonitorgraphs` 503 reported in this issue.

**Comment by loganhz** [comment] 2019-05-09 00:29
@davidnuzik yes, that should be a different issue. UI will start to check if grafana is ready when Prometheus is ready. UI need to call the grafana API to detect if grafana is ready.

**Comment by davidnuzik** [comment] 2019-05-09 16:14
Thanks Logan. I consider this issue resolved and validated then. I do not observe HTTP 503 errors when query `clustermonitorgraphs` any longer. https://github.com/rancher/rancher/issues/19564#issuecomment-490672830
It's possible the issue may stay open as we might test with a many-node cluster later.

**Comment by davidnuzik** [comment] 2019-05-09 22:53
I  have tried to reproduce this and have not been successful. I have tried in v2.2.2 (cannot get 503 errors) maybe this is because I need many more nodes or something.

**Comment by davidnuzik** [comment] 2019-05-10 23:31
@loganhz Could you comment on the 2 query requests that happen first time you load the page?
We still see this happen.

**Comment by loganhz** [comment] 2019-05-11 01:55
@davidnuzik thanks 

It should be only one request. Submited a PR to fix it

**Comment by davidnuzik** [comment] 2019-05-20 21:07
Version: Master (v2.3) (5/20/19)

I can confirm the query happening twice upon initial load of the cluster dashboard is now fixed.
503 errors were not observed refer to my prior comment here https://github.com/rancher/rancher/issues/19564#issuecomment-490969416

The issue may stay open, but is considered resolved from a UI testing standpoint. We may keep it open because we may setup a large 500-1000 node cluster later and test with that.

**Closed** 2019-07-08 19:12 UTC
Labels: [zube]: To Test, area/monitoring, area/ui, kind/bug-qa, team/ui
