### ISSUE TITLE
Workload API should report error when attempting to create Nodeport  with Source Port not in the range 30000-32767.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#11935] opened 2018-03-05 02:02 UTC
**Rancher versions: Server build from mar 3 night

Steps to reproduce the problem:
Create workloads with Nodeport  having Source Port not in the range 30000-32767.
Workload gets created successfully with no public endpoints created.

Workload creation should fail to get created in this case with error message about source Port not being in the range 30000-32767 , so user has the ability to correct the source Port.

**Comment by alena1108** [comment] 2018-03-05 18:54
Closing as a duplicate of https://github.com/rancher/rancher/issues/11732

**Closed by alena1108** 2018-03-05 18:54 UTC
Labels: kind/bug, version/2.0
