### ISSUE TITLE
Clusters stuck in Configuring state when upgrade from Rancher 2.5.11 to v2.6-head

### ISSUE THREAD

**Issue by davidnuzik** [rancher/rancher#35411] opened 2021-11-08 23:44 UTC
**Summary:**

This appears to be very much like https://github.com/rancher/rancher/issues/35330

Install Rancher 2.5.11 and in my case I created multiple imported clusters. I then upgraded to Rancher v2.6-head (`b6d9284`, 11/8/2021). Post-upgrade all my clusters (including the local cluster) are stuck in a "Configuring" state. It looks like all resources are Active except the Management cluster is stuck in the "Configuring" state.

There are no obvious errors in the rancher pod logs or in the fleet pod logs on the local cluster.

-----

**Environment:**
Rancher version: v2.5.11 > v2.6-head  (`b6d9284`, 11/8/2021) upgrade.
Rancher cluster type: HA
 
Downstream cluster type: Several imported clusters each with 1.20.12 kubernetes (one RKE1, one RKE2, one K3S, all single-node clusters)
Downstream K8s version: 1.20.12

**Steps to Reproduce:**
1. Install HA Rancher 2.5.11 and import several clusters, in my case K3S, RKE1, RKE2 each running k8s 1.20.12.
2. Upgrade to latest v2.6-head
 
**Expected Result:**
Downstream clusters eventually come to Active state

**Actual Result:**
All downstream clusters stay in the "Configuring" state.

**Comment by jakefhyde** [comment] 2021-11-08 23:51
This should be fixed by this PR: https://github.com/rancher/rancher/pull/35359.

**Comment by davidnuzik** [comment] 2021-11-08 23:51
https://github.com/rancher/rancher/pull/35359 should fix this

**Comment by davidnuzik** [comment] 2021-11-12 17:49
@jakefhyde the PR is merged - is there another we need? If not, could you move this issue To Test?

**Comment by ronhorton** [comment] 2021-11-12 20:44
I'm currently testing 2 rancher docker installs, one with the feature flag off during upgrade, the other with the feature flag on. Otherwise, the setups are identical.

first cluster A (rke flag deactivated) has been configuring/provisioning for 4 hours.
second cluster B (rke flag active) has been configuring/provisioning for 25 minutes

- both are 2.6-head Commit ID 638b29a
- do - rke2 - 1 single node clusters
- aws - rke2 - 1 single node cluster; rke1 1 single node cluster

**Comment by jakefhyde** [comment] 2021-11-18 20:14
### Root cause
 
A condition was being set on a cluster that required the subsequent default and system projects to sync, which was non-deterministic during an upgrade (more likely for 2.5.x -> 2.6-head, but not always guaranteed).

### What was fixed, or what changes have occurred
 
The conditions `SystemNamespacesAssigned` and `DefaultNamespacesAssigned` were moved from the cluster to the system and default projects of that cluster respectively. 

### Areas or cases that should be tested

Docker install, HA install, upgrades from 2.6.2 -> 2.6-head, upgrades from 2.5.x -> 2.6-head. 

Note: updating from a later 2.6-head in which the cluster has `DefaultNamespacesAssigned` and/or `SystemNamespacesAssigned` set to `Unknown`, to a more recent `2.6-head` (at least with `41a29825b3280521965792b52634b87f2e657551`) will not fix the issue. 

### What areas could experience regressions?

Assigning system namespaces on upgrade (see below). 

### Are the repro steps accurate/minimal?

Reproduction steps should be identical to https://github.com/rancher/rancher/issues/32898#issuecomment-952177280, with the caveat that the cluster should not be configuring, and the system and default projects for that cluster should have the `SystemNamespacesAssigned` and `DefaultNamespacesAssigned` conditions set to true respectively.

**Comment by snasovich** [comment] 2021-11-18 22:31
v2.6-head build has failed, so it's not ready to be tested on that tag yet. @jakefhyde , please move to test after Rancher build succeeds.

**Comment by snasovich** [comment] 2021-11-19 03:30
There is now a successful build that includes these changes, so safe to test on v2.6-head.

**Comment by ronhorton** [comment] 2021-11-19 21:03
`Reopening this ticket as the upgrade from 2.5.11 -> 2.6-head results in clusters in UNAVAILABLE`

1. created a 2.5.11 docker install
2. created clusters - DO, EC2, GKE and Custom
3. stopped docker container
4. UI has updated to `2.6-head Commit ID 4ddeafb`
5. clusters are stuck in provisioning status
6. I cannot explore any of the clusters via the hamburger menu
7. The clusters have been `unavailable` for > 45 minutes.
<img width="1406" alt="Screen Shot 2021-11-19 at 3 52 34 PM" src="https://user-images.githubusercontent.com/89212856/142691336-06292746-6016-47b3-b54c-c2612061fc20.png">

**Comment by ronhorton** [comment] 2021-11-19 22:55
This is blocked for 2.5.11 -> 2.6-head
created https://github.com/rancher/rancher/issues/35619

**Comment by snasovich** [comment] 2021-11-19 23:00
@ronhorton , this looks like a different issue as Unavailable is different from Configuring.

Did you want for clusters to become active between steps #2 and #3?

**Comment by ronhorton** [comment] 2021-11-19 23:06
@snasovich I created a new ticket https://github.com/rancher/rancher/issues/35619 for the issue. it is different unavailable from configuring as you mention.

**Comment by ronhorton** [comment] 2021-11-19 23:23
I upgraded a 2.6.2 to 2.6-head commit ID b736007

I have two rke2 clusters - one DO and one EC2 that are both in error state:

`Failed to update fleet-default/ron-rke2-do cluster.x-k8s.io/v1alpha4, Kind=Cluster for rke-cluster fleet-default/ron-rke2-do: Internal error occurred: failed calling webhook "default.cluster.cluster.x-k8s.io": failed to call webhook: Post "<url>/mutate-cluster-x-k8s-io-v1alpha4-cluster?timeout=10s": context deadline exceeded`

checking the pods of one of the clusters, I saw `system-upgrade-controller-7c878c4798-d2g4k` image `rancher/system-upgrade-controller:v0.8.0` is terminating

**Comment by sowmyav27** [comment] 2021-11-20 22:33
**On an upgrade from 2.5.11 to 2.6-head commit id: `e322f8f`**

- Clusters - rke1 DO and GKE v2 come up Active after rancher upgrade
- Post upgrade validation. tests look good.
- `SystemNamespacesAssigned` and `DefaultNamespacesAssigned` conditions set to true on the downstream cluster

**Closed** 2021-11-21 00:21 UTC
Labels: status/blocker, kind/bug-qa, [zube]: QA Next up, feature/rancher-upgrade
