### ISSUE TITLE
agent register itslef each time the VM is restarted

### ISSUE THREAD

**Issue by VPusher** [rancher/rancher#4249] opened 2016-03-31 14:14 UTC
Rancher Version: 1.0.0
Docker Version: 1.10.1
OS: Boot2Docker (Docker Machine 0.6.0, Mac)

Steps to Reproduce: 

```
$> docker run -d --restart=always -p $RANCHER_PORT:8080 --name rancher-manager rancher/server:v1.0.0
# Go to Rancher UI and save the *Host Registration URL*
$> docker run -d --privileged -v /var/run/docker.sock:/var/run/docker.sock -v /var/lib/rancher:/var/lib/rancher -e CATTLE_AGENT_IP=192.168.99.100 rancher/agent:v0.11.0 http://192.168.99.100:8080/v1/scripts/17DA698A6C2F69412192:1459425600000:07Pv0TEZd3WHaSUCHAo4nDY
# Wait for the new host to appear in the Rancher UI.
$> docker-machine restart
```
Results: 

You can see 2 hosts registered which are in fact the same.

![screen shot 2016-03-31 at 3 55 45 pm](https://cloud.githubusercontent.com/assets/3390457/14178429/e6bdebb8-f75a-11e5-8d55-518343fdb13f.png)

Each time the VM is restarted, a new host appear. You may need to wait a bit.

Expected:

There should be only one registered host.

This is really a problem because deploying stacks afterward goes into trouble since it tries to deploy containers accross all of these fake hosts...

**Comment by deniseschannon** [comment] 2016-03-31 19:05
Duplicate of https://github.com/rancher/rancher/issues/936

Please scroll down for the comments to see if you have further questions on why this occurs. This only occurs when using boot2docker, but will not happen when using real linux hosts.

**Closed by deniseschannon** 2016-03-31 19:05 UTC
