### ISSUE TITLE
Disable cadvisor

### ISSUE THREAD

**Issue by Flowman** [rancher/rancher#3017] opened 2015-12-14 01:32 UTC
Is there a way to disable cadvisor in rancher if a 3-party monitoring tool like New Relic is in palace?

I'm running the latest 0.49.1 and cadvisor still chews up 15% of the cpu with 5 containers running for no reason.

Or at least can we change the data gather timer from 1sec to 5sec, as 1sec is a bit aggressive?

**Comment by Ilya-Kuchaev** [comment] 2015-12-15 11:33
+1

**Comment by Osso** [comment] 2015-12-17 13:41
+1

**Comment by will-chan** [comment] 2015-12-28 23:56
We should at least be able to configure the polling of data so it's not so aggressive.

**Comment by ibuildthecloud** [comment] 2015-12-29 01:34
@cloudnautique Can we at least decrease the interval?

**Comment by janeczku** [comment] 2016-01-02 20:50
+1

**Comment by cloudnautique** [comment] 2016-01-04 17:26
@ibuildthecloud, yeah, I'd like to make it configurable.

**Comment by cjellick** [comment] 2016-01-15 15:09
@cloudnautique @ibuildthecloud why are we leaning towards decreasing the interval vs disabling completely?

**Comment by cloudnautique** [comment] 2016-01-15 15:19
Yes, for now. Disabling will cause a lot of issues in user experience. In the next release we are at 5 second interval

**Comment by cjellick** [comment] 2016-01-15 15:24
To elaborate for people following the issue, the core of the issue is that all of our graphs for containers and hosts would stop working?

**Comment by jwhitcraft** [comment] 2016-01-15 16:20
+1 for this as we are using sysdig and both are chewing up system resources collecting the same data.

**Comment by cloudnautique** [comment] 2016-01-15 16:26
@cjellick, correct. We also use it to get some of the data about the host since it was easily available in the api. We would need to collect info from other sources, which is very doable just not the highest priority.

**Comment by haswalt** [comment] 2016-01-26 10:44
@cjellick I'd like to see an option to disable it as well as tune it. We have our own monitoring system in place that retrieves all the information we need which makes and graphing inside rancher obsolete.

cAdvisor does get pretty resource hungry I find on hosts with lots of containers and for us it's extra churn as we have our system doing similar tasks. If we can't disable it at least lets not set fixed durations as options. I'd like to be able to turn it off or in the least make it only run once a month or something (effectively disabling it).

Unless cAdvisor data is required for some other purpose in Rancher other than reporting?

**Comment by deitch** [comment] 2016-01-27 08:50
The flip side might be the ability to leverage the cAdvisor data by integrating it from Rancher into other monitoring systems?

**Comment by CumpsD** [comment] 2016-03-21 20:02
It would be very nice to have this, we will be using zabbix to monitor it and it makes no sense to have multiple monitoring systems running. If it is needed for Rancher UI, lowering it to some interval like once a day would be fine too :)

**Comment by inwaar** [comment] 2016-08-02 20:20
+1

**Comment by ict4ngo** [comment] 2016-10-15 17:02
+1

**Comment by aemneina** [comment] 2016-10-15 18:34
quite a few duplicate issues on this one, closing in favor of https://github.com/rancher/rancher/issues/2241

**Comment by aemneina** [comment] 2016-10-15 18:53
actually reopening and waiting someone to validate this in 1.2.0-pre4

**Comment by deniseschannon** [comment] 2016-11-29 07:27
We are no longer using cadvisor as of v1.2.0 instead we're using `docker stats` for container stats and https://github.com/shirou/gopsutil for host stats.

**Closed by deniseschannon** 2016-11-29 07:27 UTC
Labels: kind/enhancement
