### ISSUE TITLE
[UI] Upgrading service doesn't show applied labels

### ISSUE THREAD

**Issue by xaka** [rancher/rancher#3063] opened 2015-12-18 01:51 UTC
Here is what service information looks like:
<img width="1420" alt="screen shot 2015-12-17 at 5 43 09 pm" src="https://cloud.githubusercontent.com/assets/504813/11887201/b348b568-a4e6-11e5-9e56-a1bd6acb1d3d.png">

And here is what upgrading service looks like:
<img width="1440" alt="screen shot 2015-12-17 at 5 43 49 pm" src="https://cloud.githubusercontent.com/assets/504813/11887204/b90ed6c6-a4e6-11e5-8d3b-6809df752a40.png">

Component | Version
--- | ---
Rancher | v0.50.1
Cattle | v0.127.0
User Interface | v0.74.0
Rancher Compose | v0.6.2

**Comment by deniseschannon** [comment] 2015-12-18 02:18
Cloning and upgrading go through the same UI process, so the comments are the same.

This is a duplicate of #2342

But in v0.50.1, you should have UI options for most of the UI options for labels.

#2550

There is a small bug with container hostname when cloning again. 
#3045

**Closed by deniseschannon** 2015-12-18 02:18 UTC

**Comment by xaka** [comment] 2015-12-18 02:24
Got it. Thanks and apologize for duplication! I'm sure GitHub has enough storage for new issue IDs.
