### ISSUE TITLE
Rancher monitoring alert-manager is broken

### ISSUE THREAD

**Issue by abhi1693** [rancher/rancher#31003] opened 2021-01-27 16:08 UTC
**What kind of request is this (question/bug/enhancement/feature request):**
bug

**Steps to reproduce (least amount of steps as possible):**
Install a fresh rancher-monitoring v9.4.202 with default values

**Result:**
Secret `alertmanager-rancher-monitoring-alertmanager` is never created. Instead, I found `alertmanager-rancher-monitoring-pre-install`
```
MountVolume.SetUp failed for volume "config-volume" : secret "alertmanager-rancher-monitoring-alertmanager" not found
```

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): v2.5.5
- Installation option (single install/HA): HA

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported):
- Machine type (cloud/VM/metal) and specifications (CPU/memory):
- Kubernetes version (use `kubectl version`):

```
(paste the output here)
```

- Docker version (use `docker version`):

```
(paste the output here)
```

**Comment by slickwarren** [comment] 2021-01-27 18:18
I attempted to reproduce this using:
* rancher v2.5.5 HA Cluster
* Monitoring v9.4.202

with the following cluster types:
* imported cluster (6vCPU)
* provider cluster (DO, 8vCPU)
* also tested installing on local cluster (6vCPU) (not recommended, but was trying to see what user could have done to get to this state

All of the above were able to install monitoring with the secret added successfully 
<img width="907" alt="Screen Shot 2021-01-27 at 9 09 08 AM" src="https://user-images.githubusercontent.com/16691014/106034687-117aa080-6088-11eb-97be-055a5775ebd5.png">

the `pre-install` secret is created while bringing up monitoring, and removed once it has successfully deployed. I am able to see the pre-install secret during `install` phase 
<img width="876" alt="Screen Shot 2021-01-27 at 9 36 55 AM" src="https://user-images.githubusercontent.com/16691014/106034818-3cfd8b00-6088-11eb-9283-cbbeeb67c947.png"> and can confirm they are removed after monitoring completes install.

I was unable to reproduce the issue with any of the above configurations.

**Comment by abhi1693** [comment] 2021-01-27 20:58
@slickwarren Earlier when v2.5.3 was released I had tried to install the monitoring, however was unsuccessful so removed it from the cluster. Today, I tried again and I thought I was doing a fresh install as the app was not already there.

Is it possible that something was not removed completely the last time which caused this issue? Because, since posted this issue, I have tried several more times and it results in the same issue every single time.

I just manually created the required secret ultimately myself.

**Comment by jiaqiluo** [comment] 2021-01-27 21:19
Hi @abhi1693 This is a rare issue that we can not reproduce on our setup.  
Can you provide some more information about the cluster where you try to install the monitoring? For example, the number and size of nodes in the cluster? 
Is it possible for you to try installing monitoring on a new cluster?

**Comment by abhi1693** [comment] 2021-01-27 23:28
@jiaqiluo I have an on-prem cluster using vsphere running on 3 nodes cluster with 8 CPU and 12G RAM. I sifted through the configuration and found two keys that run cleanup on any old remnant of the previous installs. Once I enabled them I was successfully able to install them every time.

**Comment by jiaqiluo** [comment] 2021-01-28 00:12
@abhi1693 I am glad to hear that monitoring is working now. 

All components of Monitoring are under the namespace `cattle-monitoring-system`. After you delete the monitoring app( both the `rancher-monitoring` and `rancher-monitoring-crd`) there will still be some secrets left in the namespace.  Unless you want to keep some configuration from the previous installation, you need to delete those secrets before reinstall monitoring.

**Comment by abhi1693** [comment] 2021-01-28 00:19
@jiaqiluo Can you guys document these things? As a user it's hard to troubleshoot sometimes when the application is built by a third party

**Comment by slickwarren** [comment] 2021-01-28 03:08
I was able to install monitoring on a vsphere cluster using rancher v2.5.3, uninstall monitoring, upgrade the cluster to v2.5.5, and reinstall monitoring without running into this issue (I left the secrets the way our installer handles them, and didn't hit this issue). 
<img width="1451" alt="Screen Shot 2021-01-27 at 6 46 13 PM" src="https://user-images.githubusercontent.com/16691014/106084321-026d1000-60d3-11eb-918d-cceca7bb1938.png">

<img width="854" alt="Screen Shot 2021-01-27 at 7 08 02 PM" src="https://user-images.githubusercontent.com/16691014/106084327-05680080-60d3-11eb-9007-7be469381ccd.png">

This was likely some sort of cleanup issue like you suggested originally.  We do have instructions for [uninstalling monitoring on 2.5.x,](https://rancher.com/docs/rancher/v2.x/en/monitoring-alerting/v2.5/#uninstall-monitoring) but it does not include the details about removing secrets, as we have rarely seen it be an issue.

**Comment by abhi1693** [comment] 2021-01-28 03:24
If this is not reproducible, you can close the issue as I found the workaround with the cleanupresource key in the chart

**Comment by slickwarren** [comment] 2021-01-28 15:58
https://github.com/rancher/rancher/issues/31003#issuecomment-768771707
https://github.com/rancher/rancher/issues/31003#issuecomment-768766502
https://github.com/rancher/rancher/issues/31003#issuecomment-768477872
not reproducible, closing this out

**Closed by slickwarren** 2021-01-28 15:58 UTC
