### ISSUE TITLE
Rancher DNS not registering Service without Selector

### ISSUE THREAD

**Issue by aemneina** [rancher/rancher#6190] opened 2016-10-07 17:22 UTC
I’ve setup a [Service without Selector](http://kubernetes.io/docs/user-guide/services/#services-without-selectors)

The service works great.  But the service host name is not setup in DNS, like with other services.  As well, adding a Service Alias also does not add it to DNS as I would expect.

The reason for doing this, I want separation of control for Databases to be managed external to the environment.  And I want to be able to set up a callable host by name.  The ENV variables for host and port are added, but this does not make it easy for systems that require configuration params to a host.

**Comment by alena1108** [comment] 2016-10-12 18:25
The issue is fixed with a new "microserviced" dns: https://github.com/rancher/rancher-dns/pull/35

**Comment by soumyalj** [comment] 2016-11-14 19:51
Tested with master. Created a service(k8test2) without a selector and without any pods behind it.
ping the service by name from another container in the same namespace. It resolves to the right ip address.
```
root@k8testrc1-515a2:/# ping k8test2
PING k8test2.default.svc.cluster.local (10.43.60.55): 48 data bytes
```

**Closed by soumyalj** 2016-11-14 19:51 UTC
Labels: kind/enhancement, priority/0, status/resolved, status/to-test
