### ISSUE TITLE
[BUG] rancher-system-agent needs to stop attempting to reconcile plan/watching if the K8s API server is unhealthy/the secret changes 

### ISSUE THREAD

**Issue by Oats87** [rancher/rancher#41200] opened 2023-04-18 19:49 UTC
**Rancher Server Setup**
- Rancher version: v2.7.2
- Installation option (Docker install/Helm Chart):
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc):
- Proxy/Cert Details:

**Information about the Cluster**
Downstream cluster system-agent 

**User Information**
N/A

**Describe the bug**
The `rancher-system-agent` does not gracefully handle situations when the secret being reconciled is deleted/recreated, and does not handle situations when the API server goes unhealthy. 

1. If the api server dies, and the system-agent was in the middle of reconciling a plan. it will continuously try to reconcile the plan repeatedly until it is able to update the secret. 
2. If the plan secret is deleted/recreated under the system-agent and the resourceVersion changes -- this causes the watch cache to go out of date and the agent stops reconciling plans

**To Reproduce Scenario 1**
Provision a downstream K3s/RKE2 cluster
Watch the `rancher-system-agent` logs and while it is executing a plan, stop the local cluster/stop rancher (need to make sure you can stop the cluster/rancher fast enough)

**Result Scenario 1**
The `rancher-system-agent` will continously attempt to reconcile the plan and keep erroring

**Expected Result Scenario 1**
`rancher-system-agent` should stop running and wait until the api server is healthy again.

**To Reproduce Scenario 2**
Provision a downstream K3s/RKE2 cluster managed by an HA Rancher cluster
After the downstream cluster is provisioned, stop Rancher
Take a copy of the secret of the `machine-plan` of the node you are operating on
Delete the secret from the local cluster
Create the secret `create -f` 
Start Rancher

**Result Scenario 2**
The `rancher-system-agent` won't do anything with the secret even if the plan changes

**Expected Result Scenario 2**
The `rancher-system-agent` should detect that the secret changed and restart.

**Screenshots**

**Additional context**

SURE-6267

**Comment by sowmyav27** [comment] 2023-04-25 22:01
Reopening this since there are no automated tests

**Comment by sowmyav27** [comment] 2023-05-10 04:25
As per offline conversation - This is an edge case. Difficult to reproduce this. marked as `dev-validate`. 
@Oats87 to add automated tests to check the agent is not reconciling often.

**Comment by Oats87** [comment] 2023-05-15 22:36
https://github.com/rancher/rancher/pull/41459 (specifically: https://github.com/rancher/rancher/pull/41459/files#diff-347b85f4b27f0bc66ce4f2e3c4ca653d3f1c1ffb9e2b4f7c35814cf7881fd8a5R526) adds a check to ensure that the conflicts are not occurring

**Comment by Sahota1225** [comment] 2023-05-17 18:03
@jakefhyde - Can you please validate this issue

**Comment by jakefhyde** [comment] 2023-05-26 18:17
## Test Results - :heavy_check_mark: 
Verified with Docker install and HA install on v2.7-head `fbca7c3`
### Scenario 1 (apiserver is not reachable)
- Blocked traffic to apiserver on downstream host
- `system-agent` stops trying to reconcile until apiserver traffic is allowed again
### Scenario 2 (plan secret is recreated)
- Recreated plan secret
- `system-agent` detects the change and restarts to reconcile properly

**Closed** 2023-05-31 21:52 UTC
Labels: kind/bug, [zube]: To Test, status/dev-validate, area/system-agent, area/provisioning-v2, team/area2, JIRA, QA/None, team/area2/sc
