### ISSUE TITLE
Cluster stuck in "updating" state when one of the control plane is turned off and a new worker node was added.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#22845] opened 2019-09-13 04:45 UTC
Rancher server version - v2.3.0-rc3
Steps to reproduce the problem:

Create a custom cluster with following configuration:

1 control node - CN1
1 etcd node 
1 worker node 

Wait for the cluster to become "active" and deploy few workloads.
Add 1 more control node and wait for it to become "active".
Power down CN1 , so that it gets to "Unavailable" state.
Add 1 more worker node.
Cluster gets stuck in "Updating" state with following error message:

```
This cluster is currently Updating state for ever.

Delete https://<control node that is currently unavailable>:6443/api/v1/namespaces/default/serviceaccounts/netes-default: can not build dialer to c-kzmcg:m-e10726c13dfd
```

Worker node gets  stuck in "registering" state forever.

Following messages show up repeatedly in logs:

```
2019/09/13 04:27:45 [INFO] Provisioning cluster [c-kzmcg]
2019/09/13 04:27:45 [INFO] Updating cluster [c-kzmcg]
2019/09/13 04:27:45 [DEBUG] REST UPDATE apis/management.cattle.io/v3//clusters/c-kzmcg
2019/09/13 04:27:45 [DEBUG] REST GET apis/management.cattle.io/v3//clusters/c-kzmcg
2019/09/13 04:27:47 [DEBUG] NodeController calling handler node-syncer ip-**
2019/09/13 04:27:47 [DEBUG] REST DELETE apis/project.cattle.io/v3/p-8lgj4/apps/rancher-logging
2019/09/13 04:27:47 [DEBUG] NodeController calling handler nodesSyncer ip-**
2019/09/13 04:27:47 [DEBUG] NodeController calling handler init-windows-alert ip-**
2019/09/13 04:27:47 [DEBUG] NodeController calling handler cluster-monitoring-sync-windows-node-handler ip-**
2019/09/13 04:27:49 [DEBUG] The number of nodes sent to the plan: 3
2019/09/13 04:27:49 [INFO] svcOption False v1.15
2019/09/13 04:27:49 [INFO] svcOption False wv1.15
2019/09/13 04:27:49 [DEBUG] No DNS provider configured, setting default based on cluster version [1.15.3-rancher3-1]
2019/09/13 04:27:49 [DEBUG] DNS provider set to [coredns]
2019/09/13 04:27:49 [DEBUG] Host: ** has role: controlplane
2019/09/13 04:27:49 [DEBUG] Host: ** has role: controlplane
2019/09/13 04:27:49 [DEBUG] Host: ** has role: etcd
2019/09/13 04:27:49 [DEBUG] Extracted version [v1.15.3-rancher3] from image [rancher/hyperkube:v1.15.3-rancher3]
2019/09/13 04:27:49 [DEBUG] Extracted version [v1.15.3-rancher3] from image [rancher/hyperkube:v1.15.3-rancher3]
2019/09/13 04:27:49 [DEBUG] Extracted version [v1.15.3-rancher3] from image [rancher/hyperkube:v1.15.3-rancher3]
2019/09/13 04:27:49 [DEBUG] Extracted version [v1.15.3-rancher3] from image [rancher/hyperkube:v1.15.3-rancher3]
2019/09/13 04:27:49 [DEBUG] Extracted version [v1.15.3-rancher3] from image [rancher/hyperkube:v1.15.3-rancher3]
2019/09/13 04:27:49 [DEBUG] Extracted version [v1.15.3-rancher3] from image [rancher/hyperkube:v1.15.3-rancher3]
2019/09/13 04:27:49 [DEBUG] Extracted version [v1.15.3-rancher3] from image [rancher/hyperkube:v1.15.3-rancher3]
2019/09/13 04:27:49 [DEBUG] Extracted version [v1.15.3-rancher3] from image [rancher/hyperkube:v1.15.3-rancher3]
2019/09/13 04:27:49 [DEBUG] Extracted version [v1.15.3-rancher3] from image [rancher/hyperkube:v1.15.3-rancher3]
2019/09/13 04:27:49 [DEBUG] Extracted version [v1.15.3-rancher3] from image [rancher/hyperkube:v1.15.3-rancher3]
2019/09/13 04:27:49 [DEBUG] Extracted version [v1.15.3-rancher3] from image [rancher/hyperkube:v1.15.3-rancher3]
2019/09/13 04:27:49 [DEBUG] Extracted version [v1.15.3-rancher3] from image [rancher/hyperkube:v1.15.3-rancher3]
2019/09/13 04:27:49 [DEBUG] Extracted version [v3.3.10-rancher1] from image [rancher/coreos-etcd:v3.3.10-rancher1]
2019/09/13 04:27:49 [DEBUG] Version [3.3.10-rancher1] is equal or higher than version [3.2.99]
2019/09/13 04:27:49 [DEBUG] REST GET apis/management.cattle.io/v3/c-kzmcg/clusterregistrationtokens/system
2019/09/13 04:27:50 [DEBUG] REST GET api//v1//namespaces/kube-system
2019/09/13 04:27:50 [DEBUG] REST LIST api//v1//componentstatuses

2019/09/13 04:27:50 [INFO] kontainerdriver rancherkubernetesengine listening on address 127.0.0.1:41035
2019/09/13 04:27:50 [DEBUG] RPC GrpcServer listening on address 127.0.0.1:41035
2019/09/13 04:27:50 [INFO] kontainerdriver rancherkubernetesengine stopped
2019/09/13 04:27:50 [DEBUG] REST UPDATE apis/management.cattle.io/v3//clusters/c-kzmcg
2019/09/13 04:27:50 [DEBUG] ClusterController calling handler user-controllers-controller c-kzmcg
2019/09/13 04:27:50 [DEBUG] ClusterController calling handler global-admin-cluster-sync c-kzmcg
2019/09/13 04:27:50 [DEBUG] ClusterController calling handler cluster-trigger-logging-deployer-updator c-kzmcg
2019/09/13 04:27:50 [DEBUG] REST DELETE apis/project.cattle.io/v3/p-8lgj4/apps/rancher-logging
2019/09/13 04:27:50 [DEBUG] ClusterController calling handler cluster-stats c-kzmcg
2019/09/13 04:27:50 [DEBUG] ClusterController calling handler clusterHandler c-kzmcg
2019/09/13 04:27:50 [DEBUG] ClusterController calling handler clusterNetAnnHandler c-kzmcg
2019/09/13 04:27:50 [DEBUG] ClusterController calling handler ClusterSyncHandler c-kzmcg
2019/09/13 04:27:50 [DEBUG] ClusterController calling handler prometheus-operator-handler c-kzmcg
2019/09/13 04:27:50 [DEBUG] REST LIST apis/management.cattle.io/v3/c-kzmcg/projects
2019/09/13 04:27:50 [DEBUG] REST UPDATE apis/management.cattle.io/v3//clusters/c-kzmcg
2019/09/13 04:27:50 [DEBUG] ClusterController calling handler cluster-monitoring-handler c-kzmcg
2019/09/13 04:27:50 [DEBUG] ClusterController calling handler istio-cluster-status-handler c-kzmcg
2019/09/13 04:27:50 [DEBUG] ClusterController calling handler certificate-expiration c-kzmcg
2019/09/13 04:27:50 [DEBUG] ClusterController calling handler temporary-credentials c-kzmcg
2019/09/13 04:27:50 [DEBUG] ClusterController calling handler management-mcapp-cluster-controller c-kzmcg
2019/09/13 04:27:50 [DEBUG] ClusterController calling handler mgmt-cluster-rbac-remove c-kzmcg
2019/09/13 04:27:50 [ERROR] ClusterController c-kzmcg [cluster-provisioner-controller] failed with : Delete https://**:6443/api/v1/namespaces/default/serviceaccounts/netes-default: can not build dialer to c-kzmcg:m-e10726c13dfd
2019/09/13 04:27:50 [DEBUG] ClusterController calling handler mgmt-cluster-rbac-delete c-kzmcg
2019/09/13 04:27:50 [DEBUG] ClusterController calling handler cluster-agent-controller-cleanup c-kzmcg
2019/09/13 04:27:50 [DEBUG] ClusterController calling handler clusterCreateUpdate c-kzmcg
2019/09/13 04:27:50 [DEBUG] ClusterController calling handler cluster-deploy c-kzmcg
2019/09/13 04:27:50 [DEBUG] ClusterController calling handler cluster-scoped-gc c-kzmcg
2019/09/13 04:27:50 [DEBUG] ClusterController calling handler cluster-provisioner-controller c-kzmcg 

```
gz#8240

**Comment by moelsayed** [comment] 2019-09-18 18:00
Currently, we don't have any logic to trigger a cluster update when the cluster control node fails. So, this case shouldn't pass. However, in testing we see it passing sometime. 

This is because when we deploy an rke cluster, we pick the _first_ control plane node and use it in Rancher as the API endpoint for that cluster. In the instances where this test fails, that API endpoint points to the dead node. And that doesn't get updated until you remove the dead node from the cluster. In this cases the nodes are passed to rke in order of addition to the cluster 1) CN1 2) CN2.

However, if the nodes are passed in a different order when CN2 is added: 1) CN2, 2) CN1, rke will update the API endpoint with the IP of the _first_ control plane node, in this case CN2. In this case, the dead node (CN1) doesn't affect the cluster and the test case passes.

**Comment by mattmattox** [comment] 2019-09-24 20:03
I saw this issue too. It looks like Rancher manged cluster (custom) are not impacted because Rancher can failover to cattle-node-agent if cattle-cluster-agent is unavailable. But in imported clusters, Rancher won't failover and the only way to restore access is to bring the control node back online or force a reschedule of the cattle-node-agent pod.
NOTE: I was able to work around issue using https://github.com/mattmattox/drain-node-on-crash

**Comment by maggieliu** [comment] 2020-12-08 18:12
@sangeethah @sowmyav27 Can you please check if this issue is still there in the latest Rancher release? We have made changes in zero downtime that could have fixed this.

**Comment by anupama2501** [comment] 2021-01-07 00:24
Issue is seen on 2.4-head [v2.4-4544-head]
Same steps followed as above:

Create a custom cluster[AWS] with following configuration:

1 control node - CN1
1 etcd node
1 worker node

Wait for the cluster to become "active" and deploy few workloads.
Add 1 more control node and wait for it to become "active".
Power down CN1 , so that it gets to "Unavailable" state.
Add 1 more worker node.
Cluster gets stuck in "Updating" state with following error message:
<img width="1305" alt="Screen Shot 2021-01-06 at 4 16 59 PM" src="https://user-images.githubusercontent.com/38144301/103835464-35c00000-503b-11eb-9c2c-1ff7fe8bed8b.png">

Some logs on etcd
<img width="1101" alt="Screen Shot 2021-01-06 at 4 21 59 PM" src="https://user-images.githubusercontent.com/38144301/103835567-6d2eac80-503b-11eb-8cf9-b5cbbad99860.png">

**Comment by kinarashah** [comment] 2021-01-13 20:41
This isn't feasible to fix in v2.4.13, requires more investigation into how we handle API endpoints and agent fallback logic.

**Comment by StrongMonkey** [comment] 2021-04-02 00:37
I am not able to reproduce this issue in 2.5-head, could things be changed since there? Can we retest it against 2.5?

**Comment by sowmyav27** [comment] 2021-04-09 01:24
**on 2.5-head commit id: `ebee7eb3`**

- Create a custom cluster with following configuration:
```
1 control node - CN1
1 etcd node
2 worker node
```

- Wait for the cluster to become "active"\\
- Add 1 more control node and wait for it to become "active".
- Power down CN1 , so that it gets to "Unavailable" state.
- Add 1 more worker node.
- Cluster gets stuck in "Updating" state with following error: 

```
This cluster is currently Error.

Delete "https://<>:6443/api/v1/namespaces/default/serviceaccounts/netes-default": dial tcp 172.31.15.126:6443: connect: no route to host
```

**Comment by Jono-SUSE-Rancher** [comment] 2021-04-21 21:47
@StrongMonkey - It looks like Sowmya was able to reproduce this on 2.5 head - can you look at the configuration she has listed and see if you can dive into fixing this?

**Comment by StrongMonkey** [comment] 2021-04-21 22:55
@Jono-SUSE-Rancher Yes I will look into it. I tried myself but no luck at reproducing it. Will try it again.

**Comment by sowmyav27** [comment] 2021-06-23 01:56
**On 2.5-head `2412e011` and master-head `d44698d`**

- https://github.com/rancher/rancher/issues/22845#issuecomment-816336854 --> Set of steps did not reproduce the issue. 
- Closing this now. Will reopen/log new issue if we see it again

**Closed by sowmyav27** 2021-06-23 01:56 UTC
Labels: QA/S, [zube]: To Test, internal, kind/bug-qa
