### ISSUE TITLE
[RFE] vSphere cluster creation failures lead to cruft

### ISSUE THREAD

**Issue by Woovie** [rancher/rancher#45580] opened 2024-05-23 01:52 UTC
**Is your feature request related to a problem? Please describe.**
When provisioning a virtual machine to vSphere with a misconfiguration that prevents the VM from starting, you are left with a stopped virtual machine that Rancher will not clean up. In Rancher, you are left with several objects as well that must be manually deleted.

**Describe the solution you'd like**
The virtual machine should be deleted if an error is detected, and any cruft objects removed.

**Describe alternatives you've considered**
Manually handling deletion of the VM and these objects is possible, but due to the nature of complexity can be confusing and time consuming.

**Additional context**
I feel that some may want this to be optional so they can manually recover the state. Perhaps an option in Rancher or a checkbox per-cluster deployment?

This has been an issue for myself and many others. It would be nice to have a solution to simplify the process and reduce clean up time when quickly iterating or needing to fix an issue.

**Comment by jiaqiluo** [comment] 2024-07-24 00:03
close as duplicate of https://github.com/rancher/rancher/issues/44212

**Closed by jiaqiluo** 2024-07-24 00:03 UTC
Labels: kind/enhancement
