### ISSUE TITLE
[BUG] Unable to disable PSPs for Istio chart on k8s 1.24.10

### ISSUE THREAD

**Issue by nickwsuse** [rancher/rancher#40913] opened 2023-03-16 23:31 UTC
**Rancher Server Setup**
- Rancher version: `v2.7.2-rc6`
- Installation option (Docker install/Helm Chart): `Helm`
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): `RKE1`
- Proxy/Cert Details: `byo-valid`

**Information about the Cluster**
- Kubernetes version: `v1.24.10`
- Cluster Type (Local/Downstream): `Downstream`
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider): `Hosted: EC2`

**User Information**
- What is the role of the user logged in? (Admin/Cluster Owner/Cluster Member/Project Owner/Project Member/Custom): `Admin`

**Describe the bug**

After installing Istio with `global.cattle.psp.enabled = true`, trying to re-install the chart with `global.cattle.psp.enabled = false` fails. The log shows the following: `Deployment is not ready: istio-system/rancher-istio-tracing. 0 out of 1 expected pods are ready`

Logs:
```
Events:
  Type     Reason       Age                  From               Message
  ----     ------       ----                 ----               -------
  Normal   Scheduled    11m                  default-scheduler  Successfully assigned istio-system/rancher-istio-tracing-864b864b7c-gtqhm to nick-istio-rke1-w1
  Warning  FailedMount  83s (x13 over 11m)   kubelet            MountVolume.SetUp failed for volume "kube-api-access-plrjz" : failed to fetch token: serviceaccounts "rancher-istio-tracing" not found
  Warning  FailedMount  33s (x5 over 9m36s)  kubelet            Unable to attach or mount volumes: unmounted volumes=[kube-api-access-plrjz], unattached volumes=[data kube-api-access-plrjz]: timed out waiting for the condition
```

**To Reproduce**
1. On an HA cluster, provision an RKE1 downstream cluster on k8s `v1.24.10` // `v1.24.10-rancher4-1`
2. Install the Monitoring chart `v102.0.0+up40.1.2`
3. Begin to install the Istio chart `v102.0.0+up1.15.3 `
4. Before finishing the install of Istio chart, click the `Edit YAML` button
5. Change the `global.cattle.psp.enabled` value to `true`
6. Finish installing the Istio chart
7. Once installed, go back to the Istio chart page
8. Click `Update`
9. Go through the same setup steps and click the `Edit YAML` button again
10. Change the `global.cattle.psp.enabled` value to `false`
11. Finish the upgrade process

**Result**
The chart upgrade and disabling of PSPs fails. PSPs are removed, but the app shows as `Failed` rather than `Deployed`

**Expected Result**
The chart upgrade and disabling of PSPs succeeds

**Screenshots**
Current PSP Setting/Before Setting to False
![image](https://user-images.githubusercontent.com/107147272/225772968-c6c19400-c18d-4add-bec3-3ed4943d2b1e.png)

Failure Logs
![image](https://user-images.githubusercontent.com/107147272/225772952-6102bbc9-4305-4067-93e1-82b73a7366dc.png)

**Comment by stormqueen1990** [comment] 2023-03-20 22:50
I took another look at this and could not really figure out what is going on. On pulling the template with `helm get template` no references to the `rancher-istio-tracing` service account really exist, but the fact that the service account is missing is what's making the rollout fail.

As a workaround, I tried re-creating the service account and that makes the upgrade succeed. One possible way forward would be to remove the service account from the PSP condition (since it is not directly related to PSPs) so that it does not get removed when removing PSPs.

**Comment by vardhaman22** [comment] 2023-03-21 11:13
Hi @stormqueen1990 
in the rancher-tracing deployment, when we install the istio chart with psp.enabled=true the `rancher-istio-tracing`  serviceaccount was added.
When we upgrade the chart with psp.enabled=false then in the deployment template there is no field for `serviceAccountName` as per the condition set in the deployment.yaml file.
And since helm do a patch operation while updating kubernetes object... the serviceaccount for the deployment was still    `rancher-istio-tracing` and not `default` which was causing the issue.
I have raised a [PR](https://github.com/rancher/charts/pull/2495) to move that service account in a different file. please review.

**Comment by stormqueen1990** [comment] 2023-03-21 13:57
> Hi @stormqueen1990 in the rancher-tracing deployment, when we install the istio chart with psp.enabled=true the `rancher-istio-tracing` serviceaccount was added. When we upgrade the chart with psp.enabled=false then in the deployment template there is no field for `serviceAccountName` as per the condition set in the deployment.yaml file. And since helm do a patch operation while updating kubernetes object... the serviceaccount for the deployment was still `rancher-istio-tracing` and not `default` which was causing the issue. I have raised a [PR](https://github.com/rancher/charts/pull/2495) to move that service account in a different file. please review.

That makes sense to me, @vardhaman22. What I found odd is that I can reproduce the issue occasionally, and sometimes it just works. I'm now wondering if it could be an issue on Helm itself.

**Comment by rishabhmsra** [comment] 2023-03-24 11:17
Validated it on rancher v2.7.2-rc7 HA setup
- Provisioned RKE1 node driver, ec2 cluster - k8s v1.24.10-rancher4-1
- Install Monitoring chart v102.0.0+up40.1.2
- Installed Istio chart v102.0.0+up1.15.3 with `global.cattle.psp.enabled` set to `true`
- Chart installed successfully.
- Updated istio chart to same version with `global.cattle.psp.enabled` set to `false` this time
- Chart updated successfully:

![istio](https://user-images.githubusercontent.com/36376154/227505346-fdcf00b3-3e83-4c2b-a647-154ff0d70073.png)

- Also validated istio P0 scenarios and it's working as expected.

Result:
- Chart upgraded successfully with PSPs disabled, hence closing the issue.

**Closed by rishabhmsra** 2023-03-24 11:17 UTC
Labels: kind/bug, [zube]: QA Working, feature/charts-istio, team/area3, team/infracloud
