### ISSUE TITLE
The canal network does not work after launching the catalog

### ISSUE THREAD

**Issue by kingsd041** [rancher/rancher#13072] opened 2018-04-25 13:23 UTC
**Rancher versions:** 
rancher/server: Rancher 2.0 04/25 master

**Docker version: (`docker version`,`docker info` preferred)**
17.03.2-ce
**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
4.4.0-1052-aws
**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
AWS
**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**
Kubernetes
**Steps to Reproduce:**
1. Add a custom cluster and use the `canal` network
2. Launch wordpress in the catalog (I also tested mysql)
**Results:**
Wordpress failed to start, wordpress-wordpress logs can see error messages:`Error executing 'postInstallation': Failed to connect to wordpress-mariadb:3306 after 36 tries`. 
At this point I try to access the pod address or public address in the container and are unreachable
Later I found that `canal` is not working properly, one of the canal container is always crashed and the networking access is dead, but k8s cluster with `flannel network fabric` works fine
```
> kubectl get pod -n kube-system
NAME                                  READY     STATUS    RESTARTS   AGE
canal-s7sr4                           2/3       Running   9          31m
kube-dns-7dfdc4897f-qhmll             3/3       Running   0          31m
kube-dns-autoscaler-6c4b786f5-bnlfv   1/1       Running   0          31m

>kubectl describe pod canal-s7sr4 -n kube-system
...
  Warning  Unhealthy              14m (x65 over 46m)  kubelet, ip-172-31-5-253  Liveness probe failed: Get http://172.31.5.253:9099/liveness: dial tcp 172.31.5.253:9099: getsockopt: connection refused
  Warning  BackOff                4m (x130 over 41m)  kubelet, ip-172-31-5-253  Back-off restarting failed container
```

**Comment by superseb** [comment] 2018-04-25 13:26
Sounds like a duplicate of https://github.com/rancher/rancher/issues/13060

**Comment by leodotcloud** [comment] 2018-04-25 22:40
https://github.com/projectcalico/libcalico-go/issues/770

**Comment by deniseschannon** [comment] 2018-04-26 03:25
Closing as duplicate

**Closed by deniseschannon** 2018-04-26 03:25 UTC
Labels: version/2.0
