### ISSUE TITLE
rancher provisionning openstack

### ISSUE THREAD

**Issue by fturiot** [rancher/rancher#1770] opened 2015-08-09 18:09 UTC
Hi,
Why openstack provisionning not appear in choice ?

**Comment by deniseschannon** [comment] 2015-08-19 21:30
This is a duplicate of https://github.com/rancher/rancher/issues/1170. The API is supported for OpenStack, but the UI doesn't show the choices yet. It will be addressed in several weeks.

**Closed by deniseschannon** 2015-08-19 21:30 UTC
