### ISSUE TITLE
[Load Balancer] How to bind rancher balancer port to host

### ISSUE THREAD

**Issue by ndelitski** [rancher/rancher#2291] opened 2015-10-09 18:02 UTC
Using Rancher OS 0.3.3 ami-fcb7f78b
Latest Rancher server

docker-compose template:
```yml
rancher-lb:
  ports:
  - 80:80
  restart: always
  external_links:
  - conf/conf-app:conf-app
  labels:
    io.rancher.scheduler.global: 'true'
    io.rancher.loadbalancer.target.conf/conf-app: conf.mydomain.com
  tty: true
  image: rancher/load-balancer-service
  stdin_open: true
```
Everything works great when accessing by LB ip:
```
curl -H 'Host: conf.mydomain.com' 10.42.158.130
```
But i can't reach 80 port on host, seems docker didn't bind container's 80 port to host network.
Im going to deploy rancher LB service in v7 mode on each host, proxied with AWS ELB in tcp mode, so i need automaticaly bind LB port to host. How can i achieve this if ports section doesn't seem to work with `rancher/load-balancer-service` image?

**Comment by vincent99** [comment] 2015-10-09 18:26
If you're running that `curl` on the same host as the container is running on, the problem is that hairpin NAT (a request to the public IP of the host mapped to a container on the same host) does not currently work (https://github.com/rancher/rancher/issues/1920).  If that is the problem, ELB or any other computer would be able to talk to it fine.

**Comment by deniseschannon** [comment] 2015-11-12 04:15
@ndelitski I'm going to close this assuming you need the Hairpin NAT to work (#1920).

**Closed by deniseschannon** 2015-11-12 04:15 UTC
