### ISSUE TITLE
Evaluate replacing loglevel's Go binary by a shell script implementation

### ISSUE THREAD

**Issue by macedogm** [rancher/rancher#45726] opened 2024-06-10 13:30 UTC
SURE-8512

The current [loglevel](https://github.com/rancher/loglevel/) implementation uses a Go binary for simply setting Rancher's log level settings, as documented in https://www.suse.com/support/kb/doc/?id=000020239. Ideally it can be replaced by a simple Shell script:
*  https://github.com/rancher/rancher/pull/47194

This will reduce the maintenance burden and future Go related CVEs.

**Comment by macedogm** [comment] 2024-06-10 13:31
PRs to bump loglevel to reduce CVE noise:
- https://github.com/rancher/rancher/pull/45690
- https://github.com/rancher/rancher/pull/45689
- https://github.com/rancher/rancher/pull/45688

**Comment by Jono-SUSE-Rancher** [comment] 2024-08-26 20:46
Closing this as done since all of Gui's above PRs were merged.
cc: @MKlimuszka

**Comment by brandond** [comment] 2024-09-19 17:19
Reopening as the loglevel binary has not actually been eliminated. We are going to have to keep rebuilding it to fix golang stdlib vulns until it is replaced with something else.

**Comment by macedogm** [comment] 2024-09-19 17:47
PR https://github.com/rancher/rancher/pull/47194

**Comment by MbolotSuse** [comment] 2024-09-27 13:14
## Validation Template

## Root Cause

Loglevel was a utility provided inside the Rancher container which allowed users to change the log level of a running rancher installation. More information on it's usage can be found in [this KB article](https://www.suse.com/support/kb/doc/?id=000020239) (basically, exec into the container and run `loglevel --set level`).

Previously, this utility was a golang binary that simply curled a unix socket to change the log level. To reduce overhead/maintenance, it has been moved to a shell script. This shell script should have mostly the same behavior (it should be able to set the loglevel, display a help menu, and display a version).

## What was fixed, or what change have occurred

Loglevel has now been made into a shell script.

## Areas or cases that should be tested

1. Set the loglevel using `loglevel --set $LEVEL`. Confirm that the log level of the running Rancher installation has changed accordingly. At least trace, debug, info, and error levels should be tested.
  - Note: For a HA installation, this must be set in each Rancher replica to take universal effect. If this is only done inside one replica, only that replica will have the log level changed.
2. View the help menu using `loglevel --help`, `loglevel -h`, `loglevel h`, and `loglevel help`.
3. View the version using `loglevel --version`.

## What areas could experience regressions

The ability to set the loglevel of a running rancher installation (or to view the help menu/version of the loglevel utility).

## Are the repro steps accurate/minimal?

N/A - change was on the backend, no issue to reproduce.

**Comment by joesims22** [comment] 2024-10-09 21:36
Validated on v2.10-head id `fe30db7`

All test cases were completed successfully. 

| \#  | Priority | Description & Link                                        | PASS/FAIL |
| --- | -------- | --------------------------------------------------------- | --------- |
| 1   | P0       | Verify ability to set log level verbosity to debug via loglevel script(Docker)                        | ✅ PASS    |
| 2   | P0       |  Verify ability to set log level verbosity to error via loglevel script(Docker)                       | ✅ PASS    |
| 3   | P1      | Verify ability to set log level verbosity to warn/panic/fatal via loglevel script(Docker)                                 | ✅ PASS    |
| 4   | P0       | Verify ability to set log level verbosity to debug via loglevel script(HA)                        | ✅ PASS    |
| 5   | P0       |  Verify ability to set log level verbosity to error via loglevel script(HA)                                 | ✅ PASS    |
| 6   | P1       | Verify ability to set log level verbosity to warn/panic/fatal via loglevel script(HA) | ✅ PASS    |
| 7   | P0       | Verify ability to view log level version                                      | ✅ PASS    |
| 8   | P0       | Verify ability to view loglevel script help menu                                    | ✅ PASS    |
| 9   | P0       | Verify loglevel script rejects request to set log level to nonexistent verbosity                                      | ✅ PASS    |
| 10   | P0       | Upgrade: Verify ability to set log level verbosity to debug via loglevel script(Docker)                                  | ✅ PASS    |
| 11   | P0       |Upgrade: Verify ability to set log level verbosity to debug via loglevel script(HA)                                    | ✅ PASS    |

**Closed by joesims22** 2024-10-09 21:36 UTC
Labels: kind/tech-debt
