### ISSUE TITLE
Rancher 2 server fails with Loop java.lang.NullPointerException: null

### ISSUE THREAD

**Issue by tnmnt114** [rancher/rancher#10049] opened 2017-10-08 07:26 UTC
It fails on the first run on that machine, and on 3 other machines with the same docker and os version.

**Rancher versions:**
rancher/server:preview

**Docker version**: `Client:
 Version:      17.09.0-ce
 API version:  1.32
 Go version:   go1.8.3
 Git commit:   afdb6d4
 Built:        Tue Sep 26 22:41:23 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.09.0-ce
 API version:  1.32 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   afdb6d4
 Built:        Tue Sep 26 22:42:49 2017
 OS/Arch:      linux/amd64
 Experimental: false`**

**Operating system and kernel: CentOS 7.4, `3.10.0-693.2.2.el7.x86_64`**

**Type/provider of hosts: VMWare**

**Setup details: single node rancher **

**Steps to Reproduce: run `docker run -d --restart=unless-stopped -p 8080:8080 rancher/server:preview`**

**Results:**
docker logs:
`Uptime: 1  Threads: 1  Questions: 3  Slow queries: 0  Opens: 105  Flush tables: 1  Open tables: 98  Queries per second avg: 3.000
Setting up database
Importing schema
CATTLE_API_UI_URL=//releases.rancher.com/api-ui/1.0.8
CATTLE_CATTLE_VERSION=v0.184.10
CATTLE_DB_CATTLE_DATABASE=mysql
CATTLE_DB_CATTLE_MYSQL_HOST=localhost
CATTLE_DB_CATTLE_MYSQL_NAME=cattle
CATTLE_DB_CATTLE_MYSQL_PORT=3306
CATTLE_DB_CATTLE_USERNAME=cattle
CATTLE_GRAPHITE_HOST=
CATTLE_GRAPHITE_PORT=
CATTLE_HOME=/var/lib/cattle
CATTLE_HOST_API_PROXY_MODE=embedded
CATTLE_LOGBACK_OUTPUT_GELF_HOST=
CATTLE_LOGBACK_OUTPUT_GELF_PORT=
CATTLE_RANCHER_CLI_VERSION=v1.0.0-alpha4
CATTLE_RANCHER_SERVER_IMAGE=rancher/server
CATTLE_RANCHER_SERVER_VERSION=v2.0.0-alpha9
CATTLE_USE_LOCAL_ARTIFACTS=true
DEFAULT_CATTLE_API_UI_CSS_URL=/api-ui/ui.min.css
DEFAULT_CATTLE_API_UI_INDEX=//releases.rancher.com/ui/2.0.11
DEFAULT_CATTLE_API_UI_JS_URL=/api-ui/ui.min.js
DEFAULT_CATTLE_AUTH_SERVICE_EXECUTE=true
DEFAULT_CATTLE_CATALOG_EXECUTE=true
DEFAULT_CATTLE_CATALOG_URL={"catalogs":{"community":{"url":"https://git.rancher.io/community-catalog.git","branch":"${RELEASE}"},"library":{"url":"https://git.rancher.io/rancher-catalog.git","branch":"${RELEASE}"}}}
DEFAULT_CATTLE_COMPOSE_EXECUTOR_EXECUTE=true
DEFAULT_CATTLE_MACHINE_EXECUTE=true
DEFAULT_CATTLE_NETES_AGENT_EXECUTE=true
DEFAULT_CATTLE_NETES_EXECUTE=true
DEFAULT_CATTLE_RANCHER_CLI_DARWIN_URL=https://releases.rancher.com/cli/v1.0.0-alpha4/rancher-darwin-amd64-v1.0.0-alpha4.tar.gz
DEFAULT_CATTLE_RANCHER_CLI_LINUX_URL=https://releases.rancher.com/cli/v1.0.0-alpha4/rancher-linux-amd64-v1.0.0-alpha4.tar.gz
DEFAULT_CATTLE_RANCHER_CLI_WINDOWS_URL=https://releases.rancher.com/cli/v1.0.0-alpha4/rancher-windows-386-v1.0.0-alpha4.zip
DEFAULT_CATTLE_SECRETS_API_EXECUTE=true
DEFAULT_CATTLE_WEBHOOK_SERVICE_EXECUTE=true
07:22:36.277 [main] INFO  org.eclipse.jetty.util.log - Logging initialized @521ms
07:22:36.547 [main] INFO  org.eclipse.jetty.server.Server - jetty-9.2.11.v20150529
07:22:36.747 [main] INFO  c.n.c.sources.URLConfigurationSource - URLs to be used as dynamic configuration source: [jar:file:/usr/share/cattle/lib/cattle-resources-v0.184.10.jar!/config.properties]
07:22:36.768 [main] INFO  c.n.config.DynamicPropertyFactory - DynamicPropertyFactory is initialized with configuration sources: com.netflix.config.ConcurrentCompositeConfiguration@d4342c2
07:22:36.876 [main] INFO  ConsoleStatus - [BOOTSTRAP] CATTLE_HOME=/var/lib/cattle
07:22:37.051 [main] INFO  io.cattle.platform.pool.PoolConfig - Setting Pool [config] property [validationQuery=SELECT 1]
07:22:37.057 [main] INFO  io.cattle.platform.pool.PoolConfig - Setting Pool [config] property [password=****]
07:22:37.058 [main] INFO  io.cattle.platform.pool.PoolConfig - Setting Pool [config] property [maxIdle=1]
07:22:37.059 [main] INFO  io.cattle.platform.pool.PoolConfig - Setting Pool [config] property [testWhileIdle=true]
07:22:37.061 [main] INFO  io.cattle.platform.pool.PoolConfig - Setting Pool [config] property [maxWait=1000]
07:22:37.063 [main] INFO  io.cattle.platform.pool.PoolConfig - Setting Pool [config] property [url=jdbc:mysql://localhost:3306/cattle?useUnicode=true&characterEncoding=UTF-8&characterSetResults=UTF-8&prepStmtCacheSize=50&cachePrepStmts=true&prepStmtCacheSqlLimit=4096&socketTimeout=60000&connectTimeout=60000]
07:22:37.063 [main] INFO  io.cattle.platform.pool.PoolConfig - Setting Pool [config] property [testOnBorrow=false]
07:22:37.064 [main] INFO  io.cattle.platform.pool.PoolConfig - Setting Pool [config] property [minEvictableIdleTimeMillis=300000]
07:22:37.064 [main] INFO  io.cattle.platform.pool.PoolConfig - Setting Pool [config] property [timeBetweenEvictionRunsMillis=60000]
07:22:37.065 [main] INFO  io.cattle.platform.pool.PoolConfig - Setting Pool [config] property [maxActive=1]
07:22:37.065 [main] INFO  io.cattle.platform.pool.PoolConfig - Setting Pool [config] property [username=cattle]
2017-10-08 07:22:38,031 INFO    [main] [ConsoleStatus] Starting DB migration
2017-10-08 07:22:40,943 INFO    [main] [ConsoleStatus] Finished DB migration
2017-10-08 07:22:41,811 INFO    [main] [ConsoleStatus] Cluster membership changed [127.0.0.1:9345]
2017-10-08 07:22:41,813 INFO    [main] [ConsoleStatus] Checking cluster state on start-up
2017-10-08 07:22:41,813 INFO    [main] [ConsoleStatus] [BOOTSTRAP ] [4949ms] initialization succeeded
2017-10-08 07:22:42,003 INFO    [main] [ConsoleStatus] [FRAMEWORK ] [189ms] initialization succeeded
2017-10-08 07:22:43,016 INFO    [main] [ConsoleStatus] [MODEL     ] [1012ms] initialization succeeded
2017-10-08 07:22:43,067 INFO    [main] [ConsoleStatus] [DATAACCESS] [50ms] initialization succeeded
2017-10-08 07:22:43,104 INFO    [main] [ConsoleStatus] [COMMON    ] [36ms] initialization succeeded
2017-10-08 07:22:44,315 INFO    [main] [ConsoleStatus] [API       ] [1210ms] initialization succeeded
2017-10-08 07:22:44,724 INFO    [main] [ConsoleStatus] Data migration [Accounts] 226ms done
2017-10-08 07:22:44,763 INFO    [main] [ConsoleStatus] Data migration [Machine Drivers] 28ms done
2017-10-08 07:22:44,816 INFO    [main] [ConsoleStatus] Started io.cattle.platform.eventing.annotation.AnnotatedListenerRegistration 45ms
2017-10-08 07:22:44,817 INFO    [main] [ConsoleStatus] Started io.cattle.platform.lock.impl.LockDelegatorImpl 1ms
2017-10-08 07:22:44,820 INFO    [main] [ConsoleStatus] Started io.cattle.platform.launcher.MachineDriverLoader 2ms
2017-10-08 07:22:44,834 INFO    [main] [ConsoleStatus] Started io.cattle.platform.task.impl.TaskManagerImpl 14ms
2017-10-08 07:22:46,842 INFO    [main] [ConsoleStatus] Started io.cattle.platform.service.launcher.ServiceAccountCreateStartup 2008ms
2017-10-08 07:22:46,842 INFO    [main] [ConsoleStatus] [BACKEND   ] [2526ms] initialization succeeded
2017-10-08 07:22:46,842 INFO    [main] [ConsoleStatus] [DONE ] [10070ms] App initialization succeeded
2017-10-08 07:22:47,103 ERROR [:] [] [] [] [core-5         ] [i.c.p.e.manager.impl.LoopWrapper    ] Loop [conditions-loop] [null] 2/2/0 34ms java.lang.NullPointerException: null
	at io.cattle.platform.loop.ConditionsLoop.checkHealthyHosts(ConditionsLoop.java:76)
	at io.cattle.platform.loop.ConditionsLoop.run(ConditionsLoop.java:31)
	at io.cattle.platform.engine.manager.impl.LoopWrapper.lambda$executeLoop$1(LoopWrapper.java:112)
	at io.cattle.platform.deferred.util.DeferredUtils.nest(DeferredUtils.java:53)
	at io.cattle.platform.engine.manager.impl.LoopWrapper.executeLoop(LoopWrapper.java:112)
	at org.apache.cloudstack.managed.context.NoException$1.doRun(NoException.java:10)
	at org.apache.cloudstack.managed.context.NoExceptionRunnable.runInContext(NoExceptionRunnable.java:15)
	at org.apache.cloudstack.managed.context.ManagedContextRunnable$1.run(ManagedContextRunnable.java:36)
	at org.apache.cloudstack.managed.context.impl.DefaultManagedContext$1.call(DefaultManagedContext.java:57)
	at org.apache.cloudstack.managed.context.impl.DefaultManagedContext.callWithContext(DefaultManagedContext.java:110)
	at org.apache.cloudstack.managed.context.impl.DefaultManagedContext.runWithContext(DefaultManagedContext.java:54)
	at org.apache.cloudstack.managed.context.ManagedContextRunnable.run(ManagedContextRunnable.java:33)
	at org.apache.cloudstack.managed.context.NoException.run(NoException.java:12)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

2017-10-08 07:22:49,121 ERROR [:] [] [] [] [core-6         ] [i.c.p.e.manager.impl.LoopWrapper    ] Loop [conditions-loop] [null] 3/3/0 2ms java.lang.NullPointerException: null
	at io.cattle.platform.loop.ConditionsLoop.checkHealthyHosts(ConditionsLoop.java:76)
	at io.cattle.platform.loop.ConditionsLoop.run(ConditionsLoop.java:31)
	at io.cattle.platform.engine.manager.impl.LoopWrapper.lambda$executeLoop$1(LoopWrapper.java:112)
	at io.cattle.platform.deferred.util.DeferredUtils.nest(DeferredUtils.java:53)
	at io.cattle.platform.engine.manager.impl.LoopWrapper.executeLoop(LoopWrapper.java:112)
	at org.apache.cloudstack.managed.context.NoException$1.doRun(NoException.java:10)
	at org.apache.cloudstack.managed.context.NoExceptionRunnable.runInContext(NoExceptionRunnable.java:15)
	at org.apache.cloudstack.managed.context.ManagedContextRunnable$1.run(ManagedContextRunnable.java:36)
	at org.apache.cloudstack.managed.context.impl.DefaultManagedContext$1.call(DefaultManagedContext.java:57)
	at org.apache.cloudstack.managed.context.impl.DefaultManagedContext.callWithContext(DefaultManagedContext.java:110)
	at org.apache.cloudstack.managed.context.impl.DefaultManagedContext.runWithContext(DefaultManagedContext.java:54)
	at org.apache.cloudstack.managed.context.ManagedContextRunnable.run(ManagedContextRunnable.java:33)
	at org.apache.cloudstack.managed.context.NoException.run(NoException.java:12)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

2017-10-08 07:22:51,125 ERROR [:] [] [] [] [core-22        ] [i.c.p.e.manager.impl.LoopWrapper    ] Loop [conditions-loop] [null] 3/3/0 3ms java.lang.NullPointerException: null
	at io.cattle.platform.loop.ConditionsLoop.checkHealthyHosts(ConditionsLoop.java:76)
	at io.cattle.platform.loop.ConditionsLoop.run(ConditionsLoop.java:31)
	at io.cattle.platform.engine.manager.impl.LoopWrapper.lambda$executeLoop$1(LoopWrapper.java:112)
	at io.cattle.platform.deferred.util.DeferredUtils.nest(DeferredUtils.java:53)
	at io.cattle.platform.engine.manager.impl.LoopWrapper.executeLoop(LoopWrapper.java:112)
	at org.apache.cloudstack.managed.context.NoException$1.doRun(NoException.java:10)
	at org.apache.cloudstack.managed.context.NoExceptionRunnable.runInContext(NoExceptionRunnable.java:15)
	at org.apache.cloudstack.managed.context.ManagedContextRunnable$1.run(ManagedContextRunnable.java:36)
	at org.apache.cloudstack.managed.context.impl.DefaultManagedContext$1.call(DefaultManagedContext.java:57)
	at org.apache.cloudstack.managed.context.impl.DefaultManagedContext.callWithContext(DefaultManagedContext.java:110)
	at org.apache.cloudstack.managed.context.impl.DefaultManagedContext.runWithContext(DefaultManagedContext.java:54)
	at org.apache.cloudstack.managed.context.ManagedContextRunnable.run(ManagedContextRunnable.java:33)
	at org.apache.cloudstack.managed.context.NoException.run(NoException.java:12)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

2017-10-08 07:22:53,128 ERROR [:] [] [] [] [core-4         ] [i.c.p.e.manager.impl.LoopWrapper    ] Loop [conditions-loop] [null] 3/3/0 2ms java.lang.NullPointerException: null
	at io.cattle.platform.loop.ConditionsLoop.checkHealthyHosts(ConditionsLoop.java:76)
	at io.cattle.platform.loop.ConditionsLoop.run(ConditionsLoop.java:31)
	at io.cattle.platform.engine.manager.impl.LoopWrapper.lambda$executeLoop$1(LoopWrapper.java:112)
	at io.cattle.platform.deferred.util.DeferredUtils.nest(DeferredUtils.java:53)
	at io.cattle.platform.engine.manager.impl.LoopWrapper.executeLoop(LoopWrapper.java:112)
	at org.apache.cloudstack.managed.context.NoException$1.doRun(NoException.java:10)
	at org.apache.cloudstack.managed.context.NoExceptionRunnable.runInContext(NoExceptionRunnable.java:15)
	at org.apache.cloudstack.managed.context.ManagedContextRunnable$1.run(ManagedContextRunnable.java:36)
	at org.apache.cloudstack.managed.context.impl.DefaultManagedContext$1.call(DefaultManagedContext.java:57)
	at org.apache.cloudstack.managed.context.impl.DefaultManagedContext.callWithContext(DefaultManagedContext.java:110)
	at org.apache.cloudstack.managed.context.impl.DefaultManagedContext.runWithContext(DefaultManagedContext.java:54)
	at org.apache.cloudstack.managed.context.ManagedContextRunnable.run(ManagedContextRunnable.java:33)
	at org.apache.cloudstack.managed.context.NoException.run(NoException.java:12)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

2017-10-08 07:22:55,131 ERROR [:] [] [] [] [core-21        ] [i.c.p.e.manager.impl.LoopWrapper    ] Loop [conditions-loop] [null] 3/3/0 2ms java.lang.NullPointerException: null
	at io.cattle.platform.loop.ConditionsLoop.checkHealthyHosts(ConditionsLoop.java:76)
	at io.cattle.platform.loop.ConditionsLoop.run(ConditionsLoop.java:31)
	at io.cattle.platform.engine.manager.impl.LoopWrapper.lambda$executeLoop$1(LoopWrapper.java:112)
	at io.cattle.platform.deferred.util.DeferredUtils.nest(DeferredUtils.java:53)
	at io.cattle.platform.engine.manager.impl.LoopWrapper.executeLoop(LoopWrapper.java:112)
	at org.apache.cloudstack.managed.context.NoException$1.doRun(NoException.java:10)
	at org.apache.cloudstack.managed.context.NoExceptionRunnable.runInContext(NoExceptionRunnable.java:15)
	at org.apache.cloudstack.managed.context.ManagedContextRunnable$1.run(ManagedContextRunnable.java:36)
	at org.apache.cloudstack.managed.context.impl.DefaultManagedContext$1.call(DefaultManagedContext.java:57)
	at org.apache.cloudstack.managed.context.impl.DefaultManagedContext.callWithContext(DefaultManagedContext.java:110)
	at org.apache.cloudstack.managed.context.impl.DefaultManagedContext.runWithContext(DefaultManagedContext.java:54)
	at org.apache.cloudstack.managed.context.ManagedContextRunnable.run(ManagedContextRunnable.java:33)
	at org.apache.cloudstack.managed.context.NoException.run(NoException.java:12)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

2017-10-08 07:22:57,133 ERROR [:] [] [] [] [core-8         ] [i.c.p.e.manager.impl.LoopWrapper    ] Loop [conditions-loop] [null] 3/3/0 2ms java.lang.NullPointerException: null
	at io.cattle.platform.loop.ConditionsLoop.checkHealthyHosts(ConditionsLoop.java:76)
	at io.cattle.platform.loop.ConditionsLoop.run(ConditionsLoop.java:31)
	at io.cattle.platform.engine.manager.impl.LoopWrapper.lambda$executeLoop$1(LoopWrapper.java:112)
	at io.cattle.platform.deferred.util.DeferredUtils.nest(DeferredUtils.java:53)
	at io.cattle.platform.engine.manager.impl.LoopWrapper.executeLoop(LoopWrapper.java:112)
	at org.apache.cloudstack.managed.context.NoException$1.doRun(NoException.java:10)
	at org.apache.cloudstack.managed.context.NoExceptionRunnable.runInContext(NoExceptionRunnable.java:15)
	at org.apache.cloudstack.managed.context.ManagedContextRunnable$1.run(ManagedContextRunnable.java:36)
	at org.apache.cloudstack.managed.context.impl.DefaultManagedContext$1.call(DefaultManagedContext.java:57)
	at org.apache.cloudstack.managed.context.impl.DefaultManagedContext.callWithContext(DefaultManagedContext.java:110)
	at org.apache.cloudstack.managed.context.impl.DefaultManagedContext.runWithContext(DefaultManagedContext.java:54)
	at org.apache.cloudstack.managed.context.ManagedContextRunnable.run(ManagedContextRunnable.java:33)
	at org.apache.cloudstack.managed.context.NoException.run(NoException.java:12)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

2017-10-08 07:22:59,136 ERROR [:] [] [] [] [core-10        ] [i.c.p.e.manager.impl.LoopWrapper    ] Loop [conditions-loop] [null] 3/3/0 2ms java.lang.NullPointerException: null
	at io.cattle.platform.loop.ConditionsLoop.checkHealthyHosts(ConditionsLoop.java:76)
	at io.cattle.platform.loop.ConditionsLoop.run(ConditionsLoop.java:31)
	at io.cattle.platform.engine.manager.impl.LoopWrapper.lambda$executeLoop$1(LoopWrapper.java:112)
	at io.cattle.platform.deferred.util.DeferredUtils.nest(DeferredUtils.java:53)
	at io.cattle.platform.engine.manager.impl.LoopWrapper.executeLoop(LoopWrapper.java:112)
	at org.apache.cloudstack.managed.context.NoException$1.doRun(NoException.java:10)
	at org.apache.cloudstack.managed.context.NoExceptionRunnable.runInContext(NoExceptionRunnable.java:15)
	at org.apache.cloudstack.managed.context.ManagedContextRunnable$1.run(ManagedContextRunnable.java:36)
	at org.apache.cloudstack.managed.context.impl.DefaultManagedContext$1.call(DefaultManagedContext.java:57)
	at org.apache.cloudstack.managed.context.impl.DefaultManagedContext.callWithContext(DefaultManagedContext.java:110)
	at org.apache.cloudstack.managed.context.impl.DefaultManagedContext.runWithContext(DefaultManagedContext.java:54)
	at org.apache.cloudstack.managed.context.ManagedContextRunnable.run(ManagedContextRunnable.java:33)
	at org.apache.cloudstack.managed.context.NoException.run(NoException.java:12)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)`

**Comment by superseb** [comment] 2017-10-08 17:37
Duplicate of https://github.com/rancher/rancher/issues/10031

It should work though, is it not for you?

**Comment by mikygit** [comment] 2017-11-21 14:45
Same here

**Comment by superseb** [comment] 2018-01-30 10:49
With the release of [Tech Preview 2](https://forums.rancher.com/t/rancher-release-v2-0-0-tech-preview-2/8282/3), the architecture behind 2.0 has significantly changed. Any issues with any release prior to v2.0.0-alpha12 is most likely invalid. 

Please watch our [Tech Preview 2 meetup](https://www.youtube.com/watch?v=ld7ctOg3waM) to learn more about the changes in 2.0 in Tech Preview 2. 

Please file new issues after using Tech Preview 2 (any release v2.0.0-alpha12+). As always, thanks for using Rancher!

**Closed by superseb** 2018-01-30 10:49 UTC
Labels: status/more-info, version/2.0
