### ISSUE TITLE
Resources left after creating and deleting a downstream cluster on Azure

### ISSUE THREAD

**Issue by gusraggio** [rancher/rancher#35055] opened 2021-10-06 10:19 UTC
**Rancher Server Setup**
- Rancher version: 2.6.0
- Installation option (Docker install/Helm Chart): Helm
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): AKS
- Proxy/Cert Details:

**Information about the Cluster**
- Kubernetes version:
- Cluster Type (Local/Downstream):
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider):

**Describe the bug**

When deleting a rke2 cluster it leaves artifacts in Azure.
**To Reproduce**
 
After creating the first rke2 cluster, we delete it. It deletes everything related to the cluster but leaves the "Availability Set". We have set an "Availability Set" name to identify it.
**Result**

**Expected Result**

Everything should be as it was initially, with no "garbage"
**Screenshots**

**Additional context**
<!--Add any other context about the problem here.—>

**Comment by fjramons** [comment] 2021-12-05 15:05
Any update about this bug?

**Comment by fjramons** [comment] 2022-02-03 19:36
The bug remains (and is relevant cost-wise). Any plans to fix it?

**Comment by fjramons** [comment] 2022-04-06 19:29
Any news?

**Comment by fjramons** [comment] 2022-06-06 08:49
Is there anything planned to address this bug?

**Comment by fjramons** [comment] 2022-08-06 10:01
What is the status of this bug?

**Comment by fjramons** [comment] 2022-08-23 19:12
Yes, it's the only object that I have found in my tests.

**Comment by jameson-mcghee** [comment] 2022-08-23 19:20
**Intended Test Setup**
-	Rancher version(s): v2.6-head
-	Browser type & version: Brave & Most Current
-	Rancher Host: EC2 (Jenkins Job)
-	Rancher Setup:
o	RANCHER_HA_CERT_OPTION: byo-valid
o	RKE_VERSION: 1.3.13-rc4
o	AWS_VOLUME_SIZE: 20
o	AWS_AMI: ami-066f14e43aebc7472
o	AWS_SECURITY_GROUPS: sg-0e753fd5550206e55 (open-all)
o	AWS_INSTANCE_TYPE: t3a.xlarge
o	AWS_VPC: vpc-bfccf4d7
o	AWS_SUBNET: subnet-ee8cac86
o	AWS_REGION: us-east-2
-	Deployment Type: Helm
-	User Permission: Standard User

**Test Approach**
-	Verify that when I create and then delete a downstream AKS cluster, that the “Availability Set” information for that cluster is deleted in Azure
-	Verify that, when the downstream AKS cluster is deleted in Rancher, that the cluster is also deleted in Azure
-	Verify that, when the downstream AKS cluster is deleted in Rancher, that its cluster resource group is also deleted in Azure
-	Verify that, when the downstream AKS cluster is deleted in Rancher, that artifacts that are not used for the cluster’s creation are not affected, such as:
o	Keypairs
o	Unused VMs
o	etc

**Comment by jameson-mcghee** [comment] 2022-09-07 21:49
@HarrisonWAffel, I have been able to verify that this is resolved on v2.6-head and I was anticipating to be able to reproduce on v2.6.7, however, the issue appears to be resolved on there too. Any recommendations on how to reproduce this issue for validation purposes?

**Comment by HarrisonWAffel** [comment] 2022-09-08 21:23
@jameson-mcghee I don't have any additional tips on how to get this to reproduce on v2.6.7, although I was able to do so when testing this initially. Feel free to sync up with me to do another round of testing on a call, although it sounds like the issue has been resolved and clearly was reproducible in earlier versions as evident by the comments above

**Comment by HarrisonWAffel** [comment] 2022-09-12 21:01
N.B: The PR associated with this issue was merged before branching was done for the 2.7.0 release

**Comment by jameson-mcghee** [comment] 2022-09-13 22:57
I tested this ticket on v2.6.7 and was in fact able to reproduce the issue (see screenshots). However, when testing on v2.6-head (Commit ID: a3b5237), I did not see this issue reproduce. Therefore I am closing this ticket.
cc @HarrisonWAffel @sowmyav27 

Repro Steps:
1. Provision a downstream Azure Node Driver cluster with an Availability Set that does not already exist in the list of Availability Sets in Azure
2. Verify that the Availability Set is added to the list in Azure
3. Delete the cluster
4. Verify that the Availability Set and all other assets specific to that cluster (e.g. VMs, Public IP Addresses, Network Interfaces, etc.) are successfully deleted from Azure as well.

v2.6.7:
![image.png](https://zube.io/files/rancher/b7ff7b94b7ddacc232a1247c6625eecd-image.png)
![image.png](https://zube.io/files/rancher/48e2bec4cff8190c4d763ecdc4e26396-image.png)
![image.png](https://zube.io/files/rancher/b05ad00f132b0144c41bb8f9540018a0-image.png)

v2.6-head:
![image.png](https://zube.io/files/rancher/93d1e7bdf8a927497d858ec9d21b08d1-image.png)
![image.png](https://zube.io/files/rancher/c5e585117819d303499f0c55e6ad750a-image.png)
![image.png](https://zube.io/files/rancher/f691792edb9127b75162e7757dd4ce7a-image.png)

**Closed** 2022-09-13 22:58 UTC
Labels: area/machine, area/azure, [zube]: QA Working, QA/S, feature/rancher-machine, team/area2
