### ISSUE TITLE
Rancher UI unresponsive when API endpoint node goes down

### ISSUE THREAD

**Issue by KellyGriffin** [rancher/rancher#20350] opened 2019-05-21 07:21 UTC
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
Login to UI
Access Cluster and open API information via UI
Find node that is reported as endpoint API
SSH onto node and shutdown or shutdown docker (either way results in the same)

**Result:**
UI is unresponsive with error message stating API server unavailable

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI):
Cluster settings:
3 nodes, all run etcd, control plane and worker:
Rancher v2.2.2
K8s v1.13.5
Canal network, isolation disabled
Cloud provider: none

- Installation option (single install/HA):
HA

Details about Cluster are above and within the Ticket logged by Customer #4298

**Comment by alena1108** [comment] 2019-05-29 02:42
A duplicate of https://github.com/rancher/rancher/issues/20311; closing as 20311 has more data

**Closed by alena1108** 2019-05-29 02:42 UTC
