### ISSUE TITLE
Rancher 2.0 Webhook

### ISSUE THREAD

**Issue by yl-yue** [rancher/rancher#15197] opened 2018-08-23 06:42 UTC
**Rancher versions:**
rancher/server or rancher/rancher: v2.0.5

**issue:**
Can Rancher2.0 use Webhook to notify the server for an upgrade deployment?
As simple as 1.6.

**Comment by superseb** [comment] 2018-08-23 07:58
Duplicate of https://github.com/rancher/rancher/issues/13991

**Closed by superseb** 2018-08-23 07:58 UTC
