### ISSUE TITLE
The number of etcd snapshots saved in GCS exceeds the retention of backup_config

### ISSUE THREAD

**Issue by xibuka** [rancher/rancher#30565] opened 2020-12-21 02:27 UTC
**What kind of request is this (question/bug/enhancement/feature request):**
bug

**Steps to reproduce (least amount of steps as possible):**
1. deploy a 1 node k8s cluster via Rancher UI 
2. edit the cluster and `edit as YAML`, config the backup_config of etcd to use google cloud storage as following.
```
    etcd:
      backup_config:
        enabled: true
        interval_hours: 1
        retention: 2
        s3_backup_config:
          access_key: XXXXXXXXXXXXXXXX
          bucket_name: etcd-snapshot-test
          endpoint: storage.googleapis.com
          folder: backups
          region: asia-northeast1
        safe_timestamp: false
```
3. wait and see the snapshots are saved in GCS.
4. delete the snapshot in Rancher UI, and check the file in GCS

**Result:**
the number of snapshots in Rancher is 2, which is not over the retention in the setting.
![image](https://user-images.githubusercontent.com/21263862/102732626-90d8ce00-437e-11eb-8967-ef00058a6f47.png)

However the number of snapshots in GCS is not been limited to 2, the old snapshot is never get removed.
![image](https://user-images.githubusercontent.com/21263862/102732704-c4b3f380-437e-11eb-85b2-b574bea88e22.png)

And even we delete the snapshot in Rancher UI, but it doesn't get removed in GCS.

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI):
- v2.4.11

- Installation option (single install/HA):
single install on docker

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported):
Digital Ocean
- Machine type (cloud/VM/metal) and specifications (CPU/memory):
cloud, 2core CPU and 4GB memory
- Kubernetes version (use `kubectl version`):

```
> kubectl version
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.0", GitCommit:"af46c47ce925f4c4ad5cc8d1fca46c7b77d13b38", GitTreeState:"clean", BuildDate:"2020-12-09T16:50:17Z", GoVersion:"go1.15.6", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.12", GitCommit:"7cd5e9086de8ae25d6a1514d0c87bac67ca4a481", GitTreeState:"clean", BuildDate:"2020-11-12T09:11:15Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
```

- Docker version (use `docker version`):

```
> docker version
Client:
 Version:           19.03.8
 API version:       1.40
 Go version:        go1.13.8
 Git commit:        afacb8b7f0
 Built:             Wed Oct 14 19:43:43 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          19.03.8
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.13.8
  Git commit:       afacb8b7f0
  Built:            Wed Oct 14 16:41:21 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.3.3-0ubuntu2.1
  GitCommit:
 runc:
  Version:          spec: 1.0.1-dev
  GitCommit:
 docker-init:
  Version:          0.18.0
  GitCommit:
```

gz#13882

**Comment by xibuka** [comment] 2020-12-21 02:29
gz#13882

**Comment by kravciak** [comment] 2021-03-18 12:23
I was able to reproduce this on v2.4.11.
I noticed missing `secret_key` parameter in reproducer, without it you can't apply cluster changes (error 404)
For access to s3 I used google IAM service account with Storage Admin role.

```
# https://rancher.com/docs/rke/latest/en/etcd-snapshots/recurring-snapshots/#configuring-the-snapshot-service-in-yaml

s3_backup_config:
  access_key: XXXXXXXXXXXXXXXX
  secret_key: XXXXXXXXXXXXXXXX
  ...
```

Used components:
```
Rancher v2.4.11 (docker single node)
Infrastructure provider cluster (DigitalOcean v1.18.16)
1 node cluster s-4vcpu-8gb

# Snapshots visible from rancher
# c-dcq9h-rs-mb6mx snapshot deleted manually
S3 | c-dcq9h-rs-fzg96 | 44 minutes ago -- | -- | --

# Snapshots visible from cloud storage google dashboard
c-dcq9h-rs-8m5sf_2021-03-18T09:26:32Z.zip Mar 18, 2021, 10:26:47 AM	Standard	
c-dcq9h-rs-fzg96_2021-03-18T11:36:32Z.zip Mar 18, 2021, 12:36:46 PM	Standard	
c-dcq9h-rs-mb6mx_2021-03-18T10:31:32Z.zip Mar 18, 2021, 11:31:46 AM	Standard	

```

**Comment by ryansann** [comment] 2021-03-30 21:10
This issue is testable in `rke-tools:v0.1.74`, which should be added to k8s versions:
```
v1.18.17-rancher1-2
v1.19.9-rancher1-2
v1.20.5-rancher1-2
```

Testing should validate that:
1. we automatically delete backups past retention
2. manual backup deletion works correctly

**Comment by sowmyav27** [comment] 2021-03-31 15:16
@ryansann I do not see these k8s versions in rancher yet.

**Comment by anupama2501** [comment] 2021-04-05 22:59
Able to reproduce this on 2.5.5

Create a cluster with 1 node all roles
From the edit as yaml option under the etcd backup configs:
        retention: 2
        s3_backup_config:
          access_key: xxxxx
          secret_key: xxxxx
          bucket_name: anupama-gcs
          endpoint: storage.googleapis.com
          folder: ""
          region:""

Created multiple snapshots from cluster --> tools --> snapshot now and all are saved in the google cloud storage bucket provided above.
Deleted two snapshots from the tools --> snapshots and are not deleted from the google cloud bucket

**Comment by anupama2501** [comment] 2021-04-06 21:44
@ryansann, on 2.5-head, the above mentioned KDM versions are not seen.  Following are the versions available. Can we have the rke-tools fix merged in KDM?

<img width="520" alt="Screen Shot 2021-04-06 at 2 42 45 PM" src="https://user-images.githubusercontent.com/38144301/113782071-75ec5880-96e6-11eb-97e0-b35f91364219.png">

Re-opening the issue

**Comment by ryansann** [comment] 2021-04-06 21:48
@anupama2501 I will investigate this, thanks for letting me know

**Comment by anupama2501** [comment] 2021-04-06 21:52
@ryansann I did a refresh in kubernetes metadata, now the new k8s are available in 2.5-head
Moving back to qa-working

**Comment by anupama2501** [comment] 2021-04-07 18:55
@ryansann  on v2.5-4115dee8d6239b74bfc5a2bd6e9dbcb79ca5aa35-head 
k8s: v1.20.5-rancher1-2
rke-tools: 0.1.74 & 0.1.72

I still see the issue.  On rancher , for recurring snapshots, following configuration was given:
<img width="400" alt="Screen Shot 2021-04-07 at 11 46 04 AM" src="https://user-images.githubusercontent.com/38144301/113918217-fff3fa00-9796-11eb-8902-83d130430b59.png">

Snapshots on GCS are not removed even after the retention count reached but they are removed from rancher UI. Below are the screenshots for rancher vs GCS:
<img width="400" alt="Screen Shot 2021-04-06 at 10 36 22 PM" src="https://user-images.githubusercontent.com/38144301/113918865-c8398200-9797-11eb-967f-45d589202bd6.png">
<img width="400" alt="Screen Shot 2021-04-06 at 10 34 47 PM" src="https://user-images.githubusercontent.com/38144301/113918877-ca9bdc00-9797-11eb-93a3-8a7b42574c5a.png">


For snapshots, I see the older image version of rke-tools is being used on the etcd. 
<img width="500" alt="Screen Shot 2021-04-07 at 11 45 12 AM" src="https://user-images.githubusercontent.com/38144301/113919069-046ce280-9798-11eb-8a83-b9d338382a51.png">

**Comment by ryansann** [comment] 2021-04-07 19:07
@anupama2501 this is certainly the reason as the fix is not in `rancher/rke-tools:v0.1.72` and only in `rancher/rke-tools:v0.1.74`. I will check this with k8s `v1.20.5-rancher1-2` and lyk how to proceed

**Comment by sowmyav27** [comment] 2021-04-08 04:39
@kravciak Please validate using 2.5.8-rc2

**Comment by ryansann** [comment] 2021-04-08 22:12
This is not ready to be validated. It required this PR: https://github.com/rancher/kontainer-driver-metadata/pull/526 which only just got merged

**Comment by thehejik** [comment] 2021-04-09 14:59
**Test report:**
* I was able reproduce the issue on rancher/rancher:v2.5.5 - the snapshots were not deleted according to set retention count on GPC - also on attempt to delete an etcd snapshot from Rancher UI the snapshot was still present in GCP S3 bucket (it behaved correctly on AWS)
* The issue is fixed in v2.5-head `v2.5-9b0058c0329f7de1527852e03c92a4a6b3ba4d10-head`
* Etcd snapshots are now automatically removed from GCP S3 bucket (tested also on AWS) according to set retention snapshots count
* Manually deleted snapshots from rancher UI are now getting deleted also from GCP S3 bucket (tested also on AWS)

**Comment by thehejik** [comment] 2021-04-12 10:55
@ryansann do we need this fix also in `master-head`?

**Comment by sowmyav27** [comment] 2021-04-12 18:16
Reopening for RKE fixes to be vendored into rancher master-head

**Comment by deniseschannon** [comment] 2021-04-12 23:03
No need to make a specific master-head issue for this change.

**Comment by sowmyav27** [comment] 2021-04-13 00:00
Closing based on https://github.com/rancher/rancher/issues/30565#issuecomment-818298748

**Closed by sowmyav27** 2021-04-13 00:00 UTC
Labels: QA/S, [zube]: QA Next up, area/etcd, internal, kind/bug

**Comment by xibuka** [comment] 2021-04-14 14:03
@deniseschannon Do you have a plan to backport this into v2.4.x?
