### ISSUE TITLE
EKS Regional availability for ap-south

### ISSUE THREAD

**Issue by mr-karan** [rancher/rancher#19813] opened 2019-04-25 04:40 UTC
**What kind of request is this (question/bug/enhancement/feature request):**
Feature Request

**Steps to reproduce (least amount of steps as possible):**
None

**Result:**
Add `ap-south-1` for provisioning an EKS cluster. This region was recently introduced by AWS in February 2019.

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): 2.2.2
- Installation option (single install/HA):
Single Install (not relevant)

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): Infra Provider
- Machine type (cloud/VM/metal) and specifications (CPU/memory): Cloud (NA)
- Kubernetes version (use `kubectl version`): NA

**Comment by superseb** [comment] 2019-04-25 07:34
Duplicate of https://github.com/rancher/rancher/issues/18114

**Closed by superseb** 2019-04-25 07:34 UTC
