### ISSUE TITLE
Rancher health check isn't working correctly for `net: host` services, making it appear as Degraded

### ISSUE THREAD

**Issue by cusspvz** [rancher/rancher#2432] opened 2015-10-24 23:03 UTC
Versions affected: `0.43.0-rc2` and `0.43.0-rc3`

<img width="626" alt="captura de ecra 2015-10-25 as 00 02 29" src="https://cloud.githubusercontent.com/assets/3604053/10713194/b91a65b4-7aab-11e5-9ba3-39913be64b58.png">

**Comment by deniseschannon** [comment] 2015-11-02 19:24
@cusspvz I was unable to reproduce. Granted all I tried was to start a service using `net:host` from the UI. It went into active state for both service and stack. 

How did you start your service? Can you provide the docker-compose.yml?

**Comment by cusspvz** [comment] 2015-11-03 11:39
Absolutely, this is also affecting `v0.43.1`:

`docker-compose.yml`
```yml
turnserver:
  restart: on-failure:10
  ports:
  - 3478:3478/tcp
  - 3478:3478/udp
  environment:
    USE_IPV4: 'true'
  labels:
    io.rancher.scheduler.global: 'true'
    io.rancher.scheduler.affinity:host_label: type=haendpoint
  tty: true
  image: bprodoehl/turnserver
  stdin_open: true
  net: host
```

`rancher-compose.yml`
```yaml
turnserver:
  health_check:
    port: 3478
    interval: 2000
    unhealthy_threshold: 3
    response_timeout: 2000
    healthy_threshold: 2
```

Checking port with `netcat` (also tried udp just to be sure it was up)
```bash
root@server-hostname:/# nc -v -t localhost 3478                                 
Connection to localhost 3478 port [tcp/*] succeeded!                            
^C                                                                              
root@server-hostname:/# nc -v -u localhost 3478                                 
Connection to localhost 3478 port [udp/*] succeeded!                            
^C                                                                              
root@server-hostname:/#   
```

**Comment by cjellick** [comment] 2015-11-03 16:37
@deniseschannon I have reproduced this. Have run into it a lot recently actually.

**Comment by cjellick** [comment] 2015-11-03 16:38
Possibly related but not exactly the same: #2516

**Comment by m4ce** [comment] 2015-11-23 16:45
Will this be fixed in 1.0? I see that https://github.com/rancher/rancher/issues/2578 states that health checks can only be used in managed network, which would represent quite a limitation for us.

Thanks!
Matteo

**Comment by alena1108** [comment] 2015-12-11 17:04
@sangeethah In order to use Rancher services - dns and healthcheck - service has to have a "io.rancher.container.dns" label set to true. When set to true, container gets a secondary nic on Rancher managed network on Rancher network container's vnet - that enables the container to be picked for a health check/dns discovery.

**Comment by sangeethah** [comment] 2015-12-12 23:16
Tested with server version - v0.50.0-rc2
Health check reports correct health state for container when "io.rancher.container.dns"  is set to true.

When unhealthy instances are detected and removed , the new instances that get started may not be able to start in hosts where they can come up successfully since allocators are not aware of the exposed ports for these instances . This issue is tracked in #3016

**Closed by sangeethah** 2015-12-12 23:16 UTC
Labels: area/service, kind/bug, status/to-test
