### ISSUE TITLE
[project-monitoring] Helm Chart crashs with disabled Grafana

### ISSUE THREAD

**Issue by eumel8** [rancher/rancher#41199] opened 2023-02-23 18:00 UTC
**Describe the bug**
The Project Monitoring Helm Chart has the option to [disable Grafana](https://github.com/rancher/prometheus-federator/blob/main/charts/rancher-project-monitoring/0.2.1/values.yaml#L657) installation. Helm crashs if this option is set (`enabled: false`).

**To Reproduce**
disable Grafana

**Result**
Helm Chart crashs

**Expected Result**
Grafana is disabled and will not installed in the target project.

**Additional context**
The root cause are unknown variable names in this [rbac file](https://github.com/rancher/prometheus-federator/blob/main/charts/rancher-project-monitoring/0.2.1/templates/dashboard-roles.yaml#L22-L23). The resourceNames are generated from [call-nested](https://github.com/rancher/prometheus-federator/blob/main/charts/rancher-project-monitoring/0.2.1/templates/_helpers.tpl#L13) which loops over all sub-charts, which is happily only [Grafana](https://github.com/rancher/prometheus-federator/blob/main/charts/rancher-project-monitoring/0.2.1/charts/grafana/templates/_helpers.tpl#L43). But we [disabled Grafana](https://github.com/rancher/prometheus-federator/blob/main/charts/rancher-project-monitoring/0.2.1/Chart.yaml#L12) and this variables and part of code are not available.

**Comment by AndrewHoffmanQA** [comment] 2023-06-22 14:39
**testing status** - passed. moving to closed

**testing information** - 
rancher image 2.6.13
prom fed chart version 0.3.1
monitoring- 100.2.0+up40.1.2
K8- v1.24.13

**testing activities**- 

- installed latest monitoring chart
- installed 0.3.1 prom federator chart. checked box to edit yaml
- updated yaml to disable grafana 
- confirmed successful installation, and that grafana is disabled in yaml (see screenshot)
- navigated to project monitoring and created a project monitor
- confirmed all grafana links within project monitoring display a 404 and no grafana charts are displayed (see screenshot)


**testing notes**:
grafana is still installed on the system in places because project monitoring utilizes it.

**screenshots**:
<img width="1728" alt="image" src="https://github.com/rancher/rancher/assets/89030218/39985e09-557a-42c4-908f-65962b4e16fe">

<img width="1727" alt="image" src="https://github.com/rancher/rancher/assets/89030218/6fc140a3-2ed9-4844-a14a-cff8bfcafee4">

**Closed by AndrewHoffmanQA** 2023-06-22 14:39 UTC
Labels: [zube]: To Test, team/area3
