### ISSUE TITLE
[BUG] rancher-agent keeps spawning until node is OOM

### ISSUE THREAD

**Issue by Daxorinator** [rancher/rancher#34839] opened 2021-09-21 11:41 UTC
**Rancher Server Setup**
- Rancher version: v2.5.9
- Installation option (Docker install/Helm Chart): Helm Chart
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): RKE1
- Proxy/Cert Details: N/A

**Information about the Cluster**
- Kubernetes version: v1.20.6
- Cluster Type: Custom

**Describe the bug**
After safely removing a node from an existing cluster I wiped the node and reinstalled it with Debian 11 and followed the standard procedure for installing docker, etc. and then executed the `docker run` command given by Rancher to add a new node to the cluster. The public and private IP addresses were manually configured, the hostname, public and private IPs are the same as they previously were before the node was removed from the cluster. Everything comes up successfully but every 30s-1m a new `rancher/rancher-agent:v2.5.9` container spawns, this continues until the OOM Killer starts killing containers to prevent the node from dying.

**To Reproduce**
- Remove a node from an existing cluster
- Wipe the node, reinstall OS, install docker, etc.
- Add node back to cluster using provided command from rancher UI with the same hostname, public and private IP as before it was removed from the cluster.
- Wait
- Check `docker ps` 

**Result**
Many rancher-agent instances appear in `docker ps` with random names.

**Expected Result**
There shouldn't be an excessive number of rancher agents.

**Screenshots**
https://i.forbid.fun/u/12.31.03-21.09.21.png
This screenshot shows a few rancher-agents, after some time this could increase to hundreds.

**Additional context**
Never experienced this before, I've wiped the node a few times and repeated to no effect, I've also tried removing it from the cluster and running the rancher node cleanup script from superseb, then adding it back, this also produced the same result. 

It seems that the "real" rancher-agent is actually crashing for some unknown reason, it's startup command is `run.sh -- share-roo…` and it seems to crash frequently with the following being shown in the `docker logs` for the container.
```
INFO: Arguments: -- share-root.sh docker run -d --privileged --restart=unless-stopped --net=host -v /etc/kubernetes:/etc/kubernetes -v /var/run:/var/run rancher/rancher-agent:v2.5.9 --server https://rancher.XXX.YYY --token REDACTED --ca-checksum 6e28fe6ccb58d9c4c2148eee478e7f24d1215e226184e14f4eca4ae7e4b6c7e2 --no-register --only-write-certs --node-name bravo
+ trap 'exit 0' SIGTERM
++ grep :devices: /proc/self/cgroup
++ head -n1
++ awk -F/ '{print $NF}'
++ sed -e 's/docker-\(.*\)\.scope/\1/'
+ ID=
+ bash -c 'docker run -d --privileged --restart=unless-stopped --net=host -v /etc/kubernetes:/etc/kubernetes -v /var/run:/var/run  rancher/rancher-agent:v2.5.9 --server https://rancher.XXX.YYY --token bhtkcc7dwk4vwfbmd7rn9hkjspxk5l2qmc4cb52qmbpmgj5pnw86c4 --ca-checksum 6e28fe6ccb58d9c4c2148eee478e7f24d1215e226184e14f4eca4ae7e4b6c7e2 --no-register --only-write-certs --node-name bravo'
7cf2ca25a078912e3b0e6d63d8df319e2b5f08845e120abeb749d4291bf6a590
+ docker kill --signal=SIGTERM
docker: "kill" requires a minimum of 1 argument.
See 'docker kill --help'.

Usage:  docker kill [OPTIONS] CONTAINER [CONTAINER...]

Kill a running container
```
This repeats over and over in the logs. 

The "fake" rancher-agents, with the startup command `run.sh --server htt…` in `docker ps` have the following in their `docker logs`:
```
➜  ~ docker logs 2eed7d4605c2
INFO: Arguments: --server https://rancher.XXX.ltd --token REDACTED --ca-checksum 6e28fe6ccb58d9c4c2148eee478e7f24d1215e226184e14f4eca4ae7e4b6c7e2 --no-register --only-write-certs --node-name bravo
INFO: Environment: CATTLE_ADDRESS=162.55.103.244 CATTLE_AGENT_CONNECT=true CATTLE_INTERNAL_ADDRESS= CATTLE_NODE_NAME=bravo CATTLE_SERVER=https://rancher.XXX.ltd CATTLE_TOKEN=REDACTED CATTLE_WRITE_CERT_ONLY=true
INFO: Using resolv.conf: nameserver 185.12.64.2 nameserver 2a01:4ff:ff00::add:2 nameserver 185.12.64.1 nameserver 2a01:4ff:ff00::add:1
INFO: https://rancher.XXX.ltd/ping is accessible
INFO: rancher.XXX.ltd resolves to 172.67.173.156 104.21.96.62
INFO: Value from https://rancher.XXX.ltd/v3/settings/cacerts is an x509 certificate
time="2021-09-21T11:29:49Z" level=info msg="Rancher agent version v2.5.9 is starting"
time="2021-09-21T11:29:49Z" level=info msg="Option worker=false"
time="2021-09-21T11:29:49Z" level=info msg="Option requestedHostname=bravo"
time="2021-09-21T11:29:49Z" level=info msg="Option customConfig=map[address:XXX.XXX.XXX.XXX internalAddress: label:map[] roles:[] taints:[]]"
time="2021-09-21T11:29:49Z" level=info msg="Option etcd=false"
time="2021-09-21T11:29:49Z" level=info msg="Option controlPlane=false"
time="2021-09-21T11:29:49Z" level=info msg="Listening on /tmp/log.sock"
time="2021-09-21T11:29:50Z" level=info msg="Connecting to wss://rancher.XXX.ltd/v3/connect with token bhtkcc7dwk4vwfbmd7rn9hkjspxk5l2qmc4cb52qmbpmgj5pnw86c4"
time="2021-09-21T11:29:50Z" level=info msg="Connecting to proxy" url="wss://rancher.XXX.ltd/v3/connect"
time="2021-09-21T11:29:50Z" level=info msg="Starting plan monitor, checking every 120 seconds"
```
It's worth noting that this shows "worker=false, etcd=false controlplane=false" but this node actually has all 3 of those roles...

Happy to provide additional info on request, this issue seems identical to https://github.com/rancher/rancher/issues/34777 so I've provided additional info in hopes of getting it resolved.

**Comment by superseb** [comment] 2021-09-21 15:42
This seems to be a duplicate of https://github.com/rancher/rancher/issues/31454

**Closed by superseb** 2021-09-21 15:42 UTC
