### ISSUE TITLE
When service is in "upgraded" state , the stopped (older) instances show up as sidekicks in hosts view. 

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#7538] opened 2017-01-24 22:12 UTC
Rancher Versions: Build from master

Steps to reproduce the problem:
Create a service.
Upgrade the service.
When service is in "upgraded" state , launch the hosts view.
Stopped (older) instances show up as sidekicks in hosts view. 
<img width="969" alt="screen shot 2017-01-24 at 2 11 23 pm" src="https://cloud.githubusercontent.com/assets/4266958/22269135/029ecc88-e23f-11e6-87fe-1e4c479908ef.png">

<img width="1187" alt="screen shot 2017-01-24 at 2 11 59 pm" src="https://cloud.githubusercontent.com/assets/4266958/22269160/173d2cde-e23f-11e6-9ac5-b1e8c7e20afa.png">

**Comment by tfiduccia** [comment] 2017-01-24 22:51
This is actually a duplicate of #6998.  Alena removed unique deploymentunit field I think, anyway we were no longer able to show the container, so vincent found a workaround where he is showing them as sidekicks instead.  This will be the resolution unless Alena changes it back or creates another field.

**Comment by vincent99** [comment] 2017-01-24 22:51
At some point in the past we switched from generating a new deploymentUnit UUID every generation to keeping the same one and changing`version`. So these containers were missing entirely until 1.2 (or 1.3).  There is no way to properly group them because they have the same `deploymentUnit` uuid  and inconsistent `version` (the first container has `0` and doesn't match the rest of the ones for that version/unit)..

**Closed by tfiduccia** 2017-01-24 22:51 UTC
Labels: area/ui
