### ISSUE TITLE
Monitoring V2 Grafana root_url not specified

### ISSUE THREAD

**Issue by codyrancher** [rancher/rancher#31732] opened 2021-03-17 20:06 UTC
**What kind of request is this (question/bug/enhancement/feature request):**
bug

**Steps to reproduce (least amount of steps as possible):**
1. Launch dashboard
2. Install Monitoring application
3. Launch the grafana dashboard
4. Attempt to sign in

**Result:**
When clicking sign in you're taking back to the root of rancher.

This is being caused because the root_url isn't configured. https://grafana.com/docs/grafana/latest/administration/configuration/#root_url

**Comment by aiyengar2** [comment] 2021-04-08 00:20
@sowmyav27 I talked to @codyrancher offline and I don't think this issue is reproducible. I also don't think the root_url needs to be changed.

Can we test this on local+downstream+windows clusters and, if it's not an issue, just close it out?

We could also close the issue outright, but it would be better to test it first.

**Comment by slickwarren** [comment] 2021-04-09 15:50
tested on windows, local, and linux clusters using v2.5.8-rc2 and was unable to reproduce this issue

**Closed by slickwarren** 2021-04-09 15:50 UTC
Labels: QA/XS, [zube]: QA Working
