### ISSUE TITLE
Helm Multiple Values Files not Processed Correctly

### ISSUE THREAD

**Issue by MKlimuszka** [rancher/rancher#36242] opened 2022-01-24 16:31 UTC
*Issue description:*
Fleet appears to not process Helm values files correctly when there are multiple values files which contain the same Kubernetes resource type. 

*Business impact:*
Workaround in place to use a single values file

 It would be ideal if Fleet supported the functionality to have values for the same Kubernetes resource type (such as configMaps) across multiple values files. When we have many configMaps to manage, storing them all in one file can make them difficult to maintain. 

*Troubleshooting steps:*
1. In fleet.yaml, specify multiple values files with each values file containing a configMap resource.

2. When using Fleet to apply the configuration, it will only apply the final configMap entry. I.e. configMaps: configmap3: configvalue3 The configMaps in values-1.yaml and values-2.yaml are not applied. 

 

*Workaround:*
 Is workaround available and implemented? yes
Workaround in place to use a single values file

*Actual behavior:*
Only apply values from the last values file

*Expected behavior:*
Apply values from all three separate values files provided.

*Files, logs, traces:*
 <text>

*Additional notes:*
 The issue may lie in the following source code, which appears to combine the values files without taking into account their content: [https://github.com/rancher/fleet/pull/316/files#diff-fb8188a7a7a0777878968c7998c7529a87d5a9bfddf7b291b5762189a5329cc6R334-R364]

SURE-3425

**Comment by prachidamle** [comment] 2022-02-01 01:56
Tested this usecase with rancher v2.6.3 and found that with fleet v0.3.8, this is working as expected. The root cause of this issue is same as https://github.com/rancher/fleet/issues/416

I tested with  https://github.com/prachidamle/fleet-test-1 and have multiple configmaps mentioned in the values files under this repo. 

Reproduction steps:

Create at least one downstream cluster with rancher v2.6.3. 
On the left nav pane, go to "Continuous Delivery" and click "Create" to create a Git Repo. Enter the following fields on the form and submit to create the Git Repo.
a. Enter any valid name "configtest"
b. Enter the Repository URL https://github.com/prachidamle/fleet-test-1
c. Click "Add Path" and add a path with a value of valuetest
d. Create/submit the form
Inspect the Bundle (On the left pane the Advanced section -> Bundles. It will have a name of configtest-valuetest)
Look at the spec -> helm section. Notice that all configMaps key-value pairs as specificied in values1.yaml and values2.yaml are merged:

```
spec:
  helm:
    chart: ./demo
    values:
      configmaps:
        configmap1: configvalue1
        configmap2: configvalue2
      microService1:
        replicas: 1
        resources:
          limits:
            cpu: 500m
            memory: 500Mi
          requests:
            cpu: 256m
            memory: 256Mi
      microService2:
        replicas: 2
        resources:
          limits:
            cpu: 500m
            memory: 500Mi
          requests:
            cpu: 256m
            memory: 256Mi
    valuesFiles:
    - values1.yaml
    - values2.yaml
  namespace: default
```

**Comment by davidnuzik** [comment] 2022-02-22 16:51
**I could not reproduce. I can corroborate Prachi's results above with Rancher v2.6.3 -- as Prachi mentioned this should be fixed via https://github.com/rancher/fleet/issues/416**
 
**Reproduction Environment:**

Rancher version: v2.6.3 
Rancher cluster type: single-node docker install
Docker version: 20.10
 
Downstream cluster type: rke2 (type does not matter)
Downstream K8s version: v1.21.9+rke2r1 (version is not relevant)
 
**Reproduction steps:**

Note: I basically did exactly what Prachi covered above in the prior comment - this correctly tests this issue. I believe the customer reported the issue in Rancher v2.5.9 - I would recommend upgrading to v2.6.3 for resolution.
1. Create a downstream cluster.
2. On the left nav pane, go to Continuous Delivery and create a GitRepo. Plug in the following on this form, then submit to create it:
- Any valid name
- The repo URL: `https://github.com/prachidamle/fleet-test-1`
- Click the "Add Path" button and enter `valuetest` in this field
3. Now, on the left nav pane, expand "Advanced" and click on "Bundles". Click on the newly created bundle. It will be the newest age and have the name of the cluster and the name for the GitRepo you created in my case "dave-36242-valuetest"
4. Review the YAML. Notice the spec->helm section, both config maps are listed and we can see bolth values yaml files were indeed evaluated (because valuesFiles lists both)

![image](https://user-images.githubusercontent.com/45179589/155179321-46c65835-4d17-41d8-a17c-f3c49eba2dcf.png)


**Additional Info:**
To inspect the repo used for testing: if you click on the link to the repo mentioned above, which is https://github.com/prachidamle/fleet-test-1, and click on the valuestest folder you'll see both values yaml files and that each has a configMap mentioned at the bottom. As mentioned above in the steps, Rancher/Fleet is properly parsing both values files and including both configMaps.

**Closed as completed by davidnuzik** 2022-02-22 16:51 UTC
Labels: priority/0, internal, area/fleet
