### ISSUE TITLE
When retain_ip is set while upgrading a service , rolling back the upgrade process results in service left with retain_ip set to true.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#5476] opened 2016-07-18 23:22 UTC
Rancher Version:v1.1.1

Steps to reproduce the problem:
Scenario 1:
Create a service without retain_ip enabled.
While Upgrading this service , enable retain_ip.
After upgrade is done (when in "upgraded" state) , perform rollback.
Even after the service is rolled back , retain_ip continues to be enabled.

Scenario 2:
Create a service with retain_ip enabled.
While Upgrading this service , disable retain_ip.
After upgrade is done (when in "upgraded" state) , perform confirm_upgrade.
Upgraded service continues to have retain_ip enabled.

**Comment by tfiduccia** [comment] 2016-07-19 19:07
duplicate of #5410

**Comment by tfiduccia** [comment] 2016-07-19 19:11
Different scenario

**Comment by sangeethah** [comment] 2016-07-19 19:14
With rancher server version v1.1.1 ,  we are allow retain_ip to go from false to true while upgrading services . But we do not allow for  retain_ip to go from true to false while upgrading service , which is what is tracked in this issue.

**Closed** 2018-08-21 21:49 UTC
Labels: kind/bug, setup/automation, status/autoclosed
