### ISSUE TITLE
Add management of images under infrastructure

### ISSUE THREAD

**Issue by demarant** [rancher/rancher#3400] opened 2016-01-24 13:29 UTC
Inline with #3398, containers belongs to Applications. In this ticket I propose and argue that "Images" belongs to Infrastructure and deserve a management page. 

Right now v0.56, Rancher does now provide and overview of Docker images available on all host of an environment. It does provide a list of all running / stopped containers on each Host though and why not Images?

I would like to see under infrastructure (instead of containers) a list of all Images and versions available on each host, basically the output of the command _docker images_. 

On this "Images" page I would also like the button "Add Image". 

__Some use cases/motivation for this proposal__ 
This will allow me to _docker pull_ a specific image on all hosts (or a selected number of hosts) before a planned deployment. This will make sure that when I deploy a Stack it will run faster since all images are already available within the environment. The new images page will also make it possible to have an overview of which images are available on the hosts and possibility to clean up un-used images. There are for sure more use cases that the one I mentioned here. Right now it is impossible to debug if an image is present or not on the hosts. One is forced to ssh into the host, however we want to avoid user to have to ssh into hosts, and manage all the docker deployments via Rancher UI / CLI.

**Comment by vincent99** [comment] 2016-01-24 14:09
We only indirectly keep track of images used by containers on hosts.  There is no record of all the images on the host today.

Duplicate of https://github.com/rancher/rancher/issues/1277

**Closed by vincent99** 2016-01-24 14:09 UTC
