### ISSUE TITLE
v2prov RKE2 clusters cannot be provisioned when using an egress proxy and setting Agent Environment Variables in the Rancher UI

### ISSUE THREAD

**Issue by rosskirkpat** [rancher/rancher#36732] opened 2022-03-02 22:35 UTC
**Setup**
- Rancher version: v2.6-e93a53c35bd038d4cf0d0d96897e957ffef150c9-head
-- | --
Helm | v2.16.8-rancher1
Machine | v0.15.0-rancher79

- Browser type & version: Firefox 97.0.1 (64-bit)

**Describe the bug**
The environment variables HTTP_PROXY, HTTPS_PROXY, NO_PROXY are not being set in the custom cluster registration commands for either Linux or Windows

**To Reproduce**
- provision custom rke2 cluster through Rancher UI with proxy vars set in the Agent Environment Variables tab

**Result**
The registration commands do not have the environment variables HTTP_PROXY, HTTPS_PROXY, NO_PROXY set for the retrieval of the installation scripts when behind an egress proxy. This causes the installation scripts to be unable to be retrieved from Rancher when an egress proxy is configured/in place between downstream nodes and Rancher itself.

**Expected Result**
The registration commands should be fully functional when nodes are behind an egress proxy with the proper Agent environment variables (HTTP_PROXY, HTTPS_PROXY, NO_PROXY) set in the Rancher UI

**Notes**
Registration commands should have the environment variables HTTP_PROXY, HTTPS_PROXY, NO_PROXY set to allow the installation scripts to be retrieved from Rancher when an egress proxy.

For Windows, they would need to be inserted as shown below:
`PowerShell $env:HTTP_PROXY="XXX"; $env:HTTPS_PROXY="YYY"; $env:NO_PROXY="ZZZ"; curl.exe --insecure -fL https://RANCHER_URL/wins-agent-install.ps1 -o install.ps1; ...`

For linux, the proxy variables need to be set before calling curl to enable the install script to be fetched from Rancher:
`HTTP_PROXY="XXX" HTTPS_PROXY="YYY" NO_PROXY="ZZZ" curl -fL https://RANCHER_URL/system-agent-install.sh | ... `

**Screenshots**
redacting snapshot
![image](https://user-images.githubusercontent.com/55704795/156456934-38f1d536-02f0-48e1-bcd2-4dc4e0228733.png)

**Comment by phillipsj** [comment] 2022-03-07 21:45
![proxy-working-for-linux](https://user-images.githubusercontent.com/1568133/157123040-7e4cae31-95b5-4fc1-b2cf-e67a5b281abd.png)
![proxy-working-for-windows](https://user-images.githubusercontent.com/1568133/157123050-97953a0c-2ae6-4ff8-9881-22c8b99f9303.png)
![proxy-wins-installer](https://user-images.githubusercontent.com/1568133/157123058-e24ab7c8-e805-4c14-99b7-0ff8e1f127cc.png)

**Comment by sirredbeard** [comment] 2022-03-22 21:10
Ready to test. Sowmya moved it to test a couple of days ago. Per @rosskirkpat

**Comment by sirredbeard** [comment] 2022-03-23 18:14
Tracking issue https://github.com/rancher/windows/issues/156

No test plan required.

Dev validate: Use case with proxy setup and then bring up a Windows cluster. If works for Linux close, if not on Windows then open issue for later.

**Comment by rosskirkpat** [comment] 2022-03-24 13:30
https://github.com/rancher/rancher/issues/36574

**Comment by deniseschannon** [comment] 2022-03-24 13:43
@rosskirkpat Does this at least work for the Linux side? 

If so, we could close this for Linux and use the other issue that you created to track Windows.

**Comment by rosskirkpat** [comment] 2022-03-24 14:23
The fix involved changes for v2prov in how both the Linux and Windows installation scripts handle environment variables.

When the issue I linked [above](https://github.com/rancher/rancher/issues/36574) was opened, it was not known at the time that the issue extended to Linux as well as Windows. 

This issue was created because while investigating the reported Windows issue we found that the egress proxy use case was broken for all rke2 v2prov clusters.

The testing plan outlines validating that both the linux and windows registration commands include the proper environment variables as well as validating that nodes properly provision with the commands by using the proxy.

@deniseschannon Which issue would you like me to close?

**Comment by rosskirkpat** [comment] 2022-03-24 16:15
# Linux is working
The use-case is successfully validated for custom rke2 linux nodes. The linux nodes have the proper environment variables in the registration command and they successfully provision and join the cluster using the proxy.

![Screen Shot 2022-03-24 at 11 22 57 AM](https://user-images.githubusercontent.com/55704795/159959736-75895a4a-b379-482e-aa43-563320ce05f4.png)

![Screen Shot 2022-03-24 at 11 24 01 AM](https://user-images.githubusercontent.com/55704795/159959742-00d39822-0290-4d82-a149-4c7ed67b1f9f.png)

`10.0.1.121` is the etcd/cp rke2 node.

![Screen Shot 2022-03-24 at 11 26 08 AM](https://user-images.githubusercontent.com/55704795/159959740-3abaf799-66af-4893-b342-adf1332180db.png)

The etcd/cp rke2 linux node successfully joins.

![Screen Shot 2022-03-24 at 11 30 02 AM](https://user-images.githubusercontent.com/55704795/159959883-5056a42d-cd04-41d8-988e-5459fdecfb54.png)

`10.0.1.85` is the worker rke2 linux node 

![Screen Shot 2022-03-24 at 11 29 14 AM](https://user-images.githubusercontent.com/55704795/159960520-27831a33-c0fc-4e8e-8535-a5cd27442387.png)

The worker rke2 linux node successfully joins.

![Screen Shot 2022-03-24 at 11 33 24 AM](https://user-images.githubusercontent.com/55704795/159960246-c5dfffd7-76b2-44fd-b5c4-bd298c566e5a.png)

----

# Windows is not fixed

However, this issue is not fixed for Windows. I also found a system agent bug for Windows in how the plan is initially built prior to being applied to a Windows worker node. Both of these issues need to be fixed for this use-case to work.

The registration command from the UI fails when run from a cmd shell.

![Screen Shot 2022-03-24 at 11 35 52 AM](https://user-images.githubusercontent.com/55704795/159956126-bce1e704-234f-4b6d-a33b-278527a74755.png)

The registration command from the UI fails if you try to run the command from powershell.

![Screen Shot 2022-03-24 at 11 37 41 AM](https://user-images.githubusercontent.com/55704795/159956132-8b75736f-e74a-4396-adfe-1ee67227d723.png)

The command succeeds if a workaround is applied where you drop into powershell and remove the `powershell` invocation on the front of the command.

![Screen Shot 2022-03-24 at 11 40 20 AM](https://user-images.githubusercontent.com/55704795/159956010-fec294c4-091d-45ee-a710-be091bcc99d6.png)

The Windows worker node does use the proxy as expected once the workaround is applied.

![Screen Shot 2022-03-24 at 11 39 05 AM](https://user-images.githubusercontent.com/55704795/159956019-de84fa07-e00f-4135-aea4-6285a6dfb650.png)

The Windows worker node will show up in the UI but it will never join. This is caused by a system agent bug in how windows plans process environment variables in the v2prov planner.

![Screen Shot 2022-03-24 at 12 13 43 PM](https://user-images.githubusercontent.com/55704795/159961358-50203eb9-c069-4094-8c6d-859f9b474a82.png)


The system agent plan is passing in linux style variables to a Windows worker plan which causes the plan to fail to be applied.

```json
{"Plan":{"files":[{"content":"eyJjb25maWdzIjp7fSwibWlycm9ycyI6bnVsbH0=","path":"/etc/rancher/agent/registries.yaml"},{"content":"eyJjb25maWdzIjp7fSwibWlycm9ycyI6bnVsbH0=","path":"/etc/rancher/rke2/registries.yaml"},"content":"ewogICJub2RlLWxhYmVsIjogWwogICAgImNhdHRsZS5pby9vcz13aW5kb3dzIiwKICAgICJya2UuY2F0dGxlLmlvL21hY2hpbmU9N2Y2OGVmYzktZGEyMS00ZWU0LWJkMjUtYTYzZGU5MjJhNjk3IgogIF0sCiAgInByaXZhdGUtcmVnaXN0cnkiOiAiL2V0Yy9yYW5jaGVyL3JrZTIvcmVnaXN0cmllcy55YW1sIiwKICAicHJvdGVjdC1rZXJuZWwtZGVmYXVsdHMiOiBmYWxzZSwKICAic2VydmVyIjogImh0dHBzOi8vMTAuMC4xLjEyMTo5MzQ1IiwKICAidG9rZW4iOiAibG4yNWZzcTU0YnYyNzVtbWo3czIyano4aHQ2cWxqeHZmNDl3OXFkbTVibTVkY3puYmM3ZHIyIgp9","path":"/etc/rancher/rke2/config.yaml.d/50-rancher.yaml"}],"instructions":[{"name":"install","image":"rancher/system-agent-installer-rke2:v1.22.7-rke2r2","env":"$env:RESTART_STAMP=f80f465cfbe80ad3f6f6c82c3ab16fe2dff7e3aa69b14184368b451ea26f7ac3","HTTP_PROXY=ec2-3-239-92-48.compute-1.amazonaws.com:3128","HTTPS_PROXY=ec2-3-239-92-48.compute-1.amazonaws.com:3128","NO_PROXY=localhost,127.0.0.1,0.0.0.0,10.0.0.0/8,cattle-system.svc","$env:INSTALL_RKE2_EXEC=agent"],"args":["-File","run.ps1"],"command":"powershell.exe"}],"probes":"kubelet":{"initialDelaySeconds":1,"timeoutSeconds":5,"successThreshold":1,"failureThreshold":2,"httpGet":"url":"http://127.0.0.1:10248/healthz"}}}},"Checksum":"2d473c21d91a8a3f4271dbb6af1617a5c11ba53ff3290cd1ad1c610718fa11f8"}
```


> "HTTP_PROXY=ec2-3-239-92-48.compute-1.amazonaws.com:3128",
"HTTPS_PROXY=ec2-3-239-92-48.compute-1.amazonaws.com:3128",
"NO_PROXY=localhost,127.0.0.1,0.0.0.0,10.0.0.0/8,cattle-system.svc"

```log
{error loading system cert pool for probe (kubelet): crypto/x509: system root pool is not available on Windows}                                                                                                   3/24/2022 3:39:36 PM
{error loading system cert pool for probe (kubelet): crypto/x509: system root pool is not available on Windows}                                                                                                   3/24/2022 3:39:30 PM
{error loading system cert pool for probe (kubelet): crypto/x509: system root pool is not available on Windows}                                                                                                   3/24/2022 3:39:24 PM
{error loading system cert pool for probe (kubelet): crypto/x509: system root pool is not available on Windows}                                                                                                   3/24/2022 3:39:19 PM
{error loading system cert pool for probe (kubelet): crypto/x509: system root pool is not available on Windows}                                                                                                   3/24/2022 3:39:18 PM
{error loading system cert pool for probe (kubelet): crypto/x509: system root pool is not available on Windows}                                                                                                   3/24/2022 3:39:17 PM
{error executing instruction 0: <nil>}                                                                                                                                                                            3/24/2022 3:39:16 PM
{[Applyinator] Command powershell.exe [-File run.ps1] finished with err: <nil> and exit code: 1}                                                                                                                  3/24/2022 3:39:16 PM
{[2d473c21d91a8a3f4271dbb6af1617a5c11ba53ff3290cd1ad1c610718fa11f8_0:stderr]:  }                                                                                                                                  3/24/2022 3:39:16 PM
{[2d473c21d91a8a3f4271dbb6af1617a5c11ba53ff3290cd1ad1c610718fa11f8_0:stderr]:     + FullyQualifiedErrorId : VariableIsUndefined}                                                                                  3/24/2022 3:39:16 PM
{[2d473c21d91a8a3f4271dbb6af1617a5c11ba53ff3290cd1ad1c610718fa11f8_0:stderr]:     + CategoryInfo          : InvalidOperation: (fullEnv:String) [], ParentContainsErrorRecordException}                            3/24/2022 3:39:16 PM
{[2d473c21d91a8a3f4271dbb6af1617a5c11ba53ff3290cd1ad1c610718fa11f8_0:stderr]: +                                                                  ~~~~~~~~}                                                        3/24/2022 3:39:16 PM
{[2d473c21d91a8a3f4271dbb6af1617a5c11ba53ff3290cd1ad1c610718fa11f8_0:stderr]: + ... rviceName -Name Environment -PropertyType MultiString -Value $fullEnv}                                                        3/24/2022 3:39:16 PM
{[2d473c21d91a8a3f4271dbb6af1617a5c11ba53ff3290cd1ad1c610718fa11f8_0:stderr]: .ps1:83 char:129}                                                                                                                   3/24/2022 3:39:16 PM
{[2d473c21d91a8a3f4271dbb6af1617a5c11ba53ff3290cd1ad1c610718fa11f8_0:stderr]: At C:\var\lib\rancher\agent\work\20220324-153909\2d473c21d91a8a3f4271dbb6af1617a5c11ba53ff3290cd1ad1c610718fa11f8_0\run}            3/24/2022 3:39:16 PM
{[2d473c21d91a8a3f4271dbb6af1617a5c11ba53ff3290cd1ad1c610718fa11f8_0:stderr]: The variable '$fullEnv' cannot be retrieved because it has not been set.}                                                           3/24/2022 3:39:16 PM
{[Applyinator] Running command: powershell.exe [-File run.ps1]}                                                                                                                                                   3/24/2022 3:39:15 PM
{Extracting file Files/bin/run.ps1 to C:\var\lib\rancher\agent\work\20220324-153909\2d473c21d91a8a3f4271dbb6af1617a5c11ba53ff3290cd1ad1c610718fa11f8_0\run.ps1}                                                   3/24/2022 3:39:11 PM
{Extracting file Files/bin/sha256sum-amd64.txt to C:\var\lib\rancher\agent\work\20220324-153909\2d473c21d91a8a3f4271dbb6af1617a5c11ba53ff3290cd1ad1c610718fa11f8_0\sha256sum-amd64.txt}                           3/24/2022 3:39:11 PM
{Extracting file Files/bin/rke2.windows-amd64.tar.gz to C:\var\lib\rancher\agent\work\20220324-153909\2d473c21d91a8a3f4271dbb6af1617a5c11ba53ff3290cd1ad1c610718fa11f8_0\rke2.windows-amd64.tar.gz}               3/24/2022 3:39:10 PM
{Extracting file Files/bin/installer.ps1 to C:\var\lib\rancher\agent\work\20220324-153909\2d473c21d91a8a3f4271dbb6af1617a5c11ba53ff3290cd1ad1c610718fa11f8_0\installer.ps1}                                       3/24/2022 3:39:10 PM
{Pulling image index.docker.io/rancher/system-agent-installer-rke2:v1.22.7-rke2r2}                                                                                                                                3/24/2022 3:39:09 PM
{Using private registry config file at /etc/rancher/agent/registries.yaml}                                                                                                                                        3/24/2022 3:39:09 PM
{[Applyinator] Extracting image rancher/system-agent-installer-rke2:v1.22.7-rke2r2 to directory C:\var\lib\rancher\agent\work\20220324-153909\2d473c21d91a8a3f4271dbb6af1617a5c11ba53ff3290cd1ad1c610718fa11f8_0} 3/24/2022 3:39:09 PM
{[Applyinator] Applying one-time instructions for plan with checksum 2d473c21d91a8a3f4271dbb6af1617a5c11ba53ff3290cd1ad1c610718fa11f8}                                                                            3/24/2022 3:39:09 PM
{Detected first start, force-applying one-time instruction set}                                                                                                                                                   3/24/2022 3:39:09 PM
{Starting /v1, Kind=Secret controller}                                                                                                                                                                            3/24/2022 3:39:09 PM
{Starting remote watch of plans}                                                                                                                                                                                  3/24/2022 3:39:09 PM
{Setting C:/var/lib/rancher/agent/work as the working directory}                                                                                                                                                  3/24/2022 3:39:09 PM
{Listening on \\.\pipe\rancher_wins}                                                                                                                                                                              3/24/2022 3:39:09 PM
{Listening on \\.\pipe\rancher_wins_proxy}                                                                                                                                                                        3/24/2022 3:39:09 PM
{Rancher System Agent version dev (HEAD) is starting}                                                                                                                                                             3/24/2022 3:39:09 PM
{Stackdump - waiting signal at Global\stackdump-4572}                                                                                                                                                             3/24/2022 3:39:09 PM
```

**Comment by phillipsj** [comment] 2022-03-25 16:45
This is the system agent bug. https://github.com/rancher/rancher/issues/37044

**Comment by phillipsj** [comment] 2022-04-04 13:26
### Root cause 

The proxy environment variables, if set in the UI, were not being passed to the registration command for both Linux and Windows nodes for custom RKE2 clusters. This was requiring manual intervention when creating a cluster. 

### What was fixed, or what changes have occurred

The registration commands for both Linux and Windows nodes were updated to include the proxy environment variables set if populated in the UI. 

### Areas or cases that should be tested 

Custom RKE2 cluster provision needs testing with both Linux and Windows nodes.

### What areas could experience regressions? 

Just the registration command could experience a regression.

### Are the repro steps accurate/minimal?

1. Pull the lastest 2.6-hed or 2.6 RC.
2. Setup a proxy server following these instructions: https://confluence.suse.com/display/EN/Proxy+Setup
3. Create 1 etcd, 1 controlplane, 1 linux worker, and 1 windows worker VMs.
4. Create a custom RKE2 cluster with RKE2 1.22.7+rke2r2.
5. Add proxy variables to the cluster configuration in agent env vars section.
6. Verify that the proxy variables show up in both registration commands.
7. Run registration commands and watch proxy logs to ensure traffic flows through the proyx.

**Comment by slickwarren** [comment] 2022-05-03 17:58
tested on v2.6.5-rc6 - when registering the windows rke2 node (1.22.9+rke2r1) the cluster gives the following error: error applying plan -- check rancher-system-agent.service logs on node for more information, waiting for agent to check in and apply initial plan

Ross is currently investigating the issue.

**Comment by sirredbeard** [comment] 2022-05-04 19:09
Same error as https://github.com/rancher/rancher/issues/36574 which has PR in review

**Comment by slickwarren** [comment] 2022-05-06 20:27
reopening due to this issue: https://github.com/rancher/rancher/issues/36574#issuecomment-1119985236

**Comment by rosskirkpat** [comment] 2022-05-09 14:38
This issue is ready to be tested again. There were two fixes that went in on Friday, one fixed a nil pointer in system-agent specific to windows and the other was improving the logic in wins for csi-proxy and tlsConfig

**Closed** 2022-05-11 16:18 UTC
Labels: kind/bug, [zube]: Working, area/provisioning-rke2, status/release-blocker, team/area4, area/clusterprovisioningv2
