### ISSUE TITLE
[Feature Request] Rancher should check obvious agent IP registration issue and show hints

### ISSUE THREAD

**Issue by pengjiang80** [rancher/rancher#9434] opened 2017-07-22 02:36 UTC
Sometimes customers may register their agents to Rancher server with incorrect IP address which causes overlay network problem. For example, their load balancer doesn't support X-Forwarded-For header or their is NAT between agent and server. With automatic checking against some obvious issues (eg. two hosts have the same IP registered, or one host has public IP and the other has internal IP) and show hints, it will be helpful to a lot of entry level users. 

![image](https://user-images.githubusercontent.com/16434640/28487717-aa861a0c-6ec9-11e7-8fbb-e7b1eba689f0.png)

**Comment by superseb** [comment] 2017-07-22 14:51
Thanks for reporting, closing as duplicate of https://github.com/rancher/rancher/issues/9326

**Closed by superseb** 2017-07-22 14:51 UTC
