### ISSUE TITLE
`tolerations: [{operator: Exists}]` specification for cattle-cluster-agent prevents Pod re-scheduling in the event host node is Unavailable

### ISSUE THREAD

**Issue by axeal** [rancher/rancher#24636] opened 2019-12-17 16:04 UTC
**What kind of request is this (question/bug/enhancement/feature request):**

Bug

**Steps to reproduce (least amount of steps as possible):**

1. Create a simple multi-node Rancher provisioned custom cluster, nodes with all role
2. Identify the node hosting the running cattle-cluster-agent Pod and power this VM off
3. Observe that the cattle-cluster-agent Pod is not rescheduled once the node status shows as Unknown and the node.kubernetes.io/unreachable:NoExecute and node.kubernetes.io/unreachable:NoSchedule are added to the node automatically.

**Other details that may be helpful:**

The following toleration on the cattle-cluster-agent Deployment prevents the Pod being re-scheduled when the node it is running on is an unknown or false Ready status for longer than the `pod-eviction-timeout` (default 5m), and the `node.kubernetes.io/unreachable:NoExecute` taint is added to the node (https://kubernetes.io/docs/concepts/configuration/taint-and-toleration/#concepts  and https://kubernetes.io/docs/concepts/configuration/taint-and-toleration/#taint-based-evictions):
```
tolerations:
- operator: "Exists"
```

Delete this toleration and repeat the reproduction steps above to confirm Pod is successfully rescheduled without this toleration.

**Environment information**
- Rancher v2.3.3

gz#7543

**Comment by superseb** [comment] 2019-12-17 16:10
Sounds like a duplicate of https://github.com/rancher/rancher/issues/23087

**Comment by axeal** [comment] 2019-12-17 16:11
@superseb except in my testing the cluster did remain available in Rancher, with a node-agent handling requests instead as expected

**Comment by sadiapoddar** [comment] 2020-11-19 06:56
Reproduced this issue with 2.3.3
1. Created  3-noded all rolled enabled cluster. 
2. Powered off the node hosting  cattle-cluster-agent Pod 
3. Noticed that the cattle-cluster-agent Pod is not rescheduled once the node status shows as Unknown and the node.kubernetes.io/unreachable:NoExecute and node.kubernetes.io/unreachable:NoSchedule are added to the node automatically. Cluster never recovered by itself. 
<img width="510" alt="Screen Shot 2020-11-18 at 10 45 39 PM" src="https://user-images.githubusercontent.com/72409237/99631277-271c7b80-29f0-11eb-8171-4a1cca46534c.png">
<img width="155" alt="Screen Shot 2020-11-18 at 10 53 34 PM" src="https://user-images.githubusercontent.com/72409237/99631866-2f28eb00-29f1-11eb-86ea-e3e932d1f7ee.png">
<img width="1262" alt="Screen Shot 2020-11-18 at 10 53 55 PM" src="https://user-images.githubusercontent.com/72409237/99631872-3223db80-29f1-11eb-865a-a2f55891db11.png">

**Comment by sadiapoddar** [comment] 2020-11-19 20:35
Reproduced the issue with 2.5.2
steps.
Created 3-noded all rolled enabled cluster.
Powered off the node hosting cattle-cluster-agent Pod
Noticed that the cattle-cluster-agent Pod is not rescheduled once the node status shows as Unknown. 
With 2.5.2 seeing one taint that it's noSchedule--> node.kubernetes.io/unreachable:NoSchedule is added to the node automatically. 

Cluster never recovered by itself.
<img width="154" alt="Screen Shot 2020-11-19 at 12 21 35 PM" src="https://user-images.githubusercontent.com/72409237/99720939-50c2ba80-2a63-11eb-9722-63cba2541c5f.png">
<img width="466" alt="Screen Shot 2020-11-19 at 12 32 07 PM" src="https://user-images.githubusercontent.com/72409237/99720963-58825f00-2a63-11eb-84b7-012594b9e138.png">
<img width="934" alt="Screen Shot 2020-11-19 at 12 19 54 PM" src="https://user-images.githubusercontent.com/72409237/99721018-6a640200-2a63-11eb-810d-e890f910aa2a.png">

**Comment by sowmyav27** [comment] 2020-12-04 19:44
Use cases to validate:

### Fresh install checks

1. No user taints on a control plane node

- Deploy a cluster with 1 etcd, 3 controlplanes and 2 worker nodes
- verify cattle-cluster-agent workload's tolerations - Should not have any
- power off node - N1 on which cattle-cluster-agent Pod is deployed
- verify N1 gets unreachable:NoExecute and unreachable:NoSchedule taints
- Verify the pods are evicted form this node and schedule on the other control plane node

2. Taint a control plane node

- Deploy a cluster with 1 etcd, 3 controlplanes and 2 worker nodes
- verify cattle-cluster-agent workload's tolerations - Should NOT have any
- Taint a user node
- verify cattle-cluster-agent workload's tolerations - Only toleration for the user taint should be available.
- Verify logs in rancher container - clusterDeploy: redeployAgent: ..... adding taints on the node
- power off node - N1 on which cattle-cluster-agent Pod is deployed
- verify N1 gets unreachable:NoExecute and unreachable:NoSchedule taints
- Verify the pods are evicted form this node and schedule on the other control plane node

### Upgrade use cases - from 2.5.3 to 2.5-head and from 2.5.3 to master-head

3. No user taints on a control plane node

- On 2.5.3 rancher, Deploy a cluster with 1 etcd, 3 controlplanes and 2 worker nodes
- verify cattle-cluster-agent workload's tolerations and this is available
  tolerations:
  - operator: "Exists"
- Upgrade rancher to 2.5-head
- verify cattle-cluster-agent workload's tolerations - Should not have any
- power off node - N1 on which cattle-cluster-agent Pod is deployed
- verify N1 gets unreachable:NoExecute and unreachable:NoSchedule taints
- Verify the pods are evicted form this node and schedule on the other control plane node

4. Taint a control plane node

- On 2.5.3 rancher, Deploy a cluster with 1 etcd, 3 controlplanes and 2 worker nodes
- verify cattle-cluster-agent workload's tolerations and this is available
  tolerations:
  - operator: "Exists"
- Upgrade rancher to 2.5-head
- verify cattle-cluster-agent workload's tolerations - Only toleration for the user taint should be available.
- power off node - N1 on which cattle-cluster-agent Pod is deployed
- verify N1 gets unreachable:NoExecute and unreachable:NoSchedule taints
- Verify the pods are evicted form this node and schedule on the other control plane node

**Comment by adampl** [comment] 2020-12-08 13:53
Note that **k8s 1.19 has a bug** that removes the `NoExecute` taint from unavailable nodes: https://github.com/kubernetes/kubernetes/issues/94183

**Comment by sadiapoddar** [comment] 2020-12-09 02:18
Verified with 2.5-head,b2953cb, and k8s 1.18.12 

1. Created 3-noded all rolled enabled cluster.
2. Powered off the node hosting cattle-cluster-agent Pod
3. Noticed that the cattle-cluster-agent Pod was recreated on another available node automatically

<img width="842" alt="Screen Shot 2020-12-08 at 6 09 08 PM" src="https://user-images.githubusercontent.com/72409237/101564913-d9f15100-3980-11eb-8fef-6d4c303a8420.png">

**Comment by sadiapoddar** [comment] 2020-12-09 22:54
Tested for the following scenarios for user-defined taints on the control plane node
2.5-head, 8d759be
1. Deployed a cluster with 1 etcd, 3 control planes, and 2 worker nodes
2. Found that all  the control plane nodes have no schedule taint is set by default

<img width="1337" alt="Screen Shot 2020-12-09 at 12 31 00 PM" src="https://user-images.githubusercontent.com/72409237/101697322-7de40680-3a2c-11eb-8321-939bd05fb404.png">
3. cattle-cluster-agent system pod has the following tolerations set by default
<img width="1265" alt="Screen Shot 2020-12-09 at 2 07 07 PM" src="https://user-images.githubusercontent.com/72409237/101697467-bbe12a80-3a2c-11eb-8834-25dae9ae23bc.png">

4. Defined a new taint called "test1" on all the control plane nodes 
<img width="929" alt="Screen Shot 2020-12-09 at 12 39 39 PM" src="https://user-images.githubusercontent.com/72409237/101697703-22664880-3a2d-11eb-9905-9da58798df6e.png">

5. Noticed that cattle-cluster agent added that toleration for this new taint automatically
<img width="1302" alt="Screen Shot 2020-12-09 at 12 35 15 PM" src="https://user-images.githubusercontent.com/72409237/101697737-35791880-3a2d-11eb-9e75-0d18ff2d5537.png">

6. Powered-down the control plane node where the cattle-cluster-agent pod was running

7. the cattle-cluster-agent pod was never recreated on other control plane node automatically

8. When we manually deleted the cattle-cluster-agent pod, then it's recreated automatically on another control plane node

It's expected that the cattle-cluster-agent should have recreated on another control plane node automatically

Reopening the bug

**Comment by sadiapoddar** [comment] 2020-12-11 00:58
Retested for users defined taints
2.5-head,  commit 3463f5a, for both k8s 1.18.x and k8s 1.19.x
Steps.
1. deployed 2.5.3 a cluster with 1 etcd, 3 control planes, and 2 worker nodes
2. tainted all control plane nodes with a taint(example: key1=value1:NoSchedule)
3. Checked that tiants and tolerations were applied correctly 
4. Powered down the control plane node where cattle-cluster-agent was running
5. Notice that the power down node was tainted with "noExecute" taint
6. the cattle-cluster-agent pod was recreated automatically on another control plane no

Tested the upgrade cases by upgrading the 2.5.3 rancher server to v2.5-rc3, k8s 1.19.x

case1: 
No user taints on a control plane node
1. deployed 2.5.3 a cluster with 1 etcd, 3 control planes, and 2 worker nodes
2. Upgrade rancher to 2.5.4-rc3
3. Powered down the control plane node where cattle-cluster-agent was running
4. Notice the note was tainted with "noExecute" taint
5. the cattle-cluster-agent pod was recreated automatically on another control plane node

case:2 
1. deployed 2.5.3 a cluster with 1 etcd, 3 control planes, and 2 worker nodes
2. tainted all control plane nodes with a taint(example: key1=value1:NoSchedule)
3. Upgrade rancher to 2.5-head
4. Powered down the control plane node where cattle-cluster-agent was running
5. Notice the note was tainted with "noExecute" taint
6. the cattle-cluster-agent pod was recreated automatically on another control plane node

All the above test cases passed.

**Comment by sadiapoddar** [comment] 2020-12-11 02:22
Tested hosted cluster deployment type.
on 2.5-master, e4ce376
1. created a gke cluster
2. added the label "cattle.io/cluster-agent=true" on a worker node where cattle-cluster-agent was not running
3. from gke console power down the worker node where the cattle-cluster-agent was running
4. a few minutes less than 5 minutes, gke cluster created a new node 
5. the cattle-cluster-agent was running on that new node but not one the node which had "cattle.io/cluster-agent=true" label was added.

Reopening the bug for Seb to look at. @superseb  I am keeping the setup in case you want to debug

**Comment by superseb** [comment] 2020-12-14 16:19
The issue seen in GKE was because the node was shutdown in the GKE console, and because GKE updates the existing node object resource in k8s with the new IP address, it never triggered the functionality the pod reaching the maximum tolerationSeconds (300 seconds) to evict the pod, because the node object resource was updated with the new IP and the existing pod was just started on the new node.

**Comment by sangeethah** [comment] 2020-12-14 16:21
Related doc issue - https://github.com/rancher/docs/issues/2901

**Closed** 2020-12-14 16:21 UTC
Labels: [zube]: To Test, internal, kind/bug
