### ISSUE TITLE
cannot get basic service up

### ISSUE THREAD

**Issue by anandkumarpatel** [rancher/rancher#1442] opened 2015-07-09 01:17 UTC
I started the getting started tutorial, and am blocked as soon as it is time to create a service or container.

I have 3 amazon boxes, all m3.mediums ubuntu 14.04 kernel 3.13.0-57-generic
If any more info is needed let me know.

one runs master server, the other 2 are slaves.
I have the slave connecting to master (I see them on the UI) however creating anything fails to complete.

I tried to get a vanilla mongo service running , and it just spins on networking
![screen shot 2015-07-08 at 6 12 54 pm](https://cloud.githubusercontent.com/assets/2194285/8585881/fad751d8-259c-11e5-90cc-e73926ae2836.png)

i tried just to run mongo itself on the host by clicking +add container, still spins on networking.
on slaves:
```
rancher/agent-instance:v0.3.1
rancher/agent:v0.7.9
```

error from agent
```
W0709 01:15:18.228136 27278 handler.go:524] Error while processing event ("/memory.kmem.tcp.max_usage_in_bytes": 0x200 == IN_DELETE): unable to detect container from watch event on directory "/memory.kmem.tcp.max_usage_in_bytes"
W0709 01:15:18.228150 27278 handler.go:524] Error while processing event ("/cgroup.procs": 0x200 == IN_DELETE): unable to detect container from watch event on directory "/cgroup.procs"
W0709 01:15:18.228164 27278 handler.go:524] Error while processing event ("/cgroup.event_control": 0x200 == IN_DELETE): unable to detect container from watch event on directory "/cgroup.event_control"
W0709 01:15:18.228185 27278 handler.go:524] Error while processing event ("/cgroup.clone_children": 0x200 == IN_DELETE): unable to detect container from watch event on directory "/cgroup.clone_children"
W0709 01:15:18.228205 27278 handler.go:524] Error while processing event ("/tasks": 0x200 == IN_DELETE): unable to detect container from watch event on directory "/tasks"
W0709 01:15:18.228217 27278 handler.go:524] Error while processing event ("/notify_on_release": 0x200 == IN_DELETE): unable to detect container from watch event on directory "/notify_on_release"
W0709 01:15:18.228252 27278 handler.go:524] Error while processing event ("/sys/fs/cgroup/memory/docker/b9f6596eecdfe650c1e86f5a5ce8a95921843bb062d4240d9b6e58447be49884": 0x40000200 == IN_DELETE|IN_ISDIR): inotify_rm_watch: invalid argument
2015-07-09 01:15:18,782 ERROR docker [139921774156848] [delegate.py:126] Can not call [f9984725-8757-4c71-8609-0cdc76465ac3], container is not running
2015-07-09 01:15:18,789 ERROR docker [139921774161424] [delegate.py:126] Can not call [f9984725-8757-4c71-8609-0cdc76465ac3], container is not running
2015-07-09 01:15:18,814 ERROR docker [139921774161424] [delegate.py:126] Can not call [f9984725-8757-4c71-8609-0cdc76465ac3], container is not running
2015-07-09 01:15:18,816 ERROR docker [139921774155568] [delegate.py:126] Can not call [f9984725-8757-4c71-8609-0cdc76465ac3], container is not running
2015-07-09 01:15:18,969 ERROR docker [139921774159824] [delegate.py:126] Can not call [f9984725-8757-4c71-8609-0cdc76465ac3], container is not running
time="2015-07-09T01:15:19Z" level="info" msg="Processing event: &docker.APIEvents{Status:\"start\", ID:\"b9f6596eecdfe650c1e86f5a5ce8a95921843bb062d4240d9b6e58447be49884\", From:\"rancher/agent-instance:v0.3.1\", Time:1436404519}"
time="2015-07-09T01:15:19Z" level="info" msg="Assigning IP [10.42.251.232/16], ContainerId [b9f6596eecdfe650c1e86f5a5ce8a95921843bb062d4240d9b6e58447be49884], Pid [14386]"
time="2015-07-09T01:15:19Z" level="info" msg="Processing event: &docker.APIEvents{Status:\"start\", ID:\"b9f6596eecdfe650c1e86f5a5ce8a95921843bb062d4240d9b6e58447be49884\", From:\"-simulated-\", Time:0}"
time="2015-07-09T01:15:19Z" level="info" msg="Container locked. Can't run StartHandler. ID: [b9f6596eecdfe650c1e86f5a5ce8a95921843bb062d4240d9b6e58447be49884]"
```
errors from agent-instance
```
line 7: Family mismatch at [ out ipsec esp/tunnel/172.17.0.109-::ffff:54.183.14.224/require]
parse failed, line 7.
[scripts.sh:165] '[' -e /var/lib/cattle/etc/cattle/setkey ']'
[scripts.sh:168] return 1
[config.sh:1] cleanup
[config.sh:9] EXIT=1
[config.sh:11] '[' -e /var/lib/cattle/download.iFeAmQ1 ']'
[config.sh:12] rm -rf /var/lib/cattle/download.iFeAmQ1
[config.sh:15] return 1
The system is going down NOW!
Sent SIGTERM to all processes
Sent SIGKILL to all processes
Requesting system reboot
```

I want to try out rancher, but basic functionally is broken out of the box and I can not easily find out why or how to fix it. any help would be appreciated.

**Comment by cjellick** [comment] 2015-07-09 12:41
I don't think we've seen this problem before @anandkumarpatel.

The errors from the agent that are like
```
Error while processing event ("/memory.kmem.tcp.max_usage_in_bytes": 0x200 == IN_DELETE):...
```
appear to be coming from cadvisor and are potentially related linux security. Do you have AppArmor or SELinux running?
Potentially related cadivor issues:
https://github.com/google/cadvisor/issues/616
https://github.com/google/cadvisor/issues/333

Can you post the output of docker info, docker version, and docker ps -a here?

Finally are you able to create a mongo container directly on the host by sshing into the host and doing the equivalent `docker run ...`?

**Comment by deniseschannon** [comment] 2015-07-13 20:43
@anandkumarpatel Could you also provide the specific AMI ID that you used? I'd like to try and set up with the same AMI.

**Comment by anandkumarpatel** [comment] 2015-07-13 21:15
I have already terminated the instances so I can't give you exact details but all I did was start 3 amazon EC2 instances `Ubuntu Server 14.04 LTS (PV), SSD Volume Type - ami-d16a8b95`
and I know I was running docker  1.7.0

I don't remember if I did `apt-get update && apt-get upgrade` or not, but after I launched the instances I installed docker via `wget -qO- https://get.docker.com/ | sh` and then just ran master rancher on one node and slaves on the other two. (for the slave I just copied the line the UI provided for adding manual host)

**Comment by deniseschannon** [comment] 2015-07-13 21:52
I used the same ami and steps you outlined, but had no issues.

Did you make sure your security group has the appropriate ports open? 
http://docs.rancher.com/rancher/rancher-ui/infrastructure/hosts/amazon/#EC2Ports

When adding the host to Rancher, you'll want to make sure that the IP of the host is correctly shown in the Rancher UI. Sometimes Rancher selects the private IP or docker0 IP instead of the public one, which could cause issues. To fix that you add in the environment variable `-e CATTLE_AGENT_IP=<public-ip>` to the agent command.

**Comment by hasJackb** [comment] 2015-07-16 21:39
FYI, I'm having the same issue, trying to run server/agent on the same Ubuntu 14.04 box. I'm passing the CATTLE IP through, and everything seems like it's working until I try to launch a service. I'm not having these same issues doing the same thing on an Arch box with an older version of Rancher. Details below. SELinux is not running, and this happens with event he most trivial single-instances services. I have no trouble starting them from Docker directly. I'm happy to provide as much info as possible, but I'm not sure what's most useful.

Arch Box: Linux 4.0.6-1-ARCH
Rancher 	v0.25.0
Cattle 	v0.58.0
User Interface 	v0.29.0
Rancher Compose 	latest

Ubuntu 14.04 Box: Linux 3.13.0-57-generic
Rancher 	v0.28.0
Cattle 	v0.64.0
User Interface 	v0.34.0
Rancher Compose 	beta/latest

**Comment by deniseschannon** [comment] 2015-07-16 22:09
@hasJackb What version of Docker are you running? I just tested with Docker 1.7.1 and did not encounter any issues.

Can you provide me some more details on your setup?

1. Where are you launching Rancher server (cloud, localhost)? Are you using SSL or any other unique scenario to get it up?
2.  Did you configure access control or set up any environments before or after adding hosts?
3. Did you change the host registration from the default settings (typically the public IP)?
3. What image are you using the launch a service? Are you setting any advanced options or scheduling rules? Did you only have the issues after trying to start the service? Could you provide me a copy of the rancher-compose and docker-compose files from the stack/project? 

Finally, can you provide me the `docker logs` for the rancher server container?

For the rancher agent, can you follow these directions to provide me the logs for the rancher agent?

```bash
# On the host with issues, navigate to the specific folder
$ cd /var/log/rancher/
$ cat agent.log
```

Sorry, I just asked for a lot of information, but I've been unable to reproduce.

**Comment by hasJackb** [comment] 2015-07-17 14:51
@deniseschannon No problem! I appreciate the quick response.

1. I'm running Rancher server on a local, Ubuntu 14.04 desktop box. I'm not using SSL or anything other than a stock 'run the container' approach. I'm running both the server and the agent on the same box, and I've tried running it with and without setting the CATTLE_IP environment var on the agent. Same problem either way.
2. I did not add access control. Since this is in my lab, it has no inbound connections, and I was trying to keep things vanilla since I was going to tear it down after some testing.
3. I'm running internal DNS, and in the Rancher UI when going to the Add a Host page, I changed the suggested/guessed hostname from the hostname of the machine to the FQDN of the machine on the home network. It is resolvable; I've tested that. Thinking it might somehow be an issue, I also tried using the IP of the machine, with the same issues. As mentioned in 1), I've also tried setting the CATTLE_IP with no effect.
4. The docker-compose file is trivial (see below). After having issues I decided to just try to deploy MySQL to narrow things down; the problem is still there. I have no rancher-compose file (so a default scaling of 1, no addtl. settings).

My logs are 5k+ lines long; not sure how best to send them to you. I have 3 of them, from 3 different attempts. Let me know what would be easiest.

```
---
MySQL:
  image: library/mysql
  ports:
    - 3306
  environment:
    MYSQL_ROOT_PASSWORD: secret
    MYSQL_DATABASE: test
  stdin_open: true
  tty: true
```

**Comment by deniseschannon** [comment] 2015-07-17 16:21
For logs, would you be able to do a `docker logs -f` on the rancher/agent container  and at the same time a `docker logs -f` on the rancher/server container and try to start the service again? Can you provide just the snippet of logs for when you try to start the service?

Let's start with these logs when you try the service before looking into the more detailed ones.

**Comment by hasJackb** [comment] 2015-07-17 16:55
Yeah, I can do that, but probably not until this weekend or Monday, as I'm now traveling.

**Comment by deniseschannon** [comment] 2015-08-20 21:29
@anandkumarpatel @hasJackb If you are still having these same issues, can you please let me know? If not, I will be closing this issue in a couple of days as I have been unable to reproduce.

**Comment by hasJackb** [comment] 2015-08-21 16:42
@deniseschannon Sorry, things have been quite hectic. I'll try to verify today.

**Closed** 2015-09-02 17:14 UTC
Labels: kind/question
