### ISSUE TITLE
[BUG] Can not upgrade RKE1 1.22 cluster via rancher 2.7.2+

### ISSUE THREAD

**Issue by hoerup** [rancher/rancher#41292] opened 2023-04-25 20:39 UTC
**Rancher Server Setup**
- Rancher version: using Rancher 2.7.2 or 2.7.3
- Installation option (Docker install/Helm Chart): docker

**Information about the Cluster**
- Kubernetes version: RKE1 1.22.9
- Cluster Type (Local/Downstream): downstream

**Describe the bug**
Trying to upgrade a RKE1/1.22.9  cluster to 1.24.10 failed with the message 
```
Failed to validate cluster: cluster version must be at least v1.23 to use PodSecurity in RKE
```

But after downgrading to Rancher 2.7.1 the cluster upgrade was successfull

**To Reproduce**

**Result**

**Expected Result**

**Screenshots**

**Additional context**

SURE-6328

**Comment by WMP** [comment] 2023-04-27 11:36
I have this same, Rancher 2.6.5 and upgrade from rke 1.3.19 k8s 1.22 to rke 1.4.5 k8s 1.23

**Comment by AcidAngel21** [comment] 2023-04-27 11:40
I have the same problem.
It seems to have something to do with Pod Security Admissions (PSA) support that has been added by RKE v1.4.4 for clusters with Kubernetes v1.23 and above.

**Comment by jiaqiluo** [comment] 2023-04-28 23:08
I can confirm this is a bug in Rancher v2.7.2+ and RKE 1.4.4+. 


## Cause 

Starting in RKE 1.4.4, RKE support using PSA( Pod Security Admission) in cluster version 1.23 and above.

When RKE initializes the cluster, it sets the default value to the field `spec.Services.KubeAPI.PodSecurityConfiguration` when no value is provided in the cluster.yml file (see [code](https://github.com/rancher/rke/blob/5d360491203a3c1511aa6d12c496679dea05ba37/cluster/defaults.go#L398-L400)) **regardless of the cluster's Kubernetes version**. 
But later on, when RKE validates the cluster's configuration before starting the upgrading, it expects to see the abovementioned field to be set only for clusters whose **k8s version is at least 1.23** (see [code](https://github.com/rancher/rke/blob/5d360491203a3c1511aa6d12c496679dea05ba37/cluster/validation.go#L691-L703)).

Even though we can not directly create a cluster with k8s version 1.22 or less with RKE 1.4.4, we can use RKE 1.4.4 to manage existing clusters. When the existing cluster's k8s version is 1.22 or less, we will hit this bug when running the `rke up` command.  The command fails with the following error 
```
FATA[0000] Failed to validate cluster: cluster version must be at least v1.23 to use PodSecurity in RKE
```

Similarly, on  the Rancher side, if we upgrade Rancher from v2.7.1 or less to v2.7.2 or above and have an existing downstream RKE1 cluster k8s version 1.22 or less, if we upgrade or edit the cluster in Rancher UI, the cluster will be stuck in the upgrading state with the following error message:
```
Failed to validate cluster: cluster version must be at least v1.23 to use PodSecurity in RKE
```
<img width="812" alt="Screenshot 2023-04-28 at 2 46 50 PM" src="https://user-images.githubusercontent.com/6218999/235261724-f57b5cf6-88be-46c9-9fb1-e2297da49db0.png">

 
## Workaround 

For the standalone RKE cluster, we can use RKE CLI 1.3.20 or less to upgrade the cluster to 1.23; afterward, we use RKE CLI 1.4.4 to manage the cluster.  If we can not upgrade the cluster version, we must keep using RKE CLI 1.3.20 or less to manage the cluster.  
 

On the Rancher side,  First of all, we should upgrade any existing downstream to 1.23 or above before upgrading Rancher to v2.7.2 or above to eliminate the bug.  

If, unfortunately, we have already upgraded Rancher and have downstream clusters being affected,  because the upgrade process fails at the pre-flight checks, the cluster should still be functional even if its state is stuck on `updating`. But it also means that any other editing on the cluster, except for the Kubernetes version, can not take effect.

**Comment by markusewalker** [comment] 2023-05-01 17:08
**QA TEST PLAN**

Scenarios
|Scenario|Test Case|
|---|---|
|1|As a standard user, provision a downstream RKE1 node driver v1.22.x cluster in Rancher 2.6.12, upgrade Rancher to v2.7-head and upgrade the cluster to v1.25.x|

**Comment by markusewalker** [comment] 2023-05-01 17:23
Reproduced this on `v2.7-head` https://github.com/rancher/rancher/commit/8b3155933c3982851ccd17af604da1ce44c3c76c.

**ENVIRONMENT DETAILS**
- Rancher install: Docker
- Rancher version: `v2.7-head` https://github.com/rancher/rancher/commit/8b3155933c3982851ccd17af604da1ce44c3c76c
- Browser: Chrome

**TEST RESULT**
Scenarios
|Scenario|Test Case|Result|
|---|---|---|
|1|As a standard user, provision a downstream RKE1 node driver v1.22.x cluster in Rancher 2.6.12, upgrade Rancher to v2.7-head and upgrade the cluster to v1.25.x|:x:|

**REPRO STEPS**

**Scenario 1**
1. Deployed Rancher v2.6.12 and logged in as a standard user.
2. Provisioned a downstream node driver RKE1 `v1.22.13` cluster.
3. Upgraded Rancher to `v2.7-head` https://github.com/rancher/rancher/commit/8b3155933c3982851ccd17af604da1ce44c3c76c.
4. Attempted to upgrade the RKE1 cluster to v1.25 but received error message `Failed to validate cluster: cluster version must be at least v1.23 to use PodSecurity in RKE`.

**Comment by AcidAngel21** [comment] 2023-05-08 10:01
Will the issue be fixed in the next release?

**Comment by jiaqiluo** [comment] 2023-05-09 16:42
Adding this to the milestone for now

**Comment by snasovich** [comment] 2023-06-08 22:01
> Adding this to the milestone for the next release for now

@AcidAngel21 , we could not get it done in time for the upcoming release so currently _targeting_ (no commitment yet) Q3 release.
cc: @jiaqiluo

**Comment by P-n-I** [comment] 2023-06-13 09:50
Is there any workaround for a cluster that's been caught by this bug?  Ours is now stuck trying to upgrade from k8s 1.20.1.  I tried rolling rancher back to 2.7.1 but `Error: UPGRADE FAILED: chart requires kubeVersion: < 1.25.0-0 which is incompatible with Kubernetes v1.25.10+rke2r1` blocks me as I can't downgrade k8s.

**Comment by Brianalmeida** [comment] 2023-06-13 18:05
It should be worth noting that the workaround that @jiaqiluo provided only works for clusters created using the RKE CLI and ***NOT*** clusters provisioned by Rancher in the UI. From my experience, this way has yet to be doable and would likely result in performing a backup/restore on the cluster.  

@P-n-I, this cluster seems to have fallen behind on updates, but the minimum Kubernetes version for the Rancher 2.7 branch is 1.23. Perhaps downgrading Rancher back to 2.6, upgrading your downstream clusters to 1.23, and then kicking off a Rancher upgrade back to the desired 2.7 version would be ideal.

**Comment by P-n-I** [comment] 2023-06-14 06:38
@Brianalmeida thanks will do.

**Comment by femtonelson** [comment] 2023-06-26 16:26
![image](https://github.com/rancher/rancher/assets/57707061/d9c977e4-4bdd-4912-bda7-c65bdc79b823)
Hello,
Please help out. 
Rancher version : 2.7.4

**Comment by jiaqiluo** [comment] 2023-06-26 23:45
hi @femtonelson , have you tried the workaround mentioned in this [comment](https://github.com/rancher/rancher/issues/41292#issuecomment-1528181762)  ?

**Comment by femtonelson** [comment] 2023-06-27 12:33
Hi @jiaqiluo,
Added a node to the downstream cluster with all three roles and the issue got resolved.
![image](https://github.com/rancher/rancher/assets/57707061/b9d90156-64dc-4260-bcf3-3dd0911e8b75)

**Comment by belfhi** [comment] 2023-06-27 12:36
Wait, @femtonelson are you saying the upgrade worked after you added a node?

**Comment by Brianalmeida** [comment] 2023-06-27 12:41
It sounds like this comment [here](https://github.com/rancher/rancher/issues/41292#issuecomment-1609413320) was missing the required roles (in this case, it might have been missing either a control plane/etcd role) to provision this downstream cluster. RKE cluster provisioning will fail if one of three roles is absent (i.e., control plane, etcd, worker). 

Does this sound about right to you? @femtonelson

**Comment by atsai1220** [comment] 2023-06-29 23:04
This was confusing. [This](https://github.com/rancher/rke/pull/3261) rke issue was marked as resolved in the v1.4.6 release notes and v1.4.6 is part of rancher v2.4.7 [here](https://github.com/rancher/rancher/blob/eef55334b8efe838a057bdcf0ff31601d5f64e1b/go.mod#L121)

However, inspecting the commit that is part of rke v1.4.6, I [do not see the merged changes ](https://github.com/rancher/rke/blob/f7e340058df5ad031b02fde436ee5880465e6b7a/cluster/defaults.go#L401-L410) :( 

I would expect the changes [here](https://github.com/jiaqiluo/rke/blob/6e4a40fe54e29b77a32670ac2f1b154ec2a67948/cluster/defaults.go#L396-L412) to be part of v1.4.6 since it is part of the release notes.

**Comment by jiaqiluo** [comment] 2023-07-14 00:08
This issue can be validated in the latest v2.7-head

**Comment by jiaqiluo** [comment] 2023-07-18 23:43
Hi @thaneunsoo, when you validate the fix for this issue, could you confirm that Rancher logs do not flood with the following error message? 
`
[ERROR] error syncing 'c-XXXX/m-YYYY': handler machinesLabelSyncer: Failed to validate cluster: cluster version must be at least v1.23 to use PodSecurity in RKE, requeuing
`

[The QA TEST PlAN ](https://github.com/rancher/rancher/issues/41292#issuecomment-1529963170) is updated to call out this specific checking item.

**Comment by thaneunsoo** [comment] 2023-07-19 18:02
### Test Environment: ###
Rancher version: v2.7-head 95f0b50
Rancher cluster type: HA
Docker version: 20.10

Downstream cluster type: rke1

----------

### Testing: ###
Tested this issue with the following steps:
1. Deploy Rancher v2.6.12 and logged in as a standard user
2. Provision a downstream node driver RKE1 v1.22.17 cluster
3. Upgrade Rancher to v2.7-head 95f0b50
4. Attempted to upgrade the RKE1 cluster to v1.25.11

**Result**
Upgrade was successful and I did not see the following error
```
 [ERROR] error syncing 'c-XXXX/m-YYYY': handler machinesLabelSyncer: Failed to validate cluster: cluster version must be at least v1.23 to use PodSecurity in RKE, requeuing
```

I did see the following warning though this is fine.
```
33 warnings.go:80] policy/v1beta1 PodSecurityPolicy is deprecated in v1.21+, unavailable in v1.25+
```

**Closed by thaneunsoo** 2023-07-19 18:02 UTC
Labels: kind/bug, internal, [zube]: Done, QA/S, team/area2
