### ISSUE TITLE
LoadBalancer still says Initializing when API says active

### ISSUE THREAD

**Issue by jwhitcraft** [rancher/rancher#3413] opened 2016-01-26 02:43 UTC
After changing or creating a LB, it still says Initializing in the interface but the api says Active:

![screenshot 2016-01-25 21 41 54](https://cloud.githubusercontent.com/assets/26738/12571187/a51c3228-c3ac-11e5-9e80-8b2ac6994228.png)

using v0.56.0

**Comment by sshipway** [comment] 2016-01-26 03:21
Are your "Initializing" Load balancers actually working?  On my 0.56 upgraded system they seem to be inactive.  However, I do have a couple of LBs that are working correctly.  #3415

**Comment by jwhitcraft** [comment] 2016-01-26 03:22
@sshipway, some are working correctly. I was seeing issues where it seed like they were not, but in fact it was because my hosts couldn't talk to each other.

once i deleted the network agent and rebooted my hosts, it all seems fine now.

**Comment by qrpike** [comment] 2016-01-26 03:46
Having LB issues as well with CoreOS.

Seems to be a problem with Network Agent.

```
1/25/2016 9:57:55 PMrancher-net: no process found
1/25/2016 9:57:55 PMcharon: no process found
1/25/2016 9:57:56 PMtime="2016-01-26T02:57:56Z" level=error msg="Failed to connect to charon: dial unix /var/run/charon.vici: connect: connection refused"
1/25/2016 9:57:57 PMtime="2016-01-26T02:57:57Z" level=error msg="Failed to connect to charon: dial unix /var/run/charon.vici: connect: connection refused"
1/25/2016 9:57:58 PM2016/01/26 02:57:58 Failed to talk to charon:%!(EXTRA *net.OpError=dial unix /var/run/charon.vici: connect: connection refused)
1/25/2016 9:57:58 PMcharon: no process found
```

**Comment by deniseschannon** [comment] 2016-01-27 22:49
I know @sshipway and @qrpike were using CoreOS, and they should upgrade to v0.56.1 and that should solve the LB issue as your connectivity between hosts would get fixed.

@jwhitcraft Are you still having this issue? Does connectivity work for your hosts? I know you have the separate issue with rancher-compose-executor, but that should be outside the scope of this issue (i think).

**Comment by sshipway** [comment] 2016-01-27 22:50
Confirmed that Rancher 0.56.1 fixed this issue for me.

**Comment by qrpike** [comment] 2016-01-28 10:29
@deniseschannon Fixed the issue for me as well, thanks for the quick fix!

**Comment by deniseschannon** [comment] 2016-01-28 15:00
Closing at it seems everyone in this issue has their issues resolved.

**Closed by deniseschannon** 2016-01-28 15:00 UTC

**Comment by jwhitcraft** [comment] 2016-01-28 19:11
@deniseschannon, it's functioning fine, it just says Initializing.  I need to upgrade and to 0.56.1 and test.  If it's still an issue, i'll file an new ticket.
