### ISSUE TITLE
Metrics server pod is not getting evicted when a worker node is powered off

### ISSUE THREAD

**Issue by sowmyav27** [rancher/rancher#26191] opened 2020-03-22 19:08 UTC
**What kind of request is this (question/bug/enhancement/feature request):** bug

**Steps to reproduce (least amount of steps as possible):**

- Deploy cluster - Cluster spec - 1 etcd, 2 control, 3 worker nodes
- Power off W1 worker node.
- Go to System Project --> Metrics server workload - the pod is deployed in W1 and is not evicted, status of the pods are "Unknown"

**Expected Result:**
The metrics server pod should get evicted from W1 and deploy in another node.

**Note:**

- Apps do not deploy on the cluster - mySql. Error seen : `Failed to install app mysql. Error: Could not get apiVersions from Kubernetes: unable to retrieve the complete list of server APIs: metrics.k8s.io/v1beta1: the server is currently unable to handle the request`
- CIS scan runs do not work. 

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): master-head - commit id: `546b039e4` 
- Installation option (single install/HA): single

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): rke do
- Kubernetes version (use `kubectl version`):

```
1.17.4
```

**Comment by sangeethah** [comment] 2020-03-23 00:41
This behavior is also seen when testing with rancher server version - `v2.3.5`

**Comment by StrongMonkey** [comment] 2020-03-23 18:24
The workaround is to delete the pod until the pod gets scheduled into healthy nodes.

**Comment by sowmyav27** [comment] 2020-03-23 19:58
**Verified on master-head - commit id - `371ec137f`**

**Steps:**

- Deploy cluster - Cluster spec - 1 etcd, 2 control, 5 worker nodes
- Power off W1 worker node
- Go to System Project --> metrics workload - the pod is deployed in nodes W1, and is not evicted, status of the pod is "Unknown"
- Delete the pod deployed on W1 . It will get deployed on another active worker
- CIS scan run is successful on this cluster.

**Comment by deniseschannon** [comment] 2020-09-01 23:02
Closing in favor of https://github.com/rancher/rancher/issues/26190 as it's the same root cause

**Closed by deniseschannon** 2020-09-01 23:02 UTC
Labels: [zube]: Team Red Backlog, kind/bug-qa
