### ISSUE TITLE
Constant attempts made to reach cluster that has been removed (cluster was removed when it was stuck in "updating" state).

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#15717] opened 2018-09-19 20:59 UTC
Rancher server - v2.1.0-rc3

Steps to reproduce the problem:
Create a DO cluster with 1 node.
Stopped kube-apiserver in the node and added 2 more nodes .
Cluster got stuck  in "Updating" state which is tracked in https://github.com/rancher/rancher/issues/15422.

Delete this cluster.
Cluster gets deleted from rancher server.

There is a constant attempt made to reach the cluster even after it got deleted.

Rancher server logs are filled with these error messages:

```
E0919 19:21:37.516735       6 reflector.go:205] github.com/rancher/rancher/vendor/github.com/rancher/norman/controller/generic_controller.go:139: Failed to list *v1.ClusterRoleBinding: Get https://165.227.177.83:6443/apis/rbac.authorization.k8s.io/v1/clusterrolebindings?limit=500&resourceVersion=0&timeout=30s: dial tcp 165.227.177.83:6443: connect: connection refused
E0919 19:21:37.547476       6 reflector.go:205] github.com/rancher/rancher/vendor/github.com/rancher/norman/controller/generic_controller.go:139: Failed to list *v1.Role: Get https://165.227.177.83:6443/apis/rbac.authorization.k8s.io/v1/roles?limit=500&resourceVersion=0&timeout=30s: dial tcp 165.227.177.83:6443: connect: connection refused
E0919 19:21:37.548195       6 reflector.go:205] github.com/rancher/rancher/vendor/github.com/rancher/norman/controller/generic_controller.go:139: Failed to list *v1.RoleBinding: Get https://165.227.177.83:6443/apis/rbac.authorization.k8s.io/v1/rolebindings?limit=500&resourceVersion=0&timeout=30s: dial tcp 165.227.177.83:6443: connect: connection refused
E0919 19:21:37.548925       6 reflector.go:205] github.com/rancher/rancher/vendor/github.com/rancher/norman/controller/generic_controller.go:139: Failed to list *v1.ConfigMap: Get https://165.227.177.83:6443/api/v1/configmaps?limit=500&resourceVersion=0&timeout=30s: dial tcp 165.227.177.83:6443: connect: connection refused
E0919 19:21:37.568418       6 reflector.go:205] github.com/rancher/rancher/vendor/github.com/rancher/norman/controller/generic_controller.go:139: Failed to list *v1.Namespace: Get https://165.227.177.83:6443/api/v1/namespaces?limit=500&resourceVersion=0&timeout=30s: dial tcp 165.227.177.83:6443: connect: connection refused
E0919 19:21:37.575573       6 reflector.go:205] github.com/rancher/rancher/vendor/github.com/rancher/norman/controller/generic_controller.go:139: Failed to list *v1beta1.PodSecurityPolicy: Get https://165.227.177.83:6443/apis/extensions/v1beta1/podsecuritypolicies?limit=500&resourceVersion=0&timeout=30s: dial tcp 165.227.177.83:6443: connect: connection refused
E0919 19:21:37.578409       6 reflector.go:205] github.com/rancher/rancher/vendor/github.com/rancher/norman/controller/generic_controller.go:139: Failed to list *v1.Endpoints: Get https://165.227.177.83:6443/api/v1/endpoints?limit=500&resourceVersion=0&timeout=30s: dial tcp 165.227.177.83:6443: connect: connection refused
E0919 19:21:37.579081       6 reflector.go:205] github.com/rancher/rancher/vendor/github.com/rancher/norman/controller/generic_controller.go:139: Failed to list *v1.Service: Get https://165.227.177.83:6443/api/v1/services?limit=500&resourceVersion=0&timeout=30s: dial tcp 165.227.177.83:6443: connect: connection refused
E0919 19:21:37.580060       6 reflector.go:205] github.com/rancher/rancher/vendor/github.com/rancher/norman/controller/generic_controller.go:139: Failed to list *v1beta2.StatefulSet: Get https://165.227.177.83:6443/apis/apps/v1beta2/statefulsets?limit=500&resourceVersion=0&timeout=30s: dial tcp 165.227.177.83:6443: connect: connection refused
E0919 19:21:37.582206       6 reflector.go:205] github.com/rancher/rancher/vendor/github.com/rancher/norman/controller/generic_controller.go:139: Failed to list *v1.ResourceQuota: Get https://165.227.177.83:6443/api/v1/resourcequotas?limit=500&resourceVersion=0&timeout=30s: dial tcp 165.227.177.83:6443: connect: connection refused
E0919 19:21:37.589930       6 reflector.go:205] github.com/rancher/rancher/vendor/github.com/rancher/norman/controller/generic_controller.go:139: Failed to list *v1.ClusterRole: Get https://165.227.177.83:6443/apis/rbac.authorization.k8s.io/v1/clusterroles?limit=500&resourceVersion=0&timeout=30s: dial tcp 165.227.177.83:6443: connect: connection refused
E0919 19:21:37.590784       6 reflector.go:205] github.com/rancher/rancher/vendor/github.com/rancher/norman/controller/generic_controller.go:139: Failed to list *v1beta2.Deployment: Get https://165.227.177.83:6443/apis/apps/v1beta2/deployments?limit=500&resourceVersion=0&timeout=30s: dial tcp 165.227.177.83:6443: connect: connection refused
E0919 19:21:37.593076       6 reflector.go:205] github.com/rancher/rancher/vendor/github.com/rancher/norman/controller/generic_controller.go:139: Failed to list *v1.ReplicationController: Get https://165.227.177.83:6443/api/v1/replicationcontrollers?limit=500&resourceVersion=0&timeout=30s: dial tcp 165.227.177.83:6443: connect: connection refused
E0919 19:21:37.604321       6 reflector.go:205] github.com/rancher/rancher/vendor/github.com/rancher/norman/controller/generic_controller.go:139: Failed to list *v1.Job: Get https://165.227.177.83:6443/apis/batch/v1/jobs?limit=500&resourceVersion=0&timeout=30s: dial tcp 165.227.177.83:6443: connect: connection refused
E0919 19:21:38.479727       6 reflector.go:205] github.com/rancher/rancher/vendor/github.com/rancher/norman/controller/generic_controller.go:139: Failed to list *v1.Secret: Get https://165.227.177.83:6443/api/v1/secrets?limit=500&resourceVersion=0&timeout=30s: dial tcp 165.227.177.83:6443: connect: connection refused
E0919 19:21:38.488159       6 reflector.go:205] github.com/rancher/rancher/vendor/github.com/rancher/norman/controller/generic_controller.go:139: Failed to list *v1.Event: Get https://165.227.177.83:6443/api/v1/events?limit=500&resourceVersion=0&timeout=30s: dial tcp 165.227.177.83:6443: connect: connection refused
E0919 19:21:38.495675       6 reflector.go:205] github.com/rancher/rancher/vendor/github.com/rancher/norman/controller/generic_controller.go:139: Failed to list *v1beta1.CronJob: Get https://165.227.177.83:6443/apis/batch/v1beta1/cronjobs?limit=500&resourceVersion=0&timeout=30s: dial tcp 165.227.177.83:6443:^C
E0919 19:21:39.639068       6 reflector.go:205] github.com/rancher/rancher/vendor/github.com/rancher/norman/controller/generic_controller.go:139: Failed to list *v1.NetworkPolicy: Get https://165.227.177.83:6443/apis/networking.k8s.io/v1/networkpolicies?limit=500&resourceVersion=0&timeout=30s: dial tcp 165.227.177.83:6443: connect: connection refused
E0919 19:21:39.648949       6 reflector.go:205] github.com/rancher/rancher/vendor/github.com/rancher/norman/controller/generic_controller.go:139: Failed to list *v1beta2.DaemonSet: Get https://165.227.177.83:6443/apis/apps/v1beta2/daemonsets?limit=500&resourceVersion=0&timeout=30s: dial tcp 165.227.177.83:6443: connect: connection refused
E0919 19:21:39.649600       6 reflector.go:205] github.com/rancher/rancher/vendor/github.com/rancher/norman/controller/generic_controller.go:139: Failed to list *v1beta2.ReplicaSet: Get https://165.227.177.83:6443/apis/apps/v1beta2/replicasets?limit=500&resourceVersion=0&timeout=30s: dial tcp 165.227.177.83:6443: connect: connection refused
E0919 19:21:39.653293       6 reflector.go:205] github.com/rancher/rancher/vendor/github.com/rancher/norman/controller/generic_controller.go:139: Failed to list *v1beta1.Ingress: Get https://165.227.177.83:6443/apis/extensions/v1beta1/ingresses?limit=500&resourceVersion=0&timeout=30s: dial tcp 165.227.177.83:6443: connect: connection refused
```

**Comment by cjellick** [comment] 2018-09-21 15:49
After other fixes, we can't repro. Moving out of the release.

**Comment by sangeethah** [comment] 2018-09-25 15:50
This issue is also seen when provisioning gets stuck due to - https://github.com/rancher/rancher/issues/15695

**Comment by kinarashah** [comment] 2018-09-25 19:17
@alena1108 Not able to reproduce the case when the above logs are seen after cluster is removed. 

Need to confirm for 2.2 that the same behavior doesn't happen when cluster is unavailable during `provisioning` or `updating` states.

**Comment by alena1108** [comment] 2018-09-26 17:50
Given the impactful  nature of the potential fix - revising on how user clusters' controllers are being registered and deregistered - moving this issue out to 2.2

**Closed** 2019-04-09 00:21 UTC
Labels: kind/bug, status/autoclosed
