### ISSUE TITLE
Consul stack error: Activating (Expected state running but got error: instance is not running : Dependencies readiness error)

### ISSUE THREAD

**Issue by galindro** [rancher/rancher#6963] opened 2016-12-07 11:29 UTC
**Rancher Version:**
1.2

**Docker Version:**
1.12.3

**OS and where are the hosts located? (cloud, bare metal, etc):**
ROS 0.7.1

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
HA rancher + external DB

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle

**Steps to Reproduce:**
Add a Consul Cluster stack from catalog:
![image](https://cloud.githubusercontent.com/assets/4622097/20965998/742f9644-bc5f-11e6-85be-4310c0ff22b4.png)

**Results:** 
Got this error:
Activating (Expected state running but got error: instance is not running : Dependencies readiness error)

![image](https://cloud.githubusercontent.com/assets/4622097/20965984/61faf82e-bc5f-11e6-9ebb-95ed9ce5b693.png)

![image](https://cloud.githubusercontent.com/assets/4622097/20966024/922ce34a-bc5f-11e6-9508-438619db6706.png)

**Expected:**
Stack started without errors

**Comment by galindro** [comment] 2016-12-07 15:54
This problem does NOT occurs with RancherOS 0.7.0, only with RancherOS 0.7.1

**Comment by joshwget** [comment] 2016-12-09 17:50
Have you been able to confirm more than once that this issue appears on v0.7.1 but not v0.7.0? The only difference between the two is a minor kernel change. This leads me to think this is more likely a race condition than an issue with RancherOS version.

**Comment by galindro** [comment] 2016-12-09 19:13
I agree with you @joshwget, but I'm pretty sure that I could solve (or _workarround_) the problem by using rancher v0.7.0 in place of v0.7.1. I've tested twice.

**Comment by joshwget** [comment] 2016-12-09 19:29
Actually, my earlier state was incorrect. The Docker version changed from v1.12.1 to v1.12.3 between those releases. It's possible the issue is related to that. Would you mind testing the two different Docker versions on a different operating system?

**Comment by galindro** [comment] 2016-12-09 23:07
@joshwget I could confirm that this issue is related to Docker v1.12.3. I've tested on Ubuntu 16.04.

Sincerelly, Rancher v1.2 isn't a stable version in my point of view.... It solves some problems from 1.1.4 but creates new ones... That are many broken things. I was forced to use DockerCloud until it is really stable

**Comment by aemneina** [comment] 2017-05-12 18:20
Closing, please create a new ticket if this is reproducible on a newer version of rancher (1.5.9+)

**Closed by aemneina** 2017-05-12 18:20 UTC
