### ISSUE TITLE
Error seen in logs when cluster gets deleted

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#12497] opened 2018-04-04 16:52 UTC
Rancher versions: Build from master

Steps to reproduce the problem:
Created a GKE cluster.
Added 1 workload.
Deleted this cluster.

Following error seen in logs (once) when cluster gets deleted.

```
E0404 16:48:28.396016       1 tokens_controller.go:259] error synchronizing serviceaccount cluster-5bfsb/default: secrets "default-token-ttrfr" is forbidden: unable to create new content in namespace cluster-5bfsb because it is being terminated.
E0404 16:48:28.412225       1 tokens_controller.go:259] error synchronizing serviceaccount cluster-5bfsb/default: secrets "default-token-rdp4s" is forbidden: unable to create new content in namespace cluster-5bfsb because it is being terminated.
E0404 16:48:28.428057       1 tokens_controller.go:259] error synchronizing serviceaccount cluster-5bfsb/default: secrets "default-token-9nmmq" is forbidden: unable to create new content in namespace cluster-5bfsb because it is being terminated.
E0404 16:48:28.455145       1 tokens_controller.go:259] error synchronizing serviceaccount cluster-5bfsb/default: secrets "default-token-z6rl5" is forbidden: unable to create new content in namespace cluster-5bfsb because it is being terminated.
E0404 16:48:28.515519       1 tokens_controller.go:259] error synchronizing serviceaccount cluster-5bfsb/default: secrets "default-token-srntf" is forbidden: unable to create new content in namespace cluster-5bfsb because it is being terminated.



E0404 16:48:33.661080       1 tokens_controller.go:259] error synchronizing serviceaccount project-qjrrr/default: secrets "default-token-9nkzc" is forbidden: unable to create new content in namespace project-qjrrr because it is being terminated.
E0404 16:48:33.680517       1 tokens_controller.go:259] error synchronizing serviceaccount project-qjrrr/default: secrets "default-token-fbnfc" is forbidden: unable to create new content in namespace project-qjrrr because it is being terminated.
E0404 16:48:33.698359       1 tokens_controller.go:259] error synchronizing serviceaccount project-qjrrr/default: secrets "default-token-6f8f4" is forbidden: unable to create new content in namespace project-qjrrr because it is being terminated.
E0404 16:48:33.724345       1 tokens_controller.go:259] error synchronizing serviceaccount project-qjrrr/default: secrets "default-token-qksk5" is forbidden: unable to create new content in namespace project-qjrrr because it is being terminated.
```

**Comment by kinarashah** [comment] 2018-04-06 19:58
@sangeethah I can't reproduce this in the latest version, could you confirm?

**Comment by sangeethah** [comment] 2018-04-13 17:31
Tested with latest build from master:
I still see these error messages when deleting a cluster.

```E0413 17:23:12.888155       1 tokens_controller.go:259] error synchronizing serviceaccount project-pnr4d/default: secrets "default-token-fvfjh" is forbidden: unable to create new content in namespace project-pnr4d because it is being terminated.```

**Comment by kinarashah** [comment] 2018-04-13 17:46
oh! I'll add a check nonetheless

**Comment by deniseschannon** [comment] 2018-08-15 22:07
@sangeethah can you re-test? @alena1108 has put in some fixes around this area that might have fixed these errors.

**Comment by cjellick** [comment] 2018-08-22 21:38
make to warning?

**Comment by sangeethah** [comment] 2018-08-24 22:25
Tested with latest build from master:

The error messages mentioned in the issue are still when deleting a GKE cluster.
```
2018/08/24 22:21:23 [INFO] Shutting down ClusterRoleTemplateBindingController controller
2018/08/24 22:21:23 [INFO] Shutting down ProjectRoleTemplateBindingController controller
2018/08/24 22:21:23 [INFO] Shutting down NodeController controller
2018/08/24 22:21:23 [INFO] Shutting down ClusterController controller
2018/08/24 22:21:23 [INFO] Shutting down NotifierController controller
2018/08/24 22:21:23 [INFO] Shutting down NotifierController controller
2018/08/24 22:21:23 [INFO] Shutting down ProjectAlertController controller
2018/08/24 22:21:23 [INFO] Shutting down ClusterAlertController controller
2018/08/24 22:21:23 [INFO] Shutting down NetworkPolicyController controller
2018/08/24 22:21:23 [INFO] Deleting cluster [c-8z5vl]
2018/08/24 22:21:23 [INFO] Deleted cluster [c-8z5vl]
2018/08/24 22:21:23 [INFO] [mgmt-cluster-rbac-remove] Deleting namespace c-8z5vl
2018/08/24 22:21:23 [ERROR] ClusterController c-8z5vl [cluster-scoped-gc] failed with : failed to remove finalizer on :c-8z5vl
2018/08/24 22:21:23 [ERROR] ClusterController c-8z5vl [cluster-scoped-gc] failed with : failed to remove finalizer on :c-8z5vl
2018/08/24 22:21:28 [INFO] [mgmt-project-rbac-remove] Deleting namespace p-k2gwq
2018/08/24 22:21:28 [INFO] [mgmt-project-rbac-remove] Deleting namespace p-mgmhr
2018/08/24 22:21:29 [INFO] [mgmt-auth-crtb-controller] Deleting roleBinding clusterrolebinding-jbjp6
E0824 22:21:29.083075       8 tokens_controller.go:261] error synchronizing serviceaccount c-8z5vl/default: secrets "default-token-fv8h2" is forbidden: unable to create new content in namespace c-8z5vl because it is being terminated
2018/08/24 22:21:29 [INFO] [mgmt-auth-crtb-controller] Deleting roleBinding clusterrolebinding-h4d6f
E0824 22:21:29.098442       8 tokens_controller.go:261] error synchronizing serviceaccount c-8z5vl/default: secrets "default-token-2wd5l" is forbidden: unable to create new content in namespace c-8z5vl because it is being terminated
E0824 22:21:29.114182       8 tokens_controller.go:261] error synchronizing serviceaccount c-8z5vl/default: secrets "default-token-fm78t" is forbidden: unable to create new content in namespace c-8z5vl because it is being terminated
E0824 22:21:29.141736       8 tokens_controller.go:261] error synchronizing serviceaccount c-8z5vl/default: secrets "default-token-px4zx" is forbidden: unable to create new content in namespace c-8z5vl because it is being terminated
E0824 22:21:29.209560       8 tokens_controller.go:261] error synchronizing serviceaccount c-8z5vl/default: secrets "default-token-jbxqb" is forbidden: unable to create new content in namespace c-8z5vl because it is being terminated
2018/08/24 22:21:34 [INFO] [mgmt-auth-prtb-controller] Deleting roleBinding clusterrolebinding-jd2rh
2018/08/24 22:21:34 [INFO] [mgmt-auth-prtb-controller] Updating owner label for roleBinding clusterrolebinding-bd48b
2018/08/24 22:21:34 [INFO] [mgmt-auth-prtb-controller] Deleting roleBinding clusterrolebinding-bd48b
E0824 22:23:11.907347       8 watcher.go:208] watch chan error: etcdserver: mvcc: required revision has been compacted
```

**Comment by sangeethah** [comment] 2018-09-07 21:26
This issue is still reproducible with latest build from master.
Reopening issue.

**Comment by kinarashah** [comment] 2018-09-12 17:09
@alena1108 @sangeethah It looks like that it's not us who call this sync for serviceaccounts. It is coming from Kubernetes, where on every serviceaccount sync, it ensures that the token exists for it, and if it doesn't (in this case, it might have been deleted on namespace delete) - it tries to create a new secret. And this fails because no new content is allowed to be created when namespace is in terminating phase.  For reference, https://github.com/kubernetes/kubernetes/blob/master/pkg/controller/serviceaccount/tokens_controller.go#L259 is the function and 261 is where it just logs the error. 

I think currently we just log whatever Kubernetes logs, so we might need to have a better filtering for these kind of messages since they add no value to user at this point. 

This is similar to https://github.com/rancher/rancher/issues/12266 where it's the project's namespace being deleted.

**Comment by alena1108** [comment] 2018-09-12 17:19
Moving out as the issue is intermittent and recoverable from. Need more debugging and the fix most likely will be in the framework as the error is thrown by k8s, and we just bubble it up.

**Closed** 2019-04-08 22:56 UTC
Labels: area/cluster, area/gke, kind/enhancement, priority/0, status/autoclosed, team/ca
