### ISSUE TITLE
Unknown exception running process [instance.updateunhealthy]

### ISSUE THREAD

**Issue by jmreicha** [rancher/rancher#4257] opened 2016-03-31 20:01 UTC
Rancher Version: 1.0.0

Docker Version: 1.10.1

OS: CoreOS 970.1.0

Steps to Reproduce: Upgrade from v0.63.1 to v1.0.0, fixed another issue first [here](https://github.com/rancher/rancher/issues/4202)

Results:

Beginning of the traceback looks like this:

```
2016-03-31 02:26:19,588 ERROR [:] [] [] [] [ServiceReplay-2] [i.c.p.e.e.i.ProcessEventListenerImpl] Unknown exception running process [instance.updateunhealthy:773852] on [76781] org.jooq.exception.DataAccessException: SQL [select `config_item_status`.`id`, `config_item_status`.`name`, `config_item_status`.`requested_version`, `config_item_status`.`applied_version`, `config_item_status`.`source_version`, `config_item_status`.`requested_updated`, `config_item_status`.`applied_updated`, `config_item_status`.`agent_id`, `config_item_status`.`account_id`, `config_item_status`.`service_id`, `config_item_status`.`resource_id`, `config_item_status`.`resource_type`, `config_item_status`.`environment_id` from `config_item_status` where (`config_item_status`.`name` in (?) and `config_item_status`.`resource_type` = ? and `config_item_status`.`resource_id` = ?)]; Unknown column 'config_item_status.environment_id' in 'field list'
    at org.jooq.impl.Utils.translate(Utils.java:1287) ~[jooq-3.3.0.jar:na]
    at org.jooq.impl.DefaultExecuteContext.sqlException(DefaultExecuteContext.java:495) ~[jooq-3.3.0.jar:na]
    at org.jooq.impl.AbstractQuery.execute(AbstractQuery.java:326) ~[jooq-3.3.0.jar:na]
```

And Here is the error I am seeing over and over in the process logs:

![image](https://cloud.githubusercontent.com/assets/1039098/14187258/fa52cef6-f736-11e5-94ea-e209995abfac.png)

![image](https://cloud.githubusercontent.com/assets/1039098/14187228/df9f2654-f736-11e5-8346-65f3aba069f7.png)

**Comment by deniseschannon** [comment] 2016-03-31 20:02
@jmreicha I sent you an email for a request for a mysql dump.

**Comment by jmreicha** [comment] 2016-03-31 20:08
@deniseschannon Got it.  Give me a little bit here to figure out how to get a dump.

**Comment by alena1108** [comment] 2016-03-31 20:55
@jmreicha the fact that following fields were dropped (as per https://github.com/rancher/rancher/issues/4202), caused this follow up issue:

```
ALTER TABLE config_item_status DROP FOREIGN KEY fk_config_item__environment_id;
ALTER TABLE `config_item_status` DROP `environment_id`;
```

As a part of health check state migration, we rely on environment_id to be present in config_item_status table.

Not sure what the original issue was caused by that it required dropping the fields; but to fix it at this point, we would have to re-add the fields back. I would suggest the following steps:

1) Take the db dump just in case (you already did it)
2) delete from DATABASECHANGELOG where FILENAME='db/core-080.xml' // file adding environment_id
3) restart rancher. core-080.xml should be reapplied, and data base migration for health check should be picked up from then.

Let me know if you hit any problems doing that, and I can assist you (you can email me at alena at rancher.com)

**Comment by jmreicha** [comment] 2016-03-31 21:06
@alena1108 Yeah I did get the database dump.  I ran the command from step 2) `delete from DATABASECHANGELOG where FILENAME='db/core-080.xml'` and restarted and am now getting a new error, [posted here](https://gist.github.com/jmreicha/60e583475e101257710b5f72e4cdf9f2).

**Comment by alena1108** [comment] 2016-03-31 21:57
@jmreicha basically the same error you've hit as in https://github.com/rancher/rancher/issues/4202. Let me run it locally to see if I can reproduce it. Meanwhile could you email me to alena at rancher.com; if I can't reproduce it, we can setup a debugging session with you

**Comment by alena1108** [comment] 2016-03-31 22:15
@jmreicha couldn't reproduce the problem using your DB dump. Steps taken:

1) applied the db dump
2) removed entries for core-080.xml from databasechangelog table
3) restarted the server

environment_id was added to config_item_status as part of core-080.xml reapply, and the server was started successfully.

Not really sure what "Can't create table 'cattle.#sql-17_7' (errno: -1)" indicates. Could you try to:

* rollback to your db dump (the one that you've sent initially where core-080.xml was present in databasechangelog)
* execute this statement manually (this is exact statement core-080.xml executes, and fails):

```
 ALTER TABLE cattle.config_item_status ADD environment_id BIGINT NUL
```

and see if you get any error.

**Comment by jmreicha** [comment] 2016-03-31 22:50
@alena1108 Sent you a link to the DB dump.

I think we're good.  I just tried your command from above on the DB I sent you.

```mysql> ALTER TABLE cattle.config_item_status ADD environment_id BIGINT NULL;````

Then restarted Rancher server and everything seems good, no errors in the logs yet.

**Comment by alena1108** [comment] 2016-03-31 22:55
@jmreicha good that your setup is back to normal. Could you try creating a new service or starting/stopping the existing one? Just to make sure that the health state update that is done via config item, succeeds (most likely it will)

Still would like to understand what went wrong with the original upgrade, lets keep the https://github.com/rancher/rancher/issues/4202 open. This bug can be closed as its really caused by environment_id field being dropped.

**Closed** 2016-03-31 22:58 UTC

**Comment by jmreicha** [comment] 2016-03-31 23:01
@alena1108 Created a new service and everything seems okay.
