### ISSUE TITLE
"unable to create impersonator account: error getting service account token: serviceaccounts \"cattle-impersonation-system/cattle-impersonation-user-dxx4g\" not found - Error seen for Monitoring and Istio v1 charts and when using downloaded kubeconfig

### ISSUE THREAD

**Issue by slickwarren** [rancher/rancher#34187] opened 2021-08-12 00:42 UTC
**Rancher Server Setup**
- Rancher version: 2.5.9 -> 2.6.0-rc2 upgrade
- Installation option (Docker install/Helm Chart):
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): helm install

**Information about the Cluster**
- Kubernetes version: 
- Cluster Type (Local/Downstream): downsteram
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider): 

**Describe the bug**

when a user is logged in as admin, all monitoring v1 (v0.2.2) links are not working. 

**To Reproduce**
 
* deploy rancher server v2.5.9
* on a downstream cluster, install monitoring (latest version, v0.2.2)
  * grant a standard user permissions to this cluster i.e. `cluster owner` before the upgrade (see additional context)
  * verify that prometheus/grafana links are working
* upgrade rancher to v2.6.0-rc2

**Result**
`"status":500,"statusText":"","data":"unable to create impersonator account: error getting service account token: serviceaccounts \"cattle-impersonation-system/cattle-impersonation-user-dxx4g\" not found` from both prometheus and grafana. 

**Expected Result**

monitoring v1 should continue to work after an upgrade

**Screenshots**

**Additional context**

* as a standard user that was created + added to the cluster before the upgrade, I am able to access monitoring v1 apps (prom, grafana) after the upgrade.

**Comment by anupama2501** [comment] 2021-08-12 00:49
I see the same issue while accessing istio `jaeger traces` and `kiali` when logged in as admin.

- Created a downstream cluster on rancher v2.5.9 as a standard user
- installed istio v1.5.901 from cluster --> tools
- jaeger traces and kiali  work fine
- Upgrade rancher server to v2.6.0-rc2
- Access the kiali and jaeger traces as standard user works fine.
- Access the kiali and jaeger traces as an admin **errors** out:
```
unable to create impersonator account: error getting service account token: serviceaccounts "cattle-impersonation-system/cattle-impersonation-user-dxx4g" not found
```

**Comment by cmurphy** [comment] 2021-08-13 04:28
@slickwarren @anupama2501 I have not been able to reproduce this, following the upgrade scenarios for both monitoring and istio. Is there any other information about your environments that might be important that you could share? Is this 100% reproducible, or does it only happen sometimes? Is the local cluster k3s, rke, rke2, what version? Is the downstream cluster imported or created, what kind is it?

**Comment by snasovich** [comment] 2021-08-13 14:40
Moving to test as we need more info from QA here.

**Comment by sowmyav27** [comment] 2021-08-13 14:45
Setup provided to @cmurphy in an offline conversation.

**Comment by cmurphy** [comment] 2021-08-13 21:41
I was never able to reproduce this myself, but we've merged a change that will hopefully address the issue. If it doesn't, we also added trace logging so that if the problem is seen again, we can get more information about it.

**Comment by slickwarren** [comment] 2021-08-16 20:31
on v2.5.9 using HA setup for rancher:
* provision a downstream cluster (k8s 1.20.9, 3 wk, 1 cp, 1 etcd node) 
* install monitoring v2 (14.5.100) as a standard user on the cluster
* follow the P0 use case for monitoring v2 using `alerting-drivers` as the notifier
* upgrade the cluster to v2.6-head (f811996)
* login as admin, and try to access prometheus/grafana

**Comment by sowmyav27** [comment] 2021-08-17 14:10
**On an upgrade from 2.5.9 to v2.6-head (f811996) HA setup**

- In the cluster where the issue is seen for monitoring an istio, set ` kubeconfig-generate-token` = False
- Download kubeconfig and access cluster using this kubeconfig 
- User will be propted to login
- After which user sees error: `Error from server (InternalError): an error on the server ("unable to create impersonator account: error setting up impersonation for user user-h7dqq: failed to get secret for service account: cattle-impersonation-system/cattle-impersonation-user-h7dqq, error: timed out waiting for the condition") has prevented the request from succeeding`

**Comment by davidnuzik** [comment] 2021-08-24 16:48
**Understanding the issue and PR fix:**
I reviewed the PR - the commit message explains the change that resolved this issue:
> When the cluster context is set for the proxy server at initialization,
it doesn't always refresh when a new request comes in. This can cause
the cache to become stale and the proxy server handler can fail to
fetch service accounts from it even though they exist in the downstream
cluster. This change pushes the cluster context getter down to the
request handling layer instead of the server creation layer so that it
is refreshed on every request.

I also synced with Colleen to ensure I understand the change. Paraphrasing from what she mentioned to me:
Basically, the problem we were seeing here was that if you created a cluster as a standard user then upgraded Rancher and then tried to access the cluster as the admin user, the mechanism for user impersonation would correctly dynamically create an impersonation service account for the admin user in the cluster, but the cached list of service accounts was not being updated. Basically this causes a stale cache. The object that holds the cache was only being created once at initialization and was NOT getting refreshed when requests were made later, so the code was modified so that this should refresh correctly upon each request.

When testing, I can deploy system charts like Istio and monitoring as mentioned prior. This is one way to test that the issue is fixed. We'll also check that we can log in with kubectl/kubeconfig as this is another way to test effectively the same thing.
 
**My checks PASSED**
 
**Reproduction Steps:**

Not required. The issue has been reproduced several times by QA - each repro being 100% successful each time before the change (issue was not intermittent).
 
**Validation Environment:**

Rancher version: 2.5.9 to v2.6-head `b43e4d955` 8/24/21
Rancher cluster type: HA, RKE v1.2.11 (this version is recommended for 2.5.9)
Helm version: v3.3.4
Cert Manager version: v1.0.4
Certs: Self-signed
Install command: (Installed via QA Jenkins ha-deploy job)
 
Downstream cluster type: rke1 (rancher-provisioned with DO node driver)
Downstream K8s version: v1.20.9
Downstream Notes: Created one cluster with admin user and one with standard user. The standard user created cluster should be accessible by the admin user post upgrade now when testing.
 
**Validation steps:**

_For each downstream cluster created, create with 1 node with the etcd role, 1 node with the control plane role, 3 nodes with the worker role. These downstream clusters I created were with the DO node driver, 2vcpu 4gb for each node._
1. Install Rancher HA 2.5.9. Create a standard user. Create 1 cluster as the admin user. Create 1 cluster as the standard user.
The admin cluster should have the standard user added as a cluster owner after cluster creation.
2. As the standard user, deploy monitoring and istio to the two clusters. Monitoring 0.2.2. Istio 1.5.901.
Ensure the standard user can access monitoring grafana and istio links (kiali, jaeger, grafana, prometheus) (to ensure this works before upgrade).
3. Upgrade HA Rancher to v2.6-head `b43e4d955` I did this in QA Jenkins with the ha-upgrade job
4. Log in as the ADMIN user, ensure the user is able to view details for both clusters. I see monitoring is working. Ensure the user is able to access Monitoring grafana. Ensure the user is able to access Istio links (kiali, jaeger). This works without any issues.
NOTE: There is an error attempting to access Jaeger UI, but this appears to be unrelated to this specific issue.
![image](https://user-images.githubusercontent.com/45179589/130656134-40091986-c1d5-4d1a-a757-e5a173125b41.png)
A bug will be filed for this separate issue. (To be linked here once issue is created)

5. Go to Global Settings, set kubeconfig-generate-token = false
6. Attempt to access kubectl client in the browser for both clusters. This works now. I am able to get nodes, list pods, etc.
 
**Additional Info:**

**Comment by davidnuzik** [comment] 2021-08-24 19:32
Note: Needs a check on one more step again - for the kubectl test we need to actually download the kubeconfig and try to utilize it remotely, NOT within the dashboard UI shell.

**Closed** 2021-08-24 20:53 UTC
Labels: kind/bug-qa, [zube]: QA Working, status/release-blocker

**Comment by andrew-landsverk-win** [comment] 2021-09-07 18:39
Can we expect this fix in 2.6.1? I am getting the same errors in my 2.6.0 cluster.

**Comment by snasovich** [comment] 2021-09-07 18:59
@andrew-landsverk-win , this should be fixed in 2.6.0 as the issue got validated and closed, see this comment: https://github.com/rancher/rancher/issues/34187#issuecomment-904809285.
If the issue is reproducible for you, could you please share logs and describe your setup?

**Comment by andrew-landsverk-win** [comment] 2021-09-07 19:06
I get this error "sometimes" when doing a helm 3.6.2 deploy of an app after using the rancher-cli2 to login to my cluster.  It doesn't affect my 2.5.x cluster, only my 2.6.0 cluster. Which container do you want logs from? :)

**Comment by snasovich** [comment] 2021-09-07 19:19
@andrew-landsverk-win , somehow I've read it as if you have seen these errors in some logs which is not the case.
Do I understand it right that you're installing a custom application using `helm install` and this error is returned directly by `helm install`? If that's the case, full (verbose) output of it could be helpful to understand if it's this exact issue or something else.

**Comment by andrew-landsverk-win** [comment] 2021-09-07 19:41
Yes, helm fails randomly with the following errors, sometimes others I think? To be complete, we run helm from within a docker container from a different server.

```
error: unable to recognize "/tmp/kubectl_replace_486731274/resource.stdin": an error on the server ("unable to create impersonator account: error setting up impersonation for user u-8j72f: Operation cannot be fulfilled on clusterroles.rbac.authorization.k8s.io \"cattle-impersonation-u-8j72f\": the object has been modified; please apply your changes to the latest version and try again") has prevented the request from succeeding
```

```
Error: uninstall: Release not loaded: katana-api-dev: query: failed to query with labels: an error on the server ("unable to create impersonator account: error setting up impersonation for user u-8j72f: Operation cannot be fulfilled on clusterroles.rbac.authorization.k8s.io \"cattle-impersonation-u-8j72f\": the object has been modified; please apply your changes to the latest version and try again") has prevented the request from succeeding (get secrets)
```

**Comment by snasovich** [comment] 2021-09-08 00:07
@andrew-landsverk-win , thank you additional details. At a glance this seems to be a separate issue, albeit with a very similar error message. I've created a separate issue https://github.com/rancher/rancher/issues/34671 that we will work on. I would appreciate it if you could add any extra information on your environment or reproduction steps (e.g. helm charts being installed) there.
