### ISSUE TITLE
Load Balancer loses Host IP-Address binding on upgrade

### ISSUE THREAD

**Issue by proligde** [rancher/rancher#7407] opened 2017-01-13 15:03 UTC
**Rancher Versions:**
Server: 1.3.0
healthcheck: 0.2.0
ipsec: 0.0.2
network-services: 0.0.8
scheduler: 0.2.0
kubernetes (if applicable):

**Docker Version:**
1.11.2 (on the node)

**OS and where are the hosts located? (cloud, bare metal, etc):**
Ubuntu 14.04 LTS, Bare Metal (node)

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
Single Node Rancher Server, external DB

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle

**Steps to Reproduce:**
- Create a second IP adress for a single network interface using an alias. For example:
  - eth0 is 192.168.0.1
  - eth0:1 is 192.168.0.2
- Create a load balancer (I used current lb-service-haproxy:v0.4.9 coming with rancher 1.3.0)
- Create a service rule linking to a service
- Click on "Show host IP address options" below the list
- Enter one of the IPs afore mentioned to bind haproxy to, e.g. 192.168.0.2
- Create loadbalancer
- After the loadbalancer is running everything is working as expected
- Now Edit/Upgrade loadbalancer and do something without touching the IP address options mentioned before
- Click on "Edit" to finish your changes

**Results:** 
- The IP bindings are dropped
- The IP bindings are also not shown when opening them by blickin ong "IP adress options"
- This results in haproxy hijacking 192.198.0.1's ports as well _without_ any visible conflict even if they are used on the host system outside rancher's managed network which leads to most mysterious effects.

**Expected:**
- The IP bindings are kept as they have been configured

**Comment by tfiduccia** [comment] 2017-01-13 17:51
@proligde This is a Duplicate of #7288.  The host-ip is being saved on create thou.  Until it's fixed when you edit/upgrade you will have to re-enter the host-ip.  Will try to get dev to fix for next major release.

**Closed by tfiduccia** 2017-01-13 17:51 UTC
