### ISSUE TITLE
Imported Ingress configurations don't let you select anything but port 42 after changing a target container

### ISSUE THREAD

**Issue by macdja38** [rancher/rancher#15809] opened 2018-09-25 19:47 UTC
**Rancher versions:**
rancher/server or rancher/rancher: v2.0.8
rancher/agent or rancher/rancher-agent: rancherOS

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
RancherOS v1.4.0
4.14.32-rancher2
docker 18.3.1
Kubelet Version v1.11.1
Kube Proxy Version v1.11.1

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
DO

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
rancher

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**
none

**Steps to Reproduce:**
1. Setup an ingress in one namespace
2. Download yaml
3. Create ingress from yaml in another namespace
4. Change to a different target (in my case one with no port bindings setup on the container)

**Results:**
The target port is locked to 42

**Comment by loganhz** [comment] 2018-10-07 08:10
Hi @macdja38 

You can remove it by clicking the `minus`. Then you can add a new workload/service as a target 

![image](https://user-images.githubusercontent.com/21168270/46579809-134d6f80-ca4b-11e8-8219-bc7d33aeb411.png)

Ingress can only connect to the services/workloads in the same namespace with it.
You are importing the ingress to a new namespace but the target service doesn't exist in the new namespace.

**Comment by macdja38** [comment] 2018-10-08 03:56
But I'm selecting a target service that does exist in the new namespace, that's when the port changes to 42 and won't change to anything else... also their should probably be some kind of error that makes what's happening clear, instead of locking the port number to a book reference.

**Comment by loganhz** [comment] 2018-10-08 04:08
If your target is a service, you can only select the ports in the service.  

This is by design. The bad thing is that you can not edit the ports of a service in Rancher UI. You have to do it via YAML.

The service is automatically created by Rancher.  and the port 42 is automatically added by Rancher for SkyDns compatibility.

I think you can try to

- Edit the service YAML to add ports
- Select a workload as the target, then you can input any port
- Add a workload in Rancher UI with ports mapping type as Cluster IP. Then you can select your own ports in ingress for a service target

![image](https://user-images.githubusercontent.com/21168270/46592173-c91fc900-caf2-11e8-9704-1007f1cd7554.png)
![image](https://user-images.githubusercontent.com/21168270/46592182-d6d54e80-caf2-11e8-92ac-3236594ba7d1.png)

**Comment by nathanweeks** [comment] 2018-10-25 20:43
@loganhz : not sure if this is a new bug report, but when adding an Ingress where the target service is a "Hostname" or "External IP", there is no dropdown menu containing the service port. Rather, there is a textbox (Rancher v2.1.1).

**Comment by macdja38** [comment] 2018-10-25 23:13
I assume rancher can't find out what port your external service is, that definitely sounds like a different issue @nathanweeks

**Comment by loganhz** [comment] 2018-10-26 06:01
@nathanweeks It will only show the dropdown for the service which created by rancher for workloads

https://github.com/rancher/ui/blob/master/lib/shared/addon/components/form-ingress-backends/template.hbs#L68
https://github.com/rancher/ui/blob/master/app/models/dnsrecord.js#L76


If you add a hostname in Rancher UI, It looks like you have to edit yaml of the hostname service and add the port info such as 80 or 443.  

Then you can select the hostname service and input the port you added in the service in ingress page.

![image](https://user-images.githubusercontent.com/21168270/47547214-38851d80-d927-11e8-895a-f1a64c9fa4a5.png)
![image](https://user-images.githubusercontent.com/21168270/47547297-797d3200-d927-11e8-836e-2ce749fdaa58.png)

**Comment by nathanweeks** [comment] 2018-10-26 13:19
Thanks @loganhz . It would be helpful if the Rancher UI allowed port / targetPort to be specified for hostname / external IP services, to make the process of creating Ingresses that target those kinds of services more intuitive (not that editing YAML for those services to change the hard-coded port/targetPort of 42 is difficult).

**Comment by proligde** [comment] 2019-01-02 15:50
Editing the ports in the external service yaml solved my problem but I'd add a bit of information here that got me confused (Using Rancher 2.1.4): When Creating an Ingress and pointing it to an Service (external IP) I can enter a Port. But this port is ignored when saving: It's not being reflected in the yaml but it does in fact show correctly in the UI. So my UI showed Port 80 (correctly) but the yaml was still on Port42.

**Comment by loganhz** [comment] 2019-01-25 02:02
Fixed in https://github.com/rancher/ui/pull/2546 
You can specify ports in UI
It will be released in 2.2

**Closed by loganhz** 2019-01-25 02:02 UTC
Labels: kind/bug, status/need-follow-up, status/resolved, team/cn, version/2.0
