### ISSUE TITLE
docker restart  results in docker not being able to start.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#10595] opened 2017-12-15 20:06 UTC
Rancher server - v1.6.13-rc3

Had a set up with 4 hosts and few health check containers running on them.
On one of the host ,  restart docker.
Docker fails to start.

journalctl -xe:
```
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- 
-- Unit docker.service has finished shutting down.
Dec 15 19:53:50 santestnew1 systemd[1]: Closed Docker Socket for the API.
-- Subject: Unit docker.socket has finished shutting down
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- 
-- Unit docker.socket has finished shutting down.
Dec 15 19:53:50 santestnew1 systemd[1]: Stopping Docker Socket for the API.
lines 2439-2465/2492 99%
Dec 15 19:53:49 santestnew1 dockerd[5077]: time="2017-12-15T19:53:49.590309475Z" level=info msg="Container d60403feb674322f848ca28e64f5fb417d58c5548a2a225f77015665657c1b0c failed to exit within 10 seconds of signal 15 - using the force"
Dec 15 19:53:49 santestnew1 dockerd[5077]: time="2017-12-15T19:53:49.591155877Z" level=info msg="Container 8b20aabf1f04021480a5f8f3cdbbc82fb91adaeafe161f2ad590151bb51e067f failed to exit within 10 seconds of signal 15 - using the force"
Dec 15 19:53:49 santestnew1 dockerd[5077]: time="2017-12-15T19:53:49.773740140Z" level=warning msg="libcontainerd: container 8b20aabf1f04021480a5f8f3cdbbc82fb91adaeafe161f2ad590151bb51e067f restart canceled"
Dec 15 19:53:49 santestnew1 dockerd[5077]: time="2017-12-15T19:53:49.920883807Z" level=warning msg="Failed detaching sandbox 0c074c43343fe655af691bafc49168e56dec33e06e217dc7341fd13fdac471e4 from endpoint b651bfb9e23e2a6dd9de11ab489972a81e2dcaa1ff8fabbf825dcad9823402ec: failed to update store for object type *libnetwork.endpoint: open : no such file or directory\n"
Dec 15 19:53:49 santestnew1 dockerd[5077]: time="2017-12-15T19:53:49.926404168Z" level=warning msg="Failed deleting endpoint b651bfb9e23e2a6dd9de11ab489972a81e2dcaa1ff8fabbf825dcad9823402ec: endpoint with name r-network-services-network-manager-4-9d701cf1 id b651bfb9e23e2a6dd9de11ab489972a81e2dcaa1ff8fabbf825dcad9823402ec has active containers\n"
Dec 15 19:53:49 santestnew1 dockerd[5077]: time="2017-12-15T19:53:49.926851071Z" level=warning msg="Failed to delete sandbox 0c074c43343fe655af691bafc49168e56dec33e06e217dc7341fd13fdac471e4 from store: open : no such file or directory"
Dec 15 19:53:49 santestnew1 dockerd[5077]: time="2017-12-15T19:53:49.985604938Z" level=error msg="containerd: start container" error="oci runtime error: container_linux.go:247: starting container process caused \"process_linux.go:334: running prestart hook 0 caused \\\"error running hook: exit status 1, stdout: , stderr: time=\\\\\\\"2017-12-15T19:53:49Z\\\\\\\" level=fatal msg=\\\\\\\"dial unix /run/docker/libnetwork/196183ff4a50e4c858e6b0f7b4127e01bf1b8232648005d3b200bf23e250bd02.sock: connect: no such file or directory\\\\\\\" \\\\n\\\"\"\n" id=cb7eaa686480df5cbb05dfc293a9ca60e1393b10b1bea1051952447bfe4e0228
Dec 15 19:53:50 santestnew1 dockerd[5077]: time="2017-12-15T19:53:50.022095174Z" level=error msg="Create container failed with error: invalid header field value \"oci runtime error: container_linux.go:247: starting container process caused \\\"process_linux.go:334: running prestart hook 0 caused \\\\\\\"error running hook: exit status 1, stdout: , stderr: time=\\\\\\\\\\\\\\\"2017-12-15T19:53:49Z\\\\\\\\\\\\\\\" level=fatal msg=\\\\\\\\\\\\\\\"dial unix /run/docker/libnetwork/196183ff4a50e4c858e6b0f7b4127e01bf1b8232648005d3b200bf23e250bd02.sock: connect: no such file or directory\\\\\\\\\\\\\\\" \\\\\\\\n\\\\\\\"\\\"\\n\""
Dec 15 19:53:50 santestnew1 dockerd[5077]: time="2017-12-15T19:53:50.065428346Z" level=warning msg="Failed detaching sandbox 01266419b094fa38e0660f2016b7b11b2085e6f414ca11d8439cac3963acd383 from endpoint ca70a091262a0f6975e964a6d8242877eda4edf0c3e527a591d046d360143609: failed to update store for object type *libnetwork.endpoint: open : no such file or directory\n"
Dec 15 19:53:50 santestnew1 dockerd[5077]: time="2017-12-15T19:53:50.066198214Z" level=warning msg="Failed deleting endpoint ca70a091262a0f6975e964a6d8242877eda4edf0c3e527a591d046d360143609: endpoint with name r-test1-healthglobal-4-00384e54 id ca70a091262a0f6975e964a6d8242877eda4edf0c3e527a591d046d360143609 has active containers\n"
Dec 15 19:53:50 santestnew1 dockerd[5077]: time="2017-12-15T19:53:50.066598546Z" level=warning msg="Failed to delete sandbox 01266419b094fa38e0660f2016b7b11b2085e6f414ca11d8439cac3963acd383 from store: open : no such file or directory"
Dec 15 19:53:50 santestnew1 dockerd[5077]: time="2017-12-15T19:53:50.087372996Z" level=error msg="Handler for POST /v1.22/containers/cb7eaa686480df5cbb05dfc293a9ca60e1393b10b1bea1051952447bfe4e0228/start returned error: invalid header field value \"oci runtime error: container_linux.go:247: starting container process caused \\\"process_linux.go:334: running prestart hook 0 caused \\\\\\\"error running hook: exit status 1, stdout: , stderr: time=\\\\\\\\\\\\\\\"2017-12-15T19:53:49Z\\\\\\\\\\\\\\\" level=fatal msg=\\\\\\\\\\\\\\\"dial unix /run/docker/libnetwork/196183ff4a50e4c858e6b0f7b4127e01bf1b8232648005d3b200bf23e250bd02.sock: connect: no such file or directory\\\\\\\\\\\\\\\" \\\\\\\\n\\\\\\\"\\\"\\n\""
Dec 15 19:53:50 santestnew1 dockerd[5077]: time="2017-12-15T19:53:50.090021255Z" level=error msg="Error during layer Store.Cleanup(): lstat /var/lib/docker/aufs/mnt/0983fc47e6439c3848d68b0904972fb15d1e38e4e55fa11703a11ae7699f1618/usr/share/lintian/overrides/readline-common: no such file or directory"
Dec 15 19:53:50 santestnew1 dockerd[5077]: time="2017-12-15T19:53:50.099981681Z" level=info msg="stopping containerd after receiving terminated"
Dec 15 19:53:50 santestnew1 systemd[1]: Stopped Docker Application Container Engine.
-- Subject: Unit docker.service has finished shutting down
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- 
-- Unit docker.service has finished shutting down.
Dec 15 19:53:50 santestnew1 systemd[1]: Closed Docker Socket for the API.
-- Subject: Unit docker.socket has finished shutting down
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- 
-- Unit docker.socket has finished shutting down.
Dec 15 19:53:50 santestnew1 systemd[1]: Stopping Docker Socket for the API.
-- Subject: Unit docker.socket has begun shutting down
-- Defined-By: systemd
lines 2439-2467/2492 99%
Dec 15 19:53:49 santestnew1 dockerd[5077]: time="2017-12-15T19:53:49.590309475Z" level=info msg="Container d60403feb674322f848ca28e64f5fb417d58c5548a2a225f77015665657c1b0c failed to exit within 10 seconds of signal 15 - using the force"
Dec 15 19:53:49 santestnew1 dockerd[5077]: time="2017-12-15T19:53:49.591155877Z" level=info msg="Container 8b20aabf1f04021480a5f8f3cdbbc82fb91adaeafe161f2ad590151bb51e067f failed to exit within 10 seconds of signal 15 - using the force"
Dec 15 19:53:49 santestnew1 dockerd[5077]: time="2017-12-15T19:53:49.773740140Z" level=warning msg="libcontainerd: container 8b20aabf1f04021480a5f8f3cdbbc82fb91adaeafe161f2ad590151bb51e067f restart canceled"
Dec 15 19:53:49 santestnew1 dockerd[5077]: time="2017-12-15T19:53:49.920883807Z" level=warning msg="Failed detaching sandbox 0c074c43343fe655af691bafc49168e56dec33e06e217dc7341fd13fdac471e4 from endpoint b651bfb9e23e2a6dd9de11ab489972a81e2dcaa1ff8fabbf825dcad9823402ec: failed to update store for object type *libnetwork.endpoint: open : no such file or directory\n"
Dec 15 19:53:49 santestnew1 dockerd[5077]: time="2017-12-15T19:53:49.926404168Z" level=warning msg="Failed deleting endpoint b651bfb9e23e2a6dd9de11ab489972a81e2dcaa1ff8fabbf825dcad9823402ec: endpoint with name r-network-services-network-manager-4-9d701cf1 id b651bfb9e23e2a6dd9de11ab489972a81e2dcaa1ff8fabbf825dcad9823402ec has active containers\n"
Dec 15 19:53:49 santestnew1 dockerd[5077]: time="2017-12-15T19:53:49.926851071Z" level=warning msg="Failed to delete sandbox 0c074c43343fe655af691bafc49168e56dec33e06e217dc7341fd13fdac471e4 from store: open : no such file or directory"
Dec 15 19:53:49 santestnew1 dockerd[5077]: time="2017-12-15T19:53:49.985604938Z" level=error msg="containerd: start container" error="oci runtime error: container_linux.go:247: starting container process caused \"process_linux.go:334: running prestart hook 0 caused \\\"error running hook: exit status 1, stdout: , stderr: time=\\\\\\\"2017-12-15T19:53:49Z\\\\\\\" level=fatal msg=\\\\\\\"dial unix /run/docker/libnetwork/196183ff4a50e4c858e6b0f7b4127e01bf1b8232648005d3b200bf23e250bd02.sock: connect: no such file or directory\\\\\\\" \\\\n\\\"\"\n" id=cb7eaa686480df5cbb05dfc293a9ca60e1393b10b1bea1051952447bfe4e0228
Dec 15 19:53:50 santestnew1 dockerd[5077]: time="2017-12-15T19:53:50.022095174Z" level=error msg="Create container failed with error: invalid header field value \"oci runtime error: container_linux.go:247: starting container process caused \\\"process_linux.go:334: running prestart hook 0 caused \\\\\\\"error running hook: exit status 1, stdout: , stderr: time=\\\\\\\\\\\\\\\"2017-12-15T19:53:49Z\\\\\\\\\\\\\\\" level=fatal msg=\\\\\\\\\\\\\\\"dial unix /run/docker/libnetwork/196183ff4a50e4c858e6b0f7b4127e01bf1b8232648005d3b200bf23e250bd02.sock: connect: no such file or directory\\\\\\\\\\\\\\\" \\\\\\\\n\\\\\\\"\\\"\\n\""
Dec 15 19:53:50 santestnew1 dockerd[5077]: time="2017-12-15T19:53:50.065428346Z" level=warning msg="Failed detaching sandbox 01266419b094fa38e0660f2016b7b11b2085e6f414ca11d8439cac3963acd383 from endpoint ca70a091262a0f6975e964a6d8242877eda4edf0c3e527a591d046d360143609: failed to update store for object type *libnetwork.endpoint: open : no such file or directory\n"
Dec 15 19:53:50 santestnew1 dockerd[5077]: time="2017-12-15T19:53:50.066198214Z" level=warning msg="Failed deleting endpoint ca70a091262a0f6975e964a6d8242877eda4edf0c3e527a591d046d360143609: endpoint with name r-test1-healthglobal-4-00384e54 id ca70a091262a0f6975e964a6d8242877eda4edf0c3e527a591d046d360143609 has active containers\n"
Dec 15 19:53:50 santestnew1 dockerd[5077]: time="2017-12-15T19:53:50.066598546Z" level=warning msg="Failed to delete sandbox 01266419b094fa38e0660f2016b7b11b2085e6f414ca11d8439cac3963acd383 from store: open : no such file or directory"
Dec 15 19:53:50 santestnew1 dockerd[5077]: time="2017-12-15T19:53:50.087372996Z" level=error msg="Handler for POST /v1.22/containers/cb7eaa686480df5cbb05dfc293a9ca60e1393b10b1bea1051952447bfe4e0228/start returned error: invalid header field value \"oci runtime error: container_linux.go:247: starting container process caused \\\"process_linux.go:334: running prestart hook 0 caused \\\\\\\"error running hook: exit status 1, stdout: , stderr: time=\\\\\\\\\\\\\\\"2017-12-15T19:53:49Z\\\\\\\\\\\\\\\" level=fatal msg=\\\\\\\\\\\\\\\"dial unix /run/docker/libnetwork/196183ff4a50e4c858e6b0f7b4127e01bf1b8232648005d3b200bf23e250bd02.sock: connect: no such file or directory\\\\\\\\\\\\\\\" \\\\\\\\n\\\\\\\"\\\"\\n\""
Dec 15 19:53:50 santestnew1 dockerd[5077]: time="2017-12-15T19:53:50.090021255Z" level=error msg="Error during layer Store.Cleanup(): lstat /var/lib/docker/aufs/mnt/0983fc47e6439c3848d68b0904972fb15d1e38e4e55fa11703a11ae7699f1618/usr/share/lintian/overrides/readline-common: no such file or directory"
Dec 15 19:53:50 santestnew1 dockerd[5077]: time="2017-12-15T19:53:50.099981681Z" level=info msg="stopping containerd after receiving terminated"
Dec 15 19:53:50 santestnew1 systemd[1]: Stopped Docker Application Container Engine.
-- Subject: Unit docker.service has finished shutting down
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- 
-- Unit docker.service has finished shutting down.
Dec 15 19:53:50 santestnew1 systemd[1]: Closed Docker Socket for the API.
-- Subject: Unit docker.socket has finished shutting down
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- 
-- Unit docker.socket has finished shutting down.
Dec 15 19:53:50 santestnew1 systemd[1]: Stopping Docker Socket for the API.
-- Subject: Unit docker.socket has begun shutting down
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- 
-- Unit docker.socket has begun shutting down.
Dec 15 19:53:50 santestnew1 systemd[1]: docker.socket: Failed to listen on sockets: Address already in use
Dec 15 19:53:50 santestnew1 systemd[1]: Failed to listen on Docker Socket for the API.
-- Subject: Unit docker.socket has failed
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- 
-- Unit docker.socket has failed.
-- 
-- The result is failed.
Dec 15 19:53:50 santestnew1 systemd[1]: Dependency failed for Docker Application Container Engine.
-- Subject: Unit docker.service has failed
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- 
-- Unit docker.service has failed.```

**Comment by sangeethah** [comment] 2017-12-15 20:58
Logs from another host where dock restart fails:

```
root@santest3:~# journalctl -xe
Dec 15 20:55:25 santest3 systemd-udevd[21806]: Could not generate persistent MAC address for vethd68abdf: No such file or directory
Dec 15 20:55:25 santest3 kernel: eth0: renamed from veth931148f
Dec 15 20:55:25 santest3 kernel: IPv6: ADDRCONF(NETDEV_CHANGE): vethd68abdf: link becomes ready
Dec 15 20:55:25 santest3 kernel: docker0: port 1(vethd68abdf) entered forwarding state
Dec 15 20:55:25 santest3 kernel: docker0: port 1(vethd68abdf) entered forwarding state
Dec 15 20:55:26 santest3 kernel: aufs au_opts_verify:1597:dockerd[20348]: dirperm1 breaks the protection by the permission bits on the lower branch
Dec 15 20:55:26 santest3 kernel: aufs au_opts_verify:1597:dockerd[4691]: dirperm1 breaks the protection by the permission bits on the lower branch
Dec 15 20:55:27 santest3 dockerd[1336]: time="2017-12-15T20:55:27.016219857Z" level=error msg="containerd: start container" error="oci runtime error: container_linux.go:247: starting container process caused \"process_linux.go:359: container init caused \\\"rootfs_linux.go:53: mounting \\\\\\\"/var/run/docker.sock\\\\\\\" to rootfs \\\\\\\"/var/lib/docker/aufs/mnt/72a9fb803bc01b405e603f5573903fe546f744e6cbed2208c7f867373b4df8d8\\\\\\\" at \\\\\\\"/var/lib/docker/aufs/mnt/72a9fb803bc01b405e603f5573903fe546f744e6cbed2208c7f867373b4df8d8/var/run/docker.sock\\\\\\\" caused \\\\\\\"not a directory\\\\\\\"\\\"\"\n" id=9b7989e361072f5ab8ca2772ccb7830512fa560d4f13f36a0b07f3e83a09d077
Dec 15 20:55:27 santest3 dockerd[1336]: time="2017-12-15T20:55:27.025071024Z" level=error msg="Create container failed with error: invalid header field value \"oci runtime error: container_linux.go:247: starting container process caused \\\"process_linux.go:359: container init caused \\\\\\\"rootfs_linux.go:53: mounting \\\\\\\\\\\\\\\"/var/run/docker.sock\\\\\\\\\\\\\\\" to rootfs \\\\\\\\\\\\\\\"/var/lib/docker/aufs/mnt/72a9fb803bc01b405e603f5573903fe546f744e6cbed2208c7f867373b4df8d8\\\\\\\\\\\\\\\" at \\\\\\\\\\\\\\\"/var/lib/docker/aufs/mnt/72a9fb803bc01b405e603f5573903fe546f744e6cbed2208c7f867373b4df8d8/var/run/docker.sock\\\\\\\\\\\\\\\" caused \\\\\\\\\\\\\\\"not a directory\\\\\\\\\\\\\\\"\\\\\\\"\\\"\
Dec 15 20:55:27 santest3 dockerd[1336]: time="2017-12-15T20:55:27.099306495Z" level=error msg="Handler for POST /v1.22/containers/9b7989e361072f5ab8ca2772ccb7830512fa560d4f13f36a0b07f3e83a09d077/start returned error: invalid header field value \"oci runtime error: container_linux.go:247: starting container process caused \\\"process_linux.go:359: container init caused \\\\\\\"rootfs_linux.go:53: mounting \\\\\\\\\\\\\\\"/var/run/docker.sock\\\\\\\\\\\\\\\" to rootfs \\\\\\\\\\\\\\\"/var/lib/docker/aufs/mnt/72a9fb803bc01b405e603f5573903fe546f744e6cbed2208c7f867373b4df8d8\\\\\\\\\\\\\\\" at \\\\\\\\\\\\\\\"/var/lib/docker/aufs/mnt/72a9fb803bc01b405e603f5573903fe546f744e6cbed2208c7f867373b4df8d8/var/run/docker.so
Dec 15 20:55:27 santest3 kernel: aufs au_opts_verify:1597:dockerd[19639]: dirperm1 breaks the protection by the permission bits on the lower branch
Dec 15 20:55:27 santest3 kernel: aufs au_opts_verify:1597:dockerd[3689]: dirperm1 breaks the protection by the permission bits on the lower branch
Dec 15 20:55:28 santest3 kernel: aufs au_opts_verify:1597:dockerd[1702]: dirperm1 breaks the protection by the permission bits on the lower branch
Dec 15 20:55:28 santest3 kernel: aufs au_opts_verify:1597:dockerd[3091]: dirperm1 breaks the protection by the permission bits on the lower branch
Dec 15 20:55:28 santest3 dockerd[1336]: time="2017-12-15T20:55:28.478427237Z" level=info msg="Container 0cb0095ccbde464faa9c9c30b8d88d6a47d55ab41e510e73f8d4fc68e977f218 failed to exit within 10 seconds of signal 15 - using the force"
Dec 15 20:55:28 santest3 dockerd[1336]: time="2017-12-15T20:55:28.479482588Z" level=info msg="Container 8f01ecb9bf8bbb20ed1a491c1815e34ff840b2b342ee706d44313aac7f760371 failed to exit within 10 seconds of signal 15 - using the force"
Dec 15 20:55:28 santest3 dockerd[1336]: time="2017-12-15T20:55:28.581913852Z" level=warning msg="libcontainerd: container 0cb0095ccbde464faa9c9c30b8d88d6a47d55ab41e510e73f8d4fc68e977f218 restart canceled"
Dec 15 20:55:28 santest3 dockerd[1336]: time="2017-12-15T20:55:28.701841446Z" level=error msg="Handler for GET /v1.22/containers/json returned error: write unix /var/run/docker.sock->@: write: broken pipe"
Dec 15 20:55:28 santest3 dockerd[1336]: http: multiple response.WriteHeader calls
Dec 15 20:55:28 santest3 dockerd[1336]: time="2017-12-15T20:55:28.704201858Z" level=error msg="Handler for GET /v1.22/containers/json returned error: write unix /var/run/docker.sock->@: write: broken pipe"
Dec 15 20:55:28 santest3 dockerd[1336]: http: multiple response.WriteHeader calls
Dec 15 20:55:33 santest3 dockerd[1336]: time="2017-12-15T20:55:33.411055435Z" level=error msg="Force shutdown daemon"
Dec 15 20:55:33 santest3 dockerd[1336]: time="2017-12-15T20:55:33.414844257Z" level=info msg="stopping containerd after receiving terminated"
Dec 15 20:55:33 santest3 systemd[1]: Stopped Docker Application Container Engine.
-- Subject: Unit docker.service has finished shutting down
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- 
-- Unit docker.service has finished shutting down.
Dec 15 20:55:33 santest3 systemd[1]: Closed Docker Socket for the API.
-- Subject: Unit docker.socket has finished shutting down
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- 
-- Unit docker.socket has finished shutting down.
Dec 15 20:55:33 santest3 systemd[1]: Stopping Docker Socket for the API.
-- Subject: Unit docker.socket has begun shutting down
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- 
-- Unit docker.socket has begun shutting down.
Dec 15 20:55:33 santest3 systemd[1]: docker.socket: Failed to listen on sockets: Address already in use
Dec 15 20:55:33 santest3 systemd[1]: Failed to listen on Docker Socket for the API.
-- Subject: Unit docker.socket has failed
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- 
-- Unit docker.socket has failed.
-- 
-- The result is failed.
Dec 15 20:55:33 santest3 systemd[1]: Dependency failed for Docker Application Container Engine.
-- Subject: Unit docker.service has failed
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- 
-- Unit docker.service has failed.
-- 
-- The result is dependency.
Dec 15 20:55:33 santest3 systemd[1]: docker.service: Job docker.service/start failed with result 'dependency'.
Dec 15 20:55:33 santest3 systemd[1]: docker.socket: Unit entered failed state.
Dec 15 20:55:41 santest3 kernel: docker0: port 1(vethd68abdf) entered forwarding state

```

**Comment by deniseschannon** [comment] 2017-12-18 06:34
@sangeethah what version of docker and what OS?

**Comment by sidcarter** [comment] 2017-12-18 14:18
happening here too. On Ubuntu 17.10

```
$ uname -a
Linux worker-node-0 4.13.0-19-generic #22-Ubuntu SMP Mon Dec 4 11:58:07 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
```

Docker version
```
$ sudo docker version
Client:
 Version:      17.09.1-ce
 API version:  1.32
 Go version:   go1.8.3
 Git commit:   19e2cf6
 Built:        Thu Dec  7 22:24:28 2017
 OS/Arch:      linux/amd64
Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
```

**Comment by sangeethah** [comment] 2017-12-18 17:08
Docker version - 1.12.6 OS version - Ubuntu 16.04.3 LTS (with KVM) (4.4.0)

**Comment by leodotcloud** [comment] 2017-12-18 18:57
When I tried to repro the issue, I ran into a different error:

```
-- Unit docker.service has finished shutting down.
Dec 18 18:46:31 sannewtest systemd[1]: docker.socket: Failed to listen on sockets: Address already in use
Dec 18 18:46:31 sannewtest systemd[1]: Failed to listen on Docker Socket for the API.
-- Subject: Unit docker.socket has failed
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
--
-- Unit docker.socket has failed.
```

Root cause:
```
# ls -l /var/run/ | grep docker
drwx------  5 root root  100 Dec 17 03:47 docker
drwxr-xr-x  2 root root   40 Dec 17 03:55 docker.sock
```

`docker.sock` has become a directory ... that's the problem this time ...

Solution for this:
```
rm -rf /var/run/docker.sock
```

**Comment by sidcarter** [comment] 2017-12-18 19:17
yep, I noticed that. why did it become a directory though? curious!

**Comment by leodotcloud** [comment] 2017-12-18 19:23
After running `systemctl restart docker`, I still see some of the containers running.

```
root@sannewtest:~# runc list
ID                                                                 PID         STATUS      BUNDLE                                                                                       CREATED
129f0018b92be0261afe06ad83152b305c85918f646407011a6519b72ab6c57a   18785       running     /run/docker/libcontainerd/129f0018b92be0261afe06ad83152b305c85918f646407011a6519b72ab6c57a   2017-12-18T19:08:50.110333572Z
50a1df9fe8eb4848603e1063d01b67166ccb391fc3f99312c8361aae7ca17840   18609       running     /run/docker/libcontainerd/50a1df9fe8eb4848603e1063d01b67166ccb391fc3f99312c8361aae7ca17840   2017-12-18T19:08:49.695104278Z
8ea014213f0ebe1e552b3ec58fede70f40ca0ec1fb50775d35d7a0b56a80520c   18883       running     /run/docker/libcontainerd/8ea014213f0ebe1e552b3ec58fede70f40ca0ec1fb50775d35d7a0b56a80520c   2017-12-18T19:08:51.407608446Z
c68fbece72cd4f7f80778518ad820e43239ce6584a64835969ebb93fa5fa5113   18840       running     /run/docker/libcontainerd/c68fbece72cd4f7f80778518ad820e43239ce6584a64835969ebb93fa5fa5113   2017-12-18T19:08:50.315036857Z
root@sannewtest:~#
root@sannewtest:~#
root@sannewtest:~#
root@sannewtest:~# ps -ef | grep 18785
root     18785 18752  0 19:08 ?        00:00:01 rancher-metadata -reload-interval-limit=1000 -subscribe
root     19430 19012  0 19:21 pts/1    00:00:00 grep 18785
root@sannewtest:~# ps -ef | grep 18609
root     18609 18575  0 19:08 ?        00:00:00 connectivity-check
root     19432 19012  0 19:21 pts/1    00:00:00 grep 18609
root@sannewtest:~# ps -ef | grep 18883
root     18883 18868  0 19:08 ?        00:00:00 rancher-dns --listen 169.254.169.250:53 --metadata-server=localhost --answers=/etc/rancher-dns/answers.json --recurser-timeout 2 --ttl 1 -rancher-metadata-answer=169.254.169.250 -never-recurse-to=169.254.169.250
root     19434 19012  0 19:22 pts/1    00:00:00 grep 18883
root@sannewtest:~# ps -ef | grep 18840
root     18840 18825  0 19:08 pts/0    00:00:00 /.r/r /scripts/run.sh nginx -g daemon off;
root     19436 19012  0 19:22 pts/1    00:00:00 grep 18840
root@sannewtest:~#
```

**Comment by pulberg** [comment] 2017-12-18 19:41
This has been happening for a long time - https://github.com/moby/moby/issues/30348

**Comment by leodotcloud** [comment] 2017-12-18 22:53
Another observation:

Digitalocean host added using machine-driver or from DO installed docker:
```
root@leo-test-host:~# systemctl status docker
● docker.service - Docker Application Container Engine
   Loaded: loaded (/lib/systemd/system/docker.service; enabled; vendor preset: enabled)
  Drop-In: /etc/systemd/system/docker.service.d
           └─10-machine.conf
   Active: active (running) since Mon 2017-12-18 20:47:42 UTC; 1h 48min ago
     Docs: https://docs.docker.com
 Main PID: 10314 (dockerd)
    Tasks: 145
   Memory: 248.0M
      CPU: 13.196s
   CGroup: /system.slice/docker.service
           ├─10314 /usr/bin/dockerd -H tcp://0.0.0.0:2376 -H unix:///var/run/docker.sock --storage-driver aufs --tlsverify --tlscacert /etc/docker/ca.pem --tlscert /etc/docker/server.pem --tlskey /etc/docker/server-key.pem --label provider=digitalocean
```

Docker installed manually: `curl -sSL https://raw.githubusercontent.com/rancher/install-docker/master/1.12.6.sh | sh -`
```
root@leo-test3:~# systemctl status docker
● docker.service - Docker Application Container Engine
   Loaded: loaded (/lib/systemd/system/docker.service; enabled; vendor preset: enabled)
   Active: active (running) since Mon 2017-12-18 22:46:44 UTC; 3min 3s ago
     Docs: https://docs.docker.com
 Main PID: 21931 (dockerd)
    Tasks: 145
   Memory: 275.6M
      CPU: 2.630s
   CGroup: /system.slice/docker.service
           ├─21931 /usr/bin/dockerd -H fd://
           ├─21947 docker-containerd -l unix:///var/run/docker/libcontainerd/docker-containerd.sock --shim docker-containerd-shim --metrics-interval=0 --start-timeout 2m --state-dir /var/run/docker/libcontainerd/containerd --runtime docker-runc
```

I don't see the issue happening on the host where I installed docker directly from rancher scripts.

There is a difference in the arguments passed to `dockerd` while starting.

**Comment by leodotcloud** [comment] 2017-12-18 23:00
Question:

I understand `/usr/bin/dockerd -H tcp://0.0.0.0:2376 -H unix:///var/run/docker.sock` means we are listening on the docker socket and also port 2376 

But what does this mean: `/usr/bin/dockerd -H fd://`

Answer: `https://stackoverflow.com/questions/43303507/what-does-fd-mean-exactly-in-dockerd-h-fd`

**Comment by leodotcloud** [comment] 2017-12-18 23:09
I think there is some kind of a race condition between systemd and docker. I can't think of any of rancher's code or the recent networking fixes causing this problem.

**Comment by leodotcloud** [comment] 2018-03-05 19:41
@sangeethah @deniseschannon This doesn't seem to be caused by rancher. Can we close this?

**Closed** 2018-08-21 22:06 UTC
Labels: kind/bug, status/autoclosed
