### ISSUE TITLE
Upgrading EKS outside of rancher shows updated version in cluster view page but not edit

### ISSUE THREAD

**Issue by rancher-max** [rancher/rancher#26221] opened 2020-03-23 23:34 UTC
**What kind of request is this (question/bug/enhancement/feature request):**
bug

**Steps to reproduce (least amount of steps as possible):**
1. Create EKS cluster of an old version through Rancher (I created v1.13 through the API)
2. Upgrade the EKS cluster using AWS UI (I upgraded to v1.14)

**Result:**
- The upgraded kubernetes version DOES show in the cluster view page
- If editing the cluster, the upgraded kubernetes version DOES NOT show (still shows the version selected during creation)

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): v2.4.0-rc8
- Installation option (single install/HA): single

**Comment by deniseschannon** [comment] 2020-03-24 02:14
@wes how are we populating the k8s dropdown?

In general, we have an overall issue with the edit pages in EKS clusters cause it makes it look like you could select/change some other options, but per @rmweir the only option we can edit is the k8s version.

**Comment by deniseschannon** [comment] 2020-03-24 04:43
This is actually a duplicate of https://github.com/rancher/rancher/issues/24171, but I want to keep this open to track what's going on with the UI for the edit for EKS clusters.

**Comment by deniseschannon** [comment] 2020-03-24 18:41
Closing this in favor of #24171 and opened this issue instead for all the fields that are not actually updateable:

https://github.com/rancher/rancher/issues/26231

**Closed by deniseschannon** 2020-03-24 18:41 UTC
Labels: [zube]: Next Up, area/eks, kind/bug, team/ui
