### ISSUE TITLE
User \"u-eu7dpqslaf\" cannot get resource \"clusters\" in API group \"management.cattle.io\" at the cluster error seen when an RKE2 cluster is provisioning

### ISSUE THREAD

**Issue by sowmyav27** [rancher/rancher#34324] opened 2021-08-19 04:52 UTC
**Rancher Server Setup** 
- Rancher version: 2.6-head commit id: `9d5c699`
- Installation option (Docker install/Helm Chart): Helm
   - If Helm Chart, Kubernetes Info:
         Cluster Type (RKE1, RKE2, k3s, EKS, etc): RKE1 1.21.4
         Node Setup: 3 nodes all roles
         Version: 1.21.4
- Proxy/Cert Details:

**Information about the Cluster**
- Kubernetes version: v1.21.3-rc6+rke2r2
- Cluster Type (Local/Downstream): DO RKE2 node driver

**Describe the bug**
User \"u-eu7dpqslaf\" cannot get resource \"clusters\" in API group \"management.cattle.io\" at the cluster error seen when an RKE2 cluster is provisioning

**To Reproduce**
Deploy an rke2 DO cluster as an admin
Rancher logs show

```
2021/08/18 22:49:53 [INFO] Failed to find providerID for selector rke.cattle.io/machine=96286070-15aa-4333-9d5a-90b39e56a631 in cluster fleet-default/sowmyanew, machine sowmyanew-pool1-74fbf78f74-x6jjw: {"Code":{"Code":"Forbidden","Status":403},"Message":"clusters.management.cattle.io \"c-m-qlcwsmr2\" is forbidden: User \"u-eu7dpqslaf\" cannot get resource \"clusters\" in API group \"management.cattle.io\" at the cluster scope","Cause":null,"FieldName":""} (get nodes)
```

**Comment by snasovich** [comment] 2021-08-19 15:36
@sowmyav27 , this looks to be a duplicate of an issue that was deemed to be "functions as designed": https://github.com/rancher/rancher/issues/33790#issuecomment-889482922
Please close if you agree.

**Closed** 2021-08-19 16:16 UTC
Labels: kind/bug-qa, [zube]: To Test
