### ISSUE TITLE
Feature Request: Different Colours Per Cluster

### ISSUE THREAD

**Issue by eddieparker** [rancher/rancher#21038] opened 2019-06-21 04:24 UTC
Feature Request: Different Colour UI Per Cluster

I often flip between clusters without realizing which one I'm in, and then can edit the wrong one.  It'd be nice if I could set different colour backgrounds per cluster so I can tell what context I'm in.

**Comment by superseb** [comment] 2019-06-21 08:39
Duplicate of https://github.com/rancher/rancher/issues/15838

**Closed by superseb** 2019-06-21 08:39 UTC

**Comment by eddieparker** [comment] 2019-06-22 05:28
Pardon my ignorance, but all the referenced duplicates are closed but I'm unclear what the resolution is.  Does this feature exist already?  Is it on a roadmap?  Is it not going to be implemented?

**Comment by superseb** [comment] 2019-06-25 14:56
It's not on the roadmap, the referenced issue was opened a while ago and there has been no response or request for it so it is closed to try to keep the backlog as clean as possible for features that will be implemented.
