### ISSUE TITLE
[BUG] Unable to provision clusters on 2.7

### ISSUE THREAD

**Issue by sowmyav27** [rancher/rancher#39150] opened 2022-09-28 14:00 UTC
**Rancher Server Setup**
- Rancher version: 2.7-head commit id: `35388ea`
- Installation option (Docker install/Helm Chart): docker install

**Information about the Cluster**
- Kubernetes version: 1.24.4
- Cluster Type (Local/Downstream): RKE1 or RKE2

**User Information**
- What is the role of the user logged in? (Admin/Cluster Owner/Cluster Member/Project Owner/Project Member/Custom) Admin

**Describe the bug**
[BUG] Unable to provision clusters on 2.7

**To Reproduce**
- Deploy a Linode RKE1 or RKE2 clusters.

**Result**
- Error seen : `Failed while: Wait for Condition: InitialRolesPopulated: True`

**RKE1**
<img width="1067" alt="Screen Shot 2022-09-28 at 6 56 33 AM" src="https://user-images.githubusercontent.com/26032343/192798771-6b77c800-3709-4fab-87f9-c33214131653.png">

**RKE2**

<img width="1493" alt="Screen Shot 2022-09-28 at 6 59 23 AM" src="https://user-images.githubusercontent.com/26032343/192798790-cdedd722-8f4d-4328-a8e4-2459bb19462b.png">

**Comment by kinarashah** [comment] 2022-09-28 22:56
Unable to reproduce on v2.7-head (confirmed I was testing with the commit same as the issue description). The cluster provisioning goes through. Moving it back to test, can check back again if it's a timing issue that doesn't reproduce consistently.

**Comment by markusewalker** [comment] 2022-09-29 16:48
**QA TEST PLAN**
1. Setup Rancher, create a standard user and login as that user.
2. Provision downstream RKE1 & RKE2 node driver clusters.
3. Validate if the cluster and nodes come up as `Active` in Cluster Management and Cluster Explorer.

**Comment by markusewalker** [comment] 2022-09-29 17:10
Unable to reproduce on `v2.7-head` https://github.com/rancher/rancher/commit/40c390d79faef993e8509d545a4ed1e18a78a4de.

**ENVIRONMENT DETAILS**
- Rancher install: Docker
- Rancher version: `v2.7-head` https://github.com/rancher/rancher/commit/40c390d79faef993e8509d545a4ed1e18a78a4de
- Browser: Chrome

**TEST RESULT**
UNABLE TO REPRODUCE

**NON-REPRO STEPS**
1. Setup Rancher, created a standard user and logged in as that user.
2. Provisioned downstream RKE1 & RKE2 node driver clusters.
3. Validated that the cluster and nodes come up as `Active` in Cluster Management and Cluster Explorer:
![image](https://user-images.githubusercontent.com/52591819/193095570-ec635bbd-7837-4be7-8d81-81e1e66b679f.png)
![image](https://user-images.githubusercontent.com/52591819/193095503-0dd16b09-d2b0-4b80-914c-812887902232.png)
![image](https://user-images.githubusercontent.com/52591819/193095435-334bf6cb-2075-45d4-957a-fd556b74fa4a.png)
![image](https://user-images.githubusercontent.com/52591819/193095373-fb9d3872-cb7b-4988-adc9-eea461e1acf3.png)
![image](https://user-images.githubusercontent.com/52591819/193095315-922919e6-1fc0-44a6-8117-e07cfa22398e.png)

**Closed by markusewalker** 2022-09-29 17:10 UTC
Labels: kind/bug, status/blocker, [zube]: Working, QA/XS, status/release-blocker, team/area2
