### ISSUE TITLE
K3S logs don't always have timestamps

### ISSUE THREAD

**Issue by AmartC** [rancher/rancher#33046] opened 2021-04-23 17:59 UTC
When setting up a 4 node K3S cluster using Amazon EC2 for the nodes, logs are being shipped over to endpoint but notice that some logs are formatted in a manner that doesn't include the timestamp as a column. 
```
[{'log': 'Apr 22 18:30:20 ip-172-31-11-255 systemd[8530]: run-snapd-ns-lxd.mnt.mount: Succeeded.'}, {'log': 'Apr 22 18:30:20 ip-172-31-11-255 systemd[1]: run-snapd-ns-lxd.mnt.mount: Succeeded.'}, {'log': 'Apr 22 18:30:20 ip-172-31-11-255 systemd[8530]: tmp-snap.rootfs_QyXyfh.mount: Succeeded.'}, {'log': 'Apr 22 18:30:20 ip-172-31-11-255 systemd[1]: tmp-snap.rootfs_QyXyfh.mount: Succeeded.'}, {'log': 'Apr 22 18:30:20 ip-172-31-11-255 lxd.activate[26332]: => Starting LXD activation'}, {'log': 'Apr 22 18:30:20 ip-172-31-11-255 lxd.activate[26332]: ==> Loading snap configuration'}, {'log': 'Apr 22 18:30:20 ip-172-31-11-255 lxd.activate[26332]: ==> Checking for socket activation support'}, {'log': 'Apr 22 18:30:20 ip-172-31-11-255 lxd.activate[26332]: ==> Setting LXD socket ownership'}, {'log': 'Apr 22 18:30:20 ip-172-31-11-255 lxd.activate[26332]: ==> LXD never started on this system, no need to start it now'}, {'log': 'Apr 22 18:30:20 ip-172-31-11-255 systemd[1]: snap.lxd.activate.service: Succeeded.'}, {'log': 'Apr 22 18:30:20 ip-172-31-11-255 systemd[1]: Finished Service for snap application lxd.activate.'}, {'log': 'Apr 22 18:30:20 ip-172-31-11-255 systemd[1]: Started snap.lxd.hook.configure.8eb69d5c-a61f-4349-96a4-db87f691600c.scope.'}, {'log': 'Apr 22 18:30:20 ip-172-31-11-255 systemd[1]: snap.lxd.hook.configure.8eb69d5c-a61f-4349-96a4-db87f691600c.scope: Succeeded.'}, {'log': 'Apr 22 18:30:21 ip-172-31-11-255 snapd[25819]: storehelpers.go:551: cannot refresh: snap has no updates available: "core18", "lxd", "snapd"'}]
```

The Rancher logging is setup by using the Rancher server, creating a chart repository based on this the charts repository and the dev-v2.5 branch.

**Comment by paynejacob** [comment] 2021-06-08 17:15
caused by https://github.com/k3s-io/k3s/issues/3392

**Comment by paynejacob** [comment] 2021-06-18 21:49
The solution to this is going to be to write custom parsers for all the k3s system logs.  As of right now I know of the following formats:

- k3s
- klog
- etcd

**Comment by snasovich** [comment] 2021-07-14 22:10
@SheilaghM , assigning it to @nickgerace since he's the other Logging SME and we cannot have it validated by who implemented it (Jacob).

**Comment by brendarearden** [comment] 2021-08-13 18:52
Validation: FAILED

Steps to recreate:

1. Create a DO droplet, install docker and install k3s using `curl -sfL https://get.k3s.io | sh -` which installs v1.21.3+k3s1 (1d1f220f) and spins up a cluster
2. From an HA cluster (3 nodes on DO droplets clustered with rke version v1.2.11), running rancher v2.6.0-rc (installed using `helm install`)
3. Import existing k3s cluster
4. On the imported k3s cluster, install `rancher-logging`
5. Add an additional chart repo >>  name: example, type: git, git repo: https://github.com/paynejacob/rancher-logging-examples.git, branch: master
6. Go to charts and install the `rancher-logging example` from the new `example` you added
8. On local machine run `docker run -p 24224:24224 fluent/fluent-bit /fluent-bit/bin/fluent-bit -i forward -o stdout -p 'format=json_lines'`
9. On local machine run `ngrok tcp 24224`
9. Go to logging, cluster  outputs and edit the `all-logs` output as yaml and change the `spec` so that it looks like the following
```
spec:
  forward:
    servers:
    - host: 4.tcp.ngrok.io
      port: 13690
```
but use your own host and port that is output from your `ngrok` run
10. Wait a few minutes and see logs start to populate from pods
11. I do not see any logs being pulled from k3s
12. From the node running k3s, I run `journalctl -eu k3s -f` and see k3s is logging and none of those logs are being picked up.

**Comment by paynejacob** [comment] 2021-08-19 19:19
@brendarearden I think your environment was misconfigured for this.  Can you test on a cluster using ubuntu with `systemdLogPath: /var/log/journal` in your values.yaml.

**Comment by aiyengar2** [comment] 2021-08-20 20:42
Since all the fixes pushed for this PR are to rancher/charts, I am reproducing the issue in the older version of the chart shipped with 2.5.10 and available in 2.6.0 and testing the fix in the latest version of the chart, both using the latest RC of rancher/rancher.

Reproducing in: Rancher `2.6.0-rc4`, Logging [`3.9.400`](https://github.com/rancher/charts/tree/release-v2.6/charts/rancher-logging/rancher-logging/3.9.400)

Testing fix in: Rancher `2.6.0-rc4`, Logging [`100.0.0+up3.12.0`](https://github.com/rancher/charts/tree/dev-v2.6/charts/rancher-logging/rancher-logging/100.0.0%2Bup3.12.0)

---

Since no environment information was provided (and is probably not necessary), I will test this out on imported k3s clusters using 1 controlplane, 3 worker nodes.

For each of these nodes, I will also use the AMI `ami-00399ec92321828f5` corresponding to `Ubuntu Server 20.04 LTS (HVM), SSD Volume Type (64-bit x86)`

--- 

I will test two scenarios: a fresh install and an upgrade of the Logging chart.

---

#### Steps to Reproduce

##### Provision imported k3s cluster
- Provision an EC2 instance with AMI `ami-00399ec92321828f5` for your controlplane node and install k3s on it: `curl -sfL https://get.k3s.io | sh -`
- Once k3s is provisioned, grab the IP address of the ec2 instance for K3S_SERVER_IP below and the output of `sudo cat /var/lib/rancher/k3s/server/node-token` for K3S_SERVER_NODE_TOKEN
- Provision 3 more EC2 instances with the same AMI for your worker nodes and install k3s on it:
```
K3S_SERVER_IP=<insert-ip-here>
K3S_SERVER_NODE_TOKEN=<insert-token-here>

curl -sfL https://get.k3s.io | K3S_URL=https://${K3S_SERVER_IP}:6443 K3S_TOKEN=${K3S_SERVER_NODE_TOKEN} sh -
```

*NOTE: keep the controlplane node's SSH session open since you will need it as part of importing it into Rancher.*

#### Provision a FluentBit node
- Provision a single node and install Docker on it: `curl https://releases.rancher.com/install-docker/20.10.sh | sh`
- Install fluent-bit with the following script via Docker
```
docker run -d --name fluentbit -p 24224:24224 fluent/fluent-bit /fluent-bit/bin/fluent-bit -i forward -o stdout -p 'format=json_lines'
```
- Also install jq: `sudo apt-get install jq -y`

This will install a fluent-bit instance that is listening on port 24224 for logs that are then forwarded to stdout in JSON format.

*NOTE: keep track of the fluentbit node's IP address since you will need it as part of configuring the ClusterOutput below.*

##### Provision Rancher
- Provision a single node and install Docker on it: `curl https://releases.rancher.com/install-docker/20.10.sh | sh`
- Install Rancher on the single node
```
RANCHER_VERSION=v2.6.0-rc4

docker run -d --restart=unless-stopped \
  -p 80:80 -p 443:443 \
  --privileged \
  rancher/rancher:${RANCHER_VERSION}
```
- Log into Rancher
- Click on `Import Existing` -> `Generic` and name the cluster. Create it and follow the instructions to add the k3s cluster created in the previous step to the Rancher cluster via supplying the kubectl apply command on the controlplane node
- Navigate to the newly created cluster and go to Apps & Marketplace -> Charts -> Logging and click on the Chart Version on the right that corresponds to the Logging version that will be installed (e.g. `3.9.400` or `100.0.0+up3.12.0`). Click on `Install`
- On the next page, select `System` for `Install Into Project` and click `Next`
- On the last page, ensure that on clicking Compare Changes the `systemdLogPath` is patched to `/var/log/journal`, not `/run/log/journal`. If not, click on `Edit YAML` and manually patch it before continuing. 
  - This is a current UI issue and a workaround mentioned in https://github.com/rancher/dashboard/issues/3945#issuecomment-902882917.
- For testing
![Screen Shot 2021-08-20 at 11 45 55 AM](https://user-images.githubusercontent.com/13127443/130279704-b52bc945-48e3-4d24-bcfe-4cf5512768a5.png)
- Install the Logging V2 chart
- Once installed, create the following resources in the Kubernetes cluster via `kubectl apply -f` **after setting `spec.forward.servers[0].host=FLUENT_BIT_HOST_IP` below**, where FLUENT_BIT_HOST_IP is the IP of the host you created in the previous step that is listening for logs:
```yaml
apiVersion: logging.banzaicloud.io/v1beta1
kind: ClusterFlow
metadata:
  name: all-logs
  namespace: cattle-logging-system
spec:
  globalOutputRefs:
    - local
---
apiVersion: logging.banzaicloud.io/v1beta1
kind: ClusterOutput
metadata:
  name: local
  namespace: cattle-logging-system
spec:
  forward:
    servers:
    - host: FLUENT_BIT_HOST_IP
      port: 24224
    buffer:
      flush_interval: 1s
      flush_mode: interval
```

#### Check Logs

##### Collect Logs

On the FluentBit Node, run the following command:
```
docker logs fluentbit | jq 'select(.kubernetes)' > fluentbit.logs
```

##### Upgrade-Specific Instructions

On the FluentBit Node, run the following command:
```
docker logs fluentbit | jq 'select(.kubernetes)' > fluentbit-pre-upgrade.logs
```

Then run `docker stop fluentbit && docker rm -f fluentbit` to remove the fluent-bit pod.

Proceed with upgrading to the latest version of the Logging chart in `100.0.0+up3.12.0`.

Wait for 2 minutes and then re-run the command to start up the docker container:
```
docker run -d --name fluentbit -p 24224:24224 fluent/fluent-bit /fluent-bit/bin/fluent-bit -i forward -o stdout -p 'format=json_lines'
```

Then collect the logs after a period of time:
```
docker logs fluentbit | jq 'select(.kubernetes)' > fluentbit-post-upgrade.logs
```

**Comment by aiyengar2** [comment] 2021-08-20 20:46
When following the above steps, it was observed that no k3s logs showed up in fluentbit logs at all. I reached out to @paynejacob and it seems like the issue is due to an error in the fluentbit pod:

```
[2021/08/20 20:37:16] [error] [parser] cannot parse '2021-08-20T17:41:01.604126273Z'
[2021/08/20 20:37:16] [ warn] [parser:rancher] invalid time format %FT%TZ for '2021-08-20T17:41:01.604126273Z'
```

Reopening this issue and https://github.com/rancher/rancher/issues/33328 since both will be impacted as no k3s logs will be emitted.

Also, when this issue is resolved and put back to test, I will use the same setup for this issue and https://github.com/rancher/rancher/issues/33328 to test.

**Comment by brendarearden** [comment] 2021-08-24 22:58
Validation: PASSED

**Steps to recreate:**

1. Create a EC2 instance, install docker and install k3s using `curl -sfL https://get.k3s.io | sh -` which installs v1.21.3+k3s1 (1d1f220f) and spins up a cluster
2. From an HA cluster (3 nodes on DO droplets clustered with rke version v1.2.11), running rancher v2.6.0-rc (installed using helm install)
3. Import existing k3s cluster in rancher
4. From the rancher ui, go into the k3s cluster, install logging - make sure to edit the values.yaml and change the `systemdLogPath` is set to `/var/log/journal`
5. Add an additional chart repo >> name: example, type: git, git repo: https://github.com/paynejacob/rancher-logging-examples.git, branch: master
6. Go to charts and install the rancher-logging example from the new example you added
7. On local machine run `docker run -p 24224:24224 fluent/fluent-bit /fluent-bit/bin/fluent-bit -i forward -o stdout -p 'format=json_lines'`
8. On local machine run `ngrok tcp 24224`
9. Go to logging, cluster outputs and edit the all-logs output as yaml and change the spec so that it looks like the following
```
spec:
  forward:
    servers:
    - host: 4.tcp.ngrok.io
      port: 13690
but use your own host and port that is output from your ngrok run
```
10. Wait a few minutes and see logs start to populate from pods
11. Validate that I see logs with timestamps: 
```
{"date":1629835249.449112,"stream":"stderr","logtag":"F","message":"time=\"2021-08-24T20:00:49Z\" level=info msg=\"getting history for release fleet-agent-ec2-k3s\"","kubernetes" .....

{"date":1629829804.352445,"level":"warn","ts":"2021-08-24T18:30:04.352Z","caller":"etcdserver/util.go:163","msg":"apply request took too long","took":"476.926929ms","expected-duration":"100ms","prefix":"read-only range .......

```
12. I am not seeing the `[error] [parser] cannot parse ` errors 


Note: Not all logs will have a timestamp, but those that are able to, will. 
Example of log without timestamp
```
{"date":1629843775.863137,"stream":"stdout","logtag":"F","message":"</ROOT>","kubernetes":{"pod_name":"rancher-logging-fluentd-configcheck-80f7505b","namespace_name":"cattle-logging-system","pod_id":"<redacted>","labels":{"app.kubernetes.io/component":"fluentd-configcheck","app.kubernetes.io/managed-by":"rancher-logging","app.kubernetes.io/name":"fluentd"},"host":"<redacted>","container_name":"fluentd","docker_id":"<redacted>","container_image":"rancher/mirrored-banzaicloud-fluentd:v1.12.4-alpine-1"}}
```

**Closed** 2021-08-25 14:13 UTC
Labels: area/logging, [zube]: QA Working, status/dev-validate, QA/XS
