### ISSUE TITLE
UI: version sorting is not working

### ISSUE THREAD

**Issue by EugenMayer** [rancher/rancher#4999] opened 2016-06-03 00:28 UTC
**Rancher Version:**
1.0.1

**Docker Version:**
rancheros latest

**OS and where are the hosts located? (cloud, bare metal, etc):**
kvm

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**

**Steps to Reproduce:**
create a catalog revision with 2 digits as patch version

**Results:** 
https://goo.gl/3frB0f

**Expected:**
1.1.11 being the most recent
Looks like this is just the "naive" string comparison implementation, wont work for versions

**Comment by tfiduccia** [comment] 2016-07-27 00:10
@EugenMayer this is a duplicate of #3719 but also note that this seems to be working in
Master - 07/26
![image](https://cloud.githubusercontent.com/assets/11514927/17159652/ae617546-5353-11e6-83c7-cc0d4d05eb01.png)

**Closed by tfiduccia** 2016-07-27 00:10 UTC
Labels: area/ui, kind/bug
