### ISSUE TITLE
Unavailable tcp-services upstream results in 1000s of SYN retries from ingress-nginx-controller and 1000s of correlating log messages in ingress-nginx-controller logs

### ISSUE THREAD

**Issue by axeal** [rancher/rancher#28671] opened 2020-09-01 10:30 UTC
**What kind of request is this (question/bug/enhancement/feature request):**

Bug?

**Steps to reproduce (least amount of steps as possible):**

1. Provision a Rancher v2.4.5 lab with a downstream cluster (can be single node)
2. Add a simple nginx Deployment in the default Namespace, a ClusterIP service for port 80 of this workload, and add 8080=default/nginx-service:80 to the tcp-services ConfigMap in the ingress-nginx namespace.
3. Start a tcpdump on the single node in the downstream cluster `tcpdump -pni any port 80 or 8080`
4. Perform looping curl to the service `while true; do date --iso-8601=seconds && curl http://<downstream-node-ip>:8080/; done`
5. Scale down the nginx-deployment to 0.

**Result:**

Observe thousands of messages of the following format within timeframe of c. 1s:

```
2020-08-26T13:05:13.774467635Z 2020/08/26 13:05:13 [error] 112#112: *6226 connect() failed (111: Connection refused) while connecting to upstream, client: 156.67.130.73, server: 0.0.0.0:8080, upstream: "10.42.1.4:80", bytes from/to client:0/0, bytes from/to upstream:0/0
```
Before service marked as unavailable:
```
2020-08-26T13:05:17.001630840Z W0826 13:05:17.001409       6 controller.go:348] Service "default/nginx-service" does not have any active Endpoint for TCP port 80
```
The tcpdump will also show thousand of SYN packets from the ingress-nginx-controller to the upstream nginx Pod IP, which each receive a RST, ACK.

**Other details that may be helpful:**

The same behaviour is not shown if you test this but using a simple HTTP ingress Resource.

The upstream issue https://github.com/kubernetes/ingress-nginx/issues/5425 would appear relevant, and the linked nginx issue https://trac.nginx.org/nginx/ticket/2026. In the nginx issue it is asserted that the retries must be originating from the downstream client. However, my testing with packet captures indicates this is not the case and the very high number of requests originate from the ingress-nginx-controller itself after a single request from the client.

Attached is a PCAP ([nginx.zip](https://github.com/rancher/rancher/files/5155571/nginx.zip)) of the behaviour, alongside log collector output ([aseymour-rancheragent-all-0-2020-08-26_14_03_16.tar.gz](https://github.com/rancher/rancher/files/5155578/aseymour-rancheragent-all-0-2020-08-26_14_03_16.tar.gz) and [aseymour-rancheragent-all-1-2020-08-26_14_03_33.tar.gz](https://github.com/rancher/rancher/files/5155579/aseymour-rancheragent-all-1-2020-08-26_14_03_33.tar.gz)) from my reproducer lab. My client IP for the tests was 156.67.130.73, the host I tested connecting to was aseymour-rancheragent-all-0 IP 165.22.76.159, and the upstream nginx Pod IP during my test was 10.42.1.6.

The packet capture shows the a HTTP request in frame 2627, then between frames 2629 and 11804 over 4000 SYN packets sent from the node to the nginx upstream Pod, all receiving a RST, ACK, as a result of the now scaled down nginx Deployment. The nginx-ingress-controller Pod logs from the log collector output on the host, show the 1000s of Connection refused errors in the same window. 

**Environment information**
- I reproduced with Rancher v2.4.5, k8s v1.18.6, ingress-nginx v0.32.0
- User reported issue with Rancher v2.3.3, k8s v1.16.3, ingress-nginx v0.25.1

gz#11741

**Comment by axeal** [comment] 2020-11-11 14:07
Tested and observed the same behaviour with `rancher/nginx-ingress-controller:nginx-0.35.0-rancher2` and `k8s.gcr.io/ingress-nginx/controller:v0.41.0`

**Comment by Sahota1225** [comment] 2022-12-20 17:44
Team re-tested with Rancher v2.7.0 / downstream RKE v1.24.8-rancher1-1 / nginx-ingress-controller:nginx-1.2.1-rancher1 and could not reproduce the same behavior, so I think we can close this one out.

**Closed by Sahota1225** 2022-12-20 17:44 UTC
Labels: internal
