### ISSUE TITLE
Non-healthcheck enabled containers move to another host after host Power OFF

### ISSUE THREAD

**Issue by soumyalj** [rancher/rancher#10716] opened 2018-01-02 22:11 UTC
**Rancher versions:**
rancher/server:v1.6.12-flexvol
EBS driver Version: daishan1992/storage-ebs:dev

**Docker version: (`docker version`,`docker info` preferred)**1.12.6

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**Ubuntu

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**AWS

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**Single node

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**Cattle

**Steps to Reproduce:**
1. Create a setup with 3 hosts "h1, h2, h3" on AWS
2. Launch EBS catalog and create a ebs volume "testvol" from the UI storage tab
3. Create a non healthcheck enabled service "service1" of scale 3 using ebs volume "testvol"
4. Power OFF the host "h1" where service1 exists.

**Results:**
The containers are not healthcheck enabled, but they still move to another host. 
Why do non-healthcheck enabled containers move to a different host ?

**Comment by sangeethah** [comment] 2018-01-03 00:13
I see the same same behavior when testing with nfs driver as well . I see the containers being marked as "unhealthy" with following error message ```stopped (Post http://volume-plugin/VolumeDriver.Create: dial unix /var/run/rancher/storage/rancher-nfs.sock: connect: connection refused```

**Comment by StrongMonkey** [comment] 2018-01-11 17:09
I can confirm that non-healthcheck-enabled service can be moved to another host if the current host is disconnected. Not sure this is per design or not. @alena1108

**Comment by StrongMonkey** [comment] 2018-01-11 18:19
It might happen because of the race condition 
`here is only exception that I recall for non-healthcheck enabled instances. If the instance is in transitioning state (starting,stopping) at the moment host goes down, the instance will get removed.`

**Comment by soumyalj** [comment] 2018-01-30 19:27
See the similar behavior in v1.6.15.0-rc2. 
1. Create a setup with 3 hosts "h1, h2, h3" on AWS
2. Launch EBS catalog and create a ebs volume "testvol" from the UI storage tab
3. Create a non healthcheck enabled service "service1" of scale 3 using ebs volume "testvol"
4. Power OFF the host "h2" where service1 exists.

Two of the containers (are not healthcheck enabled), but they still try to move to another host.
The other container is still in running state on host 2

<img width="989" alt="screen shot 2018-01-31 at 12 45 51 am" src="https://user-images.githubusercontent.com/18536626/35586643-60b3d83e-0621-11e8-9824-c9dd0f3effd8.png">

Note: After the host is powered off, the service reconciles on the same host and the volume is still is accessible for read/write

**Comment by deniseschannon** [comment] 2018-02-01 18:52
@soumyalj when you tested, do you know if those containers were in starting or stopping state? were the `active` before testing?

**Comment by sangeethah** [comment] 2018-02-01 19:16
@denise This happens when containers are in "active" state.  This issue is also seen in nfs volume drivers.

**Comment by alena1108** [comment] 2018-03-12 22:46
@soumyalj @sangeethah I see that the agent reports the instance as stopped; then service reconcile just tries to restart/recreate it. The fact that it is constantly reproducible for instances with volumes attached, can probably be explained that when host gets disconnected, the connection to the volume gets lost, and the instance dies.Agent is still around, and can report it back to Rancher as stopped.

@deniseschannon I've cleaned up the milestone for this one, up to you whether we want to keep it open for a ref.

**Closed** 2018-08-21 21:43 UTC
Labels: area/storage, kind/question, status/autoclosed, status/reopened, version/1.6
