### ISSUE TITLE
Rancher 2.0 memory gauge always wrong

### ISSUE THREAD

**Issue by wzrdtales** [rancher/rancher#13681] opened 2018-05-24 07:59 UTC
![image](https://user-images.githubusercontent.com/1786821/40472192-07d77bbe-5f39-11e8-9ba8-9cd76ca6ac00.png)

For some reason rancher 2.0 in this setup can't detect the used memory of the server correctly. Good half of the memory is consumed in reality, still does not show up.

This is provisioned bare metal and this is a single server setup, everything including rancher runs for this test setup on a single machine.

**Comment by tfiduccia** [comment] 2018-05-24 23:21
Duplicate of #13583

**Closed by tfiduccia** 2018-05-24 23:21 UTC
