### ISSUE TITLE
convoy UI not create volume

### ISSUE THREAD

**Issue by galindro** [rancher/rancher#3312] opened 2016-01-17 22:59 UTC
I'm trying to create a convoy-gluster volume through UI but, after the creation, no volumes are listed:

![image](https://cloud.githubusercontent.com/assets/4622097/12380540/674d3740-bd5c-11e5-88d3-5011ff7c1382.png)

There are no error messages. It simply does't show created volumes and I don't know if they are effectively created on storage pool.

I'm using RancherOS 0.4.2 on my host and on the virtual machine that rancher server is running.

What logs do you want to help the analysis?

**Comment by deniseschannon** [comment] 2016-01-19 04:46
Have you tried refreshing? You could also look in the API. To check if they exist, you can go to the endpoint for your environment by going to the dropdown in your avatar and selecting API&Keys. Click on that endpoint and search for volumes. Click on volumes. You should be able to see any of the volumes that you have created. 

Note: Volumes are only showing up when they are actually mounted in a service/container. This will change in the next release of Rancher.

**Comment by sshipway** [comment] 2016-01-19 22:44
Exactly the same problem for me.

I have upgraded all hosts (including the Rancher-Server host) to Docker 1.9.1, CoreOS 899, and running Rancher-Server 0.51

Checking via the API, I can see (and remove) the old orphaned storage pools.  However there are no volumes listed for the convoy-nfs storage pool (I am using NFS for testing but I get the same problems when using Convoy-gluster as well).  Also, I cannot remove orphaned storage pools from the UI ( #3171 or #2893  I think)

However, if I try to create a new volume called 'test', then the UI tells me "Validation failed in API: name is not unique" as I previously used this.  Try with a different name, and I get no error message, but no volume appears in the UI. #2796 maybe, or #2822 - if so, should be fixed in next version.

If I create a new container, mounting 'test:/mnt', then it does in fact mount the test subdir under the Convoy-NFS mount; however there is still nothing in the Storage Pool UI.

Hopefully this will work more clearly under 0.55 when it is released.

**Comment by galindro** [comment] 2016-01-25 09:22
I could confirm what @sshipway said about the API.

**Comment by sshipway** [comment] 2016-01-25 21:21
I've tried 0.56-rc1 and it seems to fix the issue.  Very strangely, after revering to 0.51, the volumes are displayed corretcly!  I suspect 0.51 omitted setting something up in the database that 0.56 fixed.  However, in the process of going back the convoy-gluster stack was somehow borken and needed to be recreated (though the volumes were not deleted in the process)
I'm not moving to a *-rc version for stability reasons, so waiting for the next non-rc release.

**Comment by sshipway** [comment] 2016-01-27 22:44
0.56.0 fixed the issue... but brought in the networking problems.

Strangely, 0.56.1 fixed the network problems, but now we're back to the invisible storage volumes.

**Comment by deniseschannon** [comment] 2016-01-27 22:45
@sshipway Did you also update your template to the v0.2 of the template for convoy-gluster? There were some internal changes between the versions that required a template change as well for convoy-gluster.

**Comment by sshipway** [comment] 2016-01-27 22:49
@deniseschannon - Yes; in fact I re-created the convoy-nfs setup (we use NFS, not gluster).  The mounts work from containers, and I cannot create new volumes with the new names, but the volumes are not shown in the UI.  Under 0.56.0 they were shown, for some reason.
I don't know if this is related to the hostname change issue which came along at the same time?

**Comment by deniseschannon** [comment] 2016-02-02 21:14
@galindro It looks like you were hitting a duplicate of this: https://github.com/rancher/rancher/issues/2763 Also, we added a new template of convoy-gluster and in conjunction with v0.56.1 you should only be hitting the duplicate. There were some other known issues in v0.51.0 with storage pools and UI, but have been resolved with v0.56.1 and the new template of convoy-gluster.

@sshipway Just to confirm, you were using the new template (v2) of convoy-nfs? When you say you cannot create new volumes, are you trying the "Add Volume" from the UI. If so, you might be hitting the same bug and need to just refresh.

Note: I am actually running a v0.57.0-rcx version, but I believe it should be the same in v0.56.1.

**Comment by sshipway** [comment] 2016-02-02 22:41
I am using v0.2 of the convoy-nfs.template.

Creating new volumes using the 'Add volume' the volume is invisible until I refresh; then it appears as 'requested'.

Creating a new volume by creating a container with a convoy-nfs driver and mapping of 'testvol:/mnt' creates the directory i nthe NFS but it is not visible in the UI.

There are a large number of defined volumes (from previous tests) visible in the API, which are not present on disk and not visible in the UI ever, yet prevent me from creating volumes with the same name via 'Add volume'.

**Comment by deniseschannon** [comment] 2016-02-09 20:09
@sshipway I don't have a NFS setup, but I tried with convoy-gluster and I am able to reproduce the fact that volumes don't show up until I refresh for both when you add the volume from the storage pool page and when creating a container with the convoy-gluster driver. 

These are actually duplicates of https://github.com/rancher/rancher/issues/2763

But to just confirm, even after a refresh, were the volumes visible in the UI? I'd like to close this issue in favor of 2763

As for the large number of defined volumes, we should open a separate issue to track that as it's a different issue.

**Comment by sshipway** [comment] 2016-02-09 20:53
After a refresh, the volumes created from the UI were visible.  However the volumes that were created implicitly by mounting a not-yet-existing volume from a new container do not appear (though they work).

**Comment by cjellick** [comment] 2016-03-10 20:36
@vincent99 Looks like you are not including storagePools in the subscribe. When I added that to the subscribe URL in my little ws client, I got an event when I added the volume.

**Comment by deniseschannon** [comment] 2016-07-19 03:25
In v1.1.0, I am unable to reproduce this issue. When a volume was created using convoy-gluster, I was able to see the volume in the storage pool page without the need of a refresh.

**Closed by deniseschannon** 2016-07-19 03:25 UTC
Labels: area/storage, area/ui, kind/bug

**Comment by arkka** [comment] 2016-08-05 22:17
Hi,

I'm in v1.1.2 with Docker v1.10.3 using convoy-nfs still getting this UI problem.

After creating new volume, nothing happen. After refreshing the page, the volume appear but as "requested".

**Comment by elevy411** [comment] 2016-08-18 21:36
^ I have the same issue as arkka. I create volumes through the UI after reading the blog post today (08/18) and when i create volumes, they show up as requested. 

Any help would be great!

**Comment by deniseschannon** [comment] 2016-08-19 05:08
The volumes are in requested state, but not in an active state until it's actually used by a service.

**Comment by elevy411** [comment] 2016-08-19 15:32
Thank you! That would be really useful information to append to the blog post. All is working as intended now. 

On a related note, is it possible to scale the docker-nfs server to increase its resilience? Ie: have multiple containers running it so if one goes down all the data isn't lost?

**Comment by arkka** [comment] 2016-08-20 07:45
@deniseschannon thank you!
In my case, i didn't type correctly my storage pool name therefore the storage is not change to active from requested.. and i thought something wrong with the storage side (my bad).
Is it possible on the storage driver input UI using a dropdown that populate from existing storage pool instead of free input text? to avoid this kind silly mistake.

**Comment by cjellick** [comment] 2016-08-22 16:26
@arkka the reason it is a text box is because users might have other docker volume plugins installed that rancher doesnt know about, so they need a free form field. That said, maybe it can be a dropdown plus an "Other" option that then gives a textbox.

Paging @vincent99 for UI expertise.
