### ISSUE TITLE
Support for running `cattle-cluster-agent` with trace logging

### ISSUE THREAD

**Issue by snasovich** [rancher/rancher#42241] opened 2023-07-26 19:43 UTC
**Is your feature request related to a problem? Please describe.**
Currently, it's easy to run `cattle-cluster-agent` with debug-level logging by setting `CATTLE_DEBUG` or `RANCHER_DEBUG` env var to `true`, see https://github.com/rancher/rancher/blob/67422772955d5830b237fe84dbf1a26d266b55c1/cmd/agent/main.go#L60-L62

However, running with trace-level logging is not directly supported.

**Describe the solution you'd like**
Following the established pattern it's suggested to add support for `CATTLE_TRACE`/`RANCHER_TRACE` env vars to enable trace logging for `cattle-cluster-agent`.

**Describe alternatives you've considered**
As an alternative it's already possible to exec into running agent container and run `loglevel --set trace` to set logging level to trace; however:
* This is less than trivial and is only temporary
* In case trace-level logging is needed for the initial startup of the agent, some solution to execute it prior to starting the agent needs to be figured out (not immediately obvious how it will work but likely possible)
* This sets the log level to trace globally for the container, not just for the agent executable

**Additional context**
While at it, we also want to explicitly document setting logging for `cattle-cluster-agent` on https://ranchermanager.docs.rancher.com/troubleshooting/other-troubleshooting-tips/logging as it's missing that information.

**Comment by felipe-colussi** [comment] 2023-07-31 15:52
Merged on https://github.com/rancher/rancher/pull/42252

**Comment by felipe-colussi** [comment] 2023-07-31 17:16
## Validation Template

## Root Cause

We had no way of setting the trace-level for rancher-agent . 

## What was fixed, or what change have occurred

Now is possible to to add trace-level using   Agent Environment Vars. 
 `CATTLE_TRACE` or `RANCHER_TRACE` must be  set to `true`

## Areas or cases that should be tested


- Create a new cluster with the Envs set. 

## What areas could experience regressions

None. 

## Are the repro steps accurate/minimal?

Create new cluster setting  `CATTLE_TRACE` or `RANCHER_TRACE`  to `true`.
run `kubectl logs {podname}  -n cattle-system` Trace and debug level logs must appear.

**Closed** 2023-08-01 16:14 UTC
Labels: kind/enhancement, area/agent, [zube]: QA Working, QA/S, team/area2
