### ISSUE TITLE
[monitoring v2 RBAC] UI role `view monitoring` and k8s clusterRoleBinding `monitoring-ui-view` do not have the same permissions

### ISSUE THREAD

**Issue by slickwarren** [rancher/rancher#35311] opened 2021-10-28 16:26 UTC
**Rancher Server Setup**
- Rancher version: 2.6.2, 2.5.10
- Installation option (Docker install/Helm Chart): docker
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc):n/a
- Proxy/Cert Details:n/a

**Information about the Cluster**
- Kubernetes version:any
- Cluster Type (Local/Downstream):downstream
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider):any

**Describe the bug**

The UI role `view monitoring` and k8s clusterRoleBinding `monitoring-ui-view` do not have the same permissions; users added with the UI option `view monitoring` have access  to view monitoring, but users added via k8s do not 

**To Reproduce**
 
* deploy a downstream cluster with monitoring installed in the system project
* create 2 users, u1 and u2
* for u1, via the old cluster management UI, give the user `view monitoring` role in the system project, and make them a project member of the default project
* for u2, run the following `kubectl create clusterrolebinding test1 --clusterrole monitoring-ui-view --user your-user-id`, and make them a project member of the default project

**Result**
both users can access a link directly to grafana from the setup, however U2 has the UI for grafana/prometheus greyed out in rancher UI, while U1 can access the links through the UI. 

**Expected Result**

both users should be able to access the UI for monitoring.

**Screenshots**

**Additional context**

**Comment by aiyengar2** [comment] 2022-01-25 22:17
Considering the additional details listed in https://github.com/rancher/dashboard/issues/4466, it seems like the fix for this issue might be to provide the ability to list endpoints for the Monitoring-related services as part of this ClusterRole:

https://github.com/rancher/charts/blob/4a6d30516febbf07446575ccd3e2bdf804b60cea/charts/rancher-monitoring/100.1.0%2Bup19.0.3/templates/rancher-monitoring/clusterrole.yaml#L101-L129

It's possible / likely that on adding a user via the Rancher UI, the user ends up inheriting `View Services` permissions: https://github.com/rancher/rancher/blob/e96794b42d7c1d70cacfc3f2e9d37db1ec04daf5/pkg/data/management/role_data.go#L382-L383

This would allow them to see endpoints and not receive a 403, which would also resolve the vanilla k8s issue we are seeing here.

**Comment by Tejeev** [comment] 2022-02-14 20:21
Do we have any idea when this will hit?  I've got a lot of customers waiting on it and atm 2 that care enough to maintain open tickets. It's important to their user access and permissions and so is really a security consideration.

**Comment by gaktive** [comment] 2022-03-14 16:15
Internal reference: SURE-4075

**Comment by MKlimuszka** [comment] 2023-01-23 18:14
This needs to be reproduced in 2023-Q1-2.6x and 2023-Q1-2.7x, and if it can't be reproduced in those, then 2.6.9

**Comment by prachidamle** [comment] 2023-04-06 07:22
@nflynt Can you try and reproduce this in the versions noted above

**Comment by torchiaf** [comment] 2023-12-18 08:46
Is this one related to https://github.com/rancher/dashboard/issues/4466 ? It seems to be same issue.

**Closed** 2024-06-17 22:01 UTC
Labels: internal, kind/bug-qa, area/monitoring, status/to-reproduce, feature/charts-monitoring-v2, LoE/3, JIRA, team/observability&backup
