### ISSUE TITLE
Give the option to pull docker images before stopping/recreating containers when upgrading stacks

### ISSUE THREAD

**Issue by aemneina** [rancher/rancher#7291] opened 2017-01-04 18:59 UTC
**Rancher Version:**
1.2.2

upgrading stacks can be unpredictable at times in terms of maintenance windows. doing this can shrink the downtime significantly when cutting over (stopping container and starting a new one).

**Comment by chauffer** [comment] 2017-01-05 11:11
Duplicate of #7200

**Comment by will-chan** [comment] 2017-02-21 18:29
Using #7200 to track this enhancement.

**Closed by will-chan** 2017-02-21 18:29 UTC
Labels: priority/-1
