### ISSUE TITLE
websocket-proxy fails to start if options "edns0" or "single-request-reopen" are present in resolv.conf

### ISSUE THREAD

**Issue by robdewit** [rancher/rancher#6487] opened 2016-11-02 12:29 UTC
**Rancher Version:**
1.2.0-pre4-rc6 and any other starting with 1.1.4

**Docker Version:**
1.11.2 and 1.12.1

**OS and where are the hosts located? (cloud, bare metal, etc):**
Bare metal Linux, kernel 4.4.14 x86_64

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
Fails at starting server

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
N/A

**Steps to Reproduce:**
docker run -v /var/run/docker.sock:/var/run/docker.sock --name rancher -d   rancher/server:v1.2.0-pre4-rc6

**Results:** 
Stack trace just after "Downloading certificate from http://localhost:8081/v1/credentials/1c1/certificate" and then continuously after "Waiting for handler registration (1/2)"

**Expected:**
A running rancher server

Stack trace attached [rancher-stackdump.txt](https://github.com/rancher/rancher/files/566480/rancher-stackdump.txt)
Cattle debug file attached [cattle-debug.txt](https://github.com/rancher/rancher/files/566570/cattle-debug.txt)
strace output for websocket-proxy (made with `ps aux | grep websocket | grep -v grep | awk '{print "echo "$2"; strace -s1000 -f -p "$2; }')`  [strace_websocket-proxy.txt](https://github.com/rancher/rancher/files/566748/strace_websocket-proxy.txt)

`

Base OS has a unusual ethernet configuration that might be the cause: two NICs linked together using bonding kernel interface with vlan aliases on top of that (public IP is on vlan200):

```
2: eth0: <BROADCAST,MULTICAST,SLAVE,UP,LOWER_UP> mtu 9000 qdisc pfifo_fast master bond0 state UP qlen 1000
    link/ether xx:xx:xx:xx:xx:xx brd ff:ff:ff:ff:ff:ff
3: eth1: <BROADCAST,MULTICAST,SLAVE,UP,LOWER_UP> mtu 9000 qdisc pfifo_fast master bond0 state UP qlen 1000
    link/ether xx:xx:xx:xx:xx:xx brd ff:ff:ff:ff:ff:ff
4: bond0: <BROADCAST,MULTICAST,MASTER,UP,LOWER_UP> mtu 9000 qdisc noqueue state UP qlen 1000
    link/ether xx:xx:xx:xx:xx:xx brd ff:ff:ff:ff:ff:ff
6: vlan100@bond0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 9000 qdisc noqueue state UP qlen 1000
    link/ether xx:xx:xx:xx:xx:xx brd ff:ff:ff:ff:ff:ff
    inet 10.x.y.z/22 scope global vlan100
       valid_lft forever preferred_lft forever
7: vlan200@bond0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP qlen 1000
    link/ether xx:xx:xx:xx:xx:xx brd ff:ff:ff:ff:ff:ff
    inet a.b.c.d/m scope global vlan200
       valid_lft forever preferred_lft forever
```

**Comment by revog** [comment] 2016-11-14 14:28
Hello. I have exactly the same problem with Rancher 1.1.4 on Docker v1.10-1-12. Older Rancher versions like 1.0.2 work like a charm.
Any findings to solve the problem?

**Comment by robdewit** [comment] 2016-11-14 16:09
@revog I have no solution yet, but could you confirm that you may also have a non-standard network configuration on the host server?

**Comment by revog** [comment] 2016-11-18 12:00
@robdewit What do you mean by "non-standard network configuration"? We have set a static IP, that's it...

**Comment by revog** [comment] 2016-11-18 13:26
@robdewit Solved on my side :). I did a new server install and then it worked without any problems. After I've run our Ansible recipes, it was broken again. So I did a diff (with snapper) and stumbled over the `single-request-reopen` option in /etc/resolv.conf. In our default config this parameter is beeing set. After removing this part and restarting the container - everything worked as expected. 
The man page says:

> single-request-reopen (since glibc 2.9)
                     Sets RES_SNGLKUPREOP in _res.options.  The resolver
                     uses the same socket for the A and AAAA requests.  Some
                     hardware mistakenly sends back only one reply.  When
                     that happens the client system will sit and wait for
                     the second reply.  Turning this option on changes this
                     behavior so that if two requests from the same port are
                     not handled correctly it will close the socket and open
                     a new one before sending the second request.

I can't say why this parameter has such a big influence on these crashes inside the container. But maybe that's a solution for you aswell...

**Comment by robdewit** [comment] 2016-11-21 08:25
@revog Thanks for sharing your findings. Turns out for me it indeed was resolv.conf, but for me it was the "edns0" option that yields endless restarting of the websocket-proxy.

**Comment by kaos** [comment] 2017-03-08 09:15
This seems to also apply to the scheduler service (and possibly others as well), which crashes regularly with this stack trace when we have the `single-request-reopen` option present in resolv.conf (on rhel 7):

```
fatal error: unexpected signal during runtime execution
[signal 0xb code=0x1 addr=0x63 pc=0x7f69bcc38259]

runtime stack:
runtime.throw(0xb35e40, 0x2a)
	/usr/local/go/src/runtime/panic.go:547 +0x90
runtime.sigpanic()
	/usr/local/go/src/runtime/sigpanic_unix.go:12 +0x5a

goroutine 194 [syscall, locked to thread]:
runtime.cgocall(0x7b6610, 0xc820127bd8, 0x0)
	/usr/local/go/src/runtime/cgocall.go:123 +0x11b fp=0xc820127b78 sp=0xc820127b48
net._C2func_getaddrinfo(0x7f69680008c0, 0x0, 0xc820269950, 0xc8200584d8, 0x0, 0x0, 0x0)
	??:0 +0x55 fp=0xc820127bd8 sp=0xc820127b78
net.cgoLookupIPCNAME(0xc820234060, 0x10, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0xb96700)
	/usr/local/go/src/net/cgo_unix.go:111 +0x448 fp=0xc820127d50 sp=0xc820127bd8
net.cgoLookupIP(0xc820234060, 0x10, 0x0, 0x0, 0x0, 0x0, 0x0, 0xc82014e118)
	/usr/local/go/src/net/cgo_unix.go:163 +0x56 fp=0xc820127da8 sp=0xc820127d50
net.lookupIP(0xc820234060, 0x10, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/lookup_unix.go:67 +0x94 fp=0xc820127e18 sp=0xc820127da8
net.glob.func16(0xb96818, 0xc820234060, 0x10, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/hook.go:10 +0x4d fp=0xc820127e58 sp=0xc820127e18
net.lookupIPDeadline.func1(0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/lookup.go:106 +0x71 fp=0xc820127ed8 sp=0xc820127e58
internal/singleflight.(*Group).doCall(0xf8a380, 0xc8201444b0, 0xc820234060, 0x10, 0xc8202340e0)
	/usr/local/go/src/internal/singleflight/singleflight.go:93 +0x2c fp=0xc820127f88 sp=0xc820127ed8
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1998 +0x1 fp=0xc820127f90 sp=0xc820127f88
created by internal/singleflight.(*Group).DoChan
	/usr/local/go/src/internal/singleflight/singleflight.go:86 +0x3ee

goroutine 1 [chan receive]:
main.run(0xc8200d6280, 0x0, 0x0)
	/go/src/github.com/rancher/scheduler/main.go:85 +0x66b
reflect.Value.call(0x8ccfe0, 0xb966b8, 0x13, 0xa77ef0, 0x4, 0xc820079ab0, 0x1, 0x1, 0x0, 0x0, ...)
	/usr/local/go/src/reflect/value.go:435 +0x120d
reflect.Value.Call(0x8ccfe0, 0xb966b8, 0x13, 0xc820079ab0, 0x1, 0x1, 0x0, 0x0, 0x0)
	/usr/local/go/src/reflect/value.go:303 +0xb1
github.com/rancher/scheduler/vendor/github.com/urfave/cli.HandleAction(0x8ccfe0, 0xb966b8, 0xc8200d6280, 0x0, 0x0)
	/go/src/github.com/rancher/scheduler/vendor/github.com/urfave/cli/app.go:481 +0x2ee
github.com/rancher/scheduler/vendor/github.com/urfave/cli.(*App).Run(0xc82008e780, 0xc82009e160, 0x1, 0x1, 0x0, 0x0)
	/go/src/github.com/rancher/scheduler/vendor/github.com/urfave/cli/app.go:240 +0xb05
main.main()
	/go/src/github.com/rancher/scheduler/main.go:44 +0x2ce

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1998 +0x1

goroutine 20 [chan receive]:
github.com/rancher/scheduler/vendor/github.com/rancher/event-subscriber/locks.locker()
	/go/src/github.com/rancher/scheduler/vendor/github.com/rancher/event-subscriber/locks/locks.go:95 +0xe9
created by github.com/rancher/scheduler/vendor/github.com/rancher/event-subscriber/locks.init.1
	/go/src/github.com/rancher/scheduler/vendor/github.com/rancher/event-subscriber/locks/locks.go:6 +0x2b

goroutine 21 [IO wait]:
net.runtime_pollWait(0x7f69bdff5b90, 0x72, 0xc820354000)
	/usr/local/go/src/runtime/netpoll.go:160 +0x60
net.(*pollDesc).Wait(0xc820098220, 0x72, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:73 +0x3a
net.(*pollDesc).WaitRead(0xc820098220, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:78 +0x36
net.(*netFD).Read(0xc8200981c0, 0xc820354000, 0x1000, 0x1000, 0x0, 0x7f69bdfec028, 0xc82009e0a0)
	/usr/local/go/src/net/fd_unix.go:250 +0x23a
net.(*conn).Read(0xc8200584a0, 0xc820354000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/net.go:172 +0xe4
bufio.(*Reader).fill(0xc820180ae0)
	/usr/local/go/src/bufio/bufio.go:97 +0x1e9
bufio.(*Reader).Read(0xc820180ae0, 0xc82048c1c8, 0x2, 0x8, 0xc82011e4e0, 0x0, 0x0)
	/usr/local/go/src/bufio/bufio.go:207 +0x260
github.com/rancher/scheduler/vendor/github.com/gorilla/websocket.(*Conn).readFull(0xc8202aa0f0, 0xc82048c1c8, 0x2, 0x8, 0x0, 0x0)
	/go/src/github.com/rancher/scheduler/vendor/github.com/gorilla/websocket/conn.go:546 +0xa9
github.com/rancher/scheduler/vendor/github.com/gorilla/websocket.(*Conn).advanceFrame(0xc8202aa0f0, 0x452c10, 0x0, 0x0)
	/go/src/github.com/rancher/scheduler/vendor/github.com/gorilla/websocket/conn.go:570 +0x159
github.com/rancher/scheduler/vendor/github.com/gorilla/websocket.(*Conn).NextReader(0xc8202aa0f0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/go/src/github.com/rancher/scheduler/vendor/github.com/gorilla/websocket/conn.go:705 +0x76
github.com/rancher/scheduler/vendor/github.com/gorilla/websocket.(*Conn).ReadMessage(0xc8202aa0f0, 0xc82011e4e0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/go/src/github.com/rancher/scheduler/vendor/github.com/gorilla/websocket/conn.go:768 +0x55
github.com/rancher/scheduler/vendor/github.com/rancher/event-subscriber/events.(*EventRouter).run(0xc820290320, 0x7f69bf8327e0, 0xc8202f4380, 0x0, 0x0, 0x0, 0x0, 0x0)
	/go/src/github.com/rancher/scheduler/vendor/github.com/rancher/event-subscriber/events/listener.go:139 +0x916
github.com/rancher/scheduler/vendor/github.com/rancher/event-subscriber/events.(*EventRouter).RunWithWorkerPool(0xc820290320, 0x7f69bf8327e0, 0xc8202f4380, 0x0, 0x0)
	/go/src/github.com/rancher/scheduler/vendor/github.com/rancher/event-subscriber/events/listener.go:97 +0x56
github.com/rancher/scheduler/events.ConnectToEventStream(0xc82001004b, 0x15, 0xc82000e042, 0x14, 0xc820012052, 0x28, 0xc8200a3020, 0x0, 0x0)
	/go/src/github.com/rancher/scheduler/events/listener.go:30 +0x51d
main.run.func1(0xc82001004b, 0x15, 0xc82000e042, 0x14, 0xc820012052, 0x28, 0xc8200a3020, 0xc82009c420)
	/go/src/github.com/rancher/scheduler/main.go:71 +0x70
created by main.run
	/go/src/github.com/rancher/scheduler/main.go:73 +0x5bd

goroutine 22 [select]:
net/http.(*Transport).getConn(0xc8200a00c0, 0xc8203787e0, 0x0, 0xc8200985b0, 0x4, 0xc820234060, 0x13, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/http/transport.go:711 +0x4ef
net/http.(*Transport).RoundTrip(0xc8200a00c0, 0xc8203787e0, 0xc8200a00c0, 0x0, 0x0)
	/usr/local/go/src/net/http/transport.go:311 +0x7e9
net/http.send(0xc820378700, 0x7f69bdff46b8, 0xc8200a00c0, 0xed051c0c5, 0x23c40aaf, 0xf8af20, 0xc820098690, 0x0, 0x0)
	/usr/local/go/src/net/http/client.go:260 +0x6b7
net/http.(*Client).send(0xc8200a30e0, 0xc820378700, 0xed051c0c5, 0x23c40aaf, 0xf8af20, 0x411867, 0x0, 0x0)
	/usr/local/go/src/net/http/client.go:155 +0x185
net/http.(*Client).doFollowingRedirects(0xc8200a30e0, 0xc820378700, 0xb96a40, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/http/client.go:475 +0x8a4
net/http.(*Client).Do(0xc8200a30e0, 0xc820378700, 0x6, 0x0, 0x0)
	/usr/local/go/src/net/http/client.go:188 +0xff
github.com/rancher/scheduler/vendor/github.com/rancher/go-rancher-metadata/metadata.(*client).SendRequest(0xc8200a30b0, 0xc820144460, 0x49, 0x0, 0x0, 0x0, 0x0, 0x0)
	/go/src/github.com/rancher/scheduler/vendor/github.com/rancher/go-rancher-metadata/metadata/metadata.go:72 +0x18e
github.com/rancher/scheduler/vendor/github.com/rancher/go-rancher-metadata/metadata.(*client).waitVersion(0xc8200a30b0, 0x5, 0xc82042e330, 0x26, 0x0, 0x0, 0x0, 0x0)
	/go/src/github.com/rancher/scheduler/vendor/github.com/rancher/go-rancher-metadata/metadata/change.go:53 +0x21e
github.com/rancher/scheduler/vendor/github.com/rancher/go-rancher-metadata/metadata.(*client).onChangeFromVersionWithError(0xc8200a30b0, 0xc82042e330, 0x26, 0x5, 0xc82011a060, 0x0, 0x0)
	/go/src/github.com/rancher/scheduler/vendor/github.com/rancher/go-rancher-metadata/metadata/change.go:17 +0x81
github.com/rancher/scheduler/vendor/github.com/rancher/go-rancher-metadata/metadata.(*client).OnChangeWithError(0xc8200a30b0, 0x5, 0xc82011a060, 0x0, 0x0)
	/go/src/github.com/rancher/scheduler/vendor/github.com/rancher/go-rancher-metadata/metadata/change.go:12 +0x56
github.com/rancher/scheduler/resourcewatchers.WatchMetadata(0x7f69bdff4b60, 0xc8200a30b0, 0x7f69bf82f028, 0xc8200a3020, 0x0, 0x0)
	/go/src/github.com/rancher/scheduler/resourcewatchers/metadata.go:24 +0x1c2
main.run.func2(0x7f69bdff4b60, 0xc8200a30b0, 0xc8200a3020, 0xc82009c420)
	/go/src/github.com/rancher/scheduler/main.go:76 +0x67
created by main.run
	/go/src/github.com/rancher/scheduler/main.go:78 +0x603

goroutine 23 [IO wait]:
net.runtime_pollWait(0x7f69bdff5c50, 0x72, 0x0)
	/usr/local/go/src/runtime/netpoll.go:160 +0x60
net.(*pollDesc).Wait(0xc8200981b0, 0x72, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:73 +0x3a
net.(*pollDesc).WaitRead(0xc8200981b0, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:78 +0x36
net.(*netFD).accept(0xc820098150, 0x0, 0x7f69bdff5d48, 0xc82024ff00)
	/usr/local/go/src/net/fd_unix.go:426 +0x27c
net.(*TCPListener).AcceptTCP(0xc8200a8030, 0x452c10, 0x0, 0x0)
	/usr/local/go/src/net/tcpsock_posix.go:254 +0x4d
net/http.tcpKeepAliveListener.Accept(0xc8200a8030, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/http/server.go:2427 +0x41
net/http.(*Server).Serve(0xc8200ae200, 0x7f69bdff5d10, 0xc8200a8030, 0x0, 0x0)
	/usr/local/go/src/net/http/server.go:2117 +0x129
net/http.(*Server).ListenAndServe(0xc8200ae200, 0x0, 0x0)
	/usr/local/go/src/net/http/server.go:2098 +0x136
net/http.ListenAndServe(0xc82009f150, 0x3, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/http/server.go:2195 +0x98
main.startHealthCheck(0x50, 0x0, 0x0)
	/go/src/github.com/rancher/scheduler/main.go:95 +0x23a
main.run.func3(0xc8200d6280, 0xc82009c420)
	/go/src/github.com/rancher/scheduler/main.go:81 +0x48
created by main.run
	/go/src/github.com/rancher/scheduler/main.go:83 +0x632

goroutine 41 [select]:
github.com/rancher/scheduler/vendor/github.com/rancher/event-subscriber/events.(*pongHandler).startTimer(0xc8201ba0f0, 0x1388, 0x2710)
	/go/src/github.com/rancher/scheduler/vendor/github.com/rancher/event-subscriber/events/websocket_pings.go:60 +0x449
created by github.com/rancher/scheduler/vendor/github.com/rancher/event-subscriber/events.newPongHandler
	/go/src/github.com/rancher/scheduler/vendor/github.com/rancher/event-subscriber/events/websocket_pings.go:44 +0x160

goroutine 7 [IO wait]:
net.runtime_pollWait(0x7f69bdff5ad0, 0x72, 0xc8201ce000)
	/usr/local/go/src/runtime/netpoll.go:160 +0x60
net.(*pollDesc).Wait(0xc82019a1b0, 0x72, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:73 +0x3a
net.(*pollDesc).WaitRead(0xc82019a1b0, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:78 +0x36
net.(*netFD).Read(0xc82019a150, 0xc8201ce000, 0x1000, 0x1000, 0x0, 0x7f69bdfec028, 0xc82009e0a0)
	/usr/local/go/src/net/fd_unix.go:250 +0x23a
net.(*conn).Read(0xc820058488, 0xc8201ce000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/net.go:172 +0xe4
net/http.noteEOFReader.Read(0x7f69bf832598, 0xc820058488, 0xc820196138, 0xc8201ce000, 0x1000, 0x1000, 0x4062d3, 0x0, 0x0)
	/usr/local/go/src/net/http/transport.go:1687 +0x67
net/http.(*noteEOFReader).Read(0xc820010300, 0xc8201ce000, 0x1000, 0x1000, 0xc82006ad1d, 0x0, 0x0)
	<autogenerated>:284 +0xd0
bufio.(*Reader).fill(0xc820180720)
	/usr/local/go/src/bufio/bufio.go:97 +0x1e9
bufio.(*Reader).Peek(0xc820180720, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/bufio/bufio.go:132 +0xcc
net/http.(*persistConn).readLoop(0xc8201960d0)
	/usr/local/go/src/net/http/transport.go:1073 +0x177
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:857 +0x10a6

goroutine 42 [chan receive]:
github.com/rancher/scheduler/vendor/github.com/rancher/event-subscriber/events.(*EventRouter).sendWebsocketPings(0xc820290320)
	/go/src/github.com/rancher/scheduler/vendor/github.com/rancher/event-subscriber/events/websocket_pings.go:27 +0xe8
created by github.com/rancher/scheduler/vendor/github.com/rancher/event-subscriber/events.(*EventRouter).run
	/go/src/github.com/rancher/scheduler/vendor/github.com/rancher/event-subscriber/events/listener.go:136 +0x901

goroutine 192 [select]:
net/http.setRequestCancel.func4(0x0, 0xc820269890, 0xc82009afc0, 0xc82014e600)
	/usr/local/go/src/net/http/client.go:333 +0x12e
created by net/http.setRequestCancel
	/usr/local/go/src/net/http/client.go:341 +0x2f7

goroutine 8 [select]:
net/http.(*persistConn).writeLoop(0xc8201960d0)
	/usr/local/go/src/net/http/transport.go:1277 +0x472
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:858 +0x10cb

goroutine 193 [select]:
net.lookupIPDeadline(0xc820234060, 0x10, 0xed051c0d9, 0x23c4bc18, 0xf8af20, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/lookup.go:109 +0x6a6
net.internetAddrList(0xa7c4b8, 0x3, 0xc820234060, 0x13, 0xed051c0d9, 0x23c4bc18, 0xf8af20, 0x0, 0x0, 0x0, ...)
	/usr/local/go/src/net/ipsock.go:252 +0x6ee
net.resolveAddrList(0xa7a410, 0x4, 0xa7c4b8, 0x3, 0xc820234060, 0x13, 0xed051c0d9, 0x23c4bc18, 0xf8af20, 0x0, ...)
	/usr/local/go/src/net/dial.go:158 +0x466
net.(*Dialer).Dial(0xc8200ac3c0, 0xa7c4b8, 0x3, 0xc820234060, 0x13, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/dial.go:216 +0x124
net.(*Dialer).Dial-fm(0xa7c4b8, 0x3, 0xc820234060, 0x13, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/http/transport.go:38 +0x6e
net/http.(*Transport).dial(0xc8200a00c0, 0xa7c4b8, 0x3, 0xc820234060, 0x13, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/http/transport.go:659 +0x96
net/http.(*Transport).dialConn(0xc8200a00c0, 0x0, 0xc8200985b0, 0x4, 0xc820234060, 0x13, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/http/transport.go:762 +0x1e3d
net/http.(*Transport).getConn.func4(0xc8200a00c0, 0x0, 0xc8200985b0, 0x4, 0xc820234060, 0x13, 0xc82014e6c0)
	/usr/local/go/src/net/http/transport.go:706 +0x66
created by net/http.(*Transport).getConn
	/usr/local/go/src/net/http/transport.go:708 +0x262
```

Now that we have found it, it's an easy fix to remove, but it has caused a lot of pain as it was hard to find.

It feels like an easy fix would be to prune the resolv.conf on options that are unstable before using them in the service containers.. makes me a bit sad that this has been a known issue for so long, and still not being addressed.

**Comment by niusmallnan** [comment] 2017-04-14 08:22
Golang use glibc to do some dns resolv as default, but golang use go routine and glibc use system thread.
Sometimes they can not work fine together.
So we need to add CGO_ENABLED=0 before go build.

**Comment by deniseschannon** [comment] 2017-04-17 19:24
This is actually a duplicate of https://github.com/rancher/rancher/issues/6111 and I'll close in favor of that.

**Closed by deniseschannon** 2017-04-17 19:24 UTC
Labels: area/packaging, kind/bug
