### ISSUE TITLE
rancher-monitoring/Prometheus: claim.Spec.Selector is not supported for dynamic provisioning on vSphere

### ISSUE THREAD

**Issue by tompatib** [rancher/rancher#29755] opened 2020-10-26 10:59 UTC
**What kind of request is this (question/bug/enhancement/feature request):**
bug

**Steps to reproduce (least amount of steps as possible):**
1. Install rancher-monitoring 9.4.200 from Apps & Marketplace. Don't enable the "Persistent Storage for Prometheus" on Chart Options.
2. Wait until install succeed
3. Enable "Persistent Storage for Prometheus", set Size and Storage Class and hit the Upgrade

**Result:**
E1020 18:55:18.768276       1 goroutinemap.go:150] Operation for "provision-cattle-monitoring-system/prometheus-rancher-monitoring-prometheus-db-prometheus-rancher-monitoring-prometheus-0[b8d564dd-e536-418c-9b68-cc589571f0c2]" failed. No retries permitted until 2020-10-20 18:57:20.768242437 +0000 UTC m=+119721.829961911 (durationBeforeRetry 2m2s). **Error: "claim.Spec.Selector is not supported for dynamic provisioning on vSphere"**
I1020 18:55:18.768400       1 event.go:291] "Event occurred" object="cattle-monitoring-system/prometheus-rancher-monitoring-prometheus-db-prometheus-rancher-monitoring-prometheus-0" kind="PersistentVolumeClaim" apiVersion="v1" type="Warning" reason="ProvisioningFailed" message="Failed to provision volume with StorageClass \"vspherethin\": claim.Spec.Selector is not supported for dynamic provisioning on vSphere"

**Other details that may be helpful:**
We have only one storage class. After some research we removed the default flag for that but didn't help.
We couldn't find a way to influence this behavior, even edited the YAML to remove the empty selector from teh volumeClaimTemplate but it was the same.

**Environment information**
- Rancher version: 2.5.1
- Installation option (single install/HA): single

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): Custom
- Kubernetes version (use `kubectl version`): 1.19.3

gz#13093

**Comment by axeal** [comment] 2020-10-28 15:08
The problem here is caused by the vSphere Volume Plugin which requires the `PVC.Spec.Selector` field to be nil not an empty map (https://github.com/kubernetes/kubernetes/blob/v1.19.3/pkg/volume/vsphere_volume/vsphere_volume_util.go#L138).

To workaround the issue:
1. Ensure the `rancher-monitoring` app is removed.
2. Ensure the `prometheus-rancher-monitoring-prometheus-db-prometheus-rancher-monitoring-prometheus-0` is deleted from the `cattle-monitoring-system` Namespace.
3. Re-deploy the `rancher-monitoring` app, enabling the persistent storage via the `Chart Options` form view, then clicking `Edit as YAML` and removing the `prometheus.prometheusSpec.storageSpec.volumeClaimTemplate.selector` block, before clicking `Install`.

Are we able we ensure the `prometheus.prometheusSpec.storageSpec.volumeClaimTemplate.selector` field is absent by default, and not defined but empty, in the instance no selectors are specified, to mitigate this?

**Comment by tompatib** [comment] 2020-11-02 11:51
Thanks @axeal ! The workaround solved the issue.

**Comment by aiyengar2** [comment] 2020-11-05 01:22
Related to https://github.com/rancher/rancher/issues/29839#issuecomment-719817302. Closing out this issue as the workaround seems to work as expected.

> Are we able we ensure the prometheus.prometheusSpec.storageSpec.volumeClaimTemplate.selector field is absent by default, and not defined but empty, in the instance no selectors are specified, to mitigate this?

@axeal This is tracked as a UI issue in https://github.com/rancher/dashboard/issues/1757, which should be available in Rancher 2.5.2.

**Closed by aiyengar2** 2020-11-05 01:22 UTC
Labels: internal, kind/bug
