### ISSUE TITLE
Unable to import existing downstream cluster in Rancher 2.8.0 - UI plugin issue

### ISSUE THREAD

**Issue by shindebshekhar** [rancher/rancher#43892] opened 2024-01-02 12:44 UTC
**Environmental Info:**
Rancher version: 2.8.0
rke2 version  on local Rancher cluster: v1.25.10+rke2r1

Downstream cluster version:
rke2 version v1.26.9+rke2r1

Node(s) CPU architecture, OS, and Version: 
Linux Ubuntu 

Cluster Configuration:
3 Masters(local rancher cluster)
3 Master 3 Worker nodes(Downstream cluster)

**Describe the bug:**
When we try to import cluster of rke2 version v1.26.9+rke2r1 in Rancher v2.8.0, we get below error. This is air-gap environment.
![image](https://github.com/rancher/rke2/assets/42248976/52dc08b4-062a-416d-8b54-5fa077910e18)

Rancher pod logs -->
[ERROR] failed to call leader func: failed to add management data: failed to fetch images from extensions: Get "https://api.github.com/repos/rancher/ui-plugin-charts/releases": dial tcp: lookup api.github.com on 192.168.64.10:53: no such host

The Images(ui-plugin-catalog) are already populated in private registry. We tried adding repository and deploying ui related operator and pods

kubectl get po -n cattle-ui-plugin-system
NAME                                  READY   STATUS    RESTARTS   AGE
ui-plugin-catalog-ddf5dd87-b8g4n      1/1     Running   0          30m
ui-plugin-operator-5d68dd4bc9-t2p5n   1/1     Running   0          31m

**Steps To Reproduce:**

- Installed RKE2: 

**Expected behavior:**
It should download plugin from local repo 

**Actual behavior:**
It goes outside to connect to api.github.com for downloading UI plugins

**Comment by snasovich** [comment] 2024-01-03 00:29
@shindebshekhar , this looks very similar to https://github.com/rancher/rancher/issues/43779 however it looks like in your case Rancher is managing to start OK. Could you please provide more information on repro steps and status of your Rancher pods?

**Comment by shindebshekhar** [comment] 2024-01-03 08:46
> @shindebshekhar , this looks very similar to #43779 however it looks like in your case Rancher is managing to start OK. Could you please provide more information on repro steps and status of your Rancher pods?

**To Reproduce**
1. In our case we are performing upgrade of Rancher from 2.7.6 to 2.8.0 in an air-gapped environment
2. Current setup is Rancher 2.7.6 with imported downstream clusters on version v1.25.10+rke2r1 and v1.26.10+rke2r1
3. After upgrade to Rancher 2.8.0 we observed the downstream cattle-agent pods are not upgraded to latest version 2.8.0 and also while importing any other downstream cluster we got below message(snap1) on UI
SNAP 1-
![image](https://github.com/rancher/rancher/assets/42248976/7fa21284-200a-49ca-a8cc-953dc50c8750)
4. Rancher pods are in running state but pod logs has below message
[ERROR] failed to call leader func: failed to add management data: failed to fetch images from extensions: Get "https://api.github.com/repos/rancher/ui-plugin-charts/releases": dial tcp: lookup api.github.com on 192.168.64.10:53: no such host

**Result**

1. Upgrading Image on downstream cattle agent pods fails
2. Unable to import existing cluster
3. Unable to add users in project from UI

**Expected Result**
1. Automatic Image upgrade on downstream cattle agent pods should happen
2. Importing cluster should work
3. Should be able to add users in project

**Comment by nobbs** [comment] 2024-01-04 13:04
Run into a similar issue - not entirely the same, but related to this one and the already linked #43779:

Upgrade of Rancher v2.7.9 to v2.8.0 in air-gapped mode worked kind-of fine (as in: Rancher UI available, downstream clusters green and available). We also get the same error message in the rancher pod logs:

```
2024/01/04 12:57:20 [ERROR] failed to call leader func: failed to add management data: failed to fetch images from extensions: Get "https://api.github.com/repos/rancher/ui-plugin-charts/releases": dial tcp 140.82.121.6:443: i/o timeout
```

When checking the available K8s versions for our downstream RKE1 clusters I've noticed that it's still only showing the previous selection of versions up to v1.26.x, not the newly supported v1.27.x. Checking the agent pods in the `cattle-system` namespace of the downstream clusters I've noticed that they were not upgraded and are still running `rancher-agent:v2.7.9` and `rancher-webhook:v0.3.6`. Restarts of the Rancher deployment did not trigger any updates.

What did the trick was setting a proxy / no_proxy for the Rancher deployment in the local cluster (we did via Helm values, but you can also just add the `HTTP_PROXY`, `HTTPS_PROXY`, `NO_PROXY` env vars). That did successfully trigger the update of the agents on the downstream clusters to v2.8.0.

Funny thing: the proxy does have access to `github.com` but definitely not `api.github.com` (don't ask...) - so I'm still getting the same error messages as before, but for whatever reason this kind of worked. Still, would prefer this to be fixed :D

**Comment by snasovich** [comment] 2024-01-04 16:39
@shindebshekhar @nobbs , thank you for additional context. Based on this information, it's highly likely the fix to https://github.com/rancher/rancher/issues/43779 should address these issues as well.
To provide more color, it looks like management controllers are failing to start as the [call](https://github.com/rancher/rancher/blob/6445a1ab45faa617a3f5ea5a28b83083eccdb42b/pkg/multiclustermanager/app.go#L205) to start them if after the [statement](https://github.com/rancher/rancher/blob/6445a1ab45faa617a3f5ea5a28b83083eccdb42b/pkg/multiclustermanager/app.go#L201) that errors out due to the root cause of https://github.com/rancher/rancher/issues/43779. And upgrading of downstream cluster agents is handled by `clusterdeploy` controller that is a [part](https://github.com/rancher/rancher/blob/6445a1ab45faa617a3f5ea5a28b83083eccdb42b/pkg/controllers/management/controller.go#L47) of management controllers. So that explains why you don't see `rancher-agent` upgrading.

@daviswill2 , let's have these use cases reproduced on v2.8.0 and ensure they are fixed with the same changes as we're doing as part of https://github.com/rancher/rancher/issues/43779.

**Comment by nobbs** [comment] 2024-01-04 20:20
@snasovich Thanks for the context - checking the code change between v2.7.9 and v2.8.0 for `GetImages`

https://github.com/rancher/rancher/blob/72f58378bf03122a9651c9bd3b4c143a57e8fdaa/pkg/image/resolve.go#L85-L91

it fits the behaviour. I'm now confused why it worked with our proxy setting which - to my knowledge - is blocking access to <https://api.github.com>. Maybe it changed, maybe I'm misremembering. Anyway, that's not related to Rancher itself.

Going to run with the proxy workaround set until a fix is released. Truly air-gapped clusters are kind of borked right now by this issue if none of the management controllers are starting up, aren't they?

**Comment by snasovich** [comment] 2024-01-04 20:29
> Truly air-gapped clusters are kind of borked right now by this issue if none of the management controllers are starting up, aren't they?

Yep, that's why we're putting priority on addressing https://github.com/rancher/rancher/issues/43779
Frankly speaking I'm not exactly sure why Rancher is not crashlooping in upgrade scenario but does in fresh install case (see https://github.com/rancher/rancher/issues/43779#issuecomment-1857131424 for another confirmation of that) but figuring it out won't change anything about needing to address https://github.com/rancher/rancher/issues/43779 anyway so we're not focusing on that part.

**Comment by snasovich** [comment] 2024-01-04 20:52
Note: Unlike for https://github.com/rancher/rancher/issues/43779, not creating forward/backports as this issue should be addressed by the same changes so forward/backports for it will automatically cover this issue.
If it turns out this issue is not addressed (which will be determined as part of testing v2.8.1 RCs), forward/backports will be created as needed.

**Comment by shindebshekhar** [comment] 2024-01-08 09:05
@snasovich @nobbs - I confirm after whitelisting https://api.github.com/ in security proxy and setting proxy/no_proxy env variable in rancher pods, I was able to import downstream clusters and downstream cattle agents pods also got updated with newer 2.8.0 version. But production environments are air-gapped, so unfortunatley this solution will not help.

Also 1.26 from RKE perspective is EOL on 28 Feb 2024 aligning on CNCF calendar. Rancher 2.8.0 stable version is still not released, so a fix is needed for this issue in my opinion.

**Comment by jiaqiluo** [comment] 2024-01-08 18:16
The fix can be validated in Rancher [v2.8.1-rc1](https://github.com/rancher/rancher/releases/tag/v2.8.1-rc1)

**Comment by slickwarren** [comment] 2024-01-10 18:15
tested the following on rancher 2.8.1-rc1:
* airgapped rancher with BundledSystemCharts=True
* deploy an rke2 1.28.5+rke2r1 airgapped cluster in the same subnet as the rancher airgap following instructions from the documentation: https://docs.rke2.io/install/airgap via tarball method
* import the rke2 cluster into the airgapped rancher setup -> pass (no errors observed)

**Comment by slickwarren** [comment] 2024-01-10 23:53
reopening to test upgrade scenario

**Closed** 2024-01-11 17:50 UTC
Labels: area/air-gapped, [zube]: QA Working, team/area2

**Comment by shindebshekhar** [comment] 2024-01-18 04:50
> reopening to test upgrade scenario: deploy airgapped rancher on 2.7.6 deploy an airgapped rke2 cluster (1.26.7+rke2r1), import to rancher
> 
> * upgrade rancher to 2.8.1-rc1 -- pass
> * deploy a new airgapped rke2 cluster (1.26.7+rke2r1), import to upgraded rancher -- pass
> * observe no errors on downstream clusters during / after upgrade -- pass
>   
>   * existing imported clusters have their cattle-agents upgraded to 2.8.1-rc1 -- pass

Hello, I tested importing cluster with 2.8.1-rc3 release but see below error. Verified certificates are properly configured on server and client side. Also verified the checksum(CATTLE_CA_CHECKSUM environment variable) on downstream cluster cattle agent pods, it matches with value of **curl -k -s -fL <RANCHER_SERVER_URL>/v3/settings/cacerts | jq -r .value | sha256sum | awk '{print $1}'**

Environment details-
Rancher upgrade cluster version: v1.25.10+rke2r1
Downstream cluster version:  v1.26.9+rke2r1
Rancher version: 2.8.1-rc3

**Below is the error:**
time="2024-01-17T05:44:26Z" level=error msg="Issuer of last certificate found in chain (CN=xxx,O=xxx,C=xx) does not match with CA certificate Issuer (CN=xx-G2,O=xxx,C=xx). Please check if the configured server certificate contains all needed intermediate certificates and make sure they are in the correct order (server certificate first, intermediates after)"
time="2024-01-17T05:44:26Z" level=fatal msg="Certificate chain is not complete, please check if all needed intermediate certificates are included in the server certificate (in the correct order) and if the cacerts setting in Rancher either contains the correct CA certificate (in the case of using self signed certificates) or is empty (in the case of using a certificate signed by a recognized CA). Certificate information is displayed above. error: Get \"https://xxx\": tls: failed to verify certificate: x509: certificate signed by unknown authority"

**Comment by xzxiaoshan** [comment] 2024-06-06 02:46
The same problem, unable to register nodes, exists in ranger 2.8.4. When can this problem be resolved? I think this is an urgent issue.

```
[root@k8s-prod-m2 opt]# journalctl -u rancher-system-agent.service -f
Jun 05 15:10:39 k8s-prod-m2 systemd[1]: Started Rancher System Agent.
Jun 05 15:10:39 k8s-prod-m2 rancher-system-agent[1094]: time="2024-06-05T15:10:39+08:00" level=info msg="Rancher System Agent version v0.3.6 (41c07d0) is starting"
Jun 05 15:10:39 k8s-prod-m2 rancher-system-agent[1094]: time="2024-06-05T15:10:39+08:00" level=info msg="Using directory /var/lib/rancher/agent/work for work"
Jun 05 15:10:39 k8s-prod-m2 rancher-system-agent[1094]: time="2024-06-05T15:10:39+08:00" level=info msg="Starting remote watch of plans"
Jun 05 15:10:39 k8s-prod-m2 rancher-system-agent[1094]: time="2024-06-05T15:10:39+08:00" level=info msg="Initial connection to Kubernetes cluster failed with error Get \"https://rancher.xxxxx.com/version\": tls: failed to verify certificate: x509: certificate signed by unknown authority, removing CA data and trying again"
Jun 05 15:10:40 k8s-prod-m2 rancher-system-agent[1094]: time="2024-06-05T15:10:40+08:00" level=info msg="Starting /v1, Kind=Secret controller"
```
