### ISSUE TITLE
Kubernetes Version in "edit cluster" not the same as in "clusters" (RKE2)

### ISSUE THREAD

**Issue by Martin-Weiss** [rancher/rancher#34114] opened 2021-08-10 10:05 UTC
**Rancher Server Setup**
- Rancher version: 2.5.8
- Installation option (Docker install/Helm Chart): helm chart on RKE2

**Information about the Cluster**
- Kubernetes version: 1.20.7 rke2r2
- Cluster Type (Local/Downstream): local and downstream - imported

**Describe the bug**
In "edit cluster" we can see 1.20.7+rke2r1 but the installed version is 1.20.7+rke2r2

**To Reproduce**
Import an RKE2 cluster into rancher with these versions

**Result**
see above

**Expected Result**
User / admin expects to see the same and the correct / real version of the downstream cluster as this is also very important to be consistent during updates / upgrades so that one can see which cluster and which node is on which exact kubernetes and RKE2 patchlevel.

**Screenshots**
![grafik](https://user-images.githubusercontent.com/13362573/128848519-be7586b4-831c-40a3-92a5-8da22045926a.png)

![grafik](https://user-images.githubusercontent.com/13362573/128848564-5f3f32a3-0203-4aef-8f59-a8b8ee45dff4.png)

**Comment by rancher-max** [comment] 2021-08-10 17:24
I attempted to reproduce this on Rancher v2.5.9 and was unable to:
<img width="1300" alt="image" src="https://user-images.githubusercontent.com/55997940/128905515-7e865bc9-588d-4cda-8396-be37a0ef2c6c.png">

<img width="1330" alt="image" src="https://user-images.githubusercontent.com/55997940/128905558-af510922-50ce-4ae0-9046-740fc8e607f7.png">

@Martin-Weiss I'm wondering if there's perhaps something else going on here, like a custom KDM (visible at https://<your_rancher_url>/v3/settings/rke-metadata-config), since I don't see the dropdown to upgrade there for you either? See mine for reference, which is using kdm url "https://releases.rancher.com/kontainer-driver-metadata/release-v2.5/data.json":
<img width="732" alt="image" src="https://user-images.githubusercontent.com/55997940/128905921-f58aff0e-5333-4182-a800-d6f4d3ba95a9.png">

**Comment by cjellick** [comment] 2021-08-10 17:27
@rancher-max re:
> @Martin-Weiss I'm wondering if there's perhaps something else going on here, like a custom KDM (visible at https://<your_rancher_url>/v3/settings/rke-metadata-config), since I don't see the dropdown to upgrade there for you either? See mine for reference, which is using kdm url "https://releases.rancher.com/kontainer-driver-metadata/release-v2.5/data.json":

I bet this is an arigap setup and its using the version of KDM that was embedded into 2.5.8.

@Martin-Weiss can you confirm that?

**Comment by cjellick** [comment] 2021-08-10 17:30
@vincent99 any thoughts on why we might see this mismatch?

@Martin-Weiss can you post a sanitized version of this cluster from the api? should be able to get at it from `/v3/clusters/cluster id>`.

**Comment by Martin-Weiss** [comment] 2021-08-11 06:47
> 
> 
> I attempted to reproduce this on Rancher v2.5.9 and was unable to:
> <img alt="image" width="1300" src="https://user-images.githubusercontent.com/55997940/128905515-7e865bc9-588d-4cda-8396-be37a0ef2c6c.png">
> 
> <img alt="image" width="1330" src="https://user-images.githubusercontent.com/55997940/128905558-af510922-50ce-4ae0-9046-740fc8e607f7.png">
> 
> @Martin-Weiss I'm wondering if there's perhaps something else going on here, like a custom KDM (visible at https://<your_rancher_url>/v3/settings/rke-metadata-config), since I don't see the dropdown to upgrade there for you either? See mine for reference, which is using kdm url "https://releases.rancher.com/kontainer-driver-metadata/release-v2.5/data.json":
> <img alt="image" width="732" src="https://user-images.githubusercontent.com/55997940/128905921-f58aff0e-5333-4182-a800-d6f4d3ba95a9.png">

I just upgraded Rancher to 2.5.9 and it does not look much better. Rancher still shows this in "clusters" overview:

![grafik](https://user-images.githubusercontent.com/13362573/128982132-8a3c8df0-292f-4a30-afe6-73c3c8241316.png)

But this when I select "edit":

![grafik](https://user-images.githubusercontent.com/13362573/128982167-3229fc6f-2c02-4079-90d4-51260cf8345e.png)

But - with Rancher 2.5.9 I can select the upgrade to r2 even though it is r2 already:

![grafik](https://user-images.githubusercontent.com/13362573/128982277-ab1edfdb-19ad-4fb3-a3e6-6083b16d0943.png)

**Comment by Martin-Weiss** [comment] 2021-08-11 06:55
> 
> @vincent99 any thoughts on why we might see this mismatch?
> 
> @Martin-Weiss can you post a sanitized version of this cluster from the api? should be able to get at it from `/v3/clusters/cluster id>`.

Here you go: 
[cluster-info.json.txt](https://github.com/rancher/rancher/files/6966440/cluster-info.json.txt)

Could this issue be related to "cluster imported with a version that was not yet known to 2.5.8"?

I can see that the "version" shown is "gitVersion": "v1.20.7+rke2r2", but in the rke2Config I see the "kubernetesVersion": "v1.20.7+rke2r1"

**Comment by vincent99** [comment] 2021-08-11 07:11
From your last bit of info I don't think it's a UI problem; the json essentially says you "want" r1 but "have"/are running r2.  Which is a problem of how you got into that situation in the first place, but as far as edit is concerned it's only manipulating the "want".

My guess works be somewhere down the pipe there's a semver compare and r2 was selected for install because is "equal" to r1.  The plus in a semver string is metadata and ignored for comparisons so they are both considered to be the same v1.20.7.

**Comment by Martin-Weiss** [comment] 2021-08-11 07:31
> From your last bit of info I don't think it's a UI problem; the json essentially says you "want" r1 but "have"/are running r2. Which is a problem of how you got into that situation in the first place, but as far as edit is concerned it's only manipulating the "want".
> 

Due to this explanation I believe the UI needs some usability enhancement to explain.. I also do not understand how the UI can tell the end user to want "r1" even if "r2" is already running.. this would mean that we want to do a downgrade?

> My guess would be that somewhere down the pipe there's a semver compare and r2 was selected for install because it is "equal" to r1. The plus in a semver is metadata and ignored for comparisons so they are both considered to be the same v1.20.7.

So do we expect this to be "fixed" in Rancher 2.5.10 or 2.6.0? I believe it can happen that an upgrade is done outside of the view of Rancher - especially because RKE2 upgrades are not working very well in 2.5.* so far..

**Comment by Martin-Weiss** [comment] 2021-08-11 10:03
> 
> 
> The "status" of what is currently running is managed by the controller and irrelevant as far as editing the cluster is concerned.. the "spec" says you want r1, so that's what's selected and you can change it to another version if you want a different one.

We never selected something - we just "imported" the local and the downstream cluster. So IMO the "import" is setting this wrong and the data is not updated for an imported cluster if the imported cluster changed version.

The US is very confusing to the customer as it shows a wrong status for "what do you want"..

> 
> That doesn't happen immediately; if you picked 1.22 and hit save and then edit again immediately, you wouldn't expect it to show 1.20 is selected again just because it happens to still be running on one or more of the control plane nodes.
> 

Maybe the information shown or the text/description in the UI can be "enhanced"? And maybe the "want" can be changed automatically to the current status if there is no upgrade running?

> You manage the desired state, the controller makes changes such that the actual status should match that. The problem is that you've asked for r1 and the controller has delivered r2, or that you are asking for a version it doesn't know about, not that the dropdown says r1.

So how should a customer deal with cluster imports where Rancher does not know about the version?

**Comment by vincent99** [comment] 2021-08-11 11:32
Again, your problem is with the data that has been persisted, regardless of how it got there, not how it is displayed. There is some problem here that has resulted in getting to this state, and it should be addressed.  If the import process saw r2 running and then recorded version=r1, that's where the problem is.

But where the problem is not is how the UI is showing the selected version from the data it was given, and the solution is not going to involve showing the gitVersion anywhere in the edit screen.

**Comment by Martin-Weiss** [comment] 2021-08-11 11:39
> 
> 
> Again, your problem is with the data that has been persisted, regardless of how it got there, not how it is displayed. There is some problem here that has resulted in getting to this state, and it should be addressed. If the import process saw r2 running and then recorded version=r1, that's where the problem is.
> 

Yes -then this seems to be the bug.. we imported r2 and it shows r1 as persistent.

> But where the problem is not is how the UI is showing the selected version from the data it was given, and the solution is not going to involve showing the gitVersion anywhere in the edit screen.

I am also fine with more / better description and explanation in the mouse-over or in the UI screen ;-) - usability....

**Comment by cjellick** [comment] 2021-08-11 15:52
We will address this as a bug so that what is persisted matches reality. `rke2r2` should have been persisted and wasn't.

I can't speak to the exact version it will get fixed in, but my opinion is that this should be addressed in the 2.5 release and we should ensure it doesn't regress in 2.6.

@vincent99 and @Martin-Weiss thanks as usual for the in depth analysis.

Martin, I think this is a really good theory:
> Could this issue be related to "cluster imported with a version that was not yet known to 2.5.8"?
> 
> I can see that the "version" shown is "gitVersion": "v1.20.7+rke2r2", but in the rke2Config I see the "kubernetesVersion": "v1.20.7+rke2r1"

It would help explain whey @rancher-max didn't see it when attempting to reproduce. He tried with a non-airgapped 2.5.9. This version would have "known" about `v1.20.7+rke2r2`.

**Comment by cjellick** [comment] 2021-08-11 18:34
@Martin-Weiss I have a few more pieces of information to request. Can you give me the following:

1. On one of the nodes in the downstream cluster `rke2 version`
2. Directly interacting with the downstream via kubectl - `kubectl version`
3. In the "local" rancher cluster, the direct yaml output of the cluster CRD. Command should be something like `kubectl get cluster <cluster-id> -o yaml`, but i'm not exactly sure of it.

I'm pretty sure 1 & 2 won't turn up anything interesting, but want to get them just to be sure. I want 3 to see if there's any difference between rancher's api output and whats actually in k8s. The rancher API does some transformations, so I just want to be sure of the raw data.

**Comment by Martin-Weiss** [comment] 2021-08-12 06:44
> 
> 
> @Martin-Weiss I have a few more pieces of information to request. Can you give me the following:
> 
>     1. On one of the nodes in the downstream cluster `rke2 version`

```
rke2 version v1.20.7+rke2r2 (ea6514775f816b0b4972f832de7d98eba8dff55c)
go version go1.15.8b5

```
> 
>     2. Directly interacting with the downstream via kubectl - `kubectl version`
> 

Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.7+rke2r2", GitCommit:"132a687512d7fb058d0f5890f07d4121b3f0a2e2", GitTreeState:"clean", BuildDate:"2021-05-26T04:47:27Z", GoVersion:"go1.15.8b5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.7+rke2r2", GitCommit:"132a687512d7fb058d0f5890f07d4121b3f0a2e2", GitTreeState:"clean", BuildDate:"2021-05-26T04:47:27Z", GoVersion:"go1.15.8b5", Compiler:"gc", Platform:"linux/amd64"}


>     3. In the "local" rancher cluster, the direct yaml output of the cluster CRD. Command should be something like `kubectl get cluster <cluster-id> -o yaml`, but i'm not exactly sure of it.
> 

kubectl get  clusters.management.cattle.io <cluster-id> -o yaml
...
  rke2Config:
    kubernetesVersion: v1.20.7+rke2r1
    rke2upgradeStrategy:
      serverConcurrency: 1
      workerConcurrency: 1
...
  version:
    buildDate: "2021-05-26T04:47:27Z"
    compiler: gc
    gitCommit: 132a687512d7fb058d0f5890f07d4121b3f0a2e2
    gitTreeState: clean
    gitVersion: v1.20.7+rke2r2
    goVersion: go1.15.8b5
    major: "1"
    minor: "20"
    platform: linux/amd64
...

> 
> I'm pretty sure 1 & 2 won't turn up anything interesting, but want to get them just to be sure. I want 3 to see if there's any difference between rancher's api output and whats actually in k8s. The rancher API does some transformations, so I just want to be sure of the raw data.

The yaml shows the same as the API..

**Comment by cjellick** [comment] 2021-08-12 14:55
Ok, so it isn't any on-the-fly transformation occurring.

We've triaged this into the v2.5.10 milestone. I'm not the engineer who is going to actively work on it. I just wanted to collect some information to help identify whether the bug was on the rke2 side or rancher side. I believe this is rancher side.

One final thought/theory I had: is it possible that someone got to the edit the cluster page, the dropdown was populated with the `rke2r1` version (because rancher didnt have knowledge of the rke2r2 version) and then clicked save and that's what caused the `rke2r1` version to get saved to the `clsuter.spec.kubernetesVersion` field?

**Comment by Martin-Weiss** [comment] 2021-08-12 15:18
> One final thought/theory I had: is it possible that someone got to the edit the cluster page, the dropdown was populated with the `rke2r1` version (because rancher didnt have knowledge of the rke2r2 version) and then clicked save and that's what caused the `rke2r1` version to get saved to the `clsuter.spec.kubernetesVersion` field?

I can not say this for sure - but I think nobody did the edit and save as an edit was not possible anyway as Rancher 2.5.8 did not allow to select anything in the drop-down..

**Comment by thedadams** [comment] 2021-09-01 23:17
I am not able to reproduce this issue. I deployed Rancher v2.5.8 and imported an RKE cluster. I find that the Kubernetes version shows the correct version in all places that I can find it.
![Screen Shot 2021-09-01 at 4 16 35 PM](https://user-images.githubusercontent.com/3682717/131757582-8202087a-0a68-4df3-83a8-8c92bd0fcd11.png)
![Screen Shot 2021-09-01 at 4 16 50 PM](https://user-images.githubusercontent.com/3682717/131757583-d4093e0a-eae3-444d-b870-c9af45d1a9de.png)

**Comment by thedadams** [comment] 2021-09-02 16:23
I was able to reproduce this with the following steps:
1. Provision an RKE2 cluster with version `1.20.7+rke2r1`
2. Import this cluster to Rancher
3. From the downstream cluster (not in Rancher), update RKE2 to `1.20.7+rke2r2`
After the upgrade completes, I see the behavior described in the issue.

I came up with this idea after looking through the code: the `status.version` gets updated from the downstream cluster, but the `spec.rke2Config.kubernetesVersion` only gets set/updated on first import or updating that field directly (like the UI would do on upgrade). The logic indicates to me that this would be the only way for these two fields to get out of sync.

If I understand correctly, this scenario is not something we would support.

**Comment by snasovich** [comment] 2021-09-07 19:08
@deniseschannon , do you have an update on whether this should be supported or not? Instinctively I think we should support this scenario as users can upgrade downstream cluster's RKE2 directly and are not forced to do it from Rancher.

**Comment by deniseschannon** [comment] 2021-09-08 18:38
Couldn't this be as simple as updating the logic from the `status.version` instead of the `spec.rke2Config.kubernetesVersion` in the UI so that you would get whatever version exists on the cluster that is managed outside of Rancher?

@rmweir Is there any specific reason why we would need to read from `spec.rke2Config.kubernetesVersion` versus what it's maintained?

**Comment by thedadams** [comment] 2021-09-08 19:09
@deniseschannon The issue is the the edit screen is showing the outdated information right now. When you are editing a cluster, you are editing the `spec`. So not showing what is on `spec` in this case seems dubious.

**Comment by deniseschannon** [comment] 2021-09-08 19:23
Instead of populating it with spec, shouldn't it populate with `status.version`? Any technical reason why it couldn't do that?

**Comment by thedadams** [comment] 2021-09-08 20:05
Technical reason: no
Paradigm reason: yes

**Comment by snasovich** [comment] 2021-09-10 18:41
So it looks like we don't have a consensus here yet and it's been couple of days since the last comment.

Overall I don't think we should be using values from `status` for any editable fields on the Edit screen as we're working on the desired state. This comment by @vincent99 provides more rationale on why it would be wrong to do this: https://github.com/rancher/rancher/issues/34114#issuecomment-896656939

Given this, how do we address the scenario @thedadams referenced here: https://github.com/rancher/rancher/issues/34114#issuecomment-911855072 ? It seems that properly handling it may be challenging - e.g. somehow detect there was an upgrade of RKE2 on imported cluster's nodes (what if only some nodes were upgraded?) and have `spec` updated accordingly. So maybe @Martin-Weiss 's suggestion to add a note on the Edit screen UI  is the way to go here? Something along the lines of "The version displayed may be different from the actual version installed on the nodes (e.g. if k8s upgrade was done outside of Rancher)".

**Comment by deniseschannon** [comment] 2021-09-30 21:03
@Martin-Weiss Based on the only way this can be reproduced, this is expected. 

As soon as you import a RKE2 cluster, Rancher is expecting the k8s management to be handled through Rancher and not handled outside of Rancher. If you update k8s outside of Rancher, then this will no longer be in sync. 

The proposed ways have challenges of why we will not fix it at this time.

**Closed** 2021-09-30 21:03 UTC
Labels: status/wontfix, [zube]: Need Info
