### ISSUE TITLE
Monitoring - Rancher failed to install monitoring after upgrading from 2.1.7 to 2.2.0 in Airgap setup

### ISSUE THREAD

**Issue by rammaram06** [rancher/rancher#19362] opened 2019-04-03 15:18 UTC
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
** Install single node Rancher server 2.1.7 using Airgap Installation (Server has access to internet)
** Create a cluster with nodes
** Upgrade to 2.2.0 using airgap installation
** Enable Cluster level monitoring

**Result:**
```
[main] 2019/03/29 16:06:04 Starting Tiller v2.10+unreleased (tls=false)
[main] 2019/03/29 16:06:04 GRPC listening on :52444
[main] 2019/03/29 16:06:04 Probes listening on :54817
[main] 2019/03/29 16:06:04 Storage driver is ConfigMap
[main] 2019/03/29 16:06:04 Max history per release is 0
[main] 2019/03/29 16:06:04 Starting Tiller v2.10+unreleased (tls=false)
[main] 2019/03/29 16:06:04 GRPC listening on :53804
[main] 2019/03/29 16:06:04 Probes listening on :46060
[main] 2019/03/29 16:06:04 Storage driver is ConfigMap
[main] 2019/03/29 16:06:04 Max history per release is 0
[tiller] 2019/03/29 16:06:05 getting history for release cluster-monitoring
[storage] 2019/03/29 16:06:05 getting release history for "cluster-monitoring"
Release "cluster-monitoring" does not exist. Installing it now.
[tiller] 2019/03/29 16:06:05 getting history for release monitoring-operator
[storage] 2019/03/29 16:06:05 getting release history for "monitoring-operator"
[tiller] 2019/03/29 16:06:05 preparing install for cluster-monitoring
[storage] 2019/03/29 16:06:05 getting release history for "cluster-monitoring"
Release "monitoring-operator" does not exist. Installing it now.
[tiller] 2019/03/29 16:06:05 preparing install for monitoring-operator
[storage] 2019/03/29 16:06:05 getting release history for "monitoring-operator"
[tiller] 2019/03/29 16:06:05 rendering rancher-monitoring chart using values
[tiller] 2019/03/29 16:06:05 rendering rancher-monitoring chart using values
[tiller] 2019/03/29 16:06:05 performing install for monitoring-operator
[tiller] 2019/03/29 16:06:05 executing 0 crd-install hooks for monitoring-operator
[tiller] 2019/03/29 16:06:05 hooks complete for crd-install monitoring-operator
2019/03/29 16:06:05 info: manifest "rancher-monitoring/templates/rbac.yaml" is empty. Skipping.
2019/03/29 16:06:05 info: manifest "rancher-monitoring/templates/deployment.yaml" is empty. Skipping.
2019/03/29 16:06:05 info: manifest "rancher-monitoring/charts/grafana/templates/rbac.yaml" is empty. Skipping.
2019/03/29 16:06:05 info: manifest "rancher-monitoring/charts/grafana/templates/pvc.yaml" is empty. Skipping.
2019/03/29 16:06:05 info: manifest "rancher-monitoring/templates/servicemonitor.yaml" is empty. Skipping.
2019/03/29 16:06:05 info: manifest "rancher-monitoring/templates/metrics-service.yaml" is empty. Skipping.
[tiller] 2019/03/29 16:06:05 performing install for cluster-monitoring
[tiller] 2019/03/29 16:06:05 executing 0 crd-install hooks for cluster-monitoring
[tiller] 2019/03/29 16:06:05 hooks complete for crd-install cluster-monitoring
[tiller] 2019/03/29 16:06:06 failed install perform step: validation failed: unable to recognize "": no matches for kind "ServiceMonitor" in version "monitoring.coreos.com/v1"
2019/03/29 16:06:06 [ERROR] AppController p-s7js9/monitoring-operator [helm-controller] failed with : failed to install app monitoring-operator. Error: validation failed: unable to recognize "": no matches for kind "ServiceMonitor" in version "monitoring.coreos.com/v1"
[tiller] 2019/03/29 16:06:06 failed install perform step: validation failed: [unable to recognize "": no matches for kind "Prometheus" in version "monitoring.coreos.com/v1", unable to recognize "": no matches for kind "PrometheusRule" in version "monitoring.coreos.com/v1", unable to recognize "": no matches for kind "PrometheusRule" in version "monitoring.coreos.com/v1", unable to recognize "": no matches for kind "PrometheusRule" in version "monitoring.coreos.com/v1", unable to recognize "": no matches for kind "ServiceMonitor" in version "monitoring.coreos.com/v1", unable to recognize "": no matches for kind "ServiceMonitor" in version "monitoring.coreos.com/v1", unable to recognize "": no matches for kind "ServiceMonitor" in version "monitoring.coreos.com/v1", unable to recognize "": no matches for kind "ServiceMonitor" in version "monitoring.coreos.com/v1", unable to recognize "": no matches for kind "ServiceMonitor" in version "monitoring.coreos.com/v1", unable to recognize "": no matches for kind "ServiceMonitor" in version "monitoring.coreos.com/v1", unable to recognize "": no matches for kind "ServiceMonitor" in version "monitoring.coreos.com/v1", unable to recognize "": no matches for kind "ServiceMonitor" in version "monitoring.coreos.com/v1", unable to recognize "": no matches for kind "ServiceMonitor" in version "monitoring.coreos.com/v1", unable to recognize "": no matches for kind "ServiceMonitor" in version "monitoring.coreos.com/v1"]
2019/03/29 16:06:06 [ERROR] AppController p-s7js9/cluster-monitoring [helm-controller] failed with : failed to install app cluster-monitoring. Error: validation failed: [unable to recognize "": no matches for kind "Prometheus" in version "monitoring.coreos.com/v1", unable to recognize "": no matches for kind "PrometheusRule" in version "monitoring.coreos.com/v1", unable to recognize "": no matches for kind "PrometheusRule" in version "monitoring.coreos.com/v1", unable to recognize "": no matches for kind "PrometheusRule" in version "monitoring.coreos.com/v1", unable to recognize "": no matches for kind "ServiceMonitor" inversion "monitoring.coreos.com/v1", unable to recognize "": no matches for kind "ServiceMonitor" in version "monitoring.coreos.com/v1", unable to recognize "": no matches for kind "ServiceMonitor" in version "monitoring.coreos.com/v1", unable to recognize "": no matches for kind "ServiceMonitor" in version "monitoring.coreos.com/v1", unable to recognize "": no matches for kind "ServiceMonitor" in version "monitoring.coreos.com/v1", unable to recognize "": no matches for kind "ServiceMonitor" in version "monitoring.coreos.com/v1", unable to recognize "": no matches for kind "ServiceMonitor" in version "monitoring.coreos.com/v1", unable to recognize "": no matches for kind "ServiceMonitor" in version "monitoring.coreos.com/v1", unable to recognize"": no matches for kind "ServiceMonitor" in version "monitoring.coreos.com/v1", unable to recognize "": no matches for kind "ServiceMonitor" in version "monitoring.coreos.com/v1"] 

```
**Other details that may be helpful:**
All Rancher related images are in our private repository

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): 2.2.0
- Installation option (single install/HA): single install

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): Custom
- Machine type (cloud/VM/metal) and specifications (CPU/memory): VM and 4 Cores/8GB RAM
- Kubernetes version (use `kubectl version`): 

```
Client Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.6", GitCommit:"ab91afd7062d4240e95e51ac00a18bd58fddd365", GitTreeState:"clean", BuildDate:"2019-02-26T12:59:46Z", GoVersion:"go1.10.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.4", GitCommit:"c27b913fddd1a6c480c229191a087698aa92f0b1", GitTreeState:"clean", BuildDate:"2019-02-28T13:30:26Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}
```

- Docker version (use `docker version`):

```
Client:
 Version:           18.06.0-ce
 API version:       1.38
 Go version:        go1.10.3
 Git commit:        0ffa825
 Built:             Wed Jul 18 19:08:18 2018
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          18.06.0-ce
  API version:      1.38 (minimum version 1.12)
  Go version:       go1.10.3
  Git commit:       0ffa825
  Built:            Wed Jul 18 19:10:42 2018
  OS/Arch:          linux/amd64
  Experimental:     false

```

**Comment by scndel** [comment] 2019-04-03 15:38
Similar issue from 2.1.6 to 2.2.1 with similar config but **without Airgap** :

`[main] 2019/04/02 14:03:47 Starting Tiller v2.10+unreleased (tls=false)
[main] 2019/04/02 14:03:47 GRPC listening on :47865
[main] 2019/04/02 14:03:47 Probes listening on :47197
[main] 2019/04/02 14:03:47 Storage driver is ConfigMap
[main] 2019/04/02 14:03:47 Max history per release is 0
[main] 2019/04/02 14:03:48 Starting Tiller v2.10+unreleased (tls=false)
[main] 2019/04/02 14:03:48 GRPC listening on :38546
[main] 2019/04/02 14:03:48 Probes listening on :40077
[main] 2019/04/02 14:03:48 Storage driver is ConfigMap
[main] 2019/04/02 14:03:48 Max history per release is 0
[tiller] 2019/04/02 14:03:48 getting history for release cluster-monitoring
[storage] 2019/04/02 14:03:48 getting release history for "cluster-monitoring"
[storage/driver] 2019/04/02 14:03:48 query: failed to query with labels: the server is currently unable to handle the request (get configmaps)
[tiller] 2019/04/02 14:03:48 preparing update for cluster-monitoring
[storage] 2019/04/02 14:03:48 getting deployed releases from "cluster-monitoring" history
[storage/driver] 2019/04/02 14:03:48 query: failed to query with labels: the server is currently unable to handle the request (get configmaps)
2019/04/02 14:03:48 [ERROR] AppController p-4hqvk/cluster-monitoring [helm-controller] failed with : failed to install app cluster-monitoring. Error: UPGRADE FAILED: the server is currently unable to handle the request (get configmaps)`

**Comment by alena1108** [comment] 2019-04-03 17:23
@scndel your situation can be similar to one described in https://github.com/rancher/rancher/issues/19331

Changed the subject of this ticket to reflect the fact the original issue happened on airgap.

**Comment by rammaram06** [comment] 2019-04-03 17:51
@alena1108 Just an FYI, I have installed it using airgap method but server has access to internet and can download images.

**Comment by gstorme** [comment] 2019-04-05 10:16
I'm experiencing the same issue, on a new install of Rancher v2.2.1.
All nodes have Internet access.

```
[main] 2019/04/05 10:14:29 Starting Tiller v2.10+unreleased (tls=false)
[main] 2019/04/05 10:14:29 GRPC listening on :34202
[main] 2019/04/05 10:14:29 Probes listening on :43488
[main] 2019/04/05 10:14:29 Storage driver is ConfigMap
[main] 2019/04/05 10:14:29 Max history per release is 0
[main] 2019/04/05 10:14:29 Starting Tiller v2.10+unreleased (tls=false)
[main] 2019/04/05 10:14:29 GRPC listening on :44410
[main] 2019/04/05 10:14:29 Probes listening on :52747
[main] 2019/04/05 10:14:29 Storage driver is ConfigMap
[main] 2019/04/05 10:14:29 Max history per release is 0
[tiller] 2019/04/05 10:14:30 getting history for release monitoring-operator
[storage] 2019/04/05 10:14:30 getting release history for "monitoring-operator"
[storage/driver] 2019/04/05 10:14:30 query: failed to query with labels: the server is currently unable to handle the request (get configmaps)
[tiller] 2019/04/05 10:14:30 preparing update for monitoring-operator
[storage] 2019/04/05 10:14:30 getting deployed releases from "monitoring-operator" history
[tiller] 2019/04/05 10:14:30 getting history for release cluster-monitoring
[storage] 2019/04/05 10:14:30 getting release history for "cluster-monitoring"
[storage/driver] 2019/04/05 10:14:30 query: failed to query with labels: the server is currently unable to handle the request (get configmaps)
[storage] 2019/04/05 10:14:30 getting last revision of "monitoring-operator"
[storage] 2019/04/05 10:14:30 getting release history for "monitoring-operator"
[storage/driver] 2019/04/05 10:14:30 query: failed to query with labels: the server is currently unable to handle the request (get configmaps)
2019/04/05 10:14:30 [ERROR] AppController p-5f5sr/monitoring-operator [helm-controller] failed with : failed to install app monitoring-operator. Error: UPGRADE FAILED: the server is currently unable to handle the request (get configmaps)

Release "cluster-monitoring" does not exist. Installing it now.
[tiller] 2019/04/05 10:14:30 preparing install for cluster-monitoring
[storage] 2019/04/05 10:14:30 getting release history for "cluster-monitoring"
[main] 2019/04/05 10:14:30 Starting Tiller v2.10+unreleased (tls=false)
[main] 2019/04/05 10:14:30 GRPC listening on :36244
[main] 2019/04/05 10:14:30 Probes listening on :57080
[main] 2019/04/05 10:14:30 Storage driver is ConfigMap
[main] 2019/04/05 10:14:30 Max history per release is 0
[tiller] 2019/04/05 10:14:30 failed install prepare step: Could not get apiVersions from Kubernetes: the server is currently unable to handle the request
2019/04/05 10:14:30 [ERROR] AppController p-5f5sr/cluster-monitoring [helm-controller] failed with : failed to install app cluster-monitoring. Error: Could not get apiVersions from Kubernetes: the server is currently unable to handle the request
```

**Comment by loganhz** [comment] 2019-04-05 10:20
@gstorme It says `the server is currently unable to handle the request`. Can you look at the cluster dashboard please? I guess ETCD or APIserver is unhealthy. Can you try to ssh to the apiserver node and run `top` to check if the node is very busy?

**Comment by gstorme** [comment] 2019-04-05 10:43
All components were displayed as healthy, and apiserver node was not busy.
This is a new install (1 rancher + 1 etcd/controlplane + 2 workers) without any applications deployed on it yet.

I disabled monitoring, and re-enabled it after I saw the cluster-monitoring & monitoring-operator apps were not listed anymore under apps in the cluster system namespace.
Logs show different errors now.

```
[main] 2019/04/05 10:36:49 Starting Tiller v2.10+unreleased (tls=false)
[main] 2019/04/05 10:36:49 GRPC listening on :37027
[main] 2019/04/05 10:36:49 Probes listening on :46029
[main] 2019/04/05 10:36:49 Storage driver is ConfigMap
[main] 2019/04/05 10:36:49 Max history per release is 0
[main] 2019/04/05 10:36:49 Starting Tiller v2.10+unreleased (tls=false)
[main] 2019/04/05 10:36:49 GRPC listening on :41333
[main] 2019/04/05 10:36:49 Probes listening on :54863
[main] 2019/04/05 10:36:49 Storage driver is ConfigMap
[main] 2019/04/05 10:36:49 Max history per release is 0
[tiller] 2019/04/05 10:36:49 getting history for release monitoring-operator
[storage] 2019/04/05 10:36:49 getting release history for "monitoring-operator"
Release "monitoring-operator" does not exist. Installing it now.
[tiller] 2019/04/05 10:36:49 preparing install for monitoring-operator
[storage] 2019/04/05 10:36:49 getting release history for "monitoring-operator"
[tiller] 2019/04/05 10:36:49 rendering rancher-monitoring chart using values
[tiller] 2019/04/05 10:36:49 performing install for monitoring-operator
[tiller] 2019/04/05 10:36:49 executing 0 crd-install hooks for monitoring-operator
[tiller] 2019/04/05 10:36:49 hooks complete for crd-install monitoring-operator
[tiller] 2019/04/05 10:36:49 getting history for release cluster-monitoring
[storage] 2019/04/05 10:36:49 getting release history for "cluster-monitoring"
Release "cluster-monitoring" does not exist. Installing it now.
[tiller] 2019/04/05 10:36:49 preparing install for cluster-monitoring
[storage] 2019/04/05 10:36:49 getting release history for "cluster-monitoring"
[tiller] 2019/04/05 10:36:49 rendering rancher-monitoring chart using values
2019/04/05 10:36:49 info: manifest "rancher-monitoring/templates/metrics-service.yaml" is empty. Skipping.
2019/04/05 10:36:49 info: manifest "rancher-monitoring/charts/grafana/templates/pvc.yaml" is empty. Skipping.
2019/04/05 10:36:49 info: manifest "rancher-monitoring/templates/deployment.yaml" is empty. Skipping.
2019/04/05 10:36:49 info: manifest "rancher-monitoring/templates/rbac.yaml" is empty. Skipping.
2019/04/05 10:36:49 info: manifest "rancher-monitoring/templates/servicemonitor.yaml" is empty. Skipping.
2019/04/05 10:36:49 info: manifest "rancher-monitoring/charts/grafana/templates/rbac.yaml" is empty. Skipping.
[tiller] 2019/04/05 10:36:49 performing install for cluster-monitoring
[tiller] 2019/04/05 10:36:49 executing 0 crd-install hooks for cluster-monitoring
[tiller] 2019/04/05 10:36:49 hooks complete for crd-install cluster-monitoring
[tiller] 2019/04/05 10:36:50 failed install perform step: validation failed: unable to recognize "": no matches for kind "ServiceMonitor" in version "monitoring.coreos.com/v1"
2019/04/05 10:36:50 [ERROR] AppController p-5f5sr/monitoring-operator [helm-controller] failed with : failed to install app monitoring-operator. Error: validation failed: unable to recognize "": no matches for kind "ServiceMonitor" in version "monitoring.coreos.com/v1"

[tiller] 2019/04/05 10:36:50 failed install perform step: validation failed: [unable to recognize "": no matches for kind "Prometheus" in version "monitoring.coreos.com/v1", unable to recognize "": no matches for kind "PrometheusRule" in version "monitoring.coreos.com/v1", unable to recognize "": no matches for kind "PrometheusRule" in version "monitoring.coreos.com/v1", unable to recognize "": no matches for kind "PrometheusRule" in version "monitoring.coreos.com/v1", unable to recognize "": no matches for kind "ServiceMonitor" in version "monitoring.coreos.com/v1", unable to recognize "": no matches for kind "ServiceMonitor" in version "monitoring.coreos.com/v1", unable to recognize "": no matches for kind "ServiceMonitor" in version "monitoring.coreos.com/v1", unable to recognize "": no matches for kind "ServiceMonitor" in version "monitoring.coreos.com/v1", unable to recognize "": no matches for kind "ServiceMonitor" in version "monitoring.coreos.com/v1", unable to recognize "": no matches for kind "ServiceMonitor" in version "monitoring.coreos.com/v1", unable to recognize "": no matches for kind "ServiceMonitor" in version "monitoring.coreos.com/v1", unable to recognize "": no matches for kind "ServiceMonitor" in version "monitoring.coreos.com/v1", unable to recognize "": no matches for kind "ServiceMonitor" in version "monitoring.coreos.com/v1", unable to recognize "": no matches for kind "ServiceMonitor" in version "monitoring.coreos.com/v1"]
2019/04/05 10:36:50 [ERROR] AppController p-5f5sr/cluster-monitoring [helm-controller] failed with : failed to install app cluster-monitoring. Error: validation failed: [unable to recognize "": no matches for kind "Prometheus" in version "monitoring.coreos.com/v1", unable to recognize "": no matches for kind "PrometheusRule" in version "monitoring.coreos.com/v1", unable to recognize "": no matches for kind "PrometheusRule" in version "monitoring.coreos.com/v1", unable to recognize "": no matches for kind "PrometheusRule" in version "monitoring.coreos.com/v1", unable to recognize "": no matches for kind "ServiceMonitor" in version "monitoring.coreos.com/v1", unable to recognize "": no matches for kind "ServiceMonitor" in version "monitoring.coreos.com/v1", unable to recognize "": no matches for kind "ServiceMonitor" in version "monitoring.coreos.com/v1", unable to recognize "": no matches for kind "ServiceMonitor" in version "monitoring.coreos.com/v1", unable to recognize "": no matches for kind "ServiceMonitor" in version "monitoring.coreos.com/v1", unable to recognize "": no matches for kind "ServiceMonitor" in version "monitoring.coreos.com/v1", unable to recognize "": no matches for kind "ServiceMonitor" in version "monitoring.coreos.com/v1", unable to recognize "": no matches for kind "ServiceMonitor" in version "monitoring.coreos.com/v1", unable to recognize "": no matches for kind "ServiceMonitor" in version "monitoring.coreos.com/v1", unable to recognize "": no matches for kind "ServiceMonitor" in version "monitoring.coreos.com/v1"]

[main] 2019/04/05 10:36:50 Starting Tiller v2.10+unreleased (tls=false)
[main] 2019/04/05 10:36:50 GRPC listening on :59578
[main] 2019/04/05 10:36:50 Probes listening on :48780
[main] 2019/04/05 10:36:50 Storage driver is ConfigMap
[main] 2019/04/05 10:36:50 Max history per release is 0
[tiller] 2019/04/05 10:36:50 getting history for release monitoring-operator
[storage] 2019/04/05 10:36:50 getting release history for "monitoring-operator"
Release "monitoring-operator" does not exist. Installing it now.
[tiller] 2019/04/05 10:36:50 preparing install for monitoring-operator
[storage] 2019/04/05 10:36:50 getting release history for "monitoring-operator"
[tiller] 2019/04/05 10:36:50 rendering rancher-monitoring chart using values
[tiller] 2019/04/05 10:36:50 performing install for monitoring-operator
[tiller] 2019/04/05 10:36:50 executing 0 crd-install hooks for monitoring-operator
[tiller] 2019/04/05 10:36:50 hooks complete for crd-install monitoring-operator
[tiller] 2019/04/05 10:36:51 failed install perform step: validation failed: unable to recognize "": no matches for kind "ServiceMonitor" in version "monitoring.coreos.com/v1"
2019/04/05 10:36:51 [ERROR] AppController p-5f5sr/monitoring-operator [helm-controller] failed with : failed to install app monitoring-operator. Error: validation failed: unable to recognize "": no matches for kind "ServiceMonitor" in version "monitoring.coreos.com/v1"

[main] 2019/04/05 10:36:52 Starting Tiller v2.10+unreleased (tls=false)
[main] 2019/04/05 10:36:52 GRPC listening on :52920
[main] 2019/04/05 10:36:52 Probes listening on :51016
[main] 2019/04/05 10:36:52 Storage driver is ConfigMap
[main] 2019/04/05 10:36:52 Max history per release is 0
[tiller] 2019/04/05 10:36:52 getting history for release monitoring-operator
[storage] 2019/04/05 10:36:52 getting release history for "monitoring-operator"
Release "monitoring-operator" does not exist. Installing it now.
[tiller] 2019/04/05 10:36:52 preparing install for monitoring-operator
[storage] 2019/04/05 10:36:52 getting release history for "monitoring-operator"
[tiller] 2019/04/05 10:36:52 rendering rancher-monitoring chart using values
[tiller] 2019/04/05 10:36:52 performing install for monitoring-operator
[tiller] 2019/04/05 10:36:52 executing 0 crd-install hooks for monitoring-operator
[tiller] 2019/04/05 10:36:52 hooks complete for crd-install monitoring-operator
2019/04/05 10:36:52 [ERROR] ClusterController c-xbf8j [cluster-monitoring-handler] failed with : unable to sync Cluster c-xbf8j(engineering-internal): failed to detect the installation status of monitoring components: [Grafana Deployment isn't deployed, Node Exporter DaemonSet isn't deployed, Kube State Exporter Deployment isn't deployed, Prometheus StatefulSet isn't deployed]
[main] 2019/04/05 10:36:53 Starting Tiller v2.10+unreleased (tls=false)
[main] 2019/04/05 10:36:53 GRPC listening on :52573
[main] 2019/04/05 10:36:53 Probes listening on :46009
[main] 2019/04/05 10:36:53 Storage driver is ConfigMap
[main] 2019/04/05 10:36:53 Max history per release is 0
[tiller] 2019/04/05 10:36:53 getting history for release cluster-monitoring
[storage] 2019/04/05 10:36:53 getting release history for "cluster-monitoring"
Release "cluster-monitoring" does not exist. Installing it now.
[tiller] 2019/04/05 10:36:53 preparing install for cluster-monitoring
[storage] 2019/04/05 10:36:53 getting release history for "cluster-monitoring"
[tiller] 2019/04/05 10:36:53 rendering rancher-monitoring chart using values
2019/04/05 10:36:53 info: manifest "rancher-monitoring/templates/servicemonitor.yaml" is empty. Skipping.
2019/04/05 10:36:53 info: manifest "rancher-monitoring/templates/rbac.yaml" is empty. Skipping.
2019/04/05 10:36:53 info: manifest "rancher-monitoring/templates/deployment.yaml" is empty. Skipping.
2019/04/05 10:36:53 info: manifest "rancher-monitoring/templates/metrics-service.yaml" is empty. Skipping.
2019/04/05 10:36:53 info: manifest "rancher-monitoring/charts/grafana/templates/pvc.yaml" is empty. Skipping.
[tiller] 2019/04/05 10:36:53 failed install perform step: validation failed: unable to recognize "": no matches for kind "ServiceMonitor" in version "monitoring.coreos.com/v1"
2019/04/05 10:36:53 [ERROR] AppController p-5f5sr/monitoring-operator [helm-controller] failed with : failed to install app monitoring-operator. Error: validation failed: unable to recognize "": no matches for kind "ServiceMonitor" in version "monitoring.coreos.com/v1"
```

**Comment by loganhz** [comment] 2019-04-05 10:56
It looks like the Prometheus crd is not installed successfully.
I think your cluster agent is suffering some network issue.
A workaround should be delete the pod manually and it will recreate.

Can you look at the log in cluster-agent pod under System project ?

![image](https://user-images.githubusercontent.com/21168270/55623033-5d35c900-57d4-11e9-95ac-90cb34128a51.png)

**Comment by gstorme** [comment] 2019-04-05 12:12
You're right, the cluster-agent pod could not resolve the rancher server hostname.
I re-created the cluster after fixing the network.
Apologies, monitoring is successfully installed now, very niice.

**Comment by loganhz** [comment] 2019-04-05 12:13
Thanks for your update!

**Comment by rammaram06** [comment] 2019-04-05 14:36
Hey @loganhz any update on when can I expect this issue to be fixed? Will it help If I upgrade to 2.2.1? Thanks for your help!

**Comment by loganhz** [comment] 2019-04-05 14:38
@rammaram06 Please try https://github.com/rancher/rancher/issues/19362#issuecomment-480234140

**Comment by arno01** [comment] 2019-06-12 20:23
Looks like I've got the same issue with Rancher ``v2.2.4`` as soon as I've set ``"enableClusterMonitoring":true`` in the cluster config. I have an automated Rancher deployment by Terraform.

Logs https://gist.github.com/arno01/ed647eb5e84863f1d9c2cfe0e99cbdf7

**Comment by jiaqiluo** [comment] 2019-08-01 02:36
per the conversion with @loganhz, this issue is not specificated to airgap. 

Test cases:
- upgrade Rancher server, enable the monitoring right after the upgrade.
- fresh install, as soon as the cluster is active, enable the monitoring

**Comment by rammaram06** [comment] 2019-08-26 05:27
@loganhz  I tried removing the pod but its still failing with unable to ping rancher server hostname,
could you please let me know how to fix this error. I'm using Rancher 2.2.7 version.

`INFO: Environment: CATTLE_ADDRESS=10.42.1.2 CATTLE_CA_CHECKSUM=37a8671a72d8fa2eedd3e9d8576bb84f2dbd9e61c3670fed1865ef057f9a4adf CATTLE_CLUSTER=true CATTLE_INTERNAL_ADDRESS= CATTLE_K8S_MANAGED=true CATTLE_NODE_NAME=cattle-cluster-agent-55d486b877-7vv4h CATTLE_SERVER=https://testrancher.xxxx.org
INFO: Using resolv.conf: nameserver 10.43.0.10 search cattle-system.svc.cluster.local svc.cluster.local cluster.local va.xxxx.org options ndots:5
ERROR: https://testrancher.xxxx.org/ping is not accessible (Could not resolve host: testrancher.xxxx.org)`

**Comment by loganhz** [comment] 2019-08-29 05:25
> @loganhz @guangbochen I tried removing the cluster agent pod but its still failing with unable to ping rancher server hostname,
> could you please let me know how to fix this error. I'm using Rancher 2.2.7 version.
> 
> I have opened all the ports listed in requirements.
> 
> `INFO: Environment: CATTLE_ADDRESS=10.42.1.2 CATTLE_CA_CHECKSUM=37a8671a72d8fa2eedd3e9d8576bb84f2dbd9e61c3670fed1865ef057f9a4adf CATTLE_CLUSTER=true CATTLE_INTERNAL_ADDRESS= CATTLE_K8S_MANAGED=true CATTLE_NODE_NAME=cattle-cluster-agent-55d486b877-7vv4h CATTLE_SERVER=https://testrancher.xxxx.org INFO: Using resolv.conf: nameserver 10.43.0.10 search cattle-system.svc.cluster.local svc.cluster.local cluster.local va.xxxx.org options ndots:5 ERROR: https://testrancher.xxxx.org/ping is not accessible (Could not resolve host: testrancher.xxxx.org)`

could you file another issue for this, please? Thanks

**Comment by jiaqiluo** [comment] 2019-08-29 16:54
Cannot reproduce the error the issue describes.
It looks like the issue is not a general problem but highly related to the user's cluster' networking, and it could be fixed by either deleting the hanging pod or re-enable the cluster monitoring. 
Therefore, the issue is closed for now. New issues will be made if necessary.

**Closed by jiaqiluo** 2019-08-29 16:54 UTC
Labels: [zube]: To Test, area/monitoring, kind/bug, team/cn
