### ISSUE TITLE
Cluster monitoring app redeploys multiple time when system-default-registry is set

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#20202] opened 2019-05-13 18:19 UTC
Rancher server version - v2.2.2-patch1-rc2

Steps to reproduce the problem:
Have global settings -  `system-default-registry` set .
Create a DO cluster with 1 node having all roles and 1 worker node.
Enable monitoring for the cluster.
Once cluster monitoring is enabled , notice that `cluster-monitoring` redeployed multiple times.
This can be checked by seeing that the  `cluster-monitoring` app has multiple revisions and also there are multiple config maps (relating to this app) created - `cluster-monitoring.v[n]`
Deploy more workloads/App.

This also results in  cluster monitoring to be redeployed.

**Comment by sangeethah** [comment] 2019-05-13 18:25
To workaround this issue of cluster monitoring app redeploying multiple times, do the following steps:

Disable monitoring.
While enabled monitoring , add a variable `global.systemDefaultRegistry` to point to the `system-default-registry` by going to "Show advanced option"

<img width="1267" alt="Screen Shot 2019-05-13 at 11 21 44 AM" src="https://user-images.githubusercontent.com/4266958/57644604-563b6c80-7571-11e9-842d-35c19249187d.png">

After this , cluster monitoring app will not redeploys multiple time when monitoring is enabled and  when workloads/app gets deployed.

**Comment by jiaqiluo** [comment] 2019-05-13 22:10
The issue is reproduced on an HA setup running Rancher:v2.2.2-patch1-rc2 and the workaround is also confirmed to work.

**Comment by alena1108** [comment] 2019-05-14 03:15
@sangeethah per @orangedeng the issue was resolved in release/v2.2 as a part of some earlier commit. Can you give it a test in v2.2.3-rc9

**Comment by jiaqiluo** [comment] 2019-05-14 17:49
The bug fix is validated on v2.2.4-rc1

Following the same steps as the ticket describes the cluster-monitoring app does not redeploy.

**Closed by jiaqiluo** 2019-05-14 17:49 UTC
Labels: [zube]: To Test, kind/bug, status/resolved, team/cn
