### ISSUE TITLE
Sidekick is not exposed as "Link" to the "master" service.

### ISSUE THREAD

**Issue by y8** [rancher/rancher#3024] opened 2015-12-15 01:39 UTC
For example: 

````yml
mongodb:
  tty: true
  image: mongo:3.2.0
  stdin_open: true
app:
  labels:
    io.rancher.sidekicks: mongodb
  tty: true
  image: example.net/my-app
  stdin_open: true
````

With this configuration environment variables, like `MONGODB_PORT_27017_TCP_ADDR` are not set in `app` containers.

Since there no way to explicitly link `mongodb` to `app ` in the Rancher UI, it's expected that 
sidekick will be automatically linked to the `mongodb`, so environment variables will be available.

**Comment by alena1108** [comment] 2015-12-16 23:26
Duplicate of https://github.com/rancher/rancher/issues/1589

**Closed by alena1108** 2015-12-16 23:26 UTC
