### ISSUE TITLE
[BUG] k3s provisioned clusters from Rancher do not have taints on etcd/cp nodes

### ISSUE THREAD

**Issue by sowmyav27** [rancher/rancher#38681] opened 2022-08-21 20:23 UTC
**Rancher Server Setup**
- Rancher version: 2.6.7
- Installation option (Docker install/Helm Chart): docker install

**Information about the Cluster**
- Kubernetes version: `v1.24.2+k3s2`
- Cluster Type (Local/Downstream): k3s node driver linode/custom cluster 

**User Information**
- What is the role of the user logged in? (Admin/Cluster Owner/Cluster Member/Project Owner/Project Member/Custom) admin

**Describe the bug**
[BUG] k3s provisioned clusters from Rancher do not have taints on etcd/cp nodes

**To Reproduce**
1. Deploy a node driver or k3s cluster from Rancher.
2. The etcd/cp nodes do not have taints
```
node-role.kubernetes.io/control-plane=:NoSchedule 
node-role.kubernetes.io/etcd=:NoExecute
```

**Result**
The etcd/cp nodes should have the taints, so user deployed workloads do not schedule on them.

**Comment by Oats87** [comment] 2022-09-21 22:38
https://github.com/rancher/rancher/blob/a678d0e12fe21936f09ae0e906bc420e43d7d35c/pkg/provisioningv2/rke2/planner/planner.go#L855 

For whatever reason, we only taint RKE2...

**Comment by jakefhyde** [comment] 2022-09-23 22:51
### Root cause

k3s clusters did not have taints applied to etcd/controlplane nodes.

### What was fixed, or what changes have occurred

Ensure k3s clusters also have taints applied to also have taints.

### Areas or cases that should be tested

Manually tested by provisioning all 7 permutations of node roles:

| etcd               | controlplane       | worker             | node-role.kubernetes.io/control-plane=:NoSchedule | node-role.kubernetes.io/etcd=:NoExecute |
|--------------------|--------------------|--------------------|---------------------------------------------------|-----------------------------------------|
| :heavy_check_mark: |                    |                    |                                                   | :heavy_check_mark:                      |
|                    | :heavy_check_mark: |                    | :heavy_check_mark:                                |                                         |
|                    |                    | :heavy_check_mark: |                                                   |                                         |
| :heavy_check_mark: | :heavy_check_mark: |                    | :heavy_check_mark:                                | :heavy_check_mark:                      |
| :heavy_check_mark: |                    | :heavy_check_mark: |                                                   |                                         |
|                    | :heavy_check_mark: | :heavy_check_mark: |                                                   |                                         |
| :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: |                                                   |                                         |

### What areas could experience regressions?

RKE2 should still have taints (which was tested)

### Are the repro steps accurate/minimal?
:heavy_check_mark:

**Comment by jameson-mcghee** [comment] 2022-09-27 20:29
I was able to reproduce this issue on v2.6.7 by following the Steps to Reproduce. However, following the Steps to Reproduce on v2.-7head (Commit ID: c567ef3), this issue was no longer reproducible. Therefore this issue was marked as Done.

Steps to Reproduce:
* On a Rancher v2.6.7 server, navigate to the Cluster Management --> Cloud Credentials page, and click the Created button
* Select the Amazon option
* Input a unique name as well as valid Access Key, Secret Key, and Default Region info, and then click the Create button
* Navigate to the Cluster Management --> Clusters page, and click the Create button
* Toggle to RKE2/K3s and then select Amazon EC2
* Input a unique name, uncheck the Control Plane and Worker Roles, and input a valid VPC/Subnet
* Click the "+" for a new Machine Pool
* In the new Machine Pool, uncheck the Worker Role, check the Control Plane Role, and input a valid VPC/Subnet
* Click the "+" for a new Machine Pool
* In the new Machine Pool, input a valid VPC/Subnet
* Set the Kubernetes Version to v1.24.4+k3s1, and then click the Create button
* Once the cluster is Active, navigate to the Explore Cluster --> Nodes page for the cluster
-- Note that there are no Taints listed under the ETCD or Control Plane node names

**v2.6.7:**
![image.png](https://zube.io/files/rancher/7bfe35729d5efffe9dd0cb2b9c186503-image.png)
![image.png](https://zube.io/files/rancher/5b17a96bf5b79853345f46c75364a80a-image.png)
![image.png](https://zube.io/files/rancher/e448ef8db8c1cce528782385f9a1a405-image.png)

**v2.7-head (Commit ID: c567ef3):**
![image.png](https://zube.io/files/rancher/b577f4119f73314db1c210f0b81c86fb-image.png)
![image.png](https://zube.io/files/rancher/d17e4d7cd9a63874791cfdd234ea7495-image.png)
![image.png](https://zube.io/files/rancher/348c854e18b255bacea97249c90c020e-image.png)

**Closed** 2022-09-27 20:36 UTC
Labels: kind/bug, priority/1, area/k3s, [zube]: QA Working, QA/S, team/area2

**Comment by jameson-mcghee** [comment] 2022-12-02 21:23
Follow up comment. I verified that this issue also does not reproduce on Rancher `v2.7-head` (Commit ID: 38979f8) when using K8s `v1.24.8+k3s1`.

`v2.7-head` (Commit ID: 38979f8):
![image](https://user-images.githubusercontent.com/13294321/205388802-4dfd90e9-6270-4ac1-a2ac-7611c8a605d7.png)
