### ISSUE TITLE
Rancher 2.2 prometheus-agent container trying to bind to wrong IP address

### ISSUE THREAD

**Issue by troy256** [rancher/rancher#19672] opened 2019-04-17 13:02 UTC
**What kind of request is this (question/bug/enhancement/feature request):**
bug

**Steps to reproduce (least amount of steps as possible):**
Enable Monitoring on an on-prem Rancher v2.2.1 cluster. 

**Result:**
The prometheus-agent container in the prometheus-cluster-monitoring-0 pod never reaches a Running state.  It continuously restarts.  "View Logs" on the prometheus-agent container shows: 

listen tcp 10.62.157.x:6060: bind: cannot assign requested address
http: proxy error: dial tcp 10.62.157.x:9090: connect: connection refused
(last message repeats)

**Other details that may be helpful:**
In our environment a nslookup on localhost resolves to an actual IP address (10.62.157.x) in this case.  I realize that is a little wonky, but if the --proxy-url arg is changed to http://localhost.:9090 (dot after localhost) it will bind it to the localhost and return 127.0.0.1 and the prometheus-agent container starts and runs at this point.  Including the dot after localhost would resolve the issue for us.

If I change --proxy-url to http://localhost.:9090 everything starts and runs successfully.  However, after a few minutes the prometheus-agent container state becomes "Notready" and if I look at the yaml I see it has reverted back to the old value for --proxy-url and gets the same error as before.

**Environment information**
- Rancher version v2.2.1
- Installation option (single install/HA): single install

**Cluster information**
- Cluster type (Custom on-prem):
- Machine type (cloud/VM/metal) and specifications (CPU/memory): Ubuntu 18.04 VMs, 2 CPUs, 4 GB mem
- Kubernetes version (use `kubectl version`): 1.13.15
- Docker version (use `docker version`): 18.9.3

**Comment by superseb** [comment] 2019-04-17 13:39
Duplicate of https://github.com/rancher/rancher/issues/19672

**Closed by superseb** 2019-04-17 13:39 UTC

**Comment by troy256** [comment] 2019-04-17 15:03
What is this a duplicate of?  The think is to the same issue #.

**Comment by superseb** [comment] 2019-04-17 15:06
Sorry its https://github.com/rancher/rancher/issues/19243
