### ISSUE TITLE
How to rotate cattle-webhook-tls certificate when it has expired?

### ISSUE THREAD

**Issue by petertang2012** [rancher/rancher#35068] opened 2021-10-07 09:57 UTC
**Rancher Server Setup**
- Rancher version: 2.5.8
- Installation option (Docker install/Helm Chart): Helm Chart
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): EKS 
- Proxy/Cert Details: External

**Information about the Cluster**
- Kubernetes version:1.20
- Cluster Type (Local/Downstream): Local
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider): N/A

**Describe the bug**

the cluster webhook certificate seems to have expired and all RBAC operations are now blocked with the error message `Internal error occurred: failed calling webhook "rancherauth.cattle.io": Post "https://rancher-webhook.cattle-system.svc:443/v1/webhook/validation?timeout=10s": x509: certificate has expired or is not yet valid`

Culprit seems to be this secret containing webhook tls certificate expiring: 
![image](https://user-images.githubusercontent.com/1773902/136362504-1b87afe3-e4ca-4c74-bdb0-eb80666fa91d.png)

**To Reproduce**
 
Install Rancher via HELM chart and wait for a year.

**Result**
Webhook certificate expires and no instructions from Rancher documentation on how to rotate rancher webhook certificate secret.

**Expected Result**

I searched a lot of places looking for instructions on how to rotate the certificate but was not able to find any.

SURE-3475
SURE-3737
SURE-3790
SURE-3528

**Comment by gregod-com** [comment] 2021-10-07 12:42
same problem here, cattle-webhook-tls is expired and rancher-webhook deployment just loops saying `Creating new TLS secret for cattle-webhook-tls` without any warning or error message

**Comment by xvi0101** [comment] 2021-10-14 11:30
hi
@harridu I followed your workaround but secrets couldn't be created, it's trying to create secret over and over again. Any ideas?

```
time="2021-10-14T11:18:04Z" level=info msg="Rancher-webhook version dev (HEAD) is starting"
time="2021-10-14T11:18:04Z" level=info msg="Listening on :9443"
**time="2021-10-14T11:18:04Z" level=info msg="Creating new TLS secret for cattle-webhook-tls (count: 1): map[listener.cattle.io/cn-rancher-webhook.cattle-system.svc:rancher-webhook.cattle-system.svc listener.cattle.io/hash:7aaa4f3db00be92fc19d8a277022303e8c09763c46838b928cb6b5566a34ae31]"**
time="2021-10-14T11:18:05Z" level=info msg="Starting management.cattle.io/v3, Kind=GlobalRole controller"
time="2021-10-14T11:18:05Z" level=info msg="Starting apiextensions.k8s.io/v1beta1, Kind=CustomResourceDefinition controller"
time="2021-10-14T11:18:05Z" level=info msg="Starting rbac.authorization.k8s.io/v1, Kind=ClusterRoleBinding controller"
time="2021-10-14T11:18:05Z" level=info msg="Starting rbac.authorization.k8s.io/v1, Kind=Role controller"
time="2021-10-14T11:18:05Z" level=info msg="Starting management.cattle.io/v3, Kind=RoleTemplate controller"
time="2021-10-14T11:18:05Z" level=info msg="Starting /v1, Kind=Secret controller"
time="2021-10-14T11:18:05Z" level=info msg="Sleeping for 15 seconds then applying webhook config"
time="2021-10-14T11:18:05Z" level=info msg="Starting apiregistration.k8s.io/v1, Kind=APIService controller"
time="2021-10-14T11:18:05Z" level=info msg="Starting rbac.authorization.k8s.io/v1, Kind=ClusterRole controller"
time="2021-10-14T11:18:05Z" level=info msg="Starting rbac.authorization.k8s.io/v1, Kind=RoleBinding controller"
time="2021-10-14T11:18:14Z" level=info msg="Creating new TLS secret for cattle-webhook-tls (count: 1): map[listener.cattle.io/cn-rancher-webhook.cattle-system.svc:rancher-webhook.cattle-system.svc listener.cattle.io/hash:7aaa4f3db00be92fc19d8a277022303e8c09763c46838b928cb6b5566a34ae31]"
time="2021-10-14T11:18:24Z" level=info msg="Creating new TLS secret for cattle-webhook-tls (count: 1): map[listener.cattle.io/cn-rancher-webhook.cattle-system.svc:rancher-webhook.cattle-system.svc listener.cattle.io/hash:7aaa4f3db00be92fc19d8a277022303e8c09763c46838b928cb6b5566a34ae31]"
time="2021-10-14T11:18:34Z" level=info msg="Creating new TLS secret for cattle-webhook-tls (count: 1): map[listener.cattle.io/cn-rancher-webhook.cattle-system.svc:rancher-webhook.cattle-system.svc listener.cattle.io/hash:7aaa4f3db00be92fc19d8a277022303e8c09763c46838b928cb6b5566a34ae31]"
time="2021-10-14T11:18:44Z" level=info msg="Creating new TLS secret for cattle-webhook-tls (count: 1): map[listener.cattle.io/cn-rancher-webhook.cattle-system.svc:rancher-webhook.cattle-system.svc listener.cattle.io/hash:7aaa4f3db00be92fc19d8a277022303e8c09763c46838b928cb6b5566a34ae31]"
time="2021-10-14T11:18:54Z" level=info msg="Creating new TLS secret for cattle-webhook-tls (count: 1): map[listener.cattle.io/cn-rancher-webhook.cattle-system.svc:rancher-webhook.cattle-system.svc listener.cattle.io/hash:7aaa4f3db00be92fc19d8a277022303e8c09763c46838b928cb6b5566a34ae31]"
time="2021-10-14T11:19:04Z" level=info msg="Creating new TLS secret for cattle-webhook-tls (count: 1): map[listener.cattle.io/cn-rancher-webhook.cattle-system.svc:rancher-webhook.cattle-system.svc listener.cattle.io/hash:7aaa4f3db00be92fc19d8a277022303e8c09763c46838b928cb6b5566a34ae31]"
time="2021-10-14T11:19:14Z" level=info msg="Creating new TLS secret for cattle-webhook-tls (count: 1): map[listener.cattle.io/cn-rancher-webhook.cattle-system.svc:rancher-webhook.cattle-system.svc listener.cattle.io/hash:7aaa4f3db00be92fc19d8a277022303e8c09763c46838b928cb6b5566a34ae31]"
time="2021-10-14T11:19:24Z" level=info msg="Creating new TLS secret for cattle-webhook-tls (count: 1): map[listener.cattle.io/cn-rancher-webhook.cattle-system.svc:rancher-webhook.cattle-system.svc listener.cattle.io/hash:7aaa4f3db00be92fc19d8a277022303e8c09763c46838b928cb6b5566a34ae31]"
time="2021-10-14T11:19:34Z" level=info msg="Creating new TLS secret for cattle-webhook-tls (count: 1): map[listener.cattle.io/cn-rancher-webhook.cattle-system.svc:rancher-webhook.cattle-system.svc listener.cattle.io/hash:7aaa4f3db00be92fc19d8a277022303e8c09763c46838b928cb6b5566a34ae31]"
time="2021-10-14T11:19:44Z" level=info msg="Creating new TLS secret for cattle-webhook-tls (count: 1): map[listener.cattle.io/cn-rancher-webhook.cattle-system.svc:rancher-webhook.cattle-system.svc listener.cattle.io/hash:7aaa4f3db00be92fc19d8a277022303e8c09763c46838b928cb6b5566a34ae31]"
time="2021-10-14T11:19:55Z" level=info msg="Creating new TLS secret for cattle-webhook-tls (count: 1): map[listener.cattle.io/cn-rancher-webhook.cattle-system.svc:rancher-webhook.cattle-system.svc listener.cattle.io/hash:7aaa4f3db00be92fc19d8a277022303e8c09763c46838b928cb6b5566a34ae31]"
time="2021-10-14T11:20:05Z" level=info msg="Creating new TLS secret for cattle-webhook-tls (count: 1): map[listener.cattle.io/cn-rancher-webhook.cattle-system.svc:rancher-webhook.cattle-system.svc
```

**Comment by nickgerace** [comment] 2021-10-15 16:36
SURE-3475

**Comment by nickgerace** [comment] 2021-11-03 19:08
Since this is an important issue and needs to be solved, we'll be implementing a partial fix via [this child issue](https://github.com/rancher/rancher/issues/35366) in the meantime to extend the certificate expiration to 10 years. It is a self-signed cert, so the security concerns are minimal. Ideally, we will fix this issue as well (likely via a weekly CronJob that checks if the cert will expire in <30d in advance). Thank you all for your patience.

**Comment by Kampfmoehre** [comment] 2021-11-22 08:17
I tried following the steps here and deleted the `cattle-webhook-tls` secret but now the pod is stuck and repeats the same message about creating the new secret:
```
time="2021-11-22T08:11:40Z" level=info msg="Creating new TLS secret for cattle-webhook-tls (count: 1): map[listener.cattle.io/cn-rancher-webhook.cattle-system.svc:rancher-webhook.cattle-system.svc listener.cattle.io/hash:7aaa4f3db00be92fc19d8a277022303e8c09763c46838b928cb6b5566a34ae31]" 
```

I also tried recreating the validatingwebhookconfiguration but it does not seem to exist. Running `kubectl get validatingwebhookconfiguration rancher.cattle.io` just responds with `Error from server (NotFound): validatingwebhookconfigurations.admissionregistration.k8s.io "rancher.cattle.io" not found`.

Any ideas what I could try next? I am not able to update any of our clusters via Rancher UI since it runs in a timeout: context deadline exceeded.

I deleted the pod a second time but the new pod also gets stuck with creating the new secret.

**Comment by McSlow** [comment] 2021-11-23 10:30
@Kampfmoehre when you're already on 2.6.0, you have to downgrade the pod's image to 0.1.1 as @xvi0101 stated. you can do this using the ui if you want. If you only change the pod you can kill the pod after successful cert creation, then deployment recreates a 0.2.0 one. We had this on both 2.5.9 and 2.6.0 today, 2.5.9 works without downgrading, 2.6.0 like said above.
Btw.: We had this bug last year, too, and it seems to be there since 2.2. I'm loosing a bit of trust in rancher.

**Comment by Kampfmoehre** [comment] 2021-11-23 12:36
Thx @McSlow , it is working again now

**Comment by nickgerace** [comment] 2021-11-24 14:56
The partial fix (NotAfter extension) will be included in `v2.6.3`. For the following or future release: the proposed fix for the actual rotation issue has been merged and needs to be tested (https://github.com/rancher/dynamiclistener/pull/49). If validation passes after module bump in `rancher/webhook`, then this issue can be moved to "To Test".

**Comment by adriaaneyermede** [comment] 2021-12-03 14:41
I just rolled out a latest release on rancher, and this webhook issue still persists:

failed to create fleet-default/myclustername cluster.x-k8s.io/v1alpha4, Kind=Cluster for rke-cluster fleet-default/medecreate: Internal error occurred: failed calling webhook "default.cluster.cluster.x-k8s.io": Post "https://webhook-service.cattle-system.svc:443/mutate-cluster-x-k8s-io-v1alpha4-cluster?timeout=10s": service "webhook-service" not found


When will this be fixed?

Or what is the current workaround or fix to actually build a cluster on rancher?

**Comment by cbron** [comment] 2021-12-30 22:23
This workaround will work, please let me or @genexpr know if you find an instance of that not being the case: https://rancher.com/docs/rancher/v2.6/en/troubleshooting/expired-webhook-certificates/


@adriaaneyermede that is a different error relating to the webhook service not existing on startup.

**Comment by genexpr** [comment] 2022-01-10 22:04
# QA testing

### Root cause
The webhook's dynamiclistener did not check if webhook's certificate is about to expire, because the certificate value had not
been set properly on the dynamiclistener server listener. 
### What was fixed, or what changes have occurred
The dynamiclistener has had a commit that we cherry-picked into a new version of webhook which is to be used in a new version of Rancher. 
### Areas or cases that should be tested
- Use a new v2.5.12 cluster
- Upgrade from v2.5.11 to v2.5.12

### What areas could experience regressions?
### Testing step
#### Use a new v2.5.12 cluster
Deploy a new v2.5.12 pre-release Rancher container.
Find the secret called `cattle-webhook-tls` in the `cattle-system` namespace.
Copy the certificate contents and decode them. You can use a site like `https://certificatedecoder.dev`.
Observe that `Expires On` shows a date 10 years from today.

You need to test that the webhook pod keeps renewing the certificate if necessary (if it is 30 days or fewer until expiration). Since your current certificate will expire in 10 years, you would have to wait for 10 years minus 30 days to see it renewed before it is set to expire.
Instead, delete the certificate secret (by hand or with `kubectl delete pod -n cattle-system -l app=rancher-webhook`).

Go to the `rancher-webhook` deployment in the `cattle-system` namespace.
Add an environment variable to it called `CATTLE_NEW_SIGNED_CERT_EXPIRATION_DAYS` and set its value to 2.
Save the deployment and observe that its pod is deleted and a new one is created in its place.

Check that the certificate has been recreated. Decode its contents and observe that it is valid for 2 days.
The webhook pod checks in on its certificate expiration every 6 hours. In 6 hours, you can observe that it has
updated (not recreated) the certificate and its `Expires On` date is extended by 2 days again.

Because the certificate is now only valid for 2 days, as you specified, you will see the webhook pod try to update it, extend its validity period by 2 days. It will keep doing this because 2 days is fewer than 30 days, so webhook thinks it's time to update it ahead of expiration.

To get a 10-year certificate, update the deployment again by removing the environment variable and save.
Absence of that variable means the pod should make a cert that is valid for 10 years, the default.

#### Upgrade from v2.511 to v2.5.12
Now get a new v2.5.11 cluster and upgrade it to v2.5.12.
The webhook app will be upgraded in a couple of minutes. Therefore, the `rancher-webhook` deployment will also
be upgraded and its pod recreated. However, the certificate will remain the same, since it already exists, has not
expired yet, and isn't 30 days within expiration. You can verify this by checking that the cert contents have not changed at all. But the new pod will now watch it for expiration. And 30 days before expiration, it will renew the cert.

Check the image of the pod made by the `rancher-webhook` deployment, make sure it is `v0.1.3-rc1` (the number after `rc` might be different).

Run the same routine with changing the deployment's `CATTLE_NEW_SIGNED_CERT_EXPIRATION_DAYS` variable to less than 30 and observe that in 6 hours, the secret will be updated (again, not recreated). Check its expiration date and ensure it's 10 years in the future.

**Closed as completed** 2022-01-14 14:00 UTC
Labels: kind/bug, internal, team/area1, area/webhook

**Comment by genexpr** [comment] 2022-01-14 21:59
### Release note

New and existing rancher-webhook deployments will automatically renew its TLS certificate when it is 30 or fewer days within expiration date.

**Comment by Turb0Fly** [comment] 2022-05-05 20:07
> Finally, I solved the problem modifying rancher-webhook deployment image **rancher-webhook:v0.2.0** to **rancher-webhook:v0.1.1**, once the cattle-webhook-tls secret is created I switched back the image version again. And the certificate is already renewed. But first of all, you have to remove cattle-webhook-tls secret.

This is actually what solved it for me. Thanks !!!

**Comment by Flavsditz** [comment] 2022-05-12 14:01
Any idea what to do if the `rancher-webhook` pod is not even there? Can I redeploy it by hand?

**Comment by maxsokolovsky** [comment] 2022-05-12 15:06
@Flavsditz, you could try redeploying the `rancher-webhook` deployment.

**Comment by gbit-is** [comment] 2023-01-03 12:37
Had this issue as well, backed up evertything prior to trying to fix it 

I ran these 3 steps

kubectl delete secrets -n cattle-system cattle-webhook-tls
kubectl delete pod -n cattle-system rancher-webhook-unique-id
kubectl delete mutatingwebhookconfiguration rancher.cattle.io


After step 1 and 2, the cattle-webhook-tls did not regenerate and the rancher-webhook pod was in a retry loop

after the third step the rancher-webook pod regenerated the cattle-webhook-tls and that fixed my problems
