### ISSUE TITLE
Infrastructure Stacks not starting

### ISSUE THREAD

**Issue by lextra** [rancher/rancher#10327] opened 2017-11-14 10:03 UTC
**Rancher versions:**
rancher/server:
1.6.2
rancher/agent:
1.2.2

**Infrastructure Stack versions:**
healthcheck:
0.3.0
ipsec:
0.11.2
network-services:
0.2.3
scheduler:
0.6.3
kubernetes (if applicable):

**Docker version: (`docker version`,`docker info` preferred)**
Containers: 8
 Running: 8
 Paused: 0
 Stopped: 0
Images: 11
Server Version: 17.03.1-ce
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 50
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 4ab9917febca54791c5f071a9d1f404867857fcc
runc version: 54296cf40ad8143b62dbcaa1d90e520a2136ddfe
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.4.0-98-generic
Operating System: Ubuntu 16.04.3 LTS
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 62.92 GiB
Name: 10.243.125.38
ID: BNCB:JUNP:647A:SARB:ZVKQ:FGVH:7SZ7:V3P4:KL4L:SG4M:PQJK:3BQC
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Http Proxy: https://gecd-proxy.eu.net.intra:8080
No Proxy: localhost,127.0.0.1,localaddress,.localdomain.com,.xmp.net.intra,.echonet,vs-f5-uk-mgmt-aramcheck-rancher.xmp.net.intra
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
4.4.0-98-generic

NAME="Ubuntu"
VERSION="16.04.3 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.3 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
Openstack

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
HA Rancher, External DB

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle

**Steps to Reproduce:**
https://github.com/rancher/rancher/issues/9680

Steps to Reproduce:

have a large number of hosts and services per environment.
reboot all hosts
delayed processes should grow indefinitely.
the processblocking pool should be fully consumed

**Results:**

![rancherprocesses](https://user-images.githubusercontent.com/628151/32774064-681ec3c8-c92b-11e7-9b22-063ee2f522a0.JPG)

**Comment by superseb** [comment] 2017-11-14 10:06
This was fixed in v1.6.8, why is this not a duplicate of https://github.com/rancher/rancher/issues/9680?

**Comment by lextra** [comment] 2017-11-14 10:20
We were requested to open a ticket by Raul Sanchez.

**Comment by lextradev** [comment] 2017-11-14 10:23
We need to know hiw to regain control of our environment which is completely down because of this issue.   Will upgrading allow us to regain control?

**Comment by superseb** [comment] 2017-12-08 21:59
For future reference, if this is being hit in version lower than v1.6.8:

Put higher values for

```
v1/settings/pool.processblockingexecutorservice.core.size  # Set at 50
v1/settings/pool.processblockingexecutorservice.max.size  # Set at 200
```

It could take some time to recover.

**Closed by superseb** 2017-12-08 21:59 UTC
