### ISSUE TITLE
kubctl shell - Not able to use up/down arrow to navigate thru contents of a file when using vi/vim editor. 

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#5759] opened 2016-08-17 23:34 UTC
Rancher server version - v1.2.0-pre2-rc4

Steps to reproduce the problme:
Create a kubernetes env.
Launch Kubectl shell.
Create a file.
Open this file using vi editor.
Note that we are not able to use up/down arrow to navigate thru contents of a file

**Comment by DxCx** [comment] 2016-08-18 06:34
Hi @sangeethah 
i'll try to help as an experienced vim user,
i don't think this issue is related to kubernatis nor rancher itself, but to vim's bindings..
can you please post the output of :nmap ?

**Comment by ibuildthecloud** [comment] 2016-08-18 18:46
@sangeethah This might be due to the `vi` in the `kubectl` container not being a full `vi`.  I can test.  The fix would be just to install `vim-full`.

**Comment by gcallsen** [comment] 2017-02-04 02:56
I can create a new issue if helpful but this seems related enough that I'm adding here for now:

Rancher version - 1.3.3
Environment based on Cattle orchestration
Steps to reproduce: execute a shell in any running container and attempt to `vim FILENAME`
Expected results: ability to use up/down/left/right arrows to navigate
Actual results: only able to use "h-j-k-l" keys to navigate directionally.

**Comment by Kamaradeivanov** [comment] 2017-02-21 11:28
Hi, I have exactly the same problem mentioned by @gcallsen. The problem appear for all our users after the migration to Rancher 1.2. Everything work fine until 1.1.3.

Rancher impacted version - 1.2.3, 1.3.3, 1.4.1
Environment based on Cattle orchestration

**Comment by superseb** [comment] 2017-06-12 16:41
Is this still happening, `vim` is already in there and I don't think it has changed.

**Comment by superseb** [comment] 2017-07-18 11:17
Ok, try this: https://github.com/rancher/kubectld/pull/32

**Comment by superseb** [comment] 2017-07-23 20:24
Should be fixed, https://github.com/rancher/kubectld/pull/32 is merged.

**Closed by superseb** 2017-07-23 20:24 UTC
Labels: area/kubernetes, area/packaging, kind/enhancement

**Comment by jsbrain** [comment] 2020-02-28 13:39
Hi all. Somehow this is an issue again. Just created a new cluster on docker 19.03 and current stable rancher version. The cluster I replaced was on the previous version without that issue.
