### ISSUE TITLE
[BUG] Lost connectivity between Rancher manager and one-node k3s cluster (after reboot)

### ISSUE THREAD

**Issue by juadk** [rancher/rancher#40679] opened 2023-02-24 15:48 UTC
**Rancher Server Setup**
- Rancher version: 2.7.2-rc4 deployed on k3s (v1.24.10)
- Installation option (Docker install/Helm Chart): Helm Chart, k3s (v1.24.10), all hosted in Digital Ocean

**Information about the Cluster**
- Kubernetes version: v1.24.10
- Cluster Type: Downstream k3s custom cluster inside ubuntu VM (22.10)

**User Information**
- Admin user

**Describe the bug**
First thing first, bug has been discovered in our [Elemental CI](https://github.com/rancher/elemental/actions/workflows/ui-k3s-os-upgrade-rancher_latest.yaml) which runs in GCP. I was able to reproduce it without any piece of Elemental product.

Basically, after rebooting a one-node k3s cluster, it never comes back as active status in Cluster manager view. Inside the downstream cluster, k3s is crashing in loop.

**To Reproduce**
1- Install rancher `2.7.2-rc4` with Helm
2- Create a new cluster
![image](https://user-images.githubusercontent.com/6025636/221215880-c016b54a-32b2-4329-981a-66e8eec21e9f.png)
![image](https://user-images.githubusercontent.com/6025636/221216028-550e2603-1751-416a-a46d-a64191b2d821.png)

No special option, I only give a name and select the k3s version to use, then Create
![image](https://user-images.githubusercontent.com/6025636/221216409-15c3997c-675b-4739-9789-63aab7241cb2.png)
![image](https://user-images.githubusercontent.com/6025636/221216615-39a8490c-d3f2-4a96-a59f-8b9e7023f7aa.png)

3- Create a VM (Ubuntu 22.10 in Digital Ocean)
Install Docker and run:
```
root@jadamek-k3s--s-4vcpu-8gb-fra1-01:~# curl --insecure -fL https://rancher.adamek.ovh/system-agent-install.sh | sudo  sh -s - --server https://rancher.adamek.ovh --label 'cattle.io/os=linux' --token hhztrns78xdns2cjx47mp6dwxfvjkl2ngghsf4mmk9kssbn57r5x7v --ca-checksum 50828717046f1eb97e9680e078bcbd2638078d5b2ad9ff33215a1648dac487f0 --etcd --controlplane --worker
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 29800    0 29800    0     0   764k      0 --:--:-- --:--:-- --:--:--  786k
[INFO]  Label: cattle.io/os=linux
[INFO]  Role requested: etcd
[INFO]  Role requested: controlplane
[INFO]  Role requested: worker
[INFO]  Using default agent configuration directory /etc/rancher/agent
[INFO]  Using default agent var directory /var/lib/rancher/agent
[INFO]  Determined CA is necessary to connect to Rancher
[INFO]  Successfully downloaded CA certificate
[INFO]  Value from https://rancher.adamek.ovh/cacerts is an x509 certificate
[INFO]  Successfully tested Rancher connection
[INFO]  Downloading rancher-system-agent binary from https://rancher.adamek.ovh/assets/rancher-system-agent-amd64
[INFO]  Successfully downloaded the rancher-system-agent binary.
[INFO]  Downloading rancher-system-agent-uninstall.sh script from https://rancher.adamek.ovh/assets/system-agent-uninstall.sh
[INFO]  Successfully downloaded the rancher-system-agent-uninstall.sh script.
[INFO]  Generating Cattle ID
[INFO]  Successfully downloaded Rancher connection information
[INFO]  systemd: Creating service file
[INFO]  Creating environment file /etc/systemd/system/rancher-system-agent.env
[INFO]  Enabling rancher-system-agent.service
Created symlink /etc/systemd/system/multi-user.target.wants/rancher-system-agent.service → /etc/systemd/system/rancher-system-agent.service.
[INFO]  Starting/restarting rancher-system-agent.service
```
4- Once the cluster ready:
![image](https://user-images.githubusercontent.com/6025636/221219541-13d6d007-3d56-4eac-8a66-271ac8c5643b.png)

Status before reboot:
```
root@jadamek-k3s--s-4vcpu-8gb-fra1-01:/var/log# kubectl get pods -A
NAMESPACE             NAME                                                              READY   STATUS      RESTARTS   AGE
cattle-fleet-system   fleet-agent-8489b5645f-96pwf                                      1/1     Running     0          6m
cattle-system         apply-system-agent-upgrader-on-jadamek-k3s--s-4vcpu-8gb-f-bc5g5   0/1     Completed   0          5m8s
cattle-system         cattle-cluster-agent-547b6f9b49-kdzhz                             1/1     Running     0          6m41s
cattle-system         helm-operation-zfx2w                                              0/2     Completed   0          5m39s
cattle-system         rancher-webhook-6f978fb5bb-mhjbs                                  1/1     Running     0          5m28s
cattle-system         system-upgrade-controller-79fc9c84b7-hqbsb                        1/1     Running     0          6m
kube-system           coredns-7b5bbc6644-2k7vn                                          1/1     Running     0          7m37s
kube-system           helm-install-traefik-9sq7q                                        0/1     Completed   2          7m38s
kube-system           helm-install-traefik-crd-ptmxf                                    0/1     Completed   0          7m38s
kube-system           local-path-provisioner-687d6d7765-njr5n                           1/1     Running     0          7m37s
kube-system           metrics-server-667586758d-r4fpg                                   1/1     Running     0          7m37s
kube-system           svclb-traefik-3356608a-f88d5                                      2/2     Running     0          7m6s
kube-system           traefik-64b96ccbcd-99w2t                                          1/1     Running     0          7m6s
```

Reboot it with `reboot` command 

**Result**
![image](https://user-images.githubusercontent.com/6025636/221220360-6614abc9-5cbf-4a02-b86b-85e639ca50f4.png)
![image](https://user-images.githubusercontent.com/6025636/221220451-c87f3d0d-c225-4187-bce0-2bd086f943d4.png)

Downstream cluster:
```
root@jadamek-k3s--s-4vcpu-8gb-fra1-01:~# kubectl get pods -A
NAMESPACE             NAME                                                              READY   STATUS      RESTARTS        AGE
cattle-fleet-system   fleet-agent-8489b5645f-96pwf                                      1/1     Running     1 (2m12s ago)   9m29s
cattle-system         apply-system-agent-upgrader-on-jadamek-k3s--s-4vcpu-8gb-f-bc5g5   0/1     Completed   0               8m37s
cattle-system         cattle-cluster-agent-547b6f9b49-kdzhz                             1/1     Running     3 (50s ago)     10m
cattle-system         helm-operation-zfx2w                                              0/2     Completed   0               9m8s
cattle-system         rancher-webhook-6f978fb5bb-mhjbs                                  1/1     Running     1 (2m12s ago)   8m57s
cattle-system         system-upgrade-controller-79fc9c84b7-hqbsb                        1/1     Running     1 (2m12s ago)   9m29s
kube-system           coredns-7b5bbc6644-2k7vn                                          1/1     Running     1 (2m12s ago)   11m
kube-system           helm-install-traefik-9sq7q                                        0/1     Completed   2               11m
kube-system           helm-install-traefik-crd-ptmxf                                    0/1     Completed   0               11m
kube-system           local-path-provisioner-687d6d7765-njr5n                           1/1     Running     1 (2m12s ago)   11m
kube-system           metrics-server-667586758d-r4fpg                                   1/1     Running     1 (2m12s ago)   11m
kube-system           svclb-traefik-3356608a-f88d5                                      2/2     Running     2 (2m12s ago)   10m
kube-system           traefik-64b96ccbcd-99w2t                                          1/1     Running     1 (2m12s ago)   10m
root@jadamek-k3s--s-4vcpu-8gb-fra1-01:~# kubectl get pods -A
The connection to the server 127.0.0.1:6443 was refused - did you specify the right host or port?
root@jadamek-k3s--s-4vcpu-8gb-fra1-01:~# kubectl get pods -A
Error from server (ServiceUnavailable): the server is currently unable to handle the request (get pods)

cluster agent log:
```
```
root@jadamek-k3s--s-4vcpu-8gb-fra1-01:~# kubectl logs cattle-cluster-agent-547b6f9b49-kdzhz -n cattle-system
dig: couldn't get address for 'resolver1.opendns.com': failure
INFO: Environment: CATTLE_ADDRESS=10.42.0.22 CATTLE_CA_CHECKSUM=50828717046f1eb97e9680e078bcbd2638078d5b2ad9ff33215a1648dac487f0 CATTLE_CLUSTER=true CATTLE_CLUSTER_AGENT_PORT=tcp://10.43.29.252:80 CATTLE_CLUSTER_AGENT_PORT_443_TCP=tcp://10.43.29.252:443 CATTLE_CLUSTER_AGENT_PORT_443_TCP_ADDR=10.43.29.252 CATTLE_CLUSTER_AGENT_PORT_443_TCP_PORT=443 CATTLE_CLUSTER_AGENT_PORT_443_TCP_PROTO=tcp CATTLE_CLUSTER_AGENT_PORT_80_TCP=tcp://10.43.29.252:80 CATTLE_CLUSTER_AGENT_PORT_80_TCP_ADDR=10.43.29.252 CATTLE_CLUSTER_AGENT_PORT_80_TCP_PORT=80 CATTLE_CLUSTER_AGENT_PORT_80_TCP_PROTO=tcp CATTLE_CLUSTER_AGENT_SERVICE_HOST=10.43.29.252 CATTLE_CLUSTER_AGENT_SERVICE_PORT=80 CATTLE_CLUSTER_AGENT_SERVICE_PORT_HTTP=80 CATTLE_CLUSTER_AGENT_SERVICE_PORT_HTTPS_INTERNAL=443 CATTLE_CLUSTER_REGISTRY= CATTLE_FEATURES=embedded-cluster-api=false,fleet=false,monitoringv1=false,multi-cluster-management=false,multi-cluster-management-agent=true,provisioningv2=false,rke2=false CATTLE_INGRESS_IP_DOMAIN=sslip.io CATTLE_INSTALL_UUID=20863719-3ce5-409a-a9e2-59843a38c3e6 CATTLE_INTERNAL_ADDRESS= CATTLE_IS_RKE=false CATTLE_K8S_MANAGED=true CATTLE_NODE_NAME=cattle-cluster-agent-547b6f9b49-kdzhz CATTLE_SERVER=https://rancher.adamek.ovh CATTLE_SERVER_VERSION=v2.7.2-rc4
INFO: Using resolv.conf: search cattle-system.svc.cluster.local svc.cluster.local cluster.local nameserver 10.43.0.10 options ndots:5
```
![image](https://user-images.githubusercontent.com/6025636/221221507-66694902-2d45-4ffb-b40b-4bbea9670225.png)

Status after having wait a bit:
```
root@jadamek-k3s--s-4vcpu-8gb-fra1-01:~# kubectl get pods -A
NAMESPACE             NAME                                                              READY   STATUS      RESTARTS        AGE
cattle-fleet-system   fleet-agent-8489b5645f-96pwf                                      1/1     Running     1 (8m57s ago)   16m
cattle-system         apply-system-agent-upgrader-on-jadamek-k3s--s-4vcpu-8gb-f-bc5g5   0/1     Completed   0               15m
cattle-system         cattle-cluster-agent-547b6f9b49-kdzhz                             1/1     Running     11 (65s ago)    16m
cattle-system         helm-operation-zfx2w                                              0/2     Completed   0               15m
cattle-system         rancher-webhook-6f978fb5bb-mhjbs                                  1/1     Running     1 (8m57s ago)   15m
cattle-system         system-upgrade-controller-79fc9c84b7-hqbsb                        1/1     Running     1 (8m57s ago)   16m
kube-system           coredns-7b5bbc6644-2k7vn                                          1/1     Running     1 (8m57s ago)   17m
kube-system           helm-install-traefik-9sq7q                                        0/1     Completed   2               17m
kube-system           helm-install-traefik-crd-ptmxf                                    0/1     Completed   0               17m
kube-system           local-path-provisioner-687d6d7765-njr5n                           1/1     Running     1 (8m57s ago)   17m
kube-system           metrics-server-667586758d-r4fpg                                   0/1     Running     1 (8m57s ago)   17m
kube-system           svclb-traefik-3356608a-f88d5                                      2/2     Running     2 (8m57s ago)   17m
kube-system           traefik-64b96ccbcd-99w2t                                          1/1     Running     1 (8m57s ago)   17m
```
**Expected Result**
The downstream cluster should back to Active state after rebooting it.

**Additional context**
- This test is working perfectly with Rancher < 2.7.2
- It only happens **with one-node cluster**, I tried with 3 nodes and it worked as expected.
- I can easily prepare a test env, reproduce it either give access to someone who wants to check.

**Additional logs**
Upstream cluster logs: 
[jadamek-elem-s-2vcpu-4gb-fra1-01-2023-02-24_17_49_14.tar.gz](https://github.com/rancher/rancher/files/10827350/jadamek-elem-s-2vcpu-4gb-fra1-01-2023-02-24_17_49_14.tar.gz)
Downstream cluster logs:
[jadamek-k3s--s-4vcpu-8gb-fra1-01-2023-02-24_17_48_48.tar.gz](https://github.com/rancher/rancher/files/10827352/jadamek-k3s--s-4vcpu-8gb-fra1-01-2023-02-24_17_48_48.tar.gz)

**Comment by juadk** [comment] 2023-03-16 08:08
It still happens using `2.7.2-rc6`.

**Comment by MbolotSuse** [comment] 2023-03-16 18:18
This appears to be caused by the same core issues as #40843 - we should re-test after a fix for that has been merged.

**Closed** 2023-03-17 16:34 UTC
Labels: kind/bug
