### ISSUE TITLE
ServerError (500) - encountered when trying to launch namespace tab for a cluster were all hosts were deleted and new hosts added.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#11150] opened 2018-01-25 22:49 UTC
Rancher server - v2.0.0-alpha12

Steps that were done before this issue was encountered:

1. Had a 1 node RKE cluster with node from DO.
2. Deleted host from DO.
3. Host continues to be marked in "Active" state at this point.
4. Delete host from rancher UI.
5. Add 2 new hosts - 1 host with all roles and another with "worker" role.
6. Cluster state gets updated from "Active"->"Updating"->"Active".

Once cluster is active, create project in this cluster. 
Navigate to Namespace tab in UI.

User is directed to this page: 
<img width="1181" alt="screen shot 2018-01-25 at 1 50 11 pm" src="https://user-images.githubusercontent.com/4266958/35414416-41b48968-01d7-11e8-98dd-94b5cb68a9b1.png">

Following error seen in server logs:
```
time="2018-01-25T21:48:45Z" level=error msg="Unknown error: Get https://104.236.66.7:6443/api/v1/namespaces: dial tcp 104.236.66.7:6443: i/o timeout"
time="2018-01-25T21:48:46Z" level=error msg="Error during subscribe websocket: close sent"
time="2018-01-25T21:48:46Z" level=error msg="Unknown error: websocket: close sent"
2018-01-25 21:48:46.539123 I | http: response.WriteHeader on hijacked connection
2018-01-25 21:48:46.539195 I | http: response.Write on hijacked connection
2018-01-25 21:48:46.539316 I | http: response.Write on hijacked connection
2018-01-25 21:48:46.539377 I | http: response.Write on hijacked connection

**Comment by alena1108** [comment] 2018-02-28 17:51
Resolving as a duplicate of https://github.com/rancher/rancher/issues/11356

**Closed by alena1108** 2018-02-28 17:51 UTC
Labels: area/cluster, area/stack, kind/bug, version/2.0
