### ISSUE TITLE
Environments with OpenLDAP groups in access control don't show in the menu dropbown

### ISSUE THREAD

**Issue by adepretis** [rancher/rancher#5629] opened 2016-08-04 09:37 UTC
**Rancher Version:**
1.1.2

**Docker Version:**
1.10.x, 1.11.x

**OS and where are the hosts located? (cloud, bare metal, etc):**
bare metal, kvm

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
single node rancher, internal DB

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle

**Steps to Reproduce:**

* activate LDAP authentication (against OpenLDAP)
* create an environment
* assign only a group to the environments access-control (owner or member)

**Results:** 

* the environments dropdown in the top-menu only shows environments with explicit users added to the environment, although
* via "Manage Environments" all respective environments are available and can be switched to
* the only exception being the environment that is set as default - this one is shown in the menu
* all environments you see in the following screenshots have been assigned a group with the admin-role, and my user is of course part of the group
* the groups are simple OpenLDAP groups using the groupOfNames objectclass, with a cn and multiple member attributes referencing the DN of each user

![screen shot 2016-08-04 at 11 34 06](https://cloud.githubusercontent.com/assets/587018/17397229/66a26112-5a37-11e6-9033-490500f65c4b.png)

**Expected:**

The environments dropdown should show all environments where an authenticated users is either explicitly added OR member of a group added to the environments access control.

**Comment by tfiduccia** [comment] 2016-08-04 21:26
version - master 8/4
Verified environment mapping is not working.  Related to bug #3875.

**Comment by prachidamle** [comment] 2016-10-24 00:15
The root cause is same as bug https://github.com/rancher/rancher/issues/3875
Resolving this as "status/has-dependency"

@deniseschannon how do we mark duplicates?

**Comment by tfiduccia** [comment] 2016-10-28 23:18
Version - v1.2.0-pre4-rc6
Verified fixed

**Closed by tfiduccia** 2016-10-28 23:18 UTC
Labels: area/access-control, kind/bug, status/has-dependency, status/resolved, status/to-test
