### ISSUE TITLE
Not able to edit cluster for AWS CN

### ISSUE THREAD

**Issue by BellonXiao** [rancher/rancher#29666] opened 2020-10-21 07:58 UTC
**What kind of request is this (question/bug/enhancement/feature request):**
bug

**Steps to reproduce (least amount of steps as possible):**
1. register an EKS cluster in AWS CN
2. after registered, open edit cluster UI, as attached.
3. click next

**Result:**
You'll find the error message, says "Credential should be scoped to a valid region, not 'us-east-1'."  But our cluster and credential is cn-north-1. not able to go to next step.

**Other details that may be helpful:**
Adding  EKS cluster has the same issue.

![Screen Shot 2020-10-19 at 2 31 54 PM](https://user-images.githubusercontent.com/45930963/96690376-30490700-13b6-11eb-89f5-683d89997ed9.png)
![Screen Shot 2020-10-19 at 2 31 33 PM](https://user-images.githubusercontent.com/45930963/96690409-3b039c00-13b6-11eb-8828-797a17a5bff2.png)

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): 2.5.1
- Installation option (single install/HA): HA

gz#13326

**Comment by lenew** [comment] 2020-12-09 10:05
Same problem.

**Comment by hoempf** [comment] 2020-12-09 13:09
Same here.
Although I see the error when trying to create an EKS cluster on cn-northeast-1 instead of importing an existing cluster.

Env: 
* Rancher Version 2.5.3
* Single Docker Image installation.

**Comment by lenew** [comment] 2020-12-10 08:30
Seems that rancher not add eks.cn-north-1.amazonaws.com.cn into it's proxy whitelist.

**Comment by deniseschannon** [comment] 2021-03-10 00:44
Typically, if you have access to the China regions, you wouldn't have access to US regions.

**Comment by aaronRancher** [comment] 2021-03-11 22:52
Reproduced this behavior with Rancher server `rancher\rancher:v2.5.1`

Steps:
Create EKS cloud credential.
Navigate to EKS cluster create.
Select region `cn-north-1`

Result:
![Screen Shot 2021-03-11 at 3 51 44 PM](https://user-images.githubusercontent.com/57409052/110865987-b55b8c80-8281-11eb-89fe-e2f38b1a1569.png)

**Comment by aaronRancher** [comment] 2021-03-11 22:57
Also observed this behavior on `rancher\rancher:v2.5.6` with a slightly different message.

![Screen Shot 2021-03-11 at 3 56 20 PM](https://user-images.githubusercontent.com/57409052/110866541-8560b900-8282-11eb-8ccb-43b6f82c1726.png)

**Comment by PennyScissors** [comment] 2021-03-11 23:44
After some investigation and discussion with @westlywright, this seems to be a UI issue. As he explained, in order to use the JS AWS SDK and get around CORS issues, all the requests go through a proxy in our server. But part of the AWS SDK is creating the request with the correct region (region is passed to the AWS request constructor), so there could be a bug in some of the edge cases we have for China regions currently.

**Comment by westlywright** [comment] 2021-03-12 21:47
@PennyScissors and I talked offline and I wanted to add the summary of that discussion. I did some additional investigation and my original assumption of the edge case issue was not correct. We only have one edge case for `cn-northwest-1` region which changes the endpoint for the IAM call because there is no `cn-northwest-1` IAM region. This doesn't affect what we're seeing here. The AWS action that is triggering the `SignatureDoesNotMatch` error is `ListRoles`. I checked the AWS SDK constructor and found all the endpoints and region for this call were set correctly to `cn-north-1` with no reference to `us-east-1` in the AWS object. I don't think this is a front end issue from what I am seeing. So I have kicked it back for further investigation.

**Comment by aaronRancher** [comment] 2021-04-02 22:46
Tested this issue on Rancher `v2.5-head` `version bdec2f2`

I was not able to get past the `SignatureDoesNotMatch` error. But I also do not have the necessary credentials to properly test this issue.
![Screen Shot 2021-04-02 at 3 45 14 PM](https://user-images.githubusercontent.com/57409052/113459486-7c1ec400-93ca-11eb-9cb8-b140dc9b0260.png)

**Comment by aaronRancher** [comment] 2021-04-02 23:11
Tested on Rancher `master-head` `version e2deded`

Did not hit the `SignatureDoesNotMatch` error. But I do not have the proper credentials to test this issue end to end.
![Screen Shot 2021-04-02 at 4 10 36 PM](https://user-images.githubusercontent.com/57409052/113460560-0ae11000-93ce-11eb-853b-13d0e63fd1dc.png)


Reopening the issue to wait for the fix to be merged in `v2.5-head`.

**Comment by aaronRancher** [comment] 2021-04-02 23:47
Tested this issue on Rancher `v2.5-head` `version 5011025`

Did not hit the `SignatureDoesNotMatch` error:
![Screen Shot 2021-04-02 at 4 45 16 PM](https://user-images.githubusercontent.com/57409052/113461764-d15ed380-93d2-11eb-826f-e82cc905415c.png)

**Comment by yasker** [comment] 2021-04-06 00:31
@niusmallnan 's team is going to help with verifying.

Thank you @niusmallnan !

**Comment by dingluyy** [comment] 2021-04-08 05:57
Tested this issue on Rancher `v2.5-head` version `7426ba8`.

1. Register an existing Amazon EKS cluster, `Region` select `cn-north-1` with right credential, get aws cn eks interface report 502.
![image](https://user-images.githubusercontent.com/54788198/113973284-a232e100-986e-11eb-8b10-fd9d1a619db3.png)
rancher log: 
![image](https://user-images.githubusercontent.com/54788198/113974029-d65ad180-986f-11eb-8efa-4178c01a7e1e.png)

2. After registered Amazon EKS cluster, open edit cluster UI, click next, aws cn  kms interface report 502.
![image](https://user-images.githubusercontent.com/54788198/113975221-c3490100-9871-11eb-9ab8-0c1ca379f861.png)
rancher log:
![image](https://user-images.githubusercontent.com/54788198/113975287-d8be2b00-9871-11eb-9af3-d12dd5161346.png)
Adding EKS cluster has the same issue.

**Comment by sowmyav27** [comment] 2021-04-08 23:20
Reopening the issue

**Comment by niusmallnan** [comment] 2021-04-09 06:17
The proxy request failed because the domain(`*.amazonaws.com.cn`) is not in the whitelist. This is the mechanism of rancher `meta-prxoy`.

There are two ways as the workaround:

1. Add `*.amazonaws.com.cn` to `/v3/settings/whitelist-domain`
2. Add `eks.%.amazonaws.com.cn` and `kms.%.amazonaws.com.cn` to  the field `whitelistDomains` of`/v3/nodeDrivers/amazonec2`

I think we should add these domains to the code so that the user has no need to manual input.

**Comment by dingluyy** [comment] 2021-04-13 06:05
Tested the following on Rancher v2.5-head version `f54152f`:

Register an existing Amazon EKS cluster
- Region select `us-west-2`, and Cloud Credentials is `cn-north-1`, request get 403 response: **'Failed to load Clusters from Amazon: The security token included in the request is invalid'**.
   *Result*: Failed to load Amazon EKS Clusters and not able to go to next step.

- Region select `cn-north-1`, and Cloud Credentials is `cn-north-1`, loading Amazon clusters correctly.
  *Result*: Successfully import an Amazon cluster in the rancher UI.

Adding Amazon EKS cluster with k8s provider
- Region select `us-west-2`, and Cloud Credentials is `cn-north-1`, click next and request get 403 response: **'InvalidClientTokenId: The security token included in the request is invalid'**.
  *Result*: Not able to go to next step.

- Region select `cn-north-1`, and Cloud Credentials is `cn-north-1`, click next, successfully go to the next step.
  *Result*: Fill out the Amazon EKS configuration, and the EKS cluster created successfully.

Edit Amazon EKS cluster
- After Amazon EKS registered, open edit cluster UI, cluster and credential is `cn-north-1`, click next, successfully go to the next step.
  *Result*: Modify eks configuration, and eks cluster upgrade successfully. 

Register/Adding  Amazon EKS cluster with New Cloud Credentials
- Region select `us-west-2`, click `Add New`, AK/SK fill in China aws AK/SK, request get 401 response: **'401 AuthFailure: There was a problem validating your keys. Enter valid credentials and try again'**.
  *Result*: Not able to go to next step.

- Region select `cn-north-1`, click `Add New`, AK/SK fill in China aws AK/SK.
  *Result*: Create a Cloud Credentials and go to next step.

Test Passed.

**Comment by PennyScissors** [comment] 2021-04-13 23:42
Thanks @niusmallnan, your comment was incredibly helpful!

**Comment by sowmyav27** [comment] 2021-04-16 20:10
Closing this issue as per comments - https://github.com/rancher/rancher/issues/29666#issuecomment-818464413

**Closed** 2021-04-16 20:11 UTC
Labels: QA/S, [zube]: To Test, area/eks, internal, kind/bug, release-note
