### ISSUE TITLE
[SURE-5694] Rancher responds to /v1/fleet.cattle.io.clusters with a 503 when there are no permissions

### ISSUE THREAD

**Issue by kkaempf** [rancher/rancher#40962] opened 2023-02-14 13:40 UTC
#### Issue description:

Customer has a job that performs some discovery in their Rancher environments on a 15min interval. One request it performs using curl is to retrieve and filter the list of clusters in fleet-default.

When an automation removed some permissions for the user, Rancher began to timeout to request, and ingress-nginx serves a 502/503 (see repro steps).

This behaviour appears to cause ingress-nginx to retry connection attempts many times to Rancher pods. This increases the memory usage of Rancher significantly. Here’s an example from the ingress-nginx logs:

```
10.207.120.27 - token-9ddck [14/Dec/2022:21:04:43 +0000] "GET /v1/fleet.cattle.io.clusters/fleet-default HTTP/2.0" 502 150 "-" "curl/7.68.0" 150 0.009 [cattle-system-rancher-80] [] 172.19.1.108:80, 172.19.2.31:80, 172.19.0.82:80, 172.19.1.108:80 0, 0, 0, 0 0.004, 0.000, 0.000, 0.004 502, 502, 502, 502 7eb524afced8e7ef4ed525b607b5c7e0
```

```
2022/12/14 21:12:23 [error] 441#441: *872338 upstream prematurely closed connection while reading response header from upstream, client: 10.207.120.54, server: drekar-rancher-ccena.customer.com, request: "GET /v1/fleet.cattle.io.clusters/fleet-default HTTP/2.0", upstream: "http://172.19.2.32:80/v1/fleet.cattle.io.clusters/fleet-default", host: "drekar-rancher-ccena.customer.com" 
```

The comma-separated list of 172.x IP’s in the access log are nginx attempting to contact Rancher pods multiple times to get a response, sometimes this list of IP's grows to 1,000's of duplicated IP’s (pod contacts), which presumably causes the Rancher memory increase. (Note: support to research the ingress-nginx retry behaviour)

#### Business impact:
Rancher API is unresponsive when a permission response (4xx) should be expected. This also causes an inadvertent spike in memory usage.

#### Repro steps:

Create the global role (attached)
> kubectl create -f global-role.yml

Create a testing user with the "GV Automation" custom global role (created above) and User-Base
Login as the user and create an API token
Curl the API using the token:
> curl -s -u <token> https://<rancher>/v1/fleet.cattle.io.clusters/fleet-default

Remove the "GV Automation" role
> kubectl delete -f global-role.yml

Re-run the curl:
> curl -s -u <token> https://<rancher>/v1/fleet.cattle.io.clusters/fleet-default 

The curl to the API will present a 502:

```
<html>
<head><title>502 Bad Gateway</title></head>
<body>
<center><h1>502 Bad Gateway</h1></center>
<hr><center>nginx</center>
</body>
</html>
```

**Comment by MbolotSuse** [comment] 2023-11-15 17:01
The root cause of this issue is the same as #40296. Basically, there was a panic in rancher/apiserver due to a nil pointer. When using Rancher in a HA Install (i.e. installed in a k8s cluster, and accessed by a user through ingress-nginx), this resulted in a 502 error code, since Rancher would close the connection from nginx, causing nginx to return the 502 error code. 

The linked issue was fixed in 2.7.5, and these urls now appear to return a `404`, which is expected.

One additional note, direct usage of steve (the v1 endpoints specified above) is not supported. We recommend using the Kubernetes API directly, rather than using steve.

**Closed by MbolotSuse** 2023-11-15 17:01 UTC
Labels: kind/bug, team/area1, JIRA, area/steve, area/frameworks
