### ISSUE TITLE
Service Link unuseable for cross-stack service

### ISSUE THREAD

**Issue by k8w** [rancher/rancher#8352] opened 2017-03-30 10:16 UTC
*Describe your issue here*
If link a service from another stack,
ping the link name.
It will show:  bad address

It seems only service link only can be used for service in the same stack.

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v1.5.1` Cattle: `v0.177.8` UI: `v1.5.7` |
|Access|`localauth` `admin`|
|Orchestration|`Cattle`|
|Route|`service.containers`|

**Comment by david-maumenee** [comment] 2017-03-30 12:37
Hi,

I think that's not an issue.
With cattle, to access a service from another stack, you must use <service_name>.<stack_name> (to avoid conflict name)

http://docs.rancher.com/rancher/v1.5/en/cattle/internal-dns-service/#pinging-services-in-a-different-stack

**Comment by tfiduccia** [comment] 2017-03-30 17:49
@twoeo - please try <service_name>.<stack_name> and see if that resolves you issue.  If it does will you please close this.  If not can you give us a copy of your docker & rancher config files

**Comment by twoeo** [comment] 2017-03-31 14:16
Of course I can use <service_name>.<stack_name>.

But the purpose I use service link is that :
1. see service dependency relationship clearly 
2. ignore the name change from external service

So if service link is only for same-stack services, wouldn't it seems useless ? 
Because I can use <service_name>.<stack_name> whatever?

**Comment by aemneina** [comment] 2017-05-25 22:53
@twoeo is this using an alpine based image?

**Comment by loganhz** [comment] 2018-10-05 05:40
Please let us know in a comment if you can still reproduce the issue, and we'll reopen it

**Closed by loganhz** 2018-10-05 05:40 UTC
Labels: area/dns, kind/question
