### ISSUE TITLE
[UI] LB Path column wrong named

### ISSUE THREAD

**Issue by EugenMayer** [rancher/rancher#5055] opened 2016-06-09 16:50 UTC
**Rancher Version:**
v1.1.0-dev3

**Docker Version:**
Docker version 1.10.3, build 20f81dd

**OS and where are the hosts located? (cloud, bare metal, etc):**
baremetal rancheros

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
internal db, no ha

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
cattle

**Steps to Reproduce:**
create a lb service
add a service
**Results:** 
https://goo.gl/RaZjDg

**Expected:**
Column should be named "Path

**Comment by deniseschannon** [comment] 2016-06-09 23:46
Duplicate of https://github.com/rancher/rancher/issues/4943

This will be fixed in the next release.

**Closed by deniseschannon** 2016-06-09 23:46 UTC
