### ISSUE TITLE
Add Host action in UI needs a timeout

### ISSUE THREAD

**Issue by aruneli** [rancher/rancher#1516] opened 2015-07-14 05:45 UTC
From the Rancher server (ros - v0.3.3), worked on Amazon EC2 workflow for registering two RancherOS machine with Rancher Platform. For some reason, host registration was not successful (even after enablingTCP ports 9345 and 9346 and UDP ports 500 and 4500) but UI keeps showing spinning wheel with status ("Almost there Waiting for agent connection). Re-started Rancher server and I even deleted EC2 instances and UI is still stuck in same state. Discussed this issue with Will and he agreed UI needs to have a timeout. 

Screenshot below:
![image](https://cloud.githubusercontent.com/assets/7720752/8667173/b8b8d6ce-29b0-11e5-93c3-7f6bbec18473.png)

**Comment by ranger1981** [comment] 2015-07-14 06:42
Tried to register a DigitalOcean host and hit same issue. Not sure if 0.3.3 version is ready for use or I am missing something.

**Comment by vincent99** [comment] 2015-07-14 06:55
@will-chan That message just means that the `machine` resource went to `state=active` but the agent hasn't checked in so there is no corresponding `host` resource yet, which would normally happen a less than a minute later.  So there's not really anything to time-out, per se, there's nothing actually "waiting"... but if there were it would be something we'd likely add to go-machine-service, not the UI.

@ranger1981 Is the Host Registration address (in the user dropdown menu/upper-right corner) correct and accessible from the hosts?  If you go to Add Host and click on the Custom choice, the `docker run` command is approximately the same as gets run on the machines created in the clouds by the other drivers.  The URL at the end needs to be accessible from your AWS/DO VMs.

**Comment by deniseschannon** [comment] 2015-07-14 17:02
@ranger1981 What Rancher version are you running? 

I tested using the latest v0.25.0. Without changing the host registration, I had no issues adding a DO host (using the default values) and AWS host (using a RancherOS v0.3.3 AMI) using the UI to add the machines.

**Comment by deniseschannon** [comment] 2015-07-30 21:01
Looking over this one again, it looks similar to this: https://github.com/rancher/rancher/issues/203. Basically, the go-machine-service hasn't started yet.

**Comment by cjellick** [comment] 2015-12-04 16:35
@deniseschannon I think this is a dupe of #203. Can we close this?

**Comment by deniseschannon** [comment] 2015-12-04 17:45
Yes, let's close in favor of #203.

**Closed by deniseschannon** 2015-12-04 17:45 UTC
Labels: area/ui, kind/enhancement
