### ISSUE TITLE
Secret "bootstrap-secret" in namespace "cattle-system" exists and cannot be imported seen when upgrading/re-installing Rancher when bootstrap-secret is not created by Helm

### ISSUE THREAD

**Issue by MSpencer87** [rancher/rancher#37060] opened 2022-03-26 02:02 UTC
This issue closley relates to
https://github.com/rancher/rancher/issues/37003 
https://github.com/rancher/rancher/issues/36061

**Rancher version:** 2.6.4-rc12
**Installation option:** Helm -> RKE1 v1.3.3
**Proxy/Cert Details:** letsencrypt
**Kubernetes version:** 1.22
**Cluster Type:** local, as Admin

**Describe the bug**

When performing backup/restore migration on Rancher 2.6.4-rc12 using Helm install command fails when using letsencrypt
```
Error: rendered manifests contain a resource that already exists. Unable to continue with install: Secret "bootstrap-secret" in namespace "cattle-system" exists and cannot be imported into the current release: invalid ownership metadata; label validation error: missing key "app.kubernetes.io/managed-by": must be set to "Helm"; annotation validation error: missing key "meta.helm.sh/release-name": must be set to "rancher"; annotation validation error: missing key "meta.helm.sh/release-namespace": must be set to "cattle-system"
```

**To Reproduce**

1. Manually bring up  RKE 1.3.3 cluster and deploy HA Rancher 2.6.4-rc12 using LetsEncrypt
```
rke133 up --config cluster.yml

kubectl create namespace cattle-system

helm install rancher rancher-latest/rancher \
  --version=2.6.4-rc12 \
  --namespace cattle-system \
  --set hostname="" \
  --set ingress.tls.source=secret \
  --set letsEncrypt.email=""
  
  kubectl -n cattle-system create secret tls tls-rancher-ingress --cert=tls.crt --key=tls.key
  ```
2. Create resources
3. Install Rancher Backups
4. Take s3 Backup
5. Teardown cluster and delete nodes
6. Create a new RKE 1.3.3 cluster (ensure nodes are added to the same target group)
7. Create secret and migrationResource files, make sure too add the filename from s3 bucket
8. Intall rancher-backup charts into new cluster
```
helm install rancher-backup-crd rancher-charts/rancher-backup-crd -n cattle-resources-system --create-namespace --version 2.1.0

helm install rancher-backup rancher-charts/rancher-backup -n cattle-resources-system --version 2.1.0
```
9. Apply secret and migration files 
```
kubectl apply -f secret.yaml
kubectl apply -f kubectl apply -f migrationResource.yaml
```
10. Install rancher
```
helm install rancher rancher-latest/rancher \
  --version=2.6.4-rc12 \
  --namespace cattle-system \
  --set hostname="" \
  --set ingress.tls.source=secret \
  --set letsEncrypt.email=""
 ```
  
Workaround:
1. Delete the secret first, then run the helm install again
`kubectl delete secret -n cattle-system bootstrap-secret`

2. Deploy rancher with cert-manager installation, use cert-manager installation for backup/restore migration

**Comment by superseb** [comment] 2022-04-19 06:50
### Root cause

See https://github.com/rancher/rancher/issues/37060#issuecomment-1081845919

The way bootstrap-secret was implemented has basically created a conflict between Helm install and Docker install (because they share the same secret) and between 2.6.3 and 2.6.4 also between Helm install and Helm install (upgrade). The history basically comes down to:

- In 2.6.3, we changed the logic because of situations that the bootstrap-secret was not set (https://github.com/rancher/rancher/pull/35581)
- Also in 2.6.3, the previous change caused the bootstrap-secret be deleted on upgrade because Helm did not render the template if the bootstrapPassword was explicitly set (https://github.com/rancher/rancher/pull/35743)
- Because of this latest change, it now causes Helm to include the secret even if it wasn't created by Helm (When you don't set bootstrapPassword, rancher will create it on its own, this is where the use of the secret bootstrap-secret is conflicting)

### What was fixed, or what changes have occurred

Define the secret as a chart hook, this solves multiple issues:
- The situation where bootstrapPassword was not set and the secret was created by Rancher, with the secret being a hook, Helm won't complain that the secret was not created by Helm
- This also solves the issue where a restore was done with the bootstrap-secret restored (even though this is now fixed, there is a backup-restore-operator fix (https://github.com/rancher/backup-restore-operator/pull/209) to no longer backup the bootstrap-secret
- Added the secret removal to the post uninstall hook script so it will get deleted when running `helm uninstall`
 
Because of the hook, the secret will get deleted and recreated during Helm install/upgrade, but the contents should be the same.

### Areas or cases that should be tested

- Helm install
- Helm upgrade (2.6.0-2.6.4)
- Migrating Rancher between cluster using backup-restore-operator 2.1.1 and 2.1.2-rc1
- Helm uninstall (bootstrap-secret in cattle-system namespace should be deleted)

### What areas could experience regressions?
 
Anything related to a Helm install/upgrade/uninstall

### Are the repro steps accurate/minimal?

Yes

**Comment by anupama2501** [comment] 2022-05-03 03:21
Verified on v2.6.5-rc6

Helm fresh install

- Created an rke1 cluster with the rke version 1.3.10 
`kubectl create namespace cattle-system`
- Install cert manager by following https://rancher.com/docs/rancher/v2.6/en/installation/install-rancher-on-k8s/#5-install-cert-manager
```
helm install rancher rancher-latest/rancher \
  --version=2.6.5-rc6 \
  --namespace cattle-system \
  --set hostname="" \
  --set ingress.tls.source=secret \
  --set letsEncrypt.email=""
```
- Add TLS secrets   
`kubectl -n cattle-system create secret tls tls-rancher-ingress --cert=tls.crt --key=tls.key`
- Create a few workloads and ingresses
- Install Rancher Backups v2.1.2-rc3
- Take s3 Backup 
- Teardown cluster and delete nodes
- Create a new RKE  cluster as the same steps mentioned above
- Create secret and migrationResource files, make sure too add the filename from s3 bucket
- Install rancher-backup charts into new cluster
```
helm install rancher-backup-crd rancher-charts/rancher-backup-crd -n cattle-resources-system --create-namespace --version 2.1.2-rc3
helm install rancher-backup rancher-charts/rancher-backup -n cattle-resources-system --version 2.1.2-rc3
```

Helm upgrade (2.6.0-2.6.4) - PASS
Migrating Rancher between cluster using backup-restore-operator 2.1.1 and 2.1.2-rc1 - PASS

**Comment by anupama2501** [comment] 2022-05-03 22:38
Verified uninstall works:
```
helm uninstall rancher -n cattle-system
```

**Closed** 2022-05-03 22:39 UTC
Labels: kind/bug-qa, [zube]: QA Working, release-note, team/area3

**Comment by mchudinov** [comment] 2022-06-28 21:55
Same problem with stable Rancher v2.6.5.
It is easy to reproduce the issue:
1. Install Rancher with helm and no password specified. "bootstrap-secret" created
2. Uninstall Rancher with helm.  "bootstrap-secret" is gone
3. Install Rancher again -> no  "bootstrap-secret" is created :(

**Comment by funkel1989** [comment] 2022-08-29 02:56
referencing this comment here as I needed help finding the fix to this that didn't involve completely removing and re-installing rancher.

https://github.com/rancher/rancher/issues/34686#issuecomment-1150065227   

this will show how to reset the bootstrap password after deployment

**Comment by pramodsetlur** [comment] 2022-11-06 23:42
I have a similarly strange issue. 
1. Installed Rancher with helm chart value bootstrapPassword: value1
2. Updated the bootstrapPassword: value2
3. Restarted the server pods.
4. Can install into Rancher using value1 password but value2 does not work.
