### ISSUE TITLE
Certificate details not shown when created using cert-manager

### ISSUE THREAD

**Issue by mrmurb** [rancher/rancher#14467] opened 2018-07-09 20:14 UTC
**Rancher versions:**
rancher/server or rancher/rancher: 2.0.5

**Steps to Reproduce:**
Create _cert-manager_ from Helm, using Catalog.
Setup `Issuer` or `ClusterIssuer`.
Create `Certificate`, expect to be generated sucessfully.

**Results:**
`Certificate` is shown in Rancher UI. But missing fields:
- Algorithm
- Issuer
- Serial Number
- Fingerprint

_Valid Beginning_ and _Expires_ are filled, but with invalid data. [Screenshot](https://i.imgur.com/IlMN4IE.png)

**Comment by TehTotalPwnage** [comment] 2018-07-23 20:56
Duplicate of #14423.

**Closed by TehTotalPwnage** 2018-07-23 20:56 UTC
