### ISSUE TITLE
New Pods/Workload status is red when first deploying

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#11282] opened 2018-02-02 22:14 UTC
**Rancher versions:** 2.0 master 2/2

**Steps to Reproduce:**
1.  Create a Pod or a Workload

**Results:**  The Activating status is red.  Makes it look like there is an error activating the pod/workload.  Starting status should be blue

![image](https://user-images.githubusercontent.com/11514927/35757317-af7973f0-082b-11e8-834b-99ef4ec70ae3.png)

![image](https://user-images.githubusercontent.com/11514927/35757326-bad2ff82-082b-11e8-98af-05cc215bbca5.png)

**Comment by loganhz** [comment] 2018-02-03 01:36
![image](https://user-images.githubusercontent.com/21168270/35761615-8f140e1e-08c5-11e8-9f66-12aeff79e3be.png)

**Comment by loganhz** [comment] 2018-02-03 01:37
UI shows red as the transitioning is `error`.
I think we need to change it in backend.

**Comment by alena1108** [comment] 2018-02-28 17:48
A duplicate of https://github.com/rancher/rancher/issues/11548

**Closed by alena1108** 2018-02-28 17:48 UTC
Labels: area/service, kind/bug, version/2.0
