### ISSUE TITLE
Can't delete nodes from cluster in updating/error state

### ISSUE THREAD

**Issue by izaac** [rancher/rancher#29801] opened 2020-10-27 23:40 UTC
**What kind of request is this:**
bug

**Steps to reproduce:**

This used to work in `v2.4.8`. I tried this etcd recover scenario today too in `v2.4.8` and it worked but not in `v2.4.9-rc6`

### Custom RKE cluster / S3 backup

```
    - This test create 1 cluster with s3 backups enabled
        - 1 ControlPlane/worker node
        - 2 worker nodes
        - 3 etcd nodes
    - Creates an Ingress pointing to a workload
    - Snapshots the cluster and checks the backup is in S3
    - Stops the etcd nodes in ec2
    - Waits for the cluster to go into unavailable state
    - Removes all 3 etcd nodes.                   <---- THIS FAILS on v2.4.9 now
    - Creates 3 new etcd nodes and waits until the cluster
      asks to restore from backup.
    - Restores from S3 backup
    - Cluster is validated after it gets in Active state.
    - Checks the Ingress created before the backup is functional after restore.
    - Removes cluster if RANCHER_CLEANUP_CLUSTER=True
```

However in `v2.4.9-rc6` after terminating the etcd nodes from EC2 and the cluster goes into updating/error state, deleting the node objects from the cluster in Rancher is not longer possible.

**Result:**

Can't remove the etcd nodes before adding new ones to recover from S3 backup

This is the state the cluster after removing the etcd nodes from EC2
```
state": "updating",
"transitioning": "error",
"transitioningMessage": "cluster health check failed: Failed to communicate with API server: Get https://<REDACTED>:6443/api/v1/namespaces/kube-system?timeout=45s: net/http: request canceled (Client.Timeout exceeded while awaiting headers); Cluster must have at least one etcd plane host: failed to connect to the following etcd host(s) [<REDACTED>]",
```

**Other details that may be helpful:**

Adding new etcd nodes **AND THEN**  removing the terminated etcd nodes and restoring from S3 backup worked.

**Environment information**
- Rancher version: `v2.4.9-rc6`
- Installation option: Single Docker install.

**Cluster information**
- Cluster type: Custom
- Machine type: EC2 `t3.medium`
- Kubernetes version (use `kubectl version`): `v1.18.10`

**Comment by izaac** [comment] 2020-10-28 18:51
Steps to recover: 

- Join a new etcd node to the custom cluster
- Once the etcd node is ready Rancher will ask to restore from backup.
- Restore from a previous etcd S3 backup
- Once the backup starts trigger a delete from Rancher to each etcd node that is not provisioning
- Wait for the Cluster to become active.

**Comment by izaac** [comment] 2020-10-29 21:39
Rancher version: `v2.4-head (10/29/2020)` _64bc7bb50 _

The scenario is now passing the automation test that was failing to remove the nodes from the cluster in `v2.4.9-rc6`

**Comment by sowmyav27** [comment] 2020-10-29 23:31
**On 2.4.9-rc7**

- Validated the original issue - [here](https://github.com/rancher/rancher/issues/29801#issue-730950421)  and it is seen fixed.
- Validated upgrade of cluster - drain enabled/disabled
- Validated adding/deleting worker nodes from node driver and custom clusters. NO issues seen

**Comment by sowmyav27** [comment] 2020-10-30 02:15
Closing this issue as its validated on 2.4.9-rc7
Basic checks of node drain in vsphere also worked

Forwardport is tracked here - https://github.com/rancher/rancher/issues/29852

**Closed** 2020-10-30 02:16 UTC
Labels: [zube]: To Test, area/backup-recover, area/etcd, kind/bug-qa

**Comment by bmdepesa** [comment] 2020-10-30 13:26
rancher/rancher:v2.4.9-rc7

Performed regression testing around vSphere PV drain

* Create a cluster w/ cloud provider on vSphere
* Create a workload w/ a PV attached
* Delete the node where the workload is running
* Workload is drained, scheduled to another node
* PV is attached to the rescheduled workload

I ran this scenario about 10 times. The very first time, the PV appeared to be deleted and not attached to the workload, but I was unable to reproduce this in subsequent runs across multiple clusters and a fresh Rancher install. When this happened there were no indications of any errors in the logs.
