### ISSUE TITLE
When control plane becomes unavailable (host powered down) when there is another control plane in the cluster , not able to deploy nodes in the worker plane and other control plane.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#13706] opened 2018-05-24 21:56 UTC
**Rancher versions:v2.0.2

**Steps to Reproduce:**
Create a cluster with following node configurations:
1 control (n1)
1 etcd (n2)
1 worker (n3)

Add 1 more control node (n4)

Power down control node - n1.

Wait for the node to be marked  "unavailable".

Try to create a daemon set.
3 pods get created out of which only 1 pod was able to start sucessfully which is on the new control node.
There is an attempt made to start a pod in the worker node that fails with following error:

```
 Normal   SuccessfulMountVolume   5m                  kubelet, ip-172-31-3-155  MountVolume.SetUp succeeded for volume "default-token-mqlnn"
  Normal   SandboxChanged          4m (x12 over 5m)    kubelet, ip-172-31-3-155  Pod sandbox changed, it will be killed and re-created.
  Warning  FailedCreatePodSandBox  14s (x100 over 5m)  kubelet, ip-172-31-3-155  Failed create pod sandbox: rpc error: code = Unknown desc = NetworkPlugin cni failed to set up pod "hellotest-qjr5t_default" network: error getting ClusterInformation: Get https://10.43.0.1:443/apis/crd.projectcalico.org/v1/clusterinformations/default: dial tcp 10.43.0.1:443: getsockopt: no route to host
```
Other pod is attempted to start in the control node that is unavailable.

Deploying  a pod with some scale , results in all the pods getting deployed on the worker node and it get stuck in "ContainerCreating" state.

```
NAME                      READY     STATUS              RESTARTS   AGE
hello1-74f74757b9-5swtv   0/1       ContainerCreating   0          39m
hello1-74f74757b9-8rdp2   0/1       ContainerCreating   0          39m
hello1-74f74757b9-gz72c   0/1       ContainerCreating   0          39m
hello1-74f74757b9-xql8l   0/1       ContainerCreating   0          39m

```
**Results:**

**Comment by ChromoX** [comment] 2018-05-27 01:12
I am having a very similar result as the example posted above in similar circumstances.

My scenario:
  1. Start 3 control plane nodes.
  2. Reboot 1 control plane node.
    * During this reboot I never see the Rancher interface tell me anything is wrong. This I find weird. 
  3. Wait for rebooted node to come back up. (I don't know if this ever really happens because the interface seems to never report any other node status other than ```Active```.
  4. Try to schedule anything.
  5. I get the ```ContainerCreating``` state for forever.

I find a lot of the following messages in my kubelet on all the hosts in my cluster:
```
E0527 01:07:38.349627    5832 summary.go:102] Failed to get system container stats for "/docker/c89e477599a773c9921fe1ed07277d0aeb12081a004b673ccbb15c7c243caa0b": failed to get cgroup stats for "/docker/c89e477599a773c9921fe1ed07277d0aeb12081a004b673ccbb15c7c243caa0b": failed to get container info for "/docker/c89e477599a773c9921fe1ed07277d0aeb12081a004b673ccbb15c7c243caa0b": unknown container "/docker/c89e477599a773c9921fe1ed07277d0aeb12081a004b673ccbb15c7c243caa0b"
```

**Comment by etlweather** [comment] 2018-05-31 00:45
I have a similar issue with 3 nodes running etcd/control services - take one out and the API/WebUI become unresponsive for a while. Seems similar problem.

https://forums.rancher.com/t/need-for-rancher-ha-impact-if-down/10574/6?u=etlweather

**Comment by miv** [comment] 2018-06-07 12:12
I have the same problem. Killing one of the control nodes makes cluster unable to schedule workloads. Rancher interface and kublectl are alive, but nothing gets scheduled.

*Scenario is:*

- Create a cluster with 3 controls, 3 etcd,  each of them are also the worker nodes
- Kill one of the nodes
- Schedule something (busybox)

*Expected:*

Container scheduled on one of the working nodes and booted up.

*Actually happened:*

Contained does scheduled to working node, but can't boot up. It seems calico still tries to communicate with etcd on node that's down 

After failed node has been brought up - container has started.

See logs below


```
➜  ~ kubectl get nodes
NAME           STATUS     ROLES                      AGE       VERSION
129.69.8.172   Ready      controlplane,etcd,worker   9m        v1.10.1
129.69.8.173   NotReady   controlplane,etcd,worker   9m        v1.10.1
129.69.8.174   Ready      controlplane,etcd,worker   9m        v1.10.1
```


```
Events:
  Type     Reason                  Age               From                   Message
  ----     ------                  ----              ----                   -------
  Normal   Scheduled               3m                default-scheduler      Successfully assigned test-76765c65b9-lkvjx to 129.69.8.174
  Normal   SuccessfulMountVolume   3m                kubelet, 129.69.8.174  MountVolume.SetUp succeeded for volume "default-token-frd29"
  Warning  FailedCreatePodSandBox  31s (x6 over 3m)  kubelet, 129.69.8.174  Failed create pod sandbox: rpc error: code = Unknown desc = NetworkPlugin cni failed to set up pod "test-76765c65b9-lkvjx_default" network: error getting ClusterInformation: Get https://10.200.0.1:443/apis/crd.projectcalico.org/v1/clusterinformations/default: dial tcp 10.200.0.1:443: i/o timeout
  Warning  FailedCreatePodSandBox  20s               kubelet, 129.69.8.174  Failed create pod sandbox: rpc error: code = Unknown desc = NetworkPlugin cni failed to set up pod "test-76765c65b9-lkvjx_default" network: error getting ClusterInformation: Get https://10.200.0.1:443/apis/crd.projectcalico.org/v1/clusterinformations/default: net/http: TLS handshake timeout
  Normal   SandboxChanged          19s (x7 over 3m)  kubelet, 129.69.8.174  Pod sandbox changed, it will be killed and re-created.
  Normal   Pulling                 11s               kubelet, 129.69.8.174  pulling image "busybox"
  Normal   Pulled                  8s                kubelet, 129.69.8.174  Successfully pulled image "busybox"
  Normal   Created                 8s                kubelet, 129.69.8.174  Created container
  Normal   Started                 8s                kubelet, 129.69.8.174  Started container
```

**Comment by miv** [comment] 2018-06-08 08:53
I tried same scenario but this time with separate node for worker, but result is the same.


Create cluster like this. And import it to rancher.

```
nodes:
  - address: 224.12.24.172 # hostname or IP to access nodes
    user: root # root user (usually 'root')
    role: [controlplane,etcd] # K8s roles for node
    ssh_key_path: ../rancher_ssh_key # path to PEM file
  - address: 224.12.24.173
    user: root
    role: [controlplane,etcd]
    ssh_key_path: ../rancher_ssh_key
  - address: 224.12.24.174
    user: root
    role: [controlplane,etcd]
    ssh_key_path: ../rancher_ssh_key
  - address: 224.12.24.185
    user: root
    role: [worker]
    ssh_key_path: ../rancher_ssh_key
services:
  kube-api:
    service_cluster_ip_range: 10.200.0.0/16
  kube-controller:
    cluster_cidr: 10.199.0.0/16
    service_cluster_ip_range: 10.200.0.0/16
  kubelet:
    cluster_dns_server: 10.200.0.10
    extra_binds:
    - /srv:/srv
```

Kill one of the hosts

![image](https://user-images.githubusercontent.com/9864/41148749-5fb7c354-6b12-11e8-8095-45359a4596f7.png)

Try to schedule a workload.

```
Events:
  Type     Reason                  Age              From                    Message
  ----     ------                  ----             ----                    -------
  Normal   Scheduled               3m               default-scheduler       Successfully assigned busybox-7c457c545-xcxgz to 159.69.22.185
  Normal   SuccessfulMountVolume   3m               kubelet, 159.69.22.185  MountVolume.SetUp succeeded for volume "default-token-m959r"
  Warning  FailedCreatePodSandBox  3s (x7 over 3m)  kubelet, 159.69.22.185  Failed create pod sandbox: rpc error: code = Unknown desc = NetworkPlugin cni failed to set up pod "busybox-7c457c545-xcxgz_default" network: error getting ClusterInformation: Get https://10.200.0.1:443/apis/crd.projectcalico.org/v1/clusterinformations/default: dial tcp 10.200.0.1:443: i/o timeout
  Normal   SandboxChanged          2s (x7 over 3m)  kubelet, 159.69.22.185  Pod sandbox changed, it will be killed and re-created.
```

**Comment by jomeier** [comment] 2018-06-08 14:00
Is this changeset related to a fix for this problems?

https://github.com/rancher/rancher/pull/13718

**Comment by st3fanK** [comment] 2018-07-04 14:00
Hi we have the same problem. What's the status?

**Comment by alexandrem** [comment] 2018-07-05 02:13
I have encountered somewhat similar problems, but with different symptoms.

**Steps to reproduce**
Create a cluster with following topology:
- 3 etcd 
- 2 controlplane
- 2 worker nodes

Provider: Openstack

Kill one controlplane openstack cloud vm, e.g master01

**Expected results**

master01 appears unhealthy in Rancher.

All node services (kubelet, kube-proxy, nginx-proxy) reconnect gracefully to the second master02.

**Actual results**

In Rancher UI cluster nodes page, multiple hosts appear unhealthy:

- master01 (obviously)
- some etcd nodes (e.g etc01)
- some worker nodes (e.g worker01)

*services impacted below are those running on the nodes above.*

CNI daemons (e.g flannel) lose connection to api server and cannot configure/update the pod network overlay. This should actually use the iptables dnat entry for kubernetes:https service ip, but for some reason it won't do the load distribution using iptables random probability rules towards the healthy api servers. Also, the list of kubernetes api services won't get updated correctly in iptables by kube-proxy (see below) to remove the unhealthy entries.

Pods that need to speak to api server cannot do anymore via kubernetes service ip.

kube-proxy daemon loses connection to api server (using nginx 127.0.0.1:6443)

kubelet loses connection to api server (using nginx 127.0.0.1:6443)

nginx-proxy daemon cannot speak anymore to kubernetes api. It seems stuck to unhealthy master01, causing all the above daemons to not be able to reach api anymore.

So what we experience is a global outage caused by missing a single master api server with a cluster that should be HA.

**Comment by etlweather** [comment] 2018-07-05 17:47
@will-chan 
Any update on this bug?

**Comment by etlweather** [comment] 2018-07-09 21:54
@deniseschannon Is there an update on this? To me, this really makes Rancher 2 NOT production-ready. 

I have 3 nodes running all - worker,etcd and controlplan. If I take a node out,  everything becomes unavailable. Not just Rancher UI, API, kubectl - but also the load because the Nginx ingress needs to refresh its config and can't...

**Comment by murac** [comment] 2018-08-02 00:32
@jomeier `advertise_ip` is the same as setting the rancher-server URL once the cluster is deployed, is it not? this issue is the only mention of such an option i that I can find and wondering if I'm missing something. would this be an argument passed to the cattle-server? or are you referring to some undocumented rke variable?

thanks

**Comment by HanYL-coder** [comment] 2018-08-02 03:49
I got the same issue on v2.0.6.
No idea how to get it fixed.

**Comment by adingilloRancher** [comment] 2018-08-06 21:15
Master 6/8

Not able to reproduce.

**Closed by adingilloRancher** 2018-08-06 21:15 UTC
Labels: kind/bug, status/to-test, version/2.0

**Comment by ChromoX** [comment] 2018-08-07 02:01
I don't understand why this issue was closed? It seems above there are many people who are experiencing these issues.

I think this might only affect bare-metal installations.

**Comment by alexandrem** [comment] 2018-08-07 03:10
It's not only related to bare metal, but any providers with RKE. I have this with our openstack integration.

No need to close this issue. I can reproduce this anytime with my deployment.

I will spend some time most likely in the following month to address this.

**Comment by rflume** [comment] 2019-05-28 09:06
Hi, we also encounter this issue in an AWS environment. The cluster was created from Rancher 2.2.1 with the custom nodes option.

The cluster randomly becomes irresponsive ("Alert: etcd-0 is unhealthy" error). workloads cannot be deployed as we're getting timeouts. 

Last time it happened yesterday evening, today in the morning the cluster was all good again though...

Is it still possible to change the cluster's apiEndpoint somehow after the cluster went live?
I'm wondering why rancher does not create a LB for the kube-apiservers automatically in cloud environments as this is required/recommended in the official [Kubernetes Docs](https://kubernetes.io/docs/setup/independent/high-availability/#create-load-balancer-for-kube-apiserver). I would like to set one up manually now, but it seems the cluster's apiEndpoint can't be edited via the Rancher UI in cluster config ("View in API" --> "Edit")...

**Comment by adeleglise** [comment] 2020-06-01 08:20
So it appears that this is stil happening. I can reproduce with rancher 2.4.2, boostraped with RKE on CentOS VMs.

**Comment by jhughes2112** [comment] 2020-06-13 03:55
Still there.  Rancher 2.4.4, bare metal.
