### ISSUE TITLE
A bug of add account  when "Local Authentication" enabled

### ISSUE THREAD

**Issue by wangweihong** [rancher/rancher#4865] opened 2016-05-20 10:25 UTC
**Rancher Version:**
v1.0.1
**Docker Version:**
1.10.3
**OS and where are the hosts located? (cloud, bare metal, etc):**
centos7.2
**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
single node rancher
**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle
**Steps to Reproduce:**
1. enabled local Authentication
2. add an new account called "test".
3. add another account called "test" too ,and it will fail for "publicValue is not unique";
   Then change "Login Username" to a name which is unique, e.g."test123".  Click "Save"
   Wait a few seconds, UI shows a Warning icon without any message. Click “Cancel" to return to upper menu. 
 
**Results:** 
   Account "test123"   created.
**Expected:**

**Comment by deniseschannon** [comment] 2016-05-20 16:44
Duplicate of https://github.com/rancher/rancher/issues/4864

**Closed by deniseschannon** 2016-05-20 16:44 UTC
