### ISSUE TITLE
cluster member/cluster owner/project member/project owner/readonly need to be removed from custom options?

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#11089] opened 2018-01-23 15:57 UTC
Rancher version - rancher build form jan 22

Custom Roles presented when adding users to Cluster , includes "Project Owner"/"Project Member"/"Read only" (Note Cluster Owner / Cluster member is not included here)

Custom Roles presented when adding users to Project , includes "Cluster Owner"/"Cluster Member"/"Read only"(Note Project Owner / Project member is not included here)

Should cluster member/cluster owner/project member/project owner/readonly be removed from custom options (both in project and cluster context) since there are other granular roles (that make up these roles) being already presented in custom roles list ?

**Comment by deniseschannon** [comment] 2018-01-23 17:27
Duplicate of https://github.com/rancher/rancher/issues/10837

**Comment by sangeethah** [comment] 2018-01-23 17:39
@deniseschannon , this is not about filtering based on global/project/cluster for the custom roles. We would not need these roles to be even presented as "Custom Roles" for any scope  project/cluster.

**Comment by deniseschannon** [comment] 2018-01-23 17:53
that's exactly what the filter will do. the filter in the backend allows it so that the UI will not present it.

**Closed** 2018-01-23 17:54 UTC
Labels: area/ui, kind/bug, version/2.0

**Comment by westlywright** [comment] 2018-01-23 17:55
two filters will be applied to this when the fix is pushed, `hidden` and `context`. if roles are showing up in the wrong areas then they will need the context changed in the API.
