### ISSUE TITLE
`system-agent-upgrader` pods in `Error` state in an RKE2 cluster 

### ISSUE THREAD

**Issue by sowmyav27** [rancher/rancher#36868] opened 2022-03-13 01:42 UTC
**Rancher Server Setup**
- Rancher version: 2.6-head commit id `f904267`
- Installation option (Docker install/Helm Chart): docker install

**Information about the Cluster**
- Kubernetes version: `v1.21.10+rke2r1`
- Cluster Type (Local/Downstream): RKE2 EC2 node driver cluster - 3 etcd, 2 cp and 3 worker nodes

**User Information**
- What is the role of the user logged in? (Admin/Cluster Owner/Cluster Member/Project Owner/Project Member/Custom) admin

   
**Describe the bug**
`system-agent-upgrader` pods in `Error` state in an RKE2 cluster 

**To Reproduce**
- Deployed an ec2 node driver RKE2 cluster on rancher
- `apply-system-agent-upgrader` pods in error state
- Logs of the pod:
```
+ TMPDIRBASE=/var/lib/rancher/agent/tmp
--
Sun, Mar 13 2022 6:45:22 am | + mkdir -p /host/var/lib/rancher/agent/tmp
Sun, Mar 13 2022 6:45:22 am | + chroot /host /bin/sh -c 'mktemp -d -p /var/lib/rancher/agent/tmp'
Sun, Mar 13 2022 6:45:22 am | + TMPDIR=/var/lib/rancher/agent/tmp/tmp.alf7OJaW7i
Sun, Mar 13 2022 6:45:22 am | + cp /opt/rancher-system-agent-suc/install.sh /host/var/lib/rancher/agent/tmp/tmp.alf7OJaW7i
Sun, Mar 13 2022 6:45:22 am | + cp /opt/rancher-system-agent-suc/rancher-system-agent /host/var/lib/rancher/agent/tmp/tmp.alf7OJaW7i
Sun, Mar 13 2022 6:45:22 am | + chmod +x /host/var/lib/rancher/agent/tmp/tmp.alf7OJaW7i/install.sh
Sun, Mar 13 2022 6:45:22 am | + '[' -n sowmya-1-pool1-86c70b07-n6v47 ]
Sun, Mar 13 2022 6:45:22 am | + NODE_FILE=/host/var/lib/rancher/agent/tmp/tmp.alf7OJaW7i/node.yaml
Sun, Mar 13 2022 6:45:22 am | + kubectl get node sowmya-1-pool1-86c70b07-n6v47 -o yaml
Sun, Mar 13 2022 6:45:22 am | + '[' -z ]
Sun, Mar 13 2022 6:45:22 am | + grep -q 'node-role.kubernetes.io/etcd: "true"' /host/var/lib/rancher/agent/tmp/tmp.alf7OJaW7i/node.yaml
Sun, Mar 13 2022 6:45:22 am | + '[' -z ]
Sun, Mar 13 2022 6:45:22 am | + grep -q 'node-role.kubernetes.io/controlplane: "true"' /host/var/lib/rancher/agent/tmp/tmp.alf7OJaW7i/node.yaml
Sun, Mar 13 2022 6:45:22 am | + '[' -z ]
Sun, Mar 13 2022 6:45:22 am | + grep -q 'node-role.kubernetes.io/control-plane: "true"' /host/var/lib/rancher/agent/tmp/tmp.alf7OJaW7i/node.yaml
Sun, Mar 13 2022 6:45:22 am | + '[' -z ]
Sun, Mar 13 2022 6:45:22 am | + grep -q 'node-role.kubernetes.io/worker: "true"' /host/var/lib/rancher/agent/tmp/tmp.alf7OJaW7i/node.yaml
Sun, Mar 13 2022 6:45:22 am | + export 'CATTLE_AGENT_BINARY_LOCAL=true'
Sun, Mar 13 2022 6:45:22 am | + export 'CATTLE_AGENT_BINARY_LOCAL_LOCATION=/var/lib/rancher/agent/tmp/tmp.alf7OJaW7i/rancher-system-agent'
Sun, Mar 13 2022 6:45:22 am | + '[' -s /host/etc/systemd/system/rancher-system-agent.env ]
Sun, Mar 13 2022 6:45:22 am | + chroot /host /var/lib/rancher/agent/tmp/tmp.alf7OJaW7i/install.sh
Sun, Mar 13 2022 6:45:22 am | [FATAL] You must select at least one role.
```

**Comment by snasovich** [comment] 2022-03-14 18:38
This seems to be caused by https://github.com/rancher/rke2/issues/2583 and intermittently happens when there are etcd-only nodes.
The linked issue is not going to be fixed in the RKE2 releases included with 2.6.4, so we will most likely mark this one as `release-note`.
Per discussion with the team this issue should not affect cluster functioning beyond not being able to upgrade `system-agent` version.
We want to check if upgrading k8s version will recreate the job that schedules `apply-system-agent-upgrader` pods so that once the issue is fixed on RKE2 side, simply upgrading k8s version will make the issue go away.

Whoever picks up this issue, please investigate the above.

**Comment by thedadams** [comment] 2022-04-12 23:49
After investigating this issue, it seems that the answer to the question "Will the `apply-system-agent-upgrader` jobs/pods get recreated when upgrading the Kubernetes version of a cluster?" is no.

These jobs/pods will only get recreated when the `system-agent-upgrade-image` changes. This usually happens when upgrading Rancher versions.

**Comment by slickwarren** [comment] 2022-04-13 20:58
blocked on rke2 ticket: https://github.com/rancher/rke2/issues/2583

**Comment by snasovich** [comment] 2022-04-18 20:54
@slickwarren , moving to test based on this comment to linked RKE2 issue. Version `v1.21.11+rke2r1` is already in KDM's dev branch.
https://github.com/rancher/rke2/issues/2583#issuecomment-1100194740

**Comment by Josh-Diamond** [comment] 2022-04-21 02:19
Ticket #36868 - Test Results

With Docker on single-node instance:

NOTE: Attempted to reproduce 3 times; Reproduced on 3rd cluster only; Intermittent

Reproduced on rancher `v2.6-f904267847e9c60b4db76f885654b3ab6a8442cb-head`:
1. Fresh install of rancher `v2.6-head`
2. As admin, provision a downstream EC-2 AWS Node driver RKE2 cluster with k8s `v1.21.10+rke2r1`; [3 etcd, 2 cp, 3 wkr]
3. Reproduced - `system-agent-upgrader` pods in `Error` state

Screenshots:

`Attempt #1` - [successful]
![image1](https://user-images.githubusercontent.com/46494969/164358184-9e2d9823-2286-4095-b9f7-7ccb13f2c68c.png)

`Attempt #2` - [successful]
![image2](https://user-images.githubusercontent.com/46494969/164358162-88526a0f-a763-4d55-9c56-7a9932eff40e.png)

`Attempt #3` - [reproduced]
![image3](https://user-images.githubusercontent.com/46494969/164358139-2789b1f8-08bf-4875-bd06-8ba5355d843a.png)

![image4](https://user-images.githubusercontent.com/46494969/164358119-2050f586-a146-45d7-9485-9bea878429ea.png)

![image5](https://user-images.githubusercontent.com/46494969/164358085-0f9b52b4-a5db-4012-b63a-be6596259b62.png)

`Logs`
```log
+ TMPDIRBASE=/var/lib/rancher/agent/tmp
+ mkdir -p /host/var/lib/rancher/agent/tmp
+ chroot /host /bin/sh -c 'mktemp -d -p /var/lib/rancher/agent/tmp'
+ TMPDIR=/var/lib/rancher/agent/tmp/tmp.YAPLTNyrrQ
+ cp /opt/rancher-system-agent-suc/install.sh /host/var/lib/rancher/agent/tmp/tmp.YAPLTNyrrQ
+ cp /opt/rancher-system-agent-suc/rancher-system-agent /host/var/lib/rancher/agent/tmp/tmp.YAPLTNyrrQ
+ chmod +x /host/var/lib/rancher/agent/tmp/tmp.YAPLTNyrrQ/install.sh
+ '[' -n jkeslar-aws-sau-3-pool1-REDACTED ]
+ NODE_FILE=/host/var/lib/rancher/agent/tmp/tmp.YAPLTNyrrQ/node.yaml
+ kubectl get node jkeslar-aws-sau-3-pool1-REDACTED-REDACTED -o yaml
+ '[' -z  ]
+ grep -q 'node-role.kubernetes.io/etcd: "true"' /host/var/lib/rancher/agent/tmp/tmp.YAPLTNyrrQ/node.yaml
+ '[' -z  ]
+ grep -q 'node-role.kubernetes.io/controlplane: "true"' /host/var/lib/rancher/agent/tmp/tmp.YAPLTNyrrQ/node.yaml
+ '[' -z  ]
+ grep -q 'node-role.kubernetes.io/control-plane: "true"' /host/var/lib/rancher/agent/tmp/tmp.YAPLTNyrrQ/node.yaml
+ '[' -z  ]
+ grep -q 'node-role.kubernetes.io/worker: "true"' /host/var/lib/rancher/agent/tmp/tmp.YAPLTNyrrQ/node.yaml
+ export 'CATTLE_AGENT_BINARY_LOCAL=true'
+ export 'CATTLE_AGENT_BINARY_LOCAL_LOCATION=/var/lib/rancher/agent/tmp/tmp.YAPLTNyrrQ/rancher-system-agent'
+ '[' -s /host/etc/systemd/system/rancher-system-agent.env ]
+ chroot /host /var/lib/rancher/agent/tmp/tmp.YAPLTNyrrQ/install.sh
[FATAL]  You must select at least one role.
```
---

Verified on rancher `v2.6-39902086651f4a9311326bac364c2a595bb140b4-head`:
1. Fresh install of rancher `v2.6-head`
2. As admin, provision 3 downstream EC-2 AWS Node driver RKE2 cluster with k8s `v1.21.11+rke2r1`; [3 etcd, 2 cp, 3 wkr]
3. Verified - All clusters successfully provisioned with `system-agent-upgrader` pods in `Active` state; Jobs successful

Screenshots:

`Jobs - Cluster #1`
![image6](https://user-images.githubusercontent.com/46494969/164358030-a64e3ade-7bb4-421c-ac8c-6c85fd0944b6.png)


`Events - Cluster #2`
![image7](https://user-images.githubusercontent.com/46494969/164358016-9069f0ec-4a20-4045-bade-be49d6fe8722.png)


`Jobs - Cluster #3`
![image8](https://user-images.githubusercontent.com/46494969/164358003-c59e9fda-df94-4af1-864b-b865195cd9dd.png)

**Closed by Josh-Diamond** 2022-04-21 02:19 UTC
Labels: kind/bug-qa, [zube]: QA Working, dependency-rke2, status/release-blocker, team/area2
