### ISSUE TITLE
Error when upgrading app: spec.clusterIP: Invalid value

### ISSUE THREAD

**Issue by polivbr** [rancher/rancher#13734] opened 2018-05-25 21:18 UTC
**Rancher versions:**
rancher/server or rancher/rancher: 2.0.2
rancher/agent or rancher/rancher-agent: 2.0.2

**Docker version: (`docker version`,`docker info` preferred)**
17.03.2-ce

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
NAME="Ubuntu"
VERSION="16.04 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
UBUNTU_CODENAME=xenial
4.4.0-21-generic

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
Bare-metal

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
HA rancher

**Steps to Reproduce:**
1) enable Helm catalog
2) Install rabbitmq-ha app
3) Upgrade rabbitmq-ha app

**Results:**
Gets stuck on "Installing", with the error:
Installing
Kubectl apply failed. Error: The Service "rabbitmq-ha" is invalid: spec.clusterIP: Invalid value: "": field is immutable : exit status 1

This doesn't happen when installing/upgrading via Helm/Tiller, only through the Rancher UI or CLI.

Also get similar errors (spec.clusterIP) when upgrading other apps.

**Comment by loganhz** [comment] 2018-06-27 05:52
I can reproduce the issue in `v2.0.4`.

A workaround is finding the cluster ip and putting it into UI.

@StrongMonkey Not sure why Helm does work.

![image](https://user-images.githubusercontent.com/21168270/41955101-31dde3ce-7a11-11e8-86aa-5cfc3d6cdc91.png)

![image](https://user-images.githubusercontent.com/21168270/41955077-11088fe6-7a11-11e8-8301-1ceff3a13bf3.png)

**Comment by gregkeys** [comment] 2018-06-29 03:30
Im experiencing a similar issue, we have rabbitmq-ha as a requirement for one of our charts, Im experiencing it whenever I deploy a stack which includes rabbitmq-ha

**Comment by gregkeys** [comment] 2018-06-29 04:16
Turns out one of our charts in the requirement.yaml had a malformed tls section, fixing that made this error go away for us

**Comment by loganhz** [comment] 2018-10-21 10:32
Fixed in v2.1.0 as we have added Tiller back. 

https://github.com/rancher/rancher/issues/14642

**Closed by loganhz** 2018-10-21 10:32 UTC
Labels: area/catalog, kind/bug, version/2.0
