### ISSUE TITLE
catalog issues with 2.1.0

### ISSUE THREAD

**Issue by gregkeys** [rancher/rancher#16039] opened 2018-10-10 00:49 UTC
**Rancher versions:**
rancher/server 2.1.0

## Cluster Config
k8s provisioned with rke, migrated rancher from 2.0.8 rke addon method to 2.1.0 helm method

almost all catalog apps have some sort of error immediately after upgrade, deleting and re-adding seems to fix most of the issues, this is a fine for non production apps, its the production apps that we can't delete that we are most concerned with.

`Templateversions.management.cattle.io "gitlab-ci-gitlab-runner-0.1.33" not found` seeing these on any catalog app where old versions have been removed from the repository - re-adding versions back into repo does not fix the error - deleting and reinstallign seems to fix the error.

`Installing
Failed to install app demo-dev. Error: release demo-dev failed: the server could not find the requested resource (post certificates.certmanager.k8s.io)` seeing this on catalog apps that request an ssl certificate from the rancher certs manager, deleting and re-installing the app seems to fix this.

`Failed to install app sonarqube. Error: UPGRADE FAILED: the server is currently unable to handle the request (get configmaps)` this is coming from the sonarqube app from the helm charts repo

`Failed to install app demo-uat. Error: a release named demo-uat already exists. Run: helm ls --all demo-uat; to check the status of the release Or run: helm del --purge demo-uat; to delete it` 

Deleting catalog apps, with the above errors does not seem to actually remove any services in 2.1.0. it removes the catalog app link but not the underlying services, e.g. delete an app in the namespace demo-dev then do a  `kubectl get all -n demo-dev` all services are still running, there are some apps that seem to delete services when deleting, hard to tell what the differences between them is atm

**Comment by guangbochen** [comment] 2018-10-10 14:19
Hi @gregkeys, is your rancher server an HA config or a single node? thanks.

**Comment by gregkeys** [comment] 2018-10-10 18:00
HA config with 3 nodes

**Comment by gregkeys** [comment] 2018-10-11 21:31
yes

**Comment by MaxDiOrio** [comment] 2018-11-02 20:35
I'm seeing similar doing a Helm chart upgrade:
Failed to install app prometheus-qrpdj. Error: UPGRADE FAILED: the server is currently unable to handle the request (get configmaps)

Single node Rancher instance running on v2.1.1, upgraded from v2.0.7

**Comment by Terminator637** [comment] 2018-11-08 19:06
> I'm seeing similar doing a Helm chart upgrade:
> Failed to install app prometheus-qrpdj. Error: UPGRADE FAILED: the server is currently unable to handle the request (get configmaps)
> 
> Single node Rancher instance running on v2.1.1, upgraded from v2.0.7

I have the same problems

**Comment by loganhz** [comment] 2018-12-27 08:48
I cannot reproduce this issue with the following steps:

1. Start a single node rancher 2.0.7
2. Add a cluster
3. Deploy a catalog app
4. Upgrade rancher from 2.0.7 to 2.1.1
5. Upgrade the catalog app

Could you provide rancher server log, please?

**Comment by MaxDiOrio** [comment] 2018-12-27 08:54
How long are logs kept? It's been almost 2 months.  I had to delete and redeploy the app because of this.

**Comment by isavcic** [comment] 2019-04-13 11:07
Any workarounds for `Failed to install app X. Error: UPGRADE FAILED: the server is currently unable to handle the request (get configmaps)` ?

**Comment by deniseschannon** [comment] 2019-04-19 20:55
@isavcic you are most likely hitting this issue: https://github.com/rancher/rancher/issues/18571

I'm going to close this original issue as we weren't able to reproduce it.

**Closed by deniseschannon** 2019-04-19 20:55 UTC
Labels: area/catalog, kind/bug, priority/0, team/cn
