### ISSUE TITLE
Using longhorn as a persistent volume fails to deploy statefulset

### ISSUE THREAD

**Issue by kingsd041** [rancher/rancher#13374] opened 2018-05-09 06:31 UTC
**Rancher versions:**
rancher/server or rancher/rancher:  v2.0.0

**Docker version: (`docker version`,`docker info` preferred)**
17.03.2-ce
**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
Ubuntu 16.04.4 LTS
**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
AWS
**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
single node rancher
**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**
Kubernetes
**Steps to Reproduce:**
1. Launch longhorn from catalog apps
2. Deploy a statefulset on the Rancher UI to set up 2 pods and use lonhorn as a persistent volume. 
![image](https://user-images.githubusercontent.com/19684717/39798559-9ff54130-5393-11e8-943b-0701c5b91f4c.png)
![image](https://user-images.githubusercontent.com/19684717/39798569-a7234d6c-5393-11e8-91a8-5c6aa0c93567.png)
![image](https://user-images.githubusercontent.com/19684717/39798581-af74c144-5393-11e8-8db5-5ed5df005965.png)

**Results:**
The second pod failed to start.

```
root@ip-172-31-43-111:~# kubectl get pod
NAME              READY     STATUS              RESTARTS   AGE
test-longhorn-0   1/1       Running             0          20m
test-longhorn-1   0/1       ContainerCreating   0          20m
```

```
root@ip-172-31-43-111:~# kubectl describe pod test-longhorn-1
Events:
  Type     Reason                 Age                From                       Message
  ----     ------                 ----               ----                       -------
  Normal   Scheduled              20m                default-scheduler          Successfully assigned test-longhorn-1 to ip-172-31-14-169
  Normal   SuccessfulMountVolume  20m                kubelet, ip-172-31-14-169  MountVolume.SetUp succeeded for volume "default-token-t2vs9"
  Warning  FailedMount            20s (x9 over 18m)  kubelet, ip-172-31-14-169  Unable to mount volumes for pod "test-longhorn-1_default(427feb1c-534d-11e8-87f3-0a64d2b9fb98)": timeout expired waiting for volumes to attach or mount for pod "default"/"test-longhorn-1". list of unmounted volumes=[test-longhorn-volume]. list of unattached volumes=[test-longhorn-volume default-token-t2vs9]
  Warning  FailedMount            5s (x18 over 20m)  kubelet, ip-172-31-14-169  MountVolume.SetUp failed for volume "pvc-2f40ae4c-534d-11e8-87f3-0a64d2b9fb98" : mount command failed, status: Failure, reason: Device /dev/longhorn/pvc-2f40ae4c-534d-11e8-87f3-0a64d2b9fb98 is already existed

```

**Comment by BalaBalaYi** [comment] 2018-05-09 08:47
Maybe the same issue. Not sure.
I submit a issue in rancher/longhorn ( #61 in rancher/longhorn ). Please check. thx^^

**Comment by yasker** [comment] 2018-05-17 21:05
@kingsd041 is it still reproducible?

**Comment by guangbochen** [comment] 2018-05-18 00:16
@yasker this seems to be an API bug, even if I create two persisten volume it is still mounted to the first pod only, the workload seems didn't handle the volume logic properly for statefulSet.

**Comment by guangbochen** [comment] 2018-05-18 00:34
yep, @deniseschannon can you help to assign some to resolve this issue, this should be a common API bug of statefulSet PVC provisioning in the workload page.

**Comment by vincent99** [comment] 2018-05-18 00:36
This isn't an API bug, or really a bug at all.  It's a missing feature to allow describing yet-another-kind-of-storage in the UI.

**Comment by Terminator637** [comment] 2018-07-17 07:39
@vincent99 and when this feature will be implemented? Because now Longhorn is useless from Rancher UI with StateFulSets.

**Comment by bakuppus** [comment] 2018-09-11 15:18
longhorn not support multi pods bind  persistent volume , is that true ?

**Comment by yasker** [comment] 2018-09-11 18:03
@bakuppus Longhorn is a distributed block storage solution like EBS and Google Persistent Disk, it can only be mounted on one node at a time. So it's a Read-Write-Once type storage for Kubernetes, which cannot be mounted on multiple nodes at the same time (read-only is possible, we can work on that later).

In order to scale it with the workload, you would need to use StatefulSet with VolumeClaimTemplate.

**Comment by yasker** [comment] 2018-09-11 18:08
Filed https://github.com/rancher/rancher/issues/15519. Close this one.

**Closed by yasker** 2018-09-11 18:08 UTC
Labels: kind/feature, version/2.0
