### ISSUE TITLE
Swarm does not work

### ISSUE THREAD

**Issue by bergtwvd** [rancher/rancher#7116] opened 2016-12-18 22:46 UTC
**Rancher Version:**
1.2.1

**Docker Version:**
Docker version 1.12.3, build 6b644ec

**OS and where are the hosts located? (cloud, bare metal, etc):**
I have two clusters with 4 VMs in each:
- Cluster 1 (4 x Ubuntu 14.04): Linux docker-3 4.4.0-31-generic #50~14.04.1-Ubuntu SMP Wed Jul 13 01:07:32 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
- Cluster 2 (4 x Ubuntu 16.04): Linux ranch-master 4.4.0-53-generic #74-Ubuntu SMP Fri Dec 2 15:59:10 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

VMs run under Hyper-V on Windows 10 laptop.

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
Server (with DB), and 3 slaves.

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Swarm

**Steps to Reproduce:**
- start server (see quick start guide)
- add slaves one by one

**Results:** 
Intermittent results, but never a working Swarm cluster (details below).

**Expected:**
Swarm cluster with 3 nodes and one master node.

Results:
Intermittent and different per attempt.

In the final attempt I end up with two Swarm masters and see a few stack traces in the Rancher server log (see below). The cluster is not usable.

````
2016-12-18 10:56:36,741 ERROR [f1f08916-ae0a-4000-964f-bdb8478829c2:1025] [instance:48] [instance.remove] [] [cutorService-10] [c.p.e.p.i.DefaultProcessInstanceImpl] Unknown exception java.lang.IllegalStateException: Attempt to cancel when process is still transitioning
        at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl.runDelegateLoop(DefaultProcessInstanceImpl.java:188) [cattle-framework-engine-0.5.0-SNAPSHOT.jar:na]
        at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl.executeWithProcessInstanceLock(DefaultProcessInstanceImpl.java:155) [cattle-framework-engine-0.5.0-SNAPSHOT.jar:na]
        at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl$1.doWithLock(DefaultProcessInstanceImpl.java:114) [cattle-framework-engine-0.5.0-SNAPSHOT.jar:na]
        at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl$1.doWithLock(DefaultProcessInstanceImpl.java:111) [cattle-framework-engine-0.5.0-SNAPSHOT.jar:na]
        at io.cattle.platform.lock.impl.AbstractLockManagerImpl$3.doWithLock(AbstractLockManagerImpl.java:40) [cattle-framework-lock-0.5.0-SNAPSHOT.jar:na]
        at io.cattle.platform.lock.impl.LockManagerImpl.doLock(LockManagerImpl.java:33) [cattle-framework-lock-0.5.0-SNAPSHOT.jar:na]
        at io.cattle.platform.lock.impl.AbstractLockManagerImpl.lock(AbstractLockManagerImpl.java:13) [cattle-framework-lock-0.5.0-SNAPSHOT.jar:na]
        at io.cattle.platform.lock.impl.AbstractLockManagerImpl.lock(AbstractLockManagerImpl.java:37) [cattle-framework-lock-0.5.0-SNAPSHOT.jar:na]
        at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl.execute(DefaultProcessInstanceImpl.java:111) [cattle-framework-engine-0.5.0-SNAPSHOT.jar:na]
        at io.cattle.platform.object.process.impl.DefaultObjectProcessManager.executeStandardProcess(DefaultObjectProcessManager.java:32) ~[cattle-framework-object-0.5.0-SNAPSHOT.jar:na]
        at io.cattle.platform.process.common.handler.AbstractObjectProcessLogic.remove(AbstractObjectProcessLogic.java:105) ~[cattle-iaas-logic-common-0.5.0-SNAPSHOT.jar:na]
        at io.cattle.platform.process.instance.InstanceRemove.storage(InstanceRemove.java:49) ~[cattle-iaas-logic-0.5.0-SNAPSHOT.jar:na]
        at io.cattle.platform.process.instance.InstanceRemove.handle(InstanceRemove.java:39) ~[cattle-iaas-logic-0.5.0-SNAPSHOT.jar:na]
        at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl.runHandler(DefaultProcessInstanceImpl.java:448) [cattle-framework-engine-0.5.0-SNAPSHOT.jar:na]
        at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl$4.execute(DefaultProcessInstanceImpl.java:399) ~[cattle-framework-engine-0.5.0-SNAPSHOT.jar:na]
        at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl$4.execute(DefaultProcessInstanceImpl.java:393) ~[cattle-framework-engine-0.5.0-SNAPSHOT.jar:na]
        at io.cattle.platform.engine.idempotent.Idempotent.execute(Idempotent.java:42) ~[cattle-framework-engine-0.5.0-SNAPSHOT.jar:na]
        at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl.runHandlers(DefaultProcessInstanceImpl.java:393) [cattle-framework-engine-0.5.0-SNAPSHOT.jar:na]
        at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl.runLogic(DefaultProcessInstanceImpl.java:495) [cattle-framework-engine-0.5.0-SNAPSHOT.jar:na]
        at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl.runWithProcessLock(DefaultProcessInstanceImpl.java:326) [cattle-framework-engine-0.5.0-SNAPSHOT.jar:na]
        at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl$2.doWithLockNoResult(DefaultProcessInstanceImpl.java:243) ~[cattle-framework-engine-0.5.0-SNAPSHOT.jar:na]
        at io.cattle.platform.lock.LockCallbackNoReturn.doWithLock(LockCallbackNoReturn.java:7) [cattle-framework-lock-0.5.0-SNAPSHOT.jar:na]
        at io.cattle.platform.lock.LockCallbackNoReturn.doWithLock(LockCallbackNoReturn.java:3) [cattle-framework-lock-0.5.0-SNAPSHOT.jar:na]
        at io.cattle.platform.lock.impl.AbstractLockManagerImpl$3.doWithLock(AbstractLockManagerImpl.java:40) [cattle-framework-lock-0.5.0-SNAPSHOT.jar:na]
        at io.cattle.platform.lock.impl.LockManagerImpl.doLock(LockManagerImpl.java:33) [cattle-framework-lock-0.5.0-SNAPSHOT.jar:na]
        at io.cattle.platform.lock.impl.AbstractLockManagerImpl.lock(AbstractLockManagerImpl.java:13) [cattle-framework-lock-0.5.0-SNAPSHOT.jar:na]
        at io.cattle.platform.lock.impl.AbstractLockManagerImpl.lock(AbstractLockManagerImpl.java:37) [cattle-framework-lock-0.5.0-SNAPSHOT.jar:na]
        at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl.acquireLockAndRun(DefaultProcessInstanceImpl.java:240) [cattle-framework-engine-0.5.0-SNAPSHOT.jar:na]
        at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl.runDelegateLoop(DefaultProcessInstanceImpl.java:182) [cattle-framework-engine-0.5.0-SNAPSHOT.jar:na]
        at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl.executeWithProcessInstanceLock(DefaultProcessInstanceImpl.java:155) [cattle-framework-engine-0.5.0-SNAPSHOT.jar:na]
        at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl$1.doWithLock(DefaultProcessInstanceImpl.java:114) [cattle-framework-engine-0.5.0-SNAPSHOT.jar:na]
        at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl$1.doWithLock(DefaultProcessInstanceImpl.java:111) [cattle-framework-engine-0.5.0-SNAPSHOT.jar:na]
        at io.cattle.platform.lock.impl.AbstractLockManagerImpl$3.doWithLock(AbstractLockManagerImpl.java:40) [cattle-framework-lock-0.5.0-SNAPSHOT.jar:na]
        at io.cattle.platform.lock.impl.LockManagerImpl.doLock(LockManagerImpl.java:33) [cattle-framework-lock-0.5.0-SNAPSHOT.jar:na]
        at io.cattle.platform.lock.impl.AbstractLockManagerImpl.lock(AbstractLockManagerImpl.java:13) [cattle-framework-lock-0.5.0-SNAPSHOT.jar:na]
        at io.cattle.platform.lock.impl.AbstractLockManagerImpl.lock(AbstractLockManagerImpl.java:37) [cattle-framework-lock-0.5.0-SNAPSHOT.jar:na]
        at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl.execute(DefaultProcessInstanceImpl.java:111) [cattle-framework-engine-0.5.0-SNAPSHOT.jar:na]
        at io.cattle.platform.engine.server.impl.ProcessInstanceDispatcherImpl.processExecuteWithLock(ProcessInstanceDispatcherImpl.java:98) [cattle-framework-engine-0.5.0-SNAPSHOT.jar:na]
        at io.cattle.platform.engine.server.impl.ProcessInstanceDispatcherImpl$1$1.doWithLockNoResult(ProcessInstanceDispatcherImpl.java:71) [cattle-framework-engine-0.5.0-SNAPSHOT.jar:na]
        at io.cattle.platform.lock.LockCallbackNoReturn.doWithLock(LockCallbackNoReturn.java:7) [cattle-framework-lock-0.5.0-SNAPSHOT.jar:na]
        at io.cattle.platform.lock.LockCallbackNoReturn.doWithLock(LockCallbackNoReturn.java:3) [cattle-framework-lock-0.5.0-SNAPSHOT.jar:na]
        at io.cattle.platform.lock.impl.AbstractLockManagerImpl$4.doWithLock(AbstractLockManagerImpl.java:50) [cattle-framework-lock-0.5.0-SNAPSHOT.jar:na]
        at io.cattle.platform.lock.impl.LockManagerImpl.doLock(LockManagerImpl.java:33) [cattle-framework-lock-0.5.0-SNAPSHOT.jar:na]
        at io.cattle.platform.lock.impl.AbstractLockManagerImpl.tryLock(AbstractLockManagerImpl.java:25) [cattle-framework-lock-0.5.0-SNAPSHOT.jar:na]
        at io.cattle.platform.lock.impl.AbstractLockManagerImpl.tryLock(AbstractLockManagerImpl.java:47) [cattle-framework-lock-0.5.0-SNAPSHOT.jar:na]
        at io.cattle.platform.engine.server.impl.ProcessInstanceDispatcherImpl$1.doRun(ProcessInstanceDispatcherImpl.java:68) [cattle-framework-engine-0.5.0-SNAPSHOT.jar:na]
        at org.apache.cloudstack.managed.context.NoExceptionRunnable.runInContext(NoExceptionRunnable.java:15) [cattle-framework-managed-context-0.5.0-SNAPSHOT.jar:na]
        at org.apache.cloudstack.managed.context.ManagedContextRunnable$1.run(ManagedContextRunnable.java:49) [cattle-framework-managed-context-0.5.0-SNAPSHOT.jar:na]
        at org.apache.cloudstack.managed.context.impl.DefaultManagedContext$1.call(DefaultManagedContext.java:55) [cattle-framework-managed-context-0.5.0-SNAPSHOT.jar:na]
        at org.apache.cloudstack.managed.context.impl.DefaultManagedContext.callWithContext(DefaultManagedContext.java:108) [cattle-framework-managed-context-0.5.0-SNAPSHOT.jar:na]
        at org.apache.cloudstack.managed.context.impl.DefaultManagedContext.runWithContext(DefaultManagedContext.java:52) [cattle-framework-managed-context-0.5.0-SNAPSHOT.jar:na]
        at org.apache.cloudstack.managed.context.ManagedContextRunnable.run(ManagedContextRunnable.java:46) [cattle-framework-managed-context-0.5.0-SNAPSHOT.jar:na]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_72]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_72]
        at java.lang.Thread.run(Thread.java:745) [na:1.8.0_72]
Caused by: io.cattle.platform.engine.process.impl.ProcessCancelException: State [activating] is not valid for process [image.remove:null] on resource [47]
        at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl.preRunStateCheck(DefaultProcessInstanceImpl.java:265) [cattle-framework-engine-0.5.0-SNAPSHOT.jar:na]
        at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl.runDelegateLoop(DefaultProcessInstanceImpl.java:180) [cattle-framework-engine-0.5.0-SNAPSHOT.jar:na]
        at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl.executeWithProcessInstanceLock(DefaultProcessInstanceImpl.java:155) [cattle-framework-engine-0.5.0-SNAPSHOT.jar:na]
        at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl$1.doWithLock(DefaultProcessInstanceImpl.java:114) [cattle-framework-engine-0.5.0-SNAPSHOT.jar:na]
        at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl$1.doWithLock(DefaultProcessInstanceImpl.java:111) [cattle-framework-engine-0.5.0-SNAPSHOT.jar:na]
        at io.cattle.platform.lock.impl.AbstractLockManagerImpl$3.doWithLock(AbstractLockManagerImpl.java:40) [cattle-framework-lock-0.5.0-SNAPSHOT.jar:na]
        at io.cattle.platform.lock.impl.LockManagerImpl.doLock(LockManagerImpl.java:33) [cattle-framework-lock-0.5.0-SNAPSHOT.jar:na]
        at io.cattle.platform.lock.impl.AbstractLockManagerImpl.lock(AbstractLockManagerImpl.java:13) [cattle-framework-lock-0.5.0-SNAPSHOT.jar:na]
        at io.cattle.platform.lock.impl.AbstractLockManagerImpl.lock(AbstractLockManagerImpl.java:37) [cattle-framework-lock-0.5.0-SNAPSHOT.jar:na]
        at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl.execute(DefaultProcessInstanceImpl.java:111) [cattle-framework-engine-0.5.0-SNAPSHOT.jar:na]
        at io.cattle.platform.object.process.impl.DefaultObjectProcessManager.executeStandardProcess(DefaultObjectProcessManager.java:32) ~[cattle-framework-object-0.5.0-SNAPSHOT.jar:na]
        at io.cattle.platform.process.common.handler.AbstractObjectProcessLogic.remove(AbstractObjectProcessLogic.java:105) ~[cattle-iaas-logic-common-0.5.0-SNAPSHOT.jar:na]
        at io.cattle.platform.process.volume.VolumeRemove.handle(VolumeRemove.java:69) ~[cattle-iaas-logic-0.5.0-SNAPSHOT.jar:na]
        at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl.runHandler(DefaultProcessInstanceImpl.java:448) [cattle-framework-engine-0.5.0-SNAPSHOT.jar:na]
        at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl$4.execute(DefaultProcessInstanceImpl.java:399) ~[cattle-framework-engine-0.5.0-SNAPSHOT.jar:na]
        at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl$4.execute(DefaultProcessInstanceImpl.java:393) ~[cattle-framework-engine-0.5.0-SNAPSHOT.jar:na]
        at io.cattle.platform.engine.idempotent.Idempotent.execute(Idempotent.java:42) ~[cattle-framework-engine-0.5.0-SNAPSHOT.jar:na]
        at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl.runHandlers(DefaultProcessInstanceImpl.java:393) [cattle-framework-engine-0.5.0-SNAPSHOT.jar:na]
        at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl.runLogic(DefaultProcessInstanceImpl.java:495) [cattle-framework-engine-0.5.0-SNAPSHOT.jar:na]
        at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl.runWithProcessLock(DefaultProcessInstanceImpl.java:326) [cattle-framework-engine-0.5.0-SNAPSHOT.jar:na]
        at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl$2.doWithLockNoResult(DefaultProcessInstanceImpl.java:243) ~[cattle-framework-engine-0.5.0-SNAPSHOT.jar:na]
        at io.cattle.platform.lock.LockCallbackNoReturn.doWithLock(LockCallbackNoReturn.java:7) [cattle-framework-lock-0.5.0-SNAPSHOT.jar:na]
        at io.cattle.platform.lock.LockCallbackNoReturn.doWithLock(LockCallbackNoReturn.java:3) [cattle-framework-lock-0.5.0-SNAPSHOT.jar:na]
        at io.cattle.platform.lock.impl.AbstractLockManagerImpl$3.doWithLock(AbstractLockManagerImpl.java:40) [cattle-framework-lock-0.5.0-SNAPSHOT.jar:na]
        at io.cattle.platform.lock.impl.LockManagerImpl.doLock(LockManagerImpl.java:33) [cattle-framework-lock-0.5.0-SNAPSHOT.jar:na]
        at io.cattle.platform.lock.impl.AbstractLockManagerImpl.lock(AbstractLockManagerImpl.java:13) [cattle-framework-lock-0.5.0-SNAPSHOT.jar:na]
        at io.cattle.platform.lock.impl.AbstractLockManagerImpl.lock(AbstractLockManagerImpl.java:37) [cattle-framework-lock-0.5.0-SNAPSHOT.jar:na]
        at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl.acquireLockAndRun(DefaultProcessInstanceImpl.java:240) [cattle-framework-engine-0.5.0-SNAPSHOT.jar:na]
        at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl.runDelegateLoop(DefaultProcessInstanceImpl.java:182) [cattle-framework-engine-0.5.0-SNAPSHOT.jar:na]
        ... 54 common frames omitted

2016-12-18 10:56:36,779 ERROR [:] [] [] [] [cutorService-10] [.e.s.i.ProcessInstanceDispatcherImpl] Unknown exception running process [instance.remove:1025] on [48], canceled by [State [acti
````

**Comment by bergtwvd** [comment] 2016-12-20 21:40
In another attempt to get a small swarm running I did:

- create Swarm environment
- add first host (which becomes master, as shown on the Infrastructure > Hosts page
- add second host (which also becomes a master, as shown on the Infrastructure > Hosts page

The log output of the swarmkit container on the second hosts shows:

````
20-12-2016 22:04:04    Old token: SWMTKN-1-22dv0e37ipk1xv94ssceah0gzrfua5p6klh8s92z3bnj1uu8mx-89kx05m3lvwdcuiftxfzs39fb
20-12-2016 22:04:04Current token: SWMTKN-1-2rgcx954i1w2c3jnbklfet4bwdvtdp23l1ggsgsw9iou0ecvd0-cdlbsryuod1jb9xg5eiaongh8
20-12-2016 22:04:04Retrying set host label swarm=wait_leaving
20-12-2016 22:04:05Retrying set host label swarm=wait_leaving
20-12-2016 22:04:05Retrying set host label swarm=wait_leaving
20-12-2016 22:04:06Retrying set host label swarm=wait_leaving
20-12-2016 22:04:06Failed to set host label swarm=wait_leaving (5 tries)
20-12-2016 22:04:08    Old token: SWMTKN-1-22dv0e37ipk1xv94ssceah0gzrfua5p6klh8s92z3bnj1uu8mx-89kx05m3lvwdcuiftxfzs39fb
20-12-2016 22:04:08Current token: SWMTKN-1-2rgcx954i1w2c3jnbklfet4bwdvtdp23l1ggsgsw9iou0ecvd0-cdlbsryuod1jb9xg5eiaongh8
20-12-2016 22:04:08Set host label swarm=wait_leaving
20-12-2016 22:04:08Leaving old swarm
20-12-2016 22:04:08Node left the swarm.
20-12-2016 22:04:08Deleted host label swarm
20-12-2016 22:04:08time="2016-12-20T21:04:08Z" level=info msg="Listening on port: 2378"
20-12-2016 22:04:08Set host label swarm=wait_leader
20-12-2016 22:04:09Set host label swarm=wait_token
20-12-2016 22:04:11+ docker swarm join --token SWMTKN-1-2rgcx954i1w2c3jnbklfet4bwdvtdp23l1ggsgsw9iou0ecvd0-aczcbfc9mc38bsrf62le6exp7 --listen-addr 10.10.10.21:2377 --advertise-addr 10.10.10.21:2377 10.10.10.23:2377
20-12-2016 22:04:11+ set +x
20-12-2016 22:04:11This node joined a swarm as a manager.
20-12-2016 22:04:11Set host label swarm=manager
20-12-2016 22:04:11Set host label swarm=manager
````

Why are there two managers?

- add the third host, which also becomes a master.

The logfile of the swarmkit container on the 3rd host:

````

20-12-2016 22:38:26time="2016-12-20T21:38:26Z" level=info msg="Listening on port: 2378"
20-12-2016 22:38:26Retrying set host label swarm=wait_leader
20-12-2016 22:38:27Retrying set host label swarm=wait_leader
20-12-2016 22:38:28Retrying set host label swarm=wait_leader
20-12-2016 22:38:29Retrying set host label swarm=wait_leader
20-12-2016 22:38:29Failed to set host label swarm=wait_leader (5 tries)
20-12-2016 22:38:31time="2016-12-20T21:38:31Z" level=info msg="Listening on port: 2378"
20-12-2016 22:38:31Set host label swarm=wait_leader
20-12-2016 22:38:32Set host label swarm=wait_token
20-12-2016 22:38:34+ docker swarm join --token SWMTKN-1-2rgcx954i1w2c3jnbklfet4bwdvtdp23l1ggsgsw9iou0ecvd0-aczcbfc9mc38bsrf62le6exp7 --listen-addr 10.10.10.22:2377 --advertise-addr 10.10.10.22:2377 10.10.10.23:2377
20-12-2016 22:38:35+ set +x
20-12-2016 22:38:35This node joined a swarm as a manager.
20-12-2016 22:38:35Set host label swarm=manager
20-12-2016 22:38:35Set host label swarm=manager
````

Why three managers?

**Comment by LLParse** [comment] 2016-12-20 22:32
Hi @bergtwvd, 

The default setting for our Swarm template is to create 3 managers. This is for resilience purposes - a manager stores stateful information which should ideally be replicated across multiple hosts in the case of failure.

A 3-manager deployment will survive 1 manager failing, 5-manager deployment will survive 2 managers failing, etc.

It appears that you have functioning swarm cluster. By default, a manager is also a worker - these hosts will schedule containers. Try it out:

1. Find a `swarm=manager` host and get a shell on the swarmkit-mon container
2. `docker service create --name redis redis:3.0.6`
3. `docker service scale redis=5`
4. "Kill" a host and observe reconciliation, indicating swarm tolerated the host failure

Hang tight for UI integration to be updated for the new swarm implementation.

**Comment by bergtwvd** [comment] 2016-12-20 23:27
Thanks for the response.

I played a bit with removing a host, and adding it back in. Mixed results,

On removal of a host the redis containers got re-distributed on the remaining hosts. Looks great.

Next, on the host that I removed, I stopped and removed all containers, and deleted /var/lib/rancher.
Then, from Rancher, I added the host back in. (following standard steps). However, the host seems to get stuck in ``swarm=wait_token``, with the swarmkit container failing to start up.
Opened a shell and logged into the host. I noticed that the docker daemon crashed:

````
bergtwvd@ranch-slave3:~$ journalctl -xe
Dec 21 00:20:13 ranch-slave3 dockerd[7655]: time="2016-12-21T00:20:13.581334115+01:00" level=warning msg="ignoring request to join cluster, because raft state already exists"
Dec 21 00:20:13 ranch-slave3 dockerd[7655]: time="2016-12-21T00:20:13.581586661+01:00" level=info msg="53e1e80a2234648 became follower at term 4"
Dec 21 00:20:13 ranch-slave3 dockerd[7655]: time="2016-12-21T00:20:13.581707782+01:00" level=info msg="newRaft 53e1e80a2234648 [peers: [], term: 4, commit: 0, applied: 0, lastindex: 0, last
Dec 21 00:20:13 ranch-slave3 dockerd[7655]: time="2016-12-21T00:20:13.587812878+01:00" level=info msg="Listening for local connections" addr="/var/lib/docker/swarm/control.sock" proto=unix
Dec 21 00:20:13 ranch-slave3 dockerd[7655]: time="2016-12-21T00:20:13.588137336+01:00" level=info msg="Listening for connections" addr="10.10.10.23:2377" proto=tcp
Dec 21 00:20:14 ranch-slave3 dockerd[7655]: time="2016-12-21T00:20:14.356574051+01:00" level=info msg="raft.node: 53e1e80a2234648 elected leader 3829d9cf5df6afa4 at term 4"
Dec 21 00:20:14 ranch-slave3 dockerd[7655]: time="2016-12-21T00:20:14.357620740+01:00" level=warning msg="sending message to an unrecognized member ID 3829d9cf5df6afa4"
Dec 21 00:20:14 ranch-slave3 dockerd[7655]: time="2016-12-21T00:20:14.358260355+01:00" level=error msg="could not find cluster member to query for leader address"
Dec 21 00:20:14 ranch-slave3 dockerd[7655]: time="2016-12-21T00:20:14.359297642+01:00" level=panic msg="tocommit(119) is out of range [lastIndex(0)]. Was the raft log corrupted, truncated,
Dec 21 00:20:14 ranch-slave3 dockerd[7655]: panic: (*logrus.Entry) (0x1d34f40,0xc820ac8140)
Dec 21 00:20:14 ranch-slave3 dockerd[7655]: goroutine 212 [running]:
Dec 21 00:20:14 ranch-slave3 dockerd[7655]: panic(0x1d34f40, 0xc820ac8140)
Dec 21 00:20:14 ranch-slave3 dockerd[7655]:         /usr/local/go/src/runtime/panic.go:481 +0x3e6
Dec 21 00:20:14 ranch-slave3 dockerd[7655]: github.com/Sirupsen/logrus.Entry.log(0xc8200441c0, 0xc82036a3f0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0xc820aaa6c0, ...)
Dec 21 00:20:14 ranch-slave3 dockerd[7655]:         /usr/src/docker/vendor/src/github.com/Sirupsen/logrus/entry.go:113 +0x62c
Dec 21 00:20:14 ranch-slave3 dockerd[7655]: github.com/Sirupsen/logrus.(*Entry).Panic(0xc820301b80, 0xc820ac43b8, 0x1, 0x1)
Dec 21 00:20:14 ranch-slave3 dockerd[7655]:         /usr/src/docker/vendor/src/github.com/Sirupsen/logrus/entry.go:158 +0x99
Dec 21 00:20:14 ranch-slave3 dockerd[7655]: github.com/Sirupsen/logrus.(*Entry).Panicf(0xc820301b80, 0x20e24e0, 0x5d, 0xc820aa5880, 0x2, 0x2)
Dec 21 00:20:14 ranch-slave3 dockerd[7655]:         /usr/src/docker/vendor/src/github.com/Sirupsen/logrus/entry.go:206 +0x139
Dec 21 00:20:14 ranch-slave3 dockerd[7655]: github.com/coreos/etcd/raft.(*raftLog).commitTo(0xc8204222a0, 0x77)
Dec 21 00:20:14 ranch-slave3 dockerd[7655]:         /usr/src/docker/vendor/src/github.com/coreos/etcd/raft/log.go:194 +0x1a6
Dec 21 00:20:14 ranch-slave3 dockerd[7655]: github.com/coreos/etcd/raft.(*raft).handleHeartbeat(0xc8207729c0, 0x8, 0x7db60c0f20cd1881, 0x3829d9cf5df6afa4, 0x4, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
Dec 21 00:20:14 ranch-slave3 dockerd[7655]:         /usr/src/docker/vendor/src/github.com/coreos/etcd/raft/raft.go:771 +0x44
Dec 21 00:20:14 ranch-slave3 dockerd[7655]: github.com/coreos/etcd/raft.stepFollower(0xc8207729c0, 0x8, 0x7db60c0f20cd1881, 0x3829d9cf5df6afa4, 0x4, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
Dec 21 00:20:14 ranch-slave3 dockerd[7655]:         /usr/src/docker/vendor/src/github.com/coreos/etcd/raft/raft.go:736 +0x119c
Dec 21 00:20:14 ranch-slave3 dockerd[7655]: github.com/coreos/etcd/raft.(*raft).Step(0xc8207729c0, 0x8, 0x7db60c0f20cd1881, 0x3829d9cf5df6afa4, 0x4, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
Dec 21 00:20:14 ranch-slave3 dockerd[7655]:         /usr/src/docker/vendor/src/github.com/coreos/etcd/raft/raft.go:564 +0x3e0
Dec 21 00:20:14 ranch-slave3 dockerd[7655]: github.com/coreos/etcd/raft.(*node).run(0xc8201ef8b0, 0xc8207729c0)
Dec 21 00:20:14 ranch-slave3 dockerd[7655]:         /usr/src/docker/vendor/src/github.com/coreos/etcd/raft/node.go:310 +0x90e
Dec 21 00:20:14 ranch-slave3 dockerd[7655]: created by github.com/coreos/etcd/raft.RestartNode
Dec 21 00:20:14 ranch-slave3 dockerd[7655]:         /usr/src/docker/vendor/src/github.com/coreos/etcd/raft/node.go:215 +0x2e4
Dec 21 00:20:14 ranch-slave3 systemd[1]: docker.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Dec 21 00:20:14 ranch-slave3 systemd[1]: Failed to start Docker Application Container Engine.
-- Subject: Unit docker.service has failed
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
--
-- Unit docker.service has failed.
--
-- The result is failed.
Dec 21 00:20:14 ranch-slave3 systemd[1]: docker.service: Unit entered failed state.
Dec 21 00:20:14 ranch-slave3 systemd[1]: docker.service: Failed with result 'exit-code'.
Dec 21 00:20:14 ranch-slave3 systemd[1]: Starting Docker Application Container Engine...
-- Subject: Unit docker.service has begun start-up
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
--
-- Unit docker.service has begun starting up.
Dec 21 00:20:14 ranch-slave3 dockerd[7832]: time="2016-12-21T00:20:14.397930508+01:00" level=info msg="libcontainerd: new containerd process, pid: 7836"
````

**Comment by bergtwvd** [comment] 2016-12-20 23:29
Ps.
``Hang tight for UI integration to be updated for the new swarm implementation.``

I definitely hang on :+1:

**Comment by LLParse** [comment] 2016-12-21 19:19
@bergtwvd I feel your pain regarding reuse of a failed/removed host. I would recommend uninstalling/reinstalling docker to ensure all relevant state is wiped out. I am not totally sure all swarm state is in `/var/lib/docker/swarm`, based on your findings.

The `log corrupted, truncated, or lost` error is legitimate since your old node no longer belongs to the cluster. This is essentially the behavior of etcd, it is the same code. This is how I automated cleaning up corrupted/old state in etcd:
https://github.com/LLParse/catalog-dockerfiles/blob/etcd-v2.3.7-persistence/etcd/containers/0.11.0/etcd/run.sh#L101-L103

Unfortunately, there is little we can do about this, since we don't run the Docker daemon in a container - we are at the mercy of the upstream codebase. Sometimes we can't leave the old swarm and the automation running the `docker swarm join` command is ignored because Docker sees existing state.

Marking this as duplicate of https://github.com/rancher/rancher/issues/6413. Thanks for trying this out.

**Closed by LLParse** 2016-12-21 19:19 UTC
