### ISSUE TITLE
scheduled IP's dont work with external-dns

### ISSUE THREAD

**Issue by aemneina** [rancher/rancher#9524] opened 2017-07-31 04:59 UTC
**Rancher versions:**
rancher/server: 1.5.10
rancher/agent:

**Steps to Reproduce:**
1. create host (host's primary nic has 5 other IP's that route to it)
2. edit host and add scheduled ip's
3. deploy external dns provider (route 53 in this case)
4. deploy distinct services that map to each ip
5. try to resolve services with external dns URI

**Results:**
External dns gets the host IP when resolved. This should map to the scheduled ip of the service.

**Comment by aemneina** [comment] 2017-08-07 05:29
Using io.rancher.host.external_dns_ip label to force the IP supplied to external DNS. That workaround is only effective if you have *one* scheduled IP that is not the registration IP; it's not effective for multiple IPs

**Comment by csnavely** [comment] 2017-10-05 20:32
Hi, just checking in on this one. I tested with 1.6.10, which we just installed, and the behavior was the same, and it looks like it's not assigned yet.

**Comment by loganhz** [comment] 2017-10-09 04:07
hi @aemneina  
if there are multiple scheduler IPs,  external DNS should randomly select one from them. Am I correct?

**Comment by yasker** [comment] 2017-10-09 05:20
@aemneina Should there be only IPs used in the port map can be used as external DNS IP?

**Comment by loganhz** [comment] 2017-10-09 05:50
hi @aemneina @csnavely , I can not reproduce it with rancher server `1.6.10`

I have added two scheduler IPs (`1.1.1.1` and `1.1.1.2`) on a host. 

Then deployed service A (binds to `1.1.1.1:8080`) and service B (binds to `1.1.1.2:8080`).

External DNS set `a.default.default.mydomain.com` to `1.1.1.1` and `b.default.default.mydomain.com`to `1.1.1.2`.

I think the behavior is correct. Please correct me if I'm wrong.
thanks

**Comment by csnavely** [comment] 2017-10-09 22:42
It does look like the behavior is improved in 1.6.10, obviating the need for the `io.rancher.host.external_dns_ip` label..._except_ for haproxy stacks!

When I schedule an haproxy stack w/ two scheduled IPs per host and no `io.rancher.host.external_dns_ip` label, I get scheduled IPs in the GUI "Port" display, but I get a seemingly random mix of registration and scheduled IPs in my external-dns A records.

Perhaps this is related to my other open issue, rancher/rancher/9752, which I think is a flaw in how scheduled IPs and ports are allocated for haproxy stacks. external-dns is probably at the mercy of how the scheduled IP and port is allocated.

See the attached screenshot showing the "Ports" display; here is the corresponding DNS query. It even effectively de-dups, because `128.55.206.84` and `128.55.206.85` are on the same node!

```
$ host lb.corytest.test-cattle.test.spin.nersc.org
lb.corytest.test-cattle.test.spin.nersc.org has address 128.55.219.48
lb.corytest.test-cattle.test.spin.nersc.org has address 128.55.219.49
```

![rancher rancher 9524 haproxy scheduler ips](https://user-images.githubusercontent.com/26753143/31361408-11a10a4a-ad08-11e7-83fb-7969e56898fa.png)

**Comment by loganhz** [comment] 2017-10-10 01:45
thanks @csnavely !
yes, the haproxy lb issue is related to issue 9752. 
We can wait for it and test this issue again.
thanks again

**Comment by yasker** [comment] 2017-10-11 17:39
@loganhz https://github.com/rancher/rancher/issues/9752 has been merged.

**Comment by kingsd041** [comment] 2017-10-13 05:04
@loganhz 
I can not reproduce it with rancher server 1.6.11-rc3

**Closed by kingsd041** 2017-10-13 05:04 UTC
Labels: area/external-dns, area/metadata, area/networking, kind/bug, priority/-1, team/cn
