### ISSUE TITLE
"FATA[0021] CA Certificate or Key is empty" after ran 'rke -d etcd snapshot-restore' 

### ISSUE THREAD

**Issue by lianlianhe** [rancher/rancher#19647] opened 2019-04-16 09:16 UTC
RKE version:
rke version v0.2.1
Docker version: (docker version,docker info preferred)
Client:
Version: 18.09.3
API version: 1.39
Go version: go1.10.8
Git commit: 774a1f4
Built: Thu Feb 28 06:33:21 2019
OS/Arch: linux/amd64
Experimental: false

Server: Docker Engine - Community
Engine:
Version: 18.09.3
API version: 1.39 (minimum version 1.12)
Go version: go1.10.8
Git commit: 774a1f4
Built: Thu Feb 28 06:02:24 2019
OS/Arch: linux/amd64
Experimental: false

Operating system and kernel: (cat /etc/os-release, uname -r preferred)
4.20.13-1.el7.elrepo.x86_64

Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)
cloud server
cluster.yml file:
nodes:

address: xx.xx.xx.xx
internal_address: xx.xx.xx.xx
user: docker
role: [controlplane,etcd,worker]
address: xx.xx.xx.xx
internal_address: xx.xx.xx.xx
user: docker
role: [controlplane,etcd,worker]
address: xx.xx.xx.xx
internal_address: xx.xx.xx.xx
user: docker
role: [controlplane,etcd,worker]
system_images:
kubernetes: rancher/hyperkube:v1.13.5-rancher1
network:
plugin: canal
services:
etcd:
snapshot: true
creation: 6h
retention: 24h
Steps to Reproduce:
1.build & sanctified cloud server(reimage OS,create docker user and group,ssh rsa auth)
2.copy "pki.bundle.tar.gz single-etcd-snapshot.db" from single rancher env to the node of pre-rancher HA's /opt/rke/etcd-snapshots
3. uncompress pki.bundle.tar.gz to /etc/kubernetes/ssl
4. Run - rke -d etcd snapshot-restore --name single-etcd-snapshot.db --config rancher-cluster.yml from workstation.
Results:
......
INFO[0015] [etcd] Successfully tore down etcd plane..
INFO[0015] [hosts] Cleaning up host [xx.xx.xx.xx]
INFO[0015] [hosts] Cleaning up host [xx.xx.xx.xx]
INFO[0015] [hosts] Cleaning up host [xx.xx.xx.xx]
INFO[0015] [hosts] Running cleaner container on host [xx.xx.xx.xx]
INFO[0015] [hosts] Cleaning up host [xx.xx.xx.xx]
INFO[0015] [hosts] Running cleaner container on host [xx.xx.xx.xx]
INFO[0015] [hosts] Cleaning up host [xx.xx.xx.xx]
INFO[0015] [hosts] Cleaning up host [xx.xx.xx.xx]
INFO[0015] [hosts] Running cleaner container on host [xx.xx.xx.xx]
DEBU[0015] [kube-cleaner] Checking image [rancher/rke-tools:v0.1.27] on host [xx.xx.xx.xx]
DEBU[0015] Checking if image [rancher/rke-tools:v0.1.27] exists on host [xx.xx.xx.xx]
DEBU[0015] [kube-cleaner] Checking image [rancher/rke-tools:v0.1.27] on host [xx.xx.xx.xx]
DEBU[0015] Checking if image [rancher/rke-tools:v0.1.27] exists on host [xx.xx.xx.xx]
DEBU[0015] [kube-cleaner] Checking image [rancher/rke-tools:v0.1.27] on host [xx.xx.xx.xx]
DEBU[0015] Checking if image [rancher/rke-tools:v0.1.27] exists on host [xx.xx.xx.xx]
DEBU[0015] Image [rancher/rke-tools:v0.1.27] exists on host [xx.xx.xx.xx]
DEBU[0015] [kube-cleaner] No pull necessary, image [rancher/rke-tools:v0.1.27] exists on host [xx.xx.xx.xx]
DEBU[0015] Image [rancher/rke-tools:v0.1.27] exists on host [xx.xx.xx.xx]
DEBU[0015] [kube-cleaner] No pull necessary, image [rancher/rke-tools:v0.1.27] exists on host [xx.xx.xx.xx]
DEBU[0015] Image [rancher/rke-tools:v0.1.27] exists on host [xx.xx.xx.xx]
DEBU[0015] [kube-cleaner] No pull necessary, image [rancher/rke-tools:v0.1.27] exists on host [xx.xx.xx.xx]
INFO[0016] [kube-cleaner] Successfully started [kube-cleaner] container on host [xx.xx.xx.xx]
INFO[0016] [kube-cleaner] Successfully started [kube-cleaner] container on host [xx.xx.xx.xx]
INFO[0016] [kube-cleaner] Successfully started [kube-cleaner] container on host [xx.xx.xx.xx]
INFO[0016] [hosts] Removing cleaner container on host [xx.xx.xx.xx]
INFO[0016] [hosts] Removing cleaner container on host [xx.xx.xx.xx]
INFO[0016] [hosts] Removing dead container logs on host [xx.xx.xx.xx]
DEBU[0016] [cleanup] Starting log link cleanup on host [xx.xx.xx.xx]
DEBU[0016] [remove/rke-log-cleaner] Checking if container is running on host [xx.xx.xx.xx]
INFO[0016] [hosts] Removing cleaner container on host [xx.xx.xx.xx]
INFO[0016] [hosts] Removing dead container logs on host [xx.xx.xx.xx]
DEBU[0016] [cleanup] Starting log link cleanup on host [xx.xx.xx.xx]
DEBU[0016] [remove/rke-log-cleaner] Checking if container is running on host [xx.xx.xx.xx]
DEBU[0016] [remove/rke-log-cleaner] Container doesn't exist on host [xx.xx.xx.xx]
DEBU[0016] [remove/rke-log-cleaner] Container doesn't exist on host [xx.xx.xx.xx]
DEBU[0016] [cleanup] Checking image [rancher/rke-tools:v0.1.27] on host [xx.xx.xx.xx]
DEBU[0016] Checking if image [rancher/rke-tools:v0.1.27] exists on host [xx.xx.xx.xx]
DEBU[0016] [cleanup] Checking image [rancher/rke-tools:v0.1.27] on host [xx.xx.xx.xx]
DEBU[0016] Checking if image [rancher/rke-tools:v0.1.27] exists on host [xx.xx.xx.xx]
DEBU[0016] Image [rancher/rke-tools:v0.1.27] exists on host [xx.xx.xx.xx]
DEBU[0016] [cleanup] No pull necessary, image [rancher/rke-tools:v0.1.27] exists on host [xx.xx.xx.xx]
DEBU[0016] Image [rancher/rke-tools:v0.1.27] exists on host [xx.xx.xx.xx]
DEBU[0016] [cleanup] No pull necessary, image [rancher/rke-tools:v0.1.27] exists on host [xx.xx.xx.xx]
INFO[0016] [hosts] Removing dead container logs on host [xx.xx.xx.xx]
DEBU[0016] [cleanup] Starting log link cleanup on host [xx.xx.xx.xx]
DEBU[0016] [remove/rke-log-cleaner] Checking if container is running on host [xx.xx.xx.xx]
DEBU[0016] [remove/rke-log-cleaner] Container doesn't exist on host [xx.xx.xx.xx]
DEBU[0016] [cleanup] Checking image [rancher/rke-tools:v0.1.27] on host [xx.xx.xx.xx]
DEBU[0016] Checking if image [rancher/rke-tools:v0.1.27] exists on host [xx.xx.xx.xx]
DEBU[0016] Image [rancher/rke-tools:v0.1.27] exists on host [xx.xx.xx.xx]
DEBU[0016] [cleanup] No pull necessary, image [rancher/rke-tools:v0.1.27] exists on host [xx.xx.xx.xx]
INFO[0016] [cleanup] Successfully started [rke-log-cleaner] container on host [xx.xx.xx.xx]
DEBU[0016] [remove/rke-log-cleaner] Checking if container is running on host [xx.xx.xx.xx]
DEBU[0016] [remove/rke-log-cleaner] Removing container on host [xx.xx.xx.xx]
INFO[0016] [cleanup] Successfully started [rke-log-cleaner] container on host [xx.xx.xx.xx]
DEBU[0016] [remove/rke-log-cleaner] Checking if container is running on host [xx.xx.xx.xx]
DEBU[0016] [remove/rke-log-cleaner] Removing container on host [xx.xx.xx.xx]
INFO[0016] [cleanup] Successfully started [rke-log-cleaner] container on host [xx.xx.xx.xx]
DEBU[0016] [remove/rke-log-cleaner] Checking if container is running on host [xx.xx.xx.xx]
DEBU[0016] [remove/rke-log-cleaner] Removing container on host [xx.xx.xx.xx]
INFO[0017] [remove/rke-log-cleaner] Successfully removed container on host [xx.xx.xx.xx]
DEBU[0017] [cleanup] Successfully cleaned up log links on host [xx.xx.xx.xx]
INFO[0017] [hosts] Successfully cleaned up host [xx.xx.xx.xx]
INFO[0017] [remove/rke-log-cleaner] Successfully removed container on host [xx.xx.xx.xx]
DEBU[0017] [cleanup] Successfully cleaned up log links on host [xx.xx.xx.xx]
INFO[0017] [hosts] Successfully cleaned up host [xx.xx.xx.xx]
INFO[0017] [remove/rke-log-cleaner] Successfully removed container on host [xx.xx.xx.xx]
DEBU[0017] [cleanup] Successfully cleaned up log links on host [xx.xx.xx.xx]
INFO[0017] [hosts] Successfully cleaned up host [xx.xx.xx.xx]
INFO[0017] [etcd] Restoring [single-etcd-snapshot.db] snapshot on etcd host [xx.xx.xx.xx]
DEBU[0017] [remove/etcd-restore] Checking if container is running on host [xx.xx.xx.xx]
DEBU[0017] [remove/etcd-restore] Container doesn't exist on host [xx.xx.xx.xx]
DEBU[0017] [etcd] Checking image [rancher/coreos-etcd:v3.2.24-rancher1] on host [xx.xx.xx.xx]
DEBU[0017] Checking if image [rancher/coreos-etcd:v3.2.24-rancher1] exists on host [xx.xx.xx.xx]
DEBU[0017] Image [rancher/coreos-etcd:v3.2.24-rancher1] exists on host [xx.xx.xx.xx]
DEBU[0017] [etcd] No pull necessary, image [rancher/coreos-etcd:v3.2.24-rancher1] exists on host [xx.xx.xx.xx]
INFO[0017] [etcd] Successfully started [etcd-restore] container on host [xx.xx.xx.xx]
INFO[0018] [etcd] Restoring [single-etcd-snapshot.db] snapshot on etcd host [xx.xx.xx.xx]
DEBU[0018] [remove/etcd-restore] Checking if container is running on host [xx.xx.xx.xx]
DEBU[0018] [remove/etcd-restore] Container doesn't exist on host [xx.xx.xx.xx]
DEBU[0018] [etcd] Checking image [rancher/coreos-etcd:v3.2.24-rancher1] on host [xx.xx.xx.xx]
DEBU[0018] Checking if image [rancher/coreos-etcd:v3.2.24-rancher1] exists on host [xx.xx.xx.xx]
DEBU[0018] Image [rancher/coreos-etcd:v3.2.24-rancher1] exists on host [xx.xx.xx.xx]
DEBU[0018] [etcd] No pull necessary, image [rancher/coreos-etcd:v3.2.24-rancher1] exists on host [xx.xx.xx.xx]
INFO[0019] [etcd] Successfully started [etcd-restore] container on host [xx.xx.xx.xx]
INFO[0019] [etcd] Restoring [single-etcd-snapshot.db] snapshot on etcd host [xx.xx.xx.xx]
DEBU[0019] [remove/etcd-restore] Checking if container is running on host [xx.xx.xx.xx]
DEBU[0019] [remove/etcd-restore] Container doesn't exist on host [xx.xx.xx.xx]
DEBU[0019] [etcd] Checking image [rancher/coreos-etcd:v3.2.24-rancher1] on host [xx.xx.xx.xx]
DEBU[0019] Checking if image [rancher/coreos-etcd:v3.2.24-rancher1] exists on host [xx.xx.xx.xx]
DEBU[0019] Image [rancher/coreos-etcd:v3.2.24-rancher1] exists on host [xx.xx.xx.xx]
DEBU[0019] [etcd] No pull necessary, image [rancher/coreos-etcd:v3.2.24-rancher1] exists on host [xx.xx.xx.xx]
INFO[0020] [etcd] Successfully started [etcd-restore] container on host [xx.xx.xx.xx]
INFO[0021] Initiating Kubernetes cluster
DEBU[0021] Host: xx.xx.xx.xx has role: controlplane
DEBU[0021] Host: xx.xx.xx.xx has role: etcd
DEBU[0021] Host: xx.xx.xx.xx has role: worker
DEBU[0021] Host: xx.xx.xx.xx has role: controlplane
DEBU[0021] Host: xx.xx.xx.xx has role: etcd
DEBU[0021] Host: xx.xx.xx.xx has role: worker
DEBU[0021] Host: xx.xx.xx.xx has role: controlplane
DEBU[0021] Host: xx.xx.xx.xx has role: etcd
DEBU[0021] Host: xx.xx.xx.xx has role: worker
DEBU[0021] [state] local kubeconfig not found, this is a new cluster
INFO[0021] [certificates] Generating Kubernetes API server aggregation layer requestheader client CA certificates
FATA[0021] CA Certificate or Key is empty

I follow the doc of rancher ha to recover a cluster still encountered same issue https://rancher.com/docs/rancher/v2.x/en/backups/restorations/ha-restoration/

**Comment by jruffet** [comment] 2019-04-18 10:02
Same here with rke 0.2.2, after a fresh HA install (3 nodes). Steps: 

- Shutdown the other 2 nodes.
- Cleaned up the node (`xx.xx.xx.xx`) following https://rancher.com/docs/rancher/v2.x/en/cluster-admin/cleaning-cluster-nodes/ 
- Followed https://rancher.com/docs/rancher/v2.x/en/backups/restorations/ha-restoration/ (commented out the 2 other nodes from my rke config file)

```bash
$ ssh xx.xx.xx.xx "mkdir -p /opt/rke/etcd-snapshots"
$ scp snapshot.db xx.xx.xx.xx:/opt/rke/etcd-snapshots/
# copy saved /etc/kubernetes to node
$ scp -r kubernetes xx.xx.xx.xx:/etc
```
```
$ rke etcd snapshot-restore --name snapshot.db --config rke-rancher-cluster.yml
INFO[0000] Restoring etcd snapshot snapshot.db
INFO[0000] Successfully Deployed state file at [./rke-rancher-cluster.rkestate]
INFO[0000] [dialer] Setup tunnel for host [xx.xx.xx.xx]
INFO[0000] [certificates] Pulling image [rancher/rke-tools:v0.1.27] on host [xx.xx.xx.xx]
INFO[0007] [certificates] Successfully pulled image [rancher/rke-tools:v0.1.27] on host [xx.xx.xx.xx]
WARN[0012] failed to stop etcd container on host [xx.xx.xx.xx]: Can't stop Docker container [etcd] for host [xx.xx.xx.xx]: Error response from daemon: No such container: etcd  
INFO[0012] [etcd] starting backup server on host [xx.xx.xx.xx]
INFO[0013] [etcd] Successfully started [etcd-Serve-backup] container on host [xx.xx.xx.xx]
INFO[0018] [remove/etcd-Serve-backup] Successfully removed container on host [xx.xx.xx.xx]
INFO[0018] [etcd] Checking if all snapshots are identical
INFO[0018] [etcd] Successfully started [etcd-checksum-checker] container on host [xx.xx.xx.xx]
INFO[0019] [etcd] Checksum of etcd snapshot on host [xx.xx.xx.xx] is [e3bf09b421519ef0c1af71dc35d496d0]
INFO[0019] Cleaning old kubernetes cluster
INFO[0019] [worker] Tearing down Worker Plane..
INFO[0019] [worker] Successfully tore down Worker Plane..
INFO[0019] [controlplane] Tearing down the Controller Plane..
INFO[0019] [controlplane] Successfully tore down Controller Plane..
INFO[0019] [etcd] Tearing down etcd plane..
INFO[0019] [etcd] Successfully tore down etcd plane..
INFO[0019] [hosts] Cleaning up host [xx.xx.xx.xx]
INFO[0019] [hosts] Cleaning up host [xx.xx.xx.xx]
INFO[0019] [hosts] Running cleaner container on host [xx.xx.xx.xx]
INFO[0019] [kube-cleaner] Successfully started [kube-cleaner] container on host [xx.xx.xx.xx]
INFO[0020] [hosts] Removing cleaner container on host [xx.xx.xx.xx]
INFO[0020] [hosts] Removing dead container logs on host [xx.xx.xx.xx]
INFO[0020] [cleanup] Successfully started [rke-log-cleaner] container on host [xx.xx.xx.xx]
INFO[0020] [remove/rke-log-cleaner] Successfully removed container on host [xx.xx.xx.xx]
INFO[0020] [hosts] Successfully cleaned up host [xx.xx.xx.xx]
INFO[0020] [etcd] Restoring [snapshot.db] snapshot on etcd host [xx.xx.xx.xx]
INFO[0020] [etcd] Pulling image [rancher/coreos-etcd:v3.2.24-rancher1] on host [xx.xx.xx.xx]
INFO[0024] [etcd] Successfully pulled image [rancher/coreos-etcd:v3.2.24-rancher1] on host [xx.xx.xx.xx]
INFO[0024] [etcd] Successfully started [etcd-restore] container on host [xx.xx.xx.xx]
INFO[0025] Initiating Kubernetes cluster
INFO[0025] [certificates] Generating Kubernetes API server aggregation layer requestheader client CA certificates
FATA[0025] CA Certificate or Key is empty
```

**Comment by jruffet** [comment] 2019-04-18 11:30
Duplicate of https://github.com/rancher/rke/issues/1286

**Closed** 2019-04-30 09:49 UTC
