### ISSUE TITLE
"TestAndApply Error" when setting up GitHub application for pipelines

### ISSUE THREAD

**Issue by PBXg33k** [rancher/rancher#27011] opened 2020-05-09 09:58 UTC
Just deployed a new rancher environment on a new kubernetes environment and was in the process of setting up Rancher to automagically deploy applications from my public & private repositories.

In order for pipelines to work i registered a GitHub application for rancher to use and provided Rancher with the Client ID & Client Secret. The OAuth process went smoothly untill i was sent back to the callback uri (rancher).

Everytime i try to setup a GitHub application in Rancher i am presented with the following error:
`"failed to decode the config, error: 1 error(s) decoding:↵↵* 'ManagedFields[0].Time' expected a map, got 'string'"`

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v2.4.3` UI: `v2.4.22` |
|Route|`/p/local:p-v4zkc/pipeline?group=none`|
|Installation method|Helm rancher|
|Cluster Type|Custom|
|Machine Type|VPS (Hetzner Cloud)|
|Kubernetes Version|v1.18.2|

**Comment by masteredward** [comment] 2020-05-14 21:33
Same problem here! Rancher 2.4.3, Helm Install K3s 1.18.2.

**Comment by houtianhong** [comment] 2020-05-20 15:15
Rancher 2.4.3 has the same problem when adding the authorization of private gitlab-ce account. Click the authorization button and the error will pop up immediately:
failed to decode the config, error: 1 error(s) decoding: * 'ManagedFields[0].Time' expected a map, got 'string'

**Comment by icanhazbeer** [comment] 2020-05-26 17:32
Also ran into this issue running K3S 1.18.2

| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v2.4.3` UI: `v2.4.22` |

**Comment by icanhazbeer** [comment] 2020-05-26 19:51
We just tested with a reinstall of K3S/Rancher using K3S 1.17.5 and has **_success_** with this feature:

| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v2.4.3` UI: `v2.4.22` |
|Kubernetes Version in k3s| `**1.17.5**` |

What broke in the 1.18 version?

**Comment by raynic35** [comment] 2020-06-05 17:36
Same problem
Useful | Info
-- | --
Versions | Rancher v2.4.4
Kubernetes Version in k3s | 1.18.3, v1.17.6+k3s1
Any news on that?

**Comment by fbrbovic** [comment] 2020-06-10 23:04
Same problem on my end as well, any update on this?

**Comment by khatrig** [comment] 2020-06-25 07:34
rancher 2.4.5 does not work as well

**Comment by sammasamadhi** [comment] 2020-06-25 14:29
Same error on 2.4.5

**Comment by marcoroganovic** [comment] 2020-07-07 13:19
Same issue.
Version: 2.4.5

**Comment by sunliusi** [comment] 2020-07-07 15:53
same error
version:2.4.5
k3s rancher

**Comment by sunliusi** [comment] 2020-07-08 03:47
any solution?

**Comment by peterasang** [comment] 2020-07-08 08:06
same error, but on BitBucket:
version:2.4.5
k3s rancher

**Comment by sammasamadhi** [comment] 2020-07-09 00:44
rollback to v2.4.4

**Comment by sunliusi** [comment] 2020-07-09 01:13
> rollback to v2.4.4  


Is 2.4.4 available? Someone also reported an error in 2.4.4

**Comment by sunliusi** [comment] 2020-07-09 09:58
I test k3s and k8s to install rancher, it doesn't work. 

The problem was so serious that the pipeline was completely unavailable

**Comment by noismaster** [comment] 2020-07-10 11:33
I had the same error in rancher 2.4.5. I tried adding a pipeline to Gitlab 13.1.4-ee on premise.
Rancher and the target cluster bot used k3s and mariadb database.

When I switched to a single docker for rancher and a rke cluster for my target. I could add the pipeline.

**Comment by mecsys** [comment] 2020-07-15 17:31
Same issue.

| Useful | Info
| --- | --- |
| Versions | Rancher v2.4.5 UI: v2.4.28 |
| Kubernetes Version in k3s|  v1.18.4+k3s1 |

**Comment by mecsys** [comment] 2020-07-15 17:34
Same issue.

| Useful | Info
| --- | --- |
| Versions | Rancher v2.4.5 UI: v2.4.28 |
| Kubernetes Version in k3s|  v1.18.4+k3s1 |

**Comment by gicappa** [comment] 2020-07-22 12:35
I have two rancher installations: the one starting on a single docker instance (as per the getting started) is adding the pipelines with no issues, while the one installed on top of rke is giving me this error. 
I tried to inspect the request and I see a request to verify-auth with clientId and clientSecrets that are empty but I don't know if this is relevant or expected

**Comment by abhi1693** [comment] 2020-07-28 09:00
@yasker @maggieliu Any ETA on this issue? It's been nearly two months and no action on this. Can this be added to milestone v2.4.5 so that we can set up our pipelines via Github repositories?

**Comment by bmdepesa** [comment] 2020-07-29 00:02
Reproduced in v2.4.5 w/ a 1.18.6 custom cluster

- Authenticate when adding your github repo for a pipeline causes error: `failed to decode the config, error: 1 error(s) decoding: * 'ManagedFields[0].Time' expected a map, got 'string'`

**Comment by ItsReddi** [comment] 2020-07-29 08:28
The same issue appears with a bitbucket pipeline, while authenticating with bitbucket:
`TestAndApply Error
failed to decode the config, error: 1 error(s) decoding: * 'ManagedFields[0].Time' expected a map, got 'string'`

**Comment by saubi1993** [comment] 2020-07-31 13:15
The same thing happens when you are setting up bitbucket. Any updates, when this will be fixed. I am kind of stuck here.

**Comment by EckoEdc** [comment] 2020-08-02 18:24
Same issue here 
Rancher v2.4.5, single RKE install

**Comment by ItsReddi** [comment] 2020-08-06 09:52
@maggieliu any chance to move that to 2.4.6 milestone, since the pull request seems allready to be approved?

**Comment by bmdepesa** [comment] 2020-08-11 19:00
rancher/rancher:v2.4-head f32f5d1d2
rancher/rancher:master-head 28ea6d4b1

* Created an HA installation for both v2.4-head, master-head
* Created a single-node install for v2.4-head
* Created a cluster in each Rancher server
* Authorized pipeline repositories through GitHub and was able to see all repos listed without errors

**Closed by bmdepesa** 2020-08-11 19:00 UTC
Labels: [zube]: To Test
