### ISSUE TITLE
Latest Server Chart to Support cert-manager 0.12.0 is broken

### ISSUE THREAD

**Issue by ekristen** [rancher/rancher#24770] opened 2019-12-26 19:54 UTC
**What kind of request is this (question/bug/enhancement/feature request):** bug

Based on the ingress definition in master and in release/v2.3 the defined cert-manager is an issuer not a cluster issuer 

https://github.com/rancher/rancher/blob/master/chart/templates/ingress.yaml#L20-L21

However the letsencrypt definition it creates a ClusterIssuer for 0.12.0 and Issuer for 0.11.0 and lower.

https://github.com/rancher/rancher/blob/master/chart/templates/issuer-letsEncrypt.yaml#L4-L6

Either the ingress needs to be updated to use the cluster issuer for 0.12.0 or the issuer creation needs to be fixed.

**Comment by ekristen** [comment] 2019-12-26 20:25
Based on testing, updating the ingress to use the cluster issuer that it creates when using 0.12.0 gets the process further along. I have still yet to receive a certificate. 

https://github.com/rancher/rancher/blob/master/chart/templates/ingress.yaml#L21

This should be changed to 

`certmanager.io/cluster-issuer: rancher`

**Comment by JannikZed** [comment] 2019-12-31 14:49
I think we are stuck because of this issue now .. our Rancher node does not have a valid certificate, as the old cert-manager is no longer working, but we also can't upgrade as we only get this:
`Error: UPGRADE FAILED: unable to recognize "": no matches for kind "Issuer" in version "certmanager.k8s.io/v1alpha1"`
seems like it still works somewhere with the old api certmanager.k8s.io ... 
How to proceed?? It's our production cluster ..

**Comment by cloudnautique** [comment] 2019-12-31 17:15
@JannikZed, can you downgrade cert manager to version 0.9.1 and use the chart that way? The chart updates for using >=0.11.x APIs are not available in the 2.3.x line. 

Our updated instructions accidentally got mixed in with our 2.4.0-preview1 docs. We are reverting those docs as well.

**Comment by cloudnautique** [comment] 2019-12-31 18:05
We are going to go back to using the `Issuer` type across the board for everything. Keeping the chart logic simple vs. adding a new path for testing etc exceeds the limited benefit of being able to have certs issued in other namespaces within the cluster. Rancher best practice is to use a cluster dedicated to the Rancher server workloads.

**Comment by JannikZed** [comment] 2020-01-02 12:52
@cloudnautique yes, that worked out now. We went back to version 9 of cert-manager, but it took me some hours .. 
We indeed have a dedicated cluster just for Rancher.

**Comment by jiaqiluo** [comment] 2020-01-02 21:20
The bug is reproduced in v2.3.4-rc5, Rancher is installed in HA mode with cert-manager 0.12 and the option `--set ingress.tls.source=letsEncrypt`

Results:
- the workload `cattle-cluster-agent` and `cattle-node-agent` in the local cluster cannot be active, the logs show the error
```
x509: certificate is valid for ingress.local, not my-test-domain.com
```
<img width="1437" alt="Screen Shot 2020-01-02 at 2 13 28 PM" src="https://user-images.githubusercontent.com/6218999/71693851-bc783800-2d6a-11ea-97e2-c6c557ae6fdf.png">

- some certificates are not issued properly
<img width="1450" alt="Screen Shot 2020-01-02 at 2 17 51 PM" src="https://user-images.githubusercontent.com/6218999/71693861-c4d07300-2d6a-11ea-82cd-8448782742e1.png">

**Comment by cloudnautique** [comment] 2020-01-03 04:25
@JannikZed, glad it was sorted out, sorry about the doc mishap. The second comment was for our internal resolution, didn't mean to imply you were running incorrectly.

**Comment by alekc** [comment] 2020-01-03 17:36
Any idea when (and if) the merge request above is going to be present  on `rancher-stable/rancher`?
Thx

**Comment by jiaqiluo** [comment] 2020-01-03 18:52
@alekc It will go to the coming release Rancher v2.3.4, but v2.3.4 may not be marked as stable immediately.

**Comment by cloudnautique** [comment] 2020-01-03 19:26
@alekc chart versions will be available in the next round of patch updates in the next few weeks.

**Comment by jiaqiluo** [comment] 2020-01-03 21:36
Tested in Rancher v2.3.4-rc7 HA fresh install with letsEncrypt, and it works as expected.

**Comment by jiaqiluo** [comment] 2020-01-03 22:33
Upgrading Rancher from v2.3.3 to v2.3.4-rc7 succeeds. 

Steps:
- install Rancher v2.3.3 in HA mode with letsEncrypt
- when opening Rancher UI in chrome, there is no warning for insecure connection & unknown certs 
- check certifications are created properly 
- add a cluster (DO in my case)
- check the cluster working properly (launching kubectl from UI, check pods' logs)
- upgrade cert-manager to v0.12 and Rancher to v2.3.4-rc7 (still with LetsEncrypt enabled). Here is the instruction: https://github.com/rancher/rancher/issues/23424#issuecomment-570691732

after upgrading
- when opening Rancher UI in chrome, there is no warning for insecure connection & unknown certs 
- check certifications are created properly 
- check the existing cluster working properly (launching kubectl from UI, check pods' logs)
- add a new cluster
- check the new cluster working properly (launching kubectl from UI, check pods' logs)

**Closed** 2020-01-03 23:19 UTC
Labels: [zube]: To Test, team/eio

**Comment by ainiml** [comment] 2020-03-02 17:32
I believe this is happening for me on `v2.3.5`

**Comment by adeleglise** [comment] 2020-04-02 09:32
Same for me here. I upgraded cert-manager to 0.11, then to 0.14.1. Now I can't upgrade rancher release.

**Comment by chuegel** [comment] 2020-04-17 07:11
same issue here with cert-manager 0.12.

**Comment by ekristen** [comment] 2020-04-17 15:40
IIRC you will need to remove the existing ingress definition at a minimum during this process for Rancher so that after you've upgraded your cert-manager and then upgrade rancher the ingress can properly be installed. Otherwise the ingress definitions conflict.

**Comment by rawmind0** [comment] 2020-04-17 15:51
To proper upgrade Rancher and cert-manager to 0.11.0 or above, follow [OPTION B: REINSTALLING RANCHER AND CERT-MANAGER](https://rancher.com/docs/rancher/v2.x/en/upgrades/upgrades/ha/#c-upgrade-rancher)
