### ISSUE TITLE
Load balancers catching outgoing connections since update to 1.2.2

### ISSUE THREAD

**Issue by MaxNoe** [rancher/rancher#7358] opened 2017-01-09 17:06 UTC
**Rancher Versions:**
Server: v1.2.2
healthcheck: v0.2.0
ipsec: 0.0.2
network-services: v0.0.8
scheduler: v0.2.0

**Docker Version:**
1.12.1
**OS and where are the hosts located? (cloud, bare metal, etc):**

4 Ubuntu 16.04 bare metal servers

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
One rancher-server, internal DB
**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle
**Steps to Reproduce:**

We have the following setup:
4 Ubuntu 16.04 servers in a private network, 1 server is a gateway machine to another local network with internet access. On this server, we have load balancers running to distribute traffic to the correct services on the agents.

**Results:** 

Until we updated to the latest version, this gateway setup was not a problem, everything worked fine. But after the update, all http and https requests from the worker nodes are getting redirected to the load balancers instead to to the network with internet access.

e. g. on one of the internal nodes:
```
curl www.google.com
````
Results in a request to our load balancer if the load balancer is running, but goes through if it is stopped.

**Expected:**

The load balancers should not listen to outgoing traffic

**Comment by toughIQ** [comment] 2017-01-16 17:19
I am not sure, if I am dealing with the same problem here.
I have a SSL LB in front of Portus&Registry to route traffic according to URL (portus.mydomain.com & registry.mydomain.com)
Access  (`curl -I https://portus.mydomain.com`) from outside any container within this instance works fine.
But same `curl `from within a container times out. Any URL not served from this RancherInstance/Servers works fine.

**Comment by bixel** [comment] 2017-01-17 11:32
I think we found a solution for this. Looking at `iptables -S -t nat`, it seems that the rancher-agent (and its "sub-containers") applies several firewall rules in the nat table to implement the loadbalancer traffic forwarding. Therefore, outgoing traffic on the standard http/https ports ended up in the loadbalancers and never actually leaves the docker stack. Therefore wee edited the nat table, accepting outgoing traffic, which is not origination from within the docker subnets.

**Comment by toughIQ** [comment] 2017-01-17 13:00
@bixel does this solution mean, that you have to edit the ruleset every time something is changed in the rancher stack? Or did you mean a change in the rancher code itself?

**Comment by toughIQ** [comment] 2017-01-17 17:04
@deniseschannon is this issue already known or handled somewhere else? 
Since there is no assignment, label or milestone yet.
Thanks

**Comment by bixel** [comment] 2017-01-17 18:57
@toughIQ A single rule before the rancher-specific rules (CATTLE* blabla, if I remember correctly) was enough.

**Comment by toughIQ** [comment] 2017-02-06 11:06
I changed these 2 settings and now my problem is gone:
To resolve this Warning I add those two lines info my **/etc/sysctl.conf**

```
net.bridge.bridge-nf-call-ip6tables = 1
net.bridge.bridge-nf-call-iptables = 1
```

See: https://github.com/docker/docker/issues/24809

**Comment by mithrandi** [comment] 2017-02-09 06:48
I think is a duplicate of #7349.

**Comment by deniseschannon** [comment] 2018-08-23 05:35
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.

**Closed by deniseschannon** 2018-08-23 05:35 UTC
Labels: area/networking, status/autoclosed
