### ISSUE TITLE
Support upgrading only when service image has changed

### ISSUE THREAD

**Issue by dj-hedgehog** [rancher/rancher#5516] opened 2016-07-22 15:52 UTC
**Rancher Version:** v1.10dev5

**Docker Version:** 1.11.2

**OS and where are the hosts located? (cloud, bare metal, etc):** bare metal

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)** Cattle

**Steps to Reproduce:**

My CI server build a new Docker image, pushes it to my private registry and then tries to upgrade a service automatically using both commands below.
The problem is despite having `--pull` it doesn't actually pull the latest image.
I have to upgrade it with the Web UI, then it is pulled automatically.

```
rancher-compose --url "http://myrancher.com:8080/" --access-key $RANCHER_ACCESS_KEY --secret-key $RANCHER_SECRET_KEY --project-name test --file ci/docker-compose.yml --verbose up --pull -d --upgrade backend
rancher-compose --url "http://myrancher.com:8080/" --access-key $RANCHER_ACCESS_KEY --secret-key $RANCHER_SECRET_KEY --project-name test --file ci/docker-compose.yml up -d --upgrade --confirm-upgrade
```

**Results:** Upgrade is executed without pulling the latest image

**Expected:** Uprade is executed and the latest image is pulled.

This is the log of the first command above:

> rancher-compose --url "http://myrancher.com:8080/" --access-key $RANCHER_ACCESS_KEY --secret-key $RANCHER_SECRET_KEY --verbose up --pull -d --upgrade apidocs
> time="2016-07-25T15:55:55Z" level=debug msg="Environment Context from file : map[]" 
> time="2016-07-25T15:55:55Z" level=debug msg="Opening compose files: docker-compose.yml" 
> time="2016-07-25T15:55:55Z" level=debug msg="[0/1] [apidocs]: Adding " 
> time="2016-07-25T15:55:55Z" level=debug msg="Opening rancher-compose file: /builds/myproject/api-docs/rancher-compose.yml" 
> time="2016-07-25T15:55:55Z" level=debug msg="Not found: /builds/myproject/api-docs/rancher-compose.yml" 
> time="2016-07-25T15:55:55Z" level=debug msg="Looking for stack stack-test" 
> time="2016-07-25T15:55:55Z" level=debug msg="Found stack: stack-test(1e256)" 
> time="2016-07-25T15:55:55Z" level=debug msg="Launching action for apidocs" 
> time="2016-07-25T15:55:55Z" level=debug msg="Project [stack-test]: Creating project " 
> time="2016-07-25T15:55:55Z" level=debug msg="[0/1] [apidocs]: Creating " 
> time="2016-07-25T15:55:55Z" level=debug msg="Finding service apidocs" 
> time="2016-07-25T15:55:55Z" level=debug msg="Found service apidocs" 
> time="2016-07-25T15:55:56Z" level=debug msg="[0/1] [apidocs]: Created " 
> time="2016-07-25T15:55:56Z" level=debug msg="Project [stack-test]: Project created " 
> time="2016-07-25T15:55:56Z" level=debug msg="Launching action for apidocs" 
> time="2016-07-25T15:55:56Z" level=debug msg="Project [stack-test]: Starting project " 
> time="2016-07-25T15:55:56Z" level=info msg="[0/1] [apidocs]: Starting " 
> time="2016-07-25T15:55:56Z" level=debug msg="Finding service apidocs" 
> time="2016-07-25T15:55:56Z" level=debug msg="Found service apidocs" 
> time="2016-07-25T15:55:56Z" level=debug msg="Comparing hashes for apidocs: old: digest.ServiceHash{Service:\"819e11c1cc0777b573a4cf1eb71328fc7dc0c569\", LaunchConfig:\"9becb33e1da4807a05ae287eb7ca8cadc63f6d88\", SecondaryLaunchConfigs:map[string]string{}} new: digest.ServiceHash{Service:\"819e11c1cc0777b573a4cf1eb71328fc7dc0c569\", LaunchConfig:\"9becb33e1da4807a05ae287eb7ca8cadc63f6d88\", SecondaryLaunchConfigs:map[string]string(nil)}" 
> time="2016-07-25T15:55:56Z" level=info msg="[1/1] [apidocs]: Started " 
> time="2016-07-25T15:55:56Z" level=debug msg="Project [stack-test]: Project started "

**Comment by dj-hedgehog** [comment] 2016-07-25 17:11
I added the log output of the command involving `--pull` to the issue description.

**Comment by dj-hedgehog** [comment] 2016-07-27 13:52
*bump* Can you tell me more about this? Am I using it wrong or could this be a bug?

**Comment by deniseschannon** [comment] 2016-07-27 15:53
You are using it correctly, but I haven't had a chance to test it out myself to see if it's a bug.

**Comment by sjulean-elan** [comment] 2016-08-05 14:57
Confirmed, and reproduced on Cattle (with both Docker 1.11.2 and 1.12.0) and rancher:latest.

**Steps to reproduce:**
https://gist.github.com/sjulean-elan/4c45e0ff602badb712d523f1068e0b40

Use a private registry to reproduce: `export PRIVATE_REPO=myrepo:5000`

The `reproduce-bug.sh` script builds and pushes a new image, then runs `rancher-compose up --upgrade --pull`; it repeats this 3 times. Only the first image push results in an actual upgrade.

Setting `io.rancher.container.pull_image: always` does nothing (as expected, it only works if the container is actually selected to be upgraded).

**Results:** Hello, version 1!
**Expected:** Hello, version 3! (well, actually, the script should stop after the second attempt, since it doesn't confirm the upgrade)

*Workaround*: use `--force-upgrade`. However, this has two other issues:
- the `rancher-compose` user needs to implement an external way to detect image changes, to know when to force the upgrade;
- there is no way to force the upgrade of a single service; the entire stack must be upgraded even if a single service was modified. (This is a showstopper for us.)

**Comment by sjulean-elan** [comment] 2016-08-06 17:21
Here's how `rancher-compose` appears to behave (from my limited understanding of [`rancher/service.go`](https://github.com/rancher/rancher-compose/blob/master/rancher/service.go#L113)):

- hashes the current service definition;
- checks whether it should upgrade by comparing the local hash with the live hash;
- pulls the image;
- performs the upgrade.

A possible fix could be something like:
- unconditionally pull the image remotely if `--pull` was specified;
- obtain the current image SHA (that was just pulled) and incorporate it in the **local** hash;
- compare this hash to the Rancher-side `io.rancher.service.hash`, which would have incorporated the image SHA at the time of its last upgrade.

There might be a bootstrap issue here at first run, since a Docker host would be required to pull the image, but scheduling might not be done at this point. This may mean that the initial service hash could only be calculated *after* scheduling a service for the first time. Maybe it's already implemented like this, I didn't look into it.

It could also be possible to get the image SHA straight from a registry. I think it'd be good to avoid assuming access to the registry from the `rancher-compose` CLI, so if this were to be done, the CLI would probably ask Rancher to check the registry for the latest image SHA.

*Caveat emptor*: I don't have any experience with any of the Rancher code, and this looks like a non-trivial issue. However, the issue doesn't seem to reproduce with plain `docker-compose`, which appears to pull before deciding whether to upgrade.

**Comment by joshwget** [comment] 2016-10-05 01:06
@dj-hedgehog  I'd say that using `--force-upgrade` is the proper solution here rather than a workaround.

@sjulean-elan Like Docker Compose, Rancher Compose tracks what needs to be upgraded based on changes to configuration rather than changes to images. I'm a little hesitant to incorporate the current image into the service hash (what we use to decide whether or not to upgrade). This feels like it might be out of scope for Rancher Compose and it introduces a fair amount of complexity. I think what you're looking for is basically a feature request for upgrading a service _only_ if the corresponding image has changed.

Also, it is possible to force an upgrade for only certain services in a stack. Just call `up --force-upgrade` with only certain services as arguments.

**Comment by sjulean-elan** [comment] 2016-10-05 08:05
@joshwget Agreed, the `--force-upgrade` approach with only certain services as arguments can work.

If you ask me, it's still a workaround, because to automate this you need to select _which_ services to upgrade. If this is out of scope for Rancher Compose, it follows that it must be left to its user as a task. Furthermore, you need to use the Rancher API to find out whether you need to upgrade or not. Since this involves talking to the Rancher API to get the currently running images, it appears to me that it could actually be in the scope of `rancher-compose` after all.

Since this has a workaround, it could be either an implementation bug _or_ a feature request plus a documentation bug, depending on how you look at it. If you believe that it's a separate feature, I think the workaround should at least be documented.

**Comment by briceruzand** [comment] 2016-10-07 12:05
Hi,
I face to the same trouble in my continuous integration platform based on rancher. (a git push can change one or several image on our private docker repository).

Before using rancher, we use `docker-compose`, to manage full stack deployment and it work's well (on stack upgrade, only pulled images were deploy), but there was no multi host management.

For now, with rancher I use the `--force-upgrade` workaround but it always upgrade every containers on stack upgrade. I was hopping that fix for  rancher Release 1.2.0 :disappointed_relieved:  .

If think it is rancher (cli or compose) responsibility to known what container needs to be upgraded when your upgrade a full stack.

>  I'm a little hesitant to incorporate the current image into the service hash (what we use to decide whether or not to upgrade)

@joshwget I think you should, everything can be automated more easily.

Thx.

**Comment by joshwget** [comment] 2016-10-13 20:55
I definitely agree this would be a useful feature, but I don't think modifying services hashes is the right way to go about this. My current thought is to add a new type of upgrade to the CLI to support this, although we'll still have to think about this issue a little more.

**Comment by fokoenecke** [comment] 2017-05-26 13:42
This feature would be really useful for CI/CD environments. The easiest way to use it might be an additional flag on the `up` command, so that you could decide if your services should be upgraded on compose file changes or on new images.

Since many Docker workflows involve tagging the images multiple times (:1.2.3, :1.2, :1) this would make the versioning of rancher stacks really elegant. You could just define the major versions in the `rancher-compose.yml` and let `rancher up --upgrade-on-new-image` handle the rest.

:+1:

**Comment by mikaoelitiana** [comment] 2017-06-28 08:29
I am using the `--force-upgrade` option but I get issue with linked services after this. I have a database linked as `db` to my `web` service and I only upgrade `web` but after that, I get an error `28/06/2017 11:29:1008:29:10.269 [error] Postgrex.Protocol (#PID<0.1688.0>) failed to connect: ** (DBConnection.ConnectionError) tcp connect (db:5432): connection refused - :econnrefused
`

**Comment by ampedandwired** [comment] 2017-09-06 00:37
This issue is incredibly frustrating for us in our CD pipeline. `--force-upgrade` isn't a good workaround, as it recreates the container every time regardless of whether the image has changed or not. A flag like @fokoenecke suggests (`--upgrade-on-new-image` or maybe `--force-pull` to match `--force-upgrade`) would allow something like this to be implemented without changing semantics of existing flags.

**Comment by sokratisg** [comment] 2017-10-05 17:59
Same issue in our CI/CD. We have a postgres:9.5 service in one of our stacks and it pointlessly gets upgraded each time we run a rancher force-upgrade, even when the image hasn’t changed. As you may understand that causes unecessary downtime to the web service which depends on the db service.

**Comment by deniseschannon** [comment] 2018-08-22 05:01
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.

**Closed by deniseschannon** 2018-08-22 05:01 UTC
Labels: area/cli, area/rancher-compose, kind/enhancement, status/autoclosed
