### ISSUE TITLE
Add host to infrastructure fails to pick up running agent

### ISSUE THREAD

**Issue by OldManNiko** [rancher/rancher#3454] opened 2016-01-28 23:18 UTC
When adding a host as infrastructure, I cannot get the rancher server to proceed properly.  Here's the logs on the agent container.

INFO: Starting agent for 4BFCFAF6FD0998A089E7
INFO: Access Key: 4BFCFAF6FD0998A089E7
INFO: Config URL: http://ucm-rancher.qualcomm.com:8080/v1
INFO: Storage URL: http://ucm-rancher.qualcomm.com:8080/v1
INFO: API URL: http://ucm-rancher.qualcomm.com:8080/v1
INFO: IP: 10.62.22.37
INFO: Port:
INFO: Required Image: rancher/agent:v0.8.2
INFO: Current Image: rancher/agent:v0.8.2
INFO: Using image rancher/agent:v0.8.2
INFO: Downloading agent http://ucm-rancher.qualcomm.com:8080/v1/configcontent/configscripts
{"id":"0017c866-f56a-4237-bc47-5ca8aa40ac4d","type":"error","links":{},"actions":{},"status":401,"code":"Unauthorized","message":"Unauthorized","detail":null}
gzip: stdin: not in gzip format
tar: Child returned status 1
tar: Error is not recoverable: exiting now

**Comment by CBR09** [comment] 2016-01-29 07:30
Sometime, I got this issue. I usually remove all rancher-agent containers (both stopped and starting container), and re-add host.

**Comment by deniseschannon** [comment] 2016-02-01 19:34
Can you first try `rm -rf /var/lib/rancher/state; docker rm -fv rancher-agent; docker rm -fv rancher-agent-state` and then try to add?

**Comment by deniseschannon** [comment] 2016-02-09 20:40
Duplicate of https://github.com/rancher/rancher/issues/1370

Please add additional comments to that issue.

**Closed by deniseschannon** 2016-02-09 20:40 UTC
