### ISSUE TITLE
Add annotation to all old feature charts

### ISSUE THREAD

**Issue by cbron** [rancher/rancher#30542] opened 2020-12-17 23:16 UTC
We need to add the `catalog.cattle.io/os=linux` os annotation to all old charts so that UI shows them correctly. 
Likely solution: untar -> add annotation -> tar -> replace -> reindex

See original issue for more info: https://github.com/rancher/rancher/issues/30450

**Comment by cbron** [comment] 2020-12-18 17:49
This is actually going to go out out-of-band, as we are updating the main (release) branch when we merge PR.

@jiaqiluo To QA this we will setup a fork branch, and then you can switch over to that branch to simulate this release. We'll do that before we actually merge the PR. We'll need to test an existing 2.5.3 cluster getting it while running some of the features, and also a fresh 2.5.4 (head) cluster having it and installing fresh.

**Comment by cbron** [comment] 2020-12-18 22:11
PR is ready for test. Won't merge until actual release either way.

**Comment by jiaqiluo** [comment] 2020-12-22 01:58
The following git repo and branches of the PRs are used to validate the fix
```
repo: https://github.com/thedadams/charts
branch 1: add-linux-annotation-2.5 <-- the PR goes to dev-v2.5 
branch 2: add-linux-annotation     <-- the PR goes to main
```

Checks  | v2.5.3 | v2.5-head bb69b0 |
------- | ------ | ---------------- |
branch  |add-linux-annotation| add-linux-annotation-2.5
on Linux cluster, see `Linux only` on all versions of all charts in the dashboard UI | N/A | PASS 
on Windows cluster, see no chart in the dashboard UI | N/A | PASS 
install the latest versions of all charts and see the annotation `catalog.cattle.io/os=linux` when viewing the app in YAML | PASS | PASS
install an old version then upgrade to a newer version| PASS | PASS
install the old version from rancher's release branch -> change the catalog to use the above repo & branch -> upgrade the app to a newer version ==> Results: upgrade succeeds and new annotation `catalog.cattle.io/os=linux` is applied | PASS | PASS
install the old version from rancher's release branch -> change the catalog to use the above repo & branch -> upgrade the app with value changed not the chart version ==> Results: upgrade succeeds, version is not changed, and new annotation `catalog.cattle.io/os=linux` is applied| PASS | PASS

**Comment by jiaqiluo** [comment] 2020-12-22 02:04
@cbron  @sangeethah  

Keep this issue open for now because we see the following behavior:

The catalog `Rancher` is a built-in catalog, I can change its URL and branch to the testing repo, but the new charts never show up in the UI even after refreshing the catalog manually.
This does not happen to the catalog created by me. 

<img width="1611" alt="Screen Shot 2020-12-21 at 7 00 10 PM" src="https://user-images.githubusercontent.com/6218999/102839900-d321ff80-43be-11eb-899e-48ec6ed2e9e6.png">

**Comment by sangeethah** [comment] 2020-12-22 03:09
@cbron Reopening to follow up on the behavior noted here - https://github.com/rancher/rancher/issues/30542#issuecomment-749295531

**Comment by jiaqiluo** [comment] 2020-12-22 19:09
On an existing `v2.5-head` bb69b0 HA setup, the catalog `Rancher` upgrades charts automatically after [the PR](https://github.com/rancher/charts/pull/901) is merged. 

The following are validated:

1. no charts show in the dashboard in the Windows cluster 
![image](https://user-images.githubusercontent.com/6218999/102921623-e928d200-4449-11eb-976c-6e29a5b96706.png)

2. all versions of all charts show `Linux-only`. Take Istio as an example 
![image](https://user-images.githubusercontent.com/6218999/102921808-3f961080-444a-11eb-8a80-e627632ca0cd.png)

3. "Upgrade" the existing app to the **same** chart version ==> Results: the upgrade succeeds and the new annotation `catalog.cattle.io/os=linux`is applied 
4. Upgrade the existing app to the latest chart version ==> Results: the upgrade succeeds and the new annotation `catalog.cattle.io/os=linux`is applied

**Closed** 2020-12-23 00:14 UTC
Labels: [zube]: QA Working

**Comment by mecseid** [comment] 2021-01-07 23:35
After upgrading to v2.5.4 from v2.5.3, I got the following error in web browser console:
```
TypeError: Cannot read property 'catalog.cattle.io/os' of undefined
    at install.vue:424
    at Array.forEach (<anonymous>)
    at filteredVersions (install.vue:417)
    at _n.get (vue.runtime.esm.js:4479)
    at _n.evaluate (vue.runtime.esm.js:4584)
    at f.filteredVersions (vue.runtime.esm.js:4836)
    at f.r (install.vue?5fc2:1)
    at f.t._render (vue.runtime.esm.js:3548)
    at f.r (vue.runtime.esm.js:4066)
    at _n.get (vue.runtime.esm.js:4479)
```

The chart, which I wanted to upgrade, is migrated from Helm 2 to Helm 3.

I tested with a simple Helm 3 chart with CLI installation, and I got the same error.

**Comment by jiaqiluo** [comment] 2021-01-08 00:23
hi @mecseid Do you see this error in the (old) cluster management UI or the (new) cluster explorer UI

On which page do you see this error? Can you provide me any screenshots if possible?

**Comment by jiaqiluo** [comment] 2021-01-08 00:54
I tried the following and did not hit the error. Do you use any specific repo or charts? 

Here is what I did:
- run rancher:v2.5.3 single-install
- add a cluster with ec2 
- go to cluster explorer
- install monitoring v2 (9.4.200) chart from the built-in repo
- upgrade rancher from v2.5.3 to v2.5.4

Results:
- I can go to the cluster explore to check browser charts
- some of the charts will show `Linux only` which is a reflection of the new annotation `catalog.cattle.io/os` on the charts
- I can also upgrade monitoring v2 to the latest chart (9.4.202)

**Comment by jiaqiluo** [comment] 2021-01-08 00:59
Hi @mecseid Can you refresh your browser or clear the history/cache? It is possible that the new UI files do not take effect because of the local cache.

**Comment by mecseid** [comment] 2021-01-08 08:37
Hi @jiaqiluo

We have a chartmuseum hosted Helm repository, which contains v1 and v2 charts, and I added some other popular chart repositories on the new UI. (bitnami, banzaicloud, helm-stable-charts, etc).

On the Installed Apps page, if I want to upgrade an installation (mailhog as a simple example), I get the following error:
![image](https://user-images.githubusercontent.com/6381828/103991885-9f532200-5193-11eb-83b9-8732b46b054e.png)

On the charts page, I run into the same error:
![image](https://user-images.githubusercontent.com/6381828/103992332-42a43700-5194-11eb-91af-cf51f64fc2f9.png)

So, at the moment I can't use and navigate on the "Apps & Marketplace" page, because its default page is "Charts".

**Comment by jiaqiluo** [comment] 2021-01-08 16:50
The bug is reproduced on v2.5.4

Steps:
- add the following repo 
```
https://github.com/banzaicloud/banzai-charts	
master
```
<img width="958" alt="Screen Shot 2021-01-08 at 9 42 23 AM" src="https://user-images.githubusercontent.com/6218999/104041757-be06e800-5196-11eb-9159-2c1898e80234.png">

Results:
- go to the charts page
![image](https://user-images.githubusercontent.com/6218999/104041824-d840c600-5196-11eb-96ef-d55a0d09478f.png)

**Comment by cbron** [comment] 2021-01-08 17:32
@jiaqiluo can you make separate bug issue for that

**Comment by jiaqiluo** [comment] 2021-01-08 18:36
@cbron Here is the new issue to track it: https://github.com/rancher/rancher/issues/30749

**Comment by jiaqiluo** [comment] 2021-01-09 00:00
## Before the fix on charts is merged 
### On a single-install v2.5.3 setup
- add a cluster
- notice that all rancher charts do NOT have `Linux-only`  
![image](https://user-images.githubusercontent.com/6218999/104065956-d5a59700-51bd-11eb-8231-3ff940c0a551.png)
- install monitoring v2(chart v9.4.200)in the dashboard

### On a single-install v2.5.4 setup
- add a cluster
- notice that only some of the rancher charts have `Linux-only`  
![image](https://user-images.githubusercontent.com/6218999/104066098-0c7bad00-51be-11eb-9ca8-fb41a0dce203.png)
- install monitoring v2(chart v9.4.200)in the dashboard

## After the fix is merged 
### On the above-mentioned v2.5.3 setup:
- upgrade it to v2.5.4
- all versions of all charts in the `Rancher` repo show `Linux-only` 
![image](https://user-images.githubusercontent.com/6218999/104076280-e44a7900-51d2-11eb-93c5-65e40221e025.png)
- and monitoring can be upgraded to 9.4.202

### On the above-mentioned v2.5.4 setup:
- all versions of all charts in the `Rancher` repo show `Linux-only` 
![image](https://user-images.githubusercontent.com/6218999/104076000-d7795580-51d1-11eb-89cd-bfd4b2adbd85.png)
- and monitoring can be upgraded to 9.4.202
