### ISSUE TITLE
Can't login after adding user/org using GitHub Enterprise as access control

### ISSUE THREAD

**Issue by mikygit** [rancher/rancher#10434] opened 2017-11-30 14:09 UTC
**Rancher versions:**
rancher/server: v1.6.11
rancher/agent: v1.2.7

**Infrastructure Stack versions:**
healthcheck: NA
ipsec: NA
network-services: NA
scheduler: NA
kubernetes (if applicable): NA

**Docker version: (`docker version`,`docker info` preferred)**
Client:
 Version:      17.09.0-ce
 API version:  1.32
 Go version:   go1.8.3
 Git commit:   afdb6d4
 Built:        Tue Sep 26 22:41:23 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.09.0-ce
 API version:  1.32 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   afdb6d4
 Built:        Tue Sep 26 22:42:49 2017
 OS/Arch:      linux/amd64
 Experimental: false

Containers: 50
 Running: 48
 Paused: 0
 Stopped: 2
Images: 589
Server Version: 17.09.0-ce
Storage Driver: zfs
 Zpool: storage
 Zpool Health: ONLINE
 Parent Dataset: storage
 Space Used By Parent: 139776
 Space Available: 1497869704704
 Parent Quota: no
 Compression: off
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local rancher-nfs
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: active
 NodeID: 4tsma582cmzkmzyc87arz9fcw
 Is Manager: true
 ClusterID: rwvwo3yu9u3xajch35qt5ba52
 Managers: 1
 Nodes: 1
 Orchestration:
  Task History Retention Limit: 5
 Raft:
  Snapshot Interval: 10000
  Number of Old Snapshots to Retain: 0
  Heartbeat Tick: 1
  Election Tick: 3
 Dispatcher:
  Heartbeat Period: 5 seconds
 CA Configuration:
  Expiry Duration: 3 months
  Force Rotate: 0
 Autolock Managers: false
 Root Rotation In Progress: false
 Node Address: 10.57.16.61
 Manager Addresses:
  10.57.16.61:2377
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 06b9cb35161009dcb7123345749fef02f7cea8e0
runc version: 3f2f8b84a77f73d38244dd690525642a72156c64
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 3.10.0-693.5.2.el7.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
CPUs: 80
Total Memory: 503.7GiB
Name: XXXX
ID: XXXX
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Http Proxy: http://10.57.0.12:3128/
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"

3.10.0-693.5.2.el7.x86_64
**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
Bare-metal

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
single node rancher

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle

**Steps to Reproduce:**
* Install rancher and rancher agent
* Set-up Github entreprise authentification: it works
* Log out and log in again: it works
* Go back to Github entreprise authentification settings and ADD organization as possible users : log out and log in again --> **It fails**
**Results:**
2017-11-30 13:35:10,610 ERROR [:] [] [] [] [1020391880-4413] [.a.a.i.e.ExternalServiceAuthProvider] Got error from Auth service. statusCode: 500, message: Request failed, got status code: 404. Response: {"error":"Not Found"}
time="2017-11-30T13:36:09Z" level=error msg="Github getAccessToken: GET url http://xxx.xxx.com/login/oauth/access_token received error from github, err: Request failed, got status code: 404. Response: {\"error\":\"Not Found\"}"
time="2017-11-30T13:36:09Z" level=error msg="Error generating accessToken from github Request failed, got status code: 404. Response: {\"error\":\"Not Found\"}"
time="2017-11-30T13:36:09Z" level=error msg="GetToken failed with error: Request failed, got status code: 404. Response: {\"error\":\"Not Found\"}"

Doing a curl -v http://xxx.xxx.com/login/oauth/access_token from inside the rancher container =:
> Hostname was NOT found in DNS cache
>   Trying 10.112.71.249...
> Connected to xxx.xxx.com (10.112.71.249) port 80 (#0)
> GET /login/oauth/access_token HTTP/1.1
> User-Agent: curl/7.35.0
> Host: xxx.xxx.com
> Accept: */*
>
> HTTP/1.1 301 Moved Permanently
> Content-length: 0
> Location: https://xxx.xxx.com/login/oauth/access_token
>
> Connection #0 to host xxx.xxx.com left intact

**Comment by superseb** [comment] 2017-11-30 22:29
Did you configure it using a `https` URL and got switched to a `http` URL?

**Comment by mikygit** [comment] 2017-11-30 22:32
No I didn't. Configured https all the way

**Comment by superseb** [comment] 2017-11-30 22:34
I understand, but the logging is showing `http` URL, correct? So it gets changed after adding user/org?

**Comment by mikygit** [comment] 2017-11-30 22:39
You mean the http in the error log:
[.a.a.i.e.ExternalServiceAuthProvider] Got error from Auth service. statusCode: 500, message: Request failed, got status code: 404. Response: {"error":"Not Found"}
time="2017-11-30T13:36:09Z" level=error msg="Github getAccessToken: GET url http://xxx.xxx.com/login/oauth/access_token received error? 
If so, I have no idea why it is not https. 
I configured gît Auth and did checked the 'https' checkbox.

**Comment by superseb** [comment] 2017-11-30 22:58
Can you run the following query to the database: `insert into setting (name,value) values ('auth.service.log.level', 'DEBUG');`, do the sequence to trigger the bug and send me the logging? (either attach it on the issue or send it to me on https://slack.rancher.io)

**Comment by mikygit** [comment] 2017-12-01 06:01
Sure... but I have no idea how to do that :-)

**Comment by superseb** [comment] 2017-12-01 08:55
No problem.

```
docker exec -ti container_id bash
mysql cattle
insert into setting (name,value) values ('auth.service.log.level', 'DEBUG');
```

Where `container_id` is the id of the `rancher/server` container. This instantly activates debug logging for the auth service. If you can do all the same steps to reproduce and send me the logging from the `rancher/server` container, that would be great.

**Comment by mikygit** [comment] 2017-12-01 10:20
Ok, I'll do it later and keep you posted. Building stack that take time for the moment.
BTW, if I set the Github auth back again and can not log in, is there a way to hack the system to still be able to log in? Setting some kind of admin rescue credentials for instance?

**Comment by superseb** [comment] 2017-12-07 22:08
No, you can only reset it using http://rancher.com/docs/rancher/v1.6/en/faqs/troubleshooting/#help-i-turned-on-access-controldocsrancherv16enconfigurationaccess-control-and-can-no-longer-access-rancher-how-do-i-reset-rancher-to-disable-access-control

Any luck getting the log?

**Comment by mikygit** [comment] 2017-12-08 07:36
No not yet. Still setting up our cicd environment. Testing a lot.
BTW, is there a way to store/save my stacks somewhere before I crash everything? Something else than exporting manually the compose files? Mounting a folder maybe?
Would resetting rancher loose everything?

**Comment by nathanhruby** [comment] 2017-12-13 20:46
Hi, I'm having the same problem.

I manually added `api.github.scheme` in setting with value `https://` as a debug step and that seems to have no effect (?)

I then unconfigured and reconfigured access control and tested again, things were working (working == login form a separate browser works and I see the default environment page)

Then from the UI for "Access Control" I added a github org from my GHE instance using the dropdown to the "Authorized Users and Organizations" list.  

Watching the network calls in browser dev console, the POST to /v1-auth/config that updates the authorized users list has scheme set to `"http://"` in the gitHubConfig part of the params.  After the POST logins begin to fail, and there are 404 errors in the log.  

With debug enabled I see a 
```
level=info msg="newProvider github"
```
that has some info with settings and then the line 
```
Settings from db for provider github: map[ ...
```
with the settings that match what was supplied in the POST by the frontend.  

It looks like this is sneaking in with the frontend defaulting to the wrong value on POST.

Please let me know if I can provide anything else for you.

**Comment by superseb** [comment] 2017-12-18 14:59
The fix for this should be in v1.6.13. We have `rancher/server:v1.6.13-rc4` which includes this fix. rc's are not for production use, it's used for internal testing. But if you can test if the GitHub Enterprise part is fixed, this would help (just testing the auth, not running anything on it)

**Comment by nathanhruby** [comment] 2017-12-18 19:34
I'm working in a test environment right now which is HIGHLY FORTUITOUS!  Will test this afternoon and let you know.  Thanks for the quick update.

**Comment by nathanhruby** [comment] 2017-12-18 20:09
rc4 works to address this issue.  Disabling Access Control, then re-configuring it to use GHE, then adding another admin once configured yields a functional instance.  Thanks!

**Comment by deniseschannon** [comment] 2017-12-19 05:01
@nathanhruby Thanks for testing with rc4 and letting us know that it works!!

**Closed by deniseschannon** 2017-12-19 05:01 UTC
Labels: area/access-control, area/ui, kind/bug, status/resolved, status/to-test, version/1.6
