### ISSUE TITLE
Adding nodes for packet.net doesn't work

### ISSUE THREAD

**Issue by simon-k8s** [rancher/rancher#11175] opened 2018-01-26 14:34 UTC
**Rancher versions:**
rancher/server:  v2.0.0-alpha12

**Docker version: (`docker version`,`docker info` preferred)**

None I can't create a worker node

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**

Rancher Docker Image Ubuntu

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**

Openstack / KVM

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**

Internal DB 

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**

kubernetes

**Steps to Reproduce:**

I add a cluster. Afterwards I tried to add a node. I am using packet.net. I enter my api key and the projectid. Then I get > Bad Gateway: undefined

**Comment by deniseschannon** [comment] 2018-01-26 15:59
Duplicate of #10888

**Closed by deniseschannon** 2018-01-26 15:59 UTC
