### ISSUE TITLE
UI - "no-access" text for global provider that is presented in Edit GDNS entry is misleading when he is allowed to use the GDNS provider.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#18978] opened 2019-03-17 01:50 UTC
Rancher server version - Build from master - Mar 16

Steps to reproduce the problem:
As user1 (Admin) , Create a DO cluster - mytest1 with following project test1 that `user2` has access to.
Create a GDNS provider.
Create a GDNS entry with project targets as test1, the above created provider and add `user2` as owner.

As user2 , go to `Tools`/`Global DNS Entries` 
Edit the GDNS entry.
"no-access" text for global provider that can still be used is misleading.

<img width="1120" alt="Screen Shot 2019-03-16 at 6 40 10 PM" src="https://user-images.githubusercontent.com/4266958/54484014-13804100-481b-11e9-8fd2-ba74fce37207.png">

Can this text "no-access" be changed to something that indicates that he is not a owner but can still use ? Or in such cases , do we even want to provide this text ?

**Comment by westlywright** [comment] 2019-03-18 17:17
Perhaps the UX for this should be reworked. The only reason that the provider is usable is because the input is a select of all the GDNS providers available to the user including the current provider assigned to the entry being edited.

For example, if this user were to select a different provider they do have access to, save the entry, refresh the page/session, then re-edit, they would not see the inaccessible provider in the list because they have no access to that provider. Additionally if the user visits the providers page they do not see this provider because no access.  

A couple solutions could solve this:

1. exclude the inaccessible provider from the list, show the current provider (only if inaccessible) on its own line with the ability to remove, and the providers select dropdown on the next line. if the user selects a different provider the inaccessible one is removed and small cancel text would appear next to the new static provider text allowing them to cancel changing the provider if they didn't intend to.

2. a text only representation of the provider with the edit icon placed next to it that when clicked shows the provider select excluding the inaccessible provider. again a small cancel button or text could be placed somewhere to allow the user the undo this action without having to the cancel the edit completely.

**Comment by westlywright** [comment] 2019-03-18 17:17
cc @sangeethah @cjellick @alena1108

**Comment by davidnuzik** [comment] 2019-03-19 20:24
Version: Master 2.2 (3/19/19)
Confirmed issue.
Followed the steps to reproduce. Confirmed that we removed the "(no access)" text from the provider.
![image](https://user-images.githubusercontent.com/45179589/54639275-37759980-4a4a-11e9-9ef9-a338db31deb1.png)

Smoke tested. Ensured user2 can still add/remove projects they have access to and save changes, etc.

**Closed by davidnuzik** 2019-03-19 20:24 UTC
Labels: area/ui, kind/bug-qa, status/ready-for-review, status/resolved, status/to-test, team/az, version/2.0
