### ISSUE TITLE
Unable to provision Azure Disk with Azure node driver and azure cloud provider

### ISSUE THREAD

**Issue by fwiedmann** [rancher/rancher#19216] opened 2019-03-27 13:33 UTC
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**

Create a pvc with azure disk storage class set.
pvc deplyoment:
```yaml
kind: PersistentVolumeClaim

apiVersion: v1

metadata:

  name: pvc-test

  namespace: test

  labels:

    app: test

spec:

  accessModes:

    - "ReadWriteOnce"

  resources:

    requests:

      storage: "100Gi"
```

**Result:**
kubectl get pvc:
NAME              STATUS    VOLUME   CAPACITY   ACCESS MODES   STORAGECLASS         AGE
pvc-test            Pending                                      azure-disk-storage   31m

kubectl describe pvc test:
 Warning    ProvisioningFailed  59s (x32 over 31m)  persistentvolume-controller  Error creating provisioned PV object for claim pvc-test: persistentvolumes "pvc-ad62bf5a-508f-11e9-ae0a-000d3a2fcc18" is forbidden: error querying AzureDisk volume kubernetes-dynamic-pvc-XXXXXXXXXXXXXX: invalid disk URI: https://XXXXXXXXXXXXXXXXXXXX.blob.core.windows.net/vhds/kubernetes-dynamic-pvc-XXXXXXXXXXXXXXXX.vhd. Deleting the volume.

**Other details that may be helpful:**
- The pv gets created in the storage-group for dynamic pv of the cluster. 
- Works perfectly in rancher 2.1.7
- 
**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI):2.2
- Installation option (single install/HA):HA

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported):
- Machine type (cloud/VM/metal) and specifications (CPU/memory):
- Kubernetes version (use `kubectl version`):

```
(paste the output here)
```

- Docker version (use `docker version`):
18.09
```
(paste the output here)
```

**Comment by bmdepesa** [comment] 2019-04-01 21:44
I am unable to reproduce. 

* Deploy rancher server v2.1.7
* Create Azure cluster w/ cloud provider
* Attach Azure data disk to worker node
* Create PV
* Create workload in project with PVC
* *Upgrade to v2.2*
* Create workload in project
  * Added a new volume from new PVC
  * Added a new volume from existing PVC
* Edited existing workload
  * Added a new volume from new PVC
  * Added a new volume from existing PVC

PVCs get created successfully and workloads are functional.

@fwiedmann are there any steps I missed in trying to reproduce?

**Comment by alena1108** [comment] 2019-04-01 21:45
@fwiedmann is your cluster an AKS cluster (Hosted Kubernetes provider), or do you just use Azure driver to provision the nodes?

**Comment by fwiedmann** [comment] 2019-04-02 06:45
@bmdepesa No you didnt miss any steps. We had the same setup.

**Comment by fwiedmann** [comment] 2019-04-02 06:48
> @fwiedmann is your cluster an AKS cluster (Hosted Kubernetes provider), or do you just use Azure driver to provision the nodes?
@alena1108 We provision our k8s-clusters with the Azure driver.

**Comment by sirrapa** [comment] 2019-04-10 08:32
Any update on this issue?
We also noticed that the nodes created by the Azure Driver does not use managed disks.

**Comment by cjellick** [comment] 2019-04-10 18:22
No update. We cannot reproduce. If you can review @bmdepesa's steps and try to find any gaps in reproducing, that would be helpful.

**Comment by bmdepesa** [comment] 2019-04-10 18:29
@sirrapa @fwiedmann 

Are you using the Azure cloud provider with the Azure node driver?

**Comment by sirrapa** [comment] 2019-04-11 08:29
@bmdepesa yes we are using Azure cloud provider with the Azure node driver.

**Comment by bmdepesa** [comment] 2019-04-11 08:31
@sirrapa My original steps to reproduce did not use the cloud provider. I will attempt to reproduce this again.

**Comment by fwiedmann** [comment] 2019-04-11 12:54
We're using the version 2.2.0 with the new Cloud-Credential feature and using the azure cloudprovider. Set only the following to the cloudprovider: clientid, clientsecret, subscriptionid and tenantid (in v2.17.0 & v2.2.0)
This is our storageclass configuration:

```yaml
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  annotations:
    storageclass.beta.kubernetes.io/is-default-class: "true"
    storageclass.kubernetes.io/is-default-class: "true"
  name: azure-disk-storage
parameters:
  kind: dedicated
  storageaccounttype: Standard_LRS
provisioner: kubernetes.io/azure-disk
reclaimPolicy: Retain
volumeBindingMode: Immediate
```

**Comment by Nightapes** [comment] 2019-04-24 07:51
We have the same issue. It was working with Rancher 2.1.x and with 2.2.x it's broken.
Tested Rancher 2.2.2 with azure cluster and kubernetes version 1.13.x and 1.12.x same issue.
What i saw in the log is that the uri format changed.

```
// get resource group name from a managed disk URI, e.g. return {group-name} according to
// /subscriptions/{sub-id}/resourcegroups/{group-name}/providers/microsoft.compute/disks/{disk-id}
// according to https://docs.microsoft.com/en-us/rest/api/compute/disks/get
```
https://github.com/kubernetes/kubernetes/blob/master/pkg/cloudprovider/providers/azure/azure_managedDiskController.go#L263

The kube-controller-manager shows following uri in the log:

```
 Error creating provisioned PV object for claim default/test: persistentvolumes "pvc-{uuid}" is forbidden: error querying AzureDisk volume kubernetes-dynamic-pvc-{uuid}: invalid disk URI: https://{id}.blob.core.windows.net/vhds/kubernetes-dynamic-pvc-{uuid}.vhd. Deleting the volume.


```

**Comment by davidnuzik** [comment] 2019-05-08 21:11
In case it is not clear. The issue is only with Unmanaged disks. (Shared or Dedicated)

**Comment by kinarashah** [comment] 2019-05-08 22:25
That's correct @davidnuzik, The controller we removed (which has been deprecated in K8s, PersistentVolumeLabel) is related to get information about Labels and Zones. And I think path is different for managed vs unmanaged disks.

**Comment by rust84** [comment] 2019-05-10 11:14
same issue 2.2.2

**Comment by deniseschannon** [comment] 2019-05-10 14:34
@rust84 this is a known issue and being fixed in v2.2.3 (see the related backport issue https://github.com/rancher/rancher/issues/20072. Please feel free to test it out in v2.2.2-rc8 if you want.

**Comment by danielllek** [comment] 2019-05-14 10:51
@deniseschannon Something else should be done to make it work? 

I've upgrade rancher to v2.2.3, and still get errors: `Error creating provisioned PV object for claim`

**Comment by fwiedmann** [comment] 2019-05-14 10:58
We changed our default storage class from azure dedicated to managed. Works perfectly now! @kinarashah thank you for the hint 😄.

**Comment by bmdepesa** [comment] 2019-05-14 20:52
rancher/rancher:master 5/14

* Creating a PV from Storage Class for Azure dedicated disk works correctly
* Creating a PV from Storage Class for Azure shared disk does not work

To reproduce
* Deploy Rancher
* Create Azure cluster w/ cloud provider
* Create a storage class of type Azure Disk - Shared (Unmanaged)
* Create a workload with a new PV from Storage Class

Workload does not provision and an error is shown: `Pod has unbound immediate PersistentVolumeClaims (repeated 2 times)`

The persistent volume is not created, though there is a claim.

**Comment by bmdepesa** [comment] 2019-05-22 21:36
rancher/rancher:master e59adbc7

* Can create storage classes for shared and dedicated unmanaged disks
* PV are created correctly from storage classes

**Closed by bmdepesa** 2019-05-22 21:36 UTC
Labels: [zube]: To Test, kind/bug, status/ready-for-review, status/triaged, team/ca

**Comment by bmdepesa** [comment] 2019-05-22 21:45
Related: #20315

Storage type must be set in storage account setup for Azure Shared (unmanaged) disk to work in k8s versions > 1.11.x
