### ISSUE TITLE
Parsing issue with answers.yaml in UI

### ISSUE THREAD

**Issue by erikwilson** [rancher/rancher#18196] opened 2019-02-16 00:30 UTC
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**

Visit an app such as `/g/apps/catalog/cattle-global-data:library-artifactory-ha` or `/g/apps/catalog/cattle-global-data:helm-ark` and view `answers.yaml` file

**Result:**

error in the console for git based chart apps:
```
0:214255 Uncaught TypeError: e.replace is not a function
    at Function.t.escapeWithSingleQuotes (0:214255)
    at Function.e.dump (0:214243)
    at e.dump (0:214255)
    at e.dump (0:214255)
    at e.dump (0:214255)
    at Function.e.dump (0:214255)
    at Function.e.stringify (0:214255)
    at n.<anonymous> (0:175313)
    at n.get (0:47694)
    at re (0:46549)
```

or JSON for helm index based chart apps:
```
{}
```

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI):
server master
UI v2.2.2

**Comment by tfiduccia** [comment] 2019-04-08 22:01
@deniseschannon - This is an issue and is only reproducible when you view the answers.yaml in the global view.  Also the answers.yaml doesn't show up after you hit it, so we should probably fix it.

Errror: util.js:591 Uncaught TypeError: e.replace is not a function

![image](https://user-images.githubusercontent.com/11514927/55759793-27c8ef80-5a0f-11e9-91fc-c8953fae1a43.png)

**Comment by davidnuzik** [comment] 2019-04-16 20:56
Version: Master (4/16/19)

I now see answers at the global level without any issues.
![image](https://user-images.githubusercontent.com/45179589/56243058-85cc8700-604e-11e9-9f5f-82a1d31fdbbb.png)

However when I view the ark app I still see just `{ }` -- I do not think this is expected but may be a different issue perhaps. @loganhz do you have any input? Requires a new issue? Thank you.

**Comment by loganhz** [comment] 2019-04-17 00:08
@davidnuzik 

Apps without questions will show in json format now. But it looks like it is by design. I am not sure if there is some reason for it.

https://github.com/rancher/ui/blob/master/app/components/new-catalog/component.js#L182

It will be good if you can create a new issue and assign to @westlywright

**Comment by davidnuzik** [comment] 2019-04-17 17:09
Yeah, I think it's just by design I suppose it is okay (the user should know there are no questions thus answers is basically null)

**Comment by davidnuzik** [comment] 2019-04-17 17:09
I am closing this issue based on my testing done in https://github.com/rancher/rancher/issues/18196#issuecomment-483839902

**Closed by davidnuzik** 2019-04-17 17:09 UTC
Labels: area/catalog, area/ui, kind/bug, status/ready-for-review, status/resolved, status/to-test, status/triaged, team/cn
