### ISSUE TITLE
Kubernetes -- tiller-deploy is failing to run

### ISSUE THREAD

**Issue by karnatip** [rancher/rancher#7585] opened 2017-01-27 22:52 UTC
*Describe your issue here*

I see the following messgaes in the kubernetes dashboard -- 

Failed to pull image "gcr.io/kubernetes-helm/tiller:v2.1.3": Error response from daemon: {"message":"target is unknown"}
Error syncing pod, skipping: failed to "StartContainer" for "tiller" with ErrImagePull: "Error response from daemon: {\"message\":\"target is unknown\"}"

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v1.3.3` Cattle: `v0.175.9` UI: `v1.3.5` |
|Access|`localauth` `admin`|
|Orchestration|`Kubernetes`|
|Route|`k8s-tab.dashboard`|

**Comment by ryanwalls** [comment] 2017-02-04 18:13
I am seeing this as well on our setup.

**Comment by ryanwalls** [comment] 2017-02-04 18:18
May be duplicate of https://github.com/rancher/rancher/issues/7303

**Comment by ryanwalls** [comment] 2017-02-04 18:19
@karnatip What version of Docker are you running?  Looks like it may be a bug in docker that has been resolved in 1.13.1 rc1.  See https://github.com/kubernetes/helm/issues/1838#issuecomment-277021528

**Comment by aemneina** [comment] 2017-05-19 05:11
This shoudl work out of the box now. Feel free to try it on a modern version of rancher (using docker 1.12.6 ideally).

**Closed by aemneina** 2017-05-19 05:11 UTC
