### ISSUE TITLE
rancher-save-images.sh fails v2.2.4

### ISSUE THREAD

**Issue by dengtuoyu** [rancher/rancher#20696] opened 2019-06-06 03:22 UTC
https://github.com/rancher/rancher/releases/download/v2.2.4/rancher-images.txt
https://github.com/rancher/rancher/releases/download/v2.2.4/rancher-save-images.sh

docker pull jetstack/cert-manager-controller:v0.6.2
Error response from daemon: pull access denied for jetstack/cert-manager-controller, repository does not exist or may require 'docker login'

docker pull rancher/coredns-coredns:1.1.2
Error response from daemon: manifest for rancher/coredns-coredns:1.1.2 not found

docker pull rancher/prom-prometheus:v2.3.1
Error response from daemon: manifest for rancher/prom-prometheus:v2.3.1 not found

**Comment by bentastic27** [comment] 2019-06-06 16:58
Was able to confirm:

```
ben@ben-vm:~$ docker pull jetstack/cert-manager-controller:v0.6.2
Error response from daemon: pull access denied for jetstack/cert-manager-controller, repository does not exist or may require 'docker login'
ben@ben-vm:~$ docker pull rancher/coredns-coredns:1.1.2
Error response from daemon: manifest for rancher/coredns-coredns:1.1.2 not found
ben@ben-vm:~$ docker pull rancher/prom-prometheus:v2.3.1
Error response from daemon: manifest for rancher/prom-prometheus:v2.3.1 not found
```

Pulling from quay.io works for cert manager though, the image doesn't seem to exist on docker hub

```
ben@ben-vm:~$ docker pull quay.io/jetstack/cert-manager-controller:v0.6.2
v0.6.2: Pulling from jetstack/cert-manager-controller
78b595315e96: Pull complete 
2821a18ecc1f: Pull complete 
e506b56eda00: Pull complete 
3312e44d1788: Pull complete 
Digest: sha256:dab4def4ccb856dec0f62bdf96d2c3c9bbe17b8d569ef3f51c9a06b28db7a96a
Status: Downloaded newer image for quay.io/jetstack/cert-manager-controller:v0.6.2
```

The repos for rancher/coredns-coredns and prom-prometheus exist, but those tags aren't up.

**Comment by wweldon** [comment] 2019-06-06 17:46
When can we expect a fix for this?  We were hoping to get the 2.2.4 version in to address the 2.2.3 CVE .

**Comment by alena1108** [comment] 2019-06-07 00:47
@wweldon @bentastic27 @dengtuoyu we are looking into the fix. For now, you can remove all 3 images from rancher-images.txt file as non of them are required.

1) `jetstack/cert-manager-controller:v0.6.2` and `rancher/prom-prometheus:v2.3.1` got to the list by mistake due to the script pulling them from the hardcoded dev branch instead of pulling from release-v2.2 set via env variable. cc @rmweir 
2) coredns is an optional dns provider for rancher provisioned clusters

**Comment by wweldon** [comment] 2019-06-07 16:49
Thank you for the suggestion.  I will give it a try.

**Comment by alena1108** [comment] 2019-06-11 20:03
Updated the rancher-images.txt manually for now for 2.2.4. @rmweir my fix for scripts/package didn't work, so we should think of a diff solution

**Comment by wweldon** [comment] 2019-06-11 23:13
@alena1108, The suggested fix did allow me to build.  After removing the lines from my rancher-images.txt, I was able to pull all of the remaining packages, bring up Rancher 2.2.4.

sed -i '/jetstack\/cert-manager-controller\:v0.6.2/d' rancher-images.txt
sed -i '/rancher\/coredns-coredns\:1.1.2/d' rancher-images.txt
sed -i '/rancher\/prom-prometheus\:v2.3.1/d' rancher-images.txt

Hope this helps.

**Comment by patrick0057** [comment] 2019-06-13 13:43
Here is a similar fix but instead it replaces cert-manager-controller and prom-prometheus instead of deleting.  This was derived from v2.2.3 and has been confirmed to work.

```
sed -i -r 's,jetstack/cert-manager-controller:v0.6.2,quay.io/jetstack/cert-manager-controller:v0.5.2,g' rancher-images.txt
sed -i -r '/rancher\/coredns-coredns:1.1.2/d' rancher-images.txt
sed -i -r 's,rancher/prom-prometheus:v2.3.1,rancher/prom-prometheus:v2.7.1,g' rancher-images.txt
```

**Comment by alena1108** [comment] 2019-07-09 21:30
@jiaqiluo for testing, you can get rancher-images.txt and rancher-save-images.sh from the latest 2.2.5 rc

**Comment by jiaqiluo** [comment] 2019-07-09 21:50
The bugfix is validated in Rancher:v2.2.5-rc11

Steps:
- download the file `rancher-images.txt` and `rancher-save-images.sh` from the Rancher:v2.2.5-rc11 release: https://github.com/rancher/rancher/releases/tag/v2.2.5-rc11
- `chmod +x rancher-save-images.sh`
- `./rancher-save-images.sh`

Results:
- all images get pulled successfully
- the archive tar file is created successfully

**Closed by jiaqiluo** 2019-07-09 21:50 UTC
Labels: [zube]: To Test, internal, kind/bug
