### ISSUE TITLE
[BUG] Rancher Prime cluster cleanup job has wrong image

### ISSUE THREAD

**Issue by m-ildefons** [rancher/rancher#45404] opened 2024-05-07 06:47 UTC
**Rancher Server Setup**
- Rancher version: v2.7.12 (prime)
- Installation option (Docker install/Helm Chart): vcluster / helm

**Information about the Cluster**
- Kubernetes version: v1.27.12-k3s1
- Cluster Type (Local/Downstream): vcluster
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider): Imported

**User Information**
- What is the role of the user logged in? (Admin/Cluster Owner/Cluster Member/Project Owner/Project Member/Custom)
  - If custom, define the set of permissions: admin

**Describe the bug**
When unregistering a Harvester cluster from a prime-only Rancher instance, the Rancher agent's cleanup job is deployed with the wrong image:

```
 ErrImagePull (rpc error: code = NotFound desc = failed to pull and unpack image "docker.io/rancher/rancher-agent:v2.7.12": failed to resolve reference "docker.io/rancher/rancher-agent:v2.7.12": docker.io/rancher/rancher-agent:v2.7.12: not found) 
```

**To Reproduce**
1) Install a Harvester cluster
2) Install a prime-only Rancher instance (e.g. v2.7.12)
3) Import the Harvester cluster to the Rancher instance
4) Unset the `cluster-registration-url` setting of the Harvester cluster

**Result**
The Rancher agent will spawn a cleanup job with the wrong image. This job's Pod ends up in an image pull backoff state because the configured image does not exist on the registry.

**Expected Result**
The cleanup job should be spawned with the correct image and succeed.

**Screenshots**
![Screenshot at 2024-05-03 10-20-13](https://github.com/rancher/rancher/assets/17141774/88dcd1a7-a7e9-447c-afe3-5d13cc0580b2)

**Additional context**
https://github.com/rancher/rancher/blob/8298de0be13876ba54afdfcaf400f141b881842d/pkg/agent/clean/node_notwindows.go#L235

**Comment by snasovich** [comment] 2024-07-25 13:54
Closing as duplicate of https://github.com/rancher/rancher/issues/40068

**Closed by snasovich** 2024-07-25 13:54 UTC
Labels: kind/bug
