### ISSUE TITLE
User pods will be scheduled to management role only node

### ISSUE THREAD

**Issue by loganhz** [rancher/rancher#13712] opened 2018-05-24 23:49 UTC
rancher/rancher:v2.0.0

Steps to reproduce:

1.  Add a node with `management` role only.
2. Create some workloads.

Results:

The pods can be scheduled to the node. Maybe we should only schedule user pods to worker nodes?

**Comment by deniseschannon** [comment] 2018-05-25 16:30
Duplicate of https://github.com/rancher/rancher/issues/13524

We are working to make it so that control plane nodes are also marked as `unschedulable`

**Closed by deniseschannon** 2018-05-25 16:30 UTC
Labels: feedback/wechat, version/2.0
