### ISSUE TITLE
Feature request: able to save etcd snapshot into subdirectory of s3 bucket

### ISSUE THREAD

**Issue by vukor** [rancher/rancher#21281] opened 2019-07-02 13:03 UTC
**What kind of request is this (question/bug/enhancement/feature request):**
feature request

**Steps to reproduce (least amount of steps as possible):**
Create custom cluster in rancher UI + s3 backup settings

**Result:**
```
$ aws s3 ls s3://xxx/
2019-06-28 15:40:41    2383904 c-ck6wc-rs-qvrvb
```

It would be great to be able to save backup to s3://xxx/rancher-dev/ or s3://xxx/rancher-stg/ path for example. With this improvement we can use one s3 bucket for many rancher server deployments.

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): **2.2.4**
- Installation option (single install/HA): **HA**

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): **Custom**
- Machine type (cloud/VM/metal) and specifications (CPU/memory): **aws**
- Kubernetes version (use `kubectl version`): **v1.13.5**

Probably duplicated but not sure - https://github.com/rancher/rke/issues/1449

**Comment by davidnuzik** [comment] 2019-07-02 15:53
This might be a duplicate of https://github.com/rancher/rancher/issues/20859

**Comment by alena1108** [comment] 2019-07-02 18:24
https://github.com/rancher/rke/issues/1306

**Comment by alena1108** [comment] 2019-07-02 18:25
Looks this way @davidnuzik. Closing as a duplicate of https://github.com/rancher/rke/issues/1449; will keep track of the enhancement there.

**Closed by alena1108** 2019-07-02 18:25 UTC
Labels: kind/enhancement, team/ca
