### ISSUE TITLE
Kubernetes Version is empty when editing cluster v2.2.0-rc6

### ISSUE THREAD

**Issue by Troyhy** [rancher/rancher#18985] opened 2019-03-18 07:33 UTC
*Kubernetes version dropdown is empry*

![image](https://user-images.githubusercontent.com/587882/54513671-bee6de00-4960-11e9-88be-cec256b2aeb7.png)

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v2.2.0-rc6` UI: `v2.2.9` |
|Route|`authenticated.cluster.edit`|

**Comment by davidnuzik** [comment] 2019-03-18 15:55
Assigned to me to test this and try to reproduce/gather details

**Comment by davidnuzik** [comment] 2019-03-18 17:05
I am having a hard time reproducing this in v2.2.0-rc6 and latest master. I tried various RKE providers: DigitalOcean, Azure, EC2 and could not reproduce with any of those. I used Flannel networking as pictured.

**Comment by Troyhy** [comment] 2019-03-19 06:37
Cluster is using Hetzner driver https://github.com/JonasProgrammer/docker-machine-driver-hetzner
and is updated from earlier RC releases.

I tested same setup from fresh install of RC6 and it works as it should.

**Comment by Troyhy** [comment] 2019-03-19 06:39
Is there any log or other info that might help you or at least me to fix the issue in this cluster?

**Comment by GregorPirolt** [comment] 2019-03-21 19:42
@Troyhy I got the same problem. I also got the empty fields when creating a new cluster from the same rancher instance. I tried to export the cluster with the rancher cli and the use rancher up with the output. No success. Seems like the process of upgrading from 2.1.6 to alpha-3 and then all rc releases up to 8 messed up the etcd somehow... I also compacted and defraged the etcd inside rancher with no success.

**Comment by Troyhy** [comment] 2019-03-22 12:37
@GregorPirolt How did you manage interact with etcd of Rancher install? I have single node install...

**Comment by Troyhy** [comment] 2019-03-22 12:41
In my case deploying fresh cluster does not solve issue, there is something wrong in rancher's own data structures. All new clusters provisioned will suffer of this same issue. in addition whole setting yaml of cluster is uneditable and missin lot of stuff...
Here is the whole settings.yaml, It always remains this if I try to edit it.
```yaml
driver_name: "rancherkubernetesengine"
# 
#   # Rancher Config
# 
docker_root_dir: "/var/lib/docker"
enable_cluster_alerting: false
enable_cluster_monitoring: true
enable_network_policy: false
local_cluster_auth_endpoint: 
  enabled: true
name: "sandbox"
```

**Comment by GregorPirolt** [comment] 2019-03-22 13:25
> In my case deploying fresh cluster does not solve issue, there is something wrong in rancher's own data structures. All new clusters provisioned will suffer of this same issue. in addition whole setting yaml of cluster is un editable and missing lot of stuff...
> Here is the whole settings.yaml, It always remains this if I try to edit it.
> 
> ```yaml
> driver_name: "rancherkubernetesengine"
> # 
> #   # Rancher Config
> # 
> docker_root_dir: "/var/lib/docker"
> enable_cluster_alerting: false
> enable_cluster_monitoring: true
> enable_network_policy: false
> local_cluster_auth_endpoint: 
>   enabled: true
> name: "sandbox"
> ```

@Troyhy 
I got exactly the same Rancher Config and new clusters also look like that.
You could try to compact and defrag the etcd like I did, but as I said it does not help with the issue.
I also have a single node rancher running. Have you mounted the /var/lib/rancher folder onto your host machine? If so, you can try the following:
(please consider, that these steps might break the etcd db so, backup your current /var/lib/rancher folder and remount it, if you run into any problems... also if you are running a production cluster, STOP HERE :) and let someone who knows what he is doing help you)

Here is what I did to at least shrink the etcd-db and get some insight into the keys and values:
1) stop rancher
2) copy the whole etcd folder (should be at /var/lib/rancher/etcd or at /var/lib/rancher/management-state/etcd) to a separate location on your host
3) mount the copied etcd folder into a new container from image 'rancher/coreos-etcd:v3.2.24-rancher1'. 
4) inside the etcd-container (docker exec -it container-name sh) you can run the command 
etcd --data-dir=/path/to/mounted/etcd-folder and let it run
5) open another terminal window and again connect to the container (docker exec -it container-name sh)
6) run export ETCDCTL_API=3
7) now you can do all etcdctl commands with the database you could try etcdctl defrag to shrink the size with 'etcdctl get "" --prefix' you get all keys... 
7a) stop the etcd-container
8) before breaking anything, make sure you copied your original etcd folder to a save location
9) replace the old etcd folder with the one you  edited with the etcd-container
10) restart rancher
11) check if rancher can use the edited etcd db with docker logs -f name-of-your-rancher
if not, remount the etcd folder you sopied to a save location before

I hope this helps... let me know if you find something interesting.

But... I fear we have to rebuild the cluster in a fresh rancher install :(
cheers

**Comment by GregorPirolt** [comment] 2019-03-22 13:36
> In my case deploying fresh cluster does not solve issue, there is something wrong in rancher's own data structures. All new clusters provisioned will suffer of this same issue. in addition whole setting yaml of cluster is un editable and missing lot of stuff...
> Here is the whole settings.yaml, It always remains this if I try to edit it.
> 
> ```yaml
> driver_name: "rancherkubernetesengine"
> # 
> #   # Rancher Config
> # 
> docker_root_dir: "/var/lib/docker"
> enable_cluster_alerting: false
> enable_cluster_monitoring: true
> enable_network_policy: false
> local_cluster_auth_endpoint: 
>   enabled: true
> name: "sandbox"
> ```

@Troyhy 
one more thing that might be interesting: what was your update-path?
mine was v2.1.6 -> v2.2.0-alpha3 -> v.2.2.0-rc3 -> v.2.2.0-rc4 -> v.2.2.0-rc6 -> v.2.2.0-rc7 -> v.2.2.0-rc8 -> v.2.2.0-rc9 and I'm 80% sure I created the current cluster during alpha3
also: are you running locally? mine is running on 3 esxi vm (coreos)  (rancher/rancher is running on centos... but this should not matter)

**Comment by cjellick** [comment] 2019-03-22 16:12
I think you are hitting a bug that was introduced in one of our early RCs or alphas but was later fixed. Unfortunately, the bug (which I cannot find right now) put bad data into your DB. Since we don't support upgrading to or from alphas or RCs, we did not fix the bad data, we just fixed the bug that caused it so that upgrades to official releases would work.

Could you try reproducing by upgrading directly from 2.1.7 to the latest rc (v2.2.0-rc9)? You should not hit this bug through that path.

**Comment by vincent99** [comment] 2019-03-22 16:21
> mine was v2.1.6 -> v2.2.0-alpha3 -> v.2.2.0-rc3 -> v.2.2.0-rc4 -> v.2.2.0-rc6 -> v.2.2.0-rc7 -> v.2.2.0-rc8 -> v.2.2.0-rc9

While things usually work ok, upgrades to, from, or through non-releases are explicitly unsupported.  Alpha/RC tags should only be used on new, throwaway installations.  

I can't easily find a reference to it but else in the 2.2 cycle found a similar issue with upgrading through one of the versions in there resulted in broken cluster data CRDs.

**Comment by GregorPirolt** [comment] 2019-03-22 21:58
> I think you are hitting a bug that was introduced in one of our early RCs or alphas but was later fixed. Unfortunately, the bug (which I cannot find right now) put bad data into your DB. Since we don't support upgrading to or from alphas or RCs, we did not fix the bad data, we just fixed the bug that caused it so that upgrades to official releases would work.
> 
> Could you try reproducing by upgrading directly from 2.1.7 to the latest rc (v2.2.0-rc9)? You should not hit this bug through that path.

@cjellick I started to make backups of the etcd db after upgrading rancher to 2.2.0 alpha, so I can’t try the direct upgrade to rc9

I now created a new rancher and a new cluster and everthing works fine, so it must have been the bad db data.

**Comment by Troyhy** [comment] 2019-03-23 06:07
> @Troyhy
> one more thing that might be interesting: what was your update-path?
> mine was v2.1.6 -> v2.2.0-alpha3 -> v.2.2.0-rc3 -> v.2.2.0-rc4 -> v.2.2.0-rc6 -> v.2.2.0-rc7 -> v.2.2.0-rc8 -> v.2.2.0-rc9 and I'm 80% sure I created the current cluster during alpha3
> also: are you running locally? mine is running on 3 esxi vm (coreos) (rancher/rancher is running on centos... but this should not matter)

@GregorPirolt Actually my path was from initial install of  v2.2.0-alpha3 -> v.2.2.0-rc3  ->  v.2.2.0-rc6.

I'm running this on Hetzner cloud, using Hetzner provisioner  -> https://github.com/mxschmitt/ui-driver-hetzner

**Comment by Troyhy** [comment] 2019-03-23 06:12
@GregorPirolt Thanks for your ETCD info. I will try this and report back. My idea was to try to find config from etcd and replace it with "healty" one copied from another cluster witch is RC-6 without this problem.

**Comment by deniseschannon** [comment] 2019-04-15 21:20
Now that v2.2 has been officially released, Im going to close this issue. If you are having any of theses issues with an official release of Rancher please report back. Also note, that you may end up with some issues if you upgrade from a RC to an official release as sometimes (esp with the k8s version), that version might never have been introduced officially into rancher so it might be blank.

**Closed by deniseschannon** 2019-04-15 21:20 UTC
