### ISSUE TITLE
Support k8s 1.20

### ISSUE THREAD

**Issue by maggieliu** [rancher/rancher#30134] opened 2020-11-18 17:15 UTC
Need to support the new k8s version 1.20

**Comment by StrongMonkey** [comment] 2021-01-06 23:57
There are Azure library changes when bumping k8s 1.20 in rancher, make sure azureAD auth is tested to avoid any regression bug.

**Comment by StrongMonkey** [comment] 2021-01-29 03:51
Related changes:

- [ ] Rancher hyperkube is updated to v1.20.2. Hyperbase is updated to v0.0.2. https://github.com/rancher/hyperkube/pull/168 https://github.com/rancher/hyperkube/pull/167
- [ ] Etcd version is updated to 3.4.14.
- [ ] Corednd is updated to 1.8.0. (Due to https://github.com/coredns/coredns/issues/4418 we can't update to latest version 1.8.0 until this is fixed)
- [ ] Calico and canal CNI is updated to v3.17.1
- [ ] Weave CNI is updated to 2.8.1
- [ ] Metric-server is updated to v0.4.1
- [ ] Ingress-Nginx-controller is updated to v0.43.0. https://github.com/rancher/ingress-nginx/pull/37 (Drone build is failing)

Available to test on this fork. 

https://raw.githubusercontent.com/StrongMonkey/kontainer-driver-metadata/k8s.120/data/data.json

**Comment by sowmyav27** [comment] 2021-01-31 22:24
Will wait for the fixes to be merged to dev-v2.5 to test. Reopening it.

**Comment by StrongMonkey** [comment] 2021-02-01 23:58
v1.20.2-rancher2-1 is available to test on 2.5-head/2.5 RCs.

**Comment by sowmyav27** [comment] 2021-02-02 20:16
**On 2.5.6-rc4**

- Deployed clusters with k8s v1.20.2-rancher2-1 and using different network providers.
- The version of images seen:
```
- rancher/hyperkube - v1.20.2-rancher2
- etcdctl version: 3.4.14
- rancher/coredns-coredns:1.8.0
- rancher/calico-cni:v3.17.1
- rancher/calico-node:v3.17.1
- rancher/metrics-server:v0.4.1
- rancher/nginx-ingress-controller:nginx-0.43.0-rancher1
- weaveworks/weave-kube:2.8.1
```
- Network checks on all 4 clusters look good.

**Comment by StrongMonkey** [comment] 2021-02-05 17:01
Calico and Canal is upgraded to the latest version v3.17.2. Please verify this also.

**Comment by StrongMonkey** [comment] 2021-02-11 18:54
Kubectl version in shell(ember and dashboard) will also be updated to v1.19.7. Please verify that later.

**Comment by sowmyav27** [comment] 2021-02-16 23:20
Sanity Auth check on 2.5-head using Azure AD looks good.

**Comment by sowmyav27** [comment] 2021-02-17 06:43
**Kubectl version on a 1.20 k8s cluster on 2.5-head commit id: `03b8153174`**

- kubectl version
```
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.7", GitCommit:"1dd5338295409edcfff11505e7bb246f0d325d15", GitTreeState:"clean", BuildDate:"2021-01-13T13:23:52Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.2", GitCommit:"faecb196815e248d3ecfb03c680a4507229c2a56", GitTreeState:"clean", BuildDate:"2021-01-13T13:20:00Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by sowmyav27** [comment] 2021-02-19 06:35
**On master-head commit id: `f69f96bce`**

- Kubectl version is
```
kubectl version
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.7", GitCommit:"1dd5338295409edcfff11505e7bb246f0d325d15", GitTreeState:"clean", BuildDate:"2021-01-13T13:23:52Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.4", GitCommit:"e87da0bd6e03ec3fea7933c4b5263d151aafd07c", GitTreeState:"clean", BuildDate:"2021-02-18T16:03:00Z", GoVersion:"go1.15.8", Compiler:"gc", Platform:"linux/amd64"}
```

**Closed** 2021-02-19 06:35 UTC
Labels: [zube]: To Test
