### ISSUE TITLE
[not always reproducible] RKE2 Nodes are not being removed from backend/provider when deleting infrastructure-provider clusters through rancher

### ISSUE THREAD

**Issue by slickwarren** [rancher/rancher#34542] opened 2021-08-30 00:36 UTC
**Rancher Server Setup**
- Rancher version:v2.6.0-rc6
- Installation option (Docker install/Helm Chart):docker
   - If Helm Chart, Kubernetes Info:
         Cluster Type (RKE1, RKE2, k3s, EKS, etc):
         Node Setup:
         Version:
- Proxy/Cert Details:self signed

**Information about the Cluster**
- Kubernetes version:v1.21.4/1.21.3 (RKE2)
- Cluster Type (Local/Downstream): downstream
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider): Infrastructure provider - Azure, DO

**Describe the bug**

Sometimes, nodes are not being deleted from the provider when the cluster is removed through rancher. 

**To Reproduce**
 
* provision a cluster using an infrastructure provider (previously observed with azure, digital ocean)
  * wait for the cluster to come to active
* delete the cluster through rancher
  * wait for rancher to mark the cluster as deleted
* through the provider you chose, ensure your node(s) from the cluster have been deleted

**Result**
sometimes, the nodes are not removed from the provider

**Expected Result**

all nodes should be removed when deleting an infrastructure-provider cluster through rancher

**Screenshots**

**Additional context**

* this has been observed on Azure and Digital Ocean with RKE2
* this has only been observed so far with multi-node clusters

**Comment by thedadams** [comment] 2021-09-15 17:38
A couple of notes on this:
1. If you create a cluster then delete it before the nodes finish provisioning, then the cluster will be deleted from Rancher and the nodes leftover in the cloud provider. (This will be fixed and should be tested as part of the validation of the fix).
2. As far as the "not always reproducible" status of the issue: previously if the deletion job (to remove the machine from the cloud provider) failed, it would be ignored and never retried. Now the job will at least retry and this issue should be resolved or at least occur much less often.

**Comment by snasovich** [comment] 2021-09-23 02:10
Suggesting to add improvements to cluster deletion to 2.6.1 release notes. Possibly as one bullet point for all issues mentioned on the PR linked here.

**Comment by davidnuzik** [comment] 2021-09-24 23:58
**My checks PASSED**
 
**Reproduction Environment:**

Rancher version: v2.6.0
Rancher cluster type: single-node docker install
Docker version: 20.10
 
Downstream cluster type: RKE2
Downstream K8s version: v1.21.4+rke2r2
 
**Reproduction steps:**

1. In order to try to reproduce, create a multi-pool cluster. I used the EC2 node driver. Each pool having 2 or more nodes. I had to have more than a few or I just couldn't repro - went with etcd 5, cp 5, worker 5. I created the cluster and waited a bit for the ec2 instances to just BARELY provision (show up in aws) but didn't let the cluster finish creating I then deleted it. (e.g. wait for `Creating server (Amazonec2Machine) in infrastructure provider` status to almost go away but not quite, check aws and see ec2 instances there - don't wait longer or the cleanup will work; ec2 instances cannot get to Running state before attempting to delete the cluster -- or at least this was my experience).
2. I waited a bit for the cluster to be removed in rancher - I checked and I was indeed able to reproduce -- but even with 15 nodes usually only 1 or 2 get left behind -- good enough for me. Note, I also waited a bit just in case Rancher was not done cleaning them up (deleting them) still nothing so I indeed did reproduce the issue :)
3. I manually deleted the ec2 instances left behind.
![image](https://user-images.githubusercontent.com/45179589/134749385-26aba45f-8bba-4701-a5bb-85a4663b0c23.png)

 
-----
 
**Validation Environment:**

Rancher version: v2.6-head `a9e61c5` pulled at 9/24/21 ~2:20pm Pacific
Rancher cluster type: single-node docker install
Docker version: 20.10
 
Downstream cluster type: RKE2
Downstream K8s version: v1.21.4+rke2r2
 
**Validation steps:**

1. Perform the same steps as are outlined above in the reproduction section, except ensure that all ec2 nodes always get cleaned up. This required multiple attempts to reproduce the problem because the first time I reproduced it took four tries. I attempted this a total of six times to be mostly sure the fix works. I indeed could no longer reproduce, thus most likely the issue is fixed with the code change.

Here we can see from all six attempts to reproduce (validate the issue is fixed) none of the times did Rancher leave any ec2 instances behind:
![image](https://user-images.githubusercontent.com/45179589/134750417-1e08b4c3-ba45-4634-9c83-4d42b2a56ffd.png)
![image](https://user-images.githubusercontent.com/45179589/134750439-d746d0eb-a83b-4ff2-ba05-729398d93bc8.png)

**Closed by davidnuzik** 2021-09-24 23:58 UTC
Labels: kind/bug-qa, [zube]: QA Working, QA/XS, release-note, area/provisioning-rke2
