### ISSUE TITLE
[BUG] CIS scan failures on RKE2 hardened clusters

### ISSUE THREAD

**Issue by rishabhmsra** [rancher/rancher#39170] opened 2022-09-29 13:05 UTC
**Rancher Server Setup**
- Rancher version: v2.7-head(35388ea)
- Installation option (Docker install/Helm Chart): Docker

**Information about the Cluster**
- Kubernetes version: v1.24.4+rke2r1
- Cluster Type (Local/Downstream):
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider): Custom RKE2 hardened cluster(1-cp, 1-etcd, 1-w)

**User Information**
- What is the role of the user logged in? (Admin/Cluster Owner/Cluster Member/Project Owner/Project Member/Custom) Admin
  - If custom, define the set of permissions:

**Describe the bug**

- CIS scans using profiles `rke2-cis-1.23-profile-hardened` and `rke2-cis-1.23-profile-permissive` fails on RKE2 hardened clusters.

**To Reproduce**

- Provision a RKE2 hardened cluster. Followed this [guide](https://github.com/rancher/rancher/issues/36629#issuecomment-1100426864) to hardened the cluster.
- Install CIS benchmark chart `3.0.0-rc2` with below chart versions:
```
image:
  cisoperator:
    repository: rancher/cis-operator
    tag: v1.0.10-rc2
  securityScan:
    repository: rancher/security-scan
    tag: v0.2.9-rc3
  sonobuoy:
    repository: rancher/mirrored-sonobuoy-sonobuoy
    tag: v0.56.7
```
- Ran scans using `rke2-cis-1.23-profile-hardened` and `rke2-cis-1.23-profile-permissive` profile.

**Result**
- Getting failures in both permissive and hardened scans:
![image](https://user-images.githubusercontent.com/36376154/193038143-24358a16-df11-4f12-8c01-62aef4a594a5.png)

![image](https://user-images.githubusercontent.com/36376154/193038156-9b7603c2-19fa-4f81-b340-8df0ac289ff2.png)

![image](https://user-images.githubusercontent.com/36376154/193038185-9390799c-2071-45b8-966e-8b26a652bc4a.png)

**Expected Result**

- Scan should pass for both hardened and permissive profile

**Additional context**

- https://github.com/rancher/security-scan/pull/94

**Comment by prachidamle** [comment] 2022-10-04 22:41
If we plan to not have the CIS 1.23 rke2 benchmarks supported for k8s versions <1.25, then the minKubernetesVersion should be set on these benchmarks in the rancher-cis-benchmark chart @galal-hussein

**Comment by prachidamle** [comment] 2022-10-12 05:24
The PR is merged and waiting for `rancher-cis-benchmark` chart update.

**Comment by vivek-infracloud** [comment] 2022-10-14 10:47
CIS Benchmark chart fails to install on RKE2 hardened cluster.

cis-operator pod shows the following error.

`CreateContainerConfigError (container has runAsNonRoot and image will run as root (pod: "cis-operator-7469cdb657-chb8m_cis-operator-system(25057e27-f231-4dc1-91ba-9f04cbb7002c)", container: cis-operator))`

**Comment by galal-hussein** [comment] 2022-10-14 17:57
@vivek-infracloud I was able to reproduce the issue, I think there should be a specific psp in the chart so that any pod in the cis-operator will not be restricted by the default restricted policy, I wonder why this never occurred before though, the cis operator pod should always be failing since the restrticted default psp prevents any root container to start except for the pods in the kube-system namespace

**Comment by vivek-infracloud** [comment] 2022-10-17 08:19
@galal-hussein Thanks for updating the chart. I was able to install the CIS benchmark chart v3.0.0-rc7.

However, after running the permissive and hardened scans on k8s cluster v1.24.4+rke2r1 I'm still seeing the errors mentioned in the [issue](https://github.com/rancher/rancher/issues/39170#:~:text=Getting%20failures%20in%20both%20permissive%20and%20hardened%20scans%3A).

**Comment by vivek-infracloud** [comment] 2022-10-19 06:25
One test is still failing.

![Web capture_19-10-2022_15246_3 18 215 98](https://user-images.githubusercontent.com/83208989/196612863-46d741c8-fdbc-4642-80fd-31fd9b52b137.jpeg)

**Comment by vivek-infracloud** [comment] 2022-10-20 00:26
With updated CIS Benchmark chart v3.0.0-rc9 the hardened and permissive scans passed for the RKE2 hardened cluster. Hence closing the issue. Screenshot attached for the reference. 

![Web capture_20-10-2022_92427_3 18 215 98](https://user-images.githubusercontent.com/83208989/196828690-5edaf948-4dfb-4121-9613-15bcfd83bd52.jpeg)

**Closed by vivek-infracloud** 2022-10-20 00:26 UTC
Labels: kind/bug, [zube]: QA Working, team/area3, team/infracloud, feature/charts-cis-benchmark
