### ISSUE TITLE
KDM - wrong image is used for KubeDNS in RKE1 at multiple places 

### ISSUE THREAD

**Issue by jiaqiluo** [rancher/rancher#37911] opened 2022-06-04 17:15 UTC
at the following places, `rancher/mirrored-k8s-dns-kube-dns` should be used , instead of `rancher/mirrored-k8s-dns-node-cache` 

- https://github.com/rancher/kontainer-driver-metadata/blob/c974bcd1461419789c59066038fc69dce34168d0/rke/k8s_rke_system_images.go#L7329
- https://github.com/rancher/kontainer-driver-metadata/blob/c974bcd1461419789c59066038fc69dce34168d0/rke/k8s_rke_system_images.go#L7373
- https://github.com/rancher/kontainer-driver-metadata/blob/c974bcd1461419789c59066038fc69dce34168d0/rke/k8s_rke_system_images.go#L7417

Note:
I am not sure if we want to or can fix it in the released versions. 

Update:
 the fix is to introduce new versions which use the correct images

**Comment by snasovich** [comment] 2022-06-07 23:51
Closing as duplicate of https://github.com/rancher/rancher/issues/37890
Nice find, @jiaqiluo !

**Closed by snasovich** 2022-06-07 23:51 UTC
Labels: [zube]: Review, team/area2

**Comment by jiaqiluo** [comment] 2022-06-07 23:54
Instead of releasing `v1.23.4-rancher1-3` and `v1.23.6-rancher1-2`, the fix will be in the coming 1.23.7 patch relase.
