### ISSUE TITLE
Validation failed in API: PortInvalidProtocol

### ISSUE THREAD

**Issue by javisabalete** [rancher/rancher#9328] opened 2017-07-13 08:41 UTC
**Rancher versions:**
rancher/server: 1.5.3
rancher/agent: 1.2.1

**Infrastructure Stack versions:**
healthcheck: 0.2.3
ipsec: rancher/net: holder ;rancher/net: 0.11.1
network-services: metadata: 0.9.2 ; network-manager: 0.7.4
scheduler: 0.7.5

**Docker version: (`docker version`,`docker info` preferred)**
17.02.0-ce-17.05.0-ce
**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
Ubuntu 14.04.5 LTS (GNU/Linux 3.13.0-74-generic x86_64)

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
AWS-EC2

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
External DB

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle

**Steps to Reproduce:**
Upgrade service with public ports

**Results:**
Validation failed in API: PortInvalidProtocol

**Comment by garceri** [comment] 2017-08-03 20:27
@JaviSabalete Experiencing the same issue here now and then when upgrading perfectly working stacks, deleting and recreating the port mapping (with the same port/protocol information) before clicking upgrade makes the error go away.
Our environment is Rancher 1.6.2

**Comment by superseb** [comment] 2017-08-04 15:21
Cannot reproduce this in v1.6.6, can you try your scenario on this version?

**Comment by JaviSabalete** [comment] 2017-08-21 09:09
I'll upgrade to 1.6.X this week and i'll test again

**Comment by justinbleach** [comment] 2017-09-05 19:03
Rancher 1.6.5 with Docker 17.06.0-ce running on RHEL 7 does the same thing for me. 

I am researching why when our build completed the newest version of our container wasn't being deployed. I clicked "upgrade" and got the " Upgrade Error Validation failed in API: PortInvalidProtocol"

We have a public host port mapping of 8020 to the private container port of 8020.

**Comment by maxwo** [comment] 2017-09-28 12:28
I stumbled upon the same behavior when trying to upgrade a Kafka stack exposing 9092 and 7203 ports on host:

`{"id":"b2d4168d-db74-489c-b90f-8ee6cfaac488","type":"error","links":{},"status":422,"code":"PortInvalidProtocol","message":"PortInvalidProtocol","detail":null,"baseType":"error","actionLinks":{}}`

I am using Rancher on 4 environments right now (3 environments running 1.6.7 with an external MariaDB/Galera cluster, and 1 on 1.6.5 with an external MySQL 5.7 DB), and this error shows on only one of them, running 1.6.7

Versions used:

Debian Jessy as host
healthcheck:v0.3.1
net:v0.11.2
metadata:v0.9.1
network-manager:v0.7.0
scheduler:v0.7.5

**Comment by cjellick** [comment] 2017-09-28 16:43
@maxwo how are you deploying that stack? Do you have a compose file you can post?

**Comment by maxwo** [comment] 2017-09-29 11:15
This stack is deployed via the UI, in a private dedicated catalog. Here are the docker-compose and the rancher-compose:

`version: '2'

services:

  kafka:
    image: registry.pic.boulnet.com/kafka:0.11.0.0
    ports:
      - "9092:9092"
      - "7203:7203"
    environment:
      BACKEND_HOST: consul-agent.consul.rancher.internal:8500
    volumes:
      - /srv/data/kafka:/data
      - /var/log/socle/kafka:/logs
    labels:
      io.rancher.container.pull_image: always
      io.rancher.scheduler.affinity:host_label: kafka=yes
      io.rancher.scheduler.global: 'true'
      io.rancher.scheduler.affinity:container_label_ne: io.rancher.stack_service.name=$${stack_name}/$${service_name}

  zookeeper:
    image: registry.pic.boulnet.com/zookeeper:3.4.10
    restart: always
    environment:
      BACKEND_HOST: consul-agent.consul.rancher.internal:8500
    volumes:
      - /var/log/socle/zookeeper:/logs
      - /srv/data/zookeeper/data:/data
      - /srv/data/zookeeper/datalog:/datalog
    labels:
      io.rancher.container.pull_image: always
      io.rancher.scheduler.affinity:host_label: kafka=yes
      io.rancher.scheduler.global: 'true'
      io.rancher.scheduler.affinity:container_label_soft_ne: io.rancher.stack_service.name=$${stack_name}/$${service_name}

  kafka-manager:
    image: registry.pic.boulnet.com/kafka-manager:1.3.13.3
    environment:
      BACKEND_HOST: consul-agent.consul.rancher.internal:8500
    labels:
      io.rancher.container.pull_image: always
      io.rancher.scheduler.affinity:host_label: control=yes
      traefik.tags: control
      traefik.frontend.rule: PathPrefix:/kafka
      traefik.frontend.entryPoints: http
      traefik.port: 9000

  kafka-rest:
    image: registry.pic.boulnet.com/kafka-rest:3.3.0
    environment:
      BACKEND_HOST: consul-agent.consul.rancher.internal:8500
    volumes:
      - /var/log/socle/kafka-rest:/logs
    labels:
      io.rancher.container.pull_image: always
      io.rancher.scheduler.affinity:host_label: api=yes
      io.rancher.scheduler.global: 'true'
      io.rancher.scheduler.affinity:container_label_ne: io.rancher.stack_service.name=$${stack_name}/$${service_name}
      traefik.tags: api
      traefik.frontend.rule: PathPrefixStrip:/kafka
      traefik.frontend.entryPoints: http
      traefik.port: 8082
`

`.catalog:
  name: "Kafka"
  version: "0.11.0.0"
  description: "A Distributed Streaming Platform."
  uuid: kafka-0.11.0.0
  minimum_rancher_version: v0.56.0

kafka:
  start_on_create: true
  health_check:
    port: 9092
    interval: 5000
    unhealthy_threshold: 3
    strategy: recreate
    healthy_threshold: 3
    response_timeout: 5000

zookeeper:
  start_on_create: true
  health_check:
    port: 2181
    interval: 5000
    unhealthy_threshold: 3
    strategy: recreate
    healthy_threshold: 3
    response_timeout: 5000

kafka-manager:
  start_on_create: true
  health_check:
    request_line: GET /kafka/api/health HTTP/1.0
    port: 9000
    interval: 5000
    unhealthy_threshold: 3
    strategy: recreate
    healthy_threshold: 3
    response_timeout: 5000

kafka-rest:
  health_check:
    request_line: GET /topics HTTP/1.0
    port: 8082
    interval: 5000
    unhealthy_threshold: 3
    strategy: recreate
    healthy_threshold: 3
    response_timeout: 5000
`

**Comment by nathangoulding** [comment] 2018-04-13 21:04
We were experiencing this issue as well. Resolved by adding new Port Maps from the UI, replicating the settings on the new rows, and deleting all of the old Port Maps rows. Perhaps an invisible character that's not being stripped properly, or something.

**Comment by justinbleach** [comment] 2018-04-13 21:16
It’s been a while but I think a newer version of Rancher fixes this.

**Comment by superseb** [comment] 2018-09-10 06:44
Closing as stale.

**Closed by superseb** 2018-09-10 06:44 UTC
Labels: area/cattle, status/more-info
