### ISSUE TITLE
[rancher-compose] incorrect usage exits with 0 return code rather than non zero

### ISSUE THREAD

**Issue by mrproper** [rancher/rancher#3676] opened 2016-02-23 05:00 UTC
Version: v0.7.2
Steps: 
$ rancher-compose create ---foobar
Results:
Incorrect Usage.

Usage: rancher-compose create
$ echo $?
0

Expected:
echo $?
1

When you have incorrect parameter usage rancher-compose should exit with a non 0 value.
This is very important when you start doing automation...

**Comment by deniseschannon** [comment] 2016-02-23 05:08
Duplicate of https://github.com/rancher/rancher/issues/2385

**Closed by deniseschannon** 2016-02-23 05:08 UTC
