### ISSUE TITLE
[BUG] clusterprovisioner and health syncer controller conflict if status.Version is not set

### ISSUE THREAD

**Issue by Oats87** [rancher/rancher#41107] opened 2023-04-08 01:59 UTC
**Rancher Server Setup**
- Rancher version: v2.6.x - v2.7-head
- Installation option (Docker install/Helm Chart): N/A
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc):
- Proxy/Cert Details:

**Information about the Cluster**
- Kubernetes version: K3s/RKE2
- Cluster Type (Local/Downstream): Downstream Imported K3s/RKE2
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider):

**User Information**
- What is the role of the user logged in? (Admin/Cluster Owner/Cluster Member/Project Owner/Project Member/Custom)
  - If custom, define the set of permissions:
N/A

**Describe the bug**
On initial K3s/RKE2 cluster import, the clusterprovisioner and healthsyncer controllers can race with reach other, fighting to set the `Waiting` condition.

The cluster provisioner attempts to set the `Waiting` condition to `True` with a message indicating `Waiting for API to be available`, while the healthsyncer clears the message. Looking through the context on this, it turns out that this is intended behavior, where the provisioner sets the `Waiting for API to be available` message and health syncer should clear it indicating the cluster is ready (see: https://github.com/rancher/rancher/commit/877cb0c9043f23f3dad7538edf9016f3ca668cc5) 

If dealing with a K3s/RKE2 cluster and when the `statsaggregator` is unable to run in time and set the `status.Version` on the cluster object, the cluster provisioner will fail because the `status.Version` is empty (see: https://github.com/rancher/rancher/blob/8d7ffb9dadde2c1603902a465841aede71dadc97/pkg/controllers/management/clusterprovisioner/provisioner.go#L1068), this causes it to continously retry the `Create` lifecycle action and set the `Provisioned` message to `Waiting for API to be available` (see: See: https://github.com/rancher/rancher/blob/8d7ffb9dadde2c1603902a465841aede71dadc97/pkg/controllers/management/clusterprovisioner/provisioner.go#L400). The healthsyncer sees this and clears the message (see: https://github.com/rancher/rancher/blob/8d7ffb9dadde2c1603902a465841aede71dadc97/pkg/controllers/managementuser/healthsyncer/healthsyncer.go#L165), but because the `statsAggregator` has not yet set the `status.Version`, the provisioner sets the message and we end up thrashing.

I think the solution here would be to move the provisioner's message setting into the above block, i.e. only setting the message initially. I need to test this to make sure something else doesn't clear the condition message prematurely, but that is probably also considered a bug.

**To Reproduce**
This is pretty difficult to reproduce. I have a feeling it is specifically exasperated by a slow link between the Rancher and the downstream K3s cluster (and/or, the K3s cluster downstream is also slow at responding to API requests).

**Result**

**Expected Result**

**Screenshots**

**Additional context**

SURE-6128

**Comment by sowmyav27** [comment] 2023-04-25 22:06
Reopening since there are no automated tests

**Comment by deniseschannon** [comment] 2023-05-11 18:00
Whichever QA is assigned, since this is a difficult situation to test (existing user reporting only hits it after importing 300+ clusters), we have no ability to easily add in automated tests for this.

Given how hard it will be to even reproduce this issue, @Oats87, what basic provisioning use cases would test that this hasn't introduced any regressions?

**Comment by markusewalker** [comment] 2023-05-18 15:34
**QA TEST PLAN**

**Scenarios**
|Scenario|Test Case|
|---|---|
|1|As a standard user, import 5 K3S HA clusters into Rancher and validate that they come up as `Active`|
|2|As a standard user, import 5 RKE2 HA clusters into Rancher and validate that they come up as `Active`|

Since this issue is difficult to reproduce (original user imported 300+ clusters), the above test plan will aim to more so test that QA will consistently be unable to reproduce this issue.

**Comment by markusewalker** [comment] 2023-05-18 16:49
Unable to reproduce this issue in `v2.7.2`. See details below:

**ENVIRONMENT DETAILS**
- Rancher install: Docker
- Rancher version: `v2.7-head` https://github.com/rancher/rancher/commit/1eb478f3e77fde8a0328ed99cc3c39a1048442d2
- Browser: Chrome

**TEST RESULT**
|Scenario|Test Case|Result
|---|---|---|
|1|As a standard user, import 5 K3S HA clusters into Rancher and validate that they come up as `Active`|:white_check_mark:|
|2|As a standard user, import 5 RKE2 HA clusters into Rancher and validate that they come up as `Active`|:white_check_mark:|


**VALIDATION STEPS**

**Scenario 1**
1. Created a HA K3S `v1.24.13+k3s1` cluster of 4 nodes (3 control plane/etcd, 1 worker).
     - Repeated this process 5 times.
2. Navigated to Rancher > Cluster Management (as a standard user).
3. Imported each of the 5 K3S clusters; all clusters imported successfully and are `Active`:
<img width="813" alt="image" src="https://github.com/rancher/rancher/assets/52591819/61b017d7-ffc2-478c-b8b7-830acb06d493">
_________
**Scenario 2**
1. Repeated scenario 1, but used RKE2 clusters of `v1.24.13+rke2r1` (3 control plane/etcd, 3 workers).
2. Above screenshot shows the RKE2 clusters in an `Active` state.

I will conduct the above testing on the latest `v2.7-head` to see if I have similar results. Additionally, I will be running regression testing with QAs automated framework for RKE1/RKE2/K3S node driver/custom cluster provisioning.

**Comment by markusewalker** [comment] 2023-05-22 23:39
As per scaling/performance testing, using `v2.7-head` https://github.com/rancher/rancher/commit/707d173dc87d0dd28759fdf1a32e4be2949f7183, 300 K3S clusters were imported onto a Rancher HA setup. The issue was still not seen after this testing effort.

I will close this issue out.

**Closed by markusewalker** 2023-05-22 23:39 UTC
Labels: kind/bug, internal, [zube]: To Test, QA/S, area/imported-suc-managed, team/area2
