### ISSUE TITLE
Route 53 DNS service hitting API limits

### ISSUE THREAD

**Issue by wonderslug** [rancher/rancher#3257] opened 2016-01-13 16:26 UTC
Howdy

It looks like the route53 service is hitting AWS API limits.  

Im getting it going into degraded and restarting eventually with these

>1/13/2016 10:21:05 AMtime="2016-01-13T16:21:05Z" level=error msg="Failed to update provider with new DNS records: Provider error reading dns entries: Route53 API call has failed: Request failed, got status code: 400. Response: <?xml version=\"1.0\"?>\n<ErrorResponse xmlns=\"https://route53.amazonaws.com/doc/2013-04-01/\"><Error><Type>Sender</Type><Code>Throttling</Code><Message>Rate exceeded</Message></Error><RequestId>a5568810-ba11-11e5-ab6a-3b3df31c99c2</RequestId></ErrorResponse>"

Currently it looks like 5 requests per second is the limit and it does not appear that a higher limit can be requested.

http://docs.aws.amazon.com/Route53/latest/DeveloperGuide/DNSLimitations.html

**Comment by alena1108** [comment] 2016-01-14 00:47
@janeczku thank you for the fix again. Will reassign the bug to QA once external-dns is released, and new template is published

**Comment by alena1108** [comment] 2016-01-14 19:08
@sangeethah to test it, deploy route53 on your validation test setup. Let it be there for one validation test run, and make sure that this error is not seen:

```
 Request failed, got status code: 400. Response: <?xml version=\"1.0\"?>\nSenderThrottlingRate 
```
If your test removes the environment, or after route53 service removal, don't forget to cleanup the left over data from Route53 hosted zone ;)

**Comment by sangeethah** [comment] 2016-01-14 21:59
@alena1108 , Tested with "Route 53" template version - v0.2.1. I am able to reproduce the case were "Rate exceeded" is seen. 

The use case I tried was to create a stack with 100 services (scale 1) with exposed ports.
Activate the stack (so that all the services get activated in parallel).

I see a lot of these exception seen in  route53  container logs:


```
1/14/2016 1:52:57 PMtime="2016-01-14T21:52:57Z" level=error msg="Failed to add DNS record to provider {test406149.test957889.default.sangee-test.com. [107.178.223.75] A 300}: Request failed, got status code: 400. Response: <?xml version=\"1.0\"?>\n<ErrorResponse xmlns=\"https://route53.amazonaws.com/doc/2013-04-01/\"><Error><Type>Sender</Type><Code>Throttling</Code><Message>Rate exceeded</Message></Error><RequestId>2c3a0e02-bb09-11e5-83ce-b9e2e6268b45</RequestId></ErrorResponse>"
1/14/2016 1:52:57 PMtime="2016-01-14T21:52:57Z" level=info msg="Adding dns record: {test298774.test957889.default.sangee-test.com. [130.211.188.85] A 300}"
1/14/2016 1:52:57 PMtime="2016-01-14T21:52:57Z" level=error msg="Failed to add DNS record to provider {test298774.test957889.default.sangee-test.com. [130.211.188.85] A 300}: Request failed, got status code: 400. Response: <?xml version=\"1.0\"?>\n<ErrorResponse xmlns=\"https://route53.amazonaws.com/doc/2013-04-01/\"><Error><Type>Sender</Type><Code>Throttling</Code><Message>Rate exceeded</Message></Error><RequestId>2c56bdd2-bb09-11e5-861f-6f5f3c7947b0</RequestId></ErrorResponse>"
1/14/2016 1:52:57 PMtime="2016-01-14T21:52:57Z" level=info msg="Adding dns record: {test769776.test957889.default.sangee-test.com. [146.148.42.72] A 300}"
1/14/2016 1:52:57 PMtime="2016-01-14T21:52:57Z" level=error msg="Failed to add DNS record to provider {test769776.test957889.default.sangee-test.com. [146.148.42.72] A 300}: Request failed, got status code: 400. Response: <?xml version=\"1.0\"?>\n<ErrorResponse xmlns=\"https://route53.amazonaws.com/doc/2013-04-01/\"><Error><Type>Sender</Type><Code>Throttling</Code><Message>Rate exceeded</Message></Error><RequestId>2c754220-bb09-11e5-987c-7bd4aa4abab2</RequestId></ErrorResponse>"
1/14/2016 1:52:57 PMtime="2016-01-14T21:52:57Z" level=info msg="Adding dns record: {test899236.test957889.default.sangee-test.com. [130.211.188.85] A 300}"
1/14/2016 1:52:58 PMtime="2016-01-14T21:52:58Z" level=info msg="Adding dns record: {test749359.test957889.default.sangee-test.com. [107.178.223.75] A 300}"
1/14/2016 1:52:58 PMtime="2016-01-14T21:52:58Z" level=info msg="Adding dns record: {test190130.test957889.default.sangee-test.com. [130.211.188.85] A 300}"
1/14/2016 1:52:58 PMtime="2016-01-14T21:52:58Z" level=error msg="Failed to add DNS record to provider {test190130.test957889.default.sangee-test.com. [130.211.188.85] A 300}: Request failed, got status code: 400. Response: <?xml version=\"1.0\"?>\n<ErrorResponse xmlns=\"https://route53.amazonaws.com/doc/2013-04-01/\"><Error><Type>Sender</Type><Code>Throttling</Code><Message>Rate exceeded</Message></Error><RequestId>2cf71c8d-bb09-11e5-987c-7bd4aa4abab2</RequestId></ErrorResponse>"
1/14/2016 1:52:58 PMtime="2016-01-14T21:52:58Z" level=info msg="Adding dns record: {test103903.test957889.default.sangee-test.com. [130.211.188.85] A 300}"
1/14/2016 1:52:59 PMtime="2016-01-14T21:52:59Z" level=info msg="Adding dns record: {test773628.test957889.default.sangee-test.com. [146.148.42.72] A 300}"
1/14/2016 1:52:59 PMtime="2016-01-14T21:52:59Z" level=error msg="Failed to add DNS record to provider {test773628.test957889.default.sangee-test.com. [146.148.42.72] A 300}: Request failed, got status code: 400. Response: <?xml version=\"1.0\"?>\n<ErrorResponse xmlns=\"https://route53.amazonaws.com/doc/2013-04-01/\"><Error><Type>Sender</Type><Code>Throttling</Code><Message>Rate exceeded</Message></Error><RequestId>2d4bcc81-bb09-11e5-987c-7bd4aa4abab2</RequestId></ErrorResponse>"
1/14/2016 1:52:59 PMtime="2016-01-14T21:52:59Z" level=info msg="Adding dns record: {test595482.test957889.default.sangee-test.com. [130.211.188.85] A 300}"
1/14/2016 1:52:59 PMtime="2016-01-14T21:52:59Z" level=error msg="Failed to add DNS record to provider {test595482.test957889.default.sangee-test.com. [130.211.188.85] A 300}: Request failed, got status code: 400. Response: <?xml version=\"1.0\"?>\n<ErrorResponse xmlns=\"https://route53.amazonaws.com/doc/2013-04-01/\"><Error><Type>Sender</Type><Code>Throttling</Code><Message>Rate exceeded</Message></Error><RequestId>2d698dc2-bb09-11e5-987c-7bd4aa4abab2</RequestId></ErrorResponse>"
1/14/2016 1:52:59 PMtime="2016-01-14T21:52:59Z" level=info msg="Adding dns record: {test877264.test957889.default.sangee-test.com. [107.178.223.75] A 300}"
1/14/2016 1:52:59 PMtime="2016-01-14T21:52:59Z" level=info msg="Adding dns record: {test852534.test957889.default.sangee-test.com. [130.211.188.85] A 300}"
1/14/2016 1:53:00 PMtime="2016-01-14T21:53:00Z" level=info msg="Adding dns record: {test333250.test957889.default.sangee-test.com. [146.148.42.72] A 300}"
1/14/2016 1:53:00 PMtime="2016-01-14T21:53:00Z" level=info msg="Adding dns record: {test157445.test957889.default.sangee-test.com. [130.211.188.85] A 300}"
1/14/2016 1:53:01 PMtime="2016-01-14T21:53:01Z" level=info msg="Adding dns record: {test913836.test957889.default.sangee-test.com. [130.211.188.85] A 300}"
1/14/2016 1:53:01 PMtime="2016-01-14T21:53:01Z" level=info msg="Adding dns record: {test888800.test957889.default.sangee-test.com. [107.178.223.75] A 300}"
1/14/2016 1:53:02 PMtime="2016-01-14T21:53:02Z" level=info msg="Adding dns record: {test524020.test957889.default.sangee-test.com. [107.178.223.75] A 300}"
1/14/2016 1:53:03 PMtime="2016-01-14T21:53:03Z" level=info msg="Adding dns record: {test77721.test957889.default.sangee-test.com. [107.178.223.75] A 300}"
1/14/2016 1:53:03 PMtime="2016-01-14T21:53:03Z" level=info msg="Adding dns record: {test956848.test957889.default.sangee-test.com. [146.148.42.72] A 300}"
1/14/2016 1:53:03 PMtime="2016-01-14T21:53:03Z" level=info msg="Adding dns record: {test79000.test957889.default.sangee-test.com. [130.211.188.85] A 300}"
1/14/2016 1:53:04 PMtime="2016-01-14T21:53:04Z" level=info msg="Adding dns record: {test629597.test957889.default.sangee-test.com. [130.211.188.85] A 300}"
1/14/2016 1:53:04 PMtime="2016-01-14T21:53:04Z" level=info msg="Adding dns record: {test820893.test957889.default.sangee-test.com. [107.178.223.75] A 300}"
1/14/2016 1:53:04 PMtime="2016-01-14T21:53:04Z" level=info msg="Adding dns record: {test196573.test957889.default.sangee-test.com. [107.178.223.75] A 300}"
1/14/2016 1:53:04 PMtime="2016-01-14T21:53:04Z" level=info msg="Adding dns record: {test278778.test957889.default.sangee-test.com. [107.178.223.75] A 300}"
1/14/2016 1:53:05 PMtime="2016-01-14T21:53:05Z" level=info msg="Adding dns record: {test731360.test957889.default.sangee-test.com. [146.148.42.72] A 300}"
1/14/2016 1:53:05 PMtime="2016-01-14T21:53:05Z" level=info msg="Adding dns record: {test836161.test957889.default.sangee-test.com. [130.211.188.85] A 300}"
1/14/2016 1:53:05 PMtime="2016-01-14T21:53:05Z" level=info msg="Adding dns record: {test94174.test957889.default.sangee-test.com. [130.211.188.85] A 300}"
1/14/2016 1:53:06 PMtime="2016-01-14T21:53:06Z" level=info msg="Adding dns record: {test23871.test957889.default.sangee-test.com. [146.148.42.72] A 300}"
1/14/2016 1:53:06 PMtime="2016-01-14T21:53:06Z" level=info msg="Adding dns record: {test632260.test957889.default.sangee-test.com. [146.148.42.72] A 300}"
1/14/2016 1:53:06 PMtime="2016-01-14T21:53:06Z" level=info msg="Adding dns record: {test104172.test957889.default.sangee-test.com. [107.178.223.75] A 300}"
1/14/2016 1:53:06 PMtime="2016-01-14T21:53:06Z" level=error msg="Failed to add DNS record to provider {test104172.test957889.default.sangee-test.com. [107.178.223.75] A 300}: Request failed, got status code: 400. Response: <?xml version=\"1.0\"?>\n<ErrorResponse xmlns=\"https://route53.amazonaws.com/doc/2013-04-01/\"><Error><Type>Sender</Type><Code>Throttling</Code><Message>Rate exceeded</Message></Error><RequestId>31babee1-bb09-11e5-987c-7bd4aa4abab2</RequestId></ErrorResponse>"
1/14/2016 1:53:18 PMtime="2016-01-14T21:53:18Z" level=info msg="DNS records to add: [{test132883.test957889.default.sangee-test.com. [107.178.223.75] A 300} {test516283.test957889.default.sangee-test.com. [130.211.188.85] A 300} {test329901.test957889.default.sangee-test.com. [146.148.42.72] A 300} {test773628.test957889.default.sangee-test.com. [146.148.42.72] A 300} {test595482.test957889.default.sangee-test.com. [130.211.188.85] A 300} {test190130.test957889.default.sangee-test.com. [130.211.188.85] A 300} {test330266.test957889.default.sangee-test.com. [107.178.223.75] A 300} {test300050.test957889.default.sangee-test.com. [146.148.42.72] A 300} {test406149.test957889.default.sangee-test.com. [107.178.223.75] A 300} {test175185.test957889.default.sangee-test.com. [146.148.42.72] A 300} {test353718.test957889.default.sangee-test.com. [130.211.188.85] A 300} {test104172.test957889.default.sangee-test.com. [107.178.223.75] A 300} {test298774.test957889.default.sangee-test.com. [130.211.188.85] A 300} {test769776.test957889.default.sangee-test.com. [146.148.42.72] A 300} {test320634.test957889.default.sangee-test.com. [130.211.188.85] A 300}]"
```

**Comment by alena1108** [comment] 2016-01-14 22:18
@janeczku looks like AWS is still not happy even though the logs show that we do throttle the requests...we can try increasing the time slot from 1 to 2 seconds for starters; open for better suggestions.

**Comment by janeczku** [comment] 2016-01-15 02:28
@alena1108 I am not sure to which time slot you refer. I would suggest to first lower the limiter to 3 req/s https://github.com/rancher/external-dns/blob/master/providers/route53.go#L55. If this doesn't resolve the issue there might be another undocumented rate limit in place. We should be able to fix this by catching those status 400 errors and do a retry with a sleep delay.

**Comment by alena1108** [comment] 2016-01-15 06:10
>>PS: It is also worth noting, that the 5 req/s API rate limit is counted as a global limit per AWS account (not per hostedZone or AWS access key). That could have been a factor when @sangeethah ran her test. 

@sangeethah could we re-run the test again after making sure that there are no other route53 containers accessing the same account? I just realized that the other route53 service (the one that was removing the records :) which presence was discovered after this bug was reopened) might have interfered.


@janeczku 

>>I would suggest to first lower that rate to 3 req/s .

Thats a good suggestion, so we leave some room for requests coming from other clients. 

>>If this doesn't resolve the issue we can always resort to catch those status 400 errors and do a retry with a sleep delay.

The situation is recoverable even today - either metadata change, or periodic thread syncing up route53 records with the metadata, would re-apply the update. So I think for now, it would be enough to reduce the req/s limit.

**Comment by janeczku** [comment] 2016-01-16 00:50
> The situation is recoverable even today - either metadata change, or periodic thread syncing up route53 records with the metadata, would re-apply the update

Ahh, of course! :relieved:

**Comment by alena1108** [comment] 2016-01-16 00:50
@janeczku :)

**Comment by will-chan** [comment] 2016-03-08 01:35
please retest.

**Comment by sangeethah** [comment] 2016-03-11 00:15
Tested with rancher-server version - v0.63.0-rc2

Create External DNS service with version - rancher/external-dns:v0.2.1
Create a stack with 100 services (scale 1) with exposed ports.
Activate the stack (so that all the services get activated in parallel).

No "Throttling exceeded" errors was encountered when External DNS service programs the DNS entries in Route 53.

**Comment by jgreat** [comment] 2016-03-22 21:56
I see this is closed, but I'm seeing the route53 service "flap" with this error: 
```
Failed to update provider with new DNS records: Provider error reading dns entries: Route53 API call has failed: Request failed, got status code: 400. Response: <?xml version=\"1.0\"?>\n<ErrorResponse xmlns=\"https://route53.amazonaws.com/doc/2013-04-01/\"><Error><Type>Sender</Type><Code>Throttling</Code><Message>Rate exceeded</Message></Error><RequestId>4f02234d-f078-11e5-8742-bb025b4f515c</RequestId></ErrorResponse>"
```

It looks like the same issue.  Right now I have 7 environments trying to update to a route53 endpoint with many more environments planned in the future.  Would it be possible to have a configurable throttle so I can set it to something like once every N seconds? Or maybe the suggested delayed retry?   

I'm using rancher/external-dns:v0.3.0

**Comment by deniseschannon** [comment] 2016-03-22 22:42
What version of Rancher are you using?

**Comment by sangeethah** [comment] 2016-03-22 22:52
@jgreat , when I ran the tests to validate the fix , I was running only with 1 environment pointing to route53 . In my earlier tests , when I had 2 environments pointing to the same route53 hosted zone , I was abel to  reproduce the "Rate exceeded" error.

The most reliable way of not encountering this issue, is to have configurable throttle parameter that can be adjusted as per the deployments requirements.

Reopening this issue to introduce a configurable throttle parameter.

**Comment by janeczku** [comment] 2016-03-26 19:02
The currently used Route53 client library https://github.com/mitchellh/goamz seems to be EOL'd. 
This might be a good occasion to switch to the official [AWS SDK](https://github.com/aws/aws-sdk-go) which has build-in retry/backoff logic for dealing with errors like this. Since i just made the switch to the AWS SDK in another project it would probably not take me long to rewrite the Route 53 client in https://github.com/rancher/external-dns. Let me know if you are interested in a PR  @alena1108

**Comment by vincent99** [comment] 2016-03-26 19:04
Sure, that sounds good @janeczku

**Comment by janeczku** [comment] 2016-03-26 19:08
Alright :smile:

**Comment by janeczku** [comment] 2016-04-07 02:04
@vincent99 PR opened: https://github.com/rancher/external-dns/pull/31

**Comment by sangeethah** [comment] 2016-04-28 22:27
When testing with rancher/external-dns:v0.4.0 , I am still able still see the "Throttling: Rate exceeded" message show up in route53 container logs when  I have 2 environments pointing to the same route53 hosted zone:

In each of the environments:
Create a stack with 100 services (scale 1) with exposed ports.
Activate the stack (so that all the services get activated in parallel).

Following message shows in the logs:
```
4/28/2016 2:22:46 PMtime="2016-04-28T21:22:46Z" level=error msg="Failed to remove DNS record from provider {test-89.test52972.default.sangee-test1.com. [104.197.241.231] A 299}: Throttling: Rate exceeded\n\tstatus code: 400, request id: 59f3ba64-0d87-11e6-8328-1f6b3c404b92”
```
Also logged this issue where I see route53 instances getting recreated because of health check failures due to throttling - https://github.com/rancher/rancher/issues/4582

**Comment by janeczku** [comment] 2016-04-29 16:59
@sangeethah It's expected that there are errors at this high a scale (200 services created simultaneously). Route 53 only allows 5 API req/s. We are retrying requests for which we got a rate-limit error a certain number of times while each time delaying for an ever increasing duration. The higher the concurrent queries competing for the 5req/s rate limit the longer we would have to wait until even the last request completes with success.We can't do this indefinitely though because while we are waiting/retrying we are blocking any consecutive service changes to be send to the DNS.

With the current configuration of maxRetries=3 you should be able to create up to 40 services (spread over two environments) simultaneously without seeing a rate-limit exceeded error.
Also note that these errors are recoverable: We will detect any records that we failed to add due to rate-limit errors and re-add them in the next iteration (at least once every minute).

**Comment by jgreat** [comment] 2016-06-07 21:05
I was doing some debugging and noticed that healthcheck.go calls provider.GetRecords() 

If you are using the rancher catalog, the default health check interval is set to 2 seconds.  If you have 3 or 4 environments with multiple network-agents, just doing health checks will use up the api request limit.

I suggest increasing the health check interval in the rancher catalog. Maybe 30 seconds?

**Comment by janeczku** [comment] 2016-06-08 00:12
@jgreat This is fixed in the upcoming release of the catalog entry. See https://github.com/rancher/rancher-catalog/pull/155

**Comment by schuylr** [comment] 2016-08-03 17:35
Seconding @jgreat's point. I'm hitting Rate Limits myself because I have multiple domain names that need updating (Route53 can only perform Alias Targeting to the same Route53 Zone or established AWS services). It would be great if the Route53 Manager either:

- Allowed us to set the health check interval or have a much higher interval by default, or
- Allowed us to put multiple zones in a single agent

**Comment by jgreat** [comment] 2016-08-03 18:17
To get around the api request limits, we moved on to using an internally hosted PowerDNS service and delegating DNS for our rancher subdomain to that server. 

There is a powerdns external service in the public catalog and here is a link to my docker hub image for powerdns server: https://hub.docker.com/r/jgreat/powerdns/

An example rancher-catalog entry is included with the docker hub readme.

**Comment by sangeethah** [comment] 2016-08-11 20:09
Tested with rancher/external-dns:v0.5.0 hosted in https://github.com/janeczku/my-rancher-catalog.git

Scenario:
Have 2 environments pointing to the same route53 hosted zone:

In each of the environments:
Create a stack with 100 services (scale 1) with exposed ports.
Activate the stack (so that all the services get activated in parallel) at the same time.

All 200 records gets programmed successfully to route53 . 
route53 logs did not show any throttling error messages ("Rate exceeded")

@jgreat: @wonderslug: Issues you are encountering should be address with rancher/external-dns:v0.5.0.

**Comment by jgreat** [comment] 2016-08-12 21:00
That's not a good test scenario for the issue I experienced

Please try something along the lines of
35 environments each running an external DNS agent pointing to the same zone.
10 published services per environment.

This may be fixed now, but the health checks alone from all those environments were exceeding the API limits and causing intermittent external dns agent service failures.

**Comment by sangeethah** [comment] 2016-08-15 16:15
@jgreat , My understanding is that the scenario I am testing of activating an environment that has (100 services with exposed ports)  at the same time from 2 different environment which will result in high rate of concurrent calls to the the same "AWS Route 53" entry. similar to having very large number of environments pointing to the same same "AWS Route 53"  entry. 

According to @jan, API is limited to 4 calls/sec. When this limit is hit we get errors. We try to prevent errors by throttling the calls and retrying the call up to 4 times. This does not scale because we do this waiting in a single routine. Therefore updating of all other services is blocked. Therefore at some scale of concurrent services it is expected that we will get errors again.

**Comment by janeczku** [comment] 2016-08-16 00:25
@jgreat The issue concerns the missing handling of Rate Exceeded errors. The fix introduces a back-off/retry mechanism to gracefully deal with these errors. For validation it doesn't matter whether the API requests are triggered by health checks or record updates, hence the test case of having many services in two environments serves the purpose.
We have also raised the health check interval to 15 seconds and you can configure a custom value in the template as well.
/cc @sangeethah

**Comment by gmeans** [comment] 2016-08-30 21:16
Is there any way to get access to the updated external-dns template before 1.2 releases? This issue is really having an impact on our setup.

We have 3 environments, and it feels like a battle to update DNS configurations because rancher is eating up the quota. Unfortunately the Route 53 quota is shared between the API and the web console.

**Comment by jmreicha** [comment] 2016-08-31 20:00
I tried manually upgrading my route53 service to v0.5.0 but it just removes my DNS entries when it starts.  Is there a better way of getting to v0.5.0? An update to the template eventually?

**Comment by gmeans** [comment] 2016-09-07 15:26
I noticed an upgrade for the Route53 service in the Rancher UI and applied it. It appears to include v0.5.0 and so far I haven't had any Route53 rate exceeded errors.

Do updates like this get announced anywhere?

**Comment by deniseschannon** [comment] 2016-09-07 17:43
@gmeans No, we don't do any specific announcements for catalog template releases. If you see the "Upgrade Available" button for your stack available for a stack entry, it would indicate an updated template had gone out. 

@jmreicha An updated template was pushed to the catalog and should be available to everyone. 

@wonderslug @jgreat @schuylr If you upgrade to the latest template and continue to have issues, please comment on the issue.

**Closed by deniseschannon** 2016-09-07 17:43 UTC
Labels: area/external-dns, kind/bug, status/resolved, status/to-test

**Comment by schuylr** [comment] 2016-09-07 17:46
@deniseschannon I actually upgraded before the template release by making my own copy of the catalog and haven't had issues since. Thanks!

**Comment by jmreicha** [comment] 2016-09-12 01:38
@deniseschannon I just attempted upgrading via the updated template entry and it just wiped out my existing DNS entries.

Here's what's in the logs:

```
9/11/2016 6:34:48 PMtime="2016-09-12T01:34:48Z" level=info msg="Starting Rancher External DNS service"
9/11/2016 6:34:50 PMtime="2016-09-12T01:34:50Z" level=info msg="Configured Route 53 with hosted zone '.internal' in region 'us-west-1' "
9/11/2016 6:34:50 PMtime="2016-09-12T01:34:50Z" level=info msg="Healthcheck handler is listening on :1000"
9/11/2016 6:34:50 PMtime="2016-09-12T01:34:50Z" level=info msg="DNS records to remove:
```

And then it has an entry about removing the entries.

**Comment by jmreicha** [comment] 2016-09-12 02:05
Just to test, I tried stopping the old service and creating a new route53 from scratch but it never picked up any DNS changes.  When I shut off the new service and spun up the old service, the DNS entry was picked up right away after coming back up.

Does the updated catalog entry require a specific version of Rancher or something else?

**Comment by deniseschannon** [comment] 2016-09-12 15:00
@jmreicha The latest catalog entry for Route53 requires at least v1.1.0+. 

You can see if you are running the latest version of the template by sharing what tag the route53 services is using for the `rancher/external-dns` image.

**Comment by deniseschannon** [comment] 2016-09-12 15:01
Also, after it removed the existing entries, did it re-add them?

**Comment by jmreicha** [comment] 2016-09-12 17:26
@deniseschannon Yeah it never re-adds any DNS entries.  I am on an older version of Rancher (1.0.1), I wonder if that is part of my issue?

**Comment by janeczku** [comment] 2016-09-12 19:28
@jmreicha v0.5.0 of the template checks the state and health of containers before adding their public IP to the DNS entries. This information is not available in Rancher's Metadata service in any version before v1.1.0.

**Comment by jmreicha** [comment] 2016-09-12 19:51
@janeczku That makes sense.  I will work on getting upgraded and try again.  Thanks for the insight.

**Comment by linmark333** [comment] 2017-03-14 09:31
Just to provide a datapoint.

I'm on rancher 1.4.2, rancher/external-dns:v0.6.2.  With 1 environment and 1 load balancer, haven't been able to update route53.  I've increased health check to 60000

3/14/2017 2:28:36 AMtime="2017-03-14T09:28:36Z" level=error msg="Failed to add DNS record to provider {galaxy-balancer.deploy.integration.internal. [52.25.228.8] A 60}: Throttling: Rate for operation ChangeResourceRecordSets exceeded\n\tstatus code: 400, request id: 99b4708c-0898-11e7-8f86-0770e2d6dc9c"

**Comment by janeczku** [comment] 2017-03-14 12:23
@linmark333 There are ongoing isssues on Route53 service, see http://stackoverflow.com/questions/42780863/aws-route53-rate-for-operation-changeresourcerecordsets-exceeded

**Comment by linmark333** [comment] 2017-03-15 01:45
Thank you!  Didn't think I'd be so lucky to use rancher external DNS at the
time of Route53 API outage.
