### ISSUE TITLE
[ui] 'Add a host' link in notification bar when no hosts are present after adding environment does not work

### ISSUE THREAD

**Issue by superseb** [rancher/rancher#7578] opened 2017-01-27 10:31 UTC
**Rancher Versions:**
Server: 1.3.3
healthcheck:
ipsec:
network-services:
scheduler:
kubernetes (if applicable):

**Docker Version:**
n/a
**OS and where are the hosts located? (cloud, bare metal, etc):**
n/a
**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
single node
**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
n/a
**Steps to Reproduce:**
Follow up on: https://github.com/rancher/rancher/issues/7283

This also occurs after adding a new environment (in my case, kubernetes environment)

**Comment by tfiduccia** [comment] 2017-01-27 21:28
@superseb - Duplicate of #7488 and will be fixed in next release

**Closed by tfiduccia** 2017-01-27 21:28 UTC
