### ISSUE TITLE
[BUG] rancher machines are not removed from the cluster after actual worker nodes removed

### ISSUE THREAD

**Issue by riuvshyn** [rancher/rancher#43686] opened 2023-12-05 19:24 UTC
**Rancher Server Setup**
- Rancher version: 2.7.9, 2.8.0
- Installation option (Docker install/Helm Chart): helm
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc):
- Proxy/Cert Details: none

**Information about the Cluster**
- Kubernetes version: 1.27.8
- Cluster Type (Local/Downstream): downstream custom rke2 on hosted on aws
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider):

**User Information**
- What is the role of the user logged in? (Admin/Cluster Owner/Cluster Member/Project Owner/Project Member/Custom)
  - If custom, define the set of permissions:

**Describe the bug**
After upgrade from 2.7.5 to 2.7.9 I've noticed that terminated worker nodes are still displayed on rancher UI with `Nodenotfound` status.

`capi-controller-manager`: is full of errors like:

```
E1204 17:41:44.435523       1 controller.go:329] "Reconciler error" err="no matching Node for Machine \"custom-fbdc7789f02e\" in namespace \"fleet-default\": cannot find node with matching ProviderID" controller="machine" controllerGroup="cluster.x-k8s.io" controllerKind="Machine" Machine="fleet-default/custom-fbdc7789f02e" namespace="fleet-default" name="custom-fbdc7789f02e" reconcileID=330124c5-1ffb-4f7d-a618-94a976c62106
E1204 17:41:44.585423       1 controller.go:329] "Reconciler error" err="no matching Node for Machine \"custom-be9d831e6358\" in namespace \"fleet-default\": cannot find node with matching ProviderID" controller="machine" controllerGroup="cluster.x-k8s.io" controllerKind="Machine" Machine="fleet-default/custom-be9d831e6358" namespace="fleet-default" name="custom-be9d831e6358" reconcileID=63186033-4f57-4524-85af-2123a88f3a04
```

machine resource mentioned in the error still exists:
`k -n fleet-default  get machine | grep custom-be9d831e6358`

```
custom-be9d831e6358   rancher-euc1-te-test01   ip-172-29-196-238.eu-central-1.compute.internal   aws:///eu-central-1a/i-0a82b430f14175488   Running       5h6m
```

but `nodes.management.cattle.io` resources for old workers are gone

Also in downstream rke2 cluster `k get nodes` doesn't show these old nodes, so it is only affecting rancher.

**To Reproduce**
- Terminate active running  node

**Result**
After node is terminated it is removed from the cluster but it is not removed from rancher and node still displayed on UI in `Nodenotfound` status.

**Expected Result**
After node is terminated it is removed from the cluster and it is also removed from rancher.

**Screenshots**
<img width="1456" alt="image" src="https://github.com/rancher/rancher/assets/53786845/d054b7e1-1c38-4197-b236-0d56b6ddcd88">

**Additional context**
In slack other ppl mentioned that they have same issue starting from version 2.7.6 https://rancher-users.slack.com/archives/C3ASABBD1/p1701711546706849\

SURE-8277

**Comment by Oats87** [comment] 2023-12-05 21:17
From a quick glance, it appears that there is a problem with CAPI reconciliation of the machine object (it is trying to clean up the node reference)... Need to investigate this further.

**Comment by Oats87** [comment] 2023-12-05 23:26
Possibly related: https://github.com/kubernetes-sigs/cluster-api/issues/7237

**Comment by riuvshyn** [comment] 2023-12-11 14:30
I've managed to reproduce this issue with 2.8.0 version

**Comment by slickwarren** [comment] 2024-01-18 18:42
does this need a 2.9 forwardport?

**Comment by okgolove** [comment] 2024-03-11 11:44
@riuvshyn hi there!
Have the same issue. Does it somehow affect your cluster or it just stucs in `Updating` state?

**Comment by riuvshyn** [comment] 2024-03-13 11:31
@okgolove I've discovered this during testing upgrade in test env and once detected decided to revert. So I don't know much about actual impact on a managed cluster.

**Comment by okgolove** [comment] 2024-03-13 13:10
@riuvshyn ty for sharing your experience.
Could you tell from what to what version you tried to update?

**Comment by riuvshyn** [comment] 2024-03-14 10:08
@okgolove I was trying to upgrade from 2.7.5 to 2.8.0 but I think this regression was introduced in 2.7.6

**Comment by kgtw** [comment] 2024-03-14 15:14
Unfortunately the slack link referenced above is older than 90 days, so historical context within that thread is lost.

I can confirm that this is still a problem with v2.8.2 of rancher on a clean install, which is using v1.4.4 of the cluster-api controller. After a bit of investigation the problem why this is happening is because the `.metadata.deletionTimestamp` field is never set on the machine resource, this is preventing the cluster-api controller from reconciling the deletion of machine resources.

Relevant code can be seen here:
https://github.com/kubernetes-sigs/cluster-api/blob/00dbf7b9f6322d7ebd06ae2efa703b23354dd37d/internal/controllers/machine/machine_controller.go#L209-L219

I have checked the historic and future code of the cluster-api controller and this logic hasn't changed on their side. Perhaps @Oats87 you might have some insight as to where this was previously happening within the rancher code base, and or where we should be hoping to introduce the necessary changes to correctly set the deletion timestamp.

This can easily be reproduced, by simply watching the `cattle-provisioning-capi-system` pod logs then deleting a machine resource that had previously failed to reconcile.

**Comment by jdbaudean** [comment] 2024-03-20 02:17
I'm seeing this exact same behavior in 2.7.9.  This happens every time the cluster-autoscaler removes a node, I assumed it was an issue with the cluster-autoscaler or my aws-cloud-provider config.

**Comment by rjbrown57** [comment] 2024-03-25 15:59
Also seeing this issue in 2.8.2

**Comment by Oats87** [comment] 2024-04-22 19:55
> Unfortunately the slack link referenced above is older than 90 days, so historical context within that thread is lost.
> 
> I can confirm that this is still a problem with v2.8.2 of rancher on a clean install, which is using v1.4.4 of the cluster-api controller. After a bit of investigation the problem why this is happening is because the `.metadata.deletionTimestamp` field is never set on the machine resource, this is preventing the cluster-api controller from reconciling the deletion of machine resources.
> 
> Relevant code can be seen here: https://github.com/kubernetes-sigs/cluster-api/blob/00dbf7b9f6322d7ebd06ae2efa703b23354dd37d/internal/controllers/machine/machine_controller.go#L209-L219
> 
> I have checked the historic and future code of the cluster-api controller and this logic hasn't changed on their side. Perhaps @Oats87 you might have some insight as to where this was previously happening within the rancher code base, and or where we should be hoping to introduce the necessary changes to correctly set the deletion timestamp.
> 
> This can easily be reproduced, by simply watching the `cattle-provisioning-capi-system` pod logs then deleting a machine resource that had previously failed to reconcile.

Yes, I do know where the corresponding machines were being deleted for custom nodes after they were deleted from the downstream cluster. We were running into edge cases that would potentially lead to data loss from unintended machine/node deletion in disaster recovery scenarios, and opted to fall back to the "safer" option of having `cluster-api` handle node removal. As such, deleting the v1 nodes in a downstream cluster is actually not the desired method of deleting a node, we intend for nodes to be deleted through trigger/removal of the CAPI `Machine` object (which has the CAPI controllers perform the downstream `v1/Node` removal. 

Some context on this is here: https://github.com/rancher/rancher/issues/42201

As such, a workaround that can be applied to `v2.7.11` is to simply delete the CAPI `machine` object. One could potentially even write a script that would look for machines with the `Nodenotfound` and clean them up.

**Comment by jdbaudean** [comment] 2024-04-22 21:22
@Oats87 I've tried deleting the machines from both Cluster Management, and via the local cluster in the Rancher UI under Machines.  That works, however if there is another node with the same node name Rancher will drain and cordon the node that actually does exist.  We do a lot of autoscaling so an ec2 instance launched today might have the same IP (and Node name) as instance that was previously killed and removed from the cluster by the CA days or weeks ago.  For example

```
State                   Name                    Node
Nodenotfound   custom-f9d9d....   ip-10.114.30.227.ec2.internal
Running             custom-b5264....   ip-10.114.30.227.ec2.internal
```

If I delete the first node from Cluster Management it does delete the node that no longer exists, but it also drains, cordons, and deletes the second node which has active workloads.

**Comment by Oats87** [comment] 2024-04-23 02:43
> @Oats87 I've tried deleting the machines from both Cluster Management, and via the local cluster in the Rancher UI under Machines. That works, however if there is another node with the same node name Rancher will drain and cordon the node that actually does exist. We do a lot of autoscaling so an ec2 instance launched today might have the same IP (and Node name) as an instance that was previously killed and removed from the cluster by the CA days or weeks ago. For example
> 
> ```
> State                   Name                    Node
> Nodenotfound   custom-f9d9d....   ip-10.114.30.227.ec2.internal
> Running             custom-b5264....   ip-10.114.30.227.ec2.internal
> ```
> 
> If I delete the first node from Cluster Management it does delete the node that no longer exists, but it also drains, cordons, and deletes the second node which has active workloads.

To clarify, when using provisioningv2, `cluster-api` is the component responsible for performing the drain and cordon of your node. It's definitely not ideal that you're ending up in a situation where you have multiple machines that reference the same node -- ideally `cluster-api` would refer to the node using the `uid` of the `v1/Node` object which would prevent that situation; however, it does not seem that it does that based on the behavior you've described. I'll need to do some digging into determining a workaround for that specific situation.

**Comment by okgolove** [comment] 2024-04-24 05:46
May be used as a workaround:
```bash
STALE_MACHINES=$(kubectl get machines.cluster.x-k8s.io -n fleet-default -o json | jq -r '.items[] | select ((.status.conditions[] | .type=="NodeHealthy" and .status=="False" and .reason=="NodeNotFound")) | .metadata.name')
kubectl delete -n fleet-default machines.cluster.x-k8s.io $(echo ${STALE_MACHINES} | tr "\n" " ")
```

**Comment by riuvshyn** [comment] 2024-04-24 10:59
@okgolove That is exactly what I did, and put that into a CronJob but still looking forward for proper fix :/

**Comment by jdbaudean** [comment] 2024-04-24 20:35
@okgolove unfortunately that still cordons, drains, and then deletes running nodes that have the same Node Name as the machine labeled NodenotFound

**Comment by riuvshyn** [comment] 2024-04-25 12:29
@jdbaudean yeah, that is why I put that script into a cron job which is running every 15minutes to make sure that machine 
 with state`NodeNotFound` is removed as soon as it gets in to that state. In your case you might need to adjust interval.

**Comment by snasovich** [comment] 2024-05-10 21:04
Closing this issue as "by design" per https://github.com/rancher/rancher/issues/43686#issuecomment-2070844933, more specifically below from it:
> As such, deleting the v1 nodes in a downstream cluster is actually not the desired method of deleting a node, we intend for nodes to be deleted through trigger/removal of the CAPI Machine object (which has the CAPI controllers perform the downstream v1/Node removal.

**Comment by jdbaudean** [comment] 2024-05-10 21:16
@snasovich So far this happens when I delete a node from the cluster via the Rancher UI, delete a node using `kubectl delete node <node-name>`, and when the cluster-autoscaler removes nodes.  That is by design?

**Comment by rjbrown57** [comment] 2024-05-10 21:25
What's the appropriate method to trigger `deleted through trigger/removal of the CAPI Machine object`

**Comment by kgtw** [comment] 2024-05-11 00:45
@snasovich I'm not following how this is by design? This basically means any use of autoscaling (cluster autoscaler, karpenter, manual scaling of underlying cloud resources) will leave lingering nodes within the cluster with no means for reconciliation, except for the temporary solutions posted above.

**Comment by riuvshyn** [comment] 2024-05-13 11:34
@snasovich 
We have noticed that leaving these abandoned machines in `NodeNotFound` status on large clusters with dynamic leads to the state where there are hundreds of abandoned machines and even rancher UI is struggling with loading cluster management view.
This brakes custom node pools support.

**Comment by mohahmed13** [comment] 2024-05-13 13:46
We have also noticed that upgrading cluster version, or applying any projects, roles, and mappings fail to go through since the cluster is not in an `Active` state when there is a `NodeNotFound` machine present.

**Comment by jdbaudean** [comment] 2024-05-13 15:55
To add another data point, last week one of my Control Planes crashed so I removed it from the cluster via the Rancher UI and added a new Control Plane.  I came in today with a bunch of Worker nodes that couldn't register because the previously deleted Control Planes couldn't apply the plan in Cluster Management.... because they no longer existed.

The removal of nodes was all done in the Rancher UI, if this was by design, wouldn't it at least work in the Rancher UI?

**Comment by brandond** [comment] 2024-05-13 20:17
I think people are getting confused about the different resource types. You're supposed to delete the **Machine** resource, not the **Node** resource.

As Chris said:
> deleting the v1 nodes in a downstream cluster is actually not the desired method of deleting a node, we intend for nodes to be deleted through trigger/removal of the CAPI Machine object

**Comment by snasovich** [comment] 2024-05-14 02:56
@brandond , thank you for chiming in.

@jdbaudean @rjbrown57 @kgtw @riuvshyn @mohahmed13 , thank you for the feedback - I see this change of behavior affects quite a few users based on the immediate reaction.

**@Oats87 , is this something we should consider? Maybe as opt-in behavior to enable that now-removed controller?
What would be the areas of functionality potentially affected if this behavior is reinstated?**

Responding to some of the more specific comments:

@jdbaudean ,
> So far this happens when I delete a node from the cluster via the Rancher UI...

Could you please clarify what you mean by "Rancher UI"? I'm pretty sure that deleting nodes via "Cluster Management" in Rancher UI works as expected (deletes `machines.cluster.x-k8s.io` objects).

> To add another data point, last week one of my Control Planes crashed so I removed it from the cluster via the Rancher UI and added a new Control Plane. I came in today with a bunch of Worker nodes that couldn't register because the previously deleted Control Planes couldn't apply the plan in Cluster Management.... because they no longer existed.
> 
> The removal of nodes was all done in the Rancher UI, if this was by design, wouldn't it at least work in the Rancher UI?

You may be running into some other issue - unless it's tied to the previous message where Rancher UI was used to delete Node resources directly.


@kgtw ,
> @snasovich I'm not following how this is by design? This basically means any use of autoscaling (cluster autoscaler, karpenter, manual scaling of underlying cloud resources) will leave lingering nodes within the cluster with no means for reconciliation, except for the temporary solutions posted above.

Valid points. Wondering if there are any CAPI-aware autoscalers that may work here? @Oats87

**Comment by jdbaudean** [comment] 2024-05-14 03:26
@snasovich You're right, from Cluster Management it works as expected.  I don't know about other peoples workflow but I spend 99% of my time in the Rancher UI in the Cluster view, not Cluster management.  When deleting a node from the Cluster view it still leaves the Machine resource in Cluster Management.  I tried the same thing with my local K3s cluster in the Cluster view and that does work as I would expect it to, it deletes both the Node resource from the cluster and the machine resource from Rancher.  Unless I'm reading the docs wrong it appears that delete operations should work from the Cluster view, not just Cluster Management.  https://ranchermanager.docs.rancher.com/how-to-guides/new-user-guides/manage-clusters/nodes-and-node-pools#node-options-available-for-each-cluster-creation-option

The problem with kubectl is the same.  If I'm not in the Rancher UI I'm using kubectl to manage my RKE2 cluster, but if this is working as intended then we can't use kubectl either.  I'm not sure why someone would want to remove a node from their cluster but leave the machine resource, although I guess that's possible.  In my opinion, if this is the new design that Rancher is going with, then a `kubectl delete node` and a delete from the cluster view should also trigger a delete of the machine resource.

>You may be running into some other issue - unless it's tied to the previous message where Rancher UI was used to delete Node resources directly.

Yes this was because it was deleted from the Rancher UI in the cluster view or with kubectl, I tend do either one depending on what else I'm doing at the moment.

We use Rancher to make things simpler when provisioning and managing a kubernetes cluster.  I really like the product and the support we get, but adding an extra step like this that doesn't work with industry standard tools like kubectl and the cluster-autoscaler makes me less likely to use Rancher in the future.   The UI bit is annoying but kubectl and cluster autoscaling are critical.

Thanks for addressing this.

**Comment by Oats87** [comment] 2024-05-14 13:07
@snasovich I'm going to go ahead and re-open this issue.

While the original intention of removing this behavior was to better align with other providers upstream, I do believe there is merit for the various use-cases stated here (primarily auto scaling) that would benefit from a workflow that allows v1.Node objects to be deleted and have their corresponding CAPI machines cleaned up.

I believe we can re-add this behavior, but make it opt-in. Once enabled, the custom node controller in the CAPR infrastructure provider would reconcile/delete the corresponding CAPI machine objects if it sees a removal of the custom node. To those commenting on this issue that are affected by the change in behavior -- would that work?

**Comment by snasovich** [comment] 2024-05-15 14:22
@Oats87 , thank you and agree. However, we will need to document what kind of issues users may run into with this option enabled. For example, I'm assuming https://github.com/rancher/rancher/issues/42201 may then resurface on such configuration - would we then want to recommend turning this option off before restore?
It also raises a question of whether we want this as a global option or per-cluster or both (the "per-cluster" may actually cause problems if at snapshot time that option was on and we would like to turn it off to avoid https://github.com/rancher/rancher/issues/42201 as on restore it likely will get back to on for that cluster - unless we specifically handle this situation on restore).

@jdbaudean , just to close the loop on the below:

> Unless I'm reading the docs wrong it appears that delete operations should work from the Cluster view, not just Cluster Management. [ranchermanager.docs.rancher.com/how-to-guides/new-user-guides/manage-clusters/nodes-and-node-pools#node-options-available-for-each-cluster-creation-option](https://ranchermanager.docs.rancher.com/how-to-guides/new-user-guides/manage-clusters/nodes-and-node-pools#node-options-available-for-each-cluster-creation-option)

The https://ranchermanager.docs.rancher.com/how-to-guides/new-user-guides/manage-clusters/nodes-and-node-pools specifically states "2. Select Cluster Management." so the table applies to Cluster Management functionality only.

**Comment by jdbaudean** [comment] 2024-05-15 14:42
@snasovich

And then Step 3
>Find the cluster whose nodes you want to manage, and click the Explore button at the end of the row.

The explore button takes you out of Cluster Management into the Cluster view.

**Comment by snasovich** [comment] 2024-05-15 15:15
@jdbaudean , my bad - missed that part - thank you for pointing me to it.

**Comment by jdbaudean** [comment] 2024-05-30 19:41
I built on the example by @okgolove and added some logic to check for healthy nodes that shared the same node name as a stale Machine resource.  I'm super paranoid about accidentally deleting a healthy node, that tends to cause data loss for our users.  I didn't spend much time on it and it's not optimized at all, but it gets the job done.  Hope this helps some folks out

```
#!/bin/bash

DATA=$(kubectl get machines.cluster.x-k8s.io -n fleet-default -o json)
STALE_MACHINES=$(jq -r '.items[] | select ((.status.conditions[] | .type=="NodeHealthy" and .status=="False" and .reason=="NodeNotFound")) | .metadata.name' <<< "${DATA}")
HEALTHY_NODES=$(jq -r '.items[] | select ((.status.conditions[] | .type=="NodeHealthy" and .status=="True")) | .status.nodeRef.name' <<< "${DATA}")

healthy_nodes_array=($HEALTHY_NODES)
machine_array=($STALE_MACHINES)
for machine in "${machine_array[@]}"
do
  healthy_node_found=false
  echo "Checking ${machine}"
  node=$(kubectl get machines.cluster.x-k8s.io -n fleet-default -o json | jq --arg machine $machine -r '.items[] | select (.metadata.name==$machine) | .status.nodeRef.name')
  echo "Node name: $node"

  for healthy_node in "${healthy_nodes_array[@]}"
  do
    if [[ $node == $healthy_node ]]
    then
      healthy_node_found=true
      echo "****************************************************"
      echo "Healthy node found ${node}"
      echo "****************************************************"
    fi
  done
  if [[ $healthy_node_found == false ]]; then
    echo "Removing machine $machine with node name $node"
    kubectl delete -n fleet-default machines.cluster.x-k8s.io $machine
  fi
  echo ""

done
```

**Comment by zmedico** [comment] 2024-06-03 17:15
> May be used as a workaround:
> 
> ```shell
> STALE_MACHINES=$(kubectl get machines.cluster.x-k8s.io -n fleet-default -o json | jq -r '.items[] | select ((.status.conditions[] | .type=="NodeHealthy" and .status=="False" and .reason=="NodeNotFound")) | .metadata.name')
> kubectl delete -n fleet-default machines.cluster.x-k8s.io $(echo ${STALE_MACHINES} | tr "\n" " ")
> ```

You can make this event driven by reading json lines from `kubectl get --watch` like this:
```bash
while read -r machine; do
	stale=$(jq -r 'select ((.status.conditions[]? | .type=="NodeHealthy" and .status=="False" and .reason=="NodeNotFound")) | .metadata.name' <<<"${machine}")
	if [[ ${stale} && ${stale} != "${dedup}" ]]; then
		dedup=${stale}
		kubectl delete -n fleet-default machines.cluster.x-k8s.io "${stale}"
	fi
done < <(while true; do kubectl get machines.cluster.x-k8s.io -n fleet-default -o=jsonpath='{@}{"\n"}' --watch; done)
```
Then add a livenessProbe to query for NodeNotFound older than a threshold.

**Comment by Josh-Diamond** [comment] 2024-07-10 15:59
Ticket #43686 - Test Results - ✅ 
---

Verified on Rancher `v2.9-1c2b815c8dd66e141b21630904127adc8e03c3de-head`:

| Scenario | Test Case | Result |
|---|---|---|
| 1. | Provision custom rke2 cluster + delete a node; machine object expected to stay  | ✅ |
| 2. | Provision custom k3s cluster + delete a node; machine object expected to stay  | ✅ |
| 3. | Apply annotation to rke2 custom cluster + observe orphaned machine object terminate | ✅ |
| 4. | Apply annotation to k3s custom cluster + observe orphaned machine object terminate | ✅ |
| 5. | Take snapshot on custom rke2 cluster => upgrade k8s version => restore to snapshot | ✅ |
| 6. | Take snapshot on custom k3s cluster => upgrade k8s version => restore to snapshot | ✅ |

---

Scenario 1 - ✅ 
1. Fresh install of Rancher `v2.9-head`
2. Provision a downstream RKE2 custom cluster w/ k8s 1.29
3. Once `active`, take a snapshot
4. Navigate to `Cluster Explorer > Nodes` and delete a worker node, then delete the associated instance on the cloud provider side
5. Verified - issue is reproduced; `NodeNotFound` status is seen on the machine of the terminated node via `Cluster Management > Machines`; as expected

---

Scenario 2 - ✅
1. Fresh install of Rancher `v2.9-head`
2. Provision a downstream K3s custom cluster w/ k8s 1.29
3. Once `active`, take a snapshot
4. Navigate to `Cluster Explorer > Nodes` and delete a worker node, then delete the associated instance on the cloud provider side
5. Verified - issue is reproduced; `NodeNotFound` status is seen on the machine of the terminated node via `Cluster Management > Machines`; as expected

---

Scenario 3 - ✅
1. Utilizing the cluster from Scenario 1, `Edit YAML`, and apply the following annotation:
```log
rke.cattle.io/delete-missing-custom-machines-after: '5s'
```
2. Observe orphaned machine objects terminate
3. Verified - cluster `active` and accurately reflects 1:1 ratio of nodes to machines; as expected

---

Scenario 4 - ✅
1. Utilizing the cluster from Scenario 2, `Edit YAML`, and apply the following annotation:
```log
rke.cattle.io/delete-missing-custom-machines-after: '5s'
```
2. Observe orphaned machine objects terminate
3. Verified - cluster `active` and accurately reflects 1:1 ratio of nodes to machines; as expected

---

Scenario 5 - ✅
1. Fresh install of Rancher `v2.9-head`
2. Provision a downstream RKE2 custom cluster w/ k8s 1.29
3. Once `active`, take a snapshot
4. Delete a node and observe associated machine object with `NodeNotFound` status
5. `Edit YAML` and apply annotation, then upgrade k8s version to 1.30
6. Once cluster is upgraded and active, restore to snapshot
7. Verified - cluster successfully restores to snapshot, and is k8s 1.29 again
8. Once more, upgrade k8s version to 1.30
9. Verified - cluster successfully upgrades back to k8s 1.30; as expected

---

Scenario 6 - ✅
1. Fresh install of Rancher `v2.9-head`
2. Provision a downstream K3s custom cluster w/ k8s 1.29
3. Once `active`, take a snapshot
4. Delete a node and observe associated machine object with `NodeNotFound` status
5. `Edit YAML` and apply annotation, then upgrade k8s version to 1.30
6. Once cluster is upgraded and active, restore to snapshot
7. Verified - cluster successfully restores to snapshot, and is k8s 1.29 again
8. Once more, upgrade k8s version to 1.30
9. Verified - cluster successfully upgrades back to k8s 1.30; as expected

**Comment by Josh-Diamond** [comment] 2024-07-16 16:14
re-opening for further validation

**Comment by Josh-Diamond** [comment] 2024-07-16 23:53
Ticket #43686 - Additional Validation Results - ✅ 
---

| Scenario | Test Case | Result |
|---|---|---|
| 1. | Reproduce in `v2.8.0` w/ multiple nodes deleted => upgrade to `v2.9-head`, apply annotation + trigger cluster reconciliation | ✅ |
| 2. | Reproduce in `v2.9-head` => apply annotation, trigger cluster reconciliation, and observe orphaned machines removed => attempt to reproduce again w/ annotation applied | ✅ |
| 3. | Reproduce issue => apply fix => restore to snapshot + ensure nodes are not accidentally deleted | ✅ |
| 4. | Regression test RKE2 Node driver cluster | ✅ |

---

Scenario 1 - ✅ 
1. Fresh install of Rancher `v2.8.0`
2. Provision a downstream RKE2 custom cluster w/ 1 etcd/cp node and 4 worker nodes + k8s `v1.26`
3. Delete 3 of the 4 worker nodes and reproduce the issue
4. Upgrade Rancher to `v2.9-head`
5. Apply annotation and trigger cluster reconciliation, then observe orphaned machines are removed from Rancher
6. Verified - annotation successfully applied + orphaned machines are removed; as expected

---

Scenario 2 - ✅ 
1. Provision a downstream RKE2 custom cluster w/ 1 etcd/cp node and 3 worker nodes + k8s `v1.29`
2. Delete 1 of the 3 worker nodes and reproduce the issue
3. Apply annotation and trigger cluster reconciliation, then observe orphaned machine is removed from Rancher
4. Verified - annotation successfully applied + orphaned machine is removed; as expected
5. Delete another worker node, attempting to reproduce the issue
6. Issue reproduces but orphaned machine is cleaned up in 5s, as specified by annotations duration time; as expected

---

Scenario 3 - ✅ 
1. Fresh install of Rancher `v2.9-head`
2. Provision a downstream RKE2 custom cluster w/ k8s 1.29
3. Once active, take a snapshot
4. Delete a node and observe associated machine object with `NodeNotFound` status
5. `Edit YAML` and apply annotation, then upgrade k8s version to `1.30`
6. Once cluster is upgraded and active, restore to snapshot w/ `k8s + etcd` option selected
7. Verified - cluster successfully restores to snapshot, and is k8s 1.29 again; no nodes unintentionally deleted and no "ghost" machine objects seen.  Annotation is still applied; cluster is `active` and ready; as expected

---

Scenario 4 - ✅ 
1. Fresh install of Rancher `v2.9-head`
2. Provision a downstream RKE2 AWS Node driver cluster w/ k8s 1.29
3. Once `active`, take a snapshot
4. Once captured, scale the worker pool up
5. Verified - cluster successfully scales up
6. Scale the worker pool down
7. Verified - cluster successfully scales down
8. Upgrade the cluster to k8s `v1.30`
9. Verified - cluster successfully upgrades
10. Restore to snapshot taken in step 3
11. Verified - snap/restore successful, cluster is back to k8s `v1.29` + in an `active` state
12. Add the annotation to cluster yaml and ensure no nodes are unexpectedly deleted
13. Verified - annotation successfully applied; cluster is `active` and ready; no nodes are unexpectedly deleted; as expected

**Closed by Josh-Diamond** 2024-07-16 23:53 UTC
Labels: kind/bug, priority/0, QA/M, release-note, team/hostbusters, area/capi, area/capr

**Comment by riuvshyn** [comment] 2024-08-28 19:08
@Josh-Diamond @snasovich is that bug supposed to be fixed in 2.9.1?
I have just upgraded to 2.9.1 I still have same issue, when node on cloud provider is rotated machine still exists in `Nodenotfound` state. I was waiting for 10-15min and it didn't go away, I still can delete it manually as before but it is clearly not getting removed automatically as it used to be.

I have also tried to apply annotation `rke.cattle.io/delete-missing-custom-machines-after: '5s'` to machine resource in notfound state and nothing has changed resource is still there until I manually remove it. Even if adding annotation would work that is not a solution I guess as it is still a manual extra step just to clean up unneeded resources...

So can someone confirm how the fix is supposed to work?

**Comment by riuvshyn** [comment] 2024-08-28 19:14
<img width="1726" alt="image" src="https://github.com/user-attachments/assets/ef456119-5288-4269-8315-bff965718b0c">

This bug is exceptionally bad when it comes to rotating Control Plane nodes as Rancher won't start provisioning new Control plane node until old machine will be removed and since it can't be removed automatically provisioning new ControlPlane nodes gets stuck and require removing manually old machine after rotating every CP node.

**Comment by riuvshyn** [comment] 2024-08-28 20:00
Oh, I just realised that `rke.cattle.io/delete-missing-custom-machines-after: '5s'` annotation for the `cluster.provisioning.cattle.io` not for individual machine! Works as expected now with that annotation on a cluster. 🎉

**Comment by wenjo-dev** [comment] 2024-09-10 13:51
> Oh, I just realised that `rke.cattle.io/delete-missing-custom-machines-after: '5s'` annotation for the `cluster.provisioning.cattle.io` not for individual machine! Works as expected now with that annotation on a cluster. 🎉

Would you mind, explaining a little more in depth please as we're trying to implement this for some hours now and it just doesn't work.

- Where exactly do we need to add the annotation? In the cluster-config, or somewhere else?
- What exactly is the correct key/value-pair?
  key: cluster.provisioning.cattle.io      -     value: rke.cattle.io/delete-missing-custom-machines-after: '5s'  ?

You'd really help us out!

**Comment by Oats87** [comment] 2024-09-25 18:44
> > Oh, I just realised that `rke.cattle.io/delete-missing-custom-machines-after: '5s'` annotation for the `cluster.provisioning.cattle.io` not for individual machine! Works as expected now with that annotation on a cluster. 🎉
> 
> Would you mind, explaining a little more in depth please as we're trying to implement this for some hours now and it just doesn't work.
> 
> * Where exactly do we need to add the annotation? In the cluster-config, or somewhere else?
> * What exactly is the correct key/value-pair?
>   key: cluster.provisioning.cattle.io      -     value: rke.cattle.io/delete-missing-custom-machines-after: '5s'  ?
> 
> You'd really help us out!

This annotation must be added to the `clusters.provisioning.cattle.io/v1` object. `kubectl -n fleet-default annotate clusters.provisioning.cattle.io <cluster-name> rke.cattle.io/delete-missing-custom-machines-after=5s` in the local cluster

**Comment by jdbaudean** [comment] 2025-05-21 15:52
@Oats87 Is there a way to set that annotation in either the cluster.yaml or via Rancher UI?  I'd like to configure this when I build my clusters
