### ISSUE TITLE
Deleting and purging network agent causes docker to hang

### ISSUE THREAD

**Issue by withinboredom** [rancher/rancher#3491] opened 2016-02-02 07:32 UTC
Specifically it causes https://github.com/docker/docker/issues/5618

Apparently this is a kernel bug... 

To reproduce very reliably:
Create a vm of size `Standard D2 v2 (2 cores, 7 GB memory)`
Add two standard data disks of any size (I did two 1023gb disks -- azure only charges for actual data usage, not size allocated)
Drop this script in the home dir: https://github.com/clam-p/clam/blob/productionizing/stacks/server-go.sh

Run script as root (still pretty manual process):
``` bash
./server-go.sh http://url/from/add/host/in/rancher

# Select local only

# Scroll up to drop in uuid for fstab
```

Run some containers on the host. Delete and purge them all (including the network agent). Host will become unavailable and end up in a reconnecting state, foreverish.

**Comment by withinboredom** [comment] 2016-02-02 07:46
And it appears to be contagious, as now all the hardware nodes are exhibiting the same behavior. Excuse me while I go reboot all the things :|

**Comment by vincent99** [comment] 2016-02-02 16:00
[We know](https://github.com/docker/docker/issues/5618#issuecomment-67805464) and the network agent is particularly good at causing it because all it does is network traffic, but have no great ideas for fixing it at our level..

**Comment by deniseschannon** [comment] 2016-02-02 18:04
Duplicate of https://github.com/rancher/rancher/issues/931

**Closed by deniseschannon** 2016-02-02 18:04 UTC
