### ISSUE TITLE
Rancher v1.6.11, using the vxlan network, dashboard and CLI only show the first host added

### ISSUE THREAD

**Issue by hongxiaolu** [rancher/rancher#10400] opened 2017-11-27 12:24 UTC
**Rancher versions:**
rancher/server: v1.6.11
rancher/lb-service-rancher:v0.7.17
rancher/etc-host-updater:v0.0.3
rancher/k8s:v1.8.3-rancher2
rancher/kubectld:v0.8.5
rancher/kubernetes-auth:v0.0.8
rancher/dns:v0.15.3
rancher/kubectld:v0.8.5
rancher/scheduler:v0.8.2
rancher/healthcheck:v0.3.3
rancher/metadata:v0.9.5
rancher/net:v0.13.1
rancher/network-manager:v0.7.18
rancher/etcd:v2.3.7-13
rancher/agent:v1.2.7

**Docker version: (`docker version`,`docker info` preferred)**
1.12.3

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
Linux node2 4.4.0-77-generic #98-Ubuntu SMP Wed Apr 26 08:34:02 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
VirtualBox  VMware. Bare-metal

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
All

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**
Kubernetes

**Steps to Reproduce:**

1 . I manually created a new Kubernetes environment template, set up vxlan as a network driver, and built a new environment.
2. I first add a host, called NODE2, and then add NODE3, when all of the  stack running normally (all turned green), enter the dashboard view,only one host is displayed.
3. The kubectl get node is executed at CLI, and only one host is displayed. 

![1](https://user-images.githubusercontent.com/20707603/33264545-fe0ba19e-d3a8-11e7-8feb-90be26562a37.png)
![2](https://user-images.githubusercontent.com/20707603/33264558-0d689e30-d3a9-11e7-9ead-cf008173a9ef.png)

![3](https://user-images.githubusercontent.com/20707603/33264517-da6d8aa4-d3a8-11e7-802a-c15d0afbc821.jpeg)
![4](https://user-images.githubusercontent.com/20707603/33264518-de15d0b2-d3a8-11e7-9ec9-db7f1bf21ff2.png)

View the rancher-kubernetes-agent service log with the following log display:

2017/11/27 下午7:03:12time="2017-11-27T11:03:12Z" level=info msg="Connection established"
2017/11/27 下午7:03:12time="2017-11-27T11:03:12Z" level=info msg="Starting websocket pings"
2017/11/27 下午7:03:12time="2017-11-27T11:03:12Z" level=info msg="Received event: [ADDED] for Service: kube-system/kube-dns, Handling event."
2017/11/27 下午7:03:12time="2017-11-27T11:03:12Z" level=error msg="Error getting node: [node3] by name from kubernetes, err: [nodes \"node3\" not found]"
2017/11/27 下午7:03:12time="2017-11-27T11:03:12Z" level=error msg="Error getting node: [node3] by name from kubernetes, err: [nodes \"node3\" not found]"
2017/11/27 下午7:03:12time="2017-11-27T11:03:12Z" level=info msg="Received event: [ADDED] for Service: kube-system/tiller-deploy, Handling event."
2017/11/27 下午7:03:12time="2017-11-27T11:03:12Z" level=info msg="Received event: [ADDED] for Service: kube-system/monitoring-influxdb, Handling event."
2017/11/27 下午7:03:12time="2017-11-27T11:03:12Z" level=info msg="Received event: [ADDED] for Service: kube-system/monitoring-grafana, Handling event."
2017/11/27 下午7:03:13time="2017-11-27T11:03:13Z" level=info msg="Received event: [ADDED] for Service: kube-system/heapster, Handling event."
2017/11/27 下午7:03:13time="2017-11-27T11:03:13Z" level=info msg="Received event: [ADDED] for Service: kube-system/kubernetes-dashboard, Handling event."
2017/11/27 下午7:03:13time="2017-11-27T11:03:13Z" level=error msg="Error getting node: [node3] by name from kubernetes, err: [nodes \"node3\" not found]"
2017/11/27 下午7:03:13time="2017-11-27T11:03:13Z" level=error msg="Error getting node: [node3] by name from kubernetes, err: [nodes \"node3\" not found]"
2017/11/27 下午7:03:19time="2017-11-27T11:03:19Z" level=error msg="Error getting node: [node3] by name from kubernetes, err: [nodes \"node3\" not found]"
2017/11/27 下午7:03:19time="2017-11-27T11:03:19Z" level=error msg="Error getting node: [node3] by name from kubernetes, err: [nodes \"node3\" not found]"

**Expected result**

All the hosts should be displayed

**Results:**

Whether you add two hosts or three hosts or more hosts, only the first host is added

**Comment by superseb** [comment] 2017-11-27 13:07
Please check if this is not a duplicate of https://github.com/rancher/rancher/issues/10344

**Comment by sangeethah** [comment] 2017-11-30 19:12
Tested with rancher-server version - v1.6.12-rc1 using vxlan version -v0.3.1 which uses rancher/net:v0.13.1	 for cni-driver and rancher/net:v0.11.9 for vxlan-router.

When 3 hosts are added to kubernetes environment using vxlan,  all 3 hosts are listed as nodes. Able to deploy pods in all 3 hosts and cross communication between hosts work as expected.

**Closed** 2017-11-30 21:16 UTC
Labels: area/kubernetes, kind/question
