### ISSUE TITLE
Etcd restore does not work on a k8s 1.22 RKE1 cluster

### ISSUE THREAD

**Issue by sowmyav27** [rancher/rancher#35625] opened 2021-11-21 00:59 UTC
**Rancher Server Setup**
- Rancher version: 2.6-head commit id: `e322f8f`
- Installation option (Docker install/Helm Chart): Helm
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): RKE1
- Proxy/Cert Details: Rancher generated

**Information about the Cluster**
- Kubernetes version: 1.22.3-rancher1-1
- Cluster Type (Local/Downstream): Downstream RKE1 EC2 cluster 

**Describe the bug**
Etcd restore does not work on a k8s 1.22 RKE1 cluster

**To Reproduce**

- Deploy an RKE1 cluster using k8s 1.22.3rancher1-1
- Deploy a few resources on the downstream cluster
- Take a snapshot
- Restore to this snapshot (all options - 3rd option)
- The cluster keeps switching between `Active` and `Unavailable` state with message `Cluster agent is not connected`

**Note:**
This scenario worked. 
- Deploy an RKE1 cluster using k8s 1.21
- Deploy a few resources on the downstream cluster
- Take a snapshot s1
- Upgrade k8s to 1.22
- Restore to snapshot s1
- Cluster came up Active, and resources in the cluster are restored

Also this works on a DO and Azure cluster.
Fails on an EC2 cluster

**Comment by kinarashah** [comment] 2021-11-23 05:51
Worked with @sowmyav27 on reproducing this and few things to note: 
- So far haven't reproduced it on DO cluster, just ec2 node driver cluster. Need to try with custom clusters too. 
- Cluster switching states is an unrelated issue, it continues flapping between `active` and `unavailable` when cluster agent isn't deployed for the cluster. Happens sometimes after provisioning new cluster as well.  
- Cluster agent is stuck in a crash loop backoff state, also saw a few addons in a weird terminating/stuck state - unsure if they're related or different issues. Need to debug some more.

**Comment by kinarashah** [comment] 2021-12-03 19:44
Figured out the steps to reproduce - only happens when the cluster is restored to the very first snapshot right after cluster comes up Active.

**Comment by cbron** [comment] 2021-12-06 18:27
Having trouble reproducing again

**Comment by kinarashah** [comment] 2021-12-09 00:27
Both @sowmyav27 and I tried reproducing multiple times with `kinarashah/rancher:v2.6.3-rc4`, unable to reproduce. Moving this to test.

**Comment by sowmyav27** [comment] 2021-12-09 07:16
**On 2.6head commit id: `77392a6`**

- Deploy an RKE1 DO/AWS cluster
- Take a snapshot 
- Restore to the first taken recurring snapshot
- Cluster goes into Updating --> Unavailable and comes back Active.
- It does not switch between Unavailable and Active.

**Comment by slickwarren** [comment] 2022-01-06 00:08
I was also unable to reproduce this on 2.6-head (750b8a8):
* Deploy an RKE1 DO/ cluster (1.22.8-rancher1-1)
* Take a snapshot
* Restore to the first taken recurring snapshot
* Cluster goes into Updating --> Unavailable and comes back Active.
* It does not switch between Unavailable and Active. tried it multiple times (~10 times)

**Closed** 2022-01-06 00:11 UTC
Labels: kind/bug-qa, [zube]: QA Working, status/release-blocker, team/area2
