### ISSUE TITLE
Validate Docker 23.0.x

### ISSUE THREAD

**Issue by sbonds** [rancher/rancher#40417] opened 2023-02-03 14:47 UTC
**Is your feature request related to a problem? Please describe.**
Rancher "rke up" fails to install on the most recent Docker Community Edition release 23.0.0. The specific error is "Unsupported Docker version found [23.0.0]"

[Docker 23.0.0 Release Notes](https://docs.docker.com/engine/release-notes/23.0/)

**Describe the solution you'd like**
Rancher would install and work correctly on Docker 23.0.x like it does for 20.10.x. This is essentially a repeat of Issue #30406 but for Docker 23.0.x instead of 20.10.x

**Describe alternatives you've considered**
Staying on Docker 20.10.23.

SURE-5904

**Comment by vincebrannon** [comment] 2023-02-15 09:54
Created Jira for this request. SURE-5904

**Comment by snasovich** [comment] 2023-04-19 18:32
Closing it as a duplicate of https://github.com/rancher/rancher/issues/40731 (even though this one is older), let's track the updates there.

**Closed by snasovich** 2023-04-19 18:32 UTC
Labels: kind/enhancement, internal, team/area2, team/infracloud, JIRA
