### ISSUE TITLE
[BUG] Projects created via `kubectl` in downstream clusters are visible in local cluster as namespaces.

### ISSUE THREAD

**Issue by torchiaf** [rancher/rancher#44280] opened 2024-02-01 12:18 UTC
**Rancher Server Setup**
- Rancher version: 2.8.1
- Installation option: Helm, v1.26.10+k3s2, rke2

**Information about the Cluster**

local +1 Digital Ocean provider downstream cluster

**User Information**

Admin user

**Describe the bug**

1- When I create a project `foo` on a downstream cluster with kubectl/V1 endpoint -> The project is created and displaying as a project in Downstream cluster but it is also displaying the namespace `foo` in local cluster.

2- In case of `foo` project is created in the downstream, it's not possible to create a new namespace in local cluster, with the same name, the backend throws an error since the namespace `foo` already exists.

3- In case of a `foo` namespace exists in local cluster and the user creates a new project `foo` in the downstream, when the `foo` project is deleted, then the namespace `foo` in local cluster, which was existing before the test, is also deleted.

Related UI issue: https://github.com/rancher/dashboard/issues/9880

**To Reproduce**

2. Create downstream cluster
3. Create a project from kubectl/V1 endpoint
4. Copy the local cluster KUBECONFIG and export it on to terminal.
5.  Export the kubeconfig and run on local cluster
6.  `kubectl apply -f ~/create_project.yaml`

```
apiVersion: management.cattle.io/v3
kind: Project
metadata:
  name: foo
  namespace: c-4k7jp // downstream cluster-id
spec:
  clusterName: c-4k7jp // downstream cluster-id

```

**Result**

See description.

**Expected Result**

**Screenshots**

**Additional context**

**Comment by MbolotSuse** [comment] 2024-02-01 15:43
@maxsokolovsky  Can chime in here, but this is not a bug. When a project is created (for reference, all projects are created as `management.cattle.io/v3` Projects in the local cluster) a backing namespace is created for resources related to the project (i.e. `ProjectRoleTemplateBindings`). This is on-purpose, intentional behavior.

**Comment by torchiaf** [comment] 2024-02-02 10:14
> @maxsokolovsky Can chime in here, but this is not a bug. When a project is created (for reference, all projects are created as `management.cattle.io/v3` Projects in the local cluster) a backing namespace is created for resources related to the project (i.e. `ProjectRoleTemplateBindings`). This is on-purpose, intentional behavior.

HI @MbolotSuse , please, correct me if i'm wrong, but the backing namespace is created using a generated id like `p-*`; and this is usefull to avoid conflicts with namespaces manually created by users and allow UI to filter out them in the Namespace list.
In this case the backing namespace is create with the same name of the Project, I think this is at the origin of the conflicts on the UI.

**Comment by maxsokolovsky** [comment] 2024-02-02 14:43
@torchiaf, I wonder if it's because the Project name itself was the exact "foo" and not generated with `p-*`. Thus Rancher just uses its actual `metadata.name` for the backing namespace name.

**Comment by MbolotSuse** [comment] 2024-02-02 15:02
@torchiaf 

> but the backing namespace is created by rancher, using a generated id like p-* when new projects are created using the UI; 

This is incorrect. The backing namespaces for a project are always created using the `metadata.name` of the backing project. Keep in mind that projects created using Norman have a customization applied to them - the `name` in the norman request corresponds to the `displayName` of the project, and the `id` corresponds to the `metadata.name`. However, when using steve or the Rancher Kubernetes API to create resources, users need to specify these values correctly themselves. We do not intend on adding any customization here to mimic norman's behavior.

To give a practical example, here's a request to create a project using norman (`/v3/projects`):
```json
{
  "type": "project",
  "name": "example",
  "clusterId": "local",
}
```

You can create this same project through Steve (`v1/management.cattle.io.projects`) with the following:
```json
{
    "apiVersion": "management.cattle.io/v3",
    "kind": "Project",
    "metadata": {
        "generateName": "p-",
        "namespace": "local"
    },
    "spec": {
        "clusterName": "local",
        "displayName": "example"
    }
}
```

> where the old namespace is deleted when the project is deleted in downstream cluster

I apologize for nitpicking you on this point, but I want to be very clear on this item - projects do not exist in the downstream cluster. They exist inside of the local cluster - in the namespace for the cluster that they are targeting. Namespaces in the remote have a label that correlates them with a project, but the project does not exist in the downstream cluster.

As far as the backing namespace is being deleted, that too I would expect. My first guess on looking through the code is that you can find the relevant sections for creating the namespace [here](https://github.com/rancher/rancher/blob/4f6341addff89c1f090563643ba831eb9c1b87ba/pkg/controllers/management/auth/project_cluster_handler.go#L79), and deleting the namespace [here](https://github.com/rancher/rancher/blob/4f6341addff89c1f090563643ba831eb9c1b87ba/pkg/controllers/management/auth/project_cluster_handler.go#L149).

**Comment by MbolotSuse** [comment] 2024-02-02 19:00
Closing this issue, Rancher is functioning as intended.

**Closed by MbolotSuse** 2024-02-02 19:00 UTC
Labels: kind/bug
