### ISSUE TITLE
Continuous Delivery not working with http repository not using SSL

### ISSUE THREAD

**Issue by lucabarze-suse** [rancher/rancher#36594] opened 2022-02-22 10:08 UTC
**Rancher Server Setup**
- Rancher version: 2.6.3

**Information about the Cluster**
- Cluster Type (Local/Downstream): local

**User Information**
- What is the role of the user logged in? Admin
   
**Describe the bug**
It is not possible to create a Git repo without SSL certificates.

**To Reproduce**
Install a Rancher server and try to create a new git repo within Continuous Delivery application, then create an `http://` url.

**Result**
Everything in the _GIT Repo: Create_ page starting from _TLS Certificate Verification_ until the end of the page disappears.

**Expected Result**
Only the section related to _TLS Certificate Verification_ should disappears when using http instead of https.

**Screenshots**

<img width="1232" alt="http_repo" src="https://user-images.githubusercontent.com/95303943/155109882-b3ab4e77-2216-40a2-8a52-caa971e551bb.png">
<img width="1237" alt="https_repo" src="https://user-images.githubusercontent.com/95303943/155109905-dd233116-9da5-436a-85e6-03ba9ef86df1.png">

Thank you!

**Comment by richard-cox** [comment] 2022-02-23 11:09
Closing as duplicate of https://github.com/rancher/dashboard/issues/4830

**Closed by richard-cox** 2022-02-23 11:09 UTC
