### ISSUE TITLE
Upgrade_strategy in rancher-compose.yml does'nt seem to be "saved"

### ISSUE THREAD

**Issue by cabrinoob** [rancher/rancher#9144] opened 2017-06-23 09:52 UTC
**Rancher versions:**
Rancher    v1.5.8
Cattle    v0.178.11
User Interface    v1.5.9
Rancher CLI    v0.5.3
Rancher Compose    v0.12.5

**The bug:**
My problem is that when I create a new stack with this upgrade strategy in the rancher-compose :

    upgrade_strategy:
        start_first: true

When I get back the docker-compose.yml and the rancher-compose.yml from API, this option has not been saved in it.

I'am using **/v2-beta/stacks/id/composeconfig** url to get a zip file containing the docker-compose and the rancher-compose files into my jenkins Job. When I look into the rancher-compose.yml, I cannot find the upgrade_strategy property declared earlier.

Is it a bug?

Thank you

**Comment by joshwget** [comment] 2017-06-23 19:29
Yes, likely a bug. Thanks for filing.

**Comment by StrongMonkey** [comment] 2017-06-23 22:31
I don't think startFirst is part of service API field. We need to save that on service.launchConfig and the service export would work.

**Comment by joshwget** [comment] 2017-06-24 00:54
@StrongMonkey Looks like it might be part of the service API on master (https://github.com/joshwget/go-rancher/blob/du/v2/generated_service.go#L84).

**Comment by StrongMonkey** [comment] 2017-06-24 01:06
@joshwget yeah, I saw that on master too. But for 1.6 looks like its in `service.upgrade.startFirst`  and only `upgrade` field shows up after service is upgraded.

**Comment by ekristen** [comment] 2017-11-30 16:22
I can confirm this bug.

**Comment by ThomasDonath** [comment] 2018-05-04 09:58
I have filed the same problem as #13295. Any suggestions when a fix will be available?

**Comment by matthias-kloeckner** [comment] 2018-07-25 08:17
is there any chance this will be fixed in any rancher 1.6.xx version?

**Comment by deniseschannon** [comment] 2018-08-27 18:52
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.

**Closed by deniseschannon** 2018-08-27 18:52 UTC
Labels: kind/bug, priority/-1, version/1.6
