### ISSUE TITLE
Timeout issues with helm after upgrading to 2.2.4-rc2

### ISSUE THREAD

**Issue by akkie** [rancher/rancher#20289] opened 2019-05-16 11:32 UTC
**What kind of request is this (question/bug/enhancement/feature request):**
bug

**Steps to reproduce (least amount of steps as possible):**
* Upgrade to Rancher 2.2.4-rc2
* Try to install or upgrade a helm chart

**Result:**
```
Failed to install app cluster-monitoring. Error: UPGRADE FAILED: Get https://localhost:443/k8s/clusters/c-9nd4d/api/v1/namespaces/cattle-prometheus/configmaps?labelSelector=NAME%!D(MISSING)cluster-monitoring%!C(MISSING)OWNER%!D(MISSING)TILLER%!C(MISSING)STATUS%!D(MISSING)DEPLOYED: dial tcp 10.0.15.1:443: i/o timeout
```

**Other details that may be helpful:**
* 2.2.3-rc9 fails also
* If I switch back to 2.2.3-rc4, 2.2.3-rc5, 2.2.3-rc6, 2.2.3-rc7 or 2.2.3-rc8 it works as expected

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI):  2.2.4-rc2
- Installation option (single install/HA): single docker install

**Comment by bmdepesa** [comment] 2019-05-16 21:50
This was a problem with system-charts branch being incorrect in `v2.2.4-rc2`. 

Deploying apps and enabling cluster monitoring works correctly in `v2.2.4-rc5`.

**Comment by cjellick** [comment] 2019-05-16 22:25
can we close this issue @bmdepesa ?

**Comment by akkie** [comment] 2019-05-17 05:38
For me the issue remains with v2.2.4-rc5. In my opinion, the issue isn't monitoring specific. We had already used the `dev` branch of the system-charts library.

The issue occurs also for every other chart I try to install:
```
Failed to install app aerospike. Error: UPGRADE FAILED: Get https://localhost:443/k8s/clusters/c-9nd4d/api/v1/namespaces/aerospike/configmaps?labelSelector=NAME%!D(MISSING)aerospike%!C(MISSING)OWNER%!D(MISSING)TILLER%!C(MISSING)STATUS%!D(MISSING)DEPLOYED: dial tcp 10.0.15.1:443: i/o timeout
```

**Comment by bmdepesa** [comment] 2019-05-17 16:33
@akkie can you give more details on your installation? I am not able to reproduce this at all. Any app (including from system-charts) installs and operates fine in my v2.2.4-rc5 setup.

**Comment by bmdepesa** [comment] 2019-05-17 19:44
* Fresh install of 2.2.3-rc8
  * Changed system-charts to use `dev` branch
  * Enabled cluster monitoring
  * Deployed `docker-registry` and `wordpress` apps
* Upgrade to 2.2.4-rc5
  * Cluster monitoring is still functional
  * Upgraded `docker-registry` and `wordpress` apps
  * Deployed new `mongodb` app
  * Rolled back `docker-registry` and `wordpress` apps
* Downgrade to 2.2.3-rc9
  * Deployed new `docker-registry` app
* Fresh install of 2.2.3-rc9
  * Attempt to deploy new `docker-registry` app - fails due to system-charts branch
  * Change system-charts branch to dev
  * Deploy new `docker-registry` app
  * Deploy new `wordpress` app

All of the above was performed on EC2 RKE clusters in single-node Rancher installs.

**Comment by davidnuzik** [comment] 2019-05-20 18:08
I was asked to test as well with the following scenarios.

**v2.2.3 -> v2.2.4-rc2 upgrade (single-node rancher)**
- Install single-node rancher v2.2.3, enable Helm Stable, add a custom helm chart, deploy a DigitalOcean cluster.
- Enable cluster monitoring on the DO cluster
- Deploy a couple of apps (project level) such as `grafana` (from my custom helm chart), `aerospike` (helm stable), and `docker-registry` (Rancher Library) on the DO cluster

- Upgrade the single-node rancher to v2.2.4-rc2, change `system-library` catalog to `dev` branch
- Confirm monitoring is working _(no issues)_
- Upgrade each app _(no issues)_
- Try installing some other apps from each catalog _(no issues)_

**v2.2.4-rc2 fresh install (single-node rancher)**
- Install single-node rancher v2.2.4-rc2 (fresh install), enable Helm Stable, add a custom helm chart, deploy a DigitalOcean cluster.
- Change `system-library` catalog to `dev` branch.
- Enable cluster monitoring on the DO cluster _(no issues)_
- Deploy a couple of apps (project level) such as `grafana` (from my custom helm chart), `aerospike` (helm stable), and `docker-registry` (Rancher Library) on the DO cluster _(no issues)_
- Upgrade each app _(no issues)_


_Perhaps we're missing something. For example we are testing essentially with default RKE clusters (Canal network provider, k8s v1.13.5, etc -- nothing special). Maybe our clusters differ slightly or something else is different with our environments we are testing with_

_Possibly Related??_ (not sure, just trying to help)
https://stackoverflow.com/questions/53085993/helm-reset-error-ownerdmissingtiller-dial-tcp-10-96-0-1443-i-o-timeout
https://serverfault.com/questions/931061/helm-i-o-timeout-kubernetes

**Comment by orangedeng** [comment] 2019-05-24 06:11
@davidnuzik Try to setup Rancher in ubuntu in GCE. I can reproduce this problem with GCE setup 100%. This problem would happen the docker default dns resolver is not accessible and the `/etc/hosts` doesn't exist in the *jailer*. So the rancher container can not resolve the hostname `localhost` to `127.0.0.1`.

**Comment by bmdepesa** [comment] 2019-05-24 17:13
I am able to reproduce after installing Rancher in GCE.

**Comment by bmdepesa** [comment] 2019-06-13 21:45
rancher/rancher:master 8e04837c

* Create cluster
* etc/hosts is present in jail
* Deploy app
* Upgrade app
* Rollback app
* Delete app

**Comment by troy256** [comment] 2019-06-18 15:24
Issue is 100% repeatable on Rancher v2.2.5-rc5 and v2.2.4.  Version v2.2.3 does not have the issue.  This is for on-prem.  The issue is that the container is unable to resolve localhost to 127.0.0.1.

**Comment by bmdepesa** [comment] 2019-06-18 16:20
@troy256 can you provide more details on your environment? Which OS for Rancher Server and your nodes, and what type of clusters?

**Comment by troy256** [comment] 2019-06-18 16:52
Rancher Server and cluster nodes are all on-prem VMware VMs running Ubuntu 18.04 LTS.  Deploying any Catalog app from the provided Rancher Library, or any chart from anywhere, generates an error like this:

`Failed to install app fluentd-aggregator. Error: UPGRADE FAILED: Get https://localhost:443/k8s/clusters/c-qj9d4/api/v1/namespaces/fluentd-aggregator/configmaps?labelSelector=NAME%!D(MISSING)fluentd-aggregator%!C(MISSING)OWNER%!D(MISSING)TILLER%!C(MISSING)STATUS%!D(MISSING)DEPLOYED: dial tcp 10.63.128.205:443: connect: connection refused`   

The problem seems to be that it is attempting to resolve "localhost" and going out to DNS which is returning a non 127.0.0.1 address.  This is new behavior which we don't see in v2.2.3.

**Comment by cjellick** [comment] 2019-06-19 17:19
@troy256 what does your /etc/resolv.conf look like inside the rancher-server container?

Also, from inside the container, can you do an `nslookup localhost`?

you'll need to install it first with
```
apt-get update
apt-get install dnsutils -y
```

**Comment by troy256** [comment] 2019-06-19 17:28
/etc/resolv.conf inside the rancher-server container:
nameserver x
nameserver y
nameserver z

(Where x, y and z are valid IP addresses of DNS servers inside our firewall)

"nslookup localhost" returns that non-127.0.0.1 address.

I'm curious why /etc/host.conf inside rancher-server has:
order hosts,bind

And /etc/hosts inside the rancher-server container has:
127.0.0.1       localhost

So why isn't it using /etc/hosts to resolve localhost first?  Instead it seems to be going out to DNS which is returning an address.

**Comment by cjellick** [comment] 2019-06-19 17:38
@troy256 are on our slack channel? I think i know what the problem is and I'd like to debug it with you

**Comment by cjellick** [comment] 2019-06-19 18:58
Root cause: when creating the jail, we are not pulling in /etc/nsswitch.conf, so when helm goes to resolve the localhost hostname, it goes out to a dns server and that dns server happens to have an actual entry for localhost.

**Comment by cjellick** [comment] 2019-06-19 23:02
for upgrade, i think you are hitting a different issue, described here:
https://github.com/rancher/rancher/issues/20699#issuecomment-499608298
with a workaround described here:
https://github.com/rancher/rancher/issues/20699#issuecomment-499620516

**Comment by bmdepesa** [comment] 2019-06-20 18:29
rancher/rancher:release-v2.2

Using `wordpress` app to test, I am able to see `nsswitch.conf` present in both cluster and app jails.

* Create cluster
* `/opt/jail/<cluster>/etc/nsswitch.conf` is present
* `while true; do ls /opt/jail/wordpress/etc/; done;`
* Deploy wordpress app
* `/opt/jail/wordpress/etc/nsswitch.conf` is present

**Comment by mwatche** [comment] 2019-06-21 05:09
I tested with release-v2.2 and it runs for me.
I cannot test the workaround, because i cannot fid the file /usr/bin/jailer.sh on my rancher-master-server or on one of my rancher-node-server.

**Closed** 2019-06-21 16:26 UTC
Labels: [zube]: To Test, internal, kind/bug-qa, team/az, team/cn
