### ISSUE TITLE
First Digital Ocean deployment fails.

### ISSUE THREAD

**Issue by keyscores** [rancher/rancher#1585] opened 2015-07-20 00:14 UTC
Digital ocean new host is failing instantly. As soon as you add the first host it says: "almost there..." while ordinarily there was a 'Setting up machine' for a few minutes. Note that no vm was created on digital ocean. So I'm guessing it failed before it could contact digital ocean, and 'almost there' matches an internal "null" state. (Subsequent hosts are added sucessfully).
As a first fix, I would suggest more verbose error messages.

Steps that can reproduce:
1. New rancher/server instance (ubuntu)
2. Front page wizard >  "add your first host"
3. Added digital ocean credentials > ok
4. Infrastructure page displays: "Almost there waiting for agent connection".
https://www.dropbox.com/s/5r43muyu4oze8ne/Screenshot%202015-07-19%2020.05.45.png?dl=0
No VMs were created on Digital Ocean.

**Comment by deniseschannon** [comment] 2015-07-20 04:35
@keyscores This is due to the delay that occurs before go-machine-service is ready. If you try again to add another host, it'll come up. https://github.com/rancher/rancher/issues/203

**Comment by keyscores** [comment] 2015-07-20 16:13
Yes I see that it works when you try again. This is a UI issue. I think you need the correct user feedback in this case. At least provide an error.

**Comment by deniseschannon** [comment] 2015-07-20 17:17
I'll close this one as it's a duplicate of #203.

**Closed by deniseschannon** 2015-07-20 17:17 UTC
