### ISSUE TITLE
underscore in service name causes stack to get stuck in activating

### ISSUE THREAD

**Issue by cjellick** [rancher/rancher#3697] opened 2016-02-25 22:46 UTC
Steps to Reproduce: 
Create a stack using this yaml:
```
foo_bar:
  image: nginx    
```
Results: 
Stack is stuck in activating. Message is `Bad response statusCode [422]. Status [422 status code 422]. Body: [code=InvalidCharacters, fieldName=name] from [http://192.168.1.5:8080/v1/projects/1a5/services]`
Expected:
Validation should catch this as an error (I guess)

**Comment by alena1108** [comment] 2016-03-07 23:57
@prachidamle as you are working on service.name validation, could you also check this issue?

**Comment by prachidamle** [comment] 2016-03-17 05:35
@vincent99 is this a UI issue? I see that API is throwing the validation error 422 when I try to create a service containing underscore in the name using the API UI.

I also see this error thrown when creating services using rancher-compose or even in  integration py tests.
<img width="1439" alt="service_with_underscore" src="https://cloud.githubusercontent.com/assets/1470602/13837338/5ef5c3d4-ebc7-11e5-8080-9a253e174f1f.png">

**Comment by vincent99** [comment] 2016-03-17 06:21
No?  If underscore isn't allowed the field should have invalid/validCharsin the schema.  And in any case the state shouldn't get stuck activating no matter what the UI sends.

**Comment by prachidamle** [comment] 2016-03-17 17:33
This bug has the same root cause as this issue https://github.com/rancher/rancher/issues/3950

Stack is stuck in activating when the compose yaml is invalid.

**Comment by prachidamle** [comment] 2016-03-17 17:33
@deniseschannon this is duplicate of https://github.com/rancher/rancher/issues/3950

**Comment by deniseschannon** [comment] 2016-03-17 17:38
Closed in favor of #3950

**Comment by prachidamle** [comment] 2016-03-17 17:38
Also, @alena1108 mentioned this is probably a rancher-compose issue

**Closed by deniseschannon** 2016-03-17 17:38 UTC
Labels: area/service, kind/bug, status/duplicate

**Comment by joshwget** [comment] 2016-03-17 17:50
This should be fixed when docker/libcompose#99 is merged and Rancher Compose is updated
