### ISSUE TITLE
Cannot add node labels to imported k3s or rke nodes

### ISSUE THREAD

**Issue by davidnuzik** [rancher/rancher#23840] opened 2019-11-01 21:44 UTC
Rancher v2.3.2
Rancher v2.2.x (pre-existing issue)

**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
- Import a k3s cluster (in my case v0.10.1 k3s) into Rancher using the UI
- Edit node and add a label

**Result:**
Label is never added.

**Expected Result:**
Label should be added to the node(s).

**Other details that may be helpful:**
Seems to have worked in an older v2.3 release

**Comment by davidnuzik** [comment] 2019-11-05 17:04
NOTE: This is also the case with an imported RKE cluster; this makes me think that perhaps for any imported cluster we cannot apply node labels.

If this is expected, then we should perhaps consider hiding this ability in the Rancher UI for imported clusters.

**Comment by Leen15** [comment] 2019-11-12 17:16
@davidnuzik why it's not possible to add/edit/delete labels?
We did it in last versions and it's a MUST HAVE feature because we use them for scheduling workloads!

**Comment by davidnuzik** [comment] 2019-11-12 17:51
With k3s node labels/taints need to be applied at runtime i.e. when you first install k3s on the nodes. They are not modifiable once the node is up.

**Comment by Leen15** [comment] 2019-11-12 17:57
One month ago I created a cluster with lots of nodes with k3s and I added multiple of labels on them, from Rancher UI, with the previous version.
I also have 2 RKE clusters on Rancher from 1 year and i changed multiple times labels on nodes.
Now with the last version 2.3.2 I cannot edit none of them.

**Comment by davidnuzik** [comment] 2019-11-12 18:31
It looks like the k3s docs are incorrect; node labels can be set post-install (and thus I will create an docs issue to fix k3s docs). I'm going to change this to a bug-type issue as it does indeed seem like something is broken here.

Thanks for the input

**Comment by Leen15** [comment] 2019-11-12 18:36
I hope this will be fixed asap, it's very important for us.
Thanks!

**Comment by davidnuzik** [comment] 2019-11-13 18:38
Looks like for imported clusters this has been an issue since v2.2.x (pre-existing issue).

**Comment by wc-matteo** [comment] 2019-11-14 08:31
Same for me. I cannot add/edit/delete node labels through rancher. Using `kubectl` is fine, though.

**Comment by Leen15** [comment] 2019-11-14 09:23
I can confirm that using a command like:
`k3s kubectl label nodes <node-name> foo=bar --overwrite`
It works fine!

**Comment by aaronRancher** [comment] 2019-11-27 18:57
This bug is reproduced in `rancher\rancher:v2.3.2` for k3s

Import a k3s cluster (Tested with `v1.16.3-k3s.2`)
Edit node and add label.
Label is never added.
![Screen Shot 2019-11-27 at 10 48 46 AM](https://user-images.githubusercontent.com/57409052/69750305-ad69ee80-1109-11ea-9b3d-13dd8c633fec.png)
![Screen Shot 2019-11-27 at 10 48 56 AM](https://user-images.githubusercontent.com/57409052/69750311-b1960c00-1109-11ea-9ed9-2e6ff33d1571.png)

The label can be added in rke nodes.
![Screen Shot 2019-11-27 at 11 18 14 AM](https://user-images.githubusercontent.com/57409052/69750317-b6f35680-1109-11ea-9c88-b994f5afaa8d.png)


The bug fix is validated in `rancher\rancher:master-head `version 902c8ba19`.

Labels can be added in k3s nodes.
![Screen Shot 2019-11-27 at 11 55 13 AM](https://user-images.githubusercontent.com/57409052/69751779-05eebb00-110d-11ea-8f72-f518dbcfc118.png)
![Screen Shot 2019-11-27 at 11 55 27 AM](https://user-images.githubusercontent.com/57409052/69751786-08511500-110d-11ea-9d9f-c4df5baf749d.png)

Labels can be added in rke nodes.
![Screen Shot 2019-11-27 at 11 56 31 AM](https://user-images.githubusercontent.com/57409052/69751789-09824200-110d-11ea-9cc1-1c4aed38bfe9.png)
![Screen Shot 2019-11-27 at 11 56 41 AM](https://user-images.githubusercontent.com/57409052/69751793-0be49c00-110d-11ea-994b-16f68131492d.png)

**Closed by aaronRancher** 2019-11-27 18:57 UTC
Labels: [zube]: To Test, kind/bug, team/ca
