### ISSUE TITLE
Improve error message when adding EKS cluster with invalid AMI

### ISSUE THREAD

**Issue by jiaqiluo** [rancher/rancher#16786] opened 2018-11-29 21:54 UTC
**What kind of request is this (question/bug/enhancement/feature request):**
Enhancement & Bug

Rancher: master on 11/29

Steps:
Add an Amazon EKS cluster with a wrong AMI role (at the `Custom AMI override` filed)

![screenshot](https://user-images.githubusercontent.com/6218999/49254437-6bb74280-f3e6-11e8-9869-be818051aa5e.png)

Result:

Failed to provision the cluster, the UI shows the error: 
```
Error creating stack: stack failed to create: reason unknown
```

![screenshot](https://user-images.githubusercontent.com/6218999/49184809-870a4b00-f31d-11e8-83bd-26a02626e85f.png)

Rancher's log shows this error:
```
[ERROR] ClusterController c-wpsbk [cluster-provisioner-controller] failed with : error creating stack: stack failed to create: reason unknown
W1128 21:53:07.945215       7 reflector.go:270] github.com/rancher/norman/controller/generic_controller.go:175: watch of *v1.Event ended with: The resourceVersion for the provided watch is too old.
```

The EKS cluster is active on AWS console even though the IAM role is invalid.

Finally, if I delete the rke cluster from Rancher, **the actual cluster on AWS will NOT be deleted**.

(see the cluster named "eks"  )
<img width="1593" alt="screenshot" src="https://user-images.githubusercontent.com/6218999/49184907-bfaa2480-f31d-11e8-89fe-53b6d9134231.png">

**Comment by maxkorp** [comment] 2018-11-29 22:07
The cause of this is that when an invalid AMI is used, cloudformation does not emit a CREATE_FAILED event. Instead the eventreason is tied to the ROLLBACK_IN_PROGRESS event. To fix, we just need to account for ROLLBACK_IN_PROGRESS in the stack-creation-error-handling logic, preferably with CREATE_FAILED still taking priority.

**Comment by maxkorp** [comment] 2018-11-29 22:20
https://github.com/rancher/kontainer-engine/pull/103

**Comment by jiaqiluo** [comment] 2018-12-31 18:32
Failed to validate on master 12/21

Steps are the same as the original ticket described.

Results:
 1.  :white_check_mark: the error message in Rancher provided meanful information.
<img width="1406" alt="screenshot" src="https://user-images.githubusercontent.com/6218999/50565645-386e1900-0cee-11e9-8bcf-e1ccbe1d1d6a.png">
<img width="1436" alt="screenshot" src="https://user-images.githubusercontent.com/6218999/50565647-3a37dc80-0cee-11e9-9480-928bbd1553a6.png">

2. :x: The corresponding eks cluster was not deleted after deleting it from Rancher. 
<img width="1586" alt="screenshot" src="https://user-images.githubusercontent.com/6218999/50565702-b6322480-0cee-11e9-9a4e-8e8f20a13d83.png">

@cjellick @maxkorp

**Comment by cjellick** [comment] 2019-01-12 20:07
@jiaqiluo why is this "wont fix"?

**Comment by deniseschannon** [comment] 2019-01-13 00:39
@jiaqiluo let's create a separate issue for the fact that the EKS cluster wasn't deleted as that is not in the original title of the issue. let's close this issue for the original title of this issue

**Comment by jiaqiluo** [comment] 2019-01-14 16:07
@cjellick  I think I just used the label `wontfix` wrong. Sorry for the confusion. 
@deniseschannon  Sure, I will do that.

**Closed** 2019-01-14 16:19 UTC
Labels: area/eks, kind/bug-qa, kind/enhancement, priority/1, status/resolved, status/to-test, team/az, version/2.0
