### ISSUE TITLE
Stack Name in Template Variable

### ISSUE THREAD

**Issue by hendryluk** [rancher/rancher#4478] opened 2016-04-20 00:36 UTC
Is it in any way possible to refer to the stack name from a catalog template via ${} substitution?

**Comment by deniseschannon** [comment] 2016-04-21 20:45
I'm not exactly sure your use case, but Rancher automatically creates a label on containers called `io.rancher.stack.name: <stack_name>`. You can use 

```
io.rancher.stack.name=$${stack_name}
io.rancher.stack_service.name=$${stack_name}/$${service_name}
```

Here's the docs (scroll down to Service Name section (there's no header for it)).
http://docs.rancher.com/rancher/rancher-compose/scheduling/#finding-hosts-with-container-labels

Here's an example that uses it in a template. 
https://github.com/rancher/community-catalog/blob/master/templates/elasticsearch/1/docker-compose.yml

**Comment by hendryluk** [comment] 2016-04-22 06:56
I didn't mean for labels. I intend to use the substitution for environment variables within my application.
Basically I need a name to identify each instance of my application (for specific routing rules). This application is instantiated from our private catalog. 
I can of course ask the user for this name via a catalog question (e.g. "Please specify a name"), but since we're already asking for a stack identification already (aka rancher's stack name), it seems appropriate if I could use this stack name to populate environment variable within my application.
I was thinking something like this:
docker-compose.yml

```
my_app:
  environment:
    SERVICE_NAME: xxx_${STACK_NAME}
  image: xxx
```

**Comment by vincent99** [comment] 2016-04-27 21:59
`${environment_name}` would be nice too if easy.

There will be a somewhat weird distinction between `$${stack_name}` (a string passed to the scheduler which ends up evaluating to the *current* name of the stack) vs `${stack_name}` (a variable in the yaml that gets interpreted *once on create* and replaced with the *initial* name of the stack, but is not updated if the stack is renamed)

**Comment by adnan-panalytics** [comment] 2016-09-08 12:46
What I expected from $${stack_name} was the stack name to be substituted when the container is run, but the label remains as below for the elasticsearch datanodes container: 
Affinity 	io.rancher.scheduler.affinity:container_label_ne 	
io.rancher.stack_service.name=${stack_name}/${service_name} 

The ${stack_name}/${service_name} doesn't seem to be replaced. Even after all the containers are running. I don't know if this is the intended behaviour. But yes, what I would also like here as @vincent99  and @hendryluk stated, is some form of internal variable which can be used to set the stack name and service name as an environment variable. This is very important for identifying containers with the same service scaled to a big number (OR) multiple stacks with the same service. And I am aware that the metadata service can do this, but this is an extra overhead to write a bash script just to download curl and set these variables (and also need to change the Dockerfile, so that this script is executed before the others meaning its not possible to use images directly from Docker Hub).

**Comment by dirosden** [comment] 2016-10-05 19:57
Hi, Would like to know if this is achievable in some form on v1.1.4. I have a salt-minion running within the container. I would like to give the minion a unique ID based on the Container UUID, Stack and Service. Idea is to ensure no two minions get the same identifier when seen from the master. Knowing fully well, I am mutating the container, is this possible today?

**Comment by ahmet2mir** [comment] 2017-01-16 16:50
Would be nice. Another use case: if user A create volume `myvol` in a stack and user B `myvol`, volumes are shared between A containers and B containers.

I prefer to create a volume with a stackname $stackname_myvol to seperate the logic view.

**Comment by will-chan** [comment] 2017-02-06 23:44
Closing this and using #3393 to track this.

**Closed by will-chan** 2017-02-06 23:44 UTC
Labels: kind/feature
