### ISSUE TITLE
Scheduling based on key with empty value

### ISSUE THREAD

**Issue by andyshinn** [rancher/rancher#2795] opened 2015-11-24 05:18 UTC
I'm trying to schedule several services across hosts with some hosts sharing multiple services while others just one. It would seem the simplest way to do this is just have a host label for the name of the server and specify the constraint for `affinity:host_label`.

What I am currently doing is something like `service1=true` and `service2=true`. But it would be nice to just specify the keys (`io.rancher.scheduler.affinity:host_label: service1`). Though, this doesn't seem to work (service just sits in "Starting"). Not sure if this should already be working and is a bug or if this is a feature request.

**Comment by deniseschannon** [comment] 2015-11-24 05:32
This would be a duplicate of https://github.com/rancher/rancher/issues/2601

Essentially, you'd be able to use the accepted formats for selector labels as scheduling rules.

**Closed by deniseschannon** 2015-11-24 05:32 UTC

**Comment by andyshinn** [comment] 2015-11-24 05:51
Ah, thanks!
