### ISSUE TITLE
K8s inter-host connectivity issues after upgrade from rancher v1.5.6 to v1.6.6-rc6

### ISSUE THREAD

**Issue by moelsayed** [rancher/rancher#9519] opened 2017-07-30 18:50 UTC
**Rancher versions:**
rancher/server: v1.6.6-rc6
rancher/agent:

**Infrastructure Stack versions:**

network-services: rancher/network-manager:v0.7.6
kubernetes (if applicable): rancher/k8s:v1.5.4-rancher1-4

**Docker version: (`docker version`,`docker info` preferred)**

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
Host-1: ubuntu 14.04
Host-2: RHEL 7.3/Native docker
**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
Isolated planes setup. Single node rancher.

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**
k8s
**Steps to Reproduce:**
* Install Rancher v1.5.7
* Create a k8s environment
* Upgrade to Rancher v1.6.6-rc6
* Upgrade Network-services, ipsec, healthcheck
* Create some pods, services, and ingress controllers. 

**Results:**
Pods on Host-1 are unable to reach Pods on Host-2. This manifested as an ingress-lb pod on Host-1 unable to reach the service endpoint on Host-2. Further testing showed all container on Host-1 can't reach Host-2.

Containers on Host-2 are able to successfully reach Host-1!

**Comment by leodotcloud** [comment] 2017-07-31 17:58
Same root cause as: https://github.com/rancher/rancher/issues/9389

**Comment by leodotcloud** [comment] 2017-07-31 23:03
As part of the fix for: #8684 (related PRs: rancher/cattle#2760, rancher/cattle#2766), the metadata started having information about stopped containers. The problem here is due to `conntracksync` trying to fix the entries with the "stopped" upgrade containers.

**Comment by moelsayed** [comment] 2017-07-31 23:37
We hit a related [case](https://github.com/rancher/rancher/issues/9519#issuecomment-319221050) with the following infrastructure services:
rancher/metadata:v0.9.2
rancher/network-manager:v0.7.6
rancher/k8s:v1.5.4-rancher1-4
rancher/net:v0.11.5

**Comment by leodotcloud** [comment] 2017-07-31 23:45
Notes:
- build containers `map[hostIP:hostPort/protocol]` but only for running/starting containers
- Read conntrack entries, build the lookup key based on the info in the entry.
- lookup the map built previously. If hit, check if the conntrack entry has correct ip address of container. else don't do anything.

So the case of stopping containers losing traffic will happen when there is a new starting/running container with a different managed IP and with the same expose port on the same host. (This basically logically not possible)

This logic is mainly for upgraded containers .... An old container has IP: `o.o.o.o` with expose port say 4500/tcp. When it's upgraded a new container with IP: `n.n.n.n`, the old conntrack entry which was pointing to the old IP need to be flushed.

**Comment by leodotcloud** [comment] 2017-07-31 23:46
@sangeethah @moelsayed Fixed in `rancher/network-manager:v0.7.7`.

**Comment by sangeethah** [comment] 2017-08-01 05:50
This issue was not seen when testing upgrades from rancher-server 1.5.7 -> 1.6.6-rc6 and 1.6.5 -> 1.6.6-rc6 with following versions of infra stacks:
rancher/metadata:v0.9.2
rancher/network-manager:v0.7.7
rancher/net:v0.11.5
rancher/k8s:v1.7.2-rancher5

**Closed by sangeethah** 2017-08-01 05:50 UTC
Labels: area/kubernetes, kind/bug, status/resolved, status/to-test
