### ISSUE TITLE
Secrets with binary data malformed when secret is updated with WebUI

### ISSUE THREAD

**Issue by leflambeur** [rancher/rancher#27439] opened 2020-06-04 13:38 UTC
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
Create a secret with some pkcs12 data in them (typically) quite large using kubectl - editing via kubectl shows everything fine

On Rancher UI edit the secret and add a test=12345 key/value and save

**Result:**

Binary data then gets corrupted, other data is left fine

**Other details that may be helpful:**

> We are using secrets to store certificates that are mounted in containers. Some of these certificates are in a binary format (pkcs12) and we have used kubectl edit secret to update the key/value pairs as the rancher gui lacks proper support for binary secrets.
> 
> The issue we have come across now is that if we use the webui to update an existing secret that contains a key/value pair with binary data and for example add a new key/value par and save that the binary data becomes malformed.

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): 2.3.6
- Installation option (single install/HA): HA

**Cluster information**
- Kubernetes version (use `kubectl version`):v1.16.8

gzrancher/rancher#10301

**Comment by westlywright** [comment] 2020-06-09 23:00
The root cause of the issue is that the UI is attempting to display non-UTF-8 values. This was actually already addressed in our new dashboard alpha and I am proposing we bring over the same solution into the mainline UI.

If the data is not ascii like we simply will not render it, instead we will display the length of the data in bytes (see the screenshot). This way the user can still add new rows (eg test=12345) and the data we can't render will not get borked with broken non-utf8 characters and subsequently saved in a bad state. 

![Screenshot 2020-06-09 15 58 28](https://user-images.githubusercontent.com/858614/84209110-1f80a000-aa6a-11ea-8b4c-128edef032c6.png)

**Comment by sowmyav27** [comment] 2020-06-23 20:21
**Reproduced the issue On 2.4.5 rancher**

**Steps:**

- Create pkcs12 data using command `openssl pkcs12 -export -out certificate.pfx -inkey key.pem -in cert.pem`
- Create a secret in kubectl using command `kubectl create secret generic test1 --from-file=./certificate.pfx`
- View the secret - `kubectl get secret test1 -o yaml`
- Now from Rancher UI, do an EDIT of the secret --> Add a key/value - abc/1234 --> Save changes made
- View the secret - `kubectl get secret test1 -o yaml`
- The earlier data gets corrupted. 

**Validated on 2.4-head - commit id: `46f7940dd` UI Tag: `latest-2.4`**
Issue is NOT seen fixed.

**Steps**
- Create pkcs12 data using command `openssl pkcs12 -export -out certificate.pfx -inkey key.pem -in cert.pem`
- Create a secret in kubectl using command `kubectl create secret generic test1 --from-file=./certificate.pfx`
- View the secret - `kubectl get secret test1 -o yaml`
- Now from Rancher UI, do an EDIT of the secret --> Add a key/value - abc/1234 --> Save changes made
- View the secret - `kubectl get secret test1 -o yaml`
- The earlier data gets corrupted. 

**Expected Result:**
pkcs12 data should not get corrupted on an EDIT and Save of a secret

**Comment by sowmyav27** [comment] 2020-06-24 23:07
**Validated on 2.4-head - commit id: 46f7940dd UI Tag: latest-2.4**

Issue is seen fixed.

**Steps**

- Create pkcs12 data using command openssl pkcs12 -export -out certificate.pfx -inkey key.pem -in cert.pem
- Create a secret in kubectl using command kubectl create secret generic test1 --from-file=./certificate.pfx
- View the secret - kubectl get secret test1 -o yaml
- Now from Rancher UI, do an EDIT of the secret --> Add a key/value - abc/1234 --> Save changes made
- View the secret - kubectl get secret test1 -o yaml
- The earlier data dooes NOT get corrupted.

**Closed** 2020-06-24 23:51 UTC
Labels: [zube]: To Test, area/secrets, internal, team/ui
