### ISSUE TITLE
Can not use iSCSI persist volume.

### ISSUE THREAD

**Issue by mythay** [rancher/rancher#9885] opened 2017-09-15 04:44 UTC
*Try to use iscsi in k8s, but fail*

Got following error message

`MountVolume.SetUp failed for volume "odoo-postgres-pv-i" : executable file not found in $PATH
Unable to mount volumes for pod "odoo-postgres-i-2810459680-tdj0c_default(2e1a7566-99b9-11e7-ae81-026f7979f039)": timeout expired waiting for volumes to attach/mount for pod "default"/"odoo-postgres-i-2810459680-tdj0c". list of unattached/unmounted volumes=[pgdata]`

And I find other people has these issue too
[https://forums.rancher.com/t/cant-mount-iscsi-volume/5413](url)

It seems that the Rancher specific kubelet don't include iscsi indicator (iscsiadm), is it right?
---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v1.6.7` Cattle: `v0.183.5` UI: `v1.6.17` |
|Access|`Disabled`|
|Orchestration|`Kubernetes`|
|Route|`hosts.index`|

**Comment by superseb** [comment] 2017-11-07 10:01
Duplicate of https://github.com/rancher/rancher/issues/9685

**Closed by superseb** 2017-11-07 10:01 UTC
Labels: area/kubernetes, area/packaging, area/storage
