### ISSUE TITLE
Scaling down RKE1 nodepool by one scales deletes whole nodepool

### ISSUE THREAD

**Issue by thedadams** [rancher/rancher#37378] opened 2022-04-15 20:05 UTC
**Rancher Server Setup**
- Rancher version: v2.6.1 (originally discovered on v2.5.8)
- Installation option (Docker install/Helm Chart): Docker

**Information about the Cluster**
- Kubernetes version: Unknown?
- Cluster Type (Local/Downstream): Downstream
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider): RKE1 AWS

**Describe the bug**
When selecting 1 of 2 nodes in a node pool and clicking "scale down", this marked both nodes for removal, and added 2 more back in for creation, while the desired was at 1.

**To Reproduce**
- Create a 2 node pool
- Click scale down button

**Result**
Both nodes will be deleted

**Expected Result**
Only a single node to be deleted

**Additional context**
SURE-3595

**Comment by sekosekotine** [comment] 2022-05-12 08:49
same problem in 2.6.2

**Comment by snasovich** [comment] 2022-05-13 18:53
Was not able to reproduce it on 2.6-head, but the issue may be related to zones; need to review more.

**Comment by snasovich** [comment] 2022-05-16 19:19
Tried again a few other ways and cannot reproduce the issue on v2.6-head (8a31d3cc1bf0830439d4926cd06d8fccfb9c2c54) (it's also safe to assume the behavior is the same for just-released v2.6.5).

What was done:
# Provisioned RKE1 cluster in Digital Oceal with 1 all-role node and 3 worker node pools with 2 nodes each.
# Once the cluster came back active, selected one of 2 nodes in a worker node pool and clicked "Scale Down" button. UI sent backend request to v3 node object with `action=scaleDown` and only that node got removed and node pool stayed at one node.
# In the other worker node pool clicked "-" button to scale it down. One of two nodes got removed as expected.
# In the last node pool, selected one node and clicked "-" button. Once again, only one node got removed.

@sekosekotine , could you share the steps that you reproduced the issue with?

Moving to Blocked for now.

**Comment by sekosekotine** [comment] 2022-05-17 08:35
@snasovich 
Ok, so this is the steps to reproduce my problem:

1. Provisioned RKE1 cluster on Vmware vSphere : 

- 1 pool with  etcd and control Plane roles (1 node)
- 1 pool with worker role (3 nodes)

2.  in the worker node pool, i click on scale down: ok, one worker node is removed
3. in the worker node pool, i click on scale down and then, the last two nodes are removed and my pool is empty

**Comment by sekosekotine** [comment] 2022-05-17 16:02
@snasovich I will make the test on 2.6.5.
For me scale down is: from cluster management, on the end of line of a node, i 'm clicking on the three vertical dots and choose scale down

**Comment by snasovich** [comment] 2022-05-26 02:18
@sekosekotine , wondering if you've had a chance to test it on 2.6.5 ? Thank you in advance!

**Closed** 2022-06-14 07:30 UTC
Labels: area/rke, [zube]: QA Working, team/area2
