### ISSUE TITLE
container default resource limit from the project level is not propagated to existing namespaces

### ISSUE THREAD

**Issue by deniseschannon** [rancher/rancher#18877] opened 2019-03-13 19:08 UTC
master 3/13

Resource Quota Workflow

- Add resource quota to default project and set a "Namespace Default Limit"
- Any existing namespaces automatically get these quotas set at the namespace level
- Any new namespace gets these quotas set at the namespace level

Container Default Resource Limit
- Add a container default resource limit to a default project
- Any existing namespace does **NOT** get these limit set at the namespace level
- Any new namespace gets these quotas set at the namespace level

Main Difference is around existing namespaces:
For resource quotas, they are automatically propagated to namespaces that exist in your project.

For container default resource limit, you are required to update each existing namespace with these limits. 

This is a problem particularly around when setting CPU/Memory quotas because:

1. When you set a quota for CPU/Memory, you are required to set something on the workload creation. 
2. Even if you set a container default resource limit on the project level, you are also required to set a limit on the namespace level in order for it to be used at the workload creation step.

gz#7610

**Comment by Tejeev** [comment] 2019-12-20 17:09
I believe this to be more details on this bug: 

**What kind of request is this (question/bug/enhancement/feature request):**
bug

**Steps to reproduce (least amount of steps as possible):**

1. Create a project with value(s) set for **project quota(s)**
  ![image](https://user-images.githubusercontent.com/8906089/71269404-26461a00-2347-11ea-9bf0-a9170bb3a165.png)
2. Create a namespace within the project with values set for all **Container Default Resource Limits**
  ![image](https://user-images.githubusercontent.com/8906089/71269504-6b6a4c00-2347-11ea-99cd-c247bee67e59.png)
**Result**
At this point there will be no LimitRange created for the namespace**

**Further steps**

3. Set a single **Project Container Default Resource Limit**:
  ![image](https://user-images.githubusercontent.com/8906089/71269289-e54e0580-2346-11ea-84d9-5c71393d98db.png)

**Result**

The LimitRange is not created until the namespace has a **Container Default Resource Limit** configured.  This LimitRange will only have a value for the resource which has a limit set at the Project level (though the value will correctly be that which is set in the Namespace, not the Project).

```
$ kubectl get limitrange -n 11 28643c69-5f0c-4f05-b17c-b4428abcbe37 -o yaml
apiVersion: v1
kind: LimitRange
metadata:
  creationTimestamp: "2019-12-20T16:30:03Z"
  generateName: default-
  labels:
    cattle.io/creator: norman
    resourcequota.management.cattle.io/default-resource-quota: "true"
  name: 28643c69-5f0c-4f05-b17c-b4428abcbe37
  namespace: "11"
  resourceVersion: "31187"
  selfLink: /api/v1/namespaces/11/limitranges/28643c69-5f0c-4f05-b17c-b4428abcbe37
  uid: 2f62843c-c60c-43c0-9e72-a83547207a5e
spec:
  limits:
  - default:
      cpu: "1"
    defaultRequest:
      cpu: "1"
    type: Container
```

**Further steps**

4. Setting values for the rest of the **Project Container Default Resource Limits** will allow the LimitRange to correctly configure the defaults configured for the Namespace
  ![image](https://user-images.githubusercontent.com/8906089/71270470-93f34580-2349-11ea-9d23-91e13ccb721f.png)

**Results**

```
spec:
  limits:
  - default:
      cpu: "1"
      memory: 1000Mi
    defaultRequest:
      cpu: "1"
      memory: 1000Mi
    type: Container
```

**Further tests**
5. If you set either CPU or Memory **Project Container Default Limit**, both `default` and `defaultRequest` will be configured in the LimitRange for that resource, but if you set either CPU or Memory **Reservation** only `defaultRequest` for that resource will be configured.

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported):
Hosted
- Machine type (cloud/VM/metal) and specifications (CPU/memory):
VM


Rancher | v2.3.3 vanilla / default deploy (Tested on Rancher v2.3.2 as well)
User Interface | v2.3.25
Helm | v2.14.3-rancher1
Machine | v0.15.0-rancher20-1
Kuberentes | v1.16.3

**Comment by deniseschannon** [comment] 2020-12-23 04:00
@dramich can you review this PR and move this issue forward?

**Comment by Ellenqs** [comment] 2021-01-04 19:42
Test environment: Rancher 2.5.4-rc8

Host/Provider: AWS ec2 

**Test cases and results:**

Part 1. 
1. Resource Quota Workflow
	•	Add resource quota to default project and set a "Namespace Default Limit" 

	•	Any existing namespaces automatically get these quotas set at the namespace level 
	--No, this is not reproduced, existing namespaces can not automatically get the quotas updated

       •	Any new namespace gets these quotas set at the namespace level
	— Yes, reproduced

2. Container Default Resource Limit 
	•	Add a container default resource limit to a default project
	
	•	Any existing namespace does NOT get these limit set at the namespace level
	—yes, reproduced

	•	Any new namespace gets these quotas set at the namespace level
 	-- yes, reproduced


Part 2. 
1. Create a project with value(s) set for project quota(s), not set container default limit, create a namespace within the project with values set for all Container Default Resource Limits. At this point there will be no LimitRange created for the namespace**
— Yes

2. Create a project, set container default limit in project level
There will be LimitRange created for the namespace (the projects set container limit populated to namespace)
— Yes

3. Continue with case 2, update the container default limit on project, existing namespace limitRange will not change.
-- Yes

4.  Continue with case 2, update the container default limit on project, new namespace container default limit can be set to updated value
— Yes

5. Create a project, Set a single Project Container Default Resource Limit: (e.g. only cpu, not mem)
Create namespace, only cpu/mem limit will be populated.  
— Yes

6. Continue with case 5,  add all container default limit in project level, the existing namespace limitRange will have “defaultRequest” set, but “default” is not set 
-- Yes

7. Continue with case 5,  add all container default limit in project level, new created namespace will have both "default" and "defaultRequest" set.
 —Yes

**Comment by Ellenqs** [comment] 2021-01-06 21:57
Validated on rancher 2.5.4-rc8
Cluster/provider : AWS ec2

 1. create a project set the cpu limit, no set on container default limit.
 2. create a namespace set the default limit at namespace level.
 3. limitRange for both default and default request are set:
 
<img width="302" alt="Screen Shot 2021-01-06 at 1 48 36 PM" src="https://user-images.githubusercontent.com/75277058/103823421-e8399800-5026-11eb-83cd-f1fff47bb43c.png">

**Comment by sowmyav27** [comment] 2021-01-06 23:25
Moving this to reopened because of this revert - https://github.com/rancher/rancher/pull/30698

**Comment by Ellenqs** [comment] 2021-01-07 18:01
Validate on v2.5-head, works fine, so close.

**Comment by Ellenqs** [comment] 2021-01-11 22:21
Validate on both v2.5-head and master-head:

Perform the steps mentioned here: https://github.com/rancher/rancher/pull/30165

limitrange get set:
<img width="624" alt="Screen Shot 2021-01-11 at 2 20 57 PM" src="https://user-images.githubusercontent.com/75277058/104244952-48aa4a00-5418-11eb-9063-3f862e2d6716.png">

**Comment by Tejeev** [comment] 2021-10-02 03:15
Have we seen any developments on this?  Does QA know if this is still an issue in v2.6?

**Comment by maxsokolovsky** [comment] 2022-01-28 23:55
I noticed a behavior that is related to the one described here. 
In 2.6.3, if a Project does not have resourceQuotas but has containerDefaultResourceLimits, then new namespaces do not
inherit them. It's as if the absence of resourceQuotas is the reason, which is a bug.

**Comment by maxsokolovsky** [comment] 2022-01-29 00:19
The problem is here - we explicitly check if a project has resource quotas before allowing actions on container default limits.
I don't know why this is necessary, perhaps there is a reason?

If not, I can remove that part of the check and then existing and new namespaces will get container default limits from the project. 
https://github.com/rancher/rancher/blob/415ee9d1cfe8a8ae452671f82502cb49c792fd5c/pkg/controllers/managementuser/resourcequota/resource_quota_common.go#L185

**Comment by maxsokolovsky** [comment] 2022-02-09 18:59
## QA Testing

### Root cause
We used to require at least one defined Resource Quota entry in a Project to allow Container Default Limits (if defined) to propagate to new namespaces' Container Default Limits.
### What was fixed, or what changes have occurred
If a Project does not have any Resource Quotas configured, then Container Default Resource Limits are still propagated from
a Project to new namespaces created in it.

### Areas or cases that should be tested
There are possible UI issues. To test, use kubectl  to inspect namespaces with `kubectl describe ns my-namsepace`.
### What areas could experience regressions?
1. Sometimes the propagated limits are duplicated on the namespace. This does not affect anything, just looks strange.
2. Having created a new namespace with propagated container default limits, one can see that they are missing in the UI. This could be a UI issue from before.

### Steps
1. Create a new Project.
2. Assign it Container Default Limits and be sure to NOT set any Resource Quotas.
3. Create a new namespace in the project without any additional configuration.
4. Inspect the namespace and notice that it has container default limits (inherited from the Project).

**Closed** 2022-02-17 16:26 UTC
Labels: kind/bug, internal, area/resource-quota, [zube]: QA Working, team/area1
