### ISSUE TITLE
Gauges in cluster dashboard are missing when monitoring enabled in 2.3.0

### ISSUE THREAD

**Issue by n313893254** [rancher/rancher#23299] opened 2019-10-09 09:09 UTC
**What kind of request is this (question/bug/enhancement/feature request):**

bug

**Steps to reproduce (least amount of steps as possible):**
1. Create a cluster.
2. Enable monitoring.

**Result:**
The cluster dashboard is missing.

![image](https://user-images.githubusercontent.com/18737885/66467631-52c3f700-eab7-11e9-967e-f137d9e55f6d.png)

**Other details that may be helpful:**

![image](https://user-images.githubusercontent.com/18737885/66467702-725b1f80-eab7-11e9-8171-7bbaa33270d9.png)

**Environment information**
2.3.0

**Comment by loganhz** [comment] 2019-10-09 10:08
issue only happens in master branch

**Comment by westlywright** [comment] 2019-10-09 19:13
Merged to master

**Comment by aaronRancher** [comment] 2019-12-02 15:58
Was not able to reproduce the the bug in `v2.3.0` due to it being seen in master branch.
![Screen Shot 2019-12-02 at 8 37 22 AM](https://user-images.githubusercontent.com/57409052/69974075-c72c7c80-14e1-11ea-97f0-6e96817ca71a.png)

The bug fix is validated in `rancher\rancher:master-head `version 1304c55a2`.

- Create a cluster.
- Enable monitoring.
![Screen Shot 2019-12-02 at 8 57 15 AM](https://user-images.githubusercontent.com/57409052/69974063-c4ca2280-14e1-11ea-90f1-96a050050685.png)

**Closed by aaronRancher** 2019-12-02 15:58 UTC
Labels: [zube]: To Test, area/dashboard, kind/bug-qa, team/ui
