### ISSUE TITLE
Unable to view pod logs after changing the pod's log row count or log record time

### ISSUE THREAD

**Issue by fciarrone** [rancher/rancher#38037] opened 2022-06-20 19:10 UTC
- Rancher version: 2.6.5
- Installation option (Docker install/Helm Chart): Helm Chart
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): AKS
- Proxy/Cert Details:

**Information about the Cluster**
- Kubernetes version: v1.21.7
- Cluster Type (Local/Downstream): Downstream
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider): Imported - Hosted on AKS

**User Information**
- What is the role of the user logged in? (Admin/Cluster Owner/Cluster Member/Project Owner/Project Member/Custom): Admin
   
**Describe the bug**
Unable to view pod logs after changing the pod's log row count or log record time.
After making the change to another value (1000 lines / 24 hours) the logs are not displayed and the log period options are no longer displayed in the UI.

**To Reproduce**
Go to Workload > Deployments > Select the desired deployment > in the pod open the option to view logs.

In the log window, modify the desired log viewing period option.

Close the logs window and in the pod open the option to view logs again.

**Result**

**Expected Result**
The pod logs will not be displayed and the log viewing period options will also be unavailable.

**Screenshots**
![2022-06-20_15-35](https://user-images.githubusercontent.com/29306744/174664679-ee0d432c-9704-4a40-a843-6dedaf68a675.png)
![2022-06-20_15-44](https://user-images.githubusercontent.com/29306744/174664701-7d28060b-1c54-4ece-80d3-4859705b153e.png)

**Comment by jloisel** [comment] 2022-06-21 07:21
This is a known bug in 2.6.5. Do not change log settings.

**Comment by zaakiy** [comment] 2022-06-21 13:09
Thanks @jloisel. Is there a workaround?

**Comment by paveljakov** [comment] 2022-06-22 09:03
Yep, I have already done that and now logs are gone. Is there a way to bring them back without waiting for next release?

**Comment by PlayMTL** [comment] 2022-06-22 09:56
I am also affected by the problem.

I have read that recreating the affected user (deleting and recreating) has temporarily solved the problem.

**Comment by PlayMTL** [comment] 2022-06-23 07:35
Okay, this looks like a duplicate of https://github.com/rancher/rancher/issues/37820
Workaround is described here: https://github.com/rancher/rancher/issues/37820#issuecomment-1137311698

More Issues / Solution regarding this problem: 
https://github.com/rancher/dashboard/issues/6122 
https://github.com/rancher/dashboard/issues/5984

**Comment by richard-cox** [comment] 2022-06-23 08:41
Closing as duplicate of https://github.com/rancher/dashboard/issues/5984.

A fix is coming in 2.6.6, including a change to automatically update the bad settings.

Until then there are two workarounds
- via kubectl - https://github.com/rancher/rancher/issues/37820#issuecomment-1137311698
- via browser - https://github.com/rancher/dashboard/issues/6122#issuecomment-1152394027

**Closed by richard-cox** 2022-06-23 08:41 UTC
