### ISSUE TITLE
Service upgrade page is empty

### ISSUE THREAD

**Issue by looztra** [rancher/rancher#4069] opened 2016-03-21 20:57 UTC
Rancher Version: 0.63.1 / 0.63.0

Docker Version: 1.9.1 / 1.10.3

OS: ubuntu:1404 / amazon linux

Steps to Reproduce: 

rancher-compose -p default up (using the compose+rancher files attached)

Results: If you try to upgrade the service **service-guestbook-api-server**  the page is empty

Expected: upgrade page **NOT** emtpy

See the log file representing the js error in the firefox console

[compose.zip](https://github.com/rancher/rancher/files/183088/compose.zip)
![rancher-upgrade-error-screenshot](https://cloud.githubusercontent.com/assets/246526/13933888/93e77448-efaf-11e5-8cbf-89517cda10f3.png)
[rancher-ui-js-error-1458593309073.log.zip](https://github.com/rancher/rancher/files/183092/rancher-ui-js-error-1458593309073.log.zip)

Note:

- reproduced on 2 distinct setups
- trying to upgrade the service **service-guestbook-frontend** is fine

**Comment by looztra** [comment] 2016-03-21 22:04
I took the same _docker-compose.yml _file but removed the _healthcheck_ for the service **service-guestbook-api-server**...and now I can upgrade the service!

**Comment by vincent99** [comment] 2016-03-22 08:54
Duplicate of #3704 and/or #4016, but fixed in next release.

**Closed by vincent99** 2016-03-22 08:54 UTC
Labels: area/ui, kind/bug

**Comment by looztra** [comment] 2016-03-22 09:32
ok, sorry, I searched for similar issues, but it looks like I failed :-)
