### ISSUE TITLE
[rancherd] URL from reset-admin is always the private ip

### ISSUE THREAD

**Issue by rancher-max** [rancher/rancher#29162] opened 2020-09-25 16:01 UTC
**What kind of request is this (question/bug/enhancement/feature request):**
bug/enhancement

**Steps to reproduce (least amount of steps as possible):**
1. Bring up a rancherd cluster
2. Run `rancherd reset-admin`

**Result:**
The URL that is printed is always using the Private IP, even if a Public IP is available.

**Other details that may be helpful:**
Ideally this would even use a value given with tls-san if this was present during the cluster install.

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): 2.5.0-rc1
- Installation option (single install/HA): HA

**Comment by StrongMonkey** [comment] 2020-09-26 01:08
This is designed to fetch external IP first then internal IP, but without setting cloud provider it is hard to get external IP from v1.nodes. Probably won't fix this.

**Comment by rancher-max** [comment] 2020-09-28 22:09
This works okay if server-url is set to use the load balancer. Also per @StrongMonkey I believe this is fine so we can close this out.

**Comment by ebauman** [comment] 2020-10-27 16:58
This is going to flummox folks who try and stand this up on instances w/o having prior knowledge of `server-url`. If possible, can we add an env var or argument to the install script to allow for server url override?

**Comment by rancher-max** [comment] 2020-10-27 17:13
Reopening per comment above to encourage more discussion on this.

**Comment by izaac** [comment] 2020-11-12 23:17
Rancher version: `v2.5.2` 

Deploying Rancher with `rancherd` on a Linode VM with private IP is working fine.
Deploying Rancher with `rancherd` on an EC2 VM with private IP I am able to reproduce this issue.

**Comment by StrongMonkey** [comment] 2020-11-20 19:26
I put a PR https://github.com/rancher/rancher/pull/30175 to make it more user friendly to print serverURL.

It will first fetch server-url setting from rancher if it is already been set. Then fallback to rke2 config file in case user already created a fixed address/domain for all the nodes. If both are not found, use externalNodeIP/internalNodeIP. Then if all of these can't detect the server URL it will just print a message saying rancher is listening on http/8080 and https/8443 and it is up to user to find the right way to talk to it(by creating LB/round-robin DNS).
@rancher-max @ebauman Let me know what you think and feel free to comment on the PR.

**Comment by ebauman** [comment] 2020-11-20 22:11
LGTM thanks for working on this

**Comment by izaac** [comment] 2020-12-04 22:43
Rancherd version `v2.5.4-rc1` I am still getting the private IP with EC2 instances.
Ubuntu `20.04`
Instance type: `t3a.xlarge`

```
root@ip-172-31-32-249:~# rancherd reset-admin
INFO[0000] Server URL: https://172.31.32.249:8443
INFO[0000] Default admin and password created. Username: admin, Password: <REDACTED>
root@ip-172-31-32-249:~# rancherd --version
rancherd version v2.5.4-rc1 (HEAD)
```

**Comment by StrongMonkey** [comment] 2020-12-10 03:17
@izaac You should test the following use case:
If user installs rancherd(rke2) using HA and setup tls-san from https://staging.rancher.com/docs/rancher/v2.x/en/installation/install-rancher-on-linux/#1-set-up-the-config-yaml. You will be expecting the url show up when you run `reset-admin`.
Otherwise rancherd won't detect any public IP on the host, It does its best to guess the URL in the following way:
1. If server-url setting is pre-configured(through CATTLE_ environment variables in rancher daemonset), it will print the URL. This is rare as user usually sets it when login into rancher.
2. If tls-san is provided, Rancherd will use it. This means you have the address of LB or DNS that points to your nodes. Rancher will try to use the address.
3. If it can't find URL through step 1 and 2, it will show external/internal IP on the node. Mostly like it will be internal IP since there is no good way to see public ones unless cloud provider is enabled.
4. If none of these method can find URL then it should print out a friendly message and it will be user's interest to find out what's the right way to access rancher deployment. We should also make it clear that rancher listen on 8080 and 8443 on every node so it depends how user configures the LB to access the node.

**Comment by izaac** [comment] 2020-12-11 21:04
Rancher version: `v2.5.4-rc3`

@StrongMonkey im still getting the internal ip even when the first rancherd server in an HA rancherd setup  has the following config:

```
cat /etc/rancher/rke2/config.yaml
write-kubeconfig-mode: "0644"
tls-san:
  - <PUBLIC_DNS_NAME>
cloud-provider-name:  "aws"
node-name: ip-172-X-X-X.us-east-2.compute.internal
```

`Server URL: https://172.X.X.X:8443`

This is from the first server, not from the later joined servers.

I was expecting that the server URL would be the <PUBLIC_DNS_NAME> in this case. Is that correct?

**Comment by StrongMonkey** [comment] 2020-12-11 21:11
@izaac Yes that's correct

**Comment by StrongMonkey** [comment] 2020-12-15 16:03
Available to test on the next rc.

**Comment by izaac** [comment] 2020-12-17 06:39
Rancher version `v2.5.4-rc6` 

This is now returning the url clickable `tls-san` value `<PUBLIC_DNS_NAME>`  before the first login.

```
cat /etc/rancher/rke2/config.yaml
write-kubeconfig-mode: "0644"
tls-san:
  - <PUBLIC_DNS_NAME>
cloud-provider-name:  "aws"
node-name: ip-172-X-X-X.us-east-2.compute.internal
```

If we set a different `server-url` after login (common on AirGap setups) that will be returned as per @StrongMonkey [use cases explanation](https://github.com/rancher/rancher/issues/29162#issuecomment-742209761). 

Is this preferred? I would expect in these cases to prioritize the `tls-san` over `server-url`.

**Comment by izaac** [comment] 2020-12-17 16:04
Ok if server-url is set that is expected to always be shown. as per conversation with @StrongMonkey

**Closed by izaac** 2020-12-17 16:04 UTC
Labels: [zube]: QA Working, area/rancherd, kind/bug-qa
