### ISSUE TITLE
Request to add disableMountSubPath option in Prometheus operator (monitoring system chart)

### ISSUE THREAD

**Issue by suryatejaboorlu** [rancher/rancher#29149] opened 2020-09-25 06:35 UTC
**What kind of request is this (question/bug/enhancement/feature request):**
enhancement 

**Steps to reproduce (least amount of steps as possible):**
* On the NFS server, export a shared folder accessible by a specific user (Say username=kubeusr, uid=2001, gid=3001).
* Ensure the specific user exists on the nodes of the cluster.
* Mount the NFS share on the nodes of the cluster at `/pv`.
* Deploy local-path-provisioner (https://github.com/rancher/local-path-provisioner/tree/v0.0.17#installation) using `/pv`. This installation will take care of installing the StorageClass too.
* In the enable/disable page of monitoring, enable persistent storage using the local-path-storage class, and use the following 
answers under the advanced options: 
 prometheus.securityContext.runAsUser = 2001
 prometheus.securityContext.runAsGroup = 3001
 prometheus.securityContext.runAsNonRoot = true

**Result:**
Prometheus operator container will not succeed to run, and the logs point to "permission" errors.  

**Root Cause**
https://github.com/rancher/local-path-provisioner/issues/4

**Environment information**
- Rancher version: v2.3.5
- Installation option (single install/HA): Single and HA

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): Custom 
- Machine type (cloud/VM/metal) and specifications (CPU/memory): Cloud
- Kubernetes version : v1.16.15

**Comment by aiyengar2** [comment] 2020-09-25 20:25
As noted in https://github.com/rancher/system-charts/pull/345#issuecomment-698650663, the Prometheus Operator version that contains the ability to `disableMountSubPath` is only supported in k8s 1.16+. Since there is no Rancher release that exclusively supports k8s 1.16+ at the moment and we only have the ability to scope system charts to Rancher versions (as opposed to having something like a min kubernetes version), we can't support this change at the moment.

I'm closing out https://github.com/rancher/system-charts/pull/345 and https://github.com/rancher/image-mirror/pull/40 till we have the ability to support different system charts for different versions of k8s.

**Comment by aiyengar2** [comment] 2020-10-30 22:55
https://github.com/rancher/rancher/issues/29346 tracks support for this in 2.5 and https://github.com/rancher/rancher/issues/29867 tracks the backport to add support for this in 2.4

**Comment by suryatejaboorlu** [comment] 2020-12-04 16:22
I've reproduced the issue as in the instructions above and found the same permission error as below:

`level=error ts=2020-12-04T16:19:12.689Z caller=query_logger.go:87 component=activeQueryTracker msg="Error opening query log file" file=/prometheus/queries.active err="open /prometheus/queries.active: permission denied"
`

Monitoring chart: v0.2.0
Rancher Version: 2.5-head

**Comment by aiyengar2** [comment] 2020-12-04 20:07
@suryatejaboorlu I took a look at the setup. It seems like the `Prometheus` resource created by the `cluster-monitoring` deployment does not pass set `spec.storage.disableMountSubPath` at all, although the Helm template should be upgrading that field.

The workaround of manually applying `spec.storage.disableMountSubPath=true` to the `Prometheus` resource (name: `cluster-monitoring`, namespace: `cattle-prometheus`), after which the deployment no longer encounters the error you described.

#### Why isn't this field being passed in?

This is a weird bug unrelated to the current fixes since, if I do the following steps:
1. Pull in `rancher/system-charts@dev-v2.5`
1. Copy the `values.yaml` of the `cluster-monitoring` Helm deployment (picked from the Dashboard UI)
1. Run `helm template -n cattle-prometheus cluster-monitoring charts/rancher-monitoring/v0.2.0/ --values values.yaml > output.yaml`

And check the output in `output.yaml`, I see the field show up on the Prometheus CR:
![Screen Shot 2020-12-04 at 11 59 47 AM](https://user-images.githubusercontent.com/13127443/101209179-36263f00-3628-11eb-828e-d3b2d3572a4c.png)

I double checked whether this might be because the CRD is out-of-date in your cluster (which means Helm might have received the field, but ignored it). But it seems like your cluster successfully upgraded the CRD version to `monitoring.coreos.com/v1` and I was able to confirm that `spec.storage.disableMountSubPath` is defined on your CRD.

#### Need more information

Can you disable Monitoring from your cluster entirely, wait for the resources to disappear, and then capture the Rancher logs that come when you try to enable Cluster Monitoring as described above? Maybe the Rancher logs might show something that indicates why there is a discrepancy between the `values.yaml` of the Helm release and the actual template that is rendered.

**Comment by aiyengar2** [comment] 2020-12-04 20:36
Figured out the issue; the original PR dropped `crd-install` annotations that Helm 2 needs. 

I suspect Tiller wasn't able to work with the new CRDs that did not have the crd-install annotation, so it was still working with the older version of the CRD spec (which is why it ignores in new fields in the Prometheus resource). 

Added my local branch to your setup with the fixes and Monitoring deploys successfully! Will get those PRs in so we can test once more.

**Comment by jiaqiluo** [comment] 2020-12-08 06:08
We still see the same failure on v2.5-395b4fe77b37d634568349bcf911998d0643dada-head with the latest chart.
![image](https://user-images.githubusercontent.com/6218999/101445834-6fd49f80-38df-11eb-835f-b48ff23dd24c.png)
![image](https://user-images.githubusercontent.com/6218999/101445856-7a8f3480-38df-11eb-8c8d-27840656c61d.png)


I also check the CRD on the cluster. for example, the CRD `alertmanagers.monitoring.coreos.com` does contain the new annotation in your recent fix
```
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.2.4
    helm.sh/hook: crd-install
...
```

**Comment by aiyengar2** [comment] 2020-12-09 23:04
Just checked out the test setup once more. https://github.com/rancher/rancher/issues/29149#issuecomment-739006150 was not the right fix since this seems to be Kubernetes related, not Helm related.

#### Investigation

On the test cluster with the new version of the CRD installed, I tried installing a Prometheus with `spec.storage.disableMountSubPath=true` by storing the Prometheus within a `prometheus.yaml` and then running `kubectl apply -f prometheus.yaml` pointing to the cluster.

This successfully creates the resource but the field is omitted. I also noticed that `spec.storage.disableMountSubPath` doesn't show up in the k8s managed fields.

However, if I then run `kubectl apply -f prometheus.yaml` once more with *no changes*, the resource now has `spec.storage.disableMountSubPath=true`.

Could this be an upstream Kubernetes bug?

#### Next Steps

@jiaqiluo @suryatejaboorlu could we try to replicate this on a k8s 1.16 / 1.17 / 1.18 cluster? It's possible this could have been an issue introduced in Kubernetes upstream since the clusters so far have all been k8s 1.19 clusters.

**Comment by aiyengar2** [comment] 2020-12-09 23:08
#### Workaround till Fix

After upgrading to the latest chart and deploying monitoring, edit the Prometheus resource in the `cattle-prometheus` namespace (can use the Cluster Explorer UI Monitoring Pane) to add in `spec.storage.disableMountSubPath=true`. This mimics the second `kubectl apply -f prometheus.yaml` noted above and allows the resource to be deployed successfully.

@jiaqiluo can we also validate this workaround? cc: @maggieliu since a workaround exists

**Comment by jiaqiluo** [comment] 2020-12-14 19:13
The workaround is confirmed on rancher:`v2.5-head` baf486 on clusters with k8s version `v1.16.15` and `v1.19.4` 

We need to go to edit the Prometheus resource to add the `disableMountSubPath: true` line to it.
<img width="480" alt="Screen Shot 2020-12-14 at 10 17 31 AM" src="https://user-images.githubusercontent.com/6218999/102124535-a80b3f00-3e05-11eb-90f1-468648a57a6a.png">

**Comment by maggieliu** [comment] 2020-12-14 21:34
We will only support the new chart in 2.5.4+. @aiyengar2 will revert the chart in 2.4.

**Comment by aiyengar2** [comment] 2020-12-16 00:02
See note in https://github.com/rancher/rancher/issues/30484#issuecomment-745642510 for why the Rancher update of the Prometheus Operator version is necessary.

**Comment by jiaqiluo** [comment] 2020-12-17 01:09
The fix is validated on v2.5-head 49bbe0

The steps are the same as before, and now 
- the `disableMountSubPath: true` is applied by default
- Prometheus pod is active 
- no workaround is needed 

Also, confirmed that monitoring v1 0.1.4 continues working. 

Wait for the master-head to be ready for validating the fix.

**Comment by jiaqiluo** [comment] 2020-12-17 02:01
The fix is validated on master-head 3a2f30

**Closed** 2020-12-17 02:01 UTC
Labels: [zube]: QA Working, internal

**Comment by immanuelfodor** [comment] 2021-01-12 12:46
Hi Everyone,

I can clearly see the update with the fix here: https://github.com/rancher/system-charts/tree/dev-v2.5/charts/rancher-monitoring/v0.2.0

However, as far as I can tell, the Rancher UI gets the charts from this repo and branch: https://github.com/rancher/charts/tree/main/charts/rancher-monitoring

These are the versions I can see on the UI: 

![image](https://user-images.githubusercontent.com/21174107/104315919-f7638e80-54db-11eb-9b27-9ba07bb8938e.png)

And the Chart.yaml versions and the main branch here probably corresponds to that repo:

![image](https://user-images.githubusercontent.com/21174107/104316064-342f8580-54dc-11eb-8797-c60119dac0c9.png)

Could you please tell when that repo will receive the update? Or is there an open issue that I can follow? 

I have the Local Path Provisioner installed that doesn't support using subPath and so I really need the fix to be available in the "official" repo: https://github.com/rancher/local-path-provisioner/issues/4

**Comment by jiaqiluo** [comment] 2021-01-12 17:54
Hi @immanuelfodor  
This bug is fixed in monitoring v1, and your screenshots are for monitoring v2. 

monitoring v1 can be enabled in Rancher's cluster management UI at cluster&project level 
![screencapture-206-189-77-19-c-c-2jfkz-monitoring-cluster-setting-2021-01-12-10_51_56](https://user-images.githubusercontent.com/6218999/104352684-371e7c00-54c4-11eb-802c-6154bbdcb5ba.png)


And `system-library` is where its charts from.
https://github.com/rancher/system-charts

![screencapture-206-189-77-19-g-catalog-2021-01-12-10_52_34](https://user-images.githubusercontent.com/6218999/104352783-587f6800-54c4-11eb-9bb5-10ebdb019de5.png)

**Comment by immanuelfodor** [comment] 2021-01-12 19:03
Oh, wow, thank you, so this is why I can't see it there in the other repo. Are you aware of any effort to make it available for monitoring v2? I'd follow that issue then. Sadly, I couldn't go back to the v1 stack in my environment. In the meantime, I fixed the problem in a dirty way: deleted the operator itself to avoid update of the Prometheus StatefulSet, and updated the mount to do not have the subPath. But this hack prevents me from further Helm updates as it would revert the hack after redeploying the operator.

**Comment by jiaqiluo** [comment] 2021-01-12 19:06
> Oh, wow, thank you, so this is why I can't see it there in the other repo. Are you aware of any effort to make it available for monitoring v2? I'd follow that issue then. Sadly, I couldn't go back to the v1 stack in my environment. In the meantime, I fixed the problem in a dirty way: deleted the operator itself to avoid update of the Prometheus StatefulSet, and updated the mount to do not have the subPath. But this hack prevents me from further Helm updates as it would revert the hack after redeploying the operator.

@aiyengar2 Do you have the answer to the above question?

**Comment by aiyengar2** [comment] 2021-01-12 19:10
@immanuelfodor we have an issue at https://github.com/rancher/rancher/issues/29871 to rebase to the latest upstream kube-prometheus-stack chart. Once that is complete, this new field should be exposed.

**Comment by immanuelfodor** [comment] 2021-01-12 19:14
Thank you so much, I wouldn't find it with search as it doesn't include the related phrases to my problem but I subscribed to that now, super helpful, thanks again!
