### ISSUE TITLE
custom registry secret hangs indefinitely

### ISSUE THREAD

**Issue by shpwrck** [rancher/rancher#27283] opened 2020-05-27 13:57 UTC
**What kind of request is this (question/bug/enhancement/feature request):**

Bug

**Steps to reproduce (least amount of steps as possible):**

1. Navigate to the `Registry Credentials` page of any project in any cluster.
1. Click `Add Registry`
1. Attempt to create a custom registry secret for all namespaces.
    1. `Name` : Anything
    1. `Scope`: Available to all namespaces in this project
    1. `Address`: Custom
    1. `Registry`,`Username`,`Password`: Anything
1. Click `Save`

**Result:**

The request will spin indefinitely.

**Other details that may be helpful:**

* The content doesn't make a difference. I've tested against multiple registries with multiple credentials.
* In my testing, this can be worked around by selecting a single namespace, filling in the rest of the information, and then selecting all namespaces again.

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): `v2.4.3`
- Installation option (single install/HA): `HA`

**Comment by sangeethah** [comment] 2020-05-27 15:12
Duplicate of https://github.com/rancher/rancher/issues/26981

**Closed by sangeethah** 2020-05-27 15:12 UTC
