### ISSUE TITLE
When viewing Template Revisions, no information about overrides is presented.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#23066] opened 2019-09-24 22:09 UTC
Rancher server version - Build from master

Steps to reproduce the problem:
Create a cluster Template revision by choosing "1.15.4-rancher1-1" with override.
Notice the override Parameters show this info as expected.

View this Template revision.

Notice that there is no information about there being an override set for kubernetes version.

Expected Behavior:
We should show the override Parameters that will indicate to the user that there were overrides done for kubernetes version.

**Comment by deniseschannon** [comment] 2019-09-25 00:02
Since there is no ability to create custom overrides in the UI, in the edit cluster section, we should be hiding the "Custom Cluster Overrides" section as the UI will already allow you to "override" the values in the cluster options section. 

This section was previously kept for "custom overrides" and since we had removed the ability to add them, this section should be removed.

**Comment by deniseschannon** [comment] 2019-09-25 00:13
We have never implemented a way to show which fields that you can override in the template revisions page. We can look at this for a future release.

As a workaround today, you can clone your revision to see which ones have overrides possible.

**Comment by deniseschannon** [comment] 2019-09-25 17:17
@tfiduccia This needs some UX help on how we would want to show this.

**Comment by deniseschannon** [comment] 2019-09-26 05:32
Duplicate of https://github.com/rancher/rancher/issues/22183

**Closed by deniseschannon** 2019-09-26 05:32 UTC
Labels: [zube]: Next Up, kind/enhancement, team/ui
