### ISSUE TITLE
Backport UI Shows only 1000 nodes on a fresh load

### ISSUE THREAD

**Issue by alena1108** [rancher/rancher#19934] opened 2019-05-02 04:31 UTC
Backport https://github.com/rancher/rancher/issues/15128

**Comment by alena1108** [comment] 2019-05-02 04:32
Can be tested on rc5

**Comment by davidnuzik** [comment] 2019-05-03 17:34
Version: v2.2.3-rc5

I performed the same steps in v2.2.3-rc5 as I did in master in issue #15128 
So, I have copied the comment below as I had the exact same findings -- this seems to be working fine now.

------------

I can confirm now that when I set a limit less than the total, the total remains constant (does not decrease to a value equal to what the limit was set to as @gitlawr indicated above before the fix).

<img width="541" alt="Screen Shot 2019-05-03 at 10 09 09 AM" src="https://user-images.githubusercontent.com/45179589/57153614-99d0f200-6d8b-11e9-8a4d-88d0a2073fac.png">

Further, when I set my user preferences to only allow x number of rows per table (as seen below) paging now works as expected (second screenshot)
![image](https://user-images.githubusercontent.com/45179589/57153364-f54eb000-6d8a-11e9-9a2d-1c6a0dde2b2d.png)

![image](https://user-images.githubusercontent.com/45179589/57153384-039ccc00-6d8b-11e9-8e02-2a862b210dc6.png)

**Comment by loganhz** [comment] 2019-05-04 01:25
@davidnuzik it looks like you reopened this issue. It should be fixed ?

**Comment by davidnuzik** [comment] 2019-05-06 16:04
@loganhz it is fixed and working based on my tests. @sangeethah told me to keep both this and original issue open until further notice.

**Comment by sangeethah** [comment] 2019-05-21 18:05
Got confirmation from @cloudnautique that UI loads nodes correctly on setups with >1000 nodes.

**Closed by sangeethah** 2019-05-21 18:05 UTC
Labels: [zube]: To Test, internal, kind/bug, status/ready-for-review, status/resolved, status/to-test, team/cn
