### ISSUE TITLE
Graceful upgrades

### ISSUE THREAD

**Issue by deadbeef84** [rancher/rancher#4545] opened 2016-04-25 16:45 UTC
We're investigating how to do rolling upgrades, without any downtime. Here's what we would like to do:

1. Start new service
2. Wait for new service to become ready
3. Redirect new connections to the new service
4. Wait for connections to the old service to complete
5. Shutdown old service. Maybe send SIGTERM to the container, wait for container to exit then after a specified amount of time send SIGKILL? Not sure how this is handled today.
6. Remove old service.

Is this doable? Currently when using `rancher-compose up -d servicename` (with start_first: true) it seems the active connections get interrupted, even when using a loadbalancer.

**Comment by deniseschannon** [comment] 2016-04-25 18:39
Have you seen this?

**Comment by deniseschannon** [comment] 2016-04-25 18:39
http://docs.rancher.com/rancher/rancher-compose/upgrading/#rolling-upgrade

**Comment by deadbeef84** [comment] 2016-04-26 15:17
Yes, `rancher-compose upgrade oldservice newservice` seems to have the same problems as `rancher-compose up`. More specifically:
- Active connections are dropped
- After the new service has been started, during the specified --interval, new connections are still sent to the old service since it is still active.

Let me explain my use case and maybe it will become more clear. I have an http service receiving large file uploads, these could take a while to upload so I would like to avoid interruptions. Now I want to upgrade my http service.

I guess normally you would use a loadbalancer to do this kind of thing?

**Comment by deadbeef84** [comment] 2016-05-04 15:18
Any thoughts on this?

**Comment by deadbeef84** [comment] 2016-05-10 13:07
I have found a way to do it manually:
- Clone service, upgrade and start it
- Point load balancer to new service - This will not drop active connections.
- Wait for connections to the old container to complete (I used docker exec and netstat to monitor active connections)
- Stop/remove old container

Is there any chance this could be integrated into rancher-compose? I understand the waiting for connections to complete could be difficult, but it would be nice to at least have the first two steps automated.

**Comment by amachowi** [comment] 2016-09-13 13:18
Hi, 

I'd also like to vote for a more graceful upgrade. In our scenarios some kind of configurable timeout for the old container (between removing the container from haproxy and sending SIGTERM to the container) would help pretty much. 

Kind regards,
Andre.

**Comment by janeczku** [comment] 2016-09-13 18:18
Currently, we immediately stop old containers after removing them from the LB. This results in dropped connections during the upgrade, even though HAProxy LB itself would be able to handle existing connections to backends that have been dropped from its configuration.

The rolling upgrade should at least have a configurable time period for which to keep old containers running after dropping them from the load balancer.

/cc @alena1108

**Comment by deniseschannon** [comment] 2016-10-04 19:01
Duplicate of https://github.com/rancher/rancher/issues/2777

**Closed by deniseschannon** 2016-10-04 19:01 UTC
Labels: area/rancher-compose, kind/enhancement

**Comment by inetfuture** [comment] 2017-02-28 12:50
Just want to add that, not being able to do real zero downtime upgrading is a deal breaker for actual production use.

**Comment by janeczku** [comment] 2017-02-28 14:45
@inetfuture Implementation of that feature is tracked in #2777. Please leave your comment there 😄
