### ISSUE TITLE
Can not add azure ad groups to default admin

### ISSUE THREAD

**Issue by ajfriesen** [rancher/rancher#22726] opened 2019-09-09 14:45 UTC
**What kind of request is this (question/bug/enhancement/feature request):**

bug

**Steps to reproduce (least amount of steps as possible):**

Update default admin user with a azure ad group does not work.

```
curl -u "${ACCESS_TOKEN}" \
-X PUT \
-H 'Accept: application/json' \
-H 'Content-Type: application/json' \
-d '{"annotations":{"lifecycle.cattle.io/create.mgmt-auth-users-controller":"true"}, "conditions":[], "created":"2019-04-11T21:29:02Z", "creatorId":null, "description":"", "id":"user-bwwtn", "labels":{"authz.management.cattle.io/bootstrapping":"admin-user", "cattle.io/creator":"norman"}, "me":true, "mustChangePassword":false, "name":"Default Admin", "ownerReferences":[], "principalIds":["local://user-bwwtn", "azuread_user://some-group-id"], "state":"active", "transitioning":"no", "transitioningMessage":"", "username":"admin", "uuid":"d3cf154a-5ca0-11e9-b9ba-0eadc8878f18"}' \
'https://rancher-url.com/v3/users/user-bwwtn'
```

**Result:**

You can update but not login from a user of that group.
Workaround is to add every user to that principal list:

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): 2.2.8
- Installation option (single install/HA): HA

**Comment by slessardjr** [comment] 2019-09-10 18:35
Is this a duplicate of #22707 ?

**Comment by deniseschannon** [comment] 2019-09-26 17:36
Closing in favor of #33707

**Closed by deniseschannon** 2019-09-26 17:36 UTC
