### ISSUE TITLE
Use Aliyun External  DNS or Infoblox External  DNS, Can not upgrade service

### ISSUE THREAD

**Issue by kingsd041** [rancher/rancher#10076] opened 2017-10-11 05:14 UTC
**Rancher versions:**
rancher/server: 1.6.10
rancher/external-dns: v0.7.5

**Docker version: (`docker version`,`docker info` preferred)**
17.06.2-ce
**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle
**Steps to Reproduce:**
1. Use Aliyun External  DNS or Infoblox External  DNS to set the wrong "Access key id" or "Access key secret". At this service will fail to start.
2. Click the "Up to date" button to modify the correct "Access key id" or "Access key secret".
3. Review the Upgrade results.

**Results:**
Upgrade failed！
rancher/server logs：
```
time="2017-10-10T04:21:47Z" level=info msg="Upgrade Stack Event Received" eventId=62cbf876-70b4-4ad1-9018-d4efd7332f1e resourceId=1st14
time="2017-10-10T04:21:47Z" level=info msg="[alidns:]: Starting project " eventId=62cbf876-70b4-4ad1-9018-d4efd7332f1e resourceId=1st14
time="2017-10-10T04:21:47Z" level=info msg="[alidns:alidns]: Starting " eventId=62cbf876-70b4-4ad1-9018-d4efd7332f1e resourceId=1st14
time="2017-10-10T04:21:47Z" level=error msg="Failed Starting alidns : Service alidns must be state=active or inactive to upgrade, currently: state=updating-active"
time="2017-10-10T04:21:47Z" level=error msg="Failed to start: alidns : Service alidns must be state=active or inactive to upgrade, currently: state=updating-active"
time="2017-10-10T04:21:47Z" level=error msg="Stack Upgrade Event Failed: Service alidns must be state=active or inactive to upgrade, currently: state=updating-active" eventId=62cbf876-70b4-4ad1-9018-d4efd7332f1e resourceId=1st14
time="2017-10-10T04:21:47Z" level=info msg="[alidns:]: Project started " eventId=62cbf876-70b4-4ad1-9018-d4efd7332f1e resourceId=1st14
2017-10-10 04:21:47,443 ERROR [:] [] [] [] [ecutorService-3] [.e.s.i.ProcessInstanceDispatcherImpl] Unknown exception running process [stack.upgrade:1040] on [14], canceled by [State [upgrading] is not valid for process [stack.error:1102] on resource [14]]
2017-10-10 04:21:49,112 ERROR [5bf310f4-c9cd-4151-b941-66c18648fff0:1114] [instance:32->instanceHostMap:32] [instance.start->(InstanceStart)->instancehostmap.activate] [] [cutorService-27] [c.p.e.p.i.DefaultProcessInstanceImpl] Agent error for [compute.instance.activate.reply;agent=1]: Timeout getting IP address
2017-10-10 04:21:49,113 ERROR [5bf310f4-c9cd-4151-b941-66c18648fff0:1114] [instance:32] [instance.start->(InstanceStart)] [] [cutorService-27] [i.c.p.process.instance.InstanceStart] Failed [1/5] to Starting for instance [32]
2017-10-10 04:21:49,686 ERROR [2dc52f50-fe2b-45ef-9477-207976e65903:1113] [service:17] [service.update] [] [cutorService-26] [c.p.e.p.i.DefaultProcessInstanceImpl] Expected state running but got stopped
2017-10-10 04:21:49,691 ERROR [:] [] [] [] [cutorService-26] [.e.s.i.ProcessInstanceDispatcherImpl] Expected state running but got stopped
2017-10-10 04:22:03,682 ERROR [367ca2c4-8e86-43a3-887e-a1488366f999:1113] [service:17] [service.update] [] [cutorService-15] [c.p.e.p.i.DefaultProcessInstanceImpl] Expected state running but got stopped
2017-10-10 04:22:03,692 ERROR [:] [] [] [] [cutorService-15] [.e.s.i.ProcessInstanceDispatcherImpl] Expected state running but got stopped
```

**Comment by loganhz** [comment] 2017-10-12 04:20
this is `Timeout getting IP address` issue which is not related to Aliyun DNS. This is a duplicated issue i think

**Comment by yasker** [comment] 2017-10-12 23:52
@loganhz duplicate issue of which one?

**Comment by yasker** [comment] 2017-10-16 03:49
@kingsd041 Is this issue always reproducible?

**Comment by kingsd041** [comment] 2017-10-17 04:15
@yasker Yes, I have tested at least five times

**Comment by yasker** [comment] 2017-10-17 04:19
@loganhz It's not a unreproducible problem like others. You need to look into it.

**Comment by loganhz** [comment] 2017-10-17 04:20
@kingsd041 Can you help to reproduce it, please ? And ping me the env link.  I can not reproduce it. thanks a lot

**Comment by loganhz** [comment] 2017-10-17 04:30
@kingsd041 @yasker Maybe this is the root cause `https://github.com/rancher/rancher/issues/6560#issuecomment-275997267`

**Comment by loganhz** [comment] 2017-10-17 04:57
I can not reproduce the `Timeout getting IP address` issue.
But I can find an issue that user can not update the env values of  a unhealthy catalog via catalog upgrade UI.

**Comment by loganhz** [comment] 2017-10-17 08:31
A workaround is that stop the stack first and do the upgrade from UI.

In rancher, we can only upgrade the `active` or `inactive` service when we do a stack upgrade. 
https://github.com/rancher/rancher-compose-executor/blob/v1.6/rancher/normal.go#L137

**Comment by yasker** [comment] 2017-10-19 21:50
Talked with @alena1108 and @will-chan , we should just stop the service or destroy and recreate the service in this case.

Mark as won't fix.

**Closed** 2017-10-19 21:51 UTC
Labels: area/external-dns, kind/bug, status/resolved, status/wontfix, team/cn
