### ISSUE TITLE
When LB service is created with a  scale more than hosts are available , service is stuck in "activating" state forever.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#727] opened 2015-05-06 17:10 UTC
Server version - V0.18.2
Steps to reproduce the problem:

Create LB service with scale = 3 when there are only 2 hosts in the setup.
Lb service is stuck in "activating" forever.

Expected Behavior:
API should error out with error message indicating that the scale cannot be honored.

**Comment by alena1108** [comment] 2015-05-06 23:09
Its a generic problem for all related services processes (and most of other cattle objects). If something fails, we never return failure back to API, but instead keep on retrying forever OR let user to fix the failure by scaling down/deactivating the service. We should definitely think if thats a valid behavior before we go SaaS, and if not, we should think about what would be the right way to fix it.

**Comment by alena1108** [comment] 2015-05-08 21:18
Duplicating to https://github.com/rancherio/rancher/issues/557 as the cause for these bugs is the same

**Comment by sangeethah** [comment] 2015-05-15 19:39
Reopening this issue w.r.to to discussions in  - https://github.com/rancherio/rancher/issues/820

**Comment by deniseschannon** [comment] 2015-05-15 20:06
:+1: This is bad user experience. I'm not sure how we should inform the user of what the error is but if I had no knowledge of what hosts already have their ports used, then we'll have the same issue.

We need to think of the multiple users experience.

**Comment by deniseschannon** [comment] 2015-12-03 22:58
Pre-duplicate of https://github.com/rancher/rancher/issues/820

Essentially, we need better error message when service will fail to scale due to lack of open ports or invalid container info.

**Closed by deniseschannon** 2015-12-03 22:58 UTC
Labels: area/service, kind/bug
