### ISSUE TITLE
Deleted cluster stays in Removing state

### ISSUE THREAD

**Issue by kravciak** [rancher/rancher#32959] opened 2021-05-31 19:13 UTC
In EmberUI:
 - create DO infrastructure provider cluster (I tried different node configs, all of them fail)
 - remove DO cluster

VMs are removed from DO but cluster stays visible in rancher in `Removing - Waiting on cluster-scoped-gc` state.

![Screenshot from 2021-05-31 15-19-20](https://user-images.githubusercontent.com/538604/120232829-acf96900-c254-11eb-84d2-5938e03bb534.png)

<details>
  <summary>Server logs</summary>

```
2021/05/31 13:16:10 [INFO] kontainerdriver rancherkubernetesengine listening on address 127.0.0.1:33815
2021/05/31 13:16:10 [INFO] kontainerdriver rancherkubernetesengine stopped
2021/05/31 13:16:10 [WARNING] secrets "cattle-system/c-c-qbhdj" not found
2021/05/31 13:16:10 [ERROR] [etcd-backup] giving up on deleting backup [c-qbhdj-rl-rhrgd]: timed out waiting for the condition
2021/05/31 13:16:16 [ERROR] error syncing 'c-qbhdj/m-vdj87': handler node-controller: ClusterUnavailable 503: ClusterUnavailable 503: cluster not found, requeuing
2021/05/31 13:16:16 [ERROR] error syncing 'c-qbhdj/m-t8zd9': handler node-controller: ClusterUnavailable 503: ClusterUnavailable 503: cluster not found, requeuing
2021/05/31 13:16:23 [INFO] Stopping cluster agent for c-jzxr9
2021/05/31 13:16:23 [INFO] Shutting down cluster.cattle.io/v3, Kind=ClusterUserAttribute workers
2021/05/31 13:16:23 [INFO] Shutting down /v1, Kind=Pod workers
2021/05/31 13:16:23 [INFO] Shutting down rbac.authorization.k8s.io/v1, Kind=ClusterRole workers
2021/05/31 13:16:23 [INFO] Shutting down /v1, Kind=Service workers
2021/05/31 13:16:23 [INFO] Shutting down /v1, Kind=Endpoints workers
2021/05/31 13:16:23 [INFO] Shutting down /v1, Kind=Secret workers
2021/05/31 13:16:23 [INFO] Shutting down /v1, Kind=Node workers
2021/05/31 13:16:23 [INFO] Shutting down /v1, Kind=LimitRange workers
2021/05/31 13:16:23 [INFO] Shutting down cluster.cattle.io/v3, Kind=ClusterAuthToken workers
2021/05/31 13:16:23 [INFO] Shutting down apiregistration.k8s.io/v1, Kind=APIService workers
2021/05/31 13:16:23 [INFO] Shutting down /v1, Kind=ResourceQuota workers
2021/05/31 13:16:23 [INFO] Shutting down batch/v1, Kind=Job workers
2021/05/31 13:16:23 [INFO] Shutting down apps/v1, Kind=StatefulSet workers
2021/05/31 13:16:23 [INFO] Shutting down apps/v1, Kind=Deployment workers
2021/05/31 13:16:23 [INFO] Shutting down /v1, Kind=ServiceAccount workers
2021/05/31 13:16:23 [INFO] Shutting down rbac.authorization.k8s.io/v1, Kind=Role workers
2021/05/31 13:16:23 [INFO] Shutting down apps/v1, Kind=DaemonSet workers
2021/05/31 13:16:23 [INFO] Shutting down apps/v1, Kind=ReplicaSet workers
2021/05/31 13:16:23 [INFO] Shutting down /v1, Kind=ConfigMap workers
2021/05/31 13:16:23 [INFO] Shutting down policy/v1beta1, Kind=PodSecurityPolicy workers
2021/05/31 13:16:23 [INFO] Shutting down rbac.authorization.k8s.io/v1, Kind=RoleBinding workers
2021/05/31 13:16:23 [INFO] Shutting down extensions/v1beta1, Kind=Ingress workers
2021/05/31 13:16:23 [INFO] Shutting down batch/v1beta1, Kind=CronJob workers
2021/05/31 13:16:23 [INFO] Shutting down networking.k8s.io/v1, Kind=NetworkPolicy workers
2021/05/31 13:16:23 [INFO] Shutting down /v1, Kind=ReplicationController workers
2021/05/31 13:16:23 [INFO] Shutting down rbac.authorization.k8s.io/v1, Kind=ClusterRoleBinding workers
2021/05/31 13:16:23 [INFO] Shutting down /v1, Kind=Namespace workers
2021/05/31 13:16:23 [INFO] Shutting down /v1, Kind=Event workers
2021/05/31 13:16:23 [INFO] Deleting cluster [c-jzxr9]
2021/05/31 13:16:23 [INFO] [mgmt-auth-users-controller] Deleting clusterRoleTemplateBinding u-6loni3qv4q-admin for user u-6loni3qv4q
2021/05/31 13:16:23 [INFO] [mgmt-auth-users-controller] Deleting globalRoleBinding grb-pt7mb for user u-6loni3qv4q
2021/05/31 13:16:23 [INFO] [mgmt-auth-crtb-controller] Deleting roleBinding crb-5ebxtxevdj
2021/05/31 13:16:23 [INFO] [mgmt-auth-crtb-controller] Deleting rolebinding u-6loni3qv4q-admin-cluster-owner in namespace p-sgvv6 for crtb u-6loni3qv4q-admin
2021/05/31 13:16:23 [INFO] [mgmt-auth-crtb-controller] Deleting roleBinding crb-cpnpfoom7h
2021/05/31 13:16:23 [INFO] [mgmt-auth-crtb-controller] Deleting rolebinding u-6loni3qv4q-admin-cluster-owner in namespace p-6dx64 for crtb u-6loni3qv4q-admin
2021/05/31 13:16:23 [INFO] [mgmt-auth-crtb-controller] Deleting rolebinding c-jzxr9-owner-cluster-owner in namespace p-sgvv6 for crtb c-jzxr9-owner
2021/05/31 13:16:23 [INFO] [mgmt-auth-crtb-controller] Deleting rolebinding c-jzxr9-owner-cluster-owner in namespace p-6dx64 for crtb c-jzxr9-owner
2021/05/31 13:16:24 [ERROR] error syncing 'c-bj6rq/m-k9k5b': handler node-controller: ClusterUnavailable 503: ClusterUnavailable 503: cluster not found, requeuing
2021/05/31 13:16:24 [ERROR] error syncing 'c-bj6rq/m-hpb4w': handler node-controller: ClusterUnavailable 503: ClusterUnavailable 503: cluster not found, requeuing
2021/05/31 13:16:25 [ERROR] error syncing 'c-6w448/m-66wtm': handler node-controller: ClusterUnavailable 503: ClusterUnavailable 503: cluster not found, requeuing
2021/05/31 13:16:26 [INFO] error in remotedialer server [400]: websocket: close 1006 (abnormal closure): unexpected EOF
2021/05/31 13:16:28 [INFO] kontainerdriver rancherkubernetesengine listening on address 127.0.0.1:41261
2021/05/31 13:16:28 [INFO] cluster [c-jzxr9] provisioning: Tearing down Kubernetes cluster
2021/05/31 13:16:28 [INFO] cluster [c-jzxr9] provisioning: [dialer] Setup tunnel for host [159.65.84.170]
2021/05/31 13:16:28 [INFO] cluster [c-jzxr9] provisioning: [worker] Tearing down Worker Plane..
2021/05/31 13:16:28 [INFO] cluster [c-jzxr9] provisioning: [worker] Successfully tore down Worker Plane..
2021/05/31 13:16:28 [INFO] cluster [c-jzxr9] provisioning: [controlplane] Tearing down the Controller Plane..
2021/05/31 13:16:28 [INFO] Removing container [kube-apiserver] on host [159.65.84.170], try           #1
2021/05/31 13:16:28 [INFO] cluster [c-jzxr9] provisioning: [remove/kube-apiserver] Successfully removed container on host [159.65.84.170]
2021/05/31 13:16:28 [INFO] Removing container [kube-controller-manager] on host [159.65.84.170], try           #1
2021/05/31 13:16:29 [INFO] cluster [c-jzxr9] provisioning: [remove/kube-controller-manager] Successfully removed container on host [159.65.84.170]
2021/05/31 13:16:29 [INFO] Removing container [kube-scheduler] on host [159.65.84.170], try           #1
2021/05/31 13:16:29 [INFO] cluster [c-jzxr9] provisioning: [remove/kube-scheduler] Successfully removed container on host [159.65.84.170]
2021/05/31 13:16:29 [INFO] Removing container [kubelet] on host [159.65.84.170], try           #1
2021/05/31 13:16:29 [INFO] cluster [c-jzxr9] provisioning: [remove/kubelet] Successfully removed container on host [159.65.84.170]
2021/05/31 13:16:30 [INFO] Removing container [kube-proxy] on host [159.65.84.170], try           #1
2021/05/31 13:16:30 [INFO] cluster [c-jzxr9] provisioning: [remove/kube-proxy] Successfully removed container on host [159.65.84.170]
2021/05/31 13:16:30 [INFO] Removing container [service-sidekick] on host [159.65.84.170], try           #1
2021/05/31 13:16:30 [INFO] cluster [c-jzxr9] provisioning: [remove/service-sidekick] Successfully removed container on host [159.65.84.170]
2021/05/31 13:16:30 [INFO] cluster [c-jzxr9] provisioning: [controlplane] Successfully tore down Controller Plane..
2021/05/31 13:16:30 [INFO] cluster [c-jzxr9] provisioning: [etcd] Tearing down etcd plane..
2021/05/31 13:16:30 [INFO] Removing container [etcd] on host [159.65.84.170], try           #1
2021/05/31 13:16:31 [INFO] cluster [c-jzxr9] provisioning: [remove/etcd] Successfully removed container on host [159.65.84.170]
2021/05/31 13:16:31 [INFO] cluster [c-jzxr9] provisioning: [etcd] Successfully tore down etcd plane..
2021/05/31 13:16:31 [INFO] cluster [c-jzxr9] provisioning: [hosts] Cleaning up host [159.65.84.170]
2021/05/31 13:16:31 [INFO] cluster [c-jzxr9] provisioning: [hosts] Cleaning up host [159.65.84.170]
2021/05/31 13:16:31 [INFO] cluster [c-jzxr9] provisioning: [hosts] Running cleaner container on host [159.65.84.170]
2021/05/31 13:16:31 [INFO] Image [rancher/rke-tools:v0.1.74] exists on host [159.65.84.170]
2021/05/31 13:16:31 [INFO] Starting container [kube-cleaner] on host [159.65.84.170], try           #1
2021/05/31 13:16:32 [INFO] cluster [c-jzxr9] provisioning: [kube-cleaner] Successfully started [kube-cleaner] container on host [159.65.84.170]
2021/05/31 13:16:32 [INFO] cluster [c-jzxr9] provisioning: Waiting for [kube-cleaner] container to exit on host [159.65.84.170]
2021/05/31 13:16:32 [INFO] cluster [c-jzxr9] provisioning: Container [kube-cleaner] is still running on host [159.65.84.170]: stderr: [find: /opt/rke/etc/kubernetes/.tmp: Resource busy
], stdout: []
2021/05/31 13:16:33 [INFO] cluster [c-jzxr9] provisioning: Waiting for [kube-cleaner] container to exit on host [159.65.84.170]
2021/05/31 13:16:34 [INFO] Removing container [kube-cleaner] on host [159.65.84.170], try           #1
2021/05/31 13:16:34 [INFO] cluster [c-jzxr9] provisioning: [hosts] Removing cleaner container on host [159.65.84.170]
2021/05/31 13:16:34 [INFO] cluster [c-jzxr9] provisioning: [hosts] Removing dead container logs on host [159.65.84.170]
2021/05/31 13:16:34 [INFO] Image [rancher/rke-tools:v0.1.74] exists on host [159.65.84.170]
2021/05/31 13:16:34 [INFO] Starting container [rke-log-cleaner] on host [159.65.84.170], try           #1
2021/05/31 13:16:35 [INFO] error in remotedialer server [400]: read tcp 172.17.0.2:443->167.99.202.104:26459: i/o timeout
2021/05/31 13:16:35 [INFO] cluster [c-jzxr9] provisioning: [cleanup] Successfully started [rke-log-cleaner] container on host [159.65.84.170]
2021/05/31 13:16:35 [INFO] Removing container [rke-log-cleaner] on host [159.65.84.170], try           #1
2021/05/31 13:16:35 [INFO] cluster [c-jzxr9] provisioning: [remove/rke-log-cleaner] Successfully removed container on host [159.65.84.170]
2021/05/31 13:16:35 [INFO] kontainerdriver rancherkubernetesengine stopped
2021/05/31 13:16:35 [INFO] cluster [c-jzxr9] provisioning: [hosts] Successfully cleaned up host [159.65.84.170]
2021/05/31 13:16:35 [INFO] cluster [c-jzxr9] provisioning: Removing local admin Kubeconfig: management-state/rke/rke-870658123/kube_config_cluster.yml
2021/05/31 13:16:35 [INFO] cluster [c-jzxr9] provisioning: Local admin Kubeconfig removed successfully
2021/05/31 13:16:35 [INFO] cluster [c-jzxr9] provisioning: Removing state file: management-state/rke/rke-870658123/cluster.rkestate
2021/05/31 13:16:35 [INFO] cluster [c-jzxr9] provisioning: State file removed successfully
2021/05/31 13:16:35 [INFO] cluster [c-jzxr9] provisioning: Cluster removed successfully
2021/05/31 13:16:35 [INFO] Deleted cluster [c-jzxr9]
2021/05/31 13:16:36 [INFO] [mgmt-cluster-rbac-remove] Deleting namespace c-jzxr9
2021/05/31 13:16:36 [INFO] error in remotedialer server [400]: read tcp 172.17.0.2:443->167.99.202.104:33118: i/o timeout
2021/05/31 13:16:38 [INFO] error in remotedialer server [400]: read tcp 172.17.0.2:443->167.99.202.95:51712: i/o timeout
2021/05/31 13:16:41 [INFO] [mgmt-auth-crtb-controller] Deleting roleBinding crb-2xwu4qbuip
2021/05/31 13:16:41 [INFO] [mgmt-auth-crtb-controller] Deleting rolebinding creator-cluster-owner-cluster-owner in namespace p-sgvv6 for crtb creator-cluster-owner
2021/05/31 13:16:41 [INFO] [mgmt-auth-crtb-controller] Deleting rolebinding creator-cluster-owner-cluster-owner in namespace p-6dx64 for crtb creator-cluster-owner
2021/05/31 13:16:41 [ERROR] [nodepool] reconcile erorr, create or check nodes: nodes.management.cattle.io "m-" is forbidden: unable to create new content in namespace c-jzxr9 because it is being terminated
2021/05/31 13:16:41 [ERROR] [nodepool] reconcile erorr, create or check nodes: nodes.management.cattle.io "m-" is forbidden: unable to create new content in namespace c-jzxr9 because it is being terminated
2021/05/31 13:16:41 [INFO] Removing node mkravecm1
2021/05/31 13:16:41 [INFO] Removing node mkravecw1
2021/05/31 13:16:41 [INFO] [node-controller-rancher-machine] About to remove mkravecm1
2021/05/31 13:16:41 [INFO] [node-controller-rancher-machine] WARNING: This action will delete both local reference and remote instance.
2021/05/31 13:16:41 [ERROR] [nodepool] reconcile erorr, create or check nodes: nodes.management.cattle.io "m-" is forbidden: unable to create new content in namespace c-jzxr9 because it is being terminated
2021/05/31 13:16:41 [INFO] [node-controller-rancher-machine] About to remove mkravecw1
2021/05/31 13:16:41 [INFO] [node-controller-rancher-machine] WARNING: This action will delete both local reference and remote instance.
2021/05/31 13:16:41 [ERROR] [nodepool] reconcile erorr, create or check nodes: nodes.management.cattle.io "m-" is forbidden: unable to create new content in namespace c-jzxr9 because it is being terminated
2021/05/31 13:16:41 [ERROR] [nodepool] reconcile erorr, create or check nodes: nodes.management.cattle.io "m-" is forbidden: unable to create new content in namespace c-jzxr9 because it is being terminated
2021/05/31 13:16:41 [ERROR] [nodepool] reconcile erorr, create or check nodes: nodes.management.cattle.io "m-" is forbidden: unable to create new content in namespace c-jzxr9 because it is being terminated
2021/05/31 13:16:41 [ERROR] [nodepool] reconcile erorr, create or check nodes: nodes.management.cattle.io "m-" is forbidden: unable to create new content in namespace c-jzxr9 because it is being terminated
2021/05/31 13:16:41 [ERROR] [nodepool] reconcile erorr, create or check nodes: nodes.management.cattle.io "m-" is forbidden: unable to create new content in namespace c-jzxr9 because it is being terminated
2021/05/31 13:16:41 [INFO] [nodepool] deleting np-4zm6h
2021/05/31 13:16:41 [INFO] [nodepool] deleting np-lxkzl
2021/05/31 13:16:42 [INFO] [mgmt-auth-users-controller] Deleting projectRoleTemplateBinding u-7rlazmgz6b-member for user u-7rlazmgz6b
2021/05/31 13:16:42 [INFO] [mgmt-auth-users-controller] Deleting projectRoleTemplateBinding u-xv5cqvkprz-member for user u-xv5cqvkprz
2021/05/31 13:16:42 [INFO] [mgmt-project-rbac-remove] Deleting namespace p-6dx64
2021/05/31 13:16:42 [INFO] [mgmt-project-rbac-remove] Deleting namespace p-sgvv6
2021/05/31 13:16:42 [INFO] [mgmt-auth-users-controller] Deleting globalRoleBinding grb-8c5xg for user u-7rlazmgz6b
2021/05/31 13:16:42 [INFO] [mgmt-auth-users-controller] Deleting globalRoleBinding grb-pvfcz for user u-xv5cqvkprz
2021/05/31 13:16:42 [INFO] [mgmt-auth-prtb-controller] Deleting roleBinding rb-veppks6evk
2021/05/31 13:16:42 [INFO] [mgmt-auth-prtb-controller] Deleting roleBinding rb-hhdetjb73f
2021/05/31 13:16:42 [INFO] [mgmt-auth-prtb-controller] Deleting roleBinding crb-6hb6xkpbej
2021/05/31 13:16:42 [INFO] [mgmt-auth-prtb-controller] Deleting roleBinding crb-bhzoimjlxw
2021/05/31 13:16:42 [INFO] [mgmt-auth-prtb-controller] Deleting rolebinding p-6dx64-u-7rlazmgz6b-member-project-member in namespace c-jzxr9 for prtb u-7rlazmgz6b-member
2021/05/31 13:16:42 [INFO] [mgmt-auth-prtb-controller] Deleting rolebinding p-sgvv6-u-xv5cqvkprz-member-project-member in namespace c-jzxr9 for prtb u-xv5cqvkprz-member
2021/05/31 13:16:44 [ERROR] [nodepool] error updating reconcile annotation to updated: [nodepool] Failed to update nodePool annotation [np-4zm6h]: timed out waiting for the condition
2021/05/31 13:16:44 [ERROR] [nodepool] error updating reconcile annotation to updated: [nodepool] Failed to update nodePool annotation [np-lxkzl]: timed out waiting for the condition
2021/05/31 13:16:44 [INFO] [node-controller-rancher-machine] Successfully removed mkravecm1
2021/05/31 13:16:44 [INFO] [node-controller-rancher-machine] (mkravecm1) Closing plugin on server side
2021/05/31 13:16:44 [INFO] Removing node mkravecm1 done
2021/05/31 13:16:44 [ERROR] error syncing 'c-jzxr9/m-8hpnv': handler node-controller: ClusterUnavailable 503: ClusterUnavailable 503: cluster not found, requeuing
2021/05/31 13:16:44 [ERROR] error syncing 'c-jzxr9': handler cluster-watch: clusterregistrationtokens.management.cattle.io "default-token" is forbidden: unable to create new content in namespace c-jzxr9 because it is being terminated, requeuing
2021/05/31 13:16:44 [ERROR] error syncing 'c-jzxr9': handler cluster-watch: clusterregistrationtokens.management.cattle.io "default-token" is forbidden: unable to create new content in namespace c-jzxr9 because it is being terminated, requeuing
2021/05/31 13:16:44 [ERROR] error syncing 'c-jzxr9': handler cluster-watch: clusterregistrationtokens.management.cattle.io "default-token" is forbidden: unable to create new content in namespace c-jzxr9 because it is being terminated, requeuing
2021/05/31 13:16:44 [ERROR] error syncing 'c-jzxr9/m-8hpnv': handler node-controller: ClusterUnavailable 503: ClusterUnavailable 503: cluster not found, requeuing
2021/05/31 13:16:44 [ERROR] error syncing 'c-jzxr9/m-8hpnv': handler node-controller: ClusterUnavailable 503: ClusterUnavailable 503: cluster not found, requeuing
2021/05/31 13:16:44 [ERROR] error syncing 'c-jzxr9/m-8hpnv': handler node-controller: ClusterUnavailable 503: ClusterUnavailable 503: cluster not found, requeuing
2021/05/31 13:16:44 [ERROR] error syncing 'c-jzxr9/m-8hpnv': handler node-controller: ClusterUnavailable 503: ClusterUnavailable 503: cluster not found, requeuing
2021/05/31 13:16:44 [ERROR] error syncing 'c-jzxr9': handler cluster-watch: clusterregistrationtokens.management.cattle.io "default-token" is forbidden: unable to create new content in namespace c-jzxr9 because it is being terminated, requeuing
2021/05/31 13:16:44 [ERROR] error syncing 'c-jzxr9/m-8hpnv': handler node-controller: ClusterUnavailable 503: ClusterUnavailable 503: cluster not found, requeuing
2021/05/31 13:16:45 [ERROR] error syncing 'c-jzxr9/m-8hpnv': handler node-controller: ClusterUnavailable 503: ClusterUnavailable 503: cluster not found, requeuing
2021/05/31 13:16:45 [INFO] [node-controller-rancher-machine] Successfully removed mkravecw1
2021/05/31 13:16:45 [INFO] [node-controller-rancher-machine] (mkravecw1) Closing plugin on server side
2021/05/31 13:16:45 [INFO] Removing node mkravecw1 done
2021/05/31 13:16:45 [ERROR] error syncing 'c-jzxr9/m-gnlrj': handler node-controller: ClusterUnavailable 503: ClusterUnavailable 503: cluster not found, requeuing
2021/05/31 13:16:45 [ERROR] error syncing 'c-jzxr9/m-8hpnv': handler node-controller: ClusterUnavailable 503: ClusterUnavailable 503: cluster not found, requeuing
2021/05/31 13:16:45 [ERROR] error syncing 'c-jzxr9/m-gnlrj': handler node-controller: ClusterUnavailable 503: ClusterUnavailable 503: cluster not found, requeuing
2021/05/31 13:16:45 [ERROR] error syncing 'c-jzxr9/m-gnlrj': handler node-controller: ClusterUnavailable 503: ClusterUnavailable 503: cluster not found, requeuing
2021/05/31 13:16:45 [ERROR] error syncing 'c-jzxr9/m-gnlrj': handler node-controller: ClusterUnavailable 503: ClusterUnavailable 503: cluster not found, requeuing
2021/05/31 13:16:45 [ERROR] error syncing 'c-jzxr9/m-gnlrj': handler node-controller: ClusterUnavailable 503: ClusterUnavailable 503: cluster not found, requeuing
2021/05/31 13:16:45 [ERROR] error syncing 'c-jzxr9/m-gnlrj': handler node-controller: ClusterUnavailable 503: ClusterUnavailable 503: cluster not found, requeuing
2021/05/31 13:16:46 [ERROR] error syncing 'c-jzxr9/m-8hpnv': handler node-controller: ClusterUnavailable 503: ClusterUnavailable 503: cluster not found, requeuing
2021/05/31 13:16:46 [ERROR] error syncing 'c-jzxr9/m-gnlrj': handler node-controller: ClusterUnavailable 503: ClusterUnavailable 503: cluster not found, requeuing
2021/05/31 13:16:46 [ERROR] error syncing 'c-jzxr9/m-gnlrj': handler node-controller: ClusterUnavailable 503: ClusterUnavailable 503: cluster not found, requeuing
2021/05/31 13:16:46 [ERROR] error syncing 'c-qbhdj/m-vdj87': handler node-controller: ClusterUnavailable 503: ClusterUnavailable 503: cluster not found, requeuing
2021/05/31 13:16:46 [ERROR] error syncing 'c-6w448': handler cluster-watch: clusterregistrationtokens.management.cattle.io "default-token" is forbidden: unable to create new content in namespace c-6w448 because it is being terminated, requeuing
2021/05/31 13:16:46 [ERROR] error syncing 'c-qbhdj/m-t8zd9': handler node-controller: ClusterUnavailable 503: ClusterUnavailable 503: cluster not found, requeuing
2021/05/31 13:16:47 [ERROR] error syncing 'c-jzxr9/m-gnlrj': handler node-controller: ClusterUnavailable 503: ClusterUnavailable 503: cluster not found, requeuing
2021/05/31 13:16:47 [INFO] kontainerdriver rancherkubernetesengine listening on address 127.0.0.1:40657
2021/05/31 13:16:47 [INFO] kontainerdriver rancherkubernetesengine stopped
2021/05/31 13:16:47 [WARNING] secrets "cattle-system/c-c-jzxr9" not found
2021/05/31 13:16:47 [ERROR] error syncing 'c-jzxr9/m-8hpnv': handler node-controller: ClusterUnavailable 503: ClusterUnavailable 503: cluster not found, requeuing
2021/05/31 13:16:47 [INFO] [mgmt-auth-prtb-controller] Updating owner label for roleBinding crb-xxduqasa5k
2021/05/31 13:16:47 [INFO] [mgmt-auth-prtb-controller] Deleting roleBinding crb-xxduqasa5k
2021/05/31 13:16:48 [ERROR] error syncing 'c-jzxr9/m-gnlrj': handler node-controller: ClusterUnavailable 503: ClusterUnavailable 503: cluster not found, requeuing
2021/05/31 13:16:49 [ERROR] error syncing 'c-jzxr9/m-8hpnv': handler node-controller: ClusterUnavailable 503: ClusterUnavailable 503: cluster not found, requeuing
2021/05/31 13:16:50 [ERROR] error syncing 'c-jzxr9/m-gnlrj': handler node-controller: ClusterUnavailable 503: ClusterUnavailable 503: cluster not found, requeuing
2021/05/31 13:16:53 [INFO] kontainerdriver rancherkubernetesengine listening on address 127.0.0.1:36361
2021/05/31 13:16:53 [INFO] kontainerdriver rancherkubernetesengine stopped
2021/05/31 13:16:53 [WARNING] secrets "cattle-system/c-c-jzxr9" not found
2021/05/31 13:16:54 [ERROR] error syncing 'c-bj6rq/m-k9k5b': handler node-controller: ClusterUnavailable 503: ClusterUnavailable 503: cluster not found, requeuing
2021/05/31 13:16:54 [ERROR] error syncing 'c-bj6rq/m-hpb4w': handler node-controller: ClusterUnavailable 503: ClusterUnavailable 503: cluster not found, requeuing
2021/05/31 13:16:55 [ERROR] error syncing 'c-jzxr9/m-8hpnv': handler node-controller: ClusterUnavailable 503: ClusterUnavailable 503: cluster not found, requeuing
2021/05/31 13:16:55 [ERROR] error syncing 'c-jzxr9': handler cluster-watch: clusterregistrationtokens.management.cattle.io "default-token" is forbidden: unable to create new content in namespace c-jzxr9 because it is being terminated, requeuing
2021/05/31 13:16:55 [ERROR] error syncing 'c-6w448/m-66wtm': handler node-controller: ClusterUnavailable 503: ClusterUnavailable 503: cluster not found, requeuing
2021/05/31 13:16:56 [ERROR] error syncing 'c-jzxr9/m-gnlrj': handler node-controller: ClusterUnavailable 503: ClusterUnavailable 503: cluster not found, requeuing
```
</details>

Tested on master-head (5d49b92)

Works fine on rancher 2.5.7 and 2.5-head (74a37df)

**Comment by sowmyav27** [comment] 2021-06-01 19:34
Similar issue - https://github.com/rancher/rancher/issues/32689

**Comment by deniseschannon** [comment] 2021-08-02 21:40
Not sure if this is still reproducible, so verify if it is.

**Comment by kinarashah** [comment] 2021-08-03 20:37
Unable to reproduce. Moving it to test.

**Comment by aaronRancher** [comment] 2021-08-04 00:03
Tested on Rancher `master-head` `version 0972c3a` with the following steps:
Provision a few DO clusters. (RKEv1 and RKEv2)
After clusters become active, remove clusters.

Result:
Before delete:
![Screen Shot 2021-08-03 at 4 53 18 PM](https://user-images.githubusercontent.com/57409052/128101250-0c17764f-f3f1-4318-87b9-f8d17b95e26e.png)
After delete:
![Screen Shot 2021-08-03 at 4 53 47 PM](https://user-images.githubusercontent.com/57409052/128101256-4d3158b5-5016-437d-bc60-2133ca0abce9.png)
Was not able to bring up RKEv2 clusters. This is a known issue. Clusters are cleaned up without being stuck in removing state. Verified on Ember UI and Dashboard. I am unable to reproduce this issue.

**Closed** 2021-08-04 15:42 UTC
Labels: [zube]: QA Next up, area/rke2, kind/bug-qa
