### ISSUE TITLE
Unhealthy controller-manager and scheduler after fresh install of Rancher and AKS

### ISSUE THREAD

**Issue by IanMoroney** [rancher/rancher#13249] opened 2018-05-02 14:50 UTC
**Rancher versions:**
rancher/rancher:stable
rancher/rancher-agent:stable

**Infrastructure Stack versions:**
kubernetes (if applicable): 1.8.1

**Docker version: (`docker version`,`docker info` preferred)**
default rancher v2.0.0 docker version on AKS

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
Azure AKS

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
Single node rancher v2.0.0

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**
Kubernetes

**Steps to Reproduce:**
Deploy a new Rancher v2.0.0 instance
Deploy a new Azure AKS instance through Rancher
Open dashboard for instance in Rancher

**Results:**

Alert: Component controller-manager is unhealthy.
Alert: Component scheduler is unhealthy.

I believe that this may be occurring because the cloud provider is not being set by Rancher.

**Comment by superseb** [comment] 2018-05-02 15:07
Duplicate of https://github.com/rancher/rancher/issues/11496

**Closed by superseb** 2018-05-02 15:07 UTC
