### ISSUE TITLE
Monitoring - NodeSelector does not work

### ISSUE THREAD

**Issue by SkySonR** [rancher/rancher#22955] opened 2019-09-19 09:04 UTC
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
Add label on specific node
Deploy monitoring with NodeSelector parametes selected

**Result:**
Monitoring workloads scheduled on different nodes.
Any of NodeSelector or NodeAffinity does not exist in the components yaml files
**Other details that may be helpful:**
Rancher 2.2.7 deployed as helm chart to EKS cluster

**Comment by deniseschannon** [comment] 2019-10-01 20:10
Duplicate of https://github.com/rancher/rancher/issues/22760

Fixed in v2.3.

**Closed by deniseschannon** 2019-10-01 20:10 UTC
Labels: kind/bug
