### ISSUE TITLE
Bug: all catalogs get x509 errors when using s3 snapshots on Rancher v2.3.2

### ISSUE THREAD

**Issue by patrick0057** [rancher/rancher#24347] opened 2019-12-02 22:04 UTC
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
1) Setup HA Rancher installation v2.3.2 using your own set of private signed certificates.
2) create downstream cluster
3) setup s3 snapshots, use shorter snapshot periods and retention to reproduce faster

**Result:**
Observe when snapshots finally rotate through and delete the oldest snapshot that the catalog's in Rancher now have x509 errors.

**Other details that may be helpful:**
If you update the Rancher deployment it will delete the Rancher pods and fix the problem temporarily until the next time snapshots are cycled through.

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): v2.3.2
- Installation option (single install/HA): HA

**Comment by sowmyav27** [comment] 2019-12-04 16:03
**Reproduced the issue on `2.3.3`**

**Steps:**

1. Bring up a minio with self signed certs
2. On a rancher server with self-signed certificate that it generates, create an AWS cluster.
3. Enter the minio details for the S3 config in the cluster, and enter CA cert generated in Step 1 in field Custom CA Certificate 
4. When the cluster comes up Active, after manual delete of snapshots or the automatic deletion of snapshot, on ADDITION of a new catalog like "https://charts.rook.io/beta, branch:master" gives the error. On refresh of existing catalog, NO error is seen.
5. The issue is also seen when the S3 settings are modified, i.e. change the bucket name. On Listing Snapshots, NO issue was seen. 
6. Stop and start of Rancher server.
7. The catalogs recover and are seen Active. And Apps are available from these catalogs.


**Verified on `v2.3-head` commit id: `430dd0bb3`**

**Steps:**
1. Bring up a minio with self signed certs
2. On a rancher server with self-signed certificate that it generates, create an AWS cluster.
3. Enter the minio details for the S3 config in the cluster, and enter CA cert generated in Step 1 in field Custom CA Certificate 
4. When the cluster comes up Active, after manual delete of snapshots or the automatic deletion of snapshot, on ADDITION of a new catalog like "https://charts.rook.io/beta, branch:master" NO error is seen.
5. Modify S3 settings, i.e. change the bucket name in the cluster.
6. No error is seen on ADDITION of a new catalog like "https://charts.rook.io/release, branch:master" NO error is seen.

**Comment by sowmyav27** [comment] 2019-12-05 20:04
Closing the issue

**Closed by sowmyav27** 2019-12-05 20:04 UTC
Labels: [zube]: To Test, area/catalog, kind/bug
