### ISSUE TITLE
certificate rotate doesnt work on older rancher created clusters

### ISSUE THREAD

**Issue by aemneina** [rancher/rancher#20381] opened 2019-05-22 06:29 UTC
**What kind of request is this (question/bug/enhancement/feature request):**
bug

**Steps to reproduce (least amount of steps as possible):**
have a cluster with expired certs, created with an older version of rancher 2.x (2.0.7)
run cert rotate from the ui. 

**Result:**
errors ensue

**workaround:**
```#rotate certs from clusters created via rancher ui
#backup /etc/kubernetes
tar cvjf ~/k8s_config.tar.bz2 /etc/kubernetes

#create a cluster.yml file copy it to cluster-state.yml under the /etc/kubernetes/.tmp folder

#create missing certs
cd /opt/rke/etc/kubernetes/.tmp or /etc/kubernetes/.tmp
cp kube-ca.pem kube-apiserver-requestheader-ca.pem
cp kube-ca-key.pem kube-apiserver-requestheader-ca-key.pem
cp kube-apiserver.pem kube-apiserver-proxy-client.pem 
cp kube-apiserver-key.pem kube-apiserver-proxy-client-key.pem 


#need to use rancher v2.2.3+
execute rotate certs from UI for this cluster.
```
thanks to @galal-hussein for developing the workaround :D

**Comment by galal-hussein** [comment] 2019-05-28 17:57
After debugging the problem, I found that the root cause is that on older cluster we don't save the `cluster-state.yml` file on the nodes, so in rke 0.2.x it tries to pull the state to update legacy clusters, but it can't find it and breaks.

**Comment by alena1108** [comment] 2019-05-28 22:51
The issue will happen when you:

1) Have a cluster provisioned by Rancher v2.0.x. In this version of rancher/rke the cluster state wasn't stored on disk (it got added in Rancher v2.1 only)
2) Hit the cert expiration
3) Upgrade to 2.2
4) Call rotate certificates from Rancher UI. It will break as RKE 2.2 expects legacy clusters to have a cluster state on the nodes.

**Comment by alena1108** [comment] 2019-05-29 23:28
The changes can be tested with `v2.2.4-rc19`

**Comment by alena1108** [comment] 2019-05-29 23:29
No backport issue is created as we have to test the fix as a part of the upgrade to 2.2.4

**Comment by sowmyav27** [comment] 2019-05-31 00:51
verified the below scenarios:
1. rancher server and cluster expired using test image(30 mins expiry) and upgraded to v2.2.4-rc20
**post upgrade steps:**
- The cluster is seen in `Provisioning` state for more than 10 minutes.
- On doing a `Rotate Certificates` on the UI, the worker nodes are seen stuck in `Unavailable` status - `Kubelet stopped posting node status.` message is seen.
- On the worker node - the `kubelet` pod is seen restarted after the rotate certificates action.

2. rancher server expired and user cluster still active using test image(30 mins expiry) and upgraded to v2.2.4-rc20
**Post upgrade steps:**
- Wait for the user cluster certs to expire.
- After expiry, the Kubectl from the Rancher UI does not work - shows `Error 1006`.
- The cluster is seen `Active`. But not able to deploy any workloads
- No error seen on the UI.
- Remote `kubectl` works. Nodes/pods are listed successfully.

3. rancher server expired and user cluster still active using test image(30 mins expiry) and upgraded to v2.2.4-rc20
**post upgrade steps:**
- Before the cluster expires do a cert rotate.
- The cluster comes up active - no issues.

**Comment by sangeethah** [comment] 2019-06-03 15:29
@alena1108 @galal-hussein , We also have a problem that when users upgrade from 2.0.7 to 2.2.4-rc20 and wait for the cert to expire , we still dont see any proper indication on the rancher server about cert expiry. This is something we need to address  or if it cannot be addressed , understand why we see this behavior. 
This is noted in 2nd scenario in the previous comments:

```
After expiry, the Kubectl from the Rancher UI does not work - shows Error 1006.
The cluster is seen Active. But not able to deploy any workloads
No error seen on the UI. -- **Issue**
Remote kubectl works. Nodes/pods are listed successfully.
```

**Comment by galal-hussein** [comment] 2019-06-03 16:25
As described in the comment https://github.com/rancher/rancher/issues/20381#issuecomment-496718848 the issue happen because the cattle node agent pod isn't get updated on each worker node so it only pull the new certificates but doesn't restart the corresponding components.

To recover from this situation:

- ssh to each **worker** node
- restart kubelet, kube-proxy containers:
```
docker restart kubelet kube-proxy
```

**Comment by sowmyav27** [comment] 2019-06-03 18:32
verified this issue 
Upgrade from: `test image 2.0.13 to v2.2.4-rc21`
**Scenario 1: Steps:**
1. Have a cluster setup in the test image given. (3 etcd, 1 control plane, 3 worker nodes)
2. Let the Rancher server and the user cluster expire.
3. Upgrade to rancher:v2.2.4-rc21.
4. The cluster will be seen in `Provisioning` state.
<img width="1523" alt="Screen Shot 2019-06-03 at 10 57 24 AM" src="https://user-images.githubusercontent.com/26032343/58823776-59190280-85ef-11e9-870a-aad898bac271.png">

5. Cluster changed from `Provisioning`(Red) - `Updating` (Yellow)
6. It goes into `Updating` (Red) - with message - `[workerPlane] Failed to bring up Worker Plane: [error during connect: Get http://%2Fvar%2Frun%2Fdocker.sock/v1.24/containers/nginx-proxy/json: failed to find Session for client c-qvfl8:m-82ln9]`
7. The cluster will finally come up, and be seen as `Active`
8. On checking the nodes, we can see the worker nodes to be in `Unavailable` state with message - `Kubelet stopped posting node status.`
9. ssh to each worker nodes
10. restart kubelet, kube-proxy containers: `docker restart kubelet kube-proxy`
11. The nodes will recover and will be seen in `Active` state.
12. Verified that the certs have rotated.
13. Verified that the certs have new expiry dates, 10 years from when the action was performed.

**Comment by alena1108** [comment] 2019-06-03 18:58
A brief summary. This issue is an umbrella for 2 issues. 

```
Issue #1 

* Cluster got created on a version 2.0.13 or earlier.
* Before cluster expired, the setup is upgraded to 2.2.x. Then the certs expire.
* Try to rotate the certs on the cluster, and it breaks.

Issue #2

* Cluster got created on a) 2.0.13 or earlier on 2.0 release line b) 2.1.8 or earlier on 2.1 release line, and its certs expired while being on that version.
* The setup is upgraded to 2.2.x.
* Try to rotate the certs on the cluster, and it breaks.

The issue #2 doesn't happen if you upgraded the cluster to 2.0.14 or 2.1.10 prior to certs expiry/upgrade to 2.2.x
```

Both issues won't happen if you've upgraded to 2.0.1

Issue 1 got fixed with https://github.com/rancher/rke/pull/1370. 
Issue 2 is described in this comment https://github.com/rancher/rancher/issues/20381#issuecomment-498328274. For 2.2.4 release, the affected setups should be updated using the workaround.

**Comment by alena1108** [comment] 2019-06-10 16:49
If you are upgrading from the older versions of Rancher - 2.0.13 or earlier, or 2.1.8 or earlier, and your clusters have the certificates expired, some manual steps would be needed in order for the rotation to go through:

```
1) For control and etcd nodes: login to the corresponding hosts, and:

* cd /etc/kubernetes/.tmp
* check if kube-apiserver-requestheader-ca.pem exists. If not, perform the following commands:

cp kube-ca.pem kube-apiserver-requestheader-ca.pem
cp kube-ca-key.pem kube-apiserver-requestheader-ca-key.pem
cp kube-apiserver.pem kube-apiserver-proxy-client.pem
cp kube-apiserver-key.pem kube-apiserver-proxy-client-key.pem

2) Call rotateCertificates. After the command is finished, check if the worker nodes are Active. 
If not, login to each worker node and restart kubelet and proxy

```

**Comment by spawnia** [comment] 2019-06-28 15:56
I updated from v2.1.7 to v2.2.2 after the certificates were expired. I went into the UI and clicked `Rotate Certificates`. Now the UI shows:

```
This cluster is currently Updating; areas that interact directly with it will not be available until the API is ready.

Failed to rotate certificates: can't find old certificates
```

I SSH'ed into the workers and restarted both kubelet and proxy. However, when looking into the etcd and ctrl plane, the directory `/etc/kubernetes/.tmp` does not exist.

**Comment by galal-hussein** [comment] 2019-08-26 17:51
@spawnia you can copy the entier ssl certificate to .tmp:
```
cp -r /etc/kubernetes/ssl /etc/kubernetes/.tmp
```
and then trigger another certificate rotation, this should be enough to fetch the old certs and proceed the rotation normally

**Comment by galal-hussein** [comment] 2019-08-29 20:48
The [fix](https://github.com/rancher/rke/pull/1608) will handle the following:

- handle missing aggregation layer certs on upgrades
- return error if **keys or config** for any cert is missing

Steps to verify:

1- verify that cluster without aggregation layer certs will be rotated normally:
    - start a cluster with rke 0.1.8 with custom certificate expiration time (30 min)
    - wait until certificates are expired
    - run rke cert rotate with latest version

Result: the cluster certificates should be rotated normally without any manual steps

2- verify that the cluster with missing certs will be error out with the right log message:
    - start rke cluster with 1 node ALL roles
    - manually remove /etc/kubernetes/ssl/kube-apiserver.pem
    - run rke cert rotate 

Result: rke should fail with an error saying that /etc/kubernetes/ssl/kube-apiserver.pem is missing.

**Comment by sowmyav27** [comment] 2019-09-03 23:48
Verified with a custom rke image - with 10 minutes expiry

**Steps:**

1. verify that cluster without aggregation layer certs will be rotated normally:
- start a cluster with rke 0.1.8 with custom certificate expiration time (30 min)
- wait until certificates are expired
- run rke cert rotate with latest version (rke version v0.3.0-rc9)

**Result:** 
the cluster certificates are rotated normally without any manual steps. And the certs have expiry of 10 years.
And the following files are available on the control plane node.
```
kube-apiserver-requestheader-ca.pem
kube-apiserver-requestheader-ca-key.pem
kube-apiserver-proxy-client.pem
kube-apiserver-proxy-client-key.pem
```

**Closed** 2019-09-04 02:39 UTC
Labels: [zube]: To Test, area/certificate, area/cluster, internal, kind/bug, team/ca

**Comment by tg44** [comment] 2019-09-30 16:41
I still have this error. Single rancher node, single k8s node. If I click to the rotate nothing happens, the k8s node has the .tmp dir, has all the keys, but the dates on the files not updating so I think even the rotate message is "lost". I think I need to somehow update one or more containers on the k8s instance too... 

(I have all the files, only the `cluster-state.yml` is missing bcs I have no idea where I can find the original, or how I can write a new one.) 

Probably a documentation about the error and about how these things are connected would let more ppl to try and fix it by hand, when the "automatic" methods are failing. (I think yesterday I read most of the documentation and issues about this topic, but I have no idea where should I go next to learn more and finally fix my "cluster".)

**Comment by jrab66** [comment] 2020-02-11 14:10
having the same issue :/ already update rancher 2.2.8 but my old added clusters with expired cert cannot be reached or perform the cert rotation :/

**Comment by tg44** [comment] 2020-02-11 23:29
I fixed this with: https://github.com/rancher/rancher/issues/20822 I think I needed to change one line in a yaml, and everything started to come back...
