### ISSUE TITLE
Accounts Page Not Showing Account User Names

### ISSUE THREAD

**Issue by writeameer** [rancher/rancher#3181] opened 2016-01-07 00:14 UTC
Hi there,

The accounts page in the following URL:

	https://<my rancher url>/admin/accounts

Shows "black holes" under identity:

![blackhole](https://cloud.githubusercontent.com/assets/221149/12158600/71431934-b52f-11e5-9dd6-30b4f3cd3b6e.png)

However, when I edit the account using the drop down on the far right, I am able to view the user's identity:

![username](https://cloud.githubusercontent.com/assets/221149/12158601/7172fad2-b52f-11e5-804f-965befd48663.png)

Our users are sourced from an Active Directory. I wasn't sure if there was something I was doing wrong ? If not, can we please have the user identity listed instead of a black hole ? Thank you.

Ameer Deen.

**Comment by deniseschannon** [comment] 2016-01-07 03:55
This is a duplicate of https://github.com/rancher/rancher/issues/3139.

Basically, Identity APIs are returning 404 (for all authentication types).

**Closed by deniseschannon** 2016-01-07 03:55 UTC
Labels: area/ui, release/v1.0.0
