### ISSUE TITLE
CIS scan downstream cluster with project network isolation activated fails at 5.3.2 Hardended:

### ISSUE THREAD

**Issue by asemen2608** [rancher/rancher#30211] opened 2020-11-24 07:23 UTC
**What kind of request is this (question/bug/enhancement/feature request):**
bug

**Steps to reproduce (least amount of steps as possible):**

On CIS scan, on a downstream cluster with project network isolation activated, the scan fails at 5.3.2:

**Result:**

Scan fails at 5.3.2:
With error message “Ensure that all Namespaces have Network Policies defined (Scored)”

**Other details that may be helpful:**

**Environment information**

- Rancher version (rancher/rancher/rancher/server image tag or shown bottom left in the UI): Rancher v2.4.8
- Installation option (single install/HA): Install/HA
- k8s 1.18.10 on
- both upstream and downstream clusters on-prem, RKE.

After adding a network policy “default-allow-all” in all namespaces 5.3.2 it will pass.
But, it will disable project network isolation policies.

CIS scan should pass at this point, as network policies are all in namespaces, because of the Project Network Isolation.

Rancher project network isolation enabled on the downstream cluster.
Leads to network policies being defined in all namespaces:

```
$ kubectl get networkpolicies -n test-ns
NAME         POD-SELECTOR   AGE
hn-nodes     <none>         373d
np-default   <none>         373d
```

“np-default” ensures project network isolation, it allows communication with workloads in system project and the own project.

```
$ kubectl get networkpolicies np-default -o yaml -n test-ns
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  creationTimestamp: "2019-11-11T08:21:23Z"
  generation: 1
  labels:
    cattle.io/creator: norman
    field.cattle.io/projectId: p-zb96b
  name: np-default
  namespace: test-ns
  resourceVersion: "605999"
  selfLink: /apis/networking.k8s.io/v1/namespaces/test-ns/networkpolicies/np-default
  uid: 56cbc761-6ed1-4410-ac13-ce178ab052a5
spec:
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          field.cattle.io/projectId: p-zb96b
    - namespaceSelector:
        matchLabels:
          field.cattle.io/projectId: p-qpxm5
  podSelector: {}
```

![cis-scan_](https://user-images.githubusercontent.com/61939253/100061155-f001fc00-2e2d-11eb-93f9-392a52bb6971.png)

gz#13497
gz#15399

**Comment by maggieliu** [comment] 2020-11-24 18:45
@sowmyav27 Can we check and see if this can be reproduced in 2.4?

**Comment by kinarashah** [comment] 2020-11-24 18:47
We don't create network policies for namespaces in system project, so need to exclude those namespaces here https://github.com/rancher/security-scan/blob/master/package/helper_scripts/check_for_network_policies.sh#L11

**Comment by aaronRancher** [comment] 2021-01-12 23:26
The bug is reproduced with Rancher server `rancher\rancher:v2.4.8`

Steps:
Deploy a downstream cluster with network isolation.
Run a hardened CIS scan.

Result:
Scan fails at 5.3.2:
Errors with `Ensure that all Namespaces have Network Policies defined (Scored)`
![Screen Shot 2021-01-11 at 5 18 40 PM](https://user-images.githubusercontent.com/57409052/104383647-65fd1800-54ed-11eb-908c-1a6dc7213399.png)

**Comment by deniseschannon** [comment] 2021-02-05 21:32
I don't believe that removing the check for network policies in the namespaces of the system project is the correct path forward as the suggested change would impact ALL scans. This needs a further discussion of how this should be accomplished.

**Comment by ryansann** [comment] 2021-04-07 00:35
In Rancher v2.5.x there is a new process for running CIS Scans. To run a scan, navigate to the Cluster Explorer and do the following:
- Install the CIS Operator
- Navigate to `Cluster Applications > CIS Benchmark`
- Create a new, one-time scan with profile: `rke-profile-hardened-1.6`
- Allow the scan to run and once completed, click into it to view the results

Following these steps, I am able to reproduce the issue in v2.5.x

The scan is failing due to namespaces in the system project not having NetworkPolicy resources. Having no NetworkPolicy resources is the same as having a NetworkPolicy resource that allows all ingress and egress traffic to/from the namespace. So the solution I've implemented is to create a NetworkPolicy resource in each system namespace that allows all traffic. The NetworkPolicy is named `np-allow-all`. Adding these to the system project namespaces allows the scan to pass at `5.3.2`.

There is a small caveat here where we only want to add the `np-allow-all` NetworkPolicy if there isn't already an existing NetworkPolicy, this is because we will end up overriding any existing ones. This applies to certain namespaces like `fleet-system`.

I am testing various cases related to this fix.

**Comment by ryansann** [comment] 2021-04-08 23:50
The associated PR, fixes the CIS Scan issue seen when PNI is enabled. It does this using the methodology outlined above.

Passing Scan:
![cis-scan-with-pni](https://user-images.githubusercontent.com/8824599/114109455-26df2880-988a-11eb-8745-8e78f45c2d79.png)

There were a decent amount of changes in the networkpolicy controllers, so I've validated the functionality with the following:

## Test Cases

### Namespace Creation

1. Create namespace in no project
    - Expected: no rancher network policies added
    - Result: [PASS]
2. Create namespace in default project
    - Expected: non system project network policies added, hn-nodes and np-default
    - Result: [PASS]
3. Create namespace in system project 
    - Expected: system project network policies added, np-default-allow-all
    - Result: [PASS]
4. Create new project and create namespace in it
    - Expected: non system project network policies added, hn-nodes and np-default
    - Result: [PASS]

### Namespace Moving

NOTE: I fixed a bug related to moving namespaces, and that fix is a pre-requisite for these tests.

1. Move namespace w/ no network policies from no project to non system project
    - Initial: no network policies
    - Expected: hn-nodes and np-default
    - Result: [PASS]
2. Move namespace w/ user network policies from no project to non system project
    - Initial: user network policies
    - Expected: hn-nodes and np-default added, user netowrk policies retained
    - Result: [PASS]
3. Move namespace w/ no network policies from no project to system project
    - Initial: no network policies
    - Expected: np-default-allow-all
    - Result: [PASS] 
4. Move namespace w/ user network policies from no project to system project
    - Initial: user network policies
    - Expected: np-default-allow-all not added, user network policies retained
    - Result: [PASS]
5. Move namespace w/ no user network policies from default project to system project
    - Initial: hn-nodes, np-default
    - Expected: hn-nodes and np-default deleted, np-default-allow-all added
    - Result: [PASS]
6. Move namespace w/ user network policies from default project to system project
    - Initial: hn-nodes, np-default, and user network policies
    - Expected: hn-nodes and np-default deleted, np-default-allow-all not added, user network policies retained
    - Result: [PASS]
7. Move namespace w/ no user network policies from system project to default project
    - Initial: np-default-allow-all
    - Expected: np-default-allow-all deleted, hn-nodes np-default added
    - Result: [PASS]
8. Move namespace w/ user network policies from system project to default project
    - Initial: user network policies
    - Expected: hn-nodes np-default added, user network policies retained
    - Result: [PASS]

### Namespace Deletion

All of these cases work because the network policies are namespace scoped and will get deleted with the namespace.

**Comment by sowmyav27** [comment] 2021-04-11 20:09
**On 2.5.8-rc1**

- Install the CIS Operator/Chart in a downstream cluster where PNI is enabled on the cluster
- Navigate to Cluster Applications > CIS Benchmark
- Create a new, one-time scan with profile: rke-profile-hardened-1.6
- Allow the scan to run and once completed, click into it to view the results
- 5.3.2 test has failed. 
- System project has no Networkpolicy defined even when the PNI is enabled on the cluster

```
> kubectl get networkpolicy -n cis-operator-system
NAME                POD-SELECTOR   AGE
default-allow-all   <none>         11m
hn-nodes            <none>         11m
np-default          <none>         11m
> kubectl get networkpolicy -n cattle-system
No resources found in cattle-system namespace.
```

**Comment by sowmyav27** [comment] 2021-04-12 00:04
Reopening for fixes in master-head.

**Comment by ryansann** [comment] 2021-04-12 17:05
Fix is merged to master

**Comment by sowmyav27** [comment] 2021-04-17 01:21
Tracking master-head validations in a separate ticket

**Closed by sowmyav27** 2021-04-17 01:21 UTC
Labels: QA/M, [zube]: To Test, area/cluster, internal, kind/bug, priority/2, release-note
