### ISSUE TITLE
Prometheus catalog: invalid character '\x00' in string literal

### ISSUE THREAD

**Issue by danielschlegel** [rancher/rancher#6490] opened 2016-11-02 13:13 UTC
If i try to create Prometheus from catalog i get the following error.

```invalid character '\x00' in string literal```

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v1.1.4` Cattle: `v0.165.8.4` UI: `v1.1.14` |
|Access|`github` `admin`|
|Orchestration|`Kubernetes`|
|Route|`catalog-tab.launch`|

**Comment by larsmagnusherland** [comment] 2016-11-02 14:09
Same as #6447

**Comment by tfiduccia** [comment] 2016-11-04 20:48
Duplicate of #6447.  Closing in favor of original bug.

**Closed by tfiduccia** 2016-11-04 20:48 UTC
