### ISSUE TITLE
Update daemon set will lost container environment

### ISSUE THREAD

**Issue by orangedeng** [rancher/rancher#12951] opened 2018-04-21 04:04 UTC
Reproduce steps
1. Create a rke cluster
2. move ingress-nginx namespace into default project
3. update nginx-ingress-controller workload and change command a little and pay attention to environment. There will be two env var `POD_NAME` and `POD_NAMESPACE`
4. after click update, view workload detail again and see what env vars are now.

Result:
only one env var left.

Expect:
env var should still the same.

**Comment by deniseschannon** [comment] 2018-04-25 04:05
@kinarashah  this sounds like https://github.com/rancher/rancher/issues/12842 issue?

**Comment by kinarashah** [comment] 2018-04-25 17:15
@deniseschannon thank you, yes this should be fixed in the latest version

**Comment by kinarashah** [comment] 2018-04-25 18:29
@sangeethah confirmed with @orangedeng just reproduced at the workload level. 
So if you do `kubectl get daemonset nginx-ingress-controller -n ingress-nginx` and see the update happening, this issue can be considered resolved .. 

Pods not getting upgraded looks like a separate issue

**Comment by sangeethah** [comment] 2018-04-27 03:26
Tested with v2.0.0-rc1

Create a rke cluster
move ingress-nginx namespace into default project
update nginx-ingress-controller workload and add a new environment variable .

After update call is done ,Both env var POD_NAME and POD_NAMESPACE continue to be present.

This issue is tracked in https://github.com/rancher/rancher/issues/13146

**Closed by sangeethah** 2018-04-27 03:26 UTC
Labels: kind/bug, status/to-test, version/2.0
