### ISSUE TITLE
Rancher CLI failure while authentication with Active Directory via kubectl/kubeconfig after upgrade to 2.6.9

### ISSUE THREAD

**Issue by MKlimuszka** [rancher/rancher#42569] opened 2023-08-29 15:59 UTC
**Rancher Cluster:**
Rancher version: v2.6.9
Number of nodes: 3
Node OS version: ubuntu 20.04

**Downstream Cluster:**
Number of Downstream clusters: 3
Node OS: ubuntu 20.04
RKE/RKE2/K3S version: RKE1
Kubernetes version: mix v1.20.11 and v1.21.14
CNI: canal{}

**Timeout issues when authenticating with Active Directory on the Rancher CLI v2.6.9.**

See original report SURE-5796 for more info.

**Comment by PennyScissors** [comment] 2023-08-29 17:50
Posting the PR template for QA here as this issue seems to be fixed in 2.7-head already, but we couldn't find a PR associated with the fix.

### Testing

1. Create a Rancher 2.7.7-rcX cluster
2. Enable ActiveDirectory auth in it
3. Create a downstream RKE2 cluster (Make sure to enable Authorized Endpoint under the Networking tab)
4. Execute CLI command `rancher --debug token --user=<AD-std-user> --cacerts=<AD-certs> --server=<rancher-server-url> --cluster=<cluster-ID> –-auth-provider=activeDirectoryProvider`

### Regressions Considerations

Trying this on providers other than AD, specially LDAP based, might be good

**Comment by ronhorton** [comment] 2023-09-12 20:30
**Pass** Verified in rancher `v2.7-head commit ID ce4222a`
Tested with AD, openLDAP
1. created rancher 2.7-head
2. enabled auth provider
3. created downstream rke2 cluster
4. executed rancher CLI command
5. command returned expected result

![2023-09-12_16-28-59](https://github.com/rancher/rancher/assets/89212856/ae4fa7db-0d11-472a-b5e8-dfebe2fd7fb3)

**Closed** 2023-09-12 20:33 UTC
Labels: internal, area/authentication, [zube]: Done, team/area3
