### ISSUE TITLE
Can't use LDAP auth when LDAP Server has objectClass attribute in lowercase

### ISSUE THREAD

**Issue by igorcezar** [rancher/rancher#28077] opened 2020-07-25 00:21 UTC
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
1. Enable OpenLDAP Auth
2. Configure to a LDAP Server which the objectClass name is lowercase (objectclass), like below:
```
objectclass: top
objectclass: person
objectclass: inetOrgPerson
uid: f435
givenname: User
```
**Result:**
It doesn't find the inetOrgPerson objectClass and doesn't bind the user correctly.
![image](https://user-images.githubusercontent.com/10411165/88442869-7826b500-cdec-11ea-96c3-89caa1978b9b.png)

It enables OpenLDAP Auth, but it can't find any user or group, so I can't add members in any cluster.
![image](https://user-images.githubusercontent.com/10411165/88443001-f7b48400-cdec-11ea-980a-7081ff380e42.png)

**Other details that may be helpful:**
After some troubleshoot, the problem seems to be in the function [isType() in ldap_util.go](https://github.com/rancher/rancher/blob/c642f1caa0ba4be2a27ebec1e1a0a6f3e6a482d5/pkg/auth/providers/common/ldap/ldap_util.go#L99), that searches for the specific attribute name "objectClass", so in this case will never find it because the name is objectclass (lowercase).

```
func IsType(search []*ldapv2.EntryAttribute, varType string) bool {
	for _, attrib := range search {
		if attrib.Name == "objectClass" {       <===================== here
			for _, val := range attrib.Values {
				if strings.EqualFold(val, varType) {
					logrus.Debugf("ldap IsType found object of type %s", varType)
					return true
				}
			}
		}
	}
	logrus.Debugf("ldap IsType failed to determine if object is type: %s", varType)
	return false
}
```
The change I made to solve this was to use the function **strings.EqualFold** to make it case insensitive:

```
func IsType(search []*ldapv2.EntryAttribute, varType string) bool {
	for _, attrib := range search {
		if strings.EqualFold(attrib.Name, "objectClass") {
			for _, val := range attrib.Values {
				if strings.EqualFold(val, varType) {
					logrus.Debugf("ldap IsType found object of type %s", varType)
					return true
				}
			}
		}
	}
	logrus.Debugf("ldap IsType failed to determine if object is type: %s", varType)
	return false
}
```
Also changed this [isType implementation](https://github.com/rancher/rancher/blob/v2.4.5/pkg/auth/providers/ldap/ldap_client.go#L124) to use the new ldap.isType() function changed above so it can also be case insensitive.

After this changes are made, OpenLDAP auth works fine.

![image](https://user-images.githubusercontent.com/10411165/88443918-cd64c580-cdf0-11ea-9f79-cc3840ebe7c6.png)

I have opened 3 PRs for this case:
rancher/rancher#26778 
rancher/rancher#26952
rancher/rancher#26949

The same problem occurs if using others providers for LDAP, like FreeIPA, because the function **isType()** is common to them.

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): Verified on versions 2.2.8, 2.3.5 and 2.4.5.
- Installation option (single install/HA): Both single and HA

**Comment by superseb** [comment] 2020-08-03 19:59
What LDAP server are you working with?

**Comment by igorcezar** [comment] 2020-08-03 23:08
It's a IBM LDAP Server for z/OS Mainframe.

**Comment by dramich** [comment] 2020-10-13 00:01
https://github.com/rancher/rancher/pull/26949

**Comment by dramich** [comment] 2020-10-13 02:00
This has been fixed in 2.4, 2.5 and master lines.

**Comment by dramich** [comment] 2020-10-13 02:01
Thanks @igorcezar for all the pull requests 😃

**Comment by igorcezar** [comment] 2020-10-13 02:18
It was my pleasure to contribute! Thanks for accept it! 😄 
Will this fix be in version 2.4.9?

**Comment by dramich** [comment] 2020-10-13 15:47
@igorcezar No guarantees but it should be

**Comment by mrajashree** [comment] 2020-10-13 20:42
I think we should test the fix with all ldap providers, that is Openldap, AD and Freeipa, since the `IsType` method is common to all

**Comment by izaac** [comment] 2020-10-13 23:43
Regression Tests done of P1 scenarios in the following combinations:

### OpenLDAP (Manual P1)
Rancher version `v2.4-head (10/13/2020)` _928e9ce7e_
Rancher version `v2.5-head (10/13/2020)` _ffbdcb9_
Rancher version `master-head (10/13/2020)` _0dee1debc_


### OpenLDAP (Automation)
Rancher version `v2.4-head (10/13/2020)` _928e9ce7e_
Rancher version `v2.5-head (10/13/2020)` _ffbdcb9_
Rancher version `master-head (10/13/2020)` _0dee1debc_



### ActiveDirectory (Automation)
Rancher version `v2.4-head (10/13/2020)` _928e9ce7e_
Rancher version `v2.5-head (10/13/2020)` _ffbdcb9_
Rancher version `master-head (10/13/2020)` _0dee1debc_


### FreeIPA (Manual P1)
Rancher version `v2.4-head (10/13/2020)` _928e9ce7e_
Rancher version `v2.5-head (10/13/2020)` _ffbdcb9_
Rancher version `master-head (10/13/2020)` _0dee1debc_
```

**Comment by bmdepesa** [comment] 2020-10-13 23:44
@igorcezar Can you confirm that v2.4-head image resolves the problem with your LDAP server?

**Comment by izaac** [comment] 2020-10-13 23:45
@mrajashree do you know of an LDAP server other than the IBM Security Directory Server that uses the `objectClass` with all lowercase `objectclass` or know how to configure openLDAP this way?

**Comment by igorcezar** [comment] 2020-10-14 03:43
@bmdepesa It's working in v2.4-head and v2.5-head, for both OpenLdap and FreeIPA. 😄

**Closed** 2020-10-14 03:46 UTC
Labels: [zube]: To Test, kind/enhancement
