### ISSUE TITLE
Multiline values in answers.txt do not work

### ISSUE THREAD

**Issue by ekristen** [rancher/rancher#9759] opened 2017-08-25 21:24 UTC
**Rancher versions:**
rancher/server: 1.5.10
rancher/agent: 1.2.2

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle

**Steps to Reproduce:**
The UI exports answers.txt multiline value like this

```
some_answer='this is a 
multiline value
with more lines'
```

When you install a catalog entry with the answers.txt only `'this is a` gets populated into the field.

It should populate the whole value stripping the quotes, but it does not.

**Comment by cjellick** [comment] 2017-08-25 22:18
@ekristen I'm going to close as a dupe of https://github.com/rancher/rancher/issues/9305, which will be out in our next release.

Note that we chose to fix by supporting yaml and json formats. And instead of implementing some non-standard way of doing multi-line in a txt file, if you want multi-line, you'll have to use yaml and json and use their standard approaches for multiline.
Hopefully that's not too big of a burden

**Closed by cjellick** 2017-08-25 22:18 UTC

**Comment by ekristen** [comment] 2017-08-26 01:09
Happy to hear, love to use yaml! Thanks
