### ISSUE TITLE
Please provide some ways to bulk filter or delete instances in "HOSTS" and "CONTAINERS" page.

### ISSUE THREAD

**Issue by kenhuang** [rancher/rancher#1505] opened 2015-07-13 08:57 UTC
We use one of our linux machine to build our own docker images, during this process, it create so many stopped instances...

<img width="311" alt="screen shot 2015-07-13 at 8 53 11 pm" src="https://cloud.githubusercontent.com/assets/205194/8646126/44b886de-29a1-11e5-83bd-7365237d4c68.png">

Please provide some ways to bulk filter or delete instances in "HOSTS" and "CONTAINERS" page. 

We love rancher, keep up the good works!

**Comment by ibuildthecloud** [comment] 2015-07-13 15:05
+1 this feature would be so helpful.

**Comment by vincent99** [comment] 2015-07-22 08:36
Dupe of #342.  Some of the work needed for this was done with making all the table views sortable, just need to finish it.

**Closed by vincent99** 2015-07-22 08:36 UTC
Labels: area/ui, kind/enhancement
