### ISSUE TITLE
[BUG] `SystemUpgradeControllerReady` condition on clusters.provisioning.cattle.io object is unnecessarily updated in certain cases, causing thrashing

### ISSUE THREAD

**Issue by Oats87** [rancher/rancher#41085] opened 2023-04-06 16:20 UTC
**Rancher Server Setup**
- Rancher version: v2.7-head

**Describe the bug**
While testing https://github.com/rancher/rancher/issues/41080 and attempting to invent a workaround for it, I noticed that the `SystemUpgradeControllerReady` condition on the `rkecontrolplanes.rke.cattle.io` object was continuously being updated, where the only change was the timestamp of the condition. This is not ideal and we should correct this. 

**To Reproduce**
Provision a v2prov cluster, and shutdown all of your downstream nodes

**Result**
Observe that the `rkecontrolplanes.rke.cattle.io` object is constantly updated with the condition for `SystemUpgradeControllerReady`

**Expected Result**
The condition should be updated once

**Screenshots**

**Additional context**

cc: @HarrisonWAffel

**Comment by snasovich** [comment] 2023-04-19 22:19
Closing as duplicate of https://github.com/rancher/rancher/issues/41085

**Closed by snasovich** 2023-04-19 22:19 UTC
Labels: kind/bug, area/provisioning-v2, team/area2, team/area2/sc
