### ISSUE TITLE
In rc builds , ui-index and ui-dashboard-index does not stick to a UI tag.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#29307] opened 2020-10-01 17:12 UTC
ui-index and ui-dashboard-index in RC builds is the same as from master-head - “https://releases.rancher.com/dashboard/latest/index.html” and “”https://releases.rancher.com/ui/latest2/index.html”

"/v3/settings/ui-offline-preferred" is set to "dynamic"

Need confirmation if the default settings seen are expected ones for a release candidate.

I do see that the latest UI changes are not picked by RC builds , even though the values for the /v3/settings/ui-offline-preferred , ember and dashboard indexes are the same for master-head and rc builds.

`<script src="/assets/vendor-037553771a009d1b95e42f5907fcb0d5.js"></script>`  ->In RC

**Comment by sangeethah** [comment] 2020-10-01 17:57
<img width="860" alt="Screen Shot 2020-10-01 at 10 54 16 AM" src="https://user-images.githubusercontent.com/4266958/94845439-8983d300-03d4-11eb-8773-09680d484058.png">

**Comment by cbron** [comment] 2020-10-02 15:54
@sangeethah can you create a dashboard issue for the screenshot. Since we don't actually appear to be experiencing any issues here, I'm not sure what to do with this issue. I will release note the UI changes, otherwise we should be ok ?

**Comment by sangeethah** [comment] 2020-10-02 21:21
Logged this for tracking proper "User Interface" version  - https://github.com/rancher/dashboard/issues/1593

**Comment by cbron** [comment] 2020-10-02 22:18
Reopening because I believe the `UIOfflinePreferred` flag is broken, need to fix that part still, but in next milestone.

**Comment by cbron** [comment] 2020-10-12 20:34
Closing as dupe of https://github.com/rancher/rancher/issues/29362
That one is more appropriate.

**Closed by cbron** 2020-10-12 20:34 UTC
Labels: [zube]: Next Up
