### ISSUE TITLE
Assigned group roles not shown in the ui

### ISSUE THREAD

**Issue by julbrygd** [rancher/rancher#21077] opened 2019-06-24 06:48 UTC
In the cluster edit and project edit view, all roles assigned to groups (from the Active Directory) were not shown in the gui.

If i look in the API the roles were assigend to the groups.

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v2.2.4` UI: `v2.2.70` |
|Route|`authenticated.cluster.edit`|

**Comment by davidnuzik** [comment] 2019-06-24 17:08
Duplicate of https://github.com/rancher/rancher/issues/20760
Upcoming v2.2.5 release will have a fix see https://github.com/rancher/rancher/issues/20825

**Closed by davidnuzik** 2019-06-24 17:08 UTC
