### ISSUE TITLE
[2.9] Stale secrets for impersonation user in downstream cluster

### ISSUE THREAD

**Issue by samjustus** [rancher/rancher#46894] opened 2024-08-30 14:19 UTC
backport #46537

**Comment by Priyashetty17** [comment] 2024-09-11 16:53
Recreated the issue on **2.9.1.**

```
> kubectl get secrets -n cattle-impersonation-system   | grep -i u-xbhcp
cattle-impersonation-u-xbhcp-token-4clzr        kubernetes.io/service-account-token   3      2m6s
cattle-impersonation-u-xbhcp-token-bvkpq        kubernetes.io/service-account-token   3      2m31s
cattle-impersonation-u-xbhcp-token-h8zlj        kubernetes.io/service-account-token   3      2m32s
cattle-impersonation-u-xbhcp-token-lc6hj        kubernetes.io/service-account-token   3      2m27s
cattle-impersonation-u-xbhcp-token-ths8h        kubernetes.io/service-account-token   3      2m43s
> 
```

**Rancher Log:** 
```
2024/09/11 15:30:31 [INFO] EnsureSecretForServiceAccount: waiting for secret [cattle-impersonation-u-xbhcp-token-ths8h] to be populated with token
2024/09/11 15:30:51 [INFO] EnsureSecretForServiceAccount: waiting for secret [cattle-impersonation-u-xbhcp-token-lc6hj] to be populated with token
2024/09/11 15:30:52 [INFO] EnsureSecretForServiceAccount: waiting for secret [cattle-impersonation-u-xbhcp-token-h8zlj] to be populated with token
2024/09/11 15:30:53 [INFO] EnsureSecretForServiceAccount: waiting for secret [cattle-impersonation-u-xbhcp-token-bvkpq] to be populated with token

```

**Comment by Priyashetty17** [comment] 2024-09-12 01:09
I still see stale secrets for a few users with` v2.9-aa0df7efb88fef50c08451971c78f81bc002e9c3-head`. The validation template [here](https://github.com/rancher/rancher/issues/44347#issuecomment-2059375869) says "A mutex was added to the secret creation process, which prevents concurrent creation of secrets and leads to fewer "stale" secrets" --> Does this mean stale secrets can still happen but are less frequent compared to previous versions? If fewer is expected, what qualifies as "fewer"? It’s hard to say if we’re seeing fewer compared to 2.9.1 since the numbers look similar in both the releases.

**2.9-head**: 

```
> kubectl get secrets -n cattle-impersonation-system | grep -i u-5tgmj
cattle-impersonation-u-5tgmj-token-7hnvp       kubernetes.io/service-account-token  3     2m50s
cattle-impersonation-u-5tgmj-token-qvkq9       kubernetes.io/service-account-token  3     3m2s
 
> kubectl get secrets -n cattle-impersonation-system | grep -i u-d45md
cattle-impersonation-u-d45md-token-k8zh4       kubernetes.io/service-account-token  3     2m57s
cattle-impersonation-u-d45md-token-x929k       kubernetes.io/service-account-token  3     2m3s
 
> kubectl get secrets -n cattle-impersonation-system | grep -i u-d5ch7
cattle-impersonation-u-d5ch7-token-2j4qm       kubernetes.io/service-account-token  3     88s
cattle-impersonation-u-d5ch7-token-6hl52       kubernetes.io/service-account-token  3     84s
cattle-impersonation-u-d5ch7-token-csc5n       kubernetes.io/service-account-token  3     84s
cattle-impersonation-u-d5ch7-token-fbslk       kubernetes.io/service-account-token  3     88s
cattle-impersonation-u-d5ch7-token-g8jlv       kubernetes.io/service-account-token  3     84s
 
> kubectl get secrets -n cattle-impersonation-system | grep -i u-jdqxf
cattle-impersonation-u-jdqxf-token-cltst       kubernetes.io/service-account-token  3     2m19s
cattle-impersonation-u-jdqxf-token-d6l8c       kubernetes.io/service-account-token  3     2m20s
cattle-impersonation-u-jdqxf-token-f4zqg       kubernetes.io/service-account-token  3     3m16s
cattle-impersonation-u-jdqxf-token-nmz48       kubernetes.io/service-account-token  3     2m19s
 
> kubectl get secrets -n cattle-impersonation-system | grep -i u-vkwh4
cattle-impersonation-u-vkwh4-token-6cpcg       kubernetes.io/service-account-token  3     3m12s
cattle-impersonation-u-vkwh4-token-j64cj       kubernetes.io/service-account-token  3     2m26s
>
```

**Test Steps:**

1. Create a downstream cluster
2. Create 100 Users
3. Assign users as Cluster Owner to downstream cluster
4. For each created user, perform a login and in a loop, perform one of the random operations on the downstream cluster:
- Create a Deployment.
- List all namespaces in the cluster.
- Retrieve all pods from the default namespace.
5. Check for Stale Secrets for each user.

**Comment by Priyashetty17** [comment] 2024-09-13 01:20
Following Michael's suggestion: _"As far as testing this goes, I would recommend scaling down the rancher pod to a single replica - in theory this should produce no stale secrets when Rancher only has a single replica, since the mutex should fix the stale secrets caused by multiple threads in one replica."_, 
I reran the test on `v2.9-d1402ce585dfee99015d0129ad6ddcc598ce8e99-head` after scaling down the Rancher pod to a single replica. However, I am still observing stale secrets for some users.

```
> kubectl get secrets -n cattle-impersonation-system | grep u-54xnm
cattle-impersonation-u-54xnm-token-8s727        kubernetes.io/service-account-token   3      3m19s
cattle-impersonation-u-54xnm-token-sgbv4        kubernetes.io/service-account-token   3      3m22s

	2024/09/13 00:41:05 [INFO] EnsureSecretForServiceAccount: waiting for secret [cattle-impersonation-system:cattle-impersonation-u-54xnm-token-sgbv4] for service account [cattle-impersonation-system:cattle-impersonation-u-54xnm] to be populated with token
	2024/09/13 00:41:11 [INFO] EnsureSecretForServiceAccount: got the service account token for service account [cattle-impersonation-system:cattle-impersonation-u-54xnm] in 6.637913186s c-m-r8cw2wzd- 
	2024/09/13 00:41:18 [INFO] EnsureSecretForServiceAccount: waiting for secret [cattle-impersonation-system:cattle-impersonation-u-54xnm-token-8s727] for service account [cattle-impersonation-system:cattle-impersonation-u-54xnm] to be populated with token
	2024/09/13 00:41:30 [INFO] EnsureSecretForServiceAccount: got the service account token for service account [cattle-impersonation-system:cattle-impersonation-u-54xnm] in 12.233648335s c-m-r8cw2wzd- 

> kubectl get secrets -n cattle-impersonation-system | grep u-k5wfz
cattle-impersonation-u-k5wfz-token-2r9nw        kubernetes.io/service-account-token   3      3m30s
cattle-impersonation-u-k5wfz-token-ccvw4        kubernetes.io/service-account-token   3      3m33s

	2024/09/13 00:41:05 [INFO] EnsureSecretForServiceAccount: waiting for secret [cattle-impersonation-system:cattle-impersonation-u-k5wfz-token-ccvw4] for service account [cattle-impersonation-system:cattle-impersonation-u-k5wfz] to be populated with token
	2024/09/13 00:41:11 [INFO] EnsureSecretForServiceAccount: got the service account token for service account [cattle-impersonation-system:cattle-impersonation-u-k5wfz] in 6.633950626s c-m-r8cw2wzd- 
	2024/09/13 00:41:18 [INFO] EnsureSecretForServiceAccount: waiting for secret [cattle-impersonation-system:cattle-impersonation-u-k5wfz-token-2r9nw] for service account [cattle-impersonation-system:cattle-impersonation-u-k5wfz] to be populated with token
	2024/09/13 00:41:30 [INFO] EnsureSecretForServiceAccount: got the service account token for service account [cattle-impersonation-system:cattle-impersonation-u-k5wfz] in 12.235882689s c-m-r8cw2wzd- 

> kubectl get secrets -n cattle-impersonation-system | grep u-s9gvr
cattle-impersonation-u-s9gvr-token-25l5f        kubernetes.io/service-account-token   3      3m43s
cattle-impersonation-u-s9gvr-token-jgdsn        kubernetes.io/service-account-token   3      3m42s

	2024/09/13 00:41:04 [INFO] EnsureSecretForServiceAccount: waiting for secret [cattle-impersonation-system:cattle-impersonation-u-s9gvr-token-25l5f] for service account [cattle-impersonation-system:cattle-impersonation-u-s9gvr] to be populated with token
	2024/09/13 00:41:05 [INFO] EnsureSecretForServiceAccount: got the service account token for service account [cattle-impersonation-system:cattle-impersonation-u-s9gvr] in 681.300604ms c-m-r8cw2wzd- 
	2024/09/13 00:41:05 [INFO] EnsureSecretForServiceAccount: waiting for secret [cattle-impersonation-system:cattle-impersonation-u-s9gvr-token-jgdsn] for service account [cattle-impersonation-system:cattle-impersonation-u-s9gvr] to be populated with token
	2024/09/13 00:41:11 [INFO] EnsureSecretForServiceAccount: got the service account token for service account [cattle-impersonation-system:cattle-impersonation-u-s9gvr] in 6.626745359s c-m-r8cw2wzd- 
```
	
I also noticed the following **panic** in the Rancher log:
```
2024/09/13 00:20:13 [ERROR] Panic serving api request: 
Thu, Sep 12 2024 8:20:13 pmgoroutine 68291 [running]:
Thu, Sep 12 2024 8:20:13 pmruntime/debug.Stack()
Thu, Sep 12 2024 8:20:13 pm /usr/lib64/go/1.22/src/runtime/debug/stack.go:24 +0x5e
Thu, Sep 12 2024 8:20:13 pmgithub.com/rancher/norman/api.(*Server).ServeHTTP.func1()
Thu, Sep 12 2024 8:20:13 pm /go/pkg/mod/github.com/rancher/norman@v0.0.0-20240708202514-a0127673d1b9/api/server.go:175 +0x6d
Thu, Sep 12 2024 8:20:13 pmpanic({0x6c11960?, 0xd4c1420?})
Thu, Sep 12 2024 8:20:13 pm /usr/lib64/go/1.22/src/runtime/panic.go:770 +0x132
Thu, Sep 12 2024 8:20:13 pmgithub.com/rancher/rancher/pkg/auth/providers/publicapi.(*loginHandler).createLoginToken(_, _)
Thu, Sep 12 2024 8:20:13 pm /app/pkg/auth/providers/publicapi/login.go:247 +0x103a
Thu, Sep 12 2024 8:20:13 pmgithub.com/rancher/rancher/pkg/auth/providers/publicapi.(*loginHandler).login(0xc00151f6b0?, {0xc01a7eac6c?, 0x4?}, 0xc001219c20?, 0xc01a7f7560)
Thu, Sep 12 2024 8:20:13 pm /app/pkg/auth/providers/publicapi/login.go:70 +0x125
Thu, Sep 12 2024 8:20:13 pmgithub.com/rancher/norman/api.handleAction(0xc017ce10e0?, 0xc01a7f7560?)
Thu, Sep 12 2024 8:20:13 pm /go/pkg/mod/github.com/rancher/norman@v0.0.0-20240708202514-a0127673d1b9/api/server.go:263 +0x77
Thu, Sep 12 2024 8:20:13 pmgithub.com/rancher/norman/api.(*Server).handle(0xc000aa3b80, {0x90d69b0?, 0xc011a33880?}, 0x9066560?)
Thu, Sep 12 2024 8:20:13 pm /go/pkg/mod/github.com/rancher/norman@v0.0.0-20240708202514-a0127673d1b9/api/server.go:251 +0x332
Thu, Sep 12 2024 8:20:13 pmgithub.com/rancher/norman/api.(*Server).ServeHTTP(0xc000aa3b80, {0x90d69b0?, 0xc011a33880?}, 0x120?)
Thu, Sep 12 2024 8:20:13 pm /go/pkg/mod/github.com/rancher/norman@v0.0.0-20240708202514-a0127673d1b9/api/server.go:180 +0x66
Thu, Sep 12 2024 8:20:13 pmgithub.com/gorilla/mux.(*Router).ServeHTTP(0xc0008e32c0, {0x90d69b0, 0xc011a33880}, 0xc01a7f7200)
Thu, Sep 12 2024 8:20:13 pm /go/pkg/mod/github.com/gorilla/mux@v1.8.1/mux.go:212 +0x1e2
Thu, Sep 12 2024 8:20:13 pmgithub.com/rancher/rancher/pkg/multiclustermanager.(*DeferredServer).Middleware.func1({0x90d69b0, 0xc011a33880}, 0xc01a7f7200)
Thu, Sep 12 2024 8:20:13 pm /app/pkg/multiclustermanager/deferred.go:113 +0x73
Thu, Sep 12 2024 8:20:13 pmnet/http.HandlerFunc.ServeHTTP(0xc01a7f70e0?, {0x90d69b0?, 0xc011a33880?}, 0x411ebb?)
Thu, Sep 12 2024 8:20:13 pm /usr/lib64/go/1.22/src/net/http/server.go:2171 +0x29
Thu, Sep 12 2024 8:20:13 pmgithub.com/gorilla/mux.(*Router).ServeHTTP(0xc00147a9c0, {0x90d69b0, 0xc011a33880}, 0xc01a7f6fc0)
Thu, Sep 12 2024 8:20:13 pm /go/pkg/mod/github.com/gorilla/mux@v1.8.1/mux.go:212 +0x1e2
Thu, Sep 12 2024 8:20:13 pmgithub.com/gorilla/mux.(*Router).ServeHTTP(0xc008bd0a80, {0x90d69b0, 0xc011a33880}, 0xc01a7f6d80)
Thu, Sep 12 2024 8:20:13 pm /go/pkg/mod/github.com/gorilla/mux@v1.8.1/mux.go:212 +0x1e2
Thu, Sep 12 2024 8:20:13 pmgithub.com/rancher/rancher/pkg/api/steve/aggregation.(*aggregationHandler).Middleware-fm.(*aggregationHandler).Middleware.func1({0x90d69b0, 0xc011a33880}, 0xc01a7f6d80)
Thu, Sep 12 2024 8:20:13 pm /app/pkg/api/steve/aggregation/aggregation.go:52 +0x4f
Thu, Sep 12 2024 8:20:13 pmnet/http.HandlerFunc.ServeHTTP(0xc01a7f6c60?, {0x90d69b0?, 0xc011a33880?}, 0xc01a7d3da0?)
Thu, Sep 12 2024 8:20:13 pm /usr/lib64/go/1.22/src/net/http/server.go:2171 +0x29
Thu, Sep 12 2024 8:20:13 pmgithub.com/gorilla/mux.(*Router).ServeHTTP(0xc00147a840, {0x90d69b0, 0xc011a33880}, 0xc01a7f6b40)
Thu, Sep 12 2024 8:20:13 pm /go/pkg/mod/github.com/gorilla/mux@v1.8.1/mux.go:212 +0x1e2
Thu, Sep 12 2024 8:20:13 pmgithub.com/rancher/rancher/pkg/api/steve/proxy.NewProxyMiddleware.func1.1({0x90d69b0?, 0xc011a33880?}, 0x8?)
Thu, Sep 12 2024 8:20:13 pm /app/pkg/api/steve/proxy/proxy.go:80 +0x55
Thu, Sep 12 2024 8:20:13 pmnet/http.HandlerFunc.ServeHTTP(0x7f3bba90e548?, {0x90d69b0?, 0xc011a33880?}, 0x7e25460?)
Thu, Sep 12 2024 8:20:13 pm /usr/lib64/go/1.22/src/net/http/server.go:2171 +0x29
Thu, Sep 12 2024 8:20:13 pmgithub.com/rancher/rancher/pkg/api/steve/proxy.RewriteLocalCluster.func1({0x90d69b0, 0xc011a33880}, 0xc01a7f6b40)
Thu, Sep 12 2024 8:20:13 pm /app/pkg/api/steve/proxy/proxy.go:46 +0x16b
Thu, Sep 12 2024 8:20:13 pmnet/http.HandlerFunc.ServeHTTP(0xc00bbbb628?, {0x90d69b0?, 0xc011a33880?}, 0x812f4e4?)
Thu, Sep 12 2024 8:20:13 pm /usr/lib64/go/1.22/src/net/http/server.go:2171 +0x29
Thu, Sep 12 2024 8:20:13 pmgithub.com/rancher/rancher/pkg/websocket.websocketHandler.ServeHTTP({{0x9080dc0?, 0xc002adca20?}}, {0x90d69b0, 0xc011a33880}, 0xc01a7f6b40)
Thu, Sep 12 2024 8:20:13 pm /app/pkg/websocket/handler.go:35 +0xa3
Thu, Sep 12 2024 8:20:13 pmgithub.com/rancher/apiserver/pkg/middleware.NoCache.func1({0x90d69b0, 0xc011a33880}, 0xc01a7f6b40)
Thu, Sep 12 2024 8:20:13 pm /go/pkg/mod/github.com/rancher/apiserver@v0.0.0-20240708202538-39a6f2535146/pkg/middleware/cache.go:33 +0xf0
Thu, Sep 12 2024 8:20:13 pmnet/http.HandlerFunc.ServeHTTP(0x790ea80?, {0x90d69b0?, 0xc011a33880?}, 0x16?)
Thu, Sep 12 2024 8:20:13 pm /usr/lib64/go/1.22/src/net/http/server.go:2171 +0x29
Thu, Sep 12 2024 8:20:13 pmgithub.com/rancher/apiserver/pkg/middleware.ContentTypeOptions.func1({0x90d69b0, 0xc011a33880}, 0xc01a7f6b40)
Thu, Sep 12 2024 8:20:13 pm /go/pkg/mod/github.com/rancher/apiserver@v0.0.0-20240708202538-39a6f2535146/pkg/middleware/cache.go:47 +0xf6
Thu, Sep 12 2024 8:20:13 pmnet/http.HandlerFunc.ServeHTTP(0x790ea80?, {0x90d69b0?, 0xc011a33880?}, 0x11?)
Thu, Sep 12 2024 8:20:13 pm /usr/lib64/go/1.22/src/net/http/server.go:2171 +0x29
Thu, Sep 12 2024 8:20:13 pmgithub.com/rancher/rancher/pkg/auth.SetXAPICattleAuthHeader.func1({0x90d69b0, 0xc011a33880}, 0xc01a7f6b40)
Thu, Sep 12 2024 8:20:13 pm /app/pkg/auth/server.go:180 +0x173
Thu, Sep 12 2024 8:20:13 pmnet/http.HandlerFunc.ServeHTTP(0xc01de68720?, {0x90d69b0?, 0xc011a33880?}, 0x120?)
Thu, Sep 12 2024 8:20:13 pm /usr/lib64/go/1.22/src/net/http/server.go:2171 +0x29
Thu, Sep 12 2024 8:20:13 pmgithub.com/rancher/rancher/pkg/auth/audit.auditHandler.ServeHTTP({{0x9080dc0, 0xc002adca68}, 0x0, 0xc002b2fb80, 0xc003432090, 0xc0061f7990}, {0x90d69b0?, 0xc011a33880?}, 0x2278f01?)
Thu, Sep 12 2024 8:20:13 pm /app/pkg/auth/audit/filter.go:67 +0x525
Thu, Sep 12 2024 8:20:13 pmgithub.com/rancher/rancher/pkg/auth.NewServer.ToAuthMiddleware.ToMiddleware.func2.1({0x90d69b0, 0xc011a33880}, 0xc01a7f6a20)
Thu, Sep 12 2024 8:20:13 pm /go/pkg/mod/github.com/rancher/steve@v0.0.0-20240911190153-79304d93b49b/pkg/auth/filter.go:172 +0x24f
Thu, Sep 12 2024 8:20:13 pmnet/http.HandlerFunc.ServeHTTP(0xc00aee6a98?, {0x90d69b0?, 0xc011a33880?}, 0xc01de685d0?)
Thu, Sep 12 2024 8:20:13 pm /usr/lib64/go/1.22/src/net/http/server.go:2171 +0x29
Thu, Sep 12 2024 8:20:13 pmgithub.com/rancher/dynamiclistener/server.getTLSListener.wrapHandler.func1({0x90d69b0, 0xc011a33880}, 0xc01a7f6a20)
Thu, Sep 12 2024 8:20:13 pm /go/pkg/mod/github.com/rancher/dynamiclistener@v0.6.0/server/server.go:199 +0x68
Thu, Sep 12 2024 8:20:13 pmnet/http.HandlerFunc.ServeHTTP(0xc00aee6b58?, {0x90d69b0?, 0xc011a33880?}, 0xc01de685d0?)
Thu, Sep 12 2024 8:20:13 pm /usr/lib64/go/1.22/src/net/http/server.go:2171 +0x29
Thu, Sep 12 2024 8:20:13 pmgithub.com/rancher/dynamiclistener/server.ListenAndServe.HTTPRedirect.func7({0x90d69b0, 0xc011a33880}, 0xc01a7f6a20)
Thu, Sep 12 2024 8:20:13 pm /go/pkg/mod/github.com/rancher/dynamiclistener@v0.6.0/redirect.go:20 +0x1bc
Thu, Sep 12 2024 8:20:13 pmnet/http.HandlerFunc.ServeHTTP(0x412265?, {0x90d69b0?, 0xc011a33880?}, 0xc011a33801?)
Thu, Sep 12 2024 8:20:13 pm /usr/lib64/go/1.22/src/net/http/server.go:2171 +0x29
Thu, Sep 12 2024 8:20:13 pmnet/http.serverHandler.ServeHTTP({0x9094880?}, {0x90d69b0?, 0xc011a33880?}, 0x6?)
Thu, Sep 12 2024 8:20:13 pm /usr/lib64/go/1.22/src/net/http/server.go:3142 +0x8e
Thu, Sep 12 2024 8:20:13 pmnet/http.(*conn).serve(0xc018c0dd40, {0x90efeb0, 0xc002f95800})
Thu, Sep 12 2024 8:20:13 pm /usr/lib64/go/1.22/src/net/http/server.go:2044 +0x5e8
Thu, Sep 12 2024 8:20:13 pmcreated by net/http.(*Server).Serve in goroutine 5573
Thu, Sep 12 2024 8:20:13 pm /usr/lib64/go/1.22/src/net/http/server.go:3290 +0x4b4
```

**Comment by Priyashetty17** [comment] 2024-09-18 15:30
The fix doesn't completely eliminate duplicates. Closing this issue in favor of  https://github.com/rancher/rancher/issues/47126 where cleanup of secrets is implemented.

**Closed by Priyashetty17** 2024-09-18 15:30 UTC
Labels: kind/bug, priority/0, area/rbac, QA/M, release-note, status/release-note-added, team/collie
