### ISSUE TITLE
Convoy / Rancher NFS plugin

### ISSUE THREAD

**Issue by pwFoo** [rancher/rancher#8088] opened 2017-03-07 22:26 UTC
There is no convoy plugin in integrated to rancher server / catalog? Is it replaced or integrated by another plugin? Is Rancher NFS a replacement? What is planned?

**Comment by oskapt** [comment] 2017-03-08 05:59
Hi, @pwFoo - rancher-nfs is the updated version of convoy-nfs. It will work for all of your NFS needs. 

Do you have any specific questions about its use?

**Comment by pwFoo** [comment] 2017-03-08 07:11
Some documentation like convoy github page / readme would be nice. Convoy was useable without nfs too. That was nice for simple local tests.
At the moment I'm searching for the best volume solution with (automated) backups, restore and optional snapshot features.

For databases I'll test rancher-backup from catalog. So I need a backup solution for volumes too. During search I found convoy but not rancher-nfs ;)

**Comment by aemneina** [comment] 2017-05-12 16:30
Dupe of https://github.com/rancher/rancher/issues/6859 
rancher-nfs docs that should include migration path from convoy-nfs

**Closed by aemneina** 2017-05-12 16:30 UTC
Labels: area/documentation, area/storage
