### ISSUE TITLE
Database tables don't get cleaned up

### ISSUE THREAD

**Issue by mcanevet** [rancher/rancher#10841] opened 2018-01-12 14:21 UTC
**Rancher versions:**
rancher/server: v1.6.12
rancher/agent: v1.2.7

**Infrastructure Stack versions:**
healthcheck: v0.3.3
ipsec: v0.2.1
network-services: v0.2.7
scheduler: v0.6.3

**Docker version: (`docker version`,`docker info` preferred)**
v1.12.6

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
Ubuntu 16.04

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
OpenStack

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
single node rancher with external DB

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle

**Steps to Reproduce:**

**Results:**
Our MySQL database is currently taking 23GB and it keeps growing.
It looks like the biggest table is `instance` which takes over 20GB for 1.6M records. Second most big table is `image` with 1GB for 1.5M records.
I already launched the rancher/cleanup-1-1:v0.1.2 image.
Is it normal?

**Comment by junkiebev** [comment] 2018-01-17 23:17
I'm not sure if this is helpful, but I had database that kept increasing in size like that and the culprit was the weaveworks community catalog entry - it was creating and destroying the probe containers over and over again. Are you using that?

**Comment by junkiebev** [comment] 2018-01-25 13:59
This is happening to me now as well and the scheduler service keeps flapping. I have pretty much the same setup except I am on

Rancher	v1.6.14
Cattle	v0.183.37
User Interface	v1.6.37
Rancher CLI	v0.6.7
Rancher Compose	v0.12.5

My infrastructure stacks are all up to date

I'm seeing stuff like this in my server image docker logs:

018-01-25 13:58:21,904 ERROR [3c63e4e6-e018-4ed8-9aeb-9095427d0f35:18268792] [instance:452543] [instance.start->(InstanceStart)->instance.allocate->(InstanceAllocate)] [] [cutorService-11] [i.c.p.a.s.impl.AllocatorServiceImpl ] External scheduler replied with an error: Agent [55220] is removed
2018-01-25 13:58:50,653 ERROR [e5052473-3caf-4a9a-85bf-6f43a0ca1ccc:18270160] [agent:55213] [agent.deactivate->(MetadataProcessHandler)] [] [cutorService-11] [i.c.p.p.m.MetadataProcessHandler    ] Failed to find account id for agent:55213
2018-01-25 13:58:50,897 ERROR [498501d1-d7d0-4096-91bd-63748bbd78ed:18270184] [agent:55213] [agent.remove->(MetadataProcessHandler)] [] [cutorService-11] [i.c.p.p.m.MetadataProcessHandler    ] Failed to find account id for agent:55213

**Comment by ValentinOdier** [comment] 2018-02-14 20:11
Hi,

I think i have the same issue 1.4 Gb cattle.instance table

Most is due to "purged" instance
`
select distinct(state), count(*) from instance group by state;`
+----------+----------+
| state    | count(*) |
+----------+----------+
| purged   |    35715 |
| removed  |        1 |
| running  |      738 |
| stopped  |     1174 |
| stopping |        1 |
+----------+----------+


other tables looks ok.

`SELECT table_name AS "Tables", round(((data_length + index_length) / 1024 / 1024), 2) "Size in MB" FROM information_schema.TABLES WHERE table_schema = "cattle" ORDER BY (data_length + index_length) DESC;`
+-----------------------------------------------+------------+
| Tables                                        | Size in MB |
+-----------------------------------------------+------------+
| instance                                      |    1432.23 |
| audit_log                                     |     180.30 |
| image                                         |      87.48 |
| container_event                               |      45.91 |
| instance_label_map                            |      45.20 |

---------------- ------------------------- --------------------
Rancher | v1.6.11
Cattle | v0.183.30
User Interface | v1.6.30
Rancher CLI | v0.6.5
Rancher Compose | v0.12.5

**Comment by deniseschannon** [comment] 2018-03-12 19:05
@mcanevet @junkiebev @ValentinOdier 

 In 1.6.12, we added cleanup logic for databases, but there as still a known issue where we don't clean up `purged` instances: https://github.com/rancher/rancher/issues/7050#issuecomment-336292654 

Can you check to see if most of your `purged` instances fall in this state?

```
select id, state, path, instance_id from mount where volume_id in (select volume_id from mount where instance_id in (select id from instance where state="purged") and state="inactive") and state="inactive";```

**Comment by ValentinOdier** [comment] 2018-03-20 12:04
Hi,

your query now returns 73K items with currently 85K "purged".

Is there something i can do ?

**Comment by akhildhawan** [comment] 2018-03-23 14:26
@deniseschannon , 
Similar issue with only setup difference Rancher Server 1.16.10.

90K Instances filling up ~5GB DB out of which 25K are purge records with mount reference (following the query you shared} 

Also, there are 102K records @ image as well {though taking just ~80Mb}

Upgraded that to 1.16.14 (stable) as well today but DB cleanup didn't trigger - do I need any special action/configuration for that? Not in favor of trying to do purge cleanup manually.

Thanks in advance!

**Comment by shakefu** [comment] 2018-03-28 18:57
We're seeing the same... ```
| 13084 | inactive | /var/lib/rancher/etc |       13059 |
+-------+----------+----------------------+-------------+
6376 rows in set (0.04 sec)
```
Looks like about 50% of those entries are not getting cleaned up.

**Comment by junkiebev** [comment] 2018-03-28 20:49
`select count(*) from mount where volume_id in (select volume_id from mount where instance_id in (select id from instance where state="purged") and state="inactive") and state="inactive";`

returns 57,020 rows
I see 62,148 agents

the instance table is 1.8GB

**Comment by cjellick** [comment] 2018-04-05 17:56
There were a few issues causing this:
1. we were reataining stale data in the mount table, which held a reference to the instance table (this was a intended behavior, but had the unforseen side effect of blocking row deletes)
2. instances that had a reference held in the mount table would get skipped in our cleanup (this was intentional)
3. we cleanup rows from the instance table in 1000 row batches. If any batch was comprised entirely of instances that were referenced in another table, the entire cleanup would exit (this was a bug)

To fix, we added special cleanup logic to remove unnecessary stale data in the `mount` table and fixed the bug that would cause cleanup to prematurely exit

**Comment by deniseschannon** [comment] 2018-04-05 19:32
Duplicate of https://github.com/rancher/rancher/issues/7050

**Closed by deniseschannon** 2018-04-05 19:32 UTC
Labels: area/database, kind/bug, priority/-1, status/to-test, version/1.6
