### ISSUE TITLE
Expose Docker logging drivers in UI

### ISSUE THREAD

**Issue by cloudnautique** [rancher/rancher#2043] opened 2015-09-15 20:52 UTC
On container create a user can specify a logging driver. This appears to be supported in the current API, on container create there is a LogConfig field.

**Comment by cjellick** [comment] 2016-01-14 17:52
Duplicate of #2935

**Comment by cjellick** [comment] 2016-01-14 17:53
Closed in favor of the 2935 since that one was opened by user

**Closed by cjellick** 2016-01-14 17:52 UTC
Labels: area/ui, kind/enhancement
