### ISSUE TITLE
Invalid shm_size parsing

### ISSUE THREAD

**Issue by courcelm** [rancher/rancher#7989] opened 2017-02-28 14:02 UTC
**Rancher` Versions:**
Server:1.4.1
healthcheck:0.2.3
ipsec:0.8.7
network-services:0.4.5
scheduler:0.6.3

**Docker Version:**

1.12.5

**OS and where are the hosts located? (cloud, bare metal, etc):**

 Ubuntu 16.04.1 LTS (4.4.0)
Bare metal

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**

single node rancher, internal db

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**

Cattle

**Steps to Reproduce:**

Start the following stack from Rancher UI

version: '2'
services:
  hub:
    image: selenium/hub:3.0.1
  chrome:
    image: selenium/node-chrome:3.0.1
    shm_size: 256m
    links:
     - hub:hub

**Results:** 

strconv.ParseInt: parsing "256m": invalid syntax

**Comment by aemneina** [comment] 2017-02-28 22:38
I'm going to close this as a duplicate of: https://github.com/rancher/rancher/issues/3554 We can track progress there.

**Closed by aemneina** 2017-02-28 22:38 UTC
Labels: kind/bug
