### ISSUE TITLE
After etcd backup and refreshing the browser, the backups are not listed for restore in UI

### ISSUE THREAD

**Issue by soumyalj** [rancher/rancher#17557] opened 2019-01-23 23:36 UTC
Version: Master build from Jan 23

Steps:

1. Create a DO cluster with S3 configuration
2. Click on edit cluster and perform "Backup now"
3. Backup is performed which can be observed in S3 and also
https://testabc/v3/clusters/c-8hddb/etcdbackups
4. Perform a back using backup now. 
5. Refresh the UI
6. Perform a "restore from backup".
The backups are not listed in the dropdown
<img width="990" alt="screen shot 2019-01-23 at 3 30 24 pm" src="https://user-images.githubusercontent.com/18536626/51644188-33cf0600-1f24-11e9-9a35-d7a15f38d155.png">

The backups are available in https://testabc/v3/clusters/c-8hddb/etcdbackups
and also S3
```
"data": [ 5 items
{
"annotations": {
"lifecycle.cattle.io/create.etcdbackup-controller": "true"
},
"backupConfig": {
"intervalHours": 12,
"retention": 6,
"s3BackupConfig": {
"accessKey": "abcde",
"bucketName": "testbucket",
"endpoint": "s3.amazonaws.com",
"type": "/v3/schemas/s3BackupConfig"
},
"type": "/v3/schemas/backupConfig"
},


```

**Comment by westlywright** [comment] 2019-01-25 19:50
I was unable to reproduce this before and after fixing a separate UX bug with backups. I tested on local and s3 backup with a local cluster and a live cluster on DO. Will move this to test to re-verify after pr#2594 is merged.

**Comment by davidnuzik** [comment] 2019-01-29 18:58
I was able to reproduce the issue. I was on the cluster details page and did "Backup now" using local configuration. I refreshed the browser, then did a "Restore From Backup" and my backups are missing in the drop down menu:
![image](https://user-images.githubusercontent.com/45179589/51932837-39619b80-23bd-11e9-9e2c-ab873ba52323.png)

**Comment by davidnuzik** [comment] 2019-02-08 20:32
Version: Master 2.2 (2/8/19)
Confirmed fix. Cannot reproduce now, when I create a backup, then refresh the browser, and then try to restore the snapshots are listed now.
Tried this with both s3 and local etcd backup types.

**Closed by davidnuzik** 2019-02-08 20:32 UTC
Labels: area/ui, kind/bug-qa, status/ready-for-review, status/resolved, status/to-test, team/az, version/2.0
