### ISSUE TITLE
SSH timeout creating multiple clusters with same node prefix w/DO 

### ISSUE THREAD

**Issue by erikwilson** [rancher/rancher#17543] opened 2019-01-23 18:28 UTC
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
Quickly create multiple clusters with same node prefix using DigitalOcean/RKE

**Result:**
Errors like:
```
2019/01/23 21:08:45 [ERROR] ClusterController c-bqmpx [cluster-provisioner-controller] failed with : [controlPlane] Failed to bring up Control Plane: [Failed to verify healthcheck: Service [kube-apiserver] is not healthy on host [165.227.120.79]. Response code: [401], response body: {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"Unauthorized","reason":"Unauthorized","code":401}
, log: E0124 04:08:40.100811       1 authentication.go:62] Unable to authenticate the request due to an error: [x509: certificate signed by unknown authority, x509: certificate signed by unknown authority (possibly because of "crypto/rsa: verification error" while trying to verify candidate authority certificate "kube-ca")]]

2019/01/23 21:11:37 [ERROR] NodeController c-5k8b5/m-8tmlw [node-controller] failed with : Error creating machine: Error running provisioning: stat management-state/node/nodes/erik1/machines/erik1/id_rsa: no such file or directory

2019/01/23 11:08:01 [ERROR] NodeController c-f6j9b/m-brrnl [node-controller] failed with : Error creating machine: Error detecting OS: Too many retries waiting for SSH to be available.  Last error: Maximum number of retries (60) exceeded
```

**Other details that may be helpful:**
If new cluster is created before previously created cluster has connected SSH keys of previous cluster are overwritten due to using same paths on server.

**Comment by dramich** [comment] 2019-08-09 21:03
Unable to repro this in v2.2.7. This was fixed by the inclusion of the jailer so now docker-machine is running in a different directory for each cluster.

**Comment by jiaqiluo** [comment] 2019-08-10 00:01
The bug is reproduced Rancher: v2.1.6

Steps:
- created two DO clusters which node pools have the same name at the same time

Result:

<img width="1417" alt="Screen Shot 2019-08-09 at 4 58 06 PM" src="https://user-images.githubusercontent.com/6218999/62814709-44615b00-bac7-11e9-9213-4583a1397c3d.png">

**Comment by jiaqiluo** [comment] 2019-08-10 00:16
Done the same test in Rancher:mater-head bc3700f8 and did not see the problem happens.
Since now docker-machine is running in a different directory for each cluster, the problem is fixed fundamental.

**Closed by jiaqiluo** 2019-08-10 00:16 UTC
Labels: [zube]: To Test, kind/bug, team/az
