### ISSUE TITLE
Add a "Developing Rancher" section or document to this repo

### ISSUE THREAD

**Issue by scriptjs** [rancher/rancher#15052] opened 2018-08-13 00:59 UTC
Rancher is open source but its difficult to build upon it or contribute bug fixes without basic developer documentation. This should include the appropriate tool chain and versions, vendoring, and build instructions for the project.

Would appreciate a section in the README.md or dedicate a page in the wiki. I've seen efforts of others to attempt to document this but this really needs to come from Rancher. 

https://github.com/jomeier/rancher-2.x-development

Many thanks.

**Comment by cjellick** [comment] 2018-08-16 18:16
related maybe dupe https://github.com/rancher/rancher/issues/13933

**Comment by cjellick** [comment] 2018-09-10 17:29
@maxkorp can you open a corresponding issue in the docs repo?

**Comment by loganhz** [comment] 2018-10-23 13:28
Close in favor of https://github.com/rancher/docs/issues/927

**Comment by scriptjs** [comment] 2018-10-23 15:13
Hello @loganhz, @cjellick, @vincent99, @deniseschannon Why this issue has been closed. #927 suggests documentation be added to docs with no time line or prioritization. I have never believed this documentation belongs in front facing docs, except by reference (as to how one can contribute to the project). It needs to be documented in this repository. I am asking that @loganhz revert the change to this issue.

I have been looking forward to a resolution. There has been ping pong on this issue for at least 3 months. Closing it in favor of #927 removes it from the 2.1 milestone. This was already dropped from the 2.0 milestone which was frustrating. Moving it evades resolution which is even more disappointing.

Transparency is an important part of open source. As the project grows in size and scope, its important there are more eyes on the code. Concise instructions for building the project to evaluate an element of functionality, performance, fix bugs, extensions or to conceptualize a capability through code play is necessary. A normal part of documenting an open source project is to document the process of building and testing it. 

Instructions extend beyond running make, include tool chain installation, and dependency management, etc. I believe this is as important to your org (for orienting developers) as it is to open source developers to hack on rancher.

This issue was raised in different ways in the past. Others outside the rancher org have gone as far to start properly document the build and test process as best they can. I sincerely hope Rancher will take the lead, take action on this issue, and demonstrate an appropriate level of transparency for the project. Essential instructions for open source developers are required. Anything less does not speak of openness.

**Comment by maxkorp** [comment] 2018-10-24 19:11
Whoops I guess it never landed in this issue, but I added some docs here:
https://github.com/rancher/rancher/wiki/Getting-started-with-Rancher-2.0-Development

there are some code guidelines here: https://github.com/rancher/rancher/wiki/Coding-Guidelines-for-2.0

This got closed since those docs got added, and there was another related issue (this is probably a dupe of that, or vice versa) that those were created in response to.

**Comment by scriptjs** [comment] 2018-10-28 01:36
@maxkorp Thank you. Appreciate this effort! I will experiment with what you provided. I think we can close this issue on this basis. If there are issues encountered with building etc, will file issues against docs that have now been written.

**Closed** 2018-10-28 01:49 UTC
Labels: team/az, version/2.0
