### ISSUE TITLE
Some RKE2 downstream cluster options are reset to UI defaults on first Edit

### ISSUE THREAD

**Issue by snasovich** [rancher/rancher#37597] opened 2022-05-05 02:10 UTC
**Rancher Server Setup**
- Rancher version: 2.6-head (9de50354f56f69d56f84d324db62db624832486f)
- Installation option (Docker install/Helm Chart): Helm Chart (though this is likely irrelevant)
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): ?
- Proxy/Cert Details: None

**Information about the Cluster**
- Kubernetes version: v1.20.8
- Cluster Type (Local/Downstream): Downstream
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider): RKE2 provisioned

**User Information**
- What is the role of the user logged in? (Admin/Cluster Owner/Cluster Member/Project Owner/Project Member/Custom): Admin
   
**Describe the bug**
Certain RKE2 provisioned downstream cluster options (e.g. Drain nodes on upgrade settings) that were modified during initial cluster creation are reset to their default UI values on the first cluster Edit.

**To Reproduce**
1. Provision an RKE2 node driver cluster in any cloud provider setting "Upgrade Strategy -> Control Plane (or Worker Nodes) -> Drain Nodes" to "No" or leaving it as "Yes" and unchecking "Delete pods using emptyDir volumes" (so they are different than UI default)
	- Note that UI defaults may be changed in the future which may affect bug reproduction using this exact scenario; however it should still be reproducible in general, see more info in "Additional context".
<img width="1525" alt="image" src="https://user-images.githubusercontent.com/85187633/166853604-b32c4936-d0dc-4d31-abfe-5c08f1d7baa5.png">
2. "Edit Config" for this cluster (don't have to wait for it to finish provisioning) and switch to the "Upgrade Strategy" tab.
3. Observe the values of the mentioned fields switch back to defaults:
<img width="1525" alt="image" src="https://user-images.githubusercontent.com/85187633/166853699-59d97a85-a285-4981-b148-79671e9798c9.png">
4. Note that the change happens "behind the scenes", so the user doesn't have to click "Upgrade Strategy" tab for the issue to reproduce. Simply hitting "Save" right away on "Edit Config" screen would save the object with these settings reverted to UI defaults.
5. Another notable item is that if the referenced configuration changes are done on the "Edit Config" screen, the values actually "stick" and subsequent "Edit Config"s perform as expected.

**Expected Result**
Any values set on cluster creation page should not be reset back to UI defaults on "Edit Config" screen.

**Additional context**
This issue seems to stem from the difference in how values that have backend default values are handled in Rancher API based on request type (POST/PUT/GET).

The explanation below is based on setting "Delete pods using emptyDir volumes" to unchecked for Upgrade Strategy -> Control Plane.

When a cluster is created, UI submits POST request to `v1/provisioning.cattle.io.clusters` endpoint with JSON payload specifying all field values regardless whether their values match backend default values or not. For example (note `deleteEmptyDirData` set to `false`):
```json
    "spec": {
        "rkeConfig": {
            "chartValues": {
                "rke2-calico": {}
            },
            "upgradeStrategy": {
                "controlPlaneConcurrency": "1",
                "controlPlaneDrainOptions": {
                    "deleteEmptyDirData": false,
                    "disableEviction": false,
                    "enabled": true,
                    "force": false,
                    "gracePeriod": -1,
                    "ignoreDaemonSets": true,
                    "ignoreErrors": false,
                    "skipWaitForDeleteTimeoutSeconds": 0,
                    "timeout": 120
                },
```

However, if the saved object is then retrieved with GET request to `v1/provisioning.cattle.io.clusters/fleet-default/(cluster-name)` the returned JSON omits the fields that have backend default values (note how `deleteEmptyDirData` as well as few other fields are not present on `controlPlaneDrainOptions` object):
```json
    "spec": {
        "rkeConfig": {
...(few other fields omitted)...
            "upgradeStrategy": {
                "controlPlaneConcurrency": "1",
                "controlPlaneDrainOptions": {
                    "enabled": true,
                    "gracePeriod": -1,
                    "ignoreDaemonSets": true,
                    "timeout": 120
                },
```
It's interesting that 201 OK response received back from initial POST call has payload that contains all the fields.

Then, when "Edit Config" screen is used to modify this cluster object, UI sends PUT request to `v1/provisioning.cattle.io.clusters/fleet-default/(cluster-name)` endpoint with the payload containing all the fields again (not just the ones returned by GET). The update completes successfully and the response payload contains all the fields.

However, if GET request is sent again to `v1/provisioning.cattle.io.clusters/fleet-default/(cluster-name)` the returned JSON has all the fields, including the ones where values match backend defaults (response from GET below is assuming previous PUT was sent with `deleteEmptyDirData` set to `false`):
```json
    "spec": {
        "rkeConfig": {
...(few other fields omitted)...
            "upgradeStrategy": {
                "controlPlaneConcurrency": "1",
                "controlPlaneDrainOptions": {
                    "deleteEmptyDirData": false,
                    "disableEviction": false,
                    "enabled": true,
                    "force": false,
                    "gracePeriod": -1,
                    "ignoreDaemonSets": true,
                    "ignoreErrors": false,
                    "skipWaitForDeleteTimeoutSeconds": 0,
                    "timeout": 120
                },
```

It should be discussed what the desired behavior should be here since the issue is likely in Rancher core framework like Steve. However, one option could be to ensure values that match backend-defaults are persisted and GET requests always return complete object with all fields set. This would eliminate any ambiguity with API client (e.g. UI) imposing their own defaults for fields that were not returned (undefined).
This issue may be outside of `team/area2` immediate realm based on the comment above.

**Comment by jakefhyde** [comment] 2022-05-11 18:58
Since this issue doesn't seem to be affecting other API endpoints, it could be the mutating webhook we have for the cluster object. It seems likely at this time that the marshaling and subsequent unmarshaling of the cluster object drops the `omitempty` fields on subsequent updates to the object.

**Comment by HarrisonWAffel** [comment] 2022-05-20 20:05
After looking into this issue, the inconsistency seems to originating from the rancher web-hook, which drops fields that have been tagged with `omitempty`. Disabling specific fields (such as `Delete Pods using emptyDir volumes`) results in the incoming payload sent from the UI to the web-hook (via kubernetes) having fields with zero values. As such those fields are omitted, and the UI defaults are applied. Removing the `omitempty` fields from the `DrainOptions` struct will avoid the dropping of the fields entirely, and ensure that UI defaults do not overwrite the values initially supplied. 

This does not fully explain the difference between `POST` and `PUT` requests as initially observed, this behavior is likely due to an intricacy within steve/norman. However, removing the `omitempty` tag should avoid this discrepancy and result in all of the fields being returned and saved in all instances. 

There is some odd behavior that cannot be address with the removal of the `omitempty` tag. For example, deselecting the `Timeout after` box will result in a value of `0` being passed to the backend. This value is then returned in the `GET` request made by the UI, and the box will become selected but the `Drain Timeout` value will be `0`. Similar behavior occurs with the `Override pod termination grace periods` field - when this field is deselected, a value of `-1` is sent to the backend, which indicates that the [grace period should be honored](https://rancher.com/docs/rancher/v2.0-v2.4/en/cluster-admin/nodes/#grace-period). This value is then returned to the UI and the button is deselected, as a `-1` value means we do not want to override the grace period. This behavior is somewhat unintuitive, but not necessarily a bug.

**Comment by Josh-Diamond** [comment] 2022-05-31 18:47
Ticket #37597 - Test Results

With Docker on a single-node instance:

Reproduced on rancher `v2.6-9de50354f56f69d56f84d324db62db624832486f-head`:
1. Fresh install of rancher `v2.6-head`
2. Deploy a downstream RKE2 cluster - [ANY] - with Upgrade strategy changed from default settings
3. Once `Create` is selected; `Edit Config` of cluster and observe Upgrade strategy settings have reverted back to defaults

Screenshots:

`Step 2`
<img width="1430" alt="Screen Shot 2022-05-31 at 11 43 02 AM" src="https://user-images.githubusercontent.com/46494969/171262435-94bf58bf-3634-4a8a-8ffd-16fe0a8899dc.png">

`Step 3`
<img width="1433" alt="Screen Shot 2022-05-31 at 11 43 34 AM" src="https://user-images.githubusercontent.com/46494969/171262481-cf159ad9-19bc-4476-9201-cb3d31ae18a0.png">

---

Will validate once [PR](https://github.com/rancher/rancher/pull/37785) is merged

**Comment by sowmyav27** [comment] 2022-05-31 20:50
Moving this to Review since the PR is not merged.

**Comment by Josh-Diamond** [comment] 2022-06-01 16:22
Ticket #37597 - Test Results [pt. 2]

With Docker on a single-node instance:

Verified on rancher `v2.6-cba26e9274d371823d039121e7a613da42f44730-head`:
1. Fresh install of rancher `v2.6-head`
2. Deploy a downstream RKE2 cluster - [ANY] - with Upgrade strategy changed from default settings
3. Once `Create` is selected; `Edit Config` of cluster and observe Upgrade strategy settings have persisted

Screenshots:

`Step 2`
<img width="1124" alt="Screen Shot 2022-06-01 at 9 18 45 AM" src="https://user-images.githubusercontent.com/46494969/171452637-f6b5d389-6415-4d25-ab50-8e5d0b82efc9.png">

`Step 3`
<img width="1129" alt="Screen Shot 2022-06-01 at 9 17 57 AM" src="https://user-images.githubusercontent.com/46494969/171452665-b8e64cbd-8196-4a99-84e1-cedbc4b6225b.png">

**Closed by Josh-Diamond** 2022-06-01 16:22 UTC
Labels: area/webhooks, kind/bug-qa, [zube]: QA Working, QA/XS, area/provisioning-v2, feature/provisioned-rke2-k3s, feature/webhook, team/area2, area/clusterprovisioningv2
