### ISSUE TITLE
Worker server stuck on "Waiting to register with Kubernetes"

### ISSUE THREAD

**Issue by leoNardtwo** [rancher/rancher#30000] opened 2020-11-10 14:12 UTC
Hello everyone,
I have an issue trying to add a worker node/server to a Rancher cluster.

Situation:
I have two server: a Master server and worker server. 
Both server with Ubuntu 20.04 and both server with the same versions of containers images for Rancher. I'm using the stable release of Rancher.
In master server
    rancher/rke-tools                                 v0.1.66                                                                                                        
    rancher/nginx-ingress-controller                  nginx-0.35.0-rancher2                                                                                           
    rancher/hyperkube                                 v1.18.10-rancher1                                                                                               
    rancher/rancher-agent                             v2.4.8                                                                                                          
    rancher/rancher                                   stable                                                                                                          
    rancher/rancher-agent                             v2.4.7                                                                                                          
    rancher/rancher                                   v2.4.7                                                                                                          
    rancher/rke-tools                                 v0.1.64                                                                                                         
    rancher/calico-node                               v3.13.4                                                                                                         
    rancher/calico-pod2daemon-flexvol                 v3.13.4                                                                                                         
    rancher/calico-cni                                v3.13.4                                                                                                         
    rancher/coredns-coredns                           1.6.9                                                                                                           
    rancher/coreos-flannel                            v0.12.0                                                                                                         
    rancher/kube-api-auth                             v0.1.4                                                                                                          
    rancher/coreos-etcd                               v3.4.3-rancher1                                                                                                 
    rancher/metrics-server                            v0.3.6                                                                                                          
    rancher/cluster-proportional-autoscaler           1.7.1                                                                                                           
    rancher/nginx-ingress-controller-defaultbackend   1.5-rancher1                                                                                                    
    rancher/pause                                     3.1                                                                                                             

In worker server
    rancher/rke-tools       v0.1.66             
    rancher/hyperkube       v1.18.10-rancher1   
    rancher/rancher-agent   v2.4.8              

The Master-worker(has etcd, Controlplane and worker options) server has a public IP and a private ip, and a firewall with ports 3120 and 3121 openned, beause i switched ports from 80 and 443 to 3120 and 3121.
The Worker(just worker option) server has only a private ip. All private ips(master-worker and worker) in the same network range.
I was able to create the Rancher server and cluster with the master-worker server but i can't join the worker server to the cluster is stuck on "Waiting to register with Kubernetes".

Here logs from the Worker server:
[kube-proxy]
I1110 12:19:54.732165   38266 trace.go:116] Trace[1788583649]: "Reflector ListAndWatch" name:k8s.io/client-go/informers/factory.go:135 (started: 2020-11-10 12:19:25.716389265 +0000 UTC m=+287.065376894) (total time: 29.01571819s):
Trace[1788583649]: [29.01571819s] [29.01571819s] END
E1110 12:19:54.732197   38266 reflector.go:178] k8s.io/client-go/informers/factory.go:135: Failed to list *v1.Service: an error on the server ("") has prevented the request from succeeding (get services)
I1110 12:20:34.746984   38266 trace.go:116] Trace[1520358803]: "Reflector ListAndWatch" name:k8s.io/client-go/informers/factory.go:135 (started: 2020-11-10 12:20:05.731627409 +0000 UTC m=+327.080615038) (total time: 29.015316508s):
Trace[1520358803]: [29.015316508s] [29.015316508s] END
E1110 12:20:34.747019   38266 reflector.go:178] k8s.io/client-go/informers/factory.go:135: Failed to list *v1.Endpoints: an error on the server ("") has prevented the request from succeeding (get endpoints)

[nginx-proxy]
2020/11/10 12:38:11 [error] 14#14: *5271 upstream timed out (110: Operation timed out) while connecting to upstream, client: 127.0.0.1, server: 0.0.0.0:6443, upstream: "x.x.x.8:6443", bytes from/to client:0/0, bytes from/to upstream:0/0
2020/11/10 12:38:12 [error] 14#14: *5273 upstream timed out (110: Operation timed out) while connecting to upstream, client: 127.0.0.1, server: 0.0.0.0:6443, upstream: "x.x.x.8:6443", bytes from/to client:0/0, bytes from/to upstream:0/0

[kubelet]
E1110 12:39:56.525035   38447 event.go:269] Unable to write event: 'Patch https://127.0.0.1:6443/api/v1/namespaces/default/events/k8sworker1.1646248989368918: read tcp 127.0.0.1:56316->127.0.0.1:6443: read: connection reset by peer' (may retry after sleeping)
E1110 12:39:56.572547   38447 kubelet.go:2270] node "k8sworker1" not found
E1110 12:39:56.672899   38447 kubelet.go:2270] node "k8sworker1" not found
E1110 12:39:56.773154   38447 kubelet.go:2270] node "k8sworker1" not found
E1110 12:39:56.873494   38447 kubelet.go:2270] node "k8sworker1" not found
I1110 12:39:56.918721   38447 trace.go:116] Trace[1317802403]: "Reflector ListAndWatch" name:k8s.io/kubernetes/pkg/kubelet/kubelet.go:517 (started: 2020-11-10 12:39:27.907891446 +0000 UTC m=+1485.907784852) (total time: 29.010766602s):
Trace[1317802403]: [29.010766602s] [29.010766602s] END
E1110 12:39:56.918753   38447 reflector.go:178] k8s.io/kubernetes/pkg/kubelet/kubelet.go:517: Failed to list *v1.Service: an error on the server ("") has prevented the request from succeeding (get services)
E1110 12:39:56.973841   38447 kubelet.go:2270] node "k8sworker1" not found
E1110 12:39:58.277742   38447 kubelet.go:2270] node "k8sworker1" not found
E1110 12:39:58.378039   38447 kubelet.go:2270] node "k8sworker1" not found
E1110 12:39:58.478309   38447 kubelet.go:2270] node "k8sworker1" not found
I1110 12:39:58.491578   38447 kubelet_node_status.go:294] Setting node annotation to enable volume controller attach/detach
I1110 12:39:58.541552   38447 kubelet_node_status.go:486] Recording NodeHasSufficientMemory event message for node k8sworker1
I1110 12:39:58.541609   38447 kubelet_node_status.go:486] Recording NodeHasNoDiskPressure event message for node k8sworker1
I1110 12:39:58.541620   38447 kubelet_node_status.go:486] Recording NodeHasSufficientPID event message for node k8sworker1
I1110 12:39:58.541656   38447 kubelet_node_status.go:70] Attempting to register node k8sworker1
E1110 12:39:58.578603   38447 kubelet.go:2270] node "k8sworker1" not found
E1110 12:39:58.678925   38447 kubelet.go:2270] node "k8sworker1" not found
E1110 12:39:58.779173   38447 kubelet.go:2270] node "k8sworker1" not found
E1110 12:39:58.879460   38447 kubelet.go:2270] node "k8sworker1" not found
W1110 12:39:58.944379   38447 cni.go:237] Unable to update cni config: no networks found in /etc/cni/net.d

Thank  you for you help

**Comment by lindhe** [comment] 2020-11-10 18:27
I've got this too! Awesome, perhaps I'm not insane after all...

**Comment by leoNardtwo** [comment] 2020-11-11 08:03
> I've got this too! Awesome, perhaps I'm not insane after all...
> 
> **EDIT:** I've tried with `rancher/rancher:v2.5.1-linux-amd64` and `v2.4.8-linux-amd64` and they seem to behave in a similar manner.
> 
> **EDIT 2:** I remember doing a dist upgrade to the latest patch version of 20.04 a week or so ago. Could That be the cause?

Hello @lindhe, 
i think that is not the cause because is a fresh installation of ubuntu, in fact all of this are  a fresh installation. 
Thankyou.

**Comment by lindhe** [comment] 2020-11-11 08:30
I didn't particularly mean that the process of upgrading caused the problem, but rather that `20.04.01` perhaps behaves differently than `20.04` did and that Rancher may not be tested for that version of Ubuntu.

**Comment by adrootrr** [comment] 2021-01-16 12:38
I've got this too...

**Comment by adrootrr** [comment] 2021-01-16 14:28
> I didn't particularly mean that the process of upgrading caused the problem, but rather that `20.04.1` perhaps behaves differently than `20.04` did and that Rancher may not be tested for that version of Ubuntu.

Modifying nginx.com in rancher/ rke-tools image 

error_log stderr notice;

worker_processes auto;
events {
  multi_accept on;
  use epoll;
  worker_connections 1024;
}

stream {
        upstream kube_apiserver {
            
            server master1:6443;
            server master2:6443;
            server master3:6443;
            
        }

        server {
            listen        6443;
            proxy_pass    kube_apiserver;
            proxy_timeout 30;
            proxy_connect_timeout 2s;

        }

}

**Comment by lindhe** [comment] 2021-01-17 12:33
I did eventually resolve my issue. Turned out that something had caused (possibly the act of upgrading Ubuntu without gracefully shutting down Rancher) some containers to be stopped but not removed. So there were a bunch of old Rancher stuff lingering but didn't show up when I ran `docker ps`. But running `docker ps -a` revealed them, and after removing them I could install a new cluster successfully. Hope this helps someone else!

**Comment by superseb** [comment] 2021-01-18 11:44
In case of the original issue, the `while connecting to upstream` in the `nginx-proxy` container indicates the worker cannot contact the kube-apiserver to register itself as a node. The `nginx.conf` inside this container is automatically generated based on the controlplane nodes in the cluster. This does not need any manual modification as shown above. If you experience any issues here, please file a new issue with the info from your setup and the steps to reproduce.

Any node being reused in a cluster should be cleaned as old data/resources can conflict on cluster creation. This is described at https://rancher.com/docs/rancher/v2.x/en/cluster-admin/cleaning-cluster-nodes/. If this occurs with fresh or cleaned nodes, please file a new issue with info rom your setup and the steps to reproduce.

I'm closing this issue as the root cause seems to be clear based on the log, and its hard to investigate any other variations of an issue without the provided setup info requested in the issue template. Please file a new issue in case you are experiencing this issue with the data requested so we can classify a possibly bug and find the root cause.

**Closed by superseb** 2021-01-18 11:44 UTC

**Comment by clayrisser** [comment] 2021-05-06 10:06
@superseb I am getting this error with fresh cleaned nodes. I have tried Ubuntu 20.04, Ubuntu 18.04 and Debian 10 and I get the exact same error with all of them. I filed a new issue like you requested. Please take a look if you don't mind. More details are in the issue linked below.

https://github.com/rancher/rancher/issues/32575

**Comment by clayrisser** [comment] 2021-05-06 10:07
> I didn't particularly mean that the process of upgrading caused the problem, but rather that `20.04.1` perhaps behaves differently than `20.04` did and that Rancher may not be tested for that version of Ubuntu.

I tried with older versions of Ubuntu and even Debian 10 and had the same error.
