### ISSUE TITLE
Rancher UI: Service upgrade is missing internal labels (like io.rancher.container.agent.role)

### ISSUE THREAD

**Issue by pboos** [rancher/rancher#4476] opened 2016-04-19 22:51 UTC
Rancher Version: 1.0.1
Docker Version: 1.10.3
OS: Rancher-OS

Steps to Reproduce: 
1. Create a service with the following lables:
    io.rancher.container.create_agent: 'true'
    io.rancher.container.agent.role: 'environment'
2. In the rancher UI: Click on update for the service and check the labels

Results: 
Labels are empty.

So if one doesn't check in an upgrade, all those labels will be lost in an upgrade. For example with  letsencrypt from the catalog. If one tries to update it, it won't work anymore because the cattle env variables (like CATTLE_URL) are missing.

Expected:
Labels should show test=true

Problem is, that one always has to remember to add the labels again in an update through the UI. Of course this is not a problem for when one automates updates and does it with scripts. But if one does it manually, it causes to break things.

--------------

I saw that there was once a similar issue: https://github.com/rancher/rancher/issues/2342
So I wonder if that bug got reintroduced or if it didn't cover those labels here even though somebody mentioned them.

**Comment by deniseschannon** [comment] 2016-04-21 20:32
By default, the UI hides any labels that are `io.rancher.x.x`. 

In order for upgrade (and clone) to work for these labels, it needs a UI equivalent so the UI can interpret that these labels have been used.

**Comment by janeczku** [comment] 2016-09-09 22:10
Pre-duplicate of #5286. This was fixed in v1.1.1.

**Closed by janeczku** 2016-09-09 22:10 UTC
Labels: area/service, area/ui, kind/bug
