### ISSUE TITLE
No basic auth credentials supplied using custom registry

### ISSUE THREAD

**Issue by rocketeer125** [rancher/rancher#4250] opened 2016-03-31 15:25 UTC
When configuring a custom registry (using Amazon ECR), Basic Auth credentials are stripped out on pulling the docker image from the registry: 

docker-compose.yml:

    myapp:
      image: 95629****971.dkr.ecr.us-east-1.amazonaws.com/app

Results in:

`Waiting for [instance:mystack_myapp_1]. Instance status: 500 Server Error: Internal Server Error ("Get    https://95629****971.dkr.ecr.us-east-1.amazonaws.com/v2/app/manifests/latest: no basic auth credentials")`

Though the registry shows active.

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v1.0.0` Cattle: `v0.159.2` UI: `v0.100.3` |
|Access|`Disabled`|
|Route|`environment.index`|

**Comment by deniseschannon** [comment] 2016-03-31 20:01
Can you confirm what type of environment you have? Cattle/K8S/Swarm?

**Comment by rocketeer125** [comment] 2016-04-01 07:50
@deniseschannon I'm using Cattle on CentOS 7.

**Comment by deniseschannon** [comment] 2016-04-04 17:43
I re-read the issue and realized that this is a duplicate of https://github.com/rancher/rancher/issues/3126.

We don't have support for Amazon ECR.

**Closed by deniseschannon** 2016-04-04 17:43 UTC
Labels: kind/question

**Comment by rocketeer125** [comment] 2016-04-05 13:06
Ok I thought this was now supported: http://rancher.com/using-amazon-container-registry-service/

**Comment by deniseschannon** [comment] 2016-04-05 17:28
It looks like there is a basic auth issue with custom registries. Please follow: https://github.com/rancher/rancher/issues/3634

Thanks for pointing out the Amazon ECR blog post. :)

**Comment by deniseschannon** [comment] 2016-04-05 17:28
I forgot to mention that it will be in our next major release (1.1).
