### ISSUE TITLE
Rancher backup | Can't rollback (restore) Rancher from 2.6-head to 2.6.3

### ISSUE THREAD

**Issue by sgapanovich** [rancher/rancher#36803] opened 2022-03-08 18:51 UTC
**Rancher Server Setup**
- Rancher version: 2.6.3
- Installation option (Docker install/Helm Chart): Helm
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): rke1
- Proxy/Cert Details: self-signed
   
**Describe the bug**

Rancher server is not coming up active when rolling back (restoring) rancher to the backup taken in 2.6.3

**To Reproduce**
 
Official docs : https://rancher.com/docs/rancher/v2.6/en/installation/install-rancher-on-k8s/rollbacks/
1. Create Rancher on 2.6.3
2. Save kubeconfig for the local cluster (you will need it in the future when Rancher UI is not available)
3. Install Rancher Backup (you have to have a s3 bucket ready and a secret to access it)
4. Take a backup
5. Upgrade rancher to 2.6-head (3f9109c)
6. After rancher is upgraded scale down Rancher deployment to 0
7. Create a Restore yaml file with your bucket info and the secret to access your bucket (see Rancher docs above for more info) and then run `kubectl create -f <file>` 

**Result**
Restore is never completed with the following error logged in rancher-backup pod (`kubectl logs rancher-backup-6495d4976b-896b5 -n cattle-resources-system`)

```
ERRO[2022/03/08 16:49:39] Error restoring CRDs restoreCRDs: restoreResource: err updating resource CustomResourceDefinition.apiextensions.k8s.io "machinedeployments.cluster.x-k8s.io" is invalid: status.storedVersions[1]: Invalid value: "v1beta1": must appear in spec.versions
ERRO[2022/03/08 16:49:39] error syncing 'restore-migration': handler restore: error restoring CRDs, check logs for exact error, requeuing
```

apiversion differences between 2.6.3 and 2.6-head
![diffe](https://user-images.githubusercontent.com/40282141/157304679-9efe4d1f-0af4-4bde-b25f-1c79a826b28e.jpg)

**Expected Result**

Rancher restores to the state from backup

**Comment by SheilaghM** [comment] 2022-03-09 22:34
@superseb - Please look at this.  Can this be fixed for 2.6.4 or do we need to push to 2.6.5?

**Comment by superseb** [comment] 2022-03-11 17:25
This is also seen when deploying v2.6.3, updating image to v2.6-head and going back to v2.6.3 after (just a rollback without restore)

```
2022/03/10 18:14:11 [FATAL] failed to update clusters.cluster.x-k8s.io apiextensions.k8s.io/v1, Kind=CustomResourceDefinition for  clusters.cluster.x-k8s.io: CustomResourceDefinition.apiextensions.k8s.io "clusters.cluster.x-k8s.io" is invalid: status.storedVersions[1]: Invalid value: "v1beta1": must appear in spec.versions
```

Seems to be related to newer CRD versions introduced by bumping `cluster-api` from v0.4.4 to v1.0.2 in https://github.com/rancher/rancher/commit/aaac1dff68e6926efd04940b6e02b275df0c1743 and changes to v1beta1.

So far it seems to be caused by the CRDs that are updated with a new version (v1beta1), then the rollback to v2.6.3 (or the restore) wants to apply the CRDs from the previous versions that does not have v1beta1 but its trying to merge/modify `status.storedVersions` but the CRD does not have v1beta1 as its only available in the newer lib (v2.6.4 prereleases).

Some options that were thought of:

- Delete/recreate CRDs, this can't happen as we have resources created from these CRDs (both for rollback and restore). For a restore when migrating to a new cluster, we dont have this issue as there are no existing CRDs, but for any other scenario we need to change existing CRDs
- Automate the modification needed to CRDs on Rancher startup and in backup-restore-operator, as Rancher only starts after the restore we can't only have it in Rancher but it also needs to exist in backup-restore-operator

For testing purposes, I've used this to get the CRD in a state where a rollback would succeed (haven't tested with restore but should be the same):

```
# Make sure you have `kubectl proxy` active

curl -d '[{ "op": "replace", "path":"/status/storedVersions", "value": ["v1alpha4"] }]' \
  -H "Content-Type: application/json-patch+json" \
  -X PATCH \
 http://localhost:8001/apis/apiextensions.k8s.io/v1beta1/customresourcedefinitions/clusters.cluster.x-k8s.io/status

curl -d '[{ "op": "replace", "path":"/status/storedVersions", "value": ["v1alpha4"] }]' \
  -H "Content-Type: application/json-patch+json" \
  -X PATCH \
 http://localhost:8001/apis/apiextensions.k8s.io/v1beta1/customresourcedefinitions/machinedeployments.cluster.x-k8s.io/status

curl -d '[{ "op": "replace", "path":"/status/storedVersions", "value": ["v1alpha4"] }]' \
  -H "Content-Type: application/json-patch+json" \
  -X PATCH \
 http://localhost:8001/apis/apiextensions.k8s.io/v1beta1/customresourcedefinitions/machinehealthchecks.cluster.x-k8s.io/status

curl -d '[{ "op": "replace", "path":"/status/storedVersions", "value": ["v1alpha4"] }]' \
  -H "Content-Type: application/json-patch+json" \
  -X PATCH \
 http://localhost:8001/apis/apiextensions.k8s.io/v1beta1/customresourcedefinitions/machines.cluster.x-k8s.io/status

curl -d '[{ "op": "replace", "path":"/status/storedVersions", "value": ["v1alpha4"] }]' \
  -H "Content-Type: application/json-patch+json" \
  -X PATCH \
 http://localhost:8001/apis/apiextensions.k8s.io/v1beta1/customresourcedefinitions/machinesets.cluster.x-k8s.io/status
```

**Comment by thedadams** [comment] 2022-03-16 20:25
It seems that this issue only affects HA Rancher.

I followed [these steps](https://rancher.com/docs/rancher/v2.5/en/installation/other-installation-methods/single-node-docker/single-node-upgrades) to upgrade the Docker install of Rancher and then followed [these steps](https://rancher.com/docs/rancher/v2.5/en/installation/other-installation-methods/single-node-docker/single-node-rollbacks/) to rollback the Docker install of Rancher and was successful with this.

**Comment by jiaqiluo** [comment] 2022-03-23 22:29
@superseb 's comment has explained the issue and cause pretty well.  However, the proposed fix (patching the CRD) does not work, so we have to (manually) clean up the cluster before restoring the backup. 

We have made two scripts to make it easier: one for cleaning up the cluster, another one for checking if there is any rancher-related resources in the cluster. They are available here: https://github.com/rancherlabs/support-tools/tree/master/cleanup-rancher-k8s-resources

As the result, we need to update the instruction for restoring Rancher backup in the Docs to add the new requirement. 
https://rancher.com/docs/rancher/v2.6/en/backups/restoring-rancher/

Also, add it to the release note.

**Comment by Jono-SUSE-Rancher** [comment] 2022-03-23 23:54
Thanks for the update Jack. @jtravee - please make sure this gets release noted with the information provided by Jack regarding the scripts. As far as the ticket, we will move it to 2.6.5 once you've release noted it.

**Comment by jtravee** [comment] 2022-03-24 13:09
> Thanks for the update Jack. @jtravee - please make sure this gets release noted with the information provided by Jack regarding the scripts. As far as the ticket, we will move it to 2.6.5 once you've release noted it.

Thanks! I will create an issue for docs today for this and update the release notes; will let you know when completed.

**Comment by MKlimuszka** [comment] 2022-03-24 20:40
There is no fixes going into rancher or rancher-backup-restore.
The cleanup script is ready and passed to QA

**Comment by anupama2501** [comment] 2022-03-24 20:50
Cleanup script was hanging previously for namespaces having finalizers. 

@superseb  provided a new fix https://github.com/rancherlabs/support-tools/pull/160

**Comment by jiaqiluo** [comment] 2022-03-24 22:19
https://github.com/rancherlabs/support-tools/pull/160

**Comment by jiaqiluo** [comment] 2022-03-24 22:20
The fix is added to the above mentioned PR

**Comment by anupama2501** [comment] 2022-03-25 15:54
Validated the issue by 
upgrading rancher from 2.6.3 to 2.6.4-rc13 and rolled back to 2.6.3
upgrading rancher from 2.5.12 to 2.6.4-rc13 and rolled back to 2.5.12


1. Created 5 downstream clusters 1 with 5 nodes 3 worker,1etcd,1cp, 2 with 3 nodes 1 etcd, 1cp,1 worker ,2 with 3 nodes 1 etcd+cp, 2 worker
2. Ran pre-upgrade checks by creating a few workloads and ingresses
3. Installed rancher-backup charts `2.1.0` for 2.6.3 and `1.2.100+up1.2.1` for 2.5.12 respectively.
4. Upgraded rancher to 2.6.4-rc13 and ran post upgrade checks by validating previously created workloads and creating additional workloads and ingresses
5. Ran the verify script which lists out everything that needs to be cleaned up
6. Ran the cleanup script and verified all the namespaces, crds etc that were created by Rancher were cleaned up. - Script took approximately 45 minutes to complete.
7. Verified no remaining namespaces, configmaps, crds etc with the verify script
8. Followed the docs https://rancher.com/docs/rancher/v2.6/en/backups/migrating-rancher/ excluding step3 from the docs.
9. Installed rancher on 2.6.3 and 2.5.12 respectively on the clusters.
10. Ran pre upgrade checks and verified the tests have passed.





Keeping this issue open as the PR for the standalone cleanup and verify scripts is still not merged.

**Comment by jiaqiluo** [comment] 2022-03-25 20:36
Moving this issue to to-test because the linked PR is merged.

**Comment by anupama2501** [comment] 2022-03-25 20:55
Closing the issue validations noted here https://github.com/rancher/rancher/issues/36803#issuecomment-1079164548

**Closed by anupama2501** 2022-03-25 20:55 UTC
Labels: kind/bug-qa, [zube]: To Test, release-note, status/release-blocker, team/area3, feature/charts-backup-restore

**Comment by andruwa13** [comment] 2023-02-17 15:26
kubectl delete -n fleet-default  clusterregistrations $(kubectl get clusterregistrations -n fleet-default)
