### ISSUE TITLE
[BUG] v2prov machine provisioned machines can get stuck in "Creating server * in infrastructure provider" 

### ISSUE THREAD

**Issue by Oats87** [rancher/rancher#41915] opened 2023-06-22 18:39 UTC
**Rancher Server Setup**
- Rancher version: v2.7.3
- Installation option (Docker install/Helm Chart): N/A
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc):
- Proxy/Cert Details: N/A

**Information about the Cluster**
- Kubernetes version: N/A
- Cluster Type (Local/Downstream): Downstream Provisioned

**User Information**
- What is the role of the user logged in? (Admin/Cluster Owner/Cluster Member/Project Owner/Project Member/Custom)
  - If custom, define the set of permissions:
N/A

**Describe the bug**
There is a race condition where Rancher can prematurely clean up machine provision create jobs (and subsequently orphan the created VMs if the machine is deleted). This leads to a state where Rancher is "waiting" for the creation of a machine when the machine has been created already.

**To Reproduce**
1. Create a machine provisioned v2prov cluster
2. Wait for the cluster to become healthy
3. Attempt to scale up a pool (preferably with a lot of nodes)

**NOTE**: Given the fact that this is a race condition, it is NOT consistently reproducible.

**Result**
Occasionally, the machine VM will be created and leave Rancher in a state where it says something along the lines of
"Creating server [*] in infrastructure provider", but the VM is healthy and has already joined the node. The corresponding job will be prematurely cleaned up. If the user attempts to delete the machine, it will proceed to orphan the machine in the infrastructure provider because Rancher thinks the job was never actually created/VM was never actually created.

**Expected Result**
The jobs are not prematurely cleaned up and the `infrastructuremachine` is properly updated.

**Screenshots**

**Additional context**
This is being caused because the machine provision controller is cleaning up the job prematurely if the `providerID` is set on the machine in the line here: https://github.com/rancher/rancher/blob/18ad6028a05d7745d11f47b50ece4fbec1a8997b/pkg/controllers/capr/machineprovision/controller.go#L649

This logic should ensure that the conditions have been reconciled before cleaning up.

**Comment by snasovich** [comment] 2023-06-23 16:53
Moving to "Release Note" status to increase the visibility of it to be put as a known issue onto v2.7.5 release notes.

**Comment by snasovich** [comment] 2023-06-26 23:26
We have new `v2.7-head` image published as of ~7 minutes ago and it's ready to be tested on it!

**Comment by Josh-Diamond** [comment] 2023-06-27 18:13
Ticket #41915 - Test Results - ✅ 
---

❗ Unable to reproduce issue on `v2.7.4` ❗ 

---

Verified with HA Helm Rancher on `v2.7-3aedc24d3087c3bbc4deb4d8c5ae40f55945e913-head`:

| Scenario | Test Case | Result |
|---|---|---|
| 1. | Provision a downstream AWS RKE2 Node driver cluster - [1 all-roles node pool] - once `active`, scale up node pool significantly | ✅ |
| 2. | Provision a downstream AWS RKE2 Node driver cluster - [individual-roles, 3 node pools] - once `active`, scale up node pools significantly | ✅ |
| 3. | Provision a downstream AWS K3s Node driver cluster - [1 all-roles node pool] - once `active`, scale up node pool significantly | ✅ |
| 4. | Provision a downstream AWS K3s Node driver cluster - [individual-roles, 3 node pools] - once `active`, scale up node pools significantly | ✅ |
| 5. | Regression Check: Import a downstream RKE2 cluster + deploy workload | ✅ |
| 6. | Regression Check: Import a downstream K3s cluster + deploy workload | ✅ |

---

Scenario 1 -
1. Fresh install of Rancher `v2.7-head`
2. Provision a downstream AWS RKE2 Node driver cluster, 1 all-roles node pool w/ k8s `v1.26.5+rke2r1`
3. Verified - cluster successfully provisions
4. Once cluster is `active`, scale up the node pool significantly
5. Observe cluster scale up nodes
6. Verified - Node pool successfully scales up, as expected;

---

Scenario 2 -
1. Fresh install of Rancher `v2.7-head`
2. Provision a downstream AWS RKE2 Node driver cluster, 3 node pools w/ individual roles and using k8s `v1.26.5+rke2r1`
3. Verified - cluster successfully provisions
4. Once `active`, scale up each node pool significantly
5. Observe cluster scale up nodes
6. Verified - All node pools successfully scale up; as expected

---

Scenario 3 -
1. Fresh install of Rancher `v2.7-head`
2. Provision a downstream AWS K3s Node driver cluster, 1 all-roles node pool w/ k8s `v1.26.5+k3s1`
3. Verified - cluster successfully provisions
4. Once cluster is `active`, scale up the node pool significantly
5. Observe cluster scale up nodes
6. Verified - Node pool successfully scales up, as expected;

---

Scenario 4 -
1. Fresh install of Rancher `v2.7-head`
2. Provision a downstream AWS K3s Node driver cluster, 3 node pools w/ individual roles and using k8s `v1.26.5+k3s1`
3. Verified - cluster successfully provisions
4. Once `active`, scale up each node pool significantly
5. Observe cluster scale up nodes
6. Verified - All node pools successfully scale up; as expected

---

Scenario 5 - (regression check)
1. Fresh install of Rancher `v2.7-head`
2. Import a downstream RKE2 cluster w/ k8s `v1.26.5+rke2r1`
3. Verified - Cluster successfully imports
4. Deploy a workload
5. Verified - workload successfully deployed + `active`

---

Scenario 6 - (regression check)
1. Fresh install of Rancher `v2.7-head`
2. Import a downstream K3s cluster w/ k8s `v1.26.5+k3s1`
3. Verified - Cluster successfully imports
4. Deploy a workload
5. Verified - workload successfully deployed + `active`

**Closed by Josh-Diamond** 2023-06-27 18:13 UTC
Labels: kind/bug, area/machine, [zube]: QA Working, release-note, area/provisioning-v2, team/area2/sc, team/area2/edi
