### ISSUE TITLE
Catalog description doesn't not change when switching from entry page

### ISSUE THREAD

**Issue by shakefu** [rancher/rancher#7929] opened 2017-02-22 21:41 UTC
**Rancher Versions:**
- Rancher	v1.4.1
- Cattle	v0.176.9
- User Interface	v1.4.6
- Rancher CLI	v0.4.1
- Rancher Compose	v0.12.2

**Docker Version:**
1.13.0

**OS and where are the hosts located? (cloud, bare metal, etc):**
CoreOS 1313.0.0 on AWS EC2

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
HA Rancher and AWS RDS

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle

**Steps to Reproduce:**
Going from "non-trivial" (HTML, bullet lists, links, etc.) descriptions to any other:
1. Go to Catalog
2. View Details of any entry with non-trivial description, such as "Kubernetes"
3. In the "Catalog:" dropdown, top left, choose any other entry
4. Description does not change

Going from "trivial" (one line, plain text) descriptions to "non-trivial":
1. Go to Catalog
2. View Details of any entry with a trivial description, such as "Rancher Network Policy Manager"
3. In the "Catalog:" dropdown, top left, choose any entry with a non-trivial description, such as "Kubernetes"
4. Description is blank

**Results:** 
Entry description always continues to display the same text until you back out to the catalog.

If an entry with a trivial one line description is chosen, such as "Rancher Network Policy Manager," then the description will change as expected when switching to any other entry with a trivial description. If you switch to an entry with a non-trivial description, its description will be blank.

**Comment by tfiduccia** [comment] 2017-02-23 18:19
This is a duplicate of #6470.  Closing in favor of previous bug.

**Closed by tfiduccia** 2017-02-23 18:19 UTC
