### ISSUE TITLE
[BUG] AWS EKS Deployed (but waiting) Cluster can cause a crash/panic loop

### ISSUE THREAD

**Issue by BenB196** [rancher/rancher#38715] opened 2022-08-24 23:09 UTC
**Rancher Server Setup**
- Rancher version: `2.6.7`
- Installation option (Docker install/Helm Chart): `Helm`
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): `RKE1` (1.23.7 & 1.23.8 tested)
- Proxy/Cert Details: Default helm ingress

**Information about the Cluster**
- Kubernetes version: `1.22`
- Cluster Type (Local/Downstream): `Downstream`
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider): `Amazon EKS Hosted`

**User Information**
- What is the role of the user logged in? (Admin/Cluster Owner/Cluster Member/Project Owner/Project Member/Custom)
  - If custom, define the set of permissions: `Admin`

**Describe the bug**

When an AWS EKS cluster is provisioned through Rancher, but hangs on `Waiting for API` (for one reason or another). After a while Rancher pods will start to crash/panic loop from an invalid memory error

**To Reproduce**

1. Have Rancher setup
2. Create a new Amazon EKS cluster
3. Have something that prevents Rancher from validating that the new EKS cluster API is ready
   - In my case, there was a firewall blocking 6443/tcp between the EKS cluster and Rancher
4. Wait a while (I don't know exactly when the issue started, but I know the issue didn't start immediately)

**Result**

Rancher pods will eventually enter into a crash/panic loop (see below for the panic)

**Expected Result**

I would expect Rancher to gracefully handle prolonged Waiting for API cluster provisioning.

**Screenshots**

**Additional context**

Panic
```
E0824 22:38:28.276560      33 runtime.go:79] Observed a panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer dereference)
goroutine 3771 [running]:
k8s.io/apimachinery/pkg/util/runtime.logPanic({0x3a140a0, 0x73f5a70})
        /go/pkg/mod/k8s.io/apimachinery@v0.24.2/pkg/util/runtime/runtime.go:75 +0x85
k8s.io/apimachinery/pkg/util/runtime.HandleCrash({0x0, 0x0, 0xc00714d6e0})
        /go/pkg/mod/k8s.io/apimachinery@v0.24.2/pkg/util/runtime/runtime.go:49 +0x75
panic({0x3a140a0, 0x73f5a70})
        /usr/lib64/go/1.17/src/runtime/panic.go:1038 +0x215
github.com/rancher/rancher/pkg/controllers/management/eks.(*eksOperatorController).onClusterChange(0xc0013b52b0, {0xc00d393b68, 0x40b274}, 0x409f100)
        /go/src/github.com/rancher/rancher/pkg/controllers/management/eks/eks_cluster_handler.go:259 +0x1989
github.com/rancher/rancher/pkg/generated/controllers/management.cattle.io/v3.FromClusterHandlerToHandler.func1({0xc004e42526, 0x6c5e82a14d}, {0x4b36a40, 0xc00d395200})
        /go/src/github.com/rancher/rancher/pkg/generated/controllers/management.cattle.io/v3/cluster.go:105 +0x44
github.com/rancher/lasso/pkg/controller.SharedControllerHandlerFunc.OnChange(0xc00d395200, {0xc004e42526, 0x42a3064}, {0x4b36a40, 0xc00d395200})
        /go/pkg/mod/github.com/rancher/lasso@v0.0.0-20220627205005-00d9c8e9dda6/pkg/controller/sharedcontroller.go:29 +0x38
github.com/rancher/lasso/pkg/controller.(*SharedHandler).OnChange(0xc000925590, {0xc004e42526, 0x7}, {0x4b36a40, 0xc00276d268})
        /go/pkg/mod/github.com/rancher/lasso@v0.0.0-20220627205005-00d9c8e9dda6/pkg/controller/sharedhandler.go:75 +0x23f
github.com/rancher/lasso/pkg/controller.(*controller).syncHandler(0xc000cf16b0, {0xc004e42526, 0x7})
        /go/pkg/mod/github.com/rancher/lasso@v0.0.0-20220627205005-00d9c8e9dda6/pkg/controller/controller.go:233 +0x93
github.com/rancher/lasso/pkg/controller.(*controller).processSingleItem(0xc000cf16b0, {0x37c5e40, 0xc00714d6e0})
        /go/pkg/mod/github.com/rancher/lasso@v0.0.0-20220627205005-00d9c8e9dda6/pkg/controller/controller.go:214 +0x10e
github.com/rancher/lasso/pkg/controller.(*controller).processNextWorkItem(0xc000cf16b0)
        /go/pkg/mod/github.com/rancher/lasso@v0.0.0-20220627205005-00d9c8e9dda6/pkg/controller/controller.go:191 +0x46
github.com/rancher/lasso/pkg/controller.(*controller).runWorker(...)
        /go/pkg/mod/github.com/rancher/lasso@v0.0.0-20220627205005-00d9c8e9dda6/pkg/controller/controller.go:180
k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0x7fe604519400)
        /go/pkg/mod/k8s.io/apimachinery@v0.24.2/pkg/util/wait/wait.go:155 +0x67
k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0x3739580, {0x4b09600, 0xc002553ec0}, 0x1, 0xc001a6f6e0)
        /go/pkg/mod/k8s.io/apimachinery@v0.24.2/pkg/util/wait/wait.go:156 +0xb6
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0x0, 0x3b9aca00, 0x0, 0x1, 0x440ba5)
        /go/pkg/mod/k8s.io/apimachinery@v0.24.2/pkg/util/wait/wait.go:133 +0x89
k8s.io/apimachinery/pkg/util/wait.Until(0x0, 0xc001a6f6e0, 0x0)
        /go/pkg/mod/k8s.io/apimachinery@v0.24.2/pkg/util/wait/wait.go:90 +0x25
created by github.com/rancher/lasso/pkg/controller.(*controller).run
        /go/pkg/mod/github.com/rancher/lasso@v0.0.0-20220627205005-00d9c8e9dda6/pkg/controller/controller.go:148 +0x2c6
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
        panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x2ee2789]

goroutine 3771 [running]:
k8s.io/apimachinery/pkg/util/runtime.HandleCrash({0x0, 0x0, 0xc00714d6e0})
        /go/pkg/mod/k8s.io/apimachinery@v0.24.2/pkg/util/runtime/runtime.go:56 +0xd8
panic({0x3a140a0, 0x73f5a70})
        /usr/lib64/go/1.17/src/runtime/panic.go:1038 +0x215
github.com/rancher/rancher/pkg/controllers/management/eks.(*eksOperatorController).onClusterChange(0xc0013b52b0, {0xc00d393b68, 0x40b274}, 0x409f100)
        /go/src/github.com/rancher/rancher/pkg/controllers/management/eks/eks_cluster_handler.go:259 +0x1989
github.com/rancher/rancher/pkg/generated/controllers/management.cattle.io/v3.FromClusterHandlerToHandler.func1({0xc004e42526, 0x6c5e82a14d}, {0x4b36a40, 0xc00d395200})
        /go/src/github.com/rancher/rancher/pkg/generated/controllers/management.cattle.io/v3/cluster.go:105 +0x44
github.com/rancher/lasso/pkg/controller.SharedControllerHandlerFunc.OnChange(0xc00d395200, {0xc004e42526, 0x42a3064}, {0x4b36a40, 0xc00d395200})
        /go/pkg/mod/github.com/rancher/lasso@v0.0.0-20220627205005-00d9c8e9dda6/pkg/controller/sharedcontroller.go:29 +0x38
github.com/rancher/lasso/pkg/controller.(*SharedHandler).OnChange(0xc000925590, {0xc004e42526, 0x7}, {0x4b36a40, 0xc00276d268})
        /go/pkg/mod/github.com/rancher/lasso@v0.0.0-20220627205005-00d9c8e9dda6/pkg/controller/sharedhandler.go:75 +0x23f
github.com/rancher/lasso/pkg/controller.(*controller).syncHandler(0xc000cf16b0, {0xc004e42526, 0x7})
        /go/pkg/mod/github.com/rancher/lasso@v0.0.0-20220627205005-00d9c8e9dda6/pkg/controller/controller.go:233 +0x93
github.com/rancher/lasso/pkg/controller.(*controller).processSingleItem(0xc000cf16b0, {0x37c5e40, 0xc00714d6e0})
        /go/pkg/mod/github.com/rancher/lasso@v0.0.0-20220627205005-00d9c8e9dda6/pkg/controller/controller.go:214 +0x10e
github.com/rancher/lasso/pkg/controller.(*controller).processNextWorkItem(0xc000cf16b0)
        /go/pkg/mod/github.com/rancher/lasso@v0.0.0-20220627205005-00d9c8e9dda6/pkg/controller/controller.go:191 +0x46
github.com/rancher/lasso/pkg/controller.(*controller).runWorker(...)
        /go/pkg/mod/github.com/rancher/lasso@v0.0.0-20220627205005-00d9c8e9dda6/pkg/controller/controller.go:180
k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0x7fe604519400)
        /go/pkg/mod/k8s.io/apimachinery@v0.24.2/pkg/util/wait/wait.go:155 +0x67
k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0x3739580, {0x4b09600, 0xc002553ec0}, 0x1, 0xc001a6f6e0)
        /go/pkg/mod/k8s.io/apimachinery@v0.24.2/pkg/util/wait/wait.go:156 +0xb6
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0x0, 0x3b9aca00, 0x0, 0x1, 0x440ba5)
        /go/pkg/mod/k8s.io/apimachinery@v0.24.2/pkg/util/wait/wait.go:133 +0x89
k8s.io/apimachinery/pkg/util/wait.Until(0x0, 0xc001a6f6e0, 0x0)
        /go/pkg/mod/k8s.io/apimachinery@v0.24.2/pkg/util/wait/wait.go:90 +0x25
created by github.com/rancher/lasso/pkg/controller.(*controller).run
        /go/pkg/mod/github.com/rancher/lasso@v0.0.0-20220627205005-00d9c8e9dda6/pkg/controller/controller.go:148 +0x2c6
```

**Comment by jakefhyde** [comment] 2022-08-30 19:43
### Root cause

Private EKS and GKE clusters would fail to create the service account token, creating an empty secret. Afterwards we would try to reference that secrets name, which would fail.

### What was fixed, or what changes have occurred

Merged the same fix that was applied to private AKS clusters. (https://github.com/rancher/rancher/pull/38221)

### Areas or cases that should be tested

Private GKE and EKS hosted cluster provisioning.
 
### What areas could experience regressions?

N/A

### Are the repro steps accurate/minimal?
:heavy_check_mark:

**Comment by jakefhyde** [comment] 2022-09-07 20:19
For affected eks and gke clusters (as well as AKS clusters pre v2.6.8), the following gist can be run in order to fix private clusters that are crashing. **THIS IS NOT A GUARANTEE THAT THE AFFECTED CLUSTERS WILL WORK AFTERWARDS.** This just short-circuits the following section: 
https://github.com/rancher/rancher/blob/08f844a6bfad590004d4804f22c9a889233d1a9b/pkg/controllers/management/eks/eks_cluster_handler.go#L247-L266 which will crash if the service account token could not be generated with the public API. Rancher and the downstream clusters have to be able to communicate with one another, for more information, read the following: https://docs.aws.amazon.com/eks/latest/userguide/cluster-endpoint.html

**Comment by sowmyav27** [comment] 2022-09-08 19:07
**On 2.6.8**

- Deployed Rancher docker install on a Linode instance
- Deployed an EKS private cluster
- Rancher restarts continuously.
- Rancher logs show:
```
E0908 19:04:46.608424      45 runtime.go:79] Observed a panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer dereference)
goroutine 1982 [running]:
k8s.io/apimachinery/pkg/util/runtime.logPanic({0x3a140a0, 0x73f5a70})
	/go/pkg/mod/k8s.io/apimachinery@v0.24.2/pkg/util/runtime/runtime.go:75 +0x85
k8s.io/apimachinery/pkg/util/runtime.HandleCrash({0x0, 0x0, 0xc002420d30})
	/go/pkg/mod/k8s.io/apimachinery@v0.24.2/pkg/util/runtime/runtime.go:49 +0x75
panic({0x3a140a0, 0x73f5a70})
	/usr/lib64/go/1.17/src/runtime/panic.go:1038 +0x215
github.com/rancher/rancher/pkg/controllers/management/eks.(*eksOperatorController).onClusterChange(0xc003ab0b60, {0xc006febb68, 0x40b274}, 0x409f100)
	/go/src/github.com/rancher/rancher/pkg/controllers/management/eks/eks_cluster_handler.go:259 +0x1989
github.com/rancher/rancher/pkg/generated/controllers/management.cattle.io/v3.FromClusterHandlerToHandler.func1({0xc002055866, 0x85ad2a747d830}, {0x4b36a40, 0xc007296d00})
	/go/src/github.com/rancher/rancher/pkg/generated/controllers/management.cattle.io/v3/cluster.go:105 +0x44
github.com/rancher/lasso/pkg/controller.SharedControllerHandlerFunc.OnChange(0xc007296d00, {0xc002055866, 0x42a3064}, {0x4b36a40, 0xc007296d00})
	/go/pkg/mod/github.com/rancher/lasso@v0.0.0-20220627205005-00d9c8e9dda6/pkg/controller/sharedcontroller.go:29 +0x38
github.com/rancher/lasso/pkg/controller.(*SharedHandler).OnChange(0xc0008e2af0, {0xc002055866, 0x7}, {0x4b36a40, 0xc0010e9400})
	/go/pkg/mod/github.com/rancher/lasso@v0.0.0-20220627205005-00d9c8e9dda6/pkg/controller/sharedhandler.go:75 +0x23f
github.com/rancher/lasso/pkg/controller.(*controller).syncHandler(0xc00067c6e0, {0xc002055866, 0x7})
	/go/pkg/mod/github.com/rancher/lasso@v0.0.0-20220627205005-00d9c8e9dda6/pkg/controller/controller.go:233 +0x93
github.com/rancher/lasso/pkg/controller.(*controller).processSingleItem(0xc00067c6e0, {0x37c5e40, 0xc002420d30})
	/go/pkg/mod/github.com/rancher/lasso@v0.0.0-20220627205005-00d9c8e9dda6/pkg/controller/controller.go:214 +0x10e
github.com/rancher/lasso/pkg/controller.(*controller).processNextWorkItem(0xc00067c6e0)
	/go/pkg/mod/github.com/rancher/lasso@v0.0.0-20220627205005-00d9c8e9dda6/pkg/controller/controller.go:191 +0x46
github.com/rancher/lasso/pkg/controller.(*controller).runWorker(...)
	/go/pkg/mod/github.com/rancher/lasso@v0.0.0-20220627205005-00d9c8e9dda6/pkg/controller/controller.go:180
k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0x7faa322a1b70)
	/go/pkg/mod/k8s.io/apimachinery@v0.24.2/pkg/util/wait/wait.go:155 +0x67
k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0x56b60, {0x4b09600, 0xc0012dac90}, 0x1, 0xc000fc6e40)
	/go/pkg/mod/k8s.io/apimachinery@v0.24.2/pkg/util/wait/wait.go:156 +0xb6
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc00365372f, 0x3b9aca00, 0x0, 0x6, 0x6)
	/go/pkg/mod/k8s.io/apimachinery@v0.24.2/pkg/util/wait/wait.go:133 +0x89
k8s.io/apimachinery/pkg/util/wait.Until(0x0, 0x4, 0xc001c1b200)
	/go/pkg/mod/k8s.io/apimachinery@v0.24.2/pkg/util/wait/wait.go:90 +0x25
created by github.com/rancher/lasso/pkg/controller.(*controller).run
	/go/pkg/mod/github.com/rancher/lasso@v0.0.0-20220627205005-00d9c8e9dda6/pkg/controller/controller.go:148 +0x2c6
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x2ee2789]

goroutine 1982 [running]:
k8s.io/apimachinery/pkg/util/runtime.HandleCrash({0x0, 0x0, 0xc002420d30})
	/go/pkg/mod/k8s.io/apimachinery@v0.24.2/pkg/util/runtime/runtime.go:56 +0xd8
panic({0x3a140a0, 0x73f5a70})
	/usr/lib64/go/1.17/src/runtime/panic.go:1038 +0x215
github.com/rancher/rancher/pkg/controllers/management/eks.(*eksOperatorController).onClusterChange(0xc003ab0b60, {0xc006febb68, 0x40b274}, 0x409f100)
	/go/src/github.com/rancher/rancher/pkg/controllers/management/eks/eks_cluster_handler.go:259 +0x1989
github.com/rancher/rancher/pkg/generated/controllers/management.cattle.io/v3.FromClusterHandlerToHandler.func1({0xc002055866, 0x85ad2a747d830}, {0x4b36a40, 0xc007296d00})
	/go/src/github.com/rancher/rancher/pkg/generated/controllers/management.cattle.io/v3/cluster.go:105 +0x44
github.com/rancher/lasso/pkg/controller.SharedControllerHandlerFunc.OnChange(0xc007296d00, {0xc002055866, 0x42a3064}, {0x4b36a40, 0xc007296d00})
	/go/pkg/mod/github.com/rancher/lasso@v0.0.0-20220627205005-00d9c8e9dda6/pkg/controller/sharedcontroller.go:29 +0x38
github.com/rancher/lasso/pkg/controller.(*SharedHandler).OnChange(0xc0008e2af0, {0xc002055866, 0x7}, {0x4b36a40, 0xc0010e9400})
	/go/pkg/mod/github.com/rancher/lasso@v0.0.0-20220627205005-00d9c8e9dda6/pkg/controller/sharedhandler.go:75 +0x23f
github.com/rancher/lasso/pkg/controller.(*controller).syncHandler(0xc00067c6e0, {0xc002055866, 0x7})
	/go/pkg/mod/github.com/rancher/lasso@v0.0.0-20220627205005-00d9c8e9dda6/pkg/controller/controller.go:233 +0x93
github.com/rancher/lasso/pkg/controller.(*controller).processSingleItem(0xc00067c6e0, {0x37c5e40, 0xc002420d30})
	/go/pkg/mod/github.com/rancher/lasso@v0.0.0-20220627205005-00d9c8e9dda6/pkg/controller/controller.go:214 +0x10e
github.com/rancher/lasso/pkg/controller.(*controller).processNextWorkItem(0xc00067c6e0)
	/go/pkg/mod/github.com/rancher/lasso@v0.0.0-20220627205005-00d9c8e9dda6/pkg/controller/controller.go:191 +0x46
github.com/rancher/lasso/pkg/controller.(*controller).runWorker(...)
	/go/pkg/mod/github.com/rancher/lasso@v0.0.0-20220627205005-00d9c8e9dda6/pkg/controller/controller.go:180
k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0x7faa322a1b70)
	/go/pkg/mod/k8s.io/apimachinery@v0.24.2/pkg/util/wait/wait.go:155 +0x67
k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0x56b60, {0x4b09600, 0xc0012dac90}, 0x1, 0xc000fc6e40)
	/go/pkg/mod/k8s.io/apimachinery@v0.24.2/pkg/util/wait/wait.go:156 +0xb6
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc00365372f, 0x3b9aca00, 0x0, 0x6, 0x6)
	/go/pkg/mod/k8s.io/apimachinery@v0.24.2/pkg/util/wait/wait.go:133 +0x89
k8s.io/apimachinery/pkg/util/wait.Until(0x0, 0x4, 0xc001c1b200)
	/go/pkg/mod/k8s.io/apimachinery@v0.24.2/pkg/util/wait/wait.go:90 +0x25
created by github.com/rancher/lasso/pkg/controller.(*controller).run
	/go/pkg/mod/github.com/rancher/lasso@v0.0.0-20220627205005-00d9c8e9dda6/pkg/controller/controller.go:148 +0x2c6
INFO: Running k3s server --cluster-init --cluster-reset
2022/09/08 19:05:01 [INFO] Rancher version v2.6.8 (f650ce839) is starting
```

**Comment by thaneunsoo** [comment] 2022-09-08 20:07
**On 2.6.8**

- Deployed Rancher install on AWS instance
- Deployed GKE private cluster
- Rancher shows the crashloop
![image.png](https://zube.io/files/rancher/9047de0718fca31a0e54680a732d24eb-image.png)

**Comment by thaneunsoo** [comment] 2022-09-08 20:43
### Test Environment: ###
Rancher version: v2.6-head
Rancher cluster type: HA
Docker version: 20.10

Downstream cluster type: EKS and GKE private

----------

### Testing: ###

Tested this issue with the following steps:
EKS
1. Deployed Rancher docker install on a Linode instance
2. Deployed an EKS private cluster

GKE
1. Deployed Rancher install on AWS instance
2. Deployed GKE private cluster
3. Create VPC Network
4. Create Cloud NAT Gateway
5. Create Private GKE Cluster with Master IPv4 CIDR Block set to 172.16.0.0/28

Details for testing are listed [here](https://confluence.suse.com/display/EN/GKE+Private+Cluster+Scenarios)

**Results** - Pass
Private EKS Cluster provisioning and Private GKE Cluster provisioning are successful without the crash/panic loops

**Closed** 2022-09-09 15:36 UTC
Labels: kind/bug, area/eks, [zube]: QA Working, QA/S, feature/kev2, team/area2, v2.6.9
