### ISSUE TITLE
CoreDNS add-on config changes were lost after downstream RKE Upgrade

### ISSUE THREAD

**Issue by annablender** [rancher/rancher#36985] opened 2022-03-21 20:40 UTC
**Rancher Server Setup**
- Rancher version: 2.6.3
- Installation option (Docker install/Helm Chart): 
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc):
- Proxy/Cert Details:

**Information about the Cluster**
- Kubernetes version: v1.21.8
- Cluster Type (Local/Downstream): downstream
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider): RKE1 cluster kubernetes v1.19.4, upgraded to v1.21.8

**Describe the bug**

Customer deployed an RKE1 downstream cluster with kubernetes v1.19.4. They made changes to the CoreDNS add-on config, then upgraded the kubernetes version of their downstream cluster to v1.21.8. Their CoreDNS config changes were lost after the downstream upgrade.

**To Reproduce**
 

- Install Rancher version v2.6.3
- Deploy downstream cluster with k8s version v1.19.14-rancher1-1
- Change CoreDNS forward plugin policy using below KB  https://www.suse.com/support/kb/doc/?id=000020186
- Verify the modification in configmap 
- kubectl get cm -n kube-system coredns -o yaml
- After upgrading the downstream cluster to 1.21.8, the changes applied to CoreDNS add-ons were lost , but the same config is visible in cluster’s YAML spec.

**Result**

CoreDNS add-on config changed back to default, but the cluster YAMl spec stayed as it is.

**Expected Result**

CoreDNS add-on config should be consistent with cluster's YAML spec.

SURE-4227

**Comment by snasovich** [comment] 2022-03-25 17:24
@samkulkarni20 , per @kinarashah this could be a good issue to get more experience with KDM templates. Could you have someone on your team start looking into it if you have capacity?

**Comment by snasovich** [comment] 2022-04-14 16:30
@samkulkarni20 / @rayandas , this got closed automatically because of "fixes" word in PR. We want to avoid this as we want the issue to go to testing. Also, we still require 2 PR reviews to merge so should have someone else take a look. I've taken a peek and have one comment. Could you please take a look? https://github.com/rancher/rke/pull/2900#discussion_r850613706

**Comment by vivek-infracloud** [comment] 2022-04-15 11:40
### Validated the issue on rancher v2.6.5-rc1.

**Validation steps followed -**
- Install Rancher version v2.6.5-rc1
- Deployed downstream cluster with k8s version v1.19.16-rancher1-4
- Changed CoreDNS forward plugin policy using below KB  https://www.suse.com/support/kb/doc/?id=000020186
- Verified the modification in configmap with command - `kubectl get cm -n kube-system coredns -o yaml`
- After upgrading the downstream cluster to 1.21.11, the CoreDNS add-ons remained same.

**CoreDNS add-on config is consistent with cluster's YAML specification.**

**Issue is not active anymore.**

**Comment by snasovich** [comment] 2022-04-15 14:58
@vivek-infracloud , we're still discussing the fix per comments on the linked PR (that should have not been merged yet). We may need to revalidate it - if the solution is updated.

**Comment by rayandas** [comment] 2022-04-21 05:51
Validation steps:
- Install Rancher version v2.6.5-rc1
- Deploy a downstream cluster with k8s version v1.19.16-rancher1-4
- Change CoreDNS forward plugin policy using below KB https://www.suse.com/support/kb/doc/?id=000020186
- Verify the modification in configmap with command - `kubectl get cm -n kube-system coredns -o yaml`
- Upgrade the cluster to `v1.21.11`
- CoreDNS add-on config should be consistent with cluster's YAML spec. Check using `kubectl get cm -n kube-system coredns -o yaml`

**Comment by rishabhmsra** [comment] 2022-04-21 11:46
**Validated on rancher v2.6.5-rc1**

**Steps followed :**
- Provisioned a k8s `v1.19.16-rancher1-4` custom cluster(1-cp, 1-etcd, 1-w)
- Changed CoreDNS forward plugin policy using KB https://www.suse.com/support/kb/doc/?id=000020186.
- Verified the modification in configmap with command - `kubectl get cm -n kube-system coredns -o yaml`
- Upgraded the cluster to v1.20.11-rancher1-1
- The the CoreDNS add-ons remained same after the upgrade and consistent with cluster's YAML spec.

However noticed one **issue** after upgrading the cluster to v1.21 the new CoreDNS pods with image `rancher/mirrored-coredns-coredns:1.8.4` went into **Pending** state with error : 

![pod-pending1](https://user-images.githubusercontent.com/36376154/164451254-b1521736-72cd-4286-861e-d554a8ea628a.png)

On comparing the codedns pod yaml for versions v1.7.0 and 1.8.4, found that there are differences in the `podAntiAffinity` rules.

**Comment by rishabhmsra** [comment] 2022-04-22 13:18
I also validated this on rancher v2.6.4 and after upgrading the cluster from `v1.19.16-rancher1-4` to `v1.21.10-rancher1-1`, seeing same error with coredns pods as mentioned above.

**Comment by rishabhmsra** [comment] 2022-04-25 10:56
From above observations the original issue is resolved. CoreDNS add-ons remained same and consistent with cluster YAML spec after the cluster upgrade.

However, getting a different issue where coredns pod is not getting scheduled after the cluster upgrade because of the error mentioned [here](https://github.com/rancher/rancher/issues/36985#issuecomment-1105102730). On rancher v2.6.4 as well, same behaviour is observed which indicates that this is not a regression due to the original issue fix, hence closing this and creating a new issue for coredns pod scheduling https://github.com/rancher/rancher/issues/37461

**Comment by snasovich** [comment] 2022-04-27 17:26
Reopened this issue as https://github.com/rancher/rke/pull/2915 reverts the changes made for April 2022 KDM patches milestone. Setting milestone to 2.6.5 to attempt to address it there.

**Comment by snasovich** [comment] 2022-05-18 16:58
@kinarashah , did these changes make their way into 2.6.5 or do we need to "revert the revert" still?

**Comment by rayandas** [comment] 2022-05-20 04:46
I think we need to revert the revert. @kinarashah correct me if i’m wrong

**Comment by snasovich** [comment] 2022-05-26 02:14
@kinarashah , ping.

**Comment by snasovich** [comment] 2022-07-06 18:58
Sending it back to testing as the linked PR is merged. It was already tested before prior to changes rolled back, but now with them merged in again we want this retested.
@rishabhmsra FYI

**Comment by rishabhmsra** [comment] 2022-07-13 13:23
validated on rancher v2.6-head(2c21373)

Steps followed:
- Provisioned a k8s `v1.19.16-rancher1-6`, downstream custom cluster(1-cp, 1-etcd, 1-w)
- Changed CoreDNS forward plugin policy using KB https://www.suse.com/support/kb/doc/?id=000020186.
- Verified the modification in configmap with command - `kubectl get cm -n kube-system coredns -o yaml`
- Upgraded the cluster to v1.21.14-rancher1-1
- The CoreDNS add-ons remained same after the cluster upgrade and consistent with cluster's YAML spec.

Result:
- CoreDNS add-ons remained same after cluster upgrade, also the CoreDNS schedule [issue](https://github.com/rancher/rancher/issues/37461) is tracked in a separate ticket, hence closing this one.

**Closed by rishabhmsra** 2022-07-13 13:23 UTC
Labels: internal, [zube]: QA Working, feature/provisioned-rke1, team/area2, team/infracloud
