### ISSUE TITLE
Adding controlplane or etcd node with --label resets labels on other nodes

### ISSUE THREAD

**Issue by dnoland1** [rancher/rancher#25144] opened 2020-01-29 07:01 UTC
**What kind of request is this (question/bug/enhancement/feature request):**
bug

**Steps to reproduce (least amount of steps as possible):**
1. Provision a three node custer cluster (k8s v1.15.9), 1 worker, 1 controlplane, and 1 etcd node. For each node use `--label color=red` in the docker run command to label each node with the color red.
2. In the UI, edit each node of the three nodes and change the color label to blue.
3. Add a fourth controlplane node to the cluster and use `--label color=red`.

**Result:**
After adding the fourth controlplane node, the original controlplane node and etcd node labels are changed back to their original labels of color=red. This is not expected behavior, the labels should not have changed.

**Other details that may be helpful:**
The label on the worker node does not change. Adding more workers does not reset labels. Adding more etcd or controlplane nodes does reset labels on both etcd and controlplane nodes. Deletion of an etcd or controlplane node also resets labels of the remaining etcd and controlplane nodes.

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI):
v2.3.5

- Installation option (single install/HA):
single install

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported):
custom
- Machine type (cloud/VM/metal) and specifications (CPU/memory):
t3a.medium in aws
- Kubernetes version (use `kubectl version`):

```
> kubectl version
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.1", GitCommit:"d647ddbd755faf07169599a625faf302ffc34458", GitTreeState:"clean", BuildDate:"2019-10-02T17:01:15Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.9", GitCommit:"2e808b7cb054ee242b68e62455323aa783991f03", GitTreeState:"clean", BuildDate:"2020-01-18T23:24:23Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}
```

- Docker version (use `docker version`):

```
$ docker version
Client: Docker Engine - Community
 Version:           19.03.5
 API version:       1.40
 Go version:        go1.12.12
 Git commit:        633a0ea838
 Built:             Wed Nov 13 07:22:05 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.5
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.12
  Git commit:       633a0ea838
  Built:            Wed Nov 13 07:28:45 2019
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.2.10
  GitCommit:        b34a5c8af56e510852c35414db4c1f4fa6172339
 runc:
  Version:          1.0.0-rc8+dev
  GitCommit:        3e425f80a8c931f88e6d94a8c831b9d5aa481657
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

**Comment by dramich** [comment] 2020-02-12 00:31
This is working as intended. The label being added through the docker command is saved as part of the plan for the node which is then applied by RKE and used as the source of truth for any additional updates. Editing a label that was set on the docker call will eventually be overwritten on a normal sync for the node even without adding a new node to trigger this. The logic for controlplane/etcd vs worker nodes are also slightly different as seen by the fact the worker does not get updated.

**Comment by dramich** [comment] 2020-02-12 18:55
This is technically a regression based on https://github.com/rancher/rancher/issues/15709. The edit use case should work but delete is still not supported.

**Comment by retornam** [comment] 2020-02-25 00:07
@StrongMonkey We ran into something similar to this issue last week, new nodes are started by 
passing the  label `--label example.com/node-pool=gpu` but then end up with the label `--label example.com/node-pool=default` .  Logs on the node show that correct label is passed on node startup.

**Comment by sowmyav27** [comment] 2020-03-03 22:09
**Reproduced the issue on v 2.3.5**

**Steps:**

- Deploy a three node cluster cluster (k8s v1.15.9), 1 worker, 1 controlplane, and 1 etcd node. For each node use --label test=value in the docker run command to label each node with the color red.
- In the UI, edit each node of the three nodes and change the test label to value2.
- Add a fourth controlplane node to the cluster and use --label test=value.
- After adding the fourth controlplane node, the original controlplane node and etcd node labels are changed back to their original labels of test=value.

verified on master-head - commit id: `3623201ad` issue still exists

**Steps:**
- Deploy a three node cluster cluster (k8s v1.15.9), 1 worker, 1 controlplane, and 1 etcd node. For each node use --label test=value in the docker run command to label each node with the color red.
- In the UI, edit each node of the three nodes and change the test label to value2.
- Add a fourth controlplane node to the cluster and use --label test=value.
- After adding the fourth controlplane node, the original controlplane node and etcd node labels are changed back to their original labels of test=value.

**Comment by sowmyav27** [comment] 2020-03-05 18:47
**Verified on master-head commit id: `f6872eb2c`**

- Deploy a three node cluster cluster (k8s v1.15.9), 1 worker, 1 controlplane, and 1 etcd node. For each node use --label `color=red` in the docker run command to label each node with the color red.
- In the UI, edit each node of the three nodes and change the test `color=blue`
- During edit of labels on the node
- Editing labels that are part of the original plan on the etcd and control plane nodes - causes a reconcile --> Cluster goes into Updating state --> reconcile happens and cluster comes back to Active state
- Editing labels that are part of the original plan on the worker node, does NOT cause a reconcile, but the cluster state does change to Updating for few seconds before it comes back to Active.
- Add a fourth controlplane node to the cluster and use --label `color=red`
- After adding the fourth controlplane node, the original controlplane node and etcd node labels do not change.
- The newly added control plane node has label - `color=red`

- The issue mentioned here - https://github.com/rancher/rancher/issues/25144#issue-556675916 is fixed.

- But on adding a new label (not part of the original plane) on the control plane node -- A reconcile happens which is not expected. Hence reopening the issue.

**Comment by sowmyav27** [comment] 2020-03-06 22:05
**Verified on master-head - commit id: `beba5247e`**

- Deploy a three node cluster cluster (k8s v1.17), 1 worker, 1 controlplane, and 1 etcd node. For each node use --label color=red in the docker run command to label each node with the color red.
- In the UI, edit each node of the three nodes and change the test color=blue
- During edit of labels on the node

- - Editing labels that are part of the original plan on the etcd and control plane nodes - causes a reconcile --> Cluster goes into Updating state --> reconcile happens and cluster comes back to Active state
- - Editing labels that are part of the original plan on the worker node, does NOT cause a reconcile, but the cluster state does change to Updating for few seconds before it comes back to Active.

- Add a fourth controlplane node to the cluster and use --label color=red
- After adding the fourth controlplane node, the original controlplane node and etcd node labels do not change.
- The newly added control plane node has label - color=red
- The label is seen set via kubectl get nodes <node-name> -o yaml
- On adding a new label (not part of the original plane) on the control plane node/ etcd or worker nodes -- A reconcile does NOT happen

**Comment by steved** [comment] 2020-03-09 17:00
Could the fix(es) for this issue be backported to the 2.3 line?

**Comment by StrongMonkey** [comment] 2020-03-10 01:12
This is backported into 2.3. Available to test on 2.3 head

**Comment by sangeethah** [comment] 2020-03-10 03:44
@StrongMonkey Could you add the PR that was merged in  2.3 release to the issue ?

**Comment by rancher-max** [comment] 2020-03-10 19:05
#### Validated backport on v2.3-head `Rancher version 351ef07c6`

Initial State after label edit:
![image](https://user-images.githubusercontent.com/55997940/76342077-32dd6d00-62bb-11ea-9a3d-c8427d86d6a3.png)

Add cp, etcd and worker nodes (added one at a time):
![image](https://user-images.githubusercontent.com/55997940/76345368-77b7d280-62c0-11ea-947e-4230fa9188c8.png)


- Verified new labels do not reconcile. No screenshot here, but validated via server logs
- Verified deleting nodes does not update labels

**Closed by rancher-max** 2020-03-10 19:05 UTC
Labels: [zube]: To Test, internal

**Comment by Subbaraman-Sowmya** [comment] 2024-11-13 08:31
Not able to add the node using control plane context with etcd-controlplane not responding when label is given.
k label pod color=red  etcd-controlplane -n kube-system
error: all resources must be specified before label changes: etcd-controlplane
