### ISSUE TITLE
vSphere CPI/CSI options omitted when selecting `vsphere` cloud provider in Rancher 2.6.7 or newer

### ISSUE THREAD

**Issue by David-VTUK** [rancher/rancher#39462] opened 2022-09-04 09:01 UTC
**Setup**
- Rancher version: >= 2.6.7
- Browser type & version: Firefox 104.0

**Describe the bug**
vSphere CSI options are omitted when selecting the respective cloud provider in rke2 provisioning. vSphere CPI options however remain

**To Reproduce**
Create cluster -> RKE2 -> Select `vSphere` as the cloud provider > Navigate to addon config

**Result**

**Expected Result**
vSphere CPI options presented, vSphere CSI options are omitted. 

**Screenshots**
In 2.6.7/2.6.8:

![image](https://user-images.githubusercontent.com/5892615/188305043-df1b018b-cea3-457d-afa5-7a1a3ee2977d.png)

in 2.6.6

![image](https://user-images.githubusercontent.com/5892615/188305170-b0258539-cbc7-4cf8-80b6-bb25510b0613.png)

**Additional context**

In 2.6.6 the latest (non experimental) version of RKE2 is 1.22.13
In 2.6.8 the latest version of RKE2 is 1.24.4

The CSI chart has a version restriction:

https://github.com/rancher/charts/blob/36de515042fb94888c751aeedd645f6ffae6a854/index.yaml#L8784

```
  rancher-vsphere-csi:
  - annotations:
      catalog.cattle.io/certified: rancher
      catalog.cattle.io/display-name: vSphere CSI
      catalog.cattle.io/kube-version: '>= 1.20.0-0 < 1.24.0-0'
```

Even in 2.6.8, if a valid version is specified for the RKE2 version, the CSI options are not present.

The CPI chart does have a version restriction, but is higher:

https://github.com/rancher/charts/blob/36de515042fb94888c751aeedd645f6ffae6a854/index.yaml#L8576

```
  rancher-vsphere-cpi:
  - annotations:
      catalog.cattle.io/certified: rancher
      catalog.cattle.io/display-name: vSphere CPI
      catalog.cattle.io/kube-version: '>= 1.18.0-0 < 1.25.0-0'
```

What I suspect is happening:

- in 2.6.8 when an RKE2 version is created, it defaults to the latest version (1.24.4) which is outside the range of the CSI chart but not the CPI chart. However, if you were to select a different version that does fall within this range, this is not re-evaluated.

- in 2.6.6 when an RKE2 cluster is created, it defaults to the latest version (1.22.13) which is inside the range of both charts, therefore both chart values are seen 

Therefore, I believe an action needs to be performed in the UI whenever a specific k8s version is selected to re-evaluate respective addon charts for the vSphere cloud provider, assuming the version restriction is for a legitimate reason.

**Comment by Jono-SUSE-Rancher** [comment] 2022-10-31 20:19
@MKlimuszka can you work with your team and Prachi to see if we can figure out what's happening with the chart? It might be something @samkulkarni20 can look at with his team.

**Comment by mihkel** [comment] 2022-11-03 13:40
I'm adding my two cents if I may. I've noticed that somehow the display of the vsphere csi config options seem to be related to the K8S version that the Rancher server itself is running on not the version that I would like Rancher to deploy for me.

For example:
* Running Rancher 2.6.9 on K3S v1.24.6+k3s1 and trying to deploy RKE2 cluster v1.24.4+rke2r1 -- no vsphere csi config options shown
* Running Rancher 2.6.9 on K3S v1.23.13+k3s1 and deploying RKE2 cluster v1.24.4+rke2r1 -- all good, vsphere csi options present.

**Comment by snasovich** [comment] 2022-11-03 15:04
@mihkel , thank you for reporting this observation.
This actually makes sense as CSI chart is only compatible with k8s 1.20 through 1.23, not 1.24.
However, in this case it seems to be wrong it's evaluated against Rancher cluster version and not downstream cluster version. Plus the UX could definitely be better to handle case where it's not supported by selected downstream cluster version.

The other good question is why it's not filtering out on v2.6.6 or on v2.6-head versions.

This is not a resolution, just some thoughts for @rayandas @mitulshah-suse who are working on this issue.
cc: @MKlimuszka @prachidamle

**Comment by rayandas** [comment] 2022-11-07 07:47
Thanks for all the pointers. 
There's a tracking issue https://github.com/rancher/rancher/issues/38188 to update CSI chart to include all the bug fixes that happened for CSI, this includes vSphere CSI `2.6.1` (latest version) which supports K8s `1.24` So I believe this (updated CSI chart to the latest) will fix the issue vSphere CSI configs getting omitted. 
The milestone of the mentioned tracking issue  is `2023-Q1-v2.7x`. but this issue milestone is 2.7.0 and is release blocker right now. 
cc: @prachidamle @snasovich @mitulshah-suse

**Comment by snasovich** [comment] 2022-11-08 00:39
Investigated this one a little more and TLDR is that the immediate issue should indeed be fixed by https://github.com/rancher/rancher/issues/38188 and we can wait for it to be done for the next minor feature release after 2.7.0 (which is `2023-Q1-v2.7x` milestone) as this issue is not actually a regression.

Per https://github.com/rancher/rancher/issues/39462#issuecomment-1297597317 it's already established that the UI doesn't render CSI configuration form if request to `v1/catalog.cattle.io.clusterrepos/rancher-charts?link=index` doesn't return `rancher-vsphere-csi` entry.
This is an issue in itself as whether there is an appropriate version of CPI/CSI chart to be installed on the downstream cluster depends on the selected RKE2 version. I.e. it depends on if the versions of CPI/CSI charts bundled in the release supports that release.
@brandond @rancher-max , is it possible for RKE2 release to bundle versions of CPI/CSI charts that don't support it? For example, I believe this PR adds CSI 2.6.0 that is required for k8s 1.24.x, but I'm sure we've released 1.24.x versions before then. Does it mean whose versions had CSI chart bundled within them that wasn't working or it wasn't bundled at all?
I understand that once CSI base chart is updated and pulled into RKE2 it's no longer an issue for the subsequent patch releases, but for those first few releases on new minor k8s version we may not have charts ready yet.

Circling back on UI, @codyrancher , is there something that UI uses from that payload (e.g. to generate form automatically) or it's simply exists/not exists check?

Now, onto the explanation of why the issue showed up in v2.6.7 and is not reproducible on `v2.6-head`.

v2.6.7 is the first version with 1.24.x support and since that release it's the default for embedded k3s version when running Rancher as Docker container (https://github.com/rancher/rancher/blob/v2.6.7/package/Dockerfile#L45) - and that's how most testing was done. So since 2.6.7+ was generally tested on 1.24 k8s then, the issue showed up. As per https://github.com/rancher/rancher/issues/39462#issuecomment-1302132086 even 2.6.9 running on 1.23 doesn't exhibit this issue. So it's not really a regression - just the fact that CSI chart currently bundled in Rancher doesn't support k8s 1.24+.

The reason why the issue is not reproducible on `v2.6-head` (or any non-release version for that matter) is because the filtering logic used by `v1/catalog.cattle.io.clusterrepos/rancher-charts?link=index` endpoint (https://github.com/rancher/rancher/blob/08bf3fedd660c884fab1780a172593d5ad59f7cf/pkg/catalogv2/content/content.go#L200) simply short-circuits for non-release versions and returns unfiltered list. Now, I can see a rationale in not filtering based on Rancher version chart annotations, but I don't see a good reason to skip filtering based on k8s version and suggest fixing it.
@prachidamle @MKlimuszka , I believe it's something that will be for your team.

Pending the responses to some pending questions, we will repurpose this issue to fix charts filtering for non-release versions and probably open another one to properly use downstream cluster information to determine whether CSI/CPI charts are available (or assume they are as a stop-gap measure, if possible).

**Comment by slickwarren** [comment] 2022-11-17 19:28
note that on the latest (2.7.0) the behavior seems to have flipped: now the UI shows only CSI options, but no CPI options (see linked ticket above for details)

**Comment by mihkel** [comment] 2022-11-17 20:30
> note that on the latest (2.7.0) the behavior seems to have flipped: now the UI shows only CSI options, but no CPI options (see linked ticket above for details)

I've seen it also on 2.6.9 when I upgraded one rke2 cluster from 1.24.4 to 1.24.7. After the upgrade the CPI options were missing. Downgrade to 1.24.4 made them show up again.

**Comment by bluecmd** [comment] 2022-11-26 23:04
> note that on the latest (2.7.0) the behavior seems to have flipped: now the UI shows only CSI options, but no CPI options (see linked ticket above for details)

I can confirm this. I was trying out Rancher for the first time and this caused a lot of confusion. Running vSphere 8.0 with Rancher v2.7.0.

**Comment by mateuszdrab** [comment] 2022-11-27 10:33
I face similar issues when upgrade rancher and then upgrade my cluster via GUI. 
When I open the configuration page and select a supported version of RKE, this wipes my CSI/CPI settings.
This seems to be because when the current version is selected, there are no settings shown in the addon page.

Workaround for me is now to edit the yaml

**Comment by vivek-infracloud** [comment] 2022-12-20 10:56
I re-tested this behaviour on rancher v2.6.9 and v2.7.0 for RKE2 type cluster.

On rancher v2.6.9 both the CPI and CSI options are not visible.
![Screenshot from 2022-12-20 16-20-57](https://user-images.githubusercontent.com/83208989/208650619-3c282b67-dbd8-4235-80f6-0578b366a66c.png)

On rancher v2.7.0 CPI option is not visible but the CSI option is visible as mentioned [here](https://github.com/rancher/rancher/issues/39462#issuecomment-1319102711) by @slickwarren

**Comment by vivek-infracloud** [comment] 2022-12-20 11:06
### On rancher v2.6.9 for k8s cluster v1.23.14+rke2r1 only CSI configuration is visible.
![Screenshot from 2022-12-20 16-34-15](https://user-images.githubusercontent.com/83208989/208652577-9bb13925-16e9-4668-b638-1ee7827a5da3.png)

**Comment by vivek-infracloud** [comment] 2022-12-20 11:08
### On rancher v2.6.9 for k8s cluster v1.22.16+rke2r1 only CPI configuration is visible along with Calico configuration.
![Screenshot from 2022-12-20 16-34-02](https://user-images.githubusercontent.com/83208989/208652888-a709419a-c95a-48a0-adc9-233222a2eb36.png)

**Comment by vivek-infracloud** [comment] 2023-01-17 04:30
Tested the CSI/CPI cloud configuration visibility on rancher v2.7.0 while pointing KDM to Dev branch.

![Screenshot from 2023-01-17 09-56-03](https://user-images.githubusercontent.com/83208989/212809903-3675e4bc-2412-44a7-a067-fba1cd295c9d.png)

**Closed by vivek-infracloud** 2023-01-17 04:30 UTC
Labels: kind/bug, priority/0, [zube]: To Test, QA/XS, team/infracloud
