### ISSUE TITLE
[Windows] Windows Pod couldn't access Kubernetes APIs with VXLAN mode

### ISSUE THREAD

**Issue by aiwantaozi** [rancher/rancher#20968] opened 2019-06-19 04:54 UTC
Rancher server version v2.3.0-alpha4
Step to reproduce:
1. create windows cluster with one linux node and one windows node, default flannel and vxlan network configure
2. create a workload use image ```mcr.microsoft.com/powershell:nanoserver-1809``` and schedule to windows node
3. create a workload schedule to linux node
4. curl kubernetes API inside linux pod could get response
```
export TOKEN_CONTENT=$(cat /var/run/secrets/kubernetes.io/serviceaccount/token) 
export NAMESPACE=$(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace) 
export CACERT_PATH=/var/run/secrets/kubernetes.io/serviceaccount/ca.crt 
curl -v --cacert $CACERT_PATH --header "Authorization: Bearer $TOKEN_CONTENT" https://kubernetes.default.svc.cluster.local/api/v1/namespaces/$NAMESPACE/services
```
5. curl kubernetes API inside windows pod return timeout, couldn't access
```
$TOKEN_CONTENT=$(cat /var/run/secrets/kubernetes.io/serviceaccount/token) 
$NAMESPACE=$(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace)
$CACERT_PATH="/var/run/secrets/kubernetes.io/serviceaccount/ca.crt"
curl.exe -v --cacert $CACERT_PATH --header "Authorization: Bearer $TOKEN_CONTENT" --header "Connection: Keep-Alive" https://kubernetes.default.svc.cluster.local/api/v1/namespaces/$NAMESPACE/services
```
6. The overlay mode will report timeout error, but Host-gateway is fine

This will prevent windows logging daemonset to get pod info from API server.

**Comment by orangedeng** [comment] 2019-06-20 01:23
Did you try the api server cluster ip? 10.42.0.1?

**Comment by thxCode** [comment] 2019-06-23 15:28
Reproduced on Overlay mode, did more searching on the rules of VFP, and then found:
```
  MAPPING : 
      Flags : permanent non-unique-pa mac-mapping 
      Provider address: 172.31.11.172    <-- Windows host
      Customer address: 10.43.0.1
      Provider MAC address: 00-00-00-00-00-00
      Idle time: 0
      TNI: 0
      Customer MAC address: 0A-3D-D9-C9-41-42
...
LAYER : LB
    Friendly name : LB
    Flags : 0x1, Default Allow 
    Priority : 300
  ...
  GROUP : LB_OUT
      Friendly name : LB_OUT
      Priority : 100
      Direction : OUT
      Type : IPv4
        Conditions:
            <none>
      Match type : Longest prefix match on Destination IP
    ...
    RULE : 
        Friendly name : LB_5ED47_10.42.4.2_10.43.0.1_443_6443_6
        Priority : 100
        Flags : 1 terminating 
        Type : lbnat
        Conditions:
            Protocols : 6
            Destination IP : 10.43.0.1
            Destination ports : 443
        Flow TTL: 240
        Rule Data:
        Decrementing TTL
        Fixing MAC
        Modifying destination IP
        Modifying destination port
        Creating a flow pair
        Map space : 3E588020-FDD1-465B-9F84-9AC539E60FB7
        Count of DIP Ranges: 1
        DIP Range(s) : 
                { 172.31.15.129 : 6443 }  <-- Linux control plane host
        FlagsEx : 0

```

It looks like there is no difference between the rule of the normal Service.

**Comment by thxCode** [comment] 2019-06-25 04:11
Filed an issue https://github.com/kubernetes/kubernetes/issues/79359

**Comment by aiwantaozi** [comment] 2019-06-28 03:25
In host gateway mode, when reuse node, kubernetes api server's cluster ip `10.43.0.1` is unreachable. After delete that windows node from cluster, run `clean.ps1 under`  `c:/etc/rancher`, and run ```get-hnspolicylist | remove-hnspolicylist``` to clean the policy, then add back that node, the api server' cluster ip is reachable again.

**Comment by loganhz** [comment] 2019-08-28 23:34
Move it back to 2.3, I think maybe we should add it in release note. Please move it out if it doesn't matter.

**Comment by deniseschannon** [comment] 2019-08-30 16:04
@loganhz this was already on the list of what will be release noted.

**Comment by pirminjanka** [comment] 2019-11-28 15:56
+1

**Comment by loganhz** [comment] 2020-02-25 02:51
Issue has been fixed in k8s 1.18. We need to remove the UI warning  in Rancher UI if it's a k8s 1.18 cluster.

**Comment by loganhz** [comment] 2020-05-20 08:36
Verified logging in K8s 1.18. It only works in some particular Windows versions. I guess it is a Windows (OS) issue. 

`Windows Server 2019 Datacenter Version 1809 (OS Build 17763.1039)` works.
` Windows Server 2019 Datacenter Version 1809 (OS Build 17763.1217)` doesn't work.

If you are using AWS, please use `Windows_Server-2019-English-Full-ContainersLatest-2020.02.12 (ami-0c898f8cf1a4ae1f5)` instead of the current default one `Windows_Server-2019-English-Full-ContainersLatest-2020.05.13 (ami-0d8a1595447f9bb46)`.

**Comment by jiaqiluo** [comment] 2020-05-22 19:13
The fix is validated in rancher:master-3015-head 7f82086e0

1. the warning message shows when the cluster's k8s version < 1.18

<img width="1473" alt="Screen Shot 2020-05-22 at 11 21 11 AM" src="https://user-images.githubusercontent.com/6218999/82701165-7beb5f00-9c24-11ea-9223-d7205ae0bf56.png">

<img width="1423" alt="Screen Shot 2020-05-22 at 11 21 43 AM" src="https://user-images.githubusercontent.com/6218999/82701177-8279d680-9c24-11ea-8499-9016a48f8841.png">

2. the warning message does NOT show when the cluster's k8s version >= 1.18

<img width="1462" alt="Screen Shot 2020-05-22 at 11 21 26 AM" src="https://user-images.githubusercontent.com/6218999/82701227-9a515a80-9c24-11ea-8ac4-e7505d93176a.png">

<img width="1467" alt="Screen Shot 2020-05-22 at 11 21 51 AM" src="https://user-images.githubusercontent.com/6218999/82701236-9cb3b480-9c24-11ea-9a35-dccb84937446.png">

3. The cluster monitoring works on the custom cluster with the following config:
- k8s `v1.18.3-rancher1-1`
- Windows Support: `Enabled`
- Flannel Backend: `VXLAN (Overlay)`
- Windows image in EC2: `Windows_Server-2019-English-Full-ContainersLatest-2020.02.12`

**Closed** 2020-05-22 22:22 UTC
Labels: [zube]: To Test, area/windows, internal, kind/bug-qa, priority/0, team/ui
