### ISSUE TITLE
[rancher-pushprox] duplicate label in ServiceMonitor resource

### ISSUE THREAD

**Issue by aledegano** [rancher/rancher#35216] opened 2021-10-07 07:51 UTC
Rendering the template for the ServiceMonitor resource in the rancher-pushprox chart results in a duplicate key `release` in the labels, for which the values are once quoted and once not quoted.

This happens because the label `release` is first defined for all commonLabels [here](https://github.com/rancher/charts/blob/dev-v2.5/charts/rancher-pushprox/rancher-pushprox/0.1.400/templates/_helpers.tpl#L42) and then again, only for the ServiceMonitor [here](https://github.com/rancher/charts/blob/dev-v2.5/charts/rancher-pushprox/rancher-pushprox/0.1.400/templates/_helpers.tpl#L85).

Unfortunately this results in a chart that FluxV2 cannot deploy, because the HelmController of Flux relies on the Kustomize yaml parser that does not accept duplicate YAML keys as you can see in fluxcd/flux2#1522.

Do we really need the second `release` key with the quoted value? Or could it be dropped and only rely on the `release` key defined in the commonLabels?

I will be happy to open a PR once we agree on the best strategy to move forward.

**Comment by jiaqiluo** [comment] 2021-10-20 18:11
@aledegano  Thank you for reporting the issue. We will fix it in the next chart release.

**Comment by jiaqiluo** [comment] 2021-11-04 18:00
Can be tested in  `rancher-monitoring  16.6.1+up16.6.0`



### Root cause
a duplicate label in ServiceMonitor resource in the chart `rancher-pushprox` which is used as the base for multiple sub-charts of rancher-monitoring 

### What was fixed, or what changes have occurred 
remove the duplicate label 

### Areas or cases that should be tested 
the general functionality of the monitoring chart 

### What areas could experience regressions? 
the monitoring chart,
but technically the change should not introduce any regression since it just drops a duplicated label 

### Are the repro steps accurate/minimal?
n/a

**Comment by jmcsagdc** [comment] 2021-11-29 22:15
Reproduced in 0.1.400 (screenshot left-bottom)
Verified fixed in 0.1.501 (screenshot right-bottom)

To see the changes, go to the github repo (https://github.com/rancher/charts/tree/dev-v2.5/assets/rancher-pushprox) for rancher/charts and click Go to file. Search for "rancher-pushprox.tgz" and download the various .tgz tarballs. (see screenshot)

Then `helm template rancher-monitoring <tarball>` and look for the duplications or their removals (see screenshot)

![2 5fix](https://user-images.githubusercontent.com/15971368/143951046-b16de9e5-582a-4eb6-9b45-575c75f0ea72.jpg)
)

**Closed by jmcsagdc** 2021-11-29 22:15 UTC
Labels: [zube]: To Test, QA/XS, team/area3
