### ISSUE TITLE
[BUG] High CPU usage after rancher pod restart

### ISSUE THREAD

**Issue by cmurphy** [rancher/rancher#39219] opened 2022-10-03 22:57 UTC
Epic: https://github.com/rancher/rancher/issues/36702

After performing a PRTB migration as described in https://github.com/rancher/rancher/issues/39217, CPU usage for one of the rancher pods remains high for 15-20 minutes.

Messages like the following were seen in the logs:

```
2022/05/01 09:12:05 [WARNING] could not find user , will not create impersonation account on cluster
```

The impersonation issue is likely fixed by https://github.com/rancher/rancher/issues/36054. The high CPU usage may still need to be investigated.

**Comment by rmweir** [comment] 2022-11-11 21:24
This needs to be reproduced to make sure it is still an issue since the impersonation issue was resolved. If it can be reproduced then the logs are unrelated.

**Comment by moio** [comment] 2024-12-02 10:03
Recent changes in this code area, and the lack of other reports of this log line, make me believe this bug is gone now.

I am closing this, feel free to reopen if symptoms appear again.

**Closed by moio** 2024-12-02 10:03 UTC
Labels: kind/bug, area/scalability, team/scaling
