### ISSUE TITLE
[Monitoring v1] 0.2.0 cannot be installed into the local cluster in Rancher HA setup 

### ISSUE THREAD

**Issue by jiaqiluo** [rancher/rancher#30537] opened 2020-12-17 17:58 UTC
**What kind of request is this (question/bug/enhancement/feature request):**
bug 

**Steps to reproduce (least amount of steps as possible):**
- run Rancher:v2.5.4-rc6 in HA installation mode
- enable monitoring v1 chart 0.2.0 on the local cluster 

**Result:**
The UI shows monitoring is enabled, and the POST request looks legit, but there is actually nothing installed/created in the local cluster. 

**Other details that may be helpful:**
Monitoring v1 0.2.0 can be enabled on the downstream cluster on this setup.

**Comment by jiaqiluo** [comment] 2020-12-17 19:27
I see the same bug behavior on the rancher:v2.5.3 HA setup.

The monitoring chart version is `0.1.4`

**Comment by bmdepesa** [comment] 2020-12-17 20:24
v1 Monitoring can be enabled on the local cluster in v2.4.8

**Comment by aiyengar2** [comment] 2020-12-17 22:16
thanks @jiaqiluo @bmdepesa. 

The root cause seems to be that we expect the condition `AgentDeployed` to be on a local cluster in Rancher 2.4.8, but as part of the rewrite we seemed to have added in a flag that prevents the agent from being deployed onto the internal (local) cluster:

https://github.com/rancher/rancher/blob/2161018b5c1ffa489b299a039df508b43d41d5e0/pkg/controllers/management/clusterdeploy/clusterdeploy.go#L251-L254

As a result that flag is never added and monitoring is never enabled on the cluster (on either a cluster or project level) because our controllers exit out the moment we detect that condition is not met:

https://github.com/rancher/rancher/blob/2161018b5c1ffa489b299a039df508b43d41d5e0/pkg/controllers/managementagent/monitoring/clusterHandler.go#L59-L61

This doesn't impact users who created their local clusters before Rancher 2.4.8 (e.g. existing setups) since they would have had that condition met. Once the fix is in, deleting the local cluster manually via the API and restarting the Rancher server with `--add-local true` should fix the issue.

We should also check https://github.com/rancher/rancher/issues/29328 once the fix is in to master to see whether it was the same root cause.

**Comment by jiaqiluo** [comment] 2020-12-17 22:54
I can confirm that
- the bug exists on rancher:v2.5.0
- the bug does not exist on rancher:v2.4.11

**Comment by jiaqiluo** [comment] 2020-12-22 19:06
the bug fix is validated on 
- v2.5-bd660e161d52bd156eaa423f7f04ea1a22ec6f9f-head
- master-9c7419571a0bd8d82cac0139360623073ef0892e-head

Now we can enable the monitoring v1 in the local cluster when Rancher is installed in HA mode.

**Closed** 2020-12-22 19:07 UTC
Labels: [zube]: QA Working
