### ISSUE TITLE
DNS NAPTR Records

### ISSUE THREAD

**Issue by hwinkel** [rancher/rancher#3715] opened 2016-02-27 19:44 UTC
Please support full SRV NPTR support for DNS discivery

**Comment by ibuildthecloud** [comment] 2016-02-27 20:38
@vincent99

**Comment by vincent99** [comment] 2016-02-27 20:49
SRV & PTR?  Sure, PTR is already in the server but not put into the config, and SRV could be added.

Or do you really mean [NAPTR](https://en.m.wikipedia.org/wiki/NAPTR_record), which I have a hard time seeing a use case for since there is no way for you to provide custom DNS entries.

**Comment by hwinkel** [comment] 2016-02-27 23:45
@vincent99 Yes, I mean NAPTR. Was late as I added the issue, sorry for that ;)

We have at least tow use case to announce endpoints in a DNS discovery scenario:

Diameter Peer Discovery: https://tools.ietf.org/html/rfc6408
SIP peer Discovery: https://tools.ietf.org/html/rfc3263

**Comment by vincent99** [comment] 2016-02-29 19:42
Not sure if you mean internal-dns (the server containers use to resolve names) or external-dns (which manages entries in a 3rd-parth public DNS provider).

But in either case, we don't have any way for you to inject arbitrary DNS entries, nor any knowledge of magic regular expressions that you might want to put in as NAPTR entries.  So I'm not sure how this would be useful.  It seems like you probably want external-dns to create the A records for services and then your own NAPTR entries that point to them that Rancher knows nothing about.

**Comment by deniseschannon** [comment] 2016-07-13 06:13
SRV request is duplicate of #3642

**Comment by deniseschannon** [comment] 2016-07-19 16:47
@hwinkel If you have further questions, please re-open.

**Closed by deniseschannon** 2016-07-19 16:47 UTC
Labels: kind/question
