### ISSUE TITLE
Duplicate roleBindings being created

### ISSUE THREAD

**Issue by dramich** [rancher/rancher#29932] opened 2020-11-04 17:26 UTC
@mrajashree has seen this in a downstream cluster and there have been at least two internal reports of seeing this in larger setups. 

It appears to affect multiple versions of rancher but at this point there are no clear steps to repro but needs to be investigated thoroughly to determine if rancher really is creating duplicate roleBindings.

There are multiple data sets that can be used to look at this which I have. 

gz#12526
gz#13400
gz#14235
gz#13826
gz#14439
gz#14985

gz#15411

**Comment by mrajashree** [comment] 2020-11-04 17:28
yup I added a user to a cluster as owner, and the CRTB created 3 CRBs in the downstream cluster for the same user with role `cluster-owner`, and same rbac label `authz.cluster.cattle.io/rtb-owner`

**Comment by mrajashree** [comment] 2020-11-04 17:31
I added a user to a cluster as owner, and the CRTB created 3 CRBs in the downstream cluster for the same user with role `cluster-owner`, and same rbac label `authz.cluster.cattle.io/rtb-owner` . 
We use generated names for those clusterrolebindings and that could be the reason.
This does not repro always, happened only once

**Comment by Tejeev** [comment] 2021-01-26 13:32
Hi @mrajashree, we have a cluster where this seems to happen often.  Please DM me if you would like access (customer has offered)

**Comment by ryansann** [comment] 2021-02-06 01:59
I am now able to reliably reproduce this issue with the following steps:

1. Deploy Rancher HA (3 replicas)
2. Create 3-5 users
3. Deploy downstream cluster
4. Add users as members to project=default in downstream cluster
5. Add users as members to downstream cluster
6. Dump the duplicate RoleBindings and ClusterRoleBindings
7. Restart rancher pods
8. Wait for startup / initialization
9. Dump duplicates again
10. Observe that the number of duplicates has increased

Duplicates appear to be created when cache retrieval operations via the indicies in the management/auth controllers don't return results for existing bindings. I am continuing to investigate.

**Comment by deniseschannon** [comment] 2021-03-19 22:42
After the design discussions, the proper fix for this is to move to a deterministic names instead of generated names.

**Comment by anupama2501** [comment] 2021-03-19 23:32
Able to reproduce this on v2.4.15 by following @Ryan steps:
1. On HA rancher server, create a three users from global --> security --> users
2. Create a cluster and add the users as members in the cluster [from default project]
3. From the kubectl commands, get the count of the role-bindings and cluster role-bindings
4. Restart the rancher pods
5. Once the cluster is active, from the same kubectl commands, observer the count of role-bindings and cluster role-bindings increase. [increased by 10] 

On 2.5.7 HA setup followed same steps as above but couldn't reproduce the issue

On 2.5-head single node:
Followed the same steps as above and observed the value of cluster cluster role-bindings increase by 1 but no change in the count of role-bindings

**Comment by sowmyav27** [comment] 2021-04-06 23:45
We will test on 2.5-head but reopening the issue for PRs for master-head to be merged

**Comment by ryansann** [comment] 2021-04-07 17:05
@sowmyav27 I will prepare forward port PR to master, but will hold off on merging anything until after testing is completed.

**Comment by prachidamle** [comment] 2021-04-07 17:09
I already have a master PR but will merge after @ryansann merges his fixes.

**Comment by anupama2501** [comment] 2021-04-10 00:49
Verified test scenarios: 
HA Rancher with 3 nodes all roles enabled Version v2.4.15
Steps:
1. Create users 1-5 from global --> security --> users
2. Logging in as user1, created a cluster with 1 etcd, 1 cp, 3 worker and install istio
3. Logging in as user2, created a cluster with 1 etcd, 1 cp, 3 worker and created a project P1 and install monitoring
4. As admin, create a project P1 in cluster1 and add user 3 as Project owner and project member --- From the rolebindings list verify duplicates role bindings created for cluster1 - project P1
5. As admin, add user to P1 as project member and verified no duplicate role bindings created
6. Logged in as user3, create a namespace, deploy workload and ingress in project P1 on cluster from step2
7. Logged in as user4,  deploy workload and ingress in project P1 on cluster from step3 in an already available namespace in P1
8. Restart the rancher pods and verify the role bindings, multiple cluster rile bindings and role bindings are created:
get the list of all duplicates created.

  | DEBU[0001]   total duplicate role bindings: 41
  | DEBU[0001]   groups of duplicate cluster role bindings: 2
  | DEBU[0001]   total duplicate cluster role bindings: 4

9. Upgrade the rancher server to the version v2.5.8-rc2
10. Verified after upgrade the duplicates are not seen on the rancher
11. As admin, create a project P2 in the cluster from step2 and add user3 in this project as Cluster owner and cluster member.
12. Verify the role bindings and duplicate role bindings list -- No duplicates are seen on the rancher server.
13. Create a project P2 on the cluster from step3
14. Add the user5 as a project member in the project P2 and cluster owner in the same cluster
Verified no duplicates are created

**Comment by sowmyav27** [comment] 2021-04-14 02:52
reopening because of issue found - https://github.com/rancher/rancher/issues/32105

**Comment by dramich** [comment] 2021-04-14 15:19
@sowmyav27 can we move this issue forward with QA/testing and track the issue of duplicates not being cleaned up separately in the issue you linked? I don't want to conflate the two things as they are separate efforts.

**Comment by anupama2501** [comment] 2021-04-20 05:39
Verified fresh install  v2.5-d1083bc63e4ddde70ffadd09bf0133ae5862b5fe-head and master-1c3629fbe520d4cfe66b95c31cfdd2f3946f39dc-head

- Created users 1-5 and roles a
- user1 - install istio and add project p1. Add user3 to P1 as PM and PO
- user2 - install monitoring and add project P2. Add user4 to P2 as PM
- user3 and user4- deploy workload and ingress in respective projects
- Got the list of rolebindings created and verified the bindings created were deterministic name and not generated names.
- Verified no duplicates were seen in the bindings result

Verified upgrade from v2.4.15 --> master-1c3629fbe520d4cfe66b95c31cfdd2f3946f39dc-head followed the same test steps updated in the upgrade from 2.4.15 --> 2.5-head

Upgrade from 2.5.7 HA --> 2.5-d1083bc63e4ddde70ffadd09bf0133ae5862b5fe-head HA
- Created users 1-5 and roles a
- user1 - install istio and add project p1. Add user3 to P1 as PM and PO
- user2 - install monitoring and add project P2. Add user4 to P2 as PM
- user3 and user4- deploy workload and ingress in respective projects
- Restarted the rancher server and got the list of rolebindings created and the duplicates count.
- Upgrade the rancher server to the latest 2.5-d1083bc63e4ddde70ffadd09bf0133ae5862b5fe-head
- Verified no duplicates seen and created users to the new and existing projects and the users have permissions to the resources as provided.

**Closed** 2021-04-20 05:39 UTC
Labels: QA/L, [zube]: To Test, internal, priority/0, release-note
