### ISSUE TITLE
OpenLDAP: Result Code 32 "No Such Object"

### ISSUE THREAD

**Issue by JRial95** [rancher/rancher#35259] opened 2021-10-25 13:29 UTC
**Rancher Server Setup**
- Rancher version: v2.6.2
- Installation option (Docker install/Helm Chart): Helm Chart
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): RKE2 
- Proxy/Cert Details:

**Information about the Cluster**
- Kubernetes version: v1.21.5+rke2r2
- Cluster Type (Local/Downstream): Local

**Describe the bug**

When I try to configure the OpenLDAP authentication provider, I get an error: Result Code 32 "No Such Object".

**To Reproduce**

1. Go to Rancher's OpenLDAP authentication provider configuration page.

1. Fill these following fields:
   - Hostname
   - Port
   - TLS (check)
   - Certificate
   - Service Account Distinguished Name
   - Service Account Password
   - User Search Base

1. Use a valid LDAP user for the test.

1. Submit form by clicking on "Enable" button.

**Result**

Check Rancher logs using the following command:

```
kubectl -n cattle-system logs -l app=rancher -c rancher --follow
```

You should see something like this:

```
2021/10/25 09:51:20 [ERROR] API error response 401 for POST /v3/openLdapConfigs/openldap?action=testAndApply. Cause: LDAP Result Code 32 "No Such Object":
```

**Expected Result**

The OpenLDAP authentication should be enabled.

**Additional context**

By investigating the code and from my understanding, I think the problem comes from the request that is made on lines 71 to 78 in `ldap_client.go`. Unfortunately, I don't know how to solve the problem. Do you have an idea?

https://github.com/rancher/rancher/blob/64c748d1692a8887d642d57fcd720b1a71fb8160/pkg/auth/providers/ldap/ldap_client.go#L71-L78

**Comment by MbolotSuse** [comment] 2022-09-02 13:09
I'm re-opening this to track the newest PR submitted for this issue - #38736.

**Comment by MbolotSuse** [comment] 2023-03-16 20:59
## Release note

Credit goes to github user @JRial95 for developing the fix to this issue.

**Comment by MbolotSuse** [comment] 2023-03-24 20:15
After further review of the user-submitted PR, we've decided to pull this out and re-evaluate the functionality. There were some concerns raised that the current functionality could cause adverse impacts, outlined below, that made us uncertain about leaving this in. We do intend to re-evaluate Rancher's functionality in this area in the future, and hopefully present a better solution.

For background, Rancher today (in the case of most auth providers) always attempts to scope its searches to the permissions of the requesting user. It does this so that when users attempt to add new permissions to a user/group for a cluster/project, they can only see the objects that they could see outside of Rancher. This way, Rancher doesn't become an "attack vector", allowing users to effectively escalate their permissions in the auth providers.

However, we recognize that this approach does not account for typical setups (such as LDAP) where users have no permissions in the authentication provider and the service account is used as a way of tightly controlling read permissions from the application. We see these configurations as legitimate use cases, and want to better support them.

To this end, we are going to consider a more comprehensive solution to this issue. One potential solution would be to expose a field on the auth config (`search_using_service_account`, a bool) which will cause Rancher to always use the service account (and never the user) to search for users/groups. This value will default to false, to keep Rancher's current behavior for our existing consumers. This will allow users who use the more typical setups to use Rancher in the method that they desire, and implementing an explicit behavior will give us the chance to ensure that this behavior is consistent and up to our standards of quality. 

I apologize to users who have been waiting for this functionality, and hope that we can fix this issue soon.

**Comment by AndrewHoffmanQA** [comment] 2023-07-14 19:37
test plan:

perquisite 
- stand up local cluster
- configure LDAP auth and restrict the users from doing a search 

bug scope 
- when users can successfully configure and save an LDAP auth in a rancher instance this bug will be fixed.  the rest of the test plan is a targeted regression to ensure existing functionality 

Basic LDAP functionality on a LDAP setup which does not give users permission to search the LDAP setup, including:

regression areas- 
- User login
- User search (i.e. add a user to a cluster or project, make sure that you can see search results with no errors in the logs)
- Group search (same idea as user search, but with groups)
- User refresh (Add a user to a group or remove a user from a group, manually refresh the user, make sure the new permissions applied)

**Comment by Jono-SUSE-Rancher** [comment] 2023-10-04 20:57
@MbolotSuse and @martyav - Since we've release v2.7.7 and the release notes PR was merged, are we able to close this issue or does it need to be moved to a future milestone? Otherwise 2.7.7 is already tagged for community use, so I'd like to close that milestone if possible.

**Comment by martyav** [comment] 2023-10-04 21:17
@Jono-SUSE-Rancher I'm ok with closing. From my perspective, it's already in a published page and is also mentioned in the now-closed PR if we want to track it down later from GH.

**Comment by MKlimuszka** [comment] 2023-10-04 22:08
As the issue has been release noted, and it's not a simple bug fix. I am closing this issue in favor of a feature ticket.
https://github.com/rancher/rancher/issues/43064

**Closed by MKlimuszka** 2023-10-04 22:08 UTC
Labels: area/authentication, QA/S, release-note, team/area3, [zube]: Release Note, community-pr, status/release-note-added
