### ISSUE TITLE
UI not loading on Chrome

### ISSUE THREAD

**Issue by diogogmt** [rancher/rancher#4070] opened 2016-03-21 21:11 UTC
Rancher Version:
0.63.1

Docker Version:
Docker version 1.9.0, build 76d6bc9

OS: 
ubuntu wily

Steps to Reproduce: 

Load the rancher UI on Chrome

Results: 
The following errors are outputted to the browser console:

* server.rancher.local/:1 Failed to find a valid digest in the 'integrity' attribute for resource 'http://server.rancher.local:8080/assets/vendor-ef2d8c0ba9fbead853773dde7e2f49b2.js' with computed SHA-256 integrity 'fQX8Hv5RgYjrpyIvaPgXaP1hQwUmD9WQF50CyKg1qvg='. The resource has been blocked.
* ui-ff548e9ae3e48f5760c70836d3559780.js:1 Uncaught ReferenceError: define is not defined

Expected:

UI should load without error just like it is on Firefox and Safari

**Comment by vincent99** [comment] 2016-03-22 08:52
Duplicate of https://github.com/rancher/rancher/issues/3948

**Closed by vincent99** 2016-03-22 08:52 UTC
Labels: area/ui, kind/bug

**Comment by diogogmt** [comment] 2016-03-22 13:07
@vincent99 
Bug #3948 is not the same as this.
This bug is happening only when loading the rancher 0.63.1 UI on a Chrome web browser.
There is nothing to do with database migrations.

**Comment by vincent99** [comment] 2016-03-22 16:07
@diogogmt sorry, wrong number... #4008
