### ISSUE TITLE
rancher-dns does not honor upstream TTL, static TTL for all requests

### ISSUE THREAD

**Issue by ketchoop** [rancher/rancher#8805] opened 2017-05-18 18:06 UTC
**Rancher versions:**
rancher/server: 1.5.9
rancher/agent: 1.2.2

**Infrastructure Stack versions:**
network-services: metadata 0.9.1, network-manager 0.6.6

**Docker version: (`docker version`,`docker info` preferred)**

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**

RancherOS 1.0

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**

Parallels VM

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**

HA with external DB

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**
 
Cattle

**Steps to Reproduce:**

I have consul dns for service discovery. When I start my services dns lookup seems to be ok:

```
me@container$ dig db.cachet.service.x
...
...
db.cachet.service.x. 0	IN	A	10.42.143.80
```

After that I try to upgrade db and got the same thing, but on host(outside of container) dns lookup works fine:

```
me@host$ dig db.cachet.service.x
...
db.cachet.service.herzen. 0	IN	A	10.42.8.85

me@container$ dig db.cachet.service.x
...
...
db.cachet.service.x. 0	IN	A	10.42.143.80
```

Is there any way to reduce TTL for internal dns cache? Because, there is no way to wait five or more minutes for dns cache invalidation.

Guys, please, do something with it. It's really awful.

**Comment by superseb** [comment] 2017-05-18 18:24
Thanks for reporting @ket4yii , I understand this be painful. Let me close this in favor of https://github.com/rancher/rancher/issues/8659, we'll look into it and see what we can do.

**Comment by ket4yii** [comment] 2017-05-18 18:53
@superseb 
>  I understand this be painful

It's not painful, it breaks infrastructure at all and makes me gray-haired. Is there any way to just turn internal dns off and use host ip which has dnsmasq for this purposes? Adding resolving DNS in docker doesn't work because I can't pass host ip, there is no vars for it at all, through rancher.

**Comment by ket4yii** [comment] 2017-05-18 19:03
From rancher-dns docs:

```
--ttl	600	Default TTL for local responses that are returned
```

How can I run rancher-dns with another ttl value?

**Comment by superseb** [comment] 2017-05-18 21:00
Trying the best I can here. If we can quickly identify the root cause, we can fix it and get the problem out of the way for everybody. If you want to help test it, that would be great. I created branch `dns_ttl` in `https://github.com/superseb/rancher-catalog.git`. If you add this to your settings (Admin -> Settings, Add Catalog, "library" "https://github.com/superseb/rancher-catalog.git", "dns_ttl"), and update your network-services stack with the TTL configured. Be aware that this version also enables debug logging, so only for testing/debugging purposes.

**Comment by ket4yii** [comment] 2017-05-19 08:49
@superseb Great. I'm going to test it ASAP.

**Comment by ket4yii** [comment] 2017-05-19 08:59
@superseb OH GOD, IT WORKS! Do you need additional info? Logs, dns queries and other things?

**Comment by superseb** [comment] 2017-05-19 09:04
@ket4yii If this solves your case, than that setting is enough I assume. At the moment it's a non-configurable default setting which is causing problems. Quick fix would be to get this configurable in the main catalog, for changing the default inside rancher-dns I would need to get some more info from engineering (why this was chosen, what side-effects are there when we lower it etc). Thanks for testing.

**Comment by juliangamble** [comment] 2017-05-30 01:05
Hi @superseb  - I'm running docker with consul dns as well - and was seeing something similar. 
I've had a look at your commits:

https://github.com/superseb/rancher-catalog/commit/f4569eb186ce3c1b22b2a815d7ee1367f84d74a7
https://github.com/superseb/rancher-catalog/commit/86e7beb60dbc836f119ae3d8504b510274dee826

And seen your note:
> update your network-services stack with the TTL configured

I can see that I need to set a `TTL` parameter. From reading the code, I would have thought I'd need to `export` a `TTL` variable - but you're saying I need to set this in rancher? Could you expand on your method?

**Comment by superseb** [comment] 2017-05-30 09:10
The TTL parameter is not present in the previous catalog item, hence setting `$TTL` has no effect. This new item adds `TTL` with a default of `600`, which is statically configured at the moment. Let me create a PR for upstream so people can configure it in the official catalog item.

**Comment by ket4yii** [comment] 2017-05-30 13:57
@superseb I think this behaviour of the internal DNS is not compatible with RFC. I mean, if a DNS record has TTL it shouldn't be overrided or, at least(but I think it's not compatible either), you should set TTL field. Because it's hard to debug what happened with DNS.

**Comment by superseb** [comment] 2017-05-30 18:18
Agreed, we need to get this properly fixed (investigate and apply proper code to respect upstream).

**Comment by ket4yii** [comment] 2017-06-09 13:13
@superseb Any news about this flag in network-services? Sorry, if I'm annoying, but new network-services version is available and I can't upgrade because of this bug.

**Comment by ketchoop** [comment] 2017-07-04 23:11
ping

**Comment by alena1108** [comment] 2017-07-14 22:31
@ketchoop just a quick summary. We have 2 issues:

1) Rancher default TTL being too long
2) Rancher DNS not respecting upstream TTL

for 1) we are going to make TTL configurable via the template (with 10 seconds as default). This fix would be provided ASAP to unblock you.

for 2) a bigger fix is needed for the rancher-dns. When store item in DNS cache, store it for the upstream TTL. Also upon forming the response to the user, update the TTL value to "upstream TTL - time spend in rancher dns internal cache". Along with the fix, we are gonna change the default value for defaultTTL to 10 seconds on the microservice side as well.

@kinarashah  ^

**Comment by ketchoop** [comment] 2017-07-14 23:51
@alena1108 Thank you!

**Comment by deniseschannon** [comment] 2017-08-09 21:37
Available in network-services v0.2.6, with `rancher/dns:v0.15.2`

**Comment by sangeethah** [comment] 2017-08-16 21:33
Tested with rancher-server version - v1.6.8-rc3 with  network-services v0.2.6 and rancher/dns:v0.15.2.

This version of dns comes with TTL set to 1 sec default.

From within any container , when we  try to reach upstream URL , TTL gets defaulted to "0" secs.

If the TTL in the DNS is changed to some other value (like 60 secs ) , upstream TTL gets defaulted to the the lower of DNS TTL and upstream TTL.


Keeping this issue is open to implement the following:
1. It may not be ideal to use the same TTL for internal and upstream DNS resolution
2. In case of upstream DNS resolution , should we be able to use the TTL value from upstream URL directly instead of going with the  lower of DNS TTL and upstream TTL?

**Comment by alena1108** [comment] 2017-08-17 23:02
@sangeethah the original issue was fixed; will be keeping track of the enhancement you've suggested in https://github.com/rancher/rancher/issues/9711

**Closed by alena1108** 2017-08-17 23:02 UTC
Labels: area/dns, kind/bug, priority/-1, version/1.6
