### ISSUE TITLE
[BUG] Rancher upgrade fail: Failed to find system chart "fleet"

### ISSUE THREAD

**Issue by johnliu55tw** [rancher/rancher#36914] opened 2022-03-16 06:06 UTC
**Rancher Server Setup**
- Rancher version: v2.6.3
- Installation option (Docker install/Helm Chart): Helm Chart, with `useBundledSystemChart: true`
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): RKE2 v1.22.7-rke2r1
- Proxy/Cert Details: Certificates from files

**Information about the Cluster**
- Kubernetes version: v1.22.7-rke2r1
- Cluster Type (Local/Downstream): Local
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider):

**User Information**
- What is the role of the user logged in? (Admin/Cluster Owner/Cluster Member/Project Owner/Project Member/Custom): Admin
  - If custom, define the set of permissions:
   
**Describe the bug**

When I tried to upgrade Rancher to version `v2.6-99974f06038921d357c443cb4f17459d1377a51d-head`, Rancher failed to upgrade "fleet" due to the following error:
```
[ERROR] available chart version (100.0.2+up0.3.8) for fleet is less than the min version (100.0.3+up0.3.9-rc1) 
[ERROR] Failed to find system chart fleet will try again in 5 seconds: no chart name found
```
It's caused by the `rancher-charts` resource (of `clusterrepo.catalog.cattle.io`) is not updated even if the `gitBranch` has changed:
![image](https://user-images.githubusercontent.com/5047724/158524875-05a21aa4-47bd-4b4b-bcb5-a0cc700ca135.png)
Here the `spec.gitBranch` is `dev-v2.6`, but the `status.commit` still shows the old commit. ([`5d21c199`](https://github.com/rancher/charts/commit/5d21c199dc7db29b6a5c755558edf4f6343b4c2b) is a very old).

**To Reproduce**
1. Install Rancher `v2.6.3` via Helm Chart on RKE2
2. Retrieve chart for `v2.6-99974f06038921d357c443cb4f17459d1377a51d-head`: `rancher-0.0.0-1647299882.commit-99974f060.release-v2-6.tgz`
3. Running `helm get values -n cattle-system rancher -oyaml > values.yaml` to dump the current value, then add `rancherImageTag: v2.6-99974f06038921d357c443cb4f17459d1377a51d-head` to the `values.yaml`
4. Upgrade Rancher with the `values.yaml` using helm: `helm upgrade rancher ./*.tgz --namespace cattle-system -f values.yaml`
5. Check the Rancher Pods log, and the error messages are shown.

**Result**
fleet is not upgraded to the desired version `v0.3.9-rc5`:
```
kubectl get deploy -n cattle-fleet-system fleet-controller -o jsonpath='{.spec.template.spec.containers[0].image}'
rancher/fleet:v0.3.8
```

**Expected Result**

fleet should be upgraded to the desired version `v0.3.9-rc5`

**Screenshots**

**Additional context**
Seems like this issue only occurred when `useBundledSystemChart` is set to `true` during the installation. When this value is absent, fleet successfully upgraded to `v0.3.9-rc5`.

SURE-4063

**Comment by aiyengar2** [comment] 2022-03-16 16:08
@johnliu55tw I'm not exactly sure what the issue is here, but generally if `useBundledSystemChart` is set to true, we assume that you are operating in an air-gapped environment and only use what was bundled into the Docker image.

It's also possible that this is an issue unique to 2.6-head since, iirc, we don't generally test air-gapped scenarios till we cut the first RC (possibly because some settings need to be changed to support building the Rancher image for airgap).

**Comment by sowmyav27** [comment] 2022-03-20 16:57
**On 2.6head commit id: `024e6fa`**

- No fleet is deployed in local cluster - docker install rancher
- Rancher logs show

```
2022/03/20 16:55:35 [ERROR] Failed to find system chart fleet will try again in 5 seconds: configmaps "" not found
2022/03/20 16:55:40 [ERROR] Failed to find system chart fleet will try again in 5 seconds: configmaps "" not found
2022/03/20 16:55:45 [ERROR] Failed to find system chart fleet will try again in 5 seconds: configmaps "" not found
2022/03/20 16:55:45 [ERROR] error syncing 'git-webhook': handler apiservice: failed to create cattle-fleet-system/stv-aggregation /v1, Kind=Secret for apiservice git-webhook: namespaces "cattle-fleet-system" not found, requeuing
2022/03/20 16:55:50 [ERROR] Failed to find system chart fleet will try again in 5 seconds: configmaps "" not found
2022/03/20 16:55:55 [ERROR] Failed to find system chart fleet will try again in 5 seconds: configmaps "" not found
2022/03/20 16:56:00 [ERROR] Failed to find system chart fleet will try again in 5 seconds: configmaps "" not found
2022/03/20 16:56:05 [ERROR] Failed to find system chart fleet will try again in 5 seconds: configmaps "" not found
2022/03/20 16:56:10 [ERROR] Failed to find system chart fleet will try again in 5 seconds: configmaps "" not found
2022/03/20 16:56:15 [ERROR] Failed to find system chart fleet will try again in 5 seconds: configmaps "" not found
2022/03/20 16:56:20 [ERROR] Failed to find system chart fleet will try again in 5 seconds: configmaps "" not found
2022/03/20 16:56:25 [ERROR] Failed to find system chart fleet will try again in 5 seconds: configmaps "" not found
2022/03/20 16:56:30 [ERROR] Failed to find system chart fleet will try again in 5 seconds: configmaps "" not found
2022/03/20 16:56:32 [ERROR] error syncing 'library': handler catalog: Update failed: fatal: Unable to create '/var/lib/rancher/management-state/catalog-cache/380859f1003fe7603cddc6c15b34b7263f1f0deaa92ddcde465811d032ee7078/.git/index.lock': File exists.

Another git process seems to be running in this repository, e.g.
an editor opened by 'git commit'. Please make sure all processes
are terminated then try again. If it still fails, a git process
may have crashed in this repository earlier:
remove the file manually to continue.
: exit status 128, requeuing
2022/03/20 16:56:35 [ERROR] Failed to find system chart fleet will try again in 5 seconds: configmaps "" not found
2022/03/20 16:56:40 [ERROR] Failed to find system chart fleet will try again in 5 seconds: configmaps "" not found
```

**Comment by SheilaghM** [comment] 2022-03-22 20:52
Root-causing this and tracking it between Harvester, Fleet, and Rancher will need additional engineering time so this will not make the v2.6.4 release, but we will continue working it.

**Comment by janeczku** [comment] 2022-04-04 14:59
Reproduced the issue by upgrading from v2.6.3 to v2.6.4.

Observation: `Clusterrepo` resource for Rancher `charts` is referencing an outdated commit SHA (`5d21c199`).


<img width="1668" alt="Screenshot 2022-04-04 at 16 52 55" src="https://user-images.githubusercontent.com/3813921/161571938-c92222f3-81fa-43be-952b-4e35b97c0393.png">


Logs:

```
Mon, Apr 4 2022 4:24:48 pm | 2022/04/04 14:24:48 [ERROR] Failed to find system chart fleet will try again in 5 seconds: no chart name found
Mon, Apr 4 2022 4:24:52 pm | 2022/04/04 14:24:52 [ERROR] error syncing 'fleet-default/demo-managed-system-upgrade-controller': handler mcc-bundle: no chart version found for system-upgrade-controller-100.0.2+up0.3.2, requeuing
Mon, Apr 4 2022 4:24:52 pm | 2022/04/04 14:24:52 [ERROR] error syncing 'fleet-default/gusdemo-managed-system-upgrade-controller': handler mcc-bundle: no chart version found for system-upgrade-controller-100.0.2+up0.3.2, requeuing
Mon, Apr 4 2022 4:24:53 pm | 2022/04/04 14:24:53 [ERROR] available chart version (100.0.2+up0.3.8) for fleet is less than the min version (100.0.3+up0.3.9)
```

 clusterrepo.catalog.cattle.io/rancher-charts

```
> kubectl get clusterrepo.catalog.cattle.io/rancher-charts -o yaml
apiVersion: catalog.cattle.io/v1
kind: ClusterRepo
metadata:
  creationTimestamp: "2022-01-28T15:39:02Z"
  generation: 5
  name: rancher-charts
  resourceVersion: "75317643"
  uid: bfed7ceb-91a5-4253-89dc-b186909b1cef
spec:
  forceUpdate: "2022-04-04T14:17:41Z"
  gitBranch: release-v2.6
  gitRepo: https://git.rancher.io/charts
status:
  branch: release-v2.6
  commit: 5d21c199dc7db29b6a5c755558edf4f6343b4c2b
  conditions:
  - lastUpdateTime: "2022-04-04T14:17:41Z"
    status: "True"
    type: FollowerDownloaded
  - lastUpdateTime: "2022-04-04T14:45:49Z"
    status: "True"
    type: Downloaded
  downloadTime: "2022-04-04T14:45:49Z"
  indexConfigMapName: rancher-charts-0-bfed7ceb-91a5-4253-89dc-b186909b1cef
  indexConfigMapNamespace: cattle-system
  observedGeneration: 5
  url: https://git.rancher.io/charts
```

**Comment by PennyScissors** [comment] 2022-04-11 19:37
> Reproduced the issue by upgrading from v2.6.3 to v2.6.4. `useBundledSystemChart` was not enabled.
> 
> Observation: `Clusterrepo` resource for Rancher `charts` is referencing an outdated commit SHA (`5d21c199`).
> 
> <img alt="Screenshot 2022-04-04 at 16 52 55" width="1668" src="https://user-images.githubusercontent.com/3813921/161571938-c92222f3-81fa-43be-952b-4e35b97c0393.png">
> 
> Logs:
> 
> ```
> Mon, Apr 4 2022 4:24:48 pm | 2022/04/04 14:24:48 [ERROR] Failed to find system chart fleet will try again in 5 seconds: no chart name found
> Mon, Apr 4 2022 4:24:52 pm | 2022/04/04 14:24:52 [ERROR] error syncing 'fleet-default/demo-managed-system-upgrade-controller': handler mcc-bundle: no chart version found for system-upgrade-controller-100.0.2+up0.3.2, requeuing
> Mon, Apr 4 2022 4:24:52 pm | 2022/04/04 14:24:52 [ERROR] error syncing 'fleet-default/gusdemo-managed-system-upgrade-controller': handler mcc-bundle: no chart version found for system-upgrade-controller-100.0.2+up0.3.2, requeuing
> Mon, Apr 4 2022 4:24:53 pm | 2022/04/04 14:24:53 [ERROR] available chart version (100.0.2+up0.3.8) for fleet is less than the min version (100.0.3+up0.3.9)
> ```
> 
> clusterrepo.catalog.cattle.io/rancher-charts
> 
> ```
> > kubectl get clusterrepo.catalog.cattle.io/rancher-charts -o yaml
> apiVersion: catalog.cattle.io/v1
> kind: ClusterRepo
> metadata:
>   creationTimestamp: "2022-01-28T15:39:02Z"
>   generation: 5
>   name: rancher-charts
>   resourceVersion: "75317643"
>   uid: bfed7ceb-91a5-4253-89dc-b186909b1cef
> spec:
>   forceUpdate: "2022-04-04T14:17:41Z"
>   gitBranch: release-v2.6
>   gitRepo: https://git.rancher.io/charts
> status:
>   branch: release-v2.6
>   commit: 5d21c199dc7db29b6a5c755558edf4f6343b4c2b
>   conditions:
>   - lastUpdateTime: "2022-04-04T14:17:41Z"
>     status: "True"
>     type: FollowerDownloaded
>   - lastUpdateTime: "2022-04-04T14:45:49Z"
>     status: "True"
>     type: Downloaded
>   downloadTime: "2022-04-04T14:45:49Z"
>   indexConfigMapName: rancher-charts-0-bfed7ceb-91a5-4253-89dc-b186909b1cef
>   indexConfigMapNamespace: cattle-system
>   observedGeneration: 5
>   url: https://git.rancher.io/charts
> ```

@janeczku Did you enable `useBundledSystemChart` at any time for your setup and then disabled it? Did you check the value of the env var $CATTLE_SYSTEM_CATALOG is not "bundled"? When you install Rancher from the chart and enable `useBundledSystemChart`, the [current logic](https://github.com/rancher/rancher/blob/b44d54ae2e81707e46a68de5da3834b8b7b43fa0/chart/templates/deployment.yaml#L127-L130) doesn't let you toggle it back to "external".  So if you enable it and then disabled it, it is still enabled, but to you it could look as if this issue is present with `useBundledSystemChart=false`.

**Comment by guangbochen** [comment] 2022-04-12 03:16
We are still waiting for the upstream fix but would be fine to postpone it to the next v2.6.6 fix due to the time constraints.

Our current approach is to [delete all rancher's clusterrepos so they will be updated by the new version rancher pods](https://github.com/harvester/harvester/blob/a9006087711e92415960801ceca611febd04e937/package/upgrade/upgrade_manifests.sh#L193-L199), but this is just a temp workaround, thanks.

**Comment by bk201** [comment] 2022-04-12 03:57
> We are still waiting for the upstream fix but would be fine to postpone it to the next v2.6.6 fix due to the time constraints.
> 
> Our current approach is to [delete all rancher's clusterrepos so they will be updated by the new version rancher pods](https://github.com/harvester/harvester/blob/a9006087711e92415960801ceca611febd04e937/package/upgrade/upgrade_manifests.sh#L193-L199), but this is just a temp workaround, thanks.

Just want to note this workaround works because we preload images, and the new pods start quickly before the existing non-leader pod becomes the leader.

**Comment by MKlimuszka** [comment] 2022-06-10 15:39
During triage, Steven says that this is due to how we bundle the charts for airgapped setups, so this needs to be given to team 2.

**Comment by PennyScissors** [comment] 2022-06-13 18:45
> During triage, Steven says that this is due to how we bundle the charts for airgapped setups, so this needs to be given to team 2.

Expanding on the comment above, I investigated this issue with @kinarashah, and we found out this is not a fleet specific issue, it's a bug on how bundled chart repos for airgap are updated after a Rancher upgrade. My understanging is that when you upgrade Rancher the commits of your ClusterRepo resources should get updated to the new commits of the repos bundled in the new Rancher version you are upgrading to. We found that the commit is not getting updated, and since we have a minimum fleet version set in the Dockerfile [here](https://github.com/rancher/rancher/blob/c8d01c681cdaf9ed8f4d5e0f86c18681848d0734/package/Dockerfile#L67) that we use for validation, [this check fails](https://github.com/rancher/rancher/blob/0e49c0fcfbf8a1651dd7a2c6487f8e2001cd91d5/pkg/catalogv2/system/system.go#L414-L417) and throws the error shown above because the new Rancher version has a new higher fleet version min that is not available. I expect this to affect SUC, webhook, and any chart that has a min in the Dockerfile.

**Comment by izaac** [comment] 2022-07-07 21:25
Rancher version before upgrade: `v2.6.3`
Fleet version before upgrade: `v0.3.8`

Rancher version after upgrade: `v2.6.6`
Fleet version before upgrade: `v0.3.9`
Local cluster where the Rancher chart is installed: RKE1.

**I was not able to reproduce**.

I've followed the steps to reproduce to upgrade Rancher from `v2.6.3` to `v2.6.6`.
I've included an extra step where I push the new images listed in `rancher-images.txt` before upgrade.

1. Install Rancher v2.6.3 via Helm Chart on RKE1 Airgap
2. Load the new `rancher-images.txt` image list to the private registry used by Rancher
3. Retrieve chart for `v2.6.6`
4. Render the template and install with the previous values of the template command used in 2.6.3 (example after these steps).
5. Upgrade Rancher: `kubectl -n cattle-system apply -R -f  ./rancher`
6. Check Fleet is upgraded successfully to `v0.3.9`

Example upgrade command to render the helm template:

`helm template rancher ./rancher-2.6.6.tgz --output-dir . --namespace cattle-system --set hostname=<REDACTED> --set rancherImage=<REDACTED>/rancher/rancher --set systemDefaultRegistry=<REDACTED> --set useBundledSystemChart=true --set ingress.tls.source=secret --set rancherImageTag=v2.6.6 --no-hooks`

**Comment by HarrisonWAffel** [comment] 2022-07-11 21:50
@izaac Thanks for testing this issue again! I do see some slight differences between the initial reproduction steps and your test. For instance your local cluster uses RKE1 instead of RKE2, and you pushed the `rancher-images.txt` before you upgraded. Could you please re-test this following the initial reproduction steps exactly? That would help determine if this has been fixed indirectly, or if step `2` was able to resolve the issue.

**Comment by izaac** [comment] 2022-07-12 02:53
@HarrisonWAffel I've done the same scenario I described but now on RKE2. I also didn't include the step `2` (load images before upgrade).

If I don't load the images in the private registry I end up with `ErrImagePull` `ImagePullBackOff` because the images don't exist in the private registry. We must have those in the registry before upgrade.

I did see the error message in the logs:

```
022/07/12 02:48:18 [ERROR] Failed to find system chart fleet will try again in 5 seconds: no chart name found
2022/07/12 02:48:23 [ERROR] Failed to find system chart fleet will try again in 5 seconds: no chart name found
2022/07/12 02:48:28 [ERROR] Failed to find system chart fleet will try again in 5 seconds: no chart name found
2022/07/12 02:48:33 [ERROR] Failed to find system chart fleet will try again in 5 seconds: no chart name found
```

But it recovered after a while when fleet got upgraded successfully from `v0.3.8` to `v0.3.9` (Rancher version v2.6.3 to v2.6.6)

**Comment by izaac** [comment] 2022-07-14 19:55
I was able to reproduce in this upgrade path: Rancher `v2.5.12` to Rancher `v2.6.3`. In. this path we expect fleet to upgrade from `v0.3.5` to `v0.3.8`.

After upgrading to Rancher `v2.6.3` I see Rancher upgrades and then fleet gets the helm upgrade too but the image is still `v0.3.5`

```
kubectl get deploy -n cattle-fleet-system fleet-controller -o jsonpath='{.spec.template.spec.containers[0].image}'
<REGISTRY_DNS>/rancher/fleet:v0.3.5
```

[Steps](https://github.com/rancher/rancher/issues/36914#issuecomment-1178247478) followed on Airgap RKE2 HA. And upgrade path: Rancher `v2.5.12` to `v2.6.3`

I am closing this issue as this is not reproducible on `v2.6.6`

**Comment by AndrewHoffmanQA** [comment] 2022-11-15 16:37
picking this bug up to attempt to reproduce. appears to be related to https://zube.io/rancher/rancher/c/52334

**Comment by ronhorton** [comment] 2023-01-11 17:08
**Could not reproduce - when upgrading to v2.6.8, fleet and webhook versions updated correctly**
1. created an `airgap rancher with rancher v2.6.3`
2. verified fleet chart version `100.0.2+up0.3.8` and rancher-webhook chart version `1.0.2+up0.2.2`
3. upgraded airgap to rancher v2.6.8 with `--set useBundledSystemChart=true`
4. verified fleet and rancher webhook versions had `updated as expected` 

- fleet:100.0.5+up0.3.11 
- rancher-webhook:1.0.5+up0.2.6

<img width="1631" alt="2022-11-30_17-20-11" src="https://user-images.githubusercontent.com/89212856/205102861-760dbbb0-9d79-4d89-9484-bb7025993787.png">

**Closed** 2023-01-11 17:09 UTC
Labels: area/catalog, internal, area/air-gapped, area/fleet, [zube]: QA Working, area/harvester, team/area3, LoE/8, area/charts
