### ISSUE TITLE
Update kubectl version

### ISSUE THREAD

**Issue by Itiho** [rancher/rancher#13917] opened 2018-06-08 21:36 UTC
**Rancher versions:**
rancher/rancher: 2.0.2

**kubectl top** command need version 1.10+ but in rancher 2.0.2 **Launch kubectl** shell interface kubectl command version is 1.8.9

```
kubectl version
Client Version: version.Info{Major:"1", Minor:"8+", GitVersion:"v1.8.9-rancher1", GitCommit:"68595e18f25e24125244e9966b1e5468a98c1cd4", GitTreeState:"clean", BuildDate:"2018-03-13T04:51:52Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.1", GitCommit:"d4ab47518836c750f9949b9e0d387f20fb92260b", GitTreeState:"clean", BuildDate:"2018-04-12T14:14:26Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by superseb** [comment] 2018-06-09 06:16
Duplicate of https://github.com/rancher/rancher/issues/13554

**Closed by superseb** 2018-06-09 06:16 UTC
