### ISSUE TITLE
[ERROR] nodeDrain (v2.2.8)

### ISSUE THREAD

**Issue by LincolnBruce** [rancher/rancher#23333] opened 2019-10-10 01:19 UTC
**What kind of request is this (question/bug/enhancement/feature request):**
Node Draining

**Steps to reproduce (least amount of steps as possible):**
执行Node驱散

**Result:**
`
2019/10/10 01:15:39 [ERROR] nodeDrain: [iZ2zefj6k9vb8bfodcfg0wZ] in cluster [c-24bcj] :  <nil>
2019/10/10 01:15:40 [INFO] Draining node iZ2zefj6k9vb8bfodcfg0wZ in c-24bcj
2019/10/10 01:15:40 [ERROR] nodeDrain: [iZ2zefj6k9vb8bfodcfg0wZ] in cluster [c-24bcj] :  <nil>
2019/10/10 01:15:40 [INFO] Draining node iZ2zefj6k9vb8bfodcfg0wZ in c-24bcj
2019/10/10 01:15:40 [ERROR] nodeDrain: [iZ2zefj6k9vb8bfodcfg0wZ] in cluster [c-24bcj] :  <nil>
2019/10/10 01:15:40 [INFO] Draining node iZ2zefj6k9vb8bfodcfg0wZ in c-24bcj
2019/10/10 01:15:40 [ERROR] nodeDrain: [iZ2zefj6k9vb8bfodcfg0wZ] in cluster [c-24bcj] :  <nil>
`

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI):
- Installation option (single install/HA):
Rancher v2.2.8 single install
![image](https://user-images.githubusercontent.com/7814560/66531871-ec36eb80-eb3f-11e9-86c8-1054274dc7f7.png)

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported):
- Machine type (cloud/VM/metal) and specifications (CPU/memory):
- Kubernetes version (use `kubectl version`):
Cluster type: Custom
Machine type: aliyun cloud 
![image](https://user-images.githubusercontent.com/7814560/66531647-0d4b0c80-eb3f-11e9-8e13-161df84bea88.png)

```
(paste the output here)
```

Rancher Docker version (use `docker version`):

Client:
 Version:           18.09.0
 API version:       1.39
 Go version:        go1.10.4
 Git commit:        4d60db4
 Built:             Wed Nov  7 00:49:01 2018
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.0
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.4
  Git commit:       4d60db4
  Built:            Wed Nov  7 00:16:44 2018
  OS/Arch:          linux/amd64
  Experimental:     false
```
(paste the output here)
```

gzrancher/rancher#6553

**Comment by sowmyav27** [comment] 2020-06-24 17:32
**Verified on rancher 2.2.8**

**Steps:** 
- Deploy a custom cluster - 3 nodes - 1 etcd/control plane, 2 worker nodes.
- Deploy a workload - type deployment with 3 pods.
- Drain a worker node - Safe/Aggressive
- The node transitions from `Draining` to `Drained` state and in kubectl state of the node is `Ready,SchedulingDisabled`
- The pods migrate to another worker node. 
- No error seen in logs.
- Rancher logs:

```
2020/06/24 17:28:50 [INFO] Draining node <node-ip> in c-9hhfc
2020-06-24 17:29:49.840625 I | mvcc: store.index: compact 2863
2020-06-24 17:29:49.846367 I | mvcc: finished scheduled compaction at 2863 (took 718.993µs)
```

**Comment by kinarashah** [comment] 2020-06-24 20:16
@sowmyav27 Could we test this on ec2 cluster with aws cloud provider and debug logs enabled just in case we reproduce it?

**Comment by sowmyav27** [comment] 2020-06-24 21:31
**Reproduced the issue on 2.2.8** 

**Steps:**

- Deploy a cloud provider setup using AWS - 1 master and 2 worker nodes.
- Deploy a workload - type deployment with 3 pods.
- Drain a worker node - Safe
- The node is stuck in `Draining`
- Error in rancher server logs - `2020/06/24 21:24:28 [ERROR] nodeDrain: [sowmya-worker-2] in cluster [c-ztrfz] :  <nil>`

**Issue is seen on `2.4.5`**

**Steps:**

- Deploy a cloud provider setup using AWS - 1 master and 2 worker nodes.
- Deploy a workload - type deployment with 3 pods.
- Drain a worker node - Safe
- The node is stuck in `Draining`
- error seen in rancher server logs: `020/06/24 21:27:17 [ERROR] nodeDrain: kubectl error draining node [sowmya-245-wrk-2] in cluster [c-h6snt]: `

**Comment by kinarashah** [comment] 2020-07-15 21:35
Available for test in 2.4-head

**Comment by sowmyav27** [comment] 2020-07-16 21:05
**Verified on 2.4-head commit id: `6a9435770`**

**Scenario#1**
- Deploy a cloud provider setup using AWS - 1 master and 2 worker nodes.
- Deploy a workload - type deployment with 3 pods.
- Drain a worker node n1 - Safe
- The pods get deleted from n1 and get schedule don n2.
- the node will be in `Drained` state. 

**Scenario#2**
- Deploy a cloud provider setup using AWS - 1 master and 2 worker nodes with k8s 1.17
- Upgrade k8s to 1.18 and enable drain
- Verified the upgrade goes through.

**Comment by sowmyav27** [comment] 2020-07-16 21:05
Reopening for fix on master

**Comment by sowmyav27** [comment] 2020-07-23 22:27
Master PR: https://github.com/rancher/rancher/pull/27957

**Comment by sowmyav27** [comment] 2020-07-23 23:11
**Verified on 2.4-head - commit id: `f6ff6a754` and on master-head commit id: `fd3e37bec`**

- Deploy a 4 node - 1 etcd/control and 3 worker nodes cloud provider enabled setup
- Drain a node. the pod on the node get drained and are scheduled on other nodes
- Node is seen in `Ready,SchedulingDisabled` state
- upgrade k8s version of the cluster when drain is enabled. The nodes get drained and upgraded.
- However on master the upgrade of cluster will not work because of this issue -- https://github.com/rancher/rancher/issues/27340

**Closed** 2020-07-23 23:36 UTC
Labels: [zube]: To Test, internal, kind/bug
