### ISSUE TITLE
Upgrading service should not result in loss of volume data

### ISSUE THREAD

**Issue by janeczku** [rancher/rancher#5010] opened 2016-06-04 16:15 UTC
**Rancher Version:**
rancher/server:v1.1.0-dev3
rancher/agent:v1.0.1
rancher/agent-instance:v0.8.1
rancher-compose-v0.8.2

**Docker Version:**
1.10.3

**Steps to Reproduce:**

Given the docker-compose.yml:

``` yaml
test:
  tty: true
  image: ubuntu:14.04.3
  stdin_open: true
  volumes:
  - /opt/mount
```

Run:

> $ rancher-compose up

Exec into the created container and run:

> $ touch /opt/mount/data.txt

Edit docker-compose.yml changing image to `ubuntu:14.04.4`

Run:

> $ rancher-compose up --upgrade
> $ rancher-compose up --upgrade --confirm-upgrade

Exec into the created container and run:

> $ cat /opt/mount/data.txt

**Results:** 
`cat: /opt/mount/data.txt: No such file or directory`

**Expected:**
The data should not be lost.

The volume should be re-used for the replacement container. Specifically, the new container should be created using the existing `container volume` as `named volume`.
For example: Given that the previous container had the volume named `9f411c6...87210` mounted in `/opt/mount`, then the new container should be created with the named volume `9f411c6...87210:/opt/mount`.
Additionally, the new container would need to be scheduled to the host that has the previous container.

Reference for how this works in in docker-compose:
https://github.com/docker/compose/pull/2934
https://github.com/docker/libcompose/pull/89

**Comment by EugenMayer** [comment] 2016-06-10 06:06
@deniseschannon that is what i was talking about during the webinar. i did not know that @janeczku already reported this, but this is also quiet relevant in the letsencrypt catalog. I could reproduce this on a different catalog and actually really had data-loss on a container, due to that.

I would actually even say, this is pretty severe even, since a lot of hub. images do use anon-volumes and expect you to either care about this yourself or not - if you include those in a rancher catalog an make them name, you lose data during upgrade. So a pretty real case actually

**Comment by pwFoo** [comment] 2016-06-11 06:08
Most volumes should be named volumes because it's better to handle. Should also be a problem with the mariadb gelera from the catalog?

**Comment by andul** [comment] 2016-07-27 10:32
A data loss in a productive environment is a total dealbreaker for Rancher

**Comment by alena1108** [comment] 2016-10-10 17:51
This would be fixed with new volumeTemplate/volume per stack/deployment unit feature. @deniseschannon could you update the bug with the reference to the doc once it is written?

**Comment by joshwget** [comment] 2016-10-10 18:06
The original issue uses a bind mount instead of named volumes. We should probably recommend the latter in docs since users might not be aware of the side effects of using bind mounts.

**Comment by deniseschannon** [comment] 2016-11-22 22:43
This use case is not actually addressed unless you used named volumes, which is what we recommend.

**Comment by alena1108** [comment] 2016-12-06 19:09
@cjellick not sure if we support sharing non-named volumes by more than 1 container?

**Comment by EugenMayer** [comment] 2016-12-06 19:17
@cjellick @deniseschannon its a blocker in both direction. Either u use anon-volumes, which blocks u, since this will result in data loss. Or you use named-volumes, which will block you when using things like catalogs, since the volume-name would be shared across different stacks of the catalogs, which is not the idea behind it. 

Those are just X-Instances of Appliance Z.

You can work arround using stomething like a "unique stack identifier" in the catalog options, being mandatory - you use this stack-identifier, be it a number, a string "xadasda" - as a prefix to your name volumes in docker-compose ( as a variable) - like a namespace. 

This way you can deploy a catalog several times and still keep changes over upgrades.

Why the above is not a build-in solution into rancher (at least catalogs), does not get into my head. But in the end, it forced us away from catalogs and also away from rancher in our biggest use case. A real pitty.

**Comment by joshwget** [comment] 2016-12-06 19:28
@EugenMayer This is no longer the case for named volumes in 1.2. Volumes can now be scoped per container, stack, or environment (https://docs.rancher.com/rancher/v1.2/en/rancher-services/storage-service/).

The use case you describe is a stack scoped volume, which is now the default. Each instance of a stack will have its own volume.

**Comment by joshwget** [comment] 2016-12-06 19:33
@deniseschannon @alena1108 @cjellick I don't see how we'd set any kind of scope policy for anonymous volumes. Does it make sense to disable this feature since it'll likely result in unintended behavior? Maybe there's some advantage to anonymous volumes over named volumes that I'm not thinking of though.

**Comment by psyhonut** [comment] 2016-12-08 14:53
Can some one provide more detailed explanation about this new volumes feature? Because when I trying to do everything from docs, I always see **inactive** status and nothing works.

**Comment by joshwget** [comment] 2016-12-08 17:40
@psyhonut Can you walk through what you tried so we know where the docs could be improved?

**Comment by psyhonut** [comment] 2016-12-09 14:50
This is my steps to implement shared volume:
- go into Catalog, select Rancher NFS
- in NFS Server wrote hostname, where I want to serve NFS (in my case this is my only one host with containers)
- mount directory is something like /var/rancher-nfs
```
version: '2'
services:
  nfs-driver:
    privileged: true
    image: rancher/storage-nfs:v0.6.0
    pid: host
    labels:
      io.rancher.scheduler.global: 'true'
      io.rancher.container.create_agent: 'true'
      io.rancher.container.agent.role: environment
    environment:
      NFS_SERVER: '${NFS_SERVER}'
      MOUNT_DIR: '${MOUNT_DIR}'
      MOUNT_OPTS: '${MOUNT_OPTS}'
    volumes:
    - /run:/run
    - /dev:/host/dev
    - /var/lib/rancher/volumes:/var/lib/rancher/volumes:shared
    logging:
      driver: json-file
      options:
        max-size: 25m
        max-file: '2'
```
- go to Infrastructure - Storage, and add volume entering only name. Then I see a table with my "Inactive" volume.

And that is it all that I understand from docs :-)
What I need to do next?

**Comment by joshwget** [comment] 2016-12-09 17:53
Volumes are inactive until they're actually used by a service. Volumes created through the UI are [scoped at the environment level](https://docs.rancher.com/rancher/v1.2/en/rancher-services/storage-service/#environment-scoped-1).

**Comment by psyhonut** [comment] 2016-12-12 08:39
@joshwget but I can't understand how to use them in my services, created from UI.

**Comment by deniseschannon** [comment] 2016-12-13 19:26
@psyhonut Did you try with a new service to see if it works there?

**Comment by psyhonut** [comment] 2016-12-14 13:50
New Service -> no buttons to choose volumes. Only fields to input data manually. What should I write?

**Comment by psyhonut** [comment] 2016-12-14 13:50
@deniseschannon  New Service -> no buttons to choose volumes. Only fields to input data manually. What should I write?

**Comment by deniseschannon** [comment] 2016-12-14 22:41
Just like described in the docs page: https://docs.rancher.com/rancher/v1.2/en/rancher-services/storage-service/#using-storage-drivers-in-the-ui

<img width="1042" alt="screen shot 2016-12-14 at 11 13 58 am" src="https://cloud.githubusercontent.com/assets/11410997/21204233/36c9c17e-c20b-11e6-8b25-6e547e70a806.png">

The `volume_name` would be the name of the volume you added.

**Comment by psyhonut** [comment] 2016-12-15 09:01
@deniseschannon thanks for the answer. And one last question - what should I need to write into field **Volume Driver**?

**Comment by deniseschannon** [comment] 2016-12-19 22:48
@psyhonut Per the docs "The volume driver will be the name of the storage driver."

**Comment by thebalaa** [comment] 2017-03-08 04:10
+1 anonymous volumes should be mounted on upgraded containers, please!

**Comment by EugenMayer** [comment] 2017-03-08 10:48
@thebalaa with the new scoped named volumes, this issue is actually solved the proper way.

You should not expect anon-volumes to persist over upgrades, it will also not do if you do a 
`docker compose down && docker-compose up` since docker-compose down will delete all anon-volumes.

for the rancher devs though, there is a tiny detail here, doing a `docker-compose pull && docker-compose up` will pull newer images and only replace the services which have newer images. but this operation differs to the above, since anon-volumes are *not deleted*.
This creates also issues of other kinds, e.g. that you have your app-code based exposed as anon-volume so other containers in the stack can mount it (e.g. the httpd container for static files) and this pull && up will not update the anon-container, so the codebase will be the old one. Please see the stack answer i have written here http://stackoverflow.com/a/41585585/3625317 it describes this more briefly.

That said anon volumes shall not be persisted over "upgrades" since this will cause an unknown chain of issues. More over, docker designed those to be "lossy on container remake" and how i learn, there are good reasons.

So instead of trying to fix "anon volume persistence" this has been already solved by "scoped name volumes" and this issue should be closed

**Comment by joshwget** [comment] 2017-03-08 18:31
@EugenMayer Interesting note about how Docker Compose will only replace services with newer images. Thanks for the heads up there.

I agree that using scoped volumes is the solution here. Based on the Docker docs anonymous volumes are removed when containers are removed so there's really not much we can do about this in any case.

**Closed by joshwget** 2017-03-08 18:31 UTC
Labels: area/service, kind/bug

**Comment by luisehk** [comment] 2017-09-20 17:43
Just had a data loss thanks to this... I used the Gitlab stack from the Rancher Catalog and when I upgraded it everything was gone.

**Comment by EugenMayer** [comment] 2017-09-21 02:58
@luisehk the real issue comes from the catalogs - the quality of those i so bad, that proper volume handling, even though it is now days possible, is just not part of it. Its a huge issue and will hurt ranchers reputation a lot over the time - but thats a different story
