### ISSUE TITLE
update/re-pull docker image

### ISSUE THREAD

**Issue by fentas** [rancher/rancher#1872] opened 2015-08-25 19:01 UTC
Hiho,
is there a way to update/change/pull docker image e.g. within a running service or on host directly over rancher ui? For me it seems a necessity to be able to do that. 

One way to that would be a web console to host as mentioned in #1858. Or just a button "re-pull image".
Also (or) would it be nice to be able to clean up the host from not needed images. (docker rmi)

**Comment by deniseschannon** [comment] 2015-08-25 21:11
We just created an issue to track this concept through rancher-compose, but I will leave this one open for UI updating. https://github.com/rancher/rancher/issues/1874

**Comment by sonicsnes** [comment] 2015-10-12 10:09
+1

**Comment by Shaidar20** [comment] 2015-10-19 10:15
bumping this. A UI feature to allow for updating existing images would be great. I have not looked at the API, but I assume that option does exist. 

On a positive note: Rancher is awesome! Keep it up guys!

**Comment by deniseschannon** [comment] 2015-10-19 17:28
An easy way to always pull the latest image would be to add a label to your service. This would cause it to always pull a new image onto the host before deploying the service.

`io.rancher.container.pull_image: always`

http://docs.rancher.com/rancher/labels/

**Comment by rayvbr** [comment] 2015-10-19 18:54
Setting a 'io.rancher.container.pull_image: always'-label doesn't seem to work for me, at least not for private repo's. Is there something else that needs to be set for this to work?

**Comment by deniseschannon** [comment] 2015-10-19 19:01
@rayvbr What version are you running? V0.39.0+ should have pull working on private registries.

**Comment by rayvbr** [comment] 2015-10-19 19:22
I'm running 0.41.0. 

Just to be clear: it should re-pull after every restart (of both the specific container, as well as the application), right?

**Comment by deniseschannon** [comment] 2015-10-19 19:29
A restart would not cause it as you would be using the SAME container. You would need to stop the container and delete. When a new container is started, it would re-pull an image on the host before deploying a NEW container.

**Comment by etlweather** [comment] 2015-10-22 14:23
`io.rancher.container.pull_image: always` works, however I noticed that when I clone a service, that label isn't kept. Is that intentional?

**Comment by vincent99** [comment] 2015-10-22 15:18
@etlweather that is a bug, https://github.com/rancher/rancher/issues/2342.

**Comment by cusspvz** [comment] 2015-11-20 12:16
I would like to propose three pull ways from the UI.
1. On service's options dropdown, where you could pull image on all hosts.
2. On stack's options dropdown, where you could pull all services images on all hosts.
3. On service upgrade where you could mark **Pull before start** (same as `rancher-compose up --pull`)

**Comment by deniseschannon** [comment] 2016-02-04 21:05
I'd like to close this as the label and option in the UI (checked by default) allows you to re-pull docker images. 

@cusspvz 
If you do an in-service upgrade and select the "always pull image" checkbox, then you would be pulling the image for any time the service is deployed on a host.

**Closed by deniseschannon** 2016-02-04 21:05 UTC
Labels: area/service, area/ui, kind/feature

**Comment by deitch** [comment] 2016-02-21 13:41
I just realized this is closed. Can we reopen it? 

The label and option in the UI allows you to decide between "always pull" and "never pull". But as @cusspvz say above, how would I do the following in the UI, "For this service that does not have always pull set, pull now."?

**Comment by deniseschannon** [comment] 2016-02-22 19:46
@deitch You would do an upgrade and select the checkbox. Going forward, it would always pull before launching the container.

Can you describe a use case of when you wouldn't want always or never because I'm assuming that if you want to pull, then you'd probably want to always pull as you are re-using the same tag in Dockerhub.

**Comment by deitch** [comment] 2016-02-22 19:55
Running an upgrade without changing the image would force a pull? That would work.

In the end, we decided to go for "always pull", so I added it to the tag in the compose yml, but I can see use cases where you might not want always pull, but want to do it on-demand.

**Comment by deniseschannon** [comment] 2016-02-22 20:03
@deitch Yes, you'd need to make sure you check the "pull always" checkbox under the image name. That would mean any time the container is launched, it would pull a new image to the host.

**Comment by deitch** [comment] 2016-02-22 20:05
Or 

````yml
  labels:
    io.rancher.container.pull_image=always
````

**Comment by DamonGant** [comment] 2016-02-23 14:02
@deitch If you want to leave it at that, that option needs to be better documented. Took me a while to find out it existed.

**Comment by deitch** [comment] 2016-02-23 14:03
@DamonGant me too. Actually, I found it by creating a new service (but not starting it) with the option "always pull" checked, then looking at the config. Later I found it in the docs.

**Comment by deniseschannon** [comment] 2016-02-23 17:37
All labels that are supported in rancher-compose are listed in the docs at this location:

http://docs.rancher.com/rancher/labels/

**Comment by scomma** [comment] 2016-11-21 16:29
Hi. This option is sorely needed in our case. Always pulling the image isn't the same as manually triggering a pull. This is how we do a deploy:

1. Build a new image
2. Upgrade a migration service (which is simply a run-and-die service that runs the database migrations) through `rancher-compose -p`
3. Upgrade the rest of the stack through `rancher-compose -p`

The problem is after 1 completes but before 2 completes, we cannot have any container in the stack other than migration service running the new code base. However occasionally the migration can take up to multiple hours, and meanwhile some containers would be killed, rebalanced and recreated. If the always pull label is set, then it will start with the new code base.

Our solution right now is to stick to `rancher-compose`, but so far this is a CLI feature with no GUI equivalent.

**Comment by pdonorio** [comment] 2018-02-16 16:01
The updated link for rancher labels is: http://rancher.com/docs/rancher/latest/en/cattle/labels/

@deniseschannon I didn't understand if this is possible also when launching a normal container (not a service) through the rancher API. Or do I have to pull or remove the image before that? How, I can't find a way for that too... thanks

**Comment by pdonorio** [comment] 2018-02-19 08:42
Made a test today on latest rancher `1.6`; by adding the label describe above to the API creation of a single container the image is effectively updated/pulled before starting.
