### ISSUE TITLE
Support for shipping cluster templates

### ISSUE THREAD

**Issue by alena1108** [rancher/rancher#22306] opened 2019-08-20 20:38 UTC
We should have a capability of shipping cluster templates

**Comment by cbron** [comment] 2021-04-23 13:56
Duplicate of https://github.com/rancher/rancher/issues/30099 ?

**Comment by Jono-SUSE-Rancher** [comment] 2021-04-23 21:25
This ticket is tracking the ability to apply any cluster YAML in a K8s cluster and it would deploy. We should test this as a import.yaml and through fleet.

**Comment by vincent99** [comment] 2021-04-23 22:30
? That's not at all what the original issue from Alena (who no longer works here) says

**Comment by deniseschannon** [comment] 2021-05-19 18:20
I've edited the original request so it's related to only shipping cluster templates (not pre-packaged ones). 

With the new cluster provisioning framework, we should be able to deploy any cluster templates. We will use this issue to track deploying a cluster CR by importing as YAML as well as an option for fleet.

**Comment by slickwarren** [comment] 2021-07-24 00:27
on master-head (861fb92):

* using [this repo](https://github.com/slickwarren/cluster-template-examples/tree/fleet-template/fleet-test), I was able to create a downstream cluster using fleet (specifying the `fleet-cluster` workspace) -- pass
  * there was an error within fleet due to http://fleet.rancher.io/bundle-diffs/ (which is a known solution, unrelated to these tests)
* deleting said cluster through fleet works as expected -- pass
  * deleting the cluster through `cluster management` does delete the cluster, but next time that fleet updates, the cluster will redeploy with settings from the repo (expected)
* editing the `repo` results in a new cluster deployed through fleet, with the new settings applied there --> this only happens if the user edits the _name_ of a cluster. editing other values (i.e. k8s version) works as expected. I have let the dev know about this to take necessary action -- pass
* provisioning via `import yaml` through the local cluster also works. . 
* Note: I was able to provision an imported cluster, but did not provision using a provider (i.e. digital ocean).  -> will continue with this test on monday

**Comment by slickwarren** [comment] 2021-08-05 17:26
I need more info on how to configure the machine instances for a node driver, since those are a separate request from what is in the cluster.yaml

**Comment by vincent99** [comment] 2021-08-08 09:29
In general the easiest way to see what you should be sending for something is to open the Network tab of the dev tool sin a browser and see what the UI sends. 

machinePools are part of the cluster spec.  They contain the replica count, roles, and a `machineConfigRef`.

The rest of the config (region, instance type, that sort of thing) is in a separate resource; There is a different type and fields for each machine driver.  For instance DigitalOcean is a `/v1/rke-machine-config.cattle.io.digitaloceanconfigs`.

- You need one machineConfig per pool.
- The same one can't be shared across 2 pools, even though that sounds like an obviously useful thing to do.
- They must be created in the same namespace as the cluster (`fleet-default`).
- They are mostly immutable so you need to make a new one to change anything.
- The `spec.rkeConfig.machinePools[].machineConfigRef` points at the config you created.  So for DO the kind would be `DigitaloceanConfig` and the `name` whatever you called it (or the UI uses `generateName` instead of making the user pick one).

**Comment by slickwarren** [comment] 2021-08-12 22:31
on 2.6-head (9d2e086) I was able to verify that deploying a cluster via yaml is also working. Thanks to Vincent's help above, I was able to:
* create a credential for digital ocean (this was done through the UI)
* create a machineConfig for reference by the cluster via `import yaml`
* create a cluster via `import yaml`, which points to the above 2 resources and is able to bring a node to `active`, and the user is able to use the node as expected

![Screen Shot 2021-08-12 at 3 21 00 PM](https://user-images.githubusercontent.com/16691014/129277464-022a4376-519d-4e59-b4b0-86892f24c990.png)

these changes were merged pre-split of branches, so no need to test on master-head

**Closed** 2021-08-12 22:50 UTC
Labels: kind/feature, priority/0, [zube]: QA Working, QA/need-info
