### ISSUE TITLE
When LB service is scaled more than the host available , editing the scale should fail and user should be presented with an error message.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#768] opened 2015-05-11 16:48 UTC
Server version - V0.20.0

Create LB service with scale 2 and link it to another service in the same environment.
Set up has 3 hosts.
Edit Lb service and set scale to 4.
This results in another LB agent being created on the 3rd host , as expected.

The service is stuck in "updating-active" state forever , since there is no host available for scaling to 4.

Expected Behavior:
Editing the scale of the service should report failure and user should be presented with an appropriate error message.

**Comment by alena1108** [comment] 2015-05-11 22:58
Sangeetha, as per our discussion, its related to the fact that we don't change the status of the service to failed when the service fails to bring up instances. The reason of the failure doesn't matter. So marking as a duplicate to https://github.com/rancherio/rancher/issues/557. Lets just keep all the discussions there.

**Comment by sangeethah** [comment] 2015-05-15 19:34
I am reopening this issue , w.ro.to the discussions in  https://github.com/rancherio/rancher/issues/820

**Comment by deniseschannon** [comment] 2015-05-15 20:07
:+1: Same comments as #727. Need to think of multiple users.

**Comment by deniseschannon** [comment] 2015-12-03 22:58
Pre-duplicate of https://github.com/rancher/rancher/issues/820

Essentially, we need better error message when service will fail to scale due to lack of open ports or invalid container info.

**Closed by deniseschannon** 2015-12-03 22:58 UTC
Labels: area/service, kind/bug, status/reopened
