### ISSUE TITLE
Allow Rancher UI to be Highly-Available

### ISSUE THREAD

**Issue by ahazelwood** [rancher/rancher#13919] opened 2018-06-08 22:16 UTC
It would be nice to be able to access the rancher UI from more than one server for high-availability reasons.  Similarly to the way that etcd and the control plane can be run on more than one node.

**Comment by superseb** [comment] 2018-06-09 06:18
Duplicate of https://github.com/rancher/rancher/issues/13292

**Closed by superseb** 2018-06-09 06:18 UTC
