### ISSUE TITLE
Bitnami Chart fails to refresh, causing Rancher Backup Restore timeouts and loops

### ISSUE THREAD

**Issue by jonathon2nd** [rancher/rancher#31940] opened 2021-04-06 15:48 UTC
**What kind of request is this (question/bug/enhancement/feature request):**
bug

**Steps to reproduce (least amount of steps as possible):**
On the Rancher Management Cluster, in the Cluster Explorer, navigate to Rancher Backups.
Create a Restore attempt.

**Result:**
UI becomes unavalible. 
After a few minutes navigated to one of the Rancher nodes and ran `kubectl logs -n cattle-resources-system -l app.kubernetes.io/name=rancher-backup -f` to view the logs.
The following error occurs, and then it trys again, never ending.

```
...
INFO[2021/04/05 21:45:34] Getting new UID for grb-7blfg
INFO[2021/04/05 21:45:34] Successfully restored cattle-globalrolebinding-grb-7blfg
INFO[2021/04/05 21:45:34] Processing controllerRef apps/v1/deployments/rancher
INFO[2021/04/05 21:45:34] Scaling up controllerRef apps/v1/deployments/rancher to 3
ERRO[2021/04/05 21:45:34] Error restoring cluster-scoped resources [error restoring bitnami-v3 of type management.cattle.io/v3, Resource=catalogs: restoreResource: err updating resource Timeout: request did not complete within requested timeout 34s]
ERRO[2021/04/05 21:45:34] error syncing 'restore-kj2pp': handler restore: error restoring cluster-scoped resources, check logs for exact error, requeuing
...
```

**Other details that may be helpful:**
After 15+ minutes of this constant looping, I decided to restore the cluster using rke. Which I successfully did. I setup daily reoccurring RKE etcd snapshots previously. 

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): v2.5.7
- Installation option (single install/HA): HA

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): Imported
- Machine type (cloud/VM/metal) and specifications (CPU/memory): VMs, 5 vCPUS, 8G Ram
- Kubernetes version (use `kubectl version`):

```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.6", GitCommit:"dff82dc0de47299ab66c83c626e08b245ab19037", GitTreeState:"clean", BuildDate:"2020-07-15T16:58:53Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.5", GitCommit:"6b1d87acf3c8253c123756b9e61dac642678305f", GitTreeState:"clean", BuildDate:"2021-03-18T01:02:01Z", GoVersion:"go1.15.8", Compiler:"gc", Platform:"linux/amd64"}
```

  - Docker version (use `docker version`):

```
$ docker version
Client: Docker Engine - Community
 Version:           19.03.12
 API version:       1.40
 Go version:        go1.13.10
 Git commit:        48a66213fe
 Built:             Mon Jun 22 15:46:54 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.12
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.13.10
  Git commit:       48a66213fe
  Built:            Mon Jun 22 15:45:28 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.2.13
  GitCommit:        7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

**Comment by jonathon2nd** [comment] 2021-04-06 18:45
OK, I see that the loop was caused by bitnami chart not responding, looking at the logs.
It first thought there was an issue with bitnami chart, https://github.com/bitnami/charts/issues/6034. Though that seems silly in hindsight.

Not sure why it is timing out for Rancher.

Logs: rancher
```
2021/04/06 18:38:50 [INFO] Catalog sync done. 0 templates created, 23 templates updated, 0 templates deleted, 0 templates failed
2021/04/06 18:39:24 [ERROR] error syncing 'bitnami-v3': handler catalog: Timeout: request did not complete within requested timeout 34s, requeuing
2021/04/06 18:39:26 [INFO] Updating global catalog bitnami-v3
2021/04/06 18:40:02 [INFO] Catalog sync done. 0 templates created, 23 templates updated, 0 templates deleted, 0 templates failed
2021/04/06 18:40:36 [ERROR] error syncing 'bitnami-v3': handler catalog: Timeout: request did not complete within requested timeout 34s, requeuing
2021/04/06 18:40:38 [INFO] Updating global catalog bitnami-v3
2021/04/06 18:41:14 [INFO] Catalog sync done. 0 templates created, 23 templates updated, 0 templates deleted, 0 templates failed
2021/04/06 18:41:48 [ERROR] error syncing 'bitnami-v3': handler catalog: Timeout: request did not complete within requested timeout 34s, requeuing
2021/04/06 18:41:50 [INFO] Updating global catalog bitnami-v3
2021/04/06 18:42:26 [INFO] Catalog sync done. 0 templates created, 23 templates updated, 0 templates deleted, 0 templates failed
W0406 18:42:40.081933       7 warnings.go:80] apiextensions.k8s.io/v1beta1 CustomResourceDefinition is deprecated in v1.16+, unavailable in v1.22+; use apiextensions.k8s.io/v1 CustomResourceDefinition
2021/04/06 18:43:00 [ERROR] error syncing 'bitnami-v3': handler catalog: Timeout: request did not complete within requested timeout 34s, requeuing
2021/04/06 18:43:03 [INFO] Updating global catalog bitnami-v3
W0406 18:43:12.122023       7 warnings.go:80] extensions/v1beta1 Ingress is deprecated in v1.14+, unavailable in v1.22+; use networking.k8s.io/v1 Ingress
2021/04/06 18:43:39 [INFO] Catalog sync done. 0 templates created, 23 templates updated, 0 templates deleted, 0 templates failed
```

![image](https://user-images.githubusercontent.com/52681917/113762220-f9557c00-96dd-11eb-891b-2a46557b0e27.png)

Even happening in API.
```

API Request
cURL command line:
curl -u "${CATTLE_ACCESS_KEY}:${CATTLE_SECRET_KEY}" \
-X POST \
-H 'Accept: application/json' \
-H 'Content-Type: application/json' \
'https://rancher.example.com/v3/catalogs/bitnami-v3?action=refresh'
HTTP Request:
HTTP/1.1 POST /v3/catalogs/bitnami-v3?action=refresh
Host: rancher.example.com
Accept: application/json
Content-Type: application/json
Content-Length: 2

{ }
HTTP Response:
HTTP/1.1 500
content-encoding: gzip
content-length: 135
content-type: application/json
date: Tue, 06 Apr 2021 18:41:17 GMT
expires: Wed 24 Feb 1982 18:42:00 GMT
strict-transport-security: max-age=15724800; includeSubDomains
x-api-schemas: https://rancher.example.com/v3/schemas
x-content-type-options: nosniff

{
"baseType": "error",
"code": "ServerError",
"message": "Timeout: request did not complete within requested timeout 34s",
"status": 500,
"type": "error"
}
```

**Comment by jonathon2nd** [comment] 2021-04-06 18:56
Kube-api seems to be going mad.
![image](https://user-images.githubusercontent.com/52681917/113763773-b1375900-96df-11eb-93e6-97c693e0d2e2.png)

![image](https://user-images.githubusercontent.com/52681917/113763812-be544800-96df-11eb-96f2-e58d213fae3a.png)
The red host in question
![image](https://user-images.githubusercontent.com/52681917/113763856-cca26400-96df-11eb-89d2-f5500f7c8cc6.png)


`0dfafd9db2e6        rancher/hyperkube:v1.20.5-rancher1     "/opt/rke-tools/entr…"   21 hours ago        Up 18 minutes                           kube-apiserver`


```
docker logs 0dfafd9db2e6
Trace[1954452546]: ---"Conversion done" 260ms (18:49:00.245)
Trace[1954452546]: [34.274036088s] [34.274036088s] END
I0406 18:50:23.999933       1 client.go:360] parsed scheme: "passthrough"
I0406 18:50:23.999998       1 passthrough.go:48] ccResolverWrapper: sending update to cc: {[{https://10.1.0.42:2379  <nil> 0 <nil>}] <nil> <nil>}
I0406 18:50:24.000012       1 clientconn.go:948] ClientConn switching balancer to "pick_first"
I0406 18:50:32.242559       1 client.go:360] parsed scheme: "passthrough"
I0406 18:50:32.244026       1 passthrough.go:48] ccResolverWrapper: sending update to cc: {[{https://10.1.0.43:2379  <nil> 0 <nil>}] <nil> <nil>}
I0406 18:50:32.244049       1 clientconn.go:948] ClientConn switching balancer to "pick_first"
I0406 18:50:34.551335       1 client.go:360] parsed scheme: "passthrough"
I0406 18:50:34.551434       1 passthrough.go:48] ccResolverWrapper: sending update to cc: {[{https://10.1.0.41:2379  <nil> 0 <nil>}] <nil> <nil>}
I0406 18:50:34.551447       1 clientconn.go:948] ClientConn switching balancer to "pick_first"
I0406 18:50:36.265083       1 trace.go:205] Trace[539009329]: "List" url:/apis/management.cattle.io/v3/catalogs,user-agent:rancher/v0.0.0 (linux/amd64) kubernetes/$Format,client:10.1.0.43 (06-Apr-2021 18:50:35.753) (total time: 511ms):
Trace[539009329]: ---"Listing from storage done" 302ms (18:50:00.056)
Trace[539009329]: ---"Writing http response done" count:5 208ms (18:50:00.264)
Trace[539009329]: [511.183294ms] [511.183294ms] END
E0406 18:50:38.038690       1 controller.go:116] loading OpenAPI spec for "v1beta1.custom.metrics.k8s.io" failed with: OpenAPI spec does not exist
I0406 18:50:38.038763       1 controller.go:129] OpenAPI AggregationController: action for item v1beta1.custom.metrics.k8s.io: Rate Limited Requeue.
I0406 18:50:47.646354       1 trace.go:205] Trace[991831637]: "Update" url:/apis/management.cattle.io/v3/catalogs/bitnami-v3,user-agent:rancher/v0.0.0 (linux/amd64) kubernetes/$Format,client:10.1.0.43 (06-Apr-2021 18:50:13.539) (total time: 34106ms):
Trace[991831637]: [34.106930306s] [34.106930306s] END
I0406 18:51:03.914329       1 trace.go:205] Trace[1693196921]: "GuaranteedUpdate etcd3" type:*unstructured.Unstructured (06-Apr-2021 18:48:26.454) (total time: 157459ms):
Trace[1693196921]: ---"Transaction prepared" 157436ms (18:51:00.913)
Trace[1693196921]: [2m37.459760725s] [2m37.459760725s] END
I0406 18:51:04.363378       1 client.go:360] parsed scheme: "passthrough"
I0406 18:51:04.363432       1 passthrough.go:48] ccResolverWrapper: sending update to cc: {[{https://10.1.0.42:2379  <nil> 0 <nil>}] <nil> <nil>}
I0406 18:51:04.363447       1 clientconn.go:948] ClientConn switching balancer to "pick_first"
I0406 18:51:06.560306       1 client.go:360] parsed scheme: "passthrough"
I0406 18:51:06.560377       1 passthrough.go:48] ccResolverWrapper: sending update to cc: {[{https://10.1.0.43:2379  <nil> 0 <nil>}] <nil> <nil>}
I0406 18:51:06.560396       1 clientconn.go:948] ClientConn switching balancer to "pick_first"
I0406 18:51:19.315849       1 client.go:360] parsed scheme: "passthrough"
I0406 18:51:19.316123       1 passthrough.go:48] ccResolverWrapper: sending update to cc: {[{https://10.1.0.41:2379  <nil> 0 <nil>}] <nil> <nil>}
I0406 18:51:19.316153       1 clientconn.go:948] ClientConn switching balancer to "pick_first"
I0406 18:51:24.415653       1 trace.go:205] Trace[1575512618]: "Update" url:/apis/management.cattle.io/v3/catalogs/bitnami-v3,user-agent:rancher/v0.0.0 (linux/amd64) kubernetes/$Format,client:10.1.0.43 (06-Apr-2021 18:50:50.175) (total time: 34240ms):
Trace[1575512618]: ---"About to convert to expected version" 139ms (18:50:00.315)
Trace[1575512618]: [34.240268436s] [34.240268436s] END
E0406 18:51:38.050402       1 controller.go:116] loading OpenAPI spec for "v1beta1.custom.metrics.k8s.io" failed with: OpenAPI spec does not exist
I0406 18:51:38.050442       1 controller.go:129] OpenAPI AggregationController: action for item v1beta1.custom.metrics.k8s.io: Rate Limited Requeue.
I0406 18:51:40.054322       1 client.go:360] parsed scheme: "passthrough"
I0406 18:51:40.054380       1 passthrough.go:48] ccResolverWrapper: sending update to cc: {[{https://10.1.0.42:2379  <nil> 0 <nil>}] <nil> <nil>}
I0406 18:51:40.054400       1 clientconn.go:948] ClientConn switching balancer to "pick_first"
I0406 18:51:40.880897       1 trace.go:205] Trace[499751359]: "GuaranteedUpdate etcd3" type:*unstructured.Unstructured (06-Apr-2021 18:49:01.728) (total time: 159152ms):
Trace[499751359]: ---"Transaction prepared" 159129ms (18:51:00.880)
Trace[499751359]: [2m39.152368104s] [2m39.152368104s] END
I0406 18:51:44.966483       1 client.go:360] parsed scheme: "passthrough"
I0406 18:51:44.966562       1 passthrough.go:48] ccResolverWrapper: sending update to cc: {[{https://10.1.0.43:2379  <nil> 0 <nil>}] <nil> <nil>}
I0406 18:51:44.966585       1 clientconn.go:948] ClientConn switching balancer to "pick_first"
I0406 18:51:55.623018       1 client.go:360] parsed scheme: "passthrough"
I0406 18:51:55.623099       1 passthrough.go:48] ccResolverWrapper: sending update to cc: {[{https://10.1.0.41:2379  <nil> 0 <nil>}] <nil> <nil>}
I0406 18:51:55.623129       1 clientconn.go:948] ClientConn switching balancer to "pick_first"
I0406 18:52:00.022693       1 trace.go:205] Trace[462926649]: "Update" url:/apis/management.cattle.io/v3/catalogs/bitnami-v3,user-agent:rancher/v0.0.0 (linux/amd64) kubernetes/$Format,client:10.1.0.43 (06-Apr-2021 18:51:25.779) (total time: 34243ms):
Trace[462926649]: ---"About to convert to expected version" 185ms (18:51:00.965)
Trace[462926649]: [34.243241618s] [34.243241618s] END
I0406 18:52:11.612057       1 client.go:360] parsed scheme: "passthrough"
I0406 18:52:11.612121       1 passthrough.go:48] ccResolverWrapper: sending update to cc: {[{https://10.1.0.42:2379  <nil> 0 <nil>}] <nil> <nil>}
I0406 18:52:11.612151       1 clientconn.go:948] ClientConn switching balancer to "pick_first"
I0406 18:52:15.802406       1 client.go:360] parsed scheme: "passthrough"
I0406 18:52:15.803342       1 passthrough.go:48] ccResolverWrapper: sending update to cc: {[{https://10.1.0.43:2379  <nil> 0 <nil>}] <nil> <nil>}
I0406 18:52:15.803368       1 clientconn.go:948] ClientConn switching balancer to "pick_first"
I0406 18:52:27.275601       1 trace.go:205] Trace[1233846543]: "GuaranteedUpdate etcd3" type:*unstructured.Unstructured (06-Apr-2021 18:49:38.249) (total time: 169025ms):
Trace[1233846543]: ---"Transaction prepared" 169004ms (18:52:00.274)
Trace[1233846543]: [2m49.025507363s] [2m49.025507363s] END
I0406 18:52:27.748524       1 client.go:360] parsed scheme: "passthrough"
I0406 18:52:27.748626       1 passthrough.go:48] ccResolverWrapper: sending update to cc: {[{https://10.1.0.41:2379  <nil> 0 <nil>}] <nil> <nil>}
I0406 18:52:27.748650       1 clientconn.go:948] ClientConn switching balancer to "pick_first"
I0406 18:52:37.173286       1 trace.go:205] Trace[1620185678]: "Update" url:/apis/management.cattle.io/v3/catalogs/bitnami-v3,user-agent:rancher/v0.0.0 (linux/amd64) kubernetes/$Format,client:10.1.0.43 (06-Apr-2021 18:52:03.073) (total time: 34099ms):
Trace[1620185678]: [34.099366248s] [34.099366248s] END
I0406 18:52:52.628106       1 client.go:360] parsed scheme: "passthrough"
I0406 18:52:52.628646       1 passthrough.go:48] ccResolverWrapper: sending update to cc: {[{https://10.1.0.42:2379  <nil> 0 <nil>}] <nil> <nil>}
I0406 18:52:52.628665       1 clientconn.go:948] ClientConn switching balancer to "pick_first"
```

**Comment by jonathon2nd** [comment] 2021-04-06 19:45
This only seems to be happening with the bitnami chart.
Adding a copy for testing fails as well, it goes into a refresh state, and trying to change it or refresh it fails.
![image](https://user-images.githubusercontent.com/52681917/113769332-7f75c080-96e6-11eb-8050-774178d0ee56.png)
![image](https://user-images.githubusercontent.com/52681917/113769551-b64bd680-96e6-11eb-8a77-968ee4ee2a86.png)
Adding another chart works fine.
![image](https://user-images.githubusercontent.com/52681917/113769595-c2d02f00-96e6-11eb-9ea0-0ccbe80aba16.png)

**Comment by jonathon2nd** [comment] 2021-04-06 20:10
Used RKE ETCD snapshot-restore to go back to 2.5.5, I upgraded to 2.5.7 about a week ago. The catalog is still not refreshing, and experiencing all of the above still.
From this issue, https://github.com/rancher/rancher/issues/31614, I was thinking it was a bug introduced with 2.5.6, but I guess not. 
![image](https://user-images.githubusercontent.com/52681917/113772341-3293e900-96ea-11eb-81b7-36e27dbf5b2f.png)

**Comment by jonathon2nd** [comment] 2021-04-06 20:40
Reverted back to 2.5.7, cause being at 2.5.5 was not helping. I was using my admin LDAP user. I logged in with the local admin account, and the same issues persist.

I also tried adding the chart with helm v2, same results.
![image](https://user-images.githubusercontent.com/52681917/113775495-6b35c180-96ee-11eb-87a6-f100ef443959.png)

**Comment by jonathon2nd** [comment] 2021-04-06 21:17
I am however, able to add bitnami in the other Rancher UI
![image](https://user-images.githubusercontent.com/52681917/113779527-7b03d480-96f3-11eb-9a0f-c0754b78d6c5.png)
I am assuming this is a Cluster Manager UI bug then?

**Comment by jonathon2nd** [comment] 2021-07-15 19:37
I have upgraded to Rancher 2.5.9, and RKE to 1.2.9. I am still experiencing this issue, even though it should contain the fix, https://github.com/rancher/rancher/issues/33256, https://github.com/rancher/rancher/issues/32938
![image](https://user-images.githubusercontent.com/52681917/125847063-8553909a-dbe3-41a2-b969-feea2058e42a.png)

I am still seeing these logs
```
2021/07/15 19:14:47 [ERROR] error syncing 'bitnami-v3': handler catalog: Timeout: request did not complete within requested timeout 34s, requeuing
W0715 19:16:47.884404       7 warnings.go:80] apiextensions.k8s.io/v1beta1 CustomResourceDefinition is deprecated in v1.16+, unavailable in v1.22+; use apiextensions.k8s.io/v1 CustomResourceDefinition
2021/07/15 19:16:50 [INFO] Updating global catalog bitnami-v3
2021/07/15 19:17:25 [ERROR] error syncing 'bitnami-v3': handler catalog: Timeout: request did not complete within requested timeout 34s, requeuing
2021/07/15 19:19:27 [INFO] Updating global catalog bitnami-v3
W0715 19:19:32.885242       7 warnings.go:80] extensions/v1beta1 Ingress is deprecated in v1.14+, unavailable in v1.22+; use networking.k8s.io/v1 Ingress
2021/07/15 19:20:02 [ERROR] error syncing 'bitnami-v3': handler catalog: Timeout: request did not complete within requested timeout 34s, requeuing
2021/07/15 19:22:04 [INFO] Updating global catalog bitnami-v3
2021/07/15 19:22:39 [ERROR] error syncing 'bitnami-v3': handler catalog: Timeout: request did not complete within requested timeout 34s, requeuing
2021/07/15 19:24:41 [INFO] Updating global catalog bitnami-v3
W0715 19:24:55.887500       7 warnings.go:80] apiextensions.k8s.io/v1beta1 CustomResourceDefinition is deprecated in v1.16+, unavailable in v1.22+; use apiextensions.k8s.io/v1 CustomResourceDefinition
2021/07/15 19:25:16 [ERROR] error syncing 'bitnami-v3': handler catalog: Timeout: request did not complete within requested timeout 34s, requeuing
2021/07/15 19:26:21 [ERROR] Unknown error: Timeout: request did not complete within requested timeout 34s
2021/07/15 19:27:18 [INFO] Updating global catalog bitnami-v3
W0715 19:27:37.892961       7 warnings.go:80] extensions/v1beta1 Ingress is deprecated in v1.14+, unavailable in v1.22+; use networking.k8s.io/v1 Ingress
2021/07/15 19:27:53 [ERROR] error syncing 'bitnami-v3': handler catalog: Timeout: request did not complete within requested timeout 34s, requeuing
2021/07/15 19:29:57 [INFO] Updating global catalog bitnami-v3
W0715 19:30:17.890109       7 warnings.go:80] apiextensions.k8s.io/v1beta1 CustomResourceDefinition is deprecated in v1.16+, unavailable in v1.22+; use apiextensions.k8s.io/v1 CustomResourceDefinition
2021/07/15 19:30:32 [ERROR] error syncing 'bitnami-v3': handler catalog: Timeout: request did not complete within requested timeout 34s, requeuing
W0715 19:31:37.112948       7 warnings.go:80] extensions/v1beta1 Ingress is deprecated in v1.14+, unavailable in v1.22+; use networking.k8s.io/v1 Ingress
2021/07/15 19:32:34 [INFO] Updating global catalog bitnami-v3
```
And seeing CPU spikes because of it.

I have restarted things to no avail, and have tried manually refreshing the catalog with Rancher UI
![image](https://user-images.githubusercontent.com/52681917/125846880-b7c3d5b0-43ce-441e-8eae-eb2a0c517cc2.png)

And with API
```
API Request
cURL command line:
curl -u "${CATTLE_ACCESS_KEY}:${CATTLE_SECRET_KEY}" \
-X POST \
-H 'Accept: application/json' \
-H 'Content-Type: application/json' \
'https://rancher.example.com/v3/catalogs/bitnami-v3?action=refresh'
HTTP Request:
HTTP/1.1 POST /v3/catalogs/bitnami-v3?action=refresh
Host: rancher.example.com
Accept: application/json
Content-Type: application/json
Content-Length: 2

{ }
HTTP Response:
HTTP/1.1 500
content-encoding: gzip
content-length: 135
content-type: application/json
date: Thu, 15 Jul 2021 19:27:09 GMT
expires: Wed 24 Feb 1982 18:42:00 GMT
strict-transport-security: max-age=15724800; includeSubDomains
x-api-schemas: https://rancher.example.com/v3/schemas
x-content-type-options: nosniff

{
"baseType": "error",
"code": "ServerError",
"message": "Timeout: request did not complete within requested timeout 34s",
"status": 500,
"type": "error"
}
```

**Comment by nickgerace** [comment] 2021-08-05 04:50
Hi @jonathon2nd - what Kubernetes version are you using? The upstream fix has been merged as well, but our catalog fix should be working since we dropped the bloated field entirely. There could still be an issue, however.

Have you tried this with a fresh cluster as well?

Upstream: https://github.com/kubernetes/kubernetes/issues/102749

**Comment by nickgerace** [comment] 2021-08-13 20:18
No problem, @jonathon2nd. Would you mind providing the output of this command? (substituting fields as needed)
```sh
kubectl get catalogs.management.cattle.io <your-catalog-here> -o json | wc -c | awk '{print $1/1000"K"}'
```

Looks like our proposed fix did make it in `2.5.9` too: https://github.com/rancher/rancher/pull/33261

**Comment by jonathon2nd** [comment] 2021-08-13 21:12
```
> kubectl get catalogs.management.cattle.io bitnami-v3 -o json | wc -c | awk '{print $1/1000"K"}'
1359.44K
```
This is the catalog: https://charts.bitnami.com/bitnami

When I attempt to refresh the catalog in the UI, nothing happens for a bit till it times out, then
![image](https://user-images.githubusercontent.com/52681917/129418261-91060d48-17bb-43cb-88ca-84d30af50ac0.png)


Which is the same as when I attempt in the API
```
API Request
cURL command line:
curl -u "${CATTLE_ACCESS_KEY}:${CATTLE_SECRET_KEY}" \
-X POST \
-H 'Accept: application/json' \
-H 'Content-Type: application/json' \
'https://rancher.example.com/v3/catalogs/bitnami-v3?action=refresh'
HTTP Request:
HTTP/1.1 POST /v3/catalogs/bitnami-v3?action=refresh
Host: rancher.example.com
Accept: application/json
Content-Type: application/json
Content-Length: 2

{ }
HTTP Response:
HTTP/1.1 500
content-encoding: gzip
content-length: 135
content-type: application/json
date: Fri, 13 Aug 2021 21:04:05 GMT
expires: Wed 24 Feb 1982 18:42:00 GMT
strict-transport-security: max-age=15724800; includeSubDomains
x-api-schemas: https://rancher.example.com/v3/schemas
x-content-type-options: nosniff

{
"baseType": "error",
"code": "ServerError",
"message": "Timeout: request did not complete within requested timeout 34s",
"status": 500,
"type": "error"
}
```


Upon adding another catalog
![image](https://user-images.githubusercontent.com/52681917/129418518-8c7bd9d3-b35a-408a-84a7-0a5e30897ab4.png)

```
2021/08/13 21:06:18 [INFO] Updating global catalog bitnami-test
2021/08/13 21:06:26 [INFO] Updating global catalog bitnami-v3
2021/08/13 21:07:01 [ERROR] error syncing 'bitnami-v3': handler catalog: Timeout: request did not complete within requested timeout 34s, requeuing
2021/08/13 21:08:30 [INFO] Catalog sync done. 99 templates created, 0 templates updated, 0 templates deleted, 0 templates failed
```

Refreshing the new catalog works. Both in UI and API.
Now how do I get the existing catalog to behave?


Also, 
```
> kubectl get catalogs.management.cattle.io bitnami-test -o json | wc -c | awk '{print $1/1000"K"}'
3.059K
> kubectl get catalogs.management.cattle.io bitnami-v3 -o json | wc -c | awk '{print $1/1000"K"}'
1359.44K
```

**Comment by nickgerace** [comment] 2021-08-13 21:27
> Now how do I get the existing catalog to behave?

We designed it such that it _should_ be migrated to the compressed version. Try editing a random field in the catalog yaml, perhaps something superfluous or a chart version you do not use. We want to trigger an update.

**Comment by jonathon2nd** [comment] 2021-08-13 21:37
LOL, wat?
![image](https://user-images.githubusercontent.com/52681917/129420804-8086b13a-fb84-4dca-99fc-73706c54507f.png)

**Comment by jonathon2nd** [comment] 2021-08-13 21:44
Adding a description failed
![image](https://user-images.githubusercontent.com/52681917/129421103-a906ba2c-fddd-432f-9022-b9ee8612a4dd.png)

Do I just start delete status and managedFields, will that work? (Read in from file)

**Comment by nickgerace** [comment] 2021-08-13 21:48
> Do I just delete status and managedFields, will that work? (Read in from file)

I've seen this approach work inconsistently. `etcd` does not like anything nearing ~1.3MB, and the issue is that it's _already_ that size and we are trying to update. I say, go for it with the status field.

**Comment by jonathon2nd** [comment] 2021-08-13 21:55
hmm, even with trimming the managedFields down I am not able to update
![image](https://user-images.githubusercontent.com/52681917/129422017-7ebc1a33-3563-4d78-8fef-ac0f60343033.png)

**Comment by nickgerace** [comment] 2021-08-13 22:08
Did you wipe out the `status` field entirely?

**Comment by jonathon2nd** [comment] 2021-08-13 22:12
Same result.

**Comment by jonathon2nd** [comment] 2021-08-13 22:26
Attempting though CLI
```
$ kubectl --kubeconfig ~/k8s_configs/rancher replace catalogs bitnami-v3 -f ../Downloads/bitnami-v3.yaml
Error from server (Timeout): error when replacing "../Downloads/bitnami-v3.yaml": Timeout: request did not complete within requested timeout 34s
```
Going to see if I can extend the timeout?

**Comment by jonathon2nd** [comment] 2021-08-13 22:37
Na, only client side it seems. I am not seeing a way to change server side, don't even see it.
Not sure what to do at this point? Is there some way to directly update the key in ETCD?

**Comment by nickgerace** [comment] 2021-08-13 23:05
> Not sure what to do at this point? Is there some way to directly update the key in ETCD?

I believe you _can_, but I would not recommend it. I would personally recommend using the new `bitnami` catalog, deleting the old one, and giving it the same name if possible.

I apologize for the inconvenience. While it is triggered by an upstream issue (https://github.com/rancher/rancher/issues/31940#issuecomment-893162018), the catalog is still too large. Fortunately, new and most other catalogs should be fine.

**Comment by jonathon2nd** [comment] 2021-08-17 20:38
> I believe you can, but I would not recommend it. I would personally recommend using the new bitnami catalog, deleting the old one, and giving it the same name if possible.

Yeah, I don't feel like that is an option. I added a test chart, installed an app from it. Deleted and recreated the same chart with the same name and the app is still 'orphaned'. Having a bunch of apps which can no longer be updated/upgraded/changed is far less than ideal.

![image](https://user-images.githubusercontent.com/52681917/129796788-c5f4f1fb-c3c3-4e50-8ee5-a62104e06096.png)

Is there some way to remedy this, manually configure the application to be managed by a catalog?
Looking in the API for the app shows this, but it should work with the new catalog I have already created?

![image](https://user-images.githubusercontent.com/52681917/129797084-91e24c66-1364-4370-8093-c07998fdab83.png)

**Comment by jonathon2nd** [comment] 2021-08-17 20:42
My mistake. I had recreated the catalog in the wrong scope. When I recreate the 'bitnami-test' catalog in the global scope the app is no longer 'orphaned'

![image](https://user-images.githubusercontent.com/52681917/129797308-5a683758-31b9-4b3d-9f45-a2899e4c119d.png)

Ok, this will work. Thank you @nickgerace, I greatly appreciate the assistance!

I am nervous to do this to all the apps lol. Will have to go though and backup all the clusters just incase, though it should be fine.

**Closed** 2021-08-17 20:44 UTC

**Comment by nickgerace** [comment] 2021-08-17 20:47
Sounds good, @jonathon2nd! No worries; I am thankful that you worked with me to ensure that there was not a regression. This was a performance enhancement that was not your fault, so your patience is greatly appreciated. Please feel free to file new issues or talk in the Rancher Users Slack as always.
