### ISSUE TITLE
[2.4.2] cattle-cluster-agent goes unhealthy, clusters show up in Rancher as "Unavailable"

### ISSUE THREAD

**Issue by Oats87** [rancher/rancher#26613] opened 2020-04-13 16:17 UTC
**What kind of request is this (question/bug/enhancement/feature request):** Bug

**Steps to reproduce (least amount of steps as possible):**

Difficult to determine precise steps for reproducing. We took the path of provision new K8s 1.17.4 cluster, and let it sit for > 10 days. Eventually, the cluster went unavailable and the `cattle-cluster-agent` logs showed: `watch of *summary.SummarizedObject ended with: unexpected object:`

**Other details that may be helpful:**

```
W0413 15:27:31.112849       1 reflector.go:326] github.com/rancher/steve/pkg/clustercache/controller.go:187: watch of *summary.SummarizedObject ended with: unexpected object: &{{{Status v1} {      0 0001-01-01 00:00:00 +0000 UTC <nil> <nil> map[] map[] [] []  []}} }
W0413 15:36:11.421095       1 reflector.go:326] github.com/rancher/steve/pkg/clustercache/controller.go:187: watch of *summary.SummarizedObject ended with: unexpected object: &{{{Status v1} {      0 0001-01-01 00:00:00 +0000 UTC <nil> <nil> map[] map[] [] []  []}} }
W0413 15:36:23.141545       1 reflector.go:326] github.com/rancher/steve/pkg/clustercache/controller.go:187: watch of *summary.SummarizedObject ended with: unexpected object: &{{{Status v1} {      0 0001-01-01 00:00:00 +0000 UTC <nil> <nil> map[] map[] [] []  []}} }
W0413 15:50:48.470615       1 reflector.go:326] github.com/rancher/steve/pkg/clustercache/controller.go:187: watch of *summary.SummarizedObject ended with: unexpected object: &{{{Status v1} {      0 0001-01-01 00:00:00 +0000 UTC <nil> <nil> map[] map[] [] []  []}} }
W0413 15:51:27.245361       1 reflector.go:326] github.com/rancher/steve/pkg/clustercache/controller.go:187: watch of *summary.SummarizedObject ended with: unexpected object: &{{{Status v1} {      0 0001-01-01 00:00:00 +0000 UTC <nil> <nil> map[] map[] [] []  []}} }
W0413 15:59:11.566124       1 reflector.go:326] github.com/rancher/steve/pkg/clustercache/controller.go:187: watch of *summary.SummarizedObject ended with: unexpected object: &{{{Status v1} {      0 0001-01-01 00:00:00 +0000 UTC <nil> <nil> map[] map[] [] []  []}} }
W0413 16:07:32.347236       1 reflector.go:326] github.com/rancher/steve/pkg/clustercache/controller.go:187: watch of *summary.SummarizedObject ended with: unexpected object: &{{{Status v1} {      0 0001-01-01 00:00:00 +0000 UTC <nil> <nil> map[] map[] [] []  []}} }
```

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): 2.4.2
- Installation option (single install/HA): HA

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): Custom
- Machine type (cloud/VM/metal) and specifications (CPU/memory): Not Relevant 
- Kubernetes version (use `kubectl version`): 1.17.4

**Comment by Konpon96** [comment] 2020-04-14 09:34
Having exactly the same problem with Rancher 2.4.2 after upgrading. On top of that, there seems to be a memory leak on the cluster agent pod which ends up in consuming the whole RAM of the machine, rendering it unusable:

![2020-04-13](https://user-images.githubusercontent.com/4958634/79209252-70499300-7e43-11ea-8499-f995c52d7ba5.png)

Just as @Oats87 wrote, there doesn't seem to be much happening in the pod itself, it barely logs one line every 5 minutes, but it's always exactly the same line - with `summary.SummarizedObject ended with: unexpected object`.

**Comment by dramich** [comment] 2020-04-16 00:28
This is a duplicate of https://github.com/rancher/rancher/issues/26633, closing.

**Closed by dramich** 2020-04-16 00:28 UTC
Labels: [zube]: Next Up

**Comment by aavileli** [comment] 2020-04-23 01:57
Is there a fix for this. Did the memory leak been identified.
Eks clusters show up in Rancher as "Unavailable" Restarting cattle node agent and rancher is not a solution
