### ISSUE TITLE
[cli] stack variable doesn't matter

### ISSUE THREAD

**Issue by peceka** [rancher/rancher#5600] opened 2016-08-01 11:02 UTC
**Rancher Version:**
v1.1.2

**Rancher CLI:**
v0.0.1 (downloaded from https://github.com/rancher/cli/releases)

When doing:
[gitlab-runner@git2-prod docker]$ rancher --stack test --debug up --pull --upgrade --confirm-upgrade

rancher doesn't care about setting stack and takes directory name as stack name:

DEBU[0000] Environment Context from file : map[]
DEBU[0000] Opening compose files: docker-compose.yml
DEBU[0000] Opening rancher-compose file: /home/gitlab-runner/builds/a56e360e/0/project/project/docker/rancher-compose.yml
DEBU[0000] [0/1] [app]: Adding
DEBU[0000] Looking for stack docker
DEBU[0000] Found stack: docker(1e25)
DEBU[0000] Launching action for app
DEBU[0000] Project [docker]: Creating project
INFO[0000] [0/1] [app]: Creating
DEBU[0000] Finding service app
DEBU[0000] Found service app
INFO[0000] [0/1] [app]: Created
DEBU[0000] Project [docker]: Project created
DEBU[0000] Launching action for app
DEBU[0000] Project [docker]: Starting project
INFO[0000] [0/1] [app]: Starting
DEBU[0000] Finding service app
DEBU[0000] Found service app
DEBU[0000] Comparing hashes for app: old: digest.ServiceHash{Service:"2efbf44df214fef32780e1a6b9df6f8e68204969", LaunchConfig:"7db9512325e67ef6c22c8ea2f7ff3d84f828e8bc", SecondaryLaunchConfigs:map[string]string{}} new: digest.ServiceHash{Service:"2efbf44df214fef32780e1a6b9df6f8e68204969", LaunchConfig:"ae048cf6557c89b775edb1d11678cb70d9087579", SecondaryLaunchConfigs:map[string]string(nil)}
INFO[0001] Finished pulling git:5005/project/project:tag
DEBU[0001] Finding service app
DEBU[0001] Found service app
ERRO[0001] Failed Starting app : Service app must be state=active or inactive to upgrade, currently: state=activating
ERRO[0001] Failed to start: app : Service app must be state=active or inactive to upgrade, currently: state=activating
FATA[0001] Service app must be state=active or inactive to upgrade, currently: state=activating

**Comment by deniseschannon** [comment] 2016-08-18 22:27
We changed where the stack flag is in the `up` and it was verified in v0.1.0-rc2. 

Pre-duplicate of https://github.com/rancher/rancher/issues/5674, which is now closed.

**Closed by deniseschannon** 2016-08-18 22:27 UTC
Labels: area/cli
