### ISSUE TITLE
Fluentd target logging cert disappear after click test button

### ISSUE THREAD

**Issue by aiwantaozi** [rancher/rancher#17782] opened 2019-01-31 09:17 UTC
In fluentd logging target, use the edit as file, input cert, click save, then click test, the cert dissapeared

**Comment by n313893254** [comment] 2019-06-18 03:10
1. It disappears in the first time to click save.
2. After refresh action is done, the logging cert will show again.

**Comment by davidnuzik** [comment] 2019-06-27 22:54
@aiwantaozi @n313893254 I am not reproducing in v2.2.4; should I use another version? Or is there a specific way I need to plug in my cert in the UI? which one will disappear? all three?

Need more details please. Thanks.
![Screen Shot 2019-06-27 at 3 54 03 PM](https://user-images.githubusercontent.com/45179589/60306117-ddf7f300-98f3-11e9-9e96-50b68da54634.png)

**Comment by n313893254** [comment] 2019-06-28 02:46
@davidnuzik I use master version to reproduce and I think v2.2.4 can reproduce too. All three will disappear. And Only the first time enable logging will reproduce. 

steps:
1. Add a new project in cluster project/namespace page.
2. Go to the new project logging page.
3. Select fluentd logging target, use the edit as file, input cert, click save.

Result: When the page is refreshing, the cert disappear. And after refreshing, the cert display in the input. 

So make sure the refreshing time is long for a human to see change.

**Comment by davidnuzik** [comment] 2019-06-28 22:04
Is cert being plugged into the text editor?
This is what I am doing:
![Screen Shot 2019-06-28 at 3 02 38 PM](https://user-images.githubusercontent.com/45179589/60373677-dac53b80-99b5-11e9-8238-ab61719e3676.png)

I followed your suggested steps (project level instead of cluster level logging). v2.2.4
I tried the first time as you suggested only first time will repro. I did not repro still. The certificates stay there for my in my Chrome browser window.

**Comment by davidnuzik** [comment] 2019-06-28 22:14
Disappears from text editor? (edit as file area) or the area where we add the actual certificate file contents?

**Comment by n313893254** [comment] 2019-07-01 04:16
![image](https://user-images.githubusercontent.com/18737885/60410048-d3da3b00-9bf8-11e9-8f95-4da8e0ec8c8d.png)

![image](https://user-images.githubusercontent.com/18737885/60410037-c9b83c80-9bf8-11e9-8e18-33e2de69282c.png)

I input the cert by keyboard and using v2.2.4. 
The cert disappears from the text editor and the area where we add the actual certificate file contents.
Sometimes I cannot repro too. So I add a debugger in here: https://github.com/rancher/ui/blob/3da10991b1246e96a2f34305b1ad4a537400f597/lib/logging/addon/logging/route.js#L58

**Comment by n313893254** [comment] 2019-07-01 04:18
And cluster level can also repro, but it needs to add a new cluster. So I suggest using project-level to repro will be more convenient.

**Comment by davidnuzik** [comment] 2019-07-02 22:11
Thanks for the additional steps. I had been reading from file for certs, so copy and pasted in this time. Still not reproducing. I'm going to see if @sangeethah has any recommendations. I've tried everything I can think of now and have not once reproduced in v2.2.4.

That said, the fix doesn't appear to be hurting anything.

**Comment by davidnuzik** [comment] 2019-07-15 22:51
We are closing this issue; this was tested numerous times. While I was unable to reproduce I can say with certainty that no UI issues were identified with the fix.

Every time I test the certificates stay in place.

**Closed by davidnuzik** 2019-07-15 22:51 UTC
Labels: [zube]: To Test, area/logging, area/ui, kind/bug-qa, priority/0, team/ui
