### ISSUE TITLE
"Netsplit" of overlay network

### ISSUE THREAD

**Issue by hhucke** [rancher/rancher#8324] opened 2017-03-28 12:54 UTC
Hallo all.

The company I'm working with runs a partly rancher controlled "docker network" which hosts diverse services. Within one and a  half weeks we had the so far not reproducible situation (possibly related with high load situations) that there were "network splits" in the overlay network.
I assume that they were caused by hiccups of a IPSec rancher-agent instance because when I restarted the obviously responsible instance the whole installation returned to the expected behaviour and formerly disturbed connections - within the overlay network - worked again.

**Rancher Versions:** 1.1.0
Server: ???
healthcheck: ???
ipsec: ???
network-services: ???
scheduler: ???
kubernetes (if applicable):

**Docker Version:** 1.12.3

**OS and where are the hosts located? (cloud, bare metal, etc):** Ubuntu 16.04.1 LTS (cloud)

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
    dockerized Racnher with external DB

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
    AFAIK Swarm

**Steps to Reproduce:**
    None

**Results:** 
    (None)

**Comment by vincent99** [comment] 2017-03-28 16:02
A good place to start would be upgrading, as you are on a 10-month old release (and not even the newest patch release).  Everything relevant has significantly changed since then.  We can only  provide community support for recent releases, and even commercial support for 1.1(.4) ends soon.

**Comment by hhucke** [comment] 2017-03-30 10:42
Would be feasible if I would be the administrator of the installation.

Even the information that it's an already known error in a number of older versions would help. But it doesn't make sense to thrive the company towards an update/upgrade without being sure that this error is fixed.

**Comment by vincent99** [comment] 2017-03-30 19:03
There are may things that could be wrong so I can't tell you if something you can't reproduce is a known problem or fixed or not.  But all the relevant services have been significantly changed and/or rewritten since then.

The container world changes quickly and using old software is a recipe for failure.  For example Docker 1.12 didn't exist at the time the Rancher version you're using was released.

**Comment by superseb** [comment] 2017-05-25 08:30
@hhucke Thanks for reporting but without any reproducible situation, and/or related logging we can only guess where it's going wrong. 

Definitely upgrading would be a good first step, closing for now, let me know if you need anything else or file a new issue so we can take a look.

**Closed by superseb** 2017-05-25 08:30 UTC
