### ISSUE TITLE
[BUG] Upgrading Kubernetes Version does not retain RKE User Addons

### ISSUE THREAD

**Issue by jakefhyde** [rancher/rancher#38446] opened 2022-07-27 19:33 UTC
**Rancher Server Setup**
- Rancher version: v2.6.6

**Information about the Cluster**
- Cluster Type (Local/Downstream): Downstream
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider): RKE1

**Describe the bug**

When upgrading Kubernetes Version for Rancher provisioned clusters, the RKE User Addons job is not replaced, which means that addons will not be retained if overwritten by RKE's other jobs.  

**To Reproduce**

- Add the following under `rancherKubernetesEngineConfig`
```
addons: |-
    ---
    apiVersion: v1
    kind: ConfigMap
    metadata:
      name: coredns
      namespace: kube-system
    data:
      Corefile: |
        .:53 {
            errors
            health {
              lameduck 5s
            }
            ready
            kubernetes cluster.local in-addr.arpa ip6.arpa {
              pods insecure
              fallthrough in-addr.arpa ip6.arpa
              ttl 30
            }
            forward . "/etc/resolv.conf"
            cache 30
            loop
            reload
            loadbalance
        }
```
- After deployment, verify coredns config map has the corefile as intended
- Edit cluster and upgrade the Kubernetes version

**Result**

CoreDNS config map has returned to default

**Expected Result**

CoreDNS config map persists changes

**Additional context**

SURE-3508

**Comment by markusewalker** [comment] 2022-09-15 17:45
Closing this issue as a duplicate of https://github.com/rancher/rancher/issues/38703.

**Closed by markusewalker** 2022-09-15 17:45 UTC
Labels: kind/bug, priority/0, internal, [zube]: Working, QA/XS, team/area2, JIRA, v2.7.0
