### ISSUE TITLE
Unable to attach volumes to pod, "has no NodeID annotation" error

### ISSUE THREAD

**Issue by tempman5** [rancher/rancher#31673] opened 2021-03-12 08:40 UTC
Hi,

I think that this is not a bug, as you can configure trident driver installation for doing it in a different default path. But my current platform is generating a problem for me because I'm trying change Operating System.

Current platform is RancherOS with /opt/rke/var/lib/kubelet path use. Rancher version is 2.4.10, k8s is 1.17.13, trident driver version is 19.10.0 with a custom-yaml for putting RancherOS kubelet path indicated previously.

What's the problem? We are changing Operating System in a new worker node to Ubuntu Server 20.04. It enters well as Active in the cluster, but not attach current volumes. If I run kubectl describe -n trident pod trident-csi-xxx (trident pod from new worker node with Ubuntu) it shows the next error:

  Warning  FailedMount  14m (x1140 over 45h)    kubelet, xxx-docker1  MountVolume.SetUp failed for volume "registration-dir" : hostPath type check failed: /opt/rke/var/lib/kubelet/plugins_registry/ is not a directory

It happens because Ubuntu has kubelet in /var/lib/ and not in /opt/rke (rke dir doesn't exist). If I create manually the dir, duplicate the files/dirs and I create a symlink it is not working...

I've searched in Google about this and people has a kubeadm.conf file for changing root-dir of kubelet, but I don't have this file, not sure as kubelet is running at system starting. It is not under systemd. K8s installation is done automatically when adding new node to the cluster with the command offered by Rancher. The command is:

sudo docker run -d --privileged --restart=unless-stopped --net=host -v /etc/kubernetes:/etc/kubernetes -v /var/run:/var/run rancher/rancher-agent:v2.4.10 --server https://rancher.xxx.xx:5443 --token xxxxxxxxx --ca-checksum xxxxxxxxxx --worker
 
Subject error indicated in this thread is when I try run a pod in this new worker node, it is showed in the pod events. We want migrate RancherOS to Ubuntu Server in both worker and master nodes.

Thanks beforehand.

**Comment by tempman5** [comment] 2021-03-15 09:14
Some help for this please? Thanks beforehand.

**Comment by superseb** [comment] 2021-04-16 14:22
Duplicate of https://github.com/rancher/rke/issues/2486

**Closed by superseb** 2021-04-16 14:22 UTC
