### ISSUE TITLE
Bug: Incorrect public IP got displayed after stop/start a EC2 instance

### ISSUE THREAD

**Issue by zhang8473** [rancher/rancher#5302] opened 2016-06-30 19:50 UTC
Rancher server can connect to the name instance but the displayed public IP is incorret. AWS arranged a new public IP but the rancher UI does not catch it.
![image](https://cloud.githubusercontent.com/assets/5016962/16502011/28bdeea2-3ec1-11e6-8579-1e052c762fbd.png)

**Comment by tfiduccia** [comment] 2016-06-30 23:09
@zhang8473 this is a duplicate of #388 
There is a documented work-around that you can use:
http://docs.rancher.com/rancher/faqs/troubleshooting/#what-do-i-do-if-the-ip-of-my-host-has-changed-due-to-reboot

**Closed by tfiduccia** 2016-06-30 23:09 UTC
