### ISSUE TITLE
Project members cannot create namespace in the UI when there's no namespaces in the project

### ISSUE THREAD

**Issue by gitlawr** [rancher/rancher#36088] opened 2022-01-10 08:42 UTC
**Rancher Server Setup**
- Rancher version: v2.6.3
- Installation option (Docker install/Helm Chart):

**Information about the Cluster**
- Kubernetes version: v1.21.7+rke2r2
- Cluster Type (Local/Downstream): downstream provisioned by EC2 node driver.

**To Reproduce**
1. Log in as the admin. Provision a EC2 cluster.
2. Add a new user(e.g. user1)
3. Set user1 as a "Cluster Member" of the cluster.
3. Create a new project(e.g. project1) in the cluster.
4. Add user1 to this project as Project Member
5. Login as user1 and navigate to Explorer -> Cluster -> Projects/Namespaces

**Result**
1. There's no `Create Namespace` button in the UI.
2. user1 has the namespace creation permission:
```
$kubectl auth can-i create namespace --as <user-id>
yes
```
3. As the admin, create a new namespace in project1, the `Create Namespace` button immediately show up in user1's view.

**Expected Result**
Be able to create new namespaces in the UI as a project member.

**Comment by guangbochen** [comment] 2022-01-12 12:34
seems identical with the https://github.com/rancher/rancher/issues/35453

**Comment by cbron** [comment] 2022-03-08 19:59
Closing, dupe of: https://github.com/rancher/rancher/issues/35453

**Closed** 2022-04-14 17:39 UTC
Labels: kind/bug, [zube]: Next Up, team/ui, area/harvester
