### ISSUE TITLE
Per_container scoped volume

### ISSUE THREAD

**Issue by StrongMonkey** [rancher/rancher#8683] opened 2017-05-05 20:30 UTC
Steps to reproduce:
1 . Create a service using the following yaml file.
```
sion: '2'
volumes:
  daishan-re:
    driver_opts:
      size: '10'
    driver: rancher-ebs
    per_container: true
services:
  coo:
    image: ubuntu
    stdin_open: true
    volumes:
    - daishan-re:/mydata
    labels:
      io.rancher.sidekicks: test-data
  test-data:
    image: ubuntu:14.04.2
    stdin_open: true
    volumes:
    - daishan-re:/mydata
    tty: true
    command:
    - cat
```
2. Upgrade service, by specifying an invalid option to it.(Example: logger_driver: 123). This will cause service failed to upgrade.
3. The existing volume will be deleted. A new volume( with the new DeploymentUUID name) will be created. User will lose data from the previous volume.

This is reproducible very consistently with container_scoped volume. Seems like the container_scoped volume is specifically bind to a deploymentUUID. Once the deployementUUID is changed during the upgrade, the volume will be deleted, which is not desired.

**Comment by StrongMonkey** [comment] 2017-05-05 20:56
@cjellick Assign this to us as i think this might require a big change in cattle.

**Comment by aemneina** [comment] 2017-05-09 01:07
Not sure if this is related: https://github.com/rancher/rancher/issues/7271

**Comment by deniseschannon** [comment] 2017-05-09 16:17
Duplicate of #7271

**Comment by soumyalj** [comment] 2017-05-09 18:41
This is not a duplicate.

**Comment by deniseschannon** [comment] 2017-05-19 04:06
When re-factoring is added into master, we should re-test this.

**Comment by tfiduccia** [comment] 2017-10-05 22:08
Re-test when volume support is implemented.

**Comment by m4ce** [comment] 2018-03-30 07:13
Just a quick note - per_container is nowhere documented on the official rancher docs (http://rancher.com/docs/rancher/v1.6/en/cattle/volumes/). It might be good to document this as it is quite an important feature!

**Comment by eugenevd** [comment] 2018-04-05 21:14
I agree with @m4ce - it would be appreciated

**Comment by deniseschannon** [comment] 2018-09-13 17:18
Not relevant with the refactored 2.0 work. 

With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.

**Closed by deniseschannon** 2018-09-13 17:18 UTC
Labels: area/container-refactoring, area/storage, kind/bug, priority/-1, status/to-test, version/2.0

**Comment by BGaunitz** [comment] 2019-08-15 18:49
Hi,

I experienced the same issue in Rancher 1.6.28 and can confirm that the per_container volumes are recreated with different name on failure (as @StrongMonkey explained). 

I would also consider this behavior extremely critical as it affects essential functions of a stack by not being able to scale services with a separate volume per container, respectively having the possibility of losing data eventually.

I assume the bug might be in the following code snippet, as the UUID is used within the name to find existing volumes and that UUID changes on deployment, therefore the volume is recreated on the host.
```
if (template.getPerContainer()) {
    String name = stack.getName() + "_" + volumeNamePostfix + "_" + this.unit.getServiceIndex() + "_"
            + uuid + "_";
    // append 5 random chars
    List<? extends Volume> volumes = context.objectManager
            .find(Volume.class, VOLUME.ACCOUNT_ID, service.getAccountId(),
                    VOLUME.REMOVED, null, VOLUME.VOLUME_TEMPLATE_ID, template.getId(), VOLUME.STACK_ID,
                    stack.getId(), VOLUME.DEPLOYMENT_UNIT_ID, unit.getId());
    for (Volume vol : volumes) {
        if (vol.getName().startsWith(name)) {
            volume = vol;
            break;
        }
    }
```

[File in Cattle Repository](https://github.com/rancher/cattle/blob/6cd0557e166f38898189e72756e6afae56ce0b49/code/iaas/service-discovery/server/src/main/java/io/cattle/platform/servicediscovery/deployment/impl/unit/DeploymentUnit.java#L422)

![picturemessage_td4ukvst 2xz](https://user-images.githubusercontent.com/12612362/63118377-f7392980-bf9d-11e9-9c66-f4ee555e9655.png)

Best regards, Benjamin
