### ISSUE TITLE
[CLI] make fails with https call

### ISSUE THREAD

**Issue by coke** [rancher/rancher#9365] opened 2017-07-17 20:31 UTC
**Rancher versions:**
rancher/server:
rancher/agent:

**Infrastructure Stack versions:**
healthcheck:
ipsec:
network-services:
scheduler:
kubernetes (if applicable):

**Docker version: (`docker version`,`docker info` preferred)**
Client:
 Version:      17.06.0-ce
 API version:  1.30
 Go version:   go1.8.3
 Git commit:   02c1d87
 Built:        Fri Jun 23 21:31:53 2017
 OS/Arch:      darwin/amd64
**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
$ sw_vers
ProductName:	Mac OS X
ProductVersion:	10.12.5
BuildVersion:	16F73
$ uname -r
16.6.0
**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**

**Steps to Reproduce:**

Download rancher/cli on master (8520534a2717b0d1e6c9a0097a3482a7612616bf)

make

dies with:

Step 2/15 : RUN apt-get update &&     apt-get install -y xz-utils zip rsync
 ---> Running in 2751c479aaf7
E: The method driver /usr/lib/apt/methods/https could not be found.
The command '/bin/sh -c apt-get update &&     apt-get install -y xz-utils zip rsync' returned a non-zero code: 100
FATA[0615] exit status 100
make: *** [ci] Error 1

**Results:**

Can't build. Probably needs 'apt-get install apt-transport-https' to be run before the other installs.

**Comment by superseb** [comment] 2017-08-02 12:49
Just tried to build using `make` on Docker for Mac and Docker 17.03 on CentOS, both succeeded. Maybe some local images/cache interferring, or maybe some proxy settings? Closing as this is not a bug but please respond if you need help.

**Closed by superseb** 2017-08-02 12:49 UTC
