### ISSUE TITLE
Unable to enable external authentication when switching to new ADFS server

### ISSUE THREAD

**Issue by nickngch** [rancher/rancher#26668] opened 2020-04-17 01:25 UTC
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
1. Enabled external authentication on original ADFS server
2. Disable external authentication
3. Enable external authentication on new ADFS server

**Result:**
Error "Logging in failed: Your account may not be authorized to log in."

**Other details that may be helpful:**
Usually, remove `adfs_user `under `principalIds` by `kubectl edit users` would solve the issue but in this particular case, we still hit the error after cleaning old `adfs_user` record in users.

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): v2.3.5
- Installation option (single install/HA): HA

**Comment by luthermonson** [comment] 2020-05-05 07:29
This ultimately came down to a problem with crewjam/saml fork we have still persisting a bug where you can't put in a saml provider with multiple certs. They've actually fixed this now here: https://github.com/crewjam/saml/issues/192 and perhaps it's time to look at crewjam/saml and see if the updates made to it do not warrant us using a branch any more or at least get this patched into our branch.

**Comment by jgallucci32** [comment] 2020-11-22 20:24
This seems like a significant issue which should be posted as a warning in the AD FS documentation for Rancher. This means in large organizations which rely on the rolling of certificates for smooth transitions, Rancher will only be available 11 out of 12 months a year given it usually takes a month to roll them.

**Comment by makeacode** [comment] 2020-12-28 17:39
I just got bit by this....our AD FS server also uses 2 signing certificates for rotation purposes as mentioned by @jgallucci32.  I managed to get around the rancher problem by removing the older of the signing certificates from the federationmetadata.xml that i uploaded to rancher when enabling SAML.

**Comment by deniseschannon** [comment] 2021-01-31 01:55
@paynejacob With the latest updates to the latest SAML library, this might be fixed

**Comment by paynejacob** [comment] 2021-03-04 20:22
Tested with 88306e1c1670 I was able to switch between 2 different adfs instances on 2 different domains.  Users were able to log in with both servers.

**Comment by izaac** [comment] 2021-03-19 19:00
Rancher version `v2.5.7` 
I can switch ADFS servers without issues.

But I couldn't reproduce on `v2.5.5`, `v2.4.15` with our QA environments. Is this only reproducible when using multiple certificates then @luthermonson @paynejacob ?

**Comment by deniseschannon** [comment] 2021-04-12 19:15
@izaac when switching, did you make changes to the ADFS backend so they weren't identical?

**Comment by izaac** [comment] 2021-04-12 20:41
@deniseschannon I used two different ADFS servers to test the changes. Each had a different domain although I'm not sure if the certificate had a wildcard, if that's the difference you're talking about.. But @paynejacob might have more tech details about the setups.

**Comment by sowmyav27** [comment] 2021-04-16 19:39
Closing this as we were not able to reproduce as mentioned https://github.com/rancher/rancher/issues/26668#issuecomment-803046785 and https://github.com/rancher/rancher/issues/26668#issuecomment-818204913

**Closed by sowmyav27** 2021-04-16 19:39 UTC
Labels: QA/S, QA/need-info, [zube]: To Test, internal
