### ISSUE TITLE
Should not delete the cattle-system namespace when deleting the imported k8s cluster when Rancher pod is running in it

### ISSUE THREAD

**Issue by guangbochen** [rancher/rancher#33800] opened 2021-07-28 15:25 UTC
**Rancher Server Setup**
- Rancher version: master-head

**Describe the bug**
When deleting the imported k8s cluster from the Rancher it will delete all the resources and the namespace of the `cattle-system`, but this will cause an issue of the imported k8s cluster if it has extra resources that exist in the same `cattle-system` namespace, e.g, in the Harvester cluster we run embedded Rancher in this namespace which should not get removed by the Rancher.

**To Reproduce**
1. import an existing k8s cluster to the Rancher server.
2. delete the imported k8s cluster
3. the `cattle-system` namespace  and its resources is removed completely 

**Result**
- resources in the same namespace will also get deleted.

**Expected Result**
should keep the other resource and the `cattle-system` namespace, probably only delete the cluster-agent node.

**Comment by deniseschannon** [comment] 2021-08-19 04:47
QA should test removing an importing cluster and re-importing to ensure a cluster could still be imported.

**Comment by guangbochen** [comment] 2021-08-19 10:05
verified using the `master-head-08-19` version:
1. imported a downstream Harvester/k8s cluster via the `Importing Existing` option
2. the cluster explorer is ready
3. delete the imported cluster and all resources have remained (the downstream cluster must have embedded rancher installed on the `cattle-system` namespace)
4. reimporting the same cluster again and the cluster explorer still working as expected.

![image](https://user-images.githubusercontent.com/4569037/130049733-db0a1786-0816-4ab1-839f-e2d7068bd078.png)

**Comment by deniseschannon** [comment] 2021-08-19 15:10
@kravciak Can you do one additional validation? I believe the change we made only keeps the cattle system namespace IF Rancher is running on the imported cluster.

Can you validate that removing a regular imported cluster cleans up the `cattle-system` namespace?

**Comment by deniseschannon** [comment] 2021-08-19 15:10
@dnoland1 Do you think this change will affect the hosted Rancher use case at all?

**Comment by dnoland1** [comment] 2021-08-19 15:40
@deniseschannon I don't think it will, but can test. Does "imported k8s cluster" include k3s clusters that have been imported?

**Comment by deniseschannon** [comment] 2021-08-19 15:46
Yes, I would assume so @dnoland1

**Comment by kravciak** [comment] 2021-08-20 12:43
@deniseschannon pods are not cleaned from cattle-system namespace after cluster removal

I did:
- run v2.6-head (b3980c2) docker single node rancher
- import k3s cluster `Import Existing -> Generic`
- wait until all pods on k3s are running after import
- remove k3s cluster from dashboard UI

I tried to reproduce on v2.6.0-rc2 but it behaves the same, cattle-system namespace is not removed from k3s cluster (and deleted cluster keeps popping back in dashboard as `Removing, scheduled for deletion`)

```
kubectl get pods -A
NAMESPACE             NAME                                      READY   STATUS      RESTARTS   AGE
kube-system           local-path-provisioner-5ff76fc89d-cxm5w   1/1     Running     0          6m33s
kube-system           coredns-7448499f4d-r7b4j                  1/1     Running     0          6m33s
kube-system           helm-install-traefik-crd-pjv9m            0/1     Completed   0          6m33s
kube-system           helm-install-traefik-mfn72                0/1     Completed   0          6m33s
kube-system           metrics-server-86cbb8457f-jpfqk           1/1     Running     0          6m33s
kube-system           svclb-traefik-t7d8t                       2/2     Running     0          6m17s
kube-system           traefik-97b44b794-9wx8s                   1/1     Running     0          6m17s
cattle-system         cattle-cluster-agent-5977659645-lxddk     1/1     Running     0          4m30s
cattle-fleet-system   fleet-agent-68c987f6-wgpdf                1/1     Running     0          3m51s
```

**Comment by sowmyav27** [comment] 2021-08-20 23:24
**On 2.6.0-rc1**

- Import a k3s cluster
- Delete it from Rancher
- cattle-cluster-agent pod is seen deleted from the cluster.

```
 kubectl get pods -A
NAMESPACE             NAME                                      READY   STATUS      RESTARTS   AGE
kube-system           local-path-provisioner-5ff76fc89d-m9mxf   1/1     Running     0          5m1s
kube-system           metrics-server-86cbb8457f-zd7bc           1/1     Running     0          5m1s
kube-system           coredns-6488c6fcc6-jtnnr                  1/1     Running     0          5m1s
kube-system           helm-install-traefik-gn8cc                0/1     Completed   0          5m1s
kube-system           svclb-traefik-7x2zz                       2/2     Running     0          4m42s
kube-system           svclb-traefik-njtv7                       2/2     Running     0          4m42s
kube-system           svclb-traefik-2bl9l                       2/2     Running     0          4m42s
kube-system           traefik-6f9cbd9bd4-hz4jm                  1/1     Running     0          4m42s
cattle-fleet-system   fleet-agent-7fd89c96df-7zmd6              1/1     Running     0          3m51s
```
- cattle-system Namespace seems to have gotten deleted
```
kubectl get namespaces
NAME                          STATUS   AGE
local                         Active   4m5s
kube-node-lease               Active   5m33s
default                       Active   5m33s
kube-public                   Active   5m33s
cattle-fleet-system           Active   4m26s
cattle-impersonation-system   Active   4m41s
kube-system                   Active   5m33s
```

**On 2.6-head commit id: `24e5435`**
- Import a k3s cluster
- Delete it from Rancher
- cattle-cluster-agent pod is seen deleted from the cluster.
- The clean up pod errors out
- cattle-system namespace is seen in terminating state
```
kubectl logs cattle-cleanup-c5hc9-55nbr -n default
time="2021-08-20T23:21:53Z" level=info msg="Starting sleep for 1 min to allow server time to disconnect...."
time="2021-08-20T23:21:53Z" level=warning msg="failed to reconcile kubelet, error: Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?"
time="2021-08-20T23:21:53Z" level=info msg="Listening on /tmp/log.sock"
time="2021-08-20T23:22:53Z" level=info msg="Starting cluster cleanup"
time="2021-08-20T23:22:53Z" level=fatal msg="checking for cattle-system/rancher service: services \"rancher\" is forbidden: User \"system:serviceaccount:default:cattle-cleanup-l77bw\" cannot get resource \"services\" in API group \"\" in the namespace \"cattle-system\""
```

**Comment by cmurphy** [comment] 2021-08-23 18:50
Can I get clarification on the expected outcome - is the correct outcome for imported clusters that do *not* have rancher running in them that the `cattle-system` namespace *should* be deleted - the opposite of what the issue title says? And the current problem is that it is being partly deleted but stuck in a `Terminating` state?

**Comment by deniseschannon** [comment] 2021-08-23 21:19
Two use cases:

1. Original use case: Import k8s cluster. When removing the cluster from Rancher, it should clean up the cattle-system namespace. 
2. New use case to support: Import k8s cluster that has rancher running in the cattel-system-namspace. (Harvester use case). When removing the "Harvester" cluster from Rancher, it shouldn't clean up the cattle-system namespace

**Comment by cmurphy** [comment] 2021-08-24 20:30
Ready to test on 2.6

**Comment by guangbochen** [comment] 2021-08-25 07:46
Re-tested using the `master-head-390a336`, deleting the imported harvester cluster will not clean up the `cattle-system` namespace and resources, also re-importing the deleted cluster also works, thanks.

**Comment by deniseschannon** [comment] 2021-08-25 09:31
@guangbochen can you re-test with v2.6-head as the changes for master have not been merged.

**Comment by guangbochen** [comment] 2021-08-25 10:35
> @guangbochen can you re-test with v2.6-head as the changes for master have not been merged.

ditto, it works in `v2.6-head`, thanks.

**Comment by kravciak** [comment] 2021-08-25 13:29
I imported 2 k3s clusters, one clean and one with rancher running.
Cattle-system ns is nore deleted after removal from UI on any of them.

After removal from rancher state is:
```
# clean k3s
~> kubectl get pods -n cattle-system
NAME                                    READY   STATUS    RESTARTS   AGE
cattle-cluster-agent-857c8b5694-prstq   1/1     Running   0          25m

# k3s with rancher
~> kubectl get pods -n cattle-system
NAME                                    READY   STATUS      RESTARTS   AGE
cattle-cluster-agent-5bd497d754-74pj8   1/1     Running     0          22m
rancher-64cb65cbf7-xt75l                1/1     Running     0          25m
helm-operation-j5jw2                    0/2     Completed   0          21m
helm-operation-nph7s                    0/2     Completed   0          20m
helm-operation-gj68f                    0/2     Completed   0          20m
rancher-webhook-64f6bf4d54-zrlmv        1/1     Running     0          20m
helm-operation-7smk2                    0/2     Completed   0          20m
```

**Comment by snasovich** [comment] 2021-08-25 14:56
@cmurphy , could you please take a look into this?

**Comment by cmurphy** [comment] 2021-08-25 15:25
@kravciak how long did you wait between clicking delete and checking the cluster state? Could you show the state of the cattle-system namespace as well?

**Comment by gitlawr** [comment] 2021-09-26 09:30
Reproduced as a regression in v2.6-0dd1ce6547cbb3253a8c6f48f5d538c98e7c567d-head

1. Import a Harvester cluster and wait until it's ready.
2. Remove the Harvester cluster. The cattle-system namespace is deleted.

**Comment by cmurphy** [comment] 2021-09-26 22:31
@gitlawr after harvester is imported does the rancher service exist in the cattle-system namespace? `kubectl -n cattle-system get svc`. If it does not exist then that is why the namespace is getting deleted. So https://github.com/rancher/rancher/issues/34716 might be causing this regression, rather than the other way around.

**Comment by guangbochen** [comment] 2021-09-27 00:46
the Rancher service is definite there and this is what we have agreed on how to identify the embedded multi-rancher cluster.

**Comment by gitlawr** [comment] 2021-09-27 05:26
I can reproduce with `v2.6.0` or `v2.6-b7c440be05dff2055b4c8c201e31df97026bc24b-head` upstream Rancher and v0.3.0-preview1 Harvester

Here's the support bundle after the Harvester cluster is imported to Rancher. It provides manifests & logs for debugging.
[supportbundle_preview1_import_to_260.zip](https://github.com/rancher/rancher/files/7233574/supportbundle_preview1_import_to_260.zip)

Here's the Rancher Logs grabbed when the imported cluster is deleted.
[r-logs.txt](https://github.com/rancher/rancher/files/7233578/r-logs.txt)

**Comment by yasker** [comment] 2021-09-27 15:52
For QA: `v2.6-b7c440be05dff2055b4c8c201e31df97026bc24b-head` is an older version. Please go ahead with the validation first but wait for Harvester team to confirm the result and close the issue if the validation passed on the Rancher side, since the time is tight and this is a blocker for Harvester.

**Comment by gitlawr** [comment] 2021-09-28 08:56
Verified in v2.6-06e19b04ce49a4a8f2895769cfa892b8ad14575c-head

I can import, delete, then reimport a Harvester v0.3.0-preview1 cluster to Rancher from Virtualization Management. The Harvester cluster remains working after these operations.

**Closed by gitlawr** 2021-09-28 08:56 UTC
Labels: kind/bug, [zube]: To Test, alpha-priority/1, status/final-release-blocker, area/harvester

**Comment by slickwarren** [comment] 2021-09-28 21:37
reproduced on v2.6-head (06e19b0)
Import a Harvester cluster and wait until it's ready.
Remove the Harvester cluster. The cattle-system namespace is deleted.
