### ISSUE TITLE
Secrets encryption are not set by the UI

### ISSUE THREAD

**Issue by sowmyav27** [rancher/rancher#30560] opened 2020-12-18 23:46 UTC
**What kind of request is this (question/bug/enhancement/feature request):** bug

**Steps to reproduce (least amount of steps as possible):**

- Deployed a cluster custom through API
- secretsEncryptionConfig value is not set on the cluster. - Issue logged https://github.com/rancher/rancher/issues/30558
- Select "enabled" secrets encryption from the UI
- This is NOT sent in the API request by the UI and the value does not get set on the cluster

**Expected Result:**
UI should send the value even though no default is set on the backend

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): 2.5-head- commit id: `bb69b03`
- Installation option (single install/HA): HA (Any)

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): custom rke
- Kubernetes version (use `kubectl version`):

```
1.19 (Any)
```

**Comment by westlywright** [comment] 2020-12-18 23:59
Once the `secretsEncryptionConfig` is created by the backend this should work. The problem is that you're creating a cluster outside the UI and editing in the UI. When we edit a cluster via the UI we dont go through a populate the config with defaults. The component to enabled the secrets encryption is expecting this object to exist on the rke config.

**Comment by deniseschannon** [comment] 2020-12-21 20:27
This is related to the lack of schema in the backend and the UI relies on the schema. Closing in favor of the other ticket #30558

**Closed by deniseschannon** 2020-12-21 20:27 UTC
Labels: [zube]: Next Up, kind/bug-qa, team/ui
