### ISSUE TITLE
UI is stuck on saving registry credential, Rancher 2.4.3

### ISSUE THREAD

**Issue by huijitec** [rancher/rancher#27012] opened 2020-05-10 09:57 UTC
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
Enter `Resources => Secrets => Registry Crendtials` page, then click the `Add Registry` button to add a registry credential for my private gitlab container registry.

I'm sure the credential info is correct, type `docker login ...` in bash cli on the rancher server and it shows login success.

**Result:**
Rancher UI gets stucked at saving forever, screenshot is in below:

<img width="1258" alt="screenshot1" src="https://user-images.githubusercontent.com/55648157/81495890-2b9c0500-92e6-11ea-8797-95c776448fe4.png">

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI):
- Installation option (single install/HA):

* Rancher and UI: v2.4.3
* Rancher Cluster: fresh new installation for 3 nodes HA with RKE

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): Custom
- Machine type (cloud/VM/metal) and specifications (CPU/memory): Cloud VPS, 4c/8gb
- Kubernetes version (use `kubectl version`):

```
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.5", GitCommit:"e0fccafd69541e3750d460ba0f9743b90336f24f", GitTreeState:"clean", BuildDate:"2020-04-16T11:44:03Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.5", GitCommit:"e0fccafd69541e3750d460ba0f9743b90336f24f", GitTreeState:"clean", BuildDate:"2020-04-16T11:35:47Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
```

- Docker version (use `docker version`):

```
Client: Docker Engine - Community
 Version:           19.03.8
 API version:       1.40
 Go version:        go1.12.17
 Git commit:        afacb8b7f0
 Built:             Wed Mar 11 01:25:46 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.8
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.17
  Git commit:       afacb8b7f0
  Built:            Wed Mar 11 01:24:19 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.2.13
  GitCommit:        7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

**Comment by sangeethah** [comment] 2020-05-10 14:48
Duplicate of https://github.com/rancher/rancher/issues/26981

**Closed by sangeethah** 2020-05-10 14:48 UTC
