### ISSUE TITLE
[RFE] K8's 1.27 Support 

### ISSUE THREAD

**Issue by Sahota1225** [rancher/rancher#40943] opened 2023-03-21 20:38 UTC
This is a placeholder ticket for 1.27

**Comment by donch** [comment] 2023-04-28 14:34
Hi, we are running Kubernetes 1.27 with Rancher 2.6.10 for user authentication (our cluster is imported into Rancher).

We have a lot of warning when using kubectl : 
```
kubectl get nodes
Warning: Use tokens from the TokenRequest API or manually created secret-based tokens instead of auto-generated secret-based tokens.
NAME                         STATUS   ROLES           AGE   VERSION
```

This warning is related to : https://github.com/kubernetes/enhancements/tree/master/keps/sig-auth/2799-reduction-of-secret-based-service-account-token

Is there any way to avoid theses warnings ? 

Thanks.

**Comment by mitulshah-suse** [comment] 2023-10-17 14:17
Closing as duplicate of https://github.com/rancher/rancher/issues/41840

**Closed by mitulshah-suse** 2023-10-17 14:17 UTC
Labels: kind/enhancement, team/area2
