### ISSUE TITLE
Error detecting OS: Too many retries waiting for SSH to be available when creating a cluster on vSphere behind NAT

### ISSUE THREAD

**Issue by Turb0Fly** [rancher/rancher#29286] opened 2020-09-30 20:11 UTC
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
In Rancher, create cloud credentials to vCenter using its 1:1 NAT IP address.
Create associated node template
Add cluster, select vSphere option and create a cluster using the node template.
Node gets created, registers the original IP address, not the NAT address.
When Rancher tries to SSH in, it cannot establish connection because it does not know the NAT address of the node.

**Result:**
`Error creating machine: Error detecting OS: Too many retries waiting for SSH to be available.  Last error: Maximum number of retries (60) exceeded`

**Other details that may be helpful:**
1:1 NAT for all devices. e.g. destination IP 10.200.200.45, then NAT IP would be 100.200.100.45.

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): 2.4.5
- Installation option (single install/HA): HA

gz#12566

**Comment by luthermonson** [comment] 2021-01-26 17:59
Code dan wrote attempts ssh and backs off/retries, merged it as we see vsphere ssh issues a lot and this should at least give us some extra chances to confirm the node is up and accessible before we fail.

**Comment by bmdepesa** [comment] 2021-01-26 18:04
@sadiapoddar as part of testing this issue, let's do a full regression test of vSphere node templates

**Comment by sadiapoddar** [comment] 2021-01-29 04:48
on v2.5.6-rc3

**Deployed cluster using node template** 
 
   -  Ran the pre-upgrade automation test on it 
   -   Added new node to cluster
   -   Deleted node from the cluster
   -   Installed monitoring

**Provisioned a node driver cluster by enabling cloud provider config**

      - Ran the pre-upgrade automation test on it
      - Added new node to cluster
      - Deleted node from the cluster
      - Installed monitoring

     **Ran the following PV tests**    
          -  Creating workload with a new PV(Persistent volume)
          -   Deleting the pod of the workload with the PV mounted
          -   Deleting workload with PV mounted
          -   Deleting the worker node where the workload with PV mounted

**Comment by sadiapoddar** [comment] 2021-02-01 23:19
Tested on v2.5-6-rc3 
Failed to deploy a cluster by creating a node template that was pointing to rancher latest iso. 

Steps to repro (the problem is always reproducible)
1. Create node template by selecting "install from boot2docker ISO " and pointing to rancher latest iso
<img width="1269" alt="Screen Shot 2021-02-01 at 3 09 45 PM" src="https://user-images.githubusercontent.com/72409237/106529601-a83bc880-649f-11eb-918e-6b9baf4637c1.png">

2. Create a node driver cluster using the above node template

First it hits the no valid IP error 
 [ERROR] error syncing 'c-qzcdh/m-j5gbs': handler node-controller: notifying bugsnag: [Error creating machine: Error in driver during machine creation: No valid IP despite waiting for one - check DHCP status], requeuing

and then later hitting the machine already existing error
2021/02/01 20:47:34 [ERROR] error syncing 'c-qzcdh/m-hfdzq': handler node-controller: notifying bugsnag: [Error creating machine: Error in driver during machine creation: The name 'xxxxxx' already exists.], requeuing

And the cluster deployment in stuck in "already exists error"..

We kept the setup for you if you want to debug it or like to look at the full logs


Additional info that can be helpful, we tried the same iso template on v2.5.5 and was able to deploy the cluster successfully.

**Comment by deniseschannon** [comment] 2021-02-15 13:54
My understanding is that this is being re-tested so moving it over to-test.

**Comment by bmdepesa** [comment] 2021-02-17 17:06
rancher/rancher:v2.5-head 03b8153

The failing test from this comment: https://github.com/rancher/rancher/issues/29286#issuecomment-771228968 can be reproduced every execution in our vSphere 6.7 test environment, when it was previously working. 

```
handler node-controller: notifying bugsnag: [Error creating machine: Error in driver during machine creation: No valid IP despite waiting for one - check DHCP status], requeuing
```

The nodes are assigned valid IPs in vCenter. This was tried with different node sizes and we see the same result consistently.

**Comment by sadiapoddar** [comment] 2021-02-17 18:24
Verified on v2.5.4 

- Created a cluster pointing to the rancher latest ISO at https://releases.rancher.com/os/latest/rancheros-vmware.iso
- Didn't hit an issue.
- The cluster created successfully.

**Comment by bmdepesa** [comment] 2021-02-24 00:17
rancher/rancher:v2.5-head 30e53bd

* Create a vSphere cluster from node template using the default boot2docker RancherOS iso
* Cluster provisions successfully without any errors

Still needs to be tested on `master-head`

**Comment by bmdepesa** [comment] 2021-02-24 22:58
rancher/rancher:master-head 465bb3b

* Create a vSphere cluster from node template using the default boot2docker RancherOS iso
* Cluster provisions successfully without any errors

**Closed by bmdepesa** 2021-02-24 22:58 UTC
Labels: [zube]: QA Working, internal
