### ISSUE TITLE
[BUG] Provisioning fails with ipv6

### ISSUE THREAD

**Issue by cl-rf** [rancher/rancher#42411] opened 2023-08-14 18:29 UTC
**Rancher Server Setup**
- Rancher version:
Rancher 2.7.5.

**Information about the Cluster**
- Kubernetes version: 2.6
- Cluster Type (Local/Downstream):
  
Provisioned vSphere Cluster

**Describe the bug**
The health probes fail when provisioning a new cluster when using ipv6.

**To Reproduce**
Provision a new cluster in vSphere using ipv6/

**Result**
The health probes never report back that it is healthy even though the pods are up.
```
10:11:55 am | [INFO ] waiting for viable init node
-- | --
10:13:49 am | [INFO ] configuring bootstrap node(s) wagon-pool1-6957f56fdd-r5m8p: waiting for agent to check in and apply initial plan
10:15:29 am | [INFO ] configuring bootstrap node(s) wagon-pool1-6957f56fdd-r5m8p: waiting for probes: etcd, kube-apiserver, kube-controller-manager, kube-scheduler, kubelet
10:16:15 am | [INFO ] configuring bootstrap node(s) wagon-pool1-6957f56fdd-r5m8p: waiting for probes: etcd, kube-controller-manager, kube-scheduler, kubelet
```

**Expected Result**
The health checks pass 

**Screenshots**

**Additional context**
The health checks fail using 127.0.0.1 but respond on the ipv6 loopback.
```
`~# curl http://127.0.0.1:2381/health
curl: (7) Failed to connect to 127.0.0.1 port 2381: Connection refused

l~# curl http://127.0.0.1:10248/healthz
curl: (7) Failed to connect to 127.0.0.1 port 10248: Connection refused

~# curl https://127.0.0.1:10259/healthz
curl: (7) Failed to connect to 127.0.0.1 port 10259: Connection refused

~# curl https://[::1]:10259/healthz -k
ok

~# curl http://[::1]:10248/healthz
ok

~# curl http://[::1]:2381/health
{"health":"true","reason":""}
```

It looks like the health checks are hardcoded to 127.0.0.1 instead of "localhost"
https://github.com/rancher/rancher/blob/release/v2.7/pkg/capr/planner/probe.go

```
var allProbes = map[string]plan.Probe{
	"calico": {
		InitialDelaySeconds: 1,
		TimeoutSeconds:      5,
		SuccessThreshold:    1,
		FailureThreshold:    2,
		HTTPGetAction: plan.HTTPGetAction{
			URL: "http://127.0.0.1:9099/liveness",
		},
	},
	"etcd": {
		InitialDelaySeconds: 1,
		TimeoutSeconds:      5,
		SuccessThreshold:    1,
		FailureThreshold:    2,
		HTTPGetAction: plan.HTTPGetAction{
			URL: "http://127.0.0.1:2381/health",
		},
	},
```

One other thing is that kube-apiserver seems to bind to both the ipv4 and ipv6 loopbacks but the others don't.

```
~# curl https://[::1]:6443/readyz -k
{
  "kind": "Status",
  "apiVersion": "v1",
  "metadata": {},
  "status": "Failure",
  "message": "Unauthorized",
  "reason": "Unauthorized",
  "code": 401
}

~# curl https://127.0.0.1:6443/readyz -k
{
  "kind": "Status",
  "apiVersion": "v1",
  "metadata": {},
  "status": "Failure",
  "message": "Unauthorized",
  "reason": "Unauthorized",
  "code": 401
}
```

```
State                  Recv-Q                 Send-Q                                         Local Address:Port                                   Peer Address:Port                 Process                
LISTEN                 0                      4096                                                       *:9345                                              *:*                                            
LISTEN                 0                      4096                                                   [::1]:10248                                          [::]:*                                            
LISTEN                 0                      4096                                                       *:6443                                              *:*                                            
LISTEN                 0                      4096                                                   [::1]:2379                                           [::]:*                                            

LISTEN                 0                      4096                                                   [::1]:2381                                           [::]:*                                            

```

SURE-6782

**Comment by fayak** [comment] 2023-08-17 10:25
We're facing the same issue, and we have tried running rancher 2.7.5 rebuilt with this applied first:
 `grep -rni 127.0.0.1 -l | xargs sed -e 's,127.0.0.1,localhost,g' -i`
 
 It looks like it's working. This is a really dumb solution as some `127.0.0.1` may be still needed, but most probably the "real" solution can be inspired by this. Should I go ahead and try to submit a PR and figure out which `127.0.0.1` must be replace by `localhost` or not ?
 
 Thanks @cl-rf for the identification !

**Comment by lbaker-esnet** [comment] 2023-08-17 14:32
@fayak  That's great to hear! We suspected a solution like yours would work but I agree there may be other items to consider.

**Comment by cl-rf** [comment] 2023-08-17 14:43
I think localhost makes more sense than hardcoding 127.0.0.1 at least in the probes file. The hosts file can easily be changed for localhost if there is a problem.

**Comment by markusewalker** [comment] 2023-09-19 19:09
**QA TEST PLAN**

**Scenarios**
|Scenario|Test Case|
|---|---|
|1|As a standard user, attempt to provision an RKE2 custom cluster with public and private IPv6 specified and validate that the registration command correctly formats IPv6|
|2|As a standard user, attempt to provision an RKE2 custom cluster with dual stack specified and validate that the registration command correctly formats IPv6|
|3|As a standard user, attempt to provision an RKE2 custom cluster with public and private IPv4 specified and validate that the registration command correctly formats IPv4|

**Comment by markusewalker** [comment] 2023-09-19 19:12
Reproduced this issue in https://github.com/rancher/rancher/commit/efc48ac09ab8307cc949f13aa5e57cc2568c4ab6. See details below:

**ENVIRONMENT DETAILS**
- Rancher install: Docker
- Rancher version: `v2.8-head` https://github.com/rancher/rancher/commit/efc48ac09ab8307cc949f13aa5e57cc2568c4ab6

**TEST RESULT**
|Scenario|Test Case|Result
|---|---|---|
|1|As a standard user, attempt to provision an RKE2 custom cluster with public and private IPv6 specified and validate that the registration command correctly formats IPv6|:x:|

**VALIDATION STEPS**

**Scenario 1**
1. As a standard user, attempted to provision a downstream RKE2 `v1.27.5+rke2r1` custom cluster.
2. In the `Advanced` section, specified the public and private IPv6 addresses; validated that the registration command correctly parses the respective flags.
3. Unable to successfully properly provision due to the health probes failing.

Once the PR has been merged and is ready for validation, I will test the test plan in full at that time to verify if the issue has been addressed.

**Comment by markusewalker** [comment] 2023-10-05 17:13
After a deeper dive into the scenario 1 failure above, I root-caused the issue to be a DNS misconfiguration with the IPv6-only nodes. After addressing those DNS issues on the backend, I successfully validated that this is addressed in `v2.8-head` https://github.com/rancher/rancher/commit/fc12e7d779577d10ded1a8e249f51727848b878e.

**ENVIRONMENT DETAILS**
- Rancher install: Docker
- Rancher version: `v2.8-head` https://github.com/rancher/rancher/commit/fc12e7d779577d10ded1a8e249f51727848b878e


**TEST RESULT**
|Scenario|Test Case|Result
|---|---|---|
|1|As a standard user, attempt to provision an RKE2 custom cluster with public and private IPv6 specified and validate that the registration command correctly formats IPv6|:white_check_mark:|
|2|As a standard user, attempt to provision an RKE2 custom cluster with dual stack specified and validate that the registration command correctly formats IPv6|:white_check_mark:|
|3|As a standard user, attempt to provision an RKE2 custom cluster with public and private IPv4 specified and validate that the registration command correctly formats IPv4|:white_check_mark:|

**VALIDATION STEPS**

**Scenario 1**
1. As a standard user, attempted to provision a downstream RKE2 `v1.27.6+rke2r1` custom cluster (1 etcd, 1 cp, 1 worker).
2. In the `Advanced` section, specified the public and private IPv6 addresses; validated that the registration command correctly parses the respective flags.
3. Edited the cluster as YAML and added the following snippets:
Machine global config:
```
cluster-cidr: "2001:cafe:42:0::/56"
service-cidr: "2001:cafe:42:1::/112"
```

```
spec:
  rkeConfig:
    networking:
      stackPreference: ipv6
```
4. Validated that the cluster and nodes came up as `Active`.
5. Repeated the above step for the following cluster configurations:
     - 1 etcd+cp, 1 worker
     - 1 etcd + cp + worker
_______

**Scenario 2**
1. As a standard user, attempted to provision a downstream RKE2 `v1.27.6+rke2r1` custom cluster (1 etcd, 1 cp, 1 worker).
2. Edited the cluster as YAML and added the following snippets:

Machine global config:
```
cluster-cidr: "10.42.0.0/16,2001:cafe:42:0::/56"
service-cidr: "10.43.0.0/16,2001:cafe:42:1::/112"
```

```
spec:
  rkeConfig:
    networking:
      stackPreference: dual
```
3. Validated that the cluster and nodes came up as `Active`.
4. Took an etcd snapshot.
5. Editeed the YAML to have the following:
```
spec:
  rkeConfig:
    networking:
      stackPreference: ipv4
```
7. Restored the etcd snapshot using all options; validated that the YAML contained the `stackPreference` as expected.


_____

**Scenario 3**
1. As a standard user, attempted to provision a downstream RKE2 `v1.27.6+rke2r1` custom cluster (1 etcd, 1 cp, 1 worker).
2. In the `Advanced` section, specified the public and private IPv4 addresses; validated that the registration command correctly parses the respective flags.
3. Edited the cluster as YAML and added the following snippet:
```
spec:
  rkeConfig:
    networking:
      stackPreference: ipv4
```
4. Validated that the cluster and nodes came up as `Active`.

**Closed by markusewalker** 2023-10-05 17:13 UTC
Labels: kind/bug, internal, [zube]: QA Working, QA/S, area/provisioning-v2, team/area2, area/capr

**Comment by workjiao** [comment] 2024-02-18 07:41
https://github.com/rancher/rancher/issues/42411#issuecomment-1749334073
@markusewalker  
May I ask how this DNS problem is solved? I seem to have encountered the same problem.

**Comment by ronnyaa** [comment] 2024-04-15 15:52
same problem here, 
having the fix google able would be nice. this is the first hit for the search. 

the nodes have working dns over ipv6. so i do not know what that dns problem consists of.
