### ISSUE TITLE
[BUG] VAI Cache Namespace Taking ~9 Mins to Propagate Across All .DB Files

### ISSUE THREAD

**Issue by brudnak** [rancher/rancher#47742] opened 2024-10-25 22:01 UTC
# Rancher Server Setup

| Component                        | Version / Type                                      |
| -------------------------------- | --------------------------------------------------- |
| Rancher version starting         | v2.10-dae07ed09601506420c133a69d6e6d27bb7a53ec-head |
| Installation option              | Helm (high availability)                            |
| RKE binary version used          | v1.6.2                                              |
| If Helm Chart k8s cluster        | v1.30.4                                             |
| Cert Details                     | external tls `aws acm`                              |
| Docker version                   | 20.10.7, build f0df350                              |
| Downstream cluster type          | not applicable                                      |
| Downstream K8s version           | not applicable                                      |
| Authentication providers enabled | local                                               |
| Logged in user role              | admin                                               |

# Describe the bug

Running an HA Rancher with VAI / `ui-sql-cache` enabled. When creating a namespace, that namespace is not immediately propagated across all `.db` files from each Rancher pod. I thought this used to be the case with resources like secrets, but that namespaces would propagate almost immediately across database files.

# To Reproduce

1. Start an HA rancher on `head`
2. Enable the VAI / `ui-sql-cache` feature flag, wait for restart
3. In the Rancher UI navigate to the local cluster and create a namespace under the default project named `myspace`
4. On the projects/namespaces page in the Rancher UI give the browser a hard refresh
5. After this is done have the cluster kube config file on your local machine and run the following command:
    - You'll need the following installed
      - `kubectl` with access to a Rancher cluster
      - `sqlite3` installed
      - `zsh` shell

```sh
curl -sL https://raw.githubusercontent.com/brudnak/rancher-test-scripts/refs/heads/main/vai/namespace/script.sh | zsh -s -- myspace 10
```

# Result

It took ~9 minutes for the namespace to propagate across all `.db` files. Is this expected?

```sh
=== 📊 FINAL SUMMARY ===
Search for: myspace
✅ Successfully found in all pods!
Planned duration: 10 minutes
Actual duration: 8.76 minutes
Completed 10.0% faster than maximum time

Pod Discovery Timeline:
rancher-7fb5cfc58d-mtrnb: Found after 46 seconds
rancher-7fb5cfc58d-tvvl8: Found after 7 seconds
rancher-7fb5cfc58d-8qc92: Found after 522 seconds

Total propagation time: 515 seconds
```

# Expected Result

For a namespace not to take ~9 minutes to propagate across all `.db` files. As this was not previously the case

# Bug Frequency

| Frequency                                                                                          | Selected Option |
| -------------------------------------------------------------------------------------------------- | --------------- |
| Consistent (10/10) - A consistent bug can be replicated every time the test is executed.           | ✅               |
| Frequent (7/10)- A frequent bug can be replicated like 7 out of 10 times when a test is replicated |                 |
| Occasional (5/10) - Occasional bug is more hard to replicate than a frequent bug.                  |                 |
| Once thus far, twice thus far - Few bugs cannot be reproduced every time you run the test.         |                 |

**Comment by moio** [comment] 2024-10-28 11:39
As the SQLite database is not meant to be read or used by any process other than Rancher, we've used options that forego flushing data to disk unless memory pressure requires that.

IOW, it is completely expected that looking at SQLite DB files from another process such as sqlite3 will give you an outdated and potentially inconsistent view of data actually available in Rancher.

I am sorry I fear this testing approach will just not work well under current assumptions.

Is it a possibility to check from the Steve API instead of going directly to the database file?

**Comment by MKlimuszka** [comment] 2024-10-28 17:19
@moio , are you saying this may not be a bug at all?

**Comment by moio** [comment] 2024-10-28 17:31
Correct. We do not expect the DB files to be correct and complete at any point in time

What is expected to be correct and complete at any point in time is the whole state of the database - files and memory (inside of the Rancher process)

The problem is you can't easily look at that without being inside Rancher itself

**Comment by tomleb** [comment] 2024-10-28 18:27
If we really want to look at the inside of the database, then we may use `VACUUM INTO /path/to/snapshot.db` sqlite statement to make snapshot of the DB to another file.

I don't think rancher has the sqlite3 binary installed so we'd need to use debug containers for this.

> Is it a possibility to check from the Steve API instead of going directly to the database file?

One benefit I see from looking at the DB, at least to check that it exists / has content is you can be somewhat sure that vai is enabled. Just going through steve won't give you that information (afaik), so we could have a regression there and not be aware.

**Comment by brudnak** [comment] 2024-10-28 22:31
>One benefit I see from looking at the DB, at least to check that it exists / has content is you can be somewhat sure that vai is enabled. Just going through steve won't give you that information (afaik), so we could have a regression there and not be aware.

This was qa's pov as well - (afaik too there isn't a way to confirm this with steve alone)

**Comment by moio** [comment] 2024-10-29 07:44
I agree adding a Steve endpoint to dump the DB can be useful for QA purposes (and possibly troubleshooting).

IIUC `VACUUM INTO` will work even with `PRAGMA synchronous = OFF`, because the file is closed before returning, so it should fit this use case really well.

Note that running `VACUUM INTO` from a debug container will not work - it must be run from inside the Rancher process, for it to take into account unflushed and in-memory state.

Once we have that, if more than a handful seconds is necessary to propagate state, then it should be considered a bug.

**Comment by tomleb** [comment] 2024-10-29 14:02
> Note that running VACUUM INTO from a debug container will not work - it must be run from inside the Rancher process, for it to take into account unflushed and in-memory state.

Hum, here's my understanding and why I think this should still work with a debug container.. First, we're running with `PRAGMA journal_mode = WAL` so all changes to othe database are appended to the `-wal` file. We're using `PRAGMA synchronous = off` so those writes are only given to the OS, but we're not explicitely waiting for them to be written to disk. So they might be in the OS cache, but not yet in disk. Fine. Now say another process (debug container) opens the database and runs `VACUUM INTO`.. I would expect that database to see the changes even if they're not yet written durably to disk. Otherwise, I don't really see how multiple goroutines living in many (sometimes changing) processes can view the latest state of the DB. Does that make sense? I've been trying and failing to find an explanation / proof for the above. :/

**Comment by moio** [comment] 2024-10-30 12:09
I will admit I was not aware of unix behavior for written but unflushed changes to a file.

This answer looks like a credible explanation to me: https://stackoverflow.com/questions/39070671/linux-is-data-written-to-a-file-guaranteed-to-be-visible-to-other-processes

So, there is a good chance I was wrong and it should work.

I'd appreciate if @brudnak could do a quick test - even completely manually - just to prove the theory is correct - 9 minutes should be enough to spawn a debug container, run sqlite3 attached to the database giles, run the VACUUM INTO a new db, close sqlite3, open the VACCUUmed DB and see that content there exists.

If that is not the case, I can take a deeper look.

**Comment by brudnak** [comment] 2024-10-30 19:52
@moio @tomleb  When using vacuum the namespace is available immediately 

```sh
curl -sL https://raw.githubusercontent.com/brudnak/rancher-test-scripts/refs/heads/main/vai/namespace-vacuum/script.sh | zsh -s -- test-namespace-123
```

```log
Processing pod: rancher-8569b6b7f9-6qpfb
Running vacuum process on pod...
Starting vacuum process...
Go is already installed
Found existing vacuum tool, attempting to use it...
Existing vacuum tool worked successfully
Copying snapshot from pod...
tar: Removing leading `/' from member names
Checking snapshot from rancher-8569b6b7f9-6qpfb...
✅ Found namespace 'test-namespace-123' in pod: rancher-8569b6b7f9-6qpfb
Cleaning up temporary files...
Processing pod: rancher-8569b6b7f9-84qn4
Running vacuum process on pod...
Starting vacuum process...
Go is already installed
Found existing vacuum tool, attempting to use it...
Existing vacuum tool worked successfully
Copying snapshot from pod...
tar: Removing leading `/' from member names
Checking snapshot from rancher-8569b6b7f9-84qn4...
✅ Found namespace 'test-namespace-123' in pod: rancher-8569b6b7f9-84qn4
Cleaning up temporary files...
Processing pod: rancher-8569b6b7f9-9zcbk
Running vacuum process on pod...
Starting vacuum process...
Go is already installed
Found existing vacuum tool, attempting to use it...
Existing vacuum tool worked successfully
Copying snapshot from pod...
tar: Removing leading `/' from member names
Checking snapshot from rancher-8569b6b7f9-9zcbk...
✅ Found namespace 'test-namespace-123' in pod: rancher-8569b6b7f9-9zcbk
Cleaning up temporary files...
```

**Comment by moio** [comment] 2024-10-31 07:41
Excellent, that proves the two theories with one shot!

 - Unflushed written changes to files are visible to other processes
 - changes are propagated without big delays, just not flushed (as expected)

I guess we are good closing this one!

Thanks everybody

**Closed** 2024-11-01 23:39 UTC
Labels: kind/bug, team/frameworks
