### ISSUE TITLE
[BUG]rancher-ui zh-hans translations execute shell has error

### ISSUE THREAD

**Issue by anjia0532** [rancher/rancher#9034] opened 2017-06-12 09:04 UTC
chrome console log
```
core.js:189 Uncaught Error: A value must be provided for: instnceName
    at o._format (core.js:189)
    at o.r.format (core.js:41)
    at n.format (format-message.js:27)
    at n.compute (-format-base.js:94)
    at n.compute (ember.prod.js:14318)
    at n.value (ember.prod.js:14645)
    at Object.d [as read] (ember.prod.js:15035)
    at Object.r [as getValue] (ember.prod.js:10169)
    at Object.T [as inline] (ember.prod.js:42801)
    at Object.inline (ember.prod.js:43307)
```
other language is ok.

the `instnceName` is wrong,should be `instanceName`

```yaml
modalShell:
  title: '命令行:{instanceName}'
```
from  https://github.com/rancher/ui/blob/master/translations/zh-hans.yaml#L2271 ,but `rancher/server:v1.6.2`‘s http://rancher.mydomain.com/translations/zh-hans.json?1.6.5 

```javascript
// ellipsis...
"modalShell": {
		"title": "命令行: {instnceName}"
	}
// ellipsis...
```
---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v1.6.2` Cattle: `v0.181.4` UI: `v1.6.5` |
|Access|`Disabled`|
|Orchestration|`Cattle`|
|Route|`service.containers`|

**Comment by tfiduccia** [comment] 2017-06-12 17:46
Duplicate of #8963

**Closed by tfiduccia** 2017-06-12 17:46 UTC
