### ISSUE TITLE
[BUG] rke2 clusters with invalid values for tolerations / affinity agent customization do not show error to user, stay in `updating` state on cluster create

### ISSUE THREAD

**Issue by slickwarren** [rancher/rancher#41606] opened 2023-05-18 22:38 UTC
**Rancher Server Setup**
- Rancher version: v2.7-head ()
- Installation option (Docker install/Helm Chart): helm
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): rke1, 1.4.5
- Proxy/Cert Details: valid certs

**Information about the Cluster**
- Kubernetes version: tested with 1.25.9, 1.26.x
- Cluster Type (Local/Downstream): downstream
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider): rke2 linode driver

**User Information**
- What is the role of the user logged in? (Admin/Cluster Owner/Cluster Member/Project Owner/Project Member/Custom)
  - If custom, define the set of permissions: standard user, cluster owner

**Describe the bug**

when provisioning a cluster with invalid values for tolerations or affinity agent customizations (cluster agent or fleet agent), the cluster is able to start being created. However, the cluster never shows any error state and hangs in an `updating` state

**To Reproduce**

* deploy an rke2 cluster
  * for cluster agent and fleet agent customization, enter a bad label for tolerations and node affinity, i.e. `badLabel 123"[];'{}-+=`
* wait for the cluster to provision

**Result**
cluster is able to be created, but stays in an `updating` state, see screenshots

**Expected Result**

cluster should error out and bubble this state up to the user on the `management` page 
error should be shown to the user

if user ssh's into the node and views rke2-server logs, you can see there is an error that spams there every few seconds:
```

May 18 22:37:07 bad-custization1-dsa-3a9fb14b-s4rsd rke2[2054]: time="2023-05-18T22:37:07Z" level=error msg="Failed to process config: failed to process /var/lib/rancher/rke2/server/manifests/rancher/cluster-agent.yaml: failed to create cattle-system/cattle-cluster-agent apps/v1, Kind=Deployment for  kube-system/cluster-agent: Deployment.apps \"cattle-cluster-agent\" is invalid: [spec.template.spec.affinity.nodeAffinity.requiredDuringSchedulingIgnoredDuringExecution.nodeSelectorTerms[0].matchExpressions[1].key: Invalid value: \"notGood~ [];'/..,\": prefix part a lowercase RFC 1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*'), spec.template.spec.affinity.nodeAffinity.requiredDuringSchedulingIgnoredDuringExecution.nodeSelectorTerms[0].matchExpressions[1].key: Invalid value: \"notGood~ [];'/..,\": name part must consist of alphanumeric characters, '-', '_' or '.', and must start and end with an alphanumeric character (e.g. 'MyName',  or 'my.name',  or '123-abc', regex used for validation is '([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9]'), spec.template.spec.tolerations[3].key: Invalid value: \"notGood~ [];'/..,\": prefix part a lowercase RFC 1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*'), spec.template.spec.tolerations[3].key: Invalid value: \"notGood~ [];'/..,\": name part must consist of alphanumeric characters, '-', '_' or '.', and must start and end with an alphanumeric character (e.g. 'MyName',  or 'my.name',  or '123-abc', regex used for validation is '([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9]')]"
```

**Screenshots**

![Screen Shot 2023-05-18 at 3 30 18 PM](https://github.com/rancher/rancher/assets/16691014/c4d48c8e-b57f-4756-99e3-a5039d58995a)
![Screen Shot 2023-05-18 at 3 30 12 PM](https://github.com/rancher/rancher/assets/16691014/7b72dbed-66b7-460d-a907-568717902ec7)
<img width="760" alt="Screen Shot 2023-05-18 at 1 42 00 PM" src="https://github.com/rancher/rancher/assets/16691014/017ec415-722f-4c24-901b-9c5844c6e916">

**Additional context**

error is bubbled up to the user for rke1

**Comment by snasovich** [comment] 2023-05-23 18:56
Kicked it out to Q3 for now as it's not a critical bug applicable only if the user provides an invalid configuration and is essentially a poor UX where error root cause is not bubbled up in the UI.
This can be improved by adding format validation on these fields - best to do it on both UI and backend. For backend options include adding `pattern` on the generated CRD (which may require deeper changes as CRDs are [generated](https://github.com/rancher/wrangler/blob/39a4707f0689cc97ca955f5eea5d0b37e1664cae/pkg/crd/init.go#L238) by Wrangler) or adding these validations to webhook.

**Comment by slickwarren** [comment] 2023-05-23 19:19
referencing UI issue: https://github.com/rancher/dashboard/issues/8920

**Comment by snasovich** [comment] 2023-08-09 16:46
We may want to follow something like [`64d6bc5` (#41768)](https://github.com/rancher/rancher/pull/41768/commits/64d6bc54f26d9ae3a483122e9f7071f80f96219c) to add validation to these fields on `cluster.provisioning.cattle.io` but given how large and core this CRD this should be done as a larger effort and not part of fixing this (rather small) issue.

Kicking out to Q1.

**Comment by felipe-colussi** [comment] 2023-10-27 18:25
I was trying to take a look into this, it is impossible to change to the `kubebuilder`  with simple changes, it would require a lot of effort/tests. 

Wile testing:
* Some fields that weren't required become required.
* The fields with `rkev1.GenericMap` don't  work (can't unmarshal into it).
* Some data that is not mapped on the struct are passed, generating errors.
* When embebeding a structs  the embebed fields don't seem to be created.

**Comment by a-blender** [comment] 2023-10-27 19:07
Would adding validation to the CRD even bubble up via rke2? The fact that rke bubbles up the error and rke2 does not may be a result of how RKE2 is designed (I've run into this before). cc @jakefhyde 

This may not be as deep as we want, but we could also add a validator/regex to the `systemtemplate` and check that agent customization fields are valid before setting them on the cluster agent deployment - see https://github.com/rancher/rancher/blob/c3411e0ca574b7086308bf4ef2e49984cd247dd1/pkg/systemtemplate/import.go#L102-L123. It wouldn't show the underlying error from the rke2 logs but would alert the user a lot earlier if they are attempting to add the agent customization via kubectl instead of the UI.

**Comment by felipe-colussi** [comment] 2023-10-30 16:26
@a-blender, after talking with @snasovich  we decided to add the validation on the web-hook.
It is not the k8s "recommended" way, but given the way we create the CRDs and the size/importance of the cluster one it is much safer.

**Comment by slickwarren** [comment] 2024-08-19 19:11
on 2.9-head (63d8298029ce22942459eaaf0dbe084963c234c5) I tested the original use case, but it is still failing. I think its because this line only checks the label key, but should also checking the value
https://github.com/thatmidwesterncoder/webhook/blob/release/v0.5/pkg/resources/provisioning.cattle.io/v1/cluster/validator.go#L530

if I have a bad label key, then the UI does report a failure when the user tries to create

can this be fixed?

**Comment by snasovich** [comment] 2024-08-26 19:22
@slickwarren , agree it would be nice to add deeper validation that includes validating remaining `Toleration` and `NodeSelectorRequirement` fields - though reading original repro steps of the issue it seems to be specifically around label key.

@thatmidwesterncoder , can we use functions from https://pkg.go.dev/k8s.io/kubernetes/pkg/apis/core/validation package, more specifically https://pkg.go.dev/k8s.io/kubernetes/pkg/apis/core/validation#ValidateTolerations / https://pkg.go.dev/k8s.io/kubernetes/pkg/apis/core/validation#ValidateNodeSelectorRequirement or are the issue with core data types mismatch?

Depending on the amount of effort needed we will need to evaluate if it's worth doing deeper validation.

**Comment by snasovich** [comment] 2024-10-24 21:46
Closing this issue with `v2.9.1` milestone retroactively as:
1. The exact scenario in "Steps to Reproduce" was addressed
2. Keeping it open creates weird situation where forwardport to v2.10.0 (https://github.com/rancher/rancher/issues/46402) to ensure done changes are moved to v2.10 release branch is targeting earlier release than this is targeting now (v2.10.1).

That said, a new issue to address concerns from https://github.com/rancher/rancher/issues/41606#issuecomment-2297260113 will be created to improve validation further.

**Closed by snasovich** 2024-10-24 21:46 UTC
Labels: priority/2, kind/bug-qa, QA/XS, release-note, area/provisioning-v2, area/capr/rke2, team/hostbusters, status/release-note-added
