### ISSUE TITLE
Allow load balancer target to be able to use external services that are using hostname

### ISSUE THREAD

**Issue by fernandofederico1984** [rancher/rancher#2624] opened 2015-11-09 23:54 UTC
I created an external service called external-1, that external service points to a host name: dev.test.com. On the other hand, I have a service called myService that calls and endpoint in the host docker.test.com (I need it to be called that way in order to mach the host name certificate *.test.com) I want myService to call dev.test.com

here is the docker file:

```
external-1:
  image: rancher/external-service
myService:
  expose:
  - 8081/tcp
  ports:
  - 8080:8081/tcp
  image: myService:1.0.0
  links:
  - docker.test.com:external-1

```

and this is my rancher compose file

```
myService:
  scale: 1
external-1:
  hostname: dev.test.com
```

Seems that I can connect, but I always get 405 (method not allowed) from inside myService. Of course the same endpoint works fine if I hit dev.test.com directly

**Comment by fernandofederico1984** [comment] 2015-11-10 20:11
BTW, where can I see the logs of the HA proxy for external systems?

**Comment by deniseschannon** [comment] 2015-11-18 22:29
Currently, a load balancer target cannot be an external service pointing to a hostname. I thought there was an issue for it, but cannot seem to find it. This might become that issue. :)

As for the logs, there is a separate issue request to get the logs. 

https://github.com/rancher/rancher/issues/2414

**Comment by alena1108** [comment] 2016-12-13 17:44
Should be fixed in the new haproxy release (v0.4.5)

**Comment by soumyalj** [comment] 2016-12-13 22:30
Tested with v1.2.1-rc1. Created an external service "ext1" pointing to a service "service2" in another stack "test".  Created a loadbalancer with target as "ext1".  The loadbalancer targets pointed correctly to the "service2" in stack "test". 
Here is the snippet of ``` etc/haproxy/haproxy.cfg```
```
resolvers rancher
 nameserver dnsmasq 169.254.169.250:53

listen default
bind *:42

frontend 82
bind *:82
mode http
default_backend 82_

backend 82_
acl forwarded_proto hdr_cnt(X-Forwarded-Proto) eq 0
acl forwarded_port hdr_cnt(X-Forwarded-Port) eq 0
    http-request add-header X-Forwarded-Port %[dst_port] if forwarded_port
    http-request add-header X-Forwarded-Proto https if { ssl_fc } forwarded_prot
o
mode http
server service2.test service2.test:80   check resolvers rancher


```

**Closed by soumyalj** 2016-12-13 22:30 UTC
Labels: area/balancer, kind/enhancement, kind/feature, priority/-1, status/resolved, status/to-test

**Comment by djskinner** [comment] 2017-02-04 14:09
External services are not showing up in the target dropdown when configuring a load balancer in 1.3.3. Is this a regression or just not possible to do?

**Comment by brettneese** [comment] 2017-02-28 02:37
We're having that issue also

**Comment by brettneese** [comment] 2017-05-08 18:15
According to @vincent99, this was (intentionally?) broken (without updating these issues) for some reason between 1.3.3 and 1.5.5: 

"External hostnames intentionally do not show up because balancing to a name has a variety of implications and tradeoffs and configuration that we do not have controls to manage."

Really unfortunate, since it was working before (and was broken without explanation on the issues/PRs that originally enabled it). It would be nice if those "implications and tradeoffs and configuration" were explained in more detail and, if at all possible, this were still an option in spite of them. 

👎

**Comment by GiGurra** [comment] 2017-06-21 08:05
I wonder why there is even an option to create an external service pointing to a hostname when there is no way to target it from a load balancer?
