### ISSUE TITLE
Settings - no error message if no-admin user edits global settings

### ISSUE THREAD

**Issue by jiaqiluo** [rancher/rancher#20467] opened 2019-05-24 23:29 UTC
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
- run Rancher: v2.2.4-rc12
- enable Github Auth
- log in as a Github user, and by default the user is a standard user
- go to `Settings`
- edit `ui-index` to another value
- save 
<img width="717" alt="screenshot" src="https://user-images.githubusercontent.com/6218999/58360993-912a8380-7e40-11e9-8c06-2d9fb288bb8e.png">

**Result:**
- the value of `ui-index` is not changed 
- no error message shows to indicate the Github user has no permission to change settings

**Expected Result:**
An error message should show up if the user has no permission to change settings

**Comment by alena1108** [comment] 2019-05-25 00:29
Assuming the issue is not a regression in 2.2.4, moving it to 2.3 cc @jiaqiluo

**Comment by loganhz** [comment] 2019-08-15 05:18
It has `links.update` is in API. I think we should fix it in backend.

**Comment by mrajashree** [comment] 2019-08-16 18:05
@loganhz @jiaqiluo  I do see API returning a 403. I even see the error in UI, but the error popup lasts for hardly a few seconds before the second api call to refresh settings page is done. This is the error in UI. 
<img width="1440" alt="Screen Shot 2019-08-16 at 11 02 25 AM" src="https://user-images.githubusercontent.com/10672776/63188097-630aa900-c015-11e9-8b1d-ace7ab8dd7ef.png">

Error in UI:
![Untitled](https://user-images.githubusercontent.com/10672776/63188091-60a84f00-c015-11e9-87ad-c4a18203af55.png)

**Comment by loganhz** [comment] 2019-08-16 23:02
@mrajashree can we remove the `update` link in API if the user doesn't have permission to update the setting.

We are doing this for other resources. So users don't have to try if they can edit or not.

**Comment by mrajashree** [comment] 2019-08-17 00:02
@loganhz okay will do

**Comment by jiaqiluo** [comment] 2019-08-20 23:05
The bug fix is validated in Rancher:master-head d66a45ecd

Follow the same steps as the issue describes, and now the Github user cannot see the `Edit` option for the `ui-index`

<img width="1466" alt="Screen Shot 2019-08-20 at 4 03 18 PM" src="https://user-images.githubusercontent.com/6218999/63390538-5911de80-c364-11e9-84f9-461fa92d7851.png">

**Closed** 2019-08-20 23:06 UTC
Labels: [zube]: To Test, area/api, kind/bug-qa, team/ca
