### ISSUE TITLE
Project "Container Default Resource Limit" settings allow you to define a default reservation greater than the default limit

### ISSUE THREAD

**Issue by gaktive** [rancher/rancher#39700] opened 2022-08-02 23:42 UTC
Internal reference: SURE-4864
Reported in 2.6.5

Issue description:
The "Container Default Resource Limit" configuration on Rancher Projects permits creation of a default reservation for CPU/memory that exceeds the default limit for CPU/memory, in which instance Rancher produces no error within the UI and permits creation of this conflicting reservation/limit. The LimitRange resource fails to create in the Namespaces of the Project, with errors of the following format in the Rancher Pod logs: 

```
2022/06/23 14:51:16 [ERROR] error syncing 'test': handler resourceQuotaSyncController: LimitRange "b91c5718-c334-4ec3-a66b-c50a7251a470" is invalid: spec.limits[0].defaultRequest[memory]: Invalid value: resource.Quantity{i:resource.int64Amount

{value:1048576000, scale:0}
, d:resource.infDecAmount{Dec*inf.Dec)(nil)}, s:"", Format:"BinarySI"}: default request value 1000Mi is greater than default limit value 2Mi, requeuing
```

This should require a backend (as well as possible frontend validation) fix, such that this cannot occur when a user defines the Container Default Resource Limit for a Project via the Rancher2 Terraform Provider (https://registry.terraform.io/providers/rancher/rancher2/latest/docs/resources/project#container_resource_limit) or Rancher API.

Business impact:
The LimitRange resource for Namespaces in Project's with this bad configuration are not created, without any error to indicate this within Rancher UI

Repro steps:

- Provision a Rancher v2.6.5 instance and a single all role node cluster 
- Create a test Project, with a single test Namespace, and under "Container Default Resource Limit" set the Memory Reservation to 1000Mi and Memory Limit to 2Mi
- Observe you can successfully save the changes, but errors appear in Rancher Pod logs 
- Create a new test Project, with a single test Namespace, and under "Container Default Resource Limit" set a CPU Reservation of 2000 and a CPU Limit of 2000
- Observe you can successfully save the changes, but similar errors appear in Rancher Pods logs: 

```
2022/06/23 15:08:06 [ERROR] error syncing 'test2': handler resourceQuotaSyncController: LimitRange "94ad658d-f709-41f3-8bac-cd138fbca6fd" is invalid: spec.limits[0].defaultRequest[cpu]: Invalid value: resource.Quantity{i:resource.int64Amount {value:2, scale:0}
, d:resource.infDecAmount{Dec*inf.Dec)(nil)}, s:"2", Format:"DecimalSI"}: default request value 2 is greater than default limit value 1, requeuing
```

Workaround:
N/A

Actual behavior:
Able to create Project Container Default Resource Limit configuration where the default reservation for CPU/memory exceeds the default limit for CPU/memory, resulting in errors when Rancher attempts to create the LimitRange resource in Project Namespaces

Expected behavior:
Unable to create Project Container Default Resource Limit configuration where the default reservation for CPU/memory exceeds the default limit for CPU/memory

**Comment by gaktive** [comment] 2022-11-26 00:45
Transferred to backend to investigate further. If UI validation is required, let us know over in `rancher/dashboard`.

**Comment by skanakal** [comment] 2023-06-01 12:16
This issue reproducible in rancher 2.7.3

```
newrancherserver:~ # kubectl get -n cattle-system deployment.apps/rancher -o json | jq -r .spec.template.spec.containers[].image
rancher/rancher:v2.7.3
newrancherserver:~ # 
newrancherserver:~ # kubectl logs -f -n cattle-system deployment.apps/rancher  | grep resourceQuotaSyncController | head -1
2023/06/01 12:09:02 [ERROR] error syncing 'test': handler resourceQuotaSyncController: LimitRange "2ee6f535-0e91-433b-8a72-976d58a36be9" is invalid: spec.limits[0].defaultRequest[memory]: Invalid value: resource.Quantity{i:resource.int64Amount{value:1048576000, scale:0}, d:resource.infDecAmount{Dec:(*inf.Dec)(nil)}, s:"", Format:"BinarySI"}: default request value 1000Mi is greater than default limit value 2Mi, requeuing
newrancherserver:~ #
```

**Comment by pennyscissors** [comment] 2023-10-30 22:23
Update on this issue after some investigation.

This is not a resource quota problem, is a container default limit problem. Although they might seem like the same feature, they are not in the code. They also produce different objects/requests. Another important detail is the container default limits need to be set at the project level, not namespace level to be able to reproduce this issue. I don't think the level should matter, but there seems to be another bug that prevents a LimitRange object from being created when you set them at the namespace level and so you don't see the error when I think you should. That said, in the terms of this issue the controller seems to work as intended. Therefore a fix for this issue should be done at the Rancher webhook level by extending our current validation for projects/namespaces to check for container default limits as well. This would produce an error the UI can then make use of to warn the user when they've entered incompatible reserve/limit values for container resources.

**Comment by joesims22** [comment] 2023-12-12 15:24
### Issue Recreate

I was able to recreate the issue in v2.8-head

1. Create a Rancher instance with v2.8.
2. Provision a downstream RKE1 single node all role cluster.
3. Create a new project, and under “Container Default Resource Limit” set the “Memory Reservation” value to 1000MiB and the “Memory Limit” value to 2MiB.
4. Create a namespace in the new project, and verify it successfully saves but errors are observed in Rancher logs.
5. Create another new project, and under "Container Default Resource Limit" set the "CPU Reservation" value to 2000mCPUs and the "CPU Limit" value to 1000m.
6. Create a namespace in the new project, and verify it successfully saves but errors are observed in Rancher logs.

**Issues observed**

- Rancher allows you to create a Project Container Default Resource Limit configuration where the default reservation for CPU/Memory exceeds the default limit for CPU/Memory, which causes an error when Rancher attempts to create the LimitRange object in the Project's namespace.

`2023/12/12 14:32:04 [ERROR] error syncing 'nc1': handler resourceQuotaSyncController: LimitRange "default-8fwx6" is invalid: spec.limits[0].defaultRequest[memory]: Invalid value: resource.Quantity{i:resource.int64Amount{value:1048576000, scale:0}, d:resource.infDecAmount{Dec:(*inf.Dec)(nil)}, s:"1000Mi", Format:"BinarySI"}: default request value 1000Mi is greater than default limit value 2Mi, requeuing`

`2023/12/12 14:45:34 [ERROR] error syncing 'nc2': handler resourceQuotaSyncController: LimitRange "default-bl79r" is invalid: spec.limits[0].defaultRequest[cpu]: Invalid value: resource.Quantity{i:resource.int64Amount{value:2, scale:0}, d:resource.infDecAmount{Dec:(*inf.Dec)(nil)}, s:"2", Format:"DecimalSI"}: default request value 2 is greater than default limit value 1, requeuing`

**Comment by joesims22** [comment] 2023-12-12 21:12
> ## QA TEST PLAN
> ### Test Cases

> **1)	Creating Project Container Default Resource Limit CPU/Memory configuration individually**
> **2)	Creating Project Container Default Resource Limit CPU/Memory configuration together**
> 
> # 1 Creating Project Container Default Resource Limit CPU/Memory configuration individually
> 
> 
> **Test Steps:**
> 
> 1. Create a single node docker Rancher instance with v2.8-head.
> 2. Provision a downstream RKE1 single node all role cluster.
> 3. Create a new project, and under Container Default Resource Limit set the “Memory Reservation” value to 1000MiB and the “Memory Limit” value to 2MiB.
> 4. Create a namespace in the new project.
> 5. Verify that Rancher throws an error regarding the CPU Reservation/Limit
> 6. Check the Rancher logs to verify the error creating the LimitRange object (docker <container-name> logs)
> 7. Create a new project, and under “Container Default Resource Limit” set the “CPU Reservation” value to 2000mCPUs and the “CPU Limit” value to 1000mCPUs.
> 8. Create a namespace in the new project.
> 9. Verify that Rancher throws an error.
> 10. Check the Rancher logs to verify the error creating the LimitRange object (docker <container-name> logs)
>
>
> # 2 Creating Project Container Default Resource Limit CPU/Memory configuration together
> 
> 
> **Test Steps:**
> 
> 1. Create a single node docker Rancher instance with v2.8-head.
> 2. Provision a downstream RKE1 single node all role cluster.
> 3. Create a new project, and under Container Default Resource Limit set the “CPU Reservation” value to 2000mCPUs and the “CPU Limit” value to 1000mCPUs. Also, set the “Memory Reservation” value to 1000MiB and the “Memory Limit” value to 1000MiB. 
> 4. Create a namespace in the new project.
> 5. Verify that Rancher throws an error regarding the CPU Reservation/Limit
> 6. Check the Rancher logs to verify the error creating the LimitRange object `docker <container-name> logs`
> 7. Create a new project, and under Container Default Resource Limit set the “CPU Reservation” value to 1000mCPUs and the “CPU Limit” value to 1000mCPUs. Also, set the “Memory Reservation” value to 2000MiB and the “Memory Limit” value to 1000MiB.
> 8. Create a namespace in the new project.
> 9. Verify that Rancher throws an error regarding the Memory Reservation/Limit
> 10. Check the Rancher logs to verify the error creating the LimitRange object `docker <container-name> logs`
> 11. Create a new project, and under Container Default Resource Limit set the “CPU Reservation” value to 2000mCPUs and the “CPU Limit” value to 1000mCPUs. Also, set the “Memory Reservation” value to 2000MiB and the “Memory Limit” value to 1000MiB.
> 12. Verify that Rancher throws an error regarding the CPU and Memory Reservation/Limit
> 13. Check the Rancher logs to verify the error creating the LimitRange objects `docker <container-name> logs`

**Comment by maxsokolovsky** [comment] 2024-02-13 18:02
## QA Testing

### Root cause

Neither norman nor webhook had any validation for container resource default limits. Users were free to create invalid
requests and limits for resources, which led to Rancher's controller being stuck in an error loop trying to create the
corresponding LimitRange objects, which the Kubernetes API server kept rejecting.

### What was fixed, or what changes have occurred

We added validation to the webhook, so that it blocks the creation of projects that have invalid container resource
default limit configuration.

### Areas or cases that should be tested

Creating a project with different values for container resource default limit configuration.

### What areas could experience regressions?

### Steps

1. Run Rancher with a custom build of the webhook (or an RC released with the change).
2. Create a project (try both a local and remote cluster).
3. Specify Container Default Resource Limits. Validation mimics the upstream behavior of the Kubernetes API server when
   it validates LimitRanges. The container default resource configuration must have properly formatted quantities for
   all requests and limits. Limits for any resource must not be less than requests.
    1. Negative values are fine.
    2. Equal values for request and limit for any resource are fine.
    3. Bad values, like "apple", cause an error.
    4. Set a resource to be greater than the limit and expect an error.
    5. Note that the GPU resource has no effect, it just exists in the UI, ignore it. Test with CPU and memory only.

**Comment by Priyashetty17** [comment] 2024-02-13 19:20
@maxsokolovsky could you please create a webhook RC? Also, a rancher PR might be needed to reference the webhook RC.

**Comment by Priyashetty17** [comment] 2024-03-07 15:24
Moving this back to QA-Next-Up as there are 2.8-Next1 issues that are ready to test. Will get back to this after 2.8 issues are done.

**Comment by Priyashetty17** [comment] 2024-04-05 20:41
All scenarios identified in the test plan have been validated with `v2.9-ca18e7126d90c20c720dd570ea900c357baafa93-head`.

**Closed by Priyashetty17** 2024-04-05 20:41 UTC
Labels: kind/bug, priority/1, area/projects, QA/L, JIRA, size/2, kind/tech-debt, team/frameworks

**Comment by maxsokolovsky** [comment] 2024-07-31 18:52
# Release note

Rancher now validates Container Default Resource Limit on Projects.

Validation mimics the upstream behavior of the Kubernetes API server when it validates LimitRanges. The container default resource configuration must have properly formatted quantities for all requests and limits.

Limits for any resource must not be less than requests.
