### ISSUE TITLE
Fail to create different type of port mapping for the same container port

### ISSUE THREAD

**Issue by zionwu** [rancher/rancher#12626] opened 2018-04-11 07:44 UTC
**Rancher versions:**
rancher/server:lastet 03/11

**Steps to Reproduce:**
1. Create a workload with two port mapping , one is `Load Balancer`, another is `Every Node`, both use 80 as containerPort.

![image](https://user-images.githubusercontent.com/1213386/38602984-ff7ea12e-3d9e-11e8-9128-1b3f8862c378.png)

2. Click `Save` and there is error `Validation failed in API: Deployment.apps "testabc" is invalid: spec.template.spec.containers[0].ports[1].name: Duplicate value: "tcp80"`

![image](https://user-images.githubusercontent.com/1213386/38603032-13eb7006-3d9f-11e8-886c-c38c7f01370d.png)

![image](https://user-images.githubusercontent.com/1213386/38603046-1ae55b9c-3d9f-11e8-8c0c-e4a843d90d9b.png)

If this is not a valid case, UI should not allow user to perform such behavior.  
If this is a valid case, backend should not use `tcp` and `containerPort` for the name.
The root cause is this line in aggregate_store.go :
```
port["name"] = fmt.Sprintf("%s%s", strings.ToLower(convert.ToString(port["protocol"])), strconv.Itoa(int(containerPort)))
```

**Comment by zionwu** [comment] 2018-04-11 07:50
If I change the container port for the second one, the workload can be created, but only the service of `Load Balance` is created

**Comment by alena1108** [comment] 2018-04-11 16:30
Duplicate of https://github.com/rancher/rancher/issues/11761

**Closed by alena1108** 2018-04-11 16:30 UTC
Labels: area/service, kind/bug, version/2.0
