### ISSUE TITLE
kubectl client version needs to be updated to latest in rancher

### ISSUE THREAD

**Issue by soumyalj** [rancher/rancher#15683] opened 2018-09-18 18:05 UTC
**Rancher versions:**
rancher/server or rancher/rancher:v2.1.0-rc2

**Steps to Reproduce:**
1. Create a rke cluster using Rancher
Cluster with Kuberentes versionv1.11.3(latest) gets created by default.
2. Launch kubectl through rancher UI
Server version points to v1.11.3
Client version points to v1.10.5
<img width="1645" alt="screen shot 2018-09-18 at 11 03 30 am" src="https://user-images.githubusercontent.com/18536626/45707032-978a9200-bb32-11e8-8f65-a2523bb3a1bc.png">

Client version needs to be updated to v1.11.3

**Comment by alena1108** [comment] 2019-03-12 06:24
Closing as a duplicate of https://github.com/rancher/rancher/issues/18676

**Closed by alena1108** 2019-03-12 06:24 UTC
Labels: kind/bug, priority/2, team/ca, version/2.0
