### ISSUE TITLE
API Tokens seem to fail after initial session times out

### ISSUE THREAD

**Issue by cloudnautique** [rancher/rancher#8214] opened 2017-03-17 17:53 UTC
**Rancher Versions:**
Server: 1.4.1

Using AzureAD, account based API tokens fail after the initial session times out. We need to verify that when an api key is used that we can create new sessions with the backend.

**Comment by kelchm** [comment] 2017-03-17 18:16
Thanks for opening an issue @cloudnautique. I'm still trying to find a 100% reliable way to reproduce this issue, but if there are any further details I can provide please just let me know.

**Comment by kelchm** [comment] 2017-03-20 13:24
One further update to this -- I think there is another level of complexity here.

It seems that this is related to the API key being created under a `User` vs `Local User`. Going to continue working on a reliable way to reproduce the issue.

**Comment by tfiduccia** [comment] 2017-03-20 21:39
@kelchm - hello, I can't currently reproduce your issue.  So a couple of things might help me.
1.  When the API key is created, what "kind" of user is creating and using the API key (is it a Admin or User)?
2.  What type of API key are you using?  It is a Account API key or a Environment key?
3.  Does it always fail on the same API call?
4.  I'm not sure the difference between a "User" vs "Local user"?

**Comment by kelchm** [comment] 2017-03-21 19:33
@tfiduccia 

>1. When the API key is created, what "kind" of user is creating and using the API key (is it a Admin or User)?

The user is an admin.

>2. What type of API key are you using? It is a Account API key or a Environment key?

I am creating an account API key that is used for multiple environments.

>3. Does it always fail on the same API call?

Yes, but admittedly I have not tested other rancher commands extensively. The error message I receive when running `rancher up ...` is: `time="2017-03-20T12:46:46Z" level=fatal msg="Failed to read project: Failed to find the current environment"`

>4. I'm not sure the difference between a "User" vs "Local user"?

This seems to be the root of the issue... I've noticed when adding a user to an environment that the user can either be added as a 'User' (IE: a user from Azure AD) or as a 'Local User' (IE: a user **NOT** from Azure AD). I have not had a recurrence of this bug since adding the 'local' version of this user to each of the environments.

Please let me know if you have any other questions.

**Comment by tfiduccia** [comment] 2017-03-27 22:34
It looks like before you enabled AzureAD, you enabled Local Authentication and added a few accounts.  Switching authentications is not suggested and they don't mix.    If you do switch.. you have to completely remove/delete all the users from previous authentication method and restart.  

If you are using any other authentication method besides Local, you should not (and shouldn't be able to) add user's that are outside.

**Comment by kelchm** [comment] 2017-03-30 15:31
@tfiduccia, I did in fact enable local auth before switching to Azure AD.

FWIW, the GUI makes no mention of there being issues between switching between authentication methods (IE: disable local auth, then enable Azure AD.) I'd argue that the current design encourages that user to quickly switch authentication via the GUI. At the very least there could be a warning presented when disabling auth that specific actions need to be taken before switching to another authentication type.

**Comment by tfiduccia** [comment] 2017-03-30 17:30
@kelchm - We do have multiple issues already been entered surrounding this area.  But the warning is not a bad idea.  I do know that at some point we have talked about support for multiple authentication types.  For now, I'm going to go ahead and close this and will talk about the warning with the developers.  Thanks!

**Closed by tfiduccia** 2017-03-30 17:30 UTC
