### ISSUE TITLE
"unable to create impersonator account ... serviceaccounts not found" error after upgrade from 2.5.9 to 2.6.0

### ISSUE THREAD

**Issue by cmurphy** [rancher/rancher#34824] opened 2021-09-20 17:19 UTC
**Rancher Server Setup**
- Rancher version: 2.6.0
- Installation option (Docker install/Helm Chart): ?
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): ?
- Proxy/Cert Details: ?

**Information about the Cluster**
- Kubernetes version: ?
- Cluster Type (Local/Downstream): downstream
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider):

**Describe the bug**

From https://github.com/rancher/rancher/issues/34671#issuecomment-922883807:

> Not sure if that's exactly the same issue, but it may be:

![image](https://user-images.githubusercontent.com/1220710/134045468-8e83d175-fb17-470d-a06b-795b0eeb88b5.png)

> I just upgraded a Rancher cluster from 2.5.9 to 2.6.0. It now fails to upgrade the agent in the downstream cluster.

> No keycloak is in use, but we use FreeIPA authentication, if that matters.

**To Reproduce**
 

**Result**

**Expected Result**

**Screenshots**

**Additional context**

Created from issue https://github.com/rancher/rancher/issues/34671#issuecomment-922883807. May be related to https://github.com/rancher/rancher/issues/34187.

**Comment by ankit-ls** [comment] 2021-09-21 10:26
Experiencing the same issue after `2.6.0` upgrade.

After downloading the kubeconfig, and running `kubectl` the following error is being observed:
```
$ k get nodes
Error from server (InternalError): an error on the server ("unable to create impersonator account: error setting up impersonation for user u-qwerty123: failed to get secret for service account: cattle-impersonation-system/cattle-impersonation-u-qwerty123, error: serviceaccounts \"cattle-impersonation-system/cattle-impersonation-u-qwerty123\" not found") has prevented the request from succeeding
```

Though the UI is successfully able to display the nodes:
<img width="1280" alt="Screenshot 2021-09-21 at 3 53 20 PM" src="https://user-images.githubusercontent.com/87482092/134154756-c1a4efac-d634-49b1-a257-a62f8ed7ed5c.png">

**Comment by cmurphy** [comment] 2021-09-21 15:56
@tuxpeople could you [enable trace logging](https://rancher.com/docs/rancher/v2.0-v2.4/en/troubleshooting/logging/#how-to-configure-a-log-level) on the rancher server for a short time and show any logs related to "impersonation" or "impersonator"? Could you check on the downstream cluster whether the service account is in fact there `kubectl -n cattle-impersonation-system get serviceaccount`?

How many nodes are in your local RKE1 cluster? How many in the downstream RKE1 cluster, and how was that deployed? RKE1 on existing nodes, cloud provider, or imported?

**Comment by cmurphy** [comment] 2021-09-21 17:07
@ankit-ls if you're able to share any logs or details of your deployment that would be helpful too.

**Comment by tuxpeople** [comment] 2021-09-22 11:28
@cmurphy Hi Colleen

There are service accounts in the downstreamcluster, but not the one he complains about:
```
[root@rancher-test-001 ~]# kubectl -n cattle-impersonation-system get serviceaccount
NAME                                SECRETS   AGE
cattle-impersonation-u-47gxn        1         46h
cattle-impersonation-u-63pxstdqwp   1         46h
cattle-impersonation-u-dvgrzbbuyx   1         46h
cattle-impersonation-u-gykbp3it2p   1         46h
cattle-impersonation-u-j2jv9        1         46h
cattle-impersonation-u-mxl2w3kt73   1         46h
cattle-impersonation-u-pegwa4vgkj   1         46h
cattle-impersonation-u-t2lawztxdm   1         46h
cattle-impersonation-u-wqajade3yl   1         46h
cattle-impersonation-u-zflcmvxsm4   1         46h
cattle-impersonation-user-tx2zz     1         46h
default                             1         46h
```

The management Cluster consists of 3 Nodes, the downstream cluster consists of 6 nodes (3 Worker, 3 Controlplane). Downstream cluster was deployed out of Rancher, "existing nodes" with the docker command Rancher displays. The cluster is not very new, but I can't tell you which was the first version we installed. But I remember to already upgrade this cluster to 2.5 back when that was released.

```
[root@rancher-test-001 ~]# export KUBECONFIG=/home/rancher/kube_config_rancher-cluster.yml
[root@rancher-test-001 ~]# kubectl get nodes
NAME            STATUS   ROLES                      AGE    VERSION
XX.XXX.XX.XXX   Ready    controlplane,etcd,worker   536d   v1.21.5
XX.XXX.XX.XXY   Ready    controlplane,etcd,worker   536d   v1.21.5
XX.XXX.XX.XXZ   Ready    controlplane,etcd,worker   536d   v1.21.5
[root@rancher-test-001 ~]# 
[root@rancher-test-001 ~]# export KUBECONFIG=/home/rancher/downstreamcluster-config.yml
[root@rancher-test-001 ~]# kubectl get nodes
NAME           STATUS   ROLES               AGE    VERSION
kln-test-001   Ready    worker              404d   v1.20.6
kln-test-002   Ready    worker              404d   v1.20.6
kln-test-003   Ready    worker              152d   v1.20.6
kms-test-001   Ready    controlplane,etcd   404d   v1.20.6
kms-test-002   Ready    controlplane,etcd   404d   v1.20.6
kms-test-003   Ready    controlplane,etcd   404d   v1.20.6
```

As for the logs, please find them attached. I tried to capture the interesting part (cut stuff away from before and after, but nod from between). Let me know if you need more:

[rancher-log.txt](https://github.com/rancher/rancher/files/7210230/rancher-log.txt)

As Rancher complains about secrets, here's also a list of them in the downstreamcluster:
```
[root@rancher-test-001 ~]# kubectl -n cattle-impersonation-system get secrets
NAME                                            TYPE                                  DATA   AGE
cattle-impersonation-u-47gxn-token-fwgkb        kubernetes.io/service-account-token   3      47h
cattle-impersonation-u-63pxstdqwp-token-5hdjg   kubernetes.io/service-account-token   3      47h
cattle-impersonation-u-dvgrzbbuyx-token-sk7h7   kubernetes.io/service-account-token   3      47h
cattle-impersonation-u-gykbp3it2p-token-swhjf   kubernetes.io/service-account-token   3      47h
cattle-impersonation-u-j2jv9-token-5btr7        kubernetes.io/service-account-token   3      47h
cattle-impersonation-u-mxl2w3kt73-token-zhxkr   kubernetes.io/service-account-token   3      47h
cattle-impersonation-u-pegwa4vgkj-token-cfrlr   kubernetes.io/service-account-token   3      47h
cattle-impersonation-u-t2lawztxdm-token-z7t77   kubernetes.io/service-account-token   3      47h
cattle-impersonation-u-wqajade3yl-token-wvpp9   kubernetes.io/service-account-token   3      47h
cattle-impersonation-u-zflcmvxsm4-token-d6466   kubernetes.io/service-account-token   3      47h
cattle-impersonation-user-tx2zz-token-pnpzf     kubernetes.io/service-account-token   3      47h
default-token-5krdc  
```

**Comment by cmurphy** [comment] 2021-09-22 14:05
@tuxpeople could you enable TRACE logs with

`$ kubectl -n cattle-system get pods -l app=rancher --no-headers -o custom-columns=name:.metadata.name | while read rancherpod; do kubectl -n cattle-system exec $rancherpod -c rancher -- loglevel --set trace; done`

and send the logs related to "impersonation" or "impersonator"?

> There are service accounts in the downstreamcluster, but not the one he complains about:

That's good information, are there any other warning or error logs in rancher about user u-jfyttf5ej2?

**Comment by tuxpeople** [comment] 2021-09-22 14:41
@cmurphy My apologizes, I over-read your "trace" and just copy/pasted "debug" from the linked webpage. Here's a piece of log file, hopefully it helps (slightly redacted):
[log2.txt](https://github.com/rancher/rancher/files/7211526/log2.txt)

> That's good information, are there any other warning or error logs in rancher about user u-jfyttf5ej2?

I found some while grep trough this new log file. But nothing special except for the not existing, I think.

I wantet to know who this user is. At <RANCHER-URL>/dashboard/c/local/auth/management.cattle.io.user I see the users but none of them has this ID. But I also don't see myself there, but as I connected the external auth, I may be tied to the "admin" user, which is on that list.

I tried to directly access <RANCHER-URL>/dashboard/c/local/auth/management.cattle.io.user/u-jfyttf5ej2#gp which brings me to the "User: System account for Cluster c-g9q7w". I attached below screenshots from the 4 tabs of the permissions, maybe that system account "lost" some permissions?

![Bildschirmfoto 2021-09-22 um 16 38 17](https://user-images.githubusercontent.com/1506076/134364958-7ce21c59-3a1f-4600-9311-31134d0e31bb.png)
![Bildschirmfoto 2021-09-22 um 16 38 23](https://user-images.githubusercontent.com/1506076/134364955-1dd2cd5f-19dd-4179-bac2-9383c94aa8af.png)
![Bildschirmfoto 2021-09-22 um 16 38 31](https://user-images.githubusercontent.com/1506076/134364953-b96bf6de-fe8f-48bb-b416-615090ca219d.png)
![Bildschirmfoto 2021-09-22 um 16 38 41](https://user-images.githubusercontent.com/1506076/134364945-19b50001-90bf-484e-931f-d61a39ab2d4a.png)

**Comment by difrost** [comment] 2021-09-22 16:32
Hi @cmurphy 
Looks like I've stepped into the same issue:
- both clusters RKE provisioned: 1.20.10
- Upgrade from Rancher 2.5.9 to 2.6.0

I've got a bit different message, UI is showing:
Error while applying agent YAML, it will be retried automatically: exit status 1, Error from server (InternalError): an error on the server ("unable to create impersonator account: error setting up impersonation for user u-zj7uehpdv3: the server rejected our request for an unknown reason (post namespaces.meta.k8s.io)") has prevented the request from succeeding

The server logs starts from:
`2021/09/22 15:49:52 [ERROR] error syncing 'c-vx5mv/creator-cluster-owner': handler cluster-crtb-sync: couldn't ensure service account impersonator: the 
server rejected our request for an unknown reason (post namespaces.meta.k8s.io), requeuing
2021/09/22 15:49:52 [ERROR] error syncing 'p-nqfbd/u-yzamxjvdq6-member': handler cluster-prtb-sync: couldn't ensure service account impersonator: the se
rver rejected our request for an unknown reason (post namespaces.meta.k8s.io), requeuing
2021/09/22 15:49:52 [ERROR] error syncing 'p-j2mcn/u-huumhjsp6q-member': handler cluster-prtb-sync: couldn't ensure service account impersonator: the se
rver rejected our request for an unknown reason (post namespaces.meta.k8s.io), requeuing
2021/09/22 15:49:52 [ERROR] error syncing 'c-vx5mv/u-zj7uehpdv3-admin': handler cluster-crtb-sync: couldn't ensure service account impersonator: the ser
ver rejected our request for an unknown reason (post namespaces.meta.k8s.io), requeuing
2021/09/22 15:49:52 [ERROR] error syncing 'p-nqfbd/creator-project-owner': handler cluster-prtb-sync: couldn't ensure service account impersonator: the 
server rejected our request for an unknown reason (post namespaces.meta.k8s.io), requeuing
2021/09/22 15:49:52 [ERROR] error syncing 'p-j2mcn/creator-project-owner': handler cluster-prtb-sync: couldn't ensure service account impersonator: the 
server rejected our request for an unknown reason (post namespaces.meta.k8s.io), requeuing`

I can see repeated:
`2021/09/22 16:07:42 [ERROR] error syncing 'c-vx5mv': handler cluster-deploy: Error while applying agent YAML, it will be retried automatically: exit status 1, Error from server (InternalError): an error on the server ("unable to create impersonator account: error setting up impersonation for user u-zj7uehpdv3: the server rejected our request for an unknown reason (post namespaces.meta.k8s.io)") has prevented the request from succeeding , requeuing`

**Comment by cmurphy** [comment] 2021-09-22 20:18
@tuxpeople thanks for all the information, this has been really helpful. I've proposed a PR that should address the issue.

> I wanted to know who this user is. At /dashboard/c/local/auth/management.cattle.io.user I see the users but none of them has this ID.

The user that Rancher is complaining about is a service user and so it doesn't show up in the list of regular users in the UI. However, you can confirm that the user exists by running `kubectl get user u-jfyttf5ej2` on the local cluster.

> But I also don't see myself there, but as I connected the external auth, I may be tied to the "admin" user, which is on that list.

Correct, when using external auth your own user gets tied to the admin user and that is what will appear on the list.

For QA: although I haven't been able to naturally get my test system into the state that @tuxpeople describes, I can fake the problem by manually deleting a user's impersonation service account from the downstream cluster (`kubectl -n cattle-impersonation-system delete sa cattle-impersonation-user-abcde`) and then trying to use kubectl as that user on the downstream cluster.

@difrost this looks like a separate issue and I think is not directly related to the impersonation subsystem that we're addressing in this issue. Are you able to use any kubectl command on the downstream cluster? Can you check if any of these issues could be possible explanations for what you're seeing:

- misconfiguration of the load balancer: https://github.com/k3s-io/k3s/issues/1437
- problem with the CNI: https://unofficial-kubernetes.readthedocs.io/en/latest/getting-started-guides/kubeadm/#troubleshooting-troubleshooting
- problem with Istio: https://github-wiki-see.page/m/istio/istio/wiki/Troubleshooting-Istio#diagnostics

**Comment by tuxpeople** [comment] 2021-09-23 05:09
@cmurphy Your help is highly appreciated! Never had a such good and fast response on an issue here for Rancher before. 

Out of curiosity: I assume your patch will be included in 2.6.1. Can I just install 2.6.1 and it's going to magically working again or do I have to do manual steps to get the cluster working again?

**Comment by difrost** [comment] 2021-09-23 08:09
@cmurphy Thanks for quick turnaround. Indeed this was not a Rancher issue, I've managed to fix it - on downstream cluster a webhook was rejecting requests. 

Cheers!

**Comment by cmurphy** [comment] 2021-09-23 16:44
@tuxpeople yes, this will be included in 2.6.1, and upgrading will automatically fix it.

@difrost glad to hear it!

**Comment by sowmyav27** [comment] 2021-09-27 19:09
On 2.6.0, reproduced the issue as Colleen has mentioned [here](https://github.com/rancher/rancher/issues/34824#issuecomment-925298900) 

**Steps:**

- Deploy a downstream rke2 cluster
- delete the SA in the downstream cluster `kubectl -n cattle-impersonation-system delete sa <sa-name>`
- Download kubeconfig from the cluster on rancher UI
- access the kubectl of this cluster from local terminal using this kubeconfig
- Error seen:

```
Error from server (InternalError): an error on the server ("unable to create impersonator account: error setting up impersonation for user u-lxbxl: failed to get secret for service account: cattle-impersonation-system/cattle-impersonation-u-lxbxl, error: serviceaccounts \"cattle-impersonation-system/cattle-impersonation-u-lxbxl\" not found") has prevented the request from succeeding
```

**On 2.6-head commit id: `fe57abd`**

- Deploy a downstream rke2 cluster
- delete the SA in the downstream cluster `kubectl -n cattle-impersonation-system delete sa <sa-name>`
- Download kubeconfig from the cluster on rancher UI
- access the kubectl of this cluster from local terminal using this kubeconfig
- The SA gets recreated

```
> kubectl -n cattle-impersonation-system get sa
NAME                                SECRETS   AGE
cattle-impersonation-u-25kz2efowx   1         12s
cattle-impersonation-u-gqj49        1         4s
default                             1         11m
```

**Closed** 2021-09-27 19:15 UTC
Labels: [zube]: QA Working

**Comment by mrlnstpn** [comment] 2022-08-11 07:24
The workaround that works for us to fix this is by doing a rolling restart on the rancher deployment.

`kubectl rollout restart deploy rancher -n cattle-system`

**Comment by nicklasfrahm** [comment] 2022-08-17 08:40
This is still an issue with Rancher `v2.6.6` and an AKS cluster with version `1.22.6`.

**Comment by gomker** [comment] 2023-03-01 16:53
> I can also confirm that this issue exists on Rancher `v2.6.6`, with an AKS direct imported cluster. I further verified that it is an issue exclusive to AKS clusters. I took the same cluster, and added it to Rancher the "old" way as a generic cluster, the issue no longer exists. So it very much seems to me like it is an issue with the way Rancher imports an AKS cluster.
> 
> EDIT: I kept digging, and I was incorrect. This doesn't have to do with AKS in my case. For me, this was a simple incompatibility with the kubernetes version. We upgraded to k8s v24 a while back. Existing rbac through Rancher kept working. But new users were having issues. The fix was to upgrade Rancher from 2.6.6 to 2.6.8, which is compatible with k8s v24.

Thank you @De1taE1even  

I can confirm moving to v2.6.9 ( I specfied 2.6.8 but "stable" did whatever it does) and works with AKS K8 version 1.25.5

**Comment by Buzzglo** [comment] 2023-10-16 21:00
Encountered this on 2.6.10

**Comment by aprilrieger** [comment] 2023-11-21 01:00
Encountered on 2.7.8
