### ISSUE TITLE
[BUG] vSphere CPI add-on configuration no longer available in the Rancher UI

### ISSUE THREAD

**Issue by datamattsson** [rancher/rancher#39629] opened 2022-11-16 23:18 UTC
**Rancher Server Setup**
- Rancher version: 2.6.9, 2.7.0

**Describe the bug**

I was running 2.6.9 and the vSphere CPI option vanished in the UI and I also noticed 1.24.7+rke2 had appeared in my deployment options. It was 1.24.4+rke2 yesterday or the day before that.

**To Reproduce**

Create vSphere cluster from Rancher UI, select vSphere cloud provider and go to Add-On config. vSphere CPI is no longer there.

**Result**

Can't launch new clusters on vSphere.

**Expected Result**

Being able to launch clusters like yesterday.

**Comment by David-VTUK** [comment] 2022-11-17 10:14
Rancher/dashboard issue for reference #39462

**Comment by datamattsson** [comment] 2022-11-17 17:12
> Likely a duplicate of #39462

I'm missing CPI UI elements, not CSI, which #39462 talks about.

I went through the hoops of upgrading my manager cluster to `v1.24.6-rancher1-1` (RKE1) without seeing any improvements.

**Comment by slickwarren** [comment] 2022-11-17 19:28
This is reproducible on v2.7.0, which is related to the linked issue (but seems to be complimentary to that one):
* deploy a vsphere rke2 cluster from local cluster v1.24.7 (also tested with v1.23.13):
  * enable the vsphere cloud provider
  * navigate to add-on config tab
  * observe that only CSI options are available in the UI (No CPI options)
 I agree that this is a duplicate of the root of the linked issue, but the behavior has changed: https://github.com/rancher/rancher/issues/39462#issuecomment-1302132086

**Closed** 2022-11-17 19:29 UTC
Labels: kind/bug, status/duplicate
