### ISSUE TITLE
Privileged doesn't work

### ISSUE THREAD

**Issue by Miminoux** [rancher/rancher#10000] opened 2017-10-03 14:37 UTC
**Rancher versions:**
rancher/server: 1.6.7
rancher/agent: 1.2.5

**Infrastructure Stack versions:**
healthcheck: 0.3.1
ipsec: 0.11.7
network-services: 0.9.3 + 0.7.7
scheduler: 0.8.2
kubernetes (if applicable): nope
rancher-nfs : 0.8.5

**Docker version: (`docker version`,`docker info` preferred)**
Docker version : 
Client:
 Version:      1.12.6
 API version:  1.24
 Go version:   go1.6.4
 Git commit:   78d1802
 Built:        Tue Jan 10 20:17:57 2017
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.6
 API version:  1.24
 Go version:   go1.6.4
 Git commit:   78d1802
 Built:        Tue Jan 10 20:17:57 2017
 OS/Arch:      linux/amd64

Docker info : 
Containers: 25
 Running: 19
 Paused: 0
 Stopped: 6
Images: 56
Server Version: 1.12.6
Storage Driver: aufs
 Root Dir: /data/docker/aufs
 Backing Filesystem: extfs
 Dirs: 353
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local rancher-nfs
 Network: host null bridge overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options:
Kernel Version: 3.16.0-4-amd64
Operating System: Debian GNU/Linux 8 (jessie)
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 1.963 GiB
Name: myNode
ID: CVVM:4CFG:...4E:VXJA:XEBD
Docker Root Dir: /data/docker
Debug Mode (client): false
Debug Mode (server): false
Http Proxy: http://myProxy:3128
Https Proxy: myProxy:3128
Registry: https://index.docker.io/v1/
WARNING: No kernel memory limit support
WARNING: No cpu cfs quota support
WARNING: No cpu cfs period support
Insecure Registries:
 {myArtifactory}:5003
 127.0.0.0/8

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
Linux myNode 3.16.0-4-amd64 #1 SMP Debian 3.16.39-1 (2016-12-30) x86_64 GNU/Linux
**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
VMware VM
**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle
**Steps to Reproduce:**
Docker file : 
FROM artifactory.intranet.atih.sante.fr:5003/alpine:latest
RUN apk update && apk add --update nfs-utils && rm -rf /var/cache/apk/*
RUN rm /sbin/halt /sbin/poweroff /sbin/reboot
ADD entry.sh /usr/local/bin/entry.sh
VOLUME /mnt
ENTRYPOINT ["/usr/local/bin/entry.sh"]

entry.sh : 
#! /bin/sh
echo set
set -m
echo rpc.startd
rpc.statd &
sleep 1
echo rpcbind
rpcbind -f &
sleep 1
echo mount
mount -t "${FSTYPE:=nfs4}" -o "${MOUNT_OPTIONS:=nfsvers=4}" "${SERVER:?manque le SERVER}:${SHARE:?manque le partage}" '/mnt'
sleep 1
echo check
mount | grep nfs
echo fg
fg

In rancher, new stack, new service with that image : 
SERVER=nfs-server
SHARE=myShare
Security : Privileged : check Full access to the host

get the logs (docker logs r-test-nfs-nfs-1-d11cdd24) in a file (>/tmp/rancher.log)

On the node, open a shell and run the container (toto) in privileged mode : 
docker run --rm -it --privileged=true -e SERVER=nfs-server -e SHARE=myShare --name toto nfs-client
(adapt the image name to use the same)
get log (docker logs toto) in a file (>/tmp/toto.log)
By the way, the container is doing what I'm expecting it to do.

Run the same without privileged=true (tata) : 
docker run --rm -it -e SERVER=nfs-server -e SHARE=myShare --name tata nfs-client
(adapt the image name to use the same)
get log (docker logs tata) in a file (>/tmp/tata.log)
By the way, the container is **not** doing what I'm expecting it to do.

**Results:**
Compare logs /tmp/toto.log, /tmp/tata.log to /tmp/rancher.log.
Launched with rancher, the container isn't working and is issuing the same logs as the container without privileged mode (rancher.log ~ tata.log) where the container with the privileged mode is issuing correct logs and working.

Any idea ? 
Something else : I ran docker inspect on the 3 container which gave me the same output : 
            "Privileged": true,

**Comment by Miminoux** [comment] 2017-10-03 14:41
Oh gosh, will I win something for being the 10 000th issuer ? ^^

**Comment by vincent99** [comment] 2017-10-03 19:39
I can get you a closed/unreproducible sticker, like so many of the other 9999... We don't have access to your artifactory, we don't know what you're "expecting it to do", and this is far too involved for a bug with the description "Privileged doesn't work".

Creating a service in the UI and selecting privileged works fine.  The resulting containers are privileged, as you've seen yourself.  You have some other unrelated problem not described here at all.

```
[docker@onesix-host1 ~]$ docker ps
CONTAINER ID        IMAGE                            COMMAND                  CREATED             STATUS              PORTS               NAMES
faab88a9e39d        ubuntu:14.04.3                   "/.r/r /bin/bash"        5 minutes ago       Up 5 minutes                            r-Another-privileged-1-5e0be5da

[docker@onesix-host1 ~]$ docker inspect faab88a9e39d | grep Privileged
            "Privileged": true,
```

**Comment by Miminoux** [comment] 2017-10-04 14:45
Hi,
Sorry, I did't run into details because I thought it was not relevant.
There is the Dockerfile and the entrypoint script above. Launching the image in rancher throws an error which seems to me related to insufficient privilege, this error is not launched in the standalone container unless I remove de privilege option.
This container is supposed to mount an NFS4 volume in /mnt (and share it but the share cannot work) but the problem is not exactly on "getting that specific container to work" but why isn' it having the same behavior running with rancher and in standalone (although I checked the privilege box in rancher) 
So that is my conclusion : the privilege checkbox may not work (at least, in that case). Sorry for my poor english, feel free to rename the issue with a more detailed title.

By the way, I managed to get things to work for me with NFSv3. This is done by changing the mount command to this : 
mount -t "${FSTYPE:=nfs}" -o ${MOUNT_OPTIONS:=nolock} "${SERVER:?missing nfs server}:${SHARE:?missing share name}" '/mnt'

Will I get that closed/unreproducible sticker like so many of the other 9,999 ? Please don't ^^
I ran deep into the issue form and forgot the most important thing : thanks a lot for such a good tool as Rancher. It does a great job !

Bye bye

**Comment by vincent99** [comment] 2017-10-04 15:56
You're jumping to a conclusion about a message that says something about permissions and then trying to solve a problem that isn't there.  The privileged flag is being sent down and set on the container.  You've seen It in the inspect yourself.  Privileged is not the problem.

Since it involves an NFS server the most obvious thing would be the server is saying "no" for some reason.  As I said before the two obvious differences are: 

- you're using managed networking by defaultin Rancher (so the source IP may be different)  

- and using rancher-dns instead of the host's (so the server name may be resolving to something different).

**Comment by Miminoux** [comment] 2017-10-05 07:10
Hi
Actually there is no nfs issue, no dns issue neither.
I jumped to that conclusion because I can reproduce the same error message in standalone container when I remove the privilege option.

In the end, if you strongly don't want to get it as an issue, go ahead. Get that holy shame sticker on this thread I don't mind. I wanted to contribute to the project, not to fight about my nfs dns and so on.

If not closed yet, I will paste the error when at work.

Bye

**Comment by Miminoux** [comment] 2017-10-05 08:20
Hi,
On the standalone container without the option I get this error on the "mount" command : 
flock: unrecognized option: e
BusyBox v1.26.2 (2017-06-11 06:38:32 GMT) multi-call binary.

Usage: flock [-sxun] FD|{FILE [-c] PROG ARGS}

[Un]lock file descriptor, or lock FILE, run PROG

        -s      Shared lock
        -x      Exclusive lock (default)
        -u      Unlock FD
        -n      Fail rather than wait
mount.nfs4: Operation not permitted
mount: permission denied (are you root?)

On the rancher container I get quite the same : 
flock: unrecognized option: e
BusyBox v1.26.2 (2017-06-11 06:38:32 GMT) multi-call binary.

Usage: flock [-sxun] FD|{FILE [-c] PROG ARGS}

[Un]lock file descriptor, or lock FILE, run PROG

        -s      Shared lock
        -x      Exclusive lock (default)
        -u      Unlock FD
        -n      Fail rather than wait
mount.nfs4: access denied by server while mounting devel-rancher-nfs-applis-siw:piramig
mount: permission denied (are you root?)

My lecture of it is that the rancher container had almost enough privileges but get an error whereas in the unprivileged container, the mount command detects the container detects he has no privilege.

Oh and if you have no NFS (and privileges) it says : 
mount.nfs4: Failed to resolve server devel-ranr-nfs-applis-siw: Name or service not known
or
mount.nfs4: requested NFS version or transport protocol is not supported

Bye

**Comment by loganhz** [comment] 2018-10-12 07:02
Thanks for your report!

With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.

If you think we should keep this issue open, please let me know.

**Closed by loganhz** 2018-10-12 07:02 UTC
Labels: kind/question, version/1.6
