### ISSUE TITLE
[BUG] project monitoring page - details section - metrics are not displaying

### ISSUE THREAD

**Issue by AndrewHoffmanQA** [rancher/rancher#39786] opened 2022-12-06 17:59 UTC
**Rancher Server Setup**
- Rancher version: v2.7.0
- monitoring version- 101.0.0+up19.0.3
- prom fed version- 1.0.0+up0.1.1

**Information about the Cluster**
- Kubernetes version: v1.24.4
- Cluster Type (Local/Downstream): local

**User Information**
-Admin user utilized. no RBAC in this bug

**Describe the bug**
after installing monitoring and Prometheus federator, and creating a project monitor the project monitors page, detail section does not populate with data from the project. 

note: summary page does display values
note: opening Grafana and checking the pod metrics there also displays no metrics

**To Reproduce**
1. navigate Apps > Charts
2. install monitoring
3. install prom federator
4.navigate to cluster > project/namespace
5. create a project 
6. create a namespace for the project you just created
7. navigate Monitoring > project monitors
8. create a new project monitor, select the name of the project you created
9. on the project monitoring page and the monitor you just created, click the blue text in the 'project' column

**Result**
user is sent to the project monitoring page. under project metrics tab > details section the user will see no data displayed for any of the 5 graphs.

if the user clicks Grafana and clicks on 'Rancher / pod' they will see the same thing.
**Expected Result**
metrics are displayed in these areas

**Screenshots**
<img width="1653" alt="image" src="https://user-images.githubusercontent.com/89030218/205986160-79b315ee-38a6-46c2-b893-d3dd4caf644d.png">

**Additional context**
video repro

https://user-images.githubusercontent.com/89030218/205986385-744df5dd-c822-486e-9cd5-9b94724fdeb2.mp4

**Comment by aiyengar2** [comment] 2022-12-09 01:11
@AndrewHoffmanQA this should be identical to https://github.com/rancher/rancher/issues/38934#issuecomment-1289428142, but shown on Project Monitoring V2 right?

Does your Monitoring V2 in this setup show the same issue described in the comment above?

**Comment by aiyengar2** [comment] 2022-12-09 01:12
I assume this is in an RKE1 cluster, can you try to reproduce this in an RKE2 1.24 cluster and see if the same occurs? If so, this might be a novel issue.

**Comment by PennyScissors** [comment] 2023-05-02 19:53
I tried reproducing this in different cluster types and k8s versions and I was not able to do it. It is possible this issue was fixed in the latest monitoring version since the version in this issue is pretty old.

Setup 1 - couldn't reproduce
Rancher 2.7-head ae27e81
K3s v1.25.5+k3s1
Prometheus Federator 2.0.1+up0.2.2
Monitoring 102.0.0+up40.1.2
![image](https://user-images.githubusercontent.com/8951271/235771187-5585ec9a-d581-4e1a-9984-976cfa0af2fe.png)


Setup 2 - couldn't reproduce
Rancher 2.7-head ae27e81
RKE2 v1.24.13+rke2r1 
Prometheus Federator 2.0.1+up0.2.2
Monitoring 102.0.0+up40.1.2
![image](https://user-images.githubusercontent.com/8951271/235771262-019fa5f2-416d-442a-be70-36d85efd6405.png)


Setup 3 - couldn't reproduce
Rancher 2.7-head ae27e81
RKE1 v1.24.13
Prometheus Federator 2.0.1+up0.2.2
Monitoring 102.0.0+up40.1.2
![image](https://user-images.githubusercontent.com/8951271/235771299-2f217b7a-cfa5-4f6c-8599-0f375d552331.png)

**Closed** 2023-05-03 17:18 UTC
Labels: kind/bug, priority/1, area/monitoring, [zube]: Next Up, team/area3, regression, status/cannot-reproduce
