### ISSUE TITLE
JS errors in cluster Alerts page

### ISSUE THREAD

**Issue by smallteeths** [rancher/rancher#22498] opened 2019-08-29 01:55 UTC
Rancher version v2.2.8

Steps to reproduce (least amount of steps as possible):
   1. Go to the cluster, route to Alerts page.
   2. Go to the Default project then Switch back to cluster.

Result:
Page operation does not affect
See JS errors in the console.

![Jietu20190829-093126](https://user-images.githubusercontent.com/27733391/63903423-eda0ce80-ca3f-11e9-8b57-b7fd14ba9cd5.jpg)

**Comment by davidnuzik** [comment] 2019-08-29 17:12
Version: v2.2.8

I have reproduced the issue exactly as smallteeths described with the same errors in the browser dev console.

Version: master-head (v2.3) (8/28/19)

The issue is NOT happening on the latest master-head image (upcoming v2.3 release); it will also successfully navigate back to the cluster page.


Considering this is a fairly minor issue (at least in my opinion) I would recommend upgrading to v2.3 once it's available for resolution to this issue.

**Comment by tfiduccia** [comment] 2019-09-03 23:53
I also tested this in master and am no longer able to reproduce.  @davidnuzik - can you please close as resolved.

**Comment by davidnuzik** [comment] 2019-09-04 16:03
Closing as resolved in upcoming v2.3 release. Refer to my last comment.

**Closed by davidnuzik** 2019-09-04 16:03 UTC
Labels: [zube]: To Test, area/alerting, kind/bug, team/ui
