### ISSUE TITLE
Unable to create k8s v1.24 downstream clusters using Oracle Linux 8.4

### ISSUE THREAD

**Issue by rishabhmsra** [rancher/rancher#38214] opened 2022-07-07 16:45 UTC
**Rancher Server Setup**
- Rancher version: v2.6-head(f08ea66)
- Installation option (Docker install/Helm Chart): Docker with **local** cluster : `v1.24.2+k3s1`
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc):

**Information about the Cluster**
- Kubernetes version: v1.24.2-rancher1-1
- Cluster Type (Local/Downstream): Downstream
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider): Custom and Node driver -> (1cp, 1etcd, 1w)

**User Information**
- What is the role of the user logged in? (Admin/Cluster Owner/Cluster Member/Project Owner/Project Member/Custom) Admin
  - If custom, define the set of permissions:

   
**Describe the bug**

- On rancher v2.6-head(f08ea66), downstream custom or node driver cluster provisioning using Oracle Linux 8.4 fails with below errors:
- Community AMI (ami-0eb9c7bb30e82c851) -> Custom cluster fails to come up Active with error `[[network] Host [<REDACTED>] is not able to connect to the following ports: [<REDACTED>:2379]. Please check network policies and firewall rules]`. Disabling the firewall on the nodes didn't solve the issue.
- Private AMIs (ami-04af5cab834369e3c,  ami-0a97aa701ceeffec6) -> Custom cluster comes up `Active` but after some time it goes into Unavailable state with error : `Cluster agent is not connected`
- Node Driver cluster -> It's failing with `[ERROR] error syncing 'c-bg24w/m-9w72h': handler node-controller: Error creating machine: RHEL ssh command error: command: sudo systemctl disable nm-cloud-setup.service nm-cloud-setup.timer err: exit status 1 output: Failed to disable unit: Unit file nm-cloud-setup.service does not exist., requeuing.`

**To Reproduce**
 
- Create rancher v2.6-head(https://github.com/rancher/rancher/commit/f08ea66a123c3fd74253e87f8d83282b205e748a) server(docker install)
- Deploy RKE1 downstream, Custom or Node Driver `v1.24.2-rancher1-1` k8s cluster(1c, 1e, 1w) using AMIs as mentioned in above section.
- Clusters will fail to come into Active state.

**Result**
- Cluster fails to come into Active state with OL 8.4.

**Expected Result**
- Cluster should come into Active state.

**Screenshots**

**Additional context**

**Comment by jiaqiluo** [comment] 2022-07-07 23:02
Updates from Dev:
1. The custom cluster does not work because changes in the default firewall in 8.4 prevent rke1 pods from reaching out to Rancher to connect to the cluster agent. This issue has been logged here and the fix is to run the following command on the VM

**Comment by jiaqiluo** [comment] 2022-07-11 19:15
Problem:
Original, we have the logic to disable the service "nm-cloud-setup.timer" and "nm-cloud-setup.service" on RHEL 8.4. It introduces two problems:

- The same logic is applied when the OS is Oracle Linux, but the services do not exist on OL.
- the services exist not only on RHEL 8.4; I also see them on RHEL 8.6 ( rancher will support 8.6 soon)

Fixes:
- instead of checking for a specific OS version, we now check OS ID.
- improve the logic for detecting and disabling the services.

Validations:

1. The scenarios mentioned in the issue should work now. Please also check [my previous comment ](https://github.com/rancher/rancher/issues/38214#issuecomment-1178348035)
2. Provsioning cluster whose OS is  RHEL 8.4  should continue working.

**Comment by jiaqiluo** [comment] 2022-07-11 20:23
can be tested on the latest v2.6-head

**Comment by rishabhmsra** [comment] 2022-07-14 13:01
Re-opening this issue

Validated on rancher v2.6(2c21373) -> docker install

Custom cluster:
- Created 3 ec2 VMs using OL AMI (ami-0eb9c7bb30e82c851)
- Ran below commands on VMs:
```
firewall-cmd --zone=public  --add-masquerade --permanent
firewall-cmd --reload
```
- Created a k8s v1.24.2-rancher1-1 custom cluster(1-cp, 1-e, 1-w), by running the registration command for etcd, cp and worker on the VMs.
- Cluster got stuck into provisioning state with error : `[[network] Host [<REDACTED>] is not able to connect to the following ports: [<REDACTED>:2379]. Please check network policies and firewall rules]`
- Also this [documents](https://github.com/rancher/rancher/issues/38214#:~:text=Update%3A%20if%20the%20above%20does%20not%20work%2C%20try%20https%3A//rancher.com/docs/rancher/v2.6/en/installation/resources/advanced/firewall/) seems to be for HA setup of rancher.

Node driver cluster:
- Provisioned a k8s v1.24.2-rancher1-1 cluster(1-cp. 1-e, 1-w), using OL community AMI (ami-0eb9c7bb30e82c851).
- Cluster got stuck into Provisioning state with msg : `Waiting for etcd, controlplane and worker nodes to be registered`
- Rancher server logs:
```
[ERROR] error syncing 'c-gx5sp/m-cvz8x': handler node-controller: Error creating machine: Error checking the host: Error checking and/or regenerating the certs: There was an error validating certificates for host "<REDACTED>:2376": Get "https://<REDACTED>:2376/version": dial tcp 3.22.27.165:2376: connect: no route to host, requeuing
```

**Comment by jiaqiluo** [comment] 2022-07-18 17:15
Node driver cluster using OL 8.4 is not supported, ie, they are not marked as supported in the matrix of 2.6.6 and the coming 2.6.7, so it is not surprising to see errors on the node driver downstream cluster.

**Comment by jiaqiluo** [comment] 2022-07-18 17:32
The custom cluster, which has a single node, works. ( OL 8.4 + RKE1 1.24)
The custom cluster, which has dedicated nodes, does not work.  ( OL 8.4 + RKE1 1.24)
The problem is that the process `dockerd` on the control plane node takes all the memory and makes the node unresponsive; thus, the cluster health check fails. 


The following are the output of `top` which shows dockerd tasks nearly all memory 
```
> top 
  PID USER      PR  NI    VIRT    RES    SHR S  %CPU  %MEM     TIME+ COMMAND
  882 root      20   0   18.3g  14.2g      0 S 279.0  92.4 124:38.69 dockerd
```


The following are the logs of the service `dockerd`
```
● docker.service - Docker Application Container Engine
   Loaded: loaded (/usr/lib/systemd/system/docker.service; enabled; vendor preset: disabled)
   Active: active (running) since Fri 2022-07-15 21:37:05 GMT; 13min ago
     Docs: https://docs.docker.com
 Main PID: 77889 (dockerd)
    Tasks: 28
   Memory: 1.2G
   CGroup: /system.slice/docker.service
           └─77889 /usr/bin/dockerd -H fd:// --containerd=/run/containerd/containerd.sock

Jul 15 21:37:11 ip-172-31-1-240.us-west-1.compute.internal dockerd[77889]: time="2022-07-15T21:37:11.088961139Z" level=info msg="ignoring event" container=664f9e7475961c28c7148d3e9510ebf8e8a2a43d97ca144d9a1ab1136fbbfc0c module=libcontainerd namespace=moby topic=/tasks/delete type="*events.TaskDelete"
Jul 15 21:37:38 ip-172-31-1-240.us-west-1.compute.internal dockerd[77889]: time="2022-07-15T21:37:38.620532283Z" level=info msg="ignoring event" container=b157ef9c5f347f181d1124149be9120a2592a836102bfe76e7636f9087bc8ca6 module=libcontainerd namespace=moby topic=/tasks/delete type="*events.TaskDelete"
Jul 15 21:37:43 ip-172-31-1-240.us-west-1.compute.internal dockerd[77889]: time="2022-07-15T21:37:43.665470795Z" level=info msg="ignoring event" container=59bf88f841b694f6a4bc9e99e5f70c80be941320bfc41d881870ada6aa5a01c7 module=libcontainerd namespace=moby topic=/tasks/delete type="*events.TaskDelete"
Jul 15 21:39:49 ip-172-31-1-240.us-west-1.compute.internal dockerd[77889]: time="2022-07-15T21:39:49.634590870Z" level=error msg="Handler for GET /v1.40/containers/30a958ae90c56497b980580684eca79c57593aa50f4096bc19575c4cceeb1b85/json returned error: write unix /var/run/docker.sock->@: write: broken pipe"
Jul 15 21:39:49 ip-172-31-1-240.us-west-1.compute.internal dockerd[77889]: http: superfluous response.WriteHeader call from github.com/docker/docker/api/server/httputils.WriteJSON (httputils_write_json.go:11)
Jul 15 21:39:49 ip-172-31-1-240.us-west-1.compute.internal dockerd[77889]: time="2022-07-15T21:39:49.757889077Z" level=error msg="Handler for GET /v1.40/containers/22404c4e33f84d2a14307456fdaab3b5a43650f257de8bbffde67533bb263298/json returned error: write unix /var/run/docker.sock->@: write: broken pipe"
Jul 15 21:39:49 ip-172-31-1-240.us-west-1.compute.internal dockerd[77889]: http: superfluous response.WriteHeader call from github.com/docker/docker/api/server/httputils.WriteJSON (httputils_write_json.go:11)
Jul 15 21:39:49 ip-172-31-1-240.us-west-1.compute.internal dockerd[77889]: time="2022-07-15T21:39:49.865447242Z" level=error msg="Handler for GET /v1.40/containers/22404c4e33f84d2a14307456fdaab3b5a43650f257de8bbffde67533bb263298/json returned error: write unix /var/run/docker.sock->@: write: broken pipe"
Jul 15 21:39:49 ip-172-31-1-240.us-west-1.compute.internal dockerd[77889]: http: superfluous response.WriteHeader call from github.com/docker/docker/api/server/httputils.WriteJSON (httputils_write_json.go:11)
Jul 15 21:45:34 ip-172-31-1-240.us-west-1.compute.internal dockerd[77889]: time="2022-07-15T21:45:34.277305785Z" level=info msg="ignoring event" container=5cc6c42d9050f1d30fd9f046222981bdbf0c714870a2d10081bbb01c96194afe module=libcontainerd namespace=moby topic=/tasks/delete type="*events.TaskDelete"
```

The temporary workaround is to restart `dockerd` service and prune docker. However, I see the process dockerd keeps taking more and more memory at a slower pace than before applying the workaround, so it will eventually use all memory and make the whole cluster unavailable again.

**Comment by jiaqiluo** [comment] 2022-08-12 21:43
The same error happens when using OL 8.6 with Docker 20.10.17 on a custom 1.24.2-rancher1-1 cluster on v2.6-head b8b95dc

**Comment by Sahota1225** [comment] 2022-10-18 21:13
Closing because its duplicate of https://github.com/rancher/rancher/issues/38816

**Comment by sowmyav27** [comment] 2022-12-30 17:21
Reopening, would like to keep this open since we call this OS as unsupported in our support matrix.

**Comment by vivek-infracloud** [comment] 2023-05-04 16:22
Tried installing docker with docker install script on VM with OL 8.7 and OL9.1. 
![Screenshot from 2023-05-04 13-49-09](https://user-images.githubusercontent.com/83208989/236264565-8dc9d50d-3e3d-4c5d-a59f-e058842cf121.png)
![Screenshot from 2023-05-04 14-06-02](https://user-images.githubusercontent.com/83208989/236264591-2e920aa0-62df-49d4-a5f8-0d1c402573cc.png)


The dokcer v23.0.2 installed successfully. But the node driver cluster creation fails with the error mentioned in the issue above.

**Closed** 2024-03-21 17:31 UTC
Labels: priority/1, kind/bug-qa, [zube]: Done, release-note, team/hostbusters, team/infracloud
