### ISSUE TITLE
Active Directory authentication takes a long time in v2.0.4

### ISSUE THREAD

**Issue by alexandrem** [rancher/rancher#14284] opened 2018-06-28 17:52 UTC
**Rancher versions:**
rancher/server or rancher/rancher: v2.0.4
rancher/agent or rancher/rancher-agent: v2.0.4

**Steps to Reproduce:**

Login with a ldap/AD user in v2.0.4 at the login screen or in the Security/Authentication admin page with the "Test and enable authentication" step.

**Results:**

There seems to be a regression in latest v2.0.4 with the AD authentication and possibly the navigation of the ldap database objects.

It takes more than 2 minutes to login with a user.

**Comment by twittyc** [comment] 2018-06-28 19:39
AD auth is failing for us with an internal server error after upgrading to 2.0.4 from 2.0.2

**Comment by mitchellmaler** [comment] 2018-06-28 19:44
We just upgraded Rancher from 2.0.2 to 2.0.4 and getting the same issues. When I try to log in it times out or returns an internal server error on the UI.

This works when I downgrade back to 2.0.2 with no configuration changes.

```2018/06/28 19:40:42 [ERROR] API error response 500 for POST /v3/activeDirectoryConfigs/activedirectory?action=testAndApply. Cause: server returned error for search DC=[removed],DC=[removed],DC=net (member:1.2.840.113556.1.4.1941:=CN=Maler\5c,Mitchell,OU=Users,OU=[removed],OU=Office Locations,DC=[removed],DC=[removed],DC=net): unable to read LDAP response packet: read tcp [ip address]:60800->[ip address]:3268: read: connection reset by peer: unable to read LDAP response packet: read tcp [ip address]:60800->[ip address]:3268: read: connection reset by peer
```

**Comment by pulberg** [comment] 2018-06-28 20:31
Also upgraded from v2.0.2 to v2.0.4 and seeing very long AD log in times.

**Comment by pulberg** [comment] 2018-06-28 21:41
@mrajashree I'm not sure on the count of principals in v2.0.2, but right now from /v3/principals I counted 310 instances of `"type": "principal"`

**Comment by alexandrem** [comment] 2018-06-28 21:55
@mrajashree I have 299 principal items.

I believe the new groups `member:1.2.840.113556.1.4.1941` subtree search here is the culprit:

https://github.com/rancher/rancher/blob/v2.0.4/pkg/auth/providers/activedirectory/activedirectory_client.go#L133-L171

**Comment by alexandrem** [comment] 2018-06-28 21:57
Also, yes this is an official Active Directory server.

**Comment by mitchellmaler** [comment] 2018-06-28 21:59
@mrajashree Yes, ours is our corporate Active Directory server.

**Comment by pulberg** [comment] 2018-06-28 22:41
I've used ldapsearch to troubleshoot previous AD login/password issues (Rancher v1.6.xx), and the experience from ldapsearch never matches the experience of logging in from Rancher.  That said, my ldapsearch queries return very quickly, but loggin in through Rancher is very slow.

`time ldapsearch -x -H ldap://abc.123.com -D "svcacct" -W -b "dc=123,dc=com" "cn=Phillip Ulberg" -s sub "(cn=*)" cn mail sn`

```Enter LDAP Password: 
# extended LDIF
#
# LDAPv3
# base <dc=123,dc=com> with scope subtree
# filter: cn=Phillip Ulberg
# requesting: (cn=*) cn mail sn 
#

# Phillip Ulberg, Users, rjf.com
dn: CN=Phillip Ulberg,CN=Users,DC=123,DC=com
cn: Phillip Ulberg
sn: Ulberg
mail: Phillip.Ulberg@123.com

# search reference
ref: ldap://DomainDnsZones.123.com/DC=DomainDnsZones,DC=123,DC=com

# search result
search: 2
result: 0 Success

# numResponses: 3
# numEntries: 1
# numReferences: 1

real    0m0.683s
user    0m0.006s
sys     0m0.003s
```

**Comment by mrajashree** [comment] 2018-06-28 22:50
@pulberg I don't see the OID `member:1.2.840.113556.1.4.1941` in your filter before the user's DN, maybe you didn't paste it here, but can you confirm you ran the command with that

**Comment by pulberg** [comment] 2018-06-28 22:58
@mrajashree Maybe the syntax is wrong, but this output doesn't look like it has anything useful - 

`time ldapsearch -H ldap://abc.123.com -x -D "svcacct" -W -b "dc=123,dc=com" "(member:1.2.840.113556.1.4.1941:=Phillip Ulberg)"`

```Enter LDAP Password: 
# extended LDIF
#
# LDAPv3
# base <dc=123,dc=com> with scope subtree
# filter: (member:1.2.840.113556.1.4.1941:=Phillip Ulberg)
# requesting: ALL
#

# search reference
ref: ldap://DomainDnsZones.123.com/DC=DomainDnsZones,DC=123,DC=com

# search result
search: 2
result: 0 Success

# numResponses: 2
# numReferences: 1

real    0m1.237s
user    0m0.007s
sys     0m0.003s
```

**Comment by mrajashree** [comment] 2018-06-28 23:23
@pulberg  `(member:1.2.840.113556.1.4.1941:=Phillip Ulberg)` doesn't seem like you're passing the Distinguished Name, I was expecting something of the form `(member:1.2.840.113556.1.4.1941:=cn=Phillip Ulberg,cn=users,dc=123,dc=com)`

**Comment by pulberg** [comment] 2018-06-29 02:48
@mrajashree The syntax is still not working, i'm no ldapsearch expert so I have no idea what the correct form is - 

`time ldapsearch -H ldap://abc.123.com -x -D "svcacct" -W -b "(member:1.2.840.113556.1.4.1941:=cn=Phillip Ulberg,dc=123,dc=com)"`

```
# search result
search: 2
result: 34 Invalid DN syntax
text: 0000208F: NameErr: DSID-03100225, problem 2006 (BAD_NAME), data 8349, bes
 t match of:
        '(member:1.2.840.113556.1.4.1941:=cn=Phillip Ulberg,dc=123,dc=com
 )'
```

**Comment by alexandrem** [comment] 2018-06-29 02:57
@pulberg 

You must add the search base string (like configured in the authentication settings) before the search query in that ldapsearch command (`-b "OU=xxx,DC=xx,DC=yy" "member:1.2.840.xxxx"`).

Also, if you set the debug flag (`--debug`) to the rancher server then you can see all ldap query parameters in the logs.

Look for `AD: Query for pulling user's groups` message to extract the full member search query with your user DN.

**Comment by alexandrem** [comment] 2018-06-29 14:01
Personally I solved the issue by changing the ldap whole subtree search with single level:

```
diff --git a/pkg/auth/providers/activedirectory/activedirectory_client.go b/pkg/auth/providers/activedirectory/activedirectory_client.go
index 3a32d978..79608b3a 100644
--- a/pkg/auth/providers/activedirectory/activedirectory_client.go
+++ b/pkg/auth/providers/activedirectory/activedirectory_client.go
@@ -54,7 +54,7 @@ func (p *adProvider) loginUser(adCredential *v3public.BasicLogin, config *v3.Act
        query := "(" + config.UserLoginAttribute + "=" + ldapv2.EscapeFilter(samName) + ")"
        logrus.Debugf("LDAP Search query: {%s}", query)
        search := ldapv2.NewSearchRequest(config.UserSearchBase,
-               ldapv2.ScopeWholeSubtree, ldapv2.NeverDerefAliases, 0, 0, false,
+               ldapv2.ScopeSingleLevel, ldapv2.NeverDerefAliases, 0, 0, false,
                query,
                ldap.GetUserSearchAttributes(MemberOfAttribute, ObjectClassAttribute, config), nil)
```

Here are the principals count (/v3/principals) for my user for each version:

v2.0.2 = 85
v2.0.4 `ScopeWholeSubtree` = 299 (truncated by server)
v2.0.4 `ScopeSingleLevel` = 85

**Comment by alexandrem** [comment] 2018-06-29 14:39
If anyone wants to validate for their on-prem, you can try this image:

`alexandrem/rancher:v2.0.4-ad`

**Comment by mrajashree** [comment] 2018-07-02 18:13
@alexandrem I think the initial query for the sAMAccountName needs to have the subtree scope, because it's possible that the user search base you gave is >1 levels above the user who is trying to login.
Can you also please run the ldapsearch command again with this additional filter for objectClass and share the time it takes? The filter in the seach command will look something like this:
`(&(objectClass=group)(member:1.2.840.113556.1.4.1941:=CN=user,CN=Users,DC=123,DC=com))`

Thanks

**Comment by alexandrem** [comment] 2018-07-03 13:55
I just tested v2.0.5-rc2 and it seems to be resolved.

I'm not quite sure how, because it seems to be the same nested groups query with whole subtree.

I have 85 principals count in the /v3/principals like I did for v2.0.2

**Comment by alexandrem** [comment] 2018-07-03 14:09
That was for my dev environment, but production experienced the same timeout issue.

However, I found out some settings that make a huge difference.

Changing:

User 
**Search Field**: `sAMAccountName|sn|givenName`

to

**Search Field**: `sAMAccountName`

makes the login fast again.

Tested on v2.0.5-rc2

**Comment by deniseschannon** [comment] 2018-07-03 18:24
In v2.0.4, we default to using Microsoft's search for what groups a user belongs to and have it include any nested groups so that nested group support would work. This may be attributing to the slower login. In v2.0.5, we are going to introduce a setting that allows you to disable the search for nested groups if you have issues logging in. This can be disabled by logging in as the local user to edit the authentication configuration. 

We will be introducing this setting for AD as well as openLDAP as neither have defaulted search functionality for nested groups.

**Comment by sangeethah** [comment] 2018-07-04 00:42
@adingilloRancher as part of validating this issue , following needs to be validated:

Fresh Install

1. Validate AD provisioning with nested group membership option disabled. In this case nested group feature should not work when nested groups get  added to access list , project  and cluster members. 
2. Validate AD provisioning with nested group membership option enabled. Nested group feature should work when nested groups get  added to access list , project  and cluster members.

Upgrade

2.0.2 - AD setup  ( I will test this workflow)
Have scenarios to test nested Group in site access list  and at cluster and member level. 
Only members in the nested Group will be given access (not from groups under the nested group)
Upgrade to 2.0.5-rc3  (In UI make sure that the nested Group membership flag is enabled )
Existing  nested Group assignments should work at  access list  and at cluster and member level.
Add  nested Group in site access list  and at cluster and member level. 
All members (from all groups under this group) of the  nested Group should be given access.

2.0.4 - AD setup 
Have scenarios to test nested Group in site access list  and at cluster and member level. 
All members (from all groups under this group) of the  nested Group should be given access.

Upgrade to 2.0.5-rc3 (In UI make sure that the nested Group  membership flag is enabled )
Existing  nested Group assignments should work at  access list  and at cluster and member level.
Add  nested Group in site access list  and at cluster and member level. 
All members (from all groups under this group) of the  nested Group should be given access.

**Comment by sangeethah** [comment] 2018-07-05 18:48
Tested the following upgrade path from 2.0.2 -> 2.0.4 with AD auth enabled. After upgrading to 2.0.4,
"Search direct and nested group memberships" is enabled enabled by default as expected.

2.0.2 - AD setup
Have scenarios to test nested Group in site access list and at cluster and member level.
Only members in the nested Group will be given access (not from groups under the nested group)
Upgrade to 2.0.5-rc3 (In UI make sure that the nested Group membership flag is enabled )
Existing nested Group assignments (members from all groups under this group) works at access list and at cluster and member level.
Add nested Group in site access list and at cluster and member level.
All members (from all groups under this group) of the nested Group are given access as expected.

**Comment by adingilloRancher** [comment] 2018-07-05 21:17
Performed 2.0.4 -> 2.0.5-rc3 workflow.  "Search direct and nested group memberships" is enabled by default. Validated expected behavior.

2.0.4 - AD setup
Have scenarios to test nested Group in site access list and at cluster and member level.
All members (from all groups under this group) of the nested Group should be given access.

Upgrade to 2.0.5-rc3 (In UI make sure that the nested Group membership flag is enabled )
Existing nested Group assignments should work at access list and at cluster and member level.
Add nested Group in site access list and at cluster and member level.
All members (from all groups under this group) of the nested Group should be given access.

On Fresh Install, validated expected behavior when "Search direct and nested group memberships" is enabled. Also validated nested groups CANNOT login when disabled. ONLY users of the parent group can login.

**Closed by adingilloRancher** 2018-07-05 21:17 UTC
Labels: area/authentication, kind/bug, status/resolved, status/to-test, version/2.0

**Comment by deniseschannon** [comment] 2018-07-11 16:43
Due to upgrade issues from earlier versions that were not using nested groups, we will be turning the nested group search off by default as of v2.0.6 (https://github.com/rancher/rancher/issues/14482) for AD and openLDAP.
