### ISSUE TITLE
kubectl not working with certificate-authority-data or certificate-authority

### ISSUE THREAD

**Issue by alexgaganashvili** [rancher/rancher#12995] opened 2018-04-23 21:08 UTC
It appears that kubectl is not working when you specify the ca cert – either through **certificate-authority-data** or **certificate-authority**. I'm getting:
`Unable to connect to the server: x509: certificate signed by unknown authority`

Thanks

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v2.0.0-beta3` UI: `v2.0.35` |
|Access|`` |
|Route|`global-admin.clusters.index`|

**Comment by superseb** [comment] 2018-04-23 21:47
Duplicate of https://github.com/rancher/rancher/issues/12995

**Closed by superseb** 2018-04-23 21:47 UTC

**Comment by advancingu** [comment] 2018-05-17 19:48
@superseb How can this be a duplicate of itself? I'm trying to get kubectl to talk to a ServiceAccount in the cluster and am getting the same response, so would appreciate seeing the original ticket.

**Comment by superseb** [comment] 2018-05-17 19:51
I probably meant https://github.com/rancher/rancher/issues/11388. In case of well known CA, it needs to be cleared in v2.0.0. If self signed, the cacert needs to be mounted in the container to populate `/v3/settings/cacerts` properly in the API.
