### ISSUE TITLE
There is no way to choose Balancer Algorithm when adding Balancer service.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#1478] opened 2015-07-09 23:29 UTC
Server version - V0.27.0-rc1

There is no way to choose Balancer Algorithm when adding Balancer service.
Algorithm is set to "Roundrobin" .

<img width="1090" alt="screen shot 2015-07-09 at 4 27 47 pm" src="https://cloud.githubusercontent.com/assets/4266958/8609251/b1b21504-2657-11e5-938c-73e05ed957ee.png">

**Comment by vincent99** [comment] 2015-07-10 04:51
Not in the API.

**Comment by alena1108** [comment] 2015-08-21 23:11
Duplicate of https://github.com/rancher/rancher/issues/876, will keep track of the issue there.

**Closed by alena1108** 2015-08-21 23:11 UTC
Labels: area/balancer, area/service, kind/bug
