### ISSUE TITLE
feature request to add/tag clustername/id to rancher server logs

### ISSUE THREAD

**Issue by jambajaar** [rancher/rancher#21637] opened 2019-07-19 02:08 UTC
Rancher version:
v2.2.3

Type:
Enhancement

Description:
Currently in a HA configuration with 3 application servers (min), rancher server pod on any one of the node can handle the client request and the logs are written as expected based on how the pod handles the request.

in troubleshooting scenarios, it would be good if each of the logs are 'tagged' with the cluster name or cluster-id to better distinguish the logs, if multiple requests are being handled for the same type, the logs type and data for the same type of log will be the same across various clusters and extremely hard to distinguish which cluster a particular log belongs to.

for this example snippet, its very hard which particular node/pod these messages are related to?

2019/07/18 20:29:53 [INFO] stdout: Waiting for machine to be running, this may take a few minutes... 
2019/07/18 20:29:53 [INFO] Waiting for machine to be running, this may take a few minutes...

prefixing the clustername/cluster ID will add value to the logs.

gz#5187

SURE-1033

**Comment by jameson-mcghee** [comment] 2022-12-05 21:38
During validation of this ticket on `v2.7-head` (Commit ID: 914f0f4), I was able to verify that when checking the logs for the "leader" node on an HA Rancher server, all downstream RKE1 cluster logs that are captured in the "leader" node for the `local` cluster will be prefaced by the `Mgmt Cluster` name for the downstream cluster as well as the node name for the downstream cluster's specific node (when applicable). I was also able to verify that modifying the `loglevel` to `DEBUG` or `TRACE` also works as intended. Therefore I am closing this ticket.

![image](https://user-images.githubusercontent.com/13294321/205747124-d3d66aba-87f1-48d7-b2ec-02bc111e3013.png)

**Closed by jameson-mcghee** 2022-12-05 21:38 UTC
Labels: kind/enhancement, internal, [zube]: QA Working, QA/S, kind/good-first-issue, team/area2, JIRA, good-first-issue, good first issue
