### ISSUE TITLE
Ensure RBAC for logs, exec, and kubectl shell works properly

### ISSUE THREAD

**Issue by cjellick** [rancher/rancher#12746] opened 2018-04-16 18:13 UTC
Specifically, make sure it works correctly for  member vs read-only user.

**Comment by sangeethah** [comment] 2018-04-19 01:14
Tested with latest build from master:

As project member , user is able to get logs for container and  exec into containers that belong to the namespaces in this project. But not able to launch kubectl shell.

As project owner , user is able to get logs for container and  exec into containers that belong to the namespaces in this project. But not able to launch kubectl shell.

As read only user , user is able to get logs for container but not able to exec into containers that belong to the namespaces in this project. No able to exec into the container is the expected behavior in this case , since he is a read only user.  But not able to launch kubectl shell.

Not being able to  launch kubectl shell in all the above 3 use cases is an issue that needs to be fixed.


As cluster owner , user is able to get logs for container and  exec into containers that belong to the namespaces in all the projects in the cluster. Able to launch kubectl shell.

As cluster member , user is able to get logs for container and  exec into containers that belong to the namespaces in this project. Not able to launch kubectl shell.

Not being able to  launch kubectl shell as cluster member is an issue that needs to be fixed.

**Comment by deniseschannon** [comment] 2018-04-19 21:10
Took the following comments about kubectl shell and put them in #12569. Closing this one as that info has been transferred.

**Closed by deniseschannon** 2018-04-19 21:10 UTC
Labels: area/rbac, priority/0, version/2.0
