### ISSUE TITLE
Possible Rancher v2.7.3 memory leak?

### ISSUE THREAD

**Issue by Eldritch2004** [rancher/rancher#41713] opened 2023-06-01 12:12 UTC
**Setup**
- Rancher version: v2.7,3

**Describe the bug**
Started Rancher on a local Kubernetes Cluster, installed with helm.
With time the Rancher pods will allocate more and more memory until reaching the node limit and crashing

**To Reproduce**
start Rancher, create new Clusters in vSphere, wait

![image](https://github.com/rancher/dashboard/assets/29575745/ff3b7646-57f3-4151-a6a5-00584924858b)

**Additional context**
[rancher-diagnostic-data-1.6.2023-14_06_28.json.zip](https://github.com/rancher/dashboard/files/11624985/rancher-diagnostic-data-1.6.2023-14_06_28.json.zip)

**Comment by pwurbs** [comment] 2023-06-01 13:48
I faced the same. My solution was, to deploy the Rancher chart using resource values for mem request and limit.

**Comment by Eldritch2004** [comment] 2023-06-01 13:52
> I faced the same. My solution was, to deploy the Rancher chart using resource values for mem request and limit. By this I could avoid OOM of node level. There is now only a Rancher pod restart, which is not critical in the HA solution.

Yeah, gave limits to the deployments, too. Doesn't solve the problem but will prevent the nodes from crashing

**Comment by Eldritch2004** [comment] 2023-06-12 08:50
> Could be #41379 / #41225
> 
> ```
> Workaround:
> - set the CATTLE_REQUEST_CACHE_DISABLED = true environment variable on the local cluster, rancher deployment
> - set the CATTLE_REQUEST_CACHE_DISABLED = true environment variable on all downstream clusters, cattle-cluster-agent deployments
> ```

Seems to be a different issue. Setting those didn't mitigate the problem

**Comment by frit0-rb** [comment] 2023-06-20 06:38
Any workround about this issue?

We have the same problem, we putted limits but still having the issue

![image](https://github.com/rancher/rancher/assets/56691791/161bba85-538d-4c71-a6fa-6cc060bdd7e7)

**Comment by pwurbs** [comment] 2023-06-20 06:56
I think, the limit is a good workaround. As long as you operate Rancher in HA mode with more than 1 replica, then the restart of one Rancher pod doesn't impose any impact, but prevents the node from running OOM.

**Comment by lerminou** [comment] 2023-06-21 11:49
I just updated and discovered the same problem in Rancher 2.7.4, I was in 2.6 before without any problems.
sorry @frit0-rb

**Comment by moio** [comment] 2023-06-22 07:21
Seems a duplicate of #41225 to me. Please try the test image in https://github.com/rancher/rancher/issues/41225#issuecomment-1581159631 or wait for 2.7.5 and report back if the problem is fixed or not.

Thanks!

**Comment by moio** [comment] 2023-06-22 07:23
To me this looks like a potential duplicate of https://github.com/rancher/rancher/issues/41809. We do not have a fix yet, but keep an eye on it as we will post updates.

**Closed** 2024-04-09 06:51 UTC
Labels: kind/bug
