### ISSUE TITLE
kubelet error connection

### ISSUE THREAD

**Issue by spyworldxp** [rancher/rancher#8696] opened 2017-05-08 03:51 UTC
Rancher Versions: Since version v1.5.5 - v1.6.0 (current)
Operating System: Rancher v1.0.1
Virtualization: VMware ESXi 6.5 (vCenter 6.5)
kubernetes: v1.5.4-rancher1-4
Docker Version: 17.05.0-ce
Environment Type:Kubernetes

When deploy kubernetes.

```
5/8/2017 11:42:15 AM+ FQDN=docker01
5/8/2017 11:42:15 AM+ exec kubelet --kubeconfig=/etc/kubernetes/ssl/kubeconfig --api_servers=https://kubernetes.kubernetes.rancher.internal:6443 --allow-privileged=true --register-node=true --cloud-provider=rancher --healthz-bind-address=0.0.0.0 --cluster-dns=10.43.0.10 --cluster-domain=cluster.local --network-plugin=cni --network-plugin-dir=/etc/cni/managed.d --pod-infra-container-image=gcr.io/google_containers/pause-amd64:3.0 --hostname-override docker01
5/8/2017 11:42:15 AMFlag --api-servers has been deprecated, Use --kubeconfig instead. Will be removed in a future version.
5/8/2017 11:42:15 AMI0508 03:42:15.312807   21908 feature_gate.go:189] feature gates: map[]
5/8/2017 11:42:15 AMI0508 03:42:15.391591   21908 docker.go:356] Connecting to docker on unix:///var/run/docker.sock
5/8/2017 11:42:15 AMI0508 03:42:15.391637   21908 docker.go:376] Start docker client with request timeout=2m0s
5/8/2017 11:42:15 AME0508 03:42:15.391944   21908 kube_docker_client.go:98] failed to retrieve docker version: Cannot connect to the Docker daemon. Is the docker daemon running on this host?
5/8/2017 11:42:15 AMW0508 03:42:15.392013   21908 kube_docker_client.go:99] Using empty version for docker client, this may sometimes cause compatibility issue.
5/8/2017 11:42:15 AMI0508 03:42:15.395753   21908 manager.go:143] cAdvisor running in container: "/docker/ac0cf848efca073ea01efc8de9577934b12b15219ab70b08a74f701749a85d56"
5/8/2017 11:42:15 AMW0508 03:42:15.396060   21908 manager.go:147] Unable to connect to Docker: Cannot connect to the Docker daemon. Is the docker daemon running on this host?
5/8/2017 11:42:15 AMW0508 03:42:15.396466   21908 manager.go:151] unable to connect to Rkt api service: rkt: cannot tcp Dial rkt api service: dial tcp 127.0.0.1:15441: getsockopt: connection refused
5/8/2017 11:42:15 AMI0508 03:42:15.398414   21908 fs.go:117] Filesystem partitions: map[/dev/sda1:{mountpoint:/var/lib/docker/aufs major:8 minor:1 fsType:ext4 blockSize:0}]
5/8/2017 11:42:15 AMI0508 03:42:15.399828   21908 manager.go:198] Machine: {NumCores:2 CpuFrequency:2399998 MemoryCapacity:4142526464 MachineID:6a7b652f3677464382b49ac8dc35ba0f SystemUUID:4217C4E7-F781-3444-472A-39BF3DC6C1F3 BootID:3508b22d-1d8b-4aea-9557-08c7d4ccb5f6 Filesystems:[{Device:/dev/sda1 Capacity:49682366464 Type:vfs Inodes:6279168 HasInodes:true} {Device:none Capacity:49682366464 Type:vfs Inodes:6279168 HasInodes:true}] DiskMap:map[251:0:{Name:zram0 Major:251 Minor:0 Size:977362944 Scheduler:none} 8:0:{Name:sda Major:8 Minor:0 Size:52428800000 Scheduler:deadline}] NetworkDevices:[{Name:dummy0 MacAddress:ca:2b:b1:4c:f9:0d Speed:0 Mtu:1500} {Name:eth0 MacAddress:00:50:56:97:62:13 Speed:10000 Mtu:1500}] Topology:[{Id:0 Memory:0 Cores:[{Id:0 Threads:[0] Caches:[{Size:32768 Type:Data Level:1} {Size:32768 Type:Instruction Level:1} {Size:262144 Type:Unified Level:2}]}] Caches:[{Size:20971520 Type:Unified Level:3}]} {Id:2 Memory:0 Cores:[{Id:0 Threads:[1] Caches:[{Size:32768 Type:Data Level:1} {Size:32768 Type:Instruction Level:1} {Size:262144 Type:Unified Level:2}]}] Caches:[{Size:20971520 Type:Unified Level:3}]}] CloudProvider:Unknown InstanceType:Unknown InstanceID:None}
5/8/2017 11:42:15 AMI0508 03:42:15.400290   21908 manager.go:204] Version: {KernelVersion:4.4.66-boot2docker ContainerOsVersion:Debian GNU/Linux 8 (jessie) DockerVersion:Unknown CadvisorVersion: CadvisorRevision:}
5/8/2017 11:42:15 AMW0508 03:42:15.402234   21908 container_manager_linux.go:205] Running with swap on is not supported, please disable swap! This will be a fatal error by default starting in K8s v1.6! In the meantime, you can opt-in to making this a fatal error by enabling --experimental-fail-swap-on.
5/8/2017 11:42:15 AMI0508 03:42:15.402445   21908 kubelet.go:252] Watching apiserver
5/8/2017 11:42:15 AMW0508 03:42:15.404918   21908 kubelet_network.go:69] Hairpin mode set to "promiscuous-bridge" but kubenet is not enabled, falling back to "hairpin-veth"
5/8/2017 11:42:15 AMI0508 03:42:15.404958   21908 kubelet.go:477] Hairpin mode set to "hairpin-veth"
5/8/2017 11:42:15 AME0508 03:42:15.405570   21908 docker_manager.go:252] Failed to execute Info() call to the Docker client: Cannot connect to the Docker daemon. Is the docker daemon running on this host?
5/8/2017 11:42:15 AMW0508 03:42:15.405584   21908 docker_manager.go:253] Using fallback default of /var/lib/docker for location of Docker runtime
5/8/2017 11:42:15 AMerror: failed to run Kubelet: failed to create kubelet: failed to get runtime version: docker: failed to get docker version: Cannot connect to the Docker daemon. Is the docker daemon running on this host?
```

**Comment by pulberg** [comment] 2017-05-08 16:07
Kubernetes 1.5.4 not supported on Docker 17.05-ce, from the Rancher v1.6.0 release notes - 

Supported Docker Versions

Docker 1.10.3
Docker 1.12.3-1.12.6
Docker 1.13.1 (Not with Kubernetes)
Docker 17.03.0-ce (Not with Kubernetes)
Docker 17.03.0-ee (Not with Kubernetes)

**Comment by joshwget** [comment] 2017-05-08 17:01
Can you try this again with a supported version of Docker and see if this resolves your issue?

**Comment by spyworldxp** [comment] 2017-05-09 05:12
I receive an error message from Docker 1.12.3-1.12.6
```

5/9/2017 12:41:33 PM+ exec kubelet --kubeconfig=/etc/kubernetes/ssl/kubeconfig --api_servers=https://kubernetes.kubernetes.rancher.internal:6443 --allow-privileged=true --register-node=true --cloud-provider=rancher --healthz-bind-address=0.0.0.0 --cluster-dns=10.43.0.10 --cluster-domain=cluster.local --network-plugin=cni --network-plugin-dir=/etc/cni/managed.d --pod-infra-container-image=gcr.io/google_containers/pause-amd64:3.0 --hostname-override docker-bry03
5/9/2017 12:41:33 PMFlag --api-servers has been deprecated, Use --kubeconfig instead. Will be removed in a future version.
5/9/2017 12:41:33 PMI0509 04:41:33.296414   13700 feature_gate.go:189] feature gates: map[]
5/9/2017 12:41:33 PMI0509 04:41:33.431071   13700 docker.go:356] Connecting to docker on unix:///var/run/docker.sock
5/9/2017 12:41:33 PMI0509 04:41:33.431094   13700 docker.go:376] Start docker client with request timeout=2m0s
5/9/2017 12:41:33 PMI0509 04:41:33.434715   13700 manager.go:143] cAdvisor running in container: "/docker/353b19ad8a10f618cb0b63c3f548575196c97eea77095621f295d34798319e6b"
5/9/2017 12:41:33 PMW0509 04:41:33.441801   13700 manager.go:151] unable to connect to Rkt api service: rkt: cannot tcp Dial rkt api service: dial tcp 127.0.0.1:15441: getsockopt: connection refused
5/9/2017 12:41:33 PMI0509 04:41:33.449216   13700 fs.go:117] Filesystem partitions: map[/dev/sda1:{mountpoint:/etc/resolv.conf major:8 minor:1 fsType:ext4 blockSize:0} none:{mountpoint:/ major:0 minor:73 fsType:aufs blockSize:0}]
5/9/2017 12:41:33 PMI0509 04:41:33.450887   13700 manager.go:198] Machine: {NumCores:2 CpuFrequency:2399998 MemoryCapacity:2099372032 MachineID:6a7b652f3677464382b49ac8dc35ba0f SystemUUID:4217F5F2-0C8D-C1FD-61E0-C142A06A70B2 BootID:6e763170-14e3-49dc-82c3-76b98f6a055b Filesystems:[{Device:/dev/sda1 Capacity:49682366464 Type:vfs Inodes:6279168 HasInodes:true} {Device:none Capacity:49682366464 Type:vfs Inodes:6279168 HasInodes:true}] DiskMap:map[8:0:{Name:sda Major:8 Minor:0 Size:52428800000 Scheduler:deadline} 251:0:{Name:zram0 Major:251 Minor:0 Size:465281024 Scheduler:none}] NetworkDevices:[{Name:dummy0 MacAddress:82:0e:e9:af:3b:18 Speed:0 Mtu:1500} {Name:eth0 MacAddress:00:50:56:97:0f:8e Speed:10000 Mtu:1500}] Topology:[{Id:0 Memory:0 Cores:[{Id:0 Threads:[0] Caches:[{Size:32768 Type:Data Level:1} {Size:32768 Type:Instruction Level:1} {Size:262144 Type:Unified Level:2}]}] Caches:[{Size:20971520 Type:Unified Level:3}]} {Id:2 Memory:0 Cores:[{Id:0 Threads:[1] Caches:[{Size:32768 Type:Data Level:1} {Size:32768 Type:Instruction Level:1} {Size:262144 Type:Unified Level:2}]}] Caches:[{Size:20971520 Type:Unified Level:3}]}] CloudProvider:Unknown InstanceType:Unknown InstanceID:None}
5/9/2017 12:41:33 PMI0509 04:41:33.451381   13700 manager.go:204] Version: {KernelVersion:4.4.41-boot2docker ContainerOsVersion:Debian GNU/Linux 8 (jessie) DockerVersion:1.12.6 CadvisorVersion: CadvisorRevision:}
5/9/2017 12:41:33 PMW0509 04:41:33.453191   13700 container_manager_linux.go:205] Running with swap on is not supported, please disable swap! This will be a fatal error by default starting in K8s v1.6! In the meantime, you can opt-in to making this a fatal error by enabling --experimental-fail-swap-on.
5/9/2017 12:41:33 PMI0509 04:41:33.453435   13700 kubelet.go:252] Watching apiserver
5/9/2017 12:41:33 PMW0509 04:41:33.455259   13700 kubelet_network.go:69] Hairpin mode set to "promiscuous-bridge" but kubenet is not enabled, falling back to "hairpin-veth"
5/9/2017 12:41:33 PMI0509 04:41:33.455287   13700 kubelet.go:477] Hairpin mode set to "hairpin-veth"
5/9/2017 12:41:33 PMI0509 04:41:33.476264   13700 docker_manager.go:256] Setting dockerRoot to /mnt/sda1/var/lib/docker
5/9/2017 12:41:33 PMI0509 04:41:33.476278   13700 docker_manager.go:259] Setting cgroupDriver to cgroupfs
5/9/2017 12:41:33 PMI0509 04:41:33.488197   13700 server.go:770] Started kubelet v1.5.4-rancher1
5/9/2017 12:41:33 PME0509 04:41:33.492521   13700 kubelet.go:1145] Image garbage collection failed: unable to find data for container /
5/9/2017 12:41:33 PMI0509 04:41:33.492728   13700 kubelet_node_status.go:204] Setting node annotation to enable volume controller attach/detach
5/9/2017 12:41:33 PMI0509 04:41:33.492742   13700 rancher.go:641] ExternalID [docker-bry03]
5/9/2017 12:41:33 PMI0509 04:41:33.492747   13700 rancher.go:648] InstanceID [docker-bry03]
5/9/2017 12:41:33 PMI0509 04:41:33.492919   13700 server.go:123] Starting to listen on 0.0.0.0:10250
5/9/2017 12:41:33 PMI0509 04:41:33.518963   13700 rancher.go:648] InstanceID [docker-bry03]
5/9/2017 12:41:33 PMI0509 04:41:33.551909   13700 rancher.go:648] InstanceID [docker-bry03]
5/9/2017 12:41:33 PMI0509 04:41:33.577111   13700 kubelet_node_status.go:246] Adding node label from cloud provider: beta.kubernetes.io/instance-type=rancher
5/9/2017 12:41:33 PMI0509 04:41:33.577173   13700 kubelet_node_status.go:257] Adding node label from cloud provider: failure-domain.beta.kubernetes.io/zone=FailureDomain1
5/9/2017 12:41:33 PMI0509 04:41:33.577194   13700 kubelet_node_status.go:261] Adding node label from cloud provider: failure-domain.beta.kubernetes.io/region=Region1
5/9/2017 12:41:33 PME0509 04:41:33.604742   13700 kubelet.go:1634] Failed to check if disk space is available for the runtime: failed to get fs info for "runtime": unable to find data for container /
5/9/2017 12:41:33 PME0509 04:41:33.604800   13700 kubelet.go:1642] Failed to check if disk space is available on the root partition: failed to get fs info for "root": error trying to get filesystem Device for dir /var/lib/kubelet: err: could not find device with major: 0, minor: 15 in cached partitions map
5/9/2017 12:41:33 PMI0509 04:41:33.607284   13700 fs_resource_analyzer.go:66] Starting FS ResourceAnalyzer
5/9/2017 12:41:33 PMI0509 04:41:33.607311   13700 status_manager.go:129] Starting to sync pod status with apiserver
5/9/2017 12:41:33 PMI0509 04:41:33.607430   13700 kubelet.go:1714] Starting kubelet main sync loop.
5/9/2017 12:41:33 PMI0509 04:41:33.607440   13700 kubelet.go:1725] skipping pod synchronization - [container runtime is down]
5/9/2017 12:41:33 PMI0509 04:41:33.607352   13700 volume_manager.go:242] Starting Kubelet Volume Manager
5/9/2017 12:41:33 PMI0509 04:41:33.616552   13700 factory.go:295] Registering Docker factory
Unknown Date
5/9/2017 12:41:33 PMW0509 04:41:33.616571   13700 manager.go:247] Registration of the rkt container factory failed: unable to communicate with Rkt api service: rkt: cannot tcp Dial rkt api service: dial tcp 127.0.0.1:15441: getsockopt: connection refused
5/9/2017 12:41:33 PMI0509 04:41:33.616575   13700 factory.go:54] Registering systemd factory
5/9/2017 12:41:33 PMI0509 04:41:33.617084   13700 factory.go:86] Registering Raw factory
5/9/2017 12:41:33 PMI0509 04:41:33.617536   13700 manager.go:1106] Started watching for new ooms in manager
5/9/2017 12:41:33 PMI0509 04:41:33.620688   13700 oomparser.go:185] oomparser using systemd
5/9/2017 12:41:33 PMI0509 04:41:33.621160   13700 manager.go:288] Starting recovery of all containers
5/9/2017 12:41:33 PMI0509 04:41:33.621189   13700 manager.go:293] Recovery completed
5/9/2017 12:41:33 PMF0509 04:41:33.621256   13700 kubelet.go:1210] Failed to start cAdvisor inotify_add_watch /var/lib/docker/aufs/mnt/915469cf049a4503711b06f9713f3cd5293be1e81515779da176ad2243cb49be/sys/fs/cgroup/cpu: no such file or directory
```

**Comment by cjellick** [comment] 2017-09-19 00:46
Same as https://github.com/rancher/rancher/issues/8495?

**Comment by superseb** [comment] 2018-01-27 13:51
Closing as duplicate of https://github.com/rancher/rancher/issues/8495

**Closed by superseb** 2018-01-27 13:51 UTC
Labels: area/kubernetes, kind/question
