### ISSUE TITLE
Expected state running but got error: Timeout getting IP address

### ISSUE THREAD

**Issue by jmreicha** [rancher/rancher#9367] opened 2017-07-17 21:29 UTC
**Rancher versions:**
rancher/server: `v1.5.6`
rancher/agent: `v1.2.2`

**Infrastructure Stack versions:**
healthcheck: `v0.2.3`
ipsec: `net:holder`
network-services: `Network manager service is v0.7.4 and metadata service is v0.9.2
scheduler: `v0.7.5`

**Docker version: (`docker version`,`docker info` preferred)** `1.12.6`

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)** `CoreOS 1298.x`, Kernel: `4.9.9/4.9.16`

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)** `AWS`

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)** `HA Rancher, external DB.`

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)** `Cattle`

**Steps to Reproduce:**

Spin up a new host and bootsrap with shell script to use a VPC internal IP.

**Results:**

Seeing `Expected state running but got error: Timeout getting IP address` errors on the rancher server (master) for the new host that gets spun up.  There is more info and logs - will be dumping that in an update.

**Comment by leodotcloud** [comment] 2017-07-17 21:41
This error can happen if the infrastructure stack version is not compatible with the current version of `rancher/server`. One of the ways to confirm that would be to navigate to Stacks > Infrastructure and check for the message next to "network-services". (`Template version not found`)

### Example:
![image](https://user-images.githubusercontent.com/19392926/28291039-a63d296a-6afd-11e7-8d0a-95fdc06e8d58.png)



## Steps to fix this:
```
Step 1: 
    - Navigate to here: http(s)://<rancher_server:port>/v1-catalog/templates

Step 2:
    - Search for network-services and take note of defaultTemplateVersionId.
      Example: defaultTemplateVersionId": "library:infra*network-services:20"

Step 3:
    - Navigate to http(s)://<rancher_server:port>/
    - Open the affected Environment.
    - Click on Stacks > Infrastructure
    - Click on the menu of the network services stack and click 'View in API'
    - You should see 'externalId' not matching 'defaultTemplateVersionId' we figured in previous step.

Step 4:
    - Edit the stack via API browser and set to the correct folder version, click 'Show Request' followed by 'Send Request'
```

**Comment by jmreicha** [comment] 2017-07-17 21:56
Still doesn't seem to be fixed yet after following the instructions above.  The template error is gone but still having trouble activating the healthcheck and ipsec containers on the new host.  Here are the logs from the `rancher-agent` on the host in question.

```
7/17/2017 4:51:51 PMtime="2017-07-17T21:51:51Z" level=info msg="Received event: Name: storage.volume.activate, Event Id: 13c3e76e-1969-41f7-9691-66509209378d, Resource Id: 1vspm8733"
7/17/2017 4:51:51 PMtime="2017-07-17T21:51:51Z" level=info msg="Reply: 13c3e76e-1969-41f7-9691-66509209378d, storage.volume.activate, 1vspm8733:volumeStoragePoolMap"
7/17/2017 4:51:51 PMtime="2017-07-17T21:51:51Z" level=info msg="Received event: Name: compute.instance.activate, Event Id: acf01917-3b73-4118-8427-92d0fb9f0120, Resource Id: 1ihm6887"
7/17/2017 4:51:51 PMtime="2017-07-17T21:51:51Z" level=info msg="rancher id [8298]: Container with docker id [91b37de4eaf3a658bd56ffec51e6256956636a586d55ab5e05e97861ba7b251d] has been started"
7/17/2017 4:52:05 PMtime="2017-07-17T21:52:05Z" level=error msg="Error processing event" err=Timeout getting IP address eventId=3f25a930-a7e9-406f-a20b-95d842c236eb eventName=compute.instance.activate resourceId=1ihm6885
7/17/2017 4:52:05 PMtime="2017-07-17T21:52:05Z" level=info msg="Received event: Name: compute.instance.activate, Event Id: c5de6a7c-590d-4767-a2f0-4ee3e4bfc7d0, Resource Id: 1ihm6885"
7/17/2017 4:52:05 PMtime="2017-07-17T21:52:05Z" level=error msg="Error processing event" err=Timeout getting IP address eventId=c5de6a7c-590d-4767-a2f0-4ee3e4bfc7d0 eventName=compute.instance.activate resourceId=1ihm6885
7/17/2017 4:52:05 PMtime="2017-07-17T21:52:05Z" level=info msg="Received event: Name: compute.instance.activate, Event Id: 7179d3bf-d728-4f0c-b9f7-b0f161ce04c6, Resource Id: 1ihm6885"
7/17/2017 4:52:23 PMtime="2017-07-17T21:52:23Z" level=error msg="Error processing event" err=Timeout getting IP address eventId=acf01917-3b73-4118-8427-92d0fb9f0120 eventName=compute.instance.activate resourceId=1ihm6887
7/17/2017 4:52:23 PMtime="2017-07-17T21:52:23Z" level=info msg="Received event: Name: compute.instance.activate, Event Id: fc5ec700-ecf4-4032-8ee9-42cf1277e585, Resource Id: 1ihm6887"
7/17/2017 4:52:23 PMtime="2017-07-17T21:52:23Z" level=error msg="Error processing event" err=Timeout getting IP address eventId=fc5ec700-ecf4-4032-8ee9-42cf1277e585 eventName=compute.instance.activate resourceId=1ihm6887
7/17/2017 4:52:23 PMtime="2017-07-17T21:52:23Z" level=info msg="Received event: Name: compute.instance.activate, Event Id: 2eaab412-1ccd-4589-bfe8-98efc206041d, Resource Id: 1ihm6887"
7/17/2017 4:52:30 PMtime="2017-07-17T21:52:30Z" level=info msg="Received event: Name: compute.instance.remove, Event Id: 383c392e-1519-4dba-8c0d-8fe7f50ff367, Resource Id: 1ihm6861"
7/17/2017 4:52:30 PMtime="2017-07-17T21:52:30Z" level=info msg="Reply: 383c392e-1519-4dba-8c0d-8fe7f50ff367, compute.instance.remove, 1ihm6861:instanceHostMap"
7/17/2017 4:52:37 PMtime="2017-07-17T21:52:37Z" level=error msg="Error processing event" err=Timeout getting IP address eventId=7179d3bf-d728-4f0c-b9f7-b0f161ce04c6 eventName=compute.instance.activate resourceId=1ihm6885
7/17/2017 4:52:37 PMtime="2017-07-17T21:52:37Z" level=info msg="Received event: Name: compute.instance.activate, Event Id: 177cd331-98ee-4a71-af0c-51e1bcdaa27b, Resource Id: 1ihm6885"
7/17/2017 4:52:37 PMtime="2017-07-17T21:52:37Z" level=error msg="Error processing event" err=Timeout getting IP address eventId=177cd331-98ee-4a71-af0c-51e1bcdaa27b eventName=compute.instance.activate resourceId=1ihm6885
7/17/2017 4:52:37 PMtime="2017-07-17T21:52:37Z" level=info msg="Received event: Name: compute.instance.activate, Event Id: 5da8bb99-e024-4d01-896f-fbdee08f477c, Resource Id: 1ihm6885"
7/17/2017 4:52:55 PMtime="2017-07-17T21:52:55Z" level=error msg="Error processing event" err=Timeout getting IP address eventId=2eaab412-1ccd-4589-bfe8-98efc206041d eventName=compute.instance.activate resourceId=1ihm6887
7/17/2017 4:52:55 PMtime="2017-07-17T21:52:55Z" level=info msg="Received event: Name: compute.instance.activate, Event Id: 6ed637f0-19c0-42f0-8518-288ee67e9cdc, Resource Id: 1ihm6887"
7/17/2017 4:52:55 PMtime="2017-07-17T21:52:55Z" level=error msg="Error processing event" err=Timeout getting IP address eventId=6ed637f0-19c0-42f0-8518-288ee67e9cdc eventName=compute.instance.activate resourceId=1ihm6887
7/17/2017 4:52:55 PMtime="2017-07-17T21:52:55Z" level=info msg="Received event: Name: compute.instance.activate, Event Id: a0c45f86-d8e4-417e-b68b-2eb9eebedf4b, Resource Id: 1ihm6887"
7/17/2017 4:53:09 PMtime="2017-07-17T21:53:09Z" level=error msg="Error processing event" err=Timeout getting IP address eventId=5da8bb99-e024-4d01-896f-fbdee08f477c eventName=compute.instance.activate resourceId=1ihm6885
7/17/2017 4:53:10 PMtime="2017-07-17T21:53:10Z" level=info msg="Received event: Name: compute.instance.deactivate, Event Id: 363e2948-247e-400d-aaff-e4294a65564f, Resource Id: 1ihm6885"
7/17/2017 4:53:10 PMtime="2017-07-17T21:53:10Z" level=info msg="rancher id [8296]: Container with docker id [d2fed3925732681061c0b25622a980457379aca6b0453b385b4ea57cc3ad584b] has been deactivated"
7/17/2017 4:53:10 PMtime="2017-07-17T21:53:10Z" level=info msg="Reply: 363e2948-247e-400d-aaff-e4294a65564f, compute.instance.deactivate, 1ihm6885:instanceHostMap"
7/17/2017 4:53:27 PMtime="2017-07-17T21:53:27Z" level=error msg="Error processing event" err=Timeout getting IP address eventId=a0c45f86-d8e4-417e-b68b-2eb9eebedf4b eventName=compute.instance.activate resourceId=1ihm6887
7/17/2017 4:53:28 PMtime="2017-07-17T21:53:28Z" level=info msg="Received event: Name: compute.instance.deactivate, Event Id: eaed7c19-59ed-423d-8ba9-06c11f7ca7b7, Resource Id: 1ihm6887"
7/17/2017 4:53:28 PMtime="2017-07-17T21:53:28Z" level=info msg="rancher id [8298]: Container with docker id [91b37de4eaf3a658bd56ffec51e6256956636a586d55ab5e05e97861ba7b251d] has been deactivated"
7/17/2017 4:53:28 PMtime="2017-07-17T21:53:28Z" level=info msg="Reply: eaed7c19-59ed-423d-8ba9-06c11f7ca7b7, compute.instance.deactivate, 1ihm6887:instanceHostMap"
7/17/2017 4:53:29 PMtime="2017-07-17T21:53:29Z" level=info msg="Received event: Name: compute.instance.deactivate, Event Id: 8ebca73c-5aeb-47e6-b0c9-9d645a9d43a3, Resource Id: 1ihm6888"
7/17/2017 4:53:29 PMtime="2017-07-17T21:53:29Z" level=info msg="Reply: 8ebca73c-5aeb-47e6-b0c9-9d645a9d43a3, compute.instance.deactivate, 1ihm6888:instanceHostMap"
7/17/2017 4:53:30 PMtime="2017-07-17T21:53:30Z" level=info msg="Received event: Name: compute.instance.remove, Event Id: b27535a7-8fbf-495f-aad0-bf171c4d6b5e, Resource Id: 1ihm6871"
7/17/2017 4:53:30 PMtime="2017-07-17T21:53:30Z" level=info msg="Reply: b27535a7-8fbf-495f-aad0-bf171c4d6b5e, compute.instance.remove, 1ihm6871:instanceHostMap"
7/17/2017 4:54:05 PMtime="2017-07-17T21:54:05Z" level=info msg="Received event: Name: storage.volume.remove, Event Id: ad396c1c-3ac8-4766-b513-65bb2ba0d559, Resource Id: 1vspm8732"
7/17/2017 4:54:05 PMtime="2017-07-17T21:54:05Z" level=info msg="rancher id [1vspm8732]: Volume with name [] has been removed"
7/17/2017 4:54:05 PMtime="2017-07-17T21:54:05Z" level=info msg="Reply: ad396c1c-3ac8-4766-b513-65bb2ba0d559, storage.volume.remove, 1vspm8732:volumeStoragePoolMap"
7/17/2017 4:54:30 PMtime="2017-07-17T21:54:30Z" level=info msg="Received event: Name: compute.instance.remove, Event Id: 1f6506aa-72e5-4e23-9c8b-912ce7c34a26, Resource Id: 1ihm6864"
7/17/2017 4:54:30 PMtime="2017-07-17T21:54:30Z" level=info msg="Reply: 1f6506aa-72e5-4e23-9c8b-912ce7c34a26, compute.instance.remove, 1ihm6864:instanceHostMap"
7/17/2017 4:54:30 PMtime="2017-07-17T21:54:30Z" level=info msg="Received event: Name: compute.instance.remove, Event Id: 045d8e67-4349-4766-84d9-bd778b492def, Resource Id: 1ihm6873"
7/17/2017 4:54:30 PMtime="2017-07-17T21:54:30Z" level=info msg="Reply: 045d8e67-4349-4766-84d9-bd778b492def, compute.instance.remove, 1ihm6873:instanceHostMap"
7/17/2017 4:54:30 PMtime="2017-07-17T21:54:30Z" level=info msg="Received event: Name: compute.instance.deactivate, Event Id: 7a0f1513-d61f-47f7-866c-6bd19114a85c, Resource Id: 1ihm6886"
7/17/2017 4:54:30 PMtime="2017-07-17T21:54:30Z" level=info msg="rancher id [8297]: Container with docker id [75def844789a3042deca2717010e432dfc84914e3c14460a4ec7e192041bf62c] has been deactivated"
7/17/2017 4:54:30 PMtime="2017-07-17T21:54:30Z" level=info msg="Reply: 7a0f1513-d61f-47f7-866c-6bd19114a85c, compute.instance.deactivate, 1ihm6886:instanceHostMap"
7/17/2017 4:54:31 PMtime="2017-07-17T21:54:31Z" level=info msg="Received event: Name: storage.volume.remove, Event Id: 6557c111-f7f2-4ae1-8d62-71b600a6fa92, Resource Id: 1vspm8735"
7/17/2017 4:54:31 PMtime="2017-07-17T21:54:31Z" level=info msg="rancher id [1vspm8735]: Volume with name [] has been removed"
7/17/2017 4:54:31 PMtime="2017-07-17T21:54:31Z" level=info msg="Reply: 6557c111-f7f2-4ae1-8d62-71b600a6fa92, storage.volume.remove, 1vspm8735:volumeStoragePoolMap"
7/17/2017 4:54:31 PMtime="2017-07-17T21:54:31Z" level=info msg="Received event: Name: storage.volume.remove, Event Id: 72c9165b-8e59-4431-8c38-1334432acd9a, Resource Id: 1vspm8733"
7/17/2017 4:54:31 PMtime="2017-07-17T21:54:31Z" level=info msg="rancher id [1vspm8733]: Volume with name [] has been removed"
7/17/2017 4:54:31 PMtime="2017-07-17T21:54:31Z" level=info msg="Reply: 72c9165b-8e59-4431-8c38-1334432acd9a, storage.volume.remove, 1vspm8733:volumeStoragePoolMap"
7/17/2017 4:54:32 PMtime="2017-07-17T21:54:32Z" level=info msg="Received event: Name: storage.volume.remove, Event Id: cbd39012-0e4f-47b5-bb26-14d28e645007, Resource Id: 1vspm8734"
7/17/2017 4:54:32 PMtime="2017-07-17T21:54:32Z" level=info msg="rancher id [1vspm8734]: Volume with name [] has been removed"
7/17/2017 4:54:32 PMtime="2017-07-17T21:54:32Z" level=info msg="Reply: cbd39012-0e4f-47b5-bb26-14d28e645007, storage.volume.remove, 1vspm8734:volumeStoragePoolMap"
```

Not sure if anything there is relevant or not.

**Comment by leodotcloud** [comment] 2017-07-17 22:00
Just added Step 5

**Comment by justinturpin** [comment] 2017-07-18 01:30
I did the 5 steps listed in leodotcloud's comment and they worked for 2 of our environments, but failed on our staging: metadata and DNS services will not start.

<img width="1032" alt="screen shot 2017-07-17 at 6 26 27 pm" src="https://user-images.githubusercontent.com/7243103/28296516-9c5cd330-6b1d-11e7-994f-866d246a4bdf.png">

The environment should be the same, in fact its on the same rancher cluster as the previous. The metadata services are in a "Starting: Waiting for dependencies" or "Starting: scheduling" state. I caught a glimpse of an error before the container disappeared and tried to start again and it said something like "Dependencies readiness error". Any other steps that should be performed? I even tried adding a new host and it actually won't start any new containers except for the agent.

Thanks!

**Comment by ecliptik** [comment] 2017-07-18 17:22
We just started seeing this on our Rancher 1.5.6 production environment as well. Our setup is very similar to @jmreicha, AWS, versions, etc.

Trying to reproduce it in on our dev server and will provide any additional details.

**Comment by ecliptik** [comment] 2017-07-18 17:52
We are seeing this due to losing 5 of 8 hosts with a required label. For some reason 5 hosts just "disappeared" while 3 stayed up. I believe this may be due to a memory leak from a container stack that we've been seeing and we're going to put a limit on it to avoid it

**Comment by dwo** [comment] 2017-07-20 08:40
So we ran into the same thing on our Rancher 1.5 cluster, and those 5 steps fixed it for us too.

`defaultTemplateVersionId` was @ 17 and our network-services stack had `externalId` @ 20. We manually updated the network-services `externalId` down to 17 and "upgraded" the stack to the current version. It actually put the networking container images down a few versions -- and it took a really long time over 50+ workers but was ultimately successful.

@leodotcloud Any idea how a network-services stack can get into this state and how it can be avoided in future? Were some backwards-incompatible changes made to the catalogs / docker image tags or something like that?

It's confusing, as most of the workers were running fine on those higher versions. New workers, as of about a week or two ago, started failing to bring up any containers (infrastructure or otherwise) with the timeout error.

**Comment by rbojan** [comment] 2017-07-20 20:58
@dwo We had the same problems:

> defaultTemplateVersionId was @ 17 and our network-services stack had externalId @ 20. We manually updated the network-services externalId down to 17 and "upgraded" the stack to the current version. It actually put the networking container images down a few versions -- and it took a really long time over 50+ workers but was ultimately successful.

Although we didn't need that long to regenerate as we have 6 workers in the applicable environment ;).

> It's confusing, as most of the workers were running fine on those higher versions. New workers, as of about a week or two ago, started failing to bring up any containers (infrastructure or otherwise) with the timeout error.

Our workers did the same in a shorter timeframe.

@leodotcloud Your fix helped us - thanks a lot! We are curious about the reason for that kind of failure.

**Comment by dwo** [comment] 2017-07-20 21:15
I should have also said: thank you for the fix. 🙇

**Comment by leodotcloud** [comment] 2017-07-20 22:06
302 (Redirecting) "Thanks" to @aemneina @joshwget and @deniseschannon. I just got the instructions from them :-)
@deniseschannon will be providing more details about this issue.

**Comment by jmreicha** [comment] 2017-07-21 01:34
@ecliptik Did you get your issue resolved?  I think I'm good to close this if you did.

**Comment by deniseschannon** [comment] 2017-07-21 03:24
In v1.5.0-v1.6.0, the automatic upgrade manager had some faulty logic of when to upgrade the network-services. We were required to create this automatic upgrade due to major metadata changes that went into v1.5.0. We had corrected the automatic upgrade logic as of v1.6.1. At the same time, in v1.6.1, we had moved from using the `master` branch of the Rancher catalog to a new `v1.6-release` branch in order to be able to keep updating network services stack in Rancher and hopefully prevent any further unintended automatic upgrades in the v1.5.0-v1.6.0 versions. 

Unfortunately, last week, we accidentally merged a PR into `master` for 30 minutes. The automatic upgrade of network services only occurs once an hour so if your thread was triggered in that half hour window when a new template was available, you would have ended up automatically upgrading  your network-services. And then getting automatically downgrade (when we reverted the PR) and stuck in the situation where it doesn't know what template version that you are on (ie. the grey button on your stack). 

Initially, our first method of preventing automatic ugprades was to separate the branch used in Rancher catalog. But after the accidentally merge, we've put on additional protection to the `master` branch so that any PRs would automatically look like this and it'd be much more apparent that it shouldn't be merged. 

<img width="715" alt="screen shot 2017-07-20 at 8 21 31 pm" src="https://user-images.githubusercontent.com/11410997/28447950-0f53c386-6d89-11e7-9810-e4a44e6002d6.png">

Again, we apologize for this accident, but hope the workaround has solved it. If you upgrade to v1.6.2+, you will not incur this problem as the automatic upgrade was fixed.

**Comment by dwo** [comment] 2017-07-21 13:01
@deniseschannon Thanks for the explanation, and glad to hear it's not likely to bite us again. 😄

**Closed** 2017-07-21 17:23 UTC

**Comment by Taffarel** [comment] 2017-07-25 20:11
@leodotcloud your fix works fine for me!!!! Save me a lot of time. Thank you so much!!!!

**Comment by Edenshaw** [comment] 2017-11-24 18:28
Thank you for the information @leodotcloud, your reply helped me solving this issue. I think other option to solve the problems of the network-services version without touching the API would be:

1. Delete the entire stack of the network-services
2. Go to the Catalog of Rancher
3. Search for network-services
4. Select latest version and deploy

It worked for me and you don't have to do any modification using the API.

**Comment by Maghin** [comment] 2018-05-18 14:35
Hi, we had this exact problem and this last answer worked for us, thank you @Edenshaw 
We were migrating docker from 1.12.6 to 1.13.1 then rancher from 1.6.7 to 1.6.17

**Comment by mautz-et-tong** [comment] 2018-09-06 12:36
The solution from @Edenshaw works in 1.6.21. Thank you
