### ISSUE TITLE
Cloned container (not service) will error out with ('NoneType' object has no attribute 'iteritems')

### ISSUE THREAD

**Issue by monkstick** [rancher/rancher#5218] opened 2016-06-22 15:39 UTC
Sorry if this is a bit messy, its my first bug report

**Rancher Version:**
Rancher v1.1.0-dev5
Cattle  v0.164.1
User Interface  v1.1.10
Rancher Compose v0.8.4

**Docker Version:**
Containers: 9
 Running: 3
 Paused: 0
 Stopped: 6
Images: 5
Server Version: 1.11.2
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 53
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge null host
Kernel Version: 4.4.0-21-generic
Operating System: Ubuntu 16.04 LTS
OSType: linux
Architecture: x86_64
CPUs: 16
Total Memory: 4.611 GiB
Name: ubuntu
ID: JH4G:OBZ4:IQXY:LYFC:6B6J:FGWJ:6LHM:WYSD:O5R2:AKMU:53JM:4RSK
Docker Root Dir: /var/lib/docker
Debug mode (client): false
Debug mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support

**OS and where are the hosts located? (cloud, bare metal, etc):**
Windows 10 Hyper-V -> Ubuntu 16.04

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
Two windows 10 Pro servers running Hyper-V, both running Ubuntu 16.04
Server #1 (The one that I supplied docker info for) runs the Rancher server
Server #1 has a rancher client
Server #2 has a rancher client

(I have tried in various configurations and tried using Debian 8.5.0 with the exact same results)

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
I am unsure what this means

**Steps to Reproduce:**
Install a fresh Ubuntu server on Hyper-V
Install Rancher and docker
log in, add host and use my local IP address
Spin up the rancher/agent using the add host string 
Start any container with any settings. 
Clone the container using the GUI

Fails with this error:  Error ('NoneType' object has no attribute 'iteritems')

**Results:** 
Container fails to clone and produces this error: Fails with this error:  Error ('NoneType' object has no attribute 'iteritems')

**Expected:**

Container to clone

EDIT: Also, if I create a new container, without using the clone feature and manually input the same ports, volumes, schedules etc, then it spins up perfectly fine

**Comment by deniseschannon** [comment] 2016-06-22 15:57
I am unable to reproduce in v1.1.0-dev5 when doing a simple clone test.

Are you starting services or containers? Could you share the equivalent docker-compose.yml? This can be found for a service by clicking on the stack name and clicking on "View Config".

**Comment by monkstick** [comment] 2016-06-22 16:13
I am starting containers, no stacks or anything else, other than Infrastructure - Hosts

Where do I find docker-compose.yml for containers?

The only pattern I can find is Hyper-V. On my server (Laptop) before this one, It was running bare metal.

**Comment by monkstick** [comment] 2016-06-22 16:21
As I am more of a visual kind of guy,

https://youtu.be/sxmpid5aZCg

**Comment by deniseschannon** [comment] 2016-06-22 16:41
Thanks! The video was super helpful. The error looked like a UI issue, so I hadn't actually tried to create the container. 

I can verify that I was able ot reproduce. This isn't happening when cloning with services, but only with containers. 

Steps To Reproduce:
1. Add a container (nginx)
2. Clone container
3. Change name 
4. Click on create

Container will error out with "('NoneType' object has no attribute 'iteritems')"

**Comment by deniseschannon** [comment] 2016-06-22 16:42
@monkstick Please try using services to launch containers. It's under Stacks->Add Service.  You can specify specific hosts as well.

**Comment by monkstick** [comment] 2016-06-22 17:02
@deniseschannon I can confirm that cloning when using a service seems to work.

Does using a Service instead of adding a container the way I was doing it do anything different, or is it just a UI thing?

Regardless, Thanks for the workaround!

**Comment by schuylr** [comment] 2016-07-06 20:12
I can confirm the same bug, when just trying to clone a simple Ubuntu container (not part of any service)

**Comment by linsheng9731** [comment] 2016-07-20 03:18
I got same bug when i use clone function !
The full stack trace as below :

```
2016-07-20 03:06:04,406 ERROR agent [140312235551632] [event.py:112] Error in request : 5e24d920-18ac-472c-a459-3a3f94ba4b21
Traceback (most recent call last):
  File "/var/lib/cattle/pyagent/cattle/agent/event.py", line 95, in _worker_main
    resp = agent.execute(req)
  File "/var/lib/cattle/pyagent/cattle/agent/__init__.py", line 15, in execute
    return self._router.route(req)
  File "/var/lib/cattle/pyagent/cattle/plugins/core/event_router.py", line 13, in route
    resp = handler.execute(req)
  File "/var/lib/cattle/pyagent/cattle/agent/handler.py", line 34, in execute
    return method(req=req, **req.data.__dict__)
  File "/var/lib/cattle/pyagent/cattle/plugins/docker/compute.py", line 529, in instance_activate
    self._do_instance_activate(instance, host, progress)
  File "/var/lib/cattle/pyagent/cattle/plugins/docker/compute.py", line 600, in _do_instance_activate
    self._setup_device_options(create_config['host_config'], instance)
  File "/var/lib/cattle/pyagent/cattle/plugins/docker/compute.py", line 781, in _setup_device_options
    for dev, options in device_options.iteritems():
AttributeError: 'NoneType' object has no attribute 'iteritems'
```

**Comment by TimWeyand** [comment] 2016-08-05 22:49
I am having the same bug, while cloning an container. If i use the same settings and creating a new container - it works

**Comment by arellano-gustavo** [comment] 2016-08-15 23:17
Same bug here.

**Comment by arko19** [comment] 2016-09-03 20:54
I got the same bug in v1.2.0-pre2

**Comment by vincent99** [comment] 2016-09-04 02:02
@cjellick wouldn't this be from the Python agent?

**Comment by cjellick** [comment] 2016-09-06 16:30
Yeah, Apparently in this scenario, deviceOptions is present in the json object but explicitly set to null
https://github.com/rancher/python-agent/blob/master/cattle/plugins/docker/compute.py#L776-L781

Similar to this bug:
https://github.com/rancher/python-agent/pull/238

**Comment by JaviSabalete** [comment] 2016-09-28 16:05
Same behavior here

**Comment by fjmoreno** [comment] 2016-09-30 14:51
same on 1.1.4

**Comment by chcheruk** [comment] 2016-09-30 19:24
Same observed on 
Rancher	v1.1.3
Cattle	v0.165.8.1
User Interface	v1.1.12
Rancher Compose	v0.8.6

**Comment by ybbaigo** [comment] 2016-10-17 08:57
+1 for same on 1.1.4

**Comment by oxplayru** [comment] 2016-11-13 06:17
+1

**Comment by cjellick** [comment] 2016-11-15 14:35
rancher 1.2.0 will address this as the agent responsible for the bug (python-agent) has been completely rewritten in go.

**Comment by cjellick** [comment] 2016-11-15 14:36
ping @deniseschannon - just fyi - im assign this to the 1.2.0 milestone since it has been addressed by the agent rewrite.

**Comment by cjellick** [comment] 2016-11-15 14:36
Ping @StrongMonkey, since you're the one who rewrote the agent :-)

**Comment by sangeethah** [comment] 2016-11-16 01:26
Tested with latest build from master.
rancher-agent version - rancher/agent:v1.1.0-rc15
Steps To Reproduce:
1. Add a container (nginx)
2. Clone container
3. Change name 
4. Click on create

Able to create the cloned container successfully.

**Closed by sangeethah** 2016-11-16 01:26 UTC
Labels: area/container, kind/bug, status/resolved, status/to-test
