### ISSUE TITLE
[Forwardport] air gap RKE2 downstream cluster fails to pull images if the registry mirrors endpoint does not contain a schema

### ISSUE THREAD

**Issue by Sahota1225** [rancher/rancher#46433] opened 2024-08-01 22:17 UTC
Forwardport: https://github.com/rancher/rancher/issues/46090

**Comment by markusewalker** [comment] 2024-08-02 16:07
**QA TEST PLAN**

|#|Scenario|
|---|---|
|1|Provision RKE2 air-gap downstream cluster with `https://` schema in mirror endpoint|
|2|Provision RKE2 air-gap downstream cluster without `https://` schema in mirror endpoint|
|3|Provision RKE2 non air-gap downstream cluster with `https://` schema in mirror endpoint|
|4|Provision RKE2 non air-gap downstream cluster without `https://` schema in mirror endpoint|

**Comment by jiaqiluo** [comment] 2024-08-02 19:16
Closing as a duplicate of https://github.com/rancher/rancher/issues/46400

**Closed by jiaqiluo** 2024-08-02 19:16 UTC
Labels: kind/bug, priority/1, internal, QA/S, area/provisioning-v2, team/hostbusters
