### ISSUE TITLE
how can I get the kubeconfig file without Rancher Auth-proxy?

### ISSUE THREAD

**Issue by satomic** [rancher/rancher#18900] opened 2019-03-14 03:37 UTC
often we create a k8s cluster by using Rancher UI, that's easy. And we can also download the `kubeconfig` file on the cluster level easily.

but my question is, the `kubeconfig` file on Rancher UI we can get is a **Rancher Auth-Proxy** kubeconfig file, that means, if the rancher server is down, we can not control our k8s cluster anymore.

I know that we can get the `kubecfg-kube-admin.yaml` file in the path `/etc/kubernetes/ssl` or `/etc/kubernetes/.tmp` of the `rancher-node-agent` pod, but acturally, not every time the yaml file is exists there. that makes me very confused. cuz if my Rancher Server is down, I recreate a rancher server, but without the original `kubeconfig` file, I can not reimport the k8s cluster to the new rancher server again.

is there any convinent way to get the orignal `kubeconfig` file directly connected to the k8s apiserver without rancher-auth-proxy?
or can you add a new button on Rancher UI for us to download such a file easier? thanks.

@loganhz

**Comment by alena1108** [comment] 2019-03-14 03:45
@satomic "Make clusters reachable without master" feature will be available in rancher 2.2. Here is the ticket for the ref:

https://github.com/rancher/rancher/issues/13698

**Comment by satomic** [comment] 2019-03-14 04:03
@alena1108 cool, thanks! can not wait for the 2.2 GA anymore

**Comment by alena1108** [comment] 2019-03-14 04:56
@satomic np! Closing the issue as a duplicate of 13698

**Closed by alena1108** 2019-03-14 04:56 UTC
