### ISSUE TITLE
unable to create single node EKS cluster

### ISSUE THREAD

**Issue by raazcrzy** [rancher/rancher#19388] opened 2019-04-04 14:53 UTC
**What kind of request is this (question/bug/enhancement/feature request):**
bug

**Steps to reproduce (least amount of steps as possible):**
1. Try to create a one node EKS cluster
2. After going into `provisioning` status, cluster creation fails. 

**Result:**
The error message is:
```
Error creating stack: stack failed to create: Desired capacity:3 must be between the specified min size:1 and max size:1 (Service: AmazonAutoScaling; Status Code: 400; Error Code: ValidationError; Request ID: redated)
```

**Other details that may be helpful:**
The request captured from network tab:
```
{"dockerRootDir":"/var/lib/docker","enableClusterAlerting":false,"enableClusterMonitoring":false,"enableNetworkPolicy":false,"type":"cluster","amazonElasticContainerServiceConfig":{"accessKey":"redated","ami":"","associateWorkerNodePublicIp":true,"displayName":"","driverName":"amazonelasticcontainerservice","instanceType":"t3.medium","kubernetesVersion":"1.11","maximumNodes":1,"minimumNodes":1,"nodeVolumeSize":0,"region":"us-west-2","serviceRole":"eaas-admin","sessionToken":"","userData":"","virtualNetwork":null,"type":"amazonElasticContainerServiceConfig","secretKey":"redated","subnets":[]},"name":"test-eks-cluster"}

```

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): rancher/rancher:v2.2.1
- Installation option (single install/HA): single node

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): rancher hosted on GKE
- Machine type (cloud/VM/metal) and specifications (CPU/memory): 4/15
- Kubernetes version (use `kubectl version`): 1.11

```
(paste the output here)
```

- Docker version (use `docker version`):

```
(paste the output here)
```

**Comment by rmweir** [comment] 2019-04-05 04:34
@raazcrzy thank you for filing an issue. I believe this is a duplicate of https://github.com/rancher/rancher/issues/18243.

**Closed** 2019-04-05 07:17 UTC
