### ISSUE TITLE
[feature request] healtheck for external services

### ISSUE THREAD

**Issue by ndelitski** [rancher/rancher#2506] opened 2015-11-02 16:27 UTC
I define AWS ElastiCache in rancher environment as an external service and would like to monitor it in a same way as my other services in the environment. Hope there will be alarms in the near future.

**Comment by deniseschannon** [comment] 2015-11-02 18:04
Didn't realize this is a duplicate of https://github.com/rancher/rancher/issues/1773

**Closed by deniseschannon** 2015-11-02 18:04 UTC
Labels: area/service, kind/feature
