### ISSUE TITLE
Installed rancher convoy-gluster catalog template, it was broken, and can't remove it

### ISSUE THREAD

**Issue by virtuman** [rancher/rancher#6197] opened 2016-10-08 01:59 UTC
**Rancher Version:**
rancher/server:v1.2.0-pre4-rc1

**Docker Version:**
Server Version: 1.12.1

**OS and where are the hosts located? (cloud, bare metal, etc):**
3 x Dedicated bare metal servers
PRETTY_NAME="Ubuntu 16.04.1 LTS"

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
single node rancher
single network interfaces on all 3 servers
external mysql DB

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle

**Steps to Reproduce:**
Installed convoy-gluster storage driver from the older version of catalog template, it was not working due to some paths mismatch, tried to revert all my installation steps, but it still left the options in the Administration -> Storage menu, and I think it's actually keeps on trying to initialize itself non-stop all the time, despite the fact that I've been trying to erase it since the very beginning:

![screen shot 2016-10-07 at 6 53 47 pm](https://cloud.githubusercontent.com/assets/1087996/19209453/74aa60ec-8cbf-11e6-963d-c914adeb5f82.png)

**Results:** 
very slow rancher UI
tried to install amazon efs, but it wouldn't install and I'm suspecting that it's somehow conflicting with my previous installation of convoy-gluster

also I always see these types of entries in docker logs -f rancher:

```
2016-10-08 02:26:41,385 ERROR [:] [] [] [] [ServiceReplay-8] [i.c.p.e.e.i.ProcessEventListenerImpl] Unknown exception running process [instance.stop:769758] on [18776], canceled by [State [requested] is not valid for process [port.deactivate:null] on resource [10218]]
2016-10-08 02:26:41,411 ERROR [:] [] [] [] [ServiceReplay-9] [i.c.p.e.e.i.ProcessEventListenerImpl] Unknown exception running process [mount.create:801539] on [49543], canceled by [State [deactivating] is not valid for process [volume.activate:818315] on resource [29892]]
2016-10-08 02:27:41,372 ERROR [69611c2e-f2da-4741-be73-8ece56ef2245:801495] [volume:29892->volumeStoragePoolMap:28972] [volume.deactivate->(VolumeDeactivate)->volumestoragepoolmap.remove] [] [erviceReplay-21] [c.p.e.p.i.DefaultProcessInstanceImpl] Agent error for [storage.volume.remove.reply;agent=680]: VolumeRemove: failed to remove volume: DoVolumeRemove: failed to remove volume: Error response from daemon: Unable to remove volume, volume still in use: remove bbc5a21de53dbe683bf8e9c79fdbf55f588f9c98bf4a285e060144e7429f1e3a: volume is in use - [c51f3c958cc1341484af6b71f389a13d51ae828d0fe3c761d0e4db0f1d4f1376]
2016-10-08 02:27:41,373 ERROR [69611c2e-f2da-4741-be73-8ece56ef2245:801495] [volume:29892] [volume.deactivate] [] [erviceReplay-21] [c.p.e.p.i.DefaultProcessInstanceImpl] Agent error for [storage.volume.remove.reply;agent=680]: VolumeRemove: failed to remove volume: DoVolumeRemove: failed to remove volume: Error response from daemon: Unable to remove volume, volume still in use: remove bbc5a21de53dbe683bf8e9c79fdbf55f588f9c98bf4a285e060144e7429f1e3a: volume is in use - [c51f3c958cc1341484af6b71f389a13d51ae828d0fe3c761d0e4db0f1d4f1376]
2016-10-08 02:27:41,431 ERROR [:] [] [] [] [erviceReplay-21] [i.c.p.e.e.i.ProcessEventListenerImpl] Agent error for [storage.volume.remove.reply;agent=680]: VolumeRemove: failed to remove volume: DoVolumeRemove: failed to remove volume: Error response from daemon: Unable to remove volume, volume still in use: remove bbc5a21de53dbe683bf8e9c79fdbf55f588f9c98bf4a285e060144e7429f1e3a: volume is in use - [c51f3c958cc1341484af6b71f389a13d51ae828d0fe3c761d0e4db0f1d4f1376]
```

**Expected:**
expected to have been able to get the volume, but shortly after trying to installed learned that it wasn't longer working.

I just want to be able to maintain minimal deployment data in some backup and try to re-create complete rancher deployment without losing any data of already deployed stacks and containers, to be able to continue to manage it in the rancher, but would ideally like to be able to reset all "bad" data from rancher DB

**Comment by janeczku** [comment] 2016-10-12 11:28
@virtuman Do you maybe still have a service that is referencing a convoy-gluster volume?
To clean up the storage pool, follow the steps listed here:
https://github.com/rancher/rancher/issues/2918#issuecomment-217216012
and please let me know if that worked for you,

**Comment by virtuman** [comment] 2016-10-12 20:18
I was never able to set up convoy to get it to work, so no references were ever made to it, at least as far as I know, maybe it did something on it's own? How could I check ?

I wasn't able to figure out how to delete and purge the volume; i tried the following:
http://localhost:8080/v1/projects/1a5/storagepools/

I saw the link to deactivate:
http://localhost:8080/v1/projects/1a5/storagepools/1sp12/?action=deactivate

but didn't see how to REMOVE or PURGE, i tried changing the `?action=remove` and `?action=purge` but the volume still appears under the 
http://localhost:8080/v1/projects/1a5/storagepools/

so probably not doing something right? could you elaborate on how to remove and purge ?

Thank you.

**Comment by virtuman** [comment] 2016-10-12 20:24
Is there supposed to be a storagepool for each host? or did these get created along with convoy installation and need to also be removed?


{

    "id": "1sp29",
    "type": "storagePool",
    "links": {
        "self": "…/v1/projects/1a5/storagepools/1sp29",
        "account": "…/v1/projects/1a5/storagepools/1sp29/account",
        "credentials": "…/v1/projects/1a5/storagepools/1sp29/credentials",
        "hosts": "…/v1/projects/1a5/storagepools/1sp29/hosts",
        "images": "…/v1/projects/1a5/storagepools/1sp29/images",
        "volumes": "…/v1/projects/1a5/storagepools/1sp29/volumes"
    },
    "actions": {
        "update": "…/v1/projects/1a5/storagepools/1sp29/?action=update",
        "deactivate": "…/v1/projects/1a5/storagepools/1sp29/?action=deactivate"
    },
    "baseType": "storagePool",
    "name": "srv-eu2 Storage Pool",
    "state": "active",
    "accountId": "1a5",
    "blockDevicePath": null,
    "created": "2016-08-16T01:35:36Z",
    "createdTS": 1471311336000,
    "description": null,
    "driverName": null,
    "externalId": null,
    "kind": "docker",
    "removed": null,
    "transitioning": "no",
    "transitioningMessage": null,
    "transitioningProgress": null,
    "uuid": "cf847a54-9858-405d-a14e-642e75fc9e99",
    "volumeAccessMode": null,
    "volumeCapabilities": null

}

**Comment by janeczku** [comment] 2016-10-16 13:01
@virtuman Host storage pools are created when the host is added. You don't need to remove them.
Where you able to setup convoy-efs now?

**Comment by janeczku** [comment] 2016-10-16 14:45
Pre-duplicate of https://github.com/rancher/rancher/issues/6263. @virtuman if you continue having problems getting convoy-efs to work after cleaning the storage pools please open a separate issue for it.

**Closed by janeczku** 2016-10-16 14:45 UTC
Labels: area/convoy
