### ISSUE TITLE
[v2.8] Remove CAPI webhook from rancher/webhook 

### ISSUE THREAD

**Issue by MKlimuszka** [rancher/rancher#44619] opened 2024-02-29 23:02 UTC
Backport of https://github.com/rancher/rancher/issues/43619

With the addition of the provisioning pod which now installs the capi webhook we no longer need to serve a separate webhook for capi in rancher/webhook.

rancher/webhook creates webhooks for capi in [capi.go](https://github.com/rancher/webhook/blob/release/v0.4/pkg/capi/capi.go) which can be removed as well as the sub chart which is created in rancher/webhook for capi.
Validation

Confirm that rancher/rancher no longer creates a validatingWebhookConfiguration that points to rancher/webhook capi endpoints.

**Comment by tomleb** [comment] 2024-03-01 22:17
@MKlimuszka Should we assign someone from QA for this? It's merged but not yet deployed in Rancher. 

If so, I'll provide a validation template next week.

**Comment by PeeBee66** [comment] 2024-03-04 06:20
Air gapped system not able to find capi-webhook-service - can this be removed in 2.8.2

[ERROR} failed to create fleet-default/testcluster cluster.x-k8s.io/v1beta1, Kind=cluster for rke-cluster fleet-defualt/testcluster: internal error occured: failed calling weekhook "default.cluster.cluster.x-k8s.io": failed to call webhook: Post "https://capi-webhook-service.cattle-provisioning-capi-system.svc:443/mutate-cluster-x-k8s-io-v1beta1-cluster?timeout=10s": service :capi-webhook-service: not found

**Comment by tomleb** [comment] 2024-03-04 14:49
> Air gapped system not able to find capi-webhook-service - can this be removed in 2.8.2
> 
> [ERROR} failed to create fleet-default/testcluster cluster.x-k8s.io/v1beta1, Kind=cluster for rke-cluster fleet-defualt/testcluster: internal error occured: failed calling weekhook "default.cluster.cluster.x-k8s.io": failed to call webhook: Post "https://capi-webhook-service.cattle-provisioning-capi-system.svc:443/mutate-cluster-x-k8s-io-v1beta1-cluster?timeout=10s": service :capi-webhook-service: not found

Can you elaborate on what you mean by "can this be removed in 2.8.2"? 2.8.2 is already released.

If you're encountering an issue with an existing installation then I suggest looking into the GH issues to see if anyone has solved it, or create one if there isn't any. Unless you believe your error message comes from the change of this issue here (not part of a release yet).

The capi-webhook-service one is the new CAPI webhook that we already migrated to in v2.7.7. The one we're removing here is the old one that shouldn't be in use anymore.

**Comment by tomleb** [comment] 2024-03-06 16:30
## Validation Template

## Root Cause

We removed the CAPI webhook from rancher/webhook. There's a LOT more details here: https://github.com/rancher/rancher/issues/43619#issuecomment-1971574484.

A quick summary is that before `v2.7.7`, Rancher was deploying the CAPI webhook from within the Rancher webhook pod. It was deployed using the chart defined in Rancher webhook repository. Starting from `v2.7.7`, the CAPI webhook was no longer deployed within the Rancher pod. Instead, it was deployed in another namespace by Rancher. Rancher was hardcoded to NOT deploy the CAPI webhook from webhook, but we kept the CAPI webhook charts in rancher/webhook anyway.

## What was fixed, or what change have occurred

We have completely removed the possibility to deploy the CAPI webhook from within the webhook pod.

This means:
- Rancher no longer provides CAPI specific parameter for the Helm installation command to deploy webhook.
- Webhook no longer contains any CAPI-specific code and neither CAPI-specific chart

## Areas or cases that should be tested

- P0 functionality for webhook
- Upgrading from version before `v2.7.7` to a version after `v2.7.7` should work, the CAPI webhook should still work and the following resources should be cleaned up(*):
    - Service `webhook-service` in namespace `cattle-system`
    - Secret `rancher-webhook-tls` in namespace `cattle-system`

(*): Side note on this but my change doesn't affect this, the change made in `v2.7.7` should have covered this already, but if it doesn't then we should probably fix it.

## What areas could experience regressions

We made some changes to the charts, some combination of values for the chart might render unusable YAML to deploy the webhook (integration tests only test a basic case).

I don't expect it but could be an issue when upgrading from before `v2.7.7` to this version that would prevent the CAPI webhook to work.



## Are the repro steps accurate/minimal?

N/A

**Comment by Priyashetty17** [comment] 2024-03-13 14:41
Before capi removal as part of this issue, when a user upgraded from version 2.7.6 (where capi.enabled was set to true) to 2.7.7+, the output of helm get values would show capi.enabled as false. However, with the current implementation, if we upgrade from version 2.7.6 (where capi.enabled is true) to 2.8.3-rc3, the output of helm get values would show capi.enabled as true. Moving this to "**Reopened**" to fix the helm values. 

**Note**: Even though the capi parameters are captured in the 'helm get values', there are no references to capi elsewhere ie., in the rancher-webhook deployment/pod.

**Comment by Priyashetty17** [comment] 2024-03-13 23:23
Validated with `v2.8-26957c1422431b50fa590fffaf7a5f7909ff6589-head` and `rancher-webhook:v0.4.3-rc1`. All scenarios identified in the test plan have been executed and passed ✅

**Closed by Priyashetty17** 2024-03-13 23:23 UTC
Labels: QA/M, kind/tech-debt, area/webhook, team/frameworks

**Comment by tomleb** [comment] 2024-03-21 17:49
# Release notes

## Rancher Webhook

### Behavior Changes

The embedded Cluster API webhook is removed from the rancher webhook and can no longer be installed from the webhook chart. The Cluster API webhook was already migrated to a separate Pod in a previous version (`v2.7.7`).
