### ISSUE TITLE
Editing deployed Rancher Logging looses state if you Edit as File

### ISSUE THREAD

**Issue by Tejeev** [rancher/rancher#26559] opened 2020-04-08 18:43 UTC
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
1. Enable logging on a cluster
2. Test that all is working.  
3. If it is, go back to logging, and choose to edit as file

**Result:**
All configurations are lost.  The same is true when going the other way.
It is also not at all clear how to format the file or what information should be pulled over.

**Expected Behavior**
We would expect the input configurations to be retained and displayed as you switch back and forth between the two methods of editing.  This would be in line with behavio we see in other items we edit as forms and files throughout the Rancher UI. 

**Other details that may be helpful:**

**Environment information**
- Rancher version: v2.3.x

**Workaround**
If you enabled while editing as form, your configurations are saved in a secret in the correct format.
1. Go to the system project
2. Navigate to Secrets
![image](https://user-images.githubusercontent.com/8906089/78820671-1e7eb400-79d0-11ea-9e54-2fb1f7264b29.png)
3. Select `rancher-logging-fluentd`
![image](https://user-images.githubusercontent.com/8906089/78820742-3eae7300-79d0-11ea-9a35-8944b6161a9c.png)
4. Select edit in the top right hand corner elipsis
![image](https://user-images.githubusercontent.com/8906089/78820807-584fba80-79d0-11ea-805e-1c544e6d0129.png)
5. Search for `elastic` in your browser and something will be highlighted in the clusters.conf key
![image](https://user-images.githubusercontent.com/8906089/78821007-a95fae80-79d0-11ea-991b-f7c47c832453.png)
![image](https://user-images.githubusercontent.com/8906089/78820986-9ea51980-79d0-11ea-80ce-5beebe32db32.png)
6. If you click in the Value field it will reveal the data.  Copy everything in the elasticsearch block.  This is the text you must enter into the `match` tags in the edit as file of your logging deployment
![image](https://user-images.githubusercontent.com/8906089/78821288-23903300-79d1-11ea-9dce-cbe21c9515e6.png)

gzrancher/rancher#9427

**Comment by Tejeev** [comment] 2020-04-14 22:22
Notes from #26543:
**What kind of request is this (question/bug/enhancement/feature request):**
bug

**Steps to reproduce (least amount of steps as possible):**

1. Enable logging on a cluster
2. `Test` the settings when Editing as a Form (make sure it is successful 
  ![image](https://user-images.githubusercontent.com/8906089/78721380-537efe00-791f-11ea-9796-7a723a833f13.png)
3. Go to Edit as a File and without making any changes, initiate a `Dry Run`

**Result:**
Dry run fails. 
![image](https://user-images.githubusercontent.com/8906089/78721477-8923e700-791f-11ea-9d03-1f23490b8ff9.png)

Even in a configuration where the dry succeeded (not sure why yet) the fluentd daemonset got stuck in a crashloop with no logs.

**Environment information**
- Rancher: v2.3.5

**Tested on:**
Rancher Launched (Provider) EC2 cluster
- Kubernetes: v1.17.2
- Elasticsearch: standalone docker container elasticsearch:7.6.0
- Logging: v0.1.4

Rancher Launched (Provider) Google GKE cluster
- Kubernetes: v1.15.9-gke.24
- Elasticsearch: standalone docker container elasticsearch:7.6.0
- Logging: v0.1.4

**Comment by tancou** [comment] 2020-05-01 19:30
Hi,

I have almost the same issue with the app catalog.
The parser between the View form and the YAML view is not working properly.

**Environment information :**

Component | Version
-- | --
Rancher | v2.4.2
User Interface | v2.4.14
Helm | v2.16.3-rancher1
Machine | v0.15.0-rancher35

**Bug 1 :**

**Steps to reproduce (least amount of steps as possible):**
1. Go to Apps
2. Deploy an app using YAML
3. Then upgrade the app.
4. Use the Form view.

**Result:**
Fields are empty.

**Expected Behavior**
Fields should display the correct configuration.

**Bug 2 :**

**Steps to reproduce (least amount of steps as possible):**
1. Go to Apps
2. Deploy an app using form view
3. Then upgrade the app.
4. Show the YAML view

**Result:**
Boolean values are defined with quotes

> myboolean: "true"

The Helm chart can't be upgraded because `myboolean` is a string and not a boolean.

**Expected Behavior**

Boolean values should be parsed properly.
> myboolean: true

**Bug 3 :**

**Steps to reproduce (least amount of steps as possible):**
1. Go to Apps
2. Deploy an app using form view
3. Edit a field/value
4. Show the YAML view
(Happens if you edit the YAML first too)

**Result:**
Values are not updated

**Expected Behavior**
Values should be the same as form view.

**Comment by westlywright** [comment] 2020-06-23 19:02
@tancou thanks for the info. I believe this is a separate issue unrelated to Logging so I have moved into a new ticket (see edit).

**Comment by izaac** [comment] 2020-10-19 17:44
Rancher version `v2.4-head` _f210f54bd_
I validated the **Fluentd Configuration** state is preserved navigating back and forth as Form and as File.

**Comment by izaac** [comment] 2020-10-19 17:46
Closing this issue as it's specific to `v2.4`

Will work on #29558 (`v2.5`) and #29562 (`master`)

**Closed by izaac** 2020-10-19 17:46 UTC
Labels: [zube]: To Triage, area/logging, internal, kind/enhancement, team/ui
