### ISSUE TITLE
Random mapping of ports is broken on upgrade

### ISSUE THREAD

**Issue by rzachariah** [rancher/rancher#3980] opened 2016-03-15 22:37 UTC
Rancher Version: Rancher 0.59.1

Docker Version: Docker 1.10.2

OS: Ubuntu 14.04.4 LTS

Steps to Reproduce: 
1. Create a Rancher catalog entry that deploys a stack containing a service that gets assigned a random high value port. For example, you could have a snippet of docker-compose.yml that looks like this. Note we only specify the private port for the collector. We rely on Rancher to assign the public port. We are relying on this feature: https://github.com/rancher/rancher/issues/2097
collector:
  ports:
  - "80"
2. Deploy this Rancher catalog entry to a Rancher environment. The first time you deploy, everything will work great. Collector will be assigned a random high value port.
3. Now make a modification to the catalog entry.
4. Perform an upgrade to the new catalog version.

Results: After upgrade, collector will have lost its public port.

Expected: Collector should retain its public port.

**Comment by deniseschannon** [comment] 2016-03-16 04:53
Duplicate of #3979

**Closed by deniseschannon** 2016-03-16 04:53 UTC
