### ISSUE TITLE
Unexpected behavior in downstream EKS cluster following rancher server upgrade to v2.6.7-rc3

### ISSUE THREAD

**Issue by Josh-Diamond** [rancher/rancher#38317] opened 2022-07-18 23:12 UTC
**Rancher Server Setup**
- Rancher version: `v2.6.6` => `v2.6.7-rc3`
- Installation option (Docker install/Helm Chart): `Helm`
- Proxy/Cert Details: `byo-valid`

**Information about the Cluster**
- Kubernetes version: `v1.21.13-eks-84b4fe6`
- Cluster Type (Local/Downstream):
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider):
Downstream, Hosted 

**User Information**
- What is the role of the user logged in? (Admin/Cluster Owner/Cluster Member/Project Owner/Project Member/Custom)
Standard user

**Describe the bug**
When rancher server is upgraded from `v2.6.6` => `v2.6.7-rc3`, downstream EKS cluster (active with 3 nodes) goes into an `Updating` state.  Machines are then scaled from `3` => `6`, then back down from `6` => `3`.  Once machines are scaled back down to `3`, the cluster comes up `Active`

**To Reproduce**
1. Fresh install of rancher `v2.6.6`
2. As standard user, provision a downstream 3-node EKS cluster, k8s 1.21
3. Once active, upgrade rancher server to `v2.6.7-rc3`
4. Reproduced

**Result**
Cluster goes into an `Updating` state.  Machines are then scaled from `3` => `6`, then back down from `6` => `3`.  Once machines are scaled back down to 3, the cluster comes up `Active`

**Expected Result**
Cluster state should go from `Active` => `Unavailable` => `Active`; Machines should NOT scale

**Screenshots**

`Immediately after rancher server upgrade`
<img width="1585" alt="Screen Shot 2022-07-18 at 3 37 12 PM" src="https://user-images.githubusercontent.com/46494969/179631593-2e1645bd-695e-486f-aef1-37aaf2510935.png">

`Updating EKS cluster scales to 6 machines`
<img width="1547" alt="Screen Shot 2022-07-18 at 3 38 56 PM" src="https://user-images.githubusercontent.com/46494969/179631627-4334c8df-5ed1-4c20-babb-70936d759980.png">

`Updating EKS cluster w/ 6 machines active`
<img width="1548" alt="Screen Shot 2022-07-18 at 3 41 18 PM" src="https://user-images.githubusercontent.com/46494969/179631655-430d19fc-1d21-463b-b8ba-9c1b6c68492a.png">

`Updating EKS cluster scales down - 4 machines`
<img width="1549" alt="Screen Shot 2022-07-18 at 3 47 57 PM" src="https://user-images.githubusercontent.com/46494969/179631796-d79ce5db-f4e4-4d9f-8f84-5a13f68cb521.png">

`Updating EKS cluster scales down - 3 machines`
<img width="1528" alt="Screen Shot 2022-07-18 at 3 49 53 PM" src="https://user-images.githubusercontent.com/46494969/179631833-dad039ba-edd6-4a49-bc00-fa6efb146f20.png">

`EKS cluster eventually resolves as Active`
<img width="1528" alt="Screen Shot 2022-07-18 at 3 51 40 PM" src="https://user-images.githubusercontent.com/46494969/179631868-9f439813-211d-4df7-a171-3556503d757d.png">

**Comment by annablender** [comment] 2022-07-19 20:46
I investigated this with @Josh-Diamond. This node scale behavior is expected because of this regression fix https://github.com/rancher/rancher/issues/38014. After provisioning a cluster, EKS will now add the default cluster security group (created by EKS) to a new launch template version, then start a rolling update to apply that launch template to the nodes. EKS will often scale the nodes up/down to complete the rolling update faster.

@Josh-Diamond didn't see any scale when first creating the jkeslar clusters because you weren't running. https://github.com/rancher/rancher/releases/tag/v2.6.7-rc3 yet, which means you weren't running the latest version of eks operator which has the default security group fix. On upgrade to v2.6.7-rc3, the update was pulled in and a rolling update to add the default security group was started. As long as the cluster comes up active and stable after the nodegroup, then this is fine.

This ticket can be closed.

**Comment by Josh-Diamond** [comment] 2022-07-19 23:19
Although this is expected behavior given our recent changes, it should NOT be expected behavior overall, and needs to be addressed

**Comment by snasovich** [comment] 2022-07-20 20:51
Closing this issue as we're going to be rolling back the change that led to it, see https://github.com/rancher/rancher/issues/38303#issuecomment-1190737178 for more info.

**Closed** 2022-07-20 20:51 UTC
Labels: status/wontfix, kind/bug-qa, [zube]: Done, team/area2
