### ISSUE TITLE
NodeController Panics

### ISSUE THREAD

**Issue by ekristen** [rancher/rancher#26368] opened 2020-03-30 16:11 UTC
**What kind of request is this (question/bug/enhancement/feature request):**

bug

**Steps to reproduce (least amount of steps as possible):**

Unsure

**Result:**

Panic

**Other details that may be helpful:**

I upgraded a cluster this morning and only the control nodes upgraded while all the worker nodes failed to upgrade.

My Rancher HA logs are 

```
2020/03/30 16:07:35 [ERROR] NodeController ip-10-50-150-56.us-west-2.compute.internal recovered from panic "runtime error: invalid memory address or nil pointer dereference". (err=<nil>) Call stack:
goroutine 7427 [running]:
github.com/rancher/rancher/vendor/k8s.io/apimachinery/pkg/util/runtime.RecoverFromPanic(0xc017c85db0)
/go/src/github.com/rancher/rancher/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:158 +0xb5
panic(0x3255340, 0x6bf26d0)
/usr/local/go/src/runtime/panic.go:522 +0x1b5
github.com/rancher/rancher/pkg/controllers/user/monitoring.(*clusterMonitoringEnabledHandler).syncWindowsNode(0xc00cfa6300, 0xc01d0353e0, 0x2a, 0x0, 0xc019917180, 0x7fa0f6a8c008, 0x0, 0x0)
/go/src/github.com/rancher/rancher/pkg/controllers/user/monitoring/cluster_monitoring_enabled_handler.go:58 +0xe7
github.com/rancher/rancher/vendor/github.com/rancher/types/apis/core/v1.(*nodeController).AddHandler.func1(0xc01d0353e0, 0x2a, 0x0, 0x0, 0xc017c85d58, 0x3, 0x3, 0x0)
/go/src/github.com/rancher/rancher/vendor/github.com/rancher/types/apis/core/v1/zz_generated_node_controller.go:149 +0xe0
github.com/rancher/rancher/vendor/github.com/rancher/norman/controller.(*genericController).syncHandler(0xc00ce0a300, 0x2fe9880, 0xc024e8a620, 0x0, 0x0)
/go/src/github.com/rancher/rancher/vendor/github.com/rancher/norman/controller/generic_controller.go:367 +0x35d
github.com/rancher/rancher/vendor/github.com/rancher/norman/controller.(*genericController).processNextWorkItem(0xc00ce0a300, 0xc00d170c00)
/go/src/github.com/rancher/rancher/vendor/github.com/rancher/norman/controller/generic_controller.go:276 +0xd3
github.com/rancher/rancher/vendor/github.com/rancher/norman/controller.(*genericController).runWorker(0xc00ce0a300)
/go/src/github.com/rancher/rancher/vendor/github.com/rancher/norman/controller/generic_controller.go:264 +0x2b
github.com/rancher/rancher/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1(0xc00d5f4590)
/go/src/github.com/rancher/rancher/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:152 +0x54
github.com/rancher/rancher/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc00d5f4590, 0x3b9aca00, 0x0, 0x1, 0xc00a288120)
/go/src/github.com/rancher/rancher/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:153 +0xf8
github.com/rancher/rancher/vendor/k8s.io/apimachinery/pkg/util/wait.Until(0xc00d5f4590, 0x3b9aca00, 0xc00a288120)
/go/src/github.com/rancher/rancher/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:88 +0x4d
created by github.com/rancher/rancher/vendor/github.com/rancher/norman/controller.(*genericController).run
/go/src/github.com/rancher/rancher/vendor/github.com/rancher/norman/controller/generic_controller.go:256 +0xb7
```

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): 2.3.3
- Installation option (single install/HA): HA

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): Custom
- Machine type (cloud/VM/metal) and specifications (CPU/memory): Metal
- Kubernetes version (use `kubectl version`): 

```
(paste the output here)
```

- Docker version (use `docker version`):

```
(paste the output here)
```

**Comment by ekristen** [comment] 2020-03-30 16:20
Might be related to https://github.com/rancher/rancher/issues/26368

**Comment by superseb** [comment] 2020-03-30 16:22
Duplicate of https://github.com/rancher/rancher/issues/25203

**Closed by superseb** 2020-03-30 16:22 UTC

**Comment by ekristen** [comment] 2020-03-30 16:24
Dang, no matter how hard I search I can never seem to find the related issue. Thanks @superseb sorry for the dupe.
