### ISSUE TITLE
Node template select custom node driver, need to refresh the page first

### ISSUE THREAD

**Issue by rootwuj** [rancher/rancher#19034] opened 2019-03-20 01:11 UTC
**What kind of request is this (question/bug/enhancement/feature request):**
bug

**Steps to reproduce (least amount of steps as possible):**
1. Add a custom host driver
2. Add a host template and choose a custom driver

**Result:**
When you select a custom driver, the options are not displayed. Need to refresh the page first.

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): rancher/rancher:mster
- Installation option (single install/HA):single

**Comment by westlywright** [comment] 2019-03-27 18:08
Dupe of https://github.com/rancher/rancher/issues/19066, closing in favor of that one.

**Closed by westlywright** 2019-03-27 18:08 UTC
