### ISSUE TITLE
Rancher backup and restore fails with errors for imported RKE2 version (v1.20.9+rke2r1)

### ISSUE THREAD

**Issue by janeczku** [rancher/rancher#33942] opened 2021-08-04 15:55 UTC
**Rancher Server Setup**
- Rancher version: 2.5.9
- Installation option (Docker install/Helm Chart):
RKE2

**Information about the Cluster**
- Kubernetes version: v1.20.9+rke2r1
- Cluster Type (Local/Downstream): Local

**Describe the bug**

Creating Rancher backups  or restoring existing backup with Rancher Backup Operator fails every single time.

**To Reproduce**
 
1. Install Rancher using the Rancher and Kubernetes versions documented above
2. Follow the docs to backup Rancher: https://rancher.com/docs/rancher/v2.5/en/backups/back-up-rancher/
3. Follow the docs to restore Rancher from an existing backup: https://rancher.com/docs/rancher/v2.5/en/backups/restoring-rancher/

**Result**

1. Backup operation fails
2. Restore operation fails

The following error is logged in the `rancher-backup` pod in the `cattle-system-ressource` namespace:

```
ERRO[2021/08/04 15:47:55] error syncing 'twofold': handler backups: Backup.resources.cattle.io "twofold" is invalid: [status.summary: Invalid value: "null": status.summary in body must be of type string: "null", status.nextSnapshotAt: Invalid value: "null": status.nextSnapshotAt in body must be of type string: "null"]Backup.resources.cattle.io "twofold" is invalid: [status.storageLocation: Invalid value: "null": status.storageLocation in body must be of type string: "null", status.summary: Invalid value: "null": status.summary in body must be of type string: "null", status.backupType: Invalid value: "null": status.backupType in body must be of type string: "null", status.filename: Invalid value: "null": status.filename in body must be of type string: "null", status.lastSnapshotTs: Invalid value: "null": status.lastSnapshotTs in body must be of type string: "null", status.nextSnapshotAt: Invalid value: "null": status.nextSnapshotAt in body must be of type string: "null"], requeuing
```

**Expected Result**

Backup and restore works.

**JIRA ID**: SURE-3220

**Comment by snasovich** [comment] 2021-08-04 18:24
After discussing it with @deniseschannon we want this fix in 2.6.0.

**Comment by snasovich** [comment] 2021-08-05 21:54
@janeczku , this issue is specific to this exact version of RKE2 (`v1.20.9+rke2r1`) as it fails on setting any string field to `""`. Related RKE2 issue: https://github.com/rancher/rke2/issues/1530
The impact of this RKE2 issue is likely too big to be reasonably addressed in all Rancher-related components. RKE2 team is working on a fix. Meanwhile, suggesting to use `v1.20.8+rke2r1` as it's not affected.
Thus, suggesting to close this issue. Please do if you're OK with this resolution.

**Comment by snasovich** [comment] 2021-08-06 14:56
Also note this version is now marked as pre-release with note on the referenced issue: https://github.com/rancher/rke2/releases/tag/v1.20.9+rke2r1

**Comment by deniseschannon** [comment] 2021-08-09 05:11
Using this issue to track that KDM is updated in dev-v2.6. 

Note: In KDM for v2.5, the bad version has been hidden and not able to upgrade to.

**Comment by Jono-SUSE-Rancher** [comment] 2021-08-10 18:08
Should be ready to test via https://github.com/rancher/rke2/issues/1530

**Comment by rancher-max** [comment] 2021-08-11 19:48
I see this working now in v1.20.9+rke2r2 and backups can successfully be taken. Just did this simple scenario as I already validated the rke2 related issue that is the root cause:
<img width="1436" alt="image" src="https://user-images.githubusercontent.com/55997940/129093576-36c04560-d9e4-40eb-968c-754ccb99883b.png">

**Closed by rancher-max** 2021-08-11 19:48 UTC
Labels: area/backup-recover, status/dev-validate, dependency-rke2
