### ISSUE TITLE
Host from different environment are showing up in the UI on "Hosts" tab

### ISSUE THREAD

**Issue by alena1108** [rancher/rancher#2336] opened 2015-10-13 19:24 UTC
Reported by the user. Steps to reproduce:

1) Have 2 environments: e1 and e2
2) Pick e1 in the UI, go to the "Hosts" view. After some time you can see hosts from e2 showing up under this view.

In the screeshot below, 7th host belongs to a different environment. Gist shows the environments' objects details

https://s3.amazonaws.com/uploads.hipchat.com/34474/320787/GjdqOuQzDING5Lr/Screen%20Shot%202015-10-13%20at%207.39.25%20AM.png
https://gist.github.com/tobowers/590edfde9fc454afbf3e

@vincent99 any idea what could have caused it? Is it most likely related to an incorrect account_id being set in the event sent by Rancher, or some UI bug?

**Comment by sangeethah** [comment] 2015-10-15 14:39
I have seen this issue happen in this scenario:

In my set up , I create an environment - say "abc" and I am in the "Infrastructure" tab of this environment.

Using API testing , I am creating/deleting services in "Default" environment , when I am still logged in  UI in environment "abc". I see hosts from "Default" environment being listed in the "Infrastructure" view. When UI is refreshed, the hosts from "Default" environment would not be seen anymore.

**Comment by vincent99** [comment] 2015-10-15 16:07
This sounds like the subscribe socket is sometimes sending the UI events for resources that don't along to the active environment.

**Comment by ibuildthecloud** [comment] 2015-10-15 16:34
I'd say you have two sockets open...

**Comment by ibuildthecloud** [comment] 2015-10-15 16:45
Can somebody validate that this only happens with admin accounts.  That is my suspicion.

**Comment by deniseschannon** [comment] 2015-10-16 03:16
@sangeethah Let's try your scenario together where I'm logged in as an user and you're an admin.

**Comment by ebr** [comment] 2015-10-19 19:57
I've seen this happen at least 3 times, but the incorrect host disappears after a few minutes (it's still present in its correct environment). It does feel like what @vincent99 described re: subscribe socket.

**Comment by deniseschannon** [comment] 2015-10-22 19:14
We have been unable to reproduce this issue to confirm that it's only admins. 

But @ebr and @tobowers, can you confirm if you've seen this from users or just admins?

**Comment by tobowers** [comment] 2015-10-22 19:52
I have seen it and my colleague has seen it and both of us are admins. It's possible that it's only admins.

**Comment by deniseschannon** [comment] 2015-10-22 20:05
Since admins get access to all environments (even if you aren't a member), that might play a part in why only admins see the issue.

**Comment by ebr** [comment] 2015-10-28 17:21
@deniseschannon I can't really confirm this for non-admin users since we only have admins (small shop), and also i've only seen this happen a few times, so not readily reproducible.

**Comment by vincent99** [comment] 2016-03-08 08:26
I think whatever this might have been was resolved with changes to the way the Socket is opened in the UI based on the current project.

**Comment by tfiduccia** [comment] 2016-03-09 17:59
Version - master 3/9
Was able to reproduce this and the fix is in the next release.
Verified fixed.

**Closed by tfiduccia** 2016-03-09 17:59 UTC
Labels: area/ui, kind/bug, release/v1.0.0, status/to-test
