### ISSUE TITLE
 Error (409 Client Error: Conflict ("create <active volume>: conflict: volume name must be unique")

### ISSUE THREAD

**Issue by gerbac** [rancher/rancher#6031] opened 2016-09-22 09:24 UTC
**Rancher Version:** v1.0.2

**Docker Version:** v1.11.2

**OS and where are the hosts located? OS is linux Ubuntu (local)

**Environment Type: (Cattle)**

**Setup Details:** 

Some of our containers were mounted to convoy-nfs driver. When running the same container in different hosts with the "same volume mounts" the above error was produced. 

We tried renaming the container, still the error occurs. Now, we can't run our container to different hosts as it looks on the same volume. 

Are we missing something in our set up?

Could you help us out? 

Parent Directory used in nfs-server: /exports

Thanks in Advance!

**Comment by blaisef3392** [comment] 2016-09-23 02:12
got the same issue here

**Comment by dirkdevriendt** [comment] 2016-09-26 16:07
Same symptoms here on rancher v1.1.3

Tip: We've had this before and then it was related to two containers being started together in one stack with the same volume definition that did not exist yet. This caused the creation of two volumes with the same name and subsequent failure because of the ambiguity between the two. Deleting one of the two identically named volumes solved the issue.

In this case, however, we only have one pre-existing volume with the correct name.

Further (possibly unrelated) observation: although the volumes are labeled "Inactive" or have only one or two Mounts displayed on the Infrastructure\Storage page, many (as in 10+) purged containers are shown on the "Shared with" tab for the container(s) using the volume. It seems some connections are not being cleaned up correctly.

This issue was solved for us by starting the stack/containers with the driver entry removed and just using the volume definitions. This seems to indicate the volume driver attempts to create a new volume instead of using the existing one. (If that is by design, it contradicts the documentation at http://docs.rancher.com/rancher/v1.2/en/rancher-services/storage-service/)

HTH

**Comment by aemneina** [comment] 2016-11-08 04:09
@dirkdevriendt thanks for the troubleshooting tips! I'll close this out.

**Closed by aemneina** 2016-11-08 04:09 UTC
Labels: kind/question
