### ISSUE TITLE
[RFE] Add new "Status" field

### ISSUE THREAD

**Issue by samjustus** [rancher/rancher#42217] opened 2023-07-25 17:43 UTC
related to Global Roles v2

SURE-6202

**Comment by MbolotSuse** [comment] 2023-09-21 14:31
## Basic Requirements

- A new field should be added on the GlobalRole [type](https://github.com/rancher/rancher/blob/b74a73ce418ba74aec4f15d835fa64d7ca8851d9/pkg/apis/management.cattle.io/v3/authz_types.go#L143) called Status
- This field should have the type `GlobalRoleStatus`, which is a complex type having the following fields:
  - `LastUpdate` a timestamp, indicating the last time that the status was updated
  - `Summary` a string, one of `Complete`, `InProgress`, or `Error`
  - `Conditions` a slice of [Condition](https://github.com/kubernetes/apimachinery/blob/77401902abdff140aad8d3369ea748f68aaa5810/pkg/apis/meta/v1/types.go#L1432-L1492), indicating the status of specific backing RBAC objects. One condition should be made for each ClusterRole or Role being created for this object
- `Summary` should be marked as complete only when all desired objects have fully rolled out

**Comment by tomleb** [comment] 2023-11-17 19:12
What kind of guarantees do we want to have with this status field?

For example, should the status revert to `InProgress` when a related `ClusterRole` is modified? And if so, how quick do we want it to be moved to `InProgress`?

Also, should the status revert to `InProgress` if a child of an `.inheritedClusterRoles` is modified? What if it is the `ClusterRole` of a child in `.inheritedClusterRoles` [1]? And the same question applies, how quick do we want it to change to `InProgress`?[2]

[1] IMO it would suck if updating the `.inheritedClusterRoles` field of a `GlobalRole` would not change its status. It seems pretty important, especially for test robustness. (eg: avoiding flaky tests when updating this field for example)

[2] That seems pretty important too for the same reason as above. Consider the scenario with a GlobalRole that is already `Complete` . If takes too long for the cache to be populated + the change to be enqueued + the controller to work on the change such that it doesn't yet update the status to `InProgress`, then the tests (as example) could falsely believe that the GlobalRole is complete.

I do realize that the `LastUpdate` timestamp can help somewhat here, but that's not a fullproof solution either because what if you have the following:

```yaml
apiVersion: management.cattle.io/v3
kind: GlobalRole
metadata:
  ...
inheritedClusterRoles:
- roleA
- roleB
status:
  lastUpdated: time T
```

and your test updates both roleA and roleB. Even if the timestamps is now time T+1, the controller might only have processed the change of roleA, but not yet roleB, so you might falsely think the role is `Complete` when it's really not.

Thoughts?

**Comment by JonCrowther** [comment] 2024-02-07 20:46
# QA Validation

## Root Cause
When attempting to automate GlobalRoles, there is currently no method of knowing when the GlobalRole has successfully created all the backing Roles and ClusterRole. If an immediate next step was to check for or use the backing resources, it might fail. The only way around it would be to perform a wait and hoping it was adequately long enough. Similarly, updating a GlobalRole might require changes to the backing resources and there's no way to identify if those changes have taken place. 

## What was fixed, or what change has occurred
Added a new Status field to GlobalRoles. It contains the following fields:

- `Conditions`: essentially a status for each backing resource. If there are any errors attempting to create the backing resource they are specified here.
- `LastUpdate`: timestamp of the last update that changed the GlobalRole
- `Summary`: A string to indicate the overall status of the GlobalRole. Can be InProgress, Complete or Error

Any time a GlobalRole is created or updated, the status summary is set to InProgress until all the conditions (backing resources) are checked. Then, if all conditions are successful, the summary is set to Complete. If any condition is not met, it is set to Error.

Now automation or integration tests could wait until they see `Complete` before attempting to use the GlobalRole.

## Areas or cases that should be tested

Since this is exclusively additive and doesn't change the GlobalRoles, the existing behaviour of GlobalRoles should remain unchanged. Running any existing GlobalRole/GlobalRoleBinding tests would cover any possible regressions.

## What areas could experience regressions
Since this is a new field, I think the most important test is the upgrade scenario. What happens to GlobalRoles that didn't have a status now that this field exists. In my tests, it successfully adds them and populated the status, but this is probably the most likely area to experience issues.


## Are the repro steps accurate/minimal

So there are 3 possible status summaries. `Complete` is easy to test. All the default GlobalRoles should reach this state very quickly after starting Rancher.

`Error` occurs whenever a backing resource can't be created. One of the easiest to see is to create a GlobalRole with a `namespacedRules` that specifies a namespace that does not exist yet. Something like:

```
apiVersion: management.cattle.io/v3
kind: GlobalRole
metadata:
  namespace: default
  name: test-gr
namespacedRules:
  test-namespace:
    - apiGroups:
      - catalog.cattle.io
      resources:
      - apps
      verbs:
      - edit
```
This will create `test-gr` but the status summary will be `Error` because it can't make the Role in the specified namespace.

Seeing the `InProgress` status may be difficult as the reconcile happens very quickly. The test can be done either by automation that calls "get" on the global role and watches the status. To do so manually:

1. Create or pick a GlobalRole to test. I'll call mine `test-gr`
2. Do `kubectl get globalrole test-gr -w -oyaml` which will show the updates as they happen
3. In another terminal, modify the rules of `test-gr`
4. See that the status changes in the terminal that is watching

**Comment by anupama2501** [comment] 2024-07-08 23:50
Validated the following test cases on v2.9-head `1c2b815c` and on an upgrade from 2.8.5 to 2.9-head `1c2b815c`

Test | Status | Comments
-- | -- | --
Create a global role and verify the status is Completed | PASS | 
Create Global role with inherited cluster roles and verify the status is Completed | | No status field for inherited cluster roles
Create Global role with namespaced rules and verify the status is Completed | PASS | 
Create a global role and have status field in error | PASS | Create a namespaced rule without the namespace
Verify the status field summary updated to completed once the error is resolved | PASS | 
Verify kubectl get roles shows the status Error for errored namespaces | PASS | 
Create global role and verify lastUpdatedTime | PASS | Updated with the latest timestamp for when the global role is created.
Create global role and update backing cluster role and verify status.conditions.lastUpdatedTime | FAIL | lastUpdateTime and lastTransitionTime are the same https://github.com/rancher/rancher/issues/46065
Delete the backing cluster role from global role and verify lastTransitionTime | FAIL | https://github.com/rancher/rancher/issues/46065
Create a namespacedrule without the namespace and verify status.conditions.lastTransitionTime is updated on an update | PASS | 
Create global role with 2 namespaces and verify status update on both | PASS | 
Create global role pre upgrade and verify the fields post upgrade | PASS | 
Verify the built in roles have status fields | PASS | 
Verify that 'k explain globalroles' includes information about the new field Status | PASS | 
Verify that 'k describe globalroles <globalrole>' includes information about Status | PASS | 
Verify the terminating state for the global role | PASS | Added a finalizer and verified the status is in terminating when deleting the global role. 
Verify in progress state for the global role | PASS | ran the command `kubectl get globalrole test-gr -w -oyaml`  and the status is in progress when the global role is updated

**Comment by anupama2501** [comment] 2024-07-08 23:51
Closing as individual tickets were filed for the Failed cases.

**Closed by anupama2501** 2024-07-08 23:51 UTC
Labels: kind/enhancement, priority/0, area/rbac, QA/M, JIRA, team/collie
