### ISSUE TITLE
Can't attach EBS volume to Kubernetes Pod

### ISSUE THREAD

**Issue by galal-hussein** [rancher/rancher#4444] opened 2016-04-16 15:22 UTC
Rancher Version:
1.0.0
Docker Version:
1.10.3
OS: 
ubuntu 14.04
Steps to Reproduce: 
- Bring up Kubernetes environment with Ec2 nodes with the right IAM Roles.
- Create a EBS volume.
- run the following example pod:
```
apiVersion: v1
kind: Pod
metadata:
  name: aws-web
spec:
  containers:
    - name: web
      image: nginx
      ports:
        - name: web
          containerPort: 80
          protocol: TCP
      volumeMounts:
        - name: html-volume
          mountPath: "/usr/share/nginx/html"
  nodeSelector:
    provider: aws
  volumes:
    - name: html-volume
      awsElasticBlockStore:
        # Enter the volume ID below
        volumeID: vol-xxxxxxx
        fsType: ext4
```
Results: 

I can see that the ebs volume state changed from "available" to "in use", and the ebs attached to the node:

```
root@ip-172-31-34-61:~# lsblk
NAME    MAJ:MIN   RM SIZE RO TYPE MOUNTPOINT
xvda    202:0      0   8G  0 disk 
└─xvda1 202:1      0   8G  0 part /
xvdba   202:13312  0   1G  0 disk
```

However the pod is failing to attach this volume, and it timesout eventaully with the following error:

```
W0416 14:59:40.106600    9311 aws_util.go:188] Retrying attach for EBS Disk "vol-50c051a2" (retry count=1).
W0416 14:59:40.172026    9311 aws.go:1043] Got assignment call for already-assigned volume: ba@vol-50c051a2
E0416 14:59:40.220624    9311 aws.go:1081] endAttaching on non-allocated device
W0416 15:00:40.242804    9311 aws_util.go:188] Retrying attach for EBS Disk "vol-50c051a2" (retry count=2).
W0416 15:00:40.298752    9311 aws.go:1043] Got assignment call for already-assigned volume: ba@vol-50c051a2
E0416 15:00:40.345513    9311 aws.go:1081] endAttaching on non-allocated device
W0416 15:01:40.369875    9311 aws_util.go:188] Retrying attach for EBS Disk "vol-50c051a2" (retry count=3).
W0416 15:01:40.469950    9311 aws.go:1043] Got assignment call for already-assigned volume: ba@vol-50c051a2
E0416 15:01:40.561267    9311 aws.go:1081] endAttaching on non-allocated device
W0416 15:02:40.583890    9311 aws_util.go:188] Retrying attach for EBS Disk "vol-50c051a2" (retry count=4).
W0416 15:02:40.655696    9311 aws.go:1043] Got assignment call for already-assigned volume: ba@vol-50c051a2
E0416 15:02:40.705906    9311 aws.go:1081] endAttaching on non-allocated device
W0416 15:03:40.719445    9311 aws_util.go:188] Retrying attach for EBS Disk "vol-50c051a2" (retry count=5).
W0416 15:03:40.786377    9311 aws.go:1043] Got assignment call for already-assigned volume: ba@vol-50c051a2
E0416 15:03:40.842550    9311 aws.go:1081] endAttaching on non-allocated device
W0416 15:04:40.859516    9311 aws_util.go:188] Retrying attach for EBS Disk "vol-50c051a2" (retry count=6).
W0416 15:04:40.951587    9311 aws.go:1043] Got assignment call for already-assigned volume: ba@vol-50c051a2
E0416 15:04:41.032547    9311 aws.go:1081] endAttaching on non-allocated device
W0416 15:05:41.049700    9311 aws_util.go:188] Retrying attach for EBS Disk "vol-50c051a2" (retry count=7).
W0416 15:05:41.146346    9311 aws.go:1043] Got assignment call for already-assigned volume: ba@vol-50c051a2
E0416 15:05:41.199353    9311 aws.go:1081] endAttaching on non-allocated device
W0416 15:06:41.221202    9311 aws_util.go:188] Retrying attach for EBS Disk "vol-50c051a2" (retry count=8).
W0416 15:06:41.312315    9311 aws.go:1043] Got assignment call for already-assigned volume: ba@vol-50c051a2
E0416 15:06:41.372385    9311 aws.go:1081] endAttaching on non-allocated device
W0416 15:07:41.391021    9311 aws_util.go:188] Retrying attach for EBS Disk "vol-50c051a2" (retry count=9).
W0416 15:07:41.444161    9311 aws.go:1043] Got assignment call for already-assigned volume: ba@vol-50c051a2
E0416 15:07:41.517877    9311 aws.go:1081] endAttaching on non-allocated device
E0416 15:08:41.538217    9311 kubelet.go:1780] Unable to mount volumes for pod "aws-web_default(afbfb9d2-03e3-11e6-8987-02b8430c7340)": Could not attach EBS Disk "vol-50c051a2". Timeout waiting for mount paths to be created.; skipping pod
E0416 15:08:41.538243    9311 pod_workers.go:138] Error syncing pod afbfb9d2-03e3-11e6-8987-02b8430c7340, skipping: Could not attach EBS Disk "vol-50c051a2". Timeout waiting for mount paths to be created.
I0416 15:08:52.991458    9311 aws.go:546] Zone not specified in configuration file; querying AWS metadata service
E0416 15:08:53.104615    9311 aws.go:676] Tag "KubernetesCluster" not found; Kuberentes may behave unexpectedly.
I0416 15:08:53.104697    9311 aws.go:683] AWS cloud - no tag filtering
```

Expected:

The pod should be running and the disk attached successfully.

**Comment by alena1108** [comment] 2016-04-20 19:46
Added more logging to kubelet code, and here is the root cause for the problem.Steps kubelet performs to create a pod with PV volume:

1) mount EBS volume to EC2 host
2) start POD container with the volume attached

And in Rancher setup step 1) fails. Although EBS volume gets mounted to the host successfully under /dev/xvdba:
=====================================
ubuntu@ip-172-31-43-197:~$ lsblk

NAME    MAJ:MIN   RM SIZE RO TYPE MOUNTPOINT
xvda    202:0      0   8G  0 disk
└─xvda1 202:1      0   8G  0 part /
xvdba   202:13312  0   1G  0 disk // EBS volume

but kubelet can't verify the path as it doesn't see changes to host's /dev directory:
=====================================
I0420 06:34:22.457947    2064 aws_util.go:199] Device path /dev/xvdba
I0420 06:34:22.459348    2064 aws_util.go:330] getDiskByIdPaths: Device path /dev/xvdba
I0420 06:34:22.459441    2064 aws_util.go:229] Verifying device path /dev/xvdba
I0420 06:34:22.459472    2064 aws_util.go:345] Checking if path exists: checking path /dev/xvdba
I0420 06:34:22.459558    2064 aws_util.go:350] Checking if path exists: path doesn't exist /dev/xvdba

Only after kubelet is restarted, it picks all the changes from /dev, attaches the volume and bind mounts it successfully to the pod's container:
=====================================
I0420 07:26:34.295013   23493 aws_util.go:199] Device path /dev/xvdba
I0420 07:26:34.295052   23493 aws_util.go:330] getDiskByIdPaths: Device path /dev/xvdba
I0420 07:26:34.295067   23493 aws_util.go:229] Verifying device path /dev/xvdba
I0420 07:26:34.295079   23493 aws_util.go:345] Checking if path exists: checking path /dev/xvdba
I0420 07:26:34.295121   23493 aws_util.go:210] Successfully attached EBS Disk "vol-05589bb3".


The fix would be: find a way for kubelet container to get /dev directory changes.

**Comment by lyoungblood** [comment] 2016-05-22 22:31
I'm currently blocked by this - which rancher server tag should I grab from the repository to get the fix?

**Comment by deniseschannon** [comment] 2016-05-23 17:22
@lyoungblood This is not yet in a release, but will be made available for our v1.1 release. When this issue is closed, it will be available in whatever the next release available.

**Comment by lyoungblood** [comment] 2016-05-24 02:31
@deniseschannon Thanks!  And thank you to everyone at Rancher for making such an amazing product.

**Comment by alena1108** [comment] 2016-05-26 17:43
@soumyalj to test the fix, you would have to:

1) Use ```rancher/k8s:v1.2.4-rancher-1``` image for all services using rancher/k8s image
2) Have rancher server, and add AWS host to it as a custom host. When create an instance on amazon, pick:

- ubuntu with HVM
- IAM role: volumesRole // important
- securityGroup: all open

3) Make sure you have docker 1.10.3
4) Create volume on AWS - use the smallest size.
5) Create k8s pod using the volume. Here is the template example:

```
apiVersion: v1
kind: Pod
metadata:
  name: aws-web
spec:
  containers:
    - name: web
      image: nginx
      ports:
        - name: web
          containerPort: 80
          protocol: TCP
      volumeMounts:
        - name: html-volume

          mountPath: "/usr/share/nginx/html"
  volumes:
    - name: html-volume
      awsElasticBlockStore:
        # Enter the volume ID below

        volumeID: vol-f28df840  // id of the AWS volume
        fsType: ext4
```
Make sure the pod is created successfully.

6) Login to nginx container, write something to /usr/share/nginx/html.
7) either recreate the pod, or create a new pod using the same volume. Make sure that you see the modifications done to /usr/share/nginx/html 


@galal-hussein could you also test it for GCE volumes. The steps will be similar. But make sure EBS is validated first.

**Comment by galal-hussein** [comment] 2016-05-27 18:32
@alena1108 I failed to use ebs as persistent volume for pod, the setup was as follows:

t2.small machine as rancher server
ubuntu 14.04 hvm
docker 1.10.3
security group opened

t2.micro as a registered node
ubuntu 14.04 hvm
docker 1.10.3
security group opened for all incoming traffic
IAM role with access to full ebs access


I am getting the following error when i started the pod:

```
kubectl describe pods
Name:		aws-web
Namespace:	default
Node:		ip-172-31-42-217/52.19.4.135
Start Time:	Fri, 27 May 2016 20:07:14 +0200
Labels:		<none>
Status:		Pending
IP:		
Controllers:	<none>
Containers:
  web:
    Container ID:	
    Image:		nginx
    Image ID:		
    Port:		80/TCP
    QoS Tier:
      memory:		BestEffort
      cpu:		BestEffort
    State:		Waiting
      Reason:		ContainerCreating
    Ready:		False
    Restart Count:	0
    Environment Variables:
Conditions:
  Type		Status
  Ready 	False 
Volumes:
  html-volume:
    Type:	AWSElasticBlockStore (a Persistent Disk resource in AWS)
    VolumeID:	vol-825d7370
    FSType:	ext4
    Partition:	0
    ReadOnly:	false
Events:
  FirstSeen	LastSeen	Count	From				SubobjectPath	Type		Reason		Message
  ---------	--------	-----	----				-------------	--------	------		-------
  52s		52s		1	{default-scheduler }				Normal		Scheduled	Successfully assigned aws-web to ip-172-31-42-217
  2s		2s		1	{kubelet ip-172-31-42-217}			Warning		FailedMount	Unable to mount volumes for pod "aws-web_default(d77a3a0e-2435-11e6-8fcd-02f6322758e6)": Could not attach EBS Disk "vol-825d7370". Timeout waiting for mount paths to be created.
  2s		2s		1	{kubelet ip-172-31-42-217}			Warning		FailedSync	Error syncing pod, skipping: Could not attach EBS Disk "vol-825d7370". Timeout waiting for mount paths to be created.
```
I am using rancher/k8s:v1.2.4-rancher1 image for all services.

**Comment by alena1108** [comment] 2016-05-27 18:36
@galal-hussein wonder if there were any changes in k8s 1.2.4 causing this to fail as i've debugged/fixed/tested it for 1.2.0. Will debug and update the bug

**Comment by alena1108** [comment] 2016-05-27 18:52
@galal-hussein confirmed: k8s added extra check to validate a provider type in 1.2.4. As in our case cloudProvider is Rancher, not AWS, you would hit this error on kubelet:

```
Error getting AWSCloudProvider while detaching PD "vol-8790d231": Failed to get AWS Cloud Provider. plugin.host.GetCloudProvider returned &{0xc2085cc000 0xc208557b00} instead
```
I am going to revert this particular commit on k8s rancher branch, and will update you with the new image to test the fix

**Comment by alena1108** [comment] 2016-05-27 19:27
@galal-hussein please test using image ```alena1108/k8s:v1.2.4-rancher1```

**Comment by galal-hussein** [comment] 2016-05-27 20:17
@alena1108 The test worked on ```alena1108/k8s:v1.2.4-rancher1``` and the ebs volume mounted inside the pod:

```
root@ip-172-31-38-249:~# lsblk
NAME    MAJ:MIN   RM SIZE RO TYPE MOUNTPOINT
xvda    202:0      0   8G  0 disk 
└─xvda1 202:1      0   8G  0 part /
xvdba   202:13312  0   1G  0 disk /var/lib/kubelet/plugins/kubernetes.io/aws-ebs/mounts/vol-d8f2dc2a
```

**Comment by galal-hussein** [comment] 2016-05-27 23:50
@alena1108 The test worked on GCE too.

**Comment by alena1108** [comment] 2016-05-28 00:10
@galal-hussein awesome, thanks for testing it. Closing the issue

**Comment by alena1108** [comment] 2016-05-28 00:13
Tested with dev2 Rancher and alena1108/k8s:v1.2.4-rancher1k8s image

**Closed** 2016-05-28 00:12 UTC
Labels: area/kubernetes, kind/bug, status/resolved, status/to-test

**Comment by Dmitry1987** [comment] 2016-12-10 14:07
Hi @alena1108 , I have the same issue with AWS EBS volumes not getting created, and your example pod with 'already existent' volume also didn't work.  I did use IAM role that allows needed EC2 actions. Getting this errors during creation:

```kubectl describe pod aws-web
Name:           aws-web
Namespace:      default
Node:           ip-172-31-29-106.us-west-2.compute.internal/172.31.29.106
Start Time:     Sat, 10 Dec 2016 13:55:42 +0000
Labels:         <none>
Status:         Pending
IP:
Controllers:    <none>
Containers:
  web:
    Container ID:
    Image:              nginx
    Image ID:
    Port:               80/TCP
    State:              Waiting
      Reason:           ContainerCreating
    Ready:              False
    Restart Count:      0
    Volume Mounts:
      /usr/share/nginx/html from html-volume (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-fpf8x (ro)
    Environment Variables:      <none>
Conditions:
  Type          Status
  Initialized   True
  Ready         False
  PodScheduled  True
Volumes:
  html-volume:
    Type:       AWSElasticBlockStore (a Persistent Disk resource in AWS)
    VolumeID:   vol-1d115195
    FSType:     ext4
    Partition:  0
    ReadOnly:   false
  default-token-fpf8x:
    Type:       Secret (a volume populated by a Secret)
    SecretName: default-token-fpf8x
QoS Class:      BestEffort
Tolerations:    <none>
Events:
  FirstSeen     LastSeen        Count   From                                                    SubobjectPath   Type             Reason          Message
  ---------     --------        -----   ----                                                    -------------   -------- ------          -------
  13s           13s             1       {default-scheduler }                                                    Normal           Scheduled       Successfully assigned aws-web to ip-172-31-29-106.us-west-2.compute.internal
  13s           5s              5       {kubelet ip-172-31-29-106.us-west-2.compute.internal}                   Warning          FailedMount     MountVolume.SetUp failed for volume "kubernetes.io/aws-ebs/570a6403-bee0-11e6-87c1-2e1fa97c7333-html-volume" (spec.Name: "html-volume") pod "570a6403-bee0-11e6-87c1-2e1fa97c7333" (UID: "570a6403-bee0-11e6-87c1-2e1fa97c7333") with: mount failed: exit status 32
Mounting arguments: /var/lib/kubelet/plugins/kubernetes.io/aws-ebs/mounts/vol-1d115195 /var/lib/kubelet/pods/570a6403-bee0-11e6-87c1-2e1fa97c7333/volumes/kubernetes.io~aws-ebs/html-volume  [bind]
Output: mount: special device /var/lib/kubelet/plugins/kubernetes.io/aws-ebs/mounts/vol-1d115195 does not exist
```

How do I verify my K8s installed through Rancher is able to see AWS volumes?   I think it's some kind of K8s installation issue, because it looks for some kubelet plugins (in error output).
Please advice how to solve this? 

Thanks in advance :)

**Comment by emk** [comment] 2017-01-10 21:43
I'm quite impressed with Pachyderm so far, but I'm still seeing this issue under Rancher 1.3.0. Versions:

> kubectl version
> Client Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.1", GitCommit:"82450d03cb057bab0950214ef122b67c83fb11df", GitTreeState:"clean", BuildDate:"2016-12-14T00:57:05Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"linux/amd64" }
> Server Version: version.Info{Major:"1", Minor:"5+", GitVersion:"v1.5.1-rancher1", GitCommit:"24adf52d6f18be9071dc3194b4dca4a0d4e35bb9", GitTreeState:"clean", BuildDate:"2016-12-15T05:28:48Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"linux/amd64"}

The manifest is taken from the original #4444 bug report. The error is (all "xxxxxxxx" bits were originally AWS IDs):

> MountVolume.SetUp failed for volume "kubernetes.io/aws-ebs/adc7c136-d77a-11e6-978a-b6d2eaf5775b-html-volume" (spec.Name: "html-volume") pod "adc7c136-d77a-11e6-978a-b6d2eaf5775b" (UID: "adc7c136-d77a-11e6-978a-b6d2eaf5775b") with: mount failed: exit status 32 Mounting command: mount Mounting arguments: /var/lib/kubelet/plugins/kubernetes.io/aws-ebs/mounts/vol-xxxxxxxxxxxxxxxx /var/lib/kubelet/pods/adc7c136-d77a-11e6-978a-b6d2eaf5775b/volumes/kubernetes.io~aws-ebs/html-volume [bind] Output: mount: special device /var/lib/kubelet/plugins/kubernetes.io/aws-ebs/mounts/vol-xxxxxxxxxxxxxxxx does not exist

I've tried granting the kubernetes nodes both these privileges:

```json
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Effect": "Allow",
      "Action": [
        "ec2:AttachVolume",
        "ec2:DetachVolume"
      ],
      "Resource": "arn:aws:ec2:us-east-1:xxxxxxxxxxxx:instance/*"
    },
    {
      "Effect": "Allow",
      "Action": [
        "ec2:AttachVolume",
        "ec2:DetachVolume"
      ],
      "Resource": "arn:aws:ec2:us-east-1:xxxxxxxxxxxx:volume/*"
    }
  ]
}
```

...and also these:

```json
 {
  "Version": "2012-10-17",
  "Statement": [
    {
      "Action": "ec2:*",
      "Effect": "Allow",
      "Resource": "*"
    },
    {
      "Effect": "Allow",
      "Action": "elasticloadbalancing:*",
      "Resource": "*"
    },
    {
      "Effect": "Allow",
      "Action": "cloudwatch:*",
      "Resource": "*"
    },
    {
      "Effect": "Allow",
      "Action": "autoscaling:*",
      "Resource": "*"
    }
  ]
}
```

Thank you for any advice you can provide!

CC @alena1108 @seamusabshere

**Comment by emk** [comment] 2017-01-17 23:09
If you're still seeing this bug in modern Rancher, see https://github.com/rancher/rancher/issues/7370#issuecomment-273325303 for the fix which worked for me. CC @Dmitry1987
