### ISSUE TITLE
[rke2] unable to create an rke2 cluster with more than 1 node

### ISSUE THREAD

**Issue by slickwarren** [rancher/rancher#37272] opened 2022-04-12 01:17 UTC
**Rancher Server Setup**
- Rancher version: v2.6-head (b44d54a)
- Installation option (Docker install/Helm Chart): docker
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): n/a
- Proxy/Cert Details: n/a

**Information about the Cluster**
- Kubernetes version: 1.22.7, 1.21.11 rke2
- Cluster Type (Local/Downstream): downstream
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider): aws

**User Information**
- What is the role of the user logged in? (Admin/Cluster Owner/Cluster Member/Project Owner/Project Member/Custom): admin

   
**Describe the bug**
user is unable to provision a downstream cluster with multiple nodes, specifically dedicated nodes per role. 

**To Reproduce**
* deploy an rke2 cluster with 1 node per role (tested with k8s 1.22, 1.21)

**Result**
etcd node is stuck in `waiting for plan to be applied`, cluster never gets to an active state

**Expected Result**
cluster should register all nodes and get to an active state

**Screenshots**
<img width="624" alt="Screen Shot 2022-04-11 at 6 15 53 PM" src="https://user-images.githubusercontent.com/16691014/162859178-1c8b84e8-a4d9-4acd-9b6b-a3617866f3c6.png">

**Comment by timhaneunsoo** [comment] 2022-04-12 16:40
Closing this issue as a duplicate of [36939](https://github.com/rancher/rancher/issues/36939)

**Closed** 2022-04-12 16:40 UTC
Labels: kind/bug-qa, area/provisioning-rke2
