### ISSUE TITLE
rancher every 6 hours rise many connections

### ISSUE THREAD

**Issue by qixd111** [rancher/rancher#30785] opened 2021-01-12 03:20 UTC
_*Describe_ your issue here*
what these?
tcp    ESTAB      0      0      127.0.0.1:57098              127.0.0.1:443                
tcp    ESTAB      0      0      127.0.0.1:51718              127.0.0.1:443                
tcp    ESTAB      0      0      127.0.0.1:51712              127.0.0.1:443                
tcp    ESTAB      0      0      127.0.0.1:51782              127.0.0.1:443                
tcp    ESTAB      0      0      127.0.0.1:57036              127.0.0.1:443                
tcp    ESTAB      0      0      127.0.0.1:51744              127.0.0.1:443                
tcp    ESTAB      0      0      127.0.0.1:57058              127.0.0.1:443                
tcp    ESTAB      0      0      127.0.0.1:51770              127.0.0.1:443                
tcp    ESTAB      0      0      127.0.0.1:51760              127.0.0.1:443                
tcp    ESTAB      0      0      127.0.0.1:46796              127.0.0.1:443                
tcp    ESTAB      0      0      127.0.0.1:57062              127.0.0.1:443                
tcp    ESTAB      0      0      127.0.0.1:57042              127.0.0.1:443                
tcp    ESTAB      0      0      127.0.0.1:46778              127.0.0.1:443                
tcp    ESTAB      0      0      127.0.0.1:57106              127.0.0.1:443                
tcp    ESTAB      0      0      127.0.0.1:57076              127.0.0.1:443                
tcp    ESTAB      0      0      127.0.0.1:46754              127.0.0.1:443                
tcp    ESTAB      0      0      127.0.0.1:46782              127.0.0.1:443                
tcp    ESTAB      0      0      127.0.0.1:57072              127.0.0.1:443                
tcp    ESTAB      0      0      127.0.0.1:51728              127.0.0.1:443                
tcp    ESTAB      0      0      127.0.0.1:46772              127.0.0.1:443                
tcp    ESTAB      0      0      127.0.0.1:51756              127.0.0.1:443                
tcp    ESTAB      0      0      127.0.0.1:51734              127.0.0.1:443                
tcp    ESTAB      0      0      127.0.0.1:46732              127.0.0.1:443                
tcp    ESTAB      0      0      127.0.0.1:57086              127.0.0.1:443                
tcp    ESTAB      0      0      127.0.0.1:46758              127.0.0.1:443                
tcp    ESTAB      0      0      127.0.0.1:51924              127.0.0.1:443                
tcp    ESTAB      0      0      127.0.0.1:57046              127.0.0.1:443                
tcp    ESTAB      0      0      127.0.0.1:46768              127.0.0.1:443      

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v2.5.4` UI: `v2.5.4` |
|Route|`undefined`|

**Comment by qixd111** [comment] 2021-01-12 03:20
single docker deployed rancher

**Comment by qixd111** [comment] 2021-01-12 03:21
how to solve it?

**Comment by superseb** [comment] 2021-01-12 07:45
Probably a duplicate of https://github.com/rancher/rancher/issues/28360, workaround is to disable telemetry.

**Closed by superseb** 2021-01-12 07:45 UTC
