### ISSUE TITLE
Load Balancer upgrade resets Host IP

### ISSUE THREAD

**Issue by kirrmann** [rancher/rancher#7492] opened 2017-01-20 17:13 UTC
If I upgrade a load balancer, all the values for port rules are copied into to the corresponding input fields, but "Host IP" is hidden and reset.

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v1.3.2` Cattle: `v0.175.8` UI: `v1.3.5` |
|Access|`ldap` `admin`|
|Orchestration|`Cattle`|
|Route|`hosts.index`|

**Comment by tfiduccia** [comment] 2017-01-20 17:25
Duplicate of #7288

**Closed by tfiduccia** 2017-01-20 17:25 UTC
