### ISSUE TITLE
Restrict custom catalog name to have no spaces

### ISSUE THREAD

**Issue by vegasbrianc** [rancher/rancher#4243] opened 2016-03-31 08:57 UTC
Adding a custom catalog with a space in the name (which is not best practice in Key Value Pairs but has happened with one of our users) makes the catalog work sporadically. That means either the images from the catalog don't appear or the catalog item is not available when opening an item.

Images missing
<img width="553" alt="screen shot 2016-03-31 at 10 56 31" src="https://cloud.githubusercontent.com/assets/674790/14170690/4cb6cfa6-f72f-11e5-95f5-c2508a5f6443.png">

Opening Catalog Item
<img width="407" alt="screen shot 2016-03-31 at 10 56 36" src="https://cloud.githubusercontent.com/assets/674790/14170689/4c8c215c-f72f-11e5-8574-f6569d42b96e.png">

Removing the space from the catalog name resolves this issue. However, it would be useful to either support spaces in names or restrict the field to have no spaces allowed.

<img width="1224" alt="screen shot 2016-03-31 at 10 49 20" src="https://cloud.githubusercontent.com/assets/674790/14170602/ed48b1a6-f72e-11e5-80c4-32ac7e2d7ff2.png">

---
|Versions|Rancher `v1.0.0` Cattle: `v0.159.2` UI: `v0.100.3` |
|Access|`localauth` `admin`|

**Comment by deniseschannon** [comment] 2016-03-31 17:12
Duplicate of https://github.com/rancher/rancher/issues/3124

**Comment by deniseschannon** [comment] 2016-03-31 17:12
We will actually be allowing a space in the catalog name.

**Closed by deniseschannon** 2016-03-31 17:12 UTC
