### ISSUE TITLE
Persistent Volume of Type NFS Share cannot be created with access mode "Many Nodes Read-Write" (aka ReadWriteMany / RWX)

### ISSUE THREAD

**Issue by Remigius2011** [rancher/rancher#13113] opened 2018-04-26 09:47 UTC
**Rancher versions:**
rancher/server or rancher/rancher: v2.0.0-beta4
rancher/agent or rancher/rancher-agent: v2.0.0-beta4

**Infrastructure Stack versions:**
healthcheck:
ipsec:
network-services:
scheduler:
kubernetes (if applicable): v1.10.1-rancher2

**Docker version: (`docker version`,`docker info` preferred)** 17.03.2-ce

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)** ubuntu 16.04.04 4.4.0-119-generic

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)** VMWare Workstation 14 Pro 14.1.1 build-7528167

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)** single node rancher / single node k8s cluster

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**

**Steps to Reproduce:**

* add new persistent volume
* enter name "test"
* select volume plugin "NFS Share"
* enter valid data for path and server
* check only access mode "Many Nodes Read-Write"
* click "save"

**Results:**

The following error message appears:

"Validation failed in API: PersistentVolume "test" is invalid: spec.accessModes: Required value"

**Comment by Remigius2011** [comment] 2018-04-26 14:26
Follow-Up: Sometimes it seems to work (e.g. after logout / login). Also, creating a PVC under Volumes fails when only "Many Nodes Read-Write" is checked.

**Comment by tfiduccia** [comment] 2018-04-30 22:43
@Remigius2011 - I believed we have fixed this in the latest rancher/rancher:master.  If you see this problem in our next release, please reopen.

**Comment by nathanweeks** [comment] 2018-05-03 16:17
I'm also seeing the same error in rancher/rancher:2.0.0

**Comment by Remigius2011** [comment] 2018-05-04 08:12
@tfiduccia exactly (and see also my instructions), if you select another mode, it will not complain, as another mode satisfies the validation requirements and you will only notice a problem when you try to create a claim with RWX.

**Comment by tfiduccia** [comment] 2018-05-08 19:49
Version - 2.0 master 5/8
Verified fixed

@Remigius2011 & @nathanweeks - The issue is fixed in our latest master build and will be going into the 2.0.1 build.

**Closed by tfiduccia** 2018-05-08 19:49 UTC
Labels: area/storage, area/ui, kind/bug, status/resolved, status/to-test, version/2.0

**Comment by Remigius2011** [comment] 2018-05-19 09:36
I can confirm it is working in v2.0.1-rc4 / k8s v1.10.1. I can creeate a volume and an RWX volume claim and access it from at least two pods (one read-only, the other writable).
