### ISSUE TITLE
enhancement: login into host from UI

### ISSUE THREAD

**Issue by kkvilekval** [rancher/rancher#5109] opened 2016-06-14 02:07 UTC
**Rancher Version:**
V 1.1.0-dev3

**Docker Version:**
docker 10.3

**OS and where are the hosts located? (cloud, bare metal, etc):**
AWS ubuntu

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
internal DB using mounted host volume

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**

**Steps to Reproduce:**
None:

**Results:** 
Open a terminal window to the underlying on host.. similar to a window to a container.
Currently I download the machine config to a local node and find the id_rsa and ssh directly in to lookaround and fix issues.  Having the ability to login directly from the UI would be cool.
 

**Expected:**

**Comment by deniseschannon** [comment] 2016-06-14 02:52
Duplicate of https://github.com/rancher/rancher/issues/2184

**Closed by deniseschannon** 2016-06-14 02:52 UTC
