### ISSUE TITLE
v2.3.3 SAML groups with Keycloak doesn't work anymore

### ISSUE THREAD

**Issue by eumel8** [rancher/rancher#24556] opened 2019-12-12 15:18 UTC
After upgrading from Rancher 2.3.2 to 2.3.3 fetching groups from Keycloak doesn't work anymore. Also a fresh installation of Rancher 2.3.3 has the same result.

**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
Setup Keycloak SAML auth
Setup username, uid, group field and rancher url
Setup XML file from Keycloak
Setup cert+key

**Result:**
Connection is sucessfull. If I choose  "Allow members of Clusters, Projects, plus Authorized Users and Organizations" only the current user is available in the menu. no groups anymore

**Other details that may be helpful:**
worked till 2.3.2 :-)

**Environment information**
- Rancher v2.3.3
- Keycloak 5.0.0
- Ubuntu 16.04
- Installation option (single install/HA): both

**Comment by Tejeev** [comment] 2019-12-13 19:56
Ive recreated by deploying two clusters side by side (2.3.2 and 2.3.3), adding our Keycloak server, and logging in with synched users.  On the 2.3.3 cluster, when I go to a downstream cluster and choose to add a member, none of the groups available in the 2.3.2 cluster despite all configurations being parallel.
I've tried moving users in groups and logging in with different users.  I can log in with any user that should authenticate but I can't add them to the clusters.

**Comment by sangeethah** [comment] 2019-12-13 21:48
@Tejeev We have this related  issue fixed in https://github.com/rancher/rancher/issues/24437 . Could you please see if the issue is fixed when testing  with `v2.3.4-rc3` ?

**Comment by eumel8** [comment] 2019-12-14 05:30
works for me, thx

**Comment by sangeethah** [comment] 2019-12-14 06:28
Thank you for confirming @eumel8

**Closed** 2019-12-14 06:28 UTC
Labels: area/authentication, kind/bug
