### ISSUE TITLE
[BUG] [2.5]Rancher API Audit Log fails to capture API calls at Audit Level 3

### ISSUE THREAD

**Issue by samjustus** [rancher/rancher#38345] opened 2022-07-20 15:04 UTC
Backport rancher/rancher#38323

**Comment by KevinJoiner** [comment] 2022-09-26 16:13
## Root Cause
When Audit Level is set to level 3, Rancher attempts to add the response body to the audit message. Rancher then prints the compacted JSON. This audit message would fail if the response body was composed of compressed data since no decompression was performed before attempting to create a valid JSON. The error for this audit message failure was ignored, so the user had no indication of what went wrong.

## What fix or change occurred
The audit logger now checks the content-encoding of the response message to determine if the data is compressed. Audit logger then attempts to decompress this data and append it to the log message.
The audit logger will also log errors that occur during audit writes in Rancher.

## Areas or cases that should be tested.
***While testing, we will have to search the auidtLog for messages, this can be difficult because there are a lot of messages***
***One method is to grep the log file for the action you are looking for example `tail -f /var/log/auditlog/rancher-api-audit.log | grep nginx` will get only log messages that include nginx*** 

1. Start a new rancher cluster with API auditing level 3 enabled
    - via helm `--set auditLog.level=3` 
    - via docker `--env AUDIT_LEVEL=3`
2. Create a new deployment in the local cluster.
3. Verify that the request for the deployment was recorded in the audit log.
   - HA: `kubectl logs -n cattle-system -f rancher-<gen_name> rancher-audit-log`
   - docker: run `cat /var/log/auditlog/rancher-api-audit.log` in docker container.

## What areas could experience regressions
Verify that other audit levels still work as they did before. 

#### Audit level 2 test
1. Start a new rancher cluster with API auditing level 2 enabled
    - via helm `--set auditLog.level=2` 
    - via docker env `AUDIT_LEVEL=2`
2. Create a new deployment in the local cluster (nginx:latest) through the UI. 

3. Verify that the request for the deployment was recorded in the audit log without a `responseBody` section.
   - HA: `kubectl logs -n cattle-system -f rancher-<gen_name> rancher-audit-log`
   - docker: run `cat /var/log/auditlog/rancher-api-audit.log` in docker container.

#### Audit level 1 test
1. Start a new rancher cluster with API auditing level 1 enabled
    - via helm `--set auditLog.level=1` 
    - via docker env `AUDIT_LEVEL=1`
2. Create a new deployment in the local cluster (nginx:latest) through the UI. 
3. Verify that the request for the deployment was recorded in the audit log without a `responseBody` and `requestBody` section.
   - HA: `kubectl logs -n cattle-system -f rancher-<gen_name> rancher-audit-log`
   - docker: run `cat /var/log/auditlog/rancher-api-audit.log` in docker container.

#### Audit level 0 test
1. Start a new rancher cluster with API auditing level 1 enabled
    - via helm `--set auditLog.level=0` 
    - via docker env `AUDIT_LEVEL=0`
2. Create a new deployment in the local cluster (nginx:latest) through the UI. 
3. Verify that there are no logs created.
   - HA: `kubectl describe -n cattle-system rancher` verify there is no sidecard pod in the deployment
   - docker: `ls /var/log/auditlog/rancher-api-audit.log` verify the log file was not created.

## Are the repro steps accurate/minimal?
Yes

**Comment by dasarinaidu** [comment] 2022-11-17 23:59
This issue is reproduced on v2.5.16

**Reproducible Steps:**

1. Provision a rancher (Set auditlogs set to 3)
      `helm : --set auditLog.level=1`
3. Create a downstream cluster (RKE1)
4. Create a Deployment
5. Check for the Audit logs
      `kubectl -n cattle-system logs -f rancher-5db44474cf-fvbbr rancher-audit-log`
7. Check for the POST call on creating a deployment
8. Delete the deployment
9. In audit logs check for the DELETE call on deleting a deployment

**Comment by dasarinaidu** [comment] 2022-11-29 21:57
Validated this ticket on v2.5.s1-head and all the test cases were working as expected and I am closing the ticket.

<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:////Users/sdasari/Library/Group%20Containers/UBF8T346G9.Office/TemporaryItems/msohtmlclip/clip.htm">
<link rel=File-List
href="file:////Users/sdasari/Library/Group%20Containers/UBF8T346G9.Office/TemporaryItems/msohtmlclip/clip_filelist.xml">
<style>

</style>
</head>

<body link="#0563C1" vlink="#954F72">



Test   Scenario | Test Steps | Test Cases | Check point | Status
-- | -- | -- | -- | --
AuditLogs (Level 3) on Deployment    on HA(RKE1) | 1. Install rancher server via helm and while installing add the env   variable --set auditLog.level=3 (v2.5.s1-head)     2. As an admin, create 1 rke1 node driver downstream cluster and an   eks  downstream cluster with 1 etcd, 1   cp and 1 worker pools in each of the clusters.     3. From the rke1 and EKS clusters, created a deployment | 1.   HA     2. Loglevel=3     3. Login as Admin     4. Create a RKE1 cluster     5. Create a Deployment     6. Checkfor the auditLogs | Appropriate   audit logs should be recorded      Should have a POST call with all the details should be present. | Pass
  |   | 1.   HA     2. Loglevel=3     3. Login as Admin     4. Create a RKE1 cluster     5. Scale up/Down deployment      6. Checkfor the auditLogs | Appropriate   audit logs should be recorded      Should have a  PUT  call with all the details should be   present. | Pass
  |   | 1.   HA     2. Loglevel=3     3. Login as Admin     4. Create a RKE1 cluster     5. Clone a Deployment     6. Checkfor the auditLogs | Appropriate   audit logs should be recorded      Should have a POST & PUT  call   with all the details should be present. | Pass
  |   | 1.   HA     2. Loglevel=3     3. Login as Admin     4. Create a RKE1 cluster     5. Delete a Deployment     6. Checkfor the auditLogs | Appropriate   audit logs should be recorded      Should have a DELETE call with all the details should be present. | Pass
AuditLogs (Level 3) on DaemonSet on HA(RKE1) | 1. Install rancher server via helm and while installing add the env   variable --set auditLog.level=3 (v2.5.s1-head)     2. As an admin, create 1 rke1 node driver downstream cluster and an   eks  downstream cluster with 1 etcd, 1   cp and 1 worker pools in each of the clusters.     3. From the rke1 and EKS clusters, created a daemon set with the container   image | 1.   HA     2. Loglevel=3     3. Login as Admin     4. Create a RKE1 cluster     5. Create a DemonSet     6. Checkfor the auditLogs | Appropriate   audit logs should be recorded      Should have a POST call with all the details should be present. | Pass
  |   | 1.   HA     2. Loglevel=3     3. Login as Admin     4. Create a RKE1 cluster     5. Clone a DemonSet     6. Checkfor the auditLogs | Appropriate   audit logs should be recorded      Should have a POST & PUT  call   with all the details should be present. | Pass
  |   | 1.   HA     2. Loglevel=3     3. Login as Admin     4. Create a RKE1 cluster     5. Delete a DemonSet     6. Checkfor the auditLogs | Appropriate   audit logs should be recorded      Should have a DELETE call with all the details should be present. | Pass
AuditLogs (Level 3) on Deployment    on Docker(RKE1) | 1. Install rancher server via docker and while installing add the env   variable --set auditLog.level=3 (v2.5.s1-head)     2. As an admin, create 1 rke1 node driver downstream cluster      3. From the rke1  created a   deployment  the container image | 1.   Docker install (v2.5.s1-head)     2. Loglevel=3     3. Login as Admin     4. Create a RKE1 cluster     5. Create a Deployment     6. Checkfor the auditLogs | Appropriate   audit logs should be recorded      Should have a POST call with all the details should be present. | Pass
  |   | 1.   Docker install (v2.5.s1-head)     2. Loglevel=3     3. Login as Admin     4. Create a RKE1 cluster     5. Scale up/Down deployment      6. Checkfor the auditLogs | Appropriate   audit logs should be recorded      Should have a  PUT  call with all the details should be   present. | Pass
  |   | 1.   Docker install (v2.5.s1-head)     2. Loglevel=3     3. Login as Admin     4. Create a RKE1 cluster     5. Clone a Deployment     6. Checkfor the auditLogs | Appropriate   audit logs should be recorded      Should have a POST & PUT  call   with all the details should be present. | Pass
  |   | 1.   Docker install (v2.5.s1-head)     2. Loglevel=3     3. Login as Admin     4. Create a RKE1 cluster     5. Delete a Deployment     6. Checkfor the auditLogs | Appropriate   audit logs should be recorded      Should have a DELETE call with all the details should be present. | Pass
Regression:     AuditLogs (Level 1) on Deployment  on   Docker(RKE1) | Regression:     1. Install rancher server via docker and while installing add the env   variable --set auditLog.level=1 (v2.5.s1-head)     2. As an admin, create 1 rke1 node driver downstream cluster      3. From the rke1  created a   deployment  the container image | 1.   Docker install (v2.5.s1-head)     2. Loglevel=1     3. Login as Admin     4. Create a RKE1 cluster     5. Create a Deployment     6. Checkfor the auditLogs | Appropriate   audit logs should be recorded      Should have a POST call with all the details should be present. | Pass
  |   | 1.   Docker install (v2.5.s1-head)     2. Loglevel=1     3. Login as Admin     4. Create a RKE1 cluster     5. Scale up/Down deployment      6. Checkfor the auditLogs | Appropriate   audit logs should be recorded      Should have a  PUT  call with all the details should be   present. | Pass
  |   | 1.   Docker install (v2.5.s1-head)     2. Loglevel=1     3. Login as Admin     4. Create a RKE1 cluster     5. Clone a Deployment     6. Checkfor the auditLogs | Appropriate   audit logs should be recorded      Should have a POST & PUT  call   with all the details should be present. | Pass
  |   | 1.   Docker install (v2.5.s1-head)     2. Loglevel=1     3. Login as Admin     4. Create a RKE1 cluster     5. Delete a Deployment     6. Checkfor the auditLogs | Appropriate   audit logs should be recorded      Should have a DELETE call with all the details should be present. | Pass



</body>

</html>

**Closed by dasarinaidu** 2022-11-29 21:57 UTC
Labels: kind/bug, [zube]: QA Working, team/area1
