### ISSUE TITLE
Timeout getting IP address in fresh Ubuntu 16.04 host on 1.3.0

### ISSUE THREAD

**Issue by dj-hedgehog** [rancher/rancher#7379] opened 2017-01-11 16:44 UTC
*I am aware there are plenty of issues regarding this but since this appears for me in Rancher 1.3 and I've tried everything I'm opening this issue nonetheless*

**Rancher Versions:**
Server: 1.3
everything else is latest

**Docker Version:** Docker version 1.12.6
**OS and where are the hosts located? (cloud, bare metal, etc):** bare metal
**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)** single node rancher, internal DB
**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)** Cattle  

Backstory: We've upgraded 5 hosts from Rancher 1.1.3 to 1.3. After 3 days of tinkering most things are running again but two hosts (CentOS 7) always had the infamous "Timeout getting IP address" error so I reinstalled a fresh Ubuntu 16.04 on them.

I added the following to `/etc/docker/daemon.json`

```
{
  "dns": ["8.8.8.8", "8.8.4.4"]
}
```
Then restarted `systemctl daemon-reload` & `service docker restart` but still `ipsec, healthcheck & ipsec-cni-driver` get timeouts.

**Comment by arnekaiser** [comment] 2017-01-12 20:34
We still have the same problem with (nearly) the same setup.

**Comment by Schinti95** [comment] 2017-01-14 02:55
i can confirm the same error with the same setup

**Comment by arnekaiser** [comment] 2017-01-30 10:20
Thank you so much @penguinxr2 ! Setting a fake search domain solved it for us also.

**Comment by dj-hedgehog** [comment] 2017-01-30 11:30
Oh my god, that fixed the nasty problem for me too. Both my Ubuntu 16.04 and 14.04 hosts are back online.

@penguinxr2: How did you find this problem?

**Comment by penguinxr2** [comment] 2017-01-30 15:09
@dj-hedgehog Took a while to get there, I tried pretty much every suggestion I could find related to this issue, which ultimately seemed to be exclusively DNS related. So when I found out it was trying to fetch rancher metadata from the webserver that was running on my domain catchall it gave an SSL certificate error. From that, I figured the DNS pecking order must have rancher's internal stuff dead last, so setting the search domain to something bogus made those queries fail and rancher would resolve against its internal DNS service. This is my understanding at least.

**Comment by dockerrancher** [comment] 2017-01-31 18:28
Thank you guys for the solution for this problem on my "netcup" root-server.

penguinxr2 wrote :

On the affected hosts I set the dns-search to something fictional- "example.org" via the /etc/docker/daemon.json.
{ "dns": ["8.8.8.8", "8.8.4.4"], "dns-search": ["example.org"] }

and after that i did :

systemctl daemon-reload & service docker restart


i tried several solutions, but only this one was the solution

**Comment by Kilhog** [comment] 2017-02-08 16:16
Same issue with debian jessie, I tried the solution with `{ "dns": ["8.8.8.8", "8.8.4.4"], "dns-search": ["example.org"] }` But it doesn't work, do you have another idea ?
(ps: I have also tried to run the dockerd like that : `/usr/bin/dockerd --dns 8.8.8.8 --dns 8.8.4.4 --dns-search ploppdsfoosdfp -H fd://` It still doesn't work)

**Comment by vipseixas** [comment] 2017-02-08 21:33
Changind DNS does not work for me. I'm using Rancher 1.4.0. 

Just created a new environment (cattle) and added a host (CentOS Atomic), the default services die with this error.

**Comment by aemneina** [comment] 2017-02-08 21:40
@vipseixas checklist to run through:

- selinux permissive or disabled? Usually the audit log would throw a permission error indicating SELinux doesnt like what is going on, when set to enforcing.
- dns (stated above)
- kernel version on OS (I've had good experiences 3.10.0-500+)
- is the metadata service up, healthy and reachable (check the container logs here, ensure the containers are not flapping)
- docker version

**Comment by vipseixas** [comment] 2017-02-09 17:27
@aemneina Sorry, I had to deactivate Rancher in my environment. The agent services were leading the machine load up to 8 (maybe because of this problem?) and it was troubling other processes. I will try again in a isolated environment.

The strange thing is that the issue was intermittent. My stack sometimes worked and sometimes became degraded with the IP error message.

**Comment by jsalva** [comment] 2017-02-09 21:46
I'm having the same issue as @vipseixas (intermittent IP timeout error) using 1.4.0. Never happened to me in 1.3.*

**Comment by aemneina** [comment] 2017-02-09 21:53
@jsalva can you check the metadata service containers, see how long they stay up? You can locate them under Stacks->Infrastructure Stacks... Network services -> metadata. Youll most likely need to check on the host the containers reside on using docker ps to see how long they've been up. There's also a logs tab under metadata service, that might hold hints as to why it might be restarting. The docker logs for the metadata containers might contain hints as well. Thats a key component in getting containers their IP's and if thats restarting sporadically, we should root out the reason why.

**Comment by jsalva** [comment] 2017-02-10 00:02
I let the containers run for a while, and I noticed that at a certain point, all of my metadata service logs consist exclusively the following:

`2/9/2017 6:58:08 PM2017/02/09 23:58:08 http: Accept error: accept tcp [::]:80: accept4: too many open files; retrying in 1s`

**Comment by elvecz** [comment] 2017-02-10 06:38
Worked for me as well! daemon.json, thanks a lot!

**Comment by ibuildthecloud** [comment] 2017-02-10 14:48
@jsalva The file descriptor leak issue should have be addressed already in 1.4.0.  1.4.1 will be released next week and will become the new stable version.

**Comment by jsalva** [comment] 2017-02-10 15:18
Thanks @ibuildthecloud; do you happen to know if there's something that can be done in the meantime, or should I just wait until 1.4.1?

**Comment by ibuildthecloud** [comment] 2017-02-11 00:57
@jsalva I need to confirm, I maybe wrong and this has not yet been fixed.  Regardless if it hasn't or not it should be in 1.4.1.  To answer you question though, you need to wait for 1.4.1.

**Comment by jsalva** [comment] 2017-02-14 18:33
@ibuildthecloud I still seem to be having the issue after upgrading to 1.4.1. Metadata service still appears to be hitting limits on open files, necessitating a regular restart of the network-services stack

**Comment by Hildebrand** [comment] 2017-02-15 08:45
I'm seeing the same issue. The rancher/metadata:v0.7.0 log is filled with one entry per second of the following line:
15/02/2017 09:44:322017/02/15 08:44:32 http: Accept error: accept tcp [::]:80: accept4: too many open files; retrying in 1s

Should we increase the ulimit?

**Comment by bsauvajon** [comment] 2017-02-21 11:20
Same problem here running Rancher 1.4.1, after a few hours rancher/metadata log is full of "too many open files" errors

**Comment by amsdard** [comment] 2017-02-28 09:13
Same problem with my environment on 1.4.1

**Comment by aemneina** [comment] 2017-05-17 21:36
This should since be resolved in more modern versions of rancher. If someone encounters this issue with rancher 1.5.x please file a new ticket with relevant details.

**Closed by aemneina** 2017-05-17 21:36 UTC

**Comment by dj-hedgehog** [comment] 2017-05-27 09:04
I am back with a fresh 16.04 host and latest Rancher 1.6.0 and the same problem :(

**Comment by kneufeld** [comment] 2017-11-08 21:35
I've been seeing the same thing in `1.6` on Ubuntu. What fixed the issue for me was installing a newer docker version from official docker repos (`Docker version 17.06.2-ce, build cec0b72`) by following instructions here: https://docs.docker.com/engine/installation/linux/docker-ce/ubuntu/
