### ISSUE TITLE
helm not working with rancher

### ISSUE THREAD

**Issue by aemneina** [rancher/rancher#7539] opened 2017-01-24 23:54 UTC
**Rancher Versions:**
Server:1.3.3
healthcheck:
ipsec:
network-services:
scheduler:
kubernetes (if applicable):
1.5.1

**Docker Version:**
1.12.6

**OS and where are the hosts located? (cloud, bare metal, etc):**

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
Nginx in front of rancher

**Steps to Reproduce:**
rancher behind nginx yields:
helm install deis/workflow --namespace deis

Error: forwarding ports: error upgrading connection: unable to upgrade connection: 

Hitting rancher server directly:
$ helm install deis/workflow --namespace deis

Error: forwarding ports: error upgrading connection: error dialing backend: dial tcp x.x.x.:10250: getsockopt: connection timed out

**Results:** 
helm to connect to k8s api and deploy tiller

**Comment by wlan0** [comment] 2017-01-25 20:09
@aemneina @galal-hussein This is fixed in v1.3.3 of rancher with nginx in front of rancher and the nginx config is  (slight changes from the doc) -

```
upstream rancher {
    server 127.0.0.1:8080;
}

server {
    listen 443 ssl spdy;
    server_name hussein.rancher.space;
    ssl_certificate ssl/nginx.crt;
    ssl_certificate_key ssl/nginx.key;

    location / {
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Forwarded-Port $server_port;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_pass http://rancher;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "Upgrade";
        # This allows the ability for the execute shell window to remain open for up to 15 minutes. Without this parameter, the default is 1 minute and will automatically close.
        proxy_read_timeout 900s;
    }
}

server {
    listen 80;
    server_name hussein.rancher.space;
    return 301 https://$server_name$request_uri;
}
```

**Comment by sangeethah** [comment] 2017-01-25 23:25
Duplicate of https://github.com/rancher/rancher/issues/7234

**Comment by galal-hussein** [comment] 2017-01-25 23:26
Rancher version: v1.3.3
kubernetes version: rancher/k8s:v1.5.1-rancher1-8

Tested nginx in front of Rancher and helm is working without problems.

**Closed by galal-hussein** 2017-01-25 23:26 UTC
Labels: kind/bug, status/resolved, status/to-test

**Comment by iambowen** [comment] 2017-03-27 03:42
Just found the same error, when using rancher 1.5.2 with k8s catalog 1.5.4.
I will try to change the k8s catolog first.
