### ISSUE TITLE
Cannot install Apps since 2.2.4

### ISSUE THREAD

**Issue by mwatche** [rancher/rancher#20912] opened 2019-06-17 15:24 UTC
**What kind of request is this (question/bug/enhancement/feature request):**
Cannot install apps since 2.2.4. With 2.2.3 it runs.

**Steps to reproduce (least amount of steps as possible):**
Install an app for example artifactory-ha

**Result:**
Failed to install.
Log:
2019/06/17 06:26:13 [INFO] Creating roleBinding User u-zmkw5fpsdq Role project-member
[main] 2019/06/17 06:26:16 Starting Tiller v2.10+unreleased (tls=false)
[main] 2019/06/17 06:26:16 GRPC listening on :49892
[main] 2019/06/17 06:26:16 Probes listening on :59489
[main] 2019/06/17 06:26:16 Storage driver is ConfigMap
[main] 2019/06/17 06:26:16 Max history per release is 1
[tiller] 2019/06/17 06:26:17 getting history for release artifactory-ha
[storage] 2019/06/17 06:26:17 getting release history for "artifactory-ha"
2019/06/17 06:26:18 [INFO] Handling backend connection request [c-c54n5:m-c7b40a7757c5]
2019/06/17 06:26:28 [INFO] error in remotedialer server [400]: read tcp 172.17.0.2:443->172.24.15.250:56536: i/o timeout
2019/06/17 06:26:29 [INFO] Handling backend connection request [c-c54n5:m-62c10847a69e]
2019/06/17 06:26:39 [INFO] error in remotedialer server [400]: read tcp 172.17.0.2:443->172.24.249.5:39594: i/o timeout
[storage/driver] 2019/06/17 06:26:47 query: failed to query with labels: Get https://localhost:443/k8s/clusters/c-c54n5/api/v1/namespaces/artifactory-ha/configmaps?labelSelector=NAME%3Dartifactory-ha%2COWNER%3DTILLER: dial tcp 10.128.0.229:443: i/o timeout
[tiller] 2019/06/17 06:26:47 preparing update for artifactory-ha
[storage] 2019/06/17 06:26:47 getting deployed releases from "artifactory-ha" history
2019/06/17 06:26:49 [INFO] Handling backend connection request [c-c54n5:m-c7b40a7757c5]
2019/06/17 06:26:58 [INFO] Handling backend connection request [c-c54n5:m-62c10847a69e]
2019/06/17 06:26:59 [INFO] error in remotedialer server [400]: read tcp 172.17.0.2:443->172.24.15.250:56624: i/o timeout
2019/06/17 06:27:08 [INFO] error in remotedialer server [400]: read tcp 172.17.0.2:443->172.24.249.5:39683: i/o timeout
[storage/driver] 2019/06/17 06:27:17 query: failed to query with labels: Get https://localhost:443/k8s/clusters/c-c54n5/api/v1/namespaces/artifactory-ha/configmaps?labelSelector=NAME%3Dartifactory-ha%2COWNER%3DTILLER%2CSTATUS%3DDEPLOYED: dial tcp 10.128.0.229:443: i/o timeout
2019/06/17 06:27:17 [ERROR] AppController p-tbfmw/artifactory-ha [helm-controller] failed with : failed to install app artifactory-ha. Error: UPGRADE FAILED: Get https://localhost:443/k8s/clusters/c-c54n5/api/v1/namespaces/artifactory-ha/configmaps?labelSelector=NAME%!!(MISSING)D(MISSING)artifactory-ha%!!(MISSING)C(MISSING)OWNER%!!(MISSING)D(MISSING)TILLER%!!(MISSING)C(MISSING)STATUS%!!(MISSING)D(MISSING)DEPLOYED: dial tcp 10.128.0.229:443: i/o timeout
 
2019/06/17 06:27:21 [INFO] Handling backend connection request [c-c54n5:m-c7b40a7757c5]
2019/06/17 06:27:21 [INFO] Handling backend connection request [c-c54n5:m-62c10847a69e]

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): 2.2.4
- Installation option (single install/HA): single install with 3 Nodes ectd/Control Plane and 5 Worker Nodes

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported):
- Machine type (cloud/VM/metal) and specifications (CPU/memory):
- Kubernetes version (use `kubectl version`):

```
Client Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.7", GitCommit:"6f482974b76db3f1e0f5d24605a9d1d38fad9a2b", GitTreeState:"clean", BuildDate:"2019-03-25T02:52:13Z", GoVersion:"go1.10.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.5", GitCommit:"2166946f41b36dea2c4626f90a77706f426cdea2", GitTreeState:"clean", BuildDate:"2019-03-25T15:19:22Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}

```

- Docker version (use `docker version`):

```
Client:
 Version:           18.09.6
 API version:       1.39
 Go version:        go1.10.8
 Git commit:        481bc77156
 Built:             Sat May  4 02:34:58 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.6
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.8
  Git commit:       481bc77
  Built:            Sat May  4 02:02:43 2019
  OS/Arch:          linux/amd64
  Experimental:     false
```

**Comment by cjellick** [comment] 2019-06-20 17:44
Looks like you are hitting this issue: https://github.com/rancher/rancher/issues/20289

I've described the root cause and some possible ways to temporarily workaround here:
https://github.com/rancher/rancher/issues/20289#issuecomment-503687274

**Comment by cjellick** [comment] 2019-06-20 17:54
@sangeethah I think this doesn't need any more testing than what is in #20289. I think thye are the same issue.

**Comment by sangeethah** [comment] 2019-06-21 16:34
Closing this issue with the test results from 
 -https://github.com/rancher/rancher/issues/20289#issuecomment-504133724

**Closed by sangeethah** 2019-06-21 16:34 UTC
Labels: [zube]: To Test, kind/bug
