### ISSUE TITLE
LB with SSL - cert config missing after LB (working state) scaled down from n to 0 and then scaled up from 0 to n

### ISSUE THREAD

**Issue by aruneli** [rancher/rancher#1910] opened 2015-08-28 01:03 UTC
Had a LB with SSL termination in working state (scale :3)
Scaled down to 0
Scaled up to 1
haproxy.cfg has no cert configured now

<img width="1203" alt="screen shot 2015-08-27 at 5 59 24 pm" src="https://cloud.githubusercontent.com/assets/7720752/9536850/e50fbda2-4ce5-11e5-9058-b8558067115c.png">

**Comment by alena1108** [comment] 2015-08-28 01:11
Duplicate of https://github.com/rancher/rancher/issues/1899

**Closed by alena1108** 2015-08-28 01:11 UTC
