### ISSUE TITLE
K8s system stack not able to start because of etcd containers getting 404 when access metadata.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#6098] opened 2016-10-01 00:00 UTC
Rancher Server - server version from master
K8s version - 1.4 template version - latest from "qa" branch ( https://github.com/rancher/rancher-catalog)

etcd logs:

```
++ giddyup service scale etcd
time="2016-09-30T23:32:28Z" level=fatal msg="Error 404 accessing /self/stack/services/etcd path" 
+ SCALE=
++ giddyup ip myip
time="2016-09-30T23:32:28Z" level=fatal msg="Failed to find IP: Error 404 accessing /self/container path" 
+ IP=
+ META_URL=http://rancher-metadata.rancher.internal/2015-12-19
++ wget -q -O - http://rancher-metadata.rancher.internal/2015-12-19/self/stack/name
wget: server returned error: HTTP/1.1 404 Not Found
+ STACK_NAME=
++ wget -q -O - http://rancher-metadata.rancher.internal/2015-12-19/self/container/create_index
wget: server returned error: HTTP/1.1 404 Not Found
+ CREATE_INDEX=
++ wget -q -O - http://rancher-metadata.rancher.internal/2015-12-19/self/container/service_index
wget: server returned error: HTTP/1.1 404 Not Found
+ SERVICE_INDEX=
++ wget -q -O - http://rancher-metadata.rancher.internal/2015-12-19/self/host/uuid
+ HOST_UUID=9d5083d9-d28d-4aab-b177-a8befc725c1d
+ LEGACY_DATA_DIR=/data
+ DATA_DIR=/pdata
+ DR_FLAG=/pdata/DR
+ export ETCD_DATA_DIR=/pdata/data.current
+ ETCD_DATA_DIR=/pdata/data.current
+ export ETCDCTL_ENDPOINT=http://etcd.:2379
+ ETCDCTL_ENDPOINT=http://etcd.:2379
++ tr . -
++ echo
+ NAME=
+ '[' 1 -eq 0 ']'
+ eval node
++ node
++ mkdir -p /pdata/data.current
++ '[' -d /data/member ']'
++ '[' -d /data/data.current ']'
++ '[' -f /pdata/DR ']'
++ '[' -d /pdata/data.current/member ']'
+++ cat /pdata/data.current/ip
++ '[' 10.42.3.242 == '' ']'
+++ grep
+++ etcdctl_one member list
+++ target_ip=0
++++ giddyup service containers
+++ for container in '$(giddyup service containers)'
++++ wget -q -O - http://rancher-metadata.rancher.internal/2015-12-19/self/service/containers/Kubernetes_etcd_1/primary_ip
+++ primary_ip=10.42.163.245
+++ giddyup probe tcp://10.42.163.245:2379
+++ '[' 1 == 0 ']'
+++ '[' 0 == 0 ']'
+++ echo No etcd nodes available
BusyBox v1.24.1 (2015-12-16 08:00:02 GMT) multi-call binary.
Usage: grep [-HhnlLoqvsriwFE] [-m N] [-A/B/C N] PATTERN/-e PATTERN.../-f FILE [FILE]...
Search for PATTERN in FILEs (or stdin)
    -H  Add 'filename:' prefix
    -h  Do not add 'filename:' prefix
    -n  Add 'line_no:' prefix
    -l  Show only names of files that match
    -L  Show only names of files that don't match
    -c  Show only count of matching lines
    -o  Show only the matching part of line
    -q  Quiet. Return 0 if PATTERN is found, 1 otherwise
    -v  Select non-matching lines
    -s  Suppress open and read errors
    -r  Recurse
    -i  Ignore case
    -w  Match whole words only
    -x  Match whole lines only
    -F  PATTERN is a literal (not regexp)
    -E  PATTERN is an extended regexp
    -m N    Match up to N times per file
    -A N    Print N lines of trailing context
    -B N    Print N lines of leading context
    -C N    Same as '-A N -B N'
    -e PTRN Pattern to match
    -f FILE Read pattern from file
++ '[' '' ']'
++ giddyup leader check
++ '[' -d /pdata/data.current/member ']'
++ echo data.current
++ disaster_node
+++ cat /pdata/DR
++ RECOVERY_DIR=/pdata/data.current
++ '[' /pdata/data.current == /pdata/data.current ']'
+++ create_backup DR /pdata/data.current
+++ backup_type=DR
+++ target_dir=/pdata/data.current
++++ date +%Y%m%d.%H%M%S
+++ backup_dir=/pdata/data.20160930.233228.DR
+++ etcdctl backup --data-dir /pdata/data.current --backup-dir /pdata/data.20160930.233228.DR
+++ echo /pdata/data.20160930.233228.DR
++ RECOVERY_DIR=/pdata/data.20160930.233228.DR
++ echo 'Sanitizing backup...'
Sanitizing backup...
++ PID=48
++ giddyup probe http://127.0.0.1:2379/health --loop --min 1s --max 15s --backoff 1.2
++ etcd --name --data-dir /pdata/data.20160930.233228.DR --force-new-cluster
Get http://127.0.0.1:2379/health: dial tcp 127.0.0.1:2379: getsockopt: connection refused
2016-09-30 23:32:29.040939 E | etcdmain: error verifying flags, '/pdata/data.20160930.233228.DR' is not a valid flag. See 'etcd --help'.
Get http://127.0.0.1:2379/health: dial tcp 127.0.0.1:2379: getsockopt: connection refused
Get http://127.0.0.1:2379/health: dial tcp 127.0.0.1:2379: getsockopt: connection refused
Get http://127.0.0.1:2379/health: dial tcp 127.0.0.1:2379: getsockopt: connection refused
Get http://127.0.0.1:2379/health: dial tcp 127.0.0.1:2379: getsockopt: connection refused
Get http://127.0.0.1:2379/health: dial tcp 127.0.0.1:2379: getsockopt: connection refused
Get http://127.0.0.1:2379/health: dial tcp 127.0.0.1:2379: getsockopt: connection refused
Get http://127.0.0.1:2379/health: dial tcp 127.0.0.1:2379: getsockopt: connection refused
Get http://127.0.0.1:2379/health: dial tcp 127.0.0.1:2379: getsockopt: connection refused
Get http://127.0.0.1:2379/health: dial tcp 127.0.0.1:2379: getsockopt: connection refused
Get http://127.0.0.1:2379/health: dial tcp 127.0.0.1:2379: getsockopt: connection refused
Get http://127.0.0.1:2379/health: dial tcp 127.0.0.1:2379: getsockopt: connection refused
Get http://127.0.0.1:2379/health: dial tcp 127.0.0.1:2379: getsockopt: connection refused
Get http://127.0.0.1:2379/health: dial tcp 127.0.0.1:2379: getsockopt: connection refused
Get http://127.0.0.1:2379/health: dial tcp 127.0.0.1:2379: getsockopt: connection refused
Get http://127.0.0.1:2379/health: dial tcp 127.0.0.1:2379: getsockopt: connection refused
Get http://127.0.0.1:2379/health: dial tcp 127.0.0.1:2379: getsockopt: connection refused
Get http://127.0.0.1:2379/health: dial tcp 127.0.0.1:2379: getsockopt: connection refused
Get http://127.0.0.1:2379/health: dial tcp 127.0.0.1:2379: getsockopt: connection refused
Get http://127.0.0.1:2379/health: dial tcp 127.0.0.1:2379: getsockopt: connection refused
Get http://127.0.0.1:2379/health: dial tcp 127.0.0.1:2379: getsockopt: connection refused
Get http://127.0.0.1:2379/health: dial tcp 127.0.0.1:2379: getsockopt: connection refused
Get http://127.0.0.1:2379/health: dial tcp 127.0.0.1:2379: getsockopt: connection refused
Get http://127.0.0.1:2379/health: dial tcp 127.0.0.1:2379: getsockopt: connection refused
Get http://127.0.0.1:2379/health: dial tcp 127.0.0.1:2379: getsockopt: connection refused
Get http://127.0.0.1:2379/health: dial tcp 127.0.0.1:2379: getsockopt: connection refused
Get http://127.0.0.1:2379/health: dial tcp 127.0.0.1:2379: getsockopt: connection refused
```

kubernetes logs:

```
9/30/2016 4:56:53 PM+ UUID=fff4ac85-afe6-4b4c-bd29-74fd4e124268
9/30/2016 4:56:53 PM++ jq -r '.data[0].actions.certificate'
9/30/2016 4:56:53 PM++ curl -s -u 3D588FF83A963728CFB8:CS5v9A2zRKr5Gy27TTn1wqoweUUoXucz9Gq6Poy8 'http://104.155.157.90:8080/v1/services?uuid=fff4ac85-afe6-4b4c-bd29-74fd4e124268'
9/30/2016 4:56:53 PM+ ACTION='http://104.155.157.90:8080/v1/services/1s130/?action=certificate'
9/30/2016 4:56:53 PM+ '[' -n 'http://104.155.157.90:8080/v1/services/1s130/?action=certificate' ']'
9/30/2016 4:56:53 PM+ mkdir -p /etc/kubernetes/ssl
9/30/2016 4:56:53 PM+ cd /etc/kubernetes/ssl
9/30/2016 4:56:53 PM+ curl -s -u 3D588FF83A963728CFB8:CS5v9A2zRKr5Gy27TTn1wqoweUUoXucz9Gq6Poy8 -X POST 'http://104.155.157.90:8080/v1/services/1s130/?action=certificate'
9/30/2016 4:56:53 PM+ unzip -o certs.zip
9/30/2016 4:56:53 PMfff4ac85-afe6-4b4c-bd29-74fd4e124268Archive:  certs.zip
9/30/2016 4:56:53 PM  inflating: ca.pem
9/30/2016 4:56:53 PM  inflating: cert.pem
9/30/2016 4:56:53 PM  inflating: key.pem
9/30/2016 4:56:53 PM+ cd /
9/30/2016 4:56:53 PM+ cat
9/30/2016 4:56:53 PM+ '[' kube-apiserver == kubelet ']'
9/30/2016 4:56:53 PM+ '[' kube-apiserver == kube-apiserver ']'
9/30/2016 4:56:53 PM++ curl -s http://rancher-metadata/2015-12-19/self/container/ips/0
9/30/2016 4:56:53 PM+ CONTAINERIP=10.42.43.53
9/30/2016 4:56:53 PM+ set -- kube-apiserver --service-cluster-ip-range=10.43.0.0/16 --etcd-servers=http://etcd:2379 --insecure-bind-address=0.0.0.0 --insecure-port=80 --cloud-provider=rancher --allow_privileged=true --admission-control=NamespaceLifecycle,LimitRanger,SecurityContextDeny,ResourceQuota,ServiceAccount --client-ca-file=/etc/kubernetes/ssl/ca.pem --tls-cert-file=/etc/kubernetes/ssl/cert.pem --tls-private-key-file=/etc/kubernetes/ssl/key.pem --advertise-address=10.42.43.53
9/30/2016 4:56:53 PM+ exec kube-apiserver --service-cluster-ip-range=10.43.0.0/16 --etcd-servers=http://etcd:2379 --insecure-bind-address=0.0.0.0 --insecure-port=80 --cloud-provider=rancher --allow_privileged=true --admission-control=NamespaceLifecycle,LimitRanger,SecurityContextDeny,ResourceQuota,ServiceAccount --client-ca-file=/etc/kubernetes/ssl/ca.pem --tls-cert-file=/etc/kubernetes/ssl/cert.pem --tls-private-key-file=/etc/kubernetes/ssl/key.pem --advertise-address=10.42.43.53
9/30/2016 4:56:53 PMI0930 23:56:53.435427       1 genericapiserver.go:630] Will report 10.42.43.53 as public IP address.
9/30/2016 4:56:53 PMW0930 23:56:53.474859       1 cacher.go:469] Terminating all watchers from cacher *storage.StorageClass
9/30/2016 4:56:53 PMW0930 23:56:53.476362       1 cacher.go:469] Terminating all watchers from cacher *api.PodTemplate
9/30/2016 4:56:53 PMW0930 23:56:53.476683       1 cacher.go:469] Terminating all watchers from cacher *api.LimitRange
9/30/2016 4:56:53 PMW0930 23:56:53.476901       1 cacher.go:469] Terminating all watchers from cacher *api.ResourceQuota
9/30/2016 4:56:53 PMW0930 23:56:53.477137       1 cacher.go:469] Terminating all watchers from cacher *api.Secret
9/30/2016 4:56:53 PMW0930 23:56:53.477354       1 cacher.go:469] Terminating all watchers from cacher *api.ServiceAccount
9/30/2016 4:56:53 PMW0930 23:56:53.477704       1 cacher.go:469] Terminating all watchers from cacher *api.PersistentVolume
9/30/2016 4:56:53 PMW0930 23:56:53.477991       1 cacher.go:469] Terminating all watchers from cacher *api.PersistentVolumeClaim
9/30/2016 4:56:53 PMW0930 23:56:53.478229       1 cacher.go:469] Terminating all watchers from cacher *api.ConfigMap
9/30/2016 4:56:53 PMW0930 23:56:53.478440       1 cacher.go:469] Terminating all watchers from cacher *api.Namespace
9/30/2016 4:56:53 PMW0930 23:56:53.478655       1 cacher.go:469] Terminating all watchers from cacher *api.Endpoints
9/30/2016 4:56:53 PMW0930 23:56:53.478857       1 cacher.go:469] Terminating all watchers from cacher *api.Node
9/30/2016 4:56:53 PMW0930 23:56:53.479089       1 cacher.go:469] Terminating all watchers from cacher *api.Pod
9/30/2016 4:56:53 PMW0930 23:56:53.479290       1 cacher.go:469] Terminating all watchers from cacher *api.Service
9/30/2016 4:56:53 PMW0930 23:56:53.479587       1 cacher.go:469] Terminating all watchers from cacher *api.ReplicationController
9/30/2016 4:56:53 PMW0930 23:56:53.481013       1 cacher.go:469] Terminating all watchers from cacher *apps.PetSet
9/30/2016 4:56:53 PMW0930 23:56:53.481695       1 cacher.go:469] Terminating all watchers from cacher *autoscaling.HorizontalPodAutoscaler
9/30/2016 4:56:53 PMW0930 23:56:53.481915       1 cacher.go:469] Terminating all watchers from cacher *batch.Job
9/30/2016 4:56:53 PMW0930 23:56:53.482136       1 cacher.go:469] Terminating all watchers from cacher *certificates.CertificateSigningRequest
9/30/2016 4:56:53 PMW0930 23:56:53.482372       1 cacher.go:469] Terminating all watchers from cacher *autoscaling.HorizontalPodAutoscaler
9/30/2016 4:56:53 PMW0930 23:56:53.482611       1 cacher.go:469] Terminating all watchers from cacher *api.ReplicationController
9/30/2016 4:56:53 PME0930 23:56:53.483082       1 reflector.go:214] k8s.io/kubernetes/plugin/pkg/admission/serviceaccount/admission.go:103: Failed to list *api.ServiceAccount: Get http://0.0.0.0:80/api/v1/serviceaccounts?resourceVersion=0: dial tcp 0.0.0.0:80: getsockopt: connection refused
9/30/2016 4:56:53 PMW0930 23:56:53.483320       1 cacher.go:469] Terminating all watchers from cacher *extensions.DaemonSet
9/30/2016 4:56:53 PMW0930 23:56:53.483630       1 cacher.go:469] Terminating all watchers from cacher *extensions.Deployment
9/30/2016 4:56:53 PMW0930 23:56:53.483961       1 cacher.go:469] Terminating all watchers from cacher *batch.Job
9/30/2016 4:56:53 PMW0930 23:56:53.487090       1 cacher.go:469] Terminating all watchers from cacher *extensions.Ingress
9/30/2016 4:56:53 PMW0930 23:56:53.487384       1 cacher.go:469] Terminating all watchers from cacher *extensions.ReplicaSet
9/30/2016 4:56:53 PMW0930 23:56:53.487693       1 cacher.go:469] Terminating all watchers from cacher *extensions.NetworkPolicy
9/30/2016 4:56:53 PMW0930 23:56:53.488007       1 cacher.go:469] Terminating all watchers from cacher *policy.PodDisruptionBudget
9/30/2016 4:56:53 PMW0930 23:56:53.488236       1 cacher.go:469] Terminating all watchers from cacher *rbac.Role
9/30/2016 4:56:53 PMW0930 23:56:53.508557       1 cacher.go:469] Terminating all watchers from cacher *rbac.Role
9/30/2016 4:56:53 PMW0930 23:56:53.509002       1 cacher.go:469] Terminating all watchers from cacher *rbac.RoleBinding
9/30/2016 4:56:53 PMW0930 23:56:53.509231       1 cacher.go:469] Terminating all watchers from cacher *rbac.ClusterRole
9/30/2016 4:56:53 PMW0930 23:56:53.509593       1 cacher.go:469] Terminating all watchers from cacher *rbac.ClusterRoleBinding
9/30/2016 4:56:53 PMW0930 23:56:53.509808       1 cacher.go:469] Terminating all watchers from cacher *rbac.RoleBinding
9/30/2016 4:56:53 PMW0930 23:56:53.510012       1 cacher.go:469] Terminating all watchers from cacher *rbac.ClusterRole
9/30/2016 4:56:53 PMW0930 23:56:53.510297       1 cacher.go:469] Terminating all watchers from cacher *rbac.ClusterRoleBinding
9/30/2016 4:56:53 PME0930 23:56:53.513638       1 reflector.go:214] k8s.io/kubernetes/plugin/pkg/admission/resourcequota/resource_access.go:83: Failed to list *api.ResourceQuota: Get http://0.0.0.0:80/api/v1/resourcequotas?resourceVersion=0: dial tcp 0.0.0.0:80: getsockopt: connection refused
9/30/2016 4:56:53 PME0930 23:56:53.515391       1 reflector.go:203] k8s.io/kubernetes/plugin/pkg/admission/limitranger/admission.go:154: Failed to list *api.LimitRange: Get http://0.0.0.0:80/api/v1/limitranges?resourceVersion=0: dial tcp 0.0.0.0:80: getsockopt: connection refused
9/30/2016 4:56:53 PME0930 23:56:53.515929       1 reflector.go:214] k8s.io/kubernetes/plugin/pkg/admission/serviceaccount/admission.go:119: Failed to list *api.Secret: Get http://0.0.0.0:80/api/v1/secrets?fieldSelector=type%3Dkubernetes.io%2Fservice-account-token&resourceVersion=0: dial tcp 0.0.0.0:80: getsockopt: connection refused
9/30/2016 4:56:53 PME0930 23:56:53.645617       1 cacher.go:254] unexpected ListAndWatch error: pkg/storage/cacher.go:194: Failed to list *rbac.ClusterRole: client: etcd cluster is unavailable or misconfigured
9/30/2016 4:56:53 PME0930 23:56:53.645956       1 cacher.go:254] unexpected ListAndWatch error: pkg/storage/cacher.go:194: Failed to list *rbac.RoleBinding: client: etcd cluster is unavailable or misconfigured
9/30/2016 4:56:53 PME0930 23:56:53.646198       1 cacher.go:254] unexpected ListAndWatch error: pkg/storage/cacher.go:194: Failed to list *rbac.ClusterRoleBinding: client: etcd cluster is unavailable or misconfigured
9/30/2016 4:56:53 PME0930 23:56:53.646358       1 cacher.go:254] unexpected ListAndWatch error: pkg/storage/cacher.go:194: Failed to list *rbac.ClusterRole: client: etcd cluster is unavailable or misconfigured
9/30/2016 4:56:53 PME0930 23:56:53.646477       1 cacher.go:254] unexpected ListAndWatch error: pkg/storage/cacher.go:194: Failed to list *rbac.RoleBinding: client: etcd cluster is unavailable or misconfigured
9/30/2016 4:56:53 PME0930 23:56:53.646657       1 cacher.go:254] unexpected ListAndWatch error: pkg/storage/cacher.go:194: Failed to list *rbac.Role: client: etcd cluster is unavailable or misconfigured
9/30/2016 4:56:53 PME0930 23:56:53.646772       1 cacher.go:254] unexpected ListAndWatch error: pkg/storage/cacher.go:194: Failed to list *rbac.Role: client: etcd cluster is unavailable or misconfigured
9/30/2016 4:56:53 PME0930 23:56:53.647648       1 cacher.go:254] unexpected ListAndWatch error: pkg/storage/cacher.go:194: Failed to list *policy.PodDisruptionBudget: client: etcd cluster is unavailable or misconfigured
9/30/2016 4:56:53 PME0930 23:56:53.647869       1 cacher.go:254] unexpected ListAndWatch error: pkg/storage/cacher.go:194: Failed to list *extensions.NetworkPolicy: client: etcd cluster is unavailable or misconfigured
9/30/2016 4:56:53 PME0930 23:56:53.648090       1 cacher.go:254] unexpected ListAndWatch error: pkg/storage/cacher.go:194: Failed to list *extensions.ReplicaSet: client: etcd cluster is unavailable or misconfigured
9/30/2016 4:56:53 PME0930 23:56:53.649110       1 cacher.go:254] unexpected ListAndWatch error: pkg/storage/cacher.go:194: Failed to list *extensions.Ingress: client: etcd cluster is unavailable or misconfigured
9/30/2016 4:56:53 PME0930 23:56:53.649268       1 cacher.go:254] unexpected ListAndWatch error: pkg/storage/cacher.go:194: Failed to list *batch.Job: client: etcd cluster is unavailable or misconfigured
9/30/2016 4:56:53 PME0930 23:56:53.650132       1 cacher.go:254] unexpected ListAndWatch error: pkg/storage/cacher.go:194: Failed to list *extensions.Deployment: client: etcd cluster is unavailable or misconfigured
9/30/2016 4:56:53 PME0930 23:56:53.650303       1 cacher.go:254] unexpected ListAndWatch error: pkg/storage/cacher.go:194: Failed to list *extensions.DaemonSet: client: etcd cluster is unavailable or misconfigured
9/30/2016 4:56:53 PMW0930 23:56:53.650457       1 storage_extensions.go:83] third party resource sync failed: client: etcd cluster is unavailable or misconfigured
9/30/2016 4:56:53 PME0930 23:56:53.650585       1 cacher.go:254] unexpected ListAndWatch error: pkg/storage/cac
```

**Comment by LLParse** [comment] 2016-10-05 17:54
@deniseschannon I see you assigned this to me...do you want me to fix metadata? Or are we going to revert to putting loops at the top of every container to wait for metadata to become reachable?

**Comment by alena1108** [comment] 2016-10-07 16:41
timing issues are most likely caused by the new agent. We'd have to put a wait loop for now on the service level

**Comment by sangeethah** [comment] 2016-10-07 16:49
Older K8s templates will have to continue to work on rancher-server version - 1.2  as well.

**Comment by sangeethah** [comment] 2016-10-11 05:21
This issue is not encountered when testing with k8s 1.4 templates which have introduced delays when accessing metadata.

Keeping this issue open to make the metadata propagation faster , so we will not have any issues when using older K8s templates which do not have any delay when accessing metadata.

**Comment by deniseschannon** [comment] 2016-11-02 19:02
@sangeethah Do we still need this open if we are only offering k8s 1.4 templates?

**Closed** 2016-11-02 21:06 UTC
Labels: area/kubernetes, area/metadata, kind/bug, status/blocker, status/to-test

**Comment by deniseschannon** [comment] 2016-11-02 21:07
In Rancher 1.2, we will only support K8S 1.4 so this should be fixed.
