### ISSUE TITLE
[Windows] rancher-agent on windows 1809, x509 cert signed by unkown

### ISSUE THREAD

**Issue by curx** [rancher/rancher#20235] opened 2019-05-14 16:06 UTC
**What kind of request is this (question/bug/enhancement/feature request):**
bug

**Steps to reproduce (least amount of steps as possible):**
start rancher-agent on windows 1809 worker via run cmd provided from rancherui

**Result:**
```
ERRO[0000] https://192.168.100.131 is not accessible (The underlying connection was closed: Could not establish trust relationship for the SSL/TLS secure channel.)
```

**Other details that may be helpful:**
test rancher installation with autogenerated tls certificate,
created on a linux
```
docker run -d --port 80:80 -p 443:443 -v /opt/rancher:/var/lib/rancher rancher/rancher:master
```

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI):
rancher/rancher:master, commit: b7071be
```
{
...
  "org.label-schema.build-date": "2019-05-14T04:29:13Z",
  "org.label-schema.vcs-ref": "b7071befc39087148a8660754f0e972b62c1d6a6",
  "org.label-schema.vcs-url": "https://github.com/rancher/rancher.git"
...
}
```
rancher/rancher-agent:master
```
{
...
   "org.label-schema.build-date": "2019-05-14T04:26:34Z",
   "org.label-schema.vcs-ref": "b7071befc39087148a8660754f0e972b62c1d6a6",
   "org.label-schema.vcs-url": "https://github.com/rancher/rancher.git",
...
}
```
- Installation option (single install/HA): **single**

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): **custom**
- Machine type (cloud/VM/metal) and specifications (CPU/memory): **VM**
- Kubernetes version (use `kubectl version`): **v1.14.1-rancher1-2**

- Docker version (use `docker version`):

``` docker version
Client: Docker Engine - Enterprise
 Version:           18.09.6
 API version:       1.39
 Go version:        go1.10.8
 Git commit:        1578dcadd2
 Built:             05/04/2019 02:34:11
 OS/Arch:           windows/amd64
 Experimental:      false

Server: Docker Engine - Enterprise
 Engine:
  Version:          18.09.6
  API version:      1.39 (minimum version 1.24)
  Go version:       go1.10.8
  Git commit:       1578dcadd2
  Built:            05/04/2019 02:32:24
  OS/Arch:          windows/amd64
  Experimental:     false
```

**Comment by curx** [comment] 2019-05-14 17:18
As a "workaround" i've imported the rancher selfsigned cacert to Windows CertStoreLocation via PowerShell: `Import-Certificate -CertStoreLocation Cert:\CurrentUser\Root\ -FilePath C:\cert.cer`

**Comment by thxCode** [comment] 2019-05-23 02:59
@curx , Boot a new rancher-server via `docker run -d --port 80:80 -p 443:443 -v /opt/rancher:/var/lib/rancher rancher/rancher:master`, but I could not reproduce this issue.

Do you follow [OPTION B-BRING YOUR OWN CERTIFICATE: SELF-SIGNED] (https://rancher.com/docs/rancher/v2.x/en/installation/single-node/) to setup rancher-server?

**Comment by curx** [comment] 2019-05-27 07:01
@thxCode, i've used Option A; the let Rancher create my certificate ;)
Have you tested it as well?

**Comment by loganhz** [comment] 2019-05-28 21:41
Reproduced in Aliyun Cloud. We will fix it. Thanks for the report

**Comment by loganhz** [comment] 2019-05-31 23:18
@curx fixed in `rancher/rancher:master` Could you try that, please? Next preview version will be out in June

**Comment by kingsd041** [comment] 2019-06-12 07:23
Tested  rancher/rancher:master (06/12)
According to the reproduce step test, I can add windows nodes on Aliyun

**Closed by kingsd041** 2019-06-12 07:23 UTC
Labels: [zube]: To Test, alpha, area/windows, kind/bug, team/cn
