### ISSUE TITLE
[v2.7]  Update ACI-CNI to 6.0.4.2

### ISSUE THREAD

**Issue by akhilesh-oc** [rancher/rancher#45910] opened 2024-06-26 08:42 UTC
There is ACI-CNI version 6.0.4.2 which is an upgrade to 6.0.4.1

**Comment by snasovich** [comment] 2024-07-02 15:32
Closed as duplicate of https://github.com/rancher/rancher/issues/45949

**Closed by snasovich** 2024-07-02 15:32 UTC
Labels: kind/enhancement, team/hostbusters, area/kdm, feature/kdm
