### ISSUE TITLE
[BUG] Fleet-local workspace doesn't deploy on local setups

### ISSUE THREAD

**Issue by MbolotSuse** [rancher/rancher#43017] opened 2023-09-29 19:41 UTC
**Rancher Server Setup**
- Rancher version: release/v2.8, run on local

**Information about the Cluster**
- Kubernetes version: 1.27
- Cluster Type (Local/Downstream): local

**User Information**
N/A

**Describe the bug**
When rancher is run on a local setup, the `fleet-local` workspace is not created, and the following error is repeated in the logs:
> [ERROR] error syncing 'fleet-local/local': handler cluster-create: server url is missing, can't generate kubeconfig for fleet import cluster, requeuing

This seems to be caused by the below behavior:
- Rancher [pre-creates](https://github.com/rancher/rancher/blob/436f4de405dece4b03d1a8e059d9bad35db37cea/pkg/data/dashboard/namespace.go#L19) the `fleet-local` system namespace early on in it's boot process.
- Rancher creates the `local` management cluster, which causes a provisioning cluster to be created
- Rancher attempts to create a [fleet cluster](https://github.com/rancher/rancher/blob/436f4de405dece4b03d1a8e059d9bad35db37cea/pkg/controllers/provisioningv2/fleetcluster/fleetcluster.go#L163) based on the provisioning cluster
- Rancher attempts to [produce a kubeconfig](https://github.com/rancher/rancher/blob/436f4de405dece4b03d1a8e059d9bad35db37cea/pkg/provisioningv2/kubeconfig/manager.go#L301) based on the internal server url
- Since rancher is not running in an embedded configuration, and is not in a HA environment (or a downstream cluster), rancher has [not set](https://github.com/rancher/rancher/blob/436f4de405dece4b03d1a8e059d9bad35db37cea/pkg/controllers/dashboard/apiservice/setting.go#L56) the internal server url
- Since no fleet cluster is created, the [backing fleetworkspace](https://github.com/rancher/rancher/blob/436f4de405dece4b03d1a8e059d9bad35db37cea/pkg/controllers/provisioningv2/fleetworkspace/controller.go#L110) for fleet-local is never created.
- Once the webhook has been deployed, since the `fleet-local` namespace has already been created, Rancher is no longer able to create the fleet-local workspace.

**To Reproduce**
Run rancher on local.

**Result**
No fleet-local workspace is created, and users cannot target resources at the local cluster.

**Expected Result**
The fleet-local workspace is created, like in a docker enviroment.

**Screenshots**
N/A

**Comment by manno** [comment] 2023-10-04 10:13
> Rancher [pre-creates](https://github.com/rancher/rancher/blob/436f4de405dece4b03d1a8e059d9bad35db37cea/pkg/data/dashboard/namespace.go#L19) the fleet-local system namespace early on in it's boot process.

Is that necessary? Doesn't creating a workspace create a namespace?

> Since rancher is not running in an embedded configuration, and is not in a HA environment (or a downstream cluster), rancher has [not set](https://github.com/rancher/rancher/blob/436f4de405dece4b03d1a8e059d9bad35db37cea/pkg/controllers/dashboard/apiservice/setting.go#L56) the internal server url

Isn't Rancher always installed with ` --set hostname=`?

> Once the webhook has been deployed, since the fleet-local namespace has already been created, Rancher is no longer able to create the fleet-local namespace.

Did you mean "workspace" instead of namespace?

**Comment by MbolotSuse** [comment] 2023-10-04 13:10
> Is that necessary? Doesn't creating a workspace create a namespace?

I'm not sure. It's possible that rancher needs to put things (like local cluster resources) inside the namespace before the workspace is created. 

> Isn't Rancher always installed with  --set hostname=?

No. The docker install of Rancher does not require that this be set at install time.

> Did you mean "workspace" instead of namespace?

Yes, the last word of the sentence should read "workspace" instead of namespace. Thanks for catching the typo, I will update the issue.

**Comment by zozidalom** [comment] 2023-10-23 18:39
Same issue for me ([ERROR] error syncing 'fleet-local/local': handler cluster-create: server url is missing, can't generate kubeconfig for fleet import cluster, requeuing) by using [v2.7.8-linux-amd64](https://hub.docker.com/layers/rancher/rancher/v2.7.8-linux-amd64/images/sha256-eb827c2b0dca1b065ee4eb62721cd9153279f7b4aa00a3d7d1142b986b7e7be3?context=explore)

**Comment by manno** [comment] 2024-03-20 14:53
This is seems to be a duplicate of https://github.com/rancher/rancher/issues/41848. Please reopen if the problem persists.

**Closed by manno** 2024-03-20 14:53 UTC
Labels: kind/bug
