### ISSUE TITLE
Couldn't bring up network: couldn't find any CNI network configurations

### ISSUE THREAD

**Issue by dotnet123** [rancher/rancher#10112] opened 2017-10-13 01:18 UTC
**Rancher versions:v2.0.0-alpha9*

CentOS Linux release 7.3.1611 (Core) 

I got this error.

![333](https://user-images.githubusercontent.com/21954452/31526103-5771f376-aff7-11e7-8464-ec22fdabbd83.png)

**Comment by superseb** [comment] 2017-10-13 08:22
Closing as duplicate of https://github.com/rancher/rancher/issues/10033

**Closed by superseb** 2017-10-13 08:22 UTC
