### ISSUE TITLE
SSLError when adding a worker

### ISSUE THREAD

**Issue by nesc58** [rancher/rancher#9089] opened 2017-06-16 13:57 UTC
Hi,
I've got the following error message when register a worker / adding a host
`requests.exceptions.SSLError: hostname '<ip>' doesn't match either of '<hostname>', '<hostname>.<domain>', '<ip>'`

I use a self signed certificate with an registered ca on the hosts for the rancher master server.

The req information of the SSL certificate looks like:
```
[req]
distinguished_name = req_distinguished_name
req_extensions = v3_req
prompt = no
[req_distinguished_name]
<C, ST, L, O, OU, CN filled. CN is an hostname>
[v3_req]
keyUsage = keyEncipherment, dataEncipherment
extendedKeyUsage = serverAuth
subjectAltName = @alt_names
[alt_names]
DNS.1 = <hostname>
DNS.2 = <hostname>.<domain>
IP = <ip>
```

When I use the `<hostname>` for the rancher master server everything is okay. Chrome and Firefox also accept the certificates (`https://<hostname>`, `https://<ip>` both are valid)
Use the `<ip>` the curious error message appears in the docker log.

Is the urllib3 version outdated? The source-code of urllib looks fine.  Is this an error or bug in urllib3 / request or is the version in the rancher script outdated?

Hope you can understand the problem.

versions:
rancher/os: 1.0.2
rancher/server: 1.6.2
rancher/agent: I don't know. Run the command copied from the web interface when click on Add Host.

**Comment by aemneina** [comment] 2017-06-17 19:53
SSL certs secure domains, not IP's... That's why you'd get an SSL error if trying to connect to an IP vs the domain name the cert matches.

**Comment by nesc58** [comment] 2017-06-19 07:40
@aemneina: The SANs of a certificate allow ip addresses. It is also documented in a RFC https://tools.ietf.org/html/rfc5280#section-4.2.1.6

The latest check in the urllib looks fine and should work:
```
if key == 'DNS':
    if host_ip is None and _dnsname_match(value, hostname):
        return
        dnsnames.append(value)
elif key == 'IP Address':
    if host_ip is not None and _ipaddress_match(value, host_ip):
        return
    dnsnames.append(value)
```

An other interesting error message is the following when I remove the `IP = <ip>` field of the certificate. Urllib accepts the certificate (I don't know why, because the ip is not signed) but now the rancher/agent needs the IP in a SAN field.
```
time="2017-06-12T13:43:20Z" level=info msg="Launching agent"
time="2017-06-12T13:43:20Z" level=info msg="https://<public-ip>/v1<token>"
time="2017-06-12T13:43:20Z" level=info msg="Listening for events on https://<public-ip>/v1"
time="2017-06-12T13:43:20Z" level=info msg="launching hostapi"
time="2017-06-12T13:43:20Z" level=info msg="Serialize compute requests: false, driver: overlay"
time="2017-06-12T13:43:20Z" level=error msg="Get https://<public-ip>/v1: x509: cannot validate certificate for <public-ip> because it doesn't contain any IP SANs"
time="2017-06-12T13:43:20Z" level=fatal msg="Exiting. Error: Get https://<public-ip>/v2-beta: x509: cannot validate certificate for <public-ip> because it doesn't contain any IP SANs"

```

On the one hand urllib/request raises a SSLException when use the IP field on the other hand (without the ip field) rancher/agent raises an error when the IP field is not used....

**Comment by superseb** [comment] 2017-10-27 15:15
Closing as duplicate of https://github.com/rancher/rancher/issues/8792, let me know if you don't agree

**Closed by superseb** 2017-10-27 15:15 UTC
Labels: area/server, kind/question

**Comment by michaelact** [comment] 2023-05-08 02:56
How I can disable the IP access to prevent client get SSL error, like `strict-sni-checking` in traefik?
https://doc.traefik.io/traefik/https/tls/#strict-sni-checking
