### ISSUE TITLE
[BUG] Project owners cannot create namespaces with PSA enabled with CIS 1.23 enabled

### ISSUE THREAD

**Issue by MKlimuszka** [rancher/rancher#44585] opened 2024-02-26 23:32 UTC
**Rancher Server Setup**
- Rancher version:  SUSE Rancher 2.7.9 

**Information about the Cluster**
RKE/RKE2/K3S version: rke2
Kubernetes version: 1.26

Issue description:
Users created with project ownership cannot create namespaces in said project under the following circumstances:

Local cluster has CIS 1.23 enabled

PSA enforcing is enabled when creating the namespace

**Business impact:**
Users need to be able to enforce security contexts.

**Troubleshooting steps:**
Tested under multiple instances now

**Repro steps:**

    Create local cluster with CIS 1.23
    Install Rancher
    Create project and user
    Assign user as project owner
    Attempt to create namespace in project with enforcing psa checked

**Workaround:**
Is workararound available and implemented? NO

**Actual behavior:**
Get error 'rancher.cattle.io.namespaces.create-non-kubesystem" denied the request: Unauthorized'

**Expected behavior:**
No error

SURE-7532

**Comment by MbolotSuse** [comment] 2024-02-29 19:40
I'm going to close this ticket. While I can reproduce the behavior, Rancher is working as intended in the current state. There is currently another issue #44402 which serves as a discussion point for changes to the current behavior. 

To elaborate further, Rancher currently requires users to have special permissions to change/set PSA labels on namespaces. These permissions are explained in both our [public docs site](https://ranchermanager.docs.rancher.com/reference-guides/rancher-webhook#application-fails-to-deploy-due-to-rancher-webhook-blocking-access) and in the [webhook docs](https://github.com/rancher/webhook/blob/release/v0.5/docs.md#psa-label-validation). Project Owners specifically lack the permissions to set a PSA label (including the enforce label identified in this issue). Allowing these users to set a PSA label would allow them to potentially impact the state of the entire cluster, so we don't allow this for project owners.

The recommended solution is to set defaults on the AdmissionConfiguration. An example is provided in the [public docs site](https://ranchermanager.docs.rancher.com/reference-guides/rancher-security/psa-restricted-exemptions). We are aware that this solution does not fit for all use cases, and as part of #44402 are considering alternative solutions.

**Closed by MbolotSuse** 2024-02-29 19:40 UTC
Labels: kind/bug, priority/1, internal, feature/charts-cis-benchmark, area/frameworks, team/frameworks
