### ISSUE TITLE
rancher server crashed with "[FATAL] k3s exited with: exit status 1"

### ISSUE THREAD

**Issue by soumyalj** [rancher/rancher#22819] opened 2019-09-12 03:55 UTC
Version: master-head

Steps:
1. Create a cluster with S3 backup config. Provide S3 bucket name, endpoint s3.amazonaws.com and do not provide access/secret keys
Cluster gets created successfully and snapshots fail as expected. 
After around 1 hour and 40 mins, rancher server crashed . 
Logs from rancher server below.

```
2019/09/12 01:20:42 [WARNING] [etcd] Failed to take one-time snapshot on host [167.71.245.110], exit code [1]: time="2019-09-12T01:20:41Z" level=fatal msg="failed to set s3 server: failed to check s3 bucket:soumyas3test, err:404 Not Found" 

2019/09/12 01:20:42 [ERROR] EtcdBackupController c-qlm7d/c-qlm7d-ms-vwn7r [etcdbackup-controller] failed with : [etcd-backup] failed to perform etcd backup: [etcd] Failed to take one-time snapshot on host [167.71.245.110], exit code [1]: time="2019-09-12T01:20:41Z" level=fatal msg="failed to set s3 server: failed to check s3 bucket:soumyas3test, err:404 Not Found" 

2019/09/12 01:21:59 http: TLS handshake error from 127.0.0.1:44156: EOF
E0912 01:38:01.737727       7 streamwatcher.go:109] Unable to decode an event from the watch stream: net/http: request canceled (Client.Timeout exceeded while reading body)
E0912 01:38:01.738215       7 streamwatcher.go:109] Unable to decode an event from the watch stream: net/http: request canceled (Client.Timeout exceeded while reading body)
E0912 01:38:01.738247       7 streamwatcher.go:109] Unable to decode an event from the watch stream: net/http: request canceled (Client.Timeout exceeded while reading body)
E0912 01:38:01.738448       7 streamwatcher.go:109] Unable to decode an event from the watch stream: net/http: request canceled (Client.Timeout

....
....
....

E0912 01:49:59.012557       7 streamwatcher.go:109] Unable to decode an event from the watch stream: net/http: request canceled (Client.Timeout exceeded while reading body)
2019/09/12 01:52:15 http: TLS handshake error from 127.0.0.1:44708: EOF
2019/09/12 01:52:15 http: TLS handshake error from 127.0.0.1:44706: EOF
2019/09/12 01:55:47 http: TLS handshake error from 127.0.0.1:44774: EOF
2019/09/12 02:05:24 http: TLS handshake error from 127.0.0.1:44988: EOF
2019/09/12 02:05:55 http: TLS handshake error from 127.0.0.1:44996: EOF
2019/09/12 02:11:56 http: TLS handshake error from 127.0.0.1:45130: EOF
2019/09/12 02:12:27 http: TLS handshake error from 127.0.0.1:45140: EOF
2019/09/12 02:12:57 http: TLS handshake error from 127.0.0.1:45142: EOF
2019/09/12 02:15:29 http: TLS handshake error from 127.0.0.1:45188: EOF
2019/09/12 02:20:03 http: TLS handshake error from 127.0.0.1:45290: EOF
2019/09/12 02:36:13 http: TLS handshake error from 127.0.0.1:45600: EOF
E0912 02:39:31.405804      31 server.go:252] lost master
lost lease
...
....

al tcp 127.0.0.1:6443: connect: connection refused
E0912 02:39:31.448958       7 reflector.go:270] github.com/rancher/norman/controller/generic_controller.go:175: Failed to watch *v3.RKEK8sServiceOption: Get https://localhost:6443/apis/management.cattle.io/v3/watch/rkek8sserviceoptions?resourceVersion=874&timeout=30m0s&timeoutSeconds=590: dial tcp 127.0.0.1:6443: connect: connection refused
E0912 02:39:31.449011       7 reflector.go:270] github.com/rancher/norman/controller/generic_controller.go:175: Failed to watch *v3.Project: Get https://localhost:6443/apis/management.cattle.io/v3/watch/projects?resourceVersion=2811&timeout=30m0s&timeoutSeconds=588: dial tcp 127.0.0.1:6443: connect: connection refused
E0912 02:39:31.449066       7 reflector.go:270] github.com/rancher/norman/controller/generic_controller.go:175: Failed to watch *v3.GlobalDNS: Get https://localhost:6443/apis/management.cattle.io/v3/watch/globaldnses?resourceVersion=481&timeout=30m0s&timeoutSeconds=320: dial tcp 127.0.0.1:6443: connect: connection refused
2019/09/12 02:39:31 [FATAL] k3s exited with: exit status 1

```

**Comment by moelsayed** [comment] 2019-09-17 17:23
Closing this as duplicate of #22841

**Closed by moelsayed** 2019-09-17 17:23 UTC
Labels: [zube]: Next Up, kind/bug-qa, team/ca
