### ISSUE TITLE
Reduce size of v3.App and v3.Catalog objects

### ISSUE THREAD

**Issue by rmweir** [rancher/rancher#32418] opened 2021-04-28 01:05 UTC
## Child Issues

- [ ] `v3.Catalog` https://github.com/rancher/rancher/issues/32938
- [ ] `v3.App` https://github.com/rancher/rancher/issues/32939

## Summary

**What kind of request is this (question/bug/enhancement/feature request):**
enhancement

**Description:**
Catalogs and apps can be enormous in size causes performance issues and other bugs. The [bitnami](https://charts.bitnami.com/bitnami) chart for example is about 1mb in size. For catalog size is largely due to recording the hash of each version of each charts on its status, at least for non git catalogs. One solution is to gzip certain fields, like chart version hashes, or only record the hash for the latest version of each chart on the status (both examples apply to catalogs specifically). Large object size in kubernetes 1.20 is leading to timeouts and high cpu consumption spikes, see related issues.

**Related issues:**
https://github.com/rancher/rancher/issues/32175
https://github.com/rancher/rancher/issues/31940
https://github.com/rancher/rancher/issues/31614
https://github.com/rancher/rancher/issues/32295

**Other details that may be helpful:**
Once solutions are implemented may want to tryout adding the bitnami catalog while using a 1.20 management cluster.

**Comment by nickgerace** [comment] 2021-05-17 19:51
https://github.com/rancher/rancher/pull/32746 addresses `v3.Catalog` size, but does not address `v3.App` size. Is there a reproducible scenario for very large `v3.App` sizes?

**Comment by nickgerace** [comment] 2021-06-04 21:25
Closing in favor of child issues since they have been prioritized differently:
- #32938
- #32939

**Closed by nickgerace** 2021-06-04 21:25 UTC
Labels: QA/M, [zube]: Working
