### ISSUE TITLE
[Backport release/v2.7] Init Node cannot be removed

### ISSUE THREAD

**Issue by Oats87** [rancher/rancher#43142] opened 2023-10-12 20:42 UTC
Backport: https://github.com/rancher/rancher/issues/42709

**Comment by Josh-Diamond** [comment] 2023-10-17 23:01
TIcket #43142 - Test Results - ✅ 
---

Reproduced on single-instance docker running Rancher `v2.7.6`:
1. Fresh install of Rancher `v2.7.6`
2. Provision a downstream AWS RKE2 cluster w/ 2 node pools - [`etcd + cp`, `wkr`] - with three nodes per pool
3. Once `active`, take a manual snapshot
4. Once snapshot is successfully captured and `active`, navigate to `Cluster Management > Edit Config` and make a modification to the `etcd + cp` node pool - [ I modified `Root Disk Size` ]
5. Reproduced - cluster enters `updating` state; init node hangs in `deleting` state, and the following Rancher logs are seen:
```log
[ERROR] [rkebootstrap] fleet-default/jkeslar-clusterr-bootstrap-template-<REDACTED>: cluster fleet-default/jkeslar-clusterr machine fleet-default/jkeslar-clusterr-pool1-<REDACTED>-<REDACTED> was still joined to deleting etcd machine fleet-default/jkeslar-clusterr-pool1-<REDACTED>-<REDACTED>
```

---

Validated on Rancher `v2.7-918fb36b3edaa8f305ee5b9d0c6c51ec52813bda-head`:

| Scenario | Test Case | Result |
|---|---|---|
| 1. | Provision downstream RKE2 cluster w/ 3 `etcd + cp` nodes and 3 `wkr` nodes => manually take snapshot => modify the `etcd + cp` node pool | ✅  |
| 2. | Provision downstream RKE2 cluster w/ 3 `etcd + cp` nodes and 3 `wkr` nodes => manually take snapshot => delete the init node | _pending_ |
| 3. | Provision downstream RKE2 cluster w/ 3 `etcd + cp` nodes and 3 `wkr` nodes => manually take snapshot => delete one `etcd/cp` node which is NOT the init node | Blocked https://github.com/rancher/rancher/issues/42895 |
| 4. | Restore local etcd backup - [`only etcd`] | Blocked https://github.com/rancher/rancher/issues/42895 |
| 5. | Restore local etcd backup - [`k8s version and etcd`] | Blocked https://github.com/rancher/rancher/issues/42895 |
| 6. | Restore local etcd backup - [`cluster config, k8s version and etcd`] | Blocked https://github.com/rancher/rancher/issues/42895 |
| 7. | Restore s3 etcd backup - [`only etcd`] | Blocked https://github.com/rancher/rancher/issues/42895 |
| 8. | Restore s3 etcd backup - [`k8s version and etcd`] | Blocked https://github.com/rancher/rancher/issues/42895 |
| 9. | Restore s3 etcd backup - [`cluster config, k8s version and etcd`] | Blocked https://github.com/rancher/rancher/issues/42895 |
| 10. | Take snapshot, upgrade the K8s version, modify `etcd+cp` node pool, restore to snapshot | Blocked https://github.com/rancher/rancher/issues/42895 |
| 11. | Disable automatic snapshots | _pending_ |
| 12. | Restore to same snapshot multiple times  - (at least 3 times) | Blocked https://github.com/rancher/rancher/issues/42895 |

---

Scenario 1 - ✅ 
1. Fresh install of Rancher `v2.7-head`
2. Provision a downstream RKE2 cluster w/ 3 `etcd+cp` nodes and 3 `wkr` nodes
3. Once `active`, manually take a snapshot
4. Once snapshot is successfully captured, navigate to `Cluster Management > Edit Config` and modify the `etcd+cp` pool - [I changed the Root Disk Size]
5. Verified - cluster successfully updates and comes up `active`; as expected

---

Scenario 2 - ✅ 
1. Fresh install of Rancher `v2.7-head`
2. Provision a downstream RKE2 cluster w/ 3 `etcd+cp` nodes and 3 `wkr` nodes
3. Once `active`, manually take a snapshot
4. Once snapshot is successfully captured, delete the init node
5. Verified - cluster successfully removes the node from the cluster + a new node is provisioned in its place; as expected

---

Scenario 3 - ✅ 
1. Fresh install of Rancher `v2.7-head`
2. Provision a downstream RKE2 cluster w/ 3 `etcd+cp` nodes and 3 `wkr` nodes
3. Once `active`, manually take a snapshot
4. Once snapshot is successfully captured, delete a node from the `etcd+cp` pool, but NOT the init node
5. Verified - cluster successfully removes the node from the cluster + a new node is provisioned in its place; as expected

---

Snap/restore checks, were taken up as part of the regression check suite for this issue, and https://github.com/rancher/rancher/issues/42895 was encountered, blocking the snap/restore regression checks at this time.

Due to this issue no longer being hit, I'm closing this out as validated, and snap/restore issue encountered will be further tracked and tested in https://github.com/rancher/rancher/issues/42895

**Closed by Josh-Diamond** 2023-10-17 23:01 UTC
Labels: [zube]: QA Working, team/area2, area/capr

**Comment by Josh-Diamond** [comment] 2023-10-25 17:54
Ticket #43142 - Test Results - ✅ 
---

Re-tested on Rancher `v2.7.9-966bb7bd86f7dbf62b5a10271013ebb15e556e96-head`:

| Scenario | Test Case | Result |
|---|---|---|
| 1. | Provision downstream RKE2 cluster w/ 3 `etcd + cp` nodes and 3 `wkr` nodes => manually take snapshot => modify the `etcd + cp` node pool | ✅  |
| 2. | Provision downstream RKE2 cluster w/ 3 `etcd + cp` nodes and 3 `wkr` nodes => manually take snapshot => delete the init node | ✅  |
| 3. | Provision downstream RKE2 cluster w/ 3 `etcd + cp` nodes and 3 `wkr` nodes => manually take snapshot => delete one `etcd/cp` node which is NOT the init node | ✅  |

---

Scenario 1 - ✅ 
1. Fresh install of Rancher `v2.7.9-head`
2. Provision a downstream RKE2 cluster w/ 3 `etcd+cp` nodes and 3 `wkr` nodes
3. Once `active`, manually take a snapshot
4. Once snapshot is successfully captured, navigate to `Cluster Management > Edit Config` and modify the `etcd+cp` pool - [I changed the Root Disk Size]
5. Verified - cluster successfully updates and comes up `active`; as expected

---

Scenario 2 - ✅ 
1. Fresh install of Rancher `v2.7.9-head`
2. Provision a downstream RKE2 cluster w/ 3 `etcd+cp` nodes and 3 `wkr` nodes
3. Once `active`, manually take a snapshot
4. Once snapshot is successfully captured, delete the init node
5. Verified - cluster successfully removes the node from the cluster + a new node is provisioned in its place; as expected

---

Scenario 3 - ✅ 
1. Fresh install of Rancher `v2.7.9-head`
2. Provision a downstream RKE2 cluster w/ 3 `etcd+cp` nodes and 3 `wkr` nodes
3. Once `active`, manually take a snapshot
4. Once snapshot is successfully captured, delete a node from the `etcd+cp` pool, but NOT the init node
5. Verified - cluster successfully removes the node from the cluster + a new node is provisioned in its place; as expected
