### ISSUE TITLE
AKS spinup in switzerlandnorth fails

### ISSUE THREAD

**Issue by tuxpeople** [rancher/rancher#31154] opened 2021-02-05 10:32 UTC
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
Create a new AKS cluster in Rancher and use switzerlandnorth as Region

**Result:**
![aks4](https://user-images.githubusercontent.com/1506076/107021979-1a185880-67a5-11eb-9a1e-3efb31832470.png)

**Other details that may be helpful:**
If you create such a cluster from Azure portal, it's no problem to have the log analytics dashboard in switzerlandnorth:
![b5302939-e426-4130-9f8e-03b9fddf663c](https://user-images.githubusercontent.com/1506076/107022327-885d1b00-67a5-11eb-9462-d3b5a90ff9ef.jpg)

**Environment information**
Rancher 2.5.5 in single-node RKE Cluster

**Comment by tuxpeople** [comment] 2021-07-08 13:46
Dear bot, as nobody ever looked at this issue, I doubt that it's fixed.

**Comment by superseb** [comment] 2021-07-08 14:45
@tuxpeople This seems to be fixed in the next upcoming minor release (v2.6.0), see https://github.com/rancher/aks-operator/blob/master/pkg/aks/check.go. Are you looking for this to be fixed in the current release as well (v2.5.x)?

**Comment by tuxpeople** [comment] 2021-07-08 14:48
Hi @superseb I'm fine with 2.6 👍  I'm happy that this is going to be fixed. I just thought nobody cares because nobody ever commented here.

**Comment by superseb** [comment] 2021-07-08 15:54
I think this needs to be updated in 2.5.x regardless, I'll take a look at it.

We started using the bot to at least make sure that the issues are still valid so we don't have so many to go through (as you said, it's growing)

**Comment by davidnuzik** [comment] 2021-09-09 19:11
**My checks PASSED**
 
**Reproduction Steps:**

Not required.

-----
 
**Validation Environment:**

Rancher version: v2.5-head `b2f17e430` pulled 9/9/21 11:20am Pacific
Rancher cluster type: single-node docker install
Docker version: 20.10
 
Downstream cluster type: AKS
Downstream K8s version: v1.20.9 (Switzerland north region)
 
**Validation steps:**

1. Try to provision an AKS cluster in the Switzerland north region.
2. This cluster successfully comes up.
3. All resources in Azure appear to be in the correct region.

![image](https://user-images.githubusercontent.com/45179589/132747046-9deecb94-0497-4cbf-9fec-b23de0f0b5da.png)
![image](https://user-images.githubusercontent.com/45179589/132747363-0fc8f3b1-6d38-4796-9494-a8cbe1b3431c.png)


4. I can deploy a workload successfully.
5. I can delete/tear down the cluster in Rancher successfully.

**Closed by davidnuzik** 2021-09-09 19:11 UTC
Labels: [zube]: QA Working
