### ISSUE TITLE
Can not provision ARM worker node for K3s via Rancher UI

### ISSUE THREAD

**Issue by rajha-korithrien** [rancher/rancher#36463] opened 2022-02-09 16:45 UTC
**Rancher Server Setup**
- Rancher version: 2.6.3
- Installation option (Docker install/Helm Chart): Helm Chart onto RKE2 v1.22.6+rke2r1, go1.16.10b7
- Rancher UI is behind an out of cluster Nginx Proxy

**Information about the Cluster**
- Kubernetes version: K3s `v1.22.5+k3s2` same behavior occurs with K3s `v1.21.9+k3s1`
- Cluster Type (Local/Downstream): Downstream
  * Custom - etcd and control plane are on amd64 nodes, trying to add a worker on aarch64 node

**User Information**
- What is the role of the user logged in? Admin

**Describe the bug**
This is very similar to what is described in #34966.

Logs of the `rancher-system-agent` service on the worker node show:
```
Feb  8 21:03:37 mach-1 rancher-system-agent[13353]: time="2022-02-08T21:03:37Z" level=info msg="Extracting image rancher/system-agent-installer-k3s:v1.22.5-k3s2 to directory /var/lib/rancher/agent/wor
k/20220208-210337-applied.plan/7a64b0fcf7b2b4e994d7303ccc3f064eba67a880a30894d6b5b1a38316f41b37_0"
Feb  8 21:03:37 mach-1 rancher-system-agent[13353]: time="2022-02-08T21:03:37Z" level=info msg="Using private registry config file at /etc/rancher/agent/registries.yaml"
Feb  8 21:03:37 mach-1 rancher-system-agent[13353]: time="2022-02-08T21:03:37Z" level=info msg="Pulling image index.docker.io/rancher/system-agent-installer-k3s:v1.22.5-k3s2"
Feb  8 21:03:37 mach-1 rancher-system-agent[13353]: time="2022-02-08T21:03:37Z" level=error msg="error while staging: no child with platform linux/arm64 in index rancher/system-agent-installer-k3s:v1.
22.5-k3s2: failed to get image index.docker.io/rancher/system-agent-installer-k3s:v1.22.5-k3s2"
```

**To Reproduce**
1) Log into the Rancher UI and create a K3s cluster (just etcd and control plane node first, AMD64 based nodes).
2) Use the provided command to provision etcd and control plane nodes. Wait for them to come up.
3) Then add a new node with just the worker role to get the provision command.
4) Run the worker node provision command on an ARM based node in our case `5.1.0-trunk-arm64 #1 SMP Debian 5.1.10-1~exp1sr2 (2019-06-18) aarch64`

**Result**
The worker node never provisions.

**Expected Result**
The worker node should complete provisioning.

**Additional context**
The Docker Hub repo for `rancher/system-agent-installer-k3s` doesn't list any aarch64 images.
Given that K3s is fully supported on ARM and one can manually setup K3s on arm via `curl -sfL https://get.k3s.io | sh -`
It is expected that install via Rancher UI to ARM should work.
If we use all AMD64 worker nodes the install works as expected.

Thanks for taking the time to look! Understand that K3s support is still "tech preview", but we can't preview it when we can't use it to install to our ARM edge devices :-)

**Comment by pixelchrome** [comment] 2022-04-11 05:17
Any update or feedback?

**Comment by hwinkel** [comment] 2022-05-08 06:41
I just come to the same issue while trying to deploy a raspi k3s cluster with RKE2 via rancher custom registration.

`no child with platform linux/arm in index rancher/system-agent-installer-k3s`

happend with latest rancher 2.6.4

**Comment by n1849778** [comment] 2022-05-09 20:32
We have the same problem while trying to deploy a Raspberry PI into a RKE cluster. It gets hung up on the provisioning step. Some forums said to wait for a few hours, and I did waited for at least 12 hours an the node was still stuck in provisioning. Its been quite a journey for us here. I read somewhere that Raspberry PI, for for that matter of fact any Single-Board Computer (SBC) with and ARM64 processor is not support by RKE. Is that true? And I have to adopt K3S cluster for any ARM64 processor? With K3S and ARM64, we have not been having any luck as well. I was wondering if there has been any success stories with K3S and ARM64? This web site does say that K3S supports ARM64 and ARMv7 processors.

https://k3s.io/

Just wanted to see if anyone was successful with creating ARM64 nodes in K3S. And if you successfully created an ARM64 node in K3S how did you do it?

**Comment by PhakornKiong** [comment] 2022-05-29 14:57
> We have the same problem while trying to deploy a Raspberry PI into a RKE cluster. It gets hung up on the provisioning step. Some forums said to wait for a few hours, and I did waited for at least 12 hours an the node was still stuck in provisioning. Its been quite a journey for us here. I read somewhere that Raspberry PI, for for that matter of fact any Single-Board Computer (SBC) with and ARM64 processor is not support by RKE. Is that true? And I have to adopt K3S cluster for any ARM64 processor? With K3S and ARM64, we have not been having any luck as well. I was wondering if there has been any success stories with K3S and ARM64? This web site does say that K3S supports ARM64 and ARMv7 processors.
> 
> https://k3s.io/
> 
> Just wanted to see if anyone was successful with creating ARM64 nodes in K3S. And if you successfully created an ARM64 node in K3S how did you do it?

I managed to provision k3s into raspberry pi 4 (1 master, 1 node, k3 version `v1.23.6+k3s1`) following the tutorial from
https://www.youtube.com/watch?v=X9fSMGkjtug&t=265s

However creating a cluster doesn't work and give similar error to what is being reported above

I'm using `rancher version v2.6.5 (c4d59fa88)` from docker

**Comment by nlucansk** [comment] 2022-06-30 06:08
There are some ARM builds visible on dockerhub but those are still not present in the UI 
![image](https://user-images.githubusercontent.com/51444462/176604545-631d14a2-f6d7-437b-b3d1-63d8bc2407c3.png)
![image](https://user-images.githubusercontent.com/51444462/176604735-6a6e2e96-3595-444c-b531-6c42f66a0f6f.png)

**Comment by rajha-korithrien** [comment] 2022-08-30 14:33
This message is mostly to keep the stale bot happy ;-)

Has anyone gotten a K3s cluster to deploy on arm64 via the provision command given in the Rancher 2.6.x UI?
My team has not been in a position to try for a while since Rancher 2.6.4, has anyone tried in 2.6.7 (which is the latest at the moment)?

**Comment by theOxifier** [comment] 2022-09-28 04:09
I am on 2.6.5 and it isn't working for me either.

**Comment by snasovich** [comment] 2022-10-03 20:48
Closing as duplicate of https://github.com/rancher/rancher/issues/36463

**Closed by snasovich** 2022-10-03 20:48 UTC
