### ISSUE TITLE
Chart 2.8.6 is not released

### ISSUE THREAD

**Issue by berkerol** [rancher/rancher#46614] opened 2024-08-09 08:57 UTC
2.8.6-rc3 and 2.9.0 are released but 2.8.6 is not released. Can you also release that?

I can't update to 2.9.0 because of a known bug so at least I want to get 2.8.6.

**Comment by jcox10** [comment] 2024-08-09 21:26
https://github.com/rancher/rancher/issues/46562

**Comment by riuvshyn** [comment] 2024-08-12 12:42
same issue here, missing 2.8.6 image  and helm chart version

**Comment by sicko583** [comment] 2024-08-13 08:59
I can not even find version higher than v2.8.3 in repo search:

helm search repo rancher

NAME                    CHART VERSION   APP VERSION     DESCRIPTION
rancher-latest/rancher  2.8.3           v2.8.3          Install Rancher Server to manage Kubernetes clu...
rancher-stable/rancher  2.8.3           v2.8.3          Install Rancher Server to manage Kubernetes clu...

**Comment by riuvshyn** [comment] 2024-08-13 09:00
I have noticed that this bug fix version mentioned Prime version, build is only available for Rancher Prime customers, through the Rancher Prime registry.

subscription for bug fixes 🙃

**Comment by richard-cox** [comment] 2024-08-13 09:08
Closing as duplicate of https://github.com/rancher/rancher/issues/46562

Generally...
- As 2.8.0 has been released new 2.7 patch releases are Prime only
- As 2.9.0 has also now been released new 2.8 patch releases will also be Prime only
- The latest minor build will contain all bug fixes, security updates, etc. This is currently 2.9.0

**Closed by richard-cox** 2024-08-13 09:08 UTC
Labels: kind/bug

**Comment by harridu** [comment] 2024-08-30 08:17
Sorry 2 say, but this is mean. The community and Suse are working together to find and fix bugs in Rancher. If Suse restricts access to the fixed stable version, then this seems counterproductive and discouraging.

**Comment by richard-cox** [comment] 2024-09-02 15:11
@harridu bug fixes are available in the latest minor release line. Not all fixes are backported to prime only releases, and it's rare features ever are. Please also not the stable / latest helm repo concepts are under review and there may be changes following it.
