### ISSUE TITLE
Rancher catalog seems to no longer accept sub folders with more than two digtis

### ISSUE THREAD

**Issue by wundram** [rancher/rancher#4277] opened 2016-04-02 20:26 UTC
Rancher Version: 1.0.0

Docker Version: 1.10.3

OS: Ubuntu

Steps to Reproduce: Create a catalog template with a long number for the versioned folder.   We use the timestamp so we know we will have a monotonically increasing number without having to check the previous value.  As our template entries are automatically constructed by our build system

Results: 
If the subfolder is 1459436366/  the catalog picks up the compose files as 59436366/docker-compse.yml instead of docker-compose.yml which would be the case if the subfolder was 0/.   This is new behaviour in 1.0.0 is breaking our build system.   The result is that we cannot deploy any stack from our catalog

Expected:
Any valid numeric subfolder in the catalog should be accepted.

**Comment by vincent99** [comment] 2016-04-02 20:53
Duplicate of #4195 , will be fixed in 1.0.1

**Closed by vincent99** 2016-04-02 20:53 UTC
