### ISSUE TITLE
Not able to create ingresses on amazon ec2 node driver clusters in an HA rancher on 1.20 cluster

### ISSUE THREAD

**Issue by anupama2501** [rancher/rancher#35754] opened 2021-12-04 02:32 UTC
Information about the Cluster
**Rancher Server Setup**
- Rancher version: v2.5.11
- Installation option (Docker install/Helm Chart): Helm Chart
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): RKE1, v1.20.12-rancher1-2, 1.2.14
- Proxy/Cert Details: Selfsigned

**Information about the Cluster**
- Kubernetes version: v1.20.12
- Cluster Type (Local/Downstream): `Downstream node driver 1 worker, 1 etcd, 1 cp RKE1`

**Describe the bug**
Creation of ingress on an AWS node driver cluster created on a rancher HA server does not go through and errors out with Failed calling webhook error. More details in the result and additional info. 

**To Reproduce**
1. Create a rancher HA server on v2.5.11
2. Create a downstream RKE1 node driver Amazon EC2 cluster with any node count
3. From any project create a workload 
4. Create an ingress pointing to this workload

**Result**
The ingress creation does not go through and it errors out 
```
baseType: "error"
code: "InternalError"
message: "Internal error occurred: failed calling webhook \"validate.nginx.ingress.kubernetes.io\": Post \"https://ingress-nginx-controller-admission.ingress-nginx.svc:443/networking/v1beta1/ingresses?timeout=10s\": context deadline exceeded"
status: 500
type: "error"
```

**Expected Result**
Expected the ingress creation to go through without any error.

**Additional context**
1. This is not seen on node driver RKE DO clusters on HA or custom clusters 
2. Not seen on docker install DO,Amazon ec2 or custom clusters.
3. Only seen on Amazon ec2 node driver HA.
4. Also not seen on clusters on k8s `v1.19.16`

Errors seen in the rancher logs:
```


 7 warnings.go:80] extensions/v1beta1 Ingress is deprecated in v1.14+, unavailable in v1.22+; use networking.k8s.io/v1 Ingress
W1204 02:19:48.667464       7 warnings.go:80] extensions/v1beta1 Ingress is deprecated in v1.14+, unavailable in v1.22+; use networking.k8s.io/v1 Ingress
W1204 02:20:04.308015       7 warnings.go:80] apiextensions.k8s.io/v1beta1 CustomResourceDefinition is deprecated in v1.16+, unavailable in v1.22+; use apiextensions.k8s.io/v1 CustomResourceDefinition
W1204 02:22:02.682439       7 warnings.go:80] extensions/v1beta1 Ingress is deprecated in v1.14+, unavailable in v1.22+; use networking.k8s.io/v1 Ingress
W1204 02:26:15.307942       7 warnings.go:80] apiextensions.k8s.io/v1beta1 CustomResourceDefinition is deprecated in v1.16+, unavailable in v1.22+; use apiextensions.k8s.io/v1 CustomResourceDefinition


2021/12/04 02:04:45 [ERROR] error syncing 'ingress-ip-domain': handler copy-settings: the server could not find the requested resource, requeuing
2021/12/04 02:04:45 [ERROR] error syncing 'install-uuid': handler copy-settings: the server could not find the requested resource, requeuing
2021/12/04 02:04:45 [ERROR] error syncing 'ingress-ip-domain': handler copy-settings: the server could not find the requested resource, requeuing
2021/12/04 02:04:45 [ERROR] error syncing 'install-uuid': handler copy-settings: the server could not find the requested resource, requeuing
2021/12/04 02:04:45 [ERROR] error syncing 'ingress-ip-domain': handler copy-settings: the server could not find the requested resource, requeuing
```

Errors seen in ingress-controller:
```
E1204 02:26:15.592042       6 server.go:77] "Failed to decode request body" err="couldn't get version/kind; json parse error: unexpected end of JSON input"
2021/12/04 02:26:16 http: TLS handshake error from :38364: read tcp 172.31.13.232:8443->:38364: read: connection reset by peer
E1204 02:26:17.685127       6 server.go:77] "Failed to decode request body" err="couldn't get version/kind; json parse error: unexpected end of JSON input"
E1204 02:26:17.758252       6 server.go:77] "Failed to decode request body" err="couldn't get version/kind; json parse error: unexpected end of JSON input"
 - - [04/Dec/2021:02:26:45 +0000] "GET /v3/connect/config HTTP/2.0" 200 19691 "-" "Go-http-client/2.0" 2902 0.010 [cattle-system-rancher-80] [] 10.42.0.6:80 19704 0.012 200 69048a76b18c5e7762850db3ecb19c5d
 - - [04/Dec/2021:02:27:40 +0000] "GET /v3/connect/config HTTP/2.0" 200 19708 "-" "Go-http-client/2.0" 2900 0.007 [cattle-system-rancher-80] [] 10.42.2.6:80 19721 0.008 200 73e8898aea23c402278561bdbec31eaa
```

**Comment by deniseschannon** [comment] 2021-12-05 16:00
@samkulkarni20 Can we confirm that this is still an active issue on 2.5-head?

**Comment by doflamingo721** [comment] 2021-12-09 10:41
@anupama2501 This issue is working as expected on 2.5 head.

Setup configuration:

**Rancher server setup**:

- Installation option : Helm chart.
- If Helm Chart, Kubernetes cluster and version : RKE1, rke:1.2.15-rc1, kubernetes:v1.20.13-rancher1-1

**Information about the Cluster**:

- Kubernetes version: v1.20.12
- Cluster Type (Local/Downstream): Downstream node driver 1 worker, 1 etcd, 1 cp RKE1

**Steps taken to validate**:

1. Create a rancher HA server on 2.5-head
2. Create a downstream RKE1 node driver Amazon EC2 cluster with any node count
3. Create a nginx deployment
4. Create an ingress pointing to this nginx workload.
The service must be accessible at <node_ip>/index.html

**Result**:
The ingress creation goes through without any errors.

cc: @deniseschannon @samkulkarni20

**Comment by sowmyav27** [comment] 2021-12-13 01:28
**This issue is seen on 2.6-head commit id: `e62e1ae`**

- Cluster - AWS EC2 rke1 k8s version - v1.20.13
- Ingress created through v2 API gives the error:

```
Internal error occurred: failed calling webhook "validate.nginx.ingress.kubernetes.io": Post "https://ingress-nginx-controller-admission.ingress-nginx.svc:443/networking/v1beta1/ingresses?timeout=10s": context deadline exceeded
```

**Comment by anupama2501** [comment] 2021-12-13 05:25
Seeing this on v2.6.2 k8s 1.19.16-rancher1-2 AWS node driver SLES and post upgrading the rancher server to 2.6-head e62e1ae on the cluster
But not on fresh install of the cluster AWS node driver SLES on k8s 1.19.16-rancher1-2 on 2.6-head e62e1ae.

**Comment by sgapanovich** [comment] 2021-12-13 19:27
Couldn't reproduce the issue with the following set up:

Rancher version: 2.5.11
Rancher cluster type: HA
Docker version: 20.10

Downstream cluster type: aws ec2 node cluster
Downstream K8s version: 1.20.12

I have two  downstream clusters: rhel and ubuntu (3etcd, 2 cp, 3 workers)

----------

### Testing: ###

1. Create a rancher HA server on 2.5.11
2. Create a downstream RKE1 node driver Amazon EC2 cluster with any node count (see info about clusters above)
3. Create a deployment
4. Create an ingress pointing to this workload
    ingresses are created 
    i can curl services
![2 5 11](https://user-images.githubusercontent.com/40282141/145874861-225e9982-ed7a-4565-8a49-194e648d992e.jpg)

5. Upgrade
6. i still can curl services
    ![curl](https://user-images.githubusercontent.com/40282141/145875261-381afaca-ba26-4e06-95a3-52d955dff02d.jpg)

NOTE:
Running automation jobs for pre-upgrade/post-upgrade which create and check Ingresses passed for both downstream cluster

**Comment by cmurphy** [comment] 2021-12-14 00:50
I wasn't able to reproduce this on 2.6. This is what I tried, guided by [this](https://github.com/rancher/rancher/issues/35754#issuecomment-992122600):

1. Installed rancher v2.6.2 on single-node k3s cluster with helm chart
2. Created a single-node RKE v1.19.6-rancher1-2 cluster on Amazon EC2 infrastructure provider
- I tried using the default AMI and also tried overriding with `ami-0174313b5af8423d7` which is the public SLES 15 SP2 image
3. Navigated to the Ember UI
4. Created a workload using image `nginx:latest` and exposing port 80
5. Created an ingress resource with cluster IP pointing to the workload
6. Workload and ingress came up successfully, clicking the ingress URL correctly forwards me to the nginx welcome page
7. Upgraded Rancher to v2.6-head
8. Existing ingress still works
9. Created a second ingress which also works
10. No errors seen in the rancher logs or ingress controller logs

Is there anything else I might be missing that could reproduce this?

**Comment by cmurphy** [comment] 2021-12-15 00:04
I was able to reproduce this in rancher. The trick seems to be using a cluster with more than 2 nodes.

I was also able to reproduce this without rancher, with rke alone. So I think this issue should be transferred to the rke team.

Repro steps for RKE alone:

1. Create two EC2 nodes
2. Create an rke cluster with cluster.yml:
```
nodes:
    - address: <addr>.us-west-2.compute.amazonaws.com
      user: ubuntu
      role:
        - controlplane
        - etcd
      ssh_key_path: /home/colleen/Downloads/colleen-ec2.pem
    - address: <addr>.us-west-2.compute.amazonaws.com
      user: ubuntu
      role:
        - worker
      ssh_key_path: /home/colleen/Downloads/colleen-ec2.pem
services:
    etcd:
        snapshot: true
        creation: 6h
        retention: 24h
kubernetes_version: v1.20.13-rancher1-1
ingress:
    provider: nginx
```
3. Create workload
```
$ kubectl create deploy nginx --image=nginx:latest --port=80
deployment.apps/nginx create
```
4. Create service
```
$ kubectl create svc clusterip nginx --tcp=80:80
service/nginx created
```
5. Create ingress
```
$ cat ingress.yaml 
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: test1
  namespace: default
spec:
  rules:
  - host: test1.example.com
    http:
      paths:
      - backend:
          service:
            name: nginx
            port:
              number: 80
        path: /
        pathType: ImplementationSpecific
$ kubectl apply -f ingress.yaml 
Error from server (InternalError): error when creating "ingress.yaml": Internal error occurred: failed calling webhook "validate.nginx.ingress.kubernetes.io": Post "https://ingress-nginx-controller-admission.ingress-nginx.svc:443/networking/v1beta1/ingresses?timeout=10s": context deadline exceeded
```
Also happens with `extensions/v1beta1` and `networking.k8s.io/v1beta`:
```
$ cat ingress.yaml 
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: test1
  namespace: default
spec:
  rules:
  - host: test1.example.com
    http:
      paths:
      - backend:
          serviceName: nginx
          servicePort: 80
        path: /
$ kubectl apply -f ingress.yaml 
Warning: extensions/v1beta1 Ingress is deprecated in v1.14+, unavailable in v1.22+; use networking.k8s.io/v1 Ingress
Error from server (InternalError): error when creating "ingress.yaml": Internal error occurred: failed calling webhook "validate.nginx.ingress.kubernetes.io": Post "https://ingress-nginx-controller-admission.ingress-nginx.svc:443/networking/v1beta1/ingresses?timeout=10s": context deadline exceeded
```

Extending the timeout in the `ingress-nginx-admission` validatingwebhookconfiguration doesn't help, nor does changing the `apiGroups` or `apiVersions` setting.

This issue seems to be known and unsolved in the upstream ingress-nginx controller: https://github.com/kubernetes/ingress-nginx/issues/5401

**Comment by cmurphy** [comment] 2021-12-15 03:48
Some more debugging information: there's a connection issue between the API server docker container and the nginx-ingress admission controller service. On `v1.20.13-rancher1-1` and `v1.20.12-rancher1-1`, where it's not working:

```
$ kubectl -n ingress-nginx get svc ingress-nginx-controller-admission
NAME                                 TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)   AGE
ingress-nginx-controller-admission   ClusterIP   10.43.127.209   <none>        443/TCP   37m
$ docker exec -it kube-apiserver curl -ivk https://10.43.127.209
*   Trying 10.43.127.209:443...
* TCP_NODELAY set
* connect to 10.43.127.209 port 443 failed: Connection timed out
* Failed to connect to 10.43.127.209 port 443: Connection timed out
* Closing connection 0
curl: (28) Failed to connect to 10.43.127.209 port 443: Connection timed out
```

On `v1.21.6-rancher1-1`, where it is working:

```
$ kubectl -n ingress-nginx get svc ingress-nginx-controller-admission
NAME                                 TYPE        CLUSTER-IP     EXTERNAL-IP   PORT(S)   AGE
ingress-nginx-controller-admission   ClusterIP   10.43.102.67   <none>        443/TCP   2m2s
$ docker exec -it kube-apiserver curl -ivk https://10.43.102.67
*   Trying 10.43.102.67:443...
* TCP_NODELAY set
* Connected to 10.43.102.67 (10.43.102.67) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/certs/ca-certificates.crt
  CApath: /etc/ssl/certs
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.3 (IN), TLS handshake, Encrypted Extensions (8):
* TLSv1.3 (IN), TLS handshake, Certificate (11):
* TLSv1.3 (IN), TLS handshake, CERT verify (15):
* TLSv1.3 (IN), TLS handshake, Finished (20):
* TLSv1.3 (OUT), TLS change cipher, Change cipher spec (1):
* TLSv1.3 (OUT), TLS handshake, Finished (20):
* SSL connection using TLSv1.3 / TLS_AES_128_GCM_SHA256
* ALPN, server accepted to use http/1.1
* Server certificate:
*  subject: O=nil2
*  start date: Dec 15 03:31:33 2021 GMT
*  expire date: Nov 21 03:31:33 2121 GMT
*  issuer: O=nil1
*  SSL certificate verify result: unable to get local issuer certificate (20), continuing anyway.
> GET / HTTP/1.1
> Host: 10.43.102.67
> User-Agent: curl/7.68.0
> Accept: */*
> 
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
* Mark bundle as not supporting multiuse
< HTTP/1.1 400 Bad Request
HTTP/1.1 400 Bad Request
< Date: Wed, 15 Dec 2021 03:42:46 GMT
Date: Wed, 15 Dec 2021 03:42:46 GMT
< Content-Length: 0
Content-Length: 0

< 
* Connection #0 to host 10.43.102.67 left intact
```

So maybe some problem with the CNI in rke.

**Comment by cmurphy** [comment] 2021-12-15 17:22
Additional notes: seen consistently on EC2 in us-west-2, not seen on GCP or DO. Still seen on EC2 when switching the CNI to Calico from Canal:

```
...
network:
    plugin: calico
    calico_cloud_provider: aws
```

**Comment by cmurphy** [comment] 2021-12-16 00:49
Workaround summary for release notes:

On custom clusters with two or more nodes provisioned using the Amazon EC2 infrastructure provider using default settings, a configuration problem causes creation of Ingress resources to fail. Options to work around this are:
1. Select a cluster version of 1.21 or greater or upgrade the cluster to version v1.21 or greater.
2. In the EC2 node template, when configuring security groups, instead of selecting "Standard: Automatically create a rancher-nodes group", manually create the security group in the AWS console [following the documented port requirements](https://rancher.com/docs/rancher/v2.6/en/installation/requirements/ports/#ports-for-rancher-server-nodes-on-rke) and then additionally allowing incoming access to port 8443 from within the security group, and select that group in "Choose one or more existing groups" in Rancher.

**Comment by superseb** [comment] 2021-12-16 08:54
Pretty sure this is because the fix (https://github.com/rancher/rke/pull/2626) we implemented in RKE for this issue was not backported/changed scope as it was added for k8s 1.21 and up but the NGINX ingress version which was initially only used in k8s 1.21 and up was backported to older versions but the fix was not backported.

The fix here is to change the version scope from k8s to NGINX ingress and then scope it to`>=0.48.0` (based on the templates) and backport it to Rancher 2.5/RKE 1.2

**Comment by anupama2501** [comment] 2022-01-14 23:47
I see this issue on 2.5.12-rc4, SLES15-sp3 AMI on an AWS node driver cluster with 3 worker, 1 etcd, 1 cp, k8s version `v1.19.16-rancher1-2`

**Comment by snasovich** [comment] 2022-02-03 22:55
Moving to Team Area 2 to re-triage.

**Comment by snasovich** [comment] 2022-02-15 19:32
This issue should no longer be reproducible on 2.6.3 + latest versions from Jan 2022 KDM release (from 2/8/2022).
To fix it in 2.5.x, we would need to backport the fix from https://github.com/rancher/rancher/issues/35754#issuecomment-995566492 to RKE 1.2 and release new version of 2.5.x as RKE 1.2 is vendored in.
Since 2.5.x is EOM (end of maintenance) at this time, it's proposed to close this issue.

@anupama2501 (cc: @sowmyav27), could you please verify this is no longer an issue in 2.6.3 + latest versions from Jan 2022 KDM release and close this issue then?

**Comment by sowmyav27** [comment] 2022-03-14 14:21
@rishabhmsra @vivek-infracloud As mentioned by Sergey in [this](https://github.com/rancher/rancher/issues/35754#issuecomment-1040704576) comment, could you please verify this is no longer an issue in 2.6.3 + latest versions from Jan 2022 KDM release and close this issue then?

**Comment by rishabhmsra** [comment] 2022-03-17 12:40
Validated this on rancher v2.6.3 HA setup.

**Rancher Server Setup**
- Rancher version: v2.6.3
- Installation option (Docker install/Helm Chart): Helm Chart
    - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): RKE1, k8s:v1.22.6, rke:1.3.7

**Steps followed :**
- Provisioned 3 k8s `v1.22.6-rancher1-1`, `v1.21.9-rancher1-1`, `v1.20.15-rancher1-1` clusters -> ec2 noder driver RKE1 `(1-cp, 1-w, 1-etcd)`
- Deployed nginx with cluster Ip (port 80) in default ns on all downstream clusters.
- Created ingress pointing to nginx. Ingress creation was successful.
- Accessed `<worker-node-ip>/index.html` -> getting the nginx welcome page

**Result:**
- Ingress creation was successful and was able to access the nginx.

**Closed by rishabhmsra** 2022-03-17 12:40 UTC
Labels: area/ingress, kind/bug-qa, [zube]: To Test, team/area2
