### ISSUE TITLE
Can not delete node

### ISSUE THREAD

**Issue by yoke88** [rancher/rancher#13055] opened 2018-04-25 05:36 UTC
*Can not delete node in ui, the delete button show the forbidden icon*

![default](https://user-images.githubusercontent.com/3146226/39227878-9f9ed310-488d-11e8-987e-8ed5033eb5dc.png)

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `master` UI: `v2.0.37` |
|Access|`local` `admin`|
|Route|`authenticated.cluster.nodes.index`|

**Comment by yoke88** [comment] 2018-04-25 06:47
using view in API ,and i can delete it with api.

**Comment by tfiduccia** [comment] 2018-04-25 18:49
@yoke88  - I can't reproduce this.  Can you tell me what browser you are using and what type of cluster this is.

**Comment by yoke88** [comment] 2018-04-26 02:05
i'm using google chrome version 66.0.3359.117（正式版本） （64 位）， i have never used a touch screen.

**Comment by yoke88** [comment] 2018-04-26 02:09
I have delete the node in GUI v2.0.36, but it not work , and the same time , there is a problem related to volume add in GUI v2.0.36 ,so i upgraded to GUI v2.0.37 . after the upgrade ,i still can not delete the node,
so i mannuly delete the node with `kubectl delete node ceph4` ,then delete the node using API.

**Comment by tfiduccia** [comment] 2018-05-02 23:39
Version - v2.0.0
Verified fixed in UI v2.0.41.  Let me know if you are still having issues.

**Closed by tfiduccia** 2018-05-02 23:39 UTC
Labels: version/2.0
