### ISSUE TITLE
Exec shell and "view logs" for pods are not functional  in a cis 1.5 hardened setup when only public ip is provided when registering custom nodes.

### ISSUE THREAD

**Issue by soumyalj** [rancher/rancher#26175] opened 2020-03-21 00:54 UTC
Version: v2.4.0-rc8
K8s version: V1.17.4-rancher1-2
Steps:
1. Create a hardened custom cluster setup using the guidelines in the below docs:
https://rancher.com/docs/rancher/v2.x/en/security/hardening-2.3.5/

2. Create pods and exec shell into the pods:
Exec shell fails with Close code 1006 as below:

![Screen Shot 2020-03-20 at 5 50 17 PM](https://user-images.githubusercontent.com/18536626/77215786-541c3580-6ad3-11ea-8efd-f6167603bd88.png)

View logs for the pods are also not functional
![Screen Shot 2020-03-20 at 5 52 47 PM](https://user-images.githubusercontent.com/18536626/77215860-bd03ad80-6ad3-11ea-8814-34dc3680992f.png)

**Comment by superseb** [comment] 2020-03-22 16:45
Not able to reproduce on 1.17.4 cluster.

**Comment by sowmyav27** [comment] 2020-03-22 18:55
On a CIS 1.4 hardened cluster (latest master-head commit id: `371ec137f`) - k8s version - 1.17.4-rancher1-2 - Exec Shells shows `Closed Code: 1006` issue. View Logs works.

**Comment by soumyalj** [comment] 2020-03-23 19:18
Tested with v2.4.0-rc8 .

1. Followed the steps of hardening guide. 
2. Created a custom cluster specifying both public ip and internal ip in the "docker run" command as specified in the docs below.
https://rancher.com/docs/rke/latest/en/config-options/services/#kubelet-serving-certificate-requirements
3.The cluster was active and exec shell and view logs were functional.

**Comment by sowmyav27** [comment] 2020-03-24 16:59
On master-head commit id: `4aa97c7be` - verified with CIS 1.4 hardened cluster the following scenarios have been verified:
- with "DenyEscalatingExec" plugin, nodes registered using both public and private ips the workloads deployed have exec shell and view logs working.
- with "DenyEscalatingExec" plugin, nodes registered using only public ip the workloads deployed have exec shell and view logs working.

**Comment by sowmyav27** [comment] 2020-03-24 18:35
Verified on latest master-head, With a CIS 1.5 hardened cluster 
- In a custom cluster, nodes registered with public IP address, the exec shell and view logs do not work in the cluster for workloads.

**Comment by sangeethah** [comment] 2020-03-24 21:50
@paraglade Can this be documented as known issue ? - Exec shell and "view logs" for pods are not functional in a cis 1.5 hardened setup when only public ip is provided when registering custom nodes

**Comment by paraglade** [comment] 2020-03-26 23:35
PR created: https://github.com/rancher/docs/pull/2391

**Comment by sowmyav27** [comment] 2020-03-26 23:54
Verified the docs
```
Known Issues
Rancher exec shell and view logs for pods are not functional in a cis 1.5 hardened setup when only public ip is provided when registering custom nodes.
```
https://rancher.com/docs/rancher/v2.x/en/security/hardening-2.3.5/#known-issues

Closing the issue.

**Closed by sowmyav27** 2020-03-26 23:54 UTC
Labels: [zube]: To Test, kind/bug-qa, team/eio

**Comment by paraglade** [comment] 2020-04-10 17:41
In the hardening guide the kubelet is configured with generate_serving_certificate = true to create certs for the kublet. If the docker run registration command is run with only the public ip of the node the certs are generated with the provided public address . In the case of AWS EC2 nodes the hostname maps to the private ip of the instance. As a result the cert is not valid for internal cluster communication which effectively breaks the ability to view logs or exec shell in the rancher UI.

further reading:
https://rancher.com/docs/rke/latest/en/config-options/services/#kubelet-options
https://rancher.com/docs/rke/latest/en/config-options/services/#kubelet-serving-certificate-requirements
