### ISSUE TITLE
MonitorMetric objects remain static through Rancher upgrades

### ISSUE THREAD

**Issue by dkeightley** [rancher/rancher#27761] opened 2020-06-27 22:08 UTC
**What kind of request is this (question/bug/enhancement/feature request):** bug

**Steps to reproduce (least amount of steps as possible):** 

1. Using an earlier Rancher version ([v2.2.13 in this example](https://github.com/rancher/rancher/blob/v2.2.13/pkg/controllers/user/monitoring/metricExpression.go#L3562))
2. Enable monitoring on a downstream cluster
3. Verify the current MonitorMetric object for the cluster/node (in this case the expression for `node-cpu-load-1` was incorrect)
4. Upgrade Rancher ([v2.3.2 in this example](https://github.com/rancher/rancher/blob/v2.3.2/pkg/controllers/user/monitoring/metricExpression.go#L3559), although could be any 2.3.x or 2.4.x version)
5. Verify the MonitorMetric object again, the spec for the Rancher version in use would be expected.

With a kubeconfig for the rancher management cluster this loop can verify the `node-cpu-load-1` objects of all clusters.
```bash
for ns in $(kubectl get monitormetric -A | awk '$2 ~ /node-cpu-load-1$/ { print $1 }')
  do
    kubectl get monitormetric -n $ns node-cpu-load-1 -o yaml
done
```

**Result:** The metrics in the UI are not as expected or different between clusters/nodes that were created at different Rancher versions.

For example:
```yaml
...
  description: node cpu load 1
  expression: sum(node_load1{instance=~"$instance"}) / count(node_cpu_seconds_total{mode="system",instance=~"$instance"})
```

The expected expression would be the raw load avg: `sum(node_load1{instance=~"$instance"})`

**Other details that may be helpful:** MonitorMetrics objects define UI queries only, metrics from Prometheus/Grafana would be unaffected.

gz#10922

SURE-2208

**Comment by jiaqiluo** [comment] 2020-06-29 19:55
@dkeightley  Do you upgrade the monitoring after upgrading the Rancher?

**Comment by jiaqiluo** [comment] 2020-06-29 22:41
@dkeightley  I am able to reproduce the bug. Actually it is known behavior.

The new object definition containing the new expression applies only when monitoring is enabled. 

I see the new express after I disable and re-enable the cluster monitoring in exiting cluster, or enable it in a new cluster. 

So the workaround is to re-enable the monitoring in the cluster. 


here is the original issue for updating the expression: https://github.com/rancher/rancher/issues/22820

**Comment by aiwantaozi** [comment] 2020-06-30 01:54
If you don't want to re-enable the monitoring, could edit the expression field in monitormetric directly.

**Comment by aiwantaozi** [comment] 2020-07-08 06:41
We can upgrade the metrics when rancher upgrades, but it will also overwrite the metrics user have customized.

**Comment by aiyengar2** [comment] 2021-09-15 21:09
@dkeightley this issue should only affect users who are upgrading from Rancher 2.2.x upwards. I don't believe this is a supported upgrade path today (since even 2.4 is EOL), so I'm closing out this issue.

If a user who is upgrading from Rancher 2.2.x encounters this issue, I'd advise using the workaround documented in https://github.com/rancher/rancher/issues/27761#issuecomment-651471313 post-upgrading Rancher to 2.3.x+, after which the workaround should no longer be necessary.

---

#### Why does this only affect users who are upgrading from Rancher 2.2.x upwards?

Between Rancher 2.2.x and Rancher 2.3.x, we made changes to the default `MonitorMetrics` objects deployed by Rancher. However, since then the MonitorMetrics object have never been changed; therefore, even if a user were to upgrade Rancher from 2.3.x to any later version, they would never encounter this issue.

This can be double-checked via the following bash commands.

First I pulled the relevant files:

```bash
curl -o 2-2.go https://raw.githubusercontent.com/rancher/rancher/release/v2.2/pkg/controllers/user/monitoring/metricExpression.go
curl -o 2-3.go https://raw.githubusercontent.com/rancher/rancher/release/v2.3/pkg/controllers/user/monitoring/metricExpression.go
curl -o 2-5.go https://raw.githubusercontent.com/rancher/rancher/release/v2.5/pkg/controllers/managementagent/monitoring/metricExpression.go
curl -o 2-6.go https://raw.githubusercontent.com/rancher/rancher/release/v2.6/pkg/controllers/managementuserlegacy/monitoring/metricExpression.go
```

Then I compared the diffs. I observed a diff between release/v2.2 -> release/v2.3:
```bash
diff 2-2.go 2-3.go
1246,1247c1246,1247
<   expression: sum(node_load5) / count(node_cpu_seconds_total{mode="system"})
<   legendFormat: Load5
---
>   expression: sum(node_load5) by (instance)
>   legendFormat: Load5([[instance]])
1263,1264c1263
<   expression: sum(node_load5) by (instance) / count(node_cpu_seconds_total{mode="system"})
<     by (instance)
---
>   expression: sum(node_load5) by (instance)
1281,1282c1280,1281
<   expression: sum(node_load1) / count(node_cpu_seconds_total{mode="system"})
<   legendFormat: Load1
---
>   expression: sum(node_load1) by (instance)
>   legendFormat: Load1([[instance]])
1298,1299c1297
<   expression: sum(node_load1) by (instance) / count(node_cpu_seconds_total{mode="system"})
<     by (instance)
---
>   expression: sum(node_load1) by (instance)
1350,1352c1348,1350
<   expression: (sum(node_filesystem_size_bytes{device!="rootfs"})
<      - sum(node_filesystem_free_bytes{device!="rootfs"})
<     ) / sum(node_filesystem_size_bytes{device!="rootfs"})
---
>   expression: (sum(node_filesystem_size_bytes{device!~"rootfs|HarddiskVolume.+"})
>      - sum(node_filesystem_free_bytes{device!~"rootfs|HarddiskVolume.+"})
>     ) / sum(node_filesystem_size_bytes{device!~"rootfs|HarddiskVolume.+"})
1368,1370c1366,1368
<   expression: (sum(node_filesystem_size_bytes{device!="rootfs"})
<     by (instance) - sum(node_filesystem_free_bytes{device!="rootfs"})
<     by (instance)) / sum(node_filesystem_size_bytes{device!="rootfs"})
---
>   expression: (sum(node_filesystem_size_bytes{device!~"rootfs|HarddiskVolume.+"})
>     by (instance) - sum(node_filesystem_free_bytes{device!~"rootfs|HarddiskVolume.+"})
>     by (instance)) / sum(node_filesystem_size_bytes{device!~"rootfs|HarddiskVolume.+"})
1423,1424c1421,1422
<   expression: sum(node_load15) / count(node_cpu_seconds_total{mode="system"})
<   legendFormat: Load15
---
>   expression: sum(node_load15) by (instance) 
>   legendFormat: Load15([[instance]])
1440,1441c1438
<   expression: sum(node_load15) by (instance) / count(node_cpu_seconds_total{mode="system"})
<     by (instance)
---
>   expression: sum(node_load15) by (instance)
3385c3382
<   expression: sum(rate(node_disk_written_bytes_total{instance=~"$instance"}[5m]))
---
>   expression: sum(rate(node_disk_written_bytes_total{instance=~"$instance", device!~"HarddiskVolume.+"}[5m]))
3402c3399
<   expression: sum(rate(node_disk_written_bytes_total{instance=~"$instance"}[5m]))
---
>   expression: sum(rate(node_disk_written_bytes_total{instance=~"$instance", device!~"HarddiskVolume.+"}[5m]))
3420c3417
<   expression: sum(rate(node_disk_read_bytes_total{instance=~"$instance"}[5m]))
---
>   expression: sum(rate(node_disk_read_bytes_total{instance=~"$instance", device!~"HarddiskVolume.+"}[5m]))
3437c3434
<   expression: sum(rate(node_disk_read_bytes_total{instance=~"$instance"}[5m])) by
---
>   expression: sum(rate(node_disk_read_bytes_total{instance=~"$instance", device!~"HarddiskVolume.+"}[5m])) by
3454,3456c3451,3453
<   expression: (sum(node_filesystem_size_bytes{device!="rootfs",instance=~"$instance"})
<      - sum(node_filesystem_free_bytes{device!="rootfs",instance=~"$instance"})
<     ) / sum(node_filesystem_size_bytes{device!="rootfs",instance=~"$instance"})
---
>   expression: (sum(node_filesystem_size_bytes{device!~"rootfs|HarddiskVolume.+",instance=~"$instance"})
>      - sum(node_filesystem_free_bytes{device!~"rootfs|HarddiskVolume.+",instance=~"$instance"})
>     ) / sum(node_filesystem_size_bytes{device!~"rootfs|HarddiskVolume.+",instance=~"$instance"})
3472,3474c3469,3471
<   expression: (sum(node_filesystem_size_bytes{device!="rootfs",instance=~"$instance"})
<     by (device) - sum(node_filesystem_free_bytes{device!="rootfs",instance=~"$instance"})
<     by (device)) / sum(node_filesystem_size_bytes{device!="rootfs",instance=~"$instance"})
---
>   expression: (sum(node_filesystem_size_bytes{device!~"rootfs|HarddiskVolume.+",instance=~"$instance"})
>     by (device) - sum(node_filesystem_free_bytes{device!~"rootfs|HarddiskVolume.+",instance=~"$instance"})
>     by (device)) / sum(node_filesystem_size_bytes{device!~"rootfs|HarddiskVolume.+",instance=~"$instance"})
3562c3559
<   expression: sum(node_load1{instance=~"$instance"}) / count(node_cpu_seconds_total{mode="system",instance=~"$instance"})
---
>   expression: sum(node_load1{instance=~"$instance"})
3579c3576
<   expression: sum(node_load1{instance=~"$instance"}) / count(node_cpu_seconds_total{mode="system",instance=~"$instance"})
---
>   expression: sum(node_load1{instance=~"$instance"})
3596c3593
<   expression: sum(node_load15{instance=~"$instance"}) / count(node_cpu_seconds_total{mode="system",instance=~"$instance"})
---
>   expression: sum(node_load15{instance=~"$instance"})
3613c3610
<   expression: sum(node_load15{instance=~"$instance"}) / count(node_cpu_seconds_total{mode="system",instance=~"$instance"})
---
>   expression: sum(node_load15{instance=~"$instance"})
3766c3763
<   expression: sum(node_load5{instance=~"$instance"}) / count(node_cpu_seconds_total{mode="system",instance=~"$instance"})
---
>   expression: sum(node_load5{instance=~"$instance"})
3783c3780
<   expression: sum(node_load5{instance=~"$instance"}) / count(node_cpu_seconds_total{mode="system",instance=~"$instance"})
---
>   expression: sum(node_load5{instance=~"$instance"})
```

However, since release/v2.3, we have not made any modifications to these objects that requires them to be changed.

```bash
diff 2-3.go 2-6.go
11c11
< 	managementv3 "github.com/rancher/types/apis/management.cattle.io/v3"
---
> 	managementv3 "github.com/rancher/rancher/pkg/generated/norman/management.cattle.io/v3"
80,83c80
< 	if err := json.Unmarshal(jsondata, obj); err != nil {
< 		return err
< 	}
< 	return nil
---
> 	return json.Unmarshal(jsondata, obj)
```

**Closed by aiyengar2** 2021-09-15 21:09 UTC
Labels: kind/bug, internal, [zube]: RT - Sprint Ready
