### ISSUE TITLE
Upgrade the default CSI driver which ships with Rancher for vSphere Volume provisioning

### ISSUE THREAD

**Issue by leflambeur** [rancher/rancher#26169] opened 2020-03-20 21:09 UTC
**What kind of request is this (question/bug/enhancement/feature request):**
Enhancement

**Details**
Rancher currently uses kubernetes.io/vsphere-volume as the provisioner for vsphere storage, the in-tree provider that comes with k8s but this functionality is now being migrated to out-tree CSI and CPI drivers 

Could Rancher be upgraded to ship the new out-tree CSI driver for vSphere:

https://github.com/kubernetes-sigs/vsphere-csi-driver

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI):2.3.5
- Installation option (single install/HA):N/A

**Comment by Tejeev** [comment] 2020-10-06 18:23
Duplicate of https://github.com/rancher/rancher/issues/23357

**Closed by Tejeev** 2020-10-06 18:23 UTC
Labels: area/storage, area/vsphere
