### ISSUE TITLE
Memory leak in v2.4.2 with no clusters or nodes

### ISSUE THREAD

**Issue by dnoland1** [rancher/rancher#26577] opened 2020-04-09 17:49 UTC
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
1. Installed Rancher v2.3.5 on a two node k3s cluster with MySQL backend (2020-03-26)
2. Upgrade to Rancher v2.4.2 (2020-04-02)

**Result:**
On both k3s nodes, the Rancher process/pod memory utilization is growing about 800MB a day and currently over 3GB:
```
USER       PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
root      6029  4.3 44.9 3741456 3574740 ?     Sl   Apr02 426:45 rancher --http-listen-port=80 --https-listen-port=443 --audit-log-path=/var/log/auditlog/rancher-api-audit.log --audit-level=0 --audit-log-maxage=10 --audit-log-maxbackup=10 --audit-log-maxsize=100 --no-cacerts --http-listen-port=80 --https-listen-port=443 --add-local=off
```
```
root     23692  4.7 46.5 3810068 3662124 ?     Sl   Apr02 472:49 rancher --http-listen-port=80 --https-listen-port=443 --audit-log-path=/var/log/auditlog/rancher-api-audit.log --audit-level=0 --audit-log-maxage=10 --audit-log-maxbackup=10 --audit-log-maxsize=100 --no-cacerts --http-listen-port=80 --https-listen-port=443 --add-local=off
```
kubectl top pods output:
```
NAMESPACE                   NAME                                                      CPU(cores)   MEMORY(bytes)   
demo-hosted                 rancher-75f5896bd-8jxv7                                   4m           3347Mi          
demo-hosted                 rancher-75f5896bd-kc75f                                   3m           3445Mi          
```

Memory growth over last 24 hours:
<img width="405" alt="image" src="https://user-images.githubusercontent.com/468462/78924666-13b73400-7a4f-11ea-8ad6-0b84301c9938.png">

**Other details that may be helpful:**
No clusters or nodes have been added to this cluster.

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI):
v2.3.5 -> v2.4.2
- Installation option (single install/HA):
HA w/ k3s & MySQL

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported):
K3s
- Machine type (cloud/VM/metal) and specifications (CPU/memory):
m5.large on AWS (2vCPU, 8GB RAM)
- Kubernetes version (use `kubectl version`):

```
> kubectl version
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.8", GitCommit:"ec6eb119b81be488b030e849b9e64fda4caaf33c", GitTreeState:"clean", BuildDate:"2020-03-12T21:00:06Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.4+k3s1", GitCommit:"3eee8ac3a1cf0a216c8a660571329d4bda3bdf77", GitTreeState:"clean", BuildDate:"2020-03-25T16:13:25Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"linux/amd64"}
```

- Docker version (use `docker version`):
Using containerd

**Comment by vitobotta** [comment] 2020-04-10 17:15
I was just told on Slack about this issue. I'm having the same problem, CPU and memory usage going crazy every now and then.

**Comment by aaronRancher** [comment] 2020-04-10 17:30
This bug is reproduced with Rancher server `rancher\rancher:v2.4.2`
Steps:
Installed Rancher v2.3.5 on a two node k3s cluster with MySQL backend 
Upgrade to Rancher v2.4.2
Result:
Memory usage before upgrade:
![v2 3 5 initial memory](https://user-images.githubusercontent.com/57409052/79009583-a8379a00-7b14-11ea-9b7f-a6ce481bb9d5.png)
Memory usage after idle for 1 day:
<img width="380" alt="Screen Shot 2020-04-10 at 9 22 28 AM" src="https://user-images.githubusercontent.com/57409052/79009589-b4235c00-7b14-11ea-9762-2085fb1c0a46.png">

**Comment by dnoland1** [comment] 2020-04-11 00:53
I also have a fresh install of Rancher v2.4.2 that was not upgraded and seeing the same memory consumption pattern.

**Comment by dramich** [comment] 2020-04-16 00:29
This issue and https://github.com/rancher/rancher/issues/26633 both have the same root cause.

**Comment by vitobotta** [comment] 2020-04-16 08:05
I had another problem because of this yesterday where I deleted a node pool, and Rancher was having memory/load issues and therefore the actual nodes were not deleted from the cloud provider, so I had to cleanup manually.

**Comment by dramich** [comment] 2020-04-16 17:24
@aaronRancher The best way to test this is to have a setup and just let it sit. With the agent you should be able to see the memory climb within the hour, but seeing the rancher leak takes more time.

**Comment by dramich** [comment] 2020-04-16 17:25
This pr https://github.com/rancher/rancher/pull/26644 fixes this in master by pulling in latest steve.

**Comment by dramich** [comment] 2020-04-16 18:25
This is related to dashboard being active. When dashboard is active something called the clustercache is watching all events in the cluster and pushing those into a workqueue. The workqueue is two maps that keep track of things being worked and things that need to be worked. When we pull something from the queue it moves to the 2nd map and just stays there as the item is never marked as completed in the queue. If the object is never marked it never leaves the map thus creating a leak. This was seen on a smaller cluster but the more activity in the cluster the faster this leak will happen. This has been fixed and is in both 2.4-head and master-head images.

**Comment by vitobotta** [comment] 2020-04-16 18:27
@dramich hi, I'd it possible to disable the dashboard for now until the new release is out? Thanks

**Comment by vincent99** [comment] 2020-04-16 18:30
Settings -> Feature Flags -> Dashboard

**Comment by vitobotta** [comment] 2020-04-16 18:31
@vincent99 awesome, thanks!

**Comment by sangeethah** [comment] 2020-04-16 20:46
Reopening this issue to get the fixes merged in master since it was reverted - https://github.com/rancher/rancher/pull/26663 - Revert "Refactor for lasso" #26663

**Comment by aaronRancher** [comment] 2020-04-18 00:35
Installed Rancher v2.4-head on a two node k3s (t2.medium) cluster with MySQL backend (v5.7.22, db.t2.large)
Rancher memory behavior of 2.4-head version `cf5ab1dcb` for 6 hours.
![Screen Shot 2020-04-17 at 5 04 18 PM](https://user-images.githubusercontent.com/57409052/79623467-4b6a4f80-80d1-11ea-8308-2fce2066bb3f.png)

**Comment by jiaqiluo** [comment] 2020-04-21 18:04
Install `Rancher:v2.4.2` in an RKE 3-node cluster, and add couple clusters to the setup. Here is the CPU and memory consumption of the `rancher` workload in the local cluster:

<img width="1411" alt="Screen Shot 2020-04-21 at 11 02 23 AM" src="https://user-images.githubusercontent.com/6218999/79898158-a1840f00-83bf-11ea-9ba0-ff13ee130776.png">

Make another identical setup using the image `Rancher:v2.4-2774-head` cf5ab1d :

<img width="1393" alt="Screen Shot 2020-04-21 at 11 03 19 AM" src="https://user-images.githubusercontent.com/6218999/79898227-c2e4fb00-83bf-11ea-8ad2-9ef5ccccde15.png">

**Comment by aaronRancher** [comment] 2020-04-22 23:31
Tested with Rancher server rancher\rancher:v2.4.2 version 7f7d6bf.
Cluster was idle for 3 days:
![Screen Shot 2020-04-22 at 4 30 44 PM](https://user-images.githubusercontent.com/57409052/80043467-a2e43300-84b6-11ea-8405-d8bc066ac339.png)

Tested with Rancher server rancher\rancher:master-head version 8bd9245.
Cluster was idle for 3 days:
![Screen Shot 2020-04-22 at 4 31 08 PM](https://user-images.githubusercontent.com/57409052/80043486-af688b80-84b6-11ea-83cc-febc9c1f98c7.png)

Tested with Rancher server rancher\rancher:v2.4-head version 7f7d6bf.
Cluster was idle for 3 days:
![Screen Shot 2020-04-22 at 4 31 25 PM](https://user-images.githubusercontent.com/57409052/80043500-ba232080-84b6-11ea-8498-58a134038b09.png)

**Comment by jiaqiluo** [comment] 2020-04-23 01:03
Run the following three setups on three identical RKE provisioned cluster (k8s v1.17.4), and provision the same number of clusters on it.
- rancher v2.4.2 
- rancher v2.4-head 
- rancher mater-head 

<img width="1403" alt="Screen Shot 2020-04-22 at 5 58 07 PM" src="https://user-images.githubusercontent.com/6218999/80047718-0ffdc580-84c3-11ea-9516-e5bf1cd2afb6.png">
<img width="1396" alt="Screen Shot 2020-04-22 at 5 58 29 PM" src="https://user-images.githubusercontent.com/6218999/80047722-12601f80-84c3-11ea-9f51-c58508415266.png">
<img width="1385" alt="Screen Shot 2020-04-22 at 5 58 47 PM" src="https://user-images.githubusercontent.com/6218999/80047723-13914c80-84c3-11ea-94af-4c5d87b2bfa5.png">


It turns out in the past 12 hours:
- the memory consumption of v2.4.2 were rising up to 931 MB memory and restarted
- `master-head` and `v2.4-head` used about 600 - 700 MB constantly

**Comment by aaronRancher** [comment] 2020-04-24 00:53
Tested on Rancher `v2.4.3-rc1` on a two node k3s (t2.large) cluster with MySQL backend (v5.7.22, db.t2.large)
![Screen Shot 2020-04-23 at 5 20 33 PM](https://user-images.githubusercontent.com/57409052/80163347-c082cc80-858a-11ea-8aac-2bdcb728ad28.png)
Tested with k3s HA Rancher server `rancher\rancher:v2.4-head` version `7f7d6bf`.
![Screen Shot 2020-04-23 at 5 51 05 PM](https://user-images.githubusercontent.com/57409052/80163502-40109b80-858b-11ea-8bbb-cf66073a78b5.png)

Memory consumption is stable on idle.

**Closed by aaronRancher** 2020-04-24 00:53 UTC
Labels: [zube]: To Test, internal, kind/bug

**Comment by abel533** [comment] 2020-09-02 05:56
Add a picture that occupies more than 10G of memory.
![1](https://user-images.githubusercontent.com/1787798/91937211-06fbeb00-ed24-11ea-991a-97e14e37b4b0.png)
