### ISSUE TITLE
Web service ip not resolving in nginx container

### ISSUE THREAD

**Issue by pebreo** [rancher/rancher#7691] opened 2017-02-05 03:31 UTC
Rancher Versions: 1.3.0 
Docker Version: 1.13.0
OS and where are the hosts located? cloud 
Setup Details: digital ocean: 1 rancher server + 1 host 
Environment Type: Cattle

Steps to Reproduce:
When I deploy using `rancher-compose` command I got the following **error** from my `nginx` container:
```
2017/02/05 02:59:59 [emerg] 9#9: host not found in upstream "web" in /etc/nginx/conf.d/default.conf:13
```
This is similar to issue: https://github.com/rancher/rancher/issues/2628

The weird thing is when I push images to a host created using **docker machine**, everything works as fine no problem:
```
docker-machine -f staging.yml up -d # see staging.yml below
```
I'm not sure what difference in the **rancher-created host** vs. my **docker-machine-created host** that would cause this issue. 

This is my rancher-compose.yml
```yaml
version: '2'
services:
  web:
    scale: 1
    start_on_create: true
  nginx:
    scale: 1
    start_on_create: true
  postgres:
    scale: 1
    start_on_create: true
```
This is my `staging.yml` docker compose file:
Note that I'm using `envsubst` so I can use environment variables in my nginx conf files as recommended by the official `library/nginx` documentation on Docker Hub.
```yaml
version: "2"

services:
  web:
    image: myacct/web_staging:0.0.13
    stdin_open: true
    tty: true
    restart: always
    expose:
      - "8000"
    networks:
      - backend
    volumes:
      - django-static:/usr/src/collectstatic 
      - backup:/backup
    env_file: .env
    environment:
      DEBUG: 'false'
      DB_PASS: secretepw
      EMAIL_ENABLE_NOTIFICATION: 'true'
    entrypoint: /usr/src/app/backend/docker-entrypoint.sh postgres 5432
    command: /bin/bash /usr/src/app/backend/start.sh 
    labels:
      io.rancher.container.pull_image: always
      io.rancher.scheduler.affinity: myhostname=host01

  nginx:
    image: myacct/nginx_staging:0.0.18
    restart: always
    ports:
      - "80:80"
    volumes_from:
      - web
    env_file: .env
    networks:
      - backend
    labels:
      io.rancher.sidekicks: web
      io.rancher.container.pull_image: always
      io.rancher.scheduler.affinity: myhostname=host01
    command: /bin/sh -c "envsubst < /etc/nginx/conf.d/django_project.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"

  postgres:
    restart: always
    image: myacct/postgres_staging:0.0.6
    stdin_open: true
    tty: true
    volumes:
      - pgdata:/var/lib/postgresql/data/
    networks:
      - backend
    environment:
      POSTGRES_PASSWORD: secretpw
    labels:
      io.rancher.container.pull_image: always
      io.rancher.scheduler.affinity: myhostname=host01

volumes:
  django-static:
  pgdata:
  # used to backup and restore django data
  backup: 

networks:
  backend:

```
This is my `nginx.conf`:
```
user  nginx;
worker_processes  4;

error_log  /var/log/nginx/error.log warn;
pid        /var/run/nginx.pid;


events {
    worker_connections  1024;
}


http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                      '$status $body_bytes_sent "$http_referer" '
                      '"$http_user_agent" "$http_x_forwarded_for"';

    access_log  /var/log/nginx/access.log  main;

    sendfile        on;
    #tcp_nopush     on;

    keepalive_timeout  65;

    #gzip  on;

    include /etc/nginx/conf.d/*.conf;
}
```
And this is my `/etc/nginx/conf.d/default.conf`
```
server {

    listen 80;
    server_name example.org;
    charset utf-8;
    client_max_body_size 1000M;

    location /static {
        alias /usr/src/collectstatic;
    }

    location / {
        proxy_pass http://web:8000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }

}
```
When go to `/etc/resolve.conf` in my nginx container  I get:
```bash
# cat /etc/resolv.conf 
# Dynamic resolv.conf(5) file for glibc resolver(3) generated by resolvconf(8)
#     DO NOT EDIT THIS FILE BY HAND -- YOUR CHANGES WILL BE OVERWRITTEN
nameserver 8.8.8.8
nameserver 8.8.4.4
```

Is there any more information I can provide?

Thanks.
-Paul

**Comment by pebreo** [comment] 2017-02-05 05:58
Here's an update of what I've tried so far. To try to isolate what is wrong, I was able to get it to work using `tutum/nginx` image with the `nginx.conf` and `default.conf` files above.

I had to change `user www-data;` and `daemon off;` in the `nginx.conf` file to get it to work the `tutum/nginx` image.

Also, to see whether the official `nginx` alpine and non-alpine images was the cause of the problem, I  tried both `nginx:1.11` and `nginx:1.11-alpine` images - but that didn't matter.

**Comment by HenryTheSir** [comment] 2017-02-06 09:58
Just a general hint with Docker and nginx:
nginx makes just one DNS lookup at service start, if your backend container gets a new IP you have to restart the nginx container.

You can fix this by setting an DNS resolver : 
resolver 169.254.169.250 valid=5s ipv6=off;

and filling an variable with your DNS name : 
set $backendweb web;
 proxy_pass http://$backendweb:8000;

By this configuration nginx looks up DNS all 5 seconds again and does not fail on startup if your web container is not yet started or has no IP assigned

**Comment by jurajseffer** [comment] 2017-02-14 10:10
There is something odd with Rancher DNS though (experienced this behaviour with 1.1 and 1.3).

When we had Alpine images, every 20 seconds, DNS request to its DNS service for the short name of a service, e.g. `session` instead of `session.site....` would return no A records. All the requests in between were fine. I could replicate this using curl inside the container. This affected all Alpine containers but not all the time - sometimes the resolution wouldn't work at all so we had to keep redeploying that alpine container until it started resolving other services. We worked around this by switching to Debian images that seem to use resolv.conf with search domains so DNS queries don't fail. 

I have rancher-dns service logs for the above behaviour if someone from the internals is willing to have a look at them.

However, now we have a problem of not being able to resolve certain services from our nginx container. Let's say there is a service called `session`. I've observed the following (from a debian based nginx container):

1. `ping session` works, seems to use domain search
2. `dig session` doesn't work, returns no A records from rancher dns
3. `dig session @127.0.0.1` doesn't work either (asking dnsmasq inside nginx container)
4. `dig +search session` works, using rancher dns
5. `dig +search session @127.0.0.1` works, using dnsmasq
6. `nslookup session` works, seems to append search domain to it

**Comment by janeczku** [comment] 2017-02-14 15:36
@jurajseffer 

There are known issues with Alpine not playing nice with domain search, because it's not using the glib standard c library. https://github.com/gliderlabs/docker-alpine/issues/8#issuecomment-255600445
In short: <serviceName> does not work, but <serviceName>.<stackName> does.

**Comment by jurajseffer** [comment] 2017-02-14 18:07
@janeczku I know about those. The problem is Rancher not returning A records for some some load balancers (<serviceName>). We think we can replicate it by removing the service (two Rancher LBs) and then redeploying it. After this is done, Rancher stops returning A records for <serviceName>, only <serviceName>.<stackName> etc are successfully queried. Furthermore, restarting Rancher's DNS container fixes it but only in a single host setup, it breaks the DNS resolution in our two host setup. I.e. if we restart DNS on host1, host2 can't query and vice versa.

**Comment by janeczku** [comment] 2017-02-14 19:54
@jurajseffer you can send me your rancher-dns logs at jan@rancher.com though i doubt there will by anything useful there without having debug logging enable.

**Comment by jurajseffer** [comment] 2017-02-15 12:44
@janeczku Sent it to you now. It's with debug turned on.

**Comment by janeczku** [comment] 2017-02-16 01:37
@vincent99 After looking at the log, i think this might be an issue where queries for `serviceName.` result in a NXDOMAIN or NODATA response that is being cached. This might be a race condition where the client service is started before the queried service is created or has any running containers. The first reply from us will then either be a NXDOMAIN from upstream DNS or NODATA from local config (no containers). These are then being cached and we will send these replies back for any consecutive queries for the next 10 minutes (cache TTL).

**Comment by jurajseffer** [comment] 2017-02-16 14:00
@janeczku That sounds like it could have something to do with it but I don't think the problem goes away after 10 minutes. Also it would not explain why we got no A records from Rancher DNS exactly every 20 seconds. I.e. we had curl running every second and each 20th curl call failed with "unknown host" as you can see in the logs. I should add those logs were from Rancher 1.1 setup but we have similar DNS problems in 1.3 as described above in https://github.com/rancher/rancher/issues/7691#issuecomment-279664529
With regards to nginx we're working around this by using `sevice.stack....` hosts now.

Thank you for looking into it.

**Comment by superseb** [comment] 2017-05-23 21:16
@jurajseffer Do you have anything to add, does this still occur?

**Comment by jurajseffer** [comment] 2017-05-24 05:36
@superseb As far as I know it still occurs on 1.3 but we've switched most images to Debian from Alpine because of this so it only happens to a service or two. When it does, restarting Rancher's network-manager services fixes it. All I had was the debug logs for Rancher DNS that showed inconsistent lookups.

**Comment by superseb** [comment] 2017-05-24 07:52
Did you try to reproduce on 1.5.*?

**Comment by jurajseffer** [comment] 2017-05-24 09:51
No, sorry, we've not upgraded yet.

**Comment by rbhaddon** [comment] 2017-06-28 18:52
I can confirm that the problem still exists on Rancher 1.6.2.

**Comment by bmmathe** [comment] 2017-11-16 14:30
@HenryTheSir which IP do I use for the DNS resolver?  In my case I have 3 manager nodes in the swarm and all services are attached to a custom overlay network called proxy.

**Comment by port22** [comment] 2018-09-20 10:54
What are the actual IPs to use as nginx resolver in Docker? Does it differ with `docker-compose v2/3` and Docker Swarm via `docker stack deploy` ?
It seems that with docker-compose `127.0.0.11` is working, but with `docker stack deploy` it doesn't

**Comment by loganhz** [comment] 2018-10-12 06:51
Thanks for your report!

With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.

If you think we should keep this issue open, please let me know.

**Closed by loganhz** 2018-10-12 06:51 UTC
Labels: area/dns, status/more-info, version/1.6
