### ISSUE TITLE
Integrate Helm 3 in Rancher

### ISSUE THREAD

**Issue by ankur111** [rancher/rancher#20596] opened 2019-05-31 20:15 UTC
* In 2.4, both Helm 2 & Helm 3 will be supported:
      * Helm version selection will occur when adding a new catalog
      * Once the catalog is created, you cannot update / change the selected helm version
      * All installs of apps will be with the catalog selected helm version
      * Any existing deployed app(s) will continue to be managed by helm 2
      * Any existing catalog(s) will continue to identified as a helm 2 catalog
* Once any app is deployed using Helm 3, there will be no support for rolling back to being managed by Helm 2

* These changes need to be applied to catalog apps as well as multi-cluster apps

**CLI Support**  
* Add cli support for helm version when adding new catalog
* Confirm that CLI will be able to deploy using Helm 3 and upgrades for already deployed Helm 2 app will continue to be managed with Helm 2.

**Comment by pietervogelaar** [comment] 2019-09-11 09:30
Is it already possible to use Helm 3 beta with Rancher somehow?

**Comment by pietervogelaar** [comment] 2019-09-11 11:24
Because of https://github.com/helm/helm/issues/2060 Helm 2 is a deal breaker for us. It's one of the things they solved https://v3.helm.sh/docs/faq/. The latest version is now Helm 3 beta 3.

**Comment by pietervogelaar** [comment] 2019-09-11 12:09
I can confirm that Helm `v3.0.0-beta.3` is usable with Rancher `v2.2.8`.

In Rancher I have setup a custom GitHub Helm catalog, it contains a chart called "generic-app".

On my laptop I have the command `helm` (v3.0.0-beta.3) and with `export KUBECONFIG=....` I point to the kubeconfig file I downloaded from the Rancher UI for my cluster.

```
helm install example-ruby-api generic-app --namespace development-early-adopters --set image.tag=latest
helm install example-ruby-api generic-app --namespace development-late-majority --set image.tag=stable
```

This installs the Chart correctly into the proper namespace. Because of helm 3, the same release name can exist in different namespaces.

All the native Kubernetes resources workloads, services etc. are visible in the Rancher UI.

The "App" page however is (off course) still empty. Helm 3 releases are now stored in-cluster with CRD. So this App page will have to query it.

**Comment by shandyDev** [comment] 2019-11-13 15:05
It's happened - https://helm.sh/blog/helm-3-released/

**Comment by dmastag** [comment] 2019-11-13 15:10
I think its safe to talk about an upgrade path if we are still using Helm 2

**Comment by vincent99** [comment] 2019-11-13 15:47
If you installed tiller and team helm 2 in a cluster before, you can continue to do so with helm 3 on your own today.

The "apps" functionality in Rancher uses helm (2), with orchestration to run tiller only on-demand, not exposed to the Internet, and using the current user's credentials.  We  do this because we never viewed using a system-wide service account with broad permissions for any user to deploy any chart that does whatever it wants as acceptable.  

Now that helm acknowledges that problem and has provided a proper way to support that model, we should be able to switch to helm 3 and let apps from the UI and native helm CLI integrate with each other in a future Rancher release.

**Comment by oneilsh** [comment] 2019-11-15 07:35
Update: looks like this will be addressed soon in rancher now that helm v3 is out: https://github.com/rancher/rancher/issues/20596

will just have to deal til then.

**Comment by nilsher** [comment] 2019-11-25 17:29
I am completely new to rancher and built a new cluster the other day. However I installed everything with helm 3.

From what I understand you should be able to install helm charts through ranchers web ui in "APPS". However no list of apps is listed for me(added helm stable repo), is this because of using helm3 which this ticet wants to be integrated?

**Comment by tega90** [comment] 2019-12-06 11:09
When installing a chart using helm install, you don't see the app in "Apps" View. When installing the chart using the "apps" functionality, you don't see it using helm list. Is this considered as an issue and will integrating helm 3 in rancher fix it?
Apps functionality provides some nice features, but also, new helm versions provide its own nice features... :)

**Comment by yl-yue** [comment] 2019-12-18 06:34
Is there a temporary solution

**Comment by cloudnautique** [comment] 2019-12-19 21:11
@yl-yue, what is the problem you need to work around right now?

**Comment by yl-yue** [comment] 2019-12-30 07:42
@cloudnautique Is there a way to deploy apps using Helm3 in the rancher catalog, In the catalog, some apps need to use Helm3 to deploy.

It is possible to install the required Helm3 outside of rancher to deploy apps, but will the deployed apps be managed by rancher.

**Comment by cloudnautique** [comment] 2020-01-22 13:01
@yl-yue, you can use helm3 CLI directly with a Rancher provisioned Kubernetes cluster today. Deploying apps with Helm3 CLI will need to be managed via the Helm3 CLI, as Rancher will have no concept of them. 

The Catalog does not use Helm3 yet and can not use Helm3 charts features until we add support.

**Comment by dramich** [comment] 2020-01-23 16:07
Validate this is fixed with the uplift:
https://github.com/rancher/rancher/issues/25036

**Comment by dbecher-ito** [comment] 2020-02-15 15:23
When using helm 3, how does it come that helm list does not list rancher as a release? I am using minikube to test rancher and wanted to get a clean slate and used helm uninstall rancher, which does not work. :/

**Comment by mitchellmaler** [comment] 2020-02-15 16:17
If you deployed rancher using helm 3 then it will show up. You have to make sure the list is in the correct namespace you deployed it in such as cattle-system. helm list -n cattle-system

**Comment by jiaqiluo** [comment] 2020-03-07 00:48
the feature is validated on master-head 6330683

- new catalog can be added as either helm 2 or helm 3 catalog
- the designated helm version is used to deploy, upgrade, rollback, delete apps 
- helm 2 is used for existing apps and catalogs when upgrading from v2.3.5 to master-head

Detailed tests and results are tacked in the test plan.

**Closed by jiaqiluo** 2020-03-07 00:48 UTC
Labels: [zube]: To Test, kind/feature, kind/task
