### ISSUE TITLE
Edit Service dialog doesn't show existing links

### ISSUE THREAD

**Issue by gordontyler** [rancher/rancher#2250] opened 2015-10-07 18:28 UTC
I've created a service (app) in a stack with links to another service (db) in the same stack. When I use the Edit link from the dropdown for the "app" service, the Service Links section in the dialog is empty and it says "This service has no service links". However, if I view the docker-compose config for the stack, the "app" service has a link defined to the "db" service as expected.

**Comment by deniseschannon** [comment] 2015-10-07 18:40
Duplicate of https://github.com/rancher/rancher/issues/1294

**Comment by deniseschannon** [comment] 2015-10-07 18:42
@gordontyler Do you have multiple environments?

**Comment by gordontyler** [comment] 2015-10-07 18:43
Yes, but these are all in the same environment.

**Comment by deniseschannon** [comment] 2015-11-12 04:11
Reconciling issues. This is definitely a duplicate of https://github.com/rancher/rancher/issues/1389

**Closed by deniseschannon** 2015-11-12 04:11 UTC
Labels: area/ui
