### ISSUE TITLE
Cannot enable freeIPA through API

### ISSUE THREAD

**Issue by carllantz** [rancher/rancher#41253] opened 2023-04-23 01:10 UTC
**Rancher Server Setup**
- Rancher version: 2.7.2
- Installation option (Docker install/Helm Chart): Helm
RKE2 

**Information about the Cluster**
- Kubernetes version: v1.23.17
- Cluster Type (Local/Downstream): Local

**Describe the bug**
When using the API to enable freeipa, it shows it configured correctly but shows errors with allowedPrincipalIds. Works correctly when enabling freeipa through the ui.

**To Reproduce**
Install rancher and post to api.
```
[root@local ~]# cat temp.json
{
  "ldapConfig": {
    "enabled": true,
    "servers": [
      "rgs-freeipa.testit.help"
    ],
    "port": 389,
    "serviceAccountDistinguishedName": "uid=rgs,cn=users,cn=accounts,dc=testit,dc=help",
    "serviceAccountPassword": "PASS",
    "accessMode": "required",
    "userSearchBase": "cn=users,cn=accounts,dc=testit,dc=help",
    "groupSearchBase": "cn=groups,cn=accounts,dc=testit,dc=help",
    "groupDNAttribute": "entrydn",
    "groupObjectClass": "groupofnames",
    "allowedPrincipalIds": [
      "freeipa_user://uid=rgs,cn=users,cn=accounts,dc=testit,dc=help",
      "freeipa_groups://cn=rancher,cn=groups,cn=accounts,dc=testit,dc=help"
    ],
    "username": "USER",
    "password": "PASS"
  },
  "username": "USER",
  "password": "PASS"
}

[root@local ~]# curl -i -k -X POST -H 'Accept: application/json' -H 'Content-Type: application/json' -u "USER:PASS" -d "@temp.json" "https://local.testit.help/v3/freeIpaConfigs/freeipa?action=testAndApply"

HTTP/2 200
date: Sun, 23 Apr 2023 01:03:17 GMT
content-type: application/json
content-length: 0
cache-control: no-cache, no-store, must-revalidate
expires: Wed 24 Feb 1982 18:42:00 GMT
set-cookie: R_SESS=XXXX:XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX; Path=/; HttpOnly
x-api-cattle-auth: true
x-api-schemas: https://local.testit.help/v3/schemas
x-content-type-options: nosniff
strict-transport-security: max-age=15724800; includeSubDomains

``` 
**Result**
Errors in the UI and can't login.
![screen1](https://user-images.githubusercontent.com/3734133/233813902-4a8fcfc7-61a2-4806-bc9b-2d48f8cafd65.png)

**Expected Result**
Freeipa enabled and working correctly
**Screenshots**
![screen2](https://user-images.githubusercontent.com/3734133/233813954-d6241ae5-bdd2-415a-84d6-5b89cc6e4dc5.png)

**Additional context**
kubectl get authconfig freeipa -o yaml shows the same whether posting to api or using the ui.

**Comment by PennyScissors** [comment] 2023-06-20 21:07
Closing this issue as I was unable to reproduce. I attempted to reproduce it in Rancher 2.7.4 by provisioning a FreeIPA server using Terraform and enabling it in Rancher. We do not officially support hitting the Rancher API directly to enable an auth provider, but we have a Terraform provider we support so it made more sense to use Terraform to attempt reproduction since it interacts with the Rancher API in a similar way.

**Closed by PennyScissors** 2023-06-20 21:07 UTC
Labels: kind/bug, internal, area/authentication, team/area3, [zube]: Team Area 3
