### ISSUE TITLE
hostPort defined on workload via YAML lost after editing workload via the UI

### ISSUE THREAD

**Issue by axeal** [rancher/rancher#23375] opened 2019-10-11 09:17 UTC
**What kind of request is this (question/bug/enhancement/feature request):**

Bug

**Steps to reproduce (least amount of steps as possible):**

1. Spin up a default custom cluster with Rancher v2.2.8 or v2.3.0
2. Deploy the following simple nginx Deployment exposing a hostPort:
```
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  labels:
    app: nginx
  name: nginx
  namespace: default
spec:
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - image: nginx
        name: nginx
        ports:
        - containerPort: 80
          hostPort: 8080
          protocol: TCP
```
3. Observe nginx reachable via hostPort
4. Open Edit form for the Deployment in Rancher UI and observe port incorrectly shown as NodePort 0:
<img width="1374" alt="Screenshot 2019-10-11 at 10 48 31" src="https://user-images.githubusercontent.com/9771530/66639973-42775d80-ec18-11e9-9988-d74198a231aa.png">
5. Click upgrade in the Edit UI and observe the hostPort is removed from the Deployment.

**Environment information**
- Tested on Rancher v2.2.8 and v2.3.0

**Comment by superseb** [comment] 2019-10-11 22:34
Sounds like a duplicate of https://github.com/rancher/rancher/issues/17878

**Comment by alena1108** [comment] 2019-10-11 22:56
It's an API issue. Port created via yaml format in rancher api:

```
"ports": [
{
"containerPort": 80,
"protocol": "TCP",
"sourcePort": 0,
"type": "/v3/project/schemas/containerPort"
}
```

And here is what UI expects (example of the port configured via UI)

```
"ports": [
{
"containerPort": 80,
"dnsName": "nginx-hostport",
"kind": "HostPort",
"name": "foo",
"protocol": "TCP",
"sourcePort": 55,
"type": "/v3/project/schemas/containerPort"
}
],
```

Ideally we should figure out the mapper on the API side that would translate ports created natively, to the format UI understands.

**Comment by sangeethah** [comment] 2019-11-06 05:11
Able to reproduce the issue using rancher server version - `v2.3.1`

Tested with rancher server using laster - `v2.3-head` - `c915d7e34`

Create a workload with hostport using kubectl shell.
Open this workload in "Edit Workload" view . host port is displayed correctly.

<img width="1187" alt="Screen Shot 2019-11-05 at 8 59 29 PM" src="https://user-images.githubusercontent.com/4266958/68269782-eaadf580-000f-11ea-8b74-764981e520fb.png">

Saving the workload (without any changes made) does not result in host port being lost.  


When u try to open this workload again in "Edit workload" view ,port is again set to "0" and on save we loose the host port settings.

<img width="1187" alt="Screen Shot 2019-11-05 at 9 09 53 PM" src="https://user-images.githubusercontent.com/4266958/68270007-b5ee6e00-0010-11ea-9654-81b381aa4294.png">

**Comment by alena1108** [comment] 2019-11-06 18:24
@sangeethah the issue you are seeing, is diff. That's a regression introduced by initial fix. You can reproduce it by simply creating a new deployment with the hostport from the UI. I'll work on the fix

**Comment by sangeethah** [comment] 2019-11-08 05:13
Tested with latest rancher version - `v2.3-head` - `add7bda8f`
1. Create a new deployment with the hostport from the UI. On Edit view, able to see the host port displayed correctly.
On editing(with/without any changes) and saving , does not result in host port  loss.

2. Create a new deployment with the hostport from kubectl. On Edit view from UI, able to see the host port displayed correctly.
On editing(with/without any changes) and saving , does not result in host port  loss.
Further edits done on this deployment also does not result in host port  loss.

**Closed by sangeethah** 2019-11-08 05:13 UTC
Labels: [zube]: To Test, internal, team/ca
