### ISSUE TITLE
Rancher EBS does not play nice with rescheduling to different AZ

### ISSUE THREAD

**Issue by smazurov** [rancher/rancher#8283] opened 2017-03-23 21:52 UTC
**Rancher Versions:**
Server: 1.5.1
scheduler: v0.7.4

**Docker Version:** 1.12.6

**OS and where are the hosts located? (cloud, bare metal, etc):** Amazon Linux, AWS

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)** HA

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)** Cattle

**Steps to Reproduce:**

- Setup 2 hosts, one per AZ (for this, I was in us-west-1a and us-west-1c). Have `type=test-node` label attached to both hosts
- Create a new service with rancher-ebs backed volume (created manually in volumes tab), restrict it to run on that label only
- Evacuate one of the hosts, so our test service gets moved to the other host

**Results:** 

The service will fail to start as it cannot attach ebs volume cross AZ.

```
time="2017-03-23T23:14:03Z" level=error msg="Failed to attach, opts=={\"created\":\"true\",\"name\":\"redacted\",\"rancher\":\"true\",\"size\":\"10\",\"volumeID\":\"vol-redacted\",\"volumeType\":\"gp2\"}: An error occurred (InvalidVolume.ZoneMismatch) when calling the AttachVolume operation: The volume 'vol-redacted' is not in the same availability zone as instance 'i-redacted'"
time="2017-03-23T23:14:03Z" level=error msg=attach.response error="An error occurred (InvalidVolume.ZoneMismatch) when calling the AttachVolume operation: The volume 'vol-redacted' is not in the same availability zone as instance 'i-redacted'"
```

**Comment by ptcuops** [comment] 2017-03-24 14:26
The ticket title was about Rancher EBS, but in the description, you mentioned rancher-nfs. Assuming this was a type and you were indeed referring to EBS volumes, the single AZ restriction is an artifact of the underlying technology. AWS EBS volumes are not portable across AZ's. You can take a snapshot of an EBS volume and create an entirely new volume in a different AZ based on that snapshot, but that's about the extent of cross AZ portability for EBS volumes.

If your storage needs don't involve a ton of high speed back and forth traffic, you can consider using an EFS volume that is connected through your containers via Rancher EFS or NFS. There are limitations, of course. For instance, you probably wouldn't want to run a database on an EFS volume.

**Comment by cjellick** [comment] 2017-03-24 15:18
@StrongMonkey Is this a duplicate of one of the bugs you are working on?

**Comment by StrongMonkey** [comment] 2017-03-24 16:11
I think it is related to the scheduling part of the EBS volume we discussed @cjellick

**Comment by soumyalj** [comment] 2017-04-28 17:31
Tested with Master. Created 2 hosts with label "test=abc", host1 in AWS west zone and the host2 in AWS east zone. Launched a service "testser" with two containers using existing EBS volume and scheduling set to host with label "test=abc". Service was created successfully on host1. After evacuating host1, the containers of service "testser" and the volume do not move to host2 in the east zone. EBS volumes do not move across zones.

**Closed by soumyalj** 2017-04-28 17:31 UTC
Labels: kind/bug, status/resolved, status/to-test
