### ISSUE TITLE
Auto Theme Corrupted

### ISSUE THREAD

**Issue by Toonix** [rancher/rancher#7142] opened 2016-12-20 14:36 UTC
Rancher Version: 1.2.1

Docker Version: 1.12.3

OS and where are the hosts located? RancherOS, VMWareESX

Setup Details: (single node rancher, internal DB

Environment Type: (Cattle)

1. Changed Theme to Auto
2. Logout
3. Login

If you do that you only see XML Output. Change back to Light/Dark and relogin.

**Comment by willseward** [comment] 2016-12-20 16:05
Dup of #7090

**Comment by tfiduccia** [comment] 2016-12-20 18:51
Closing as duplicate of #7090.  Will be fixed in next version.

**Closed by tfiduccia** 2016-12-20 18:51 UTC
