### ISSUE TITLE
Error launching template with special characters its rancher-compose.yml

### ISSUE THREAD

**Issue by zambon** [rancher/rancher#5437] opened 2016-07-14 23:12 UTC
**Rancher Version:** 1.1.0

**Docker Version:** 1.11.2

**OS and where are the hosts located? (cloud, bare metal, etc):**

* Ubuntu 16.04 64-bit
* SoftLayer - Virtual machines

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**

* Single node rancher
* External database
* Single host (proxy + rancher + db in a Docker Compose file)

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)** Cattle

**Steps to Reproduce:**

1. Find [this template](https://gist.github.com/zambon/3007fd58687b18682621b665b499c4ec) in its private catalog and click `View Details`.
1. Fill in the form and click `Launch`.

**Results:** 

1. UI shows `Conflict`.
    ![Conflict](http://i.imgur.com/58GkHe3.png)
1. Rancher's container (`rancher/server:v1.1.0`) outputs [this](https://gist.githubusercontent.com/zambon/869693cc5f378350d938519bdef1b5c1/raw/2cdb5a68e289cc3b190966293b5bd386a1917de9/gistfile1.txt).

**Expected:**

* Stack is created successfully. This template used to work with Rancher v1.0.2.

The same problem is reproducible by using the REST API directly (response code 409).

**Comment by zambon** [comment] 2016-07-20 16:23
I was wrong! I deployed another Rancher instance in v1.0.2, and the template failed (except I got _Internal Server Error_ instead of _Conflict_).

It turned out there was a special character in `rancher-compose.yml`, as shown below.
![special-character](http://i.imgur.com/LpA9ei9.png)

```
$ git d HEAD^ HEAD 0/rancher-compose.yml
diff --git a/templates/seahorse/0/rancher-compose.yml b/templates/seahorse/0/rancher-compose.yml
index 1c7a383..96db14f 100644
--- a/templates/seahorse/0/rancher-compose.yml
+++ b/templates/seahorse/0/rancher-compose.yml
@@ -10,7 +10,7 @@
     blocks from the palette of available operations even less code savvy users
     are able to design workflows containing steps such as: ETL, data
     manipulation, clean-up and reports, even up to advanced predictive
-    analytics. Workflows exported from Seahorse are production<E2><80><91>ready and easy
+    analytics. Workflows exported from Seahorse are production-ready and easy
     to deploy on Apache Spark clusters.
 
   questions:
```

I'll rename this issue accordingly.

**Comment by tfiduccia** [comment] 2016-07-20 18:47
@zambon Closing - duplicate of #5342
Added the different hyphens to comment in bug to ensure testing once we get a fix.

**Closed by tfiduccia** 2016-07-20 18:47 UTC
Labels: area/catalog, kind/bug
