### ISSUE TITLE
KEv2 clusters imported using the Rancher client have their config improperly rewritten

### ISSUE THREAD

**Issue by thedadams** [rancher/rancher#36128] opened 2022-01-13 00:37 UTC
**Rancher Server Setup**
- Rancher version: v2.6-head
- Installation option (Docker install/Helm Chart): any
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): any
- Proxy/Cert Details: any

**Information about the Cluster**
- Kubernetes version:
- Cluster Type (Local/Downstream): Downstream
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider): imported KEv2
   
**Describe the bug**
If a KEv2 cluster is imported using the Rancher client (like with terraform), then the config will be improperly applied. For example, importing an EKS cluster with terraform while leaving out any mention of node groups (which is proper) will end up deleting all the node groups from the EKS cluster when it is imported into Rancher.

**To Reproduce**
Use the terraform provider to import an EKS cluster. Do not specify any node groups in the terraform config.

**Result**
All the node groups of the EKS cluster will be deleted after the EKS cluster is imported.

**Expected Result**
The cluster should be imported and not updated at all in EKS.

**Additional context**
The underlying issue here is that the slice types in the KEv2 structs have the struct tag `norman:pointer`. This is improper because a slice type is already a pointer.

To fix this:
1. All slices types in the three KEv2 operators need to have this struct tag removed.
2. The dependencies for these three operators should be bumped in Rancher.
3. Run `go generate` in Rancher.

After Rancher is updated, the terraform provider and the CLI also should be updated.

https://github.com/rancher/terraform-provider-rancher2/issues/800

SURE-3842
SURE-3833

**Comment by annablender** [comment] 2022-02-11 22:15
I fixed this issue with some direction from @thedadams. The source of the problem was unnecessary `norman:pointer` struct tags on the NodeGroup field in the <EKS/AKS/GKE>ClusterConfigSpec. Details in PR. I opened three PRs to fix each KEv2 operator and three more PRs to fix code in the terraform provider and bump the operator and crd versions in `rancher/rancher` and `rancher/charts.`

Fixes
* https://github.com/rancher/eks-operator/pull/59
* https://github.com/rancher/aks-operator/pull/52
* https://github.com/rancher/gke-operator/pull/73

Integration PRs
* https://github.com/rancher/rancher/pull/36461
* https://github.com/rancher/terraform-provider-rancher2/pull/860
* https://github.com/rancher/charts/pull/1725

**Comment by annablender** [comment] 2022-02-11 22:26
## Testing template

#### Root cause

Unnecessary `norman:pointer` struct tags on the `NodeGroups` field in the `ClusterConfigSpec` for each KEv2 provider.

#### What was fixed, or what changes have occurred

https://github.com/annablender/eks-operator/blob/3ebbab540c6c77741d9b549e21849c3fbeb22011/pkg/apis/eks.cattle.io/v1/types.go#L51

#### Areas or cases that should be tested
 
#### What areas could experience regressions ?
 
#### Are the repro steps accurate/minimal ?

**Comment by sowmyav27** [comment] 2022-02-16 15:20
**Test cases to validate:**
- Import EKS v2 into Rancher using TF
- Import EKS v2 in Rancher using Rancher UI
```
- Create an EKS cluster - `cluster-1` in AWS console (Latest k8s version). Add Node groups in this cluster in AWS console.
- Import this cluster in Rancher by navigating to Cluster Management --> Import --> EKS
- Add in the credentials, select the right region where EKS is created in AWS console.
- Select the cluster from the dropdown - `cluster-1`
- Click on Create/Save
- Verify the cluster comes up Active. And nodegroups/nodes are available on the cluster
- Edit cluster
- Add another nodegroup
- Save changes made
- Wait for the cluster to come back up Active.
- Verify in Rancher - all nodegroups including existing ones and the new one added is available.
- Verify in AWS, all nodegoups are available.
```
- Provision an EKS v2 cluster from Rancher UI

**Comment by timhaneunsoo** [comment] 2022-02-23 00:13
### Test Environment: ###
Rancher version: v2.6-head
Rancher cluster type: HA
Docker version: 20.10

Downstream cluster type: EKS v2 cluster

----------

### Testing: ###

Tested this issue with the following scenarios:
- Import EKS v2 into Rancher using TF
- Import EKS v2 in Rancher using Rancher UI
- Provision an EKS v2 cluster from Rancher UI

**Result**

- Import EKS v2 into Rancher using TF - Low Pass
The cluster gets added into Rancher but is stuck on `Waiting`

- Import EKS v2 in Rancher using Rancher UI - Low Pass
The cluster gets added into Rancher but is stuck on `Waiting`

- Provision an EKS v2 cluster from Rancher UI - Pass

**Comment by annablender** [comment] 2022-03-01 14:19
@timhaneunsoo I was unable to reproduce the specific error that you showed above. I did, however, test importing an EKS cluster on v2.6-head run on a DO node, and ran into an intermittent issue that I've seen before where the UI hangs with `Waiting for API to be available.`

This is my terraform config
```
terraform {
  required_providers {
    rancher2 = {
      source = "terraform.example.com/local/rancher2"
      version = "1.0.0"
    }
  }
}

provider "rancher2" {
  api_url    = "<DO node ip>"
  token_key = "<Rancher API bearer token>"
  insecure = true
}

resource "rancher2_cluster" "bar" {
  name = "ablender-eks-test"
  description = "Terraform EKS cluster"
  eks_config_v2 {
    cloud_credential_id = "cattle-global-data:<Rancher AWS cloud credential>"
    region = "us-east-2"
    imported = true
  }
}
```

Here's the result of trying to import EKS ablender-eks-test

![image](https://user-images.githubusercontent.com/12955547/156185912-877e2866-f543-450e-919d-862e3b656310.png)

The mgmt cluster shows `NodeGroups: null` in the `eksConfig` which` is correct. This means that node groups in EKS will not get deleted. The node group for my cluster is still active. @kinarashah and I believe this issue is fixed and I will open a new GitHub issue for the error I saw on 2.6-head.

This issue can be closed.

**Comment by annablender** [comment] 2022-03-01 23:18
Here's the new GH issue that blocked the EKS import https://github.com/rancher/rancher/issues/36700. To verify the fix for this issue, you can check the mgmt cluster yaml in the Rancher UI and verify that `NodeGroups: null.` If this is set, then the node deletion bug is fixed.

**Comment by timhaneunsoo** [comment] 2022-03-03 18:52
### Test Environment: ###
Rancher version: v2.6-head 
Rancher cluster type: HA
Docker version: 20.10

Downstream cluster type: EKS v2 cluster

----------

### Testing: ###

Retested this issue with the following scenarios:
- Import EKS v2 into Rancher using TF
- Import EKS v2 in Rancher using Rancher UI
- Provision an EKS v2 cluster from Rancher UI (Pass from previous testing)

**Result**

- Import EKS v2 into Rancher using TF - Pass
Node groups is set to `null` and node group is still preserved once importing into Rancher
![Screen Shot 2022-03-03 at 1.52.11 PM.png](https://zube.io/files/rancher/468325db2029baabcd742cc51916971a-screen-shot-2022-03-03-at-1-52-11-pm.png)


- Import EKS v2 in Rancher using Rancher UI - Pass
Node groups is set to `null` and node group is still preserved once importing into Rancher
![Screen Shot 2022-03-02 at 6.49.30 PM.png](https://zube.io/files/rancher/eaa497b73f1b781cf73a3779ac68c4e1-screen-shot-2022-03-02-at-6-49-30-pm.png)

- Provision an EKS v2 cluster from Rancher UI - Pass (from previous testing)

**Closed by timhaneunsoo** 2022-03-03 18:52 UTC
Labels: internal, area/cli, area/gke, area/aks, area/eks, area/terraform, [zube]: QA Working, QA/S, feature/kev2, team/area2
