### ISSUE TITLE
Add support for GCR

### ISSUE THREAD

**Issue by StrongMonkey** [rancher/rancher#6956] opened 2016-12-06 19:18 UTC
We need to support adding a json file as the password field in adding private registry.
Issues: For Google Container Registry, users could use their own json file as their private key but when we copy the contents we are automatically stripping off the newline `/n`. Our go-agent needs that to pull private image.
Expected: Add support for GCR. Specifically, add an option to upload a key-file as the password fields and do not strip '/n' off.

**Comment by deniseschannon** [comment] 2016-12-06 19:52
Duplicate of https://github.com/rancher/rancher/issues/5132

**Comment by untoldone** [comment] 2016-12-07 19:40
Just wanted to mention -- I don't know what Rancher's github bug labels represent, but I personally feel this might be a bug rather than being a new feature as it seems to be described in the title? It is a regression for those who depend on a private GCR registry. The regression single-handedly prevents me from being able to run 1.2 / 1.2.1 in production since it was supported in prior version.

Thanks again for all your work! I'm sure you're all getting slammed with this stuff. Really appreciate the time.

**Comment by StrongMonkey** [comment] 2016-12-08 01:26
@vincent99 can you make the change in UI for it?

**Comment by StrongMonkey** [comment] 2016-12-15 17:16
@vincent99  I am able to fix it in the backend

**Comment by StrongMonkey** [comment] 2016-12-16 17:03
@sangeethah Can you test the scenario i referenced in this issue? I believe it is fixed cause i tested myself but just want you to double-check.

**Comment by soumyalj** [comment] 2016-12-20 04:40
Tested with v1.3.0-rc1. Pushed an ubuntu image to the Google Container Registry. Added the GCR registry to rancher by providing password as a json file. Created a service by using the image pushed to GCR. Image pull and service creation was successful.

**Closed by soumyalj** 2016-12-20 04:40 UTC
Labels: area/registry, kind/bug, status/resolved, status/to-test

**Comment by ZGF4** [comment] 2017-03-10 20:41
I'm having issues doing this. Pasting the json file as the password does not seem to be working. Any ideas?

**Comment by StrongMonkey** [comment] 2017-03-10 21:01
@ZGF4 which rancher server version are you running now?

**Comment by joantune** [comment] 2017-07-23 14:43
For anyone coming here to search on how to add Google Container's Engine to Rancher - create a Service Account, add permissions to it to the corresponding bucket on Google Storage - and follow the instructions here:

https://cloud.google.com/container-registry/docs/advanced-authentication

in short: add the host with the username _json_key and the json file as a password

**Comment by superseb** [comment] 2017-07-23 15:12
Thanks @joantune , this should be in the docs soon: https://github.com/rancher/rancher.github.io/pull/836

**Comment by ralstan-vaz** [comment] 2018-10-08 18:52
Trying to use the user as  _json_key and the password as json file contents with rancher 2.0.8.
It does not seem to work. is there any work around for this ?

**Comment by leodotcloud** [comment] 2018-12-14 16:40
@ralstan-vaz I ran into the same problem, but then I realized I was missing a config when launching a Pod.

  ```
imagePullSecrets:
  - name: registry-secret-name
```


It would be nice to have this feature implemented: https://github.com/rancher/rancher/issues/17005, especially:

> Mandatory: Including the following statement automatically within the yaml file when deploying an image as already stated by other people in other messages.

Steps:

Add Registry>
Custom: `gcr.io/myregistry`
Name: `myregistry`
Username: `_json_key`
Password: `copy paste of the contents of the service account json file`

Now when launching a Pod:
```
apiVersion: v1
kind: Pod
metadata:
  name: nato-pod
spec:
  imagePullSecrets:
  - name: myregistry
  containers:
    - name: nato
      image: gcr.io/myregistry/leodotcloud/swiss-army-knife
```

Hope this helps.
