### ISSUE TITLE
Navigation bar on Rancher UI showing incorrect values

### ISSUE THREAD

**Issue by sowmyav27** [rancher/rancher#21950] opened 2019-08-02 22:36 UTC
**What kind of request is this (question/bug/enhancement/feature request):** bug

**Steps to reproduce (least amount of steps as possible):**
On 2.2.7-rc-2
- Edit a node template (AWS)
- save the changes
- the navigation bar is shown like this .
<img width="1497" alt="Screen Shot 2019-08-02 at 12 07 16 PM" src="https://user-images.githubusercontent.com/26032343/62402144-2cc02a80-b53b-11e9-9358-66421922097f.png">

**Note:**
On a refresh of the page, the page is restored to normal values.
This happens sometimes and not always.

**Comment by tfiduccia** [comment] 2019-09-03 19:55
@sowmyav27 - I've tried multiple times and I can't reproduce?  Are you still seeing this happen?  What type of cluster is Rancher on?

**Comment by sowmyav27** [comment] 2019-09-03 20:44
@tfiduccia I dont see it happen all the time. I have not noticed it on latest master as such.

**Comment by vicparker** [comment] 2019-09-05 22:05
Notice the same UI anomalies, but inconsistent.  Rancher 2.2.8 server on ESX VM.  Browser console log attached.

[104.154.224.236-1567719489982-console-out.txt](https://github.com/rancher/rancher/files/3581390/104.154.224.236-1567719489982-console-out.txt)

**Comment by tfiduccia** [comment] 2019-09-05 22:30
We need to research this and see if there is something we can do.

**Comment by deniseschannon** [comment] 2019-10-05 15:33
Duplicate of https://github.com/rancher/rancher/issues/22985

**Closed** 2019-10-05 15:33 UTC
Labels: [zube]: To Triage, kind/bug-qa, team/ui
