### ISSUE TITLE
App upgrade failure: panic at go/src/k8s.io/helm/pkg/tiller/release_update.go:166

### ISSUE THREAD

**Issue by zhongguanqun** [rancher/rancher#21070] opened 2019-06-23 01:48 UTC
What kind of request is this (question/bug/enhancement/feature request):
**panic: runtime error: invalid memory address or nil pointer dereference**
[signal SIGSEGV: segmentation violation code=0x1 addr=0x50 pc=0x12e8cc8]

goroutine 15 [running]:
k8s.io/helm/pkg/tiller.(*ReleaseServer).performUpdateForce(0xc420819860, 0xc42052a8c0, 0x0, 0x0, 0x17b7b40)
	/go/src/k8s.io/helm/pkg/tiller/release_update.go:166 +0x188
k8s.io/helm/pkg/tiller.(*ReleaseServer).UpdateRelease(0xc420819860, 0x17d8960, 0xc420932210, 0xc42052a8c0, 0xc420819860, 0x16b98a6, 0xd)
	/go/src/k8s.io/helm/pkg/tiller/release_update.go:43 +0x245
k8s.io/helm/pkg/proto/hapi/services._ReleaseService_UpdateRelease_Handler.func1(0x17d8960, 0xc420932210, 0x16066c0, 0xc42052a8c0, 0x32, 0xc42052aa50, 0x1, 0x1681d11)
	/go/src/k8s.io/helm/pkg/proto/hapi/services/tiller.pb.go:1244 +0x86
k8s.io/helm/vendor/github.com/grpc-ecosystem/go-grpc-prometheus.(*ServerMetrics).UnaryServerInterceptor.func1(0x17d8960, 0xc420932210, 0x16066c0, 0xc42052a8c0, 0xc42094e6e0, 0xc42094e700, 0x48, 0xc42094e5c0, 0xc420a37a40, 0x4108c8)
	/go/src/k8s.io/helm/vendor/github.com/grpc-ecosystem/go-grpc-prometheus/server_metrics.go:86 +0xdb
k8s.io/helm/pkg/tiller.newUnaryInterceptor.func1(0x17d8960, 0xc420932210, 0x16066c0, 0xc42052a8c0, 0xc42094e6e0, 0xc42094e700, 0xc420655ab0, 0x4108c8, 0x50, 0x15d88a0)
	/go/src/k8s.io/helm/pkg/tiller/server.go:60 +0xab
k8s.io/helm/pkg/proto/hapi/services._ReleaseService_UpdateRelease_Handler(0x1640500, 0xc420819860, 0x17d8960, 0xc420932210, 0xc42052a870, 0x1715568, 0x0, 0x0, 0xc4207a2800, 0x0)
	/go/src/k8s.io/helm/pkg/proto/hapi/services/tiller.pb.go:1246 +0x167
k8s.io/helm/vendor/google.golang.org/grpc.(*Server).processUnaryRPC(0xc4200d1540, 0x17e14a0, 0xc42031f1e0, 0xc4204b4100, 0xc4208198f0, 0x2162cf0, 0x0, 0x0, 0x0)
	/go/src/k8s.io/helm/vendor/google.golang.org/grpc/server.go:826 +0x9c8
k8s.io/helm/vendor/google.golang.org/grpc.(*Server).handleStream(0xc4200d1540, 0x17e14a0, 0xc42031f1e0, 0xc4204b4100, 0x0)
	/go/src/k8s.io/helm/vendor/google.golang.org/grpc/server.go:1023 +0x1318
k8s.io/helm/vendor/google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc42080efc0, 0xc4200d1540, 0x17e14a0, 0xc42031f1e0, 0xc4204b4100)
	/go/src/k8s.io/helm/vendor/google.golang.org/grpc/server.go:572 +0x9f
created by k8s.io/helm/vendor/google.golang.org/grpc.(*Server).serveStreams.func1
	/go/src/k8s.io/helm/vendor/google.golang.org/grpc/server.go:570 +0xa1
2019/06/23 01:41:27 **[ERROR] AppController p-pqlm4/cluster-alerting [helm-controller] failed with : failed to install app cluster-alerting. Error: UPGRADE FAILED: transport is closing**

**Steps to reproduce (least amount of steps as possible):**

**Result:**

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI):
- Installation option (single install/HA):

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported):
- Machine type (cloud/VM/metal) and specifications (CPU/memory):
- Kubernetes version (use `kubectl version`):

```
(paste the output here)
```

- Docker version (use `docker version`):
18.09.6-3.el7.x86_64

```
(paste the output here)
```

**Comment by davidnuzik** [comment] 2019-06-24 16:35
I tested on single-node rancher (issue did not specify if HA or not) with v2.2.2 -> v2.2.4 upgrade (have cluster-alerting on before upgrade).
I did _not_ get a panic in my particular case, but I did see a lot of errors in the logs complaining about:
![image](https://user-images.githubusercontent.com/45179589/60036086-38c6eb80-9663-11e9-8ad8-e8564b285ef6.png)
Then eventually
![image](https://user-images.githubusercontent.com/45179589/60036109-47150780-9663-11e9-8bb9-fa330638399a.png)

@zhongguanqun was this setup single-node rancher or HA setup? Anything else we should know?

**Comment by alena1108** [comment] 2019-06-24 20:03
https://github.com/helm/helm/issues/4672

**Comment by LaysDragon** [comment] 2019-08-01 03:10
Tiller crash while I trying to upgrade openebs....
Good news seems the bug is fixed in new version of helm
Bad news is helm version is 2.1.10 in rancher single node deployment image
Can you plan to upgrade the version of helm in new version of rancher?

**Comment by LaysDragon** [comment] 2019-08-01 03:12
Even I may can upgrade the helm version in rancher image myself,but I not sure if the rancher is compatible to new version of helm..that is too annoying that my application is stuck and cannot upgrade.

**Comment by dnoland1** [comment] 2019-09-22 00:10
Customer hit this problem today, or at least the same error. After attempting to deploy cluster monitoring on v2.2.7, got error: `Failed to install app cluster-monitoring. Error: UPGRADE FAILED: transport is closing` and seeing this in the logs:
```
[storage] 2019/09/21 21:04:44 getting last revision of "cluster-monitoring"
[storage] 2019/09/21 21:04:44 getting release history for "cluster-monitoring"
[storage] 2019/09/21 21:04:44 getting release history for "cluster-monitoring"
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x50 pc=0x12e8cc8]
goroutine 71 [running]:
k8s.io/helm/pkg/tiller.(*ReleaseServer).performUpdateForce(0xc4205be000, 0xc4200ba870, 0x0, 0x0, 0x17b7b40)
/go/src/k8s.io/helm/pkg/tiller/release_update.go:166 +0x188
k8s.io/helm/pkg/tiller.(*ReleaseServer).UpdateRelease(0xc4205be000, 0x17d8960, 0xc420814e40, 0xc4200ba870, 0xc4205be000, 0x16b98a6, 0xd)
/go/src/k8s.io/helm/pkg/tiller/release_update.go:43 +0x245
k8s.io/helm/pkg/proto/hapi/services._ReleaseService_UpdateRelease_Handler.func1(0x17d8960, 0xc420814e40, 0x16066c0, 0xc4200ba870, 0x32, 0xc4200baa00, 0x1, 0x1681d11)
/go/src/k8s.io/helm/pkg/proto/hapi/services/tiller.pb.go:1244 +0x86
k8s.io/helm/vendor/github.com/grpc-ecosystem/go-grpc-prometheus.(*ServerMetrics).UnaryServerInterceptor.func1(0x17d8960, 0xc420814e40, 0x16066c0, 0xc4200ba870, 0xc4208d2e00, 0xc4208d2e20, 0x48, 0xc4208d2ac0, 0xc42071fa40, 0x4108c8)
/go/src/k8s.io/helm/vendor/github.com/grpc-ecosystem/go-grpc-prometheus/server_metrics.go:86 +0xdb
k8s.io/helm/pkg/tiller.newUnaryInterceptor.func1(0x17d8960, 0xc420814e40, 0x16066c0, 0xc4200ba870, 0xc4208d2e00, 0xc4208d2e20, 0xc420709ab0, 0x4108c8, 0x50, 0x15d88a0)
/go/src/k8s.io/helm/pkg/tiller/server.go:60 +0xab
k8s.io/helm/pkg/proto/hapi/services._ReleaseService_UpdateRelease_Handler(0x1640500, 0xc4205be000, 0x17d8960, 0xc420814e40, 0xc4200ba820, 0x1715568, 0x0, 0x0, 0x136d814, 0x9)
/go/src/k8s.io/helm/pkg/proto/hapi/services/tiller.pb.go:1246 +0x167
k8s.io/helm/vendor/google.golang.org/grpc.(*Server).processUnaryRPC(0xc4201c3680, 0x17e14a0, 0xc4201a8160, 0xc420912000, 0xc4205be0c0, 0x2162cf0, 0x0, 0x0, 0x0)
/go/src/k8s.io/helm/vendor/google.golang.org/grpc/server.go:826 +0x9c8
k8s.io/helm/vendor/google.golang.org/grpc.(*Server).handleStream(0xc4201c3680, 0x17e14a0, 0xc4201a8160, 0xc420912000, 0x0)
/go/src/k8s.io/helm/vendor/google.golang.org/grpc/server.go:1023 +0x1318
k8s.io/helm/vendor/google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc42080e390, 0xc4201c3680, 0x17e14a0, 0xc4201a8160, 0xc420912000)
/go/src/k8s.io/helm/vendor/google.golang.org/grpc/server.go:572 +0x9f
created by k8s.io/helm/vendor/google.golang.org/grpc.(*Server).serveStreams.func1
/go/src/k8s.io/helm/vendor/google.golang.org/grpc/server.go:570 +0xa1
2019/09/21 21:04:45 [ERROR] AppController p-rrwdl/cluster-monitoring [helm-controller] failed with : failed to install app cluster-monitoring. Error: UPGRADE FAILED: transport is closing
2019/09/21 21:04:46 [INFO] error in remotedialer server [400]: read tcp 10.42.0.86:80->10.42.1.0:42224: i/o timeout
2019/09/21 21:04:47 [ERROR] ClusterController c-b6zhw [cluster-monitoring-handler] failed with : failed to get cattle-prometheus/prometheus-operated endpoints: endpoints "cattle-prometheus/prometheus-operated" not found
2019/09/21 21:04:50 [INFO] Handling backend connection request [c-b6zhw:m-97b69a24f99c]
```

**Comment by kinarashah** [comment] 2019-09-23 21:33
https://github.com/rancher/rancher/issues/23017

**Comment by alena1108** [comment] 2019-09-24 23:09
@dramich have to cherry-pick https://github.com/helm/helm/pull/4630/files to our helm fork

**Comment by sowmyav27** [comment] 2019-09-25 23:00
**Reproduced the issue on rancher:v2.2.7**
**Steps:**
1. Set Chart repo URL with a custom chart catalog.
2. Use kubectl apply -f <pv-test.yaml>
3. Launch Longhorn v0.5.0 and wait for active.
4. Upgrade to v0.6.0. (invalid version) Wait until (typically 5~10 minutes) error message `Failed to install app longhorn-system. Error: UPGRADE FAILED: timed out waiting for the condition` is seen on app detail page.
5. Try to rollback to the first revision (it’s version v0.5.0). The error message `Failed to install app longhorn-system. Error: UPGRADE FAILED: transport is closing occurs`
Rancher logs shows a panic
```
[storage] 2019/09/25 22:56:23 getting release history for "longhorn-system"
[storage] 2019/09/25 22:56:23 getting release history for "longhorn-system"
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x50 pc=0x12e8cc8]

goroutine 41 [running]:
k8s.io/helm/pkg/tiller.(*ReleaseServer).performUpdateForce(0xc42077ee70, 0xc4202ec2d0, 0x0, 0x0, 0x17b7b40)
	/go/src/k8s.io/helm/pkg/tiller/release_update.go:166 +0x188
k8s.io/helm/pkg/tiller.(*ReleaseServer).UpdateRelease(0xc42077ee70, 0x17d8960, 0xc420816060, 0xc4202ec2d0, 0xc42077ee70, 0x16b98a6, 0xd)
	/go/src/k8s.io/helm/pkg/tiller/release_update.go:43 +0x245
k8s.io/helm/pkg/proto/hapi/services._ReleaseService_UpdateRelease_Handler.func1(0x17d8960, 0xc420816060, 0x16066c0, 0xc4202ec2d0, 0x32, 0xc4202ec870, 0x1, 0x1681d11)
	/go/src/k8s.io/helm/pkg/proto/hapi/services/tiller.pb.go:1244 +0x86
k8s.io/helm/vendor/github.com/grpc-ecosystem/go-grpc-prometheus.(*ServerMetrics).UnaryServerInterceptor.func1(0x17d8960, 0xc420816060, 0x16066c0, 0xc4202ec2d0, 0xc42091a220, 0xc42091a240, 0x48, 0xc42091a100, 0xc42012da40, 0x4108c8)
	/go/src/k8s.io/helm/vendor/github.com/grpc-ecosystem/go-grpc-prometheus/server_metrics.go:86 +0xdb
k8s.io/helm/pkg/tiller.newUnaryInterceptor.func1(0x17d8960, 0xc420816060, 0x16066c0, 0xc4202ec2d0, 0xc42091a220, 0xc42091a240, 0xc42080fab0, 0x4108c8, 0x50, 0x15d88a0)
	/go/src/k8s.io/helm/pkg/tiller/server.go:60 +0xab
k8s.io/helm/pkg/proto/hapi/services._ReleaseService_UpdateRelease_Handler(0x1640500, 0xc42077ee70, 0x17d8960, 0xc420816060, 0xc4202ec230, 0x1715568, 0x0, 0x0, 0xc420058800, 0x0)
	/go/src/k8s.io/helm/pkg/proto/hapi/services/tiller.pb.go:1246 +0x167
k8s.io/helm/vendor/google.golang.org/grpc.(*Server).processUnaryRPC(0xc4200c3400, 0x17e14a0, 0xc4205e9ce0, 0xc420604a00, 0xc42077ef00, 0x2162cf0, 0x0, 0x0, 0x0)
	/go/src/k8s.io/helm/vendor/google.golang.org/grpc/server.go:826 +0x9c8
k8s.io/helm/vendor/google.golang.org/grpc.(*Server).handleStream(0xc4200c3400, 0x17e14a0, 0xc4205e9ce0, 0xc420604a00, 0x0)
	/go/src/k8s.io/helm/vendor/google.golang.org/grpc/server.go:1023 +0x1318
k8s.io/helm/vendor/google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc420601a40, 0xc4200c3400, 0x17e14a0, 0xc4205e9ce0, 0xc420604a00)
	/go/src/k8s.io/helm/vendor/google.golang.org/grpc/server.go:572 +0x9f
created by k8s.io/helm/vendor/google.golang.org/grpc.(*Server).serveStreams.func1
	/go/src/k8s.io/helm/vendor/google.golang.org/grpc/server.go:570 +0xa1
2019/09/25 22:56:23 [ERROR] AppController p-jmzwq/longhorn-system [helm-controller] failed with : failed to install app longhorn-system. Error: UPGRADE FAILED: transport is closing
```

**Comment by sowmyav27** [comment] 2019-09-26 00:04
**Verified on master-head latest**
**Steps:**

- Set Chart repo URL with a custom chart catalog.
- Use kubectl apply -f <pv-test.yaml>
- Launch Longhorn v0.5.0 and wait for active.
- Upgrade to v0.6.0. (invalid version) Wait until (typically 5~10 minutes) error message Failed to install app longhorn-system. Error: UPGRADE FAILED: timed out waiting for the condition is seen on app detail page.
- Try to rollback to the first revision (it’s version v0.5.0). Error is seen - `Failed to install app longhorn-system. Error: UPGRADE FAILED: a released named longhorn-system is in use, cannot re-use a name that is still in use`

**Rancher logs:**
```
[storage] 2019/09/26 00:00:47 getting deployed releases from "longhorn-system" history
2019/09/26 00:00:47 [ERROR] AppController p-69bgj/longhorn-system [helm-controller] failed with : failed to install app longhorn-system. Error: UPGRADE FAILED: timed out waiting for the condition

[main] 2019/09/26 00:00:47 Starting Tiller v2.10+unreleased (tls=false)
[main] 2019/09/26 00:00:47 GRPC listening on :34322
[main] 2019/09/26 00:00:47 Probes listening on :48706
[main] 2019/09/26 00:00:47 Storage driver is ConfigMap
[main] 2019/09/26 00:00:47 Max history per release is 1
[tiller] 2019/09/26 00:00:47 getting history for release longhorn-system
[storage] 2019/09/26 00:00:47 getting release history for "longhorn-system"
[tiller] 2019/09/26 00:00:47 preparing update for longhorn-system
[storage] 2019/09/26 00:00:47 getting deployed releases from "longhorn-system" history
[storage] 2019/09/26 00:00:48 getting last revision of "longhorn-system"
[storage] 2019/09/26 00:00:48 getting release history for "longhorn-system"
[storage] 2019/09/26 00:00:48 getting release history for "longhorn-system"
[tiller] 2019/09/26 00:00:48 failed update prepare step: a released named longhorn-system is in use, cannot re-use a name that is still in use
2019/09/26 00:00:48 [ERROR] AppController p-69bgj/longhorn-system [helm-controller] failed with : failed to install app longhorn-system. Error: UPGRADE FAILED: a released named longhorn-system is in use, cannot re-use a name that is still in use
```
No panic seen.

**Comment by mrajashree** [comment] 2019-09-26 00:22
This error isn't longhorn specific. We set tiller max history to 1. When the upgrade to 0.6.0 (invalid version) was unsuccessful, the revision created for it went in "PENDING_UPGRADE" state.
When rolling back to 0.5.0, [tiller](https://github.com/rancher/helm/blob/86a8197b91561255c94e33be1816299f6d14186f/pkg/tiller/release_update.go#L39) tries getting all releases in "DEPLOYED" state.
It doesn't get any, and tries creating a new revision replacing any existing ones. However this is allowed only if the existing revision is in "DELETED" or "FAILED" state. Since the release corresponding to 0.6.0 is still in "PENDING_UPGRADE" [this](https://github.com/rancher/helm/blob/86a8197b91561255c94e33be1816299f6d14186f/pkg/tiller/release_server.go#L195) returns an error

**Comment by alena1108** [comment] 2019-09-26 02:07
@dramich for 2.3.0, we should change the default for TILLER_HISTORY_MAX from 1 to 10

cc @daxmc99

**Comment by sowmyav27** [comment] 2019-09-26 23:06
Verified with rancher `master-head` latest

**Steps:**

Bring up an rke cluster DO - 3 nodes - all roles. Create a project p1, and namespace ns1.
Set Chart repo URL with a custom chart catalog.
Use kubectl apply -f <pv-test.yaml>
Launch Longhorn v0.5.0 and wait for active.
Upgrade to v0.6.0. (invalid version) Wait until (typically 5~10 minutes) error message `Failed to install app longhorn-system. Error: UPGRADE FAILED: timed out waiting for the condition` is seen on app detail page.
Rollback to v0.5.0.

In one cluster, the above set of steps resulted in the following error:
`Failed to install app longhorn-system. Error: UPGRADE FAILED: Job failed: DeadlineExceeded`

**Rancher logs:**
```
[kube] 2019/09/26 22:19:41 Looks like there are no changes for Deployment "longhorn-ui"
2019/09/26 22:19:41 [DEBUG] Requesting user: user-4c5w7, Requesting groups: [system:authenticated] Impersonate user:  Impersonate group: []
2019/09/26 22:19:41 [DEBUG] Triggering auth refresh on user-4c5w7
2019/09/26 22:19:41 [DEBUG] Skipping refresh for user-4c5w7 due to max-age
2019/09/26 22:19:41 [DEBUG] GET: 3.376032msclusters
[tiller] 2019/09/26 22:19:41 executing 2 post-upgrade hooks for longhorn-system
2019/09/26 22:19:41 [DEBUG] Requesting user: user-4c5w7, Requesting groups: [system:authenticated] Impersonate user:  Impersonate group: []
2019/09/26 22:19:41 [DEBUG] Triggering auth refresh on user-4c5w7
2019/09/26 22:19:41 [DEBUG] Skipping refresh for user-4c5w7 due to max-age
2019/09/26 22:19:41 [DEBUG] GET: 3.523147msclusters
[kube] 2019/09/26 22:19:41 building resources from manifest
[kube] 2019/09/26 22:19:41 warning: failed to load schema: SchemaError(io.k8s.api.apps.v1beta1.StatefulSetCondition): invalid object doesn't have additional properties
[kube] 2019/09/26 22:19:41 creating 1 resource(s)
2019/09/26 22:19:41 [DEBUG] Requesting user: user-4c5w7, Requesting groups: [system:authenticated] Impersonate user:  Impersonate group: []
2019/09/26 22:19:41 [DEBUG] Triggering auth refresh on user-4c5w7
2019/09/26 22:19:41 [DEBUG] Skipping refresh for user-4c5w7 due to max-age
2019/09/26 22:19:41 [DEBUG] GET: 3.193001msclusters
[kube] 2019/09/26 22:19:41 warning: failed to load schema: SchemaError(io.k8s.api.apps.v1beta1.StatefulSetCondition): invalid object doesn't have additional properties
2019/09/26 22:19:41 [DEBUG] Requesting user: user-4c5w7, Requesting groups: [system:authenticated] Impersonate user:  Impersonate group: []
2019/09/26 22:19:41 [DEBUG] Triggering auth refresh on user-4c5w7
2019/09/26 22:19:41 [DEBUG] Skipping refresh for user-4c5w7 due to max-age
2019/09/26 22:19:41 [DEBUG] GET: 3.342981msclusters
[kube] 2019/09/26 22:19:41 Watching for changes to Job longhorn-post-upgrade with timeout of 5m0s
[kube] 2019/09/26 22:19:42 Add/Modify event for longhorn-post-upgrade: ADDED
[tiller] 2019/09/26 22:19:42 warning: Release longhorn-system post-upgrade longhorn/templates/postupgrade-job.yaml could not complete: Job failed: DeadlineExceeded
2019/09/26 22:19:42 suppressing panic for copyResponse error in test; copy error: context canceled
2019/09/26 22:19:42 [DEBUG] Stopping Tiller
2019/09/26 22:19:42 [DEBUG] REST CREATE apis/project.cattle.io/v3/p-rfmhl/apprevisions
2019/09/26 22:19:42 [DEBUG] REST UPDATE apis/project.cattle.io/v3/p-rfmhl/apps/longhorn-system
2019/09/26 22:19:42 [DEBUG] AppController calling handler app-state-controller p-rfmhl/longhorn-system
2019/09/26 22:19:42 [DEBUG] AppController calling handler istio-app-handler p-rfmhl/longhorn-system
2019/09/26 22:19:42 [ERROR] AppController p-rfmhl/longhorn-system [helm-controller] failed with : failed to install app longhorn-system. Error: UPGRADE FAILED: Job failed: DeadlineExceeded

2019/09/26 22:19:42 [DEBUG] AppController calling handler helm-controller p-rfmhl/longhorn-system
2019/09/26 22:19:42 [DEBUG] AppController calling handler helm-controller p-rfmhl/longhorn-system

```

In another cluster, the above set of steps resulted in the following error:
`Failed to install app longhorn-system. Error: UPGRADE FAILED: timed out waiting for the condition`

**Rancher logs :**
```
2019/09/26 22:49:07 [ERROR] AppController p-8xjws/longhorn-system [helm-controller] failed with : failed to install app longhorn-system. Error: UPGRADE FAILED: timed out waiting for the condition

[main] 2019/09/26 22:49:44 Starting Tiller v2.10+unreleased (tls=false)
[main] 2019/09/26 22:49:44 GRPC listening on :55998
[main] 2019/09/26 22:49:44 Probes listening on :55159
[main] 2019/09/26 22:49:44 Storage driver is ConfigMap
[main] 2019/09/26 22:49:44 Max history per release is 10
[tiller] 2019/09/26 22:49:45 getting history for release longhorn-system
[storage] 2019/09/26 22:49:45 getting release history for "longhorn-system"
[tiller] 2019/09/26 22:49:45 preparing update for longhorn-system
[storage] 2019/09/26 22:49:45 getting deployed releases from "longhorn-system" history
[storage] 2019/09/26 22:49:45 getting last revision of "longhorn-system"
[storage] 2019/09/26 22:49:45 getting release history for "longhorn-system"
[tiller] 2019/09/26 22:49:45 rendering longhorn chart using values
2019/09/26 22:49:45 info: manifest "longhorn/templates/ingress.yaml" is empty. Skipping.
2019/09/26 22:49:45 info: manifest "longhorn/templates/tls-secrets.yaml" is empty. Skipping.
[kube] 2019/09/26 22:49:46 warning: failed to load schema: SchemaError(io.k8s.apimachinery.pkg.apis.meta.v1.Preconditions): invalid object doesn't have additional properties
[tiller] 2019/09/26 22:49:46 creating updated release for longhorn-system
[storage] 2019/09/26 22:49:46 creating release "longhorn-system.v3"
[storage] 2019/09/26 22:49:46 getting release history for "longhorn-system"
[tiller] 2019/09/26 22:49:46 performing update for longhorn-system
[tiller] 2019/09/26 22:49:46 executing 2 pre-upgrade hooks for longhorn-system
[tiller] 2019/09/26 22:49:46 hooks complete for pre-upgrade longhorn-system
[kube] 2019/09/26 22:49:46 warning: failed to load schema: SchemaError(io.k8s.apimachinery.pkg.apis.meta.v1.Preconditions): invalid object doesn't have additional properties
[kube] 2019/09/26 22:49:46 building resources from updated manifest
[kube] 2019/09/26 22:49:46 warning: failed to load schema: SchemaError(io.k8s.apimachinery.pkg.apis.meta.v1.Preconditions): invalid object doesn't have additional properties
[kube] 2019/09/26 22:49:46 checking 15 resources for changes
[kube] 2019/09/26 22:49:46 Looks like there are no changes for StorageClass "longhorn"
[kube] 2019/09/26 22:49:46 Looks like there are no changes for ServiceAccount "longhorn-service-account"
[kube] 2019/09/26 22:49:46 Looks like there are no changes for CustomResourceDefinition "settings.longhorn.rancher.io"
[kube] 2019/09/26 22:49:46 Looks like there are no changes for CustomResourceDefinition "replicas.longhorn.rancher.io"
[kube] 2019/09/26 22:49:47 Looks like there are no changes for CustomResourceDefinition "engines.longhorn.rancher.io"
[kube] 2019/09/26 22:49:47 Looks like there are no changes for CustomResourceDefinition "volumes.longhorn.rancher.io"
[kube] 2019/09/26 22:49:47 Looks like there are no changes for CustomResourceDefinition "engineimages.longhorn.rancher.io"
[kube] 2019/09/26 22:49:47 Looks like there are no changes for CustomResourceDefinition "nodes.longhorn.rancher.io"
[kube] 2019/09/26 22:49:47 Looks like there are no changes for ClusterRole "longhorn-role"
[kube] 2019/09/26 22:49:47 Looks like there are no changes for ClusterRoleBinding "longhorn-bind"
[kube] 2019/09/26 22:49:48 Looks like there are no changes for Service "longhorn-backend"
[kube] 2019/09/26 22:49:48 Looks like there are no changes for Service "longhorn-frontend"
[kube] 2019/09/26 22:49:48 Looks like there are no changes for DaemonSet "longhorn-manager"
[kube] 2019/09/26 22:49:48 Looks like there are no changes for Deployment "longhorn-driver-deployer"
[kube] 2019/09/26 22:49:48 Looks like there are no changes for Deployment "longhorn-ui"
[tiller] 2019/09/26 22:49:48 executing 2 post-upgrade hooks for longhorn-system
[kube] 2019/09/26 22:49:48 building resources from manifest
[kube] 2019/09/26 22:49:48 warning: failed to load schema: SchemaError(io.k8s.apimachinery.pkg.apis.meta.v1.Preconditions): invalid object doesn't have additional properties
[kube] 2019/09/26 22:49:48 creating 1 resource(s)
[kube] 2019/09/26 22:49:48 warning: failed to load schema: SchemaError(io.k8s.apimachinery.pkg.apis.meta.v1.Preconditions): invalid object doesn't have additional properties
[kube] 2019/09/26 22:49:49 Watching for changes to Job longhorn-post-upgrade with timeout of 5m0s
[kube] 2019/09/26 22:49:49 Add/Modify event for longhorn-post-upgrade: ADDED
[kube] 2019/09/26 22:49:49 longhorn-post-upgrade: Jobs active: 1, jobs failed: 0, jobs succeeded: 0
2019-09-26 22:50:54.414237 I | mvcc: store.index: compact 4045
2019-09-26 22:50:54.416819 I | mvcc: finished scheduled compaction at 4045 (took 1.362324ms)
[tiller] 2019/09/26 22:54:49 warning: Release longhorn-system post-upgrade longhorn/templates/postupgrade-job.yaml could not complete: timed out waiting for the condition
2019/09/26 22:54:49 suppressing panic for copyResponse error in test; copy error: context canceled
2019/09/26 22:54:49 [ERROR] AppController p-8xjws/longhorn-system [helm-controller] failed with : failed to install app longhorn-system. Error: UPGRADE FAILED: timed out waiting for the condition

2019-09-26 22:55:54.418919 I | mvcc: store.index: compact 4679
2019-09-26 22:55:54.421261 I | mvcc: finished scheduled compaction at 4679 (t
```


- Also, on rolling back, it took about 5 minutes for the new revision id to be displayed in the drop down when you click on `Rollback`

**Comment by mrajashree** [comment] 2019-09-27 23:43
Saw the same behavior using upstream helm too.
Tested with these steps
1. Packaged longhorn app's 0.5.0 and 0.6.0 versions into a chart repo, added this chart repo to minikube cluster
2. Installed longhorn 0.5.0
3. Tiller creates a revision which is shown in "DEPLOYED" state.
```
➜  ~ helm ls
NAME           	REVISION	UPDATED                 	STATUS  	CHART             	APP VERSION	NAMESPACE
cautious-macaw 	1       	Fri Sep 27 15:42:10 2019	DEPLOYED	longhornfive-0.5.0	v0.5.0     	default
```
4. Upgraded release to 0.6.0, upgrade failed with error:
```
➜  ~ UPGRADE FAILED
Error: transport is closing
Error: UPGRADE FAILED: transport is closing
```
5. A release revision corresponding to 0.6.0 is created and is stuck in "PENDING_UPGRADE" as expected since longhorn 0.6.0 was broken.
```
➜  ~ helm history cautious-macaw
REVISION	UPDATED                 	STATUS         	CHART             	DESCRIPTION
1       	Fri Sep 27 15:42:10 2019	DEPLOYED       	longhornfive-0.5.0	Install complete
2       	Fri Sep 27 15:48:08 2019	PENDING_UPGRADE	longhornsix-0.6.0 	Preparing upgrade
3       	Fri Sep 27 15:49:22 2019	PENDING_UPGRADE	longhornfive-0.5.0	Preparing upgrade
```

Also the longhorn pods are stuck in ContainerCreating state
```
➜  ~ kubectl get pods
NAME                                         READY   STATUS              RESTARTS   AGE
longhorn-driver-deployer-7b4fd464d7-7kmkw    0/1     Init:0/1            0          10m
longhorn-driver-deployer-b77fdfbc6-4wsjs     0/1     Init:0/1            0          16m
longhorn-manager-nldt5                       0/1     ContainerCreating   0          10m
longhorn-post-upgrade-v6ftx                  0/1     ContainerCreating   0          10m
```
6. Rollback to version 0.5.0
```
➜  ~ helm rollback cautious-macaw 1
Rollback was a success.
```
Although this is shown as success, the longhorn-manager pods never rollback successfully, they remain stuck in ContainerCreating state and keep using 0.6.0 image instead of 0.5.0
```
longhorn-manager-nldt5                       0/1     ContainerCreating   0          12m
longhorn-post-upgrade-v6ftx                  0/1     ContainerCreating   0          12m
```
7. The configmap created for the latest revision contains 0.5.0 image, same as for Rancher, but never gets applied

So this looks like an upstream helm bug, found similar bugs open in helm repo:
https://github.com/helm/helm/issues/5939
https://github.com/helm/helm/issues/5915

**Comment by mrajashree** [comment] 2019-09-30 18:06
For cluster-monitoring issue that @dnoland1 shared, cluster-monitoring was turned on and off a few times. One of the times when it was turned off, the configmap corresponding to the app got stuck in "DELETING" state instead of getting deleted. Deleting this configmap for cluster-monitoring app worked. 
You can get the configmap by running this command and looking for a  configmap named cluster-monitoring.v(X) where X is the app version number
```
> kubectl get configmap -n cattle-prometheus
NAME                                DATA   AGE
cluster-monitoring.v1                 1      21m
```

**Comment by alena1108** [comment] 2019-09-30 20:21
Moving out of v2.3. In v2.3, we've resolved:

* Panic issue
* Issue where `Max history=1` was causing issues with rollbacks from unsuccessful upgrades

**Comment by deniseschannon** [comment] 2019-11-13 05:40
@mrajashree We've updated to Helm 2.14.3 as of v2.3, so can you check if this is still an issue?

**Comment by deniseschannon** [comment] 2020-02-06 04:50
@brendarearden With the upgrade to Helm 3 in 2.4, we should test if this use case is still an issue.

**Comment by brendarearden** [comment] 2020-02-28 16:44
Since we are not defaulting new deploys to Helm 3 in 2.4, we will be upgrading Helm 2 to the most recent available version to see if that resolves this issue. We should still check to see if this is resolved in 2.4 with apps that are deployed with Helm 3.

**Comment by deniseschannon** [comment] 2020-03-04 18:50
With the upgrade to Helm 2.16.3, we should test if this is still an issue with Helm 2: https://github.com/rancher/rancher/issues/25663

Since Helm3 removes Tiller, this bug can only be fixed in Helm 2.

**Comment by dramich** [comment] 2020-03-04 19:01
@deniseschannon The original issue was fixed long ago, there is another issue buried in here that @mrajashree reproduced and based off the open issues in helm that is not fixed yet. My recommendation is this issue should be closed and a new one opened based off [this](https://github.com/rancher/rancher/issues/21070#issuecomment-536128458).

**Comment by maggieliu** [comment] 2020-04-06 18:25
Followup ticket: https://github.com/rancher/rancher/issues/26510

**Closed by maggieliu** 2020-04-06 18:25 UTC
Labels: [zube]: To Test, area/catalog-service, kind/bug
