### ISSUE TITLE
Stacks are being stuck into `Activating` state when created with `rancher-compose`

### ISSUE THREAD

**Issue by cusspvz** [rancher/rancher#2209] opened 2015-10-01 17:58 UTC
Occurred since my upgrade from `v0.39.0` to `v0.40.0-rc1`

<img width="1267" alt="captura de ecra 2015-10-1 as 18 56 05" src="https://cloud.githubusercontent.com/assets/3604053/10229098/4a657568-686e-11e5-954d-f693c6e7d682.png">

**Comment by cusspvz** [comment] 2015-10-01 18:00
Update: It seems it is reproducible from UI.

As so, the creation of a new Stack on UI should be sufficient to reproduce.

**Comment by deniseschannon** [comment] 2015-10-01 18:14
Note: the RC releases still haven't gone through QA so there might be little bugs here and there. :)

But I was unable to reproduce with the UI. Can you click on the cow to make sure you have the right corresponding UI release? It should be v0.53.0.  Sometimes when I upgrade, my UI gets stuck on the old version and I just close my browser and relaunch Rancher.

**Comment by cusspvz** [comment] 2015-10-01 20:46
<img width="555" alt="captura de ecra 2015-10-1 as 21 46 42" src="https://cloud.githubusercontent.com/assets/3604053/10233363/ee127212-6885-11e5-83c6-16f1ff84aef7.png">

**Comment by deniseschannon** [comment] 2015-10-02 18:15
Can you share your `docker-compose.yml` as I haven't been able to reproduce?

**Comment by deniseschannon** [comment] 2015-10-06 18:17
@cusspvz Are you still seeing the activating issue? Could you try this command in the SQL DB to see what's going on? Note: Environment in the DB is the same as Stack in the UI. 

```
select id, name, state from environment where removed is null;
```

**Comment by deniseschannon** [comment] 2015-10-06 22:30
@cusspvz if you still have this setup, could you provide the rancher server logs?

**Comment by cusspvz** [comment] 2015-10-07 11:44
Not seeing this issue since `0.40.0`, but I haven't played enough for confirming.
@fernandoneto this also appeared on your local setup right? Is this issue still happening on your setup?

**Comment by cusspvz** [comment] 2015-10-07 11:47
> Can you share your `docker-compose.yml` as I haven't been able to reproduce?

Seems it wasn't `docker-compose.yml` fault since it was reproducible by creating a new *Stack* over UI.

> Are you still seeing the activating issue? Could you try this command in the SQL DB to see what's going on?

I've did a fresh install with `0.40.0`. Let's wait for @fernandoneto response.

**Comment by fernandoneto** [comment] 2015-10-08 14:28
Im using 
![captura de ecra de 2015-10-08 15 26 30](https://cloud.githubusercontent.com/assets/6515784/10369222/1559deaa-6dd1-11e5-9d1f-f3b462f1df95.png) and never occurred again.

**Comment by deniseschannon** [comment] 2015-10-08 21:13
@fernandoneto I'm going to close this. Please re-open if you see it again.

**Closed by deniseschannon** 2015-10-08 21:13 UTC

**Comment by fernandoneto** [comment] 2015-10-09 10:53
ok
