### ISSUE TITLE
rancher cli login fails if API Key is scoped to cluster

### ISSUE THREAD

**Issue by longwuyuan** [rancher/rancher#19348] opened 2019-04-03 05:19 UTC
**What kind of request is this (question/bug/enhancement/feature request):**
bug

**Steps to reproduce (least amount of steps as possible):**
- Create rancherserver installation with version 2.2.1
- Create a custom cluster
- Create a user
- Create api-key for user but scope it to the cluster and save the bearer-token
- Download rancher cli for linux
- Use the rancher cli to login as per docs https://rancher.com/docs/rancher/v2.x/en/cli/#cli-authentication

**Result:**

```
~ rancher login https://<rancherserverurl>/v3 --token  token-9mzf8:dfjjm9khvg45w8hrpnr8qdmflfshw4ktmcrgnqp58brs9nwkdjsuyrgs --context devopsdragon

FATA[0001] Bad response statusCode [401]. Status [401 Unauthorized]. Body: [message=clusterID does not match] from [https://<rancher-server-url>/v3]
```

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI):
version 2.2.1

- Installation option (single install/HA):
Single Node Install

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): Custom
- Machine type (cloud/VM/metal) and specifications (CPU/memory): VM 4 core 8GB RAM
- Kubernetes version (use `kubectl version`): 

```
kubectl version            
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.0", GitCommit:"641856db18352033a0d96dbc99153fa3b27298e5", GitTreeState:"clean", BuildDate:"2019-03-25T15:53:57Z", GoVersion:"go1.12.1", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.4", GitCommit:"c27b913fddd1a6c480c229191a087698aa92f0b1", GitTreeState:"clean", BuildDate:"2019-02-28T13:30:26Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}

```

- Docker version (use `docker version`):

```
% sudo docker version
Client:
 Version:           18.09.3
 API version:       1.39
 Go version:        go1.10.8
 Git commit:        774a1f4
 Built:             Thu Feb 28 06:40:58 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.3
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.8
  Git commit:       774a1f4
  Built:            Thu Feb 28 05:59:55 2019
  OS/Arch:          linux/amd64
  Experimental:     false
```

**Comment by superseb** [comment] 2019-04-03 08:46
Duplicate of https://github.com/rancher/rancher/issues/18639

**Closed by superseb** 2019-04-03 08:46 UTC
