### ISSUE TITLE
k8s node switch issue

### ISSUE THREAD

**Issue by jerrycen** [rancher/rancher#10297] opened 2017-11-09 02:01 UTC
Setup k8s environment with three nodes in Rancher

I want to test the following case:

Shutting down one or two of the three nodes.
I want to know if it the left node can still provide service.
But I got the following error.

**1.etcd Error Log：**
(Failed to allocate instance [container:1i4172]: Bad instance [container:1i4172] in state [error]: Allocation failed: Host must satisfy resource constraints: [instanceReservation: 1]. host must not have a container with label io.rancher.stack_service.name=kubernetes/etcd)  

**2.rancher Error Log：**
2017-11-09 01:49:02,453 ERROR [1a2d3721-4159-42c7-a08a-86269af56cb7:51607] [instance:3823->instanceHostMap:278] [instance.start->(InstanceStart)->instancehostmap.activate] [] [cutorService-25] [c.p.e.p.i.DefaultProcessInstanceImpl] Unknown exception io.cattle.platform.util.exception.ExecutionException: io.cattle.platform.async.utils.TimeoutException: Timeout
        at io.cattle.platform.process.common.handler.AgentBasedProcessLogic.handleEvent(AgentBasedProcessLogic.java:193)

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v1.6.11-rc7` Cattle: `v0.183.29` UI: `v1.6.28` k8s:'k8s:v1.8.2-rancher3'docker:'1.12.3'|
|Access|`Disabled`|
|Orchestration|`Kubernetes`|
|Route|`hosts.index`|

**Comment by loganhz** [comment] 2017-11-13 06:45
@jerrycen Please use English to describe your issue next time.
thanks a lot

Maybe the document can solve your problem. 
 https://rancher.com/docs/rancher/v1.6/en/kubernetes/disaster-recovery/

**Comment by superseb** [comment] 2017-11-23 23:13
The etcd service is deployed with anti affinity rule to itself, so each etcd will land on a different node. If you spin up 3 nodes, it will try to deploy 3 etcd instances. With 3 etcd instances, you are allowed one failure. By more than one failure, you'll have to run disaster recovery. The orchestration will try to start the other instances of etdc but cant schedule them i.e. `host must not have a container with label io.rancher.stack_service.name=kubernetes/etcd)`

The other messages is the agent being shutdown because the host is shutdown.

Let me know if you have any other question, closing as not a bug.

**Closed by superseb** 2017-11-23 23:13 UTC
Labels: kind/question
