### ISSUE TITLE
intermittent error seen when provisioning clusters - "Error from server (Forbidden)"

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#13129] opened 2018-04-26 20:38 UTC
Steps to reproduce the problem:

Provisioning custom cluster with 2 control nodes/3 etcd and 3 worker nodes 

When provisioning is still in progress , we see the following intermittent  error message shown:

 Waiting for API to be available; exit status 1, Error from server (Forbidden): error when retrieving current configuration of: &{0xc420720e40 0xc4205ff340 cattle-system management-state/tmp/yaml-405267538 0xc4216686b0 0xc4216686b0 false} from server for: "management-state/tmp/yaml-405267538": namespaces "cattle-system" is forbidden: User "user-w9nc8" cannot get namespaces in the namespace "cattle-system" Error from server (Forbidden): error when retrieving current configuration of: &{0xc4201bcd80 0xc420595500 cattle-system cattle management-state/tmp/yaml-405267538 0xc42175a230 0xc42175a230 false} from server for: "management-state/tmp/yaml-405267538": serviceaccounts "cattle" is forbidden: User "user-w9nc8" cannot get serviceaccounts in the namespace "cattle-system" Error from server (Forbidden): error when retrieving current configuration of: &{0xc420720f00 0xc4205fcd90 cattle management-state/tmp/yaml-405267538 0xc421668818 0xc421668818 false} from server for: "management-state/tmp/yaml-405267538": clusterrolebindings.rbac.authorization.k8s.io "cattle" is forbidden: User "user-w9nc8" cannot get clusterrolebindings.rbac.authorization.k8s.io at the cluster scope Error from server (Forbidden): error when retrieving current configuration of: &{0xc4201bce40 0xc4205f0a10 cattle-system cattle-credentials-d8618c7 management-state/tmp/yaml-405267538 0xc42175a2a0 0xc42175a2a0 false} from server for: "management-state/tmp/yaml-405267538": secrets "cattle-credentials-d8618c7" is forbidden: User "user-w9nc8" cannot get secrets in the namespace "cattle-system" Error from server (Forbidden): error when retrieving current configuration of: &{0xc420720fc0 0xc4202c04d0 cattle-system cattle-cluster-agent management-state/tmp/yaml-405267538 0xc4216688a8 0xc4216688a8 false} from server for: "management-state/tmp/yaml-405267538": deployments.extensions "cattle-cluster-agent" is forbidden: User "user-w9nc8" cannot get deployments.extensions in the namespace "cattle-system" Error from server (Forbidden): error when retrieving current configuration of: &{0xc4201bcf00 0xc42004ecb0 cattle-system cattle-node-agent management-state/tmp/yaml-405267538 0xc42175a330 0xc42175a330 false} from server for: "management-state/tmp/yaml-405267538": daemonsets.extensions "cattle-node-agent" is forbidden: User "user-w9nc8" cannot get daemonsets.extensions in the namespace "cattle-system"

This full message shows up as cluster status in UI .

Is there way to prevent this intermediate error from happening / reporting in the UI ?

**Comment by sangeethah** [comment] 2018-04-27 21:51
Tested with latest build from master ```91a916874851        rancher/rancher:master ```
I saw this intermediate error message show up when provisoning a 1 node cluster.

**Comment by alena1108** [comment] 2018-09-11 20:35
Moving the issue out as @carolynhu couldn't reproduce it, and the error is intermittent and recoverable from. Will debug on the issue more in the next release.

**Comment by bradjones1** [comment] 2018-10-06 21:02
For what it's worth, running `rancher/rancher:v2.1.0` with https://github.com/rancher/rancher/pull/15688 applied makes the cluster stick in "Waiting for API to be available", but this error is not shown. There are no applicable log entries that I could see.

**Comment by bradjones1** [comment] 2018-10-07 20:07
Another note: This seems to be a possible regression in 2.1.x, 2.0.8 appears to work just fine?

**Comment by loganhz** [comment] 2018-10-21 05:35
@bradjones1

Not sure if your issue is related to https://github.com/rancher/rancher/issues/16012

> exit status 1, Error from server (Forbidden): error when retrieving current configuration of: &{0xc420720e40 0xc4205ff340 cattle-system management-state/tmp/yaml-405267538 0xc4216686b0 0xc4216686b0 false} from server for: "management-state/tmp/yaml-405267538": namespaces "cattle-system" is forbidden: User "user-w9nc8" cannot get namespaces in the namespace "cattle-system" 

Did you see the similar logs in your rancher server like above?
Can you create a separated issue if not, please?

**Comment by matthax** [comment] 2018-11-05 20:38
Seeing the same problem after migrating to 2.1.x - definitely looks like a regression.

We are seeing the same forbidden error for the user when adding new nodes to a cluster

**Comment by proligde** [comment] 2019-02-08 21:47
Same here - I might add that this problem occurs for us only on virtualBox nodes that are cloned from each other. The drive image we clone has a clean docker installed already (but is not configured as a rancher node, yet).

**Comment by cjellick** [comment] 2019-02-09 01:25
If it is only happening for clones, maybe it has to do with duplicate MAC addresses causing two nodes to get the same IP address in your network?

Just a wild guess.

Otherwise a more detailed description of your setup (like the template found when you create a new issue) and a snippet of the server logs might be helpful.

**Comment by proligde** [comment] 2019-02-09 10:23
@cjellick Thanks for the hint but I ruled that out before, assigning the clones differnt MAC addresses. After I couldn't get that cluster to work I destroyed it completely, wiped /var/lib/rancher and all docker containers from all nodes and created a new cluster. This time it worked. The setup was the same: One ControlPlane node, two WorkerNodes. The only thing I changed: I didn't add the worker nodes simultaneously but one after the other. I can't tell if it's coincidence or in fact a race condition but now everything works as expected.

**Comment by cjellick** [comment] 2019-02-09 14:24
Were they cloned from a machine that was already a rancher node and thus had a /var/lib/rancher dir when closed? That dir cannot be cloned. Has a little bit of state/identifying data in it

**Comment by mohapma** [comment] 2019-03-28 06:26
During Helm install i am getting below error. Can anyone help me out to solve this issue?
$ helm install rancher-stable/rancher \--kubeconfig ~/.kube/config \--name rancher \--namespace cattle-system \--set hostname=rancher2.test.com \--set ingress.tls.source=secret

Error: release rancher failed: namespaces "cattle-system" is forbidden: User "system:serviceaccount:kube-system:default" cannot get resource "namespaces" in API group "" in the namespace "cattle-system"

**Comment by deniseschannon** [comment] 2019-04-08 23:14
@mohapma yours is different as you are trying to launch rancher server versus the original one is for when you are trying to add clusters into rancher server. 

Closing as any new issues should be filed separately.

**Closed by deniseschannon** 2019-04-08 23:14 UTC
Labels: kind/bug, priority/1, status/autoclosed, team/ca
