### ISSUE TITLE
User created network policies are deleted when disabling Network project isolation on the cluster

### ISSUE THREAD

**Issue by sowmyav27** [rancher/rancher#30135] opened 2020-11-18 18:23 UTC
**What kind of request is this (question/bug/enhancement/feature request):** bug

**Steps to reproduce (least amount of steps as possible):**

- Create user network policies following this example [here](https://kubernetes.io/docs/concepts/services-networking/network-policies/#networkpolicy-resource) on a cluster
- Enable NPI on the cluster
- hn-nodes and np-default seen additionally
- Disable NPI on the cluster.
- All the network policies are deleted.
```
> kubectl get networkpolicies -A
No resources found
```

**Expected Result:**
User created Network policies should not get deleted.

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): 2.4.7 and 2.5-head - commit id: `71da1569`
- Installation option (single install/HA): single

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): DO RKE
- Kubernetes version (use `kubectl version`):

```
1.18/1.19 (any)
```

**Comment by kinarashah** [comment] 2020-11-18 19:30
Note: This isn't a regression, behavior is present in earlier versions as well. Ideally we shouldn't be removing user's network policies @leodotcloud what do you think?

**Comment by leodotcloud** [comment] 2020-11-18 20:35
Agree with @kinarashah. Unfortunately, this has been the behavior since the beginning. The function [here](https://github.com/rancher/rancher/blob/0db277711f3f7a5fbc3801343448707e8f952d69/pkg/controllers/managementuser/networkpolicy/clusterHandler.go#L132) needs to be fixed by not deleting all the network policies, only the ones created by Rancher. (np-*, hp-*, etc)

**Comment by kinarashah** [comment] 2020-11-20 20:48
Thanks for confirming @leodotcloud! 

@maggieliu this is not a regression and this has been since the beginning of project network isolation feature. Going to move this out of 2.5.3. cc @deniseschannon

**Comment by kravciak** [comment] 2021-04-01 10:26
I reproduced this on master-head (440b4e5), I will re-test after the fix is merged.

**Comment by aaronRancher** [comment] 2021-04-05 23:41
This issue is reproduced on Rancher `v2.5.7`.

Steps:
Create user network policies following this example [here](https://kubernetes.io/docs/concepts/services-networking/network-policies/#networkpolicy-resource) on a cluster
```
Aarons-MBP:Test yaml aaronyee$ kc apply -f networkpolicy.yaml
networkpolicy.networking.k8s.io/test-network-policy created
Aarons-MBP:Test yaml aaronyee$ kubectl get networkpolicies -A
NAMESPACE      NAME                  POD-SELECTOR   AGE
default        test-network-policy   role=db        9s
fleet-system   default-allow-all     <none>         21m
```
Enable Project Network Isolation on the cluster
hn-nodes and np-default seen additionally
```
Aarons-MBP:Test yaml aaronyee$ kubectl get networkpolicies -A
NAMESPACE      NAME                  POD-SELECTOR   AGE
default        hn-nodes              <none>         3s
default        np-default            <none>         3s
default        test-network-policy   role=db        3m5s
fleet-system   default-allow-all     <none>         24m
```
Disable Project Network Isolation on the cluster.
The user network policies are deleted.
```
Aarons-MBP:Test yaml aaronyee$ kubectl get networkpolicies -A
NAMESPACE      NAME                POD-SELECTOR   AGE
fleet-system   default-allow-all   <none>         10s
```

**Comment by aaronRancher** [comment] 2021-04-06 00:32
The bug fix is verified with Rancher server `rancher\rancher:v2.5-head` `version 93d921f`
When Project Network Isolation is disabled, the user created network policies are no longer deleted.

Reopening for a fix in master-head.

**Comment by ryansann** [comment] 2021-04-06 16:40
Thanks @aaronRancher, I will forward port this to master

**Comment by ryansann** [comment] 2021-04-06 21:54
@aaronRancher I merged the forward port to master, moving this back To Test

**Comment by aaronRancher** [comment] 2021-04-06 23:53
The bug fix is verified on Rancher `master-head` `version 13eec94`.
When Project Network Isolation is disabled, the user created network policies are no longer deleted.

**Comment by ryansann** [comment] 2021-04-19 20:01
I've done some additional testing here around node port and host port services, which get their own network policies. If you create host port and node port workloads and then disable PNI, you will notice that these policies stick around. This is due to them not having the label: `cattle.io/creator: norman`, which is what we use to delete Rancher created policies. I've opened a PR to add this label to these policies, so they will be picked up for deletion when disabling PNI.

To test this, create node port and host port workloads in the default project with PNI enabled. Then disable PNI and ensure there are no Rancher created policies that have not been deleted.

**Comment by aaronRancher** [comment] 2021-04-21 18:44
I am unable to reproduce the above comment on Rancher `v2.5.7` with the following steps:
Create a downstream cluster.
Enable PNI.
Create node port and host port workloads in the default project.
Verify network policies are created:
```
> kubectl get networkpolicies -A
NAMESPACE      NAME                               POD-SELECTOR                                                                 AGE
default        hn-nodes                           <none>                                                                       8m9s
default        hp-testworkload-6587d86644-8ljg6   field.cattle.io/podName=testworkload-6587d86644-8ljg6                        106s
default        np-default                         <none>                                                                       8m9s
default        np-test-workload2-nodeport         workload.user.cattle.io/workloadselector=deployment-default-test-workload2   45s
fleet-system   default-allow-all                  <none>                                                                       11m
```
Disable PNI.
Verify network policies are deleted:
```
> kubectl get networkpolicies -A
NAMESPACE      NAME                POD-SELECTOR   AGE
fleet-system   default-allow-all   <none>         2m44s
```

The network policies did not have the `cattle.io/creator: norman` label.
```
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
creationTimestamp: "2021-04-21T18:15:15Z"
  generation: 1
  managedFields:
  name: np-test-workload2-nodeport
  namespace: default
  ownerReferences:
  - apiVersion: v1
    kind: Service
    name: test-workload2-nodeport
    uid: c162a6f2-4f93-4988-a214-c056aaa4a9af
  resourceVersion: "3796"
  uid: 6733ab05-05aa-4fa8-8c86-2fe0ba22867b
spec:
  ingress:
  - ports:
    - port: 8082
      protocol: TCP
  podSelector:
    matchLabels:
      workload.user.cattle.io/workloadselector: deployment-default-test-workload2
  policyTypes:
  - Ingress
```

**Comment by aaronRancher** [comment] 2021-04-21 20:59
The above comment is reproduced on `v2.5.8-rc4`:
Before PNI is disabled:
```
> kubectl get networkpolicies -A
NAMESPACE         NAME                        POD-SELECTOR                                                        AGE
cattle-system     np-default-allow-all        <none>                                                              2m48s
default           hn-nodes                    <none>                                                              2m48s
default           hp-test2-764c84d6dd-5dc7v   field.cattle.io/podName=test2-764c84d6dd-5dc7v                      6s
default           np-default                  <none>                                                              2m48s
default           np-test1-nodeport           workload.user.cattle.io/workloadselector=deployment-default-test1   19s
fleet-system      default-allow-all           <none>                                                              12m
ingress-nginx     np-default-allow-all        <none>                                                              2m48s
kube-node-lease   np-default-allow-all        <none>                                                              2m48s
kube-public       np-default-allow-all        <none>                                                              2m48s
kube-system       np-default-allow-all        <none>                                                              2m48s
security-scan     np-default-allow-all        <none>
```
After PNI is disabled, the network policies are not deleted:
```
> kubectl get networkpolicies -A
NAMESPACE      NAME                        POD-SELECTOR                                                        AGE
default        hp-test2-764c84d6dd-5dc7v   field.cattle.io/podName=test2-764c84d6dd-5dc7v                      99s
default        np-test1-nodeport           workload.user.cattle.io/workloadselector=deployment-default-test1   112s
fleet-system   default-allow-all           <none>
```

**Comment by aaronRancher** [comment] 2021-04-21 21:13
The fix (https://github.com/rancher/rancher/pull/32222) is validated on Rancher `v2.5-head` `version 71fd809`

 Before PNI is disabled:
```
> kubectl get networkpolicies -A
NAMESPACE         NAME                        POD-SELECTOR                                                        AGE
cattle-system     np-default-allow-all        <none>                                                              144m
default           hn-nodes                    <none>                                                              144m
default           hp-test2-847c78b946-8vll6   field.cattle.io/podName=test2-847c78b946-8vll6                      134m
default           np-default                  <none>                                                              144m
default           np-test1-nodeport           workload.user.cattle.io/workloadselector=deployment-default-test1   135m
fleet-system      default-allow-all           <none>                                                              146m
ingress-nginx     np-default-allow-all        <none>                                                              144m
kube-node-lease   np-default-allow-all        <none>                                                              144m
kube-public       np-default-allow-all        <none>                                                              144m
kube-system       np-default-allow-all        <none>                                                              144m
security-scan     np-default-allow-all        <none>                                                              144m
```
After PNI is disabled:
```
> kubectl get networkpolicies -A
NAMESPACE      NAME                POD-SELECTOR   AGE
fleet-system   default-allow-all   <none>         148m
```
The node port and host port network policies have the `cattle.io/creator: norman` label:
```
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  creationTimestamp: "2021-04-21T21:09:29Z"
  generation: 1
  labels:
    cattle.io/creator: norman
``` 

Waiting for the fix to be merged into master before closing: https://github.com/rancher/rancher/pull/32227

**Comment by aaronRancher** [comment] 2021-04-21 22:33
Will track fix on master-head here: https://github.com/rancher/rancher/issues/32278

**Closed by aaronRancher** 2021-04-21 22:33 UTC
Labels: [zube]: To Test, kind/bug, priority/0, release-note
