### ISSUE TITLE
Bug: coredns-autoscaler needs readiness and liveness check

### ISSUE THREAD

**Issue by patrick0057** [rancher/rancher#24939] opened 2020-01-13 20:55 UTC
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
coredns autoscaler does not have a readiness and liveness check

**Result:**
If a node goes offline where coredns-autoscaler is running, it will not be rescheduled properly.

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI):
- Installation option (single install/HA): HA

gz#7893
SURE-1649

**Comment by Jono-SUSE-Rancher** [comment] 2021-03-30 17:19
Whoever grabs this, we don't expect the liveness check to actually correct the expected behavior to have the pod rescheduled after the node goes down. In 2.5.4 we added in the ability to configure the tolerations on add-ons which may solve this issue but needs to be investigated.

**Comment by izaac** [comment] 2021-03-30 21:59
Rancher version: `v2.5.7`

Scenarios:

Cluster type `Imported RKE`
Clusters had at least three workers.

- Cluster 1 in `1.18` with coreDNS add ons with the tolerations
- Cluster 2 in `1.19` with coreDNS add ons with the tolerations
- Cluster 3 in `1.18` with default values for coreDNS

Add-ons configuration in `cluster.yml`

```yaml
monitoring:
  tolerations:
  - key: "node.kubernetes.io/unreachable"
    operator: "Exists"
    effect: "NoExecute"
    tolerationseconds: 15
ingress:
  provider: nginx
  tolerations:
  - key: "node.kubernetes.io/unreachable"
    operator: "Exists"
    effect: "NoExecute"
    tolerationseconds: 15
network:
  plugin: calico
  tolerations:
  - key: "node.kubernetes.io/unreachable"
    operator: "Exists"
    effect: "NoExecute"
    tolerationseconds: 15
dns:
  provider: coredns
  tolerations:
  - key: "node.kubernetes.io/unreachable"
    operator: "Exists"
    effect: "NoExecute"
    tolerationseconds: 15
  - key: "node.kubernetes.io/not-ready"
    operator: "Exists"
    effect: "NoExecute"
    tolerationseconds: 300
```

Cluster 1 - `1.18` with coreDNS add ons with the tolerations
Turned off the worker node which had one of the 2 coredns pods. After the node was unreachable by kubernetes the pod went to `Unknown` status. A new pod was scheduled in other available worker node and come up `Active`

Cluster 2 - `1.19` with coreDNS add ons with the tolerations
Turned off the worker node which had one of the 2 coredns pods. After the node was unreachable by kubernetes the pod went to `Unknown` status. Config scale in the deployment 2 and Ready scale was 1. No pod was re-scheduled.

Cluster 3 - `1.18` with default values for coreDNS
Turned off the worker node which had one of the 2 coredns pods. After the node was unreachable by kubernetes the pod went to `Unknown` status. Config scale in the deployment 2 and Ready scale was 1. No pod was re-scheduled.

**Comment by snasovich** [comment] 2021-12-21 18:58
If we're using https://github.com/kubernetes-sigs/cluster-proportional-autoscaler/blob/master/charts/cluster-proportional-autoscaler/templates/deployment.yaml for coredns-autoscaler, we could try adding the same liveness/readiness probes as in the linked template.

**Comment by annablender** [comment] 2022-01-20 22:07
Liveness and readiness probes added to the RKE1 coredns-autoscaler deployment https://github.com/rancher/kontainer-driver-metadata/pull/791

**Comment by annablender** [comment] 2022-01-25 19:12
## Testing template

#### Root cause

No root cause. CoreDNS autoscaler health probes requested by customer. This will assist in info/debugging if an autoscaler pod is unable to be rescheduled.
 
#### What was fixed, or what changes have occurred

- New KDM CoreDNS template added with liveness and readiness probes https://github.com/rancher/kontainer-driver-metadata/blob/dev-v2.6/rke/templates/coredns_v1.8.3-rancher2.go
- Updated `templates.go` https://github.com/rancher/kontainer-driver-metadata/blob/08d37bec45020d4b87bf0c70d1027b46319b5e46/rke/templates/templates.go#L140

#### Areas or cases that should be tested

1. Create an RKE1 downstream cluster with the latest KDM (the coredns and coredns autoscaler deployments will be added automatically)
2. Check the coredns autoscaler deployment config for liveness and readiness probes

<img width="1774" alt="Screen Shot 2022-01-18 at 5 39 32 PM" src="https://user-images.githubusercontent.com/12955547/151043356-57264acc-763e-49c1-ae95-badd5cf7a911.png">
 
#### What areas could experience regressions ?

None.
 
#### Are the repro steps accurate/minimal ?

Yes.

**Comment by snasovich** [comment] 2022-02-02 20:21
Reverted from KDM for now, will get into next KDM release likely coinciding with v2.6.4.

**Comment by annablender** [comment] 2022-02-02 21:31
PR reopened for 2.6.4 
* https://github.com/rancher/kontainer-driver-metadata/pull/820. 

I also added a backport issue and PR for Rancher 2.5 
* https://github.com/rancher/kontainer-driver-metadata/pull/820
* https://github.com/rancher/kontainer-driver-metadata/pull/821

Both PRs will wait to merge until the upcoming KDM release is done.

**Comment by annablender** [comment] 2022-02-15 21:24
## Testing template

#### Root cause

N/A. CoreDNS autoscaler health checks requested for more debug info if a coredns-autoscaler pod is not able to be rescheduled onto a failed node.
 
#### What was fixed, or what changes have occurred

- Added new CoreDNS template with liveness and readiness probes for the autoscaler https://github.com/rancher/kontainer-driver-metadata/blob/dev-v2.6/rke/templates/coredns_v1.8.3-rancher2.go
- Updated `templates.go` with new template https://github.com/rancher/kontainer-driver-metadata/blob/0d1175e5c569318589905b5255e41666f9a5b2a8/rke/templates/templates.go#L141

#### Areas or cases that should be tested

Test steps
1. Create an RKE1 downstream cluster on Rancher 2.6-head. The coredns autoscaler will deploy automatically
2. View the coredns autoscaler pod config
3. View Health Checks. You should see the health check fields configured, it will look like this

![image](https://user-images.githubusercontent.com/12955547/154151544-2165a4eb-518d-46ce-ad4f-3c9fb3a2d6d1.png)
 
#### What areas could experience regressions ?

If template gets overwritten or removed, then health checks will not show up as configured in the coredns-autoscaler pod for RKE1 downstream clusters.
 
#### Are the repro steps accurate/minimal ?

Yes.

**Comment by rishabhmsra** [comment] 2022-02-16 11:21
**Re-opening this issue**

**Rancher Server:**
- v2.6-head (3f30288)
- docker install

**Validation steps followed:**
- Created a single node downstream AWS node driver cluster using k8s `v1.21.9-rancher1-1`
- Checked the coredns-autoscaler Health Check config
- `Readiness Check` and `Liveness Check` fields are not configured:

![coredns](https://user-images.githubusercontent.com/36376154/154247190-74628b76-230f-47da-afce-265e2bf8894c.png)

**Comment by annablender** [comment] 2022-02-16 22:37
I also saw this today while fixing a CI issue. @jiaqiluo and I figured out that coredns autoscaler has port requirements for the health checks. Upstream https://github.com/coredns/helm/blob/f4fcc7649235afef5e360e7547d76b9e6cbca6d8/charts/coredns/templates/deployment-autoscaler.yaml#L71-L75 has health checks at `/healthz:8080`

Put in a PR to fix https://github.com/rancher/kontainer-driver-metadata/pull/831.

**Comment by rishabhmsra** [comment] 2022-02-23 09:39
Tried validating this on rancher v2.6-head (https://github.com/rancher/rancher/commit/e55a04c1915c62bbc23ee1e5db70208ce2a11679) but could not proceed because of the issue https://github.com/rancher/rancher/issues/36588.

Rancher Server:
- v2.6-head (https://github.com/rancher/rancher/commit/e55a04c1915c62bbc23ee1e5db70208ce2a11679)
- docker install

Validation steps followed :
- Created a single node AWS node driver cluster using k8s 1.22.6-rancher1-2
- Rancher server got crashed and became inaccessible https://github.com/rancher/rancher/issues/36588.

**Comment by rishabhmsra** [comment] 2022-02-25 13:26
Re-opening this issue
Validated this on 2.6-head(6352861), but due to a UI issue cannot validate the Health Check fields. 
Logged the ticket https://github.com/rancher/dashboard/issues/5215.

**Comment by annablender** [comment] 2022-02-25 17:21
@rishabhmsra If I understand this correctly, you validated that an RKE1 downstream cluster deploys successfully on 2.6-head(https://github.com/rancher/rancher/commit/635286172d41b24c074236060651af34c831b133) and the coredns-autoscaler-deployment has the correct health checks, but those checks are not showing up correctly in the UI?

**Comment by rishabhmsra** [comment] 2022-03-01 12:55
@annablender, yes I was able to provision the RKE1 downstream cluster on v2.6-head. Also I saw some fields were configured for `coredns-autoscaler-deployment` healthcheck, but I could not validate it completely because the values were not showing up properly. Also the `Liveness Check` was not visible at all on the UI. Once the UI issue is fixed, I'll re-validate this.

**Comment by snasovich** [comment] 2022-03-01 19:13
Waiting on UI fix https://github.com/rancher/dashboard/issues/5215 which is currently in review.

**Comment by annablender** [comment] 2022-03-01 20:43
@rishabhmsra Sounds great. I'll keep an eye on this.

**Comment by snasovich** [comment] 2022-03-02 22:21
The linked https://github.com/rancher/dashboard/issues/5215 is now in test, so moving this one to test too.

**Comment by rishabhmsra** [comment] 2022-03-03 12:46
**Rancher Server:**
- v2.6-head (39befda)
- docker install

**Validation steps followed as mentioned [here](https://github.com/rancher/rancher/issues/24939#issuecomment-1040807865) :**
- Provisioned a single node AWS node driver k8s `v1.22.6-rancher1-2` cluster.
- Checked the coredns-autoscaler heatlh check fields and `Readiness` and `Liveness Check` are configured correctly.

![coredns-ss1](https://user-images.githubusercontent.com/36376154/156566506-4b2b3d24-5086-4e2b-a576-01e1ac6c5aaa.png)

**Result:**
- The Health Check fields values are configured as expected, hence closing the issue.

**Closed** 2022-03-09 17:13 UTC
Labels: kind/bug, area/dns, internal, [zube]: Done, [zube]: To Test, status/awaiting-ui, feature/provisioned-rke1, team/area2, feature/kdm
