### ISSUE TITLE
[feature] show free disk space or disk usage in % in a host view

### ISSUE THREAD

**Issue by ndelitski** [rancher/rancher#2616] opened 2015-11-09 07:54 UTC
I have constantly to check out free disk space, because of devicemapper leak problem, so would be nice to see it on a single page. When something goes wrong on the host the most common problem is 100% disk usage...
Actually you can show only indicator when disk usage is more 80%.

**Comment by sshipway** [comment] 2015-11-11 04:00
+1 for this.  It would be very helpful to have a small bar/pie in the Host screen to show the space used in the /var/lib/docker filesystem.  However this might need to be configurable if people are using different filesystem locations, or multiple filesystems (such as to hold persistent data)

**Comment by gordontyler** [comment] 2015-11-16 18:11
Related: #2476

**Comment by cusspvz** [comment] 2016-01-14 23:02
+1

**Comment by deniseschannon** [comment] 2016-02-04 21:48
Duplicate of #1542

**Closed by deniseschannon** 2016-02-04 21:48 UTC
Labels: area/stats, kind/feature, release/future
