### ISSUE TITLE
Removing in-tree vSphere vCenter server entries does not propagate

### ISSUE THREAD

**Issue by DH-Rancher** [rancher/rancher#27306] opened 2020-05-28 12:33 UTC
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
Initial config:

```yaml
rancher_kubernetes_engine_config:
  cloud_provider:
    name: vsphere
    vsphereCloudProvider:
      disk: {}
      global:
        insecure-flag: true
        soap-roundtrip-count: 0
      network: {}
      virtual_center:
        172.16.10.22:
          datacenters: /Homelab
          soap-roundtrip-count: 0
          user: administrator@vsphere.local
      workspace:
        datacenter: /Homelab
        folder: /Homelab/vm/K8S
        server: 172.16.10.22
```

Kube-apiserver container info:

```bash
root@vsp-intree1:~# docker inspect kube-apiserver | grep cloud
            "--cloud-config=/etc/kubernetes/cloud-config",
            "--cloud-provider=vsphere",
                "--cloud-config=/etc/kubernetes/cloud-config",
                "--cloud-provider=vsphere",
root@vsp-intree1:~# 
```

Contents of /etc/kubernetes/cloud-config

```bash
root@vsp-intree1:~# cat /etc/kubernetes/cloud-config

[Global]
user = ""
password = ""
insecure-flag = "true"
soap-roundtrip-count = "0"


[VirtualCenter "172.16.10.22"]
        user = "administrator@vsphere.local"
        password = "Removed"
        datacenters = "/Homelab"
        soap-roundtrip-count = "0"

[Workspace]
        server = "172.16.10.22"
        datacenter = "/Homelab"
        folder = "/Homelab/vm/K8S"
        default-datastore = ""
        resourcepool-path = ""

[Disk]

[Network]
```

Amend config to include second vcenter, point the workspace to it

```yaml
rancher_kubernetes_engine_config:
  cloud_provider:
    name: vsphere
    vsphereCloudProvider:
      disk: {}
      global:
        insecure-flag: true
        soap-roundtrip-count: 0
      network: {}
      virtual_center:
        172.16.10.22:
          datacenters: /Homelab
          soap-roundtrip-count: 0
          user: administrator@vsphere.local
        172.16.10.23:
          datacenters: /Homelab2
          soap-roundtrip-count: 0
          user: administrator@vsphere.local
      workspace:
        datacenter: /Homelab
        folder: /Homelab/vm/K8S
        server: 172.16.10.23
```

Kube-apiserver restarts

```bash
41 seconds ago      Up 40 seconds                           kube-apiserver
```

 /etc/kubernetes/cloud-config gets updated:

```bash
[Global]
user = ""
password = ""
insecure-flag = "true"
soap-roundtrip-count = "0"

[VirtualCenter "172.16.10.22"]
        user = "administrator@vsphere.local"
        password = "Removed"
        datacenters = "/Homelab"
        soap-roundtrip-count = "0"
[VirtualCenter "172.16.10.23"]
        user = "administrator@vsphere.local"
        password = "Removed"
        datacenters = "/Homelab2"
        soap-roundtrip-count = "0"

[Workspace]
        server = "172.16.10.23"
        datacenter = "/Homelab"
        folder = "/Homelab/vm/K8S"
        default-datastore = ""
        resourcepool-path = ""

[Disk]

[Network]
```

Remove one of the vCenter entries (172.16.10.22 in this example)

```yaml
virtual_center:
        172.16.10.23:
          datacenters: /Homelab2
          soap-roundtrip-count: 0
          user: administrator@vsphere.local
      workspace:
        datacenter: /Homelab
        folder: /Homelab/vm/K8S
        server: 172.16.10.23
```

After clicking save, Rancher triggers a cluster upate, but kube-apiserver is not restarted. Additionally, going back to editing the cluster yaml reveals the segment previously removed has been re-inserted.

```yaml
virtual_center:
        172.16.10.22:
          datacenters: /Homelab
          soap-roundtrip-count: 0
          user: administrator@vsphere.local
        172.16.10.23:
          datacenters: /Homelab2
          soap-roundtrip-count: 0
          user: administrator@vsphere.local
      workspace:
        datacenter: /Homelab
        folder: /Homelab/vm/K8S
        server: 172.16.10.23
```

 /etc/kubernetes/cloud-config still reflects the previous configuration:

```bash
[Global]
user = ""
password = ""
insecure-flag = "true"
soap-roundtrip-count = "0"

[VirtualCenter "172.16.10.22"]
        user = "administrator@vsphere.local"
        password = "Removed"
        datacenters = "/Homelab"
        soap-roundtrip-count = "0"
[VirtualCenter "172.16.10.23"]
        user = "administrator@vsphere.local"
        password = "Removed"
        datacenters = "/Homelab2"
        soap-roundtrip-count = "0"

[Workspace]
        server = "172.16.10.23"
        datacenter = "/Homelab"
        folder = "/Homelab/vm/K8S"
        default-datastore = ""
        resourcepool-path = ""

[Disk]

[Network]
```

**Result:**

Adding additional enties works. However removing entries does not.

**Other details that may be helpful:**

**Environment information**

| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v2.4.3` UI: `v2.4.22` |
|Route|`undefined`|

Rancher HA install on RKE

**Cluster information**
- Cluster type: Infrastructure provider leveraging vSphere node driver
- Machine type: VM 2vCPU/4GB RAM
- Kubernetes version (use `kubectl version`):

```
Infrastructure provider : vSphere
Machine Type : VM 2vCPU/4GB RAM
Kubernetes version: v1.17.5
```

- Docker version (use `docker version`):

```
19.03.9
```

gz#10316

**Comment by redi-dangeloj** [comment] 2020-06-12 15:43
Hitting what looks like the same issue with Rancher 2.4.3.    

Our cluster's rancher_rke_template information has an erroneous IP address for vcenter and causes dynamic storage provisioning to be blocked.    

Besides uses Edit YAML for the cluster config and trying to delete the entries (with adding Password: back from presumably be redacted), we have also tried creating a RKE template, modifying a new version and verifying the yaml only has a single and correct entry, and then update the child cluster having the issue to the new version along with even deploying new nodes and always end up with having the extra erroneous entries for vcenters that don't exist.    With the vsphere provider trying to contact an unreachable vcenter, we cannot provision any Persistent Volumes and are blocked.

**Comment by superseb** [comment] 2020-11-03 19:27
This seems to be happening around https://github.com/rancher/rancher/blob/master/pkg/api/norman/store/cluster/cluster_store.go#L945

**Comment by sadiapoddar** [comment] 2020-12-18 23:48
Reproduced this issue on v2.4.3 
Steps to repro
1. created a cluster on vSphere cloud provider by choosing the "custom" provider option and added the clouder provider information in YMAL file
2. Once the cluster is up checked all the config info. 
`
root@sadia-control1:~# docker inspect kube-apiserver |grep cloud
            "--cloud-config=/etc/kubernetes/cloud-config",
            "--cloud-provider=vsphere",
                "--cloud-config=/etc/kubernetes/cloud-config",
                "--cloud-provider=vsphere",
root@sadia-control1:~# cat /etc/kubernetes/cloud-config

[Global]
user = ""
password = ""
insecure-flag = "true"
soap-roundtrip-count = "0"


[VirtualCenter "xxx"]
        user = ""xxxxx"r"
        password = ""xxxxx""
        port = "443"
        datacenters = ""xxxxx""
        soap-roundtrip-count = "0"

[Workspace]
        server = "xxx"
        datacenter = "xxxxx"
        folder = "xxxxx"
        default-datastore ="xxxxx"
        resourcepool-path = ""xxxxx""

[Disk]

[Network]

 `

3. Edited the cluster configuration and added a second vCenter information in the cluster config and saved it
<img width="843" alt="Screen Shot 2020-12-18 at 3 34 05 PM" src="https://user-images.githubusercontent.com/72409237/102672878-f17dc600-4146-11eb-9f71-61acb5f28a66.png">

4. Since the second vCenter which was added doesn't exist, the cluster update showing an error during updating the cluster with the newly added vCenter.

<img width="1254" alt="Screen Shot 2020-12-18 at 3 11 46 PM" src="https://user-images.githubusercontent.com/72409237/102672994-4a4d5e80-4147-11eb-8657-37221648bddd.png">

5. Removed the second vCenter clause from the cluster config YMAL file and saved
Still seeing the same error on the UI. Checked the cluster config file and the second vCenter info added in YMAL file not removed. Tried a few times to remove that entry and it's not removable. 

With this 2nd vCenter the Rancher UI periodic cluster update tries to connect to the second vCenter and shows the error
<img width="1254" alt="Screen Shot 2020-12-18 at 3 11 46 PM" src="https://user-images.githubusercontent.com/72409237/102673207-09a21500-4148-11eb-8d1f-5c6683a6b851.png">

**Comment by rawmind0** [comment] 2021-01-05 19:02
Issue reproduced on rancher v2.5.x. 

Making some testing, the issue seems to be around https://github.com/rancher/rancher/blob/master/pkg/api/norman/store/cluster/cluster_store.go#L541
Data is arriving find to update function but Rancher API is not overwriting empty `virtual_center` entries. It's merging old and new values instead of replace them.

Investigating to find out a solution for this issue.

Starting from original example:

* Deploy cluster with cloud_provider with 2 virtual_centers: Working
```
rancher_kubernetes_engine_config:
  cloud_provider:
    name: vsphere
    vsphereCloudProvider:
      disk: {}
      global:
        insecure-flag: true
        soap-roundtrip-count: 0
      network: {}
      virtual_center:
        172.16.10.22:
          datacenters: /Homelab
          soap-roundtrip-count: 0
          user: administrator@vsphere.local
        172.16.10.23:
          datacenters: /Homelab2
          soap-roundtrip-count: 0
          user: administrator@vsphere.local
      workspace:
        datacenter: /Homelab
        folder: /Homelab/vm/K8S
        server: 172.16.10.23
```

* Updating cluster removing 1 virtual_centers: Not working. It's merging old and new values instead of replace them, letting virtual_center.172.16.10.22 as was.
```
rancher_kubernetes_engine_config:
  cloud_provider:
    name: vsphere
    vsphereCloudProvider:
      disk: {}
      global:
        insecure-flag: true
        soap-roundtrip-count: 0
      network: {}
      virtual_center:
        172.16.10.23:
          datacenters: /Homelab2
          soap-roundtrip-count: 0
          user: administrator@vsphere.local
      workspace:
        datacenter: /Homelab
        folder: /Homelab/vm/K8S
        server: 172.16.10.23
```

* Updating cluster setting 1 empty virtual_centers: Not working. It's merging old and new values instead of replace them, setting virtual_center.172.16.10.22 as empty.
```
rancher_kubernetes_engine_config:
  cloud_provider:
    name: vsphere
    vsphereCloudProvider:
      disk: {}
      global:
        insecure-flag: true
        soap-roundtrip-count: 0
      network: {}
      virtual_center:
        172.16.10.22:
        172.16.10.23:
          datacenters: /Homelab2
          soap-roundtrip-count: 0
          user: administrator@vsphere.local
      workspace:
        datacenter: /Homelab
        folder: /Homelab/vm/K8S
        server: 172.16.10.23
```

**Comment by rawmind0** [comment] 2021-01-06 11:11
Submitted PR #30692 to fix the issue

**Comment by sadiapoddar** [comment] 2021-01-21 19:39
Verified the fix on 2.4-head, commit id, 4c214400c,

1. Created a cluster on vSphere cloud provider by choosing the "custom" provider option and added the clouder provider information in YMAL file

2. Once the cluster is up checked all the config info.

`
root@sadia-control1:# docker inspect kube-apiserver |grep cloud
"--cloud-config=/etc/kubernetes/cloud-config",
"--cloud-provider=vsphere",
"--cloud-config=/etc/kubernetes/cloud-config",
"--cloud-provider=vsphere",
root@sadia-control1:# cat /etc/kubernetes/cloud-config
[Global]
user = ""
password = ""
insecure-flag = "true"
soap-roundtrip-count = "0"

[VirtualCenter "xxx"]
user = ""xxxxx"r"
password = ""xxxxx""
port = "443"
datacenters = ""xxxxx""
soap-roundtrip-count = "0"

[Workspace]
server = "xxx"
datacenter = "xxxxx"
folder = "xxxxx"
default-datastore ="xxxxx"
resourcepool-path = ""xxxxx""


3. Edited the cluster configuration and added a second non-existing vCenter information in the cluster config and saved it
<img width="713" alt="Screen Shot 2021-01-21 at 11 28 15 AM" src="https://user-images.githubusercontent.com/72409237/105402073-d128a780-5bdb-11eb-99fb-1a6242f23e55.png">

4. Noticed a health error during updating the cluster with the newly added Center. 

5. Re-edited the cluster config to remove the newly added vCenter info 
6. Checked after saving it 
The cloud configuration doesn't have the second vCenter information in the config

<img width="700" alt="Screen Shot 2021-01-21 at 11 32 48 AM" src="https://user-images.githubusercontent.com/72409237/105402689-9a06c600-5bdc-11eb-87bd-b5dec89fe567.png">

7. Cluster became healthy. 

Closing the bug as vCenter's in-tree server entries are propagating as expected

**Comment by deniseschannon** [comment] 2021-05-05 20:28
We will need a proper fix for v2.6, v2.5 and v2.4 as the current one changes and breaks the API for edge cases.

**Comment by rawmind0** [comment] 2021-06-03 13:23
Submitted PR https://github.com/rancher/rancher/pull/33009 proposing a fix for this issue. 

More info at https://github.com/rancher/rancher/pull/33009#issue-660793933

**Comment by jiaqiluo** [comment] 2021-06-22 14:58
can be validated in rancher:`v2.5.9-rc3`

**Comment by slickwarren** [comment] 2021-06-23 22:10
Tested the following on v2.5.9-rc3, 2.5-head (2412e01183eed0c62f8cc4f27334966d388e8b92), and master-head (d44698d):
* deploy rancher setup on vsphere
* provision downstream cluster using vsphere provisioner
  * configure downstream cluster with 2 virtual-centers as in this example/original comment: https://github.com/rancher/rancher/issues/27306#issuecomment-754835065
* allow cluster to come to active
* edit cluster, remove one of the virtual-centers

verified that:
* issue is reproducible in 2.5.5 ( unable to remove 2nd virtual center)
* downstream cluster does remove 2nd virtual center
* downstream cluster continues to operate normally after 2nd vcenter is removed
* after reproducing in 2.5.5, updating the rancher setup to 2.5.9-rc3 + re-removing the 2nd virtual center does indeed remove it + cluster operates normally after removal.

**Closed by slickwarren** 2021-06-23 22:10 UTC
Labels: QA/S, [zube]: To Test, area/server, internal, priority/0

**Comment by sowmyav27** [comment] 2021-07-06 20:10
Backport ticket logged [here](https://github.com/rancher/rancher/issues/33491)
