### ISSUE TITLE
Unsuccessful catalog/helm chart will spam new configmap entries and breaking ranchers responsiveness

### ISSUE THREAD

**Issue by wzrdtales** [rancher/rancher#18673] opened 2019-03-07 08:26 UTC
**What kind of request is this (question/bug/enhancement/feature request):**

bug

**Steps to reproduce (least amount of steps as possible):**

Install a catalog item and bring it to fail while installing or upgrading and just leave it running.

**Result:*

The catalog item will spam over and over again new configmap entries for releases. This is of course just how helm stores its data. It has however a bad impact on the whole system. It slows down rancher, or may make it even impossible to use, since rancher tries to receive all config maps before allowing control. This might take a loooooooong time then.

![image](https://user-images.githubusercontent.com/1786821/53942206-7145b800-40ba-11e9-9f4e-42e36b58e1e3.png)

And the second thing is, it might fill up all the etcd nodes, since things can get big here more quickly than one would think. Finally the last problem is, that deleted all the created releases itself, takes an eternity and basically breaks the functionality to remove the namespace and forces to remove them by hand through kubectl and high parallelism, to at least speed up things a bit.

**Other details that may be helpful:**

The configmaps are created by helm, and it seems they're never being cleaned up. Probably `maxHistory` is unset and therefor unlimited. That could be already an easy fix to the issue.

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): rancher/rancher:2.1.6
- Installation option (single install/HA): HA

**Cluster information**
Not relevant for this issue

**Comment by superseb** [comment] 2019-03-07 08:48
Duplicate of https://github.com/rancher/rancher/issues/17994

**Closed by superseb** 2019-03-07 08:48 UTC

**Comment by wzrdtales** [comment] 2019-03-07 08:52
@superseb Disagree, at least when the information is not merged to the other issue. And the reason is also a different, this is b/c helm has no limitations set to `maxHistory` the other issue, just complains about the retry. While this is also just happens b/c of retrying there is an overlap, but these information definitely need to be merged, since this is the reason I did not found an open ticket for it yet :)
