### ISSUE TITLE
[BUG][v2.9] Unable to use Rancher UI proxied Grafana to view most(?) dashboards

### ISSUE THREAD

**Issue by blovett** [rancher/rancher#46567] opened 2024-08-07 15:27 UTC
**Rancher Server Setup**
- Rancher version: 2.9.0
- Installation option (Docker install/Helm Chart): Helm
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): 
     - 104.1.0+up57.0.3
     - RKE2 v1.28.12+rke2r1
- Proxy/Cert Details:

**Information about the Cluster**
- Kubernetes version: v1.28.12+rke2r1 / v1.30.2+rke2r1
- Cluster Type (Local/Downstream): both
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider): custom, rke2

**User Information**
- What is the role of the user logged in? Admin

**Describe the bug**

When attempting to view graphs in Grafana that have been proxied through the Rancher UI, some end up erroring out in a funny way. Example shown in the below screenshot.

![rancher-proxy-error-example](https://github.com/user-attachments/assets/8790b1c4-15c0-4c5a-9a97-5098b0835659)

**To Reproduce**

Navigate to cluster dashboard. Select Monitoring on the left hand side. Then select Grafana. Open up a dashboard such as "Kubernetes / Compute Resources / Cluster".

**Result**

The browser window goes white, and the dashboard does not display as expected. 

**Expected Result**

Dashboards are usable.

**Screenshots**
Attached above.

**Additional context**
None that I can think of at this moment.

**Comment by mallardduck** [comment] 2024-08-13 21:29
Hiya @blovett - Can you share what version of the monitoring chart you are using here? I mostly want to confirm because there are 2 versions of charts that we shipped for `rancher-monitoring` in 2.9.0 - so I want to confirm which of the two this issue happens on for you? Or if it happens on both versions?

**Comment by blovett** [comment] 2024-08-13 22:39
> Hiya @blovett - Can you share what version of the monitoring chart you are using here? I mostly want to confirm because there are 2 versions of charts that we shipped for `rancher-monitoring` in 2.9.0 - so I want to confirm which of the two this issue happens on for you? Or if it happens on both versions?

Hi. This is with `rancher-monitoring-104.1.0+up57.0.3`. I have not tried the other version yet. Sorry for leaving this out.

**Comment by blovett** [comment] 2024-08-14 11:13
I installed the other version (`104.0.0+up45.31.1`) on a test cluster and it does not exhibit this behavior. Upgrading it to `104.1.0+up57.0.3` and it does. Downgrading, it doesn't again.

**Comment by mallardduck** [comment] 2024-08-14 13:33
@blovett - Greatly appreciate you clarifying the version and going as far as testing both!

We shipped two versions this release because we were upgrading the underlying components. So the issue seems to only exist in the newer version. From my quick test on my side it seems like the issue seems to be related to some missing or inaccessible web-assets. We'll look into this further and see about getting this fixed.

**Comment by mallardduck** [comment] 2024-08-14 14:30
Digging more into this - just going to dump a stream of w/e logging I can find:

Here's the URL that is failing: `/api/v1/namespaces/cattle-monitoring-system/services/http:rancher-monitoring-grafana:80/proxy/chunk.8.8aa451110aebe6a6cc4f.js`

From grafana container logs on `rancher-monitoring-grafana-` pod:
```
logger=context userId=0 orgId=1 uname= t=2024-08-14T14:21:07.503318251Z level=info msg="Request Completed" method=GET path=/chunk.8.8aa451110aebe6a6cc4f.js status=404 remote_addr=192.168.1.140 time_ms=1102 duration=1.102236101s size=45291 referer="/api/v1/namespaces/cattle-monitoring-system/services/http:rancher-monitoring-grafana:80/proxy/d/efa86fd1d0c121a26444b636a3f509a8/kubernetes-compute-resources-cluster?orgId=1&refresh=10s" handler=notfound
```

Upon doing a complete wip of site cache (via Application tab of devtools, "Clear Site Data") the UI loading issues no longer break the page visually. However the 404 for the JS file still happens and many graphs are incorrectly rendered. Of note - loading a different dashboard works fine.

I've determined the 404 isn't the root cause of this issue. As the issue happens on dashboards where the 404 does not appear. The issue is actually related to this error in the JS console:

```
Uncaught (in promise) Error: A listener indicated an asynchronous response by returning true, but the message channel closed before a response was received
```

**Comment by mallardduck** [comment] 2024-09-04 20:13
This appears to be fixed in the [pending rebase for 2.10](https://github.com/rancher/charts/pull/4384) bumping to use `61.3.2` upstream.
I suspect that this will be backported to 2.9 and should resolve this issue at that time.

**Comment by skanakal** [comment] 2024-09-16 11:35
@mallardduck This issue is likely from here https://github.com/grafana/grafana/issues/76180
 The fix is included in Grafana v10.3.4, and it worked for me...

**Comment by mallardduck** [comment] 2024-09-26 17:19
@skanakal - I've tested and found we can upgrade to a higher version to fix as well. I have created initial PR to mirror the new versions we will need.

**Comment by mallardduck** [comment] 2024-09-30 00:19
Still need a PR to patch existing affected chart versions to use new images.

**Comment by mallardduck** [comment] 2024-10-01 15:53
Fix merged into `dev-v2.9` branch under [104.1.2-rc.1+up57.0.3](https://github.com/rancher/charts/pull/4517/commits/b62b8b4c4e0e9c473a334cc556602354838affd1)

**Comment by deepakpunia-suse** [comment] 2024-10-14 14:49
Bug verification steps confirmed Grafana dashboards load correctly without issues with below version. The white screen issue appears resolved.

Details :
Rancher : v2.9.3-alpha5
cluster : v1.30.5+rke2r1
monitoring : 104.1.2-rc.1+up57.0.3
logging : 104.1.2-rc.1+up4.8.0

Steps to verify this bug:
Access Grafana via Rancher UI.
Select a dashboard, like "Kubernetes / Compute Resources / Cluster."
Observe for any white screen error on loading the dashboard.

Attached screen shot
![Image](https://github.com/user-attachments/assets/8e4bcb5f-8f88-41e8-bbf5-3b68e17cb560)

**Closed** 2024-10-15 16:16 UTC
Labels: kind/bug, team/observability&backup

**Comment by deepakpunia-suse** [comment] 2024-10-21 09:08
Now it's changed to `104.1.2+up57.0.3` version
