### ISSUE TITLE
Rollback - k8s version not reflected on clusters after rancher server rollback

### ISSUE THREAD

**Issue by sowmyav27** [rancher/rancher#18382] opened 2019-02-25 20:42 UTC
**What kind of request is this:** bug

**Steps to reproduce:**
1. Launch rancher server v2.1.6
2. Create a cluster with k8s version - v1.11.6
3. Upgrade rancher server to v2.2.0-rc2.
4. For the cluster created already, upgrade k8s version to v1.12.5/ v1.13.1
5. Rollback the rancher server to v2.1.6

**Expected Result:**
`kubernetesVersion` under `rancherKubernetesEngineConfig` and `appliedSpec` should reflect the upgraded one, which is under `gitVersion`

**Actual Result:**
`kubernetesVersion` under `rancherKubernetesEngineConfig` and `appliedSpec` reflects older version. 

<img width="438" alt="screen shot 2019-02-25 at 12 39 12 pm" src="https://user-images.githubusercontent.com/26032343/53367332-b61f6100-38fa-11e9-9aec-9cfc8d3d5b6b.png">

<img width="365" alt="screen shot 2019-02-25 at 12 39 25 pm" src="https://user-images.githubusercontent.com/26032343/53367339-bddf0580-38fa-11e9-991f-ea93de2a78ec.png">

<img width="334" alt="screen shot 2019-02-25 at 12 39 40 pm" src="https://user-images.githubusercontent.com/26032343/53367345-c46d7d00-38fa-11e9-8fd8-fa801fb95559.png">

**Other details that may be helpful:**

**Environment information**
- Rancher version: v2.1.6 to v2.2.0-rc2
- Installation option (single install/HA): single install

**Cluster information**
- Cluster type : DO/AWS/Azure
- Kubernetes version (use `kubectl version`):

```
before upgrade of rancher- v1.11.6
after upgrade of rancher - upgraded to v1.12.5/ v1.13.1
```

**Comment by kinarashah** [comment] 2019-02-26 00:54
@sowmyav27 I am able to reproduce this issue when I rollback to the etcd backup taken before the upgrade. This is expected, because this data doesn't have latest cluster state. Also, don't think `v1.12.5` is supported version for `rancher/rancher:v2.1.6`. So we'd sync up information from v1 k8s node, and it would reflect in version under cluster API but not in our saved RKE config. 

These kind of rollbacks would only happen when upgrade fails for some reason, and user wants to rollback to previous data and restore the system. So I think we should be okay with this, @alena1108 @sangeethah can confirm.

**Comment by alena1108** [comment] 2019-02-26 00:59
Confirming. When rancher rolls back, it rolls back to the old etcd snapshot. It means that any changes done on the next rancher version prior to rollback, can get lost once rollback is performed.

**Comment by cjellick** [comment] 2019-02-26 02:56
wont fix

**Closed by cjellick** 2019-02-26 02:56 UTC
Labels: kind/bug-qa, version/2.0
