### ISSUE TITLE
AD Authentication - Allow members of clusters, projects, etc not working as expected

### ISSUE THREAD

**Issue by nxf5025** [rancher/rancher#15181] opened 2018-08-22 14:13 UTC
**Rancher versions:**
v2.0.7

**Steps to Reproduce:**
1. Configure AD Authentication
2. For site access select "Allow members of Clusters, Projects, plus Authorized Users and Organizations"
3. Create a cluster and configure the members using an AD group
4. Attempt to log in with a user that is a part of the AD group associated with the cluster, but not a part of the "Authorized Users and Organizations"

**Results:**
"Logging in failed: Check credentials, or your account may not be authorized to log in."

**Comment by mrajashree** [comment] 2018-08-28 17:13
Hi @nxf5025, I'd like to check a few things
1. Have you provided any value for the Default Login Domain? If yes then are the users from this group under same domain. If there isn't any value provided to Default Login Domain, are the users using their domains to login?
2. This ldapsearch command is equivalent to the query we run to test user creds, can you run this and share the result?
```
ldapsearch -H ldap://server -x -D "loginDomain\testUsername" -W -b "UserSearchBase" -s sub "(&(sAMAccountName=testusername)(objectClass=person))"
```

**Comment by nxf5025** [comment] 2018-08-28 18:19
1. Default Domain: JNJ - Attempting to log in with a user in the NA domain (na\nfisher1)
2. Possible to email you the output of the ldapsearch? It contains emails and phone numbers so I don't want to publicly post.

**Comment by mrajashree** [comment] 2018-08-28 18:26
@nxf5025  Oh that's okay, I actually only wanted to see if that command succeeds or returns "Invalid Credentials" or some other errors.

**Comment by nxf5025** [comment] 2018-08-28 18:27
Okay yes I can confirm that it returns valid data

**Comment by mrajashree** [comment] 2018-08-28 18:57
Okay thanks @nxf5025 , how about the nested group memberships option? Is that what you're trying and is that enabled?

**Comment by nxf5025** [comment] 2018-08-28 22:17
I have the nested group option disabled. If I enable it I get an "ldap: connection timed out"

**Comment by mrajashree** [comment] 2018-08-28 23:51
@nxf5025 So is the user who's trying to login, a member of the group added to the cluster via nested membership? Just want to confirm so we know that the problem is because of nested memberships not being retrieved
Maybe running these commands can tell us for sure
If user is a part of the group via nested membership then this first command won't return any entries in the response, but the second will
1. non-nested query
```
ldapsearch -H ldap://server -x -D "loginDomain\testUsername" -W -b "UserTryingToLogin's_DN" -s base "(memberOf=GroupAddedToCluster's_DN)"
```
2. nested
```
ldapsearch -H ldap://server -x -D "loginDomain\testUsername" -W -b "UserTryingToLogin's_DN" -s base "(memberof:1.2.840.113556.1.4.1941:=GroupAddedToCluster's_DN)"
```

**Comment by nxf5025** [comment] 2018-08-29 15:40
Confirmed that both commands are returning a lot of entries

**Comment by alena1108** [comment] 2018-08-30 21:15
Requested more info (logs, devtools screen shots) from the user

**Comment by mrajashree** [comment] 2018-09-04 18:55
After getting further information, we found that the CRTBs for cluster-members contained group names that didn't exactly match the group's DNs, because of the way they were being added, which is not a rancher issue. Closing this bug

**Closed by mrajashree** 2018-09-04 18:55 UTC
Labels: area/authentication, kind/bug, priority/-1, status/more-info, team/ca, version/2.0
