### ISSUE TITLE
Can't launch machine in AWS ME region 

### ISSUE THREAD

**Issue by dominicpg** [rancher/rancher#31980] opened 2021-04-08 05:49 UTC
Issue :   Can't launch EC2 rke cluster in AWS ME south region using node template that has created using default AMI/settings. logged " handler node-controller: Error setting machine configuration from flags provided: Invalid region specified, requeuing" 

Steps to reproduce: 
1) Create AWS node template for EC2 rke deployment , under AWS - ME south region ( aka Bahrain ) , using default settings.
2) No change in AMI . Accept default AMI/user while creating template.
3) Deploy cluster -  Add cluster -> EC2 cluster -> Deploy new cluster.
4) No New instance will start/deploy in EC2 dashboard and Rancher cluster GUI will signal waiting for etcd/control/ nodes.
5) Rancher Manager has captured below in logs.

2021/04/08 05:48:08 [INFO] Creating jail for c-lwhzp
2021/04/08 05:48:08 [INFO] Provisioning node ctrl-nodes-2
2021/04/08 05:48:08 [INFO] Provisioning node worker-nodes-1
2021/04/08 05:48:08 [INFO] Provisioning node worker-nodes-2
2021/04/08 05:48:08 [INFO] Provisioning node ctrl-nodes-3
2021/04/08 05:48:08 [INFO] Provisioning node worker-nodes-3
2021/04/08 05:48:08 [INFO] Provisioning node ctrl-nodes-1
2021/04/08 05:48:08 [INFO] Generating and uploading node config ctrl-nodes-2
2021/04/08 05:48:08 [INFO] Generating and uploading node config worker-nodes-1
2021/04/08 05:48:08 [INFO] Generating and uploading node config worker-nodes-2
2021/04/08 05:48:09 [INFO] Generating and uploading node config ctrl-nodes-1
2021/04/08 05:48:09 [INFO] Generating and uploading node config ctrl-nodes-3
2021/04/08 05:48:09 [INFO] Generating and uploading node config worker-nodes-3
2021/04/08 05:48:23 [ERROR] [node] enqueing node pool c-lwhzp:np-f7mpr
2021/04/08 05:48:23 [ERROR] error syncing 'c-lwhzp/m-6v679': handler node-controller: Error setting machine configuration from flags provided: Invalid region specified, requeuing
2021/04/08 05:48:23 [ERROR] [node] enqueing node pool c-lwhzp:np-v64d8
2021/04/08 05:48:23 [ERROR] [node] enqueing node pool c-lwhzp:np-v64d8
2021/04/08 05:48:24 [ERROR] error syncing 'c-lwhzp/m-zkpld': handler node-controller: Error setting machine configuration from flags provided: Invalid region specified, requeuing
2021/04/08 05:48:24 [ERROR] error syncing 'c-lwhzp/m-cnw69': handler node-controller: Error setting machine configuration from flags provided: Invalid region specified, requeuing
2021/04/08 05:48:24 [ERROR] [node] enqueing node pool c-lwhzp:np-f7mpr
2021/04/08 05:48:24 [ERROR] [node] enqueing node pool c-lwhzp:np-v64d8
2021/04/08 05:48:24 [ERROR] [node] enqueing node pool c-lwhzp:np-f7mpr
2021/04/08 05:48:24 [ERROR] error syncing 'c-lwhzp/m-npxnb': handler node-controller: Error setting machine configuration from flags provided: Invalid region specified, requeuing
2021/04/08 05:48:24 [ERROR] error syncing 'c-lwhzp/m-4rwcn': handler node-controller: Error setting machine configuration from flags provided: Invalid region specified, requeuing
2021/04/08 05:48:24 [ERROR] error syncing 'c-lwhzp/m-ppmxx': handler node-controller: Error setting machine configuration from flags provided: Invalid region specified, requeuing

**Comment by janeczku** [comment] 2021-04-12 10:37
It appears we have added support for the `me-south-1` AWS region in the latest machine driver release. This is currently expected to ship in Rancher v2.5.8.

https://github.com/rancher/machine/commit/3ef91b79742d22bbc1fd5a94e797ceea79a79cc0
https://github.com/rancher/rancher/pull/31889

**Comment by dominicpg** [comment] 2021-04-12 13:44
great news. thanks @janeczku

**Comment by PennyScissors** [comment] 2021-04-19 20:35
I tried validating this issue, but credentials from `me-south-1` are required to validate it. The first step to reproduce it is to create a node template which won't be possible without credentials from the same region.

**Comment by PennyScissors** [comment] 2021-04-21 19:36
Tested in v2.5.8-rc7 (machine version v0.15.0-rancher54) using temporary test credentials given by @dominicpg.

Created node template for an EC2 single node cluster in the `me-south-1` region.
![image](https://user-images.githubusercontent.com/8951271/115605515-76b0ed00-a297-11eb-8352-a58876df8c97.png)
![image](https://user-images.githubusercontent.com/8951271/115609432-5fc0c980-a29c-11eb-9881-558c6d792a44.png)

Rancher failed to create the cluster with the following errors
```
2021/04/21 19:20:11 [INFO] [node-controller-rancher-machine] (screspo-me-region-test1) Missing instance ID, this is likely due to a failure during machine creation
2021/04/21 19:20:15 [ERROR] error syncing 'c-qbcx6/m-js6sf': handler node-controller: Error creating machine: Error in driver during machine creation: Error launching instance: Unsupported: The requested configuration is currently not supported. Please check the documentation for supported configurations., requeuing
```

**Comment by PennyScissors** [comment] 2021-04-21 20:10
Also tested in Rancher v2.5.7 (from docker image) and I successfully reproduced the initial problem
```
2021/04/21 20:03:00 [INFO] Creating jail for c-zd26j
2021/04/21 20:03:00 [INFO] Provisioning node screspo-me-region-test1
2021/04/21 20:03:00 [INFO] Generating and uploading node config screspo-me-region-test1
2021/04/21 20:03:15 [ERROR] [node] enqueing node pool c-zd26j:np-dnmr8
2021/04/21 20:03:15 [ERROR] error syncing 'c-zd26j/m-8fv85': handler node-controller: Error setting machine configuration from flags provided: Invalid region specified, requeuing
2021/04/21 20:05:15 [ERROR] error syncing 'c-zd26j/m-8fv85': handler node-controller: nodes.management.cattle.io "m-8fv85" not found, requeuing
2021/04/21 20:05:15 [INFO] Creating jail for c-zd26j
2021/04/21 20:05:15 [INFO] Provisioning node screspo-me-region-test2
2021/04/21 20:05:15 [INFO] Generating and uploading node config screspo-me-region-test2
2021/04/21 20:05:30 [ERROR] [node] enqueing node pool c-zd26j:np-dnmr8
2021/04/21 20:05:30 [ERROR] error syncing 'c-zd26j/m-t7s49': handler node-controller: Error setting machine configuration from flags provided: Invalid region specified, requeuing
```

**Comment by PennyScissors** [comment] 2021-04-24 01:57
I looked into this a bit more and I think the problem is happening in the Go AWS SDK we use in the AWS EC2 driver in rancher-machine. Launching an EC2 instance in the `me-south-1` region using rancher-machine and all default values will throw an unsupported configuration error (see below) due to a missing `InstanceId` paramenter which you get once the instance has been launched (but it failed to do so). Launching it using the AWS EC2 console with the same values works fine.

```
The request must contain the parameter InstanceId
Error creating machine: Error in driver during machine creation: Error launching instance: Unsupported: The requested configuration is currently not supported. Please check the documentation for supported configurations.
```

**Comment by PennyScissors** [comment] 2021-04-24 02:08
I looked into this a bit more and I think the problem is happening in the Go AWS SDK we use in the AWS EC2 driver in rancher-machine. Launching an EC2 instance in the `me-south-1` region using rancher-machine and all default values will throw an unsupported configuration error (see below) due to a missing `InstanceId` parameter which you get once the instance has been created, but it failed to do so (see [here](https://github.com/rancher/machine/blob/b7095a1a4fca03488f24605161b5ac431342d1c9/drivers/amazonec2/amazonec2.go#L788-L791)). Launching it using the AWS EC2 console with the same values works fine, so it is a problem in rancher-machine and likely unrelated to the default AMI being used.

```
The request must contain the parameter InstanceId
Error creating machine: Error in driver during machine creation: Error launching instance: Unsupported: The requested configuration is currently not supported. Please check the documentation for supported configurations.
```

**Comment by janeczku** [comment] 2021-04-26 09:13
@PennyScissors This is most likely related to using an unsupported EC2 instance type. The node template above appears to be configured with an instance from the T2 family, which might not be available in the `me-south-1` region.

**Comment by PennyScissors** [comment] 2021-04-26 17:51
@janeczku Good catch, I'll look into that.

**Comment by PennyScissors** [comment] 2021-04-26 18:02
@janeczku @rmweir Good catch, maybe [this](https://github.com/rancher/machine/blob/b7095a1a4fca03488f24605161b5ac431342d1c9/drivers/amazonec2/amazonec2.go#L39) needs to be bumped up to `t3.micro` instead.

**Comment by PennyScissors** [comment] 2021-04-26 18:46
Just confirmed the issue is caused by the EC2 instance type as @janeczku suggested (Thank you!). I successfully created an EC2 instance using standalone rancher-machine v0.15.0-rancher54 and all values set to their default except region and instance type. If all regions support t3 instances, the fix should be as easy as bumping the default. 
```
./rancher-machine -D create --driver amazonec2 --amazonec2-region me-south-1 --amazonec2-instance-type t3.micro screspo-me-test
```
![image](https://user-images.githubusercontent.com/8951271/116134330-9f185d00-a684-11eb-82a9-079d8cf18681.png)

**Comment by cbron** [comment] 2021-04-28 21:40
Moving this to 2.6 to investigate converting all regions from t2 to t3. cc @rmweir @dramich

**Comment by westlywright** [comment] 2021-04-29 18:01
UI will now change the default instance type to `t3.medium` in the event that a `me*` region is selected. CC: @cbron @rmweir

**Comment by PennyScissors** [comment] 2021-04-30 01:04
Validated in Rancher v2.5-head (`v2.5-7723077a1eb30c197bd2740c30a23882c4dad80b-head`)

The node template now has `t3.medium` as the default instance type

![image](https://user-images.githubusercontent.com/8951271/116635921-e4eb5480-a914-11eb-946a-9906c277717d.png)

Single node cluster was successfully created in the `me-south-1` region

![image](https://user-images.githubusercontent.com/8951271/116635977-0a785e00-a915-11eb-94c8-b77ceeed1986.png)

**Comment by PennyScissors** [comment] 2021-04-30 01:06
Validated in Rancher v2.5-head (`v2.5-7723077a1eb30c197bd2740c30a23882c4dad80b-head`)

The node template now has `t3.medium` as the default instance type

![image](https://user-images.githubusercontent.com/8951271/116635921-e4eb5480-a914-11eb-946a-9906c277717d.png)

Single node cluster was successfully created in the `me-south-1` region

![image](https://user-images.githubusercontent.com/8951271/116635977-0a785e00-a915-11eb-94c8-b77ceeed1986.png)

**Comment by PennyScissors** [comment] 2021-04-30 17:49
Validated in master-head (master-fcd9f3a2a9abe6ca07f8ee61a42b634e38f96080-head)

Same steps as above, cluster was created successfully:

![image](https://user-images.githubusercontent.com/8951271/116734048-c41d1080-a9a1-11eb-87e2-3dfb740edef3.png)

![image](https://user-images.githubusercontent.com/8951271/116734077-cda67880-a9a1-11eb-85d8-ccf997407f1e.png)

**Closed** 2021-04-30 19:39 UTC
Labels: [zube]: QA Working, priority/2, release-note, status/dev-validate
