### ISSUE TITLE
[BUG] Additional trusted CAs doesn't apply to keycloak oidc

### ISSUE THREAD

**Issue by HoustonDad** [rancher/rancher#43217] opened 2023-10-19 16:37 UTC
**Rancher Server Setup**
- Rancher version: 2.7.5

**Information about the Cluster**
- Kubernetes version: 1.25.x
- Cluster Type (Local/Downstream): Local

**User Information**
- What is the role of the user logged in: Admin

**Describe the bug**
Customers following the following: https://ranchermanager.docs.rancher.com/how-to-guides/new-user-guides/authentication-permissions-and-global-configuration/authentication-config/configure-keycloak-oidc#configuration-reference

Will run into an issue where a self signed keycloak server will fail unles the full CA bundle is used. Meaning either the additional trusted CA's aren't passed properly, or the documentation needs to be updated to include the need for it with self signed certificates.

**To Reproduce**
Create cluster using private signed CA
Add CA to additional trusted CA's
Configure keycloak server that uses certificates signed by the same CA
Add just the client certificate, as CA is in additional trusted certs, and the documentation doesn't explicitly state that the full chain should be needed.
Workaround:
Is workararound available and implemented? yes
What is the workaround: above

**Result**
Needs full chain to function

**Expected Result**
Either respects additional trusted CAs or documentation reflects that it doesn't. 

SURE-6675

**Comment by HoustonDad** [comment] 2023-10-19 16:38
This may be related to https://github.com/rancher/rancher/issues/42371

**Comment by tomleb** [comment] 2023-12-05 18:01
## Validation Template

## Root Cause

The OS certificate bundle isn't used when a cert/key is provided to the keycloak auth provider configuration. This bundle contains the [custom certs that user can specify during install](https://ranchermanager.docs.rancher.com/getting-started/installation-and-upgrade/resources/custom-ca-root-certificates).

## What was fixed, or what change have occurred

We're now using the OS bundle when the cert/key is provided.  So now the OS bundle is used whether or not the cert/key are provided.

## Areas or cases that should be tested

- P0 functionality for keycloak provider
- Rancher can connect to a keycloak behind certs/keys from a trusted custom CA **WITH** certs/keys provided in the authconfig.

## What areas could experience regressions

There might be regressions with the following properties when using the keycloak auth provider:

- HTTP proxy
  - The [HTTP proxy setting](https://ranchermanager.docs.rancher.com/reference-guides/single-node-rancher-in-docker/http-proxy-configuration) should be respected when no certs and keys are provided.
  - The HTTP proxy setting should NOT be respected when certs and keys are provided. (Will need another GH issue to fix this)
- Custom CA certs
  - A keycloak instance should be trusted if the CA cert is part of the custom CAs when certs and keys are provided in auth config.
  - A keycloak instance should be trusted if the CA cert is part of the custom CAs when certs and keys are NOT provided in auth config.



## Are the repro steps accurate/minimal?

N/A

**Comment by tomleb** [comment] 2024-03-21 15:46
# Release notes

## Authentication

### Behavior Changes

Rancher uses additional trusted CAs when establishing a secure connection to the keycloak OIDC authentication provider.

**Comment by dasarinaidu** [comment] 2024-03-22 00:12
Validated this issue on v2.8.3-rc3, looks good and closing this issue.

**Closed by dasarinaidu** 2024-03-22 00:12 UTC
Labels: kind/bug, internal, area/certificate, [zube]: To Test, QA/M, release-note, status/to-test, team/collie
