### ISSUE TITLE
Swarm Templates do not show version

### ISSUE THREAD

**Issue by will-chan** [rancher/rancher#4099] opened 2016-03-23 23:48 UTC
Rancher Version:
1.0.0-rc2
Docker Version:
1.10.3
OS: 

Steps to Reproduce: 
Under a Swarm environment, click on Catalog and select any templates.  Choose a version and there are no version text even though you can select it and eventually start the template.
![screen shot 2016-03-23 at 4 47 47 pm](https://cloud.githubusercontent.com/assets/10134676/14004395/0e744f5c-f117-11e5-92f5-f93f9e2f2142.png)

Results: 
Can't see version.
Expected:
Should see version.

**Comment by vincent99** [comment] 2016-03-24 01:09
This is because the templates don't have a rancher-compose.yml defining the version.

**Comment by LLParse** [comment] 2016-03-24 18:13
Closing issue because it is a duplicate of https://github.com/rancher/rancher/issues/4101

**Closed by LLParse** 2016-03-24 18:13 UTC
Labels: area/ui, kind/bug
