### ISSUE TITLE
Menu for Download CLI not showing properly

### ISSUE THREAD

**Issue by kaos** [rancher/rancher#3241] opened 2016-01-12 12:50 UTC
Hi,

Rancher: v0.51.0

When the "bottom" nav bar is not at the bottom, the popup menu for the download cli options opens below the button, resulting in not being shown properly..
![image](https://cloud.githubusercontent.com/assets/72965/12263962/7aaf5ebc-b933-11e5-8859-1132f6747473.png)

**Comment by RVN-BR** [comment] 2016-01-18 18:59
On 0.55.0-rc3 the menu is opening up normally (going up), but I cant download anymore... when I click any of the platforms there is a console error showing up "Uncaught Error: <ui@component:page-footer::ember1206> had no action handler for: composeDownload"

**Comment by vincent99** [comment] 2016-01-22 17:41
Two separate problems.. the links work now, but the footer still doesn't stick to the bottom of the page sometimes, and then the menu thinks it has room to go downward.

**Comment by tfiduccia** [comment] 2016-01-22 17:42
The original issue is still broken.  I can alway scroll down below the footer on every page and if I do that, then the CLI is not visible.  We have a good 3 inches of space below the footer.

**Comment by lvuch** [comment] 2016-02-02 15:24
Resolved in last release

**Comment by kaos** [comment] 2016-02-05 15:30
After a fresh page reload, the bottom nav/status bar is nicely fixed at the bottom of the page.
But after clicking around some dialogs (edit, upgrade, vies services, etc) there's some extra space below it again, it won't go away until I reload the page.

![image](https://cloud.githubusercontent.com/assets/72965/12850576/b63d3d6e-cc25-11e5-89fd-c7e9f5d3d66e.png)

**Comment by tfiduccia** [comment] 2016-02-11 17:07
Version - 0.58.0-rc2
Verified fixed - I can't reproduce this any longer.  Will keep an eye out for the extra space below the footer.

**Closed by tfiduccia** 2016-02-11 17:07 UTC
Labels: area/ui, kind/bug, status/resolved
