### ISSUE TITLE
Rancher-NFS should support nfsvers=3

### ISSUE THREAD

**Issue by jonathanbaraldi** [rancher/rancher#8943] opened 2017-05-31 21:16 UTC
**Rancher versions:**
rancher/server: 1.5.10
rancher/agent: v1.2.2 

**Infrastructure Stack versions:**
healthcheck :v0.2.3 
ipsec: holder
network-services: v0.6.6
scheduler: v0.7.5
kubernetes (if applicable):

**Docker version: (`docker version`,`docker info` preferred)**
1.12
**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
Centos7
**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
VMWare
**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
HA Rancher - Active/Active - external DB
**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle
**Steps to Reproduce:**
Create Rancher-NFS  and try to use NFS Version 3
**Results:**
Failed do mount

**Comment by joshwget** [comment] 2017-05-31 21:27
Duplicate of #7080

**Closed by joshwget** 2017-05-31 21:27 UTC
