### ISSUE TITLE
Can't view graphs

### ISSUE THREAD

**Issue by iangcarroll** [rancher/rancher#4077] opened 2016-03-22 15:29 UTC
Rancher Version: 0.63.1

Docker Version: N/A

OS: Ubuntu 

Steps to Reproduce: 
Go to a host's detail page.

Results: 
Graphs do not render and the following error is shown in the rancher server logs:
```
time="2016-03-22T15:26:42Z" level=info msg="Invalid HostUuid." hostUuid=4f53f245-bca7-4933-917c-02fdb74f6b60
time="2016-03-22T15:26:42Z" level=error msg="could not find host uuid"
time="2016-03-22T15:26:43Z" level=info msg="Registering backend for host [4f53f245-bca7-4933-917c-02fdb74f6b60]"
```

Expected:
Graphs render.

This also happens with container graphs, but there are no error logs in the dev console or server logs. It just shows sockets opening and then closing shortly after.

**Comment by deniseschannon** [comment] 2016-03-22 17:47
Duplicate of https://github.com/rancher/rancher/issues/3615

This is fixed in our next RC (v1.0.0-rc1)

**Closed by deniseschannon** 2016-03-22 17:47 UTC
