### ISSUE TITLE
[convoy-nfs] requires nolock mount option.. no nfs locking in convoy nfs

### ISSUE THREAD

**Issue by kkvilekval** [rancher/rancher#4953] opened 2016-05-30 05:03 UTC
Mounting convoy-nfs fails unless nolock is included in the mount options. It appears that while rpcbind is started by the launch script, the rpc.statd is not. File locking over nfs is thus unavailable.

We actually need locking over nfs.

https://github.com/rancher/convoy-agent/blob/master/packaging/convoy-agent/launch#L171

 5/11/2016 9:46:04 PMWaiting for metadata
    5/11/2016 9:46:04 PMtime="2016-05-12T04:46:04Z" level=info msg="Execing [/usr/bin/nsenter --mount=/proc/21656/ns/mnt -F -- /var/lib/docker/aufs/mnt/9362b696c64335f026344abfdbf1ba74329ff7e039ceb8828de7041c31f6aa8f/var/lib/rancher/convoy-agent/share-mnt --stage2 /var/lib/rancher/convoy/convoy-nfs-47f99cab-b92d-45c2-88cb-e086cad2775a -- /launch volume-agent-nfs-internal 21656]"
    5/11/2016 9:46:04 PMRegistering convoy socket at /var/run/convoy-convoy-nfs.sock
    5/11/2016 9:46:04 PMMounting at: /var/lib/rancher/convoy/convoy-nfs-47f99cab-b92d-45c2-88cb-e086cad2775a/mnt
    5/11/2016 9:46:04 PMMounting nfs. Command: mount -t nfs -o rsize=32768,wsize=32768,noatime,intr XX.XX.XX.XX:/export/rdata/nsfdata /var/lib/rancher/convoy/convoy-nfs-47f99cab-b92d-45c2-88cb-e086cad2775a/mnt
    5/11/2016 9:46:04 PMmount.nfs: rpc.statd is not running but is required for remote locking.
    5/11/2016 9:46:04 PMmount.nfs: Either use '-o nolock' to keep locks local, or start statd.
    5/11/2016 9:46:04 PMmount.nfs: an incorrect mount option was specified

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v1.0.1` Cattle: `v0.159.7` UI: `v1.0.5` |
|Access|`localauth` `admin`|
|Route|`environments.index`|

**Comment by fabiorauber** [comment] 2016-05-31 16:23
I'm using CoreOS and ran into the same problem. Starting rpc.statd.service on the host solved it. In addition, convoy-nfs does not support self-signed certificates.

**Comment by kkvilekval** [comment] 2016-05-31 16:59
Sorry but I am unclear what you mean by host in this context?
Is this the host where the docker containers are run?  Is this possible to
do when the host is started through rancher?

Or do I need to somehow start this in the container itself where rpc.bind
is run?

Thanks.

On Tue, May 31, 2016 at 9:23 AM, Fabio Rauber <notifications@github.com>
wrote:

> I'm using CoreOS and ran into the same problem. Starting rpc.statd.service
> on the host solved it. In addition, convoy-nfs does not support self-signed
> certificates.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/rancher/rancher/issues/4953#issuecomment-222742015>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/APDrqCDkC3Cm68TB5B0ZbdAqd4tvW2_Uks5qHGCJgaJpZM4IpfbY>
> .
>



-- 
Kris Kvilekval (kris@viqi.org)
www.ViQi.org  (805)-699-6081

**Comment by lyoungblood** [comment] 2016-06-06 16:22
Is there a way to enable rpc.statd on RancherOS?  I ran into this issue as well, and adding nolock to the Convoy NFS options is not viable for production use.

**Comment by fabiorauber** [comment] 2016-06-06 16:56
@kkvilekval, actually I use CoreOS as the host OS, where the containers run. I made it start automatically via cloud config, starting the rpc-statd.service systemd unit.

**Comment by fabiorauber** [comment] 2016-06-06 16:58
@lyoungblood, I assumed this did not happen with RancherOS, and wondered why I decided to use CoreOS...

**Comment by lyoungblood** [comment] 2016-06-06 17:29
I can confirm that it does happen on the latest version of RancherOS as well.  Adding the nolock option is a temporary workaround.

**Comment by lyoungblood** [comment] 2016-06-07 19:49
Interestingly enough, on a RHEL 7 cluster, where NFS locking is enabled by enabling rpc-statd and nfs-lock services, the following error occurs while attempting to start a container that relies on Convoy NFS driver:  Error (500 Server Error: Internal Server Error ("create mysolr-nfs2: Coudln't get flock. Error: no locks available"))

Note: spelling is same as error received (Coudln't instead of Couldn't)

**Comment by kkvilekval** [comment] 2016-06-07 19:56
so to make this very confusing.. I can use convory-nfs with locking if:

1.  Install a recent NFS server on bare (non-rancher)  ubuntu or debian node
2.  Specify nfsvers=4 as a convoy-nfs mount options.

Interestingly it appears that nfs ver 4 somehow takes over the role of rpc.statd and statd does not need to be started.

I had been trying to use softnas are our NFS server and while this did support nfs ver 3 and 4.  While it reported using nfs ver 4 , it did not support locking.  Using my NFS server seems to work.

**Comment by lyoungblood** [comment] 2016-06-07 22:03
@kkvilekval This actually makes sense because rpc.statd locking is only required for NFS versions 2 and 3.  If your server supports NFSv4, rpc.statd shouldn't be necessary.

**Comment by guzmo** [comment] 2016-08-12 09:42
I see this is marked as resolved but is it possible to try it or which version will it be available in?

**Comment by janeczku** [comment] 2016-08-12 23:58
@guzmo The version that has the fix is v0.10.0. See the PR here: https://github.com/rancher/rancher-catalog/pull/186.

**Comment by sangeethah** [comment] 2016-08-13 03:05
@janeczku , I tried with rancher/convoy-agent:v0.10.0 with template version - v0.5.0.

Convoy-nfs instance is able to start (with nfsvers=3) , but I am not able to create services with volumes using convoy-nfs ..I get the following error:

```2016-08-13 02:49:24,132 ERROR [419d48aa-88a2-4bd0-9f38-e5a041a2c04c:94065] [instance:2007->instanceHostMap:2001] [instance.start->(InstanceStart)->instancehostmap.activate] [] [utorService-529] [c.p.e.p.i.DefaultProcessInstanceImpl] Agent error for [compute.instance.activate.reply;agent=157]: 500 Server Error: Internal Server Error ("create myvol1: Coudln't get flock. Error: no locks available") ```

 ```2016-08-13 02:55:37,964 INFO agent [140566522256752] [utils.py:430] worker2 : Done request 95d4c7a8-bbfc-45d0-949b-5396c42daf1e for compute.instance.activate [28.976323843] seconds 
2016-08-13 02:55:37,964 ERROR agent [140566522256752] [event.py:112] Error in request : 95d4c7a8-bbfc-45d0-949b-5396c42daf1e 
Traceback (most recent call last):
  File "/var/lib/cattle/pyagent/cattle/agent/event.py", line 95, in _worker_main
    resp = agent.execute(req)
  File "/var/lib/cattle/pyagent/cattle/agent/__init__.py", line 15, in execute
    return self._router.route(req)
  File "/var/lib/cattle/pyagent/cattle/plugins/core/event_router.py", line 13, in route
    resp = handler.execute(req)
  File "/var/lib/cattle/pyagent/cattle/agent/handler.py", line 34, in execute
    return method(req=req, **req.data.__dict__)
  File "/var/lib/cattle/pyagent/cattle/plugins/docker/compute.py", line 529, in instance_activate
    self._do_instance_activate(instance, host, progress)
  File "/var/lib/cattle/pyagent/cattle/plugins/docker/compute.py", line 585, in _do_instance_activate
    self._setup_volumes(create_config, instance, start_config, client)
  File "/var/lib/cattle/pyagent/cattle/plugins/docker/compute.py", line 729, in _setup_volumes
    DockerPool.do_volume_activate(v)
  File "/var/lib/cattle/pyagent/cattle/plugins/docker/storage.py", line 199, in do_volume_activate
    return DockerPool()._do_volume_activate(volume, None, None)
  File "/var/lib/cattle/pyagent/cattle/plugins/docker/storage.py", line 232, in _do_volume_activate
    JsonObject.unwrap(driver_opts))
  File "/var/lib/cattle/pyagent/dist/docker/utils/decorators.py", line 35, in wrapper
    return f(self, *args, **kwargs)
  File "/var/lib/cattle/pyagent/dist/docker/api/volume.py", line 24, in create_volume
    return self._result(self._post_json(url, data=data), True)
  File "/var/lib/cattle/pyagent/dist/docker/client.py", line 150, in _result
    self._raise_for_status(response)
  File "/var/lib/cattle/pyagent/dist/docker/client.py", line 146, in _raise_for_status
    raise errors.APIError(e, response, explanation=explanation)
APIError: 500 Server Error: Internal Server Error ("create myvol1: Coudln't get flock. Error: no locks available")
2016-08-13 02:55:37,972 INFO agent [140566522256752] [utils.py:430] Response: {"name": "reply.5120103123148676929", "resourceType": "instanceHostMap", "resourceId": "1ihm2006", "id": "858a896c-1c42-4cc7-96c8-22f7993f464a", "transitioningInternalMessage": "500 Server Error: Internal Server Error (\"create myvol1: Coudln't get flock. Error: no locks available\")", "time": 1471056937000, "previousNames": ["compute.instance.activate"], "transitioning": "error", "data": {}, "previousIds": ["95d4c7a8-bbfc-45d0-949b-5396c42daf1e"]} [0.00601506233215] seconds 
```

**Comment by sangeethah** [comment] 2016-08-15 17:52
convoy-nfs logs:
```
15/2016 10:12:34 AMtime="2016-08-15T17:12:34Z" level=debug msg="Create a new volume test1 for docker" pkg=daemon
8/15/2016 10:12:34 AMtime="2016-08-15T17:12:34Z" level=debug msg= event=create object=volume opts=map[Size:0 BackupURL: VolumeName:test1 VolumeDriverID: VolumeType: VolumeIOPS:0 PrepareForVM:false] pkg=daemon reason=prepare volume=test1
8/15/2016 10:12:40 AMtime="2016-08-15T17:12:40Z" level=debug msg="Response:  {\n\t\"Err\": \"Coudln't get flock. Error: no locks available\"\n}" pkg=daemon
8/15/2016 10:14:05 AMtime="2016-08-15T17:14:05Z" level=debug msg="Handle plugin get volume: POST /VolumeDriver.Get" pkg=daemon
```

**Comment by janeczku** [comment] 2016-08-15 21:36
@sangeethah As usual test using the template from my catalog. The image should be `janeczku/convoy-agent:v0.10.1-test`.

**Comment by sangeethah** [comment] 2016-08-15 23:40
@janeczku , when trying to the latest image that has changes from https://github.com/rancher/convoy-agent/issues/30 , there is a problem with not being able to launch containers having volumes in convoy-nfs using NFSv3  .Following error seen in convoy-nfs 
```
8/15/2016 3:58:10 PMtime="2016-08-15T22:58:10Z" level=debug msg= event=create object=volume opts=map[VolumeType: VolumeIOPS:0 PrepareForVM:false Size:0 BackupURL: VolumeName:testnew123 VolumeDriverID:] pkg=daemon reason=prepare volume=testnew123
8/15/2016 3:58:16 PMtime="2016-08-15T22:58:16Z" level=debug msg="Response:  {\n\t\"Err\": \"Coudln't get flock. Error: no locks available\"\n}" pkg=daemon
```

Following is NFS export config:

```/var/nfs *(rw,sync,no_subtree_check)```

**Comment by sangeethah** [comment] 2016-08-16 22:45
Tested with image- janeczku/convoy-agent:v0.10.1-test hat has changes from rancher/convoy-agent#30 .

Able to get convoy-nfs system stack deployed successfully using NFSv3. Also able to create services having volumes from this convoy-nfs as volume driver.

Also able to get convoy-nfs system stack deployed successfully using NFSv4. Able to create services having volumes from this convoy-nfs as volume driver.

**Comment by cjellick** [comment] 2016-09-13 19:57
Reopened because it was accidentally auto-closed when I merge the above PR.

**Comment by cjellick** [comment] 2016-09-13 19:57
To test:
1. Test with an nfs v3 server, ensure works
2. Test with an nfs v4 server on a kernel older than 3.13, ensure works.

**Comment by sangeethah** [comment] 2016-09-14 00:19
Tested with rancher-server version - v1.2.0-pre3-rc3 with  https://github.com/cjellick/rancher-catalog/ using rancher/convoy-agent:v0.12.0.

1. Tested with an nfs v4 server on a kernel older than 3.14.

root@san-nfs-2:/var/nfs# uname -a
Linux san-nfs-2 3.13.0-95-generic #142~precise1-Ubuntu SMP Fri Aug 12 18:20:15 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

Able to start "convoy-nfs" stack successfully and able to create services using "convoy-nfs" volume drivers .

2. Tested  using NFSv3 (by setting mount_opts: nfsvers=3)

Not also able to get convoy-nfs system stack to deploy successfully using NFSv3. 

```
13/2016 5:00:34 PMMounting nfs. Command: mount -t nfs -o nfsvers=3 159.203.111.19:/var/nfs /var/lib/rancher/convoy/convoy-nfs-ver3-8960fd8c-3393-4c2b-806f-9f5909ce9254/mnt
9/13/2016 5:00:34 PMmount.nfs: rpc.statd is not running but is required for remote locking.
9/13/2016 5:00:34 PMmount.nfs: Either use '-o nolock' to keep locks local, or start statd.
9/13/2016 5:00:34 PMmount.nfs: mounting 159.203.111.19:/var/nfs failed, reason given by server: No such file or directory
9/13/2016 5:00:36 PMWaiting for metadata
9/13/2016 5:00:37 PMtime="2016-09-14T00:00:37Z" level=info msg="Execing [/usr/bin/nsenter --mount=/proc/10918/ns/mnt -F -- /var/lib/docker/aufs/mnt/b59486dc50c4e23f2bd85e6562ed8d5ecbf184b667d261e3f3ff51e524ae7249/var/lib/rancher/convoy-agent/share-mnt --stage2 /var/lib/rancher/convoy/convoy-nfs-ver3-8960fd8c-3393-4c2b-806f-9f5909ce9254 -- /launch volume-agent-nfs-internal 10918]"
9/13/2016 5:00:37 PMRegistering convoy socket at /var/run/convoy-convoy-nfs-ver3.sock
9/13/2016 5:00:37 PMMounting at: /var/lib/rancher/convoy/convoy-nfs-ver3-8960fd8c-3393-4c2b-806f-9f5909ce9254/mnt
9/13/2016 5:00:37 PMMounting nfs. Command: mount -t nfs -o nfsvers=3 159.203.111.19:/var/nfs /var/lib/rancher/convoy/convoy-nfs-ver3-8960fd8c-3393-4c2b-806f-9f5909ce9254/mnt
9/13/2016 5:00:37 PMmount.nfs: rpc.statd is not running but is required for remote locking.
9/13/2016 5:00:37 PMmount.nfs: Either use '-o nolock' to keep locks local, or start statd.
9/13/2016 5:00:37 PMmount.nfs: mounting 159.203.111.19:/var/nfs failed, reason given by server: No such file or directory
```

**Comment by janeczku** [comment] 2016-09-14 01:07
@cjellick @yasker The upgrade of the image base to Ubuntu 16 broke NFSv3 again. https://github.com/rancher/convoy-agent/commit/ff52616e0b28b21eb8120badc5741104457dbaa4
NFSv3 is broken in Ubuntu 16.x: https://bugs.launchpad.net/ubuntu/+source/rpcbind/+bug/1558196

**Comment by cjellick** [comment] 2016-09-30 21:05
Can test against the PR: https://github.com/rancher/rancher-catalog/pull/201
Once verified, we can merge that PR

**Comment by sangeethah** [comment] 2016-09-30 22:25
@janeczku , can you provide a template that has the fix with which verification can be done?

**Comment by janeczku** [comment] 2016-10-02 18:43
@sangeethah The template is here: https://github.com/rancher/rancher-catalog/pull/201
I have added it to my catalog https://github.com/janeczku/my-rancher-catalog (convoy-nfs v0.5.0)

**Comment by sangeethah** [comment] 2016-10-03 23:18
Tested with rancher-server version - v1.2.0-pre3 and rancher/convoy-agent:v0.12.0 from https://github.com/janeczku/my-rancher-catalog.

Able to test using NFSv3 (by setting mount_opts: nfsvers=3) and NFSv4 on ubuntu 14.04.

**Comment by sangeethah** [comment] 2016-10-03 23:53
Able to deploy services using volume drivers in NFSv4 on ubuntu 14.02 which  has kernel older than 3.14.
root@sangee-nfs-old:/var/nfs/testmev42old# uname -a
Linux sangee-nfs-old 3.13.0-96-generic #143~precise1-Ubuntu SMP Tue Aug 30 14:38:06 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
root@sangee-nfs-old:/var/nfs/testmev42old#

**Closed by sangeethah** 2016-10-03 23:53 UTC
Labels: area/convoy, kind/bug, status/reopened, status/to-test
