### ISSUE TITLE
not work  Service External Links

### ISSUE THREAD

**Issue by andruwa13** [rancher/rancher#6841] opened 2016-11-30 18:22 UTC
![rancher 2016-11-30 20-20-20](https://cloud.githubusercontent.com/assets/5846351/20765368/af72ae28-b73a-11e6-9afe-e72bc09e408f.png)

![phpmyadmin 2016-11-30 20-21-00](https://cloud.githubusercontent.com/assets/5846351/20765377/b63c1f5a-b73a-11e6-85fa-b7a88ac435c6.png)

![phpmyadmin 2016-11-30 20-21-39](https://cloud.githubusercontent.com/assets/5846351/20765383/bc7632ac-b73a-11e6-833f-82778782123b.png)

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v1.2.0-pre4-rc15` Cattle: `v0.173.6` UI: `v1.2.31` |
|Access|`github` `admin`|
|Orchestration|`Cattle`|
|Route|`service.containers`|
---
Update
Rancher **v1.1.4 and v1.2.0-pre3** work Service External Links

**Comment by mccricardo** [comment] 2016-12-03 00:15
I'm experiencing the same issue with Rancher 1.2.0.

**Comment by andruwa13** [comment] 2016-12-16 19:02
not work 1.2.1

**Comment by mccricardo** [comment] 2016-12-16 19:34
Are your images alpine:3.4 based?

**Comment by andruwa13** [comment] 2016-12-22 08:58
not work v1.2.2-rc2

**Comment by andruwa13** [comment] 2016-12-22 08:59
mccricardo

> Are your images alpine:3.4 based?
all services

**Comment by janeczku** [comment] 2016-12-22 09:56
@andruwa13 Could you open a shell to the phpMyAdmin container and run `ping www.google.com`? Please paste the output here.

**Comment by mccricardo** [comment] 2016-12-22 10:15
@andruwa13 we had the same issue. There are known issues with alpine 3.4. Try including:

```
dns_search:
  - rancher.internal
```

in your `docker-compose.yml`

**Comment by janeczku** [comment] 2016-12-22 17:18
I am closing this as a pre-duplicate of https://github.com/rancher/rancher/issues/7026 where the cause of this issue has been identified as relating to using Alpine base images.

**Closed by janeczku** 2016-12-22 17:18 UTC

**Comment by andruwa13** [comment] 2016-12-23 00:15
docker-compose.yml
`version: '2'
services:
  phpmyadmin:
    mem_limit: 268435456
    image: phpmyadmin/phpmyadmin:latest
    environment:
      PMA_ARBITRARY: '1'
    stdin_open: true
    external_links:
    - bankoved/db:db
    ports:
    - 4444:80/tcp
    memswap_limit: 536870912
    cpu_shares: 200
    labels:
      io.rancher.container.pull_image: always`

not work 

![phpmyadmin 2016-12-23 02-14-52](https://cloud.githubusercontent.com/assets/5846351/21444401/ab5034c8-c8b5-11e6-927b-859b5adafd52.png)

**Comment by andruwa13** [comment] 2017-01-01 20:54
@mccricardo thank you, work
