### ISSUE TITLE
high CPU usage across all hosts during create/upgrade due to metadata service + DNS

### ISSUE THREAD

**Issue by theRealWardo** [rancher/rancher#8505] opened 2017-04-13 22:36 UTC
**Rancher Versions:**
Server: 1.5.5
healthcheck: 0.2.3
ipsec: 0.0.7
network-services: 0.9.1 (metadata) and 0.6.6 (network manager)
scheduler: 0.7.5
kubernetes (if applicable): nopes

**Docker Version:**
17.03.0-ce

**OS and where are the hosts located? (cloud, bare metal, etc):**
Ubuntu 16.04.2 LTS (4.4.0) and a few Ubuntu 14.04.5 LTS (3.13.0) running on AWS

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
HA Rancher with RDS

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle

**Steps to Reproduce:**

1. Start a cluster with a good number of machines to make sure your metadata service has plenty of data. (the environment where I noted this today was running 48 hosts)
1. Launch a bunch of containers (maybe some Telegraf to shove CPU and network data into an InfluxDB so you can see stuff in Grafana later)
1. Launch some more containers... maybe upgrade some containers...

**Results:** 

High CPU usage is observed on **ALL** hosts in the cluster. Here is one host during an upgrade:

![screen shot 2017-04-13 at 3 29 12 pm](https://cloud.githubusercontent.com/assets/284347/25026939/2d511e56-205e-11e7-8ec0-8088e749c509.png)
![screen shot 2017-04-13 at 3 29 26 pm](https://cloud.githubusercontent.com/assets/284347/25026942/2f7b5598-205e-11e7-8445-9b9c861ec3ce.png)

DNS service sends a lot of data during this time as well:

![screen shot 2017-04-13 at 3 30 03 pm](https://cloud.githubusercontent.com/assets/284347/25026972/5e72cc3c-205e-11e7-883d-b1be6d780996.png)

Digging into logs for the metadata service I see a ton of quick reloading of answers
```
time="2017-04-13T22:00:12Z" level=info msg="Download and reload in: 152.962397ms"
time="2017-04-13T22:00:12Z" level=info msg="Update requested for version: 672275"
time="2017-04-13T22:00:12Z" level=info msg="Downloaded in 17.306846ms"
time="2017-04-13T22:00:12Z" level=info msg="Generating and reloading answers"
time="2017-04-13T22:00:12Z" level=info msg="Update requested for version: 672274"
time="2017-04-13T22:00:12Z" level=info msg="Generating answers"
time="2017-04-13T22:00:12Z" level=info msg="Generated and reloaded answers"
time="2017-04-13T22:00:12Z" level=info msg="Applied http://ha.rancher.mux/v1/configcontent/metadata-answers?client=v2&requestedVersion=672274?version=672276-14a7928f14789d3a00ab33efdfd9c22c"
time="2017-04-13T22:00:12Z" level=info msg="Download and reload in: 312.971699ms"
time="2017-04-13T22:00:12Z" level=info msg="Downloaded in 10.124486ms"
time="2017-04-13T22:00:12Z" level=info msg="Generating and reloading answers"
time="2017-04-13T22:00:12Z" level=info msg="Update requested for version: 672278"
time="2017-04-13T22:00:12Z" level=info msg="Generating answers"
time="2017-04-13T22:00:13Z" level=info msg="Generated and reloaded answers"
time="2017-04-13T22:00:13Z" level=info msg="Applied http://ha.rancher.mux/v1/configcontent/metadata-answers?client=v2&requestedVersion=672274?version=672275-14a7928f14789d3a00ab33efdfd9c22c"
time="2017-04-13T22:00:13Z" level=info msg="Download and reload in: 330.665421ms"
time="2017-04-13T22:00:13Z" level=info msg="Update requested for version: 672278"
time="2017-04-13T22:00:13Z" level=info msg="Downloaded in 42.239164ms"
time="2017-04-13T22:00:13Z" level=info msg="Generating and reloading answers"
time="2017-04-13T22:00:13Z" level=info msg="Update requested for version: 672277"
time="2017-04-13T22:00:13Z" level=info msg="Generating answers"
time="2017-04-13T22:00:13Z" level=info msg="Generated and reloaded answers"
time="2017-04-13T22:00:13Z" level=info msg="Applied http://ha.rancher.mux/v1/configcontent/metadata-answers?client=v2&requestedVersion=672278?version=672278-14a7928f14789d3a00ab33efdfd9c22c"
time="2017-04-13T22:00:13Z" level=info msg="Download and reload in: 298.367767ms"
time="2017-04-13T22:00:13Z" level=info msg="Downloaded in 19.420332ms"
time="2017-04-13T22:00:13Z" level=info msg="Generating and reloading answers"
time="2017-04-13T22:00:13Z" level=info msg="Generating answers"
time="2017-04-13T22:00:13Z" level=info msg="Generated and reloaded answers"
time="2017-04-13T22:00:13Z" level=info msg="Applied http://ha.rancher.mux/v1/configcontent/metadata-answers?client=v2&requestedVersion=672277?version=672278-14a7928f14789d3a00ab33efdfd9c22c"
time="2017-04-13T22:00:13Z" level=info msg="Download and reload in: 327.065607ms"
time="2017-04-13T22:00:14Z" level=info msg="Update requested for version: 672279"
time="2017-04-13T22:00:14Z" level=info msg="Downloaded in 50.613182ms"
time="2017-04-13T22:00:14Z" level=info msg="Generating and reloading answers"
time="2017-04-13T22:00:14Z" level=info msg="Generating answers"
time="2017-04-13T22:00:14Z" level=info msg="Generated and reloaded answers"
```

at the same time the DNS service is reloading aggressively as well
```
time="2017-04-13T22:00:12Z" level=info msg="Reloading answers"
time="2017-04-13T22:00:12Z" level=info msg="Reloaded answers"
time="2017-04-13T22:00:12Z" level=info msg="Reloading answers"
time="2017-04-13T22:00:12Z" level=info msg="Reloaded answers"
time="2017-04-13T22:00:12Z" level=info msg="Reloading answers"
time="2017-04-13T22:00:12Z" level=info msg="Reloaded answers"
time="2017-04-13T22:00:13Z" level=info msg="Reloading answers"
time="2017-04-13T22:00:13Z" level=info msg="Reloaded answers"
time="2017-04-13T22:00:13Z" level=info msg="Reloading answers"
time="2017-04-13T22:00:13Z" level=info msg="Reloaded answers"
time="2017-04-13T22:00:14Z" level=info msg="Reloading answers"
time="2017-04-13T22:00:14Z" level=info msg="Reloaded answers"
time="2017-04-13T22:00:14Z" level=info msg="Reloading answers"
time="2017-04-13T22:00:14Z" level=info msg="Reloaded answers"
time="2017-04-13T22:00:15Z" level=info msg="Reloading answers"
time="2017-04-13T22:00:15Z" level=info msg="Reloaded answers"
time="2017-04-13T22:00:15Z" level=info msg="Reloading answers"
time="2017-04-13T22:00:15Z" level=info msg="Reloaded answers"
```

**Comment by nhumrich** [comment] 2017-04-20 18:23
Looks like this might be related to the docker version. I also had this problem, but once I downgraded docker to 1.12.6 the problem went away.

**Comment by ket4yii** [comment] 2017-06-09 13:04
I've got the same issue. CPU usage is really high for this little microservice.

**Comment by tuwid** [comment] 2017-07-17 13:38
Having the same issue on 1.6.2 / Ubuntu 16.10

**Comment by veered** [comment] 2017-07-18 20:21
We are having similar issues on Rancher 1.6.2 (3k containers, 9 hosts)

**Comment by tuwid** [comment] 2017-07-21 06:20
@theRealWardo after updating to 1.6.4 the issue disappeared for me (till now) but we're still monitoring. @veered with 3k containers this becomes an architectural issue though so not sure if it will solve it for you

**Comment by denizin** [comment] 2017-07-31 20:33
We are seeing this issue with 1.6.5.  Anytime containers are added/upgraded we see a large spike in all our cluster hosts.  

6 hosts (docker 17.03-ce) running about 115 containers per host.  We have a lot of load balancers running in front of our applications in our stacks....maybe about 80 out of the 155 are load balancers and the load on those go up every time we see this issue.

Is there some way to get a better understanding of how the rancher load balancers and the metadata service interact?  We're trying to determine if our architecture setup is the culprit.  

Thank you.

**Comment by ehlavaty** [comment] 2017-08-04 15:54
Same issue, here. I tried:

Rancher v1.6.6, Docker 1.12.6
Rancher v1.6.6, Docker 1.13.1
Rancher v1.6.5, Docker 1.13.1 
Rancher v1.6.5, Docker 17.06.x-ce

I planned to upgrade our test environments from Rancher 1.1.4, Docker 1.13.1 because of https://github.com/rancher/rancher/issues/4691. 

We use AWS t2.medium instances (about 30 containers, per) there and everything has been working fine for quite a while. No CPU spikes during deploys or anything like that.

In all of the above 1.6.x scenarios, the same t2.mediums have major CPU and load avg spikes during deploy when the metadata and dns update stuff kicks-off. Sometimes, even to the point of the instance going into a 'Disconnected' state. I've seen 1 min load average reach as high as 15-ish, which never happened before with 1.1.4 (we might maybe hit 2 once in blue-moon).

If i want to upgrade our 3 test environments, I'm looking at doubling my AWS costs on larger instances, just to get over the deployment hump. That's not so great.

**Comment by ehlavaty** [comment] 2017-08-04 20:36
Not sure if this will be helpful, or not but I ran an strace -C on the rancher-metadata -subscribe PID during a stack deploy with about 30 containers.

On Ubuntu 16.04.3 LTS, Docker 1.12.6, Rancher 1.6.6, rancher/metadata:v0.9.3

```
% time     seconds  usecs/call     calls    errors syscall
------ ----------- ----------- --------- --------- ----------------
 90.52    0.638151         722       884        99 futex
  7.67    0.054092         183       296           epoll_wait
  1.13    0.008000          95        84           sched_yield
  0.57    0.004000          11       374       139 read
  0.06    0.000402           2       218           write
  0.05    0.000372           0      4201           clock_gettime
  0.00    0.000000           0         6           close
  0.00    0.000000           0        38           select
  0.00    0.000000           0         3           getsockname
  0.00    0.000000           0        12           setsockopt
  0.00    0.000000           0         9           epoll_ctl
  0.00    0.000000           0         7         3 accept4
------ ----------- ----------- --------- --------- ----------------
100.00    0.705017                  6132       241 total
```

**Comment by aemneina** [comment] 2017-09-27 16:05
This is related to : [#9373](https://github.com/rancher/rancher/issues/9373)
The workaround is to set the cpu shares for the metadata service. The side effect is that deployment time decreases as metadata is in the processing path.

**Comment by Rucknar** [comment] 2017-10-12 06:19
I've tested with the CPU shares set to 100, instead of the default of 1024. Has anyone else had any success with this? I still saw the CPU service burning through CPU to the same profile...

**Comment by GiGurra** [comment] 2017-10-27 05:41
Im having the same issue. All cpu cores are fully consumed for 5-10 seconds.
5 hosts and maybe 300 containers total.
Rancher version 1.6.7
Docker version 17.03.1-ce
Ubuntu 16.04.2 lts

**Comment by aemneina** [comment] 2017-10-27 17:31
There are a couple fixes in progress, one is to throttle metadata requests, another is to impose CPU quotas. The fix should ship with 1.6.11. I'll close this out. Feel free to comment if you think I'm missing something here, and I can reopen.

Similar issue to https://github.com/rancher/rancher/issues/9957

**Closed** 2017-10-27 17:31 UTC
Labels: area/metadata, area/networking

**Comment by mspanc** [comment] 2017-12-06 21:15
Hello I am experiencing the same after upgrading to 1.6.12.

**Comment by adenot** [comment] 2018-01-15 03:20
I'm also experiencing this with rancher 1.6.13, docker 17.06.2-ce

**Comment by veered** [comment] 2018-03-12 17:26
@aemneina I think that this issue ought to be re-opened or tracked in a new issue

**Comment by adenot** [comment] 2018-03-13 00:20
Related: #10860

**Comment by marvinwankersteen** [comment] 2018-04-12 12:06
We had similiar issue, but we had everytime high cpu usage on rancher-dns and rancher-metadata.
The cause was, that the healthcheck on one container had flapped between "active" and "unhealthy". After every state-change of the container/service, the metadata and/or dns gets updated.

The solution for us was to edit the healthcheck-timeouts. The container/service now stays active and the cpu load on rancher-dns and rancher-metadata is gone.
