### ISSUE TITLE
Helm upgrade fails with the error related to the secret "bootstrap-secret"

### ISSUE THREAD

**Issue by jiaqiluo** [rancher/rancher#37003] opened 2022-03-22 23:45 UTC
**Rancher Server Setup**
- Rancher version: 2.6.3
- Installation option (Docker install/Helm Chart): helm 
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): rke1 v1.21.7
- Proxy/Cert Details:

**Information about the Cluster**
- Kubernetes version:
- Cluster Type (Local/Downstream):
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider):

**User Information**
- What is the role of the user logged in? (Admin/Cluster Owner/Cluster Member/Project Owner/Project Member/Custom)
  - If custom, define the set of permissions: Admin

   
**Describe the bug**

upgrading Rancher from `2.6.3` to `2.6.4-rc11` by using `Helm upgrade`  command fails 

**To Reproduce**
 
- use helm to install rancher 2.6.3 
- log in Rancher UI, set password and URL by following instructions 
- (optional) create a downstream cluster and wait it to be active 
- use helm to upgrade rancher to 2.6.4-rc11:
```
helm upgrade rancher rancher-latest/rancher \
  --namespace cattle-system \
  --set hostname=xxxxx \
  --version v2.6.4-rc11
```

**Result**
`Error: UPGRADE FAILED: rendered manifests contain a resource that already exists. Unable to continue with update: Secret "bootstrap-secret" in namespace "cattle-system" exists and cannot be imported into the current release: invalid ownership metadata; label validation error: missing key "app.kubernetes.io/managed-by": must be set to "Helm"; annotation validation error: missing key "meta.helm.sh/release-name": must be set to "rancher"; annotation validation error: missing key "meta.helm.sh/release-namespace": must be set to "cattle-system"`
**Expected Result**

the upgrade should succeed 
 
**Workaround:**
delete the secret first, then run the helm upgrade again 
` kubectl delete secret -n cattle-system bootstrap-secret`

**Comment by paynejacob** [comment] 2022-03-28 18:41
closing duplicate of https://github.com/rancher/rancher/issues/37060

**Closed by paynejacob** 2022-03-28 18:41 UTC
Labels: priority/1, [zube]: To Triage, release-note, area/upgrade, feature/rancher-server-helm-chart, team/area1

**Comment by jtravee** [comment] 2022-04-26 21:43
No need to release note in 2.6.5 as it's a duplicate of #37060, which was already noted in 2.6.4.
