### ISSUE TITLE
centos7 build a swarm environment error

### ISSUE THREAD

**Issue by 1026524749** [rancher/rancher#9421] opened 2017-07-21 01:06 UTC
rancher 1.6.3 server + centos7.3

three visual machine of centos 7.3 ,these machine all copy by  a machine what is only install docker 1.17.3.

now ,i build a swarm envirment and user default swarm template .when i add first host ,it is normal。i try to add second host，the swarmkit container of first host is  abnormal。views the logs ，ishow the following info.

`2017/7/21 上午9:18:31time="2017-07-21T01:18:31Z" level=info msg="Listening on port: 2378"
2017/7/21 上午9:18:32jq: error (at <stdin>:1): Cannot index string with string "Description"
2017/7/21 上午9:18:32jq: error (at <stdin>:1): Cannot index string with string "Spec"
2017/7/21 上午9:18:32jq: error (at <stdin>:1): Cannot index string with string "Spec"
2017/7/21 上午9:18:32jq: error (at <stdin>:1): Cannot index string with string "Spec"
2017/7/21 上午9:18:32/opt/rancher/run.sh: line 245: + : syntax error: operand expected (error token is "+ ")`

i add the three host  ，the swarmkit of it also is abnormal 
host 1 and host 2 label is swarm = manager 
host 3 label is swarm = wait_leader

udp 500 4500 tcp 2377 2378 2379 is open 
---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v1.6.3` Cattle: `v0.181.13` UI: `v1.6.9` |
|Access|`localauth` `admin`|
|Orchestration|`Swarm`|
|Route|`hosts.index`|

**Comment by superseb** [comment] 2017-07-21 07:21
Closing as duplicate of https://github.com/rancher/rancher/issues/8183

**Closed by superseb** 2017-07-21 07:21 UTC
Labels: area/swarm, kind/question
