### ISSUE TITLE
Get error when editing project template

### ISSUE THREAD

**Issue by orangedeng** [rancher/rancher#10510] opened 2017-12-11 13:35 UTC
**Rancher versions:**
rancher/server: 1.16.13-rc1
rancher/agent: N/A

**Infrastructure Stack versions:**
healthcheck:
ipsec:
network-services:
scheduler:
kubernetes (if applicable):

**Docker version: (`docker version`,`docker info` preferred)**

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**

**Steps to Reproduce:**
1. Get in to Manage Environments page.
2. Click Add template
3. Click Windows template

**Results:**
```
The currently enabled stack "Rancher IPsec" does not support Windows (Experimental) Orchestration.
```
**Workaround: Disable IPsec network first and switch to windows template again.**

**Comment by loganhz** [comment] 2017-12-12 03:25
Hi @vincent99 , I have fixed an issue that user can not switch to windows orchestration as there is some required catalog items which can not be disabled.

But how do we deal with these kind of catalog items which can be disabled like `Rancher IPsec`? I think showing error message is the expected behavior in this case.

**Comment by vincent99** [comment] 2017-12-12 22:46
I'm not sure why IPsec is required in the first place when there's alternatives (vxlan).. but remove things that are "required" but not available?  Or at least make the disable button available in that situation?

**Comment by loganhz** [comment] 2017-12-13 00:10
IPsec is not required. User should disable IPSec first and switch to windows. This is by design. Is it correct? If so, I think we can close this issue.

**Comment by deniseschannon** [comment] 2017-12-15 21:57
@loganhz Is it possible to disable all networking options after clicking on the `Windows` orchestration type to avoid the error message?

If not, can we edit the error message to say "Disable all networking options before switching orchestrations?"

**Comment by deniseschannon** [comment] 2017-12-18 06:51
Available with v1.6.13-rc4

**Comment by deniseschannon** [comment] 2017-12-18 19:27
@loganhz When clicking on the other orchestration types after clicking on Windows, ipsec is no longer enabled. Is it possible to force it to be enabled when clicking back onto the other container orchestration types?

**Comment by kingsd041** [comment] 2017-12-20 03:35
Tested with Rancher/server:v1.6.13-rc5. 
Click on Windows template and there is no error message.

@deniseschannon  Can I close this issue?

**Comment by deniseschannon** [comment] 2017-12-20 06:01
@kingsd041 I tested by clicking on the Windows orchestration and toggling between that and the other orchestration types when creating a new template. Specifically, IPsec doesn't throw an error when selecting Windows and it is selected by default when selecting a non-Windows orchestration.

**Closed by deniseschannon** 2017-12-20 06:01 UTC
Labels: area/ui, area/windows, kind/enhancement, status/resolved, status/to-test, team/cn
