### ISSUE TITLE
[BUG][RKE2] Workload endpoint times out when setting public port

### ISSUE THREAD

**Issue by thaneunsoo** [rancher/rancher#38379] opened 2022-07-22 16:36 UTC
**Rancher Server Setup**
- Rancher version: 2.6.7-rc3
- Installation option (Docker install/Helm Chart):
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): RKE2
- Proxy/Cert Details:

**Information about the Cluster**
- Kubernetes version: 1.24.2
- Cluster Type (Local/Downstream):
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider):

**User Information**
- What is the role of the user logged in? (Admin/Cluster Owner/Cluster Member/Project Owner/Project Member/Custom)
  - If custom, define the set of permissions: Admin, Standard user that is cluster owner

**Describe the bug**

Workload endpoint with 9999(also tried handful of other port numbers) public port set is unable to connect and times out.
Workload comes up active but the endpoint keeps timing out. This was tested on 1.24.2 k8s version and on all cni providers for rke2. Sometimes this problem doesn't occur as I saw successful endpoints in some jenkins jobs, but most of the time I saw this issue.

**To Reproduce**

1. Create RKE2 cluster with 1.24.2 k8s version
2. Create workload with public port set to 9999 (or any port number)
3. Try to reach workload endpoint using link 
<img width="360" alt="image" src="https://user-images.githubusercontent.com/108360907/180484182-1d127b23-df2c-49bc-ad9a-81d7e0955bbd.png">

**Result**
Endpoint times out and is unable to load

**Expected Result**

Should be able to reach endpoint and then endpoint/name.html should return name of workload

**Comment by HarrisonWAffel** [comment] 2022-08-16 19:01
@timhaneunsoo How is this daemon set created and exposed? My first assumption is that it is just using a NodePort, but if that is the case then I cannot reproduce this on my test server (NodePorts can only be created in the range `30000-32768`). When I create a workload with a NodePort for a workload within that port range, I can reach the endpoint presented in the UI. 

You mention that `Sometimes this problem doesn't occur as I saw successful endpoints in some jenkins jobs, but most of the time I saw this issue.`, does this mean that the workload that you cannot access was created by Jenkins? Or did you create it in the UI? If a Jenkins job created the Workload/NodePort then I think that would explain why this reproduces for you but not when I attempt to do it via the UI. Using the reproduction information in the description, I am unable to reproduce this on 2.6.7RC-3 and 2.6.7RC-7, I will keep looking into this once I have a bit more information

**Comment by sowmyav27** [comment] 2022-08-16 19:20
Issue seen on on 2.6.6 also

**Comment by HarrisonWAffel** [comment] 2022-08-16 20:49
Thanks to the QA team for filling in the gaps on how this reproduces!

I can verify that this issue does readily reproduce on 2.6.7rc-3 when exposing a workload using a host-port. When testing on 2.6.7-rc3 I found that this issue does not occur for k8's 1.23.8, only for 1.24.2. I was unable to reproduce this issue on 2.6.7-rc7, as well as 2.6.7-rc9, when using either k8's 1.23.8 or 1.24.2. The description states that this issue is intermittent, so I'm going to spend a bit more time seeing if I _can_ reproduce it on the latest RC, as well as see if I can find any evidence of this being indirectly fixed.

**Comment by HarrisonWAffel** [comment] 2022-08-25 16:36
I still can't get this issue to reproduce on v2.6.7, so I'm going to close this issue out. Feel free to re-open it if it does reproduce in the future.

**Closed by HarrisonWAffel** 2022-08-25 16:36 UTC
Labels: kind/bug-qa, [zube]: Working, QA/XS, team/area2, v2.7.0
