### ISSUE TITLE
[BUG] Rancher pods crashing after upgrading from 2.8.5 to 2.9.0

### ISSUE THREAD

**Issue by cola4u** [rancher/rancher#46453] opened 2024-08-01 23:07 UTC
**Rancher Server Setup**
- Rancher version: 2.9.0
- Installation option (Docker install/Helm Chart): Helm chart
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): GKE cluster, 1.29.6-gke.1254000
- Proxy/Cert Details:

**Information about the Cluster**
- Kubernetes version: 1.29.6-gke.1254000
- Cluster Type (Local/Downstream): local

**User Information**
- What is the role of the user logged in? Admin

**Describe the bug**
I upgraded our Rancher install last night from 2.8.5 to 2.9.0.  The upgrade seemed to go through ok, I was able to use the system after the upgrade.  Today, when I went to check on one of our clusters, our instance was completely down.  I can see the rancher pods are in a CrashLoopBackoff.  I've tried redeploying the rancher deployment, and it ends up the same way.  I get the following in the logs of all the pods I've checked:
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x26586b5]

goroutine 4860 [running]:
github.com/rancher/steve/pkg/schema/definitions.listGVKModels({0x906faf0, 0xc006416a48}, 0xc00685e400, {0x78c6e88db108, 0xc000f38dd0})
	/go/pkg/mod/github.com/rancher/steve@v0.0.0-20240709130809-47871606146c/pkg/schema/definitions/handler.go:226 +0x5b5
github.com/rancher/steve/pkg/schema/definitions.(*SchemaDefinitionHandler).Refresh(0xc001dffbc0)
	/go/pkg/mod/github.com/rancher/steve@v0.0.0-20240709130809-47871606146c/pkg/schema/definitions/handler.go:107 +0x17a
github.com/rancher/steve/pkg/debounce.(*DebounceableRefresher).RefreshAfter.func1()
	/go/pkg/mod/github.com/rancher/steve@v0.0.0-20240709130809-47871606146c/pkg/debounce/refresher.go:49 +0x106
created by github.com/rancher/steve/pkg/debounce.(*DebounceableRefresher).RefreshAfter in goroutine 4394
	/go/pkg/mod/github.com/rancher/steve@v0.0.0-20240709130809-47871606146c/pkg/debounce/refresher.go:38 +0x13b
```

```
➜  ~ k get pods
NAME                                   READY   STATUS             RESTARTS         AGE
gke-config-operator-7bd679974b-gdc9t   1/1     Running            0                7d22h
rancher-548c8b9ffd-7xg8c               0/1     CrashLoopBackOff   18 (108s ago)    76m
rancher-548c8b9ffd-db4nh               0/1     CrashLoopBackOff   19 (3m32s ago)   80m
rancher-548c8b9ffd-vqv8x               0/1     CrashLoopBackOff   20 (4m ago)      80m
rancher-6c9fddc694-rclgn               0/1     CrashLoopBackOff   19 (85s ago)     82m
rancher-webhook-6d699c9d8b-l2csr       1/1     Running            0                7d22h
```

**To Reproduce**

I don't know if I can

**Result**

**Expected Result**

I expected rancher to be up and running

**Screenshots**

**Additional context**

**Comment by cola4u** [comment] 2024-08-01 23:40
I've been paying closer attention to the logs from the failed pods, and it seems these log entries occur right before the crash:
```
2024/08/01 23:35:47 [INFO] Listening on :444
2024/08/01 23:35:48 [INFO] Starting /v1, Kind=Secret controller
2024/08/01 23:35:48 [INFO] Updating TLS secret for cattle-system/tls-rancher-internal (count: 19):
```

**Comment by brandond** [comment] 2024-08-01 23:41
Appears to be a duplicate of https://github.com/rancher/rancher/issues/46453 - would you mind trying some of the suggestions in there regarding CRD modifications? I'm going to close this as a dupe.

**Closed by brandond** 2024-08-01 23:41 UTC
Labels: kind/bug
