### ISSUE TITLE
Not able to add volume claim.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#12281] opened 2018-03-26 18:49 UTC
Rancher server version - Latest from master

Steps to reproduce the problem:
Create a Persistent Volume for NFS volume plugin.

Try to create a volume claim for this PV.

User is presented with this error message:

"Validation failed in API: PersistentVolumeClaim "mynfsvol1" is invalid: spec.resources[storage]: Required value"

<img width="1353" alt="screen shot 2018-03-26 at 11 45 18 am" src="https://user-images.githubusercontent.com/4266958/37926071-349e0cf2-30eb-11e8-9910-2da6d6841725.png">

```
{type: "persistentVolumeClaim", accessModes: ["ReadWriteOnce"], name: "mynfsvol1", volumeId: "mynfs1",…}
accessModes:["ReadWriteOnce"]
0:"ReadWriteOnce"
name:"mynfsvol1"
namespaceId:"default"
resources:{}
storageClassId:null
type:"persistentVolumeClaim"
volumeId:"mynfs1"
```

```
{"actionLinks":{},"baseType":"error","code":"Invalid","links":{},"message":"PersistentVolumeClaim \"mynfsvol1\" is invalid: spec.resources[storage]: Required value","status":422,"type":"error"}
```

**Comment by sangeethah** [comment] 2018-03-27 00:09
When resources field is set , able to get the volume claims created successfully.
```
    storage_capacity = {"storage": "1Gi"}
    request = {"requests": storage_capacity}
    p_client.create_persistentVolumeClaim(name="mytest1",
                                          namespaceId="default",
                                          projectId="project-97c2g",
                                          resources=request,
                                          volumeId="persistentvolume-ksblc",
                                          accessModes=["ReadWriteMany"])
```

**Comment by Toflar** [comment] 2018-04-26 10:29
I still have the same issue. It works for `Single Node Read-Write` but not for `Multi Node Read-Write`.

**Comment by tfiduccia** [comment] 2018-04-26 17:35
@Toflar - what version of rancher do you have?

**Comment by Toflar** [comment] 2018-04-27 10:02
`v2.0.0-beta4`

**Comment by loganhz** [comment] 2018-08-22 13:28
I can not recreate this issue. It should be fixed already.

**Comment by tfiduccia** [comment] 2018-08-27 18:54
@Toflar -  can you still reproduce this issue?  I cannot reproduce.

**Comment by Toflar** [comment] 2018-08-27 19:04
haven‘t used it anymore and won‘t in the near future so you may close it if you like :) thanks for asking!

**Closed** 2018-08-27 19:10 UTC
Labels: area/storage, area/ui, status/reopened, status/resolved, status/to-test, version/2.0
