### ISSUE TITLE
Error in Access Control with AD Integration

### ISSUE THREAD

**Issue by CarTerr** [rancher/rancher#10520] opened 2017-12-12 06:57 UTC
**Rancher versions:**
rancher/server: v1.6.12
rancher/agent: v1.2.7

**Infrastructure Stack versions:**
healthcheck: v0.3.1
ipsec:
network-services:
network-manager:v0.7.7
scheduler:
kubernetes (if applicable):

**Docker version: (`docker version`,`docker info` preferred)**
$ docker version
Client:
 Version:      17.09.0-ce
 API version:  1.32
 Go version:   go1.8.3
 Git commit:   afdb6d4
 Built:        Tue Sep 26 22:42:18 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.09.0-ce
 API version:  1.32 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   afdb6d4
 Built:        Tue Sep 26 22:40:56 2017
 OS/Arch:      linux/amd64
 Experimental: false

$ docker info
Containers: 2
 Running: 2
 Paused: 0
 Stopped: 0
Images: 38
Server Version: 17.09.0-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 06b9cb35161009dcb7123345749fef02f7cea8e0
runc version: 3f2f8b84a77f73d38244dd690525642a72156c64
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.4.0-101-generic
Operating System: Ubuntu 16.04.3 LTS
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 2.938GiB
Name: ub
ID: NN4Y:PPBP:X4D4:4ED5:D6YQ:PLGT:DXTI:QLUC:HF4U:QGSJ:MF42:54ZS
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
$ cat /etc/os-release
NAME="Ubuntu"
VERSION="16.04.3 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.3 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial

$uname -r
4.4.0-101-generic

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
VmWare 6.5
**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
single node rancher

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle
**Steps to Reproduce:**
Clear instalation rancher v1.6.12 in docker. In web interface Admin--Access Control.
Choose Active Directory and fill the following parameters
Hostname or IP Address -- 192.168.0.1
Port -- 389 (no TLS)
Default login Domain -- CONNECT
Service Account Username -- syncldap
Service Account Password -- password
User Search Base -- dc=connect,dc=local
But in rancher v1.6.7 it's work fine.
**Results:**
in browser is: 400 Bad Request: invalid header value
in debug log is:
ERROR [:] [] [] [] [ecutorService-7] [.a.a.i.e.ExternalServiceAuthProvider] getIdentity: Got error from Auth service. statusCode: 400

**Comment by superseb** [comment] 2017-12-12 08:37
Can you configure debug logging and add it here? You can do it via the API (`http://<rancher_ip>/v2-beta/settings/auth.service.log.level` to `DEBUG`) or via the DB (`insert into setting (name,value) values ('auth.service.log.level', 'DEBUG');`).

**Comment by CarTerr** [comment] 2017-12-12 11:11
http://192.168.0.122:8080/v2-beta/settings/auth.service.log.level
```
{
"id": "auth.service.log.level",
"type": "activeSetting",
"links": {
"self": "…/v2-beta/settings/auth.service.log.level"
},
"actions": { },
"baseType": "setting",
"name": "auth.service.log.level",
"activeValue": "DEBUG",
"inDb": true,
"source": "Database",
"value": "DEBUG"
}
```
In log nothing
`2017-12-12 11:08:13,748 INFO  [:] [] [] [] [ecutorService-4] [.c.p.a.e.i.ArchaiusEventListenerImpl] Refreshing settings`

there are no debug information

**Comment by superseb** [comment] 2017-12-12 11:38
* Start `rancher/server`
* Configure `auth.service.log.level` as `DEBUG`
* `docker logs <rancher_server_container` should show `time="xx" level=info msg="No Auth provider configured"`
* Configure AD auth
* Send complete log to me on Rancher Users Slack (https://slack.rancher.io) or attach it to this issue.

**Comment by CarTerr** [comment] 2017-12-20 04:50
At this moment the problem is stay.
Tell me how to change the authorization from AD to LOCAL AUTHENTICATION?

**Comment by superseb** [comment] 2017-12-29 09:54
People hitting this, can you verify if this is the same as https://github.com/rancher/rancher/issues/10690? I.e. moving to upper level works?

**Comment by CarTerr** [comment] 2017-12-29 10:25
Yes, it's same issue. Possible problem in the language, because I have CN in Cyrilic

**Comment by superseb** [comment] 2018-01-30 10:39
OK closing this as duplicate of https://github.com/rancher/rancher/issues/10690

**Closed by superseb** 2018-01-30 10:39 UTC
Labels: area/access-control, status/more-info, version/1.6
