### ISSUE TITLE
Monitoring fails to deploy with persistent storage

### ISSUE THREAD

**Issue by OBenned** [rancher/rancher#25795] opened 2020-03-05 11:04 UTC
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
Enable monitoring with persistent storage

**Result:**
prometheus-cluster-monitoring-0 fails to deploy with the error: Error while running "VolumeBinding" filter plugin for pod "prometheus-cluster-monitoring-0": could not find v1.PersistentVolume "pvc-5c905e4b-86ab-11e9-84af-005056a0ed7e"

**Other details that may be helpful:**
Tried different storage solutions: gluster longhorn

**Environment information**
- Rancher version 2.3.4
- Installation option (single install/HA): HA

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): Rancher launched cluster
- Machine type (cloud/VM/metal) and specifications (CPU/memory): VMWare
- Kubernetes version (use `kubectl version`): 1.17.0

- Docker version (use `docker version`): 19.3.5

**Comment by Tejeev** [comment] 2020-06-11 11:12
I believe this is a duplicate of https://github.com/rancher/rancher/issues/17256

**Comment by maggieliu** [comment] 2020-06-12 16:48
@jiaqiluo Can we verify if Monitoring 0.1.1 fixed this issue or not?

**Comment by jiaqiluo** [comment] 2020-06-12 18:26
The bug is fixed in the latest chart `v0.1.1`
see this issue for more info: https://github.com/rancher/rancher/issues/26969
and this comment for the validation steps: https://github.com/rancher/rancher/issues/17256#issuecomment-643371125

**Closed by jiaqiluo** 2020-06-12 18:26 UTC
Labels: [zube]: To Test
