### ISSUE TITLE
Search Line limits exceeded.

### ISSUE THREAD

**Issue by mickengland** [rancher/rancher#10423] opened 2017-11-28 19:14 UTC
*Describe your issue here*
When adding a pod I get the following error:

Search Line limits were exceeded, some dns names have been omitted, the applied search line is: jenkins.svc.cluster.local svc.cluster.local cluster.local kubelet.kubernetes.rancher.internal kubernetes.rancher.internal rancher.internal
Back-off restarting failed container
Error syncing pod

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v1.6.11` Cattle: `v0.183.30` UI: `v1.6.30` |
|Access|`github` `admin`|
|Orchestration|`Kubernetes`|
|Route|`storagepools.pools`|

**Comment by superseb** [comment] 2017-11-29 08:34
What version of Kubernetes is running? This is a warning, and should not block proper functioning of the components. We fixed this warning in v1.6.11 and Kubernetes v1.8.3-rancher1 (https://github.com/rancher/rancher/issues/9303). Closing as not a bug, if you still see this in the latest Kubernetes version, please report back with the steps you've taken to get into this state.

**Closed by superseb** 2017-11-29 08:34 UTC

**Comment by mickengland** [comment] 2017-11-30 02:21
So I was not able to upgrade to the latest kubernetes as I kept getting a conflicts message but there was no indication what was causing this. I deleted my environment to try to create a new kubernetes cluster after having upgraded rancher to the latest version but I am now running into other issues with the healthcheck service not start which I have submitted another issue for.
