### ISSUE TITLE
Couldn't bring up network: couldn't find any CNI network configurations

### ISSUE THREAD

**Issue by dotnet123** [rancher/rancher#10114] opened 2017-10-13 06:59 UTC
**Rancher versions:v2.0.0-alpha10
**
I had this issue, Please help !
![7](https://user-images.githubusercontent.com/21954452/31533861-ead0f840-b026-11e7-9749-4c4a7e81abe6.png)

**Results:**

**Comment by superseb** [comment] 2017-10-13 08:22
Closing as duplicate of https://github.com/rancher/rancher/issues/10033

**Closed by superseb** 2017-10-13 08:22 UTC
