### ISSUE TITLE
Hosts tab displays duplicate host instances with conflicting rancher agent on each.

### ISSUE THREAD

**Issue by jalleyne** [rancher/rancher#3203] opened 2016-01-08 07:41 UTC
I have a boot2docker image locally and added it as a host to my local rancher instance. Now the hosts tab shows multiple/ duplicate instances of that host each with a rancher agent that seems to conflict. Only the first host rancher agent correctly starts with the other saying the port is already in use (presumably by the other agent, since if i stop the agent that started the next one successfully connect). Presumably this isn't intended, any ideas on what might be going on?

I was going to paste the logs here, but for some reason the agent container no longer shows any output.

<img width="1438" alt="screen shot 2016-01-08 at 2 42 30 am" src="https://cloud.githubusercontent.com/assets/163205/12192990/052851a0-b5b2-11e5-9363-c5271daf5bf8.png">

**Comment by deniseschannon** [comment] 2016-01-11 21:40
This is a duplicate of https://github.com/rancher/rancher/issues/936

If you scroll through the comments, you can see why it occurs. Essentially, Rancher saves some state like the host's UUID in /var/lib/rancher/ on the host. But that part of boot2docker's disk is ephemeral by default, so when you reboot it's gone, gets a new UUID when the agent starts up, and is a "different" host.

**Closed by deniseschannon** 2016-01-11 21:40 UTC

**Comment by jalleyne** [comment] 2016-01-11 21:53
logical, thank you for the explanation.
