### ISSUE TITLE
[BUG] - Provisioning allows clusters to include names with dot "." when all is lowercase this breaks fleet agent

### ISSUE THREAD

**Issue by izaac** [rancher/rancher#39248] opened 2022-10-06 16:53 UTC
**Rancher Server Setup**
- Rancher version: `v2.6.9-rc3`
- Installation option: Helm Chart
   - If Helm Chart, Kubernetes Cluster and version: `RKE1 HA` 
- Proxy/Cert Details: valid certificates

**Information about the Cluster**
- Kubernetes version: `N/A`
- Cluster Type: Cluster provisioning v2 and imported clusters

**User Information**
- What is the role of the user logged in? This was done as Admin but applies to users with provisioning rights.

**Describe the bug**

When provisioning clusters the UI permits the use of dots and dashes This makes fleet not to deploy in the provisioned downstream cluster

**To Reproduce**

- Go to provisioning to any cluster type and create the cluster with  dot in the name all lowercase
- The clusters will be provisioned successfully

**Result**

- The provisioned cluster doesn't have the fleet agent and fleet components deployed.

**Additional Information** 

Related issue: https://github.com/rancher/fleet/issues/739
Analysis:

> If I use the name Test.1 I get the following error: Cluster.provisioning.cattle.io "Test.1" is invalid: metadata.name: Invalid value: "Test.1": a lowercase RFC 1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is `'[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*'`) but this does not happen with test.1.

> The verification seems to happen in the Rancher [UI] because they explicitly allow dots, which Fleet does not [Pattern: "^[-a-z0-9]*$"](https://github.com/rancher/fleet/pull/918/files#diff-927d423e0c49728f25e29bb70ac2e0d993b9be8cebd4cfbaea474e18e34f3982R171) 
(SURE-5467)

**Comment by thardeck** [comment] 2022-10-07 08:33
Dashes "-" are accepted in Fleet following RFC 1123, as are lowercase characters and numbers. `^[-a-z0-9]*$`

**Comment by jameson-mcghee** [comment] 2022-10-31 22:19
I have confirmed that this issue does in fact reproduce on `v2.7.0-rc8`. The warning message is not generated, the cluster goes into `Active` state, and there are no _fleet_-related workload items at all in the clusters.

![image](https://user-images.githubusercontent.com/13294321/199120986-59492319-d5ad-405e-ad68-11267fe087bb.png)
![image](https://user-images.githubusercontent.com/13294321/199121003-c1e6cdd3-0145-4e35-b2d5-42d15b6393da.png)
![image](https://user-images.githubusercontent.com/13294321/199121015-2decc27f-b6e4-4257-9cc3-77cf89766988.png)

**Comment by HarrisonWAffel** [comment] 2023-01-03 19:30
The fix for this has been merged and can be tested once the webhook version is bumped, which will likely happen when other v1.25 webhook work is completed

**Comment by jameson-mcghee** [comment] 2023-01-03 22:19
This issue is still reproducing on `v2.7-head` (Commit ID: 7d16a0d). Therefore I am Reopening this ticket.
cc @HarrisonWAffel 

**`v2.7-head` (Commit ID: 7d16a0d):**
![image](https://user-images.githubusercontent.com/13294321/210450207-10aab921-2c4c-4a3a-8e42-dae93a20be2c.png)
![image](https://user-images.githubusercontent.com/13294321/210450217-f3d1bd92-07af-4dc5-ba91-e3ef6fb7766c.png)
![image](https://user-images.githubusercontent.com/13294321/210450224-84c7bbad-7d3d-4b42-85e3-1b88cde7e6f9.png)

**Rancher Logs:**
[rancher-566cd4485d-6h7cp_rancher.log](https://github.com/rancher/rancher/files/10340135/rancher-566cd4485d-6h7cp_rancher.log)

**Comment by HarrisonWAffel** [comment] 2023-01-03 22:22
@jameson-mcghee the webhook version has not yet been bumped so this fix will not yet be present, apologies if I've moved it into to-test early

**Comment by jameson-mcghee** [comment] 2023-01-03 22:22
@HarrisonWAffel, why are we not simply preventing the user from being able to use special characters for this field in the UI? Or possibly stripping them from the request in the API call? 
I may be oversimplifying it, but this _seems_ like a simple fix that `rancher/dashboard` should be able to handle?

**Comment by HarrisonWAffel** [comment] 2023-01-03 22:26
@jameson-mcghee There are multiple ways you could create the object, for example you can create it using `kubectl` with the invalid name format, circumventing both the UI and Rancher API. By adding it to the webhook we catch the issue regardless of how the resource is being created

**Comment by HarrisonWAffel** [comment] 2023-01-09 15:28
the webhook has been bumped and now includes this change

**Comment by jiaqiluo** [comment] 2023-01-10 20:06
This issue can be validated in the lastest v2.7-head.

**Comment by jameson-mcghee** [comment] 2023-01-11 16:53
During testing on `v2.7-head` (Commit ID: da810a7), I observed that I was prevented from being able to created clusters containing a "." (period) character. However, the message returned from the API call (and is provided in the UI) states "_admission webhook "rancher.cattle.io.clusters.provisioning.cattle.io" denied the request without explanation_", which is both not user-friendly and is not the message that is supposed to be presented (per input from @HarrisonWAffel). Therefore I am reopening this ticket until the proper message is provided in the UI.

**`v2.7-head` (Commit ID: da810a7):**
![image](https://user-images.githubusercontent.com/13294321/211867486-b8d0fa16-7738-45f8-acb5-7a46d08ac2de.png)
![image](https://user-images.githubusercontent.com/13294321/211867500-3e38e663-ddc2-409e-b5e3-a70e485ffd56.png)

**Comment by HarrisonWAffel** [comment] 2023-01-11 17:20
The root cause of this missing message is a failure to return the response object when handling denied requests. The webhook was recently refactored and changed how response objects are handled within Admission handlers. Previously, the response object was passed to the admission function as a pointer, allowing functions to modify it directly without having to explicitly return it.

We now have to explicitly return the response object in order for any details to be communicated with the user.

**Comment by HarrisonWAffel** [comment] 2023-01-11 23:01
A fix has been made to the Rancher webhook which should resolve the missing error message, and since the webhook dependency within Rancher has just been bumped I'm moving this issue back into to-test

**Comment by jiaqiluo** [comment] 2023-01-12 19:27
can be validated in the latest v2.7-head with webhook version v0.3.2-rc9

**Comment by jameson-mcghee** [comment] 2023-01-12 20:21
During testing on `v2.7-head` (Commit ID: e54432e) with _rancher-webhook_ `v0.3.2-rc9`, I was able to verify that a user is no longer able to provision a cluster with a "." period character in the name, and they are instead provisioned a warning message in the UI that explains what information is allowed as a valid Cluster Name. Based on this as well as all previous testing done for this ticket, I am closing this ticket as Done.

![image](https://user-images.githubusercontent.com/13294321/212172331-9e456545-a9a0-4785-ae41-b2c62f498b13.png)

**Closed by jameson-mcghee** 2023-01-12 20:21 UTC
Labels: kind/bug, priority/1, [zube]: QA Next up, QA/XS, release-note, area/provisioning-v2, team/area2

**Comment by kkaempf** [comment] 2023-02-09 09:49
SURE-5499
