### ISSUE TITLE
[UI] Compose YAML action doesn't preserve logging driver configuration

### ISSUE THREAD

**Issue by xaka** [rancher/rancher#3140] opened 2015-12-26 01:25 UTC
Following YAML parts are getting lost when you click `Compose YAML`:

```yaml
log_driver: gelf
log_opt:
  gelf-address: udp://logstash:12201
```

Not big deal until you blindly copy/paste generated YAML and end up with no logging at all :fearful:

**Comment by deniseschannon** [comment] 2015-12-26 17:01
Duplicate of #2388

**Closed by deniseschannon** 2015-12-26 17:01 UTC
