### ISSUE TITLE
No stacks on login

### ISSUE THREAD

**Issue by aldeed** [rancher/rancher#2874] opened 2015-12-02 15:15 UTC
In the latest (0.47) UI, when you first log in using GitHub, it says No Stacks. A page refresh shows the stacks correctly.

To reproduce, log out and then back in using GitHub auth.

**Comment by deniseschannon** [comment] 2015-12-02 16:39
Duplicate of https://github.com/rancher/rancher/issues/2861

**Closed by deniseschannon** 2015-12-02 16:39 UTC
