### ISSUE TITLE
Issues with tests marked Not Applicable for CIS scan

### ISSUE THREAD

**Issue by sowmyav27** [rancher/rancher#25857] opened 2020-03-07 01:22 UTC
**What kind of request is this (question/bug/enhancement/feature request):** bug

**Steps to reproduce (least amount of steps as possible):**
**Issue#1**

- Navigate to cluster --> Tools --> CIS scan page.
- Run a scan
- The scan reports Number of tests Passed/Failed/Skipped. The count of these three status tests do not equal the total number of tests. 
- The result is missing number of tests that are in Not Applicable status.

<img width="1325" alt="Screen Shot 2020-03-06 at 5 15 08 PM" src="https://user-images.githubusercontent.com/26032343/76133747-88b9c880-5fce-11ea-9059-b857b4a29499.png">

**Expected Result:** 
Column for "Not Applicable" number of tests be available on the UI.

**Issue#2**
- Navigate to cluster --> Tools --> CIS scan page.
- Run a scan
- Click on the scan
- The tests in Not Applicable status, have "Skip" action enabled on the UI
<img width="1282" alt="Screen Shot 2020-03-06 at 5 15 28 PM" src="https://user-images.githubusercontent.com/26032343/76133833-0a115b00-5fcf-11ea-98e5-244479ad7e5e.png">

**Expected Result:** 
"Skip" action should NOT be available on the UI for tests that are "Not Applicable".

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): master-head - ui Tag: latest2
- Installation option (single install/HA): single

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): rke custom
- Kubernetes version (use `kubectl version`):

```
1.17
```

**Comment by izaac** [comment] 2020-03-09 20:59
Rancher version: `2.4 master-head (03/09/2020)` commit id: 17bd84f8d

- Not Applicable results totals are also displayed in a column of the CIS Scans results page. ✅ 
- N/A results in the CIS Scan details page still have the Skip button/action active. :x:

**Comment by codyrancher** [comment] 2020-03-09 21:20
@izaac I believe the second issue is a dupe of https://zube.io/rancher/rancher-engineering/c/28341

**Comment by izaac** [comment] 2020-03-11 16:44
Rancher version: `2.4 master-head (03/10/2020)` commit id: 570461823

According to https://github.com/rancher/rancher/issues/25863#issuecomment-597374753

Skip buttons will get removed. Validated issue #1 in the issue description.

**Closed by izaac** 2020-03-11 16:44 UTC
Labels: [zube]: To Test, area/scan-tool, kind/bug-qa, team/ui
