### ISSUE TITLE
Agent keeps failing and host state stucks at "Reconnecting"

### ISSUE THREAD

**Issue by fernandoneto** [rancher/rancher#3908] opened 2016-03-10 14:19 UTC
## Rancher Version :

v0.59.1

## Docker Version:

 1.10.2

## OS:

 Ubuntu 14.04.4 LTS (3.13.0-79-generic)

## Steps to Reproduce: 

- Create a instance in AWS and launch rancher-server.
- Wait until UI is available, configure auth and then lets add a host.
- In add host menu select  "Other" and fill the fields according your configurations. We are using Azure driver.
- Add some container's or a stack from catalog.

## Results: 

After some time the host go to `Reconnecting` and we have to restart rancher-server container  to host go to `Active` again

## Expected:

Hosts recover from reconnecting state automatically.

## Related: 

#2196 

![captura de ecra de 2016-03-10 12 36 30](https://cloud.githubusercontent.com/assets/6515784/13671924/8cfaef9a-e6ca-11e5-894f-dad85eb4585c.png)

**Comment by deniseschannon** [comment] 2016-03-14 18:04
Unable to reproduce. I launched an Azure using the Azure driver (new in v0.63.0, it has it's own dedicated page) and added a service onto it. It launched the containers fine and did not go into reconnecting. I will keep it up for the next 24 hours and try to monitor. Once it goes into reconnecting, does it recover on its own?

**Comment by fernandoneto** [comment] 2016-03-15 12:44
@deniseschannon no, i have to restart the rancher-server.

**Comment by deniseschannon** [comment] 2016-03-15 17:13
I am unable to reproduce. I left my box up for 24 hours and had no issues where the host went into reconnecting. 

Why do you need to restart rancher-server? Couldn't you just re-add the agent?

**Comment by fernandoneto** [comment] 2016-03-15 19:33
@deniseschannon because our production environment has many hosts. Is easier to have a bash script that restart rancher server every 2 hours and prevent reconneting.

**Comment by fernandoneto** [comment] 2016-03-16 12:13
@deniseschannon at this moment im getting a reconneting host in my test environment. If you want i can provide you acess  to this environment. just send me a email to fernando.neto@junglecloud.com

**Comment by rtorino** [comment] 2016-05-11 22:45
I'm also experiencing the same issue. I think it started after we rebooted the rancher server host.

**Comment by deniseschannon** [comment] 2016-07-19 16:49
@fernandoneto @rtorino 

Are you still having these issues with Rancher v1.1.1?

**Comment by bacheson** [comment] 2016-08-16 14:56
Same exact thing here. It appears to afflict setups with many containers. The Hosts UI is bordering on unusable at this point with our setup. v1.1.2

![rancher-reconnecting-bug](https://cloud.githubusercontent.com/assets/9341738/17703546/188cb794-63a0-11e6-8784-b620bd3a024f.png)

**Comment by deniseschannon** [comment] 2016-08-17 18:38
@bacheson Would you mind opening a new issue for yours? I know the others were using Azure and it looks like you are using Packet. 

I'll close this one cause of the old version of Rancher as well.

**Closed by deniseschannon** 2016-08-17 18:38 UTC
Labels: kind/question
