### ISSUE TITLE
Using RANCHER_ENVIRONMENT fails when the account of the account key is added to multiple environments

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#9837] opened 2017-09-06 19:06 UTC
Rancher versions: v1.6.9-rc3
Rancher cli version: v0.6.4-rc4

Steps to reproduce the problem:
AD enabled setup.
User1 is "owner" of 1 environment - testuser2-Default  and "member" of another environment - Default.
Generate account api keys for this user.
set RANCHER_ENVIRONMENT variable to "testuser2-Default"

Not able to find this environment

```
Sangeethas-MBP:rancher-v0.6.4-rc4 sangeethahariharan1$ ./rancher env ls
ID        NAME                ORCHESTRATION   STATE     CREATED
1a5       Default             cattle          active    2017-09-06T18:05:38Z
1a14      testuser2-Default   cattle          active    2017-09-06T18:25:39Z
Sangeethas-MBP:rancher-v0.6.4-rc4 sangeethahariharan1$ ./rancher stack ls
FATA[0000] Not found: testuser2-Default                 
Sangeethas-MBP:rancher-v0.6.4-rc4 sangeethahariharan1$ 
```
But if I set the RANCHER_ENVIRONMENT variable to env id, it works.

Also if i remove User1 from being the member of "Default" environment , I am able to use rancher cli by setting RANCHER_ENVIRONMENT variable to "testuser2-Default"

**Comment by deniseschannon** [comment] 2017-09-06 20:57
@sangeethah Per the docs, we have always only supported environment ID as setting your environment variable. 

http://rancher.com/docs/rancher/v1.6/en/cli/#using-environment-variables

This would be an enhancement to set it using environment name as well.

**Comment by sangeethah** [comment] 2017-09-06 21:03
@deniseschannon , document states this - 
```# Set the environment to use, you can use either environment ID or environment name
$ export RANCHER_ENVIRONMENT=<environment_id>```

**Comment by deniseschannon** [comment] 2017-09-06 21:21
@sangeethah You are correct. I'm unable to reproduce your issue. I was able to use CLI using environment variables and setting the Rancher environment using ID or name. with the same kind of auth and membership levels on environments.

**Comment by superseb** [comment] 2017-11-06 15:24
1. Start `rancher/server:v1.6.10`
1. Enable AD access control using `user1`
1. Add `user2` to `Default` environment
1. Login as `user2`
1. Create API account key
1. Run `RANCHER_ENVIRONMENT=Default rancher ps`, works
1. Create new environment called `test`
1. Run `RANCHER_ENVIRONMENT=Default rancher ps`, fails
1. Run `RANCHER_ENVIRONMENT=test rancher ps`, fails

**Comment by superseb** [comment] 2017-11-07 09:26
Sounds like a duplicate of https://github.com/rancher/rancher/issues/9988

**Closed** 2017-11-07 09:34 UTC
Labels: area/cli, kind/bug, version/1.6
