### ISSUE TITLE
[scale down behavior] rke1 scale down for rke1 deletes the oldest node in the pool, while rke2 deletes the newest node in the pool

### ISSUE THREAD

**Issue by slickwarren** [rancher/rancher#35753] opened 2021-12-04 01:58 UTC
**Rancher Server Setup**
- Rancher version: v2.6.3-rc3
- Installation option (Docker install/Helm Chart): docker
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc):
- Proxy/Cert Details:n/a

**Information about the Cluster**
- Kubernetes version:1.21.7 / 1.22.3
- Cluster Type (Local/Downstream): downstream
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider): tested with harvester

**Describe the bug**

Scaling down a pool with rke1 will delete the oldest node in the pool. However scaling down an rke2 pool deletes the newest node in the pool 

**To Reproduce**
 
* deploy a downstream rke1 and rke2 cluster, each with multiple worker nodes in their own pool
* once active, scale up the worker pool for rke1. Then scale down. note that the older nodes are removed (those that were created first)
* do the same for rke2. note that the nodes recently created with scaling up were removed instead

**Expected Result**

I'm not sure how this will effect things in production, but it seems like this has the potential to cause issues

**Comment by snasovich** [comment] 2021-12-20 18:58
Need to confirm with PM whether we want to mirror RKE1 behavior or provider users with an option to set the deletion policy on node pools (see https://release-0-1.cluster-api.sigs.k8s.io/common_code/machineset_controller.html for some info). Moving to Need Info until it's clear.

**Comment by snasovich** [comment] 2022-01-14 22:47
Per discussion with @cloudnautique and @deniseschannon we want to mimic old behavior, so we want to default to "Oldest" DeletePolicy.

**Comment by jiaqiluo** [comment] 2022-01-18 18:41
from @thedadams 
```
This is the annotation from CAPI that needs to be added to the MachineDeployment (where Jake linked above) OldestMachineSetDeletePolicy
```
also, we will need to consider the migration path for this fix.

**Comment by thedadams** [comment] 2022-01-27 22:44
### Root cause
By default, CAPI deletes a random machine on scale down. This is not the same as RKE1, so this should be changed.

### What was fixed, or what changes have occurred
Now, Rancher will use the mechanism in CAPI to tell it to delete the oldest machine first on scale down.

### Areas or cases that should be tested
1. Provision an RKE2 cluster from Rancher with multiple nodes in the machine pools
2. Scale down a machine pool. Observe that the oldest machine is the one that is cleaned up.

### What areas could experience regressions?
N/A

### Are the repro steps accurate/minimal?
Yes.

**Comment by sowmyav27** [comment] 2022-02-02 00:39
**On 2.6-head commit id: `da382a8`**

- Provision an RKE2 cluster from Rancher with multiple nodes in the machine pools - AWS Node driver cluster - `v1.22.6+rke2r1` version
- Scale up worker nodes
- Wait for the nodes to come up Active.
- Scale down a worker machine pool. 
- The oldest machine is the one that is cleaned up. (first deployed one)

But it does not work in the following usecase

- Provision an RKE2 cluster from Rancher with multiple nodes in the machine pools - AWS Node driver cluster - `v1.22.6+rke2r1` version
- Scale up worker nodes
- When the nodes are provisioning, Scale down a worker machine pool. 
- The ones in Provisioning state are deleted. 

**Expected:**
The oldest (earliest one ) created should be deleted.

**Comment by thedadams** [comment] 2022-02-02 15:25
In regards to scaling machine pools, we use the CAPI framework to do it for us. We can tell the CAPI controllers which priority of deletion to use (oldest, newest, random). For example, we now tell CAPI that we would like to scale down using the oldest deletion priority.

The issue is that the logic in CAPI for these priorities is set by them. Therefore, when we tell CAPI to use the oldest deletion priority, this is the priority from highest to lowest (with the caveat that if the creation time of the machine is not set or is set into the future, then CAPI will ignore the machine):
1. If the machine is already deleting
2. If the machine has the `cluster.x-k8s.io/delete-machine` annotation
3. If the machine doesn't yet have a node reference
4. If the machine is in a failed state
6. Then machines are order, from oldest to newest, by when they were created.

The issue is that when a machine is provisioning, it falls into number (3). Therefore, it will get deleted with higher priority than any machine that is currently running (including the much older ones).

**Comment by sowmyav27** [comment] 2022-02-13 21:37
**On 2.6-head commit id: `11a7451`**

- Provision an RKE2 cluster from Rancher with multiple nodes in the machine pools - AWS Node driver cluster - `v1.21.9+rke2r1` version
- Scale up worker nodes
- Wait for the nodes to come up Active.
- Scale down a worker machine pool.
- The oldest machine is the one that is cleaned up. (first deployed one)
- Found another issue when testing this issue - https://github.com/rancher/rancher/issues/36502

Closing this issue

**Closed by sowmyav27** 2022-02-13 21:37 UTC
Labels: area/cluster, kind/bug-qa, [zube]: QA Next up, QA/XS, team/area2
