### ISSUE TITLE
rancher 2.6.5 dashboard "View logs" Buttons Not valid

### ISSUE THREAD

**Issue by 15120968809** [rancher/rancher#37819] opened 2022-05-25 09:08 UTC
![bb68fc7f53753415a88a4fc44452549](https://user-images.githubusercontent.com/42596598/170226140-7635aa2a-2e1e-43c2-86cc-d8ebffa036d8.png)

**Comment by rak-phillip** [comment] 2022-05-27 16:32
@15120968809 thanks for raising this issue and helping to make Rancher better 😁 

It looks like we have several reports for this, so I'm going to close this as a duplicate of #5984 to help us better track and test in a single place. Feel free to reopen this issue if you feel it shouldn't be closed. Otherwise, follow up in #5984 if there's more that needs to be added.

@gaktive

**Closed by rak-phillip** 2022-05-27 16:32 UTC
