### ISSUE TITLE
Catalog access re-enabling with github blocked results in a 503

### ISSUE THREAD

**Issue by chrisurwin** [rancher/rancher#5352] opened 2016-07-07 14:44 UTC
In an environment where github is blocked on the proxy, initially Rancher shows the cached catalog that comes in the rancher image. 

Disabling and re-enabling the catalogs results in a 503 error when it should just point back to the  cached catalog.

**Comment by mrajashree** [comment] 2016-10-06 21:10
Tried to reproduce this, instead of resulting in a 503 error, the latest version now displays a message saying `There are no compatible templates`. Once the catalogs are re-enabled and if github is not blocked, the latest catalog should be pulled from github, which it what it does currently, and hence pointing back to cached catalog on re-enabling won't work

**Comment by mrajashree** [comment] 2016-10-14 17:27
Unable to reproduce this issue with current rancher/server:master. This might have been fixed by recent changes in catalog service and cattle UI. I have referenced the catalog-service PRs

**Comment by mrajashree** [comment] 2016-10-18 23:06
Unable to reproduce this running the following command in an ubuntu VM: `docker run -d --restart=always -p 8080:8080 rancher/server:v1.2.0-pre4-rc3`. This delay seems to be there in `docker for Mac`, but is not related to the catalog-service code

**Comment by sangeethah** [comment] 2016-10-20 00:51
Tested with rancher server version - v1.2.0-pre4-rc4

In the rancher-server setup, I have blocked access to github by adding the following iptables rules:

```
iptables -I FORWARD -d <gihub ipaddress>-j DROP
```

Disable and Enable the catalog. 
Once the catalog is enabled , user is presented with error message "There are no compatible templates".
There is no " 503" error message presented to the user.
This message "There are no compatible templates" is  presented to the user for a very long time like 2 mts (seems like this is the time taken to wait for the gihub access to timeout) after which catalog gets presented to the user eventually.  

Every catalog takes additional 2 mts to be shown. When i have 3 catalogs to start with , the last of the catalog takes 6 mts to load since we are doing the catalog fetch sequentially.

This issue is tracked in https://github.com/rancher/rancher/issues/4903

**Comment by sangeethah** [comment] 2016-10-20 14:58
Reopening this issue to track the above seen behavior which is one of the issues tracked in #4903

**Comment by sangeethah** [comment] 2016-10-25 18:19
Tested with rancher-server version -- v1.2.0-pre4-rc5

In the rancher-server setup, I have blocked access to git.rancher.io by adding the following iptables rules:

```
iptables -I FORWARD -d <git.rancher.io>-j DROP
iptables -I FORWARD -s <git.rancher.io>-j DROP

```
Delete all the existing catalog entries for library/community/infra are deleted (This is equivalent of disabling all the catalogs)
At this point , rancher catalog service gets halted and user is presented with error message "There are no compatible templates".

```
time="2016-10-25T18:07:50Z" level=info msg="Request to refresh catalog" 
time="2016-10-25T18:07:50Z" level=info msg="Halting Catalog service, Catalog git repo url not provided" 
```
Enable all catalogs by adding back the same catalog entries for library/community/infra.

User is presented with contents of all the catalogs from cache as expected immediately without having to wait for the catalog pull to fail.

**Closed by sangeethah** 2016-10-25 18:19 UTC
Labels: area/catalog-service, kind/bug, priority/-1, status/reopened, status/resolved, status/to-test
