### ISSUE TITLE
Feature Request: Add User Data option for Digital Ocean hosts

### ISSUE THREAD

**Issue by rubenmch** [rancher/rancher#2187] opened 2015-09-29 22:11 UTC
The Digital Ocean User Data option is missing in Rancher.

We need to add a swapfile to our hosts when the host is provisioned and right now there's to way to set this up in Rancher.

**Comment by rubenmch** [comment] 2015-09-29 22:28
I read in other issues you use the Docker Machine Digital Ocean driver which doesn't currently have the User Data option so this feature can't be implemented until that option is added to the driver.

**Comment by deniseschannon** [comment] 2016-07-13 04:56
Duplicate of https://github.com/rancher/rancher/issues/1765

**Closed by deniseschannon** 2016-07-13 04:56 UTC
Labels: area/machine, kind/enhancement, status/has-dependency
