### ISSUE TITLE
External service takes nearly 18mins to start in 1.1.0-DEV3

### ISSUE THREAD

**Issue by ibrokethecloud** [rancher/rancher#4971] opened 2016-05-31 23:13 UTC
**Rancher Version:**
1.1.0-DEV3

**Docker Version:**
1.10.2

**OS and where are the hosts located? (cloud, bare metal, etc):**
RHEL 7.2 on a multi cloud.

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
Single node Rancher with an external DB

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle

**Steps to Reproduce:**
Stop / Start stack

**Results:** 
When booting up a stack only containing external links and service aliases, we have observed that the services take too long too boot up.

I have traced one service down in the rancher logs which took nearly 18 mins to start up.

![image](https://cloud.githubusercontent.com/assets/19664014/15693477/c888de38-27d8-11e6-800f-3d08b4f7fb81.png)

I can trace the same in the rancher-debug logs and it shows the following:
```root@385f11f7e988:/var/lib/cattle/logs# grep -i serviceexposemap * | grep 451382
cattle-debug.log:2016-05-31 22:40:54,757 DEBUG [004ac0c6-799f-44e3-adab-63d2e7edeaad:7737034] [service:4779] [service.activate->(ServiceUpdateActivate)] [] [torService-1985] [c.p.e.p.i.DefaultProcessInstanceImpl] Attempting to run process [serviceexposemap.create:7737049] on resource [451382] 
cattle-debug.log:2016-05-31 22:40:54,765 DEBUG [004ac0c6-799f-44e3-adab-63d2e7edeaad:7737034] [service:4779->serviceExposeMap:451382] [service.activate->(ServiceUpdateActivate)->serviceexposemap.create] [] [torService-1985] [c.p.e.p.i.DefaultProcessInstanceImpl] Changing state [requested->activating] on [serviceExposeMap:451382] 
cattle-debug.log:2016-05-31 22:40:54,765 DEBUG [004ac0c6-799f-44e3-adab-63d2e7edeaad:7737034] [service:4779->serviceExposeMap:451382] [service.activate->(ServiceUpdateActivate)->serviceexposemap.create] [] [torService-1985] [c.p.e.p.i.DefaultProcessInstanceImpl] Exiting with code [SCHEDULED] : SCHEDULED 
cattle-debug.log:2016-05-31 22:40:54,774 DEBUG [004ac0c6-799f-44e3-adab-63d2e7edeaad:7737034] [service:4779] [service.activate->(ServiceUpdateActivate)] [] [torService-1985] [c.p.e.p.i.DefaultProcessInstanceImpl] Exiting [SCHEDULED] process [serviceexposemap.create:7737049] on resource [451382] 
cattle-debug.log:2016-05-31 22:41:09,800 INFO  [:] [] [] [] [torService-1985] [i.c.p.e.e.i.ProcessEventListenerImpl] Communication timeout on process [service.activate:7737034] on [4779] : Object [serviceExposeMap:451382] failed to satisfy predicate [15000] millis 
cattle-debug.log:2016-05-31 22:58:21,272 INFO  [:] [] [] [] [ecutorService-9] [i.c.p.e.e.i.ProcessEventListenerImpl] Communication timeout on process [service.activate:7737034] on [4779] : Object [serviceExposeMap:451382] failed to satisfy predicate [15000] millis 
cattle-debug.log:2016-05-31 22:58:21,588 DEBUG [:] [] [] [] [ecutorService-9] [c.p.e.p.i.DefaultProcessInstanceImpl] Attempting to run process [serviceexposemap.create:7737049] on resource [451382] 
cattle-debug.log:2016-05-31 22:58:21,603 DEBUG [dbbdfd06-23f7-4558-b558-5473d17092b6:7737049] [serviceExposeMap:451382] [serviceexposemap.create->(ServiceExposeMapCreate)] [] [ecutorService-9] [c.p.e.p.i.DefaultProcessInstanceImpl] Running handler [ServiceExposeMapCreate] 
cattle-debug.log:2016-05-31 22:58:21,603 DEBUG [dbbdfd06-23f7-4558-b558-5473d17092b6:7737049] [serviceExposeMap:451382] [serviceexposemap.create->(ServiceExposeMapCreate)] [] [ecutorService-9] [c.p.e.p.i.DefaultProcessInstanceImpl] Finished handler [ServiceExposeMapCreate] 
cattle-debug.log:2016-05-31 22:58:21,610 DEBUG [dbbdfd06-23f7-4558-b558-5473d17092b6:7737049] [serviceExposeMap:451382] [serviceexposemap.create->(AgentInstanceApplyItems)] [] [ecutorService-9] [c.p.e.p.i.DefaultProcessInstanceImpl] Running post listener [AgentInstanceApplyItems] 
cattle-debug.log:2016-05-31 22:58:21,612 DEBUG [dbbdfd06-23f7-4558-b558-5473d17092b6:7737049] [serviceExposeMap:451382] [serviceexposemap.create->(AgentInstanceApplyItems)] [] [ecutorService-9] [c.p.e.p.i.DefaultProcessInstanceImpl] Finished post listener [AgentInstanceApplyItems] 
cattle-debug.log:2016-05-31 22:58:21,612 DEBUG [dbbdfd06-23f7-4558-b558-5473d17092b6:7737049] [serviceExposeMap:451382] [serviceexposemap.create->(ActivateByDefault)] [] [ecutorService-9] [c.p.e.p.i.DefaultProcessInstanceImpl] Running post listener [ActivateByDefault] 
cattle-debug.log:2016-05-31 22:58:21,612 DEBUG [dbbdfd06-23f7-4558-b558-5473d17092b6:7737049] [serviceExposeMap:451382] [serviceexposemap.create->(ActivateByDefault)] [] [ecutorService-9] [c.p.e.p.i.DefaultProcessInstanceImpl] Finished post listener [ActivateByDefault] 
cattle-debug.log:2016-05-31 22:58:21,612 DEBUG [dbbdfd06-23f7-4558-b558-5473d17092b6:7737049] [serviceExposeMap:451382] [serviceexposemap.create->(LoadBalancerServiceUpdateConfig)] [] [ecutorService-9] [c.p.e.p.i.DefaultProcessInstanceImpl] Running post listener [LoadBalancerServiceUpdateConfig] 
cattle-debug.log:2016-05-31 22:58:21,615 DEBUG [dbbdfd06-23f7-4558-b558-5473d17092b6:7737049] [serviceExposeMap:451382] [serviceexposemap.create->(LoadBalancerServiceUpdateConfig)] [] [ecutorService-9] [c.p.e.p.i.DefaultProcessInstanceImpl] Finished post listener [LoadBalancerServiceUpdateConfig] 
cattle-debug.log:2016-05-31 22:58:21,619 DEBUG [dbbdfd06-23f7-4558-b558-5473d17092b6:7737049] [serviceExposeMap:451382] [serviceexposemap.create] [] [ecutorService-9] [c.p.e.p.i.DefaultProcessInstanceImpl] Changing state [activating->active] on [serviceExposeMap:451382] 
cattle-debug.log:2016-05-31 22:58:21,627 DEBUG [:] [] [] [] [ecutorService-9] [c.p.e.p.i.DefaultProcessInstanceImpl] Exiting [DONE] process [serviceexposemap.create:7737049] on resource [451382] ```

**Expected:**
This seems to have started after we moved to 1.1.0-DEV2. We have eventually moved to 1.1.0-DEV3 yesterday to see if it helped but its not made much of a difference. 

Can you please recommend if there is anything else we can check?

**Comment by ibuildthecloud** [comment] 2016-05-31 23:40
@ibrokethecloud I like the handle :)

The admin->processes in the UI is a good place to start.  That log doesn't provide much info.  The admin->process look for running task and if you click on them look for a little hazard icon.  That will have some error.

**Comment by alena1108** [comment] 2016-05-31 23:41
@ibrokethecloud could you share docker-compose/rancher-compose files of your stack?

**Comment by ibrokethecloud** [comment] 2016-05-31 23:44
@ibuildthecloud the handle was built with the hope it will garner attention and get someone to look at issues.. last one wasn't having much luck ;)

**Comment by ibrokethecloud** [comment] 2016-06-01 00:01
Here is the docker-compose:
```mail-smtp:
  image: rancher/external-service
mail-imap:
  image: rancher/external-service
db-outage:
  image: rancher/external-service
db-kana:
  image: rancher/external-service
service-desktop:
  image: rancher/external-service
service-esb-old:
  image: rancher/external-service
service-esb-new:
  image: rancher/external-service
service-doc-management:
  image: rancher/external-service
service-payments:
  image: rancher/external-service
service-harmony-address:
  image: rancher/external-service
service-virus-scan:
  image: rancher/external-service
service-solr:
  image: rancher/external-service
service-chat:
  image: rancher/external-service
monitoring-introscope:
  image: rancher/external-service
monitoring-logstash:
  image: rancher/external-service
```

Here is the rancher-compose
```mail-smtp:
  hostname: mailserver
mail-imap:
  hostname: mailimap
db-outage:
  hostname: ${DB_OUTAGE}.${FQDN}
db-kana:
  hostname: ${DB_KANA}.${FQDN}
service-desktop:
  external_ips: 
    - ${SERVICE_DESKTOP}
service-esb-old:
  hostname: ${SERVICE_ESB_OLD}.${FQDN}
service-esb-new:
  hostname: ${SERVICE_ESB_NEW}.${FQDN}
service-doc-management:
  hostname: ${SERVICE_DOC_MANAGEMENT}.${FQDN}
service-payments:
  hostname: ${SERVICE_PAYMENTS}.${FQDN}
service-harmony-address:
  hostname: ${SERVICE_HARMONY_ADDRESS}.${FQDN}
service-virus-scan:
  hostname: ${SERVICE_VIRUS_SCAN}.${FQDN}
service-solr:
  hostname: ${SERVICE_SOLR}.${FQDN}
service-chat:
  hostname: ${SERVICE_CHAT}.${FQDN}
monitoring-introscope:
  hostname: ${MONITORING_INTROSCOPE}.${FQDN}
monitoring-logstash:
  hostname: ${LOGSTASH}.${FQDN}

**Comment by JayHaoDing** [comment] 2016-06-01 00:38
@alena1108 strange thing is when service stucks at activating state, clicking stop button on that service will actually make it be active

By the way I'm with @ibrokethecloud :)

**Comment by ibrokethecloud** [comment] 2016-06-01 00:47
Here we go:

![image](https://cloud.githubusercontent.com/assets/19664014/15694973/f9391072-27e5-11e6-8437-c516599d7859.png)

```
io.cattle.platform.async.utils.TimeoutException: Object [serviceExposeMap:451813] failed to satisfy predicate [15000] millis
	at io.cattle.platform.object.monitor.impl.ResourceMonitorImpl.waitFor(ResourceMonitorImpl.java:92)
	at io.cattle.platform.object.monitor.impl.ResourceMonitorImpl.waitFor(ResourceMonitorImpl.java:97)
	at io.cattle.platform.object.monitor.impl.ResourceMonitorImpl.waitForNotTransitioning(ResourceMonitorImpl.java:124)
	at io.cattle.platform.servicediscovery.deployment.impl.unit.ExternalDeploymentUnitInstance.waitForNotTransitioning(ExternalDeploymentUnitInstance.java:112)
	at io.cattle.platform.servicediscovery.deployment.impl.unit.DeploymentUnit.createInstance(DeploymentUnit.java:264)
	at io.cattle.platform.servicediscovery.deployment.impl.unit.DeploymentUnit.start(DeploymentUnit.java:222)
	at io.cattle.platform.servicediscovery.deployment.ServiceDeploymentPlanner.deploy(ServiceDeploymentPlanner.java:144)
	at io.cattle.platform.servicediscovery.deployment.impl.DeploymentManagerImpl.startUnits(DeploymentManagerImpl.java:239)
	at io.cattle.platform.servicediscovery.deployment.impl.DeploymentManagerImpl.activateDeploymentUnits(DeploymentManagerImpl.java:206)
	at io.cattle.platform.servicediscovery.deployment.impl.DeploymentManagerImpl$1.doWithLock(DeploymentManagerImpl.java:131)
	at io.cattle.platform.servicediscovery.deployment.impl.DeploymentManagerImpl$1.doWithLock(DeploymentManagerImpl.java:110)
	at io.cattle.platform.lock.impl.AbstractLockManagerImpl$3.doWithLock(AbstractLockManagerImpl.java:40)
	at io.cattle.platform.lock.impl.LockManagerImpl.doLock(LockManagerImpl.java:33)
	at io.cattle.platform.lock.impl.AbstractLockManagerImpl.lock(AbstractLockManagerImpl.java:13)
	at io.cattle.platform.lock.impl.AbstractLockManagerImpl.lock(AbstractLockManagerImpl.java:37)
	at io.cattle.platform.servicediscovery.deployment.impl.DeploymentManagerImpl.activate(DeploymentManagerImpl.java:110)
	at io.cattle.platform.servicediscovery.deployment.impl.DeploymentManagerImpl.activate(DeploymentManagerImpl.java:93)
	at io.cattle.platform.servicediscovery.process.ServiceUpdateActivate.handle(ServiceUpdateActivate.java:78)
	at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl.runHandler(DefaultProcessInstanceImpl.java:446)
	at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl$4.execute(DefaultProcessInstanceImpl.java:393)
	at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl$4.execute(DefaultProcessInstanceImpl.java:387)
	at io.cattle.platform.engine.idempotent.Idempotent.execute(Idempotent.java:42)
	at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl.runHandlers(DefaultProcessInstanceImpl.java:387)
	at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl.runLogic(DefaultProcessInstanceImpl.java:493)
	at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl.runWithProcessLock(DefaultProcessInstanceImpl.java:320)
	at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl$2.doWithLockNoResult(DefaultProcessInstanceImpl.java:260)
	at io.cattle.platform.lock.LockCallbackNoReturn.doWithLock(LockCallbackNoReturn.java:7)
	at io.cattle.platform.lock.LockCallbackNoReturn.doWithLock(LockCallbackNoReturn.java:3)
	at io.cattle.platform.lock.impl.AbstractLockManagerImpl$3.doWithLock(AbstractLockManagerImpl.java:40)
	at io.cattle.platform.lock.impl.LockManagerImpl.doLock(LockManagerImpl.java:33)
	at io.cattle.platform.lock.impl.AbstractLockManagerImpl.lock(AbstractLockManagerImpl.java:13)
	at io.cattle.platform.lock.impl.AbstractLockManagerImpl.lock(AbstractLockManagerImpl.java:37)
	at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl.acquireLockAndRun(DefaultProcessInstanceImpl.java:257)
	at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl.runDelegateLoop(DefaultProcessInstanceImpl.java:185)
	at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl.executeWithProcessInstanceLock(DefaultProcessInstanceImpl.java:158)
	at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl$1.doWithLock(DefaultProcessInstanceImpl.java:108)
	at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl$1.doWithLock(DefaultProcessInstanceImpl.java:105)
	at io.cattle.platform.lock.impl.AbstractLockManagerImpl$3.doWithLock(AbstractLockManagerImpl.java:40)
	at io.cattle.platform.lock.impl.LockManagerImpl.doLock(LockManagerImpl.java:33)
	at io.cattle.platform.lock.impl.AbstractLockManagerImpl.lock(AbstractLockManagerImpl.java:13)
	at io.cattle.platform.lock.impl.AbstractLockManagerImpl.lock(AbstractLockManagerImpl.java:37)
	at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl.execute(DefaultProcessInstanceImpl.java:105)
	at io.cattle.platform.engine.eventing.impl.ProcessEventListenerImpl.processExecute(ProcessEventListenerImpl.java:74)
	at io.cattle.platform.engine.eventing.impl.ProcessEventListenerImpl.processExecute(ProcessEventListenerImpl.java:56)
	at sun.reflect.GeneratedMethodAccessor595.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at io.cattle.platform.eventing.annotation.MethodInvokingListener$1.doWithLockNoResult(MethodInvokingListener.java:76)
	at io.cattle.platform.lock.LockCallbackNoReturn.doWithLock(LockCallbackNoReturn.java:7)
	at io.cattle.platform.lock.LockCallbackNoReturn.doWithLock(LockCallbackNoReturn.java:3)
	at io.cattle.platform.lock.impl.AbstractLockManagerImpl$3.doWithLock(AbstractLockManagerImpl.java:40)
	at io.cattle.platform.lock.impl.LockManagerImpl.doLock(LockManagerImpl.java:33)
	at io.cattle.platform.lock.impl.AbstractLockManagerImpl.lock(AbstractLockManagerImpl.java:13)
	at io.cattle.platform.lock.impl.AbstractLockManagerImpl.lock(AbstractLockManagerImpl.java:37)
	at io.cattle.platform.eventing.annotation.MethodInvokingListener.onEvent(MethodInvokingListener.java:72)
	at io.cattle.platform.eventing.impl.AbstractThreadPoolingEventService$2.doRun(AbstractThreadPoolingEventService.java:135)
	at org.apache.cloudstack.managed.context.NoExceptionRunnable.runInContext(NoExceptionRunnable.java:15)
	at org.apache.cloudstack.managed.context.ManagedContextRunnable$1.run(ManagedContextRunnable.java:49)
	at org.apache.cloudstack.managed.context.impl.DefaultManagedContext$1.call(DefaultManagedContext.java:55)
	at org.apache.cloudstack.managed.context.impl.DefaultManagedContext.callWithContext(DefaultManagedContext.java:108)
	at org.apache.cloudstack.managed.context.impl.DefaultManagedContext.runWithContext(DefaultManagedContext.java:52)
	at org.apache.cloudstack.managed.context.ManagedContextRunnable.run(ManagedContextRunnable.java:46)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by JayHaoDing** [comment] 2016-06-01 01:00
@alena1108 I just tried same compose file with Rancher v1.0.2 and there is no issue. Seems new bug got introduced in 1.1.0-dev version

**Comment by JayHaoDing** [comment] 2016-06-01 12:09
Did a few more tests. There is no issue on a fresh installed Rancher v1.0.2 or v1.1.0-dev3. So seems something wrong with the Rancher db which has been upgraded a few times since v0.x version. We are checking it further, try to compare db scheme between a clean Rancher server and the heavy used Rancher server.

**Comment by flaccid** [comment] 2016-06-01 12:15
I did a `mysqldiff` and its the same (liquibase succeeded each time). I'm assuming something else is in play here; db data, state in processes, networking etc. After a check over of the external mysql db server its healthy and without error, performing well and schema matches that of what a clean v1.1.0-dev3 should be.

**Comment by alena1108** [comment] 2016-06-01 17:24
@JayHaoDing thank you for debugging it. 

> id a few more tests. There is no issue on a fresh installed Rancher v1.0.2 or v1.1.0-dev3. So seems something wrong with the Rancher db which has been upgraded a few times since v0.x version

Does the problem exist only for the stack created in one of the previous version? If you create the same stack on the upgraded setup, and stop/start it, do you still see the issue?

> strange thing is when service stucks at activating state, clicking stop button on that service will actually make it be active

There is a bug in our process logic: stuck process P1 (activate) doesn't get cancelled by P2 (deactivate), and as Inactive state - final state of deactivate process - is a valid start state for activate process, the stuck activate process will be performed again. 

@sangeethah as we are going to run upgrade test, could you check this use case while upgrading to dev3? Deploy the stack from compose file while being on the previous version, upgrade to dev3, stop/start the service.

**Comment by JayHaoDing** [comment] 2016-06-01 18:26
I used same compose filed provided above to create the stack in the newly installed Rancher. 
There are also more complex stacks in the other Rancher having same issue. It's quite random, any service may get stuck. But I haven't tried those stacks in new Rancher server as it requires other configuration/hosts. 

		_____________________________

**Comment by JayHaoDing** [comment] 2016-06-02 23:06
@alena1108 not sure if there is a issue for this bug?

> There is a bug in our process logic: stuck process P1 (activate) doesn't get cancelled by P2 (deactivate), and as Inactive state - final state of deactivate process - is a valid start state for activate process, the stuck activate process will be performed again.

**Comment by soumyalj** [comment] 2016-06-07 23:34
@ibrokethecloud : From what version did you upgrade to 1.1.0-dev3 ?

**Comment by JayHaoDing** [comment] 2016-06-07 23:41
@soumyalj from 1.1.0-dev2 and actually this issue was seen in 1.1.0-dev2 already. 

But we are not sure now from what version we upgraded to 1.1.0-dev2 because the rancher release label **latest** has been changed to indicate latest dev rather than stable version, so we probably accidentally upgraded from a stable version to dev version.

**Comment by flaccid** [comment] 2016-06-07 23:43
From memory, its been upgraded many times from even pre v1. It may of been from 1.0.0 to 1.0.1 to 1.0.2 to 1.1.0-dev2 to 1.1.0-dev3. We are basically wanting to avoid wiping the DB. A diff on the schema of the existing DB and a fresh one of 1.1.0-dev3 shows the schema structure is the same.

**Comment by flaccid** [comment] 2016-06-07 23:44
Now for this production rancher, we do plan on only using the `stable` tag per @JayHaoDing.

**Comment by JayHaoDing** [comment] 2016-06-10 01:31
Just tried 1.1.0-dev4, this issue still exists. Hopefully it can be fixed in 1.1.0

**Comment by JayHaoDing** [comment] 2016-06-10 01:45
I also tried Rancher v1.0.2 **with same mysql database** and the behaviour is different:

- InRancher v1.0.2 the service status seems also stuck but the stack status can become active quickly
- In Rancher v1.1.0-dev1+, both service/stack status may get stuck even the container status seems be fine

**Comment by soumyalj** [comment] 2016-06-10 20:51
Used the above docker-compose and rancher-compose as an example. Upgraded from 1.1.0-dev2 to 1.1.0-dev4. After stopping and starting the stack, all the external services start immediately. Not able to reproduce the issue.

**Comment by alena1108** [comment] 2016-06-10 20:56
@JayHaoDing 

> In Rancher v1.1.0-dev1+, both service/stack status may get stuck even the container status seems be fine

In the initial commit, you've mentioned the external service use case - so is reflected in your stack compose file. Are you seeing the issue for regular service as well? Is health check configured for the containers? 

We couldn't reproduce the issue in house. Is it possible to share following information once you hit the issue on your side:

* result of the db queries below
```
select id, name, state, health_state from environment where id =<stack id of the stack that is stuck in activating state"
select id, name, state, health_state from service where environment_id=<stack id>
select id, name, state, health_state from instance where id in (select instance_id from service_expose_map where service_id in (select id from service where environment_id=<id of your stack>))
```
* cattle-debug.log taken from your rancher server 

Service health state is comprised of combined health states of the service's instances health state. In case when all instance are running, but health state of at least one of them is unhealthy/initializing, the state of the service will say "unhealthy/initializing". Similar with the stack health state - it reflects health states of the services belonging to it. The request for db queries is to figure out if the failing health state causing the stack to be stuck.

cattle-debug log is to see if there is anything else failing.

**Comment by JayHaoDing** [comment] 2016-06-13 12:19
@soumyalj  thanks for your feedback. I'm pretty this issue is related to something inside our db because I have tried to setup a new Rancher server with 1.1.0-dev3 and there is no issue with the compose files provided above.

@alena1108 In our production Rancher, such problem happens for regular services too. I need confirm later if health check has been configured and I will provide more logs tomorrow.

**Comment by JayHaoDing** [comment] 2016-06-14 01:23
@alena1108 I tried above compose file again on v1.1.0-dev4 and here are outputs.

The URL of the stack is /env/1a14/apps/stacks/1e641 so 641 is the stack id in database. Seems there isn't any result from the 3rd db query

```
mysql> select id, name, state, health_state from cattle.environment where id = "641";
+-----+-------------+------------+--------------+
| id  | name        | state      | health_state |
+-----+-------------+------------+--------------+
| 641 | egress-test | activating | healthy      |
+-----+-------------+------------+--------------+
1 row in set (0.00 sec)

mysql> select id, name, state, health_state from cattle.service where environment_id="641";
+------+-------------------------+------------+--------------+
| id   | name                    | state      | health_state |
+------+-------------------------+------------+--------------+
| 2573 | service-chat            | activating | healthy      |
| 2574 | monitoring-XXX          | active     | healthy      |
| 2575 | service-XXX             | active     | healthy      |
| 2576 | service-XXX             | active     | healthy      |
| 2577 | monitoring-XXX          | active     | healthy      |
| 2578 | mail-imap               | active     | healthy      |
| 2579 | db-XXX                  | active     | healthy      |
| 2580 | db-XXX                  | active     | healthy      |
| 2581 | service-XXX             | active     | healthy      |
| 2582 | mail-smtp               | active     | healthy      |
| 2583 | service-XXX             | active     | healthy      |
| 2584 | service-XXX             | active     | healthy      |
| 2585 | service-XXX             | active     | healthy      |
| 2586 | service-XXX             | active     | healthy      |
| 2587 | service-XXXX            | active     | healthy      |
+------+-------------------------+------------+--------------+
15 rows in set (0.00 sec)

mysql> select id, name, state, health_state from cattle.instance where id in (select instance_id from cattle.service_expose_map where service_id in (select id from cattle.service where environment_id="641"));
Empty set (2.75 sec)
```

So I used the id 2573 from previous query but result was still empy
```
mysql> select id, name, state, health_state from cattle.instance where id in (select instance_id from cattle.service_expose_map where service_id="2573");
Empty set (2.42 sec)
```

I checked the cattle.service_expose_map table directly and looks the service_id is kind of 2 or 3 digits number. After selected 50000 items I could not see any item with 4 digits. So just for a try I did following query but it wasn't related at all.
```
mysql> select id, name, state, health_state from cattle.instance where id in (select instance_id from cattle.service_expose_map where instance_id="2573");
+------+----------------------+--------+--------------+
| id   | name                 | state  | health_state |
+------+----------------------+--------+--------------+
| 2573 | splunk_XXX           | purged | NULL         |
+------+----------------------+--------+--------------+
1 row in set (2.06 sec)
```

Then in the service page, I saw this string on top right so I did query based on 212745
` Activating (Waiting for [serviceExposeMap:1sem212745]. ServiceExposeMap status: null)`
cattle-debug.log shows as below. There is no log related to 212745 in cattle-error.log
```
# grep -i serviceexposemap * | grep 212745 cattle-debug.log
2016-06-14 00:16:37,680 DEBUG [4a846198-2dcb-492b-8b9a-213d55bfd48c:2844900] [service:2573] [service.activate->(ServiceUpdateActivate)] [] [cutorService-22] [c.p.e.p.i.DefaultProcessInstanceImpl] Attempting to run process [serviceexposemap.create:2844922] on resource [212745]
2016-06-14 00:16:37,714 DEBUG [4a846198-2dcb-492b-8b9a-213d55bfd48c:2844900] [service:2573->serviceExposeMap:212745] [service.activate->(ServiceUpdateActivate)->serviceexposemap.create] [] [cutorService-22] [c.p.e.p.i.DefaultProcessInstanceImpl] Changing state [requested->activating] on [serviceExposeMap:212745]
2016-06-14 00:16:37,714 DEBUG [4a846198-2dcb-492b-8b9a-213d55bfd48c:2844900] [service:2573->serviceExposeMap:212745] [service.activate->(ServiceUpdateActivate)->serviceexposemap.create] [] [cutorService-22] [c.p.e.p.i.DefaultProcessInstanceImpl] Exiting with code [SCHEDULED] : SCHEDULED
2016-06-14 00:16:37,725 DEBUG [4a846198-2dcb-492b-8b9a-213d55bfd48c:2844900] [service:2573] [service.activate->(ServiceUpdateActivate)] [] [cutorService-22] [c.p.e.p.i.DefaultProcessInstanceImpl] Exiting [SCHEDULED] process [serviceexposemap.create:2844922] on resource [212745]
2016-06-14 00:16:52,751 INFO  [:] [] [] [] [cutorService-22] [i.c.p.e.e.i.ProcessEventListenerImpl] Communication timeout on process [service.activate:2844900] on [2573] : Object [serviceExposeMap:212745] failed to satisfy predicate [15000] millis
2016-06-14 00:31:47,323 INFO  [:] [] [] [] [ecutorService-8] [i.c.p.e.e.i.ProcessEventListenerImpl] Communication timeout on process [service.activate:2844900] on [2573] : Object [serviceExposeMap:212745] failed to satisfy predicate [15000] millis
```

**Comment by JayHaoDing** [comment] 2016-06-14 01:50
@alena1108 how about the other bug you mentioned? Will it be fixed in v1.1.0?

> There is a bug in our process logic: stuck process P1 (activate) doesn't get cancelled by P2 (deactivate), and as Inactive state - final state of deactivate process - is a valid start state for activate process, the stuck activate process will be performed again.

**Comment by alena1108** [comment] 2016-06-14 02:00
@JayHaoDing most likely it will be fixed in the follow up dev release.

**Comment by JayHaoDing** [comment] 2016-06-15 05:27
Any idea if this is related to #5129? We see services which are stuck are looping in service_expose_map table there are huge number of removed items in our database.

**Comment by ibrokethecloud** [comment] 2016-06-15 05:38
Here is the query for one such service which was stuck:

![image](https://cloud.githubusercontent.com/assets/19664014/16069104/2c665c0a-330f-11e6-80bd-86345e301872.png)

Not sure if its even related but figured it was worth mentioning.

**Comment by aemneina** [comment] 2016-07-08 00:33
@alena1108 rooted this to be a case where hosts weren't present in the host table, but had agent reconnect processes chewing up resources. Processes were removed, agent state was marked as removed. That free'd up the process execution workers to do useful work. Closing issue.

**Closed by aemneina** 2016-07-08 00:33 UTC
Labels: kind/bug, status/to-test
