### ISSUE TITLE
Wait helm template failed. Error: stat /redis: no such file or directory : exit status 1

### ISSUE THREAD

**Issue by innerpeacez** [rancher/rancher#21706] opened 2019-07-23 10:01 UTC
**What kind of request is this (question/bug/enhancement/feature request):**
question

**Steps to reproduce (least amount of steps as possible):**
```
helm repo list
```
```
NAME    	URL                                        
harbor  	http://xx/chartrepo/library
```
```
helm -n test install redis harbor/redis
```
```
NAME: redis
LAST DEPLOYED: 2019-07-23 17:34:18.125769078 +0800 CST m=+0.243587752
NAMESPACE: test
STATUS: deployed

NOTES:
** Please be patient while the chart is being deployed **
Redis can be accessed via port 6379 on the following DNS names from within your cluster:

redis-master.test.svc.cluster.local for read/write operations
redis-slave.test.svc.cluster.local for read-only operations


To get your password run:

    export REDIS_PASSWORD=$(kubectl get secret --namespace test redis -o jsonpath="{.data.redis-password}" | base64 --decode)

To connect to your Redis server:

1. Run a Redis pod that you can use as a client:

   kubectl run --namespace test redis-client --rm --tty -i --restart='Never' \
    --env REDIS_PASSWORD=$REDIS_PASSWORD \
   --image docker.io/bitnami/redis:5.0.5-debian-9-r36 -- bash

2. Connect using the Redis CLI:
   redis-cli -h redis-master -a $REDIS_PASSWORD
   redis-cli -h redis-slave -a $REDIS_PASSWORD

To connect to your database from outside the cluster execute the following commands:

    kubectl port-forward --namespace test svc/redis 6379:6379 &
    redis-cli -h 127.0.0.1 -p 6379 -a $REDIS_PASSWORD

```
but I started it via rancher ui catelog and I get an error.

**Result:**
![image](https://user-images.githubusercontent.com/37059529/61701525-e582ae80-ad70-11e9-9c7b-e5e75b965c61.png)

![image](https://user-images.githubusercontent.com/37059529/61702631-bcfbb400-ad72-11e9-8c9d-1947772654c8.png)

![image](https://user-images.githubusercontent.com/37059529/61701602-0c40e500-ad71-11e9-8630-e9f3e8161870.png)

![image](https://user-images.githubusercontent.com/37059529/61701667-21b60f00-ad71-11e9-913f-c201fb74b39d.png)

Wait helm template failed. Error: stat /redis: no such file or directory : exit status 1

**Other details that may be helpful:**
This repo uses the repo of harbor.
![image](https://user-images.githubusercontent.com/37059529/61703149-97bb7580-ad73-11e9-97e4-231b95e1eb0a.png)

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI):
v2.2.4
- Installation option (single install/HA):
single install

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported):
- Machine type (cloud/VM/metal) and specifications (CPU/memory):
- Kubernetes version (use `kubectl version`):

```
(paste the output here)
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.1", GitCommit:"eec55b9ba98609a46fee712359c7b5b365bdd920", GitTreeState:"clean", BuildDate:"2018-12-13T10:39:04Z", GoVersion:"go1.11.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.5", GitCommit:"2166946f41b36dea2c4626f90a77706f426cdea2", GitTreeState:"clean", BuildDate:"2019-03-25T15:19:22Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}

```

- Docker version (use `docker version`):

```
(paste the output here)
Client:
 Version:           18.09.1
 API version:       1.39
 Go version:        go1.10.6
 Git commit:        4c52b90
 Built:             Wed Jan  9 19:35:01 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.1
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.6
  Git commit:       4c52b90
  Built:            Wed Jan  9 19:06:30 2019
  OS/Arch:          linux/amd64
  Experimental:     false


```

**Comment by superseb** [comment] 2019-08-13 22:10
This sounds as a duplicate of https://github.com/rancher/rancher/issues/18535, let me know if it is different.

**Closed by superseb** 2019-08-13 22:10 UTC
