### ISSUE TITLE
v0.43.1 Convoy issue

### ISSUE THREAD

**Issue by ajagnanan** [rancher/rancher#2469] opened 2015-10-28 20:44 UTC
I tried starting redis with the convoy driver and not sure why, but i'm getting this error: 

```Volume drivers were only introduced in API version 1.19```

I rolled back to v0.42 and its working. I think it may have to do with convoy?

**Comment by mattrochon** [comment] 2015-10-29 17:14
We are experiencing the same issue

**Comment by wlan0** [comment] 2015-10-30 18:10
@ajagnanan @mattrochon The issue is because of a regression caused by docker-py 1.5. We upgraded to docker-py 1.5 in v0.43 to support some new docker features (https://github.com/rancher/rancher/issues/2313). This version of docker-py does not allow `--volume-driver` to be passed in to `docker run (api call)` using a client version less than `1.19`. https://github.com/docker/docker-py/blob/master/docker/utils/utils.py#L707

A fix for this is in the works - https://github.com/rancher/python-agent/pull/181

**Comment by ajagnanan** [comment] 2015-10-30 18:12
cool, thanks!

**Comment by rahulgoel1985** [comment] 2015-11-12 17:12
Hi, In which version shall we expect the fix for this v0.45 as v0.44 is already released?

**Comment by deniseschannon** [comment] 2015-11-12 17:44
The fix will be in our next official Rancher release. We've been busy getting ready for DockerCon, so we will be skipping this week's release. Be sure to follow the announcements in the forums to get an update with the latest releases.

**Comment by sangeethah** [comment] 2015-11-14 00:37
Tested with build from master:

Since the issue is with setting any kind of volume-driver , verified the fix using "local" volume driver.

Docker version 1.9.0, build 76d6bc9 

Able to create containers using  volume-driver set to "local" and volume set to "volume name:/path"
Able to see the volume name listed when qureying for volumes in the host using -  docker volume ls command.
The container has "/path"  created.

When creating another container in the same host with volume-driver set to "local" and volume set to same value as the above container and verified that both containers share the same volume.

**Closed by sangeethah** 2015-11-14 00:37 UTC
Labels: area/volume, kind/bug, status/resolved, status/to-test

**Comment by jloisel** [comment] 2015-11-16 15:47
Confirmed on Ubuntu with Docker 1.9 and EBS volume driver. Going to wait the new release to use Convoy. We'll migrate from the host to the EBS volume once it's working again.
