### ISSUE TITLE
Validate k8s 1.8 with Docker 1.12.6, 1.13.x and 17.03

### ISSUE THREAD

**Issue by galal-hussein** [rancher/rancher#7852] opened 2017-02-16 21:35 UTC
**Rancher Versions:**
Server: v1.5.0-alpha1
healthcheck: v0.2.3
ipsec: v0.8.7
network-services: rancher/network-manager:v0.4.5
scheduler: rancher/scheduler:v0.6.3
kubernetes (if applicable): 1.5.2

**Docker Version:**
1.13.1
**OS and where are the hosts located? (cloud, bare metal, etc):**
RHEL 7.3
**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
single node rancher
**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Kubernetes
**Steps to Reproduce:**
- Install Rancher 1.5.0-alpha1
- Register agents with Docker 1.13.1
- Install kubernetes stack

**Results:** 

kubelet, kubectl, and rancher-ingress-controller services are failing with the following message:

```
Expected state running but got error: Error response from daemon: oci runtime error: container_linux.go:247: starting container process caused "process_linux.go:258: applying cgroup configuration for process caused \"mountpoint for devices not found\""
```

**Comment by galal-hussein** [comment] 2017-02-16 23:00
In ubuntu 16.04 the kubernetes stack had the same error at first, and it started eventually, but i can't create any container afterwards:

```
 Error (Error response from daemon: shim error: chmod /dev/pts/0: no such file or directory)
```

**Comment by alena1108** [comment] 2017-02-17 19:19
Doesn't look like k8s officially supports docker 1.13 for 1.5.x version: 

https://github.com/kubernetes/kubernetes/issues/40431
https://github.com/kubernetes/kops/issues/849

```
the supported configurations are kubernetes 1.3/1.4 with docker 1.11.2, and k8s 1.5 with docker 1.12.1 or 1.12.3. Anything else is likely to be troublesome.
```

**Comment by egulacti** [comment] 2017-03-10 07:52
I had the same issue and following alena's comment I uninstalled docker-ce (17.03.0~ce-0~ubuntu-xenial) and installed 1.12.3 version. Kubernetes is up and running now

**Comment by Z3roCoder** [comment] 2017-03-16 08:47
I currently have docker-ce version 1.17

Is the reccommended way to do this still to install docker 1.12?

**Comment by deniseschannon** [comment] 2017-03-16 21:11
@Z3roCoder Correct. Kubernetes 1.5.2, which is the current version that Rancher supports does not support Docker 1.13 or Docker 17.03

**Comment by iambowen** [comment] 2017-03-20 01:56
@deniseschannon  that make sense, I think it's the root cause. And tested, seems like so.

**Comment by Z3roCoder** [comment] 2017-03-21 15:14
How would I go about to correctly install a working docker version under Ubuntu 16.04?

**Comment by jralmaraz** [comment] 2017-04-05 03:23
@Z3roCoder  as stated before by Denise and Alena, you should use the supported docker versions. In my case I have just installed 1.12.6 and the Kubernetes Stack started smoothly.

apt-cache policy docker-engine
apt-get install -y docker-engine=1.12.6-0~ubuntu-xenial

Cheers!

**Comment by deniseschannon** [comment] 2017-04-06 21:39
k8s 1.6 still doesn't support docker 1.13, so moving this out to another release

**Comment by deniseschannon** [comment] 2017-08-28 23:27
When creating the templates for k8s 1.8, we should also verify the add-ons have the latest supported version.

**Comment by SamMousa** [comment] 2017-09-08 15:25
I'm getting the same issues on docker 1.12.6 (running 2 rancher OS nodes in vms and setting up kubernetes)

**Comment by sangeethah** [comment] 2017-09-15 17:42
closing this issue in favor of https://github.com/rancher/rancher/issues/9776

**Closed by sangeethah** 2017-09-15 17:42 UTC
Labels: area/kubernetes, kind/bug, status/to-test, version/1.6
