### ISSUE TITLE
Infrastructure stacks are displayed for a github member

### ISSUE THREAD

**Issue by soumyalj** [rancher/rancher#6869] opened 2016-12-01 23:43 UTC
**Rancher Version:**1.2.0

**Docker Version:**1.12.3

**OS and where are the hosts located? (cloud, bare metal, etc):**Ubuntu, Cloud

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**Single node

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**Cattle

**Steps to Reproduce:**
1. Create a rancher v1.2.0 setup
2. Enable github authentication
3. Add a github user as a member for an env
4. Login to rancher as a github member

Results
The infrastructure stacks are displayed when logged as a member.

Expected
Infrastructure stacks should not be displayed for members

**Comment by tfiduccia** [comment] 2016-12-02 00:14
This is not a bug.  Infrastructure is not referenced in the Stacks drop-down menu.  According to previous bug, being able to see them when you click on ALL is not a bug.

Duplicate of #6670

**Closed by tfiduccia** 2016-12-02 00:14 UTC
Labels: area/ui, kind/bug
