### ISSUE TITLE
[Bug] Cannot save registry credentials on rancher 2.4.3 and 2.4.4

### ISSUE THREAD

**Issue by presidenten** [rancher/rancher#27399] opened 2020-06-02 13:38 UTC
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
- Create cluster
- Try to add registry credentials to project for all namespaces
- Press the save-button

Browser console says that code cant check id of null
![image](https://user-images.githubusercontent.com/3883897/83526571-e8991000-a4e6-11ea-9f54-7e21fd74da9c.png)

Error here: 
![image](https://user-images.githubusercontent.com/3883897/83526636-023a5780-a4e7-11ea-98e8-d6ad2cbbd009.png)

**Result:**
- Get stuck in "Saving" forever

**Other details that may be helpful:**
I verified that the bug is not present in rancher 2.4.2.

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI):
2.4.3, 2.4.4
- Installation option (single install/HA):
Single install

**Comment by sangeethah** [comment] 2020-06-02 19:16
Duplicate of https://github.com/rancher/rancher/issues/26981

**Closed by sangeethah** 2020-06-02 19:16 UTC
