### ISSUE TITLE
Collect k3s-agent.service logs in addition to k3s.service

### ISSUE THREAD

**Issue by jawabuu** [rancher/rancher#33328] opened 2021-06-22 16:40 UTC
@nickgerace 
Following the update here https://github.com/rancher/charts/pull/1248 to use Journald instead of syslog for control plane logs,
the filter used is
```
Systemd_Filter    _SYSTEMD_UNIT=k3s.service
```
This will only collect logs for the k3s server process/k3s server node.
This filter should be added to also collect logs on agent nodes
```
Systemd_Filter    _SYSTEMD_UNIT=k3s-agent.service
```
@paynejacob  also fixed a similar situation for rke2 here
https://github.com/rancher/charts/pull/1249

https://github.com/rancher/charts/blob/c5552eb0deef54a00f7e6bb99f8bfdbf4c465f65/charts/rancher-logging/rancher-logging/100.0.0%2Bup3.10.0/templates/loggings/rke2/configmap.yaml#L17-L22

```
    [INPUT]
        Name              systemd
        Tag               rke2
        Path              {{ .Values.systemdLogPath | default "/var/log/journal" }}
        Systemd_Filter    _SYSTEMD_UNIT=rke2-server.service
        Systemd_Filter    _SYSTEMD_UNIT=rke2-agent.service
```

**Comment by izaac** [comment] 2021-07-07 21:52
This is only for systemd based systems. Not Alpine

**Comment by snasovich** [comment] 2021-07-14 22:12
@SheilaghM , assigning it to @nickgerace since he's the other Logging SME and we cannot have it validated by who implemented it (Jacob).

**Comment by brendarearden** [comment] 2021-08-13 18:52
Validation: FAILED

Steps to recreate:

1. Create a DO droplet, install docker and install k3s using `curl -sfL https://get.k3s.io | sh -` which installs v1.21.3+k3s1 (1d1f220f) and spins up a cluster
2. From an HA cluster (3 nodes on DO droplets clustered with rke version v1.2.11), running rancher v2.6.0-rc (installed using `helm install`)
3. Import existing k3s cluster
4. On the imported k3s cluster, install `rancher-logging`
5. Add an additional chart repo >>  name: example, type: git, git repo: https://github.com/paynejacob/rancher-logging-examples.git, branch: master
6. Go to charts and install the `rancher-logging example` from the new `example` you added
8. On local machine run `docker run -p 24224:24224 fluent/fluent-bit /fluent-bit/bin/fluent-bit -i forward -o stdout -p 'format=json_lines'`
9. On local machine run `ngrok tcp 24224`
9. Go to logging, cluster  outputs and edit the `all-logs` output as yaml and change the `spec` so that it looks like the following
```
spec:
  forward:
    servers:
    - host: 4.tcp.ngrok.io
      port: 13690
```
but use your own host and port that is output from your `ngrok` run
10. Wait a few minutes and see logs start to populate from pods
11. I do not see any logs being pulled from k3s
12. From the node running k3s, I run `journalctl -eu k3s -f` and see k3s is logging and none of those logs are being picked up.

**Comment by paynejacob** [comment] 2021-08-19 19:19
@brendarearden I think your environment was misconfigured for this.  Can you test on a cluster using ubuntu with `systemdLogPath: /var/log/journal` in your values.yaml.

**Comment by aiyengar2** [comment] 2021-08-20 20:48
k3s setup was reproduced as part of https://github.com/rancher/rancher/issues/33046#issuecomment-902946259.

As described in https://github.com/rancher/rancher/issues/33046#issuecomment-902948076, currently k3s logs are not being emitted at all due to a failure to parse the timestamp that was merged as part of the fix for https://github.com/rancher/rancher/issues/33046.

Both issues will be unblocked once the single fix to resolve that issue is put in.

**Comment by brendarearden** [comment] 2021-08-24 23:37
Validation: PASSED

**Steps to recreate:**

1. Create a EC2 instance, install docker and install k3s using `curl -sfL https://get.k3s.io | sh -` which installs v1.21.3+k3s1 (1d1f220f) and spins up a cluster
2. From an HA cluster (3 nodes on DO droplets clustered with rke version v1.2.11), running rancher v2.6.0-rc (installed using helm install)
3. Import existing k3s cluster in rancher
4. From the rancher ui, go into the k3s cluster, install logging - make sure to edit the values.yaml and change the `systemdLogPath` is set to `/var/log/journal`
5. Add an additional chart repo >> name: example, type: git, git repo: https://github.com/paynejacob/rancher-logging-examples.git, branch: master
6. Go to charts and install the rancher-logging example from the new example you added
7. On local machine run `docker run -p 24224:24224 fluent/fluent-bit /fluent-bit/bin/fluent-bit -i forward -o stdout -p 'format=json_lines'`
8. On local machine run `ngrok tcp 24224`
9. Go to logging, cluster outputs and edit the all-logs output as yaml and change the spec so that it looks like the following
```
spec:
  forward:
    servers:
    - host: 4.tcp.ngrok.io
      port: 13690
but use your own host and port that is output from your ngrok run
```
10. Wait a few minutes and see logs start to populate from pods
11. Validate that I see logs from k3s.service for systemd: 
```
{"date":1629829804.352445,"level":"warn","ts":"2021-08-24T18:30:04.352Z","caller":"etcdserver/util.go:163","msg":"apply request took too long","took":"476.926929ms","expected-duration":"100ms","prefix":"read-only range ","request":"key:\"/registry/namespaces/default\" ","response":"range_response_count:1 size:1124","_BOOT_ID":"dacc95935c394697ae64d09da4ee36d1","_MACHINE_ID":"ec29300ff8b2052f4a348b562c7e3809","PRIORITY":"6","SYSLOG_FACILITY":"3","_UID":"0","_GID":"0","_SELINUX_CONTEXT":"unconfined\n","_SYSTEMD_SLICE":"system.slice","_CAP_EFFECTIVE":"3fffffffff","_TRANSPORT":"stdout","_HOSTNAME":"ip-172-31-3-167","_SYSTEMD_CGROUP":"/system.slice/k3s.service","_SYSTEMD_UNIT":"k3s.service","SYSLOG_IDENTIFIER":"k3s","_COMM":"k3s-server","_EXE":"/var/lib/rancher/k3s/data/9df574741d2573cbbe6616e8624488b36b3340d077bc50da7cb167f1b08a64d1/bin/containerd","_CMDLINE":"/usr/local/bin/k3s server","_SYSTEMD_INVOCATION_ID":"cb761cade90f4c83a2775864d140db47","_STREAM_ID":"23f7ec19adb34127a289c09cbd10679c","_PID":"1944"}

```
12. Validate that I see logs from k3s-agent.service for systemd:
```
{"date":1629820002.294195,"_BOOT_ID":"569efbe2b13b4526a22f74914ddcad57","_MACHINE_ID":"ec2321e91a78265fcc2da05d10ba3ea0","PRIORITY":"6","SYSLOG_FACILITY":"3","_UID":"0","_GID":"0","_SELINUX_CONTEXT":"unconfined\n","_SYSTEMD_SLICE":"system.slice","_CAP_EFFECTIVE":"3fffffffff","_TRANSPORT":"stdout","_EXE":"/usr/bin/dash","_HOSTNAME":"ip-172-31-0-38","_STREAM_ID":"27cf6b86c21a4d91ba4bfd49533b2dd2","SYSLOG_IDENTIFIER":"sh","MESSAGE":"+ /usr/bin/systemctl is-enabled --quiet nm-cloud-setup.service","_PID":"1170","_COMM":"sh","_CMDLINE":"/bin/sh -xc ! /usr/bin/systemctl is-enabled --quiet nm-cloud-setup.service","_SYSTEMD_CGROUP":"/system.slice/k3s-agent.service","_SYSTEMD_UNIT":"k3s-agent.service","_SYSTEMD_INVOCATION_ID":"d29c0cef821048518f131fa5f5e4ed6d"}


{"date":1629835515.0,"level":"W","thread_id":"1174","filename":"warnings.go","linenumber":"70","message":"discovery.k8s.io/v1beta1 EndpointSlice is deprecated in v1.21+, unavailable in v1.25+; use discovery.k8s.io/v1 EndpointSlice","_BOOT_ID":"569efbe2b13b4526a22f74914ddcad57","_MACHINE_ID":"ec2321e91a78265fcc2da05d10ba3ea0","PRIORITY":"6","SYSLOG_FACILITY":"3","_UID":"0","_GID":"0","_SELINUX_CONTEXT":"unconfined\n","_SYSTEMD_SLICE":"system.slice","_CAP_EFFECTIVE":"3fffffffff","_TRANSPORT":"stdout","_HOSTNAME":"ip-172-31-0-38","_SYSTEMD_CGROUP":"/system.slice/k3s-agent.service","_SYSTEMD_UNIT":"k3s-agent.service","_SYSTEMD_INVOCATION_ID":"d29c0cef821048518f131fa5f5e4ed6d","_STREAM_ID":"4430a3fd538a4f3689b74a25504ad4da","SYSLOG_IDENTIFIER":"k3s","_PID":"1174","_COMM":"k3s-agent","_EXE":"/var/lib/rancher/k3s/data/9df574741d2573cbbe6616e8624488b36b3340d077bc50da7cb167f1b08a64d1/bin/containerd","_CMDLINE":"/usr/local/bin/k3s agent"}

```

I also confirmed that these logs were coming from the node running k3s using `journalctl -eu k3s -f` and on agents nodes using `journalctl -fu k3s-agent`

**Closed** 2021-08-25 14:13 UTC
Labels: kind/bug, area/logging, [zube]: QA Working, status/dev-validate, QA/S, release-note
