### ISSUE TITLE
Can not add environment in Rancher UI

### ISSUE THREAD

**Issue by nhumrich** [rancher/rancher#8559] opened 2017-04-20 19:37 UTC
**Rancher Versions:**
Server: 1.5.5
(all other info irrelevant as I cant even create an environment)

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
HA Rancher, external DB

**Steps to Reproduce:**
Create a rancher HA cluster in 1.5.3, create a couple environments. Upgrade rancher to 1.5.5, try to create another environment.

**Results:** 
The "add environment" button on the manage environments page takes you to a page with nothing on it. No network requests, but I get an error in the javascript console: 

```
ember.prod.js:17749 Uncaught TypeError: Cannot read property 'includes' of undefined
    at https://rancher2.mydomain.com/assets/ui-75c22fcbbbbec68ca05c03041d7a797a.js:94:3586
    at Array.find (native)
    at n.<anonymous> (https://rancher2.mydomain.com/assets/ui-75c22fcbbbbec68ca05c03041d7a797a.js:94:3543)
    at d.f.get (https://rancher2.mydomain.com/assets/vendor-0f5234ec3ba2a6f843abe79a8d0cccf9.js:10:23458)
    at Object.r (https://rancher2.mydomain.com/assets/vendor-0f5234ec3ba2a6f843abe79a8d0cccf9.js:11:30682)
    at n.get (https://rancher2.mydomain.com/assets/vendor-0f5234ec3ba2a6f843abe79a8d0cccf9.js:14:19994)
    at https://rancher2.mydomain.com/assets/ui-75c22fcbbbbec68ca05c03041d7a797a.js:80:3121
    at https://rancher2.mydomain.com/assets/vendor-0f5234ec3ba2a6f843abe79a8d0cccf9.js:14:12018
    at n.forEach (https://rancher2.mydomain.com/assets/vendor-0f5234ec3ba2a6f843abe79a8d0cccf9.js:14:11784)
    at n.map (https://rancher2.mydomain.com/assets/vendor-0f5234ec3ba2a6f843abe79a8d0cccf9.js:14:11980)```

**Comment by deniseschannon** [comment] 2017-04-21 19:51
@nhumrich Did you disable your community catalog? It sounds like this is a duplicate of https://github.com/rancher/rancher/issues/8461

**Comment by nhumrich** [comment] 2017-04-21 22:33
Yes I did. Does look like a duplicate.

**Closed** 2017-04-21 22:34 UTC
