### ISSUE TITLE
RKE2 Provisioning - etcd, control plane and worker nodes

### ISSUE THREAD

**Issue by deniseschannon** [rancher/rancher#32362] opened 2021-04-27 03:51 UTC
Introduced etcd only nodes concept into RKE2

Test nodes with individual roles as well as nodes with combined roles

**Comment by sowmyav27** [comment] 2021-05-12 16:35
Blocked because of https://github.com/rancher/rancher/issues/32543

**Comment by deniseschannon** [comment] 2021-05-18 20:53
This should be able to be tested as the blcoker bug was resolved.

**Comment by slickwarren** [comment] 2021-05-18 22:39
this only works for digital ocean nodes as of master (55f0bb2), and there is a visualization bug even for that case

https://github.com/rancher/rancher/issues/32741 -> custom cluster multinode
https://github.com/rancher/rancher/issues/32739 -> DO visualization bug
https://github.com/rancher/rancher/issues/32779 -> ec2 multi node

**Comment by slickwarren** [comment] 2021-05-20 16:24
As of master-head (55f0bb2):
the `worker` role doesn't have a label. This seems to imply that all nodes have the `worker` role by default, plus any other roles that were assigned to a node. **is this by design? should all nodes be worker nodes?** If so, we aren't able to assign dedicated nodes per role.  
Here's what a single node cluster's roles looks like:
<img width="546" alt="Screen Shot 2021-05-20 at 9 09 26 AM" src="https://user-images.githubusercontent.com/16691014/119014489-e07eee00-b94c-11eb-9432-4c7485bf8776.png">

and here's a single node without the `worker` role assigned when provisioning:
<img width="510" alt="Screen Shot 2021-05-20 at 9 22 53 AM" src="https://user-images.githubusercontent.com/16691014/119014591-fa203580-b94c-11eb-9ca8-51eb867c657f.png">


Below is an example of a multi node cluster, with one dedicated worker node.  
```
kubectl get nodes
NAME              STATUS   ROLES                       AGE     VERSION
ip-172-31-5-40    Ready    control-plane,etcd,master   7m18s   v1.20.5-dev+c8283cd8
ip-172-31-8-178   Ready    <none>                      66s 
```

Here is a related ticket https://github.com/rancher/rancher/issues/32799 for dedicated roles.

**Comment by deniseschannon** [comment] 2021-07-12 18:03
Yes, all nodes are worker by default. There are some other issues that will be adding the explicit worker label, but I've reopened this issue as trying to provision a cluster with separate roles seems to still be broken.

**Comment by kinarashah** [comment] 2021-07-29 20:32
etcd node is up but rke2-server fails to report active status, so system-agent is just waiting for `systemctl restart rke2-server` and doesn't update node status. This needs to be fixed in rke2 so the systemd notifies for etcd node without waiting for control plane node to come up.

**Comment by kinarashah** [comment] 2021-08-01 20:12
@deniseschannon I am confused as to why we moved this issue to test, the fix for this issue is set for milestone `v1.21.4+rke2r1` (https://github.com/rancher/rke2/issues/1483) which is yet to be released.

**Comment by deniseschannon** [comment] 2021-08-01 20:31
I thought the PR associated with this issue was merged and released as part of the RC. We will have to double check with the RKE2 team.

**Comment by deniseschannon** [comment] 2021-08-02 18:33
Available as part of RKE2 v1.21.3-rc1+rke2e2

**Comment by slickwarren** [comment] 2021-08-02 20:01
on master-head () I tested the following using RKE2 v1.21.3-rc1+rke2r2 (**REOPENING**):
* single node (DO) all roles -- pass
* multi cluster, combined roles (cp + etcd, etcd + worker, cp + worker) -- fail (cp + worker failed to register)
  * cp + worker has error `Waiting for node to be registered in Kubernetes`
* multi cluster, single node per role -- fail (no nodes register)
  * etcd node has error message `Waiting for control plane to be available`, cp node has `Waiting for etcd to be available` and worker node `Waiting for agent to check in and apply initial plan`

note: machine pools/configs did not show much in terms of errors, only what is shown above.  pools that did not have all nodes active read as 'scaling up'

**Comment by davidnuzik** [comment] 2021-08-03 22:57
PR: https://github.com/rancher/kontainer-driver-metadata/pull/625 (bumps to v1.21.3-rc2+rke2r2)

**Comment by rancher-max** [comment] 2021-08-04 01:21
The latest rke2 rc (rc2) allows systemd to come up:
```
  Active: active (running) since Tue 2021-08-03 23:56:26 UTC; 58min ago
```
however the nodes are not starting:
![image](https://user-images.githubusercontent.com/55997940/128106869-48424030-b704-4644-885d-40dd53f76776.png)


system agent on control plane is stuck with this message:
```
Aug 03 23:55:33 ip-172-31-14-208 rancher-system-agent[1346]: time="2021-08-03T23:55:33Z" level=debug msg="[K8s] Processing secret maxsing-bootstrap-template-p7b77-machine-plan in namespace fleet-default at gener>
```
and restarting the agent does not work, nor does restarting rke2-server process.

**Comment by kinarashah** [comment] 2021-08-04 16:38
https://github.com/rancher/kontainer-driver-metadata/pull/627

**Comment by kinarashah** [comment] 2021-08-04 17:15
Tested with Rancher v2.6-head, commit `88a46bd` and RKE2 `v1.21.3-rc2+rke2r2`. DO cluster, 1 etcd, 1 cp and 1 worker - nodes are provisioned successfully and cluster comes up Active.

**Comment by rancher-max** [comment] 2021-08-04 19:03
I see this working with rancher v2.6-head commit `222dced` using rke2 v1.21.3-rc2+rke2r2. Did a DO cluster and EC2 cluster with 1 etcd, 1 cp, and 1 worker as well.

**Comment by sowmyav27** [comment] 2021-08-04 20:55
**On 2.6-head commit id: `222dced`**

Validated the following scenarios. Able to deploy RKE2 clusters for the follow scenarios using rke2 version: `v1.21.3-rc2+rke2r2`
- 1 node all roles
- 1 etcd, 1 control and 1 worker nodes
- 1 etcd+ control and 2 worker nodes

The clusters - DO RKE2 came up Active.

**Closed by sowmyav27** 2021-08-04 20:55 UTC
Labels: [zube]: QA Next up, area/rke2, dependency-rke2, status/blocker, status/has-dependency

**Comment by slickwarren** [comment] 2021-08-04 21:06
also tested the following on 2.6-head commit id: 222dced:
* scale 1 node all roles (start with 1 node active, scale up to 3 nodes) 
* combination of roles (etcd + cp, cp + worker, worker + etcd)

smoke test of 1 role per node on master-head (2b156fd)
