### ISSUE TITLE
Misleading error message around failure to allocate container

### ISSUE THREAD

**Issue by aemneina** [rancher/rancher#8905] opened 2017-05-28 18:26 UTC
**Rancher versions:**
rancher/server: 1.5.9
rancher/agent: 1.2.2

**Docker version: (`docker version`,`docker info` preferred)**
1.12.6

**Steps to Reproduce:**
1. create a service with bind mount (local volume driver)
2. attempt to reschedule container to another host with label + scheduling rule
3. get failure 'Allocation failed: needs host with label schedule: container'

- Looks like the allocator determines the suitability for the container based on volume placement
- host label doesnt match the host found suitable

**Results:**
Get an error `(Failed to allocate instance [container:1i24]: Bad instance [container:1i24] in state [error]: Allocation failed: needs host with label schedule: container)`

Not sure if we can make a more helpful message here.

**Comment by StrongMonkey** [comment] 2017-05-30 20:30
duplicate of https://github.com/rancher/rancher/issues/8636

**Comment by deniseschannon** [comment] 2018-09-14 03:15
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.

**Closed by deniseschannon** 2018-09-14 03:15 UTC
Labels: area/scheduler, area/storage, kind/enhancement, priority/-1, status/autoclosed, version/1.6
