### ISSUE TITLE
[BUG] Error `error parsing azure-group-cache-size , skipping update strconv.Atoi: parsing "": invalid syntax` seen in Rancher server

### ISSUE THREAD

**Issue by sowmyav27** [rancher/rancher#40887] opened 2023-03-15 05:32 UTC
**Rancher Server Setup**
- Rancher version: 2.7-head commit `cd1a716`
- Installation option (Docker install/Helm Chart): Helm
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): RKE2 `v1.24.10+rke2r1`
- Proxy/Cert Details:

**User Information**
- What is the role of the user logged in? (Admin/Cluster Owner/Cluster Member/Project Owner/Project Member/Custom)
  - If custom, define the set of permissions: Admin

**Describe the bug**
[BUG] Error `error parsing azure-group-cache-size , skipping update strconv.Atoi: parsing "": invalid syntax` seen in Rancher server

**To Reproduce**
- Rancher server has a few clusters - RKE2/RKE1/k3s downstream clusters.
- And this error is seen a few times in the rancher server `error parsing azure-group-cache-size , skipping update strconv.Atoi: parsing "": invalid syntax`

**Result**
Error in Rancher server logs
```
2023/03/15 05:25:14 [INFO] Starting cluster controllers for c-mjj4s
2023/03/15 05:25:14 [INFO] Starting cluster.cattle.io/v3, Kind=ClusterUserAttribute controller
2023/03/15 05:25:14 [INFO] Starting cluster.cattle.io/v3, Kind=ClusterAuthToken controller
2023/03/15 05:25:14 [ERROR] error parsing azure-group-cache-size, skipping update strconv.Atoi: parsing "": invalid syntax
2023/03/15 05:25:14 [INFO] Refreshing driverMetadata in 1440 minutes
2023/03/15 05:25:14 [INFO] cluster [c-mjj4s] worker-upgrade: call upgrade to reconcile for node [m-2sdxh]
2023/03/15 05:25:14 [INFO] cluster [c-mjj4s] worker-upgrade: updated node [m-2sdxh] to upgrade
2023/03/15 05:25:14 [INFO] driverMetadata: refreshing data from upstream https://releases.rancher.com/kontainer-driver-metadata/dev-v2.7/data.json
2023/03/15 05:25:14 [INFO] Retrieve data.json from local path /var/lib/rancher-data/driver-metadata/data.json
2023/03/15 05:25:15 [INFO] cluster [c-hgwv6] worker-upgrade: call upgrade to reconcile for node [m-hkxw8]
```

---
**Note:**
- This issue is seen on 2.7.0 also
SURE-3985

**Comment by snasovich** [comment] 2023-03-15 18:31
@sowmyav27 , are there any clusters in Azure in your setup?

@prachidamle @MKlimuszka , this error is coming from https://github.com/rancher/rancher/blob/cd1a71624a94de993d471ce8a643cf4d2dbb75a6/pkg/auth/providers/azure/azure_provider.go#L472 and being in Auth Providers looks like your team is best positioned to investigate it (it could be caused by something on our end, but the error message is in Auth Providers still). Changing team label to `team/area3`.

**Comment by MKlimuszka** [comment] 2023-03-16 17:35
We can queue this for investigation after the other tickets we've committed to for Q2.

**Comment by jakefhyde** [comment] 2023-03-16 17:38
For context, this error message is transient, and has been happening for years (see logs: https://github.com/rancher/rancher/issues/30747#issue-782279364). It's just trying to sync the `azure-group-cache-size` setting, which has a default value of `""`, so `strings.Atoi` doesn't work.

**Comment by nickwsuse** [comment] 2023-06-02 19:44
`Verified on v2.7-head ID: f0d4078`

I imported an AKS cluster and provisioned a downstream AKS cluster and I didn't see this error in the logs for any of the rancher pods.

**Closed** 2023-06-12 18:16 UTC
Labels: kind/bug, area/authentication, team/area3, [zube]: QA Review
