### ISSUE TITLE
Rancher 2 enable jwt token auth passthrough

### ISSUE THREAD

**Issue by mitchellmaler** [rancher/rancher#15813] opened 2018-09-26 01:53 UTC
Currently, with Rancher 2 you have to use the bearer token that it provides to access the Kubernetes cluster. We also use Rancher to manage the request to the clusters api server. There are times were apps/libraries only support k8s service account authentication with jwt tokens but using rancher this is not possible. Rancher server should either support jwt tokens mapped to a service account in the cluster or just provide a passthrough to the secured clusters api server (behind rancher) which allows authenticating as that service account. This would allow compatibility with applications that do not natively support basic authentication with rancher using the tokens.

**Comment by superseb** [comment] 2018-09-26 13:29
Duplicate of https://github.com/rancher/rancher/issues/14997

**Closed by superseb** 2018-09-26 13:29 UTC
Labels: version/2.0
