### ISSUE TITLE
Will Rancher Support Aliyun SLB

### ISSUE THREAD

**Issue by artemus717** [rancher/rancher#8921] opened 2017-05-30 16:30 UTC
Will Rancher support aliyun slb load balance like aws elb ?

**Rancher versions:**
rancher/server: 1.5.5
rancher/agent:

**Infrastructure Stack versions:**
healthcheck:
ipsec:
network-services:
scheduler:
kubernetes (if applicable):

**Docker version: (`docker version`,`docker info` preferred)**

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**

**Steps to Reproduce:**

**Results:**

**Comment by niusmallnan** [comment] 2017-05-31 03:33
China team has a plan to do this thing, first assigned to me.

**Comment by artemus717** [comment] 2017-05-31 06:34
Good news !

**Comment by niusmallnan** [comment] 2017-06-05 09:42
@artemus717  
I did some simple work.
You can add this catalog if you want to try it out.
https://github.com/niusmallnan/slb-catalog

**Comment by artemus717** [comment] 2017-06-12 13:37
Thanks , i will try it in my test environment first !

**Comment by artemus717** [comment] 2017-06-20 15:26
It can not start up , even if i cancel healthcheck

**Comment by niusmallnan** [comment] 2017-06-21 01:34
@artemus717 You don't need to cancel healthcheck, you can show external-lb logs here, I can help you to find out the cause.
I have tested it, it can work well.

**Comment by artemus717** [comment] 2017-06-21 08:57
I find out why. Is there any document show how to use it ?

time="2017-06-20T14:50:37Z" level=info msg="Starting Rancher External LoadBalancer service"
time="2017-06-20T14:50:38Z" level=fatal msg="Failed to initialize provider 'aliyun_slb': SLB_ACCESS_KEY is not set"
time="2017-06-20T14:50:40Z" level=info msg="Starting Rancher External LoadBalancer service"
time="2017-06-20T14:50:41Z" level=fatal msg="Failed to initialize provider 'aliyun_slb': SLB_ACCESS_KEY is not set"
time="2017-06-20T14:50:43Z" level=info msg="Starting Rancher External LoadBalancer service"
time="2017-06-20T14:50:44Z" level=fatal msg="Failed to initialize provider 'aliyun_slb': SLB_ACCESS_KEY is not set"
time="2017-06-20T14:50:52Z" level=info msg="Starting Rancher External LoadBalancer service"
time="2017-06-20T14:50:53Z" level=fatal msg="Failed to initialize provider 'aliyun_slb': SLB_ACCESS_KEY is not set"

**Comment by niusmallnan** [comment] 2017-06-22 02:08
@artemus717 
same with this：https://github.com/rancher/community-catalog/blob/master/templates/aws-elbv1/0/README.md

**Comment by artemus717** [comment] 2017-07-09 11:37
time="2017-07-09T11:21:39Z" level=error msg="Failed to add LB config for endpoint lb-wz916mwopirjez047mhm0: SLB 'lb-wz916mwopirjez047mhm0' is not configured with instance port matching the service port '85'"
time="2017-07-09T11:21:46Z" level=info msg="LB configs to add: 1"
time="2017-07-09T11:21:46Z" level=info msg="Adding LB config: {lb-wz916mwopirjez047mhm0 cloud_CLOUD-IDA-TENANT_c5a02060-0ae9-4242-96d9-a31eb58c3c40_rancher.internal 85 [{172.20.1.190 85}]}"
time="2017-07-09T11:21:47Z" level=error msg="Failed to add LB config for endpoint lb-wz916mwopirjez047mhm0: SLB 'lb-wz916mwopirjez047mhm0' is not configured with instance port matching the service port '85'"


I think the port should be backend server port , not front port .
Some times , the port we want to expose is not the one on the host.

**Comment by hongxiaolu** [comment] 2017-07-25 03:22
Test passed！

If the logs prompt  " time="2017-07-24T15:11:26Z" level=fatal msg="Failed to initialize Rancher metadata client: Get http://rancher-metadata/2015-12-19/version: dial tcp: lookup rancher-metadata: no such host" "
you must comment out  " options timeout:1 attempts:1 rotate single-request-reopen  " in the "/etc/resolv.conf "

**Comment by artemus717** [comment] 2017-07-28 15:35
@niusmallnan Can I make some help ?

**Comment by yasker** [comment] 2017-09-15 22:06
Hi @artemus717

Can you help to check if SLB in https://github.com/rancher/rancher-catalog/tree/v1.6-cn-development works for you?

Thanks!

**Comment by artemus717** [comment] 2017-09-24 09:54
@yasker I will make a test as soon as possible.

**Comment by yasker** [comment] 2017-09-24 09:56
@artemus717 Great, thanks!

**Comment by kingsd041** [comment] 2017-09-25 11:43
@yasker @niusmallnan 
Tested with rancher-server version-v1.6.10 with rancher/external-lb:v0.3.2 
Environment with 2 hosts.
ECS uses the proprietary network.
ECS instances are registered in Rancher with their private/public IP addresses.

Test passed.

**Comment by yasker** [comment] 2017-09-25 11:44
@kingsd041 Thanks. Let's wait a bit for @artemus717 's result.

**Comment by yasker** [comment] 2017-10-06 05:28
It looks good. Let's close this.

**Closed by yasker** 2017-10-06 05:28 UTC
Labels: area/loadbalancer, kind/feature, status/to-test, team/cn

**Comment by artemus717** [comment] 2017-10-15 16:35
@yasker I deploy it in my protest environment for several days .
It still can not listen to the front port of SLB.

![image](https://user-images.githubusercontent.com/16465173/31586858-e2a7396a-b209-11e7-83b9-8611dd7ff7e9.png)

**Comment by yasker** [comment] 2017-10-15 16:38
@artemus717 do you have the reproduce steps?

**Comment by niusmallnan** [comment] 2017-10-16 01:31
@artemus717 
Please see the README: https://github.com/rancher/rancher-catalog/blob/v1.6-cn-development/infra-templates/aliyun-slb/0/README.md
`The front end ports of the SLB listener need to be consistent with the exposed ports on the host.`

This is due to the restriction of Aliyun SDK.

**Comment by artemus717** [comment] 2017-10-18 11:10
![_20171018185537](https://user-images.githubusercontent.com/16465173/31715340-0a5d00f6-b436-11e7-89b1-e03a3c817f2b.jpg)
@yasker Can you understand my poor painting ?
Since ports are rare resource on hosts,  when we run serveral container on one host and want them both be port 80 , we use slb do this.

**Comment by artemus717** [comment] 2017-10-18 11:12
@niusmallnan Thanks , i find another way to do this .
I add both port to SLB , for example backend port is 8443 front port is 443 , i add both 8443 and 443 to front port and set 443 can only response to 127.0.0.1.
