### ISSUE TITLE
Rancher agent  does not use proxy environment in callback to  rancher

### ISSUE THREAD

**Issue by chrisbulgaria** [rancher/rancher#24876] opened 2020-01-07 09:34 UTC
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
Import existing cluster into Rancher - with a proxy between that cluster and Rancher. Add to the agent yaml the required HTTP_PROXY, HTTPS_PROXY, NO_PROXY envs

Expected : Rancher cluster/node can contact Rancher and import is successful

**Result:**
Rancher agent wss calls fail, log 
time="2019-12-19T09:39:08Z" level=info msg="Connecting to wss://rancher.foobar.com with token $token"
time="2019-12-19T09:39:08Z" level=info msg="Connecting to proxy" url="wss://rancher.foobar.com/v3/connect/register"
time="2019-12-19T09:39:18Z" level=error msg="Failed to connect to proxy. Empty dialer response" error="dial tcp :443: i/o timeout"
time="2019-12-19T09:39:18Z" level=error msg="Remotedialer proxy error" error="dial tcp $IP_OF_RANCHER:443: i/o timeout"

**Other details that may be helpful:**
This is the same issue as rancher/rancher#24681 and rancher/rancher#22750 , sorry for opening a new one, but those are probably not clear enough.
The problem is in remotedialer/client.go line 26
dialer = &websocket.Dialer{HandshakeTimeout:HandshakeTimeOut}
should read instead
dialer = &websocket.Dialer{HandshakeTimeout:HandshakeTimeOut,Proxy: http.ProxyFromEnvironment}

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI):
2.3.3 single install

gz#13523

**Comment by chrisbulgaria** [comment] 2020-01-19 12:39
This  bug still exists in 2.3.4

**Comment by rshiva777** [comment] 2020-01-24 08:17
@ loganhz, is the issue resolved. it am still facing the same proxy issue in v.2.3.4

**Comment by chrisbulgaria** [comment] 2020-01-25 06:39
No , it’s not resolved unfortunately . I ‘ll continue to try to make rancher people see it’s important ... here is the pull request fixing it : https://github.com/rancher/remotedialer/pull/12

**Comment by sangeethah** [comment] 2020-02-01 00:23
Re opening this issue for validation.

**Comment by bmdepesa** [comment] 2020-02-03 16:29
rancher/rancher:v2.3-head
rancher/rancher:master-head

* Created Rancher behind proxy
* Created nodedriver ec2 cluster
* Created imported cluster -- adding proxy vars to agent YAMLs before importing.
* Rancher server, nodedriver cluster, and imported cluster are all using the proxy, with traffic seen crossing the proxy through logs.

**Comment by bmdepesa** [comment] 2020-02-12 20:44
rancher/rancher:v2.3-head 6eecc2c8b

Re-validated this issue w/ the following scenario:
* Rancher not behind proxy
* Get import yaml from registration command
* Modify yaml to include proxy vars for both agents:
```
- name: HTTP_PROXY
  value: "url:port"
- name: HTTPS_PROXY
  value: "url:port"
- name: NO_PROXY
  value: "localhost,127.0.0.1,0.0.0.0"
```
* Cluster registers w/ traffic going through proxy
* Deployed workload in imported cluster

**Comment by bmdepesa** [comment] 2020-02-13 19:05
https://github.com/rancher/docs/issues/2286

**Comment by djakielskiadesso** [comment] 2020-05-19 10:58
This bug also still exists in the latest release 2.4.3

**Comment by janeczku** [comment] 2020-11-06 09:09
It appears that this issue was only partially fixed:
The agent now uses the proxy environment variables during the initial websocket connection but then Rancher re-applies the agent YAML and the environment variables get lost : https://github.com/rancher/rancher/issues/25412

**Comment by kinarashah** [comment] 2021-01-29 22:57
Using this issue to track agent not respecting proxy env vars, closing https://github.com/rancher/rancher/issues/25412 

gz#13333

**Comment by deniseschannon** [comment] 2021-02-11 21:26
Testing is dependent on UI (#31023), but backend is complete.

**Comment by slickwarren** [comment] 2021-02-11 22:02
currently blocked by https://github.com/rancher/rancher/issues/31258 (unable to test backend)

**Comment by slickwarren** [comment] 2021-02-16 19:20
tested the backend, and is still failing to properly deploy downstream cluster behind proxy

**Steps to reproduce (least amount of steps as possible):**
* deploy rancher v2.5-head (3e96d7f)
* deploy a downstream cluster 
* update agentEnvVars using v3 api (I set proxy settings HTTP_PROXY, HTTPS_PROXY, NO_PROXY



**Result:**
* this cluster and any subsequent clusters will have an error related to `spec.template.spec.containers[0].env`
* API is clearing the agentEnvVars set, and resetting with an empty name and the schema type
<img width="486" alt="Screen Shot 2021-02-12 at 3 06 37 PM" src="https://user-images.githubusercontent.com/16691014/108100752-2f11a900-703b-11eb-92b4-c12a799c7234.png">
<img width="318" alt="Screen Shot 2021-02-16 at 9 12 51 AM" src="https://user-images.githubusercontent.com/16691014/108100754-3042d600-703b-11eb-8bda-a76080277cbf.png">

**Comment by axeal** [comment] 2021-02-18 09:54
@slickwarren The correct format for an envVar is as follows, and agentEnvVars can be successfully set via the API in this format in my testing on `v2.5-head (03b8153)`: `{"name":"HTTP_PROXY","value":"http://192.168.200.1:80"}`

However, these do not propagate to the imported cluster cluster-agent YAML, due to a variable naming mismatch in
https://github.com/rancher/rancher/pull/31024/commits/cd7f89a449c9c8678eaf8bc3c35d9031139740ff These are passed to the template as `AgentEnvVars` but the template references `AgentEnvVar`

**Comment by kinarashah** [comment] 2021-02-18 17:15
@axeal About the variable naming mismatch, I fixed it later in #31124, which was tested in `v2.5-head` for issue https://github.com/rancher/rancher/issues/31126.  Do you still see the issue?

**Comment by axeal** [comment] 2021-02-19 10:41
@kinarashah I just tested again with `v2.5-head (96dc206)` and observe the agentEnvVars are still not propogated to the cattle-cluster-agent in the registration YAML.

**Steps to reproduce (least amount of steps as possible):**
- Deploy a Rancher `v2.5-head (96dc206)` instance
- Create an imported cluster
- Edit imported cluster via API to add an agentEnvVars `{"name":"HTTP_PROXY","value":"http://192.168.200.1:80"}`
- View registration YAML for the imported cluster

**Result:**
- No `HTTP_PROXY` env variable present on the cluster-register container of the cluster-agent Deployment.

**Comment by slickwarren** [comment] 2021-02-20 23:56
I am now able to use proxy environment correctly ([see repro details from this ticket](https://github.com/rancher/rancher/issues/29993#issuecomment-782766995)) on v2.5-head( 96dc206)  and master-head (dbf1838).  I did notice that, on 2.5-head, the yaml from the registration command _did not_ include the env vars set through v3 api, so i manually added them. However on master-head, they were there but missing `"` around the values (all other env values had these).  I added them to each value before running `kubectl apply -f <registration>.yaml` 
cc @kinarashah not sure if this is expected or not, but not blocking this ticket since the current process isn't expecting the manually added values to be in the downloaded yaml. 

<img width="429" alt="Screen Shot 2021-02-20 at 3 01 43 PM" src="https://user-images.githubusercontent.com/16691014/108611485-b5a7ec80-7393-11eb-9a25-65b8f02a21e8.png">

**Comment by slickwarren** [comment] 2021-02-21 00:37
reopening: the missing quotes in the env vars was validated to work, but we do expect these to be added automatically to the yaml if they exist on the rancher server. Reopening because the build for 2.5-head failed, will validate that they are added as soon as the build is ready

**Comment by slickwarren** [comment] 2021-02-22 15:49
verified that running the registration cmd as-is (after adding agentEnvVars via v3 api) is working as well. The yaml now includes those variables 
<img width="329" alt="Screen Shot 2021-02-22 at 7 46 07 AM" src="https://user-images.githubusercontent.com/16691014/108732309-48ef3800-74e2-11eb-99ae-7aaca8719226.png">
<img width="351" alt="Screen Shot 2021-02-22 at 7 46 24 AM" src="https://user-images.githubusercontent.com/16691014/108732312-4a206500-74e2-11eb-89ad-035675982c9c.png">
tested on  master-head (dbf1838) and 2.5-head (b4be2b22879d85f268dff655206b8e515d803142).

**Closed by slickwarren** 2021-02-22 15:49 UTC
Labels: [zube]: QA Next up, internal, kind/bug, priority/0

**Comment by mightymouse2045** [comment] 2021-06-05 08:14
> * Edit imported cluster via API to add an agentEnvVars `{"name":"HTTP_PROXY","value":"http://192.168.200.1:80"}`

How do you do this step?

**Comment by d02540315** [comment] 2022-03-30 19:55
> verified that running the registration cmd as-is (after adding agentEnvVars via v3 api) is working as well. The yaml now includes those variables <img alt="Screen Shot 2021-02-22 at 7 46 07 AM" width="329" src="https://user-images.githubusercontent.com/16691014/108732309-48ef3800-74e2-11eb-99ae-7aaca8719226.png"> <img alt="Screen Shot 2021-02-22 at 7 46 24 AM" width="351" src="https://user-images.githubusercontent.com/16691014/108732312-4a206500-74e2-11eb-89ad-035675982c9c.png"> tested on master-head ([dbf1838](https://github.com/rancher/rancher/commit/dbf18389c36b56983c9848c1de1832faea2fc0a6)) and 2.5-head ([b4be2b2](https://github.com/rancher/rancher/commit/b4be2b22879d85f268dff655206b8e515d803142)).

Hi - can you attach the whole yaml file please?
