### ISSUE TITLE
Unable to remove node with "Waiting on user-node-remove" message

### ISSUE THREAD

**Issue by SheilaghM** [rancher/rancher#36055] opened 2022-01-06 18:23 UTC
SURE-3520

Rancher Cluster:
Rancher version: 2.5.9
Number of nodes: 3
Node OS version: Rancher OS v1.5.3

Downstream Cluster:
Number of Downstream clusters: 110
Node OS: Rancher OS v1.5.3
RKE/RKE2/K3S version: 
Kubernetes version: v1.18.20
CNI: Canal

Longhorn:
Longhorn version:
CPU per node:
Memory per node:
Disk type: HDD/SSD/NVMe
Network bandwidth between the nodes:

Other:
Underlying Infrastructure: AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal
Any 3rd party software installed on the nodes:

**User Information**
- What is the role of the user logged in? (Admin/Cluster Owner/Cluster Member/Project Owner/Project Member/Custom)
  - If custom, define the set of permissions:

Issue description:
k8 node doesn't get removed from the cluster - UI shows the message: "Waiting on user-node-remove_c-qhshf"

Business impact:
They are updating Operating system in all the downstream cluster nodes. when they remove a node from the vsphere node pool, it was stuck in removing. Also it was not removing from the vCenter as well. They are stuck in removing the nodes and can't upgrade their nodes now.

Troubleshooting steps:
1. Edit the node in cli -> remove the finalizer -> node gets removed from the UI( but not from the vCenter)

Repro steps:

Not able to reproduce the issue in house.
Workaround:
Is workararound available and implemented? yes
What is the workaround: Remove the finalizer from node yaml.

Actual behavior:
Node stick in removing state

Expected behavior:
Node should be removed from the UI and vCenter.

Files, logs, traces:
finalizers: - clusterscoped.controller.cattle.io/user-node-remove_c-xxxxxxxx (see SURE for actual)
Logs attached to SURE ticket

**Comment by MKlimuszka** [comment] 2022-02-01 22:41
Resolving as unable to reproduce

**Closed** 2022-02-01 22:41 UTC
Labels: [zube]: Need Info, team/area3
