### ISSUE TITLE
Rancherv2.5.2 & ARM

### ISSUE THREAD

**Issue by PPCM** [rancher/rancher#30034] opened 2020-11-11 17:21 UTC
There is no build for ARM arch.

Can you build it?
Thanks

**Comment by cbron** [comment] 2020-11-11 17:42
Hi @PPCM the latest and stable tags only have AMD, we should be fixing that in future. For now there is an arm build on the tag itself: https://hub.docker.com/layers/rancher/rancher/v2.5.2/images/sha256-2abde8adf2acf4830bcab85f41122d45a2685129dbe25e7590b7f28337b8fac1?context=explore

**Comment by PPCM** [comment] 2020-11-11 17:48
Thanks for the answer, I will wait the official build

**Comment by cbron** [comment] 2020-11-11 18:00
That is the official build, the one I linked. The problem is that the way we copy from that build to the stable tag drops the arm image.

**Comment by PPCM** [comment] 2020-11-11 18:02
OK, great. So I will use it!

**Comment by cbron** [comment] 2020-11-11 18:18
Ok good, closing this issue then.

**Closed by cbron** 2020-11-11 18:18 UTC
