### ISSUE TITLE
[UI] deployment with node specified does not display properly

### ISSUE THREAD

**Issue by guoyk93** [rancher/rancher#21847] opened 2019-07-30 05:59 UTC
Rancher v2.2.6
UI v2.2.90

Deployment with node specified does not display properly.

Edit Page:

Rule has been set.

![屏幕快照 2019-07-30 下午1 53 41](https://user-images.githubusercontent.com/52509957/62104323-d308f780-b2d1-11e9-9b2a-7b4f022e5d34.png)

Deployment Page:

Shows nothing.

![屏幕快照 2019-07-30 下午1 53 56](https://user-images.githubusercontent.com/52509957/62104343-e2884080-b2d1-11e9-9c49-0690bc59ee17.png)

**Comment by guoyk93** [comment] 2019-08-30 13:38
any update?

**Comment by tfiduccia** [comment] 2019-09-04 23:08
Version - master 9/4
I reproduced this in 2.2.8, but it looks like it's fixed and should be released with 2.3.
![image](https://user-images.githubusercontent.com/11514927/64298779-8dbc9300-cf2b-11e9-8774-ebab4a6e1d7e.png)

**Closed** 2019-09-04 23:08 UTC
