### ISSUE TITLE
apply-system-agent-upgrader is intermittently stuck in error/unavailable pod creation loop

### ISSUE THREAD

**Issue by jameson-mcghee** [rancher/rancher#40441] opened 2023-02-07 16:09 UTC
**Rancher Server Setup**
- Rancher version: `v2.7.0`
- Installation option (Docker install/Helm Chart): Both
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): K3s
- Proxy/Cert Details: N/A

**Information about the Cluster**
- Kubernetes version: `v1.24.9+rke2r2` and `1.24.9+k3s2`
- Cluster Type (Local/Downstream): Downstream
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider): Infrastructure Provider

**User Information**
- What is the role of the user logged in? (Admin/Cluster Owner/Cluster Member/Project Owner/Project Member/Custom) Admin and Standard

**Describe the bug**
When creating a node driver cluster, the `apply-system-agent-upgrader...` pods go into either an _error_ or _unavailable_ state

**To Reproduce**
1. Spin up a Rancher server
2. Provision a downstream Node Driver RKE2 cluster
3. Once provisioned, navigate to the _Pods_ for the cluster
  - It must be note that the error may be intermittent, so it may be necessary to repeat Steps 2 & 3 a number of times before observing the error

**Result**
Note that the  `apply-system-agent-upgrader...` pods will be in an _error_ or _unavailable_ state, and will continue to respin up new pods that will then error out.

**Expected Result**
The `apply-system-agent-upgrader...` pods spin up without error.

**Screenshots**
![image](https://user-images.githubusercontent.com/13294321/217296617-5853f737-95b5-4e76-95b6-d4112c7dad56.png)
![image](https://user-images.githubusercontent.com/13294321/217296638-06c687c2-8ae0-4f73-83cf-ba3d788e2a19.png)

**Additional context**
**`apply-system-agent-upgrader` Pod Logs:**
[apply-system-agent-upgrader-on-jrm270test401835-etcd-ac1e-snnql_upgrade.log](https://github.com/rancher/rancher/files/10677037/apply-system-agent-upgrader-on-jrm270test401835-etcd-ac1e-snnql_upgrade.log)

**Comment by sbstp** [comment] 2023-02-07 16:40
I'm not sure what's happening in the `amd64` case, but in the `arm64` case, the error that Josh had:
```
/usr/bin/kubectl: line 1: syntax error: unexpected redirection
```
Is caused by the fact that `curl` is downloading an XML document to `/usr/bin/kubectl` and then making that file executable. The `<` of the opening tag is interpreted as a bash redirection somehow. We get an XML document because the arch returned by `uname -m` is incompatible with the arch naming scheme Google uses for `kubectl`. You can see the 404 XML document [here](https://storage.googleapis.com/kubernetes-release/release/v1.24.0/bin/linux/aarch64/kubectl).

A PR with a fix for this is available here https://github.com/rancher/system-agent/pull/106

**Comment by Josh-Diamond** [comment] 2023-02-08 22:22
Ticket # 40441 - Test Results - ✅ 
---

With Docker on a single-node instance:

Verified on rancher `v2.7-0504ce63c1cad67b2c2be14a0325533b60902832-head`:
1. Fresh install of rancher `v2.7-head`
2. Provision a downstream K3s AWS Node driver cluster / arm64 infrastructure; k8s `v1.24.10+k3s1`
    - AMI: [`ami-0a9790c5a531163ee`/`ubuntu/images/hvm-ssd/ubuntu-jammy-22.04-arm64-server-20220912`]
    - Instance Type: [`a1.xlarge`]
3. Once `active`, navigate to `Cluster Explorer > Pods` and observe `apply-system-agent-upgrader` pod
4. Verified - `apply-system-agent-upgrader` pod is active and stable; clean logs

**Closed** 2023-02-09 16:30 UTC
Labels: kind/bug-qa, area/system-agent, team/area2, [zube]: Blocked
