### ISSUE TITLE
Not able to use container links in the docker-compose.yml when containers don't exist in the local machine.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#566] opened 2015-04-20 16:57 UTC
Server version - V0.16.3

Steps to reproduce the problem:

Create Environment.
Create a service with scale1 specifying the host (h1) in "Security/Host" section and having a link to container that is present in another host h2.

Activate service.

Use "Export Config" for Environment to generate the docker-compose.yml

Use this docker-compose.yml file to create the instances.

Following error is seen:

Sangeethas-MacBook-Pro:~ sangeethahariharan1$ docker-compose up
Creating sangeethahariharan1_test366326_1...
Could not get container for container2_link
Sangeethas-MacBook-Pro:~ sangeethahariharan1$

**Comment by vincent99** [comment] 2015-04-23 03:59
Duplicate of #567, which has comments...

**Comment by vincent99** [comment] 2015-04-23 04:01
Maybe not a duplicate, but these are very similar.. @sangeethah can you clarify the titles?

**Comment by sangeethah** [comment] 2015-04-23 18:32
@vincent99 , thanks for noticing this . I have changed the title for  #567 , to reflect the bug description which is about dataVolumesFrom link and not container link.

**Comment by deniseschannon** [comment] 2015-12-03 23:04
This is an issue with Docker as well, so we won't fix.

**Closed by deniseschannon** 2015-12-03 23:04 UTC
Labels: area/service, kind/bug, status/wontfix
