### ISSUE TITLE
Unable to see project members after upgrade.

### ISSUE THREAD

**Issue by mattmattox** [rancher/rancher#20760] opened 2019-06-10 20:59 UTC
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
- Setup Rancher HA cluster running v2.2.3
- Configure Active Directory authentication
- Grant permissions to AD users at the project level
- Upgrade Rancher to v2.2.4

**Result:**
- Users can still login but don't show up in member list in UI
- If you add a user and refresh the page the user shows up
- If you add a group and refresh the page the groups don't shows up
- Only the project level is impacted, cluster level is fine

**Other details that may be helpful:**
As part of troubleshooting, we cycled the Rancher containers with no joy.

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): v2.2.4
- Installation option (single install/HA): HA

**Comment by davidnuzik** [comment] 2019-06-10 21:17
Possibly duplicate of https://github.com/rancher/rancher/issues/20714 although that issue does not mention the groups not showing up.

**Comment by davidnuzik** [comment] 2019-06-10 22:17
I have replicated and can confirm exactly what is stated in the issue description. The API shows everything this is just a UI issue. I've updated my issue I mentioned in my last comment.
This happens on single-node rancher or HA and doesn't require an upgrade.

**Comment by marcinbojko** [comment] 2019-06-11 09:59
Same for HA

**Comment by trondhindenes** [comment] 2019-06-12 07:44
can repro. This is very bad, since there's no easy way to know what the access is for a cluster anymore. It would be awesome if a fix was fast-tracked

**Comment by basroovers** [comment] 2019-06-12 12:14
I experience the exact same thing. If I open up the logging I can see changes coming through and they function properly. But the project members are missing in the overview.

**Comment by pcolony** [comment] 2019-06-12 15:15
We experienced the same symptom after upgrading from 2.2.3 to 2.2.4 last week.  Adding LDAP groups (Active Directory) to Rancher Projects, they do not show up in the UI.  This was previously working for us.

Because we have enterprise support with Rancher, I have a case open and they're looking into it.

**Comment by cjellick** [comment] 2019-06-12 16:04
@davidnuzik can you test to see if this repros with github?

**Comment by davidnuzik** [comment] 2019-06-12 16:23
@cjellick I can confirm this also repros with GitHub authentication. So far confirmed that these providers are affected: AzureAD, Active Directory, GitHub, local accounts (users) both master (tracked in #20714) and v2.2.4 (this issue)

**Comment by davidnuzik** [comment] 2019-06-12 17:49
Closed #20714 (original issue) in favor of this issue (v2.3 milestone). See #20825 for backport (v2.2.5 milestone)

**Comment by davidnuzik** [comment] 2019-06-13 23:17
Version: v2.2.4 -> master (v2.3) (6/13/19) (upgrade)

I can confirm that members are now seen with a fresh install or post-upgrade (from v2.2.4). Also, groups now show up (they didn't at all before in v2.2.4).

This area was also smoke tested to ensure we didn't find any issues in related areas.
For version v2.2.5 release please see issue https://github.com/rancher/rancher/issues/20825

**Closed by davidnuzik** 2019-06-13 23:17 UTC
Labels: [zube]: To Test, area/ui, internal, team/ui
