### ISSUE TITLE
[Convoy-NFS] couldn't connect to NFS server

### ISSUE THREAD

**Issue by Kanshiroron** [rancher/rancher#3343] opened 2016-01-20 15:33 UTC
My bad...

**Comment by Kanshiroron** [comment] 2016-01-20 17:02
I actually do have an issue :)

This bug might be the same as [#3099](https://github.com/rancher/rancher/issues/3099)

I'm trying to connect to a NFS server with Convoy but the server refuses saying:
```
Jan 20 16:41:44 rancher-nfs rpc.mountd[18157]: refused mount request from 10.0.0.4 for / (/): not exported
Jan 20 16:41:47 rancher-nfs rpc.mountd[18157]: refused mount request from 10.0.0.3 for / (/): not exported
Jan 20 16:41:50 rancher-nfs rpc.mountd[18157]: refused mount request from 10.0.0.4 for / (/): not exported
```
Convoy-NFS agent logs:
```
Waiting for metadata.time="2016-01-20T16:56:34Z" level=info msg="Execing [/usr/bin/nsenter --mount=/proc/392/ns/mnt -F -- /var/lib/docker/aufs/mnt/824823ee0108e4744b78b2834aae451dd519f237951b54607f7fd95423499206/var/lib/rancher/convoy-agent/share-mnt --stage2 /var/lib/rancher/convoy/convoy-nfs-abb7e1d9-48e0-440a-95da-9e3658dcef58 -- /launch volume-agent-nfs-internal]" 
Registering convoy socket at /var/run/conoy-convoy-nfs.sock
Mounting at: /var/lib/rancher/convoy/convoy-nfs-abb7e1d9-48e0-440a-95da-9e3658dcef58/mnt
Mounting nfs. Command: mount -t nfs -o nfsvers=4 10.0.0.5:/ /var/lib/rancher/convoy/convoy-nfs-abb7e1d9-48e0-440a-95da-9e3658dcef58/mnt
mount.nfs: Operation not permitted
```

My NFS configuration should be very permissive:
`/etc/exports`
> /nfs    0.0.0.0/0.0.0.0(rw,sync,no_subtree_check,fsid=0)

`/etc/hosts.allow`
> rpcbind: ALL

I am able to mount the NFS storage on the node whith command `mount -t nfs 10.0.0.5:/ /mnt/`, and also if I launch the Convoy-nfs-agent with the option `--net=host`.

Here is my config:
rancher/convoy-agent:v0.2.0
Rancher v0.51.0
Cattle v0.130.0
User Interface v0.78.0
Rancher Compose v0.7.0
Docker 1.9.1
nfs-kernel-server v1.2.8

**Comment by cjellick** [comment] 2016-01-20 17:59
@Kanshiroron this:
> /nfs 0.0.0.0/0.0.0.0(rw,sync,no_subtree_check,fsid=0)
indicates that you are exporting the `/nfs` directory, not `/. I think you need to deploy convoy-nfs with `/nfs` as the path, no?

**Comment by Kanshiroron** [comment] 2016-01-21 10:09
Hello @cjellick,
Thanks for your answer. I actually tried with /nfs instead but it's not working either.
But since I added the option `fsid=0` in `/etc/exports` it should be `/`
Also, I was able to mount the NFS volume with the following command:
```
mount -t nfs 10.0.0.5:/ /mnt/
```

Thanks for your help,
Best regards

**Comment by cjellick** [comment] 2016-03-10 16:40
@Kanshiroron sorry for no response in such a long time. Did you ever figure out your issue here? If not, I'll be digging into this issue to see if I can repro.

**Comment by cjellick** [comment] 2016-03-10 17:19
Possibly related to the fact that the source port gets changed because of NAT. I'll be working on a solution to fix that.

**Comment by cjellick** [comment] 2016-03-12 23:42
I believe this is a dupe of #3099. I'm going to close this in favor of that one @Kanshiroron.

**Closed by cjellick** 2016-03-12 23:42 UTC
Labels: area/storage, kind/bug, release/v1.0.0
