### ISSUE TITLE
LoadBalancer and Access Logs

### ISSUE THREAD

**Issue by Daxten** [rancher/rancher#5538] opened 2016-07-25 11:26 UTC
Aggregating all issues here about the LB, I can't find a sane way to make access logs available on the load balancer.

Any one can help me with this? (specially making them available in the log stream of docker and / or pushing it to an ELK Stack)

i think the documentation could be updated about this also, since access logs seem to be quite important (of course one option would be to proxy the request through one more application, but is that really the solution?)

**Comment by deniseschannon** [comment] 2016-07-26 18:48
Duplicate of https://github.com/rancher/rancher/issues/2414

**Closed by deniseschannon** 2016-07-26 18:48 UTC
