### ISSUE TITLE
[Logging v2] Support hardened cluster

### ISSUE THREAD

**Issue by izaac** [rancher/rancher#28620] opened 2020-08-28 19:34 UTC
**What kind of request is this:**
bug

**Steps to reproduce:**

- Configure a custom hardened cluster **cis-1.5 hardened profile**
- Deploy the `rancher-logging` App from Dashbaord

**Result:**

Fluentbit pods failed to deploy

```
Error creating: pods "rancher-logging-fluentbit-" is forbidden: unable to validate against any pod security policy: [spec.volumes[0]: Invalid value: "hostPath": hostPath volumes are not allowed to be used spec.volumes[1]: Invalid value: "hostPath": hostPath volumes are not allowed to be used]	a few seconds ago
Warning	FailedCreate	Error creating: pods "rancher-logging-fluentbit-" is forbidden: unable to validate against any pod security policy: []
```

**Other details that may be helpful:**

**Environment information**
- Rancher version: `v2.5-alpha1 (08/28/2020)`
- Installation option : HA k8s

**Cluster information**
- Cluster type : Custom
- Machine type (cloud/VM/metal) and specifications (CPU/memory): VM t3a.medium AWS
- Kubernetes version (use `kubectl version`): v1.18.6-rancher1-2

**Comment by paynejacob** [comment] 2020-09-10 16:16
Adding the following psp https://gist.github.com/paynejacob/fe0d62b94aca86e22d3ef31b2bd78271 gets past the errors but causes a nil pointer error in the operator.  I am waiting until https://github.com/rancher/charts/pull/608 is merged before investigating further.

**Comment by deniseschannon** [comment] 2020-12-23 13:24
Duplicate of https://github.com/rancher/rancher/issues/29371, but leaving open cause it contains good info

**Comment by superseb** [comment] 2022-06-03 13:54
Can this be retested on current version?

**Comment by ronhorton** [comment] 2022-10-25 18:35
**PASS** verified in `2.7-head commit id 9e7e4bc`
1. installed logging on hardened cluster
2. created secret
3. created cluster output - elasticsearch
4. created cluster flow 
`logs flowing to elasticsearch from hardened cluster`
also verified configchecks for logging had completed - all workloads running - no errors. 
checked local cluster rancher logs for errors - none. 

CIS scan testing in https://github.com/rancher/rancher/issues/29372

![2022-10-25_14-30-27](https://user-images.githubusercontent.com/89212856/197854313-bbc35bf2-ed71-4fa8-b0f6-b0030e99a9b6.png)

**Closed** 2022-10-25 18:51 UTC
Labels: area/logging, kind/bug-qa, [zube]: QA Working, team/area3
