### ISSUE TITLE
Unable to set up Rancher Keycloak SAML auth

### ISSUE THREAD

**Issue by klainte** [rancher/rancher#16004] opened 2018-10-08 16:55 UTC
Hi there,

**Rancher versions:**
rancher/rancher:latest (v2.1)

**Infrastructure Stack versions:**
kubernetes: 1.10.7_1521

**Docker version:**
```
Server Version: 18.03.1-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 773c489c9c1b21a6d78b5c538cd395416ec50f88
runc version: 4fc53a81fb7c994640722ac585fa9ca548971871
init version: 949e6fa
Kernel Version: 3.10.0-693.21.1.el7.x86_64
Operating System: CentOS Linux 7 (Core)
```

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
Ref to Docker info above

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
Other (Virtual Server)

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
Single node, internal DB

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**
k8s

**Steps to Reproduce:**
Go to https://<your_rancher_url>/g/security/authentication/keycloak
Fill the form according to https://rancher.com/docs/rancher/v2.x/en/admin-settings/authentication/keycloak/

My setup:
- Display Name Field = cn
- User Name Field = givenname
- UID Field = uid
- Groups Field =  memberof
- Rancher API Host = https://<my_rancher_url> 
- And private key + cert + Metada xml from Keycloak
Then click on "Authenticate with Keycloak"

**Expected Results:**
As suggested by Rancher, you should be redirected to Keycloak's login page (pop-up)

**Actual Results:**
A new window pops up, however you are not redirected to Keycloak's login page but end up on the same URL https://<my_rancher_url>/g/security/authentication/keycloak?RelayState=<really_long_saml_stuff>

**Additional observations.**
Few things I noticed:
1. The SAML request is never sent to my keycloak server
2. If I compare the SAML GET request from Rancher to a valid SAML GET request from another app, I can see there is no "Destination" attribute in the AuthnRequest tag
```xml
<?xml version="1.0" encoding="UTF-8"?>
<samlp:AuthnRequest xmlns:samlp="urn:oasis:names:tc:SAML:2.0:protocol" xmlns:saml="urn:oasis:names:tc:SAML:2.0:assertion" ID="id-60618df5801f187f14af8922069e14379b4a3c52" Version="2.0" IssueInstant="2018-10-08T16:09:14.257Z" AssertionConsumerServiceURL="https://my_rancher_url/v1-saml/keycloak/saml/acs" ProtocolBinding="urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST">
   <saml:Issuer Format="urn:oasis:names:tc:SAML:2.0:nameid-format:entity">https://my_rancher_url/v1-saml/keycloak/saml/metadata</saml:Issuer>
   <samlp:NameIDPolicy Format="urn:oasis:names:tc:SAML:2.0:nameid-format:transient" AllowCreate="true" />
</samlp:AuthnRequest>
```
Which might explain 1.
3. If I compare this request to another valid request, I can see the missing "Destination" attribute
```xml
<?xml version="1.0" encoding="UTF-8"?>
<samlp:AuthnRequest xmlns:samlp="urn:oasis:names:tc:SAML:2.0:protocol" xmlns:saml="urn:oasis:names:tc:SAML:2.0:assertion" AssertionConsumerServiceURL="myACS_URL" Destination="https://my_keycloak/auth/realms/my_realm/protocol/saml" ID="_4a3d5f17-d8c6-41e5-8393-d5b6e03a73e5" IssueInstant="2018-10-08T16:10:35Z" Version="2.0">
   <saml:Issuer>my_issuer</saml:Issuer>
   <samlp:NameIDPolicy AllowCreate="true" Format="urn:oasis:names:tc:SAML:1.1:nameid-format:emailAddress" />
</samlp:AuthnRequest>
```
4. Contrary to all application for which I set up a SAML auth with Keycloak, I did not provide the "Identity provider SSO URL" to Rancher, even if this information is available in the metadata.xml file provided to Rancher. For ref, the metadata.xml I provided:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<EntityDescriptor entityID="https://mykeycloak/auth/realms/my_realm"
                   xmlns="urn:oasis:names:tc:SAML:2.0:metadata"
                   xmlns:dsig="http://www.w3.org/2000/09/xmldsig#"
                   xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
   <IDPSSODescriptor WantAuthnRequestsSigned="true"
      protocolSupportEnumeration="urn:oasis:names:tc:SAML:2.0:protocol">
      <SingleLogoutService
         Binding="urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST"
         Location="https://mykeycloak/auth/realms/my_realm/protocol/saml" />
   <NameIDFormat>urn:oasis:names:tc:SAML:2.0:nameid-format:persistent</NameIDFormat>
   <NameIDFormat>urn:oasis:names:tc:SAML:2.0:nameid-format:transient</NameIDFormat>
   <NameIDFormat>urn:oasis:names:tc:SAML:1.1:nameid-format:unspecified</NameIDFormat>
   <NameIDFormat>urn:oasis:names:tc:SAML:1.1:nameid-format:emailAddress</NameIDFormat>

      <SingleSignOnService Binding="urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST"
         Location="https://mykeycloak/auth/realms/my_realm/protocol/saml" />
      <KeyDescriptor use="signing">
        <dsig:KeyInfo>
          <dsig:KeyName>key_name</dsig:KeyName>
          <dsig:X509Data>
            <dsig:X509Certificate>my_cert</dsig:X509Certificate>
          </dsig:X509Data>
        </dsig:KeyInfo>
      </KeyDescriptor>
   </IDPSSODescriptor>
</EntityDescriptor>
```
Maybe that's just a configuration issue on my side.
I'll gladly submit a PR on Rancher documentation regarding Keycloak conf when I figure this out.

**Comment by gotoadmin** [comment] 2018-10-09 14:03
Same issue on my end - not being redirected to keycloak.

**Comment by commiaI** [comment] 2018-10-19 09:20
Same issue ... have you resolved it ?

**Comment by klainte** [comment] 2018-10-19 13:15
Not resolved on my side, I tried many different configuration options, without success so far.
I just configured Sonar + with Keycloak SAML auth in 5 min without any issue.

Let's hope someone from Rancher's team will take a look at this.

**Comment by loganhz** [comment] 2018-10-19 15:43
Thanks for your report!
We will look at it and if it is a bug, we will try to fix it in 2.1.2

**Comment by mrajashree** [comment] 2018-10-19 17:30
@klainte It looks like there is no entry for HTTP-redirect binding in your IdP's metadata. This could happen if on your Keycloak client you have `Force POST Binding` set to true. Can you please disable it and then try? So that the redirect binding will be enabled and used?

**Comment by commiaI** [comment] 2018-10-22 06:18
Redirection works with these settings. However, once authenticated to keycloak, I have a 403 - forbidden. An idea of ​​the problem? Problem with the registered user? Certificate validation problem? Another problem?
Thanks again for the help

**Comment by klainte** [comment] 2018-10-22 06:37
@mrajashree Perfect, that's working, thanks a lot! I tried so many different conf and somehow I managed not to try with "Force post binding" turned off, shame on me. As I said before, I'll gladly submit a PR to improve the documentation regarding SAML setup for Keycloak. Do you want me to close this issue anyway and submit the PR later?

@commiaI I received a notif from you, if you get a 403, check your Keycloak logs, you might have the wrong ClientID in Keycloak. The expected one is:
clientId=https://<your_rancher_url>/v1-saml/keycloak/saml/metadata

**Comment by commiaI** [comment] 2018-10-22 07:03
All is good keycloak side, no error, the forbidden is displayed once redirected to rancher

**Comment by klainte** [comment] 2018-10-22 13:12
@commiaI I can replicate the "forbidden" issue when I enter a wrong certificate in rancher (e.g. when I change a ramdom letter in it). Maybe you made a typo?

**Comment by alena1108** [comment] 2018-10-22 19:02
Have to document that for keycloak following has to be configured on the IDP side:

```
Client Signature Required: OFF
Force POST Binding: OFF
Valid Redirect URIs: in the format of https://yourRancherHostURL/v1-saml/keycloak/saml/acs
IDP Initiated SSO URL Name: IdPSSOName
Base URL: /auth/realms/amp/protocol/saml/clients/IdPSSOName
```

**Comment by commiaI** [comment] 2018-10-22 19:50
Normally i imported the certificate and key from a file. I have specially generated them with the command in the documentation. Maybe as problem is here? Should they have some link with keycloak?

**Comment by mrajashree** [comment] 2018-10-23 14:02
@commiaI Can you please ensure that these 2 fields are set correctly?
```
Valid Redirect URIs: in the format of https://yourRancherHostURL/v1-saml/keycloak/saml/acs
Fine Grain SAML Endpoint Configuration -> Assertion Consumer Service POST Binding URL: in the form of https://yourRancherHostURL/v1-saml/keycloak/saml/acs
```

**Comment by klainte** [comment] 2018-10-23 15:18
@commiaI I just tried generating a cert using the command from the documentation
``` 
openssl req -x509 -sha256 -nodes -days 365 -newkey rsa:2048 -keyout myservice.key -out myservice.cert
```
All parameters set to default (basically hit enter at each question), pasting the key and cert in Rancher and it's working just fine.

**Comment by mrajashree** [comment] 2018-10-23 17:56
@commiaI okay, can you also enable `Include AuthnStatement` and try? If the error still persists, can you share debug logs? These instructions show how to enable debug logs https://rancher.com/docs/rancher/v2.x/en/faq/technical/#how-can-i-enable-debug-logging

If you still get 403, in your debug logs, there would be a message of the form `RESPONSE: ===`, followed by `ERROR`. Can you please share these?

**Comment by klainte** [comment] 2018-10-25 15:59
@mrajashree I have a few more observations. If I sum this up, SAML auth is working if
- Either "Sign Documents" or "Sign assertions" set to **ON**, if both are ON, it's fine too. If not, it triggers "ERROR: either the Response or Assertion must be signed" in Rancher Debug Log
- All other options set to **OFF**
- ClientID = https://yourRancherHostURL/v1-saml/keycloak/saml/metadata
- Valid Redirect URIs = https://yourRancherHostURL/v1-saml/keycloak/saml/acs
This is the simplest working setup I tested.

You do not need to set ACS Post Binding URL, IDP Initiated SSO URL Name or Base URL unless you want to setup IDP Initiated SSO.

Strange thing though, when I log in to Rancher using Keycloak, my user is not "created". Actually I am being logged as the user admin. Is that the expected behavior, or did I miss something? For now my Site Access is set to "Allow any valid Users".

**Comment by mrajashree** [comment] 2018-10-25 17:58
Hi @klainte you being logged as the admin user is the expected behavior. This doc explains the behavior https://rancher.com/docs/rancher/v2.x/en/admin-settings/authentication/#external-authentication-configuration-and-principal-users

Thanks for testing the exact configuration that worked. Like you said earlier, if you want to open a PR for docs with this information we'll be glad to review and get it merged

**Comment by klainte** [comment] 2018-10-26 09:13
@mrajashree Thanks for the additional documentation link.
PR submitted (https://github.com/rancher/docs/pull/951).

Also, I did try to setup IDP Initiated SSO, but got an error in Rancher (ERROR: InResponseTo does not match any of the possible request IDs (expected [])). I will open a new issue for this.

**Comment by PhilsLab** [comment] 2018-11-29 11:37
I'm unable to fix this issue with my installation, even after changing the documented settings.
Also, the documentation is missing that Rancher does not accept the key formated which keycloak generates by default.
Is there any chance this will be fixed _including_ client signature validation?

**Comment by mrajashree** [comment] 2019-01-15 16:21
Closing this since the docs PR is merged

**Closed by mrajashree** 2019-01-15 16:21 UTC
Labels: area/access-control, area/documentation, status/resolved, version/2.0

**Comment by 46602907** [comment] 2019-11-22 06:57
> correctly

看到你keycloak上的配置了，想咨询一下在rancher上应该如何对应呢。 Display Name Field，User Name Field ，UID Field ，Groups Field  分别在Rancher 上填写什么，对应keycloak 哪里的字段呢

**Comment by 46602907** [comment] 2019-11-22 08:40
![image](https://user-images.githubusercontent.com/13148354/69410619-61ecc480-0d46-11ea-93e3-723dc1c05475.png)
2019/11/22 16:39:01 [DEBUG] NodeController calling handler cluster-monitoring-sync-windows-node-handler cn-shanghai.192.168.10.242
2019/11/22 16:39:01 [DEBUG] RESPONSE: ===
<samlp:Response xmlns:samlp="urn:oasis:names:tc:SAML:2.0:protocol" xmlns:saml="urn:oasis:names:tc:SAML:2.0:assertion" Destination="https://rhadm.efotile.com/v1-saml/keycloak/saml/acs" ID="ID_10dd0643-ae20-472b-bfd3-33ffe065ac6d" InResponseTo="id-0bc54bd81efd448c646ecb32204369c8c3f71405" IssueInstant="2019-11-22T08:39:01.505Z" Version="2.0"><saml:Issuer>https://hsadmin.fotile.com/auth/realms/fcloud</saml:Issuer><dsig:Signature xmlns:dsig="http://www.w3.org/2000/09/xmldsig#"><dsig:SignedInfo><dsig:CanonicalizationMethod Algorithm="http://www.w3.org/2001/10/xml-exc-c14n#"/><dsig:SignatureMethod Algorithm="http://www.w3.org/2001/04/xmldsig-more#rsa-sha256"/><dsig:Reference URI="#ID_10dd0643-ae20-472b-bfd3-33ffe065ac6d"><dsig:Transforms><dsig:Transform Algorithm="http://www.w3.org/2000/09/xmldsig#enveloped-signature"/><dsig:Transform Algorithm="http://www.w3.org/2001/10/xml-exc-c14n#"/></dsig:Transforms><dsig:DigestMethod Algorithm="http://www.w3.org/2001/04/xmlenc#sha256"/><dsig:DigestValue>jxITqO/Q/TqWEKM5tsCAgiw2Pk6AJNqQ80KP3SOCUgU=</dsig:DigestValue></dsig:Reference></dsig:SignedInfo><dsig:SignatureValue>fYAM2zWiWC0nTymN/5GCaV5RopyZpjpXyOEqIkjfIxZ0DYL+RpeF+Ci95LO51uE8U7FGhZMtqu/t0g3c8sLeib7h1KrC0neFq21PF7c2e40mrvGS6kwG+R5STx0mLQuadX7lIzKLTtsIL+26p6knmfVxB4trJRaR7tdEFHDOJoJQ/dbDISx1srJQlqEgmDJ4cfHUd1kQNfR4HtrzYVxjRJR74Eg0rYl11atyR7E5TMfLQjUnrg0/1ZB9VFRP5/ojyaNoaSEWLvHZ3vXnHuAsbHqyk+weZpkG9LHC2CHpa+GHqPqB1fCQCrvuwwvMHKPVLZbekue3OhqULrXMbJnFMw==</dsig:SignatureValue><dsig:KeyInfo><dsig:KeyName>OuGNXXs0bD0U7RF_fJ4xxAzeNdCcVyatd567i057ZJw</dsig:KeyName><dsig:X509Data><dsig:X509Certificate>MIICmzCCAYMCBgFoE8n7zzANBgkqhkiG9w0BAQsFADARMQ8wDQYDVQQDDAZmY2xvdWQwHhcNMTkwMTAzMTI1NTMwWhcNMjkwMTAzMTI1NzEwWjARMQ8wDQYDVQQDDAZmY2xvdWQwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQCcEXdaTigrN3bQ7S6itiUabNlE5OifOjHbhwwhetdRg9ClsPjK6295fRe3gUDYfUjB6P7er42YhX4aVLnG4oDGxVS6bWXJKK4lJfdM0gsrhxMrkoMexgGy8YfnwVKgmEXv286uXAx/YyMahI2A+aQZjD17dCUuwMkJumWFaHds84zuufSVjKRfOIsCYwSHRSn8285IB1N5kXZ7sCMEJ7wI2+BfLEgE551A+Md
HTtc0icmpWEh3B+k2R5frYKKNEwLHueq3cy6zM/g8C8pCfbjq1/Q6lFsUZtkFmtffTrKjfPi/mODmzP6HFfCOB3bp/1EleOitOoBSxRM5nLhji8rbAgMBAAEwDQYJKoZIhvcNAQELBQADggEBAD7a67tp6/edkjppfnEuMS3m4bww24l7EewegXxIAQIrSCJtognHWIUmUfqmhng+Dg/sEVWKNvX9k7lsUtdwrvIe4CpY/4VLIupS8CPuSWkb6sY20VIXtGSD4u3VPseTkUZiLz+Y9cFjI7SwQsmW8Cqs+jxqZu1bfcdbuOFT8675qbKRZP6rh2XuRBcU0bqdThbrIzJDqOf0pzljvaepTlXpRwQrMAV5QabG3WN15fr8n/pnePvaPEsHXpcq8qVeUVZQyabHUWLaVg0kcXOOf4gt8tUegrSietD56ms2PWkKrgKtPZ9cqKdLYsid9ujxukKaS05nKABB4Z0t4i3mNA8=</dsig:X509Certificate></dsig:X509Data><dsig:KeyValue><dsig:RSAKeyValue><dsig:Modulus>nBF3Wk4oKzd20O0uorYlGmzZROTonzox24cMIXrXUYPQpbD4yutveX0Xt4FA2H1Iwej+3q+NmIV+GlS5xuKAxsVUum1lySiuJSX3TNILK4cTK5KDHsYBsvGH58FSoJhF79vOrlwMf2MjGoSNgPmkGYw9e3QlLsDJCbplhWh3bPOM7rn0lYykXziLAmMEh0Up/NvOSAdTeZF2e7AjBCe8CNvgXyxIBOedQPjHR07XNInJqVhIdwfpNkeX62CijRMCx7nqt3MuszP4PAvKQn246tf0OpRbFGbZBZrX306yo3z4v5jg5sz+hxXwjgd26f9RJXjorTqAUsUTOZy4Y4vK2w==</dsig:Modulus><dsig:Exponent>AQAB</dsig:Exponent></dsig:RSAKeyValue></dsig:KeyValue></dsig:KeyInfo></dsig:Signature><samlp:Status><samlp:StatusCode Value="urn:oasis:names:tc:SAML:2.0:status:Success"/></samlp:Status><saml:Assertion xmlns="urn:oasis:names:tc:SAML:2.0:assertion" ID="ID_84fabe8d-6d40-465e-ac59-0da5faed0ea3" IssueInstant="2019-11-22T08:39:01.505Z" Version="2.0"><saml:Issuer>https://hsadmin.fotile.com/auth/realms/fcloud</saml:Issuer><dsig:Signature xmlns:dsig="http://www.w3.org/2000/09/xmldsig#"><dsig:SignedInfo><dsig:CanonicalizationMethod Algorithm="http://www.w3.org/2001/10/xml-exc-c14n#"/><dsig:SignatureMethod Algorithm="http://www.w3.org/2001/04/xmldsig-more#rsa-sha256"/><dsig:Reference URI="#ID_84fabe8d-6d40-465e-ac59-0da5faed0ea3"><dsig:Transforms><dsig:Transform Algorithm="http://www.w3.org/2000/09/xmldsig#enveloped-signature"/><dsig:Transform Algorithm="http://www.w3.org/2001/10/xml-exc-c14n#"/></dsig:Transforms><dsig:DigestMethod Algorithm="http://www.w3.org/2001/04/xmlenc#sha256"/><dsig:DigestValue>hMGvnlofG68vfkbxVU9clFgDQJtwH9v1jG1HZD+JG0g=</dsig:DigestValue></dsig:Reference></dsig:Signe
dInfo><dsig:SignatureValue>HTsUHs8wYALzwRkC6kxLDcKK9yNytWHxDm6YtNZYwqhuwZWG3aOXSI/x3AiT2DncrymrQbZmfV5z6R+JcY4/EQFjARXR2/5V/0ddqtfNrQ0FyTHliUV11qM9X+oDV5bx5Wy1dwBixOG4Fn8WgJOGtkdXeRTZzD/8hr933Etu++V6TRR+I+R9+EDPxqcKjE6AUmcKB7z8fvRuGWsFkNnMBXw9uGoJ9ISO3AO4dZ4mpV6I73p2H99b8dcQgruypBdGyOXBLw7PQMDFFAC82xFgDXMMknCIYHSM7mAHqZa4cwiVEL7+PXa2u9ZTZR2W6SfdFqikbK11+4HUeI6DNJJbxQ==</dsig:SignatureValue><dsig:KeyInfo><dsig:KeyName>OuGNXXs0bD0U7RF_fJ4xxAzeNdCcVyatd567i057ZJw</dsig:KeyName><dsig:X509Data><dsig:X509Certificate>MIICmzCCAYMCBgFoE8n7zzANBgkqhkiG9w0BAQsFADARMQ8wDQYDVQQDDAZmY2xvdWQwHhcNMTkwMTAzMTI1NTMwWhcNMjkwMTAzMTI1NzEwWjARMQ8wDQYDVQQDDAZmY2xvdWQwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQCcEXdaTigrN3bQ7S6itiUabNlE5OifOjHbhwwhetdRg9ClsPjK6295fRe3gUDYfUjB6P7er42YhX4aVLnG4oDGxVS6bWXJKK4lJfdM0gsrhxMrkoMexgGy8YfnwVKgmEXv286uXAx/YyMahI2A+aQZjD17dCUuwMkJumWFaHds84zuufSVjKRfOIsCYwSHRSn8285IB1N5kXZ7sCMEJ7wI2+BfLEgE551A+MdHTtc0icmpWEh3B+k2R5frYKKNEwLHueq3cy6zM/g8C8pCfbjq1/Q6lFsUZtkFmtffTrKjfPi/mODmzP6HFfCOB3bp/1EleOitOoBSxRM5nLhji8rbAgMBAAEwDQYJKoZIhvcNAQELBQADggEBAD7a67tp6/edkjppfnEuMS3m4bww24l7EewegXxIAQIrSCJtognHWIUmUfqmhng+Dg/sEVWKNvX9k7lsUtdwrvIe4CpY/4VLIupS8CPuSWkb6sY20VIXtGSD4u3VPseTkUZiLz+Y9cFjI7SwQsmW8Cqs+jxqZu1bfcdbuOFT8675qbKRZP6rh2XuRBcU0bqdThbrIzJDqOf0pzljvaepTlXpRwQrMAV5QabG3WN15fr8n/pnePvaPEsHXpcq8qVeUVZQyabHUWLaVg0kcXOOf4gt8tUegrSietD56ms2PWkKrgKtPZ9cqKdLYsid9ujxukKaS05nKABB4Z0t4i3mNA8=</dsig:X509Certificate></dsig:X509Data><dsig:KeyValue><dsig:RSAKeyValue><dsig:Modulus>nBF3Wk4oKzd20O0uorYlGmzZROTonzox24cMIXrXUYPQpbD4yutveX0Xt4FA2H1Iwej+3q+NmIV+GlS5xuKAxsVUum1lySiuJSX3TNILK4cTK5KDHsYBsvGH58FSoJhF79vOrlwMf2MjGoSNgPmkGYw9e3QlLsDJCbplhWh3bPOM7rn0lYykXziLAmMEh0Up/NvOSAdTeZF2e7AjBCe8CNvgXyxIBOedQPjHR07XNInJqVhIdwfpNkeX62CijRMCx7nqt3MuszP4PAvKQn246tf0OpRbFGbZBZrX306yo3z4v5jg5sz+hxXwjgd26f9RJXjorTqAUsUTOZy4Y4vK2w==</dsig:Modulus><dsig:Exponent>AQAB</dsig:Exponent></dsig:RSAKeyValue></dsig:KeyValue></dsig:KeyInfo></dsig:Signature><saml:Subject><saml:NameID Format="urn:oasis:names:tc:SAML:2.0:nameid-format:transient">G
-1bfdee87-1aa3-4fbe-b4cd-d1ed12d83c1e</saml:NameID><saml:SubjectConfirmation Method="urn:oasis:names:tc:SAML:2.0:cm:bearer"><saml:SubjectConfirmationData InResponseTo="id-0bc54bd81efd448c646ecb32204369c8c3f71405" NotOnOrAfter="2019-11-02T15:36:12.209Z" Recipient="https://rhadm.efotile.com/v1-saml/keycloak/saml/acs"/></saml:SubjectConfirmation></saml:Subject><saml:Conditions NotBefore="2019-11-22T08:38:59.505Z" NotOnOrAfter="2019-11-02T15:36:12.209Z"><saml:AudienceRestriction><saml:Audience>https://rhadm.efotile.com/v1-saml/keycloak/saml/metadata</saml:Audience></saml:AudienceRestriction></saml:Conditions><saml:AttributeStatement><saml:Attribute FriendlyName="id" Name="id" NameFormat="urn:oasis:names:tc:SAML2.0:attrname-format:unspecified"><saml:AttributeValue xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:type="xs:string">b125826a-4cf6-4fb8-b652-98d96ebffbc0</saml:AttributeValue></saml:Attribute><saml:Attribute FriendlyName="cn" Name="cn" NameFormat="urn:oasis:names:tc:SAML2.0:attrname-format:unspecified"><saml:AttributeValue xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:type="xs:string">江文奇</saml:AttributeValue></saml:Attribute><saml:Attribute FriendlyName="username" Name="username" NameFormat="urn:oasis:names:tc:SAML2.0:attrname-format:unspecified"><saml:AttributeValue xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:type="xs:string">jiangwq</saml:AttributeValue></saml:Attribute><saml:Attribute Name="Role" NameFormat="urn:oasis:names:tc:SAML:2.0:attrname-format:basic"><saml:AttributeValue xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:type="xs:string">view-authorization</saml:AttributeValue></saml:Attribute><saml:Attribute Name="Role" NameFormat="urn:oasis:names:tc:SAML:2.0:attrname-format:basic"><saml:AttributeValue xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2
001/XMLSchema-instance" xsi:type="xs:string">query-groups</saml:AttributeValue></saml:Attribute><saml:Attribute Name="Role" NameFormat="urn:oasis:names:tc:SAML:2.0:attrname-format:basic"><saml:AttributeValue xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:type="xs:string">query-users</saml:AttributeValue></saml:Attribute><saml:Attribute Name="Role" NameFormat="urn:oasis:names:tc:SAML:2.0:attrname-format:basic"><saml:AttributeValue xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:type="xs:string">view-clients</saml:AttributeValue></saml:Attribute><saml:Attribute Name="Role" NameFormat="urn:oasis:names:tc:SAML:2.0:attrname-format:basic"><saml:AttributeValue xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:type="xs:string">view-profile</saml:AttributeValue></saml:Attribute><saml:Attribute Name="Role" NameFormat="urn:oasis:names:tc:SAML:2.0:attrname-format:basic"><saml:AttributeValue xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:type="xs:string">manage-events</saml:AttributeValue></saml:Attribute><saml:Attribute Name="Role" NameFormat="urn:oasis:names:tc:SAML:2.0:attrname-format:basic"><saml:AttributeValue xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:type="xs:string">query-realms</saml:AttributeValue></saml:Attribute><saml:Attribute Name="Role" NameFormat="urn:oasis:names:tc:SAML:2.0:attrname-format:basic"><saml:AttributeValue xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:type="xs:string">manage-realm</saml:AttributeValue></saml:Attribute><saml:Attribute Name="Role" NameFormat="urn:oasis:names:tc:SAML:2.0:attrname-format:basic"><saml:AttributeValue xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:type="xs:string">offline_access</saml:Attribut
eValue></saml:Attribute><saml:Attribute Name="Role" NameFormat="urn:oasis:names:tc:SAML:2.0:attrname-format:basic"><saml:AttributeValue xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:type="xs:string">read-token</saml:AttributeValue></saml:Attribute><saml:Attribute Name="Role" NameFormat="urn:oasis:names:tc:SAML:2.0:attrname-format:basic"><saml:AttributeValue xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:type="xs:string">realm-admin</saml:AttributeValue></saml:Attribute><saml:Attribute Name="Role" NameFormat="urn:oasis:names:tc:SAML:2.0:attrname-format:basic"><saml:AttributeValue xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:type="xs:string">manage-account-links</saml:AttributeValue></saml:Attribute><saml:Attribute Name="Role" NameFormat="urn:oasis:names:tc:SAML:2.0:attrname-format:basic"><saml:AttributeValue xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:type="xs:string">view-identity-providers</saml:AttributeValue></saml:Attribute><saml:Attribute Name="Role" NameFormat="urn:oasis:names:tc:SAML:2.0:attrname-format:basic"><saml:AttributeValue xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:type="xs:string">manage-users</saml:AttributeValue></saml:Attribute><saml:Attribute Name="Role" NameFormat="urn:oasis:names:tc:SAML:2.0:attrname-format:basic"><saml:AttributeValue xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:type="xs:string">manage-account</saml:AttributeValue></saml:Attribute><saml:Attribute Name="Role" NameFormat="urn:oasis:names:tc:SAML:2.0:attrname-format:basic"><saml:AttributeValue xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:type="xs:string">view-users</saml:AttributeValue></saml:Attribute><saml:Attribute Name="Role" NameFo
rmat="urn:oasis:names:tc:SAML:2.0:attrname-format:basic"><saml:AttributeValue xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:type="xs:string">manage-authorization</saml:AttributeValue></saml:Attribute><saml:Attribute Name="Role" NameFormat="urn:oasis:names:tc:SAML:2.0:attrname-format:basic"><saml:AttributeValue xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:type="xs:string">超级管理员</saml:AttributeValue></saml:Attribute><saml:Attribute Name="Role" NameFormat="urn:oasis:names:tc:SAML:2.0:attrname-format:basic"><saml:AttributeValue xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:type="xs:string">query-clients</saml:AttributeValue></saml:Attribute><saml:Attribute Name="Role" NameFormat="urn:oasis:names:tc:SAML:2.0:attrname-format:basic"><saml:AttributeValue xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:type="xs:string">manage-identity-providers</saml:AttributeValue></saml:Attribute><saml:Attribute Name="Role" NameFormat="urn:oasis:names:tc:SAML:2.0:attrname-format:basic"><saml:AttributeValue xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:type="xs:string">manage-clients</saml:AttributeValue></saml:Attribute><saml:Attribute Name="Role" NameFormat="urn:oasis:names:tc:SAML:2.0:attrname-format:basic"><saml:AttributeValue xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:type="xs:string">uma_authorization</saml:AttributeValue></saml:Attribute><saml:Attribute Name="Role" NameFormat="urn:oasis:names:tc:SAML:2.0:attrname-format:basic"><saml:AttributeValue xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:type="xs:string">impersonation</saml:AttributeValue></saml:Attribute><saml:Attribute Name="Role" NameFormat="urn:oasis:names:tc:SAML:2.0:attrnam
e-format:basic"><saml:AttributeValue xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:type="xs:string">view-events</saml:AttributeValue></saml:Attribute><saml:Attribute Name="Role" NameFormat="urn:oasis:names:tc:SAML:2.0:attrname-format:basic"><saml:AttributeValue xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:type="xs:string">view-realm</saml:AttributeValue></saml:Attribute><saml:Attribute Name="Role" NameFormat="urn:oasis:names:tc:SAML:2.0:attrname-format:basic"><saml:AttributeValue xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:type="xs:string">create-client</saml:AttributeValue></saml:Attribute></saml:AttributeStatement></saml:Assertion></samlp:Response>
===
NOW: 2019-11-22 08:39:01.661787053 +0000 UTC
ERROR: assertion invalid: SubjectConfirmationData is expired
![image](https://user-images.githubusercontent.com/13148354/69410770-a7a98d00-0d46-11ea-9c37-2f66e1f088f4.png)

**Comment by 46602907** [comment] 2019-11-22 10:58
我找到了，是keycloak5.0.0 的bug.
![image](https://user-images.githubusercontent.com/13148354/69420671-147a5280-0d5a-11ea-9a3b-02ea0dee353e.png)
