### ISSUE TITLE
RTNETLINK error in Rancher logs

### ISSUE THREAD

**Issue by sshipway** [rancher/rancher#3114] opened 2015-12-22 00:03 UTC
The following error is appearing in the Rancher logs every few seconds (along with many other log entries).  Not sure if this is a cause for concern.
Rancher 0.50.2, CoreOS
````
2015-12-22 00:02:25,652 ERROR [:] [] [] [] [cutorService-10] [.p.c.v.i.ConfigItemStatusManagerImpl] Failed null, exit code [1] output [INFO: Updating host-routes
INFO: Downloading https://rancher.container.auckland.ac.nz/v1//configcontent//host-routes current=
INFO: Running /var/lib/cattle/download/host-routes/host-routes-549-43fd6287135af077f5dffa7a2b5721a16cf12fe8b28a9e1bf522b35d19a80ea8/apply.sh
RTNETLINK answers: Invalid argument
[[scripts.sh:184] script_env
[[scripts.sh:109] '[' -n https://rancher.container.auckland.ac.nz/v1 ']'
[[scripts.sh:110] return
[[scripts.sh:186] export CATTLE_HOME=/var/lib/cattle
[[scripts.sh:186] CATTLE_HOME=/var/lib/cattle
[[scripts.sh:187] export CATTLE_CONFIG_URL=https://rancher.container.auckland.ac.nz/v1
[[scripts.sh:187] CATTLE_CONFIG_URL=https://rancher.container.auckland.ac.nz/v1
[[scripts.sh:188] export CATTLE_STORAGE_URL=https://rancher.container.auckland.ac.nz/v1
[[scripts.sh:188] CATTLE_STORAGE_URL=https://rancher.container.auckland.ac.nz/v1
[apply.sh:5] OUTPUT=content-home/etc/cattle/subnet-bridge-gateway
[apply.sh:125] gateway
[apply.sh:44] read SUBNET BRIDGE GATEWAY
[apply.sh:44] subnet_bridge_gateway
[apply.sh:9] '[' '!' -e content-home/etc/cattle/subnet-bridge-gateway ']'
[apply.sh:32] cat content-home/etc/cattle/subnet-bridge-gateway
[apply.sh:45] '[' -z 10.42.0.1 ']'
[apply.sh:49] RUN_ARPTABLES=true
[apply.sh:51] grep -q 10.42.0.1
[apply.sh:51] ip addr show dev docker0
[apply.sh:44] read SUBNET BRIDGE GATEWAY
[apply.sh:45] '[' -z 10.42.0.1 ']'
[apply.sh:49] RUN_ARPTABLES=true
[apply.sh:51] grep -q 10.42.0.1
[apply.sh:51] ip addr show dev docker0
[apply.sh:44] read SUBNET BRIDGE GATEWAY
[apply.sh:126] setup_routes
[apply.sh:59] cat
[[apply.sh:59] routes
[[apply.sh:37] read SUBNET BRIDGE GATEWAY
[[apply.sh:37] subnet_bridge_gateway
[[apply.sh:9] '[' '!' -e content-home/etc/cattle/subnet-bridge-gateway ']'
[[apply.sh:32] cat content-home/etc/cattle/subnet-bridge-gateway
[[apply.sh:38] echo route add 10.42.0.0/16 dev docker0 src 10.42.0.1 table 300
[[apply.sh:37] read SUBNET BRIDGE GATEWAY
[[apply.sh:38] echo route add 169.254.169.250/32 dev docker0 src 10.42.0.1 table 300
[[apply.sh:37] read SUBNET BRIDGE GATEWAY
[apply.sh:67] apply_config ip -batch etc/cattle/host-routes
[scripts.sh:147] local file=etc/cattle/host-routes
[scripts.sh:148] local 'cmd=ip -batch'
[scripts.sh:150] ip -batch content-home/etc/cattle/host-routes
RTNETLINK answers: Invalid argument
[scripts.sh:151] '[' -e /var/lib/cattle/etc/cattle/host-routes ']'
[scripts.sh:154] return 1
]
````

**Comment by deniseschannon** [comment] 2016-01-04 21:32
What version of CoreOS/Docker are you using? I saw @ibuildthecloud mention that Docker 1.8 and Rancher don't provide the best experience. The issues we saw in Docker 1.8 were addressed in Docker 1.9.1, which is only available in CoreOS Beta.

**Comment by deniseschannon** [comment] 2016-01-06 18:17
@sshipway Besides what version of CoreOs/Docker, are you seeing these logs in rancher/server or rancher/agent?

**Comment by sshipway** [comment] 2016-01-08 04:59
rancher/server; this is running with docker 1.8.3 and CoreOS 845.0.0

I should be able to upgrade to CoreOS 877 which uses docker 1.9.1 but it will take a bit of time (not as easy as upgrading the cattle)

**Comment by Slamper** [comment] 2016-01-12 08:14
@denisechannon Also confirmed on latest CoreOS Beta Version with Docker 1.9.1 maybe this is the reason for the timeout in #3051

**Comment by Flowman** [comment] 2016-01-13 15:41
I got the same issue on CoreOS 835.9.0 with rancher v0.51.0 and docker 1.8.

**Comment by sshipway** [comment] 2016-01-13 21:13
I found that I had to use CoreOS 877.1.0 (Beta) for Rancher cattle to work properly (this version has Docker 1.9.1).  The current CoreOS Beta is 899.1.0.

**Comment by deniseschannon** [comment] 2016-03-04 21:35
@sshipway It seems like moving to CoreOS Beta, which is Docker 1.9.1 and now the minimum required version has solved your issue. Please re-open if I'm mistaken.

**Closed by deniseschannon** 2016-03-04 21:35 UTC
Labels: kind/question
