### ISSUE TITLE
Okta login fails through tile.

### ISSUE THREAD

**Issue by DominicGunn** [rancher/rancher#19374] opened 2019-04-03 20:21 UTC
**What kind of request is this (question/bug/enhancement/feature request):**

This is a bug. When trying to access Rancher through an Okta tile (shown below), login fails. When logging in through the 'Login with Okta' button, login succeeds.

<img width="295" alt="Screenshot 2019-04-03 at 21 20 39" src="https://user-images.githubusercontent.com/4493719/55510509-5a14ce80-5656-11e9-8a95-ed3b13429220.png">

**Steps to reproduce (least amount of steps as possible):**

Follow this tutorial: https://mattslifebytes.com/2018/08/15/using-okta-and-other-saml-idps-with-rancher-2-0/

**Result:**

<img width="509" alt="Screenshot 2019-04-03 at 21 16 09" src="https://user-images.githubusercontent.com/4493719/55510290-db1f9600-5655-11e9-9d6a-e85d04b5ea82.png">

**Environment information**
- Rancher version: v2.2.1 
- Installation option (single install/HA): HA

**Comment by superseb** [comment] 2019-04-03 21:05
Sounds like a duplicate of https://github.com/rancher/rancher/issues/19196, let me know if its not

**Closed by superseb** 2019-04-03 21:05 UTC
