### ISSUE TITLE
RKE2 Provisioning: Day 2 Ops - Etcd Restore

### ISSUE THREAD

**Issue by deniseschannon** [rancher/rancher#32392] opened 2021-04-27 05:26 UTC
local
s3
Restore with only etcd
Restore with etcd & k8s version
Restore with etcd snapshot, k8s version & cluster config

**Comment by deniseschannon** [comment] 2021-05-04 20:55
```
apiVersion: provisioning.cattle.io/v1
kind: Cluster
metadata:
  name: #string
  annotations:
    {}
#    key: string
  labels:
    {}
#    key: string
  namespace: fleet-default
spec:
  cloudCredentialSecretName: do
  kubernetesVersion: v1.21.0-alpha2+rke2r1
  rkeConfig:

#    etcdSnapshotRestore:
#      createdAt: string
#      name: string
#      nodeName: string
#      s3:
#        bucket: string
#        cloudCredentialName: string
#        endpoint: string
#        endpointCA: string
#        folder: string
#        region: string
#        skipSSLVerify: boolean

```

**Comment by ShylajaDevadiga** [comment] 2021-07-07 03:41
While validating using master-head commit id: 3e44415, from rancher UI
On a single node AWS Custom Cluster and DO Node Driver:
Local:
- On demand as well as scheduled snapshot creation was successful
- Restore using snapshot with workloads was successful
- Retention count works as expected
- Config file is updated 
```
ubuntu@ip-172-31-44-251:~$ sudo cat /etc/rancher/rke2/config.yaml.d/50-rancher.yaml 
{
  "agent-token": "<TOKEN>",
  "cni": "calico",
  "etcd-snapshot-retention": 5,
  "etcd-snapshot-schedule-cron": "0 */5 * * *",
  "node-label": [
    "rke.cattle.io/machine=<machine>"
  ],
  "token": "<TOKEN>"
}ubuntu@ip-172-31-44-251:~$
```
![image](https://user-images.githubusercontent.com/56045581/124696744-78ec1600-de9a-11eb-84b5-3c3d69f4b6bb.png)


S3:
- While validating storing snapshots in S3 bucket, It doesn't appear as though S3 parameters are being sent to a node when being provisioned. We need to confirm the parameters sent to the node from the Rancher UI to help determine the cause.

Validating on AWS Node Driver and DO Custom Cluster is blocked due to cluster creation issue.

**Comment by davidnuzik** [comment] 2021-08-05 22:56
@deniseschannon I think this is duplicated by https://github.com/rancher/rancher/issues/32391 which is where I am carefully testing both etcd snapshots on local and s3 and restore as well. Also same for rke1 clusters: https://github.com/rancher/dashboard/issues/2971

I suggest we just close this issue as all of this is already covered in both the issues I referenced.

**Closed** 2021-08-06 03:59 UTC
Labels: [zube]: Working, area/rke2
