### ISSUE TITLE
Incorrect resource quota set for namespaces where Project quota is enabled

### ISSUE THREAD

**Issue by SheilaghM** [rancher/rancher#35647] opened 2021-11-23 18:51 UTC
SURE-3695

Rancher Cluster:
Rancher version: v2.5.10 & v.2.6.2
Number of nodes: 3
Node OS version: Ubuntu 20.04.3 LTS

Downstream Cluster:
Number of Downstream clusters: 1 
Node OS: Ubuntu 20.04.3 LTS
RKE/RKE2/K3S version: NA
Kubernetes version: NA
CNI: NA

Longhorn:
Longhorn version:NA
CPU per node: NA
Memory per node: NA
Disk type: HDD/SSD/NVMe
Network bandwidth between the nodes: NA

Other:
Underlying Infrastructure: NA
Any 3rd party software installed on the nodes: NA
-->

Issue description:
The namespace created after utilizing all project limits; the resource quota allocated to new namespace contains quota which is not provided in project quota

Business impact:
Unable to create a new config map on a namespace where no project resource quota assigned for configmap 

Repro steps: 

Create a Project with below resource limits
```  containerDefaultResourceLimit:
    limitsCpu: 200m
    limitsMemory: 128Mi
    requestsCpu: 100m
    requestsMemory: 64Mi
  description: ""
  displayName: quotatest
  enableProjectMonitoring: false
  namespaceDefaultResourceQuota:
    limit:
      limitsCpu: "1000"
      limitsMemory: "2000"
  resourceQuota:
    limit:
      limitsCpu: "1000"
      limitsMemory: "2000"
```

Create a namespace inside the project
The namespace gets a quota with the below settings 
```  spec:
    hard:
      limits.cpu: 1k
      limits.memory: 2k
```
Create another namespace, but this time the new namespace gets below the quota
```  spec:
    hard:
      configmaps: "0"
      limits.cpu: "0"
      limits.memory: "0"
      persistentvolumeclaims: "0"
      pods: "0"
      replicationcontrollers: "0"
      requests.cpu: "0"
      requests.memory: "0"
      requests.storage: "0"
      secrets: "0"
      services: "0"
      services.loadbalancers: "0"
      services.nodeports: "0"
```

Create a new config map on second namespace
```configmaps "test" is forbidden: exceeded quota: default-995sh, requested: configmaps=1, used: configmaps=0, limited: configmaps=0```

Actual behavior:
Unable to create config maps on namespace that doesn't have a project-level configmap quota set

Expected behavior:
Configmap creation should work since the limit is set for only CPU and Memory

**Comment by sowmyav27** [comment] 2021-12-07 19:33
@annablender In our initial checks we were not able to reproduce this on 2.6.2. Have to try a few more usecases and additionally test it on 2.6-head. But will get to it post 2.6.3 release

**Comment by finkr** [comment] 2022-01-14 13:07
Project Quota can't be remove, which is a serious problem, see https://github.com/rancher/rancher/issues/35688

**Comment by seanrmurphy** [comment] 2022-01-24 17:13
Pretty sure these error messages are related to this:

```
2022/01/24 17:08:06 [ERROR] error syncing <REDACTED>': handler resourceQuotaSyncController: quantities must match the regular e │
│ xpression '^([+-]?[0-9.]+)([eEinumkKMGTP]*[-+]?[0-9]*)$', handler resourceQuotaUsedLimitController: quantities must match the re │
│ gular expression '^([+-]?[0-9.]+)([eEinumkKMGTP]*[-+]?[0-9]*)$', requeuing 
```

I'm having issues working with Quotas in 2.6.3; more specifically, adding Quotas to projects after they have been created and modifying allocation to namespaces.

**Comment by seanrmurphy** [comment] 2022-01-24 17:17
I do find that if I manually remove all quota from the project using `kubectl -n local edit project p-<project-id>` and then reapply all quotas from scratch it works much better than specifying some and then adding more subsequently. It is a bit heavy handed, though....

**Comment by maxsokolovsky** [comment] 2022-01-24 21:29
I can only reproduce it (v2.5.11) if I make a new namespace via kubectl, not via UI.

Like this:
```
apiVersion: v1
kind: Namespace
metadata:
  annotations:
    field.cattle.io/projectId: local:p-mr8wf
  labels:
    field.cattle.io/projectId: p-mr8wf
  name: test
```

Then, yes, the additional limitations (to configMaps and Secrets and others) are in effect for some reason.
```
> kubectl get resourcequota -n test

configmaps: 1/0, persistentvolumeclaims: 0/0, pods: 0/0, replicationcontrollers: 0/0, requests.cpu: 0/0, requests.memory: 0/0, requests.storage: 0/0, secrets: 1/0, services: 0/0, services.loadbalancers: 0/0, services.nodeports: 0/0   limits.cpu: 0/0, limits.memory: 0/0
```

**Comment by maxsokolovsky** [comment] 2022-01-24 22:20
This seems to be a similar issue: https://github.com/rancher/rancher/issues/27750.
Will check, but both might be related to a bigger issue: https://github.com/rancher/rancher/issues/25150.

**Comment by seanrmurphy** [comment] 2022-01-25 08:47
Perhaps I should create a specific issue around what we have seen but I thought it was more or less captured in existing issues such as this one and https://github.com/rancher/rancher/issues/35385.

We tried v2.6 but had exactly problems around how project quotas are mapped to namespace quotas and we explicitly saw the issue that there was a mismatch in units as noted here https://github.com/rancher/rancher/issues/35385#issuecomment-964942040 (and I guess that also is consistent with the output from the log messages I included above).

2.5 seemed to exhibit less issues around this, so we reverted to that - now we're looking at using 2.6 again.

I can itemize a few problems we are having if it would help; one thing I did yday which caused problems:
- create a project with no quota
- create a namespace with no quota
- add quota to project, giving namespace all of the quota (ie configure it so that the intent is to have one namespace within the project)
- the quota is passed on to the project as expected - good!
- add an additional quota item to the project in the same way
- this is not passed on to the namespace

**Comment by seanrmurphy** [comment] 2022-01-25 16:09
@maxsokolovsky - thanks for quick response (and I hope I have not hijacked an issue and shifted the focus!)

I guess it's a non-trivial issue and there are probably quite a number of cases to be considered.

Afaik, k8s only does enforcement at the namespace abstraction; as such if rancher provides the ability to introduce quota at the Project level, but it is not enforced (at the namespace level), it's very unclear what is going on and what kind of behaviour to expect. Also, if I add a new quota to the Project and it is not passed on to the namespace at all (in the case that I don't create new namespaces), I guess there is no enforcement of this new quota at all, so it is essentially redundant.

In my case, I had an empty namespace, so I (perhaps incorrectly) guessed that quota changes at the Project level would automatically apply at the namespace level - if this is not the behaviour of rancher, I would expect some kind of UI notification to inform me of this.

Perhaps I don't understand the intended operation properly - if not, I'd be happy to learn how I should be using these control knobs.

**Comment by maxsokolovsky** [comment] 2022-01-25 19:27
@seanrmurphy, I checked the docs - this behavior is intentional. At the very bottom: https://rancher.com/docs/rancher/v2.6/en/project-admin/resource-quotas/quotas-for-projects/

```
Updating an existing namespace default limit for a quota at the project level will not result 
in that value being propagated to existing namespaces in the project; 
the updated value will only be applied to newly created namespaces in that project."
```

**Comment by seanrmurphy** [comment] 2022-01-26 08:18
Thanks for the clarification @maxsokolovsky - I had not seen that - I guess that content is quite new.

Even with that content, it's still not entirely clear to me how it works. Would you be able to provide a couple of clarifications?

- Case 1: I create a Project and a Namespace with no Quota - I create a container which has a memory limit of 4GB. Now I want to introduce a Quota of 2GB for the Project - does this operation fail?
- Case 2: I have a Project and a Namespace with no Quota. I add a limit to the memory consumption of the Project (and an associated default for the Namespace); I understand this gets propagated to the Namespace. I then add a Quota for the amount of cpus which can be consumed by the Project. This does not get propagated to the Namespace. If no Namespace is created, this cpu limit is not applied anywhere - is that correct?
-- If I create a new Namespace in this case, the cpu limits will apply to the new Namespace so then the total Project resource cpu consumption will be whatever is consumed in the first Namespace (which is unlimited) plus whatever is consumed in the second Namespace (which has a limit) - is this correct?

**Comment by maxsokolovsky** [comment] 2022-01-26 19:55
@seanrmurphy
Case 1: no, the operation will not fail. Just like in standard Kubernetes, this would have to do with existing workloads, which are never affected. When you create the a Quota of 2GB for the project, you will create the **first and only** ResourceQuota object in your namespace. So the existing container will just fill up this quota immediately. But it will still be created fine.

```
$ kubectl get resourcequota -n ns1
LIMIT
limits.memory: 400Mi/100Mi
```

Case 2: The CPU quota added to the project **does** get propagated to the namespace because it's a new resource. So the limit will be applied in all namespaces of the project, in this case. 
I would say the docs aren't clear here. Propagation does not happen if you **edit** the limit for an existing resource quota. But if you add a **new** resource's limit, then it does get propagated to existing and future namespaces.

**Comment by seanrmurphy** [comment] 2022-01-27 09:04
@maxsokolovsky - thanks again for the helpful clarification.

Regarding case 1: from a user perspective, it would be nice to at least get some warning/notification if I try to create a quota which is smaller than the resources already in use.

Regarding case 2: I'm pretty sure I tried to add new resource quotas to a project which were not propagated to namespaces (I had added cpu and memory limits initially and then I added storage reservations subsequently but they did not appear in the namespace) - I will test again and update here.

**Comment by seanrmurphy** [comment] 2022-01-28 09:01
I did a couple of quick tests; I was not able to reproduce the case that I believe I have seen before but some of the behaviour I found was not so intuititive.

- Test 1:
  - Create Project
    - Create Quotas (CPU Limit 10000mCPUs, Mem Limit 4096 MB); Namespace Default Limit is the same
    - Do not specify Container Default Resource Limit
  - Create Namespace
    - Namespace has no Quota associated
    - I had expected the Namespace to have the Namespace Default Limit
    - Interestingly, I do see the Quota in a label (see attached image - output from k9s) but it does not appear to be applied to the Namespace correctly

- Test 2:
  - Create Project with no quotas
  - Create Namespace
  - Add Quotas to Project (CPU Limit 10000mCPUs, Mem Limit 4096 MB); Namespace Default Limit is the same
    - Do not specify Container Default Resource Limit
  - Quotas are propagated to namespace
  - This worked as expected
  
- Test 3 (following from test 2):
  - Add additional Quota to Project (Storage Reservation 30000MB)
  - Modifications were propagated to the Namespace
  - This works as expected but I believe I have had cases where this did not work as expected - I will try it again when some workload is added to the Namespace to see if that makes any difference

- Test 4 (following test 3):
  - Remove Storage Reservation from Project (click remove, click save)
  - User is redirected back to list of Projects/Namespaces which I assume means that the operation was successful 
  - Open the Project config again and the Storage Reservation is still there
  - This was behaviour I had seen before so I had expected that, but it is a quite unsatisfactory - if the operation errors or is otherwise not possible, I would expect a notification indicating this

I'm working with Rancher 2.6.3 and k3s 1.21.7+k3s1 with docker for runtimes and Ubuntu 20.04 as host OS.

![Screenshot from 2022-01-28 09-41-05](https://user-images.githubusercontent.com/540360/151514935-2f6ee58c-7dde-48ee-bf7e-a2f82b77b7c0.png)

**Comment by annablender** [comment] 2022-01-31 14:14
Going to chime in here because I didn't before.

I worked this issue about a month ago. I was unable to reproduce the issue on 2.6.2 due to a regression with Project quota namespaces where if you input a 

Project Resource Quota
- CPUProjectLimit: 2000
- CPUNamespaceDefaultLimit: 2000
- MemProject Limit: 1000
- Mem NamespaceDefaultLimit: 1000

![image](https://user-images.githubusercontent.com/12955547/151807821-49545cf8-496e-4d60-b1ef-df6e2747e0b7.png)

1) This is incorrect because in a cluster, a user should be able to allocate a project memory limit of 1000mi and a project namespace default limit of 1000mi. That would just mean, they'd only be able to create one namespace within the project and add containers to it.

2) The UI is also wonky and doesn't show the quota fields within screen size.

3) @finkr Is also correct in pointing out that Rancher users need to be able to delete Project Quotas. Otherwise, they have to restart their cluster.

It sounds like @seanrmurphy also found the issue unreproducible, but found a myriad of other unintuitive behavior regarding project quotas which is what I noticed. @sowmyav27 I think this issue can be closed provided we have other issues open for outstanding bugs.

**Comment by maxsokolovsky** [comment] 2022-01-31 15:28
This issue occurs when you try to create namespaces bypassing the UI - directly via kubectl.
We have to support that. The UI sets the special annotation `field.cattle.io/resourceQuota` for remaining quota in relation to the project's total quota and passes it to the backend. We need to set this annotation ourselves on the backend. We must effectively do what to the UI does when it is bypassed.

The problem is that the UI sets the value of the annotation in a strange way, it does not just pull a constant value from the project. Sometimes it calculates the remaining available quota for a new namespace, sometimes it does not. Sometimes the calculation is strange - zero or a negative value for available resource quota. And I have seen different behaviors in same scenarios.

We need to understand exactly what the UI must do and then write the same logic for the backend, so that users can use kubectl to make namespaces in projects, but without bypassing all our additional logic. @gaktive

**Comment by seanrmurphy** [comment] 2022-02-01 10:02
Thanks for this @annablender .

From my testing above, I identified two specific issues, one of which is tracked elsewhere as noted by @finkr. The other open issue relates to the case in which a new Project is created with Quota and the Quota is not propagated to the Namespace. I'm not sure if there is another open issue which captures this bug; if there another such issue, I guess the current issue can be closed.

Regarding your point 1 above: I'd just add that this is one of the first tests we did (and I guess also other folks would do this in the initial testing) - if it fails/gives v unexpected behaviour, it raises not insignificant questions as I'm sure you can imagine.

Regarding your point 3 above: deleting a cluster simply to remove a Project Quota is not an option for us. As noted above, I did this using `kubectl -n local edit project p-<project-id>` - is this a Very Bad thing to do? Could it have unexpected implications?

**Comment by maxsokolovsky** [comment] 2022-02-18 20:08
There are a few edge cases that trigger behaviors whose intent we need to understand. Many behaviors are not documented, so we don't we know if they are expected, correct, and intuitive to the user. 

I believe we would need to evaluate those (possibly include someone from the UI team as well, for good measure) and decide what to do. In addition, the backend controller responsible for handling new namespaces and resource quotas, as well as container limits, needs to be significantly refactored and cleaned up to be correct, more readable and performant.

Here are some behaviors and questions about them:
- If a new namespace exceeds the quota for any one resource, should we reject the quota creation? Or should we create a zeros-for-all quota? Or should we create a quota with zeros only for requested resources that are filled up?
- When should we ever create a zeros-for-all quota?
- How do we deal with negative quota values passed in?
- Should the backend try to emulate what the UI does by calculating requested quota based on already used quota in the project? This is for when the request does not go through the UI.
- Should we ever reject new namespaces?
- More questions to be added...

About the crux of this particular issue - I believe we create a zeros-for-all quota when a new namespace would not fit simply because this is our way of rejecting the namespace. The namespace itself is created immediately on request. Our logic handles creating a Resource Quota in it. Instead of rejecting the quota and deleting the namespace, we just make a fully restrictive quota. Not sure if this is the most intuitive behavior.

**Comment by cbron** [comment] 2022-02-22 23:52
> If a new namespace exceeds the quota for any one resource, should we reject the quota creation? Or should we create a zeros-for-all quota? Or should we create a quota with zeros only for requested resources that are filled up?

Going with last option here, we should only block things that are over quota. If you are over CPU, you should still be able to make a NS with only configMaps. But ideally we alert user and tell them they are over CPU quota, so they aren't confused if they did actually want to allocate CPU. 


UI behavior: 
* When adding a namespace with a resource is over quota, the UI will only add zero-out for those resources that are over the limit, this is correct behavior. 

UI todo: 
* Need to add warning label when you are over quota, the slider going to zero doesn't tell you _why_ it's at zero. 
* Stop rebalancing quotas on existing namespaces, stay in line with docs - need to repro first
* Bug around removing quota on a project not actually removing it - need to repro first
* Bug around negative values - dashboard 5153

Non-UI behavior: 
* Adding namespace with the proper project annotation: when you are under quota you get a quota for the default, which is proper behavior.
* Adding namespace with the proper project annotation: when you are over quota, or request resources that go over quota, you get a zeroes-for-all (blocking) quota. This we want to unify with the docs and UI behavior of only blocking over-allocated resource.

Non-UI todo: 
* Last bullet above.
* We also need establish an exact list of resources for which a quota applies. The backend does not currently fully handle a few. This may be longer term.

**Comment by maxsokolovsky** [comment] 2022-02-24 18:24
For this particular task, we'll have backend changes to achieve the following behavior:

For scenarios where namespaces are created in kubectl:
- If requested quota fits the project, then it is granted and associated with the namespace.
- If requested quota does not fit, then zero quota only for overfilled resources is granted.

It should not matter whether requested quota comes from project defaults or annotation.

**Comment by catherineluse** [comment] 2022-02-25 00:50
@gaktive I think this issue can be closed because the back end has settled on the plan in this comment for now https://github.com/rancher/rancher/issues/35647#issuecomment-1050136094

**Comment by maxsokolovsky** [comment] 2022-03-04 22:35
## QA Testing

### Root cause
We were creating an all-restrictive quota (zero for all resources) for namespaces that do not 
fit the project quota for at least one resource. This was happening only with namespaces created via kubectl.

### What was fixed, or what changes have occurred
We now never create the all-restrictive quota limit.
If a new namespace does not fit the project limit, then we create a zero quota only for those resources that are overfilled,
regardless of whether the namespace is created via UI or kubectl.

This is true even if you use kubectl and explicitly specify resource quota limits with a special annotation, like this:
`field.cattle.io/resourceQuota: '{"limit":{"limitsCpu":"100m", "limitsMemory":"100Mi", "configMaps": "50"}}'`

### Areas or cases that should be tested
- Running the scenarios on the RC.
- Creating namespaces according to the old behaviors from `v2.6.3-patch1`, then upgrading to the RC. Existing namespaces and their quota limits must not be affected. But the new
behaviors are in effect for new namespaces.

### What areas could experience regressions?
Please ignore the following until you run through the main scenarios. This is mostly information to keep in mind but no action is needed at this moment.

One issue that will soon disappear is a lack of full synchronization between frontend and backend.
Here is one scenario:

A project has a limit of 500 total and 300 per namespace default (of some resource).
I make a namespace ns1 in the UI that wants and gets 300.
Then I make a namespace ns2 via kubectl that wants 300, but gets 0, because there is only 200 remaining.
Then I make a namespace ns3 in the UI that wants 300 and should get the remaining 200 (this behavior is intentional when a request is made via UI). But the UI calculates the remaining as -100.
The backend does not let -100 through and assigns 0. But there is still 200 available in the project, technically.
This happens because the backend always sets the requested quota annotation on the namespace whether or not a full quota is granted or there has been an error.
But the UI uses it to calculate actual balances.

### Steps
#### Scenario 1
Project resource limits:
CPU: 500m, Memory: 512Mi

Default limits for new namespace:
CPU: 300m, Memory: 64Mi

Make two namespaces, ns1 and ns2, in the UI, use the defaults. Inspect them with `kubectl describe ns [ns-name]`

ns1 has quota limit
CPU: 300m, Memory: 64Mi

ns2 has quota limit - notice that because you created the namespace in the UI, it gets remainder of the resource, not zero.
CPU: 200m, Memory: 64Mi

Now the CPU resource is completely occupied in the project.
Create a new namespace in the project using kubectl.
```
apiVersion: v1
kind: Namespace
metadata:
  annotations:
    field.cattle.io/projectId: [your-cluster-ID]:[your-project-ID]
  name: k1
```

k1 has quota limit
CPU: 0m, Memory: 64Mi

Create another namespace via UI called ns3.
ns3 has quota limit
CPU: 0m, Memory: 64Mi

#### Scenario 2
Project resource limits:
CPU: 500m, Memory: 512Mi

Default limits for new namespace:
CPU: 250m, Memory: 64Mi

Make two namespaces, ns1 and ns2, in the UI, use the defaults. Inspect them with `kubectl describe ns [ns-name]`

ns1 has quota limit
CPU: 250m, Memory: 64Mi

ns2 has quota limit
CPU: 250m, Memory: 64Mi

Now the CPU resources is completely filled in the project.
Create a new namespace in the project using kubectl.
```
apiVersion: v1
kind: Namespace
metadata:
  annotations:
    field.cattle.io/projectId: [your-cluster-ID]:[your-project-ID]
  name: k1
```

k1 has quota limit
CPU: 0m, Memory: 64Mi

Create another namespace via UI called ns3.
ns3 has quota limit
CPU: 0m, Memory: 64Mi

#### Scenario 3
Do the same test but for the namespace created with kubectl, do specify some custom limits in an annotation.
```
apiVersion: v1
kind: Namespace
metadata:
  annotations:
    field.cattle.io/projectId: [your-cluster-ID]:[your-project-ID]
    field.cattle.io/resourceQuota: '{"limit":{"limitsCpu":"100m", "limitsMemory":"100Mi", "configMaps": "50"}}'
  name: k1
```

namespace k1 has quota limit
CPU: 0m, Memory: 100Mi, configMaps: 50

#### Scenario 4
Create a project and do not set any resource limits.
Then create a namespace in the project using the UI.
And then create another namespace in the project using kubectl but do specify some resource quota limit:
```
apiVersion: v1
kind: Namespace
metadata:
  annotations:
    field.cattle.io/projectId: [your-cluster-ID]:[your-project-ID]
    field.cattle.io/resourceQuota: '{"limit":{"limitsCpu":"100m", "limitsMemory":"100Mi", "configMaps": "50"}}'
  name: k1
```

Observe that both namespaces end up having NO limits.

#### Scenario 5
Project resource limits:
CPU: 500m, Memory: 512Mi

Default limits for new namespace:
CPU: 300m, Memory: 64Mi

Create a namespace outside of any project. Run `kubectl create ns my-ns`.
Inspect it and observe that it has no resource quota limits.
Now move it to the project. Observe that the default quota limits are applied to it.

my-ns has quota limit
CPU: 300m, Memory: 64Mi

**Comment by brudnak** [comment] 2022-03-07 21:44
# My checks PASSED
  
## Validation Environment

| Component               | Version / Type                                     |
| ----------------------- | -------------------------------------------------- |
| Rancher version         | v2.6-3f9109c3f3a1ea482f66f7e3700e495d36517e10-head |
| Rancher cluster type    | Docker                                             |
| Docker version          | 20.10.7, build 20.10.7-0ubuntu5~20.04.2            |
| Helm version            | v2.16.8-rancher1                                   |
| Downstream cluster type | RKE Linode                                         |
| Downstream K8s version  | v1.21.9-rancher1-1                                 |
| Browser type            | Google Chrome                                      |
| Browser version         | 99.0.4844.51 (Official Build) (x86_64)             |

## Validation steps

1. Create a project
   - Name: `mytest-project` 
   - Resource Quotas:
     - CPU Limit / Project Limit: `500m`
     - Memory Limit / Project Limit: `512Mi`
     - CPU Limit / Namespace Default Limit: `300m`
     - Memory Limit / Namespace Default Limit: `64Mi`
2. Create two namespaces in the UI
    1. Name: `ns1`
    2. Name: `ns2`
3. Inspect them with

```shell
kubectl describe namespace $nameOfNamespace
```

4. Create a new namespace in the project using `kubectl` 
   - Launch the `Kubectl Shell` from the UI
   - Run the following commands

```shell
touch new-namespace-spec.yaml
vi new-namespace-spec.yaml
```

5. Paste in the following yaml file

```yaml
apiVersion: v1
kind: Namespace
metadata:
  annotations:
    field.cattle.io/projectId: [your-cluster-ID]:[your-project-ID]
  name: k1
```

6. Run the following

```shell
kubectl create -f new-namespace-spec.yaml
```

```shell
kubectl describe namespace k1
```

 ## Results

 #### Expected
 For the namespace created via kubectl to abide by the resource quota set to the project

 #### Actual
 :white_check_mark: PASS : The namespace created via kubectl did abide by the resource quota set against the project 


## Additional Tests

<table>
    <tbody>
        <tr>
            <th>Test</th>
            <th>Steps</th>
            <th>Expected</th>
            <th>Actual</th>
            <th>Pass/Fail</th>
        </tr>
        <tr>
            <td>Additional checks with different values</td>
            <td>
                <ol>
                    <li>Create a project</li>
                    <li>Name: <code>mytest-project2</code></li>
                    <li>Resource Quotas</li>
                    <li>CPU Limit / Project Limit: <code>500m</code></li>
                    <li>Memory Limit / Project Limit: <code>512Mi</code></li>
                    <li>CPU Limit / Namespace Default Limit: <code>250m</code></li>
                    <li>Memory Limit / Namespace Default Limit: <code>64Mi</code></li>
                    <li>Create two namespaces in the UI</li>
                    <li><code>anotherns1</code></li>
                    <li><code>anotherns2</code></li>
                    <li>Create a new namespace in the project using <code>kubectl</code></li>
                    <li>Check that the new namespace has expected resource quotas</li>
                    <li><code>kubectl describe namespace YOUR_NS</code></li>
                </ol>
            </td>
            <td>Namespace created with kubectl <b>SHOULD</b> have CPU Limit: 0m & Memory Limit: 64Mi</td>
            <td>Namespace created with kubectl <b>DOES</b> have CPU Limit: 0m & Memory Limit: 64Mi</td>
            <td>:white_check_mark:</td>
        </tr>
        <tr>
            <td>Do the same test but for the namespace created with kubectl, do specify some custom limits in an annotation</td>
            <td>
                <ol>
                    <li>Create resource quotas for CPU and Memory limit</li>
                    <li>Max out the CPU limit with namespaces from the UI</li>
                    <li>Try to get a namespace with CPU using kubectl with custom limits in an annotation</li>
                </ol>
            </td>
            <td>To not be able to bypass project resource quotas</td>
            <td>Unable to bypass project resource quota using custom limit in annotation</td>
            <td>:white_check_mark:</td>
        </tr>
        <tr>
            <td>Create a namespace outside of any project</td>
            <td>
                <ol>
                    <li>kubectl create ns my-ns</li>
                </ol>
            </td>
            <td>That no project resource quota should be assigned to a namespace outside of a project</td>
            <td>No resource quota was assigned to the namespace outside of the project</td>
            <td>:white_check_mark:</td>
        </tr>
    </tbody>
</table>

**Closed** 2022-03-08 17:33 UTC
Labels: priority/2, internal, [zube]: QA Working, QA/S, release-note, team/area1

**Comment by maxsokolovsky** [comment] 2022-03-16 03:13
# Resource note
For namespaces created inside projects via kubectl, the controller no longer assigns an all-restrictive quota limit when a resource limit exceeds the remaining amount in the project. Instead, a zero just for the exceeding resource is granted.
