### ISSUE TITLE
modifying loglevel inside of a rancher pod causes a panic

### ISSUE THREAD

**Issue by rosskirkpat** [rancher/rancher#36512] opened 2022-02-14 19:34 UTC
The kubectl command found [here](https://rancher.com/docs/rancher/v2.6/en/troubleshooting/logging/#how-to-configure-a-log-level) cause a panic and fails to set the loglevel properly due to Rancher running in a SLES container.

~~This problem is highly likely to be present in any Rancher build that uses the SLES container.~~

This is a critical issue as it prevents devs/QA/customers from being able to turn on debug/trace logging.

```console
rancher-59996cbc97-9wfbk:/var/lib/rancher # loglevel --set debug
Trace/breakpoint trap (core dumped)
```

Update: Feb 15

This issue appears to only exist in 2.6.4* versions. It appears that the issue is not reproducible in the 2.6.3 release.

There was a new release of loglevel in dec. 2021 (https://github.com/rancher/loglevel/commit/a6663d646b5733678832f1651a3229e163b62153) which would have landed in the 2.6.4* versions but not in 2.6.3.

It is also possible that a package update inside the SLES container that rancher runs inside of is at fault.

https://github.com/rancher/loglevel/issues/11

**Comment by MbolotSuse** [comment] 2022-02-16 01:07
Looks like the core issue is that an upgrade to the go version (from 1.9.7 -> 1.17.5). The presence of the `-linkmode external` caused the end binaries to have serious issues. I've opened a PR to try and address this. 

In the meantime, here's a workaround that you can use to fix affected deployments (pretty temporarily): 
```
kubectl -n cattle-system get pods -l app=rancher --no-headers -o custom-columns=name:.metadata.name | while read rancherpod; do kubectl -n cattle-system exec $rancherpod -- bash -c "curl --insecure -L -X GET https://github.com/rancher/loglevel/releases/download/v0.1.3/loglevel-amd64-v0.1.3.tar.gz | tar xvzf - -C /usr/bin"; done
```

Notes on this workaround:
- Don't run this in production (Mainly leaving this here in case this issue comes up in the future). I had to disable SSL verification on the curl command to get this to work, which leaves this susceptible to a man in the middle attack. If you need to run this in prod, download the tar on your local and then use [kubectl cp](https://kubernetes.io/docs/reference/generated/kubectl/kubectl-commands#cp) to transfer the tar into the pod.
- All this does is replace the loglevel binary with an older working version (version 0.1.3). This won't be what you want if you are testing functionality related to this binary, but I think that you are fine. In the case that you just want to enable logging, this will work.
- If the pods are destroyed and the deployment creates new ones, you will need to run this command again
- You will still need to run the related commands (linked in the issue) to turn on/off logging levels - all this does is make it so that the commands to increase/decrease log verbosity work.

**Comment by MbolotSuse** [comment] 2022-02-17 16:37
Validation template:

Root cause
The go compiler used to produce the loglevel binary was upgraded from version 1.9 to version 1.17. This upgrade caused some odd behavior due to our use of the `-linkmode external` flag. This flag appears to be utilized by go to determine if it should pass of linking to an external program. More can be read on this flag here: `https://cs.opensource.google/go/go/+/master:src/cmd/cgo/doc.go` . In short, this does not appear to be needed any longer, and appears to rely on CGO for some functionality (which we explicitly disable). This was causing the produced loglevel binaries to be unusable.

What was fixed, or what changes have occurred

The compiler flag was removed, the binaries were rebuilt, and rancher was configured to use the new version of loglevel (0.1.5).

Areas or cases that should be tested

Use of the loglevel binary in rancher (`loglevel` to get the current loglevel `loglevel --set DEBUG` to set the level to debug, etc.). Effects should also be double checked (i.e. make sure that the loglevel is actually changed by looking at the logs).

What areas could experience regressions ?

The ability to set the loglevel in rancher pods. 

Are the repro steps accurate/minimal ?
Yes. They are included here for convenience.

1. Run rancher:v2.6.4-rc2. It should be noted that this bug was only introduced on recent builds of rancher 2.6.4 and is not present in 2.63. In addition, this bug was observed on a local docker setup and in cluster, and should be validated as fixed in both setups.
2. Use a shell to exec into a running container (local `docker exec -it $RANCHER_NAME sh`, k8s `kubectl exec --stdin --tty -n cattle-system $RANCHER_POD_NAME -- sh`).
3. Attempt to view the current log level (`loglevel`). Observe the `Trace/breakpoint trap (core dumped)` error.
4. Attempt to change the log loglevel (`loglevel --set info`). Observe the `Trace/breakpoint trap (core dumped)` error.

**Closed** 2022-02-24 17:32 UTC
Labels: kind/bug, internal, [zube]: QA Working, QA/XS, status/release-blocker, team/area1
