### ISSUE TITLE
rancher cluster monitoring, prometheus keeps getting oomkilled

### ISSUE THREAD

**Issue by krishofmans** [rancher/rancher#19673] opened 2019-04-17 14:17 UTC
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
Enable monitoring on cluster, we tried both persistent and non-persistent and increased the memory limit to 1250Mb

**Result:**
Prometheus keeps getting oomkilled. We already have a monitoring stack deployed so we can see it going oom in that grafana/prometheus. We have other clusters where the combination is working, so they don't seem to be interfering with each other.

![image](https://user-images.githubusercontent.com/999774/56294867-15943300-612c-11e9-8b07-813e4710ebfd.png)

**Other details that may be helpful:**

A describe of the pod after oomkilled:
```
Name:               prometheus-cluster-monitoring-0
Namespace:          cattle-prometheus
Priority:           0
PriorityClassName:  <none>
Node:               k8s-development-6/192.168.26.24
Start Time:         Wed, 17 Apr 2019 15:15:50 +0200
Labels:             app=prometheus
                    chart=prometheus-0.0.1
                    controller-revision-hash=prometheus-cluster-monitoring-c6f68955b
                    monitoring.coreos.com=true
                    prometheus=cluster-monitoring
                    release=cluster-monitoring
                    statefulset.kubernetes.io/pod-name=prometheus-cluster-monitoring-0
Annotations:        cni.projectcalico.org/podIP: 10.42.5.39/32
Status:             Running
IP:                 10.42.5.39
Controlled By:      StatefulSet/prometheus-cluster-monitoring
Containers:
  prometheus:
    Container ID:  docker://4ed302f33e8a0b5b8d81d7b2680ec85c0b79e1caa9c5233c1d0d417441b0fa15
    Image:         rancher/prom-prometheus:v2.7.1
    Image ID:      docker-pullable://rancher/prom-prometheus@sha256:b32864cfe5f7f5d146820ddc6dcc5f78f40d8ab6d55e80decd5fc222b16344dc
    Port:          <none>
    Host Port:     <none>
    Args:
      --web.console.templates=/etc/prometheus/consoles
      --web.console.libraries=/etc/prometheus/console_libraries
      --config.file=/etc/prometheus/config_out/prometheus.env.yaml
      --storage.tsdb.path=/prometheus
      --storage.tsdb.retention=12h
      --web.enable-lifecycle
      --storage.tsdb.no-lockfile
      --web.route-prefix=/
      --web.listen-address=127.0.0.1:9090
    State:          Waiting
      Reason:       CrashLoopBackOff
    Last State:     Terminated
      Reason:       OOMKilled
      Exit Code:    137
      Started:      Wed, 17 Apr 2019 15:48:43 +0200
      Finished:     Wed, 17 Apr 2019 15:50:50 +0200
    Ready:          False
    Restart Count:  7
    Limits:
      cpu:     1
      memory:  1250Mi
    Requests:
      cpu:        750m
      memory:     750Mi
    Environment:  <none>
    Mounts:
      /etc/prometheus/config_out from config-out (ro)
      /etc/prometheus/configmaps/prometheus-cluster-monitoring-nginx from configmap-prometheus-cluster-monitoring-nginx (ro)
      /etc/prometheus/rules/prometheus-cluster-monitoring-rulefiles-0 from prometheus-cluster-monitoring-rulefiles-0 (rw)
      /etc/prometheus/secrets/exporter-etcd-cert from secret-exporter-etcd-cert (ro)
      /prometheus from prometheus-cluster-monitoring-db (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from cluster-monitoring-token-hpwqw (ro)
  prometheus-config-reloader:
    Container ID:  docker://b89874489455ac0845324967575b74161445def8fabb5f7537ff46b7845e2159
    Image:         rancher/coreos-prometheus-config-reloader:v0.29.0
    Image ID:      docker-pullable://rancher/coreos-prometheus-config-reloader@sha256:9c47f0451a3c0a2277fb259367785226bf3be317dd5b98bacbb6aa9b112feba2
    Port:          <none>
    Host Port:     <none>
    Command:
      /bin/prometheus-config-reloader
    Args:
      --log-format=logfmt
      --reload-url=http://localhost:9090/-/reload
      --config-file=/etc/prometheus/config/prometheus.yaml.gz
      --config-envsubst-file=/etc/prometheus/config_out/prometheus.env.yaml
    State:          Running
      Started:      Wed, 17 Apr 2019 15:15:59 +0200
    Ready:          True
    Restart Count:  0
    Limits:
      cpu:     50m
      memory:  50Mi
    Requests:
      cpu:     50m
      memory:  50Mi
    Environment:
      POD_NAME:  prometheus-cluster-monitoring-0 (v1:metadata.name)
    Mounts:
      /etc/prometheus/config from config (rw)
      /etc/prometheus/config_out from config-out (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from cluster-monitoring-token-hpwqw (ro)
  prometheus-proxy:
    Container ID:  docker://248c2b143d138068261cb1a23ae86e0f54d835bc7d51802f9e24bd2773d9e963
    Image:         rancher/nginx:1.15.8-alpine
    Image ID:      docker-pullable://rancher/nginx@sha256:c9a462bce16d85dde1861d45aebfae80c812d733187d045cbb7ffe3d71ac37bd
    Port:          80/TCP
    Host Port:     0/TCP
    Command:
      /bin/sh
      -c
      cp /nginx/run-sh.tmpl /var/run/nginx-start.sh; chmod +x /var/run/nginx-start.sh; /var/run/nginx-start.sh
    State:          Running
      Started:      Wed, 17 Apr 2019 15:16:03 +0200
    Ready:          True
    Restart Count:  0
    Limits:
      cpu:     100m
      memory:  100Mi
    Requests:
      cpu:     50m
      memory:  50Mi
    Environment:
      POD_IP:   (v1:status.podIP)
    Mounts:
      /nginx from configmap-prometheus-cluster-monitoring-nginx (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from cluster-monitoring-token-hpwqw (ro)
  prometheus-agent:
    Container ID:  docker://423af7cc63520471ed1cb510502723214b8a248637931946957ed844e9c60d5f
    Image:         rancher/prometheus-auth:v0.2.0
    Image ID:      docker-pullable://rancher/prometheus-auth@sha256:8f715bf8eb4ea41c6598ccd244da51743d14f5a5c7cb93091fdced531cf48dbe
    Port:          9090/TCP
    Host Port:     0/TCP
    Command:
      prometheus-auth
    Args:
      --proxy-url=http://localhost:9090
      --listen-address=$(POD_IP):9090
      --filter-reader-labels=prometheus
      --filter-reader-labels=prometheus_replica
    State:          Waiting
      Reason:       CrashLoopBackOff
    Last State:     Terminated
      Reason:       Error
      Exit Code:    2
      Started:      Wed, 17 Apr 2019 15:50:42 +0200
      Finished:     Wed, 17 Apr 2019 15:51:49 +0200
    Ready:          False
    Restart Count:  7
    Limits:
      cpu:     500m
      memory:  200Mi
    Requests:
      cpu:      100m
      memory:   100Mi
    Liveness:   http-get http://:web/-/healthy delay=0s timeout=10s period=10s #success=1 #failure=6
    Readiness:  http-get http://:web/-/ready delay=0s timeout=10s period=10s #success=1 #failure=10
    Environment:
      POD_IP:   (v1:status.podIP)
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from cluster-monitoring-token-hpwqw (ro)
  rules-configmap-reloader:
    Container ID:  docker://53ad8293a571ae6a217248d9018fde7026d0cf8e1e8bf42fdd9a018564456d2b
    Image:         rancher/coreos-configmap-reload:v0.0.1
    Image ID:      docker-pullable://rancher/coreos-configmap-reload@sha256:f58cb3b14aea0fc5b5f1d8f978218036b48207a2eb53079e3af9ce14db5f0676
    Port:          <none>
    Host Port:     <none>
    Args:
      --webhook-url=http://localhost:9090/-/reload
      --volume-dir=/etc/prometheus/rules/prometheus-cluster-monitoring-rulefiles-0
    State:          Running
      Started:      Wed, 17 Apr 2019 15:16:09 +0200
    Ready:          True
    Restart Count:  0
    Limits:
      cpu:     100m
      memory:  25Mi
    Requests:
      cpu:        100m
      memory:     25Mi
    Environment:  <none>
    Mounts:
      /etc/prometheus/rules/prometheus-cluster-monitoring-rulefiles-0 from prometheus-cluster-monitoring-rulefiles-0 (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from cluster-monitoring-token-hpwqw (ro)
Conditions:
  Type              Status
  Initialized       True
  Ready             False
  ContainersReady   False
  PodScheduled      True
Volumes:
  config:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  prometheus-cluster-monitoring
    Optional:    false
  config-out:
    Type:    EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:
  prometheus-cluster-monitoring-rulefiles-0:
    Type:      ConfigMap (a volume populated by a ConfigMap)
    Name:      prometheus-cluster-monitoring-rulefiles-0
    Optional:  false
  secret-exporter-etcd-cert:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  exporter-etcd-cert
    Optional:    false
  configmap-prometheus-cluster-monitoring-nginx:
    Type:      ConfigMap (a volume populated by a ConfigMap)
    Name:      prometheus-cluster-monitoring-nginx
    Optional:  false
  prometheus-cluster-monitoring-db:
    Type:    EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:
  cluster-monitoring-token-hpwqw:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  cluster-monitoring-token-hpwqw
    Optional:    false
QoS Class:       Burstable
Node-Selectors:  beta.kubernetes.io/os=linux
Tolerations:     node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
Events:
  Type     Reason     Age                   From                        Message
  ----     ------     ----                  ----                        -------
  Normal   Pulling    38m                   kubelet, k8s-development-6  pulling image "rancher/prom-prometheus:v2.7.1"
  Normal   Scheduled  38m                   default-scheduler           Successfully assigned cattle-prometheus/prometheus-cluster-monitoring-0 to k8s-development-6
  Normal   Pulled     38m                   kubelet, k8s-development-6  Successfully pulled image "rancher/prom-prometheus:v2.7.1"
  Normal   Pulling    38m                   kubelet, k8s-development-6  pulling image "rancher/coreos-prometheus-config-reloader:v0.29.0"
  Normal   Pulled     38m                   kubelet, k8s-development-6  Successfully pulled image "rancher/coreos-prometheus-config-reloader:v0.29.0"
  Normal   Pulling    38m                   kubelet, k8s-development-6  pulling image "rancher/nginx:1.15.8-alpine"
  Normal   Created    38m                   kubelet, k8s-development-6  Created container
  Normal   Started    38m                   kubelet, k8s-development-6  Started container
  Normal   Created    38m                   kubelet, k8s-development-6  Created container
  Normal   Pulled     38m                   kubelet, k8s-development-6  Successfully pulled image "rancher/nginx:1.15.8-alpine"
  Normal   Pulling    38m                   kubelet, k8s-development-6  pulling image "rancher/prometheus-auth:v0.2.0"
  Normal   Started    38m                   kubelet, k8s-development-6  Started container
  Normal   Pulled     38m                   kubelet, k8s-development-6  Successfully pulled image "rancher/prometheus-auth:v0.2.0"
  Normal   Created    38m                   kubelet, k8s-development-6  Created container
  Normal   Started    38m                   kubelet, k8s-development-6  Started container
  Normal   Pulling    38m                   kubelet, k8s-development-6  pulling image "rancher/coreos-configmap-reload:v0.0.1"
  Normal   Created    37m                   kubelet, k8s-development-6  Created container
  Normal   Started    37m                   kubelet, k8s-development-6  Started container
  Normal   Pulled     37m                   kubelet, k8s-development-6  Successfully pulled image "rancher/coreos-configmap-reload:v0.0.1"
  Normal   Started    37m (x2 over 38m)     kubelet, k8s-development-6  Started container
  Normal   Created    37m (x2 over 38m)     kubelet, k8s-development-6  Created container
  Warning  Unhealthy  28m                   kubelet, k8s-development-6  Liveness probe failed: HTTP probe failed with statuscode: 502
  Normal   Pulled     28m (x2 over 37m)     kubelet, k8s-development-6  Container image "rancher/prom-prometheus:v2.7.1" already present on machine
  Warning  BackOff    8m9s (x49 over 28m)   kubelet, k8s-development-6  Back-off restarting failed container
  Warning  Unhealthy  3m11s (x52 over 28m)  kubelet, k8s-development-6  Readiness probe failed: HTTP probe failed with statuscode: 502
```

**Environment information**
- Rancher version: 2.2.2 (latest stable at the time of writing)
- Installation option (single install/HA):single install

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): Custom
- Machine type (cloud/VM/metal) and specifications (CPU/memory): 3 admin nodes 4 core/3gb, 5 worker nodes: 8 cores/16gb, all running ubuntu 16.04
```
NAME                 STATUS   ROLES               AGE    VERSION
k8s-dev-admin-4      Ready    controlplane,etcd   142d   v1.12.7
k8s-dev-admin-5      Ready    controlplane,etcd   142d   v1.12.7
k8s-dev-admin-6      Ready    controlplane,etcd   142d   v1.12.7
k8s-development-10   Ready    worker              126d   v1.12.7
k8s-development-6    Ready    worker              126d   v1.12.7
k8s-development-7    Ready    worker              126d   v1.12.7
k8s-development-8    Ready    worker              126d   v1.12.7
k8s-development-9    Ready    worker              126d   v1.12.7
```

- Kubernetes version (use `kubectl version`): 
```
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.4", GitCommit:"c27b913fddd1a6c480c229191a087698aa92f0b1", GitTreeState:"clean", BuildDate:"2019-03-01T23:34:27Z", GoVersion:"go1.12", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.7", GitCommit:"6f482974b76db3f1e0f5d24605a9d1d38fad9a2b", GitTreeState:"clean", BuildDate:"2019-03-25T02:41:57Z", GoVersion:"go1.10.8", Compiler:"gc", Platform:"linux/amd64"}
```

- Docker version (use `docker version`): 17.3.2

**Comment by loganhz** [comment] 2019-05-04 05:41
Enhanced the prometheus memory usage a bit by removing unused rules and reduced the scrap frequency.

Chart PR merged

Waiting for https://github.com/rancher/rancher/pull/19766 https://github.com/rancher/types/pull/801 https://github.com/rancher/system-charts/pull/37 merged and https://github.com/rancher/rancher/pull/19766 https://github.com/rancher/types/pull/801 backport to 2.2. branch.

**Comment by jiaqiluo** [comment] 2019-07-24 21:43
The bug fix is validated in Rancher: master-head c2d9dc8a

Steps:
- run Rancher container single install
- add an EC2 cluster with 3 etcd/control plane nodes, 3 workers nodes. Each node is t2.medium 2 vCPU, 4 GB memory
- enable the cluster monitoring with all default settings 
- run some automation test on the cluster to make it "busy"
- keep and observe the cluster monitoring apps for a while (its 3+ hours as the time writing the comment)

Results:
- the pod `prometheus-cluster-monitoring-0` in workload `prometheus-cluster-monitoring` does not get oomkilled anymore
- the cluster monitoring feature works as expected 

<img width="1426" alt="screenshot" src="https://user-images.githubusercontent.com/6218999/61830977-6305f780-ae21-11e9-8705-bd08354c1a9e.png">

<img width="1825" alt="screenshot" src="https://user-images.githubusercontent.com/6218999/61830864-191d1180-ae21-11e9-890e-e26e5dcc1556.png">

**Closed** 2019-07-30 16:41 UTC
Labels: [zube]: To Test, area/monitoring, kind/bug, team/cn

**Comment by PeterMaco** [comment] 2020-08-01 15:39
This is still happening in 2.4.5. Could you please share some details about the root cause of the issue? Do I need to configure something to stop this happening? Symptoms are exactly the same as it is described in the original post.

**Comment by brylor** [comment] 2020-08-07 16:58
I'm having this problem also in  v2.4.2

**Comment by brylor** [comment] 2020-08-07 21:06
I was getting OOM on the prometheus container in the prometheus-cluster-monitoring-0 pod.. I raised the memory from the UI and it's holding.

**Comment by timmy59100** [comment] 2020-08-27 12:48
@PeterMaco Same with 2.4.5 also increased memory limit like @brylor

**Comment by casabian** [comment] 2020-09-29 06:42
@PeterMaco I can also confirm this on 2.4.5.  As @brylor said increasing prometheus's default memory limits prevents this from happening.

**Comment by petertang2012** [comment] 2020-11-17 13:39
I am also experiencing this on 2.5.1 with 2.4.5 created cluster

**Comment by stefanlasiewski** [comment] 2021-03-16 22:46
Still having this in 2.4.12!

Seems like the docs at https://rancher.com/docs/rancher/v2.x/en/monitoring-alerting/v2.0.x-v2.4.x/cluster-monitoring/ have RAM values that are too low.

**Comment by cypromis** [comment] 2021-05-01 21:04
Still having this in 2.5.7

**Comment by quangthe** [comment] 2021-07-15 03:56
I got this issue on image `rancher/mirrored-prometheus-prometheus:v2.24.0`. The `prometheus-rancher-monitoring-prometheus-0` pod keeps restarting. 

![Screen Shot 2021-07-15 at 10 49 40 AM](https://user-images.githubusercontent.com/171691/125726625-dc23231c-ca67-4ac3-981d-1e8bce75f967.png)

**Comment by joaogl** [comment] 2021-07-19 08:58
Using rancher-monitoring 9.4.203 I'm getting the same issue, I was digging into the graphs and it seems graphana has managed to hit almost 8G ram usage on a empty cluster with barely anything running and only 2 custom scrappers, galeradb and gitlab.

Comparing this to the 'recommended' 1g ram or whatever it was it quite a big jump, is this supposed? I mean if it consumes this much ram on an empty cluster how much ram are you guys giving this for a full prod cluster? 32G?

**Comment by alvaromlg** [comment] 2021-07-20 10:40
We are having the same OOM killed issue on rancher-monitoring 9.4.202 on a 8GB ram instance dedicated only for this service.

Before upgrading our instance to 16GB or 32GB it would be good to know if its a memory leak/bug or minimum requirements have been updated.

**Comment by alvaromlg** [comment] 2021-07-21 13:00
More info and temporal fix on this for anyone coming here.
I am running prometheus on a dedicate server instance with 2 vCPU and 8GB ram, it only runs basic kube/rancher needed services and prometheus, something like this:
```
NAMESPACE                  NAME
cattle-monitoring-system   prometheus-rancher-monitoring-prometheus-0   
cattle-monitoring-system   pushprox-kube-proxy-client-rt874
cattle-monitoring-system   rancher-monitoring-prometheus-adapter-5fc7c8768d-zthz5
cattle-monitoring-system   rancher-monitoring-prometheus-node-exporter-6qs6q
cattle-system              cattle-node-agent-kqxzn
ingress-nginx              nginx-ingress-controller-tt8sq
iptables                   firewall-k8swall-hqnbr
```
And this is the current status:
CPU: 66%
Memory:   4805Mi  62%

So because it kept getting oomkilled I modified the prometheus resources to this (basically x2 on both memory attributes):
```
    resources:
      limits:
        cpu: 1000m
        memory: 3000Mi
      requests:
        cpu: 750m
        memory: 1500Mi
```
For now it runs fine, no restarts due oomkilled crashes. I also run prometheus on a staging cluster with less nodes and there the default resources configuration works fine.

So looks like that configuration basically **doesnt scale up**, probably with more nodes it will need more resources, maybe it should appear on the helm README if its intended or should get fixed if its some kind of memory leak but that helm chart wont work on most of the production clusters with a decent number of nodes.
