### ISSUE TITLE
AzureAD and Local Auth broken after 2.2 Upgrade

### ISSUE THREAD

**Issue by dnauck** [rancher/rancher#19202] opened 2019-03-27 06:16 UTC
**What kind of request is this (question/bug/enhancement/feature request):**
bug

**Steps to reproduce (least amount of steps as possible):**
1. Upgraded Rancher v2.1.7 to v2.2.0
2. try to login via AzureAD (was working before)
**Result:**
HTTP 500 ERROR

```
ServerError (500)
Server error while authenticating
```

**Other details that may be helpful:**

error in rancher server log:

```
2019/03/27 06:08:35 [ERROR] API error response 500 for POST /v3-public/azureADProviders/azuread?action=login. Cause: error getting secret r[K}8:DksA)hHQ>Mh1%!k(MISSING):knV8DnVa6HVo5-O0X%!}(MISSING)qn&mFV%!H(MISSING)rK5F:X! invalid resource name "DksA)hHQ>Mh1%!k(MISSING):knV8DnVa6HVo5-O0X%!}(MISSING)qn&mFV%!H(MISSING)rK5F:X!": [may not contain '%!'(MISSING)]
```

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI):
- Installation option (single install/HA): single install version 2.2.0

**Comment by dnauck** [comment] 2019-03-27 06:18
Hello,

local login is also broken:

```
2019/03/27 06:17:58 [ERROR] API error response 401 for POST /v3-public/localProviders/local?action=login. Cause: crypto/bcrypt: hashedPassword is not the hash of the given password
```

**Comment by davidnuzik** [comment] 2019-03-27 17:07
Version v2.1.7 -> v2.2.0 upgrade
I am having a hard time reproducing the problem from QA testing perspective.
- Have single install (non-HA) rancher setup with v2.1.7 enable Azure AD auth. Log out and in to ensure is working.
- Upgrade to v2.2.0. Login in again -- no issues logging in.
- Log out and log in with local auth -- again no issues logging in.

I do not see any errors when watching rancher docker logs at INFO level. cc: @sangeethah

**Comment by dnauck** [comment] 2019-03-27 22:51
Tested the upgrade process again, same result

**Comment by dnauck** [comment] 2019-03-28 07:03
How can i help you to find the issue? The log looks not very helpful as it contains only these single error lines.

**Comment by tfiduccia** [comment] 2019-03-28 18:41
@cjellick  - This looks like a secret named "DksA)hHQ>Mh1%!k(MISSING):knV8DnVa6HVo5-O0X%!}(MISSING)qn&mFV%!H(MISSING)rK5F:X!" is breaking log in.  Can you have someone look into it.

**Comment by mrajashree** [comment] 2019-03-30 00:22
Unable to repro this
On a 2.1.7 setup I enabled Azure AD auth and added another AD user as a cluster-member
Both AD users could logout and login
Upgraded to 2.2.0
Both users can still logout login. Logging in as local admin user works too.

The error that local user gets `hashedPassword is not the hash of the given password` seems to be because the hashed pwd we had saved for this user doesn't match the pwd user is currently provided.
@dnauck Did you happen to reset the local admin password using this command post upgrade? `docker exec -ti <container_id> reset-password`?

**Comment by cjellick** [comment] 2019-03-30 00:26
@dnauck when you say you tested the upgrade process again, does that mean you are able to revert to 2.1.7, see it working again, and then upgrade and see it fail again?

**Comment by dnauck** [comment] 2019-03-30 08:46
@cjellick yes, i created a snapshot of the vm, upgraded to v2.2.0 and tested. It was not working so i reverted the snapshot back and tested again with the same result.

@mrajashree no, didn't know this command

**Comment by cjellick** [comment] 2019-04-01 17:38
@dnauck do you know what version of Rancher you have upgrade through?

**Comment by dnauck** [comment] 2019-04-01 17:57
@cjellick i upgraded from v2.1.7 to v2.2.0 - or do you want to know sth. else?

**Comment by dramich** [comment] 2019-04-01 17:59
The error message is coming from [here](https://github.com/rancher/rancher/blob/94beacf49092cc8e3c14242d1af8fe3a120ce653/pkg/auth/providers/common/password.go#L54) which didn't exist in 2.1.7. It was added in [this](https://github.com/rancher/rancher/commit/f370381f1c43b2b2a9cb9925a78c0156c3521e13#diff-af55677ca7a7d590dd2623b2f3bca1f0) PR.

**Comment by dnauck** [comment] 2019-04-01 18:01
@dramich sure, v2.1.7 runs well, after upgrade to v2.2.0 it does not

**Comment by dramich** [comment] 2019-04-01 18:55
@dnauck I am reaching out on user slack for some more info.

**Comment by cjellick** [comment] 2019-04-03 21:18
Thanks for identifying this issue @dnauck!

**Comment by sangeethah** [comment] 2019-04-04 00:42
@dnauck  We have validated that this issue is fixed in rancher server version - v2.2.2-rc1 using AD auth which has a service account password which has ":". Details of tests done - https://github.com/rancher/rancher/issues/19346#issuecomment-479702279.

Could you please check if upgrading to `v2.2.2-rc1` fixes your issue ?

**Comment by dnauck** [comment] 2019-04-04 18:45
@sangeethah i already changed the Azure AD App Secret to a value without a colon :(

**Comment by sangeethah** [comment] 2019-04-30 17:43
@dnauck Thanks for reporting this issue .
Closing this issue per findings from https://github.com/rancher/rancher/issues/19346#issuecomment-479702279

**Closed by sangeethah** 2019-04-30 17:43 UTC
Labels: area/authentication, area/secrets, kind/bug, status/blocker, status/ready-for-review, status/resolved, status/working, team/az
