### ISSUE TITLE
422 Body: [code=NotUnique, fieldName=name] when multiple containers use the same data volume

### ISSUE THREAD

**Issue by dj-hedgehog** [rancher/rancher#4460] opened 2016-04-19 09:23 UTC
Rancher Version: v1.0.0

Docker Version: 1.10.3

OS: Ubuntu 15.04

Steps to Reproduce:

`docker-compose --verbose up` with this `docker-compose.yml`:

```
app:
  image: mageinferno/magento2-nginx:1.9.9-2
  ports:
    - "80:80"
  links:
    - phpfpm
    - db
  volumes_from:
    - appdata
  environment:
    - APP_MAGE_MODE=production
    - VIRTUAL_HOST=shop.liquid-trading.de
  labels:
    io.rancher.sidekicks: appdata, phpfpm, setup

appdata:
  image: tianon/true
  volumes:
    - "/var/magento2/src:/src"

phpfpm:
  image: mageinferno/magento2-php:7.0.2-fpm-1
  links:
    - db
  volumes_from:
    - appdata
  environment:
    - APP_MAGE_MODE=default
    - PHP_MEMORY_LIMIT=2048M

db:
  image: mariadb:10.1.10
  ports:
    - "3306:3306"
  volumes:
    - "/var/magento2/mysql:/var/lib/mysql"

setup:
  image: mageinferno/magento2-php:7.0.2-fpm-1
  command: /usr/local/bin/mage-setup
  links:
    - db
  volumes_from:
    - appdata
```

Results: 

```
INFO[0000] Creating service app
DEBU[0000] Creating service app with hash: digest.ServiceHash{Service:"04eebe96f990ab64972bce5193990b3e6b8da6a2", LaunchConfig:"792bc6859a5da13c8bc9ce0c1e502a38418e3cb8", SecondaryLaunchConfigs:map[string]string{"appdata":"a4b64bdd56ddf28671e2787b7fc583bb55b804e9", "phpfpm":"5b7975000c982dd602f04b98f9e55f63d3b9817c", "setup":"367a2ef15c2a8d522e9f05f9ed23229eb02b05bd"}}
ERRO[0000] Failed Creating app : Bad response statusCode [422]. Status [422 status code 422]. Body: [code=NotUnique, fieldName=name] from [http://rancher.storyx.company:8080/v1/services]
```

Expected:

Spinning up all containers.

**Comment by willseward** [comment] 2016-04-19 18:02
Verified in Rancher v1.0.1 as well

**Comment by deniseschannon** [comment] 2016-04-25 21:56
I was unable to reproduce.

I used a simplified docker-compose.yml and it had no issues launching even tho it's using teh same volume name. 

Is this a fresh stack? Do you already have a service called `app` in the stack?

```
app:
  image: nginx
  ports:
    - "80:80"
  links:
    - phpfpm
    - db
  volumes_from:
    - appdata
  labels:
    io.rancher.sidekicks: appdata, phpfpm, setup

appdata:
  image: nginx
  volumes:
    - "/var/magento2/src:/src"

phpfpm:
  image: nginx
  links:
    - db
  volumes_from:
    - appdata

db:
  image: nginx
  ports:
    - "3306:3306"
  volumes:
    - "/var/magento2/mysql:/var/lib/mysql"

setup:
  image: nginx
  links:
    - db
  volumes_from:
    - appdata
```

**Comment by willseward** [comment] 2016-05-03 14:00
I've experienced this issue a few more times since. I can best describe this issue as "transient". 

One thing I did find: If you create, destroy, and recreate a storage pool, it could contribute to the problem. Are the volume names left over after a storage pools is deleted? I know the actual UI element for the pool remains even after the backing service is deleted.

**Comment by gsf-greece** [comment] 2016-05-11 10:57
I think I ran into the same issue. It was definately the same error but I don't know if it was the same problem.  It happened after I deleted my stack and tried to run it again. It kept happening until I changed the stack name into a new one.

Rancher version: v1.1.0-dev1

**Comment by deniseschannon** [comment] 2016-05-11 22:18
@gsf-greece Were you using the same stack name? Did you delete the stack in the UI or rancher-compose?

I could see some use case where if you had the same services in the stack, you delete the stack (from the UI) and immediately try to launch services with the same name in the stack with the same name. There might be some timing issues where the service might not be marked as deleted.

**Comment by gsf-greece** [comment] 2016-05-12 08:15
@deniseschannon I was using the same stack name when I was getting the error. I deleted the stack from the UI. I also think I checked the Containers menu and the previous containers were removed.

Since I did this countless times before I had to add a shared volume without any issues, I think it might be connected to the same issue. I only guessed this was going to be fixed by changing the stack name from your comment "Is this a fresh stack?"

**Comment by danipolo** [comment] 2016-07-23 20:58
I have exactly the same problem here mentioned.

**Comment by cjellick** [comment] 2016-10-04 14:21
@ibuildthecloud and @alena1108 are reworking all the stack-base volume logic in rancher. We explicitly talked about supporting this scenario and it should be addressed. I'm going to reassign.

**Comment by deniseschannon** [comment] 2016-11-02 18:54
The new storage drivers should allow ability to use the same volume between multiple containers.

**Comment by sangeethah** [comment] 2016-11-08 04:10
Tested with latest build from master.

Tried to create a stack providing the docker-compose.yml provided in the issue.
Service dont start and we see the following error:
 "Activating (Expected state running but got error: instance is not running : Dependencies readiness error)"

<img width="1376" alt="screen shot 2016-11-07 at 8 09 50 pm" src="https://cloud.githubusercontent.com/assets/4266958/20086561/2a737976-a526-11e6-9aab-0cd86caada44.png">

**Comment by dj-hedgehog** [comment] 2016-11-18 12:38
The workaround I used was to get rid of all data containers and mount the directory directly instead.
When I'm trying to create the stack above no matter how I call `appdata`. I always get the `Name NotUnique` error. What can I do about this?

@deniseschannon What storage drivers are you talking about?

**Comment by alena1108** [comment] 2016-12-14 21:57
@sangeethah the issue you are hitting, is not related to the original issue. The problem is most likely caused by the instance erroring out to start. You might want to check container logs to double check that. In the original issue, service failed to create with 422 error. Reassigning back for verification

**Comment by sangeethah** [comment] 2016-12-29 19:59
Tested with rancher-server version - v1.3.0-rc2
Added following env variable for db service:
```
  environment:
    - MYSQL_ROOT_PASSWORD=test
    - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    - MYSQL_RANDOM_ROOT_PASSWORD=test
```

app service is not able to start successfully:

<img width="1572" alt="screen shot 2016-12-29 at 11 58 55 am" src="https://cloud.githubusercontent.com/assets/4266958/21553643/3efdd0b0-cdbe-11e6-91a4-9f78fb1c5d1c.png">


app1 container fails to start with the following error - Starting (Waiting for dependencies)

app-1 container logs:

```
12/29/2016 11:53:44 AM2016/12/29 19:53:44 [emerg] 12#12: host not found in upstream "php-fpm:9000" in /etc/nginx/conf.d/default.conf:2
12/29/2016 11:53:44 AMnginx: [emerg] host not found in upstream "php-fpm:9000" in /etc/nginx/conf.d/default.conf:2
12/29/2016 11:53:57 AM2016/12/29 19:53:57 [emerg] 12#12: host not found in upstream "php-fpm:9000" in /etc/nginx/conf.d/default.conf:2
12/29/2016 11:53:57 AMnginx: [emerg] host not found in upstream "php-fpm:9000" in /etc/nginx/conf.d/default.conf:2
```

**Comment by airtonix** [comment] 2016-12-31 13:17
@sangeethah @alena1108 would this apply to my concourse template I'm trying to spin up at home? 
https://github.com/airtonix/rancher-catalog/blob/master/templates/concourse/0/docker-compose.yml

I'm getting similar errors: 

```
12/31/2016 11:40:53 PMtime="2016-12-31T13:10:53Z" level=info msg="Stack Create Event Received" eventId=f47f0293-a9ee-4a5f-92fc-7ddbd3343e71 resourceId=1st31
12/31/2016 11:40:53 PMtime="2016-12-31T13:10:53Z" level=info msg="[concourse:]: Creating project " eventId=f47f0293-a9ee-4a5f-92fc-7ddbd3343e71 resourceId=1st31
12/31/2016 11:40:53 PMtime="2016-12-31T13:10:53Z" level=info msg="[concourse:concourse-db]: Creating " eventId=f47f0293-a9ee-4a5f-92fc-7ddbd3343e71 resourceId=1st31
12/31/2016 11:40:53 PMtime="2016-12-31T13:10:53Z" level=info msg="Creating service concourse-db"
12/31/2016 11:40:53 PMtime="2016-12-31T13:10:53Z" level=info msg="[concourse:concourse-db]: Created " eventId=f47f0293-a9ee-4a5f-92fc-7ddbd3343e71 resourceId=1st31
12/31/2016 11:40:53 PMtime="2016-12-31T13:10:53Z" level=info msg="[concourse:concourse-tsa]: Creating " eventId=f47f0293-a9ee-4a5f-92fc-7ddbd3343e71 resourceId=1st31
12/31/2016 11:40:53 PMtime="2016-12-31T13:10:53Z" level=info msg="Creating service concourse-tsa"
12/31/2016 11:40:53 PMtime="2016-12-31T13:10:53Z" level=info msg="[concourse:concourse-tsa]: Created " eventId=f47f0293-a9ee-4a5f-92fc-7ddbd3343e71 resourceId=1st31
12/31/2016 11:40:53 PMtime="2016-12-31T13:10:53Z" level=info msg="[concourse:concourse-worker]: Creating " eventId=f47f0293-a9ee-4a5f-92fc-7ddbd3343e71 resourceId=1st31
12/31/2016 11:40:53 PMtime="2016-12-31T13:10:53Z" level=info msg="Creating service concourse-worker"
12/31/2016 11:40:54 PMtime="2016-12-31T13:10:54Z" level=error msg="Failed Creating concourse-worker : Bad response statusCode [422]. Status [422 status code 422]. Body: [code=NotUnique, baseType=error, fieldName=name] from [http://localhost:8080/v2-beta/projects/1a5/services]"
12/31/2016 11:40:54 PMtime="2016-12-31T13:10:54Z" level=info msg="[concourse:concourse-certs]: Creating " eventId=f47f0293-a9ee-4a5f-92fc-7ddbd3343e71 resourceId=1st31
12/31/2016 11:40:54 PMtime="2016-12-31T13:10:54Z" level=info msg="[concourse:concourse-certs]: Created " eventId=f47f0293-a9ee-4a5f-92fc-7ddbd3343e71 resourceId=1st31
12/31/2016 11:40:54 PMtime="2016-12-31T13:10:54Z" level=error msg="Failed to start: concourse-worker : Bad response statusCode [422]. Status [422 status code 422]. Body: [code=NotUnique, baseType=error, fieldName=name] from [http://localhost:8080/v2-beta/projects/1a5/services]"
12/31/2016 11:40:54 PMtime="2016-12-31T13:10:54Z" level=error msg="Stack Create Event Failed: Bad response statusCode [422]. Status [422 status code 422]. Body: [code=NotUnique, baseType=error, fieldName=name] from [http://localhost:8080/v2-beta/projects/1a5/services]" eventId=f47f0293-a9ee-4a5f-92fc-7ddbd3343e71 resourceId=1st31
12/31/2016 11:40:54 PMtime="2016-12-31T13:10:54Z" level=info msg="[concourse:]: Project created " eventId=f47f0293-a9ee-4a5f-92fc-7ddbd3343e71 resourceId=1st31
```

**Comment by dahendel** [comment] 2017-05-19 16:04
I am having the same issue. It is extremely frustrating.

[https://github.com/dahendel/rancher-app-catalog/tree/master/infra-templates/consul/1](url)

**Comment by vincent99** [comment] 2017-05-19 17:00
@dahendel 422 just means validation failed, there are infinite unrelated ways to cause that.  Yours is that your rancher-compose defines a service called `consul` which has neither an image nor a selector in docker-compose... Because the one it is supposed to correspond to is called `consul-clients`.

**Comment by dahendel** [comment] 2017-05-19 18:20
@vincent99 Thanks. I have been banging my head on this., and missed that tiny detail.

**Comment by rawmind0** [comment] 2017-10-04 17:45
I get same issue with v1.6.10...

Tested it with ```Elasticsearch Cluster 5.5.1``` package, getting the same error with different services inside same package.

It happens once you deploy the package from catalog, you remove it and immediately redeploy it  with same name. 

Redeploy 1 failing es-data service....
```
time=“2017-10-04T14:00:38Z” level=info msg=“Stack Create Event Received” eventId=05c0a828-4b59-4d11-a2e3-5c17124cf11b resourceId=1st358
time=“2017-10-04T14:00:38Z” level=info msg=“Creating volume template es-storage-volume”
time=“2017-10-04T14:00:38Z” level=info msg=“[es-cluster:]: Creating project ” eventId=05c0a828-4b59-4d11-a2e3-5c17124cf11b resourceId=1st358
time=“2017-10-04T14:00:38Z” level=info msg=“[es-cluster:es-data]: Creating ” eventId=05c0a828-4b59-4d11-a2e3-5c17124cf11b resourceId=1st358
time=“2017-10-04T14:00:38Z” level=info msg=“[es-cluster:es-client]: Creating ” eventId=05c0a828-4b59-4d11-a2e3-5c17124cf11b resourceId=1st358
time=“2017-10-04T14:00:38Z” level=info msg=“[es-cluster:es-master]: Creating ” eventId=05c0a828-4b59-4d11-a2e3-5c17124cf11b resourceId=1st358
time=“2017-10-04T14:00:38Z” level=info msg=“Creating service es-client”
time=“2017-10-04T14:00:38Z” level=info msg=“Creating service es-master”
time=“2017-10-04T14:00:38Z” level=info msg=“Creating service es-data”
time=“2017-10-04T14:00:39Z” level=error msg=“Failed Creating es-data : Bad response statusCode [422]. Status [422 status code 422]. Body: [code=NotUnique, fieldName=name, baseType=error] from [http://localhost:8080/v2-beta/projects/1a14/services]”
time=“2017-10-04T14:00:39Z” level=error msg=“Failed to start: es-data : Bad response statusCode [422]. Status [422 status code 422]. Body: [code=NotUnique, fieldName=name, baseType=error] from [http://localhost:8080/v2-beta/projects/1a14/services]”
time=“2017-10-04T14:00:39Z” level=info msg=“[es-cluster:es-client]: Created ” eventId=05c0a828-4b59-4d11-a2e3-5c17124cf11b resourceId=1st358
time=“2017-10-04T14:00:39Z” level=info msg=“[es-cluster:es-master]: Created ” eventId=05c0a828-4b59-4d11-a2e3-5c17124cf11b resourceId=1st358
time=“2017-10-04T14:00:39Z” level=info msg=“[es-cluster:es-sysctl]: Creating ” eventId=05c0a828-4b59-4d11-a2e3-5c17124cf11b resourceId=1st358
time=“2017-10-04T14:00:39Z” level=info msg=“[es-cluster:es-sysctl]: Created ” eventId=05c0a828-4b59-4d11-a2e3-5c17124cf11b resourceId=1st358
time=“2017-10-04T14:00:39Z” level=info msg=“[es-cluster:es-storage]: Creating ” eventId=05c0a828-4b59-4d11-a2e3-5c17124cf11b resourceId=1st358
time=“2017-10-04T14:00:39Z” level=info msg=“[es-cluster:es-storage]: Created ” eventId=05c0a828-4b59-4d11-a2e3-5c17124cf11b resourceId=1st358
time=“2017-10-04T14:00:39Z” level=error msg=“Stack Create Event Failed: Bad response statusCode [422]. Status [422 status code 422]. Body: [code=NotUnique, fieldName=name, baseType=error] from [http://localhost:8080/v2-beta/projects/1a14/services]” eventId=05c0a828-4b59-4d11-a2e3-5c17124cf11b resourceId=1st358
time=“2017-10-04T14:00:39Z” level=info msg=“[es-cluster:]: Project created ” eventId=05c0a828-4b59-4d11-a2e3-5c17124cf11b resourceId=1st358
2017-10-04 14:00:39,871 ERROR [4cdf2363-83f3-40e8-9d05-bcc6f92d2078:6461488] [stack:358] [stack.create] [] [cutorService-67] [c.p.e.p.i.DefaultProcessInstanceImpl] Agent error for [stack.create.reply;handler=rancher-compose-executor]: Bad response statusCode [422]. Status [422 status code 422]. Body: [code=NotUnique, fieldName=name, baseType=error] from [http://localhost:8080/v2-beta/projects/1a14/services]
2017-10-04 14:00:40,177 ERROR [:] [] [] [] [cutorService-67] [.e.s.i.ProcessInstanceDispatcherImpl] Agent error for [stack.create.reply;handler=rancher-compose-executor]: Bad response statusCode [422]. Status [422 status code 422]. Body: [code=NotUnique, fieldName=name, baseType=error] from [http://localhost:8080/v2-beta/projects/1a14/services]
```

Redeploy 2 failing es-client service....
```
time=“2017-10-04T14:04:57Z” level=info msg=“Stack Create Event Received” eventId=e3a06db5-b774-4b52-9314-6d4af25377bd resourceId=1st359
time=“2017-10-04T14:04:57Z” level=info msg=“Creating volume template es-storage-volume”
time=“2017-10-04T14:04:57Z” level=info msg=“[es-cluster:]: Creating project ” eventId=e3a06db5-b774-4b52-9314-6d4af25377bd resourceId=1st359
time=“2017-10-04T14:04:57Z” level=info msg=“[es-cluster:es-data]: Creating ” eventId=e3a06db5-b774-4b52-9314-6d4af25377bd resourceId=1st359
time=“2017-10-04T14:04:57Z” level=info msg=“[es-cluster:es-master]: Creating ” eventId=e3a06db5-b774-4b52-9314-6d4af25377bd resourceId=1st359
time=“2017-10-04T14:04:57Z” level=info msg=“[es-cluster:es-client]: Creating ” eventId=e3a06db5-b774-4b52-9314-6d4af25377bd resourceId=1st359
time=“2017-10-04T14:04:57Z” level=info msg=“Creating service es-master”
time=“2017-10-04T14:04:57Z” level=info msg=“Creating service es-data”
time=“2017-10-04T14:04:57Z” level=info msg=“Creating service es-client”
time=“2017-10-04T14:04:57Z” level=error msg=“Failed Creating es-client : Bad response statusCode [422]. Status [422 status code 422]. Body: [code=NotUnique, fieldName=name, baseType=error] from [http://localhost:8080/v2-beta/projects/1a14/services]”
time=“2017-10-04T14:04:58Z” level=info msg=“[es-cluster:es-master]: Created ” eventId=e3a06db5-b774-4b52-9314-6d4af25377bd resourceId=1st359
time=“2017-10-04T14:04:58Z” level=info msg=“[es-cluster:es-data]: Created ” eventId=e3a06db5-b774-4b52-9314-6d4af25377bd resourceId=1st359
time=“2017-10-04T14:04:58Z” level=info msg=“[es-cluster:es-sysctl]: Creating ” eventId=e3a06db5-b774-4b52-9314-6d4af25377bd resourceId=1st359
time=“2017-10-04T14:04:58Z” level=info msg=“[es-cluster:es-storage]: Creating ” eventId=e3a06db5-b774-4b52-9314-6d4af25377bd resourceId=1st359
time=“2017-10-04T14:04:58Z” level=info msg=“[es-cluster:es-storage]: Created ” eventId=e3a06db5-b774-4b52-9314-6d4af25377bd resourceId=1st359
time=“2017-10-04T14:04:58Z” level=info msg=“[es-cluster:es-sysctl]: Created ” eventId=e3a06db5-b774-4b52-9314-6d4af25377bd resourceId=1st359
time=“2017-10-04T14:04:58Z” level=error msg=“Failed to start: es-client : Bad response statusCode [422]. Status [422 status code 422]. Body: [code=NotUnique, fieldName=name, baseType=error] from [http://localhost:8080/v2-beta/projects/1a14/services]”
time=“2017-10-04T14:04:58Z” level=error msg=“Stack Create Event Failed: Bad response statusCode [422]. Status [422 status code 422]. Body: [code=NotUnique, fieldName=name, baseType=error] from [http://localhost:8080/v2-beta/projects/1a14/services]” eventId=e3a06db5-b774-4b52-9314-6d4af25377bd resourceId=1st359
time=“2017-10-04T14:04:58Z” level=info msg=“[es-cluster:]: Project created ” eventId=e3a06db5-b774-4b52-9314-6d4af25377bd resourceId=1st359
2017-10-04 14:04:58,967 ERROR [d2c9b4f1-8149-4212-b4f8-5b228a8a240b:6462029] [stack:359] [stack.create] [] [cutorService-63] [c.p.e.p.i.DefaultProcessInstanceImpl] Agent error for [stack.create.reply;handler=rancher-compose-executor]: Bad response statusCode [422]. Status [422 status code 422]. Body: [code=NotUnique, fieldName=name, baseType=error] from [http://localhost:8080/v2-beta/projects/1a14/services]
2017-10-04 14:04:59,142 ERROR [:] [] [] [] [cutorService-63] [.e.s.i.ProcessInstanceDispatcherImpl] Agent error for [stack.create.reply;handler=rancher-compose-executor]: Bad response statusCode [422]. Status [422 status code 422]. Body: [code=NotUnique, fieldName=name, baseType=error] from [http://localhost:8080/v2-beta/projects/1a14/services]
```

Waiting a couple of minutes between remove and redeploy the package, issue doesn't occur... 

It seems a race condition, Services are removed async and some of them could still exist transitioning to removed once the stack is already removed. Redeploying so quickly from the catalog could eventually  generates status code 422, notUnique service name error.

**Comment by TheCase** [comment] 2018-02-08 17:11
Similar issue here on 1.6.12.  I can Delete the stack and it will stand up, no problem.  I only see the `NotUnique` error when upgrading the catalog version that has these new services:
```time="2018-02-07T23:32:42Z" level=error msg="Failed to start: es-data-blue : Bad response statusCode [422]. Status [422 status code 422]. Body: [fieldName=name, code=NotUnique, baseType=error] from [http://localhost:8080/v2-beta/projects/1a5/services]" 
time="2018-02-07T23:32:42Z" level=error msg="Failed to start: es-data-green : Bad response statusCode [422]. Status [422 status code 422]. Body: [fieldName=name, code=NotUnique, baseType=error] from [http://localhost:8080/v2-beta/projects/1a5/services]" ```

**Comment by deniseschannon** [comment] 2018-08-22 04:34
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.

**Closed by deniseschannon** 2018-08-22 04:34 UTC
Labels: kind/bug, status/autoclosed, status/reopened
