### ISSUE TITLE
If missing required field for Services, the Create button stays dimmed and says Saving...

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#2567] opened 2015-11-05 19:30 UTC
Version - Master with reskin UI

Steps:
1.  Add Service
2.  Don't put in a Name and click on Create

Results:
The Create button dims and it says Saving... So I can no longer create service.

Expected:
The button should go back to active and say Create.  All other Adds work this way.

**Comment by deniseschannon** [comment] 2015-11-05 19:46
Duplicate of #2566. Just found it in my training today. ;)

**Closed by deniseschannon** 2015-11-05 19:46 UTC
Labels: area/service, area/ui, kind/bug
