### ISSUE TITLE
v2.6.5- Release testing - Run Automation suite against 2.6.5-rc

### ISSUE THREAD

**Issue by Jono-SUSE-Rancher** [rancher/rancher#37348] opened 2022-04-13 18:50 UTC
Run Automation suite against 2.6.5-rc (3 weeks before release)

Jenkins | Assignee | Status
-- | -- | --
rancher-v3_additional_tests | TBD | 
rancher-v3_additional_tests_cli | TBD |
rancher-v3_additional_tests_long | TBD |
rancher-v3_auth_enabled_rancher | TBD |
rancher-v3_cluster_auth_grb_istio_monitoring | TBD |

---
Start date - Post Bug complete date - TBD
Due by - TBD

**Comment by timhaneunsoo** [comment] 2022-05-02 17:10
Closing ticket as duplicate of [313](https://github.com/rancher/qa-tasks/issues/313)

**Closed** 2022-05-02 17:11 UTC
Labels: kind/task, [zube]: Release Task, qa-release-task
