### ISSUE TITLE
[BUG] Enabling ACE after cluster provisioning results in unusable kubeconfig contexts

### ISSUE THREAD

**Issue by thatmidwesterncoder** [rancher/rancher#41832] opened 2023-06-13 21:16 UTC
**Rancher Server Setup**
- Rancher version: v2.7.3+, reported on 2.7.3 but persists to newest version
- Installation option (Docker install/Helm Chart): Docker and running locally from source
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): k3s latest via k3d
- Proxy/Cert Details:

**Information about the Cluster**
- Kubernetes version: 1.25.9, but any version most likely will be effected
- Cluster Type (Local/Downstream): Downstream
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider): Custom and DigitalOcean

**User Information**
- What is the role of the user logged in? (Admin/Cluster Owner/Cluster Member/Project Owner/Project Member/Custom): Admin
  - If custom, define the set of permissions: all

**Describe the bug**

When you create a RKE2 cluster on existing nodes or provisioned through <Cloud Provider> and activate "Authorized Cluster Endpoint" after the cluster is available; connecting to the ACE endpoint results in a "401 Unauthorized" even though there is a cert/token present. 

The ACE works fine _if it is enabled when creating the cluster_. This behavior only occurs when enabling ACE after creation.

**To Reproduce**

1. Create a RKE2 cluster without ACE, can leave everything default
2. Once it is provisioned, edit the cluster and activate ACE
3. Download a kubeconfig and try to use an ACE context

**Result**
The ACE context does not work. 

**Expected Result**

The ACE should work exactly as it does if it is enabled during provisioning -> e.g. exactly like a regular k8s context hitting the infrastructure node(s).

**Screenshots**

n/a

**Additional context**

- The kubeconfig looks fine - cert is present for ACE, and token is used for relay context
- I dug a bit into it due to the fact that it appears CRDs for `clusterauthtoken` aren't present, thus the kube-api-proxy pod barks about not being able to fetch the token when the user comes in on the ACE endpoint
- applying the diff below seems to fix it. But I am not sure of the other repercussions that could be caused by having the agent watching more CRDs. Maybe these CRDs are harder/heavier to watch and thats why we wouldn't  want them installed on every cluster. 
- this also makes rancher be the part that says "install X CRDs", I'm not sure if this should be moved somewhere else. 

<details>
<summary>always_install_token_crds.diff</summary>

```diff
diff --git a/pkg/controllers/managementuser/controllers.go b/pkg/controllers/managementuser/controllers.go
index f08e9909a..7a9129214 100644
--- a/pkg/controllers/managementuser/controllers.go
+++ b/pkg/controllers/managementuser/controllers.go
@@ -48,13 +48,12 @@ func Register(ctx context.Context, mgmt *config.ScaledContext, cluster *config.U
 	// register secrets controller for impersonation
 	cluster.Core.Secrets("").Controller()
 
-	if clusterRec.Spec.LocalClusterAuthEndpoint.Enabled {
-		err := clusterauthtoken.CRDSetup(ctx, cluster.UserOnlyContext())
-		if err != nil {
-			return err
-		}
-		clusterauthtoken.Register(ctx, cluster)
+	// create the auth CRDs
+	err := clusterauthtoken.CRDSetup(ctx, cluster.UserOnlyContext())
+	if err != nil {
+		return err
 	}
+	clusterauthtoken.Register(ctx, cluster)
 
 	// Ensure these caches are started
 	cluster.Core.Namespaces("").Controller()
```

</details>

SURE-6359
SURE-6353

**Comment by Sahota1225** [comment] 2023-07-28 17:33
duplicate of https://github.com/rancher/rancher/issues/42255

**Comment by KevinKeo** [comment] 2023-08-11 09:31
Same issue here, with the stable rancher and provisioning latest RKE2.

**Comment by ifelsefi** [comment] 2023-11-10 15:16
Restarting upstream pods on local cluster fixes the issue.  I am running Rancher 2.7.1 v1.24.10+rke2r1.

**Comment by Zappelphilipp** [comment] 2024-01-16 08:03
running Rancher 2.8 and K8s v1.26.11 +rke2r1 - same problem. 
can confirm, restarting Rancher (development environment - `docker restart rancher`) fixed it.

**Comment by harrisonbc** [comment] 2024-02-15 10:26
Running Rancher v2.8.2 and can confirm the issue and the resolution was to restart the Upstream Rancher Pods.

**Comment by dantecl** [comment] 2024-03-21 14:36
+1 on Rancher 2.8.2 here, and also affected by this bug. For us, a `kubectl rollout restart rancher -n cattle-system` populated the CRD/token and things worked without downtime, but really not ideal.

**Comment by atsai1220** [comment] 2024-04-12 00:44
Not sure if exactly the same issue. We have Rancher v2.7.9 and the CRDs for `ClusterAuthToken` exist in the cluster except generating a new Kubeconfig does not create new ClusterAuthTokens in _some_ rke2 clusters. They all have ACE enabled.

**Comment by Tbag12** [comment] 2024-04-22 13:41
Will this problem be fixed in the next version? ? ? Currently I am using v2.8.3 and also encountered

**Comment by susesgartner** [comment] 2024-06-24 15:22
Ticket #41832 - Test Results - ✅
---
 
| Scenario | Test Case | Result |
|---|---|---|
| 1. | Enable Ace after cluster provisioning | PASS |
| 2. | Enable Ace before cluster provisioning | PASS |
 
---
Verified with (HA Helm or Docker) on Rancher `v2.9-4dd0c38a2aab4f77271c07d2c887ecf5bbcea5e3-head`:
---
 
Scenario 1: Enable Ace after cluster provisioning
---
1. Provision an rke2 cluster
2. After the cluster has provisioned, enable ACE.
3. Switch contexts to the ACE context
4. Verify the ACE context works as intended
 
Results: The ACE context can be used without any errors being observed
 
---
 
Scenario 2: Enable Ace before cluster provisioning
---
1. Provision an rke2 cluster with ACE enabled
3. Switch contexts to the ACE context
4. Verify the ACE context works as intended
 
Results: The ACE context can be used without any errors being observed

**Closed by susesgartner** 2024-06-24 15:22 UTC
Labels: kind/bug, priority/0, internal, QA/XS, area/ace, team/hostbusters, JIRA
