### ISSUE TITLE
Editing Default environment

### ISSUE THREAD

**Issue by firegrass** [rancher/rancher#1719] opened 2015-08-03 11:51 UTC
![rancher_members_bug](https://cloud.githubusercontent.com/assets/115086/9036889/c2911ba6-39dd-11e5-9c8a-c5e7dcec3e04.png)

![rancher_members_bug2](https://cloud.githubusercontent.com/assets/115086/9036928/23d3ba68-39de-11e5-9e32-a32aa95fc00a.png)

When editing the default environment it won't save and errors. Creating a new environment works fine, but then errors when you edit it. Looks like you have to explicitly add another owner/member at creation.

**Comment by deniseschannon** [comment] 2015-08-03 16:17
Duplicate of #1590. 

For the "Default" environment, you need to click on the environment name at least once before the edit from the dropdown on the "Manage Environments" page will work. 

What version of Rancher Server are you running? When I try to add a new environment, it only saves if there is at least one owner in it. I'm running v0.31.0. So, the UI should be forcing you to create an environment with at least 1 owner. The owner of the "Default" environment (which is you) is not showing up on the Edit page.

**Closed by deniseschannon** 2015-08-03 16:17 UTC
