### ISSUE TITLE
Cluster explorer doesn't honour the "Table Rows per Page" setting on workload tab

### ISSUE THREAD

**Issue by carolosf** [rancher/rancher#38312] opened 2022-07-18 17:28 UTC
**Rancher Server Setup**
- Rancher version: 2.6.5
- Installation option (Docker install/Helm Chart):
   - terraform modules rancher2 and rke using RKE1
- Proxy/Cert Details:

**Information about the Cluster**
- Kubernetes version: v1.23.6-rancher-1
- Cluster Type (Local/Downstream):
   -  Problem affects local and downstream clusters, both clusters are rancher 2.6.5 and using kubes v1.23.6-rancher-1 and created with terraform

**User Information**
- What is the role of the user logged in? (Admin)

**Describe the bug**
The new UI (cluster explorer) doesn't honour the "Table Rows per Page" setting on workload tab. There are other parts of the UI where this is also ignored.

**To Reproduce**

- Navigate to your user icon and hit preferences
- Select "Table Rows per Page" to be 500
- Choose a down stream cluster 
- Expand the Cluster menu item in the left side bar
- Click on Projects/Namespaces
- Click on a namespace that has 150 workloads
- Go to the Workloads tab

**Result**
A page that only has 10 workload items displayed even though my "Table Rows per Page" setting is set to 500.

**Expected Result**
All 150 workload items should be displayed.

**Screenshots**
Setting:
![rancher 265 settings](https://user-images.githubusercontent.com/2076671/179567640-f0763368-9b45-4322-b6de-4530ed976022.png)

Problem page:
![rancher_265_ignoring_table_rows](https://user-images.githubusercontent.com/2076671/179567713-7114d48e-2317-4632-9b9a-9b9a2f8e070f.png)

**Additional context**
First thank you for all the hard work you all put in.

The page counter is also wrong it incorrectly reports 10 pages but there are 15.

We have a rancher cluster running over 17000 deployments, these are organised into 100 namespaces with around 150 deployments each used by hundreds of users. The paging through results issue is so annoying for our users that we are considering not upgrading from Rancher 2.5.* to Rancher 2.6.* until this is fixed.

**Comment by rak-phillip** [comment] 2022-07-22 00:21
@carolosf thanks for raising this issue an helping to make Rancher better.

I'm going to close this issue because it appears to be a duplicate of rancher/dashboard#6346 and rancher/dashboard#6027, which should be fixed in the upcoming 2.6.7 release. Please, feel free to reopen if you think the issue hasn't been resolved.

**Closed by rak-phillip** 2022-07-22 00:21 UTC
