### ISSUE TITLE
Cannot add registry for all namespaces in the project

### ISSUE THREAD

**Issue by mscbpi** [rancher/rancher#27156] opened 2020-05-19 22:52 UTC
**What kind of request is this (question/bug/enhancement/feature request):**

Bug

**Steps to reproduce (least amount of steps as possible):**

Add a registry in a project and select "Available for all namespaces in this project"

**Result:**

Stuck on Saving

**Other details that may be helpful:**

```
component.js:79 Uncaught TypeError: Cannot read property 'id' of null
```
which leads to

```
var nsId = this.namespace.id,
```
It seems the GUI does not support a `null` namespace, which is the case when selecting the option.

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI):
v2.4.3
- Installation option (single install/HA):
HA

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported):
- Machine type (cloud/VM/metal) and specifications (CPU/memory):
- Kubernetes version (use `kubectl version`):

```
(paste the output here)
```

- Docker version (use `docker version`):

```
(paste the output here)
```

**Comment by sangeethah** [comment] 2020-05-19 23:22
Duplicate of https://github.com/rancher/rancher/issues/27117

**Closed by sangeethah** 2020-05-19 23:22 UTC
