### ISSUE TITLE
Cluster owner not able to edit Harvester cluster without accessing cloud credential

### ISSUE THREAD

**Issue by guangbochen** [rancher/rancher#34800] opened 2021-09-18 06:54 UTC
**Rancher Server Setup**
- Rancher version: `v2.6-head`
- Installation option (Docker install/Helm Chart): All works
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): RKE2
- Proxy/Cert Details:

**Describe the bug**
Cloud credentials aren't shareable, so if you create a cluster with user A, make user B a cluster owner (or other roles), and then come to the edit screen as user B, you will not find the credential here.

**To Reproduce**
1. login as a cluster-admin user A, and create a new cluster using Harvester/VMWare vSphere RKE2 node driver
2. add another user B to the cluster as a cluster owner and create the cluster
3. login as with a user B
4. click to edit the cluster and it shows `cloud credential no found`, therefore users have to add custom cloud credentials in order to edit this cluster properly
![image](https://user-images.githubusercontent.com/4569037/133878526-8cdcb9db-9b50-44b7-85dd-ea1de966e974.png)

**Result**
The user B may not have access to the VMWare vSphere, but would prefer to edit the assigned cluster as a cluster owner.

**Expected Result**
~~Cloud credentials should be shareable for the cluster owners(but may need some concerns of not expose the credentails)~~ 

**Screenshots**

**Additional context**
as mentioned in the https://github.com/rancher/dashboard/pull/3881

**Comment by kinarashah** [comment] 2021-09-22 20:29
**There are two ways we can scale up nodes:** 
1) Nodes page - using `(+)` in UI to update node pools 
2) Edit Config/Edit Cluster and increment machine count 

**RKE1:** 
- Cluster owner is able to scale up nodes using both Nodes page and Edit Config. 
- It works for all node drivers, tested on EC2, DO and Vsphere. 
- It works for both v2.5.8, v2.5.9 and v2.6.0. 

**RKE2:**   
- Cluster owner is able to scale up nodes for all node drivers (tested on EC2, DO and Vsphere) **only** using Nodes page

**RKE2: Edit Config behavior** This changes based on the driver: 
**EC2**
On Edit Config, there's an error - `The request must contain the parameter AWSAccessKeyId`. 
- This error doesn't seem to prevent the Edit Cluster. 
- On Save, there's a new error: `"VPC/Subnet" is required` which blocks the save. 
- Edit as YAML works. 

**DigitalOcean** 
On Edit Config, there's no error whatsoever. Scaling up works. 

**Vsphere**
On Edit Config, there's an error - `Cloud credential not found`. 
- This error doesn't seem to prevent the Edit Cluster. 
- On Save, cluster edit goes through and node comes up successfully. 

We need to figure out why there are different errors for node drivers on Edit Config. This mostly seems related to UI, because Edit as YAML works. cc @sowmyav27 @anupama2501 @vincent99

**Comment by yasker** [comment] 2021-09-22 21:58
Unassign @sowmyav27 due to it's not fixed yet.

**Comment by gaktive** [comment] 2021-09-22 22:43
If it turned out UI work is needed, either a file an item in `rancher/dashboard`, transfer this there or ping me to do so.

**Comment by gaktive** [comment] 2021-09-22 22:44
@anupama2501 if you do file items, cross link them here so I can find them easily.

**Comment by anupama2501** [comment] 2021-09-22 22:54
Ref issues on dashboard:
https://github.com/rancher/dashboard/issues/4257 
https://github.com/rancher/dashboard/issues/4256

**Comment by kinarashah** [comment] 2021-09-23 18:21
The issue's original description is no longer valid. We're not going to make cloud credentials sharable. The expected behavior is for cluster owner to be able to Edit Clusters without accessing cloud credentials. https://github.com/rancher/dashboard/pull/3881#issuecomment-925554562

**Comment by snasovich** [comment] 2021-09-23 18:58
Updated milestone to 2.6.2 due to the amount of changes needed this close to 2.6.1 release.

**Comment by deniseschannon** [comment] 2021-09-23 22:38
Doesn't this mean that all of this is UI issues/errors and there is no backend work? Shouldn't this be closed? cc: @kinarashah

**Comment by kinarashah** [comment] 2021-09-23 22:41
@deniseschannon We updated issue title and description to track the current problem, `Cluster owner not able to edit Harvester cluster without accessing cloud credential`, so don't need to close it yet.

**Comment by snasovich** [comment] 2021-11-03 23:10
This has been discussed with @thedadams @cloudnautique @vincent99 and the conclusion is we want to allow users to edit cluster in case they don't have access to previously assigned cloud credentials. This also includes the ability to change to another cloud credentials they have access to.
Handling any EKS/AKS/GKE bugs is not in scope of this issue and separate GH issues will be created as needed.

**Comment by thedadams** [comment] 2021-11-10 18:54
Associated UI issue: https://github.com/rancher/dashboard/issues/4544

**Comment by TachunLin** [comment] 2021-11-22 12:20
Verified `not fixed` on master-d577bb6c-head with rancher v2.6.3-rc1 (node driver v.0.3.4)
[Please check more details in [harvester/harvester/#1348](https://github.com/harvester/harvester/issues/1348)

### Result
With cluster owner userB login and edit RKE2 cluster config,
The cloud credential can't be shared and loaded correctly while login with another userB
It shows error messgge: secrets "cc-9zkzk" is forbidden: User "u-7kxkd" cannot get resource "secrets" in API group "" in the namespace "cattle-global-data"

![image](https://user-images.githubusercontent.com/29251855/142857040-6b0c5643-a222-4c40-96b8-c0dbda188100.png)

**Comment by snasovich** [comment] 2021-11-22 16:25
@TachunLin , the fix is in https://github.com/rancher/rancher/commit/3517d0b2ff5daabe124b6c96b1e2cde40ccb44ba which is after v2.6.3-rc1.
Please either test on v2.6-head or if you need RC, in the next RC.

**Comment by thedadams** [comment] 2021-11-24 00:37
This situation with Harvester seems to be different from the original one in the description. You can see the error for Harvester is different from the error shown in the description.

The original issue involved making requests via the meta proxy. However, it looks like Harvester requests the cloud credential directly. This is a very different issue.

I have a possible fix for this Harvester issue, but I think it would be valuable to have a separate issue for that.

**Comment by snasovich** [comment] 2021-11-24 03:46
@guangbochen / @TachunLin , given the information above, could you please open a separate issue and assign it to @thedadams ? This specific issue is a general V2/RKE2 provisioning issue and was addressed; what you're running into now is Harvester-specific and requires a different fix. Thank you.

**Comment by TachunLin** [comment] 2021-11-24 05:10
@snasovich / @thedadams, according to the comment I open a new isuse [rancher/rancher/#35651](https://github.com/rancher/rancher/issues/35651) to separate the Harvester-specific issue. 

About the existing one, according to the description it probably reproduced by using VMWare vSphere
could you help to validate it since you might have the ESXi account.

**Comment by snasovich** [comment] 2021-11-24 20:01
@TachunLin , thank you. The original issue should be reproducible regardless of provider, so can be validated on DO/Azure/AWS.

@sowmyav27 , is this something your QA team can validate?

**Comment by sowmyav27** [comment] 2021-12-02 01:05
**On 2.6.2**

- Deployed an RKE2 DO cluster
- Add a user as cluster owner
- Login as cluster owner 
- Edit Config on the cluster
- Error seen `Unable to authenticate you`

<img width="1675" alt="Screen Shot 2021-12-01 at 5 02 38 PM" src="https://user-images.githubusercontent.com/26032343/144338936-b4e32752-8790-4cc2-83ff-3d5ccc98589c.png">

And scaling up node in the Edit Config page doesnt work since the node fails with error `Failed creating server (DigitaloceanMachine) in infrastructure provider: CreateError: Failure detected from referenced resource rke-machine.cattle.io/v1, Kind=DigitaloceanMachine with name "sowmya-rke2-26-...: Running pre-create checks... Creating machine... (sowmya-rke2-26-pool2-...) Creating SSH key... (sowmya-rke2-26-... Creating Digital Ocean droplet... Error creating machine: Error in driver during machine creation: POST https://api.digitalocean.com/v2/droplets: 422 You specified an invalid image for Droplet creation. The default lines below are for a sh/bash shell, you can specify the shell you're using, with the --shell flag.`

**On 2.6-head commit id: `46eb9d4`**
- Deployed an RKE2 DO cluster
- Add a user as cluster owner
- Login as cluster owner 
- Edit Config on the cluster
- No error seen and scaling up in thhis page works. Node comes up Active.

**Closed** 2021-12-02 05:27 UTC
Labels: [zube]: QA Working, area/provisioning-v2, feature/provisioned-rke2-k3s
