### ISSUE TITLE
Can't enter Openstack config data when adding a host. 

### ISSUE THREAD

**Issue by eebjr** [rancher/rancher#4719] opened 2016-05-06 21:12 UTC
In the latest Rancher release, the option for adding an openstack host seems to be missing.
From the UI, when I select openstack driver, no fields are shown.
From the API create action page, when I click openstackconfig I get; 
{
"id": "eabed400-4624-4d38-a654-33f29436e4cd",
"type": "error",
"links": { },
"actions": { },
"status": 404,
"code": "Not Found",
"message": "Not Found",
"detail": null,
}

See also the rancher forums:

https://forums.rancher.com/t/openstack-config-seems-to-be-missing-cant-add-a-host-to-openstack/2710?u=ebishop

See the rancher forums for a few more details:  

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v1.1.0-dev1` Cattle: `v0.160.3` UI: `v1.0.7` |
|Access|`localauth` `admin`|
|Route|`environments.index`|

**Comment by deniseschannon** [comment] 2016-05-06 21:15
I just noticed your UI comment, but I am unable to reproduce the UI side. When I select openstack on the other driver in the UI, all the fields show up for me. 

There is a known issue that you can't get any of the machine driver schemas individually by ID.

**Comment by eebjr** [comment] 2016-05-06 21:24
[cid:image001.png@01D1A7B3.AF0A08B0]

**Comment by vincent99** [comment] 2016-05-06 23:54
There's a separate issue where the driver configs can end up empty or with the wrong fields.. restarting the server should fix that.

**Comment by deniseschannon** [comment] 2016-05-12 20:25
@eebjr Did you try restarting the server to see if it helped you?

**Comment by eebjr** [comment] 2016-05-12 21:06
@deniseschannon, sorry, I replied to the email like a noob. Yes, restarting worked.

**Comment by deniseschannon** [comment] 2016-05-12 21:18
No problem. 

Closing in favor of https://github.com/rancher/rancher/issues/4563

**Closed by deniseschannon** 2016-05-12 21:18 UTC
Labels: kind/question
