### ISSUE TITLE
Link not established with sidekicked container

### ISSUE THREAD

**Issue by EliSnow** [rancher/rancher#1589] opened 2015-07-20 19:12 UTC
Rancher: v0.28.0
Cattle: v0.64.0
Rancher-compose: v0.22.0

With the following `docker-compose.yml`:

```yml
test-apache:
  ports:
  - 80:80/tcp
  restart: on-failure:5
  tty: true
  image: debian:jessie
  links:
  - test-node:node
  stdin_open: true
test-node:
  restart: on-failure:5
  tty: true
  image: debian:jessie
  stdin_open: true
  labels:
    io.rancher.sidekicks: test-apache
```
Container `test-apache` is not getting a link to `test-node`.

**Comment by ibuildthecloud** [comment] 2015-07-20 20:58
@alena I think when we setup the links to emulate Docker links we don't look at sidekicks.  Also, do you consider sidekicks for DNS?

**Comment by alena1108** [comment] 2015-07-21 16:50
@ibuildthecloud no, we don't look at the sidekicks when emulate docker links, thats a known issue. And yes, we doc consider sidekicks for DNS, but it works a bit different from the regular use case.

Lets say we have a service A, and B is its sidekick. To every instance of service A, instances of B will get resolved by "B". But to other services, B instances get resolved as "B.A"

**Comment by 1N50MN14** [comment] 2015-07-26 19:20
+1

**Comment by clintbeacock** [comment] 2016-06-03 15:53
Is there any workaround to this issue?  It's causing a lot of problems for me, as I've just discovered.  

I have some application services that are comprised of nginx containers (named app) and php sidekicks (named php)

Part of the start script for the nginx container is to set the php backend dynamically by resolving the ip it gets from php.  The problem is that all the nginx instances (I'm scaled to 6 in this case) resolve to the same php container, instead of each to their own.

I was wondering why my scaling up didn't seem to help in handling increased loads, and it's because only one php container is being hit.

This also causes major failures in downscaling a service, because if rancher chooses to remove the service that was housing the only resolving php container, the other nginx containers all fail (because the php ip is only set at the nginx container startup, and does not know what happens beyond that)

Please let me know if there's a quick workaround for this, as it's killing me in production.

I'd also like to +1 this as a priority item, as I'm likely not the only one affected by this.

I should have mentioned, I'm using rancher v1.0.1

**Comment by alena1108** [comment] 2016-06-10 21:39
@clintbeacock 

>> The problem is that all the nginx instances (I'm scaled to 6 in this case) resolve to the same php container, instead of each to their own.

Sidekick container is not pinned to the particular master container via DNS; DNS would return one of the service A records, not necessarily the container of the same host. DNS returns the random ip address of one of the service's instances. 

>> Please let me know if there's a quick workaround for this, as it's killing me in production.
I'd also like to +1 this as a priority item, as I'm likely not the only one affected by this.

To pin nginx to the sidekick's ip address of php service (located on the same host), we suggest this approach (using rancher metadata):

https://forums.rancher.com/t/sidekick-how-detect-primary-service-container/1992/2

For non-sidekick use cases, we suggest to use Load Balancer to ensure requests load distribution.

In the future, we are planning to assign service a VIP (virtual ip address) that is consistent through the service lifecycle. Service dns will get resolved to VIP, and then we would balance between service's instance's ips.

**Comment by clintbeacock** [comment] 2016-06-11 14:00
@alena1108 
Thanks.  I had a look initially at the metadata, but wasn't able to find what I needed.  The link you provided explains it perfectly for me.

**Comment by alena1108** [comment] 2016-07-08 22:04
closing the issue as we are not planning to add links for the sidekick. All the data sidekick needs, can be retrieved using metadata

**Closed by alena1108** 2016-07-08 22:04 UTC
Labels: area/service, kind/bug
