### ISSUE TITLE
Catalog Updates Does Not Pull New Images

### ISSUE THREAD

**Issue by ekristen** [rancher/rancher#8777] opened 2017-05-16 20:28 UTC
It seems that when you update a catalog entry, if the image hasn't change and has the label pull_image set to always, the new image will not be pulled if nothing about the service yaml has changed.

**Comment by joshwget** [comment] 2017-05-16 23:49
Duplicate of #5516. Please reopen if you disagree @ekristen.

**Closed by joshwget** 2017-05-16 23:49 UTC
Labels: kind/question
