### ISSUE TITLE
Show API response in embedded kubectl view

### ISSUE THREAD

**Issue by superseb** [rancher/rancher#15246] opened 2018-08-27 10:23 UTC
Launch kubectl execs into a pod from the `cattle-node-agent`(`-l app=cattle-agent`), but if it fails to find one, the API returns 404 but the UI keeps showing `Connecting`.

Would be also be good to grey out the window when the connection is closed (now it just says Closed on top without any other indication)

**Comment by tfiduccia** [comment] 2019-01-07 18:23
@superseb - Hello, David verified that the window greys out when the connection is closed but we can't reproduce the API returning a 404.  Can you please verify that happens?

**Comment by superseb** [comment] 2019-01-26 22:18
Window is greyed out but no explanation/API response.

<img width="1660" alt="screen shot 2019-01-26 at 22 54 42" src="https://user-images.githubusercontent.com/2620179/51793415-96443280-21c0-11e9-82d3-d61b076899d5.png">

**Comment by davidnuzik** [comment] 2019-02-14 22:48
Shell now repots why it was terminated:
`command terminated with non-zero exit code: Error executing in Docker Container: 137` is an example when we delete the `cattle-node-agent` DaemonSet for example.

But if I do something like delete `cattle-cluster-agent` Deployment we get no explanation in the UI shell. Just the gray border around the terminal indicating the connection is closed.

@n313893254 is there anyway to get more information when the websocket is closed or in closing state in the UI shell?
![image](https://user-images.githubusercontent.com/45179589/52822719-c2402e80-306f-11e9-9c13-b336f0c99743.png)

Here is an example, web socket is closed and it's nice that shell has grey border around now and indicates is closed but I think we want to print something in the terminal or have a pop-up error in the UI to make it very clear something went wrong.
![image](https://user-images.githubusercontent.com/45179589/52822763-e6037480-306f-11e9-9d7d-1a0fa87bff80.png)

**Comment by n313893254** [comment] 2019-02-15 06:43
@davidnuzik  I delete `cattle-cluster-agent`, and the UI shell still work.

I add error info in UI. https://github.com/rancher/ui/pull/2654#issue-252963437

**Comment by davidnuzik** [comment] 2019-02-16 15:48
Awesome @n313893254 thanks for adding the error info in the UI. This should help to make it very clear to the user there is an issue with the connection.

**Comment by davidnuzik** [comment] 2019-02-25 20:02
@n313893254 I deleted the `cattle-node-agent` pod in order to cause a websocket closure but do not see an error in the UI.

![image](https://user-images.githubusercontent.com/45179589/53365104-93427c00-38fd-11e9-9b99-18c7535cefa9.png)

![image](https://user-images.githubusercontent.com/45179589/53365085-8c1b6e00-38fd-11e9-96d7-088f93487cfa.png)

**Comment by n313893254** [comment] 2019-02-26 02:11
@davidnuzik Error displays here. The WebSocket is disconnected, and the code is 1000. 

![image](https://user-images.githubusercontent.com/18737885/53382284-b8db8e00-39ae-11e9-95fe-fd636cc93527.png)

**Comment by davidnuzik** [comment] 2019-02-26 20:23
Version: Master 2.2 (2/26/19)
Confirmed issue.

When there is an exception that will cause the kubectl shell to disconnect it's more clear now.
The shell has a thick gray border around it now.
The shell shows a code at the top-right when an error happens:

![image](https://user-images.githubusercontent.com/45179589/53443648-69568b80-39c9-11e9-9fe8-61313073e927.png)

In the browser dev console we see:
![image](https://user-images.githubusercontent.com/45179589/53443669-73788a00-39c9-11e9-8a20-3a2b16d370e9.png)

This makes it more clear that something went wrong.

@superseb if you have any input or this is not to your liking please let us know and explain. Thanks!

**Closed by davidnuzik** 2019-02-26 20:23 UTC
Labels: area/ui, kind/enhancement, status/ready-for-review, status/reopened, status/to-test, team/cn, version/2.0
