### ISSUE TITLE
Pipelines fail repeatedly. 

### ISSUE THREAD

**Issue by cloudnautique** [rancher/rancher#11765] opened 2018-02-28 23:07 UTC
**Rancher versions:**
rancher/server: 2.0 master 2/28

**Steps**
Added an "Imported" cluster
Enabled GH for pipelines
Click Add pipeline
setup repository
configured build step
removed stage 3
Save

Run Manual build

All builds fail

See:
```
time="2018-02-28T21:36:33Z" level=info msg="respData:{\"type\":\"Repository\",\"id\":22946960,\"name\":\"web\",\"active\":true,\"events\":[\"push\"],\"config\":{\"content_type\":\"json\",\"insecure_ssl\":\"1\",\"secret\":\"********\",\"url\":\"https://10.20.0.4/hooks?pipelineId=project-br9qq:pipeline-76trt\"},\"updated_at\":\"2018-02-28T21:36:33Z\",\"created_at\":\"2018-02-28T21:36:33Z\",\"url\":\"https://api.github.com/repos/cloudnautique/cattle/hooks/22946960\",\"test_url\":\"https://api.github.com/repos/cloudnautique/cattle/hooks/22946960/test\",\"ping_url\":\"https://api.github.com/repos/cloudnautique/cattle/hooks/22946960/pings\",\"last_response\":{\"code\":null,\"status\":\"unused\",\"message\":null}}"
time="2018-02-28T21:36:39Z" level=error msg="Error get Jenkins engine - error get jenkins token - secret \"jenkins\" not found"
E0228 21:36:39.931931       1 generic_controller.go:200] PipelineExecutionController project-br9qq/pipeline-76trt-1 [pipeline-execution-controller] failed with : pipelineexecutionlogs.management.cattle.io "pipeline-76trt-1-0-0" already exists

...
time="2018-02-28T22:05:30Z" level=error msg="Error get Jenkins engine - error get jenkins token - secret \"jenkins\" not found"
time="2018-02-28T22:05:30Z" level=error msg="Error get Jenkins engine - error get jenkins token - secret \"jenkins\" not found"
time="2018-02-28T22:05:40Z" level=error msg="Error get Jenkins engine - error get jenkins token - secret \"jenkins\" not found"
```
 in server logs

**Comment by gitlawr** [comment] 2018-03-01 02:30
I was not able to reproduce this.
Can you do the following to see if the pipeline stack is deployed successfully
```
kubectl get ns cattle-pipeline
kubectl get pod,secret -n cattle-pipeline
```
And is there any abnormal logs when enabling pipeline?

**Comment by gitlawr** [comment] 2018-03-02 05:52
due to fetching secret in the wrong plane.
Can be reprodecued by:
1. run rancher/server:master
2. import a cluster
3. setup pipeline and run in that cluster
Should be fixed in latest master but is pending on some other issues to test.
I'll change the issue status when it is available to retest

**Comment by cloudnautique** [comment] 2018-03-02 19:37
I no longer see this issue in the latest builds.

**Closed** 2018-03-03 16:41 UTC
Labels: area/pipeline, kind/bug, status/resolved, status/to-test, version/2.0
