### ISSUE TITLE
Project resource quota deletion not propagating to namespaces

### ISSUE THREAD

**Issue by KevinJoiner** [rancher/rancher#38010] opened 2022-06-15 16:55 UTC
**Rancher Server Setup**
- Rancher version: 2.6 RKE1
- Installation option (Docker install/Helm Chart): Docker Install

**Information about the Cluster**
- Kubernetes version: Kubernetes version: 1.20.6
- Cluster Type (Local/Downstream):
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider):

   
**Describe the bug**

The removal of a resource quota in a project does not correctly propagate to namespaces.

**To Reproduce**
 
- Create New Project with a resource quota
- Create a new namespace in the project
- Verify that a new resourcequota was created for the new namespace `k get resourcequota -A`
- Remove the resourcequotas from the project

**Result**
The created resourcequota for the namespace is still present with the initial quota/limits set
**Expected Result**

The created resourcequota has no quotas/limits set

**Screenshots**

**Additional context**

**Comment by maxsokolovsky** [comment] 2022-09-30 19:34
Reproduced on `v2.7-head`. Created a project with a resource quota, then a namespace in it. When I go to edit the namespace, the UI shows the resource quota tab. When I delete the resource quota from the project, it disappears from the UI and also from the namespace config view. However, it remains in the database, and is enforced in the namespace.

**Comment by maxsokolovsky** [comment] 2022-11-18 20:38
Apologies, I merged this today by accident, hadn't looked at this issue in a while, didn't realize this has not been tested by QA yet. Thought it was fully done too soon. While it does have integration tests, it still needs to be tested by QA. If there are issues found, I will make a new PR with changes.

**Comment by maxsokolovsky** [comment] 2022-11-18 20:56
## QA Testing

### Root cause
When a quota limit is removed from a project, the corresponding limits are not removed in the project's
namespaces.

### What was fixed, or what changes have occurred
When Rancher computes the new resource quota, it needs to include only those resources on the quota that are defined with some limit value on the project. If the project quota does not define a limit for some resource, then ignore the resource quota requested. Keep the current behavior where the requested amount trumps the default one, if the default exists in the project.

### Areas or cases that should be tested

### What areas could experience regressions?

### Steps
1. Create a project with a resource quota for `CPU 200m and Memory 256Mi` for Project Limit and `CPU 100m and Memory 128Mi` for Namespace Default Limit.
1. Create a namespace called `ns1` in the project.
1. Inspect a resource quota that got added to the `ns1` namespace with `kubectl get quota -n ns1`.
1. Ensure that the quota has the folowing limits (the second number is important): `limits.cpu: 0/100m, limits.memory: 0/128Mi`.
1. Go to the Project configuration -> Resource Quotas.
1. Remove just the CPU limit from the quota and save.
1. Fetch the quota in the `ns1` namespace again and ensure it has the folowing limit: `limits.memory: 0/128Mi`. Just the memory limit remained, the CPU limit got deleted from the project's namespace.
1. Go back to the Project configuration and remove the memory limit.
1. Fetch the quota in the `ns1` namespace again and get `No resources found in ns1 namespace`. This means there is no quota anymore, since there are no limits.

**Comment by dasarinaidu** [comment] 2022-11-30 22:17
I have validated this issue on Docker and HA installed rancher.
Rancher Version : v2.7-f7692f30cf47d00073cc41b879e0ff90fb0a68b0-head

<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:////Users/sdasari/Library/Group%20Containers/UBF8T346G9.Office/TemporaryItems/msohtmlclip/clip.htm">
<link rel=File-List
href="file:////Users/sdasari/Library/Group%20Containers/UBF8T346G9.Office/TemporaryItems/msohtmlclip/clip_filelist.xml">
<style>

</style>
</head>

<body link="#0563C1" vlink="#954F72">



Test   Scenario | Test Cases | Check point | Status
-- | -- | -- | --
Resource Quota Create (HA) | 1. Install rancher server via helm v2.7-head     2. As an admin, create 1 rke1 node driver downstream cluster      3. From the rke1 and EKS clusters, created a project     4. Create a NameSpace | a.   Check for the resource quota limits ( On cluster run the command : kubectl   get resourcequota -A )     Make sure the limits are showing properly     b. Delete the NameSpace and check for the resource quota limits     Make sure the limits are not showing ( On cluster run the command : kubectl   get resourcequota -A  OR kubectl get   quota -n ns1) | Pass
Resource Quota Create (HA) | 1. Install rancher server via helm v2.7-head     2. As an admin, create 1 rke1 node driver downstream cluster      3. From the rke1 and EKS clusters, created a project     4. Create a NameSpace      5. Update the resource quota limits in Project and in NameSpace | a.   Check for the resource quota limits ( On cluster run the command : kubectl   get resourcequota -A )     Make sure the limits are showing properly     b. Delete the NameSpace and check for the resource quota limits     Make sure the limits are not showing ( On cluster run the command : kubectl   get resourcequota -A  OR. kubectl get   quota -n ns1) | Pass
Resource Quota Create multiple name spaces(HA) | 1. Install rancher server via helm v2.7-head     2. As an admin, create 1 rke1 node driver downstream cluster      3. From the rke1 and EKS clusters, created a project     4. Create multiple NameSpaces | a.   Check for the resource quota limits ( On cluster run the command : kubectl   get resourcequota -A )     Make sure the limits are showing properly on all the clusters     b. Delete the NameSpaces one by one and check for the resource quota limits     Make sure the limits are not showing ( On cluster run the command : kubectl   get resourcequota -A OR. kubectl get quota -n ns1) | Pass
Resource Quota Create (Docker) | 1. Install rancher server via helm v2.7-head     2. As an admin, create 1 rke1 node driver downstream cluster      3. From the rke1 and EKS clusters, created a project     4. Create a NameSpace | a.   Check for the resource quota limits ( On cluster run the command : kubectl   get resourcequota -A )     Make sure the limits are showing properly     b. Delete the NameSpace and check for the resource quota limits     Make sure the limits are not showing ( On cluster run the command : kubectl   get resourcequota -A  OR kubectl get   quota -n ns1) | Pass
Resource Quota Create (Docker) | 1. Install rancher server via helm v2.7-head     2. As an admin, create 1 rke1 node driver downstream cluster      3. From the rke1 and EKS clusters, created a project     4. Create a NameSpace      5. Update the resource quota limits in Project and in NameSpace | a.   Check for the resource quota limits ( On cluster run the command : kubectl   get resourcequota -A )     Make sure the limits are showing properly     b. Delete the NameSpace and check for the resource quota limits     Make sure the limits are not showing ( On cluster run the command : kubectl   get resourcequota -A  OR. kubectl get   quota -n ns1) | Pass
Resource Quota Create multiple name spaces(Docker) | 1. Install rancher server via helm v2.7-head     2. As an admin, create 1 rke1 node driver downstream cluster      3. From the rke1 and EKS clusters, created a project     4. Create multiple NameSpaces | a.   Check for the resource quota limits ( On cluster run the command : kubectl   get resourcequota -A )     Make sure the limits are showing properly on all the clusters     b. Delete the NameSpaces one by one and check for the resource quota limits     Make sure the limits are not showing ( On cluster run the command : kubectl   get resourcequota -A OR. kubectl get quota -n ns1) | Pass



</body>

</html>

**Closed** 2022-11-30 22:57 UTC
Labels: [zube]: To Test, release-note, team/area1
