### ISSUE TITLE
UI shows "Setting up Kubernetes" even after the system containers are up and running

### ISSUE THREAD

**Issue by soumyalj** [rancher/rancher#5101] opened 2016-06-13 21:33 UTC
**Rancher Version:**: Master

**OS and where are the hosts located? (cloud, bare metal, etc):** Ubuntu, Cloud

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**: Kubernetes

**Steps to Reproduce:**
1. Create a new Kubernetes environment and wait for all the system containers to come up successfully.
2. Click on the environment tab and choose the Kubernetes environment again. The UI still shows
"Setting up Kubernetes"

<img width="1109" alt="screen shot 2016-06-13 at 2 30 47 pm" src="https://cloud.githubusercontent.com/assets/18536626/16023855/985888b8-3173-11e6-9c4a-c592532c598a.png">

**Comment by tfiduccia** [comment] 2016-06-13 21:46
duplicate of https://github.com/rancher/rancher/issues/5081

**Closed by tfiduccia** 2016-06-13 21:46 UTC
Labels: area/ui, kind/bug
