### ISSUE TITLE
Health check and scheduler stuck initializing

### ISSUE THREAD

**Issue by jclark360** [rancher/rancher#7132] opened 2016-12-19 19:45 UTC
**Rancher Version:**
1.2.1

**Docker Version:**
1.12.3

**OS and where are the hosts located? (cloud, bare metal, etc):**
Ubuntu 14.04 aws

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
3 node ha with external db

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle

**Steps to Reproduce:**
Install 1.2.1 add hosts

**Results:** 
Scheduler and health check stuck initializing

**Expected:**
Started

Healthcheck logs

12/19/2016 2:10:21 PMtime="2016-12-19T19:10:21Z" level=info msg="Starting haproxy listener"
12/19/2016 2:10:22 PMtime="2016-12-19T19:10:22Z" level=info msg="healthCheck -- starting haproxy\n * Starting haproxy haproxy\n   ...done.\n"
12/19/2016 2:10:22 PMtime="2016-12-19T19:10:22Z" level=info msg="Scheduling apply config"
12/19/2016 2:10:22 PMtime="2016-12-19T19:10:22Z" level=info msg="healthCheck -- reloading haproxy config with the new config changes\n[WARNING] 353/191022 (32) : config : 'option forwardfor' ignored for proxy 'web' as it requires HTTP mode.\n"
12/19/2016 2:10:27 PMtime="2016-12-19T19:10:27Z" level=info msg="Scheduling apply config"
12/19/2016 2:10:27 PMtime="2016-12-19T19:10:27Z" level=info msg="healthCheck -- no changes in haproxy config\n"
12

scheduler logs

12/19/2016 2:10:46 PMtime="2016-12-19T19:10:46Z" level=info msg="Listening for health checks on 0.0.0.0:80/healthcheck"
12/19/2016 2:10:46 PMtime="2016-12-19T19:10:46Z" level=info msg="Connecting to cattle event stream."
12/19/2016 2:10:46 PMtime="2016-12-19T19:10:46Z" level=info msg="Subscribing to metadata changes."
12/19/2016 2:10:46 PMtime="2016-12-19T19:10:46Z" level=info msg="Adding resource pool [storageSize] with total 74347999 and used 0 for host 28a04038-6ef8-4b3f-a084-8c7a39e31bd3"
12/19/2016 2:10:46 PMtime="2016-12-19T19:10:46Z" level=info msg="Adding resource pool [instanceReservation] with total 1000000 and used 24 for host 28a04038-6ef8-4b3f-a084-8c7a39e31bd3"
12/19/2016 2:10:46 PMtime="2016-12-19T19:10:46Z" level=info msg="Adding resource pool [cpuReservation] with total 4000 and used 0 for host 28a04038-6ef8-4b3f-a084-8c7a39e31bd3"
12/19/2016 2:10:46 PMtime="2016-12-19T19:10:46Z" level=info msg="Adding resource pool [memoryReservation] with total 15769534464 and used 0 for host 28a04038-6ef8-4b3f-a084-8c7a39e31bd3"
12/19/2016 2:10:46 PMtime="2016-12-19T19:10:46Z" level=info msg="Adding resource pool [memoryReservation] with total 15769534464 and used 0 for host 73d68cf1-7f80-4dc8-81e7-2bc51b403f33"
12/19/2016 2:10:46 PMtime="2016-12-19T19:10:46Z" level=info msg="Adding resource pool [storageSize] with total 74445799 and used 0 for host 73d68cf1-7f80-4dc8-81e7-2bc51b403f33"
12/19/2016 2:10:46 PMtime="2016-12-19T19:10:46Z" level=info msg="Adding resource pool [instanceReservation] with total 1000000 and used 22 for host 73d68cf1-7f80-4dc8-81e7-2bc51b403f33"
12/19/2016 2:10:46 PMtime="2016-12-19T19:10:46Z" level=info msg="Adding resource pool [cpuReservation] with total 4000 and used 0 for host 73d68cf1-7f80-4dc8-81e7-2bc51b403f33"
12/19/2016 2:10:46 PMtime="2016-12-19T19:10:46Z" level=info msg="Initializing event router" workerCount=100
12/19/2016 2:10:46 PMtime="2016-12-19T19:10:46Z" level=info msg="Connection established"
12/19/2016 2:10:46 PMtime="2016-12-19T19:10:46Z" level=info msg="Starting websocket pings"

**Comment by matthijsvdr** [comment] 2016-12-19 20:01
Looks like you have the same issue as me: https://github.com/rancher/rancher/issues/7130

**Comment by goffinf** [comment] 2016-12-20 09:00
Looks like a few of us are experiencing the same issue with the health check, scheduler and load balancer getting stuck in 'initializing' status, which at least is a small crumb of comfort that it is likely to be a common cause/effect rather than necessarily something very site specific (still might be of course).

Hopefully Rancher will be able to provide some solid advice ASAP as for us it is a total blocker for using v1.2 (we don't see this for v1.1.4)

Fraser.

**Comment by goffinf** [comment] 2016-12-20 10:26
Adding a few more details.

I stood up a simple Rancher cluster (1 server + 2 nodes) with a local Db, just for testing.

It comes up almost ok, apart from three things ...

1.       The scheduler container doesn’t start, it’s just stuck initializing. The logs show this :-

```
18/12/2016 22:31:34time="2016-12-18T22:31:33Z" level=info msg="Listening for health checks on 0.0.0.0:80/healthcheck"
18/12/2016 22:31:34time="2016-12-18T22:31:33Z" level=info msg="Connecting to cattle event stream."
18/12/2016 22:31:34time="2016-12-18T22:31:33Z" level=info msg="Subscribing to metadata changes."
18/12/2016 22:31:34time="2016-12-18T22:31:34Z" level=info msg="Adding resource pool [instanceReservation] with total 1000000 and used 9 for host e5f1c264-f1ca-4ace-bc3e-927459bd9add"
18/12/2016 22:31:34time="2016-12-18T22:31:34Z" level=info msg="Adding resource pool [cpuReservation] with total 2000 and used 0 for host e5f1c264-f1ca-4ace-bc3e-927459bd9add"
18/12/2016 22:31:34time="2016-12-18T22:31:34Z" level=info msg="Adding resource pool [memoryReservation] with total 3704619008 and used 0 for host e5f1c264-f1ca-4ace-bc3e-927459bd9add"
18/12/2016 22:31:34time="2016-12-18T22:31:34Z" level=info msg="Adding resource pool [storageSize] with total 5818134 and used 0 for host e5f1c264-f1ca-4ace-bc3e-927459bd9add"
18/12/2016 22:31:34time="2016-12-18T22:31:34Z" level=info msg="Initializing event router" workerCount=100
18/12/2016 22:31:34time="2016-12-18T22:31:34Z" level=info msg="Connection established"
18/12/2016 22:31:34time="2016-12-18T22:31:34Z" level=info msg="Starting websocket pings"
18/12/2016 22:49:59time="2016-12-18T22:49:59Z" level=info msg="Adding resource pool [instanceReservation] with total 1000000 and used 4 for host 0cdada1a-1e59-4889-9939-3a2d2329839f"
18/12/2016 22:49:59time="2016-12-18T22:49:59Z" level=info msg="Adding resource pool [cpuReservation] with total 2000 and used 0 for host 0cdada1a-1e59-4889-9939-3a2d2329839f"
18/12/2016 22:49:59time="2016-12-18T22:49:59Z" level=info msg="Adding resource pool [memoryReservation] with total 3704619008 and used 0 for host 0cdada1a-1e59-4889-9939-3a2d2329839f"
18/12/2016 22:49:59time="2016-12-18T22:49:59Z" level=info msg="Adding resource pool [storageSize] with total 5817597 and used 0 for host 0cdada1a-1e59-4889-9939-3a2d2329839f"
```

2.       I created a global scope load-balancer (linked to an nginx service (port 80:80) that came up no problem – pulled from ECR) but it is also stuck initializing’. Log shows this :-

```
18/12/2016 22:39:13time="2016-12-18T22:39:13Z" level=info msg="KUBERNETES_URL is not set, skipping init of kubernetes controller"
18/12/2016 22:39:13time="2016-12-18T22:39:13Z" level=info msg="Starting Rancher LB service"
18/12/2016 22:39:13time="2016-12-18T22:39:13Z" level=info msg="LB controller: rancher"
18/12/2016 22:39:13time="2016-12-18T22:39:13Z" level=info msg="LB provider: haproxy"
18/12/2016 22:39:13time="2016-12-18T22:39:13Z" level=info msg="starting rancher controller"
18/12/2016 22:39:13time="2016-12-18T22:39:13Z" level=info msg="Healthcheck handler is listening on :10241"
18/12/2016 22:39:16time="2016-12-18T22:39:16Z" level=info msg=" -- starting haproxy\n[ALERT] 352/223916 (27) : Starting frontend GLOBAL: cannot bind UNIX socket [/run/haproxy/admin.sock]\n"
18/12/2016 22:39:16time="2016-12-18T22:39:16Z" level=info msg=" -- reloading haproxy config with the new config changes\n[WARNING] 352/223916 (38) : config : 'option forwardfor' ignored for proxy 'default' as it requires HTTP mode.\n"
```

3.       On the first host, the health-check container is running fine, but the one on the second is stuck initializing. The logs show this :-

```
18/12/2016 22:50:24time="2016-12-18T22:50:23Z" level=info msg="Starting haproxy listener"
18/12/2016 22:50:28time="2016-12-18T22:50:28Z" level=info msg="healthCheck -- starting haproxy\n * Starting haproxy haproxy\n   ...done.\n"
18/12/2016 22:50:28time="2016-12-18T22:50:28Z" level=info msg="Scheduling apply config"
18/12/2016 22:50:28time="2016-12-18T22:50:28Z" level=info msg="healthCheck -- reloading haproxy config with the new config changes\n[WARNING] 352/225028 (31) : config : 'option forwardfor' ignored for proxy 'web' as it requires HTTP mode.\n"
18/12/2016 22:50:38time="2016-12-18T22:50:38Z" level=info msg="Scheduling apply config"
18/12/2016 22:50:38time="2016-12-18T22:50:38Z" level=info msg="healthCheck -- no changes in haproxy config\n"
18/12/2016 22:51:52time="2016-12-18T22:51:52Z" level=info msg="Starting haproxy listener"
18/12/2016 22:51:52time="2016-12-18T22:51:52Z" level=info msg="healthCheck -- starting haproxy\n[WARNING] 352/225152 (16) : config : 'option forwardfor' ignored for proxy 'web' as it requires HTTP mode.\n"
18/12/2016 22:51:52time="2016-12-18T22:51:52Z" level=info msg="Scheduling apply config"
18/12/2016 22:51:52time="2016-12-18T22:51:52Z" level=info msg="healthCheck -- no changes in haproxy config\n"
```
I can ping between the ip-sec containers on separate hosts (in both directions), but NOT between an ipsec container and any other container nor between any other two containers (not ipsec).

Here’s a picture :-

![rancher_v1 2 1_initializing2](https://cloud.githubusercontent.com/assets/2772752/21346983/a7ddff6e-c69e-11e6-9d17-6a49a12f82f3.jpg)

**Comment by goffinf** [comment] 2016-12-20 14:58
More details

I created a new group of nodes (1 server + 2 nodes) this time using docker 1.10.3 in case using 1.12.x was a problem.

No change, health-check and scheduler containers still stuck in 'initializing' state.

OS: RHEL 7.3
Platform: AWS
Rancher Version: 1.2.1
Docker Version : tried 1.12.3 and 1.10.3 (same behavior)
Docker Compose version: 1.9.0 (also 1.8.1 on the docker 1.10.3 hosts).

**Comment by goffinf** [comment] 2016-12-21 13:04
Rancher have confirmed a problem with networking that should be fixed in v1.2.2 (expected in the next few days).

**Comment by jclark360** [comment] 2016-12-21 14:06
I have fixed our problem, it was two fold:

1) you must use an ALB with aws installations, do NOT use an ELB
2) when you register your hosts you need to set the cattle_agent_ip to the private ip of the ec2 instance, don't let it auto-discover as it uses the public ip instead. 

@leodotcloud @ibuildthecloud

**Comment by goffinf** [comment] 2016-12-21 15:27
We already use an ALB and none of our instances have a public IP.

**Comment by yoerayo** [comment] 2016-12-21 21:34
I had this problem at one point when I registered the first two agents in quick succession.  Removing one of the agents and re-adding it seemed to fix that problem.

**Closed** 2017-01-10 18:40 UTC

**Comment by ElPsyCongro** [comment] 2017-10-12 22:17
Hi I'm having an issue like this...I have a rancher-server on a local server. What I'm trying to do is add my AWS host with his public IP but they can reach my local server only by VPN connection. (When I execute the command generated by the UI of Rancher to add a host the detected cattle agent IP is his IP of the VPN even when use the public IP of the host for cattle agent IP).
Every host has a OpenVPN client that is running on background providing a tun0 interface, I have a VPN server on AWS that allows connection between clients and redirect all the traffic through the VPN. Also my local server is connected to that VPN.
The AWS hosts get added but when the second host is added the health check stays on initializing and there is no connection between hosts. Any idea of what is happening? What I'm doing is wrong?

**Comment by iamfreee** [comment] 2017-10-17 20:54
@ElPsyCongro maybe you have to open udp ports 500 and 4500 for hosts inter-communication?

http://rancher.com/docs/rancher/v1.6/en/hosts/custom/#security-groupsfirewalls

**Comment by superseb** [comment] 2017-10-17 21:00
@ElPsyCongro Can you open a new issue if you are experiencing problems? Along with all the used versions etc we can investigate.

**Comment by ElPsyCongro** [comment] 2017-10-17 21:31
@iamfreee All my hosts have the UDP port 500 and 4500 open on the inbound rules in AWS. There is no communication between health check containers and there should be able to ping from the Shell to the IP of the other container.

**Comment by ElPsyCongro** [comment] 2017-10-17 21:40
@superseb Yes I will, but the thing is that I don't know if what I'm trying to do is correct or it should work. 
Remember that I'm using an OpenVPN client connection on the local server in order to be reachable from anyone that has a OpenVPN client configuration to the OpenVPN server hosted on AWS. So my hosts has an OpenVPN client config and they are connected to the VPN but as I said the connection between my hosts in Rancher doesn't happen.

**Comment by maxfriedmann** [comment] 2018-03-23 10:31
Ran into this issue again today, this time, none of the tips helped me. I explicitly had to tell the agent to use the IPv4 address as CATTLE_AGENT_IP. I double checked the UDP ports being open for the IPv6 which is being used by Rancher by default, but couldn't get it to work. Anyway, maybe that helps somebody else.
