### ISSUE TITLE
Support Global or Shared Node Templates

### ISSUE THREAD

**Issue by ekristen** [rancher/rancher#19333] opened 2019-04-02 19:19 UTC
**What kind of request is this (question/bug/enhancement/feature request):** feature request

It seems that node templates are scoped to a user, which can be problematic when you have multiple people that need to manage a cluster.

I would ask that there be a way to share node templates or make them globally available in some way so they are not limited to a user.

This would help prevent against user being deactivated or deleted when someone leaves the organization, this would make it easier for an admin such as myself to allow a dev to use a node-template in a custom cluster without that dev having to create the node template themselves.

This could be a duplicate of https://github.com/rancher/rancher/issues/14337, but I'm not familiar with Rancher 1's variation, so I opted to open another issue for now.

**Comment by superseb** [comment] 2019-04-02 20:01
Duplicate of https://github.com/rancher/rancher/issues/12186

**Closed by superseb** 2019-04-02 20:01 UTC

**Comment by vincent99** [comment] 2019-04-02 22:51
This is still coming eventually, having them at all separate from the template was the first step in 2.2.

**Comment by rimoore** [comment] 2019-04-06 01:10
> This is still coming eventually, having them at all separate from the template was the first step in 2.2.

I need this too. Rights needed exceed datacenter policy so we are using a service account. I'd like a global template so don't have to go in to everyone's profile and create a separate template.

**Comment by ybizeul** [comment] 2020-04-08 13:35
I'm not sure I understand why that is a duplicate of #12186.

I thought the point was to be able to define global Node templates : i.e. I am an admin, and I want to define node templates that my standard users will be able to use when provisioning clusters.

I don't think #12186 fixes that.
