### ISSUE TITLE
Cannot access exposed port from docker host.

### ISSUE THREAD

**Issue by SamMousa** [rancher/rancher#6950] opened 2016-12-06 11:57 UTC
**Rancher Version:**
1.2.0
**Docker Version:**
1.12.3
**OS and where are the hosts located? (cloud, bare metal, etc):**
VPS, Ubuntu 16.04 and  / or 14.04
**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
Single node rancher, internal db mounted via data container
**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle
**Steps to Reproduce:**
1. Create a container that exposes a port on the host.
2. Check if you can connect from the host to that port by using IP 127.0.0.1.
**Results:** 
Immediately after the container comes up the connection will succeed for some time. 
After a while connections from the host will fail but connections from other hosts the published port, using the hosts public IP, will still succeed.
I think I could force it to stop working by upgrading the service, and I can temporary fix it by rebooting the host.
**Expected:**
When I expose a port on the host machine I expect it to be accessible from the host as well. Note that it could be related to hairpin NAT, but I think that only applies to using the public IP from the host and not using the loopback address.

This behavior started after upgrading to rancher 1.2

**Comment by SamMousa** [comment] 2016-12-06 12:22
Seems to be the same when using a Load Balancer to expose the ports.

**Comment by SamMousa** [comment] 2016-12-06 12:29
Did some more research, this is the output of `iptables -t nat -L -n | grep 25`.
I've added a loadbalancer that balances both port 25 and 2500 to container port 2500.

````
DNAT       tcp  --  0.0.0.0/0            0.0.0.0/0            tcp dpt:25 ADDRTYPE match dst-type LOCAL to:10.42.168.111:25
DNAT       tcp  --  0.0.0.0/0            0.0.0.0/0            tcp dpt:25 ADDRTYPE match dst-type LOCAL to:10.42.168.111:25
DNAT       tcp  --  0.0.0.0/0            0.0.0.0/0            tcp dpt:25 ADDRTYPE match dst-type LOCAL to:10.42.240.25:25
DNAT       tcp  --  0.0.0.0/0            0.0.0.0/0            tcp dpt:587 ADDRTYPE match dst-type LOCAL to:10.42.240.25:587
DNAT       tcp  --  0.0.0.0/0            0.0.0.0/0            tcp dpt:25 ADDRTYPE match dst-type LOCAL to:10.42.240.25:25
DNAT       tcp  --  0.0.0.0/0            0.0.0.0/0            tcp dpt:587 ADDRTYPE match dst-type LOCAL to:10.42.240.25:587
DNAT       tcp  --  0.0.0.0/0            0.0.0.0/0            tcp dpt:25 ADDRTYPE match dst-type LOCAL to:10.42.240.25:25
DNAT       tcp  --  0.0.0.0/0            0.0.0.0/0            tcp dpt:587 ADDRTYPE match dst-type LOCAL to:10.42.240.25:587
DNAT       tcp  --  0.0.0.0/0            0.0.0.0/0            tcp dpt:25 ADDRTYPE match dst-type LOCAL to:10.42.49.91:25
DNAT       tcp  --  0.0.0.0/0            0.0.0.0/0            tcp dpt:25 ADDRTYPE match dst-type LOCAL to:10.42.49.91:25
DNAT       tcp  --  0.0.0.0/0            0.0.0.0/0            tcp dpt:25 ADDRTYPE match dst-type LOCAL to:10.42.49.91:25
DNAT       tcp  --  0.0.0.0/0            0.0.0.0/0            tcp dpt:2500 ADDRTYPE match dst-type LOCAL to:10.42.227.2:2500
DNAT       tcp  --  0.0.0.0/0            0.0.0.0/0            tcp dpt:25 ADDRTYPE match dst-type LOCAL to:10.42.49.91:25
DNAT       tcp  --  0.0.0.0/0            0.0.0.0/0            tcp dpt:25 ADDRTYPE match dst-type LOCAL to:10.42.227.2:25
DNAT       tcp  --  0.0.0.0/0            0.0.0.0/0            tcp dpt:25 ADDRTYPE match dst-type LOCAL to:10.42.227.2:25
DNAT       tcp  --  0.0.0.0/0            0.0.0.0/0            tcp dpt:25 ADDRTYPE match dst-type LOCAL to:10.42.227.2:25
DNAT       tcp  --  0.0.0.0/0            0.0.0.0/0            tcp dpt:25 ADDRTYPE match dst-type LOCAL to:10.42.227.2:25
DNAT       tcp  --  0.0.0.0/0            0.0.0.0/0            tcp dpt:2500 ADDRTYPE match dst-type LOCAL to:10.42.227.2:2500
MARK       tcp  --  0.0.0.0/0            0.0.0.0/0            tcp dpt:25 MARK set 0x1068
DNAT       tcp  --  0.0.0.0/0            0.0.0.0/0            tcp dpt:25 to:10.42.227.2:25
DNAT       tcp  --  0.0.0.0/0            0.0.0.0/0            tcp dpt:25 ADDRTYPE match dst-type LOCAL to:10.42.227.2:25
MARK       tcp  --  0.0.0.0/0            0.0.0.0/0            tcp dpt:2500 MARK set 0x1068
DNAT       tcp  --  0.0.0.0/0            0.0.0.0/0            tcp dpt:2500 to:10.42.227.2:2500
DNAT       tcp  --  0.0.0.0/0            0.0.0.0/0            tcp dpt:2500 ADDRTYPE match dst-type LOCAL to:10.42.227.2:2500
````

The strange thing is, for port 2500 I can actually connect from the host to the container via `telnet 127.0.0.1 25`. There are also a lot of records in the table for port 25 that are referring to IP addresses no longer in use by a container.
Could it be that Rancher is polluting the IP tables / not cleaning them up when doing service upgrades?

**Comment by aemneina** [comment] 2016-12-06 17:30
@leodotcloud this looks related to [#6941](https://github.com/rancher/rancher/issues/6941) sound about right?

**Comment by leodotcloud** [comment] 2016-12-06 18:55
@aemneina yes, the root cause for this is 6941. The changes have been merged in. New version of network-manager (v0.2.14) has been released. Upgrade of the network-manager service and a reboot of the hosts will resolve the iptables rules problems.

**Comment by aemneina** [comment] 2016-12-06 19:14
@SamMousa can you try upgrading your network-manager service? Should be under stacks-> infrastructure. You should be presented with an upgrade available button for network services.

**Comment by deniseschannon** [comment] 2016-12-06 19:53
@SamMousa @leodotcloud @aemneina These changes haven't been made public yet, we're still testing internally.

**Comment by SamMousa** [comment] 2016-12-06 23:42
Ok, thanks for the feedback.

**Comment by sangeethah** [comment] 2016-12-07 00:56
Tested the following scenarios using - rancher/network-manager:v0.2.14.

Deploy services having exposed ports .  Able to access containers using 127.0.0.1:<exposed port> from the host where they are running.
Upgrade the service.
We are able to continue to access containers using 127.0.0.1:<exposed port> from the host where they are running.

Also there is also no duplicated iptable rules for opening ports on the host.

**Comment by SamMousa** [comment] 2016-12-08 09:19
Upgrading now, will confirm if it works for me as well, and if so close this.

**Comment by SamMousa** [comment] 2016-12-08 09:21
Works for me! Thanks!

**Closed** 2016-12-08 13:11 UTC
Labels: status/to-test
