### ISSUE TITLE
Metrics-server v0.4.1 timeout - already fixed in upstream

### ISSUE THREAD

**Issue by daleckystepan** [rancher/rancher#32425] opened 2021-04-28 10:13 UTC
**What kind of request is this (question/bug/enhancement/feature request):**
Update metrics-server to  v0.4.2 or v0.4.3

**Steps to reproduce (least amount of steps as possible):**
1) Rancher 2.5.7
2) Install Kubernetes: 1.20.5 through UI

**Result:**
Metrics-server bug
https://github.com/kubernetes-sigs/metrics-server/issues/671

```
E0321 05:18:22.783887       1 webhook.go:199] Failed to make webhook authorizer request: Post "https://172.20.0.1:443/apis/authorization.k8s.io/v1/subjectaccessreviews": context canceled
E0321 05:18:22.807245       1 errors.go:77] Post "https://172.20.0.1:443/apis/authorization.k8s.io/v1/subjectaccessreviews": context canceled
```

Very slow kubectl commands

**Other details that may be helpful:**
According to https://github.com/kubernetes-sigs/metrics-server/issues/671 should be fixed in v0.4.2 or v0.4.3

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): 2.5.7
- Installation option (single install/HA): single, doesnt matter

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): Custom
- Machine type (cloud/VM/metal) and specifications (CPU/memory): metal
- Kubernetes version (use `kubectl version`):

```
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.0", GitCommit:"cb303e613a121a29364f75cc67d3d580833a7479", GitTreeState:"clean", BuildDate:"2021-04-08T21:16:14Z", GoVersion:"go1.16.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.5", GitCommit:"6b1d87acf3c8253c123756b9e61dac642678305f", GitTreeState:"clean", BuildDate:"2021-03-18T01:02:01Z", GoVersion:"go1.15.8", Compiler:"gc", Platform:"linux/amd64"}
```

- Docker version (use `docker version`):

```
# docker version
Client: Docker Engine - Community
 Version:           19.03.13
 API version:       1.40
 Go version:        go1.13.15
 Git commit:        4484c46d9d
 Built:             Wed Sep 16 17:02:52 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.13
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       4484c46d9d
  Built:            Wed Sep 16 17:01:20 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.3
  GitCommit:        269548fa27e0089a8b8278fc4fc781d7f65a939b
 runc:
  Version:          1.0.0-rc92
  GitCommit:        ff819c7e9184c13b7c2607fe6c30ae19403a7aff
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

SURE-3632

**Comment by bentastic27** [comment] 2021-11-09 17:38
This is still an issue. This is leading to excessive inflight requests on the kube-apiserver as well as broken metrics.

**Comment by paynejacob** [comment] 2022-01-11 18:42
### Root cause ### What was fixed, or what changes have occurred
The root cause was a bug in the upstream metric server.  

 ### Areas or cases that should be tested 
 Provision a cluster with k8s 1.20.5 with metrics server enabled.  The kubelet should not show error messages similar to the ones above.
 
### What areas could experience regressions?
Any issues will be in the metrics server deployment or the kubelet logs.

 ### Are the repro steps accurate/minimal?
 
 yes

**Closed** 2022-01-22 01:37 UTC
Labels: kind/bug, internal, [zube]: QA Working

**Comment by Auston-Ivison-Suse** [comment] 2022-01-22 01:39
**Validation**
Rancher server: v2.6.3
KDM branch: dev-v2.6-v1.20.14-0122

**Steps For Validation**
1. Provision a downstream with 3 workers, 1 control plane, and 1 etcd
2. Within the kubernetes options select the k8s: v1.20.14-rancher2-1 (must change kdm version in global settings to make this possible in 2.6.3 rancher version) 
3. Provision the cluster with all other defaults. 
4. checked the version of the metrics server in pods: it should be 0.5.0 which contains the fix we need for this issue. 
5. The logs showed no errors or warnings

**Use-Case Deploy Horizontal Autoscaler**
1. From the cluster's dashboard get into the kubectl shell.
2. run the following commands

a. 
```
kubectl create deployment php-apache --image=k8s.gcr.io/hpa-example

```

b. 
```
kubectl patch deployment php-apache -p='{"spec":{"template":{"spec":{"containers":[{"name":"hpa-example","resources":{"requests":{"cpu":"200m"}}}]}}}}'


```

c. 
```
kubectl create service clusterip php-apache --tcp=80
```

d. 
```
kubectl autoscale deployment php-apache --cpu-percent=50 --min=1 --max=10

```
e. 
```
kubectl get hpa
```

f. 
```
kubectl run --generator=run-pod/v1 -i --tty load-generator --image=busybox /bin/sh

```
3. Check the deployment to make sure it is active (this may take a few minutes) 

Screenshot of the active autoscaler: 
![metricserver263.png](https://zube.io/files/rancher/80aada451fe07e8dacaf73e1caf01bfb-metricserver263.png)
