### ISSUE TITLE
Azure with cloud provider enabled - Cluster gets stuck in "provisioning" state forever with following error message: - " Failed to bring up Control Plane: [Failed to verify healthcheck"

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#16632] opened 2018-11-16 23:51 UTC
Steps to reproduce the problem:

Create an Azure cluster with cloud provider enable and following node configuration:
1 control node
1 etcd node
3 worker nodes 

Nodes are stuck in "registering" state with error message - "Waiting to register with Kubernetes"

Cluster gets stuck in "provisioning" state forever with following error message:

 
```

[controlPlane] Failed to bring up Control Plane: [Failed to verify healthcheck: Service [kube-apiserver] is not healthy on host [168.62.222.50]. Response code: [500], response body: [+]ping ok [+]log ok [+]etcd ok [+]poststarthook/generic-apiserver-start-informers ok [+]poststarthook/start-apiextensions-informers ok [+]poststarthook/start-apiextensions-controllers ok [-]poststarthook/bootstrap-controller failed: reason withheld [-]poststarthook/rbac/bootstrap-roles failed: reason withheld [-]poststarthook/scheduling/bootstrap-system-priority-classes failed: reason withheld [-]poststarthook/ca-registration failed: reason withheld [+]poststarthook/start-kube-apiserver-informers ok [+]poststarthook/start-kube-apiserver-admission-initializer ok [+]poststarthook/start-kube-aggregator-informers ok [+]poststarthook/apiservice-registration-controller ok [+]poststarthook/apiservice-status-available-controller ok [+]poststarthook/apiservice-openapi-controller ok [+]poststarthook/kube-apiserver-autoregistration ok [+]autoregister-completion ok healthz check failed , log: I1116 23:37:13.622299 1 storage_scheduling.go:100] all system priority classes are created successfully or already exist.]
--

```

[cluster.log](https://github.com/rancher/rancher/files/2591260/cluster.log)

**Comment by alena1108** [comment] 2018-11-28 23:04
@moelsayed can you see if there is an issue with RKE, or with k8s 1.12 + Azure combo

**Comment by sangeethah** [comment] 2018-11-29 20:50
@alena1108 @moelsayed  Able to get an Azure cluster with no cloud provider set provision successfully.

**Comment by moelsayed** [comment] 2018-11-30 00:25
I am unable to reproduce this with current(29/11) master + k8s 1.12.3 and Azure. I tried 5 clusters with the same combination of nodes and roles.

**Comment by davidnuzik** [comment] 2018-12-04 16:55
I am still encountering issues when I attempt to provision Azure RKE cluster with azure cloud provider option. I tested in current master (12/4). Initially I reproduce exactly with kube-api health issues. Then after a long time kube seems to destroy the nodes and try again and then things sort of work but none of the worker nodes are responding. Happy to provide rancher server logs and a screenshot of options chosen to cause the issue.

**Comment by davidnuzik** [comment] 2018-12-05 20:42
Closing issue, please refer to #16887

**Closed by davidnuzik** 2018-12-05 20:42 UTC
Labels: kind/bug-qa, priority/0, releases/alpha1, team/az, version/2.0
