### ISSUE TITLE
[BUG] Error seen when creating a project as cluster owner and assigning another stand user as project member to the project

### ISSUE THREAD

**Issue by sowmyav27** [rancher/rancher#38573] opened 2022-08-10 04:53 UTC
**Rancher Server Setup**
- Rancher version: 2.6head - commit id: `b8b95dc` and `2.6.6`
- Installation option (Docker install/Helm Chart): docker install

**Information about the Cluster**
- Kubernetes version: 1.23 on 2.6.6 and 1.24 RKE2 on 2.6.head AWS node driver RKE 2 cluster

**User Information**
- What is the role of the user logged in? (Admin/Cluster Owner/Cluster Member/Project Owner/Project Member/Custom) standard user

**Describe the bug**
[BUG] Error seen when creating a project as cluster owner and assigning another stand user as project member to the project

**To Reproduce**

- As admin create two standard users - user1 and user2
- As standard user - user1, login and deploy the cluster
- When the cluster has come up Active, Navigate to cluster Explorer --> Projects and namespaces
- Create a new Project, and add standard user - user2 as Project owner, while creating the project
- Save changes made
- Error seen in UI: `projectroletemplatebindings.management.cattle.io is forbidden: User "u-66gsf" cannot create resource "projectroletemplatebindings" in API group "management.cattle.io" in the namespace "p-n466d"`
- Network call - `https://rancherserver/v3/projectroletemplatebindings` gives an error `{"baseType":"error","code":"Forbidden","message":"projectroletemplatebindings.management.cattle.io is forbidden: User \"u-66gsf\" cannot create resource \"projectroletemplatebindings\" in API group \"management.cattle.io\" in the namespace \"p-n466d\"","status":403,"type":"error"}` 
- But there is a Network POST request `https://rancherserver/v3/projects` with 201 status code
- The project is seen created, but the user is NOT added.
- When standard user creates a project first. Then Edit Config on the project --> Add member --> Add user2 as Project Owner --> This gets saved successfully

**Note:**
This happens on 2.6.6 also.

**Comment by cbron** [comment] 2022-09-13 00:11
Reproduced, but I get this error regardless of adding new member or not.

There are 2 calls that happen when you hit create, neither reference the other user: 
* A POST to `https://rainbow.cp-dev.rancher.space/v3/projects` that completes with 201
* A POST to `https://rainbow.cp-dev.rancher.space/v3/projects/c-m-6h5tt5vx:p-mbd4r?action=setpodsecuritypolicytemplate` that fails with 403 and message above, the payload here is empty

**Comment by cbron** [comment] 2022-09-13 00:13
Oh, @anupama2501 is this actually: https://github.com/rancher/dashboard/issues/6464
Maybe this is a regression now ? I'm using 2.6-head on 4e634b6 (from sept 12th).

**Comment by anupama2501** [comment] 2022-09-13 12:06
@cbron I tried reproducing this issue on v2.6.8 and v2.6-head 79a5328 with Azure AD auth enabled.


- I'm not seeing the issue on v2.6.8 for both RKE2 and RKE1 downstream node driver clusters as a cluster owner and cluster member when I create a project.
- I noticed this error on v2.6-head 79a5328 on rke2 downstream node driver cluster only and not rke1 node driver downstream cluster  when I try to create a project as a cluster member and not as a cluster owner - See the error on the Post URL 

`https://<rancherserverIP>/v3/projects/c-m-npcfw5ln:p-65tnt?action=setpodsecuritypolicytemplate` 
Error : `projects.management.cattle.io "p-65tnt" is forbidden: User "u-cczqeq4tow" cannot get resource "projects" in API group "management.cattle.io" in the namespace "c-m-npcfw5ln"`


**Note:**
I see the error from the original comment ` User \"u-66gsf\" cannot create resource "projectroletemplatebindings\" in API group ` to be different than the error I notice `: User "u-cczqeq4tow" cannot get resource "projects" in API group` with different Post URLs.

Error in the original comment above:
```
{"baseType":"error","code":"Forbidden","message":"projectroletemplatebindings.management.cattle.io is forbidden: User \"u-66gsf\" cannot create resource \"projectroletemplatebindings\" in API group \"management.cattle.io\" in the namespace \"p-n466d\"","status":403,"type":"error"}
```

Error I notice seems to be the same as https://github.com/rancher/dashboard/issues/6464
```
Error : `projects.management.cattle.io "p-65tnt" is forbidden: User "u-cczqeq4tow" cannot get resource "projects" in API group "management.cattle.io" in the namespace "c-m-npcfw5ln"
```

**Comment by cbron** [comment] 2022-09-13 21:46
Can we close this issue out then ?

**Comment by anupama2501** [comment] 2022-09-15 13:18
yes we can close the issue and re open if seeing again in the future.

**Comment by anupama2501** [comment] 2022-09-15 13:18
Closing issue as it is not reproducible on v2.6-head

**Closed by anupama2501** 2022-09-15 13:18 UTC
Labels: kind/bug, [zube]: To Triage, team/area1
