### ISSUE TITLE
Rancher not start ubuntu

### ISSUE THREAD

**Issue by TheYkk** [rancher/rancher#17123] opened 2018-12-16 07:24 UTC
**What kind of request is this (question/bug/enhancement/feature request):**
bug

**Steps to reproduce (least amount of steps as possible):**

I tried to set up rancher, but unfortunately was not installed.
i use this command 
``$ sudo docker run -d --restart=unless-stopped -p 80:80 -p 443:443 rancher/rancher:latest``
but when i request ``https://192.168.50.1/`` get 403 http error
**Result:**

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI):rancher/rancher
- Installation option (single install/HA):single install

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported):
- Machine type (cloud/VM/metal) and specifications (CPU/memory):virtualbox
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.1", GitCommit:"eec55b9ba98609a46fee712359c7b5b365bdd920", GitTreeState:"clean", BuildDate:"2018-12-13T10:39:04Z", GoVersion:"go1.11.2", Compiler:"gc", Platform:"linux/ amd64"}

```

- Docker (use `docker info`):

```

  | docker info
-- | --
  |  
  | Containers: 5
  | Running: 2
  | Paused: 0
  | Stopped: 3
  | Images: 2
  | Server Version: 18.09.0
  | Storage Driver: overlay2
  | Backing Filesystem: extfs
  | Supports d_type: true
  | Native Overlay Diff: true
  | Logging Driver: json-file
  | Cgroup Driver: cgroupfs
  | Plugins:
  | Volume: local
  | Network: bridge host macvlan null overlay
  | Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
  | Swarm: inactive
  | Runtimes: runc
  | Default Runtime: runc
  | Init Binary: docker-init
  | containerd version: c4446665cb9c30056f4998ed953e6d4ff22c7c39
  | runc version: 4fc53a81fb7c994640722ac585fa9ca548971871
  | init version: fec3683
  | Security Options:
  | apparmor
  | seccomp
  | Profile: default
  | Kernel Version: 4.15.0-29-generic
  | Operating System: Ubuntu 18.04.1 LTS
  | OSType: linux
  | Architecture: x86_64
  | CPUs: 3
  | Total Memory: 3.017GiB
  | Name: okd
  | ID: CDNS:DCWK:TVMU:JKJ5:3HUY:QPCG:UXZ5:JABS:UYPE:W5AG:SOFV:72QP
  | Docker Root Dir: /var/lib/docker
  | Debug Mode (client): false
  | Debug Mode (server): false
  | Registry: https://index.docker.io/v1/
  | Labels:
  | Experimental: false
  | Insecure Registries:
  | 127.0.0.0/8
  | Live Restore Enabled: false
  | Product License: Community Engine
  |  
  |  


```

**Comment by superseb** [comment] 2018-12-17 20:56
Please share a screenshot or the output of `curl -k -v https://192.168.50.1/`?

**Comment by TheYkk** [comment] 2018-12-18 02:20
http://prntscr.com/lwb054

**Comment by superseb** [comment] 2018-12-18 08:31
This shows return code 200 and the expected JSON output. We'll need a screenshot of the 403 error as there is no issue seen here. Also, the IP is not `192.168.50.1` but I assume you set it up again.

**Comment by TheYkk** [comment] 2018-12-19 11:35
i create other vm . 
http://prntscr.com/lwxsww
http://prntscr.com/lwxtck

**Comment by TheYkk** [comment] 2018-12-19 11:43
i change port and its working

**Comment by superseb** [comment] 2018-12-19 11:48
I guess your browser has a proxy or something else configured that denies you from visiting this port/range. Especially if it works on another port.

For future reference, one might also try creating a local tunnel over SSH to test if the UI can be visited over it:

```
ssh -L8443:127.0.0.1:443 root@IP
```

Then visit https://127.0.0.1:8443 on your PC.

Closing this as not a bug, let me know if you think there is a bug in Rancher here.

**Closed by superseb** 2018-12-19 11:48 UTC
Labels: kind/question, version/2.0
