### ISSUE TITLE
Glusterfs Not Working

### ISSUE THREAD

**Issue by mholttech** [rancher/rancher#3878] opened 2016-03-09 00:58 UTC
Rancher Version:
0.59.1
Docker Version:
1.10.1
OS: 
3x RancherOS 4.2.8
Steps to Reproduce: 
After adding all 3 Hosts to Rancher, I added the GlusterFS from the Library using the default information.  
Results: 
GlusterFS never finishes setting up volume

glusterfs-server_1 log
````
3/8/2016 4:49:25 PMWaiting for all service containers to start...
3/8/2016 4:50:44 PMContainers are starting...
3/8/2016 4:50:44 PMWaiting for Gluster Daemons to come up
3/8/2016 4:51:19 PMgluster peer probe 10.42.227.123
3/8/2016 4:51:19 PMpeer probe: success.
3/8/2016 4:51:20 PMgluster peer probe 10.42.51.16
````

glusterfs-server_2 log
````
3/8/2016 4:50:01 PMWaiting for all service containers to start...
3/8/2016 4:50:44 PMContainers are starting...
3/8/2016 4:50:44 PMWaiting for Gluster Daemons to come up
3/8/2016 4:51:21 PMgluster peer probe 10.42.152.194
3/8/2016 4:51:21 PMpeer probe: success. Host 10.42.152.194 port 24007 already in peer list
3/8/2016 4:51:21 PMgluster peer probe 10.42.51.16
````

glusterfs-server_3 log
````

3/8/2016 4:50:47 PMWaiting for all service containers to start...
3/8/2016 4:50:53 PMContainers are starting...
3/8/2016 4:50:53 PMWaiting for Gluster Daemons to come up
3/8/2016 4:51:33 PMgluster peer probe 10.42.152.194
````

glusterfs-volume-create_1
````
3/8/2016 4:52:30 PMWaiting for pool...
3/8/2016 4:52:35 PMpool list: failed
3/8/2016 4:52:35 PMWaiting for pool...
3/8/2016 4:52:40 PMpool list: failed
3/8/2016 4:52:40 PMWaiting for pool...
````

**Comment by deniseschannon** [comment] 2016-03-09 18:26
I am unable to reproduce. 

I set up the same, but the only difference was Rancher v0.61.0-rc3. Where are you deploying RancherOS? I did mine on AWS. 

It took awhile, but eventually my glusterfs went active.

**Comment by mholttech** [comment] 2016-03-10 07:59
I tried it again today running 3 hosts on Rancher OS v0.4.4-rc1 and Rancher Server v0.63.0-rc1 with no luck.  Running my environment in an vSphere environment

**Comment by deniseschannon** [comment] 2016-03-17 22:49
Duplicate of https://github.com/rancher/rancher/issues/3670

Please follow the other issue for updates.

**Closed by deniseschannon** 2016-03-17 22:49 UTC
Labels: kind/question
