### ISSUE TITLE
Add ability to add/edit selector links in the UI

### ISSUE THREAD

**Issue by nhumrich** [rancher/rancher#3353] opened 2016-01-20 20:17 UTC
You can add selectors to a service to decide which hosts the service will run on. But you can not remove said selectors from the UI. The UI shows the selector as being removed, but when you upgrade, and load the service again, you will see the selector is still there.
This also applied to changing selectors. If you try to change a selector, it instead creates a second one, so after you upgrade the service, there will now be two selectors, the one you used to have, and the one you should have. 
If you make any mistake with selectors, you have to recreate a whole new service, even a clone will copy the bad ones over.

Helpful version info:
Rancher 	v0.51.0
Cattle 	v0.130.0
User Interface 	v0.78.0
Rancher Compose 	v0.7.0

**Comment by deniseschannon** [comment] 2016-01-20 21:15
This is seems similar to https://github.com/rancher/rancher/issues/2550 where we need to add in places in the UI for selector labels.

**Comment by deniseschannon** [comment] 2016-07-13 06:01
Duplicate of https://github.com/rancher/rancher/issues/2270

**Closed by deniseschannon** 2016-07-13 06:01 UTC
Labels: area/ui, kind/enhancement
