### ISSUE TITLE
Global User List Table: Only own DisplayName displayed after Update to 2.2.1 with Keycloak integration

### ISSUE THREAD

**Issue by ChrisHaPunkt** [rancher/rancher#19353] opened 2019-04-03 09:23 UTC
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
Activate Keycloak Authentication with parameters shown below.
![Bildschirmfoto 2019-04-03 um 11 10 18](https://user-images.githubusercontent.com/4389395/55467495-b7cafb80-5601-11e9-9a04-5f1b1e0378e5.png)

**Result:**
![Bildschirmfoto 2019-04-03 um 11 15 30](https://user-images.githubusercontent.com/4389395/55467623-f6f94c80-5601-11e9-828b-418de548dc3a.png)

In 2.2.1 it's only the current session users **DisplayName** that is shown in the Overview table. 
In version 2.1.8, the **DisplayName** was shown for every Keycloak synced user in Users overview. 

**Other details that may be helpful:**
On the "User Details" page (clicked on Rancher ID) the **DisplayName** is shown, regardless which user is viewed.

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): 2.2.1
- Installation option (single install/HA): HA
- Docker version: 18.06

**Comment by alena1108** [comment] 2019-04-05 05:02
@westlywright not sure if it's an UI issue; please assign to me if you think it's api.

**Comment by westlywright** [comment] 2019-04-10 23:27
@ChrisHaPunkt I am having a bit of trouble reproducing this and could use a bit more info if possible? Are you seeing this still? If so can you look at the network requests, find the call to `v3/principals`, and inspect the response data? The data we pull from to build the display name is a computed property that reads `name` else read `id`, if we have a `loginName` on the principals model you'll see that in the paren (which you are) as well. Based solely on the images provided and the trouble I am having reproducing the scenario, I wonder if the data being sent back could be wrong? Can your confirm or deny this?

**Comment by ChrisHaPunkt** [comment] 2019-04-11 07:29
Hi @westlywright,
thank you for your investigation. I'm still facing this issue.
What do you mean with you are computing the display name? My understanding from the docs is, that we can give the SAML Field which contains the "Display Name" ("The AD attribute that contains the display name of users.") [docs](https://rancher.com/docs/rancher/v2.x/en/admin-settings/authentication/keycloak/#configuring-keycloak-in-rancher). I did not come in touch with a **loginName** attribute.

Some context in addition to our configuration:
- the **uid** SAML attribute contains the corresponding **a**-ID  per user (a14cc4b, a0fc3d0,...)
- the **displayName** attribute contains the first and last name of the user and is configured as  "Display Name Field" as shown above.

The **/v3/principals** request responses only my own users data (properties and group memberships) as shown here
![Bildschirmfoto 2019-04-11 um 09 05 08](https://user-images.githubusercontent.com/4389395/55937848-44953b00-5c3a-11e9-9073-8eca1c9252c6.png)

Furthermore, some more insight in **/v3/users/** request and **/v3/principals/keycloak_user%3A%2F%2Fa0fc3d0**
![Bildschirmfoto 2019-04-11 um 09 05 29](https://user-images.githubusercontent.com/4389395/55938636-17e22300-5c3c-11e9-9cab-ec31895bfd3e.png)
![Bildschirmfoto 2019-04-11 um 09 06 47](https://user-images.githubusercontent.com/4389395/55938724-46f89480-5c3c-11e9-9a7b-1dfe5926b5a2.png)


Thank you again for your response. If you need more information, please let me know.

**Comment by westlywright** [comment] 2019-04-11 17:14
@ChrisHaPunkt sorry for the confusion. The computed property I mentioned is in regards to the front end. We use a `displayName` property in the Rancher UI nearly everywhere but not every resource has that property on the model that is returned from the API. In order to account for that, we have a dynamic property on every resource in the Rancher UI called `displayName` that checks if the model has a `name` property and if it not it will return the `id` (every resource should have an id). 

For the `principal` object that is returned from `/v3/principals` API we actually have a [data mangler](https://github.com/rancher/ui/blob/2.1-fixes/app/models/principal.js#L125) that checks to see if the model has the `displayName` property on the way into our JS code and if it does we override the `name` property with `displayName` and delete the key so we don't override the UI's computed `displayName`. I do not think this matters, in this case, those because the `principals` API is not returning a `displayName`, we would see it in the network request, but I thought the explanation may be helpful. 

Based on the API data shown in the images the UI is working correctly. It is displaying the `displayName` which in this case is the `name` param on the principal model and the `loginName` in paren. It just so happens they the same. Additionally, the code that deals with this in the UI has not changed between 2.1 & 2.2. 

Let me do some more digging. Perhaps something changed on the backend between the two versions.

Thanks again for the additional info, very helpful.

**Comment by vincent99** [comment] 2019-07-03 22:00
@alena1108 In the last screenshot above, we're getting a principal and the only information in there is random string, there is no human names there, so the UI can't show them.  I don't know if that's because of a change in our code, or the configuration of the auth provider, but the UI can't return info that's not coming back...

**Comment by ChrisHaPunkt** [comment] 2019-07-12 06:39
If you need more information please let me know.

**Closed** 2024-01-31 16:25 UTC
Labels: kind/bug, area/authentication, [zube]: To Triage, team/area3, squad/auth-providers
