### ISSUE TITLE
GlobalRoleBinding deletion by garbagecollector causing panic in rancher-webhook

### ISSUE THREAD

**Issue by anupama2501** [rancher/rancher#33429] opened 2021-06-29 22:46 UTC
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
1. From global --> security --> users --> created user1 
2. From global --> security --> roles --> create global role with `Resource` `authconfigs` and no verbs
3. Associate the custom role to the user.
4. Delete the custom role

**Result:**
The global custom role is removed from the global --> security --> roles but the error logs in the rancher server are seen continuously for every few minutes.

**Expected Result:**
while syncing garbagecollector.node item, no internal error should be seen

**Other details that may be helpful:**
Logs in rancher:
```
26 garbagecollector.go:309] error syncing item &garbagecollector.node{identity:garbagecollector.objectReference{OwnerReference:v1.OwnerReference{APIVersion:"management.cattle.io/v3", Kind:"GlobalRoleBinding", Name:"grb-vsx84", UID:"4bd9f139-485c-40ef-bdf6-04bcdf9f5cf2", Controller:(*bool)(nil), BlockOwnerDeletion:(*bool)(nil)}, Namespace:""}, dependentsLock:sync.RWMutex{w:sync.Mutex{state:0, sema:0x0}, writerSem:0x0, readerSem:0x0, readerCount:1, readerWait:0}, dependents:map[*garbagecollector.node]struct {}{(*garbagecollector.node)(0xc022354780):struct {}{}}, deletingDependents:false, deletingDependentsLock:sync.RWMutex{w:sync.Mutex{state:0, sema:0x0}, writerSem:0x0, readerSem:0x0, readerCount:0, readerWait:0}, beingDeleted:false, beingDeletedLock:sync.RWMutex{w:sync.Mutex{state:0, sema:0x0}, writerSem:0x0, readerSem:0x0, readerCount:0, readerWait:0}, virtual:false, virtualLock:sync.RWMutex{w:sync.Mutex{state:0, sema:0x0}, writerSem:0x0, readerSem:0x0, readerCount:0, readerWait:0}, owners:[]v1.OwnerReference{v1.OwnerReference{APIVersion:"management.cattle.io/v3", Kind:"GlobalRole", Name:"gr-79d5n", UID:"540f3166-d9bf-4d65-a467-c4b473fd254e", Controller:(*bool)(nil), BlockOwnerDeletion:(*bool)(nil)}}}: Internal error occurred: failed calling webhook "rancherauth.cattle.io": Post "https://rancher-webhook.cattle-system.svc:443/v1/webhook/validation?timeout=10s": EOF
```

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): v2.5.8
- Installation option (single install/HA): Single

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): Infrastructure Provider

**Comment by ryansann** [comment] 2021-06-30 19:52
This issue seems to be leading to orphaned GlobalRoleBindings. GlobalRoleBindings set their associated GlobalRole as an owner reference. When the GlobalRole is deleted, the corresponding GRBs should also be removed by the garbage collector, but this looks to not be happening due to this k8s error that is happening. I am investigating the cause of this.

**Comment by ryansann** [comment] 2021-07-02 22:44
@anupama2501 this is ready to test now. The new chart is: `rancher-webhook-0.1.100-rc4+up0.1.1-rc4`

Some things to note:
- The original error we saw (`Post https://<webhook>/v1/webhook/validate: EOF`) was being caused by a closed connection. The connection was being closed due to a panic. The panic was fixed in wrangler, so I updated that dependency and resolved the panic / closed connection issue.
- The panic was happening due to GlobalRoles not being found when Updating or Deleting GlobalRoleBindings, a responsibility carried out by the k8s garbage collector due to the `OwnerReferences` on these objects, applied in the norman `globalrolebinding.Store`. The webhook now admits requests to delete GlobalRoleBindings and update the finalizers when the associated GlobalRole is not found. This allows for the garbage collector to properly cleanup GlobalRoleBindings after their corresponding GlobalRole is removed, which solves the problem of orphaned GRBs which we were seeing as a result of this issue.
- The debugging functionality of the webhook was improved, via debug logs through specifying `RANCHER_DEBUG=true` as an environment variable

To properly test this, we need to make sure a few things are true:
1. The error logs previously seen coming from the `kube-apiserver` should no longer happen. 
2. Perform these steps:
- Add alice as a Standard User
- Create a GlobalRole with any permissions
- Associate alice to the newly created GlobalRole
- In the management cluster, note the creation of a GlobalRoleBinding via: `kubectl get globalrolebindings` (it will be the newest one in the list)
- Delete the GlobalRole that you created
- Observe the GlobalRoleBinding that was recently created has been successfully removed
3. Further validation can be done with these steps
- Add `RANCHER_DEBUG=true` to the webhook deployment
- Perform the steps in 2.
- Observe logs like the following: `DEBU[0041] admit result: DELETE management.cattle.io/v3, Kind=GlobalRoleBinding grb-8xgqv user=system:serviceaccount:kube-system:generic-garbage-collector allowed=true err=<nil>` in the rancher-webhook pod logs. These logs are saying that the garbage collector was allowed to delete GlobalRoleBinding grb-xxxxx.

**Comment by anupama2501** [comment] 2021-07-06 18:38
Verified on rancher-server: `v2.5.9-rc4`, webhook version: `rancher-webhook:v0.1.1-rc4`
1. From global --> security --> roles, created a global role - au-g1, with auth configs and verb:list
2. Created a standard user - user1 and associated au-g1 to the user.
3. Verified from the management cluster kubectl that the global role bindings was created:
```
kubectl get globalrolebindings
grb-gs96h 
```
4. Deleted the global role au-g1
5. Verified from the kubectl command that the global rolebindings was deleted.

Enabling `RANCHER_DEBUG=true` in the webhook deployment
1. Added the environment variable `RANCHER_DEBUG=true`, and upgraded the webhook deployment
2. Verified the debug logs of the rancher webhook pod, displays the global role deleted:
```
time="2021-07-06T18:28:16Z" level=debug msg="admit result: DELETE management.cattle.io/v3, Kind=GlobalRoleBinding grb-tsjk8 user=system:serviceaccount:kube-system:generic-garbage-collector allowed=true err=<nil>"
time="2021-07-06T18:28:16Z" level=debug msg="admit result: UPDATE management.cattle.io/v3, Kind=GlobalRoleBinding grb-tsjk8 user=system:admin allowed=true err=<nil>"
```

**Upgrade scenario, rancher server: v2.5.8, before upgrade webhook:v0.1.000**
1. From global --> security --> roles, created a global role - au-g1, with auth configs and verb:list
2. Created a standard user - user1 and associated au-g1 to the user.
3. Verified from the management cluster kubectl that the global role bindings was created:
4. Deleted the global role au-g1
5. Following logs are seen in the rancher server ``` 23 garbagecollector.go:309] error syncing item &garbagecollector.node{identity:garbagecollector.objectReference{OwnerReference:v1.OwnerReference{APIVersion:"management.cattle.io/v3", Kind:"GlobalRoleBinding", Name:"grb-sv7xf", UID:"2907e138-b07a-4e5b-9b0d-aab9612e4bf5", Controller:(*bool)(nil), BlockOwnerDeletion:(*bool)(nil)}, Namespace:""}```
6. Added the nev variables in the webhook deployment `RANCHER_DEBUG=true` 
7. Upgraded the webhook to version `rancher-webhook:v0.1.1-rc4`
8. Verified the grb is removed and no logs for garbage collector is seen.
9. verified the webhook pod logs `time="2021-07-06T18:32:25Z" level=debug msg="admit result: DELETE management.cattle.io/v3, Kind=GlobalRoleBinding grb-sv7xf user=system:serviceaccount:kube-system:generic-garbage-collector allowed=true err=<nil>"
`

**Closed** 2021-07-06 21:42 UTC
Labels: QA/S, [zube]: QA Working, kind/bug-qa
