### ISSUE TITLE
Disk space not showing and host stats not working

### ISSUE THREAD

**Issue by garduch** [rancher/rancher#2664] opened 2015-11-13 09:44 UTC
CoreOS 766.5.0
Docker v1.7.1
rancher 	v0.44.0

Disk space not showing and host stats not working.
![screen shot 2015-11-13 at 10 43 09](https://cloud.githubusercontent.com/assets/15831019/11143146/5a950100-89f3-11e5-99dd-bf33f43313c9.png)
![screen shot 2015-11-13 at 10 43 30](https://cloud.githubusercontent.com/assets/15831019/11143159/6f34d2e8-89f3-11e5-85b7-925feec3ea7a.png)

**Comment by deniseschannon** [comment] 2015-11-13 18:37
Duplicate of https://github.com/rancher/rancher/issues/2380 and https://github.com/rancher/rancher/issues/2205

These issues have been fixed in master and will be available in our next release of Rancher.

**Closed by deniseschannon** 2015-11-13 18:37 UTC
