### ISSUE TITLE
Avoid second container for a service on a host where a first container for the service is running

### ISSUE THREAD

**Issue by siwonne** [rancher/rancher#7029] opened 2016-12-13 13:40 UTC
**Rancher Version:*v1.1.4

**Docker Version:*1.12.1*

**OS and where are the hosts located? (4.4.27-boot2docker on docker-machine( driver: virtualbox 4.3.36_Ubuntur105129) on ubuntu 14.04.1):**

**Setup Details: (single node rancher )**

**Environment Type: (Cattle)**

**Steps to Reproduce:**
service:
  labels:
    io.rancher.container.affinity:container_label_ne:    io.rancher.stack_service.name=$${stack_name}/$${service_name}

**Results:** 
Two containers for the same service are running on one host.

**Expected:**
Atmost one container for the service should run on a host.

**Comment by salvax86** [comment] 2016-12-14 12:05
I had the same issue with Rancher v1.2.0:

**rancher-compose.yml**

```
service-A:
    retain_ip: true
    scale: 3
```

**docker-compose.yml**

```
service-A:
    image: busybox
    labels:
      io.rancher.scheduler.affinity:host_label: A=true
      io.rancher.container.affinity:container_label_ne: io.rancher.stack_service.name=$${stack_name}/$${service_name}
```

Inspired by community catalog (kafka, zookeeper), my workaround was:

**rancher-compose.yml**

```
service-A:
    retain_ip: true
```

**docker-compose.yml**

```
service-A:
    image: busybox
    labels:
      io.rancher.scheduler.affinity:host_label: A=true
      io.rancher.scheduler.global: true
```

Through this approach it is garanted that the service-A is started on every hosts with label "A=true" and only once

**Comment by siwonne** [comment] 2016-12-15 14:10
Grazie!

**Comment by siwonne** [comment] 2016-12-15 15:56
But then you cannot scale anymore.

**Comment by salvax86** [comment] 2016-12-15 15:58
You scale through 'labeling' on new instances. Steps for my example:
1. Add new host
2. Put on new host the label "A=true"
3. Wait a little and a new container is starting on the host

**Comment by siwonne** [comment] 2016-12-21 12:58
That seems to work for now. Nevertheless it is a BUG!

**Comment by aemneina** [comment] 2017-05-12 18:43
Cant reproduce this on 1.5.9. Closing this out, feel free to holler if you can reproduce on a newer version of rancher.

**Closed by aemneina** 2017-05-12 18:43 UTC
