### ISSUE TITLE
[cli] command "rancher run" cannot add parameter environment(like docker run -e)

### ISSUE THREAD

**Issue by neillau24** [rancher/rancher#8560] opened 2017-04-21 06:23 UTC
**Rancher Versions:**
Server:1.5.6 rc1
healthcheck:v0.2.3
ipsec:holder
network-services:v0.6.6
scheduler:v0.7.5
kubernetes (if applicable):

**Docker Version:**17.03

**OS and where are the hosts located? (cloud, bare metal, etc):**

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**Cattle

**Steps to Reproduce:**

**Results:**

**Comment by deniseschannon** [comment] 2017-06-05 23:26
Pre-duplicate of https://github.com/rancher/rancher/issues/8589

**Closed by deniseschannon** 2017-06-05 23:26 UTC
Labels: area/cli
