### ISSUE TITLE
Rancher 2.0 - unknown authority in kubectl command

### ISSUE THREAD

**Issue by etlweather** [rancher/rancher#13621] opened 2018-05-21 17:02 UTC
**Rancher versions:**
rancher/server or rancher/rancher: 2.0
rancher/agent or rancher/rancher-agent: 2.0

Opening the Kubectl option from the UI, the `kubectl` command returns `x509: certificate signed by unknown authority`.

I'm using a certificate signed by an internal CA so the CA Cert isn't known to this service.

**Comment by superseb** [comment] 2018-05-22 15:29
If cacerts is not properly parsed/recognized/loaded, it will also fail for other components that depend on it (embedded kubectl for instance). Closing as duplicate of https://github.com/rancher/rancher/issues/13615

**Closed by superseb** 2018-05-22 15:29 UTC
