### ISSUE TITLE
Different bundles at same GitRepo is not being updated accordingly

### ISSUE THREAD

**Issue by MKlimuszka** [rancher/rancher#36243] opened 2022-01-24 16:35 UTC
*Issue description:*
Have 2 bundles defined on an unique GitRepo. 
Example:
(1) manifest configmap bundle 
(2) helm chart which uses the configmap as its values - using dependsOn. 

Expectation is that (1) configmap was updated it re-runs (2) helm chart. 
Observed behavior: The (1) configmap is being updated in k8s after its changed in git but the (2) does not run automatically. Customer need to do 'Force update' manually

*Business impact:*
No business impact, but its broken the automation and need manual actions.

*Troubleshooting steps:*
 - customer call simulating the issue for watching the behavior described.

*Repro steps:*

Reproduce the behavior in a LAB. [https://github.com/leonardoalvesprates/k8s/tree/master/lab/fleet/nginx-configmap-helm.] 

I faced the same results. (1) bundle configmap upload k8s configmap as expected but (2) bundle helm chart did not re-run automatically. It works at the creating time of the GitRepo only, but further updates in git did not re-run automatically.

*Workaround:*
 Is workararound available and implemented? yes
 In a LAB, when I changed the helm chart file Chart.yaml values like version and appVersion it seems to re-ran as expected.

*Actual behavior:*
Bundles in same GitRepo not being re-run as expected

*Expected behavior:*
 Re-run automatically both bundles when changes happened in git.

*Files, logs, traces:*
 <text>

*Additional notes:*
SURE-3608

**Comment by izaac** [comment] 2022-04-04 22:56
Could be the test data be made public or attached here as zip for creating a sample repository and try to reproduce ?

Access to https://github.com/leonardoalvesprates/k8s/tree/master/lab/fleet/nginx-configmap-helm.  results in a 404 for me.

**Comment by izaac** [comment] 2022-07-06 23:33
Rancher version: `v2.6.3`
Fleet: `v0.3.8`

I'm not able to reproduce 
I tried updating the ConfigMap in the configmap bundle only.
This from my git repo forked from the lab repo and I see in the fleet-agent logs that the helm upgrade is triggered for both the helm bundle (dependsOn manifests) and the manifests bundle.

Im not sure if im missing a step, do we have more info or steps to repro

**Comment by izaac** [comment] 2022-07-11 21:04
Requested more info in SURE-3608

**Comment by mattfarina** [comment] 2022-07-21 19:21
Removing the milestone as this looks like it's not an issue with fleet.

When you use Helm and there is no change in its manifests on upgrade Kubernetes won't make an update that restarts the pods. If you want to force an update there are two methods.

1. [Use an annotation that picks up a change in a configmap and force a restart](https://helm.sh/docs/howto/charts_tips_and_tricks/#automatically-roll-deployments)
2. On `helm upgrade` there is a `--force` flag that will "force resource updates through a replacement strategy". It looks like setting a bundledeployment for Helm to force will cause a force on upgrade. [You can see it in the fleet source here](https://github.com/rancher/fleet/blob/5a141a6b18f0e778b1ba1c248d76f9b03c0bf06c/pkg/helmdeployer/deployer.go#L342).

In the example provided, the helm chart depends on a configmap. Changes to that configmap won't cause a change in the Helm chart so k8s won't apply a change that causes pods to restart. The bundle needs to be forced to restart which is, I think possible, with the force option on the bundle for the Helm chart.

**Comment by thardeck** [comment] 2022-09-28 07:51
@MKlimuszka Should we close the issue following @mattfarina explanation?

**Closed** 2022-11-15 15:13 UTC
Labels: kind/bug, internal, [zube]: Working, area/fleet, team/fleet
