### ISSUE TITLE
Location and Size fields can not display correctly for newly added node driver in node template list page

### ISSUE THREAD

**Issue by ly5156** [rancher/rancher#18492] opened 2019-03-01 03:32 UTC
**What kind of request is this (question/bug/enhancement/feature request):**
feature request

**Steps to reproduce (least amount of steps as possible):**
1. Click the Add Node Driver button in the Node Drivers tab on drivers page
2. input download url of pingan node driver, and custom ui url of pingan
3. add whitelist domain of custom ui
4. click save botton and wait for active
5. go to node templates page and add pingan template

**Result:**
pingan node driver on node templates page, location and size cannot be displayed

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): master

**Comment by davidnuzik** [comment] 2019-03-01 17:30
@ly5156 could you provide me the location of the pingan node driver url? Where can I get the custom UI as well? Or, @westlywright is this something I can testing using the google-gke example?

**Comment by davidnuzik** [comment] 2019-03-04 20:47
Assigned to @ly5156 for testing to validate this is now working correctly. We are unable to test with the pingan driver or something similar.

**Comment by davidnuzik** [comment] 2019-03-15 15:57
We believe the issue is resolved but do not have the means to validate currently and we have not heard back from the author. I've been asked to close this issue.

**Closed by davidnuzik** 2019-03-15 15:57 UTC
Labels: area/node-template, status/resolved, status/to-test
