### ISSUE TITLE
Regression: No DNS resolution inside container

### ISSUE THREAD

**Issue by jloisel** [rancher/rancher#4291] opened 2016-04-05 08:19 UTC
Rancher Version: 1.0.0

Docker Version: 1.10.3

OS: Ubuntu 14.04.3 LTS

Steps to Reproduce: 
1. Start Rancher 1.0.0 from scratch,
2. Add your own machine as host with -e CATTLE_AGENT_IP=<local network ip>,
3. Create a stack with an "ubuntu" service which launches an ubuntu container,
4. Execute shell inside the container and try "ping google.com"

Results: 
ping: unknown host google.com

Expected:
It should successfully resolve google.com.

Everything was working fine with Rancher v0.63.1.

**Comment by jloisel** [comment] 2016-04-05 08:32
Further investigation shows that it's happening when the container is using "managed" network configuration. When trying with "host", the command executes successfully.

**Comment by deniseschannon** [comment] 2016-04-05 17:56
I am unable to reproduce.

Where is your OS hosted? I did your setup in Digital Ocean and was able to `ping google.com` inside the container on the host that also has rancher/server running.

**Comment by deniseschannon** [comment] 2016-04-05 17:59
Can you share your `/etc/resolv.conf` inside the container that is failing to ping as well as the network agent on that host?

**Comment by tfiduccia** [comment] 2016-04-05 19:33
Created a custom host with -e CATTLE_AGENT_IP= <rancher ip>, ubuntu service with managed network and I also could not reproduce.

**Comment by jloisel** [comment] 2016-04-06 06:48
My /etc/resolv.conf shows:
> search rancher.internal
nameserver 169.254.169.250

Here is a screenshot of an ubuntu container run with managed network showing the dns issue:
![dns-issue](https://cloud.githubusercontent.com/assets/3208716/14308036/ac432bce-fbd3-11e5-8655-31e03aa2fb82.png)

Only a single machine (my own host) has been added using custom command line with -e CATTLE_AGENT_IP added (as it's required when running on same host as the server):

![single-machine](https://cloud.githubusercontent.com/assets/3208716/14308081/fed13dcc-fbd3-11e5-89b0-8a78bfa28d39.png)

for some reason, the rancher internal dns doesn't resolve external domains. Everything was working fine with v0.63.1. After upgrading, Jenkins could not download our sources from remote Git anymore this is how I discovered the whole issue.

I've tried also with a fresh copy of Rancher (without any volume binding), and it's facing the same issue. Can reproduce anytime on my machine.

**Comment by vincent99** [comment] 2016-04-06 07:19
@jloisel Can you grab the contents of `/var/lib/cattle/etc/cattle/dns/answers.json`from the Network Agent container?

**Comment by jloisel** [comment] 2016-04-06 08:01
I can successfully reproduce the issue on my laptop too. A fresh Rancher 1.0.0 install with same machine as host.

Here is the json file you asked:
https://gist.github.com/jloisel/07625a084eb87b93cfb73afa38ad3c6a

**Comment by vincent99** [comment] 2016-04-06 15:56
Gist seems to have eaten the format of the file, but close enough... So the recursive lookup server that is used defaults to the one in the host's resolv.conf.  In this case it is `127.0.1.1`.

Do you have a local DNS cache running on the host?  That IP is essentially localhost, so it isn't going to be reachable from within the network agent container.

**Comment by jloisel** [comment] 2016-04-06 17:08
I don't have any DNS cache being installed on any machine. Both are running a stock Ubuntu 14.04.4 LTS for years. Again, it's working fine with Rancher v0.63.1 and lower.

**Comment by jloisel** [comment] 2016-04-06 17:28
With Rancher v0.63.1, the answers.json contains:

> {"10.42.71.19":{"search":["rancher.internal","default.rancher.internal","ubuntu.
default.rancher.internal"],"recurse":[],"a":{},"cname":{}},"default":{"search":[
],"recurse":["8.8.8.8", "8.8.4.4"],"a":{"rancher-metadata.rancher.internal.":{"a
nswer":["169.254.169.250"]},"default_ubuntu_1.ubuntu.default.rancher.internal.":
{"answer":["10.42.71.19"]},"ubuntu.default.rancher.internal.":{"answer":["10.42.
71.19"]}},"cname":{}}}

It seems like Rancher v0.63.1 is configured to use Google's DNS.

**Comment by jloisel** [comment] 2016-04-06 17:29
With Rancher v0.63.1, it obviously works since it uses Google DNS. I don't have configured Google DNS anywhere:

![rancher-0 63 1](https://cloud.githubusercontent.com/assets/3208716/14326336/ccb1fd68-fc2d-11e5-9800-7368ef459e05.png)

**Comment by jloisel** [comment] 2016-04-06 17:58
It seems like Ubuntu uses dnsmasq coupled with Network Manager starting from 12.04:

> jerome@jerome-pc:/etc/init.d$ ps aux | grep dns
nobody    2078  0.0  0.0  27216  1412 ?        S    19:06   0:00 /usr/sbin/dnsmasq --no-resolv --keep-in-foreground --no-hosts --bind-interfaces --pid-file=/run/sendsigs.omit.d/network-manager.dnsmasq.pid --listen-address=127.0.1.1 --conf-file=/var/run/NetworkManager/dnsmasq.conf --cache-size=0 --proxy-dnssec --enable-dbus=org.freedesktop.NetworkManager.dnsmasq --conf-dir=/etc/NetworkManager/dnsmasq.d

Which explains why DNS queries get answered on 127.0.1.1.

**Comment by jloisel** [comment] 2016-04-06 18:23
After disabling dnsmasq (which is enabled by default on Ubuntu 12.04 and above), it works fine with Rancher 1.0.0. It now uses the right dns, provided by DHCP by our internet box.

**Comment by vincent99** [comment] 2016-04-06 21:09
I assume from the picture that you mean Ubuntu Desktop?  Server doesn't come with dnsmasq by default anywhere that I'm aware of.

**Comment by jloisel** [comment] 2016-04-07 06:12
Yes, Ubuntu Desktop. I think it deserves a page in your documentation to explain how to configure Ubuntu to have properly working DNS in Rancher. Or, Rancher should be able to translate 127.0.1.1 to the IP address of the host machine to ensure dns calls are not lost inside the network agent container.

**Comment by deniseschannon** [comment] 2016-04-07 21:49
I'm surprised that you got ubuntu desktop working as someone else was unable to get it to work.

https://github.com/rancher/rancher/issues/4291

**Comment by jloisel** [comment] 2016-04-08 07:59
Have you a link to the person thread or issue who couldn't make it work? Anyway, I think this should be fixed to avoid having to mess up with Ubuntu Desktop default configuration. It's quite annoying to have to tune the operating system to fix some strange issues like this.

**Comment by deniseschannon** [comment] 2016-04-08 19:20
The issue #4291 is the person who couldn't make Ubuntu Desktop work.

**Comment by jloisel** [comment] 2016-04-08 20:03
I think you have mistakingly have put the same issue number as here.

**Comment by deniseschannon** [comment] 2016-04-08 21:31
Apologies: https://github.com/rancher/rancher/issues/4175

Just FYI, you can also search the issues to try and find similar ones. I just searched for "Ubuntu Desktop" to find the issue.

**Comment by vincent99** [comment] 2016-04-08 23:42
So there is code in the docker daemon that detects this situation of a `127.*` nameserver and defaults the container to Google's instead (`8.8.8.8` and `8.8.4.4`).  But that gets disabled if `--dns-search` is passed, which we do for the Network Agent container.

**Comment by alena1108** [comment] 2016-06-01 21:02
Should be fixed with:

```
alena@Alenas-MacBook-Pro: [scaleupgrading]~/repos/cattle$ git show 35b5332
commit 35b5332bbb0e62f357a37e0fe0270a806c040c88
Author: Alena Prokharchyk <alena@rancher.com>
Date:   Fri Apr 8 23:59:08 2016 -0700

    Don't set rancher.internal search domain for system containers
```

@sangeethah to test, change dns on your compute host to 127.0.0.1, trigger network agent start and verify that the dns is set to google dns in the containers /etc/resolv.conf and answers.json file, recurse field.

**Comment by soumyalj** [comment] 2016-06-04 00:12
Reproduced the issue in Rancher v1.0.0 as below:
<img width="1920" alt="screen shot 2016-06-03 at 5 06 14 pm" src="https://cloud.githubusercontent.com/assets/18536626/15796163/31e824e8-29ae-11e6-98f4-618eaaede365.png">

Verified the fix in master
<img width="976" alt="screen shot 2016-06-03 at 5 09 20 pm" src="https://cloud.githubusercontent.com/assets/18536626/15796171/4ac850e6-29ae-11e6-8c1a-6448f572f353.png">

**Closed by soumyalj** 2016-06-04 00:12 UTC
Labels: area/agent, kind/bug, status/to-test

**Comment by gerich-home** [comment] 2016-09-08 10:21
I have found a different workaround for the issue (with no change to dnsmasq). Check it here: https://github.com/rancher/rancher/issues/5920

**Comment by Vergnais** [comment] 2016-09-27 13:52
Hi,

I fear i face the same issue on debian 8. As soon as I use "managed network" my dns can't resolve internet addresses. 
In containers i have : cat /etc/resolv.conf
search <xxxxx.xxx> rancher.internal
nameserver 169.254.169.250

I've started docker daemon on my host with --dns parameter : 
/usr/bin/dockerd --dns <xxx.xxx.xxx.xxx> -H fd://

docker version : Docker version 1.12.1, build 23cf638
rancher version : 1.1.4

no dnsmasq started on host.

Of course when manually changing container /etc/resolv.conf with my external  <xxx.xxx.xxx.xxx> dns server address, the container resolves correctly.

What may I have missed ?

**Comment by VAdamec** [comment] 2017-01-24 10:02
Same here, latest version Rancher, by default only 169.254.169.250 is added to resolv.conf in containers. I can add them via docker-compose file, but that make no sense, it need to be inherited from host.

**Comment by VAdamec** [comment] 2017-01-24 12:02
Hm, I even cannot add them via docker-compose, Rancher result for such attempt looks like this (it's added by commented out):

#/etc/resolv.conf on instance
search rancher.internal openstacklocal chrome.selenium.rancher.internal selenium
.rancher.internal
# nameserver 10.0.0.1
# nameserver 10.0.0.2
nameserver 169.254.169.250

**Comment by gprime44** [comment] 2017-02-08 16:41
A have exactly the same problem.

If i add a Resolving Server (8.8.8.8) with Managed Network, i can't acces to the Internet 
![image](https://cloud.githubusercontent.com/assets/18438018/22746806/51f6f9ee-ee25-11e6-8549-188c8ffcb44d.png)

and my /etc/resolv.conf is commented inside my container

![image](https://cloud.githubusercontent.com/assets/18438018/22746929/d3a8af96-ee25-11e6-85ef-33e19a4397a3.png)

**Comment by vincent99** [comment] 2017-02-08 17:16
This issue is nearly a year old and closed.  That is what the resolv.conf supposed to look like.  Rancher runs its own DNS server on each host, which responds to requests for internal names (*.rancher.internal) and recurses to the configured resolvers for names it does not handle.  Multiple `nameserver` entries are *backups*, they are not tried in order if the first one responds.

**Comment by gprime44** [comment] 2017-02-08 18:22
Ok sorry, my mistake. So why my container can't access to the Internet if i use the Managed network ? It work fine with "bridge", but a can't use "links".

**Comment by Shubhankitmishra** [comment] 2018-08-03 12:34
https://github.com/jderusse/docker-dns-gen/issues/21?_pjax=%23js-repo-pjax-container
Find The solution here
