### ISSUE TITLE
Do not reference stack name in rancher-compose.yml if link is in same stack

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#7033] opened 2016-12-13 18:13 UTC
**Rancher Version:** version - v1.2.0

**Steps to Reproduce:**
1.  Create a stack and add a service
2.  Add a load balancer and link to the service
3.  Export or view the config

**Results:** Notice that the service: tag in the rancher.compose.yml says stackname/service.

**Expected:** If the stack is not external it should not reference the stack name.

**Comment by deniseschannon** [comment] 2016-12-13 18:15
Duplicate of https://github.com/rancher/rancher/issues/6829

**Closed by deniseschannon** 2016-12-13 18:15 UTC
Labels: area/container, kind/bug
