### ISSUE TITLE
[external-dns]  Aliases on Route53 trigger a crash

### ISSUE THREAD

**Issue by marcbachmann** [rancher/rancher#4949] opened 2016-05-28 16:22 UTC
**Rancher Version:**
v1.1.0-dev3

**Docker Version:**
1.11.1

**OS and where are the hosts located?** ubuntu, vps, scaleway.com

**Setup Details:** single node rancher

**Environment Type: ** Cattle

**Steps to Reproduce:**
Set up `rancher/external-dns` to use Route53, create a service, that gets registered on s3 and then create an alias record from your root domain to the domain created by the service.

<img width="409" alt="screen shot 2016-05-28 at 5 53 47 pm" src="https://cloud.githubusercontent.com/assets/431376/15628396/6963d5b4-2500-11e6-8807-e99e13393818.png">

**Results:** 
`rancher/external-dns` creashes and can't recover until you delete the alias again.
```
2016/05/28 15:10:38 http: panic serving 10.42.121.230:33332: runtime error: invalid memory address or nil pointer dereference
goroutine 1111 [running]:
net/http.(*conn).serve.func1(0xc8202f9130, 0x7f3dfd482890, 0xc8200294e8)
	/usr/local/go/src/net/http/server.go:1287 +0xb5
github.com/rancher/external-dns/providers.(*Route53Handler).GetRecords(0xc8200eb560, 0x0, 0x0, 0x0, 0x0, 0x0)
	/source/gopath/src/github.com/rancher/external-dns/providers/route53.go:171 +0x5ae
main.healtcheck(0x7f3dfd492b68, 0xc8202f8e70, 0xc8202efb20)
	/source/healthcheck.go:28 +0x1be
net/http.HandlerFunc.ServeHTTP(0xc15790, 0x7f3dfd492b68, 0xc8202f8e70, 0xc8202efb20)
	/usr/local/go/src/net/http/server.go:1422 +0x3a
github.com/gorilla/mux.(*Router).ServeHTTP(0xc8200e86e0, 0x7f3dfd492b68, 0xc8202f8e70, 0xc8202efb20)
	/source/Godeps/_workspace/src/github.com/gorilla/mux/mux.go:100 +0x29e
net/http.serverHandler.ServeHTTP(0xc82011f260, 0x7f3dfd492b68, 0xc8202f8e70, 0xc8202efb20)
	/usr/local/go/src/net/http/server.go:1862 +0x19e
net/http.(*conn).serve(0xc8202f9130)
	/usr/local/go/src/net/http/server.go:1361 +0xbee
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:1910 +0x3f6
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x53bfbe]

goroutine 1 [running]:
github.com/rancher/external-dns/providers.(*Route53Handler).GetRecords(0xc8200eb560, 0x0, 0x0, 0x0, 0x0, 0x0)
	/source/gopath/src/github.com/rancher/external-dns/providers/route53.go:171 +0x5ae
main.getProviderDnsRecords(0x9, 0x0, 0x0)
	/source/external-dns.go:130 +0x4c
main.UpdateProviderDnsRecords(0xc8203af9b0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/source/external-dns.go:12 +0x67
main.main()
	/source/main.go:122 +0x4e9

goroutine 37 [IO wait, 12 minutes]:
net.runtime_pollWait(0x7f3dfd43f050, 0x72, 0xc82000a150)
	/usr/local/go/src/runtime/netpoll.go:157 +0x60
net.(*pollDesc).Wait(0xc820179790, 0x72, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:73 +0x3a
net.(*pollDesc).WaitRead(0xc820179790, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:78 +0x36
net.(*netFD).Read(0xc820179730, 0xc8203ff000, 0x800, 0x800, 0x0, 0x7f3dfd47e050, 0xc82000a150)
	/usr/local/go/src/net/fd_unix.go:232 +0x23a
net.(*conn).Read(0xc820028538, 0xc8203ff000, 0x800, 0x800, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/net.go:172 +0xe4
crypto/tls.(*block).readFromUntil(0xc8204b2f00, 0x7f3dfd482938, 0xc820028538, 0x5, 0x0, 0x0)
	/usr/local/go/src/crypto/tls/conn.go:455 +0xcc
crypto/tls.(*Conn).readRecord(0xc82008edc0, 0xc15e17, 0x0, 0x0)
	/usr/local/go/src/crypto/tls/conn.go:540 +0x2d1
crypto/tls.(*Conn).Read(0xc82008edc0, 0xc82023a000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/go/src/crypto/tls/conn.go:901 +0x167
net/http.noteEOFReader.Read(0x7f3dfd492a20, 0xc82008edc0, 0xc82013cf78, 0xc82023a000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/http/transport.go:1370 +0x67
net/http.(*noteEOFReader).Read(0xc8204bd460, 0xc82023a000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	<autogenerated>:126 +0xd0
bufio.(*Reader).fill(0xc820401da0)
	/usr/local/go/src/bufio/bufio.go:97 +0x1e9
bufio.(*Reader).Peek(0xc820401da0, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/bufio/bufio.go:132 +0xcc
net/http.(*persistConn).readLoop(0xc82013cf20)
	/usr/local/go/src/net/http/transport.go:876 +0xf7
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:685 +0xc78
```

**Expected:**
Better error handling

**Comment by vincent99** [comment] 2016-05-28 19:59
@alena1108 @janeczku wasn't this supposed to be fixed in the 0.4 image?

**Comment by janeczku** [comment] 2016-05-29 16:48
@vincent99 It was fixed in v0.4.1. We just need to merge the updated catalog template (i don't have  permissions for that repo): https://github.com/rancher/rancher-catalog/pull/148

**Comment by janeczku** [comment] 2016-05-29 16:54
Duplicate of https://github.com/rancher/rancher/issues/4671

**Comment by deniseschannon** [comment] 2016-05-29 22:24
@marcbachmann The latest template has been release. Please re-open if you still face the issue.

**Closed by deniseschannon** 2016-05-29 22:24 UTC

**Comment by marcbachmann** [comment] 2016-05-29 22:33
Thanks. Everything is working. Nice work!
