### ISSUE TITLE
Can't edit environment name and description

### ISSUE THREAD

**Issue by silviupanaite** [rancher/rancher#1856] opened 2015-08-22 12:04 UTC
When I try to modify the name of an existent environment it will not save.
Component	Version
Rancher	v0.32.0
Cattle	v0.75.0
User Interface	v0.40.0
Rancher Compose	beta/latest

**Comment by deniseschannon** [comment] 2015-08-22 15:54
@silviupanaite This is most likely a duplicate of https://github.com/rancher/rancher/issues/1590. 

Can you try clicking on the Environment name and Edit from the detailed environment name? There is a UI bug that will be fixed in the next release where editing from the "Manage Environments" page is broken.

**Closed by deniseschannon** 2015-08-22 15:54 UTC

**Comment by silviupanaite** [comment] 2015-08-31 08:54
Yes it is. Thank you

**Comment by deniseschannon** [comment] 2015-08-31 17:05
@silviupanaite This was fixed in v0.34.0. Please let me know when you test out that version if it's still an issue.

**Comment by silviupanaite** [comment] 2015-09-09 14:36
It is fixed.
