### ISSUE TITLE
[RKE2 snapshot] Inconsistent file size for etcd snapshot

### ISSUE THREAD

**Issue by timhaneunsoo** [rancher/rancher#37382] opened 2022-04-18 17:44 UTC
**Rancher Server Setup**
- Rancher version: v2.6-head b8cbc1a
- Installation option (Docker install/Helm Chart):
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc):
- Proxy/Cert Details:

**Information about the Cluster**
- Kubernetes version: v1.22.8+rke2r1
- Cluster Type (Local/Downstream):
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider): RKE2 node driver cluster

**User Information**
- What is the role of the user logged in? (Admin/Cluster Owner/Cluster Member/Project Owner/Project Member/Custom)
  - If custom, define the set of permissions: Standard

   
**Describe the bug**

When taking a etcd snapshot on RKE2, there is an inconsistency in the file size. The snapshot files should be the same across all the machines.

**To Reproduce**
 
1. Create RKE2 node driver cluster as a Standard user (3 etcd, 2 cp, 3 worker)
2. Once the cluster becomes active, take a snapshot
3. View the snapshot file sizes

**Result**
One of the etcd snapshots' size is different

**Expected Result**

All the file sizes should be the same, since the snapshot should be shared across all the etcd nodes.

**Screenshots**

<img width="1469" alt="image" src="https://user-images.githubusercontent.com/97477402/163849926-b67cb6c5-50c1-49f1-862f-eec6b0a61b17.png">

**Comment by snasovich** [comment] 2022-04-18 20:46
@timhaneunsoo , looks to be the duplicate of https://github.com/rancher/rancher/issues/36713. Please close if that is correct.

**Comment by timhaneunsoo** [comment] 2022-04-19 14:50
Closing as duplicate of [36713](https://github.com/rancher/rancher/issues/36713)

**Closed** 2022-04-19 14:50 UTC
Labels: kind/bug-qa, [zube]: QA Next up, status/duplicate, duplicate, team/area2
