### ISSUE TITLE
Duplicate host entries in infrastructure tab

### ISSUE THREAD

**Issue by juliengarcia** [rancher/rancher#2868] opened 2015-12-02 08:10 UTC
Hello, 
when I restart a machine on which rancher agent is, the host entry is duplicated in the infrastructure tab in the GUI.

<img width="888" alt="screen shot 2015-12-02 at 09 09 53" src="https://cloud.githubusercontent.com/assets/3304363/11525576/7b81929e-98d4-11e5-8a12-7c21a3e860c3.png">

**Comment by deniseschannon** [comment] 2015-12-02 18:11
Duplicate of the closed issue of https://github.com/rancher/rancher/issues/936

If you scroll down to @imikushin's comment about why this occurs with boot2docker, it should explain why it's happening.

**Closed by deniseschannon** 2015-12-02 18:11 UTC
