### ISSUE TITLE
Could not get stats from cAdvisor;  TypeError: 'NoneType' object has no attribute '__getitem__'"

### ISSUE THREAD

**Issue by NigelThorne** [rancher/rancher#1147] opened 2015-06-11 04:57 UTC
I'm running rancher/server:beta  (as of 5 days ago)  which seems to be v0.23.0-rc6

Trying to start an agent using the commandline given
```sudo docker run -d --privileged -v /var/run/docker.sock:/var/run/docker.sock rancher/agent:v0.7.9 http://octohost:8080/v1/scripts/3644335875869986112F:1433995200000:X6dIbmWCJSdJu86q8dDqkaMsSA```
or as the blog mentioned... with the environment varliable
``` sudo docker run -d --privileged  -e CATTLE_AGENT_IP=10.10.240.245  -v /var/run/docker.sock:/var/run/docker.sock rancher/agent:latest http://octohost:8080/v1/scripts/3644335875869986112F:1433980800000:4pC98X6cjCQv1UFUez9gNcxqkg```

Either way I'm getting the agent stopping instantly with 'wrong version' error.

```
docker logs 0fb4ada61aa5

INFO: Running Agent Registration Process, CATTLE_URL=http://octohost:8080/v1
time="2015-06-11T00:58:45Z" level=fatal msg="Error response from daemon: client and server don't have same version (client : 1.18, server: 1.16)"
INFO: Checking for Docker version >= 1.6.0
Please ensure Host Docker version is >= 1.6.0 and container has r/w permissions to docker.sock
```

I've tried a few version of the agent:

```
docker images
REPOSITORY            TAG                 IMAGE ID            CREATED             VIRTUAL SIZE
rancher/server        beta                46e42c673c30        5 days ago          507.5 MB
rancher/server        latest              46e42c673c30        5 days ago          507.5 MB
rancher/server        v0.23.0-rc6         46e42c673c30        5 days ago          507.5 MB
rancher/agent         v0.7.9              8def006f0d7a        11 days ago         372.4 MB
rancher/agent         v0.7.8              5882d6b384ef        2 weeks ago         330.8 MB
rancher/agent         v0.7.6              a1d174884260        4 weeks ago         307.5 MB
rancher/agent         latest              a1d174884260        4 weeks ago         307.5 MB
```
ps: Is the agent a client or a server?

**Comment by deniseschannon** [comment] 2015-06-11 05:55
The issue is that your machine needs to have a docker version that's greater than 1.6.0. Ideally, 1.6.2. Rancher server will always pick the correct Rancher agent version for you, so you don't need to worry about trying to find the right agent version. 

Can you do a `sudo docker version` to see what your version is?

Also, what kind of box are you running on?

**Comment by NigelThorne** [comment] 2015-06-12 07:38
Oops. Sorry didn't understand. I've upgraded to 1.6.2, but I still have problems.

```
sudo docker version
Client version: 1.6.2
Client API version: 1.18
Go version (client): go1.4.2
Git commit (client): 7c8fca2
OS/Arch (client): linux/amd64
Server version: 1.6.2
Server API version: 1.18
Go version (server): go1.4.2
Git commit (server): 7c8fca2
OS/Arch (server): linux/amd64
```

After starting an agent I get this:
```
docker logs d937b9815864f742b250dee3bcd6cee8427a54ab87fd1e462f3c77c16bc63f6a

INFO: Running Agent Registration Process, CATTLE_URL=http://10.10.240.245:8080/v1
INFO: Checking for Docker version >= 1.6.0
INFO: Found Server version: 1.6.2
INFO: docker version: Client version: 1.6.0
INFO: docker version: Client API version: 1.18
INFO: docker version: Go version (client): go1.4.2
INFO: docker version: Git commit (client): 4749651
INFO: docker version: OS/Arch (client): linux/amd64
INFO: docker version: Server version: 1.6.2
INFO: docker version: Server API version: 1.18
INFO: docker version: Go version (server): go1.4.2
INFO: docker version: Git commit (server): 7c8fca2
INFO: docker version: OS/Arch (server): linux/amd64
INFO: docker info: Containers: 158
INFO: docker info: Images: 119
INFO: docker info: Storage Driver: aufs
INFO: docker info: Root Dir: /var/lib/docker/aufs
INFO: docker info: Backing Filesystem: extfs
INFO: docker info: Dirs: 440
INFO: docker info: Dirperm1 Supported: false
INFO: docker info: Execution Driver: native-0.2
INFO: docker info: Kernel Version: 3.13.0-24-generic
INFO: docker info: Operating System: Ubuntu 14.04.2 LTS
INFO: docker info: CPUs: 1
INFO: docker info: Total Memory: 994.1 MiB
INFO: docker info: Name: octohost
INFO: docker info: ID: 3XYN:XBMI:2QUK:Y22A:TSII:FIOH:B66V:53M5:WBT6:WMYO:WJYI:NINF
WARNING: No swap limit support
INFO: Attempting to connect to: http://10.10.240.245:8080/v1
INFO: http://10.10.240.245:8080/v1 is accessible
INFO: Inspecting host capabilities
INFO: System: false
INFO: Host writable: true
INFO: Token: xxxxxxxx
INFO: Running registration
Traceback (most recent call last):
  File "./register.py", line 11, in <module>
    secret_key=os.environ['CATTLE_REGISTRATION_SECRET_KEY'])
  File "/usr/local/lib/python2.7/dist-packages/cattle.py", line 34, in from_env
    return gdapi.from_env(prefix=prefix, factory=Client, **kw)
  File "/usr/local/lib/python2.7/dist-packages/gdapi.py", line 604, in from_env
    return _from_env(prefix=prefix, factory=factory, **args)
  File "/usr/local/lib/python2.7/dist-packages/gdapi.py", line 623, in _from_env
    return factory(**result)
  File "/usr/local/lib/python2.7/dist-packages/cattle.py", line 12, in __init__
    super(Client, self).__init__(*args, **kw)
  File "/usr/local/lib/python2.7/dist-packages/gdapi.py", line 195, in __init__
    self._load_schemas()
  File "/usr/local/lib/python2.7/dist-packages/gdapi.py", line 309, in _load_schemas
    response = self._get_response(self._url)
  File "/usr/local/lib/python2.7/dist-packages/gdapi.py", line 258, in _get_response
    headers=self._headers)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 477, in get
    return self.request('GET', url, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 465, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 573, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/adapters.py", line 415, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', gaierror(-2, 'Name or service not known'))
```


Thanks

**Comment by cloudnautique** [comment] 2015-06-12 23:54
When you go to start the agent, what is the registration command that you start with? I would recommend starting with rancher/agent:v0.7.9 instead of rancher/agent:latest if you are not already.

**Comment by NigelThorne** [comment] 2015-06-15 03:43
```
vagrant@octohost:~$ sudo docker run -d --privileged -v /var/run/docker.sock:/var/run/docker.sock rancher/agent:v0.7.9 http://octohost:8080/v1/scripts/E68B61B3BD25FF2439CB:1434326400000:Af5z4GqBd5xYaKW5kOA1BObdYqY
docker 27059dcb2c509a8237d3c5740a3b1ffeba98c84e695a548e0ed3cb2af1f58efb
vagrant@octohost:~$ docker ps
CONTAINER ID        IMAGE                      COMMAND                CREATED             STATUS              PORTS                              NAMES
27059dcb2c50        rancher/agent:v0.7.9       "/run.sh http://octo   2 seconds ago       Up 1 seconds                                           prickly_mcclintock
32e158815db7        rancher/server:latest      "/usr/bin/s6-svscan    4 days ago          Up 2 days           3306/tcp, 0.0.0.0:8080->8080/tcp   romantic_hodgkin
26e1bea3a07a        octohost/docgraph:latest   "/usr/local/bin/fore   2 weeks ago         Up 2 days           0.0.0.0:32768->4000/tcp            agitated_lovelace

vagrant@octohost:~$ docker logs 2705
INFO: Running Agent Registration Process, CATTLE_URL=http://octohost:8080/v1
INFO: Checking for Docker version >= 1.6.0
INFO: Found Server version: 1.6.2
INFO: docker version: Client version: 1.6.0
INFO: docker version: Client API version: 1.18
INFO: docker version: Go version (client): go1.4.2
INFO: docker version: Git commit (client): 4749651
INFO: docker version: OS/Arch (client): linux/amd64
INFO: docker version: Server version: 1.6.2
INFO: docker version: Server API version: 1.18
INFO: docker version: Go version (server): go1.4.2
INFO: docker version: Git commit (server): 7c8fca2
INFO: docker version: OS/Arch (server): linux/amd64
INFO: docker info: Containers: 159
INFO: docker info: Images: 119
INFO: docker info: Storage Driver: aufs
INFO: docker info: Root Dir: /var/lib/docker/aufs
INFO: docker info: Backing Filesystem: extfs
INFO: docker info: Dirs: 442
INFO: docker info: Dirperm1 Supported: false
INFO: docker info: Execution Driver: native-0.2
INFO: docker info: Kernel Version: 3.13.0-24-generic
INFO: docker info: Operating System: Ubuntu 14.04.2 LTS
INFO: docker info: CPUs: 1
INFO: docker info: Total Memory: 994.1 MiB
INFO: docker info: Name: octohost
INFO: docker info: ID: 3XYN:XBMI:2QUK:Y22A:TSII:FIOH:B66V:53M5:WBT6:WMYO:WJYI:NINF
WARNING: No swap limit support
INFO: Attempting to connect to: http://octohost:8080/v1
ERROR: http://octohost:8080/v1 is not accessible
ERROR: http://octohost:8080/v1 is not accessible
ERROR: http://octohost:8080/v1 is not accessible
```

ok so octohost isn't resolving?   I'll try the IPAddress..
```
vagrant@octohost:~$ sudo docker run -d --privileged -v /var/run/docker.sock:/var/run/docker.sock rancher/agent:v0.7.9 http://octohost.leicabio.com:8080/v1/scripts/E68B61B3BD25FF2439CB:1434326400000:Af5z4GqBd5xYaKW5kOA1BObdYqY
0bddba9763838f80d39f054bb2bb3d6a6c6c34f26dcca08eb7702b794aba9670
vagrant@octohost:~$ docker logs 0bddba9763838f80d39f054bb2bb3d6a6c6c34f26dcca08eb7702b794aba9670

INFO: Running Agent Registration Process, CATTLE_URL=http://octohost.leicabio.com:8080/v1
INFO: Checking for Docker version >= 1.6.0
INFO: Found Server version: 1.6.2
INFO: docker version: Client version: 1.6.0
INFO: docker version: Client API version: 1.18
INFO: docker version: Go version (client): go1.4.2
INFO: docker version: Git commit (client): 4749651
INFO: docker version: OS/Arch (client): linux/amd64
INFO: docker version: Server version: 1.6.2
INFO: docker version: Server API version: 1.18
INFO: docker version: Go version (server): go1.4.2
INFO: docker version: Git commit (server): 7c8fca2
INFO: docker version: OS/Arch (server): linux/amd64
INFO: docker info: Containers: 162
INFO: docker info: Images: 119
INFO: docker info: Storage Driver: aufs
INFO: docker info: Root Dir: /var/lib/docker/aufs
INFO: docker info: Backing Filesystem: extfs
INFO: docker info: Dirs: 448
INFO: docker info: Dirperm1 Supported: false
INFO: docker info: Execution Driver: native-0.2
INFO: docker info: Kernel Version: 3.13.0-24-generic
INFO: docker info: Operating System: Ubuntu 14.04.2 LTS
INFO: docker info: CPUs: 1
INFO: docker info: Total Memory: 994.1 MiB
INFO: docker info: Name: octohost
INFO: docker info: ID: 3XYN:XBMI:2QUK:Y22A:TSII:FIOH:B66V:53M5:WBT6:WMYO:WJYI:NINF
WARNING: No swap limit support
INFO: Attempting to connect to: http://octohost.leicabio.com:8080/v1
INFO: http://octohost.leicabio.com:8080/v1 is accessible
INFO: Inspecting host capabilities
INFO: System: false
INFO: Host writable: true
INFO: Token: xxxxxxxx
INFO: Running registration
Traceback (most recent call last):
  File "./register.py", line 11, in <module>
    secret_key=os.environ['CATTLE_REGISTRATION_SECRET_KEY'])
  File "/usr/local/lib/python2.7/dist-packages/cattle.py", line 34, in from_env
    return gdapi.from_env(prefix=prefix, factory=Client, **kw)
  File "/usr/local/lib/python2.7/dist-packages/gdapi.py", line 604, in from_env
    return _from_env(prefix=prefix, factory=factory, **args)
  File "/usr/local/lib/python2.7/dist-packages/gdapi.py", line 623, in _from_env
    return factory(**result)
  File "/usr/local/lib/python2.7/dist-packages/cattle.py", line 12, in __init__
    super(Client, self).__init__(*args, **kw)
  File "/usr/local/lib/python2.7/dist-packages/gdapi.py", line 195, in __init__
    self._load_schemas()
  File "/usr/local/lib/python2.7/dist-packages/gdapi.py", line 309, in _load_schemas
    response = self._get_response(self._url)
  File "/usr/local/lib/python2.7/dist-packages/gdapi.py", line 258, in _get_response
    headers=self._headers)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 477, in get
    return self.request('GET', url, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 465, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 573, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/adapters.py", line 415, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', gaierror(-2, 'Name or service not known'))
```

**Comment by cloudnautique** [comment] 2015-06-15 05:51
It looks like the second attempt is the FQDN, not the IP?

**Comment by NigelThorne** [comment] 2015-06-16 07:08
true. I tried the IP with the same results. Cut and pasted the wrong example.
```
docker run -d --privileged -v /var/run/docker.sock:/var/run/docker.sock rancher/agent:v0.7.9 http://10.10.240.245:8080/v1/scripts/E68B61B3BD25FF2439CB:1434326400000:Af5z4GqBd5xYaKW5kOA1BObdYqY
5c0e99fe6a9c8e0eaeedf64f42ac2edd2f1d1763e43d5e13997d05adbced8684
vagrant@octohost:~$ docker logs 5c0e99fe6a9c8e0eaeedf64f42ac2edd2f1d1763e43d5e13997d05adbced8684

INFO: Running Agent Registration Process, CATTLE_URL=http://10.10.240.245:8080/v1
INFO: Checking for Docker version >= 1.6.0
INFO: Found Server version: 1.6.2
INFO: docker version: Client version: 1.6.0
INFO: docker version: Client API version: 1.18
INFO: docker version: Go version (client): go1.4.2
INFO: docker version: Git commit (client): 4749651
INFO: docker version: OS/Arch (client): linux/amd64
INFO: docker version: Server version: 1.6.2
INFO: docker version: Server API version: 1.18
INFO: docker version: Go version (server): go1.4.2
INFO: docker version: Git commit (server): 7c8fca2
INFO: docker version: OS/Arch (server): linux/amd64
INFO: docker info: Containers: 165
INFO: docker info: Images: 142
INFO: docker info: Storage Driver: aufs
INFO: docker info: Root Dir: /var/lib/docker/aufs
INFO: docker info: Backing Filesystem: extfs
INFO: docker info: Dirs: 477
INFO: docker info: Dirperm1 Supported: false
INFO: docker info: Execution Driver: native-0.2
INFO: docker info: Kernel Version: 3.13.0-24-generic
INFO: docker info: Operating System: Ubuntu 14.04.2 LTS
INFO: docker info: CPUs: 1
INFO: docker info: Total Memory: 994.1 MiB
INFO: docker info: Name: octohost
INFO: docker info: ID: 3XYN:XBMI:2QUK:Y22A:TSII:FIOH:B66V:53M5:WBT6:WMYO:WJYI:NINF
WARNING: No swap limit support
INFO: Attempting to connect to: http://10.10.240.245:8080/v1
INFO: http://10.10.240.245:8080/v1 is accessible
INFO: Inspecting host capabilities
INFO: System: false
INFO: Host writable: true
INFO: Token: xxxxxxxx
INFO: Running registration
Traceback (most recent call last):
  File "./register.py", line 11, in <module>
    secret_key=os.environ['CATTLE_REGISTRATION_SECRET_KEY'])
  File "/usr/local/lib/python2.7/dist-packages/cattle.py", line 34, in from_env
    return gdapi.from_env(prefix=prefix, factory=Client, **kw)
  File "/usr/local/lib/python2.7/dist-packages/gdapi.py", line 604, in from_env
    return _from_env(prefix=prefix, factory=factory, **args)
  File "/usr/local/lib/python2.7/dist-packages/gdapi.py", line 623, in _from_env
    return factory(**result)
  File "/usr/local/lib/python2.7/dist-packages/cattle.py", line 12, in __init__
    super(Client, self).__init__(*args, **kw)
  File "/usr/local/lib/python2.7/dist-packages/gdapi.py", line 195, in __init__
    self._load_schemas()
  File "/usr/local/lib/python2.7/dist-packages/gdapi.py", line 309, in _load_schemas
    response = self._get_response(self._url)
  File "/usr/local/lib/python2.7/dist-packages/gdapi.py", line 258, in _get_response
    headers=self._headers)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 477, in get
    return self.request('GET', url, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 465, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 573, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/adapters.py", line 415, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', gaierror(-2, 'Name or service not known'))
```

**Comment by NigelThorne** [comment] 2015-06-16 07:29
ok .. I just ran the rancher server with --privileged  and in the UI told it the api address was Other but entered it's own IP with port 8080. 

Then ran the provided command for the agent. 
```
sudo docker run -d --privileged -v /var/run/docker.sock:/var/run/docker.sock rancher/agent:v0.7.9 http://10.10.240.245:8080/v1/scripts/59AB550B342AAE257106:1434438000000:ijfSixl195s9Tj45fLTqRcVQQ
```

It has run through and appeared in the Rancher UI!

The logs for the agent show it downloaded a bunch of stuff...  then ends with 

```
INFO: Downloading http://10.10.240.245:8080/v1//configcontent//host-config current=
INFO: Running /var/lib/cattle/download/host-config/host-config-1-2732cb6a92c67dbaceec71e94551a232c71e4a1a9aab6cf3747e04ee652f1ff0/apply.sh
INFO: HOME -> ./
INFO: HOME -> ./etc/
INFO: HOME -> ./etc/cattle/
INFO: HOME -> ./etc/cattle/api.crt
INFO: Sending host-config applied 1-2732cb6a92c67dbaceec71e94551a232c71e4a1a9aab6cf3747e04ee652f1ff0
time="2015-06-16T07:23:44Z" level="info" msg="Starting event router."
time="2015-06-16T07:23:44Z" level="info" msg="Watching state directory: /var/lib/rancher/state/containers"
time="2015-06-16T07:23:44Z" level="info" msg="Processing event: &docker.APIEvents{Status:\"start\", ID:\"462c756426f6e47c254ff13ff623ffb3b51b86a38da24d8f222b8d74b96acfa9\", From:\"-simulated-\", Time:0}"
time="2015-06-16T07:23:44Z" level="info" msg="Processing event: &docker.APIEvents{Status:\"start\", ID:\"417ebe706300637eb99377c7dd89aee9b2fc58f318a29db07dcdda6255c2e261\", From:\"-simulated-\", Time:0}"
time="2015-06-16T07:23:44Z" level="info" msg="Processing event: &docker.APIEvents{Status:\"start\", ID:\"70eff1e946aa1d0e558d89c85afb747a4285f4171960200dd4c24ead41eed66c\", From:\"-simulated-\", Time:0}"
time="2015-06-16T07:23:44Z" level="info" msg="Processing event: &docker.APIEvents{Status:\"start\", ID:\"26e1bea3a07a9b02c34c48b6cf9dc67eb1f60375f10bc13d837f170ad83b1757\", From:\"-simulated-\", Time:0}"
2015-06-16 07:23:44,351 ERROR cattle [139873997269744] [utils.py:126] Could not get stats from cAdvisor at: http://127.0.0.1:9344/api/v1.2/containers
Traceback (most recent call last):
  File "/var/lib/cattle/pyagent/cattle/utils.py", line 120, in _get
    with closing(urllib2.urlopen(url, timeout=5)) as resp:
  File "/usr/lib/python2.7/urllib2.py", line 127, in urlopen
    return _opener.open(url, data, timeout)
  File "/usr/lib/python2.7/urllib2.py", line 404, in open
    response = self._open(req, data)
  File "/usr/lib/python2.7/urllib2.py", line 422, in _open
    '_open', req)
  File "/usr/lib/python2.7/urllib2.py", line 382, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 1214, in http_open
    return self.do_open(httplib.HTTPConnection, req)
  File "/usr/lib/python2.7/urllib2.py", line 1184, in do_open
    raise URLError(err)
URLError: <urlopen error [Errno 111] ECONNREFUSED>
2015-06-16 07:23:44,377 ERROR cattle [139873997269744] [utils.py:126] Could not get stats from cAdvisor at: http://127.0.0.1:9344/api/v1.2/containers
Traceback (most recent call last):
  File "/var/lib/cattle/pyagent/cattle/utils.py", line 120, in _get
    with closing(urllib2.urlopen(url, timeout=5)) as resp:
  File "/usr/lib/python2.7/urllib2.py", line 127, in urlopen
    return _opener.open(url, data, timeout)
  File "/usr/lib/python2.7/urllib2.py", line 404, in open
    response = self._open(req, data)
  File "/usr/lib/python2.7/urllib2.py", line 422, in _open
    '_open', req)
  File "/usr/lib/python2.7/urllib2.py", line 382, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 1214, in http_open
    return self.do_open(httplib.HTTPConnection, req)
  File "/usr/lib/python2.7/urllib2.py", line 1184, in do_open
    raise URLError(err)
URLError: <urlopen error [Errno 111] ECONNREFUSED>
I0616 17:23:46.565682 18985 storagedriver.go:92] No backend storage selected
I0616 17:23:46.583502 18985 storagedriver.go:94] Caching 60 stats in memory
I0616 17:23:46.584386 18985 manager.go:106] cAdvisor running in container: "/docker/462c756426f6e47c254ff13ff623ffb3b51b86a38da24d8f222b8d74b96acfa9"
I0616 17:23:46.589897 18985 fs.go:87] Filesystem partitions: map[/dev/mapper/vagrant--vg-root:{mountpoint:/ major:252 minor:0} /dev/sda1:{mountpoint:/boot major:8 minor:1}]
I0616 17:23:46.681702 18985 manager.go:127] Machine: {NumCores:1 CpuFrequency:2600000 MemoryCapacity:1042350080 MachineID:486a079fc92f26f75ef852655351fd9e SystemUUID:422334CD-2274-2310-5C5D-FE04347228AF BootID:348be5a4-d9f2-45b0-835e-be1d2e87e7e1 Filesystems:[{Device:/dev/mapper/vagrant--vg-root Capacity:41092214784} {Device:/dev/sda1 Capacity:246755328}] DiskMap:map[252:0:{Name:dm-0 Major:252 Minor:0 Size:41884319744 Scheduler:none} 252:1:{Name:dm-1 Major:252 Minor:1 Size:805306368 Scheduler:none} 2:0:{Name:fd0 Major:2 Minor:0 Size:0 Scheduler:deadline} 8:0:{Name:sda Major:8 Minor:0 Size:42949672960 Scheduler:deadline}] NetworkDevices:[{Name:eth0 MacAddress:00:50:56:a3:c5:53 Speed:10000 Mtu:1500} {Name:eth1 MacAddress:00:50:56:a3:53:0d Speed:10000 Mtu:1500} {Name:lxcbr0 MacAddress:fe:1c:23:39:fa:e8 Speed:0 Mtu:1500}] Topology:[{Id:0 Memory:1042350080 Cores:[{Id:0 Threads:[0] Caches:[{Size:32768 Type:Data Level:1} {Size:32768 Type:Instruction Level:1} {Size:262144 Type:Unified Level:2}]}] Caches:[{Size:20971520 Type:Unified Level:3}]}]}
I0616 17:23:46.688273 18985 manager.go:134] Version: {KernelVersion:3.13.0-24-generic ContainerOsVersion:Ubuntu 14.04.2 LTS DockerVersion:1.6.2 CadvisorVersion:0.12.0}
I0616 17:23:47.016998 18985 factory.go:226] Registering Docker factory
I0616 17:23:47.032855 18985 factory.go:60] Registering Raw factory
I0616 17:23:47.053414 18985 manager.go:872] Started watching for new ooms in manager
I0616 17:23:47.068019 18985 manager.go:212] Starting recovery of all containers
```

after that the following just keeps repeating the following

```
2015-06-16 07:27:57,517 ERROR agent [139873997269744] [event.py:108] d2fc8204-8c7e-4772-a023-56d410f905ee : Unknown error
Traceback (most recent call last):
  File "/var/lib/cattle/pyagent/cattle/agent/event.py", line 91, in _worker_main
    resp = agent.execute(req)
  File "/var/lib/cattle/pyagent/cattle/agent/__init__.py", line 15, in execute
    return self._router.route(req)
  File "/var/lib/cattle/pyagent/cattle/plugins/core/event_router.py", line 13, in route
    resp = handler.execute(req)
  File "/var/lib/cattle/pyagent/cattle/plugins/core/event_handlers.py", line 32, in execute
    type.on_ping(event, resp)
  File "/var/lib/cattle/pyagent/cattle/plugins/docker/compute.py", line 96, in on_ping
    self._add_instances(ping, pong)
  File "/var/lib/cattle/pyagent/cattle/plugins/docker/compute.py", line 111, in _add_instances
    self.add_container('running', container, containers)
  File "/var/lib/cattle/pyagent/cattle/plugins/docker/compute.py", line 122, in add_container
    'uuid': self._get_uuid(container),
  File "/var/lib/cattle/pyagent/cattle/plugins/docker/compute.py", line 156, in _get_uuid
    uuid = container['Labels']['io.rancher.container.uuid']
TypeError: 'NoneType' object has no attribute '__getitem__'
```

**Comment by deniseschannon** [comment] 2015-06-17 17:08
@NigelThorne Can you let me know what OS type you are running? Also, can you confirm your hosts that you're adding can ping wherever Rancher server is connected?

**Comment by NigelThorne** [comment] 2015-06-23 02:04
```
vagrant@octohost:~$ uname --all
Linux octohost 3.13.0-24-generic #47-Ubuntu SMP Fri May 2 23:30:00 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux
vagrant@octohost:~$ docker version
Client version: 1.6.2
Client API version: 1.18
Go version (client): go1.4.2
Git commit (client): 7c8fca2
OS/Arch (client): linux/amd64
Server version: 1.6.2
Server API version: 1.18
Go version (server): go1.4.2
Git commit (server): 7c8fca2
OS/Arch (server): linux/amd64
```

My agent is on the same docker box as the rancher server. Just different docker images. Is there some command I can try to check this for you? 

I've tried this: 
```
vagrant@octohost:~$ docker ps
CONTAINER ID        IMAGE                           COMMAND                CREATED             STATUS              PORTS                                          NAMES
7ce425a90ece        rancher/agent-instance:v0.3.1   "/etc/init.d/agent-i   6 days ago          Up 6 days           0.0.0.0:500->500/udp, 0.0.0.0:4500->4500/udp   058beaf1-5c22-4efc-89b3-0abb036abf83
462c756426f6        rancher/agent:v0.7.9            "/run.sh run"          6 days ago          Up 6 days                                                          rancher-agent
417ebe706300        rancher/server:latest           "/usr/bin/s6-svscan    6 days ago          Up 6 days           3306/tcp, 0.0.0.0:8080->8080/tcp               dreamy_colden
vagrant@octohost:~$ docker exec 462c756426f6 ping 10.10.240.245
PING 10.10.240.245 (10.10.240.245) 56(84) bytes of data.
64 bytes from 10.10.240.245: icmp_seq=1 ttl=64 time=0.066 ms
64 bytes from 10.10.240.245: icmp_seq=2 ttl=64 time=0.057 ms
64 bytes from 10.10.240.245: icmp_seq=3 ttl=64 time=0.056 ms
64 bytes from 10.10.240.245: icmp_seq=4 ttl=64 time=0.072 ms
```

**Comment by Djiit** [comment] 2015-06-30 12:37
I got the same error here on CoreOS Alpha (723.1.0) : 

    TypeError: 'NoneType' object has no attribute '__getitem__'"

**Comment by deniseschannon** [comment] 2015-07-02 16:40
@ibuildthecloud Can you take a look at this issue?

@Djiit what version of Rancher are you running?

**Comment by Djiit** [comment] 2015-07-03 12:25
I pulled the latest image with docker. It's v0.24.0

**Comment by deniseschannon** [comment] 2015-07-03 15:02
@Djiit Could you try pulling latest again? It should be at v0.25.0. We made some networking updates between the releases. I haven't been able to reproduce your issue, but have been running v0.25.0 for awhile.

**Comment by NigelThorne** [comment] 2015-07-06 12:01
I'll give this a go when I get back to work.

**Comment by AKoetsier** [comment] 2015-07-07 19:56
I had the same problem running agent 0.7.9 and server 0.25 and beta (on 7th of juli). After removing an old (stopped) docker container the problem went away. Since your stacktrace reports compute.py line 111 the problems seems to be one of the running containers? It seems the container is a NoneType in some cases. Just my $0.02, have no actual idea why it happens or what the real cause was.

**Comment by deniseschannon** [comment] 2015-07-08 17:49
@Djiit @AKoetsier Can you confirm whether or not you are using the same host for your Rancher server and agent?

**Comment by ibuildthecloud** [comment] 2015-07-08 18:01
There are various odd scenarios where `Labels` can be null on a container.  We need to fix this to not assume there is always a `Labels` field.

**Comment by AKoetsier** [comment] 2015-07-08 19:12
@deniseschannon That is correct, I am using the agent and server on the same host.

**Comment by cjellick** [comment] 2015-07-09 12:53
@deniseschannon My fix for the label assumption is merged. How should we handle the assignment of this issue to QA since it expose other problems unrelated to the label assumption issue?

**Comment by cjellick** [comment] 2015-07-09 13:20
Ah, my mistake, everything else in this issue is resolved but the __getitem__ issue.

**Comment by cjellick** [comment] 2015-07-09 13:22
Steps to reproduce:
1. Create some containers on a docker **1.5** host
2. Upgrade to docker 1.7
3. Start rancher agent on host

**Comment by deniseschannon** [comment] 2015-07-09 13:42
If you are experiencing this issue, the workaround is to remove any old containers that were started with Docker 1.5. Afterwards, you will be able to start rancher agent with no issues.

**Comment by Djiit** [comment] 2015-07-09 14:06
Hi Denise, i'll try that in a few minutes. Thx.

**Comment by Djiit** [comment] 2015-07-14 14:15
@cjellick you were right !

I was able to start rancher after removing old containers.

Thx

**Closed** 2015-07-23 21:58 UTC
Labels: kind/bug, status/resolved, status/to-test
