### ISSUE TITLE
Hit error in local cluster that wont clean up

### ISSUE THREAD

**Issue by cloudnautique** [rancher/rancher#18895] opened 2019-03-14 00:01 UTC
Rancher/rancher:v2.2.0-rc4 HA install docker 18.09

I am hitting this error:
https://github.com/rancher/rancher/blame/9be83e8575da8ba6e19468033d5ade407b578eec/pkg/controllers/user/monitoring/operatorHandler.go#L102

My cluster list shows:
![Screen Shot 2019-03-13 at 5 01 17 PM](https://user-images.githubusercontent.com/1989084/54322245-a7e76b00-45b1-11e9-84f0-169b65cae504.png)

**Comment by cjellick** [comment] 2019-03-14 16:34
Id like this looked at for 2.2.0

**Comment by thxCode** [comment] 2019-03-15 16:05
#### Case 1 (Single Node)
- Set up a new local cluster(2C4G) via `minikube version: v0.35.0` with the following script:
```
minikube start  --alsologtostderr --registry-mirror=https://registry.docker-cn.com  --extra-config=kubelet.authentication-token-webhook=true --extra-config=kubelet.authorization-mode=Webhook --cache-images
```
- Run a new nginx container as the LB in host
- Add a fake DNS(rancher.localhost) resolution to host and VM created by minikube
- Init tiller and install cert-manager
- Install rancher via helm with the following script:
```
helm install rancher-alpha/rancher --version v2.2.0-alpha6 --namespace cattle-system --set rancherImageTag=v2.2.0-rc4 --set hostname=frank.localhost --name rancher
```
- Enable Monitoring -> didn't see any errors
- Disable Monitoring -> didn't see any errors
- Enable Monitoring again -> didn't see any errors

#### Case 2 (Multiple Node)
- Set up a noodpool with 4 Ubuntu 1804 (2C8G) instances in GCP
- Run a new nginx container as the LB in one instance
- Add a DNS(frank.rancher-cn-test.com) A record in AWS Route53
- Create a 3 nodes cluster via `rke`
- Init tiller and install cert-manager
- Install rancher via helm with the following script:
```
helm install rancher-alpha/rancher --version v2.2.0-alpha6 --namespace cattle-system --set rancherImageTag=v2.2.0-rc4 --set hostname=frank.rancher-cn-test.com --name rancher
```
- Enable Monitoring -> didn't see any errors
- Disable Monitoring -> didn't see any errors
- Enable Monitoring again -> didn't see any errors

@cloudnautique Am I missing something? Could you detail me more?
cc @loganhz  @cjellick

**Comment by thxCode** [comment] 2019-03-17 01:26
For the regression testing, I think we only need to check as the below:
- enable cluster/project monitoring, the operator will be installed
- disable all monitoring, the operator will be uninstalled

**Comment by sangeethah** [comment] 2019-03-17 06:26
@thxCode @cloudnautique As part of validating this issue we will cover the suggested regression tests.
Are there known steps to reproduce the error reported in this issue ?

**Comment by thxCode** [comment] 2019-03-17 07:05
@jiaqiluo 

- To verify the issue has been fixed or not, I think you can follow the HA doc, create a HA RKE cluster and install the Rancher HA via helm, that is enough. Am I missing anything? @cloudnautique
- For regression testing, https://github.com/rancher/rancher/issues/18895#issuecomment-473606934, including:
  1. Enable cluster Monitoring, check Operator is up or not. Disable cluster Monitoring, Operator is down or not.
  2. Same steps follow 1 for project Monitoring
  3. Enable cluster Monitoring, enable project Monitoring, diable cluster Monitoring, Operator is still up.
  4. Enable project Monitoring, enable cluster Monitoring, disable project Monitoring, Operator is still up.

**Comment by sangeethah** [comment] 2019-03-17 16:03
@thxCode @cloudnautique 
To verify the issue has been fixed or not, I think you can follow the HA doc, create a HA RKE cluster and install the Rancher HA via helm, that is enough. Am I missing anything? @cloudnautique

This is how we always do our HA installs. But have not encountered this issue when enabling monitoring.

**Comment by thxCode** [comment] 2019-03-18 02:17
@sangeethah , this issue is more subtle. When rancher installs the agent into local cluster, rancher will no longer connect to local cluster directly, but use the connection between rancher and agent. The opportunity to switch this causes an error. Although the reconciling could fix the error(change the `State` of Condition `PrometheusOperatorDeployed` to `False`), but it doesn't clean up the error message(the `Message` and `Reason` of Condition `PrometheusOperatorDeployed`).

In fact, I have tried as https://github.com/rancher/rancher/issues/18895#issuecomment-473345087, but also could not reproduce, but it was still there, so we should fix it.

**Comment by jiaqiluo** [comment] 2019-03-19 17:17
Setup: Rancher: master 3/18, HA mode
Here are the regression tests applied on RKE cluster (DO cluster, 1 etcd, 1 control plane, 2 workers):
- Enable cluster Monitoring, enable project Monitoring, disable cluster Monitoring, Operator is still up; disable project Monitoring, Operator is down. 
- Enable project Monitoring, enable cluster Monitoring, disable project Monitoring, Operator is still up; disable cluster Monitoring, Operator is down. 
- Enable cluster Monitoring, Operator is up; disable cluster Monitoring, Operator is down. 
- Enable project Monitoring, Operator is up; disable project Monitoring, Operator is down.

**Comment by cjellick** [comment] 2019-03-19 18:23
Regression steps are sufficient. closing

**Closed by cjellick** 2019-03-19 18:23 UTC
Labels: area/monitoring, kind/bug-qa, status/ready-for-review, status/resolved, status/to-test, status/working, team/cn, version/2.0
