### ISSUE TITLE
Cannot select k8s version when editing cluster after upgrading from 2.1.6 to 2.2

### ISSUE THREAD

**Issue by Maxwell1987** [rancher/rancher#19201] opened 2019-03-27 06:14 UTC
**What kind of request is this (question/bug/enhancement/feature request):**
BUG

**Steps to reproduce (least amount of steps as possible):**
1. Edit cluster
2. Click "Kubernetes Version" dropdown list

**Result:**
The dropdown list is empty

**Other details that may be helpful:**
Tested in firefox and safari

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI):
2.2
- Installation option (single install/HA):
single

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported):
Custom

- Machine type (cloud/VM/metal) and specifications (CPU/memory):
kingsoft cloud

- Kubernetes version (use `kubectl version`):
1.12.4

- Docker version (use `docker version`):
18.09.3

**Comment by superseb** [comment] 2019-03-27 08:38
Please specify the upgrade path with exact versions from Rancher, and if possible, the upgrade path of the exact versions the cluster.

**Comment by loganhz** [comment] 2019-03-30 00:27
@Maxwell1987 Can you post the value in API `/v3/settings/k8s-version-to-images`

I guess you tried to upgrade to a RC version? We cannot reproduce this issue

**Comment by loganhz** [comment] 2019-04-01 00:18
![image](https://user-images.githubusercontent.com/21168270/55297210-82ce7580-5456-11e9-971e-8058edb2d9bf.png)

@pengjiang80 reproduced this issue in a setup upgraded from RC release.

The schema of rancherKubernetesEngineConfig is broken. A lot of fields are missing in the setup

**Comment by loganhz** [comment] 2019-04-01 01:34
@orangedeng confirmed it only happens if rancher upgraded from a RC version.

**Comment by orangedeng** [comment] 2019-04-01 08:00
@loganhz @cjellick Can we move it out of v2.2.2, I don't think we should support upgrade rancher from a RC version to a formal version.

The root cause is that, we have a `rancherKubernetesEngineConfig` dynamic schema in early RC build and we won't have it any more in 2.2.0.

**Comment by Maxwell1987** [comment] 2019-04-01 09:07
@loganhz It’s true that I have upgraded to the RC4 version before, then I returned to the release version, and then upgraded to 2.1.6. How to fix the problem of `rancherKubernetesEngineConfig` schema?

**Comment by sowmyav27** [comment] 2019-04-01 17:17
Tried to reproduce on an upgrade from `v2.1.6` to `v2.2.0`.
Steps taken:
1. On rancher v2.1.6 created a cluster with 3 nodes(all roles) type - hosted-Amazon EC2.
2. Upgraded to `rancher:v2.2.0`.

No error observed. The cluster was in `Unavailable` state and transitioned into `Active` state in few seconds.

**Comment by alena1108** [comment] 2019-04-01 17:26
@Maxwell1987 upgrading between RCs is not something Rancher supports. There are multiple things that could go wrong. 

>  then I returned to the release version

Did you rollback to the previously taken etcd snapshot too? Thats the recommended upgrade procedure. If you restore to the etcd of the officially supported rancher version, then the upgrade to 2.2 should work.

Closing as a duplicate of:
https://github.com/rancher/rancher/issues/18120

**Closed by alena1108** 2019-04-01 17:26 UTC
Labels: kind/bug, priority/2, status/to-reproduce, team/cn, version/2.0
