### ISSUE TITLE
Rancher on k3s logging [ERROR] Error certs=InvalidBodyContent 422: failed to parse key: key must be PEM encoded PKCS1 or PKCS8: x509: failed to parse private key (use ParseECPrivateKey instead for this key format) parsing cert k3s-serving. Will not display correctly in UI

### ISSUE THREAD

**Issue by dnoland1** [rancher/rancher#25791] opened 2020-03-05 06:50 UTC
**What kind of request is this (question/bug/enhancement/feature request):**
bug

**Steps to reproduce (least amount of steps as possible):**
Install 2 node k3s cluster:
```
INSTALL_K3S_SKIP_DOWNLOAD=true INSTALL_K3S_EXEC="--cluster-cidr 172.16.0.0/16 --service-cidr 192.168.0.0/16 --cluster-dns 192.168.0.10 --flannel-backend=ipsec" K3S_DATASTORE_ENDPOINT="mysql://${username}:${password}@tcp(${endpoint}:3306)/${dbname}" INSTALL_K3S_EXEC="--no-deploy traefik" k3s.sh
```

Deploy rancher helm chart on cluster
```
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: rancher
  namespace: kube-system
spec:
  chart: rancher
  repo: https://releases.rancher.com/server-charts/latest
  version: "v2.3.5"
  targetNamespace: cattle-system
  set:
    hostname: "%HOSTNAME%"
    tls: external
    antiAffinity: required
    replicas: 2
```
**Result:**
Seeing
```
> kubectl logs -n cattle-system rancher-86846968db-c6smj | grep InvalidBodyContent
2020/03/05 06:14:00 [ERROR] Error certs=InvalidBodyContent 422: failed to parse key: key must be PEM encoded PKCS1 or PKCS8: x509: failed to parse private key (use ParseECPrivateKey instead for this key format) parsing cert k3s-serving. Will not display correctly in UI
> kubectl logs -n cattle-system rancher-86846968db-nvbxz | grep InvalidBodyContent
2020/03/05 06:14:00 [ERROR] Error certs=InvalidBodyContent 422: failed to parse key: key must be PEM encoded PKCS1 or PKCS8: x509: failed to parse private key (use ParseECPrivateKey instead for this key format) parsing cert k3s-serving. Will not display correctly in UI
2020/03/05 06:14:00 [ERROR] Error certs=InvalidBodyContent 422: failed to parse key: key must be PEM encoded PKCS1 or PKCS8: x509: failed to parse private key (use ParseECPrivateKey instead for this key format) parsing cert k3s-serving. Will not display correctly in UI
2020/03/05 06:14:00 [ERROR] Error certs=InvalidBodyContent 422: failed to parse key: key must be PEM encoded PKCS1 or PKCS8: x509: failed to parse private key (use ParseECPrivateKey instead for this key format) parsing cert k3s-serving. Will not display correctly in UI
2020/03/05 06:14:00 [ERROR] Error certs=InvalidBodyContent 422: failed to parse key: key must be PEM encoded PKCS1 or PKCS8: x509: failed to parse private key (use ParseECPrivateKey instead for this key format) parsing cert k3s-serving. Will not display correctly in UI
2020/03/05 06:14:00 [ERROR] Error certs=InvalidBodyContent 422: failed to parse key: key must be PEM encoded PKCS1 or PKCS8: x509: failed to parse private key (use ParseECPrivateKey instead for this key format) parsing cert k3s-serving. Will not display correctly in UI
2020/03/05 06:14:00 [ERROR] Error certs=InvalidBodyContent 422: failed to parse key: key must be PEM encoded PKCS1 or PKCS8: x509: failed to parse private key (use ParseECPrivateKey instead for this key format) parsing cert k3s-serving. Will not display correctly in UI
```

**Other details that may be helpful:**
No noticeable impact or issues with Rancher.

See also https://github.com/rancher/rancher/issues/25236

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI):
v2.3.5
- Installation option (single install/HA):
HA/k3s

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported):
k3s
- Machine type (cloud/VM/metal) and specifications (CPU/memory):
m5.large on AWS
- Kubernetes version (use `kubectl version`):

```
1.17.3
```

- Docker version (use `docker version`):
NA, using containerd

**Comment by superseb** [comment] 2020-03-05 13:52
Duplicate of https://github.com/rancher/rancher/issues/24423

**Closed by superseb** 2020-03-05 13:52 UTC
