### ISSUE TITLE
Allow user to specify that a node will never be healthy in the UI.

### ISSUE THREAD

**Issue by cloudnautique** [rancher/rancher#23394] opened 2019-10-11 22:57 UTC
Some solutions create a node that is a "dummy" node that will never have kubelet or actually exist. In Rancher 2.2.8 this node would not show up in the UI. In Rancher 2.3 this node does show appear in the UI.

Since the node will never show up as healthy, or finish registering. the Rancher UI show the node as unhealthy and Red. In this situation the user will no longer be able to use the UI for noticing when something is actually broken.

As a user, I should be able to have Rancher ignore a particular node through a label.

Something like:
`cattle.rancher.io/node-status: ignore`

**Comment by cloudnautique** [comment] 2019-10-16 21:36
When the ignore label is applied to the node:
1. Rancher will show the node greyed out in UI as "Ignored".
 - there can be an action on the node object that can apply/remove the label
1. Rancher will not use this as overall node health calculation on the node dashboard.
1. This will not impact the way Rancher returns the node object through the API.
1. This will not impact kubernetes scheduling.

**Comment by alena1108** [comment] 2019-10-25 23:36
After talking offline with @cloudnautique, we are going to take the following approach:

* Don't register node created using kubectl, if it has a certain name or label. The result will be consistent with 2.2.x behavior that was reset in 2.3.x with https://github.com/rancher/rancher/pull/20375/files#diff-9ed547abad12a5cd862ad5e02f9e08b3L311 fix.
* Node name to skip will be defined in settings, and that's what we'd expect users to leverage if they want this functionality. 
* In addition to that, we'll expose similar behavior, only through specific label. If kubectl created node has `cattle.rancher.io/node-status: ignore` label, it will never be synced back by nodessyncer.

**Comment by sangeethah** [comment] 2019-11-08 01:28
Test cases to validate:

`v3/settings/ignore-node-name` related cases:

1. Set `v3/settings/ignore-node-name` to some nodename say  "deletenode".
2. Create  a new cluster.
3. Add a new node using kubectl with nodename - "deletenode". This node should not show up in ui in node list page.
4. Add a new node using kubectl with nodename - "node1". This node should  show up in ui in node list page and it will be in "Unavailable" state.
5. Add a node to a custom cluster using register command having node name override set to "deletenode" .  Should this get hidden from the UI ?
6. Set `v3/settings/ignore-node-name` to "node1". This will NOT result in "node1" (added in step4) to get removed from UI. This should NOT result in  "deletenode" ( added in step3) to show up in UI . It will continue to be hidden.

`cattle.rancher.io/node-status: ignore` label related cases:

1. Create  a new cluster.
2. Add a new node using kubectl with ignore label. This node should not show up in ui in node list page.
4. To an existing good node , add ignore label. This will NOT result in the node being removed from the UI.
5. Add a node to a custom cluster using register command with ignore label.  Should this get hidden from the UI ?

**Comment by sangeethah** [comment] 2019-11-08 23:55
Tested with latest `v2.3-head` - `716c87d1f`

`v3/settings/ignore-node-name` related cases:

1. Set v3/settings/ignore-node-name to some nodename say "deletenode".
2. Create a new cluster.
3. Add a new node using kubectl with nodename - "deletenode". This node does not show up in ui in node list page.
4. Add a new node using kubectl with nodename - "node1". This node shows up in ui in node list page and it will be in "Unavailable" state.
5. Add a node to a custom cluster using register command having node name override set to "deletenode" . This node will get registered successfully even though its node name matches the "ignore-node-name" settings.
6. Set `v3/settings/ignore-node-name` to "node1". This will NOT result in "node1" (added in step4) to get removed from UI. This should NOT result in "deletenode" ( added in step3) to show up in UI . It continues to be hidden.

`cattle.rancher.io/node-status: ignore` label related cases:

1. Create a new cluster.
2. Add a new node using kubectl with ignore label. This node does not show up in ui in node list page.
3. To an existing good node , add ignore label. This will NOT result in the node being removed from the UI.
4. Add a node to a custom cluster using register command with ignore label. This node will show up in the UI even though the ignore label is set.

**Comment by sangeethah** [comment] 2019-11-11 16:35
@cloudnautique Can you confirm the behavior noted with this fix is as expected?

**Comment by sangeethah** [comment] 2019-11-11 20:29
Reopening this issue to discuss on how upgrade cases needs to be handled.

Tried the following use case:


Create a bipIp node from kubectl.
Wait for it to get synced to rancher and get to "Unavailable" state.
Using kubectl , add label - `cattle.rancher.io/node-status: ignore`. ( Did this step from kubectl , since the label change done from rancher UI did not take effect)
Label gets synced to v3/nodes.
Delete the node from rancher server using api ip. ( Attempted from api ui since UI does not have delete option)
Node gets deleted from rancher side as well as from kubectl.

Expected Behavior:
Node gets deleted from rancher side .
But node continues to be part of the cluster and can be listed  from kubectl.

**Comment by alena1108** [comment] 2019-11-12 18:00
@sangeethah after applying the fix, node removal in the user cluster will be skipped if the nodeName is white(black) listed in settings

**Comment by sangeethah** [comment] 2019-11-15 00:30
Tested with latest build from `v2.3-head` - 

Create a bipIp node from kubectl.
Wait for it to get synced to rancher and get to "Unavailable" state.
Set `v3/settings/ignore-node-name1 to "bigip"
Delete the node from rancher server using api ip. ( Attempted from api ui since UI does not have delete option)
Node gets deleted from rancher side.
Node continues to be part of the cluster and can be listed from kubectl as expected.

**Comment by sangeethah** [comment] 2019-11-15 04:02
Reopening this issue to get confirmation on the behavior that we currently see when nodes are getting ignored:

Set `v3/settings/ignore-node-name1 to "bigip"
Create a bipIp node from kubectl.
This node does not get synced to rancher v3/nodes and we donot see it the node list.

But `cattle-node-agent` and `canal` daemonsets try to scale up to 2  and are stuck in "updating" state. 

<img width="1214" alt="Screen Shot 2019-11-14 at 6 55 46 PM" src="https://user-images.githubusercontent.com/4266958/68915941-d3aa8a00-0718-11ea-9741-c11f0387a53b.png">


Wanted to confirm if this behavior we are seeing is something we want to address as part of this fix ?

**Comment by sangeethah** [comment] 2019-11-15 04:08
Note : In the case of upgrade scenario , the same behavior is noted that prevents the agent from being updated .

<img width="1272" alt="Screen Shot 2019-11-14 at 8 04 00 PM" src="https://user-images.githubusercontent.com/4266958/68916271-07d27a80-071a-11ea-9380-17467570fa08.png">

The scenario attempted is:
Deploy Rancher server 2.3.2 with a custom cluster.
Create a bipIp node from kubectl.
Wait for it to get synced to rancher and get to "Unavailable" state.
Notice that `cattle-node-agent` and `canal` daemonsets try to scale up to 2 and are stuck in "updating".
Upgrade to `v2.3-head`
Set `v3/settings/ignore-node-name1 to "bigip"
Delete the node from rancher server using api ip. ( Attempted from api ui since UI does not have delete option)
Node gets deleted from rancher side.
Node continues to be part of the cluster and can be listed from kubectl as expected.

But `cattle-node-agent` and `canal` daemonsets continue to be "updating" state . This prevents the node-agents on the healthy nodes to get upgraded.

**Comment by cloudnautique** [comment] 2019-11-15 04:16
Deploying workloads is out of scope for this issue. There is a workaround if needed by the user, where all nodes can be labeled.

**Comment by deniseschannon** [comment] 2019-11-15 19:06
@sangeethah based on @cloudnautique response can you create a separate bug for this issue and we can close out this original ticket.

**Comment by sangeethah** [comment] 2019-11-20 15:32
Constant attempts to start system containers on ignored nodes tracked in https://github.com/rancher/rancher/issues/24172

**Closed by sangeethah** 2019-11-20 15:32 UTC
Labels: [zube]: To Triage, internal, kind/enhancement, team/ca
