### ISSUE TITLE
[CatalogV2] rancher-logging helm chart - Splunk certificate issue

### ISSUE THREAD

**Issue by zaggash** [rancher/rancher#31810] opened 2021-03-26 17:52 UTC
#### Using both secret definition explained in the [BanzaiCloud upstream doc](https://banzaicloud.com/docs/one-eye/logging-operator/configuration/plugins/outputs/secret/)  

```
ca_file:
 valueFrom:
    secretKeyRef:
      name: <kubernetes-secret-name>
      key: <kubernetes-secret-key>
```  

Check the config in the `rancher-logging-fluentd` pod at `/fluentd/app_config/fluentd.conf`  

Currently, the `secret` is pasted in the config file as a _raw PEM_ and not as a _file location_.  
```
@id clusterflow:cattle-logging-system:splunk-hec-prd-all:clusteroutput:cattle-logging-system:splunk-hec-prd-output 
 ca_file -----BEGIN CERTIFICATE----- 
<redacted PEM> 
 -----END CERTIFICATE-----
```
Looking at the documentation from the [fluentd Splunk plugin documentation](https://github.com/fluent/fluent-plugin-splunk/blob/master/README.hec.md#ca_file)  it should be a file location.
A path to the cert and not the raw cert content pasted into the config file.

The other secret definition like below is not working either,  the content of `mountFrom` is deleted.
```
mountFrom:
    name: <kubernetes-secret-name>
    key: <kubernetes-secret-key>
```

#### Environment
Rancher version 2.5.6
rancher-logging Helm Chart version 3.9.000

gz#16014
gz#15792
gz#16219

**Comment by zaggash** [comment] 2021-03-26 17:53
The same apply for the Elasticsearch CA definition.
gz#16014

**Comment by bbenduduh** [comment] 2021-04-08 08:11
When using TLS, same dysfunctional behavior observed for Kafka and Syslog Outputs !

**Comment by dbason** [comment] 2021-07-13 23:00
The syntax for using `mountFrom` should be:
```yaml
ca_file:
 mountFrom:
    secretKeyRef:
      name: <kubernetes-secret-name>
      key: <kubernetes-secret-key>
```

If the secret has been added in the UI, you should be able to modify the yaml for the installed app and change `valueFrom` to `mountFrom`.  Currently the UI is just adding the secret as a standard secretKeyRef

**Comment by gaktive** [comment] 2021-09-22 22:55
@Jono-SUSE-Rancher just checking, is this ready for UI to work on for 2.5.10? If so, I can move it into Cody's queue.

**Comment by Jono-SUSE-Rancher** [comment] 2021-09-22 22:56
That seems like a good question for @SheilaghM - it looks like this is an internal issue that is in the RT - Sprint Ready column. Where did you see that it requires UI work?

**Comment by annablender** [comment] 2021-11-23 22:47
This is a bug in bonzai upstream. @bashofmann's PR for a UI workaround has already been merged and will be available in 2.6.3 and 2.5.12. Updated all associated tickets.

**Comment by rak-phillip** [comment] 2022-01-04 19:35
@ronhorton here's some of the background that you requested

### Root Cause

There are some logging providers that can’t inject secret into their configuration because they require a file to read from. `mountFrom` is used to generate the file in these cases

### What was fixed or what changes have occurred

`mountFrom` was added as a `mountKey` for logging providers in question. This change can be observed in the generated `yaml` (`mountFrom` will be used in place of `valueFrom` for providers in question). 

### Areas or cases that should be tested

The following Rancher Logging Providers are affected:

* Elastic Search
* Forward
* Kafka
* Loki
* SplunkHec
* Syslog

### What areas could experience regressions?

Rancher Logging for the providers detailed above.

### Are the repro steps accurate/minimal?

1. Install Logging via Explore Cluster => Cluster Tools => Logging => Install
2. Create a cluster output for the logging providers via Logging => ClusterOutputs => Create (Splunk will be used for this example)
3. Make selections for Connection File/Path/Cert/Key, Edit as YAML, and confirm that `mountFrom` prop is used for selection instead of `valueFrom`
4. Verify that logs work as expected for logging provider

**Comment by ronhorton** [comment] 2022-01-04 20:01
As of `2.5-head Commit ID 07a745a`

1. installed logging v2
2. created a cluster output for splunk
3. made selections for file/path/cert/key
4. edit as yaml

I see the `valueFrom` populated and `mountFrom` commented. Click `Save`, and valueFrom is populated. 
<img width="509" alt="Screen Shot 2022-01-04 at 3 00 58 PM" src="https://user-images.githubusercontent.com/89212856/148116745-ee021a93-418a-4922-ae33-6147ad09d615.png">

**Comment by annablender** [comment] 2022-01-04 22:23
@ronhorton I did the dev-validate on this issue. I tested the mountFrom key, according to the bonzai logging docs, in a clusteroutput config for splunk. My steps were as follows:

1. Run Rancher in docker
2. Create an RKE1 DO 3 node downstream cluster
3. Create a secret key for splunk in Rancher
4. Create a cluster output and cluster flow; use the `mountFrom` field instead of `valueFrom` so Rancher will mount the splunk token as a file in the fluentd logging pod
5. Create a 4th DO node
6. Follow the instructions in [Logging Providers](https://confluence.suse.com/pages/viewpage.action?spaceKey=EN&title=Logging+Providers) to install Splunk on that node, access the web hook, create a test index and view logging output
7. If the UI workaround is successful, Rancher will successful be able to authenticate with splunk using the token mounted using the `mountFrom` field. Logs will show up in splunk.

**Comment by ronhorton** [comment] 2022-01-04 22:33
**PASS** Verified in `2.5-head Commit ID 07a745a`

1. installed logging v2
2. setup a cluster output for splunk
3. click on `edit as Yaml`

`mountFrom is now populated, whereas before it was valueFrom`
<img width="534" alt="Screen Shot 2022-01-04 at 5 29 09 PM" src="https://user-images.githubusercontent.com/89212856/148133014-1044805a-2e64-417f-aeb3-91b513fb4b4d.png">

**Closed** 2022-01-04 22:33 UTC
Labels: kind/bug, internal, area/logging, [zube]: QA Working, area/ui, team/area3

**Comment by annablender** [comment] 2022-01-04 22:36
Looks good to me! Thank you guys
