### ISSUE TITLE
Support for private catalogs with Git SSH protocol

### ISSUE THREAD

**Issue by johnrengelman** [rancher/rancher#3147] opened 2015-12-29 01:11 UTC
It would be nice to be able to specify the connection information for a private Git repository when adding a catalog entry. This would include the private SSH key to use for connecting when using the `git+ssh` protocol.

**Comment by mcuadros** [comment] 2015-12-29 18:36
If you wish to use private repositories is better use https protocol and a token, we are running our private catalog using this pattern and works perfect.

`https://<your-token>:@github.com/your/private-catalog`

**Comment by CBR09** [comment] 2016-01-08 08:55
+1

**Comment by airtonix** [comment] 2016-07-21 23:21
@mcuadros that only works for github. What about bitbucket, private stash, private gitlab, private other git.

What you really need to be doing is this:

```
[ + ] Add Catlog

[  Catalog Name                                            ] [ Catalog URI                                         ]
one of the following:
-  [ Button Upload: Private Key ]
-  [ Button: Generate SSH Key ]
```

**Comment by SydOps** [comment] 2016-08-11 07:56
+1 for this feature

**Comment by shoutcool** [comment] 2016-08-19 08:25
+1 this feature would be great. 
We normally work with Bitbucket over ssh URLs. So we had to enable the http access to Bitbucket, just because of Rancher

**Comment by jlee70** [comment] 2016-09-23 20:29
+1

**Comment by juanfont** [comment] 2016-11-11 16:35
+100000

**Comment by gerhro** [comment] 2016-11-22 12:03
+1

**Comment by swartel-fa** [comment] 2016-12-19 09:11
+1

**Comment by NDevox** [comment] 2016-12-19 09:18
+1. This is a serious problem for some businesses.

**Comment by ekristen** [comment] 2017-01-08 20:34
+1

**Comment by gcallsen** [comment] 2017-02-01 02:58
+1

**Comment by leroy0211** [comment] 2017-03-17 15:15
+1

**Comment by Kurisutian** [comment] 2017-04-20 12:54
+1
Definitely something I would also need when using rancher at our company. It's a must have to me!
Any status updates as it's tagged for a closed milestone?

**Comment by swartel-fa** [comment] 2017-04-28 10:33
up please

**Comment by royerhq** [comment] 2017-05-10 19:09
+1

**Comment by superseb** [comment] 2017-05-10 19:14
Closing this as duplicate of https://github.com/rancher/rancher/issues/3248, it will be referenced.

**Closed by superseb** 2017-05-10 19:14 UTC
Labels: area/catalog-service, kind/enhancement
