### ISSUE TITLE
Error message when launching templates with Read-Only role

### ISSUE THREAD

**Issue by zambon** [rancher/rancher#7549] opened 2017-01-25 21:55 UTC
**Rancher Versions:**
Server: 1.3.3

_Other details omitted; I believe they aren't important for this issue._

**Steps to Reproduce:**

1. Log into Rancher
1. Switch to an environment that your user has _Read-Only_ role
1. Try to launch a template

**Results:**  The error message says _Method not allowed_, which is a bit unclear.

**Expectation:** An error message that clearly indicates I don't have permission to launch templates in this environment.

**Comment by tfiduccia** [comment] 2017-01-27 21:40
This is previously reported and a duplicate of #1990

**Closed** 2017-01-27 21:40 UTC
