### ISSUE TITLE
Snapshots will timeout when snapshot take longer to complete (when etcd contains a lot of data)

### ISSUE THREAD

**Issue by intonet** [rancher/rancher#19496] opened 2019-04-10 07:56 UTC
Hi 
I have problem with snapshots. My cluster is working with a few deployed application. 
I have 3 masters node created on azure with ubuntu 16.04. Not working local and s3 snapshots no matter is take manual or scheduled.

Rancher logs
```
2019/04/09 12:48:17 [INFO] Starting saving snapshot on etcd hosts
2019/04/09 12:48:17 [INFO] [dialer] Setup tunnel for host [172.xxx.xxx.7]
2019/04/09 12:48:17 [INFO] [dialer] Setup tunnel for host [172.xxx.xxx.12]
2019/04/09 12:48:17 [INFO] [dialer] Setup tunnel for host [172.xxx.xxx.13]
2019/04/09 12:48:18 [INFO] [etcd] Saving snapshot [c-8ng9s-ms-2hpmj] on host [172.xxx.xxx.7]
2019/04/09 12:48:22 [INFO] Handling backend connection request [c-8ng9s:m-btlcr]
2019/04/09 12:48:24 [INFO] [etcd] Successfully started [etcd-snapshot-once] container on host [172.xxx.xxx.7]
2019/04/09 12:48:29 [INFO] Handling backend connection request [c-mdp8g:m-gtgtd]
2019/04/09 12:48:38 [INFO] Handling backend connection request [c-mdp8g:m-kbxhj]
2019/04/09 12:48:56 [INFO] Handling backend connection request [c-8ng9s:m-l7hvg]
2019/04/09 12:49:08 [INFO] Handling backend connection request [c-mdp8g:m-kbxhj]
2019/04/09 12:49:34 [INFO] kontainerdriver rancherkubernetesengine stopped
2019/04/09 12:49:34 [WARNING] Error waiting for container [etcd-snapshot-once] on host [172.xxx.xxx.7]: Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
2019/04/09 12:49:43 [INFO] Handling backend connection request [c-8ng9s:m-btlcr]
2019/04/09 12:49:47 [INFO] kontainerdriver rancherkubernetesengine listening on address 127.0.0.1:10071
2019/04/09 12:49:47 [INFO] Starting saving snapshot on etcd hosts
2019/04/09 12:49:47 [INFO] [dialer] Setup tunnel for host [172.xxx.xxx.12]
2019/04/09 12:49:47 [INFO] [dialer] Setup tunnel for host [172.xxx.xxx.13]
2019/04/09 12:49:47 [INFO] [dialer] Setup tunnel for host [172.xxx.xxx.7]
2019/04/09 12:49:47 [INFO] [etcd] Saving snapshot [c-8ng9s-ms-2hpmj] on host [172.xxx.xxx.7]
2019/04/09 12:49:51 [INFO] [etcd] Successfully started [etcd-snapshot-once] container on host [172.xxx.xxx.7]
2019/04/09 12:49:57 [INFO] Handling backend connection request [c-mdp8g:m-gtgtd]
2019/04/09 12:50:10 [INFO] Handling backend connection request [c-8ng9s:m-btlcr]
2019/04/09 12:50:26 [INFO] Handling backend connection request [c-mdp8g:m-gtgtd]
2019/04/09 12:50:35 [INFO] Handling backend connection request [c-mdp8g:m-kbxhj]
2019/04/09 12:50:45 [INFO] Handling backend connection request [c-8ng9s:m-l7hvg]
2019/04/09 12:51:04 [INFO] Handling backend connection request [c-8ng9s:m-btlcr]
2019/04/09 12:51:12 [INFO] Handling backend connection request [c-8ng9s:m-l7hvg]
2019/04/09 12:51:13 [INFO] kontainerdriver rancherkubernetesengine stopped
2019/04/09 12:51:13 [WARNING] Error waiting for container [etcd-snapshot-once] on host [172.xxx.xxx.7]: Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
2019/04/09 12:51:13 [INFO] [etcd-backup] Deleteing backup c-8ng9s-ms-2hpmj
```

On master host Etcd-snapshot-once work max 60s and show only:

```
docker logs --tail=100 -f etcd-snapshot-once
time="2019-04-08T12:09:59Z" level=info msg="Initializing Rolling Backups" creation=12h0m0s retention=72h0m0s
time="2019-04-08T12:09:59Z" level=info msg="invoking set s3 service client"
```

I tried local and s3 backups and both was stuck on activating.

On /opt/rke/etcd-snapshots/  directory is many part files
```
ls /opt/rke/etcd-snapshots/ -lah
-rw-r--r-- 1 root root 1.2G Apr 10 01:33 c-8ng9s-rl-wx8g7.part
-rw-r--r-- 1 root root 107M Apr  9 06:48 c-8ng9s-rs-2qx7p.part
-rw-r--r-- 1 root root 640M Apr  8 13:19 c-8ng9s-rs-956zd.part
-rw-r--r-- 1 root root    0 Apr  9 06:43 c-8ng9s-rs-bx9d5.part
-rw-r--r-- 1 root root 1.1G Apr  9 06:53 c-8ng9s-rs-hppkt.part
-rw-r--r-- 1 root root 274M Apr  9 12:56 c-8ng9s-rs-m9gzc.part
-rw-r--r-- 1 root root 112M Apr  9 13:02 c-8ng9s-rs-n6l9l.part
-rw-r--r-- 1 root root 703M Apr  8 13:15 c-8ng9s-rs-s77rh.part
-rw-r--r-- 1 root root 417M Apr  8 13:10 c-8ng9s-rs-t8tjw.part
-rw-r--r-- 1 root root 705M Apr  9 06:54 c-8ng9s-rs-xprjm.par 
```

Full snapshot take 1.7GB. 
Maybe is a problem with size. My dev cluster with one master and s3 on the same rancher instance take snapshots successful but snapshot takes 9MB only 

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v2.2.2-rc5` UI: `v2.2.38` |
|Route|`authenticated.cluster.nodes.index`|

**Comment by deniseschannon** [comment] 2019-04-12 20:00
It sounds like you might be hitting this: https://github.com/rancher/rancher/issues/18465

1. I wouldn't recommend picking up RCs, they are RCs for a reason and we don't test upgrades between RCs so upgrading to a final version might not work for you.

2. Is this an upgraded setup (aka did you create these clusters before v2.2.0?). What were your steps to update the cluster to start taking snapshots? Can you take a snapshot of  the  UI to show the settings for the backups section? (pun intended!)

**Comment by intonet** [comment] 2019-04-16 07:47
This is not problem with s3 because I tried to also local snapshots as well. 
I Upgraded from v2.1.7 to 2.2.1 by helm. I tried to take snapshots but not working. I read about similar problem on centos and decide to test on RC version.  [here](https://github.com/rancher/rancher/issues/19421)

<img width="1230" alt="Screenshot 2019-04-16 at 09 39 45" src="https://user-images.githubusercontent.com/35962194/56191100-fb732b80-602b-11e9-8353-e3adc594a120.png">

**Comment by deniseschannon** [comment] 2019-04-17 22:51
after upgrading, have you "saved" the settings in any existing cluster to convert it from the old backup settings to the new ones? 

Do you have this issue with any newly provisioned clusters?

**Comment by intonet** [comment] 2019-04-18 10:37
yes. I saved setting not once trying switching to local backup. 
This for existing cluster. I didn't try create new one. 
I have two clusters. DEV and PROD.  Both was created on 2.1 runcher. Snapshots works fine on Dev where is smal Etcd dump size. 
For me looks like Etcd-snapshot image works with timeout on 60s and in this time take only a  part of backup. ( different size of .part files)

**Comment by superseb** [comment] 2019-04-19 21:10
Steps to reproduce:
* Create custom cluster, add nodes with necessary roles (I used 3 etcd, 2 controlplane, 2 worker)
* Fill up etcd
  * Login to one etcd node
  * Shell into `etcd` container: `docker exec -ti etcd sh`
  * Create dummy file: `dd if=/dev/zero of=testfile.out bs=1500 count=1024`
  * Fill up etcd: 
```
for i in `seq 1 1000`; do cat testfile.out | etcdctl put key; done
```
* Check DB size
```
docker exec etcd etcdctl endpoint status --endpoints=$(docker exec etcd /bin/sh -c "etcdctl member list | cut -d, -f5 | sed -e 's/ //g' | paste -sd ','") --write-out table
```
* Create snapshot using `Snapshow Now` in UI

**Comment by alena1108** [comment] 2019-04-26 18:48
Can be tested with 2.2.3-rc2 build

**Comment by soumyalj** [comment] 2019-05-04 00:14
Reproduced the issue with rancher v2.2.2 using the steps as mentioned above.
Observed the rancher logs :
```
2019/05/03 23:49:04 [INFO] kontainerdriver rancherkubernetesengine stopped
2019/05/03 23:49:04 [WARNING] Error waiting for container [etcd-snapshot-once] on host [abcd]: Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
2019/05/03 23:49:05 [INFO] Handling backend connection request [c-m2pqq:m-65263204df03]
2019/05/03 23:49:10 [INFO] kontainerdriver rancherkubernetesengine listening on address 127.0.0.1:10447
2019/05/03 23:49:10 [INFO] Starting saving snapshot on etcd hosts
2019/05/03 23:49:10 [INFO] [dialer] Setup tunnel for host [abcd]
2019/05/03 23:49:10 [INFO] [dialer] Setup tunnel for host [abcd]
2019/05/03 23:49:10 [WARNING] Failed to set up SSH tunneling for host [abcd]: Can't establish dialer connection: can not build dialer to c-m2pqq:m-ddd433304250
2019/05/03 23:49:10 [INFO] [dialer] Setup tunnel for host [efgh]
2019/05/03 23:49:10 [INFO] [dialer] Setup tunnel for host [efgh]
2019/05/03 23:49:15 [INFO] error in remotedialer server [400]: read tcp 172.***:443->: i/o timeout
2019/05/03 23:49:15 [WARNING] Failed to set up SSH tunneling for host [efgh]: Can't retrieve Docker Info: error during connect: Get http://%!F(MISSING)var%!F(MISSING)run%!F(MISSING)docker.sock/v1.24/info: tunnel disconnect

```

In /opt/rke/etcd-snapshots/ directory .part file was observed

```
ubuntu@ip-172-31-14-239:/opt/rke/etcd-snapshots$ ls -ltr
total 457904
-rw-r--r-- 1 root root   5472288 May  3 22:30 c-m2pqq-rs-7wqrs
-rw-r--r-- 1 root root 452460544 May  3 23:51 c-m2pqq-ms-whxpd.part



```

**Comment by soumyalj** [comment] 2019-05-05 01:34
Tested with v2.2.3-rc5 . Created Custom cluster with  3etcd only nodes, 1 control/worker node 
1. Exec into one of the etcd nodes. (The etcd nodes were 2core with 4G RAM)
2. for i in `seq 1 1000`; do cat testfile.out | etcdctl --endpoints=172.31.x.x:2379 put key; done
3. etcd was filled up to 1.8G
docker exec etcd etcdctl endpoint status --endpoints=172.31.x.x:2379 --write-out table
etcd was filled up to 1.8G
+-------------------+------------------+---------+---------+-----------+-----------+------------+
|     ENDPOINT      |        ID        | VERSION | DB SIZE | IS LEADER | RAFT TERM | RAFT INDEX |
+-------------------+------------------+---------+---------+-----------+-----------+------------+
| 172.31.x.x:2379 | 69db3b90a372493f |  3.2.24 |  1.8 GB |      true |        45 |       9669 |
+-------------------+------------------+---------+---------+-----------+-----------+------------+
4. etcd snapshot now was performed.

The snapshot was stuck in activating state and the etcd node goes to "Unavailable" state

![Screen Shot 2019-05-04 at 6 21 46 PM](https://user-images.githubusercontent.com/18536626/57186730-890ea200-6e99-11e9-93d4-b6b33713ae5b.png)

The snapshot may go to active state, but goes to activating state  again. There is also an attempt to remove the snapshot .

```
2019/05/05 01:23:16 [INFO] Container [etcd-snapshot-once] is still running on host [abcd]
2019/05/05 01:23:17 [INFO] Waiting for [etcd-snapshot-once] container to exit on host [abcd]
2019/05/05 01:23:20 [INFO] [remove/etcd-snapshot-once] Successfully removed container on host [abcd]
2019/05/05 01:23:20 [WARNING] Failed to remove container [Can't remove Docker container [etcd-snapshot-once] for host [3.14.143.155]: Error: No such container: etcd-snapshot-once]: %!!(MISSING)v(MISSING)
2019/05/05 01:23:20 [INFO] kontainerdriver rancherkubernetesengine stopped
2019/05/05 01:23:20 [WARNING] Failed to get gather logs from container [etcd-snapshot-once]: Error: No such container: etcd-snapshot-once
2019/05/05 01:23:26 [INFO] [etcd] Successfully started [etcd-snapshot-once] container on host [abcd]
2019/05/05 01:23:26 [INFO] Waiting for [etcd-snapshot-once] container to exit on host [3.14.143.155]
2019/05/05 01:23:27 [INFO] Container [etcd-snapshot-once] is still running on host [abcd]



```
etcd container logs
```
2019-05-05 01:12:56.430767 I | rafthttp: established a TCP streaming connection with peer a347e5f9a316d213 (stream Message reader)
2019-05-05 01:13:27.196769 W | etcdserver: read-only range request "key:\"/registry/secrets/cattle-system/cattle-token-2b4wc\" " with result "range_response_count:1 size:2324" took too long (441.539984ms) to execute
2019-05-05 01:13:27.233352 W | etcdserver: read-only range request "key:\"/registry/secrets/cattle-system/cattle-token-2b4wc\" " with result "range_response_count:1 size:2324" took too long (445.074317ms) to execute
2019-05-05 01:14:44.139503 W | rafthttp: lost the TCP streaming connection with peer 81012ddadb1e31d0 (stream Message reader)
2019-05-05 01:14:44.139547 E | rafthttp: failed to read 81012ddadb1e31d0 on stream Message (read tcp 172.31.7.152:46286->172.31.x.x:2380: i/o timeout)
2019-05-05 01:14:44.139553 I | rafthttp: peer 81012ddadb1e31d0 became inactive
2019-05-05 01:14:56.094549 I | etcdmain: rejected connection from "172.31.8.x.x:36522" (error "read tcp 172.31.x.x:2380->172.31.8.x.x:36522: i/o timeout", ServerName "")
2019-05-05 01:14:56.832466 I | etcdmain: rejected connection from "172.31.x.x:36526" (error "read tcp 172.31.x.x:2380->172.31.8.254:36526: i/o timeout", ServerName "")
2019-05-05 01:15:02.016857 I | rafthttp: peer 81012ddadb1e31d0 became active
2019-05-05 01:15:02.016885 I | rafthttp: established a TCP streaming connection with peer 81012ddadb1e31d0 (stream Message reader)
2019-05-05 01:15:21.262639 I | mvcc: store.index: compact 8000
2019-05-05 01:15:21.264381 I | mvcc: finished scheduled compaction at 8000 (took 1.141878ms)
2019-05-05 01:17:46.692577 W | mvcc/backend: snapshotting is taking more than 30.000169781 seconds to finish transferring 1709.9605522682446 MB [started at 2019-05-05 01:17:16.689723588 +0000 UTC]


```

**Comment by superseb** [comment] 2019-05-07 12:06
The issue seen comes from memory usage of using `minio-go` library to upload the file to S3/Minio. This fails on a 4GB machine but succeeds when using 8GB of memory. When looking at the code, the snapshot is not compressed, which uses a lot of memory but also will take longer to transfer (and will cost more money if S3). Suggestion would be to compress the snapshot on the node, before transferring (and decompressing after retrieval). There is some information on tests done by etcd team here https://github.com/etcd-io/etcd/issues/5186

**Comment by alena1108** [comment] 2019-06-13 23:57
As the @superseb stated in his comment, the fix for the issue is to start compressing (zip) our etcd snapshots. We do it to resolve 2 issues:

* Minio library hitting OOM
* Reduce disk usage on local storage and S3

As a part of testing, we should:

* Validate that the original issue is not happening any more.
* Re-test etcd snapshot functionality for both local and S3 backend
* Make sure the snapshots taken prior to v2.2.5 (the ones that are not compressed) are functional - test the recovery and snapshot removal use cases.

**Comment by soumyalj** [comment] 2019-06-28 04:28
Tested with master-head build from June 27.

Tested with t2.large machines(2 core 8G RAM)
Created Custom cluster with 3etcd only nodes, 1 control/worker node .
S3 Minio configuration was set for etcd backups

Exec into one of the etcd nodes. (The etcd nodes were 2core with 4G RAM)
Create dummy file: dd if=/dev/zero of=testfile.out bs=1500 count=1024
for i in seq 1 1000; do cat testfile.out | etcdctl put key; done
etcd was filled up to 1.7G
docker exec etcd etcdctl endpoint status --endpoints=172.31.x.x:2379 --write-out table
etcd was filled up to 1.7G
2019-06-28 04:22:13.118904 W | pkg/flags: recognized environment variable ETCDCTL_ENDPOINTS, but unused: shadowed by corresponding flag
+--------------------+------------------+---------+---------+-----------+-----------+------------+
|      ENDPOINT      |        ID        | VERSION | DB SIZE | IS LEADER | RAFT TERM | RAFT INDEX |
+--------------------+------------------+---------+---------+-----------+-----------+------------+
| 172.31.11.182:2379 | 5c39cd9b39557c39 |  3.3.10 |  1.7 GB |     false |         2 |      18528 |
+--------------------+------------------+---------+---------+-----------+-----------+------------+

Snapshot was taken and it completed in around 3 mins
Restore was also performed and it completed in around 4 mins

Other use cases tested for regression:

1. Snapshot restore using S3 minio configuration was tested and it was successful
2. Snapshot restore using S3 configuration was tested and it was successful
3. Created single node cluster with DO node. Snapshot was taken and restored. Two more etcd nodes were added and restore was performed . Restore was successful
4. Local back and restore was tested a few times and it was successful.
5. Create a 3 node custom cluster with all three roles(etcd, control, worker) and deploy few workloads . Perform a backup. Break the cluster by powering off 3 nodes. Wait for cluster to become unavailable. Delete the existing powered off nodes and and add 3 new etcd nodes. perform restore. Restore was successful

**Closed** 2019-06-28 04:57 UTC
Labels: [zube]: To Test, area/backup-recover, kind/bug, team/ca
