### ISSUE TITLE
UI - All cloud credentials show up in Linode Template creation page.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#21601] opened 2019-07-17 22:00 UTC
Rancher server version - Build from master - 7/17

Steps to reproduce the problem:
Create a Digital Ocean Node template which would also prompt the creation of DO cloud credentials.
Create a Linode Node Template.
"Cloud Credentials" drop down menu has DO  cloud credential pre selected.

Expected Behavior:
"Cloud Credentials" drop down should show only Linode cloud credentials.

**Comment by loganhz** [comment] 2019-08-12 10:27
This need to be fixed in https://github.com/linode/rancher-ui-driver-linode repo

We need to extend the NodeDriver mixin or do something similar with https://github.com/rancher/ui/blob/master/lib/shared/addon/mixins/node-driver.js#L238

cc @deniseschannon @phillc

**Comment by phillc** [comment] 2019-08-12 20:53
Was able to reproduce with `v0.3.0-alpha.3` and is fixed in `v0.3.0`.

**Comment by davidnuzik** [comment] 2019-08-13 15:43
Version: master-head (v2.3) (8/13/19)

Follow the steps to reproduce, create a DO nodeTemplate (which also makes us create a Cloud Credential for it).
Now, try to create a Linode nodeTemplate, the issue is fixed as we no longer see DigitalOcean cloud credential listed (and I am prompted to create a Linode CC)

![image](https://user-images.githubusercontent.com/45179589/62955746-6e0bd200-bda6-11e9-83b4-41618dbcc2d9.png)

**Closed by davidnuzik** 2019-08-13 15:43 UTC
Labels: [zube]: To Test, area/ui, internal, team/ui
