### ISSUE TITLE
When switching between environments, load balancer targets disappear

### ISSUE THREAD

**Issue by jraede** [rancher/rancher#2646] opened 2015-11-12 15:41 UTC
If you then go to add a new target to the seemingly empty load balancer, it will override all existing targets. If you refresh the page, the targets show.

This happens when we use the menu at the top right of the UI to switch between our "Dev" and "Production" environments.

**Comment by deniseschannon** [comment] 2015-11-12 15:43
This is a duplicate of https://github.com/rancher/rancher/issues/1389

**Comment by deniseschannon** [comment] 2015-11-12 15:43
And the underlying issue is that the link is missing in the UI with multiple environments.

**Closed by deniseschannon** 2015-11-12 15:43 UTC
