### ISSUE TITLE
Cannot Add VmWare vSphere Host  - Upgrade docker-machine to v0.5.6

### ISSUE THREAD

**Issue by kilokill** [rancher/rancher#3233] opened 2016-01-11 02:16 UTC
Everytime I try to add a VmWare vSphere Host I get the following error:

```
1/10/2016 9:10:51 PMtime="2016-01-11T02:10:51Z" level=info msg="Cmd slice: [create -d vmwarevsphere --vmwarevsphere-boot2docker-url /var/lib/cattle/boot2docker.iso --vmwarevsphere-compute-ip 192.168.2.228 --vmwarevsphere-cpu-count 1 --vmwarevsphere-datacenter ha-datacenter --vmwarevsphere-datastore SSD1-500GB --vmwarevsphere-disk-size 200 --vmwarevsphere-memory-size 200 --vmwarevsphere-network VM Network --vmwarevsphere-password Kilokilo!12 --vmwarevsphere-username root --vmwarevsphere-vcenter 192.168.2.228 TEST]"
1/10/2016 9:10:51 PMtime="2016-01-11T02:10:51Z" level=info msg="stdout: Creating CA: /var/lib/cattle/machine/5aed8a6a-86f6-468e-ba6b-dcb02095d74d/certs/ca.pem" resourceId: =1ph17
1/10/2016 9:10:51 PMtime="2016-01-11T02:10:51Z" level=info msg="stdout: Creating client certificate: /var/lib/cattle/machine/5aed8a6a-86f6-468e-ba6b-dcb02095d74d/certs/cert.pem" resourceId: =1ph17
1/10/2016 9:10:51 PMtime="2016-01-11T02:10:51Z" level=info msg="stdout: Running pre-create checks..." resourceId: =1ph17
1/10/2016 9:10:51 PMtime="2016-01-11T02:10:51Z" level=info msg="stdout: Creating machine..." resourceId: =1ph17
1/10/2016 9:10:51 PMtime="2016-01-11T02:10:51Z" level=info msg="stdout: (TEST) Image cache does not exist, creating it at /var/lib/cattle/machine/5aed8a6a-86f6-468e-ba6b-dcb02095d74d/cache..." resourceId: =1ph17
1/10/2016 9:10:51 PMtime="2016-01-11T02:10:51Z" level=info msg="stdout: (TEST) Downloading boot2docker.iso from /var/lib/cattle/boot2docker.iso..." resourceId: =1ph17
1/10/2016 9:10:51 PMtime="2016-01-11T02:10:51Z" level=info msg="stdout: (TEST) Generating SSH Keypair..." resourceId: =1ph17
1/10/2016 9:10:52 PMtime="2016-01-11T02:10:52Z" level=info msg="stdout: (TEST) Uploading Boot2docker ISO ..." resourceId: =1ph17
1/10/2016 9:10:52 PMtime="2016-01-11T02:10:52Z" level=info msg="stderr: Error creating machine: Error in driver during machine creation: Incomplete vSphere information: missing /var/lib/cattle/machine/5aed8a6a-86f6-468e-ba6b-dcb02095d74d/boot2docker.iso" resourceId=1ph17
1/10/2016 9:10:52 PMtime="2016-01-11T02:10:52Z" level=info msg="starting cleanup..." machine name=TEST
1/10/2016 9:10:52 PMtime="2016-01-11T02:10:52Z" level=info msg="cleanup successful" machine name=TEST
1/10/2016 9:10:52 PMtime="2016-01-11T02:10:52Z" level=error msg="Error processing event" err="Error in driver during machine creation: Incomplete vSphere information: missing /var/lib/cattle/machine/5aed8a6a-86f6-468e-ba6b-dcb02095d74d/boot2docker.iso" eventId="d64c5018-925f-423f-831c-4261f21c64e5" eventName="physicalhost.create;handler=goMachineService" resourceId=1ph17
```

I put the boot2docker iso in /var/lib/cattle but for whatever reason it isn't able to use it. I've tried putting the direct github iso download url for the iso as well, nothing works. 

Any ideas?

**Comment by deniseschannon** [comment] 2016-01-11 21:45
The UI is just calling the docker-machine command to add hosts to the machine. It looks like you are having issues with the docker-machine command.

Have you tried using docker-machine  with VmWare VSphere to isolate that it's not a Rancher issue? https://docs.docker.com/machine/drivers/vsphere/

I've never tested launching a vmware vsphere host, but I believe the URL must be a URL and can't be a folder location.

**Comment by mgherman** [comment] 2016-02-05 03:35
I ran into this issue yesterday, and it is a bug in the version of docker-machine (v.0.5.2) shipped in Rancher. The issue is outlined here https://github.com/docker/machine/issues/2279 and has been rectified in the current release of docker-machine (v.0.5.6).

Inserting the new version of docker-machine into the rancher/server container allows the vsphere host to be built, but is then cleaned up by another bug, due to not finding the certs/ca.pem

**Comment by deniseschannon** [comment] 2016-02-08 18:56
We will be working on updating the docker-machine version in an upcoming release.

**Comment by daswars** [comment] 2016-02-29 22:36
i have the same error. With the "docker-machine version 0.6.0, build" works again.

**Comment by akurkin** [comment] 2016-03-01 09:39
@daswars which version of rancher are you using?

**Comment by daswars** [comment] 2016-03-01 14:11
Hi @akurkin at the moment as i write the text i only use docker-machine. But with the version v0.61.0-rc3 https://hub.docker.com/r/rancher/server/tags/ it works.

here my example input:

VSPHERE_BOOT2DOCKER_URL=""
VSPHERE_CPU_COUNT=4
VSPHERE_DATACENTER="Datacenter"
VSPHERE_DATASTORE="vsanDatastore"
VSPHERE_DISK_SIZE=22000
VSPHERE_HOSTSYSTEM="Cluster-vSAN/srv01.example.com"
VSPHERE_MEMORY_SIZE=4096
VSPHERE_NETWORK="Intranet"
VSPHERE_PASSWORD="SEXYPASSWORD"
VSPHERE_POOL=""
VSPHERE_USERNAME="itadmin@example.local"
VSPHERE_VCENTER="vcenter.example.com"
VSPHERE_VCENTER_PORT="443"

**Comment by deniseschannon** [comment] 2016-03-04 17:48
Confirmed with @hibooboo2 that the docker-machine has been upgraded to v0.6, so this should be fixed in the next release. 

@kilokill After the next release comes out, would you be able to verify?

**Comment by kilokill** [comment] 2016-03-04 18:58
@deniseschannon Yes. Can definitely verify the fix once released.

**Comment by deniseschannon** [comment] 2016-03-13 18:25
@kilokill With v0.63.0 released, could you please test and let me know if it's working? Docker-machine has been updated.

**Comment by mgherman** [comment] 2016-03-14 20:05
Hi Denise,

We have just upgraded rancher/server to 0.63 and can confirm docker-machine can create vmwarevsphere hosts successfully.

Thanks for the fix!

Rgds,

mgh

**Comment by kilokill** [comment] 2016-03-14 20:10
@deniseschannon Seconding @mgherman . Its working now.

**Comment by deniseschannon** [comment] 2016-03-14 20:20
Thanks for verifying @mgherman and @kilokill!

**Closed by deniseschannon** 2016-03-14 20:20 UTC
Labels: area/machine, kind/bug, status/pr-submitted, status/to-test

**Comment by briannosaurus** [comment] 2016-03-16 21:23
I don't think this is fix. as i am on the lastest 0.63 and i am still getting the same error as OP.

Error in driver during machine creation: Incomplete vSphere information: missing /var/lib/cattle/machine/3e2a0220-4e79-4faf-853f-d1946ee2b066/boot2docker.iso

But my logs shows it does and it downloads it into the correct folder. it just does not copy it to vsphere.

now if i use the same command in the logs on my ubuntu system it creates the virtual machines just fine.

**Comment by deniseschannon** [comment] 2016-03-17 03:22
@mgherman and @kilokill were able to launch their hosts with no issues on  v0.63.0. Would either of you be able to give some guidance? I haven't had time to attempt to launch them in vSphere.

@briannosaurus Can you share your logs (hide the sensitive information)?

**Comment by briannosaurus** [comment] 2016-03-23 14:54
Here is my output:

`INFO[25595] Creating Machine                              eventId=89833ced-eb4c-4b14-9fa1-95196c9a8ce9 resourceId=1ph31                                                                                                                         
INFO[25595] Cmd slice: [create -d vmwarevsphere --vmwarevsphere-compute-ip Cluster-Core/10.0.3.202 --vmwarevsphere-cpu-count 2 --vmwarevsphere-datacenter TestLab --vmwarevsphere-datastore Datastore-TestLab --vmwarevsphere-disk-size 20480 --vmwarevsphere-memory-size 2048 --vmwarevsphere-network VLAN 10 --vmwarevsphere-password 1234 --vmwarevsphere-pool Cluster-Core/Resources/Rancher-Cluster --vmwarevsphere-username deploy@vsphere.local --vmwarevsphere-vcenter 10.0.5.250 Rancher-Test1]                                                                                                                                                                                                                                      
INFO[25596] Creating Machine                              eventId=a72a4eba-3a93-4fed-8b0f-70c53c567e99 resourceId=1ph32                                                                                                                         
INFO[25596] Cmd slice: [create -d vmwarevsphere --vmwarevsphere-compute-ip Cluster-Core/10.0.3.202 --vmwarevsphere-cpu-count 2 --vmwarevsphere-datacenter TestLab --vmwarevsphere-datastore Datastore-TestLab --vmwarevsphere-disk-size 20480 --vmwarevsphere-memory-size 2048 --vmwarevsphere-network VLAN 10 --vmwarevsphere-password 1234 --vmwarevsphere-pool Cluster-Core/Resources/Rancher-Cluster --vmwarevsphere-username deploy@vsphere.local --vmwarevsphere-vcenter 10.0.5.250 Rancher-Test2]                                                                                                                                                                                                                                      
INFO[25596] stdout: Creating CA: /var/lib/cattle/machine/2b99f306-f3a9-4f38-9f21-0dd6ae96e270/certs/ca.pem  resourceId: =1ph31                                                                                                                  
INFO[25596] stdout: Creating CA: /var/lib/cattle/machine/346469a3-aba8-47c6-9443-8a09a99a3b8d/certs/ca.pem  resourceId: =1ph32                                                                                                                  
INFO[25596] stdout: Creating client certificate: /var/lib/cattle/machine/346469a3-aba8-47c6-9443-8a09a99a3b8d/certs/cert.pem  resourceId: =1ph32                                                                                                
INFO[25596] stdout: Creating client certificate: /var/lib/cattle/machine/2b99f306-f3a9-4f38-9f21-0dd6ae96e270/certs/cert.pem  resourceId: =1ph31                                                                                                
INFO[25596] stdout: Running pre-create checks...          resourceId: =1ph31                                                                                                                                                                    
INFO[25596] stdout: Creating machine...                   resourceId: =1ph31                                                                                                                                                                    
INFO[25596] stdout: (Rancher-Test1) Image cache does not exist, creating it at /var/lib/cattle/machine/2b99f306-f3a9-4f38-9f21-0dd6ae96e270/cache...  resourceId: =1ph31                                                                        
INFO[25596] stdout: (Rancher-Test1) No default boot2docker iso found locally, downloading the latest release...  resourceId: =1ph31                                                                                                             
INFO[25597] stdout: (Rancher-Test1) Latest release for github.com/boot2docker/boot2docker is v1.10.3  resourceId: =1ph31                                                                                                                        
INFO[25597] stdout: (Rancher-Test1) Downloading https://github.com/boot2docker/boot2docker/releases/download/v1.10.3/boot2docker.iso to /var/lib/cattle/machine/2b99f306-f3a9-4f38-9f21-0dd6ae96e270/cache/boot2docker.iso...  resourceId: =1ph31                                                                                                                                                                                                                                               
INFO[25597] stdout: Running pre-create checks...          resourceId: =1ph32                                                                                                                                                                    
INFO[25597] stdout: Creating machine...                   resourceId: =1ph32                                                                                                                                                                    
INFO[25597] stdout: (Rancher-Test2) Image cache does not exist, creating it at /var/lib/cattle/machine/346469a3-aba8-47c6-9443-8a09a99a3b8d/cache...  resourceId: =1ph32                                                                        
INFO[25597] stdout: (Rancher-Test2) No default boot2docker iso found locally, downloading the latest release...  resourceId: =1ph32                                                                                                             
INFO[25598] stdout: (Rancher-Test2) Latest release for github.com/boot2docker/boot2docker is v1.10.3  resourceId: =1ph32                                                                                                                        
INFO[25598] stdout: (Rancher-Test2) Downloading https://github.com/boot2docker/boot2docker/releases/download/v1.10.3/boot2docker.iso to /var/lib/cattle/machine/346469a3-aba8-47c6-9443-8a09a99a3b8d/cache/boot2docker.iso...  resourceId: =1ph32                                                                                                                                                                                                                                               
INFO[25605] stdout: (Rancher-Test2) 0%....10%....20%....30%....40%....50%....60%....70%....80%....90%....100%  resourceId: =1ph32                                                                                                               
INFO[25605] stdout: (Rancher-Test2) Generating SSH Keypair...  resourceId: =1ph32                                                                                                                                                               
INFO[25605] stdout: (Rancher-Test2) Uploading Boot2docker ISO ...  resourceId: =1ph32                                                                                                                                                           
INFO[25606] stdout: (Rancher-Test1) 0%....10%....20%....30%....40%....50%....60%....70%....80%....90%....100%  resourceId: =1ph31                                                                                                               
INFO[25606] stdout: (Rancher-Test1) Generating SSH Keypair...  resourceId: =1ph31                                                                                                                                                               
INFO[25606] stdout: (Rancher-Test1) Uploading Boot2docker ISO ...  resourceId: =1ph31                                                                                                                                                           
INFO[25609] stdout: (Rancher-Test2) Creating directory Rancher-Test2 on datastore Datastore-TestLab of vCenter 10.0.5.250...   resourceId: =1ph32                                                                                                    
INFO[25609] stdout: (Rancher-Test1) Creating directory Rancher-Test1 on datastore Datastore-TestLab of vCenter 10.0.5.250...   resourceId: =1ph31                                                                                                    
INFO[25609] stderr: Error creating machine: Error in driver during machine creation: Incomplete vSphere information: missing /var/lib/cattle/machine/346469a3-aba8-47c6-9443-8a09a99a3b8d/boot2docker.iso  resourceId=1ph32                     
INFO[25609] starting cleanup...                           machine name=Rancher-Test2                                                                                                                                                            
INFO[25609] stderr: Error creating machine: Error in driver during machine creation: Incomplete vSphere information: missing /var/lib/cattle/machine/2b99f306-f3a9-4f38-9f21-0dd6ae96e270/boot2docker.iso  resourceId=1ph31                     
INFO[25609] starting cleanup...                           machine name=Rancher-Test1                                                                                                                                                            
INFO[25609] cleanup successful                            machine name=Rancher-Test2                                                                                                                                                            
ERRO[25609] Error processing event                        err=Error in driver during machine creation: Incomplete vSphere information: missing /var/lib/cattle/machine/346469a3-aba8-47c6-9443-8a09a99a3b8d/boot2docker.iso eventId=a72a4eba-3a93-4fed-8b0f-70c53c567e99 eventName=physicalhost.create;handler=goMachineService resourceId=1ph32                                                                                                                                                
INFO[25609] cleanup successful                            machine name=Rancher-Test1                                                                                                                                                            
ERRO[25609] Error processing event                        err=Error in driver during machine creation: Incomplete vSphere information: missing /var/lib/cattle/machine/2b99f306-f3a9-4f38-9f21-0dd6ae96e270/boot2docker.iso eventId=89833ced-eb4c-4b14-9fa1-95196c9a8ce9 eventName=physicalhost.create;handler=goMachineService resourceId=1ph31 `

The only thing i can see wrong is the boot2docker.iso is download to a folder cache. but then tries to upload the .iso from the parent folder of cache. not the .iso in cache and it cant find it causing it to fail. but if i run:

`$ docker create -d vmwarevsphere --vmwarevsphere-compute-ip Cluster-Core/10.0.3.202 --vmwarevsphere-cpu-count 2 --vmwarevsphere-datacenter TestLab --vmwarevsphere-datastore Datastore-TestLab --vmwarevsphere-disk-size 20480 --vmwarevsphere-memory-size 2048 --vmwarevsphere-network VLAN\ 10 --vmwarevsphere-password 1234 --vmwarevsphere-pool Cluster-Core/Resources/Rancher-Cluster --vmwarevsphere-username deploy\@vsphere.local --vmwarevsphere-vcenter 10.0.5.250 Rancher-Test1-cli`

This works

**Comment by deniseschannon** [comment] 2016-03-25 17:22
@briannosaurus Can you confirm that you ran the `docker-machine` command on the host that has rancher/server container running?

**Comment by briannosaurus** [comment] 2016-04-01 14:12
@deniseschannon Yes it works on the host.
where does it look for the image before downloading it.i want to copy the iso to there to see if that works.
