### ISSUE TITLE
YML export doesn't have version:2

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#6085] opened 2016-09-30 00:38 UTC
**Rancher Version:**master with perf buid

**Steps to Reproduce:**
1.  Export config

**Results:** Doesn't have version:2 tag

**Expected:**  Should have version:2

**Comment by deniseschannon** [comment] 2016-09-30 02:32
Duplicate of https://github.com/rancher/rancher/issues/5870

**Closed by deniseschannon** 2016-09-30 02:32 UTC
Labels: area/service, kind/bug
