### ISSUE TITLE
Auto-prune Hosts

### ISSUE THREAD

**Issue by MarcusSjolin** [rancher/rancher#3607] opened 2016-02-12 07:42 UTC
This is a feature request, not an expected behaviour.

I would like to see a feature where hosts can get auto pruned after a set period of time if enabled. Either through connectivity api request or through some global setting in Rancher.

This relates to my issue where my "run on all hosts" won't work if there's hosts reconnecting.

https://github.com/rancher/rancher/issues/3480

also probably same as
https://github.com/rancher/rancher/issues/1870

**Comment by deniseschannon** [comment] 2016-02-15 05:05
As you mentioned, duplicate of #1870.

**Closed by deniseschannon** 2016-02-15 05:05 UTC
