### ISSUE TITLE
Unable to provision Azure Disk with Azure node driver

### ISSUE THREAD

**Issue by jgreat** [rancher/rancher#19749] opened 2019-04-22 15:53 UTC
I've set up a azure node driver cluster with the cloud provider enabled. Enabled storage-classes with "shared" or ""dedicated" options and I'm unable to create "shared" disk that provisions correctly.

Specifying "shared" or "dedicated" seems to set up a new StorageV2 storage account in the resource group successfully, but it cannot bind the vhd to a volume:

```
Error creating provisioned PV object for claim default/test-2: persistentvolumes "pvc-511601d5-6513-11e9-8d5e-000d3a367102" is forbidden: error querying AzureDisk volume kubernetes-dynamic-pvc-511601d5-6513-11e9-8d5e-000d3a367102: invalid disk URI: https://ds6fd5d302651211e9bcab0.blob.core.windows.net/vhds/kubernetes-dynamic-pvc-511601d5-6513-11e9-8d5e-000d3a367102.vhd. Deleting the volume.
```

This did work the last time I played with Azure, rancher 2.0.8 or so.

Things that do work: Managed Disk
The cloud-provider creates Managed Disk like a champ, but we can't bind those because node driver creates nodes using "un-managed" disk that are stored as blob in a storage account.  

Using storage accounts/blog storage for disk pretty much been deprecated for "managed disk".
Storage account limits per Azure account and best practices say 1 storage account per node (disk availability). This makes the old style of storage accounts limit.

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v2.2.2` UI: `v2.2.41` |
|Route|`volumes.detail`|

**Comment by fwiedmann** [comment] 2019-04-24 07:21
https://github.com/rancher/rancher/issues/19216

**Comment by deniseschannon** [comment] 2019-05-03 22:01
Closing as this is a duplicate of https://github.com/rancher/rancher/issues/19216

**Closed by deniseschannon** 2019-05-03 22:01 UTC
Labels: area/node-template, area/storage, kind/bug
