### ISSUE TITLE
rancher-machine may not delete a vSphere VM if an error is encountered removing the cloud-init iso 

### ISSUE THREAD

**Issue by Oats87** [rancher/rancher#41133] opened 2023-04-11 21:36 UTC
There is an issue where rancher-machine may not properly delete a VM if an error is encountered while removing the cloud-init ISO. Notably, the only error that would not cause machine to skip removing the VM itself would be an error from vsphere that the cloud-init ISO doesn't exist.

See: https://github.com/rancher/machine/blob/88a638a36a007b42de12639eb0b19a6139c6f3f3/drivers/vmwarevsphere/vsphere.go#L503

SURE-4070

**Comment by Sahota1225** [comment] 2023-04-26 18:48
rancher machine needs to be bumped in rancher for this to be ready to test

**Comment by Oats87** [comment] 2023-05-15 22:39
https://github.com/rancher/rancher/pull/41459/files#diff-347b85f4b27f0bc66ce4f2e3c4ca653d3f1c1ffb9e2b4f7c35814cf7881fd8a5R526 bumps rancher machine to a version with the vmwarevsphere driver fix

**Comment by markusewalker** [comment] 2023-05-16 23:56
**QA TEST PLAN**

Scenarios
|Scenario|Test Case|
|---|---|
|1|As a standard user, provision a downstream K3S node driver cluster, remote cloud-init based folders, delete a worker node in the cluster and validate that it is removed and a new node replaces it|
|2|As a standard user, provision a downstream RKE1 node driver cluster, remote cloud-init based folders, delete a worker node in the cluster and validate that it is removed and a new node replaces it|
|3|As a standard user, provision a downstream RKE2 node driver cluster, remote cloud-init based folders, delete a Linux and a Windows worker node in the cluster and validate that they are removed and new nodes replace them|

**Comment by markusewalker** [comment] 2023-05-17 00:05
Reproduced this issue on `v2.7.3`. See details below:

**ENVIRONMENT DETAILS**
- Rancher install: Docker
- Rancher version: `v2.7-head` https://github.com/rancher/rancher/commit/b9ddec9e7d295ee309b61a8e36206e1ba6fe06c4
- Browser: Chrome

**TEST RESULT**
|Scenario|Test Case|Result
|---|---|---|
|1|As a standard user, provision a downstream K3S node driver cluster, remote cloud-init based folders, delete a worker node in the cluster and validate that it is removed and a new node replaces it|:x:|

**REPRO STEPS**

**Scenario 1**
1. As a standard user, provisioned a downstream K3S `v1.26.4+k3s1` node driver cluster (1 etcd, 1 cp, 1 worker).
     - Validated that the cluster and nodes came up `Active`.
2. In the worker node shell, ran command `sudo rm -rf /etc/cloud/ && sudo rm -rf /var/lib/cloud/`.
3. Deleted the worker node from the cluster and the node was stuck in `Deleting` and was not removed from Rancher or the vSphere infrastructure page.
     - Attempted this step several times on different clusters and I intermittently reproduced the behavior. In the times that it deleted and a new node would come up, it was stuck in a state of `Reconciling`.

As I am able to intermittently reproduce this behavior, I will test again with the latest `v2.7-head` and see if I see this issue.

**Comment by markusewalker** [comment] 2023-05-17 00:25
Validated that the initial issue is resolved in `v2.7-head` https://github.com/rancher/rancher/commit/b9ddec9e7d295ee309b61a8e36206e1ba6fe06c4. However, there seems to be a separate issue that I found in testing. Please find below:

**ENVIRONMENT DETAILS**
- Rancher install: Docker
- Rancher version: `v2.7-head` https://github.com/rancher/rancher/commit/b9ddec9e7d295ee309b61a8e36206e1ba6fe06c4
- Browser: Chrome

**TEST RESULT**
|Scenario|Test Case|Result
|---|---|---|
|1|As a standard user, provision a downstream K3S node driver cluster, remote cloud-init based folders, delete a worker node in the cluster and validate that it is removed and a new node replaces it|:x:|
|2|As a standard user, provision a downstream RKE2 node driver cluster, remote cloud-init based folders, delete a Linux and a Windows worker node in the cluster and validate that they are removed and new nodes replace them|:x:|

**VALIDATION STEPS**

**Scenario 1**
1. As a standard user, provisioned a downstream K3S `v1.26.4+k3s1` node driver cluster (1 etcd, 1 cp, 1 worker).
     - Validated that the cluster and nodes came up `Active`.
2. In the worker node shell, ran command `sudo rm -rf /etc/cloud/ && sudo rm -rf /var/lib/cloud/`.
3. Deleted the worker node from the cluster and validated that it was successfully removed in Rancher and the vSphere infrastructure page.
4. Validated that a new worker node spun up in Rancher and vSphere infrastructure page after the old node was successfully deleted.
5. When monitoring the new node, I see the following
<img width="288" alt="image" src="https://github.com/rancher/rancher/assets/52591819/571d4552-4cb1-486a-a0be-a3261730324a"> 
     - I repeated this several times, but I am constantly seeing this with new clusters as well.
_________
**Scenario 2**
1. Repeated scenario 1, but provisioned a downstream RKE2 `v1.26.4+rke2r1` node driver cluster (1 etcd, 1 cp, 1 worker).
2. After deleting the Linux worker node after scenario 1 step 3, I noted that the node gets stuck here:
<img width="306" alt="image" src="https://github.com/rancher/rancher/assets/52591819/b2094fea-d1ab-4a1d-840f-c93f12f3d52f">

@Oats87 I'm reopening this issue due to the issue that I reported. The original issue appears to have been resolved, but I would expect that the new node come up `Active` as part of this issue being resolved.

**Comment by snasovich** [comment] 2023-05-23 20:03
@markusewalker , the issue you ran into seems to be https://github.com/rancher/rancher/issues/41613 and since it's now in test, this one can be retested as well. Thank you!

**Comment by markusewalker** [comment] 2023-05-23 22:38
Retested this against `v2.7-head` https://github.com/rancher/rancher/commit/6ce75a0b57ad9e88cf135254a9b3b40082788eb6 (ensured this was the latest Rancher image despite the fix being in later commit). Please see updated results below:

**ENVIRONMENT DETAILS**
- Rancher install: Docker
- Rancher version: `v2.7-head` https://github.com/rancher/rancher/commit/6ce75a0b57ad9e88cf135254a9b3b40082788eb6
- Browser: Chrome

**TEST RESULT**
|Scenario|Test Case|Result
|---|---|---|
|1|As a standard user, provision a downstream K3S node driver cluster, remote cloud-init based folders, delete a worker node in the cluster and validate that it is removed and a new node replaces it|:white_check_mark:|
|2|As a standard user, provision a downstream RKE2 node driver cluster, remote cloud-init based folders, delete a Linux and a Windows worker node in the cluster and validate that they are removed and new nodes replace them|:x:|

**VALIDATION STEPS**

**Scenario 1**
1. As a standard user, provisioned a downstream K3S `v1.26.4+k3s1` node driver cluster (1 etcd, 1 cp, 1 worker).
     - Validated that the cluster and nodes came up `Active`.
2. In the worker node shell, ran command `sudo rm -rf /etc/cloud/ && sudo rm -rf /var/lib/cloud/`.
3. Deleted the worker node from the cluster and validated that it was successfully removed in Rancher and the vSphere infrastructure page.
4. Validated that a new worker node spun up in Rancher and vSphere infrastructure page after the old node was successfully deleted.
5. Validated that the new worker node eventually becomes `Active` and the cluster as well, as expected.
_Note: Repeated this scenario 3 times, each time it succeeded. Additionally, I tried with RKE2 as well with `v1.26.4+rke2r1`, same results as well._
_____________
**Scenario 2**
1. Repeated scenario 1, but provisioned a downstream RKE2 `v1.26.4+rke2r1` node driver cluster (1 etcd, 1 cp, 1 Linux worker + 1 Windows worker).
2. Deleted the Linux and Windows worker nodes at the same time.
3. Noted that the Linux worker node gets stuck in a `Reconciling` state with message `Waiting for probes: calico, kubelet` and the Windows worker node gets stuck in a `Reconciling` state with message `Waiting for probes: kubelet`.

While the issue has been addressed for Linux nodes, it appears that when a Windows worker node is present, this issue is still relevant. As such, I will be reopening the issue again as this issue should be resolved for Linux and Windows nodes, not just Linux nodes.

**Comment by Oats87** [comment] 2023-05-24 17:06
@aiyengar2 given the involvement of windows in the test failure, I think I'm going to need your help here.

**Comment by markusewalker** [comment] 2023-05-24 19:58
Spoke with @Oats87 offline and figured out there was an issue in my initial testing. I updated my test results above and both scenarios are now successful.

Closing this issue.

**Closed by markusewalker** 2023-05-24 19:58 UTC
Labels: area/machine, internal, [zube]: Reopened, QA/S, area/provisioning-v2, feature/provisioned-rke1, team/area2, team/area2/sc
