### ISSUE TITLE
Container names sometimes show up as hashes?

### ISSUE THREAD

**Issue by jmreicha** [rancher/rancher#5858] opened 2016-08-31 17:47 UTC
**Rancher Version:** `1.0.1`

**Docker Version:** `1.10.3`

**OS and where are the hosts located? (cloud, bare metal, etc):** `CoreOS 1068.8.0`

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)** `Single node`

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)** `Cattle`

**Steps to Reproduce:**

Create some services in a stack.

**Results:** 

Sometimes the container picks up the Rancher service name and sometimes it just uses the hash.

![image](https://cloud.githubusercontent.com/assets/1039098/18139878/169399e8-6f68-11e6-8e94-39ef0dfe1d59.png)

**Expected:**

It would be nice to see the container named as the service name.

**Comment by willseward** [comment] 2016-08-31 19:24
I can confirm this for: 

__Rancher__: 1.1.3
__OS__: Ubuntu 16.04/14.04 and RHEL 7
__Docker__: 1.11.2 and 1.12.1, respectively

**Comment by deniseschannon** [comment] 2016-09-23 02:22
Duplicate of https://github.com/rancher/rancher/issues/5329

**Closed by deniseschannon** 2016-09-23 02:22 UTC
