### ISSUE TITLE
Only users with administrator permissions are allowed to refresh the catalog.

### ISSUE THREAD

**Issue by kingsd041** [rancher/rancher#27327] opened 2020-05-29 05:30 UTC
**What kind of request is this (question/bug/enhancement/feature request):**
bug

**Steps to reproduce (least amount of steps as possible):**
1. Add users and grant standard user permissions
2. Add users to project members and grant Owner permissions
3. Login to rancher as a new user and navigate to project-level apps
4. Click `Refresh` to refresh the catalog

**Result:**

Refresh failure

![image](https://user-images.githubusercontent.com/19684717/83224227-7acfaa00-a1af-11ea-8e35-0f945cb0e50e.png)

Grant the user administrator permissions, new users can refresh the catalog

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI):
2.4.3 or 2.3.7
- Installation option (single install/HA):
single

gz#10457

**Comment by laurent-r** [comment] 2020-06-25 14:17
Same as #26554 ?

**Comment by cbron** [comment] 2020-06-25 22:08
Project owners can only refresh catalogs for projects they are owners of. They cannot refresh or edit cluster, global, or _all_ project catalogs. So for example project owners have access to: `/v3/projectCatalogs/<my_project:a_catalog>?action=refresh`, but not `/v3/projectCatalogs/?action=refresh`.

**Comment by aaronRancher** [comment] 2021-03-15 23:34
The bug is reproduced with Rancher server `rancher\rancher:v2.4.3` and `rancher\rancher:v2.5.6`

Steps:
1. Launch a cluster.
2. Add a standard user from global view.
3. Create a new project and add the standard user as an owner.
4. Log in as standard user.
5. Navigate to Cluster > Project > Apps > Launch > Refresh

Result:
User is unable to refresh the catalog.
![Screen Shot 2021-03-15 at 4 10 49 PM](https://user-images.githubusercontent.com/57409052/111233537-675cc680-85aa-11eb-8495-d81eb582fcdd.png)

**Comment by rawmind0** [comment] 2021-03-16 16:06
May be i'm missing something, but i'm not fully understanding this issue. Other users than administrators are allowed to refresh catalogs. 

Due to security reasons, standard and/or basic user global roles are not providing catalog management permissions. Depending on the scope, catalog management permissions are provided by :
- global role `Manage Catalogs`
- cluster role `Manage Cluster Catalogs`
- project role `Manage Project Catalogs`

> 1. Add users and grant standard user permissions

> 2. Add a standard user from global view.

What does these exactly mean?? Are you just binding `User` global role to the user?? Are you also binding `Manage Catalogs` global role to the user but it's not working properly?? If not , have you consider to include `Manage Catalogs` global role as `Default role for new users` ??

 I've made some tests on Rancher v2.4.x and v2.5.6 and is working fine to me. User with global role `User` and:
- global role `Manage Catalogs`: can edit and refresh only global catalogs
- cluster role `Manage Cluster Catalogs` as cluster member: can edit and refresh only cluster catalogs
- project `Manage Project Catalogs` as project member: can edit and refresh only project catalogs, taking into account what @cbron  mentioned [here](https://github.com/rancher/rancher/issues/27327#issuecomment-649842320). Project catalogs can be properly refreshed from UI "Cluster" -> "Project" -> "Tools" -> "Catalogs"

Doing a proper mix of these roles, a standard user should be able to edit and refresh all scope catalogs. 

Could you please provide more information to clarify what is exactly requested here??

**Comment by deniseschannon** [comment] 2021-03-16 18:07
Standard users are unable to refresh the global catalog due to a design change around securing read only users to not be able to perform any non-read only actions, which has removed the ability to allow standard users to refresh catalogs unless specifically granted permissions to manage the catalogs.  

As described above you can refresh catalogs if given manage permissions for the type of catalog you want. 

Another workaround could be to create the same catalog as a project level catalog in order to refresh at the project level for project owners.

Please note that all catalogs refresh within 5 min without manual intervention. 

This is a won't fix as it's based on design.

**Closed by deniseschannon** 2021-03-16 18:07 UTC
Labels: QA/XS, [zube]: Working, internal
