### ISSUE TITLE
Bind-Mount Workload Volumes with Custom Sub Path Do Not Mount

### ISSUE THREAD

**Issue by RonWilliams** [rancher/rancher#16526] opened 2018-11-09 20:13 UTC
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
Create a Bind-Mount Volume with a path on node and use a sub path in volume. 

**Result:**
Volume will not Bind-Mount to host. 

**Other details that may be helpful:**
Screenshot of UI
![Working and Non-Working Bind Mount Configuration from Rancher UI](https://user-images.githubusercontent.com/2753036/48285887-30e27000-e421-11e8-9c72-f58df669cba3.png)

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): Rancher v 2.1.1
- Installation option (single install/HA): Single Install

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): Hosted, On-Prem
- Machine type (cloud/VM/metal) and specifications (CPU/memory): VM 4 CPU/ 16GB RAM
- Kubernetes version (use `kubectl version`):

```
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.5", GitCommit:"32ac1c9073b132b8ba18aa830f46b77dcceb0723", GitTreeState:"clean", BuildDate:"2018-06-21T11:46:00Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.3", GitCommit:"a4529464e4629c21224b3d52edfe0ea91b072862", GitTreeState:"clean", BuildDate:"2018-09-09T17:53:03Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}
```

- Docker (use `docker info`):

```
[root@rancherworkr nas]# docker info
Containers: 49
 Running: 37
 Paused: 0
 Stopped: 12
Images: 24
Server Version: 1.13.1
Storage Driver: overlay2
 Backing Filesystem: xfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: journald
Cgroup Driver: systemd
Plugins: 
 Volume: local
 Network: bridge host macvlan null overlay
 Authorization: rhel-push-plugin
Swarm: inactive
Runtimes: docker-runc runc
Default Runtime: docker-runc
Init Binary: /usr/libexec/docker/docker-init-current
containerd version:  (expected: aa8187dbd3b7ad67d8e5e3a15115d3eef43a7ed1)
runc version: 5eda6f6fd0c2884c2c8e78a6e7119e8d0ecedb77 (expected: 9df8b306d01f59d3a8029be411de015b7304dd8f)
init version: fec3683b971d9c3ef73f284f176672c44b448662 (expected: 949e6facb77383876aeff8a6944dde66b3089574)
Security Options:
 seccomp
  WARNING: You're not using the default seccomp profile
  Profile: /etc/docker/seccomp.json
Kernel Version: 3.10.0-862.11.6.el7.x86_64
Operating System: Red Hat Enterprise Linux Server 7.5 (Maipo)
OSType: linux
Architecture: x86_64
Number of Docker Hooks: 3
CPUs: 2
Total Memory: 7.779 GiB
Name: rancherworkr
ID: CTRW:6EJ2:WXHO:DAWP:YGC4:QCVE:KIR6:WBUX:7QAD:GDOV:6TAF:VJR2
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://registry.access.redhat.com/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
Registries: registry.access.redhat.com (secure), docker.io (secure)
```

**Comment by Oats87** [comment] 2018-11-10 00:56
This is a known issue in Kubernetes when running the Kubelet within a container. Please see https://github.com/rancher/rancher/issues/14836 for reference.

I will not close this ticket yet to see if we can come up with a workaround for this.

**Comment by sjkeerthi** [comment] 2018-12-18 13:17
Still the Issue seems to exists On Rancher 2.1.3 along with Kubernetes 1.11.5

**Comment by deniseschannon** [comment] 2019-05-09 02:55
Duplicate of #14836

**Closed by deniseschannon** 2019-05-09 02:55 UTC
Labels: area/storage, status/discussion
