### ISSUE TITLE
kubelets failing to start when using 'aws' as cloud provider

### ISSUE THREAD

**Issue by aemneina** [rancher/rancher#7829] opened 2017-02-15 16:12 UTC
**Rancher Versions:**
Server: 1.3.4
applicable): 1.5.1

**Docker Version:**
1.12.6

**OS and where are the hosts located? (cloud, bare metal, etc):**
ubuntu 16.04 in ec2

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Kubernetes template edited to use aws as cloud provider

**Steps to Reproduce:**
add hosts

**Results:** 
kubelet throwing these errors:
```
2/14/2017 8:28:54 PM+ exec kubelet --kubeconfig=/etc/kubernetes/ssl/kubeconfig --api_servers=https://kubernetes.kubernetes.rancher.internal:6443 --allow-privileged=true --register-node=true --cloud-provider=aws --healthz-bind-address=0.0.0.0 --cluster-dns=10.43.0.10 --cluster-domain=cluster.local --network-plugin=cni --network-plugin-dir=/etc/cni/managed.d --hostname-override ae-k8s-uw-1
2/14/2017 8:28:54 PMFlag --api-servers has been deprecated, Use --kubeconfig instead. Will be removed in a future version.
2/14/2017 8:28:54 PMI0215 04:28:54.614288    6948 feature_gate.go:181] feature gates: map[]
2/14/2017 8:28:54 PMI0215 04:28:54.614393    6948 aws.go:746] Building AWS cloudprovider
2/14/2017 8:28:54 PMI0215 04:28:54.614530    6948 aws.go:700] Zone not specified in configuration file; querying AWS metadata service
2/14/2017 8:28:54 PMerror: failed to run Kubelet: could not init cloud provider "aws": error finding instance i-09745770d13a96f20: error listing AWS instances: NoCredentialProviders: no valid providers in chain
```

**Comment by alena1108** [comment] 2017-02-15 17:59
@nrvale0 looks like IAM permissions are not set, right?

**Comment by nrvale0** [comment] 2017-02-15 18:02
@alena1108 That's not an error message I've seen before and doesn't appear to be related to the various permission setups required for EBS, ELB, S3. 

If I were to guess, it looks to me like client library trying to talk to AWS API does not have AWS_ZONE set along with AWS_REGION. But that's just a first guess.

**Comment by wlan0** [comment] 2017-02-17 18:28
@aemneina 

Can you ensure that the following permissions were set for the AWS hosts - 
```
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Effect": "Allow",
      "Action": "s3:*",
      "Resource": [
        "arn:aws:s3:::kubernetes-*"
      ]
    },
    {
      "Effect": "Allow",
      "Action": "ec2:Describe*",
      "Resource": "*"
    },
    {
      "Effect": "Allow",
      "Action": "ec2:AttachVolume",
      "Resource": "*"
    },
    {
      "Effect": "Allow",
      "Action": "ec2:DetachVolume",
      "Resource": "*"
    },
    {
      "Effect": "Allow",
      "Action": ["ec2:*"],
      "Resource": ["*"]
    },
    {
      "Effect": "Allow",
      "Action": ["elasticloadbalancing:*"],
      "Resource": ["*"]
    }  ]
}
```

**Comment by alena1108** [comment] 2017-02-21 17:44
Closing as duplicate of https://github.com/rancher/rancher/issues/7455

**Closed by alena1108** 2017-02-21 17:44 UTC
Labels: area/kubernetes, kind/bug
