### ISSUE TITLE
Exec shell on pods does not work

### ISSUE THREAD

**Issue by sowmyav27** [rancher/rancher#34044] opened 2021-08-07 19:03 UTC
**Rancher Server Setup**
- Rancher version: 2.6.0-rc1
- Installation option (Docker install/Helm Chart): HELM
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): RKE1
- Proxy/Cert Details: Rancher generated

**Information about the Cluster**
- Kubernetes version: Downstream - 1.21.3 custom windows, 1.20.9 Imported RKE1

**Describe the bug**
Exec shell on pods does not work

**To Reproduce**
(This is an upgraded setup)

- On 2.5.9 deploy a couple of downstream clusters - Imported RKE1 and windows custom clusters
- Deploy workloads in a project/namespace on both clusters
- Upgrade from 2.5.9 to 2.6.0-rc1
- On 2.6.0rc1
- Deploy a project/namespace
- deploy a workload
- User is not able to exec into the pod. says disconnected. In Ember ui 1006 error code is seen (Admin user)

**Comment by thehejik** [comment] 2021-08-12 14:58
I was unable to reproduce this issue, no trace of `Disconnected` message, the shell was running on both clusters after upgrade from 2.5.9 to 2.6.0-rc1(+rc2).

Only problem was that on `rancher:2.5.9` the WebSocket was not ready on local cluster after local cluster deployment so I had to wait a bit but it was up and running after a few min (and the shell did not run before that - just Disconnected message, once the ws initialized it was ok)

**Local cluster:**
• deployed local RKE1 cluster with k8s `1.20.9-rancher1-1` with `rke-v1.2.11` binary (one node all roles)
• `rancher:2.5.9` installed by helm on the rke1 cluster

**Added 2 downstream clusters:**
• Imported - provisioned RKE1 cluster (one node all roles) with k8s `1.20.9-rancher1-1` with `rke-v1.2.11` binary, imported by reg. command
• Custom Win - provisioned RKE1 windows cluster (1 linux-etcd, 1 linux-cp, 1 linux-worker, 3 windows workers) with k8s `1.20.9-rancher1-1` using windows 2019 updated 07.14.21 `ami-05a418fd6eb36fd5b` (provisioned from CI)

**On both downstream clusters created a testing workload (on rancher:2.5.9 + k8s 1.20.9):**
• created a namespace `testing` and deployed a Deployment with `nginx:alpine` on Imported Linux cluster and `ranchertest/testnginx:windows` on windows cluster
• the shell didn't run when pressed `Execute Shell` from Cluster Explorer on windows cluster (but worked in Ember) - filed https://github.com/rancher/rancher/issues/34197 for 2.5.10 milestone
• the shell worked ok on the imported Linux cluster

**Performed rancher upgrade by helm to `rancher:2.6.0-rc1`:**
• the shell started to work even on the Windows Cluster what didn't work on rancher:2.5.9, worked also on the imported windows cluster (deployment created on 2.5.9)
• created a similar deployment by using the same images this time on rancher:2.6.0-rc1 
• Windows cluster updated from k8s `1.20.9-rancher1-1` to `1.21.3-rancher1-1`
• again successfully validated that the Shell works

Performed another update to `rancher:2.6.0-rc2`, the shell still worked on both clusters in Vue and Ember UIs.

Imported RKE1
![shell_imported](https://user-images.githubusercontent.com/12828077/129219215-8708fb77-5a62-4c04-95e7-cdadafb3927e.png)

Custom Windows RKE1
![shell_windows](https://user-images.githubusercontent.com/12828077/129219222-8b0a93d2-e366-4779-ab13-91ae67540cd4.png)

**Comment by thehejik** [comment] 2021-08-12 15:31
Closing as fixed.

**Closed by thehejik** 2021-08-12 15:31 UTC
Labels: kind/bug-qa, [zube]: QA Working, status/release-blocker, area/upgrade

**Comment by zhaobei** [comment] 2021-12-09 11:46
I'm on 2.6.2 The same problem was encountered 
![image](https://user-images.githubusercontent.com/55879962/145390785-d7e1fbbc-72c5-42b6-8c8c-a5cad1ee6371.png)
Such problems will not occur in administrators, but as ordinary users
