### ISSUE TITLE
[BUG] Replacing controlplane nodes in RKE Node Driver cluster, with nodes in a cordoned state, results in a broken cluster with unavailable worker nodes

### ISSUE THREAD

**Issue by sbstp** [rancher/rancher#40740] opened 2023-03-01 19:24 UTC
**Rancher Server Setup**
- Rancher version: 2.6.9

**Information about the Cluster**
- Kubernetes version: any
- Cluster Type (Local/Downstream): Downstream
   - created on digital ocean nodes using RKE1 driver

**User Information**
- What is the role of the user logged in? admin

**Describe the bug**

If you replace the controlplane nodes in an RKE Node Driver cluster, where the count of cordoned nodes >= max_unavailable_worker count, the controlplane nodes are replaced, but the worker nodes are not updated. As a result the nginx-proxy on the worker nodes references the old (now removed) controlplane nodes and the worker nodes become unavailable. 

**To Reproduce**

* Create 2 node pools, one with 4 worker nodes and one with 1 control plane/etcd node.
* Cordon 2 of the nodes in the worker pool
* Add a node in the control plane pool, once that node is ready you should see something like `[ERROR] error syncing 'c-5wbmg/upgrade_': handler rke-worker-upgrader: cluster [c-5wbmg] worker-upgrade: more than allowed nodes upgrading for cluster: unavailable 2 maxUnavailable 1, requeuing` in the logs
* Finally remove the original node from the control plane pool.

**Result**
Once the node is removed, all the worker nodes will get disconnected from the cluster because the nginx-proxy references the removed node.

**Expected Result**
The worker nodes should reference the new control plane node.

**Screenshots**

![image](https://user-images.githubusercontent.com/862368/222241554-2d7e550a-d30d-48bf-8522-01e986f57694.png)

**Additional context**

SURE-5712

**Comment by jiaqiluo** [comment] 2024-02-15 02:36
The bug is reproduced in Rancher v.2.8.1, node-driver RKE1 cluster v1.27.10 

All steps are the same as the issue, except that I added the 2nd etcd+cp node in a new node pool, and then deleted the original node pool for the 1st etcd+cp node. 

Only the worker3 node is active because the node plan v2 is applied, the only changes in the node plan v2, compared with v1, is the value of the `CP_HOST` arg & env being the IP of the new CP node.

Rancher logs show that at the time of processing the node `m-worker3`, it is the only entry in the `notReady` list, so the count of `notReady` nodes is not greater than the maxUnavailable, therefore `m-worker3` got updated ([code](https://github.com/rancher/rancher/blob/871b6d9137246bd93733f01184ea435f40c5d56c/pkg/controllers/management/rkeworkerupgrader/upgrade.go#L314-L335)).

```
2024/02/15 01:17:45 [INFO] cluster [c-gk88t] worker-upgrade: call upgrade to reconcile for node [m-worker1]
2024/02/15 01:17:45 [DEBUG] cluster [c-gk88t] worker-upgrade: node [m-zkhr4] is not a workerOnly node
2024/02/15 01:17:45 [DEBUG] cluster [c-gk88t] worker-upgrade: workerNodeInfo: nodes 4 maxAllowed 1 upgrading 2 notReady [] toProcess [  m-worker1 m-worker2] toPrepare [  m-worker4 m-worker3] done [] toUncordon []
2024/02/15 01:17:45 [ERROR] error syncing 'c-gk88t/m-worker1': handler rke-worker-upgrader: cluster [c-gk88t] worker-upgrade: more than allowed nodes upgrading for cluster: unavailable 2 maxUnavailable 1, requeuing

2024/02/15 01:18:06 [INFO] cluster [c-gk88t] worker-upgrade: call upgrade to reconcile for node [m-worker3]
2024/02/15 01:18:06 [DEBUG] cluster [c-gk88t] worker-upgrade: node [m-worker3] is not ready
2024/02/15 01:18:06 [DEBUG] cluster [c-gk88t] worker-upgrade: node [m-zkhr4] is not a workerOnly node
2024/02/15 01:18:06 [DEBUG] cluster [c-gk88t] worker-upgrade: workerNodeInfo: nodes 4 maxAllowed 1 upgrading 2 notReady [ m-worker3] toProcess [  m-worker1 m-worker2] toPrepare [ m-worker4] done [] toUncordon []

2024/02/15 01:18:06 [INFO] cluster [c-gk88t] worker-upgrade: call upgrade to reconcile for node [m-worker4]
2024/02/15 01:18:06 [INFO] cluster [c-gk88t] worker-upgrade: updated upgrading unavailable node [m-worker3] with version 2
2024/02/15 01:18:06 [DEBUG] cluster [c-gk88t] worker-upgrade: node [m-worker1] is not ready
2024/02/15 01:18:06 [DEBUG] cluster [c-gk88t] worker-upgrade: node [m-worker3] is not ready
2024/02/15 01:18:06 [DEBUG] cluster [c-gk88t] worker-upgrade: node [m-worker4] is not ready
2024/02/15 01:18:06 [DEBUG] cluster [c-gk88t] worker-upgrade: node [m-zkhr4] is not a workerOnly node
2024/02/15 01:18:06 [DEBUG] cluster [c-gk88t] worker-upgrade: workerNodeInfo: nodes 4 maxAllowed 1 upgrading 1 notReady [   m-worker4 m-worker1 m-worker3] toProcess [ m-worker2] toPrepare [] done [] toUncordon []
2024/02/15 01:18:06 [ERROR] error syncing 'c-gk88t/m-worker3': handler rke-worker-upgrader: cluster [c-gk88t] worker-upgrade: more than allowed nodes upgrading for cluster: unavailable 3 maxUnavailable 1, requeuing

2024/02/15 01:18:21 [INFO] cluster [c-gk88t] worker-upgrade: call upgrade to reconcile for node [m-worker3]
2024/02/15 01:18:21 [DEBUG] cluster [c-gk88t] upgrading condition: [true] plan changed: [false]
2024/02/15 01:18:21 [DEBUG] cluster [c-gk88t] worker-upgrade cluster status node version [2]
2024/02/15 01:18:21 [DEBUG] cluster [c-gk88t] worker-upgrade: node [m-worker1] is not ready
2024/02/15 01:18:21 [DEBUG] cluster [c-gk88t] worker-upgrade: node [m-worker2] is not ready
2024/02/15 01:18:21 [DEBUG] cluster [c-gk88t] worker-upgrade: node [m-worker3] is done
2024/02/15 01:18:21 [DEBUG] cluster [c-gk88t] worker-upgrade: node [m-worker4] is not ready
2024/02/15 01:18:21 [DEBUG] cluster [c-gk88t] worker-upgrade: node [m-zkhr4] is not a workerOnly node
2024/02/15 01:18:21 [DEBUG] cluster [c-gk88t] worker-upgrade: workerNodeInfo: nodes 4 maxAllowed 1 upgrading 0 notReady [   m-worker4 m-worker1 m-worker2] toProcess [] toPrepare [] done [] toUncordon []
```



Screenshot:
![40740-repruduce](https://github.com/rancher/rancher/assets/6218999/2612ea03-43a4-4626-badb-92b7ce4a80dc)

**Comment by jiaqiluo** [comment] 2024-02-21 00:53
It turns out to be the expected behavior in this particular scenario. 

### What happens to the cluster after adding the 2nd control plane node? 

At first, we add a 2nd controlPlane+etcd node to the cluster. After the node becomes active, Rancher starts the process of upgrading worker nodes. 
Because there are 2 nodes cordoned, and the maxUnavailableWorker value is 1 which is calculated by the default 10% multiples the number of worker nodes 4, **the cluster is stuck in the upgrading status and never becomes active**. 

The following error messages in Rancher logs indicate that Rancher can not upgrade any worker node:
```
2024/02/20 15:28:11 [ERROR] error syncing 'c-pcr6n/upgrade_': handler rke-worker-upgrader: cluster [c-pcr6n] worker-upgrade: more than allowed nodes upgrading for the cluster: unavailable 2 maxUnavailable 1, requeuing
2024/02/20 15:39:12 [ERROR] error syncing 'c-pcr6n/m-gv78z': handler rke-worker-upgrader: cluster [c-pcr6n] worker-upgrade: more than allowed nodes upgrading for cluster: unavailable 2 maxUnavailable 1, requeuing
```

#### why all worker nodes are in the active status?

It is because none of them go into the upgrading process, and they all connect to the 1st control plane nodes so the connection between kubelet in the worker nodes and the control plane node is healthy.

the screenshot  shows the cluster is in the upgrading status and all nodes are active: 
![screencapture-moral-reasonably-sailfish-ngrok-free-app-dashboard-c-manager-provisioning-cattle-io-cluster-fleet-default-c-pcr6n-2024-02-20-17_33_34](https://github.com/rancher/rancher/assets/6218999/a529c703-8406-4711-adbf-99e1fc1fc6ae)


### What happens to the cluster after removing the 1st control plane node? 

Then, we remove the 1st control plane node. Notice that the cluster is currently stuck in the upgrading status.  Soon 3 of 4 worker nodes become unavailable with the message "Kubelet stopped posting node". It is expected to happen simply because the kubelet in them has only the connection to the 1st control plane node which is removed from the cluster. 

####  Why there is one active worker node that finishes the upgrade? 

This is related to how Rancher works:
Rancher runs a controller to upgrade worker nodes, and the controller keeps processing all worker nodes one by one unstoppably. Rancher treats the worker node whose condition `Ready` is not `true` as a `notReady` node ([code](https://github.com/rancher/rancher/blob/27a381bdcb70f33f22408940bc617f078f6f3835/pkg/controllers/management/rkeworkerupgrader/node.go#L150)). There are many reasons for a node to become not ready, one of those could be a broken node plan that Rancher sends to the node. So to eliminate this possible failure and also not violate the limit of max unavailable worker nodes, Rancher will send the new node plan to the `notReady` node(s) if the number of notReady nodes does not exceed the above limit ([code](https://github.com/rancher/rancher/blob/27a381bdcb70f33f22408940bc617f078f6f3835/pkg/controllers/management/rkeworkerupgrader/upgrade.go#L314-L335)). This happens before Rancher checks the actual number of unavailable nodes which is a combination of notReady node(s) and node(s) during the upgrading ([code](https://github.com/rancher/rancher/blob/27a381bdcb70f33f22408940bc617f078f6f3835/pkg/controllers/management/rkeworkerupgrader/upgrade.go#L337-L342)). 

It does not happen at the same time for all worker nodes to become unavailable, one possible reason can be the network delay, so there is a moment when Rancher tries to upgrade one particular node, that node is the only one `notReady` node, so Rancher goes ahead to send the new node plan to the node; at the next step, Rnacher checks the number of unavailable nodes, the count turns out to be 3 (1 `notRready` node and 2 condoned nodes), so Rancher returns the error saying that more than allowed nodes are upgrading for the cluster.  That one worker node receives and applies the new node plan which contains the IP address of the 2nd control plan nodes, therefore, its kubelet can talk to the cluster and therefore becomes active and upgraded. 


The following Rancher logs indicate`m-6j5kd` is the only `notReady` node, so send the new node plan (version 2) to it:
```
2024/02/20 17:37:28 [INFO] cluster [c-pcr6n] worker-upgrade: call upgrade to reconcile for node [m-6j5kd]
2024/02/20 17:37:28 [DEBUG] cluster [c-pcr6n] worker-upgrade: workerNodeInfo: nodes 4 maxAllowed 1 upgrading 1 notReady [ m-6j5kd] toProcess [ m-8sn6b] toPrepare [  m-cjk6t m-l8grn] done [] toUncordon []
2024/02/20 17:37:28 [INFO] cluster [c-pcr6n] worker-upgrade: updated upgrading unavailable node [m-6j5kd] with version 2
```

The screenshot shows the cluster is in the upgrading status, and only one node is active:
![screencapture-moral-reasonably-sailfish-ngrok-free-app-dashboard-c-manager-provisioning-cattle-io-cluster-fleet-default-c-pcr6n-2024-02-20-17_41_17](https://github.com/rancher/rancher/assets/6218999/759ada21-b033-4294-8489-f501fff1b039)


### Workarounds and Suggestions 

The workaround is to Increase the `max_unavailable_worker` before the node replacement or when the issue is encountered. 

It is strongly recommended to not remove the original control plane node from a cluster especially when the cluster is stuck in the upgrading status, doing so may cause data loss and result in a broken cluster. 

### Workarounds and Suggestions 
The number of cordoned nodes should be considered when setting a proper  `max_unavailable_worker` value in the cluster.

**Comment by snasovich** [comment] 2024-05-22 03:01
Closing as "Working as Expected"

**Closed by snasovich** 2024-05-22 03:01 UTC
Labels: kind/bug, priority/0, internal, area/provisioning-rke1, team/hostbusters, JIRA
