### ISSUE TITLE
Logging v2 - Syslog output with UDP not working

### ISSUE THREAD

**Issue by SheilaghM** [rancher/rancher#35197] opened 2021-10-19 21:59 UTC
SURE-3452

**Rancher Server Setup**
Rancher Cluster:
Rancher version: v2.5.9
Number of nodes: 3
Node OS version: Ubuntu 18.04

Downstream Cluster:
Number of Downstream clusters: 1
Node OS: Ubuntu 18.04
RKE/RKE2/K3S version: RKE2
Kubernetes version: 1.20.8
CNI: canal

Other:
Underlying Infrastructure: VMWare
Any 3rd party software installed on the nodes: No

**Describe the bug**
Logging v2 syslog output with UDP not working. After configuring UDP transport , there was no traffic observed on port 514.

**To Reproduce**
Install Logging with chart version 3.9.400
Install and configure rsyslog on a remote system
Enable log filtering by creating a file /etc/rsyslog.d/remote.conf with below content
 
$ModLoad imtcp.so         # load module
$InputTCPServerRun 514 # Starts a TCP server on selected port
$ModLoad imudp.so         # provides UDP syslog reception
$UDPServerRun 514         # start a UDP syslog server at standard port 514
$template RemoteLogs,"/var/log/remote/%HOSTNAME%/%PROGRAMNAME%.log"
*.* ?RemoteLogs& ~
 

Create a ClusterOutput
apiVersion: logging.banzaicloud.io/v1beta1
kind: ClusterOutput
metadata:
  name: demo-test
  namespace: cattle-logging-system
spec:
  syslog:
    buffer:
      timekey: 1m
      timekey_use_utc: true
      timekey_wait: 10s
    format:
      app_name_field: kubernetes.pod_name
      hostname_field: cluster
      log_field: message
    host: 192.168.110.174
    insecure: false
    port: 514
    transport: udp
Create a ClusterFlow 
 
apiVersion: logging.banzaicloud.io/v1beta1
kind: ClusterFlow
metadata:
  name: demo-flow
  namespace: cattle-logging-system
spec:
  filters:
  - record_transformer:
      records:
      - cluster: clsterX
  globalOutputRefs:
  - demo-test

**Result**
No logs were transferred.

**Expected Result**
Logs should be transferred to remote syslog.

**Additional context**
Workaround:
Is workararound available and implemented? yes
What is the workaround:

Replace the logging object's fluentd image with ghcr.io/banzaicloud/fluentd:v1.13.3-alpine-8 , it works fine with UDP.
(kubectl edit loggings.logging.banzaicloud.io rancher-logging)

Looks like below patch is missing and we need updated fluentd image or Logging operator.
https://github.com/cloudfoundry/fluent-plugin-syslog_rfc5424/pull/8/files

**Comment by stefanlasiewski** [comment] 2022-01-12 03:05
Is this a duplicate of https://github.com/rancher/rancher/issues/32144

**Comment by MKlimuszka** [comment] 2022-02-22 16:51
It looks like a recent fluentd image has solved this and we upgraded to the image elsewhere. I'll send this to QA for validation.

**Comment by ronhorton** [comment] 2022-02-25 16:44
**Pass** verified in `2.6-head Commit ID 8cc8121`
1. provisioned a syslog server
2. created a cluster output with server ip and port 514 / UDP
3. created a deployment on cluster 
4. tailed syslog on syslog server

`Logs flowed via UDP`

**Closed by ronhorton** 2022-02-25 16:44 UTC
Labels: internal, area/logging, [zube]: QA Working, team/area3, feature/charts-logging-v2
