### ISSUE TITLE
vSphere/ESXi 7.0 VM provisioning that requires modifying the VM properties fails (Ie adding devices)

### ISSUE THREAD

**Issue by DH-Rancher** [rancher/rancher#27732] opened 2020-06-25 13:50 UTC
**What kind of request is this (question/bug/enhancement/feature request):**

Bug

**Steps to reproduce (least amount of steps as possible):**

Create a vSphere node template containing multiple networks. Use this template to provision a cluster to a vSphere 7 & ESXi7 environment

**Result:**

The following is presented in vSphere and the node fails to provision. Note, single NIC nodes provision without issue.

![image](https://user-images.githubusercontent.com/57356014/85730982-062a5580-b6f2-11ea-8fe8-e616781e066d.png)

**Other details that may be helpful:**

Trace logs from Rancher (However, these don't add anything extra)

```
2020/06/25 12:40:52 [INFO] [node-controller-rancher-machine] (m1-1) Adding network: /Homelab/network/VDS-MGMT-DEFAULT
2020/06/25 12:40:52 [TRACE] REST UPDATE apis/management.cattle.io/v3/c-9nsw7/nodes/m-lwljm
2020/06/25 12:40:52 [DEBUG] stdout: (m1-1) Adding network: /Homelab/network/VDS-NEST-DEFAULT
2020/06/25 12:40:52 [INFO] [node-controller-rancher-machine] (m1-1) Adding network: /Homelab/network/VDS-NEST-DEFAULT
2020/06/25 12:40:52 [TRACE] REST UPDATE apis/management.cattle.io/v3/c-9nsw7/nodes/m-lwljm

2020/06/25 12:40:55 [TRACE] REST UPDATE apis/management.cattle.io/v3/c-9nsw7/nodes/m-lwljm
2020/06/25 12:40:55 [TRACE] NodeController calling handler rke-worker-upgrader c-9nsw7/m-lwljm
2020/06/25 12:40:55 [ERROR] NodeController c-9nsw7/m-lwljm [node-controller] failed with : Error creating machine: Error in driver during machine creation: A specified parameter was not correct: deviceChange[1].device.key
2020/06/25 12:40:55 [TRACE] NodeController calling handler cluster-provisioner-controller c-9nsw7/m-lwljm
2020/06/25 12:40:55 [TRACE] NodeController calling handler cluster-stats c-9nsw7/m-lwljm
2020/06/25 12:40:55 [TRACE] NodeController calling handler nodepool-provisioner c-9nsw7/m-lwljm
2020/06/25 12:40:55 [TRACE] NodeController calling handler node-controller c-9nsw7/m-lwljm
2020/06/25 12:40:55 [TRACE] NodeController calling handler rke-worker-upgrader c-9nsw7/m-lwljm
2020/06/25 12:40:55 [TRACE] NodeController c-9nsw7/m-lwljm completed with dropped err: [node-controller] failed with : Error
2020/06/25 12:40:55 [DEBUG] Triggering auth refresh on u-4r7xs
```
vCenter VPXD logs (Note the key as `-1` for both vNICs)
```
2020-06-25T13:20:04.116Z info vpxd[10851] [Originator@6876 sub=Default opID=97e94a2-01] [VpxLRO] -- ERROR lro-1115251 -- vm-8840 -- vim.VirtualMachine.reconfigure: vmodl.fault.InvalidArgument:
--> Result:
--> (vmodl.fault.InvalidArgument) {
-->    faultCause = (vmodl.MethodFault) null, 
-->    faultMessage = (vmodl.LocalizableMessage) [
-->       (vmodl.LocalizableMessage) {
-->          key = "com.vmware.vim.vpxd.vmprov.duplicateDeviceKey", 
-->          arg = <unset>, 
-->          message = <unset>
-->       }
-->    ], 
-->    invalidProperty = "deviceChange[1].device.key"
-->    msg = ""
--> }
--> Args:
--> 
--> Arg spec:
--> (vim.vm.ConfigSpec) {
-->    changeVersion = <unset>, 
-->    name = <unset>, 
-->    version = <unset>, 
-->    createDate = "2020-06-25T13:20:00.543008Z", 
-->    uuid = <unset>, 
-->    instanceUuid = <unset>, 
-->    npivNodeWorldWideName = <unset>, 
-->    npivPortWorldWideName = <unset>, 
-->    npivWorldWideNameType = <unset>, 
-->    npivDesiredNodeWwns = <unset>, 
-->    npivDesiredPortWwns = <unset>, 
-->    npivTemporaryDisabled = <unset>, 
-->    npivOnNonRdmDisks = <unset>, 
-->    npivWorldWideNameOp = <unset>, 
-->    locationId = <unset>, 
-->    guestId = <unset>, 
-->    alternateGuestName = <unset>, 
-->    annotation = <unset>, 
-->    files = (vim.vm.FileInfo) null, 
-->    tools = (vim.vm.ToolsConfigInfo) null, 
-->    flags = (vim.vm.FlagInfo) null, 
-->    consolePreferences = (vim.vm.ConsolePreferences) null, 
-->    powerOpInfo = (vim.vm.DefaultPowerOpInfo) null, 
-->    numCPUs = <unset>, 
-->    vcpuConfig = <unset>, 
-->    numCoresPerSocket = <unset>, 
-->    autoCoresPerSocket = <unset>, 
-->    memoryMB = <unset>, 
-->    memoryHotAddEnabled = <unset>, 
-->    cpuHotAddEnabled = <unset>, 
-->    cpuHotRemoveEnabled = <unset>, 
-->    virtualICH7MPresent = <unset>, 
-->    virtualSMCPresent = <unset>, 
-->    deviceChange = (vim.vm.device.VirtualDeviceSpec) [
-->       (vim.vm.device.VirtualDeviceSpec) {
-->          operation = "add", 
-->          fileOperation = <unset>, 
-->          device = (vim.vm.device.VirtualVmxnet3) {
-->             dynamicProperty = <unset>, 
-->             key = -1, 
-->             deviceInfo = (vim.Description) null, 
-->             backing = (vim.vm.device.VirtualEthernetCard.DistributedVirtualPortBackingInfo) {
-->                port = (vim.dvs.PortConnection) {
-->                   switchUuid = "50 3b f7 94 0f 8f 73 20-24 0f a4 38 2b 85 b7 c9", 
-->                   portgroupKey = "dvportgroup-27", 
-->                   portKey = <unset>, 
-->                   connectionCookie = <unset>
-->                }
-->             }, 
-->             connectable = (vim.vm.device.VirtualDevice.ConnectInfo) null, 
-->             slotInfo = (vim.vm.device.VirtualDevice.BusSlotInfo) null, 
-->             controllerKey = <unset>, 
-->             unitNumber = <unset>, 
-->             addressType = <unset>, 
-->             macAddress = <unset>, 
-->             wakeOnLanEnabled = <unset>, 
-->             resourceAllocation = (vim.vm.device.VirtualEthernetCard.ResourceAllocation) null, 
-->             externalId = <unset>, 
-->             uptCompatibilityEnabled = <unset>
-->          }, 
-->          profile = <unset>, 
-->          backing = (vim.vm.device.VirtualDeviceSpec.BackingSpec) null
-->       }, 
-->       (vim.vm.device.VirtualDeviceSpec) {
-->          operation = "add", 
-->          fileOperation = <unset>, 
-->          device = (vim.vm.device.VirtualVmxnet3) {
-->             dynamicProperty = <unset>, 
-->             key = -1, 
-->             deviceInfo = (vim.Description) null, 
-->             backing = (vim.vm.device.VirtualEthernetCard.DistributedVirtualPortBackingInfo) {
-->                port = (vim.dvs.PortConnection) {
-->                   switchUuid = "50 3b f7 94 0f 8f 73 20-24 0f a4 38 2b 85 b7 c9", 
-->                   portgroupKey = "dvportgroup-48", 
-->                   portKey = <unset>, 
-->                   connectionCookie = <unset>
-->                }
-->             }, 
-->             connectable = (vim.vm.device.VirtualDevice.ConnectInfo) null, 
-->             slotInfo = (vim.vm.device.VirtualDevice.BusSlotInfo) null, 
-->             controllerKey = <unset>, 
-->             unitNumber = <unset>, 
-->             addressType = <unset>, 
-->             macAddress = <unset>, 
-->             wakeOnLanEnabled = <unset>, 
-->             resourceAllocation = (vim.vm.device.VirtualEthernetCard.ResourceAllocation) null, 
-->             externalId = <unset>, 
-->             uptCompatibilityEnabled = <unset>
-->          }, 
-->          profile = <unset>, 
-->          backing = (vim.vm.device.VirtualDeviceSpec.BackingSpec) null
-->       }
-->    ], 
-->    cpuAllocation = (vim.ResourceAllocationInfo) null, 
-->    memoryAllocation = (vim.ResourceAllocationInfo) null, 
-->    latencySensitivity = (vim.LatencySensitivity) null, 
-->    cpuAffinity = (vim.vm.AffinityInfo) null, 
-->    memoryAffinity = (vim.vm.AffinityInfo) null, 
-->    networkShaper = (vim.vm.NetworkShaperInfo) null, 
-->    cpuFeatureMask = <unset>, 
-->    extraConfig = <unset>, 
-->    swapPlacement = <unset>, 
-->    bootOptions = (vim.vm.BootOptions) null, 
-->    vAppConfig = (vim.vApp.VmConfigSpec) null, 
-->    ftInfo = (vim.vm.FaultToleranceConfigInfo) null, 
-->    repConfig = (vim.vm.ReplicationConfigSpec) null, 
-->    vAppConfigRemoved = <unset>, 
-->    vAssertsEnabled = <unset>, 
-->    changeTrackingEnabled = <unset>, 
-->    firmware = <unset>, 
-->    maxMksConnections = <unset>, 
-->    guestAutoLockEnabled = <unset>, 
-->    managedBy = (vim.ext.ManagedByInfo) null, 
-->    memoryReservationLockedToMax = true, 
-->    nestedHVEnabled = <unset>, 
-->    vPMCEnabled = <unset>, 
-->    scheduledHardwareUpgradeInfo = (vim.vm.ScheduledHardwareUpgradeInfo) null, 
-->    vmProfile = <unset>, 
-->    messageBusTunnelEnabled = <unset>, 
-->    crypto = (vim.encryption.CryptoSpec) null, 
-->    migrateEncryption = <unset>, 
-->    sgxInfo = (vim.vm.SgxInfo) null, 
-->    ftEncryptionMode = <unset>, 
-->    guestMonitoringModeInfo = (vim.vm.GuestMonitoringModeInfo) null
--> }
2020-06-25T13:20:04.116Z info vpxd[10851] [Originator@6876 sub=vpxLro opID=97e94a2] [VpxLRO] -- FINISH task-3072
2020-06-25T13:20:04.116Z info vpxd[10851] [Originator@6876 sub=Default opID=97e94a2] [VpxLRO] -- ERROR task-3072 -- vm-8840 -- vim.VirtualMachine.reconfigure: vmodl.fault.InvalidArgument:
--> Result:
--> (vmodl.fault.InvalidArgument) {
-->    faultCause = (vmodl.MethodFault) null, 
-->    faultMessage = (vmodl.LocalizableMessage) [
-->       (vmodl.LocalizableMessage) {
-->          key = "com.vmware.vim.vpxd.vmprov.duplicateDeviceKey", 
-->          arg = <unset>, 
-->          message = <unset>
-->       }
-->    ], 
-->    invalidProperty = "deviceChange[1].device.key"
-->    msg = ""
--> }
```

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI):
- Installation option (single install/HA):

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported):
- Machine type (cloud/VM/metal) and specifications (CPU/memory):
- Kubernetes version (use `kubectl version`):

```
vSphere IaaS
2vCPU 4GB Ram
N/A - Cluster does not provision
```

- Docker version (use `docker version`):

```
N/A - Cluster does not provision
```

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v2.4.3` UI: `v2.4.22` |
|Route|`undefined`|

**Comment by DH-Rancher** [comment] 2020-06-29 07:50
Possibly related: https://github.com/rancher/rancher/issues/25404

**Comment by albal** [comment] 2020-07-09 16:49
I also have the same problem with all the recent versions of Rancher include the latest as of today.  Tried with vCenter 7.0:
`A specified parameter was not correct: deviceChange[1].device.key Cannot add multiple devices using the same device key..`

**Comment by ipyker** [comment] 2020-08-06 11:13
> 我对Rancher的所有最新版本（包括今天的最新版本）也有同样的问题。尝试使用vCenter 7.0：
> `A specified parameter was not correct: deviceChange[1].device.key Cannot add multiple devices using the same device key..`

yeah，My situation is the same as you, using rancheros-vmware.iso to create a host template. Then vpshere creates a new cluster and reports the same error as you in vcenter。

**Comment by David-VTUK** [comment] 2020-08-20 12:17
@albal @ipyker 

Can you please post your node template configurations?

**Comment by albal** [comment] 2020-08-20 13:54
Here is my node template configuration:

`   

None

Not available

Not available


Not available


admin Log Out
{
"amazonec2Config": null,
"annotations": {
"ownerBindingsCreated": "true"
},
"baseType": "nodeTemplate",
"cloudCredentialId": "cattle-global-data:cc-567c5",
"created": "2020-06-30T10:45:12Z",
"createdTS": 1593513912000,
"creatorId": "user-b8ljz",
"driver": "vmwarevsphere",
"engineInstallURL": "https://releases.rancher.com/install-docker/19.03.sh",
"engineRegistryMirror": null,
"id": "cattle-global-nt:nt-pcs4v",
"labels": {
"cattle.io/creator": "norman"
},
"links": {
"nodePools": "…/v3/nodePools?nodeTemplateId=cattle-global-nt%3Ant-pcs4v",
"nodes": "…/v3/nodes?nodeTemplateId=cattle-global-nt%3Ant-pcs4v",
"self": "…/v3/nodeTemplates/cattle-global-nt:nt-pcs4v",
"update": "…/v3/nodeTemplates/cattle-global-nt:nt-pcs4v"
},
"name": "vCenter",
"principalId": "local://user-b8ljz",
"state": "active",
"transitioning": "no",
"transitioningMessage": "",
"type": "nodeTemplate",
"useInternalIpAddress": true,
"uuid": "c6c04403-babe-11ea-9ae4-0242ac110002",
"vmwarevsphereConfig": {
"boot2dockerUrl": "",
"cfgparam": [
"disk.enableUUID=TRUE"
],
"cloneFrom": "/TSEW/vm/Docker-Template",
"cloudConfig": "#cloud-config",
"cloudinit": "",
"contentLibrary": "",
"cpuCount": "4",
"creationType": "template",
"customAttribute": null,
"datacenter": "/TSEW",
"datastore": "/TSEW/datastore/HDD_RAID10",
"datastoreCluster": "",
"diskSize": "20000",
"folder": "/TSEW/vm/Kube",
"hostsystem": "/TSEW/host/Lab/192.168.0.10",
"memorySize": "8192",
"network": [
"/TSEW/network/10G"
],
"pool": "/TSEW/host/Lab/Resources",
"sshPassword": "tcuser",
"sshPort": "22",
"sshUser": "docker",
"sshUserGroup": "staff",
"tag": null,
"username": "",
"vappIpallocationpolicy": "fixedAllocated",
"vappIpprotocol": "IPv4",
"vappProperty": [ 5 items
"guestinfo.dns.servers=${dns:/TSEW/network/10G}",
"guestinfo.dns.domains=${searchPath:/TSEW/network/10G}",
"guestinfo.interface.0.ip.0.address=ip:/TSEW/network/10G",
"guestinfo.interface.0.ip.0.netmask=${netmask:/TSEW/network/10G}",
"guestinfo.interface.0.route.0.gateway=${gateway:/TSEW/network/10G}"
],
"vappTransport": "com.vmware.guestInfo",
"vcenter": "",
"vcenterPort": "443"
}
}`

**Comment by agepi477** [comment] 2020-08-28 11:15
Same issue here: 

I'm using rancher v2.4.5 and vCenter 7. 
The user I'm using in the Cloud Credentials has admin rights on the vSphere Cluster.
Using boot2docker with the rancheros image.
All information in the NodeTemplate seems to be valid.

When I create a cluster (single node with all roles) with the node template, rancher creates the virtual machine but is not able to add a network adapter and the CD Drive to mount the rancherOS image. Instead there is this error message popping out in vSphere: "A specified parameter was not correct: deviceChange[1].device.key Cannot add multiple devices using the same device key"

With rancher v2.3.2 and vSphere 6.5 it was working.

**Comment by agepi477** [comment] 2020-08-28 11:21
Here is my node template:
[nodetemplate.txt](https://github.com/rancher/rancher/files/5141763/nodetemplate.txt)

**Comment by albal** [comment] 2020-08-28 11:32
I can confirm v2.3.2 does not work with vSphere 7.0 either.

**Comment by DH-Rancher** [comment] 2020-08-28 13:12
In some circumstances, It works with Rancher 2.4.5 and vSphere 7. Where I currently see it fail is when:

* Multiple instances of a device type are added to a VM (ie multiple NICS)
* Instances launched with boot2docker
* (Possibly) modification of existing VM resources.

CC @luthermonson

**Comment by albal** [comment] 2020-09-02 15:44
This is still an issue with Rancher v.2.4.7

**Comment by DH-Rancher** [comment] 2020-09-08 19:53
Have been able to reproduce this issue with vanilla Docker-Machine (https://github.com/docker/machine). It looks like there might be a compatibility issue upstream with vSphere 7.

**Comment by albal** [comment] 2020-10-12 13:46
Still the same issue with Rancher v2.5.0 and v.2.5.1 - it seems this won't be fixed.  I am struggling to find any documentation on how to create a vCenter VM template which would be suitable for the "Deploy from template: Data Center" in *node-templates* - can someone point me in the right direction?

**Comment by casesta** [comment] 2020-10-12 16:23
> Still the same issue with Rancher v2.5.0 and v.2.5.1 - it seems this won't be fixed. I am struggling to find any documentation on how to create a vCenter VM template which would be suitable for the "Deploy from template: Data Center" in _node-templates_ - can someone point me in the right direction?

Are you referring to just making a VM Template and not really related to the issue discussed in this thread? If so, what I ended up doing was just grabbing an Ubuntu cloud-image from: https://cloud-images.ubuntu.com/ (OVA is an option), deploy that to vCenter, then convert that VM to a template and boom.

I then have the cloud-init file in the node template install any additional packages I need that is not included by default (nfs-common for instance) and add a service account I can use to sign into the node with (separate from the ssh user Rancher adds for it's use)

**Comment by AkideLiu** [comment] 2020-10-12 16:55
> > Still the same issue with Rancher v2.5.0 and v.2.5.1 - it seems this won't be fixed. I am struggling to find any documentation on how to create a vCenter VM template which would be suitable for the "Deploy from template: Data Center" in _node-templates_ - can someone point me in the right direction?
> 
> Are you referring to just making a VM Template and not really related to the issue discussed in this thread? If so, what I ended up doing was just grabbing an Ubuntu cloud-image from: https://cloud-images.ubuntu.com/ (OVA is an option), deploy that to vCenter, then convert that VM to a template and boom.
> 
> I then have the cloud-init file in the node template install any additional packages I need that is not included by default (nfs-common for instance) and add a service account I can use to sign into the node with (separate from the ssh user Rancher adds for it's use)

Thanks so much for this extremely useful info **cloud-image** , rancher has lots of problems to provision ubuntu from vmware template by manually installed.

Confirm that provisioning kubernetes cluster on vSphere successfully with following specifications : 

- rancher 2.5.1
- vSphere 7.0 U1
- ubuntu-bionic-18.04-cloudimg

**Comment by DH-Rancher** [comment] 2020-10-12 17:08
**On the subject of VM templates:**

As previously discussed the cloud-image templates work well. Additionally, consider using packer to create templates (https://github.com/David-VTUK/Rancher-Packer).

The main bit is to ensure `cloud-init` is in a state accepting of new instance-metadata. Typically this involves "cleaning" cloud-init in your template (the aforementioned Packer templates do this by default, ie:)

```
# Reset any existing cloud-init state
#
cloud-init clean -s -l
```
The `cloud-image` template does this by default I believe.

**On the subject of vSphere 7 support:**

We're working on it, but unfortunately we cannot share an ETA at this time

As a workaround (admittedly, not ideal:)

Try to configure your template to mimic the desired end configuration state in terms of attached port groups. Currently, I can get it to work cloning a VM template with the desired port group already attached.

**Comment by DH-Rancher** [comment] 2020-10-21 17:36
@albal @agepi477 @ipyker - Would you be willing to test an experimental version of Rancher that we have modified to address vSphere 7, please?

If so, on any machine with Docker:

```
docker run -d --restart=unless-stopped \
  -p 80:80 -p 443:443 \
  --privileged \
  rancher/rancher:v2.4-head
```
* Log into Rancher  
* Configure Cloud Credential and Node Template  
* Attempt to create a cluster

**Comment by systemmonkey42** [comment] 2020-10-22 09:24
I did some quick testing, and it all came up (using a template generated via Packer (David-VTUK/Rancher-Packer).
I'll test pvc with a vsphere backend to ensure it does what it should.

**Comment by albal** [comment] 2020-10-22 10:40
Works for me now @DH-Rancher - version v2.4-4037-head reported in the UI.  Created the credentials, added a new single node cluster using boot2docker.  Thank you very much.

**Comment by DH-Rancher** [comment] 2020-10-22 11:37
Thank you very much @systemmonkey42 @albal

**Comment by bmdepesa** [comment] 2020-10-26 17:57
v2.4-head, v2.5-head, master-head tested in this issue: https://github.com/rancher/rancher/issues/29519#issuecomment-712872322

**Closed by bmdepesa** 2020-10-26 17:57 UTC
Labels: [zube]: To Test, area/vsphere

**Comment by aledr** [comment] 2020-11-10 22:10
Tested on 2.5.2 with vApp properties and It fails to add IP address.

**Comment by DH-Rancher** [comment] 2020-11-10 22:20
@aledr - Are there any errors reported in vSphere,?

Are you using the vapp properties in combination with a cloud-init script to set the IP address of a node?

**Comment by aledr** [comment] 2020-11-11 02:00
No errors on vSphere.
Only vApp without cloud-init script personalization.

I see only IPv6 at the Virtual Machine status at vSphere.
At Rancher I see "Waiting for SSH to be available." and then "Error creating machine: Error detecting OS: Too many retries waiting for SSH to be available. Last error: Maximum number of retries (60) exceeded".

**Comment by DH-Rancher** [comment] 2020-11-11 09:06
@aledr - I'd say in that instance it isn't a vSphere 7 issue as addressed by this GH issue. If vSphere is only reporting the ipv6 address of the VM then the IPv4 properties haven't been set, which may indicate a configuration issue.

Can you please raise a separate GH issue for this and/or mention this in the community slack channel (https://slack.rancher.io/) and we'll dig into this further.

It may be as simple as the cloud-init script referencing the wrong interface name.
