### ISSUE TITLE
Anonymous LDAP Authentication 

### ISSUE THREAD

**Issue by asanami** [rancher/rancher#5669] opened 2016-08-09 08:24 UTC
**Rancher Version:**

1.1.1

**Docker Version:**

**OS and where are the hosts located? (cloud, bare metal, etc):**

bare metal

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**

Single node rancher

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**

Cattle

**Steps to Reproduce:**

Configure access control through OpenLDAP

**Expected:**

Our LDAP configuration supports  anonymous readonly access.  Is it possible to optionally provide service account username and passwords.

**Comment by tfiduccia** [comment] 2016-08-09 17:42
Duplicate of #2372

**Closed by tfiduccia** 2016-08-09 17:42 UTC
