### ISSUE TITLE
If there are multiple ".xip.io" ingress rules that are created for different workloads , there is only 1 endpoint created that directs traffic to all workloads.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#13806] opened 2018-06-01 01:11 UTC
**Rancher versions: Build from master
**Steps to Reproduce:**
Create a ingress with 2 ".xip.io" ingress rules (no path specified/same path specified) to 2 different workloads.

<img width="1270" alt="screen shot 2018-05-31 at 6 05 03 pm" src="https://user-images.githubusercontent.com/4266958/40815803-d7cfe1b6-64fd-11e8-92d9-c87d063ba612.png">

Only 1 endpoint gets generated which directs traffic to both workloads.

In this case , we would expect 2 endpoints to be generated for each workload.

**Comment by alena1108** [comment] 2018-06-01 03:52
@kinarashah could you check if it can be caused by that commit where rules with the same hostname/path were merged. The merge should be done only for the case when hostname option is picked in the UI.

**Comment by kinarashah** [comment] 2018-06-01 17:30
@alena1108 That commit fixed calculating the `httpIngressPath` correctly, but looks like there is still some issue with endpoints - only one gets created, I'll fix it.

**Comment by alena1108** [comment] 2018-06-01 23:27
@sangeethah @kinarashah I'm rethinking my original statement. Grouping actually makes sense because it lets you setup path based routing, where the same `.xip.io` domain is generated for all targets having diff paths, so the traffic can get routed to the workload based on path only.

Having it this way is more flexible. If user wants to have diff xip.io domain for his other workload, he can achieve it by creating a separate ingress.

**Comment by alena1108** [comment] 2018-06-01 23:31
@ibuildthecloud @deniseschannon I'm going to close the issue if there are no objections

**Comment by sangeethah** [comment] 2018-06-01 23:32
@alena1108 , we have the ability to add multiple workloads under the same ingress rules for grouping  by path. 
When a new ingress rule is created , it would be better to have its own endpoint that directs to only the workloads for this rule ?

**Comment by alena1108** [comment] 2018-06-01 23:49
@sangeethah it's just a UI representation; when it comes to translating it to the API rules, there is no diff between:

<img width="1269" alt="screen shot 2018-06-01 at 4 46 18 pm" src="https://user-images.githubusercontent.com/1562176/40867734-8415ae02-65bb-11e8-8132-02193c1c0222.png">

and 
<img width="1263" alt="screen shot 2018-06-01 at 4 46 29 pm" src="https://user-images.githubusercontent.com/1562176/40867737-870fe064-65bb-11e8-84ab-4a9eac8f4b8a.png">

The grouping is done by hostname/path, where hostname in this case is `xip.io` wildcard. If we want this grouping to be respected, it would require big api changes

@deniseschannon I'm going to move this bug to unschedulable. If user wants diff xip.io domain for his workload, he can create a separate ingress resource for it.

**Closed** 2018-10-21 13:27 UTC
Labels: kind/bug, status/autoclosed, status/wontfix, version/2.0
