### ISSUE TITLE
Mixed content in HTTPS

### ISSUE THREAD

**Issue by ndelitski** [rancher/rancher#2311] opened 2015-10-11 21:44 UTC
Anyone explain why rancher frontend send requests with HTTP when `api.host` settings set to https?
```
Mixed Content: The page at 'https://mydomain.com/infra/hosts' was loaded over HTTPS, but requested an insecure XMLHttpRequest endpoint 'http://mydomain.com/v1/hosts/1h1'. This request has been blocked; the content must be served over HTTPS.
```

**Comment by ndelitski** [comment] 2015-10-11 22:08
Also i noticed if start non-fresh rancher container it trying to connect long time, flooding this:
```
ERRO[0000] Unable to create event router                 error=Get https://mydomain.com/v1: net/http: transport closed before response was received
INFO[0000] Exiting rancher-compose-executor             
INFO[0000] Setting log level                             logLevel=info
INFO[0000] Starting go-machine-service...                gitcommit=ecc762f
ERRO[0000] Unable to create EventRouter                  Err=Get https://mydomain.com/v1: EOF
INFO[0000] Exiting go-machine-service...                
INFO[0000] Starting rancher-compose-executor             gitcommit=v0.1.1
ERRO[0000] Unable to create event router                 error=Get https://mydomain.com/v1: net/http: transport closed before response was received
```
I have AWS ELB above rancher with proxy protocol enabled, working in TCP mode...

**Comment by deniseschannon** [comment] 2015-10-12 17:48
@ndelitski Have you looked at our troubleshooting docs? They have some specifics on what happens if go-machine-service is repeating. 

http://docs.rancher.com/rancher/faqs/troubleshooting/

Due to your setup, I'm also going to ask @cjellick to take a look as he might have better insight.

**Comment by cjellick** [comment] 2015-10-14 21:43
@ndelitski The api.host setting does not impact any of the URLs used in the UI. It only affects the url that our agents on your hosts connect to (this does include the go-machine-service, however).

This mixed context issue happens when we cannot correctly determine the protocol of the incoming request.

Can you provide a few more details about your setup?
- What version of rancher are you on?
- Do you have multiple rancher-server instances?
  - If yes, did you start the rancher-servers in "ha" mode via `-e CATTLE_HOST_API_PROXY_MODE="ha"`?
- Does the ELB point directly at them or is there another intermediary proxy? (An odd question I realize, but ELB -> HAProxy -> application seems to be a common setup).
- Are you running on the standard 443 https port?

**Comment by ebr** [comment] 2015-10-28 18:16
Started opening a new issue about this, but then saw this one. I believe I'm in the same boat. It seems like a re-occurrence of https://github.com/rancher/rancher/issues/1876  and/or related to https://github.com/rancher/websocket-proxy/pull/21.

The Rancher server is behind ELB, configured correctly with proxy protocol. SSL is terminated by the ELB. After loading any page, everything works fine for one or two minutes, after which actions like opening a shell to a container, getting the logs, getting the charts in the host status page, all simply display "connecting". In the console, I get: 

`Mixed Content: The page at 'https://my.rancher.tld/infra/hosts' was loaded over HTTPS, but requested an insecure XMLHttpRequest endpoint 'http://my.rancher.tld/v1/containers/1i741/?action=execute'. This request has been blocked; the content must be served over HTTPS.`

`Mixed Content: The page at 'https://my.rancher.tld/apps' was loaded over HTTPS, but requested an insecure XMLHttpRequest endpoint 'http://my.rancher.tld/v1/containers/1i525/?action=logs'. This request has been blocked; the content must be served over HTTPS.`

...and so forth.

It feels like going from any `/apps` or `/infra/hosts` URI to any `?action=*` URI starts producing the above error soon after refreshing the page. A browser refresh fixes this for another minute or so, and this is the only fix that works. Going to other pages (e.g. Infrastructure) has no effect.

This happens even if there's an active websockets connection (i.e. i'd be watching host metrics, try to get container logs and hit the above errors, while host metrics continue coming in just fine).

@cjellick to answer your questions:

  - v0.43.1
  - no, but i am using an external DB (the only "HA"-like change from the default setup)
    - no
  - yes (ELB points directly at Rancher)
  - yes (443) on the ELB.

I also tried tweaking some ELB settings such as connection draining, but saw no improvement.

**Comment by deniseschannon** [comment] 2015-11-02 22:45
This looks like a duplicate of https://github.com/rancher/rancher/issues/2464 that will be fixed in the next release. 

I'll close this issue in favor of the other one.

**Comment by ebr** [comment] 2015-11-06 17:00
@deniseschannon @cjellick I don't think this is a duplicate of #2464. Just upgraded to 0.44.0 and still having trouble. it looks like #1876, which was fixed but maybe not entirely. I had high hopes for this fix after https://github.com/rancher/rancher-catalog-service/pull/14, but no dice it seems. See my notes above please... Basically I end up refreshing the page after every other `action` (e.g. getting the logs, opening container shell, scaling...) to be able to proceed.

I  can reproduce this very consistently in multiple browsers, for example: 1) get the logs for any container, and then 2) try to open a shell to any container (same or otherwise). 9 out of 10 times I'll get the `Mixed content` warning, and after that point *no* other actions work until I reload the page. I set up the ELB as per instructions, and it't gotta be be set up correctly, because websockets work fine.... until they don't - as described. 

I'll try any troubleshooting suggestions. Can share a screen recording if that might help.

Thanks!

**Comment by cjellick** [comment] 2015-11-06 17:32
@ebr I agree that this is not a dupe of #2464. I'm reopening.
We will get an ELB+rancher setup to see if we can reproduce.
From what you've said, you have a very normal/basic setup, so hopefully we can reproduce. Will give you an update sometime next week.

**Comment by ebr** [comment] 2015-11-06 17:44
thank you @cjellick! I forgot to add one thing, may be relevant: my rancher agents are connecting to the server on a different URL than the UI (it is a subdomain of the UI URL - e.g. `http://hosts.my.rancher.url` for host registration vs `https://my.rancher.url` for the UI). The agents are not going through the ELB, and therefore not using SSL.

**Comment by cjellick** [comment] 2015-11-06 18:27
Thanks for the additional information @ebr. We'll setup host registration the same way.

**Comment by cjellick** [comment] 2015-11-06 18:29
@aruneli Can you setup and test ELB+SSL+rancher?

**Comment by aruneli** [comment] 2015-11-06 18:37
@cjellick Ok, assign this to me. I may have previously created setup.

**Comment by johnrengelman** [comment] 2015-11-11 19:17
I'm also experiencing this same problem. Same setup. SSL+ELB, however I'm using the same domain for UI access and Host registration, so I it's not that.

**Comment by johnrengelman** [comment] 2015-11-13 15:41
More details. 
I'm seeing this request:
```
wss://rancher.connectedfleet.io/v1/subscribe?eventNames=resource.change&include=hosts&include=instances&include=instance&include=loadBalancerConfig&include=loadBalancerTargets&include=loadBalancerListeners&include=instanceLinks&include=ipAddresses&projectId=1a15
```
is returning the following header in it's response:
```
X-API-Schemas:http://rancher.connectedfleet.io/v1/schemas
```

**Comment by cjellick** [comment] 2015-11-13 16:04
@johnrengelman do you have a single rancher server or more than one? Are you running the websocket-proxy in its own container or are you allow the rancher/server container to manage it? (If you don't know what the websocket-proxy is, then rancher/server is running it for you).

Do you have any other proxies between ELB and rancher?

What version of rancher are you on?

**Comment by johnrengelman** [comment] 2015-11-13 16:07
```
Component	Version
Rancher	v0.44.0
Cattle	v0.107.0
User Interface	v0.65.0
Rancher Compose	v0.5.1
```

I'm running rancher-server has it's own docker container: 
`docker run -d --restart=always -p 8080:8080 -e CATTLE_DB_CATTLE_MYSQL_HOST=${aws_db_instance.db.address} -e CATTLE_DB_CATTLE_MYSQL_PORT=${aws_db_instance.db.port} -e CATTLE_DB_CATTLE_MYSQL_NAME=rancher -e CATTLE_DB_CATTLE_USERNAME=pnroot -e CATTLE_DB_CATTLE_PASSWORD=P3op1eN3t rancher/server:v0.44.0`

Then placing an ELB in front of this instance that's routing HTTPS:443 -> HTTP:8080

**Comment by johnrengelman** [comment] 2015-11-26 01:20
Still a problem in `v0.47.0`

**Comment by cjellick** [comment] 2015-12-10 18:00
@johnrengelman Besides Proxy Protocol, you need the listener and target in ELB to be TCP/TLS, not HTTP/HTTPS because they don't support WebSockets in HTTP mode.

**Comment by cjellick** [comment] 2015-12-10 18:01
@ndelitski could that be your problem as well?

**Comment by johnrengelman** [comment] 2015-12-10 18:18
@cjellick I have that configured properly.The site works fine initially, but then it just stops and starts sending that message. It appears that one of the responses somewhere changes the domain. Please see my note above where a response is sending the response header `X-API-Schemas:http://rancher.connectedfleet.io/v1/schemas` even though I originally arrived to the site on `https`

**Comment by cjellick** [comment] 2015-12-10 18:35
@johnrengelman apologies in advance for the string of questions.
We just had someone verify in our forums today that they have ELB + SSL + rancher working, so I suspect this could be a configuration issue or something that we recently fixed.

What is the exact, full mixed-context message?

Also, did you configure rancher in [single server mode](http://docs.rancher.com/rancher/installing-rancher/installing-server/) or in[multi server node](http://docs.rancher.com/rancher/installing-rancher/installing-server/multi-nodes/)?

**Comment by johnrengelman** [comment] 2015-12-10 19:46
Single server:
```
Mixed Content: The page at 'https://rancher.connectedfleet.io/apps/1e26/services/1s301/containers' was loaded over HTTPS, but requested an insecure XMLHttpRequest endpoint 'http://rancher.connectedfleet.io/v1/containers/1i743/?action=logs'. This request has been blocked; the content must be served over HTTPS.
```

Replicated by open the log view for a container (logs appear), close it and re-open it (mixed message content error appears)

**Comment by cjellick** [comment] 2015-12-10 20:11
Hmmm. Not sure what is going on @johnrengelman. Would you be interested in either giving me access to your rancher cluster or doing a google hangout to debug?

**Comment by cjellick** [comment] 2015-12-10 21:00
You can ping me on IRC as cjellick if you like.

**Comment by dverbeek84** [comment] 2015-12-11 09:58
A am running 0.49.1 And i don't have the problem any more. Great job!

**Comment by cjellick** [comment] 2015-12-11 15:34
Thanks @dverbeek84 but this fix was not in 49.1. I suspect you were hitting a different but similar bug that was in fact fixed in 49.1

**Comment by ebr** [comment] 2015-12-11 16:56
Still there in 0.49.1 ( @dverbeek84's comment got my hopes up, but alas... )

@cjellick:

![rancher](https://cloud.githubusercontent.com/assets/2433541/11749803/ce07df02-9ffd-11e5-8ac0-d55a142469ae.png)

It does indeed seem like getting the logs is the easiest way to reproduce the issue. Sometimes it happens after a couple of tries. I initially also suspected that opening a shell a few times would also trigger this, but perhaps not - i just tried opening shells to several containers, and it kept working after 5 tries (which is unheard of with `action=logs`). but this is anecdotal, i haven't done any structured testing.

@cjellick we can definitely do a hangout to troubleshoot.

**Comment by cjellick** [comment] 2015-12-11 17:17
@ebr: @johnrengelman and I debugged yesterday and we got to the bottom of it. Fix should be in the next release.

Sorry this bug has been hanging around for so long.

**Comment by ebr** [comment] 2015-12-11 20:02
no worries and thank you for getting to the bottom of it! :+1:

**Comment by cjellick** [comment] 2015-12-11 21:34
@ebr @johnrengelman We have an RC candidate with a fix for this: `rancher/server:v0.50.0-rc1` if you care to test it out. let me know,

DISCLAIMER: This is an RC and can potentially have other bugs in it. :-)

**Comment by cjellick** [comment] 2015-12-11 22:31
and now `rancher/server:v0.50.0-rc2` :-)

**Comment by cjellick** [comment] 2015-12-11 23:33
@aruneli can you test?

**Comment by dverbeek84** [comment] 2015-12-12 09:41
@cjellick @ebr Indeed my problem was related to #2464

**Comment by johnrengelman** [comment] 2015-12-14 20:01
@cjellick I just updated to `0.50.0-rc2` and everything is looking good so far. I'm going to be in my test cluster a bit today, I'll update this if I come across any odd behavior, but so far I think you've finally nipped this one.

**Comment by cjellick** [comment] 2015-12-14 20:12
Thanks @johnrengelman!  We should have the official release soon (which I think will be based off of an rc3).

**Comment by ebr** [comment] 2015-12-14 22:25
@cjellick @johnrengelman awesome news, thank you! I won't be able to test the RC this week, but really looking forward to the release! :100: :stars:

**Comment by aruneli** [comment] 2015-12-14 23:45
Closing it as tested based on above comments after discussing with Will.

**Closed by aruneli** 2015-12-14 23:45 UTC
Labels: kind/bug, status/resolved, status/to-test
