### ISSUE TITLE
Service discovery records / services are not created when workload is deployed

### ISSUE THREAD

**Issue by sowmyav27** [rancher/rancher#33704] opened 2021-07-21 03:31 UTC
**Rancher Server Setup**
- Rancher version: master-head commit id: `cfbd0d3`
- Installation option (Docker install/Helm Chart): HA/Single install
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): AKS/GKE/RKE1 local cluster

**Information about the Cluster**
- Kubernetes version: 1.20.8
- Cluster Type (Local/Downstream): Custom RKE1 cluster/DO RKE1 cluster

**Describe the bug**
Service discovery records / services are not created when workload is deployed

**To Reproduce**

- Deploy workloads from Ember UI
- Services are not created
- Deploy a DNS record pointing to wk01 workload
- From another workload curl on the dns record.
- Says `curl: (6) Could not resolve host: dns`

**Result**
Services should get created and DNS resolution must work

**Comment by sowmyav27** [comment] 2021-07-24 03:56
On master-head commit id: `be7cdb8`, I see Service discoveries entries being created for workloads deployed in ember UI. And DNS resolution also works. (HA setup, AWS Node driver cluster 1.20.8 k8s version)

**Comment by rmweir** [comment] 2021-07-26 21:16
Moving to test. This was caused by the hostedcluster handler being registered to cluster agents. The handler accesses v3.Apps and v3.Projects which are not available on downstream clusters. This caused downstream controllers to get stuck and none of them to run. This has been fixed here https://github.com/rancher/rancher/commit/9e0d1b2cdcf16822a6b756b5759216e065e5c6bf by @StrongMonkey by gating registering the handler with the multi-cluster-management flag which is set to false on downstream clusters.

**Comment by anupama2501** [comment] 2021-07-27 22:37
Verified on master-head 01665d0, kubernetes v1.20.8 HA

1. Created a downstream cluster rke1 node driver.
2. From ember UI, created a few workloads - verified SDs are created for the workloads
3. Created a DNS entry and pointed an ingress to the DNS entry - Verified curl on DNS record works fine
4. Ran validation tests on the cluster - tests have passed

**Closed by anupama2501** 2021-07-27 22:37 UTC
Labels: [zube]: QA Working, kind/bug-qa, status/release-blocker
