### ISSUE TITLE
cluster monitoring does not respect Selectors

### ISSUE THREAD

**Issue by Tejeev** [rancher/rancher#22760] opened 2019-09-10 15:09 UTC
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
1. At cluster level, enable monitoring with a valid selector declared
![image](https://user-images.githubusercontent.com/8906089/64620860-8e966e80-d3dc-11e9-8ddd-c664814ba36d.png)
![image](https://user-images.githubusercontent.com/8906089/64621030-dfa66280-d3dc-11e9-800a-8ee3b0dff15a.png)

**Result:**
Only prometheus-cluster-monitoring Pods are scheduled with the selector.

```
> kubectl get pods -n cattle-prometheus -o wide
NAME                                                      READY   STATUS    RESTARTS   AGE   IP               NODE            NOMINATED NODE   READINESS GATES
exporter-kube-state-cluster-monitoring-75567dff98-n4nd2   1/1     Running   0          20m   10.42.2.3        tpatel-w-nt3    <none>           <none>
exporter-node-cluster-monitoring-2gwwx                    1/1     Running   0          20m   157.245.69.150   tpatel-w-nt4    <none>           <none>
exporter-node-cluster-monitoring-9zt2v                    1/1     Running   0          20m   157.245.78.74    tpatel-cp-nt3   <none>           <none>
exporter-node-cluster-monitoring-fqhxs                    1/1     Running   0          20m   157.245.77.250   tpatel-w-nt2    <none>           <none>
exporter-node-cluster-monitoring-k9kqp                    1/1     Running   0          20m   157.245.71.190   tpatel-w-nt1    <none>           <none>
exporter-node-cluster-monitoring-l7tq9                    1/1     Running   0          20m   157.245.72.165   tpatel-cp-nt1   <none>           <none>
exporter-node-cluster-monitoring-nlxlt                    1/1     Running   0          20m   157.245.74.76    tpatel-cp-nt2   <none>           <none>
exporter-node-cluster-monitoring-pqmhj                    1/1     Running   0          20m   157.245.79.151   tpatel-w-nt3    <none>           <none>
grafana-cluster-monitoring-576c5d879f-ngqkk               2/2     Running   0          20m   10.42.4.2        tpatel-w-nt4    <none>           <none>
prometheus-cluster-monitoring-0                           5/5     Running   1          19m   10.42.3.7        tpatel-w-nt1    <none>           <none>
prometheus-operator-monitoring-operator-c474f7475-gsbbg   1/1     Running   0          20m   10.42.1.5        tpatel-w-nt2    <none>           <none>
> kubectl describe pod prometheus-cluster-monitoring-0 -n cattle-prometheus | grep Node-Sel -A3
Node-Selectors:  beta.kubernetes.io/os=linux
                 role=promet
Tolerations:     node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
> kubectl describe pod grafana-cluster-monitoring-576c5d879f-ngqkk -n cattle-prometheus | grep Node-Sel -A3
Node-Selectors:  beta.kubernetes.io/os=linux
Tolerations:     node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
Events:
> kubectl describe pod prometheus-operator-monitoring-operator-c474f7475-gsbbg -n cattle-prometheus | grep Node-Sel -A3        
Node-Selectors:  beta.kubernetes.io/os=linux
Tolerations:     node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
```

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI):
```
Component:     Version
Rancher:           v2.2.5
User Interface:  v2.2.89
Helm:                 v2.10.0-rancher11
Machine:            v0.15.0-rancher8-1
```
- Installation option (single install/HA):
single install Rancher with HA cluster

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported):
Hosted
- Machine type (cloud/VM/metal) and specifications (CPU/memory):
cloud
- Kubernetes version (use `kubectl version`):

```
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.7", GitCommit:"4683545293d792934a7a7e12f2cc47d20b2dd01b", GitTreeState:"clean", BuildDate:"2019-06-06T01:46:52Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.3", GitCommit:"5e53fd6bc17c0dec8434817e69b04a25d8ae0ff0", GitTreeState:"clean", BuildDate:"2019-06-06T01:36:19Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}

```

- Docker version (use `docker version`):

```
Client:
 Version:      1.10.3
 API version:  1.24
 Go version:   go1.5.3
 Git commit:   20f81dd
 Built:        Thu Mar 10 21:49:11 2016
 OS/Arch:      linux/amd64
```

**Comment by tfiduccia** [comment] 2019-09-11 20:31
Version - master 9/11
Checked and it's true that the Selector does not seem to be working properly.

**Comment by n313893254** [comment] 2019-09-12 06:46
Sorry I cannot reproduce this issue. Version - master 9/12

Here are my steps:
1. Add a cluster using DO node.
2. Add a label `poi = poi` for a node.
3. Enable cluster monitoring with `poi = poi` node-selector.

Result:
Check the grafana-cluster-monitoring, prometheus-cluster-monitoring and prometheus-operator-monitoring-operator, `poi = poi` is added to node-selectors.

```
> kubectl get pods -n cattle-prometheus -o wide
NAME                                                       READY     STATUS    RESTARTS   AGE       IP              NODE             NOMINATED NODE   READINESS GATES
exporter-kube-state-cluster-monitoring-7465ffb97b-x98cd    1/1       Running   0          107s      10.42.0.10      qingyang-test1   <none>           <none>
exporter-node-cluster-monitoring-hbmbw                     1/1       Running   0          108s      167.99.125.43   qingyang-test1   <none>           <none>
grafana-cluster-monitoring-58b6f85ddd-m8m7f                2/2       Running   0          107s      10.42.0.9       qingyang-test1   <none>           <none>
prometheus-cluster-monitoring-0                            5/5       Running   1          102s      10.42.0.12      qingyang-test1   <none>           <none>
prometheus-operator-monitoring-operator-6b8899ff99-pdmg9   1/1       Running   0          111s      10.42.0.7       qingyang-test1   <none>           <none>

>kubectl describe pod prometheus-cluster-monitoring-0 -n cattle-prometheus | grep Node-Sel -A3
Node-Selectors:  kubernetes.io/os=linux
                 poi=poi
Tolerations:     cattle.io/os=linux:NoSchedule
                 node.kubernetes.io/not-ready:NoExecute for 300s

>kubectl describe pod grafana-cluster-monitoring-58b6f85ddd-m8m7f -n cattle-prometheus | grep Node-Sel -A3
Node-Selectors:  kubernetes.io/os=linux
                 poi=poi
Tolerations:     cattle.io/os=linux:NoSchedule
                 node.kubernetes.io/not-ready:NoExecute for 300s

>kubectl describe pod prometheus-operator-monitoring-operator-6b8899ff99-pdmg9 -n cattle-prometheus | grep Node-Sel -A3
Node-Selectors:  kubernetes.io/os=linux
                 poi=poi
Tolerations:     cattle.io/os=linux:NoSchedule
                 node.kubernetes.io/not-ready:NoExecute for 300s
```

**Comment by Tejeev** [comment] 2019-09-16 13:28
I upgraded cluster to 2.2.8 (rancher/rancher:latest 9/16/2019) and have tried adding the node selector to existing monitoring as well as disabling and enabling monitoring with the node selectors (cluster and for both default and system projects), but in either case, the grafana and operator pods do not inherit the nodeSelector.  If I edit an existing monitoring tool configuration to add a selector that does not currently exist, only the `prometheus-cluster-monitoring` workload complains of no nodes matching the node selector.

**Comment by Tejeev** [comment] 2019-09-16 16:26
\internal

**Comment by loganhz** [comment] 2019-09-16 16:28
Can you try 2.3.0-rc3, please?

**Comment by Tejeev** [comment] 2019-09-16 22:55
Ah!  Sorry missed that. Yes 2.3.9-rc3 works as expected.  Thank you!

**Comment by tfiduccia** [comment] 2019-09-18 18:20
Verified in 2.3.0.  Closing issue

**Closed by tfiduccia** 2019-09-18 18:20 UTC
Labels: area/monitoring, kind/bug, team/ui
