### ISSUE TITLE
Stack upgrade doesn't work with v1.1.0-dev5

### ISSUE THREAD

**Issue by pwFoo** [rancher/rancher#5242] opened 2016-06-24 21:06 UTC
**Rancher Version:** 
v1.1.0-dev5

**Docker Version:** 
Docker version 1.10.3, build 20f81dd

**OS and where are the hosts located? (cloud, bare metal, etc):** 
RancherOS 0.4.5, KVM VM

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
Single node rancher, internal DB

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle

**Steps to Reproduce:**
Upgrade a stack based of two containers (php-fpm with sidekick webserver). I have a global stack mariadb-galera cluster running on each host. The php-fpm is linked to MySQL/galera or the MySQL/galera LB. Stack upgrades doesn't work. Move during the upgrade to the Rancher Server running host and no error occurs. 

Maybe it could be related to the host the stack is deployed to! Initial deploy seems to work (maybe service link is missing...), but ugrade fails. If I change the destination host is will be redeployed 

**Results:** 
Error message: `Upgrade Error
Validation failed in API: requestedHostId`

**Expected:**
Upgrade the service

Any idea why the upgrade won't work?

**Comment by pwFoo** [comment] 2016-06-24 21:39
Maybe it is dependent on the schedule rules. Changed from specific host to a host label rule and it seems to work.

**Comment by deniseschannon** [comment] 2016-06-28 05:20
Duplicate of https://github.com/rancher/rancher/issues/3323

**Closed by deniseschannon** 2016-06-28 05:20 UTC
