### ISSUE TITLE
Ingress with auto xip.io dns generation is using the node internal IP address instead of external.

### ISSUE THREAD

**Issue by izaac** [rancher/rancher#22534] opened 2019-08-29 23:34 UTC
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
Custom cluster with cloud provider Azure I created one master linux box for Control Plane and etcd.
One Windows Box.

Adding nodes to the cluster Rancher usually collects both Internal and External IP addresses for these nodes and cloud provider combination.

1. Create Workload of type NodePort.
2. Create Ingress pointing to the workload.
3. See the resolution of the automatically generated DNS entry resolves the Master node Internal IP address making it unresolvable from external.

**Result:**

In this case the xip.io service return a new DNS entry but using the Master node internal IP.

![Screen Shot 2019-08-29 at 4 29 24 PM](https://user-images.githubusercontent.com/27659/63983160-5f960980-ca7a-11e9-8525-e01a7024434b.png)

![Screen Shot 2019-08-29 at 4 25 19 PM](https://user-images.githubusercontent.com/27659/63983166-63c22700-ca7a-11e9-8190-62ed81debed1.png)

dig +short test1-ingress.ns1.192.168.0.63.xip.io
**192.168.0.63** .  -> Internal IP that can be seen in the first screenshot.

**Environment information**
- Rancher version: master-head (v2.3) (08/29/2019)
- Windows workers: windows server 2903

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): Custom
- Machine type (cloud/VM/metal) and specifications (CPU/memory): cloud
- Kubernetes version (use `kubectl version`): 

```
v1.15.3-rancher3-1
```

- Docker version (use `docker version`):

```
19.03.1
```

**Comment by sowmyav27** [comment] 2019-08-30 15:57
Verified on master-head.
the xip.io ingress for AWS works as expected. (windows workload)

**Comment by izaac** [comment] 2019-08-30 21:32
Verified on master-head
Having a linux worker active this issue is still reproducible in Azure.

**Comment by thxCode** [comment] 2019-09-02 08:06
@izaac ,I did a test for pure v1.14.6 Linux cluster (1 controlplane + 1 Linux worker) with the following cases and mark the result in the rightmost column:

| rancher/rancher version | ingress-controller version | cloud provider type | with public ip | DNS suffix |
| :---: | --- | :---: | --- | ---: |
| v2.2.8 | rancher/nginx-ingress-controller:0.21.0-rancher3 | AWS/Azure | no | NODE_PRIVATE_IP.xip.io |
| v2.2.8 | rancher/nginx-ingress-controller:0.21.0-rancher3 | - | no | NODE_PRIVATE_IP.xip.io |
| v2.2.8 | rancher/nginx-ingress-controller:0.21.0-rancher3 | AWS/Azure | **yes** | **NODE_PUBLIC.xip.io**|
| v2.2.8 | rancher/nginx-ingress-controller:0.21.0-rancher3 | - | **yes** | **NODE_PUBLIC_IP.xip.io**|
| master-head | rancher/nginx-ingress-controller:nginx-0.25.1-rancher1 | AWS/Azure | no | NODE_PRIVATE_IP.xip.io |
| master-head | rancher/nginx-ingress-controller:nginx-0.25.1-rancher1 | - | no | NODE_PRIVATE_IP.xip.io |
| master-head | rancher/nginx-ingress-controller:nginx-0.25.1-rancher1 | AWS/Azure | **yes** | **NODE_PUBLIC.xip.io**|
| master-head | rancher/nginx-ingress-controller:nginx-0.25.1-rancher1 | - | **yes** | **NODE_PUBLIC_IP.xip.io**|

As you see, if want **NODE_PUBLIC_IP.xip.io**, you need to pass the public IP of the node explicitly when adding. 

In fact, the formatting of `xip.io` DNS is determined by ingress controller, the logic of ingress controller will detect two annotations of Node: 
```
if found `rke.cattle.io/external-ip` {
  return public-ip as ingress IP
}
if found `rke.cattle.io/internal-ip` {
  return private-ip as ingress IP
}
```
https://github.com/rancher/ingress-nginx/blob/46c70a1f6919537b25affa642ffbec6db10292be/internal/k8s/main.go#L66-L83

You might confuse for the auto gained public IP from a cloud provider, I think this is not a bug but like a product design decision. In short, as a workaround, if you want the _right_ `xip.io` DNS, you must pass a public IP when adding an agent. This also applies to the Windows cluster.

cc @sowmyav27 , @sangeethah

**Comment by loganhz** [comment] 2019-09-02 23:57
Not a regression

**Comment by izaac** [comment] 2019-09-03 16:18
thanks @thxCode I'll validate the current `master-head` today to check the expected results for Azure and after that close this issue if that's the case.

**Comment by izaac** [comment] 2019-09-18 16:05
Dependency for finishing testing this was closed linking it here https://github.com/rancher/rancher/issues/22612

**Comment by sowmyav27** [comment] 2019-09-18 22:15
**Verified on `rancher:v2.3.0-rc5`.**

- Deploy an AWS custom cluster with following spec

```
- windows enabled
- k8s - v1.15.3
- 1 linux etcd/control node, 1 linux worker node - Ubuntu 18.04 
- 1 windows worker node - Windows_Server-1903-English-Core-Base-2019.08.16 
- cloud provider enabled.
```

- Deploy a workload and an xio.io ingress to the workload.
- Ingress is generated - `ing01.default.<worker node private ip> .xip.io/name.html`

**Comment by sowmyav27** [comment] 2019-09-18 22:35
Waiting on this issue - https://github.com/rancher/rancher/issues/22942 to test one more use case before I close this issue.

**Comment by sowmyav27** [comment] 2019-09-19 20:51
The xip.io ingress for usecase - cloud provider set, register custom cluster nodes with only public ip will be tested as part of this issue https://github.com/rancher/rancher/issues/22942. 

Closing this issue.

**Closed by sowmyav27** 2019-09-19 20:51 UTC
Labels: [zube]: To Test, area/ingress, area/windows, kind/bug-qa, team/cn
