### ISSUE TITLE
Defunct processes: [git-remote-http] <defunct>

### ISSUE THREAD

**Issue by smalenfant** [rancher/rancher#13858] opened 2018-06-05 19:47 UTC
Not sure if this is an issue. 

**Rancher versions:**
rancher/server or rancher/rancher: 2.0.2
rancher/agent or rancher/rancher-agent: 2.0.2

**Infrastructure Stack versions:**
kubernetes (if applicable): 1.10.1

**Docker version: (`docker version`,`docker info` preferred)**
Server Version: 17.03.2-ce

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
RancherOS v1.1.1

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
KVM

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
single node rancher

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**
Kubernetes

**Steps to Reproduce:**
N/A

**Results:**
Looking inside the `rancher/rancher:v2.0.2` container, I can see all those defunct container:

```
root        27  0.0  0.0      0     0 ?        Z    May25   0:00 [git-remote-http] <defunct>
root        88  0.0  0.0      0     0 ?        Z    May25   0:00 [git-remote-http] <defunct>
root       126  0.0  0.0      0     0 ?        Z    May25   0:00 [git-remote-http] <defunct>
root       135  0.0  0.0      0     0 ?        Z    May25   0:00 [git-remote-http] <defunct>
root       203  0.0  0.0      0     0 ?        Z    May25   0:00 [git-remote-http] <defunct>
root       242  0.0  0.0      0     0 ?        Z    May25   0:00 [git-remote-http] <defunct>
root       251  0.0  0.0      0     0 ?        Z    May25   0:00 [git-remote-http] <defunct>
root       318  0.0  0.0      0     0 ?        Z    May25   0:00 [git-remote-http] <defunct>
root       356  0.0  0.0      0     0 ?        Z    May25   0:00 [git-remote-http] <defunct>
root       388  0.0  0.0      0     0 ?        Z    May25   0:00 [git-remote-http] <defunct>
root       432  0.0  0.0      0     0 ?        Z    May26   0:00 [git-remote-http] <defunct>
root       470  0.0  0.0      0     0 ?        Z    May26   0:00 [git-remote-http] <defunct>
root       480  0.0  0.0      0     0 ?        Z    May26   0:00 [git-remote-http] <defunct>
root       569  0.0  0.0      0     0 ?        Z    May26   0:00 [git-remote-http] <defunct>
root       607  0.0  0.0      0     0 ?        Z    May26   0:00 [git-remote-http] <defunct>
root       619  0.0  0.0      0     0 ?        Z    May26   0:00 [git-remote-http] <defunct>
root       682  0.0  0.0      0     0 ?        Z    May26   0:00 [git-remote-http] <defunct>
root       722  0.0  0.0      0     0 ?        Z    May26   0:00 [git-remote-http] <defunct>
```

**Comment by superseb** [comment] 2018-06-07 15:37
Steps to reproduce:

- Launch `rancher/rancher`
- Enable Helm Stable or Incubator

**Comment by eyespies** [comment] 2018-06-11 03:39
+1 

Same issue here...

```
root     29403     2  0 01:50 ?        00:00:00 [kworker/10:0]
root     29597  1278  0 02:03 ?        00:00:00 [git-remote-http] <defunct>
root     29598  1278  0 02:03 ?        00:00:00 [git-remote-http] <defunct>
root     29603  1278  0 02:03 ?        00:00:00 [git-remote-http] <defunct>
root     29607  1278  0 02:03 ?        00:00:00 [git-remote-http] <defunct>
root     30397  1278  0 03:03 ?        00:00:00 [git-remote-http] <defunct>
root     30398  1278  0 03:03 ?        00:00:00 [git-remote-http] <defunct>
root     30403  1278  0 03:03 ?        00:00:00 [git-remote-http] <defunct>
root     30410  1278  0 03:03 ?        00:00:00 [git-remote-http] <defunct>
root     30413  1278  0 03:03 ?        00:00:00 [git-remote-http] <defunct>
root     30416  1278  0 03:03 ?        00:00:00 [git-remote-http] <defunct>
root     30420  1278  0 03:03 ?        00:00:00 [git-remote-http] <defunct>
root     30423  1278  0 03:03 ?        00:00:00 [git-remote-http] <defunct>
root     30846     2  0 03:34 ?        00:00:00 [kworker/u49:1]
root     31120     1  0 Jun08 ?        00:00:00 /usr/sbin/smartd -n -q never
```

**Comment by brechsteiner** [comment] 2018-06-11 21:35
+1

**Comment by StrongMonkey** [comment] 2018-06-15 23:47
When you see this, does rancher being installed as an air-gapped setup?

**Comment by ajacques** [comment] 2018-06-16 05:32
@StrongMonkey If you're asking if users see this only on air-gapped Rancher installations, then I see this issue on my controller that is connected and can communicate to the internet.

**Comment by Janfy** [comment] 2018-07-09 08:56
Hi,
Same problem for me.
I'm running rancher 2.0.4.

**Comment by k8w** [comment] 2018-07-11 02:57
Is it because of Catalog?
Can I resolve this by disable Catalog ?

**Comment by tboemker-bkfs** [comment] 2018-07-16 15:25
What does it mean for an issue to be added to a milestone? This issue had been added to the 2.0.6 milestone, but it is not fixed in 2.0.6.

**Comment by bmdepesa** [comment] 2018-07-20 16:30
rancher/rancher:master 7/20

Reproduced in 2.0.5

Enabled Helm Stable
`docker exec <rancher/rancher> ps` 
No defunct processes are running

**Closed by bmdepesa** 2018-07-20 16:30 UTC
Labels: kind/bug, priority/-1, status/resolved, status/to-test, version/2.0

**Comment by thehackercat** [comment] 2019-02-21 02:32
+1
