### ISSUE TITLE
When I change the rancher's language to Chinese,.I can't use "Execute Shell" to execute shell in container

### ISSUE THREAD

**Issue by lucas1993ch** [rancher/rancher#9015] opened 2017-06-09 02:07 UTC
*Describe your issue here*
When I change the rancher's language to Chinese,.I can't use "Execute Shell" to execute shell in container,
but it works when the language is English.

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v1.6.1` Cattle: `v0.181.3` UI: `v1.6.5` |
|Access|`localauth` `admin`|
|Orchestration|`Mesos`|
|Route|`service.containers`|

**Comment by StrongMonkey** [comment] 2017-06-09 18:35
duplicate of https://github.com/rancher/rancher/issues/8963.

**Closed** 2017-06-09 18:35 UTC

**Comment by loganhz** [comment] 2017-06-10 03:34
@lucas1993ch 
there is a workaround for this issue. Or you can wait for rancher v1.6.3

1. open http://${your_rancher_server}/v1/settings/api.ui.index  and click edit
2. input `//rancherui.oss-cn-shanghai.aliyuncs.com/ui/1.6.2/latest` for value and click show request and send request
3. go to rancher server host `docker restart`  rancher server container (restart all server containers if HA)
4. done

**Comment by vincent99** [comment] 2017-06-10 04:05
I know you're trying to be helpful but this is a bad thing to tell people to do.

- We do not release ad-hoc patches and should not tell a random subset of people to use them. If it's that important (and I don't think this qualifies) then there should be a real release for it.
- There exists simple workarounds that require no code change, like changing to any other language temporarily.  `shift-L` will toggle to the "none" language easily. 
  - I'm sure you control it but that domain hosts nothing else official.
  - You're telling users to run unknown code with powerful access from an unknown source with has unknown logging, access control, et.
  -  Users are not going to know or remember to change it back on subsequent releases and will later be broken when it's deleted, or inexplicably out of date.
-  (There is already an automatically updated latest which includes the relevant PR.  Normally `//releases.rancher.com/ui/latest`, but now `stable` because `latest` is 2.0)
- (You don't need to restart to change that setting)

**Comment by loganhz** [comment] 2017-06-11 06:58
thanks @vincent99 ! understood
