### ISSUE TITLE
random crashes of rancher server on AWS

### ISSUE THREAD

**Issue by pkaramol** [rancher/rancher#12308] opened 2018-03-27 08:29 UTC
**Rancher versions:**
rancher/server: 1.6.14
rancher/agent: 1.2.9

**Infrastructure Stack versions:**
healthcheck: v0.3.3
ipsec: 0.13.7
network-services: (network-manager: v0.7.19/metadata: v0.9.5)
scheduler: v0.8.3
kubernetes (if applicable): n/a

**Docker version: (`docker version`,`docker info` preferred)**
```
ubuntu@ip-10-0-1-151:~$ sudo docker info
Containers: 11
 Running: 11
 Paused: 0
 Stopped: 0
Images: 13
Server Version: 17.12.1-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 9b55aab90508bd389d7654c4baf173a981477d55
runc version: 9f9c96235cc97674e935002fc3d78361b696a69e
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.4.0-1052-aws
Operating System: Ubuntu 16.04.4 LTS
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 1.952GiB
Name: ip-10-0-1-151
ID: R6UL:T6HX:JJ6K:CBNW:WE7N:YN4I:XIZX:XWUM:Q7GU:EHLQ:R2IH:GZA6
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: No swap limit support
```

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
```
ubuntu@ip-10-0-1-151:~$ cat /etc/os-release 
NAME="Ubuntu"
VERSION="16.04.4 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.4 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial
```

``` 
ubuntu@ip-10-0-1-151:~$ uname -r
4.4.0-1052-aws
```

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
**AWS**

Rancher Server is on a __`t2.micro`__ instance 

RDS for Rancher server is on __`db.t2.micro`__ db instance.

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
1 Rancher Master / 1 Rancher Host / External DB (RDS) for the master

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle

**Steps to Reproduce:**
Accessing Rancher server randomly will give (after a long time while it is trying to connect) a `502` - Bad Gateway.

This may happen after a prolonged period of normal operation, without any issues whatsoever (although the server only hosts 1 Rancher Node and it is generally not heavily accessed / utilized) 

The EC2 instance hosting the server will become completely unresponsive.

Problem seems to be resolved after rebooting the EC2 instance.

The Server is behind `nginx`

```
$ nginx -v
nginx version: nginx/1.10.3 (Ubuntu)
```

Here is the config file:

```
$ cat /etc/nginx/sites-available/rancher-server.conf 
map $http_upgrade $connection_upgrade {
    default Upgrade;
    ''      close;
}


server {

        listen 80;
        listen 443 ssl;

        server_name my.rancher.server.com;

        location / {

          proxy_pass http://127.0.0.1:8080;
          proxy_set_header X-Real-IP  $remote_addr;
          proxy_set_header X-Forwarded-For $remote_addr;
          proxy_set_header Host $host;
          proxy_set_header X-Forwarded-Proto $scheme;
          proxy_http_version 1.1;
          proxy_set_header Upgrade $http_upgrade;
          proxy_set_header Connection $connection_upgrade;
          # This allows the ability for the execute shell window to remain open for up to 15 minutes. Without this parameter, the default is 1 minute and will automatically close.
          proxy_read_timeout 900s;


          if ($scheme != 'https') {
            rewrite ^ https://$host$request_uri? permanent;
          }

        }


    ssl_certificate /etc/letsencrypt/live/my.rancher.server.com/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/my.rancher.server.com/privkey.pem; # managed by Certbot
```

[Here](https://gist.github.com/pkaramol/52893faaf02057ff10996bd1bf0cdda2) is an long output from server logs.

**Comment by superseb** [comment] 2018-03-27 08:40
Please supply what instance types you are using for the instance running `rancher/server` and the RDS size you are using. The log shows quite a few of `cannot allocate memory`, so it seems your system is underpowered for the workloads you are trying to run.

**Comment by pkaramol** [comment] 2018-03-27 08:42
@superseb issue updated with instance types

**Comment by pkaramol** [comment] 2018-03-27 08:44
@superseb 

the __`t2.micro`__ instance has 1GB of RAM that is in accordance with the product's [requirements](http://rancher.com/docs/rancher/v1.6/en/installing-rancher/installing-server/#requirements).

**Comment by superseb** [comment] 2018-03-27 08:47
The container needs 1GB of RAM, you have an instance with 1GB of RAM and burstable CPU with low credits. For a more complete answer, see this comment: https://github.com/rancher/rancher/issues/12069#issuecomment-372085724

Closing as not a bug, let me know if raising the instance size does not solve the problem so we can investigate.

**Closed by superseb** 2018-03-27 08:47 UTC
Labels: status/more-info, version/1.6

**Comment by pkaramol** [comment] 2018-03-27 08:54
thx for the feedback;

it would be nice however if you updated the relevant section on the requirements to be a little more specific on this given that usually I think the requirements are about the machine a product will be run on.

I believe the way it is currently stated misleads a bit users to opt for __`t2.micro`__ (given the financial aspect)
