### ISSUE TITLE
Azure Blob Storage etcd backups via minIO S3 gateway show as Active in the UI even if they do not exist

### ISSUE THREAD

**Issue by rosskirkpat** [rancher/rancher#26641] opened 2020-04-15 22:06 UTC
**What kind of request is this (question/bug/enhancement/feature request):**
bug

**Steps to reproduce (least amount of steps as possible):**
0. Infrastructure setup in Azure, including Azure Blob Storage
1. setup MinIO s3 gateway that leverages Azure Blob Storage instead of AWS S3 (https://docs.min.io/docs/minio-gateway-for-s3.html)
2. have the annotation `nginx.ingress.kubernetes.io/proxy-body-size` in the System `nginx-ingress-controller` workload set below the size of your etcd snapshots in the 
2. take a snapshot(s)
3. verify snapshot(s) are showing as active in the UI
4. attempt to restore from a snapshot via the UI

**Result:**

The ETCD backups are not actually present in azure blob storage and the cluster is now stuck in "Updating" indefinitely

**Other details that may be helpful:**

To get this working, set the following annotation (this was the size needed for our test environment but it could obviously be smaller to match the actual etcd backup size):
`nginx.ingress.kubernetes.io/proxy-body-size: 512m`

this bug was found in the course of finding a working solution.

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): v2.3.4

gz#9474

**Comment by junkiebev** [comment] 2020-04-16 21:25
If this happens, it's possible to restore from an earlier local snapshot and that will make the cluster once again "usable". The bug (and probably a bad one?) is that it appears in the UI as though it was a successful (and thus _restoreable_) backup.

**Comment by izaac** [comment] 2020-05-07 18:05
Step No. 1 is referring to Minio S3 Gateway mode `https://docs.min.io/docs/minio-gateway-for-s3.html`

**Comment by izaac** [comment] 2020-05-07 19:11
Attempt to reproduce in Rancher `v2.3.4`

1. Configure Azure Blob Storage
2. Deploy [MinIO as Azure Gateway](https://docs.min.io/docs/minio-gateway-for-azure.html)
  - `docker run -p 9000:9000 --name azure-s3 -e "MINIO_ACCESS_KEY=azurestoragename" -e "MINIO_SECRET_KEY=azurestoragekey" -v /mnt/data:/data -v /root/config:/root/.minio minio/minio --certs-dir /root/.minio/certs gateway azure`
3. Login to MinIO web UI check version and create bucket `test1`
  ```
VERSION
2020-05-06T23:23:25Z
PLATFORM
Host: f0f21287c175 | OS: linux | Arch: amd64
RUNTIME
Version: go1.13.10 | CPUs: 2
  ```
4. Edit the Rancher cluster S3 configuration (this might require MinIO to use self-signed certs as the client is https only)
5. Make an snapshot (backup)
6. Check the snapshot was created with the MinIO Web UI and listed in Rancher
7.  Set the `nginx.ingress.kubernetes.io/proxy-body-size:` annotation to a very low value like `200k` in `nginx-ingress-controller` in the Cluster `System` project. (Wait until the ingress is updated)
8. Restore snapshot
```
Cluster is in Updating state with error:

2020/05/07 18:51:27 [ERROR] ClusterController c-pv7ns [cluster-provisioner-controller] failed with : Failed to download etcd snapshot from s3, exit code [1]: time="2020-05-07T18:51:27Z" level=fatal msg="failed to download s3 backup: no backups found"
```

If I set the annotation value as suggested to `nginx.ingress.kubernetes.io/proxy-body-size: 512m` Rancher is able to find the backup file and restore the snapshot.

The snapshots looked healthy to me when stored in MinIO (azure blob) as I was able to download and check the binary file locally in my computer, the error seems to happen when Rancher tries to download(?) the backup file from MinIO.

**Comment by izaac** [comment] 2020-05-07 20:53
The above error was due because I was changing the backup target from Local to S3. Default when creating the cluster was local. Then I switch the configuration from local to S3, that's why the file wasn't found when attempting to restore.

Even setting the `nginx.ingress.kubernetes.io/proxy-body-size: 100k` in the YAML path `spec -> template -> metadata -> annotations`  I'm able to see the backup properly created in the MinIO Azure, where the smallest backup zip is more than 300k.

**Comment by izaac** [comment] 2020-05-07 23:03
Couldn't reproduce with the following tests performed additional to what I've commented above:

- With the annotation using a low size value (100k).
- Storing the snapshots in a folder inside the bucket.
- Storing the snapshots directly in the bucket (no folder).

The Azure Blob storage information is the following in case is important:

```
Performance/Access tier: Standard/Hot 
Replication: Locally-redundant storage (LRS)
Account kind: BlobStorage
```

Every time I hit the `Snapshot Now` I saw the backup triggered and the backup file created in the Storage.

Using MinIO `VERSION 2020-05-06T23:23:25Z` as Azure gateway, using self-signed certificates.

**Comment by izaac** [comment] 2020-05-07 23:38
Could it be possible that before switching to MinIO/AzureBlob backups the cluster had Local backups ? Because local backups are enabled by default in new RKE Rancher clusters.

In that case switching to MinIO/AzureBlob will list the local snapshots in Rancher but these local backups won't appear in the AzureBlob. 

Restoring from a local backup listed in Rancher but having the S3 MinIO configured will lead the cluster to get into this state:

![Screen Shot 2020-05-07 at 12 57 50 PM](https://user-images.githubusercontent.com/27659/81354659-0ce90480-9081-11ea-85f3-00e1e7210f31.png)

Because at this point Rancher will look for the file in the Remote storage only.

**Comment by ArgonV** [comment] 2020-09-29 17:33
I can confirm that with a large Rancher provisioned cluster, I needed to add the nginx.ingress.kubernetes.io/proxy-body-size annotation and set a large size for my backups to make it into the Minio bucket.

**Comment by deniseschannon** [comment] 2020-10-14 04:24
@izaac when testing this, did we actually try and restore from any of those backups? The issue indicates that it looks like the snapshot occurs but it actually can't be restored from?

**Comment by izaac** [comment] 2020-10-14 04:43
@deniseschannon the issue states that the file was created in the storage but the UI was stuck when they tried to restore:

> **Result:**
> 
> The ETCD backups are not actually present in azure blob storage and the cluster is now stuck in "Updating" indefinitely


I tried a few scenarios but all the etcd backup files were created and seen in Minio. I also see I restored from a backup in step 8 here: https://github.com/rancher/rancher/issues/26641#issuecomment-625443922

The Azure Blob detailes I used are also detailed in this other comment: https://github.com/rancher/rancher/issues/26641#issuecomment-625540050

What I don't see here are the cluster details while performing these backups, this seems to happen on large clusters with a large etcd dataset ?

**Comment by rosskirkpat** [comment] 2020-10-15 21:48
@izaac In this situation, the etcd backup size was >400MB, which required bumping the annotation for `nginx.ingress.kubernetes.io/proxy-body-size`. Without that setting, the snapshots would show in the Rancher UI but would never make it into the Azure Blob Storage and could not be used as a restore point. There seemed to be a missing validation that the backup actually existed after creation.

**Comment by izaac** [comment] 2020-11-11 04:44
Rancher version: `v2.3.4` Single Install on Azure VM.
MinIO: `minio/minio:latest` (11/10/2020) with Azure Blob as described [here](https://github.com/rancher/rancher/issues/26641#issuecomment-625443922). With self-signed cert.
Downstream Cluster: Azure RKE. 1 Control Plane, 3 etcd, 1 worker with k8s `v1.17.4`

**I wasn't able to reproduce the issue**, nothing was changed in the ingress, all was out of the box configuration in Rancher and the Downstream cluster (with S3 backups enabled).

I generated data in the downstream cluster (secrets with lots of text).

I see the files in the Azure Blob using MinIO:

![Screen Shot 2020-11-10 at 9 42 50 PM](https://user-images.githubusercontent.com/27659/98769777-e7291900-239d-11eb-828a-2481d6bd1f95.png)

![Screen Shot 2020-11-10 at 9 43 02 PM](https://user-images.githubusercontent.com/27659/98769758-dd9fb100-239d-11eb-87ee-e7b5124b9e88.png)

**Comment by deniseschannon** [comment] 2020-11-11 17:03
@rosskirkpat It seems that QA is unable to reproduce this issue. Do you have any more insight on what is different in what QA is doing vs what is reported?

**Comment by maggieliu** [comment] 2020-11-24 22:52
@izaac Can we try to reproduce with an older version of minio? Per support: there are 4 candidates - March 25, April 2nd, April 4th, April 10th

**Comment by izaac** [comment] 2020-11-25 04:43
@maggieliu I tried the same scenario described above with `minio/minio:RELEASE.2020-03-25T07-03-04Z`

![Screen Shot 2020-11-24 at 9 41 52 PM](https://user-images.githubusercontent.com/27659/100184124-fd56cf00-2e9d-11eb-992b-f8c52eca7cde.png)

**Comment by izaac** [comment] 2023-02-22 02:40
Closing, please open a new issue referencing this one if this is still something that occurs on latest releases.

**Closed by izaac** 2023-02-22 02:40 UTC
Labels: kind/bug, internal, status/more-info
