### ISSUE TITLE
Restored containers of a service that is not part of service anymore is listed as being part of service.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#3169] opened 2016-01-05 23:30 UTC
Server version - Build from master - Jan 5

Steps to reproduce the problem:
Create and activate a service.
Delete one of the instance from the service and use restore option.
Start the stopped instance. This instance starts up as a standalone instance.

UI still shows this instance ( Default_test1_1) still shows up as being part of the service.

<img width="1361" alt="screen shot 2016-01-05 at 3 13 43 pm" src="https://cloud.githubusercontent.com/assets/4266958/12130432/1310e286-b3bf-11e5-8992-29bfe7a9da03.png">

Expected Behavior:
This instance should be shown in the standalone container.

**Comment by deniseschannon** [comment] 2016-01-10 05:27
This is a duplicate of : https://github.com/rancher/rancher/issues/2810.

@will-chan: I'm not sure we can fix this per @vincent99 comment in #2810.

**Closed** 2016-07-27 23:20 UTC
Labels: area/ui, kind/bug
