### ISSUE TITLE
Better UX for External Cloud provider vSphere

### ISSUE THREAD

**Issue by alena1108** [rancher/rancher#20131] opened 2019-05-09 23:43 UTC
Kubernetes initiative "Moving in-tree cloud providers out" will result in more cloud providers deployed as external. Current k8s native flow for deploying cloud provider is:

* Pass cloud provider = external flag to api server start arguments. Some additional arguments might be required as well
* Deploy external cloud provider controller as a k8s native app (daemonset)

We have to think of a better UX for that in Rancher. Initial thoughts:

* External provider toggle in the UI/API driving defaults for some cluster config fields
* Followed by out of tree provider deployment from the System catalog
* Some cloud provider manifests can be a part of RKE default addons specs.

@vincent99 @janeczku 

gz#12549

**Comment by deniseschannon** [comment] 2021-01-06 00:15
Duplicate of https://github.com/rancher/rancher/issues/23357

**Closed by deniseschannon** 2021-01-06 00:15 UTC
Labels: [zube]: Next Up, kind/enhancement, kind/feature
