### ISSUE TITLE
Unable to modify Cluster Name

### ISSUE THREAD

**Issue by timgriffiths** [rancher/rancher#13321] opened 2018-05-06 23:38 UTC
**Rancher versions:**
rancher/rancher:v2.0.0

**Docker version: (`docker version`,`docker info` preferred)**
Docker version 17.06.0-ce, build 02c1d87

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
```
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"

```
Kernel
`4.9.40`

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
Bare-metal

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
Single Node Rancher

**Steps to Reproduce:**
- Create a new bare-metal cluster
- Edit the Cluster and try and and change the Cluster Name

**Results:**
- Cluster Name dose not change.

**Comment by loganhz** [comment] 2018-05-07 10:10
Hi, @timgriffiths 
I can not reproduce this issue. Is there any error in chrome console log?

**Comment by timgriffiths** [comment] 2018-05-07 13:26
Oh Ok it to_lowers the cluster name, i was trying to change the name from "myname" to "Myname" and that wasn't working, might want to add a tool time or something about that some where.

**Comment by tfiduccia** [comment] 2018-05-07 18:49
@timgriffiths - Kubernetes does not deal with upper case letters, so we lowercase everything.  I'm going to close this cause it's not a bug.

**Closed by tfiduccia** 2018-05-07 18:49 UTC
