### ISSUE TITLE
Sidekick is not removed when removing its parent container

### ISSUE THREAD

**Issue by nunofgs** [rancher/rancher#5406] opened 2016-07-12 15:05 UTC
**Rancher Version:**
1.1.0.

**Docker Version:**
1.10.3.

**OS and where are the hosts located? (cloud, bare metal, etc):**
AWS.

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
Single node rancher.

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle.

**Steps to Reproduce:**
1. Launch a service with a sidekick.
2. Delete the main container.

**Results:** 

The sidekick is not deleted. However, the reverse is true — if you delete the sidekick, the main container is deleted.

![delete2](https://cloud.githubusercontent.com/assets/92085/16772001/62f1f464-484a-11e6-93d4-566ea1210700.gif)

**Expected:**

The sidekick should be deleted when removing its parent container.

**Comment by deniseschannon** [comment] 2016-07-12 15:44
This is by design due to design of the sidekick use case. Typically, the expected relationship is that the primary service (parent container) has some dependency on the sidekick service. 

So, when a parent container is deleted, we will re-launch another parent container on the same host as the sidekick container and reference the existing sidekick container. 

But if a sidekick container is deleted, then we automatically delete the parent container related (as we assume there is some kind of dependency, which is why you would have chosen to create a sidekick in the first place).

**Comment by ruimarinho** [comment] 2016-07-12 18:05
I think the relation is expected if the service index is respected (see https://github.com/rancher/rancher/issues/5405, but that's likely a bug).

**Comment by deniseschannon** [comment] 2016-07-29 21:54
Closing this as this is expected behavior that a sidekick would not be removed if a parent container is removed.

**Closed by deniseschannon** 2016-07-29 21:54 UTC
Labels: kind/question
