### ISSUE TITLE
SSL verify False, doesn't work on S3-compatible storage option.

### ISSUE THREAD

**Issue by MKlimuszka** [rancher/rancher#40254] opened 2023-01-23 19:07 UTC
Setup with Minio. 

Issue description:
x509: certificate signed by unknown authority, requeuing

errors, even when skip TLS verify is selected

Business impact:
This has impacted Optus in setting up their Rancher DR strategy

I have provided a workaround with persistent volumes, however they want to use Minio in future

Troubleshooting steps:
Tried with TLS verify on and off, same result

Repro steps:

    setup backup job on Minio without certs
    try to backup

Actual behavior:
<text>

Expected behavior:
TLS verify should skip ignore the self signed certificates

See original ticket for logs. 
SURE-3153

**Comment by MKlimuszka** [comment] 2023-01-23 19:08
This needs to be reproduced in 2023-Q1-2.6x and 2023-Q1-2.7x

**Comment by nflynt** [comment] 2023-02-13 20:12
Working with @eliyamlevy, I was unable to reproduce this issue on `v2.7-head` or `v2.6-head`. In both cases, using a self-signed SSL certificate in front of minio, the backup fails as expected with "Skip TLS Verifications" **unchecked**, and succeeds with "Skip TLS Verifications" **checked**. This appears to be fixed in the latest builds of both release branches.

**Closed** 2023-02-13 21:06 UTC
Labels: kind/bug, internal, area/backup-recover, status/to-reproduce, [zube]: Next Up, kind/good-first-issue, team/area3

**Comment by superseb** [comment] 2023-02-14 08:05
Fixed in https://github.com/rancher/backup-restore-operator/issues/254
