### ISSUE TITLE
A host cannot connect the container of B host

### ISSUE THREAD

**Issue by 1026524749** [rancher/rancher#10612] opened 2017-12-18 10:04 UTC
*Describe your issue here*
I have three centos7.2 host A，B，C 
The three hosts have been running for more than a month.A few days ago sudden business failure, business cannot access.I found that the lb container could not distribute data to the business container.
The lb container is deployed on A host and cannot be connected to the business container on the B host, but the container on the C host is normal.

The test found that the firewalls of the three main engines were normal, the 500 and 4500udp ports were normally open, and the firewall strategy was normal.
Testing is also connected using the nc command.
Use the route command traceroute to test
 A host - > container of B failed
B Host - > container of A failed
C host - > container of AB success
AB host - >  container of C success

I checked the host IP and checked the DNS container of A host and found it was normal
---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v1.6.3` Cattle: `v0.181.13` UI: `v1.6.9` |
|Access|`localauth` `admin`|
|Orchestration|`Cattle`|
|Route|`hosts.index`|

**Comment by superseb** [comment] 2017-12-18 12:09
Are you using `ipsec` as overlay network?

There have been many improvement in keeping the overlay network healthy (i.e. ipsec tunnels retry) in the past releases, please update to v1.6.12 and see if this solves your problem. If not, please reply so we can investigate. Closing for now as not a bug, let me know if you need any other information.

**Closed by superseb** 2017-12-18 12:09 UTC
