### ISSUE TITLE
Switching between services in a stack requires reload to show container metrics

### ISSUE THREAD

**Issue by gordontyler** [rancher/rancher#2887] opened 2015-12-03 15:08 UTC
If I'm viewing the containers page for a service in a stack (example URL: http://torgtylervm1/apps/1e5/services/1s390/containers), and then switch to another service in the same stack using the dropdown in the breadcrumb, the container metric graphs for the service don't load (the area where they should be is just blank). I have to reload the page in the browser to get the container metrics graphs to load.

Navigating out to the stack page and then back into a different service works as expected, loading the container metric graphs. It's only when switching between services using the dropdown that the problem occurs.

--
Rancher	v0.47.0
Cattle	v0.115.0
User Interface	v0.68.0
Rancher Compose	v0.5.3

**Comment by deniseschannon** [comment] 2015-12-30 23:24
Verified this is a UI issue in v0.51.0.

Steps to Reproduce:
1. Create and start 2 services in 1 stack.
2. Click on detailed service view, which show container stats. 
3. Using drop-down, select the other service for the detailed service view.

Result: Container stats on second service don't come up unless you refresh the browser.

Expected result: Container stats to show up after switching services.

**Comment by vincent99** [comment] 2016-03-08 20:20
I think we fixed this a while ago?

**Comment by deniseschannon** [comment] 2016-03-09 19:56
Still broken in v0.61.0-rc3

**Comment by JayHaoDing** [comment] 2016-03-10 00:11
Seems this issue does not exist in our environment with Rancher v59.1

**Comment by tfiduccia** [comment] 2016-03-22 22:58
Version - master 3/22
Not fixed?

**Comment by tfiduccia** [comment] 2016-06-10 05:12
Version - master 6/9
Verified fixed - looks like it's fixed now.

**Closed by tfiduccia** 2016-06-10 05:12 UTC
Labels: area/stats, area/ui, kind/bug, status/resolved, status/to-test
