### ISSUE TITLE
CA check improvements for `rancher-agent`

### ISSUE THREAD

**Issue by snasovich** [rancher/rancher#45582] opened 2024-05-23 02:52 UTC
Placeholder
SURE-8076

**Comment by snasovich** [comment] 2024-05-28 19:55
Blocked on design review currently.

**Comment by MbolotSuse** [comment] 2024-05-29 20:20
Depends on #45628.

**Comment by Sahota1225** [comment] 2024-07-02 18:02
https://github.com/rancher/rancher/issues/45974

**Comment by markusewalker** [comment] 2024-07-02 19:45
Tested this with results over in Qase test run /RM/1631. I noted the following failure:

|#|Scenario|Result|
|---|---|---|
|4|Setup Rancher with valid ca-certs and `agent-tls-mode=system-store`|:x:|

**VALIDATION STEPS**
1. Setup Rancher v2.9-head with a valid cert.pem and/or key.pem file.
     - Ensured  `agentTLSMode=system-store` in the helm install command.
2. Ran command `kubectl get settings agent-tls-mode -o yaml` and noted that the value is `strict`.

There are two other scenarios that have the same steps as above that have not been tested yet due to this failure. Marking as blocked until this is resolved.

**Comment by MbolotSuse** [comment] 2024-07-02 20:22
@markusewalker Can you provide more details? The default on 2.9.0 will be strict, but the actual value should be as in the helm command, `system-store` - your output doesn't provide sufficient detail to determine if that is the case.

**Comment by markusewalker** [comment] 2024-07-02 20:32
@MbolotSuse sure, updated my comment with the information we discussed offline.

**Comment by mallardduck** [comment] 2024-07-02 20:45
@markusewalker - Can you verify what the helm command is actually rendering templates into? I'm able to verify that based on the `release/v2.9` branch the chart should set Env variables as expected. So I'd like to confirm what you're seeing there to identify if the issue is with the helm chart, or "after the chart".

For instance, in my testing I can see:

Default values file (no ENV var expected):
```
→ helm template ./chart/|grep -A1 CATTLE_AGENT_TLS
```

And when I set the `agentTLSMode` we see:
```
→ helm template ./chart/ --set agentTLSMode=system-store|grep -A1 CATTLE_AGENT_TLS
        - name: CATTLE_AGENT_TLS_MODE
          value: "system-store"
```

**Comment by markusewalker** [comment] 2024-07-02 21:43
@mallardduck is `helm template` the only means in which this can be tested? I used the following command:

```
helm install rancher rancher-latest/rancher --namespace cattle-system --set global.cattle.psp.enabled=false \
 --set ingress.tls.source=secret  --set hostname=$NAME --set rancherImageTag=v2.9-head \
 --set bootstrapPassword=<retracted>--set agentTLSMode="system-store"
```
If so, I can attempt to retest. I had used this method as the reference guide given implied that `helm install` should work.

**Comment by mallardduck** [comment] 2024-07-03 00:47
@markusewalker - No it's just the easiest way to directly see the rendered helm results w/o a cluster. You can also do the install command you shared, but append `--dry-run --debug` and get similar results to the `helm template` command. However that method does require a k8s cluster for some minimal (hence dry run) cluster state checking.

However, I see that the issue and it's much more simple than that and I believe you're not using the correct chart. From what I can see the newest chart published in `rancher-latest` helm repo is `v2.9.0-rc1` from May 7th. The changes to add this feature to the chart itself were only merged 4 days ago so will not be in `v2.9.0-rc1` charts.

@MbolotSuse - I'm not familiar with this area, wondering if you are? I assume they need a `v2.9.0-rc2` since charts probably aren't published on alpha by design? Or maybe should they just test from the local `./charts` folder?

**Comment by markusewalker** [comment] 2024-07-03 15:09
@mallardduck `v2.9.0-rc7` recently became available. I will try with that version and see if I have successful results.

**Comment by markusewalker** [comment] 2024-07-03 15:57
Re-ran the test cases outlined in Qase test run /RM/1631. Using `v2.9.0-alpha7`, I was successfully able to  validate this issue. Summary of the scenarios tested provided below:

|#|Scenario|Result|
|---|---|---|
|1|Validate Rancher is accessible with valid ca-certs|:white_check_mark:|
|2|Validate Rancher is inaccessible with invalid ca-certs|:white_check_mark:|
|3|Validate Rancher is unusable with invalid ca-certs and `agentTLSMode=system-store`|:white_check_mark:|
|4|Validate Rancher is accessible/usable with valid ca-certs and `agentTLSMode=system-store`|:white_check_mark:|
|5|Update `agentTLSMode` from `strict` to `system-store`|:white_check_mark:|
|6|Update `agentTLSMode` from `system-store` to `strict`|:white_check_mark:|
|7|Upgrade Rancher from v2.8-head -> v2.9-head|:white_check_mark:|
|8|Upgrade Rancher from v2.8-head -> v2.9-head w/`agentTLSMode=strict`|:white_check_mark:|

**Closed by markusewalker** 2024-07-03 15:57 UTC
Labels: kind/enhancement, area/agent, kind/feature, priority/0, internal, team/hostbusters, JIRA
