### ISSUE TITLE
glusterfs-server_glusterfs-daemon won`t start after host reboot

### ISSUE THREAD

**Issue by clicman** [rancher/rancher#4817] opened 2016-05-16 19:23 UTC
I have glusterfs cluster on 3 nodes.
When I reboot first node
Then all come up except glusterfs-server_glusterfs-daemon
It keeps restarts

Logs: http://pastebin.com/8KnMHUEX

Even daemon container falis to start, volume automatucully mounts and replication works.

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v1.1.0-dev1` Cattle: `v0.160.3` UI: `v1.0.7` |
|Access|`github` `admin`|
|Route|`hosts.index`|

**Comment by deniseschannon** [comment] 2016-06-07 17:13
I was unable to reproduce. I tried rebooting my nodes that were running glusterfs cluster and had no issues of them coming up.

**Comment by clicman** [comment] 2016-06-07 18:11
Just deployed glusterfs stack from catalog (on 1.0.2 now) and right after deployment finished tried to upgrade it (point host labels on scheduling) and glusterfs dameon falis to start.
Logs: http://pastebin.com/g5gRAMXd
Different error now, but daemon problem again. And cancelling upgrade not fixes the problem.

Wait 15 minutes please. I'll write another comment with original use-case result...

**Comment by clicman** [comment] 2016-06-07 19:13
Hmm... Could not reproduce original problem on 1.0.2

**Comment by deniseschannon** [comment] 2016-06-07 21:08
I'll close this as I was unable to reproduce on v1.1.0-dev4-rc1 (latest dev release), please re-open if you have further issues.

**Closed by deniseschannon** 2016-06-07 21:08 UTC
Labels: kind/question
