### ISSUE TITLE
rancher load balancer 503's

### ISSUE THREAD

**Issue by jmreicha** [rancher/rancher#5225] opened 2016-06-22 20:32 UTC
**Rancher Version:** `1.0.1`

**Docker Version:** `1.9.1`

**OS and where are the hosts located? (cloud, bare metal, etc):** `AWS - CoreOS`

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)** `Single node internal DB`

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)** `Cattle`

**Steps to Reproduce:**

I'm not really sure how exactly to reproduce this because it has only happened a few times in total.  Every so often the internal Rancher lb seems to "get stuck" and starts giving 503 errors.  The most recent time this happened I had just added a new service and a new internal Rancher load balancer.  After adding the new service and lb my front facing lb started sending 503's.

I have been able to fix the issue by stopping and starting the Rancher load balancer but this obviously isn't ideal.

I don't see anything to indicate a problem in the Rancher lb logs, is there anything else I can look at?

I realize that this probably isn't the easiest thing to diagnose and troubleshoot.

**Comment by bacheson** [comment] 2016-06-23 15:05
+1

I've experienced this exact problem. I didn't report the issue because I struggled with how to adequately describe it. Certain hosts become unreachable by the LB service host. Rebooting the LB or restarting the network container on the service host resolves the issue. Pinging the service IP from the LB host simply hangs and I don't see any errors logged. It looks like a cattle network issue.

**Comment by jmreicha** [comment] 2016-06-23 16:47
Hopefully I have described the issue adequately.  I also didn't want to report this because it is difficult to explain and reproduce, but it has happened enough times now that I feel like it isn't just a coincidence.

I'm happy to provide more details in specifics if needed.

**Comment by deniseschannon** [comment] 2016-06-23 18:30
It sounds as if the haproxy.cfg is not being re-configured after some specific use case/steps. As if you restart the LB, it will re-trigger the configuration of the LB. 

It will be a bit hard to reproduce on my end without reliable steps. :)

If you know who to trigger it exactly (like it happens after adding a new X and then i get 503), that'd be great. After it happens, you can verify it by exec- into the load balancer and look at the `/etc/haproxy/haproxy.cfg' to see if it's programmed your new additions.

**Comment by jmreicha** [comment] 2016-06-23 19:00
I'll have to do some testing to see if I can get it to break.  Exec'ing into the container after it breaks should be easy enough at least.

I will update if I have any luck, otherwise, hopefully somebody else is able to reproduce this and can help diagnose.

**Comment by ebreton** [comment] 2017-01-30 21:11
I am linking some other issues that look connected:

* random 503 with https://github.com/rancher/rancher/issues/7579
* plain 503 with https://github.com/rancher/rancher/issues/7579
* an new error on the logs which is not directly connected but does not help with the diagnostics: https://github.com/rancher/rancher/issues/7591

**Comment by tiant167** [comment] 2017-02-18 03:47
We're having similar issue, any progress? We have laready upgraded to 1.4.1, but still not work. thx

**Comment by rostved** [comment] 2017-03-01 19:16
Make sure to have UDP 500 and 4500 open on all hosts. I've experienced similar symptoms only to find that port 4500 was closed on the host running the service-container. The load balancer was running from two other hosts, and only one of them could ping the service. Opening port 4500 resolved it.

**Comment by ebreton** [comment] 2017-03-01 19:53
On my side, I had the issue with one host only.

**Comment by oskapt** [comment] 2017-04-08 22:14
You can enable statistics within HAProxy by adding something like this to the default block in the Rancher config:
```
defaults
  stats enable  
  stats realm Haproxy\ Statistics
  stats uri /ty2775
  stats auth haproxy:s33kretp4ss  
```

After saving it will activate statistics on every URL at the path `/ty2775` (so you might want to change that for your installation). You'll be able to log in with the `username:password` combo provided in the `stats auth` line.

This will show you what HAProxy sees, but at the moment Rancher doesn't do any health checking within HAProxy. It might still be useful for determining what frontends and backends exist in the config.

You can also shell into the container and look at `/etc/haproxy/haproxy.cfg`. Rancher routes from frontend to backend by ACL, matching on port or Host/SNI information according to what you've configured.

Sometimes an error in the configuration prevents a reload. HAProxy is smart enough not to reload a broken config, but if you restart the container, it has no choice. From within the container you can test the config with `haproxy -c -f /etc/haproxy/haproxy.cfg`. This will show you errors in the config, and usually this is the same output that will be visible in the container logs (albeit on a single line there).

HAProxy throws a 503 when it doesn't know where to send the request. This means that there's no backend (route failure), it can't resolve the backend's IP from the hostname, the backend is down (if health checking is enabled), or the backend timed out. We have liberal timeouts in the config, and we build the config with container IPs to avoid latency from DNS lookups against the internal resolver. Route failure is unlikely unless the request doesn't provide what we need, and we don't do health checking. 

You can try adding the following and then waiting until it fails again to see if there's any output, but there's no guarantee that it will capture anything useful:
```
global
  log /dev/stdout local0 info
  debug

defaults
  log global
```

All HAProxy is doing is routing from request to backend. If you capture it throwing a 503, take the time to test it and see where in the chain it's failing:

* The container is based on Ubuntu 16.04, so you can run `apt-get -qq update` and `apt-get -qq install telnet net-tools curl`
* With those installed, consider that the 503 means "I can't send this anywhere." Telnet from the haproxy container to your backend on its IP and port and see if it responds.
* If it responds, hit it with `curl -I` (providing the Host: header if necessary) and see if you get back a 200.
* If the backend is responding, hit HAProxy's frontend port directly from within the container, passing the Host header so that it routes from frontend to backend as it would from the outside
* If all of that works, and if you're fortunate enough to have captured this event on a site or instance with minimal traffic, you can try to capture data with `tcpdump` coming into the frontend and going out to any backend, and see if HAProxy is sending the inbound traffic to where it's supposed to go.

You can also dump and review the HAProxy config with `docker cp <container_id>:/etc/haproxy/haproxy.cfg .` and take a look at it. Make sure that it's not routing to a bad default or that what it expects for its ACLs is correct.

Hopefully this gives everyone enough information to do some troubleshooting the next time this comes around.

**Comment by aemneina** [comment] 2017-05-19 02:01
there's a lot of good troubleshooting info on this thread. Closing out, if anyone has any new issues with a modern version of rancher... please do file them.

**Closed by aemneina** 2017-05-19 02:01 UTC
Labels: area/balancer, kind/bug
