### ISSUE TITLE
Cluster provisioning stuck on waiting for API to be available when using RHEL 8.4 AMI on a Node driver RKE1 cluster

### ISSUE THREAD

**Issue by timhaneunsoo** [rancher/rancher#36526] opened 2022-02-15 19:58 UTC
**Rancher Server Setup**
- Rancher version: v2.6-head 11a7451
- Installation option (Docker install/Helm Chart):
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): rke1

**Information about the Cluster**
- Kubernetes version: 1.21.8
- Cluster Type (Local/Downstream):
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider): RKE1 EC2 AWS

**User Information**
- What is the role of the user logged in? (Admin/Cluster Owner/Cluster Member/Project Owner/Project Member/Custom)
  - If custom, define the set of permissions: Standard User

   
**Describe the bug**

User is trying to deploy RKE1 aws node driver cluster using a public RHEL 8.4 ami. Cluster seems to be stuck on `Waiting for API to be available`
<img width="565" alt="Screen Shot 2022-02-15 at 2 05 44 PM" src="https://user-images.githubusercontent.com/97477402/154138017-36e8c2c4-ecf3-48a4-a0f7-8c547bf180a1.png">
This issue occurred on 2.6.3 v1.21/v1.22 and 2.6-head v1.21/v1.22

**To Reproduce**
 
1. Deploy RKE1 aws node driver cluster using a public RHEL 8.4 ami
2. Check status of deployment

**Result**
Deployment status is stuck on "Waiting" with the message "Waiting for API to be available" below.

**Expected Result**

Deployment is successfully deployed.

**Screenshots**

**Additional context**

The same AMI wasn’t able to finish running the docker install script when attempting to install manually

The kube-apiserver log gives a 503 error
![image](https://user-images.githubusercontent.com/97477402/154138709-5314b3ff-887f-48b9-b383-face3ced622c.png)

The ports seem to be listening, as expected
![image](https://user-images.githubusercontent.com/97477402/154138824-29a0329f-004c-4a67-aa69-e502166c49cf.png)

The cluster agent log on the control plane node gives the following message on the last line
`time="2022-02-15T15:59:51Z" level=info msg="Removing unmanaged agent /elegant_shannon(address)"`

The release version is correct
![image](https://user-images.githubusercontent.com/97477402/154139020-0d20d3d3-0f67-4e4b-94f2-11034be7e767.png)

There were no unexpected restarts (I manually restarted kube-apiserver to see if that would do anything)
![image](https://user-images.githubusercontent.com/97477402/154139108-df5cf16b-9fb1-479d-b13c-45a28316d4c9.png)

**Comment by snasovich** [comment] 2022-04-18 20:57
Moving to 2.6.6 as it's not a regression (been this way since at least 2.6.3).

**Comment by HarrisonWAffel** [comment] 2022-05-05 18:37
I've been able to reproduce this issue, but have observed slightly different behavior than Tim. Provisioning a RHEL 8.4 node (`ami-0b0af3577fe5e3532`, `Red Hat Enterprise Linux release 8.4 (Ootpa)`) with the AWS node driver does fail, however from what I can see it fails when performing port checks. I have not been able to get a cluster stuck in a `Waiting For API` state, however I suspect that both issues stem from the same root issue. This is the error I have observed: 

```
[INFO ] [network] Successfully started [rke-port-checker] container on host [44.203.82.99]
[ERROR] [[network] Host [44.203.82.99] is not able to connect to the following ports: [10.0.12.3:2379]. Please check network policies and firewall rules]
```

From what I can see, these port checks are failing due to RHEL 8.4's inclusion of NetworkManager. This is a known issue and is documented here: https://rancher.com/docs/rancher/v2.6/en/cluster-provisioning/node-requirements/#oracle-linux-and-rhel-derived-linux-nodes . The fix included in the linked documentation is not possible for nodes provisioned using the AWS Node Driver, as that process is entirely controlled by rancher-machine. This service should be disabled by rancher-machine to prevent this issue from occurring. 


Also, I suspect the error Tim ran into regarding manually running the install-docker script may be due to a version mismatch, RHEL 8.4 only supports the [install script for 20.10.7](https://www.suse.com/assets/EN-Rancherv2.6.4-150422-0151-56.pdf), whereas the latest is 20.10.12. I can confirm that version 20.10.12 does fail to run on RHEL 8.4, however that is expected.

**Comment by HarrisonWAffel** [comment] 2022-05-13 21:11
### Root cause
  RHEL 8.4 includes two NetworkManager services which interfere with CNI's. This issue is documented here: https://rancher.com/docs/rancher/v2.6/en/cluster-provisioning/node-requirements/?#oracle-linux-and-rhel-derived-linux-nodes, however the fix included in the linked documentation is not possible for nodes provisioned using the AWS Node Driver as that process is entirely controlled by rancher-machine.
### What was fixed, or what changes have occurred
  When provisioning RHEL 8.4, rancher-machine will disable the two disruptive services and reboot the host before attempting to install docker. 
### Areas or cases that should be tested
  The creation of a RHEL 8.4 node using an EC2 node driver
  + Create an RKE1 node template using a RHEL 8.4 AMI (such as, `ami-0b0af3577fe5e3532`)
  + Create a new cluster using this node template
  + observe the nodes go into an `active` state
### What areas could experience regressions?
  The creation of other RHEL versions, however the fix is localized to 8.4 so it is unlikely other versions will be effected.

**Closed** 2022-05-20 15:16 UTC
Labels: kind/bug-qa, [zube]: QA Working, QA/XS, team/area2

**Comment by moonlight16** [comment] 2022-09-01 21:28
I'm hitting this issue on RHEL8.6.  I realize the 8.6 is not in the test matrix yet, but I did get this working earlier. For various reasons, I had to tear down my k8s cluster and re-install.  Now its not working with this problem.

As this issue suggests, I checked for nm-cloud-setup.service nm-cloud-setup.timer.  These do not exist on my nodes.  Any suggestions?

**Comment by 631068264** [comment] 2022-09-02 02:28
same error  in centos
```
time="2022-09-02T01:58:31Z" level=info msg="Removing unmanaged agent /modest_napier(03c295c07307ebac5a8fcf0157f2ca28c125333cd13dbfb7817b7a5302ca5b3a)"
```

And I can't find any error in Provisioning Log

**Comment by HarrisonWAffel** [comment] 2022-09-02 17:28
@moonlight16 What version of Rancher are you using? [RHEL 8.6 was added to the support matrix for v2.6.7](https://www.suse.com/suse-rancher/support-matrix/all-supported-versions/rancher-v2-6-7/). If upgrading Rancher to 2.6.7 does not resolve your issue, please look for an existing ticket and if you cannot find one then please create a new one with as much information as possible. 

@631068264 The log message you've included is not informative enough for me to determine if your issue is the same issue as this ticket, as that message can appear under a number of circumstances. 

In general, closed issues are not actively monitored and are not typically reopened once QA validation has passed. Please look for existing tickets, or create new ones for your issues. For your reference, here is a list of support matrices for recent Rancher versions: https://www.suse.com/suse-rancher/support-matrix/all-supported-versions/rancher-v2-6-7/. Hopefully we can resolve both of your issues in separate / new tickets
