### ISSUE TITLE
[rancher-compose] Support for Multiple Compose Files?

### ISSUE THREAD

**Issue by chkelly** [rancher/rancher#2626] opened 2015-11-10 05:53 UTC
Following along here..

https://docs.docker.com/compose/extends/

It looks like rancher-compose doesn't support multiple compose files (-f arguments).

For example. Heres my docker-compose.yml file

```
movie-quotes:
  image: chkelly/python-movie-quotes:v1.0.4
  links:
   - redis
  restart: always
  tty: true
  stdin_open: true
  ports:
   - 8080
redis:
  image: redis
  ports:
   - 6379
```

heres my docker-compose.prod.yml file

```
movie-quotes-lb:
  ports:
  - 8004:8080
  restart: always
  labels:
    io.rancher.scheduler.global: 'true'
  tty: true
  image: rancher/load-balancer-service
  links:
  - movie-quotes:movie-quotes
  stdin_open: true
```

If I run the following...

```
$ rancher-compose -f docker-compose.yml -f docker-compose.prod.yml up
INFO[0000] Creating stack python-movie-quotes
ERRO[0000] Failed to find movie-quotes
ERRO[0000] Failed to find movie-quotes
INFO[0000] Creating service movie-quotes-lb
WARN[0000] Failed to find service movie-quotes to link to
INFO[0001] Project [python-movie-quotes]: Starting project
ERRO[0001] Failed to find movie-quotes
ERRO[0001] Failed to find movie-quotes
INFO[0001] [0/1] [movie-quotes-lb]: Starting
WARN[0001] Failed to find service movie-quotes to link to
INFO[0029] [1/1] [movie-quotes-lb]: Started
INFO[0029] Project [python-movie-quotes]: Project started
```

However if I run..

```
$ cat docker-compose.yml docker-compose.prod.yml > docker-compose.tmp.yml

$ rancher-compose -f docker-compose.tmp.yml up
INFO[0000] Creating service redis
INFO[0000] Creating service movie-quotes
INFO[0001] Project [python-movie-quotes]: Starting project
INFO[0001] [0/3] [redis]: Starting
INFO[0016] [1/3] [redis]: Started
INFO[0016] [1/3] [movie-quotes]: Starting
....
```

Everything starts up correctly.

**Comment by Rucknar** [comment] 2015-11-10 12:41
I've used extends before with rancher compose. Our usage didn't quite look like the above though.

We had something along the lines of: 

docker-compose.yaml
```
web:
  extends:
    file: common.yml
    service: default-web
  image: web
```
common.yml
```
default-web:  
  ports:
  - 80:80
  restart: always
  labels:
    io.rancher.scheduler.global: 'true'
  tty: true
  stdin_open: true
```

**Comment by deniseschannon** [comment] 2015-11-10 18:00
It will be fixed when this issue is addressed in libcompose. https://github.com/docker/libcompose/issues/98

**Comment by deadbeef84** [comment] 2016-02-03 17:25
The issue is now fixed in libcompose, when will we see it in rancher-compose?

**Comment by deniseschannon** [comment] 2016-02-03 17:51
Yes, this should be in our next rancher-compose release when we rebase our Godeps of libcompose.

**Comment by deniseschannon** [comment] 2016-02-10 18:42
Using v0.7.2-rc1, which has the latest updates from libcompose, it seems to only use the last file when multiple `-f` are used. 

dc1.yml

```
s1:
  image: nginx
```

dc2.yml
```
s2:
  image: nginx
```

```
$ rancher-compose -p multiple1 -f dc1.yml -f dc2.yml up
INFO[0000] Creating stack multiple1     
# Ignores services in dc1.yml                
INFO[0000] Creating service s2                          
INFO[0000] Project [multiple1]: Starting project        
INFO[0000] [0/1] [s2]: Starting                         
INFO[0004] [1/1] [s2]: Started  
```

```
$ rancher-compose -p multiple2 -f dc2.yml -f dc1.yml up
INFO[0000] Creating stack multiple1   
# Ignores services in dc2.yml                  
INFO[0000] Creating service s2                          
INFO[0000] Project [multiple1]: Starting project        
INFO[0000] [0/1] [s2]: Starting                         
INFO[0004] [1/1] [s2]: Started  
```

**Comment by mentholi** [comment] 2016-02-24 15:00
Hopefully this can be fixed in near future. I just noticed this when I tried to do separate Compose files for different environments. It seems that I need to manually concatenate those files for now or is there any better workaround?

**Comment by deniseschannon** [comment] 2016-03-20 00:56
Verified with v0.8.0-rc1. Able to pass in 2 compose files and have all services in both file start.

**Comment by deniseschannon** [comment] 2016-03-23 18:08
We will be release v0.7.3 with GA and will need to re-verify when we add a new v0.8.0-rcx.

**Comment by Rucknar** [comment] 2016-03-31 10:17
@deniseschannon to clarify, has this been released with GA?

**Comment by deniseschannon** [comment] 2016-03-31 17:18
@Rucknar No, this has not been released with GA, which is why it's still open and has a Milestone of 1.1. :) 

Sorry for the confusing language. I had verified with v0.8.0-rc1, but we did not end up bumping to that version for GA.

**Comment by deniseschannon** [comment] 2016-04-29 20:22
Verified with v0.8.0-rc3

**Closed by deniseschannon** 2016-04-29 20:22 UTC
Labels: area/rancher-compose, kind/enhancement, status/to-test
