### ISSUE TITLE
K8S - kubectl CLI unable to connect

### ISSUE THREAD

**Issue by DaveBlooman** [rancher/rancher#3953] opened 2016-03-13 15:23 UTC
Rancher Version: 0.63

Docker Version: 1.9.1

OS: Rancher - 4.2.3 Server - OSX local

Steps to Reproduce: 

1. Create K8s cluster
2. Copy config from kubectl window to local machine.  
3. Attempt to run any kubectl command, e.g ` kubectl version`

Results: `error: couldn't read version from server: an error on the server has prevented the request from succeeding`

Expected:  kubectl to show client and server version.,

I am using Github auth, is this preventing the client access?

**Comment by ibuildthecloud** [comment] 2016-03-13 15:28
Kubectl only allows sending credentials if the server is SSL.  This means you need to run rancher behind SSL.  Refer to http://docs.rancher.com/rancher/installing-rancher/installing-server/basic-ssl-config/ for more info about SSL.

**Comment by ibuildthecloud** [comment] 2016-03-13 15:30
We have a new CLI coming for Rancher that will allow you to do `rancher kubectl get po` that will make this process easier.

**Comment by ibuildthecloud** [comment] 2016-03-22 05:28
We have made some magical unicorn changes such that even if Rancher server isn't running with SSL enabled kubectl will still work.  This is because port 8080 is actually now capable of serving http or https.  In short, in the next release the generate kubectl config will work regardless of whether you have SSL or not, or if you've enabled authentication or not.

**Comment by deniseschannon** [comment] 2016-03-23 03:16
@DaveBlooman Would you be able to test to see if this works for you using v1.0.0-rc1?

**Comment by deniseschannon** [comment] 2016-03-28 19:04
@DaveBlooman This has been fixed in our v1.0.0-rcX releases. If you still have issues, please re-open.

**Closed by deniseschannon** 2016-03-28 19:04 UTC
Labels: area/kubernetes, kind/bug, priority/0, status/resolved, status/to-test

**Comment by Yermouth** [comment] 2016-07-27 07:55
Rancher version: 1.1.1

Docker Version: 1.11.1

Rancher cluster: a list of ubuntu 14.04 instance in GCE

OS with kubectl installed: Windows 7 professional

Steps to Reproduce:

1. Created a 4-host kubernetes cluster

2. Generate and Copy config from kubectl page to local machine (i.e. placed config under C:\Users\XXXXX\.kube ).

3. run `kubectl` command 

Results: `Unable to connect to the server: http: server gave HTTP response to HTTPS client`

and when I change the server address from https:// to http:// , I get 

Results: `error: couldn't read version from server: an error on the server has prevented the request from succeeding`

I am currently using http for the rancher server. I have tried v1.3.0 for both windows/amd64 and windows/386 but get the same error.

I remember that I have successfully use command like `kubectl get service` with my remote cluster before with using HTTP, but when I enable the access control function and change the config, it cannot work anymore. 

May I know if this problem is related to SSL or other config issues? Thanks.
