### ISSUE TITLE
No stats available for both hosts and containers

### ISSUE THREAD

**Issue by jonvargas** [rancher/rancher#3616] opened 2016-02-13 20:21 UTC
**Brief:**

The statistical blocks are not displayed for both containers and hosts detail views.

**Environment:**

Rancher	v0.59.0
Cattle	v0.148.0
User Interface	v0.90.0
Rancher Compose	v0.7.2
Rancher server installed on bare metal and used as a host too.

Container view:
http://i.imgur.com/6JGzCWI.png

Host view:
http://i.imgur.com/Z6VFjCn.png

**Comment by sfarges** [comment] 2016-02-14 16:24
Same as #3384 ?

**Comment by deniseschannon** [comment] 2016-02-14 17:12
What version of Docker are you using? If using Docker 1.10, it's a duplicate of https://github.com/rancher/rancher/issues/3615

**Comment by deniseschannon** [comment] 2016-03-05 04:58
Closing in favor of the other 2 issues.

**Closed by deniseschannon** 2016-03-05 04:58 UTC
