### ISSUE TITLE
Nutanix Rancher Node Driver 

### ISSUE THREAD

**Issue by Sahota1225** [rancher/rancher#36348] opened 2022-02-01 21:23 UTC
Integrate Nutanix Rancher Node driver in the default node drivers provided by Rancher.
It should not be enabled by default.

**Comment by paynejacob** [comment] 2022-02-07 19:19
https://github.com/nutanix/docker-machine

We need to add the node driver to rancher https://github.com/rancher/rancher/blob/908854bfedf1f8ddadb87453f4a162aaf37a86be/pkg/data/management/machinedriver_data.go

additionally we will need to define the public and private fields for the driver here https://github.com/rancher/rancher/blob/908854bfedf1f8ddadb87453f4a162aaf37a86be/pkg/data/management/machinedriver_data.go#L35

this will require a UI issue as well to create the forms in the  UI for the driver.

**Comment by snasovich** [comment] 2022-02-07 19:40
@paynejacob , there is already PR for this which also has Ember UI part linked - https://github.com/rancher/rancher/pull/35348 (should have linked it earlier).
Whether we're doing Vue (dashboard) UI is TBD at this time.

**Comment by snasovich** [comment] 2022-03-03 21:15
@tuxtof , merged your PR and moved this issue to test. Since your team is handling testing, could you or anyone from your team please test it on `v2.6-head` and confirm it's working as expected?

**Comment by tuxtof** [comment] 2022-03-04 16:34
@snasovichjust deploy a `v2.6-head` rancher, driver is here , enabling is OK, deploying cluster create correctly the VM, was just blocked due to some container missing in my env
do we have a doc to fully deploy a working dev branch based instance

**Comment by snasovich** [comment] 2022-03-05 02:46
@tuxtof , could you please clarify what you mean by a "doc to fully deploy a working dev branch based instance"?
You can do single node Docker install following the docs here: https://rancher.com/docs/rancher/v2.6/en/installation/other-installation-methods/single-node-docker/
Just use `rancher/rancher:v2.6-head` image to use the latest successfully built image from `release/v2.6` branch.

**Comment by tuxtof** [comment] 2022-03-07 11:05
@snasovich 
i correctly deploy the builded commit with the classic single node docker approach no problem with that
my question was more to deploy a cluster with this builded branch
as he try to pull a rancher/agent:commit i put everything in a private repo and configure the cluster to use it
but it seems it don't work
![image](https://user-images.githubusercontent.com/180613/157019415-707a04e1-179b-4b49-8052-2c28817102e1.png)
that's why i ask if there is a specific doc

**Comment by snasovich** [comment] 2022-03-07 21:29
@tuxtof , I'm not sure I'm following exactly what you're running into.
Could you please share the exact reproduction steps?
Also, since there seems to be an issue with the agent, could you please share logs from `cattle-cluster-agent-...` pod?

Lastly, just a few hours ago we've put a change to default `v2.6-head` Rancher to use `v2.6-head` agent: https://github.com/rancher/rancher/blame/release/v2.6/pkg/settings/setting.go#L26 - so maybe that will ensure you're using the agent image you're expecting?

**Comment by tuxtof** [comment] 2022-03-08 07:35
@snasovich i just test with v2.6.4-rc6 binary release and all works perfectly
so i think we can close this issue

for info
i also test building f2a4147cf and i have a new issue
kubernetes version dropdown list is empty
![image](https://user-images.githubusercontent.com/180613/157188486-4bce6053-5cb6-4f1d-8057-db2f987b751a.png)

**Comment by snasovich** [comment] 2022-03-08 15:22
@tuxtof , great to hear it's working fine for you.

Regarding the other you're reporting, I'm not seeing it myself. Could you please share more about how you've reproduced it?
k8s versions dropdown values come from request to `/settings` API call the browser makes and the resulting JSON should have a setting named `k8s-versions-current`. Could you check this on your setup?

**Comment by tuxtof** [comment] 2022-03-09 06:52
procedure to reproduce it 
run on a fresh Ubuntu 21.04/docker 20.10.12
gh repo clone rancher/rancher && cd rancher
git checkout f2a4147cf
make
docker run -d --restart=unless-stopped -p 80:80 -p 443:443 --privileged rancher/rancher:f2a4147cf


a `/settings` return

![image](https://user-images.githubusercontent.com/180613/157378702-ad155101-73b2-43e5-946e-f1a7f72227ea.png)

for info i test with a more recent commit and no more issue

you can close this issue in all case

**Comment by snasovich** [comment] 2022-03-09 21:17
@tuxtof , this may be due to Rancher not picking up KDM data yet since your versions data is empty. There is a URL that Rancher polls to get data like k8s versions, so maybe polling didn't happen properly for some reason (e.g. bad URL).
It's configured in settings like shown on screenshot below:
![image](https://user-images.githubusercontent.com/85187633/157537292-cd171a13-9864-41c5-b57d-4a0256dbcf98.png)

Given that you confirmed it's not reproducible on newer versions and the fact you confirmed Nutanix node driver is working as expected, closing this issue.

**Closed** 2022-03-22 02:22 UTC
Labels: internal, [zube]: QA Working, team/area2
