### ISSUE TITLE
Cluster owners can't manage cluster members if they only have global user-base permissions

### ISSUE THREAD

**Issue by bashofmann** [rancher/rancher#36252] opened 2022-01-25 09:44 UTC
**Rancher Server Setup**
- Rancher version: 2.6.3
- Installation option (Docker install/Helm Chart): both
- Proxy/Cert Details: none

**Information about the Cluster**
- Kubernetes version: All
- Cluster Type (Local/Downstream): Downstream, all providers
   
**Describe the bug**
A user that is a cluster owner of a cluster but only has user-base permissions globally is not allowed to manage the cluster members of the cluster he is owner of.

**To Reproduce**
Create a user with global user-base permissions
![Bildschirmfoto 2022-01-25 um 10 39 54](https://user-images.githubusercontent.com/243056/150952067-db4c6244-b69e-4926-8787-fde2b4c3a888.png)

Give this user cluster owner permissions in one cluster. For testing, I additionally tried to also give the user the "Manage Cluster Members" role explicitly, which does not change the result.
![Bildschirmfoto 2022-01-25 um 10 40 13](https://user-images.githubusercontent.com/243056/150952046-5ca1bce5-04bf-486f-8b46-ab8a193f248f.png)

Wit the test user try to edit the members of the cluster.

**Result**
You can't edit the cluster members with the testuser.

![Bildschirmfoto 2022-01-25 um 10 43 28](https://user-images.githubusercontent.com/243056/150952127-26258c08-a5b1-4db0-af7d-2bb2437d5e7f.png)

**Expected Result**
You should be able to edit the cluster members with the testuser.

**Additional context**
If you additionally give the testuser "Standard User" permissions globally, they are allowed to edit the cluster members of the cluster they are owner in.

This worked correctly in 2.5.x and seems to be a regression in 2.6.

**Comment by MbolotSuse** [comment] 2023-11-14 19:50
I'm unable to reproduce this on v2.8-head. I suspect that this was related to SURE-5431, which was resolved in v2.7.5. I recommend that this issue be closed.

**Closed** 2023-11-14 20:05 UTC
Labels: priority/1, internal, area/rbac, team/area1
