### ISSUE TITLE
[UI] show full container name on mouse hover on hosts - missing title attribute on containers links

### ISSUE THREAD

**Issue by demarant** [rancher/rancher#2767] opened 2015-11-21 11:07 UTC
This is a minor issue however very easy to fix.

problem:
We have a github name convention that makes the container names quite long and therefore we cannot distinguish them in the Rancher hosts UI, they all starts with "eeadocker..." see screenshot

![rancher hosts](https://www.dropbox.com/s/pvpzpss0a6zta1l/Rancher-hosts.png?raw=1)

An idea would be for longer names to show the beginning and the end ... like eeadoc...indata.

quick solution:
In any case the UI misses the title attribute on the container links, this will at least give the full name on mouse over.

**Comment by deniseschannon** [comment] 2015-11-23 18:23
Duplicate of https://github.com/rancher/rancher/issues/1415

**Closed by deniseschannon** 2015-11-23 18:23 UTC
