### ISSUE TITLE
Feature Request: Private Registry Integration with Kubernetes

### ISSUE THREAD

**Issue by strantalis** [rancher/rancher#4263] opened 2016-04-01 10:50 UTC
As of right now it does not look like that kubernetes can interact with private registries that are setup in rancher. I was specifically trying to setup AWS ECR with kubernetes. I think this feature would be a nice to have and make things easier working with kubernetes through rancher in the future.

Rancher Version: v1.0

**Comment by deniseschannon** [comment] 2016-04-23 06:08
Pre-duplicate of https://github.com/rancher/rancher/issues/4529

**Closed by deniseschannon** 2016-04-23 06:08 UTC
Labels: area/kubernetes, area/registry, kind/enhancement
