### ISSUE TITLE
Grouping/filtering hosts by label

### ISSUE THREAD

**Issue by gordontyler** [rancher/rancher#2902] opened 2015-12-03 21:50 UTC
It would be useful to be able to filter and/or group the hosts on the InfraStructure/Hosts page by host labels. For example, if I have a "role" label defined on some hosts, I would like to group all the hosts that have the same value for the "role" label into a visually distinct group. Another example would be to only show hosts that have a specific label and value combination. Simple globbing on the value would be nice to have.

**Comment by dahendel** [comment] 2015-12-09 21:21
+1 I am going through this right now in our infrastructure testing environment. Lots of machines very cluttered.

**Comment by hwinkel** [comment] 2016-03-06 06:46
:+1:

**Comment by deniseschannon** [comment] 2016-07-13 04:33
This is actually a duplicate of https://github.com/rancher/rancher/issues/1824

**Closed by deniseschannon** 2016-07-13 04:33 UTC
Labels: area/ui, kind/enhancement
