### ISSUE TITLE
vSphere CSI chart updates to upstream v2.7.0 / v2.6.2 / v2.5.4 / v2.4.3

### ISSUE THREAD

**Issue by phillipsj** [rancher/rancher#38188] opened 2022-07-05 13:19 UTC
**Is your feature request related to a problem? Please describe.**

Bugfix releases have happened for CSI and those all need to be pulled in.

**Describe the solution you'd like**

Update Rancher Charts to pull in bugfix releases of the vSphere CSI chart.

# Checklist for items that need completed

- [x] Update Image-mirror repo
- [x] Update manifests in rancher/vsphere-charts
- [x] Notify about chart "release" (reference @brandond @cwayne18 and @rancher-max in team-release-rancher-bits that new chart version is available)
- [x] Update chart in rancher/charts
- [x] Update chart in rancher/rke2-charts (RKE team)
- [x] Updated RKE2 to consume new chart (RKE2 team)

**Comment by jiaqiluo** [comment] 2022-09-12 20:53
Moved back to "working" because we need to update charts in the Update chart in rancher/charts, rancher/rke2-charts, and rancher/RKE2.  
See the checklist in the issue for progress.

**Comment by annablender** [comment] 2022-11-21 18:42
## Testing template

#### Root cause

VSphere CSI and CPI drivers needed image bumps to pull in new updates and fixes.

#### What was fixed, or what changes have occurred

Image version update
* CSI 2.5.3, 2.6.1 -> 2.5.4, 2.6.2, 2.7.0 
* CPI 1.24.1 -> 1.24.2, 1.25.0

#### Areas or cases that should be tested
 
This should be tested by deploying the CSI and CPI charts into a downstream RKE1 cluster on vSphere. Follow "Step 3: Deploying the chart" in [Jamie's docs](https://github.com/rancher/vsphere-charts/blob/main/DEVELOPING.MD).




#### What areas could experience regressions ?
 
#### Are the repro steps accurate/minimal ?

**Comment by vivek-infracloud** [comment] 2022-12-05 10:19
vSphere CSI chart fails to install on rancher v1.24.8.

vSphere CSI Controller pod showed error - 

`0/3 nodes are available: 3 node(s) had untolerated taint {node.cloudprovider.kubernetes.io/uninitialized: true}. preemption: 0/3 nodes are available: 3 Preemption is not helpful for scheduling.`

**Comment by brandond** [comment] 2022-12-05 19:38
@vivek-infracloud That indicates that the CPI chart hasn't been installed successfully. When the cloud provider it is working properly it will clear the uninitialized taint on the nodes. Please check the status of the cloud provider installation.

**Comment by vivek-infracloud** [comment] 2022-12-06 08:34
@brandond Correct. I tested the charts again. The CPI installation process finished but the cloud provider was not set on the node. I'm moving the CPI issue to Reopened.

**Comment by annablender** [comment] 2022-12-08 14:14
@vivek-infracloud I tested the CSI/CPI charts on `v2.7-head` and they worked as expected.

Repro steps
* Create a ubuntu20.04 vm in vsphere
* Run rancher/rancher:v2.7-head docker install on the vm
* Provision a downstream vsphere node driver cluster (1 cp, 1 etcd, 1 worker) via the rancher ui
* Verify the downstream cluster is using the dev-v2.7 applications repo
* Install vSphere CSI and CPI charts
* Verify installation completed successfully and deployment/pods are running and healthy

![image](https://user-images.githubusercontent.com/12955547/206468409-cbac6224-3263-47bc-965c-407d6b8e8f86.png)

![image](https://user-images.githubusercontent.com/12955547/206468538-0dc75b82-1c6a-42b4-a733-165ae0365c7b.png)

![image](https://user-images.githubusercontent.com/12955547/206468624-7d76f165-1c57-45af-be60-e271b979e382.png)

**Comment by raghavgithub** [comment] 2022-12-08 21:01
Hi,

Seems like vSphere CSI chart is not available yet for RKE1 K8 1.2.4.8. Created K3s cluster 
Provider: K3s
Kubernetes Version: v1.24.4

and deployed downstream RKE1 cluster using Rancher UI

Provider: RKE1
Kubernetes Version: v1.24.8

Installed CPI and CSI manually using yamls. vsphere-csi-controller-65c978d596-djbtn POD is in pending state 0/6. May I know if this is supported config or if I am missing something here? Should I installed RKE1 K8 1.23 version to make it work?

# kubectl get pods -A
NAMESPACE             NAME                                                 READY   STATUS      RESTARTS   AGE
cattle-fleet-system   fleet-agent-dbcf8d667-65gfl                          1/1     Running     0          109m
cattle-system         cattle-cluster-agent-5748b5b756-dgps2                1/1     Running     0          106m
cattle-system         cattle-cluster-agent-5748b5b756-lv2m7                1/1     Running     0          111m
cattle-system         cattle-node-agent-h4fq9                              1/1     Running     0          106m
cattle-system         cattle-node-agent-t86cc                              1/1     Running     0          106m
cattle-system         cattle-node-agent-tcxbf                              1/1     Running     0          111m
cattle-system         helm-operation-dlqq9                                 0/2     Completed   0          33m
cattle-system         kube-api-auth-g2dgs                                  1/1     Running     0          111m
default               mongod-0                                             0/1     Pending     0          2m53s
ingress-nginx         ingress-nginx-admission-create-9bqkg                 0/1     Completed   0          111m
ingress-nginx         ingress-nginx-admission-patch-vngzt                  0/1     Completed   2          111m
ingress-nginx         nginx-ingress-controller-k5vbn                       1/1     Running     0          111m
ingress-nginx         nginx-ingress-controller-phpkm                       1/1     Running     0          106m
ingress-nginx         nginx-ingress-controller-r4qg7                       1/1     Running     0          106m
kube-system           calico-kube-controllers-74df54cbb7-k5xt8             1/1     Running     0          111m
kube-system           canal-529d9                                          2/2     Running     0          111m
kube-system           canal-cp4fc                                          2/2     Running     0          106m
kube-system           canal-gpzbh                                          2/2     Running     0          106m
kube-system           coredns-59499769fb-nfzsh                             1/1     Running     0          111m
kube-system           coredns-59499769fb-vkxp9                             1/1     Running     0          106m
kube-system           coredns-autoscaler-67cbd4599c-wcwl2                  1/1     Running     0          111m
kube-system           metrics-server-585b7cc746-sjf58                      1/1     Running     0          111m
kube-system           rancher-vsphere-cpi-cloud-controller-manager-45z4v   1/1     Running     0          33m
kube-system           rancher-vsphere-cpi-cloud-controller-manager-jfrqx   1/1     Running     0          33m
kube-system           rancher-vsphere-cpi-cloud-controller-manager-nj9hs   1/1     Running     0          33m
kube-system           rke-coredns-addon-deploy-job-dzss7                   0/1     Completed   0          111m
kube-system           rke-ingress-controller-deploy-job-pkqbl              0/1     Completed   0          111m
kube-system           rke-metrics-addon-deploy-job-t5jdj                   0/1     Completed   0          111m
kube-system           rke-network-plugin-deploy-job-hctkf                  0/1     Completed   0          111m
kube-system           vsphere-csi-controller-65c978d596-djbtn              0/6     Pending     0          7m30s
kube-system           vsphere-csi-node-6xbhq                               3/3     Running     0          7m37s
kube-system           vsphere-csi-node-l6nrd                               3/3     Running     0          7m37s
kube-system           vsphere-csi-node-mm9rl                               3/3     Running     0          7m37s

Storage class was created but not able to create PVC

**Comment by vivek-infracloud** [comment] 2022-12-09 07:04
vSphere CSI chart installed successfully on rancher v2.7-head and v2.7.0.

Testing steps:
1. Created a rancher server v2.7.0 (also v2.7-head) on vSphere.
2. Created a downstream RKE1 vSphere node driver cluster with 1cp, 1worker and 1 etcd node.
3. Installed a CPI chart v101.1.0+up1.4.1
4. Installed a CSI chart v101.1.0+up2.6.2-rancher1
5. Created a deployment with storage using PVC.
6. Deployment creation was successful.

CPI and CSI charts are working as expected, hence closing the issue.

**Comment by vivek-infracloud** [comment] 2022-12-12 08:40
I validated the CPI, CSI chart installation as mentioned in the [QA Template here](https://github.com/rancher/rancher/issues/38188#issuecomment-1322495276).

There is a small mistake in the following helm install command. 

`helm install -f values.yaml --namespace --kube-system --kubeconfig <path to kube config> cpi ./charts/rancher-vsphere-cpi`

-- (double hyphen marks) before the kube-system should be removed. Otherwise, the chart installation fails with following error.
`Error: INSTALLATION FAILED: Kubernetes cluster unreachable: Get "https://172.16.132.116/k8s/clusters/c-hmdvq/version?timeout=32s": dial tcp 172.16.132.116:443: i/o timeout
`

**Comment by vivek-infracloud** [comment] 2023-01-05 05:04
@annablender Since charts are working as expected, may we close this issue?

**Comment by annablender** [comment] 2023-01-05 14:30
@vivek-infracloud Yes, go ahead

**Closed** 2023-01-09 07:33 UTC
Labels: kind/enhancement, priority/1, area/vsphere, [zube]: QA Working, QA/M, feature/charts-vsphere, team/area2, team/infracloud
