### ISSUE TITLE
Update to Multiclusterapp's roles does not reflect on the permissions that the apps creator has during helm install

### ISSUE THREAD

**Issue by mrajashree** [rancher/rancher#18088] opened 2019-02-14 00:48 UTC
**Steps to reproduce**:

1. Create a multiclusterapp with role "project-owner", and select grafana
2. Multiclusterapp creation works, but the actual app creation fails with the following error:

```
2019/02/13 11:44:16 [ERROR] AppController p-9fprs/mcappupdate-p-9fprs [helm-controller] failed with : failed to install app mcappupdate-p-9fprs. Error: release mcappupdate-p-9fprs failed: podsecuritypolicies.extensions is forbidden: User "u-cwvqgohqig" cannot create resource "podsecuritypolicies" in API group "extensions" at the cluster scope
```
3. Update multiclusterapp to add role "cluster-owner"

**Result**
Same error persists although the apps creator gets the cluster-role (crtb gets created for the app's system account)

**Expected**
App creation should succeed

**NOTE**
If while creating multiclusterapp with grafana, cluster-owner and project-owner roles are passed at the time of creation, app creation succeeds

**Comment by mrajashree** [comment] 2019-02-14 00:51
https://github.com/rancher/rancher/issues/18077 related

**Comment by cjellick** [comment] 2019-02-15 15:25
Caused by pre-existing bug, doesn't need fixed in v2.2.0

**Comment by bmdepesa** [comment] 2019-03-01 20:29
rancher/rancher:master 3/1

* Created multicluster app (grafana) with role `Project Owner`
* MC app was created, but could not progress past installing with error for permissions
* Upgraded MC app to add `Cluster Owner` role
* Grafana app updated and launched successfully

**Closed by bmdepesa** 2019-03-01 20:29 UTC
Labels: area/multi-cluster-app, kind/bug-qa, status/ready-for-review, status/resolved, status/to-test, status/working, team/ca, version/2.0
