### ISSUE TITLE
[BUG][EKS][2.6/2.7] Unable to view YAML for downstream EKS clusters

### ISSUE THREAD

**Issue by STARRY-S** [rancher/rancher#40667] opened 2023-02-13 09:28 UTC
**Rancher Server Setup**
- Rancher version: 2.6.10 / 2.7.1
- Installation option: Docker
- Proxy/Cert Details: N/A

**User Information**
- What is the role of the user logged in: admin

**Describe the bug**

Can not view the cluster information page after importing EKS cluster into Rancher (k8s version: 1.23, 1.24, etc),
the page shows **"Loading..."** and the console log shows the error of the `eksNodeGroups` is `null`.

**To Reproduce**

1. Create an EKS cluster in the AWS console, kube version 1.23/1.24.
2. Import this cluster into Rancher.
3. Go to the cluster information page.

**Result**

The page shows **"Loading..."** and the console log shows the error of the `eksNodeGroups` is `null`.

<img width="1728" alt="Screenshot 2023-02-08 at 17 49 15" src="https://user-images.githubusercontent.com/41445339/218420658-aa3da506-27ec-437d-86e2-49d8652e53d4.png">

**Comment by Josh-Diamond** [comment] 2023-02-24 01:29
Follow-up context:

   - issue NOT seen in 2.6.9
   - issue seen in 2.6.10 + 2.6-head
   
As Nancy highlights, this is only affecting standard users.

**Comment by richardcase** [comment] 2023-02-24 11:25
I am looking into this from an eks-operator point-of-view.

**Comment by cbron** [comment] 2023-02-24 14:29
@Josh-Diamond can you split out the RBAC part of this issue from Nancy's comment, team-1 can handle from there: https://github.com/rancher/rancher/issues/40667#issuecomment-1442149800

Both of these issues should be prioritized separately. This EKS part of this problem feels like a bug, not a blocker.

**Comment by crobby** [comment] 2023-02-24 14:32
Quick question @Josh-Diamond 
The original issue notes 2.6.10 as the version, but the repro steps reference 2.6-head as the version used.  
We have a theory on the fix here, but it turns out that the specific version is important here since 2.6.10 references a version of steve that has the fix for the links, but 2.6-head does not yet reference that fixed steve.  We think that we just need to update 2.6-head, but if this problem is in 2.6.10, we may have another problem.

**Comment by Josh-Diamond** [comment] 2023-02-24 16:49
@crobby looking into this now and testing on `2.6.10`.. thinking about this more, its possible I commented that this issue was seen on `2.6.10` because the original issue was `Cluster Details` page not loading, which has since been fixed.

So this EKS `View YAML` issue (which has since been determined as a separate bug) may very well not be seen on `2.6.10`

Will post results and confirm soon 👍

**Comment by Josh-Diamond** [comment] 2023-02-24 17:57
@crobby okay, I can confirm the EKS `View YAML` issue is NOT seen on 2.6.10 after all.

I believe what happened, is before this issue title changed and was transferred, that comment confirming this was seen on  2.6.10 was in reference to  `Cluster Details page won't load for imported EKS`.

Updating that comment

**Comment by crobby** [comment] 2023-02-24 18:49
With https://github.com/rancher/rancher/pull/40680 merged, I believe this is now ready to test.

**Comment by Josh-Diamond** [comment] 2023-02-24 20:51
Ticket #40667 - Test Results - _Pending_ 
---

With Docker on a single-node instance:

Verified on rancher `v2.6-f76a1c515cd12d0bc01e69e747d0734ae18df793-head`:

| Scenario | Test Case | Result |
|---|---|---|
| 1. | Rancher provisioned downstream EKS cluster w/ admin + standard user as `cluster-owners` | ✅ |
| 2. | Import EKS cluster from EKS Console into rancher server w/ admin + standard user as `cluster-owners` | ✅ |

---

Scenario 1:
1. Fresh install of rancher `v2.6-head`
2. As admin, create a standard user
3. As admin, provision a downstream EKS cluster w/ k8s 1.23
4. Once `active`, add standard user as member of cluster as `cluster-owner`
5. As admin, navigate to `Cluster Management > View YAML`
6. Verified - `View YAML` successfully loads YAML page w/ clean console logs
7. Logout admin, login standard user
8. As standard user, navigate to `Cluster Management > View YAML`
9. Verified - `View YAML` successfully loads YAML page w/ clean console logs

---

Scenario 2:
1. Create an EKS cluster w/ k8s 1.24 from EKS Console
2.  Fresh install of rancher `v2.6-head`
3. As admin, create a standard user
4. As admin, import EKS cluster (created in step 1) into rancher
5. Once imported cluster is `active`, add standard user as a `cluster-owner` member to the cluster
6. As admin, navigate to `Cluster Management > View YAML`
7. Verified - `View YAML` successfully loads YAML page w/ clean console logs
8. Logout admin, login standard user
9. As standard user, navigate to `Cluster Management > View YAML`
10. 9. Verified - `View YAML` successfully loads YAML page w/ clean console logs

**Comment by crobby** [comment] 2023-02-24 21:07
I wouldn't expect much of a chance for additional regressions around this.
The actual fix was in Steve https://github.com/rancher/steve/commit/48cf877a80b3a5a5b4aca2759181ee0b9036ae9e

The fix only changes the content of the view/selfLink for this particular resource.

That fix was actually already part of 2.6.10, but the problem was that it never got put back on the 2.6 branch, so it wasn't picked-up by 2.6-head builds.

**Closed** 2023-02-24 23:23 UTC
Labels: kind/bug, [zube]: QA Working, regression, team/highlander
