### ISSUE TITLE
Rancher local cluster charts not updated on upgrade from v2.5.9 -> v2.6.0 with --set useBundledSystemChart: true

### ISSUE THREAD

**Issue by SheilaghM** [rancher/rancher#35188] opened 2021-10-19 18:42 UTC
SURE-3336

**Rancher Server Setup**
Rancher Cluster:
Rancher version: v2.6.0 upgraded from v2.5.9

Downstream Cluster:
N/A

Longhorn:
N/A

Other:
N/A

**Information about the Cluster**
- Kubernetes version:
- Cluster Type (Local/Downstream):
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider):

Issue description:
In a Rancher environment with the helm chart option `--set useBundledSystemChart=true` the available Rancher charts in the local cluster are not updated upon upgrade from Rancher v2.5.9.

Business impact:
Latest v2.6 charts are not available to the user, and the rancher-webhook and fleet workloads are not updated, resulting in multiple failures. Following errors in Rancher Pod logs:

2021/09/09 15:23:02 [ERROR] error syncing 'machinehealthchecks.cluster.x-k8s.io': handler need-a-cert: services "webhook-service" not found, requeuing
2021/09/09 15:23:02 [ERROR] error syncing 'clusters.cluster.x-k8s.io': handler need-a-cert: services "webhook-service" not found, requeuing
2021/09/09 15:23:02 [ERROR] error syncing 'machinesets.cluster.x-k8s.io': handler need-a-cert: services "webhook-service" not found, requeuing
2021/09/09 15:23:02 [ERROR] error syncing 'machinedeployments.cluster.x-k8s.io': handler need-a-cert: services "webhook-service" not found, requeuing
2021/09/09 15:23:02 [ERROR] error syncing 'machines.cluster.x-k8s.io': handler need-a-cert: services "webhook-service" not found, requeuing
2021/09/09 15:23:02 [ERROR] error syncing 'validating-webhook-configuration': handler need-a-cert: services "webhook-service" not found, requeuing
2021/09/09 15:23:03 [ERROR] available chart version (0.3.500) for fleet-crd is less than the min version (100.0.0+up0.3.6)
2021/09/09 15:23:03 [ERROR] Failed to find system chart fleet-crd will try again in 5 seconds: no chart name found
2021/09/09 15:23:08 [ERROR] available chart version (0.3.500) for fleet-crd is less than the min version (100.0.0+up0.3.6)
2021/09/09 15:23:08 [ERROR] Failed to find system chart fleet-crd will try again in 5 seconds: no chart name found
2021/09/09 15:23:13 [ERROR] available chart version (0.3.500) for fleet-crd is less than the min version (100.0.0+up0.3.6)
2021/09/09 15:23:13 [ERROR] Failed to find system chart fleet-crd will try again in 5 seconds: no chart name found2021/09/09 15:23:02 [ERROR] error syncing 'machinehealthchecks.cluster.x-k8s.io': handler need-a-cert: services "webhook-service" not found, requeuing
2021/09/09 15:23:02 [ERROR] error syncing 'clusters.cluster.x-k8s.io': handler need-a-cert: services "webhook-service" not found, requeuing
2021/09/09 15:23:02 [ERROR] error syncing 'machinesets.cluster.x-k8s.io': handler need-a-cert: services "webhook-service" not found, requeuing
2021/09/09 15:23:02 [ERROR] error syncing 'machinedeployments.cluster.x-k8s.io': handler need-a-cert: services "webhook-service" not found, requeuing
2021/09/09 15:23:02 [ERROR] error syncing 'machines.cluster.x-k8s.io': handler need-a-cert: services "webhook-service" not found, requeuing
2021/09/09 15:23:02 [ERROR] error syncing 'validating-webhook-configuration': handler need-a-cert: services "webhook-service" not found, requeuing
2021/09/09 15:23:03 [ERROR] available chart version (0.3.500) for fleet-crd is less than the min version (100.0.0+up0.3.6)
2021/09/09 15:23:03 [ERROR] Failed to find system chart fleet-crd will try again in 5 seconds: no chart name found
2021/09/09 15:23:08 [ERROR] available chart version (0.3.500) for fleet-crd is less than the min version (100.0.0+up0.3.6)
2021/09/09 15:23:08 [ERROR] Failed to find system chart fleet-crd will try again in 5 seconds: no chart name found
2021/09/09 15:23:13 [ERROR] available chart version (0.3.500) for fleet-crd is less than the min version (100.0.0+up0.3.6)
2021/09/09 15:23:13 [ERROR] Failed to find system chart fleet-crd will try again in 5 seconds: no chart name found

RKE2 Node Driver cluster provisioning fails with following error:

Failed to create fleet-default/rke2 cluster.x-k8s.io/v1alpha4, Kind=Cluster for rke-cluster fleet-default/rke2: Internal error occurred: failed calling webhook "default.cluster.cluster.x-k8s.io": Post "https://webhook-service.cattle-system.svc:443/mutate-cluster-x-k8s-io-v1alpha4-cluster?timeout=10s": service "webhook-service" not found, failed to create fleet-default/rke2-pool1 cluster.x-k8s.io/v1alpha4, Kind=MachineDeployment for rke-cluster fleet-default/rke2: Internal error occurred: failed calling webhook "default.machinedeployment.cluster.x-k8s.io": Post "https://webhook-service.cattle-system.svc:443/mutate-cluster-x-k8s-io-v1alpha4-machinedeployment?timeout=10s": service "webhook-service" not found

Troubleshooting steps:
N/A

Repro steps:

- Provision a single all role node RKE cluster (I used RKE v1.2.9)
- Install Rancher v2.5.9 from helm with `--set useBundledSystemChart=true`, only other option I specified in `helm install` with `–set hostname`
- Perform `helm upgrade` to v2.6.0 with `--set useBundledSystemChart=true`
- Observe lack of chart version updates available in local cluster Apps & Marketplace, errors in Rancher Pod logs and inability to provision RKE2 cluster
- Perform `helm upgrade` to `--set useBundledSystemChart=false` and attempt to refresh the Rancher chart repository, observe issues persist
- Workaround:
- Is workararound available and implemented? Not that I could determine, attempting to `--set useBundledSystemChart=false` and fresh chart repo still didn't resolve this

 It's easy to reproduce: use the flag and see if the chart repo has been updated. Good issue to learn about charts.

Actual behavior:
Only existing Rancher v2.5.9 chart versions appear available

Expected behavior:
Rancher v2.6.0 charts available

Files, logs, traces:
Contents of the two rancher-charts-<x> ConfigMaps from my lab after upgrade to v2.6.0, not sure how to decode these, but both the same

Additional notes:
Correct charts are available on fresh install of v2.6.0

**Comment by MKlimuszka** [comment] 2022-07-01 20:05
Reporter cannot reproduce. Closing.

**Closed by MKlimuszka** 2022-07-01 20:05 UTC
Labels: internal, [zube]: Next Up, team/area3
