### ISSUE TITLE
Scheduling don't care for mCPU

### ISSUE THREAD

**Issue by Dremor** [rancher/rancher#10321] opened 2017-11-12 15:45 UTC
I have two server. The first one (A) got 8 cpu (but I assigned him 4000mCPU), the second one (B) got 8 cpu (and 8000 mCPU).

I launch 12 container, each consuming 1000 mCPU.

If I'm not mistaken, there should be 4 containers on A and 8 on B, but the scheduler seems to just randomly send the containers on each of my two servers. Sometime I have 2 on A, and the rest on B, sometime I have half on A, half on B, etc... Same goes when I add some test cloud instance (with 1000 mCPU each), these instance sometime get 3 or 4 containers, even when the other servers still got plenty of mCPU available.

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v1.6.10` Cattle: `v0.183.22` UI: `v1.6.23` |
|Access|`localauth` `admin`|
|Orchestration|`Cattle`|
|Route|`service.containers`|

**Comment by loganhz** [comment] 2017-11-13 09:48
Hi @Dremor , 

I cannot reproduce your issue with `v1.6.10`.  Can you check if there is some useful log in `scheduler` infrastructure service?

Host A

![image](https://user-images.githubusercontent.com/21168270/32718869-786f325e-c899-11e7-8ae1-244d3984d898.png)

Host B

![image](https://user-images.githubusercontent.com/21168270/32718898-988541aa-c899-11e7-99bb-13dd3d3583af.png)

Service

![image](https://user-images.githubusercontent.com/21168270/32718950-be18d292-c899-11e7-94f0-596b39802da4.png)

Deploy with 15 instances

![image](https://user-images.githubusercontent.com/21168270/32719012-defa64e4-c899-11e7-90e3-d70a7e23934d.png)

**Comment by Dremor** [comment] 2017-11-14 17:27
Indeed, seems like the scheduler is constantly crashing.

```
14/11/2017 18:23:48time="2017-11-14T17:23:48Z" level=info msg="Received event: Name: scheduler.reserve, Event Id: a30895ca-be9d-46f5-b781-faae0c0f32b6, ResourceId : 1i471"
14/11/2017 18:23:48time="2017-11-14T17:23:48Z" level=info msg="Reserving [] for e41bde5c-9a13-4a3c-aa5d-afbd45e206cc. Force=false"
14/11/2017 18:23:48time="2017-11-14T17:23:48Z" level=info msg="Reply: Name: reply.7672224111284878651, PreviousIds: [a30895ca-be9d-46f5-b781-faae0c0f32b6], ResourceId: 1i471, Data: map[]."
14/11/2017 18:24:04time="2017-11-14T17:24:04Z" level=info msg="Hit websocket pong timeout. Last websocket ping received at 2017-11-14 17:23:54.46319713 +0000 UTC. Closing connection."
14/11/2017 18:24:04time="2017-11-14T17:24:04Z" level=error msg="Exiting scheduler with error: <nil>"
```

**Comment by superseb** [comment] 2017-11-26 16:21
@Dremor Can you create a new issue describing your setup and logging so we can take a look? Closing this as not a bug.

**Closed by superseb** 2017-11-26 16:21 UTC
Labels: status/more-info
