### ISSUE TITLE
User is allowed to log in when he is not in allowed list of users and is not a member any cluster/project.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#12031] opened 2018-03-07 19:47 UTC
rancher version: master

Steps to reproduce:

Enable Github authentication
Select ```Allow members of Projects, plus Authorized Users and Organizations```
Do not add "user1" to this list.
Add this "user1" as the cluster member of an existing cluster.

Log in as "user1" and user i able to see cluster as expected.
Remove "user1" from the cluster member list.

Logging in as "user1" succeeds and no cluster is presented to the user.

Expected Result:
"user1" should not be allowed to log in to rancher-server.

**Comment by cjellick** [comment] 2018-03-13 18:40
This "restricted" behavior is changing slightly. The implementation is now simply whether the user already exists in rancher. They don't necessarily need to be pre-assigned to a cluster or project, Co-assigning @vincent99 because he mentioned updating the text to reflect the new behavior. But leaving myself assigned as well to ensure we talk through the the new behavior once more to make sure we are all ok with it

**Comment by galal-hussein** [comment] 2018-03-15 23:21
I can reproduce the same issue in AD authentication as well

**Comment by sangeethah** [comment] 2018-03-15 23:32
@cjellick Does this mean that  user needs to deleted explicitly for his access rights to be re evaluated?

**Comment by cjellick** [comment] 2018-04-19 16:53
Disregard my comment from 3/13. My implementation was wrong. We will fix it to behave like 1.6 (needs to be explicitly member of project or cluster).

**Comment by sangeethah** [comment] 2018-04-19 23:33
@adingilloRancher When you are validating this issue please make sure you validate the scenario that is mentioned in https://github.com/rancher/rancher/issues/12595 as well.

**Comment by adingilloRancher** [comment] 2018-04-20 16:44
Master 4/20/18
Verified fix for both local and git users.

**Closed by adingilloRancher** 2018-04-20 16:44 UTC
Labels: area/ui, kind/bug, priority/0, status/resolved, status/to-test, version/2.0
