### ISSUE TITLE
Rancher deletes EKS Nodegroups when importing EKS Cluster

### ISSUE THREAD

**Issue by SharpThunder** [rancher/rancher#36465] opened 2022-02-09 18:47 UTC
**Rancher Server Setup**
- Rancher version: 2.6.3
- Installation option (Docker install/Helm Chart):
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): EKS

**Information about the Cluster**
- Kubernetes version: 1.19
- Cluster Type (Local/Downstream): Downstream
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider): EKS

**User Information**
- What is the role of the user logged in? (Admin/Cluster Owner/Cluster Member/Project Owner/Project Member/Custom)
  - If custom, define the set of permissions: Admin

   
**Describe the bug**

Rancher deletes EKS Nodegroups when importing EKS Cluster and gives " Cluster must have at least one managed nodegroup. "  error.

**To Reproduce**
 

Import EKS cluster from Terraform using Rancher2 provider.

**Result**
Rancher deletes EKS Nodegroups

**Expected Result**

Successfully imported cluster.

**Comment by thedadams** [comment] 2022-02-09 18:51
Closing as a duplicate of https://github.com/rancher/rancher/issues/36128

**Closed by thedadams** 2022-02-09 18:51 UTC
