### ISSUE TITLE
[Logging v2] - Project Owner should be able to access the logging Flows and Outputs from UI 

### ISSUE THREAD

**Issue by izaac** [rancher/rancher#29266] opened 2020-09-30 00:27 UTC
Rancher version `master-head (09/29/2020)` _a2a141e_

Unless there's an existing Flows/Outputs in a namespace that is part of a project that's owned by the user I am not able to see the rancher-logging overview.

This is the UI when I have these existing CRDs

![Screen Shot 2020-09-29 at 5 23 23 PM](https://user-images.githubusercontent.com/27659/94629820-af946080-0278-11eb-9910-59b1eb301034.png)

But If I don't have anything and I open the Dashboard with a Project Owner I don't see the menu

![Screen Shot 2020-09-29 at 5 25 06 PM](https://user-images.githubusercontent.com/27659/94629875-d94d8780-0278-11eb-91ab-db0cf415db09.png)

Project Owner should be able to get/list ClusterOutputs. Get/list and create Flows and Outputs.
Project Member should be able to get/list Flows, Outputs and ClusterOutputs.

**Comment by maggieliu** [comment] 2020-09-30 21:33
Please re-test and see if  this is NS existing/not-existing issue and not actually needing a CR to be created. If it's just requiring a namespace, then we will just document it.

**Comment by jiaqiluo** [comment] 2020-09-30 21:56
The following is confirmed in the latest master-head:

If there is at least 1 namespace in the project, then the `project owner` / `project member` is able to see the entry for logging in the dashboard. 
 
![image](https://user-images.githubusercontent.com/6218999/94743965-15dabb00-032d-11eb-9882-62d4a201d944.png)

cc @maggieliu

**Comment by maggieliu** [comment] 2020-09-30 22:10
Once the docs PR is merged, we can close

**Comment by maggieliu** [comment] 2020-10-02 03:10
Closing since doc is merged

**Closed by maggieliu** 2020-10-02 03:10 UTC
Labels: [zube]: Team Green Backlog, area/documentation
