### ISSUE TITLE
[BUG] Rancher v2.7.2: downstream Private GKE clusters are broken: "failed to call webhook: context deadline exceeded"

### ISSUE THREAD

**Issue by nflynt** [rancher/rancher#41142] opened 2023-04-12 16:35 UTC
## SURE-2984

**Rancher Server Setup**
- Rancher version: `v2.7.2`
- Installation option (Docker install/Helm Chart): **Helm Chart**
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): `rancher/k3s:v1.24.10-k3s1`
- Proxy/Cert Details: **Custom domain, proxied through nginx w/ letsencrypt**

**Information about the Cluster**
- Kubernetes version: `v1.24.10-gke.2300`
- Cluster Type (Local/Downstream): **Downstream (Rancher Provisioned)**
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider): **GKE w/ "Private Cluster" checked**

**User Information**
- What is the role of the user logged in? **Admin**

**Describe the bug**
When provisioning a new GKE cluster through Rancher and selecting the "Private Cluster" option, with appropriate network configuration following [Rancher documentation](https://ranchermanager.docs.rancher.com/reference-guides/cluster-configuration/rancher-server-configuration/gke-cluster-configuration/gke-private-clusters), the installation appears to succeed. Rancher can see the cluster status, but attempting to make any changes or install charts fails with these errors:

> Internal error occurred: failed calling webhook "[rancher.cattle.io](http://rancher.cattle.io/).namespaces.create-non-kubesystem": failed to call webhook: Post "[https://rancher-webhook.cattle-system.svc:443/v1/webhook/validation/namespaces?timeout=10s](https://rancher-webhook.cattle-system.svc/v1/webhook/validation/namespaces?timeout=10s)": context deadline exceeded

> failed to wait for roles to be populated

This does not occur on v2.7.1 and prior, seemingly due to the `rancher-webhook` not being automatically deployed to downstream clusters in these versions.

**To Reproduce**
Firstly on the GKE side, set up a VPC and, for simplicity, a Cloud NAT + Cloud Router for the cluster to use. Here are the settings I used:
![vpc_basic_config](https://user-images.githubusercontent.com/122321752/231520464-8ecddf56-91a6-4167-bd22-6337c9e83b11.png)
![vpc_firewall_config](https://user-images.githubusercontent.com/122321752/231520481-dd14b93a-4c6a-4149-bf7c-be3fec114876.png)
![cloud_router_settings](https://user-images.githubusercontent.com/122321752/231520501-ae1bda37-014c-48a9-bb13-7cdaae7d4449.png)
![cloud_nat_settings](https://user-images.githubusercontent.com/122321752/231520512-759ddfda-ae8c-4742-8f63-c9ce0436efe7.png)

Then, on the Rancher side, deploy a new GKE cluster using this VPC. In my case, I chose to use a MasterAuthorizedNetwork, which allows Rancher to perform initial provisioning on the nodes, but this isn't required to reproduce the bug. These are the settings I used:

![cluster_config_1](https://user-images.githubusercontent.com/122321752/231520863-766774e5-3413-4f5a-89a5-82b8af0edd79.png)
![cluster_config_2](https://user-images.githubusercontent.com/122321752/231520880-2fd870f1-d02a-4935-bb56-a194e47ae83e.png)
![cluster_config_3](https://user-images.githubusercontent.com/122321752/231520898-847399a2-41bf-42fd-83d7-3c929405d702.png)

**Result**
Rancher successfully provisions the cluster and shows an "Active" status for all machines. However, attempting to make any changes or install any charts spins for about 10 seconds and then times out with an error. (See screenshots below.)

**Expected Result**
Rancher should ideally be able to fully manage the cluster.

**Screenshots**
Rancher can poll the cluster status and it appears healthy:
![cluster_appears_alive](https://user-images.githubusercontent.com/122321752/231521131-90cc3ac6-4635-44da-833e-6536401c3843.png)

Trying to create a namespace fails:
![namespace_creation_failure](https://user-images.githubusercontent.com/122321752/231521178-34809a22-9c1e-454a-b675-ff5e3965c7dc.png)

Trying to install the Monitoring chart fails:
![monitoring_install_failure](https://user-images.githubusercontent.com/122321752/231521193-083df717-e45b-463b-b70b-88b38aaf298f.png)

**Additional context**

Based on the behavior, I theorize that the kubeapi server is unable to access the webhook pod running on port 9443, since the default firewall rules only permit traffic over ports 443 and 15090. @MbolotSuse noticed that this seems similar to the following issue https://github.com/elastic/cloud-on-k8s/issues/1437#issuecomment-516836262

**Comment by nflynt** [comment] 2023-04-12 17:05
After some testing, the workaround mentioned in https://github.com/elastic/cloud-on-k8s/issues/1437#issuecomment-516836262 does appear to work around the issue. Specific to my setup, these firewall settings worked:

Rule: Ingress
Port: 9443/tcp
Source: 172.16.0.32/28 (masterIpv4CidrBlock)
Target: gke-nflynt-272-private-webhook-isolation-3c93ee4b-node (automatically generated node tag for this cluster)

These steps are documented in great detail here: https://cloud.google.com/kubernetes-engine/docs/how-to/private-clusters#add_firewall_rules 

Since this is now something Rancher installs will need to deal with out of the box, I would think we should update the Rancher-side [GKE Private documentation](https://ranchermanager.docs.rancher.com/reference-guides/cluster-configuration/rancher-server-configuration/gke-cluster-configuration/gke-private-clusters) to call this out.

**Comment by cbron** [comment] 2023-04-12 21:05
We should consider running webhook on port 443, but that may cause problems/complications around permissions. If we decide no, then this should become a documentation issue, and hopefully is fixed automatically when you deploy GKE clusters.

**Comment by KevinJoiner** [comment] 2023-04-13 12:54
I am onboard with allowing the webhook to run as root and bind to 443 if it is an opt-in configuration.

If we allow the binding ports for the webhook to be configurable via helm and somehow pass that value down through rancher, we will allow users to still use rancher-webhook without adding a new firewall rule. This would also address this related issue https://github.com/rancher/webhook/issues/211 and the dev scenario where Rancher-webhooK default port conflicts with [Rancher-Desktops default port](https://github.com/rancher-sandbox/rancher-desktop/issues/1890#issuecomment-1318658573). As you noted to run webhook on 443 a user would also need to change the context of the rancher-webhook pod to run as root https://kubernetes.io/docs/tasks/configure-pod-container/security-context/#configure-volume-permission-and-ownership-change-policy-for-pods

**Comment by samjustus** [comment] 2023-05-22 18:57
SURE-2984

**Comment by KevinJoiner** [comment] 2023-07-11 20:07
# Validation

## Root Cause
Users who need to run Rancher on a private GKE cluster can not run the webhook because the GKE firewall defaults to only allow port 443. Rancher webhook runs on port 9443 and can not be configured to run on 443 by the user.

## What was fixed, or what change has occurred
Rancher now has the ability to change the helm values used to install rancher-webhook on per cluster basis. This allows us to add configurable port information into the Rancher/Webhook chart, which users can then manipulate via the cluster object.

This change adds the ability to customize the values used to install a cluster's webhook. This is done by editing a new field on the cluster object that specifies the helm values to use when installing the webhook. These values are synced to a ConfigMap in the cluster and are referenced when installing the helm chart.

## Areas or cases that should be tested

### Desired checks
- Validate that the webhook can run on a private GKE cluster. when configured correctly.
- Validate that each changing webhook values for cluster A does not affect cluster B's webhook values.
- Validate that not using the new cluster field retains previous Rancher behavior. (webhook values before change match values after the change)

### Steps
1. Create a GKE VPC Cloud NAT + Cloud Router for the cluster to using the provided screenshot in the issue description.
2. Run new Rancher instance and recoded local cluster's helm value
    1. Create shell to the local cluster.
    2. Run `helm -n cattle-system get values rancher-webhook`
    3. record the values returned for future verification
3. Create a downstream GKE cluster using the VPC created above.
4. Wait for cluster to finish provisioning and enter the Active state.
5. Attempt to create a namespace verify you are denied.
6. Edit the yaml for the cluster.
7. the following section under spec.
   ``` yaml
   spec:
       chartValues:
           rancher-webhook: '{"port": 443, "cap_net_bind_service": true }'
   ```
8. Save the new yaml file.
9.  wait for rancher-webhook to be redeployed
10. verify you can create a namespace.
11. verify that the local cluster's webhook values are unaffected
    1. Create shell to the local cluster.
    2. Run `helm -n cattle-system get values rancher-webhook`
    3. verify that the values returned match the previously recorded values.


## What areas could experience regressions
This change should only change the helm values used to install the webhook for the cluster that was edited. We want to validate that this does not affect previous installation values.
1. Get the helm values used to install the webhook before this change was introduce `v2.7.5` 
    1. Start `v2.7.5` rancher instance.
    2. Create shell to the local cluster.
    3. Run `helm -n cattle-system get values rancher-webhook`
    4. Record the returned values
2. Get the helm values for local cluster on `v2.7-HEAD` (can be done during basic validation steps above)
    1. Start a `v2.7-HEAD` rancher instance.
    2. Create shell to the local cluster.
    3. Run `helm -n cattle-system get values rancher-webhook`
    4. Verify the values returned match the ones above.

## Are the repro steps accurate/minimal?
yes.

**Comment by KevinJoiner** [comment] 2023-07-20 00:43
This needs a webhook RC before testing.

**Comment by anupama2501** [comment] 2023-07-28 23:45
QA Neo webhook related checks to validate 
Fresh checks:
1. Verify installing rancher on v2.7-head by providing the helm values `--set webhook.port=9553 --set webhook.priorityClassName="system-node-critical" --set priorityClassName="rancher-critical`
     - Verify by running the helm get values -n cattle-system rancher-webhook, port value is set to 9553
     - Verify by creating a namespace/project in the local cluster
 2. Create a downstream rke2 node driver cluster and verify the webhook rules set to local cluster are not set in the downstream cluster. 
 3. Edit the downstream cluster and update the rancher config as follows
 ```
apiVersion: v1
 kind: ConfigMap
 metadata:
     name: rancher-config
     namespace: cattle-system
     labels: 
         "app.kubernetes.io/part-of": "rancher"
 data:
     rancher-webhook: 'port: 9443'
```
      - Verify the values in the local cluster are unaffected by this change and the downstream cluster values are updated
 4. Delete the port set in the local cluster and verify the port is changed back to the default.
     - Create a namespace and a project and verify the creation works.
 5. Restart rancher server and verify the values are not updated.
 **Upgrade checks:**
6. Upgrade rancher server by providing the helm values 
    - Verify the local cluster has the updated port.
    - no changes in the downstream cluster.
    - Update the downstream cluster and verify the port is updated on the downstream cluster.

**Comment by anupama2501** [comment] 2023-08-02 15:17
Available for testing in v2.7.7-rc1

**Comment by cpinjani** [comment] 2023-08-07 11:22
**Desired Downstream checks**

Build:
```
v2.7.7-rc1
rancher-webhook:v0.3.6-rc3
```

Validation Results - :x: 

**Steps**
- Create a GKE VPC Cloud NAT + Cloud Router for the cluster to using the provided screenshot in the issue description.
- Run new Rancher instance
- Create a downstream GKE cluster using the VPC created above, wait for cluster to finish provisioning and enter the Active state.
- Attempt to create a namespace verify you are denied.
![image](https://github.com/rancher/rancher/assets/73099870/352a5209-2d89-4027-8aa3-a2520fc1d0da)

- Apply the following ConfigFile to the downstream cluster
 ```
apiVersion: v1
 kind: ConfigMap
 metadata:
     name: rancher-config
     namespace: cattle-system
     labels: 
         "app.kubernetes.io/part-of": "rancher"
 data:
     rancher-webhook: 'port: 443'
```

- Wait for rancher-webhook to be redeployed
Seems like rancher-webhook is not getting redeployed after applying the config and creating namespace fails again with above error

```
$ kubectl get nodes
NAME                                    STATUS   ROLES    AGE     VERSION
gke-cpinjani-priv1-test-9ba71502-4rx1   Ready    <none>   5m40s   v1.25.11-gke.1700

$ kubectl apply -f rancher-config.yaml 
configmap/rancher-config created

$ kubectl describe configmap rancher-config -n cattle-system
Name:         rancher-config
Namespace:    cattle-system
Labels:       app.kubernetes.io/part-of=rancher
Annotations:  <none>

Data
====
rancher-webhook:
----
port: 443

BinaryData
====
Events:  <none>

$ kubectl get deployment rancher-webhook -n cattle-system
NAME              READY   UP-TO-DATE   AVAILABLE   AGE
rancher-webhook   1/1     1            1           130m

Containers:
   rancher-webhook:
    Image:     rancher/rancher-webhook:v0.3.6-rc3
    Ports:       9443/TCP, 8777/TCP
    Host Ports:  0/TCP, 0/TCP
    Liveness:    http-get https://:https/healthz delay=0s timeout=1s period=5s #success=1 #failure=3
    Startup:     http-get https://:https/healthz delay=0s timeout=1s period=5s #success=1 #failure=60
    Environment:
      STAMP:             
      ENABLE_CAPI:       false
      ENABLE_MCM:        false
      CATTLE_PORT:       9443
      CATTLE_CAPI_PORT:  8777
      NAMESPACE:          (v1:metadata.namespace)

```

**Comment by anupama2501** [comment] 2023-08-07 16:31
@cpinjani can you update the rancher-webhook version to `rancher/rancher-webhook:v0.3.6-rc4` by editing the cluster-agent in the `cattle-system` namespace and adding the env value `CATTLE_RANCHER_WEBHOOK_VERSION=2.0.6+up0.3.6-rc4` on the downstream cluster and 
On the local cluster,  update the rancher deployment by adding the env var `CATTLE_RANCHER_WEBHOOK_VERSION=2.0.6+up0.3.6-rc4` and see if the fix works?

**Comment by anupama2501** [comment] 2023-08-07 18:36
Re opening as I'm unable to set the priorityClassName and port while installing rancher:
**Webhook version:** `rancher/rancher-webhook:v0.3.6-rc4`
**Rancher chart:** `v2.7.7-rc`
**Image tag:** `v2.7-head 6bc6c90 `
**Steps:**
1. Install rancher server on v2.7.7-rc1 and rancherImageTag=v2.7-head as follows `helm upgrade --install rancher rancher-latest/rancher --version 2.7.7-rc1 --namespace cattle-system --set hostname=<redacted> --set global.cattle.psp.enabled=false --set bootstrapPassword=admin  --set webhook.port=9333 --set webhook.priorityClassName="system-node-critical"  --set rancherImageTag=v2.7-head`
2. Once rancher is up, try to get the webhook values:
```
> helm -n cattle-system get values rancher-webhook
USER-SUPPLIED VALUES:
capi:
  enabled: false
global:
  cattle:
    systemDefaultRegistry: ""
mcm:
  enabled: true
port: 443
priorityClassName: rancher-critical
```
3. Notice that the webhook port and priorityClassName are not updated.

**Additional Info:**
Try to pass only either the port or webhook priorityClassName while installing rancher and notice the values are set. For example, if we `helm upgrade --install rancher rancher-latest/rancher --version 2.7.7-rc1 --namespace cattle-system --set hostname=<redacted> --set global.cattle.psp.enabled=false --set bootstrapPassword=admin  --set webhook.port=9443 --set rancherImageTag=v2.7-head``:
```
> helm -n cattle-system get values rancher-webhook
USER-SUPPLIED VALUES:
capi:
  enabled: false
global:
  cattle:
    systemDefaultRegistry: ""
mcm:
  enabled: true
port: 9443
priorityClassName: rancher-critical
```

Following warnings are seen in the rancher logs:
```
2023/08/07 18:27:32 [WARNING] Failed to get rancher rancherWebhookValues failed to unmarshal 'rancher-webhook' value: yaml: mapping values are not allowed in this context
2023/08/07 18:27:32 [WARNING] Failed to get rancher rancherWebhookValues failed to unmarshal 'rancher-webhook' value: yaml: mapping values are not allowed in this context
```

**Comment by cpinjani** [comment] 2023-08-08 18:47
@anupama2501 The webhook fix is indeed in v0.3.6-rc4 as per https://github.com/rancher/webhook/pull/266/commits/851f4cbdf60beae7c76a186aa0e4c293a2d4b207
Thanks for pointing out.

**Desired Downstream checks**
Webhook version: `rancher/rancher-webhook:v0.3.6-rc4`
Rancher chart: `v2.7.7-rc1`
Image tag: `v2.7-head d0eac94`

Validation Results - Passed :white_check_mark: 

**Steps**
- Create a GKE VPC Cloud NAT + Cloud Router for the cluster to using the provided screenshot in the issue description.
- Run new Rancher instance
- Create a downstream GKE cluster using the VPC created above, wait for cluster to finish provisioning and enter the Active state.
- Attempt to create a namespace verify you are denied.
- Apply the following ConfigFile to the downstream cluster
```
apiVersion: v1
kind: ConfigMap
metadata:
    name: rancher-config
    namespace: cattle-system
    labels: 
        "app.kubernetes.io/part-of": "rancher"
data:
    rancher-webhook: 'port: 443'

```
- Allow rancher-webhook to run as root and wait for it to be redeployed:
```
rancher-webhook:
    Image:        rancher/rancher-webhook:v0.3.6-rc4
    Ports:          443/TCP, 8777/TCP
```
- Able to create a namespace (cattle-monitoring-system) and install Monitoring chart:
![image](https://github.com/rancher/rancher/assets/73099870/92e6e4a4-ba1c-49da-ae3c-d304213cdcd3)

**Comment by anupama2501** [comment] 2023-08-15 04:28
Verified on v2.7.7-rc2, webhook version: 

Fresh checks:

- Verify installing rancher on v2.7-head by providing the helm values --set webhook.port=9553 --set webhook.priorityClassName="system-node-critical" --set priorityClassName="rancher-critical
- Verified by running the helm get values -n cattle-system rancher-webhook, port value is set to 9443
- Verified by creating a namespace/project in the local cluster
- Created a downstream k3s node driver cluster and verify the webhook rules set to local cluster are not set in the downstream cluster.
   - Edit the downstream cluster and update the rancher config as follows
   - Verified the values in the local cluster are unaffected by this change and the downstream cluster values are updated

 ```
apiVersion: v1
kind: ConfigMap
metadata:
    name: rancher-config
    namespace: cattle-system
    labels: 
        "app.kubernetes.io/part-of": "rancher"
data:
    rancher-webhook: 'port: 9443'
```


- Restart rancher server and verify the values are not updated.
Upgrade checks:
- Upgrade rancher server by providing the helm values
- Verified the local cluster has the updated port.
- no changes in the downstream cluster.
    - Updated the downstream cluster and verify the port is updated on the downstream cluster.

**Comment by anupama2501** [comment] 2023-08-16 22:35
Closing the ticket as validations look good.

**Closed by anupama2501** 2023-08-16 22:35 UTC
Labels: kind/bug, priority/2, [zube]: QA Working, release-note, team/area1, regression, status/to-test, JIRA, team/highlander, deprecation-note

**Comment by KevinJoiner** [comment] 2023-09-28 15:52
# Release Notes

## Synopsis of issue
In some specific environment Rancher is unable to run or install rancher-webhook helm release with the default helm values.
## Resolution
Users can now modify the values used to install the rancher-webhook on the local and downstream clusters.
For more info visit: https://ranchermanager.docs.rancher.com/reference-guides/rancher-webhook

**Comment by sravanakinapally** [comment] 2024-08-28 02:29
How can we update rancher-webhook to use a private image registry and use`imagePullSecrets` in webhook deployment?
