### ISSUE TITLE
[cli] catalog list does not work correctly with RANCHER_URL

### ISSUE THREAD

**Issue by mishak87** [rancher/rancher#9048] opened 2017-06-13 08:58 UTC
**Rancher versions:**
rancher/server: 1.6.2
rancher (cli): 0.6.1

I have only RANCHER_URL, RANCHER_ACCESS_KEY and RANCHER_SECRET_KEY defined in environment variables.

```
> rancher --env 1a12345 catalog list
NAME      CATEGORY   ID
FATA[0000] Invalid URL https://rancher-test.example.com, must contain /v2-beta
```

Prefixing RANCHER_URL with `/v2-beta` works
```
RANCHER_URL="$RANCHER_URL/v2-beta" rancher --env 1a12345 catalog list
```

**Comment by deniseschannon** [comment] 2017-06-13 15:08
Duplicate of https://github.com/rancher/rancher/issues/8137

**Closed by deniseschannon** 2017-06-13 15:08 UTC
