### ISSUE TITLE
Save "Start before Stopping" state between upgrades

### ISSUE THREAD

**Issue by focusshifter** [rancher/rancher#3657] opened 2016-02-19 18:53 UTC
Sometimes we forget to check the "Start before Stopping" checkbox while deploying our internal services, so for more than a half of minute all of us are staring at 503 page.

I've found #2615, and while I agree that the checkbox must be off by default, it would be nice to keep its on/off state between upgrades to avoid stupid errors.

**Comment by Rucknar** [comment] 2016-02-25 11:12
@focusshifter You can control this in the rancher compose file with the config below.lf your doing a lot of these it might work a little easier using the CLI instead of the UI..

```
upgrade_strategy:
  start_first: true
```

**Comment by deniseschannon** [comment] 2016-07-13 06:10
Duplicate of https://github.com/rancher/rancher/issues/2703

**Closed by deniseschannon** 2016-07-13 06:10 UTC
Labels: area/ui, kind/enhancement
