### ISSUE TITLE
Events table has empty columns

### ISSUE THREAD

**Issue by nwmac** [rancher/rancher#40332] opened 2023-01-23 08:53 UTC
Some of the columns on the Events table are not populated - looking at the API response, the data is returned.

![image](https://user-images.githubusercontent.com/1955897/213999168-c0adb622-bbb7-4823-b6ea-cf1dc2ed867c.png)

Empty columns:

- Last Seen
- Object
- Subobject
- Source
- First Seen

**Comment by Jono-SUSE-Rancher** [comment] 2023-01-26 20:00
@Sahota1225 and @snasovich - Can you guys take a look at this and prioritize it for v2.7.2?

**Comment by cbron** [comment] 2023-02-07 23:15
> This appears to be caused by a backend change between 2.7.0 and 2.7-head.

Does this affect 2.6.x ?

**Comment by torchiaf** [comment] 2023-02-08 08:36
> > This appears to be caused by a backend change between 2.7.0 and 2.7-head.
> 
> Does this affect 2.6.x ?

2.6.x seems to be not affected.

**Comment by rmweir** [comment] 2023-02-09 04:21
I believe I have isolated this issue to this PR https://github.com/rancher/steve/pull/69. I think it is related tot he apiserver change it pulls in https://github.com/rancher/apiserver/pull/19.

**Comment by Josh-Diamond** [comment] 2023-02-09 23:27
Encountered this issue as well,  here are the details pertaining to what I observed:

---


**Setup**
- Rancher version: `v2.7-96097e8091fcb0aaca43f33ebee02f7c4016129f-head`
- Browser type & version: `Chrome`

**Describe the bug**
When navigating to `Cluster Explorer > Cluster > Events` on an active cluster, only the state is shown.  All other details - [ `last seen`, `reason`, `object`, `subobject`, `source`, `message`, `first seen`, `count`, `name` ] - are no longer displayed.

**To Reproduce**
1. Fresh install of rancher `v2.7-head`
2. Provision a downstream cluster - [ this was seen on RKE1, RKE2 + K3s AWS Node driver clusters with both k8s 1.24 + 1.25 ]
3. Once `active`, navigate to `Cluster Explorer > Cluster > Events`
4. Reproduced

**Result**
Only the state field is accurately shown and displayed

**Expected Result**
All fields should be accurately shown and displayed

**Screenshots**
<img width="1546" alt="k3s 1 25 6 - reproduced; 2 7-head" src="https://user-images.githubusercontent.com/46494969/217953504-aeac1606-71bd-4ec6-a44a-44d1bf0c7b0b.png">


**Additional context**

API GET request for `Events` page is successful; status code: 200; with what appears to be a full payload
![image (9)](https://user-images.githubusercontent.com/46494969/217954793-f6c2c9bc-817c-4176-84a4-1e29868020c4.png)


Also, this issue is not seen on `v2.7.0`

**Comment by rmweir** [comment] 2023-02-14 15:42
Testing:
1. View the events of a local k3s/rke or downstream rke cluster.
2. Go to events page. I did this by typing events into search.
3. If there are no events you can trigger some by rotating certificates using the cluster manager or doing something similar.

Expected before fix: Events will be missing information. In my case they only showed the state, "active".
Expected after fix: Events should be fully or near fully annotated.

Possible regressions:
Test the [warning headers issue](https://github.com/rancher/rancher/issues/39413) again as the fix for that introduced this regression and needed to be slightly changed.

**Comment by dasarinaidu** [comment] 2023-02-27 20:21
I m still seeing few fields were not displaying the data on `v2.7-d559c2f16d5a634d8e5188e242ee9a5b69c55908-head`

Missing fields/Columns:

- Last Seen
- Subobject
- Source
- First Seen
- Count

![image](https://user-images.githubusercontent.com/22034884/221673982-581f7b8f-ffdb-47e0-baab-705a855cb109.png)

**Note:**  I also looked into v2.7.0 and all these fields were populating data properly.
![image](https://user-images.githubusercontent.com/22034884/221676218-d7fccff1-177e-4056-8523-4e1e40720ae8.png)

**Comment by dasarinaidu** [comment] 2023-02-28 18:20
Validated this issue on `v2.7-cca09e4768af17067ca3a848a6b3e5ed44e99aa1-head`

I can see events and data on all the fields. Looks good to me and closing this card.

**Details:**
1. Version : `v2.7-cca09e4768af17067ca3a848a6b3e5ed44e99aa1-head`
2. Users : Standard and Admin
3. Clusters : Local and RKE1
4. Modes : Dark and Light

**Steps:**
1. Provision rancher v2.7
2. Cluster Explorer -> Local -> Cluster->Events
3. Check for the columns and data on each column

Actual:
a. Appropriate columns and data are displaying properly

Note: validated the same on Cluster Dashboard page also.


![image](https://user-images.githubusercontent.com/22034884/221942771-22764931-9129-4aae-a2c6-8d39feb10443.png)

![image](https://user-images.githubusercontent.com/22034884/221944259-c63352dc-f3aa-4006-ba52-e0b097fa71c7.png)

**Closed by dasarinaidu** 2023-02-28 18:20 UTC
Labels: kind/bug, status/blocker, priority/0, [zube]: QA Working, QA/S, team/area1, regression, size/2
