### ISSUE TITLE
Can't get stats after upgrade of Rancher

### ISSUE THREAD

**Issue by osallou** [rancher/rancher#3653] opened 2016-02-19 08:35 UTC
Version:
0.59.0
Steps: 
Upgraded Rancher and can't access live cpu/ram stats anymore
Tried to upgrade Docker too (from 1.9.1 to 1.10.1) with same result.
Results: 
Web socket error

    ...
    Socket connect 3 to ws://a.b.c.d/v1/hoststats...
    multi-stats.js:174 WebSocket connection to 'ws:/a.b.c.d/v1/hoststats?token=XXXXXXX failed: HTTP Authentication failed; no valid credentials available

I am logged on host, can access and manage everything correctly.

Expected:

**Comment by fedya** [comment] 2016-02-21 00:42
This
https://github.com/rancher/rancher/issues/3615

Locally i fixed it, and propesed a patch.

**Comment by deniseschannon** [comment] 2016-02-21 06:10
Yes, duplicate of #3615.

**Closed by deniseschannon** 2016-02-21 06:10 UTC
