### ISSUE TITLE
Load balancer refuses connection after target`s container restart

### ISSUE THREAD

**Issue by clicman** [rancher/rancher#4734] opened 2016-05-09 09:20 UTC
### Problem

Given: 
* ghost blog service
* load balancer serviing blog service
* I can open blog

When:
* I restart container winh blog deployed

Then:
* load balancer refuses connection, I cannot open blog    

### Works fine
When:
 * I stop container
 * and I start container again

Then:
* I can open blog.

Problem 100% reproduceble.

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v1.1.0-dev1` Cattle: `v0.160.3` UI: `v1.0.7` Docker: `1.10.3` |
|Access|`github` `admin`|
|Route|`environments.index`|

**Comment by deniseschannon** [comment] 2016-05-12 21:16
Reproduced in v1.1.0-dev1

When a target service container is restarted, haproxy loses its backend for the service.

Steps to Reproduce
1. Start ghost with 1 container
2. Start Load balancer pointing to ghost (port 2368)
3. Restart ghost container

Results
In the LB, the `/etc/haproxy/haproxy.cfg` will not have anything programmed in the backend.

**Comment by deniseschannon** [comment] 2016-05-12 22:20
Actually, this is a duplicate of https://github.com/rancher/rancher/issues/4487

Closing in favor of that issue.

**Closed by deniseschannon** 2016-05-12 22:20 UTC
Labels: area/balancer, kind/bug
