### ISSUE TITLE
Changing vSphere Credentials causes old nodes to fail on deletion

### ISSUE THREAD

**Issue by a-blender** [rancher/rancher#40608] opened 2023-02-17 23:26 UTC
**Rancher Server Setup**
- Rancher version: v2.6.9
- Installation option (Docker install/Helm Chart):
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc):
- Proxy/Cert Details:

**Information about the Cluster**
- Kubernetes version: v1.22.17+rke2r1
- Cluster Type (Local/Downstream):
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider):

**User Information**
- What is the role of the user logged in? (Admin/Cluster Owner/Cluster Member/Project Owner/Project Member/Custom)
  - If custom, define the set of permissions:

Admin

**Describe the bug**

In-tree CPI on RKE2 1.22.x, vSphere 7.0.3. Customer updated their vSphere password and were unable to remove nodes from the cluster due to errors.

**To Reproduce**

* In Rancher 2.6.9, create an RKE2 single node all role cluster in vSphere
* Change vSphere password in the vSphere web client; update credentials in the rancher ui
* Try to delete node in rancher

**Result**

![image](https://user-images.githubusercontent.com/12955547/219815950-ddd2997a-675f-454c-a033-5aa3256cc369.png)

**Expected Result**

Node should delete successfully.

SURE-5801

**Comment by annablender** [comment] 2023-02-17 23:34
I was able to reproduce this issue on Rancher v2.6.9 with an rke1 cluster with a single node, all roles. I also noticed that if you create an rke1 vsphere cluster and change the vsphere password, that a similar error appears in the rancher logs but the node is still removed. So this bug appears to be specific to rke2.

Rancher server logs
```
2023/02/17 22:17:31 [ERROR] error syncing 'fleet-default/ablender-rke2-pool1-89fdb0cb-srghr': handler machine-provision-remove: an error on the server ("unable to create impersonator account: error getting service account token: error getting secret: Get \"https://10.43.0.1:443/api/v1/namespaces/cattle-impersonation-system/secrets/cattle-impersonation-u-jt56c4a3lz-token\": dial tcp 10.43.0.1:443: connect: connection refused") has prevented the request from succeeding (get nodes ablender-rke2-pool1-89fdb0cb-srghr), requeuing
```

Screenshot
![image](https://user-images.githubusercontent.com/12955547/219816623-51fbe580-eb63-40f9-9e47-c1415d6d2815.png)

I will begin debugging on Monday.

**Comment by annablender** [comment] 2023-02-21 14:19
If there is a fix for this, it will go only into Rancher 2.7.x.

**Comment by dereknola** [comment] 2023-03-15 19:37
I was not able to reproduce this with a single node. You run into a understandable error when attempting this with: if you only have 1 machine provisioned in a cluster, and then delete that machine, you don't have a cluster to access anymore.
![image](https://user-images.githubusercontent.com/11727736/225412811-a0b5b446-a086-4423-b514-3e6fea03322a.png)

RKE2  v1.24.10+rke2r, will endlessly sit waiting for an initial node.

When testing with multiple nodes, can confirm that the delete error is seen. The rke2 logs themselves however, do not reveal much. It simply appears that the node is removed from the etcd quorum abruptly and doesn't know how to handle it. Whatever is removing the node from the rancher side not doing it cleanly. 

[rke2-delete-node.log](https://github.com/rancher/rancher/files/10983903/rke2-delete-node.log)

Looking at the logs of the still existing nodes, you can see that the node was removed from etcd. 
```
Mar 15 19:25:58 rke2-ha-pass-pool1-4ae271b6-qrmqf rke2[1423]: time="2023-03-15T19:25:58Z" level=info msg="Removing name=rke2-ha-pass-pool1-4ae271b6-6jghs-fc23771d id=9111896555467186857 address=172.16.1.145 from etcd"
Mar 15 19:26:12 rke2-ha-pass-pool1-4ae271b6-qrmqf rke2[1423]: time="2023-03-15T19:26:12Z" level=info msg="Stopped tunnel to 172.16.1.145:9345"
Mar 15 19:26:12 rke2-ha-pass-pool1-4ae271b6-qrmqf rke2[1423]: time="2023-03-15T19:26:12Z" level=info msg="Proxy done" err="context canceled" url="wss://172.16.1.145:9345/v1-rke2/connect"
```
[rke2-still-up-node.log](https://github.com/rancher/rancher/files/10983931/rke2-still-up-node.log)


I would guess this is not an issue in RKE2 code, but in the v2 provisioner for rke2.

**Comment by dereknola** [comment] 2023-03-15 19:51
An additional tidbit, if you change the password in vsphere back to the original one, and change the vpshere credentials in rancher, you can then delete nodes without an issue.

**Comment by markusewalker** [comment] 2023-05-01 23:02
**QA TEST PLAN**

**Scenarios**
|Scenario|Test Case|
|---|---|
|1|As a standard user, provision a downstream RKE1 node driver cluster (1 etcd, 1 cp, 1 worker), change the vSphere password, delete worker node in Rancher and validate that it deletes and is replaced|
|2|As a standard user, provision a downstream RKE2 node driver cluster (1 etcd/cp, 1 worker), change the vSphere password, delete worker node in Rancher and validate that it deletes and is replaced|
|3|As a standard user, provision a downstream K3S node driver cluster (1 node, all roles), change the vSphere password, delete node in Rancher and validate that it deletes and is replaced|
|4|As a standard user, provision a downstream RKE2 node driver cluster (1 etcd, 1 cp, 1 Linux worker, 1 Windows worker), change the vSphere password, delete worker node in Rancher and validate that it deletes and is replaced|

**Comment by markusewalker** [comment] 2023-05-01 23:47
I was able to reproduce this behavior on `v2.7.3`. Please see details below:

- Rancher install: Docker
- Rancher version: `v2.7.3`
- Browser: Chrome

**TEST RESULT**
|Scenario|Test Case|Result|
|---|---|---|
|1|As a standard user, provision a downstream RKE1 node driver cluster (1 etcd, 1 cp, 1 worker), change the vSphere password, delete worker node in Rancher and validate that it deletes and is replaced|:white_check_mark:|
|2|As a standard user, provision a downstream RKE2 node driver cluster (1 etcd/cp, 1 worker), change the vSphere password, delete worker node in Rancher and validate that it deletes and is replaced|:x:|
|3|As a standard user, provision a downstream K3S node driver cluster (1 node, all roles), change the vSphere password, delete node in Rancher and validate that it deletes and is replaced|:x:|

**REPRO STEPS**

**Scenario 1**
1. As a standard user, provisioned a downstream RKE1 node driver `v1.25.9` cluster with 1 etcd, 1 cp and 1 worker.
2. Validated that the cluster and nodes came up as `Active` in Cluster Management and Cluster Explorer.
3. In vSphere client, temporarily updated my password.
4. Navigated back to Rancher and updated my vSphere cloud credential to reference the updated password.
5. Attempted to delete the worker node; it successfully deleted and was replaced with a new worker node that eventually came to be in an `Active` state.
_______
**Scenario 2**
1. Repeated scenario 1 steps 1-4, but provisioned a downstream RKE2 node driver `v1.24.13+rke2r1` cluster with 1 etcd/cp and 1 worker.
2. Attempted to delete the worker node, but it fails to delete and hangs with the following error message:
![Screen Shot 2023-05-01 at 4 26 33 PM](https://user-images.githubusercontent.com/52591819/235550275-65a15e4d-2753-448b-b3af-3995dd3244f6.png)
_________
**Scenario 3**
1. Repeated scenario 1 steps 1-4, but provisioned a downstream K3S node driver `v1.23.17+k3s1` cluster with 1 node, all roles.
2. Attempted to delete the worker node, but it fails to delete and hangs as shown below:
![Screen Shot 2023-05-01 at 4 26 42 PM](https://user-images.githubusercontent.com/52591819/235550255-9ebf903c-c802-4b52-99c5-2bdb8fa391db.png)

**ADDITIONAL NOTES**
For what it's worth, I reverted my vSphere client password back to the original password. After doing so, I attempted scaled each of my above clusters to have an additional worker node. Once `Active`, I attempted to delete the new worker node with my original vSphere client password.

RKE1 and RKE2 successfully deleted the worker node and created a new one, while K3S was not even able to scale up a new node. It may be a separate issue from what is described here, but throwing out the behavior that I saw while attempting to reproduce the stated issue.

**Comment by bfbachmann** [comment] 2023-08-03 01:38
I figured I'd post a full description of what's happening here in case it's of use to people in the future.

## Rancher Machine

Rancher Machine is a fork of Docker Machine that was originally designed to work as a simple CLI that supports driver plugins. Each driver plugin needs to be configured differently, so drivers specify their own set of flags that are _only_ parsed by Rancher Machine if the `create` command was specified. In other words, Rancher machine only ever looks for driver configuration during machine creation.

### Machine Creation

#### In Rancher Machine

When Rancher Machine receives the `create` command, it fetches driver-specific flags via the [`getCreateFlags`](https://github.com/rancher/machine/blob/3fd34ee08fcc5f89650ba9f179ae994d2fffcc20/libmachine/drivers/drivers.go#L24) method on the driver. It will then find all available values for each of these flags (by searching command-line arguments and envvars) and use them to populate driver configuration via the [`SetConfigFromFlags`](https://github.com/rancher/machine/blob/3fd34ee08fcc5f89650ba9f179ae994d2fffcc20/libmachine/drivers/drivers.go#L67) driver method. This is all done inside [`cmdCreateInner`](https://github.com/rancher/machine/blob/bd7ac597518926039ccaa40fb407b11c508b8ae5/commands/create.go#L149) and nowhere else! This means that Rancher Machine _will not_ check command line arguments (or their associated envvars) for driver-specific config unless it's executing the `create` command.

Once the driver config has been set and the remote machine as been created, Rancher Machine will [persist all the configuration it used to create the machine](https://github.com/rancher/machine/blob/bd7ac597518926039ccaa40fb407b11c508b8ae5/commands/create.go#L276). Originally, it persisted this information to a file on disk, but in the Rancher use-case, this config will also be [stored in a secret](https://github.com/rancher/machine/blob/f035d910537020bc8c947d012e759ab0a8d42ddb/libmachine/persist/secretstore.go#L72) inside the local cluster. This way, the next time Rancher Machine runs and needs to do something with the host that was created earlier, it can simply load the config it used to create the machine from the secret (or file) instead of forcing the user to provide all the same config via flags or envvars again (note almost all the behaviour I'm describing here originated in Docker Machine and was simply _inherited_ by Rancher Machine).

Nevertheless, this creates a problem. If any machine configuration (like credentials) happens to change after the machine is created, Rancher Machine will attempt to use the outdated configuration on subsequent commands, and may be unable to communiate the with machine as a result – the secret containing the machine/driver config will never be updated because Rancher Machine simply lacks this functionality (seemingly by the original Docker Machine design).

#### In Rancher v1 Provisioning (rke1)

Rancher uses machine templates to store configuration for machines. Information that is used to populate machine templates is stored in secrets with the `mc-` prefix. These secrets are read by Rancher's node controller and used during provisioning to specify driver-specific config when creating remote machines [via command line arguments](https://github.com/rancher/rancher/blob/a65c26a5e695cae286fbbdca143f7223eee7ce30/pkg/controllers/management/node/controller.go#L312).

These machine configuration secrets are kept up to date with driver configuration (including cloud credentials), so they always represent the latest machine/driver config and credentails. The problem, again, is that Rancher machine doesn't accept flags/envvars for driver config on any command other than the create command, so [previous PRs](https://github.com/rancher/rancher/pull/24435) to address this problem in Rancher _only_ didn't work (or at least don't work now).

Interestingly, if you create an RKE1 cluster, change the related cloud credentials, and then try removing it, all resources related to that cluster will be deleted in Rancher, but Rancher Machine will never actually be able to delete the node. So, in that case, you'd have a dangling node after cluster deletion that Rancher never tells you about!

#### In Rancher v2 Provisioning (rke2/k3s)

When creating machines via CAPR (v2 provisioning), Rancher creates machine driver secrets containing driver credentials populated with info from cloud credentials linked to that machine. This secret is always kept up to date when cloud credentails are changed. When Rancher CAPR goes to [create a machine](https://github.com/rancher/rancher/blob/3f86d2ecb270e17c00378546b838cea213360045/pkg/controllers/capr/machineprovision/controller.go#L626), it creates a job that runs Rancher Machine with [environment variables populated from the machine driver secret](https://github.com/rancher/rancher/blob/3f86d2ecb270e17c00378546b838cea213360045/pkg/controllers/capr/machineprovision/controller.go#L632). This is good, because it means the container running the Rancher Machine command that gets created for the job always has the latest driver config/credentails (via envvars), but again this doesn't solve the problem because Rancher machine simply ignores the envvars and loads the old config from its own secret.

If you create an RKE2/k3s cluster, rotate its cloud credentials, and then try delete it, Rancher will eventually give you a useful error indicating machine deletion failure because it tracks the result of the Rancher Machine job and pipes its errors back to you.

**Comment by dh-apporto** [comment] 2023-09-18 17:44
I am also seeing similar behavior after our Azure Cloud credential expired.   I pushed a new cloud credential password by updating the client secret in the UI, but I left everything else the same (same credential name, etc).   I was able to create new nodes after that happened, but existing nodes couldn't change PVC mounts or be deleted.   Delete message errors are similar to the ones recorded here (and googling the errors is how I found this and other related tickets).

I did check the `machine-driver-secret` for the host in fleet-default namespace, and the credentials were updated there.  However, I still received error messages when deleting the hosts (and pvc mounts weren't updating either).

Deleting the machine-state secret for the host and rerunning the deleting job allowed the UI to get rid of the host (maybe this is the same as force delete in the UI...), but the cloud services stayed provisioned and had to be deleted manually.

Is there a way to force the machine-state to get the new credentials?  (assuming that is where the problem lies)

I'm not sure if you want a new ticket on the Azure cloud credentials issue, or if you want to address it with this ticket.   We are on rancher 2.7.3 when this happened.

**Comment by markusewalker** [comment] 2023-09-29 19:49
Validated this against `v2.8-head` https://github.com/rancher/rancher/commit/bfbf05a582d8a263a7385016f00f4215e6bcb876.

**ENVIRONMENT DETAILS**
- Rancher install: Docker
- Rancher version: `v2.8-head` https://github.com/rancher/rancher/commit/bfbf05a582d8a263a7385016f00f4215e6bcb876

**TEST RESULT**
|Scenario|Test Case|Result
|---|---|---|
|1|As a standard user, provision a downstream RKE1 node driver cluster (1 etcd, 1 cp, 1 worker), change the vSphere password, delete worker node in Rancher and validate that it deletes and is replaced|:white_check_mark:|
|2|As a standard user, provision a downstream RKE2 node driver cluster (1 etcd/cp, 1 worker), change the vSphere password, delete worker node in Rancher and validate that it deletes and is replaced|:white_check_mark:|
|3|As a standard user, provision a downstream K3S node driver cluster (1 node, all roles), change the vSphere password, delete node in Rancher and validate that it deletes and is replaced|:white_check_mark:|

**VALIDATION STEPS**

**Scenario 1**
1. As a standard user, provisioned a downstream RKE1 node driver `v1.27.6-rancher1-1` cluster with 1 etcd, 1 cp and 1 worker.
2. Validated that the cluster and nodes came up as `Active` in Cluster Management and Cluster Explorer.
3. In vSphere client, temporarily updated my password.
4. Navigated back to Rancher and updated my vSphere cloud credential to reference the updated password.
5. Attempted to delete the worker node; it successfully deleted and was replaced with a new worker node that eventually came to be in an `Active` state.
_______

**Scenario 2**
1. Repeated scenario 1 steps 1-4, but provisioned a downstream RKE2 node driver `v1.27.6+rke2r1` cluster with 1 etcd/cp and 1 worker.
     - Received the same successful results.

_________
**Scenario 3**
1. Repeated scenario 1 steps 1-4, but provisioned a downstream K3S node driver `v1.26.97+k3s1` cluster with 1 node, all roles +. 1 worker.
     - Received the same successful results.

**Comment by bfbachmann** [comment] 2023-10-05 19:51
Reopening this issue as there is a lingering bug that I've addressed [here](https://github.com/rancher/machine/pull/228).

The result of the bug is that, if you create a vSphere cluster and then rotate your vSphere username, the Rancher machine will continue using your old username instead of the new one.

Originally I had reopened https://github.com/rancher/rancher/issues/42972 for this bug, but that was the wrong one – I should have reopened this one.

**Comment by susesgartner** [comment] 2023-10-06 16:29
Ticket #40608 - Test Results - ✅ PASS
---
 
| Scenario | Test Case | Result |
|---|---|---|
| 1. | Rotate vSphere credentials on cluster (1 node vanilla) | PASS |
| 2. | Rotate vSphere credentials on cluster (2 node) | PASS|
| 3. | Rotate vSphere credentials on cluster (3 node) | PASS |
 
---
Verified with (HA Helm or Docker) on Rancher `v2.8-head` fc12e7d:
---
 
Scenario 1: Rotate vSphere credentials on cluster (1 node vanilla)
---
1. Create a cluster with 1 node and all roles
2. Edit the cloud credentials of the cluster to a new User/password
3. Delete the cluster
 
Results: Cluster successfully deleted
 
---
 
Scenario 2: Rotate vSphere credentials on cluster (2 node)
---
1. Create a cluster with 2 nodes (1 etcd/cp 1 worker)
2. Edit the cloud credentials of the cluster to a new User/password
3. Delete the cluster
 
Results: Cluster successfully deleted

---

Scenario 3: Rotate vSphere credentials on cluster (3 node)
---
1. Create a cluster with 3 nodes all roles 
2. Edit the cloud credentials of the cluster to a new User/password
3. Delete the cluster
 
Results: Cluster successfully deleted

**Closed by susesgartner** 2023-10-06 16:29 UTC
Labels: kind/bug, internal, area/cloud-provider, [zube]: To Test, area/rke2, QA/S, team/area2, JIRA, team/area2/sc
