### ISSUE TITLE
[Cluster Explorer] Log Button not visible/cropped (Follow/Download)

### ISSUE THREAD

**Issue by mscbpi** [rancher/rancher#31621] opened 2021-03-08 10:45 UTC
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
Display log.

**Result:**
![image](https://user-images.githubusercontent.com/28528210/110311064-90f27c80-8003-11eb-8c17-9ab10975d071.png)
Log button at bottom of the page are not visible. Resizing browser or web part does not change anything, nor  zooming out

**Other details that may be helpful:**
Used to work normally in 2.5.5

Tested on various Chromium Browsers.

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): 2.5.6
- Installation option (single install/HA): HA 

gz#15599

**Comment by sadhugit** [comment] 2021-04-16 09:35
Hi Team, Any update on this issue.

**Comment by vincent99** [comment] 2021-04-16 15:38
This a duplicate of multiple other issues, in the wrong repo, and fixed already for 2.5.8.  https://github.com/rancher/dashboard/issues/2488

**Comment by mscbpi** [comment] 2021-04-16 21:16
Oh thanks I am going to close that one and I have a bunch of others open here that are related to the dashboard. Thanks @vincent99

**Closed** 2021-04-16 21:16 UTC
Labels: internal
