### ISSUE TITLE
Edit cluster page does not show node pools on an edit of RKE1 Node driver cluster

### ISSUE THREAD

**Issue by sowmyav27** [rancher/rancher#35491] opened 2021-11-13 01:54 UTC
**Rancher Server Setup**
- Rancher version: 2.6-head commit id: `638b29a`
- Installation option (Docker install/Helm Chart): Helm
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): RKE1
- Proxy/Cert Details: Rancher generated

**Information about the Cluster**
- Kubernetes version: 1.20 (any)
- Cluster Type (Local/Downstream): Downstream DO RKE1 cluster

**Describe the bug**
Edit cluster page does not show node pools on an edit of RKE1 Node driver cluster

**To Reproduce**

- Deploy an RKE1  Node driver DO cluster
- When the cluster comes up Active, Edit cluster.
- Edit cluster page does not show all the options as expected. 
- Instead

<img width="1676" alt="Screen Shot 2021-11-12 at 5 53 29 PM" src="https://user-images.githubusercontent.com/26032343/141601432-cc9ef038-2ba5-4915-b9ad-7f1d987de723.png">

**Comment by snasovich** [comment] 2021-11-16 03:34
This will be fixed by updated https://github.com/rancher/rancher/pull/35451.
The root cause is that RKE1 clusters returned by `/v3/clusters` endpoint are missing `rancherKubernetesEngineConfig` which break UI as shown on the issue's screenshot. Caused by improvements done for https://github.com/rancher/rancher/issues/25487.

**Comment by snasovich** [comment] 2021-11-17 18:41
This is now available to be tested on v2.6-head.

### Root cause
Changes implemented per https://github.com/rancher/rancher/issues/25487 resulted in `rancherKubernetesEngineConfig` removed from the response of `/v3/clusters` API endpoint.

### What was fixed, or what changes have occurred
`clusters.management.cattle.io` was added to the excluded objects so the dynamic type is used for this case and the code is performing in the same way as prior to the referenced change when it relates to these objects. The fact that performance improvement is removed in this case should not be an issue as generally you wouldn't have thousands of clusters.
 
### Areas or cases that should be tested
Provisioning/editing RKE1 clusters.
 
### What areas could experience regressions?
Performance of listing clusters will be back to "prior to https://github.com/rancher/rancher/issues/25487 fix levels", but as noted above that's OK. No regressions are expected from this actual fix as we're just getting behavior to what it was before.
 
### Are the repro steps accurate/minimal?
Yes, though technically you don't even have to wait for the cluster to become Active - you can edit while it's still being provisioned and the issue would be reproducible then as well.

**Comment by davidnuzik** [comment] 2021-11-17 19:47
Appears fixed in latest v2.6-head. Will validate this properly soon but we should not longer be blocked in this area.

**Comment by davidnuzik** [comment] 2021-11-17 21:11
**My checks PASSED**
 
**Reproduction Steps:**

Not required. I had reproduced the issue myself prior to discovering this issue.

-----
 
**Validation Environment:**

Rancher version: v2.6-head `96e2438` 11/17/2021
Rancher cluster type: single-node docker install
Docker version: 20.10
 
Downstream cluster type: RKE1
Downstream K8s version: v1.21.6-rancher1-1
 
**Validation steps:**

1. Provision any RKE1 cluster. In my case I created a 1-node cluster using the ec2 node driver.
2. When the cluster is not yet active, edit it (you technically don't have to wait here).
3. When the cluster is active, edit it and can ensure can make a change. This works.

Notice the issue is now resolved. We have the missing fields/areas back in the rke1 edit cluster iframe:
![image](https://user-images.githubusercontent.com/45179589/142283093-397b9d62-99a3-4c68-a6b3-fc9adf764c59.png)

 
**Additional Info:**

**Closed by davidnuzik** 2021-11-17 21:11 UTC
Labels: status/blocker, kind/bug-qa, [zube]: QA Working
