### ISSUE TITLE
host and containers should show ipv6 addresses when they exist

### ISSUE THREAD

**Issue by cglewis** [rancher/rancher#1115] opened 2015-06-09 18:42 UTC
currently it will only show the ipv4 addresses, even when they have ipv6 addresses.

**Comment by cjellick** [comment] 2016-03-28 23:26
@deniseschannon can we close this as a duplicate of #1403

**Comment by deniseschannon** [comment] 2016-03-28 23:46
Yes, closing in favor #1403

**Closed by deniseschannon** 2016-03-28 23:46 UTC
Labels: area/api, kind/enhancement, release/future
