### ISSUE TITLE
Can't remove Member Roles after cluster creation

### ISSUE THREAD

**Issue by troy256** [rancher/rancher#24934] opened 2020-01-13 19:03 UTC
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
Provision new cluster in Rancher 2.3.3 and set member roles.  After cluster is ready edit the cluster, expand Member Roles, and notice that the minus button normally on the right side of each row is missing (see screenshot).

![cluster-member-roles](https://user-images.githubusercontent.com/48829375/72283327-852c4580-360c-11ea-9b48-9abd3b425497.jpg)

**Other details that may be helpful:**
This is on-prem.  Using OpenLDAP for authentication.

**Environment information**
Rancher 2.3.3, Single node, on-prem.  This is seen across all of our clusters.

**Cluster information**
- On-prem, custom cluster from Vsphere VMs running Ubuntu 18.04 LTS 8C/32G systems.
- Kubernetes version: 1.15.6, although we have clusters on other K8S versions with same issue.
- Docker version: 19.3.4, although we have clusters on other Docker versions withe same issue.

**Comment by westlywright** [comment] 2020-01-22 22:10
@deniseschannon this was fixed in master but was not targeted at 2.3.x. This issue doesn't have a milestone either so should the fix be back ported? 

OG Issue: https://github.com/rancher/rancher/issues/24428
OG PR: https://github.com/rancher/ui/pull/3668

**Comment by deniseschannon** [comment] 2020-01-22 22:41
This sounds like a duplicate of #24428 

But we can use this to track as a backport of what we need to do for 2.3.x.

**Comment by sowmyav27** [comment] 2020-01-23 19:28
**Reproduced the issue on `2.3.4`**

**Steps:**

- Deploy a cluster
- Add User1 as a member of the cluster
- Go to Edit cluster --> Member Roles section
- minus-icon to remove members from project missing from Edit Project page

<img width="1480" alt="Screen Shot 2020-01-23 at 11 26 24 AM" src="https://user-images.githubusercontent.com/26032343/73016693-34b6a400-3dd3-11ea-97d6-e049a0797eb8.png">

**On 2.3.5-rc2**
- Issue is seen fixed
<img width="1418" alt="Screen Shot 2020-01-23 at 11 27 28 AM" src="https://user-images.githubusercontent.com/26032343/73016774-616abb80-3dd3-11ea-90ff-e4e0df7f222d.png">

**Closed by sowmyav27** 2020-01-23 19:28 UTC
Labels: [zube]: To Test, kind/bug, team/ui
