### ISSUE TITLE
Add UI support for cluster capabilities 

### ISSUE THREAD

**Issue by kinarashah** [rancher/rancher#15105] opened 2018-08-16 21:30 UTC
https://github.com/rancher/rancher/issues/12422

**Comment by loganhz** [comment] 2018-10-20 00:30
Backend is merged in master.

**Comment by davidnuzik** [comment] 2018-12-03 18:01
Related issue - #16785

Related UI issues:
#16783
#16784

**Comment by davidnuzik** [comment] 2018-12-12 22:11
Needs testing, #16785 will be resolved later and is only loose end remaining in this area.

**Comment by davidnuzik** [comment] 2018-12-15 01:15
Note: All areas have been validated except for IngressCapabilities (previously IngressController); it's possible there may be a bug in this area and this area is being tested further.

**Comment by davidnuzik** [comment] 2018-12-17 19:57
Version: Master 2.2 (12/14/18)
Confirmed new UI features EXCEPT for the new row added to the add ingress page regarding ingressControllers in PR https://github.com/rancher/ui/pull/2364 (now called ingressCapabilities). This is not working and an API bug was entered around this: #17140 and EXCEPT for NodePortRange due to #16785

**Closed by davidnuzik** 2018-12-17 19:57 UTC
Labels: area/cluster, area/ui, kind/enhancement, status/resolved, status/to-test, version/2.0
