### ISSUE TITLE
Issues with vSphere volume classes/volume claims

### ISSUE THREAD

**Issue by nitram2k** [rancher/rancher#12692] opened 2018-04-13 14:24 UTC
**Rancher versions:**
rancher/server: v2.0.0-beta3
rancher/agent: v2.0.0-beta3

When trying to deploy a storage class, with the 'Vmware Vsphere Volume' provisioner, I can't seem to add a PVC to it, it fails with the following message:

`Type     Reason              Age                 From                         Message
  ----     ------              ----                ----                         -------
  Warning  ProvisioningFailed  1m (x102 over 26m)  persistentvolume-controller  no volume plugin matched`

I've also tried to follow the following tutorial and adding it manually, which results in the same error: https://github.com/kubernetes/examples/blob/master/staging/volumes/vsphere/README.md

settings:

Provisioner: VMware Vsphere Volume
Disk Format: Thin
Datastore: XXX-VSAN-MS1
host failures: 2
cache reservation: 20
FS type: ext4

**Environment**:
- Kubernetes version (use `kubectl version`):
kubectl version
I0413 14:10:48.561688     375 http.go:105] HTTP2 has been explicitly disabled
I0413 14:10:48.585829     375 http.go:105] HTTP2 has been explicitly disabled
Client Version: version.Info{Major:"1", Minor:"8+", GitVersion:"v0.0.0-master+$Format:%h$", GitCommit:"$Format:%H$", GitTreeState:"", BuildDate:"1970-01-01T00:00:00Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"8+", GitVersion:"v0.0.0-master+$Format:%h$", GitCommit:"$Format:%H$", GitTreeState:"", BuildDate:"1970-01-01T00:00:00Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"linux/amd64"}
- Cloud provider or hardware configuration:
Vsphere (deployed with vsphere provider)
- OS (e.g. from /etc/os-release):
Ubuntu 16.06
boot2docker 17.02
- Kernel (e.g. `uname -a`):
Linux rancher 4.4.0-119-generic #143-Ubuntu SMP Mon Apr 2 16:08:24 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

**Comment by tfiduccia** [comment] 2018-04-16 23:16
@nitram2k - Did you configure the cluster to point to that cloud provider?
![image](https://user-images.githubusercontent.com/11514927/38839846-740655d2-4191-11e8-9047-d1d9e2910f85.png)

**Comment by nitram2k** [comment] 2018-04-17 09:42
@tfiduccia No, it says 'none' right now. Since i can only choose 'none' or 'generic' I thought it was not needed?

In the template I've added the vsphere connection info, and the nodes provision just fine, however the VMWare Vsphere Volume driver in the storage class doesn't work. 

Should I switch the proider from none to generic? And what values does it expect? 

So if I understand correctly the vsphere info I provided in the templates when creating the nodes does not get used within the storage class?

It's kind of confusing, but I hope you can help me out :)

**Comment by b3tts32** [comment] 2018-04-17 21:03
+1 here for anyone that has an example of vsphere cloud provider working with 2.0

**Comment by vincent99** [comment] 2018-04-18 08:37
Yes you have to have the cloud provider to use the storage driver; that's what he the credentials for the storage to communicate with the API.

No we do not currently do anything to make this easier to do for vsphere.

**Comment by nitram2k** [comment] 2018-04-18 08:47
@vincent99 thanks for te answer, but can you maybe point out what exactly we have to do to get this to work? 

Do we have to fill in the cloud provider from none to generic, and if so, what does it expect for values? Or do we need to follow the guide at https://github.com/vmware/kubernetes/blob/enable-vcp-uxi/README.md, which doesn't really work when using the latest rancher beta3.

Or do we have to do both?

**Comment by gaui** [comment] 2018-04-18 21:28
Would also like to know more about this. It's not clear to me after configuring vSphere node template with all credentials, what should be filled in when selecting generic for "cloud provider" ?

**Comment by nitram2k** [comment] 2018-04-23 15:03
anyone ? :(

**Comment by alllexandrz** [comment] 2018-05-14 12:49
some one? :(

**Comment by the-nicolas** [comment] 2018-05-21 20:35
I also spent many hours playing with Rancher 2.0 latest and VSphere 6.7...
- Host provisioning works fine
- PV Claim pending
- Can´t see any connection attempt in VSphere logs to the API

Where can I find any logs what that provisioner is doing?!?

:-((((

**Comment by nitram2k** [comment] 2018-06-07 10:38
Any updates on this? This is preventing us from considering using Rancher in production... anyone?

**Comment by the-nicolas** [comment] 2018-06-07 10:51
Also still found no solution yet.

Note:
I have switched to portworx at the moment to work around the problem. As it stands, I will not change that in the future, because it brings with it some other benefits. Sharing of volumes, snapshots on k8s level and S3 Backup, replication and more flexible resource management (IOPS etc.) - also on k8s level. And I can just use normal ESXI hypervisor and don´t need vsphere server.

**Comment by nitram2k** [comment] 2018-06-08 14:27
@vincent99 do you have any suggestions for this? is this a rancher issue or a k8s one? Can you maybe point us in the right direction?

**Comment by frenchtoasters** [comment] 2018-06-14 18:23
@vincent99 are we just doing this wrong? Or is there some issue here with rancher that still needs to be fixed?

**Comment by LinAnt** [comment] 2018-06-15 11:08
@frenchtoasters The cloud-config is generated in JSON which is not supported by vSphere: https://github.com/rancher/rancher/issues/13115

It should be fixed in the next Rancher release 2.0.3

**Comment by frenchtoasters** [comment] 2018-06-15 12:57
Thanks for the response @LinAnt any idea when we might see v2.0.3 pushed out?

**Comment by loganhz** [comment] 2018-10-20 01:03
Thanks for the report!

We are using RKE to launch kubernetes and the cloud provider support of how to indicate your yamls are located here:
https://rancher.com/docs/rke/v0.1.x/en/config-options/cloud-providers/

Please let us know in a comment if you can still reproduce the issue, and we'll reopen it

**Closed by loganhz** 2018-10-20 01:03 UTC
Labels: area/storage, area/vsphere, version/2.0
