### ISSUE TITLE
Rancher 2.2.x cannot view logs/exec shell in cluster local project system

### ISSUE THREAD

**Issue by panho66** [rancher/rancher#18614] opened 2019-03-06 05:56 UTC
**What kind of request is this (question/bug/enhancement/feature request):**
bug

**Steps to reproduce (least amount of steps as possible):**
Install K8s using RKE then install Rancher 2.2 alpha 6
Goto Rancher UI, cluster local project system
View logs for cattle-node-agent and cattle-cluster-agent from GUI view logs
Exec shell for  cattle-node-agent and cattle-cluster-agent and rancher

**Result:**
Cannot view log and cannot exec shell

**Other details that may be helpful:**
Rancher 2.2 alpha 6 and v2.2.0-rc2 both have problem to view logs and exec shell
Rancher 2.1.x has no problem

screen dump to view logs 
![image](https://user-images.githubusercontent.com/15118220/53859078-a5749680-4030-11e9-8a87-93521b67bc0e.png)

screen dump to exec shell
![image](https://user-images.githubusercontent.com/15118220/53859103-bb825700-4030-11e9-8455-a2dd5173ba3f.png)

**Comment by superseb** [comment] 2019-03-06 09:06
Duplicate of https://github.com/rancher/rancher/issues/17028

**Closed by superseb** 2019-03-06 09:06 UTC
