### ISSUE TITLE
Rancher 2.2.2 HA cannot View/Edit Yaml when the yaml less than 2048 bytes

### ISSUE THREAD

**Issue by Maxwell1987** [rancher/rancher#19854] opened 2019-04-29 06:00 UTC
**What kind of request is this (question/bug/enhancement/feature request):**
BUG

**Steps to reproduce (least amount of steps as possible):**
any yaml less than 2048 bytes, use View/Edit yaml menu will get '[object Objec]' error.
In firefox, the request finished and response returns the base64 encoded yaml, but UI displays '[object Object].
In chrome, the request return error, and UI displays  '[object Object].

**Environment information**
- Rancher version (`rancher/rancher` 2.2.2):
- Installation option (single install/HA):
HA

**Cluster information**
- Cluster type (Custom):
- Machine type (VM) and specifications (32C/64G):
- Kubernetes version (use `kubectl version`): 1.13.5
- Docker version (use `docker version`): 18.9.5

**Comment by superseb** [comment] 2019-04-29 08:01
Duplicate of https://github.com/rancher/rancher/issues/19723

**Closed by superseb** 2019-04-29 08:01 UTC
