### ISSUE TITLE
[RFE] Projects Public API: validate `ClusterName`

### ISSUE THREAD

**Issue by cmurphy** [rancher/rancher#42913] opened 2023-09-21 21:13 UTC
**Is your feature request related to a problem? Please describe.**

Projects disappear from the UI when not in the correct namespace.

Add project:
```
apiVersion: management.cattle.io/v3
kind: Project
metadata:
  name: das-kubectl-projekt
  namespace: default
spec:
  displayName: created via kubectl
  clusterName: local
```

The project appears on the UI. Then by using the "Create namespace" button of that project to add a new namespace, the project disappears and the namespace appears into "Not in a Project".

![image (3)](https://github.com/rancher/rancher/assets/1220710/9d1afdf0-e7eb-422c-a216-18f5b935cafe)

As soon as the namespace is deleted, the project reemerges:

![image (4)](https://github.com/rancher/rancher/assets/1220710/efabf70b-1ba8-48a2-b00a-8b2f4329665c)

**Describe the solution you'd like**

The project must be in the cluster namespace, and `clusterName` must match the namespace. Either we need to validate the two fields are the same, and possibly validate that the cluster exists, or remove `clusterName` entirely since it is redundant with `namespace`.

**Comment by MbolotSuse** [comment] 2023-09-26 14:04
## Validation Template

## Root Cause

The webhook did not provide any validation on the `spec.clusterName` field of project.

## What was fixed, or what change have occurred

The following validation has been added to the `spec.clusterName` field:
- The field may not be empty.
- The field must match the namespace of the project.
- The field must refer to an existing `management.cattle.io/cluster` object.

## Areas or cases that should be tested

- Creating a project with an empty clusterName `""` -> Deny
- Creating a project which has a different clusterName than the namespace the cluster is in `some-cluster` (e.x. project is in the `local` namespace) -> Deny
- Creating a project which does not refer to a valid cluster `default` -> Deny
- Creating a project with a clusterName that refers to an existing cluster, in the correct namespace `local` -> Allow

## What areas could experience regressions

The use of the `spec.clusterName` field on projects.
Since namespace is an immutable field, and the clusterName must match the namespace, this effectively makes the clusterName field immutable, and prevents users from moving a project from one cluster to another. I think that this is acceptable, but should probably be noted.

## Are the repro steps accurate/minimal?
Yes, they are up-to-date on the issue.

**Comment by dasarinaidu** [comment] 2023-10-06 18:30
**Observation 1: Project created with errors in log**

I created a project with v1, the project got created successfully but seeing below errors in the logs.

Steps:

1. Create downstream cluster
2. Create a project from V1 endpoint

POST : {{URL}}/v1/management.cattle.io.projects
```
{
      "apiVersion": "management.cattle.io/v3",
      "kind": "Project",
      "metadata": {
    	"name": "dastest",
        "namespace": "c-m-rmnngvzg"
      },
      "spec": {
        "clusterName": "c-m-rmnngvzg",
    	"displayName": "insomnia-test-project"
      }
    }
```

Actual:
1. Project got created & i can see it on UI
2. Docker logs containing below errors that indicates serviceAccount (misleading the user)

```
2023/10/06 18:23:46 [ERROR] defaultSvcAccountHandler: Sync: error handling default ServiceAccount of namespace key=dastest, err=Operation cannot be fulfilled on namespaces "dastest": the object has been modified; please apply your changes to the latest version and try again
2023/10/06 18:23:46 [ERROR] defaultSvcAccountHandler: Sync: error handling default ServiceAccount of namespace key=dastest, err=Operation cannot be fulfilled on namespaces "dastest": the object has been modified; please apply your changes to the latest version and try again
```

**Comment by MbolotSuse** [comment] 2023-10-06 20:17
@dasarinaidu I don't believe that this is related to the above changes at all. Near as I can tell, this is a transient error caused by [this handler](https://github.com/rancher/rancher/blob/01127d844339ea8ab498f334121e2956be610409/pkg/controllers/managementuser/nsserviceaccount/nssvcaccnt.go#L70). It's transient since the error indicates that the cache returned a stale object which we attempted to use for an update, I would expect more logs if the error persisted. 

I'm not entirely sure why that handler is attempting to update your namespace (it shouldn't be a system namespace or in the system project), but the point stands that this is unrelated to the above fields.

You can try asking @maxsokolovsky for more information if you'd like more investigation into this issue, but unless you can point to a symptom from the issue it would be tough for me to call that a bug.

**Comment by dasarinaidu** [comment] 2023-10-09 21:49
https://github.com/rancher/dashboard/issues/9880

**Comment by dasarinaidu** [comment] 2023-10-09 21:54
Validated this issue on `v2.8-fc12e7d779577d10ded1a8e249f51727848b878e-head` & webhook version `rancher/rancher-webhook:v0.4.0-rc10`: ; The below tests are passed and closing this ticket.

**Test Cases:**

1. Creating a project with an empty clusterName "" -> Deny
2. Creating a project which has a different clusterName than the namespace the cluster is in some-cluster (e.x. project is in the local namespace) -> Deny
3. Creating a project which does not refer to a valid cluster default -> Deny
4. Creating a project with a cluster that refers to a not existing namespace -- Deny
5. Creating a project with a clusterName that refers to an existing cluster, in the correct namespace local -> Allow

**Closed by dasarinaidu** 2023-10-09 21:54 UTC
Labels: kind/bug, [zube]: QA Working, QA/S, team/area1
