### ISSUE TITLE
cannot ship logs to elasticsearch

### ISSUE THREAD

**Issue by zhaoyao91** [rancher/rancher#13443] opened 2018-05-11 17:56 UTC
*Describe your issue here*

I have created a cluster in AWS, and try to config the cluster to ship logs to es. I've tried aws es and es cloud service, neither worked, there is no error showing in the UI, but I can't find any new index in the es.

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v2.0.0` UI: `v2.0.41` |
|Access|`local` `admin`|
|Route|`containers.index`|

**Comment by aiwantaozi** [comment] 2018-05-12 08:54
Thanks. @zhaoyao91  Have you reset the password for user elastic in es cloud? I will check aws later.

**Comment by zhaoyao91** [comment] 2018-05-12 12:01
well, i created es on es cloud, and it just gave me the credentials and told me to save and use it

**Comment by zhaoyao91** [comment] 2018-05-13 04:44
We have tested in 2 environment. In my rancher server, I get such log

```
[ERROR] error updating ns cattle-logging status: Operation cannot be fulfilled on namespaces "cattle-logging": the object has been modified; please apply your changes to the latest version and try again
```

In another rancher server, we got such log:

```
2018-05-12 15:20:30 +0000 [warn]: #0 failed to flush the buffer. retry_time=6 next_retry_seconds=2018-05-12 15:20:59 +0000 chunk="56bfb266598fe0f6b11279aa4ae924d3" error_class=Elasticsearch::Transport::Transport::Errors::Unauthorized error="[401] "
```

**Comment by aiwantaozi** [comment] 2018-05-13 13:51
401 auth failed, could you try your username and pass in curl, doc is here: https://www.elastic.co/guide/en/x-pack/current/http-clients.html

**Comment by zhaoyao91** [comment] 2018-05-21 17:38
well, by looking though the logs of fluentd started by rancher, I found it didn't include the user and password in the settings

```
  <match c-47jrs:project-xjj7g.** project-custom.c-47jrs:project-xjj7g.**>
    @type elasticsearch
    include_tag_key true
    hosts "https://1b9d40cbaf442f26fab67523238d76de.us-west-2.aws.found.io:9243"
    reload_connections true
    logstash_prefix "test_Default"
    logstash_format true
    logstash_dateformat "%Y.%m.%d"
    type_name "container_log"
    ssl_verify true
    flush_interval 3s
    max_retry_wait 30
    disable_retry_limit
    num_threads 8
    buffer_type file
    buffer_path /fluentd/etc/buffer/project.c-47jrs:project-xjj7g.buffer
    buffer_queue_limit 128
    buffer_chunk_limit 256m
    slow_flush_log_threshold 40.0
    <buffer>
      @type file
      path /fluentd/etc/buffer/project.c-47jrs:project-xjj7g.buffer
      flush_thread_count 8
      flush_interval 3s
      retry_forever
      retry_max_interval 30
      chunk_limit_size 256m
      queue_limit_length 128
    </buffer>
  </match>
</ROOT>
```

Here is the doc of fluentd elastic search for user and password

https://github.com/uken/fluent-plugin-elasticsearch#user-password-path-scheme-ssl_verify

**Comment by aiwantaozi** [comment] 2018-05-22 08:05
thank you so much, will check and update soon.

**Comment by OBenned** [comment] 2018-05-23 10:19
I can confirm this is not working on 2.0.1

I tried to also ship logs with http only to my own ES cluster, but still no logs.
Even the embedded es doesent log anything

**Comment by krishofmans** [comment] 2018-05-23 14:04
I tried to ship logs to elasticsearch and syslog (using papertrailapp) both don't work, configuration is valid, it detects invalid config, but it doesn't actually start shipping off logs.

**Comment by OBenned** [comment] 2018-05-24 09:54
Okay so i spent the last 2½ day banging my head against the wall with this problem.
Im running my cluster on RancherOS so im not sure if this is a problem on other distros, but i would imagine so.

The problem for me, and maybe other is that fluentd needs to make symlinks from /var/lib/docker/containers to /var/log/containers which did not happen in my case, so therefore there was no data being sent to elastic

The solution for now in my case was doing the following: https://github.com/kubernetes/kubernetes/issues/52172#issuecomment-356085479
This is not a perfect solution at all, but it gotta do for now

**Comment by krishofmans** [comment] 2018-05-24 15:09
I tested the workaround with the built-in fluentd but it doesn't seem to work. 
I have a container if people are willing to try: registry.gitlab.rotate-it.be/kris/loglinker:latest
Source can be found here: https://gitlab.rotate-it.be/kris/loglinker/tree/master
There doesn't seem to be any logging output, there was initially since the script wasn't +x'd properly

**Comment by OBenned** [comment] 2018-05-24 17:16
For me the built-in was throwing all sorts of errors, so for now i followed the fluentd example https://docs.fluentd.org/v0.12/articles/kubernetes-fluentd

**Comment by brunocramos** [comment] 2018-05-29 04:56
I'm facing the same issues. I've checked my nodes and /var/log/containers exists, but it's empty.

**Comment by aiwantaozi** [comment] 2018-05-29 06:34
/var/log/containers is symlink create by k8s, could you check whether the symlink create? The symlink may like below.

# ls -l /var/log/containers
  cattle-cluster-agent-9fbb7557c-9zf97_cattle-system_cluster-register-01b358eb220bc17b72c8f22109fba8b9ae7948d91adb30f39a639a437064e5af.log -> /var/log/pods/ada285eb-5e85-11e8-83c1-080027e09ef7/cluster-register_245.log

 # /var/log/pods/ada285eb-5e85-11e8-83c1-080027e09ef7/
 # ls -l cluster-register_245.log
  cluster-register_246.log -> /var/lib/docker/containers/ca81addafdc09602560c9576ec1605f19f9e8ad12222bfa9024ac23dddcfbe88/ca81addafdc09602560c9576ec1605f19f9e8ad12222bfa9024ac23dddcfbe88-json.log

**Comment by aiwantaozi** [comment] 2018-05-29 09:21
Hi, for platforms like RancherOS and boot2docker, it may mount in different place, we will check and support for RancherOS and boot2docker.

Could you check whether is have symlink under:
RancherOS: /opt/rke/var/log/containers
Boot2Docker: /mnt/sda1/rke/var/log/containers

**Comment by brunocramos** [comment] 2018-05-29 13:43
Just as @aiwantaozi mentioned, it seems it's indeed an issue with the path. I'm using RancherOS as well.

![image](https://user-images.githubusercontent.com/4956907/40662535-fd9855ae-632c-11e8-97bd-5cbb2d94c0fd.png)

**Comment by krishofmans** [comment] 2018-05-29 14:23
Great, yep, there they are, I will try the workaround again with that directory:
![image](https://user-images.githubusercontent.com/999774/40655901-fe1c26d4-6342-11e8-9a7e-ae9bf1ea4516.png)
This was a machine created by rancher OS, sort of expected it to know out of the box where the logs are located. I assume there will need to be some sort of log directory detection mechanism that will have to be implemented?

**Comment by gkTim** [comment] 2018-05-29 15:43
So how can we change the path of the embedded elastic search logging to this path?
And is rancher not testing on there own distro?

**Comment by krishofmans** [comment] 2018-05-30 08:46
I changed the workaround to use the proper host path on boot2docker:
```
kind: DaemonSet
apiVersion: extensions/v1beta1
metadata:
  name: log-linker
  namespace: kube-system
  labels:
    app: log-linker
spec:
  selector:
    matchLabels:
      app: log-linker
  template:
    metadata:
      labels:
        app: log-linker
    spec:
      containers:
      - name: log-linker
        image: registry.gitlab.rotate-it.be/kris/loglinker:latest
        command:
        - /log-linker.sh
        volumeMounts:
        - name: var-lib-docker
          mountPath: /var/lib/docker
        - name: var-log
          mountPath: /var/log
      volumes:
      - name: var-log
        hostPath:
          path: /mnt/sda1/rke/var/log
      - name: var-lib-docker
        hostPath:
          path: /var/lib/docker
```

I can see the log files in an interactive shell on the deamonset, but it still does not ship them.

**Comment by RobAWilkinson** [comment] 2018-05-30 16:56
I'm experience the exact same issue on the same version trying to ship logs to elastic search. I keep seeing this error in my Docker logs for the rancher host could it be related?
```
error updating ns cattle-logging status: Operation cannot be fulfilled on namespaces "cattle-logging": the object has been modified; please apply your changes to the latest version and try again
```

**Comment by aiwantaozi** [comment] 2018-06-11 02:28
https://github.com/rancher/rke/issues/662

**Comment by jiuchongxiao** [comment] 2018-06-20 11:06
@zhaoyao91  did you solved it? i have the same issue

**Comment by zhaoyao91** [comment] 2018-06-20 17:37
@jiuchongxiao yes, I have solved it by not using rancher

**Comment by cloudnautique** [comment] 2018-06-29 19:44
a workaround in the cloudconfig for RancherOS. 
```
#cloud-config
ssh_authorized_keys:
- <SSH_AUTHORIZED_KEYS>
write_files:
  - path: /etc/rc.local
    permissions: "0755"
    owner: root
    content: |
      #!/bin/bash
      rm -rf /var/log/containers /var/log/pods /var/lib/rancher/rke/log
      ln -s /opt/rke/var/log/containers /var/log/containers
      ln -s /opt/rke/var/log/pods /var/log/pods
      mkdir -p /var/lib/rancher/rke
      ln -s /opt/rke/var/lib/rancher/rke/log /var/lib/rancher/rke/log
      wait-for-docker
      <DOCKER_REG_COMMAND>
rancher:
  docker:
    engine: docker-17.03.2-ce
```

**Comment by sandbox-services** [comment] 2018-07-03 21:22
This issue has been resolved within RKE but still persists with clusters created by the UI.

https://github.com/rancher/rke/issues/662

**Comment by aiwantaozi** [comment] 2018-09-06 01:14
If docker root is not default /var/lib/docker, you could config it in the cluster option now.  And rke also make the symbol link for ```/var/log/containers/``` ```/var/log/pods/``` and ```/var/lib/docker```. You can try the new version to check whether it work.

**Comment by aiwantaozi** [comment] 2018-09-19 10:08
Related PR: https://github.com/rancher/rancher/pull/14667
You can config custom docker root in the cluster option page.

**Comment by aiwantaozi** [comment] 2018-09-19 10:09
Close in favour of https://github.com/rancher/rancher/issues/13304

**Closed by aiwantaozi** 2018-09-19 10:10 UTC
Labels: area/tools, kind/bug, status/resolved, team/cn, version/2.0
