### ISSUE TITLE
v2.6.3 - Tracking issue for RKE2 k8s November Patches

### ISSUE THREAD

**Issue by Jono-SUSE-Rancher** [rancher/rancher#35369] opened 2021-11-03 22:01 UTC
This is the tracking issue for the RKE2 November k8s Patches. We should be checking/validating the following versions:

- v1.22.4
- 1.21.7
- v1.20.13

**Comment by deniseschannon** [comment] 2021-11-19 03:27
Per the other issue: 

Assigning @rancher-max to introduce 1.22 RKE2/k3s versions in KDM now that Rancher v2.6-head runs on local 1.22.
Changes would go into dev-v2.6-1.22 KDM branch.

Keeping @kinarashah  assigned so I don't miss on tracking these versions for final release.

**Comment by rancher-max** [comment] 2021-12-03 17:42
Since dev-v2.6-1.22 KDM was merged to dev-v2.6, the changes were put into dev-v2.6 KDM directly.

I have validated pointing KDM to https://raw.githubusercontent.com/rancher/kontainer-driver-metadata/dev-v2.6/data/data.json on rancher v2.6.3-rc3 that both upgrades and provisioning work as expected.

**Upgrade UI on a v1.20.12+rke2r1 cluster**:
<img width="1675" alt="image" src="https://user-images.githubusercontent.com/55997940/144640046-a0d492d0-13fc-4d88-a429-4acb7afc604b.png">
Confirmed that upgrading to each of the new versions (v1.20.13+rke2r1, v1.21.7+rke2r1, and v1.22.4+rke2r1) is successful. 

**Provisioning UI:**
<img width="714" alt="image" src="https://user-images.githubusercontent.com/55997940/144645518-580ea4e3-757b-4b60-9439-76322ff381dd.png">
Confirmed that I am able to provision both versions, although 1.22 hits https://github.com/rancher/rancher/issues/35683. That issue will cover 1.22 provisioning, so from a KDM prospective, this issue has been fully validated and is working as expected.

**Closed by rancher-max** 2021-12-03 17:42 UTC
Labels: [zube]: To Test, dependency-rke2
