### ISSUE TITLE
[RFE] Provide CA cert when using onsite s3 api

### ISSUE THREAD

**Issue by aemneina** [rancher/rancher#19489] opened 2019-04-10 00:48 UTC
**What kind of request is this (question/bug/enhancement/feature request):**
feature

**Use case:**
The configuration provided by the current implementation of S3 backups does not have a provision to include/add a client-trusted CA or read additional certificates from the host system trusted CA certs.

The go function SystemCertPool() as an example of functionality works well for this requirement as it will also use a copy of the host system trusted CA certs and our hosts are already configured that way.

**Result:**
When using self signed certificates Rancher will fail with an error 'certificate signed by unknown authority' on sending .
This is why we need the HTTPS client to be able to add Extra CA Certs.

**Comment by deniseschannon** [comment] 2019-04-16 03:49
Duplicate of https://github.com/rancher/rancher/issues/19222

**Closed by deniseschannon** 2019-04-16 03:49 UTC
Labels: area/backup-recover, kind/enhancement
