### ISSUE TITLE
namespace via kubectl can be created exeeding the project resource Quotas

### ISSUE THREAD

**Issue by OlliL** [rancher/rancher#25794] opened 2020-03-05 08:02 UTC
**What kind of request is this:** bug

**Steps to reproduce (least amount of steps as possible):**
Create a namespace via "rancher kubectl create -f  yaml-file"
```
apiVersion: v1
kind: Namespace
metadata:
  annotations:
    field.cattle.io/projectId: c-z8rqx:p-5k5jx
    field.cattle.io/resourceQuota: '{"limit":{"limitsCpu":"30000m","limitsMemory":"20048Mi","requestsCpu":"600000m","requestsMemory":"1000024Mi"}}'
    field.cattle.io/containerDefaultResourceLimit: '{}'
  name: dummy
```

**Result:**
Namespace is created exeeding the Project Resource Quotas. Namespace can also no longer be edited in Rancher UI because then the API Resource Quota validation kicks in and prevents saving any changes.

I would have expected that some kind of admission controller prevents me from creating a namespace in a project context via kubectl exceeding the Rancher defined Project Quota.

**Environment information**
- Rancher version: 2.3.5
- Installation option: HA

**Cluster information**
- Cluster type: Custom
- Machine type: VM
- Kubernetes version: v1.14.6
- Docker version: 19.3

gz#10910

**Comment by danielxolsson** [comment] 2020-03-05 10:54
I can confirm this behavior with rancher installed kubernetes version v1.17.3 and rancher v2.3.5.

**Comment by OlliL** [comment] 2020-06-07 13:58
Push?

**Comment by 5nafu** [comment] 2020-06-26 14:51
This applies not only to namespaces with the annotation `field.cattle.io/resourceQuota`, set in the YAML file, but also to any namespaces created without any quotas, if the default quotas in the project will exceed the available resources.

**Comment by janeczku** [comment] 2020-08-27 16:20
I could not reproduce this on Rancher v2.4.5.

When creating a namespace with kubectl and assigning it to a project using the `field.cattle.io/projectId` annotation, Rancher created a ResourceQuota in that namespace using the "default namespaces quotas" configured in that project.

**Closed** 2020-08-27 18:01 UTC

**Comment by vincebrannon** [comment] 2022-07-07 14:07
Can reproduce this in 2.6.5, results in negative numbers in the Rancher GUI when editing the namespace. 
Customer would like to see the YAML values sanity checked against the project limits before it is accepted.
