### ISSUE TITLE
Web view of API is blank

### ISSUE THREAD

**Issue by michaelkoro** [rancher/rancher#15050] opened 2018-08-12 08:28 UTC
**Rancher versions:**
rancher/server or rancher/rancher: 2.0.4
rancher/agent or rancher/rancher-agent: 2.0.4

**Docker version:**
17.03.2

**Operating system and kernel:**
Ubuntu 16.04

**Type/provider of hosts: **
VSphere VM

**Setup details:**
Air gap installation

**Steps to Reproduce:**
Start up rancher server. Configure the api endpoint as the name of the server.
Login to rancher, try to access the endpoint - you'll get a blank web page.
When trying to curl the webpage, you'll get an authentication error, create a new API key, and use its tokens to curl the api, you'll get back a long json.

**Comment by superseb** [comment] 2018-08-12 09:02
Duplicate of https://github.com/rancher/rancher/issues/14649

**Closed by superseb** 2018-08-12 09:02 UTC
