### ISSUE TITLE
rancher-images.txt for rancher 2.5.8 and 2.5.9 is missing docker.io/rancher/kubectl:v1.18.6 -> uninstall crd job fails in image pull due to that

### ISSUE THREAD

**Issue by Martin-Weiss** [rancher/rancher#34074] opened 2021-08-09 12:38 UTC
**Rancher Server Setup**
- Rancher version: 2.5.8 or 2.5.9
- Installation option (Docker install/Helm Chart): helm chart, rke2 1.20.8

**Information about the Cluster**
- Kubernetes version: 1.20.8

**Describe the bug**
Uninstall CRD job does not execute because it wants to use image docker.io/rancher/kubectl:v1.18.6 which is not in the private registry, because it is not part of the rancher-images.txt for 2.5.8 and 2.5.9

**To Reproduce**
Air gapped setup
Only mirror the images from rancher-images.txt
Install a CRD
Uninstall a CRD -> job fails in image pull

**Result**
Uninstall CRD does not work

**Expected Result**
All required images should be in rancher-images.txt so that the CRD uninstall job works also in airgapped..

**Comment by cbron** [comment] 2021-08-10 16:08
@Martin-Weiss can you clarify which chart you are trying to uninstall, is it rancher itself ? Starting in 2.5.8 the rancher chart doesn't use `rancher/kubectl` for the uninstall, it uses the shell image from setting.go. 
You can see that here: `wget https://releases.rancher.com/server-charts/stable/rancher-2.5.8.tgz` -> look in values.yaml `postDelete.image.repository`. That is `rancher/shell:v0.1.6` which is in the airgap list. 

Was this an upgrade or a fresh install ? Are there any more error logs ?

**Comment by Martin-Weiss** [comment] 2021-08-10 16:51
The customer deployed the rancher-monitoring-crd 9.4 helm chart to the default namespace in a downstream cluster. When you now go to rancher apps and marketplace in explorer and ask for "uninstall" - the kubectl:v1.18.6 image is used.
I can also see that there is a kubectl:v1.18.0 image in the images.txt so not sure why we have that but not v1.18.6?

**Comment by cbron** [comment] 2021-08-10 17:34
Moving to 2.5.10, I believe we just need to backport a different fix.

**Comment by jiaqiluo** [comment] 2021-08-13 23:27
To be clear, The fix is to include the CRD charts when the package script generates the images.txt file. 
But it does not bring the image `rancher/kubectl:v1.18.6` back because the package script runs against only the latest version of each chart and the missing image is not used in the latest version of the monitoring v2 chart anymore.

**Comment by brendarearden** [comment] 2021-09-14 19:49
available to test in v2.5.10-rc1

**Comment by izaac** [comment] 2021-09-21 20:18
Reproduced on Rancher version: `v2.5.9` Airgap

**Comment by izaac** [comment] 2021-09-21 23:13
Results on Rancher version `v2.5.10-rc1`

- Latest chart version works install/uninstall `v16.6.0`
- Next version `v14.5.100` crd create/delete jobs failed pulling `rancher/rancher-agent:v2.5.7`
- Next version `v9.4.203` crd create/delete jobs failed pulling `rancher/kubectl:v1.18.6`

So it's ok to assume only the latest chart version will work on a fresh Airgap install?

@jiaqiluo @cbron

**Comment by jiaqiluo** [comment] 2021-09-22 16:37
@izaac Yep, it looks good.

**Closed** 2021-09-22 16:42 UTC
Labels: [zube]: QA Working
