### ISSUE TITLE
Unable to create sidekick with image: docker:dind

### ISSUE THREAD

**Issue by withinboredom** [rancher/rancher#4808] opened 2016-05-16 04:03 UTC
*Describe your issue here*
I'm trying to use docker in docker for jenkins swarm. I'm unable to create a sidecar with the image `docker:dind` I get the error that it cannot find image `dind` as it seems to have stripped the `docker:` part. This also causes an infinite loop of creating services, which if it isn't already a separate issue, I can make as well.

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v1.1.0-dev1` Cattle: `v0.160.3` UI: `v1.0.7` |
|Access|`github` `admin`|
|Route|`container.labels`|

**Comment by patrickbusch** [comment] 2016-05-20 11:46
I have exactly the same problem, want to run `docker:1.10.3-dind` but the image name gets stripped to `1.10.3-dind', running on rancher 1.0.1

**Comment by patrickbusch** [comment] 2016-05-20 11:49
I this is already a known bug here: https://github.com/rancher/rancher/issues/2801

A possible workaround should be downloading the image, retagging, and using it then. I will try that later

**Comment by deniseschannon** [comment] 2016-05-20 14:37
Yes, this is a duplicate of #2801. Will close in favor of the original issue. 

Basically either primary service or sidekick service wouldn't be able to use a `docker:tag`.

**Closed by deniseschannon** 2016-05-20 14:37 UTC
