### ISSUE TITLE
rancher version filter did not work in the catalog apps

### ISSUE THREAD

**Issue by guangbochen** [rancher/rancher#15014] opened 2018-08-09 09:14 UTC
Rancher versions: v2.0.7

Steps to Reproduce:

1. Add a custom catalog with a chart that contains `rancher_version: v2.0.8` in its questions.yml file
2. Go to `Catalog Apps` page and filter the app by name
3. The app which contains the `rancher_version: v2.0.7` is still showing up

Results: The app with  `rancher_version: v2.0.8` is not expected to show up.

**Comment by StrongMonkey** [comment] 2018-08-15 16:37
`RancherVersion` is only a thing for templateVersion. And for filter, try to remove `category_ne` filter and apply again.

**Comment by guangbochen** [comment] 2018-08-20 02:38
In Rancher 1.6.x, the catalog apps are filtered by the back-end using `. minimum_rancher_version` instead of front-end @vincent99.

So I think we need to add version filtering in Rancher 2.0 ASAP, @deniseschannon @StrongMonkey, e.g. `Kubernetes dashboard` will only show up in 2.0.7 as it requires to use `System Project` .

**Comment by alena1108** [comment] 2018-09-05 20:14
That sounds like the missing feature, not a bug

**Comment by deniseschannon** [comment] 2019-05-09 20:26
Duplicate of https://github.com/rancher/rancher/issues/18469

**Closed by deniseschannon** 2019-05-09 20:26 UTC
Labels: area/catalog, kind/feature
