### ISSUE TITLE
[Monitoring] - Add Deployment and Daemonset kind to Rancher / Workload dashboards

### ISSUE THREAD

**Issue by codyrancher** [rancher/rancher#35340] opened 2021-11-01 22:36 UTC
Currently the Rancher / Workload and Rancher / Workload (Pods) dashboards in grafana only allow you to select ReplicaSet as the kind. These dashboards need to support the other two kinds before we can tackle this issue on the front end https://github.com/rancher/dashboard/issues/1879

![image](https://user-images.githubusercontent.com/55104481/139751026-b8e0601e-88ba-4f19-99f1-25a65d6d2135.png)

**Comment by gaktive** [comment] 2021-11-01 22:44
Labelled this as 2.6.3 for now based on the related UI milestone. Will advise PM about possible slip based on timing.

**Comment by aiyengar2** [comment] 2021-11-01 22:44
The root cause for this is that the `created_by_kind` field within `kube-state-metrics` metrics for `Deployments`, `StatefulSets`, `DaemonSets`, `Jobs`, etc. will always be `ReplicaSet`.

This is because those resources create `ReplicaSet`s, which in turn create `Pod`s, so the resource who creates the pods whose metrics we are aggregating will always generally be a `ReplicaSet` (unless a user directly `kubectl apply`s a `Pod`, which is uncommon afaik).

The fix for this will involve refactoring **both** dashboards in https://github.com/rancher/charts/tree/release-v2.6/charts/rancher-monitoring/rancher-monitoring/100.0.0%2Bup16.6.0/files/rancher/workloads in order to utilize `kube_replicaset_owner` to collect the data owned by all Pods owned by all ReplicaSets owned by a particular kind of resource.

**Comment by aiyengar2** [comment] 2021-11-01 22:48
Instead of refactoring, another good idea might be to just relabel the existing dashboards to `ReplicaSet` dashboards and drop the `kind` field in favor of hard-coding the `kind` to `ReplicaSet`.

Then create new `Workload` dashboards based on the now-renamed `ReplicaSet` dashboards that support a `kind` dropdown that lists `Deployments`, `DaemonSets`, etc.

**Comment by vincent99** [comment] 2021-11-02 00:55
> The root cause for this is that the created_by_kind field within kube-state-metrics metrics for Deployments, StatefulSets, DaemonSets, Jobs, etc. will always be ReplicaSet.
> This is because those resources create ReplicaSets, which in turn create Pods

This is only true for Deployments.. Jobs, DaemonSets, etc manage Pods directly, not an intermediary ReplicaSet.

**Comment by jiaqiluo** [comment] 2021-11-10 20:50
With rancher-monitoring chart `100.0.0+up16.6.0`, the list of `kind` is dynamically generated depending on resources in the namespace.  For example, I see the following three kinds in the namespace `cattle-monitoring-system`

<img width="880" alt="Screen Shot 2021-11-10 at 12 12 33 PM" src="https://user-images.githubusercontent.com/6218999/141190531-45ac7f93-c732-4263-959d-161581e399fd.png">


Also, if a new kind of resource is deployed into the namespace, the list of `kind` will update to include the kind autonomically.

Based on those results,  I wonder if the issue is still valid unless I misunderstand the scenarios here? 
cc @codyrancher

**Comment by jiaqiluo** [comment] 2021-11-10 22:03
I confirmed with @codyrancher offline that we can close this issue with the following two conclusions: 
- the kind list is updated dynamically depending on the resources in the target namespace   
- `ReplicaSet` is equivalent to Deployment in K8s world

**Closed by jiaqiluo** 2021-11-10 22:03 UTC
Labels: internal, area/windows, area/monitoring, [zube]: Working
