### ISSUE TITLE
CLI for GlobalDNS & globalDNS provider rbac changes and actions

### ISSUE THREAD

**Issue by mrajashree** [rancher/rancher#17982] opened 2019-02-11 23:02 UTC
This ticket is to track the changes to globalDNS CLI made for rbac

1. GlobalDNS spec will have a new field for Members; members will have only one access type and that is owner
2. There will be 2 new actions on globalDNS called addProjects and removeProjects for modifying the projects. Both will take as input a list of v3.Project
3. Projects field is now non updatable in the API, since we have actions described above for updating them.
4. Rest of the fields can be updated via Edit/PUT

GlobalDNS provider will also have a new field for Members, and each member can have only one access type that is owner.

**Comment by cjellick** [comment] 2019-03-01 02:24
available in cli version v2.2.0-rc11

**Comment by cjellick** [comment] 2019-03-01 02:25
@moelsayed to validate, since you have the other mcapp cli issues, but if you are busy, we can reassign

**Comment by alena1108** [comment] 2019-03-05 19:04
@mrajashree to validate

**Comment by gitlawr** [comment] 2019-03-07 07:01
To validate, Run `rancher globaldns -h` and follow the command usage. It should be self-descriptive, otherwise we can improve the descriptions.

**Comment by prachidamle** [comment] 2019-03-09 11:17
While trying to create a GlobalDNS entry, I get this error for the projectID:

Prachis-MacBook-Pro:rancher-v2.2.0-rc13 prachi$ ./rancher globaldns entries create --provider nn --fqdn a.com --project local:p-sst8r
FATA[0000] Get https://localhost:8443/v3: EOF 

Any idea why the CLI fails to list this project? (its local's Default project)

**Comment by gitlawr** [comment] 2019-03-09 14:47
@prachidamle I cannot reproduce the error, but the EOF might reflect unexpected closed connections.
1. How do you know the error comes from listing projects?
2. Is this error consistently reproduced for multiple tries, changing to different projects, etc.?

To get more details you can do `export RANCHER_CLIENT_DEBUG=true` before running the command, it will print requests and responses for the API calls and help diagnose

**Comment by prachidamle** [comment] 2019-03-11 22:43
@gitlawr I tried on an ha setup and no longer receive the error while creating GlobalDNS entry. However now updating the entry fails for me:

```
Prachis-MacBook-Pro:rancher-v2.2.0-rc13 prachi$ ./rancher globaldns entries
ID                            FQDN        PROVIDER_ID                          TARGET                       CREATED
cattle-global-data:gd-5cwsk   testc.com   cattle-global-data:prachi-provider   afterupgcluster:newproject   2019-03-11T22:40:32Z
cattle-global-data:gd-p56st   test.com    cattle-global-data:prachi-provider   afterupgcluster:newproject   2019-03-11T22:34:13Z


Prachis-MacBook-Pro:rancher-v2.2.0-rc13 prachi$ ./rancher globaldns entries update --fqdn testb.com cattle-global-data:gd-5cwsk
FATA[0000] Bad response statusCode [500]. Status [500 Internal Server Error]. Body: [] from [https://soumyahatest.qa.rancher.space/v3/globalDnses/cattle-global-data:gd-5cwsk] 

```

**Comment by gitlawr** [comment] 2019-03-12 04:19
1. It is sending only changing fields. Missing fields should be unchanged, see: https://github.com/rancher/norman/blob/master/store/proxy/proxy_store.go#L402
The reason why we [do that in cli](https://github.com/rancher/cli/blob/master/cmd/globaldns.go#L743) is because every field has `omitempty` tag, and the framework marshalls the input and drop all empty fields, making them unchanged. As a result, e.g., we cannot set member slice to empty when using the API object as the input.
2. It is actual call done twice, we usually do [Lookup](https://github.com/rancher/cli/blob/master/cmd/common.go#L299) first to get a resource interface then get the object by ID(so that we can handling object with both name or ID).

These are two common patterns in cli.

Regarding the 500 issue, I cannot reproduce it as well. Do you get the same 500 when you do a
```
curl -k -u <token> -X PUT -H "Content-Type: application/json" -d '{"fqdn":"testb.com"}' https://soumyahatest.qa.rancher.space/v3/globalDnses/cattle-global-data:gd-5cwsk
```

**Comment by prachidamle** [comment] 2019-03-12 23:51
@gitlawr, the 500 issues was a bug in GlobalDNS that was resolved todayhttps://github.com/rancher/rancher/pull/18841

I tested with the fix, Global DNS CLI worked fine. Validated all of the following commands

```Commands validated:
     ls                List global DNS entries
     create            Create a global DNS entry
     update            Update a global DNS entry
     delete, rm        Delete global DNS entries
     list-members, lm  List members of a global DNS entry
     add-member        Add members to a global DNS entry
     delete-member     Delete members from a global DNS entry
     add-project       Add target projects to a global DNS entry
     delete-project    Delete target projects from a global DNS entry```

**Comment by prachidamle** [comment] 2019-03-12 23:52
@alena1108 issue is validated, please close per review.

**Comment by gitlawr** [comment] 2019-03-13 01:57
Changing target type is tricky now.
Mcapp target -> projects target: Update and reset mcapp then do `add-project`
Projects target -> Mcapp target: Need to do `delete-project` then update to set mcapp

We should make that straightforward for users:
When the current target is mcapp, running `add-project` makes the switch
When the current target is project, running `update --multi-cluster-app` makes the switch

**Comment by cjellick** [comment] 2019-03-13 16:23
remaining requests form @prachidamle comment are in v2.2.0-rc14

**Comment by sangeethah** [comment] 2019-03-13 17:22
Assigned to @prachidamle for validation.

**Comment by prachidamle** [comment] 2019-03-13 18:51
Validated the recent fix for following usecases:
When the current target is mcapp, running add-project makes the switch
When the current target is project, running update --multi-cluster-app makes the switch

Also validate other commands again.

**Comment by prachidamle** [comment] 2019-03-13 18:51
@alena1108 / @cjellick to close the issue after reviewing the validation.

**Closed** 2019-03-15 18:18 UTC
Labels: area/cli, area/multi-cluster-app, kind/feature-component, status/ready-for-review, status/reopened, status/resolved, status/to-validate, status/working, team/cn, version/2.0
