### ISSUE TITLE
update rancher code to compatible with the prometheus operator crd validation

### ISSUE THREAD

**Issue by aiwantaozi** [rancher/rancher#21904] opened 2019-08-01 08:21 UTC
Rancher server: master
After @guangbochen 's pr https://github.com/rancher/system-charts/pull/72 added validation to prometheus operator crd, we need to update rancher code to compatible with the validation

related issue:
https://github.com/rancher/rancher/issues/19362

Step to reproduce:
1. use dev system-charts, enable monitoring to deploy the crd include validation
2. add notifiers
3. add a cluster level event alert
4. then app rancher-alerting is deployed
5. check rancher server log and find errors
```
2019/08/01 08:53:56 [ERROR] ClusterAlertGroupController local/event-alert [cluster-alert-group-deployer] failed with : failed to get Alertmanager Deployment information, statefulsets.apps "alertmanager-cluster-alerting" not found, [cluster-alert-group-controller] failed with : create prometheus rule cattle-prometheus:local failed, PrometheusRule.monitoring.coreos.com "local" is invalid: []: Invalid value: map[string]interface {}{"kind":"PrometheusRule", "apiVersion":"monitoring.coreos.com/v1", "metadata":map[string]interface {}{"labels":map[string]interface {}{"source":"rancher-alert", "cattle.io/creator":"norman"}, "generation":1, "uid":"e5696d58-b439-11e9-b189-067d93cedea8", "name":"local", "namespace":"cattle-prometheus", "creationTimestamp":"2019-08-01T08:53:56Z"}, "spec":map[string]interface {}{"groups":[]interface {}{map[string]interface {}{"name":"local:event-alert", "rules":interface {}(nil)}}}}: validation failure list:
spec.groups.rules in body must be of type array: "null"
2019/08/01 08:53:57 [ERROR] ClusterAlertRuleController local/deployment-event-alert [cluster-alert-rule-deployer] failed with : failed to get Alertmanager Deployment information, statefulsets.apps "alertmanager-cluster-alerting" not found, [cluster-alert-rule-controller] failed with : create prometheus rule cattle-prometheus:local failed, PrometheusRule.monitoring.coreos.com "local" is invalid: []: Invalid value: map[string]interface {}{"apiVersion":"monitoring.coreos.com/v1", "metadata":map[string]interface {}{"creationTimestamp":"2019-08-01T08:53:57Z", "labels":map[string]interface {}{"cattle.io/creator":"norman", "source":"rancher-alert"}, "generation":1, "uid":"e5ad1eee-b439-11e9-b189-067d93cedea8", "name":"local", "namespace":"cattle-prometheus"}, "spec":map[string]interface {}{"groups":[]interface {}{map[string]interface {}{"name":"local:event-alert", "rules":interface {}(nil)}}}, "kind":"PrometheusRule"}: validation failure list:
spec.groups.rules in body must be of type array: "null"
...
2019/08/01 08:55:00 [ERROR] ClusterAlertGroupController local/event-alert [cluster-alert-group-controller] failed with : create prometheus rule cattle-prometheus:local failed, PrometheusRule.monitoring.coreos.com "local" is invalid: []: Invalid value: map[string]interface {}{"spec":map[string]interface {}{"groups":[]interface {}{map[string]interface {}{"name":"local:event-alert", "rules":interface {}(nil)}}}, "kind":"PrometheusRule", "apiVersion":"monitoring.coreos.com/v1", "metadata":map[string]interface {}{"generation":1, "uid":"0b6149f4-b43a-11e9-b189-067d93cedea8", "name":"local", "namespace":"cattle-prometheus", "creationTimestamp":"2019-08-01T08:55:00Z", "labels":map[string]interface {}{"cattle.io/creator":"norman", "source":"rancher-alert"}}}: validation failure list:
spec.groups.rules in body must be of type array: "null"
2019/08/01 08:55:00 [ERROR] ClusterAlertRuleController local/deployment-event-alert [cluster-alert-rule-controller] failed with : create prometheus rule cattle-prometheus:local failed, PrometheusRule.monitoring.coreos.com "local" is invalid: []: Invalid value: map[string]interface {}{"kind":"PrometheusRule", "apiVersion":"monitoring.coreos.com/v1", "metadata":map[string]interface {}{"generation":1, "uid":"0ba98af7-b43a-11e9-b189-067d93cedea8", "name":"local", "namespace":"cattle-prometheus", "creationTimestamp":"2019-08-01T08:55:00Z", "labels":map[string]interface {}{"cattle.io/creator":"norman", "source":"rancher-alert"}}, "spec":map[string]interface {}{"groups":[]interface {}{map[string]interface {}{"rules":interface {}(nil), "name":"local:event-alert"}}}}: validation failure list:
spec.groups.rules in body must be of type array: "null"
```

**Comment by jiaqiluo** [comment] 2019-08-28 23:48
The bug fix is validated in Rancher:master-head 19e84cee4 

Since the bug is found and fixed in master-head, so it is not reproducible. 

Steps are the same as the issue describes:
- use dev system-charts, enable monitoring to deploy the crd include validation
- add notifiers
- add a cluster level event alert
- then app rancher-alerting is deployed
- check rancher server log and find errors

Results:
- the errors in the issue are not shown anymore
- cluster altering works as expected

**Closed by jiaqiluo** 2019-08-28 23:48 UTC
Labels: [zube]: To Test, area/alerting, area/monitoring, kind/bug-qa, team/cn
