### ISSUE TITLE
too many open files?

### ISSUE THREAD

**Issue by joshuacox** [rancher/rancher#1219] opened 2015-06-14 13:30 UTC
I know this sort of stuff has been discussed extensively in the past, but I feel that I don't have enough containers to have run into this issue.  I have four days uptime on a rancherOS node, and yet with just a handful of containers running I'm hitting the `too many open files` wall.  I can certainly fix things from here and get it working by doing some cleanup, but I feel very much that I am just treating the symptom of a larger issue.  I suspect the root cause is something with overlay itself piling up openfiles.

```
rancher@rancher:~$ docker run --name $OVPN_DATA -v /etc/openvpn busybox
FATA[0000] Error response from daemon: open /var/lib/docker/repositories-overlay: too many open files 
rancher@rancher:~$ docker ps -a
CONTAINER ID        IMAGE                             COMMAND                CREATED             STATUS                       PORTS                                          NAMES
b50eb510e8ae        rancher/agent-instance:v0.3.1     "/etc/init.d/agent-i   3 days ago          Up 3 days                                                                   a30d13a2-b6c0-4918-be81-4ddad1f91ead   
216acc9c7ed9        nginx:latest                      "nginx -g 'daemon of   3 days ago          Up 3 days                    80/tcp, 443/tcp                                9c042341-ee20-48f4-ba1c-fff2103cc0fe   
d054276ff9da        mysql:latest                      "/entrypoint.sh mysq   3 days ago          Up 3 days                    3306/tcp                                       00b0bb7e-315b-4ba4-902a-d5dfe7958e1d   
1bdd4a1be033        rancher/agent:v0.7.9              "/run.sh run"          3 days ago          Up 3 days                                                                   rancher-agent                          
8257cff9bb54        joshuacox/docker-icinga2:latest   "/entrypoint.sh /usr   4 days ago          Up 4 days                    80/tcp                                         54a086b4-979b-4bcb-9053-938323279085   
c913c04cc127        rancher/agent-instance:v0.3.1     "/etc/init.d/agent-i   4 days ago          Up 4 days                    0.0.0.0:500->500/udp, 0.0.0.0:4500->4500/udp   74525b44-5a30-40dc-8f0d-37a9418de210   
e9c18cc8e015        rancher/agent:v0.7.9              "/run.sh state"        4 days ago          Exited (0) 4 days ago                                                       rancher-agent-state                    
bb5ca9d03bc1        rancher/agent:v0.7.9              "/run.sh http://ranc   4 days ago          Restarting (-1) 2 days ago 
```

**Comment by vincent99** [comment] 2015-06-19 18:55
@joshuacox can you please add your comments to https://github.com/rancherio/os/issues/359

**Comment by deniseschannon** [comment] 2015-06-24 17:45
This isn't just a RancherOS issue as I've had the same issue reproduced on RHEL 6.

**Comment by joshuacox** [comment] 2015-06-25 07:07
@deniseschannon can you confirm what storage driver you are using?  Notice I'm using overlay here, but I also have hosts using AUFS and BTRFS this problem is singular with overlay,  though I have separate problems with the other storages as well.

**Comment by ibuildthecloud** [comment] 2015-06-27 17:14
When this error occurs can you please share the output of "lsof -p <docker daemon pid>".  I believe this is a bug in Docker 1.6

**Comment by moimael** [comment] 2015-06-29 08:31
I hit the same issue. here is the output of lsof -p : 
    31536	/bin/bash	/dev/pts/0
    31536	/bin/bash	/dev/pts/0
    31536	/bin/bash	/dev/pts/0
    31536	/bin/bash	/dev/pts/0

**Comment by moimael** [comment] 2015-06-30 10:07
Is there a workaround ? I can't event stop container or list images.

**Comment by Nicofuma** [comment] 2015-06-30 10:09
use ps to find and then kill the process of the rancher-agent

**Comment by imikushin** [comment] 2015-08-21 18:40
FYI, I've just set `ulimit -n` to 1000000 and  `/proc/sys/fs/file-max` to 1000000000 in v0.4.0-dev. This is coming to v0.4.0-rc2 to be cut in a few minutes.

**Comment by EliSnow** [comment] 2015-09-04 20:44
@imikushin, how can I change these settings in an existing, running RancherOS v0.3.3 server? I need to up the open file limit for a database container but `ulimit -n unlimited` gives me `ulimit: open files: cannot modify limit: Operation not permitted` and modifying `/etc/security/limit.conf` doesn't seem to have any affect.

**Comment by imikushin** [comment] 2015-09-07 05:28
Thanks @EliSnow! 
So, you can add `--default-ulimit, nofile=1000000:1000000` to docker args via cloud-config. On RancherOS v0.3.3 this should look like:
```yml
#cloud-config
rancher:
  user_docker:
    args: [docker, -d, -s, overlay, -G, docker, -H, 'unix:///var/run/docker.sock', --default-ulimit, nofile=1000000:1000000]
```
Or, using `ros config`:
```
# ros config set rancher.user_docker.args [docker, -d, -s, overlay, -G, docker, -H, 'unix:///var/run/docker.sock', --default-ulimit, nofile=1000000:1000000]
```

**Comment by eyecreate** [comment] 2015-10-13 03:20
I tried increasing my docker container ulimits using the ros config listed above and was told Incorrect usage. Should I change from what is listed by imikishin?

**Comment by deniseschannon** [comment] 2015-10-14 18:29
@eyecreate which version of rancherOS are you using? 

In RancherOS, v0.3.3, it should probably be
```
ros config set user_docker.args [docker, -d, -s, overlay, -G, docker, -H, 'unix:///var/run/docker.sock', --default-ulimit, nofile=1000000:1000000]
```

In v0.4.0, we require the `rancher` prefix as we are allowing cloud configs (includes write_files, ssh_authorized_keys) to be saved versus just the rancher configurations.

**Comment by MhdAli** [comment] 2015-10-28 02:44
I had the same issue I guess as @eyecreate, every time I run the mentioned command I get
```
$ sudo ros config set user_docker.args [docker, -d, -s, overlay, -G, docker, -H, 'unix:///var/run/docker.sock', --default-ulimit, nofile=1000000:1000000]
Incorrect Usage.

NAME:
   set - set a value

USAGE:
   command set [arguments...]

```

So it turns out that it need quotation to work out
```
$ sudo ros config set user_docker.args '[docker, -d, -s, overlay, -G, docker, -H, 'unix:///var/run/docker.sock', --default-ulimit, nofile=1000000:1000000]'
```

**Comment by will-chan** [comment] 2017-01-28 00:25
Closing issue as we don't support RHEL 6 and we will track it as part of RancherOS.

**Closed by will-chan** 2017-01-28 00:25 UTC
Labels: area/agent, kind/bug
