### ISSUE TITLE
Cannot deploy an environment with k8s controller

### ISSUE THREAD

**Issue by ltagliamonte** [rancher/rancher#5290] opened 2016-06-30 00:59 UTC
I'm trying to use rancher with kubernetes,
i'm using 2 new servers on aws,one that host the UI and another as slave.
I created a new environment of type kubernetes, I added an host, the kubernetes component installation starts and never finish.
The kubelet container fails with the following error:

```
time="2016-06-30T00:56:51Z" level=fatal msg="Failed to find state.json" 
Archive:  certs.zip
  inflating: ca.pem                  
  inflating: cert.pem                
  inflating: key.pem                 
time="2016-06-30T00:57:06Z" level=fatal msg="Failed to find state.json" 
```
---

| Useful | Info |
| :-- | :-- |
| Versions | Rancher `v1.1.0-dev5` Cattle: `v0.164.1` UI: `v1.1.10` |
| Access | `Disabled` |
| Orchestration | `Kubernetes` |
| Route | `hosts.index` |

**Comment by tfiduccia** [comment] 2016-07-01 00:32
Can you upgrade to 1.1.0 and try again.  I cannot reproduce this.

**Comment by ltagliamonte** [comment] 2016-07-01 22:43
Hello @tfiduccia ,
i did use the latest tag from docker hub which points to 1.1.0 and it is still not working.
Same error on kubelet container.

**Comment by tfiduccia** [comment] 2016-07-01 22:50
Are you using a 1.11 version of docker on the host?  Because kubernetes does not yet support 1.11 and you have to make sure you have a 1.10 version.

**Comment by t5unamie** [comment] 2016-07-12 10:54
I have the same issue.

docker version
Client:
 Version:      1.10.0
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   590d5108
 Built:        Thu Feb  4 18:18:11 2016
 OS/Arch:      darwin/amd64

Server:
 Version:      1.11.2
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   b9f10c9
 Built:        Wed Jun  1 21:20:08 2016
 OS/Arch:      linux/amd64

This is the version of Rancher server I am using.

docker run -d --restart=always -p 8080:8080 rancher/server:v1.1.0

system is forever stuck on  "Starting services (8 of 9)"

This is the docker ps -a output.

docker ps -a
CONTAINER ID        IMAGE                               COMMAND                  CREATED             STATUS                      PORTS                                          NAMES
7150df5e0fe6        rancher/ingress-controller:v0.1.3   "ingress-controller -"   4 minutes ago       Up 4 minutes                                                               r-Kubernetes_rancher-ingress-controller_1
881a0d8e6cf0        rancher/k8s:v1.2.4-rancher7         "/usr/bin/entry.sh ku"   4 minutes ago       Up 4 minutes                                                               r-Kubernetes_proxy_1
ff5de2c307f8        rancher/k8s:v1.2.4-rancher7         "/usr/bin/entry.sh ku"   4 minutes ago       Exited (1) 18 seconds ago                                                  r-Kubernetes_kubelet_1
e3cfffc0616c        rancher/k8s:v1.2.4-rancher7         "/usr/bin/entry.sh ku"   4 minutes ago       Up 4 minutes                                                               r-Kubernetes_controller-manager_1
fb1f4ade8a7c        rancher/kubernetes-agent:v0.2.0     "kubernetes-agent"       4 minutes ago       Up 4 minutes                                                               r-Kubernetes_rancher-kubernetes-agent_1
ff9a2f1e05f2        rancher/kubectld:v0.2.0             "kubectld.sh"            4 minutes ago       Up 4 minutes                                                               r-Kubernetes_kubectld_1
f3e2a33b2fe4        rancher/k8s:v1.2.4-rancher7         "/usr/bin/entry.sh ku"   4 minutes ago       Up 4 minutes                                                               r-Kubernetes_scheduler_1
2e1abab6c051        rancher/k8s:v1.2.4-rancher7         "/usr/bin/entry.sh ku"   4 minutes ago       Up 4 minutes                                                               r-Kubernetes_kubernetes_1
ccb31c0df546        rancher/etcd:v2.3.6-3               "/run.sh node"           5 minutes ago       Up 5 minutes                                                               r-Kubernetes_etcd_1
3440632411a3        rancher/agent-instance:v0.8.3       "/etc/init.d/agent-in"   5 minutes ago       Up 5 minutes                0.0.0.0:500->500/udp, 0.0.0.0:4500->4500/udp   ee239413-a64a-4e3d-8c37-ccab835fbe76
ed6bee9ffaa0        busybox:latest                      "/bin/true"              5 minutes ago       Exited (0) 5 minutes ago                                                   r-Kubernetes_etcd_data_1
20024da893f5        rancher/agent:v1.0.2                "/run.sh run"            5 minutes ago       Up 5 minutes                                                               rancher-agent
1487a4e2cce3        rancher/agent:v1.0.2                "/run.sh state"          5 minutes ago       Exited (0) 5 minutes ago                                                   rancher-agent-state
5ad0522f12c1        rancher/agent:v1.0.2                "/run.sh http://192.1"   5 minutes ago       Exited (0) 5 minutes ago                                                   loving_stallman
04bd737208d5        rancher/server:v1.1.0               "/usr/bin/s6-svscan /"   7 minutes ago       Up 7 minutes                3306/tcp, 0.0.0.0:8080->8080/tcp  

Log output for container that fails to start

docker logs ff5de2c307f8
Archive:  certs.zip
  inflating: ca.pem                  
  inflating: cert.pem                
  inflating: key.pem                 
time="2016-07-12T10:46:48Z" level=fatal msg="Failed to find state.json" 
Archive:  certs.zip
  inflating: ca.pem                  
  inflating: cert.pem                
  inflating: key.pem                 
time="2016-07-12T10:49:33Z" level=fatal msg="Failed to find state.json" 
Archive:  certs.zip
  inflating: ca.pem                  
  inflating: cert.pem                
  inflating: key.pem                 
time="2016-07-12T10:51:03Z" level=fatal msg="Failed to find state.json"

**Comment by deniseschannon** [comment] 2016-07-20 21:14
@t5unamie How many hosts do you have in your setup? How big is your host?

**Comment by Shyckymn** [comment] 2016-08-17 18:22
I run into the same issue today...
Trying to install Kubernetes in Rancher environment.
The image "r-Kubernetes_kubelet_1" doesn't start.

Setting up Kubernetes
- Add at least one host
- Waiting for a host to be active
- Creating Kubernetes system stack
- Starting services (7 of 9) (loop...)

The kubelet container logs show this info:
Archive:  certs.zip
inflating: ca.pem
inflating: cert.pem
inflating: key.pem
time="2016-08-17T18:20:34Z" level=fatal msg="Failed to find state.json"

**Comment by deniseschannon** [comment] 2016-08-18 06:18
@Shyckymn What Rancher/Docker version are you using?

**Comment by Shyckymn** [comment] 2016-08-25 19:58
@deniseschannon I was trying to do that in my Windows 10 workstation, using Docker for Windows. But right now, I change my environment to Linux RHEL 7.2. I will try to do the same procedure later. Thanks for your attention.

**Comment by Tebro** [comment] 2016-09-09 06:46
I have the same issue when using docker-machine virtualbox hosts on my laptop. Have 3 hosts with 2GB RAM and 1 CPU each.

**Comment by andylmtang** [comment] 2016-09-16 05:47
I have the same issue too with docker-machine virtual box hosts

root# docker version
Client:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.7
 Git commit:   23cf638
 Built:        Thu Aug 18 22:32:50 UTC 2016
 OS/Arch:      darwin/amd64

Server:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   23cf638
 Built:        Thu Aug 18 17:52:38 2016
 OS/Arch:      linux/amd64

**Comment by tfiduccia** [comment] 2016-09-16 17:39
@tebro - what Rancher/Docker version are you using?
@andyimtang - Kubernetes does not yet support 1.12 and you have to make sure you have a 1.10 version.

**Comment by Tebro** [comment] 2016-09-16 17:42
Ah. Had the latest version of rancher but the boot2docker machines use
Docker 1.12

**Comment by tfiduccia** [comment] 2016-09-16 17:44
@Tebro - Not sure if you saw my comment to Andy, but Kubernetes has not yet verified that version.  We know for sure it works with 1.10.

**Comment by donghui** [comment] 2016-09-18 06:48
@tfiduccia I don't think #5972 Duplicate of #5290.

**The reason:**
In #5290: kubelet container fails with the following error:
time="2016-06-30T00:56:51Z" level=fatal msg="Failed to find state.json" 

But in #5972 there is no such error. and Kubernetes_rancher-ingress-controller_1 can not start normally.
Log in Kubernetes_rancher-ingress-controller_1:
time="2016-09-14T14:00:38Z" level=error msg="Health check failed: unable to reach Kubernetes. Error: &url.Error{Op:\"Get\", URL:\"http://**master**/apis/extensions/v1beta1/ingresses\", Err:(*net.OpError)(0xc8201c3720)}"
time="2016-09-14T14:00:38Z" level=error msg="Healtcheck failed for LB controller"

I think when rancher-ingress-controller_1 execute health check using above url, it is using wrong ip address of master because there is another host named **master** in my local network. When I close network between my vmware and local network, setup can complete normally.

And i have  downgraded docker to 1.10.3 and try again. it still not working.

**Comment by aemneina** [comment] 2016-09-19 18:01
@andylmtang @Tebro not sure cross host communication works using virtualbox, this might be the  issue youre facing.

@donghui your issue looks specific to there being another host resolving to 'master' in your environment. Rancher k8s maps 'master' to the kubernetes api.

**Comment by aemneina** [comment] 2016-11-04 15:51
Closing due to inactivity. Please file new issues if you come across problems.

**Closed by aemneina** 2016-11-04 15:51 UTC
Labels: area/kubernetes, kind/question
