### ISSUE TITLE
Rancher (MySQL) Database growing more than expected

### ISSUE THREAD

**Issue by jambajaar** [rancher/rancher#12261] opened 2018-03-24 01:15 UTC
**Rancher versions:**
1.6.5 +

MySQL DB has quickly grown to 13GB
Instance table for example seems to have 2M records

There seems to be some issues causing DB to bloat up

**Comment by deniseschannon** [comment] 2018-04-05 19:31
Duplicate of https://github.com/rancher/rancher/issues/7050

**Closed by deniseschannon** 2018-04-05 19:31 UTC
Labels: area/database, status/to-test
