### ISSUE TITLE
Rancher UI does not get upgraded 

### ISSUE THREAD

**Issue by dhaus97** [rancher/rancher#15981] opened 2018-10-06 12:32 UTC
**Rancher versions:**
rancher/server or rancher/rancher: v2.1.0
rancher/agent or rancher/rancher-agent: v2.1.0

**Docker version: (`docker version`,`docker info` preferred)** 
docker info
Containers: 49
 Running: 29
 Paused: 0
 Stopped: 20
Images: 21
Server Version: 17.03.2-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 4ab9917febca54791c5f071a9d1f404867857fcc
runc version: 54296cf40ad8143b62dbcaa1d90e520a2136ddfe
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.0-6-amd64
Operating System: Debian GNU/Linux 9 (stretch)
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 7.783 GiB
Name: X
ID: EHMA:A46N:OJIX:ETBV:3PNA:OBTT:ZLIX:64K4:L47W:GQ7B:H6IT:V3FT
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: No swap limit support

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
cat /etc/os-release
PRETTY_NAME="Debian GNU/Linux 9 (stretch)"
NAME="Debian GNU/Linux"
VERSION_ID="9"
VERSION="9 (stretch)"
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"

uname -r
4.9.0-6-amd64

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
Azure Virtual Machine
**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
Single Node

**Steps to Reproduce:**
Upgraded the Rancher Server with its existing data from v2.0.2 to current version v2.1.0 based on the documentation provided here: https://rancher.com/docs/rancher/v2.x/en/upgrades/upgrades/single-node-upgrade/
After finishing the upgrade, Rancher version has changed, clicking on the button in the bottom left corner leaves the User interface in an older version.

Expected:
Version of the User Interface should be the same as the server version
**Results:**
![rancherversions](https://user-images.githubusercontent.com/30733340/46571389-8a640480-c974-11e8-8513-fbd74b05dde4.PNG)

**Comment by cjellick** [comment] 2018-10-06 14:29
Ui version should be 2.0.77. We’ll take a look. If you logout and close your browser and then come back in, does it change?


On Oct 6, 2018, at 5:32 AM, dhaus97 <notifications@github.com<mailto:notifications@github.com>> wrote:


Rancher versions:
rancher/server or rancher/rancher: v2.1.0
rancher/agent or rancher/rancher-agent: v2.1.0

Docker version: (docker version,docker info preferred)
docker info
Containers: 49
Running: 29
Paused: 0
Stopped: 20
Images: 21
Server Version: 17.03.2-ce
Storage Driver: overlay2
Backing Filesystem: extfs
Supports d_type: true
Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
Volume: local
Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 4ab9917febca54791c5f071a9d1f404867857fcc
runc version: 54296cf40ad8143b62dbcaa1d90e520a2136ddfe
init version: 949e6fa
Security Options:
seccomp
Profile: default
Kernel Version: 4.9.0-6-amd64
Operating System: Debian GNU/Linux 9 (stretch)
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 7.783 GiB
Name: X
ID: EHMA:A46N:OJIX:ETBV:3PNA:OBTT:ZLIX:64K4:L47W:GQ7B:H6IT:V3FT
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
127.0.0.0/8
Live Restore Enabled: false

WARNING: No swap limit support

Operating system and kernel: (cat /etc/os-release, uname -r preferred)
cat /etc/os-release
PRETTY_NAME="Debian GNU/Linux 9 (stretch)"
NAME="Debian GNU/Linux"
VERSION_ID="9"
VERSION="9 (stretch)"
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"

uname -r
4.9.0-6-amd64

Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)
Azure Virtual Machine
Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)
Single Node

Steps to Reproduce:
Upgraded the Rancher Server with its existing data from v2.0.2 to current version v2.1.0 based on the documentation provided here: https://rancher.com/docs/rancher/v2.x/en/upgrades/upgrades/single-node-upgrade/
After finishing the upgrade, Rancher version has changed, clicking on the button in the bottom left corner leaves the User interface in an older version.

Expected:
Version of the User Interface should be the same as the server version
Results:
[rancherversions]<https://user-images.githubusercontent.com/30733340/46571389-8a640480-c974-11e8-8513-fbd74b05dde4.PNG>

**Comment by KaelBaldwin** [comment] 2018-10-06 15:38
I just had to make sure to clear my cache.

**Comment by vincent99** [comment] 2018-10-06 16:15
Likely the webserver in the server container isn't sending appropriate cache headers.

(Also the UI version should have been rolled over to 2.1.0 during the RC process...)

**Comment by loganhz** [comment] 2018-10-06 18:28
HTTP headers look good in v2.0.2 and v2.1.0

```
Accept-Ranges: bytes
Content-Length: 2641
Content-Type: text/html; charset=utf-8
Date: Sat, 06 Oct 2018 18:21:10 GMT
Last-Modified: Thu, 04 Oct 2018 18:01:45 GMT
```

I can reproduce this issue with the following steps:

1. Open the Rancher UI of `v2.0.2` before upgrade rancher server.
2. Upgrade the rancher server to `v2.1.0`
3. Go back to the Rancher UI tab and click logout
4. Login again

Now the backend is v2.1.0 but the UI is still v2.0.2

You can close the previous tab and open Rancher UI again after upgrade 
Or just refresh your bowser.

**Comment by dhaus97** [comment] 2018-10-06 19:47
User Interface version gets shown as v2.0.77 after clearing the browser cache, as said by @KaelBaldwin

**Comment by vincent99** [comment] 2018-10-07 05:37
Those headers do not look good, it should be explicit saying no-cache fit the HTML response.

**Comment by loganhz** [comment] 2018-10-10 04:57
We need to add `Cache-Control: no-cache` for HTML and `Cache-Control: max-age=31536000, public` for JS file

**Comment by loganhz** [comment] 2018-10-10 23:49
The fix will be in `v2.1.1`

As the HTML is already cached in browsers, you still need to clear the cache manually if you met this issue in Rancher `v2.1.1`.

**Comment by jiaqiluo** [comment] 2018-11-16 23:14
**Reproduction on  v2.0.2**
1. Deployed v2.0.2
2. Loaded UI
3. Upgraded to 2.1.0
4. Saw incorrect version

**Validation on master on 11/16**
1. continued to upgrade to rancher:master on 11/16
2. Saw the correct version
3. Opened network tools
4. Validated the `no-cache`, `no-store`, `must-revalidate` header is applied to HTML requests and is not using a cached version.

**Comment by jiaqiluo** [comment] 2018-12-31 20:35
**Reproduction on  v2.0.2**
1. Deployed v2.0.2
2. Loaded UI
3. Upgraded to 2.1.0
4. Saw incorrect version

**Validation on v2.1.4**
1. continued to upgrade to rancher:v2.1.4
2. Saw the correct version
3. Opened network tools
4. Validated the `Cache-Control: no-cache, no-store, must-revalidate` header was applied to HTML response headers and Rancher is not using a cached version.
5. Validated the` Cache-Control: max-age=31536000, public` header was applied for all CSS and JS files' response headers, and those files were retrieved from the Rancher server. 

It should be safe to close the ticket since the validation was passed on v2.1.4, and v2.2 should have the same behavior.

**Closed by jiaqiluo** 2018-12-31 20:35 UTC
Labels: area/server, kind/bug, status/resolved, status/to-test, team/cn, version/2.0
