### ISSUE TITLE
Pods can still hang when deleting cattle-node-cleanup job

### ISSUE THREAD

**Issue by snasovich** [rancher/rancher#37063] opened 2022-03-26 02:11 UTC
A previous fix was implemented to try to cleanup the cattle-cleanup-node jobs and pods. That fix worked in some cases, but it is still possible for the pod to get stuck in a terminating state.

A fix should be included to force delete the pods to ensure that pods get deleted, which, in turns, allows the job to be cleaned up.

Reproduction steps:
1. Create an RKE1 custom cluster with Kubernetes version v1.21.10
2. Join one node with all roles and one node with worker-only role.
3. After all nodes are active, turn off the VM. Don't delete the node.
4. Wait for the node to become unavailable in the Rancher UI.
5. Delete the node from the Rancher UI.

Result:
The node may hang and not be cleaned up. You will see the `cattle-cleanup-node` job and a pod in the downstream cluster stuck in the deleting or terminating phase.

Expected result:
The node gets cleaned up and the job and pod are deleted from the downstream cluster.

SURE-4289

**Comment by thedadams** [comment] 2022-04-01 21:03
### Root cause
The node-cleanup job completely ignored the private registry information for a cluster.

### What was fixed, or what changes have occurred
The cattle-cleanup-node job now created with private registry information similar to the cattle-cluster-agent.

### Areas or cases that should be tested
1. Create a custom RKE1 cluster with Kubernetes version v1.21.10 (I don't know if the Kubernetes version is important, but I was able to reproduce this issue with that version).
2. Provision three custom nodes: one with all roles and two with a worker-only role.
3. Once all nodes are active, turn the VM off one of the worker nodes.
4. Once this worker node is unavailable in the Rancher UI, delete the node from the Rancher UI. It should be deleted.
5. Without turning the VM off, delete the second worker-only node. It should be deleted.

### What areas could experience regressions?
Deleting nodes from custom RKE1 clusters.

### Are the repro steps accurate/minimal?
Yes

**Comment by Josh-Diamond** [comment] 2022-04-07 23:02
Ticket #37063 - Test Results - [Duplicate of [#35148](https://github.com/rancher/rancher/issues/35148)]

With Docker on single-node instance:

Reproduction Failure on rancher `v2.6-9ef92c2168bd91ce6b05734731d9c2c21c42a5f4-head`:
1. Unable to reproduce; I have experienced this error first hand and am able to ensure quality verification provided below


Verified on rancher `v2.6-6955cebc208a925e3e6f42a3a7f5d24dcd7d2585-head`:
1. Fresh install of rancher `v2.6-head`
2. Provision an RKE1 Custom downstream cluster, k8s `v1.21.10`, with 3 nodes; One with all 3 roles [etcd, cp, wkr], and two as dedicated worker nodes
3. Once cluster is `Active` and stable, turn off VM of one of the dedicated worker nodes
4. Once the node becomes `Unavailable`, delete it from the rancher UI - [SUCCESSFULLY_DELETED]
5. With both remaining nodes in an `Active` state, delete the remaining dedicated worker node - [SUCCESSFULLY_DELETED]
6. Verified - All steps are executed successfully; No nodes caught in "hang" state and unable to be removed

**Closed by Josh-Diamond** 2022-04-07 23:02 UTC
Labels: internal, area/custom-cluster, [zube]: To Test, QA/XS, feature/provisioned-rke1, team/area2
