### ISSUE TITLE
[Feature Request ] Access controlling per stack within env

### ISSUE THREAD

**Issue by nathanxu** [rancher/rancher#5310] opened 2016-07-01 09:24 UTC
Rancher supports to assign the permission per environment while it couples host resource and permission controlling. We met several real cases that people want to share host resources within environment and control the operation against stacks (view, change or delete stack). For these users, It's not acceptable to create a set of environments for purpose of stack access controlling while can't share limited host resources.

**Comment by deniseschannon** [comment] 2016-07-01 15:53
Duplicate of #5309

**Closed by deniseschannon** 2016-07-01 15:53 UTC
