### ISSUE TITLE
rancher-gatekeeper chart sets --exempt-namespace to wrong Namespace on gatekeeper-controller-manager

### ISSUE THREAD

**Issue by axeal** [rancher/rancher#32157] opened 2021-04-15 12:36 UTC
**What kind of request is this (question/bug/enhancement/feature request):**

Bug

**Steps to reproduce (least amount of steps as possible):**

1. Deploy the rancher-gatekeeper 3.3.000 chart in a Rancher v2.5.7 instance

**Result:**

Observe the `--exempt-namespace` arg on the `gatekeeper-controller-manager` Deployment is set to `gatekeeper-system` where the gatekeeper chart is actually installed in the namespace `cattle-gatekeeper-system`.

**Other details that may be helpful:**

The hardcoded `gatekeeper-system` value (https://github.com/rancher/charts/blob/release-v2.5/charts/rancher-gatekeeper/rancher-gatekeeper/3.3.000/templates/gatekeeper-controller-manager-deployment.yaml#L57) appears to originate from the upstream v3.3.0 chart (https://github.com/open-policy-agent/gatekeeper/blob/v3.3.0/charts/gatekeeper/templates/gatekeeper-controller-manager-deployment.yaml#L57), but has subsequently been updated upstream to `{{ .Release.Namespace }}` (https://github.com/open-policy-agent/gatekeeper/blob/v3.4.0/charts/gatekeeper/templates/gatekeeper-controller-manager-deployment.yaml#L49).

In addition to setting the default `--exempt-namespace` dynamically and adding the `admission.gatekeeper.sh/ignore` label to the Namespace (https://github.com/open-policy-agent/gatekeeper/blob/v3.4.0/charts/gatekeeper/templates/namespace-post-install.yaml), it would be helpful to allow a templated list of additional `--exempt-namespace`s to permit user exemption of other Namespaces, such as kube-system (https://open-policy-agent.github.io/gatekeeper/website/docs/exempt-namespaces/).

**Environment information**
- Rancher v2.5.7 / rancher-gatekeeper 3.3.000

**Comment by samkulkarni20** [comment] 2022-01-27 12:45
The issue is with 2.5 chart. This release line is EOM as of v2.5.12 & the only fixes to follow will be the security patches and/or high severity bugs. Closing this issue since it's no longer required.

**Closed by samkulkarni20** 2022-01-27 12:45 UTC
Labels: kind/bug, internal, [zube]: Review, team/area3, feature/charts-opa-gatekeeper, team/infracloud
