### ISSUE TITLE
Rancher compose variables for external_links do not work

### ISSUE THREAD

**Issue by Verikon** [rancher/rancher#3951] opened 2016-03-13 14:11 UTC
Rancher Version: v0.59.1
Docker Version: 1.10.2, build c3959b1
OS: Ubuntu 14.04

Steps to Reproduce: 
- Produce a private catalog , and item with the compose files below.
- Add a service (Mongo in this example)
- Deploy from catalog

Results: 
- answers.txt (in the catalog preview) shows the correctly selected service in its external representation; eg: (Stackname/Mongo-Service).
- the resulting container's rancher-compose.yml has excluded/removed the external links parameters in the docker-compose.yml file.
- Adding a linked container via rancher's UI and restarting the container works.

Expected: 
- be able to ping "mongo" from within the container - but cannot.

docker-compose.yml
```
asset-service:
  image: redis
  external_links:
    - ${mongo_service}:mongo
```

rancher-compose.yml
```
.catalog:
  name: "asset-service"
  version: "0.1"
  description: "Asset Service (STOMP)"
  questions:
    - variable: "mongo_service"
      type: "service"
      label: "MongoDB"
      description: "Choose the Mongo database to connect the asset service to"
```

**Comment by deniseschannon** [comment] 2016-03-13 18:29
Duplicate of https://github.com/rancher/rancher/issues/3929

**Closed by deniseschannon** 2016-03-13 18:29 UTC
