### ISSUE TITLE
Certificate error when attempting to Add a Catalog in v2.3.0-rc9

### ISSUE THREAD

**Issue by mattmattox** [rancher/rancher#23231] opened 2019-10-04 18:09 UTC
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
- Deploy Rancher v2.3.0-rc9

**Result:**
x509 certificate signed by unknown authority error for all catalogs minus git.rancher.io.
![image](https://user-images.githubusercontent.com/17145893/66229550-b315fb80-e6a7-11e9-9fe6-7b5de600403c.png)

**Other details that may be helpful:**
If you curl the catalog from inside Rancher, it works fine with not cert error.
Also, this environment is using an proxy. 

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): v2.3.0-rc9
- Installation option (single install/HA): HA

**Comment by dsargent3220** [comment] 2019-10-07 15:00
I can confirm that this is still having issues in rc11.  I upgraded the cluster and Kubernetes.
I also removed the helm catalog and readded it, same errors as above.

**Comment by dsargent3220** [comment] 2019-10-16 16:08
This may be because we are behind a proxy, however, we have the same basic setup as our previous Rancher instances so something must be new that is causing this behavior.

**Comment by dsargent3220** [comment] 2019-10-16 20:09
This appears to be fixed in 2.3.1-rc4

**Comment by dsargent3220** [comment] 2019-10-22 18:45
OK, this is really frustrating.  I'm finishing up testing on our new cluster configs and deleted the current test cluster and readded it and now I'm getting the cert errors again.  This is on 2.3.1

**Comment by bmdepesa** [comment] 2019-10-23 20:43
I am unable to reproduce so far in v2.3.1

* HA install (fresh install v2.3.1)
* Rancher-generated self-signed certs
* Rancher behind proxy (Squid proxy)
* Create a cluster (1.15.5)
* Enable global Helm / Helm Incubator catalogs
  * Sync succeeded
* Add a few custom catalogs to global
  * Sync succeeded
* Add some project catalogs
  * Sync succeeded

I did not see any x509 errors at any point. 

@dsargent3220 are there any other details you can provide on your setup that might help in reproducing?

**Comment by dsargent3220** [comment] 2019-10-23 21:03
Both of the clusters I see this on were upgrades from 2.2.8.  Beyond that?  Not that I can think of
I'm free until 4 pm pacific if you want to do a Zoom.

**Comment by bmdepesa** [comment] 2019-10-23 21:08
Can you provide your proxy config (with sensitive info removed)?  

I will try in an upgraded setup as well on the next pass.

**Comment by dsargent3220** [comment] 2019-10-23 21:16
Sure, here you go.
```echo "Adding proxies to /etc/environment"
http_proxy="http://wall.ad.selinc.com:8080/"
ftp_proxy="http://wall.ad.selinc.com:2121/"
no_proxy="localhost,127.0.0.1,127.0.0.0,127.0.0.*,0.0.0.0,localaddress,ad.selinc.com,10.0.0.0/8,10.,10.*"

# Export proxy settings for immediate use.
export http_proxy=$http_proxy
export https_proxy=$http_proxy
export HTTP_PROXY=$http_proxy
export HTTPS_PROXY=$http_proxy
export ftp_proxy=$ftp_proxy
export FTP_PROXY=$ftp_proxy
export no_proxy=$no_proxy
export no_proxy=$no_proxy

# Add proxy to /etc/environment so these are loaded with each startup
tee /etc/environment << eof
http_proxy="$http_proxy"
https_proxy="$http_proxy"
HTTP_PROXY="$http_proxy"
HTTPS_PROXY="$http_proxy"
ftp_proxy="$ftp_proxy"
FTP_PROXY="$ftp_proxy"
no_proxy="$no_proxy"
NO_PROXY="$no_proxy"
LANG="en_US.UTF-8"
LANGUAGE="en_US.UTF-8"
LC_COLLATE="C"
LC_CTYPE="en_US.UTF-8"
KACE_SERVER="fpul-patch.ad.selinc.com"
eof

# Includes the /etc/environment file and runs the exports so the env variables become active immediately and can be used below.
# shellcheck disable=SC1091
source /etc/environment```
That is run as part of our prep script for every CentOS node we build.

**Comment by bmdepesa** [comment] 2019-10-23 21:22
Are you able to provide the configuration for the proxy itself? Is it possible the proxy configuration changed recently?

**Comment by dsargent3220** [comment] 2019-10-23 21:49
Oh, sorry.  I doubt that is it as our older clusters work just fine with the same proxy settings.  I'd have to check with our security department but don't have high hopes there.  We use Forcepoint and it is a rather complex beast
And from my support case:
I seem to be able to curl the endpoints fine from both the machine Rancher is running on and from within the Rancher container.
The traffic is flowing through our proxy as expected and I'm getting back S3 bucket information.
The output is the same from both the server and the container.

Here is the response from within the Rancher container

```root@4dbf7718af9c:/var/lib/rancher# curl -vvv https://charts.rook.io/release/
*   Trying 10.100.0.240...
* TCP_NODELAY set
* Connected to wall.ad.selinc.com (10.100.0.240) port 8080 (#0)
* allocate connect buffer!
* Establish HTTP proxy tunnel to charts.rook.io:443
> CONNECT charts.rook.io:443 HTTP/1.1
> Host: charts.rook.io:443
> User-Agent: curl/7.58.0
> Proxy-Connection: Keep-Alive
>
< HTTP/1.1 200 Connection established
< Date: Fri, 04 Oct 2019 17:58:13 GMT
< Proxy-Connection: Keep-Alive
< Via: 1.1 wall - Websense appliance
<
* Proxy replied 200 to CONNECT request
* CONNECT phase completed!
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/certs/ca-certificates.crt
  CApath: /etc/rancher/ssl
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* CONNECT phase completed!
* CONNECT phase completed!
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
* TLSv1.2 (IN), TLS handshake, Server finished (14):
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
* TLSv1.2 (OUT), TLS change cipher, Client hello (1):
* TLSv1.2 (OUT), TLS handshake, Finished (20):
* TLSv1.2 (IN), TLS handshake, Finished (20):
* SSL connection using TLSv1.2 / ECDHE-RSA-AES128-GCM-SHA256
* ALPN, server accepted to use h2
* Server certificate:
*  subject: CN=*.rook.io
*  start date: Dec 31 00:00:00 2018 GMT
*  expire date: Jan 31 12:00:00 2020 GMT
*  subjectAltName: host "charts.rook.io" matched cert's "*.rook.io"
*  issuer: C=US; O=Amazon; OU=Server CA 1B; CN=Amazon
*  SSL certificate verify ok.
* Using HTTP2, server supports multi-use
* Connection state changed (HTTP/2 confirmed)
* Copying HTTP/2 data in stream buffer to connection buffer after upgrade: len=0
* Using Stream ID: 1 (easy handle 0x5636e62aa580)
> GET /release/ HTTP/2
> Host: charts.rook.io
> User-Agent: curl/7.58.0
> Accept: */*
>
* Connection state changed (MAX_CONCURRENT_STREAMS updated)!
< HTTP/2 404
< content-type: text/html
< content-length: 639
< last-modified: Mon, 03 Dec 2018 04:55:01 GMT
< etag: "cf660f422731cbbe06a1bc2231bedc9b"
< x-amz-error-code: NoSuchKey
< x-amz-error-message: The specified key does not exist.
< x-amz-error-detail-key: release/index.html
< date: Fri, 04 Oct 2019 17:58:13 GMT
< server: AmazonS3
< x-cache: Error from cloudfront
< via: 1.1 536063cb28bfc05fcb7a78183dd89b73.cloudfront.net (CloudFront)
< x-amz-cf-pop: SEA19-C1
< x-amz-cf-id: me_GFTAGgB0C2XIA7NjbKGqD-r6ZQ5j8qZdRfsfoU0ITkwB3O6DxnQ==
<
<!DOCTYPE html>
<html>
<head>
  <title>S3 Bucket Listing Generator</title>
</head>
<body>
  <div id="navigation"></div>
  <div id="listing"></div>

<script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
<script type="text/javascript">
  var S3BL_IGNORE_PATH = false;
  var BUCKET_URL = 'https://s3.amazonaws.com/rook.charts';
  var BUCKET_WEBSITE_URL = "https://charts.rook.io";
  var EXCLUDE_FILE = 'index.html';
  var AUTO_TITLE = true;
</script>
<script type="text/javascript" src="https://rawgit.com/rufuspollock/s3-bucket-listing/gh-pages/list.js"></script>
</body>
</html>

* Connection #0 to host wall.ad.selinc.com left intact
```

Here is the response from the host
```[root@lpul-ranchertest ~]# curl -vvv https://charts.rook.io/release/
* About to connect() to proxy wall.ad.selinc.com port 8080 (#0)
*   Trying 10.100.0.240...
* Connected to wall.ad.selinc.com (10.100.0.240) port 8080 (#0)
* Establish HTTP proxy tunnel to charts.rook.io:443
> CONNECT charts.rook.io:443 HTTP/1.1
> Host: charts.rook.io:443
> User-Agent: curl/7.29.0
> Proxy-Connection: Keep-Alive
>
< HTTP/1.1 200 Connection established
< Date: Fri, 04 Oct 2019 17:59:23 GMT
< Proxy-Connection: Keep-Alive
< Via: 1.1 wall - Websense appliance
<
* Proxy replied OK to CONNECT request
* Initializing NSS with certpath: sql:/etc/pki/nssdb
*   CAfile: /etc/pki/tls/certs/ca-bundle.crt
  CApath: none
* SSL connection using TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
* Server certificate:
*       subject: CN=*.rook.io
*       start date: Dec 31 00:00:00 2018 GMT
*       expire date: Jan 31 12:00:00 2020 GMT
*       common name: *.rook.io
*       issuer: CN=Amazon,OU=Server CA 1B,O=Amazon,C=US
> GET /release/ HTTP/1.1
> User-Agent: curl/7.29.0
> Host: charts.rook.io
> Accept: */*
>
< HTTP/1.1 404 Not Found
< Content-Type: text/html
< Content-Length: 639
< Connection: keep-alive
< Last-Modified: Mon, 03 Dec 2018 04:55:01 GMT
< ETag: "cf660f422731cbbe06a1bc2231bedc9b"
< x-amz-error-code: NoSuchKey
< x-amz-error-message: The specified key does not exist.
< x-amz-error-detail-Key: release/index.html
< Date: Fri, 04 Oct 2019 17:58:13 GMT
< Server: AmazonS3
< X-Cache: Error from cloudfront
< Via: 1.1 fda3b2797d2719576f6b916583a28e52.cloudfront.net (CloudFront)
< X-Amz-Cf-Pop: SEA19-C2
< X-Amz-Cf-Id: Ei8qjF0KWv-o567DfuFLFI4Y2c1iNqBp8VNaPIVdFiqr4NKLSaa8yw==
<
<!DOCTYPE html>
<html>
<head>
  <title>S3 Bucket Listing Generator</title>
</head>
<body>
  <div id="navigation"></div>
  <div id="listing"></div>

<script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
<script type="text/javascript">
  var S3BL_IGNORE_PATH = false;
  var BUCKET_URL = 'https://s3.amazonaws.com/rook.charts';
  var BUCKET_WEBSITE_URL = "https://charts.rook.io";
  var EXCLUDE_FILE = 'index.html';
  var AUTO_TITLE = true;
</script>
<script type="text/javascript" src="https://rawgit.com/rufuspollock/s3-bucket-listing/gh-pages/list.js"></script>
</body>
</html>

* Connection #0 to host wall.ad.selinc.com left intact

And here is the response from one of the hosts we know works

[root@lpul-k8sprdwrk1 ~]# curl -vvv https://charts.rook.io/release/
* About to connect() to proxy wall.ad.selinc.com port 8080 (#0)
*   Trying 10.100.0.240...
* Connected to wall.ad.selinc.com (10.100.0.240) port 8080 (#0)
* Establish HTTP proxy tunnel to charts.rook.io:443
> CONNECT charts.rook.io:443 HTTP/1.1
> Host: charts.rook.io:443
> User-Agent: curl/7.29.0
> Proxy-Connection: Keep-Alive
>
< HTTP/1.1 200 Connection established
< Date: Fri, 04 Oct 2019 18:00:22 GMT
< Proxy-Connection: Keep-Alive
< Via: 1.1 wall - Websense appliance
<
* Proxy replied OK to CONNECT request
* Initializing NSS with certpath: sql:/etc/pki/nssdb
*   CAfile: /etc/pki/tls/certs/ca-bundle.crt
  CApath: none
* SSL connection using TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
* Server certificate:
*       subject: CN=*.rook.io
*       start date: Dec 31 00:00:00 2018 GMT
*       expire date: Jan 31 12:00:00 2020 GMT
*       common name: *.rook.io
*       issuer: CN=Amazon,OU=Server CA 1B,O=Amazon,C=US
> GET /release/ HTTP/1.1
> User-Agent: curl/7.29.0
> Host: charts.rook.io
> Accept: */*
>
< HTTP/1.1 404 Not Found
< Content-Type: text/html
< Content-Length: 639
< Connection: keep-alive
< Last-Modified: Mon, 03 Dec 2018 04:55:01 GMT
< ETag: "cf660f422731cbbe06a1bc2231bedc9b"
< x-amz-error-code: NoSuchKey
< x-amz-error-message: The specified key does not exist.
< x-amz-error-detail-Key: release/index.html
< Date: Fri, 04 Oct 2019 17:58:13 GMT
< Server: AmazonS3
< X-Cache: Error from cloudfront
< Via: 1.1 760139201585481b26f947c5f776103a.cloudfront.net (CloudFront)
< X-Amz-Cf-Pop: SEA19-C2
< X-Amz-Cf-Id: gmzYzLdmV_1opsIrPUn5hEkHAV3jZJ4Xf-Fsq59l3EvyL2zAHeX0Pw==
<
<!DOCTYPE html>
<html>
<head>
  <title>S3 Bucket Listing Generator</title>
</head>
<body>
  <div id="navigation"></div>
  <div id="listing"></div>

<script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
<script type="text/javascript">
  var S3BL_IGNORE_PATH = false;
  var BUCKET_URL = 'https://s3.amazonaws.com/rook.charts';
  var BUCKET_WEBSITE_URL = "https://charts.rook.io";
  var EXCLUDE_FILE = 'index.html';
  var AUTO_TITLE = true;
</script>
<script type="text/javascript" src="https://rawgit.com/rufuspollock/s3-bucket-listing/gh-pages/list.js"></script>
</body>
</html>

* Connection #0 to host wall.ad.selinc.com left intact```

**Comment by alena1108** [comment] 2019-11-06 18:01
@sangeethah the issue you are seeing, is diff. That's a regression introduced by initial fix. You can reproduce it by simply creating a new deployment with the hostport from the UI. I'll work on the fix

**Comment by sowmyav27** [comment] 2019-12-04 00:10
**Verified on `v2.3-head` commit id: `430dd0bb3`**
Steps:

**Comment by sowmyav27** [comment] 2019-12-05 20:04
Closing the issues with the above validations.

**Closed by sowmyav27** 2019-12-05 20:04 UTC
Labels: [zube]: To Test, internal, kind/bug, team/az
