### ISSUE TITLE
[2.6] Cluster stuck waiting for cluster-agent on docker install rancher behind ngrok

### ISSUE THREAD

**Issue by kinarashah** [rancher/rancher#34015] opened 2021-08-06 17:12 UTC
Steps to reproduce:
- Run docker rancher container behind ngrok. (master-head or v2.6-head) 
- Add a RKE2 cluster. 
- Kube components come up and are running, but cluster is in "Waiting for cluster-agent" 
- Error from rancher logs: 
```
2021/08/06 17:01:41 [INFO] Failed to find providerID for selector rke.cattle.io/machine=64ff49b3-6cbe-4dce-8c3e-9ff0a4ff5d41 in cluster fleet-default/kinara-do-node, machine kinara-do-node-pool1-547ff8b89c-wfsf2: Get "https://ff073ca2ccf1.ngrok.io/k8s/clusters/c-m-585de23a/api/v1/nodes?labelSelector=rke.cattle.io%!F(MISSING)machine%!D(MISSING)64ff49b3-6cbe-4dce-8c3e-9ff0a4ff5d41": x509: certificate signed by unknown authority
```

Refer to https://github.com/rancher/rancher/issues/33878#issuecomment-893603177 for the root cause.

**Comment by claudioser** [comment] 2021-08-13 10:15
I can reproduce error  trying to provision on AWS with rancher 2.6 install on Azure  RKE1 Cluster

**Comment by Oats87** [comment] 2021-08-13 19:25
> I can reproduce error trying to provision RKE2 on AWS with Rancher 2.6 install on Azure RKE1 Cluster - build version - rancherImageTag=master-c58f95221d76c6e6a32c89426b300f8afd2ab69a-head
> 
> extract of log:
> 
> ```
> 2021/08/13 10:05:18 [INFO] Failed to find providerID for selector rke.cattle.io/machine=aa6d7bc3-0ae3-4936-acab-7a003311e6d4 in cluster fleet-default/rke2awscentral, machine rke2awscentral-po │
> │ ol1-8c64fd78b-hsfcd: {"Code":{"Code":"Forbidden","Status":403},"Message":"clusters.management.cattle.io \"c-m-1db6b728\" is forbidden: User \"u-pm63ybmili\" cannot get resource \"clusters\" i │
> │ n API group \"management.cattle.io\" at the cluster scope","Cause":null,"FieldName":""} (get nodes)
> ```

The 403 is a transient error that will eventually stop being reported once RBAC is reconciled.

**Comment by aiyengar2** [comment] 2021-08-17 01:53
Available to test in Rancher 2.6.0-rc3.

#### Steps to reproduce
- Provision a node and open two SSH sessions in it
- In the first session:
  - install Docker on it via `curl https://releases.rancher.com/install-docker/20.10.sh | sh`
  - Install ngrok on it: `sudo apt install unzip; curl -o ngrok.zip https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-linux-amd64.zip; unzip ngrok.zip; rm ngrok.zip; mv ngrok /usr/bin/ngrok; chmod +x /usr/bin/ngrok`
  - Run `ngrok http 80`
- In the second SSH session, run the following command to start Rancher
```
# RANCHER_VERSION=v2.6.0-rc2
RANCHER_VERSION=v2.6.0-rc3

docker run -d --restart=unless-stopped \
  -p 80:80 -p 443:443 \
  --privileged \
  rancher/rancher:${RANCHER_VERSION}
```
- Access Rancher via ngrok and set the server-url to the ngrok URL
- Deploy a RKE2 cluster
- View Rancher logs

### 2.6.0-rc2

Same error was reproduced, as indicated in the ticket. Cluster does not finish provisioning.
```
2021/08/17 01:31:55 [INFO] Failed to find providerID for selector rke.cattle.io/machine=892d37bf-a0ba-45ed-b6a5-e5fb7164a6b0 in cluster fleet-default/arvind-do-rancher260rc2, machine arvind-do-rancher260rc2-all-6bb64c66fc-g8khp: Get "https://2443cad48194.ngrok.io/k8s/clusters/c-m-d36e4ddb/api/v1/nodes?labelSelector=rke.cattle.io%!F(MISSING)machine%!D(MISSING)892d37bf-a0ba-45ed-b6a5-e5fb7164a6b0": x509: certificate signed by unknown authority
2021/08/17 01:31:56 [INFO] Failed to find providerID for selector rke.cattle.io/machine=338b6937-8980-4675-a95e-a66c0b8ab75f in cluster fleet-default/arvind-do-rancher260rc2, machine arvind-do-rancher260rc2-all-6bb64c66fc-2mx9b: Get "https://2443cad48194.ngrok.io/k8s/clusters/c-m-d36e4ddb/api/v1/nodes?labelSelector=rke.cattle.io%!F(MISSING)machine%!D(MISSING)338b6937-8980-4675-a95e-a66c0b8ab75f": x509: certificate signed by unknown authority
2021/08/17 01:31:56 [INFO] Handling backend connection request [c-m-d36e4ddb]
2021/08/17 01:32:03 [INFO] Failed to find providerID for selector rke.cattle.io/machine=228f5783-17ea-4971-ac0c-cc5d392bdac7 in cluster fleet-default/arvind-do-rancher260rc2, machine arvind-do-rancher260rc2-all-6bb64c66fc-rxk8k: Get "https://2443cad48194.ngrok.io/k8s/clusters/c-m-d36e4ddb/api/v1/nodes?labelSelector=rke.cattle.io%!F(MISSING)machine%!D(MISSING)228f5783-17ea-4971-ac0c-cc5d392bdac7": x509: certificate signed by unknown authority
2021/08/17 01:32:07 [INFO] Handling backend connection request [c-m-d36e4ddb]
2021/08/17 01:32:10 [INFO] error in remotedialer server [400]: websocket: close 1006 (abnormal closure): unexpected EOF
2021/08/17 01:32:10 [INFO] error in remotedialer server [400]: websocket: close 1006 (abnormal closure): unexpected EOF
2021/08/17 01:32:10 [INFO] error in remotedialer server [400]: websocket: close 1006 (abnormal closure): unexpected EOF
2021/08/17 01:32:10 [INFO] Failed to find providerID for selector rke.cattle.io/machine=892d37bf-a0ba-45ed-b6a5-e5fb7164a6b0 in cluster fleet-default/arvind-do-rancher260rc2, machine arvind-do-rancher260rc2-all-6bb64c66fc-g8khp: Get "https://2443cad48194.ngrok.io/k8s/clusters/c-m-d36e4ddb/api/v1/nodes?labelSelector=rke.cattle.io%!F(MISSING)machine%!D(MISSING)892d37bf-a0ba-45ed-b6a5-e5fb7164a6b0": x509: certificate signed by unknown authority
2021/08/17 01:32:11 [INFO] Failed to find providerID for selector rke.cattle.io/machine=338b6937-8980-4675-a95e-a66c0b8ab75f in cluster fleet-default/arvind-do-rancher260rc2, machine arvind-do-rancher260rc2-all-6bb64c66fc-2mx9b: Get "https://2443cad48194.ngrok.io/k8s/clusters/c-m-d36e4ddb/api/v1/nodes?labelSelector=rke.cattle.io%!F(MISSING)machine%!D(MISSING)338b6937-8980-4675-a95e-a66c0b8ab75f": x509: certificate signed by unknown authority
```

### 2.6.0-rc3

Saw this weird error on my browser that says I cannot use ngrok due to too many open connections on trying to log into Rancher:

```
Too many connections! The tunnel session 'ts_1wpn8hEf7BIUXQZ48oztp8ZsBlM' has violated the rate-limit policy of 20 connections per minute by initiating 32 connections in the last 60 seconds. Please decrease your inbound connection volume or upgrade to a paid plan for additional capacity.

The error encountered was: ERR_NGROK_702
```

Also saw the following logs and the cluster did not finish provisioning.
```
2021/08/17 01:51:23 [INFO] Failed to find providerID for selector rke.cattle.io/machine=101b92d8-1a79-4380-9e8b-6f548b675b61 in cluster fleet-default/arvind-rancher260rc3, machine arvind-rancher260rc3-all-65f8cdbc4-w5nxj: {"Code":{"Code":"Forbidden","Status":403},"Message":"clusters.management.cattle.io \"c-m-5c8rrwk2\" is forbidden: User \"u-oxzb3trxyk\" cannot get resource \"clusters\" in API group \"management.cattle.io\" at the cluster scope","Cause":null,"FieldName":""} (get nodes)
2021/08/17 01:51:24 [INFO] Handling backend connection request [c-m-5c8rrwk2]
2021/08/17 01:51:26 [INFO] Failed to find providerID for selector rke.cattle.io/machine=c13ae36d-5273-4fbd-ae4f-0bbb60562e40 in cluster fleet-default/arvind-rancher260rc3, machine arvind-rancher260rc3-all-65f8cdbc4-99jx7: {"Code":{"Code":"Forbidden","Status":403},"Message":"clusters.management.cattle.io \"c-m-5c8rrwk2\" is forbidden: User \"u-oxzb3trxyk\" cannot get resource \"clusters\" in API group \"management.cattle.io\" at the cluster scope","Cause":null,"FieldName":""} (get nodes)
2021/08/17 01:51:32 [INFO] Failed to find providerID for selector rke.cattle.io/machine=620c2555-4542-458b-827a-c027e116062e in cluster fleet-default/arvind-rancher260rc3, machine arvind-rancher260rc3-all-65f8cdbc4-djfxs: {"Code":{"Code":"Forbidden","Status":403},"Message":"clusters.management.cattle.io \"c-m-5c8rrwk2\" is forbidden: User \"u-oxzb3trxyk\" cannot get resource \"clusters\" in API group \"management.cattle.io\" at the cluster scope","Cause":null,"FieldName":""} (get nodes)
2021/08/17 01:51:34 [INFO] Handling backend connection request [c-m-5c8rrwk2]
2021/08/17 01:51:38 [INFO] Failed to find providerID for selector rke.cattle.io/machine=101b92d8-1a79-4380-9e8b-6f548b675b61 in cluster fleet-default/arvind-rancher260rc3, machine arvind-rancher260rc3-all-65f8cdbc4-w5nxj: {"Code":{"Code":"Forbidden","Status":403},"Message":"clusters.management.cattle.io \"c-m-5c8rrwk2\" is forbidden: User \"u-oxzb3trxyk\" cannot get resource \"clusters\" in API group \"management.cattle.io\" at the cluster scope","Cause":null,"FieldName":""} (get nodes)
2021/08/17 01:51:41 [INFO] Failed to find providerID for selector rke.cattle.io/machine=c13ae36d-5273-4fbd-ae4f-0bbb60562e40 in cluster fleet-default/arvind-rancher260rc3, machine arvind-rancher260rc3-all-65f8cdbc4-99jx7: {"Code":{"Code":"Forbidden","Status":403},"Message":"clusters.management.cattle.io \"c-m-5c8rrwk2\" is forbidden: User \"u-oxzb3trxyk\" cannot get resource \"clusters\" in API group \"management.cattle.io\" at the cluster scope","Cause":null,"FieldName":""} (get nodes)
2021/08/17 01:51:44 [INFO] Handling backend connection request [c-m-5c8rrwk2]
2021/08/17 01:51:47 [INFO] Failed to find providerID for selector rke.cattle.io/machine=620c2555-4542-458b-827a-c027e116062e in cluster fleet-default/arvind-rancher260rc3, machine arvind-rancher260rc3-all-65f8cdbc4-djfxs: {"Code":{"Code":"Forbidden","Status":403},"Message":"clusters.management.cattle.io \"c-m-5c8rrwk2\" is forbidden: User \"u-oxzb3trxyk\" cannot get resource \"clusters\" in API group \"management.cattle.io\" at the cluster scope","Cause":null,"FieldName":""} (get nodes)
2021/08/17 01:51:48 [INFO] error in remotedialer server [400]: websocket: close 1006 (abnormal closure): unexpected EOF
2021/08/17 01:51:53 [INFO] Failed to find providerID for selector rke.cattle.io/machine=101b92d8-1a79-4380-9e8b-6f548b675b61 in cluster fleet-default/arvind-rancher260rc3, machine arvind-rancher260rc3-all-65f8cdbc4-w5nxj: {"Code":{"Code":"Forbidden","Status":403},"Message":"clusters.management.cattle.io \"c-m-5c8rrwk2\" is forbidden: User \"u-oxzb3trxyk\" cannot get resource \"clusters\" in API group \"management.cattle.io\" at the cluster scope","Cause":null,"FieldName":""} (get nodes)
```

**Comment by aiyengar2** [comment] 2021-08-17 01:53
@Oats87 any clue why I'm seeing these errors? Are they due to ngrok or due to some missing permissions?

Reopening...

**Comment by rawmind0** [comment] 2021-08-17 11:56
@aiyengar2 , my 2 cents on this:
* ngrok `Too many connections!` error may be normal due to community version has  this limitation
* as @Oats87  commented, `The 403 is a transient error that will eventually stop being reported once RBAC is reconciled.`
* `x509: certificate signed by unknown authority`: This is happening due to ngrok ssl certs are being used instead of rancher ca. It seems that the rancher docker image doesn't trust ngrok (letsencrypt) ca certificates. 

From rancher server/agent dockers: 
* `curl https://fb37e30c83f8.ngrok.io` is getting `curl: (60) SSL certificate problem: unable to get local issuer certificate` . 
* using ngrok tls chain on the curl call, results ok, `curl https://fb37e30c83f8.ngrok.io --cacert ngrok.pem`

**Comment by aiyengar2** [comment] 2021-08-17 18:32
@rawmind0 re: 

> ngrok Too many connections! error may be normal due to community version has this limitation

The fact that it occurs only in 2.6.0-rc3 and not in 2.6.0-rc2 makes me think that is a regression, although probably unrelated to this issue. I have opened a new issue to track in https://github.com/rancher/rancher/issues/34280.

> as @Oats87 commented, The 403 is a transient error that will eventually stop being reported once RBAC is reconciled.

Trying to reproduce for a bit longer to see if it eventually disappears.

**Comment by aiyengar2** [comment] 2021-08-17 19:10
Hmm I see the same error happening in the cluster when trying to provision an RKE2 cluster for >20 minutes:

```
2021-08-17 19:02:57.936553 I | mvcc: store.index: compact 9415
2021-08-17 19:02:57.973810 I | mvcc: finished scheduled compaction at 9415 (took 35.130328ms)
2021/08/17 19:02:59 [INFO] Handling backend connection request [c-m-s2ztvcjw]
2021/08/17 19:03:05 [INFO] error in remotedialer server [400]: websocket: close 1006 (abnormal closure): unexpected EOF
2021/08/17 19:03:05 [INFO] error in remotedialer server [400]: websocket: close 1006 (abnormal closure): unexpected EOF
2021/08/17 19:03:08 [INFO] error in remotedialer server [400]: read tcp 172.17.0.2:80->172.17.0.1:43428: i/o timeout
2021/08/17 19:03:08 [INFO] Failed to find providerID for selector rke.cattle.io/machine=c69e993f-dc25-431c-aed7-9cc01b2448a7 in cluster fleet-default/arvind-rke2-ngrok, machine arvind-rke2-ngrok-all-7b89f54595-x6rmb: {"Code":{"Code":"Forbidden","Status":403},"Message":"clusters.management.cattle.io \"c-m-s2ztvcjw\" is forbidden: User \"u-4pizqrctqn\" cannot get resource \"clusters\" in API group \"management.cattle.io\" at the cluster scope","Cause":null,"FieldName":""} (get nodes)
2021/08/17 19:03:08 [INFO] Failed to find providerID for selector rke.cattle.io/machine=1e2a1989-c0c8-49fb-ad4b-eb5a460bda1f in cluster fleet-default/arvind-rke2-ngrok, machine arvind-rke2-ngrok-all-7b89f54595-d9lg4: {"Code":{"Code":"Forbidden","Status":403},"Message":"clusters.management.cattle.io \"c-m-s2ztvcjw\" is forbidden: User \"u-4pizqrctqn\" cannot get resource \"clusters\" in API group \"management.cattle.io\" at the cluster scope","Cause":null,"FieldName":""} (get nodes)
2021/08/17 19:03:10 [INFO] Handling backend connection request [c-m-s2ztvcjw]
2021/08/17 19:03:11 [INFO] Failed to find providerID for selector rke.cattle.io/machine=29d13fb4-accc-4f6d-aad8-d9979661a7b1 in cluster fleet-default/arvind-rke2-ngrok, machine arvind-rke2-ngrok-all-7b89f54595-x2lnr: {"Code":{"Code":"Forbidden","Status":403},"Message":"clusters.management.cattle.io \"c-m-s2ztvcjw\" is forbidden: User \"u-4pizqrctqn\" cannot get resource \"clusters\" in API group \"management.cattle.io\" at the cluster scope","Cause":null,"FieldName":""} (get nodes)
2021/08/17 19:03:20 [INFO] Handling backend connection request [c-m-s2ztvcjw]
2021/08/17 19:03:23 [INFO] Failed to find providerID for selector rke.cattle.io/machine=1e2a1989-c0c8-49fb-ad4b-eb5a460bda1f in cluster fleet-default/arvind-rke2-ngrok, machine arvind-rke2-ngrok-all-7b89f54595-d9lg4: {"Code":{"Code":"Forbidden","Status":403},"Message":"clusters.management.cattle.io \"c-m-s2ztvcjw\" is forbidden: User \"u-4pizqrctqn\" cannot get resource \"clusters\" in API group \"management.cattle.io\" at the cluster scope","Cause":null,"FieldName":""} (get nodes)
2021/08/17 19:03:23 [INFO] Failed to find providerID for selector rke.cattle.io/machine=c69e993f-dc25-431c-aed7-9cc01b2448a7 in cluster fleet-default/arvind-rke2-ngrok, machine arvind-rke2-ngrok-all-7b89f54595-x6rmb: {"Code":{"Code":"Forbidden","Status":403},"Message":"clusters.management.cattle.io \"c-m-s2ztvcjw\" is forbidden: User \"u-4pizqrctqn\" cannot get resource \"clusters\" in API group \"management.cattle.io\" at the cluster scope","Cause":null,"FieldName":""} (get nodes)
2021/08/17 19:03:26 [INFO] error in remotedialer server [400]: websocket: close 1006 (abnormal closure): unexpected EOF
2021/08/17 19:03:26 [INFO] Failed to find providerID for selector rke.cattle.io/machine=29d13fb4-accc-4f6d-aad8-d9979661a7b1 in cluster fleet-default/arvind-rke2-ngrok, machine arvind-rke2-ngrok-all-7b89f54595-x2lnr: {"Code":{"Code":"Forbidden","Status":403},"Message":"clusters.management.cattle.io \"c-m-s2ztvcjw\" is forbidden: User \"u-4pizqrctqn\" cannot get resource \"clusters\" in API group \"management.cattle.io\" at the cluster scope","Cause":null,"FieldName":""} (get nodes)
2021/08/17 19:03:30 [INFO] Handling backend connection request [c-m-s2ztvcjw]
2021/08/17 19:03:38 [INFO] Failed to find providerID for selector rke.cattle.io/machine=1e2a1989-c0c8-49fb-ad4b-eb5a460bda1f in cluster fleet-default/arvind-rke2-ngrok, machine arvind-rke2-ngrok-all-7b89f54595-d9lg4: {"Code":{"Code":"Forbidden","Status":403},"Message":"clusters.management.cattle.io \"c-m-s2ztvcjw\" is forbidden: User \"u-4pizqrctqn\" cannot get resource \"clusters\" in API group \"management.cattle.io\" at the cluster scope","Cause":null,"FieldName":""} (get nodes)
2021/08/17 19:03:39 [INFO] Failed to find providerID for selector rke.cattle.io/machine=c69e993f-dc25-431c-aed7-9cc01b2448a7 in cluster fleet-default/arvind-rke2-ngrok, machine arvind-rke2-ngrok-all-7b89f54595-x6rmb: {"Code":{"Code":"Forbidden","Status":403},"Message":"clusters.management.cattle.io \"c-m-s2ztvcjw\" is forbidden: User \"u-4pizqrctqn\" cannot get resource \"clusters\" in API group \"management.cattle.io\" at the cluster scope","Cause":null,"FieldName":""} (get nodes)
2021/08/17 19:03:41 [INFO] Handling backend connection request [c-m-s2ztvcjw]
2021/08/17 19:03:42 [INFO] Failed to find providerID for selector rke.cattle.io/machine=29d13fb4-accc-4f6d-aad8-d9979661a7b1 in cluster fleet-default/arvind-rke2-ngrok, machine arvind-rke2-ngrok-all-7b89f54595-x2lnr: {"Code":{"Code":"Forbidden","Status":403},"Message":"clusters.management.cattle.io \"c-m-s2ztvcjw\" is forbidden: User \"u-4pizqrctqn\" cannot get resource \"clusters\" in API group \"management.cattle.io\" at the cluster scope","Cause":null,"FieldName":""} (get nodes)
2021/08/17 19:03:43 [INFO] error in remotedialer server [400]: websocket: close 1006 (abnormal closure): unexpected EOF
2021/08/17 19:03:43 [INFO] error in remotedialer server [400]: websocket: close 1006 (abnormal closure): unexpected EOF
2021/08/17 19:03:51 [INFO] Handling backend connection request [c-m-s2ztvcjw]
2021/08/17 19:03:54 [INFO] Failed to find providerID for selector rke.cattle.io/machine=1e2a1989-c0c8-49fb-ad4b-eb5a460bda1f in cluster fleet-default/arvind-rke2-ngrok, machine arvind-rke2-ngrok-all-7b89f54595-d9lg4: {"Code":{"Code":"Forbidden","Status":403},"Message":"clusters.management.cattle.io \"c-m-s2ztvcjw\" is forbidden: User \"u-4pizqrctqn\" cannot get resource \"clusters\" in API group \"management.cattle.io\" at the cluster scope","Cause":null,"FieldName":""} (get nodes)
2021/08/17 19:03:54 [INFO] Failed to find providerID for selector rke.cattle.io/machine=c69e993f-dc25-431c-aed7-9cc01b2448a7 in cluster fleet-default/arvind-rke2-ngrok, machine arvind-rke2-ngrok-all-7b89f54595-x6rmb: {"Code":{"Code":"Forbidden","Status":403},"Message":"clusters.management.cattle.io \"c-m-s2ztvcjw\" is forbidden: User \"u-4pizqrctqn\" cannot get resource \"clusters\" in API group \"management.cattle.io\" at the cluster scope","Cause":null,"FieldName":""} (get nodes)
2021/08/17 19:03:57 [INFO] Failed to find providerID for selector rke.cattle.io/machine=29d13fb4-accc-4f6d-aad8-d9979661a7b1 in cluster fleet-default/arvind-rke2-ngrok, machine arvind-rke2-ngrok-all-7b89f54595-x2lnr: {"Code":{"Code":"Forbidden","Status":403},"Message":"clusters.management.cattle.io \"c-m-s2ztvcjw\" is forbidden: User \"u-4pizqrctqn\" cannot get resource \"clusters\" in API group \"management.cattle.io\" at the cluster scope","Cause":null,"FieldName":""} (get nodes)
2021/08/17 19:04:01 [INFO] Handling backend connection request [c-m-s2ztvcjw]
2021/08/17 19:04:02 [INFO] error in remotedialer server [400]: websocket: close 1006 (abnormal closure): unexpected EOF
2021/08/17 19:04:09 [INFO] Failed to find providerID for selector rke.cattle.io/machine=1e2a1989-c0c8-49fb-ad4b-eb5a460bda1f in cluster fleet-default/arvind-rke2-ngrok, machine arvind-rke2-ngrok-all-7b89f54595-d9lg4: {"Code":{"Code":"Forbidden","Status":403},"Message":"clusters.management.cattle.io \"c-m-s2ztvcjw\" is forbidden: User \"u-4pizqrctqn\" cannot get resource \"clusters\" in API group \"management.cattle.io\" at the cluster scope","Cause":null,"FieldName":""} (get nodes)
2021/08/17 19:04:09 [INFO] Failed to find providerID for selector rke.cattle.io/machine=c69e993f-dc25-431c-aed7-9cc01b2448a7 in cluster fleet-default/arvind-rke2-ngrok, machine arvind-rke2-ngrok-all-7b89f54595-x6rmb: {"Code":{"Code":"Forbidden","Status":403},"Message":"clusters.management.cattle.io \"c-m-s2ztvcjw\" is forbidden: User \"u-4pizqrctqn\" cannot get resource \"clusters\" in API group \"management.cattle.io\" at the cluster scope","Cause":null,"FieldName":""} (get nodes)
2021/08/17 19:04:10 [INFO] error in remotedialer server [400]: read tcp 172.17.0.2:80->172.17.0.1:43678: i/o timeout
2021/08/17 19:04:10 [INFO] Stopping cluster agent for c-m-s2ztvcjw
2021/08/17 19:04:10 [ERROR] failed to start cluster controllers c-m-s2ztvcjw: context canceled
2021/08/17 19:04:12 [INFO] Failed to find providerID for selector rke.cattle.io/machine=29d13fb4-accc-4f6d-aad8-d9979661a7b1 in cluster fleet-default/arvind-rke2-ngrok, machine arvind-rke2-ngrok-all-7b89f54595-x2lnr: {"Code":{"Code":"Forbidden","Status":403},"Message":"clusters.management.cattle.io \"c-m-s2ztvcjw\" is forbidden: User \"u-4pizqrctqn\" cannot get resource \"clusters\" in API group \"management.cattle.io\" at the cluster scope","Cause":null,"FieldName":""} (get nodes)
2021/08/17 19:04:12 [INFO] Handling backend connection request [c-m-s2ztvcjw]
2021/08/17 19:04:22 [INFO] error in remotedialer server [400]: websocket: close 1006 (abnormal closure): unexpected EOF
2021/08/17 19:04:22 [INFO] error in remotedialer server [400]: websocket: close 1006 (abnormal closure): unexpected EOF
2021/08/17 19:04:22 [INFO] Handling backend connection request [c-m-s2ztvcjw]
2021/08/17 19:04:24 [INFO] Failed to find providerID for selector rke.cattle.io/machine=1e2a1989-c0c8-49fb-ad4b-eb5a460bda1f in cluster fleet-default/arvind-rke2-ngrok, machine arvind-rke2-ngrok-all-7b89f54595-d9lg4: {"Code":{"Code":"Forbidden","Status":403},"Message":"clusters.management.cattle.io \"c-m-s2ztvcjw\" is forbidden: User \"u-4pizqrctqn\" cannot get resource \"clusters\" in API group \"management.cattle.io\" at the cluster scope","Cause":null,"FieldName":""} (get nodes)
2021/08/17 19:04:24 [INFO] Failed to find providerID for selector rke.cattle.io/machine=c69e993f-dc25-431c-aed7-9cc01b2448a7 in cluster fleet-default/arvind-rke2-ngrok, machine arvind-rke2-ngrok-all-7b89f54595-x6rmb: {"Code":{"Code":"Forbidden","Status":403},"Message":"clusters.management.cattle.io \"c-m-s2ztvcjw\" is forbidden: User \"u-4pizqrctqn\" cannot get resource \"clusters\" in API group \"management.cattle.io\" at the cluster scope","Cause":null,"FieldName":""} (get nodes)
2021/08/17 19:04:27 [INFO] Failed to find providerID for selector rke.cattle.io/machine=29d13fb4-accc-4f6d-aad8-d9979661a7b1 in cluster fleet-default/arvind-rke2-ngrok, machine arvind-rke2-ngrok-all-7b89f54595-x2lnr: {"Code":{"Code":"Forbidden","Status":403},"Message":"clusters.management.cattle.io \"c-m-s2ztvcjw\" is forbidden: User \"u-4pizqrctqn\" cannot get resource \"clusters\" in API group \"management.cattle.io\" at the cluster scope","Cause":null,"FieldName":""} (get nodes)
```

I do notice that ngrok shows a bunch of 101 responses to `/v3/register`.
![Screen Shot 2021-08-17 at 12 06 00 PM](https://user-images.githubusercontent.com/13127443/129785694-ee4c9122-5251-448e-8cc8-ec89dd17cb30.png)

 it is possible that this is due to the number of connections that ngrok allows without logging in. Will attempt to reproduce the above steps with a free, logged-in ngrok account, which should increase the number of connections allowed to 40 per minute based on [ngrok pricing](https://ngrok.com/pricing).

**Comment by aiyengar2** [comment] 2021-08-17 19:27
> #### Steps to reproduce
> - Provision a node and open two SSH sessions in it
> - In the first session:
>   - Install ngrok on it: `sudo apt-get update -y; sudo apt-get install -y unzip; curl -o ngrok.zip > https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-linux-amd64.zip; unzip ngrok.zip; rm ngrok.zip; mv ngrok /usr/bin/ngrok; chmod +x /usr/bin/ngrok`
- Login to ngrok by supplying a valid auth token: `ngrok authtoken ${NGROK_AUTH_TOKEN}`
>   - Run `ngrok http 80`
> - In the second SSH session, run the following command to start Rancher
>  ```
> # RANCHER_VERSION=v2.6.0-rc2
> RANCHER_VERSION=v2.6.0-rc3
> 
> curl https://releases.rancher.com/install-docker/20.10.sh | sh
> 
> docker run -d --restart=unless-stopped \
>   -p 80:80 -p 443:443 \
>   --privileged \
>   rancher/rancher:${RANCHER_VERSION}
>  ```
> - Access Rancher via ngrok and set the server-url to the ngrok URL
> - Deploy a RKE2 cluster
> - View Rancher logs

### 2.6.0-rc3

The issue is not observed; the RKE2 cluster is able to provision successfully!

![d4f765bef383 ngrok io_dashboard_c___manager_provisioning cattle io cluster_fleet-default_arvind-rke2-ngrok](https://user-images.githubusercontent.com/13127443/129788216-f7a75ead-0829-4d3a-a440-19aa76fdfbc7.png)

**Comment by aiyengar2** [comment] 2021-08-17 19:30
Since it seems like Rancher does finish provisioning on a docker install rancher behind ngrok **as long as the ngrok account is not anonymous (e.g. a Free user is sufficient)**, I think there are two paths forward here:
1. We can close out this issue since there is a way to configure ngrok in order to have it work with a docker install of rancher
2. We can leave this issue open in order to get Rancher to requiring <20 connections per minute and address it at some point in 2.6.x. I don't think this needs to be a release blocker for 2.6.0.

cc: @sowmyav27 I think we should go with option 1 and close out this issue since it was reported by Kinara and probably does not affect any of our users. What do you think?

**Comment by sowmyav27** [comment] 2021-08-18 18:24
Separate issue logged - https://github.com/rancher/rancher/issues/34280. Closing this one as original issue is not seen anymore

**Closed by sowmyav27** 2021-08-18 18:24 UTC
Labels: area/rke2, [zube]: QA Next up, status/dev-validate, status/final-release-blocker
