### ISSUE TITLE
add defaultRegistry to rancher helm for rancher images

### ISSUE THREAD

**Issue by curx** [rancher/rancher#18582] opened 2019-03-05 10:45 UTC
**What kind of request is this enhancement/feature request:**
add new value defaultRegistry to helm to get a better task for a rancher deployment, e.g. on an AIR gap installation and all relevant information are set in a helm-value file, only

**Steps to reproduce (least amount of steps as possible):**

Customize rancher-values.yaml for single point of configuration, e.g. tls.ingress.source etc.pp
`helm inspect values rancher-<version>.tgz > rancher-values.yaml`

and customize all needed settings at value file, or create an single one:
`echo "defaultRegisty: internal.registry.tld:port" > rancher-values.yaml`

`helm template rancher-<version>.tgz --namespace cattle-system --name rancher --values rancher-values.yaml ...`

**Result:**
the deployment manifest have all relevant parts in place:

```
(...)
     containers:
      - image: registry.yourdomain.com:port/rancher/rancher:v2.2.0-alpha6
(...)
        env:
(...)
        - name: CATTLE_SYSTEM_DEFAULT_REGISTRY
          value: registry.yourdomain.com:port
(...)
```
**Other details that may be helpful:**
it configured the URL of rancher image and set the env for the default-system-registry

**Environment information**
- Rancher version:  stable (v2.1.6) and last version
- Installation option: HA AIRgap Installation, no access to Remote DockerHUB/Internet

**Comment by janeczku** [comment] 2019-03-05 11:38
Hi @curx, the ability to set the default registry in the Helm chart was added here: https://github.com/rancher/rancher/issues/17156. This will allow users to pass arbitrary environment variables to the Rancher deployment.

Example from values.yml:
```
# Extra environment variables passed to the rancher pods.
# extraEnv:
- name: CATTLE_SYSTEM_DEFAULT_REGISTRY
  value: "private-registry.example.com"
```

See here for the documentation PR: https://github.com/rancher/docs/pull/1156/files

**Comment by janeczku** [comment] 2019-03-05 11:38
Duplicate of https://github.com/rancher/rancher/issues/17156

**Closed by janeczku** 2019-03-05 11:38 UTC

**Comment by curx** [comment] 2019-03-05 11:57
@janeczku The improvement is aimed at setting the (internal) registry once, otherwise it must be set in extraEnv and in the rancherImage.

**Comment by janeczku** [comment] 2019-03-05 12:14
@curx I understand. We want to keep the number of Helm options to a minimum and therefore decided to allow setting it via the `envVar` option.  Also, the registry configured in the Default Registry Setting must not necessarily be the same as the registry used for the Helm install.
