### ISSUE TITLE
Lowercase hostnames for nodes added to custom cluster

### ISSUE THREAD

**Issue by superseb** [rancher/rancher#12592] opened 2018-04-09 20:13 UTC
**Rancher versions:**
rancher/server: v2.0.0-beta2

**Steps to Reproduce:**

- Create a node with hostname with a capital letter (`Hostname`)
- Add it to a custom cluster

**Results:**
```
Failed to get kubernetes node [Hostname]: "Hostname" not found
```

**Comment by sangeethah** [comment] 2018-04-09 20:30
Duplicate of - https://github.com/rancher/rancher/issues/12499

**Closed by sangeethah** 2018-04-09 20:30 UTC
Labels: kind/bug, version/2.0
