### ISSUE TITLE
Allow LDAP or any auth groups as admins rather than individual

### ISSUE THREAD

**Issue by will-chan** [rancher/rancher#5954] opened 2016-09-12 22:55 UTC
Today, you have to specify individual users as admin users for Rancher.  This feature allows admins to configure groups to allow same privileges.

**Comment by fuhbar** [comment] 2016-09-24 11:22
@will-chan Is this possibly a duplicate of #5488? If so we could close this one.

**Comment by deniseschannon** [comment] 2016-12-13 04:04
Duplicate of #5488

**Closed by deniseschannon** 2016-12-13 04:04 UTC
Labels: kind/enhancement
