### ISSUE TITLE
broken Statistics page v0.59.0

### ISSUE THREAD

**Issue by fedya** [rancher/rancher#3615] opened 2016-02-13 00:11 UTC
Statistics only in pending state
![snapshot6](https://cloud.githubusercontent.com/assets/598477/13023949/57bcf3bc-d1ff-11e5-9171-603deb311d51.png)

[root@abf-slave ~]# docker version
Client:
 Version:      1.10.0
 API version:  1.22
 Go version:   go1.5.1
 Git commit:   35sfs44t
 OS/Arch:      linux/amd64

Server:
 Version:      1.10.0
 API version:  1.22
 Go version:   go1.5.1
 Git commit:   35sfs44t
 Built:        
 OS/Arch:      linux/amd64

Rancher: v0.59.0

If i downgrade back to docker 1.9.0 all working fine again.

**Comment by fedya** [comment] 2016-02-13 09:22
2/13/2016 12:21:10 PMtime="2016-02-13T09:21:10Z" level=info msg="Invalid HostUuid." hostUuid=a7477703-031b-4c93-a8b6-e7dde14c395b
2/13/2016 12:21:10 PMtime="2016-02-13T09:21:10Z" level=error msg="could not find host uuid"
2/13/2016 12:21:11 PMtime="2016-02-13T09:21:11Z" level=info msg="Registering backend for host [a7477703-031b-4c93-a8b6-e7dde14c395b]"
2/13/2016 12:22:05 PMtime="2016-02-13T09:22:05Z" level=info msg="Invalid HostUuid." hostUuid=a7477703-031b-4c93-a8b6-e7dde14c395b
2/13/2016 12:22:05 PMtime="2016-02-13T09:22:05Z" level=error msg="could not find host uuid"
2/13/2016 12:22:07 PMtime="2016-02-13T09:22:07Z" level=info msg="Registering backend for host [a7477703-031b-4c93-a8b6-e7dde14c395b]"

**Comment by bacheson** [comment] 2016-02-13 22:16
+1

Don't mean to sound negative by the following comment; After-all Rancher is something I'm not paying for and absolutely love.

These sort of regressions in the UI seem very common. How are tests not catching these issues?

**Comment by vincent99** [comment] 2016-02-13 23:39
@bacheson This issue has nothing to do with the UI, it can't show data that isn't sent.

If you think you can do a better job of testing the infinitely variable combinations of hardware, network & storage configs, distros, kernels, docker versions, user software and random vendor patches applied to all of those levels, and separating the actual issues from the majority that end up being "lolz firewall"/user error, [we're hiring](http://rancher.com/careers/).

**Comment by ibuildthecloud** [comment] 2016-02-14 00:14
I believe this is due to an incompatibility between cadvisor and Docker 1.10, @fedya can you share what is your host OS?

@bacheson The tests cases for this functionality have not been ran against 1.10.  This is basically a case of "OMG DOCKER 1.10 WAS RELEASED 9 DAYS AGO WHY HAVENT YOU FIXED EVERYTHING IT BREAKS!!!"

**Comment by bacheson** [comment] 2016-02-14 00:48
@vincent99 @ibuildthecloud 

For the record, 1.10-rc was release 1 month ago. Projects like Weave released updates immediately addressing incompatibilities.

I meant no offence guys ... I love and respect what you are doing

**Comment by fedya** [comment] 2016-02-14 01:00
@ibuildthecloud i tested ubuntu, centos and openmandriva.
Issue valid only for docker 1.9.1+ , on 1.9.0 everything works as expected

**Comment by ibuildthecloud** [comment] 2016-02-14 01:33
@bacheson Whoa.... don't poke the bear here.  You have no idea the amount of testing we have done against 1.10 already.  https://github.com/docker/docker/issues?utf8=%E2%9C%93&q=is%3Aissue+author%3Aibuildthecloud+  I have personally filed and help addressed 29 issues in 1.10 dating back to Dec 21 (yes before rc1 because we test against master in order to give us more time to get bugs fixed).  Not to toot our own horn here but Rancher is probably the largest contributor in QA of pre-releases of Docker.  We really really have to bite our tongue when people complain about quality or not fixing things fast enough because you really have no idea how much effort we already put into this.

**Comment by ibuildthecloud** [comment] 2016-02-14 01:36
@fedya Just to clarify you are seeing this issue with 1.9.1 and 1.10.0?  I'm personally not aware of an issue with 1.9.1

**Comment by bacheson** [comment] 2016-02-14 02:27
@ibuildthecloud I apologize if you feel I was challenging your work ... that was not my intention ... please accept my sincere apologies ... the community and people like myself owe an immense debt to trailblazers like yourself ... I'm a heavy user / huge fan of Rancher; I champion your platform on a daily basis to friends and colleagues

**Comment by ibuildthecloud** [comment] 2016-02-14 04:53
@bacheson Hey, no worries.  We love our users and are happy that they are forgiving of our mistakes.  When someone complains we take it as at least that means there is something they like about the product and wish it worked better.  If we get no complaints/issues then obviously nobody is using it :)

**Comment by fedya** [comment] 2016-02-14 14:24
@ibuildthecloud i tested it with 1.9.1 1.10.0 and 1.10.1 on Ubuntu 15.10 and OpenMandriva 2014.2
Issue not in host system but in docker, they changed something in containers data and new rancher can't parse it.

**Comment by fedya** [comment] 2016-02-14 14:25
Ubuntu server 15.10
Stats in pending state too.
```
root@ub0:~# docker version
Client:
 Version:      1.10.1
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   9e83765
 Built:        Thu Feb 11 19:32:54 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.10.1
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   9e83765
 Built:        Thu Feb 11 19:32:54 2016
 OS/Arch:      linux/amd64
```

Btw i found weird thing.
One of my hosts still live with 1.9.0 and if i switch to 1.9.0 host and go back to 1.10.x i see stats.

**Comment by fedya** [comment] 2016-02-17 12:37
issue in Cadvisor

```
2016-02-17 09:23:53,626 INFO process-manager [140370331438288] [process_manager.py:65] Launching ['cadvisor.sh', 'cadvisor', '-logtostderr=true', '-listen_ip', '127.0.0.1', '-port', '9344', '-housekeeping_interval', '1s', '-docker_root', u'/var/cache/docker']
2016-02-17 09:23:53,627 INFO process-manager [140370331438288] [process_manager.py:68] Launched ['cadvisor.sh', 'cadvisor', '-logtostderr=true', '-listen_ip', '127.0.0.1', '-port', '9344', '-housekeeping_interval', '1s', '-docker_root', u'/var/cache/docker'] as pid 4048
016-02-17 09:23:55,627 INFO process-manager [140370331438288] [process_manager.py:79] Process 4048 is dead, return code 255
2016-02-17 09:23:55,628 INFO process-manager [140370331438288] [process_manager.py:65] Launching ['cadvisor.sh', 'cadvisor', '-logtostderr=true', '-listen_ip', '127.0.0.1', '-port', '9344', '-housekeeping_interval', '1s', '-docker_root', u'/var/cache/docker']
2016-02-17 09:23:55,629 INFO process-manager [140370331438288] [process_manager.py:68] Launched ['cadvisor.sh', 'cadvisor', '-logtostderr=true', '-listen_ip', '127.0.0.1', '-port', '9344', '-housekeeping_interval', '1s', '-docker_root', u'/var/cache/docker'] as pid 4082
2016-02-17 09:23:57,629 INFO process-manager [140370331438288] [process_manager.py:79] Process 4082 is dead, return code 255
```

**Comment by fedya** [comment] 2016-02-17 15:30
Well, i fixed this issue in my host
Culrpit is here
https://github.com/rancher/rancher/blob/master/agent/Dockerfile#L18

**Comment by fedya** [comment] 2016-02-17 15:51
Let me explain what's going wrong with 1.9.1 and 1.10.x dockers and why Statistics can't work as expected.

At first look at this string
https://github.com/rancher/cadvisor-package/blob/master/cadvisor.sh#L6

`DIR=$(docker inspect rancher-agent | jq -r '.[0].Volumes["/var/log/rancher"]')`

It is okay for docker < 1.9.1  
but in modern version should be something like this
`DIR=$(docker inspect --format '{{ range .Mounts }}{{ if eq .Destination "/var/log/rancher" }}{{ .Source }}{{ end }}{{ end }}' rancher-agent)

Then look this 
https://github.com/rancher/rancher/blob/master/agent/run.sh#L157

`local dir="$(docker inspect -f '{{index .Volumes "/var/lib/cattle"}}' rancher-agent-state)"`

For 1.9.1+ is wrong, should be:

`local dir="$(docker inspect --format '{{ range .Mounts }}{{ if eq .Destination "/var/lib/cattle" }}{{ .Source }}{{ end }}{{ end }}' rancher-agent-state)"`

Why? Docker docs says that after 1.8 they moved to the 'new structure'.


Docker 1.10.1, stats page working as expected
![snapshot6](https://cloud.githubusercontent.com/assets/598477/13115099/824b3cb4-d5a7-11e5-87ee-fc0d2824946b.png)

**Comment by composer22** [comment] 2016-02-25 17:06
why is this closed?  How do we fix this or what is the work around?

**Comment by composer22** [comment] 2016-02-25 17:14
error:
```
docker run -d -e CATTLE_HOST_LABELS='com.XXX.role=master&com.XXX.awszone=a' --privileged -v /var/run/docker.sock:/var/run/docker.sock -v /var/lib/rancher:/var/lib/rancher --name rancher-agent-core-000 rancher/agent:v0.9.2 http://rancher-server.mgmt.XXX.com:32772/v1/scripts/905D7A51624CB1B8E5FC:1456347600000:A6kCzL0d4QW78fau5uzwSJzJNSM
```
Launch 1.10.x + Ubuntu 15.x + EC2
```
docker run -d -e CATTLE_HOST_LABELS='com.xxx.role=master&com.xxx.awszone=a' --privileged -v /var/run/docker.sock:/var/run/docker.sock -v /var/lib/rancher:/var/lib/rancher --name rancher-agent-core-000 rancher/agent:v0.9.2 http://rancher-server.mgmt.xxx.com:32772/v1/scripts/905D7A51624CB1B8E5FC:1456347600000:A6kCzL0d4QW78fau5uzwSJzJNSM
```
What is the release mechanism for your change to the agent docker image? I don't see a pull request or reference here yet you closed this ticket.

**Comment by deniseschannon** [comment] 2016-02-25 17:30
@composer22 Where do you see that the issue is closed?

**Comment by composer22** [comment] 2016-02-25 17:56
@deniseschannon Sorry. My misread.

Here is some additional testing info. 

systemd logging driver with Docker 1.10.x daemon
running rancher/agent:v0.9.2 

shell into the agent container....

This build appears to use when I log in:
```
#docker --version
Docker version 1.6.0, build 4749651
```
although...
```
# ls -lah docker*
-rwxr-xr-x 1 root root 15M Feb  2 21:33 docker
-rwxr-xr-x 1 root root 29M Feb  2 21:34 docker-1.9

#docker-1.9 --version
Docker version 1.9.1, build a34a1d5
```

Experiment based on cadvisor-package/cadvisor.sh and proposed changes:

```
# 1.6 w/ current:
docker inspect rancher-agent | jq -r '.[0].Volumes["/var/log/rancher"]'
/var/log/rancher

# 1.6 with proposed change:
docker inspect --format '{{ range .Mounts }}{{ if eq .Destination "/var/log/rancher" }}{{ .Source }}{{ end }}{{ end }}' rancher-agent    
null

# 1.9.1 with current:
docker-1.9 inspect rancher-agent | jq -r '.[0].Volumes["/var/log/rancher"]'
null

# 1.9.1 with proposed change:
docker-1.9 inspect --format '{{ range .Mounts }}{{ if eq .Destination "/var/log/rancher" }}{{ .Source }}{{ end }}{{ end }}' rancher-agent
/var/log/rancher
```
moving on to rancher/agent/run.sh

```
# 1.6 with current:
docker inspect -f '{{index .Volumes "/var/lib/cattle"}}' rancher-agent-state    
/var/lib/docker/volumes/609f517a8fb81d1fd02d812be45e0b143a43589ba259b10d40850d230ae83b5c/_data

# 1.6  with proposed change:
docker inspect --format '{{ range .Mounts }}{{ if eq .Destination "/var/lib/cattle" }}{{ .Source }}{{ end }}{{ end }}' rancher-agent-state    
null

# 1.9.1 with current:
docker-1.9 inspect -f '{{index .Volumes "/var/lib/cattle"}}' rancher-agent-state
Template parsing error: template: :1:8: executing "" at <.Volumes>: Volumes is not a field of struct type types.ContainerJSON

# 1.9.1 with proposed change:
docker-1.9 inspect --format '{{ range .Mounts }}{{ if eq .Destination "/var/lib/cattle" }}{{ .Source }}{{ end }}{{ end }}' rancher-agent-state
/var/lib/docker/volumes/609f517a8fb81d1fd02d812be45e0b143a43589ba259b10d40850d230ae83b5c/_data
```

**Comment by fedya** [comment] 2016-02-25 18:06
@composer22 
this issue is complex issue.
Well, part of this is connected to wrong PATH's detection, where 
`docker version |grep Client\ version | cut -d":" -f2`
can't grep anything
and second part connected with websocket.

If you want, guys, i can push my own image where issue fixed.

**Comment by composer22** [comment] 2016-02-25 18:31
@fedya 

No rush, but it would be nice. Just ping us here when you get some time.

Nothing is ever simple :dancers:

**Comment by cloudnautique** [comment] 2016-03-04 20:54
@fedya, `docker` inside the rancher agent is docker 1.6, which will use the API from 1.6 to talk to a Docker daemon regardless of version(so long as its greater). So it will continue to be able to use the current `grep` and `.Volumes`. It looks like your testing is done with both a newer client and newer Docker version and would explain what you are observing.

The Docker version check is only to make sure that Docker 1.6 is less then the server version. If its not we die early and the agent will not start. After that, we do not use that command for anything else.

The PR for agent/run.sh and the suggestions for the cAdvisor script will be needed once we upgrade the base docker in the rancher/agent container.

With Docker 1.10.x our suspicion it is the version of cAdvisor that needs to be updated. We have seen errors in the rancher-agent saying it can't get file system stats, and based on cAdvisors releases, they had issues to resolve with 1.10.x.

Which OS are you you running?

**Comment by hlj** [comment] 2016-03-10 00:41
:+1:

**Comment by composer22** [comment] 2016-03-16 01:23
sorry been offline and busy.

Running on Ubuntu 15.10 Wily

**Comment by cloudnautique** [comment] 2016-03-16 16:29
related to #3384

**Comment by composer22** [comment] 2016-03-16 20:20
interesting if its only a package change

**Comment by sangeethah** [comment] 2016-03-17 06:03
Tested with latest build from master:

Set up -  Hosts - Ubuntu 15.10  with docker - 1.10.3
Able to view graphs  for cpu , memory,network, storage for containers and host,

**Closed** 2016-03-17 20:23 UTC
Labels: area/stats, kind/bug, status/to-test

**Comment by composer22** [comment] 2016-03-22 20:57
thanks sangeethah

**Comment by MichaelErmer** [comment] 2016-03-23 18:26
@sangeethah, unfortunately i still have this error with rc1:
Rancher	v1.0.0-rc1
Cattle	v0.156.2
User Interface	v0.96.0
Rancher Compose	v0.7.3-rc2

rancher/agent:v0.11.0 

Ubuntu 14.04.4 LTS  -Linux 3.13.0-24-generic #46-Ubuntu SMP Thu Apr 10 19:11:08 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux
Docker version 1.10.3, build 20f81dd

**Comment by cloudnautique** [comment] 2016-03-23 18:33
@MichaelErmer can you clarify which error/behavior you are seeing?

 Can you attach logs from the rancher-agent and/or rancher/server that show the errors?

**Comment by deniseschannon** [comment] 2016-03-23 18:33
@MichaelErmer Ubuntu 14.04.4 never had an issue with stats not showing up. My stats show up in v0.63.1 and v1.0.0-rc1.

**Comment by MichaelErmer** [comment] 2016-03-23 18:36
@deniseschannon http://puu.sh/nReJg/7ef580c874.png

the agent logs show no errors:
````
I0323 19:30:10.032142   25687 machine.go:50] Couldn't collect info from any of the files in "/etc/machine-id,/var/lib/dbus/machine-id"
I0323 19:30:10.032226   25687 manager.go:205] Machine: {NumCores:32 CpuFrequency:2401000 MemoryCapacity:270381015040 MachineID: SystemUUID:00000000-0000-0000-0000-0CC47AA9F500 BootID:ad19feea-0327-4046-9085-338782c76ff2 Filesystems:[{Device:/dev/sda2 Capacity:2155920961536 Type:vfs Inodes:133693440}] DiskMap:map[8:0:{Name:sda Major:8 Minor:0 Size:2397799710720 Scheduler:deadline} 8:16:{Name:sdb Major:8 Minor:16 Size:1999844147200 Scheduler:deadline}] NetworkDevices:[{Name:eth0 MacAddress:0c:c4:7a:a9:f5:00 Speed:100 Mtu:1500} {Name:eth1 MacAddress:0c:c4:7a:a9:f5:01 Speed:1000 Mtu:1500} {Name:lxcbr0 MacAddress:32:e8:e1:f9:63:a5 Speed:0 Mtu:1500}] Topology:[{Id:0 Memory:135092084736 Cores:[{Id:0 Threads:[0 16] Caches:[{Size:32768 Type:Data Level:1} {Size:32768 Type:Instruction Level:1} {Size:262144 Type:Unified Level:2}]} {Id:1 Threads:[1 17] Caches:[{Size:32768 Type:Data Level:1} {Size:32768 Type:Instruction Level:1} {Size:262144 Type:Unified Level:2}]} {Id:2 Threads:[2 18] Caches:[{Size:32768 Type:Data Level:1} {Size:32768 Type:Instruction Level:1} {Size:262144 Type:Unified Level:2}]} {Id:3 Threads:[3 19] Caches:[{Size:32768 Type:Data Level:1} {Size:32768 Type:Instruction Level:1} {Size:262144 Type:Unified Level:2}]} {Id:4 Threads:[4 20] Caches:[{Size:32768 Type:Data Level:1} {Size:32768 Type:Instruction Level:1} {Size:262144 Type:Unified Level:2}]} {Id:5 Threads:[5 21] Caches:[{Size:32768 Type:Data Level:1} {Size:32768 Type:Instruction Level:1} {Size:262144 Type:Unified Level:2}]} {Id:6 Threads:[6 22] Caches:[{Size:32768 Type:Data Level:1} {Size:32768 Type:Instruction Level:1} {Size:262144 Type:Unified Level:2}]} {Id:7 Threads:[7 23] Caches:[{Size:32768 Type:Data Level:1} {Size:32768 Type:Instruction Level:1} {Size:262144 Type:Unified Level:2}]}] Caches:[{Size:20971520 Type:Unified Level:3}]} {Id:1 Memory:135288930304 Cores:[{Id:0 Threads:[8 24] Caches:[{Size:32768 Type:Data Level:1} {Size:32768 Type:Instruction Level:1} {Size:262144 Type:Unified Level:2}]} {Id:1 Threads:[9 25] Caches:[{Size:32768 Type:Data Level:1} {Size:32768 Type:Instruction Level:1} {Size:262144 Type:Unified Level:2}]} {Id:2 Threads:[10 26] Caches:[{Size:32768 Type:Data Level:1} {Size:32768 Type:Instruction Level:1} {Size:262144 Type:Unified Level:2}]} {Id:3 Threads:[11 27] Caches:[{Size:32768 Type:Data Level:1} {Size:32768 Type:Instruction Level:1} {Size:262144 Type:Unified Level:2}]} {Id:4 Threads:[12 28] Caches:[{Size:32768 Type:Data Level:1} {Size:32768 Type:Instruction Level:1} {Size:262144 Type:Unified Level:2}]} {Id:5 Threads:[13 29] Caches:[{Size:32768 Type:Data Level:1} {Size:32768 Type:Instruction Level:1} {Size:262144 Type:Unified Level:2}]} {Id:6 Threads:[14 30] Caches:[{Size:32768 Type:Data Level:1} {Size:32768 Type:Instruction Level:1} {Size:262144 Type:Unified Level:2}]} {Id:7 Threads:[15 31] Caches:[{Size:32768 Type:Data Level:1} {Size:32768 Type:Instruction Level:1} {Size:262144 Type:Unified Level:2}]}] Caches:[{Size:20971520 Type:Unified Level:3}]}] CloudProvider:Unknown InstanceType:Unknown InstanceID:None}
I0323 19:30:10.033420   25687 manager.go:211] Version: {KernelVersion:3.13.0-24-generic ContainerOsVersion:Ubuntu 14.04.4 LTS DockerVersion:1.10.3 CadvisorVersion:0.22.0 CadvisorRevision:}
I0323 19:30:10.225645   25687 factory.go:233] Registering Docker factory
I0323 19:30:10.227663   25687 factory.go:97] Registering Raw factory
I0323 19:30:10.483184   25687 manager.go:1039] Started watching for new ooms in manager
I0323 19:30:10.483236   25687 oomparser.go:198] OOM parser using kernel log file: "/var/log/kern.log"
I0323 19:30:10.486193   25687 manager.go:292] Starting recovery of all containers
I0323 19:30:10.630095   25687 manager.go:297] Recovery completed
I0323 19:30:10.653622   25687 cadvisor.go:106] Starting cAdvisor version: 0.22.0- on port 9344
time="2016-03-23T18:30:10Z" level="info" msg="Host not registered yet. Sleeping 1 second and trying again." Attempt=7 reportedUuid="83fbcf8f-769d-4e8d-ba1f-3fadbfcfaa0d" 
time="2016-03-23T18:30:11Z" level="info" msg="Host not registered yet. Sleeping 1 second and trying again." Attempt=8 reportedUuid="83fbcf8f-769d-4e8d-ba1f-3fadbfcfaa0d" 
time="2016-03-23T18:30:12Z" level="info" msg="Connecting to proxy." url="ws://192.168.2.22:8086/v1/connectbackend?token=eyJhbGciOiJSUzI1NiJ9.eyJleHAiOjE0NTg3NTgxMTIsInN1YiI6ImNhdHRsZSIsImlzcyI6Imh0dHA6XC9cL2NhdHRsZS5pbyIsInJlcG9ydGVkVXVpZCI6IjgzZmJjZjhmLTc2OWQtNGU4ZC1iYTFmLTNmYWRiZmNmYWEwZCIsImlhdCI6MTQ1ODc1NzgxMiwia2lkIjoiZGVmYXVsdCJ9.nNbhA6UBINvG8dloW7zsYvXlU4Ik9DWTCZ3oolkr9WKJLsEmiFniuBEamoj402I3HeX70U9y9dib6pdZas6nr6K3gIx2AQcY7cLQqoCNaNQdTUSbSt_IX1UgqBex2zL2njY8vcISViU3YvImnN0Vg-WFuLoOxnpSifX1zUa3YdUPbjMfxhBJFkUVL2gpt8PHd2XgvFolYoyhsN8zWp-KDb5guqYFGLtuFrlJj1Qyk5qzXxsFllz33YEiAto8eZscoCxJjjdJyHwPVYlPZQxizH1Mb3azqQMeRcrqoWL85ya2uwk5Hous9Nv2z4Na18izAqFqIGcjNgOkQsxjG8ZlAw" 
time="2016-03-23T18:30:26Z" level="info" msg="Processing event: &docker.APIEvents{Status:\"start\", ID:\"4f6a3a448617fc2aa954619003b959790b0266d113961c4fefa75ff7246f8a6a\", From:\"-simulated-\", Time:0}" 
time="2016-03-23T18:30:26Z" level="info" msg="Processing event: &docker.APIEvents{Status:\"start\", ID:\"0dbf668b26c2904f8e461215f3bb53645b063bc721262342c520af9829e4162c\", From:\"-simulated-\", Time:0}" 
time="2016-03-23T18:30:26Z" level="info" msg="Processing event: &docker.APIEvents{Status:\"start\", ID:\"7e2f269fe91a79234636c1608e5e111b23d7cec44891490586ed95c2737cad16\", From:\"-simulated-\", Time:0}" 
time="2016-03-23T18:30:27Z" level="info" msg="Processing event: &docker.APIEvents{Status:\"start\", ID:\"12dae896145cf46ffa6c15431f585d24b528a20ccce3317db3614d694782d509\", From:\"-simulated-\", Time:0}" 
time="2016-03-23T18:30:27Z" level="info" msg="Processing event: &docker.APIEvents{Status:\"start\", ID:\"3dc8e0b3da568e0c2ab4d6b6915da91c6152dd496b61c332f126ce07092f6c42\", From:\"-simulated-\", Time:0}" 
time="2016-03-23T18:30:27Z" level="info" msg="Processing event: &docker.APIEvents{Status:\"start\", ID:\"50ec50c9d75faa246cc17c4542067f3705139c92a93b8f21badf5da48da8fd1c\", From:\"-simulated-\", Time:0}" 
time="2016-03-23T18:30:27Z" level="info" msg="Processing event: &docker.APIEvents{Status:\"start\", ID:\"4a3e1b96fd0d3c6b3f639625086de9363c7c8dac8eefb13e0b20e9248ecad309\", From:\"-simulated-\", Time:0}" 
time="2016-03-23T18:30:27Z" level="info" msg="Processing event: &docker.APIEvents{Status:\"start\", ID:\"38bbe8fbfa3e6804be7f77400374b876b928cf0ef72f993b687d90c75bf3a965\", From:\"-simulated-\", Time:0}" 
time="2016-03-23T18:30:27Z" level="info" msg="Processing event: &docker.APIEvents{Status:\"start\", ID:\"1e9af892fd52831a3cc5883f569e8349b1978927f86e1a10947b8a809461dd74\", From:\"-simulated-\", Time:0}" 
time="2016-03-23T18:30:27Z" level="info" msg="Processing event: &docker.APIEvents{Status:\"start\", ID:\"b296ccdeb559e7068eef4b39ec096669a41769c41021a836d378fcddd2127b3f\", From:\"-simulated-\", Time:0}" 
time="2016-03-23T18:30:27Z" level="info" msg="Processing event: &docker.APIEvents{Status:\"start\", ID:\"85a9376e355cd459026686e381cbcb1d9d6d4602a726d567941388436e8b4c72\", From:\"-simulated-\", Time:0}" 
time="2016-03-23T18:30:27Z" level="info" msg="Processing event: &docker.APIEvents{Status:\"start\", ID:\"e17e09029b62872b8a9376e81c643b2a2d428921c820342b7cf4bd0a3544af4d\", From:\"-simulated-\", Time:0}" 
time="2016-03-23T18:30:27Z" level="info" msg="Processing event: &docker.APIEvents{Status:\"start\", ID:\"0f1299cc36fbb82d118d6c9d62b20871779c11a68a3ce12bbb931432b28d414a\", From:\"-simulated-\", Time:0}" 
time="2016-03-23T18:31:46Z" level="info" msg="Processing event: &docker.APIEvents{Status:\"start\", ID:\"cfa47673c9302d2d191e8419ac4390097a7e2a226649c062b838b9aaddd6b17f\", From:\"rancher/agent-instance:v0.8.1\", Time:1458757906}" 
time="2016-03-23T18:31:46Z" level="info" msg="Assigning IP [10.42.169.218/16], ContainerId [cfa47673c9302d2d191e8419ac4390097a7e2a226649c062b838b9aaddd6b17f], Pid [26891]" 
time="2016-03-23T18:31:46Z" level="info" msg="Processing event: &docker.APIEvents{Status:\"start\", ID:\"cfa47673c9302d2d191e8419ac4390097a7e2a226649c062b838b9aaddd6b17f\", From:\"-simulated-\", Time:0}" 
time="2016-03-23T18:31:53Z" level="info" msg="Processing event: &docker.APIEvents{Status:\"start\", ID:\"11454373144ec11beb24968c9751c907fd01aad08a8b3c6f93281f397563183a\", From:\"redis:latest\", Time:1458757913}" 
time="2016-03-23T18:31:54Z" level="info" msg="Assigning IP [10.42.65.168/16], ContainerId [11454373144ec11beb24968c9751c907fd01aad08a8b3c6f93281f397563183a], Pid [28124]" 
time="2016-03-23T18:31:54Z" level="info" msg="Processing event: &docker.APIEvents{Status:\"start\", ID:\"11454373144ec11beb24968c9751c907fd01aad08a8b3c6f93281f397563183a\", From:\"-simulated-\", Time:0}" 
`

**Comment by MichaelErmer** [comment] 2016-03-23 18:53
NVM, sorry guys, the problem was my nginx config not upgrading websockets.

**Comment by StorminGorman** [comment] 2016-04-21 20:26
This seems to be broken again using docker 1.11.0

**Comment by MichaelErmer** [comment] 2016-04-21 21:45
@StorminGorman are u using an nginx proxy?

**Comment by deniseschannon** [comment] 2016-04-22 18:52
@StorminGorman @MichaelErmer This is a known issue for Docker 1.11 and v1.0.1. v1.0.1 supports Docker 1.10.3.

**Comment by tmds** [comment] 2016-05-03 12:25
> @StorminGorman @MichaelErmer This is a known issue for Docker 1.11 and v1.0.1. v1.0.1 supports Docker 1.10.3.

Is there an open issue? Should this issue be re-opened?

**Comment by deniseschannon** [comment] 2016-05-05 23:50
https://github.com/rancher/rancher/issues/4406
