### ISSUE TITLE
[Forwardport 2.9][BUG] [CAPR] rancher-system-agent can be restarted during an etcd restoration operation which will lead to inconsistent results 

### ISSUE THREAD

**Issue by Jono-SUSE-Rancher** [rancher/rancher#43964] opened 2024-01-09 20:25 UTC
Forwardport of https://github.com/rancher/rancher/issues/43658 - this was already merged prior to branching for 2.9 so it should already be available for testing in 2.9.

**Comment by markusewalker** [comment] 2024-01-30 17:28
**QA TEST PLAN**

|#|Scenario|Test Case|
|---|---|---|
|1|Restore snapshot|Provision downstream RKE2 cluster, take etcd snapshot, upgrade K8s cluster, restore snapshot|
|2|Restore snapshot with rotated worker nodes|Provision downstream RKE2 cluster, take etcd snapshot, rotate worker nodes, restore snapshot|
|3|Restore same snapshot with rotated worker nodes 3 times|Provision downstream K3s cluster, take etcd snapshot, rotate worker nodes, upgrade K8s cluster, restore same snapshot 3 times|
|4|Restore snapshot after rebooting nodes|Provision downstream K3s cluster, take etcd snapshot, reboot worker nodes, restore snapshot|
|5|Restore snapshot after rebooting rotated worker nodes|Provision downstream K3s cluster, take etcd snapshot, rotate worker nodes, reboot worker nodes, restore snapshot|

**Comment by markusewalker** [comment] 2024-01-30 18:46
Tested this against `v2.9-head` https://github.com/rancher/rancher/commit/ed8725676a615b0fb6851957f4295dad6593fb89. See details below:

**ENVIRONMENT DETAILS**
- Rancher install: Docker
- Rancher version: `v2.9-head` https://github.com/rancher/rancher/commit/ed8725676a615b0fb6851957f4295dad6593fb89

**TEST RESULT**
|#|Scenario|Test Case|Result
|---|---|---|---|
|1|Restore snapshot|Provision downstream RKE2 cluster, take etcd snapshot, upgrade K8s cluster, restore snapshot|:white_check_mark:|
|2|Restore snapshot with rotated worker nodes|Provision downstream RKE2 cluster, take etcd snapshot, rotate worker nodes, restore snapshot|:white_check_mark:|
|3|Restore same snapshot with rotated worker nodes 3 times|Provision downstream K3s cluster, take etcd snapshot, rotate worker nodes, upgrade K8s cluster, restore same snapshot 3 times|:white_check_mark:|
|4|Restore snapshot after rebooting nodes|Provision downstream K3s cluster, take etcd snapshot, reboot worker nodes, restore snapshot|:white_check_mark:|
|5|Restore snapshot after rebooting rotated worker nodes|Provision downstream K3s cluster, take etcd snapshot, rotate worker nodes, reboot worker nodes, restore snapshot|:white_check_mark:|

**VALIDATION STEPS**

**Scenario 1**
1. Provisioned a downstream RKE2 `v1.26.11+rke2r1` cluster (3 etcd, 2 cp, 3 worker) as a standard user.
2. Took an etcd snapshot.
3. Upgraded the K8s version of the downstream cluster.
4. Deployed 3 daemonsets with image `nginx:latest`.
5. Successfully restored snapshot with options cluster config, Kubernetes version and etcd.

_______

**Scenario 2**
1. Provisioned a downstream RKE2 `v1.26.11+rke2r1` cluster (3 etcd, 2 cp, 3 worker) as a standard user.
2. Took an etcd snapshot.
3. Rotated all of the worker nodes.
4. Deployed 3 daemonsets with image `nginx:latest`.
5. Successfully restored snapshot with options cluster config, Kubernetes version and etcd.

_____

**Scenario 3**
1. Provisioned a downstream K3s `v1.26.11+k3s2` cluster (3 etcd, 2 cp, 3 worker) as a standard user.
2. Took an etcd snapshot.
3. Rotated all of the worker nodes.
4. Upgraded the K8s version of the downstream cluster.
5. Deployed 3 daemonsets with image `nginx:latest`.
6. Successfully restored snapshot with options cluster config, Kubernetes version and etcd.
     - Repeated this step 3 times.

_____

**Scenario 4**
1. Provisioned a downstream K3s `v1.26.11+k3s2` cluster (3 etcd, 2 cp, 3 worker) as a standard user.
2. Took an etcd snapshot.
3. Rebooted all of the worker nodes in the backend infrastructure side.
4. Deployed 3 daemonsets with image `nginx:latest`.
5. Successfully restored snapshot with options cluster config, Kubernetes version and etcd.

______

**Scenario 5**
1. Provisioned a downstream K3s `v1.26.11+k3s2` cluster (3 etcd, 2 cp, 3 worker) as a standard user.
2. Took an etcd snapshot.
3. Rotated all of the worker nodes.
4. Rebooted all of the worker nodes in the backend infrastructure side.
5. Deployed 3 daemonsets with image `nginx:latest`.
6. Successfully restored snapshot with options cluster config, Kubernetes version and etcd.

**Comment by Oats87** [comment] 2024-01-30 20:46
I have confirmed that the following steps work for reproducing this issue (and proving that it is resolved with the new system-agent version):

1. Start up Rancher that uses `v0.3.4` system-agent
1. Create a new custom K3s cluster
1. Register a single node (all in one) with the cluster
1. Wait for the node to become active
1. When the cluster is stable, take an etcd snapshot
1. Take the original registration command that was used to initially register the node with the cluster, and wrap it with a `bash` while loop, i.e. `while true; do ${CUSTOM_REGISTRATION_COMMAND}; sleep 5; done`
1. Attempt to restore the etcd snapshot, and note that Rancher gets stuck trying at some point during the etcd restoration process
1. Upgrade to the version of rancher containing the updated system-agent version
1. Attempt to run a second restoration of etcd. Note that you may have to wait up to 5 minutes to see any progress, as the original plan delivered may start to be reconciled but fail due to the original failed etcd restoration step.

Observations:
* The while loop running the registration command will start to provide log messages stating `[INFO]  Active plan reconciliation detected. Sleeping for 5 seconds and retrying check`

**Comment by markusewalker** [comment] 2024-01-30 21:03
Reopening so that I can test the above https://github.com/rancher/rancher/issues/43964#issuecomment-1917864661 as a new scenario. I will update the earlier test result comment with the results.

**Comment by markusewalker** [comment] 2024-01-30 21:54
Updated [test plan](https://github.com/rancher/rancher/issues/43964#issuecomment-1917677442) with the new scenario. Closing issue.

**Closed by markusewalker** 2024-01-30 21:54 UTC
Labels: kind/bug, [zube]: To Triage, QA/M, team/area2, area/capr
