### ISSUE TITLE
[BUG] Global user-base + cluster owner not able to see/edit all options while editing RKE1 downstream clusters

### ISSUE THREAD

**Issue by samjustus** [rancher/rancher#40581] opened 2023-02-16 16:07 UTC
**Rancher Server Setup**
- Rancher version: 2.6.8

**Describe the bug**
Global user-base and cluster owner is not able to see/edit all options while editing RKE1 cluster through UI.

**To Reproduce**
created a downstream RKE1 as admin
created a global user-base local user
added the previously created user as cluster owner at Member Member for the RKE1 cluster
Logged into UI as the previous user created
Tried to edit the RKE1 cluster in Cluster Management
Was able to see only the snippets "Member Roles" and "Labels & Annotations" while editing

The same steps were reproduced with downstream RKE2 and could see/edit all options while editing RKE2.

Additionally, the user-base + cluster owner could delete/remove both clusters, RKE1 and RKE2.

SURE-5419

**Comment by pmatseykanets** [comment] 2023-09-14 21:10
@gaktive Can someone help me and @tomleb to take a look at this from the UI side? Thanks!

**Comment by pmatseykanets** [comment] 2023-09-18 21:03
Overall, it seems reasonable for the cluster owner to be able to edit the cluster configuration even if they are only a member of user-base global group.

As it (the UI) is today in order to properly render the Edit config UI we need the user-base role to have at least get and list permissions for nodedrivers, nodetemplates and other resources.

We don't want to add additional permissions to the user-base global role as it meant to have minimal possible priveleges.

Instead, we would like to change the UI to render and allow to edit as much as possible  of the cluster configuration with the given permissions.

**Comment by gaktive** [comment] 2023-09-21 21:03
@pmatseykanets I've asked who on UI can help out, will keep you posted.

**Comment by gaktive** [comment] 2023-11-13 19:51
Per https://github.com/rancher/dashboard/issues/9804#issuecomment-1789380695, UI has a question for backend. @samjustus who's can help Richard there?

**Comment by richard-cox** [comment] 2023-11-14 10:02
To expand on https://github.com/rancher/dashboard/issues/9804#issuecomment-1789380695

1) The Cluster owner, who has the global user-base role, would not be able to manage/see anything node or node pool related
2) API requests to edit cluster resources (excluding node or node pools) will work correctly. From memory i think some node config is included in v3/norman

**Comment by MKlimuszka** [comment] 2023-11-16 20:49
Closing this ticket in favor of https://github.com/rancher/dashboard/issues/9804

**Closed by MKlimuszka** 2023-11-16 20:49 UTC
Labels: kind/bug, priority/0, internal, area/rbac, area/authentication, team/ui, status/awaiting-ui, team/area1, JIRA

**Comment by richard-cox** [comment] 2023-11-17 12:24
I've tried to bring everything together here

## Problem Space
- Customer would like a user that has the global user-base role and a cluster cluster-owner role for an RKE1 cluster
- They would like the user to be able to manage the RKE1 cluster.
- It's been stated that the user cannot edit the cluster in the UI because certain resources are not available
  - nodetemplates. potentially nodedrivers, etc 
- In JIRA, Nancy has stated "node drivers, kontainer drivers, role templates, principals, psp templates, and psac templates are all required to view and edit the form".   
- Peter has confirmed adding these permissions renders the form correctly
- They do not want to add additional permissions to any role or user in order to manage the cluster

## Investigation
I've created a user, as per above, and see the following for collection permissions and resource count when fetched

> The user is an owner of an RKE1 cluster

|Url | Test User | Admin|
|----|---|---|
| /v3/schemas/nodetemplate | POST, GET (0 resource) | POST, GET (2 resource) |
| /v1/schemas/management.cattle.io.nodetemplate | 404 (404) | GET, blocked-POST (2 resource) |
| /v3/schemas/nodedriver | POST, GET (0 resource) | POST, GET (21 resource) | 
| /v1/schemas/management.cattle.io.nodedriver | 404 (404)| GET, blocked-POST (21 resource)s | 
| /v3/schemas/nodes | POST, GET (3 resource)  | POST, GET (4 resource)
| /v1/management.cattle.io.node |  GET, blocked-POST (3 resource)  | GET, blocked-POST (4 resource)
| /v3/schemas/nodepool |  POST, GET (1 resource) | POST, GET (1 resource)
| /v1/schemas/management.cattle.io.nodepool | GET, blocked-POST (0 resource) | GET, blocked-POST (1 resource)
| /v3/schemas/principal | GET (0 resource) | GET (0 resource)
| /v3/cloudcredentials | n/a (0 resource) | n/a (1 resource)
| /v3/schemas/roleTemplates | 404 (0 resources) | 404 (42 resources)
| /v3/kontainerdrivers | n/a (0 resource) | n/a (11 resource)
| /v1/schemas/management.cattle.io.kontainerdrivers | 404 (404) | GET, blocked-POST (11 resource)
| In addition | |
| /v3/principals/local%3A%2F%2Fuser-xglvs | 200 - null response | 200 - populated response
| /v3/principals/local%3A%2F%2Fu-q7z6d | 200 - null response | 200 - populated response (this is the principal of the test user - they cannot fech themselves)

I then added the user to a global role that had get, list on nodedrivers. This revealed the whole edit cluster config. Some parts were broken, like node template name and the membership section

There is a LOT going on here
- Users cannot fetch v1 versions of v3 resources nodetemplate, kontainerdrivers. In addition user cannot see roleTemplates
- Fetching /v3 node drivers returns an empty list, adding permissions to v1/mgmt nodedriver resource results in a /v3 non-empty list
- User cannot fetch the principal of themselves (they can fetch themselves)

## Actions
- Question - BE - What should the user be able to change when editing a cluster when they have no access to nodedriver or user based resources
- Question - BE - Should resources like node driver be available (schema is available, requests return an empty result set) when the user does not have permissions for them?
- Problem - As it stand we would remove just about everything other than editing labels/annotations. Is this acceptible?
- Task -  We also need to disable the create cluster process, given the user should not be able to (are the permissions wired in?)
