### ISSUE TITLE
kube-apiserver incomplete SAN for earlier provisioned Control Plane nodes

### ISSUE THREAD

**Issue by isavcic** [rancher/rancher#19648] opened 2019-04-16 10:07 UTC
**What kind of request is this (question/bug/enhancement/feature request):**
Bug.

**Steps to reproduce (least amount of steps as possible):**
Provision a Custom cluster
Add at least two Control Plane nodes

**Result:**
The first Control Plane node will have an incomplete SSL certificate for kube-apiserver: it will contain only its IP address/DNS record in its SAN, yet it will be balanced with the other kube-apiserver, leading to sporadic SSL errors.

**Other details that may be helpful:**
This can be confirmed by running `openssl x509 -text -noout -in /etc/kubernetes/ssl/kube-apiserver.pem | grep DNS` on the first Control Plane node. This certificate should be the same as on the last provisioned Control Plane node, yet it isn't.

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): v2.1.8
- Installation option (single install/HA): single install

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): Custom
- Machine type (cloud/VM/metal) and specifications (CPU/memory): VM (8 CPU, 16 GB RAM)
- Kubernetes version (use `kubectl version`):

```
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.0", GitCommit:"641856db18352033a0d96dbc99153fa3b27298e5", GitTreeState:"clean", BuildDate:"2019-03-26T00:04:52Z", GoVersion:"go1.12.1", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.5", GitCommit:"2166946f41b36dea2c4626f90a77706f426cdea2", GitTreeState:"clean", BuildDate:"2019-03-25T15:19:22Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}
```

- Docker version (use `docker version`):

```
Client:
 Version:           18.09.4
 API version:       1.39
 Go version:        go1.10.8
 Git commit:        d14af54
 Built:             Wed Mar 27 18:34:51 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.4
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.8
  Git commit:       d14af54
  Built:            Wed Mar 27 18:01:48 2019
  OS/Arch:          linux/amd64
  Experimental:     false
```

**Comment by superseb** [comment] 2019-04-16 10:07
Duplicate of https://github.com/rancher/rancher/issues/16151

**Closed by superseb** 2019-04-16 10:07 UTC
