### ISSUE TITLE
Simplified Chinese- container “Execute Shell” Cannot execute

### ISSUE THREAD

**Issue by chenchanglei** [rancher/rancher#9197] opened 2017-06-29 07:54 UTC
*Describe your issue here*

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v1.6.2` Cattle: `v0.181.4` UI: `v1.6.5` |
|Access|`localauth` `admin`|
|Orchestration|`Cattle`|
|Route|`stacks.index`|

**Comment by superseb** [comment] 2017-06-29 07:56
Duplicate of https://github.com/rancher/rancher/issues/8963, let me know if you disagree.

**Closed by superseb** 2017-06-29 07:56 UTC
