### ISSUE TITLE
Cannot generate kubeconfig for downstream cluster when kubeconfig-generate-token set to false

### ISSUE THREAD

**Issue by rmweir** [rancher/rancher#32880] opened 2021-05-26 02:11 UTC
**What kind of request is this (question/bug/enhancement/feature request):**
bug

**Steps to reproduce (least amount of steps as possible):**
1. Set value of kubeconfig-generate-token setting to "false".
2. Provision DO cluster. Wait until cluster is active.
3. Select "Kubeconfig" button on DO cluster's cluster page.

**Result:**
No kubeconfig is shown and errors are returned.

![image](https://user-images.githubusercontent.com/19376037/119592265-fcd7bc00-bd8c-11eb-9c60-6350316b3f38.png)

**Comment by Jono-SUSE-Rancher** [comment] 2021-07-02 20:46
@izaac is this a duplicate of #33474? Can we close this one in favor of that one? We've assigned that one to Kinara to take a look.

**Comment by izaac** [comment] 2021-07-02 20:54
@Jono-SUSE-Rancher good search skills it sounds right. It is a dupe.

**Comment by sowmyav27** [comment] 2021-07-07 17:31
Closing this one as per https://github.com/rancher/rancher/issues/32880#issuecomment-873248670

**Closed by sowmyav27** 2021-07-07 17:31 UTC
Labels: [zube]: To Triage, kind/bug-qa
