### ISSUE TITLE
RKE Cluster Templates - fail to update private registry URL when the override option is not enabled

### ISSUE THREAD

**Issue by zerotens** [rancher/rancher#37708] opened 2022-05-12 16:44 UTC
# Update 

Rancher version: v2.6.5

Steps:
- Create an RKE1 cluster template with a private registry configured without enabling any override functionality on the private registry.
- Create a cluster using this cluster template
- Create a cluster template revision and modify the credentials or URL of the private registry, notice that the override functionality is still disabled
- Edit the cluster and use the newly created cluster template revision

Results:
 New private registry settings won't be applied

Expected Results:
The new private registry settings should be applied

Screeshot of the section in the cluster template revision creation page: 
<img width="659" alt="image" src="https://user-images.githubusercontent.com/6218999/170796097-4678d613-3019-4daf-9c59-f2f71f18fb7a.png">

---
# Original Post: 

https://github.com/rancher/rancher/pull/37606/files

Repro:

1. Create RKE Template with 1 private registry
2. Apply RKE Template to a Cluster
3. Modify RKE Template and add a second registry or modify the old and make sure override is disabled
4. New Registry won't be applied

Code Issue

Loading old registry details from cluster into registryMap:
https://github.com/rancher/rancher/blob/c4d59fa88e2313e1446ba542a21c39e15a17f375/pkg/api/norman/store/cluster/cluster_store.go#L436-L440

Old registry details from cluster are used to override the new private registry details in dataFromTemplate
Settings from the cluster template revision in dataFromTemplate are gone and old credentials are used
https://github.com/rancher/rancher/blob/c4d59fa88e2313e1446ba542a21c39e15a17f375/pkg/api/norman/store/cluster/cluster_store.go#L518-L525

@jiaqiluo Could you have a look?

**Comment by jiaqiluo** [comment] 2022-05-12 17:56
hi @zerotens  In your case of editing an existing cluster, the values already applied to the cluster take precedence over the ones in the cluster template. So what you see is the expected result.

**Comment by zerotens** [comment] 2022-05-12 18:00
Hi @jiaqiluo,

> hi @zerotens In your case of editing an existing cluster, the values already applied to the cluster take precedence over the ones in the cluster template. So what you see is the expected result.

So editing the private registry is not possible anymore? Are you totally sure?
I really don't think this is the wanted behaviour and does not make any sense to me.

**Comment by jiaqiluo** [comment] 2022-05-12 18:04
@zerotens  To change the private registry of an existing cluster, you can edit the cluster and change the values, instead of changing the cluster template.

**Comment by zerotens** [comment] 2022-05-12 18:10
> @zerotens To change the private registry of an existing cluster, you can edit the cluster and change the values, instead of changing the cluster template.

@jiaqiluo not if the cluster was created by an RKE1 Template and the values are not selected to be overriden in the rke template section.
Then you can't set the values on the Edit Cluster Page and the bug occurs.

**Comment by jiaqiluo** [comment] 2022-05-12 18:47
@zerotens  I was wrong about the precedence: in fact, the values from the cluster template will overwrite whatever the values the user set. I just tested in a 2.6.3  setup: although the UI still doesn't allow me to change the value, the backend actually applies the new values from the new template revision.

**Comment by zerotens** [comment] 2022-05-12 19:01
> @zerotens I was wrong about the precedence: in fact, the values from the cluster template will overwrite whatever the values the user set. I just tested in a 2.6.3 setup: although the UI still doesn't allow me to change the value, the backend actually applies the new values from the new template revision.
 
@jiaqiluo 

> I think this could be a UI bug where after the field is changed to editable in the cluster template revision, UI still does not show the field as ediable.

Ok if you set the field to be editable then it would work and edit the cluster manually then it would work.

Actually private registries would be then the only values you can't update this way in cluster revision templates, due to the logic you implemented.
Everything else and also every other overrideable value can be done via default values from the cluster revision template.

What speaks against making private registries behave like every other value?

**Comment by jiaqiluo** [comment] 2022-05-13 01:02
I think I figured out what happens here: the problem comes from the UI, not the backend.

Currently, when we click and open the edit page of an RKE cluster, the UI will GET the cluster object from the backend and show the applied values of the cluster in the UI; If we select a new RKE cluster template revision, UI will not update the values it shows, in other words, it will keep the applied values and ignore the ones in the cluster template revision.   Now if we click the save button, none of the new values from the new cluster template revision will be applied because UI sends the old existing applied values back to the backend.  
In the case where the field was `allow user overwrite` original but not in the new revision, UI will drop that field's value when it sends the PUT request to the backend. 

I kind of understand why the UI behaves this way: because UI does not know if user has changed the currently showing values or not, instead of losing users' modifications,  it decides to preserve whatever the current values are. 
However, this causes 2 problems:
1. new values in the new cluster template revision are not applied
2. if the field is not marked as `allow user overwrite`, user will never have the chance to correct the value even if he knows what the new value is 

I will bring this issue to the team.

**Comment by zerotens** [comment] 2022-05-13 03:51
@jiaqiluo 
Thank you very much for looking into this deeply.
Depending on my free time i will try something out and if it works i will create an PR.

**Comment by zerotens** [comment] 2022-05-13 17:33
@jiaqiluo 

I created an pull request which fixes my use case.

But you are totally right there is more broken in case the old cluster template revision and the newly selected revision have changes in the override options.

Those overrides won't be shown because the web ui does not ask the server what override options are enabled for the selected cluster template revision.

**Comment by jiaqiluo** [comment] 2022-05-27 23:17
### Root cause
For REK clusters that are created from a cluster template revision,  the private registry info ( url, username, or password) from the existing cluster is always used when updating the cluster, this causes the problem in this very specific scenario: if the private registry info is changed in the newly-applied cluster template revision AND those fields are not marked as "allow user override", the new values will never be applied. 

### What was fixed, or what changes have occurred
The private registry info from the existing cluster is used only when the "allow user override" is enabled for the private registry info in the cluster template revision; otherwise, apply the values from the revision. 

### Areas or cases that should be tested
updating the existing rke cluster in the above-mentioned scenario.

### What areas could experience regressions?
 The private registry setting on the RKE cluster. 

### Are the repro steps accurate/minimal?
yes

**Comment by markusewalker** [comment] 2022-06-03 18:43
Verified on `v2.6-head` https://github.com/rancher/rancher/commit/79a3bcba901add6249cfbb6d9d4961599553f8da.

**ENVIRONMENT DETAILS**
- Rancher HA
- Rancher version:
     - Verified version `v2.6-head` https://github.com/rancher/rancher/commit/79a3bcba901add6249cfbb6d9d4961599553f8da
- Browser: Chrome

**TEST RESULT**
PASS

VERIFICATION STEPS
1. Setup Rancher and login to the UI in a browser.
2. Created a standard user and login to Rancher as that user.
3. Go to Cluster Management and created a new downstream node driver RKE1 cluster.
     - When creating, in the `Private Registry` section, checked `Enabled`:
<img width="1146" alt="image" src="https://user-images.githubusercontent.com/52591819/171926366-a302d4a1-b9f1-4a90-b828-260c89892990.png"> 
4. After the cluster successfully provisions, edit the config and head back to `Private Registry`. Create test values in url, user and password.
5. Verified that the new registry settings were properly set:
<img width="1143" alt="image" src="https://user-images.githubusercontent.com/52591819/171926491-ae1b5b67-0c28-40aa-ae12-59e49050e1eb.png">

Cluster, correctly, shows as not `Active` due to me putting test values that are not recognizable. But the issue of the options not staying has been verified to be addressed, so closing this issue.

**Closed by markusewalker** 2022-06-03 18:43 UTC
Labels: [zube]: QA Working, QA/M, feature/cluster-templates, team/area2
