### ISSUE TITLE
[CIS] evaluate the variables in the results/report

### ISSUE THREAD

**Issue by leodotcloud** [rancher/rancher#25161] opened 2020-01-29 22:45 UTC

**Comment by maggieliu** [comment] 2020-03-12 16:23
Moving it out to 2.4.x. The problem is that In the description of the test, there are variables like $apiserverconf which are not interpreted. This can be fixed by changing the code because most of those variables don't make sense in context of RKE.

**Comment by deniseschannon** [comment] 2020-03-20 22:06
I'd prefer not to re-write the text that comes directly from the CIS benchmarks as this is a huge maintenance on our end.

Anything that requires changes/remediation from RKE would be covered in the hardening guide which is what we ask users to follow to get a hardened cluster.

**Closed** 2020-03-20 22:06 UTC
Labels: [zube]: Next Up, area/scan-tool
