### ISSUE TITLE
AKS Cluster Deployment fails in South Central US

### ISSUE THREAD

**Issue by jambajaar** [rancher/rancher#21636] opened 2019-07-19 01:44 UTC
Rancher version:
v2.2.5

Type:
Bug

Description:
deployment of AKS cluster on Azure South Central US failed w/ error below:

Operationalinsights.WorkspacesClient#CreateOrUpdate: Failure sending request: StatusCode=0 -- Original Error: autorest/azure: Service returned an error. Status=403 Code="RequestDisallowedByPolicy" Message="Resource 'aksdevinternal01-southcentralus-rg-EUS' was disallowed by policy. 

It seems like Rancher is targeting resource group on Azure (AKS) Eastern US for South Central US deployment

**Comment by davidnuzik** [comment] 2019-07-19 16:05
Version: v2.2.5

I wasn't able to reproduce the issue. Keep in mind this doesn't invalidate your claims -- it's possible I couldn't reproduce due to some other factor(s). With our QA test account on Azure I was successfully able to bring up an Azure AKS cluster by picking the South Central US region.

The HTTP/API appears correct to me so frontend looks good. When I checked on the Azure web console the cluster and VMs are created in the correct region, South Central US. I didn't observe the error mentioned in the UI nor in the rancher logs.

I tested with a single-node rancher running v2.2.5 release.

Some guesses as to what may have gone wrong:
- Our Azure accounts differ somehow (not sure how/where)
- On the client side, browser wasn't fully updated (such as if this was an upgrade) and so for some reason UI has some stale cached files and so didn't provision correctly.

**Comment by davidnuzik** [comment] 2019-07-19 16:30
What was the exact "Cluster Resource Group" name you supplied as part of creating the AKS cluster? Was this done through the UI or API?

**Comment by trananthony** [comment] 2019-07-23 16:52
We are using an existing RG that is empty.  The app id has ownership of the RG but not the subscription.

**Comment by trananthony** [comment] 2019-07-23 17:06
aks cluster deployment through the UI

**Comment by davidnuzik** [comment] 2019-07-26 19:44
I reproduced the issue.

v2.2.5
1. Using Azure webconsole / cli create a Resource Group, make the location South Central US. (It should be empty).
2. Create an AKS cluster, use the name of the RG created in step 1.

Result:
The Log Analytics workspace and Solution objects are in East US region. They should be in the South Central US region...
![image](https://user-images.githubusercontent.com/45179589/61977336-0af6fe80-afa3-11e9-80ce-51f9e06ed8fa.png)

**Comment by davidnuzik** [comment] 2019-07-26 20:54
I took a deeper look, again with v2.2.5 although all versions should currently be affected. Here is some additional information:

**_Scenario 1:_**
_Have user create the RG in Azure, then use Rancher to create AKS cluster with this RG_
Rancher does the following:

Puts Kubernetes service and logging analytics and solution in my RG called "david-icreated" that I created.
![image](https://user-images.githubusercontent.com/45179589/61980681-4fd36300-afac-11e9-9c14-0363c476066d.png)
(and as mentioned before 2 are in the wrong region)

Puts the rest of the resources in a rancher-generated RG called "MC_david-icreated_c-hd5jb_southcentralus" for some reason:
![image](https://user-images.githubusercontent.com/45179589/61980740-74c7d600-afac-11e9-95a2-d3413b9c7133.png)
These are in the correct region, but wrong RG.

Below shows the two RG's created:
![image](https://user-images.githubusercontent.com/45179589/61980865-ca03e780-afac-11e9-884c-784eeffe545e.png)



**_Scenario 2:_**
_Have Rancher create the RG (does not pre-exist in Azure)_
Rancher does the following:

This also happens when I create via the UI and plugin RG name of "david-ranchermade" it does the same thing as Scenario 1.
![image](https://user-images.githubusercontent.com/45179589/61980814-9f199380-afac-11e9-9142-832429f5c47d.png)

**Comment by dramich** [comment] 2019-07-30 00:29
This was due to the mapping in KE AKS driver being old as seen [here](https://github.com/rancher/kontainer-engine/commit/cedd75d7b076a3e848e933816bf7f9b3d3f1deaf#diff-fdee2f189d794fc3e135129d93b4d373L952)

**Comment by deniseschannon** [comment] 2019-07-30 17:09
Master should not have this issue as it was already fixed previously by @daxmc99. This issue is to track the fix in the 2.2 line.

**Comment by davidnuzik** [comment] 2019-07-30 17:46
The fix here: https://github.com/rancher/kontainer-engine/pull/174 updates regions for AKS. This resolves the issue in v2.2-head (v2.2.7). I also checked in master-head (v2.3) to do a quick sanity check to ensure the issue does not exist in this version.

Version: 
master-head (7/30/19) (quick check to ensure issue does not exist in this version)

- Confirmed ALL objects are in South Central US region (just like pictured below in v2.2-head validation).

Version: 
v2.2-head (7/30/19) (v2.2.7) (latest ui-index `https://releases.rancher.com/ui/2.2.92/index.html`)

- Create AKS cluster, set region to "South Central US"
- Inspect HTTP ensure we send location: "southcentralus"
- Review Azure resource group creation, ensure that for both resource groups ALL resources are in the South Central US region.

This is now fixed, before the Solution and Log analytics workspace objects would be in the East US region.

As we can see all objects are in the South Central US region now in v2.2-head
![image](https://user-images.githubusercontent.com/45179589/62151361-00937800-b2b5-11e9-947a-ca4803ea0015.png)
![image](https://user-images.githubusercontent.com/45179589/62151386-0a1ce000-b2b5-11e9-83c5-849b62c7c364.png)

**Closed by davidnuzik** 2019-07-30 17:46 UTC
Labels: [zube]: To Test, internal, kind/bug, team/az

**Comment by trananthony** [comment] 2019-08-08 18:03
Updated to v2.2.7 has not resolved the issue where the worker nodes were not deployed on an existing empty resource group.  Rancher did create another resource group where the worker nodes resided, and only resource type "Log Analytics workspace", "Kubernetes service", and "Solution" were created on existing resource group.

**Comment by dramich** [comment] 2019-08-08 18:13
@trananthony Can you open a new issue with more details? Your setup, what you are doing, etc.
