### ISSUE TITLE
How to config ApiServer?

### ISSUE THREAD

**Issue by agasbzj** [rancher/rancher#13463] opened 2018-05-14 07:28 UTC
I noticed that the ApiServer is a single docker container started by rancher agent, who's name is **kube-apiserver**.
My question is how to modify the args of it? (e.g. add a **--requestheader-username-headers** to enable auth proxy). Maybe we can stop that container and run it manually again with the new args, but it seems not a good practice.
And I wonder why not run the ApiServer as a kubernetes deployment? It will be easier to config if you do so.

I love Rancher2.
Thank you.

**Rancher versions:**
rancher/server or rancher/rancher: 2.0
rancher/agent or rancher/rancher-agent: 2.0

**Comment by superseb** [comment] 2018-05-14 07:33
Duplicate of https://github.com/rancher/rancher/issues/13076

Only possible using RKE and import or using the API for now.

**Closed by superseb** 2018-05-14 07:33 UTC

**Comment by Angelinsky7** [comment] 2018-05-30 06:03
@superseb please could you explain how we can do that with 

> using the API for now

which api ? rancher ? kubernetes ? how ? (i'm interested with --max-pods)
thanks a lot for you great support !

**Comment by superseb** [comment] 2018-05-30 19:42
https://github.com/rancher/rke/#extra-args-and-binds
