### ISSUE TITLE
[BUG] SUSE Support Matrix is missing Rancher 2.8.0

### ISSUE THREAD

**Issue by gavinmcfall** [rancher/rancher#43805] opened 2023-12-18 08:01 UTC
https://www.suse.com/suse-rancher/support-matrix/all-supported-versions/

Latest this goes to is 2.7.9

2.8.0 has been out for 2 weeks now.

Expected:

The support Matrix is update AT release

**Comment by aanjaneyam** [comment] 2023-12-20 00:43
Even though support matrix has not been updated yet. Is there any information available somewhere on which version of k3s does rancher 2.8.0 support. Does it support latest k3s version v1.28.4+k3s2.

**Comment by snasovich** [comment] 2024-01-16 02:59
@gavinmcfall , thank you for reporting this issue.
Please note that the support matrix is only updated once Rancher release is marked as stable (see https://ranchermanager.docs.rancher.com/getting-started/installation-and-upgrade/resources/choose-a-rancher-version#helm-chart-repositories) - this has not happened yet with v2.8.0. In fact, v2.8.0 will not be promoted to `rancher-stable` due to some regressions that slipped into the first release of the new minor version. These issues are getting fixed in v2.8.1 tracked in https://github.com/rancher/rancher/milestone/338. When/if v2.8.1 is promoted to stable support matrix will be published.

Also, as noted by @Martin-Weiss v2.8.0 (and upcoming v2.8.1) don't yet support v1.28 - this is tracked in https://github.com/rancher/rancher/issues/43109 for inclusion in later release.

Closing this issue.

**Closed by snasovich** 2024-01-16 02:59 UTC
Labels: kind/bug
