### ISSUE TITLE
2.0.8 / 2.0.7 Can't get any storage class and/or volume working

### ISSUE THREAD

**Issue by iocaste** [rancher/rancher#15244] opened 2018-08-27 09:32 UTC
**Rancher versions:**
rancher/server or rancher/rancher: 2.0.8
rancher/agent or rancher/rancher-agent: 2.0.8

**Infrastructure Stack versions:**
healthcheck:
ipsec:
network-services:
scheduler:
kubernetes (if applicable):

**Docker version: (`docker version`,`docker info` preferred)**
17.03.2

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
16.04.5 LTS (Xenial Xerus)

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
DO

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
single node rancher

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**
Kubernetes

**Steps to Reproduce:**

* Create cluster with digitalocean using built in plugin and add 3 nodes, use 16.04 ubuntu.
* OR Manually create 3 nodes using digitalocean, ubuntu 16.04 and docker 17.03.2

**NFS Share** (Only method that was able to write)
If using NFS share (Volume without class)
1. Add volume with nfs server. Example: 
Name: mysql-volume-0
Path: /nfs/mysql-volume-0/_data/
2. Create workload, create claim and attach to volume.

**DigitalOcean CSI plugin**
1. Add feature-gates: MountPropagation=true to cluster
2. Add do secret
3. Install class using kubectl apply -f https://raw.githubusercontent.com/digitalocean/csi-digitalocean/master/deploy/kubernetes/releases/csi-digitalocean-v0.1.4.yaml
4. Add workload, create claim using DO class

**Longnorn using CSI**
1. Add feature-gates: MountPropagation=true to cluster
2. Get longhorn 0.3.0 from catalog
3. Add workload, create claim using longhorn class

**Longnorn using Flexvolume**
1. Get longhorn 0.3.0 from catalog
2. Add workload, create claim using longhorn class

**NFS provisioner**
1. Add nfs provisioner from catalogg
2. Add workload, create claim using nfs-provisioner class

**Results:**

**NFS Share**
Directory "/nfs/mysql-volume-0/_data/" inside nfs server /nfs/ won't be created when workload is up. I have to manually mkdir -p /nfs/mysql-volume-0/_data/ and chmod 777 /nfs and chown 1001:nogroup so that nodes could write to that directory.

I don't know why nodes writes as 1001 user.

**DigitalOcean CSI plugin**
Volume isn't writable. When starting mysql container logs are giving:
```Error executing 'postInstallation': EACCES: permission denied, mkdir '/bitnami/mysql'```

**Longnorn using CSI**
Volume isn't writable. When starting mysql container logs are giving:
```Error executing 'postInstallation': EACCES: permission denied, mkdir '/bitnami/mysql'```

**Longnorn using Flexvolume**
Volume isn't writable. When starting mysql container logs are giving:
```Error executing 'postInstallation': EACCES: permission denied, mkdir '/bitnami/mysql'```

**NFS provisioner**
Volume isn't writable. When starting mysql container logs are giving:
```Error executing 'postInstallation': EACCES: permission denied, mkdir '/bitnami/mysql'```

For workloads i've tried using images: bitnami/mysql:8.0.12-debian-9-r16 and mysql:latest
I have tried everything with Ubuntu 16.04 and RancherOS, same. Workloads can't write to volume.

Example of workload yaml file:

```
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "2"
    field.cattle.io/creatorId: user-j9z8q
  creationTimestamp: 2018-08-27T08:45:05Z
  generation: 6
  labels:
    workload.user.cattle.io/workloadselector: deployment-pool-locations-mysql
  name: mysql
  namespace: pool-locations
  resourceVersion: "8369"
  selfLink: /apis/apps/v1beta2/namespaces/pool-locations/deployments/mysql
  uid: 7f0b3d6d-a9d5-11e8-b78f-e6f08e50fef6
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      workload.user.cattle.io/workloadselector: deployment-pool-locations-mysql
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        workload.user.cattle.io/workloadselector: deployment-pool-locations-mysql
    spec:
      affinity: {}
      containers:
      - env:
        - name: MYSQL_DATABASE
          value: pool_locations
        - name: MYSQL_PASSWORD
          value: prod_78vZ78X4dxKvquMF
        - name: MYSQL_ROOT_PASSWORD
          value: prod_DuLsua6mJXaQa8ZZ
        - name: MYSQL_USER
          value: pool_locations
        image: bitnami/mysql:8.0.12-debian-9-r16
        imagePullPolicy: Always
        name: mysql
        resources: {}
        securityContext:
          allowPrivilegeEscalation: true
          privileged: true
          readOnlyRootFilesystem: false
          runAsNonRoot: false
        stdin: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        tty: true
        volumeMounts:
        - mountPath: /bitnami
          name: mysql-claim-0
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: mysql-claim-0
        persistentVolumeClaim:
          claimName: mysql-claim-0
status:
  conditions:
  - lastTransitionTime: 2018-08-27T08:45:05Z
    lastUpdateTime: 2018-08-27T09:33:16Z
    message: ReplicaSet "mysql-8496599795" is progressing.
    reason: ReplicaSetUpdated
    status: "True"
    type: Progressing
  - lastTransitionTime: 2018-08-27T09:33:39Z
    lastUpdateTime: 2018-08-27T09:33:39Z
    message: Deployment does not have minimum availability.
    reason: MinimumReplicasUnavailable
    status: "False"
    type: Available
  observedGeneration: 6
  replicas: 2
  unavailableReplicas: 2
  updatedReplicas: 1
```

**Comment by relzhong** [comment] 2018-12-26 04:17
Duplicate of #14836,  leave mount subpath empty can help.

**Comment by deniseschannon** [comment] 2019-04-12 00:09
Closing in favor of #14836

**Closed by deniseschannon** 2019-04-12 00:09 UTC
Labels: area/storage, status/investigate
