### ISSUE TITLE
A Network error is seen in Rancher when logging in after deploying rancher, and user has to refresh page to get to Home page

### ISSUE THREAD

**Issue by sowmyav27** [rancher/rancher#34038] opened 2021-08-07 16:16 UTC
**Rancher Server Setup**
- Rancher version: 2.6-head commit id: `0ab00d`
- Installation option (Docker install/Helm Chart): docker install

**Describe the bug**
Sometimes on logging in Network error is seen in Rancher, and user has to refresh page to get to Home page

**To Reproduce**

- Deploy rancher 2.6-head
- Find initial password from logs and login
- Change password and set to a new one
- User faces a Network error page

<img width="1371" alt="Screen Shot 2021-08-07 at 9 14 00 AM" src="https://user-images.githubusercontent.com/26032343/128606701-575e2ed2-2039-44e1-a269-c76af549ddd1.png">

To get out of this, user has to refresh the page

**Comment by deniseschannon** [comment] 2021-08-09 03:57
Is there anything captured in the console in order to reproduce this? 

How often is this happening @sowmyav27 ?

**Comment by sowmyav27** [comment] 2021-08-09 04:29
Checked rancher logs, did not see anything obvious. I would have faced it a couple of times during my validations. I can try a few more times to see if i can reproduce this issue.

**Comment by sowmyav27** [comment] 2021-08-09 05:07
Error seen in rancher logs:
```
2021/08/09 05:04:45 [INFO] certificate CN=dynamic,O=dynamic signed by CN=dynamiclistener-ca,O=dynamiclistener-org: notBefore=2021-08-09 05:03:38 +0000 UTC notAfter=2022-08-09 05:04:45 +0000 UTC
2021/08/09 05:04:45 [INFO] certificate CN=dynamic,O=dynamic signed by CN=dynamiclistener-ca,O=dynamiclistener-org: notBefore=2021-08-09 05:03:38 +0000 UTC notAfter=2022-08-09 05:04:45 +0000 UTC
2021/08/09 05:04:45 [INFO] certificate CN=dynamic,O=dynamic signed by CN=dynamiclistener-ca,O=dynamiclistener-org: notBefore=2021-08-09 05:03:38 +0000 UTC notAfter=2022-08-09 05:04:45 +0000 UTC
2021/08/09 05:04:45 [INFO] Updating TLS secret for serving-cert (count: 6): map[field.cattle.io/projectId:local:p-zz5l5 listener.cattle.io/cn-127.0.0.1:127.0.0.1 listener.cattle.io/cn-172.17.0.2:172.17.0.2 listener.cattle.io/cn-<>:<> listener.cattle.io/cn-localhost:localhost listener.cattle.io/cn-rancher.cattle-system:rancher.cattle-system listener.cattle.io/fingerprint:SHA1=<>]
2021/08/09 05:04:45 [INFO] Active TLS secret serving-cert (ver=3294) (count 6): map[field.cattle.io/projectId:local:p-zz5l5 listener.cattle.io/cn-127.0.0.1:127.0.0.1 listener.cattle.io/cn-<>:172.17.0.2 listener.cattle.io/cn-<>:<> listener.cattle.io/cn-localhost:localhost listener.cattle.io/cn-rancher.cattle-system:rancher.cattle-system listener.cattle.io/fingerprint:SHA1=<>]
2021/08/09 05:04:47 [ERROR] Unknown error: Post "https://127.0.0.1:6443/apis/management.cattle.io/v3/namespaces/user-hvlqd/preferences?timeout=15m0s": context canceled
2021/08/09 05:04:47 [ERROR] Unknown error: Get "https://127.0.0.1:6443/api/v1/namespaces?includeObject=Object&limit=100000&timeout=15m0s": context canceled
2021/08/09 05:04:47 [ERROR] Error during subscribe write tcp <>:443-><>:61543: use of closed network connection
```

**Comment by sowmyav27** [comment] 2021-08-18 13:32
This seems to happen on a docker install, immediately after the rancher server password is set.

**Comment by paynejacob** [comment] 2021-08-23 21:41
Looking into this further the synthetic load makes this easier to detect but the actual issue is rancher is replacing it's ingress certs around the same that users finish updating their password.  Any open requests when the cert is updated fail.    I think the synthetic load just make this process take longer so it is easier to refresh the ui during the transition.

**Comment by Auston-Ivison-Suse** [comment] 2021-11-10 02:09
**Setup for Reproduction**
- Rancher version: v2.6.1 and v2.6.2
- Installation option: Docker install
**Setup for Validation **
- Rancher version: 2.6-head (17f2546) 

**Steps for Reproduction and Validation**
1. Install rancher using docker running the following command with the version changed as needed:
```
docker run -d --restart=unless-stopped \
  -p 80:80 -p 443:443 \
  --privileged \
rancher/rancher:v2.6-head
```
2. Go to the URL of the rancher installation example: public ip-address ec2 assigns.
3. Follow instructions for docker install to login. 
4. Observer the error

**Notes** 
It didn't happen every time I tried on previous versions, but I was able to replicate the issue, and observed no network error when on commit (17f2546)

**Comment by c0h1b4** [comment] 2022-02-15 18:29
Why closing?
Just happened to me today with the latest version of rancher.
There is absolutely no fix on this thread and you close it????

**Comment by davidnuzik** [comment] 2022-02-16 17:00
@Auston-Ivison-Suse was following correct process here. The issue is resolved in v2.6.3 of Rancher. I do not see this issue any longer as well. Both with single-node docker set up and HA rancher setup.

@c0h1b4 if you are still seeing this issue could you file a new bug with details about your Rancher setup? My thinking is maybe there is something different about our environments that might be causing the issue still for you? Details on how your certs are set up with Rancher would help as well.

**Comment by davidnuzik** [comment] 2022-02-23 23:46
Actually - reopening this one. This was fixed a while back and I had not seen the issue very recently. Now - we seem to have a regression - today on v2.6-head (`8c785a1`) I see this happen more often. I'm not sure when this came back up on v2.6-head.

![image](https://user-images.githubusercontent.com/45179589/155429589-5090f2b1-987e-4969-b632-fecd76058f67.png)

I'm not sure what could have changed - the PRs to update the dynamiclistener fixed this prior - I never saw the issue before and don't see in on v2.6.3 release.

**Comment by cbron** [comment] 2022-03-03 18:56
Bumping to 2.6.5 given timeline and it being sporadic.

**Comment by cbron** [comment] 2022-04-01 23:42
We are having trouble reproducing this one, moving back to 2.6.x until we get more firm reproduction steps.

**Comment by einsteinarbert** [comment] 2022-11-24 10:01
In my context, my physical server has been error: out of memory error => k8s don't have enough ram for run Rancher and all other deployment.

**Comment by cbron** [comment] 2023-10-30 19:47
Closing due to inactivity and being unable to repro

**Closed by cbron** 2023-10-30 19:47 UTC
Labels: priority/2, kind/bug-qa, [zube]: Reopened, team/area1
