### ISSUE TITLE
Rancher Cluster Agent, Node Agent might get hung when something goes wrong in the middle of WebSocket Session Handshake

### ISSUE THREAD

**Issue by ukinau** [rancher/rancher#21117] opened 2019-06-25 15:43 UTC
**What kind of request is this (question/bug/enhancement/feature request):**
bug

**Steps to reproduce (least amount of steps as possible):**
Honestly we are not so sure how we can cause this situation in detail...
but let me describe as detail as possible.

0. Deploy rancher-server behind Nginx which enabled Web Socket Session Proxy
1. Make sure all agents established websocket session with rancher-server
2. Force Shutdown node running rancher-server
     -> Point: We should not give a time for server to send RST/FIN TCP Packet
3. rancher-server will be deployed on other nodes by kubernetes
4. some agent which **was in the middle of Web Socket Handshake** at that time get hung without establishing Web Socket Session and keep tcp connection from **client point of view**.
    (our case actually saw 400 out of 900 node agent get hung because of that)
5. other agent which was not in the middle of Web Socket Handshake correctly at that time retried to establish web socket session with new rancher-server and then succeeded in establishing Websocket Session (our case 500 out of 900 nodes) 

**Result:**

All node-agent which might get hung show following logs as a last log. 
At least we observed it hung longer than 1 day.
```
time="2019-06-23T03:41:34Z" level=info msg="Connecting to wss://<rancher endpoint>/v3/connect with token  XXX"
time="2019-06-23T03:41:34Z" level=info msg="Connecting to proxy" url="wss://<rancher endpoint>/v3/connect"
```
If node-agent succeeded in establishing web socket session, we should be able to see `Starting plan monitor` as a last log (https://github.com/rancher/rancher/blob/master/pkg/agent/main.go#L166-L185), from this log, we can judge this node-agent didn't establish Web Socket Session. We also checked with metrics introduced by https://github.com/rancher/norman/pull/285 . 

We actually checked TCP session if this node-agent succeeded in establishing or not. It does actually.

```
# docker inspect 88bbc6467217|grep Pid
            "Pid": 126715,
            "PidMode": "",
            "PidsLimit": 0,
# lsof -p 126715
COMMAND    PID USER   FD      TYPE             DEVICE SIZE/OFF      NODE NAME
agent   126715 root  cwd       DIR              252,3      285       131 /
agent   126715 root  rtd       DIR              252,3      285       131 /
agent   126715 root  txt       REG              252,3 65785952  10669724 /usr/bin/agent
agent   126715 root    0r     FIFO                0,9      0t0 301300830 pipe
agent   126715 root    1w     FIFO                0,9      0t0 301300831 pipe
agent   126715 root    2w     FIFO                0,9      0t0 301300832 pipe
agent   126715 root    3u     unix 0xffff89a08a7c0800      0t0 301301866 /tmp/log.sock
agent   126715 root    4u  a_inode               0,10        0      6092 [eventpoll]
agent   126715 root    5u     IPv4          354317824      0t0       TCP <client>37162->LB:https (ESTABLISHED)
agent   126715 root    8u     unix 0xffff89a0f0f4f000      0t0 301299652 socket
```

That's why we can imagine something is happening in the middle of Web Socket Session Handling and also if we send abort signal to node-agent, we could get following stack trace 

```
docker kill  -s ABRT

SIGABRT: abort
PC=0x45a5c1 m=0 sigcode=0
 
goroutine 0 [idle]:
runtime.futex(0x42c7000, 0x80, 0x0, 0x0, 0x7fff00000000, 0x0, 0x0, 0x0, 0x7ffffe8be470, 0x40a7f2, ...)
    /usr/local/go/src/runtime/sys_linux_amd64.s:531 +0x21
runtime.futexsleep(0x42c7000, 0x0, 0xffffffffffffffff)
    /usr/local/go/src/runtime/os_linux.go:46 +0x4b
runtime.notesleep(0x42c7000)
    /usr/local/go/src/runtime/lock_futex.go:151 +0xa2
runtime.stopm()
    /usr/local/go/src/runtime/proc.go:2016 +0xe3
runtime.findrunnable(0xc00005c000, 0x0)
    /usr/local/go/src/runtime/proc.go:2487 +0x4dc
runtime.schedule()
    /usr/local/go/src/runtime/proc.go:2613 +0x13a
runtime.park_m(0xc000001680)
    /usr/local/go/src/runtime/proc.go:2676 +0xae
runtime.mcall(0x0)
    /usr/local/go/src/runtime/asm_amd64.s:299 +0x5b
 
goroutine 1 [IO wait, 1966 minutes]:
internal/poll.runtime_pollWait(0x7f8ed0007af0, 0x72, 0xc0011d31a0)
    /usr/local/go/src/runtime/netpoll.go:173 +0x66
internal/poll.(*pollDesc).wait(0xc00075b498, 0x72, 0xffffffffffffff00, 0x2840b00, 0x41036d8)
    /usr/local/go/src/internal/poll/fd_poll_runtime.go:85 +0x9a
internal/poll.(*pollDesc).waitRead(0xc00075b498, 0xc0000f9800, 0x400, 0x400)
    /usr/local/go/src/internal/poll/fd_poll_runtime.go:90 +0x3d
internal/poll.(*FD).Read(0xc00075b480, 0xc0000f9800, 0x400, 0x400, 0x0, 0x0, 0x0)
    /usr/local/go/src/internal/poll/fd_unix.go:169 +0x179
net.(*netFD).Read(0xc00075b480, 0xc0000f9800, 0x400, 0x400, 0xc0000f9800, 0x0, 0x400)
    /usr/local/go/src/net/fd_unix.go:202 +0x4f
net.(*conn).Read(0xc00000c1d8, 0xc0000f9800, 0x400, 0x400, 0x0, 0x0, 0x0)
    /usr/local/go/src/net/net.go:177 +0x68
crypto/tls.(*block).readFromUntil(0xc0007f6030, 0x283e800, 0xc00000c1d8, 0x5, 0xc00000c1d8, 0x5ae3df)
    /usr/local/go/src/crypto/tls/conn.go:492 +0x89
crypto/tls.(*Conn).readRecord(0xc000d35c00, 0x25af616, 0xc0011d34f0, 0x0)
    /usr/local/go/src/crypto/tls/conn.go:593 +0xdd
crypto/tls.(*Conn).readHandshake(0xc000d35c00, 0xc000bbe116, 0xc000bbe180, 0xb3, 0xb3)
    /usr/local/go/src/crypto/tls/conn.go:955 +0x9a
crypto/tls.(*clientHandshakeState).handshake(0xc0011d36e0, 0xc000986780, 0x0)
    /usr/local/go/src/crypto/tls/handshake_client.go:191 +0xaa
crypto/tls.(*Conn).clientHandshake(0xc000d35c00, 0x25af690, 0xc000d35d20)
    /usr/local/go/src/crypto/tls/handshake_client.go:168 +0x397
crypto/tls.(*Conn).Handshake(0xc000d35c00, 0x0, 0x0)
    /usr/local/go/src/crypto/tls/conn.go:1272 +0xf1
github.com/rancher/rancher/vendor/github.com/gorilla/websocket.(*Dialer).Dial(0xc000862a40, 0xc000f28440, 0x32, 0xc00079ba10, 0x0, 0x0, 0x0, 0x0)
    /go/src/github.com/rancher/rancher/vendor/github.com/gorilla/websocket/client.go:217 +0xa61
github.com/rancher/rancher/vendor/github.com/rancher/norman/pkg/remotedialer.connectToProxy(0xc000f28440, 0x32, 0xc00079ba10, 0x25aedc8, 0x0, 0xc00079ba40, 0x0, 0x0)
    /go/src/github.com/rancher/rancher/vendor/github.com/rancher/norman/pkg/remotedialer/client.go:27 +0x127
github.com/rancher/rancher/vendor/github.com/rancher/norman/pkg/remotedialer.ClientConnect(0xc000f28440, 0x32, 0xc00079ba10, 0x0, 0x25aedc8, 0xc00079ba40)
    /go/src/github.com/rancher/rancher/vendor/github.com/rancher/norman/pkg/remotedialer/client.go:15 +0x67
main.run(0x24c9972, 0xf)
    /go/src/github.com/rancher/rancher/pkg/agent/main.go:208 +0x5a3
main.main()
    /go/src/github.com/rancher/rancher/pkg/agent/main.go:49 +0x9b
```

You can see following line which indicate it wait for WebSocket Session Handshake to be finished 

`github.com/rancher/rancher/vendor/github.com/rancher/norman/pkg/remotedialer.connectToProxy(0xc000f28440, 0x32, 0xc00079ba10, 0x25aedc8, 0x0, 0xc00079ba40, 0x0, 0x0)`

**Other details that may be helpful:**

We actually investigate bit more about this situation and we noticed that gorila's web socket session client actually have infinite HandshakeTimeout at default (https://github.com/rancher/rancher/blob/master/vendor/github.com/gorilla/websocket/client.go#L181-L189, https://golang.org/pkg/net/#Dialer) .

Rancher actually didn't specify `HandshakeTimeout ` in Dialer as following, that's why node-agent adapt infinite HandshakeTimeout.
 - https://github.com/rancher/rancher/blob/master/pkg/agent/main.go#L208
 - https://github.com/rancher/rancher/blob/master/vendor/github.com/rancher/norman/pkg/remotedialer/client.go#L25

That's why if rancher-server or nginx got something wrong and stopped to proceed WebSocket Session Handshake after establish TCP connection, node-agent might get hung.

**Propose**

So we basically should set HandshakeTimeout as reasonable time like 10 second. 
Otherwide some agent might just wait for in-complete Web Socket Session Handshake for ever which should be stopped and retried. 

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): 2.2.3 
- Installation option (single install/HA): HA

**Cluster information**
- Cluster type (Infrastructure Provider): OpenStack
- Machine type (cloud/VM/metal) and specifications (CPU/memory): VM, 8 core 32 GB
- Kubernetes version (use `kubectl version`): 1.13.5

This troubleshooting has been done with  @liFeixiang  @nanorobocop

**Comment by ukinau** [comment] 2019-06-25 16:00
There are 2 repository we need to set HandshakeTimeout. one is rancher/rancher. the other one is rancher/norman.  I already created 2 PR as above

**Comment by cjellick** [comment] 2019-09-06 20:28
the remotedialer fixes for this are not in master at least as of `e78ddbbb9` because we made a switch to rancher/remotedialer which did not have the commit

**Comment by cjellick** [comment] 2019-09-09 16:42
Closing, day-to-day running of rancher will prove that this doesnt cause a regression and I don't think we need to explicitly trigger this scenario from a testing perspective

**Closed by cjellick** 2019-09-09 16:42 UTC
Labels: [zube]: To Test, kind/bug, status/to-validate, team/az
