### ISSUE TITLE
Upgrade from Rancher 1.1.0 to 1.3 Yields Fatal Connection Errors (getsockopt: connection refused) 

### ISSUE THREAD

**Issue by ppandy** [rancher/rancher#7867] opened 2017-02-17 15:53 UTC
**Rancher Versions:**
Server: v1.1.0 -> v1.3.x

**Docker Version:**
1.12.5, build 047e51b/1.12.5 (SELinux Permissive)

**OS and where are the hosts located? (cloud, bare metal, etc):**
CentOS 7 3.10.0-514.2.2.el7.x86_64 (Bare Metal, ESXI VMWare)

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
Single Admin Node with External DB

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
100% Cattle

**Steps to Reproduce:**
We ran an upgrade by stopping the running 1.1.0 Container, and launching the new container in the new arg syntax. (We also tried ENV Vars, with the same result)

```
docker run -d --restart=unless-stopped -p 8080:8080 \
rancher/server:1.3 \
--db-host myhost.example.com \
--db-port 3306 \
--db-user username \
--db-pass password \
--db-name cattle 
```

**Results:** 
Upgrade worked properly as far as db updates, but starting the event listeners (routers?) consistently got the following error. We gave it a few hours, and even tried with 1.2.x, and then again with 1.3.x, thinking we had a db upgrade race condition or somesuch, but no luck. Eventually had to db restore and start 1.1.0.

`Unable to create event router" error="Get http://localhost:8080/v2-beta: dial tcp [::1]:8080: getsockopt: connection refused`

Note, our initial thoughts were that firewalld (and iptables) were misconfigured and somehow interfering with NAT services. CentOS7 has default configs that are fairly restrictive. Looking at this ticket might lead to some resolution, but noting that we haven't really gone down this road yet:

https://github.com/docker/docker/issues/16137#issuecomment-271615192

**Comment by ppandy** [comment] 2017-02-20 23:26
@cjellick More info and a more recent stacktrace:

time="2017-02-20T23:23:13Z" level=info msg="Starting rancher-compose-executor" version=v0.12.1
fatal error: unexpected signal during runtime execution
[signal 0xb code=0x1 addr=0x63 pc=0x7f5d4503eb2c]
runtime stack:
runtime.throw(0xaeff60, 0x2a)
        /usr/local/go/src/runtime/panic.go:547 +0x90
runtime.sigpanic()
        /usr/local/go/src/runtime/sigpanic_unix.go:12 +0x5a
goroutine 27 [syscall, locked to thread]:
runtime.cgocall(0x7ab6c0, 0xc820034bd8, 0x0)
        /usr/local/go/src/runtime/cgocall.go:123 +0x11b fp=0xc820034b78 sp=0xc820034b48
net._C2func_getaddrinfo(0x7f5d380008c0, 0x0, 0xc8200132c0, 0xc8200ea010, 0x0, 0x0, 0x0)
        ??:0 +0x55 fp=0xc820034bd8 sp=0xc820034b78
net.cgoLookupIPCNAME(0xc820012075, 0x9, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0xb49c00)
        /usr/local/go/src/net/cgo_unix.go:111 +0x448 fp=0xc820034d50 sp=0xc820034bd8
net.cgoLookupIP(0xc820012075, 0x9, 0x0, 0x0, 0x0, 0x0, 0x0, 0xc820387da0)
        /usr/local/go/src/net/cgo_unix.go:163 +0x56 fp=0xc820034da8 sp=0xc820034d50
net.lookupIP(0xc820012075, 0x9, 0x0, 0x0, 0x0, 0x0, 0x0)
        /usr/local/go/src/net/lookup_unix.go:67 +0x94 fp=0xc820034e18 sp=0xc820034da8
net.glob.func16(0xb49cb0, 0xc820012075, 0x9, 0x0, 0x0, 0x0, 0x0, 0x0)
        /usr/local/go/src/net/hook.go:10 +0x4d fp=0xc820034e58 sp=0xc820034e18
net.lookupIPDeadline.func1(0x0, 0x0, 0x0, 0x0)
        /usr/local/go/src/net/lookup.go:106 +0x71 fp=0xc820034ed8 sp=0xc820034e58
internal/singleflight.(*Group).doCall(0xfc9480, 0xc82000e140, 0xc820012075, 0x9, 0xc8203a0000)
        /usr/local/go/src/internal/singleflight/singleflight.go:93 +0x2c fp=0xc820034f88 sp=0xc820034ed8
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:1998 +0x1 fp=0xc820034f90 sp=0xc820034f88
created by internal/singleflight.(*Group).DoChan
        /usr/local/go/src/internal/singleflight/singleflight.go:86 +0x3ee
goroutine 1 [IO wait]:
net.runtime_pollWait(0x7f5d4410ff40, 0x72, 0x0)
        /usr/local/go/src/runtime/netpoll.go:160 +0x60
net.(*pollDesc).Wait(0xc82019daa0, 0x72, 0x0, 0x0)
        /usr/local/go/src/net/fd_poll_runtime.go:73 +0x3a
net.(*pollDesc).WaitRead(0xc82019daa0, 0x0, 0x0)
        /usr/local/go/src/net/fd_poll_runtime.go:78 +0x36
net.(*netFD).accept(0xc82019da40, 0x0, 0x7f5d4411dd40, 0xc8203a08a0)
        /usr/local/go/src/net/fd_unix.go:426 +0x27c
net.(*TCPListener).AcceptTCP(0xc8200223c0, 0x8a0bf1618a100, 0x0, 0x0)
        /usr/local/go/src/net/tcpsock_posix.go:254 +0x4d
net.(*TCPListener).Accept(0xc8200223c0, 0x0, 0x0, 0x0, 0x0)
        /usr/local/go/src/net/tcpsock_posix.go:264 +0x3d
github.com/rancher/websocket-proxy/proxy/proxyprotocol.(*Listener).Accept(0xc82018f800, 0x0, 0x0, 0x0, 0x0)
        /go/src/github.com/rancher/websocket-proxy/proxy/proxyprotocol/proxy_protocol.go:71 +0x79
github.com/rancher/websocket-proxy/proxy/tls.(*SplitListener).Accept(0xc8203a0840, 0x0, 0x0, 0x0, 0x0)
        /go/src/github.com/rancher/websocket-proxy/proxy/tls/splitter.go:29 +0x79
net/http.(*Server).Serve(0xc820157700, 0x7f5d4411dc20, 0xc8203a0840, 0x0, 0x0)
        /usr/local/go/src/net/http/server.go:2117 +0x129
github.com/rancher/websocket-proxy/proxy.(*Starter).StartProxy(0xc82007efa0, 0x0, 0x0)
        /go/src/github.com/rancher/websocket-proxy/proxy/proxy.go:165 +0x1518
main.main()
        /go/src/github.com/rancher/websocket-proxy/main.go:72 +0x756
goroutine 17 [syscall, locked to thread]:
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:1998 +0x1
goroutine 18 [IO wait]:
net.runtime_pollWait(0x7f5d44110000, 0x72, 0xc8200ec000)
        /usr/local/go/src/runtime/netpoll.go:160 +0x60
net.(*pollDesc).Wait(0xc8200e6060, 0x72, 0x0, 0x0)
        /usr/local/go/src/net/fd_poll_runtime.go:73 +0x3a
net.(*pollDesc).WaitRead(0xc8200e6060, 0x0, 0x0)
        /usr/local/go/src/net/fd_poll_runtime.go:78 +0x36
net.(*netFD).Read(0xc8200e6000, 0xc8200ec000, 0x1000, 0x1000, 0x0, 0x7f5d4624c050, 0xc82000a120)
        /usr/local/go/src/net/fd_unix.go:250 +0x23a
net.(*conn).Read(0xc8200ea000, 0xc8200ec000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
        /usr/local/go/src/net/net.go:172 +0xe4
net/http.noteEOFReader.Read(0x7f5d441100c0, 0xc8200ea000, 0xc82005bf48, 0xc8200ec000, 0x1000, 0x1000, 0x4071d3, 0x0, 0x0)
        /usr/local/go/src/net/http/transport.go:1690 +0x67
net/http.(*noteEOFReader).Read(0xc8200e20a0, 0xc8200ec000, 0x1000, 0x1000, 0xc820033d1d, 0x0, 0x0)
        <autogenerated>:284 +0xd0
bufio.(*Reader).fill(0xc8200e8060)
        /usr/local/go/src/bufio/bufio.go:97 +0x1e9
bufio.(*Reader).Peek(0xc8200e8060, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0)
        /usr/local/go/src/bufio/bufio.go:132 +0xcc
net/http.(*persistConn).readLoop(0xc82005bee0)
        /usr/local/go/src/net/http/transport.go:1076 +0x177
created by net/http.(*Transport).dialConn
        /usr/local/go/src/net/http/transport.go:860 +0x10a6
goroutine 19 [runnable]:
net/http.(*Request).write(0xc8201c6700, 0x7f5d44110138, 0xc8200ee000, 0x7f5d44110100, 0x0, 0x0, 0x0, 0x0)
        /usr/local/go/src/net/http/request.go:430 +0x407
net/http.(*persistConn).writeLoop(0xc82005bee0)
        /usr/local/go/src/net/http/transport.go:1286 +0x2dc
created by net/http.(*Transport).dialConn
        /usr/local/go/src/net/http/transport.go:861 +0x10cb
goroutine 8 [sleep]:
time.Sleep(0x12a05f200)
        /usr/local/go/src/runtime/time.go:59 +0xf9
github.com/rancher/websocket-proxy/proxy.(*Switcher).start(0xc8200d2300)
        /go/src/github.com/rancher/websocket-proxy/proxy/frontend_switcher.go:58 +0x1f5
created by github.com/rancher/websocket-proxy/proxy.NewSwitcher
        /go/src/github.com/rancher/websocket-proxy/proxy/frontend_switcher.go:25 +0x80
goroutine 9 [select]:
github.com/rancher/websocket-proxy/vendor/github.com/patrickmn/go-cache.(*janitor).Run(0xc8201100a0, 0xc820015e40)
        /go/src/github.com/rancher/websocket-proxy/vendor/github.com/patrickmn/go-cache/cache.go:1037 +0x15c
created by github.com/rancher/websocket-proxy/vendor/github.com/patrickmn/go-cache.runJanitor
        /go/src/github.com/rancher/websocket-proxy/vendor/github.com/patrickmn/go-cache/cache.go:1056 +0x81
goroutine 10 [sleep]:
time.Sleep(0xee6b280)
        /usr/local/go/src/runtime/time.go:59 +0xf9
github.com/rancher/websocket-proxy/proxy.(*Starter).StartProxy.func1(0xc82007efa0)
        /go/src/github.com/rancher/websocket-proxy/proxy/proxy.go:114 +0x14c
created by github.com/rancher/websocket-proxy/proxy.(*Starter).StartProxy
        /go/src/github.com/rancher/websocket-proxy/proxy/proxy.go:116 +0xfb4
goroutine 22 [select]:
net/http.(*persistConn).roundTrip(0xc82005bee0, 0xc8203534d0, 0x0, 0x0, 0x0)
        /usr/local/go/src/net/http/transport.go:1476 +0xf1f
net/http.(*Transport).RoundTrip(0xc8200bc000, 0xc8201c6700, 0xf, 0x0, 0x0)
        /usr/local/go/src/net/http/transport.go:327 +0x9bb
net/http/httputil.(*ReverseProxy).ServeHTTP(0xc820015e80, 0x7f5d4411de38, 0xc8200d0c30, 0xc8202de1c0)
        /usr/local/go/src/net/http/httputil/reverseproxy.go:210 +0x886
github.com/rancher/websocket-proxy/proxy.(*proxyProtocolConverter).ServeHTTP(0xc8201100c0, 0x7f5d4411de38, 0xc8200d0c30, 0xc8202de1c0)
        /go/src/github.com/rancher/websocket-proxy/proxy/proxy.go:244 +0x5e
github.com/rancher/websocket-proxy/vendor/github.com/gorilla/mux.(*Router).ServeHTTP(0xc82000eff0, 0x7f5d4411de38, 0xc8200d0c30, 0xc8202de1c0)
        /go/src/github.com/rancher/websocket-proxy/vendor/github.com/gorilla/mux/mux.go:98 +0x29e
github.com/rancher/websocket-proxy/proxy.(*pathCleaner).ServeHTTP(0xc8200223b8, 0x7f5d4411de38, 0xc8200d0c30, 0xc8202de1c0)
        /go/src/github.com/rancher/websocket-proxy/proxy/proxy.go:206 +0xe9
github.com/rancher/websocket-proxy/proxy.(*SwarmHandler).ServeHTTP(0xc8201a23c0, 0x7f5d4411de38, 0xc8200d0c30, 0xc8202de1c0)
        /go/src/github.com/rancher/websocket-proxy/proxy/swarm_handler.go:14 +0xba
net/http.serverHandler.ServeHTTP(0xc820157700, 0x7f5d4411de38, 0xc8200d0c30, 0xc8202de1c0)
        /usr/local/go/src/net/http/server.go:2081 +0x19e
net/http.(*conn).serve(0xc8204d3380)
        /usr/local/go/src/net/http/server.go:1472 +0xf2e
created by net/http.(*Server).Serve
        /usr/local/go/src/net/http/server.go:2137 +0x44e
goroutine 23 [select]:
net/http.(*Transport).getConn(0xc8200bc000, 0xc8201c6000, 0x0, 0xa3c9b8, 0x4, 0xc820012075, 0xe, 0x0, 0x0, 0x0)
        /usr/local/go/src/net/http/transport.go:714 +0x4ef
net/http.(*Transport).RoundTrip(0xc8200bc000, 0xc8201c6000, 0xf, 0x0, 0x0)
        /usr/local/go/src/net/http/transport.go:314 +0x7e9
net/http/httputil.(*ReverseProxy).ServeHTTP(0xc820015e80, 0x7f5d4411de38, 0xc8200f6340, 0xc8201c6460)
        /usr/local/go/src/net/http/httputil/reverseproxy.go:210 +0x886
github.com/rancher/websocket-proxy/proxy.(*proxyProtocolConverter).ServeHTTP(0xc8201100c0, 0x7f5d4411de38, 0xc8200f6340, 0xc8201c6460)
        /go/src/github.com/rancher/websocket-proxy/proxy/proxy.go:244 +0x5e
github.com/rancher/websocket-proxy/vendor/github.com/gorilla/mux.(*Router).ServeHTTP(0xc82000eff0, 0x7f5d4411de38, 0xc8200f6340, 0xc8201c6460)
        /go/src/github.com/rancher/websocket-proxy/vendor/github.com/gorilla/mux/mux.go:98 +0x29e
github.com/rancher/websocket-proxy/proxy.(*pathCleaner).ServeHTTP(0xc8200223b8, 0x7f5d4411de38, 0xc8200f6340, 0xc8201c6460)
        /go/src/github.com/rancher/websocket-proxy/proxy/proxy.go:206 +0xe9
github.com/rancher/websocket-proxy/proxy.(*SwarmHandler).ServeHTTP(0xc8201a23c0, 0x7f5d4411de38, 0xc8200f6340, 0xc8201c6460)
        /go/src/github.com/rancher/websocket-proxy/proxy/swarm_handler.go:14 +0xba
net/http.serverHandler.ServeHTTP(0xc820157700, 0x7f5d4411de38, 0xc8200f6340, 0xc8201c6460)
        /usr/local/go/src/net/http/server.go:2081 +0x19e
net/http.(*conn).serve(0xc8204d3400)
        /usr/local/go/src/net/http/server.go:1472 +0xf2e
created by net/http.(*Server).Serve
        /usr/local/go/src/net/http/server.go:2137 +0x44e
goroutine 24 [IO wait]:
net.runtime_pollWait(0x7f5d4410fe80, 0x72, 0xc8204db000)
        /usr/local/go/src/runtime/netpoll.go:160 +0x60
net.(*pollDesc).Wait(0xc82013eed0, 0x72, 0x0, 0x0)
        /usr/local/go/src/net/fd_poll_runtime.go:73 +0x3a
net.(*pollDesc).WaitRead(0xc82013eed0, 0x0, 0x0)
        /usr/local/go/src/net/fd_poll_runtime.go:78 +0x36
net.(*netFD).Read(0xc82013ee70, 0xc8204db000, 0x1000, 0x1000, 0x0, 0x7f5d4624c050, 0xc82000a120)
        /usr/local/go/src/net/fd_unix.go:250 +0x23a
net.(*conn).Read(0xc8200ea030, 0xc8204db000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
        /usr/local/go/src/net/net.go:172 +0xe4
bufio.(*Reader).Read(0xc820429980, 0xc8204db000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
        /usr/local/go/src/bufio/bufio.go:197 +0x126
github.com/rancher/websocket-proxy/proxy/proxyprotocol.(*Conn).Read(0xc820387d70, 0xc8204db000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
        /go/src/github.com/rancher/websocket-proxy/proxy/proxyprotocol/proxy_protocol.go:107 +0xdc
bufio.(*Reader).fill(0xc8204299e0)
        /usr/local/go/src/bufio/bufio.go:97 +0x1e9
bufio.(*Reader).Read(0xc8204299e0, 0xc820353478, 0x1, 0x1, 0x879040, 0x0, 0x0)
        /usr/local/go/src/bufio/bufio.go:207 +0x260
github.com/rancher/websocket-proxy/proxy/tls.(*Conn).Read(0xc820387da0, 0xc820353478, 0x1, 0x1, 0x0, 0x0, 0x0)
        /go/src/github.com/rancher/websocket-proxy/proxy/tls/splitter.go:20 +0x7d
net/http.(*connReader).closeNotifyAwaitActivityRead(0xc8203d2a80, 0xc8204ac780, 0xc8203a0ba0)
        /usr/local/go/src/net/http/server.go:542 +0x9c
created by net/http.(*connReader).startBackgroundRead
        /usr/local/go/src/net/http/server.go:537 +0x92
goroutine 25 [runnable]:
net/http.(*connReader).closeNotifyAwaitActivityRead(0xc8203a08c0, 0xc8204ac060, 0xc820010280)
        /usr/local/go/src/net/http/server.go:540
created by net/http.(*connReader).startBackgroundRead
        /usr/local/go/src/net/http/server.go:537 +0x92
goroutine 26 [select]:
net.lookupIPDeadline(0xc820012075, 0x9, 0xed03d7180, 0x1637d959, 0xfca120, 0x0, 0x0, 0x0, 0x0, 0x0)
        /usr/local/go/src/net/lookup.go:109 +0x6a6
net.internetAddrList(0xa3e048, 0x3, 0xc820012075, 0xe, 0xed03d7180, 0x1637d959, 0xfca120, 0x0, 0x0, 0x0, ...)
        /usr/local/go/src/net/ipsock.go:252 +0x6ee
net.resolveAddrList(0xa3c0a8, 0x4, 0xa3e048, 0x3, 0xc820012075, 0xe, 0xed03d7180, 0x1637d959, 0xfca120, 0x0, ...)
        /usr/local/go/src/net/dial.go:158 +0x466
net.(*Dialer).Dial(0xc82000e410, 0xa3e048, 0x3, 0xc820012075, 0xe, 0x0, 0x0, 0x0, 0x0)
        /usr/local/go/src/net/dial.go:216 +0x124
net.(*Dialer).Dial-fm(0xa3e048, 0x3, 0xc820012075, 0xe, 0x0, 0x0, 0x0, 0x0)
        /usr/local/go/src/net/http/transport.go:38 +0x6e
net/http.(*Transport).dial(0xc8200bc000, 0xa3e048, 0x3, 0xc820012075, 0xe, 0x0, 0x0, 0x0, 0x0)
        /usr/local/go/src/net/http/transport.go:662 +0x96
net/http.(*Transport).dialConn(0xc8200bc000, 0x0, 0xa3c9b8, 0x4, 0xc820012075, 0xe, 0x0, 0x0, 0x0)
        /usr/local/go/src/net/http/transport.go:765 +0x1e3d
net/http.(*Transport).getConn.func4(0xc8200bc000, 0x0, 0xa3c9b8, 0x4, 0xc820012075, 0xe, 0xc8204ac0c0)
        /usr/local/go/src/net/http/transport.go:709 +0x66
created by net/http.(*Transport).getConn
        /usr/local/go/src/net/http/transport.go:711 +0x262
time="2017-02-20T23:23:14Z" level=fatal msg="Failed to configure cattle client: Get http://localhost:8080/v1: EOF"
time="2017-02-20T23:23:14Z" level=fatal msg="Failed to configure cattle client: Get http://localhost:8080/v1: EOF"
time="2017-02-20T23:23:14Z" level=fatal msg="Unable to create event router" error="Get http://localhost:8080/v2-beta: EOF"
time="2017-02-20T23:23:15Z" level=info msg="Setting log level" logLevel=info
time="2017-02-20T23:23:15Z" level=info msg="Starting go-machine-service..." gitcommit=v0.35.0
time="2017-02-20T23:23:15Z" level=info msg="Waiting for handler registration (1/2)"
time="2017-02-20T23:23:15Z" level=fatal msg="Exiting go-machine-service: Get http://localhost:8080/v2-beta: dial tcp 127.0.0.1:8080: getsockopt: connection refused"

**Comment by superseb** [comment] 2017-05-24 12:30
What's the current status @ppandy ?

**Comment by Goldcap** [comment] 2017-05-24 13:22
@superseb Sadly no progress. We're limping along with 1.1, but it's going to be critical for us to figure this out soon as 1.1 is so outdated. Not sure where to go from here, honestly.

**Comment by superseb** [comment] 2017-05-24 13:29
I have to dig up on the bugs/issues, there is a environment variabele workaround for `rancher/server`, and a IP workaround for `.local` TLD if you are using that? What did you try already?

**Comment by Goldcap** [comment] 2017-05-24 13:38
@superseb I don't think it's any of that, my impression was that our NIC configuration in VSphere was causing the issue. We use FQDNs, and have every machine in the environment resolve via internal DNS, so .local wouldn't be the cause AFAIK.

Noting that we haven't done anything particularly unusual, VSphere with CentOS7 and static IP's. We fiddled with /etc/sysconfig/network-scripts/*, we have an open firewall, but it was all pretty mysterious.

**Comment by digitalpark** [comment] 2017-06-15 22:18
@superseb @cjellick We've traced this back to issues with the network manager in VSphere < 6.5, and after upgrading we see fewer issues with Rancher.

So we can probably safely close this one out, unless there's any value in triage against VSphere 5.5. I think it's a pretty isolated use case, but might point someone else in the right direction. 

Thanks for all the help either way!

**Comment by superseb** [comment] 2017-06-16 11:46
Thanks a lot for reporting back!

**Closed by superseb** 2017-06-16 11:46 UTC
Labels: status/more-info
