### ISSUE TITLE
Etcd Certificate Rotate fails

### ISSUE THREAD

**Issue by maese83** [rancher/rancher#23827] opened 2019-11-01 15:05 UTC
*Describe your issue here*
My Cluster has a soon expiring etcd certificate but I can't rotate it over the GUI. It does somthing in the back but afterwards I see still the same warning: This cluster has certs that are expiring or have expired. I have a single cluster installation. 

I tried with Kubernetes 
- v1.15.5: not working
- v1.16.2: not working

- Rancher v.2.3: not working
- Rancher v2.3.2: not working

**Comment by sowmyav27** [comment] 2019-11-01 17:13
@maese83 
I verified on 2.3.2 rancher, with k8s 1.15.
I am able to rotate certs from the UI and the certs do get rotated (get a new expiry date) on the etcd, control plane and worker nodes.

Would you be able to check if the right cert expiry is available in the API
Do a `View in API` of the cluster form the Clusters page in UI.
Check the section `certificatesExpiration` which will be displayed something like following.

```
"certificatesExpiration": {
"kube-apiserver": {
"expirationDate": "2029-10-29T16:56:27Z",
"type": "/v3/schemas/certExpiration"
},
"kube-ca": {
"expirationDate": "2029-10-29T16:49:31Z",
"type": "/v3/schemas/certExpiration"
},
"kube-controller-manager": {
"expirationDate": "2029-10-29T16:56:27Z",
"type": "/v3/schemas/certExpiration"
},
"kube-etcd-159-203-110-76": {
"expirationDate": "2029-10-29T16:56:28Z",
"type": "/v3/schemas/certExpiration"
},
"kube-node": {
"expirationDate": "2029-10-29T16:56:27Z",
"type": "/v3/schemas/certExpiration"
},
"kube-proxy": {
"expirationDate": "2029-10-29T16:56:27Z",
"type": "/v3/schemas/certExpiration"
},
"kube-scheduler": {
"expirationDate": "2029-10-29T16:56:27Z",
"type": "/v3/schemas/certExpiration"
}
},
```

**Comment by maese83** [comment] 2019-11-01 22:06
Hi @sowmyav27 
Here my expiry information. 2 etcd nodes have a 2019 expiration date, 1 has 2029.
`certificatesExpiration": {
"kube-apiserver": {
"expirationDate": "2029-10-29T13:30:54Z",
"type": "/v3/schemas/certExpiration"
},
"kube-ca": {
"expirationDate": "2028-11-08T22:05:19Z",
"type": "/v3/schemas/certExpiration"
},
"kube-controller-manager": {
"expirationDate": "2029-10-29T13:30:54Z",
"type": "/v3/schemas/certExpiration"
},
"kube-etcd-192-168-9-168": {
"expirationDate": "2029-05-11T15:48:04Z",
"type": "/v3/schemas/certExpiration"
},
"kube-etcd-192-168-9-17": {
"expirationDate": "2019-11-11T22:24:00Z",
"type": "/v3/schemas/certExpiration"
},
"kube-etcd-192-168-9-18": {
"expirationDate": "2019-11-11T22:05:22Z",
"type": "/v3/schemas/certExpiration"
},
"kube-etcd-192-168-9-87": {
"expirationDate": "2029-10-29T14:27:45Z",
"type": "/v3/schemas/certExpiration"
},
"kube-etcd-192-168-9-88": {
"expirationDate": "2029-10-29T14:27:44Z",
"type": "/v3/schemas/certExpiration"
},
"kube-etcd-192-168-9-89": {
"expirationDate": "2029-10-29T14:27:44Z",
"type": "/v3/schemas/certExpiration"
},
"kube-node": {
"expirationDate": "2029-10-29T13:30:55Z",
"type": "/v3/schemas/certExpiration"
},
"kube-proxy": {
"expirationDate": "2029-10-29T13:30:55Z",
"type": "/v3/schemas/certExpiration"
},
"kube-scheduler": {
"expirationDate": "2029-10-29T13:30:55Z",
"type": "/v3/schemas/certExpiration"
}`

**Comment by maese83** [comment] 2019-11-01 22:16
I just saw I have 6 etcd entries, but I have actually only 3 etcd nodes: 192-168-9-87 , 192-168-9-88 and 192-168-9-89 are the correct IPs. The other 3 wrong or old IPs.

My nodes overview:

NAME              STATUS   ROLES          AGE    VERSION
vmk8setcd1        Ready    etcd           168d   v1.16.2
vmk8setcd2        Ready    etcd           168d   v1.16.2
vmk8setcd3        Ready    etcd           168d   v1.16.2

**Comment by Azaradel** [comment] 2019-11-04 15:26
I have a similar situation in one of my clusters. There are certs generated for etcd nodes that used to exist and they are expiring soon so the GUI displays this scary warning about expiration.  It's an old cluster made with rancher 2.0.x, the rotation of other certificates went smooth two weeks  ago while following instructions from [documentation](https://rancher.com/docs/rancher/v2.x/en/cluster-admin/certificate-rotation/#rotating-expired-certificates-after-upgrading-older-rancher-versions) and at least I can be calm with existing nodes.

I already removed cert files that were associated with old etcd nodes from nodes in:
- `/etc/kubernetes/.tmp`
- `/etc/kubernetes/ssl`
- `/opt/rke/etc/kubernetes/.tmp`
- `/opt/rke/etc/kubernetes/ssl`

But API still returns information about two of them. Is there a way to remove those entries?
I can bring more information if needed.

**Comment by MaxDiOrio** [comment] 2019-11-05 00:22
I need to add a Me Too for this.  I have extra etcd nodes showing in the certificate section, but not in the nodes section.

How do I remove the old nodes from the certificate expiration section?  And will the cluster go into a bad state when these certs expire?  We can't really have a cluster go unavailable, it's a UAT cluster that needs to be up.

Thanks.

**Comment by maese83** [comment] 2019-11-07 22:44
Hi @sowmyav27 
Any idea. My etcd certificate expires in 4 days and it would be critical if the full cluster is blocked. Any idea how to fix that?
Thanks Marcel

**Comment by corx96** [comment] 2019-11-08 07:07
Hi,
i got the same problem. 
@maese83 My Cluster expired two days ago and is still available. I think it's because of the valid certificates. The message that I should rotate the cluster is still present and the entries in the Api are still present. Looks like an optical bug.

A way to get rid of this would be nice

**Comment by maese83** [comment] 2019-11-08 12:50
Hi @corx96 
Thanks for the Info, this takes out a bit the pressure if the cluster continues to work ;-)

**Comment by thomashoell** [comment] 2019-11-29 09:12
I have the exact same problem. However, the certificate **IS** rotated. This can be verified by doing a `openssl s_client -connect <my-etcd-node-ip>:2379`. The certificate presented is valid from 2018-12-13 to 2029-11-26. Also, the etcd certificate and key files in _/etc/kubernetes/ssl_ are updated every time the rotation is performed.

**Comment by maese83** [comment] 2019-12-12 09:15
> I have the exact same problem. However, the certificate **IS** rotated. This can be verified by doing a `openssl s_client -connect <my-etcd-node-ip>:2379`. The certificate presented is valid from 2018-12-13 to 2029-11-26. Also, the etcd certificate and key files in _/etc/kubernetes/ssl_ are updated every time the rotation is performed.
> 
> EDIT: The issue seems to be that some old etcd nodes are still present in the API:
> 
> ```json
> // present
>   "kube-etcd-172-16-6-32": {
>     "expirationDate": "2029-11-26T08:20:37Z",
>     "type": "/v3/schemas/certExpiration"
>   },
> // removed
>   "kube-etcd-172-16-6-33": {
>     "expirationDate": "2019-12-13T10:59:15Z",
>     "type": "/v3/schemas/certExpiration"
>   },
> // removed
>   "kube-etcd-172-16-6-34": {
>     "expirationDate": "2019-12-13T11:03:35Z",
>     "type": "/v3/schemas/certExpiration"
>   },
> // removed
>   "kube-etcd-172-16-6-35": {
>     "expirationDate": "2019-12-13T10:55:17Z",
>     "type": "/v3/schemas/certExpiration"
>   }```
> 
> .33, .34, .35 were removed from the cluster some time ago. No clue why they're still listed here.
> ```

Hi and how can this old etcd node can be removed?

**Comment by loganhz** [comment] 2019-12-31 09:33
Old cert issue will be fixed in https://github.com/rancher/rancher/issues/24333

@deniseschannon @maggieliu  maybe we need to fix it in 2.3 ?

**Comment by loganhz** [comment] 2019-12-31 09:36
Added into 2.3.4 milestone. We have submitted the PRs for master branch.  

https://github.com/rancher/rke/pull/1824
https://github.com/rancher/rancher/pull/24548

**Comment by sowmyav27** [comment] 2020-02-25 22:13
**Reproduced the issue on 2.3.5**

**Steps:**

- Add a cluster with 3 etcd nodes, 1 control plane and 1 worker nodes
- Delete one etcd node and wait for another one to be provisioned.
- After the cluster has come up Active, Rotate certs
- Click View API for the cluster. The cert for removed ectd node is still in API and the expirationDate not changed.
<img width="385" alt="Screen Shot 2020-02-25 at 1 20 10 PM" src="https://user-images.githubusercontent.com/26032343/75288861-07925280-57d2-11ea-8a64-c19c91acf022.png">

**Verified on master-head - latest - commit id: `6085a90e2`**

**Steps:**
- Add a cluster with 3 etcd nodes, 1 control plane and 1 worker nodes
- Delete one etcd node and wait for another one to be provisioned.
- After the cluster has come up Active, Do a view in API of the cluster
- `certificatesExpiration` will NOT show the old etcd node (which was deleted)
- Do a Rotate Certs action.
- All the certs get rotated. and a new expiry can be seen in the View in API.

**Closed** 2020-02-26 03:36 UTC
Labels: [zube]: To Test, internal, kind/bug

**Comment by corx96** [comment] 2020-02-26 06:54
So if I understand this correctly the error will no longer occur in the next version when a node is deleted.

But how do we get the wrong certificate out of the system. Rancher continues to display an error message indicating that the certificates have expired.
 Is it enough to rotate the certificates in the next version or do we have to do something else?

**Comment by loganhz** [comment] 2020-02-26 06:58
Nothing need to do after upgrading to the new version. It will automatically clean up the existing wrong cert warnings. https://github.com/rancher/rancher/blob/master/pkg/controllers/user/certsexpiration/certsexpiration.go#L76
