### ISSUE TITLE
Cluster and Node Agent Environment Variables Should be Modified if the Rancher Server's Name is modified

### ISSUE THREAD

**Issue by JasonvanBrackel** [rancher/rancher#15099] opened 2018-08-16 16:29 UTC
**Rancher versions:**
rancher/server or rancher/rancher: v2.0.7
rancher/agent or rancher/rancher-agent: v2.0.7

**Steps to Reproduce:**
The Cluster and Cluster Node agents variables as set so the agent can call back to the rancher server.  These are not changed if the rancher server is renamed.

Original Settings
![image](https://user-images.githubusercontent.com/942110/44221546-d4d4bc00-a14f-11e8-9887-d61401c2979f.png)

![image](https://user-images.githubusercontent.com/942110/44221557-d9997000-a14f-11e8-89ff-b2502cf9a0f7.png)

Update the cluster name
![image](https://user-images.githubusercontent.com/942110/44221568-e5853200-a14f-11e8-8000-af6d807a10ed.png)

Agents remain unchanged
![image](https://user-images.githubusercontent.com/942110/44221615-05b4f100-a150-11e8-81ee-3fe38c8da170.png)

Change the 

**Results:**

**Comment by cjellick** [comment] 2018-12-17 21:12
can you define what you mean by renamed? Where are you doing the renaming

**Comment by cjellick** [comment] 2018-12-17 21:12
didnt mean to close. just bad aim on the ol' clicker

**Comment by deniseschannon** [comment] 2019-04-11 23:39
Duplicate of https://github.com/rancher/rancher/issues/14731

**Closed by deniseschannon** 2019-04-11 23:39 UTC
Labels: area/agent, internal, kind/bug, priority/0, status/more-info, team/az
