### ISSUE TITLE
Waiting for server-url setting to be set

### ISSUE THREAD

**Issue by panho66** [rancher/rancher#16288] opened 2018-10-25 03:40 UTC
**What kind of request is this (question/bug/enhancement/feature request):**
problem possible bug
**Steps to reproduce (least amount of steps as possible):**
Install Rancher 2.1 with server-chart 2018-10-2, rke
Login Rancher and accept default server-url
Rancher console up and shows messages
**'Waiting for server-url setting to be set'**

**Result:**
Wait for a long time for cluster to be ready but still showing 
_This cluster is currently Provisioning.
Waiting for server-url setting to be set_
Scale up Rancher instance from 1 to 2 
Cattle-cluster-agent and Cattle-node-agent create instantly 

**Other details that may be helpful:**
before scaling up Rancher instance
[dockeradm@rancher2-lab2-1 .rke_home]$ kubectl get pods --all-namespaces
NAMESPACE       NAME                                      READY     STATUS      RESTARTS   AGE
cattle-system   rancher-56cff595f6-dsfhp                  2/2       Running     0          53m
ingress-nginx   default-http-backend-797c5bc547-8qqlc     1/1       Running     0          1h
ingress-nginx   nginx-ingress-controller-25l8f            1/1       Running     0          1h
ingress-nginx   nginx-ingress-controller-57vsr            1/1       Running     0          1h
ingress-nginx   nginx-ingress-controller-gn6bf            1/1       Running     0          1h
ingress-nginx   nginx-ingress-controller-wrrqd            1/1       Running     0          2m
kube-system     canal-5l4xk                               3/3       Running     0          1h
kube-system     canal-5qm8h                               3/3       Running     0          1h
kube-system     canal-8scm7                               3/3       Running     0          1h
kube-system     canal-d8mf7                               3/3       Running     0          1h
kube-system     canal-k8jhk                               3/3       Running     0          1h
kube-system     canal-ntgv9                               3/3       Running     0          1h
kube-system     cert-manager-787d565b77-6s2ql             1/1       Running     0          53m
kube-system     kube-dns-7588d5b5f5-mbxdw                 3/3       Running     0          1h
kube-system     kube-dns-7588d5b5f5-tnvsf                 3/3       Running     0          1h
kube-system     kube-dns-autoscaler-5db9bbb766-9ztq8      1/1       Running     0          1h
kube-system     metrics-server-97bc649d5-hkmk4            1/1       Running     0          1h
kube-system     rke-ingress-controller-deploy-job-cgx2j   0/1       Completed   0          1h
kube-system     rke-kubedns-addon-deploy-job-d6f6w        0/1       Completed   0          1h
kube-system     rke-metrics-addon-deploy-job-qlm26        0/1       Completed   0          1h
kube-system     rke-network-plugin-deploy-job-rgckh       0/1       Completed   0          1h
tiller-system   tiller-deploy-784556886d-nhxsd            1/1       Running     0          1h

2018/10/25 03:20:04 [INFO] Updating workload [cattle-system/rancher] with public endpoints [[{"addresses":["","",""],"port":443,"protocol":"HTTPS","serviceName":"cattle-system:rancher","ingressName":"cattle-system:rancher","hostname":"rancher.middleware-lab-1.auiag.corp","allNodes":false}]]
2018/10/25 03:23:26 [ERROR] ClusterController local [cluster-deploy] failed with : waiting for server-url setting to be set
2018/10/25 03:23:32 [ERROR] ClusterController local [cluster-deploy] failed with : waiting for server-url setting to be set
2018/10/25 03:23:32 [ERROR] ClusterController local [cluster-deploy] failed with : waiting for server-url setting to be set
2018/10/25 03:23:32 [ERROR] ClusterController local [cluster-deploy] failed with : waiting for server-url setting to be set
2018/10/25 03:23:32 [INFO] Updating workload [ingress-nginx/nginx-ingress-controller] with public endpoints [[{"nodeName":"local:machine-7ftgj","addresses":["rancher2-lab2-4.auiag.corp"],"port":80,"protocol":"TCP","podName":"ingress-nginx:nginx-ingress-controller-25l8f","allNodes":false},{"nodeName":"local:machine-7ftgj","addresses":["rancher2-lab2-4.auiag.corp"],"port":443,"protocol":"TCP","podName":"ingress-nginx:nginx-ingress-controller-25l8f","allNodes":false},{"nodeName":"local:machine-tjbdj","addresses":["rancher2-lab2-6.auiag.corp"],"port":80,"protocol":"TCP","podName":"ingress-nginx:nginx-ingress-controller-gn6bf","allNodes":false},{"nodeName":"local:machine-tjbdj","addresses":["rancher2-lab2-6.auiag.corp"],"port":443,"protocol":"TCP","podName":"ingress-nginx:nginx-ingress-controller-gn6bf","allNodes":false},{"nodeName":"local:machine-79c6c","addresses":["rancher2-lab2-5.auiag.corp"],"port":80,"protocol":"TCP","podName":"ingress-nginx:nginx-ingress-controller-57vsr","allNodes":false},{"nodeName":"local:machine-79c6c","addresses":["rancher2-lab2-5.auiag.corp"],"port":443,"protocol":"TCP","podName":"ingress-nginx:nginx-ingress-controller-57vsr","allNodes":false}]]
2018/10/25 03:23:32 [INFO] Updating workload [ingress-nginx/nginx-ingress-controller] with public endpoints [[{"nodeName":"local:machine-7ftgj","addresses":["rancher2-lab2-4.auiag.corp"],"port":80,"protocol":"TCP","podName":"ingress-nginx:nginx-ingress-controller-25l8f","allNodes":false},{"nodeName":"local:machine-7ftgj","addresses":["rancher2-lab2-4.auiag.corp"],"port":443,"protocol":"TCP","podName":"ingress-nginx:nginx-ingress-controller-25l8f","allNodes":false},{"nodeName":"local:machine-tjbdj","addresses":["rancher2-lab2-6.auiag.corp"],"port":80,"protocol":"TCP","podName":"ingress-nginx:nginx-ingress-controller-gn6bf","allNodes":false},{"nodeName":"local:machine-tjbdj","addresses":["rancher2-lab2-6.auiag.corp"],"port":443,"protocol":"TCP","podName":"ingress-nginx:nginx-ingress-controller-gn6bf","allNodes":false},{"nodeName":"local:machine-79c6c","addresses":["rancher2-lab2-5.auiag.corp"],"port":80,"protocol":"TCP","podName":"ingress-nginx:nginx-ingress-controller-57vsr","allNodes":false},{"nodeName":"local:machine-79c6c","addresses":["rancher2-lab2-5.auiag.corp"],"port":443,"protocol":"TCP","podName":"ingress-nginx:nginx-ingress-controller-57vsr","allNodes":false}]]
2018/10/25 03:23:36 [ERROR] ClusterController local [cluster-deploy] failed with : waiting for server-url setting to be set
2018/10/25 03:23:36 [ERROR] ClusterController local [cluster-deploy] failed with : waiting for server-url setting to be set
2018/10/25 03:24:12 [INFO] Updating pod [ingress-nginx/nginx-ingress-controller-wrrqd] with public endpoints [[{"nodeName":"local:machine-rgbb5","addresses":["rancher2-lab2-1.auiag.corp"],"port":80,"protocol":"TCP","podName":"ingress-nginx:nginx-ingress-controller-wrrqd","allNodes":false},{"nodeName":"local:machine-rgbb5","addresses":["rancher2-lab2-1.auiag.corp"],"port":443,"protocol":"TCP","podName":"ingress-nginx:nginx-ingress-controller-wrrqd","allNodes":false}]]
2018/10/25 03:24:12 [INFO] Updating workload [ingress-nginx/nginx-ingress-controller] with public endpoints [[{"nodeName":"local:machine-7ftgj","addresses":["rancher2-lab2-4.auiag.corp"],"port":80,"protocol":"TCP","podName":"ingress-nginx:nginx-ingress-controller-25l8f","allNodes":false},{"nodeName":"local:machine-7ftgj","addresses":["rancher2-lab2-4.auiag.corp"],"port":443,"protocol":"TCP","podName":"ingress-nginx:nginx-ingress-controller-25l8f","allNodes":false},{"nodeName":"local:machine-tjbdj","addresses":["rancher2-lab2-6.auiag.corp"],"port":80,"protocol":"TCP","podName":"ingress-nginx:nginx-ingress-controller-gn6bf","allNodes":false},{"nodeName":"local:machine-tjbdj","addresses":["rancher2-lab2-6.auiag.corp"],"port":443,"protocol":"TCP","podName":"ingress-nginx:nginx-ingress-controller-gn6bf","allNodes":false},{"nodeName":"local:machine-79c6c","addresses":["rancher2-lab2-5.auiag.corp"],"port":80,"protocol":"TCP","podName":"ingress-nginx:nginx-ingress-controller-57vsr","allNodes":false},{"nodeName":"local:machine-79c6c","addresses":["rancher2-lab2-5.auiag.corp"],"port":443,"protocol":"TCP","podName":"ingress-nginx:nginx-ingress-controller-57vsr","allNodes":false},{"nodeName":"local:machine-rgbb5","addresses":["rancher2-lab2-1.auiag.corp"],"port":80,"protocol":"TCP","podName":"ingress-nginx:nginx-ingress-controller-wrrqd","allNodes":false},{"nodeName":"local:machine-rgbb5","addresses":["rancher2-lab2-1.auiag.corp"],"port":443,"protocol":"TCP","podName":"ingress-nginx:nginx-ingress-controller-wrrqd","allNodes":false}]]
2018/10/25 03:24:12 [INFO] Updating ingress [cattle-system:rancher] with public endpoints [[{"addresses":["","","",""],"port":443,"protocol":"HTTPS","serviceName":"cattle-system:rancher","ingressName":"cattle-system:rancher","hostname":"rancher.middleware-lab-1.auiag.corp","allNodes":false}]]
2018/10/25 03:24:12 [INFO] Updating workload [cattle-system/rancher] with public endpoints [[{"addresses":["","","",""],"port":443,"protocol":"HTTPS","serviceName":"cattle-system:rancher","ingressName":"cattle-system:rancher","hostname":"rancher.middleware-lab-1.auiag.corp","allNodes":false}]]
2018/10/25 03:24:12 [INFO] Updating workload [cattle-system/rancher] with public endpoints [[{"addresses":["","","",""],"port":443,"protocol":"HTTPS","serviceName":"cattle-system:rancher","ingressName":"cattle-system:rancher","hostname":"rancher.middleware-lab-1.auiag.corp","allNodes":false}]]
2018/10/25 03:24:55 [ERROR] ClusterController local [cluster-deploy] failed with : waiting for server-url setting to be set
2018/10/25 03:24:59 [INFO] Creating token for user user-q8bcg
time="2018-10-25 03:24:59" level=info msg="Telemetry Client v0.5.1"
time="2018-10-25 03:24:59" level=info msg="Listening on 0.0.0.0:8114"
2018/10/25 03:25:02 [WARNING] error updating ns user-q8bcg status: Operation cannot be fulfilled on namespaces "user-q8bcg": the object has been modified; please apply your changes to the latest version and try again

**Comment by superseb** [comment] 2018-10-25 06:49
Duplicate of https://github.com/rancher/rancher/issues/16213

**Closed by superseb** 2018-10-25 06:49 UTC
