### ISSUE TITLE
Can't edit cluster if both cluster and Rancher server go down

### ISSUE THREAD

**Issue by cloudnautique** [rancher/rancher#13167] opened 2018-04-27 20:06 UTC
Rancher 2.0-x
If both the cluster and Rancher server go down at the same time, and then Rancher server comes back up first. The detection logic for the cluster doesn't get run, and the UI isn't able to determine that it should not communicate with the cluster endpoint.

Reproduce:

1. Launch rancher/rancher
2. import or create a cluster
3. change IP of server (Go from office to home on a laptop)
4. Start back up
5. Click edit in the UI.

Ideally a user can get to the edit screen to get the registration URL or Docker commands to re-run registration.

**Comment by deniseschannon** [comment] 2019-04-09 05:36
Duplicate of https://github.com/rancher/rancher/issues/14731

Currently, support for changing server-url doesn't exist.

**Closed by deniseschannon** 2019-04-09 05:36 UTC
Labels: area/backup-recover, kind/feature
