### ISSUE TITLE
Cluster goes to unavailable because failed to communicate with API server: i/o timeout

### ISSUE THREAD

**Issue by ldipaolaIT** [rancher/rancher#30959] opened 2021-01-22 20:56 UTC
**What kind of request is this (question/bug/enhancement/feature request):**
QUESTION/BUG

**Steps to reproduce (least amount of steps as possible):**
IT HAPPENS RANDOMLY

**Result:**
I GET FROM RANCHER BELOW MESSAGE RANDOMLY AND I LOSE CONNECTIVITY WITH A K8S CLUSTER:
Cluster health check failed: Failed to communicate with API server: Get "https://X.X.X.X:6443/api/v1/namespaces/kube-system?timeout=45s": write tcp X.X.X.X:443->X.X.X.X:58260: i/o timeout

**Other details that may be helpful:**
INSIDE RANCHER NODE, I SEE BELOW ERROR:
2021/01/22 20:54:33 [ERROR] error syncing 'u-isxe45ee6z': handler cat-user-attribute-controller: Put "https://X.X.X.X:6443/apis/cluster.cattle.io/v3/namespaces/cattle-system/clusteruserattributes/u-isxe45ee6z": write tcp X.X.X.X:443->X.X.X.X:44508: i/o timeout, requeuing

INSIDE A WORKER NODE, I SEE BELOW ERROR:
http: proxy error: write tcp 172.17.0.2:443 -> X.X.X.X:41234: write: connection reset by peer

AFTER A FEW MINUTES, IT CONNECTS AGAIN.
IN SOME CASES, THE CONNECTION WAS RESTABLISHED BY RESTARTING THE CATTLE AGENT CONTAINER OR BY DELETING IT (IT WAS REBUILT AUTOMATICALLY).

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): v2.5.1
- Installation option (single install/HA): SINGLE INSTALL

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): VMWARE HOSTED

- Machine type (cloud/VM/metal) and specifications (CPU/memory):
VMs
Master Nodes: 2 Cores - 8 GB RAM
Worker Nodes: 8 Cores - 32 GB RAM

- Kubernetes version (use `kubectl version`): 

```
(paste the output here)
```

- Docker version (use `docker version`): 
Docker version 17.03.2-ce, build f5ec1e2

```
(paste the output here)
```

**Comment by ldipaolaIT** [comment] 2021-01-25 12:26
Any light on this? Thanks in advance!

**Comment by romanwoessner** [comment] 2021-02-19 15:07
We are experiencing the exact same issue on Rancher v2.5.5 with two of our vSphere clusters.
In some cases the connection between Rancher and the API server gets reestablished after a few minutes.

**Comment by dulm** [comment] 2021-02-23 16:18
same problom

**Comment by mbu147** [comment] 2021-02-24 17:06
+1

**Comment by 463024907** [comment] 2021-02-27 11:29
+1 same problem with v2.4.8

**Comment by micw** [comment] 2021-03-05 12:48
I had this issue a moment ago with rancher 2.5.5. Api was unavailable for a few minutes. I checked connectivitiy between nodes - everything was fine. While I was still searching for an issue, it suddenly got working.

**Comment by AlessioCasco** [comment] 2021-03-24 00:09
+1 same problem with v2.5.5 deployed in AWS

**Comment by gricuk** [comment] 2021-03-29 17:00
+1 with 2.5.5, also VMWARE hosted

**Comment by godocean** [comment] 2021-04-14 11:05
I met the same issue with v2.4.5.
How to increase the timeout between rancher and k8s API server? My timeout is 30s, I think it's related to the response of API server, sometimes it works out and sometime error happened.

**Comment by AlessioCasco** [comment] 2021-05-04 18:29
+1 same problem with v2.5.7 deployed over k3s in AWS
It seems [this article](https://support.rancher.com/hc/en-us/articles/360058516672) was written to address the issue, but unfortunately it's still happening for me even tho my version is not the one affected.

**Comment by timmy59100** [comment] 2021-06-01 15:22
Same with 2.5.8.
Fixed by deleting cattle-node-agent.

**Comment by thbiela** [comment] 2021-06-05 19:22
Same problem using 2.5.8 and hetzner cloud provider. Any ideas?

**Comment by vj-gsr** [comment] 2021-06-07 06:33
Upgraded rancher to `2.5.8` and started observing this very often now - any permanent fix for this?

**Comment by HarborZeng** [comment] 2021-06-08 07:07
Same problem occurred after a few days of normal run.

Rancher runs in single install mode, with 5 physical machines in the same network.

I can't execute `kubectl xxx` in control node, because it won't response.

Is this fixable? How to? Or do I have to delete all the containers in my 5 machines, and reinstall HA mode?

**Comment by Johann-Foerster** [comment] 2021-07-07 15:02
+1 v2.5.5 vSphere clusters, rancher in single docker install mode. Any fix? Does Rancher HA help?

**Comment by soo-cubus** [comment] 2021-08-05 07:53
Same, rancher v2.4.5, vmware sphere hosted

**Comment by AlessioCasco** [comment] 2021-08-05 08:58
Updated to `v2.5.9` 2 weeks ago and so far the issue hasn't occurred.
I'd wait 2/3 more weeks before claim victory.

Deployed over 3 k3s nodes in AWS

**Comment by vj-gsr** [comment] 2021-08-05 11:23
Same here. We were running `v2.5.8` and facing this, contacted rancher supported and they have advised upgrading to `v2.5.9`.  This is very recent tho. will update if it really solves the issue.

**Comment by IlyaNakhaichuk** [comment] 2021-08-05 12:25
@vj-gsr Did it help you after the update?

**Comment by AlessioCasco** [comment] 2021-08-06 12:08
> Updated to `v2.5.9` 2 weeks ago and so far the issue hasn't occurred.
> I'd wait 2/3 more weeks before claim victory.
> 
> Deployed over 3 k3s nodes in AWS

forget it, it's just happened to me now

**Comment by dannyfranca** [comment] 2021-08-08 14:55
same here, rancher 2.5.9 in k3s cluster importing another k3s cluster

**Comment by claytonsilva** [comment] 2021-08-08 16:59
X

Em qua., 7 de jul. de 2021 12:02, Johann-Foerster ***@***.***>
escreveu:

**Comment by vj-gsr** [comment] 2021-08-10 04:02
`2.5.9` is a false promise guys, the issue still persists. It happed to us after the upgrade too :(

**Comment by ralff2208** [comment] 2021-08-11 15:21
Hi guys, I had the same problem but I did the mistake, I'm using AWS resources so I configure ALB to expose my rancher console, so I didn't create the Security Group rules to allow my workers, controlplane and etcd servers to connect in that ALB, So I add this rules on SG and now it's work well, I dont know if this could help, but that is it.

**Comment by dannyfranca** [comment] 2021-08-12 12:38
Other case and possible solution:

Rancher v2.5.9 in a RKE2 cluster, importing an RKE cluster.
Control plane in a t3a.small EC2 instance.

After reboot control plane instance rancher informed Disk pressure in this contorl plane instance. Increasing volume size and rebooting again solved the problem.

I dont know if its connected, but Rancher can't find out real problem before control plane reboot.

**Comment by ThoSap** [comment] 2021-09-08 14:42
Had the same issue today with Rancher `v2.5.9` and RKE `v1.19.14-rancher1-1`, VMware vSphere hosted.
We did not reboot the etcd/Control Plane, it fixed itself after ~10 minutes...

**Comment by kikolouro** [comment] 2021-09-15 10:37
Same with Rancher v2.5.9

**Comment by iosifnicolae2** [comment] 2021-09-24 12:55
Same issue in v2.5.9

Any idea how to debug the problem?

**Comment by martin-sucha** [comment] 2021-09-26 08:06
> Any idea how to debug the problem?

i/o timeout in Go can mean for example DNS timeout or TCP timeout. Since there is IP address in the error message, it looks like an issue with the connection or the API server.

I'm not a Rancher/Kubernetes developer, but gathering more data would help I suppose, as we don't have a reproducer for this issue.

* Capturing network dump during the incident.
* If some process is stuck, it would help to know what it is doing, so things like logs or information from runtime (Go [profiles](https://go.dev/blog/pprof), [traces](https://pkg.go.dev/runtime/trace) etc.) or strace. So perhaps gathering this information from the API server could help. Or maybe you could get some useful information by connecting a debugger to the process while the issue is happening.

**Comment by weisdd** [comment] 2021-10-14 10:43
@AlessioCasco thanks for sharing that!

We often get to see I/O timeouts as well. We've identified two cases so far:

1. Recv-Q is piling up, rancher doesn't read it, socket is still open:

```
# netstat -a -n
Active Internet connections (servers and established)
Proto Recv-Q Send-Q Local Address           Foreign Address         State
tcp6  5798978      0 172.16.210.7:80         172.16.210.12:55480     ESTABLISHED
```
traefik was trying to reach rancher, though the latter did not react to the packets sent to this port.
Also, some Send-Q seemed to also be stuck (not included in the snippet)

2. Recv-Q is piling up, rancher doesn't read it, socket is closing:

```
# netstat -a -n | grep -v "tcp        0      0"
Active Internet connections (servers and established)
Proto Recv-Q Send-Q Local Address           Foreign Address         State
tcp        0 321444 172.16.210.62:80        172.16.223.34:53948     ESTABLISHED
tcp        0 321444 172.16.210.62:80        172.16.223.34:53924     ESTABLISHED
tcp   1382175      0 172.16.210.62:80        172.16.223.34:53476     CLOSE_WAIT

# netstat -a -n | grep -v "tcp        0      0"
Active Internet connections (servers and established)
Proto Recv-Q Send-Q Local Address           Foreign Address         State
tcp        0 321444 172.16.210.62:80        172.16.223.34:53948     ESTABLISHED
tcp        0 321444 172.16.210.62:80        172.16.223.34:53924     ESTABLISHED
```

traefik, for some reasons, was still trying to reach rancher on the closed port.
Also, some Send-Q seemed to also be stuck.

In the end, since we already swapped out pretty much everything we could, we moved from traefik to nginx to see if it handles those connectivity issues better (e.g. if it can reestablish connection faster than traefik, that's already a big improvement). Atm, it's too early to say if we got any improvements here.

**Comment by AlessioCasco** [comment] 2021-10-14 11:00
@weisdd Thanks for your info.

We were also thinking of getting rid of traefik in favour of nginx, let me know your findings for the next weeks please.

**Comment by weisdd** [comment] 2021-10-14 15:48
@AlessioCasco did you check that inside rancher pods?
Most of connections will have zeroes, and only a few - non-zero values (those values are fine if numbers keep on changing).

**Comment by timmy59100** [comment] 2021-11-03 08:08
Did anyone have the problem with 2.5.10?:
The API Server has been updated to fix slow consumers causing deadlocks. See #34907.

**Comment by AlessioCasco** [comment] 2021-11-03 09:16
Hello people!

As mentioned above, I got confirmation from rancher that [2.5.11](https://github.com/rancher/rancher/releases/tag/v2.5.11) should have the issue fixed, I'll try to upgrade in the next days and see if the problem is solved.
Please share your findings after the upgrade.

@timmy59100 Nope, 2.5.10 doesn't have anything related this issue unfortunately.

**Comment by AlessioCasco** [comment] 2021-11-05 18:34
I've upgraded to 2.5.11 today, will keep you posted with the findings

**Comment by AlessioCasco** [comment] 2021-11-08 15:06
It turns out Rancher told me a wrong info:

```text
hello Alessio, I can confirm that the 2.5.11 release was only a CVE release and did not contain any previously planned bug fixes.  Those bug fixes have been pushed to our next release.
```

So do not update to 2.5.11 if you want to have this issue fixed

**Comment by norcis** [comment] 2021-11-19 05:31
2.6.2 similar problems.
`[Error] cluster health check failed: Failed to communicate with API server during namespace check: Get "https://10.43.0.1:443/api/v1/namespaces/kube-system?timeout=45s": context deadline exceeded`

**Comment by timothystewart6** [comment] 2021-11-24 23:36
Same on 2.6.2.  This happened after clicking "Redeploy" on 4-5 deployments.  It recovered after about 5 minutes.  Deployments were fine, only rancher UI seemed to be impacted.

```bash
HTTP Error 500: Internal Server Error
{"data":"write tcp 10.42.1.64:443->10.42.1.1:58500: i/o timeout"}
```

**Comment by julienleboeuf** [comment] 2021-11-25 13:51
Still same problem with 2.6.2 but oddly when it occurs with new UI, it can work sometimes work with legacy UI

**Comment by hyj-github** [comment] 2021-11-30 06:04
I often encounter this problem, and every time I solve it by restarting the rancher container. Is there a better solution?

**Comment by daleckystepan** [comment] 2021-11-30 06:25
Just wait a few minutes.

**Comment by hyj-github** [comment] 2021-11-30 06:56
> Just wait a few minutes.

I waited a while, but I couldn't connect, so I ended up restarting the container！

**Comment by hyj-github** [comment] 2021-12-01 02:11
I have three clusters, one of which is frequently disconnected from Rancher, and the other two are fine. Is this problem related to cluster?

**Comment by hyj-github** [comment] 2021-12-02 07:57
> It turns out Rancher told me a wrong info:
> 
> ```
> hello Alessio, I can confirm that the 2.5.11 release was only a CVE release and did not contain any previously planned bug fixes.  Those bug fixes have been pushed to our next release.
> ```
> 
> So do not update to 2.5.11 if you want to have this issue fixed

I found the problem in the Rancher documentation.[rancher](https://rancher.com/docs/rancher/v2.5/en/troubleshooting/networking/#check-if-mtu-is-correctly-configured-on-hosts-and-on-peering-tunnel-appliances-devices)

**Comment by LivesMountain** [comment] 2021-12-07 08:54
I have the same problem!!!wait for solution

**Comment by AlessioCasco** [comment] 2021-12-17 12:00
Hello everyone!
I got some news from rancher: They told me that they have now identified an issue with the same behaviour in another customer and a fix for that issue is scheduled into `v2.5.12`, which is currently targeted for a mid-January release.
I've asked if there is an idea on when this will be ported to `v2.6.x`

I'll keep you posted as soon as I have news

**Comment by AlessioCasco** [comment] 2022-01-18 08:35
Hello!
Some quick updates about this:

Rancher just communicated that the fix for this issue is still scheduled into the next Rancher v2.6 patch release (currently as v2.6.4 and scheduled for a March release)
The issue itself was tracked and fixed in https://github.com/rancher/remotedialer/pull/36

**Comment by hyj-github** [comment] 2022-01-19 12:22
> Hello everyone! I got some news from rancher: They told me that they have now identified an issue with the same behaviour in another customer and a fix for that issue is scheduled into `v2.5.12`, which is currently targeted for a mid-January release. I've asked if there is an idea on when this will be ported to `v2.6.x`
> 
> I'll keep you posted as soon as I have news

It's mid-January and v2.5.12 hasn't been released yet.
Do you have any news about the new rancher release?

**Comment by junkiebev** [comment] 2022-01-28 20:38
I'm still seeing the behavior, albeit not nearly as often, in `v2.5.12`

**Comment by AlessioCasco** [comment] 2022-02-02 23:30
Hi everyone!

Rancher just told me that the fix went into 2.5.12 and 2.6.3-patch1 versions. They believe the issue will be resolved by the fix, but there is still a chance that they might have missed something.

Please test and report back if you see improvements

Thanks
Alessio

**Comment by snasovich** [comment] 2022-02-04 17:19
This should be addressed by the same fix as https://github.com/rancher/rancher/issues/34819 with changes getting into 2.5.12 and 2.6.3-patch1.

Please note that the fix requires the new code to be running in both the Rancher server and the downstream cluster agents.  After the Rancher server upgrade, the cluster agent for a time period will be running the old agent until they are upgraded. If you experience these errors during upgrade or shortly afterwards this is OK. However, if you see these errors after the initial stabilization passes, please let us know.

**Closed by snasovich** 2022-02-04 17:19 UTC
Labels: team/area2

**Comment by asavich-intellective** [comment] 2022-09-22 08:08
Using rancher 2.6.7 and have this issue

**Comment by d70rr3s** [comment] 2023-01-25 18:54
I was facing this issue with a clean cluster setup and was driving nuts, probably sounds like topic but, I just restarted the kube-apiserver container and started working.

**Comment by admejia2** [comment] 2023-03-03 19:20
i had the same issue and could fixed, first step check resources of nodes if are sufficient (memory/cpu) after increased at least 8 Gb ram i could found real issue token expired of rancher. 

kubectl -n cattle-system get secret -o json | jq -r '.items[].metadata | select(.annotations."kubernetes.io/service-account.name" == "rancher") | .name'
 kubectl -n cattle-system delete secret rancher-token-xxxxxxx
kubectl rollout restart deployment rancher -n cattle-system

**Comment by manning-ncsa** [comment] 2023-11-21 20:03
@admejia2 This is happening to me on Rancher v2.7.5 but only on a Kubernetes cluster I created recently. Your solution of deleting the token worked for me, with slightly modified commands due to `rancher` apparently being `cattle` on my system:
```bash
CATTLE_TOKEN=$(kubectl -n cattle-system get secret -o json | jq -r '.items[].metadata | select(.annotations."kubernetes.io/service-account.name" == "cattle") | .name')
kubectl -n cattle-system delete secret $CATTLE_TOKEN
kubectl rollout restart deployment cattle-cluster-agent -n cattle-system
```

**Comment by lteixeira-dock** [comment] 2024-03-20 17:24
I had the same issue in Rancher v2.7.5, only in one EKS Fargate Cluster. The solution of deleting the token worked for me.

**Comment by meektechie** [comment] 2025-01-02 12:39
For me, It was because of Disk utilization on node end. After increasing the volume the issue got resolved
