### ISSUE TITLE
[Suggestion] Support for Azure Active Directory as Access Control

### ISSUE THREAD

**Issue by kvaes** [rancher/rancher#4242] opened 2016-03-31 08:43 UTC
Rancher Version: New

Motivation: Azure Active Directory has become one of the new defaults for my windows based shops.

**Comment by deniseschannon** [comment] 2016-06-28 04:14
Pre-Duplicate of https://github.com/rancher/rancher/issues/4918

This was added in v1.1.0-dev5.

**Closed by deniseschannon** 2016-06-28 04:14 UTC
Labels: area/access-control, kind/feature
