### ISSUE TITLE
Sometimes Cannot add nodes to custom cluster.

### ISSUE THREAD

**Issue by aaronyeeski** [rancher/rancher#25635] opened 2020-02-27 20:38 UTC
**What kind of request is this (question/bug/enhancement/feature request):**
bug

**Steps to reproduce (least amount of steps as possible):**
Install Rancher master-head in HA using k3s nodes.
https://staging.rancher.com/docs/rancher/v2.x/en/installation/k8s-install/create-nodes-lb/
Rancher install command:
```
helm install rancher rancher-alpha/rancher --namespace cattle-system --set hostname=<hostname> --version 2.4.0-alpha1  --set rancherImageTag=master-head
```
In Rancher, create a 1 node custom cluster, all roles.
After the cluster comes up active, add 2 more nodes to the cluster with all roles.

**Result:**
Cluster is stuck updating with:
```
Host must be a URL or a host:port pair: "https://"; host must be a URL or a host:port pair: "https://"
```
![Screen Shot 2020-02-27 at 10 18 14 AM](https://user-images.githubusercontent.com/57409052/75484356-df3b5d00-5965-11ea-84fe-5f3750963dc0.png)

**Other details that may be helpful:**
This behavior is inconsistent. Indicative of a timing issue.

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI):
`rancher\rancher:master-head` `version ca71db485`
- Installation option (single install/HA): HA

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): custom
- Kubernetes version (use `kubectl version`): 

```
v1.17.3-rancher1-1
```

- Docker version (use `docker version`):

```
19.03.2
```

**Comment by deniseschannon** [comment] 2020-02-28 15:17
@aaronRancher @sangeethah  is this happening in RKE HA installs as well? 

This assumes that you get past: https://github.com/rancher/rancher/issues/25524

**Comment by sangeethah** [comment] 2020-02-28 15:20
There is no getting past https://github.com/rancher/rancher/issues/25524 . These issues are not always reprodiucible.

**Comment by deniseschannon** [comment] 2020-03-03 18:44
@aaronRancher @sangeethah Next time you have a setup for these intermittent setups, can you please let engineering know so we can look at it?

**Comment by deniseschannon** [comment] 2021-12-02 20:19
Since QA hasn't reproduced or hit this issue in the last 9 months, I'm going to close the issue.

**Closed by deniseschannon** 2021-12-02 20:19 UTC
Labels: kind/bug-qa, [zube]: Need Info, team/area2
