### ISSUE TITLE
[rancher-dns] cloudflare json error

### ISSUE THREAD

**Issue by spidercpsf** [rancher/rancher#4501] opened 2016-04-21 17:33 UTC
Rancher Version:
 1.0.1
Docker Version:
1.10.3
OS: 
Ubuntu
Steps to Reproduce: 
Using rancher-dns with cloudflare
Results: 
4/22/2016 12:30:25 AMtime="2016-04-21T17:30:25Z" level=fatal msg="Failed to set zone for root domain *****: CloudFlare API call has failed: json: cannot unmarshal number into Go value of type string"

**Comment by vincent99** [comment] 2016-04-21 22:17
Duplicate of https://github.com/rancher/rancher/issues/4482 -- Cloudflare changed their API and broke strongly-typed clients.

**Closed by vincent99** 2016-04-21 22:17 UTC
