### ISSUE TITLE
[BUG] all-roles K3s cluster hits `Failed to communicate with API server error`, intermittently when scaling up/down, after a manual snapshot is taken

### ISSUE THREAD

**Issue by Josh-Diamond** [rancher/rancher#43329] opened 2023-10-30 18:18 UTC
**Rancher Server Setup**
- Rancher version: `v2.8.0-rc3`
- Installation option (Docker install/Helm Chart): `Docker`

**Information about the Cluster**
- Kubernetes version: `v1.27.6+k3s1`
- Cluster Type (Local/Downstream): All-roles Downstream AWS Node driver

**User Information**
- What is the role of the user logged in? `Admin`

**Describe the bug**
Intermittently, when scaling all-roles k3s Node driver clusters, the cluster will enter an `error` state w/ the following message: `cluster health check failed: Failed to communicate with API server during namespace check: apiserver not ready`

**To Reproduce**
1. Fresh install of Rancher `v2.8.0-rc3`
2. Provision a single-node downstream AWS Node driver cluster w/ all-roles + k8s `v1.27.6+k3s1`
3. Once `active`, manually take a snapshot
4. Once captured, scale the cluster up to 3 total nodes, scaling up 1 at a time
5. Once scaled up, delete the init node
6. Once init node has been removed, scale the cluster back down to 1 node
7. Reproduced 

**Result**
Cluster stuck in `Error` state w/ the following error seen on one of the machines: `Error applying plan -- check rancher-system-agent.service logs on node for more information`

**Expected Result**
Cluster expected to successfully scale back down to 1 node

**Screenshots**
![image (39)](https://github.com/rancher/rancher/assets/46494969/e1c2e8b6-16f7-4fb2-95f6-af86cda2b13a)

**Additional context**
empty logs on node(machine?) in error state
```logs
-- Logs begin at Mon 2023-10-30 17:34:13 UTC. --
```

Rancher Server logs
```logs
2023/10/30 18:20:27 [ERROR] error syncing 'c-m-<REDACTED>': handler cluster-deploy: apiserver not ready, requeuing
2023/10/30 18:20:27 [INFO] [planner] rkecluster fleet-default/jkeslar-k3s-new: configuring bootstrap node(s) jkeslar-k3s-new-pool1-<REDACTED>: error applying plan -- check rancher-system-agent.service logs on node for more information, waiting for probes: kube-apiserver, kube-controller-manager, kube-scheduler, kubelet
2023/10/30 18:20:38 [ERROR] error syncing 'fleet-default/jkeslar-k3s-new-bootstrap-template-<REDACTED>': handler rke-bootstrap-cluster-name: apiserver not ready, requeuing
W1030 18:21:39.268748      38 warnings.go:80] cluster.x-k8s.io/v1alpha3 MachineSet is deprecated; use cluster.x-k8s.io/v1beta1 MachineSet
W1030 18:22:23.206043      38 warnings.go:80] cluster.x-k8s.io/v1alpha3 Machine is deprecated; use cluster.x-k8s.io/v1beta1 Machine
2023/10/30 18:22:27 [ERROR] error syncing 'c-m-<REDACTED>': handler cluster-deploy: apiserver not ready, requeuing
2023/10/30 18:22:27 [INFO] [planner] rkecluster fleet-default/jkeslar-k3s-new: configuring bootstrap node(s) jkeslar-k3s-new-pool1-<REDACTED>: error applying plan -- check rancher-system-agent.service logs on node for more information, waiting for probes: kube-apiserver, kube-controller-manager, kube-scheduler, kubelet
2023/10/30 18:22:38 [ERROR] error syncing 'fleet-default/jkeslar-k3s-new-bootstrap-template-<REDACTED>': handler rke-bootstrap-cluster-name: apiserver not ready, requeuing
```

**Comment by jakefhyde** [comment] 2023-10-30 22:39
This is currently believed to be caused by https://github.com/rancher/rancher/pull/43230, which was an intended fix for https://github.com/rancher/rancher/issues/43097. This fix was intended to move the etcd safe member removal to before a node is drained, effectively removing it as a participating etcd member, but allowing it to remain as a node in the cluster. However, since k3s does not run etcd as a static pod, this appears to be causing issues wherein removing it from etcd prior to draining causes a complete node failure and prevents the safe node removal from ever succeeding correctly.

**Comment by snasovich** [comment] 2023-10-31 19:10
With revert PR https://github.com/rancher/rancher/pull/43330 merged, this will be available to be tested on `v2.8-head` once https://drone-publish.rancher.io/rancher/rancher/10922 (or later build) passes. This issue can be moved "To Test" after that.

**Comment by snasovich** [comment] 2023-10-31 22:12
@Josh-Diamond , ready to test now since the build passed. If the issue is no longer reproducible, please close it and also remove the milestone as technically this issue was not present in any released version so it doesn't seem right to close it with `v2.8.0` milestone as it wasn't "fixed" in that milestone. FYI @daviswill2 @Jono-SUSE-Rancher

**Comment by Josh-Diamond** [comment] 2023-11-01 17:10
Ticket #43329 - Test Results - ✅ 
---

Verified on Rancher `v2.8-5649fafcd786cbe61c6e4a8518ca3aede25601f9-head`:
| Scenario | Test Case | Result |
|---|---|---|
| 1. | cluster1 | ✅ |
| 2. | cluster2 | ✅ |
| 3. | cluster3 | ✅ |
| 4. | cluster4 | ✅ |
| 5. | cluster5 | ✅ |

The following scenario was **successfully** executed on 5 clusters:
1. Fresh install of Rancher `v2.8-head`
2. Provision a single-node all-roles downstream K3s AWS Node driver w/ k8s `v1.27.7+k3s1`
3. Once `active`, take a manual snapshot
4. Once captured, scale up cluster by 1
5. Verified - cluster successfully scales up; total nodes now 2
6. Scale up the cluster by 1, once more
7. Verified - cluster successfully scales up; total nodes now 3
8. Scale down the cluster by 1
9. Verified - cluster successfully scales down; total nodes now 2
10. Scale down cluster by 1, once more
11. Verified - cluster successfully scales down; as expected

**Closed** 2023-11-01 17:11 UTC
Labels: kind/bug, [zube]: QA Working, status/release-blocker, team/area2
