### ISSUE TITLE
Backport Cannot edit load-balancer or service discovery yaml #19723

### ISSUE THREAD

**Issue by cjellick** [rancher/rancher#20032] opened 2019-05-07 18:35 UTC
Backport for https://github.com/rancher/rancher/issues/19723

**Comment by jordanandres1** [comment] 2019-05-07 19:51
This issue is also happening in version 2.2.2 rancher:stable

**Comment by davidnuzik** [comment] 2019-05-07 22:04
Version: v2.1.7 -> v2.2.3-rc7

The problem is when you try to View/Edit YAML of LB, Service (Ingress), Secrets, Config Maps.
I tested all of these. We can now view/edit YAML for each without any issues post-upgrade. See the #19723 issue for details about this. Issue only happens with HA upgrades and is now fixed.

**Comment by davidnuzik** [comment] 2019-05-15 16:54
Re-opened issue for me to take a look at and try to reproduce what was reported  in originating issue #19723 because this should be fixed based on my testing done in v2.2.3-rc7 recently.
I will need to check cronJob view/edit yaml as well.

**Comment by davidnuzik** [comment] 2019-05-15 18:57
UPDATE:
There was some confusion. v2.2.3 does NOT have this fix. This is because we had to cut a v2.2.3 release to fix a significant issue with monitoring. Thus v2.2.3 release does NOT contain this fix. The unsupported rc's will, but this should never be used in production.

I have re-opened this issue to double-check and validate _again_ in v2.2.4-rc1 or newer rc.

**Comment by davidnuzik** [comment] 2019-05-16 17:53
Version: v2.1.7 -> v2.2.4-rc2 (HA Setup)

I tested this again, just to make doubly sure everything looks good in 2.2.4. I again checked Service (Ingress) with a xip.io and l4 lb, Secrets, Config maps, and now also included a check with cronjob workload as this was mentioned in the originating issue.

During my tests I encountered no issues when I try to edit/view YAML post-upgrade. No unexpected warnings/errors in browser dev console as well. You might see an error when attempt to view/edit YAML and this is NOT related to this issue. It doesn't break anything. This is tracked here: #20249 

Again, note this problem only affects an HA setup AND with upgrades to newer rancher 2.2.3 and earlier.

**Closed by davidnuzik** 2019-05-16 17:53 UTC
Labels: [zube]: To Test, kind/bug, status/resolved, team/az
