### ISSUE TITLE
Custom catalogues with mixed-case names no longer work under 0.63.0

### ISSUE THREAD

**Issue by sshipway** [rancher/rancher#3971] opened 2016-03-15 02:08 UTC
Rancher Version: 0.63.0

Docker Version: 1.9.1

OS: CoreOS

Steps to Reproduce: 
Create custom Catalogue on git server with at least one entry containing at least one parameter.
Add this to the Rancher custom Catalogues with a mixed-case name (eg, "Test")
Try to resynch catalogues
Try to create new item from this catalogue entry

Results: 
When updating catalogue, stays in 'rotating flower' update rathere than completing.
When creating new item, catalogue entry appears with README.md correct and all versions listed in dropdown, but form below is not shown, only the 'rotating flower'.

Expected:
Form to create new catalogue item should be displayed so that new item can be created

----

Tested with Rancher Library and Community catalogues, both work fine.  However local catalogue held in local Git server, plus copy of community catalogue on github, both have this issue.  Before update to 0.63.0 both were working correctly.  Forked copy of community catalogue used for test is identical to official community catalogue.

**Comment by vincent99** [comment] 2016-03-15 02:19
The refresh button is https://github.com/rancher/rancher/issues/3902 , it finishes but the API isn't returning an object like the UI expects.

There's nothing special about custom vs the standard official & community ones so the 2nd part is odd; Is there anything in the browser dev tools console or failed request in the network tab?

**Comment by sshipway** [comment] 2016-03-15 21:01
Only error message in console is
````
downloadable font: rejected by sanitizer (font-family: "rancher-icons" style:normal weight:normal stretch:normal src index:0) source: https://rancher.container.auckland.ac.nz/assets/fonts/rancher-icons-29e6a8f649f4772228422e9043c7459d.ttf?1cqlea
````
What there does seem to be is an 404 not found error for the page, when I click on one of the Templates in the catalogue and it tries to retrieve a specific version of the tmeplate:
````
GET XHR https://rancher.container.auckland.ac.nz/v1-catalog/templates/UOA:janitor [HTTP/1.1 200 OK 154ms]
GET XHR https://rancher.container.auckland.ac.nz/v1-catalog/templates/uoa:janitor:1 [HTTP/1.1 404 Not Found 155ms]
````
The Catalogue is called 'UOA' (in capitals) -- possibly something is going on with case-sensitivity in the name resulting in lower-casing the catalogue name and it then being wrong?

Both of my 'local' catalogues have mixed-case names and seem to have the same effect

**Comment by sshipway** [comment] 2016-03-15 21:05
@vincent99 -- Testing confirms that the problem is with Catalogues that have mixed-case names (the rancher-supplied Library and Community catalogues are lower-case).  If I rename one of my custom catalogues in lower-case only, then it works, but is displayed with the first letter capitalised!  This is definitely a problem as it means we cannot call our catalogue 'UOA' or even 'Community-Dev'.

**Comment by deniseschannon** [comment] 2016-03-15 21:43
Seems to be a duplicate of https://github.com/rancher/rancher/issues/3955

**Comment by prachidamle** [comment] 2016-03-15 22:46
Yes @deniseschannon, its the same issue https://github.com/rancher/rancher/issues/3955
The PR fixing the issue has been submitted.

**Comment by deniseschannon** [comment] 2016-03-16 04:16
Closing in favor of #3955

**Closed by deniseschannon** 2016-03-16 04:16 UTC
Labels: area/catalog-service, kind/bug, status/resolved
