### ISSUE TITLE
Cannot create EKS cluster using admin user role

### ISSUE THREAD

**Issue by alexandrem** [rancher/rancher#15102] opened 2018-08-16 20:40 UTC
**Rancher versions:**
rancher/server or rancher/rancher: v2.0.7
rancher/agent or rancher/rancher-agent: v2.0.7

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)** AWS

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)** HA on kubernetes

**Steps to Reproduce:**

1. Connect authentication to Active Directory
2. Validate AD auth with a user (Test and enable authentication) - this user is now linked to default admin role
3. Attempt to create a EKS cluster (enter access key + secret)
4. Immediate answer from API call is `400: null` 

**Results:**

I've been seeing this since at least v2.0.5

The UI will show immediately the error message `400: null` in red below the create button.
Looking at the ajax call, we see this is wrapped in json object and is the only response from the Rancher api.

Using a non admin user works correctly though.

**Comment by cjellick** [comment] 2018-09-12 00:10
When this is validated, make sure you attempt to repro in v2.0.7 before you attempt to repro in a 2.1 RC. If we can't repro with the version originally reported, then we may need more info

**Comment by cjellick** [comment] 2018-09-12 00:38
@StrongMonkey to validate

**Comment by StrongMonkey** [comment] 2018-09-13 18:53
Not able to reproduce it in v2.0.7. 
Steps:
1. Create  a fresh v2.0.7 rancher install. Configure AD authentication.
2. Login as the user which is used to configure AD authentication.
3. Be able to create a EKS cluster.

Once 2.1 RC is out i will reverify this.
@alexandrem Can you make sure the user you created do have the privilege to create cluster? We probably need more info to reproduce your issue.

**Comment by StrongMonkey** [comment] 2018-09-13 22:40
Also tested with the latest master, didn't reproduce the issue as well.

**Comment by cjellick** [comment] 2018-09-18 00:54
We've now had three engineers fail to reproduce. closing. @alexandrem feel free to open with more steps to repro if you can still repro

**Closed by cjellick** 2018-09-18 00:54 UTC
Labels: kind/bug, priority/1, status/more-info, status/to-test, status/to-validate, team/az, version/2.0
