### ISSUE TITLE
Can't get certs with Let's Encrypt on HA install

### ISSUE THREAD

**Issue by ba221400** [rancher/rancher#17816] opened 2019-02-01 21:14 UTC
**What kind of request is this (question/bug/enhancement/feature request):**
Question

**Steps to reproduce (least amount of steps as possible):**
Follow HA guide: https://rancher.com/docs/rancher/v2.x/en/installation/ha/ 

Using nginx as a layer 4 load balancer with example config (https://rancher.com/docs/rancher/v2.x/en/installation/ha/create-nodes-lb/nginx/) in front of 3 Rancher master nodes. Use cert-manager and Lets Encrypt to attempt to generate ssl certs. Load balancer has public IP address with domain/DNS associated with it. Port 80 and 443 are open.

**Result:**
Rancher and associated pods (ingress, cert-manager) all running successfully, but certs are never obtained. I can not manually navigate to the well-known address either, which makes me think the L4 load balancer isn't working or the ingress load balancer isn't working.

Ingress info:
```
Name:             cm-acme-http-solver-tr74p
Namespace:        cattle-system
Address:          x.x.x.x,x.x.x.y
Default backend:  default-http-backend:80 (<none>)
Rules:
  Host                   Path  Backends
  ----                   ----  --------
  rancher.mydomain.com
                         /.well-known/acme-challenge/Bf-oPbO34tgehadfI0k7Qsf_fza4rHUKC534easfO5TM   cm-acme-http-solver-xnw4t:8089 (<none>)
Annotations:
  field.cattle.io/publicEndpoints:  [{"addresses":["x.x.x.x","x.x.x.y"],"port":80,"protocol":"HTTP","serviceName":"cattle-system:cm-acme-http-solver-xnw4t","ingressName":"cattle-system:cm-acme-http-solver-tr74p","hostname":"rancher.mydomain.com","path":"/.well-known/acme-challenge/Bf-oPbO6hy7DdfI0k7Qsf_fza4rHUKC575duPOfO5TM","allNodes":false}]
Events:                             <none>


Name:             rancher
Namespace:        cattle-system
Address:          x.x.x.x,x.x.x.xy
Default backend:  default-http-backend:80 (<none>)
TLS:
  tls-rancher-ingress terminates rancher.mydomain.com
Rules:
  Host                   Path  Backends
  ----                   ----  --------
  rancher.mydomain.com
                            rancher:80 (<none>)
Annotations:
  certmanager.k8s.io/issuer:                          rancher
  field.cattle.io/publicEndpoints:                    [{"addresses":["x.x.x.x","x.x.xy"],"port":443,"protocol":"HTTPS","serviceName":"cattle-system:rancher","ingressName":"cattle-system:rancher","hostname":"rancher.mydomain.com","allNodes":false}]
  nginx.ingress.kubernetes.io/proxy-connect-timeout:  30
  nginx.ingress.kubernetes.io/proxy-read-timeout:     1800
  nginx.ingress.kubernetes.io/proxy-send-timeout:     1800
Events:                                               <none>
```
Ingress logs:
```
I0123 02:02:32.615026       7 controller.go:179] Backend successfully reloaded.
I0123 02:07:26.990283       7 event.go:218] Event(v1.ObjectReference{Kind:"Ingress", Namespace:"cattle-system", Name:"rancher", UID:"a18cc766-1eb3-11e9-a3a4-9c8e9916e498", APIVersion:"extensions", ResourceVersion:"1347", FieldPath:""}): type: 'Normal' reason: 'CREATE' Ingress cattle-system/rancher
W0123 02:07:26.990427       7 backend_ssl.go:49] error obtaining PEM from secret cattle-system/tls-rancher-ingress: error retrieving secret cattle-system/tls-rancher-ingress: secret cattle-system/tls-rancher-ingress was not found
W0123 02:07:30.307510       7 controller.go:769] Service "cattle-system/rancher" does not have any active Endpoint.
W0123 02:07:30.307607       7 controller.go:1015] SSL certificate "cattle-system/tls-rancher-ingress" does not exist in local store.
I0123 02:07:30.307675       7 controller.go:169] Configuration changes detected, backend reload required.
```

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): 2.1.5
- Installation option (single install/HA): HA

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): 
- Machine type (cloud/VM/metal) and specifications (CPU/memory):
- Kubernetes version (use `kubectl version`):

```
(paste the output here)
```

- Docker version (use `docker version`):

```
(paste the output here)
```

**Comment by nklmilojevic** [comment] 2019-02-02 21:42
Having the same problem as well.

**Comment by Flos** [comment] 2019-03-19 21:23
I have also the same setup and the same issue.

**Comment by rajha-korithrien** [comment] 2019-03-25 18:16
I am also having this problem following the same instructions. I can confirm the issue is not with my HA nginx proxy as I have confirmed packets get sent from the HA proxy system to each of the RKE provisioned nodes on port 80 when cert-manager tries to do a self test. Therefore the problem must be with the ingress setup by the Rancher helm chart.

Here is the log of my cert-manager
```
kubectl -n kube-system logs cert-manager-6464494858-9znlb
```
```
I0325 17:22:25.633379       1 start.go:79] starting cert-manager v0.5.2 (revision 9e8c3ad899c5aafaa360ca947eac7f5ba6301035)
I0325 17:22:25.634494       1 controller.go:126] Using the following nameservers for DNS01 checks: [10.43.0.10:53]
I0325 17:22:25.634997       1 leaderelection.go:175] attempting to acquire leader lease  kube-system/cert-manager-controller...
I0325 17:22:25.635465       1 server.go:84] Listening on http://0.0.0.0:9402
I0325 17:23:28.793842       1 leaderelection.go:184] successfully acquired lease kube-system/cert-manager-controller
I0325 17:23:28.794097       1 controller.go:68] Starting certificates controller
I0325 17:23:28.794159       1 controller.go:68] Starting clusterissuers controller
I0325 17:23:28.794172       1 controller.go:68] Starting ingress-shim controller
I0325 17:23:28.794959       1 controller.go:68] Starting issuers controller
I0325 17:23:28.894301       1 controller.go:168] ingress-shim controller: syncing item 'cattle-system/rancher'
I0325 17:23:28.894344       1 sync.go:140] Certificate "tls-rancher-ingress" for ingress "rancher" already exists
I0325 17:23:28.894366       1 sync.go:143] Certificate "tls-rancher-ingress" for ingress "rancher" is up to date
I0325 17:23:28.894378       1 controller.go:182] ingress-shim controller: Finished processing work item "cattle-system/rancher"
I0325 17:23:30.820095       1 controller.go:171] certificates controller: syncing item 'cattle-system/tls-rancher-ingress'
I0325 17:23:30.820268       1 sync.go:274] Preparing certificate cattle-system/tls-rancher-ingress with issuer
I0325 17:23:30.820436       1 logger.go:43] Calling GetOrder
I0325 17:23:31.149014       1 logger.go:73] Calling GetAuthorization
I0325 17:23:31.246788       1 logger.go:93] Calling HTTP01ChallengeResponse
I0325 17:23:31.246824       1 prepare.go:279] Cleaning up old/expired challenges for Certificate cattle-system/tls-rancher-ingress
I0325 17:23:31.246841       1 logger.go:68] Calling GetChallenge
I0325 17:23:31.432318       1 http.go:134] wrong status code '404'
I0325 17:23:31.432526       1 ingress.go:49] Looking up Ingresses for selector certmanager.k8s.io/acme-http-domain=1227163451,certmanager.k8s.io/acme-http-token=1177226878
I0325 17:23:31.432560       1 helpers.go:201] Found status change for Certificate "tls-rancher-ingress" condition "Ready": "False" -> "False"; setting lastTransitionTime to 2019-03-25 17:23:31.432555558 +0000 UTC m=+65.804544564
I0325 17:23:31.432597       1 sync.go:276] Error preparing issuer for certificate cattle-system/tls-rancher-ingress: http-01 self check failed for domain "argus.icasa.nmt.edu"
E0325 17:23:31.432658       1 sync.go:197] [cattle-system/tls-rancher-ingress] Error getting certificate 'tls-rancher-ingress': secret "tls-rancher-ingress" not found
E0325 17:23:31.438717       1 controller.go:180] certificates controller: Re-queuing item "cattle-system/tls-rancher-ingress" due to error processing: http-01 self check failed for domain "argus.icasa.nmt.edu"
I0325 17:23:31.438977       1 controller.go:168] ingress-shim controller: syncing item 'cattle-system/rancher'
I0325 17:23:31.439014       1 sync.go:140] Certificate "tls-rancher-ingress" for ingress "rancher" already exists
I0325 17:23:31.439026       1 sync.go:143] Certificate "tls-rancher-ingress" for ingress "rancher" is up to date
I0325 17:23:31.439033       1 controller.go:182] ingress-shim controller: Finished processing work item "cattle-system/rancher"
I0325 17:23:33.812815       1 controller.go:168] ingress-shim controller: syncing item 'cattle-system/rancher'
I0325 17:23:33.812876       1 sync.go:140] Certificate "tls-rancher-ingress" for ingress "rancher" already exists
I0325 17:23:33.812895       1 sync.go:143] Certificate "tls-rancher-ingress" for ingress "rancher" is up to date
I0325 17:23:33.812906       1 controller.go:182] ingress-shim controller: Finished processing work item "cattle-system/rancher"
I0325 17:23:33.812815       1 controller.go:168] ingress-shim controller: syncing item 'cattle-system/cm-acme-http-solver-s7nm7'
I0325 17:23:33.812916       1 sync.go:65] Not syncing ingress cattle-system/cm-acme-http-solver-s7nm7 as it does not contain necessary annotations
I0325 17:23:33.812923       1 controller.go:182] ingress-shim controller: Finished processing work item "cattle-system/cm-acme-http-solver-s7nm7"
I0325 17:23:33.813876       1 controller.go:141] issuers controller: syncing item 'cattle-system/rancher'
I0325 17:23:33.814063       1 setup.go:144] Skipping re-verifying ACME account as cached registration details look sufficient.
I0325 17:23:33.814087       1 controller.go:155] issuers controller: Finished processing work item "cattle-system/rancher"
I0325 17:23:35.438965       1 controller.go:171] certificates controller: syncing item 'cattle-system/tls-rancher-ingress'
I0325 17:23:35.439125       1 sync.go:274] Preparing certificate cattle-system/tls-rancher-ingress with issuer
I0325 17:23:35.439290       1 logger.go:43] Calling GetOrder
I0325 17:23:35.641491       1 logger.go:73] Calling GetAuthorization
I0325 17:23:35.774380       1 logger.go:93] Calling HTTP01ChallengeResponse
I0325 17:23:35.774469       1 prepare.go:279] Cleaning up old/expired challenges for Certificate cattle-system/tls-rancher-ingress
I0325 17:23:35.774532       1 logger.go:68] Calling GetChallenge
I0325 17:23:35.892286       1 http.go:134] wrong status code '404'
```
It then repeats the "Looking up Ingress to wrong status code '404' each time cert-manager tries to issue the cert.

**Comment by rajha-korithrien** [comment] 2019-03-27 17:39
For others who may be having this problem with Rancher and cert-manager, I have fixed my issue and it is due to my HA nginx proxy in front of the cluster ingress. The key was realizing that the ACME well-known URL would fail with an http request to port 80, to the front end server we want to use (the server name we are ultimately getting a certificate for) but would succeed with an https request to port 443 (after dealing with the self signed certificate presented by the ingress controller).

Increasing the debugging to the ingress controllers via a `-v` added to the daemonset (similar instructions can be found [from the kubernetes folks](https://github.com/kubernetes/ingress-nginx/blob/master/docs/troubleshooting.md). Gives an idea of what the ingress is actually seeing from the HA proxy. On a working (https) request we see:
```
"GET /.well-known/acme-challenge/LUntllMMSQlSYA5xqMbgsd8iCF53-VVfX7Lkt_3-Pwo HTTP/1.1
Host: argus.xxx.yyy.zzz
X-Request-ID: 21cb422ed5d10630ca87cbf0d0a40851
X-Real-IP: 1.2.3.4
X-Forwarded-For: 1.2.3.4
X-Forwarded-Host: argus.xxx.yyy.zzz
X-Forwarded-Port: 443
X-Forwarded-Proto: https
X-Original-URI: /.well-known/acme-challenge/LUntllMMSQlSYA5xqMbgsd8iCF53-VVfX7Lkt_3-Pwo
X-Scheme: https
User-Agent: Wget/1.19.5 (darwin17.5.0)
Accept: */*
Accept-Encoding: identity
```
On a failed (http) request we see:
```
"GET /.well-known/acme-challenge/LUntllMMSQlSYA5xqMbgsd8iCF53-VVfX7Lkt_3-Pwo HTTP/1.1
Host: rancher_servers
X-Request-ID: bdf2268f3fad1efda9f3490dbd5a95bf
X-Real-IP: 1.2.3.4
X-Forwarded-For: 1.2.3.4
X-Forwarded-Host: rancher_servers
X-Forwarded-Port: 80
X-Forwarded-Proto: http
X-Original-URI: /.well-known/acme-challenge/LUntllMMSQlSYA5xqMbgsd8iCF53-VVfX7Lkt_3-Pwo
X-Scheme: http
User-Agent: Go-http-client/1.1
Accept-Encoding: gzip
```
Notice that the 'Host:' and 'X-Forwarded-Host:' headers seen by the ingress are not the same between the working and non-working cases. This is caused by using a "stream" definition to send TLS traffic to the ingress while using an "http" definition to proxy regular port 80 traffic. My nginx HA proxy in front of the ingress passes on exactly what came from the client in the "stream" case but changes the headers in the "http" case. The solution is to tell nginx to send appropriate headers. Specifically:
```
   upstream rancher_servers {
        least_conn;
        server 192.168.20.28:80 max_fails=3 fail_timeout=5s;
        server 192.168.20.29:80 max_fails=3 fail_timeout=5s;
        server 192.168.20.30:80 max_fails=3 fail_timeout=5s;
    }

    server {
        listen  80;

        location /.well-known {
                proxy_pass http://rancher_servers;
                proxy_set_header Host argus.xxx.yyy.zzz;
                proxy_set_header X-Forwarded-Host argus.xxx.yyy.zzz;
                allow all;
        }

        location / {
                deny all;
        }
    }
```
Works for me, as it allows lets encrypt to get at things via port 80, and denies everything else, and ensures that the ingress controller see's the host header it expects to correctly route the GET request.
Works for me

**Comment by superseb** [comment] 2019-04-10 13:43
This should be resolved by the current config which does not redirect HTTP -> HTTPS

**Closed by superseb** 2019-04-10 13:43 UTC
Labels: area/certificate, area/ha, kind/question
