### ISSUE TITLE
[external-dns] upgrade gandi-api due to breaking change in zone record api

### ISSUE THREAD

**Issue by jeanlouisboudart** [rancher/rancher#10136] opened 2017-10-17 15:03 UTC
Under certain circumstances, we got some issues while updating dns entries with gandi provider.

**Rancher versions:**
rancher/server: 1.6.9
rancher/agent:

**Infrastructure Stack versions:**
healthcheck:
ipsec:
network-services:
scheduler:
kubernetes (if applicable):
external-dns: 0.7.2

**Docker version: (`docker version`,`docker info` preferred)**
 17.06.2-ce

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
Ubuntu 16.04.3 LTS (4.10.0)

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
GCE

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
single node, internal DB bind mounted

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle

**Steps to Reproduce:**
Spawn a gandi stack from catalog pointing to an existing domain.
Spawn few containers with port mapping to generate A records.

**Results:**
You should quickly some errors while updating records.

**Comment by jeanlouisboudart** [comment] 2017-10-17 15:07
It looks like gandi api introduced a breaking change recently (see changelog http://doc.rpc.gandi.net/changelog/changelog-3.3.36.html)

2017-08-02 BREAKING CHANGE: ZoneRecordReturn id changed from int to string (due to XML-RPC limitations for the integer type being reached)

The underlying library has already integrated the fix (see https://github.com/prasmussen/gandi-api/commit/ea082cd46fbf61e93e96255fa20e470488a937f4), but for the moment you're pointing to an older commit https://github.com/rancher/external-dns/blob/master/vendor.conf#L22

**Comment by deniseschannon** [comment] 2017-10-17 22:28
@jeanlouisboudart I've released `rancher/external-dns:v0.7.6` for this updated change.

Can you make a community catalog PR to update the catalog item and ping me on it? I'll merge it once I see it.

**Comment by jeanlouisboudart** [comment] 2017-10-18 06:11
sure i'll do this now

**Comment by robeastham** [comment] 2017-11-01 13:42
I just installed the GANDI DNS Stack and then tried to install ghost. I ended up with a record in my gandi.net account that looked like this:

ghost.ghost.default

These are the only two stacks I've tried to install on a new test rancher server deployment on Azure.

Also, I just went to check to get the above (ghost.ghost.default) and it appears that some looping error is creating multiple Zone File versions. When I went to bed last night after trying to set up Ghost I had 10 versions now I have 647 versions! Is this something to do with the breaking changes in the api mentioned above.

Or could it be a misconfig on my part? I access the Rancher server single node via IP with external MYSQL, but my understanding is that this should not affect the above - unless I'm missing something?

**Comment by superseb** [comment] 2017-11-01 14:14
What version of the `external-dns` are you running? I just merged the API fix by @jeanlouisboudart

**Comment by jeanlouisboudart** [comment] 2017-11-01 15:15
I saw it creating multiple version to with both version didn't find what were the cause yet.

Gandi's side api breaking change makes no sense, they changed an "id" to a string, but in many places it's still a integer :/

**Comment by superseb** [comment] 2017-11-02 13:23
Ok ping me on Rancher Users Slack if you need help on this (https://slack.rancher.io)

**Comment by loganhz** [comment] 2018-10-05 11:35
Please let us know in a comment if you can still reproduce the issue, and we'll reopen it

**Closed by loganhz** 2018-10-05 11:35 UTC
Labels: area/external-dns

**Comment by dsenouf** [comment] 2018-11-26 16:11
Hello @superseb still seems to be a problem with Gandi API, using external-dns v 0.7.9 with rancher 1.6.21
