### ISSUE TITLE
RKE2/K3S Upgrades from Rancher not working if master nodes are tainted on imported rke2/k3s clusters

### ISSUE THREAD

**Issue by bashofmann** [rancher/rancher#32050] opened 2021-04-12 14:34 UTC
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
* Create a highly available RKE2 cluster, with an older version (e.g. `v1.20.4+rke2r1`) and configure the control-plane/master nodes with `CriticalAddonsOnly=true:NoExecute` taint as documented here https://docs.rke2.io/install/ha/#2a-optional-consider-server-node-taints. This is a best practices to prevent user workloads to run on the control plane nodes.
* Import the RKE2 cluster into Rancher
* Upgrade the RKE2 cluster from the Rancher UI (Edit Cluster, Change version, Save)

**Result:**
The system-upgrade-controller Pod, as well as the Pods of the rke2 master upgrade plan can't be scheduled because they are missing a toleration for the `CriticalAddonsOnly=true:NoExecute` taint.

**Other details that may be helpful:**
* system-upgrade-controller Helm chart: https://github.com/rancher/system-charts/tree/dev-v2.5/charts/rancher-k3s-upgrader
* Plan templates: https://github.com/rancher/rancher/blob/master/pkg/controllers/management/k3sbasedupgrade/template.go

This also affects a K3S cluster, where such a taint has been added, as documented at https://rancher.com/docs/k3s/latest/en/installation/ha/#2-launch-server-nodes

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): 2.5.7
- Installation option (single install/HA): HA

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): Imported RKE2
- Kubernetes version (use `kubectl version`): v1.20.4+rke2r1

SURE-3506

**Comment by estenrye** [comment] 2021-04-22 14:28
After adding the CriticalAddonsOnly toleration to the system-upgrade-controller allowed it to deploy.

Updating the plan for the master nodes to provision with the appropriate toleration allowed the upgrade to continue:

```yaml
apiVersion: upgrade.cattle.io/v1
kind: Plan
metadata:
  creationTimestamp: "2021-04-22T12:26:28Z"
  generation: 2
  labels:
    rancher-managed: "true"
  managedFields:
  - apiVersion: upgrade.cattle.io/v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:labels:
          .: {}
          f:rancher-managed: {}
      f:spec:
        .: {}
        f:concurrency: {}
        f:cordon: {}
        f:drain:
          .: {}
          f:force: {}
        f:nodeSelector:
          .: {}
          f:matchExpressions: {}
        f:serviceAccountName: {}
        f:upgrade:
          .: {}
          f:image: {}
        f:version: {}
    manager: rancher
    operation: Update
    time: "2021-04-22T12:26:28Z"
  - apiVersion: upgrade.cattle.io/v1
    fieldsType: FieldsV1
    fieldsV1:
      f:status:
        .: {}
        f:applying: {}
        f:conditions: {}
        f:latestHash: {}
        f:latestVersion: {}
    manager: system-upgrade-controller
    operation: Update
    time: "2021-04-22T12:26:28Z"
  - apiVersion: upgrade.cattle.io/v1
    fieldsType: FieldsV1
    fieldsV1:
      f:spec:
        f:tolerations: {}
    manager: agent
    operation: Update
    time: "2021-04-22T13:40:08Z"
  name: rke2-master-plan
  namespace: cattle-system
  resourceVersion: "210404"
  selfLink: /apis/upgrade.cattle.io/v1/namespaces/cattle-system/plans/rke2-master-plan
  uid: e433cf96-05e9-486a-90a2-493cf8267951
spec:
  concurrency: 1
  cordon: true
  drain:
    force: true
  nodeSelector:
    matchExpressions:
    - key: node-role.kubernetes.io/master
      operator: In
      values:
      - "true"
  serviceAccountName: system-upgrade
  tolerations:
  - effect: NoExecute
    key: CriticalAddonsOnly
    operator: Equal
    value: "true"
  upgrade:
    image: rancher/rke2-upgrade
  version: v1.20.5+rke2r1
status:
  applying:
  - controlplane01
  conditions:
  - lastUpdateTime: "2021-04-22T13:40:14Z"
    reason: Version
    status: "True"
    type: LatestResolved
  latestHash: 8328420e692ecd89c06ecce046b0f6c089a2f7b6331567e81bfb6f37
  latestVersion: v1.20.5-rke2r1
```

Still working through getting the nodes updated, but that has more to do with how I implemented hostnames and dns than anything else I think:

```
utomation-user@controlplane01:~$ kubectl logs -n cattle-system apply-rke2-worker-plan-on-node03-with-8328420e692ecd89c06-tmdq6
Error from server (NotFound): pods "apply-rke2-worker-plan-on-node03-with-8328420e692ecd89c06-tmdq6" not found
```

**Comment by fredleger** [comment] 2021-05-04 07:01
facing this one too. 

I was kind of a surprised, because some tools already include this toleration which seems to become a standard now (ex: aws-external-controller).

**Comment by fredleger** [comment] 2021-07-08 07:00
activity ;-)



Le mer. 7 juil. 2021 à 20:10, stale[bot] ***@***.***> a
écrit :

**Comment by fredleger** [comment] 2021-07-10 12:44
as far as i know this is still relevant and very painful when you setup a whole k3s cluster

**Comment by bashofmann** [comment] 2021-08-24 15:51
The upgrade job pods can now be scheduled and the upgrade of the control plane node also succeeds, but then the upgrade hangs:

```
NAME              STATUS   ROLES                  AGE     VERSION         INTERNAL-IP    EXTERNAL-IP   OS-IMAGE             KERNEL-VERSION   CONTAINER-RUNTIME
ip-172-31-3-204   Ready    control-plane,master   10m     v1.21.3+k3s1    172.31.3.204   <none>        Ubuntu 18.04.5 LTS   5.4.0-1055-aws   containerd://1.4.8-k3s1
ip-172-31-0-73    Ready    <none>                 9m27s   v1.20.10+k3s1   172.31.0.73    <none>        Ubuntu 18.04.5 LTS   5.4.0-1055-aws   containerd://1.4.9-k3s1
```

The master plan pod is completed, the worker plan pod hangs in the prepare init container:

```
apply-k3s-worker-plan-on-ip-172-31-0-73-with-1f51254078cd-fp5h9   0/1     Init:0/2    0          7m2s
apply-k3s-master-plan-on-ip-172-31-3-204-with-1f51254078c-kggl4   0/1     Completed   0          7m2s
```

Logs from the prepare init container of the worker plan pod:

```
+ /opt/k3s kubectl get plan k3s-master-plan -o 'jsonpath={.metadata.name}' -n cattle-system
+ PLAN=k3s-master-plan
+ '[' -z k3s-master-plan ]
+ /opt/k3s+ jq '.status.applying | length'
 kubectl get plan k3s-master-plan -n cattle-system -o json
+ NUM_NODES=41
+ '[' 41 '==' 0 ]
+ info 'Waiting for all master nodes to be upgraded'
+ echo '[INFO] ' 'Waiting for all master nodes to be upgraded'
+ sleep 5
[INFO]  Waiting for all master nodes to be upgraded
```

The master upgrade plan looks weird:

```
apiVersion: upgrade.cattle.io/v1
kind: Plan
metadata:
  creationTimestamp: "2021-08-24T15:38:34Z"
  generation: 1
  labels:
    rancher-managed: "true"
  name: k3s-master-plan
  namespace: cattle-system
  resourceVersion: "2698"
  uid: 0ba6b81f-4c5b-4d19-829f-ca533d0860c6
spec:
  concurrency: 1
  cordon: true
  nodeSelector:
    matchExpressions:
    - key: node-role.kubernetes.io/master
      operator: In
      values:
      - "true"
  serviceAccountName: system-upgrade-controller
  tolerations:
  - operator: Exists
  upgrade:
    image: rancher/k3s-upgrade
  version: v1.21.3+k3s1
status:
  applying:
  - ip-172-31-3-204
  - ip-172-31-3-204
  - ip-172-31-3-204
  - ip-172-31-3-204
  - ip-172-31-3-204
  - ip-172-31-3-204
  - ip-172-31-3-204
  - ip-172-31-3-204
  - ip-172-31-3-204
  - ip-172-31-3-204
  - ip-172-31-3-204
  - ip-172-31-3-204
  - ip-172-31-3-204
  - ip-172-31-3-204
  - ip-172-31-3-204
  - ip-172-31-3-204
  - ip-172-31-3-204
  - ip-172-31-3-204
  - ip-172-31-3-204
  - ip-172-31-3-204
  - ip-172-31-3-204
  - ip-172-31-3-204
  - ip-172-31-3-204
  - ip-172-31-3-204
  - ip-172-31-3-204
  - ip-172-31-3-204
  - ip-172-31-3-204
  - ip-172-31-3-204
  - ip-172-31-3-204
  - ip-172-31-3-204
  - ip-172-31-3-204
  - ip-172-31-3-204
  - ip-172-31-3-204
  - ip-172-31-3-204
  - ip-172-31-3-204
  - ip-172-31-3-204
  - ip-172-31-3-204
  - ip-172-31-3-204
  - ip-172-31-3-204
  - ip-172-31-3-204
  - ip-172-31-3-204
  conditions:
  - lastUpdateTime: "2021-08-24T15:44:22Z"
    reason: Version
    status: "True"
    type: LatestResolved
  latestHash: 1f51254078cdbd90a187a812118f41cdde0d1e970b98da81642fc803
  latestVersion: v1.21.3-k3s1
```

The system-upgrade-controller logs just has some errors that it could not reach the kubernetes api while the master was being upgraded:

```
W0824 15:38:33.791937       1 client_config.go:543] Neither --kubeconfig nor --master was specified.  Using the inClusterConfig.  This might not work.
time="2021-08-24T15:38:33Z" level=info msg="Applying CRD plans.upgrade.cattle.io"
time="2021-08-24T15:38:33Z" level=info msg="Waiting for CRD plans.upgrade.cattle.io to become available"
time="2021-08-24T15:38:34Z" level=info msg="Done waiting for CRD plans.upgrade.cattle.io to become available"
time="2021-08-24T15:38:35Z" level=info msg="Starting /v1, Kind=Node controller"
time="2021-08-24T15:38:35Z" level=info msg="Starting /v1, Kind=Secret controller"
time="2021-08-24T15:38:35Z" level=info msg="Starting batch/v1, Kind=Job controller"
time="2021-08-24T15:38:35Z" level=info msg="Starting upgrade.cattle.io/v1, Kind=Plan controller"
W0824 15:38:54.065080       1 reflector.go:402] k8s.io/client-go@v1.18.0-k3s.1/tools/cache/reflector.go:125: watch of *v1.Plan ended with: very short watch: k8s.io/client-go@v1.18.0-k3s.1/tools/cache/reflector.go:125: Unexpected watch close - watch lasted less than a second and no items received
W0824 15:38:54.070995       1 reflector.go:402] k8s.io/client-go@v1.18.0-k3s.1/tools/cache/reflector.go:125: watch of *v1.Job ended with: very short watch: k8s.io/client-go@v1.18.0-k3s.1/tools/cache/reflector.go:125: Unexpected watch close - watch lasted less than a second and no items received
W0824 15:38:54.071887       1 reflector.go:402] k8s.io/client-go@v1.18.0-k3s.1/tools/cache/reflector.go:125: watch of *v1.Secret ended with: very short watch: k8s.io/client-go@v1.18.0-k3s.1/tools/cache/reflector.go:125: Unexpected watch close - watch lasted less than a second and no items received
W0824 15:38:54.073950       1 reflector.go:402] k8s.io/client-go@v1.18.0-k3s.1/tools/cache/reflector.go:125: watch of *v1.Node ended with: very short watch: k8s.io/client-go@v1.18.0-k3s.1/tools/cache/reflector.go:125: Unexpected watch close - watch lasted less than a second and no items received
time="2021-08-24T15:38:54Z" level=error msg="error syncing 'cattle-system/k3s-master-plan': handler system-upgrade-controller: Put https://10.43.0.1:443/apis/upgrade.cattle.io/v1/namespaces/cattle-system/plans/k3s-master-plan/status: dial tcp 10.43.0.1:443: connect: connection refused, handler system-upgrade-controller: failed to list batch/v1, Kind=Job for system-upgrade-controller cattle-system/k3s-master-plan: Get https://10.43.0.1:443/apis/batch/v1/jobs?labelSelector=objectset.rio.cattle.io%2Fhash%3D01f3fb8de3b126872b320e36a80e1764c3869cb6: dial tcp 10.43.0.1:443: connect: connection refused, requeuing"
time="2021-08-24T15:38:54Z" level=error msg="error syncing 'cattle-system/k3s-master-plan': handler system-upgrade-controller: Put https://10.43.0.1:443/apis/upgrade.cattle.io/v1/namespaces/cattle-system/plans/k3s-master-plan/status: dial tcp 10.43.0.1:443: connect: connection refused, handler system-upgrade-controller: failed to list batch/v1, Kind=Job for system-upgrade-controller cattle-system/k3s-master-plan: Get https://10.43.0.1:443/apis/batch/v1/jobs?labelSelector=objectset.rio.cattle.io%2Fhash%3D01f3fb8de3b126872b320e36a80e1764c3869cb6: dial tcp 10.43.0.1:443: connect: connection refused, requeuing"
time="2021-08-24T15:38:54Z" level=error msg="error syncing 'cattle-system/k3s-master-plan': handler system-upgrade-controller: Put https://10.43.0.1:443/apis/upgrade.cattle.io/v1/namespaces/cattle-system/plans/k3s-master-plan/status: dial tcp 10.43.0.1:443: connect: connection refused, handler system-upgrade-controller: failed to list batch/v1, Kind=Job for system-upgrade-controller cattle-system/k3s-master-plan: Get https://10.43.0.1:443/apis/batch/v1/jobs?labelSelector=objectset.rio.cattle.io%2Fhash%3D01f3fb8de3b126872b320e36a80e1764c3869cb6: dial tcp 10.43.0.1:443: connect: connection refused, requeuing"
time="2021-08-24T15:38:54Z" level=error msg="error syncing 'cattle-system/k3s-master-plan': handler system-upgrade-controller: Put https://10.43.0.1:443/apis/upgrade.cattle.io/v1/namespaces/cattle-system/plans/k3s-master-plan/status: dial tcp 10.43.0.1:443: connect: connection refused, handler system-upgrade-controller: failed to list batch/v1, Kind=Job for system-upgrade-controller cattle-system/k3s-master-plan: Get https://10.43.0.1:443/apis/batch/v1/jobs?labelSelector=objectset.rio.cattle.io%2Fhash%3D01f3fb8de3b126872b320e36a80e1764c3869cb6: dial tcp 10.43.0.1:443: connect: connection refused, requeuing"
time="2021-08-24T15:38:55Z" level=error msg="error syncing 'cattle-system/k3s-worker-plan': handler system-upgrade-controller: Put https://10.43.0.1:443/apis/upgrade.cattle.io/v1/namespaces/cattle-system/plans/k3s-worker-plan/status: dial tcp 10.43.0.1:443: connect: connection refused, handler system-upgrade-controller: failed to list batch/v1, Kind=Job for system-upgrade-controller cattle-system/k3s-worker-plan: Get https://10.43.0.1:443/apis/batch/v1/jobs?labelSelector=objectset.rio.cattle.io%2Fhash%3D19b07e1cd2912de170265e299047a04e986ccf80: dial tcp 10.43.0.1:443: connect: connection refused, requeuing"
time="2021-08-24T15:38:55Z" level=error msg="error syncing 'cattle-system/k3s-worker-plan': handler system-upgrade-controller: Put https://10.43.0.1:443/apis/upgrade.cattle.io/v1/namespaces/cattle-system/plans/k3s-worker-plan/status: dial tcp 10.43.0.1:443: connect: connection refused, handler system-upgrade-controller: failed to list batch/v1, Kind=Job for system-upgrade-controller cattle-system/k3s-worker-plan: Get https://10.43.0.1:443/apis/batch/v1/jobs?labelSelector=objectset.rio.cattle.io%2Fhash%3D19b07e1cd2912de170265e299047a04e986ccf80: dial tcp 10.43.0.1:443: connect: connection refused, requeuing"
time="2021-08-24T15:38:55Z" level=error msg="error syncing 'cattle-system/k3s-worker-plan': handler system-upgrade-controller: Put https://10.43.0.1:443/apis/upgrade.cattle.io/v1/namespaces/cattle-system/plans/k3s-worker-plan/status: dial tcp 10.43.0.1:443: connect: connection refused, handler system-upgrade-controller: failed to list batch/v1, Kind=Job for system-upgrade-controller cattle-system/k3s-worker-plan: Get https://10.43.0.1:443/apis/batch/v1/jobs?labelSelector=objectset.rio.cattle.io%2Fhash%3D19b07e1cd2912de170265e299047a04e986ccf80: dial tcp 10.43.0.1:443: connect: connection refused, requeuing"
time="2021-08-24T15:38:55Z" level=error msg="error syncing 'cattle-system/k3s-worker-plan': handler system-upgrade-controller: Put https://10.43.0.1:443/apis/upgrade.cattle.io/v1/namespaces/cattle-system/plans/k3s-worker-plan/status: dial tcp 10.43.0.1:443: connect: connection refused, handler system-upgrade-controller: failed to list batch/v1, Kind=Job for system-upgrade-controller cattle-system/k3s-worker-plan: Get https://10.43.0.1:443/apis/batch/v1/jobs?labelSelector=objectset.rio.cattle.io%2Fhash%3D19b07e1cd2912de170265e299047a04e986ccf80: dial tcp 10.43.0.1:443: connect: connection refused, requeuing"
time="2021-08-24T15:38:56Z" level=error msg="error syncing 'cattle-system/k3s-master-plan': handler system-upgrade-controller: Put https://10.43.0.1:443/apis/upgrade.cattle.io/v1/namespaces/cattle-system/plans/k3s-master-plan/status: dial tcp 10.43.0.1:443: connect: connection refused, handler system-upgrade-controller: failed to list batch/v1, Kind=Job for system-upgrade-controller cattle-system/k3s-master-plan: Get https://10.43.0.1:443/apis/batch/v1/jobs?labelSelector=objectset.rio.cattle.io%2Fhash%3D01f3fb8de3b126872b320e36a80e1764c3869cb6: dial tcp 10.43.0.1:443: connect: connection refused, requeuing"
time="2021-08-24T15:38:56Z" level=error msg="error syncing 'cattle-system/k3s-worker-plan': handler system-upgrade-controller: Put https://10.43.0.1:443/apis/upgrade.cattle.io/v1/namespaces/cattle-system/plans/k3s-worker-plan/status: dial tcp 10.43.0.1:443: connect: connection refused, handler system-upgrade-controller: failed to list batch/v1, Kind=Job for system-upgrade-controller cattle-system/k3s-worker-plan: Get https://10.43.0.1:443/apis/batch/v1/jobs?labelSelector=objectset.rio.cattle.io%2Fhash%3D19b07e1cd2912de170265e299047a04e986ccf80: dial tcp 10.43.0.1:443: connect: connection refused, requeuing"
time="2021-08-24T15:38:56Z" level=error msg="error syncing 'cattle-system/k3s-master-plan': handler system-upgrade-controller: Put https://10.43.0.1:443/apis/upgrade.cattle.io/v1/namespaces/cattle-system/plans/k3s-master-plan/status: dial tcp 10.43.0.1:443: connect: connection refused, handler system-upgrade-controller: failed to list batch/v1, Kind=Job for system-upgrade-controller cattle-system/k3s-master-plan: Get https://10.43.0.1:443/apis/batch/v1/jobs?labelSelector=objectset.rio.cattle.io%2Fhash%3D01f3fb8de3b126872b320e36a80e1764c3869cb6: dial tcp 10.43.0.1:443: connect: connection refused, requeuing"
time="2021-08-24T15:38:57Z" level=error msg="error syncing 'cattle-system/k3s-worker-plan': handler system-upgrade-controller: Put https://10.43.0.1:443/apis/upgrade.cattle.io/v1/namespaces/cattle-system/plans/k3s-worker-plan/status: dial tcp 10.43.0.1:443: connect: connection refused, handler system-upgrade-controller: failed to list batch/v1, Kind=Job for system-upgrade-controller cattle-system/k3s-worker-plan: Get https://10.43.0.1:443/apis/batch/v1/jobs?labelSelector=objectset.rio.cattle.io%2Fhash%3D19b07e1cd2912de170265e299047a04e986ccf80: dial tcp 10.43.0.1:443: connect: connection refused, requeuing"
time="2021-08-24T15:38:57Z" level=error msg="error syncing 'cattle-system/k3s-master-plan': handler system-upgrade-controller: Put https://10.43.0.1:443/apis/upgrade.cattle.io/v1/namespaces/cattle-system/plans/k3s-master-plan/status: dial tcp 10.43.0.1:443: connect: connection refused, handler system-upgrade-controller: failed to list batch/v1, Kind=Job for system-upgrade-controller cattle-system/k3s-master-plan: Get https://10.43.0.1:443/apis/batch/v1/jobs?labelSelector=objectset.rio.cattle.io%2Fhash%3D01f3fb8de3b126872b320e36a80e1764c3869cb6: dial tcp 10.43.0.1:443: connect: connection refused, requeuing"
time="2021-08-24T15:38:58Z" level=error msg="error syncing 'cattle-system/k3s-worker-plan': handler system-upgrade-controller: Put https://10.43.0.1:443/apis/upgrade.cattle.io/v1/namespaces/cattle-system/plans/k3s-worker-plan/status: dial tcp 10.43.0.1:443: connect: connection refused, handler system-upgrade-controller: failed to list batch/v1, Kind=Job for system-upgrade-controller cattle-system/k3s-worker-plan: Get https://10.43.0.1:443/apis/batch/v1/jobs?labelSelector=objectset.rio.cattle.io%2Fhash%3D19b07e1cd2912de170265e299047a04e986ccf80: dial tcp 10.43.0.1:443: connect: connection refused, requeuing"
time="2021-08-24T15:38:58Z" level=error msg="error syncing 'cattle-system/k3s-master-plan': handler system-upgrade-controller: Put https://10.43.0.1:443/apis/upgrade.cattle.io/v1/namespaces/cattle-system/plans/k3s-master-plan/status: dial tcp 10.43.0.1:443: connect: connection refused, handler system-upgrade-controller: failed to list batch/v1, Kind=Job for system-upgrade-controller cattle-system/k3s-master-plan: Get https://10.43.0.1:443/apis/batch/v1/jobs?labelSelector=objectset.rio.cattle.io%2Fhash%3D01f3fb8de3b126872b320e36a80e1764c3869cb6: dial tcp 10.43.0.1:443: connect: connection refused, requeuing"
time="2021-08-24T15:38:59Z" level=error msg="error syncing 'cattle-system/k3s-worker-plan': handler system-upgrade-controller: Put https://10.43.0.1:443/apis/upgrade.cattle.io/v1/namespaces/cattle-system/plans/k3s-worker-plan/status: dial tcp 10.43.0.1:443: connect: connection refused, handler system-upgrade-controller: failed to list batch/v1, Kind=Job for system-upgrade-controller cattle-system/k3s-worker-plan: the server is currently unable to handle the request, requeuing"
time="2021-08-24T15:38:59Z" level=error msg="error syncing 'cattle-system/k3s-master-plan': handler system-upgrade-controller: Put https://10.43.0.1:443/apis/upgrade.cattle.io/v1/namespaces/cattle-system/plans/k3s-master-plan/status: dial tcp 10.43.0.1:443: connect: connection refused, handler system-upgrade-controller: failed to list batch/v1, Kind=Job for system-upgrade-controller cattle-system/k3s-master-plan: the server is currently unable to handle the request, requeuing"
time="2021-08-24T15:39:08Z" level=error msg="error syncing 'cattle-system/k3s-master-plan': handler system-upgrade-controller: the server is currently unable to handle the request (put plans.meta.k8s.io k3s-master-plan), requeuing"
I0824 15:39:09.122926       1 trace.go:116] Trace[460128162]: "Reflector ListAndWatch" name:k8s.io/client-go@v1.18.0-k3s.1/tools/cache/reflector.go:125 (started: 2021-08-24 15:38:54.071922978 +0000 UTC m=+20.294459312) (total time: 15.05096193s):
Trace[460128162]: [15.05096193s] [15.05096193s] END
E0824 15:39:09.122950       1 reflector.go:178] k8s.io/client-go@v1.18.0-k3s.1/tools/cache/reflector.go:125: Failed to list *v1.Secret: Get https://10.43.0.1:443/api/v1/namespaces/cattle-system/secrets?resourceVersion=1484: dial tcp 10.43.0.1:443: connect: connection refused
I0824 15:39:09.122991       1 trace.go:116] Trace[683024728]: "Reflector ListAndWatch" name:k8s.io/client-go@v1.18.0-k3s.1/tools/cache/reflector.go:125 (started: 2021-08-24 15:38:54.065139568 +0000 UTC m=+20.287675912) (total time: 15.057833203s):
Trace[683024728]: [15.057833203s] [15.057833203s] END
E0824 15:39:09.123001       1 reflector.go:178] k8s.io/client-go@v1.18.0-k3s.1/tools/cache/reflector.go:125: Failed to list *v1.Plan: Get https://10.43.0.1:443/apis/upgrade.cattle.io/v1/namespaces/cattle-system/plans?resourceVersion=1643: dial tcp 10.43.0.1:443: connect: connection refused
I0824 15:39:09.182918       1 trace.go:116] Trace[1458323237]: "Reflector ListAndWatch" name:k8s.io/client-go@v1.18.0-k3s.1/tools/cache/reflector.go:125 (started: 2021-08-24 15:38:54.073985914 +0000 UTC m=+20.296522248) (total time: 15.10889728s):
Trace[1458323237]: [15.10889728s] [15.10889728s] END
E0824 15:39:09.182944       1 reflector.go:178] k8s.io/client-go@v1.18.0-k3s.1/tools/cache/reflector.go:125: Failed to list *v1.Node: Get https://10.43.0.1:443/api/v1/nodes?resourceVersion=1633: dial tcp 10.43.0.1:443: connect: connection refused
I0824 15:39:09.184050       1 trace.go:116] Trace[436340495]: "Reflector ListAndWatch" name:k8s.io/client-go@v1.18.0-k3s.1/tools/cache/reflector.go:125 (started: 2021-08-24 15:38:54.071038575 +0000 UTC m=+20.293574909) (total time: 15.11298493s):
Trace[436340495]: [15.11298493s] [15.11298493s] END
E0824 15:39:09.184076       1 reflector.go:178] k8s.io/client-go@v1.18.0-k3s.1/tools/cache/reflector.go:125: Failed to list *v1.Job: Get https://10.43.0.1:443/apis/batch/v1/namespaces/cattle-system/jobs?resourceVersion=1535: dial tcp 10.43.0.1:443: connect: connection refused
time="2021-08-24T15:39:09Z" level=error msg="error syncing 'cattle-system/k3s-worker-plan': handler system-upgrade-controller: the server is currently unable to handle the request (put plans.meta.k8s.io k3s-worker-plan), requeuing"
```

The master upgrade job logs are fine:

```
+ upgrade
+ get_k3s_process_info
+ ps -ef
+ grep -E 'k3s .*(server|agent)'
+ grep -E -v '(init|grep|channelserver|supervise-daemon)'
+ awk '{print $1}'
[INFO]  K3S binary is running with pid 4911
[INFO]  Comparing old and new binaries
+ K3S_PID=4911
+ '[' -z 4911 ]
+ info 'K3S binary is running with pid 4911'
+ echo '[INFO] ' 'K3S binary is running with pid 4911'
+ cat /host/proc/4911/cmdline
+ head -n 1
+ awk '{print $1}'
+ K3S_BIN_PATH=/usr/local/bin/k3s
+ '[' 4911 '==' 1 ]
+ '[' -z /usr/local/bin/k3s ]
+ return
+ replace_binary
+ NEW_BINARY=/opt/k3s
+ FULL_BIN_PATH=/host/usr/local/bin/k3s
+ '[' '!' -f /opt/k3s ]
+ info 'Comparing old and new binaries'
+ echo '[INFO] ' 'Comparing old and new binaries'
+ sha256sum /opt/k3s /host/usr/local/bin/k3s
+ wc -l
+ cut '-d ' -f1
+ uniq
+ BIN_COUNT=2
+ '[' 2 '==' 1 ]
+ getfilecon /host/usr/local/bin/k3s
+ awk '{print $2}'
[INFO]  Deploying new k3s binary to /usr/local/bin/k3s
+ K3S_CONTEXT=
+ info 'Deploying new k3s binary to /usr/local/bin/k3s'
+ echo '[INFO] ' 'Deploying new k3s binary to /usr/local/bin/k3s'
+ cp /opt/k3s /host/usr/local/bin/k3s
[INFO]  K3s binary has been replaced successfully
+ '[' -n  ]
+ info 'K3s binary has been replaced successfully'
+ echo '[INFO] ' 'K3s binary has been replaced successfully'
+ return
+ kill_k3s_process
+ kill -SIGTERM 4911
+ info 'Successfully Killed old k3s process 4911'
+ echo '[INFO] ' 'Successfully Killed old k3s process 4911'
[INFO]  Successfully Killed old k3s process 4911
```

Node labels:

```
kubectl get nodes --show-labels
NAME              STATUS   ROLES                  AGE   VERSION         LABELS
ip-172-31-3-204   Ready    control-plane,master   16m   v1.21.3+k3s1    beta.kubernetes.io/arch=amd64,beta.kubernetes.io/instance-type=k3s,beta.kubernetes.io/os=linux,k3s.io/hostname=ip-172-31-3-204,k3s.io/internal-ip=172.31.3.204,kubernetes.io/arch=amd64,kubernetes.io/hostname=ip-172-31-3-204,kubernetes.io/os=linux,node-role.kubernetes.io/control-plane=true,node-role.kubernetes.io/master=true,node.kubernetes.io/instance-type=k3s,plan.upgrade.cattle.io/k3s-master-plan=1f51254078cdbd90a187a812118f41cdde0d1e970b98da81642fc803
ip-172-31-0-73    Ready    <none>                 15m   v1.20.10+k3s1   beta.kubernetes.io/arch=amd64,beta.kubernetes.io/instance-type=k3s,beta.kubernetes.io/os=linux,k3s.io/hostname=ip-172-31-0-73,k3s.io/internal-ip=172.31.0.73,kubernetes.io/arch=amd64,kubernetes.io/hostname=ip-172-31-0-73,kubernetes.io/os=linux,node.kubernetes.io/instance-type=k3s
```

**Comment by kinarashah** [comment] 2021-08-24 19:21
Seems like this is happening even without adding taints on a normal upgrade, but doesn't happen on Rancher v2.5.9. Some other changes might be causing this, I am looking into it.

**Comment by kinarashah** [comment] 2021-08-24 23:33
Update: My initial theory was wrong - it isn't other changes in Rancher. @dweomer helped and looked at the setup, the issue is the multiple duplicate entries in `status: applying:` and the fix would need to be in SUC itself.

**Comment by kinarashah** [comment] 2021-08-25 03:34
Available to test with the latest chart on `v2.6-head`, please confirm that `system-upgrade-controller` is at `v0.7.5`.

**Comment by bashofmann** [comment] 2021-08-25 13:50
Works for me now. The upgrade runs through successfully.

**Comment by dweomer** [comment] 2021-09-29 15:07
@deniseschannon this should be addressed by SUC [v0.8.0-rc.1](https://github.com/rancher/system-upgrade-controller/releases/tag/v0.8.0-rc.1) which needs to be bumped for the system management reference as per https://github.com/rancher/rancher/issues/34964

**Comment by kinarashah** [comment] 2021-11-19 03:55
@thedadams has updated SUC to `v0.8.0`, moving this issue to test: 

feature-charts: https://github.com/rancher/charts/pull/1565 
k3s-upgrader: https://github.com/rancher/system-charts/pull/540

**Comment by deniseschannon** [comment] 2021-11-19 05:51
@kinarashah @thedadams Did we update the line within Rancher that selects which chart to deploy? It's somewhere in the rancher code base that was missed last time....I just don't remember where it is.

**Comment by deniseschannon** [comment] 2021-11-19 05:54
@ibuildthecloud helped me find it, but it doesn't look like the version matches? https://github.com/rancher/rancher/blob/28175e61119e13e8f8338280a720dd900c130d1f/pkg/controllers/provisioningv2/rke2/managesystemagent/managesystemagentplan.go#L28

**Comment by thedadams** [comment] 2021-11-19 06:28
100.0.1 is the latest version. The metadata on the semver (the part after the +) is ignored when helm looks for the version.

Version 100.0.1+up0.3.1 uses version 0.8.0 of system-upgrade-controller.

**Comment by thedadams** [comment] 2021-11-19 06:30
@deniseschannon https://github.com/rancher/charts/blob/dev-v2.6/charts/system-upgrade-controller/system-upgrade-controller/100.0.1+up0.3.1/values.yaml

**Closed as completed** 2021-12-01 19:01 UTC
Labels: dependency-rke2
