### ISSUE TITLE
Remove redundant "Azure Unmanaged Disk" option from Storage Class dialog

### ISSUE THREAD

**Issue by jgreat** [rancher/rancher#19744] opened 2019-04-22 01:14 UTC
Remove the "Azure Unmanaged Disk" radio button from the storage class options.

The "Azure Unmanaged Disk" style of input was for kubernetes version prior to 1.7.2. 
https://kubernetes.io/docs/concepts/storage/storage-classes/#azure-disk

Selecting this option and then trying to change it to the new style after the fact breaks the storage class for the cluster. The controller-manager will try and select the wrong storage-account.

The "kind: shared" and "kind: dedicated" parameters are for "unmanaged disk" and "kind: managed" is for managed disk

![image](https://user-images.githubusercontent.com/5324639/56478026-6d56d500-6471-11e9-8614-21facff109fa.png)

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v2.2.2` UI: `v2.2.41` |
|Route|`authenticated.cluster.monitoring.index`|

**Comment by davidnuzik** [comment] 2019-04-30 21:54
@westlywright @jgreat I see that we have removed the redundant radio buttons. However, I also see that Location and Storage Account fields are now missing as well (I don't seem them in the schema) is this expected? For each kind there is only an option to supply the "Storage Account Type" unlike the screenshot in the issue description.

![image](https://user-images.githubusercontent.com/45179589/56995885-de744780-6b57-11e9-9b82-7fced204c8d3.png)

**Comment by davidnuzik** [comment] 2019-05-08 21:25
Version: Master (v2.3) (5/8/19)

I can confirm removal of this radio button option. Now instead we have a drop down that let's you select the Kind you would like to specify (as pictured below).

I validated that the UI is working correctly and successfully provisioned a managed disk. Please note that due to a bug I was not able to validate unmanaged at this time, but this appears to be working correctly from the UI-perspective (UI, API, HTTP). As such I will be closing this issue.

For details around the issue where we cannot create a PVC for a storage class with Azure Disk provisioner, see #19216

**Closed by davidnuzik** 2019-05-08 21:25 UTC
Labels: [zube]: To Test, area/storage, area/ui, kind/bug, status/to-test, status/triaged, team/az
