### ISSUE TITLE
Condtional logic and other niceties for rancher-compose.yml

### ISSUE THREAD

**Issue by nrvale0** [rancher/rancher#6502] opened 2016-11-03 19:11 UTC
This is a feature request relayed from customer discussion at NYC Container Days...

Customer would like some sort of conditional logic support in rancher-compose.yml such that options can be enabled/disabled/hidden/exposed based on user input to other options.

Ex: "If I uncheck the box for 'Encrypt' I would like the drop-down for TSL certificate to be grayed-put/hiddden.

**Comment by joshwget** [comment] 2017-02-11 00:47
@nrvale0 Can I close? I think this is a duplicate of #3239.

**Closed** 2017-02-11 05:47 UTC
Labels: kind/feature

**Comment by nrvale0** [comment] 2017-02-13 04:59
@joshwget Indeed, it appears to be nearly 1:1. Feel free to close. Thx for asking.
