### ISSUE TITLE
kubernetes-ingress-lbs containers are not tied up to any specific plane (orchestration/compute).

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#8013] opened 2017-03-01 19:10 UTC
Rancher Versions: Build from master

Currently , kubernetes-ingress-lbs containers are not tied up to any specific plane. In "required" plane isolation mode , they will end up landing in hosts that are part of etcd plane , which is not desirable.

We should have the kubernetes-ingress-lbs to be part of orchestration/compute plane.

**Comment by LLParse** [comment] 2017-03-01 19:13
Duplicate of https://github.com/rancher/rancher/issues/8013

**Comment by cloudnautique** [comment] 2017-03-02 04:29
I would say they have an anti-affinity for nopod=true, but leave it to the user to set other scheduling labels. 
The power here is that the user can now control where they land, and setup DNS or external load balancing targets. This more closely mimics the behavior seen in cattle that is leveraged my most customers.

**Comment by LLParse** [comment] 2017-03-02 17:40
@cloudnautique Just for reference, we did away with nopods=true. The new flow is the containers have hard affinity to their respective planes via `etcd=true` `orchestration=true` and `compute=true` labels. With this, user can achieve any sort of overlap they desire, to "break the rules" in the name of restoring resiliency without paying for standby hosts.

**Comment by deniseschannon** [comment] 2017-03-02 22:39
Spoke with @alena1108 about making the ingress controller hae a configuration option to request to not schedule on the planes.

**Comment by deniseschannon** [comment] 2017-04-06 21:44
Closing in favor of #7909

**Closed by deniseschannon** 2017-04-06 21:44 UTC
Labels: area/kubernetes, kind/bug
