### ISSUE TITLE
healthcheck containers recreated

### ISSUE THREAD

**Issue by qixinyun** [rancher/rancher#8267] opened 2017-03-22 12:35 UTC
**Rancher Versions:**
Server: 1.5.1 (upgrade from 1.1.4 to 1.5.1)
healthcheck:0.2.3
ipsec:
network-services:0.5.3
scheduler:0.7.5
kubernetes (if applicable):

**Docker Version:**

[ansible@sandbox-service-2 ~]$ docker info
Containers: 53
 Running: 41
 Paused: 0
 Stopped: 12
Images: 100
Server Version: 1.10.3
Storage Driver: devicemapper
 Pool Name: docker-thinpool
 Pool Blocksize: 524.3 kB
 Base Device Size: 10.74 GB
 Backing Filesystem: xfs
 Data file:
 Metadata file:
 Data Space Used: 12.59 GB
 Data Space Total: 102 GB
 Data Space Available: 89.42 GB
 Metadata Space Used: 9.019 MB
 Metadata Space Total: 1.07 GB
 Metadata Space Available: 1.061 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: true
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Library Version: 1.02.107-RHEL7 (2016-06-09)
Execution Driver: native-0.2
Logging Driver: json-file
Plugins:
 Volume: local
 Network: host bridge null
Kernel Version: 3.10.0-327.36.1.el7.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
Number of Docker Hooks: 2
CPUs: 2
Total Memory: 7.64 GiB
Name: sandbox-service-2
ID: 7XYA:7M4M:D25V:4JXS:CA6J:SWVW:NQX7:FONX:VV3W:YOIB:VPWR:GZIP
WARNING: bridge-nf-call-iptables is disabled
WARNING: bridge-nf-call-ip6tables is disabled
Registries: docker.io (secure)

**OS and where are the hosts located? (cloud, bare metal, etc):**
Centos 7.2 Aliyun,
CentOS Linux release 7.2.1511 (Core)
kernel 3.10.0-327.36.1.el7.x86_64
**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
HA rancher external DB, 4 Hosts
**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle
**Steps to Reproduce:**
healthcheck containers recreated at about every 10 mins.
It seems the container is lost (killed), not stopped. So it will be recreate all the time.

lost one -> recreate -> lost another -> recreate.....
**Results:** 
sometime the containers can not ping other containers with different hosts.

![snip20170322_4](https://cloud.githubusercontent.com/assets/22721576/24197645/5c8e3258-0f3d-11e7-8276-97a541ccbd47.png)

**Comment by opsforge** [comment] 2017-03-22 14:09
I think you are seeing the exact same thing I did (and your setup is similar too):
https://github.com/rancher/rancher/issues/8234

**Comment by superseb** [comment] 2017-11-16 23:05
Closing as duplicate of https://github.com/rancher/rancher/issues/8234

**Closed by superseb** 2017-11-16 23:05 UTC
Labels: area/balancer, kind/question
