### ISSUE TITLE
[BUG]  failed to create mutating configuration

### ISSUE THREAD

**Issue by ghost** [rancher/rancher#42611] opened 2023-08-31 18:52 UTC
**Rancher Server Setup**
- Rancher version: 2.7.5

**Information about the Cluster**
- Kubernetes version: v1.28.1

**Describe the bug**
level=error msg="error syncing 'cattle-system/cattle-webhook-ca': handler secrets: failed to create mutating configuration: MutatingWebhookConfiguration.admissionregistration.k8s.io \"\" is invalid: metadata.name: Required value: name or generateName is required, requeuing"

**To Reproduce**
Follow these steps: https://ranchermanager.docs.rancher.com/v2.7/troubleshooting/other-troubleshooting-tips/expired-webhook-certificate-rotation

Then the rancher-webhook pod in cattle-system won't come back online with the error described above

**Comment by tomleb** [comment] 2023-09-05 18:33
Thanks for opening an issue. Closing as duplicate of https://github.com/rancher/webhook/issues/286.

**Comment by KevinJoiner** [comment] 2023-09-05 19:25
@brisp-jelle 
To manually recover from this state, you can recreate an empty configuration and restart the rancher-webhook pod
``` yaml
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: rancher.cattle.io
  ```
  `kubectl delete pod -n cattle-system -l app=rancher-webhook`

**Comment by jdoc-sag** [comment] 2024-02-16 15:07
This was helpful @KevinJoiner. Thanks.
For fellow newbies, I used `kubectl apply -f config.yaml` where config.yaml contained the empty config above.
Joel, with Rancher 2.8.2

**Comment by mike12806** [comment] 2024-05-12 23:59
This is happening to me on 2.8.2

**Comment by h0jeZvgoxFepBQ2C** [comment] 2024-06-26 11:48
Happening to me after updating from 2.8.3 to 2.8.5.  @KevinJoiner 's solution worked for me so far

**Comment by tomleb** [comment] 2024-07-16 18:43
Migrating https://github.com/rancher/webhook/issues/286 here since we manage all our issues in rancher/rancher. Re-opening.

# Summary

While working on https://github.com/rancher/rancher/issues/41789 I wanted to test that the webhook was still working correctly after some dependency changes. I deleted both mutating and validating webhook configuration. I expected webhook to recreate both but it only created the validating one. Here's what I see in the logs:

```
time="2023-09-01T20:08:33Z" level=error msg="error syncing 'cattle-system/cattle-webhook-ca': handler secrets: failed to create mutating configuration: MutatingWebhookConfiguration.admissionregistration.k8s.io \"\" is invalid: metadata.name: Required value: name or generateName is required, requeuing"
```

This patch fixes the issue for me but would need to add some tests (integration/unit).

```diff
diff --git a/pkg/server/server.go b/pkg/server/server.go
index 1c3f7418332f..1645ddcfe54f 100644
--- a/pkg/server/server.go
+++ b/pkg/server/server.go
@@ -275,9 +275,9 @@ func (s *secretHandler) ensureWebhookConfiguration(validatingConfig *v1.Validati
 		}
 	}
 
-	currMutation, err := s.mutatingController.Get(validatingConfig.Name, metav1.GetOptions{})
+	currMutation, err := s.mutatingController.Get(mutatingConfig.Name, metav1.GetOptions{})
 	if apierrors.IsNotFound(err) {
-		_, err = s.mutatingController.Create(currMutation)
+		_, err = s.mutatingController.Create(mutatingConfig)
 		if err != nil {
 			return fmt.Errorf("failed to create mutating configuration: %w", err)
 		}
```

# Reproducing

Delete both webhook configurations

```
kubectl delete mutatingwebhookconfiguration rancher.cattle.io
kubectl delete validatingwebhookconfiguration rancher.cattle.io 
```

Wait a little bit so that webhook tries to recreate them.

You'll see that the validating exists but not the mutating.

Note that the this can also be reproduced by following the official instructions for rotating expired webhook certificates: https://ranchermanager.docs.rancher.com/v2.7/troubleshooting/other-troubleshooting-tips/expired-webhook-certificate-rotation

**Comment by Priyashetty17** [comment] 2024-08-06 05:54
@pmatseykanets Moved it to Reopened as we need a webhook RC to validate this issue. Could you also please add a QA/validation template for the issue?

**Comment by pmatseykanets** [comment] 2024-08-06 11:29
## Validation Template

## What was fixed, or what change has occurred

A bug was fixed that was preventing a MutatingWebhookConfiguration from being recreated.

## Areas or cases that should be tested

- Delete the ValidatingWebhookConfiguration
- Delete the MutatingWebhookConfiguration
- Restart the webhook
- Make sure both ValidatingWebhookConfiguration and MutatingWebhookConfiguration were created

## What areas could experience regressions

N/A

## Are the repro steps accurate/minimal?

N/A.

**Comment by Priyashetty17** [comment] 2024-08-09 16:50
Validated all scenarios identified in the test plan with **v2.9-416e5c404537f6c953dac9a537fa99d15221589a-head** and **rancher/rancher-webhook:v0.5.1-rc.1**

- Verify Mutating Webhook Configuration gets recreated - local cluster
- Verify Validating Webhook Configuration gets recreated - local cluster
- Verify Mutating and Validating Webhook Configurations gets recreated - local cluster
- Verify Mutating Webhook Configuration gets recreated - downstream cluster
- Verify Validating Webhook Configuration gets recreated - downstream cluster
- Verify Mutating and Validating Webhook Configurations gets recreated - downstream cluster
- Verify Mutating and Validating Webhook Configurations gets recreated when CA secret is modified - local cluster
- Verify Mutating and Validating Webhook Configurations gets recreated when CA secret is modified - downstream cluster
- Upgrade from v2.9.0 to v2.9-head. Verify Mutating and Validating Webhook Configurations gets recreated
- Upgrade from v2.9.0 (with workaround applied) to v2.9-head. Verify Mutating and Validating Webhook Configurations gets recreated

**Note**: The webhook was manually updated to **rancher/rancher-webhook:v0.5.1-rc.1** for testing purposes, as https://github.com/rancher/rancher/pull/46599 has not been merged yet.

**Closed by Priyashetty17** 2024-08-09 16:50 UTC
Labels: kind/bug, priority/2, QA/M, kind/good-first-issue, team/frameworks
