### ISSUE TITLE
Cannot create cluster/project role in master

### ISSUE THREAD

**Issue by loganhz** [rancher/rancher#18052] opened 2019-02-13 08:21 UTC
rancher/rancher:master 02/12

Steps

1. Go to role page
2. Add a cluster role

Results:

Server always returns error

![image](https://user-images.githubusercontent.com/21168270/52696964-57c5ba80-2fab-11e9-9755-2510457aa935.png)

**Comment by cjellick** [comment] 2019-02-13 22:30
@mrajashree this is caused by the validation you added for roleTemplate
```
--- a/pkg/api/customization/roletemplate/roletemplate.go
+++ b/pkg/api/customization/roletemplate/roletemplate.go
@@ -1,10 +1,13 @@
 package roletemplate
 
 import (
+	"fmt"
 	"net/http"
 
 	"github.com/rancher/norman/types"
+	"github.com/rancher/norman/types/convert"
 	"github.com/rancher/types/apis/management.cattle.io/v3"
+	"github.com/rancher/types/client/management/v3"
 )
 
 type Wrapper struct {
@@ -12,10 +15,20 @@ type Wrapper struct {
 }
 
 func (w Wrapper) Validator(request *types.APIContext, schema *types.Schema, data map[string]interface{}) error {
-	if request.Method != http.MethodPut {
+	if request.Method != http.MethodPut && request.Method != http.MethodPost {
 		return nil
 	}
 ...
 	rt, err := w.RoleTemplateLister.Get("", request.ID)
 	if err != nil {
```

On POST, request.ID is empty, so `rt, err := w.RoleTemplateLister.Get("", request.ID)` throws an error 

If you have time, can you add a test to test creating roleTeampltes? Could cover the basic create works use case, the validation error you get based on your changes, and the previous validation error you would get if you tried to update a builtin role.

I realize you have a lot to do before code completely, so i dont mind if the tests are a follow up post code freeze

**Comment by mrajashree** [comment] 2019-02-13 22:37
@cjellick Thanks for the pointer! Okay, will try to get whatever tests I can, if not then post code freeze

**Comment by mrajashree** [comment] 2019-02-13 23:29
@loganhz fix is in master now

**Comment by loganhz** [comment] 2019-02-13 23:30
Thanks!

**Comment by sangeethah** [comment] 2019-02-14 04:55
Tested with latest build from master - Feb 13
Able to create cluster/project role successfully.

**Closed by sangeethah** 2019-02-14 04:55 UTC
Labels: kind/bug-qa, status/ready-for-review, status/resolved, status/to-test, status/working, team/ca, version/2.0
