### ISSUE TITLE
Installed Apps don't update after upgrade from v2.6.3 to v2.6.8 when Rancher chart uses --set useBundledSystemChart=true

### ISSUE THREAD

**Issue by MKlimuszka** [rancher/rancher#39532] opened 2022-11-08 19:42 UTC
Issue description:
Installed Apps, e.g. fleet and rancher-webhook, don't update after upgrade from v2.6.3 to v2.6.8 when Rancher chart uses --set useBundledSystemChart=true. As a result, fleet is left on chart version 100.0.2+up0.3.8 versus 100.0.5+up0.3.11 and rancher-webhook is left on chart version 1.0.2+up0.2.2 versus 1.0.5+up0.2.6.

Business impact:
Older components (fleet and rancher-webhook) running without new patch releases.

Troubleshooting steps:
N/A

Repro steps:

    Create 3 all-role node RKE cluster (I used RKE v1.2.22 / Kubernetes v1.20.15-rancher2-1).
    Install Rancher v2.6.3 with ingress.tls.source=rancher and  useBundledSystemChart=true
    Observe fleet chart version 100.0.2+up0.3.8 and rancher-webhook chart version 1.0.2+up0.2.2 in Installed Apps in Rancher local cluster
    Upgrade Rancher via helm to v2.6.8 (still with useBundledSystemChart=true) and observe fleet chart version remains at 100.0.2+up0.3.8 and rancher-webhook chart version remains at 1.0.2+up0.2.2 in Installed Apps in Rancher local cluster.
    In a separate matching lab environment repeat this process but without  useBundledSystemChart=true on the Rancher helm chart at installation and upgrade.
    Observe fleet is upgraded to chart version 100.0.5+up0.3.11 and rancher-webhook is upgraded to chart version 1.0.5+up0.2.6 after the Rancher v2.6.8 upgrade.
    In a separate matching lab environment install v2.6.8 directly with useBundledSystemChart=true and observe fleet runs chart version 100.0.5+up0.3.11 and rancher-webhook runs chart version 1.0.5+up0.2.6

Workaround:
Is workaround available and implemented? No
What is the workaround: N/A

Actual behavior:
Installed component charts not upgraded after Rancher upgrade where useBundledSystemChart=true is set

Expected behavior:
Installed component charts upgraded after Rancher upgrade, even where useBundledSystemChart=true

SURE-5190

**Comment by MKlimuszka** [comment] 2022-11-08 19:44
This is very similar to https://github.com/rancher/rancher/issues/36914

**Comment by ronhorton** [comment] 2022-12-01 16:12
**Could not reproduce - when upgrading to v2.6.8, fleet and webhook versions updated correctly**
1. created an `airgap rancher with rancher v2.6.3`
2. verified fleet chart version `100.0.2+up0.3.8` and rancher-webhook chart version `1.0.2+up0.2.2`
3. upgraded airgap to rancher v2.6.8 with `--set useBundledSystemChart=true`
4. verified fleet and rancher webhook versions had `updated as expected` 

- fleet:100.0.5+up0.3.11 
- rancher-webhook:1.0.5+up0.2.6

<img width="1631" alt="2022-11-30_17-20-11" src="https://user-images.githubusercontent.com/89212856/205102861-760dbbb0-9d79-4d89-9484-bb7025993787.png">

**Comment by prachidamle** [comment] 2022-12-01 17:11
@PennyScissors could you please check if the repro steps are fine and if there is anything else that can help reproduce this issue?

**Comment by PennyScissors** [comment] 2022-12-01 21:42
@prachidamle The steps look right to me. I guess one thing we could check is the commit hash. After the upgrade verify the commit hash of the rancher-charts ClusterRepo resource was updated, and the new commit hash is not the same as latest (lastest is whatever last commit the rancher/charts repo has when you test, it should be an older commit from when we released v2.6.8 but I can't say which commit for sure). @ronhorton let me know if you need help, I can shadow you or something

**Comment by AndrewHoffmanQA** [comment] 2023-01-11 16:19
QA has completed its investigation of this issue. moving to 'done' column.

**Comment by MKlimuszka** [comment] 2023-01-31 23:24
- Reopening as we may have a path to reproduction.

**Comment by eliyamlevy** [comment] 2023-02-17 15:49
Reproduced on HA cluster with k8s version `v1.20.15-rancher1-3`.  Installed rancher `2.6.3` with `useBundledSystemChart=true` and `ingress.tls.source=rancher`, then upgraded to rancher `2.6.8` with the same settings. 

Observed that the system charts did not upgrade, specifically looked at fleet and rancher-webhook and confirmed what was reported in the issue.

To note, tried reproducing without `ingress.tls.source=rancher` in the helm install and the charts did upgrade.

**Comment by kkaempf** [comment] 2023-03-06 14:29
Adding @mattfarina - might be related to the out-of-band Fleet update to 0.4.0 ?! 🤔

**Comment by kkaempf** [comment] 2023-04-12 08:28
dropping from Fleet backlog since the team is fully booked

**Comment by kkaempf** [comment] 2023-08-18 08:28
closing as done

**Comment by l4zy0n3** [comment] 2023-09-22 15:05
This requires a released 2.8 helm chart to test, only the 2.8-head image is available for now, tests would yield unreliable results without the chart

**Comment by l4zy0n3** [comment] 2023-09-27 11:28
Verified on Upgrade from 2.7.7-rc4 -> 2.8.0-alpha1 airgapped
following apps got upgraded after rancher upgrade is complete
rancher-webhook
2.0.6+up0.3.6-rc4 -> 103.0.0+up0.4.0-rc7
fleet
102.2.0+up0.8.0-rc.9 -> 103.1.0+up0.9.0-rc.1

**Comment by rohitsakala** [comment] 2023-10-13 16:54
@l4zy0n3 Can you re test  this bug. Since the previous fix lead to another bug. and now we have a new fix which should fix it by these PRs 

https://github.com/rancher/rancher/pull/43137
https://github.com/rancher/rancher/pull/43136

**Comment by martyav** [comment] 2023-10-25 15:57
Is this ONLY webhook and fleet, or were those the only two installed apps tested? Asking because release notes have distinct sections for the webhook, fleet, and apps.

**Comment by l4zy0n3** [comment] 2023-10-27 13:31
Verified on Upgrade from 2.7.7-rc7 -> 2.8.0-rc2
image:v2.8-head
The following apps got upgraded after rancher upgrade was complete
rancher-webhook
2.0.6+up0.3.6 -> 103.0.0+up0.4.0-rc10
fleet
102.2.0+up0.8.0 -> 103.1.0+up0.9.0-rc.4

Additional Test Scenarios (Thanks @rohitsakala)

Non-AirGap

- Non-HA 

- [x] Upgrade from 2.7 to 2.8. - check if the right versions of the Charts are shown.
- [x] OOB Release Updates - check if the right versions of the Charts are shown.
- [x] Changing branches without upgrade - check if the right versions of the Charts are shown.

- HA

- [x] Upgrade from 2.7 to 2.8 - check if the right versions of the Charts are shown.
- [x] OOB Release Updates - check if the right versions of the Charts are shown.
- [x] Changing branches without upgrade - check if the right versions of the Charts are shown.

AirGap

- Non HA

- [x] Upgrade from 2.7 to 2.8 - check if the right versions of the Charts are shown.

- HA

- [x] Upgrade from 2.7 to 2.8 - check if the right versions of the Charts are shown.

**Closed** 2023-10-27 13:33 UTC
Labels: priority/1, internal, area/webhooks, [zube]: To Test, area/fleet, release-note, area/upgrade, JIRA, team/mapps, status/release-note-added
