### ISSUE TITLE
Make docker version -18.06 default for "Docker Install URL" when creating node templates.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#17184] opened 2018-12-19 18:53 UTC
Rancher server version - Build from master

Make docker version -18.06 default for "Docker Install URL" when creating node templates.

Currently it is set to 17.03.

**Comment by cjellick** [comment] 2019-01-23 20:55
dupe of https://github.com/rancher/rancher/issues/15824

**Closed by cjellick** 2019-01-23 20:55 UTC
Labels: kind/bug-qa, priority/0, team/ca, version/2.0
