### ISSUE TITLE
Sometimes worker nodes are Unavailable for long time on scaling up

### ISSUE THREAD

**Issue by sowmyav27** [rancher/rancher#22669] opened 2019-09-05 22:57 UTC
**What kind of request is this (question/bug/enhancement/feature request):** bug

**Steps to reproduce (least amount of steps as possible):**
1. Have an rke cluster- AWS - 1 etcd, 1 control plane and 1 worker node. in v2.2.8
2. Upgrade to rancher master latest - `4c7e3263a` - commit id. 
3. Scale up the number of worker nodes

**Expected Result:**
The scaled up worker node should come to Active state.

**Actual Result:**
It is taking really long for the worker node to come up `Active`. 
Error seen:
<img width="1483" alt="Screen Shot 2019-09-05 at 3 36 33 PM" src="https://user-images.githubusercontent.com/26032343/64389007-caed5780-cff5-11e9-90e7-8c82a0559a64.png">

**Note:**
Even after 10 minutes, it failed to come up.
Scaled up worker node by 1 more. Then both the scaled up nodes came up Active quickly.

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): 2.2.8 to rancher-master
- Installation option (single install/HA): single

**Comment by alena1108** [comment] 2019-09-07 00:20
@sangeethah @sowmyav27 can we fetch these details once you see the issue happening again:

* kubectl get nodes // see if the node appears in the output
* See if the node agent gets deployed successfully on the host. If it does, get the logs from the node agent container.

**Comment by janeczku** [comment] 2019-09-09 16:41
Same issue was observed on Rancher HA installations when provisioning new clusters or scaling up node pools. As visible in the screenshot below, the nodes have a status `ready` in downstream K8s API but not in Rancher API.

- Rancher v2.2.8
- Management Cluster: K8s v1.14.6
- User Cluster: K8s v1.14.6
- RancherOS v1.5.3
- Docker 18.9.2

<img width="1425" alt="Screenshot 2019-09-09 at 18 37 28" src="https://user-images.githubusercontent.com/3813921/64549491-1a52c100-d331-11e9-80ee-746a9c7bc697.png">

**Comment by daxmc99** [comment] 2019-09-09 22:04
This appears to be a node syncer issue. I was able to workaround this issue by triggering an update of the v3.Node in some other way (ie adding a description).

**Comment by daxmc99** [comment] 2019-09-16 16:34
@ibuildthecloud 's PR here https://github.com/rancher/rancher/pull/22866

**Comment by daxmc99** [comment] 2019-09-17 01:20
For testing:
This issue can be tested by observing the revision numbers of the v3.Node objects on provisioning via `kubeclt get nodes.management.cattle.io -n <cluster-namespace> -o yaml | grep "revision"`
These values before these fixes should be high (over 300 for the worker before this fix). After this fix they should be under 100 after provisioning. 

For posterity: The root cause of this issue was high contention on `nodesyncer.go` which was resolved by fixing a loop bug between syncLabels and labels.go

**Comment by sowmyav27** [comment] 2019-09-17 19:06
verified on `rancher:v2.3.0-rc4`

Steps:

- Deploy and rke DO cluster with 3 nodes - 1 etcd, 1 control plane and 1 worker node.
- The worker node is initially in `Unavailable` state - with the Runtime error on the UI.
- But it comes to `Active` quickly, less than a minute.
- Verified by scaling up the worker nodes also.
- The nodes come up to `Active` state quickly. They do not take much time like mentioned in the issue - https://github.com/rancher/rancher/issues/22669#issue-490048097

Also the generation numbers on `rancher:v2.3.0-rc4` with the fix is : (on a cluster with 3 nodes, scale up the number of worker nodes, and observe the generation numbers)
```
kubectl get nodes.management.cattle.io -n c-2bpwx -o yaml | grep "generation"
    generation: 33
    generation: 25
    generation: 25
    generation: 33
    generation: 33
```

In `rancher:v2.3.0-rc3` without the fix: (on a cluster with 3 nodes, scale up the number of worker nodes, and observe the generation numbers)
```
kubectl get nodes.management.cattle.io -n c-gmckf -o yaml | grep "generation"
    generation: 10
    generation: 606
    generation: 4
    generation: 89
    generation: 2
    generation: 319
```

**Closed** 2019-09-17 19:15 UTC
Labels: [zube]: To Test, kind/bug-qa, team/az
