### ISSUE TITLE
Unable to update chart in Git custom catalog : chart already exists

### ISSUE THREAD

**Issue by Dremor** [rancher/rancher#14183] opened 2018-06-23 17:10 UTC
I'm working on an updated nfs-provisioner chart, but I'm unable to update as Rancher say that there is already a chart with the same name.

Git repository : https://lab.dremor.info/rancher2/charts.git
Branch: develop

I tried:
- Put the updated version in its own folder: [e1db4477](https://lab.dremor.info/rancher2/charts/commit/e1db44774822b023451d992573d2bcddb38de553)
- Delete the old version: [ac41e0ba](https://lab.dremor.info/rancher2/charts/commit/ac41e0ba8abbdc52a81938962c3ddb0c98e3e6b0)

Logs:
```bash
2018/06/23 16:59:14 [INFO] traversing files and generating templates
2018/06/23 16:59:15 [INFO] Updating catalog dremor-library-unstable
2018/06/23 16:59:15 [INFO] Creating template dremor-library-unstable-nfs-provisioner
2018/06/23 16:59:15 [ERROR] CatalogController dremor-library-unstable [catalog] failed with : failed to update templates. Multiple error occurred: [failed to create template dremor-library-unstable-nfs-provisioner: templates.management.cattle.io "dremor-library-unstable-nfs-provisioner" already exists]

```

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v2.0.3` UI: `v2.0.53` |
|Access|`local` `admin`|
|Route|`NA`|

**Comment by StrongMonkey** [comment] 2018-06-25 20:35
duplicate of https://github.com/rancher/rancher/issues/14186

**Closed** 2018-06-25 21:48 UTC
