### ISSUE TITLE
[BUG] Keycloak admin user cannot see groups for cluster members

### ISSUE THREAD

**Issue by samjustus** [rancher/rancher#45496] opened 2024-05-15 15:13 UTC
**Issue description:**
An admin user can see only groups to which it belongs on keycloak. So in the Rancher scope, the admin cannot see groups assigned to a cluster, or that someone added to an administrator role.

**Business impact:**
One cannot see groups someone else may have assigned to the administrator role. This can result in permissions that are not desired, and this problem cannot be detected.

**Repro steps:**

add a group to a Cluster -> Cluster Members
log in with an administrator that does not belong to that group
You get Unable to fetch principal info
Workaround:
Is a workaround available and implemented? no
What is the workaround:

**Actual behavior:**
Administrators cannot see groups assigned to cluster memberships unless they are part of that group on keycloak

**Expected behavior:**
Administrators should be able to see groups assigned to clusters

**Comment by samjustus** [comment] 2024-05-15 15:14
[SURE-6002](https://jira.suse.com/browse/SURE-6002)

**Comment by alegrey91suse** [comment] 2024-07-10 09:29
Hi @samjustus, I'd like to try to take care of this issue if you agree.

**Comment by alegrey91** [comment] 2024-07-15 14:01
Hi, I took a look to the issue and tried to reproduce the bug.
In my opinion rancher is working as expected.
Since we are trying to access information that do not belong to the user in keycloak, the same information cannot be fetched from Rancher as well.
Even if the user is an administrator user, if this user doesn't have rights to access these information in keycloak (as it seems to be by default) then rancher should not be able to do it.
I don't know if this could be handled by keycloak in some way by adding some rights to the users, but rancher should only reflect what the user can do from keycloak.

**Comment by alegrey91** [comment] 2024-08-05 14:32
@samjustus should we close this issue since it doesn't seems to be a bug?

**Closed** 2024-08-06 11:55 UTC
Labels: kind/bug, priority/1, area/rbac, JIRA, team/collie
