### ISSUE TITLE
Clusters become unreachable via helm and kubectl after some times even after upgrading to v2.6.6

### ISSUE THREAD

**Issue by hemanth4984** [rancher/rancher#38163] opened 2022-07-01 16:23 UTC
**Rancher Server Setup**
- Rancher version: v2.6.6
- Installation option (Docker install/Helm Chart): 
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): RKE2 - v1.23.6+rke2r1

**Information about the Cluster**
- Kubernetes version: v1.21.7
- Cluster Type (Local/Downstream):
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider): Imported

**User Information**
- What is the role of the user logged in? (Admin/Cluster Owner/Cluster Member/Project Owner/Project Member/Custom) - Admin
  - If custom, define the set of permissions: 

  
**Describe the bug**
https://github.com/rancher/rancher/issues/37250 - This issue still exists even after upgrading to v2.6.6

**Additional context**
Getting below error:

helm upgrade --install dev-calico-ipam . '--kubeconfig=****' '--namespace=dev-ipam'
Error: Kubernetes cluster unreachable: Get "https://rancher.xyz.net/k8s/clusters/c-123/version?timeout=32s": net/http: TLS handshake timeout

**Comment by git-ival** [comment] 2022-07-01 18:02
Hi @hemanth4984 can you provide more details on the steps leading to the error? 

General questions:
* Did you upgrade Rancher itself to 2.6.6 or is this a new install? 
  * If you upgraded, what version of Rancher were you on previously?
* It seems like you're seeing a TLS timeout only when trying to upgrade calico. Do other kubectl/helm commands work as expected while using Rancher 2.6.6?
* Are the Rancher pods themselves running fine?
* Are there any Rancher logs from around the time you ran that upgrade command that might be helpful?

**Comment by rmweir** [comment] 2022-07-01 18:39
Does restarting the rancher pod temporarily resolve the issue?

**Comment by Arjen4357** [comment] 2022-07-01 19:40
> Hi @hemanth4984 can you provide more details on the steps leading to the error?
> I am his colleague and can answer these questions.
> General questions:
> 
> * Did you upgrade Rancher itself to 2.6.6 or is this a new install? upgraded from 2.6.4 to 2.6.6
>   
>   * If you upgraded, what version of Rancher were you on previously? 2.6.4
> * It seems like you're seeing a TLS timeout only when trying to upgrade calico. Do other kubectl/helm commands work as expected while using Rancher 2.6.6? nope, it is the same issue with other helm commands. This is just an example of failing command. Also, even without restart some helm commands work and most of them fail with "cluster unreachable" error.
> * Are the Rancher pods themselves running fine? yes pods are running without any issues.
> * Are there any Rancher logs from around the time you ran that upgrade command that might be helpful? 
> * Is your Rancher cluster certificate valid? yes certificate is valid till next year.

**Comment by Arjen4357** [comment] 2022-07-01 19:43
> Does restarting the rancher pod temporarily resolve the issue?
Even without restarting some requests are working. And with restart again some work and most don't. They fail with "cluster unreachable" "TLS handshake timeout" error

**Comment by Arjen4357** [comment] 2022-07-04 10:46
Can someone respond here? rancher pod restarts workaround is not reliable as 60-70% of the deployments are failing. we are unable to deploy anything to downstream clusters due to this issue.

**Comment by liyimeng** [comment] 2022-07-05 20:51
This only happen when running kubectl from Rancher ui? or also happen if running kubectl directly toward k8s API server?

**Comment by Arjen4357** [comment] 2022-07-05 21:53
> This sounds unrelated to 37250, as that issue was solved consistently by restarting rancher pods. Restarting reset the communication buffer until it got overloaded again. This issue sounds more like there is a consistent issue on any communication regardless of context, and that typically points to more environmental issues.
> 
> * Does this happen with kubectl or only helm ?
        Happens with both.
> * Does it happen with both a generated kubeconfig and the shell pod ?
      We use generated kubeconfig method.
> * Does it happen when going directly to downstream cluster ?
      Nope,  only when proxied through rancher
> * Was there a version of Rancher you were running that didn't see this problems ?
      Earlier we were on 2.6.3 and didn't see this issue.
> * Do rancher logs contain specific errors ?
      Not sure

**Comment by Arjen4357** [comment] 2022-07-05 21:53
> This only happen when running kubectl from Rancher ui? or also happen if running kubectl directly toward k8s API server?

Only via Rancher.

**Comment by liyimeng** [comment] 2022-07-11 12:42
> > This only happen when running kubectl from Rancher ui? or also happen if running kubectl directly toward k8s API server?
> 
> Only via Rancher.

@Arjen4357 Thanks. Good that workload should not be impacted.

**Comment by rmweir** [comment] 2022-07-14 23:26
What sized nodes are you using for your local cluster and affected downstream cluster?

**Comment by terryf82** [comment] 2022-07-21 03:26
This sounds like what we just dealt with today, after upgrading from `2.6.2` to `2.6.6`. Everything appeared normal in the UI, but deploying / upgrading apps to downstream clusters ceased to function. In the logs of one of the rancher pods I discovered:
```
handler helm-controller: failed to install app. Error: Kubernetes cluster unreachable: unknown
```

We soon rolled back to `2.6.2` (not a simple task given the breaking changes of `2.6.4`, but thankfully it worked). All clusters involved are EKS `v1.20`, apologies I don't have more context to add.

**Comment by DeyvsonL** [comment] 2023-04-11 03:43
I still have the same issue on Rancher 2.6.11 and custom (docker command) RKE1 v1.24.10-rancher4-1.
I can't see the cluster on UI or interact with kubectl, but on Rancher API I can still find the cluster and the cluster state is always updating.

**Comment by cbron** [comment] 2023-10-30 19:40
Going to close this due to being unreproducible on our side.

**Closed by cbron** 2023-10-30 19:40 UTC
