### ISSUE TITLE
Namespaces are not getting created because it could not find roleTemplates

### ISSUE THREAD

**Issue by DinshKW44** [rancher/rancher#26653] opened 2020-04-16 16:31 UTC
**What kind of request is this (question/bug/enhancement/feature request):**
Question/Issue

**Steps to reproduce (least amount of steps as possible):**
When I create namespace, it gets stuck in activating state. The namespace is created under a project in rancher. 
 I am using rancher 2.3.4v and k8s version 1.16.3. I imported an existing k8s cluster into rancher. When I create a namespace through rancher in a project, it gets stuck in activating state. When checked on k8s end, it is active. The user through which I am creating namespace in rancher is having project owner access. The error from rancher says "[ERROR] NamespaceController ******* [namespace-auth] failed with : couldn't get role template rt-j6dbw: roleTemplate.management.cattle.io "rt-j6dbw" not found" But I could not find the roleTemplate at all.

If i create a namespace outside the project and move into into error occurring project, the namespace disappears for few users.

**Result:**
Namespace gets stuck in activating state

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): 2.3.4
- Installation option (single install/HA): Yes

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): Imported
- Machine type (cloud/VM/metal) and specifications (CPU/memory): VM
- Kubernetes version (use `kubectl version`): 1.16.3

```
(paste the output here)
```

- Docker version (use `docker version`):

```
(paste the output here)
```

**Comment by izaac** [comment] 2020-04-16 23:02
I am not able to reproduce in Rancher version: `v2.3.4` and an imported RKE cluster with k8s `v1.16.3-rancher1-1` (Node roles: 1 all, 2 workers).

I import the cluster.
I add `user1` as standard user.
Cluster gets active.
As `admin` I create `project1` and add `user1` as project owner.
As `user1` I create a namespace `ns1` in `project1`. It goes active.
As `admin` I create namespace `ns2` in `project1`. It goes active.

Login as admin add `user2`
As `user1` I create `project2` and add `user2` as project owner.
As `user2` I create a namespace `ns3` in `project2`. It goes active.
As `user1` I create namespace `ns4` in `project2`. It goes active.
As `admin` I create namespace `ns5` in `project2`. It goes active.

@DinshKW44 do you have any more details to share to see if I can reproduce with more info?

**Comment by DinshKW44** [comment] 2020-04-17 13:37
I am really sorry. Firstly, we were on k8s version 1.12.3. When on 1.12.3, I created a project and added users to it. Also, some of the users were given project owner access and some were given custom role access such as LimitRange with Project owner inherited, LimitRange, ServiceMonitor & Prometheus. It worked all fine. 
After upgrading the cluster to 1.16.3, I am starting to face these issues. None of the custom roles were edited. When in 1.16.3, one of the user with project owner access creates a namespace, it goes into activating state and for some of the users, the namespaces disappears (they could not view it). When checked internally in the k8s cluster, I can view those namespaces. For example:
I have cluster admin access and I create a namespace, I get the following error:
2020/04/17 13:31:50 [ERROR] NamespaceController test-willbedeleted [namespace-auth] failed with : couldn't get role template rt-j6dbw: roleTemplate.management.cattle.io "rt-j6dbw" not found
2020/04/17 13:31:50 [ERROR] NamespaceController test-willbedeleted [namespace-auth] failed with : couldn't get role template rt-j6dbw: roleTemplate.management.cattle.io "rt-j6dbw" not found
2020/04/17 13:31:51 [ERROR] NamespaceController test-willbedeleted [namespace-auth] failed with : couldn't get role template rt-j6dbw: roleTemplate.management.cattle.io "rt-j6dbw" not found

 When I search for the roleTemplate, I do not find it:
kubectl get roleTemplate | grep rt-j6dbw

**Comment by izaac** [comment] 2020-04-17 16:43
@DinshKW44 thanks for the extra information I will take a look at this and try to reproduce.

**Comment by DinshKW44** [comment] 2020-04-17 20:07
Hey @izaac thank you. I found the issue. My teammate, when he checked, he observed that one of the users had no roles assigned inside the project. Normally rancher does not allow to add a user to project without a role but this is weird. Somehow the  user did not have any role.  As soon as we deleted the user without a role, everything got fixed.

**Comment by izaac** [comment] 2020-04-17 23:21
@DinshKW44 I was about to update the issue and tell you I wasn't able to reproduce, I tried a few scenarios around Custom Roles and Project access. It's not straightforward since it's a very old k8s version upgraded to 1.16.3. There are built-in and default roles too, it might be the reason the user was allowed? 

Thanks for updating.

**Comment by izaac** [comment] 2023-02-22 02:47
Closing, open if this is still an issue or if it is reproducible on latest Rancher versions.

**Closed by izaac** 2023-02-22 02:47 UTC
Labels: [zube]: To Triage
