### ISSUE TITLE
[2.7] Unable to RollBack cattle-token to the previous one

### ISSUE THREAD

**Issue by dasarinaidu** [rancher/rancher#39895] opened 2022-12-14 00:01 UTC
**Rancher Server Setup**
- Rancher version: `v2.7`
- Installation option (Docker install/Helm Chart): Helm
- RKE2 Cluster

**Describe the bug**
User trying to Rollback the cattle-token to the previous version but the system is throwing an exception and unable to rollback to the previous version.

**To Reproduce**

1. Login into Rancher (v2.7)
2. Create RKE2 cluster
3. Delete the cattle-token (Cluster Explorer -> Storage->Secrets -> cattle-system-> cattle-token)
4. Navigate to Deployment -> cattle-cluster-agent -> Three dots ->Select option RollBack
5. Check for the token selection window for RollBack
6. Select a revision from drop down and Click Roll Back

**Result**
1. User getting an Error message
2. System is throwing 422 error code
3. Rollback did not happened to previous token

**Expected Result**
1.  System should rollback the `cattle-token` to the previously selected `cattle-token` ( based on the selection by user)

**Service Details**
```
Request URL: xxxxxxx/c-m-kqcfqnxg/apis/apps/v1/namespaces/cattle-system/deployments/cattle-cluster-agent
Request Method: PATCH
Status Code: 422 
Response : 
{
  "kind": "Status",
  "apiVersion": "v1",
  "metadata": {},
  "status": "Failure",
  "message": "Deployment.apps \"cattle-cluster-agent\" is invalid: spec.template.metadata.labels: Invalid value: map[string]string{}: `selector` does not match template `labels`",
  "reason": "Invalid",
  "details": {
    "name": "cattle-cluster-agent",
    "group": "apps",
    "kind": "Deployment",
    "causes": [
      {
        "reason": "FieldValueInvalid",
        "message": "Invalid value: map[string]string{}: `selector` does not match template `labels`",
        "field": "spec.template.metadata.labels"
      }
    ]
  },
  "code": 422
} 
```

**Screenshots**
Rollback Option: 
![image](https://user-images.githubusercontent.com/22034884/207468874-4a113585-efa8-4ae5-996b-f365854fe113.png)

Rollback to Revision screen:
![image](https://user-images.githubusercontent.com/22034884/207469403-bd45108a-5b54-434b-a965-f536af806335.png)

Error: 
![image](https://user-images.githubusercontent.com/22034884/207469443-cb46fdfb-515f-422e-bd49-60491a8d15cb.png)

**Additional context**
1. This is happening on HA & Docker installed rancher
2. Issue is with RKE1, RKE2 and K3 clusters
3. Issue existed on v2.6.7, v2.6.9, v2.7-head

**Comment by dasarinaidu** [comment] 2022-12-14 00:22
This might be root cause of https://github.com/rancher/rancher/issues/39103

**Comment by anupama2501** [comment] 2022-12-14 16:23
Closing as its a duplicate of the linked issue.

**Closed by anupama2501** 2022-12-14 16:23 UTC
Labels: kind/bug, team/area1
