### ISSUE TITLE
Adding support for private Docker registries in Kubernetes  

### ISSUE THREAD

**Issue by galal-hussein** [rancher/rancher#4547] opened 2016-04-25 19:20 UTC
Rancher Version:
1.0.1
Docker Version:
1.10.1

Adding private registries in Rancher should affect kubernetes as well, i tried adding a credentials for Docker hub in rancher and then run a private image in a pod, and it failed to pull the image:

```
 12s		12s		1	{default-scheduler }					Normal		Scheduled	Successfully assigned awesomeapp to node-02
  11s		11s		1	{kubelet node-02}	spec.containers{awesomeapp}	Normal		Pulling		pulling image "husseingalal/awesomeapp"
  9s		9s		1	{kubelet node-02}	spec.containers{awesomeapp}	Warning		Failed		Failed to pull image "husseingalal/awesomeapp": Error: image husseingalal/awesomeapp not found
  9s		9s		1	{kubelet node-02}					Warning		FailedSync	Error syncing pod, skipping: failed to "StartContainer" for "awesomeapp" with ErrImagePull: "Error: image husseingalal/awesomeapp not found"

  9s	9s	1	{kubelet node-02}	spec.containers{awesomeapp}	Normal	BackOff		Back-off pulling image "husseingalal/awesomeapp"
  9s	9s	1	{kubelet node-02}					Warning	FailedSync	Error syncing pod, skipping: failed to "StartContainer" for "awesomeapp" with ImagePullBackOff: "Back-off pulling image \"husseingalal/awesomeapp\""
```
However i was able to pull the image and run it inside a pod successfully by creating a registry secret and then use podspec.imagePullSecret as described [here](http://kubernetes.io/docs/user-guide/images/#specifying-imagepullsecrets-on-a-pod)

**Comment by deniseschannon** [comment] 2016-04-27 23:56
Duplicate of https://github.com/rancher/rancher/issues/4529

**Closed by deniseschannon** 2016-04-27 23:56 UTC
