### ISSUE TITLE
[feature] Allow Services to configure upper limit for instance count

### ISSUE THREAD

**Issue by sshipway** [rancher/rancher#2582] opened 2015-11-06 03:23 UTC
In some cases, a Service needs to have a maximum instance count.  For example, your nginx service can have any number of instances, but your pgsql container with persistant filesystem needs to be limited to 1 instance and 1 only.

It would be useful for a Service to be able to specify a hard upper limit on the instance count, so that the ScaleUp button disappears when it reches this level, and the Instances slider will not go above the value.

Another possibility would be having a third option of "Single instance only" along with the existing "1 instance on every host" or "Run X containers", or a checkbox for "Cannot be changed" on the number of instances.

**Comment by demarant** [comment] 2015-11-07 11:33
this FR looks like a dupe of #2590

**Comment by vincent99** [comment] 2015-11-07 17:57
For what was asked yes..

But limiting the scale isn't really good enough if you are running a database. If the container or host dies, the scale is 0 and should be 1 so a new one is scheduled to a potentially different host without your data, which probably isn't super helpful.

Without shared storage it seems you really want to use a standalone container so that there is no automatic scheduling, or a service scheduled to match a unique host label (and then additionally restrict changing the scale with #2590)

**Comment by will-chan** [comment] 2017-01-30 02:12
Using #2590 to track this.

**Closed by will-chan** 2017-01-30 02:12 UTC
Labels: area/service, kind/feature
