### ISSUE TITLE
[BUG] Possible memory leak on accesscontrol/schemas

### ISSUE THREAD

**Issue by aruiz14** [rancher/rancher#47318] opened 2024-09-30 15:50 UTC
**Rancher Server Setup**
- Rancher version: >=2.8, possibly earlier too
- Installation option (Docker install/Helm Chart): no special instructions needed

**Information about the Cluster**
- Kubernetes version: any
- Cluster Type (Local/Downstream): any

**Describe the bug**
Analysis of heap profiling shows unexpected usage around accesscontrol/schemas. While investigating, I detected that multiple concurrent usage (e.g. driven by UI usage), could cause multiple routines to all try to Add a new entry to the cache. I have no definitive evidence this causes a leak under all circumstances, maybe it needs rapidly-changing roles to invalidate the cache to trigger the problem, but it's still not optimal.

**Comment by rancher-max** [comment] 2024-10-28 19:32
@aruiz14 Does this only happen when we have concurrent users in the UI all trying to add things at the same time? Is it able to be replicated via just the API by chance, do you know?

Also, do the tests you wrote cover the fixes (i.e no additional QA testing needed)?

**Comment by aruiz14** [comment] 2024-10-29 07:49
Hi @rancher-max, it's not easy at all to replicate this issue. The changes applied here (and #47460) aim to refactor the code to handle better concurrency management. I can't think of any specific validations you could run. My suggestion would be to test both of them together and just ensure that access control works as expected.

**Comment by rancher-max** [comment] 2024-11-07 18:27
Test we're planning on running:

1. Bring up Rancher with three downstreams and a few objects (our baseline setup)
2. Run the k6 test for access control:
  a. Create roles and users multiple times concurrently
  b. Login concurrently with all users
3. Check memory to ensure it is not steadily increasing after user sessions are closed.

This should hopefully tell us something, but if not we will just close the issue as there are the functional tests written around this already and if we notice in the future then we can try to define a better test to replicate.

**Comment by MSpencer87** [comment] 2024-11-14 03:37
**Unable to reproduce memory leak on Rancher v2.8.0**

**No persistent memory increases observed on Rancher v2.10.0 from baseline access control tests**


**Steps for validation**
1. Bring up HA Rancher on v2.10.0-alpha12, install Monitoring and set CATTLE_PROMETHEUS_METRICS=true
2. Import 3 downstream clusters
3. Create 1000 ConfigMaps via create_k8s_resources.js taken from https://github.com/rancher/dartboard/blob/main/k6/create_k8s_resources.js
```
k6 run -e KUBECONFIG=$PATH_TO_KUBECONFIG -e CONTEXT=$CONTEXT -e BASE_URL=$K8S_API_URL -e CONFIG_MAP_COUNT=1000 -e SECRET_COUNT=1 create_k8s_resources.js
```
4. Create 50 Users and 50 Roles via create_roles_users.js taken from https://github.com/rancher/dartboard/blob/main/k6/create_roles_users.js , delete users and roles manually via UI, create roles and users again, repeat a few times, adjust vus up to 20 on various runs
```
k6 run -e KUBECONFIG=$KUBECONFIG -e CONTEXT=$CONTEXT -e COUNT=$COUNT ./create_roles_users.js
```
5. Run heap monitor script, verify no memory leaks are present during access control tests
```
while true; do
	for pod in $(kubectl -n cattle-system get pods -l app=rancher --no-headers -o custom-columns=name:.metadata.name); do
		kubectl exec -n cattle-system ${pod} -c rancher -- curl -s http://localhost:6060/debug/pprof/heap -o heap
		kubectl cp -n cattle-system -c rancher ${pod}:heap ./heap

		go tool pprof -top --trim=false ./heap
	done
done
```
view heap data with locally via pprof
```
pprof -http=localhost:8080 heap
```

**Closed by MSpencer87** 2024-11-14 03:37 UTC
Labels: kind/bug, area/steve, team/bullseye-qa
