### ISSUE TITLE
Massive rancher-agent logs filled with repeated unable to get usage from thin pool device

### ISSUE THREAD

**Issue by goffinf** [rancher/rancher#5512] opened 2016-07-22 08:42 UTC
**Rancher Version:**

1.1.0

**Docker Version:**

1.10.3

**OS and where are the hosts located? (cloud, bare metal, etc):**

RHEL 7.2 / AWS

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**

HA Rancher (3 nodes), external Db

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**

Cattle

**Steps to Reproduce:**

OOTB install/config of Rancher so no special use case instructions.

The docker install uses the default RHEL script based from the Docker docs: https://docs.docker.com/engine/installation/linux/rhel/

docker demon is configured:

-H fd:// -H tcp://0.0.0.0:2375 -H unix:///var/run/docker.sock --graph=/data/docker ...

/data is the mouint point for atached EBS of 100GB

Docker info returns (note: the devicemapper storage driver is using 'loop-back'. We are aware of the warning advice around use for production (this is a non production environment):

[ec2-user@10-64-3-158 ~]$ docker info
Containers: 11
 Running: 8
 Paused: 0
 Stopped: 3
Images: 12
Server Version: 1.10.3
Storage Driver: devicemapper
 Pool Name: docker-202:160-5767172-pool
 Pool Blocksize: 65.54 kB
 Base Device Size: 10.74 GB
 Backing Filesystem: xfs
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 4.205 GB
 Data Space Total: 107.4 GB
 Data Space Available: 99.78 GB
 Metadata Space Used: 7.037 MB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.14 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Data loop file: /data/docker/devicemapper/devicemapper/data
 WARNING: Usage of loopback devices is strongly discouraged for production use. Either use `--storage-opt dm.thinpooldev` or use `--storage-opt dm.no_warn_on_loop_devices=true` to suppress this warning.
 Metadata loop file: /data/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.107-RHEL7 (2015-12-01)
Execution Driver: native-0.2
Logging Driver: json-file
Plugins:
 Volume: local
 Network: host bridge null
Kernel Version: 3.10.0-327.18.2.el7.x86_64
Operating System: Red Hat Enterprise Linux Server 7.2 (Maipo)
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 7.389 GiB
Name: 10-64-3-158.avivaaws.com
ID: HMJO:PGNN:3PGU:URHH:2LKZ:KKWB:HWSE:UUAG:2WQY:LM65:U7OE:U3PR
Http Proxy: http://uknp-obproxy.avivaaws.com:80
Https Proxy: http://uknp-obproxy.avivaaws.com:80
No Proxy: localhost,127.0.0.1,10.*,docker-registry-private-digital.avivaaws.com,docker-registry-mirror-digital.avivaaws.com,.via.novonet,.avivagroup.com,.avivaaws.com,.ecs.com,169.254.169.254
WARNING: bridge-nf-call-iptables is disabled
WARNING: bridge-nf-call-ip6tables is disabled

**Results:** 

Thousands of repeated messages about thin pool fs usage (sample below).

This happens on all Rancher HA servers AND on all hosts.

I have attached a zip file containing the following:

1. var-log-rancher-agent.log (/var/log/rancher/agent.log) from one of the Rancher HA servers
2. rancher-agent-cointainer-server.log (truncated output from the command docker logs rancher-agent >rancher-agent.log 2>&1) taken from the same Rancher HA server in (1)
3. rancher-agent-host.log (truncated output from the command docker logs rancher-agent >rancher-agent.log 2>&1) from one of the registered Hosts.

(2) and (3) output have been truncated because clearly the logs are massive. I stopped the output from the command above when the file size reached 1GB !!

E0708 15:56:27.759654   26468 thin_pool_watcher.go:65] encountered error refreshing thin pool watcher: error performing thin_ls on metadata device /dev/loop1: Error running command `thin_ls --no-headers -m -o DEV,EXCLUSIVE_BYTES /dev/loop1`: exec: "thin_ls": executable file not found in $PATH
output:

E0708 15:56:28.355016   26468 handler.go:278] unable to get fs usage from thin pool for device 128: no cached value for usage of device 128
E0708 15:56:29.823608   26468 handler.go:278] unable to get fs usage from thin pool for device 128: no cached value for usage of device 128
E0708 15:56:31.073218   26468 handler.go:278] unable to get fs usage from thin pool for device 128: no cached value for usage of device 128
E0708 15:56:32.829584   26468 handler.go:278] unable to get fs usage from thin pool for device 128: no cached value for usage of device 128
E0708 15:56:34.492505   26468 handler.go:278] unable to get fs usage from thin pool for device 128: no cached value for usage of device 128
E0708 15:56:36.007645   26468 handler.go:278] unable to get fs usage from thin pool for device 128: no cached value for usage of device 128
time="2016-07-08T14:56:36Z" level="info" msg="Processing event: &docker.APIEvents{Status:\"start\", ID:\"9c33b8f0e8cb296f6f03c0291a6f4933c733f4b479ee1a4367e8d86bec9d6964\", From:\"rancher/agent-instance:v0.8.3\", Time:1467989796}" 
time="2016-07-08T14:56:36Z" level="info" msg="Assigning IP [10.42.34.130/16], ContainerId [9c33b8f0e8cb296f6f03c0291a6f4933c733f4b479ee1a4367e8d86bec9d6964], Pid [26989]" 
time="2016-07-08T14:56:36Z" level="info" msg="Processing event: &docker.APIEvents{Status:\"start\", ID:\"9c33b8f0e8cb296f6f03c0291a6f4933c733f4b479ee1a4367e8d86bec9d6964\", From:\"-simulated-\", Time:0}" 
E0708 15:56:37.215847   26468 handler.go:278] unable to get fs usage from thin pool for device 135: no cached value for usage of device 135
E0708 15:56:37.462914   26468 handler.go:278] unable to get fs usage from thin pool for device 128: no cached value for usage of device 128
E0708 15:56:38.298222   26468 handler.go:278] unable to get fs usage from thin pool for device 135: no cached value for usage of device 135
E0708 15:56:38.729387   26468 handler.go:278] unable to get fs usage from thin pool for device 128: no cached value for usage of device 128
E0708 15:56:39.828470   26468 handler.go:278] unable to get fs usage from thin pool for device 128: no cached value for usage of device 128
E0708 15:56:39.920311   26468 handler.go:278] unable to get fs usage from thin pool for device 135: no cached value for usage of device 135
E0708 15:56:41.551592   26468 handler.go:278] unable to get fs usage from thin pool for device 135: no cached value for usage of device 135
E0708 15:56:41.772358   26468 handler.go:278] unable to get fs usage from thin pool for device 128: no cached value for usage of device 128
I0708 15:56:43.952712   26468 thin_pool_watcher.go:117] reserving metadata snapshot for thin-pool docker-202:160-5767172-pool
E0708 15:56:43.994912   26468 handler.go:278] unable to get fs usage from thin pool for device 135: no cached value for usage of device 135
E0708 15:56:43.995018   26468 thin_pool_watcher.go:65] encountered error refreshing thin pool watcher: error performing thin_ls on metadata device /dev/loop1: Error running command `thin_ls --no-headers -m -o DEV,EXCLUSIVE_BYTES /dev/loop1`: exec: "thin_ls": executable file not found in $PATH
output:

**Expected:**

A MUCH smaller log for the rancher-agent container
[aviva-rancher-agent-logs.zip](https://github.com/rancher/rancher/files/377798/aviva-rancher-agent-logs.zip)

**Comment by goffinf** [comment] 2016-07-23 16:11
I can confirm that after configuring the LVM thinpool storage using the scrip provided by Redhat, the rancher-agent messages appear to have ceased. I will continue to monitor, and if this remains the case I will close the ticket.

**Comment by cjellick** [comment] 2016-07-25 15:47
@goffinf can you point me at that script?

**Comment by goffinf** [comment] 2016-07-25 20:07
Hey Craig,

sure. The script I'm referring to of course is the docker-storage-setup that comes with the RHEL docker binary install (rather than the default install from docker). As I'm sure you are aware Redhat is very picky about the details and in my experience it isn't possible to successfully configure the devicemapper LVM thinpool storage unless you use both the docker binary from Redhat and the setup script (attached). Trying to do otherwise typically just results in the storage setup script hanging and the meta and data pools created utterly unusable.

Using the default (loopback) storage driver config is clearly not ideal and on RHEL at least results in the proliferation of error messages outlined above from the rancher-agent container. Configuring devicemapper thinpool remedies that.

However, there's no free lunch here. I would say I am a bit unhappy being locked in to a vendor's roadmap for docker but the reality is that at present this is the only sanctioned distro at the org that I work for.

This ticket came about following a different rancher-agent problem which I've raised separately:-

https://github.com/rancher/rancher/issues/5528

Jul 21 16:34:47 10-64-13-250 docker: time="2016-07-21T16:34:47.329682223+01:00" level=error msg="Handler for GET /v1.22/containers/rancher-ha-agent/json returned error: No such container: rancher-ha-agent"
Jul 21 16:34:52 10-64-13-250 docker: time="2016-07-21T16:34:52.553092835+01:00" level=error msg="Handler for GET 

HTHs

Fraser
[docker-storage-setup.zip](https://github.com/rancher/rancher/files/382363/docker-storage-setup.zip)

**Comment by cjellick** [comment] 2016-07-26 00:06
Thanks for the info @goffinf. I was aware of RHEL's pickiness, but not of the script, as I typically don't run on RHEL. At any rate, I was actually asking about the script on behalf of a user that was experiencing the same problem.  But I've now realized that that user is you. :-)

**Comment by goffinf** [comment] 2016-07-26 07:50
Hehe. Would still be good to understand why the rancher-agent reports this configuration difference, and indeed quite so vociferously ! Using the loopback device isn't really an error as such and, whilst I can rotate the logs, they quickly become completely full of this message which hides other important output.

**Comment by cjellick** [comment] 2016-07-26 15:13
It is actually cadvisor, the third party stats gathering/reporting tool we use which is logging that error. It looks like it was relatively recently reported here:
https://github.com/google/cadvisor/issues/1306

and following the issue trail to the ultimate PR, a _possible_ fix was merged in June: https://github.com/google/cadvisor/pull/1327.

So, it may be time for us to look into updating cadvisor again.

So that we can test a newer version of cadvisor, what would the steps to reproduce be @goffinf? Basically, just run RHEL docker on a RHEL vm, but without running the storage setup script?

**Comment by goffinf** [comment] 2016-07-26 19:42
Yes that approach would seem to be a close enough approximation of my environment. I am running an AWS instance with a specifically hardened CIS based AMI build, but there is no evidence to suggest any of that would effect these results. I can send you the very specific steps that form this part of the AMI build if that would help, although they are taken pretty much verbatim from the Redhat Openshift docker install docs. I would be more that happy to test a revised version of the agent container as well if you want. I am in regular contact with your UK colleagues (Chris Urwin and Simon Robinson) so they could easily coordinate testing with us (Aviva - we are a large financial services organisation).

Regards

Fraser.

**Comment by cjellick** [comment] 2016-07-26 19:53
Looks like the fix made it into a pre-release of cadvisor:
https://github.com/google/cadvisor/releases/tag/v0.23.4

**Comment by goffinf** [comment] 2016-07-27 07:43
To clarify what I said earlier. To reproduce you just need a to follow a standard docker install (per the docker docs) on RHEL, specifically NOT using the docker binary from Redhat, and leaving the default devicemapper config as loopback. On site I use install from a local RPM to ensure that the vagaries of the Internet do not impact our internal build process, but that is likely not important.

I'll check if the rancher-agent (via cadvisor) messages also appear for a local Centos VM in case that makes it easier for you to test (rather than have to provide a valid Redhat subscription)

The instructions from the Openshift docs I was referring are of course how to configure the thinpool device to work with this distro (so most likely you don't need those).

**Comment by cjellick** [comment] 2016-07-27 16:48
@goffinf I just repro'd on a local centos vm

**Comment by cjellick** [comment] 2016-07-27 23:25
Was able to resolve the issue with the above PR. This'll go into our next release.

**Comment by goffinf** [comment] 2016-07-28 07:06
Thx Craig. Do you mean the next point release of Rancher as a whole (1.1.1 ?) or do you release the rancher-agent separately (obviously I'm keen to upgrade ASAP)

**Comment by cjellick** [comment] 2016-07-29 00:02
@goffinf this _just_ missed our release yesterday (Release v1.2.0-pre1). Next one (pre2) will be in two weeks. In the meantime, I could give you a _no garauntees_ version that you could point your current rancher deployment at, if that interests you.

**Comment by cjellick** [comment] 2016-07-29 00:32
@goffinf Ok, here is the updated cadvisorr. Again, this hasn't been through all our QA yet and won't until our next release. So try at your own risk, but it has worked in my own testing.

https://github.com/rancher/cadvisor-package/releases/download/v0.23.4/cadvisor.tar.gz

You'll want to update the `agent.package.cadvisor.url` setting. You can do this through the browser or via curl. To do it via browser, go to http://<your rancher server ip>:8080/v1/activesettings/1as!agent.package.cadvisor.url, click edit, and update the value to `https://github.com/rancher/cadvisor-package/releases/download/v0.23.4/cadvisor.tar.gz`

After you set the setting, it looks like you'll have to restart the rancher-agent containers on your hosts for it to take affect. Or it may happen after some amount of time on my own, but I restarted to ensure it happened immediately.


FYI, the release will have the new version baked in, you won't have to set this setting if you wait for the release.

**Comment by goffinf** [comment] 2016-07-29 08:26
Thx @cjellick, I might give this a go in a sandpit Rancher environment. Working for a relatively conservative org it might be difficult for me to get approval for a 'pre' release version in our prod environment, so I'm a bit stuck between a rock and a hard place ... but that's my problem, you've done your part.

I appreciate your attention for this one. .... Now if you could just sort out this related one too ;-) ... https://github.com/rancher/rancher/issues/5528

**Comment by cjellick** [comment] 2016-07-29 20:07
@goffinf I had a feeling pulling the pre release might be a stretch, just wanted to get the option out there.

**Comment by sangeethah** [comment] 2016-09-08 19:05
Tested with rancher-server version  - v1.2.0-pre3-rc1.

We are still getting - cAdvisor version 0.23.2
```
root@sangeev120pre3rc1-10acre-1:/var/lib/cattle/bin# ./cadvisor --version
cAdvisor version 0.23.2 ()
```

**Comment by deniseschannon** [comment] 2016-09-09 18:37
@sangeethah Please re-test whenever v1.2.0-pre3-rc2 is created.

**Comment by soumyalj** [comment] 2016-09-13 21:47
Tested with v1.2.0-pre3-rc3. The message "unable to get fs usage from thin pool for device" is not seen any more.
The cadvisor version is below:
root@ip-172-31-18-38:/var/lib/cattle/bin# ./cadvisor --version
cAdvisor version 0.23.4 ()

**Closed by soumyalj** 2016-09-13 21:47 UTC
Labels: status/resolved, status/to-test
