### ISSUE TITLE
Storage pool persists after convoy-gluster removed

### ISSUE THREAD

**Issue by hrwebasst** [rancher/rancher#2893] opened 2015-12-03 18:46 UTC
I attempted to launch convoy-gluster and it failed I rinse washed and repeated a couple times(kept getting stuck at degraded and only made two containers on one host) and then gave up deleting it.

I noticed in storage pools even though I had deleted the containers from the host and the stack that it remained.

![pools](https://cloud.githubusercontent.com/assets/9060082/11570246/0d065fd4-99ab-11e5-9d6b-88ae6ad6489d.png)

**Comment by deniseschannon** [comment] 2015-12-03 18:56
What OS are you running? If you are running CoreOS, you may be hitting this issue: https://github.com/rancher/rancher/issues/2836

The storate pool removal is a duplicate of https://github.com/rancher/rancher/issues/2788.

**Comment by hrwebasst** [comment] 2015-12-03 19:01
I'm running ubuntu 14.04

![convoy](https://cloud.githubusercontent.com/assets/9060082/11570644/2976c436-99ad-11e5-9192-5596c1c1aab5.png)
![screenshot from 2015-12-03 11 00 12](https://cloud.githubusercontent.com/assets/9060082/11570647/2e72f982-99ad-11e5-814c-2a4264e16fef.png)

**Comment by cjellick** [comment] 2015-12-03 21:14
@hrwebasst The fact that the storage pool isn't deleted is a known issue that we'll be fixing soon. Thanks for reporting.

Would you be able to share more information about the issue that you were running into with actually deploying convoy-gluster? What would be most helpful is a view of which convoy-gluster containers were not starting and the full logs from one such container.

Thanks in advance!

**Comment by hrwebasst** [comment] 2015-12-03 21:16
@cjellick if you want to find me on irc corn13read I can give you full access to my environment. It's just standard ubuntu 14.04 with docker 1.9.0 and v0.47.0 rancher. I have successfully deployed gluster to 3 and 4 hosts but no matter how I skin it I can't get convoy-gluster to deploy

**Comment by amalagaura** [comment] 2015-12-03 21:22
I am having this same issue. I was recreating gluster and convoy-gluster a few times because I needed to recreate gluster and am unable to get convoy-gluster started again.

I tried creating different names for the storage-pool and volumes but no luck either. Will rebooting clear this?

```
12/3/2015 4:22:29 PMtime="2015-12-03T21:22:29Z" level=debug msg="Volume gluster-volume is being mounted it to /var/lib/rancher/convoy/convoy-gluster-5fb86e34-64fb-4e60-91eb-31511b36d2f7/glusterfs/mounts/gluster-volume, with option [-t glusterfs]" pkg=util
12/3/2015 4:22:30 PMtime="2015-12-03T21:22:30Z" level=debug msg="Cleaning up environment..." pkg=daemon
12/3/2015 4:22:30 PMtime="2015-12-03T21:22:30Z" level=error msg="Failed to execute: mount [-t glusterfs glusterfs:/gluster-volume /var/lib/rancher/convoy/convoy-gluster-5fb86e34-64fb-4e60-91eb-31511b36d2f7/glusterfs/mounts/gluster-volume], output Mount failed. Please check the log file for more details.\n, error exit status 1"
12/3/2015 4:22:30 PM{
12/3/2015 4:22:30 PM	"Error": "Failed to execute: mount [-t glusterfs glusterfs:/gluster-volume /var/lib/rancher/convoy/convoy-gluster-5fb86e34-64fb-4e60-91eb-31511b36d2f7/glusterfs/mounts/gluster-volume], output Mount failed. Please check the log file for more details.\n, error exit status 1"
12/3/2015 4:22:30 PM}
12/3/2015 4:22:30 PMtime="2015-12-03T21:22:30Z" level=info msg="convoy exited with error: exit status 1"
12/3/2015 4:22:30 PMtime="2015-12-03T21:22:30Z" level=info msg=Exiting.
```

**Comment by deniseschannon** [comment] 2015-12-03 21:51
@hrwebasst issue was due to the lack of a host label (on the hosts) in order for the convoy-gluster service to deploy it's containers. 

@amalagaura It sounds as if you have a different issue. Could you open a new one as I'm going to close this one as we have addressed his issue. The inability to remove volumes/storagepools are tracked in  #2788 (deleting the convoy stack doesn't delete the storage pool), #2796 (enabling the ability to delete volumes)

**Closed by deniseschannon** 2015-12-03 21:51 UTC
