### ISSUE TITLE
Flapping behavior seen on rolebinding

### ISSUE THREAD

**Issue by ibuildthecloud** [rancher/rancher#35544] opened 2021-11-16 23:50 UTC
One rolebinding was observed to be flapping back and forth between project id.  This was due to name collision on the generated rolebinding. 

PR: rancher/rancher#35543

**Comment by sgapanovich** [comment] 2021-12-02 23:23
### Test Environment: ###
Rancher version: 2.6.3-rc3 (2.6.2 is used to compare rolebindings)
Rancher cluster type: HA
Docker version: 20.10

----------

### Testing: ###

1. Created a project in the local cluster 
2. Created a standard user
3. Added the user to the project 
4. Ran `kubectl get rolebinding ...` on both cluster (2.6.3-rc3 and 2.6.2)
I see that in 2.6.3-rc3 a project name `p-72f2g` is added to the rolebinding name `r-cluster-local-view-p-72f2g-prtb-xqlzb-wr4qhqhb34` in the `fleet-local` namespace  
```
2.6.3-rc3

NAMESPACE                      NAME                                                              ROLE                                                                  AGE
p-72f2g                        prtb-xqlzb-edit                                                   Role/edit                                                             25s
fleet-local                    r-cluster-local-view-p-72f2g-prtb-xqlzb-wr4qhqhb34                Role/r-cluster-local-view                                             25s
local                          rb-qulyaycvd4                                                     Role/p-72f2g-projectmember                                            25s
local                          p-72f2g-prtb-xqlzb-project-member                                 Role/project-member                                                   25s
p-72f2g                        prtb-xqlzb-project-member                                         Role/project-member                                                   25s



2.6.2

NAMESPACE                      NAME                                                              ROLE                                                                  AGE
p-9pbpk                        prtb-7xmt5-edit                                                   Role/edit                                                             37s
fleet-local                    r-cluster-local-view-prtb-7xmt5-7l5l5jpb7e                        Role/r-cluster-local-view                                             37s
local                          rb-cwdsymgyyf                                                     Role/p-9pbpk-projectmember                                            37s
local                          p-9pbpk-prtb-7xmt5-project-member                                 Role/project-member                                                   37s
p-9pbpk                        prtb-7xmt5-project-member                                         Role/project-member                                                   37s
```
@ibuildthecloud Looking at your PR I suppose that's exactly what you changed. I am not sure how I can reproduce the “flapping” mentioned in the issue to really test the fix. What do i need to do to actually see the flapping (considering that i have two projects in the same cluster with the same user assigned to the same role in those projects)

**Comment by sgapanovich** [comment] 2021-12-11 00:01
Testing continued:

on 2.6.2:
- add the same user to 2 different projects in the same cluster 
  - use the same name for project role template binding (`prtb-s1s1s` was used in POST requests to create data)
- Notice: one rolebinding (for the second project/prtb) is missing
  - it’s created for the first project but it’s not created for the second
  - two projects can claim that rolebinding 

![262](https://user-images.githubusercontent.com/40282141/145655224-677ba250-2826-4bd2-aa4b-20e746f26a3a.jpg)


------


on 2.6head 9295d4f
- add the same user to 2 different projects in the same cluster 
  - use the same name for project role template binding  (`prtb-s1s1s` was used in POST requests to create data)
- Notice: since a project name is added to the rolebinding 2 expected rolebinding are created 
  - each project has its own role binding dedicated to it 
![26head](https://user-images.githubusercontent.com/40282141/145655228-1af57dc6-e41d-487e-8b5e-40c44606571e.jpg)

**Closed** 2021-12-11 00:01 UTC
Labels: [zube]: QA Working, QA/need-info, feature/rbac
