### ISSUE TITLE
Audit Logs: Sorting after time breaks relative time

### ISSUE THREAD

**Issue by patschi** [rancher/rancher#10268] opened 2017-11-03 09:01 UTC
When sorting within audit logs by `TIME ASC` (`/admin/audit-logs?sortBy=created&sortOrder=asc`), the relative time seems to be wrong: it's always shown as "a day ago" even when some log entries were created couple of minutes ago. When sorting after `time` once again (`DESC`) everything's working fine again.

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v2.0.0-alpha9` Cattle: `v0.184.10` UI: `v2.0.11` |
|Access|`Disabled`|
|Orchestration|``|
|Route|`containers.index`|

**Comment by tfiduccia** [comment] 2017-11-06 19:28
This was fixed in our newest master build.  Fix will be out in the next alpha.  duplicate of #9656

**Closed by tfiduccia** 2017-11-06 19:28 UTC
