### ISSUE TITLE
Kubernetes only shows one of three nodes

### ISSUE THREAD

**Issue by gstorme** [rancher/rancher#8649] opened 2017-05-03 14:56 UTC
**Rancher Versions:**
Server: 1.5.8
healthcheck: 0.2.3
ipsec: 0.0.7
network-services: stuck on checking upgrades...
kubernetes: 1.5.4

**Docker Version:**
1.12.6 on agents, 17.03.1-ce on rancher host

**OS and where are the hosts located? (cloud, bare metal, etc):**
RancherOS 1.0.1 on Openstack

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
Single node Rancher + three agents

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Kubernetes

**Steps to Reproduce:**
Install RancherOS on 4 openstack machines
Install Rancher server on 1 host
Create Kubernetes environment
Add 3 RancherOS hosts to this environment

**Results:** 
Three nodes are registered in the k8s environment
Kubernetes nodes only show the first node

**rancher hosts:** 
ID        HOSTNAME                 STATE     CONTAINERS   IP                LABELS    DETAIL
1h1       rancheros-01.novalocal   active    33           185.115.216.108
1h2       rancheros-02.novalocal   active    12           185.115.216.114
1h3       rancheros-03.novalocal   active    14           185.115.216.117

**kubectl get nodes:**
NAME                     STATUS    AGE
rancheros-01.novalocal   Ready     1h

Hosts and containes overview in Rancher:

![screencapture-185-115-216-105-8080-env-1a7-infra-hosts-1493823359236](https://cloud.githubusercontent.com/assets/3859276/25666775/c260546c-3021-11e7-850d-5d57904478b5.png)

Nodes overview in Kubernetes dashboard:

![image](https://cloud.githubusercontent.com/assets/3859276/25666959/52c31a1c-3022-11e7-9bac-bdedaaef1156.png)

**Comment by gregster85** [comment] 2017-05-04 16:08
I have replicated this setup, but with 3 CoreOS hosts instead of RancherOS. No issue there.
All three hosts are visible in Kubernetes nodes.

Am I missing something why this doesn't work with RancherOS hosts?

**Comment by joshwget** [comment] 2017-05-05 03:26
Is this issue consistently reproducible with RancherOS? Or did you experience this just the once?

**Comment by gregster85** [comment] 2017-05-05 15:36
I destroyed and re-created the complete environment (including vm's), same result.
The Rancher server version now is v1.5.9.

**Comment by karamsahu** [comment] 2017-10-12 07:34
I was struggling with the same issue, and finally able to resolve this by changing the host registeration url from the default one to sothing else.  see screenshot below
![image](https://user-images.githubusercontent.com/9219378/31484244-29ed0ada-af4d-11e7-9c29-91c1ac0ff902.png)

Also, i stopped and removed all running containers by using this command `docker rm -f $(docker ps -a -q)` (Caution: this will remove all running containers)

And finally, re created the kubernetes evnironment, and added hosts one by one. Now, `kubectl get nodes` returns 2 nodes. 

Thanks

**Comment by superseb** [comment] 2017-10-12 07:53
Multiple things to check here:

* Is the host visible in Infrastructure -> Hosts and Active
* If it is, check `kubectl get nodes`
* If not present, check the `kubelet` container logs on the nodes that are not present in `kubectl get nodes` to get more info.

Please file a new issue if you are run into problems here, we can take a look. Closing this for now.

**Closed by superseb** 2017-10-12 07:53 UTC
Labels: area/kubernetes

**Comment by CayoM** [comment] 2017-11-29 12:46
Hi, im facing the same issue as described above.

The 2nd Host is visible in the Infrastructure of the Kubernetes Environment and all containers seems to be OK, since they are all green up and running, but it does not show up as a Node in Kubernetes.



Here the output of docker logs from the kubelet container. This log output keeps looping:

rancher/k8s:v1.8.3-rancher2
`I1129 12:30:00.703553   52026 kubelet_node_status.go:280] Setting node annotation to enable volume controller attach/detach
I1129 12:30:00.703611   52026 rancher.go:683] ExternalID [devnode01.test.de]
I1129 12:30:00.703629   52026 rancher.go:690] InstanceID [devnode01.test.de]
I1129 12:30:00.725974   52026 rancher.go:690] InstanceID [devnode01.test.de]
I1129 12:30:00.742965   52026 rancher.go:690] InstanceID [devnode01.test.de]
I1129 12:30:00.760166   52026 kubelet_node_status.go:336] Adding node label from cloud provider: beta.kubernetes.io/instance-type=rancher
I1129 12:30:00.760234   52026 kubelet_node_status.go:347] Adding node label from cloud provider: failure-domain.beta.kubernetes.io/zone=FailureDomain1
I1129 12:30:00.760254   52026 kubelet_node_status.go:351] Adding node label from cloud provider: failure-domain.beta.kubernetes.io/region=Region1
W1129 12:30:00.834790   52026 helpers.go:847] eviction manager: no observation found for eviction signal allocatableNodeFs.available`


Rancher Agent Version: rancher/agent:v1.2.7
Rancher Server Version: docker.io/rancher/server:latest

**Comment by superseb** [comment] 2017-12-20 21:49
@CayoM I don't see anything wrong here, as the node gets found by the cloudprovider. Can you file a new issue using the issue template and include the full kubelet log and output of `kubectl get nodes`?
