### ISSUE TITLE
Better validation on Custom Registry entry form

### ISSUE THREAD

**Issue by gesrat-cisco** [rancher/rancher#2971] opened 2015-12-10 00:50 UTC
Please add data entry validation to the Custom Registry entry form.  If mistakenly entry a URL scheme as well as a path prefix - eg http://quay.mycorp.com vs quay.mycorp.com,  you dont get a data entry error, and if you try and launch a container that references this registry - it just fails with an unhelpful error message

FYI - it may be that if you try and launch any container with an invalid image path that it just fails with an unhelpful error message

**Comment by deniseschannon** [comment] 2015-12-11 05:04
Duplicate of https://github.com/rancher/rancher/issues/300

**Closed by deniseschannon** 2015-12-11 05:04 UTC
