### ISSUE TITLE
cluster-scoped-gc hangs if project namespace is removed before project level scoped crs

### ISSUE THREAD

**Issue by cloudnautique** [rancher/rancher#19021] opened 2019-03-19 19:08 UTC
In a heavily loaded cluster, the etcd db keyspace filled up and no writes could happen to the cluster. This was mid-delete of clusters. It appears that the project namespaces were deleted before the project level CustomResources were deleted.

```
 # etcdctl --endpoints=${ETCDCTL_ENDPOINT} get --prefix / --keys-only |grep p-t5kpk
/registry/management.cattle.io/projectalertgroups/p-t5kpk/projectalert-workload-alert
/registry/management.cattle.io/projectalertrules/p-t5kpk/less-than-half-workload-available
/registry/management.cattle.io/projectalertrules/p-t5kpk/memory-close-to-resource-limited
/registry/management.cattle.io/projectroletemplatebindings/p-t5kpk/creator-project-owner
/registry/management.cattle.io/projectroletemplatebindings/p-t5kpk/u-fxy6ricq7e-member
```
in rancher logs we see:
```
2019/03/19 17:53:02 [ERROR] ClusterController c-jxcf7 [cluster-scoped-gc] failed with : namespaces "p-fdkwf" not found```

**Comment by rmweir** [comment] 2019-09-05 01:01
I have tried reproducing this issue the following ways:

1. Create cluster on master with project, install app, delete project namespace, delete cluster 
2. Create cluster on v2.2.0 with project, install app, delete project namespace, delete cluster 
3. Create cluster on v2.2.0 with project, add users, install app delete cluster
4. Create cluster on v2.2.0 with project, add users, install app, add alerts, delete cluster 
5. Create cluster on v2.2.0 with project, add users/app/alerts. Fill up etcd with arbitrary records. 

In each situation I was able to delete without cluster-scoped-gc hanging. Worth noting: when etcd is filled I was unable to add additional data and I was unable to get data due to `Error:  context deadline exceeded`

**Comment by rmweir** [comment] 2019-09-05 16:31
@cjellick has requested that this is postponed

**Comment by cjellick** [comment] 2019-09-10 15:41
Assigning to @drpebcak to see if this repros after the v2.3 scale testing. If it doesn't we will close this. If it does, will investigate further.

**Comment by deniseschannon** [comment] 2020-03-27 23:13
This was never seen as part of scale testing for 2.4 so going to close it.

**Closed by deniseschannon** 2020-03-27 23:13 UTC
Labels: [zube]: Team Blue Backlog, area/scalability, kind/bug
