### ISSUE TITLE
[BUG] Rancher v2.6.12 Failed to get GlobalRoleBinding for 'globaladmin-user-pn62n': %!w(<nil>)

### ISSUE THREAD

**Issue by oguzhansrky** [rancher/rancher#41500] opened 2023-05-10 23:44 UTC
**Rancher Server Setup**
- Rancher version: v2.6.12 
- Installation option (Docker install/Helm Chart): Docker install
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): RKE2
- Proxy/Cert Details:

**Information about the Cluster**
- Kubernetes version: v1.24.8+k3s1
- Cluster Type (Local/Downstream): Local
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider):

**User Information**
- What is the role of the user logged in? (Admin/Cluster Owner/Cluster Member/Project Owner/Project Member/Custom)
  - If custom, define the set of permissions: Admin

**Describe the bug**
Failed to get GlobalRoleBinding for 'globaladmin-user-pn62n': %!w(<nil>)

**To Reproduce**

**Result**

**Expected Result**

**Screenshots**
![image](https://github.com/rancher/rancher/assets/52497227/fba61107-863e-4b03-9989-a4f8647acbb5)

**Additional context**
Greetings, I'm uninstalling rancher on docker. local kubernetes gives this error for a while. I think it's a bug because I didn't do anything. Also, this version 2, which I am currently using, affects my live environment.

**Comment by wontfixthis** [comment] 2023-05-12 07:48
Same here.

Rancher 2.6.12, v1.20.15+rke2r2

**Comment by dasarinaidu** [comment] 2023-05-15 19:37
Duplicate of : https://github.com/rancher/rancher/issues/41465

**Closed** 2023-05-16 15:32 UTC
Labels: kind/bug
