### ISSUE TITLE
Backport:Monitoring Query fails periodically.

### ISSUE THREAD

**Issue by loganhz** [rancher/rancher#19600] opened 2019-04-14 12:24 UTC
https://github.com/rancher/rancher/issues/19564

**Comment by alena1108** [comment] 2019-05-07 18:28
Can be tested with rc7

**Comment by davidnuzik** [comment] 2019-05-09 16:23
Version: v2.2.3-rc7

I still observe that when we load the cluster dashboard page we make 2 query requests to `clustermonitorgraphs` but now, we no longer get 503 errors. The queries only start when monitoring is ready. I have tested this several times in order too try to reproduce the issue but no longer can. I can also disable monitoring, watch this page, and still avoid 503 or other errors upon the query. I can re-enable again, still watching the dashboard page and not observe and HTTP errors.

Note, there are more details around this here: #19564 but the core issue reported is resolved. We do not get HTTP 503 with `clustermonitorgraphs` any longer based on my tests.

It's possible the issue may stay open as we might test with a many-node cluster later.

**Comment by davidnuzik** [comment] 2019-05-10 23:32
Reopened. There is a question in the v2.3 issue asking about how we still see 2 query requests upon initial load of the cluster dashboard.

**Comment by loganhz** [comment] 2019-05-11 01:55
@davidnuzik thanks 

It should be only one request. Submited a PR to fix it

**Comment by davidnuzik** [comment] 2019-05-14 22:08
Thanks Logan.

Version: v2.2.4-rc1 

I can now confirm upon initial load of the page we only see one query rather than two.
I was never successful in reproducing the issue. We believe this is because we need a 500-1000 node cluster to do this. (The 503 errors were never observed).

Since I can confirm that we have removed the duplicate query (and smoke tested monitoring and found it to be working fine) I am going to close this v2.2.4 issue.
As for the originating issue in master (v2.3) I will _leave this open_ as in that version we might try to test with a large 500-1000 node cluster at some point. This is yet to be determined.

**Closed by davidnuzik** 2019-05-14 22:08 UTC
Labels: [zube]: To Test, area/monitoring, area/ui, kind/bug-qa, status/ready-for-review, status/reopened, status/resolved, status/to-test, team/cn
