### ISSUE TITLE
Importing a AKS cluster with complicated configuration is not editable from Rancher

### ISSUE THREAD

**Issue by thedadams** [rancher/rancher#37681] opened 2022-05-11 00:25 UTC
**Rancher Server Setup**
- Rancher version: v2.6-head
- Installation option (Docker install/Helm Chart): Any
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc):
- Proxy/Cert Details: Any

**Information about the Cluster**
- Kubernetes version: Any
- Cluster Type (Local/Downstream): Downstream
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider): AKS

**Describe the bug**
If an AKS cluster is created outside of Rancher with some complicated configuration (specifically `--outbound-type userDefinedRouting`), then importing it into Rancher may work but a user would not be able to make any changes to the AKS cluster through Rancher.

**To Reproduce**
1. Create an AKS cluster with `aksctl` passing some non-standard configuration like `--outbound-type userDefinedRouting`.
2. Import the cluster into Rancher
3. Add a node pool to the cluster from Rancher.

**Result**
An error will occur related to changing a field that cannot be changed.

**Expected Result**
The node pool should successfully be added.

**Additional context**
After some discussion on this issue, it seems that since the AKS cluster configuration through the CLI is so complicated, that the best course of action is that `aks-operator` should pull the cluster state from AKS and update the current cluster state with the configuration `aks-operator` and Rancher know about. For example, `outbound-type` is not part of the configuration that Rancher is aware of, so that will not change when the cluster is update from Rancher.

SURE-4373

**Comment by annablender** [comment] 2022-05-26 20:28
The root cause of this issue is when rancher imports an AKS cluster, it creates a new v3 mgmt cluster object instead of pulling in already existing fields in Azure. Rancher only manages the fields that it knows about so cluster config fields created using `aksctl` cannot be updated by Rancher. That's why creating a new node pool has no effect. The fix will be to add logic [here](https://github.com/rancher/aks-operator/blob/a32c2bf0c3254301d1257345d4db786fef49162e/pkg/aks/create.go#L151) in the `aks-operator` to retrieve the `ManagedCluster` object from Azure if it exists and if not, create a new one.

**Comment by annablender** [comment] 2022-06-07 21:18
I was not able to reproduce this issue on `rancher-v2.6` head.

Repro steps
* Create an AKS cluster using the Azure CLI using the [Azure docs](https://docs.microsoft.com/en-us/azure/aks/limit-egress-traffic#restrict-egress-traffic-using-azure-firewall) for creating a cluster with custom UserDefinedRouting (UDR) and a firewall

CLI command
```
az aks create -g $RG -n $AKSNAME -l $LOC   --node-count 3 --generate-ssh-keys   --network-plugin $PLUGIN   --outbound-type userDefinedRouting   --service-cidr 10.41.0.0/16   --dns-service-ip 10.41.0.10   --docker-bridge-address 172.17.0.1/16   --vnet-subnet-id $SUBNETID   --service-principal $APPID   --client-secret $PASSWORD   --api-server-authorized-ip-ranges $FWPUBLIC_IP
```

* Add firewall rules to allow access to docker, the rancher server, and the Kubernetes API/443

```
az network firewall network-rule create -g $RG -f $FWNAME --collection-name 'aksfwnr' -n 'cfdocker' --protocols 'TCP' --source-addresses '*' --destination-fqdns 'production.cloudflare.docker.com' --destination-ports 443
az network firewall network-rule create -g $RG -f $FWNAME --collection-name 'aksfwnr' -n 'dockerio' --protocols 'TCP' --source-addresses '*' --destination-fqdns 'registry-1.docker.io' --destination-ports 443
az network firewall network-rule create -g $RG -f $FWNAME --collection-name 'aksfwnr' -n 'ngrok' --protocols 'TCP' --source-addresses '*' --destination-fqdns '<rancher server>' --destination-ports 443 # rancher server
az network firewall network-rule create -g $RG -f $FWNAME --collection-name 'aksfwnr' -n 'kubeapi' --protocols 'TCP' --source-addresses '*' --destination-addresses "<Kubernetes API service IP>" --destination-ports 443 # k8s api server
```

* Create a firewall rule to allow all inbound internet traffic

```
```

* Import the AKS cluster into Rancher
* Create a new node pool and save config

![image](https://user-images.githubusercontent.com/12955547/172480988-b13c81d6-c6d2-429d-80be-f515d0de1d84.png)

![image](https://user-images.githubusercontent.com/12955547/172481072-f5eabddc-77c1-473b-ab8f-e5c056e0d38e.png)

![image](https://user-images.githubusercontent.com/12955547/172481095-cb35a235-38b5-4b2c-9bd5-29b794db807a.png)

![image](https://user-images.githubusercontent.com/12955547/172481143-24a5cbc1-0c6d-4590-8dcf-e0625dbd69c2.png)

I noticed that while Azure did not return an error about a non-modifiable field for `outboundType` or `vnetSubnetId`, once imported into Rancher my authorized IP address range was overwritten with a null value.

AKS cluster not yet imported into Rancher
<img width="490" alt="image" src="https://user-images.githubusercontent.com/12955547/172483978-22f4dff3-7a29-40d7-bd59-ecc8aed46be9.png">

After import into Rancher...
<img width="471" alt="image" src="https://user-images.githubusercontent.com/12955547/172484068-e1e7344e-b086-4050-afe3-54769cbd6972.png">

This demonstrates the root cause of this issue, that Rancher tries to empty/null out configuration fields in Azure that it doesn't know about on cluster creation. Rancher should pull the value for this field on creation, instead of overwriting it in Azure. This makes me believe [the suggested fix](https://github.com/rancher/rancher/issues/37681#issuecomment-1138998234) is still needed.

**Comment by annablender** [comment] 2022-06-09 19:33
Discovered a new bug while testing https://github.com/rancher/rancher/issues/37955.

**Comment by annablender** [comment] 2022-06-10 23:08
After a good amount of code diving for this fix, there's 3 separate things going on here that are contributing to the root cause of this bug.

1. The aks operator was not properly checking for the authorized IP range field (fixed in PR [#59](https://github.com/rancher/aks-operator/pull/59)
2.

**Comment by Josh-Diamond** [comment] 2022-06-16 23:24
Ticket #37681 - Test Results [pt. 1]

With Docker on a single-node instance:

Reproduced on rancher `v2.6.5`:
1. Create an AKS cluster using the Azure CLI using the [Azure docs](https://docs.microsoft.com/en-us/azure/aks/limit-egress-traffic#restrict-egress-traffic-using-azure-firewall) for creating a cluster with custom UserDefinedRouting (UDR) and a firewall EXCEPT update FWPUBLIC_IP to 0.0.0.0/0 
2. Fresh install of rancher `v2.6.5`
3. Import aks cluster created in step 1 into rancher via UI
4. `Edit Config` and add a node pool
5. Reproduced - authorized IP address range was overwritten with a null value in Azure portal and on the `authorizedIpAddressRange` field on the mgmt cluster object

Screenshot:

`Step 4`
<img width="1238" alt="Screen Shot 2022-06-16 at 4 22 46 PM" src="https://user-images.githubusercontent.com/46494969/174194041-6f7f04a5-35f8-4e50-80ac-d4ec2ddb6678.png">

`Step 5`
<img width="295" alt="authorizedIPRangenull" src="https://user-images.githubusercontent.com/46494969/174193123-0dd1c97b-da31-4aad-889d-7bedf26d3f79.png">

**Comment by annablender** [comment] 2022-06-24 21:56
## Testing template

#### Root cause

When creating or updating an AKS cluster, the aks operator does not check to see if a `managedCluster` object already exists and creates a new `managedCluster` object with only fields it knows about. This results in some fields associated with an existing cluster in Azure being overwritten on the `CreateOrUpdate` API call in `create.go`. When the aks operator does a sync and builds a config based on the state of the upstream AKS cluster, there is also a bug where authorized IP ranges configured in Azure will get overwritten with a nil value because rancher doesn't dereference the *[]string properly. Thus, the authorized IP range won't show up in the UI.
 
#### What was fixed, or what changes have occurred

I've refactored `create.go` in the aks operator to separate out the create and update operations. This is for improving the flow of the code and increasing readability, and because the aks operator only needs to pull and merge in data from the upstream AKS cluster when a provisioned or imported cluster is updated. When a cluster is created, it only needs to create a new `ManagedCluster` object if it does not already exist.

* Creating a cluster: When creating an AKS cluster, the aks operator pulls the cluster state and if it does not exist, creates a new `ManagedCluster` object with fields from the config spec.

* Updating a cluster: When updating an AKS cluster, the aks operator pulls the cluster state into a `ManagedCluster` object, then updates that object with fields from the config spec that were set/updated by Rancher or user-defined in Rancher. This approach enables us to only care about the fields that Rancher manages instead of having to maintain the logic every time that Azure adds a new field to their configuration. This also does not break the principal from the [KEv2 docs](https://github.com/rancher/rancher/wiki/Kontainer-Engine-v2:-The-new-way-rancher-integrates-with-cloud-providers#how-does-rancher-integrate-with-the-kev2-operators) of having non nil flags for managed fields in Rancher and nil flags for non-managed fields in Rancher. This piece just merges in the upstream state before an update to AKS so nil flags in Rancher don't overwrite fields in upstream (KEv2 thing: when I say upstream I mean the downstream cluster). 

* Authorized IP range bug: When building the upstream AKS cluster spec, the aks operator will check the upstream state and set authorized IP ranges correctly.

* Added missing func comments
 
#### Areas or cases that should be tested

This issue requires a lot of testing because it touches all parts of provisioning an AKS cluster. Here's the basic test plan I used to smoke test my changes.

Test plan
1. Provisioned (via the Rancher UI kubernetes v1.23.5)
	a. 1 node AKS cluster
	b. 1 node AKS. Update auth IP range to 0.0.0.0/0 in Azure. Check that no config was overwritten in AKS/change was propogated as expected
	c. 1 node AKS cluster. Update HTTP Application Routing in rancher UI. Check that no config was overwritten in AKS
2. Import
	a. 3 node AKS cluster created via CLI with UDR and firewall. Check that no config was overwritten in AKS (agent pool, network). Update kubernetes version for the cluster configuration
	b. 3 node AKS cluster created via Azure portal
 
#### What areas could experience regressions ?

I can think of a regression happening if,

1) New fields are added to the list of fields that Rancher manages (CRD types.go) and `UpdateCluster` is not updated to incorporate those
2) What constitutes an 'update to AKS' changes
 
#### Are the repro steps accurate/minimal ?

Yes.

**Comment by annablender** [comment] 2022-07-07 13:43
This appears to be a minor bug with test 1C

`Veri-FAILED 1C - Cluster fails to update with an error regarding the same name value being assigned, expected unique values`

I'll put in a PR to fix this when I can get to it. Thank you @Josh-Diamond !

**Comment by annablender** [comment] 2022-07-11 21:42
@Josh-Diamond This is ready for retest. Make sure you are running the aks operator chart version `rancher-aks-operator:100.0.5+up1.0.6.`

**Comment by Josh-Diamond** [comment] 2022-07-11 22:59
Ticket #37681 - Test Results [pt. 3]

With Docker on a single-node instance:

Verified on rancher `v2.6-bda0897a42ac77431383eb4a4bcd0454de056b98-head`:
1. Fresh install of rancher v2.6-head
2. From UI, provision a downstream AKS cluster with k8s v1.23.5, single-node with all-roles
3. Verified 1A - Cluster successfully provisions
4. In Azure portal, update auth IP range to 0.0.0.0/0
5. Verified 1B - Cluster update successful, no config was overwritten in AKS and change was propagated as expected
6. From Rancher UI, update cluster to enable HTTP Application Routing
7. Verified 1C - Cluster update successful, no config was overwritten in AKS and change was propagated as expected

Screenshot:

`Step 7 - Azure portal`
<img width="444" alt="Screen Shot 2022-07-11 at 3 57 28 PM" src="https://user-images.githubusercontent.com/46494969/178372679-461f3822-e8b8-422a-9879-19d3fc17ff50.png">

`Step 7 - Cluster Management`
<img width="1354" alt="Screen Shot 2022-07-11 at 3 57 40 PM" src="https://user-images.githubusercontent.com/46494969/178372698-24a45086-7b92-45c1-b43d-eb1c56416fa2.png">

**Closed by Josh-Diamond** 2022-07-11 22:59 UTC
Labels: internal, area/aks, [zube]: QA Working, QA/S, feature/kev2, team/area2
