### ISSUE TITLE
Clone Webhook Issue

### ISSUE THREAD

**Issue by wmbutler** [rancher/rancher#8320] opened 2017-03-28 03:46 UTC
**Rancher Versions:**
Server: 1.5.3
healthcheck: v0.2.3
ipsec: rancher/net:holder
network-services: rancher/metadata:v0.8.11 
scheduler:
kubernetes (if applicable):

**Docker Version:** 1.12.6

**OS and where are the hosts located? (cloud, bare metal, etc):** AWS

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)** Single Node MySQL

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)** Cattle

**Steps to Reproduce:** Clone a Webhook

**Results:** Cloned item does not match original 

Scale a Service vs. Upgrade a service

![screen shot 2017-03-27 at 11 38 06 pm](https://cloud.githubusercontent.com/assets/1254810/24388234/4a4fb108-1347-11e7-992a-de0d37fa1893.png)

![screen shot 2017-03-27 at 11 38 15 pm](https://cloud.githubusercontent.com/assets/1254810/24388233/4a4b3fd8-1347-11e7-8c00-aaad33dde6ac.png)

**Comment by tfiduccia** [comment] 2017-03-28 18:40
Duplicate of #7996 - Clone always reverts back to Kind = Scale a service.

**Closed by tfiduccia** 2017-03-28 18:40 UTC
