### ISSUE TITLE
Upgrade delete service links not saving 

### ISSUE THREAD

**Issue by bacheson** [rancher/rancher#2723] opened 2015-11-18 19:56 UTC
1) upgrade a service
2) delete service link
3) click upgrade

the link will still exist

**Comment by deniseschannon** [comment] 2015-11-21 06:40
In v0.46.0, I was unable to reproduce, but I am also testing with the new UI. 

Here are some more detailed steps I performed.

Service 1 with link to Service2.
In UI, select Upgrade option to a different image (leaving link in tact). 
Finish Upgrade
Edit service 1 to delete the link to service 2. Save the edit.
In UI, select Upgrade option. Link to service 2 is NOT showing up.

**Comment by alex88** [comment] 2015-11-23 23:19
Just tried to:

1) upgrade service
2) add link during service upgrade
3) actually upgrade

link not present

**Comment by deniseschannon** [comment] 2015-11-24 00:57
What rancher version are you running? How are you upgrading (UI or rancher-compose)?

**Comment by alex88** [comment] 2015-11-24 01:07
Upgrading via UI, rancher 0.46.0

**Comment by deniseschannon** [comment] 2015-11-24 17:46
I'm on our latest rc (doing testing) and still have been unable to reproduce. 

Link is present after I added during service upgrade. 

Do you have multiple environments? I'm wondering if you are hitting https://github.com/rancher/rancher/issues/1389

**Comment by deniseschannon** [comment] 2015-12-31 03:58
@alex88 As I have been unable to reproduce (after multiple attempts), I'm going to assume you were hitting #1389 where sometimes links aren't present if you have multiple environments. Closing in favor of that issue.

**Closed by deniseschannon** 2015-12-31 03:58 UTC
Labels: kind/question
