### ISSUE TITLE
Live migration of containers across hosts

### ISSUE THREAD

**Issue by sjkeerthi** [rancher/rancher#1293] opened 2015-06-19 17:57 UTC
Hi All

Once I install the RancherOS on my two boxes and will manage via Rancher Agent is there a possible way to migrate my container from one RancherOs to another one from UI just by Drag n Drop from the Rancher UI. If this is not possible I hope we need this feature to bring it up.

Thanks in Advance,
Keerthi

**Comment by vincent99** [comment] 2015-06-19 18:36
This is not currently possible because the storage volumes would have to be migrated with the container, along with any other containers that depend on those same volumes, recursively.  This is roughly what [Flocker](https://clusterhq.com/) does.

It may be possible in the future once we have a better story around volume management in Rancher.

**Comment by sjkeerthi** [comment] 2015-06-19 19:12
Is there a logical way round of for example mount one of the NFS volume to all the docker and can point /var/lib/docker and then will it work?

**Comment by vincent99** [comment] 2015-06-19 19:20
I'm not sure if docker will work with multiple separate hosts sharing a `/var/lib/docker`.. But you could certainly use a NFS mount on every host and bind individual volumes to directories in it.  There is still no live-migration action to do the actual move, but you could use the Clone action on a container and change the host it will be put on to create a new container on the new host, then delete the old one on the old host.

**Comment by lavvy** [comment] 2015-08-01 15:04
This feature is no doubt the only thing holding us back to virtualization. Rancher has never ceased to amaze us. We actually had been looking for a way to safeguard our volume, and that's why I am still stuck with virtualization with all the overhead.
But I saw rancher-volume project it has all needed , like create,save and restore volume.
But my question is , I have not seen it in the web manager yet ? 
Or are they planning it for a specific release ? 
Secondly, if save and restore has been achieved for rancher volume, then live migration is just in already.
So folks, does this feature have a timeline ? We want get out of virtualization

**Comment by thaJeztah** [comment] 2015-08-01 15:14
For full live migration of a container, I think docker has to add support for this first. There's work in progress for this, but I don't think there's an ETA yet. See for example https://github.com/docker/docker/pull/13602, but I'm not sure if this is currently held back because of the introduction of RunC (https://github.com/opencontainers/runc)

**Comment by lavvy** [comment] 2015-08-01 15:32
Ok. But how can one do volume snapshot , save and restore in rancher web manager

**Comment by deniseschannon** [comment] 2015-08-04 16:48
@lavvy Currently, it's not available in Rancher. You can follow this issue https://github.com/rancher/rancher/issues/29, which will be incorporating the rancher-volume project when it's completed.

**Comment by willseward** [comment] 2016-01-06 21:41
Now that convoy-gluster is available, would this be possible?

**Comment by deniseschannon** [comment] 2016-02-04 19:24
Duplicate of #438

**Closed by deniseschannon** 2016-02-04 19:24 UTC
Labels: area/container, area/storage, area/ui, kind/enhancement
