### ISSUE TITLE
v0.42.0 Multiple ports not exposed correctly

### ISSUE THREAD

**Issue by c58** [rancher/rancher#2471] opened 2015-10-29 05:46 UTC
Hello! 
I have a problem with multiple ports exposing. If you make a container with multiple mapped ports (any image, all from Rancher UI), on start/restart of the container only one port mapped (exists in iptables of a host). When container started with incorrectly mapped ports, if you change ports mapping of any started container of the host (with Rancher UI), then all ports of each container will be mapped correctly.

Multiple ports mapping of a container must be mapped correctly on each start/restart of the container.

Rancher v0.42.0
Cattle v0.102.0
Rancher Compose v0.4.3

**UPDATE:** 
Same problem with latest rancher server (v0.43.1)

**Comment by deniseschannon** [comment] 2015-10-30 07:09
This sounds like a duplicate of this issue; https://github.com/rancher/rancher/issues/1898

**Closed by deniseschannon** 2015-10-30 07:09 UTC
