### ISSUE TITLE
Support Rancher Monitoring feature on ARM64

### ISSUE THREAD

**Issue by kerven88** [rancher/rancher#28342] opened 2020-08-11 06:50 UTC
**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI):   rancher/rancher:v2.4.5-linux-arm64
- Installation option (single install/HA):    single install

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported):  Custom
- Kubernetes version (use `kubectl version`):   v1.18.6
- Docker version (use `docker version`):   v19.3.12
- OS version:   Linux 4.18.0-80.7.2.el7.aarch64

I'm currently starting cluster monitoring on arm64, but the container fails to start, and from the startup log it's because the container image is the amd version.

When does rancher monitoring support arm64?

**Comment by cbron** [comment] 2021-08-24 16:44
Rancher in general does not support arm64 at this time. Duplicate of: https://github.com/rancher/rancher/issues/18891

**Closed by cbron** 2021-08-24 16:44 UTC
