### ISSUE TITLE
Host hung in invalid state...

### ISSUE THREAD

**Issue by eebjr** [rancher/rancher#2916] opened 2015-12-04 15:35 UTC
while adding a host, via the v47 api, I had a host end up in the "Active" state in UI, but also still waiting to really go active. In the API view, the machines entry is present, but there is no host entry. 

here's a screen capture of the UI: 
![not_really_active](https://cloud.githubusercontent.com/assets/7059223/11592931/0e86cee0-9a67-11e5-87b8-1970f71b1e16.png)

I have another stack filling my server logs at the moment, so I'll try to reproduce at a later date and capture the logs. But I don't see any errors related to the host named hereford in the logs. The last few logs for hereford is the following: (can't show them all because my openstack username and password are printed in plain text :-( )

time="2015-12-03T22:37:17Z" level=info msg="Rancher-agent for machine started" containerId="1ad3114a9cb5215ecab451a2b746001c73121ff1ac51
b74d1ecad2efdbbaf41c" machineExternalId="ebade79c-45e3-4571-932c-718aab2adac5" resourceId=1ph6
time="2015-12-03T22:37:17Z" level=info msg="Creating and uploading extracted machine config" resourceId=1ph6
time="2015-12-03T22:37:17Z" level=info msg="Machine config file created and encoded." destFile="/var/lib/cattle/machine/ebade79c-45e3-45
71-932c-718aab2adac5/hereford.tar.gz" resourceId=1ph6

**Comment by deniseschannon** [comment] 2015-12-08 18:17
if you are using the API, did you make sure to set up the host registration before launching a host?

Also, I'm not sure if openstack is working with docker-machine.

**Comment by cjellick** [comment] 2015-12-08 18:21
@eebjr My guess is that the rancher-agent running on the newly creeated machine cannot reach the rancher-server API. Can you get onto the machine and verify that the rancher-server can be reached from there?

Also, the rancher-agent container should at least be attempting to run on that machine at this point and should have some logs indicating why it has not yet checked in with the rancher-server. Can you provide those logs?

**Comment by eebjr** [comment] 2015-12-08 20:40
I deleted this one and moved on so I don't have logs. I've been creating VM instances in Openstack for a while now, using the API so that's not the problem. I thought this may be a problem with the new UI, so I let  you know. Again...moving on now...

**Comment by deniseschannon** [comment] 2015-12-30 23:29
@eebjr If you hit this issue again, please re-open and provide the logs requested by @cjellick. We are unable to reproduce and would need some information.

**Closed by deniseschannon** 2015-12-30 23:29 UTC
Labels: kind/question
