### ISSUE TITLE
removed host can't be add to kubernetes environment once again

### ISSUE THREAD

**Issue by logicigam** [rancher/rancher#4639] opened 2016-05-01 10:07 UTC
I'm testing the cluster HA with remove one of the host,but after I do that ,I can't add the host I just removed to the environment once again--after I execute the run agent command,there is nothing pop up onto the host page.I check out the container logs of the agent running on that host and found some error that maybe related to this issue:
`
Using image rancher/agent:v1.0.1
INFO: Downloading agent http://172.17.32.16:5000/v1/configcontent/configscripts
{"id":"72f0209b-ed91-4f6c-92dc-6f3eefba6f1f","type":"error","links":{},"actions":{},"status":401,"code":"Unauthorized","message":"Unauthorized","detail":null}
gzip: stdin: not in gzip format
tar: Child returned status 1
tar: Error is not recoverable: exiting now
`
finally,I try to delete the /var/lib/rancher dir and everything just magically work,the host show up once again.but I think it's not so good to let user manually remove that dir before re-add a removed host.

docker 1.9.1

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v1.0.1` Cattle: `v0.159.7` UI: `v1.0.5` |
|Access|`localauth` `admin`|
|Route|`authenticated.project.help`|

**Comment by alena1108** [comment] 2016-05-02 16:41
@deniseschannon what are our official steps for re-adding the same host to Rancher? I do believe we require /var/lib/rancher directory to be cleaned up

**Comment by deniseschannon** [comment] 2016-05-02 18:51
We shouldn't require clearing `/var/lib/rancher` unless you are using a cloned VM.

**Comment by logicigam** [comment] 2016-05-05 04:36
all my hosts are created one by one,not cloned VM

**Comment by ibuildthecloud** [comment] 2016-05-19 23:22
@deniseschannon It's seems spotty whether we need `/var/lib/rancher` to be deleted or not.  It's 50/50 for me.  I think somebody should look into this.

**Comment by deniseschannon** [comment] 2016-05-20 05:13
@ibuildthecloud Agreed. This is some type of regression as it seems as if it's more likely that we need to wipe out `/var/lib/rancher` than before.

**Comment by deniseschannon** [comment] 2016-10-15 02:55
@StrongMonkey Another one of the issues where we should try and reproduce now using our new go agent. 

@logicigam We have completely refactored our agent code in 1.2.0 so if we cannot reproduce, we will close the issue and if you see this issue in 1.2.0, then please open a new issue.

**Comment by StrongMonkey** [comment] 2016-10-19 22:19
I don't see the problem happening with rancher/server:v1.2.0-pre4-rc4. After adding a host, remove that one, I am able to re-add it again. @deniseschannon

**Closed by StrongMonkey** 2016-10-19 22:19 UTC
Labels: area/agent, kind/bug
