### ISSUE TITLE
[Istio] Upon disabling Istio there are many warnings in the Rancher logs

### ISSUE THREAD

**Issue by davidnuzik** [rancher/rancher#20959] opened 2019-06-18 20:53 UTC
Version: v2.3.0-alpha4

**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
- Enable Istio
- Wait a bit (Istio should be fully up and ready). Disable Istio. Watch logs.

**Result:**
There will be many errors in the rancher logs indicating SchemaError (Very small snippet below)
```
[rancher-8495c9bc8f-v9kjd] [kube] 2019/06/18 20:43:42 warning: failed to load schema: SchemaError(io.k8s.api.apps.v1.DeploymentCondition): invalid object doesn't have additional properties                                                                                 
[rancher-8495c9bc8f-v9kjd] [kube] 2019/06/18 20:43:42 Starting delete for "tcpconnectionsclosed" metric 
[rancher-8495c9bc8f-v9kjd] [kube] 2019/06/18 20:43:42 warning: failed to load schema: SchemaError(io.k8s.api.apps.v1.DeploymentCondition): invalid object doesn't have additional properties                                                                                 
[rancher-8495c9bc8f-v9kjd] [kube] 2019/06/18 20:43:42 Starting delete for "requestcount" metric 
[rancher-8495c9bc8f-v9kjd] [kube] 2019/06/18 20:43:42 warning: failed to load schema: SchemaError(io.k8s.api.apps.v1.DeploymentCondition): invalid object doesn't have additional properties                                                                                 
[rancher-8495c9bc8f-v9kjd] [kube] 2019/06/18 20:43:42 Starting delete for "requestsize" metric 
[rancher-8495c9bc8f-v9kjd] [kube] 2019/06/18 20:43:43 warning: failed to load schema: SchemaError(io.k8s.api.apps.v1.DeploymentCondition): invalid object doesn't have additional properties                                                                                 
[rancher-8495c9bc8f-v9kjd] [kube] 2019/06/18 20:43:43 Starting delete for "responsesize" metric 
```

There are also suppressed panics (another small snippet below, see the last line here):

```
[rancher-8495c9bc8f-v9kjd] [tiller] 2019/06/18 20:43:45 error: object not found, skipping delete 
[rancher-8495c9bc8f-v9kjd] [tiller] 2019/06/18 20:43:45 executing 58 post-delete hooks for cluster-istio 
[rancher-8495c9bc8f-v9kjd] [kube] 2019/06/18 20:43:45 building resources from manifest 
[rancher-8495c9bc8f-v9kjd] [kube] 2019/06/18 20:43:45 warning: failed to load schema: SchemaError(io.k8s.api.apps.v1.DeploymentCondition): invalid object doesn't have additional properties 
[rancher-8495c9bc8f-v9kjd] [kube] 2019/06/18 20:43:45 creating 1 resource(s) 
[rancher-8495c9bc8f-v9kjd] [kube] 2019/06/18 20:43:45 warning: failed to load schema: SchemaError(io.k8s.api.apps.v1.DeploymentCondition): invalid object doesn't have additional properties 
[rancher-8495c9bc8f-v9kjd] [kube] 2019/06/18 20:43:46 Watching for changes to ClusterRole istio-cleanup-secrets-istio-system with timeout of 5m0s 
[rancher-8495c9bc8f-v9kjd] [kube] 2019/06/18 20:43:46 Add/Modify event for istio-cleanup-secrets-istio-system: ADDED 
[rancher-8495c9bc8f-v9kjd] 2019-06-18 20:43:46.031958 I | suppressing panic for copyResponse error in test; copy error: context canceled
```

**Other details that may be helpful:**
Full logs from kubetail (apologies for the chars in front of and behind log lines. kubetail does this to colorize logs; you can cat the file to see the colors in most terminals and run `reset` to reset the terminal)
[HA_kubetail_logs.txt](https://github.com/rancher/rancher/files/3303379/HA_kubetail_logs.txt)

**Environment information**
v2.3.0-alpha4 (HA Setup, but any configuration has the error)

**Comment by davidnuzik** [comment] 2019-06-18 20:54
@loganhz could you assign out accordingly? I'm not certain who is best to look at this. We just were not sure if there is reason for concern here or not and would appreciate if someone could review the logs to see if we have any actual issues to worry about here.

From a UI-perspective I could not identify this causing any functional issues. Istio passed QA checks in this build.

**Comment by guangbochen** [comment] 2019-06-25 00:50
can't reproduce either with `v2.3.0-alpha4 - istio 1.5.0` or `v2.3.0-alpha5 - istio 1.2.0` using RKE cluster, can you help to validate if `v2.3.0-alpha5 ` has the same issue in your cluster, and what type of cluster are we using e.g, GKE?

**Comment by davidnuzik** [comment] 2019-06-26 22:39
@guangbochen I reproduce with v2.3.0-alpha4 - istio 0.0.1
![image](https://user-images.githubusercontent.com/45179589/60219530-9e63d500-9827-11e9-830b-a604c3df9f6a.png)

I tested again to doubly confirm.

Short video showing the issues. I am tailing rancher server logs in this video. You will immediately see the many warnings when I disable Istio.

https://vimeo.com/344683581

If it's helpful (or relevant). My rancher server is running on Digital Ocean host and my cluster is also 1 large digital ocean RKE (1 big node with all roles, with more than enough resources for istio).

**Comment by rancher-max** [comment] 2020-02-06 20:54
Leaving this open, but checked in current state with both Rancher v2.3.5 and master-head `fe3163fc2`. Full tailed log at the end. These warnings do not show up anymore, but there are three lines that should probably be fixed. The first two should just not happen, and the last WARNING should probably be an INFO:
```
2020/02/06 19:00:39 uninstall: Failed deletion of "cluster-istio": no objects visited
[tiller] 2020/02/06 19:00:40 error: release "cluster-istio": object "" not found, skipping delete
2020/02/06 19:00:40 [WARNING] release "cluster-istio" deleted
```

```
[main] 2020/02/06 20:36:59 Starting Tiller v2.14+unreleased (tls=false)
[main] 2020/02/06 20:36:59 GRPC listening on :34051
[main] 2020/02/06 20:36:59 Probes listening on :48134
[main] 2020/02/06 20:36:59 Storage driver is ConfigMap
[main] 2020/02/06 20:36:59 Max history per release is 10
[storage] 2020/02/06 20:37:00 getting release history for "cluster-istio"
[tiller] 2020/02/06 20:37:00 uninstall: Deleting cluster-istio
[tiller] 2020/02/06 20:37:00 executing 24 pre-delete hooks for cluster-istio
[tiller] 2020/02/06 20:37:00 hooks complete for pre-delete cluster-istio
[storage] 2020/02/06 20:37:00 updating release "cluster-istio.v1"
[kube] 2020/02/06 20:37:00 Starting delete for "istio-galley" Service
[kube] 2020/02/06 20:37:00 Starting delete for "kiali" Service
[kube] 2020/02/06 20:37:00 Starting delete for "istio-policy" Service
[kube] 2020/02/06 20:37:01 Starting delete for "istio-telemetry" Service
[kube] 2020/02/06 20:37:01 Starting delete for "istio-pilot" Service
[kube] 2020/02/06 20:37:01 Starting delete for "istio-citadel" Service
[kube] 2020/02/06 20:37:01 Starting delete for "istio-sidecar-injector" Service
[kube] 2020/02/06 20:37:01 Starting delete for "istio-galley" Deployment
[kube] 2020/02/06 20:37:01 Starting delete for "kiali" Deployment
[kube] 2020/02/06 20:37:01 Starting delete for "istio-policy" Deployment
[kube] 2020/02/06 20:37:01 Starting delete for "istio-telemetry" Deployment
[kube] 2020/02/06 20:37:01 Starting delete for "istio-pilot" Deployment
[kube] 2020/02/06 20:37:01 Starting delete for "istio-citadel" Deployment
[kube] 2020/02/06 20:37:01 Starting delete for "istio-sidecar-injector" Deployment
[kube] 2020/02/06 20:37:01 Starting delete for "istio-tracing" Deployment
[kube] 2020/02/06 20:37:01 Starting delete for "istio-service-reader" Role
[kube] 2020/02/06 20:37:01 Starting delete for "istio-galley-admin-role-binding-istio-system" ClusterRoleBinding
[kube] 2020/02/06 20:37:01 Starting delete for "istio-kiali-admin-role-binding-istio-system" ClusterRoleBinding
[kube] 2020/02/06 20:37:01 Starting delete for "istio-mixer-admin-role-binding-istio-system" ClusterRoleBinding
[kube] 2020/02/06 20:37:01 Starting delete for "istio-pilot-istio-system" ClusterRoleBinding
[kube] 2020/02/06 20:37:01 Starting delete for "istio-citadel-istio-system" ClusterRoleBinding
[kube] 2020/02/06 20:37:01 Starting delete for "istio-security-post-install-role-binding-istio-system" ClusterRoleBinding
[kube] 2020/02/06 20:37:01 Starting delete for "istio-sidecar-injector-admin-role-binding-istio-system" ClusterRoleBinding
[kube] 2020/02/06 20:37:01 Starting delete for "istio-multi" ClusterRoleBinding
[kube] 2020/02/06 20:37:01 Starting delete for "istio-galley-istio-system" ClusterRole
[kube] 2020/02/06 20:37:01 Starting delete for "kiali-viewer" ClusterRole
[kube] 2020/02/06 20:37:01 Starting delete for "kiali" ClusterRole
[kube] 2020/02/06 20:37:02 Starting delete for "istio-mixer-istio-system" ClusterRole
[kube] 2020/02/06 20:37:02 Starting delete for "istio-pilot-istio-system" ClusterRole
[kube] 2020/02/06 20:37:02 Starting delete for "istio-citadel-istio-system" ClusterRole
[kube] 2020/02/06 20:37:02 Starting delete for "istio-security-post-install-istio-system" ClusterRole
[kube] 2020/02/06 20:37:02 Starting delete for "istio-sidecar-injector-istio-system" ClusterRole
[kube] 2020/02/06 20:37:02 Starting delete for "istio-reader" ClusterRole
[kube] 2020/02/06 20:37:02 Starting delete for "istio-security-post-install-account" ServiceAccount
[kube] 2020/02/06 20:37:02 Starting delete for "istio-citadel-service-account" ServiceAccount
[kube] 2020/02/06 20:37:02 Starting delete for "istio-sidecar-injector-service-account" ServiceAccount
[kube] 2020/02/06 20:37:02 Starting delete for "istio-multi" ServiceAccount
[kube] 2020/02/06 20:37:02 Starting delete for "istio-galley-service-account" ServiceAccount
[kube] 2020/02/06 20:37:02 Starting delete for "kiali-service-account" ServiceAccount
[kube] 2020/02/06 20:37:02 Starting delete for "istio-mixer-service-account" ServiceAccount
[kube] 2020/02/06 20:37:02 Starting delete for "istio-pilot-service-account" ServiceAccount
[kube] 2020/02/06 20:37:02 Starting delete for "istio-galley-configuration" ConfigMap
[kube] 2020/02/06 20:37:02 Starting delete for "kiali" ConfigMap
[kube] 2020/02/06 20:37:02 Starting delete for "kiali-console" ConfigMap
[kube] 2020/02/06 20:37:02 Starting delete for "istio-security-custom-resources" ConfigMap
[kube] 2020/02/06 20:37:02 Starting delete for "istio" ConfigMap
[kube] 2020/02/06 20:37:02 Starting delete for "istio-sidecar-injector" ConfigMap
2020/02/06 20:37:02 uninstall: Failed deletion of "cluster-istio": no objects visited
[kube] 2020/02/06 20:37:02 Starting delete for "istio-policy" DestinationRule
[kube] 2020/02/06 20:37:02 Starting delete for "istio-telemetry" DestinationRule
[kube] 2020/02/06 20:37:02 Starting delete for "istio-policy" HorizontalPodAutoscaler
[kube] 2020/02/06 20:37:02 Starting delete for "istio-telemetry" HorizontalPodAutoscaler
[kube] 2020/02/06 20:37:02 Starting delete for "istio-pilot" HorizontalPodAutoscaler
[kube] 2020/02/06 20:37:02 Starting delete for "jaeger-query" Service
[kube] 2020/02/06 20:37:03 Starting delete for "jaeger-collector" Service
[kube] 2020/02/06 20:37:03 Starting delete for "jaeger-agent" Service
[kube] 2020/02/06 20:37:03 Starting delete for "zipkin" Service
[kube] 2020/02/06 20:37:03 Starting delete for "tracing" Service
[kube] 2020/02/06 20:37:03 Starting delete for "istio-sidecar-injector" MutatingWebhookConfiguration
[kube] 2020/02/06 20:37:03 Starting delete for "istioproxy" attributemanifest
[kube] 2020/02/06 20:37:03 Starting delete for "kubernetes" attributemanifest
[kube] 2020/02/06 20:37:03 Starting delete for "prometheus" handler
[kube] 2020/02/06 20:37:03 Starting delete for "kubernetesenv" handler
[kube] 2020/02/06 20:37:03 Starting delete for "responsesize" instance
[kube] 2020/02/06 20:37:03 Starting delete for "tcpconnectionsclosed" instance
[kube] 2020/02/06 20:37:03 Starting delete for "tcpconnectionsopened" instance
[kube] 2020/02/06 20:37:03 Starting delete for "tcpbytesent" instance
[kube] 2020/02/06 20:37:03 Starting delete for "attributes" instance
[kube] 2020/02/06 20:37:03 Starting delete for "requestcount" instance
[kube] 2020/02/06 20:37:03 Starting delete for "requestsize" instance
[kube] 2020/02/06 20:37:03 Starting delete for "tcpbytereceived" instance
[kube] 2020/02/06 20:37:03 Starting delete for "requestduration" instance
[kube] 2020/02/06 20:37:03 Starting delete for "promtcpconnectionclosed" rule
[kube] 2020/02/06 20:37:03 Starting delete for "promhttp" rule
[kube] 2020/02/06 20:37:03 Starting delete for "tcpkubeattrgenrulerule" rule
[kube] 2020/02/06 20:37:03 Starting delete for "promtcpconnectionopen" rule
[kube] 2020/02/06 20:37:03 Starting delete for "promtcp" rule
[kube] 2020/02/06 20:37:03 Starting delete for "kubeattrgenrulerule" rule
[tiller] 2020/02/06 20:37:03 error: release "cluster-istio": object "" not found, skipping delete
[tiller] 2020/02/06 20:37:03 executing 24 post-delete hooks for cluster-istio
[tiller] 2020/02/06 20:37:03 hooks complete for post-delete cluster-istio
[tiller] 2020/02/06 20:37:03 purge requested for cluster-istio
[storage] 2020/02/06 20:37:03 deleting release "cluster-istio.v1"
2020/02/06 20:37:03 [WARNING] release "cluster-istio" deleted

[main] 2020/02/06 20:37:05 Starting Tiller v2.14+unreleased (tls=false)
[main] 2020/02/06 20:37:05 GRPC listening on :45647
[main] 2020/02/06 20:37:05 Probes listening on :46992
[main] 2020/02/06 20:37:05 Storage driver is ConfigMap
[main] 2020/02/06 20:37:05 Max history per release is 10
[storage] 2020/02/06 20:37:06 getting release history for "cluster-istio"
[tiller] 2020/02/06 20:37:06 uninstall: Release not loaded: cluster-istio
2020/02/06 20:37:06 [INFO] withdraw istio metric expression from CLuster c-97znb successfully
```

**Comment by rayandas** [comment] 2023-01-05 11:57
V1 charts are not supported anymore. V2 charts can't be disabled. Looking at the above comment from @rancher-max the issue was no longer reproducible in Rancher `v2.3.5`. Hence this issue can be closed.

**Closed** 2023-01-06 10:28 UTC
Labels: kind/bug-qa, area/istio, [zube]: Unscheduled, team/infracloud
