### ISSUE TITLE
[Feature Request] Shared Node Templates

### ISSUE THREAD

**Issue by mitchellmaler** [rancher/rancher#13591] opened 2018-05-18 16:12 UTC
#I would like to be able to share node templates between the other admin users that are managing the clusters. Right now it seems like it is per user. We are having to share a single admin account to be able to provision new clusters with the same config.

**Comment by superseb** [comment] 2018-05-18 19:16
Duplicate of https://github.com/rancher/rancher/issues/12186

**Closed by superseb** 2018-05-18 19:16 UTC

**Comment by mitchellmaler** [comment] 2018-05-18 19:18
Nice! Missed that one. I'll follow that issue.
