### ISSUE TITLE
Custom cattle project template gets removed/replaced with default

### ISSUE THREAD

**Issue by DenverJ** [rancher/rancher#8021] opened 2017-03-02 05:03 UTC
**Rancher Versions:**
Server: 1.3.4

**OS and where are the hosts located? (cloud, bare metal, etc):** AWS

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)** HA rancher & single node

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)** Cattle

**Steps to Reproduce:** Unknown...

We have modified the default Cattle template with settings necessary to run in our environment. This includes custom configuration for the rancher IPSEC service as well as a catalog item from a custom internal catalog repository. We don't know what triggers it (on a restart of the manager?) but our custom config is removed and replaced with the default cattle template. We are behind a proxy to get out to github.

Here is an extract from the project_template table. It shows just cattle as that is what we care about but we can actually see that all templates are removed and recreated.
```
mysql> select id,name,kind,uuid,description,state,created,removed,remove_time from project_template where Name LIKE '%cattle%';
+----+-------------------+-----------------+--------------------------------------+------------------------------------+---------+---------------------+---------------------+---------------------+
| id | name              | kind            | uuid                                 | description                        | state   | created             | removed             | remove_time         |
+----+-------------------+-----------------+--------------------------------------+------------------------------------+---------+---------------------+---------------------+---------------------+
|  4 | Cattle (Modified) | projectTemplate | 34303f93-c337-40a1-af7d-19ef44b7834b | Default Cattle template (Modified) | removed | 2017-01-03 00:43:13 | 2017-01-31 05:00:16 | 2017-01-31 05:07:04 |
| 14 | Cattle            | projectTemplate | 62a3105a-3913-4195-83b5-c1eef0007f8c | Default Cattle template            | removed | 2017-01-31 05:00:52 | 2017-02-01 01:16:45 | 2017-02-01 01:26:08 |
| 19 | Cattle            | projectTemplate | bda5f93b-c206-4ba8-bfb0-764be02dbd25 | Default Cattle template            | removed | 2017-02-01 01:20:23 | 2017-02-08 02:51:31 | 2017-02-08 02:59:14 |
| 23 | Cattle            | projectTemplate | 78b8ac47-ef5f-412f-8ee4-78bf0459559e | Default Cattle template            | removed | 2017-02-08 02:56:31 | 2017-02-08 12:53:14 | 2017-02-08 13:02:53 |
| 28 | Cattle            | projectTemplate | 4cad6cf0-0198-431d-830f-612440947e7a | Default Cattle template            | removed | 2017-02-08 12:58:15 | 2017-02-08 16:48:17 | 2017-02-08 16:50:30 |
| 33 | Cattle            | projectTemplate | 749408e6-d6f7-4504-bc94-5ca0a453cf05 | Default Cattle template            | removed | 2017-02-08 16:53:17 | 2017-02-08 18:33:18 | 2017-02-08 18:36:45 |
| 38 | Cattle            | projectTemplate | e2f9a14a-1589-4702-9e61-35e65582d92e | Default Cattle template            | removed | 2017-02-08 18:38:19 | 2017-02-08 18:53:22 | 2017-02-08 19:02:12 |
| 43 | Cattle (Modified) | projectTemplate | be84e674-1496-40cf-94f0-427df0d02cd1 | Default Cattle template (Modified) | removed | 2017-02-08 18:58:23 | 2017-03-01 05:07:29 | 2017-03-01 05:11:52 |
| 49 | Cattle (Modified) | projectTemplate | 8481052f-db8c-4b58-902f-254ea06ad02a | Default Cattle template (Modified) | active  | 2017-03-01 05:12:30 | NULL                | NULL                |
+----+-------------------+-----------------+--------------------------------------+------------------------------------+---------+---------------------+---------------------+---------------------+
```
And here is some relevant looking lines from the cattle-debug.log that match up with the add/remove times above...
```
2017-02-08 03:53:15,929 INFO  [:] [] [] [] [ecutorService-8] [i.c.p.s.s.ProjectTemplateService    ] Loaded project templates from the catalog
2017-02-08 12:53:13,703 INFO  [:] [] [] [] [cutorService-10] [i.c.p.s.s.ProjectTemplateService    ] Removing project template [catalog://library:project*mesos:0]
2017-02-08 12:53:13,805 INFO  [:] [] [] [] [cutorService-10] [i.c.p.s.s.ProjectTemplateService    ] Removing project template [catalog://library:project*kubernetes:0]
2017-02-08 12:53:13,913 INFO  [:] [] [] [] [cutorService-10] [i.c.p.s.s.ProjectTemplateService    ] Removing project template [catalog://library:project*windows:0]
2017-02-08 12:53:13,978 INFO  [:] [] [] [] [cutorService-10] [i.c.p.s.s.ProjectTemplateService    ] Removing project template [catalog://library:project*swarm:0]
2017-02-08 12:53:14,050 INFO  [:] [] [] [] [cutorService-10] [i.c.p.s.s.ProjectTemplateService    ] Removing project template [catalog://library:project*cattle:0]
2017-02-08 12:58:14,199 INFO  [:] [] [] [] [ecutorService-4] [i.c.p.s.s.ProjectTemplateService    ] Adding project template [catalog://library:project*kubernetes:0]
2017-02-08 12:58:14,324 INFO  [:] [] [] [] [ecutorService-4] [i.c.p.s.s.ProjectTemplateService    ] Adding project template [catalog://library:project*mesos:0]
2017-02-08 12:58:14,416 INFO  [:] [] [] [] [ecutorService-4] [i.c.p.s.s.ProjectTemplateService    ] Adding project template [catalog://library:project*windows:0]
2017-02-08 12:58:14,493 INFO  [:] [] [] [] [ecutorService-4] [i.c.p.s.s.ProjectTemplateService    ] Adding project template [catalog://library:project*swarm:0]
2017-02-08 12:58:14,568 INFO  [:] [] [] [] [ecutorService-4] [i.c.p.s.s.ProjectTemplateService    ] Adding project template [catalog://library:project*cattle:0]
2017-02-08 16:48:16,163 INFO  [:] [] [] [] [ecutorService-1] [i.c.p.s.s.ProjectTemplateService    ] Removing project template [catalog://library:project*kubernetes:0]
2017-02-08 16:48:16,275 INFO  [:] [] [] [] [ecutorService-1] [i.c.p.s.s.ProjectTemplateService    ] Removing project template [catalog://library:project*mesos:0]
2017-02-08 16:48:16,364 INFO  [:] [] [] [] [ecutorService-1] [i.c.p.s.s.ProjectTemplateService    ] Removing project template [catalog://library:project*windows:0]
2017-02-08 16:48:16,442 INFO  [:] [] [] [] [ecutorService-1] [i.c.p.s.s.ProjectTemplateService    ] Removing project template [catalog://library:project*swarm:0]
2017-02-08 16:48:16,503 INFO  [:] [] [] [] [ecutorService-1] [i.c.p.s.s.ProjectTemplateService    ] Removing project template [catalog://library:project*cattle:0]
2017-02-08 16:53:16,616 INFO  [:] [] [] [] [ecutorService-3] [i.c.p.s.s.ProjectTemplateService    ] Adding project template [catalog://library:project*kubernetes:0]
2017-02-08 16:53:16,659 INFO  [:] [] [] [] [ecutorService-3] [i.c.p.s.s.ProjectTemplateService    ] Adding project template [catalog://library:project*mesos:0]
2017-02-08 16:53:16,710 INFO  [:] [] [] [] [ecutorService-3] [i.c.p.s.s.ProjectTemplateService    ] Adding project template [catalog://library:project*windows:0]
2017-02-08 16:53:16,755 INFO  [:] [] [] [] [ecutorService-3] [i.c.p.s.s.ProjectTemplateService    ] Adding project template [catalog://library:project*swarm:0]
2017-02-08 16:53:16,796 INFO  [:] [] [] [] [ecutorService-3] [i.c.p.s.s.ProjectTemplateService    ] Adding project template [catalog://library:project*cattle:0]
2017-02-08 18:33:17,408 INFO  [:] [] [] [] [ecutorService-1] [i.c.p.s.s.ProjectTemplateService    ] Removing project template [catalog://library:project*kubernetes:0]
2017-02-08 18:33:17,603 INFO  [:] [] [] [] [ecutorService-1] [i.c.p.s.s.ProjectTemplateService    ] Removing project template [catalog://library:project*mesos:0]
2017-02-08 18:33:17,750 INFO  [:] [] [] [] [ecutorService-1] [i.c.p.s.s.ProjectTemplateService    ] Removing project template [catalog://library:project*windows:0]
2017-02-08 18:33:17,882 INFO  [:] [] [] [] [ecutorService-1] [i.c.p.s.s.ProjectTemplateService    ] Removing project template [catalog://library:project*swarm:0]
2017-02-08 18:33:18,032 INFO  [:] [] [] [] [ecutorService-1] [i.c.p.s.s.ProjectTemplateService    ] Removing project template [catalog://library:project*cattle:0]
2017-02-08 18:38:18,339 INFO  [:] [] [] [] [cutorService-10] [i.c.p.s.s.ProjectTemplateService    ] Adding project template [catalog://library:project*mesos:0]
2017-02-08 18:38:18,391 INFO  [:] [] [] [] [cutorService-10] [i.c.p.s.s.ProjectTemplateService    ] Adding project template [catalog://library:project*kubernetes:0]
2017-02-08 18:38:18,470 INFO  [:] [] [] [] [cutorService-10] [i.c.p.s.s.ProjectTemplateService    ] Adding project template [catalog://library:project*windows:0]
2017-02-08 18:38:18,564 INFO  [:] [] [] [] [cutorService-10] [i.c.p.s.s.ProjectTemplateService    ] Adding project template [catalog://library:project*swarm:0]
2017-02-08 18:38:18,633 INFO  [:] [] [] [] [cutorService-10] [i.c.p.s.s.ProjectTemplateService    ] Adding project template [catalog://library:project*cattle:0]
2017-02-08 18:53:19,394 INFO  [:] [] [] [] [ecutorService-5] [i.c.p.s.s.ProjectTemplateService    ] Removing project template [catalog://library:project*mesos:0]
2017-02-08 18:53:19,751 INFO  [:] [] [] [] [ecutorService-5] [i.c.p.s.s.ProjectTemplateService    ] Removing project template [catalog://library:project*kubernetes:0]
2017-02-08 18:53:20,215 INFO  [:] [] [] [] [ecutorService-5] [i.c.p.s.s.ProjectTemplateService    ] Removing project template [catalog://library:project*windows:0]
2017-02-08 18:53:20,635 INFO  [:] [] [] [] [ecutorService-5] [i.c.p.s.s.ProjectTemplateService    ] Removing project template [catalog://library:project*swarm:0]
2017-02-08 18:53:21,114 INFO  [:] [] [] [] [ecutorService-5] [i.c.p.s.s.ProjectTemplateService    ] Removing project template [catalog://library:project*cattle:0]
2017-02-08 18:58:21,645 INFO  [:] [] [] [] [cutorService-10] [i.c.p.s.s.ProjectTemplateService    ] Adding project template [catalog://library:project*kubernetes:0]
2017-02-08 18:58:22,006 INFO  [:] [] [] [] [cutorService-10] [i.c.p.s.s.ProjectTemplateService    ] Adding project template [catalog://library:project*mesos:0]
2017-02-08 18:58:22,351 INFO  [:] [] [] [] [cutorService-10] [i.c.p.s.s.ProjectTemplateService    ] Adding project template [catalog://library:project*windows:0]
2017-02-08 18:58:22,528 INFO  [:] [] [] [] [cutorService-10] [i.c.p.s.s.ProjectTemplateService    ] Adding project template [catalog://library:project*swarm:0]
2017-02-08 18:58:22,718 INFO  [:] [] [] [] [cutorService-10] [i.c.p.s.s.ProjectTemplateService    ] Adding project template [catalog://library:project*cattle:0]
2017-02-08 19:08:23,712 INFO  [:] [] [] [] [ecutorService-4] [i.c.p.s.s.ProjectTemplateService    ] Removing project template [catalog://library:project*kubernetes:0]
2017-02-08 19:13:24,573 INFO  [:] [] [] [] [ecutorService-1] [i.c.p.s.s.ProjectTemplateService    ] Adding project template [catalog://library:project*kubernetes:0]
```

**Comment by tfiduccia** [comment] 2017-03-02 17:36
@DenverJ - this is actually a duplicate of #7985.  Any time you try to create or even modify a public template the changes are getting removed.  We are looking into it.

**Closed by tfiduccia** 2017-03-02 17:36 UTC
