### ISSUE TITLE
`json unmarshall error` when using external_link to a service that was scheduled on a specific host

### ISSUE THREAD

**Issue by prelegalwonder** [rancher/rancher#3929] opened 2016-03-11 17:20 UTC
Rancher Version: 0.59.1

Docker Version: 1.10.2

OS: Ubuntu 14.04.4 LTS 

Steps to Reproduce: 
1. create an applications stack with a service 
(eg. Stack called Data, service is consul )
2. create a new stack with a container that references an external_link that exists in the first "Data" stack that is of type "service".
eg. 
```yaml
my-portal:
    restart: always
    tty: TRUE
    image: some.registry.com:5000/dev/myportal:v2
    expose:
     - "8443"
    external_links:
        - Data/consul:consul
    environment:
        NODE_ENV: "staging"
        MY_BRANCH: "master"
```
Results: 
```
level=error msg="Failed Creating portal : json: cannot unmarshal number into Go value of type string"
level=error msg="Stack Create Event Failed: json: cannot unmarshal number into Go value of type string" eventId=27b40da6-04b6-4271-911c-cb7fbf1a3fb1 resourceId=1e44
level=info msg="[bugtest:]: Project created " eventId=27b40da6-04b6-4271-911c-cb7fbf1a3fb1 resourceId=1e44 
```
Service never gets activated and hangs indefinitely because external_link doesn't get created. 

Expected:
Service gets activated and has access to external_link reference. 

Notes: If the external_link is of type "External" instead of "Service", there is no issue.

**Comment by deniseschannon** [comment] 2016-03-11 17:25
How are you creating the stack? Through the UI or Rancher-compose?

Duplicate of https://github.com/rancher/rancher/issues/2501

But I still haven't been able ot reproduce

**Comment by deniseschannon** [comment] 2016-03-11 17:28
Also, could you share your docker-compose.yml of your other stack that you are linking the service to?

**Comment by prelegalwonder** [comment] 2016-03-11 17:34
I'm using the Rancher UI + private catalog. Though I've confirmed the same happens if I  just drop in a docker-compose.yml contents into the "Add Stack -> docker-compose.yml dialog box".

For the first (external) Stack, I just created it via the "Data" stack via the U/I but I'll attach the exported config. 



[compose.zip](https://github.com/rancher/rancher/files/169650/compose.zip)

**Comment by prelegalwonder** [comment] 2016-03-11 17:36
Also, I just want to emphasize (because I think it may help), when I cross-stack link to a type "external" service like IP / DNS, it works fine. It's only when I cross-stack link to a type "service" do I run into the issue.

**Comment by deniseschannon** [comment] 2016-03-11 17:57
I created your Data stack (with no issues), I then copied and pasted your new stack in the UI and no issues in my setup.

Is this a fresh install or upgraded setup? I have never been able to reproduce and it's not a rancher-compose specific error, since it's json unmarshalling error.

**Comment by prelegalwonder** [comment] 2016-03-11 18:13
It's a fresh install. 
Are you using the same version of Docker? 

Maybe it's a regression or similar occurrence of [this bug](https://github.com/docker/compose/issues/2515) and I need to re-open / open a new issue in the Docker project?

What do you think? I'm hanging out in #rancher on freenode if you want to chat. nick: skel

**Comment by Verikon** [comment] 2016-03-13 18:58
I created a private repo to test this issue against, https://github.com/Verikon/rancher-test-catalogue.

In theory you should be able to add this github repo as a private registry, and deploy the container, pinging a hostname of "mongo" from within.

**Comment by prelegalwonder** [comment] 2016-03-14 03:01
FYI, I completely blew away my rancher setup, and installed v0.63.0 fresh and I can no longer create this issue. When I have some time, I'll go back and try again with v0.59.1

**Comment by Verikon** [comment] 2016-03-14 13:04
@prelegalwonder , thanks - i'll give that a try then.

**Comment by Verikon** [comment] 2016-03-14 14:32
Confirm that, I do NOT experience a problem when running v0.63.0.

**Comment by deniseschannon** [comment] 2016-03-14 18:18
@prelegalwonder @Verikon I'd be surprised if it was a version issue as we didn't make any changes in rancher-compose between the 2 releases. 

Would you be okay with closing this and we can re-open if you can reproduce?

**Comment by prelegalwonder** [comment] 2016-03-14 18:20
Sure np. Thanks for taking the time to look at this!

**Comment by Verikon** [comment] 2016-03-14 19:27
I was able to recreate this in v0.63.

When the target service has deployed scheduling rules then we can recreate this issue.

**Comment by Verikon** [comment] 2016-03-14 19:36
thanks @deniseschannon - hope that helps catching the bug.

**Comment by deniseschannon** [comment] 2016-03-14 19:36
I am going to try and reproduce shortly cause this bug drives me crazy!

**Comment by deniseschannon** [comment] 2016-03-14 20:29
Thank you @Verikon!! I was able to reproduce with your detailed steps. :) 

1. Create a service scheduled on a specific host using the option in the Scheduling tab. "Run All containers on one host"
2. Add catalog  https://github.com/Verikon/rancher-test-catalogue
3. Add template and select service from step 1.

**Comment by Verikon** [comment] 2016-03-14 20:53
great @deniseschannon ; thanks for all your hard work :)

**Comment by deniseschannon** [comment] 2016-03-15 03:58
This is occurring due to #3970. Once that is fixed, this use case will be fixed as well.

**Comment by alena1108** [comment] 2016-03-15 20:56
Closing in favor of https://github.com/rancher/rancher/issues/594

**Closed by alena1108** 2016-03-15 20:56 UTC
Labels: kind/bug
