### ISSUE TITLE
Should accept only valid DNS name formats for service link names.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#1315] opened 2015-06-22 17:26 UTC
Sever version - v0.25.0-rc2

Steps to reproduce the problem:

I had named service link name as "127.0.0" , I see that the DNS resolution using "127.0.0" fails , even though dig on "127.0.0" shows the correct list of container ip addresses it should resolve to.

![screen shot 2015-06-22 at 10 16 04 am](https://cloud.githubusercontent.com/assets/4266958/8287920/b92f6ad6-18c7-11e5-8ef7-86e41f1997a9.png)

I see similar issue when using  service link name as "127.0.0.1"

![screen shot 2015-06-22 at 10 18 07 am](https://cloud.githubusercontent.com/assets/4266958/8287954/0665c7e6-18c8-11e5-8813-9dd99a08c2b3.png)

There is also a similar issue when using spaces in dnsname - i used link name as "test me"

I see it being programmed in network agent:

    "10.42.228.21": {
        "client.": ["10.42.228.21"],
        "client.rancher.internal.": ["10.42.228.21"],
        "mydns.": ["10.42.95.81", "10.42.50.51", "10.42.49.74"],
        "mydns.rancher.internal.": ["10.42.95.81", "10.42.50.51", "10.42.49.74"],
        "test me.": ["10.42.95.81", "10.42.50.51", "10.42.49.74"],
        "test me.rancher.internal.": ["10.42.95.81", "10.42.50.51", "10.42.49.74"]
    }, 

But these links are not usable.

**Comment by deniseschannon** [comment] 2015-12-03 23:02
Duplicate of #680

**Closed by deniseschannon** 2015-12-03 23:02 UTC
Labels: kind/bug
