### ISSUE TITLE
[BUG] Fleet fails to sync repository via SSH

### ISSUE THREAD

**Issue by pjbgf** [rancher/rancher#43499] opened 2023-11-06 20:03 UTC
**Rancher Server Setup**
- Rancher version: `v2.8-7034c86f64e338464d17721262c3819d946a6070-head`
- Installation option (Docker install/Helm Chart):
   - Docker install

**Information about the Cluster**
- Kubernetes version:
- Cluster Type (Local/Downstream): Local

**User Information**
- What is the role of the user logged in?

Admin

**Describe the bug**
Fleet fails to sync repository via SSH as it cannot find the `git` cli in the execution path.

**To Reproduce**
- Create a new Git Repo in Continuous Delivery.
- Set a SSH URL.
- Finish creating the repository.

**Result**
Fleet errors with `Exec: "git": executable file not found in $PATH`

**Expected Result**
Fleet syncs the repository.

**Screenshots**
![image](https://github.com/rancher/rancher/assets/5452977/a7df7c7f-b857-431c-9b7b-a51b409f8d50)

**Additional context**
This could not be reproduced in `v2.7.8` or `v2.7.9`.

**Comment by pjbgf** [comment] 2023-11-13 15:37
Fixed as per rancher/gitjob#362.

**Comment by olblak** [comment] 2023-11-15 07:54
Until QA validation (if required), this issue should not be closed

**Comment by pjbgf** [comment] 2023-11-15 11:25
@olblak my bad for closing this too early.

**Comment by olblak** [comment] 2023-11-17 09:51
Adding to the milestone v2.8-Next1 to target the next Rancher release

**Comment by sbulage** [comment] 2024-03-04 09:16
I see 2.8.3-rc2 is available for testing, so removed label `[zube]: Waiting for Rancher RC` label

**Comment by thehejik** [comment] 2024-03-04 16:22
### Test report

This issue is fixed in current `rancher:2.8.3-rc2`:
![image](https://github.com/rancher/rancher/assets/12828077/192542b9-01c0-4d8a-8afb-6547fab991f8)

Current fleet app version is: `fleet:103.1.1+up0.9.1-rc.5` and images are:
```
rancher/fleet:v0.9.1-rc.5
rancher/gitjob:v0.9.3
rancher/fleet-agent:v0.9.1-rc.5
```
### Testing
I could reproduce the issue by using `rancher/gitjob:v1.27` which was tagged/built just before merging the commit with fix:
![image](https://github.com/rancher/rancher/assets/12828077/833a575e-4756-4b59-9eba-b102e2abb0e0)

But normally without knowing exact fleet images versions/tags at time of the failure I'm unable to reproduce any problems as  rancher `v2.8-head` (even with commit hash) is pointing to `dev-v2.8` app repo with up-to-date charts and images.

Closing.

**Comment by thehejik** [comment] 2024-03-05 07:47
@kkaempf reopened for Platform Team checks.

**Comment by gaktive** [comment] 2024-03-14 19:02
@bmdepesa since Fleet tested this, perhaps Rancher QA can do a quick sanity test on this amidst other work. I'll figure out a way of improved communications on this between teams going forward.

**Comment by bmdepesa** [comment] 2024-03-14 19:22
Since this area (git repo) is fleet-specific we'll close this as tested. I don't see what else Rancher QA could do to additionally validate.

**Closed by bmdepesa** 2024-03-14 19:22 UTC
Labels: kind/bug, [zube]: To Triage, area/fleet, status/to-test, team/fleet, status/tracked-in-fleet
