### ISSUE TITLE
unable to use rancher

### ISSUE THREAD

**Issue by mwaaas** [rancher/rancher#6687] opened 2016-11-20 06:08 UTC
Failed to allocate instance [container:1i135]: Bad instance [container:1i135] in state [removed]: Failed to find network for networkMode managed

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v1.2.0-pre4-rc8` Cattle: `v0.173.0` UI: `v1.2.23` |
|Access|`github` `admin`|
|Orchestration|`Cattle`|
|Route|`settings.projects.detail`|

**Comment by tfiduccia** [comment] 2016-11-20 06:55
@mwaaas - in RC8 the catalog entries did not automatically deploy to the Default Environment.  You will have to go the catalog and deploy these manually if you want to use it.  Or create a new cattle environment.
Catalog template to deploy:
Rancher Healthcheck
Rancher DNS
Rancher Metadata
Rancher Network-manager
Rancher IPSEC
Rancher Scheduler

Closing this as a duplicate of #6666

**Closed by tfiduccia** 2016-11-20 06:55 UTC
