### ISSUE TITLE
CIS Benchmark catalog app failed to generate CIS scan report due to large configmap size

### ISSUE THREAD

**Issue by hcbing** [rancher/rancher#37200] opened 2022-04-06 02:17 UTC
**Rancher Server Setup**
- Rancher version: v2.6.3
- Installation option (Docker install/Helm Chart): Helm v3.6.3
  - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): RKE1 v1.3.3

**Information about the Cluster**
- Kubernetes version: v1.21.7-rancher1-1
- Cluster Type (Local/Downstream): Local

**User Information**
- What is the role of the user logged in? Admin

**Describe the bug**
CIS Benchmark catalog app failed to generate CIS scan report due to large configmap size.

**To Reproduce**
1. Provision a new cluster running k8s v1.21.7-rancher1-1 using RKE CLI v1.3.32. In our case, it's a 13-node cluster.
2. Helm install Rancher v2.6.3.
3. Apps & Marketplace > Charts > CIS Benchmark v2.0.2 (All else default)
4. CIS Benchmark > Scans > Create > Profile: rke-profile-hardened-1.6
5. Scan state for "warn" results: Pass
6. Scheduling: Run scan once

**Result**
`The ConfigMap "cisscan-output-for-scan-2qzzq" is invalid: []: Too long: must have at most 1048576 bytes error creating configmap for storing the report`

**Expected Result**
`ClusterScan complete, there are some test failures, please check the ClusterScanReport`

**Additional context**
Getting this error consistently with each new scan retry.
Tried skipping multiple tests, still the same error.
Ran similar scans on other RKE provisioned local clusters and downstream Rancher-launched clusters, seems to work fine. Doesn't seem to be cluster type specific.
Tried increasing etcd max-request-bytes parameter to 2MB, made no difference.

**Comment by hcbing** [comment] 2022-06-06 03:11
Still an open issue.

**Comment by Rancheroo** [comment] 2022-06-07 05:58
This seems to be working in Rancher 2.6.5

![image](https://user-images.githubusercontent.com/56899019/172306408-a26810a7-55e3-4f70-bcf8-6472a0ac54a9.png)

**Comment by Rancheroo** [comment] 2022-06-07 06:09
However in addition to this issue, I am seeing the same problems when using the eks-profile
![image](https://user-images.githubusercontent.com/56899019/172308035-8bd2fff2-53fe-4294-9abe-e8d54e25112e.png)

**Comment by macedogm** [comment] 2022-06-20 13:33
@MKlimuszka I think that this should be moved to https://github.com/rancher/cis-operator. WDYT?

**Comment by hcbing** [comment] 2022-08-20 07:53
bump

**Comment by vardhaman22** [comment] 2022-11-01 05:03
@hcbing 
This issue is not reproducible on rancher v2.6.9.
Can you please confirm if you are still facing this issue.

**Comment by MKlimuszka** [comment] 2022-11-17 18:22
Given that we can't reproduce this, I am closing it. If new reproduction steps are added, it can be reopened.

**Closed by MKlimuszka** 2022-11-17 18:22 UTC
Labels: kind/bug, [zube]: Need Info, team/area3, team/infracloud, feature/charts-cis-benchmark

**Comment by xhejtman** [comment] 2023-08-21 23:19
This issue is still there, large cluster can easily create bigger config map than 1MB. I have an example.

**Comment by nicgrobler** [comment] 2024-08-05 17:01
can confirm - big enough cluster (in our case, 32 workers) causes this when running hardened profile (1.8)
