### ISSUE TITLE
[BUG] Creating a project/namespace with container default limits do not always result in the controller creating a LimitRange obj

### ISSUE THREAD

**Issue by samjustus** [rancher/rancher#43349] opened 2023-10-31 16:53 UTC
need to investigate use cases and bugs before we can address rancher/rancher#39700

**Comment by pennyscissors** [comment] 2023-11-02 21:46
Findings post investigating this:

When you create a project without CDLs (Container Default Limits), and then create a namespace with CRLs (Container Resource Limits) inside that project, a LimitRange object is not created. This feature provides multiple ways for input/edit of CDL/CRL configurations (you can set CDLs and CRLs through the project's resource quotas view, project's CDLs view, and namespaces' CRLs view) which add complexity as these are all affected. 
[
This piece of code](https://github.com/rancher/rancher/blob/9b9a65d5f28f23d40798d6549d463915c89c8ee5/pkg/controllers/managementuser/resourcequota/resource_quota_sync.go#L458-L483) in the resource quota controller gets executed when a LimitRange needs to be created, and it's in charge of "merging" the namespace CRLs with the project's CDLs. The issue is that when there are no CDLs set in the project the namespace belongs to, the logic in there does not use the namespace's CRLs and so a LimitRange is not created. But once you implement a fix for this (use the namespace's CRLs when there are no project CDLs defined), a few other issues arise which exposes underlying problems in the controller logic that were hidden by this bug. There is no simple fix.

Some of the issues I saw post fix were: 
1. If you edit the project to add CDLs when there were no CDLs defined previously, all existing namespaces get updated with those CDLs. (directly conflicts with the behavior we have documented [here](https://ranchermanager.docs.rancher.com/how-to-guides/advanced-user-guides/manage-projects/manage-project-resource-quotas/set-container-default-resource-limits#resource-limit-propagation))
2. If your project has CDLs, and a namespace belonging to said project has CRLs, you can't override the CDLs through the namespace's CRL view. Any values you leave empty when you add CRLs to your namespace will be populated by the projects CDLs regardless of removing the value in the UI. This results in a discrepancy of values among the namespace's CRLs defined in the `field.cattle.io/containerDefaultResourceLimit` annotation (only has the values you set in the UI), the LimitRange object associated with said namespace (has values you set in the UI + project's CDLs), and `spec.containerDefaultResourceLimit` in the project manifest (same values as LimitRange).

**Closed** 2023-11-14 17:56 UTC
Labels: kind/bug, priority/0, area/projects, team/area1, JIRA
