### ISSUE TITLE
service storage / data only container?

### ISSUE THREAD

**Issue by pwFoo** [rancher/rancher#1378] opened 2015-07-01 20:42 UTC
Is it possible to use data only container as persistent storage for a service?
Add a "storage" container, but rancher try to start it and it get stucks with "in progress" and "starting" message.

**Comment by moimael** [comment] 2015-07-03 09:01
+1

**Comment by pwFoo** [comment] 2015-07-03 21:06
I try to organize my containers as services, because it's grouped by projects.

WebApps as service (apache, mysql, storage / data only container)

Dynamic frontside proxy [jwilder/nginx-proxy](https://github.com/jwilder/nginx-proxy) divided to docker-gen, nginx and storage.

So service persistent storage would be an important feature for me.

**Comment by cjellick** [comment] 2015-07-06 13:44
@pwFoo. Thanks for the question.

Can you provide some more details about how you are configuring/starting the storage container that is getting stuck in in progress/starting? I'd like to try to reproduce. Here are some specific questions:

- What image is it? (Or what public image is it based off of if it is customized/private image).
- What is the command you are specifying for the container? (to be clear, I'm referring to the [docker CMD option] (https://docs.docker.com/reference/run/#cmd-default-command-or-options) here).

**Comment by moimael** [comment] 2015-07-06 13:48
@cjellick I think the important part here is that we do not want the container to start. 
See this : https://docs.docker.com/userguide/dockervolumes/ 
The part about "Creating and mounting a data volume container"

But handling data volume container directly in the ui with features such as Backup/restore/move would be awesome. 
I think you might use labels to differentiate data volumes containers from normal containers and prevent them from starting.

**Comment by pwFoo** [comment] 2015-07-06 14:34
As moimael writes above.

There is no problem to create a data only container with Rancher UI if it is not(!) a service container.
Just create a container, cmd "true". Container will be created and stay in stopped mode. All works fine.

Now I try to create a project ("test1") and a service with some containers to build a web app

apache, mysql with persistent data. Because we need persistent data we need two data only container inside the service.

1. container "dbstorage", persistent mysql storage (image "fedora/mariadb", volume "/var/lib/mysql", cmd "true")
2. container "webspace", persistent webspace data (image "fedora/httpd", volume "/var/www/html", cmd "true")
3. webserver (image "fedora/httpd", volumes-from "webspace"
4. database (image "fedora/mariadb", volumes-from "dbstorage"

So data only containers should stay stopped, but all service containers will be started (run 1+ instances). We need a way to create a service container with 0 running instances.

I hope that helps.

**Comment by moimael** [comment] 2015-07-06 14:37
It is linked to this : ref #1395

**Comment by cjellick** [comment] 2015-07-06 14:45
Great info. Thanks to both of you. The part I didn't pick up on initially was that the in-progress/starting issue was specific to services.

Will investigate and sync-up with some team members on this. To summarize, I think this issue represents a bug where data-only containers cannot be made part of a service and issue #1395 represents a feature request for better data-only container support.

**Comment by cjellick** [comment] 2015-07-06 14:47
There is also probably a third item: having to specify the CMD as true for a data-only container is a small hack because we don't support creating but not starting containers on a host. They aren't actually placed on a host until they are "started" in rancher.

**Comment by pwFoo** [comment] 2015-08-05 15:31
data only container would be important for persistent data (mysql, webspaces with uploads, ...) for containers and services. Any update or plans to add this feature?

**Comment by pwFoo** [comment] 2015-08-17 14:05
After some time I looked into rancher services and tried to setup data only containers and volumes-from to use it as persistent storage.
But there is no volumes-from at service UI. Will it be added in the (near?) future?

**Comment by alena1108** [comment] 2015-08-17 16:33
@pwFoo we are planning to add it in the UI soon. Today you can use volumesFrom feature using rancher-compose. http://docs.rancher.com/rancher/rancher-compose/, refer to "Sidekick" section explaining the syntax.

**Comment by pwFoo** [comment] 2015-08-17 17:47
Thanks for posting the link to rancher-compose. I'll take a look into and play with it in the next time!
Great to read volumes from will be added soon.

**Comment by pwFoo** [comment] 2015-09-05 12:05
Is there an example how to use sidekicks to use volumes-from inside an service and is it possible from RancherUI?

Is there an example how to use volumes-from MySQL-Storage service for MySQL-Server service?

**Comment by deniseschannon** [comment] 2015-09-08 18:29
It is not possible from the Rancher UI, but there are examples of how it's supported in rancher-compose using sidekicks to achieve the volumes-from. 

http://docs.rancher.com/rancher/rancher-compose/#sidekicks

**Comment by pwFoo** [comment] 2015-09-10 06:40
Docker data only container could be replaced by convoy? Convoy volumes seems to be persistent volumes (like volumes-from a data container) with additional features (snapshot, backup, restore, ...).

So convoy should be added to RancherOS AS default?

**Comment by pwFoo** [comment] 2015-09-10 06:56
Seems to be planned.
http://rancher.com/using-convoy-to-backup-and-recover-a-wordpress-mysql-database-with-docker/?utm_content=20470085&utm_medium=social&utm_source=googleplus

**Comment by pwFoo** [comment] 2015-09-13 08:00
After some tests. Stopped data only containers seems not to work inside a service. Tested different settings

-  restart: 'no'
- io.rancher.os.remove=false
- io.rancher.os.createonly=true
- io.rancher.container.start_once=true

but container restarts forever.

So I hope persist volumes and also share persist volumes between service containers will be possible in the near future with convoy...

**Comment by deniseschannon** [comment] 2015-09-16 18:04
What version are you using? You should be able to use the  `io.rancher.container.start_once=true` label with v0.37.0. 

https://github.com/rancher/rancher/issues/1935 was fixed in v0.37.0. See notes on how the label should work.

**Comment by pwFoo** [comment] 2015-09-26 11:21
It seems to work with newer version.

**Comment by pwFoo** [comment] 2015-09-30 15:06
Create data only container should be fine with labels.

I created an issue about data only container as sidekick inside a service (#2159), because each service get a independent data only container instead of share the same one with volumes-from.

So I think we can close this issue here and follow #2159.

**Closed** 2015-09-30 16:25 UTC
Labels: area/container, kind/enhancement
