### ISSUE TITLE
Switching between Node Types fails

### ISSUE THREAD

**Issue by Noctalin** [rancher/rancher#11855] opened 2018-03-02 09:10 UTC
**Rancher versions:**
v2.0.0-alpha16

**Operating system and kernel:**
4.9.75-rancher

**Type/provider of hosts:**
DockerVM inside Freenas 11.1U2

**Setup details:**
Single node rancher

**Steps to Reproduce:**
Freshly installed RancherOS on Freenas 11.1U2 with DockerVM.
Create a Cluster and setup nodes later.
Deactivated all drivers except Generic driver.
Going to create Nodes menu to add first Node and selecting Docker Machine type then trying to switch to Custom fails and does nothing.
Gives out Error in Google console as seen in screenshot.

**Results:**
![chrome_2018-03-02_09-55-43](https://user-images.githubusercontent.com/11031032/36891307-70d32c90-1e01-11e8-9d62-8ae608122496.png)

**Comment by superseb** [comment] 2018-03-02 12:11
Duplicate of https://github.com/rancher/rancher/issues/10873

**Closed by superseb** 2018-03-02 12:11 UTC
