### ISSUE TITLE
When deleting catalog app, namespace isn't deleted

### ISSUE THREAD

**Issue by divyangjp** [rancher/rancher#14012] opened 2018-06-15 07:12 UTC
When catalog app is deployed, rancher creates separate namespace for it.
Deleting catalog app deletes all other resources related to that app except namespace created for that app.

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v2.0.2` UI: `v2.0.48` |
|Access|`local` |
|Route|`authenticated.project.ns.index`|

**Comment by loganhz** [comment] 2018-06-26 06:14
@guangbochen @StrongMonkey Can we remove the namespace?

**Comment by StrongMonkey** [comment] 2018-06-26 17:07
duplicate of https://github.com/rancher/rancher/issues/14012

**Closed** 2018-07-16 21:37 UTC
Labels: area/catalog, kind/enhancement, version/2.0
