### ISSUE TITLE
Cluster stuck in updating state after Rancher upgrade

### ISSUE THREAD

**Issue by aaronRancher** [rancher/rancher#34018] opened 2021-08-06 18:14 UTC
**Rancher Server Setup**
- Rancher version: Rancher upgrade from v2.5.9 to v2.6.0-rc1
- Installation option (Docker install/Helm Chart): HA helm install

**Information about the Cluster**
- Kubernetes version: `v1.20.9`
- Cluster Type (Local/Downstream): Downstream
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider): Azure node driver

**Describe the bug**

Azure node cluster becomes stuck in updating state after Rancher upgrade

**To Reproduce**
 
Bring up a v2.5.9 HA install.
Deploy an Azure node cluster (3 etcd, 1 control, 3 worker) k8s version `v1.20.9`. Ubuntu 18.04 LTS
After the cluster becomes available, upgrade Rancher to v2.6.0-rc1.

**Result**
The cluster becomes stuck in updating state.
`[file-deploy] Deploying file [/etc/kubernetes/kube-api-authn-webhook.yaml] to node [...]`
![image](https://user-images.githubusercontent.com/57409052/128554438-da2b4a83-8601-483f-bc41-82bb93bc5e02.png)
An etcd node becomes unreachable. 

**Expected Result**

All nodes should be active after Rancher upgrade.

**Comment by sowmyav27** [comment] 2021-08-06 23:35
I saw a downstream cluster go to Updating state (not a complete RKE up), but came back up Active . This was on an upgrade from 2.5.9 to 2.6.0-rc1

**Comment by kinarashah** [comment] 2021-08-07 01:34
Not able to reproduce with upgrade from v2.5.9 to v2.6.0-rc1. 
Created an ec2 cluster and azure node driver cluster. Both clusters stayed in Active state post upgrade. 

@sowmyav27 mentioned that this issue doesn't reproduce all the time, so keeping it open in case it happens again. We can take a look at logs to confirm if the cluster actually went through provisioning then.

**Comment by sowmyav27** [comment] 2021-08-17 17:27
Could not reproduce clusters going into Upgrading state on an upgrade from 2.5.9 to 2.6.0-rc3

**Comment by sowmyav27** [comment] 2021-08-18 13:19
Closing this issue. Will reopen if we see this issue again

**Closed by sowmyav27** 2021-08-18 13:19 UTC
Labels: kind/bug-qa, [zube]: To Triage, QA/need-info, area/upgrade
