### ISSUE TITLE
The stack name will not get updated when you update stack name from WebUI->Stacks, like api invoke, etc.

### ISSUE THREAD

**Issue by wang-xin** [rancher/rancher#5829] opened 2016-08-29 03:57 UTC
**Rancher Version:** v1.0.1

**Docker Version:** Docker 1.10.3

**OS and where are the hosts located? (cloud, bare metal, etc):** bare

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB):** external DB

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)** Cattle

**Steps to Reproduce:** 
update stack name from WebUI Stacks -> invoke api / access infa WebUI
it only get updated at WebUI Stacks page

**Results:** 
![1](https://cloud.githubusercontent.com/assets/17465385/18040258/5661583e-6dde-11e6-8f74-d7d64865c174.png)

![2](https://cloud.githubusercontent.com/assets/17465385/18040270/76b02eda-6dde-11e6-8937-d338bce72e1b.png)

![3](https://cloud.githubusercontent.com/assets/17465385/18041211/e3644eb2-6de8-11e6-87c3-b690688f14cb.png)

**Expected:** The stack name is testlog1234 in the api.

**Comment by tfiduccia** [comment] 2016-09-06 18:56
Duplicate of #4328

**Closed** 2016-09-06 18:57 UTC
