### ISSUE TITLE
go machine service fails to start with error - "Unable to start EventRouter - websocket: bad handshake"

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#1711] opened 2015-08-01 05:03 UTC
Server version - V0.31.0-rc4

I see the problem where go machine service fails to start with error - "Unable to start EventRouter - websocket: bad handshake" and there is repeated attempts made to start go machine service which keeps failing.

I have been able to do host registration and add hosts successfully on multiple instances.

This issue seems to happen when "add host" is done very quickly after host registration is done.  

Following is the exception seen:

```
time="2015-08-01T04:53:37Z" level=error msg="Unable to start EventRouter" Err="websocket: bad handshake" 
time="2015-08-01T04:53:37Z" level=info msg="Exiting go-machine-service..." 
time="2015-08-01T04:53:38Z" level=info msg="Setting log level" logLevel=info 
time="2015-08-01T04:53:38Z" level=info msg="Starting go-machine-service..." gitcommit=102d311 
time="2015-08-01T04:53:38Z" level=info msg="Initializing event router" workerCount=10 
time="2015-08-01T04:53:39Z" level=error msg="Failed to subscribe to events." error="websocket: bad handshake" subscribeUrl="ws://104.197.102.237:8080//v1/subscribe?eventNames=physicalhost.bootstrap%3Bhandler%3DgoMachineService&eventNames=physicalhost.remove%3Bhandler%3DgoMachineService&eventNames=ping%3Bhandler%3DgoMachineService&eventNames=physicalhost.create%3Bhandler%3DgoMachineService" 
time="2015-08-01T04:53:39Z" level=error msg="Unable to start EventRouter" Err="websocket: bad handshake" 
time="2015-08-01T04:53:39Z" level=info msg="Exiting go-machine-service..." 
time="2015-08-01T04:53:40Z" level=info msg="Setting log level" logLevel=info 
time="2015-08-01T04:53:40Z" level=info msg="Starting go-machine-service..." gitcommit=102d311 
time="2015-08-01T04:53:40Z" level=info msg="Initializing event router" workerCount=10 
time="2015-08-01T04:53:41Z" level=error msg="Failed to subscribe to events." error="websocket: bad handshake" subscribeUrl="ws://104.197.102.237:8080//v1/subscribe?eventNames=ping%3Bhandler%3DgoMachineService&eventNames=physicalhost.create%3Bhandler%3DgoMachineService&eventNames=physicalhost.bootstrap%3Bhandler%3DgoMachineService&eventNames=physicalhost.remove%3Bhandler%3DgoMachineService" 
```

**Comment by cjellick** [comment] 2015-08-03 16:58
@sangeethah I  found the issue: the Host Registration value somehow had a trailing slash in it. So, the property looked like `http://foo/` instead of `http://foo`. And this caused an issue in go machine serverice because the connection URL became `http://foo//v1/subscribe` (two slashes after foo).

So, the app should be more tolerant of the double slash. It is in most places, but perhaps not for this specific scenario.

I don't know how you got the trailing slash in there. I cannot reproduce it, but I removed it and gms is up and running normally.

**Comment by sangeethah** [comment] 2015-08-03 17:16
@cjellick - The url had "/" in it - "http://<ipaddress>:8080/" . So we could consider this as user error or provide some checks to not accept the values that could be invalid.

**Comment by cjellick** [comment] 2015-08-03 17:17
Agreed.
It seems like the UI prevents the trailing slash now. Did you input the url via the normal UI? If so, maybe vince fixed it or something

**Comment by cjellick** [comment] 2015-08-03 17:21
test msg

**Comment by sangeethah** [comment] 2015-08-03 17:22
Setting the host.api was done thru api

**Comment by cjellick** [comment] 2015-08-03 17:26
test

**Comment by cjellick** [comment] 2015-08-03 17:26
test

**Comment by cjellick** [comment] 2015-08-03 17:28
again

**Comment by cjellick** [comment] 2015-08-03 17:28
is this thing on

**Comment by cjellick** [comment] 2015-08-03 17:51
test again

**Comment by gregory** [comment] 2015-08-15 22:40
got the same issue right after i went to add a custom host. not that there is an exception throwned


```
2015-08-15 22:36:17,116 INFO    [main] [ConsoleStatus] [102/102] [59444ms] [1ms] Starting storage-simulator
22:36:17.242 [main] INFO  ConsoleStatus - [DONE ] [66149ms] Startup Succeeded, Listening on port 8081
150815 22:34:55 [Warning] Using unique option prefix key_buffer instead of key_buffer_size is deprecated and will be removed in a future release. Please use the full name instead.
150815 22:34:55 [Note] /usr/sbin/mysqld (mysqld 5.5.44-0ubuntu0.14.04.1) starting as process 58 ...
150815 22:34:56 [Warning] Using unique option prefix key_buffer instead of key_buffer_size is deprecated and will be removed in a future release. Please use the full name instead.
150815 22:34:56 [Note] /usr/sbin/mysqld (mysqld 5.5.44-0ubuntu0.14.04.1) starting as process 64 ...
150815 22:34:56 [Warning] Using unique option prefix key_buffer instead of key_buffer_size is deprecated and will be removed in a future release. Please use the full name instead.
150815 22:34:56 [Note] mysqld (mysqld 5.5.44-0ubuntu0.14.04.1) starting as process 68 ...
Warning: Unable to load '/usr/share/zoneinfo/iso3166.tab' as time zone. Skipping it.
Warning: Unable to load '/usr/share/zoneinfo/zone.tab' as time zone. Skipping it.
time="2015-08-15T22:36:18Z" level=info msg="Starting websocket proxy. Listening on [:8080], Proxying to cattle API at [localhost:8081], Monitoring parent pid [12]."
2015-08-15 22:36:59,515 ERROR [:] [] [] [] [ecutorService-4] [o.a.c.m.context.NoExceptionRunnable ] Uncaught exception io.cattle.platform.async.utils.TimeoutException: Object [account:6] failed to satisfy predicate [15000] millis
        at io.cattle.platform.object.monitor.impl.ResourceMonitorImpl.waitFor(ResourceMonitorImpl.java:92) ~[cattle-framework-resource-monitor-0.5.0-SNAPSHOT.jar:na]
        at io.cattle.platform.object.monitor.impl.ResourceMonitorImpl.waitFor(ResourceMonitorImpl.java:97) ~[cattle-framework-resource-monitor-0.5.0-SNAPSHOT.jar:na]
        at io.cattle.platform.object.monitor.impl.ResourceMonitorImpl.waitForState(ResourceMonitorImpl.java:114) ~[cattle-framework-resource-monitor-0.5.0-SNAPSHOT.jar:na]
        at io.cattle.platform.docker.machine.launch.MachineLauncher.getCredential(MachineLauncher.java:93) ~[cattle-docker-machine-0.5.0-SNAPSHOT.jar:na]
        at io.cattle.platform.docker.machine.launch.MachineLauncher.doRun(MachineLauncher.java:132) ~[cattle-docker-machine-0.5.0-SNAPSHOT.jar:na]
        at org.apache.cloudstack.managed.context.NoExceptionRunnable.runInContext(NoExceptionRunnable.java:13) ~[cattle-framework-managed-context-0.5.0-SNAPSHOT.jar:na]
        at org.apache.cloudstack.managed.context.ManagedContextRunnable$1.run(ManagedContextRunnable.java:49) [cattle-framework-managed-context-0.5.0-SNAPSHOT.jar:na]
        at org.apache.cloudstack.managed.context.impl.DefaultManagedContext$1.call(DefaultManagedContext.java:55) [cattle-framework-managed-context-0.5.0-SNAPSHOT.jar:na]
        at org.apache.cloudstack.managed.context.impl.DefaultManagedContext.callWithContext(DefaultManagedContext.java:108) [cattle-framework-managed-context-0.5.0-SNAPSHOT.jar:na]
        at org.apache.cloudstack.managed.context.impl.DefaultManagedContext.runWithContext(DefaultManagedContext.java:52) [cattle-framework-managed-context-0.5.0-SNAPSHOT.jar:na]
        at org.apache.cloudstack.managed.context.ManagedContextRunnable.run(ManagedContextRunnable.java:46) [cattle-framework-managed-context-0.5.0-SNAPSHOT.jar:na]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471) [na:1.7.0_79]
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:304) [na:1.7.0_79]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:178) [na:1.7.0_79]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [na:1.7.0_79]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) [na:1.7.0_79]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) [na:1.7.0_79]
        at java.lang.Thread.run(Thread.java:745) [na:1.7.0_79]

time="2015-08-15T22:37:14Z" level=info msg="Setting log level" logLevel=info
time="2015-08-15T22:37:14Z" level=info msg="Starting go-machine-service..." gitcommit=102d311
time="2015-08-15T22:37:15Z" level=info msg="Initializing event router" workerCount=10
time="2015-08-15T22:37:15Z" level=error msg="Failed to subscribe to events." error="websocket: bad handshake" subscribeUrl="ws://foo.com/v1/subscribe?eventNames=physicalhost.bootstrap%3Bhandler%3DgoMachineService&eventNames=physicalhost.remove%3Bhandler%3DgoMachineService&eventNames=ping%3Bhandler%3DgoMachineService&eventNames=physicalhost.create%3Bhandler%3DgoMachineService"
time="2015-08-15T22:37:15Z" level=error msg="Unable to start EventRouter" Err="websocket: bad handshake"
time="2015-08-15T22:37:15Z" level=info msg="Exiting go-machine-service..."
time="2015-08-15T22:37:16Z" level=info msg="Setting log level" logLevel=info
time="2015-08-15T22:37:16Z" level=info msg="Starting go-machine-service..." gitcommit=102d311
time="2015-08-15T22:37:16Z" level=info msg="Initializing event router" workerCount=10
kkkkkkkkkkktime="2015-08-15T22:37:17Z" level=error msg="Failed to subscribe to events." error="websocket: bad handshake" subscribeUrl="ws://foo.com/v1/subscribe?eventNames=physicalhost.create%3Bhandler%3DgoMachineService&eventNames=physicalhost.bootstrap%3Bhandler%3DgoMachineService&eventNames=physicalhost.remove%3Bhandler%3DgoMachineService&eventNames=ping%3Bhandler%3DgoMachineService"
time="2015-08-15T22:37:17Z" level=error msg="Unable to start EventRouter" Err="websocket: bad handshake"
time="2015-08-15T22:37:17Z" level=info msg="Exiting go-machine-service..."
time="2015-08-15T22:37:18Z" level=info msg="Setting log level" logLevel=info
time="2015-08-15T22:37:18Z" level=info msg="Starting go-machine-service..." gitcommit=102d311
time="2015-08-15T22:37:18Z" level=info msg="Initializing event router" workerCount=10
time="2015-08-15T22:37:19Z" level=error msg="Failed to subscribe to events." error="websocket: bad handshake" subscribeUrl="ws://foo.com/v1/subscribe?eventNames=ping%3Bhandler%3DgoMachineService&eventNames=physicalhost.create%3Bhandler%3DgoMachineService&eventNames=physicalhost.bootstrap%3Bhandler%3DgoMachineService&eventNames=physicalhost.remove%3Bhandler%3DgoMachineService"
time="2015-08-15T22:37:19Z" level=error msg="Unable to start EventRouter" Err="websocket: bad handshake"
time="2015-08-15T22:37:19Z" level=info msg="Exiting go-machine-service..."
time="2015-08-15T22:37:20Z" level=info msg="Setting log level" logLevel=info
time="2015-08-15T22:37:20Z" level=info msg="Starting go-machine-service..." gitcommit=102d311
time="2015-08-15T22:37:20Z" level=info msg="Initializing event router" workerCount=10
t
```

**Comment by cjellick** [comment] 2015-08-27 15:25
@gregory In your logs, did you replace your domain with foo.com?
```
ws://foo.com/v1/subscribe?eventNames=physicalhost.create%3Bhandler%3DgoMachineService&eventNames=physicalhost.bootstrap%3Bhandler%3DgoMachineService&eventNames=physicalhost.remove%3Bhandler%3DgoMachineService&eventNames=ping%3Bhandler%3DgoMachineService"
time="2015-08-15T22:37:17Z" level=error msg="Unable to start EventRouter" Err="websocket: bad handshake"
```
If so, does the real value correctly have :8080 at the end of it?

**Comment by gregory** [comment] 2015-10-23 03:39
of course @cjellick :)

it does not since i started rancher server on port 80...

**Comment by gregory** [comment] 2015-10-23 03:43
```
time="2015-10-23T03:35:41Z" level=info msg="Initializing event router" workerCount=10
time="2015-10-23T03:35:41Z" level=error msg="Failed to subscribe to events." error="websocket: bad handshake" subscribeUrl="ws://foo.com/v1/subscribe?eventNames=ping%3Bhandler%3DgoMachineService
&eventNames=physicalhost.create%3Bhandler%3DgoMachineService&eventNames=physicalhost.bootstrap%3Bhandler%3DgoMachineService&eventNames=physicalhost.remove%3Bhandler%3DgoMachineService"
time="2015-10-23T03:35:41Z" level=error msg="Unable to start EventRouter" Err="websocket: bad handshake"
time="2015-10-23T03:35:41Z" level=info msg="Exiting go-machine-service..."
time="2015-10-23T03:35:42Z" level=error msg="Error during upgrade for host [22874c90-874a-4243-ab87-d20ffb981080]: [websocket: could not find connection header with token 'upgrade']"
2015/10/23 03:35:42 http: multiple response.WriteHeader calls
time="2015-10-23T03:35:42Z" level=error msg="Failed to subscribe to events." error="websocket: bad handshake" subscribeUrl="ws://foo.com/v1/subscribe?eventNames=ping%3Bhandler%3Drancher-compose-
executor&eventNames=environment.create%3Bhandler%3Drancher-compose-executor"
time="2015-10-23T03:35:42Z" level=fatal msg="Unable to start event router" error="websocket: bad handshake"
time="2015-10-23T03:35:43Z" level=error msg="Error during upgrade for host [b4e4ce12-f89e-463a-b82a-814dd5549cb4]: [websocket: could not find connection header with token 'upgrade']"
```

**Comment by cjellick** [comment] 2015-10-30 17:24
@gregory Thanks for the reply. Sorry for the delayed response. I was out last week. 

I see this in your rancher server logs:
```
time="2015-08-15T22:36:18Z" level=info msg="Starting websocket proxy. Listening on [:8080], Proxying to cattle API at [localhost:8081], Monitoring parent pid [12]."
```
which indicates rancher is running on 8080.

Can you describe your setup in a little more detail? Do you have any proxies or load balancers running in front of rancher that is listening on port 80 and forwarding to 8080? If so, can you describe them and (if possible) post the proxy configuration (with any necessary redactions).

Also, I'm adding more verbose logging to go-machine-service so that we can see that exact nature of the bad handshake. If we don't get this solved by the time that's released, that should help us track down the problem.

**Comment by cjellick** [comment] 2015-10-30 19:41
@gregory FWIW, these types of failures with go-machine-service are usually caused by some proxy or other network device sitting between go-machine-service and rancher-server that ends up blocking websocket requests.

**Comment by cjellick** [comment] 2015-12-04 17:08
Closing. We added additional logging that will allow this problem to be debugged better. Thee is nothing else that can be fixed here as the connection issues are usually on per environment basis.

**Closed by cjellick** 2015-12-04 17:08 UTC
Labels: area/machine, kind/bug
