### ISSUE TITLE
Stopping Stack Doesn't work

### ISSUE THREAD

**Issue by ronag** [rancher/rancher#3560] opened 2016-02-08 16:59 UTC
Pushing stop on  a stack doesn't do anything. Have to stop each service one at ta time.

Rancher	v0.56.1
Cattle	v0.141.1
User Interface	v0.86.0
Rancher Compose	v0.7.1

**Comment by deniseschannon** [comment] 2016-02-08 19:31
Duplicate of https://github.com/rancher/rancher/issues/3453.

What kind of services do you have?

It may actually be a duplicate of https://github.com/rancher/rancher/issues/3284

**Closed by deniseschannon** 2016-02-08 19:31 UTC
