### ISSUE TITLE
After executing a pipeline, logs do not appear for some stages sometimes

### ISSUE THREAD

**Issue by soumyalj** [rancher/rancher#19590] opened 2019-04-12 22:51 UTC
Rancher version: v2.1.8

Steps

1. Create a 3 node RKE cluster
2. Create a pipeline using a github repo
3. After executing a pipeline, logs sometimes do not appear for some stages (Log is unavailable). 
Clicking between different steps allows the logs to load occassionally

![Screen Shot 2019-04-12 at 2 11 36 PM](https://user-images.githubusercontent.com/18536626/56070015-9b823980-5d3a-11e9-865e-ea48203f7acd.png)

**Comment by soumyalj** [comment] 2019-04-15 20:16
This issue was not seen in v2.2.2

**Comment by gitlawr** [comment] 2019-05-13 01:16
Duplicate of https://github.com/rancher/rancher/issues/17079.
It is fixed in v2.2 but has not been backported in v2.1.

**Closed** 2019-05-13 01:19 UTC
Labels: [zube]: To Triage, kind/bug-qa, team/cn
