### ISSUE TITLE
Could not connect to Local Rancher Server through EC2 host. 

### ISSUE THREAD

**Issue by AjinkyaBapat** [rancher/rancher#9852] opened 2017-09-09 04:58 UTC
**Rancher versions:**
rancher/server:1.6.8

I have setup a Rancher Server on my local machine.

Added a custom host on same machine -- IT Worked

I was trying to add EC2 hosts by both ways (Through Wizard & manually by custom command through ssh from those machines)

I knew that my local IP would not be reachable so I set up a tunnel at "http://myhost.*****.me", changed the rancher server URL in UI.

If I curl "http://myhost.*****.me" from EC2 instances, it is accessible.

But somehow I am getting an error while running custom host command on those hosts.

**Results:**

sudo docker run -e CATTLE_AGENT_IP="EC2_INSTANCE_IP"  --rm --privileged -v /var/run/docker.sock:/var/run/docker.sock -v /var/lib/rancher:/var/lib/rancher rancher/agent:v1.2.6 http://myhost.*****.me/v1/scripts/5D8150914C11A1D35B64:1483142400000:18lFKUzZS1yDpuOMsaNgxI7m6Tc

INFO: Running Agent Registration Process, CATTLE_URL=http://myhost.***.me/v1
INFO: Attempting to connect to: http://myhost.***.me/v1
INFO: http://myhost.****.me/v1 is accessible
INFO: Inspecting host capabilities
INFO: Boot2Docker: false
INFO: Host writable: true
INFO: Token: xxxxxxxx
INFO: Running registration
Traceback (most recent call last):
  File "./register.py", line 11, in <module>
    secret_key=os.environ['CATTLE_REGISTRATION_SECRET_KEY'])
  File "/usr/local/lib/python2.7/dist-packages/cattle.py", line 45, in from_env
    return gdapi.from_env(prefix=prefix, factory=Client, **kw)
  File "/usr/local/lib/python2.7/dist-packages/gdapi.py", line 613, in from_env
    return _from_env(prefix=prefix, factory=factory, **args)
  File "/usr/local/lib/python2.7/dist-packages/gdapi.py", line 632, in _from_env
    return factory(**result)
  File "/usr/local/lib/python2.7/dist-packages/cattle.py", line 12, in __init__
    super(Client, self).__init__(*args, **kw)
  File "/usr/local/lib/python2.7/dist-packages/gdapi.py", line 197, in __init__
    self._load_schemas()
  File "/usr/local/lib/python2.7/dist-packages/gdapi.py", line 315, in _load_schemas
    response = self._get_response(self._url)
  File "/usr/local/lib/python2.7/dist-packages/gdapi.py", line 266, in _get_response
    self._error(r.text)
  File "/usr/local/lib/python2.7/dist-packages/gdapi.py", line 255, in _error
    raise ApiError(self._unmarshall(text))
  File "/usr/local/lib/python2.7/dist-packages/gdapi.py", line 300, in _unmarshall
    object_pairs_hook=self.object_pairs_hook)
  File "/usr/lib/python2.7/json/__init__.py", line 352, in loads
    return cls(encoding=encoding, **kw).decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded

Is there any way I can achieve this?
By "this", I mean I want my EC2 hosts to be connected to my local Rancher Server just like I have locally connected hosts.

**Comment by cjellick** [comment] 2017-09-18 16:27
`ngrok` is a great tool for doing this. I use it alsmost daily.
Note that you will have to create an account and save your authtoken locally via `ngrok authtoken`, otherwise ngrok will rate limit your requests and the hosts wont be able to connect.

**Comment by cjellick** [comment] 2017-09-18 20:21
The root cause could be that your tunnel is somehow not handling the traffic properly. In particular, we make use of websockets, which we've known to cause problems for proxies/tunnels that are not configured properly to handle then.

I'm going to close this. If you feel your question wasn't answered sufficiently, go ahead and reopen.

**Closed by cjellick** 2017-09-18 20:21 UTC
Labels: area/agent, area/server, kind/question
