### ISSUE TITLE
Error related to services/proxy when viewing metrics in Rancher UI

### ISSUE THREAD

**Issue by MKlimuszka** [rancher/rancher#40253] opened 2023-01-23 19:02 UTC
### Rancher Cluster:
**Rancher version**: 2.6.4
**Number of nodes**: 1

**Node OS version**: Ubuntu 20.04.3 LTS

### Downstream Cluster:
**Number of Downstream clusters**: 1
**Node OS**: Ubuntu 20.04.3 LTS
**RKE/RKE2/K3S version**: RKE
**Kubernetes version**: v1.20.4 
**CNI**:

### Longhorn:
**Longhorn version**:
**CPU per node**:
**Memory per node**:
**Disk type**: HDD/SSD/NVMe
**Network bandwidth between the nodes**:

### Other:
**Underlying Infrastructure**: AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal

SURE-4497

### Issue description:
When viewing cluster metrics, or metrics for a Workload pod, the following error is shown:

```
Error
services "http:rancher-monitoring-grafana:80" is forbidden: User "userID" cannot create resource "services/proxy" in API group "" in the namespace "cattle-monitoring-system"
```

### Repro steps:

1. Enable monitoring v2 on downstream cluster
1. Create a project in this downstream cluster
1. Create a namespace in this project
1. Create an nginx workload in this namespace
1. Edit the members of the project and add a user with the "Read-only" role
1. Run this in the kubectl shell for the cluster:
    ```
    kubectl create clusterrolebinding view-monitoring-ui --clusterrole=monitoring-ui-view --user=userID
    ```
1. Now this user should be able to login and explore the cluster to view cluster metrics or pod metrics under Workloads

### Workaround:
**Is workararound available and implemented?** Yes
**What is the workaround**: Add the 'create' verb to the monitoring-ui-view ClusterRole for the services/proxy resource.

### Actual behavior:
During step 7 in the repro steps, the following error is seen when the metrics are viewed:

```
Error
services "http:rancher-monitoring-grafana:80" is forbidden: User "userID" cannot create resource "services/proxy" in API group "" in the namespace "cattle-monitoring-system"
```
 
### Expected behavior:
No error should be seen

**Comment by MKlimuszka** [comment] 2023-01-23 19:03
This needs to be reproduced in 2023-Q1-2.6x, 2023-Q1-2.7x, and if it cannot be reproduced in those, 2.6.4

**Comment by stormqueen1990** [comment] 2023-02-13 22:47
This error is not related to the Rancher version, but to the cluster roles deployed with the rancher-monitoring chart. It is still reproducible with rancher-monitoring v102.0.0+up40.1.2 using the steps described above. I confirmed that adding the `create` verb to the `services/proxy` resource RBAC section solves the issue.

**Comment by sowmyav27** [comment] 2023-06-27 16:52
As per offline conversation @MKlimuszka will confirm the milestone this issue is going to be targeted for.

**Comment by vivek-shilimkar** [comment] 2023-09-04 02:50
Monitoring chart installation/upgrade is failing with following error.

`Error: UPGRADE FAILED: YAML parse error on rancher-monitoring/templates/rancher-monitoring/clusterrole.yaml: error converting YAML to JSON: yaml: line 40: did not find expected alphabetic or numeric character`

Hence, reopening the issue.

**Comment by vivek-shilimkar** [comment] 2023-09-06 06:40
Tested the issue on rancher `v2.8-head` and with monitoring version `103.0.0+up40.1.2`

**Steps followed**

1. Installed monitoring v2 on downstream cluster
2. Created a project in this downstream cluster
3. Created a namespace in this project
4. Created an nginx workload in this namespace
5. Created a standard user from Users and Authentications.
6. Edit the members of the project and add a user created in step 5 with the "Read-only" role.
7. Run this in the kubectl shell for the cluster:
`kubectl create clusterrolebinding view-monitoring-ui --clusterrole=monitoring-ui-view --user=userID`
8. Login into rancher with the user created at step 5.
9. Checked if grafana is accessible.

**Results**
Grafana page can be viewed if it is already open. 
However the Grafana page cannot be open by clicking on the link from the Rancher UI. 
![Screenshot from 2023-09-06 12-09-28](https://github.com/rancher/rancher/assets/83208989/b408eb40-5c1d-4e88-a89f-1c9ed8a3e489)


**Read-Only user member needs more permissions to open Grafana page from UI.**

@sowmyav27 @MKlimuszka  If this behaviour is acceptable we can close this issue.

**Comment by geethub97** [comment] 2023-09-11 17:24
Per the docs (https://ranchermanager.docs.rancher.com/integrations-in-rancher/monitoring-and-alerting/rbac-for-monitoring#users-with-rancher-based-permissions), this is the expected behavior: 

"A User bound to the View Monitoring Rancher Role only has permissions to access external Monitoring UIs if provided links to those UIs. In order to access the Monitoring Pane to get those links, the User must be a Project Member of at least one Project." 

If we want to update this, we would need to discuss with the UI team as that is where the requirement for project member permissions stems from.

cc: @prachidamle @MKlimuszka

**Comment by geethub97** [comment] 2023-09-13 19:35
Update: I have investigated further and this seems to be an issue within the Rancher UI. Changes I make to the verbs for the endpoints are overwritten and changing them directly from the Rancher UI causes other errors. We have raised issue with the UI team.

**Comment by sowmyav27** [comment] 2023-09-19 16:48
@ronhorton Can you pls test Step 7 from the original issue description - https://github.com/rancher/rancher/issues/40253#issue-1553605050 ?

**Comment by ronhorton** [comment] 2023-09-19 17:51
reproducing origninal issue:
<img width="763" alt="2023-09-19_13-49-43" src="https://github.com/rancher/rancher/assets/89212856/245feea1-97ab-4cc0-bee7-d3fe063a971b">

When the read-only project member logs in and goes to the cluster page, there are no metrics appearing.

I checked the rancher pod logs and found these errors:
2023/09/19 17:38:09 [INFO] [mgmt-auth-prtb-controller] Creating role/clusterRole p-rgjv7-projectmember
2023-09-19T17:38:09.457547678Z 2023/09/19 17:38:09 [INFO] [mgmt-auth-prtb-controller] Creating roleBinding for membership in project p-rgjv7 for subject u-mb7hh
2023-09-19T17:38:09.469313184Z 2023/09/19 17:38:09 [INFO] [mgmt-auth-prtb-controller] Creating clusterRoleBinding for membership in cluster c-m-h
xskdmzv for subject u-mb7hh
2023-09-19T17:38:09.477366884Z 2023/09/19 17:38:09 [INFO] [mgmt-auth-prtb-controller] Creating role read-only in namespace c-m-hxskdmzv
2023-09-19T17:38:09.488495291Z 2023/09/19 17:38:09 [INFO] [mgmt-auth-prtb-controller] Creating roleBinding for subject u-mb7hh with role read-only in namespace c-m-hxskdmzv
2023-09-19T17:38:09.496181255Z 2023/09/19 17:38:09 [INFO] [mgmt-auth-prtb-controller] Creating role read-only in namespace p-rgjv7
2023-09-19T17:38:09.509038188Z 2023/09/19 17:38:09 [INFO] [mgmt-auth-prtb-controller] Creating roleBinding for subject u-mb7hh with role read-only in namespace p-rgjv7
`2023-09-19T17:38:09.554266494Z 2023/09/19 17:38:09 [ERROR] error syncing 'p-rgjv7/prtb-8pv9f': handler auth-prov-v2-prtb: roletemplatebinding doesn't have any subject fields set: prtb-8pv9f, requeuing
2023-09-19T17:38:14.002408316Z 2023/09/19 17:38:14 [ERROR] Error during subscribe websocket: close sent`

`W0919 17:43:26.393567      33 reflector.go:456] pkg/mod/github.com/rancher/client-go@v1.27.4-rancher1/tools/cache/reflector.go:231: watch of *v1.Role ended with: an error on the server ("unable to decode an event from the watch stream: tunnel disconnect") has prevented the request from succeeding`

**Comment by geethub97** [comment] 2023-09-21 17:27
@sowmyav27 the UI issue is for: https://github.com/rancher/rancher/issues/40253#issuecomment-1707759275

UI is not needed to fix the initial bug (SURE-4497), but the error that was found after.

**Comment by ronhorton** [comment] 2023-09-26 20:16
attempted to reproduce using:
rancher:2.7.4
rancher-monitoring:102.0.0+up40.1.2

Enable monitoring v2 on downstream cluster
Create a project in this downstream cluster
Create a namespace in this project
Create an nginx workload in this namespace
Edit the members of the project and add a user with the "Read-only" role
Run this in the kubectl shell for the cluster:
kubectl create clusterrolebinding view-monitoring-ui --clusterrole=monitoring-ui-view --user=userID
Now this user should be able to login and explore the cluster to view cluster metrics or pod metrics under Workloads

No error observed; read-only user does not see metrics at bottom of cluster page.

**Comment by geethub97** [comment] 2023-09-27 00:19
@ronhorton posting a summary of our offline discussion here for cross visibility

The error shows up differently depending on what versions of Rancher and monitoring are deployed.

For context: per the docs (https://ranchermanager.docs.rancher.com/integrations-in-rancher/monitoring-and-alerting/rbac-for-monitoring#users-with-rancher-based-permissions) there are two levels of permissions for the view monitoring ui role:
- Read-Only: only has permissions to access external Monitoring UIs if provided links to those UIs (not from the Monitoring UI Pane)
- Member: can access links directly from the Monitoring Ui Pane

A User added as a Read-Only Project Member will not be able to access the links from the Monitoring Pane, which is what we see when following these steps for Rancher v2.8:

1. Deploy Rancher v2.8 on a downstream cluster.
2. Install monitoring chart version 103.0.0+up40.1.2
3. Go to the monitoring pane and save the Grafana link for later use  
4. Create a **standard user with permissions to view the monitoring UI**
5. Create a project in the downstream cluster
6. Create a namespace in the downstream cluster
7. Add the standard user from step 3 with the **Read-Only** role
8. Log in as the standard user
9. Grafana (and all the other links) on the Monitoring UI are inaccessible, but opening the link saved in step 3 and will allow the user to view the metrics. 

To reproduce the original error (https://github.com/rancher/rancher/issues/40253#issue-1553605050) in rancher v2.7.4 with an older version of monitoring (e.g. 102.0.0+up40.1.0):

1. Deploy Rancher v2.7 on a downstream cluster.
2. Install monitoring chart version 102.0.0+up40.1.2
3. Go to the monitoring pane and save the Grafana link for later use  
4. Create a **standard user with permissions to view the monitoring UI**
5. Create a project in the downstream cluster
6. Create a namespace in the downstream cluster
7. Add the standard user from step 3 with the **Read-Only role**
8. Log in as the standard user
9. Open the link from step 3 and you will get the following error: 
![image (1)](https://github.com/rancher/rancher/assets/99695266/5f2b7766-f990-4616-a515-f8e1b121a488)

**Comment by geethub97** [comment] 2023-09-27 01:22
@ronhorton posting a summary of our offline discussion here for cross visibility

The error s(https://github.com/rancher/rancher/issues/40253#issue-1553605050) hows up differently depending on what versions of Rancher and monitoring are deployed.

My understanding for the read-only view monitoring ui role (per the docs:(https://ranchermanager.docs.rancher.com/integrations-in-rancher/monitoring-and-alerting/rbac-for-monitoring#users-with-rancher-based-permissions):
- Read-Only Project Member: only has permissions to access external Monitoring UIs if provided links to those UIs (not from the Monitoring UI Pane)

A User added as a Read-Only Project Member will not be able to access the links from the Monitoring Pane, which is what we see when following these steps for Rancher v2.8 with monitoring version 103.0.0+up40.1.2 (which contains the fix for https://github.com/rancher/rancher/issues/40253#issue-1553605050): 

1. Deploy Rancher v2.8 on a downstream cluster.
2. Install monitoring chart version 103.0.0+up40.1.2
3. Go to the monitoring pane and save the Grafana link for later use  
4. Create a **standard user with permissions to view the monitoring UI**
5. Create a project in the downstream cluster
6. Create a namespace in the downstream cluster
7. Add the standard user from step 3 with the **Read-Only** role
8. Log in as the standard user
9. Grafana (and all the other links) on the Monitoring UI are inaccessible, but opening the link saved in step 3 and will allow the user to view the metrics. 

To reproduce the error (https://github.com/rancher/rancher/issues/40253#issue-1553605050) in rancher v2.7.4 with an older version of monitoring (e.g. 102.0.0+up40.1.0):

1. Deploy Rancher v2.7 on a downstream cluster.
2. Install monitoring chart version 102.0.0+up40.1.2
3. Go to the monitoring pane and save the Grafana link for later use  
4. Create a **standard user with permissions to view the monitoring UI**
5. Create a project in the downstream cluster
6. Create a namespace in the downstream cluster
7. Add the standard user from step 3 with the **Read-Only role**
8. Log in as the standard user
9. Open the link from step 3 and you will get the following error: 
![image (1)](https://github.com/rancher/rancher/assets/99695266/5f2b7766-f990-4616-a515-f8e1b121a488)

**Comment by ronhorton** [comment] 2023-09-27 15:24
**Pass** verified fixed in rancher 2.7 & 2.8 with rancher monitoring: 103.0.0+up40.1.2

Retried [test steps](https://github.com/rancher/rancher/issues/40253#issuecomment-1736229377) using
rancher:`2.7.7-rc7`
rancher monitoring: 103.0.0+up40.1.2
- no user error
- user can view metrics & grafana page

Retried [test steps](https://github.com/rancher/rancher/issues/40253#issuecomment-1736229377) using
rancher `2.8-head commit ID 5cffa89`
rancher monitoring: 103.0.0+up40.1.2
- no user error
- user can view metrics & grafana page

**Comment by ronhorton** [comment] 2023-10-02 15:05
**After a few test iterations, the update on this issue is:**
1. The bug where the user could not view the saved URLs for the grafana pages has been resolved. Ie, a read-only user can view the grafana pages by going to their url in a browser - but not from the grafana UI links on the monitoring page - correct behavior.
2. the monitoring assets at the bottom of the cluster page are not displayed - and shouldn't be - based on the user's read-only access. There are still 403 errors being observed in the console for these assets as the user correctly does not have access to them. That particular issue is being tracked in dashboard ticket https://github.com/rancher/dashboard/issues/9792 - currently in 'working'. A similar ticket was addressed by removing the calls that result in the 403 based on access level - in this case, read-only. 

**Quesitons:**
1. can this ticket be closed
2. does this ticket require a backport
3. does 9792 require a backport (as the 403 is observed in 2.7.6 as well?)

**Comment by ronhorton** [comment] 2023-10-03 17:31
Need to re-test this when https://github.com/rancher/rancher/issues/43030 (blocker) is complete and tested.

**Comment by sowmyav27** [comment] 2023-10-04 16:51
**Summary from what was discussed offline today**

There could be two different issues here
1. The issue that @geethub97 fixed which is this - https://github.com/rancher/rancher/issues/40253#issuecomment-1736525904
2. The original issue that user is facing - https://github.com/rancher/rancher/issues/40253#issue-1553605050

---

**Action Items:**
1. @ronhorton  to test the usecase that @geethub97  has fixed which is mentioned here - https://github.com/rancher/rancher/issues/40253#issuecomment-1736525904
4. @geethub97 to test how the fix behaves in 2.6.x rancher
5. @geethub97  and @prachidamle  to verify how monitoring for a User with read only permissions and  clusterrole - `monitoring-ui-view` is supposed to work. 
- - Docs - https://ranchermanager.docs.rancher.com/integrations-in-rancher/monitoring-and-alerting/rbac-for-monitoring#users-with-rancher-based-permissions _VS_
- - What User claims should work, which would be a UI bug - https://github.com/rancher/dashboard/issues/9792
7. @geethub97 @MKlimuszka @prachidamle to also confirm if these two ^ are separate issues (must track them separately)

**Comment by ronhorton** [comment] 2023-10-04 20:06
**1. reproduced issue where user cannot launch the URL for grafana and see metrics. **
`rancher v2.7.6`
`rancher-monitoring:102.0.1+up40.1.2`
1. created standard user
2. added standard user to downstream cluster as read-only project member
3. saved grafana URL
4. logged in as user1
5. went to grafana URL from step 3
result: grafana metrics did not load - all metric endopints returned 403s. 
<img width="1487" alt="2023-10-04_15-55-36" src="https://github.com/rancher/rancher/assets/89212856/75ffa1bb-37c5-40c5-82b7-0b0b0ac9d211">
<img width="345" alt="2023-10-04_15-57-54" src="https://github.com/rancher/rancher/assets/89212856/43de9600-1b54-4d65-82bd-f3c041512709">

**Comment by ronhorton** [comment] 2023-10-05 20:12
**Pass** verified fixed in `v2.8-head commit id fc12e7d`
1. created standard user
2. added standard user to downstream cluster as read-only project member
3. ran role-binding command in kubectl shell as admin on downstream cluster
4. saved grafana URL
5. logged in as user1
6. went to grafana URL from step 4

`verified on 2 different downstream ubuntu clusters`

<img width="1423" alt="2023-10-05_16-11-36" src="https://github.com/rancher/rancher/assets/89212856/d09acedd-82e3-4693-b061-7bf5fd118646">
<img width="1430" alt="2023-10-05_14-12-01" src="https://github.com/rancher/rancher/assets/89212856/97e02fb3-2016-4c48-88bf-c88968aebc29">

**Closed** 2023-10-05 20:24 UTC
Labels: kind/bug, priority/1, internal, area/monitoring, [zube]: Done, team/area3, team/infracloud, kind/docs

**Comment by prachidamle** [comment] 2023-10-05 20:43
@sowmyav27 Updates to the Action Items called out in here https://github.com/rancher/rancher/issues/40253#issuecomment-1747287448

>>> 3. @geethub97 and @prachidamle to verify how monitoring for a User with read only permissions and clusterrole - monitoring-ui-view is supposed to work.
Docs - https://ranchermanager.docs.rancher.com/integrations-in-rancher/monitoring-and-alerting/rbac-for-monitoring#users-with-rancher-based-permissions VS
What User claims should work, which would be a UI bug - https://github.com/rancher/dashboard/issues/9792

We met with Product team and have followup actions items below on this.

>>>>4. @geethub97 @MKlimuszka @prachidamle to also confirm if these two ^ are separate issues (must track them separately)

Yes these are 2 separate issues - 
- This particular ticket fixes the "[Error related to services/proxy when viewing metrics in Rancher UI](https://github.com/rancher/rancher/issues/40253#top)" by adding the Create verb
- The 403 errors noticed are a separate issue and existing since previous versions.

--------------------

Updated Action Items after talking to Product:

- @prachidamle  and @geethub97  to send a summary explaining the known limitations of read only user to Product
- Product @CamrynCarter will create a doc ticket to explain the read-only user permissions
- Product @CamrynCarter will create a UI feature request to review/fix the read-only user permissions 
- UI/Dashboard ticket opened for the 403 errors should be updated with the context that this is a unknown error and working as designed earlier - Product team would open a feature request to review how this should be fixed. - @prachidamle 

- This backend ticket https://github.com/rancher/rancher/issues/40253 to be updated with tests on 2.6.x - @geethub97 
- This backend ticket https://github.com/rancher/rancher/issues/40253 should be closed if the "Error related to services/proxy" is fixed - @ronhorton

**Comment by geethub97** [comment] 2023-10-06 00:49
Per our meeting earlier today, for a read-only user: 

1. The the 403 errors on the cluster page in the Rancher UI and the 403 errors when accessing monitoring panel links externally are two different issues.
2. The workaround support asked us to verify (adding the create verb to the services/proxy resource) fixes the issue with accessing the monitoring links externally. A read-only user cannot access those links externally without the create verb in the services/proxy resource RBAC section. 
3. We have filed several different tickets for the errors on the cluster page within the Rancher UI, but that is technically a feature request because the read-only user, by design, is not supposed to have access to the monitoring panels on the cluster page.
