### ISSUE TITLE
Error messages relating to "409 Conflict" not cleared even after the next attempt to activate services succeeded.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#7927] opened 2017-02-22 19:21 UTC
Rancher Versions: Build from master

Steps to reproduce the problem:
In my case , I was trying to create a stack by passing rancher and docker compose yml which fails with 
```Bad response statusCode [409]. Status [409 Conflict]. Body: [message=Conflict, baseType=error, code=Conflict] from [http://localhost:8080/v2-beta/projects/1a5/loadbalancerservices/1s23/?action=setservicelinks```.

This issue is tracked in https://github.com/rancher/rancher/issues/5426.

I tried to activate the stack again from UI , which succeeded. But i continue to see the ```409 Conflict]``` conflict error message in UI because of  transitioningMessage and transitioning values not being updated.

```
"transitioning": "error",
"transitioningMessage": "Bad response statusCode [409]. Status [409 Conflict]. Body: [message=Conflict, baseType=error, code=Conflict] from [http://localhost:8080/v2-beta/projects/1a5/loadbalancerservices/1s23/?action=setservicelinks]",
```
<img width="1463" alt="screen shot 2017-02-22 at 11 05 04 am" src="https://cloud.githubusercontent.com/assets/4266958/23228365/1fea48b2-f8f1-11e6-8dea-d7ced764acef.png">

**Comment by alena1108** [comment] 2017-02-23 19:02
@sangeethah is transitioning error left on the stack? or on the underlying LB service?

**Comment by sangeethah** [comment] 2017-03-01 18:58
@alena1108 , transitioning error messages are seen on the stack.

**Comment by mgmonteleone** [comment] 2017-03-15 20:42
Have same issue on 1.5.1

**Comment by alexanderdalloz** [comment] 2017-04-06 13:51
I face the same on current stable release 1.5.3 when deploying the Prometheus stack from the community catalog with action=setservicelinks:
Error (Bad response statusCode [409]. Status [409 Conflict]. Body: [baseType=error, message=Conflict, code=Conflict] from [http://localhost:8080/v2-beta/projects/1a20/services/1s192/?action=setservicelinks])
![rancher1 5 3_bad_response_statuscode409_conflict_setservicelinks](https://cloud.githubusercontent.com/assets/24923701/24757883/d16bc91a-1ae0-11e7-9adf-ac81bc5de2b8.png)

**Comment by sangeethah** [comment] 2017-05-01 19:13
This issue is not reproducible any more when testing with rancher-server 1.6.0-rc3.
Automation runs does not show these failure anymore.

**Comment by xaka** [comment] 2017-07-11 20:30
I'm on 1.6.3 and I've just got the same issue:

> Error (Bad response statusCode [409]. Status [409 Conflict]. Body: [code=Conflict, message=Conflict, baseType=error] from [http://localhost:8080/v2-beta/projects/1a5/serviceconsumemaps?serviceId=1s246])

That is after adding a new stack with 50+ services. Message doesn't go away.

**Comment by alexanderdalloz** [comment] 2017-07-18 14:42
Hi,
for us it is still an open and serious malfunction. We see statusCode 409 and statusCode 500 situations.
The deployed stacks are small, consisting just out of 2 services (either 1 Apache service and 1 MySQL+sidekick service or 1 Apache service plus 1 PostgreSQL+sidekick service). Images served by a local docker registry.
As links are broken it makes our continous deployment non reliable and has a severe impact on us.
Please reopen this ticket and help us debugging how to fix it.
![rancher_stackcreation_409_setservicelinks](https://user-images.githubusercontent.com/24923701/28323009-e93c243e-6bd7-11e7-8df2-a874a67b14ee.png)
![rancher_stackcreation_500_setservicelinks](https://user-images.githubusercontent.com/24923701/28323021-ed3fcdb0-6bd7-11e7-9dc5-a06e76534eba.jpg)

**Comment by deniseschannon** [comment] 2017-07-18 17:55
@xaka @alexanderdalloz How are you guys adding your stacks/services? Using the UI or CLI? If using CLI, what version are you using?

Note: None of these fixes are in the rancher-compose CLI. It's only available in the Rancher CLI.

**Comment by xaka** [comment] 2017-07-18 17:58
@deniseschannon in my case I always used UI

**Comment by alexanderdalloz** [comment] 2017-07-18 17:59
@deniseschannon The error occurs mainly when deploying the stack manually through the browser UI as a manual process. I do not see failed automatic deployments using rancher-compose.

**Comment by krumware** [comment] 2019-09-06 16:34
Still experiencing this on v1.6.28. Is there any way to just clear the error message? The stack is running fine, but the error sticks around.

This happens when we deploy new stacks that have services that have another stack with services of the same names. For example, redis containers named redis.

**Comment by xiaoluhong** [comment] 2020-07-29 14:04
The problem recurred today, but I'm not sure if it was caused by the same cause. 

Mysql was unable to create new connections because of the number of connections, so it was unable to write new data when creating the service.

![image](https://user-images.githubusercontent.com/20707603/88809376-a50d0a80-d1e6-11ea-97b5-145c1cc7db34.png)

`SHOW STATUS WHERE variable_name LIKE "Threads_%" OR variable_name = "Connections"`

![image](https://user-images.githubusercontent.com/20707603/88809416-b0f8cc80-d1e6-11ea-9e2f-06e5251070ff.png)

Now, I need to know why are there so many connections.

**Comment by deniseschannon** [comment] 2020-12-22 05:13
As 1.6 is EOL as of June 30, 2020, we are closing 1.6 issues.

**Closed by deniseschannon** 2020-12-22 05:13 UTC
Labels: [zube]: To Triage, internal, kind/bug, version/1.6
