### ISSUE TITLE
[BUG] rke2-agent config using down control plane node

### ISSUE THREAD

**Issue by poblahblahblah** [rancher/rancher#41375] opened 2023-05-02 16:52 UTC
**Rancher Server Setup**
- Rancher version: 2.7.2
- Installation option (Docker install/Helm Chart):  Helm
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): RKE2
- Proxy/Cert Details:

**Information about the Cluster**
- Kubernetes version: 1.25.x
- Cluster Type (Local/Downstream): Custom RKE2
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider):

**User Information**
- What is the role of the user logged in? (Admin/Cluster Owner/Cluster Member/Project Owner/Project Member/Custom)
  - If custom, define the set of permissions: Admin

**Describe the bug**

One of our control plane nodes (IP: 10.118.192.12) is down due to hardware issues. While it's been down we have been unable to have new nodes (workers or control-planes) join the cluster.

This is the log rke2-agent.service that repeated:

```
May 02 16:38:38 worker100 rke2[37489]: time="2023-05-02T16:38:38Z" level=error msg="failed to get CA certs: Get \"https://127.0.0.1:6444/cacerts\": read tcp 127.0.0.1:57772->127.0.0.1:6444: read: connection reset by peer"
```

After doing some digging it looks like this is a local proxy that proxies the connection to a control-plane node.

This is the contents of `/etc/rancher/rke2/config.yaml.d/50-rancher.yaml`:

```
{
  "node-label": [
    "cattle.io/os=linux",
    "rke.cattle.io/machine=9a4c5a3c-7a56-4cf6-8534-00455de1d4cc"
  ],
  "server": "https://10.118.192.12:9345",
  "token": "<SNIP>"
}
```

Notice that the server it hands out is the downed control-plane node.

Once I manually updated that file to point to a healthy control-plane node the worker was able to join the cluster.

This might belong in the rke2 project. Apologies if it does.

**To Reproduce**

1. Create a cluster
2. Figure out which control-plane node gets set in `/etc/rancher/rke2/config.yaml.d/50-rancher.yaml` by default
3. Attempt to have nodes join the cluster

**Result**

Obtuse failure

**Expected Result**

The nodes should join the cluster. The `server` key should be set to an active and healthy control-plane node _or_ we should be able to set this to a DNS name that points to a load balancer so that traffic can be distributed to healthy control-plane nodes.

**Screenshots**

**Additional context**

**Comment by poblahblahblah** [comment] 2023-05-02 17:07
One workaround for this would be to have your OS provisioning system put a file into `/etc/rancher/rke2/config.yaml.d/` with the following content:

```
{
  "server": "https://control-plane-load-balancer:9345"
}
```

**Comment by snasovich** [comment] 2023-06-26 18:36
@jakefhyde , is this essentially https://github.com/rancher/rancher/issues/39021 (or very much part of it)?

**Comment by snasovich** [comment] 2023-07-13 19:57
Closing as duplicate of #39021 based on 👍 from @jakefhyde to the comment above.

**Closed by snasovich** 2023-07-13 19:57 UTC
Labels: kind/bug, [zube]: Release Candidates, team/area2
