### ISSUE TITLE
Kubernetes deployments for infra cannot pull image from private docker registry if default registry is set in advanced settings

### ISSUE THREAD

**Issue by hiscal2015** [rancher/rancher#7988] opened 2017-02-28 11:52 UTC
**Rancher Versions:** 1.4.1

**Docker Version:** 1.12.6

**OS and where are the hosts located? (cloud, bare metal, etc):** Ubuntu 16.04

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)** single

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)** Kubernetes

**Steps to Reproduce:**

1) set default registry from advanced settings, eg reg.example.com
2) create a new kubernetes environment and add hosts
3) basic infrastructure containers can be successfully created, images were pulled by prefix reg.example.com, e.g. reg.example.com/rancher/k8s:v1.5.2-rancher, but failed to start below pods since they are trying to pull images from gco.io or docker hub:

user@server:$ kubectl get pods --namespace=kube-system
NAME                                    READY     STATUS              RESTARTS   AGE
heapster-3467702493-f4dkl               0/1       ContainerCreating   0          3h
influxdb-grafana-876329878-8j9dc        0/2       ContainerCreating   0          3h
kube-dns-1208858260-30rv5               0/4       ContainerCreating   0          3h
kubernetes-dashboard-2492700511-trnz5   0/1       ContainerCreating   0          3h
tiller-deploy-3991468440-m1p0v          0/1       ContainerCreating   0          3h

4) rancher-agent container(not the one to add hosts) started with images pulled from docker hub but not from private registry as well.

Is this a bug?

**Comment by tfiduccia** [comment] 2017-02-28 18:46
@hiscal2015 Did you add the registry in the Add Registry page as well?  It still has to be there so that it can verify your credentials.

**Comment by hiscal2015** [comment] 2017-02-28 19:01
@tfiduccia I have set anyone can pull images from my repos without authentication, Do I still have to add it to Add Registry page?

**Comment by tfiduccia** [comment] 2017-02-28 19:03
@hiscal2015 - Yes

**Comment by hiscal2015** [comment] 2017-03-01 01:56
@tfiduccia Still not work

rancher/agent:v1.2.0 pulled from docker hub and google containers were trying to pull from gcr.io not my private registry.

CONTAINER ID        IMAGE                                                       COMMAND                  CREATED             STATUS                      PORTS               NAMES
99cd48a7b271        reg.example.com/rancher/network-manager:v0.4.5   "/rancher-entrypoint."   7 seconds ago       Up 7 seconds                                    r-network-services-network-manager-6-20c2f8c9
845801be50e2        rancher/agent:v1.2.0                                        "/run.sh run"            19 seconds ago      Up 18 seconds                                   rancher-agent
1bd221b624f3       reg.example.com/rancher/agent:v1.2.0             "/run.sh https://ranc"   35 seconds ago      Exited (0) 25 seconds ago                       ecstatic_bassi


$ kubectl get pods --namespace=kube-system
NAME                                    READY     STATUS              RESTARTS   AGE
heapster-3467702493-bm49c               0/1       ContainerCreating   0          1m
influxdb-grafana-876329878-0fgzg        0/2       ContainerCreating   0          1m
kube-dns-1208858260-77hv7               0/4       ContainerCreating   0          1m
kubernetes-dashboard-2492700511-k4zvg   0/1       ContainerCreating   0          1m
tiller-deploy-3991468440-vgtxb          0/1       ContainerCreating   0          1m


Events:
  FirstSeen	LastSeen	Count	From							SubObjectPath	Type		Reason		Message
  ---------	--------	-----	----							-------------	--------	------		-------
  3m		3m		1	{default-scheduler }							Normal		Scheduled	Successfully assigned heapster-3467702493-bm49c to host1
  3m		3m		1	{kubelet host1}			Warning		FailedSync	Error syncing pod, skipping: failed to "StartContainer" for "POD" with ErrImagePull: "image pull failed for gcr.io/google_containers/pause-amd64:3.0, this may be because there are no credentials on this request.  details: (Error response from daemon: {\"message\":\"Get https://gcr.io/v1/_ping: dial tcp 108.177.97.82:443: i/o timeout\"})"

**Comment by deniseschannon** [comment] 2017-03-01 18:52
This is a known issue that will be addressed in 1.5. 

Duplicate of https://github.com/rancher/rancher/issues/7362

**Closed by deniseschannon** 2017-03-01 18:52 UTC
