### ISSUE TITLE
kubectl cannot communicate with k8s api server if LDAP is enabled

### ISSUE THREAD

**Issue by wlan0** [rancher/rancher#7316] opened 2017-01-05 19:46 UTC
**Rancher Versions:**
Server: v1.2.2

Steps:
1. Start k8s
2. Enable LDAP
3. Execute remote kubectl commands

Expected:

kubectl commands work correctly

Actual Results:

kubectl commands fail with "Service Unavailable" error

**Comment by deniseschannon** [comment] 2017-01-11 22:17
@tfiduccia Can you please test to see if the new k8s template in v1.3.1-rc2 addresses this issue?

**Comment by tfiduccia** [comment] 2017-01-11 23:06
Version 1.2.2
Sid, I am unable to reproduce this in version 1.2.2.  I created a kubernetes environment, after it was all active, I enabled LDAP and then went to my terminal and ran kubectl get node and it worked just find.

**Comment by alena1108** [comment] 2017-01-23 19:21
@wlan0 confirmed with @tfiduccia - the test was attempted via remote kubectl client

**Comment by galal-hussein** [comment] 2017-01-25 17:17
cannot reproduce, closing. Will reopen if issue is reported again.

**Closed by galal-hussein** 2017-01-25 17:17 UTC
Labels: kind/bug, status/to-test
