### ISSUE TITLE
[BUG] Rancher container is stuck in updating on Ubuntu 22.04

### ISSUE THREAD

**Issue by thaneunsoo** [rancher/rancher#39072] opened 2022-09-21 22:27 UTC
**Rancher Server Setup**
- Rancher version: v2.6-head 
- Installation option (Docker install/Helm Chart): Docker
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc):
- Proxy/Cert Details: 

**Information about the Cluster**
- Kubernetes version:
- Cluster Type (Local/Downstream):
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider):

**User Information**
- What is the role of the user logged in? (Admin/Cluster Owner/Cluster Member/Project Owner/Project Member/Custom)
  - If custom, define the set of permissions:

**Describe the bug**

After doing a docker install of rancher, the rancher container seems to be stuck in updating as seen below
```
2022/09/21 21:58:08 [INFO] Watching metadata for k3s.cattle.io/v1, Kind=Addon
2022/09/21 21:58:08 [INFO] Watching metadata for storage.k8s.io/v1, Kind=StorageClass
2022/09/21 21:58:08 [INFO] Watching metadata for management.cattle.io/v3, Kind=ClusterMonitorGraph
2022/09/21 21:58:08 [INFO] Watching metadata for rke-machine.cattle.io/v1, Kind=VmwarevsphereMachine
2022/09/21 21:58:08 [INFO] Watching metadata for management.cattle.io/v3, Kind=Setting
2022/09/21 21:58:08 [INFO] Watching metadata for management.cattle.io/v3, Kind=ManagedChart
2022/09/21 21:58:08 [INFO] Watching metadata for rke-machine.cattle.io/v1, Kind=Amazonec2Machine
2022/09/21 21:58:08 [INFO] Watching metadata for management.cattle.io/v3, Kind=ProjectCatalog
2022/09/21 21:58:08 [INFO] Watching metadata for /v1, Kind=PodTemplate
2022/09/21 21:58:08 [INFO] Watching metadata for fleet.cattle.io/v1alpha1, Kind=ImageScan
2022/09/21 21:58:08 [INFO] Watching metadata for cluster.x-k8s.io/v1beta1, Kind=MachineHealthCheck
2022/09/21 21:58:08 [INFO] Watching metadata for apps/v1, Kind=Deployment
2022/09/21 21:58:08 [INFO] Watching metadata for management.cattle.io/v3, Kind=ProjectRoleTemplateBinding
2022/09/21 21:58:08 [INFO] Watching metadata for rbac.authorization.k8s.io/v1, Kind=Role
2022/09/21 21:58:08 [INFO] Watching metadata for networking.k8s.io/v1, Kind=NetworkPolicy
2022/09/21 21:58:11 [INFO] kontainerdriver amazonelasticcontainerservice listening on address 127.0.0.1:41937
2022/09/21 21:58:11 [INFO] kontainerdriver amazonelasticcontainerservice stopped
2022/09/21 21:58:11 [INFO] dynamic schema for kontainerdriver amazonelasticcontainerservice updating
2022/09/21 21:58:11 [INFO] kontainerdriver googlekubernetesengine listening on address 127.0.0.1:44377
2022/09/21 21:58:11 [INFO] kontainerdriver googlekubernetesengine stopped
2022/09/21 21:58:11 [INFO] dynamic schema for kontainerdriver googlekubernetesengine updating
2022/09/21 21:58:11 [INFO] kontainerdriver azurekubernetesservice listening on address 127.0.0.1:36859
2022/09/21 21:58:11 [INFO] kontainerdriver azurekubernetesservice stopped
2022/09/21 21:58:11 [INFO] dynamic schema for kontainerdriver azurekubernetesservice updating
```

**To Reproduce**

1. On Ubuntu 22.04 instance install Rancher using docker

**Result**
Rancher is not successfully installed and the container seems to be stuck in updating, similar to this [issue ](https://github.com/rancher/rancher/issues/35330)

**Expected Result**

Rancher container should be running successfully with rancher running

**Comment by kinarashah** [comment] 2022-09-27 21:03
Tried reproducing this issue multiple times, but unable to reproduce with `rancher/rancher:v2.6-head` (`2e0026699`). Steps I used: 
- Provision an ubuntu 22.04 instance in ec2 
```
# cat /etc/os-release
PRETTY_NAME="Ubuntu 22.04.1 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.1 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=jammy
```
- Install docker via `apt install docker.io`
```
# docker info
Client:
 Context:    default
 Debug Mode: false

Server:
 Containers: 1
  Running: 1
  Paused: 0
  Stopped: 0
 Images: 1
 Server Version: 20.10.12
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 
 runc version: 
 init version: 
 Security Options:
  apparmor
  seccomp
   Profile: default
  cgroupns
 Kernel Version: 5.15.0-1019-aws
 Operating System: Ubuntu 22.04.1 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 8
 Total Memory: 31.35GiB
 Name: ip-172-31-6-49
 ID: DX3Q:JKHH:PNTS:KD6S:7O4P:ADLF:IWTX:3Y4X:VQ3C:T5XF:46IQ:VL4P
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```
- Installed `rancher/rancher:v2.6-head` 
- Able to access rancher server URL and login successfully.

**Comment by kinarashah** [comment] 2022-09-27 21:34
I also tried provisioning 1 node each role RKE1 and RKE2 clusters, and both came up fine. Moving this issue to test.

**Comment by thaneunsoo** [comment] 2022-10-04 16:46
### Test Environment: ###
Rancher version: v2.6-head 998d8d7
Rancher cluster type: single-node docker install
Docker version: 20.10

----------

### Testing: ###

Tested this issue with the following steps:
1. On Ubuntu 22.04 instance install Rancher using docker
2. Provision RKE1 cluster
3. Provision RKE2 cluster

**Result** - Pass
Rancher container is running successfully and RKE1 and RKE2 clusters also come up fine as well.
![image.png](https://zube.io/files/rancher/ca5e4d899465efc3e6fe3c00ea7b6449-image.png)

![image.png](https://zube.io/files/rancher/88ed2555b8632ddfdda31da421188c4d-image.png)

![image.png](https://zube.io/files/rancher/297da06a99e1b7c21c22284576715bde-image.png)

**Closed** 2022-10-04 16:46 UTC
Labels: kind/bug, [zube]: QA Working, QA/XS, team/area2
