### ISSUE TITLE
Deleting pod in pod view does not refresh page

### ISSUE THREAD

**Issue by superseb** [rancher/rancher#12498] opened 2018-04-04 19:06 UTC
**Rancher versions:**
rancher/server: v2.0.0-alpha26

**Steps to Reproduce:**
- Open a pod view in the UI (URL: `p/cluster-pdsk9:project-jrzcp/workloads/nginx:nginx-hnq6n`)
- Delete the pod using the menu

**Results:**
Pod delete action is executed, page is not refreshed.

**Comment by tfiduccia** [comment] 2018-04-11 18:10
Version - 2.0 master 4/11
This is not fixed and if I refresh the browser manually it takes me to a 400 page

**Comment by kinarashah** [comment] 2018-06-13 17:19
@loganhz, in the latest master, 
I see API returning 200 status code, 
and in Response, the object with `state:removing`. 
After it gets removed, I also see status `removed`. Since it's already removed, after this point, I see `404` error on page refresh. 
I think this is expected behavior ? 

![image](https://user-images.githubusercontent.com/16870565/41367222-409979f6-6ef3-11e8-931d-fa6c1538b3a7.png)

**Comment by loganhz** [comment] 2018-06-13 17:22
Yes! Thanks

**Comment by sangeethah** [comment] 2018-06-15 02:01
Tested with master build from jun 13. 
When deleting pods from pod view ( "https://<ip>/p/c-h2q6p:project-qgslc/workloads/default:test1-dd9f798c6-5knnf" ) , pod status gets to "Removing" and then "Removed" state.

When refreshing this page , user is to taken to "404 Not found" page which is as expected since the pods does not exist anymore 

<img width="405" alt="screen shot 2018-06-14 at 6 57 19 pm" src="https://user-images.githubusercontent.com/4266958/41446528-e0eabe8a-7004-11e8-9821-4b4b2d49a883.png">

Can UI do anything better here ?

Also when in pods are in "Removed" state , "View Logs/View in API/Delete" options are shown which should not be the case.

Reopening this issue to get this addressed.

**Comment by loganhz** [comment] 2018-06-17 01:17
Talked to Vince. Please remove the actions in availableActions in backend if it should not be in the menu.

**Comment by deniseschannon** [comment] 2018-08-17 21:40
@kinarashah can you figure out what needs to be done with @loganhz?

**Comment by kinarashah** [comment] 2018-09-04 21:30
@loganhz  based on @vincent99's last comment, I don't think backend needs any changes? could you let me know what is the expected output here?

**Comment by alena1108** [comment] 2018-09-04 23:58
@loganhz could you check if it's something that can be fixed on the UI side

**Comment by loganhz** [comment] 2018-09-05 00:03
This has been fixed. It will go back to list once the state of the pod is removed.

**Comment by alena1108** [comment] 2018-09-11 21:59
@carolynhu to validate

**Comment by carolynhu** [comment] 2018-09-13 03:42
Tested with the latest master (9/12), same steps as what kinara and sangeetha did. Same issue. Reassigned it to @loganhz.

**Comment by loganhz** [comment] 2018-09-13 05:42
If a pod is a standalone pod, it will jump to workload list page when pod is removed.

If not, it will jump to workload detail page when pod is removed

![sep-13-2018 13-37-13](https://user-images.githubusercontent.com/21168270/45469141-ddbeaa80-b75a-11e8-9ab9-de00efa7516f.gif)

**Comment by westlywright** [comment] 2018-09-13 17:28
@carolynhu the new changes are in latest2, can you retest?

**Comment by carolynhu** [comment] 2018-09-13 19:04
Steps to validate:
1. Create a DigitalOcean Cluster `carolyntest`
2. Create a workload named `myworkload` under `Default`
3. Go to pods within `myworkload`, and delete it. Pods status from `Running` to `Removing` then come back to `myworkload` page.
4. Create a standalone pod, ` kubectl --kubeconfig  kube.config apply -f pod.yaml`.
5. Go to this standalone pod and delete it. All the deletion process is in workload list page.

All things works as expected.

**Closed by carolynhu** 2018-09-13 19:04 UTC
Labels: area/ui, area/workload, kind/bug, priority/1, status/resolved, status/to-test, team/ca, version/2.0
