### ISSUE TITLE
Global DNS UI: page should not be shown unless on HA

### ISSUE THREAD

**Issue by davidnuzik** [rancher/rancher#17558] opened 2019-01-23 23:40 UTC
Version: 2.2 master (1/22/19)

**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
- Have a single-node rancher install notice you can see Global DNS on the top nav bar even though this is only supported today with HA setup.

**Result:**
User can see page they should not be able too since we don't support global DNS on non-ha today.

**Comment by alena1108** [comment] 2019-01-24 00:38
@westlywright I'm not sure though if there is a way for the UI to know about whether the setup is local or HA...

**Comment by davidnuzik** [comment] 2019-01-24 00:43
Would this be inappropriate? Just throwing this out there
if exist: "local" cluster AND if exist: "cattle-global-data" ns on that cluster then, is (probably) HA

**Comment by alena1108** [comment] 2019-03-08 23:14
@davidnuzik @sangeethah with the final design, Global DNS should be enabled only on the setups having a local cluster. That means it won't be disabled on HA if addLocal is passed as false on helm install. 

@sangeethah feel free to close as a duplicate of https://github.com/rancher/rancher/issues/18603

**Comment by sangeethah** [comment] 2019-03-08 23:16
Validation for this issue is tracked in https://github.com/rancher/rancher/issues/18603#issuecomment-471093906

**Closed** 2019-03-08 23:15 UTC
Labels: area/ui, kind/bug-qa, priority/2, status/resolved, status/to-test, team/az, version/2.0
