### ISSUE TITLE
backup getting very big over time, because of helm cache

### ISSUE THREAD

**Issue by XzenTorXz** [rancher/rancher#19440] opened 2019-04-08 12:48 UTC
**What kind of request is this (question/bug/enhancement/feature request):**
enhancement

**Steps to reproduce (least amount of steps as possible):**
create a backup (or preparation for update) like stated in the docs:
`docker run  --volumes-from rancher-data -v $PWD:/backup alpine tar zcvf /backup/rancher-data-backup-<RANCHER_VERSION>-<DATE>.tar.gz /var/lib/rancher`

**Result:**

the resulting zip will grow in size quickly 

**Environment information**
- Rancher version: tested on 2.1.8 and 2.1.4
- Installation option (single install/HA): single install

When looking into the zip you have a cache history `var/lib/rancher/management-state/catalog-controller/cache/helm/` for the complete helm catalog, that is 8GB (in our case around 2500 Versions of the helm `index.yaml`)

**Comment by superseb** [comment] 2019-04-08 12:54
This is a duplicate of https://github.com/rancher/rancher/issues/18594, and is fixed in 2.2 here https://github.com/rancher/rancher/pull/17596

**Closed by superseb** 2019-04-08 12:54 UTC
