### ISSUE TITLE
Editing a roletemplate to add new rules does not grant expected permissions to users with that role

### ISSUE THREAD

**Issue by mrajashree** [rancher/rancher#28094] opened 2020-07-27 17:31 UTC
1. On 2.4.5 create a project scoped role `cloned-project-owner` by cloning project-owner
2. Add a user `testuser` with this `cloned-project-owner` role to a project
3. The `testuser` can enable project monitoring and edit project resource quota 
4. Upgrade to 2.4-head.
5. The builtin project-owner role will have a new rule for the resource "project" with verb "own" that gives it ownership. The cloned role `cloned-project-owner` will not have this rule upon upgrade.
6. Edit `cloned-project-owner` through API to add the same rule as the project-owner for "own" verb on "project" resource.
7. On editing the roletemplate, its corresponding k8s role in the project's namespace also gets updated to have this new rule
7. Login as `testuser`.

**Result**
testuser cannot enable monitoring or edit project resource quota

**Expected**
testuser should be able to perform everything a project-owner can, including monitoring actions and editing project quota

**Other details that may be helpful:**
The corresponding kubernetes role in the project's namespace gets updated as expected. And the rolebinding for this user binding it to the k8s role is intact upon upgrade. So this should have given the `testuser` expected permissions

gzrancher/rancher#9345

**Comment by ryansann** [comment] 2020-08-12 01:06
This issue has been hard to track down. I am still actively working on it, and wanted to provide an update with my findings so far. The issue is not related to the changes that @mrajashree made having to do with project owner permissions. I was able to reproduce the same issue in Rancher `v2.4.5` by adding and removing the inherited `Project Owner` role template to the `cloned-project-owner` role template. I also ran the same test in Rancher `v2.3.8` and did not find this issue happening. We were not using the `membershipBindingOwnerIndex` in that version and were directly retrieving RoleBindings from the api-server as opposed to using Kubernetes caching mechanisms as we have from `v2.4.0` onward.

These findings along with debugging I have done point to interactions with the `membershipBindingOwnerIndex` being the issue. In the steps to reproduce found above, prior to upgrade the user has a `projectowner` RoleBinding. After the upgrade is completed, the `projectowner` RoleBinding is deleted and a `projectmember` RoleBinding is created. This is due to the difference in project owner logic between the two versions. To grant the user project owner permissions, the `project+own` permissions need to be added to the `cloned-project-owner` role template after upgrading (via the API). However, this doesn't have the desired effect and the user is still unable to administer the project. The reason for this has to do with a stale key in the `membershipBindingOwnerIndex`. The `projectowner` RoleBinding is deleted at this point, but the indexer still maintains a key for that RoleBinding in the `membershipBindingOwnerIndex`. The RoleBinding returned for this key is `nil` and the controller errors out attempting to process it. The error happens on this line: https://github.com/rancher/rancher/blob/v2.4.6-rc1/pkg/controllers/management/auth/manager.go#L337

I have implemented a workaround that allows for the correct user experience, but does not fix the stale key issue. I will be opening a PR for this workaround as I have not found the root cause at this point.

**Comment by sowmyav27** [comment] 2020-08-14 23:35
Verified on an upgrade from 2.4.5 to 2.4-head - commit id: ``

**Scenario#1**

- On 2.4.5 create a project scoped role cloned-project-owner by cloning project-owner
- Add a user user1 with this cloned-project-owner role to a project
- The user1 can enable project monitoring and edit project resource quota
- Upgrade to 2.4-head.
- The builtin project-owner role will have a new rule for the resource "project" with verb "own" that gives it ownership. The cloned role cloned-project-owner will not have this rule upon upgrade.
- Edit cloned-project-owner through API to add the same rule as the project-owner for "own" verb on "project" resource.
- Login as user1.
- user1 is able to enable monitoring and edit project resource quota

**Comment by ryansann** [comment] 2020-08-18 17:19
@sowmyav27 thank you for the feedback. I've ran further tests and have noticed some issues with Scenario 2. Specifically, when you clone the `cluster-owner` role to create `cloned-cluster-owner`, and use that to associate a user to a cluster, the user/rbac controller is not treating the cloned role as an owner role. What ends up happening is an error like this:
```
2020/08/17 16:17:20 [ERROR] ClusterRoleTemplateBindingController c-l9gcq/crtb-784n6 [cluster-crtb-sync] failed with : couldn't ensure roles: couldn't update role rt-ph5d5: couldn't update role rt-ph5d5 in c-l9gcq: Role.rbac.authorization.k8s.io "rt-ph5d5" is invalid: rules[0].nonResourceURLs: Invalid value: []string{"*"}: namespaced rules cannot apply to non-resource URLs
```
The cloned role has a rule:
```
- nonResourceURLs:
  - '*'
  verbs:
  - '*'
```
which can't be applied to namespaced roles. Since the `cloned-cluster-owner` is not detected as an owner role, Rancher attempts to create/update namespaced roles with the rule above, which is invalid. 

I have not yet determined whether the logic in the user/rbac controller for detecting the cluster owner role needs to change, or if this is more of a user error, where we are providing invalid rules to role templates that will result in the creation of namespaced roles. In either case, this problem is unrelated to the original issue. From my testing, the original issue appears to be solved as the behavior is correct now. I think we can close this issue and handle this problem with the `cloned-cluster-owner` in a separate issue. Let me know if you agree.

**Comment by sowmyav27** [comment] 2020-08-19 23:55
**Verified on 2.4-head - commit id: `546423c42`**

**Steps:**

- On 2.4.5 create a cluster scoped role cloned-cluster-owner by cloning cluster-owner
- Add a user user2 with this cloned-cluster-owner role to a cluster
- The user2 can enable cluster level monitoring
- Upgrade to 2.4-head.
- The builtin cluster-owner role will have a new rule for the resource "clusters" with verb "own"
- Edit cloned-cluster-owner through API to add the same rule as the cluster-owner for "own" verb on "clusters" resource.
- Login as user2.
- user2 is able to enable cluster level monitoring but it took sometime for the update of "own" verb to propagate to the user2. It took > 3 minutes for the user to perform cluster level actions like - Run CIS scan/Enable cluster level monitoring
- Rancher Logs still shows error
```
2020/08/19 22:57:41 [ERROR] ClusterRoleTemplateBindingController c-cqwt4/crtb-j572z [cluster-crtb-sync] failed with : couldn't ensure roles: couldn't update role rt-4pwmn: couldn't update role rt-4pwmn in c-cqwt4: Role.rbac.authorization.k8s.io "rt-4pwmn" is invalid: rules[0].nonResourceURLs: Invalid value: []string{"*"}: namespaced rules cannot apply to non-resource URLs
```

**Comment by sowmyav27** [comment] 2020-08-24 21:57
**Verified using 2.4-head - commit id: `03ce40e37`**

- On 2.4.5 create a cluster scoped role cloned-cluster-owner by cloning cluster-owner
- Add a user user2 with this cloned-cluster-owner role to a cluster
- The user2 can enable cluster level monitoring
- Upgrade to 2.4-head.
- The builtin cluster-owner role will have a new rule for the resource "clusters" with verb "own"
- Edit cloned-cluster-owner through API to add the same rule as the cluster-owner for "own" verb on "clusters" resource.
- Login as user2.
- User 2 is able to enable cluster monitoring and run CIS scan on the cluster (immediately with no delay)

Master fix for the latest PR will be validated in this issue -  https://github.com/rancher/rancher/issues/28056

**Closed by sowmyav27** 2020-08-24 21:57 UTC
Labels: [zube]: To Test, kind/bug-qa
