### ISSUE TITLE
Rancher 2.6.2 - deletion of imported downstream RKE2 cluster with CIS profile has stuck "cattle-cleanup" with CreateContainerConfigError

### ISSUE THREAD

**Issue by Martin-Weiss** [rancher/rancher#35384] opened 2021-11-05 12:52 UTC
**Rancher Server Setup**
- Rancher version: 2.6.2
- Installation option (Docker install/Helm Chart):
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): 1.20.12-rke2r1
- Proxy/Cert Details: cert-manager

**Information about the Cluster**
- Kubernetes version: 1.20.12 rke2
- Cluster Type (Local/Downstream): downstream / importer RKE2 with CIS profile 1.6 
   (PSP and Networkpolicies are enabled)
- Infrastructure Provider = vsphere

**Describe the bug**
After deletion of downstream cluster from Rancher I can see this:

```
kubectl get pods
NAME                         READY   STATUS                       RESTARTS   AGE
cattle-cleanup-5bwnw-spnwp   0/1     CreateContainerConfigError   0          18m

```

```
kubectl describe pod cattle-cleanup-5bwnw-spnwp
Name:         cattle-cleanup-5bwnw-spnwp
Namespace:    default
Priority:     0
Node:         rke-test-worker-02/10.101.1.22
Start Time:   Fri, 05 Nov 2021 13:26:47 +0100
Labels:       controller-uid=c89ec52e-bbd1-46af-a8ed-ade4d516b2bf
              job-name=cattle-cleanup-5bwnw
Annotations:  kubernetes.io/psp: global-restricted-psp

  Warning  Failed     20m (x8 over 22m)    kubelet            Error: container has runAsNonRoot and image will run as root (pod: "cattle-cleanup-5bwnw-spnwp_default(77e35a5e-7605-4bb2-90bd-5c4f784f3bbb)", container: cleanup-agent)

```

**To Reproduce**
remove downstream cluster -> cause "cattle-cleanup job" to be created with PSP enabled in RKE2

**Result**
see above

**Expected Result**
pod runs as expected and does not fail with configerror

**Additional context**
It seems that the clusterrole -> ClusterRole/cattle-cleanup-zqtdq does not add the rights to use the PSP system-unrestricted-psp

**Comment by pwurbs** [comment] 2022-01-04 10:39
I agree to the additional context. In my case the creation of a pod for the cattle-node-cleanup job failed with Rancher 2.6.3.
`Error creating: pods "cattle-node-cleanup-8nx54-" is forbidden: PodSecurityPolicy: unable to admit pod: [spec.volumes[0]: Invalid value: "hostPath": hostPath volumes are not allowed to be used]`
I use a more restrictive standard PSP in the cluster which prohibits the usage of a hostPath volume.
The job should use a specific service account which to which the unrestricted PSP is bound.

**Comment by a-blender** [comment] 2023-03-14 16:03
This is a duplicate of https://github.com/rancher/rancher/issues/36006

**Comment by slickwarren** [comment] 2024-01-23 00:07
closing as a duplicate based on the last comment

**Closed by slickwarren** 2024-01-23 00:07 UTC
Labels: kind/bug, area/rke2, [zube]: QA Next up, QA/M, team/area2
