### ISSUE TITLE
Incorrect upgradable version shown on the helm v3 apps deployed from legacy partner apps

### ISSUE THREAD

**Issue by anupama2501** [rancher/rancher#36319] opened 2022-01-28 22:16 UTC
Note: This ticket needs an RC while validating

**Rancher Server Setup**
- Rancher version: 2.6.3 & 2.6.3-patch1-rc3
- Installation option (Docker install/Helm Chart): `v1.21.7`
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): RKE1
- Proxy/Cert Details:

**Information about the Cluster**
- Kubernetes version:  v1.21.7
- Cluster Type (Local/Downstream): DO infrastructure RKE1 1 etcd+ cp, 1 worker
   

**User Information**
- What is the role of the user logged in? (Admin/Cluster Owner/Cluster Member/Project Owner/Project Member/Custom)
  Admin

**Describe the bug**
This was found while testing an apps migration scenario. If we install an helm3 v1 app on ember UI [rancher max version set to 2.6.3] eg., aws-event-sources and then from explorer --> apps & market place, the app displays an incorrect upgradable version of the app.

**To Reproduce**

- In 2.6.2 rancher, enabled legacy feature flag
- installed aws-event-sources version:0.1.1 from legacy --> project --> select default namespace in the downstream cluster
- upgraded to 2.6.3 or 2.6.3-patch1
- Navigate to Apps & Marketplace on the downstream cluster > Installed apps

**Result**
An incorrect upgradable version `0.1.901` is shown on the app `aws-event-sources`.

**Expected Result**
The version that is available in the app is expected to be displayed.

**Screenshots**

<img width="500" alt="2022-01-28_14-08-50 (1)" src="https://user-images.githubusercontent.com/38144301/151628386-81ddda19-ee7a-4446-8005-8335b20ab751.png">

**Additional context**
Should be verified for migration steps as well:
Migration steps:

- From cluster --> default project --> apps, install the app AWS-event-sources, version 0.1.1 - app1 from ember UI
```
Add helm3 repository in the apps & market -> repositories: name: helm3-library | URL: https://git.rancher.io/helm3-charts | Branch: master from vue UI
 kubectl get apps -A | grep aws-event-sources
kubectl edit app aws-event-sources -n aws-event-sources
```
- add annotations under spec.chart.metadata.annotations
```
catalog.cattle.io/ui-source-repo: helm3-library
catalog.cattle.io/ui-source-repo-type: cluster
apps.cattle.io/migrated: "true"
```
- From the local cluster
- kubectl get apps.project.cattle.io -A | grep aws
- kubectl edit apps.project.cattle.io aws-event-sources -n p-mr57l<namespaceID of the app> and add the annotation at metadata.annotations
```
"cattle.io/skipUninstall": "true"
```
From apps & market place, verify the app version displayed on the app which would be `1.9.1`

**Comment by mguggi** [comment] 2022-03-14 17:03
@anupama2501 Is the migration path somewhere documented? 

I've the same issue, after the _Rancher_ upgrade I prefer to go with the recommended _Apps & Marketplace_ feature. I’ve created the new _Repository_ form Git (same as the old _Rancher Catalog_) and see all my apps in the new UI screen. But wenn I want upgrade my app I receive the message:

_**This is a Legacy App and it cannot be modified here
Navigate to Legacy Apps**_

**Comment by throrin19** [comment] 2022-05-16 07:45
same problem as @mguggi. But in my case, I can upgrade applications in the new *Apps & Marketplace* part in older kubernete version. After upgrade to kubernetes 1.20, I have this message

**Comment by ronhorton** [comment] 2022-12-15 20:38
@AndrewHoffmanQA would you mind trying to repro this in 2.7-head?

**Comment by ronhorton** [comment] 2023-06-28 16:55
Didn't reproduce exact behavior - attempt made in 2.7-head

Legacy tag: active
Installed from ember UI
added annotations as directed in reproduction steps

- catalog.cattle.io/ui-source-repo: helm3-library
- catalog.cattle.io/ui-source-repo-type: cluster
- apps.cattle.io/migrated: "true"
- "cattle.io/skipUninstall": "true"

In legacy apps view (ember UI) shows correctly with an upgrade and correct version listed. Installed `aws-event-sources:0.1.0`
<img width="1316" alt="2023-06-28_12-41-19" src="https://github.com/rancher/rancher/assets/89212856/25746bbb-f9ba-414a-ae0d-6258be62a930">
In the rancher UI view, correct installed version is listed; no upgrade version listed; no 'upgradeable' tag:
<img width="1246" alt="2023-06-28_12-48-45" src="https://github.com/rancher/rancher/assets/89212856/06fef926-2aca-483d-9383-b1032876c817">

**Comment by ronhorton** [comment] 2023-06-28 19:21
**closing**
discussed issue with eng manager and project manager. 
this is a legacy feature. it's no longer showing an incorrect version.
due to the edge case nature of this issue, it won't be prioritized for further work.

**Closed** 2023-06-28 19:22 UTC
Labels: area/test, priority/2, kind/bug-qa, [zube]: QA Working, team/area3, area/helm
