### ISSUE TITLE
Unable to install rancher-monitoring in v2.5.1

### ISSUE THREAD

**Issue by ImIOImI** [rancher/rancher#29539] opened 2020-10-15 14:48 UTC
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
1) Create k3s cluster in AWS
2) Install Rancher v2.5.1
3) Go to cluster explorer and install rancher-monitoring
```
helm upgrade --install=true --namespace=cattle-monitoring-system --timeout=10m0s --values=/home/shell/helm/values-rancher-monitoring-crd-9.4.200.yaml --version=9.4.200 --wait=true rancher-monitoring-crd /home/shell/helm/rancher-monitoring-crd-9.4.200.tgz
```

**Result:**
```
Error: Prometheus.monitoring.coreos.com "rancher-monitoring-prometheus" is invalid: []: Invalid value: map[string]interface {}{"apiVersion":"monitoring.coreos.com/v1", "kind":"Prometheus", "metadata":map[string]interface {}{"annotations":map[string]interface {}{"meta.helm.sh/release-name":"rancher-monitoring", "meta.helm.sh/release-namespace":"cattle-monitoring-system"}, "creationTimestamp":"2020-10-15T14:01:01Z", "generation":1, "labels":map[string]interface {}{"app":"rancher-monitoring-prometheus", "app.kubernetes.io/managed-by":"Helm", "chart":"rancher-monitoring-9.4.200", "heritage":"Helm", "release":"rancher-monitoring"}, "name":"rancher-monitoring-prometheus", "namespace":"cattle-monitoring-system", "uid":"9271368a-e3a3-40d8-bf09-b922843b7242"}, "spec":map[string]interface {}{"alerting":map[string]interface {}{"alertmanagers":[]interface {}{map[string]interface {}{"apiVersion":"v2", "name":"rancher-monitoring-alertmanager", "namespace":"cattle-monitoring-system", "pathPrefix":"/", "port":"web"}}}, "baseImage":"rancher/prom-prometheus", "containers":[]interface {}{map[string]interface {}{"args":[]interface {}{"nginx", "-g", "daemon off;", "-c", "/nginx/nginx.conf"}, "image":"rancher/library-nginx:1.19.2-alpine", "name":"prometheus-proxy", "ports":[]interface {}{map[string]interface {}{"containerPort":8080, "name":"nginx-http", "protocol":"TCP"}}, "securityContext":map[string]interface {}{"runAsGroup":101, "runAsUser":101}, "volumeMounts":[]interface {}{map[string]interface {}{"mountPath":"/nginx", "name":"prometheus-nginx"}, map[string]interface {}{"mountPath":"/var/cache/nginx", "name":"nginx-home"}}}}, "enableAdminAPI":false, "evaluationInterval":"1m", "externalUrl":"http://rancher-monitoring-prometheus.cattle-monitoring-system:9090", "listenLocal":false, "logFormat":"logfmt", "logLevel":"info", "paused":false, "podMonitorNamespaceSelector":map[string]interface {}{}, "podMonitorSelector":map[string]interface {}{}, "portName":"nginx-http", "replicas":1, "resources":map[string]
--
  | interface {}{"limits":map[string]interface {}{"cpu":"1000m", "memory":"1500Mi"}, "requests":map[string]interface {}{"cpu":"750m", "memory":"750Mi"}}, "retention":"10d", "retentionSize":"50GiB", "routePrefix":"/", "ruleNamespaceSelector":map[string]interface {}{}, "ruleSelector":map[string]interface {}{}, "scrapeInterval":"1m", "securityContext":map[string]interface {}{"fsGroup":2000, "runAsGroup":2000, "runAsNonRoot":true, "runAsUser":1000}, "serviceAccountName":"rancher-monitoring-prometheus", "serviceMonitorNamespaceSelector":map[string]interface {}{}, "serviceMonitorSelector":map[string]interface {}{}, "version":"v2.18.2", "volumes":[]interface {}{map[string]interface {}{"emptyDir":map[string]interface {}{}, "name":"nginx-home"}, map[string]interface {}{"configMap":map[string]interface {}{"items":[]interface {}{map[string]interface {}{"key":"nginx.conf", "mode":438, "path":"nginx.conf"}}, "name":"prometheus-nginx-proxy-config"}, "name":"prometheus-nginx"}}}}: validation failure list:
Thu, Oct 15 2020 9:01:02 am | type in spec.volumes.configMap is required
```

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): 2.5.1
- Installation option (single install/HA): HA
- TLS termination on ALB
- DB: RDS mysql 5.7.19

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): Hosted in AWS created with k3sup
- Machine type (cloud/VM/metal) and specifications (CPU/memory): 4 (1 server, 3 agents) AWS t3.medium instances. 2 vCPUs 8 GiB memory per instance
- Kubernetes version (use `kubectl version`):

```
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.6", GitCommit:"dff82dc0de47299ab66c83c626e08b245ab19037", GitTreeState:"clean", BuildDate:"2020-07-15T16:58:53Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.9+k3s1", GitCommit:"630bebf94b9dce6b8cd3d402644ed023b3af8f90", GitTreeState:"clean", BuildDate:"2020-09-17T19:05:07Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
```

- Docker version (use `docker version`):

```
 Version:           19.03.8
 API version:       1.40
 Go version:        go1.13.8
 Git commit:        afacb8b7f0
 Built:             Tue Jun 23 22:26:12 2020
 OS/Arch:           linux/amd64
 Experimental:      true
```

- Rancher deployed via Helm chart options

```
helm install rancher rancher-latest/rancher 
--namespace cattle-system 
--set hostname=rancher.dev.<redacted>.com 
--create-namespace 
--set tls=external
```

**Comment by sarveshcv20** [comment] 2020-11-02 05:04
@ImIOImI Hi, were you able to find a solution for this?

**Comment by aiyengar2** [comment] 2020-11-02 20:30
We haven't encountered this error before, but it seems extremely similar to the error we encountered [in k8s 1.16 clusters](https://github.com/rancher/rancher/issues/29395) that was resolved by [just removing the `items` field entirely](https://github.com/rancher/charts/pull/784/files#diff-f02c7f63c56c13b571b4fb39e83a7fd2b9e631fd29ffc36ce72d176e317e5859L2697-L2700).

Can you check whether this workaround works for you? e.g. when installing the Monitoring V2 chart and configuring it under `Chart Options`, click on the `Edit as YAML` button on the bottom and replace the contents of https://github.com/rancher/charts/blob/1d17a5bb6767f6468815b005b688fb73f7baa228/charts/rancher-monitoring/values.yaml#L2462-L2465 with `defaultMode: 438` to avoid using items entirely.

e.g. it should look like this on the UI:
![Screen Shot 2020-11-02 at 12 28 34 PM](https://user-images.githubusercontent.com/13127443/97915833-f86f8700-1d06-11eb-90c4-8229f1688578.png)

If this workaround works, this issue should be fixed in 2.5.2.

**Comment by sanusatyadarshi** [comment] 2020-11-03 05:09
@aiyengar2 Thanks a lot. It worked.

**Comment by sanusatyadarshi** [comment] 2020-11-03 05:20
<img width="1430" alt="Screenshot 2020-11-03 at 10 47 00 AM" src="https://user-images.githubusercontent.com/20282376/97952137-5d3be780-1dc2-11eb-9505-1fa3917a2003.png">
Now, I have started getting this.

**Comment by aiyengar2** [comment] 2020-11-03 07:08
@sanusatyadarshi I haven't been able to reproduce the behavior you described in the image above, but based on the screenshot you sent it could have something do with the fact that the namespace is showing up as blank, e.g. my screenshot below shows `cattle-monitoring-system` and allows me to select different namespaces there:

![Screen Shot 2020-11-02 at 11 05 25 PM](https://user-images.githubusercontent.com/13127443/97957384-e5d56c00-1d5f-11eb-84d9-3c2273b9e0e2.png)

If this issue persists for you, could you open up a new issue by filling out a new issue template with details about your specific environment?

**Comment by ImIOImI** [comment] 2020-11-03 17:19
> @ImIOImI @sarveshcv20 We haven't encountered this error before, but it seems extremely similar to the error we encountered [in k8s 1.16 clusters](https://github.com/rancher/rancher/issues/29395) that was resolved by [just removing the `items` field entirely](https://github.com/rancher/charts/pull/784/files#diff-f02c7f63c56c13b571b4fb39e83a7fd2b9e631fd29ffc36ce72d176e317e5859L2697-L2700).
> 
> Can you check whether this workaround works for you? e.g. when installing the Monitoring V2 chart and configuring it under `Chart Options`, click on the `Edit as YAML` button on the bottom and replace the contents of https://github.com/rancher/charts/blob/1d17a5bb6767f6468815b005b688fb73f7baa228/charts/rancher-monitoring/values.yaml#L2462-L2465 with `defaultMode: 438` to avoid using items entirely.
> 
> e.g. it should look like this on the UI:
> ![Screen Shot 2020-11-02 at 12 28 34 PM](https://user-images.githubusercontent.com/13127443/97915833-f86f8700-1d06-11eb-90c4-8229f1688578.png)
> 
> If this workaround works, this issue should be fixed in 2.5.2.

This worked for me. I just searched for `prometheus-nginx-proxy-config` (the line numbers in rancher are way different from the linked revision) and replaced the items with `defaultMode: 438` and hit "Upgrade"

**Comment by sanusatyadarshi** [comment] 2020-11-04 07:15
@aiyengar2 This issue is still persistent. I am not sure what is causing this because the same version was working before. I redeployed the monitoring app and since then this issue started showing up.

**Comment by aiyengar2** [comment] 2020-11-05 01:19
@sanusatyadarshi please open up [a new issue](https://github.com/rancher/rancher/issues/new) with information about your environment so that we can try to reproduce the issue.

Since the workaround described in https://github.com/rancher/rancher/issues/29539#issuecomment-720707139 appears to work for @ImIOImI, I'm closing out this issue.

**Closed by aiyengar2** 2020-11-05 01:19 UTC
Labels: [zube]: To Triage
