### ISSUE TITLE
`listquestions` API incorrectly stores boolean type as string

### ISSUE THREAD

**Issue by westlywright** [rancher/rancher#23039] opened 2019-09-23 23:56 UTC
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
Use the api ui to view the data from `/v3/clustertemplaterevisions?action=listquestions`

**Result:**
Questions are listed but questions typed 'boolean' have the default value stored as a string. 

**Other details that may be helpful:**
This was found while tracking down https://github.com/rancher/rancher/issues/22972, a bandaid was put in the UI to handle this but we should fix the incorrect storage.

**Comment by prachidamle** [comment] 2019-09-24 23:35
@westlywright This API's response is a list of v3.Question - In the schema, the "v3.Question.default" field is of type String - it is not interface{}. Hence API has to set the default values as string.

**Comment by alena1108** [comment] 2019-09-26 20:52
@westlywright @prachidamle  checked the code, it is by design. We have `value`/`default` fields of a string type, and then there is a `type` field that can be leveraged by the client when converting the value.

**Comment by alena1108** [comment] 2019-09-26 21:03
After talking to @westlywright offline, we've agreed to close this issue. Changing the backend type is not advisable from the backwards compatibility perspective, and UI already handling the type conversion for bool represented as strings.

**Closed by alena1108** 2019-09-26 21:03 UTC
Labels: [zube]: Next Up, kind/bug, team/ca
