### ISSUE TITLE
Catalog apps are broken in Rancher UI after assigning their namespace to another project

### ISSUE THREAD

**Issue by christianmue1980a** [rancher/rancher#13931] opened 2018-06-10 11:45 UTC
**Rancher versions:**
rancher/server or rancher/rancher: v2.0.2
rancher/agent or rancher/rancher-agent:  rancher/rancher-agent@sha256:e4b5c35ae9f8f8caa811018b4803117cefc2062b382119c8b4734137ccf06fdd

**Docker version: (`docker version`,`docker info` preferred)**

```
Client:
 Version:      17.03.2-ce
 API version:  1.27
 Go version:   go1.7.5
 Git commit:   f5ec1e2
 Built:        Tue Jun 27 03:35:14 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.03.2-ce
 API version:  1.27 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   f5ec1e2
 Built:        Tue Jun 27 03:35:14 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
```
NAME="Ubuntu"
VERSION="16.04.4 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.4 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial
```

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**

bare metal

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**

HA Rancher

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**

RKE / Kubernetes

**Steps to Reproduce:**

- Login into Rancher UI
- Create a new namespace X and assign it to the Default project
- Navigate to Default project and deploy an app from the catalog into namespace X
- Create a new project Z and assign the namespace X to project Z

**Results:**
- Catalog apps are NOT listed under the project Z
- Catalog apps are still listed under the Default project but are not working anymore (0 pods, link shows an empty app overview page,...)

I think the apps should be listed under project Z and be functional of course.

![image](https://user-images.githubusercontent.com/36344241/41201252-7816f408-6cb4-11e8-9ef1-d5a586bda4ac.png)

![image](https://user-images.githubusercontent.com/36344241/41201247-631dab28-6cb4-11e8-92a1-708abc953508.png)

**Comment by tfiduccia** [comment] 2019-04-15 20:58
@deniseschannon - We have removed the ability to move catalog app namespaces from 2.0.  But...

In the case where you create the namespace first then put the app in it, the move options is still there until you refresh the browser.

If you do click on move before refresh a error message box in top right comes up and basically says "unknown action"
![image](https://user-images.githubusercontent.com/11514927/56164815-59e5ce80-5f86-11e9-83d8-b2f1f653f5e6.png)

SO you still can't move them.  but there are a couple of minor UI bugs here.

**Comment by davidnuzik** [comment] 2019-04-19 22:57
It is still possible to attempt to move the namespace via the Edit function:

![image](https://user-images.githubusercontent.com/45179589/56447208-c250ea80-62bb-11e9-8ef3-aabceef9e5ee.png)

![image](https://user-images.githubusercontent.com/45179589/56447211-c977f880-62bb-11e9-8fd4-56d3707439b2.png)

**Comment by davidnuzik** [comment] 2019-06-19 20:02
Version: Master (v2.3) (6/19/19)

This fix prevents moving of namespaces once the namespace has an app deployed within it.

Projects/Namespaces page:
(/c/CLUSTERID/projects-namespaces)

- Create a namespace 'x' and assign to any project.
- Create any catalog app in this project, and assign it to the newly created 'x' namespace.
- From the same Projects/Namespaces page, click the function menu and Edit, and ensured option to move namespace from here was removed.
![image](https://user-images.githubusercontent.com/45179589/59795933-44946580-9291-11e9-87b6-da375b416f58.png)
![image](https://user-images.githubusercontent.com/45179589/59795946-4bbb7380-9291-11e9-95a6-fc69c8663afc.png)

- Now, do the same, but with two tabs (and a new namespace). One tab you keep open on the projects/namespaces page, the other you use to create the app.
- Ensured that even without leaving nav of the Projects/Namespaces page that after we have created an app for the new namespaces you cannot move it (no refresh or navigate away projects/namespaces and back to it is required).

Project ns page
(p/CLUSTERID:PROJECTID/ns)
- Go to the project you put the 'x' namespace in, go to the Namespaces page from the navbar.
- Confirmed from here as well we cannot edit the namespace and move it to another project because there is an app deployed already to this ns.

Additionally, for both tests confirmed that the "Move" button does not work once an app is associated with a namespace.

**Closed by davidnuzik** 2019-06-19 20:02 UTC
Labels: [zube]: To Test, area/catalog, area/ui, kind/bug, team/ui
