### ISSUE TITLE
API Response for certificate rotation api is incorrect

### ISSUE THREAD

**Issue by westlywright** [rancher/rancher#17317] opened 2019-01-04 19:00 UTC
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
Launch a rke cluster
When the cluster is ready from the UI or API UI use the `rotate certificates` action

**Result:**
The response data from the api is a plain string
`Rotating <service-name> certificates`

**Other details that may be helpful:**
Actions performed on other resources return the resource that was acted upon in a json blob. The UI expects JSON responses and blows up on this returned data.

**Comment by alena1108** [comment] 2019-01-09 01:04
@westlywright can you confirm that the issue is no longer present, and close the issue if so?

**Comment by cjellick** [comment] 2019-02-07 18:29
will assume @bmdepesa will verify and @westlywright has no immediate follow up

**Comment by bmdepesa** [comment] 2019-02-07 21:34
rancher/rancher:master 2/7

The response from the rotateCertificate action correctly returns `application/json` in the response headers, but there is no response:

![screen shot 2019-02-07 at 2 00 54 pm](https://user-images.githubusercontent.com/21316915/52444271-1b92e580-2ae5-11e9-9b45-6ef3cffd266f.png)

We expect there to be a response detailing which certs were rotated; e.g. 
`rotating certificates for all components`.

**Comment by bmdepesa** [comment] 2019-02-12 21:40
rancher/rancher:master 2/12

There is still no response (null) when rotating certificates. Tested through UI (viewing network console in browser) and through the API browser. 

```
HTTP/1.1 POST /v3/clusters/c-z9tml?action=rotateCertificates
Host: brandonha.qa.rancher.space
Accept: application/json
Content-Type: application/json
Content-Length: 39

{
"caCertificates": true,
"services": null
}
```

```
HTTP Response:
HTTP/1.1 200
date: Tue, 12 Feb 2019 21:39:52 GMT
server: nginx/1.13.12
strict-transport-security: max-age=15724800; includeSubDomains
content-type: application/json
status: 200
x-api-schemas: https://brandonha.qa.rancher.space/v3/cluster/c-z9tml/schemas
content-length: 5
expires: Wed 24 Feb 1982 18:42:00 GMT
```

**Comment by vincent99** [comment] 2019-02-12 21:41
The headers say there's 5 bytes, which is odd...

**Comment by bmdepesa** [comment] 2019-02-13 03:55
It looks like it's returning the string `null` which would come out to 5 bytes. It doesn't seem to show that in the API browser.

```
$> curl -u $token \
-X POST \
-k \
-H 'Accept: application/json' \
-H 'Content-Type: application/json' \
-d '{"caCertificates":false, "services":"kubelet"}' \
'https://brandonha.qa.rancher.space/v3/clusters/c-z9tml?action=rotateCertificates'
null
```

**Comment by bmdepesa** [comment] 2019-02-13 21:07
rancher/rancher:master 2/13

Response for rotateCertificates is returning correctly.

**Closed by bmdepesa** 2019-02-13 21:07 UTC
Labels: kind/bug, status/reopened, status/resolved, status/to-test, team/az, version/2.0
