### ISSUE TITLE
How to enable tlsv10 in load balancer?

### ISSUE THREAD

**Issue by rubenmch** [rancher/rancher#3034] opened 2015-12-15 23:06 UTC
We have an API used by some client apps. Some of them use .Net Framework 3.5. .Net Framework 3.5 only supports TLS 1.0 and SSL v3, it doesn't support TLS 1.1 and 1.2.

I know TLS 1.0 is insecure but we have no control over the app and can't force them to change it to a newer version of the .Net Framework.

In older versions of rancher TLS 1.0 was enabled and our API worked with those apps. 

In recent versions of rancher no-tlsv10 was added to the frontend configuration of haproxy.

In rancher 0.50 global and defaults settings for haproxy were added but I don't see a way in the haproxy documentation to override the no-tlsv10 that rancher automatically adds to the frontend configuration using only global and defaults settings.

Is there any way to enable TLS 1.0 in the current version of rancher (0.50) ?

If not please add it as a feature request.

**Comment by deniseschannon** [comment] 2015-12-22 21:47
This sounds like a pre-duplicate of #3097, but before I consolidate to one issue, I'd like to confirm. 

We will most likely take the suggestion in #3097.

**Comment by rubenmch** [comment] 2015-12-22 23:04
@deniseschannon Yes, it's the same issue, that suggestion would work for us too.

**Comment by deniseschannon** [comment] 2015-12-22 23:05
Ok, I will close in favor of the other one.

**Closed by deniseschannon** 2015-12-22 23:05 UTC
