### ISSUE TITLE
[rancher-monitoring/v100.1.2+up19.0.3] Found duplicate series for the match group on the left hand-side of the operation

### ISSUE THREAD

**Issue by roh85** [rancher/rancher#39430] opened 2022-04-07 14:32 UTC
After upgrading to rancher-monitoring/v100.1.2+up19.0.3 on Kubernetes 1.21 and Rancher 2.6.4 I get an error when viewing the metrics of a pod.

`Templating
Template variable service failed "found duplicate series for the match group {pod=\"identityserver-redis-master-0\"} on the left hand-side of the operation: [{__name__=\"kube_pod_info\", container=\"kube-state-metrics\", created_by_kind=\"StatefulSet\", created_by_name=\"identityserver-redis-master\", endpoint=\"http\", host_ip=\"filtered_out\", host_network=\"false\", instance=\"10.34.0.12:8080\", job=\"kube-state-metrics\", namespace=\"identityserver-staging\", node=\"filtered_out\", pod=\"identityserver-redis-master-0\", pod_ip=\"10.38.0.22\", service=\"rancher-monitoring-kube-state-metrics\", uid=\"31226306-c1d0-4d22-ade4-9af2366310e8\"}, {__name__=\"kube_pod_info\", container=\"kube-state-metrics\", created_by_kind=\"StatefulSet\", created_by_name=\"identityserver-redis-master\", endpoint=\"http\", host_ip=\"filtered_out\", host_network=\"false\", instance=\"10.34.0.12:8080\", job=\"kube-state-metrics\", namespace=\"identityserver\", node=\"filtered_out\", pod=\"identityserver-redis-master-0\", pod_ip=\"10.38.0.27\", service=\"rancher-monitoring-kube-state-metrics\", uid=\"842abccf-587c-4763-b222-39844732fbaf\"}];many-to-many matching not allowed: matching labels must be unique on one side"
`

The issue seems to occur because I have redis in 2 different namespaces (production & staging namespace) but with the same pod name (it is a statefulset). I fixed it temporarly by changing the namespace variable query to group on pod, namespace. I have updated the rancher-workload-pods.json and rancher-workload.json with this query and it is working now.
`kube_pod_info{namespace!=""} * on(pod, namespace) group_right(created_by_kind, created_by_name) count({__name__=~"container_.*|windows_container_.*", pod!=""}) by (pod, namespace)`

**Comment by MKlimuszka** [comment] 2022-12-05 21:17
We believe that this fix will be a useful workaround for the reporter, but it does not fix the underlying issue, which needs more investigation. But we will test this fix for the 2023 Q1 release.

**Comment by MKlimuszka** [comment] 2023-01-23 15:57
This needs to be reproduced in 2023-Q1-2.6x,  2023-Q1-2.6x, and if it cannot be reproduced in those, 2.6.4.

We should also re-review the open PR for the workaround.

**Comment by PennyScissors** [comment] 2023-02-16 21:54
This issue is a duplicate of https://github.com/rancher/rancher/issues/39430

**Comment by PennyScissors** [comment] 2023-02-16 22:15
Closing this issue as it is a duplicate of https://github.com/rancher/rancher/issues/39430 and we have already started investigating the other issue.

**Closed by PennyScissors** 2023-02-16 22:15 UTC
Labels: kind/bug, priority/2, area/monitoring, status/to-reproduce, [zube]: Next Up, team/area3
