### ISSUE TITLE
Rancher-created registry secret is missing the auth field

### ISSUE THREAD

**Issue by nanomad** [rancher/rancher#19177] opened 2019-03-26 09:02 UTC
**What kind of request is this (question/bug/enhancement/feature request):**

Bug

**Steps to reproduce (least amount of steps as possible):**

1. Create a registry secret from the UI
2. Inspect it via kubectl
3. Decode the .dockerconfigjson field

**Result:**
```
{"auths":{"registry.example.com":{"password":"password","username":"username"}}}
```
**Expected Result:**
```
{"auths":{"registry.example.com":{"username":"username","password":"password","auth":"dXNlcm5hbWU6cGFzc3dvcmQ="}}}
```
**Other details that may be helpful:**

If the secret is created via the rancher-supplied kubectl then the secret has the auth field inside. Also, *technically speaking* the email field should be there as well

Possibly related to:
https://github.com/kubernetes/kubectl/issues/571

This breaks tools like 
https://github.com/weaveworks/flux/
That use the secret to list images sha and tags

**Environment information**
- Rancher version: 2.1.7
- Kubernetes Version: v1.13.4
- Installation option:  Single Node

**Comment by calexandre** [comment] 2019-04-22 16:22
+1
I have the same Rancher version and I can confirm this issue.
Flux needs the Auth field to work properly.

Also, there is a forum [issue](https://forums.rancher.com/t/dockerconfigjson-fields-missing-auth-on-2-1-7/14038) reporting this behavior.

**Comment by cjellick** [comment] 2019-04-23 15:42
@deniseschannon - ping to get this on our radar for consideration

**Comment by ekristen** [comment] 2019-08-21 17:01
I would vote for this being backported to 2.2.x too.

**Comment by prachidamle** [comment] 2019-08-29 00:25
The fix is based on this upstream kubectl fix, which generates this auth field: https://github.com/kubernetes/kubernetes/pull/72344/files#diff-3bf290ed2a11e649da5afa02a5bbfd3a

When we create a dockerCredential secret from Rancher UI, we post the data via K8s REST API - which does not seem to have this "auth" field generation like kubectl does. Hence we will handle the generation of this field while creating the secret.

We will not be supporting upgrade of existing secrets. Only new secrets created will have the "auth" field generated.

**Comment by ekristen** [comment] 2019-09-11 19:58
Any thoughts on backporting to 2.2?

**Comment by ekristen** [comment] 2019-10-28 21:34
I am assuming that since this is still open that this hasn't landed yet in 2.3?

**Comment by prachidamle** [comment] 2019-10-28 22:01
@ekristen not yet, it is scoped for the next rancher patch release 2.3.3

**Comment by ekristen** [comment] 2019-10-28 23:28
doh! was hoping 2.3.2 ... glad it's scoped though! Thanks! Looking forward to this landing. Appreciate the feedback @prachidamle, much appreciated.

**Comment by sowmyav27** [comment] 2019-10-31 22:55
### Reproduced the issue on 2.3.2

**Steps:**

- Create a registry secret from the UI
- Inspect it via kubectl
- Decode the .dockerconfigjson field - `echo '<dockerconfigjson-value>' | base64 -d` in kubectl in cluster

```
{"auths":{"index.docker.io":{"password":"password","username":"username"}}}> `
```

### Verified on 2.3-head - latest

**Steps:**

- Create a registry secret from the UI
- Inspect it via kubectl
- Decode the .dockerconfigjson field - `echo '<dockerconfigjson-value>' | base64 -d` in kubectl in cluster

```
{"auths":{"index.docker.io":{"auth":"c293bXlhdjI3OnRlc3Q=","password":"password","username":"username"}}}>
```

**Closed** 2019-10-31 23:16 UTC
Labels: [zube]: To Test, kind/bug, team/ca
