### ISSUE TITLE
Error when parsing custom cloud provider config

### ISSUE THREAD

**Issue by OberstHorst** [rancher/rancher#13296] opened 2018-05-04 10:56 UTC
**Rancher versions:**
rancher/server or rancher/rancher: 2.0.0
rancher/agent or rancher/rancher-agent: 2.0.0

**Docker version: (`docker version`,`docker info` preferred)**
Server Version: 17.12.1-ce
**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
Kernel: 4.4.0-116-generic

NAME="Ubuntu"
VERSION="16.04.4 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.4 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial
**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
openstack VMs 
**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
single node rancher
**Steps to Reproduce:**
1.) Spin up openstack VMs and install docker.
2.) Run add cluster
3.) Add a custom cluster, leave options default.
4.) Add nodes to the cluster with suggested command, exact setup should not matter
5.) Start the cluster
6.) Edit the cluster and change to cloud provider option to custom
7.) Add "openstack" as cloud provider name and and some key value pairs (probabaly not needed)
8.) Save

**Results:**
Cluster does not spin up anymore, resulting in the following error message in the Kubernetes UI:

This cluster is currently Updating.

[workerPlane] Failed to bring up Worker Plane: Failed to verify healthcheck: Failed to check https://localhost:10250/healthz for service [kubelet] on host [10.0.100.10]: Get https://localhost:10250/healthz: dial tcp 127.0.0.1:10250: getsockopt: connection refused

When looking at the VM and executin docker ps -a it shows a line with:
20f2ba35b01c        rancher/hyperkube:v1.10.1-rancher2   "/opt/rke/entrypoint…"   31 minutes ago      Restarting (255) 49 seconds ago

The logs of the container showed:
I0504 10:52:39.057064   19163 feature_gate.go:226] feature gates: &{{} map[MountPropagation:false]}
I0504 10:52:39.059367   19163 mount_linux.go:196] Detected OS without systemd
I0504 10:52:39.068389   19163 server.go:376] Version: v1.10.1
I0504 10:52:39.068468   19163 feature_gate.go:226] feature gates: &{{} map[MountPropagation:false]}
F0504 10:52:39.069265   19163 server.go:233] failed to run Kubelet: could not init cloud provider "openstack": 1:1: illegal character U+007B
in the last lines.

I would guess it is a parsing error. 
Thank in advance

Marius

**Comment by janeczku** [comment] 2018-05-04 11:34
Confirmed 👍

**Comment by superseb** [comment] 2018-05-04 11:37
Closing as duplicate of https://github.com/rancher/rancher/issues/13115, this needs gcfg support just as vSphere needs. (https://github.com/kubernetes/kubernetes/blob/v1.10.1/pkg/cloudprovider/providers/openstack/openstack.go)

**Closed by superseb** 2018-05-04 11:37 UTC
