### ISSUE TITLE
AWS node drivers rke1 cluster are stuck in waiting when the network provider is Weave

### ISSUE THREAD

**Issue by anupama2501** [rancher/rancher#36710] opened 2022-03-02 05:03 UTC
Information about the Cluster
**Rancher Server Setup**
- Rancher version: v2.6-head `e93a53c`
- Installation option (Docker install/Helm Chart): Helm Chart
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): RKE1, v1.22.6, 1.3.7
- Proxy/Cert Details: Selfsigned

**Information about the Cluster**
- Kubernetes version: v1.22.6/v1.21.9
- Cluster Type (Local/Downstream): `Downstream node driver AWS 1 worker, 1 etcd, 1 cp RKE1`

**Describe the bug**
When the network provider weave is selected for a AWS node driver  the cluster won't come up active even when all the nodes are active. Cluster explorer page won't be active as the cluster is stuck in `Waiting`. Happens if we select an rke1 template/rke1 cluster with weave provider.

**To Reproduce**
1. Create a node driver AWS cluster with 1 etcd, 1 cp and 1 worker node
2. Select the network provider weave

**Result**
Cluster is stuck in `Waiting`. See the following error logs in rancher pods:

Status in the yaml:
`  - lastUpdateTime: "2022-03-02T00:28:38Z"
    message: Cluster agent is not connected
    reason: Disconnected`

```
2022/03/02 00:29:44 [INFO] cluster [c-tmgm8] worker-upgrade: sending node-version for node [anuweave-w1] version 1
2022/03/02 00:48:08 [ERROR] defaultSvcAccountHandler: Sync: error handling default ServiceAccount of namespace key=c-vj4l4, err=Operation cannot be fulfilled on namespaces "c-vj4l4": the object has been modified; please apply your changes to the latest version and try again
```

**Expected Result**
Cluster to come active

**Additional context**
It is not seen for DO node drivers, AWS custom clusters. Only seen for AWS node drivers. 
~~Not seen on 2.6.3 with AWS node drivers.~~

This is sometimes seen on 2.6.3 docker install as well - AWS node driver clusters with weave network provider and k8s 1.21 are stuck in `waiting`

**Comment by cmurphy** [comment] 2022-03-03 19:42
I was able to reproduce this on 2.6.3 which is why I don't think it's a team 1 regression.

**Comment by kinarashah** [comment] 2022-03-04 18:34
Was able to reproduce on 2.6.3 on 2/10 clusters, not always reproducible. Saw the same condition  on cluster object, 
`message: Cluster agent is not connected reason: Disconnected` . 

Seems to be weave issue. To confirm: 
- ssh on the control plane node. check for cluster-agent logs. container might have exited, restart to get logs 
`
ERROR: https://xxx-xx-xx-xx.us-west-2.compute.amazonaws.com/ping is not accessible (Could not resolve host:xxx-xx-xx-xx.us-west-2.compute.amazonaws.com)
`

- check weave container logs, erroring out with 
`
INFO: 2022/03/04 18:03:43.588522 ->[172.31.9.5:34109|7a:4e:5f:93:59:54(kinara-ec2weave-ep1)]: connection shutting down due to error: IP allocation was seeded by different peers (received: [7a:4e:5f:93:59:54(kinara-ec2weave-ep1)], ours: [7a:f0:a0:4b:8a:35(kinara-ec2weave-cp1)])
` 

- this is an upstream issue, from the docs https://github.com/weaveworks/weave/blob/master/site/tasks/ipam/troubleshooting-ipam.md#seeded-by-different-peers 

- implemented the workaround mentioned https://stackoverflow.com/questions/61124363/inter-node-pod-to-pod-communication-is-not-possible-why 

```
rm /var/lib/weave/weave-netdata.db
reboot

```
- no errors in weave pod, cluster agent comes up active.

**Comment by kinarashah** [comment] 2022-03-04 22:17
@anupama2501 reproduced the issue on HA setup v2.6-head. This is different than the behavior I saw. 

On this setup,  cluster-agent container doesn't come up at all: 
`
cattle-system   3m29s       Warning   FailedCreatePodSandBox    pod/cattle-cluster-agent-cb7bc4ffd-5zrt2         (combined from similar events): Failed to create pod sandbox: rpc error: code = Unknown desc = failed to set up sandbox container "e39c317582356e142bc2df8bca79484594d3f60b73dd7840375262eacca70ae4" network for pod "cattle-cluster-agent-cb7bc4ffd-5zrt2": networkPlugin cni failed to set up pod "cattle-cluster-agent-cb7bc4ffd-5zrt2_cattle-system" network: netplugin failed with no error message: signal: killed 
`

Another thing I noted is even after removing the weave-netdata and rebooting the node, the weave pods still are complaining are about disconnecting to the peer list. 
`
INFO: 2022/03/04 22:10:45.931091 ->[172.31.7.124:6783] error during connection attempt: dial tcp :0->172.31.7.124:6783: connect: connection timed out
INFO: 2022/03/04 22:11:49.419029 ->[172.31.13.84:6783] error during connection attempt: dial tcp :0->172.31.13.84:6783: connect: connection timed out
`

@anupama2501 is creating few more setups for this, will continue debugging.

**Comment by snasovich** [comment] 2022-03-11 20:31
@kinarashah @anupama2501 , any updates on this one?

**Comment by kinarashah** [comment] 2022-03-17 22:52
There were 2 issues I observed when we first reproduced issue of cluster agent disconnecting and cluster in waiting state: 
- cluster agent didn't start, dns and connection failures. I haven't been able to reproduce this behavior again, so I think it was more of a setup problem than the original issue. 

- issue with weave itself, which is due to IP allocation getting seeded by different peers error when joining nodes. Upstream issues - https://github.com/weaveworks/weave/issues/3908 and https://github.com/weaveworks/weave/issues/3902. 

Upstream issues haven't been resolved yet, it has been called out in their docs with a workaround: https://github.com/weaveworks/weave/issues/3902 
The workaround has worked consistently for me every time I reproduced the issue, and the issue is not always reproducible. 

So we should be able to close this issue unless we see a different behavior that's due to Rancher/RKE changes.

**Comment by Josh-Diamond** [comment] 2022-04-08 19:47
Ticket #36710 - Test Results

With Docker on single-node instance:

Reproduction Failures on rancher `v2.6-e93a53c35bd038d4cf0d0d96897e957ffef150c9-head`:

`With k8s v1.22.7`
1. Fresh install of rancher `v2.6-head`
2. Provision an AWS Node driver rke1 downstream cluster with k8s `v1.22.7` - 3 nodes [1 etcd, 1 cp, 1 wkr] and using `Weave` as the Network Provider
3. Reproduction Failure - Cluster is successfully provisioned

`With k8s v1.21.10`
1. Fresh install of rancher `v2.6-head`
2. Provision an AWS Node driver rke1 downstream cluster with k8s `v1.21.10` - 3 nodes [1 etcd, 1 cp, 1 wkr] and using `Weave` as the Network Provider
3. Reproduction Failure - Cluster is successfully provisioned

Screenshot:
<img width="1584" alt="36710-reprod-fail" src="https://user-images.githubusercontent.com/46494969/162516075-c938d36e-77ee-48a6-bfb3-66f3aafdb883.png">


Verified on rancher `v2.6-4a5a926fe1fc319847a78fe814e3f2be18bb2c2b-head`:

`With k8s v1.22.7`
1. Fresh install of rancher `v2.6-head`
2. Provision an AWS Node driver rke1 downstream cluster with k8s `v1.22.7` - 3 nodes [1 etcd, 1 cp, 1 wkr] and using `Weave` as the Network Provider
3. Verified - Cluster is successfully provisioned

`With k8s v1.21.10`
1. Fresh install of rancher `v2.6-head`
2. Provision an AWS Node driver rke1 downstream cluster with k8s `v1.21.10` - 3 nodes [1 etcd, 1 cp, 1 wkr] and using `Weave` as the Network Provider
3. Verified - Cluster is successfully provisioned

Screenshot:
<img width="1466" alt="36710-verified" src="https://user-images.githubusercontent.com/46494969/162516116-750fb230-86d8-408e-a28d-bf1b202b2d29.png">

**Closed by Josh-Diamond** 2022-04-08 19:47 UTC
Labels: kind/bug-qa, [zube]: QA Working, QA/XS, team/area2
