### ISSUE TITLE
Monitoring v2 - Support the Coexistence of v1 and v2

### ISSUE THREAD

**Issue by jiaqiluo** [rancher/rancher#28513] opened 2020-08-21 22:30 UTC
We need to support the coexistence of monitoring v1 and v2 in the same downstream cluster. 

Related issue: https://github.com/rancher/rancher/issues/25044

**Comment by aiyengar2** [comment] 2020-09-04 02:44
At the moment, Monitoring V1 and V2 cannot be supported together since both deploy Prometheus Operator pods that manage resources across all namespaces within the cluster. Both Monitoring V1 and Monitoring V2 would need to have the capability to limit their scope to particular namespaces (at the minimum) for both to be deployed onto the same cluster; we do not currently have support for this in Monitoring V1.

There's a UI ticket out in https://github.com/rancher/dashboard/issues/1167 to warn when trying to deploy Monitoring V2 on a cluster where Monitoring V1 is already deployed and more information on why this constraint exists in https://github.com/rancher/rancher/issues/25044.

Closing this issue out in favor of https://github.com/rancher/rancher/issues/25044 since it details the root cause for why this cannot be supported and tracks the broader issue that prevents us from supporting this coexistence in the future.

**Closed by aiyengar2** 2020-09-04 02:44 UTC
Labels: [zube]: Next Up, area/monitoring, kind/bug-qa
