### ISSUE TITLE
docker logs ERROR in creating more than one Load Balancer

### ISSUE THREAD

**Issue by yutian1224** [rancher/rancher#3116] opened 2015-12-22 03:38 UTC
how can i solve this problem? thx

rancher version: v0.50.2
docker version: 1.9.1
here is the logs:

Tuesday, December 22, 2015 18:53:56INFO: Updating agent-instance-startup
Tuesday, December 22, 2015 18:53:56INFO: Downloading http://172.19.48.3:8080/v1//configcontent//agent-instance-startup current=
Tuesday, December 22, 2015 18:53:56INFO: Running /var/lib/cattle/download/agent-instance-startup/agent-instance-startup-1-64324bfc5b482525bb012a231937d65e13f8377a9534571a8ecb62df5877b527/apply.sh
Tuesday, December 22, 2015 18:53:56INFO: Setting eth0 mac to 02:97:70:68:cb:c4
Tuesday, December 22, 2015 18:53:56RTNETLINK answers: Operation not permitted
Tuesday, December 22, 2015 18:53:56[[scripts.sh:184] script_env
Tuesday, December 22, 2015 18:53:56[[scripts.sh:109] '[' -n http://172.19.48.3:8080/v1 ']'
Tuesday, December 22, 2015 18:53:56[[scripts.sh:110] return
Tuesday, December 22, 2015 18:53:56[[scripts.sh:186] export CATTLE_HOME=/var/lib/cattle
Tuesday, December 22, 2015 18:53:56[[scripts.sh:186] CATTLE_HOME=/var/lib/cattle
Tuesday, December 22, 2015 18:53:56[[scripts.sh:187] export CATTLE_CONFIG_URL=http://172.19.48.3:8080/v1
Tuesday, December 22, 2015 18:53:56[[scripts.sh:187] CATTLE_CONFIG_URL=http://172.19.48.3:8080/v1
Tuesday, December 22, 2015 18:53:56[[scripts.sh:188] export CATTLE_STORAGE_URL=http://172.19.48.3:8080/v1
Tuesday, December 22, 2015 18:53:56[[scripts.sh:188] CATTLE_STORAGE_URL=http://172.19.48.3:8080/v1
Tuesday, December 22, 2015 18:53:56[apply.sh:5] read DEV MAC IP
Tuesday, December 22, 2015 18:53:56[[apply.sh:6] ip link show dev eth0
Tuesday, December 22, 2015 18:53:56[[apply.sh:6] grep link/ether
Tuesday, December 22, 2015 18:53:56[[apply.sh:6] awk '{print $2}'
Tuesday, December 22, 2015 18:53:56[apply.sh:6] '[' ea:66:e1:3d:d3:18 '!=' 02:97:70:68:cb:c4 ']'
Tuesday, December 22, 2015 18:53:56[apply.sh:7] info Setting eth0 mac to 02:97:70:68:cb:c4
Tuesday, December 22, 2015 18:53:56[scripts.sh:19] echo INFO: Setting eth0 mac to 02:97:70:68:cb:c4
Tuesday, December 22, 2015 18:53:56INFO: Setting eth0 mac to 02:97:70:68:cb:c4
Tuesday, December 22, 2015 18:53:56[apply.sh:8] ip link set dev eth0 address 02:97:70:68:cb:c4
Tuesday, December 22, 2015 18:53:56RTNETLINK answers: Operation not permitted
Tuesday, December 22, 2015 18:53:56
The system is going down NOW!
Tuesday, December 22, 2015 18:53:56
Sent SIGTERM to all processes
Tuesday, December 22, 2015 18:53:58
Sent SIGKILL to all processes
Tuesday, December 22, 2015 18:53:58
Requesting system reboot

**Comment by deniseschannon** [comment] 2015-12-22 20:10
Can you provide more details? Are you trying to create 2 instances of the same load balancer on the same host (this wouldn't work as we expose ports on the host)? Are you trying to create 2 different load balancers on the same host?

**Comment by yutian1224** [comment] 2015-12-23 01:58
I'm trying to create 2 instances of the same load balancer on different hosts.The 2nd load balancer is stuck when Initializing.
![image](https://cloud.githubusercontent.com/assets/13673671/11969821/02d3e206-a95b-11e5-855c-981bd54adc79.png)
![image](https://cloud.githubusercontent.com/assets/13673671/11969855/ab6966ac-a95b-11e5-85a5-e45fdcc9ba7a.png)

**Comment by deniseschannon** [comment] 2015-12-28 22:50
Pre-duplicate of https://github.com/rancher/rancher/issues/3142, but I'm going to use that issue to track what's going on. @yutian1224 Please provide more details on that issue.

**Closed by deniseschannon** 2015-12-28 22:50 UTC
Labels: kind/question
