### ISSUE TITLE
rancher server(>=2.2.4) cannot work on arm64

### ISSUE THREAD

**Issue by niusmallnan** [rancher/rancher#22033] opened 2019-08-07 14:02 UTC
**What kind of request is this (question/bug/enhancement/feature request):**
bug

**Steps to reproduce (least amount of steps as possible):**
Try to run rancher-server on ARM64 platform.
docker run -d --restart=unless-stopped -p 80:80 -p 443:443 rancher/rancher:v2.2.4

**Result:**
Exit with a fatal error

**Other details that may be helpful:**

Rancher server logs:
```
2019/08/07 13:54:07 [INFO] Creating CRD settings.management.cattle.io
2019/08/07 13:54:08 [INFO] Creating CRD templates.management.cattle.io
2019/08/07 13:54:08 [INFO] Creating CRD templateversions.management.cattle.io
2019/08/07 13:54:08 [INFO] Creating CRD templatecontents.management.cattle.io
2019/08/07 13:54:08 [INFO] Creating CRD tokens.management.cattle.io
2019/08/07 13:54:08 [INFO] Creating CRD userattributes.management.cattle.io
2019/08/07 13:54:09 [INFO] Creating CRD users.management.cattle.io
2019/08/07 13:54:09 [INFO] Creating CRD globaldnses.management.cattle.io
2019/08/07 13:54:09 [INFO] Creating CRD globaldnsproviders.management.cattle.io
2019/08/07 13:54:10 [INFO] password fields {"elasticsearchConfig":{"authPassword":".."},"fluentForwarderConfig":{"fluentServers":{"password":"..","sharedKey":".."}},"kafkaConfig":{"saslPassword":".."},"splunkConfig":{"token":".."},"syslogConfig":{"token":".."}}
2019/08/07 13:54:10 [INFO] password fields {"elasticsearchConfig":{"authPassword":".."},"fluentForwarderConfig":{"fluentServers":{"password":"..","sharedKey":".."}},"kafkaConfig":{"saslPassword":".."},"splunkConfig":{"token":".."},"syslogConfig":{"token":".."}}
2019/08/07 13:54:10 [INFO] Starting API controllers
2019/08/07 13:54:11 [FATAL] error running the jail command: cp: cannot stat '/lib64': No such file or directory
: exit status 1
```

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI):
from 2.2.4 to 2.2.7
- Installation option (single install/HA):
single

- Docker version (use `docker version`):

```
Client:
 Debug Mode: false

Server:
 Containers: 1
  Running: 0
  Paused: 0
  Stopped: 1
 Images: 3
 Server Version: 19.03.1
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 894b81a4b802e4eb2a91d1ce216b8817763c29fb
 runc version: 425e105d5a03fabd737a126ad93d62a9eeede87f
 init version: fec3683
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 4.15.0-1043-aws
 Operating System: Ubuntu 18.04.2 LTS
 OSType: linux
 Architecture: aarch64
 CPUs: 2
 Total Memory: 3.711GiB
 Name: ip-172-31-26-213
 ID: WBFW:TYQC:5533:F75Q:YDEG:BHR6:TDIV:G36R:KRSE:4JIO:3VY3:FXDJ
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No swap limit support
```

**Comment by dramich** [comment] 2019-08-09 16:43
This is a duplicate of https://github.com/rancher/rancher/issues/21534

**Closed by dramich** 2019-08-09 16:43 UTC
Labels: area/arm, area/server
