### ISSUE TITLE
[UI] Unable to cancel out of node template modal

### ISSUE THREAD

**Issue by davidnuzik** [rancher/rancher#21618] opened 2019-07-18 20:11 UTC
Version: master-head (7/18/19)

**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
- Create a node template via the "Add Cluster" page, create a cloud credential if necessary. You first need to submit your cloud credential to see node template settings.
- Now, try to Cancel out.

**Result:**
Browser dev console reports that `this.cancel is not a function`
Clicking cancel button won't do anything in the UI.

**Comment by n313893254** [comment] 2019-08-12 08:53
@davidnuzik, sorry I cannot reproduce this issue, can you give me more info to reproduce it. 

Here are my steps:
1. Go to Add Cluster - Amazon EC2 page.
2. Click "Add Node template" button.
3. Input keys and click the "Create" button.
4. After showing node setting, click the "Cancel" button.

Result:
Modal cancel success and browser dev console did not report errors.

**Comment by loganhz** [comment] 2019-08-12 10:05
This should be fixed in master

**Comment by izaac** [comment] 2019-08-16 16:51
Version: master-head (8/16/19)

I went through the Add cluster wizards with Chrome and Firefox. First as pointed out using Amazon EC2, but then I performed a verification to the other cloud providers Add cluster wizards hitting Cancel in all the steps (where applicable) before Create.

I also finished creating an Amazon EC2 and DO without hitting cancel. Clusters were successfully. created.

**Closed by izaac** 2019-08-16 16:51 UTC
Labels: [zube]: To Test, kind/bug-qa, team/ui
