### ISSUE TITLE
Multiple dynamic schemas found of the same role and account

### ISSUE THREAD

**Issue by lkm** [rancher/rancher#4190] opened 2016-03-29 09:06 UTC
Rancher Version:
1.0.0
Docker Version:
1.10.1, build 9e83765
OS: 
Ubuntu 14.04
Steps to Reproduce: 
Upgrade to 1.0.0 from 0.63.0.
Results: 
After the upgrade Rancher fails to open "Infrastructure page" and throws this exception:
```
2016-03-29 08:39:12,040 ERROR [:] [] [] [] [tp685650491-121] [i.c.p.c.d.impl.DynamicSchemaDaoImpl ] Failed to get a schema record. org.jooq.exception.InvalidResultException: Multiple dynamic schemas found of the same role and account id combination: Name:machineRole: owner AccountId: null
	at io.cattle.platform.core.dao.impl.DynamicSchemaDaoImpl.pickRecordOnPriority(DynamicSchemaDaoImpl.java:154) ~[cattle-iaas-model-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.core.dao.impl.DynamicSchemaDaoImpl.getSchemas(DynamicSchemaDaoImpl.java:55) ~[cattle-iaas-model-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.iaas.api.auth.dynamic.DynamicSchemaFactory.listSchemas(DynamicSchemaFactory.java:47) [cattle-iaas-auth-logic-0.5.0-SNAPSHOT.jar:na]
	at io.github.ibuildthecloud.gdapi.request.handler.SchemasHandler.generate(SchemasHandler.java:21) [cattle-framework-java-server-0.5.0-SNAPSHOT.jar:na]
	at io.github.ibuildthecloud.gdapi.request.handler.AbstractResponseGenerator.handle(AbstractResponseGenerator.java:14) [cattle-framework-java-server-0.5.0-SNAPSHOT.jar:na]
	at io.github.ibuildthecloud.gdapi.servlet.ApiRequestFilterDelegate.doFilter(ApiRequestFilterDelegate.java:86) [cattle-framework-java-server-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.api.servlet.ApiRequestFilter$1.runInContext(ApiRequestFilter.java:90) [cattle-framework-api-0.5.0-SNAPSHOT.jar:na]
	at org.apache.cloudstack.managed.context.ManagedContextRunnable$1.run(ManagedContextRunnable.java:49) [cattle-framework-managed-context-0.5.0-SNAPSHOT.jar:na]
	at org.apache.cloudstack.managed.context.impl.DefaultManagedContext$1.call(DefaultManagedContext.java:55) [cattle-framework-managed-context-0.5.0-SNAPSHOT.jar:na]
	at org.apache.cloudstack.managed.context.impl.DefaultManagedContext.callWithContext(DefaultManagedContext.java:108) [cattle-framework-managed-context-0.5.0-SNAPSHOT.jar:na]
	at org.apache.cloudstack.managed.context.impl.DefaultManagedContext.runWithContext(DefaultManagedContext.java:52) [cattle-framework-managed-context-0.5.0-SNAPSHOT.jar:na]
	at org.apache.cloudstack.managed.context.ManagedContextRunnable.run(ManagedContextRunnable.java:46) [cattle-framework-managed-context-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.api.servlet.ApiRequestFilter.doFilter(ApiRequestFilter.java:83) [cattle-framework-api-0.5.0-SNAPSHOT.jar:na]
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652) [jetty-servlet-9.2.11.v20150529.jar:9.2.11.v20150529]
	at org.eclipse.jetty.servlets.UserAgentFilter.doFilter(UserAgentFilter.java:83) [jetty-servlets-9.2.11.v20150529.jar:9.2.11.v20150529]
	at org.eclipse.jetty.servlets.GzipFilter.doFilter(GzipFilter.java:364) [jetty-servlets-9.2.11.v20150529.jar:9.2.11.v20150529]
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652) [jetty-servlet-9.2.11.v20150529.jar:9.2.11.v20150529]
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:585) [jetty-servlet-9.2.11.v20150529.jar:9.2.11.v20150529]
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143) [jetty-server-9.2.11.v20150529.jar:9.2.11.v20150529]
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:577) [jetty-security-9.2.11.v20150529.jar:9.2.11.v20150529]
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:223) [jetty-server-9.2.11.v20150529.jar:9.2.11.v20150529]
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1127) [jetty-server-9.2.11.v20150529.jar:9.2.11.v20150529]
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:515) [jetty-servlet-9.2.11.v20150529.jar:9.2.11.v20150529]
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185) [jetty-server-9.2.11.v20150529.jar:9.2.11.v20150529]
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1061) [jetty-server-9.2.11.v20150529.jar:9.2.11.v20150529]
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141) [jetty-server-9.2.11.v20150529.jar:9.2.11.v20150529]
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97) [jetty-server-9.2.11.v20150529.jar:9.2.11.v20150529]
	at org.eclipse.jetty.server.Server.handle(Server.java:499) [jetty-server-9.2.11.v20150529.jar:9.2.11.v20150529]
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:310) [jetty-server-9.2.11.v20150529.jar:9.2.11.v20150529]
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:257) [jetty-server-9.2.11.v20150529.jar:9.2.11.v20150529]
	at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:540) [jetty-io-9.2.11.v20150529.jar:9.2.11.v20150529]
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635) [jetty-util-9.2.11.v20150529.jar:9.2.11.v20150529]
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555) [jetty-util-9.2.11.v20150529.jar:9.2.11.v20150529]
	at java.lang.Thread.run(Thread.java:745) [na:1.7.0_95]
```

Maybe something was upgraded incorrectly?

**Comment by deniseschannon** [comment] 2016-03-29 17:23
Someone in our Beta program ran into the same issue. This is what he did:
 
Cleared two tables (while server being down): dynamic_schema and dynamic_schema_role, then started the server again. And this time, it came up without all the error messages from the driver, complaining about failed uploads.

Could you try that?

**Comment by deniseschannon** [comment] 2016-03-29 17:23
I just moved his issue out of the "Beta Lounge" on the forums. 

https://forums.rancher.com/t/upgrade-issue-from-0-63-0-to-1-0-0/2199/1

**Comment by lucacri** [comment] 2016-03-29 21:33
Same for me. I tried clearing out the two tables but now it gives me error 500 when i try to check the infrastructure page..

**Comment by deniseschannon** [comment] 2016-03-29 22:05
Did you restart Rancher server?

**Comment by lucacri** [comment] 2016-03-29 22:07
Of course, @deniseschannon. I'm battling it right now (production, everything is down). Also, the rancher server logs are useless since they are spitting pages and pages every second

**Comment by deniseschannon** [comment] 2016-03-29 23:26
@lucacri Can you try "upgrading" rancher server again with your existing DB?

**Comment by deniseschannon** [comment] 2016-03-30 04:15
Can you describe your setup? Are you running HA?

**Comment by ibuildthecloud** [comment] 2016-03-30 04:28
We are still investigating why this error has occured, but the fix should be to run

```sql
DELETE FROM dynamic_schema_role;
DELETE FROM dynamic_schema;
```

And then restart the rancher server.  If you can't have any downtime, the run the above SQL and just `kill -9 go-machine-service` and it should restart and repopulate.

**Comment by lkm** [comment] 2016-03-30 07:33
@deniseschannon Clearing the tables seems to have fixed it completely. Thanks you very much for the quick answer.

**Comment by cjellick** [comment] 2016-03-30 17:58
Might be able to bump to 1.1, but want to talk with @ibuildthecloud about it first.

**Comment by lucacri** [comment] 2016-04-01 03:08
In my case, I had to delete the whole environment, turn off the server, and go on each table and delete any reference of the environment (hosts, instances etc). Some tables had millions of records...

To be fair tho, I have a big environment with 80+ hosts, and 150-200 containers

**Comment by cjellick** [comment] 2016-04-12 16:28
@ibuildthecloud fixed this one in the above referenced PR. It should be in the RC that he built.

I don't have a good way to consistently reproduce though.

**Comment by deniseschannon** [comment] 2016-04-15 15:23
Due to the lack of ability to consistently reproduce, we will close this issue.

**Closed by deniseschannon** 2016-04-15 15:23 UTC
Labels: kind/bug, status/resolved, status/to-test
