### ISSUE TITLE
Unable to promote a worker node to control plane node after deleting a existing control plane node

### ISSUE THREAD

**Issue by bk201** [rancher/rancher#37462] opened 2022-04-25 11:52 UTC
**Rancher Server Setup**
- Rancher version: `v2.6.4`
- Installation option (Docker install/Helm Chart):
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): Helm, v1.21.7+rke2r1 
- Proxy/Cert Details:

**Information about the Cluster**
- Kubernetes version: v1.21.7+rke2r1
- Cluster Type (Local/Downstream): local

**User Information**
- What is the role of the user logged in? (Admin/Cluster Owner/Cluster Member/Project Owner/Project Member/Custom)
  - If custom, define the set of permissions:

   
**Describe the bug**

Unable to promote a worker node to control plane node after deleting a control plane node.

**To Reproduce**
 

- Create a 4-node cluster. (Assume node1~node4). I used rancherd.
- Provision 2 additional workers into control plane roles (by adding `rke.cattle.io/control-plane-role=true rke.cattle.io/etcd-role=true` labels to plan secrets.
- Now we have 3 control plane nodes. Assume node1, node2, and node3.
- Find where `rancher-webhook` pod is, assume it's on `node1`.
- Delete `node1` (`kubectl delete node node1`). In my case I need to destroy node1 VM too, otherwise the agent node will enter NotReady.
- Promote the remaining worker node node4 to control plane node (by adding `rke.cattle.io/control-plane-role=true rke.cattle.io/etcd-role=true` labels to its plan secret.
- node4 can't become a control plane node.

**Result**

The worker can't be promoted to a control plane node.

```
$ kubectl get nodes
NAME    STATUS   ROLES                       AGE    VERSION
node2   Ready    control-plane,etcd,master   144m   v1.21.7+rke2r1
node3   Ready    control-plane,etcd,master   141m   v1.21.7+rke2r1
node4   Ready    <none>                      138m   v1.21.7+rke2r1

$ kubectl get machines -A
NAMESPACE     NAME                  CLUSTER   NODENAME   PROVIDERID     PHASE     AGE    VERSION
fleet-local   custom-aacc7039c8c9   local     node2      rke2://node2   Running   146m
fleet-local   custom-ede0550cacef   local     node3      rke2://node3   Running   143m
fleet-local   custom-f757264128d2   local     node4      rke2://node4   Running   140m

kubectl get secrets -A | grep custom-
fleet-local                              custom-aacc7039c8c9-machine-plan                                    rke.cattle.io/machine-plan                    11     146m
fleet-local                              custom-aacc7039c8c9-machine-plan-token-bs5rc                        kubernetes.io/service-account-token           3      146m
fleet-local                              custom-ede0550cacef-machine-plan                                    rke.cattle.io/machine-plan                    11     143m
fleet-local                              custom-ede0550cacef-machine-plan-token-bj8lp                        kubernetes.io/service-account-token           3      143m
fleet-local                              custom-f757264128d2-machine-plan                                    rke.cattle.io/machine-plan                    11     140m
fleet-local                              custom-f757264128d2-machine-plan-token-9dhxq                        kubernetes.io/service-account-token           3      140m
```

**Expected Result**

The worker should become a control plane node.

**Screenshots**

**Additional context**

- This happens when I delete the control plane node that contains the `rancher-webhook` pod. I can't reproduce this when deleting other control plane nodes.
- After deleting the control plane node, the CAPI cluster `local` enters the "Provisioning" phase:
```
$ kubectl get cluster local -o yaml -n fleet-local
<...>
spec:
  kubernetesVersion: v1.21.7+rke2r1
  localClusterAuthEndpoint: {}
  rkeConfig: {}
status:
  clientSecretName: local-kubeconfig
  clusterName: local
  conditions:
  - status: "True"
    type: Ready
  - lastUpdateTime: "2022-04-25T09:19:48Z"
    status: "False"
    type: Reconciling
  - lastUpdateTime: "2022-04-25T09:19:48Z"
    status: "False"
    type: Stalled
  - lastUpdateTime: "2022-04-25T09:20:47Z"
    status: "True"
    type: Created
  - lastUpdateTime: "2022-04-25T11:42:20Z"
    status: "True"
    type: RKECluster
  - status: Unknown
    type: DefaultProjectCreated
  - status: Unknown
    type: SystemProjectCreated
  - lastUpdateTime: "2022-04-25T11:42:20Z"
    message: 'Operation cannot be fulfilled on secrets "custom-aacc7039c8c9-machine-plan":
      the object has been modified; please apply your changes to the latest version
      and try again'
    reason: Error
    status: "False"
    type: Provisioned
  observedGeneration: 2
  ready: true

$ kubectl get machines -A                                                 1 ↵
NAMESPACE     NAME                  CLUSTER   NODENAME   PROVIDERID     PHASE     AGE    VERSION
fleet-local   custom-aacc7039c8c9   local     node2      rke2://node2   Running   140m
fleet-local   custom-ede0550cacef   local     node3      rke2://node3   Running   137m
fleet-local   custom-f757264128d2   local     node4      rke2://node4   Running   134m
```

- Logs
[rancher-856954cf84-7qvg9.log](https://github.com/rancher/rancher/files/8554212/rancher-856954cf84-7qvg9.log)
[rancher-856954cf84-6cnz5.log](https://github.com/rancher/rancher/files/8554214/rancher-856954cf84-6cnz5.log)
[rancher-856954cf84-8d5jw.log](https://github.com/rancher/rancher/files/8554215/rancher-856954cf84-8d5jw.log)
[rancher-webhook-54c75c9d4-qrfnd.log](https://github.com/rancher/rancher/files/8554217/rancher-webhook-54c75c9d4-qrfnd.log)

**Comment by Oats87** [comment] 2022-04-27 20:17
When deleting the `node1`, are the rest of the `rancherd` processes updated to point to a new designated "init node"?

**Comment by bk201** [comment] 2022-04-28 00:29
@Oats87 I guess no. We use this [rancherd](https://github.com/rancher/rancherd) and it's a one-time process during bootstrap. From my knowledge, it doesn't run during cluster run time.

**Comment by Oats87** [comment] 2022-04-28 15:22
OK. 

Investigation is completed and root cause is determined.

There are two issues at hand here, one of which exists in the "rancherd" realm, and the other which is a minor bug in the planner.

The minor bug in the planner is that when a fixed machine ID is designated on the `rkecontrolplane` object and the planner is unable to find the corresponding machine in the list, it will simply attempt to re-elect a new init node using the standard selection algorithm. This is not desired behavior, and should be fixed to error out instead.

The second issue is that the `clusters.provisioning.cattle.io/local` object has a label on `rancherd` clusters called `rke.cattle.io/init-node-machine-id` which is how we designate a forced init node. From my cursory investigation into the way `rancherd` sets this label, it sets it here: https://github.com/rancher/rancherd/blob/master/pkg/resources/resources.go#L106 

If anything, the fact that nodes could be promoted from worker to controlplane before was actually a bug.

The workaround for this is to simply update the label on the `clusters.provisioning.cattle.io` object for the machine to an existing `controlplane,etcd` machine ID (can be found on the plan secret of the corresponding machine as a label), and the cluster will finish reconciling.

i.e.

```
NAME    STATUS   ROLES                       AGE   VERSION
node2   Ready    control-plane,etcd,master   17d   v1.21.11+rke2r1
node3   Ready    control-plane,etcd,master   17d   v1.21.11+rke2r1
node4   Ready    control-plane,etcd,master   17d   v1.21.11+rke2r1
```

**Comment by bk201** [comment] 2022-05-03 06:51
Thanks, @Oats87, I can confirm the workaround works.

Regarding the second issue, do we need to label `rke.cattle.io/init-node-machine-id` to another existing machine ID when we promote a node (After Rancher fixes the first issue)?

**Comment by Oats87** [comment] 2022-06-24 19:06
> Thanks, @Oats87, I can confirm the [workaround](https://github.com/harvester/harvester/issues/2191#issuecomment-1115794201) works.
> 
> Regarding the second issue, do we need to label `rke.cattle.io/init-node-machine-id` to another existing machine ID when we promote a node (After Rancher fixes the first issue)?

Yes, that is what you have to do.

The issue is that by default, the label is set via a chart, which is difficult to reconcile later on

**Closed** 2022-09-30 06:11 UTC
Labels: [zube]: To Triage, area/rancherd, QA/S, area/harvester, area/provisioning-rke2, feature/rancherd
