### ISSUE TITLE
[Backport 2.5] Cannot upgrade apps with deployments that were created in ember 

### ISSUE THREAD

**Issue by cbron** [rancher/rancher#34832] opened 2021-09-20 20:35 UTC
https://github.com/rancher/rancher/issues/34700

**Comment by MKlimuszka** [comment] 2022-01-11 18:19
Assigning Seb since the original PR author isn't available.

**Comment by anupama2501** [comment] 2022-01-11 18:36
Duplicate of https://github.com/rancher/rancher/issues/35407

**Closed** 2022-01-11 18:36 UTC
Labels: internal, [zube]: Next Up, team/area3
