### ISSUE TITLE
Could not rotate certificates after expirate and upgrade from old version

### ISSUE THREAD

**Issue by dnoland1** [rancher/rancher#20754] opened 2019-06-10 15:59 UTC
**What kind of request is this (question/bug/enhancement/feature request):**
bug

**Steps to reproduce (least amount of steps as possible):**
1. Install v2.0.2 and create a custom cluster.
2. Wait 1+ year for certificates to expire (or change original certs to have a short expiration date).
3. Upgrade v2.0.2 to v2.2.4 using standard upgrade process in docs.
4. Go to cluster and select Rotate Certificates in UI. Rotate for all services.

**Result:**
Certificates failed to rotate correctly.

**Other details that may be helpful:**
@aemneina , @patrick0057 , or @galal-hussein can provide workaround. It involves manually copying certs, reinstalling rancher agent, and restarting kubelet & kube-proxy.

Part of workaround:
```bash
cd /etc/kubernetes/.tmp
cp kube-ca.pem kube-apiserver-requestheader-ca.pem
cp kube-ca-key.pem kube-apiserver-requestheader-ca-key.pem
cp kube-apiserver.pem kube-apiserver-proxy-client.pem
cp kube-apiserver-key.pem kube-apiserver-proxy-client-key.pem
```
**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI):
v2.0.2 / v2.2.4
- Installation option (single install/HA):
single install

**Comment by alena1108** [comment] 2019-06-10 16:26
Closing as a duplicate of https://github.com/rancher/rancher/issues/20381

**Closed by alena1108** 2019-06-10 16:26 UTC
