### ISSUE TITLE
Sharing hosts across environments

### ISSUE THREAD

**Issue by markrey** [rancher/rancher#3619] opened 2016-02-15 18:07 UTC
We are creating "sort of" PaaS based on Rancher for internal development purpose.

- I would like to check if it is possible to share one host across multiple environments so can be used by multiple users.
- Their docker containers inside the hosts should be always hidden ( isolated ) from other environments.

**Comment by deniseschannon** [comment] 2016-02-15 18:24
Duplicate of https://github.com/rancher/rancher/issues/583

**Closed by deniseschannon** 2016-02-15 18:24 UTC

**Comment by markrey** [comment] 2016-02-15 18:27
Thanks Denise. I was trying to find the same.
