### ISSUE TITLE
[BUG] `apply-system-agent-upgrader-windows` pod is in an error state in Windows RKE2 cluster

### ISSUE THREAD

**Issue by sowmyav27** [rancher/rancher#38646] opened 2022-08-17 17:36 UTC
**Rancher Server Setup**
- Rancher version: 2.6.7-rc9
- Installation option (Docker install/Helm Chart): RKE`

**Information about the Cluster**
- Kubernetes version: `v1.24.2+rke2r1`
- Cluster Type (Local/Downstream): Downstream Windows cluster - 1 etcd/control/worker nodes each Linux, 1 windows 2022 worker node

**User Information**
- What is the role of the user logged in? (Admin/Cluster Owner/Cluster Member/Project Owner/Project Member/Custom) admin

**Describe the bug**
[BUG] `apply-system-agent-upgrader-windows` pod is in an error state in Windows RKE2 cluster with  `rancher/wins:v0.4.5` image

**To Reproduce**

- Deploy a windows RKE2 cluster
- `rancher/system-upgrade-controller:v0.8.1` deployment fails to deploy
- `system-upgrade-controller-df77f4dfd-75dtl` is deployed successfully on the control plane linux node
- Notice in the System project page, `apply-system-agent-upgrader-windows` pod is in an error state which is deployed on the windows node

**Note:**
- This issue is seen when monitoring is deployed on the cluster.
- Also seen when you upgrade RKE2 version from 1.23 to 1.24

(SURE-5462)

**Comment by rosskirkpat** [comment] 2022-08-18 16:26
While attempting to reproduce, I found that Microsoft Defender was actively blocking and removing the wins.exe binary. 

```console
bin/wins.exe cli prc run --path="bin\wins.exe" --args="up"
Program 'wins.exe' failed to run: Operation did not complete successfully because the file contains a virus or
potentially unwanted softwareAt line:1 char:1
+ bin/wins.exe cli prc run --path="bin\wins.exe" --args="up"
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~.
At line:1 char:1
+ bin/wins.exe cli prc run --path="bin\wins.exe" --args="up"
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ResourceUnavailable: (:) [], ApplicationFailedException
    + FullyQualifiedErrorId : NativeCommandFailed
```

I have included powershell commands below to disable defender and the docker daemon

```powershell
set-MpPreference -DisableRealtimeMonitoring $true -DisableScriptScanning $true -DisableArchiveScanning $true
stop-process dockerd
stop-service docker
set-service docker -startuptype disabled
```

**Comment by markusewalker** [comment] 2022-08-18 19:43
Awaiting for PR https://github.com/rancher/rancher/pull/38663 to be merged. Once merged, QA will be able to come back and validate this issue with the changes @rosskirkpat has made.

**Comment by markusewalker** [comment] 2022-08-18 21:41
Reproducing this issue still on `v2.6-head` https://github.com/rancher/rancher/commit/e5c6f0f6a44dde287e9423acd99cf906fbda0aa2

1. Setup Rancher and navigate to the UI in a browser.
2. Provisioned two custom RKE2 Windows clusters of K8s version `v1.23.7+rke2r1`; verify that the cluster and nodes all come up as `Active` in Cluster Explorer and Cluster Management.
     - For the Windows node, ensure that Microsoft Defender and Docker daemon are disabled with the following commands in Windows Powershell:

```
set-MpPreference -DisableRealtimeMonitoring $true -DisableScriptScanning $true -DisableArchiveScanning $true
stop-process dockerd
stop-service docker
set-service docker -startuptype disabled
```

![image](https://user-images.githubusercontent.com/52591819/185500146-9c5ef3f0-69c4-448f-ba6d-efa1a9c4974f.png) 
3. Assigned the standard user as a Cluster Owner to both of the clusters and logged into Rancher as that user.
4. For both of the clusters, installed the Monitoring chart; verified this was successful:
![image](https://user-images.githubusercontent.com/52591819/185500118-b9d2f0e6-5818-41b8-98c0-ac9d7af897d0.png)
![image](https://user-images.githubusercontent.com/52591819/185500126-1c5997e8-785b-4dd1-a5fe-c2e85bdca491.png)

5. For both of the clusters, navigated to Cluster Explorer > cluster > Workloads > Deployment.
6. In both of the clusters, verified that this issue is still occurring:
![image](https://user-images.githubusercontent.com/52591819/185500091-66aec00d-8ac4-41ce-b55a-e474bac59ed6.png)

One of the clusters I provisioned is intended to be upgraded to `v1.24.2+rke2r1`, but considering the reproduction, I did not upgrade as it is failing regardless.

**Comment by jameson-mcghee** [comment] 2022-08-24 15:06
**Intended Test Setup**
-	Rancher version(s): v2.6-head
-	Browser type & version: Brave & Most Current
-	Rancher Host: EC2 (Jenkins Job)
-	Rancher Setup:
o	RANCHER_HA_CERT_OPTION: byo-valid
o	RKE_VERSION: 1.3.13-rc4
o	AWS_VOLUME_SIZE: 20
o	AWS_AMI: ami-066f14e43aebc7472
o	AWS_SECURITY_GROUPS: sg-0e753fd5550206e55 (open-all)
o	AWS_INSTANCE_TYPE: t3a.xlarge
o	AWS_VPC: vpc-bfccf4d7
o	AWS_SUBNET: subnet-ee8cac86
o	AWS_REGION: us-east-2
-	Deployment Type: Helm
-	User Permission: Admin and Standard User

**Test Approach**
-	Verify that when I deploy a Windows node on an RKE2 custom cluster, that the rancher/system-upgrade-controller:v0.8.1  is able to deploy successfully
-	Verify that on the System project page, the apply-system-agent-upgrader-windows pod is not in an error state
-	Verify that the Windows node goes “Active” in Rancher
Verify that multiple Windows nodes can be deployed on a cluster without error
-	Verify that upgrading from RKE2 1.23 to 1.24 does not reproduce this error
-	Verify that deploying monitoring on the cluster does not reproduce this issue

cc @markusewalker

**Comment by ebenezar-mccoy** [comment] 2022-09-29 15:12
Hey guys, do you have an update on this one?

I am able to reproduce this on 
2.6.8 
v1.24.4-rke2r1-85bc7d7bec85

**Comment by jostmart** [comment] 2022-10-07 16:27
Same here. Exact same environment as ebenazar-mccoy.
Defender have been disabled like this:

```
Set-MpPreference -DisableRealtimeMonitoring $true"  -DisableScriptScanning $true -DisableArchiveScanning $true"
Set-MpPreference -ExclusionPath  C:\\var\\lib
```

I'm not excluding any docker directory since this is on containerd hosts.

**Comment by Dbaker1298** [comment] 2022-10-09 04:46
This happened today with a custom install:

- Rancher v2.6.8
- RKE2 v1.24.4+rke2r1
- Image: rancher/wins:v0.4.7
- system-upgrade-controller v0.9.1
- Windows (Windows Server 2022 Datacenter Azure Edition), Standard D2s v3 (2 vcpus, 8 GiB memory)
- The same `Set-MpPreference` was applied.

![image](https://user-images.githubusercontent.com/44222557/194737396-31110fa5-c543-4f64-89b5-f01f166efec9.png)

![image](https://user-images.githubusercontent.com/44222557/194737501-39c6e99e-db16-4f7c-9df4-7400bf634f8a.png)

Trying to delete the Installed App is not successful:
![image](https://user-images.githubusercontent.com/44222557/194737555-a414e244-c3fa-4086-9ae2-bc8a51221977.png)

I deleted the Deployment and the Job because too many pods were in an error state.

Pod describe on one of the failed pods:
[pod-describe-failed-pod.txt](https://github.com/rancher/rancher/files/9740756/pod-describe-failed-pod.txt)


Windows Server logs:
[windows-server-logs.log](https://github.com/rancher/rancher/files/9740755/windows-server-logs.log)

**Comment by jameson-mcghee** [comment] 2022-10-10 19:04
QA TEST PLAN
| Scenarios | Test Case |
|-------------------------------|
| 1 | Fresh install with highest K8s version for RKE2 node driver cluster as Admin User, deploying monitoring |
| 2 | Fresh install with K8s version 1.23 upgraded to K8s version 1.24 for RKE2 node driver cluster as Standard User with Cluster Owner role |

**Comment by ebenezar-mccoy** [comment] 2022-10-11 20:13
I have tested Rancher 2.6.8 RKE2 v1.22, v1.23, v1.24, they all seems to have the same issue.
In addition, Windows Worker is not able to connect back to the cluster after a reboot

**Comment by Haargrad** [comment] 2022-10-20 09:18
I have tested Rancher 2.6.8 RKE2 v1.23, v1.24, they all seems to have the same issue.

![image](https://user-images.githubusercontent.com/61315483/196908797-11e81ef8-8ea5-41b3-9800-eb5a7e5396e0.png)

![image](https://user-images.githubusercontent.com/61315483/196908921-7d822d00-74c4-489f-8827-1bc5191d7a29.png)

**Comment by marekvesely-direct** [comment] 2023-04-19 12:54
Hello, for me the same issue, I have Rocky Linux 8 servers and apply-system-agent-upgrader-* pods are faile with message:
```
exec /opt/rancher-system-agent-suc/run.sh: argument list too long
```
I didnt find any solution how to fix this... :( Rancher version 2.7.2, latest K8s version installing and Canal network. No additional configuration of Linux servers as it doen't need anything...

**Comment by snasovich** [comment] 2023-06-16 15:58
The next step for this issue is to re-test once QA team has capacity as the exact issue in the description is likely fixed per the previous comment from @aiyengar2 .

**Comment by slickwarren** [comment] 2023-06-16 22:16
tested on rancher:v2.7-head (9a33c24) and wins rancher/wins:v0.4.11
* deploy a custom rke2 cluster (1etcd, 1cp, 1worker, 1 windows node) -- all pods in a healthy state -- pass
* upgrade a windows cluster -- all pods finish upgrading and are in a healthy state -- FAIL
  * filed this blocker issue: https://github.com/rancher/rancher/issues/41868

**Comment by slickwarren** [comment] 2023-07-17 20:14
tested on version 2.7-head (58aede6) upgrading windows cluster from 1.25.11+rke2r1 -> 1.26.6+rke2r1 -- pass

**Closed by slickwarren** 2023-07-17 20:14 UTC
Labels: kind/bug, priority/0, area/windows, [zube]: To Test, QA/S, team/area2

**Comment by axeal** [comment] 2023-12-15 13:57
> Hello, for me the same issue, I have Rocky Linux 8 servers and apply-system-agent-upgrader-* pods are failed with message:
> 
> ```
> exec /opt/rancher-system-agent-suc/run.sh: argument list too long
> ```
> 
> I didnt find any solution how to fix this... :( Rancher version 2.7.2, latest K8s version installed and Canal network. No additional configuration of Linux servers as it doen't need anything...

@marekvesely-direct This error message is unrelated to the issue reported in this GitHub issue, and can instead be triggered by a misconfigured tls-ca Secret in the cattle-system Namespace of the Rancher local cluster.

Where the Rancher TLS certificate is signed by a private CA, or requires intermediate certificate(s) to establish chain of trust to a publicly trusted root CA, the tls-ca secret should contain the root CA, followed by any intermediate certificates:(https://ranchermanager.docs.rancher.com/getting-started/installation-and-upgrade/resources/add-tls-secrets#using-a-private-ca-signed-certificate).

These cacerts are retrieved from Rancher by the cluster-agent in a downstream cluster, which populates the ca.crt field of the stv-aggregation Secret in the cattle-system Namespace with their contents.

The stv-aggregation Secret is then populated as environment variables in the upgrade container of the `apply-system-agent-upgrader-*` Job Pods via an envFrom reference:

```
    envFrom:
    - secretRef:
        name: stv-aggregation
```

As a result, if the tls-ca Secret in the Rancher local cluster is misconfigured, for example with a complete list of an organizations CA certificates, the resulting environment variable in the `apply-system-agent-upgrader-*` Job can be too large, leading to an `exec /opt/rancher-system-agent-suc/run.sh: argument list too long` attempting to run the Pod.

This state can be resolved by recreating the tls-ca certificate with only the Rancher root CA (and any intermediate certificates) and performing a rollout restart of the Rancher deployment (https://ranchermanager.docs.rancher.com/getting-started/installation-and-upgrade/resources/update-rancher-certificate#2-createupdate-the-ca-certificate-secret-object).

**Comment by maksimmuravev** [comment] 2024-05-13 07:17
```bash
$ kubectl describe secret/stv-aggregation 
```

This is probably a CA issue for those who see such a huge cert's size.

```
Type:  Opaque

Data
====
ca.crt:              226116 bytes
token:               66 bytes
url:                 42 bytes
CATTLE_CA_CHECKSUM:  64 bytes
CATTLE_SERVER:       31 bytes
CATTLE_TOKEN:        54 bytes
```
