### ISSUE TITLE
[BUG] Deleting a master node breaks RKE2 cluster

### ISSUE THREAD

**Issue by thomashoell** [rancher/rancher#42034] opened 2023-07-07 12:02 UTC
**Rancher Server Setup**
- Rancher version: 2.7.5 (Issue was probably introduced in 2.7.5)
- Installation option (Docker install/Helm Chart): Helm
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): 1.25.11+rke2r1

**Information about the Cluster**
- Kubernetes version: 1.25.10+rke2r1,1.26.5+rke2r1 (at least)
- Cluster Type (Local/Downstream):
   - Downstream via vSphere.

**User Information**
- What is the role of the user logged in? Admin

**Describe the bug**
We were trying to swap the master nodes (Control Plane + etcd) of one of our clusters due to a image template update.
The new node was spawned and joined the cluster. However, when one of the existing old masters was to be removed, the current bootstrap-node gets stuck in _Reconciling_ state. 
Upon further investigation, it looks like the etcd configuration on the remaining masters is broken. The endpoints aren't updated properly and the leader election process fails. As a result, the whole cluster API is broken.
Rancher also doesn't notice that the old master was already deleted by vSphere.

**To Reproduce**
- create a RKE2 cluster with vSphere  (master pool (control plane and etcd), worker pool)
- execute an action which involves removing a node from the master pool (scale down, change node template)

**Result**
Bootstrap Node and node to be removed both get stuck in _Reconciling_ state, Control Plane is unresponsive. Also, Rancher doesn't detect that the node which was to be removed already got deleted by vSphere:
![image](https://github.com/rancher/rancher/assets/4695168/ae1355ad-48c8-4ff9-868a-7f24cd2ab9cc)
![image](https://github.com/rancher/rancher/assets/4695168/c0bb7dcc-a453-4d56-94a9-84e9517c6dbb)

**Expected Result**
Node gets removed, stable API

**Additional context**
I tried to pin down the problem by creating separate node pools for API, etcd and worker. However, creating a cluster with dedicated node pools per role doesn't seem possible. The bootstrap node (etcd) doesn't know where the control plane is and tries to talk to https://127.0.0.1:6443. The cluster never comes up:
```
Jul 07 11:01:21 ws3-test-etcd-42e6121c-b8xl6 rke2[5398]: time="2023-07-07T11:01:21Z" level=info msg="Waiting to retrieve kube-proxy configuration; server is not ready: https://127.0.0.1:6444/v1-rke2/readyz: 500 Internal Server Error"
Jul 07 11:01:21 ws3-test-etcd-42e6121c-b8xl6 rke2[5398]: time="2023-07-07T11:01:21Z" level=info msg="Waiting for apiserver addresses"
Jul 07 11:01:24 ws3-test-etcd-42e6121c-b8xl6 rancher-system-agent[2676]: time="2023-07-07T11:01:24Z" level=error msg="error encountered during parsing of last run time: parsing time \"\" as \"Mon Jan _2 15:04:05 MST 2006\": cannot parse \"\" as \"Mon\""
Jul 07 11:01:26 ws3-test-etcd-42e6121c-b8xl6 rke2[5398]: time="2023-07-07T11:01:26Z" level=info msg="Waiting to retrieve kube-proxy configuration; server is not ready: https://127.0.0.1:6444/v1-rke2/readyz: 500 Internal Server Error"
Jul 07 11:01:26 ws3-test-etcd-42e6121c-b8xl6 rke2[5398]: time="2023-07-07T11:01:26Z" level=info msg="Waiting for apiserver addresses"
Jul 07 11:01:29 ws3-test-etcd-42e6121c-b8xl6 rancher-system-agent[2676]: time="2023-07-07T11:01:29Z" level=error msg="error encountered during parsing of last run time: parsing time \"\" as \"Mon Jan _2 15:04:05 MST 2006\": cannot parse \"\" as \"Mon\""
Jul 07 11:01:31 ws3-test-etcd-42e6121c-b8xl6 rke2[5398]: time="2023-07-07T11:01:31Z" level=info msg="Waiting to retrieve kube-proxy configuration; server is not ready: https://127.0.0.1:6444/v1-rke2/readyz: 500 Internal Server Error"
Jul 07 11:01:31 ws3-test-etcd-42e6121c-b8xl6 rke2[5398]: time="2023-07-07T11:01:31Z" level=info msg="Waiting for apiserver addresses"
Jul 07 11:01:34 ws3-test-etcd-42e6121c-b8xl6 rancher-system-agent[2676]: time="2023-07-07T11:01:34Z" level=error msg="error encountered during parsing of last run time: parsing time \"\" as \"Mon Jan _2 15:04:05 MST 2006\": cannot parse \"\" as \"Mon\""
Jul 07 11:01:34 ws3-test-etcd-42e6121c-b8xl6 rke2[5398]: time="2023-07-07T11:01:34Z" level=info msg="Waiting for API server to become available"
Jul 07 11:01:36 ws3-test-etcd-42e6121c-b8xl6 rke2[5398]: time="2023-07-07T11:01:36Z" level=info msg="Waiting to retrieve kube-proxy configuration; server is not ready: https://127.0.0.1:6444/v1-rke2/readyz: 500 Internal Server Error"
Jul 07 11:01:36 ws3-test-etcd-42e6121c-b8xl6 rke2[5398]: time="2023-07-07T11:01:36Z" level=info msg="Waiting for apiserver addresses"
```

EDIT: It doesn't seem to matter how many nodes are in the master pool.

**Comment by Oats87** [comment] 2023-07-07 19:23
To clarify, how many etcd nodes did you have in your cluster? From your screenshot it appears that you only had 1 active etcd node.

**Comment by thomashoell** [comment] 2023-07-10 06:42
> To clarify, how many etcd nodes did you have in your cluster? From your screenshot it appears that you only had 1 active etcd node.

Just to be clear: I did **NOT** try to remove my last etcd node.

We initially observed the problem when we were trying to swap out master pool (3 nodes) for fresh nodes with a new image template. We added the new pool (6 master nodes in total) and began to scale down the old master pool. When the first node of the old masters was about to be removed, the problem occurred.

This can also be reproduced by following these steps:

- create a fresh cluster (1 master, 1 worker)
- add a 2nd master (everything's still fine)
- remove one of the two masters

**Comment by Oats87** [comment] 2023-07-10 13:56
Similar issue, but with K3s: https://github.com/rancher/rancher/issues/41126

**Comment by Oats87** [comment] 2023-07-10 22:38
Thank you for taking the time to report this issue @thomashoell -- I can confirm that I was able to reproduce this bug, and it seems that the primary cause for this issue is around etcd scaling logic. The etcd nodes must be scaling to a new quantity where it would be losing quorum (in this case, 2 -> 1), and the quorum loss prevention logic not firing due to a logical fallacy in the `rkebootstrap` controller.

There is logic built into Rancher that attempts to perform a safe removal of the node from etcd before allowing the node infrastructure to be removed. It does this through the use of a CAPI-specific annotation around `pre-termination`. Unfortunately, the reconciliation logic in the existing rkebootstrap provider does not properly annotate the owning machine. Manually annotating the machine object is not an effective workaround in this case as the responsible controller will not properly act upon a deletion of the machine object.

This is specifically exasperated in the case where the cluster is a machine provisioned cluster, as the underlying infrastructure is removed as soon as the deletion is requested -- in the case of a custom cluster, depending on infrastructure management, it is possible that the deleting node is alive for long enough to handle its own removal by the CAPI controllers. 

I'll be opening a PR in the coming hours along with additional test cases to specifically test for this scenario -- it appears our current integration testing suite is not comprehensive enough to handle this edge case. I have a WIP PR with a logic fix that appears to solve this issue in the meantime.

The best way to recover from this will be to perform an etcd restore in your cluster -- the CAPR provider will properly "remove" the orphaned etcd nodes and should restore your cluster from backup. If you do not have an etcd snapshot, it is possible to manually force quorum restoration of the underlying RKE2 cluster by following the relevant RKE2 documentation -- at which point the cluster should recover once the `cattle-cluster-agent` is able to connect to Rancher.

In the meantime, given the high likelihood of accidentally encountering this bug, I am going to set appropriate milestones to ship the fix for this sooner rather than later. 

/cc @snasovich @Sahota1225 @jakefhyde

**Comment by thomashoell** [comment] 2023-07-11 13:23
> Thank you for taking the time to report this issue @thomashoell -- I can confirm that I was able to reproduce this bug, and it seems that the primary cause for this issue is around etcd scaling logic. The etcd nodes must be scaling to a new quantity where it would be losing quorum (in this case, 2 -> 1), and the quorum loss prevention logic not firing due to a logical fallacy in the `rkebootstrap` controller.
> 
> There is logic built into Rancher that attempts to perform a safe removal of the node from etcd before allowing the node infrastructure to be removed. It does this through the use of a CAPI-specific annotation around `pre-termination`. Unfortunately, the reconciliation logic in the existing rkebootstrap provider does not properly annotate the owning machine. Manually annotating the machine object is not an effective workaround in this case as the responsible controller will not properly act upon a deletion of the machine object.
> 
> This is specifically exasperated in the case where the cluster is a machine provisioned cluster, as the underlying infrastructure is removed as soon as the deletion is requested -- in the case of a custom cluster, depending on infrastructure management, it is possible that the deleting node is alive for long enough to handle its own removal by the CAPI controllers.
> 
> I'll be opening a PR in the coming hours along with additional test cases to specifically test for this scenario -- it appears our current integration testing suite is not comprehensive enough to handle this edge case. I have a WIP PR with a logic fix that appears to solve this issue in the meantime.
> 
> The best way to recover from this will be to perform an etcd restore in your cluster -- the CAPR provider will properly "remove" the orphaned etcd nodes and should restore your cluster from backup. If you do not have an etcd snapshot, it is possible to manually force quorum restoration of the underlying RKE2 cluster by following the relevant RKE2 documentation -- at which point the cluster should recover once the `cattle-cluster-agent` is able to connect to Rancher.
> 
> In the meantime, given the high likelihood of accidentally encountering this bug, I am going to set appropriate milestones to ship the fix for this sooner rather than later.
> 
> /cc @snasovich @Sahota1225 @jakefhyde

@Oats87 thanks for the comprehensive explanation! 

We rebuilt the cluster from scratch. It was one of the less important ones and managed by Fleet anyways.

**Comment by thaneunsoo** [comment] 2023-07-11 16:31
### Test Environment: ###
Rancher version: v2.7.4
Rancher cluster type: single-node docker install
Docker version: 20.10

Downstream cluster type: rke2 vSphere node driver cluster

----------

### Testing: ###
Tried to reproduced with the following steps:
1. create a fresh cluster (1 master, 1 worker)
2. add a 2nd master (everything's still fine)
3. remove one of the two masters

**Result**
I was not able to reproduce the issue on v2.7.4 and the master node was successfully removed. Confirming this is a regression.
<img width="1458" alt="image" src="https://github.com/rancher/rancher/assets/108360907/4c42dfd2-4747-4da7-a1d1-dde666056e19">

**Comment by thaneunsoo** [comment] 2023-07-24 20:30
### Test Environment: ###
Rancher version: v2.7-head dc105f0
Rancher cluster type: single-node docker install
Docker version: 20.10

Downstream cluster type: rke2 vSphere node driver cluster

----------

### Testing: ###
Tested this issue with the following steps:
1. create a fresh cluster (1 master, 1 worker)
2. add a 2nd master (everything's still fine)
3. remove one of the two masters

**Result**
I was not able to reproduce the issue anymore and the master node was successfully removed.

**Closed by thaneunsoo** 2023-07-24 20:30 UTC
Labels: kind/bug, [zube]: QA Working, QA/S, area/provisioning-v2, team/area2, regression
