### ISSUE TITLE
rancher-nfs makes call back to rancher server and fails when self-signed certs are in play

### ISSUE THREAD

**Issue by aemneina** [rancher/rancher#8186] opened 2017-03-16 00:23 UTC
**Rancher Versions:**
Server:1.3.4

**Docker Version:**
1.12.6

**OS and where are the hosts located? (cloud, bare metal, etc):**
on-prem rhel 7.3

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
HA + self signed certs

**Steps to Reproduce:**
1. self signed certificate for rancher server termination
2. add hosts (verification that self signed cert was added correctly to the agent hosts)
3. start rancher nfs

**Results:** 
rancher nfs on startup calls rancher server url for config? complains about cert and fails.

`level=fatal msg="Get https://<rancher_server_uri>/v2-beta: x509: certificate signed by unknown authority"`

**Comment by LLParse** [comment] 2017-03-16 01:35
Duplicate of https://github.com/rancher/rancher/issues/7270.

Please upgrade to Rancher server v1.4.0+ and use the new template version `0.2.2`.

**Closed by LLParse** 2017-03-16 01:35 UTC
Labels: area/catalog-service, kind/bug

**Comment by aemneina** [comment] 2017-03-16 05:46
awesome, thanks @LLParse
