### ISSUE TITLE
unable to host rancher behind a reverse proxy

### ISSUE THREAD

**Issue by ka2er** [rancher/rancher#719] opened 2015-05-05 18:20 UTC
If I try to host ranger behind a reverse proxy it try to load ressources with ip of the container.
Why don't you just use relative ressource as it will occult this problem.
I tried also with env variable CATTLE_AGENT_IP=fqn.tld.fr ...

I face the following error for example 

Mixed Content: The page at 'https://fqn.tld.fr/static/' was loaded over HTTPS, but requested an insecure XMLHttpRequest endpoint 'http://10.0.0.1:5049/v1/hosts?include=agent&include=instances&include=ipAddresses'. This request has been blocked; the content must be served over HTTPS.

**Comment by glanzi** [comment] 2015-06-03 09:25
+1 I am also interested in a solution to host Ranger behind a reverse proxy.

**Comment by vincentbernat** [comment] 2015-07-09 13:25
With a more recent release, I am able to use a reverse proxy but it still falls back to HTTP when accessed over HTTPS:

> Mixed Content: The page at 'https://1efaf4bf.ngrok.com/services/welcome' was loaded over HTTPS, but requested an insecure XMLHttpRequest endpoint 'http://1efaf4bf.ngrok.com/v1/projects?all=true&limit=1000'. This request has been blocked; the content must be served over HTTPS.

The problem seems to be somewhere in EmberJS.

**Comment by vincentbernat** [comment] 2015-07-09 13:36
Notably, I have this in the headers:

```
x-api-schemas: http://1efaf4bf.ngrok.com/v1/schemas
```

I am unable to understand which component is building this header.

**Comment by vincentbernat** [comment] 2015-07-09 13:42
@ka2er @glanzi If you still have the problem, I suggest that you also set the `Host` header when forwarding. With nginx, this can be done with:

```
proxy_set_header Host $host;
```

But, the SSL problem will still be here.

**Comment by vincent99** [comment] 2015-07-09 15:36
Links in the API are absolute, so the server needs to know what the right URL is.   We will be adding support for the more standard x-forwarded-host/proto soon but for now:

http://rancher.docs.rancher.com/docs/installing-rancher/installing-server/basic-ssl-config/

**Comment by andreis** [comment] 2015-07-13 08:46
The TLS setup in the docs works for me, but I ran into some issues with Github issues - details [on IRC](https://botbot.me/freenode/rancher/2015-07-13/?msg=44359450&page=1). Can you point me in the right direction, please?

**Comment by vincent99** [comment] 2015-07-13 17:11
The problem with GitHub is the `proxy_buffer_size 512` in the SSL instructions.. but if you don't do that then the agent connection to the hosts is buffered long enough that they think they are disconnected.  So there is really no good way to setup SSL + Github right now.  We're working on solving the host connection issue by switching it to WebSocket instead of a never-ending http connection that gets buffered, and after that is fixed you'll be able to remove the proxy _buffer lines.

**Comment by andreis** [comment] 2015-07-14 08:14
@vincent99 Thank you for your answer! If you remember, please ping me here when it's implemented.

**Comment by andreis** [comment] 2015-07-14 08:15
Also, thank you for Rancher. We looked at it a couple of months ago and it was definitely not mature enough, but now it seems like it fits our use case perfectly, and comes with heaps of functionality.

**Comment by cjellick** [comment] 2015-07-28 21:45
Fixed. The host and x-forwarded-{port,proto} headers are now supported. They will be in release v0.31.0, assuming it passes QA.

The other required changes (ie, switching to websockets) are implemented and already in the "latest" tag of rancher/server.

**Comment by deitch** [comment] 2015-07-29 15:02
Hey @cjellick I just opened an issue on the forums, then stumbled across this issue. So the problem is the X-API-Schemas not properly handling the forwarded `x-forwarded-port` and `x-forwarded-proto`?

**Comment by cjellick** [comment] 2015-07-29 15:34
@deitch Would you be willing to share your proxy configuration so that I can attempt to reproduce? Feel free to mask any sensitive bits like IPs or domain names.

The current version of rancher/server:latest doesn't support the Host and X-Forwarded-{Proto|Port} headers at all. The next version will. So, the configuration that will work with the current version is waht is described here:
http://docs.rancher.com/rancher/installing-rancher/installing-server/basic-ssl-config/

**Comment by deitch** [comment] 2015-07-29 16:16
I would be happy to... if I hadn't already killed the ec2 instance! I kind of gave up on it, figured I would readdress when 0.31 comes out. 

I am pretty sure that I followed the following, though

````
upstream rancher {
    server 10.11.12.13:8080;
}

server {
    listen 8080;

    location / {
        proxy_pass http://rancher;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Forwarded-Port $server_port;
    }
}

````

**Comment by cjellick** [comment] 2015-07-29 16:43
Yes, if that's what you had, it definitely would not have worked as those headers wont be supported to v0.31.0

So... Coming Soon!™

**Comment by deitch** [comment] 2015-07-29 16:44
Got it. Is there a proper way to do it in 0.30?

**Comment by cjellick** [comment] 2015-07-29 16:53
http://docs.rancher.com/rancher/installing-rancher/installing-server/basic-ssl-config/
With an emphasis on this line:
```
proxy_set_header X-API-request-url $scheme://<host>$request_uri;
```

**Comment by sangeethah** [comment] 2015-07-29 20:01
Tested with rancher/server:v0.31.0-rc1

Able to bring up a rancher-server with SSL behind Nginx as https reverse proxy.
Following are the steps followed:

```
docker run -d --restart=always --name=rancher-server -e "CATTLE_API_ALLOW_CLIENT_OVERRIDE=true" rancher/server:v0.31.0-rc1
mkdir /root/nginx

docker run -d -p 80:80 -p 443:443 -v /root/nginx/ssl:/etc/nginx/ssl/:ro -v /root/nginx/rancher.io.conf:/etc/nginx/conf.d/rancher.io.conf:ro --link='rancher-server' nginx

nginx confifuration used:

upstream rancher {
    server rancher-server:8080;
}

server {
    listen 443 ssl;
    server_name <servername>;
    ssl_certificate /etc/nginx/ssl/rancher.io.bundled.crt;
    ssl_certificate_key /etc/nginx/ssl/rancher.io.key;

    location / {
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Forwarded-Port $server_port;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_pass http://rancher;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
    }
}

server {
    listen 80;
    server_name <servername>;
    return 301 https://$server_name$request_uri;
}
```
Able to add custom hosts , Digital Ocean hosts to rancher server successfully.
Able to view host stats.
Able to view container logs and also exec shell.
Basic sanity checks to make sure that the connectivity between containers from different hosts work.

**Closed by sangeethah** 2015-07-29 20:01 UTC
Labels: area/ssl, kind/enhancement, status/resolved, status/to-test
