### ISSUE TITLE
Kubelet not starting up on RHEL7.2 with Docker 1.12.1  and Docker 1.11.2 (Kubernetes 1.4)

### ISSUE THREAD

**Issue by soumyalj** [rancher/rancher#6181] opened 2016-10-06 20:57 UTC
**Rancher Version:**: v1.2.0-pre3

**Docker Version:**: 1.12.1 and 1.11.2

**OS and where are the hosts located? (cloud, bare metal, etc):**RHEL, Cloud

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**: Kubernetes 1.4

**Steps to Reproduce:**
1. Create a Kubernets setup on RHEL7.2 with Docker 1.12.1. Used https://github.com/rancher/rancher-catalog with qa branch

Kubelet does not startup successfully.

The error messages seen in Kubelet logs : 

```
10/6/2016 1:57:44 PMI1006 20:57:44.167030   12248 server.go:714] Started kubelet v1.4.0-beta.6.57+35af298308f3c9
10/6/2016 1:57:44 PME1006 20:57:44.167741   12248 kubelet.go:1094] Image garbage collection failed: unable to find data for container /
10/6/2016 1:57:44 PMI1006 20:57:44.169168   12248 server.go:118] Starting to listen on 0.0.0.0:10250
10/6/2016 1:57:44 PMI1006 20:57:44.198317   12248 kubelet_node_status.go:194] Setting node annotation to enable volume controller attach/detach
10/6/2016 1:57:44 PMI1006 20:57:44.198382   12248 rancher.go:592] ExternalID [soumyanewredhatk8test2]
10/6/2016 1:57:44 PMI1006 20:57:44.198387   12248 rancher.go:598] InstanceID [soumyanewredhatk8test2]
10/6/2016 1:57:44 PMI1006 20:57:44.285775   12248 rancher.go:598] InstanceID [soumyanewredhatk8test2]
10/6/2016 1:57:44 PMI1006 20:57:44.371095   12248 rancher.go:598] InstanceID [soumyanewredhatk8test2]
10/6/2016 1:57:44 PMI1006 20:57:44.469713   12248 kubelet_node_status.go:236] Adding node label from cloud provider: beta.kubernetes.io/instance-type=rancher
10/6/2016 1:57:44 PMI1006 20:57:44.469762   12248 kubelet_node_status.go:247] Adding node label from cloud provider: failure-domain.beta.kubernetes.io/zone=FailureDomain1
10/6/2016 1:57:44 PMI1006 20:57:44.469774   12248 kubelet_node_status.go:251] Adding node label from cloud provider: failure-domain.beta.kubernetes.io/region=Region1
10/6/2016 1:57:44 PME1006 20:57:44.559734   12248 kubelet.go:2127] Failed to check if disk space is available for the runtime: failed to get fs info for "runtime": unable to find data for container /
10/6/2016 1:57:44 PME1006 20:57:44.559757   12248 kubelet.go:2135] Failed to check if disk space is available on the root partition: failed to get fs info for "root": unable to find data for container /
10/6/2016 1:57:44 PMI1006 20:57:44.562028   12248 fs_resource_analyzer.go:66] Starting FS ResourceAnalyzer
10/6/2016 1:57:44 PMI1006 20:57:44.562061   12248 status_manager.go:129] Starting to sync pod status with apiserver
10/6/2016 1:57:44 PMI1006 20:57:44.562074   12248 kubelet.go:2229] Starting kubelet main sync loop.
10/6/2016 1:57:44 PMI1006 20:57:44.562083   12248 kubelet.go:2240] skipping pod synchronization - [network state unknown container runtime is down]
10/6/2016 1:57:44 PME1006 20:57:44.562283   12248 container_manager_linux.go:567] error opening pid file /var/run/docker.pid: open /var/run/docker.pid: no such file or directory
10/6/2016 1:57:44 PME1006 20:57:44.591127   12248 container_manager_linux.go:567] error opening pid file /run/docker/libcontainerd/docker-containerd.pid: open /run/docker/libcontainerd/docker-containerd.pid: no such file or directory
10/6/2016 1:57:44 PMI1006 20:57:44.596088   12248 volume_manager.go:234] Starting Kubelet Volume Manager
10/6/2016 1:57:44 PME1006 20:57:44.663661   12248 container_manager_linux.go:567] error opening pid file /var/run/docker.pid: open /var/run/docker.pid: no such file or directory
10/6/2016 1:57:44 PME1006 20:57:44.679690   12248 factory.go:291] devicemapper filesystem stats will not be reported: unable to find thin_ls binary
10/6/2016 1:57:44 PMI1006 20:57:44.679721   12248 factory.go:295] Registering Docker factory
10/6/2016 1:57:44 PMW1006 20:57:44.679738   12248 manager.go:244] Registration of the rkt container factory failed: unable to communicate with Rkt api service: rkt: cannot tcp Dial rkt api service: dial tcp [::1]:15441: getsockopt: connection refused
10/6/2016 1:57:44 PMI1006 20:57:44.679743   12248 factory.go:54] Registering systemd factory
10/6/2016 1:57:44 PMI1006 20:57:44.679898   12248 factory.go:86] Registering Raw factory
10/6/2016 1:57:44 PMI1006 20:57:44.680024   12248 manager.go:1082] Started watching for new ooms in manager
10/6/2016 1:57:44 PMI1006 20:57:44.715262   12248 oomparser.go:185] oomparser using systemd
10/6/2016 1:57:44 PMI1006 20:57:44.717853   12248 manager.go:285] Starting recovery of all containers
10/6/2016 1:57:44 PMI1006 20:57:44.727553   12248 kubelet_node_status.go:194] Setting node annotation to enable volume controller attach/detach
10/6/2016 1:57:44 PMI1006 20:57:44.727580   12248 rancher.go:592] ExternalID [soumyanewredhatk8test2]
10/6/2016 1:57:44 PMI1006 20:57:44.727609   12248 rancher.go:598] InstanceID [soumyanewredhatk8test2]
10/6/2016 1:57:44 PMI1006 20:57:44.823536   12248 rancher.go:598] InstanceID [soumyanewredhatk8test2]
10/6/2016 1:57:44 PMI1006 20:57:44.918022   12248 rancher.go:598] InstanceID [soumyanewredhatk8test2]
10/6/2016 1:57:44 PMI1006 20:57:44.967239   12248 manager.go:290] Recovery completed
10/6/2016 1:57:44 PMF1006 20:57:44.979587   12248 kubelet.go:1149] Failed to start cAdvisor inotify_add_watch /sys/fs/cgroup/cpuacct,cpu: no such file or directory
Disconnected
```

Kubernetes does startup successfully

**Comment by wlan0** [comment] 2016-10-18 23:03
This is a kubelet issue - https://github.com/kubernetes/kubernetes/issues/32728

the embedded cadvisor should be able to work with cgroups properly, and will be fixed in the future versions of kubelet. 

Until then, I have verified that running this command on the host fixes the issue 

```
  sudo mount -o remount,rw '/sys/fs/cgroup'
  sudo ln -s /sys/fs/cgroup/cpu,cpuacct /sys/fs/cgroup/cpuacct,cpu
```

**Comment by derekwaynecarr** [comment] 2016-10-19 20:49
This is a duplicate of #32728

**Comment by wlan0** [comment] 2016-12-15 19:01
@soumyalj Tested this with rancher/k8s:v1.5.1-rancher1 and verified that these logs are not present anymore.

**Comment by galal-hussein** [comment] 2016-12-16 20:03
Rancher version: master build 
kubernetes version: tested on both rancher/k8s:v1.5.1-rancher1 and rancher/k8s:v1.5.1-rancher1-1
RHEL 7.2 with Docker 1.12.5

Kubelet containers started successfully without showing the mentioned error logs, and kubernetes stack was up and running.

**Closed by galal-hussein** 2016-12-16 20:03 UTC
Labels: area/kubernetes, status/resolved, status/to-test
