### ISSUE TITLE
Cannot start convoy-gluster stack from catalogue on CoreOS host

### ISSUE THREAD

**Issue by sshipway** [rancher/rancher#2836] opened 2015-11-26 22:57 UTC
Rancher 0.47.0, convoy-agent 0.1.0, Docker 1.7.1, CoreOS 766.5.0

A glusterfs stack was successfully started up using the Catalogue.

Using the catalogue, attempted to start a Convoy stack over the top. The storagepool service started, but the main convoy service does not start; the container exits with the error message:
```
26/11/2015 2:50:48 pmWaiting for metadatatime="2015-11-26T01:50:48Z" level=fatal msg="json: cannot unmarshal string into Go value of type []*configs.ThrottleDevice"
```

**Comment by deniseschannon** [comment] 2015-12-01 22:08
I have reproduced this.

Steps to Reproduce:

1. Have Rancher setup with CoreOS host
2. Deploy glusterfs catalog template
3. Deploy convoy-gluster catalog template

Result: Convoy-Gluster-StoragePool launches fine, but convoy-gluster container can never start. 

Logs of stopped convoy-gluster container:

```
Waiting for metadatatime="2015-12-01T21:56:47Z" level=fatal msg="json: cannot unmarshal string into Go value of type []*configs.ThrottleDevice" 
Waiting for metadatatime="2015-12-01T21:57:17Z" level=fatal msg="json: cannot unmarshal string into Go value of type []*configs.ThrottleDevice" 
Waiting for metadatatime="2015-12-01T21:58:52Z" level=fatal msg="json: cannot unmarshal string into Go value of type []*configs.ThrottleDevice" 
Waiting for metadatatime="2015-12-01T21:59:17Z" level=fatal msg="json: cannot unmarshal string into Go value of type []*configs.ThrottleDevice" 
```

Expected Result: Convoy-Gluster service to become active.

**Comment by CBR09** [comment] 2015-12-10 03:28
Same issue with RancherOS.

**Comment by deniseschannon** [comment] 2015-12-10 03:53
@CBR09 What version of Rancher are you using? I've been able to launch convoy-gluster using RancherOS.

**Comment by CBR09** [comment] 2015-12-10 03:57
@deniseschannon My rancher version is v0.47.0, but I got same problem, convoy-gluster can never start.

**Comment by sshipway** [comment] 2015-12-10 08:49
I've updated to the latest Rancher 0.49.1 but we're still getting the problem (CoreOS)

**Comment by CBR09** [comment] 2015-12-10 09:13
Me too, with Rancher 0.49.1, I'm still getting the problem on RancherOS

**Comment by CBR09** [comment] 2015-12-10 10:11
@deniseschannon The problem is still persist no matter what I tried. My environment consist of 3 nodes running RancherOS and Rancher 0.49.1. Convoy_agent is also updated to 0.1.2 ( latest version). Could you point me to right direction in order to launch the service as you mentioned above ? if you need any other infos, please let me know. Many thanks.

**Comment by Negashev** [comment] 2015-12-14 18:31
+1

**Comment by taketnoi** [comment] 2015-12-15 03:25
+1

**Comment by cjellick** [comment] 2015-12-15 13:32
Ping @ibuildthecloud 
This is a problem in our share-mnt utility. Looks like it is all related to this change in the open container spec: https://github.com/opencontainers/runc/commit/c6e406af243fab0c9636539c1cb5f4d60fe0787f
where throttleDevice elements were changed from a single string to lists.

It looks like share-mnt has the latest version, so it seems where ever we are getting the data from (before unmarshall it) is passing the old version.

**Comment by ibuildthecloud** [comment] 2015-12-15 15:38
@cjellick @sshipway All of our storage stuff requires Docker 1.9.1 which means you must be running CoreOS 877.1.0 or newer.

**Comment by cjellick** [comment] 2015-12-15 15:41
Looks like we can close this issue then?

**Comment by ibuildthecloud** [comment] 2015-12-15 15:46
Yes, @sshipway can you please file a new issue if you experience any issues with CoreOS using Docker 1.9.1 or greater.  Thanks.

**Closed by ibuildthecloud** 2015-12-15 15:46 UTC
Labels: area/storage, kind/bug

**Comment by deniseschannon** [comment] 2015-12-15 15:48
@sshipway Please re-open if you have additional issues with CoreOS and convoy-gluster.

@Negashev @CBR09 @taketnoi Can one of you re-open a new issue for RancherOS and convoy-gluster?  Have you made sure to put on the host label required on hosts so that convoy-gluster knows where to deploy? It's one of the configuration options in the convoy-gluster catalog item. 

In each of your use case, please provide Rancher/RancherOS version. An indication of what is failing in convoy-gluster (i.e. which service is not launching in the convoy-gluster stack). Logs of what container is failing.

**Comment by Negashev** [comment] 2015-12-15 19:53
@deniseschannon , yes i set label for host

**Comment by sshipway** [comment] 2015-12-15 22:15
Not working using CoreOS  835.9.0.  This is the latest stable CoreOS but it uses Docker 1.8.3.

With CoreOS 877.1.0BETA (Docker 1.9.1) the convoy-glusterfs containers do start successfully, after a couple of attempts.  However, I am yet to be able to create a volume on them; this may be because the underlying glusterfs is still running on Docker 1.8 hosts?  Will investigate.
