### ISSUE TITLE
Cannot login to rancher

### ISSUE THREAD

**Issue by sowmyav27** [rancher/rancher#35639] opened 2021-11-23 04:18 UTC
**Rancher Server Setup**
- Rancher version: 2.6-head `744f32fe3` commit
- Installation option (Docker install/Helm Chart): Helm
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): RKE1

**Information about the Cluster**
- Kubernetes version: 1.22.3 local RKE1 and 1.22.3 downstream RKE1 EC2 cluster

**Describe the bug**
Cannot login to rancher 

**To Reproduce**

- Deploy a downstream rke1 cluster. 
- Take an etcd snapshot + restore. 
- User is logged out of rancher. 
- User is not able to login.
- Reset password using `kubectl -n cattle-system exec $(kubectl -n cattle-system get pods -l app=rancher | grep '1/1' | head -1 | awk '{ print $1 }') -- reset-password`. And with this new password, user is not able to login.
- Entering username and password (admin user) and hitting login -->>  logs in, makes various requests including getting a list of clusters, that succeeds, then tries to list namespaces for a cluster (which does appear in the cluster list) and gets a 401 and logs out the user

**Note:**
Happened in 2 out of say 6-7 rancher server setups (testing these ^^^ steps)

**Comment by cbron** [comment] 2021-11-23 17:15
Going to talk this one out, this is likely not a bug and just a timing issue with restoring.

**Comment by kinarashah** [comment] 2021-11-23 18:37
Only able to reproduce when one of the downstream clusters is going through a restore or was just restored and isn't active yet successfully. After password is verified, I see a lot of links that fetched correctly as expected but the ones for the restoring downstream cluster get 401 because tokens aren't available. 
Links that failed: 
`k8s/clusters/c-bn8c8/v1/ui.cattle.io.navlinks`: 401 
`k8s/clusters/c-bn8c8/v1/namespaces`: 401 

@sowmyav27 I don't think we need to fix this, since this would be expected behavior if tokens aren't present. We should make sure that logins work post restore. What do you think?

**Comment by sgapanovich** [comment] 2021-11-24 17:42
I tried on Rancher 2.6.2 with a RKE downstream (k8s 1.21)
Tried to restore using all three options multiple times (etcd only, k8s and etcd etc)
Result:
- if i didn’t navigate through the cluster
    - i didn’t even get logged out
    - was able to proceed interacting with a cluster when it got back to Active status
- if i did navigate through the cluster
    - i got logged out at some point BUT WAS ABLE TO LOG IN back with no issues 
    - was able to proceed interacting with a cluster when it got back to Active status
the only two api calls which were coming back with 500 are namespace and navlinks when a cluster was updating but as soon as cluster came up as Active there were no issues noticed

**Comment by snasovich** [comment] 2021-11-29 16:11
@cbron @kinarashah , given the comment above, do we want to investigate it further?

**Comment by kinarashah** [comment] 2021-12-09 00:27
Both @sowmyav27 and I tried reproducing multiple times with kinarashah/rancher:v2.6.3-rc4, unable to reproduce. Moving this to test.

**Comment by sowmyav27** [comment] 2021-12-09 07:03
**On 2.6-head commit id: `77392a65`**

- As an admin deploy 3 nde driver RKE1 clusters - 1 nde all roles and 2 worker nodes
- Take a manual snapshot, restore to the first recurring snapshots.
- The clusters go into updating state, and come back Active. And no issue seen
- Added a standard user as a cluster owner of cluster1
- Login as standard user in incognito window.
- restore to the first recurring snapshot as the standard user. 
- User is logged out. Admin is also logged out.  Cannot login again
- Error in rancher logs:

```
E1209 06:58:48.986930      96 reflector.go:139] pkg/mod/github.com/rancher/client-go@v1.22.3-rancher.1/tools/cache/reflector.go:168: Failed to watch *v3.ClusterAuthToken: failed to list *v3.ClusterAuthToken: Get "https://<>:6443/apis/cluster.cattle.io/v3/clusterauthtokens?resourceVersion=2458": dial tcp <>:6443: connect: connection refused
```

**Comment by cbron** [comment] 2021-12-10 17:05
We are going to do a quick sanity check on 1.21 to ensure this isn't happening, then move to 2.6.4.

**Comment by sowmyav27** [comment] 2021-12-10 20:54
**On 2.6-head commit id: `9295d4f`**

- Cannot reproduce this issue on 1.21.7 downstream cluster

**Comment by snasovich** [comment] 2022-03-01 19:31
@sowmyav27 @slickwarren has this been happening on 1.22 in recent testing?

**Comment by slickwarren** [comment] 2022-03-02 00:13
I have not seen this come up at all for 2.6.4 testing

**Comment by Auston-Ivison-Suse** [comment] 2022-03-09 17:09
**Validation Setup**

- Rancher version: v2.6-head(3df76e4)
- Local cluster k8s version: v1.22.6
- Downstream: RKE1, k8s version: v1.23.4

**Validation Steps**

1. Deploy a downstream rke1 cluster. 
2. Take an etcd snapshot + restore. 
3. Wait for Snapshot process to finish. 

**Results**

This succeeds both in the head listed and 2.6.3. 

I couldn't reproduce the issue, I tried among 9 setups and failed to see it once. 

Moving to done, but will keep my eye on this in the future.

**Closed by Auston-Ivison-Suse** 2022-03-09 17:09 UTC
Labels: kind/bug-qa, [zube]: QA Working, team/area2
