### ISSUE TITLE
vxlan error: expected one CNI driver service, but found: 2

### ISSUE THREAD

**Issue by vainkop** [rancher/rancher#11338] opened 2018-02-07 13:36 UTC
**Rancher versions:**
rancher/server:1.6.14
rancher/agent: 1.2.9

**Infrastructure Stack versions:**
healthcheck:

ipsec: 
vxlan enabled from Catalog -> Rancher Networking plugin using VXLAN overlay.

network-services: 
rancher/metadata:v0.9.5
COMMAND: `start.sh rancher-metadata -reload-interval-limit=1000 -subscribe`

rancher/network-manager:v0.7.19
COMMAND: `plugin-manager --disable-cni-setup --metadata-address 169.254.169.250`

scheduler:
rancher/scheduler:v0.8.3
COMMAND: `scheduler --metadata-address 169.254.169.250`

**Docker version: (`docker version`,`docker info` preferred)** 
1.13.1

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
Ubuntu 16.04.3

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
AWS

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
HA + External RDS

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle

**Steps to Reproduce:**
Installed VXLan from Rancher Catalog with all defaults + debug log enabled

**Results:**
Constantly getting the following errors in network manager logs:
`2/7/2018 4:30:16 PMtime="2018-02-07T13:30:16Z" level=error msg="utils: error: expected one CNI driver service, but found: 2"`

Not sure if VXLan actually working.

**Comment by superseb** [comment] 2018-02-07 13:49
Seems like you are using both ipsec and vxlan in the same environment, this is not the way to use them. Best way to use vxlan, is to create an environment template (http://rancher.com/docs/rancher/latest/en/environments/#adding-environment-templates), in this template you can disable ipsec (enabled by default) and enable vxlan, save the template. Then create a new environment from this template and add your hosts.

Closing as not a bug, let me know if you run into anything.

**Closed by superseb** 2018-02-07 13:49 UTC

**Comment by vainkop** [comment] 2018-02-07 14:21
Problem: not an easy task to remove that VXLan stack now. 

It was saying that some container is already using it & then when I stopped all user stacks, removed it & restarted user stacks then refused to start.

Reenabled VXLan from Catalog, at least the user stacks started...

So how do I properly disable IPSec & switch to VXLan & vise versa? Environment template only? What about running stacks?

**Comment by superseb** [comment] 2018-02-07 16:51
Disabling/switching network drivers is not recommended/supported in an environment. A new environment based on the correct environment template, adding hosts, and re-adding your user stacks should do the trick.
