### ISSUE TITLE
Rancher cannot add labels to nodes in imported local/aliyun/k3s cluster

### ISSUE THREAD

**Issue by 727561126** [rancher/rancher#24123] opened 2019-11-15 09:18 UTC
After adding label to the host, the host page will not flash for a moment. It can be successfully added normally through the command kuberctl.

- Rancher version (v2.3.2):
- Cluster type (Imported):
- Kubernetes version  v1.14.8-aliyun.1:
- Docker version 18.9.2:

**Comment by loganhz** [comment] 2019-12-05 04:16
Root cause is the same with https://github.com/rancher/rancher/issues/23840

**Comment by deniseschannon** [comment] 2019-12-10 20:52
@sangeethah this was already fixed and closed in master with https://github.com/rancher/rancher/pull/24192, so this is backport to 2.3.

**Comment by sowmyav27** [comment] 2019-12-11 00:08
**Verified on 2.3-head - commit id: `0da334b28 `**

**Steps:**

- Import a k3s cluster.
- Go to Nodes page of cluster.
- Edit node --> Add labels.
- Labels get added on the node.
- Edit node again --> Add labels --> Remove the previously added label and add a new one.
- New one gets reflected on the node.

**Closed** 2019-12-11 00:08 UTC
Labels: [zube]: To Test, internal, kind/bug, team/cn
