### ISSUE TITLE
Cloning hosts doesn't work with generic drivers

### ISSUE THREAD

**Issue by janeczku** [rancher/rancher#3042] opened 2015-12-16 15:24 UTC
#### Steps to reproduce
1. Add a new host using Openstack driver:  `Add Host` => `Other` => `Driver`: openstack
2. Select `Clone` from the host’s drop down menu

#### Expected result
Add Host page is shown with `Other` pre-selected and form fields for the generic driver populated with data of the cloned host.

#### Actual result
Add Host page is shown with no driver pre-selected and no fields populated

#### Version info
Rancher	v0.50.0
Cattle	v0.126.0
User Interface	v0.74.0
Rancher Compose	v0.6.2

**Comment by deniseschannon** [comment] 2015-12-16 17:44
Duplicate of https://github.com/rancher/rancher/issues/2226

**Closed by deniseschannon** 2015-12-16 17:44 UTC
