### ISSUE TITLE
The pod memory of kubectl top and cattle-grafana queries is inconsistent.

### ISSUE THREAD

**Issue by LincolnBruce** [rancher/rancher#25977] opened 2020-03-12 08:30 UTC
**What kind of request is this (question/bug/enhancement/feature request):**
k8s/clusters/c-4kdjk/api/v1/namespaces/cattle-prometheus/services/http:access-grafana:80/proxy/d/XSOTSYxiz/pods?orgId=1&var-namespace=web&var-pod=demo-f68d5db87-gdfd2&var-container=All

**Steps to reproduce (least amount of steps as possible):**
kubectl top pod demo -n web

**Result:**
The pod memory of kubectl top and grafana queries is inconsistent.

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI):
rancher/rancher:stable  v2.3.5
- Installation option (single install/HA):
single install

**Cluster information**
- Cluster type Custom；
- Machine type Aliyun and specifications (CPU 4Core/memory 8GB):
- Kubernetes version (use `kubectl version`):
v1.16.3
```
(paste the output here)
```

- Docker version (use `docker version`):
18.09.0
```
(paste the output here)
```
![image](https://user-images.githubusercontent.com/7814560/76502235-a4b1e400-647e-11ea-8717-143b0ed86940.png)
![image](https://user-images.githubusercontent.com/7814560/76502247-aa0f2e80-647e-11ea-8a17-f25d4d112577.png)

**Comment by LincolnBruce** [comment] 2020-03-12 10:23
[Pod memory used]
**Cattle-Grafana-WRONG**: /k8s/clusters/clusters/c-4kdjk/api/v1/namespaces/cattle-prometheus/services/http:access-grafana:80/proxy/d/XSOTSYxiz/pods?orgId=1&var-namespace=web&var-pod=demo-f68d5db87-gdfd2&var-container=All
**RESTFUL API**: /k8s/clusters/c-4kdjk/api/v1/namespaces/cattle-prometheus/services/http:access-grafana:80/proxy/api/datasources/proxy/1/api/v1/query_range?query=sum by(container_name) (container_memory_working_set_bytes{namespace="web",container_name!="",container_name=~".*",container_name!="POD",pod_name="demo-f68d5db87-gdfd2"})&start=1584008175&end=1584008475&step=15

Cattle-Grafana-RIGHT
**RESTFUL API**: /k8s/clusters/c-4kdjk/api/v1/namespaces/cattle-prometheus/services/http:access-grafana:80/proxy/api/datasources/proxy/1/api/v1/query_range?query=sum by(container_name) (container_memory_working_set_bytes{namespace="web",container="demo",id="",pod_name="demo-f68d5db87-gdfd2"})&start=1584008175&end=1584008475&step=15

**Comment by pangliang** [comment] 2020-03-13 05:35
same to me. 

Portainer:
![image](https://user-images.githubusercontent.com/3114995/76592549-acc95c80-652e-11ea-9fd9-ead2ec7b4338.png)

Rancher:
![image](https://user-images.githubusercontent.com/3114995/76592591-c8ccfe00-652e-11ea-9c8f-e31185b252a5.png)

rancher version: 2.3.5
k8s: v1.17.2
docker: v19.3.5
![image](https://user-images.githubusercontent.com/3114995/76592724-3ed16500-652f-11ea-838e-b1e8cbb301d5.png)

This problem also exists in older versions, such as: v2.2 v2.1

**Comment by loganhz** [comment] 2020-03-13 06:37
For the double usage issue,  it's a bug in monitoring 0.0.6 and 0.0.7 when you are using k8s 1.16+. It's fixed in https://github.com/rancher/rancher/issues/25539. It will be fixed in monitoring 0.0.8 chart. https://github.com/rancher/system-charts/commit/d8cffef0ae7e6a420f9909047738a45e5b5b9ffc

For the original issue, the Rancher's expression of memory usage is different from metrics server's expression.  https://github.com/rancher/rancher/blob/master/pkg/controllers/user/monitoring/metricExpression.go#L4169

**Comment by pangliang** [comment] 2020-03-14 13:31
Upgrade Rancher to version 2.4.0-rc3, the problem is fixed

**Comment by maggieliu** [comment] 2020-09-15 22:17
This is fixed in monitoring 0.0.8, which was renamed to 0.1.0 when 2.4 was released and is available in 2.3.7. For 2.3.8+, monitoring chart 0.1.1 is available.

**Closed** 2020-10-14 22:33 UTC
Labels: [zube]: To Test, area/monitoring, internal, kind/bug
