### ISSUE TITLE
Sometimes load-balancer takes to much time to resolv request's

### ISSUE THREAD

**Issue by fernandoneto** [rancher/rancher#2963] opened 2015-12-09 12:09 UTC
im using rancher v0.46.0 and most of the times i try to acess something running in rancher-cluster im facing a  long time to get the response ( between 10000/25000ms  ), other times the same request has a short response time ( between 800/1500ms ).

![captura de ecra de 2015-12-09 11 53 12](https://cloud.githubusercontent.com/assets/6515784/11684929/12e64f2e-9e6d-11e5-8f0e-9d6a9c0dd8f6.png)
![captura de ecra de 2015-12-09 11 52 01](https://cloud.githubusercontent.com/assets/6515784/11684928/12e64baa-9e6d-11e5-9e8b-5da14b361be4.png)
![captura de ecra de 2015-12-09 11 50 45](https://cloud.githubusercontent.com/assets/6515784/11684930/12e7621a-9e6d-11e5-932d-d20930cc4c64.png)

In rancher v0.47.0 im facing the same problem.

**Comment by fernandoneto** [comment] 2015-12-09 17:20
i make this script to test connection between loadbalancer's and container's and test if there's a problem with network

```bash
IP=(container's ip's)
PORT=8080

for x in "${IP[@]}"; do netcat -v -z -w 1 -n $x $PORT; done
```
and this is the output 

```bash 
Connection to  container ip 8080 port [tcp/*] succeeded!                         
Connection to  container ip 8080 port [tcp/*] succeeded!                         
Connection to  container ip 8080 port [tcp/*] succeeded!                        
Connection to  container ip 8080 port [tcp/*] succeeded!                        
Connection to  container ip 8080 port [tcp/*] succeeded!                         
Connection to  container ip 8080 port [tcp/*] succeeded!                        
Connection to  container ip 8080 port [tcp/*] succeeded!                         
Connection to container ip 8080 port [tcp/*] succeeded!                          
Connection to  container ip 8080 port [tcp/*] succeeded!                        
Connection to  container ip 8080 port [tcp/*] succeeded!                         
Connection to container ip 8080 port [tcp/*] succeeded!                          
Connection to  container ip 8080 port [tcp/*] succeeded! 
```

**Comment by cusspvz** [comment] 2015-12-09 18:16
Not sure of who is in charge of Load-Balancers...
ping @ibuildthecloud @deniseschannon @cloudnautique 

I'm gonna follow up this issue since is high priority for us.

## Facts
By default *HAProxy* is set with a connect timeout of **5 seconds** for each backend server, which is a great configuration in case of one of them isn't responding. Unfortunately thats not the scenario, inspite of all our container services are healthy seems that `haproxy` can't connect them somehow and hops between backend entries, giving a huge delay on our requests.

## Possible causes
I've seen four possible causes on this, it could possibly be:
* a rancher network issue;
* a rancher health check issue, in cause some of our services were really down;
* an issue on configuration generation;
* an HAProxy issue;

## What's most probable?
I told @fernandoneto to test if **all** LB containers can reach all available servers, he used `netcat` as a PoC and also checked if their configurations matched against our available services.

With that info leads me to be probably an *HAProxy* issue.

## Reproducing

One of the ways for reproducing this is to configure a LB with some *nginx hello-world* containers and execute an `ab` without `keep-alive` opt. Didn't test that out but I suppose it does the job. (Told @fernandoneto personally to test that out)

## Briefing

Is that a known issue or does any of you has seen/experienced this?
If so, any clue on what could be causing it?

I'm available for discussing, help fixing and testing it out.

**Comment by alena1108** [comment] 2015-12-09 18:38
@cusspvz  thank you for running the tests and the detailed description for the problem.

>I've seen four possible causes on this, it could possibly be: 
a rancher network issue;

You can test it by setting up some proxy server (not haproxy)  in front of web service (nginx hello-world). Check if you hit the same timeout issue

> a rancher health check issue, in case some of our services were really down;

Have you configured a health check for the web service? If not, no health check would be set on the load balancer, and that would explain the hopping in case of unreachable service. When health check is configured, unhealthy container would get ignored by haproxy, and would never be chosen for sending the request - you shouldn't see hopping as only healthy containers are picked. 

> an issue on configuration generation;

you can find Rancher default haproxy config here:

https://github.com/rancher/cattle/blob/c7feeac86a773aaf7eb53fede987bca9eb1b6463/resources/content/config-content/haproxy/content/etc/haproxy/haproxy.cfg.ftl

connect timeout is set to default - 5 secs
http mode is "http-server-close"

> an HAProxy issue or outdated version;

> I told @fernandoneto to test if all LB containers can reach all available servers, he used netcat to create a PoC and also checked if their haproxy configurations matched against our available services.
With that info leads me to be probably an HAProxy issue.

have you run this test against the latest haproxy version (1.6.2)? If not, is it possible to repeat this test again, against the latest? Rancher runs haproxy 1.5.4, so it the issue doesn't exist on 1.6.2, then the fix would be to upgrade Rancher haproxy to the latest.

**Comment by cusspvz** [comment] 2015-12-10 00:12
I've entered on one of the LB and did:
```bash
apt-get update
apt-get install software-properties-common
add-apt-repository ppa:vbernat/haproxy-1.6
apt-get update
apt-get install haproxy
```

But after a container restart I got:
```
10/12/2015 00:05:26Reading package lists...
10/12/2015 00:05:26[apply.sh:14] apt-get install -y haproxy -t trusty-backports
10/12/2015 00:05:27Reading package lists...
10/12/2015 00:05:27Building dependency tree...
10/12/2015 00:05:27Reading state information...
10/12/2015 00:05:27haproxy is already the newest version.
10/12/2015 00:05:270 upgraded, 0 newly installed, 0 to remove and 85 not upgraded.
10/12/2015 00:05:27[apply.sh:17] reload_haproxy /etc/haproxy/haproxy.cfg
10/12/2015 00:05:27[scripts.sh:169] CONFIG=/etc/haproxy/haproxy.cfg
10/12/2015 00:05:27[scripts.sh:171] '[' '!' -f /var/run/haproxy.pid ']'
10/12/2015 00:05:27[[scripts.sh:176] cat /var/run/haproxy.pid
10/12/2015 00:05:27[scripts.sh:176] haproxy -p /var/run/haproxy.pid -f /etc/haproxy/haproxy.cfg -sf 451
10/12/2015 00:05:27[ALERT] 343/000527 (652) : parsing [/etc/haproxy/haproxy.cfg:106] : 'listen' cannot handle unexpected argument '0.0.0.0:42'.
10/12/2015 00:05:27[ALERT] 343/000527 (652) : parsing [/etc/haproxy/haproxy.cfg:106] : please use the 'bind' keyword for listening addresses.
10/12/2015 00:05:27[ALERT] 343/000527 (652) : Error(s) found in configuration file : /etc/haproxy/haproxy.cfg
10/12/2015 00:05:27[WARNING] 343/000527 (652) : config : proxy 'default' has no 'bind' directive. Please declare it as a backend if this was intended.
10/12/2015 00:05:27[WARNING] 343/000527 (652) : config : missing timeouts for proxy 'default'.
10/12/2015 00:05:27   | While not properly invalid, you will certainly encounter various problems
10/12/2015 00:05:27   | with such a configuration. To fix this, please ensure that all following
10/12/2015 00:05:27   | timeouts are set to a non-zero value: 'client', 'connect', 'server'.
10/12/2015 00:05:27[ALERT] 343/000527 (652) : Fatal errors found in configuration.
10/12/2015 00:05:27[scripts.sh:179] return 1
10/12/2015 00:05:27[config.sh:1] cleanup
10/12/2015 00:05:27[config.sh:9] EXIT=1
10/12/2015 00:05:27[config.sh:11] '[' -e /var/lib/cattle/download.FYfiF7V ']'
10/12/2015 00:05:27[config.sh:12] rm -rf /var/lib/cattle/download.FYfiF7V
10/12/2015 00:05:27[config.sh:15] return 1
```

Could you please tell me what's the better approach for testing on an `agent-instance` image without having rancher to run the `apt-get install -y haproxy -t trusty-backports` command?

**Comment by cusspvz** [comment] 2015-12-10 00:18
> Have you configured a health check for the web service?

Yes we did, it is HTTP based.

**Comment by alena1108** [comment] 2015-12-10 01:05
> But after a container restart I got:

Looks like haproxy 1.6 no longer supports "listen ipAddress:port" directive (the error message "please use the 'bind' keyword for listening addresses." says it). So this is no longer valid:

``` 
listen default 0.0.0.0:42
```

It should be written in a following way:

```
listen default
        bind 0.0.0.0:80
```

In order for 1.6 to work with Rancher generated haproxy config, this line should be fixed on cattle side:

https://github.com/rancher/cattle/blob/c7feeac86a773aaf7eb53fede987bca9eb1b6463/resources/content/config-content/haproxy/content/etc/haproxy/haproxy.cfg.ftl#L88

You could either fix this line and run Cattle using your custom branch, or test it independently of rancher agent-instance by following these steps:

1) Create any ubuntu service; install haproxy 1.6 on it.
2) You can either copy haproxy config from any lb instance to your ubuntu instance (make sure to apply the fix to the line that causes problems on haproxy 1.6 https://github.com/rancher/cattle/blob/c7feeac86a773aaf7eb53fede987bca9eb1b6463/resources/content/config-content/haproxy/content/etc/haproxy/haproxy.cfg.ftl#L88);  or generate your own config.
3) Run the test and see if the connections get flaky. If you are accessing your haproxy endpoints from outside of rancher managed network, you'll have to open public port on your service.

This way you can play with different haproxy options (connection timeout, etc) to see if modifying them could fix the issue. If you use rancher agent-instance, all your custom modifications will get overridden by the next haproxy config reload.

**Comment by cusspvz** [comment] 2015-12-10 12:58
@alena1108 Thanks for your tips!

I've already reproduced this issue with a freshly ubuntu container with haproxy 1.5.4 but the fact it is intermittent is taking me more time than I've expected to isolate it.

Here's what I did come up until now:
* Reproduced with exactly the same configuration (just had to change frontend binded ip address)
* Since the delays have a pattern (the delay window seems to be *connect timeout* x *service delay), I've changed *connect timeout* from **5s** to **2s**, but haven't experienced any delay yet.

@fernandoneto also created a container based on haproxy 1.6.2 with the same configurations, inspite I haven't tested it yet.

We will keep you posted until we isolate this issue's cause.

**Comment by cusspvz** [comment] 2015-12-10 13:17
reproducible as well on haproxy 1.6.2

**Comment by cusspvz** [comment] 2015-12-10 16:20
Me and @fernandoneto hardly to figure this out. We've exposed a service directly on host (over rancher UI) and we did a code snippet to inspect for delays, after a while we experienced the same issue on the exposed service. That means that probably isn't related with haproxy but with the network somehow.

We've also noticed that the port hasn't been exposed on native docker, seems that the rancher agent acts as a network layer and handles port mapping, unfortunately I wasn't aware of that.

We are currently debugging and trying to isolate the cause of this (supposing between: Our service, Rancher network or Azure network) by launching and exposing:
* an **hello world** based on nginx over Rancher Network
* one of our API services over Rancher Network
* an **hello world** based on nginx over Docker native
* one of our API services over Docker native

Inspite our services are being part of the current tests, we really don't think this issue resides on them (our logs shown us the expected latencies on our last test, since they don't differ on delayed requests).

**Comment by alena1108** [comment] 2015-12-10 19:41
> We've also noticed that the port hasn't been exposed on native docker, seems that the rancher agent acts as a network layer and handles port mapping, unfortunately I wasn't aware of that.

Your assumption is correct. You can see all the port mappings in CATTLE_PREROUTING iptables chain.

Thank you for the updates, please keep us posted.

**Comment by cusspvz** [comment] 2015-12-11 00:09
@alena1108 we can now confirm the delay is coming from the LB.

Since this is intermittent and very hard to reproduce, me and @fernandoneto spent the whole day trying to reduce possible culprits for this. Since my last comment, the only flaw we got on directly exposed services, that lead us to think it wasn't haproxy, was actually our fault. We were constantly editing our laptops's `/etc/hosts` for selecting right hosts that we ended up hitting the LB instead of an exposed service. :disappointed: 

After the dinner, I've tried to bootstrap a new environment, very similar to the one we prepared for @ibuildthecloud to test the Reconnecting issue (won't link issues to avoid confusion).

I'm gonna provide all info you need above to reproduce and figure out whats happening, I cannot say if this configuration causes intermittence or not because I didn't experienced non-delayed requests yet.

I honestly hope you can reproduce it! :crossed_fingers:

--

Here's the connection flow schema:
[Host] -> [LB Agent] -> [nginx redirect container]

### PoC

Commands from within the LB: (notice the 5s delay)
```
root@44db16314820:/# echo "10.42.83.56 example.domain" >> /etc/hosts      
root@44db16314820:/# date; curl http://example.domain/auth; date              
Thu Dec 10 23:42:20 UTC 2015                                                    
<html>                                                                          
<head><title>301 Moved Permanently</title></head>                               
<body bgcolor="white">                                                          
<center><h1>301 Moved Permanently</h1></center>                                 
<hr><center>nginx/1.8.0</center>                                                
</body>                                                                         
</html>                                                                         
Thu Dec 10 23:42:25 UTC 2015                                                    
root@44db16314820:/#   
```

Commands from within the redirect service: (notice that there wasn't a 5s delay)
```
bash-4.3# date; curl http://localhost:80/anything; date                         
Thu Dec 10 23:52:13 UTC 2015                                                    
<html>                                                                          
<head><title>301 Moved Permanently</title></head>                               
<body bgcolor="white">                                                          
<center><h1>301 Moved Permanently</h1></center>                                 
<hr><center>nginx/1.8.0</center>                                                
</body>                                                                         
</html>                                                                         
Thu Dec 10 23:52:13 UTC 2015                                                    
bash-4.3# 
```

### Compose files

`docker-compose.yml`
```yaml
https-redirect:
  environment:
    REDIRECT: https://example.domain
  tty: true
  image: cusspvz/redirect:0.0.1
  stdin_open: true

http-lb:
  ports:
  - '80'
  links:
  - https-redirect:https-redirect
  labels:
    io.rancher.scheduler.global: 'true'
    io.rancher.loadbalancer.target.https-redirect: example.domain=80
  tty: true
  image: rancher/load-balancer-service
  stdin_open: true
```

`rancher-compose.yml`
```yaml
https-redirect:
  scale: 4

http-lb:
  load_balancer_config: {}
  health_check:
    port: 42
    interval: 2000
    unhealthy_threshold: 3
    healthy_threshold: 2
    response_timeout: 2000
```

**Comment by beenokle** [comment] 2015-12-13 16:26
Got the same delays on 0.49.1

**Comment by beenokle** [comment] 2015-12-14 07:15
We removed all LBs and exposed container's ports - and we are still experiencing slow responses.
So, I think, the problem is not with HAProxy - the problem is with Rancher network.

When LB were in stack - delay was +10 sec
Without LB - delay is equal to nginx's `proxy_connect_timeout`

In our case about 1,18% of requests delayed

**Comment by petyunchik** [comment] 2015-12-14 09:36
Confirming the issue. It's the problem with HTTP settings only, if you use the same LB configuration with SSL enabled - the problem will be resolved.

**Comment by petyunchik** [comment] 2015-12-14 09:45
And yup, i'm also using nginx after the LB. Direct services (without nginx proxy) works fine, it seems.

**Comment by beenokle** [comment] 2015-12-14 11:59
I still believe problem is not with HAProxy, but with rancher network.
I removed LB between nginx and containers - problem still existed.
Now I changed network to "Host" instead of "Managed' - seems like problem is gone

**Comment by fernandoneto** [comment] 2015-12-16 11:27
@beenokle did you solve the problem?

**Comment by cusspvz** [comment] 2015-12-16 15:37
> Confirming the issue. It's the problem with HTTP settings only, if you use the same LB configuration with SSL enabled - the problem will be resolved.

@petyunchik I'm a little bit confused, correct me if I'm wrong. You're saying that you aren't experiencing this issue with load balancers configured on *TCP* mode instead?

**Comment by beenokle** [comment] 2015-12-17 10:54
Hi Guys, do you have any updates?
Just checked logs of etcd containers, nodes are running in managed network mode (sure without any load balancers, just linked with each other, but on separate host machines, so rancher builds tunnels to each container, am i right?)
Sometimes they lose connection, there are such messages in logs
```
12/17/2015 11:30:18 ... | rafthttp: the connection to peer 1e58be60582c7259 is unhealthy
12/17/2015 11:30:23 ... I rafthttp: the connection with 1e58be60582c7259 became active
```
Problems with IPsec?

**Comment by cusspvz** [comment] 2015-12-17 11:15
@beenokle I've experienced this with containers on the same host as well, so I'm not so sure of that. Unless this issue has more than one cause.

**Comment by will-chan** [comment] 2015-12-29 00:51
We are updating our ipsec package soon so hopefully, it might be able to resolve our managed network issues.

**Comment by will-chan** [comment] 2016-01-06 19:15
#2944

**Comment by sangeethah** [comment] 2016-01-25 22:08
With rancher-server version - v0.56.0 , we updating ipsec to use charon instead of racoon.
If you still see issues with this version, please log a new issue to track it.

**Closed by sangeethah** 2016-01-25 22:08 UTC
Labels: kind/bug, release/v1.0.0

**Comment by fernandoneto** [comment] 2016-02-19 18:29
@sangeethah in version 0.59.0 the problem persist. 
i have an environment with only 1 server and 4 services. Sometimes everything works perfect and other's take to much time to response. 
When this problem occurs i execute a shell in lb container and ping the service container without problem. using curl works perfect to.
So im trying to see the haproxy logs to see if my request is reaching the destiny, but i can found the logs for haproxy. 
looking in issues section found [this](https://github.com/rancher/rancher/issues/2268) where @alena1108  explains why there's no logs. 
Trying to start rsyslog service fails, so I'm out of ideas how to get logs to solve this problem.

**Comment by fernandoneto** [comment] 2016-02-22 23:00
cc @cusspvz

**Comment by alena1108** [comment] 2016-02-22 23:20
@fernandoneto  when this problem occurs, could you try to test connection from client container to Lb service? to make sure that the problem is not on the client's end

Also you can test it independently of rancher LB by starting up haproxy as a regular service and manually configuring haproxy. To eliminate possibility that lb config reload performed by rancher, is causing the problem. You can do something like:

* have service A (client), B (haproxy), C (web service)
* register service C in B and setup client A to run continuous requests against B. Watch if it ever times out
* have A, B, C running on separate hosts.

As the last resort, try to configure health checks for lb targets with the minimal unhealthy threshold + interval. We use the same haproxy software for performing healthchecks (gets configured on the network agent side). If the problem is with haproxy, the problem should reveal itself via failed health checks. 

Several questions: How often does the problem occurs? Are your LB/target containers exist on separate hosts? Before the problem happens, is there any activity on the LB service that precedes that (like target being updated), or the system is idle?

**Comment by adammwood** [comment] 2016-10-31 12:37
We're also experiencing similar issues to this using Rancher's LB. We have three hosts for an application, which if we load balance with an ELB doesn't have any issues, however if we switch to Rancher's LB we get consistent slow requests every 5-10 seconds.

To help confirm/diagnose this, we ran a light load test for a few minutes in JMeter, and it clearly shows groups of slow requests in regular intervals. All of the slow requests are within a few ms of each other taking around 3 seconds.

Here is an example of one of these groups of slow requests, and I've linked a spreadsheet of the full run of ~3k samples below in case it's of interest.

<img width="1013" alt="rancher-lb-test-jmeter" src="https://cloud.githubusercontent.com/assets/17033142/19854191/9af53ba6-9f65-11e6-86a9-f90040538d56.png">

[rancher-lb-jmeter-results.xlsx](https://github.com/rancher/rancher/files/561703/rancher-lb-jmeter-results.xlsx)

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v1.2.0-pre4-rc4` Cattle: `v0.170.3` UI: `v1.2.17` |
|Access|`localauth` `admin`|
|Orchestration|`Cattle`|
|Route|`hosts.index`|

**Hosts**

3x EC2 c4.large - same region/VPC over 3 availability zones

**Load Balancer Config**

`docker-compose.yml`

```yaml
version: '2'
services:
  load-balancer:
    ports:
    - 443:443
    - 80:80
    external_links:
    - foo/nginx:nginx
    labels:
      io.rancher.scheduler.global: 'true'
      io.rancher.loadbalancer.ssl.ports: '443'
      io.rancher.loadbalancer.target.foo/nginx: foo.com:80=80,foo.com:443=80
    tty: true
    image: rancher/load-balancer-service
    stdin_open: true
```

`rancher-compose.yml`

```yaml
version: '2'
services:
  load-balancer:
    load_balancer_config:
      haproxy_config: {}
    default_cert: foo
    health_check:
      port: 42
      interval: 2000
      unhealthy_threshold: 3
      healthy_threshold: 2
      response_timeout: 2000
```
