### ISSUE TITLE
sidekicks that share a network with a primary cannot have helthchecks

### ISSUE THREAD

**Issue by cjellick** [rancher/rancher#4688] opened 2016-05-04 23:10 UTC
This is because the sidekick doesn't have an IP address in the rancher db, so the healthcheck doesnt get configured on the host.

Steps to reproduce:
1. Create a service with two containers: one primary and one as a sidekick. Make the sidekick use the primary's network. Should be able to just use an nginx container for primary and ubuntu for secondary
2. Set a healthcheck on port 80 for both containers

expected
both healthchecks pass

actual
primary healthcheck passes but the sidekick fails and the container keeps getting recreated

**Comment by alena1108** [comment] 2016-11-29 23:42
resolving as a duplicate of https://github.com/rancher/rancher/issues/6305 feature

**Closed by alena1108** 2016-11-29 23:42 UTC
Labels: kind/bug
