### ISSUE TITLE
Disk Sync Duration graph set to milliseconds (not the expected seconds) in the y-axis

### ISSUE THREAD

**Issue by gaktive** [rancher/rancher#40602] opened 2023-01-06 22:57 UTC
Internal reference: SURE-5755
Reported in 2.6.8 & 2.6.9

Issue description:
The General/Rancher/**** graphs shown in Grafana, which correspond with the charts shown directly in the Rancher UI, are created by Rancher Engineers, versus the General/etcd graphs, which is the vanilla dashboard.

After checking the different behaviours between both graphs, we came to the conclusion that the charts created from our side present a bug where the y-axis unit for the disk sync duration is mistakingly set to milliseconds, where the unit of the metrics series is actually in seconds, as shown in the General/etcd dashboard. Thus, the graphs show the same data but with a factor of 1000 difference.

Repro steps:

- Install Monitoring (v2) on a Rancher cluster.
- Check the Disk Sync Duration graph on:
 - Rancher UI and Grafana/Rancher/etcd (Nodes) - They both show the same info.
 - Grafana/etcd
- While, the Grafana/etcd shows the proper information (y-axis in seconds), the other two present the y-axis in milliseconds.

Compare:

![grafana-general-etcd.png](https://zube.io/files/rancher/526a2b1440c6ed3392569990dba3203b-grafana-general-etcd.png)

with:

![grafana-rancher-etcd.png](https://zube.io/files/rancher/3d4bfb9ab056a33b4979af8413d063fe-grafana-rancher-etcd.png)

![grafana-rancher-etcd-nodes.png](https://zube.io/files/rancher/95710ecabeebef2c9d4e225fbfbec4bc-grafana-rancher-etcd-nodes.png)

Workaround:
Check the proper graph in Grafana/etcd.

Actual behavior:
y-axis unit for the disk sync duration is mistakingly set to milliseconds.

Expected behavior:
The unit of the metrics series is actually in seconds.

Additional notes:
May be worth it to check if any other dashboard suffers from the same discrepancy

**Comment by stormqueen1990** [comment] 2023-02-23 23:07
### Investigation outcome

#### Verified versions:
* **Rancher v2.6.10**:
    * **Monitoring version**: 100.1.3+up19.0.3
    * **Kubernetes version**: v1.24.9
* **Rancher v2.7-head**:
    * **Monitoring version**: 102.0.0+up40.1.2
    * **Kubernetes version**: v1.25.6

The behaviour is reproducible in both versions of Monitoring. It is not related to the version of Rancher or to the version of Monitoring, but rather to our definition of the dashboard in [`rancher-etcd.json`](https://github.com/rancher/charts/blob/7772201f6abd266d99a0d00c95dd584e26d63757/packages/rancher-monitoring/rancher-monitoring/generated-changes/overlay/files/rancher/k8s/rancher-etcd.json). In the Disk Sync Duration panel, the configuration for the `yaxes` is setting the format to `ms`, thus creating the discrepancy between the General/Nodes dashboard and the Rancher/Nodes dashboard.

I was able to [validate that changing the format to `s` solves the issue](https://github.com/stormqueen1990/rancher-charts/commit/533bc69805eb11b2cb82326ad09b1bdae0d92243), although the Rancher/Nodes dashboard shows values slightly lower than the General/Nodes dashboard, probably because of our interval of aggregation.

**Comment by vivek-shilimkar** [comment] 2023-08-30 11:04
Tested the issue on rancher v2.8-head and k8s cluster v1.26.7-rancher1-1.

Installed a Monitoring chart v103.0.0+up40.1.2
Checked a Disk Sync Duration graph on Grafana.
- `General/etcd` and `General/Rancher/etcd` shows the Y axis in "s" format. 
- However, `General/Rancher/etcd (nodes)` still has a "ms" format.

To fix this issue, the `yaxes` format in `rancher-etcd-nodes.json` needs to be updated to "s".

Hence, reopening the issue.

**Comment by vivek-shilimkar** [comment] 2023-08-30 11:19
Tested the issue on rancher v2.8-head and k8s cluster v1.26.7-rancher1-1.

Installed a Monitoring chart v103.0.0+up40.1.2
Checked a Disk Sync Duration graph on Grafana.
- `General/etcd` and `General/Rancher/etcd` shows the Y axis in "s" format. 
- However, `General/Rancher/etcd (nodes)` still has a "ms" format.

To fix this issue, the `yaxes` format in `rancher-etcd-nodes.json` needs to be updated to "s".

Hence, reopening the issue.

**Comment by vivek-shilimkar** [comment] 2023-09-01 06:39
Monitoring chart installation/upgrade is failing with following error.

`Error: UPGRADE FAILED: YAML parse error on rancher-monitoring/templates/rancher-monitoring/clusterrole.yaml: error converting YAML to JSON: yaml: line 40: did not find expected alphabetic or numeric character`

Hence, reopening the issue.

**Comment by vivek-shilimkar** [comment] 2023-09-06 06:42
Tested the issue on rancher v2.8-head and k8s cluster v1.26.7-rancher1-1.

Installed a Monitoring chart v103.0.0+up40.1.2
Checked a Disk Sync Duration graph on Grafana.
- `General/etcd`, `General/Rancher/etcd`, and `General/Rancher/etcd (nodes)` shows the Y axis in correct format. 

Hence closing the issue.

**Closed by vivek-shilimkar** 2023-09-06 06:42 UTC
Labels: kind/bug, internal, area/monitoring, [zube]: QA Working, team/area3, team/infracloud, JIRA
