### ISSUE TITLE
RKE2 Provisioning: Cluster Options - Default Cluster Role for Project Members

### ISSUE THREAD

**Issue by deniseschannon** [rancher/rancher#32384] opened 2021-04-27 05:11 UTC
Pick the default role for project members

```
apiVersion: provisioning.cattle.io/v1
kind: Cluster
metadata:
  name: #string
  annotations:
    {}
#    key: string
  labels:
    {}
#    key: string
  namespace: fleet-default
spec:
  cloudCredentialSecretName: do
  kubernetesVersion: v1.20.5+rke2r1
  rkeConfig:

#  defaultClusterRoleForProjectMembers: string
```

**Comment by snasovich** [comment] 2021-12-23 18:14
@deniseschannon , could you please clarify what `defaultClusterRoleForProjectMembers` should do? At this time it doesn't look like backend is using this field at all and there doesn't seem to be a field for this on the UI.

**Comment by snasovich** [comment] 2022-01-12 22:21
This field exists on `appliedSpec` on RKE1 clusters. Need to look into what functionality it delivers and have the equivalent available in RKE2 provisioning (if applicable). Moving back to triage in Team 2.

**Comment by jiaqiluo** [comment] 2022-01-18 18:48
the field `defaultClusterRoleForProjectMembers` is already in the provisioning obj for RKE2 but is not used right now. 
The fix will be taking use of this field for RKE2 provisioning.

**Comment by jiaqiluo** [comment] 2022-04-07 22:56
In rancher:v2.6-head 0ad0def54, 
- if we set the value `defaultClusterRoleForProjectMembers` in the `cluster.provisioning.cattle.io/v1` object, the value will be synced to the corresponding  `cluster.management.cattle.io/v3` object, but not the other direction. 
- Although the value is set, it does not take any effect. There is no specific logic in the backend to use this value, even in the logic for v3 clusters. 

Based on the above observation, first, I think we need to confirm the expected behavior for this value even though the field name is descriptive and self-explained. Then, once we better understand the usage case, we can determine how we want to implement it and which team to implement it: team2 or team1, or both.

**Comment by Oats87** [comment] 2022-04-11 17:56
@jiaqiluo isn't our goal here to just mimic the behavior of what RKE1 provisioned clusters do?

If that is the case, then I would expect that if a user sets the `defaultClusterRoleForProjectMembers` field on the `v1` object, that gets trickled down to the v3 object, and subsequent project members on the cluster get the default cluster role.

**Comment by jiaqiluo** [comment] 2022-04-11 18:19
@Oats87  Yep that is what we want to do. The problem is that Rancher and RKE1 do nothing when the field is set. The field is simply ignored, as far as I can tell.

**Comment by jiaqiluo** [comment] 2022-04-14 16:26
I can confirm that this field is not used in either the backend or the frontend.

**Comment by snasovich** [comment] 2022-05-26 02:51
Closing it as "not needed" based on the comments above.

**Closed** 2022-05-26 02:51 UTC
Labels: [zube]: Done, [zube]: Need Info, area/provisioning-rke2, feature/provisioned-rke2-k3s, team/area2
