### ISSUE TITLE
rancher/agent on CoreOS Failed to get system UUID which causes stats to not work

### ISSUE THREAD

**Issue by jmatsushita** [rancher/rancher#2205] opened 2015-10-01 14:30 UTC
An agent started on CoreOS 766.4.0 seems to work and shows up as active in the Rancher UI but outputs the following errors:

```
I1001 14:27:10.292013 15236 storagedriver.go:100] No backend storage selected
I1001 14:27:10.292040 15236 storagedriver.go:102] Caching stats in memory for 2m0s
I1001 14:27:10.292068 15236 manager.go:127] cAdvisor running in container: "/system.slice/docker-5f418ceb8b8f7f953bc3015f53a54bb6201bbba39bb5f83693900daaea213ecf.scope"
I1001 14:27:10.292397 15236 fs.go:93] Filesystem partitions: map[/dev/sda3:{mountpoint:/usr major:8 minor:3} /dev/sda6:{mountpoint:/usr/share/oem major:8 minor:6} /dev/sda9:{mountpoint:/ major:0 minor:31}]
E1001 14:27:10.294179 15236 machine.go:274] Failed to get system UUID: open /proc/device-tree/vm,uuid: no such file or directory
fatal error: unexpected signal during runtime execution
[signal 0xb code=0x1 addr=0x0 pc=0x0]

runtime stack:
runtime.gothrow(0xb9f4d0, 0x2a)
	/usr/src/go/src/runtime/panic.go:503 +0x8e
runtime.sigpanic()
	/usr/src/go/src/runtime/sigpanic_unix.go:14 +0x5e

goroutine 18 [syscall, locked to thread]:
runtime.cgocall_errno(0x401930, 0xc208019cd0, 0x0)
	/usr/src/go/src/runtime/cgocall.go:130 +0xf5 fp=0xc208019c90 sp=0xc208019c68
net._C2func_getaddrinfo(0x7f1d080008c0, 0x0, 0xc208019dc8, 0xc208019d18, 0xc200000000, 0x0, 0x0)
	/usr/src/go/src/net/:26 +0x55 fp=0xc208019cd0 sp=0xc208019c90
net.cgoLookupIPCNAME(0xc20801ea00, 0x18, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/src/go/src/net/cgo_unix.go:96 +0x1c5 fp=0xc208019e00 sp=0xc208019cd0
net.cgoLookupIP(0xc20801ea00, 0x18, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/src/go/src/net/cgo_unix.go:148 +0x65 fp=0xc208019e58 sp=0xc208019e00
net.lookupIP(0xc20801ea00, 0x18, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/src/go/src/net/lookup_unix.go:64 +0x5f fp=0xc208019ea0 sp=0xc208019e58
net.func·026(0x0, 0x0, 0x0, 0x0)
	/usr/src/go/src/net/lookup.go:79 +0x55 fp=0xc208019f08 sp=0xc208019ea0
net.(*singleflight).doCall(0x1112970, 0xc208132240, 0xc20801ea00, 0x18, 0xc2080d4140)
	/usr/src/go/src/net/singleflight.go:91 +0x2f fp=0xc208019fb8 sp=0xc208019f08
runtime.goexit()
	/usr/src/go/src/runtime/asm_amd64.s:2232 +0x1 fp=0xc208019fc0 sp=0xc208019fb8
created by net.(*singleflight).DoChan
	/usr/src/go/src/net/singleflight.go:84 +0x42b

goroutine 1 [select]:
net/http.(*Transport).getConn(0xc2080641b0, 0xc2080352b0, 0x0, 0xb60550, 0x4, 0xc20801ea00, 0x1b, 0x0, 0x0, 0x0)
	/usr/src/go/src/net/http/transport.go:525 +0x608
net/http.(*Transport).RoundTrip(0xc2080641b0, 0xc2080352b0, 0xa, 0x0, 0x0)
	/usr/src/go/src/net/http/transport.go:228 +0x4d4
google.golang.org/cloud/internal.(*UATransport).RoundTrip(0xc20802af70, 0xc2080352b0, 0xc20801e9e0, 0x0, 0x0)
	/source/build/src/github.com/google/cadvisor/Godeps/_workspace/src/google.golang.org/cloud/internal/cloud.go:47 +0x109
net/http.send(0xc208035110, 0x7f1d191e9c20, 0xc20802af70, 0x1f, 0x0, 0x0)
	/usr/src/go/src/net/http/client.go:219 +0x4fc
net/http.(*Client).send(0x1113420, 0xc208035110, 0x1f, 0x0, 0x0)
	/usr/src/go/src/net/http/client.go:142 +0x15b
net/http.(*Client).doFollowingRedirects(0x1113420, 0xc208035110, 0xc08450, 0x0, 0x0, 0x0)
	/usr/src/go/src/net/http/client.go:367 +0xb25
net/http.(*Client).Get(0x1113420, 0xb60550, 0x1f, 0x54, 0x0, 0x0)
	/usr/src/go/src/net/http/client.go:299 +0xba
github.com/GoogleCloudPlatform/gcloud-golang/compute/metadata.OnGCE(0x0)
	/source/build/src/github.com/google/cadvisor/Godeps/_workspace/src/github.com/GoogleCloudPlatform/gcloud-golang/compute/metadata/metadata.go:126 +0xa6
github.com/google/cadvisor/utils/cloudinfo.onGCE(0xc2080d6000)
	/source/build/src/github.com/google/cadvisor/utils/cloudinfo/gce.go:25 +0x1f
github.com/google/cadvisor/utils/cloudinfo.detectCloudProvider(0x0, 0x0)
	/source/build/src/github.com/google/cadvisor/utils/cloudinfo/cloudinfo.go:52 +0x31
github.com/google/cadvisor/utils/cloudinfo.NewRealCloudInfo(0x0, 0x0)
	/source/build/src/github.com/google/cadvisor/utils/cloudinfo/cloudinfo.go:34 +0x31
github.com/google/cadvisor/manager.getMachineInfo(0x7f1d191ea3e8, 0x1122fb8, 0x7f1d191ea558, 0xc2080d4a30, 0x11135c0, 0x0, 0x0)
	/source/build/src/github.com/google/cadvisor/manager/machine.go:277 +0x82e
github.com/google/cadvisor/manager.New(0xc20809c5c0, 0x7f1d191ea3e8, 0x1122fb8, 0x0, 0x0, 0x0, 0x0)
	/source/build/src/github.com/google/cadvisor/manager/manager.go:151 +0x5d0
main.main()
	/source/build/src/github.com/google/cadvisor/cadvisor.go:69 +0x454

goroutine 5 [chan receive]:
github.com/golang/glog.(*loggingT).flushDaemon(0x1113980)
	/source/build/src/github.com/google/cadvisor/Godeps/_workspace/src/github.com/golang/glog/glog.go:839 +0x78
created by github.com/golang/glog.init·1
	/source/build/src/github.com/google/cadvisor/Godeps/_workspace/src/github.com/golang/glog/glog.go:406 +0x2a7

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
	/usr/src/go/src/runtime/asm_amd64.s:2232 +0x1

goroutine 11 [syscall]:
os/signal.loop()
	/usr/src/go/src/os/signal/signal_unix.go:21 +0x1f
created by os/signal.init·1
	/usr/src/go/src/os/signal/signal_unix.go:27 +0x35

goroutine 13 [select]:
net.lookupIPDeadline(0xc20801ea00, 0x18, 0xecd9f39bf, 0x2a2b1f6, 0x11135c0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/src/go/src/net/lookup.go:82 +0x6cb
net.resolveInternetAddr(0xace950, 0x3, 0xc20801ea00, 0x1b, 0xecd9f39bf, 0x2a2b1f6, 0x11135c0, 0x0, 0x0, 0x0, ...)
	/usr/src/go/src/net/ipsock.go:285 +0x49b
net.resolveAddr(0xabff70, 0x4, 0xace950, 0x3, 0xc20801ea00, 0x1b, 0xecd9f39bf, 0x2a2b1f6, 0x11135c0, 0x0, ...)
	/usr/src/go/src/net/dial.go:110 +0x378
net.(*Dialer).Dial(0xc208032b00, 0xace950, 0x3, 0xc20801ea00, 0x1b, 0x0, 0x0, 0x0, 0x0)
	/usr/src/go/src/net/dial.go:158 +0xf6
net.*Dialer.Dial·fm(0xace950, 0x3, 0xc20801ea00, 0x1b, 0x0, 0x0, 0x0, 0x0)
	/usr/src/go/src/net/http/transport.go:38 +0x79
net/http.(*Transport).dial(0xc2080641b0, 0xace950, 0x3, 0xc20801ea00, 0x1b, 0x0, 0x0, 0x0, 0x0)
	/usr/src/go/src/net/http/transport.go:479 +0x84
net/http.(*Transport).dialConn(0xc2080641b0, 0x0, 0xb60550, 0x4, 0xc20801ea00, 0x1b, 0x0, 0x0, 0x0)
	/usr/src/go/src/net/http/transport.go:564 +0x1678
net/http.func·019()
	/usr/src/go/src/net/http/transport.go:520 +0x42
created by net/http.(*Transport).getConn
	/usr/src/go/src/net/http/transport.go:522 +0x335
```

**Comment by deniseschannon** [comment] 2015-10-01 21:12
Confirmed. I got the same errors in the logs when using CoreOS. 

```
I1001 21:01:57.209585 03972 storagedriver.go:100] No backend storage selected
I1001 21:01:57.209654 03972 storagedriver.go:102] Caching stats in memory for 2m0s
I1001 21:01:57.209734 03972 manager.go:127] cAdvisor running in container: "/system.slice/docker-f12f5b0b781e457cfbbcd2c96d6f2907a6e7f01d46bb2c61f8f57c76bf4eb89c.scope"
I1001 21:01:57.210054 03972 fs.go:93] Filesystem partitions: map[/dev/sda9:{mountpoint:/ major:8 minor:9} /dev/sda3:{mountpoint:/usr major:8 minor:3} /dev/sda6:{mountpoint:/usr/share/oem major:8 minor:6}]
fatal error: unexpected signal during runtime execution
[signal 0xb code=0x1 addr=0x0 pc=0x0]

runtime stack:
runtime.gothrow(0xb9f4d0, 0x2a)
	/usr/src/go/src/runtime/panic.go:503 +0x8e
runtime.sigpanic()
	/usr/src/go/src/runtime/sigpanic_unix.go:14 +0x5e

goroutine 14 [syscall, locked to thread]:
runtime.cgocall_errno(0x401930, 0xc208017cd0, 0x0)
	/usr/src/go/src/runtime/cgocall.go:130 +0xf5 fp=0xc208017c90 sp=0xc208017c68
net._C2func_getaddrinfo(0x1841f80, 0x0, 0xc208017dc8, 0xc208017d18, 0x0, 0x0, 0x0)
	/usr/src/go/src/net/:26 +0x55 fp=0xc208017cd0 sp=0xc208017c90
net.cgoLookupIPCNAME(0xc2080d1700, 0x18, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/src/go/src/net/cgo_unix.go:96 +0x1c5 fp=0xc208017e00 sp=0xc208017cd0
net.cgoLookupIP(0xc2080d1700, 0x18, 0x0, 0x0, 0x0, 0x0, 0x0, 0xc208000120)
	/usr/src/go/src/net/cgo_unix.go:148 +0x65 fp=0xc208017e58 sp=0xc208017e00
net.lookupIP(0xc2080d1700, 0x18, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/src/go/src/net/lookup_unix.go:64 +0x5f fp=0xc208017ea0 sp=0xc208017e58
net.func·026(0x0, 0x0, 0x0, 0x0)
	/usr/src/go/src/net/lookup.go:79 +0x55 fp=0xc208017f08 sp=0xc208017ea0
net.(*singleflight).doCall(0x1112970, 0xc20800b200, 0xc2080d1700, 0x18, 0xc208071330)
	/usr/src/go/src/net/singleflight.go:91 +0x2f fp=0xc208017fb8 sp=0xc208017f08
runtime.goexit()
	/usr/src/go/src/runtime/asm_amd64.s:2232 +0x1 fp=0xc208017fc0 sp=0xc208017fb8
created by net.(*singleflight).DoChan
	/usr/src/go/src/net/singleflight.go:84 +0x42b

goroutine 1 [select]:
net/http.(*Transport).getConn(0xc2080641b0, 0xc208035450, 0x0, 0xb60550, 0x4, 0xc2080d1700, 0x1b, 0x0, 0x0, 0x0)
	/usr/src/go/src/net/http/transport.go:525 +0x608
net/http.(*Transport).RoundTrip(0xc2080641b0, 0xc208035450, 0xa, 0x0, 0x0)
	/usr/src/go/src/net/http/transport.go:228 +0x4d4
google.golang.org/cloud/internal.(*UATransport).RoundTrip(0xc20802af60, 0xc208035450, 0xc2080d16e0, 0x0, 0x0)
	/source/build/src/github.com/google/cadvisor/Godeps/_workspace/src/google.golang.org/cloud/internal/cloud.go:47 +0x109
net/http.send(0xc208035380, 0x7fa051921b28, 0xc20802af60, 0x1f, 0x0, 0x0)
	/usr/src/go/src/net/http/client.go:219 +0x4fc
net/http.(*Client).send(0x1113420, 0xc208035380, 0x1f, 0x0, 0x0)
	/usr/src/go/src/net/http/client.go:142 +0x15b
net/http.(*Client).doFollowingRedirects(0x1113420, 0xc208035380, 0xc08450, 0x0, 0x0, 0x0)
	/usr/src/go/src/net/http/client.go:367 +0xb25
net/http.(*Client).Get(0x1113420, 0xb60550, 0x1f, 0x25, 0x0, 0x0)
	/usr/src/go/src/net/http/client.go:299 +0xba
github.com/GoogleCloudPlatform/gcloud-golang/compute/metadata.OnGCE(0x0)
	/source/build/src/github.com/google/cadvisor/Godeps/_workspace/src/github.com/GoogleCloudPlatform/gcloud-golang/compute/metadata/metadata.go:126 +0xa6
github.com/google/cadvisor/utils/cloudinfo.onGCE(0xe)
	/source/build/src/github.com/google/cadvisor/utils/cloudinfo/gce.go:25 +0x1f
github.com/google/cadvisor/utils/cloudinfo.detectCloudProvider(0x0, 0x0)
	/source/build/src/github.com/google/cadvisor/utils/cloudinfo/cloudinfo.go:52 +0x31
github.com/google/cadvisor/utils/cloudinfo.NewRealCloudInfo(0x0, 0x0)
	/source/build/src/github.com/google/cadvisor/utils/cloudinfo/cloudinfo.go:34 +0x31
github.com/google/cadvisor/manager.getMachineInfo(0x7fa051922350, 0x1122fb8, 0x7fa0519224c0, 0xc2080709c0, 0x11135c0, 0x0, 0x0)
	/source/build/src/github.com/google/cadvisor/manager/machine.go:277 +0x82e
github.com/google/cadvisor/manager.New(0xc20808c540, 0x7fa051922350, 0x1122fb8, 0x0, 0x0, 0x0, 0x0)
	/source/build/src/github.com/google/cadvisor/manager/manager.go:151 +0x5d0
main.main()
	/source/build/src/github.com/google/cadvisor/cadvisor.go:69 +0x454

goroutine 5 [chan receive]:
github.com/golang/glog.(*loggingT).flushDaemon(0x1113980)
	/source/build/src/github.com/google/cadvisor/Godeps/_workspace/src/github.com/golang/glog/glog.go:839 +0x78
created by github.com/golang/glog.init·1
	/source/build/src/github.com/google/cadvisor/Godeps/_workspace/src/github.com/golang/glog/glog.go:406 +0x2a7

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
	/usr/src/go/src/runtime/asm_amd64.s:2232 +0x1

goroutine 11 [syscall]:
os/signal.loop()
	/usr/src/go/src/os/signal/signal_unix.go:21 +0x1f
created by os/signal.init·1
	/usr/src/go/src/os/signal/signal_unix.go:27 +0x35

goroutine 13 [select]:
net.lookupIPDeadline(0xc2080d1700, 0x18, 0xecd9f9645, 0x394330c1, 0x11135c0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/src/go/src/net/lookup.go:82 +0x6cb
net.resolveInternetAddr(0xace950, 0x3, 0xc2080d1700, 0x1b, 0xecd9f9645, 0x394330c1, 0x11135c0, 0x0, 0x0, 0x0, ...)
	/usr/src/go/src/net/ipsock.go:285 +0x49b
net.resolveAddr(0xabff70, 0x4, 0xace950, 0x3, 0xc2080d1700, 0x1b, 0xecd9f9645, 0x394330c1, 0x11135c0, 0x0, ...)
	/usr/src/go/src/net/dial.go:110 +0x378
net.(*Dialer).Dial(0xc208032b40, 0xace950, 0x3, 0xc2080d1700, 0x1b, 0x0, 0x0, 0x0, 0x0)
	/usr/src/go/src/net/dial.go:158 +0xf6
net.*Dialer.Dial·fm(0xace950, 0x3, 0xc2080d1700, 0x1b, 0x0, 0x0, 0x0, 0x0)
	/usr/src/go/src/net/http/transport.go:38 +0x79
net/http.(*Transport).dial(0xc2080641b0, 0xace950, 0x3, 0xc2080d1700, 0x1b, 0x0, 0x0, 0x0, 0x0)
	/usr/src/go/src/net/http/transport.go:479 +0x84
net/http.(*Transport).dialConn(0xc2080641b0, 0x0, 0xb60550, 0x4, 0xc2080d1700, 0x1b, 0x0, 0x0, 0x0)
	/usr/src/go/src/net/http/transport.go:564 +0x1678
net/http.func·019()
	/usr/src/go/src/net/http/transport.go:520 +0x42
created by net/http.(*Transport).getConn
	/usr/src/go/src/net/http/transport.go:522 +0x335
```

**Comment by terje2001** [comment] 2015-10-06 21:27
Also occurs using Fedora 22, seemingly identical stack trace, so not posting.

**Comment by gettoarun** [comment] 2015-10-29 13:40
Also appears on ubuntu:15.04

**Comment by sshipway** [comment] 2015-11-04 21:05
A big +1 to get this fixed.  We use CoreOS here and everything works with the exception of the statistics reporting in the UI, which is rather important.

**Comment by vincent99** [comment] 2015-11-06 16:55
This appears to be a (pre-)duplicate of #2380, which has more info in it, including fix for next release..

**Closed by vincent99** 2015-11-06 16:55 UTC
Labels: area/agent, kind/bug
