### ISSUE TITLE
Azure shared disk PV fails to provision from storage class when storage account type is not set

### ISSUE THREAD

**Issue by bmdepesa** [rancher/rancher#20315] opened 2019-05-18 02:11 UTC
If a storage account type is not entered when creating a shared unmanaged disk storage class on Azure Disk, the PV will fail to create. This occurs on k8s versions >= 1.12

To reproduce: 
* Deploy Rancher v2.2.4-rc5
* Create Azure cluster w/ cloud provider, k8s version >= 1.12
* Create a storage class for Azure Disk - shared unmanaged, without specifying the storage type
* Create workload with a new volume from the storage class
* The workload and PV will fail to create.

![Screen Shot 2019-05-17 at 7 08 12 PM](https://user-images.githubusercontent.com/21316915/57963298-283e8b00-78d7-11e9-87dd-f6c58e7ad05e.png)

* If the storage account type is specified, the PV will create regardless of k8s version.
* This does not occur on k8s v1.11.
* This does not occur with the dedicated unmanaged disk.
* This does not seem to be dependent on Rancher version:
  * Created a v1.11 cluster in v2.1.7 without storage account type set
  * PV provisioned after upgrade (before upgrading k8s version)
* This occurs in other versions of Rancher where clusters are created with k8s v1.12+ (v2.1.7, v2.2.2, etc..)
* This occurs in clusters that have been upgraded beyond k8s v1.11 (if a storage class was working in a v1.11 cluster, new volumes will fail to provision after the cluster is upgraded)

**Comment by kinarashah** [comment] 2019-05-18 02:13
Just to reiterate, this can be reproduced using rancher v2.1.7 too

**Comment by alena1108** [comment] 2019-05-18 04:21
Moving to v2.2 backlog as the issue is not a regression in 2.2.x. Will include the fix to one of our future releases.

**Comment by sowmyav27** [comment] 2019-08-09 15:10
### Reproduced the issue on `rancher:2.2.7`.
**Steps:**

- Deploy an Azure cluster - 1 node all roles, with cloud configuration enabled. (k8s v - 1.14)
- Create a storage class for Azure Disk - shared unmanaged, without specifying the storage type.
- Create workload with a new volume from the storage class
- The workload and PV will fail to create.

### Validated in `rancher:master-head-linux-amd64`.
**Steps:**

- Deploy an Azure cluster - 1 node all roles, with cloud configuration enabled.
- Create a storage class for Azure Disk - shared unmanaged, without specifying the storage type.
- Create workload with a new volume from the storage class
- Volume gets provisioned successfully
- Workload is deployed successfully with the volume attached to it.
- 
-

**Closed** 2019-08-09 15:45 UTC
Labels: [zube]: To Test, area/storage, kind/bug, team/az
