### ISSUE TITLE
Spurious validation errors when cloning container

### ISSUE THREAD

**Issue by gordontyler** [rancher/rancher#2691] opened 2015-11-16 15:29 UTC
I have a container that I'm trying to clone to a different host in my Rancher environment. The container uses a link to another container (db) which has already been cloned to the new host. The container also exposes a port which is bound to a port on the host.

After clicking the Clone command and setting up the link to the new db container and scheduling the clone to run on the new host, when I click Create, it comes back with a "Validation failed in API: environment" error. This confuses me because the original container had no environment variables set and I didn't add any when setting up the clone. 

If I click the (+) button in the Environment Vars section of the clone config and then delete that blank env var, clicking Create comes back with a different error: "Validation failed in API: PortWrongFormat". This is also confusing because visually inspecting the Port Map for the clone shows nothing wrong with the single port mapping (81 -> 8080 TCP).

If I delete and recreate the port mapping, the Create button then works.

**Comment by gordontyler** [comment] 2015-11-16 15:32
As a further test, I cloned the original container again, this time clearing and recreating the port mapping and creating and deleting a blank env var before clicking Create for the first time and the container was created without any validation errors. This leads me to believe that the initial configuration of the clone is bogus.

**Comment by gordontyler** [comment] 2015-11-16 15:33
Rancher	v0.44.0
Cattle	v0.107.0
User Interface	v0.65.0
Rancher Compose	v0.5.1

**Comment by deniseschannon** [comment] 2015-11-17 20:06
Not sure if you still have this around, but could you share the docker-compose.yml of the service that you were trying to clone?

**Comment by gordontyler** [comment] 2015-11-17 20:08
It was a manually created container, so there is no docker-compose.yml, nor is there a service from which I could export it.

I still have it running, if there's anything else you want me to try.

**Comment by deniseschannon** [comment] 2015-11-17 22:52
What do you mean by "manually created container"? How did you create it? Service linking wouldn't work when using a standalone container (option isn't in the UI), so I'm not sure what steps you've done to create this container. :)

Did you use the API or a docker run command?

**Comment by gordontyler** [comment] 2015-11-18 14:27
I created the original container through the Rancher UI by clicking the "Add Container" button on a Host page, i.e. not as an application service.

When I use the "Clone" operation on this container, the clone's configuration is initially broken as I described above.

**Comment by magnus919** [comment] 2015-12-30 14:28
I'm also seeing this. Like @gordontyler, I'm creating standalone containers through the web UI.

`Rancher	v0.50.2`
`Cattle	v0.127.0`
`User Interface	v0.75.0`
`Rancher Compose	v0.6.2`

**Comment by vincent99** [comment] 2016-01-27 21:37
Pre-duplicate of https://github.com/rancher/rancher/issues/3431

**Closed by vincent99** 2016-01-27 21:37 UTC
Labels: area/ui, kind/bug, release/v1.0.0
