### ISSUE TITLE
Volumes-From Sidekicks defaults to unselected when upgrading a service

### ISSUE THREAD

**Issue by ragaar** [rancher/rancher#4272] opened 2016-04-01 22:23 UTC
It isn't really relevant but the parent container looks like this:

> ```
> ovpn:
>   ports:
>   - 1194:1194/udp
>   labels:
>     io.rancher.sidekicks: ovpn-genconfig,ovpn-data,ovpn-initpki
>   image: kylemanna/openvpn
>   volumes_from:
>   - ovpn-genconfig
>   - ovpn-data
>   - ovpn-initpki
>   cap_add:
>   - NET_ADMIN
> ```

While adjusting the command line parameters for ovpn-genconfig, I discovered that Rancher's web UI tries to remove all of the volumes, in the volumes tab, from the containers listed under `volumes_from`

Steps to recreate:
1. Create a stack with multiple sidekicks, define the primary service as `never (start once)`
2. Launch the stack
3. Navigate to the container view for the stack ```<rancher url>/apps/1e18/services/1s12/containers```
4. Select the `upgrade` option
5. Change the restart behavior of the primary service to `always`
6. Navigate to the `volumes` tab, make no changes
7. Add a sidekick service to the upgrade; in my case, I used `ovpn-genconfig`
8. Navigate to the sidekick's upgrade panel, make no changes.
9. Navigate to the primary service's upgrade panel.

In my experience Step 9, Navigating to the primary panel, is not mandatory. Adjusting the sidekick and finalizing the upgrade seems to be sufficient to remove all of the containers listed under the primary service's `volumes-from` list.

Step 9 was included as it seems like a good visual test.

---
`Rancher`
> v0.59.1

`Cattle`
> v0.148.1

`User Interface`
> v0.90.0

`Rancher Compose`
> v0.7.2

`docker info`
> Server Version: 1.9.1
> Storage Driver: btrfs
> Build Version: Btrfs v3.17
> Library Version: 101
> Execution Driver: native-0.2
> Logging Driver: json-file
> Kernel Version: 3.16.0-4-amd64
> Operating System: Debian GNU/Linux 8 (jessie)

**Comment by ragaar** [comment] 2016-04-01 22:26
I am aware my version of Rancher is slightly out-of-date, I am not in a good position to upgrade my services at the moment. I am working to upgrade to the latest release, but it will be a little while.

As such, I would suggest not relying on me for testing for the moment.

**Comment by vincent99** [comment] 2016-04-01 22:28
Duplicate of https://github.com/rancher/rancher/issues/3914

**Closed by vincent99** 2016-04-01 22:28 UTC
