### ISSUE TITLE
[backport] 2.2 - Compatibility issues with cert-manager v0.11.0

### ISSUE THREAD

**Issue by drpebcak** [rancher/rancher#23693] opened 2019-10-25 21:40 UTC
backport for issue described in rancher/rancher#23424

**Comment by jiaqiluo** [comment] 2019-12-17 21:33
closed in favor of https://github.com/rancher/rancher/pull/24519

**Comment by jiaqiluo** [comment] 2019-12-18 19:52
The issue is reopened, we need to find the proper upgrading path for upgrading cert-manager and Rancher together

**Comment by jiaqiluo** [comment] 2020-01-13 18:05
The upgrading instruction is logged in the original issue. 
This issue can be closed.

**Closed by jiaqiluo** 2020-01-13 18:05 UTC
Labels: [zube]: Reopened
