### ISSUE TITLE
Panic seen in rancher server during start

### ISSUE THREAD

**Issue by sowmyav27** [rancher/rancher#36925] opened 2022-03-16 20:55 UTC
**Rancher Server Setup**
- Rancher version: 2.6.3-patch2
- Installation option (Docker install/Helm Chart): docker install
   
**Describe the bug**
Panic in rancher server during start

**To Reproduce**

- Deploy rancher.
- Panic seen in rancher, and rancher restarts.
- No further issue seen

**Result**
```
2022/03/16 18:02:14 [INFO] Watching metadata for rke-machine-config.cattle.io/v1, Kind=HarvesterConfig
panic: indexer conflict: map[byPod:{}]

goroutine 2811 [running]:
k8s.io/apimachinery/pkg/util/runtime.Must(...)
	/go/pkg/mod/k8s.io/apimachinery@v0.22.3/pkg/util/runtime/runtime.go:171
github.com/rancher/rancher/pkg/generated/controllers/catalog.cattle.io/v1.(*operationCache).AddIndexer(0xc00b166fc0, 0x44ff3da, 0x5, 0x4740d58)
	/go/src/github.com/rancher/rancher/pkg/generated/controllers/catalog.cattle.io/v1/operation.go:247 +0x127
github.com/rancher/rancher/pkg/controllers/dashboard/helm.RegisterOperations(0x4cdd148, 0xc0051cfac0, 0x4d46978, 0xc001956580, 0x4d2d228, 0xc0059a40e0, 0x4d2ac18, 0xc0059a4150)
	/go/src/github.com/rancher/rancher/pkg/controllers/dashboard/helm/operations.go:42 +0x1b8
github.com/rancher/rancher/pkg/controllers/dashboard/helm.Register(0x4cdd148, 0xc0051cfac0, 0xc000c76000)
	/go/src/github.com/rancher/rancher/pkg/controllers/dashboard/helm/register.go:22 +0x3c5
github.com/rancher/rancher/pkg/controllers/dashboard.Register(0x4cdd148, 0xc0051cfac0, 0xc000c76000, 0xc00b166d01, 0x4bca6b9, 0x0)
	/go/src/github.com/rancher/rancher/pkg/controllers/dashboard/controller.go:23 +0x5a
github.com/rancher/rancher/pkg/rancher.(*Rancher).Start.func1.1(0x4cdd148, 0xc0051cfac0, 0x3cd6800, 0x6f803c0)
	/go/src/github.com/rancher/rancher/pkg/rancher/rancher.go:251 +0x4e
github.com/rancher/rancher/pkg/wrangler.(*Context).StartWithTransaction(0xc000c76000, 0x4cdcc78, 0xc0031a1b40, 0xc0044e5f58, 0x0, 0x0)
	/go/src/github.com/rancher/rancher/pkg/wrangler/context.go:152 +0xdc
github.com/rancher/rancher/pkg/rancher.(*Rancher).Start.func1(0x4cdcc78, 0xc0031a1b40, 0x45747c4, 0x1e)
	/go/src/github.com/rancher/rancher/pkg/rancher/rancher.go:251 +0x107
github.com/rancher/wrangler/pkg/leader.(*Manager).OnLeader.func1(0xc0018077a0, 0xc00358e330)
	/go/pkg/mod/github.com/rancher/wrangler@v0.8.10/pkg/leader/manager.go:51 +0xcc
created by github.com/rancher/wrangler/pkg/leader.(*Manager).OnLeader
	/go/pkg/mod/github.com/rancher/wrangler@v0.8.10/pkg/leader/manager.go:48 +0x49
2022/03/16 18:02:33 [INFO] Rancher version v2.6.3-patch2 (98b345916) is starting
2022/03/16 18:02:33 [INFO] Listening on /tmp/log.sock
```

**Comment by admun** [comment] 2022-03-17 00:38
I am seeing the same issue... this's been happened since 2.6.3

**Comment by thedadams** [comment] 2022-03-17 01:16
This panic indicates that there was an error during Rancher startup. A careful inspection of the entire Rancher log would be needed to determine the issue.

**Comment by admun** [comment] 2022-03-17 16:25
In my case, podman logs show no error, I see there is a k3s-cluster-reset.log

[k3s-cluster-reset.log](https://github.com/rancher/rancher/files/8288067/k3s-cluster-reset.log)

**Comment by snasovich** [comment] 2022-03-29 19:02
Moving to Blocked as we need more input from QA before we're able to proceed further.

**Comment by slickwarren** [comment] 2022-04-13 20:48
QA hasn't reproduced this since this ticket was filed. If we see a ticket in the future, we will reopen/file a new ticket.

**Closed by slickwarren** 2022-04-13 20:48 UTC
Labels: kind/bug-qa, team/area2, [zube]: Blocked

**Comment by all4innov** [comment] 2022-10-19 15:29
to reopen
