### ISSUE TITLE
Rancher very slow, frequent time-outs, clusters sporadically unavailable, almost never loads successfully

### ISSUE THREAD

**Issue by virtuman** [rancher/rancher#27390] opened 2020-06-02 05:43 UTC
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
Added a few GKE imported, and VmWare RKE clusters (started noticing at 2+ clusters). 
Installed several helm 3 releases (ie 25+ with some of them up to 10 upgrades)

**Result:**
Rancher homepage with list of clusters is consistently very fast and great.
ERROR: Clicking on any of the clusters - often lands me on proper cluster's overview (cluster-home page), but some clusters don't even open that page - timeout and some error.
ERROR: Switching to project inside the cluster - freezes computer and eventually followed by some type of timeout error

**Other details that may be helpful:**
it is definitely related to the fact that rancher UI fetches all configmaps and secrets during the page/project initialization and in our case we have too many helm releases, and it just TOOOOO much to transfer

**Environment information**
- Rancher version : started from 2.3.* to 2.4.3
- Installation option (single install/HA): HA

**Comment by janeczku** [comment] 2020-07-06 14:23
Thanks for the report @virtuman. Closing since the issue is already tracked here: https://github.com/rancher/rancher/issues/25487

**Closed by janeczku** 2020-07-06 14:23 UTC
