### ISSUE TITLE
all kubectl exec attempts fail with "403 - upgrade_failed" when using istio for rancher ingress

### ISSUE THREAD

**Issue by jesseagonzalez** [rancher/rancher#35235] opened 2021-10-20 23:20 UTC
**Rancher Server Setup**

- Rancher version: `v2.5.9+`

- Installation option (Docker install/Helm Chart): `Helm Chart`
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): 
   - `Validated on both RKE:v1.2.9 and RKE2:v1.20.10+rke2r1`
- Proxy/Cert Details:
  - `Validated with both Self-Signed Certs with Cert-Manager & Seen on Customer Site with Internal Private CA.`
  - `Validated with HTTP_PROXY enabled & disabled`

**Information about the Cluster**

- Kubernetes version: `RKE2 v1.20.10+rke2r1 or RKE v1.2.9`
- Cluster Type (Local/Downstream): `Local or Downstream`
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider): `Imported`

**Describe the bug**

Rather than leveraging default `ingress-nginx` ingress controller already deployed as part of `rancher's helm chart` to expose the underlying `Rancher UI`, the customer preferred leveraging `istio's ingressgateway` as an alternative ingress controller.  

However, when running `rancher` server url behind `istio's ingressgateway` --AND-- while using `kubeconfig` file generated from `Rancher's Cluster Manager` UI, `kubectl` fails to `exec` into ANY `pod` deployed nor ANY `container` (within pod) nor ANY `namespace`.  

If I revert to leveraging generated `kubeconfig` behind default `ingress-nginx` controller already deployed, all is well again.

Below are examples of `FAILING` scenarios (w/wo `istio-proxy` sidecar):

```
(⎈|rke-kubeconfig-behind-istio:tornado)
$ kubectl exec -it tornado-5f7548c9b5-f4tzt -n tornado -- ls
Defaulted container "tornado" out of: tornado, istio-proxy, istio-validation (init)
Error from server:

(⎈|rke-kubeconfig-behind-istio:cattle-system) 
$ k exec -it rancher-69c4f4c9f9-8hkc4 -n cattle-system -- ls
Error from server: 
```

> `istio-ingressgateway` pod logs from ^^  above

```
istio-ingressgateway-77ffcc64cd-nd6tk istio-proxy [2021-10-19T15:34:57.035Z] "GET /k8s/clusters/local/api/v1/namespaces/tornado/pods/tornado-fb8565db4-p6c6z HTTP/2" 200 - via_upstream - "-" 0 14047 4 4 "10.0.0.64" "kubectl/v1.21.3 (darwin/amd64) kubernetes/ca643a4" "998df653-a9e4-9017-a198-d6e56066a77d" "rancher-istio.10.0.0.225.nip.io" "10.42.1.12:80" outbound|80||rancher.cattle-system.svc.cluster.local 10.42.2.12:53028 10.42.2.12:8443 10.0.0.64:52390 rancher-istio.10.0.0.225.nip.io -

istio-ingressgateway-77ffcc64cd-nd6tk istio-proxy [2021-10-19T15:34:57.057Z] "POST /k8s/clusters/local/api/v1/namespaces/tornado/pods/tornado-fb8565db4-p6c6z/exec?command=ls&container=tornado&stdin=true&stdout=true&tty=true HTTP/1.1" 403 - upgrade_failed - "-" 0 0 0 - "10.0.0.64" "kubectl/v1.21.3 (darwin/amd64) kubernetes/ca643a4" "5fb8e59f-5616-9383-b3fc-db3408fe5666" "rancher-istio.10.0.0.225.nip.io" "-" outbound|80||rancher.cattle-system.svc.cluster.local - 10.42.2.12:8443 10.0.0.64:9951 rancher-istio.10.0.0.225.nip.io -
```

**To Reproduce**

The following details assumes `existing rancher v2.5.9+` cluster with `metallb 9.3+` for LB VIPs and `ingress-nginx` controllers already installed and configured.

Given assumptions, the simplest way to reproduce is to:

1. Deploy `Istio` (validated with `istio v1.9.8, v1.10.4 & v1.11.2`) on existing `rancher v2.5.9+` cluster (doesn't matter how).  

  Example below using `istioctl v1.11.2` (with addt'l parameters):

  ```
  istioctl install --set profile=demo --set components.cni.namespace=kube-system --set components.cni.enabled=true --set meshConfig.enableTracing=true --set meshConfig.accessLogFile=/dev/stdout
  ```

2. Deploy `new` or `update` existing `rancher` `ingress` object within `cattle-system` `namespace` to include `kubernetes.io/ingress.class: istio` annotation.

  Example below includes both ingress objects - 

  ```
  (⎈ |rke-kubeconfig-behind-nginx:tornado) 
  $ kubectl get ingress -n cattle-system

  NAME            CLASS    HOSTS                             ADDRESS                         PORTS     AGE
  rancher         <none>   rancher.10.0.0.71.nip.io          10.0.0.71,10.0.0.72,10.0.0.73   80, 443   26h
  rancher-istio   <none>   rancher-istio.10.0.0.226.nip.io   10.0.0.226                      80, 443   25h
  ```

3. Copy `rancher ingress tls secret` to `istio-system` namespace.

  - Get existing secret name from ingress object: i.e., `secretName: tls-rancher-ingress`
  - Export out to istio-system
    `kubectl get secret tls-rancher-ingress -o yaml | kubectl apply -f - -n istio-system`

4. Navigate to rancher portal via vip behind istio ingress - i.e., https://rancher-istio.10.0.0.226.nip.io

5. Navigate to ANY upstream or downstream cluster and download kubeconfig file locally using preferred method to access via kubectl.

  Example below validating server url

  ```
  (⎈ |rke-kubeconfig-behind-istio:istio-system) 
  $ k config view --minify | grep server
    server: https://rancher-istio.10.0.0.226.nip.io/k8s/clusters/local
  ```

6. Attempt to attach to any pod/container on any namespace `kubectl exec -it <pod-name> -- ls` - see bug description for example ^^

**Result**

see bug description for example results ^^

**Expected Result**

Expectation is that kubectl exec into any pod should function correctly

Below are examples of `SUCCESSFUL` scenarios behind `nginx ingress`:

```
(⎈ |rke-kubeconfig-behind-nginx:tornado) 
$ k exec -it rancher-69c4f4c9f9-8hkc4 -n cattle-system -- ls
etcd  k3s  management-state

$ kubectl exec -it tornado-5f7548c9b5-f4tzt -n tornado -- ls
Defaulted container "tornado" out of: tornado, istio-proxy, istio-validation (init)
bin   dev  home  lib64  mnt  proc  run   srv  tmp  var
boot  etc  lib   media  opt  root  sbin  sys  usr
```

> `nginx-ingress-controller` pod logs from ^^  above

```
nginx-ingress-controller-sr7wf nginx-ingress-controller 10.0.0.10 - - [19/Oct/2021:15:31:17 +0000] "GET /k8s/clusters/local/api/v1/namespaces/tornado/pods/tornado-fb8565db4-p6c6z HTTP/2.0" 200 3555 "-" "kubectl/v1.21.3 (darwin/amd64) kubernetes/ca643a4" 206 0.007 [cattle-system-rancher-80] [] 10.42.2.8:80 14060 0.008 200 334886b8b2fa801d1110437552b15db7

nginx-ingress-controller-sr7wf nginx-ingress-controller 10.0.0.10 - - [19/Oct/2021:15:31:17 +0000] "POST /k8s/clusters/local/api/v1/namespaces/tornado/pods/tornado-fb8565db4-p6c6z/exec?command=ls&container=tornado&stdin=true&stdout=true&tty=true HTTP/1.1" 101 329 "-" "kubectl/v1.21.3 (darwin/amd64) kubernetes/ca643a4" 598 0.116 [cattle-system-rancher-80] [] 10.42.2.8:80 0 0.116 101 fc5e36c00d91230b932c6a8819e5bc36
```

**Screenshots**

<img width="1086" alt="2021-10-20-19-11-45" src="https://user-images.githubusercontent.com/8986826/138185296-c5c44143-0561-40d0-ab2f-51ec2c6ca027.png">

**Additional context**

It is probably worth mentioning that this has been validated with & without:

- `namespace` having `istio-injection=enabled` label
-  `istio virtualservices` / `gateway` objects vs. k8s `ingress` objects (via `kubernetes.io/ingress.class: istio`)
- `istio` deployed via `helm chart`, `Rancher App & Marketplace` and `istioctl`
- `istio-ingressgateway-service-account` role-binding to `cluster-admin` clusterrole

Lastly, I would also add that while doing some minor regression testing, it seemed that most if not all other functionality via portal and/or kubectl seems to work fine....

**Comment by Jono-SUSE-Rancher** [comment] 2022-01-20 15:49
Hi @jesseagonzalez - I will override stale bot and re-open this issue to see if I can get it in front of the team, though I cannot promise any timelines for when they will be able to review it.

**Comment by clemenko** [comment] 2022-02-11 14:10
Unable to reproduce with RKE v1.22.6+rke2r1, Rancher 2.6.3 and Istio 1.11.2.

**Comment by doflamingo721** [comment] 2022-04-28 10:42
**I was not able to reproduce this issue on rancher v2.6-head (7db4fe4).** 

**Rancher installation option:** helm
**Kubernetes version:** v1.22.7-rancher1-1
**Cluster type:** RKE

**Steps to validate:**
1. Install `istio 1.12.6 ` from Apps and marketplace. 
2. Update the existing `rancher` ingress object in the `cattle-system `namespace to include the `kubernetes.io/ingress.class: istio` annotation.
3. Copy `rancher ingress tls secret` to istio-system namespace.
4. Navigate to ANY upstream or downstream cluster and download kubeconfig file locally using preferred method to access via kubectl.
5. Exec into any pod or container.

Result:
`kubectl exec ` into any pod/container is working correctly.

@jesseagonzalez Can you please confirm if this is still an issue you're facing?

**Comment by doflamingo721** [comment] 2022-05-04 05:08
Hey @jesseagonzalez  Can you please confirm if this issue is still active or not for you so that we can move forward accordingly?

**Comment by rishabhmsra** [comment] 2022-05-24 11:14
Validated on rancher v2.6-head(aedfe61) and not able to reproduce it.

Rancher installation option: helm
Kubernetes version: v1.23.6
Cluster type: RKE

Followed below steps :
- Installed istio `100.3.0+up1.13.3` from apps and marketplace in `local` cluster.
- Updated the existing rancher ingress object in the `cattle-system` namespace to include the `kubernetes.io/ingress.class: istio` annotation.
- Copied rancher ingress tls secret to istio-system namespace.
- Downloaded the kubeconfig of `local` cluster locally to access kubectl 
- Was able to exec into the pod.
- Also created a downstream cluster using k8s v1.23.6-rancher1-1 and downloaded the kubeconfig file locally.

Result:
- kubectl exec into any pod/container is working as expected, hence closing the issue.

**Closed by rishabhmsra** 2022-05-24 11:14 UTC
Labels: area/istio, [zube]: QA Working, team/area3, team/infracloud
