### ISSUE TITLE
Resource quota not working with Project in Rancher 2.6.x

### ISSUE THREAD

**Issue by huytn1219** [rancher/rancher#36541] opened 2022-02-16 18:35 UTC
**Rancher Server Setup**
- Rancher version: 2.6.3
- Installation option (Docker install/Helm Chart):
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): RKE1,RKE2
- Proxy/Cert Details: N/A

**Information about the Cluster**
- Kubernetes version: 1.21.9
- Cluster Type (Local/Downstream): Downstream
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider): Custom

**User Information**
- What is the role of the user logged in? (Admin/Cluster Owner/Cluster Member/Project Owner/Project Member/Custom) Restricted Admin
  - If custom, define the set of permissions:

   
**Describe the bug**

Resources quotas weren't created in namespaces other than `default`. 
Also, resources cannot be removed once they are created in a project.

**To Reproduce**
 
* Create a new project.
* In the new project, create some resource quotas such as CPU Reservation, CPU Limit, Memory Reservation, etc...
* From the new project, create a namespace with a propagated resource quota for that namespace.
* Create a deployment in the new namespace.

**Result**
* Deployments in the namespace were still able to be deployed without resource restriction.
* `resourcequota` objects weren't automatically created in the cluster under new namespace
*  Removing resource quotas from the project in the UI didn't work.

**Expected Result**

* Deployments without resources specified should be prohibited.
* Deployments with resources specified should work properly.
* Removing resources quotas from Project in the UI should work.

**Screenshots**

**Additional context**

The `default` namespace works perfectly fine when we set the resource quota for the default project. 
if I switched back to the old UI using `https://rancher-ui.com/g` and created resource quota for a project. This worked fine with no issue.

**Comment by richard-cox** [comment] 2022-02-17 08:21
Possible duplicate of https://github.com/rancher/dashboard/issues/4804 which was fixed in 2.6.3 patch 1. @huytn1219 Can you confirm by checking the resourceQuota annotation of the project, there may be a blank space between the value and unit in some/all of the limits?

**Comment by huytn1219** [comment] 2022-02-22 19:45
@richard-cox It does have a space in between. I followed the instruction from https://github.com/rancher/dashboard/issues/4804#issuecomment-1016536254  and the issue got fixed. Thanks

**Comment by sunny760408** [comment] 2022-02-23 08:24
It web UI issue, you can go back to old UI version.

Login in original first, and then modify url as below.
original url: abc.com**/dashboard/**
old version url: abc.com**/g/clusters**

**Comment by richard-cox** [comment] 2022-02-23 08:28
@huytn1219 Fantastic! That fix is in 2.6.3 patch 1 and the next 2.6.4 release, so closing this issue

**Closed by richard-cox** 2022-02-23 08:28 UTC
