### ISSUE TITLE
machine driver issues: fatal error: unexpected signal during runtime execution

### ISSUE THREAD

**Issue by kaos** [rancher/rancher#5420] opened 2016-07-14 08:07 UTC
**Rancher Version:**
1.1.0

**Docker Version:**
1.11.2

**OS and where are the hosts located? (cloud, bare metal, etc):**
RedHat 7, bare metal

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
Single node, external DB

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle

**Steps to Reproduce:**
Running latest version... (not a new install, upgraded from 0.59.1, but also see this on another site where we upgraded from 1.0.1)

**Results:** 
See logs below.

**Expected:**
No panics.. ;)

Let me know what more you want to look at :)

Log:

```
time="2016-07-14T08:03:27Z" level=info msg="Setting log level" logLevel=info 
time="2016-07-14T08:03:27Z" level=info msg="Starting go-machine-service..." gitcommit=v0.31.6 
time="2016-07-14T08:03:27Z" level=info msg="Waiting for handler registration (1/2)" 
fatal error: unexpected signal during runtime execution
[signal 0xb code=0x1 addr=0x63 pc=0x7fd5cf5c0b2c]

runtime stack:
runtime.throw(0xc1a1a0, 0x2a)
    /usr/local/go/src/runtime/panic.go:547 +0x90
runtime.sigpanic()
    /usr/local/go/src/runtime/sigpanic_unix.go:12 +0x5a

goroutine 12 [syscall, locked to thread]:
runtime.cgocall(0x865ac0, 0xc82017dbd8, 0x0)
    /usr/local/go/src/runtime/cgocall.go:123 +0x11b fp=0xc82017db78 sp=0xc82017db48
net._C2func_getaddrinfo(0x7fd5c80008c0, 0x0, 0xc8201163f0, 0xc8200280b8, 0x0, 0x0, 0x0)
    ??:0 +0x55 fp=0xc82017dbd8 sp=0xc82017db78
net.cgoLookupIPCNAME(0xc8200bb547, 0x9, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0xc85c00)
    /usr/local/go/src/net/cgo_unix.go:111 +0x448 fp=0xc82017dd50 sp=0xc82017dbd8
net.cgoLookupIP(0xc8200bb547, 0x9, 0x0, 0x0, 0x0, 0x0, 0x0, 0x7fd5d08128e8)
    /usr/local/go/src/net/cgo_unix.go:163 +0x56 fp=0xc82017dda8 sp=0xc82017dd50
net.lookupIP(0xc8200bb547, 0x9, 0x0, 0x0, 0x0, 0x0, 0x0)
    /usr/local/go/src/net/lookup_unix.go:67 +0x94 fp=0xc82017de18 sp=0xc82017dda8
net.glob.func16(0xc85cd0, 0xc8200bb547, 0x9, 0x0, 0x0, 0x0, 0x0, 0x0)
    /usr/local/go/src/net/hook.go:10 +0x4d fp=0xc82017de58 sp=0xc82017de18
net.lookupIPDeadline.func1(0x0, 0x0, 0x0, 0x0)
    /usr/local/go/src/net/lookup.go:106 +0x71 fp=0xc82017ded8 sp=0xc82017de58
internal/singleflight.(*Group).doCall(0x10d60b0, 0xc820018c30, 0xc8200bb547, 0x9, 0xc8200bb6c0)
    /usr/local/go/src/internal/singleflight/singleflight.go:93 +0x2c fp=0xc82017df88 sp=0xc82017ded8
runtime.goexit()
    /usr/local/go/src/runtime/asm_amd64.s:1998 +0x1 fp=0xc82017df90 sp=0xc82017df88
created by internal/singleflight.(*Group).DoChan
    /usr/local/go/src/internal/singleflight/singleflight.go:86 +0x3ee

goroutine 1 [chan receive]:
main.main()
    /go/src/github.com/rancher/go-machine-service/main.go:74 +0x38e

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
    /usr/local/go/src/runtime/asm_amd64.s:1998 +0x1

goroutine 18 [syscall]:
os/signal.signal_recv(0x6)
    /usr/local/go/src/runtime/sigqueue.go:116 +0x132
os/signal.loop()
    /usr/local/go/src/os/signal/signal_unix.go:22 +0x18
created by os/signal.init.1
    /usr/local/go/src/os/signal/signal_unix.go:28 +0x37

goroutine 19 [chan receive]:
github.com/rancher/go-machine-service/locks.locker()
    /go/src/github.com/rancher/go-machine-service/locks/locks.go:61 +0xdf
created by github.com/rancher/go-machine-service/locks.init.1
    /go/src/github.com/rancher/go-machine-service/locks/locks.go:7 +0x59

goroutine 20 [select]:
net/http.(*Transport).getConn(0xc8200c2000, 0xc82010c1c0, 0x0, 0xc8200bb540, 0x4, 0xc8200bb547, 0xe, 0x0, 0x0, 0x0)
    /usr/local/go/src/net/http/transport.go:711 +0x4ef
net/http.(*Transport).RoundTrip(0xc8200c2000, 0xc82010c1c0, 0xc8200c2000, 0x0, 0x0)
    /usr/local/go/src/net/http/transport.go:311 +0x7e9
net/http.send(0xc82010c0e0, 0x7fd5d08125f8, 0xc8200c2000, 0xecf193e6d, 0x2eaf60f, 0x10d6e60, 0xc8200bb600, 0x0, 0x0)
    /usr/local/go/src/net/http/client.go:260 +0x6b7
net/http.(*Client).send(0xc82011d350, 0xc82010c0e0, 0xecf193e6d, 0x2eaf60f, 0x10d6e60, 0xc8200791e0, 0x0, 0x0)
    /usr/local/go/src/net/http/client.go:155 +0x185
net/http.(*Client).doFollowingRedirects(0xc82011d350, 0xc82010c0e0, 0xc85f00, 0x0, 0x0, 0x0)
    /usr/local/go/src/net/http/client.go:475 +0x8a4
net/http.(*Client).Do(0xc82011d350, 0xc82010c0e0, 0x14, 0x0, 0x0)
    /usr/local/go/src/net/http/client.go:188 +0xff
github.com/rancher/go-machine-service/vendor/github.com/rancher/go-rancher/client.setupRancherBaseClient(0xc820148800, 0xc820124c40, 0x0, 0x0)
    /go/src/github.com/rancher/go-machine-service/vendor/github.com/rancher/go-rancher/client/common.go:152 +0x8b9
github.com/rancher/go-machine-service/vendor/github.com/rancher/go-rancher/client.NewRancherClient(0xc820124c40, 0xc820124c40, 0x0, 0x0)
    /go/src/github.com/rancher/go-machine-service/vendor/github.com/rancher/go-rancher/client/generated_client.go:274 +0x4b
github.com/rancher/go-machine-service/events.NewEventRouter(0xbdb9c0, 0x18, 0x7d0, 0xc82001003b, 0x18, 0xc820010222, 0x14, 0xc820016012, 0x28, 0x0, ...)
    /go/src/github.com/rancher/go-machine-service/events/listener.go:235 +0xe7
main.main.func1(0xc82001003b, 0x18, 0xc820010222, 0x14, 0xc820016012, 0x28, 0xc82015a7e0, 0xc8201385a0)
    /go/src/github.com/rancher/go-machine-service/main.go:41 +0x339
created by main.main
    /go/src/github.com/rancher/go-machine-service/main.go:46 +0x2bf

goroutine 21 [select]:
net/http.(*Transport).getConn(0xc8200c2000, 0xc820156540, 0x0, 0xc82011bba0, 0x4, 0xc82011bba7, 0xe, 0x0, 0x0, 0x0)
    /usr/local/go/src/net/http/transport.go:711 +0x4ef
net/http.(*Transport).RoundTrip(0xc8200c2000, 0xc820156540, 0xc8200c2000, 0x0, 0x0)
    /usr/local/go/src/net/http/transport.go:311 +0x7e9
net/http.send(0xc820156460, 0x7fd5d08125f8, 0xc8200c2000, 0xecf193e6d, 0x2eafbf9, 0x10d6e60, 0xc82011bc60, 0x0, 0x0)
    /usr/local/go/src/net/http/client.go:260 +0x6b7
net/http.(*Client).send(0xc82011d8f0, 0xc820156460, 0xecf193e6d, 0x2eafbf9, 0x10d6e60, 0xc820154580, 0x0, 0x0)
    /usr/local/go/src/net/http/client.go:155 +0x185
net/http.(*Client).doFollowingRedirects(0xc82011d8f0, 0xc820156460, 0xc85f00, 0x0, 0x0, 0x0)
    /usr/local/go/src/net/http/client.go:475 +0x8a4
net/http.(*Client).Do(0xc82011d8f0, 0xc820156460, 0x14, 0x0, 0x0)
    /usr/local/go/src/net/http/client.go:188 +0xff
github.com/rancher/go-machine-service/vendor/github.com/rancher/go-rancher/client.setupRancherBaseClient(0xc820149000, 0xc820124f40, 0x0, 0x0)
    /go/src/github.com/rancher/go-machine-service/vendor/github.com/rancher/go-rancher/client/common.go:152 +0x8b9
github.com/rancher/go-machine-service/vendor/github.com/rancher/go-rancher/client.NewRancherClient(0xc820124f40, 0xc820124f40, 0x0, 0x0)
    /go/src/github.com/rancher/go-machine-service/vendor/github.com/rancher/go-rancher/client/generated_client.go:274 +0x4b
github.com/rancher/go-machine-service/events.NewEventRouter(0xbbfd80, 0x10, 0x7d0, 0xc82001003b, 0x18, 0xc820010222, 0x14, 0xc820016012, 0x28, 0x0, ...)
    /go/src/github.com/rancher/go-machine-service/events/listener.go:235 +0xe7
main.main.func2(0xc82001003b, 0x18, 0xc820010222, 0x14, 0xc820016012, 0x28, 0xc82015a7e0, 0xc8201385a0)
    /go/src/github.com/rancher/go-machine-service/main.go:57 +0x277
created by main.main
    /go/src/github.com/rancher/go-machine-service/main.go:62 +0x333

goroutine 22 [chan receive]:
main.main.func3(0xc82015a7e0)
    /go/src/github.com/rancher/go-machine-service/main.go:66 +0x64
created by main.main
    /go/src/github.com/rancher/go-machine-service/main.go:72 +0x355

goroutine 24 [select]:
net/http.setRequestCancel.func4(0x0, 0xc82011d3b0, 0xc820124d00, 0xc820138780)
    /usr/local/go/src/net/http/client.go:333 +0x12e
created by net/http.setRequestCancel
    /usr/local/go/src/net/http/client.go:341 +0x2f7

goroutine 10 [select]:
net/http.setRequestCancel.func4(0x0, 0xc820116300, 0xc820017e00, 0xc820012b40)
    /usr/local/go/src/net/http/client.go:333 +0x12e
created by net/http.setRequestCancel
    /usr/local/go/src/net/http/client.go:341 +0x2f7

goroutine 27 [select]:
net/http.setRequestCancel.func4(0x0, 0xc82011d950, 0xc820125000, 0xc820138d80)
    /usr/local/go/src/net/http/client.go:333 +0x12e
created by net/http.setRequestCancel
    /usr/local/go/src/net/http/client.go:341 +0x2f7

goroutine 8 [select]:
net/http.(*persistConn).readLoop(0xc820129c70)
    /usr/local/go/src/net/http/transport.go:1182 +0xd52
created by net/http.(*Transport).dialConn
    /usr/local/go/src/net/http/transport.go:857 +0x10a6

goroutine 30 [select]:
net/http.setRequestCancel.func4(0x0, 0xc82011db30, 0xc8201252c0, 0xc820139320)
    /usr/local/go/src/net/http/client.go:333 +0x12e
created by net/http.setRequestCancel
    /usr/local/go/src/net/http/client.go:341 +0x2f7

goroutine 6 [select]:
net/http.(*persistConn).readLoop(0xc82016a000)
    /usr/local/go/src/net/http/transport.go:1182 +0xd52
created by net/http.(*Transport).dialConn
    /usr/local/go/src/net/http/transport.go:857 +0x10a6

goroutine 7 [select]:
net/http.(*persistConn).writeLoop(0xc82016a000)
    /usr/local/go/src/net/http/transport.go:1277 +0x472
created by net/http.(*Transport).dialConn
    /usr/local/go/src/net/http/transport.go:858 +0x10cb

goroutine 9 [select]:
net/http.(*persistConn).writeLoop(0xc820129c70)
    /usr/local/go/src/net/http/transport.go:1277 +0x472
created by net/http.(*Transport).dialConn
    /usr/local/go/src/net/http/transport.go:858 +0x10cb

goroutine 11 [select]:
net.lookupIPDeadline(0xc8200bb547, 0x9, 0xecf193e6d, 0x2eb5a67, 0x10d6e60, 0x0, 0x0, 0x0, 0x0, 0x0)
    /usr/local/go/src/net/lookup.go:109 +0x6a6
net.internetAddrList(0xb47f20, 0x3, 0xc8200bb547, 0xe, 0xecf193e6d, 0x2eb5a67, 0x10d6e60, 0x0, 0x0, 0x0, ...)
    /usr/local/go/src/net/ipsock.go:252 +0x6ee
net.resolveAddrList(0xb43f90, 0x4, 0xb47f20, 0x3, 0xc8200bb547, 0xe, 0xecf193e6d, 0x2eb5a67, 0x10d6e60, 0x0, ...)
    /usr/local/go/src/net/dial.go:158 +0x466
net.(*Dialer).Dial(0xc820018550, 0xb47f20, 0x3, 0xc8200bb547, 0xe, 0x0, 0x0, 0x0, 0x0)
    /usr/local/go/src/net/dial.go:216 +0x124
net.(*Dialer).Dial-fm(0xb47f20, 0x3, 0xc8200bb547, 0xe, 0x0, 0x0, 0x0, 0x0)
    /usr/local/go/src/net/http/transport.go:38 +0x6e
net/http.(*Transport).dial(0xc8200c2000, 0xb47f20, 0x3, 0xc8200bb547, 0xe, 0x0, 0x0, 0x0, 0x0)
    /usr/local/go/src/net/http/transport.go:659 +0x96
net/http.(*Transport).dialConn(0xc8200c2000, 0x0, 0xc8200bb540, 0x4, 0xc8200bb547, 0xe, 0xc820138f60, 0x0, 0x0)
    /usr/local/go/src/net/http/transport.go:762 +0x1e3d
net/http.(*Transport).getConn.func4(0xc8200c2000, 0x0, 0xc8200bb540, 0x4, 0xc8200bb547, 0xe, 0xc820012c00)
    /usr/local/go/src/net/http/transport.go:706 +0x66
created by net/http.(*Transport).getConn
    /usr/local/go/src/net/http/transport.go:708 +0x262

goroutine 31 [select]:
net.lookupIPDeadline(0xc82011bba7, 0x9, 0xecf193e6d, 0x2eb6882, 0x10d6e60, 0x0, 0x0, 0x0, 0x0, 0x0)
    /usr/local/go/src/net/lookup.go:109 +0x6a6
net.internetAddrList(0xb47f20, 0x3, 0xc82011bba7, 0xe, 0xecf193e6d, 0x2eb6882, 0x10d6e60, 0x0, 0x0, 0x0, ...)
    /usr/local/go/src/net/ipsock.go:252 +0x6ee
net.resolveAddrList(0xb43f90, 0x4, 0xb47f20, 0x3, 0xc82011bba7, 0xe, 0xecf193e6d, 0x2eb6882, 0x10d6e60, 0x0, ...)
    /usr/local/go/src/net/dial.go:158 +0x466
net.(*Dialer).Dial(0xc820018550, 0xb47f20, 0x3, 0xc82011bba7, 0xe, 0x0, 0x0, 0x0, 0x0)
    /usr/local/go/src/net/dial.go:216 +0x124
net.(*Dialer).Dial-fm(0xb47f20, 0x3, 0xc82011bba7, 0xe, 0x0, 0x0, 0x0, 0x0)
    /usr/local/go/src/net/http/transport.go:38 +0x6e
net/http.(*Transport).dial(0xc8200c2000, 0xb47f20, 0x3, 0xc82011bba7, 0xe, 0x0, 0x0, 0x0, 0x0)
    /usr/local/go/src/net/http/transport.go:659 +0x96
net/http.(*Transport).dialConn(0xc8200c2000, 0x0, 0xc82011bba0, 0x4, 0xc82011bba7, 0xe, 0x0, 0x0, 0x0)
    /usr/local/go/src/net/http/transport.go:762 +0x1e3d
net/http.(*Transport).getConn.func4(0xc8200c2000, 0x0, 0xc82011bba0, 0x4, 0xc82011bba7, 0xe, 0xc8201393e0)
    /usr/local/go/src/net/http/transport.go:706 +0x66
created by net/http.(*Transport).getConn
    /usr/local/go/src/net/http/transport.go:708 +0x262
time="2016-07-14T08:03:29Z" level=info msg="Setting log level" logLevel=info 
time="2016-07-14T08:03:29Z" level=info msg="Starting go-machine-service..." gitcommit=v0.31.6 
```

**Comment by amachowi** [comment] 2016-07-16 06:58
Same issue here with RHEL7 VM running on VirtualBox 5.0, Docker 1.10.3, Rancher 1.1.0, dm.thinpooldev storage option, both internal and external Mysql (tried both). Fresh install.

**Comment by deniseschannon** [comment] 2016-07-21 15:53
@kaos @amachowi Does Rancher end up starting up okay and machine drivers work fine?

**Comment by kaos** [comment] 2016-07-21 18:33
Yes, I don't see any issues besides the logs.

**Comment by amachowi** [comment] 2016-07-22 06:40
Thank you. Works perfectly for me as well.

**Comment by kaos** [comment] 2016-07-22 09:03
Oh, I'm not sure I use the machine drivers stuff...  (which part is that, btw, just to be clear?)
And the loggs tend to fill our disks if we don't wipe the logs once in a while.. :P

**Comment by kaos** [comment] 2016-07-27 14:45
Ah, not sure what the machine drivers should look like.. but I found this new page under the admin section:
![image](https://cloud.githubusercontent.com/assets/72965/17179431/7d37bfc2-5419-11e6-8c92-3ff6a8359ade.png)

**Comment by kaos** [comment] 2016-07-27 14:46
The packet driver was Activating... so I tried to deactivate it... but it is still "Deactivating..."

**Comment by balzaczyy** [comment] 2016-08-05 06:57
I see the same issue and it fill up all the logs which make normal debug difficult. And the machine driver is not working correctly. Only packet and generic works. Other drivers are not shown, 404 for their config request when I open the web console. If I deactivate them all, they will be automatically re-enabled later.

It's quite annoying. Please take a look at this one.

**Comment by kaos** [comment] 2016-09-10 05:57
Restarts make no difference on our site at least..

**Comment by deniseschannon** [comment] 2016-11-15 19:18
@kaos  Have you seen this with v1.2.0-pre versions? I don't believe this happens anymore. If you see it, please re-open if it happens with any of the 1.2.0-pre versions.

**Comment by kaos** [comment] 2016-11-21 11:35
@deniseschannon thanks. Will keep an eye out for it. We haven't tested any of the pre 1.2 versions yet.. There's less and less bleeding edge here as we use rancher for more stuff, the stability becomes a factor, so I'd have to setup another lab environment to try it out (which I ought to do, time permitting).

**Comment by cjellick** [comment] 2016-11-22 18:01
Might be because we need to force the net package to recompile by adding the `-a` option to the go build.

**Comment by cjellick** [comment] 2016-11-22 18:04
Reclosing as dupe of https://github.com/rancher/rancher/issues/6111

**Closed by cjellick** 2016-11-22 18:04 UTC
Labels: area/machine, kind/bug
