### ISSUE TITLE
Pipeline execution does not display execution log

### ISSUE THREAD

**Issue by bmdepesa** [rancher/rancher#13448] opened 2018-05-11 22:47 UTC
**Rancher versions:**
rancher/rancher:master 5/11

**Steps to Reproduce:**
Create a cluster
Setup pipeline at cluster level
Add pipeline to project
Execute pipeline via run-once

**Results:**
Execution log does not display in the provided area. 

<img width="1281" alt="screen shot 2018-05-11 at 3 47 06 pm" src="https://user-images.githubusercontent.com/21316915/39949883-9813eb24-5532-11e8-8baf-b9e64c207072.png">

**Comment by gitlawr** [comment] 2018-05-12 15:30
I see this in the console when this happens:
![image](https://user-images.githubusercontent.com/5697937/39958881-eb93b522-563b-11e8-8002-a2b242f11287.png)
After a refresh in the browser the log shows up.

Also, the `Step Status` looks wierd. Color is missing(used to be green on success) and an empty box replaces original icon(a tick on success)

**Comment by biblesyme** [comment] 2018-05-18 08:12
@bmdepesa I can't reproduce it. Could you please take a screenshot of the `console` when you encounter it?

**Comment by gitlawr** [comment] 2018-08-30 13:44
Close the issue due to the refactor changes. Now we show `log unavailable` if it fails to get the logs in cases such as data lost in minio store.

**Closed by gitlawr** 2018-08-30 13:44 UTC
Labels: area/pipeline, kind/bug, version/2.0
