### ISSUE TITLE
[BUG] resource.start event in websockets does not include namespace parameter

### ISSUE THREAD

**Issue by Sean-McQ** [rancher/rancher#40196] opened 2023-01-18 17:17 UTC
**Rancher Server Setup**
- Rancher version: 2.7.0

**User Information**
- What is the role of the user logged in? (Admin/Cluster Owner/Cluster Member/Project Owner/Project Member/Custom) Cluster Admin

**Describe the bug**
blocks [rancher/dashboard#7919](https://github.com/rancher/dashboard/issues/7919)
when a message is sent to subscribe to a collection with additional parameters such as:
* namespace
* selector
* id

in addition to the required resourceType then the response message should include those parameters so the client application can verify what it is watching.

**To Reproduce**
subscribe to resource via steve websocket using the following message: 
`{resourceType: "apps.deployment", namespace: "default", resourceVersion: "695354"}`

**Result**
receive response message of:
`{name: "resource.start", resourceType: "apps.deployment", data: {type: "subscribe", links: {}}}`

**Expected Result**
when a message is sent to subscribe to a collection with additional parameters such as:
* namespace
* selector
* id

in addition to the resourceType then the response message should include those parameters like:
`{name: "resource.start", resourceType: "apps.deployment", namespace: "default", data: {type: "subscribe", links: {}}}`

with selector and id having similar placement for their respective keys in the response object.

**Comment by cmurphy** [comment] 2023-01-26 16:48
QA template:

## Issue: https://github.com/rancher/rancher/issues/40196
 
## Problem

 When a watch was started for a namespace, the namespace wasn't being included in the returned start event over the websocket, making it hard to verify that the watch was correctly started even though it was correct in the backend.

## Solution

Include the namespace in the start event.
 
## Testing


## Engineering Testing
### Manual Testing

Used websocat to start a watch and verify the result:

```
$ websocat -k wss://127.0.0.1:9443/v1/subscribe?sockId=1
🔼 {"resourceType": "pods", "namespace": "default"}
🔽 {"name":"resource.start","namespace":"default","resourceType":"pods","data":{"type":"subscribe","links":{}}}
```

### Automated Testing

Unit tests added in the apiserver change: https://github.com/rancher/apiserver/pull/20

## QA Testing Considerations

 
### Regressions Considerations

This change is very minimal, no regressions likely.

**Comment by dasarinaidu** [comment] 2023-01-26 23:42
I validated this issue on `v2.7-ceba69d1f9ed4c4ad78f5134e17eb0b6d1f7f59a-head` - This issue is fixed and  I am closing this ticket.

**Test Execution Details:
Test Steps :**

1. Provision rancher (Docker) 2.7-head
2. Local cluster ->Download the kubeconfig file
3. export the kubeconfig file
4. Run the command : `websocat -H="Authorization: Bearer token-aaaaa" -k wss://{host}}/v1/subscribe\?\sockId=1`

Interact with cli by passing the values with different NameSpaces as below and get output : 

Namespace : default
```
{"resourceType": "pods", "namespace": "default"}
{"name":"resource.start","namespace":"default","resourceType":"pods","data":{"type":"subscribe","links":{}}}
```

Namespace : system
```
{"resourceType": "pods", "namespace": "system"}
{"name":"resource.start","namespace":"system","resourceType":"pods","data":{"type":"subscribe","links":{}}}
```


Namespace : user created name space
```
{"resourceType": "pods", "namespace": "dans1"}
{"name":"resource.start","namespace":"dans1","resourceType":"pods","data":{"type":"subscribe","links":{}}}
```

Project: User created project
```
{"resourceType": "pods", "namespace": "dastestprj2"}
{"name":"resource.start","namespace":"dastestprj2","resourceType":"pods","data":{"type":"subscribe","links":{}}}
```


Namespace : default with a resourceVersion number
```
{"resourceType": "apps.deployment", "namespace": "default", "resourceVersion": "695354"}
{"name":"resource.start","namespace":"default","resourceType":"apps.deployment","data":{"type":"subscribe","links":{}}}
```


NO Namespace with a resourceVersion number
```
{"resourceType": "apps.deployment", "resourceVersion": "695354"}
{"name":"resource.start","resourceType":"apps.deployment","data":{"type":"subscribe","links":{}}}
```

**Closed by dasarinaidu** 2023-01-26 23:42 UTC
Labels: kind/bug, [zube]: QA Working, team/area1

**Comment by cmurphy** [comment] 2023-04-06 19:36
No release note since this is being consumed by UI and not directly user-facing.
