### ISSUE TITLE
Stack never finished Activating if created using YLM files and showing code in Status/Title bar

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#2924] opened 2015-12-04 21:32 UTC
Version - Master 11/03

Steps:
1.  Create a Stack with a External Service
2.  Export the config
3.  Create a new stack and use the exported yml files

Results:  The stack and all the services are created, but the stack itself never finishes and stays in "Activating" state.   There also seems to be some sort of 
![image](https://cloud.githubusercontent.com/assets/11514927/11601337/a9793b36-9a8f-11e5-80cd-8ad780a34f82.png)

Expected: Should finish and shouldn't show code.

**Comment by deniseschannon** [comment] 2015-12-04 21:40
Duplicate of https://github.com/rancher/rancher/issues/2906 as both are calling rancher-compose to create services.

**Closed by deniseschannon** 2015-12-04 21:40 UTC
Labels: area/service, area/ui, kind/bug
