### ISSUE TITLE
Missing the vSphere CSI Snapshotter sidecar - blockSnapshots will never work

### ISSUE THREAD

**Issue by braunsonm** [rancher/rancher#41321] opened 2023-04-27 19:24 UTC
**vSphere Server Info**
- vSphere version: 7.0.3

**Rancher Server Setup**
- Rancher version: 2.7.3

**Information about the Cluster**
- Kubernetes version: 1.25.7 RKE2

**Describe the bug**
RKE2 has added the snapshot controllers and vSphere CSI supports VolumeSnapshots. In fact, this chart added a feature flag to add support [here](https://github.com/rancher/vsphere-charts/blob/main/charts/rancher-vsphere-csi/values.yaml#L75) however it seems like it was forgotten that the CSI Snapshotter sidecar is required, as per VMware's installation instructions: https://raw.githubusercontent.com/kubernetes-sigs/vsphere-csi-driver/v2.4.0/manifests/vanilla/deploy-csi-snapshot-components.sh

Notice they apply the following patch:
```sh
# Update the vSphere CSI driver to add the snapshot side car.
tmpdir=$(mktemp -d)
echo "creating patch file in tmpdir ${tmpdir}"
cat <<EOF >> "${tmpdir}"/patch.yaml
spec:
  template:
    spec:
      containers:
        - name: csi-snapshotter
          image: 'k8s.gcr.io/sig-storage/csi-snapshotter:${release}'
          args:
            - '--v=4'
            - '--timeout=300s'
            - '--csi-address=\$(ADDRESS)'
            - '--leader-election'
          env:
            - name: ADDRESS
              value: /csi/csi.sock
          volumeMounts:
            - mountPath: /csi
              name: socket-dir
EOF

echo -e "Patching vSphere CSI driver.."
kubectl patch deployment vsphere-csi-controller -n vmware-system-csi --patch "$(cat "${tmpdir}"/patch.yaml)"
echo -e "✅ Successfully patched vSphere CSI driver, please wait till deployment is updated.."
echo -e "\n✅ Successfully deployed all components for CSI Snapshot feature.\n"
```

**To Reproduce**
Create a VolumeSnapshotDriver and a VolumeSnapshot with `blockSnapshots` enabled. You will notice that the snapshot will never complete.

**Expected Result**
The snapshot should complete and the CSI Snapshotter should be added as a sidecar

SURE-7177

**Comment by a-blender** [comment] 2023-10-30 23:33
This bug fix will also need to be backported to the vSphere charts for the next Rancher 2.7.x release.

**Comment by a-blender** [comment] 2023-11-23 06:33
@braunsonm Hello!

I  was unable to reproduce this issue.

We do have the csi-snapshotter versions required to create a snapshot packaged in the CSI chart https://github.com/rancher/image-mirror/blob/7a302ecb3ee8740db74de5129e228bf377331b87/images-list#L1396-L1398 and _creating a snapshot does work_ on the latest Rancher 2.7, but it's a lot of manual labor. I had to deploy the additional snapshot components myself, create a PVC, a snapshotStorageClass and a volumeSnapshot.

**Repro steps / workaround**

To create a snapshot
* Deploy an RKE cluster with `cloud-provider=vsphere`
* Configure the vSphere host / datacenter / cloud credentials in the Addon Config tab (same as what would be in your helm install values.yaml)
* Add the following in the Addon Config tab

```
blockVolumeSnapshot:
  enabled: true
```

* Create the cluster
* Add the additional snapshot components

```
./deploy-csi-snapshot-components.sh --kubeconfig <kubeconfig>
```

Follow the VMware docs https://docs.vmware.com/en/VMware-vSphere-Container-Storage-Plug-in/3.0/vmware-vsphere-csp-getting-started/GUID-E0B41C69-7EEB-450F-A73D-5FD2FF39E891.html to create a PVC, VolumeStorageClass, and VolumeSnapshot.

You can create a default PVC using the storage class Rancher created for you via the UI if you want. I deployed my VolumeStorageClass and VolumeSnapshot via kubectl. All these should complete successfully.

I agree that the CSI snapshotted sidecar logic should be packaged into the chart and this process more automated so customers don't get frustrated.

**Notes**

For an RKE2 cluster, this contributor is correct https://github.com/rancher/vsphere-charts/issues/50#issuecomment-1600705099. When auto installing the vSphere charts via setting `cloud-provider=vsphere` during provisioning, Rancher creates a StorageClass for you by default

<img width="975" alt="image" src="https://github.com/rancher/rancher/assets/12955547/e6bf225d-f9dd-4666-9484-2ecc63ac9706">

<img width="1009" alt="image" src="https://github.com/rancher/rancher/assets/12955547/d8a510ec-8e09-4037-b1fd-74025b2bc0d0">

but not a VolumeStorageClass. You must deploy this yourself right now to create a snapshot.

**Comment by a-blender** [comment] 2023-11-23 06:41
**Notes**

For an RKE2 cluster, this contributor is correct https://github.com/rancher/vsphere-charts/issues/50#issuecomment-1600705099. When auto installing the vSphere charts via setting `cloud-provider=vsphere` during provisioning, Rancher creates a StorageClass for you by default

<img width="975" alt="image" src="https://github.com/rancher/rancher/assets/12955547/e6bf225d-f9dd-4666-9484-2ecc63ac9706">

<img width="1009" alt="image" src="https://github.com/rancher/rancher/assets/12955547/d8a510ec-8e09-4037-b1fd-74025b2bc0d0">

but not a VolumeStorageClass. You must deploy this yourself right now to create a snapshot.

**Comment by braunsonm** [comment] 2023-11-23 13:02
@a-blender I think the point of this issue is for the snapshotter to be included with the vSphere chart. I'm not doubting it can be done when the snapshotter is deployed.

**Comment by a-blender** [comment] 2023-11-23 17:51
@braunsonm Oh, based on the repro steps I thought you were having an issue with a snapshot getting stuck _after_ you deployed the snapshotted components manually. This is expected behavior then and will be logged as an enhancement for Rancher 2.8.x.

**Comment by horihel** [comment] 2024-02-08 07:52
I've dug into possible workarounds a bit and I doubt that running `deploy-csi-snapshot-components.sh` from vmware is safe on RKE2.
The script (i've looked at the one tagged from 3.0.2) looks for a deployment `snapshot-controller` and installs it if missing, but rke2 already has the snapshot-controller (called `rke2-snapshot-controller`).
This might result in two snapshot controllers getting installed (and 2 validation webhooks too).
I did not yet run this against a test cluster, i just read the script.

So in fact only the patch part of the script is needed. And you still need to carefully check if a cluster upgrade does not remove the new sidecar (helms 3-way merge _should_ leave it though) or leave it on a non-matching version.

**Comment by susesgartner** [comment] 2024-04-15 16:51
Tested this fix on RKE2 and it works as intended however a chart update is required for the fix to be observed on RKE2. Moving this to blocked while waiting for the default CSI chart to be updated on the RKE2 side.

**Comment by markusewalker** [comment] 2024-05-02 19:11
Validated this against `v2.9-head` https://github.com/rancher/rancher/commit/98d8b8975948ce5929e38e8603950ceb223349de See details below:

**ENVIRONMENT DETAILS**
- Rancher install: Docker
- Rancher version: `v2.9-head` https://github.com/rancher/rancher/commit/98d8b8975948ce5929e38e8603950ceb223349de

**TEST RESULT**
|#|Scenario|Test Case|Result
|---|---|---|---|
|1|Add snapshotter sidecar to CSI chart w/`blockSnapshots` enabled|Provision RKE2 downstream node driver cluster,  install vSphere CSI chart with `blockSnapshots` enabled, install CSI snapshot components|:white_check_mark:|
|2|Upgrade CSI chart w/`blockSnapshots` already enabled|Provision RKE2 downstream node driver cluster,  install second highest vSphere CSI chart with `blockSnapshots` enabled, install CSI snapshot components, upgrade vSphere CSI chart to latest|:white_check_mark:

**VALIDATION STEPS**

**Scenario 1**
1. As a standard user, provisioned a downstream RKE2 `v1.28.9+rke2r1` node driver cluster (1 etcd, 1 cp, 1 worker).
2. Installed vSphere CSI chart (`104.0.0+up3.1.2-rancher4`) and ensured that `blockSnapshots` is enabled.
3. On a client machine with the cluster's kubeconfig, ran this [script](https://raw.githubusercontent.com/kubernetes-sigs/vsphere-csi-driver/v2.4.0/manifests/vanilla/deploy-csi-snapshot-components.sh).
4. Validated the script was successful and that deployment `vsphere-csi-controller` has `csi-snapshotter` as a sidecar.

________

**Scenario 2**
1. Repeated scenario 1, but installed vSphere CSI chart version `103.1.0+up3.1.2-rancher1`.
2. Upgraded chart version to latest version `104.0.0+up3.1.2-rancher4`; this was successful.
3. Validated that the deployment `vsphere-csi-controller` is still `Active`.

**Closed by markusewalker** 2024-05-02 19:11 UTC
Labels: kind/bug, internal, area/vsphere, [zube]: Next Up, QA/S, feature/charts-vsphere, team/hostbusters
