### ISSUE TITLE
UI - Catalog apps page extremely slow to load for large clusters

### ISSUE THREAD

**Issue by tylerstapler-wf** [rancher/rancher#17101] opened 2018-12-14 05:37 UTC
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
Create a cluster with a large amount of Catalog Apps. These catalog apps should have some large answers (like base64 encoded x509 certificates). In our case we have 90+ catalog apps. To recreate the configmap portion. Deploy a large number of versions of each catalog app (over a hundred in some cases).

**Result:**
Our Catalog Apps page takes over twenty seconds to load. The UI is not doing any sort of pagination or lazy loading of the data.

<img width="1433" alt="screen shot 2018-12-13 at 11 24 47 pm" src="https://user-images.githubusercontent.com/19389666/49984762-0a878700-ff2f-11e8-90d4-59a286d7aea6.png">

It also looks like the UI is loading the templates for every revision of every app.
<img width="1312" alt="screen shot 2018-12-13 at 11 25 20 pm" src="https://user-images.githubusercontent.com/19389666/49984769-14a98580-ff2f-11e8-8425-d944847c3cf8.png">

<img width="1233" alt="screen shot 2018-12-13 at 11 26 15 pm" src="https://user-images.githubusercontent.com/19389666/49984811-399df880-ff2f-11e8-8114-2453309a2363.png">

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): v2.1.1
- Installation option (single install/HA): HA

**Comment by vincent99** [comment] 2018-12-14 07:48
The entire UI is live-updating, which requires knowing about all the resources in advance.  There is pagination at both the API request level on everything and display on most things, but both are higher than 90, which is not a lot of anything.

None of this is relevant if it takes 30 seconds for the list of apps to be returned from the API.  Something is very wrong with networking it resource utilization there, and the UI can't display data that isn't coming back.

**Comment by int-tt** [comment] 2019-01-22 17:46
I have the same problem.
We are carrying out GitOps in the current project and deploying to development environment via rancher every time it is pushed to master branch.
In rancher, I think that the helm template of each Revision is held in the configmap which `gzip + base64` did, but in my cluster about 300 is exceeded, the total size of confgfigmap becomes close to 100 MB.

As a result also long time and many resources are consumed when displaying Cluster's page as well.

![image 2](https://user-images.githubusercontent.com/3135165/51554342-6a6f3700-1eb8-11e9-815d-4e5a81e1a46c.png)
![image 1](https://user-images.githubusercontent.com/3135165/51554347-6d6a2780-1eb8-11e9-9bc8-c505eac57ee5.png)

This problem has several elements overlapping and I have not got a good solution yet :(

**Comment by ekristen** [comment] 2019-03-05 23:08
This is a pretty nasty bug / problem. I've hit it with only a couple of catalogs deployed due to a bug with helm/tiller and rancher trying to upgrade an ingress rule and failing. It brought my configmaps up to 22k and the Rancher UI is not 100% unusable.

**Comment by deniseschannon** [comment] 2019-04-15 17:25
The app loading will be fixed in 2.2.2, but the cleaning up of config maps will be fixed in 2.2.3.

**Comment by bmdepesa** [comment] 2019-05-03 20:39
rancher/rancher:master 03c40d64

* Reproduced in v2.2.2
* Deploy rancher:master
* Followed steps to reproduce
* Verified only one configmap being created
* Automated test tests/validation/tests/v3_api/test_app.py:test_tiller passing
* UI & Cluster remain stable

**Closed by bmdepesa** 2019-05-03 20:39 UTC
Labels: area/catalog, internal, kind/bug, status/resolved, status/to-test, status/triaged, status/working, team/az

**Comment by laloyalo** [comment] 2020-08-06 19:16
Hello, Rancher team.

We've been experiencing an unusable Apps page, loading up to 100 Mbs of data (actually  ~20Mb transferred). We have a large cluster with ~1200 applications installed. Is there any procedure that had to take place once we migrated from 2.2.3? We are now running Rancher v2.4.5 and this issue still persists. We believe the applications screen needs some sort of pagination or at least virtual scrolling.
See the attached screenshot for an example of data being transferred and loaded.

What should we check to make sure our setup is not missing any configuration to prevent all of the data from being loaded. I understand the statement regarding live updating everything, but this is just not scalable so far.

We are running Rancher in GKE in n1-standard-4 machines with up to 13GB of allocatable memory.

Thanks!

<img width="2241" alt="Screen Shot 2020-08-06 at 14 09 39" src="https://user-images.githubusercontent.com/59898032/89572494-c83f4780-d7ee-11ea-9803-1a1ea18ea6cf.png">

**Comment by vincent99** [comment] 2020-08-06 19:40
This issue was related to keeping an unbounded number of revisions (as configmaps) for every app, which eventually added up to a lot of copies if they changed frequently.  They are cleaned up after the next upgrade.  But the long pole of the time in your screenshot is loading pods, not apps.

The response time there is terrible, but should be largely bound by the k8s control plane response since it's just being lightly modified and passed through.

We [only support](https://rancher.com/docs/rancher/v2.x/en/installation/k8s-install/#important-notes-on-architecture) running Rancher on a RKE or K3s cluster, because with something like a hosted GKE cluster you have no visibility into, or control of, the performance/configuration/backup/restore of the underlying control plane.
