### ISSUE TITLE
[RFE] [rancher-machine] [vSphere] Rewind or save changes when error is encountered

### ISSUE THREAD

**Issue by Oats87** [rancher/rancher#46340] opened 2024-07-25 18:49 UTC
**Is your feature request related to a problem? Please describe.**
In cases where `rancher-machine` is unable to fully perform provisioning of a machine, it can orphan resources which is not ideal. We have specifically observed this behavior with the VMware vSphere driver, for example in cases where the machine being created is unable to be started. 

**Describe the solution you'd like**
I see two logical solutions to this issue.
1. Save the current state to the state store so that a subsequent `rm` properly cleans up the resources
2. Rewind the changes that were performed when an error is encountered

**Describe alternatives you've considered**

**Additional context**

In my testing, I noticed that if machine encounters an error during creation, it keeps track of the machine at a high level but does not store any relevant information from the driver. This means on a subsequent `rm`, the resources are not actually destroyed, hence leading to orphaned resources.

**Comment by snasovich** [comment] 2024-08-29 21:47
Closing this as duplicate of https://github.com/rancher/rancher/issues/44212 that was fixed and validated in 2.9.1.

**Closed by snasovich** 2024-08-29 21:47 UTC
Labels: kind/enhancement, area/machine, area/vsphere
