### ISSUE TITLE
When adding multiple custom roles, users created with no associated binding userId under v3/clusterRoleTemplateBindings/id

### ISSUE THREAD

**Issue by carolynhu** [rancher/rancher#14853] opened 2018-07-30 21:39 UTC
**Rancher versions:**
rancher/server or rancher/rancher: v2.0.6

**Steps to Reproduce:**
1. Enable AD auth
2. Add cluster and add member (`testuser1` and `testuser2`) with custom roles (select multiple roles)
3. save settings
<img width="1267" alt="screen shot 2018-07-30 at 11 35 10 am" src="https://user-images.githubusercontent.com/29208297/43424580-c88ee78e-9404-11e8-806a-f61ee0bd72f9.png">

**Results:**
Both `testuser1` and `testuser2` are created. Only `testuser1` has `userId`, `userId` for `testuser2` is `null`
Here is what showing in API for `testuser1`:
https://xxxx/v3/clusterRoleTemplateBindings/c-pgtt5:crtb-pbtf2
```
{
"actions": { },
"annotations": {
"auth.cattle.io/principal-display-name": "testuser1",
"lifecycle.cattle.io/create.cluster-crtb-sync_c-pgtt5": "true",
"lifecycle.cattle.io/create.mgmt-auth-crtb-controller": "true"
},
"baseType": "clusterRoleTemplateBinding",
"clusterId": "c-pgtt5",
"created": "2018-07-30T18:32:49Z",
"createdTS": 1532975569000,
"creatorId": "user-9grr5",
"groupId": null,
"groupPrincipalId": null,
"id": "c-pgtt5:crtb-pbtf2",
"links": {
"remove": "…/v3/clusterRoleTemplateBindings/c-pgtt5:crtb-pbtf2",
"self": "…/v3/clusterRoleTemplateBindings/c-pgtt5:crtb-pbtf2",
"update": "…/v3/clusterRoleTemplateBindings/c-pgtt5:crtb-pbtf2"
},
"name": "crtb-pbtf2",
"namespaceId": null,
"roleTemplateId": "projects-create",
"type": "clusterRoleTemplateBinding",
"userId": "user-bsrmv",
"userPrincipalId": "activedirectory_user://CN=testuser1,CN=Users,DC=testad,DC=rancher,DC=io",
"uuid": "f648a01b-9426-11e8-aff7-0242ac110002"
}
```
Here is what showing in API for `testuser2`:
https://xxxx/v3/clusterRoleTemplateBindings/c-pgtt5:crtb-2q6tm
```
{
"actions": { },
"annotations": {
"auth.cattle.io/principal-display-name": "testuser2",
"lifecycle.cattle.io/create.cluster-crtb-sync_c-pgtt5": "true"
},
"baseType": "clusterRoleTemplateBinding",
"clusterId": "c-pgtt5",
"created": "2018-07-30T18:33:07Z",
"createdTS": 1532975587000,
"creatorId": "user-9grr5",
"groupId": null,
"groupPrincipalId": null,
"id": "c-pgtt5:crtb-2q6tm",
"links": {
"remove": "…/v3/clusterRoleTemplateBindings/c-pgtt5:crtb-2q6tm",
"self": "…/v3/clusterRoleTemplateBindings/c-pgtt5:crtb-2q6tm",
"update": "…/v3/clusterRoleTemplateBindings/c-pgtt5:crtb-2q6tm"
},
"name": "crtb-2q6tm",
"namespaceId": null,
"roleTemplateId": "projects-view",
"type": "clusterRoleTemplateBinding",
"userId": null,
"userPrincipalId": "activedirectory_user://CN=testuser2,CN=Users,DC=testad,DC=rancher,DC=io",
"uuid": "00c38faf-9427-11e8-aff7-0242ac110002"
}
```
When I checking https://xxxx/v3/users/
There are four users listed, and two for `testuser2`: 

|username    |userId       |  
|------------|--------------|
| testuser2  |  "user-49dkn" |
| testuser2  | "user-4hxn2"  |   
| Default Admin  |"user-9grr5"   |  
| testuser1 | "user-bsrmv"|

We can access info of `testuser2` through API `https://xxxx/v3/users/user-49dkn` and `https://xxxx/v3/users/user-4hxn2`. But under API `https://xxxx/v3/clusterRoleTemplateBindings/c-pgtt5:crtb-2q6tm` we cannot access `testuser2`, since there is no `userId`

**Comment by cjellick** [comment] 2018-08-03 04:31
I am closing this as a duplicate of https://github.com/rancher/rancher/issues/14822

**Closed by cjellick** 2018-08-03 04:31 UTC
Labels: area/rbac, kind/bug, priority/-1, status/blocker
