### ISSUE TITLE
Rancher section Catalog Apps is empty

### ISSUE THREAD

**Issue by harutyundermenjyan** [rancher/rancher#14579] opened 2018-07-17 10:06 UTC
**rke v0.1.8**
**rancher version is 2.0.6**
I've deployed k8s with HA External Load Balancer and noticed that section `Catalog Apps` is empty.
My `nginx` host and `worker` node are in different subnets but when they in the same subnet the `Catalog Apps` section is not empty and the content is in place.
Is the problem relating to different subnets or anything else , because I didn't find any other difference than subnet between worker nodes when the contents is in place..
Also I've tried to change the worker node, flush iptables but didn't helped.

**nginx rancher.conf**
```
cat /etc/nginx/conf.d/rancher.conf
upstream rancher {
    server MY_NODE_IP:80;
}
map $http_upgrade $connection_upgrade {
    default Upgrade;
    ''      close;
}

server {
         listen 443 default ssl http2;
         HOST AND CERT RELATED  PART.
         ..........
         ..........
    location / {
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Forwarded-Port $server_port;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_pass http://rancher;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection $connection_upgrade;
        # This allows the ability for the execute shell window to remain open for up to 15 minutes. Without this parameter, the default is 1 minute and will automatically close.
        proxy_read_timeout 900s;
    }
}

server {
    listen 80;
    server_name HERE_IS_MY_NGINX_SERVER_HOSTNAME;
    return 301 https://$server_name$request_uri;
}
```

<img width="1277" alt="screen shot 2018-07-17 at 9 39 44 pm" src="https://user-images.githubusercontent.com/16855630/42835478-f0fb8bb4-8a09-11e8-8adb-963b701b1c28.png">

**Comment by StrongMonkey** [comment] 2018-07-17 22:14
@harutyundermenjyan what does the rancher server logs looks like? Your rancher server container need to reach  `https://git.rancher.io/charts`(be able to resolve DNS..etc)

**Comment by harutyundermenjyan** [comment] 2018-07-18 07:04
yes, you are noticed right the issue is really connected to resolving from DNS
**kubectl -n cattle-system logs -f  cattle-689b77f8f6-5ttbv**
```
2018/07/18 06:50:45 [ERROR] CatalogController library [catalog] failed with : Get https://git.rancher.io/charts/index.yaml: dial tcp: lookup git.rancher.io on 10.43.0.10:53: server misbehaving
```

**Comment by superseb** [comment] 2018-07-18 07:33
What OS are you running? You can also use https://rancher.com/docs/rancher/v2.x/en/installation/troubleshooting-ha/generic-troubleshooting/ for troubleshooting the cluster.

**Comment by superseb** [comment] 2018-07-18 09:14
Usually the problem is the configured nameserver being an address that can't be resolved in a container (something in the `127.0.0.0/8` range). This needs to be resolved on the machine.

If this is not the case, can you share the container logging from the kube-dns pod to see why it can't function?

**Comment by harutyundermenjyan** [comment] 2018-07-18 09:44
yes, the cause is the `kubedns` container in `kube-dns` pod has been set `127.0.0.1` as `nameserver` address:

`kubectl -n kube-system exec -it kube-dns-5ccb66df65-5j69g -c kubedns sh`
```
/ # cat /etc/resolv.conf 
nameserver 127.0.0.1
```
But I've run docker with the following options:
```
ps -ef |grep docker
root      8629     1  5 09:15 ?        00:01:24 /usr/bin/dockerd --dns 172.16.0.1 --dns 172.16.0.2 --raw-logs
```

**Comment by superseb** [comment] 2018-07-18 11:23
That's a Docker configuration, pods use CNI. See https://kubernetes.io/docs/concepts/cluster-administration/networking/ and https://kubernetes.io/docs/concepts/services-networking/dns-pod-service/.

If you want to keep your `resolv.conf`, you can either configure the kubelet to use another resolv.conf file or configure an upstream server for kube-dns (https://kubernetes.io/docs/tasks/administer-cluster/dns-custom-nameservers/)

**Comment by harutyundermenjyan** [comment] 2018-07-19 09:15
With kubelet option it will affect to the whole cluster not only to dns deployment and will disrupt the work of other services, deployments....
Before I solved it by running docker service with the appropriate dns options as I've mentioned above but now it doesn't help.

**Comment by superseb** [comment] 2018-07-19 09:39
What is "before" exactly? It could be a regression but I need to know what version it was working.

The kubelet file will make sure the kube-dns deployment will get a proper upstream resolver (due to`      dnsPolicy: Default  # Don't use cluster DNS.`). By default, created pods will point to kube-dns which will then use upstream. This is the same upstream behavior you can create by using a ConfigMap.

The Docker DNS options don't work because the Kubernetes containers are launched with host networking, for pods this can't work due to CNI.

**Comment by harutyundermenjyan** [comment] 2018-07-19 10:02
Saying before, I mean before upgrading rancher from 1.6.x to 2.x I've solved this issue by adding docker DNS options.

**Comment by superseb** [comment] 2018-07-19 10:16
Ok, that makes sense. 1.6 is Docker based, 2.x is Kubernetes based.

The options presented can still help you out in the same way though.

**Comment by superseb** [comment] 2018-07-19 11:35
Going to close this as this is not a bug, let me know if you have any other questions.

**Closed by superseb** 2018-07-19 11:35 UTC
