### ISSUE TITLE
Rancher UI - services do not load links until refresh

### ISSUE THREAD

**Issue by nhumrich** [rancher/rancher#3351] opened 2016-01-20 20:15 UTC
If you use the rancher UI, you can click to another environment and it shows all the stacks/services. I have noticed that whenever I browse around in rancher, the links do not show up for the services until I do a hard refresh. This can cause problems with links disappearing. 
For example, I navigate to a page, go to upgrade a service. Because the links didnt load, the upgrade call to the service now removes the links. In order to prevent this, I have to hard refresh everytime I want to upgrade a service. 
This can be a fairly nasty bug as it removes links. It has bitten us in the foot a couple times.

**Comment by deniseschannon** [comment] 2016-01-20 21:11
This is most likely a duplicate of #1389 which was just closed and will be fixed in the next release.

Did you have multiple environments?

**Comment by nhumrich** [comment] 2016-01-20 21:16
Yep looks like a dupe

**Closed** 2016-01-20 21:25 UTC
