### ISSUE TITLE
Disk size doubled on host

### ISSUE THREAD

**Issue by kuzhao** [rancher/rancher#5932] opened 2016-09-09 00:52 UTC
**Rancher Version:**
1.1.3
**Docker Version:**
1.11.2
**OS and where are the hosts located? (cloud, bare metal, etc):**
RancherOS, virtual machine
**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
single node rancher, internal DB
**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle/Swarm
**Steps to Reproduce:**
1. Add in the host where rancher/server container sits
2. Wait until new host appears in "Infrastructure"->"Host" panel
**Results:** 
Disk space doubled. In my case the volume size displayed is 225GB whereas the actual size is 103.7GB
**Expected:**
Disk space displayed in rancher should be consistent with host OS.

**Comment by kuzhao** [comment] 2016-09-09 00:53
Attaching df -h on host OS RancherOS:
[rancher@docker-rancher ~]$ sudo df -h
Filesystem                Size      Used Available Use% Mounted on
overlay                 112.4G      2.6G    103.7G   2% /
tmpfs                     7.8G         0      7.8G   0% /dev
tmpfs                     7.8G         0      7.8G   0% /sys/fs/cgroup
/dev/vda1               112.4G      2.6G    103.7G   2% /opt
/dev/vda1               112.4G      2.6G    103.7G   2% /media
/dev/vda1               112.4G      2.6G    103.7G   2% /mnt
/dev/vda1               112.4G      2.6G    103.7G   2% /home
none                      7.8G    804.0K      7.8G   0% /run
/dev/vda1               112.4G      2.6G    103.7G   2% /var/log
/dev/vda1               112.4G      2.6G    103.7G   2% /usr/lib/firmware
/dev/vda1               112.4G      2.6G    103.7G   2% /usr/sbin/poweroff
devtmpfs                  7.8G         0      7.8G   0% /host/dev
shm                      64.0M         0     64.0M   0% /host/dev/shm
/dev/vda1               112.4G      2.6G    103.7G   2% /usr/sbin/halt
/dev/vda1               112.4G      2.6G    103.7G   2% /usr/sbin/shutdown
/dev/vda1               112.4G      2.6G    103.7G   2% /usr/sbin/reboot
/dev/vda1               112.4G      2.6G    103.7G   2% /usr/sbin/iptables
/dev/vda1               112.4G      2.6G    103.7G   2% /etc/selinux
none                      7.8G    804.0K      7.8G   0% /var/run
/dev/vda1               112.4G      2.6G    103.7G   2% /usr/lib/modules
/dev/vda1               112.4G      2.6G    103.7G   2% /etc/docker
/dev/vda1               112.4G      2.6G    103.7G   2% /usr/bin/user-docker
/dev/vda1               112.4G      2.6G    103.7G   2% /usr/sbin/wait-for-docker
/dev/vda1               112.4G      2.6G    103.7G   2% /usr/bin/docker-runc.dist
/dev/vda1               112.4G      2.6G    103.7G   2% /var/lib/rancher
/dev/vda1               112.4G      2.6G    103.7G   2% /usr/bin/system-docker
/dev/vda1               112.4G      2.6G    103.7G   2% /var/lib/docker
/dev/vda1               112.4G      2.6G    103.7G   2% /usr/bin/docker-containerd.dist
/dev/vda1               112.4G      2.6G    103.7G   2% /usr/bin/docker.dist
/dev/vda1               112.4G      2.6G    103.7G   2% /usr/share/ros
/dev/vda1               112.4G      2.6G    103.7G   2% /usr/bin/respawn
/dev/vda1               112.4G      2.6G    103.7G   2% /usr/bin/switch-console
/dev/vda1               112.4G      2.6G    103.7G   2% /usr/bin/dockerlaunch
/dev/vda1               112.4G      2.6G    103.7G   2% /usr/sbin/netconf
/dev/vda1               112.4G      2.6G    103.7G   2% /usr/bin/cloud-init
/dev/vda1               112.4G      2.6G    103.7G   2% /usr/bin/docker-containerd-shim.dist
/dev/vda1               112.4G      2.6G    103.7G   2% /usr/bin/ros
/dev/vda1               112.4G      2.6G    103.7G   2% /var/lib/rancher/cache
/dev/vda1               112.4G      2.6G    103.7G   2% /var/lib/rancher/conf
/dev/vda1               112.4G      2.6G    103.7G   2% /etc/ssl/certs/ca-certificates.crt.rancher
/dev/vda1               112.4G      2.6G    103.7G   2% /etc/resolv.conf
/dev/vda1               112.4G      2.6G    103.7G   2% /etc/hostname
/dev/vda1               112.4G      2.6G    103.7G   2% /etc/hosts
shm                      64.0M         0     64.0M   0% /dev/shm
devtmpfs                  7.8G         0      7.8G   0% /dev
shm                      64.0M         0     64.0M   0% /dev/shm
overlay                 112.4G      2.6G    103.7G   2% /var/lib/docker/overlay/0618fb04969b62d0e4728634451d43b9378c23838ade0e8d3005c297528a0e72/merged
overlay                 112.4G      2.6G    103.7G   2% /var/lib/docker/overlay/4dadb908e3026d42530861d159e504cd3cd439009f5a938f540b94d83731e164/merged
shm                      64.0M         0     64.0M   0% /var/lib/docker/containers/53f99db7d8f2c55e58d759a5d731db60e85b8eed9eb74a04a9cb0352d06a4652/shm
overlay                 112.4G      2.6G    103.7G   2% /var/lib/docker/overlay/f38863e6851caec037f32e04fa914db42d21fa727adbc48a6bdf7b37056648a1/merged
shm                      64.0M         0     64.0M   0% /var/lib/docker/containers/7059b172b95b9977d554546554b7656a6f57bee60f541433858b2774f5fcde56/shm
overlay                 112.4G      2.6G    103.7G   2% /var/lib/docker/overlay/69c7356908970248168fb08daac90a537a4506534b9aa55233432be4a93d9d7c/merged
shm                      64.0M         0     64.0M   0% /var/lib/docker/containers/e15db2bedbd6ef61c7b45ec1e6950b6e97324264ccc9580b057274899651ec57/shm
shm                      64.0M         0     64.0M   0% /var/lib/docker/containers/279d30f305b7800cf4914a96bffdd91ecc5b7cd520fb204026fdd17b8d4d7529/shm

**Comment by deniseschannon** [comment] 2016-09-09 03:25
Duplicate of https://github.com/rancher/rancher/issues/5566

**Closed by deniseschannon** 2016-09-09 03:25 UTC
