### ISSUE TITLE
Load Balancer: Host IP are not shown in the UI after the IP was set

### ISSUE THREAD

**Issue by marvinwankersteen** [rancher/rancher#7832] opened 2017-02-15 19:32 UTC
**Rancher Versions:**
Server: 1.4.1
healthcheck: 0.2.3
ipsec: 0.8.7
network-services: 0.4.5
scheduler: 0.6.3
kubernetes (if applicable):

**Docker Version:**
1.12.6

**OS and where are the hosts located? (cloud, bare metal, etc):**
CentOS (VM)
Ubuntu (VM)

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
Single Node with external DB as Container

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle

**Steps to Reproduce:**
- Create Loadbalancer with options you must set
- Add Service/Selector Rule
- Click "Show custom backend names. Show host IP address options." and "Show host IP address options."
- Fill in the host ip address
- Create LoadBalancer
- Wait
- Upgrade/Edit the Loadbalancer
- Click "Show custom backend names. Show host IP address options." and "Show host IP address options."

**Results:** 
- Host IP field is empty

In the stack overview the IP is shown like "10.8.0.75:1936/tcp" and the iptables are right. In the chain CATTLE_PREROUTING the IP is set as destination.

If you now edit the loadbalancer and you don't refill the Host IP, then the destination in iptables are reset to 0.0.0.0/0.

**Comment by tfiduccia** [comment] 2017-02-15 22:18
Duplicate of #7288

**Closed by tfiduccia** 2017-02-15 22:18 UTC
