### ISSUE TITLE
Rancher doesn't reflect changed IP addresses in nodes that have been restarted 

### ISSUE THREAD

**Issue by yunspace** [rancher/rancher#3456] opened 2016-01-29 03:12 UTC
I've recently upgraded to 0.56.0 and restarted my nodes. However after the restart, the AWS IP have changed:

![screen shot 2016-01-29 at 2 00 57 pm](https://cloud.githubusercontent.com/assets/218128/12666111/b172a7f4-c691-11e5-8976-99f7e87ec0a2.png)

However in Rancher, they were still showing the old IPs (I also lost my hostnames as described in #3414):

![screen shot 2016-01-29 at 1 59 45 pm](https://cloud.githubusercontent.com/assets/218128/12666116/c13de64e-c691-11e5-9f6c-71253777ec1d.png)

My Load Balancers are stuck in "Initializing" state which I suspect is related to this. I've tried the work around suggested in #3430 and restarted my network agents (from within rancher GUI) but didn't help. I will try and upgrade to 0.56.1 and see if there are any improvements.

**Comment by deniseschannon** [comment] 2016-01-29 03:54
This is a duplicate of https://github.com/rancher/rancher/issues/388.

Basically, when the host IP changes, Rancher does not detect the change and your network agent and your host IP will not be reflected.

You will need to rerun the agent command and set the CATTLE_AGENT_IP environment variable to get working again.

http://docs.rancher.com/rancher/faqs/troubleshooting//#what-do-i-do-if-the-ip-of-my-host-has-changed-due-to-reboot

**Closed by deniseschannon** 2016-01-29 03:54 UTC

**Comment by yunspace** [comment] 2016-01-29 04:29
Thanks this is worked. Will refer to the troubleshooting doc first in the future.
