### ISSUE TITLE
when scale down a service and then scale up , cause kernel wall "unregister_netdevice: waiting for eth0 to become free. Usage count = 4"

### ISSUE THREAD

**Issue by 4admin2root** [rancher/rancher#11927] opened 2018-03-04 14:17 UTC
**Rancher versions:**
rancher/server: v1.6.1
rancher/agent: v1.2.2

**Infrastructure Stack versions:**
healthcheck:v0.3.1
vxlan
network-services:v0.11.2 
scheduler:
kubernetes (if applicable):

**Docker version: (`docker version`,`docker info` preferred)**
1.12.6
**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
SUSE Linux Enterprise Server 12 SP2
4.4.59 
**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
azure
**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
single  and ha  , external db
**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle
**Steps to Reproduce:**
sometimes when scale down a service and then scale up, kernel wall "unregister_netdevice: waiting for eth0 to become free. Usage count =4"
**Results:**

I am sure the case is not same as 
https://github.com/rancher/rancher/issues/931  
https://github.com/moby/moby/issues/5618
(not only the NIC is different, but also the action of reproduce. )

I have upgraded kernel version to 4.4.114, but the kernel messages : "unregister_netdevice: waiting for eth0 to become free. Usage count = 4" was printed.

after I add a "health check" to my service, I find the frequency has increased.

**Comment by superseb** [comment] 2018-03-12 18:24
We tried to mitigate this long running Docker bug in v1.6.3: https://github.com/rancher/rancher/issues/9090

Please try this version and see if it improves.

Closing as not a bug for now, let me know if you run into anything.

**Closed by superseb** 2018-03-12 18:24 UTC

**Comment by 4admin2root** [comment] 2018-03-13 06:29
@superseb  I view the issue 9090.
```
Fixed in Network Services v0.2.2, network-manager:v0.7.2
```
but our ENV IS 
=========
Network Services version: v0.2.3 
network-manager: v0.7.4

**Comment by MaxDiOrio** [comment] 2018-11-05 21:38
Is there an update on this?  We have a worker node doing this to us now.
