### ISSUE TITLE
configmaps "rancher-charts-qfl96" not found on rancher manager dashboard v2.5.5

### ISSUE THREAD

**Issue by krishnakekan619** [rancher/rancher#33341] opened 2021-06-23 08:28 UTC
**What kind of request is this (question/bug/enhancement/feature request):**
Bug/Error
- We are facing the issue on rancher manager dashboard:
issue: configmaps "rancher-charts-qfl96" not found
we cant see the monitoring stack in marketing&apps section,
We have installed prometheus-grafana manually and we want to install monitoring stack with the rancher dashboard

**Steps to reproduce (least amount of steps as possible):**
- create aks cluster
- import aks cluster on rancher manager dashboard
- youll see the monitoring stack unavailable and above error

**Result:**
Facing above issuee: `configmaps "rancher-charts-qfl96" not found`

**Expected Result:**
- monitoring stack should be present

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI):  v 2.5.5
- Installation option (single install/HA): HA
- AKS : 1.19.3

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported):
- Machine type (cloud/VM/metal) and specifications (CPU/memory):
- Kubernetes version (use `kubectl version`):

Her in my case the monitoring stack button is missing so couldn't install monitoring stack on AKS cluster
![Screenshot from 2021-06-23 13-40-51](https://user-images.githubusercontent.com/55179037/123070043-0bb79a00-d431-11eb-9c3d-6e8c737895db.png)
and seeing the error : configmaps "rancher-charts-qfl96" not found

**Comment by cbron** [comment] 2021-08-06 18:20
Dupe of https://github.com/rancher/rancher/issues/33340

**Closed by cbron** 2021-08-06 18:20 UTC
