### ISSUE TITLE
With healthcheck enabled, host stops monitoring the container after it(host) is restarted

### ISSUE THREAD

**Issue by soumyalj** [rancher/rancher#4595] opened 2016-04-28 19:47 UTC
Rancher Version: April 27th update

Steps to Reproduce:
1. Configure 3 hosts on the rancher set up
2. Create a service with two containers and healthcheck enabled
3. Check the healthcheckhostmap entry for the container in the api. It should list two entries for the two hosts which are monitoring the container
4. Turn off one of the hosts. Only one entry will be seen in the healthcheckhostmap entry for the container in the api
5. Turn on the host and check /etc/healthcheck/healthcheck.cfg. It does not have an entry on the container it is monitoring.The entry shows up only after the container is restarted.
   
Bug: The host should automatically monitor the container after it is turned on.

**Comment by alena1108** [comment] 2016-05-31 17:01
Race condition with the same root cause as: https://github.com/rancher/rancher/issues/2642, closing as a duplicate

**Closed by alena1108** 2016-05-31 17:01 UTC
Labels: kind/bug
