### ISSUE TITLE
adding secrets-service after adding secrets to a container leads to error

### ISSUE THREAD

**Issue by abuisine** [rancher/rancher#8079] opened 2017-03-07 12:17 UTC
**Rancher Versions:**
Server: 1.5.0
healthcheck: v0.2.3
ipsec: rancher/net:holder
network-services: metadata:v0.8.11, network-manager:v0.4.8
scheduler: scheduler:v0.7.4
secrets: storage-secrets:v0.6.8

**Docker Version:**
17.03.0-ce

**OS and where are the hosts located? (cloud, bare metal, etc):**
bare metal Ubuntu 16.04.2 LTS (4.8.0)

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
single node rancher

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle

**Steps to Reproduce:**
Create a new environment, add secrets, create a stack with one service, attach secrets, start the service, and only then add the secrets-service to infrastructure
**Results:** 
Attemps to upgrade the service will result in
```
Upgrading (Expected state running but got error: /VolumeDriver.Attach '70edd8c5d588616ad3d03451b5d9f7b9c30ca6ffd7a34ba442ffab0aab629da9' (driver 'rancher-secrets') returned status 500: 500 Internal Server Error)
```

**Comment by abuisine** [comment] 2017-03-07 12:56
```
time="2017-03-07T12:56:07Z" level=info msg="Updating volume 48744eaa84fe16b8601c9a57f384af3eccc71b29aac1c92938e930f3f8ed332b (1v1337) rancher-secrets:1sd2 on 1h7, state inactive => inactive" err=<nil> 
time="2017-03-07T12:56:07Z" level=info msg=create.response 
time="2017-03-07T12:56:07Z" level=info msg=attach.request name=48744eaa84fe16b8601c9a57f384af3eccc71b29aac1c92938e930f3f8ed332b 
time="2017-03-07T12:56:07Z" level=error msg="Unsuccessful request: 500 Internal Server Error" 
time="2017-03-07T12:56:07Z" level=error msg="Failed to attach, opts=={\"device\":\"/var/lib/rancher/volumes/rancher-secrets/staging/48744eaa84fe16b8601c9a57f384af3eccc71b29aac1c92938e930f3f8ed332b\",\"io.rancher.secrets.token\":\"{\\\"value\\\":\\\"eyJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJjYXR0bGUiLCJraWQiOiJkZWZhdWx0IiwiaXNzIjoiaHR0cDpcL1wvY2F0dGxlLmlvIiwiZXhwIjoxNTIwNDQ4MjkyLCJ1dWlkIjoiOTY2NGNjNjctNTY5ZC00ZDQ4LTliYmMtZTUzN2IzZDU2OTNlIiwiaWF0IjoxNDg4ODkxMzY2fQ.r3H-KSXWQzSyePYj9BS2TQVidEUicrhB_xHoW0CNmBx5pvc_vW0tGsdPwExu44IwPaYGFClGmruedJ0CO_a32g42V8fIRH-9f82oGDyyjT1FsGEQEM1ZXz9H9eWW6grIZdJq61gxxO7ahu_mdPIT_zcvDvjIpG6fvY2enK1h2mwKQw4aUvZ3ScDV6WRdQ50An1EN9E5fBLu-kjmIzLZUJn1TjZtYnr_Tro8q18yzWNLih-n5iO1BklmvNrEzqPgn6Omt8xkZPfjItLbhTBvtRsautqRtGGxplytRP2wvk8dwof6VYk9CwNObwzf3obzv_Y-RWD1ev6xmg_7lIhBIFw\\\"}\",\"name\":\"48744eaa84fe16b8601c9a57f384af3eccc71b29aac1c92938e930f3f8ed332b\",\"rancher\":\"true\"}: Unsuccessful request: 500 Internal Server Error" 
time="2017-03-07T12:56:07Z" level=error msg=attach.response error="Unsuccessful request: 500 Internal Server Error" 
time="2017-03-07T12:56:07Z" level=info msg=attach.request name=48744eaa84fe16b8601c9a57f384af3eccc71b29aac1c92938e930f3f8ed332b 
time="2017-03-07T12:56:08Z" level=error msg="Unsuccessful request: 500 Internal Server Error" 
time="2017-03-07T12:56:08Z" level=error msg="Failed to attach, opts=={\"device\":\"/var/lib/rancher/volumes/rancher-secrets/staging/48744eaa84fe16b8601c9a57f384af3eccc71b29aac1c92938e930f3f8ed332b\",\"io.rancher.secrets.token\":\"{\\\"value\\\":\\\"eyJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJjYXR0bGUiLCJraWQiOiJkZWZhdWx0IiwiaXNzIjoiaHR0cDpcL1wvY2F0dGxlLmlvIiwiZXhwIjoxNTIwNDQ4MjkyLCJ1dWlkIjoiOTY2NGNjNjctNTY5ZC00ZDQ4LTliYmMtZTUzN2IzZDU2OTNlIiwiaWF0IjoxNDg4ODkxMzY2fQ.r3H-KSXWQzSyePYj9BS2TQVidEUicrhB_xHoW0CNmBx5pvc_vW0tGsdPwExu44IwPaYGFClGmruedJ0CO_a32g42V8fIRH-9f82oGDyyjT1FsGEQEM1ZXz9H9eWW6grIZdJq61gxxO7ahu_mdPIT_zcvDvjIpG6fvY2enK1h2mwKQw4aUvZ3ScDV6WRdQ50An1EN9E5fBLu-kjmIzLZUJn1TjZtYnr_Tro8q18yzWNLih-n5iO1BklmvNrEzqPgn6Omt8xkZPfjItLbhTBvtRsautqRtGGxplytRP2wvk8dwof6VYk9CwNObwzf3obzv_Y-RWD1ev6xmg_7lIhBIFw\\\"}\",\"name\":\"48744eaa84fe16b8601c9a57f384af3eccc71b29aac1c92938e930f3f8ed332b\",\"rancher\":\"true\"}: Unsuccessful request: 500 Internal Server Error" 
time="2017-03-07T12:56:08Z" level=error msg=attach.response error="Unsuccessful request: 500 Internal Server Error" 
time="2017-03-07T12:56:08Z" level=info msg=attach.request name=48744eaa84fe16b8601c9a57f384af3eccc71b29aac1c92938e930f3f8ed332b 
time="2017-03-07T12:56:08Z" level=error msg="Unsuccessful request: 500 Internal Server Error" 
time="2017-03-07T12:56:08Z" level=error msg="Failed to attach, opts=={\"device\":\"/var/lib/rancher/volumes/rancher-secrets/staging/48744eaa84fe16b8601c9a57f384af3eccc71b29aac1c92938e930f3f8ed332b\",\"io.rancher.secrets.token\":\"{\\\"value\\\":\\\"eyJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJjYXR0bGUiLCJraWQiOiJkZWZhdWx0IiwiaXNzIjoiaHR0cDpcL1wvY2F0dGxlLmlvIiwiZXhwIjoxNTIwNDQ4MjkyLCJ1dWlkIjoiOTY2NGNjNjctNTY5ZC00ZDQ4LTliYmMtZTUzN2IzZDU2OTNlIiwiaWF0IjoxNDg4ODkxMzY2fQ.r3H-KSXWQzSyePYj9BS2TQVidEUicrhB_xHoW0CNmBx5pvc_vW0tGsdPwExu44IwPaYGFClGmruedJ0CO_a32g42V8fIRH-9f82oGDyyjT1FsGEQEM1ZXz9H9eWW6grIZdJq61gxxO7ahu_mdPIT_zcvDvjIpG6fvY2enK1h2mwKQw4aUvZ3ScDV6WRdQ50An1EN9E5fBLu-kjmIzLZUJn1TjZtYnr_Tro8q18yzWNLih-n5iO1BklmvNrEzqPgn6Omt8xkZPfjItLbhTBvtRsautqRtGGxplytRP2wvk8dwof6VYk9CwNObwzf3obzv_Y-RWD1ev6xmg_7lIhBIFw\\\"}\",\"name\":\"48744eaa84fe16b8601c9a57f384af3eccc71b29aac1c92938e930f3f8ed332b\",\"rancher\":\"true\"}: Unsuccessful request: 500 Internal Server Error" 
time="2017-03-07T12:56:08Z" level=error msg=attach.response error="Unsuccessful request: 500 Internal Server Error" 
time="2017-03-07T12:56:08Z" level=info msg=attach.request name=48744eaa84fe16b8601c9a57f384af3eccc71b29aac1c92938e930f3f8ed332b 
time="2017-03-07T12:56:08Z" level=error msg="Unsuccessful request: 500 Internal Server Error" 
time="2017-03-07T12:56:08Z" level=error msg="Failed to attach, opts=={\"device\":\"/var/lib/rancher/volumes/rancher-secrets/staging/48744eaa84fe16b8601c9a57f384af3eccc71b29aac1c92938e930f3f8ed332b\",\"io.rancher.secrets.token\":\"{\\\"value\\\":\\\"eyJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJjYXR0bGUiLCJraWQiOiJkZWZhdWx0IiwiaXNzIjoiaHR0cDpcL1wvY2F0dGxlLmlvIiwiZXhwIjoxNTIwNDQ4MjkyLCJ1dWlkIjoiOTY2NGNjNjctNTY5ZC00ZDQ4LTliYmMtZTUzN2IzZDU2OTNlIiwiaWF0IjoxNDg4ODkxMzY2fQ.r3H-KSXWQzSyePYj9BS2TQVidEUicrhB_xHoW0CNmBx5pvc_vW0tGsdPwExu44IwPaYGFClGmruedJ0CO_a32g42V8fIRH-9f82oGDyyjT1FsGEQEM1ZXz9H9eWW6grIZdJq61gxxO7ahu_mdPIT_zcvDvjIpG6fvY2enK1h2mwKQw4aUvZ3ScDV6WRdQ50An1EN9E5fBLu-kjmIzLZUJn1TjZtYnr_Tro8q18yzWNLih-n5iO1BklmvNrEzqPgn6Omt8xkZPfjItLbhTBvtRsautqRtGGxplytRP2wvk8dwof6VYk9CwNObwzf3obzv_Y-RWD1ev6xmg_7lIhBIFw\\\"}\",\"name\":\"48744eaa84fe16b8601c9a57f384af3eccc71b29aac1c92938e930f3f8ed332b\",\"rancher\":\"true\"}: Unsuccessful request: 500 Internal Server Error" 
time="2017-03-07T12:56:08Z" level=error msg=attach.response error="Unsuccessful request: 500 Internal Server Error" 
time="2017-03-07T12:56:08Z" level=info msg=attach.request name=48744eaa84fe16b8601c9a57f384af3eccc71b29aac1c92938e930f3f8ed332b 
time="2017-03-07T12:56:08Z" level=error msg="Unsuccessful request: 500 Internal Server Error" 
time="2017-03-07T12:56:08Z" level=error msg="Failed to attach, opts=={\"device\":\"/var/lib/rancher/volumes/rancher-secrets/staging/48744eaa84fe16b8601c9a57f384af3eccc71b29aac1c92938e930f3f8ed332b\",\"io.rancher.secrets.token\":\"{\\\"value\\\":\\\"eyJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJjYXR0bGUiLCJraWQiOiJkZWZhdWx0IiwiaXNzIjoiaHR0cDpcL1wvY2F0dGxlLmlvIiwiZXhwIjoxNTIwNDQ4MjkyLCJ1dWlkIjoiOTY2NGNjNjctNTY5ZC00ZDQ4LTliYmMtZTUzN2IzZDU2OTNlIiwiaWF0IjoxNDg4ODkxMzY2fQ.r3H-KSXWQzSyePYj9BS2TQVidEUicrhB_xHoW0CNmBx5pvc_vW0tGsdPwExu44IwPaYGFClGmruedJ0CO_a32g42V8fIRH-9f82oGDyyjT1FsGEQEM1ZXz9H9eWW6grIZdJq61gxxO7ahu_mdPIT_zcvDvjIpG6fvY2enK1h2mwKQw4aUvZ3ScDV6WRdQ50An1EN9E5fBLu-kjmIzLZUJn1TjZtYnr_Tro8q18yzWNLih-n5iO1BklmvNrEzqPgn6Omt8xkZPfjItLbhTBvtRsautqRtGGxplytRP2wvk8dwof6VYk9CwNObwzf3obzv_Y-RWD1ev6xmg_7lIhBIFw\\\"}\",\"name\":\"48744eaa84fe16b8601c9a57f384af3eccc71b29aac1c92938e930f3f8ed332b\",\"rancher\":\"true\"}: Unsuccessful request: 500 Internal Server Error" 
time="2017-03-07T12:56:08Z" level=error msg=attach.response error="Unsuccessful request: 500 Internal Server Error" 
```

**Comment by cloudnautique** [comment] 2017-03-07 17:40
Are there any logs on the rancher server side of things?

**Comment by johnrengelman** [comment] 2017-03-20 15:32
Getting the same issue but with Docker 1.12.6 on Rancher 1.5.1.
This was in the cattle-debug logs:
```
Error id: [0ab83f14-6f9c-4004-b17b-1ae
f2ca7cd26]. java.io.IOException: Failed to rewrap secret :Bad Request
        at io.cattle.platform.framework.secret.SecretsServiceImpl$2.handleResponse(SecretsServiceImpl.java:80) ~[cattle-framework-encryption-0.5.0-SNAPSHOT.jar:na]
        at io.cattle.platform.framework.secret.SecretsServiceImpl$2.handleResponse(SecretsServiceImpl.java:75) ~[cattle-framework-encryption-0.5.0-SNAPSHOT.jar:na]
        at org.apache.http.client.fluent.Response.handleResponse(Response.java:85) ~[fluent-hc-4.3.1.jar:4.3.1]
        at io.cattle.platform.framework.secret.SecretsServiceImpl.getValues(SecretsServiceImpl.java:75) ~[cattle-framework-encryption-0.5.0-SNAPSHOT.jar:na]
        at io.cattle.platform.framework.secret.SecretsServiceImpl.getValues(SecretsServiceImpl.java:106) ~[cattle-framework-encryption-0.5.0-SNAPSHOT.jar:na]
        at io.cattle.platform.iaas.api.request.handler.SecretsApiRequestHandler.generate(SecretsApiRequestHandler.java:73) ~[cattle-iaas-api-logic-0.5.0-SNAPSHOT.jar:na]
        at io.github.ibuildthecloud.gdapi.request.handler.AbstractResponseGenerator.handle(AbstractResponseGenerator.java:14) ~[cattle-framework-java-server-0.5.0-SNAPSHOT.jar:na]
        at io.github.ibuildthecloud.gdapi.servlet.ApiRequestFilterDelegate.doFilter(ApiRequestFilterDelegate.java:99) ~[cattle-framework-java-server-0.5.0-SNAPSHOT.jar:na]
        at io.cattle.platform.api.servlet.ApiRequestFilter$1.runInContext(ApiRequestFilter.java:96) [cattle-framework-api-0.5.0-SNAPSHOT.jar:na]
        at org.apache.cloudstack.managed.context.ManagedContextRunnable$1.run(ManagedContextRunnable.java:49) [cattle-framework-managed-context-0.5.0-SNAPSHOT.jar:na]
        at org.apache.cloudstack.managed.context.impl.DefaultManagedContext$1.call(DefaultManagedContext.java:55) [cattle-framework-managed-context-0.5.0-SNAPSHOT.jar:na]
        at org.apache.cloudstack.managed.context.impl.DefaultManagedContext.callWithContext(DefaultManagedContext.java:108) [cattle-framework-managed-context-0.5.0-SNAPSHOT.jar:na]
        at org.apache.cloudstack.managed.context.impl.DefaultManagedContext.runWithContext(DefaultManagedContext.java:52) [cattle-framework-managed-context-0.5.0-SNAPSHOT.jar:na]
        at org.apache.cloudstack.managed.context.ManagedContextRunnable.run(ManagedContextRunnable.java:46) [cattle-framework-managed-context-0.5.0-SNAPSHOT.jar:na]
        at io.cattle.platform.api.servlet.ApiRequestFilter.doFilter(ApiRequestFilter.java:106) [cattle-framework-api-0.5.0-SNAPSHOT.jar:na]
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652) [jetty-servlet-9.2.11.v20150529.jar:9.2.11.v20150529]
        at org.eclipse.jetty.servlets.UserAgentFilter.doFilter(UserAgentFilter.java:83) [jetty-servlets-9.2.11.v20150529.jar:9.2.11.v20150529]
        at org.eclipse.jetty.servlets.GzipFilter.doFilter(GzipFilter.java:300) [jetty-servlets-9.2.11.v20150529.jar:9.2.11.v20150529]
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652) [jetty-servlet-9.2.11.v20150529.jar:9.2.11.v20150529]
        at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:585) [jetty-servlet-9.2.11.v20150529.jar:9.2.11.v20150529]
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143) [jetty-server-9.2.11.v20150529.jar:9.2.11.v20150529]
        at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:577) [jetty-security-9.2.11.v20150529.jar:9.2.11.v20150529]
        at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:223) [jetty-server-9.2.11.v20150529.jar:9.2.11.v20150529]
        at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1127) [jetty-server-9.2.11.v20150529.jar:9.2.11.v20150529]
        at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:515) [jetty-servlet-9.2.11.v20150529.jar:9.2.11.v20150529]
        at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185) [jetty-server-9.2.11.v20150529.jar:9.2.11.v20150529]
        at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1061) [jetty-server-9.2.11.v20150529.jar:9.2.11.v20150529]
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141) [jetty-server-9.2.11.v20150529.jar:9.2.11.v20150529]
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97) [jetty-server-9.2.11.v20150529.jar:9.2.11.v20150529]
        at org.eclipse.jetty.server.Server.handle(Server.java:499) [jetty-server-9.2.11.v20150529.jar:9.2.11.v20150529]
        at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:310) [jetty-server-9.2.11.v20150529.jar:9.2.11.v20150529]
        at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:257) [jetty-server-9.2.11.v20150529.jar:9.2.11.v20150529]
        at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:540) [jetty-io-9.2.11.v20150529.jar:9.2.11.v20150529]
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635) [jetty-util-9.2.11.v20150529.jar:9.2.11.v20150529]
        at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555) [jetty-util-9.2.11.v20150529.jar:9.2.11.v20150529]
        at java.lang.Thread.run(Thread.java:745) [na:1.8.0_72]
```

**Comment by johnrengelman** [comment] 2017-03-20 15:33
We initially followed the same path: added secrets, then deployed the infrastructure service.
this was working for some secrets and when we added a new one after it was all working, this start happening.

**Comment by mch1307** [comment] 2017-03-27 18:31
same issue here with rancher v1.5.2

**Comment by cloudnautique** [comment] 2017-03-27 20:02
I'm having trouble reproducing this issue here is what I'm doing;

 1) fresh rancher 1.5.2 install
 1) Create an environment
 1) Add 1 host
 1) Create secret (My backend is the local encryption)
 1) Launch a single service scale 1 that consumes the secret
 1) Wait til it goes green
 1) Deploy Secrets Volume Driver service. Image 0.6.8 from catalog entry 0.0.2
 1) upgrade the service

I haven't seen any errors, and the upgraded service has the secrets. I have also tried adding a second secret on the upgrade without issue. 

Can some one let me know if I'm deviating from the use case?

**Comment by mch1307** [comment] 2017-03-28 07:25
After having encountered the issue, I just removed plenty of secret volumes it had created before being able to remove the rancher-secrets. After that re-enabled the rancher secret from catalog, re-created new secrets and then stack. Everything looks ok, I could upgrade the stack. Did not try yet to add new secret to service.

**Comment by bascht** [comment] 2017-03-28 12:10
@mch1307 If I may chime in here: Are all your hosts running the same Docker Version / the same Agent Version? I ran into the same exact problem in an environment where one host was still running RancherOS v0.8.1, whereas the others where already on v0.9.1. I see that you're running 17.03.0-ce on Ubuntu, but it could be a compatibility issue nevertheless. :smile:

**Comment by cloudnautique** [comment] 2017-03-28 14:50
It is very important that in 1.5.x you use the newest secrets volume driver. We broke backwards compatibility with the 0.0.1 version from 1.4.x so that we could send large secrets.

**Comment by mch1307** [comment] 2017-03-29 07:59
@bascht I am running ContainerLinux latest stable on all hosts, all hosts running same version. The complete infra is a brand new 1.5.2 install, no upgrade so I assume docker and rancher agent versions are the same

**Comment by cloudnautique** [comment] 2017-04-05 17:11
The issue with the `failed to rewrap` message should be addressed in v1.5.4. I haven't been able to reproduce this exact issue, but we fixed a bug in the signature verification that I think has a better then not chance of resolving this.

**Comment by oskapt** [comment] 2017-04-11 17:46
I just hit this issue on 1.5.3 with secrets driver 0.6.8. I added the secret before adding the secrets infrastructure stack. When i upgraded a service to use the secret, I received this:
```
Expected state running but got error: /VolumeDriver.Attach 'fdd63a843c88c16bca28501f564e5c1f0c0b0a096b9f6f18105e4b02ed1f5d41' (driver 'rancher-secrets') returned status 500: 500 Internal Server Error
```

After deleting the secret and recreating it I was able to upgrade without issue.

**Comment by cloudnautique** [comment] 2017-04-11 17:54
As noted, the fix went out in v1.5.4.

**Comment by cloudnautique** [comment] 2017-07-21 23:49
Has anyone seen this in 1.5.4 or later?

**Comment by cloudnautique** [comment] 2017-07-21 23:50
closing because of inactivity.

**Closed by cloudnautique** 2017-07-21 23:50 UTC
Labels: area/secrets, status/resolved

**Comment by rbhaddon** [comment] 2019-01-31 19:34
In the last month, we started getting this on Rancher 1.6. It might be related to self-signed certificates used for Rancher server.  We ended up getting around 80% of the failures by populating Rancher agent hosts with a `/var/lib/rancher/etc/ssl/ca.crt` file.  The other 20%?  No clue.
