### ISSUE TITLE
Ingress Status Load Balancer IPs Not Being Updated

### ISSUE THREAD

**Issue by ekristen** [rancher/rancher#28230] opened 2020-08-04 22:17 UTC
**What kind of request is this (question/bug/enhancement/feature request):** 

Bug

**Steps to reproduce (least amount of steps as possible):**

Unknown?

**Result:**

I have several clusters setup with dedicated edge nodes with nginx ingress deployment, however the `status.loadBalancer` is not being updated to reflect the IP addresses of all the nginx ingress controller nodes.

**Other details that may be helpful:**

1. Amazon EC2 v1.16.10 (cloud provider OFF)
2. Amazon EC2 v1.16.10 (cloud provider on)
3. Amazon EC2 v1.17.6 (cloud provider OFF)

I have multiple Ingress resources defined and the `status.loadBalancer` shows only a single ip address where there are 2+ nodes WITH external IP with the nginx ingress controller deployed.

I found this because I was looking my global DNS and I saw a few records only had a single IP for the DNS record when I knew there was more than one ingress controller and edge node deployed.

---

Question 1 -- who/what is responsible for updating the `status.loadBalancer` section of the ingress in Rancher 2? Is that k8s, something special about Rancher? I can't seem to find any details?

Question 2 -- has anyone seen this before? 

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): 2.4.4
- Installation option (single install/HA): HA

gzrancher/rancher#11807

**Comment by ekristen** [comment] 2020-08-05 00:55
This looks like it's a bug in the nginx ingress controller. There are lots of reports where the status stops getting updated.

**Comment by ekristen** [comment] 2020-08-05 00:56
A restart of the ingress controller that has the lock seems to fix it, but it's less than ideal. Supposedly this is fixed after k8s 1.14 and after 0.23 of the controller but I clearly am hitting it.

https://github.com/kubernetes/ingress-nginx/issues/3033
https://github.com/kubernetes/ingress-nginx/pull/4996

**Comment by ekristen** [comment] 2020-08-05 18:03
Upon further investigation this appears to be a problem with having Project Isolation enabled. Circumstantial evidence would suggesting what when Project Isolation is enabled that only the IP of the ingress controller that has leader election will be used to update the `status.loadBalancer.ingress.{}` ip addresses.  This needs testing to confirm, but after disabling project isolation and restarting the controllers IPs for every node started appearing on ingress status fields.

**Comment by kinarashah** [comment] 2020-09-17 16:37
We add label field.cattle.io/podName to pods with host ports when network policy is enabled. This is because, upstream ingress controller finds the running addresses by filtering pods using label selector. https://github.com/kubernetes/ingress-nginx/blob/nginx-0.25.1/internal/ingress/status/status.go#L206 

https://github.com/rancher/rancher/issues/26677 has a detailed explanation. 

Only missing puzzle is how it works in 0.21.0 since it's the same code. https://github.com/kubernetes/ingress-nginx/blob/nginx-0.21.0/internal/ingress/status/status.go#L298

**Comment by kinarashah** [comment] 2020-09-17 16:49
https://github.com/rancher/rancher/issues/25492

**Comment by chrisfosterelli** [comment] 2020-09-17 22:41
@kinarashah Thanks for digging into this, I have spent much time manually updating IPs to workaround so far 😄

**Comment by sowmyav27** [comment] 2020-10-19 23:44
### **On 2.4.8 Reproduced the issue**

- Deploy a 2 worker node cluster.
- Enabled `Project Network Isolation` 
- Ingress controller deployed has the following labels: -- **Expected with fix**: `field.cattle.io/podName: nginx-ingress-controller-qfhbt` should NOT be available

```
labels:
    app: ingress-nginx
    controller-revision-hash: 8d4d59f96
    field.cattle.io/podName: nginx-ingress-controller-qfhbt
    pod-template-generation: "1"
```

- Deploy a GDNS - provider and entry
- The A record for the GDNS provider points to only 1 worker node
- Create a workload - scale = 2 in default project
- Create an ingress pointing to this workload
- View/Edit Yaml for this ingress
```
status:
  loadBalancer:
    ingress:
    - ip: <worker nodes 1>
```
- Ip address of only 1 worker node is available. -- **Expected** - all worker node's IP addresses should be available

### **On 2.5-head commit id: `9d388217`, master-head commit id: `68042fa94` and 2.4-head - commit id: `d277054ab`**

- Deploy a 2 worker node cluster.
- Enabled `Project Network Isolation` 
- Labels on the ingress-controller in System project -
```
labels:
    app: ingress-nginx
    controller-revision-hash: 6c464fc9d6
    pod-template-generation: "1"
```
- `podName` label is NOT available
- Deploy a GDNS - provider and entry
- The A record for the GDNS provider points to both the worker nodes
- Create a workload - scale = 2 in default project
- Create an ingress pointing to this workload
- View/Edit Yaml for this ingress

```
status:
  loadBalancer:
    ingress:
    - ip: <w1>
    - ip: <w2>
```

**Comment by ekristen** [comment] 2020-10-20 00:08
The main culprit here is Project Isolation. I verified this on 4 of my clusters, if you have project isolation turned on, the nginx ingress and external DNS system does not work properly. Only the nginx controller that has the lock will show up as an IP for an external DNS ingress.

**Comment by maggieliu** [comment] 2020-10-22 18:31
@sowmyav27 created separate issue to track master issue. If we can good for 2.4 and 2.5 can you please close this?

**Comment by sowmyav27** [comment] 2020-10-22 20:01
Closing this as it works on 2.4 and 2.5 branches.

**Closed by sowmyav27** 2020-10-22 20:01 UTC
Labels: [zube]: To Test, internal
