### ISSUE TITLE
[ enhancement ] Allow editing of Image for a stopped service

### ISSUE THREAD

**Issue by ebr** [rancher/rancher#2888] opened 2015-12-03 16:19 UTC
Use case:  deployed a broken image :arrow_right:  have to keep the service stopped, because starting a container from this image blows things up :arrow_right: can't edit the image :arrow_right: :crying_cat_face: 

The only way around this at the moment is to clone the service.

It would be nice to be able to edit the image and start the service.

(alternatively, broaden this to "Allow upgrade of a stopped service" - but that might be too general of a request)

**Comment by deniseschannon** [comment] 2015-12-03 22:06
I believe this is being fixed in this upcoming release. It sounds like a duplicate of https://github.com/rancher/rancher/issues/2650 but at a service level.

**Comment by sangeethah** [comment] 2015-12-04 03:24
Tested with latest build from master on dec 3.

We are presented with option to "Upgrade" when service is in "inactive" state. 

Following workflow works as expected now:
Create a service with invalid image.
Service is stuck in "activating" state since containers get "removed" and recreated which keeps failing.
Now stop the service.
Upgrade the service . As part of upgrading , correct the image name.
Service gets upgraded successfully.
"Finish upgrade" to complete the upgrade process.

**Closed by sangeethah** 2015-12-04 03:24 UTC
Labels: area/service, kind/enhancement, status/resolved, status/to-test

**Comment by kaos** [comment] 2016-01-07 08:41
When upgrading from inactive state, is it left as inactive after the upgrade as well, or does it go into activating automatically? (I'd prefer the former, requiring an explicit start action before going active.)

**Comment by deniseschannon** [comment] 2016-01-11 19:19
@kaos I had to test this out as I wasn't sure. When you upgrade, the new containers are automatically created and started and then the service is in an "Upgraded" state. When you finish the upgrade, it removes your inactive container.

**Comment by kaos** [comment] 2016-01-11 19:47
Ok, so the latter.. Thanks for checking :)
