### ISSUE TITLE
[Bug] Authentication Proxy does not work with Skaffold (blocks on rollout status)

### ISSUE THREAD

**Issue by Blackclaws** [rancher/rancher#32676] opened 2021-05-11 16:05 UTC
**What kind of request is this (question/bug/enhancement/feature request):**
Bug related to https://github.com/GoogleContainerTools/skaffold/issues/5810

**Steps to reproduce (least amount of steps as possible):**
Manage a cluster via rancher
Get the kubeconfig for the cluster and make sure your context is set to accessing the cluster via the rancher url (proxy mode) and not via the Authenticated Cluster Endpoint
Try using skaffold with the kubectl deployer and a deployment manifest (can be any simple deployment):

skaffold.yaml
```yaml
apiVersion: skaffold/v2beta13
kind: Config
metadata:
  name: minimal-example
deploy:
  kubectl:
    manifests:
    - deployment.yaml
```

deployment.yaml
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: minimal
spec:
  replicas: 3
  selector:
    matchLabels:
      app: minimal
  template:
    metadata:
      labels:
        app: minimal
    spec:
      containers:
      - name: minimal
        image: busybox
        command:
          - sleep
        args:
          - "10000"
```
**Result:**
Skaffold gets stuck at waiting for deployments to stabilize https://github.com/GoogleContainerTools/skaffold/issues/5810 and only converges after approximately 7 minutes

**Other details that may be helpful:**
Directly accessing the cluster via the api server authorized endpoint instead of the endpoint proxied by the rancher server works fine. So it appears that there is either missing functionality or some sort of weird caching behavior in play. 

Happens for all kinds of downstream clusters such as k3s or rke spawned by rancher.

**Environment information**
- Rancher version 2.5.8
- Installation option (single install/HA): HA

**Comment by jakefhyde** [comment] 2021-11-23 19:54
Moving this back to test, as I can no longer reproduce in 2.6-head. Both contexts complete in around 7 seconds, whereas in v2.6.2, the proxy completes in about 30 seconds.

**Comment by snasovich** [comment] 2021-11-30 16:44
@Blackclaws , wondering if you can validate if this is working as expected on v2.6-head image? (https://hub.docker.com/r/rancher/rancher/tags).

**Comment by Blackclaws** [comment] 2021-12-03 12:28
I can try validating it on a standalone installation or I can wait until 2.6.3 is released to validate it on our production system.

**Comment by snasovich** [comment] 2021-12-07 17:46
@Blackclaws , thank you for getting back to me. It would be great if you could validate it on a standalone installation prior in the next week or so - so we're sure it's actually fixed. Is this something you can do?

**Comment by Blackclaws** [comment] 2021-12-11 18:15
I've tried it on our production system by upgrading a copy of that to head. Issue persists. I'll try it on a standalone system as well.

**Comment by Blackclaws** [comment] 2021-12-11 18:26
A compounding issue is that as of rancher 2.6 the authorized endpoint is also broken for Keycloak backed users:

https://github.com/rancher/rancher/issues/35187

**Comment by jakefhyde** [comment] 2021-12-13 23:13
@Blackclaws still working on this, but still having some issues reproducing. Would you mind sharing some of the following information regarding your setup? 
- What kind of clusters are these (AKS, imported etc.)? 
- What kubernetes version is being used?
- What version of skaffold is being used?

Also any information regarding either skaffold or the command `kubectl -v 10 --context test-cluster rollout status deployment minimal --namespace default --watch=false
` blocking would be appreciated, as I haven't been able to reproduce comparable results with either.

**Comment by Blackclaws** [comment] 2021-12-13 23:15
Sure I'll help you as much as I can to reproduce this, I'll try to get a minimal example working as well if possible

- RKE rancher launched clusters.
- 1.21.5 in production 1.22.4 in the test I did
- Skaffold version 1.23.0

However skaffold version is not relevant as the blocking kubectl command itself shows the issue without even using skaffold.

**Comment by Blackclaws** [comment] 2021-12-20 17:40
It indeed seems fixed for new rancher setups. The existing production setup still has this issue. Setting up a new rancher starting at least from 2.5.10 doesn't show this issue, for whatever reason that may be. 

Since I can't reproduce this on a new install it seems this issue has something to do with something that happened in the past with our system. I think closing this issue is probably the best right now. I'll just setup the production system again over the holidays. If the issue does crop back up I'll reopen a new issue, or you can keep this issue open for a while, your choice.

**Comment by slickwarren** [comment] 2022-02-24 23:39
following the comment [instructions here](https://github.com/rancher/rancher/issues/32676#issuecomment-838997898), I was also unable to reproduce this issue using rancher v2.6.4-rc3.

**Closed by slickwarren** 2022-02-24 23:39 UTC
Labels: kind/task, [zube]: QA Next up, QA/S, free-for-all, team/area2
