### ISSUE TITLE
Malformed prerelease tag in kubernetes version

### ISSUE THREAD

**Issue by nlowe** [rancher/rancher#10681] opened 2017-12-28 16:24 UTC
**Rancher versions:**
rancher/server: `v2.0.0-alpha10`
rancher/agent: `v2.0-alpha4`

**Infrastructure Stack versions:**
kubernetes (if applicable): `v1.7.6+$Format:%h$`

**Docker version: (`docker version`,`docker info` preferred)**

<details>

```bash
Containers: 18
 Running: 17
 Paused: 0
 Stopped: 1
Images: 12
Server Version: 17.06.2-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 6e23458c129b551d5c9871e5174f6b1b7f6d1170
runc version: 810190ceaa507aa2727d7ae6f4790c76ec150bd2
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.4.0-104-generic
Operating System: Ubuntu 16.04.3 LTS
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 7.797GiB
Name: worker-01
ID: SZOY:5W6Y:334I:WHBH:C74L:RNJJ:EWPA:MLGA:NG2N:PX47:3MLE:Y7B5
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: No swap limit support
```

</details>

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**

<details>

```bash
user@worker-01:~$ uname -r
4.4.0-104-generic
user@worker-01:~$ cat /etc/os-release
NAME="Ubuntu"
VERSION="16.04.3 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.3 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial
```

</details>

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**

VMware ESXi VM's

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**

Single node, internal DB

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**

k8s?

**Steps to Reproduce:**

1. Follow the [Quick Start Guide for 2.0](http://rancher.com/docs/rancher/v2.0/en/quick-start-guide) to deploy a server and connect hosts
2. Attempt to deploy [nfs-client-provisioner](https://github.com/kubernetes-incubator/external-storage/tree/master/nfs-client) for PV's

**Results:**

The provisioner fails to start with:

```bash
panic: could not parse pre-release/metadata (+$Format:%h$) in version "v1.7.6+$Format:%h$"

goroutine 1 [running]:
github.com/kubernetes-incubator/external-storage/vendor/k8s.io/kubernetes/pkg/util/version.MustParseSemantic(0xc4204541a0, 0x12, 0x0)
        /home/travis/gopath/src/github.com/kubernetes-incubator/external-storage/vendor/k8s.io/kubernetes/pkg/util/version/version.go:119 +0x6c
github.com/kubernetes-incubator/external-storage/lib/controller.NewProvisionController(0x1b6d0a0, 0xc4200906e0, 0xc420014041, 0x1c, 0x1b59ea0, 0xc42013e330, 0xc4204541a0, 0x12, 0x0, 0x0, ...)
        /home/travis/gopath/src/github.com/kubernetes-incubator/external-storage/lib/controller/controller.go:304 +0x346
main.main()
        /home/travis/gopath/src/github.com/kubernetes-incubator/external-storage/nfs-client/cmd/nfs-client-provisioner/provisioner.go:144 +0x3af
```

It appears that the k8s distribution shipped with rancher contains an unformatted GitVersion string:

```bash
Client Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.0", GitCommit:"925c127ec6b946659ad0fd596fa959be43f0cc05", GitTreeState:"clean", BuildDate:"2017-12-15T21:07:38Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.6+$Format:%h$", GitCommit:"$Format:%H$", GitTreeState:"not a git tree", BuildDate:"1970-01-01T00:00:00Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by superseb** [comment] 2017-12-29 10:23
Thanks, duplicate of https://github.com/rancher/rancher/issues/10105

**Closed by superseb** 2017-12-29 10:23 UTC
