### ISSUE TITLE
"dial tcp x.x.x.x:5432: getsockopt: no route to host" error while exec'ing sql command from host A to Postgres host B

### ISSUE THREAD

**Issue by ravlio** [rancher/rancher#6043] opened 2016-09-23 10:07 UTC
**Rancher Version:**
v1.1.1

**Docker Version:**
1.12.1

**OS and where are the hosts located? (cloud, bare metal, etc):**
Ubuntu 16.04.1, Bare metal

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
2 physical nodes

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle

**Steps to Reproduce:**
Install Postgres from catalog on node A.

From node B run container with such code:

``` go
package main

import (
    "database/sql"
)

func main() {
    c, _ := sql.Open("postgres", "host=postgres user=postgres password=password dbname=postgres sslmode=disable")
    c.Ping()
}
```

**Results:** 
you will see error `dial tcp 10.42.38.79:5432: getsockopt: no route to host` in container logs.

**Expected:**
successful connection and command execution.

I trying to dig into problem and researched that sql.Open itself did not produce errors, but further commands (ping, Query, ...) does.

If I put some sleep before connection, the problem disappears. Also if I just run empty container with /bin/sh and then connect to shell and then connect to postgres via psql, the connection will succeed.

My thoughts about this is somewhere is a network lag. I assume that somewhere in overlay, IPSec maybe.

**Comment by ravlio** [comment] 2016-09-23 12:02
Error happens event with simpler code:

```go
conn, err := net.Dial("tcp", "postgres:5432")
fmt.Fprint(conn, "test") // throws here
```

**Comment by yunspace** [comment] 2016-10-23 11:23
I'm also getting the same error when connecting to a postgres container (used the official postgres:9.5) from another host. The code is also a standard golang, same as @ravlio 

    conn, err := sql.Open("postgres", URL)

**Comment by aemneina** [comment] 2016-11-08 04:08
@ravlio did you manage to resolve this?

**Comment by ravlio** [comment] 2016-11-08 08:27
@aemneina no, unfortunately. Hope Rancher team will react on this issue some day.

**Comment by aemneina** [comment] 2016-11-11 21:09
@ravlio can you share details on how this is deployed, is there a docker/rancher-compose.yml file you could share that reproduces this?

**Comment by aemneina** [comment] 2016-11-12 23:16
@ravlio Can you share the details of how you launch this postgres container? If you have the docker/rancher-compose.yml files that might help get you closer to resolving this.

**Comment by aemneina** [comment] 2016-11-12 23:24
actually rereading the original problem statement it seems the issue is that you're trying to connect to the postgres server before some sanity checks succeed (can the container/app talk to the postgres container). I'll close this out as everything seems to be working as expected.

**Closed by aemneina** 2016-11-12 23:24 UTC
Labels: kind/question

**Comment by xgz123** [comment] 2018-08-05 13:39
I have the silimar issue and it turns out to be a firewall problem
