### ISSUE TITLE
Unable to view container stats with 1.1.0 on CentOS 7 with Docker 1.10.3 using thinpool

### ISSUE THREAD

**Issue by yoerayo** [rancher/rancher#5428] opened 2016-07-14 17:41 UTC
**Rancher Version:**
1.1.0
**Docker Version:**
1.10.3
**OS and where are the hosts located? (cloud, bare metal, etc):**
CentOS 7 on VMware vSphere
**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
Single node rancher, internal DB mapped to host path
**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle
**Steps to Reproduce:**
Configure Docker 1.10.3 with dm.thinpooldev storage option, install Rancher 1.1.0, setup a container and attempt to view stats.
**Results:** 
![image](https://cloud.githubusercontent.com/assets/1474532/16849450/788e386c-49c8-11e6-81bc-751ca5df7484.png)

Plus the following repeated line in the Rancher agent log:

time="2016-07-14T17:39:22Z" level="error" msg="Error getting container info." error="request \"http://127.0.0.1:9344/api/v1.3/containers/system.slice/docker-2d01f01d4f83011039a3aecb0424ba3015978d284a94e167505b6e3b1f1e8645.scope\" failed with error: \"failed to get container \\\"/system.slice/docker-2d01f01d4f83011039a3aecb0424ba3015978d284a94e167505b6e3b1f1e8645.scope\\\" with error: unknown container \\\"/system.slice/docker-2d01f01d4f83011039a3aecb0424ba3015978d284a94e167505b6e3b1f1e8645.scope\\\"\"" id="2d01f01d4f83011039a3aecb0424ba3015978d284a94e167505b6e3b1f1e8645"

**Expected:**
Container stats are displayed

**Comment by amachowi** [comment] 2016-07-15 12:08
Have the same issue with RHEL7 and external Mysql.

**Comment by deniseschannon** [comment] 2016-07-15 15:49
@amachowi Are you also using Docker 1.10.3?

**Comment by amachowi** [comment] 2016-07-16 06:54
@deniseschannon : yes, I do.

**Comment by demarant** [comment] 2016-07-16 10:10
@deniseschannon:
This issue seems the same reported by me at https://github.com/rancher/rancher/issues/5326
We are also on centos7 and docker 1.10.3

**Comment by demarant** [comment] 2016-07-16 10:11
Maybe caused by #5452 ?

**Comment by amachowi** [comment] 2016-07-17 19:06
Seems that it is related to docker storage settings.

I run docker as following:
DOCKER_STORAGE_OPTIONS="--storage-driver devicemapper --storage-opt dm.fs=xfs --storage-opt dm.thinpooldev=/dev/mapper/VG02-docker--pool --storage-opt dm.use_deferred_removal=true"

If I leave out this storage options and use docker with loopback mode, metrics work again. Since this isn't recommended, it is not an option for production. Nevertheless, thinpoolprovisioning seems to cause  trouble.

**Comment by snahelou** [comment] 2016-07-18 07:37
Hello

Same errors  with Docker 1.11.2 and Rancher 1.1.0 and 1.1.1 (just updated).
Hosts statistics / logs / command line work but no stats for containers.

**Comment by yoerayo** [comment] 2016-07-19 13:14
Could this be related to cadvisor issue https://github.com/google/cadvisor/issues/1338?

**Comment by yoerayo** [comment] 2016-07-26 15:52
Not related to #5452 as this is still broken in 1.1.2

**Comment by deniseschannon** [comment] 2016-08-18 06:48
@yoerayo We use cadvisor for our stats, so I believe it's a cadvisor issue.  We need to upgrade our version of cadvisor as a fix has been made in cadvisor.

**Comment by janeczku** [comment] 2016-09-30 15:44
@deniseschannon The mentioned fix appears first in cAdvisor `v0.23.5`. The cAdvisor we shipped with 1.2.0-pre4 is still `v0.23.4`.
https://github.com/google/cadvisor/pull/1343

**Comment by deniseschannon** [comment] 2016-10-12 15:56
In v1.2.0-pre4, we are moving away from cadvisor, which was collecting our container stats to getting stats from `docker stats`. 

@sangeethah @soumyalj can just test that container stats is working on CentOS7 with v1.2.0-pre4?

**Comment by soumyalj** [comment] 2016-10-14 18:53
Tested with Master on Docker 1.10.3. Container stats and Host stats are displayed. See below:
<img width="1618" alt="centos-1 10 3 -container stats" src="https://cloud.githubusercontent.com/assets/18536626/19399120/be8f2c7a-9204-11e6-84d3-f46ccb78cc98.png">
<img width="1626" alt="centos1 10 3 host stats" src="https://cloud.githubusercontent.com/assets/18536626/19399126/c4f98c18-9204-11e6-844a-639bb53131c7.png">

**Closed by soumyalj** 2016-10-14 18:53 UTC
Labels: area/stats, kind/task, status/to-test
