### ISSUE TITLE
scoped token leading to 401 auth problem

### ISSUE THREAD

**Issue by zhongguanqun** [rancher/rancher#21704] opened 2019-07-23 08:20 UTC
*Describe your issue here*
<img width="1136" alt="屏幕快照 2019-07-23 下午3 52 56" src="https://user-images.githubusercontent.com/4767546/61694980-2ecd0100-ad65-11e9-96c6-ac6a9adc63a5.png">
<img width="1083" alt="屏幕快照 2019-07-23 下午3 48 59" src="https://user-images.githubusercontent.com/4767546/61695029-52904700-ad65-11e9-991e-10979c2cb477.png">

create a token based on a specfied cluster, curl rancher api by means of token auth, return 401.
create a token based on no scope, return 200.

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v2.2.2-2.2.5` UI: `v2.2.89` |
|Route|`workload`|

**Comment by satomic** [comment] 2019-08-23 09:02
this bug looks like existing in every Rancher Version (include the latest `stable` version `v2.2.8` or even the `master-head` version ). You can not select a `scope` when you add a new API key, only with `no scope`  can the API token work. otherwise you will get a `401` auth error from the Rancher Server.

**Comment by superseb** [comment] 2019-09-25 17:26
Duplicate of https://github.com/rancher/rancher/issues/18639

**Closed by superseb** 2019-09-25 17:26 UTC
