### ISSUE TITLE
calico-node keeps restarting in K8s cluster with canal networking

### ISSUE THREAD

**Issue by richyta** [rancher/rancher#27654] opened 2020-06-19 01:07 UTC
**What kind of request is this (question/bug/enhancement/feature request):**
bug

**Steps to reproduce (least amount of steps as possible):**
Delete pod for canal namespace and let a new one spin up.

**Result:**

![image](https://user-images.githubusercontent.com/39923752/85085907-1d1af600-b18e-11ea-9006-d78d5da167cc.png)

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): 2.4.4
- Installation option (single install/HA):
HA

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): onprem
- Machine type (cloud/VM/metal) and specifications (CPU/memory): VM
- Kubernetes version (use `kubectl version`): 
```
v1.17.6
``

- Docker version (use `docker version`):

```
docker://19.3.8
``

**Comment by izaac** [comment] 2020-06-19 20:58
Not able to reproduce, steps followed:

1. HA install `v2.4.3`
2. Deploy RKE/DO cluster with 1 etcd, 1 Control Plane 3 Worker nodes
    - k8s 1.17.5-rancher1-1 
3. Upgrade Rancher with `helm v3` to `v2.4.4`
4. Wait until the upgrade is done and clusters healthy
5. Upgrade k8s of DO cluster to `v1.17.6-rancher2-1`
6. Wait for cluster to get in healthy active state.


The cluster was in healthy state then I tried deleting one of the calico-node container pods in in `canal` namespace of `kube-system` as described in the issue. 

The pods are re-deployed properly .

**Comment by richyta** [comment] 2020-06-19 21:08
When I went to upgrade k8s again to the latest update after  downgrading it was ok so not sure what the problem was.

**Comment by izaac** [comment] 2020-06-19 21:11
Ok we can't consistently reproduce the issue and the cluster recovered after a [second attempt](https://github.com/rancher/rancher/issues/27654#issuecomment-646861163).

Closing and will open a new one if there we find out proper steps to repro.

**Closed by izaac** 2020-06-19 21:11 UTC
