### ISSUE TITLE
Unable to install Prometheus Operator on Rancher 2.5.1 - Cluster Dashboard

### ISSUE THREAD

**Issue by preetam-patil** [rancher/rancher#29550] opened 2020-10-14 11:03 UTC
Unable to install Prometheus Operator on Rancher 2.5.1 - Cluster Dashboard

-- Rancher HA setup on AKS Clsuter (Control Center)
-- Rancher Customer Cluster - we are installing rancher-monitoring app in this cluster from Dashboard

It seems it fails to create Prometheus pods by default

attached logs 

[helm-operation-fkcp2_undefined.log](https://github.com/rancher/dashboard/files/5377635/helm-operation-fkcp2_undefined.log)

**Comment by aiyengar2** [comment] 2020-10-15 20:43
@preetam-patil is this a k8s 1.16 cluster? logs are identical to https://github.com/rancher/rancher/issues/29395

**Comment by aiyengar2** [comment] 2020-10-15 20:49
The quick fix is simple and just involves changing the default `values.yaml`. Replace [`prometheus.prometheusSpec.volumes.items`](https://github.com/rancher/charts/blob/1d17a5bb6767f6468815b005b688fb73f7baa228/charts/rancher-monitoring/values.yaml#L2462-L2465) entirely with [`prometheus.prometheusSpec.volumes.defaultMode=438`](https://github.com/rancher/charts/pull/784/files#diff-f02c7f63c56c13b571b4fb39e83a7fd2b9e631fd29ffc36ce72d176e317e5859R2697) and it should work as expected in 2.5.1 as well.

The root cause is described in https://github.com/rancher/charts/pull/784.

**Comment by aiyengar2** [comment] 2020-11-05 01:31
Closing this out in favor of https://github.com/rancher/rancher/issues/29395. Please open a new ticket with more details if you are still encountering this issue @preetam-patil .

**Closed by aiyengar2** 2020-11-05 01:31 UTC
Labels: [zube]: Need Info
