### ISSUE TITLE
Rancher catalog fails to load

### ISSUE THREAD

**Issue by pyle** [rancher/rancher#2617] opened 2015-11-09 09:49 UTC
Rancher catalog page was loading fine but after a reboot of the server it stopped working.
It produced the following logs:
```
time="2015-11-09T09:36:58Z" level=info msg="Starting Rancher Catalog service" 
time="2015-11-09T09:36:58Z" level=info msg="Cloning the catalog from github url https://github.com/rancher/rancher-catalog.git" 
fatal: destination path './DATA' already exists and is not an empty directory.
time="2015-11-09T09:36:58Z" level=fatal msg="Failed to clone the catalog from githubexit status 128" 
```
It refers to directory `/var/lib/cattle/DATA`
To resolve issue I exec'd into the rancher server and ran a `git pull` in that directory.
After this and a refresh of the web interface the catalog loaded and worked correctly with no issue.

Possibly can be resolved by checking if folder exists and if it does to ignore and do a `git pull` instead.

**Comment by deniseschannon** [comment] 2015-11-09 21:56
Your error is similar to this forum thread. http://forums.rancher.com/t/failed-to-clone-the-catalog-from-githubexit-status-128/884/3

As indicated by @prachidamle, the rancher service actually removes the folder and clones the catalog when it restarts. 

Could it be a firewall issue as indicated in the forum thread?

**Comment by prachidamle** [comment] 2015-11-09 22:06
@pyle what version of rancher server are you running?

**Comment by pyle** [comment] 2015-11-10 08:28
@prachidamle I'm running Rancher v0.44.0

I've just done a reboot of the system that the Rancher server lies on and the catalog icon isn't appearing now at all.

**Comment by prachidamle** [comment] 2015-11-10 19:05
@pyle We tried to reproduce this but could not, we tried rebooting the rancher server VM and also rebooting the container. But dint see the git clone failure in either case.

How are you rebooting the server? Also are you using ssl for rancher server?

**Comment by pyle** [comment] 2015-11-10 22:50
@prachidamle Not using any ssl certificates for the server.
The server was rebooted normally with `sudo reboot`. 
I also rebooted just the server container  with a `docker restart <container ID>`.
 
I've just started a new server container with data from the old one (attached log).
(Before i created a new container git was not installed in the rancher/server container at all).
Seems the catalog is cloning properly now 
[catalog_log.txt](https://github.com/rancher/rancher/files/31321/catalog_log.txt)
```
time="2015-11-10T22:30:02Z" level=info msg="Starting Rancher Catalog service"
time="2015-11-10T22:30:02Z" level=info msg="Setting log level" logLevel=info
time="2015-11-10T22:30:02Z" level=info msg="Starting go-machine-service..." gitcommit=3c74782
time="2015-11-10T22:30:02Z" level=info msg="Cloning the catalog from github url https://github.com/rancher/rancher-catalog.git"
Cloning into './DATA'...
time="2015-11-10T22:30:02Z" level=info msg="Starting rancher-compose-executor" version=v0.5.0-rc2
```

The folder is in the container with the correct items.

I tried the site on my other machine and it seems the catalog icon is now loading.
Seems the browser was cahcing the interface causing the Catalog icon not to appear.
Seems to be resolved. now.

Thanks for the help :+1:

**Comment by prachidamle** [comment] 2015-11-10 23:19
@pyle Glad to know, will close this issue.

**Closed by prachidamle** 2015-11-10 23:19 UTC

**Comment by lmancilla** [comment] 2015-12-04 15:10
docker stop and docker run ...

Do not restart

**Comment by dnadave** [comment] 2016-03-24 17:32
I'm having this exact same problem.  It looks like the local clones of the repositories are being destroyed after each pull.  You alternate between getting an error (the directory pull is incomplete) and not having any catalogs available (the cloned directories are deleted).

**Comment by dnadave** [comment] 2016-03-24 17:33
For example:

`root@01b17f28e5a9:/# ls /var/lib/cattle/
DATA  keys.properties  logs
root@01b17f28e5a9:/# ls /var/lib/cattle/DATA/
community
root@01b17f28e5a9:/# ls /var/lib/cattle/DATA/community/
root@01b17f28e5a9:/# ls /var/lib/cattle/DATA/community/
root@01b17f28e5a9:/# ls /var/lib/cattle/DATA/          
community
root@01b17f28e5a9:/# cd /var/lib/cattle/DATA/  
root@01b17f28e5a9:/var/lib/cattle/DATA# ls
Axio
root@01b17f28e5a9:/var/lib/cattle/DATA# ls Axio/
root@01b17f28e5a9:/var/lib/cattle/DATA# cd Axio/
root@01b17f28e5a9:/var/lib/cattle/DATA/Axio# git pull
fatal: unable to access 'https://github.com/dnadave/rancher-catalog.git/': Could not resolve host: github.com
root@01b17f28e5a9:/var/lib/cattle/DATA/Axio# git pull
sh: 0: getcwd() failed: No such file or directory
fatal: Unable to read current working directory: No such file or directory
root@01b17f28e5a9:/var/lib/cattle/DATA/Axio# pwd
/var/lib/cattle/DATA/Axio
root@01b17f28e5a9:/var/lib/cattle/DATA/Axio# cd ..
root@01b17f28e5a9:/var/lib/cattle/DATA# ls
root@01b17f28e5a9:/var/lib/cattle/DATA# '
