### ISSUE TITLE
Failure activating local auth

### ISSUE THREAD

**Issue by markbastiaans** [rancher/rancher#2039] opened 2015-09-15 07:19 UTC
Great work on getting more authentication options for Rancher!

I have problems activating local auth. When pressing the "Enable Local Auth" button, it fails with a call to `token` and a `401 Unauthorized` error (inspected with Chrome DevTools). Also, after the error, I'm logged in as the user I specified in the local auth settings, and Rancher still prompts me to set up access control.

Rancher version: 0.37
Rancher host OS: CoreOS stable (766.3.0)
Browser: Chrome 46.0.2490.22 beta-m (64-bit) on Windows. No extensions enabled, other browsers produce the same result.

I can reproduce the problem; a clean copy of Rancher and going straight to setting up local auth produces the same results.

**Comment by deniseschannon** [comment] 2015-09-15 21:03
I've been unable to reproduce and have no issues turning it on.

Just to confirm, you're able to produce on a fresh install (no upgrades or links to existing DB)? 

Can you provide how you start rancher server?
Can you also provide the rancher server logs? http://docs.rancher.com/rancher/faqs/troubleshooting/ will provide you how to get the detailedd logs.

**Comment by deniseschannon** [comment] 2015-09-16 04:16
Any chance you have an external DB? We have a forums issue that seems similar to yours and we are thinking this might be a race condition. 

http://forums.rancher.com/t/will-not-authorize-local-access-control/472/2

**Comment by markbastiaans** [comment] 2015-09-16 06:33
Yes, able to reproduce with a fresh install and no external DB enabled. The only thing that I do differently is give the rancher server container a distinct name, like `rancher-server-0.37`.

**Comment by markbastiaans** [comment] 2015-09-16 06:42
Logs:

```
2015-09-16 06:37:08,600 DEBUG [:] [] [] [] [tp1503027776-16] [i.c.p.e.memory.InMemoryEventService ] Subscribing to [resource.change;account=5]
2015-09-16 06:37:41,110 DEBUG [:] [] [] [] [tp1503027776-16] [c.p.e.p.i.DefaultProcessInstanceImpl] Attempting to run process [credential.create:147] on resource [11]
2015-09-16 06:37:41,111 INFO  [7434eb41-f2f7-4c2b-90b9-63809a66846c:147] [credential:11] [credential.create] [] [tp1503027776-16] [c.p.e.p.i.DefaultProcessInstanceImpl] Changing state [requested->registering] on [credential:11]
2015-09-16 06:37:41,112 DEBUG [7434eb41-f2f7-4c2b-90b9-63809a66846c:147] [credential:11] [credential.create] [] [tp1503027776-16] [c.p.e.p.i.DefaultProcessInstanceImpl] Exiting with code [SCHEDULED] : SCHEDULED
2015-09-16 06:37:41,113 DEBUG [:] [] [] [] [tp1503027776-16] [c.p.e.p.i.DefaultProcessInstanceImpl] Exiting [SCHEDULED] process [credential.create:147] on resource [11]
2015-09-16 06:37:41,132 DEBUG [:] [] [] [] [cutorService-18] [c.p.e.p.i.DefaultProcessInstanceImpl] Attempting to run process [credential.create:147] on resource [11]
2015-09-16 06:37:41,191 DEBUG [a7dfa249-d01c-4c62-aecb-44533d83b70c:147] [credential:11] [credential.create->(AgentApiKeyCreate)] [] [cutorService-18] [c.p.e.p.i.DefaultProcessInstanceImpl] Running pre listener [AgentApiKeyCreate]
2015-09-16 06:37:41,191 DEBUG [a7dfa249-d01c-4c62-aecb-44533d83b70c:147] [credential:11] [credential.create->(AgentApiKeyCreate)] [] [cutorService-18] [c.p.e.p.i.DefaultProcessInstanceImpl] Finished pre listener [AgentApiKeyCreate]
2015-09-16 06:37:41,192 DEBUG [a7dfa249-d01c-4c62-aecb-44533d83b70c:147] [credential:11] [credential.create->(ApiKeyCreate)] [] [cutorService-18] [c.p.e.p.i.DefaultProcessInstanceImpl] Running pre listener [ApiKeyCreate]
2015-09-16 06:37:41,192 DEBUG [a7dfa249-d01c-4c62-aecb-44533d83b70c:147] [credential:11] [credential.create->(ApiKeyCreate)] [] [cutorService-18] [c.p.e.p.i.DefaultProcessInstanceImpl] Finished pre listener [ApiKeyCreate]
2015-09-16 06:37:41,192 DEBUG [a7dfa249-d01c-4c62-aecb-44533d83b70c:147] [credential:11] [credential.create->(RegisterTokenCreate)] [] [cutorService-18] [c.p.e.p.i.DefaultProcessInstanceImpl] Running pre listener [RegisterTokenCreate]
2015-09-16 06:37:41,192 DEBUG [a7dfa249-d01c-4c62-aecb-44533d83b70c:147] [credential:11] [credential.create->(RegisterTokenCreate)] [] [cutorService-18] [c.p.e.p.i.DefaultProcessInstanceImpl] Finished pre listener [RegisterTokenCreate]
2015-09-16 06:37:41,192 DEBUG [a7dfa249-d01c-4c62-aecb-44533d83b70c:147] [credential:11] [credential.create->(SshKeyCreate)] [] [cutorService-18] [c.p.e.p.i.DefaultProcessInstanceImpl] Running pre listener [SshKeyCreate]
2015-09-16 06:37:41,192 DEBUG [a7dfa249-d01c-4c62-aecb-44533d83b70c:147] [credential:11] [credential.create->(SshKeyCreate)] [] [cutorService-18] [c.p.e.p.i.DefaultProcessInstanceImpl] Finished pre listener [SshKeyCreate]
2015-09-16 06:37:41,194 DEBUG [a7dfa249-d01c-4c62-aecb-44533d83b70c:147] [credential:11] [credential.create->(ActivateByDefault)] [] [cutorService-18] [c.p.e.p.i.DefaultProcessInstanceImpl] Running post listener [ActivateByDefault]
2015-09-16 06:37:41,194 DEBUG [a7dfa249-d01c-4c62-aecb-44533d83b70c:147] [credential:11] [credential.create->(ActivateByDefault)] [] [cutorService-18] [c.p.e.p.i.DefaultProcessInstanceImpl] Finished post listener [ActivateByDefault]
2015-09-16 06:37:41,200 INFO  [9308c91f-2d9d-4b31-b21b-f85955d8521b:147] [credential:11] [credential.activate] [] [cutorService-18] [c.p.e.p.i.DefaultProcessInstanceImpl] Changing state [registering->activating] on [credential:11]
2015-09-16 06:37:41,206 INFO  [9308c91f-2d9d-4b31-b21b-f85955d8521b:147] [credential:11] [credential.activate] [] [cutorService-18] [c.p.e.p.i.DefaultProcessInstanceImpl] Changing state [activating->active] on [credential:11]
2015-09-16 06:37:41,215 DEBUG [:] [] [] [] [cutorService-18] [c.p.e.p.i.DefaultProcessInstanceImpl] Exiting [DONE] process [credential.activate:147] on resource [11]
```

**Comment by deniseschannon** [comment] 2015-09-16 19:36
@markbastiaans I have finally been able to reproduce. Please see https://github.com/rancher/rancher/issues/2051

Basically, if you are using an account that already has an existing entry in our account table (we create some default users (admin, system, superadmin)) and had no hosts, local auth fails to do some linking in our backend DB, but if you click on the button again (with no changes to the user info), it should authenticate you and turn it on.

**Comment by deniseschannon** [comment] 2015-09-16 19:37
Let me know if it's the same bug and I can close this one. Thanks for reporting!

**Comment by deniseschannon** [comment] 2015-09-16 21:13
If the workarounds don't work for you, can you provide the information from the DB?

Can you provide some information from the database?

1. Exec into the rancher server database. On the host run `docker exec -it <server_container_id> bash`
2. Switch to mysql. `mysql`
3. Switch to cattle DB. `use cattle;`
4. Provide the following table information.
`select * from account;`
`select * from credential;`
`select * from setting;`

**Comment by slimadvies** [comment] 2015-09-17 09:50
I had the same problem. I hacked around it by manually changing the setting db values:
``` 
mysql> select * from setting;
+----+------------------------------+-------------------------------+
| id | name                         | value                         |
+----+------------------------------+-------------------------------+
|  1 | api.auth.provider.configured | localAuthConfig               |
|  2 | api.security.enabled         | true                          |
|  3 | api.auth.local.access.mode   | restricted                    |
```

Then I had to go to /static/login and login again.

then it works.

**Comment by markbastiaans** [comment] 2015-09-17 10:42
@deniseschannon it might be the same bug, but I can't seem to get authorization setup even after I click "Enable Local Auth" for the second time.

Database dumps from my latest try (with some hosts added after the fact, hashes / hostname removed):

```
mysql> select * from account;
+----+-----------------------+------------+-----------------------+-------------+----------+---------------------+---------+-------------+-----------------------------------+-------------+------------------+
| id | name                  | kind       | uuid                  | description | state    | created             | removed | remove_time | data                              | external_id | external_id_type |
+----+-----------------------+------------+-----------------------+-------------+----------+---------------------+---------+-------------+-----------------------------------+-------------+------------------+
|  1 |                       | admin      | admin                 | NULL        | active   | NULL                | NULL    | NULL        | {"fields":{"hasLoggedIn":true}}   | NULL        | NULL             |
|  2 | system                | system     | system                | NULL        | inactive | NULL                | NULL    | NULL        | NULL                              | NULL        | NULL             |
|  3 | superadmin            | superadmin | superadmin            | NULL        | inactive | NULL                | NULL    | NULL        | NULL                              | NULL        | NULL             |
|  4 | token                 | token      | token                 | NULL        | active   | 2015-09-15 06:54:18 | NULL    | NULL        | {}                                | NULL        | NULL             |
|  5 | Default               | project    | adminProject          | NULL        | active   | 2015-09-15 06:54:18 | NULL    | NULL        | {"fields":{"defaultNetworkId":5}} | NULL        | NULL             |
|  6 | machineServiceAccount | service    | machineServiceAccount | NULL        | active   | 2015-09-15 07:04:24 | NULL    | NULL        | {}                                | NULL        | NULL             |
|  7 | NULL                  | agent      | agentAccount1         | NULL        | active   | 2015-09-15 07:05:40 | NULL    | NULL        | {}                                | NULL        | NULL             |
|  8 | NULL                  | agent      | agentAccount2         | NULL        | active   | 2015-09-15 07:05:47 | NULL    | NULL        | {}                                | NULL        | NULL             |
|  9 | NULL                  | agent      | agentAccount3         | NULL        | active   | 2015-09-15 07:05:54 | NULL    | NULL        | {}                                | NULL        | NULL             |
| 10 | NULL                  | agent      | agentAccount4         | NULL        | active   | 2015-09-15 07:06:49 | NULL    | NULL        | {}                                | NULL        | NULL             |
| 11 | NULL                  | agent      | agentAccount5         | NULL        | active   | 2015-09-15 07:06:49 | NULL    | NULL        | {}                                | NULL        | NULL             |
| 12 | NULL                  | agent      | agentAccount6         | NULL        | active   | 2015-09-15 07:06:49 | NULL    | NULL        | {}                                | NULL        | NULL             |
+----+-----------------------+------------+-----------------------+-------------+----------+---------------------+---------+-------------+-----------------------------------+-------------+------------------+
12 rows in set (0.00 sec)
```

```
mysql> select * from credential;
+----+------+------------+-------------------+--------------------------------------+-------------+--------+---------------------+---------+-------------+------+----------------------+----------------------------------------------------------------------------------------------+-------------+
| id | name | account_id | kind              | uuid                                 | description | state  | created             | removed | remove_time | data | public_value         | secret_value                                                                                 | registry_id |
+----+------+------------+-------------------+--------------------------------------+-------------+--------+---------------------+---------+-------------+------+----------------------+----------------------------------------------------------------------------------------------+-------------+
|  1 | NULL |          5 | apiKey            | 642f113c-fa53-47b7-bd8e-18182777efb9 | NULL        | active | 2015-09-15 06:59:57 | NULL    | NULL        | {}   | 02C22B91DF6D7A7535B5 | SHA256:<HASH> |        NULL |
|  2 | NULL |          6 | agentApiKey       | aa6b2a70-bcf2-427a-9c95-a65ff2b7e22d | NULL        | active | 2015-09-15 07:04:24 | NULL    | NULL        | {}   | BF4E4793DDD80E31AC3A | ZQNfbbjXhvnpCiDn9zVbJbdTxihSsw1eh6BDghtE                                                     |        NULL |
|  3 | NULL |          5 | registrationToken | 48e922ff-089a-4172-aaab-ab2751458b8a | NULL        | active | 2015-09-15 07:04:25 | NULL    | NULL        | {}   | D74F910C11536CF44DB5 | tiD7bPDskuNwPo1e19omSAwTozpNaG29BD1f1aWg                                                     |        NULL |
|  4 | NULL |          7 | agentApiKey       | e63a538b-8957-40a8-813e-c7cb404c9017 | NULL        | active | 2015-09-15 07:05:40 | NULL    | NULL        | {}   | 5B0ED60B765B5D4E707F | 3uqiwgR2H1nqVYTg6h3oWharoYauWUA17Q4o6Y6z                                                     |        NULL |
|  5 | NULL |          8 | agentApiKey       | 26809f2e-9247-480e-badd-79c729d86d36 | NULL        | active | 2015-09-15 07:05:47 | NULL    | NULL        | {}   | 5EB738BD9222246FD13C | 9UcRNacTMV5RZz3pZ2awJdaeds7KfzmsShGxsg33                                                     |        NULL |
|  6 | NULL |          9 | agentApiKey       | cbb1715a-dd7a-492d-b7cf-20963c642ddf | NULL        | active | 2015-09-15 07:05:54 | NULL    | NULL        | {}   | 4C3E23193F82AED1241E | QVoDmqUNWed2XypzY7oH1mfsBeVAGAXQmUrVX1r4                                                     |        NULL |
|  7 | NULL |         10 | agentApiKey       | b2b9b585-a8dd-4710-898a-5cc2e644d780 | NULL        | active | 2015-09-15 07:06:49 | NULL    | NULL        | {}   | DDEBA2E4307144B0EEFE | CbLvtfEDRAh99KCSpgMGUctdCurf8u6gigsPouV2                                                     |        NULL |
|  8 | NULL |         12 | agentApiKey       | a7084547-5120-4068-a41b-fc7898d3089c | NULL        | active | 2015-09-15 07:06:49 | NULL    | NULL        | {}   | 66D88C1932314FCE1489 | t5EhpHNk5gK3ih2ihH3ouJt4kXRbmbP3HRCkP4s9                                                     |        NULL |
|  9 | NULL |         11 | agentApiKey       | d44d0510-3e30-4217-8255-00dff1bba476 | NULL        | active | 2015-09-15 07:06:49 | NULL    | NULL        | {}   | 7A703D5125CAD2FD325B | uocpKB5Kgveb2zrEr7vWSqMFnxXY44cCyJyx7AtP                                                     |        NULL |
| 10 | NULL |          6 | agentApiKey       | 11aaef17-3596-4183-811d-ab7c845e19a4 | NULL        | active | 2015-09-15 19:04:48 | NULL    | NULL        | {}   | 941EE475897931C1CE58 | ZheaiVhN8N7CYP4SwhwD2fWsYhMU8ovTmXMFX3hD                                                     |        NULL |
| 12 | NULL |          6 | agentApiKey       | 38de3970-78f1-43f6-b122-d56afa09bd3a | NULL        | active | 2015-09-16 07:05:08 | NULL    | NULL        | {}   | 6802AA7E36C999B9899D | ope31Tp1o2iyBE1VuxrdxbuJCXMSwBfyc6CX9aBH                                                     |        NULL |
| 14 | NULL |          6 | agentApiKey       | d3c1f203-a7c8-4d1b-9797-f27d10bbcbdd | NULL        | active | 2015-09-16 19:05:31 | NULL    | NULL        | {}   | 38E82FFA60DD5225A023 | fn6aDJd4aRirqX6uohGvyUwoN3AiSjCGzF2BrTxE                                                     |        NULL |
| 15 | NULL |          6 | agentApiKey       | c9feac9f-7df4-4cef-b540-d4c37b262791 | NULL        | active | 2015-09-17 07:05:47 | NULL    | NULL        | {}   | 0FA70C270A4A5399C753 | EoRMxqz3zjSC6u5bmS7CFW5V2zRtehuBeRM15Exp                                                     |        NULL |
| 21 | NULL |          1 | password          | d3cc4532-a80a-4e33-b71a-2aff45b7aa1c | NULL        | active | 2015-09-17 10:31:23 | NULL    | NULL        | {}   | admin                | SHA256:<HASH> |        NULL |
+----+------+------------+-------------------+--------------------------------------+-------------+--------+---------------------+---------+-------------+------+----------------------+----------------------------------------------------------------------------------------------+-------------+
14 rows in set (0.00 sec)
```

```
mysql> select * from setting;
+----+------------------------------+---------------------------------+
| id | name                         | value                           |
+----+------------------------------+---------------------------------+
|  1 | api.auth.provider.configured | localAuthConfig                 |
|  2 | api.host                     | http://<HOSTNAME>:8080 |
|  3 | api.security.enabled         | false                           |
|  4 | api.auth.local.access.mode   | unrestricted                    |
+----+------------------------------+---------------------------------+
4 rows in set (0.00 sec)
```

**Comment by deniseschannon** [comment] 2015-09-17 10:55
@markbastiaans Can you run the following SQL statements to get your localAuth working?

```
update setting set value="true" where name="api.security.enabled";
update account set external_id=21, external_id_type="rancher_id" where id=1;
```

Afterwards, you should be able to refresh the UI and login using your `admin` account. 

Note: There is some setting that is not triggering these to be automatically updated that is logged in #2051, but we will track the fixing of it in that issue.

**Comment by markbastiaans** [comment] 2015-09-17 11:43
I've fixed it as @slimadvies outlined. Changing the two settings and restarting the Rancher container worked for me.

**Closed** 2015-09-17 13:17 UTC
Labels: area/authentication, kind/bug
