### ISSUE TITLE
Port binding to 0.0.0.0 not working from Docker compose files

### ISSUE THREAD

**Issue by Dids** [rancher/rancher#6356] opened 2016-10-21 07:28 UTC
**Rancher Version:**
1.1.4

**Docker Version:**
1.12.2

**OS and where are the hosts located? (cloud, bare metal, etc):**
Both cloud and bare metal (self-hosted)

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
Single node

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle

**Steps to Reproduce:**
In `docker-compose.yml`, bind ports to IP's like so, just like you'd expect to be able to do:

```
ports:
  - 0.0.0.0:12345:12345/tcp
  - 0.0.0.0:12345:12345/udp
  - 0.0.0.0:12346:12346/tcp
```

**Results:** 
This is how they end up in Rancher instead:

```
ports:
  - 12345:12345/tcp
  - 12345:12345/udp
  - 12346:12346/tcp
```

**Expected:**
Since using the web UI to add `0.0.0.0:` prefixes to the ports works fine, I'd expect `docker-compose.yml` to work the same way. To reiterate, this is how they end up when done with the web UI:

```
ports:
- 0.0.0.0:12345:12345/tcp
- 0.0.0.0:12345:12345/udp
- 0.0.0.0:12346:12346/tcp
```

**Comment by deniseschannon** [comment] 2016-10-21 14:56
Duplicate of https://github.com/rancher/rancher/issues/5064

**Closed by deniseschannon** 2016-10-21 14:56 UTC

**Comment by Dids** [comment] 2016-10-21 14:57
Thanks! Didn't find an existing issue, but sort of glad it already exists. :)
