### ISSUE TITLE
[BUG->RFE] Issues Encountered During Graceful Reboot of vSphere Windows Nodes

### ISSUE THREAD

**Issue by HarrisonWAffel** [rancher/rancher#42458] opened 2023-08-17 16:22 UTC
**Rancher Server Setup**
- Rancher version: n/a
- Installation option (Docker install/Helm Chart): n/a
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): RKE2 with Windows Worker
- Proxy/Cert Details:

**Information about the Cluster**
- Kubernetes version: reported v1.24.4, partially fixed on newer versions
- Cluster Type (Local/Downstream): Downstream, custom or vSphere node provisioned 

**User Information**
- What is the role of the user logged in? (Admin/Cluster Owner/Cluster Member/Project Owner/Project Member/Custom)
  - If custom, define the set of permissions: n/a

**Describe the bug**
When restarting windows nodes in the vSphere using using the graceful 'restart guest OS' button, Rancher UI may report a failed plan and the node may appear unavailable. In some cases the node will recover, however the failed plan will keep the node stuck in a failure state in the Rancher UI. This issue does not occur when running `restart-computer`, or restarting the node without using vmtools. 

**To Reproduce**
+ Provision a cluster on vSphere, with 1 linux cp+etcd node and 1 windows worker node 
+ In the vSphere UI, reboot the windows worker node using the 'Restart guest OS' option
+ occasionally,  the Rancher UI will report a failure to apply a plan, and the node will be unavailable 

**Result**
the node reports a failed plan and is not usable / responsive from the Rancher UI. In certain cases, the node may recover and be operable, however Rancher will still mark it as 'failed' due to the initial plan failure. 

**Expected Result**
The worker node comes back online after the graceful reboot and is usable

**Additional context**
This issue was partially addressed through the work done for ticket https://github.com/rancher/rancher/issues/39658, however the solution ran into unexpected regressions and had to be reverted in the most recent versions of RKE2. A new solution needs to be found which will not impact upgradability of the cluster. 

SURE-6791

**Comment by Sahota1225** [comment] 2023-09-27 18:43
moving this issue to the 2.8.0 backlog and will reevaluate the priority based on Harrison's capacity.

**Comment by slickwarren** [comment] 2024-01-09 21:55
High Level Test Plan:
* deploy windows cluster via vsphere node driver, then update the cluster
* deploy rancher 2.8.0 with windows downstream cluster -> upgrade to latest rancher version -> upgrade windows cluster
* `restart guest OS` for windows node -> wait for node to come back to active state
  * observe node is gracefully rebooted through vsphere UI rather than forced

potential other test areas:
* deploy a windows cluster with gracefulShutdownTimeout set on windows pools, delete node through UI and observe graceful shutdown through vsphere


supporting automation: 
* https://github.com/rancher/shepherd/pull/6 -> enable gracefulShutdownTimeout via automation, enhancements to vsphere automation in general
* tests for ^ https://github.com/rancher/rancher/pull/43775
* TODO: automate reboot node option : https://github.com/rancher/qa-tasks/issues/1098

**Comment by HarrisonWAffel** [comment] 2024-02-22 15:29
This issue may be resolved now that https://github.com/rancher/rke2/issues/2204 has been validated in RKE2. This should be retested once RKE2 feb patches are available

**Comment by slickwarren** [comment] 2024-03-21 17:44
tested on v2.8.3-rc5, I was still able to reproduce this issue. It appears that when the node is rebooted, the DNS name in vsphere is reset. This likely has something to do with the node not being able to reconnect to rancher, but I'm not 100% sure. 

![Screenshot from 2024-03-21 10-24-20](https://github.com/rancher/rancher/assets/16691014/9abc061a-f31d-42d8-bc26-ae73e29cddff)
![Screenshot from 2024-03-21 10-24-10](https://github.com/rancher/rancher/assets/16691014/7f7407f1-5d88-4023-9fd0-657eca1b37bf)

**Comment by snasovich** [comment] 2024-05-02 19:49
Talked with @HarrisonWAffel and to properly address it we will need to essentially implement a new feature to allow for a configurable delay.

**Comment by HarrisonWAffel** [comment] 2024-10-18 14:52
This issue can now be _partially_ tested on 2.10. Some aspects of the changes (such as the new environment variables delivered via the planner which address https://github.com/rancher/rancher/issues/45386 and https://github.com/rancher/rancher/issues/45385) will not be impactful unless you are running the October patches of rke2, which contain additional stability enhancements to the system-agent-installer-rke2 which are applicable to all cloud providers, including vSphere. The updates to Ranchers planner can be tested on vSphere without those changes, as well as setting the `CATTLE_ENABLE_WINS_DELAYED_START` agent environment variable during initial provisioning.

**Comment by markusewalker** [comment] 2024-10-18 23:54
Validated that this is addressed on `head` https://github.com/rancher/rancher/commit/f1aa9fb594e5b14578aff1cd5ddd2064be06eab1. The results have been recorded in Qase run /RM 2552. Here are the scenarios that were tested:

**ENVIRONMENT DETAILS**
- Rancher install: Helm
- Rancher version: `head` https://github.com/rancher/rancher/commit/f1aa9fb594e5b14578aff1cd5ddd2064be06eab1

**TEST RESULTS**
|#|Scenario|Result
|---|---|---|
|1|[Fresh install] Perform graceful restart guest OS on Windows nodes in downstream node driver cluster|
|2|[Fresh install] Run `Restart-Computer` command on Windows nodes in downstream node driver cluster|
|3|[Fresh install] Deploy Windows node driver cluster with parameter `gracefulShutdownTimeout` defined|
|4|[Fresh install] Replace Windows nodes and perform graceful restart guest OS|
|5|[Fresh install] Replace Windows nodes and run `Restart-Computer` command|
|6|[Upgraded Rancher] Perform graceful restart guest OS on Windows nodes in downstream node driver cluster|
|7|[Upgraded Rancher] Run `Restart-Computer` command on Windows nodes in downstream node driver cluster|
|8|[Upgraded Rancher] Deploy Windows node driver cluster with parameter `gracefulShutdownTimeout` defined|
|9|[Upgraded Rancher] Replace Windows nodes and perform graceful restart guest OS|
|10|[Upgraded Rancher] Replace Windows nodes and run `Restart-Computer` command|
|11|[Upgraded Rancher] Deploy Windows node driver cluster with environment variable `CATTLE_ENABLE_WINS_DELAYED_START`|
|12|[Upgraded Rancher] Deploy Windows node driver cluster with environment variable `CATTLE_ENABLE_WINS_SERVICE_DEPENDENCY`|
|13[Upgraded Rancher] |Deploy Windows node driver cluster with environment variables `CATTLE_ENABLE_WINS_DELAYED_START` and  `CATTLE_ENABLE_WINS_SERVICE_DEPENDENCY`|

@HarrisonWAffel let's discuss this further on Monday, but I took off custom clusters for now. I root caused the networking issue we discussed offline and ultimately this comes down to templates we have. I will keep this open so we can discuss options.

**Closed** 2024-10-21 16:08 UTC
Labels: kind/bug, kind/enhancement, internal, area/windows, QA/S, team/hostbusters, status/reopened

**Comment by HarrisonWAffel** [comment] 2024-11-11 15:28
For the release notes: 

`2.10.0` includes changes to how Windows nodes behave post node reboot, as well as provides two new settings to control how Windows services created by Rancher behave on startup. 

Two new agent environment variables have been added for Windows nodes, `CATTLE_ENABLE_WINS_SERVICE_DEPENDENCY` and `CATTLE_ENABLE_WINS_DELAYED_START`. These changes can be configured in the Rancher UI, and will be respected by all nodes running `rancher-wins` version `v0.4.20` or greater.
+ `CATTLE_ENABLE_WINS_SERVICE_DEPENDENCY` defines a service dependency between rke2 and rancher-wins, ensuring rke2 will not start before rancher-wins.
+ `CATTLE_ENABLE_WINS_DELAYED_START` changes the start type of rancher-wins to `AUTOMATIC (DELAYED)`, ensuring it starts after other Windows services.

Additionally, Windows nodes will now attempt to execute plans multiple times if the initial application fails, up to 5 times. This change, as well as appropriate use of the above two agent environment variables, aims to address plan failures for Windows nodes after a node reboot.
