### ISSUE TITLE
Cluster monitoring stuck in installing state with templateversion not found error

### ISSUE THREAD

**Issue by laoshancun** [rancher/rancher#19206] opened 2019-03-27 09:34 UTC
**What kind of request is this (question/bug/enhancement/feature request):**
bug

**Steps to reproduce (least amount of steps as possible):**
upgrade rancher-ha from v2.1.7 to v2.2.0

**Result:**
![image](https://user-images.githubusercontent.com/4952748/55064583-30d3cb80-50b5-11e9-8513-212f976e1af9.png)
![image](https://user-images.githubusercontent.com/4952748/55065174-51e8ec00-50b6-11e9-912a-9223c8befc93.png)

**Other details that may be helpful:**
instance A
```log
E0327 08:46:54.797228 7 round_trippers.go:291] CancelRequest not implemented by *rest.tokenSourceTransport
E0327 08:46:54.797331 7 streamwatcher.go:109] Unable to decode an event from the watch stream: net/http: request canceled (Client.Timeout exceeded while reading body)
E0327 08:46:54.797361 7 round_trippers.go:291] CancelRequest not implemented by *rest.tokenSourceTransport
E0327 08:46:54.797433 7 streamwatcher.go:109] Unable to decode an event from the watch stream: net/http: request canceled (Client.Timeout exceeded while reading body)
W0327 08:49:45.017305 7 reflector.go:270] github.com/rancher/norman/controller/generic_controller.go:175: watch of *v1.Endpoints ended with: too old resource version: 469462021 (469483799)
W0327 09:01:29.032225 7 reflector.go:270] github.com/rancher/norman/controller/generic_controller.go:175: watch of *v1.Endpoints ended with: too old resource version: 469529654 (469559088)
2019/03/27 09:05:02 [ERROR] Failed to construct object on output: info=InvalidFormat 422: cpu=InvalidFormat 422: count=InvalidFormat 422: strconv.ParseInt: parsing "1k": invalid syntax
E0327 09:07:15.363290 7 round_trippers.go:291] CancelRequest not implemented by *rest.tokenSourceTransport
E0327 09:07:15.363290 7 round_trippers.go:291] CancelRequest not implemented by *rest.tokenSourceTransport
E0327 09:07:15.363290 7 round_trippers.go:291] CancelRequest not implemented by *rest.tokenSourceTransport
E0327 09:07:15.363358 7 round_trippers.go:291] CancelRequest not implemented by *rest.tokenSourceTransport
E0327 09:07:15.363448 7 streamwatcher.go:109] Unable to decode an event from the watch stream: net/http: request canceled (Client.Timeout exceeded while reading body)
E0327 09:07:15.363468 7 streamwatcher.go:109] Unable to decode an event from the watch stream: net/http: request canceled (Client.Timeout exceeded while reading body)
E0327 09:07:15.363452 7 streamwatcher.go:109] Unable to decode an event from the watch stream: net/http: request canceled (Client.Timeout exceeded while reading body)
E0327 09:07:15.363452 7 streamwatcher.go:109] Unable to decode an event from the watch stream: net/http: request canceled (Client.Timeout exceeded while reading body)
E0327 09:07:15.363505 7 round_trippers.go:291] CancelRequest not implemented by *rest.tokenSourceTransport
```
instance B
```log
2019/03/27 09:30:43 [ERROR] AppController p-rj7s9/cluster-monitoring [helm-controller] failed with : catalogtemplateversions.management.cattle.io "system-library-rancher-monitoring-0.0.2" not found
2019/03/27 09:30:43 [ERROR] Failed to construct object on output: info=InvalidFormat 422: cpu=InvalidFormat 422: count=InvalidFormat 422: strconv.ParseInt: parsing "1k": invalid syntax
2019/03/27 09:30:43 [ERROR] AppController p-rj7s9/cluster-monitoring [helm-controller] failed with : catalogtemplateversions.management.cattle.io "system-library-rancher-monitoring-0.0.2" not found
2019/03/27 09:30:43 [ERROR] AppController p-rj7s9/cluster-monitoring [helm-controller] failed with : catalogtemplateversions.management.cattle.io "system-library-rancher-monitoring-0.0.2" not found
2019/03/27 09:30:43 [INFO] Catalog sync done. 40 templates created, 0 templates updated, 0 templates deleted
2019/03/27 09:30:43 [ERROR] AppController p-rj7s9/cluster-monitoring [helm-controller] failed with : catalogtemplateversions.management.cattle.io "system-library-rancher-monitoring-0.0.2" not found
2019/03/27 09:30:43 [ERROR] CatalogController aliyun [catalog] failed with : failed to update templates. Multiple error occurred: [failed to create template aliyun-kafka: namespaces "cattle-global-data" not found failed to create template aliyun-ack-knative-serving: namespaces "cattle-global-data" not found failed to create template aliyun-ceph: namespaces "cattle-global-data" not found failed to create template aliyun-ack-knative-build: namespaces "cattle-global-data" not found failed to create template aliyun-ack-springcloud-turbine: namespaces "cattle-global-data" not found failed to create template aliyun-ack-tensorflow-dev: namespaces "cattle-global-data" not found failed to create template aliyun-etcd: namespaces "cattle-global-data" not found failed to create template aliyun-exposecontroller: namespaces "cattle-global-data" not found failed to create template aliyun-ack-arms-pilot: namespaces "cattle-global-data" not found failed to create template aliyun-ack-istio: namespaces "cattle-global-data" not found failed to create template aliyun-nodered: namespaces "cattle-global-data" not found failed to create template aliyun-seldon-core: namespaces "cattle-global-data" not found failed to create template aliyun-jenkins-x-platform: namespaces "cattle-global-data" not found failed to create template aliyun-mysql-broker: namespaces "cattle-global-data" not found failed to create template aliyun-mariadb-broker: namespaces "cattle-global-data" not found failed to create template aliyun-ack-springcloud-configserver: namespaces "cattle-global-data" not found failed to create template aliyun-ack-springcloud-eureka: namespaces "cattle-global-data" not found failed to create template aliyun-ack-knative-sources: namespaces "cattle-global-data" not found failed to create template aliyun-ack-openmpi: namespaces "cattle-global-data" not found failed to create template aliyun-ack-tensorflow-serving: namespaces "cattle-global-data" not found failed to create template aliyun-catalog: namespaces
"cattle-global-data" not found failed to create template aliyun-glusterfs: namespaces "cattle-global-data" not found failed to create template aliyun-ack-consul: namespaces "cattle-global-data" not found failed to create template aliyun-ack-hyperledger-fabric: namespaces "cattle-global-data" not found failed to create template aliyun-zookeeper: namespaces "cattle-global-data" not found failed to create template aliyun-mysqlha: namespaces "cattle-global-data" not found failed to create template aliyun-rabbitmq-broker: namespaces "cattle-global-data" not found failed to create template aliyun-ack-tensorflow-training: namespaces "cattle-global-data" not found failed to create template aliyun-elasticsearch: namespaces "cattle-global-data" not found failed to create template aliyun-seldon-core-crd: namespaces "cattle-global-data" not found failed to create template aliyun-spark-broker: namespaces "cattle-global-data" not found failed to create template aliyun-vault: namespaces "cattle-global-data" not found failed to create template aliyun-ack-knative-init: namespaces "cattle-global-data" not found failed to create template aliyun-ack-springcloud-zipkin: namespaces "cattle-global-data" not found failed to create template aliyun-ack-springcloud-hystrix: namespaces "cattle-global-data" not found failed to create template aliyun-ack-springcloud-zuul: namespaces "cattle-global-data" not found failed to create template aliyun-redis-ha: namespaces "cattle-global-data" not found failed to create template aliyun-spark-oss: namespaces "cattle-global-data" not found failed to create template aliyun-ack-istio-remote: namespaces "cattle-global-data" not found failed to create template aliyun-ack-knative-eventing: namespaces "cattle-global-data" not found]
2019/03/27 09:30:43 [ERROR] AppController p-rj7s9/cluster-monitoring [helm-controller] failed with : catalogtemplateversions.management.cattle.io "system-library-rancher-monitoring-0.0.2" not found
2019/03/27 09:30:43 [ERROR] AppController p-rj7s9/cluster-monitoring [helm-controller] failed with : catalogtemplateversions.management.cattle.io "system-library-rancher-monitoring-0.0.2" not found
2019/03/27 09:30:43 [ERROR] AppController p-rj7s9/cluster-monitoring [helm-controller] failed with : catalogtemplateversions.management.cattle.io "system-library-rancher-monitoring-0.0.2" not found
2019/03/27 09:30:43 [ERROR] AppController p-rj7s9/cluster-monitoring [helm-controller] failed with : catalogtemplateversions.management.cattle.io "system-library-rancher-monitoring-0.0.2" not found
2019/03/27 09:30:43 [ERROR] AppController p-rj7s9/cluster-monitoring [helm-controller] failed with : catalogtemplateversions.management.cattle.io "system-library-rancher-monitoring-0.0.2" not found
2019/03/27 09:30:44 [ERROR] AppController p-rj7s9/cluster-monitoring [helm-controller] failed with : catalogtemplateversions.management.cattle.io "system-library-rancher-monitoring-0.0.2" not found
2019/03/27 09:30:44 [ERROR] AppController p-rj7s9/cluster-monitoring [helm-controller] failed with : catalogtemplateversions.management.cattle.io "system-library-rancher-monitoring-0.0.2" not found
2019/03/27 09:30:44 [INFO] Updating global catalog aliyun
```

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI):v2.2.0
- Installation option (single install/HA): HA

**Comment by loganhz** [comment] 2019-03-27 10:48
What

**Comment by davidnuzik** [comment] 2019-03-27 18:04
Version: v2.1.7 -> v2.2.0 Upgrade (HA setup)

No steps to reproduce were provided, but I did my best to test this from a QA perspective.

For what it's worth, and it may not be related, but on v2.1.7 I constantly get errors in the logs when trying to add the aliyun catalog show in the screenshot. It will never stop refreshing. When I review logs this is happening in a loop:
```
[rancher-b5756ff49-bn2pw] 2019/03/27 17:56:08 [INFO] Updating catalog aliyun 
[rancher-b5756ff49-bn2pw] 2019/03/27 17:56:08 [INFO] Catalog sync done. 0 templates created, 2 templates updated, 0 templates deleted 
[rancher-b5756ff49-bn2pw] 2019/03/27 17:56:08 [ERROR] CatalogController aliyun [catalog] failed with : failed to update templates. Multiple error occurred: [TemplateVersion.management.cattle.io "aliyun-seldon-core-crd-0.2.4-SNAPSHOT" is invalid: metadata.name: Invalid value: "aliyun-seldon-core-crd-0.2.4-SNAPSHOT": a DNS-1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*') TemplateVersion.management.cattle.io "aliyun-seldon-core-0.2.4-SNAPSHOT" is invalid: metadata.name: Invalid value: "aliyun-seldon-core-0.2.4-SNAPSHOT": a DNS-1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*')] 
```

I can still see the apps when I launch the catalog though in v2.1.7.

I upgraded my v2.1.7 HA to v2.2.0 and _successfully reproduced_ the issue described. I see essentially the same content in logs as well. cc: @sangeethah

**Comment by davidnuzik** [comment] 2019-03-27 18:06
As a workaround, when I click the refresh button on the Launch Apps page everything now shows up.
![image](https://user-images.githubusercontent.com/45179589/55101031-6ca06e00-5080-11e9-9707-f96c23d612ea.png)

**Comment by laoshancun** [comment] 2019-03-28 01:11
@davidnuzik Yes,it is shows up,but i did nothing.

**Comment by laoshancun** [comment] 2019-03-28 01:15
By the way,`Cluster Monitoring` and `Cluster Alert` stuck on installing.
The log says `failed with : catalogtemplateversions.management.cattle.io "system-library-rancher-monitoring-0.0.2" not found`.
Should i create an another issue?

**Comment by davidnuzik** [comment] 2019-03-28 18:59
We are looking into the issue further. We'll create an issue for that or if we need more info let you know. Thanks for reporting.

**Comment by cjellick** [comment] 2019-03-28 19:13
@laoshancun are you in an airgap setup by chance?

**Comment by laoshancun** [comment] 2019-03-29 02:47
@cjellick Rancher server has full Internet access.

**Comment by mrajashree** [comment] 2019-03-29 17:44
@laoshancun  I upgraded Rancher from 2.1.7 to 2.2.0 and enabled cluster monitoring and I cannot reproduce this, don't have these errors in my logs. Are there any other steps you took to repro?

**Comment by alena1108** [comment] 2019-03-29 17:55
@mrajashree can you check the code to see what might cause cattle-global-data **not** being created? 

Noticed this error `failed to create template aliyun-kafka: namespaces "cattle-global-data" not found` in the original comment's log. See if that might cause a follow up catalog not found error.

**Comment by laoshancun** [comment] 2019-03-30 03:16
@mrajashree Let me think,i have created a global dns provider and global dns entry,and then remove it.

**Comment by mrajashree** [comment] 2019-03-31 22:41
@laoshancun From your previous comments, you're able to view all templates am I right? The only issue was the error in the logs? Can you confirm if those errors keep showing repeatedly or you saw them only initially?

**Comment by laoshancun** [comment] 2019-04-01 01:47
I can see all templates,but `cluster-monitoring` still stuck with installing.
![image](https://user-images.githubusercontent.com/4952748/55298881-c4651d80-5462-11e9-8c3f-8ae553310063.png)

```log
2019/04/01 01:43:04 [ERROR] AppController p-rj7s9/cluster-monitoring [helm-controller] failed with : catalogtemplateversions.management.cattle.io "system-library-rancher-monitoring-0.0.2" not found
2019/04/01 01:43:04 [ERROR] AppController p-rj7s9/cluster-monitoring [helm-controller] failed with : catalogtemplateversions.management.cattle.io "system-library-rancher-monitoring-0.0.2" not found
```

**Comment by mrajashree** [comment] 2019-04-01 17:36
@laoshancun Can you exec into your rancher server container and run `kubectl get catalogtemplateversions system-library-rancher-monitoring-0.0.2 -n cattle-global-data` and share the output

**Comment by mrajashree** [comment] 2019-04-01 20:02
Changing the name of this issue since the original issue no longer exits

**Comment by mrajashree** [comment] 2019-04-01 20:35
@davidnuzik @laoshancun said the templates showed up without doing anything, and I thought you reproduced the error in logs. 
I just now read your comment saying you refreshed it, could have been some UI delay since the templates do show up. I'll leave it up to you and @sangeethah to change the title or open a new issue for that

**Comment by davidnuzik** [comment] 2019-04-01 20:52
Created issue #19301 to track the apps not showing up in catalog post upgrade (until you manually refresh catalog).

**Comment by laoshancun** [comment] 2019-04-02 06:14
@mrajashree I have upgraded rancher to v2.2.1,it was not working too.
The resource type catalogtemplateversions does not exist.
```
root@Laoshancun:~# kubectl get catalogtemplateversions system-library-rancher-monitoring-0.0.2 -n cattle-global-data
error: the server doesn't have a resource type "catalogtemplateversions"
```

**Comment by mrajashree** [comment] 2019-04-02 15:21
@laoshancun And how about this: `In this system project from your local cluster, can you go to Namespaces and see if cattle-global-data is created?`

Are you on rancher users slack channel? we could debug this faster there, couldn't find you by your Github username

**Comment by laoshancun** [comment] 2019-04-03 01:37
@mrajashree 
this cluster is a managed Kubernetes imported from Alibaba Cloud, and version is `v1.11.5`.
1. There is no `cattle-global-data` in system project.
2. The Rancher server is upgrade from v2.1.7,not from a alpha or rc version.
3. The kubeconfig file is download from rancher server.
I have created an account on slack with name laoshancun,but cannot find any channel with name rancher.

**Comment by mrajashree** [comment] 2019-04-04 00:30
@laoshancun I think you're not checking the `local` cluster's system project for the global namespace.
Also I'm not sure I follow what you said about the slack account, but you can join this users channel https://rancher-users.slack.com/

**Comment by laoshancun** [comment] 2019-04-04 01:31
@mrajashree 
There is only one cluster on rancher server,but cluster name is not `local`.Is there any problem if the cluster name is not `local`?
The slack workspace require administrator's invatation.

**Comment by mrajashree** [comment] 2019-04-08 18:22
@laoshancun To confirm again, this is an HA setup right? had you disabled the local cluster during installation by passing `--set addLocal="false"` to the helm install options?
Also I'm not sure why you're having problems joining slack users channel, that link should be enough, but can you provide your email address so we can send you an invite?

**Comment by laoshancun** [comment] 2019-04-09 03:39
laoshancun@gmail.com

**Comment by laoshancun** [comment] 2019-04-09 03:48
@mrajashree 
Rancher server is HA setup without `--set addLocal="false"`,and Rancher running on the same cluster.

**Comment by mrajashree** [comment] 2019-04-09 04:52
@laoshancun I've sent you the slack invite, please check it and join.
Also, if you did not set it to false explicitly, the local cluster should have been there. Did you have it prior to upgrade to 2.2?

**Comment by mrajashree** [comment] 2019-04-09 18:07
@alena1108 From further discussion with @laoshancun on slack:
1. The underlying cluster used for rancher HA setup is not supported (We support RKE and he's using ACK from Alibaba cloud)
2. Prior to upgrade to 2.2, the rancher server was removed by mistake, and recovered only partially because local cluster went missing after that.
The overall state of this setup doesn't seem right, that's why we haven't been able to repro, maybe starting afresh with 2.2 is the best option?

**Comment by alena1108** [comment] 2019-04-09 18:11
Given that the set of steps described in https://github.com/rancher/rancher/issues/19206#issuecomment-481367971, something we don't support - running rancher on ali cloud, rancher cleanup being done only partially - I'm going to close the issue.

@laoshancun can you try running fresh rancher 2.2, and see if you encounter the issue? Please reopen the bug if you still see it.

**Closed by alena1108** 2019-04-09 18:11 UTC
Labels: kind/bug, status/blocker, status/triaged, team/ca

**Comment by laoshancun** [comment] 2019-04-10 02:36
OK,It's seems that i have to create new one.
THX,@alena1108 @mrajashree

**Comment by lanmingle** [comment] 2019-05-07 14:34
我用腾讯云：	Failed to ensure catalog "catalog://?catalog=system-library&template=rancher-monitoring&version=0.0.2": failed to find catalog by ID "catalog://?catalog=system-library&template=rancher-monitoring&version=0.0.2": catalogtemplateversions.management.cattle.io "system-library-rancher-monitoring-0.0.2" not found

**Comment by laoshancun** [comment] 2019-05-08 01:19
@lanmingle Is there any k8s management tools better than Rancher?
