### ISSUE TITLE
8080 port is inaccessible

### ISSUE THREAD

**Issue by yangjia517** [rancher/rancher#10395] opened 2017-11-24 09:04 UTC
Hi：

Today I was at the rancher stack configuration, and add a load balancing configuration when the load balanced port mapping becomes 8080, resulting in UI cannot access, I checked the docker host, port 8080 is still IPtable, but can not access, do not know what causes.

Docker version 17.03.1-ce
Rancher v1.6.11
Cattle v0.183.30
User interface v1.6.30
Rancher CLI v0.6.5
Rancher Compose v0.12.5

Linux:ubuntu14.04 3.13.0-123-generic

**Comment by yangjia517** [comment] 2017-11-24 09:06
Is the external port of load balancing configuration not 8080? How do you call FW to control it?

**Comment by superseb** [comment] 2017-11-24 12:10
Can you share the stack definitions and steps to reproduce? If the host does not have port 8080 available, the scheduler will not schedule it.

**Comment by yangjia517** [comment] 2017-11-27 02:27
1.This is the UI port of the docker host rancher:
root@vhost31:~# netstat -ntlp |grep 8080
tcp6       0      0 :::8080                 :::*                    LISTEN      93808/docker-proxy

2.The load balancing method is used, and the 8080 port is used:
![qq 20171127101323](https://user-images.githubusercontent.com/33953118/33247856-163e71f8-d35c-11e7-9bfe-f6670f80d595.png)

My problem now is..:
If rancher's UI uses 8080 port access, I create load balancing with 8080 ports, and like you say, the program will not arrange it?
Why can't I visit UI? And the 8080 port Telnet of the docker host is passed, that is, it can not be accessed through filefox...

Thanks~

**Comment by ItsReddi** [comment] 2017-12-08 15:11
Well i have done that today by mistake also.
1. run rancher server on 8080
2. add rancher server as host itself
3. start any container on port 8080 -> external
4. rancher server will be broken

Well its obvious that binding a port twice will fail with errors.
But fixing the problem if you did the mistake is horrible.

1. You will not be able to access to rancher on any way because 8080 is blocked
2. hosts will loose connection
3. even if you restart docker, the problem is persistent, no container will start, the agents cannot connect
4. database backup restore will not have an effect

the only way to fix it was: (all other docker containers are stopped before via docker restart)
1. shutdown rancher server 
2. restore via db backup, luckily we are using mysql external db
3. delete rancher server and start it again

**Comment by Jefnull** [comment] 2018-08-11 03:10
This isn't the best solution, but I was able to resolve this by creating a duplicate container of the rancher-server bound to a different port, and then resolving the conflict, removing my new container and starting the original rancher-server

**Comment by loganhz** [comment] 2018-10-12 02:41
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.

**Closed by loganhz** 2018-10-12 02:41 UTC
Labels: area/loadbalancer, status/more-info, version/1.6
