### ISSUE TITLE
Add Keycloak as an auth provider 

### ISSUE THREAD

**Issue by deniseschannon** [rancher/rancher#14730] opened 2018-07-24 22:22 UTC

**Comment by tookko** [comment] 2018-07-30 08:22
Is this a duplicate of https://github.com/rancher/rancher/issues/10053 or integrating via a Keycloak specific protocol?

**Comment by alena1108** [comment] 2018-08-23 17:04
UI should be in as well

**Comment by carolynhu** [comment] 2018-08-31 20:47
@sangeethah groups related information updated in the set-up docs, please follow it to test group functionalities.

**Comment by tookko** [comment] 2018-09-03 20:29
Does this support SSO also in case login against Keycloak was done with OIDC, or only when it was done using SAML?

**Comment by carolynhu** [comment] 2018-09-03 20:37
@tookko We are currently only support SAML protocol.

**Comment by bmdepesa** [comment] 2018-09-12 22:13
rancher/rancher:master 9/12

Groups can be added to restricted access modes and function properly.

**Closed** 2018-09-14 03:44 UTC
Labels: area/authentication, kind/enhancement, status/resolved, status/to-test, version/2.0
