### ISSUE TITLE
Sporadic driver error during K8s upgrade: listen tcp 127.0.0.1:0: bind: address already in use

### ISSUE THREAD

**Issue by chrisreed87** [rancher/rancher#28360] opened 2020-08-12 16:04 UTC
**What kind of request is this (question/bug/enhancement/feature request):**
bug

**Steps to reproduce (least amount of steps as possible):**

Very similar issue to https://github.com/rancher/rancher/issues/19742

On two occasions now I've encountered separate customer issues where during a K8s upgrade, through the Rancher UI, the rolling upgrade will stall with this error:

`Error starting driver: failed retrieving port for driver: listen tcp 127.0.0.1:0: bind: address already in`
Getting stuck here: https://github.com/rancher/kontainer-engine/blob/65780a8839e471d3842580d5d9075ae9a3b70a02/service/service.go#L400

This issue causes the cluster controller inside Rancher to try to bind to a port that is already in use.
Some customers report that eventually it self heals and upgrade completes. The quick fix for this is to cycle the Rancher pods.

It's sporadic in that it doesn't appear to happen with each downstream cluster. The commonality I've seen with customers is this:

- Custom cluster
- Ubuntu 18.04
- K8s version < 1.118.x

**Result:**

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): v2.4.5
- Installation option (single install/HA): HA

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): Custom
- Machine type (cloud/VM/metal) and specifications (CPU/memory): cloud and VMware
- Kubernetes version (use `kubectl version`): 

```
v1.17.6 --> v1.18.6
```

- Docker version (use `docker version`):

```
(paste the output here)
```

gz#11024

gz#12126

**Comment by mattmattox** [comment] 2020-09-08 14:37
Workaround:
Kubernetes 1.15 and above
```
kubectl -n cattle-system rollout restart deployment rancher
```

Kubernetes 1.14 and below
```
kubectl -n cattle-system set env deployment --env="LAST_MANUAL_RESTART=$(date +%s)" rancher
```

Verification:
```
kubectl -n cattle-system get pods -l app=rancher    <<== Wait for all pods to be recycled
```

**Comment by izaac** [comment] 2020-11-10 20:50
Rancher `v2.4.5` HA local cluster with RKE k8s `v1.18.3`

Downstream cluster:

- Custom with 3 EC2 instances (`t3.medium`) all roles (etcd/worker/control plane)
- Ubuntu 18.04
- k8s `v1.17.13-rancher1-2`

Upgrade from `v1.17.13-rancher1-2` to `1.18.10-rancher1-2` I did a couple of kubernetes upgrades with this same version combination without noticing anything in the rancher server logs.

I will try with v1.16.x and v1.15.x to v1.18.10 which are available in this Rancher version to see if I can reproduce.

**Comment by izaac** [comment] 2020-11-10 21:44
Rancher `v2.4.5` HA local cluster with RKE k8s `v1.18.3` (11/10/2020)

Downstream clusters:

- Custom with 3 EC2 instances (`t3.medium`) all roles (etcd/worker/control plane)
- Ubuntu 18.04
- k8s `v1.15.12-rancher2-3`

- Custom with 3 EC2 instances (`t3.medium`) all roles (etcd/worker/control plane)
- Ubuntu 18.04
- k8s `v1.16.15-rancher1-3`


Upgrading these clusters to `1.18.10-rancher1-2` I didn't notice anything in the rancher server logs. Upgrade was successful.

**Comment by deniseschannon** [comment] 2020-11-10 21:44
Note: this won't reproduce on a as is system. 

You need to somehow fill up all the ports to hit this error.

**Comment by izaac** [comment] 2020-11-10 23:19
@deniseschannon I will be trying a few times. I tried with a 20 nodes cluster upgrading to latest 1.18 as described [here](https://github.com/rancher/rancher/issues/28360#issuecomment-724958533).

3 etcd, 3 control plane, 14 workers.

**Comment by izaac** [comment] 2020-11-11 20:31
Rancher version `v2.4.5 (11/11/2020)` 

Single node Rancher server. 
Downstream Custom cluster k8s `v1.17.13-rancher1-2`. 2 control plane, 3 etcd, 50 workers.
Upgrade to k8s `v1.18.10-rancher1-2` I didn't notice the error in the Rancher server logs.

I will try now on an HA `v2.4.5` Rancher server.

**Comment by izaac** [comment] 2020-11-12 00:13
I tried in a 1 Control Plane, 3 etcd, 5 workers but now running a script to use all the control plane node’s ephemeral network ports and doing an upgrade at the same time. I still see the upgrade getting applied without issues. 

We might need to dig further to isolate the root cause.

**Comment by mattmattox** [comment] 2020-11-12 00:23
@izaac It looks like this is caused by golang bug [16691](https://github.com/golang/go/issues/16691)
Also, we found that rancher-machine uses the same bind to port 0 which causes this issue.
Example: We found a Rancher pod with 57k open ports due to node pools scaling up and down.

**Comment by izaac** [comment] 2020-11-12 19:25
I was able to reproduce the issue in Rancher `v2.4.5` (`t3a.xlarge`)
The easiest way to reproduce this is to bring up a Rancher single install.
Bring up a 1.17 or lower k8s version cluster or clusters.

Go into the Rancher docker container and exhaust the ephemeral ports by opening LISTEN connections.
Perform a k8s upgrade on the cluster (or on one of the clusters) to 1.18.

![Screen Shot 2020-11-12 at 12 14 14 PM](https://user-images.githubusercontent.com/27659/98985905-6f640700-24e1-11eb-84a1-e1e4559a57d7.png)


In this case the upgrade self recovered.

**Comment by PennyScissors** [comment] 2020-11-12 19:29
> I was able to reproduce the issue in Rancher `v2.4.5` (`t3a.xlarge`)
> The easiest way to reproduce this is to bring up a Rancher single install.
> Bring up a 1.17 or lower k8s version cluster or clusters.
> 
> Go into the Rancher docker container and exhaust the ephemeral ports by opening LISTEN connections.
> Perform a k8s upgrade on the cluster (or on one of the clusters) to 1.18.
> 
> ![Screen Shot 2020-11-12 at 12 14 14 PM](https://user-images.githubusercontent.com/27659/98985905-6f640700-24e1-11eb-84a1-e1e4559a57d7.png)
> 
> In this case the upgrade self recovered.

Based on this and some stress testing I did, I can conclude this problem is not how we use Go to assign a port, instead it's something taking all the connections the system can handle until ephemeral port starvation. When we bind to port 0, Go's `net.Listen` function used [here](https://github.com/rancher/kontainer-engine/blob/65780a8839e471d3842580d5d9075ae9a3b70a02/service/service.go#L401) will find an available port for us, but in the case no ports are available, it will throw the `listen tcp 127.0.0.1:0: bind: address already in use` error which to me is the correct behavior since it could take a really long time before a port is available.

Taking all that into consideration, we can shift our focus onto how the connections are being handled. 
@mattmattox We need data from the setups and netstat output (hopefully showing a high amount of connections) to investigate. Any chances you could get that for us?

@izaac Once we get some data from Matt, can we reproduce the scenario to confirm there is a problem with rancher-machine/upgrading, that results in a high amount of connections and no recovery?

**Comment by Oats87** [comment] 2020-11-19 22:13
We diagnosed an environment that was encountering errors like this to having the `telemetry` client running and holding "ESTABLISHED" connections against the Rancher API server.

`netstat -an` showed `50,000+` connections open between `localhost:<RandomPort>` and `localhost:443` and a `-plant` showed the `telemetry` client as the one holding the connections.

I think there may be some type of issue w/ the underlying api serving objects to the telemetry client that is causing the hang... Turning off the telemetry client (turning telemtry opt to `out` from `in`) fixed the hanging established connections.

**Comment by rawmind0** [comment] 2021-02-01 20:24
Confirmed @Oats87 diagnose. 

Telemetry client is not releasing nor reusing connections to Rancher API on every [`report()`](https://github.com/rancher/telemetry/blob/master/cmd/client.go#L164) execution, every 6h by default. Depending on the size of the system, telemetry client is doing a bunch of connections: 1 rancher API, 1 every cluster, 1 every project/cluster,... The number of connections is growing up until they are exhausted, generating `listen tcp 127.0.0.1:0: bind: address already in use errors.`.

As workaround, telemetry client may be killed at Rancher docker/pod to release connections. Rancher should restart telemetry client automatically.

Submitted PR https://github.com/rancher/telemetry/pull/47 to address the issue

To test it: 
1. access to rancher docker/pod
1. force telemetry `report()` execution: `curl -X POST http://localhost:8114/v1-telemetry/report`
1. check the number of telemetry connections: `netstat -natup |grep telemetry | wc -l`
1. force telemetry `report()` execution: `curl -X POST http://localhost:8114/v1-telemetry/report`
1. check the number of telemetry connections: `netstat -natup |grep telemetry | wc -l` . 

Telemetry connections should grow up on current version, but shouldn't grow up on patched version

**Comment by izaac** [comment] 2021-02-03 16:20
Rancher version `v2.5.5`
Docker install
4 single node clusters

Make sure metrics is checked during initial Rancher configuration. (`Allow collection of anonymous statistics`)
Install `net-tools` in the docker container.

Reproduced using the steps provided here https://github.com/rancher/rancher/issues/28360#issuecomment-771134043


Rancher version `v2.5-head`
Rancher version `master-head`

With same setup above I still see the connections count going up. 
I see the telemetry fix merged but do we need to update something in the Rancher repo too?

**Comment by rawmind0** [comment] 2021-02-03 16:49
@izaac , are you using the patched version of telemetry client??

**Comment by deniseschannon** [comment] 2021-02-03 17:01
@rawmind0 Have you updated Rancher to use the patched telemetry client?

**Comment by rawmind0** [comment] 2021-02-03 17:25
Updated telemetry version on Rancher [2.5](https://github.com/rancher/rancher/pull/31113) and [master](https://github.com/rancher/rancher/pull/31114)

**Comment by rawmind0** [comment] 2021-02-03 23:13
PR's merged at 2.5 and master

**Comment by izaac** [comment] 2021-02-04 00:18
Rancher version `master-head (02/03/2021)`  _54b3a755b_
 I was able to check this with the steps provided https://github.com/rancher/rancher/issues/28360#issuecomment-771134043 

I see the number of connections is kept steadily low even after multiple request to the report endpoint.
I also validated the /v1-telemetry endpoint was properly updated after adding clusters.

Still waiting for a build of 2.5-head to validate that branch.

**Comment by izaac** [comment] 2021-02-04 02:41
Rancher version `v2.5-head-head (02/03/2021)`  _c6cdf815a_
 I was able to check this with the steps provided https://github.com/rancher/rancher/issues/28360#issuecomment-771134043 

I see the number of connections is kept steadily low even after multiple request to the report endpoint.
I also validated the /v1-telemetry endpoint was properly updated after adding clusters.

**Closed by izaac** 2021-02-04 02:41 UTC
Labels: [zube]: QA Working, internal

**Comment by izaac** [comment] 2021-02-08 23:08
`TELEMETRY_VERSION=v0.5.14`

**Comment by krumware** [comment] 2021-03-25 00:16
for others: found this happening in 2.4.5, rancher-machine versions `rancher-machine version v0.15.0-rancher43, build f675ca21`.  `TELEMETRY_VERSION=v0.5.12` 

My symptoms were that my rancher-launched clusters were no longer able to provision new nodes on AWS, but it was still able to terminate nodes on AWS.
Enabled debugging via instructions here: https://rancher.com/docs/rancher/v2.x/en/troubleshooting/logging/
Connected to each of the nodes remotely and logged errors from the instance via `docker logs --since 20m [cid] | grep "create cmd"` to find the offending machine. This helped to find the actual `rancher-machine create` command being run. Copying the command used and adding a debug flag (`rancher-machine --debug create -d amazonec2 ... `) revealed the errors.

experienced errors mentioned
`() DBG | Error loading RPC server: listen tcp 127.0.0.1:0: bind: address already in use`
and
`dial tcp: missing address`

When I attempted to run the command on another machine, there was another `Error: No machine name specified`. Manually adding a name worked, unclear why it wasn't included in the original command via the debug output.

There was some memory pressure on the nodes, but don't think it was enough to corrupt anything unless something happened in the past few days.  Ultimately, restarting the offending node seemed to help. I did need to delete the nodes that were failing to provision once the node had completed restart.

I hope that helps someone else!
