### ISSUE TITLE
Add (Swarm-)Cluster to infastructure

### ISSUE THREAD

**Issue by pizzarabe** [rancher/rancher#3584] opened 2016-02-11 09:46 UTC
I would like to have the option to add pre configured Docker Swarm clusters to Rancher. So we would be able to use Docker Swarm as the main administration interface and use rancher as the ui (we would also be able to use other software simultaneously with the same docker swarm cluster over the same interface (like: openstack magnum,...).

As a administrator i just have to add more docker nodes to my swarm cluster to scale my rancher infrastructure.

**Comment by withinboredom** [comment] 2016-02-12 02:03
+1

**Comment by yesbut** [comment] 2016-02-25 04:13
+1

**Comment by CBR09** [comment] 2016-02-25 06:53
+1

**Comment by ryanwalls** [comment] 2016-03-04 04:34
+1

**Comment by will-chan** [comment] 2016-03-08 00:23
This is coming...

**Comment by ibuildthecloud** [comment] 2016-03-11 05:27
@pizzarabe @ryanwalls @yesbut @CBR09 So I'm curious.  We will be shortly launching the ability to have Rancher manage swarm environments but.... you still add/remove hosts through Rancher.  What is the primary motivation for setting up hosts with Swarm and *then* adding the cluster to Rancher.

**Comment by ryanwalls** [comment] 2016-03-11 06:22
I think my motivation is mainly to be able to try the rancher UI with our existing provisioning scheme (ansible).  It's just a bigger barrier to entry if I have to rewrite my provisioning setup to use rancher apis.

**Comment by pizzarabe** [comment] 2016-03-11 11:53
I i want to create a Docker Infrastructure i will (always) create some Docker Servers and i will use Docker Swarm to cluster it (if i don't want to use Kubernetes).
If i want to add a Graphical UI to Docker I would like to add it to my existent Docker Swarm Cluster.
This is my Intention. ATM I have a Swarm Cluster and i want to user Rancher (and every other UI) as an extension, i don't want to create a complete new infrastructure because my UI is not able to work with my Docker Swarm Cluster.

**Comment by shija03** [comment] 2016-05-09 21:41
+1 - in the meantime - what other options are out there to manage from a GUI an existing docker swarm environment?   using docker-machine env --swarm and cli docker to run things is fine with me, but not with my team - some just don't like CLIs.

**Comment by sronsiek** [comment] 2016-08-16 09:28
+1

**Comment by kleinsasserm** [comment] 2017-04-14 06:01
Dropping in here. We would also like to have a native docker setup (docker-ce, swarm, and weave) because it is easier to handle in case of trouble but there is _no_ useful ui out there and (some) people need this. Also the features of rancher, for us the dynamic k/v, is pretty awesome but at the moment if i inspect a container started as swarm I get no information of published ports. This is a must have for using this information in external loadbalancers (nginx config). Hopefully this feature is coming too.

**Comment by superseb** [comment] 2018-01-27 13:21
Closing as duplicate of https://github.com/rancher/rancher/issues/4680

**Closed by superseb** 2018-01-27 13:21 UTC
Labels: area/scheduler, kind/enhancement
