### ISSUE TITLE
GCE + RancherOS + Rancher > not working

### ISSUE THREAD

**Issue by empinator** [rancher/rancher#9526] opened 2017-07-31 12:35 UTC
**Rancher versions:**
rancher/server: 1.6.5

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
rancheros-v1.0.3

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
GCE

**Steps to Reproduce:**
Upload RancherOS as custom Image 
Create and Boot VM (1 CPU, 4 GB RAM) with RancherOS
Start Rancher on VM: $ docker run -d --restart=unless-stopped -p 80:8080 rancher/server
Adjust Firewall to let Port 80 pass through
Try to connect to: http://<temp ip>/

**Results:**
Rancher shows first contact, but is stuck at "Loading..." in title bar and doesn't continue.
If using Ubuntu 16.04LTS instead of RancherOS and start the Rancher Docker Container there, it works

**Comment by superseb** [comment] 2017-07-31 12:38
Closing as duplicate of https://github.com/rancher/rancher/issues/8910, can you please try the workaround mentioned here: https://github.com/rancher/rancher/issues/8910#issuecomment-317780649

**Closed by superseb** 2017-07-31 12:38 UTC
