### ISSUE TITLE
Graphs continuously flashing

### ISSUE THREAD

**Issue by propyless** [rancher/rancher#5035] opened 2016-06-08 05:10 UTC
**Rancher Version:**
1.0.2

**Docker Version:**
 1.11.2

**OS and where are the hosts located? (cloud, bare metal, etc):**
CentOS - Baremetal

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
Single Node Rancher, Internal DB

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle

**Steps to Reproduce:**
Install rancher:server:stable
Go to container view for the server or any other container

**Results:** 
Graphs continuously flash. Getting graph details for a split second before reverting back to the **Connecting** text.

**Expected:**
Graphs are working perfectly showing the history of the cpu, ram, etc etc

**Other details**
Web inspector shows the graph polling as "101 Switching Protocols"
Its response is...
`Reload the page to get source for: http://domain.com:8080/v1/containerstats/0988a62ea3c35a495a5`

Opening that page in a new tab gives this error: 400 Bad request
```Bad Request
Failed to upgrade connection.```

**Comment by deniseschannon** [comment] 2016-06-08 05:21
Duplicate of https://github.com/rancher/rancher/issues/4406

**Closed by deniseschannon** 2016-06-08 05:21 UTC

**Comment by propyless** [comment] 2016-06-08 05:49
Ah sorry. I didn't find this while searching for issues.
