### ISSUE TITLE
Add B-series to Azure Instance list

### ISSUE THREAD

**Issue by ximbal** [rancher/rancher#15412] opened 2018-09-05 13:59 UTC
**Steps to Reproduce:**

I would Like to request you guys to add the B series VM's on rancher, or is there a way I could add them by myself? it would be pretty cool that you guys would open the option to manually specify the VM size. And get rid of administering this catalog.

Thank you.

**Results:**
NO B series family shown for Azure VM's

**Comment by tfiduccia** [comment] 2018-09-12 22:41
Version - 2.0 master 9/12 
The B series is added to the list, but I still cannot create a cluster with it.
![image](https://user-images.githubusercontent.com/11514927/45457108-51e94780-b6a2-11e8-9e48-6d4389c128af.png)

**Comment by westlywright** [comment] 2018-09-12 23:59
@tfiduccia i dont think this means that the issue is failing. The error you're getting back from Azure indicates that you simply don't have access to that size. I think this should be closed as resolved.

**Comment by superseb** [comment] 2018-09-13 08:09
See https://github.com/rancher/rancher/issues/14555, I created a new cluster selecting `Standard_B4ms` and got the instances:

<img width="262" alt="screen shot 2018-09-13 at 10 07 41" src="https://user-images.githubusercontent.com/2620179/45475577-1780b880-b73d-11e8-9c4a-a78d4f8628a3.png">

**Comment by deniseschannon** [comment] 2018-09-13 16:27
@tfiduccia can you re-test with the comments about how we make availability?

**Comment by tfiduccia** [comment] 2018-09-13 20:57
@westlywright @deniseschannon - I can create this size in azure when I'm logged in.  So I'm thinking this isn't because I don't have rights?

**Comment by westlywright** [comment] 2018-09-13 21:05
@cjellick @dramich I don't believe this is a UI issue, we simply pass the value to the API. Either of you have any ideas for Tani?

**Comment by superseb** [comment] 2018-09-13 21:08
@tfiduccia Can you create new resource names for everything when creating the nodes? Possibly it's trying to create a new size in an existing `docker-machine` availability set which won't work.

**Comment by tfiduccia** [comment] 2018-09-17 21:11
@westlywright @deniseschannon - the default availability set for azure template is "docker-machine".  And the B instances are not available in that?  We would need add them to docker-machine?

**Comment by tfiduccia** [comment] 2018-09-17 21:32
Version - 2.1 master 9/17 
B series added and if I change availability set to "none", works fine.  Entered separate issue for docker-machine default.
Verified fixed

**Closed by tfiduccia** 2018-09-17 21:32 UTC
Labels: area/ui, kind/enhancement, priority/-1, status/resolved, status/to-test, version/2.0
