### ISSUE TITLE
Swarm container stuck in initializing state when a GCE host is turned OFF and turned ON 

### ISSUE THREAD

**Issue by soumyalj** [rancher/rancher#6455] opened 2016-10-31 17:39 UTC
**Rancher Version:**1.2.0-pre4-rc6

**Docker Version:**1.12.2

**OS and where are the hosts located? (cloud, bare metal, etc):**Ubuntu, Cloud

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**: Swarm

**Steps to Reproduce:**
1. Create a 3 manager swarm setup using GCE hosts
2. Power OFF a host and Power ON the host. 

The swarm container on the host turned OFF and ON is stuck in initializing state as the IP address changes when GCE hosts are used. Rancher does not get the new IP and swarm does not function

**Comment by LLParse** [comment] 2016-10-31 17:51
In GCE, powering off (stopping) and powering on (starting) an instance will result in a new public IP address being assigned to the instance. When powered back on, the host doesn't detect this change and continues to report the old IP address in metadata.

We need to add logic to go-agent to detect these changes and update the public IP address for the host accordingly.

**Comment by deniseschannon** [comment] 2016-10-31 18:25
This has been the same behavior for whenever the IP changes. The workaround has always been to re-run the registration command with `CATTLE_AGENT_IP` set as the new IP. 

@soumyalj Please re-test with this use case for your swarm.

**Comment by soumyalj** [comment] 2016-11-02 22:05
@deniseschannon : Tried re-running the registration command. I see a panic in the logs:
```
time="2016-11-02T21:55:24Z" level=info msg="Initializing event router" workerCount=50 
time="2016-11-02T21:55:24Z" level=info msg="Connection established" 
time="2016-11-02T21:55:24Z" level=info msg="Starting websocket pings" 
time="2016-11-02T21:55:26Z" level=info msg="Received event: Name: compute.instance.remove, Event Id: 57275772-91ff-4411-8a7b-fbcccea1f3b8, Resource Id: 1ihm74" 
time="2016-11-02T21:55:26Z" level=info msg="Reply: 57275772-91ff-4411-8a7b-fbcccea1f3b8, compute.instance.remove, 1ihm74:instanceHostMap" 
time="2016-11-02T21:55:28Z" level=info msg="Received event: Name: delegate.request, Event Id: 50f7f134-c663-426d-b857-dd4a5b522ba6, Resource Id: " 
time="2016-11-02T21:55:28Z" level=error msg="Can not call [9de7ee7c-b222-4c08-9780-50bf6513dec1], container not exist" 
time="2016-11-02T21:55:41Z" level=info msg="Received event: Name: delegate.request, Event Id: 7e322e96-e1c9-455f-8ddb-8e0521c9c20c, Resource Id: " 
time="2016-11-02T21:55:41Z" level=error msg="Can not call [9de7ee7c-b222-4c08-9780-50bf6513dec1], container not exist" 
time="2016-11-02T21:55:41Z" level=info msg="Received event: Name: compute.instance.activate, Event Id: 161ae193-f2a3-488b-94a7-a4f0e3a37006, Resource Id: 1ihm45" 
time="2016-11-02T21:55:42Z" level=error msg="Error processing event" err="Error response from daemon: driver failed programming external connectivity on endpoint r-9de7ee7c-b222-4c08-9780-50bf6513dec1 (fe23e4388f16fc2488f97696bf9215c3dac18fa3333e207ba8d88725ab66fc15): Bind for 0.0.0.0:500 failed: port is already allocated" eventId=161ae193-f2a3-488b-94a7-a4f0e3a37006 eventName=compute.instance.activate resourceId=1ihm45 
time="2016-11-02T21:55:42Z" level=info msg="Received event: Name: compute.instance.inspect, Event Id: 74c8924b-77ed-4a1a-a176-48ef895221bd, Resource Id: " 
time="2016-11-02T21:55:42Z" level=info msg="rancher id []: Container with docker id [1c5379e6842f070d5eac81a912e3f93638a2851d2936c155062baacd7201b00a] has been inspected" 
time="2016-11-02T21:55:42Z" level=info msg="Reply: 74c8924b-77ed-4a1a-a176-48ef895221bd, compute.instance.inspect, :instanceInspect" 
time="2016-11-02T21:55:50Z" level=info msg="Received event: Name: delegate.request, Event Id: 7e322e96-e1c9-455f-8ddb-8e0521c9c20c, Resource Id: " 
time="2016-11-02T21:55:50Z" level=error msg="Can not call [9de7ee7c-b222-4c08-9780-50bf6513dec1], container not exist" 
time="2016-11-02T21:55:58Z" level=info msg="Received event: Name: delegate.request, Event Id: 7e322e96-e1c9-455f-8ddb-8e0521c9c20c, Resource Id: " 
time="2016-11-02T21:55:58Z" level=error msg="Can not call [9de7ee7c-b222-4c08-9780-50bf6513dec1], container not exist" 
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x4c3eef]

goroutine 40 [running]:
panic(0x808220, 0xc420012060)
	/usr/local/go/src/runtime/panic.go:500 +0x1a1
github.com/rancher/host-api/stats.(*ContainerStatsHandler).Handle(0xc869d8, 0xc42039c000, 0x24, 0xc42039c029, 0x2d5, 0xc42039b320, 0xc4202e3440)
	/go/src/github.com/rancher/host-api/stats/container_stats.go:106 +0x47f
created by github.com/rancher/host-api/vendor/github.com/rancher/websocket-proxy/backend.connectToProxyWS
	/go/src/github.com/rancher/host-api/vendor/github.com/rancher/websocket-proxy/backend/backend.go:81 +0xa84
time="2016-11-02T21:56:07Z" level=error msg="exit status 2" 
time="2016-11-02T21:56:11Z" level=info msg="Received event: Name: delegate.request, Event Id: 628d2608-dd19-4c34-8032-f3434aa5cf3e, Resource Id: " 
time="2016-11-02T21:56:11Z" level=error msg="Can not call [9de7ee7c-b222-4c08-9780-50bf6513dec1], container not exist" 
time="2016-11-02T21:56:11Z" level=info msg="Received event: Name: compute.instance.activate, Event Id: 7e6b174e-2792-4f33-ac48-50ee51965848, Resource Id: 1ihm45" 
time="2016-11-02T21:56:12Z" level=error msg="Error processing event" err="Error response from daemon: driver failed programming external connectivity on endpoint r-9de7ee7c-b222-4c08-9780-50bf6513dec1 (16b87d2f0b1d0c83ac3cfea636d3a5c626b91f900986322ca4ac6ad6bb8d8138): Bind for 0.0.0.0:500 failed: port is already allocated" eventId=7e6b174e-2792-4f33-ac48-50ee51965848 eventName=compute.instance.activate resourceId=1ihm45 
time="2016-11-02T21:56:12Z" level=info msg="Received event: Name: compute.instance.deactivate, Event Id: ed34a840-813a-4ca2-b28a-9fa32121d2e9, Resource Id: 1ihm45" 
time="2016-11-02T21:56:12Z" level=info msg="Reply: ed34a840-813a-4ca2-b28a-9fa32121d2e9, compute.instance.deactivate, 1ihm45:instanceHostMap" 
time="2016-11-02T21:56:12Z" level="info" msg="Starting event router." 
time="2016-11-02T21:56:12Z" level="info" msg="Watching state directory: /var/lib/rancher/state/containers" 
time="2016-11-02T21:56:12Z" level="info" msg="Connecting to proxy." url="ws://104.198.150.50:8080/v1/connectbackend?token=eyJhbG

```
The host cannot join the swarm cluster.

**Comment by soumyalj** [comment] 2016-11-02 23:42
Tried again by re-running the host registration command with CATTLE_AGENT_IP=new IP.
The host cannot join back the swarm cluster:
```
soumya@soumyaswtesthost2:~$ sudo docker ps -a
CONTAINER ID        IMAGE                           COMMAND                  CREATED             STATUS                      PORTS                                          NAMES
d47ec2ea1c35        rancher/agent:v1.1.0-rc7        "/run.sh run"            2 minutes ago       Up 2 minutes                                                               rancher-agent
edcfb9f7dbdd        rancher/agent:v1.1.0-rc7        "/run.sh http://104.1"   3 minutes ago       Exited (0) 2 minutes ago                                                   grave_turing
d13427b4d1bc        rancher/swarmkit:v1.12-2        "/opt/rancher/run.sh"    13 minutes ago      Up 13 minutes                                                              r-swarm-swarmkit-mon-2-112c8610
2ffef6332c34        rancher/swarmkit:v1.12-2        "/opt/rancher/run.sh"    About an hour ago   Exited (0) 21 minutes ago                                                  r-swarm-swarmkit-mon-2-1e9af9fd
cb4d55749ceb        redis:3.0.6                     "/entrypoint.sh redis"   2 hours ago         Exited (0) 21 minutes ago                                                  test.2.3n039ghihsmo8ojbc74j4i0iq
239f6cf2223c        rancher/agent-instance:v0.8.3   "/etc/init.d/agent-in"   3 hours ago         Up 13 minutes               0.0.0.0:500->500/udp, 0.0.0.0:4500->4500/udp   r-10247fac-0fb4-463d-8eee-bb5ea0087963
4cb08be75c14        rancher/agent:v1.1.0-rc7        "/run.sh state"          4 hours ago         Exited (0) 4 hours ago                                                     rancher-agent-state
d8f31edb5da4        rancher/agent:v1.1.0-rc7        "/run.sh http://104.1"   4 hours ago         Exited (0) 4 hours ago                                                     pedantic_spence
soumya@soumyaswtesthost2:~$ sudo docker logs -f d13427b4d1bc
++ tr -d '[[:space:]]'
++ cut -d: -f2
++ head -n1
++ grep Version
++ docker version
+ version=1.12.2
+ '[' 1.12.2 == 1.12.0 ']'
+ META_URL=http://rancher-metadata.rancher.internal/2015-12-19
+ SERVICE_NAME=swarmkit-mon
+ MANAGER_SCALE=3
++ curl -s http://rancher-metadata.rancher.internal/2015-12-19/self/host/agent_ip
+ AGENT_IP=104.198.74.108
+ '[' 104.198.74.108 == '' ']'
++ curl -s http://rancher-metadata.rancher.internal/2015-12-19/services/swarmkit-mon/uuid
+ SERVICE_UUID=9dcecc38-c01c-4a30-8186-50df4a65085f
++ curl -s http://rancher-metadata.rancher.internal/2015-12-19/self/host/uuid
+ HOST_UUID=8f0def14-daf9-4751-8720-935e9cdfa7d0
+ true
+ node
++ get_leader
++ local lowest_index lowest_ip
+ giddyup health -p 2378 --check-command /opt/rancher/health.sh
+++ containers
++++ curl -s http://rancher-metadata.rancher.internal/2015-12-19/services/swarmkit-mon/containers
+++ echo 0=swarm-swarmkit-mon-3 1=swarm-swarmkit-mon-1 2=swarm-swarmkit-mon-2
++ for container in '$(containers)'
+++ cut -d= -f2
+++ echo 0=swarm-swarmkit-mon-3
++ c=swarm-swarmkit-mon-3
+++ container_create_idx swarm-swarmkit-mon-3
++++ curl -s http://rancher-metadata.rancher.internal/2015-12-19/services/swarmkit-mon/containers/swarm-swarmkit-mon-3/create_index
+++ echo 11
++ create_index=11
++ '[' '' == '' ']'
++ lowest_index=11
+++ container_ip swarm-swarmkit-mon-3
++++ curl -s http://rancher-metadata.rancher.internal/2015-12-19/services/swarmkit-mon/containers/swarm-swarmkit-mon-3/primary_ip
+++ echo 104.154.128.183
++ lowest_ip=104.154.128.183
++ for container in '$(containers)'
+++ cut -d= -f2
+++ echo 1=swarm-swarmkit-mon-1
++ c=swarm-swarmkit-mon-1
+++ container_create_idx swarm-swarmkit-mon-1
++++ curl -s http://rancher-metadata.rancher.internal/2015-12-19/services/swarmkit-mon/containers/swarm-swarmkit-mon-1/create_index
+++ echo 14
++ create_index=14
++ '[' 11 == '' ']'
++ '[' 14 -lt 11 ']'
++ for container in '$(containers)'
+++ cut -d= -f2
+++ echo 2=swarm-swarmkit-mon-2
++ c=swarm-swarmkit-mon-2
+++ container_create_idx swarm-swarmkit-mon-2
++++ curl -s http://rancher-metadata.rancher.internal/2015-12-19/services/swarmkit-mon/containers/swarm-swarmkit-mon-2/create_index
+++ echo 17
++ create_index=17
++ '[' 11 == '' ']'
++ '[' 17 -lt 11 ']'
++ echo 104.154.128.183
+ '[' 104.154.128.183 == 104.198.74.108 ']'
++ local_node_state
+++ jq -r .Swarm.LocalNodeState
+++ curl -s --unix-socket /var/run/docker.sock http::/info
time="2016-11-02T23:20:59Z" level=info msg="Listening on port: 2378" 
++ echo active
+ '[' active == inactive ']'
+ reconcile_label
++ get_label swarm
++ curl -s http://rancher-metadata.rancher.internal/2015-12-19/self/host/labels/swarm
+ label=manager
++ is_swarm_manager
+++ jq -r .Swarm.ControlAvailable
+++ curl -s --unix-socket /var/run/docker.sock http::/info
++ echo true
+ manager=true
+ '[' true == true ']'
+ '[' manager '!=' manager ']'
+ '[' true == false ']'
+ sleep 30
+ true
+ node
++ get_leader
++ local lowest_index lowest_ip
+++ containers
++++ curl -s http://rancher-metadata.rancher.internal/2015-12-19/services/swarmkit-mon/containers
+++ echo 0=swarm-swarmkit-mon-3 1=swarm-swarmkit-mon-1 2=swarm-swarmkit-mon-2
++ for container in '$(containers)'
+++ cut -d= -f2
+++ echo 0=swarm-swarmkit-mon-3
++ c=swarm-swarmkit-mon-3
+++ container_create_idx swarm-swarmkit-mon-3
++++ curl -s http://rancher-metadata.rancher.internal/2015-12-19/services/swarmkit-mon/containers/swarm-swarmkit-mon-3/create_index
+++ echo 11
++ create_index=11
++ '[' '' == '' ']'
++ lowest_index=11
+++ container_ip swarm-swarmkit-mon-3
++++ curl -s http://rancher-metadata.rancher.internal/2015-12-19/services/swarmkit-mon/containers/swarm-swarmkit-mon-3/primary_ip
+++ echo 104.154.128.183
++ lowest_ip=104.154.128.183
++ for container in '$(containers)'
+++ cut -d= -f2
+++ echo 1=swarm-swarmkit-mon-1
++ c=swarm-swarmkit-mon-1
+++ container_create_idx swarm-swarmkit-mon-1
++++ curl -s http://rancher-metadata.rancher.internal/2015-12-19/services/swarmkit-mon/containers/swarm-swarmkit-mon-1/create_index
+++ echo 14
++ create_index=14
++ '[' 11 == '' ']'
++ '[' 14 -lt 11 ']'
++ for container in '$(containers)'
+++ cut -d= -f2
+++ echo 2=swarm-swarmkit-mon-2
++ c=swarm-swarmkit-mon-2
+++ container_create_idx swarm-swarmkit-mon-2
++++ curl -s http://rancher-metadata.rancher.internal/2015-12-19/services/swarmkit-mon/containers/swarm-swarmkit-mon-2/create_index
+++ echo 17
++ create_index=17
++ '[' 11 == '' ']'
++ '[' 17 -lt 11 ']'
++ echo 104.154.128.183
+ '[' 104.154.128.183 == 104.198.74.108 ']'
++ local_node_state
+++ jq -r .Swarm.LocalNodeState
+++ curl -s --unix-socket /var/run/docker.sock http::/info
++ echo active
+ '[' active == inactive ']'
+ reconcile_label
++ get_label swarm
++ curl -s http://rancher-metadata.rancher.internal/2015-12-19/self/host/labels/swarm
+ label=manager
++ is_swarm_manager
+++ jq -r .Swarm.ControlAvailable
+++ curl -s --unix-socket /var/run/docker.sock http::/info
++ echo true
+ manager=true
+ '[' true == true ']'
+ '[' manager '!=' manager ']'
+ '[' true == false ']'
+ sleep 30
+ true
+ node
++ get_leader
++ local lowest_index lowest_ip
+++ containers



```

**Comment by deniseschannon** [comment] 2016-11-03 03:05
@soumyalj any chance you wrote down the IPs of the host before and after? 

Did the IP of the host get updated on the UI?

**Comment by LLParse** [comment] 2016-11-16 23:23
Reproduced on Rancher master with GCE/AWS and Docker 1.12.3. Host re-registration succeeds to update the IP address. Swarm node doesn't function because the old IP address is still being advertised.

Solution is to check the agent IP address against the Swarm IP address. If a change is detected, we will leave and rejoin the swarm.

**Comment by LLParse** [comment] 2016-11-16 23:46
Similar to https://github.com/rancher/rancher/issues/6473, this bug only affects public Swarm clusters, which Rancher won't be able to support until Docker `1.13`. Moved to next release.

**Comment by LLParse** [comment] 2017-01-13 19:44
Docker `1.13` release rescheduled for 01-17-2017, moving to next release cycle.

**Comment by LLParse** [comment] 2017-02-01 23:29
Rancher won't support Docker `1.13` this release so moving to next release.

**Comment by deniseschannon** [comment] 2017-02-02 02:20
It's not that rancher will not be supporting docker 1.13, but not sure if we will be able to certify swarm with docker 1.13.

**Comment by deniseschannon** [comment] 2017-02-10 17:45
Let's re-test this with Docker 1.13 to see if there are any issues. @soumyalj

**Comment by soumyalj** [comment] 2017-02-21 18:32
Tested with v1.5.0-alpha1 and docker 1.13.0 hosts. Powered OFF and powered ON the GCE host on which had swarm worker node . Swarm container was stuck in initializing state. After using the command ```docker swarm leave --force``` on the swarm container which was stuck in initializing state, the container started.

**Closed** 2018-08-21 21:37 UTC
Labels: area/swarm, kind/bug, status/autoclosed
