### ISSUE TITLE
Public Helm Repo's (marketplace) not pulled in anymore due to proxy issues.

### ISSUE THREAD

**Issue by MG2R** [rancher/rancher#29961] opened 2020-11-06 09:38 UTC
**What kind of request is this (question/bug/enhancement/feature request):**
bug

**Steps to reproduce (least amount of steps as possible):**
- set up a Rancher 2.5.1 behind an HTTP proxy (with the `proxy` value set in Helm at installation time)
- Try adding https://helm.elastic.co as a legacy catalog (Cluster Manager)
- Try adding https://helm.elastic.co as a Repository in the new "Apps & Marketplace" Cluster Explorer UI

**Result:**
Legacy way -> just works
New way -> ERROR `Get "https://helm.elastic.co/index.yaml": dial tcp: lookup helm.elastic.co on 10.43.0.10:53: no such host`

**Other details that may be helpful:**
When I refresh the new type of Helm Repo's, I can see log entries in the cluster-agent of the managed RKE cluster (i.e. the one I'm trying to add the new Repo for). When I refresh the legacy catalog, I get no log entries anywhere.

This leads me to believe the old catalogs were fully managed on the Rancher Server, which was started with the correct proxy information by Helm, while the new ones are managed by the individual clusters' cluster-agent, which does not get the correct proxy settings from Rancher.

Another weird thing here is that the built-in Helm Repo's (in the new UI) do actually work, even though they're getting information from an external source (git.rancher.io). These also do not generate logs in the clusters' cluster agent, so I'm guessing those are managed by Rancher Server itself? 

There's almost zero documentation regarding all of this, the way it works, or which settings there are for it. Is there a way to provision clusters and set the correct proxy information for Rancher components in that cluster? I have a workaround available (locally caching external repo's), but I'd still like to properly understand what's going on here. 

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): v2.5.1
- Installation option (single install/HA): HA. Rancher Server running on RKE, the managed clusters are 

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): custom
- Machine type (cloud/VM/metal) and specifications (CPU/memory): VM, 4 cores, 8 GB or 16 GB (etcd vs workers)
- Kubernetes version (use `kubectl version`):

```
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.2", GitCommit:"52c56ce7a8272c798dbc29846288d7cd9fbae032", GitTreeState:"clean", BuildDate:"2020-04-16T11:56:40Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.3", GitCommit:"2e7996e3e2712684bc73f0dec0200d64eec7fe40", GitTreeState:"clean", BuildDate:"2020-05-20T12:43:34Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
```

- Docker version (use `docker version`):

```
Client: Docker Engine - Community
 Version:           19.03.12
 API version:       1.40
 Go version:        go1.13.10
 Git commit:        48a66213fe
 Built:             Mon Jun 22 15:46:54 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.12
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.13.10
  Git commit:       48a66213fe
  Built:            Mon Jun 22 15:45:28 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.2.13
  GitCommit:        7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

gz#13523

**Comment by jiaqiluo** [comment] 2020-11-13 20:16
Hi @MG2R  I cannot reproduce this bug on a rancher:`2.5.2` single-install setup. Can you try v2.5.2 in your environment and see if it works? Or how is my step different from yours?

The ec2 instance in which the rancher is installed does not have the access to the internet ( no public IP assigned to the instance), but a proxy server is used for rancher to access the internet. 

The sample command for installing rancher
```
docker run -d --restart=unless-stopped \
  -p 80:80 -p 443:443 \
  -e HTTP_PROXY="http://192.168.10.1:3128" \
  -e HTTPS_PROXY="http://192.168.10.1:3128" \
  -e NO_PROXY="localhost,127.0.0.1,0.0.0.0,10.0.0.0/8,192.168.10.0/24,.svc,.cluster.local" \
  --privileged \
  rancher/rancher:v2.5.2
```

I added this repo `https://helm.elastic.co` and the repo is downloaded successfully in both the (old) Multiple-Cluster-Manager UI and the (new) Cluster Explorer UI. 

![image](https://user-images.githubusercontent.com/6218999/99116849-f8e30a00-25b1-11eb-80e3-1bb3bfd8712d.png)
![image](https://user-images.githubusercontent.com/6218999/99116993-39428800-25b2-11eb-8beb-1bf2c12dcb69.png)


![image](https://user-images.githubusercontent.com/6218999/99116889-03050880-25b2-11eb-8e3f-2c710d208955.png)

![image](https://user-images.githubusercontent.com/6218999/99117013-419ac300-25b2-11eb-8ec6-00b8796f2a6b.png)

**Comment by MG2R** [comment] 2020-11-16 14:59
Are you trying this on the "local" cluster? For me it does work on the "local" cluster, which makes sense as that is running on the installatio that has the correct HTTP_PROXY variables set with Helm during the Rancher Server installation. It does not work, however, on any other cluster I manage with Rancher.

I'm using custom node RKE clusters in our own datacenter.

**Comment by jiaqiluo** [comment] 2020-11-16 18:55
@MG2R Yes I used the `local` cluster. 
I think this is related to this issue https://github.com/rancher/rancher/issues/24876

**Comment by jiaqiluo** [comment] 2020-11-16 19:00
@MG2R One more question:
> I'm using custom node RKE clusters in our own datacenter.

Do your nodes have access to the proxy? If you ssh to the node and do curl command, do you see the traffic going through the proxy? 

If the answers to those two questions are yes, the cause should be the issue I mentioned in my previous comment.

**Comment by MG2R** [comment] 2020-11-17 10:06
Yes and yes. The docker daemon is even set up to automatically inject proxy settings into containers launched with root and `docker run` (via `~/.docker/config.json`). That all works. 

I just confirmed: adding proxy settings to the cluster-agent as described in #24876 fixes this problem.

Before I close this as a duplicate, though. Can you maybe provide some feedback towards this, from the OP: 

> There's almost zero documentation regarding all of this, the way it works, or which settings there are for it.

In the Rancher docs, there's a high-level overview of what Rancher is and what it does and how it generally does things. But for debugging stuff like this, it would be really handy if the documentation outlined which components are supposed to do what. Things like the fact that Helm catalogs are now pulled from the cluster under management instead of the Rancher Server are important details to know when operating a Rancher environment.

**Comment by eest** [comment] 2021-01-15 17:00
I have experienced the same problem (running rancher v2.5.3). I am trying to set up an RKE cluster via the `Custom` provider, and the RKE cluster does not have access to the internet (expects to use a HTTP proxy to reach internet resources) but can reach the rancher system directly. I installed rancher using the "--set proxy=" and "--set noProxy=" helm options as described at https://rancher.com/docs/rancher/v2.x/en/installation/install-rancher-on-k8s/chart-options/#http-proxy

Trying to add an external Chart Repository at the Apps & Marketplace for ArgoCD (https://github.com/argoproj/argo-helm) worked as expected for the `local` cluster and I could see this was managed by the `rancher` pod on the local cluster, as in:
```
kubectl logs rancher-6585c886b-jb9rs -n cattle-system
[...]
2021/01/15 13:39:32 [INFO] Downloading repo index from https://argoproj.github.io/argo-helm/index.yaml
```

All well and fine, but trying to add the same repo to the `Custom` RKE cluster failed. Inspecting that cluster I found this:
```
kubectl logs cattle-cluster-agent-ff4d656c9-4mw9m -n cattle-system
[...]
time="2021-01-15T15:18:13Z" level=info msg="Downloading repo index from https://argoproj.github.io/argo-helm/index.yaml"
time="2021-01-15T15:18:43Z" level=error msg="error syncing 'my-argocd': handler helm-clusterrepo-download: Get \"https://argoproj.github.io/argo-helm/index.yaml\": dial tcp xxx.yyy.zzz.xxx:443: i/o timeout (Client.Timeout exceeded while awaiting headers), requeuing"
```

So while the local cluster is able to to use the proxy config from the helm installation, this is not passed on to the `cattle-cluster-agent` running in the managed RKE cluster. As mentioned above editing the deployment YAML via `kubectl edit deployment cattle-cluster-agent -n cattle-system` and adding the appropriate environment variables to the `cattle-cluster-agent` deployment spec (modified to fit my environment):
```
- name: HTTP_PROXY
  value: "url:port"
- name: HTTPS_PROXY
  value: "url:port"
- name: NO_PROXY
  value: "localhost,127.0.0.1,0.0.0.0"
```

... made it work:
```
kubectl logs cattle-cluster-agent-7dbcbf8bb8-qg9lc -n cattle-system
[...]
time="2021-01-15T15:55:33Z" level=info msg="Downloading repo index from https://argoproj.github.io/argo-helm/index.yaml"
```

But this seems like a hacky workaround (and I am not sure how persistent such a change is). I agree #24876 is related, but in that ticket the focus appears to be `Imported` clusters where you get a chance to modify the YAML describing among other things the `cattle-cluster-agent`. I am not aware of any such step when setting up a `Custom` cluster (possibly this needs to be expressed as flags to the rancher-agent utility executed when joining a node?).

**Comment by kinarashah** [comment] 2021-01-15 17:02
@jiaqiluo Could we test this out for custom clusters? ^

**Comment by jiaqiluo** [comment] 2021-02-23 18:39
The bug is reproduced on the downstream custom clusters on a `v2.5.5` single-install setup. 

Both the Rancher server and the custom cluster do not have direct access to the internet and run behind the same proxy. All nodes are in the same network so the cluster can be registered into Rancher. 

The following two repositories are used to test on both the Cluster Management UI and the Cluster Explorer UI:
```
1. https://helm.elastic.co 
2. https://github.com/argoproj/argo-helm - master branch
```	

The bug happens when adding them as the chart repositories in the `Apps & Marketplace` on the Cluster Explorer UI. 
The repositories are failed to download
![image](https://user-images.githubusercontent.com/6218999/108890297-a19a0000-75ca-11eb-9dea-c4dd7296d4b0.png)

and the logs of the `cattle-cluster-agent` pod show it failed to access those links. 
```
time="2021-02-23T18:28:33Z" level=error msg="error syncing 'r1': handler helm-clusterrepo-download: Get \"https://helm.elastic.co/index.yaml\": context deadline exceeded (Client.Timeout exceeded while awaiting headers), requeuing"

time="2021-02-23T18:32:42Z" level=error msg="error syncing 'r2': handler helm-clusterrepo-download: git clone --depth=1 -n --branch master https://github.com/argoproj/argo-helm management-state/git-repo/r2/5de4df05caadf4c62cecfc6fe3e44f2161401853ae708e28a6155f4ce5104195 error: exit status 128, detail: Cloning into 'management-state/git-repo/r2/5de4df05caadf4c62cecfc6fe3e44f2161401853ae708e28a6155f4ce5104195'...\nfatal: unable to access 'https://github.com/argoproj/argo-helm/': Failed to connect to github.com port 443: Connection timed out\n, requeuing"
```


More info:
- Rancher's builtin repos work fine in the `Apps & Marketplace`
- The same repos can be added and charts can be pulled from the internet when adding them on the Cluster Management UI

**Comment by jiaqiluo** [comment] 2021-02-23 19:51
The bugfix is validated on both Rancher `v2.5-head`  aa85f4d1 and `master-head` 67126b3

When creating/editing a downstream custom cluster, I need to edit the cluster in API to pass the configuration for `NO_PROXY`, `HTTP_PROXY`, and `HTTPS_PROXY` as environment variables. Note: A [UI enhancement](https://github.com/rancher/rancher/issues/31023) will come soon. 

After that, I can confirm that the chart repositories added in the `Apps & Marketplace` on the Cluster Explorer UI works: the charts are downloaded and listed in the `Charts`.  

<img width="742" alt="Screen Shot 2021-02-23 at 12 31 18 PM" src="https://user-images.githubusercontent.com/6218999/108899267-779a0b00-75d5-11eb-9580-f77ad1cf7f65.png">


<img width="858" alt="Screen Shot 2021-02-23 at 12 49 53 PM" src="https://user-images.githubusercontent.com/6218999/108899531-c34cb480-75d5-11eb-876e-088ad7da0e58.png">

![image](https://user-images.githubusercontent.com/6218999/108899475-b0d27b00-75d5-11eb-93b2-8f2b08afbd52.png)

**Closed by jiaqiluo** 2021-02-23 19:51 UTC
Labels: [zube]: QA Working, area/agent, area/catalog, internal, kind/bug, priority/0
