### ISSUE TITLE
Custom cluster with Scheduled CIS scan enabled creation fails at 2.5.6-rc4

### ISSUE THREAD

**Issue by rawmind0** [rancher/rancher#31242] opened 2021-02-10 18:11 UTC
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
Create a new custom cluster, enabling `Scheduled CIS scan` with default profile `RKE-CIS-1.6` ( RKE-CIS-1.6 Permissive and Hardened profiles affected)

**Result:**
Custom cluster creation fails with  errors:

- From UI: `Validation failed in API: cisScanHandler: error fetching benchmark version info rke-cis-1.6: cisbenchmarkversions.management.cattle.io "rke-cis-1.6" not found`
- From API: `Bad response statusCode [422]. Status [422 Unprocessable Entity]. Body: [baseType=error, code=InvalidBodyContent, message=cisScanHandler: error fetching benchmark version info rke-cis-1.6: cisbenchmarkversions.management.cattle.io "rke-cis-1.6" not found] from [https://<RANCHER_URL>/v3/clusters]`

**Other details that may be helpful:**
The default CIS scan profile `rke-cis-1.6` doesn’t exist at api `https://<RANCHER_URL>/v3/cisbenchmarkversions` nor `https://<RANCHER_URL>/v1/management.cattle.io.cisbenchmarkversions`

Setting CIS scan profile to `rke-cis-1.5` (permissive or hardened) makes the cluster be deployed successfully.

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): 2.5.6-rc4
- Installation option (single install/HA): Both affected

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): Custom
- Machine type (cloud/VM/metal) and specifications (CPU/memory):
- Kubernetes version (use `kubectl version`): All available at cluster creation form 

```
(paste the output here)
```

- Docker version (use `docker version`):

```
(paste the output here)
```

**Comment by prachidamle** [comment] 2021-02-16 18:15
I think this is a UI issue - we should not be listing `rke-cis-1.6` in the UI.

As mentioned by @rawmind0 above, the default CIS scan profile rke-cis-1.6 doesn’t exist at api https://<RANCHER_URL>/v3/cisbenchmarkversions nor https://<RANCHER_URL>/v1/management.cattle.io.cisbenchmarkversions

I do not see it added into KDM cis_config either. So Backend  for CIS v1 does not support rke-cis-1.6

From where does UI list this version? If it is a hardcoded list, we should change it for CIS v1.

UI ticket for this: https://github.com/rancher/rancher/issues/31343

**Comment by deniseschannon** [comment] 2021-02-17 21:36
Duplicate of #31343

**Closed by deniseschannon** 2021-02-17 21:36 UTC
Labels: kind/bug-qa
