### ISSUE TITLE
Rancher stops syncing secrets with namespaces

### ISSUE THREAD

**Issue by ChSch3000** [rancher/rancher#17011] opened 2018-12-10 17:18 UTC
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
Not sure if this is the way to reproduce the bug
1. Create new secret "passwords" with some key-value pairs (Available for all namespaces). Secrets are synced within all namespaces
2. Rename a secret key to "ABCDEF"
3. Add new key-value pair in password secrets

**Result:**
The modified and new keys aren't synced. They appear in the UI, but if I execute "kubectl get secrets -n default -o yaml | grep "ABCDEFG" " nothing is returned (same with args --all-namespaces).

Is there any option to restart the Rancher secret controller?

**Environment information**
- Rancher version 2.1.2

**Comment by ChristianSchlatter** [comment] 2018-12-10 17:49
Another Test
1. Added a new key-value pair to the secrets. (call it "FOO_BAR"
2. Create new Wokload, add environment from source, choose secret from list. FOO_BAR appears in list, choose this and deploy workload.
3. Workload deployment failed with error: CreateContainerConfigError: Couldn't find key FOO_BAR in secret default/passwords

**Comment by loganhz** [comment] 2018-12-11 11:17
@ChristianSchlatter I can not reproduce this issue. Did I miss something?

Create a secret with `key1`
Use `kubectl` to make sure `key1` is in the secret
Edit the secret in UI and rename `key1` to `key2`
Use `kubectl get secret` to check if `key2` is in the secret.

I can see key2 is in the secret.

**Comment by ChristianSchlatter** [comment] 2018-12-11 13:05
Mh.. yes, I guess Imissed something. I can't reproduce it either with new secrets.

The issues seems to affect only this secrets. Other project scope secrets are synced as usual.

Here again, added a new secret "TEST"
![screenshot_5](https://user-images.githubusercontent.com/6421265/49802222-97beb600-fd4c-11e8-9789-e7e05eca43c7.png)

But the change is not reflected within  the namespaces

`kubectl get secrets passwords -o yaml`

```
apiVersion: v1
data:
  AUA_POSTGRES_PASSWORD: ******
  DEFAULT_USER_PASSWORD: ******
  IDP_POSTGRES_PASSWORD: ******
  IDP_REDIS_PASSWORD: ******
  IDP_SQL_PASSWORD: ******
  PROS_API_PASSWORD: ******
  PROS_ODOO_PASSWORD: ******
  PROS_SQL_PASSWORD: ******
  SMTP_PASSWORD: *******
kind: Secret
metadata:
  annotations:
    field.cattle.io/creatorId: user-5czj8
    field.cattle.io/description: Allgemeine Passwörter global genutzte Elemente (DB
      etc.)
    field.cattle.io/projectId: 
c-48mmc:project-r8kk2
    lifecycle.cattle.io/create.secretsController_c-48mmc: "true"
    secret.user.cattle.io/secret: "true"
  creationTimestamp: 2018-12-10T19:45:18Z
  name: passwords
  namespace: default
  resourceVersion: "24114694"
  selfLink: /api/v1/namespaces/default/secrets/passwords
  uid: 1f7b3633-fcb4-11e8-88af-1eb3160df661
type: Opaque
```

Does the secret controller produce logs somewhere?

**Comment by tonysickpony** [comment] 2018-12-18 00:54
I am having the same problem here, running rancher v2.1.1

**Comment by iwilltry42** [comment] 2019-03-13 12:46
I am also experiencing weird issues with secrets which are assigned to a project.
I wanted to have kerberos keytabs as secrets per project, so they're available in all namespaces below that project.
Since copy-pasting to the UI with a binary format is not a good option, I did this:
- `kubectl create secret generic kerberos-client --from-file=krb5.keytab=./client.keytab`
- go to Rancher UI, select the secret I just created, clone it and tick the checkbox to make it available to all namespaces
- use it in a workload

What happens: somehow, the secret value got modified in a way, that the first few bytes are the same and then some weird bytes got appended (checked with Hex representation).

Then, when I modify the secret in a namespace to set it back to the original value, it will work in the workload, but after a while it goes back to this weird value.

I am completely lost here and for now went on creating the secret for every single namespace manually.

**Comment by deniseschannon** [comment] 2019-04-09 03:14
@ChSch3000 @iwilltry42 @tonysickpony Can you reproduce this issue on v2.2.1?

**Comment by loganhz** [comment] 2019-12-17 07:09
Please let us know in a comment if you can still reproduce the issue, and we'll reopen it

**Closed by loganhz** 2019-12-17 07:09 UTC
Labels: [zube]: Unscheduled, kind/bug, team/ca

**Comment by iwilltry42** [comment] 2019-12-17 10:54
Hi @loganhz , sorry for this super late response, I totally forgot about this issue.
I just tried it again witch v2.3.3:
* create a secret via kubectl from a Keytab (binary data)
* go to the Rancher UI and clone the secret, making it project-wide available
* compare the base64-encoded value of both secrets: the first 66 characters are the same and afterwards, they're different (the project-wide secret even has a suffix of double the size of the original secret and does contain `/+= characters, while the original secret is Alphanum only)
* The decoded values seem to differ in a single byte only :thinking:

**Comment by loganhz** [comment] 2019-12-17 11:39
Hi @iwilltry42 ,  maybe the root cause is the same with https://github.com/rancher/rancher/issues/24577

Rancher server will trim the secret value automatically.
