### ISSUE TITLE
CentOS 8 Support with Docker CE

### ISSUE THREAD

**Issue by MSandro** [rancher/rancher#23117] opened 2019-09-27 06:22 UTC
CentOS 8 needs to be supported fully.

Validate Rancher HA setup
Validate Rancher custom cluster
Validate Rancher AMI / node driver

**Comment by superseb** [comment] 2019-09-27 06:24
Duplicate of https://github.com/rancher/rancher/issues/23045

**Closed by superseb** 2019-09-27 06:24 UTC
