### ISSUE TITLE
Scaling limits on services

### ISSUE THREAD

**Issue by deniseschannon** [rancher/rancher#2590] opened 2015-11-06 23:31 UTC
Per http://forums.rancher.com/t/prevent-service-from-scaling/658 
and
http://forums.rancher.com/t/how-to-disable-scaling-of-service/894

Users would like a way to put a maximum limit of containers on a service.

**Comment by ibuildthecloud** [comment] 2015-11-07 13:50
+1.  I also need to be able to say only odd number and a minimum.  This is needed for clustered system that need a quorum.

**Comment by vincent99** [comment] 2015-11-07 17:47
New scalingPolicy embedded type and rancher-compose field?

```
{
  min: 3,
  max: 9,
  increment: 2,
  global: true/false
}
```

Or `odd: true`, but with `min`+`increment` you can express "even", "odd", or "multiple of 5".

This should be combined with #2092 and http://forums.rancher.com/t/request-better-global-scheduling/895 (for global `scale` should be X containers on each host).

And is there a reason for global to be a label on service instead of a property in rancher-compose?

**Comment by ibuildthecloud** [comment] 2015-11-07 18:01
Mainly because I don't like rancher-compose but anything that is simple key value I prefer labels.  Scale was not put as a label because it's really environment specific and "non-portable."

I would probably opt to have min, max, increment as a label too.  Increment sounds better than odd.

**Comment by ibuildthecloud** [comment] 2015-11-07 18:35
Okay, maybe labels are bad too.  I just don't like cross referencing between two files for the same service/container

**Comment by mishak87** [comment] 2015-11-08 03:04
I think labels are cool. I rarely need `rancher-compose.yml` to do something. For most of the time `docker-compose.yml` + `labels:` is enough for me.

Formal: `<val>|<min>..[<max>][*<mul>[+<add>]]`
[Regex](https://regex101.com/r/bD8xW5/1): `^((?P<value>\d+)|(?P<min>\d+\.\.(?P<max>\d+)?)?(\*(?P<mul>\d+(\+(?P<add>\d+))?)?))$`

```yaml
labels:
    io.rancher.service.scale: 1  # just 1
    io.rancher.service.scale: 1..10  # from 1 to 10 ie.: we don't have more licenses
    io.rancher.service.scale: 3..  # 3 and more
    io.rancher.service.scale: 1..4*5  # from 5 to 20 by increments of 5
    io.rancher.service.scale: *2+1  # odd starting from 3
    io.rancher.service.scale: 2..*2+1  # odd starting from 5
    io.rancher.service.scale: 1..10*2  # even starting from 2 to 20
```

 `rancher-compose.yml` scale would take priority if label was defined in `docker-compose.yml`.

**Comment by vincent99** [comment] 2015-11-08 07:12
Those kinds of things are a nightmare to parse and maintain backwards compatibility when the next new thing gets added, and completely undiscoverable in the API.  First-class options should have first-class support in the API, not unstructured magic labels with strings that require parsing and stringifying logic  in the UI, rancher-compose, and every client that wants to use them.

I don't mean to just pick on your proposal specifically, but a lot of things we use labels for in general today,  @ibuildthecloud and I talked offline about this offline... We both don't like unstructured labels, and both don't like two files.  So we will be looking into combining them into one file. The reason there are two in the first place is because `docker-compose` does not accept fields it doesn't recognize.  And the reason many things are labels is because we didn't want to have to put them in the second file.  

So the three avenues to explore are:

- See if docker will accept a patch to ignore unknown subtrees with a known user prefix, like `.key` or `x-key` (Unlikely IMO)
- See if there are any suitable yml hacks to satisfy our arbitrary data and their parser that we'd be happy with (also probably unlikely, other than maybe abusing comments)
- Forget about docker-compose.yml compatibility and use one combined file.  We can  add a `rancher-compose --de-rancher-ify combined.yml` command that outputs the `docker-compose` compatible version.

**Comment by mishak87** [comment] 2015-11-08 11:21
If this is that serious wouldn't make sense to freeze API (rancher-compose and labels) and create new issue on how to solve that? I would raise few points there since this issue changed from adding new feature to overhauling API design.
I would appreciate if you could share the offline reasoning behind this as this discipline is rather new for me and it would provide valuable insight.

My understanding was that `rancher-compose.yml` and labels were part of official Rancher API and stable.
The biggest benefit I saw when I have decided for Rancher was the ability to define docker-compose and run services locally and then globaly with same config and very similar behaviour (no scaling, links replaced with DNS behave slightly differently). Which helped me to use and learn rancher very quickly.

**Comment by ibuildthecloud** [comment] 2015-11-08 14:19
@mishak87 Don't worry about stability.  We have far too many users that we aren't going to break compatibility.  We we're just discussing how to proceed forward.

At Rancher we are very committed to Docker Native Interface.  We want to use the standard Docker approaches.  The problem is always when we need to add new functionality.  We should create a new issue for this.  Don't worry we haven't made any decisions, just brainstorming and we won't break compatibility.

**Comment by sjwoodr** [comment] 2016-03-28 19:40
Any chance of this getting done?  I still like the idea of having a scale=# and global=true resulting in that fixed # of containers on each host that matches the scheduling rules.

**Comment by vincent99** [comment] 2016-03-28 19:43
@sjwoodr Yes, but not in 1.0

**Comment by sjwoodr** [comment] 2016-03-28 20:12
I saw this was added to release/future .... so just backport it from the future!  ;)

**Comment by vincent99** [comment] 2016-03-28 22:13
There is actually a PR for it already, but it doesn't include the part you want (handling global):  https://github.com/rancher/cattle/pull/1407

**Closed** 2018-04-26 22:02 UTC
Labels: area/service, kind/feature
