### ISSUE TITLE
Failing to add new member to an environment

### ISSUE THREAD

**Issue by galal-hussein** [rancher/rancher#6267] opened 2016-10-13 23:29 UTC
**Rancher Version:**
master image
**Docker Version:**
1.12.2
**OS and where are the hosts located? (cloud, bare metal, etc):**
cloud
**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
single node rancher
**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle
**Steps to Reproduce:**
- Enable local authentication with default admin
- Add new user with type user
- Create new environment
- Login with the admin user
- Try to add the created user to the environment with any type (member, Read-Only, etc.)

**Results:** 

e.saveStacks is not a function

**Comment by galal-hussein** [comment] 2016-10-14 17:43
The same issue happens when adding new member when Github authentication is enabled.

**Comment by deniseschannon** [comment] 2016-10-16 16:22
Duplicate of https://github.com/rancher/rancher/issues/6248

**Closed by deniseschannon** 2016-10-16 16:22 UTC
Labels: kind/bug
