### ISSUE TITLE
[ui] Display actual container ID

### ISSUE THREAD

**Issue by xaka** [rancher/rancher#3098] opened 2015-12-20 06:26 UTC
Due to unknown issue it's not always possible to see container's logs from UI (I have no logging driver applied and I'm getting `disconnected` error) so the only option I have is to ssh onto rancher agent host and run `docker logs -f`, which is kind of complicated as I don't know the actual container's ID in UI and have to go through multiple steps to get to where I want.

Here is the console error I'm getting:

```
WebSocket connection to 'ws://...:8080/v1/logs/?token=eyJhbGciOiJSUzI1NiJ9.eyJleHAiOjE0NTA1OTI4NzAsInN1YiI6ImNhdHRsZSIsImxvZ3MiOnsiQ29udGFpbmVyIjoiNDhjMzBiOTg1MjVjNTM3OWYyOWUzYzNlM2E1NDljNmI0MjA3M2YwZDE4MWM1ZWY0Yzk5MjllNTQyOTZmNGZjMSIsIkxpbmVzIjo1MDAsIkZvbGxvdyI6dHJ1ZX0sImlzcyI6Imh0dHA6XC9cL2NhdHRsZS5pbyIsImhvc3RVdWlkIjoiZGYwODFkYzUtM2JjZC00YThjLTk5NzEtYzZhN2ZjNDJhNzJlIiwiaWF0IjoxNDUwNTkyNTcwLCJraWQiOiJkZWZhdWx0In0.KFmfU47HP5BTJ6mzDDeVZLZ7kcjfSx52pczNe-0td4oVxzXqUSk_kSPzlsRSA4v5a-tQTDEP-0fryarKDx0H2qTqJeNjVjHGDXKYZRzAabYzZncZi96NfWlrb5MdNUUIGmlbilonGTZ1bejmMLPLMNbfZcuRxOJ_ltMdaEXzdCTUFCAyaPeD_cqTXrWpbHql0KK0txi4vODeOm_J4uHakkuoPAhvYAhoUSb18zMLcTZVLLKITKTY0Gl_ZmlcZ9X6wKNcDpTiVZeQBJAC9Cdv3Dpqj2SGxuEjoybPu2dAb2QXCjj3YLc2EIre1IzUQCe7ahtrK2MAnzG6cwCQFD1BfQ'
failed: HTTP Authentication failed; no valid credentials available
```

I have no authentication applied, etc. as everything is being run in private network and kind of MVP. I tried to reload the page couple times and restart browser, but nothing helped so far except for `docker logs -f`, which isn't easy as I don't know container ID upfront.

**Comment by deniseschannon** [comment] 2015-12-21 21:51
Duplicate of #2474

**Closed by deniseschannon** 2015-12-21 21:51 UTC

**Comment by xaka** [comment] 2015-12-21 21:52
Why Am I so bad at searching? :sob:

**Comment by vincent99** [comment] 2015-12-21 22:13
@xaka No worries, probably because we have infinite issues put in already :-)
