### ISSUE TITLE
UI Link to nodePort host always %3Cnil%3E

### ISSUE THREAD

**Issue by stefanvangastel** [rancher/rancher#15482] opened 2018-09-10 07:11 UTC
**Rancher versions:**
**Rancher**: v2.0.8
**User Interface**: v2.0.67
**Helm**: v2.9.1-rancher1
**Machine**: v0.15.0-rancher1-1

**Infrastructure Stack versions:**
`kubectl version`
```
Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.0", GitCommit:"91e7b4fd31fcd3d5f436da26c980becec37ceefe", GitTreeState:"clean", BuildDate:"2018-06-27T20:17:28Z", GoVersion:"go1.10.2", Compiler:"gc", Platform:"windows/amd64"}

Server Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.2", GitCommit:"bb9ffb1654d4a729bb4cec18ff088eacc153c239", GitTreeState:"clean", BuildDate:"2018-08-07T23:08:19Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}
```

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
Single node rancher

**Steps to Reproduce:**
Add new scalable deployment to Rancher 2.0.8 using nodePort portmapping. Hover link to exposed port. This shows (and opens) e.g. ` %3Cnil%3E:30297`

**Results:**
![nil](https://user-images.githubusercontent.com/2473490/45281983-e94f6e80-b4d9-11e8-86b2-805d84f67460.png)

**Comment by tfiduccia** [comment] 2018-09-10 22:46
@stefanvangastel - I cannot reproduce this.  So I'm closing, if you can reproduce after next release just re-open.

**Closed by tfiduccia** 2018-09-10 22:46 UTC
Labels: area/ui, kind/bug, status/to-test, version/2.0

**Comment by azbpa** [comment] 2019-03-05 17:14
Facing the same issue when importing a cluster created manually with RKE `v0.1.16` to Rancher Server `v2.1.6`.

From where comes the information that is used by Rancher UI to display the FQDN of the host? Is it a custom annotation that might be missing?
