### ISSUE TITLE
Distinguish user owned templates/credential objects from global ones..

### ISSUE THREAD

**Issue by skyscooby** [rancher/rancher#23026] opened 2019-09-23 21:18 UTC
The list of Node Templates and Cloud Credentials is fully visible from an admin account however user level accounts only see some of the objects (ones they created?).. 

Admin users need to be able to easily see the difference and perhaps which user owns these objects obviously removing one accidentally thinking they created it when it was really a non admin users template isn't desirable..

**Comment by deniseschannon** [comment] 2019-09-26 23:17
@tfiduccia Can you give your feedback on how we should list the templates to sort a user's versus everyone if they are an admin? 

This should be for node template and cloud credentials.

**Comment by deniseschannon** [comment] 2019-09-26 23:18
Similar or duplicate of https://github.com/rancher/rancher/issues/23054

**Comment by tfiduccia** [comment] 2019-09-30 17:46
This is a duplicate of #23054, so I'll close and we'll track through that issue.

**Closed** 2019-09-30 17:50 UTC
Labels: [zube]: Next Up, kind/enhancement, team/ui
