### ISSUE TITLE
Webhook notifiers not working as for Microsoft teams

### ISSUE THREAD

**Issue by mattmattox** [rancher/rancher#20763] opened 2019-06-10 23:04 UTC
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
- Setup Rancher v2.2.1
- Create alert notifier using webhooks
- URL: https://outlook.office.com/webhook/####redacted######@####redacted######/IncomingWebhook/####redacted######/####redacted######

**Result:**
![image](https://user-images.githubusercontent.com/17145893/59232421-e3420780-8ba9-11e9-9b33-bac829873eb9.png)

**Other details that may be helpful:**
Running the following curl command inside the Rancher container returns a 200.
curl -v -X POST -H 'Content-type: application/json' --data '{"text":"Rancher Test"}' https://outlook.office.com/webhook/####redacted######@####redacted######/IncomingWebhook/####redacted######/####redacted######  

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): v2.2.1
- Installation option (single install/HA): HA

**Comment by dustinmhorvath** [comment] 2019-08-12 18:05
Apparently it returns a 200 upon receiving the webhook request. 

https://github.com/MicrosoftDocs/msteams-docs/issues/402

**Comment by SoarinFerret** [comment] 2019-09-27 22:23
Rancher is just using the prometheus alertmanager behind the scenes - so if you look at the [alertmanager docs](https://github.com/idealista/prom2teams), they reference the this project for Teams integration: https://github.com/idealista/prom2teams

The project looks like it just does a simple conversion.

Just stand that service up (they have a helm chart) and point to it for your webhook URL. I am using it with my prometheus server, I intend to set it up for rancher in the next few weeks.

**Comment by Tejeev** [comment] 2019-12-03 16:32
Duplicate of #15802

**Closed** 2019-12-03 16:33 UTC
Labels: [zube]: Unscheduled, area/notifiers, internal, kind/bug
