### ISSUE TITLE
[BUG] Rke2/k3s clusters have the error failed calling webhook even after webhook is installed for a few minutes

### ISSUE THREAD

**Issue by anupama2501** [rancher/rancher#42831] opened 2023-09-15 19:55 UTC
Information about the Cluster
**Rancher Server Setup**
- Rancher version: `v2.7.7-rc4` upgraded from `v2.7.6` also seen on `v2.7.6`
- Installation option (Docker install/Helm Chart): `Helm Chart`
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): `RKE1`, `v1.26.7`, `1.4.8`
- Proxy/Cert Details: `Self-signed`

**Information about the Cluster**
- Kubernetes version: `v1.26.8+k3s1` and `v1.26.8+rke2r1`
- Cluster Type (Local/Downstream): `Custom  3 worker, 1 etcd, 1 cp RKE1`

**Describe the bug**
On a restore to a migrated rancher server, rke2 and k3s clusters are stuck for a while in error state waiting for webhook for a few minuts even though webhook is updated/installed.

**To Reproduce**
1. Create a rancher server on v2.7.7 - HA1 server
2. Create 2 downstream clusters - rke2 and k3s node drivera
3. Take a backup - b1
4. Create an RKE1 cluster by following the guide https://rke.docs.rancher.com/installation
5. Bring down the nodes on HA1 server.
6. Restore the backed up file b1 on to the new cluster from step 4 by following the guide https://ranchermanager.docs.rancher.com/how-to-guides/new-user-guides/backup-restore-and-disaster-recovery/migrate-rancher-to-new-cluster
7. Install rancher on the new cluster - HA2
8. Check the nodes status on the HA2 server

**Result**
RKE2 and K3s clusters are stuck in errored state for a few minutes even after webhook is installed and active:
```
                 Failed to update fleet-default/anuk3sbig cluster.x-k8s.io/v1beta1, Kind=Cluster for rke-cluster fleet-default/anuk3sbig: Internal error occurred: failed calling webhook "default.cluster.cluster.x-k8s.io": failed to call webhook: Post "https://webhook-
                     service.cattle-system.svc:443/mutate-cluster-x-k8s-io-v1beta1-cluster?timeout=10s":dial tcp 10.43.181.127:443: connect: connection refused
```

**Expected Result**
Expected the clusters to come back up active as the webhook is installed and active.

**Additional context**
This was noticed in previous rancher server versions as well  v2.7.6

**Comment by MbolotSuse** [comment] 2023-09-19 19:46
One note from the team 1/webhook side: This error message doesn't (on it's own) indicate that the webhook is down for the full duration of cluster downtime. Rancher's controllers (and others with a sane back-off policy) can enter an exponential back-off after several failures, that may result in the controllers not retrying an operation until well after the webhook is available. To resolve this issue, the relevant controllers can implement a less aggressive exponential back-off, that may reduce the "extra downtime" between when the webhook is ready, and when the controllers are re-running for the clusters.

It's possible that the webhook is down for this entire time, but this should result in issues for other parts of the system (such as issues editing global/cluster roles). Absent any evidence of a broader impact (or specific evidence that the webhook is down for this entire time) I would recommend that team 2 investigate further why this specific component (v2 prov) seems to think the webhook is down for such a long time.

**Comment by bfbachmann** [comment] 2023-09-28 18:58
@anupama2501 I tried a few times but was unable to reproduce this. Were you seeing this behaviour consistently?

**Comment by anupama2501** [comment] 2023-10-18 09:59
@bfbachmann I noticed this yesterday while performing a backup/rollback it was noticed on an upgrade as well as on a roll back. While the webhook was active, the rke2 and k3s clusters were in error state waiting for the webhook to be active. It took a few minutes for the clusters to recover. This is sometimes noticed for a longer time ~10min and sometimes it is ~3 minutes.

Upgrade perfomed from v2.7.6 to v2.8.0-rc1 rancher HA server with local RKE1 cluster 
Downstream clusters - rke2 [1 etcd, 1 worker and 1 cp] and k3s[3 etcd, 3 worker and 2 cp] node drivers 

<img width="800" alt="2023-10-18_10-07-10" src="https://github.com/rancher/rancher/assets/38144301/071c6d32-14f0-481b-8cc9-6600778aa886">

**Comment by nickwsuse** [comment] 2023-10-18 12:14
I've also had upgrade scenarios (2.7.6 to v2.8-head) where the webhook error persisted for at least 15 minutes after the upgrade.

**Comment by nickwsuse** [comment] 2023-10-18 17:03
@bfbachmann I can't think of a time when I've personally seen it _never_ come up, but I've seen it take as long as three hours for the webhook to come up and clusters to then become active

**Comment by bfbachmann** [comment] 2023-12-08 19:22
I'm going to close this as it is not reliably reproducible. I _have_ seen the webhook take a while to come up before (it's often the last thing to boot), but much of this depends on the resources (CPU, RAM) available on the host system, and also the resource constraints placed on Docker (if you're using RKE1).

I think that if we see persistent issues where the webhook reliably takes a long time to book in certain cases, we can reopen this.

**Closed by bfbachmann** 2023-12-08 19:22 UTC
Labels: kind/bug, kind/bug-qa, area/provisioning-v2, team/hostbusters, area/capi, area/capr

**Comment by snegalvarsan** [comment] 2025-03-03 10:15
@anupama2501 @Sahota1225 @bfbachmann @MbolotSuse I have the same issue here,
Failed to create fleet-default/harvercluster cluster.x-k8s.io/v1beta1, Kind=Cluster for rke-cluster fleet-default/harvercluster: Internal error occurred: failed calling webhook "default.cluster.cluster.x-k8s.io": failed to call webhook: Post "https://webhook-service.cattle-system.svc:443/mutate-cluster-x-k8s-io-v1beta1-cluster?timeout=10s": service "webhook-service" not found, failed to create fleet-default/harvercluster-pool1 cluster.x-k8s.io/v1beta1, Kind=MachineDeployment for rke-cluster fleet-default/harvercluster: Internal error occurred: failed calling webhook "default.machinedeployment.cluster.x-k8s.io": failed to call webhook: Post "https://webhook-service.cattle-system.svc:443/mutate-cluster-x-k8s-io-v1beta1-machinedeployment?timeout=10s": service "webhook-service" not found
I'm using harvester version 1.1.3, with rancher running inside a docker container of version 2.6.13.
I'd be very glad if I get help, Thank you.
