### ISSUE TITLE
[ Monitoring v2 ] Pod: prometheus-rancher-monitoring-prometheus-0 CrashLoopBackOff if "Persistent Storage for Prometheus" option enabled

### ISSUE THREAD

**Issue by amorozkin** [rancher/rancher#34361] opened 2021-08-20 15:30 UTC
**Rancher Server Setup**
- Rancher version: 2.5.9
- Installation option Docker install:

**Information about the Cluster**
- Kubernetes version: v1.20.9
- Cluster Type (Local/Downstream): Downstream
- Provider: Imported (RKE)

**Describe the bug**
Pod _prometheus-rancher-monitoring-prometheus-0_ (container: _prometheus_) goes to CrashLoopBackOff with err="open /prometheus/queries.active: permission denied" if "Persistent Storage for Prometheus" (NFS type in my case) is enabled in Prometheus installation settings.

**To Reproduce**

- setup RKE cluster
- setup rancher using docker
- import cluster to Rancher
- go to Cluster Exploer -> Apps & Marketplace 
- install Monitoring Application with "Persistent Storage for Prometheus" enabled

**Result**
```
docker logs k8s_prometheus_prometheus-rancher-monitoring-prometheus-0_cattle-monitoring-system_ae9efe99-65e5-4ba8-bf4a-cb194d794867_6

level=info ts=2021-08-20T13:12:39.507Z caller=main.go:364 msg="Starting Prometheus" version="(version=2.24.0, branch=HEAD, revision=02e92236a8bad3503ff5eec3e04ac205a3b8e4fe)"
level=info ts=2021-08-20T13:12:39.507Z caller=main.go:369 build_context="(go=go1.15.6, user=root@d9f90f0b1f76, date=20210106-13:48:37)"
level=info ts=2021-08-20T13:12:39.507Z caller=main.go:370 host_details="(Linux 5.4.0-74-generic    #83~18.04.1-Ubuntu SMP Tue May 11 16:01:00 UTC 2021 x86_64 prometheus-rancher-monitoring-prometheus-0 (none))"
level=info ts=2021-08-20T13:12:39.507Z caller=main.go:371 fd_limits="(soft=1048576, hard=1048576)"
level=info ts=2021-08-20T13:12:39.507Z caller=main.go:372 vm_limits="(soft=unlimited, hard=unlimited)"
level=error ts=2021-08-20T13:12:39.508Z caller=query_logger.go:87 component=activeQueryTracker msg="Error opening query log file" file=/prometheus/queries.active err="open /prometheus/queries.active: permission denied"
panic: Unable to create mmap-ed active query log
```

**Expected Result**

**Screenshots**

**Additional context**
Think it relates to "subPath in volumeMount is not writable for non-root users " bug https://github.com/kubernetes/kubernetes/issues/41638 

POD settings:
```
  securityContext:
    fsGroup: 2000
    runAsGroup: 2000
    runAsNonRoot: true
    runAsUser: 1000
...
    - mountPath: /prometheus
      name: prometheus-rancher-monitoring-prometheus-db
      subPath: prometheus-db
```

_prometheus-db_ folder is created on the volume with permissions as _755 nobody:nogroup_ 
Changing _prometheus-db_ folder permissions on NFS server side _(chmod 777 /opt/share/rke01-monitoring/prometheus-db)_  is workaround  (or chown 1000:2000) - _queries.active_ file is created with 1000:2000 uid/gid then ...

**Comment by eminalemdar** [comment] 2021-09-10 11:21
I have the same error on Rancher version 2.6.0. When I try to create Monitoring stack enabling the Persistent Storage option for Prometheus using LocalPath prometheus container crashes. We tried to change the Helm options for example securityContext section but nothing worked for us.

**Comment by aiyengar2** [comment] 2021-09-22 18:26
@amorozkin  I was able to reproduce this in Rancher 2.5.9 on a downstream DO provisioned RKE1 cluster which used `rancher/local-path-provisioner` with Monitoring V2 using Prometheus Persistent Storage.

**However, I was unable to reproduce this in a similar cluster that was using Longhorn instead.** 

So the issue here is likely not specific to k8s / Monitoring but has to do with the way that rancher/local-path-provisioner (or whatever solution you are using for your NFS server) is configuring the underlying `subPath` folder's permissions.

---

We dealt with a similar situation to this in Monitoring V1 in https://github.com/rancher/rancher/issues/29149, where the solution was to override `prometheus.prometheusSpec.storageSpec.disableMountSubPath` to `true`; I tested this out on my local-path-provisioner instance and it fixed the issue. 

However, it should be noted that this field is deprecated based on [Prometheus Operator's Storage spec](https://github.com/prometheus-operator/prometheus-operator/blob/master/Documentation/api.md#storagespec) and might be removed in a new API version in the future based on https://github.com/prometheus-operator/prometheus-operator/pull/3143#issuecomment-615144868 and https://github.com/prometheus-operator/prometheus-operator/issues/3932#issuecomment-806538626.

The other option, if you are able to fix the permissions on the subpath to be associated with a user / group instead of `nobody:nogroup`, would be would be to modify the securityContext in prometheus.prometheusSpec.securityContext to update Prometheus to use your pre-provisioned group; you could also allow Prometheus to run as root, but I would not recommend that.

**Comment by aiyengar2** [comment] 2021-09-22 18:29
Since this is environment-specific and a workaround exists for that type of environment, I have moved this issue to`Needs Info` in case you want to provide more information if the suggested workaround does not work in your environment. But I do not believe there is a fix to be made to the Monitoring chart.

**Comment by guangbochen** [comment] 2021-09-23 07:24
if u are using the longhorn v1.2.0 and enabled the V2 monitoring in rancher v2.6.0 it will encounter a similar issue, a temp workaround can be found via  https://github.com/longhorn/longhorn/issues/2964#issuecomment-910969543.

**Comment by yasker** [comment] 2021-09-28 16:35
@guangbochen I believe this issue has been fixed with Longhorn v1.2.1-rcx, can you verify?

**Comment by guangbochen** [comment] 2021-09-29 01:28
Verified it works with the longhorn v1.2.1-rc2, should be fine to remove the harvester-related dependency, thanks.
```
➜  harvester-installer git:(rke2) ks get po -n cattle-monitoring-system
NAME                                                     READY   STATUS    RESTARTS   AGE
prometheus-rancher-monitoring-prometheus-0               3/3     Running   1          2d20h
rancher-monitoring-grafana-7f54b7d8bc-qb8mk              3/3     Running   0          2d20h
rancher-monitoring-kube-state-metrics-744b9448f4-gcp49   1/1     Running   0          2d20h
rancher-monitoring-operator-754bcd8cb4-ct85s             1/1     Running   0          2d20h
rancher-monitoring-prometheus-adapter-77568b975-92q64    1/1     Running   0          2d20h
rancher-monitoring-prometheus-node-exporter-jdtld        1/1     Running   0          2d20h
rancher-monitoring-prometheus-node-exporter-rnzgz        1/1     Running   57         2d19h
➜  harvester-installer git:(rke2) ks get pvc -n cattle-monitoring-system
NAME                                                                                     STATUS   VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS   AGE
prometheus-rancher-monitoring-prometheus-db-prometheus-rancher-monitoring-prometheus-0   Bound    pvc-98eb53d8-ae13-47a9-beb7-c5657b73762c   50Gi       RWO            longhorn       2d20h
rancher-monitoring-grafana                                                               Bound    pvc-b21988f1-df2b-4f2b-84ee-fc1e3261092a   10Mi       RWO            longhorn       2d20h
```

**Comment by ronhorton** [comment] 2022-02-25 20:48
waiting on merge of  https://github.com/rancher/charts/pull/1766  to be able to install latest version of monitoring.

**Comment by ronhorton** [comment] 2022-03-04 22:10
Verified this is working in `2.6-head Commit ID 93f3e13`

1. Created downstream cluster k8s 1.22
2. Installed longhorn
3. Installed monitoring with persistent storage for prometheus option enabled
4. Referenced longhorn in the PS option for monitoring

`Longhorn and monitoring functioned as expected. prometheus-rancher-monitoring-prometheus-0 did not error`

**Closed** 2022-03-10 13:34 UTC
Labels: area/monitoring, [zube]: Done, team/area3
