### ISSUE TITLE
Multinode vSphere Hardened custom cluster unable to register nodes

### ISSUE THREAD

**Issue by samkulkarni20** [rancher/rancher#38293] opened 2022-07-15 07:58 UTC
**Rancher Server Setup**
- Rancher version: v2.6-head([2c21373](https://github.com/rancher/rancher/commit/2c2137347e42f48ea9ab8e3ded0830f78050aef0))
- Installation option (Docker install/Helm Chart): Docker
   - ~~If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc):~~
- Proxy/Cert Details: Self Signed

**Information about the Cluster**
- Kubernetes version: any (tested with v1.23.8-rancher1-1)
- Cluster Type (Local/Downstream): Downstream
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider): vSphere 3 Node Hardened Custom Cluster with 1cp, 1etcd & 1wk node with [2.6 hardening guide](https://rancher.com/docs/rancher/v2.6/en/security/hardening-guides/rke-1.6-hardening-2.6/)

**User Information**
- What is the role of the user logged in? (Admin/Cluster Owner/Cluster Member/Project Owner/Project Member/Custom): Admin

   
**Describe the bug**

On creating a multinode hardened cluster, only first node gets registered & the cluster remains stuck in provisioning state.

**To Reproduce**
 
Steps followed:

- Provisioned VMs on engqa-7  environment.
- SSH'ed into the VMs, installed docker and followed [this](https://rancher.com/docs/rancher/v2.6/en/security/hardening-guides/rke-1.6-hardening-2.6/) cluster hardening guide to harden the cluster.
-  On creating a custom cluster from rancher UI and pasting the registration commands on the machines, only the first node got registered (which in this case was etcd node) and the rest were not showing up.
- The UI shows the ip address of the 1st node as the registered node. Although the role against that is incorrect. It shows the role of the node where the registration command is run last (which in this case was worker node). See screenshots
- The rancher server logs show:
```[INFO] rate limited provisioning-cluster-create(map[objectset.rio.cattle.io/hash:d46ac83b269feb6a792d85a86a2cf775356b7ace]) 1.00123093s```
- Whereas the control plane and worker node rancher-agent logs showed:
```level=info msg="Waiting for node to register. Either cluster is not ready for registering, cluster is currently provisioning, or etcd, controlplane and worker node have to be registered```

**Result**
On creating a multinode hardened cluster, only first node gets registered & the cluster remains stuck in provisioning state.

**Expected Result**

Cluster should get provisioned successfully.

**Screenshots**

![Screenshot from 2022-07-15 13-22-02](https://user-images.githubusercontent.com/15933023/179179119-e43a1aa3-447d-4c0e-b10f-705f0256c4a2.png)
![Screenshot from 2022-07-15 13-14-26](https://user-images.githubusercontent.com/15933023/179179131-ed5d5b43-b4ec-41ad-b12b-91f2deb8a9ca.png)

**Additional context**

May be similar to rancher/rancher#36986  
(SURE-5468)

**Comment by mitulshah-suse** [comment] 2022-08-22 09:45
This issue needs to be addressed by Jamie's team.
@sowmyav27

**Comment by annablender** [comment] 2022-11-14 22:36
I was able to reproduce this issue on rancher `v2.6.9.`

Repro steps
* Create a sphere node with a Rancher 2.6 docker install

* Provision VMs on engqa-7 environment: vSphere 3 Node Hardened Custom Cluster with 1cp, 1 etcd & 1 worker node Kubernetes 1.24.6-rancher1-1
* SSH into the VMs, install docker (did not harden the nodes. Issue showed up without hardening so that is not the problem)
* Create custom cluster in rancher UI
* Run registration commands on each node

Only the etcd node showed up in the rancher UI stuck with the message "Waiting to register with Kubernetes"

<img width="1550" alt="image" src="https://user-images.githubusercontent.com/12955547/201782242-08b658df-48a2-44d9-8557-9026069bc15e.png">

**Comment by annablender** [comment] 2022-11-29 16:11
@samkulkarni20 I've posted my progress above. Did you see the `Waiting for node to register` logs on the first attempted provision of the etcd node? Had the node been provisioned before/was dirty or was it clean? I want to note that adding a node with _all roles_ for a vsphere custom cluster in Rancher will provision successfully and may unblock your testing if that's what you need.

**Comment by annablender** [comment] 2022-11-29 17:56
After discussing with my team, only one node may be able to be registered because of duplicate hostname `localhost.` It is not the same as https://github.com/rancher/rancher/issues/29620, because the `NodeConfig` (node plan) returned from the kubernetes API is nil. I think here, the node is getting reenqueued if the rke sync is missed. There's just no plan to kick off the provisioning.

**Comment by annablender** [comment] 2022-11-30 00:27
@samkulkarni20 I was able to create an RKE1 cluster on DO nodes in the same way as you described with vsphere 
<img width="1538" alt="image" src="https://user-images.githubusercontent.com/12955547/204677438-510d78b0-9b9e-443a-8aa1-1c4551b4237b.png">. 1 cp, 1 etcd, 1 worker (registration cmd run on nodes in that order) so this issue appears to be isolated to vsphere.

The kubelet (node agent) requires nodes to have unique hostnames to be registered with the Kubernetes API, see code [here](https://github.com/rancher/rancher/blob/300948c14ad6a49a4331f2bfe32ec8525d91076a/cmd/agent/main.go#L476-L486). I think I was seeing your issue on vsphere, because all my nodes had the `localhost` hostname. When `rke up` is run, it runs the etcd plane first and if you had duplicate hostnames that would explain why you only saw the etcd node try to get registered first.

Try the following
1. Verify [required ports](https://docs.ranchermanager.rancher.io/v2.5/getting-started/installation-and-upgrade/installation-requirements/port-requirements) are open on your custom nodes 
2. Set unique hostnames on your vsphere nodes (or via the Rancher UI -> Registration -> advanced)
3. Try to register again

**Comment by annablender** [comment] 2022-12-05 22:23
I have confirmed the expected behavior on `dev-v2.7.`

vSphere re-testing
* Test 1 - 1 node, all roles (hostname all-role)
* Test 2 - 3 nodes, cp etcd worker same as the customer's setup (hostnames cp, etcd, worker)

Test 1
![image](https://user-images.githubusercontent.com/12955547/205752233-b3425bae-7306-4cb0-8859-3127f6d8eb97.png)

Test 2
![image](https://user-images.githubusercontent.com/12955547/205755685-415da938-1fef-4a17-99be-6e6fbacfc212.png)

When setting unique hostnames, both clusters provision successfully.

The duplicate hostname `localhost` was blocking registration of more than one node and that is why I was seeing only the node with the etcd-plane get registered. This also makes sense because RKE1 brings up the etcd-plane first before registering with Kubernetes, and requires nodes with all roles (cp etcd worker) to be registered before the cluster comes up as active. So nodes will hang in the ui with that `Waiting to register with Kubernetes` error message until both conditions are satisfied.

**Comment by annablender** [comment] 2022-12-07 16:08
Waiting for QA to verify above comment.

**Comment by jameson-mcghee** [comment] 2022-12-08 22:31
During testing on `v2.6.9`, I have validated that what @annablender has stated. Both that this issue can be reproduced without the need for Hardening the cluster as well as the fact that this issue is reproduced by utilizing a virtual machine template with an invalid configuration. This invalid configuration causes identical Hostname/DNS names, which prevents the provisioning of ETCD and Control Plane nodes (as described previously by @annablender). Based on that fact, I am closing this ticket.
If @samkulkarni20 provides additional information that conflicts with this determination, then we can address reopening this ticket at that time.

**Custom Cluster Registration  Commands:**
![image](https://user-images.githubusercontent.com/13294321/206580100-f57f5d65-116b-4803-8bcb-5788c72fc6e6.png)
![image](https://user-images.githubusercontent.com/13294321/206580121-a7c6277f-57be-4d3c-a913-a94616b80bd6.png)
![image](https://user-images.githubusercontent.com/13294321/206580134-4a0c36ef-255a-4e03-9a42-261cf4e12bb9.png)

**ETCD and Control Plans nodes not registering:**
![image](https://user-images.githubusercontent.com/13294321/206580287-1bde2635-8588-45bb-a419-a941c2a42984.png)

**Identical `localhost` Hostname/DNS Name:**
![image](https://user-images.githubusercontent.com/13294321/206580437-bfe4cc7c-7c98-4102-8e78-b025d783b7ee.png)
![image](https://user-images.githubusercontent.com/13294321/206580456-74fc0787-8e89-4332-8c93-de969c6166c0.png)
![image](https://user-images.githubusercontent.com/13294321/206580480-52603910-0c13-423c-8881-41b464d9ebf8.png)


**Successfully Provisioned Custom Cluster when using valid VM Template:**
![image](https://user-images.githubusercontent.com/13294321/206580827-9570e0fc-ad66-4f7c-b8d4-0516548de849.png)
![image](https://user-images.githubusercontent.com/13294321/206580845-2afdea16-1c4f-401c-978e-be5cc8d4ea93.png)
![image](https://user-images.githubusercontent.com/13294321/206580857-d73c9d05-861d-4d9d-bba1-c86aee9c2123.png)
![image](https://user-images.githubusercontent.com/13294321/206580879-53e0b6a6-188f-4f7e-8ac1-ed6bef0f0ab9.png)

**Closed by jameson-mcghee** 2022-12-08 22:31 UTC
Labels: priority/0, area/vsphere, kind/bug-qa, [zube]: Done, QA/S, team/area2, team/infracloud
