### ISSUE TITLE
helm job(helm-install-cattle-project-$Projectid-monitoring pod)got stuck after enabling project monitoring in air gap env

### ISSUE THREAD

**Issue by MKlimuszka** [rancher/rancher#38168] opened 2022-07-01 19:53 UTC
Issue description:
Customer noticed this issue in his environment  while testing internally. i.e., When enabling the project monitor it creates a helm job in the cattle-monitoring-system namespace that defaults to the “rancher/klipper-helm:v0.7.0-build20220315” and doesn´t append the image with our dtr (airgapped env remember)….I have to do this manually…then it works (see attached....bug2)

Business impact:
<text>

Troubleshooting steps:
<text>

Repro steps:

    Enable the project monitoring in air gapped environment
     

Workaround:
Is workararound available and implemented? yes
What is the workaround: Manually  add the image

Actual behavior:
fail to pull the image  (pod went to crash back loop)  due to as it fail to append the env variable to image name.  Please check the attached image

Expected behavior:
 Image should be pulled with  out any issue.

Files, logs, traces:
<text>

Additional notes:
For tracking  purpose raising the issue. Customer is eagerly waiting  for this feature since it was deprecated after 2.4
SURE-4691

**Comment by aiyengar2** [comment] 2022-10-11 17:19
@MKlimuszka this is a duplicate of https://github.com/rancher/prometheus-federator/issues/10, the issue was already fixed in https://github.com/rancher/helm-project-operator/pull/20 but is yet to be tested. Closing out this issue

**Comment by aiyengar2** [comment] 2022-10-11 17:20
Actually, I will re-open this issue to test on Rancher from QA's side since this fix was already done on the prometheus-federator repo in the above issue.

I'll close out the prometheus federator issue instead

**Comment by AndrewHoffmanQA** [comment] 2023-03-30 17:13
moving this back to 'to test' due to the ticket below blocking testing

https://github.com/rancher/rancher/issues/41016

**Comment by AndrewHoffmanQA** [comment] 2023-04-03 17:21
retest passed

testing information
- Airgapped 
- v2.7.2-rc8
- v1.25.6

installed project monitoring on local cluster and confirmed successful install and smoked tested the basic monitoring functionality.

 closing ticket

**Closed** 2023-04-03 17:21 UTC
Labels: kind/bug, area/test, priority/1, internal, area/monitoring, [zube]: QA Next up, team/area3, area/helm
