### ISSUE TITLE
Delete all hosts button in UI

### ISSUE THREAD

**Issue by aruneli** [rancher/rancher#1751] opened 2015-08-06 19:33 UTC
This is just an enhancement request. When there are multiple hosts, it would be easy if you have a "Delete all hosts" button that will delete and purge all the hosts.

**Comment by deniseschannon** [comment] 2015-08-06 19:54
Duplicate of https://github.com/rancher/rancher/issues/342

We want to add bulk actions for hosts and containers.

**Closed by deniseschannon** 2015-08-06 19:54 UTC
