### ISSUE TITLE
Rancher CLI Segmentation Fault

### ISSUE THREAD

**Issue by dizlexik** [rancher/rancher#17882] opened 2019-02-06 16:38 UTC
It looks like the v0.6.* line of the rancher-cli Docker image has not worked since v0.6.10.

I've tested each subsequent version and they all result in a "Segmentation fault" error.

**Comment by superseb** [comment] 2019-02-08 20:57
Can you supply more information on the usage so we can reproduce?


```
docker run rancher/cli:v0.6.10 --help
Rancher CLI, managing containers one UTF-8 character at a time

Usage: rancher [OPTIONS] COMMAND [arg...]

Version: v0.6.10

Options:
  --debug                           Debug logging
  --config value, -c value          Client configuration file (default ${HOME}/.rancher/cli.json) [$RANCHER_CLIENT_CONFIG]
  --environment value, --env value  Environment name or ID [$RANCHER_ENVIRONMENT]
  --url value                       Specify the Rancher API endpoint URL [$RANCHER_URL]
  --access-key value                Specify Rancher API access key [$RANCHER_ACCESS_KEY]
  --secret-key value                Specify Rancher API secret key [$RANCHER_SECRET_KEY]
  --host value                      Host used for docker command [$RANCHER_DOCKER_HOST]
  --wait, -w                        Wait for resource to reach resting state
  --wait-timeout value              Timeout in seconds to wait (default: 600)
  --wait-state value                State to wait for (active, healthy, etc)
  --help, -h                        show help
  --version, -v                     print the version

Commands:
  catalog           Operations with catalogs
  config            Setup client configuration
  docker            Run docker CLI on a host
  environment, env  Interact with environments
  events, event     Displays resource change events
  exec              Run a command on a container
  export            Export configuration yml for a stack as a tar archive or to local files
  hosts, host       Operations on hosts
  logs              Fetch the logs of a container
  ps                Show services/containers
  restart           Restart service, container
  rm                Delete service, container, stack, host, volume, secret
  run               Run services
  scale             Set number of containers to run for a service
  secrets, secret   Operations on secrets
  ssh               SSH into host
  stacks, stack     Operations on stacks
  start, activate   Start or activate service, container, host, stack
  stop, deactivate  Stop or deactivate service, container, host, stack
  up                Bring all services up
  volumes, volume   Operations on volumes
  inspect           View details for service, container, host, environment, stack, volume, secret
  wait              Wait for resources service, container, host, stack, machine, projectTemplate
  help              Shows a list of commands or help for one command

Run 'rancher COMMAND --help' for more information on a command.
```

**Comment by dizlexik** [comment] 2019-02-08 21:16
Sorry, I meant that v0.6.10 was the last version that did work correctly. Try with v0.6.11 and higher.

**Comment by ViceIce** [comment] 2019-02-25 08:16
`docker run --rm -it rancher/cli:v0.6.10 --version` > rancher version v0.6.10
`docker run --rm -it rancher/cli:v0.6.11 --version` > no output
`docker run --rm -it rancher/cli:v0.6.12 --version` > no output
`docker run --rm -it rancher/cli:v0.6.13 --version` > no output

```
docker run --rm -it --entrypoint /bin/sh rancher/cli:v0.6.13
/mnt # rancher --version
Segmentation fault (core dumped)
/mnt #
```

**Comment by krotovic** [comment] 2019-05-21 20:23
I would like to point out that tag `latest` on Docker Hub points to one of those not-working versions which might be confusing.

**Comment by danmilon** [comment] 2019-06-01 11:39
Got bitten by this too. I run the docker comment that is listed on https://github.com/rancher/cli.
Using the rancher/cli:v0.6.10 docker image worked fine.

**Comment by zeroum** [comment] 2019-10-11 21:09
The segmentation fault is still happening in rancher/cli2. Please also tag version/2.3

**Comment by aulem** [comment] 2019-11-12 16:52
hi folks,
tested today : docker image rancher/cli v0.6.11 to v0.6.14 are still segfaulting.  (same for latest) :-(

. it would be handy to add a README into the docker image repo : https://hub.docker.com/r/rancher/cli

regards

**Comment by zeroum** [comment] 2019-11-13 01:47
The problem seems to be in the build process itself, the releases and the Dockerfile of the release is fine.

I ended making this Dockerfile and building my own rancher-cli (+ kubectl) images to move on.

```
FROM alpine
RUN apk add --no-cache ca-certificates openssh-client curl jq
WORKDIR /usr/bin
RUN curl -s https://api.github.com/repos/rancher/cli/releases/latest | \
	jq '.assets[].browser_download_url | select(.|test(".+linux-amd64.+xz"))' -r | \
	xargs -n1 curl -Ls  | \
	tar -Jxxvf - --strip=2
RUN curl -LOs https://storage.googleapis.com/kubernetes-release/release/`curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt`/bin/linux/amd64/kubectl && \
	chmod +x /usr/bin/kubectl
WORKDIR /mnt
ENTRYPOINT ["rancher"]
CMD  ["--help"]

```

**Comment by deniseschannon** [comment] 2020-12-22 05:10
As 1.6 is EOL as of June 30, 2020, we are closing 1.6 issues.

**Closed by deniseschannon** 2020-12-22 05:10 UTC
Labels: [zube]: Unscheduled, area/cli, kind/bug, version/1.6

**Comment by kriscarle** [comment] 2021-03-16 19:44
In case anyone else ends up here trying to use the CLI on a Apple Silicon mac @zeroum's Dockerfile works great, I just changed the `linux-amd64` to `linux-arm`

Also works if you need to talk to old v1.6 servers 

```
FROM alpine
RUN apk add --no-cache ca-certificates openssh-client curl jq
WORKDIR /usr/bin
RUN curl -s https://api.github.com/repos/rancher/cli/releases/tags/v0.6.14 | \
	jq '.assets[].browser_download_url | select(.|test(".+linux-arm.+xz"))' -r | \
	xargs -n1 curl -Ls  | \
	tar -Jxxvf - --strip=2
WORKDIR /mnt
ENTRYPOINT ["rancher"]
```

to run it

```
docker build -t rancher-cli .
docker run --rm -it --env RANCHER_URL=https://YOUR_SITE --env RANCHER_ACCESS_KEY=abc123 --env RANCHER_SECRET_KEY=abc123 rancher-cli {rancher-cli command}
```
