### ISSUE TITLE
Exec shell not working for any of the containers in one of the hosts 

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#3596] opened 2016-02-11 21:38 UTC
Server Version - v0.58.0-rc2

Set up has 3 hosts

Not able to do exec shell for any container in one of the hosts. It stays in connecting state forever.

I get 401 Unauthorized error

```
WebSocket connection to 'ws://192.168.1.110:8080/v1/exec/?token=eyJhbGciOiJSUzI1NiJ9.eyJleHAiOjE0NTUyMjUzNzcsInN1YiI6ImNhdHRsZSIsImlzcyI6Imh0dHA6XC9cL2NhdHRsZS5pbyIsImhvc3RVdWlkIjoiYjYxNTgxN2UtZGY3ZS00YTYyLTg2NjUtMGRhYjQ1MmVlMmNlIiwiZXhlYyI6eyJBdHRhY2hTdGRpbiI6dHJ1ZSwiQXR0YWNoU3Rkb3V0Ijp0cnVlLCJUdHkiOnRydWUsIkNtZCI6WyJcL2Jpblwvc2giLCItYyIsIlRFUk09eHRlcm0tMjU2Y29sb3I7IGV4cG9ydCBURVJNOyBbIC14IFwvYmluXC9iYXNoIF0gJiYgKFsgLXggXC91c3JcL2Jpblwvc2NyaXB0IF0gJiYgXC91c3JcL2Jpblwvc2NyaXB0IC1xIC1jIFwiXC9iaW5cL2Jhc2hcIiBcL2RldlwvbnVsbCB8fCBleGV...FwvYmluXC9zaCJdLCJDb250YWluZXIiOiIwMGM5Mjk0MDJjMjAxZTU3NWYwNjY0NWY1NzcxNTM3YzBmODFjOTg5MzNlMDM4NjIwNzBiYjc3ZDJhYTYxYzYxIn0sImlhdCI6MTQ1NTIyNTA3Nywia2lkIjoiZGVmYXVsdCJ9.No9J0ZvJZAz1NxzDtnE8w8E0VtiDbSPHRPTQ8rLzjsYArThQgPJ2pBmDn97t0p42mJ1O9031ANc71a5NXHQ-P_M-BmgoC19L83lK_a2OHWqhacTqXCboDScOB8KH-2eDwAGBY39QDM1itLpclmY58idS33gsV_2Ceesk2m_3d3x5J6_w1b6thNYlqfM5AfNsm2vg6YZsir75EZyt4Fq4rg51JOTeC81RVjYrMTysqioWNST-oBLFO2VrxYsi-tB6UldSqNIQuBfIfrszJxtJU9vI9eWGWTIhKi0a8r--PEHRjWdGyIpvU9z3QJw25dI39rjY83ub2IBHhf3s7MYpvw' failed: HTTP Authentication failed; no valid credentials available
```

**Comment by will-chan** [comment] 2016-03-04 19:37
Not enough steps to consistently reproduce this.  If we can repro, let's just create a new issue to track this.

**Comment by jifeon** [comment] 2016-06-06 11:02
@will-chan  Hi, I have this error right now on rancher instance which have been run for months. Yesterday I could see logs and exec shell and now I can not. I have not performed any actions between these two states. I'm ready to post any useful debug info, pls tell what you need?

It's reproduced only for one node, but for all containers on it. But it's a node with production application, so it's a bit urgent for me. Maybe you can suggest some workarounds?

What I see in browser console:

```
WebSocket connection to 'ws://rancher.plyo.website/v1/exec/?token=eyJhbGciOiJSUzI1NiJ9.eyJleHAiOjE0NjUyMTA1NzcsInN1YiI6ImNhdHRsZSIsImlzcyI6Imh0dHA6XC9cL2NhdHRsZS5pbyIsImV4ZWMiOnsiQXR0YWNoU3RkaW4iOnRydWUsIkF0dGFjaFN0ZG91dCI6dHJ1ZSwiVHR5Ijp0cnVlLCJDbWQiOlsiXC9iaW5cL3NoIiwiLWMiLCJURVJNPXh0ZXJtLTI1NmNvbG9yOyBleHBvcnQgVEVSTTsgWyAteCBcL2JpblwvYmFzaCBdICYmIChbIC14IFwvdXNyXC9iaW5cL3NjcmlwdCBdICYmIFwvdXNyXC9iaW5cL3NjcmlwdCAtcSAtYyBcIlwvYmluXC9iYXNoXCIgXC9kZXZcL251bGwgfHwgZXhlYyBcL2JpblwvYmFzaCkgfHwgZXhlYyBcL2Jpblwvc2giXSwiQ29udGFpbmVyIjoiY...DU2ZWI5NWFkYmJjNTE4ODM2OGFmZTQ0YTdkY2M2MDJkMGQzM2U3YyJ9LCJob3N0VXVpZCI6ImE3ZjU3MGQzLWE5MTYtNDcwYS1iOTA4LWNkYTBiZTNkMjc4YyIsImlhdCI6MTQ2NTIxMDI3Nywia2lkIjoiZGVmYXVsdCJ9.fOtbKem2vhLT07o35pD3owU0xnK-NFa-22RwdFZ_1xSS68l9wEjhr5OfQQwXnhee_k9NzaZJTl6PPnEH4QTKUjcWyAi_n8D3SI_AcbxMZC_M42IqzbJ0pm2180GOS9vukCNRYiqYP3jn5uJJr00CgFRSYk8YmMtfOcxIH2Qm21H-Zb7FvRpLmfS_KKyHHGfs61m1FoM3IZN4JnfOo6hL_F8e5qyVEu9cGVI9YbrOOzzcmPrIPKPLxKDHFi-T-C6TMTEZvjUZj8Ul_0pmgAK61tt5rkkUuDJ1GX6WqWhh9lMD_873HpyESd0zkOvvOPomWvgr8q2j4e4_ePBQMN11BA' failed: HTTP Authentication failed; no valid credentials available
```

I've tried to log out and use another browser - the same effect.

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v1.0.1` Cattle: `v0.159.7` UI: `v1.0.5` |
|Access|`github` `admin`|
|Route|`environments.index`|

**Comment by jifeon** [comment] 2016-06-06 14:57
hmm, I was going to try your approach, but it just start working after I upgraded one of the containers...

**Comment by marcbachmann** [comment] 2016-07-08 08:31
I'm getting the same error. But for another reason than time settings.

One bug I found is that one host got registered with a wrong ip when it got deployed with a docker machine provider. I can still deploy services to it and they land on the correct host. But in the ui the wrong ip is show.
But I don't think that this is the problem for the websocket connection error because the websocket connection another host also doesn't work.
![image](https://cloud.githubusercontent.com/assets/431376/16681527/8ef84570-44f5-11e6-91ec-d0a93c629731.png)

**Comment by marcbachmann** [comment] 2016-07-11 06:20
For some reasons the backend can't find the host anymore. Maybe it's a bug in the dynamic registration of hosts in the [websocket-proxy](https://github.com/rancher/websocket-proxy).

```
time="2016-07-10T19:07:24Z" level=info msg="Exiting rancher-compose-executor" version=v0.8.5
time="2016-07-10T19:07:26Z" level=info msg="Starting rancher-compose-executor" version=v0.8.5
time="2016-07-10T19:07:26Z" level=info msg="Initializing event router" workerCount=10
time="2016-07-10T19:07:27Z" level=info msg="Connection established"
time="2016-07-10T21:24:13Z" level=info msg="Registering backend for host [0c511214-8849-4d36-9a05-8f9d2cc7c75a]"
time="2016-07-10T21:24:13Z" level=info msg="Registering backend for host [0c511214-8849-4d36-9a05-8f9d2cc7c75a]"
time="2016-07-10T21:24:15Z" level=info msg="Registering backend for host [1d464fe3-6d53-4347-9596-711e0f374d86]"
time="2016-07-10T21:24:15Z" level=info msg="Registering backend for host [1d464fe3-6d53-4347-9596-711e0f374d86]"
time="2016-07-11T06:04:51Z" level=info msg="Invalid HostUuid." hostUuid=0c511214-8849-4d36-9a05-8f9d2cc7c75a
time="2016-07-11T06:04:51Z" level=error msg="could not find host uuid"
time="2016-07-11T06:04:51Z" level=info msg="Invalid HostUuid." hostUuid=0c511214-8849-4d36-9a05-8f9d2cc7c75a
time="2016-07-11T06:04:51Z" level=error msg="could not find host uuid"
time="2016-07-11T06:04:52Z" level=info msg="Invalid HostUuid." hostUuid=0c511214-8849-4d36-9a05-8f9d2cc7c75a
```

My setup is very simple: https://github.com/upfrontIO/infrastructure/blob/master/structure/files/rancher.bootstrap.template
On the hosts I'm using ubuntu 16.04 & docker 1.11.

**Comment by cjellick** [comment] 2016-07-11 17:00
Odd that we see the host backend registering and then a request for that same host uuid fails. I wonder if the hosts are disconnecting. I'm not sure that we log when a host backend disconnects.

@marcbachmann do the rancher-agent logs on the the hosts indicate whether or not the host is connected?

**Comment by marcbachmann** [comment] 2016-07-11 22:44
No, they don't. Here's the log of that time.
Strange is that exactly after 12 hours it started working again. But that might be a coincidence.

```
2016-07-10 21:24:16 UTC time="2016-07-10T21:24:16Z" level="info" msg="Processing event: &docker.APIEvents{Status:\"start\", ID:\"f098e6d8a3c6fa0d15e46a2a19edb34cf69bf65ec2274c57f2598cc0eb18cb5f\", From:\"-simulated-\", Time:0}"
2016-07-10 21:24:16 UTC time="2016-07-10T21:24:16Z" level="info" msg="Processing event: &docker.APIEvents{Status:\"start\", ID:\"cf9818a8b567437515209f98ccb0ee579ce5d5f5f3405f5ec96a4a17530dec63\", From:\"-simulated-\", Time:0}"
2016-07-10 21:24:16 UTC time="2016-07-10T21:24:16Z" level="info" msg="Processing event: &docker.APIEvents{Status:\"start\", ID:\"b6556e39b2c6a07ed0680039476e74468c45a1c39e03721cdf0b2c2271294667\", From:\"-simulated-\", Time:0}"
2016-07-10 21:24:16 UTC time="2016-07-10T21:24:16Z" level="info" msg="Processing event: &docker.APIEvents{Status:\"start\", ID:\"59d8adea82f1784e7317f806456490629dea0f295babd9066a360055f1b63a1e\", From:\"-simulated-\", Time:0}"
2016-07-10 21:24:16 UTC time="2016-07-10T21:24:16Z" level="info" msg="Processing event: &docker.APIEvents{Status:\"start\", ID:\"ae9461b8ad974f257e90bc55126f9c77e03040f996efa85395a780a481851518\", From:\"-simulated-\", Time:0}"
2016-07-10 21:24:16 UTC time="2016-07-10T21:24:16Z" level="info" msg="Assigning IP [10.42.55.92/16], ContainerId [f098e6d8a3c6fa0d15e46a2a19edb34cf69bf65ec2274c57f2598cc0eb18cb5f], Pid [29229]"
2016-07-10 21:24:16 UTC time="2016-07-10T21:24:16Z" level="info" msg="Assigning IP [10.42.1.98/16], ContainerId [b6556e39b2c6a07ed0680039476e74468c45a1c39e03721cdf0b2c2271294667], Pid [669]"
2016-07-10 21:24:16 UTC time="2016-07-10T21:24:16Z" level="info" msg="Assigning IP [10.42.59.27/16], ContainerId [cf9818a8b567437515209f98ccb0ee579ce5d5f5f3405f5ec96a4a17530dec63], Pid [12628]"
2016-07-10 21:24:16 UTC I0710 21:24:16.136451 18794 storagedriver.go:50] Caching stats in memory for 2m0s
2016-07-10 21:24:16 UTC I0710 21:24:16.136720 18794 manager.go:138] cAdvisor running in container: "/docker/ae9461b8ad974f257e90bc55126f9c77e03040f996efa85395a780a481851518"
2016-07-10 21:24:16 UTC W0710 21:24:16.151159 18794 manager.go:146] unable to connect to Rkt api service: rkt: cannot tcp Dial rkt api service: dial tcp [::1]:15441: getsockopt: connection refused
2016-07-10 21:24:16 UTC I0710 21:24:16.163266 18794 fs.go:119] Filesystem partitions: map[/dev/vda:{mountpoint:/var/lib/docker/aufs major:254 minor:0 fsType:ext4 blockSize:0}]
2016-07-10 21:24:16 UTC E0710 21:24:16.170635 18794 machine.go:193] failed to get cache information for node 0: open /sys/devices/system/cpu/cpu0/cache: no such file or directory
2016-07-10 21:24:16 UTC E0710 21:24:16.170832 18794 machine.go:193] failed to get cache information for node 1: open /sys/devices/system/cpu/cpu1/cache: no such file or directory
2016-07-10 21:24:16 UTC E0710 21:24:16.170939 18794 machine.go:193] failed to get cache information for node 2: open /sys/devices/system/cpu/cpu2/cache: no such file or directory
2016-07-10 21:24:16 UTC E0710 21:24:16.171022 18794 machine.go:193] failed to get cache information for node 3: open /sys/devices/system/cpu/cpu3/cache: no such file or directory
2016-07-10 21:24:16 UTC E0710 21:24:16.171122 18794 machine.go:193] failed to get cache information for node 4: open /sys/devices/system/cpu/cpu4/cache: no such file or directory
2016-07-10 21:24:16 UTC E0710 21:24:16.171230 18794 machine.go:193] failed to get cache information for node 5: open /sys/devices/system/cpu/cpu5/cache: no such file or directory
2016-07-10 21:24:16 UTC I0710 21:24:16.174778 18794 manager.go:192] Machine: {NumCores:6 CpuFrequency:2393902 MemoryCapacity:8362426368 MachineID:aa74c7d5-c839-4202-bdb3-02c61967820e SystemUUID:aa74c7d5-c839-4202-bdb3-02c61967820e BootID:a832347a-c12c-4b4f-8ab1-f8377747fdeb Filesystems:[{Device:/dev/vda Capacity:49080274944 Type:vfs Inodes:3055616}] DiskMap:map[43:14:{Name:nbd14 Major:43 Minor:14 Size:0 Scheduler:deadline} 43:2:{Name:nbd2 Major:43 Minor:2 Size:0 Scheduler:deadline} 43:6:{Name:nbd6 Major:43 Minor:6 Size:0 Scheduler:deadline} 253:0:{Name:zram0 Major:253 Minor:0 Size:0 Scheduler:none} 43:11:{Name:nbd11 Major:43 Minor:11 Size:0 Scheduler:deadline} 43:4:{Name:nbd4 Major:43 Minor:4 Size:0 Scheduler:deadline} 43:7:{Name:nbd7 Major:43 Minor:7 Size:0 Scheduler:deadline} 43:8:{Name:nbd8 Major:43 Minor:8 Size:0 Scheduler:deadline} 254:0:{Name:vda Major:254 Minor:0 Size:50000000000 Scheduler:none} 43:1:{Name:nbd1 Major:43 Minor:1 Size:0 Scheduler:deadline} 43:15:{Name:nbd15 Major:43 Minor:15 Size:0 Scheduler:deadline} 43:3:{Name:nbd3 Major:43 Minor:3 Size:0 Scheduler:deadline} 43:9:{Name:nbd9 Major:43 Minor:9 Size:0 Scheduler:deadline} 43:13:{Name:nbd13 Major:43 Minor:13 Size:0 Scheduler:deadline} 43:10:{Name:nbd10 Major:43 Minor:10 Size:0 Scheduler:deadline} 43:12:{Name:nbd12 Major:43 Minor:12 Size:0 Scheduler:deadline} 43:5:{Name:nbd5 Major:43 Minor:5 Size:0 Scheduler:deadline} 254:16:{Name:vdb Major:254 Minor:16 Size:150000000000 Scheduler:none} 43:0:{Name:nbd0 Major:43 Minor:0 Size:0 Scheduler:deadline}] NetworkDevices:[{Name:eth0 MacAddress:de:19:50:1f:f0:03 Speed:0 Mtu:1500} {Name:ip6_vti0 MacAddress:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00 Speed:0 Mtu:1500} {Name:ip6gre0 MacAddress:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00 Speed:0 Mtu:1448} {Name:ip6tnl0 MacAddress:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00 Speed:0 Mtu:1452} {Name:sit0 MacAddress:00:00:00:00 Speed:0 Mtu:1480}] Topology:[{Id:0 Memory:0 Cores:[{Id:0 Threads:[0] Caches:[]}] Caches:[]} {Id:1 Memory:0 Cores:[{Id:0 Threads:[1] Caches:[]}] Caches:[]} {Id:2 Memory:0 Cores:[{Id:0 Threads:[2] Caches:[]}] Caches:[]} {Id:3 Memory:0 Cores:[{Id:0 Threads:[3] Caches:[]}] Caches:[]} {Id:4 Memory:0 Cores:[{Id:0 Threads:[4] Caches:[]}] Caches:[]} {Id:5 Memory:0 Cores:[{Id:0 Threads:[5] Caches:[]}] Caches:[]}] CloudProvider:Unknown InstanceType:Unknown InstanceID:None}
2016-07-10 21:24:16 UTC I0710 21:24:16.176451 18794 manager.go:198] Version: {KernelVersion:4.5.7-docker-2 ContainerOsVersion:Ubuntu 16.04 LTS DockerVersion:1.11.2 CadvisorVersion:0.23.2 CadvisorRevision:}
2016-07-10 21:24:16 UTC I0710 21:24:16.190116 18794 factory.go:217] registering Docker factory
2016-07-10 21:24:16 UTC E0710 21:24:16.190197 18794 manager.go:240] Registration of the rkt container factory failed: unable to communicate with Rkt api service: rkt: cannot tcp Dial rkt api service: dial tcp [::1]:15441: getsockopt: connection refused
2016-07-10 21:24:16 UTC I0710 21:24:16.190216 18794 factory.go:54] Registering systemd factory
2016-07-10 21:24:16 UTC I0710 21:24:16.193676 18794 factory.go:86] Registering Raw factory
2016-07-10 21:24:16 UTC I0710 21:24:16.197118 18794 manager.go:1072] Started watching for new ooms in manager
2016-07-10 21:24:16 UTC I0710 21:24:16.199884 18794 oomparser.go:185] oomparser using systemd
2016-07-10 21:24:16 UTC I0710 21:24:16.202631 18794 manager.go:281] Starting recovery of all containers
2016-07-10 21:24:16 UTC time="2016-07-10T21:24:16Z" level="info" msg="Connecting to proxy." url="wss://example.com/v1/connectbackend?token=[TOKEN]"
2016-07-10 21:24:16 UTC I0710 21:24:16.346800 18794 manager.go:286] Recovery completed
2016-07-10 21:24:16 UTC I0710 21:24:16.433411 18794 cadvisor.go:151] Starting cAdvisor version: 0.23.2- on port 9344
2016-07-11 09:24:27 UTC PID PGID S TTY TIME COMMAND
2016-07-11 09:24:27 UTC 18763 18473 S ? 00:00:15 /bin/bash /var/lib/cattle/pyagent/cattle/process_watcher.sh
2016-07-11 09:24:27 UTC 18768 18473 S ? 00:00:00 /bin/bash /var/lib/cattle/bin/cadvisor.sh cadvisor -logtostderr=true -listen_ip 127.0.0.1 -port 9344 -housekeeping_interval 1s -docker_root /var/lib/docker
2016-07-11 09:24:27 UTC 18771 18473 S ? 00:02:13 host-api -cadvisor-url http://127.0.0.1:9344 -logtostderr=true -ip 0.0.0.0 -port 9345 -auth=true -host-uuid 0c511214-8849-4d36-9a05-8f9d2cc7c75a -public-key /var/lib/cattle/etc/cattle/api.crt -cattle-url https://example.com/v1 -cattle-state-dir /var/lib/rancher/state/containers
2016-07-11 09:24:27 UTC 18794 18473 S ? 00:17:53 /var/log/rancher/.cadvisor -logtostderr=true -listen_ip 127.0.0.1 -port 9344 -housekeeping_interval 1s -docker_root /var/lib/docker
2016-07-11 09:24:27 UTC 18843 18473 S ? 00:00:02 journalctl -k -f
2016-07-11 09:24:27 UTC 29092 18473 R ? 00:00:00 ps -eO pgid
2016-07-11 09:24:27 UTC 29093 18473 S ? 00:00:00 grep -E PGID| 18473
2016-07-11 09:24:27 UTC  PID PGID S TTY TIME COMMAND
2016-07-11 09:24:27 UTC 18763 18473 S ? 00:00:15 /bin/bash /var/lib/cattle/pyagent/cattle/process_watcher.sh
2016-07-11 09:24:27 UTC 18768 18473 S ? 00:00:00 /bin/bash /var/lib/cattle/bin/cadvisor.sh cadvisor -logtostderr=true -listen_ip 127.0.0.1 -port 9344 -housekeeping_interval 1s -docker_root /var/lib/docker
2016-07-11 09:24:27 UTC 18771 18473 S ? 00:02:13 host-api -cadvisor-url http://127.0.0.1:9344 -logtostderr=true -ip 0.0.0.0 -port 9345 -auth=true -host-uuid 0c511214-8849-4d36-9a05-8f9d2cc7c75a -public-key /var/lib/cattle/etc/cattle/api.crt -cattle-url https://example.com/v1 -cattle-state-dir /var/lib/rancher/state/containers
2016-07-11 09:24:27 UTC 18794 18473 S ? 00:17:53 /var/log/rancher/.cadvisor -logtostderr=true -listen_ip 127.0.0.1 -port 9344 -housekeeping_interval 1s -docker_root /var/lib/docker
2016-07-11 09:24:27 UTC 18843 18473 S ? 00:00:02 journalctl -k -f
2016-07-11 09:24:27 UTC 29099 18473 R ? 00:00:00 ps -eO pgid
2016-07-11 09:24:27 UTC 29100 18473 S ? 00:00:00 grep -E PGID| 18473
2016-07-11 09:24:27 UTC PID 18473 has died doing kill 18768 18771 18794 18843
2016-07-11 09:24:27 UTC I0711 09:24:27.935792 18794 manager.go:1062] Exiting thread watching subcontainers
2016-07-11 09:24:27 UTC I0711 09:24:27.935969 18794 manager.go:347] Exiting global housekeeping thread
2016-07-11 09:24:27 UTC I0711 09:24:27.936046 18794 cadvisor.go:185] Exiting given signal: terminated
2016-07-11 09:24:29 UTC  PID PGID S TTY TIME COMMAND
2016-07-11 09:24:29 UTC 18763 18473 S ? 00:00:15 /bin/bash /var/lib/cattle/pyagent/cattle/process_watcher.sh
2016-07-11 09:24:29 UTC 29103 18473 R ? 00:00:00 ps -eO pgid
2016-07-11 09:24:29 UTC 29104 18473 S ? 00:00:00 grep -E PGID| 18473
2016-07-11 09:24:29 UTC Caught EXIT
2016-07-11 09:24:29 UTC  PID PGID S TTY TIME COMMAND
2016-07-11 09:24:29 UTC 18763 18473 S ? 00:00:15 /bin/bash /var/lib/cattle/pyagent/cattle/process_watcher.sh
2016-07-11 09:24:29 UTC 29110 18473 R ? 00:00:00 ps -eO pgid
2016-07-11 09:24:29 UTC 29111 18473 S ? 00:00:00 grep -E PGID| 18473
```

**Comment by cjellick** [comment] 2016-07-12 14:45
Sometimes when we've seen uncommon issues with websocket-proxy (wsp), it has been caused by some network device like a proxy or lb sitting between the hosts and the websocket proxy, causing problems with the websocket socket connection made from the host to wsp. 

You're logs don't really lead me to believe that that is the problem because we don't see the connection getting killed, but might as well sanity check that: 

do you have any network devices between the hosts and wsp that might not be configured properly to allow long-lived websocket connections?

**Comment by marcbachmann** [comment] 2016-07-12 15:09
I have rancher on with a public ip, dns on route53 and [caddy](https://github.com/mholt/caddy) for ssl negotiation (http2) & wss proxy.
the hosts are on scaleway and have a public ip.
So yes, there's a proxy in between. I assumed that the rancher websocket proxy would try a reconnect on a connection error. Isn't that the case?

**Comment by cjellick** [comment] 2016-07-12 15:26
You are correct, that is the case, though it is the _rancher-agent_ making an _outbound_ connection to wsp, not the other way around. One scenario I can dream up that could cause this is that the host still _thinks_ it is connected to wsp because the proxy has kept the connection open, but on the other side, the connection between the proxy and wsp was severed.

I don't have much evidence to support that, but lines up with the info we have in the logs.

When you say it started working exactly 12 hours later, I presume you mean it started working around `
2016-07-11 09:24:27`, right? The logs around
```
2016-07-11 09:24:27 UTC PID PGID S TTY TIME COMMAND
```
from your agent indicate that the agent was restarted at that time. This would make it work start working again because the websocket connection was reestablished.

**Comment by cjellick** [comment] 2016-07-13 13:26
@ibuildthecloud do the symptoms of this seem similar to the bug you ran into yesterday? I think it might be.

**Comment by marcbachmann** [comment] 2016-07-18 13:31
I'll try https://github.com/rancher/rancher/issues/5452. Thanks.

**Comment by rezonant** [comment] 2016-12-19 21:55
I had this problem after upgrading an environment between 1.1.4 and 1.2.0 (and kube 1.2 to 1.4) and I thought it was an upgrade gone wrong, but now after awhile my fresh new environment is exhibiting the same problem, with containers on node 1 being unreachable via Rancher's execute API (a 3 node setup). Glad to see there's already some analysis on the issue :-D

**Comment by rezonant** [comment] 2016-12-19 22:04
This is definitely still a problem in v1.2.0. 

I checked that the clocks are synced between my rancher server and the 3 nodes, that doesn't seem to be the problem.

Notably, on the affected host, when I don't get 401 Unauthorized, shell connections are extraordinarily short lived, as in, the connection closes while I am still typing, seconds after starting the shell.

**Comment by rezonant** [comment] 2016-12-19 22:12
Not sure which container logs I should check on the host, but Rancher Agent has something odd on the affected host:

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x57a114]

goroutine 35 [running]:
panic(0x834aa0, 0xc42000c070)
        /usr/local/go/src/runtime/panic.go:500 +0x1a1
github.com/rancher/agent/core/compute.setupNetworkMode(0x76, 0xc42047805a, 0x6, 0x15901060d78, 0xc42046a300, 0x34, 0x0, 0xc42028f940, 0x4, 0x4, ...)
        /go/src/github.com/rancher/agent/core/compute/compute_unix.go:189 +0x364
github.com/rancher/agent/core/compute.setupNetworking(0x76, 0xc42047805a, 0x6, 0x15901060d78, 0xc42046a300, 0x34, 0x0, 0xc42028f940, 0x4, 0x4, ...)
        /go/src/github.com/rancher/agent/core/compute/compute_unix.go:101 +0xd2
github.com/rancher/agent/core/compute.DoInstanceActivate(0x76, 0xc42047805a, 0x6, 0x15901060d78, 0xc42046a300, 0x34, 0x0, 0xc42028f940, 0x4, 0x4, ...)
        /go/src/github.com/rancher/agent/core/compute/compute.go:81 +0xae1
github.com/rancher/agent/handlers.(*ComputeHandler).InstanceActivate(0xc4201fb680, 0xc420126270, 0xc4202a1400, 0x3, 0x3)
        /go/src/github.com/rancher/agent/handlers/compute.go:44 +0x34a
github.com/rancher/agent/handlers.(*ComputeHandler).InstanceActivate-fm(0xc420126270, 0xc4202a1400, 0xc42029bc98, 0x3)
        /go/src/github.com/rancher/agent/handlers/common.go:32 +0x3e
github.com/rancher/agent/handlers.logRequest.func1(0xc420126270, 0xc4202a1400, 0xc42030dd60, 0x5e1101)
        /go/src/github.com/rancher/agent/handlers/common.go:49 +0x14a
github.com/rancher/agent/handlers.cleanLog.func1(0xc420126270, 0xc4202a1400, 0xc4204ee1c0, 0x19)
        /go/src/github.com/rancher/agent/handlers/common.go:55 +0x59
github.com/rancher/agent/vendor/github.com/rancher/event-subscriber/events.doWork(0xc420126270, 0xc4204f08a0, 0xc4202a1400, 0xcb9ac0, 0xc42044a790)
        /go/src/github.com/rancher/agent/vendor/github.com/rancher/event-subscriber/events/worker.go:94 +0x2a4
github.com/rancher/agent/vendor/github.com/rancher/event-subscriber/events.(*skippingWorkerPool).HandleWork.func1(0xc42028c2e0, 0x2, 0xc420126270, 0xc4204f08a0, 0xc4202a1400)
        /go/src/github.com/rancher/agent/vendor/github.com/rancher/event-subscriber/events/worker.go:47 +0x9e
created by github.com/rancher/agent/vendor/github.com/rancher/event-subscriber/events.(*skippingWorkerPool).HandleWork
        /go/src/github.com/rancher/agent/vendor/github.com/rancher/event-subscriber/events/worker.go:48 +0x19f

```

**Comment by rezonant** [comment] 2016-12-19 22:19
OK it looks like there was a container marked "Starting" on that host which was causing the above segfault, which was causing Rancher Agent to restart itself, which was interrupting the Websocket Proxy and causing the connection to end unexpectedly, immediately upon locating the container and Deleting it from the UI, I can now connect to the containers on host1 and they are not disconnecting themselves! :-D

**Comment by superseb** [comment] 2017-05-23 21:20
Going to close this, please open a new issue if anyone is still experiencing issues.

**Closed by superseb** 2017-05-23 21:20 UTC
Labels: kind/bug
