### ISSUE TITLE
Helm repo add rancher-stable failed

### ISSUE THREAD

**Issue by dommgifer** [rancher/rancher#22902] opened 2019-09-17 02:03 UTC
I try to use helm to install rancher.

But use command
`helm repo add rancher-stable https://releases.rancher.com/server-charts/stable`,
got error:
`Error: Looks like "https://releases.rancher.com/server-charts/stable" is not a valid chart repository or cannot be reached: Failed to fetch https://releases.rancher.com/server-charts/stable/index.yaml : 403 Forbidden`

But test url used command
`curl https://releases.rancher.com/server-charts/stable/index.yaml`,
it was worked.

How can I solved it?

**Comment by superseb** [comment] 2019-09-17 11:24
What version of Helm are you using? (`helm version --client`)

Sounds like a (transparent) proxy interfering and returning the 403, and curl possibly has a proxy configured?

**Comment by dommgifer** [comment] 2019-09-18 02:11
I tested v2.12.1 and v2.14.3 version.

**Comment by superseb** [comment] 2019-09-18 08:03
Without additional info, there is nothing much to say about this. Are you in a network restricted environment? What proxy configuration is set in the shell environment where you are executing the command and what has curl configured? What does `curl -v` show which network path is being used?

Closing it as not a bug, I added `rancher-stable` repository today and yesterday using v2.14.3 without problems but if you provide more info I can look into it.

**Closed by superseb** 2019-09-18 08:03 UTC
Labels: status/more-info

**Comment by dommgifer** [comment] 2019-09-18 09:26
Thanks for your reply!

I change another network environment, It was worked!

Maybe our office network blocked by releases.rancher.com .
