### ISSUE TITLE
Rancher 2.6.0 rancher-agent fails to provision on FIPS enabled node

### ISSUE THREAD

**Issue by danbarr** [rancher/rancher#34580] opened 2021-08-31 22:36 UTC
**Rancher Server Setup**
- Rancher version: 2.6.0
- Installation option (Docker install/Helm Chart): Helm
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): k3s
- Proxy/Cert Details: No proxy; cert issued by internal CA, CA root cert is properly available at /v3/settings/cacerts

**Information about the Cluster**
- Kubernetes version: 1.20.9
- Cluster Type (Local/Downstream): Downstream
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider): Custom OR Infrastructure Provider (tested w/Amazon EC2)

**Describe the bug**
Started testing Rancher 2.6.0 today. I attempted to create a new RKE 1.20.9 cluster using the Amazon EC2 infrastructure provider, with a RHEL 7 base AMI that has FIPS mode enabled. The node successfully installs Docker and launches the rancher-agent container, but it fails to provision with an error, `crypto/fips/fips.c:156: OpenSSL internal error: FATAL FIPS SELFTEST FAILURE`.

Also attempted a Custom cluster and running the generated docker command on a FIPS-enabled node, with the same result.

This worked with the same base AMI as of 2.5.9.

**To Reproduce**
Custom: Prepare a FIPS-enabled node (ex: RHEL 7). Create a custom cluster, and run the generated docker run command on the node. The rancher-agent container will start but immediately enter a restarting loop.

Infrastructure provider: Create a cluster using an infrastructure provider node template. Use a base node image which is FIPS-enabled (ex: a RHEL 7 AMI with FIPS mode enabled). The node will reach the "Waiting to register with Kubernetes" state but go no further.

For either case, connect to the node, run `docker logs <rancher-agent container id>` and observe the error.

**Result**
The rancher-agent container enters a restart loop with the following error (hostname and IP addresses sanitized):
```
INFO: https://rancher.example.com/ping is accessible
INFO: rancher.example.com resolves to 1.1.1.1 2.2.2.2
crypto/fips/fips.c:156: OpenSSL internal error: FATAL FIPS SELFTEST FAILURE
ERROR: The environment variable CATTLE_CA_CHECKSUM is set but there is no CA certificate configured at https://rancher.example.com/v3/settings/cacerts
```

If FIPS mode is disabled and the node is rebooted, provisioning completes successfully.

**Expected Result**
Node should successfully provision with FIPS mode enabled.

**Comment by danbarr** [comment] 2021-08-31 22:56
I believe the error is being thrown by curl, right here:

https://github.com/rancher/rancher/blob/9cf0c6c00e62556e9c32ee99c2025e8fe0f11f20/package/run.sh#L227

**Comment by danbarr** [comment] 2021-09-01 20:46
So it working on 2.4 and 2.5 (probably earlier too) was a matter of "works, but not supported"? Or is this a new thing with 2.6 specifically?

Is this a roadmap item to officially support? This is kind of a surprising stance given how government/federal "friendly" Rancher has historically positioned itself.

**Comment by bgulla** [comment] 2021-09-02 18:45
we're looking into this.

**Comment by msmeissn** [comment] 2021-09-03 09:11
is libopenssl1_1-hmac RPM in the container and has it the same version as the libopenssl1_1 RPM?

**Comment by nikkelma** [comment] 2021-09-08 23:08
Hey all, put together a quick FAQ around this topic here: https://gist.github.com/nikkelma/ffc95534cbb00385b86965a4a528431c

The team is targeting a near future release of Rancher to fix this regression.

Even though the subcomponents involved may not have been guaranteed to be using FIPS compliant modules, connectivity from downstream clusters with FIPS enabled should still be possible and will be restored in this near future release.

**Comment by danbarr** [comment] 2021-09-09 12:56
Thank you! That's a very clear summary of the FIPS status of Rancher and of the regression in 2.6.

**Comment by cjellick** [comment] 2021-09-14 16:16
This should be addressed by updating our BCI based images to `15.3.17.8.1`.

Example: https://github.com/rancher/rancher/blob/release/v2.6/package/Dockerfile.agent#L5

I think there are three Dockerfiles that need updated, would have to search the codebase for the image name referenced above to be sure.

**Comment by Jono-SUSE-Rancher** [comment] 2021-09-20 14:57
@cwayne18 - Are you guys able to provide a little guidance in terms of how to do proper validation for this issue once the version image was updated?

**Closed** 2021-09-21 21:58 UTC
Labels: [zube]: To Test

**Comment by elisiano** [comment] 2022-04-04 00:22
Howdy folks, I might need some directions.
I am trying to run rancher in docker on a Synology NAS (and no, I don't have any other hardware to run it on because that's been allocated to Harvester and I wanted to try the integration).

Not that it matters, but I run it from the CLI as follows:
```
root@DiskStation:~# docker run -d --privileged -v /volume2/docker/rancher:/var/lib/rancher:rw -p 3080:80 -p 3443:443 --name rancher rancher/rancher:v2.6.4
```

Is there anything that I need to do to make it work on such host? (bear in mind it's a kind of appliance, the options to install additional software are limited).

Thanks for any help.

<details><summary>Relevant Error Logs</summary>

```
root@DiskStation:~# docker logs rancher | grep -C1 "FATAL FIPS SELFTEST FAILURE"
I0403 23:43:36.974563      33 leaderelection.go:248] attempting to acquire leader lease kube-system/cattle-controllers...
I0403 23:43:37.044200      33 leaderelection.go:258] successfully acquired lease kube-system/cattle-controllers
W0403 23:43:43.383286      33 warnings.go:80] policy/v1beta1 PodSecurityPolicy is deprecated in v1.21+, unavailable in v1.25+
E0403 23:43:53.864053      33 gvks.go:69] failed to sync schemas: failed to sync cache for cluster.x-k8s.io/v1alpha3, Kind=Cluster
2022/04/03 23:43:58 [ERROR] error syncing 'system-library': handler catalog: Clone failed: Cloning into 'management-state/catalog-cache/6bda4fa402575032915dc735ad66131a2f8a36ff38c6fb593402ad315fbfdf85'...
crypto/fips/fips.c:521: OpenSSL internal error: FATAL FIPS SELFTEST FAILURE
error: git-remote-https died of signal 6
--
2022/04/03 23:43:58 [ERROR] error syncing 'library': handler catalog: Clone failed: Cloning into 'management-state/catalog-cache/380859f1003fe7603cddc6c15b34b7263f1f0deaa92ddcde465811d032ee7078'...
crypto/fips/fips.c:521: OpenSSL internal error: FATAL FIPS SELFTEST FAILURE
error: git-remote-https died of signal 6
--
2022/04/03 23:43:58 [ERROR] error syncing 'helm3-library': handler catalog: Clone failed: Cloning into 'management-state/catalog-cache/f341cfdfa521a9aa2b993cb34b26bb91b2d173ef1a7df8d41b8921b0e4f82788'...
crypto/fips/fips.c:521: OpenSSL internal error: FATAL FIPS SELFTEST FAILURE
error: git-remote-https died of signal 6
--
2022/04/03 23:44:00 [ERROR] error syncing 'library': handler catalog: Clone failed: Cloning into 'management-state/catalog-cache/380859f1003fe7603cddc6c15b34b7263f1f0deaa92ddcde465811d032ee7078'...
crypto/fips/fips.c:521: OpenSSL internal error: FATAL FIPS SELFTEST FAILURE
error: git-remote-https died of signal 6
--
2022/04/03 23:44:00 [ERROR] error syncing 'helm3-library': handler catalog: Clone failed: Cloning into 'management-state/catalog-cache/f341cfdfa521a9aa2b993cb34b26bb91b2d173ef1a7df8d41b8921b0e4f82788'...
crypto/fips/fips.c:521: OpenSSL internal error: FATAL FIPS SELFTEST FAILURE
error: git-remote-https died of signal 6
--
2022/04/03 23:44:00 [ERROR] error syncing 'system-library': handler catalog: Clone failed: Cloning into 'management-state/catalog-cache/6bda4fa402575032915dc735ad66131a2f8a36ff38c6fb593402ad315fbfdf85'...
crypto/fips/fips.c:521: OpenSSL internal error: FATAL FIPS SELFTEST FAILURE
error: git-remote-https died of signal 6
--
2022/04/03 23:44:01 [ERROR] error syncing 'library': handler catalog: Clone failed: Cloning into 'management-state/catalog-cache/380859f1003fe7603cddc6c15b34b7263f1f0deaa92ddcde465811d032ee7078'...
crypto/fips/fips.c:521: OpenSSL internal error: FATAL FIPS SELFTEST FAILURE
error: git-remote-https died of signal 6
--
2022/04/03 23:44:01 [ERROR] error syncing 'helm3-library': handler catalog: Clone failed: Cloning into 'management-state/catalog-cache/f341cfdfa521a9aa2b993cb34b26bb91b2d173ef1a7df8d41b8921b0e4f82788'...
crypto/fips/fips.c:521: OpenSSL internal error: FATAL FIPS SELFTEST FAILURE
error: git-remote-https died of signal 6
--
2022/04/03 23:44:02 [ERROR] error syncing 'system-library': handler catalog: Clone failed: Cloning into 'management-state/catalog-cache/6bda4fa402575032915dc735ad66131a2f8a36ff38c6fb593402ad315fbfdf85'...
crypto/fips/fips.c:521: OpenSSL internal error: FATAL FIPS SELFTEST FAILURE
error: git-remote-https died of signal 6
--
2022/04/03 23:44:02 [ERROR] error syncing 'library': handler catalog: Clone failed: Cloning into 'management-state/catalog-cache/380859f1003fe7603cddc6c15b34b7263f1f0deaa92ddcde465811d032ee7078'...
crypto/fips/fips.c:521: OpenSSL internal error: FATAL FIPS SELFTEST FAILURE
error: git-remote-https died of signal 6
--
2022/04/03 23:44:03 [ERROR] error syncing 'helm3-library': handler catalog: Clone failed: Cloning into 'management-state/catalog-cache/f341cfdfa521a9aa2b993cb34b26bb91b2d173ef1a7df8d41b8921b0e4f82788'...
crypto/fips/fips.c:521: OpenSSL internal error: FATAL FIPS SELFTEST FAILURE
error: git-remote-https died of signal 6
E0403 23:44:04.229826      33 gvks.go:69] failed to sync schemas: unable to retrieve the complete list of server APIs: rke-machine-config.cattle.io/v1: the server could not find the requested resource
E0403 23:44:04.494616      33 gvks.go:69] failed to sync schemas: unable to retrieve the complete list of server APIs: rke-machine-config.cattle.io/v1: the server could not find the requested resource
E0403 23:44:04.780343      33 gvks.go:69] failed to sync schemas: unable to retrieve the complete list of server APIs: rke-machine-config.cattle.io/v1: the server could not find the requested resource
--
2022/04/03 23:44:04 [ERROR] error syncing 'system-library': handler catalog: Clone failed: Cloning into 'management-state/catalog-cache/6bda4fa402575032915dc735ad66131a2f8a36ff38c6fb593402ad315fbfdf85'...
crypto/fips/fips.c:521: OpenSSL internal error: FATAL FIPS SELFTEST FAILURE
error: git-remote-https died of signal 6
--
2022/04/03 23:44:04 [ERROR] error syncing 'library': handler catalog: Clone failed: Cloning into 'management-state/catalog-cache/380859f1003fe7603cddc6c15b34b7263f1f0deaa92ddcde465811d032ee7078'...
crypto/fips/fips.c:521: OpenSSL internal error: FATAL FIPS SELFTEST FAILURE
error: git-remote-https died of signal 6
E0403 23:44:05.149347      33 gvks.go:69] failed to sync schemas: unable to retrieve the complete list of server APIs: rke-machine.cattle.io/v1: the server could not find the requested resource
E0403 23:44:05.360849      33 gvks.go:69] failed to sync schemas: unable to retrieve the complete list of server APIs: rke-machine.cattle.io/v1: the server could not find the requested resource
--
2022/04/03 23:44:05 [ERROR] error syncing 'helm3-library': handler catalog: Clone failed: Cloning into 'management-state/catalog-cache/f341cfdfa521a9aa2b993cb34b26bb91b2d173ef1a7df8d41b8921b0e4f82788'...
crypto/fips/fips.c:521: OpenSSL internal error: FATAL FIPS SELFTEST FAILURE
error: git-remote-https died of signal 6
--
2022/04/03 23:44:07 [ERROR] error syncing 'library': handler catalog: Clone failed: Cloning into 'management-state/catalog-cache/380859f1003fe7603cddc6c15b34b7263f1f0deaa92ddcde465811d032ee7078'...
crypto/fips/fips.c:521: OpenSSL internal error: FATAL FIPS SELFTEST FAILURE
error: git-remote-https died of signal 6
--
2022/04/03 23:44:07 [ERROR] error syncing 'helm3-library': handler catalog: Clone failed: Cloning into 'management-state/catalog-cache/f341cfdfa521a9aa2b993cb34b26bb91b2d173ef1a7df8d41b8921b0e4f82788'...
crypto/fips/fips.c:521: OpenSSL internal error: FATAL FIPS SELFTEST FAILURE
error: git-remote-https died of signal 6
--
2022/04/03 23:44:07 [ERROR] error syncing 'system-library': handler catalog: Clone failed: Cloning into 'management-state/catalog-cache/6bda4fa402575032915dc735ad66131a2f8a36ff38c6fb593402ad315fbfdf85'...
crypto/fips/fips.c:521: OpenSSL internal error: FATAL FIPS SELFTEST FAILURE
error: git-remote-https died of signal 6
--
2022/04/03 23:44:08 [ERROR] error syncing 'system-library': handler catalog: Clone failed: Cloning into 'management-state/catalog-cache/6bda4fa402575032915dc735ad66131a2f8a36ff38c6fb593402ad315fbfdf85'...
crypto/fips/fips.c:521: OpenSSL internal error: FATAL FIPS SELFTEST FAILURE
error: git-remote-https died of signal 6
--
2022/04/03 23:44:08 [ERROR] error syncing 'library': handler catalog: Clone failed: Cloning into 'management-state/catalog-cache/380859f1003fe7603cddc6c15b34b7263f1f0deaa92ddcde465811d032ee7078'...
crypto/fips/fips.c:521: OpenSSL internal error: FATAL FIPS SELFTEST FAILURE
error: git-remote-https died of signal 6
--
2022/04/03 23:44:08 [ERROR] error syncing 'helm3-library': handler catalog: Clone failed: Cloning into 'management-state/catalog-cache/f341cfdfa521a9aa2b993cb34b26bb91b2d173ef1a7df8d41b8921b0e4f82788'...
crypto/fips/fips.c:521: OpenSSL internal error: FATAL FIPS SELFTEST FAILURE
error: git-remote-https died of signal 6
E0403 23:44:11.193029      33 gvks.go:69] failed to sync schemas: failed to sync cache for rke-machine.cattle.io/v1, Kind=HarvesterMachineTemplate
--
2022/04/03 23:44:12 [ERROR] error syncing 'system-library': handler catalog: Clone failed: Cloning into 'management-state/catalog-cache/6bda4fa402575032915dc735ad66131a2f8a36ff38c6fb593402ad315fbfdf85'...
crypto/fips/fips.c:521: OpenSSL internal error: FATAL FIPS SELFTEST FAILURE
error: git-remote-https died of signal 6
--
2022/04/03 23:44:12 [ERROR] error syncing 'library': handler catalog: Clone failed: Cloning into 'management-state/catalog-cache/380859f1003fe7603cddc6c15b34b7263f1f0deaa92ddcde465811d032ee7078'...
crypto/fips/fips.c:521: OpenSSL internal error: FATAL FIPS SELFTEST FAILURE
error: git-remote-https died of signal 6
--
2022/04/03 23:44:12 [ERROR] error syncing 'helm3-library': handler catalog: Clone failed: Cloning into 'management-state/catalog-cache/f341cfdfa521a9aa2b993cb34b26bb91b2d173ef1a7df8d41b8921b0e4f82788'...
crypto/fips/fips.c:521: OpenSSL internal error: FATAL FIPS SELFTEST FAILURE
error: git-remote-https died of signal 6
--
2022/04/03 23:44:13 [ERROR] error syncing 'system-library': handler catalog: Clone failed: Cloning into 'management-state/catalog-cache/6bda4fa402575032915dc735ad66131a2f8a36ff38c6fb593402ad315fbfdf85'...
crypto/fips/fips.c:521: OpenSSL internal error: FATAL FIPS SELFTEST FAILURE
error: git-remote-https died of signal 6
--
2022/04/03 23:44:13 [ERROR] error syncing 'library': handler catalog: Clone failed: Cloning into 'management-state/catalog-cache/380859f1003fe7603cddc6c15b34b7263f1f0deaa92ddcde465811d032ee7078'...
crypto/fips/fips.c:521: OpenSSL internal error: FATAL FIPS SELFTEST FAILURE
error: git-remote-https died of signal 6
--
2022/04/03 23:44:13 [ERROR] error syncing 'helm3-library': handler catalog: Clone failed: Cloning into 'management-state/catalog-cache/f341cfdfa521a9aa2b993cb34b26bb91b2d173ef1a7df8d41b8921b0e4f82788'...
crypto/fips/fips.c:521: OpenSSL internal error: FATAL FIPS SELFTEST FAILURE
error: git-remote-https died of signal 6
--
2022/04/03 23:44:14 [ERROR] error syncing 'system-library': handler catalog: Clone failed: Cloning into 'management-state/catalog-cache/6bda4fa402575032915dc735ad66131a2f8a36ff38c6fb593402ad315fbfdf85'...
crypto/fips/fips.c:521: OpenSSL internal error: FATAL FIPS SELFTEST FAILURE
error: git-remote-https died of signal 6
--
2022/04/03 23:44:14 [ERROR] error syncing 'library': handler catalog: Clone failed: Cloning into 'management-state/catalog-cache/380859f1003fe7603cddc6c15b34b7263f1f0deaa92ddcde465811d032ee7078'...
crypto/fips/fips.c:521: OpenSSL internal error: FATAL FIPS SELFTEST FAILURE
error: git-remote-https died of signal 6
--
2022/04/03 23:44:14 [ERROR] error syncing 'helm3-library': handler catalog: Clone failed: Cloning into 'management-state/catalog-cache/f341cfdfa521a9aa2b993cb34b26bb91b2d173ef1a7df8d41b8921b0e4f82788'...
crypto/fips/fips.c:521: OpenSSL internal error: FATAL FIPS SELFTEST FAILURE
error: git-remote-https died of signal 6
--
2022/04/03 23:44:15 [ERROR] error syncing 'system-library': handler catalog: Clone failed: Cloning into 'management-state/catalog-cache/6bda4fa402575032915dc735ad66131a2f8a36ff38c6fb593402ad315fbfdf85'...
crypto/fips/fips.c:521: OpenSSL internal error: FATAL FIPS SELFTEST FAILURE
error: git-remote-https died of signal 6
--
2022/04/03 23:44:28 [ERROR] error syncing 'helm3-library': handler catalog: Clone failed: Cloning into 'management-state/catalog-cache/f341cfdfa521a9aa2b993cb34b26bb91b2d173ef1a7df8d41b8921b0e4f82788'...
crypto/fips/fips.c:521: OpenSSL internal error: FATAL FIPS SELFTEST FAILURE
error: git-remote-https died of signal 6
--
2022/04/03 23:44:28 [ERROR] error syncing 'library': handler catalog: Clone failed: Cloning into 'management-state/catalog-cache/380859f1003fe7603cddc6c15b34b7263f1f0deaa92ddcde465811d032ee7078'...
crypto/fips/fips.c:521: OpenSSL internal error: FATAL FIPS SELFTEST FAILURE
error: git-remote-https died of signal 6
```
</details>

**Comment by tsmithco** [comment] 2022-10-26 12:15
> Howdy folks, I might need some directions.
> 
> I am trying to run rancher in docker on a Synology NAS (and no, I don't have any other hardware to run it on because that's been allocated to Harvester and I wanted to try the integration).
> 
> Not that it matters, but I run it from the CLI as follows:
> 
> ```
> root@DiskStation:~# docker run -d --privileged -v /volume2/docker/rancher:/var/lib/rancher:rw -p 3080:80 -p 3443:443 --name rancher rancher/rancher:v2.6.4
> ```
> 
> Is there anything that I need to do to make it work on such host? (bear in mind it's a kind of appliance, the options to install additional software are limited).
> 
> Thanks for any help.
> 
> Relevant Error Logs
> Full Logs

You ever get this resolved?  Same issues with me trying to deploy in docker on synology.

**Comment by elisiano** [comment] 2022-10-26 12:20
> 
> You ever get this resolved?  Same issues with me trying to deploy in docker on synology.

@tsmithco no unfortunately. I moved to a different solution.

**Comment by 631068264** [comment] 2022-11-15 01:20
2.6.5 agent get same problem
```
crypto/fips/fips.c:521: OpenSSL internal error: FATAL FIPS SELFTEST FAILURE
INFO: Arguments: --server https://rancher.uniin.cn:31628 --token REDACTED --ca-checksum 95170a1a359ecbc963255afbf112ee6193d65865b5e41606ae899f0447036f50 --worker
```
