### ISSUE TITLE
[BUG] `system-agent-installer-rancher` broken on `arm64`

### ISSUE THREAD

**Issue by flaviodsr** [rancher/rancher#38589] opened 2022-08-11 13:38 UTC
**Rancher Server Setup**
- Rancher version: v.2.6.6

**Information about the Cluster**
- Kubernetes version: v1.23.8+k3s1
- Cluster Type (Local/Downstream): local
 
**Describe the bug**
Installing rancher using `rancher/system-agent-installer-rancher:v2.6.6` on a arm64 system fails with the following error message:
```
Error: "helm upgrade" requires 2 arguments

Usage:  helm upgrade [RELEASE] [CHART] [flags]
```
Looking inside the container, turns out that it includes two versions of the rancher helm chart:
```
 13K Jul  1 01:05 rancher-2.6.6-dirty.commit-9b2f2ae0e.tgz
4.2K Jul  1 01:05 rancher-2.6.6.tgz
```

**To Reproduce**
On a arm64 system with rancher-system-agent installed, create a plan to install rancher, for example:
```
{
    "instructions": [
        {
            "name": "rancher",
            "saveOutput": true,
            "image": "rancher/system-agent-installer-rancher:v2.6.6",
            "env": [
                "KUBECONFIG=/etc/rancher/k3s/k3s.yaml",
                "RANCHER_VALUES=/var/lib/rancher/values.yaml"
            ]
        }
    ]
}
```

**Result**
rancher-system-agent fails to apply the plan, with the following error message:
```
Error: "helm upgrade" requires 2 arguments

Usage:  helm upgrade [RELEASE] [CHART] [flags]
```

**Expected Result**
rancher-system-agent successfully execute the plan and rancher is installed.

**Additional context**
The root cause of the bug is probably a packing issue where two versions of the helm chart are included in the container consequently when https://github.com/rancher/rancher/blob/release/v2.6/package/installer-run.sh is executed it gets both helm charts as arguments and fails.

**Comment by snasovich** [comment] 2022-10-03 20:53
Likely duplicate of https://github.com/rancher/rancher/issues/34658

**Comment by snasovich** [comment] 2024-03-18 14:55
Closing as this is now resolved as part of https://github.com/rancher/rancher/issues/34658

**Closed by snasovich** 2024-03-18 14:55 UTC
Labels: kind/bug
