### ISSUE TITLE
Concurrent map read/write panic in authprovisioningv2 controller 

### ISSUE THREAD

**Issue by Oats87** [rancher/rancher#36845] opened 2022-03-10 21:38 UTC
CI run https://drone-publish.rancher.io/rancher/rancher/7459/2/2 failed due to Rancher panic

Analysis of Rancher logs has a panic like:
```

fatal error: concurrent map read and map write

goroutine 30298 [running]:
runtime.throw({0x4030875, 0x3f})
	/usr/lib64/go/1.17/src/runtime/panic.go:1198 +0x71 fp=0xc007927648 sp=0xc007927618 pc=0x437131
runtime.mapaccess2_faststr(0x3780da0, 0xc006347701, {0x3fa056e, 0x4})
	/usr/lib64/go/1.17/src/runtime/map_faststr.go:116 +0x3d4 fp=0xc0079276b0 sp=0xc007927648 pc=0x412eb4
k8s.io/apimachinery/pkg/apis/meta/v1/unstructured.NestedFieldNoCopy(0xc006347760, {0xc007927820, 0x1, 0x1})
	/go/src/github.com/rancher/rancher/go/pkg/mod/k8s.io/apimachinery@v0.23.3/pkg/apis/meta/v1/unstructured/helpers.go:61 +0xdf fp=0xc007927738 sp=0xc0079276b0 pc=0xccf67f
k8s.io/apimachinery/pkg/apis/meta/v1/unstructured.NestedString(0x0, {0xc007927820, 0x1, 0x1})
	/go/src/github.com/rancher/rancher/go/pkg/mod/k8s.io/apimachinery@v0.23.3/pkg/apis/meta/v1/unstructured/helpers.go:75 +0x35 fp=0xc0079277b0 sp=0xc007927738 pc=0xccf835
k8s.io/apimachinery/pkg/apis/meta/v1/unstructured.getNestedString(0xc00a9a4960, {0xc007927820, 0xc004fe7250, 0x3})
	/go/src/github.com/rancher/rancher/go/pkg/mod/k8s.io/apimachinery@v0.23.3/pkg/apis/meta/v1/unstructured/helpers.go:278 +0x1e fp=0xc0079277e0 sp=0xc0079277b0 pc=0xcd0fbe
k8s.io/apimachinery/pkg/apis/meta/v1/unstructured.(*Unstructured).GetKind(...)
	/go/src/github.com/rancher/rancher/go/pkg/mod/k8s.io/apimachinery@v0.23.3/pkg/apis/meta/v1/unstructured/unstructured.go:226
k8s.io/apimachinery/pkg/apis/meta/v1/unstructured.(*Unstructured).GroupVersionKind(0xc00b922228)
	/go/src/github.com/rancher/rancher/go/pkg/mod/k8s.io/apimachinery@v0.23.3/pkg/apis/meta/v1/unstructured/unstructured.go:430 +0x118 fp=0xc0079278a0 sp=0xc0079277e0 pc=0xcd5a38
github.com/rancher/rancher/pkg/controllers/management/authprovisioningv2.getObjectClusterNames({0x4784d10, 0xc00b922228})
	/go/src/github.com/rancher/rancher/pkg/controllers/management/authprovisioningv2/indexer.go:33 +0x1ce fp=0xc007927a10 sp=0xc0079278a0 pc=0x24a156e
github.com/rancher/rancher/pkg/controllers/management/authprovisioningv2.(*handler).OnClusterObjectChanged(0xc0048c7600, {0x4784d10, 0xc00b922228})
	/go/src/github.com/rancher/rancher/pkg/controllers/management/authprovisioningv2/role.go:106 +0x4e fp=0xc007927ab0 sp=0xc007927a10 pc=0x24a458e
github.com/rancher/rancher/pkg/controllers/management/authprovisioningv2.(*handler).OnClusterObjectChanged-fm({0x4784d10, 0xc00b922228})
	/go/src/github.com/rancher/rancher/pkg/controllers/management/authprovisioningv2/role.go:105 +0x39 fp=0xc007927ad8 sp=0xc007927ab0 pc=0x24a6659
github.com/rancher/lasso/pkg/dynamic.wrap.func1({0xe060e3d, 0xbed0fbcb0b}, {0x4784d10, 0xc00b922228})
	/go/src/github.com/rancher/rancher/go/pkg/mod/github.com/rancher/lasso@v0.0.0-20220303220250-a429cb5cb9c9/pkg/dynamic/controller.go:400 +0x116 fp=0xc007927b88 sp=0xc007927ad8 pc=0x1b944f6
github.com/rancher/lasso/pkg/controller.SharedControllerHandlerFunc.OnChange(0x3f5fac0, {0xc00d274550, 0x3fb6c52}, {0x4784d10, 0xc00b922228})
	/go/src/github.com/rancher/rancher/go/pkg/mod/github.com/rancher/lasso@v0.0.0-20220303220250-a429cb5cb9c9/pkg/controller/sharedcontroller.go:29 +0x38 fp=0xc007927bb8 sp=0xc007927b88 pc=0x1287b78
github.com/rancher/lasso/pkg/controller.(*SharedHandler).OnChange(0xc000294378, {0xc00d274550, 0x4a}, {0x4784d10, 0xc00b922228})
	/go/src/github.com/rancher/rancher/go/pkg/mod/github.com/rancher/lasso@v0.0.0-20220303220250-a429cb5cb9c9/pkg/controller/sharedhandler.go:75 +0x23f fp=0xc007927ce0 sp=0xc007927bb8 pc=0x128ae1f
github.com/rancher/lasso/pkg/controller.(*controller).syncHandler(0xc00ab3c4d0, {0xc00d274550, 0x4a})
	/go/src/github.com/rancher/rancher/go/pkg/mod/github.com/rancher/lasso@v0.0.0-20220303220250-a429cb5cb9c9/pkg/controller/controller.go:220 +0x93 fp=0xc007927d30 sp=0xc007927ce0 pc=0x1286f13
github.com/rancher/lasso/pkg/controller.(*controller).processSingleItem(0xc00ab3c4d0, {0x3596940, 0xc009afb140})
	/go/src/github.com/rancher/rancher/go/pkg/mod/github.com/rancher/lasso@v0.0.0-20220303220250-a429cb5cb9c9/pkg/controller/controller.go:201 +0x10e fp=0xc007927e08 sp=0xc007927d30 pc=0x1286bce
github.com/rancher/lasso/pkg/controller.(*controller).processNextWorkItem(0xc00ab3c4d0)
	/go/src/github.com/rancher/rancher/go/pkg/mod/github.com/rancher/lasso@v0.0.0-20220303220250-a429cb5cb9c9/pkg/controller/controller.go:178 +0x46 fp=0xc007927e50 sp=0xc007927e08 pc=0x12869c6
github.com/rancher/lasso/pkg/controller.(*controller).runWorker(...)
	/go/src/github.com/rancher/rancher/go/pkg/mod/github.com/rancher/lasso@v0.0.0-20220303220250-a429cb5cb9c9/pkg/controller/controller.go:167
github.com/rancher/lasso/pkg/controller.(*controller).runWorker-fm()
	/go/src/github.com/rancher/rancher/go/pkg/mod/github.com/rancher/lasso@v0.0.0-20220303220250-a429cb5cb9c9/pkg/controller/controller.go:166 +0x32 fp=0xc007927e70 sp=0xc007927e50 pc=0x128bc12
k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0x7f1bfa8c9190)
	/go/src/github.com/rancher/rancher/go/pkg/mod/k8s.io/apimachinery@v0.23.3/pkg/util/wait/wait.go:155 +0x67 fp=0xc007927eb0 sp=0xc007927e70 pc=0xc89287
k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0xc0078556d8, {0x4751c40, 0xc00ae6db90}, 0x1, 0xc0013cc8a0)
	/go/src/github.com/rancher/rancher/go/pkg/mod/k8s.io/apimachinery@v0.23.3/pkg/util/wait/wait.go:156 +0xb6 fp=0xc007927f30 sp=0xc007927eb0 pc=0xc890f6
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0x100000000, 0x3b9aca00, 0x0, 0xc, 0x440b85)
	/go/src/github.com/rancher/rancher/go/pkg/mod/k8s.io/apimachinery@v0.23.3/pkg/util/wait/wait.go:133 +0x89 fp=0xc007927f80 sp=0xc007927f30 pc=0xc88fe9
k8s.io/apimachinery/pkg/util/wait.Until(0x0, 0x0, 0x0)
	/go/src/github.com/rancher/rancher/go/pkg/mod/k8s.io/apimachinery@v0.23.3/pkg/util/wait/wait.go:90 +0x25 fp=0xc007927fb8 sp=0xc007927f80 pc=0xc88f25
github.com/rancher/lasso/pkg/controller.(*controller).run·dwrap·2()
	/go/src/github.com/rancher/rancher/go/pkg/mod/github.com/rancher/lasso@v0.0.0-20220303220250-a429cb5cb9c9/pkg/controller/controller.go:135 +0x2e fp=0xc007927fe0 sp=0xc007927fb8 pc=0x128648e
runtime.goexit()
	/usr/lib64/go/1.17/src/runtime/asm_amd64.s:1581 +0x1 fp=0xc007927fe8 sp=0xc007927fe0 pc=0x46b221
created by github.com/rancher/lasso/pkg/controller.(*controller).run
	/go/src/github.com/rancher/rancher/go/pkg/mod/github.com/rancher/lasso@v0.0.0-20220303220250-a429cb5cb9c9/pkg/controller/controller.go:135 +0x2c6
```

Full Rancher logs attached for posterity. 
[panic.log](https://github.com/rancher/rancher/files/8227305/panic.log)

**Comment by annablender** [comment] 2022-05-06 20:17
I have reproduced the issue on `rancher 2.6-head.`

Repro steps
* Create a feature branch off `release/v2.6`
* Add a minor comment and create a draft PR to run the provisioning tests, rerun as needed (bug showed up on retry 3)
* Decode the logs from base 64 dump

```
for CHUNK in $(grep -A1 LOG-DUMP-START Downloads/logs_rancher_rancher_22127_1_2.log | grep -v LOG-DUMP); do echo -e "\n---\nSTART LOG DUMP\n---\n"; echo -n "${CHUNK}" | base64 -d | zcat; done | less -S >> logs_rancher_rancher_22207_2_2_DECODED.log
```

```
goroutine 31626 [running]:
runtime.throw({0x4057ac5, 0x110})
	/usr/lib64/go/1.17/src/runtime/panic.go:1198 +0x71 fp=0xc004bc9648 sp=0xc004bc9618 pc=0x4371f1
runtime.mapaccess2_faststr(0x8fe532, 0xc004bc9748, {0x3fd9225, 0xa})
	/usr/lib64/go/1.17/src/runtime/map_faststr.go:116 +0x3d4 fp=0xc004bc96b0 sp=0xc004bc9648 pc=0x412ed4
k8s.io/apimachinery/pkg/apis/meta/v1/unstructured.NestedFieldNoCopy(0x46b4c7, {0xc004bc9820, 0x1, 0x1})
	/go/pkg/mod/k8s.io/apimachinery@v0.23.3/pkg/apis/meta/v1/unstructured/helpers.go:61 +0xdf fp=0xc004bc9738 sp=0xc004bc96b0 pc=0xcd01bf
k8s.io/apimachinery/pkg/apis/meta/v1/unstructured.NestedString(0xed9fe004b, {0xc004bc9820, 0x1, 0x1})
	/go/pkg/mod/k8s.io/apimachinery@v0.23.3/pkg/apis/meta/v1/unstructured/helpers.go:75 +0x35 fp=0xc004bc97b0 sp=0xc004bc9738 pc=0xcd0375
k8s.io/apimachinery/pkg/apis/meta/v1/unstructured.getNestedString(0x4021501, {0xc004bc9820, 0x0, 0xc004bc9838})
	/go/pkg/mod/k8s.io/apimachinery@v0.23.3/pkg/apis/meta/v1/unstructured/helpers.go:278 +0x1e fp=0xc004bc97e0 sp=0xc004bc97b0 pc=0xcd1afe
k8s.io/apimachinery/pkg/apis/meta/v1/unstructured.(*Unstructured).GetAPIVersion(...)
	/go/pkg/mod/k8s.io/apimachinery@v0.23.3/pkg/apis/meta/v1/unstructured/unstructured.go:218
k8s.io/apimachinery/pkg/apis/meta/v1/unstructured.(*Unstructured).GroupVersionKind(0xc005047230)
	/go/pkg/mod/k8s.io/apimachinery@v0.23.3/pkg/apis/meta/v1/unstructured/unstructured.go:426 +0x7c fp=0xc004bc98a0 sp=0xc004bc97e0 pc=0xcd64dc
github.com/rancher/rancher/pkg/controllers/management/authprovisioningv2.getObjectClusterNames({0x47b8f28, 0xc005047230})
	/go/src/github.com/rancher/rancher/pkg/controllers/management/authprovisioningv2/indexer.go:33 +0x1ce fp=0xc004bc9a10 sp=0xc004bc98a0 pc=0x24a578e
github.com/rancher/rancher/pkg/controllers/management/authprovisioningv2.(*handler).OnClusterObjectChanged(0xc00379f760, {0x47b8f28, 0xc005047230})
	/go/src/github.com/rancher/rancher/pkg/controllers/management/authprovisioningv2/role.go:109 +0x4e fp=0xc004bc9ab0 sp=0xc004bc9a10 pc=0x24a88ce
github.com/rancher/rancher/pkg/controllers/management/authprovisioningv2.(*handler).OnClusterObjectChanged-fm({0x47b8f28, 0xc005047230})
	/go/src/github.com/rancher/rancher/pkg/controllers/management/authprovisioningv2/role.go:108 +0x39 fp=0xc004bc9ad8 sp=0xc004bc9ab0 pc=0x24aaeb9
github.com/rancher/lasso/pkg/dynamic.wrap.func1({0x28fae79a, 0x10a4fd39618}, {0x47b8f28, 0xc005047230})
	/go/pkg/mod/github.com/rancher/lasso@v0.0.0-20220412224715-5f3517291ad4/pkg/dynamic/controller.go:400 +0x116 fp=0xc004bc9b88 sp=0xc004bc9ad8 pc=0x1b95f96
github.com/rancher/lasso/pkg/controller.SharedControllerHandlerFunc.OnChange(0x3f86080, {0xc002cc9e00, 0x3fddaec}, {0x47b8f28, 0xc005047230})
	/go/pkg/mod/github.com/rancher/lasso@v0.0.0-20220412224715-5f3517291ad4/pkg/controller/sharedcontroller.go:29 +0x38 fp=0xc004bc9bb8 sp=0xc004bc9b88 pc=0x1288718
github.com/rancher/lasso/pkg/controller.(*SharedHandler).OnChange(0xc000292378, {0xc002cc9e00, 0x4a}, {0x47b8f28, 0xc005047230})
	/go/pkg/mod/github.com/rancher/lasso@v0.0.0-20220412224715-5f3517291ad4/pkg/controller/sharedhandler.go:75 +0x23f fp=0xc004bc9ce0 sp=0xc004bc9bb8 pc=0x128b9bf
github.com/rancher/lasso/pkg/controller.(*controller).syncHandler(0xc000e3c630, {0xc002cc9e00, 0x4a})
	/go/pkg/mod/github.com/rancher/lasso@v0.0.0-20220412224715-5f3517291ad4/pkg/controller/controller.go:220 +0x93 fp=0xc004bc9d30 sp=0xc004bc9ce0 pc=0x1287ab3
github.com/rancher/lasso/pkg/controller.(*controller).processSingleItem(0xc000e3c630, {0x35bb8c0, 0xc0016c7c40})
	/go/pkg/mod/github.com/rancher/lasso@v0.0.0-20220412224715-5f3517291ad4/pkg/controller/controller.go:201 +0x10e fp=0xc004bc9e08 sp=0xc004bc9d30 pc=0x128776e
github.com/rancher/lasso/pkg/controller.(*controller).processNextWorkItem(0xc000e3c630)
	/go/pkg/mod/github.com/rancher/lasso@v0.0.0-20220412224715-5f3517291ad4/pkg/controller/controller.go:178 +0x46 fp=0xc004bc9e50 sp=0xc004bc9e08 pc=0x1287566
github.com/rancher/lasso/pkg/controller.(*controller).runWorker(...)
	/go/pkg/mod/github.com/rancher/lasso@v0.0.0-20220412224715-5f3517291ad4/pkg/controller/controller.go:167
github.com/rancher/lasso/pkg/controller.(*controller).runWorker-fm()
	/go/pkg/mod/github.com/rancher/lasso@v0.0.0-20220412224715-5f3517291ad4/pkg/controller/controller.go:166 +0x32 fp=0xc004bc9e70 sp=0xc004bc9e50 pc=0x128c7b2
k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0x7fa1786e1978)
	/go/pkg/mod/k8s.io/apimachinery@v0.23.3/pkg/util/wait/wait.go:155 +0x67 fp=0xc004bc9eb0 sp=0xc004bc9e70 pc=0xc89dc7
k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0x3533240, {0x4785f00, 0xc008d62bd0}, 0x1, 0xc002114960)
	/go/pkg/mod/k8s.io/apimachinery@v0.23.3/pkg/util/wait/wait.go:156 +0xb6 fp=0xc004bc9f30 sp=0xc004bc9eb0 pc=0xc89c36
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0x0, 0x3b9aca00, 0x0, 0x1, 0x440c45)
	/go/pkg/mod/k8s.io/apimachinery@v0.23.3/pkg/util/wait/wait.go:133 +0x89 fp=0xc004bc9f80 sp=0xc004bc9f30 pc=0xc89b29
k8s.io/apimachinery/pkg/util/wait.Until(0x0, 0xc0086b3ec0, 0x0)
	/go/pkg/mod/k8s.io/apimachinery@v0.23.3/pkg/util/wait/wait.go:90 +0x25 fp=0xc004bc9fb8 sp=0xc004bc9f80 pc=0xc89a65
github.com/rancher/lasso/pkg/controller.(*controller).run·dwrap·2()
	/go/pkg/mod/github.com/rancher/lasso@v0.0.0-20220412224715-5f3517291ad4/pkg/controller/controller.go:135 +0x2e fp=0xc004bc9fe0 sp=0xc004bc9fb8 pc=0x128702e
runtime.goexit()
	/usr/lib64/go/1.17/src/runtime/asm_amd64.s:1581 +0x1 fp=0xc004bc9fe8 sp=0xc004bc9fe0 pc=0x46b381
created by github.com/rancher/lasso/pkg/controller.(*controller).run
	/go/pkg/mod/github.com/rancher/lasso@v0.0.0-20220412224715-5f3517291ad4/pkg/controller/controller.go:135 +0x2c6
```

**Comment by thedadams** [comment] 2022-05-13 21:16
We believe we have fixed this issue. However, because it is intermittent and found via CI tests, I am not confident of how we can test to ensure this is fixed. This issue may just need to sit in "To Test" and be reopened if it is seen again.

**Comment by slickwarren** [comment] 2022-06-13 16:41
based on the above comment and no further reports of this issue, closing this ticket.

**Closed by slickwarren** 2022-06-13 16:41 UTC
Labels: kind/flaky-test, [zube]: To Test, status/dev-validate, area/provisioning-v2, team/area2
