### ISSUE TITLE
Azure AD auth uses too broad permissions

### ISSUE THREAD

**Issue by yvespp** [rancher/rancher#38770] opened 2022-08-30 09:07 UTC
**Is your feature request related to a problem? Please describe.**
Currently the Azure AD connection requires `Group.Read.All` and `User.Read.All` on the Microsoft Graph and Rancher checks for the roles to be present: https://github.com/rancher/rancher/blob/e6d7a18da1b7481395313de80dc78f5960597de5/pkg/auth/providers/azure/clients/ms_graph_client.go#L164

The problem is that `Group.Read.All` can not only read AD groups but also read conversations of groups:
https://docs.microsoft.com/en-us/graph/permissions-reference#application-permissions-30
_Allows the app to read group properties and memberships, and read conversations for all groups, without a signed-in user._

**Describe the solution you'd like**
Instead of `Group.Read.All` and `User.Read.All` only `Directory.Read.All` should be required:
https://docs.microsoft.com/en-us/graph/permissions-reference#application-permissions-23
_Allows the app to read data in your organization's directory, such as users, groups and apps, without a signed-in user._

**Describe alternatives you've considered**
Rancher could not check the roles (or also check for `Directory.Read.All`) and just try to access the api. This way `Directory.Read.All` might already work.

**Comment by janeczku** [comment] 2022-09-07 14:38
SURE-4068

**Comment by maxsokolovsky** [comment] 2022-10-19 14:53
This just needs a backport PR from release/v2.7.

**Comment by maxsokolovsky** [comment] 2022-11-07 16:57
For v2.7, this is taken care of (done) by https://github.com/rancherlabs/rancher-security/issues/1076
For v2.6, this is taken care of by https://github.com/rancherlabs/rancher-security/issues/1077.

**Comment by maxsokolovsky** [comment] 2022-11-21 17:12
Here is the backport PR: https://github.com/rancherlabs/rancher-security/pull/1098.
This issue is really a duplicate of https://github.com/rancherlabs/rancher-security/issues/1076, but we could keep for tracking?

**Comment by samjustus** [comment] 2022-12-07 20:19
leaving as the backport issue

**Comment by brudnak** [comment] 2023-01-05 22:27
# ✅ PASSED

## Reproduction Environment

#### Not required.

<hr>

## Validation Environment


| Component                        | Version / Type                                                                     |
| -------------------------------- | ---------------------------------------------------------------------------------- |
| Rancher version                  | v2.6-ac694c9cd0b0e2e89e894e0b92050e76cdc1fe33-head                                 |
| Rancher commit link              | https://github.com/rancher/rancher/commit/ac694c9cd0b0e2e89e894e0b92050e76cdc1fe33 |
| Installation option              | Helm (high availability)                                                           |
| If Helm Chart k8s cluster        | v1.24.7+k3s1                                                                       |
| Cert Details                     | Let's Encrypt / `traefik`                                                          |
| k3s ha external db               | Aurora MySQL 5.7.mysql_aurora.2.10.2                                               |
| Helm version                     | v2.16.8-rancher2                                                                   |
| Downstream cluster type          | Linode RKE1                                                                        |
| Downstream K8s version           | v1.24.8                                                                            |
| Authentication providers enabled | Azure AD                                                                           |
| Logged in user role              | Administrator, Standard User                                                       |
| Browser type                     | Google Chrome                                                                      |
| Browser version                  | 108.0.5359.124 (Official Build) (x86_64)                                           |

<details>
    <summary>🚨 Additional Reproduction Setup Details: Click to Expand</summary>

>K3s install command for node one. Replace values in <>

```shell
curl -sfL https://get.k3s.io | INSTALL_K3S_VERSION=<K3S_VERSION> sh -s - server --token=SECRET --datastore-endpoint=<DB_ENDPOINT> --tls-san <TLD> --node-external-ip <IP>
```

>K3s install command for node two. Replace values in <>. Main difference here is the --token

```shell
curl -sfL https://get.k3s.io | INSTALL_K3S_VERSION=<K3S_VERSION> sh -s - server --token=<TOKEN_FROM_NODE_ONE> --datastore-endpoint=<DB_ENDPOINT> --tls-san <TLD> --node-external-ip <IP>
```


</details>

## Validation steps

>Scenario: Starting with Rancher 2.6-head enable Azure AD auth with Directory.Read.All 

1. Setup Rancher server
2. Configure Azure AD to only use 1 Microsoft Graph permission `Directory.Read.All`
   - Ensure that it is an `Application` permission. **NOT** a delegated permission
   - Grant admin permission in the Azure portal UI
3. Back to Rancher UI logged in as administrator
   1. Navigate to auth providers
   2. Enable Azure AD by providing the following values:
      1. `Tenant ID`
      2. `Application ID`
      3. `Application Secret`


## Additional Info

## RESULTS

#### ✅ Expected

No errors when enabling AzureAD with only 1 Microsoft Graph permission `Directory.Read.All`. Able to successfully login and out as different user types. Administrator, Standard User.

#### ✅ Actual

No errors when enabling AzureAD with only 1 Microsoft Graph permission `Directory.Read.All`. Able to successfully login and out as different user types. Administrator, Standard User.

## 📋 QA Test Plan

<table>
    <tbody>
        <tr>
            <th>Scenario</th>
            <th>Steps</th>
            <th>Expected</th>
            <th>Actual & Pass/Fail</th>
        </tr>
         <tr>
         <td>Start 2.6-head with Azure AD enabled with <code>Directory.Read.All</code>. Upgrade to 2.7-head</td>
            <td>
                <ol>
                    <li>Start with <code>v2.6-ac694c9cd0b0e2e89e894e0b92050e76cdc1fe33-head</code></li>
                    <li>Azure AD enabled with <code>Directory.Read.All</code></li>
                    <li>Upgrade to <code>v2.7-8062f1e3ab7bff870dfab195ff699a308644168a-head</code></li>
                </ol>
            </td>
            <td>Expected: No errors from AzureAD and to still able to login and out with various users (admin, standard)</td>
            <td>Actual: No errors from AzureAD and to still able to login and out with various users (admin, standard)<br><br>Pass/Fail: ✅<code>PASS</code></td>
        </tr>
            <td>Start 2.6.9 with Azure AD enabled with <code>Group.Read.All</code> and <code>User.Read.All</code>. Upgrade to 2.6-head change Azure AD to<code>Directory.Read.All</code></td>
            <td>
                <ol>
                    <li>Start with <code>v2.6.9</code></li>
                    <li><code>Group.Read.All</code> and <code>User.Read.All</code></li>
                    <li>Start with <code>v2.6-ac694c9cd0b0e2e89e894e0b92050e76cdc1fe33-head</code></li>
                    <li>Change AzureAD to <code>Directory.Read.All</code></li>
                    <li>Disable AzureAD in Rancher UI</li>
                    <li>Enable AzureAD in RAncher UI</li>
                </ol>
            </td>
            <td>Expected: No errors from AzureAD and to still able to login and out with various users (admin, standard)</td>
            <td>Actual: No errors from AzureAD and to still able to login and out with various users (admin, standard)<br><br>Pass/Fail: ✅<code>PASS</code></td>
        </tr>
    </tbody>
</table>

**Closed by brudnak** 2023-01-05 22:27 UTC
Labels: kind/enhancement, internal, [zube]: QA Working, QA/S, team/area1

**Comment by maxsokolovsky** [comment] 2023-03-07 16:14
# Release note

Rancher no longer validates an app registration's permissions to use Microsoft Graph on endpoint updates or initial setup. Rancher recommends admins to add `Directory.Read.All` permissions of type Application. If you configure a different set of permissions, Rancher may not be able to perform some of the actions within Azure AD, if the permissions are insufficient, so you may encounter errors.
