### ISSUE TITLE
Cant view Node Scheduling when config it but can view it in Edit page

### ISSUE THREAD

**Issue by vvkkhjt** [rancher/rancher#20589] opened 2019-05-31 11:28 UTC
**What kind of request is this (question/bug/enhancement/feature request):**
bug

**Steps to reproduce (least amount of steps as possible):**
configure node scheduling 

**Result:**
view the deployment page,cant view it,but can view it in edit page

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI):v2.2.2
- Installation option (single install/HA): HA

![微信图片_20190531192722](https://user-images.githubusercontent.com/12765476/58703115-3235b300-83da-11e9-8f90-7a62e04d99a3.png)
![微信图片_20190531192716](https://user-images.githubusercontent.com/12765476/58703111-2ea22c00-83da-11e9-94b0-052de85f4d8d.png)
![未命名1559302057](https://user-images.githubusercontent.com/12765476/58703120-33ff7680-83da-11e9-94aa-e3e5f8f75d06.png)

@loganhz

**Comment by davidnuzik** [comment] 2019-06-10 17:11
@logan just wanted to confirm this is the correct PR for this issue?
One of those commits resolved this?

**Comment by loganhz** [comment] 2019-06-10 17:12
@davidnuzik yes

**Comment by davidnuzik** [comment] 2019-06-12 23:02
**Version: HA v2.2.2
Replication:**

Create a workload, set node scheduling to "Run all pods for this workload on a specific node" and pick one.
![image](https://user-images.githubusercontent.com/45179589/59392031-0b0ca900-8d2b-11e9-90e5-78fb55f3a582.png)
Save.

Now, click on the workload name to view it's details page.
You see it shows wrongly. It shows we chose the other option for all nodes:
![image](https://user-images.githubusercontent.com/45179589/59392049-211a6980-8d2b-11e9-8f0b-ea2a7018051e.png)

**Validation:
Version: Master (v2.3) (6/12/19)**

This is now fixed. When you follow those steps and view the details page for the workload now it shows correctly:
![image](https://user-images.githubusercontent.com/45179589/59392106-54f58f00-8d2b-11e9-813d-970acd5b2a7f.png)
(node name is different because is different environment)

UI regression test plan will also be updated to add this check.

**Closed by davidnuzik** 2019-06-12 23:02 UTC
Labels: [zube]: To Test, area/ui, kind/bug, team/ui
