### ISSUE TITLE
vsphere pvc - unable to mount volume

### ISSUE THREAD

**Issue by slickwarren** [rancher/rancher#37035] opened 2022-03-24 23:23 UTC
**Rancher Server Setup**
- Rancher version: v2.6.3
- Installation option (Docker install/Helm Chart): docker

**Information about the Cluster**
- Kubernetes version: v1.19.16-rancher1-3
- Cluster Type (Local/Downstream): downstream
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider): vsphere cloud driver

k8s v1.19.16-rancher1-3
cpi: 100.1.0+up1.0.100
csi:  100.1.0+up2.3.0
tried with both vsphere 6.7 and 7.0

**User Information**
- What is the role of the user logged in? (Admin/Cluster Owner/Cluster Member/Project Owner/Project Member/Custom): standard user

   
**Describe the bug**
csi/cpi charts deploy successfully however when trying to mount a volume to a workload the mount fails.. 

**To Reproduce**
* deploy cpi/csi charts in your vsphere cluster
* go to deploy a workload 
  * create a PVC when creating the workload

**Result**
workload fails to deploy, due to the volume not mounting. 
error from cluster running in 7.0: 
```
fault: "(*types.LocalizedMethodFault)(0xc000117080)({\n DynamicData: (types.DynamicData) {\n },\n Fault: (types.CnsFault) {\n  BaseMethodFault: (types.BaseMethodFault) <nil>,\n  Reason: (string) (len=16) \"VSLM task failed\"\n },\n LocalizedMessage: (string) (len=32) \"CnsFault error: VSLM task failed\"\n})\n". opId: "42af1888"
```

error from cluster running on 6.7:  
```
4 pod has unbound immediate PersistentVolumeClaims.
```

**Expected Result**
volumes should mount and the workload should get to an active state. 

* this might be due to something wrong with the environment. Further investigation is required.

**Comment by phillipsj** [comment] 2022-03-24 23:26
@slickwarren can you try the work around listed here about the nouuid? https://github.com/kubernetes-sigs/vsphere-csi-driver/issues/1189

**Comment by rosskirkpat** [comment] 2022-03-25 02:12
The root cause of this issue is a mis-configuration of the vsphere node template.

The VM hardware version of the template was vmx-10. vSphere 7.0.x requires vmx-13 or higher.
![Screen Shot 2022-03-24 at 8 57 45 PM](https://user-images.githubusercontent.com/55704795/160037574-32c1dcfd-6f93-4bfb-af73-d3b32af2df31.png)

![Screen Shot 2022-03-24 at 8 59 35 PM](https://user-images.githubusercontent.com/55704795/160038091-446ff1e5-192f-4658-b697-454a858c38b3.png)

After upgrading the VM compatibility version to support vSphere 7, we saw logs indicating that vSphere was able to successfully complete the task of attaching a virtual disk and container volume.

![Screen Shot 2022-03-24 at 9 01 01 PM](https://user-images.githubusercontent.com/55704795/160038104-3764ae91-a477-4e89-bd27-adc22d76b45d.png)

![Screen Shot 2022-03-24 at 9 04 33 PM](https://user-images.githubusercontent.com/55704795/160038511-8c89878f-24a6-45f8-a3e3-76f9ca1d7596.png)

After upgrading the VM version, Rancher also reported that the volume was able to successfully mounted.

![Screen Shot 2022-03-24 at 9 05 06 PM](https://user-images.githubusercontent.com/55704795/160039077-1c957090-ecd3-47ce-a31e-f7ff99b4d338.png)

However, the default PV filesystem type is ext4 which did not work with the `ranchertest/mytestcontainer:unprivileged` container image. This resulted in the volume being mounted but failing to finish provisioning.

With the filesystem type was set to xfs for a new PV being created, vSphere showed a 1gb disk on the node.

![Screen Shot 2022-03-24 at 9 12 17 PM](https://user-images.githubusercontent.com/55704795/160039464-73398fb3-60eb-48aa-92bb-56c6e1f23a6e.png)

There was still a configuration issue in the cluster as the XFS PV failed to attach due to the cloud provider not being initialized correctly. This could have been due to debugging steps or improper configuration. A fresh cluster setup using a VM template with at least a vmx-13 hardware version should result in a successful validation as we have seen rke1 e2e validation pass before.

![Screen Shot 2022-03-24 at 9 31 51 PM](https://user-images.githubusercontent.com/55704795/160039466-fef88fdf-3307-466b-ad32-a0d1612f1313.png)

Closing this issue as it was due to an environment configuration problem and not the CPI or CSI charts.

**Closed by rosskirkpat** 2022-03-25 02:12 UTC
Labels: area/vsphere, kind/bug-qa
