### ISSUE TITLE
[Monitoring v2] - Error: failed to create resource: ServiceMonitor.monitoring.coreos.com on Cluster with RHEL 8.5 nodes

### ISSUE THREAD

**Issue by izaac** [rancher/rancher#36742] opened 2022-03-03 20:49 UTC
**Rancher Server Setup**
- Rancher version:  `v2.6.4-rc4`
- Installation option: Helm HA RKE1
- Proxy/Cert Details: Valid certs

**Information about the Cluster**
- Kubernetes version: `v1.22.6`
- Cluster Type: Downstream
   - If downstream, what type of cluster? Custom AWS Docker 20.10 SELinux RHEL 8.5 nodes:

**User Information**
- Admin 

   
**Describe the bug**

Monitoring installation fails on the cluster with RHEL 8.5 SELinux enabled Docker 20.10 and rancher-selinux RPM fails

**To Reproduce**

- Apps & Marketplace -> Enable Monitoring I only selected the `System` project, everything else defaults and `selinux.enabled: true`

**Result**

`Error: failed to create resource: ServiceMonitor.monitoring.coreos.com "rancher-monitoring-ingress-nginx" is invalid: spec.endpoints.interval: Invalid value: "integer": spec.endpoints.interval in body must be of type string: "integer" `

**Expected Result**
Be able to install the Monitoring chart/app without errors.

**Additional context**
This isn't reproducible in a Custom cluster `v1.22.6` with Ubuntu 20.04.1 LTS nodes.

**Comment by aiyengar2** [comment] 2022-03-03 22:47
Might be a duplicate of the testing effort for https://github.com/rancher/rancher/issues/36105? SELinux + RPM Enabled (which is required for RHEL 8.5 iirc, since `getenforce` returns `Enforcing` by default)?

**Comment by izaac** [comment] 2022-03-03 23:22
This is now working on chart version `100.1.1+up19.0.3` which includes this fix https://github.com/rancher/charts/pull/1784

**Closed** 2022-03-18 17:21 UTC
Labels: kind/bug, [zube]: To Test, status/release-blocker, feature/charts-monitoring-v2
