### ISSUE TITLE
When editing a Service or Load Balancer, Links/Targets are not shown

### ISSUE THREAD

**Issue by sshipway** [rancher/rancher#2632] opened 2015-11-11 03:44 UTC
rancher-server v0.44

This does not always happen, for some reason.  Created a Service linking to another Service, or a Load Balancer linking to a Service.  The final Stack works correctly, and the API shows that the links exist, but the linked service is not displayed on the Stacks page, nor is it displayed when the Service is edited.  Adding more links still does not diplay any, though the changes are saved and display in the API.

**Comment by deniseschannon** [comment] 2015-11-11 04:37
This is a duplicate of https://github.com/rancher/rancher/issues/1389. 

It's due to multiple environments in Rancher.

**Closed by deniseschannon** 2015-11-11 04:37 UTC
