### ISSUE TITLE
Stack name is unique or not?

### ISSUE THREAD

**Issue by niusmallnan** [rancher/rancher#8536] opened 2017-04-18 08:43 UTC
**Rancher Versions:**
Server: v1.5.5

Create a stack named "aaa"
![image](https://cloud.githubusercontent.com/assets/998984/25121870/adbc3daa-2455-11e7-8964-80be9a56cd8c.png)

Create a stack named "aaa" again, an error occur.
![image](https://cloud.githubusercontent.com/assets/998984/25121933/cf832d68-2455-11e7-8b09-ad91c023e691.png)

But i can create a stack name "bbb", then rename it by "aaa",you can see:
![image](https://cloud.githubusercontent.com/assets/998984/25122010/0a04ea12-2456-11e7-80c2-6e75ef36f29e.png)

Stack name is unique or not???

**Comment by superseb** [comment] 2017-11-16 23:12
Duplicate of https://github.com/rancher/rancher/issues/8210

**Closed by superseb** 2017-11-16 23:12 UTC
Labels: kind/question
