### ISSUE TITLE
Instance gets stuck in "initializing" state even though hosts are reporting it as healthy

### ISSUE THREAD

**Issue by deniseschannon** [rancher/rancher#2169] opened 2015-09-28 18:48 UTC
Currently in Rancher, instances with healthchecks are getting stuck in `initializing` state even though the hosts are reporting the instances as healthy. 

Found from debugging: http://forums.rancher.com/t/understanding-container-service-failover-on-host-failure/431/29

**Comment by alena1108** [comment] 2015-09-28 19:05
Removed the "Blocker" flag. Tested a couple of use cases locally - tcp healthcheck for ubuntu image, and http check for nginx, healtcheck get updated just fine. Going to run more debugging on the setup where its happening, and will update the bug with findings.

**Comment by alena1108** [comment] 2015-09-29 16:46
Closing the bug as the issue on the user's side was caused by misconfigured request line in http request line of the healtcheck.

**Closed by alena1108** 2015-09-29 16:46 UTC
Labels: area/service, kind/bug
