### ISSUE TITLE
[BUG] 2.7.2-rc7 airgapped cluster throws error when attempting to install opa gatekeeper

### ISSUE THREAD

**Issue by AndrewHoffmanQA** [rancher/rancher#41015] opened 2023-03-30 16:33 UTC
**Rancher Server Setup**
- Rancher version:
charts installed on local rancher
airgapped local (1 etcd, 1cp, 1 worker)
rancher - v2.7.2-rc7
k8- v1.25.6

**Describe the bug**
opa gatekeeper- 102.0.0+up3.10.0

attempting to install OPA fails, it appears that the image is not copying correctly from the registry. 

**To Reproduce**
1. stand up local airgapped cluster
2. navigate to charts > OPA gatekeeper
3. install with standard values

**Result**
image is never successfully pulled from private registry.  see error logs screenshot

**Expected Result**
successful install

**Screenshots**

![image](https://user-images.githubusercontent.com/89030218/228903470-aca4a135-7a61-40e9-a895-3fb206ba9e24.png)

**Additional context**

**Comment by nflynt** [comment] 2023-03-31 20:06
This appears to be a dashboard regression, caused by `systemDefaultRegistry` not being saved correctly in the generated manifests. As the root cause is identical to https://github.com/rancher/rancher/issues/41016 let's consolidate and use that for tracking purposes. I'm closing this as a duplicate.

**Closed by nflynt** 2023-03-31 20:06 UTC
Labels: kind/bug, kind/bug-qa, [zube]: Working, status/release-blocker, duplicate, team/area3
