### ISSUE TITLE
Unable to access Swarm endpoint created in Rancher

### ISSUE THREAD

**Issue by lukasgr90** [rancher/rancher#4575] opened 2016-04-27 15:53 UTC
Rancher Version:  1.01
Docker Version:    1.11
OS: Ubuntu 16.04 (Servers and Client)

#Steps to Reproduce: 
  
  I've multiple docker-engines. One of them is accessible over a URL for which I've a signed SSL certificate by my university (their root authority is well known).
  
  On this docker-engine I run a rancher-server with a nginx configured as SSL reverse proxy as described here: [http://docs.rancher.com/rancher/installing-rancher/installing-server/basic-ssl-config/](http://docs.rancher.com/rancher/installing-rancher/installing-server/basic-ssl-config/)
  
  Firefox and Chrome connect without complains with the web interface of the rancher-server instance over https as expected.

  Then I created a Swarm environment and added several docker-engines as host like described in the section "Adding Hosts" of the same documentation page linked above. This worked well and I can work with the Swarm over the browser based CLI without a problem.

  But everytime I want to use any docker client by generating, downloading and using the certificate ... Zip archive (as described on the Swarm->CLI page of Rancher's web UI), I get following error:

*lukas@lukas-OptiPlex-9020:~/.docker$ export DOCKER_HOST=tcp://rancher.mars.haw-hamburg.de:443 DOCKER_TLS_VERIFY=1
lukas@lukas-OptiPlex-9020:~/.docker$ docker info
An error occurred trying to connect: Get https://rancher.mars.haw-hamburg.de:443/v1.22/info: x509: certificate signed by unknown authority*

**Comment by deniseschannon** [comment] 2016-05-05 17:28
This is a duplicate of 
https://github.com/rancher/rancher/issues/4145

**Closed by deniseschannon** 2016-05-05 17:28 UTC
