### ISSUE TITLE
简体中文 命令行无法打开

### ISSUE THREAD

**Issue by waldron-xing** [rancher/rancher#9196] opened 2017-06-29 06:22 UTC
**Rancher versions:**
rancher/server:stable 1.6.2
rancher/agent:1.2.2

**Infrastructure Stack versions:**
healthcheck:
ipsec:
network-services:
scheduler:
kubernetes (if applicable):

**Docker version: (`docker version`,`docker info` preferred)**

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**

**Steps to Reproduce:**

**Results:** 简体中文选择某个容器  选择执行命令行 无法打开命令行界面

**Comment by superseb** [comment] 2017-06-29 07:13
Duplicate of https://github.com/rancher/rancher/issues/8963, let me know if you disagree.

**Closed by superseb** 2017-06-29 07:13 UTC
