### ISSUE TITLE
Updating Ipsec fails on first attempts

### ISSUE THREAD

**Issue by cloudnautique** [rancher/rancher#3975] opened 2016-03-15 16:14 UTC
Rancher Version:
v0.63.0

Docker Version:
1.10.x

OS: 
Ubuntu 14.04

Steps to Reproduce: 
Have a large number of hosts. (>100)
Create a new service with scale 20+
Watch logs. Periodically, you'll see:

```
Failed null, exit code [3] output [INFO: Updating ipsec-hosts
INFO: Downloading https://loadtest.rancher.io/v1//configcontent//ipsec-hosts current=ipsec-hosts-12-04dc8ee18155dd4e7898fbcd23391737fc0ef00a77218e819e7e2d37bde03345
INFO: Running /var/lib/cattle/download/ipsec-hosts/ipsec-hosts-16-04dc8ee18155dd4e7898fbcd23391737fc0ef00a77218e819e7e2d37bde03345/apply.sh
INFO: HOME -> ./
INFO: HOME -> ./etc/
INFO: HOME -> ./etc/cattle/
INFO: HOME -> ./etc/cattle/ipsec/
INFO: HOME -> ./etc/cattle/ipsec/config.json
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (7) Failed to connect to localhost port 8111: Connection refused
Failed to reload ipsec config
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (7) Failed to connect to localhost port 8111: Connection refused
curl: (3) [globbing] unmatched brace in column 1
[[scripts.sh:184] script_env
[[scripts.sh:109] '[' -n https://loadtest.rancher.io/v1 ']'
[[scripts.sh:110] return
[[scripts.sh:186] export CATTLE_HOME=/var/lib/cattle
[[scripts.sh:186] CATTLE_HOME=/var/lib/cattle
[[scripts.sh:187] export CATTLE_CONFIG_URL=https://loadtest.rancher.io/v1
[[scripts.sh:187] CATTLE_CONFIG_URL=https://loadtest.rancher.io/v1
[[scripts.sh:188] export CATTLE_STORAGE_URL=https://loadtest.rancher.io/v1
[[scripts.sh:188] CATTLE_STORAGE_URL=https://loadtest.rancher.io/v1
[apply.sh:5] stage_files
[scripts.sh:77] local monit=false
[scripts.sh:79] '[' -d content-home ']'
[scripts.sh:80] find content-home -name '*.sh' -exec chmod +x '{}' ';'
[scripts.sh:81] sed 's/^/INFO: HOME -> /'
[scripts.sh:81] tar xvf - --no-overwrite-dir -C /var/lib/cattle
[scripts.sh:81] tar cf - -C content-home .
INFO: HOME -> ./
INFO: HOME -> ./etc/
INFO: HOME -> ./etc/cattle/
INFO: HOME -> ./etc/cattle/ipsec/
INFO: HOME -> ./etc/cattle/ipsec/config.json
[scripts.sh:84] '[' -d content ']'
[scripts.sh:102] '[' false = true ']'
[apply.sh:7] '[' '' '!=' true ']'
[apply.sh:8] curl -f http://localhost:8111/v1/reload
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (7) Failed to connect to localhost port 8111: Connection refused
[apply.sh:9] echo Failed to reload ipsec config
Failed to reload ipsec config
[apply.sh:10] curl http://localhost:8111/v1/reload '{'
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (7) Failed to connect to localhost port 8111: Connection refused
curl: (3) [globbing] unmatched brace in column 1
]
```

**Comment by jmatsushita** [comment] 2016-03-22 09:58
I also have the same error and don't run more than a hundred nodes.

The error shows up about every 15 seconds with different ecutorService-# numbers and always the same ipsec-hosts-XX-hash. The Downloading URL hash is the same as the Running one, but the XX  is different (as with the OP who had 12 for downloading and 16 for running). Not sure it means anything but wanted to mention it.

Looking at the cattle-debug.log shows that a certain agent number is failing. But how do I match `agent:YY` with an agent managed by rancher?

**Comment by CumpsD** [comment] 2016-03-28 00:53
Did any of you find how to resolve this?

**Comment by ibuildthecloud** [comment] 2016-03-28 18:58
This should be resolved in 1.0 based on a series of work arounds.  One of the major causes of this issue was that rancher-net would not actually be running because of an issue in monit.

**Comment by ibuildthecloud** [comment] 2016-03-28 19:00
I'm going to say this is resolved now, until somebody finds another issue...

**Comment by will-chan** [comment] 2016-03-28 21:13
Closing issue.  Please re-open if reproduced.

**Closed by will-chan** 2016-03-28 21:13 UTC
Labels: kind/bug, kind/performance, status/resolved, status/to-test
