### ISSUE TITLE
Started-once service now has state = unhealthy instead of started-once

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#6586] opened 2016-11-10 22:40 UTC
**Rancher Version:** Master 11/10

**Steps to Reproduce:**
1.  Create a service with the image = hello-world and started once on

**Results:** The container's state goes to unhealthy instead of started once.  Which means the service and stack are reflecting that state.

**Expected:**  Should be in a started-once state

**Comment by alena1108** [comment] 2016-11-11 22:43
@leodotcloud seems that it has something to do with our networking. So we have a very short living container (started using image "hello-world:latest"). It never gets an ip address assigned to it, therefore it never considered as started even once by cattle.

In Rancher, we have support for NOT restarting short living containers (data containers for instance) by passing the label start-once true ("Command" tab in the UI, Restart Never (Start once)). But these containers should still have ip addresses assigned to them.

**Comment by alena1108** [comment] 2016-11-11 23:08
Looked at the logs more. Looks like instance.start command never completes due to this error reported by the agent for short lived container (and it used to work before)

```
Agent error for [compute.instance.activate.reply;agent=1]: no such file or directory
```

```
2016-11-11 22:37:54,790 DEBUG [d8cbbe0c-9be2-4943-a15b-41dd61f4c907:739] [instance:26->instanceHostMap:26] [instance.start->(InstanceStart)->instancehostmap.activate] [] [cutorService-27] [c.p.e.p.i.DefaultProcessIn
stanceImpl] Changing state [inactive->activating] on [instanceHostMap:26]
2016-11-11 22:37:54,793 DEBUG [d8cbbe0c-9be2-4943-a15b-41dd61f4c907:739] [instance:26->instanceHostMap:26] [instance.start->(InstanceStart)->instancehostmap.activate->(InstanceHostMapActivate)] [] [cutorService-27]
[c.p.e.p.i.DefaultProcessInstanceImpl] Running handler [InstanceHostMapActivate]
2016-11-11 22:37:55,713 DEBUG [589fc03f-076a-4bd4-a2bb-84b3bb3a72fe:743] [containerEvent:103->instance:26] [containerevent.create->(ContainerEventCreate)->instance.stop] [] [cutorService-23] [c.p.e.p.i.DefaultProces
sInstanceImpl] Changing state [starting->stopping] on [instance:26]
2016-11-11 22:37:55,713 DEBUG [589fc03f-076a-4bd4-a2bb-84b3bb3a72fe:743] [containerEvent:103->instance:26] [containerevent.create->(ContainerEventCreate)->instance.stop] [] [cutorService-23] [c.p.e.p.i.DefaultProces
sInstanceImpl] Exiting with code [SCHEDULED] : SCHEDULED
2016-11-11 22:37:55,763 ERROR [d8cbbe0c-9be2-4943-a15b-41dd61f4c907:739] [instance:26->instanceHostMap:26] [instance.start->(InstanceStart)->instancehostmap.activate] [] [cutorService-27] [c.p.e.p.i.DefaultProcessIn
stanceImpl] Agent error for [compute.instance.activate.reply;agent=1]: no such file or directory
2016-11-11 22:37:55,763 DEBUG [d8cbbe0c-9be2-4943-a15b-41dd61f4c907:739] [instance:26] [instance.start->(InstanceStart)] [] [cutorService-27] [c.p.e.p.i.DefaultProcessInstanceImpl] Exiting [UNKNOWN_EXCEPTION] proces
s [instancehostmap.activate:null] on resource [26]
2016-11-11 22:37:55,763 ERROR [d8cbbe0c-9be2-4943-a15b-41dd61f4c907:739] [instance:26] [instance.start->(InstanceStart)] [] [cutorService-27] [i.c.p.process.instance.InstanceStart] Failed to Starting for instance [2
6]
```

there gotta be some timing issue because it used to work before. And for "hello-world" container the start process was always completed.

adding @StrongMonkey too

**Comment by cjellick** [comment] 2016-11-15 16:20
@alena1108 @leodotcloud do you know the current (meaning 1.1.x) behavior of short-lived, start-once containers and injecting their Rancher IP? I'm thinking through it and I _think_ that if the container stopped before the injection could happen, we would just silently fail to inject the IP.

**Comment by jpdffonseca** [comment] 2016-11-16 16:53
I'm experiencing a similar issue. When launching a short living container, right before it starts the status sometimes changes to `Unhealthy` instead of `Active`. But in this case, when the container exits the status always changes properly to `Started-once`.

This happens every now and then and I couldn't figure out yet the cause. Any thoughts on this guys?

**Comment by StrongMonkey** [comment] 2016-11-17 05:25
@tfiduccia  the fix is in cattle master now. You can start testing it

**Comment by tfiduccia** [comment] 2016-11-17 21:46
Version - master 11/17
Verified fixed

**Comment by tfiduccia** [comment] 2016-11-24 00:49
Seeing this again v1.2.0-pre4-rc14

**Comment by tfiduccia** [comment] 2016-11-25 03:59
Did you run it from a catalog?

--
Tani

On Nov 24, 2016, at 4:09 PM, Denise <notifications@github.com<mailto:notifications@github.com>> wrote:


I don't see this issue in v1.2.0-pre4-rc14. I ran the same test and it looks fine to me.
[screen shot 2016-11-24 at 3 08 49 pm]<https://cloud.githubusercontent.com/assets/11410997/20611040/fda12012-b257-11e6-8eda-a2d691976c0d.png>

-

**Comment by tfiduccia** [comment] 2016-11-25 22:51
Tracked this down. The reason why this is happening is because the infrastructure stacks were not fully deployed. Which means the started-once service failed and stopped.

**Comment by deniseschannon** [comment] 2016-11-26 01:15
@ibuildthecloud is there anything that can be done in this use case? infra stacks aren't up, but causes `started-once` containers to come up unhealthy.

**Comment by ibuildthecloud** [comment] 2016-11-26 02:39
I'd say in this situation it did the correct thing.  If the infra stacks haven't deployed then the "started-once" container never really started at all.  It failed to start, so it should be an error.  Does cattle not delete the error container and try again?

**Comment by tfiduccia** [comment] 2016-11-29 01:26
Does not delete container and try again.  Container goes to stopped and service goes to unhealthy state.

**Comment by StrongMonkey** [comment] 2016-12-05 16:36
I can't reproduce that if infra stacks are fully deployed.

**Comment by deniseschannon** [comment] 2016-12-16 19:37
This seems related to https://github.com/rancher/rancher/issues/5978

**Closed** 2018-08-21 21:27 UTC
Labels: area/workload, kind/bug, status/autoclosed
