### ISSUE TITLE
Cluster monitoring in Error state after 2.5.2 upgrade

### ISSUE THREAD

**Issue by chad-barensfeld-exa** [rancher/rancher#30136] opened 2020-11-18 19:18 UTC
**What kind of request is this (question/bug/enhancement/feature request):**
bug

**Steps to reproduce (least amount of steps as possible):**
1. Import GKE cluster on Rancher 2.4.5 using Terraform provider 1.9.0

```
resource "rancher2_cluster" "customer" {
  name = var.customer
  enable_cluster_monitoring = true
  cluster_monitoring_input {
    answers = {
      "exporter-kubelets.https"                   = "true"
      "exporter-node.enabled"                     = "true"
      "exporter-node.ports.metrics.port"          = 9796
      "exporter-node.resources.limits.cpu"        = "200m"
      "exporter-node.resources.limits.memory"     = "200Mi"
      "grafana.persistence.enabled"               = "false"
      "operator-init.enabled"                     = "true"
      "operator.resources.limits.memory"          = "250Mi"
      "prometheus.persistence.enabled"            = "false"
      "prometheus.resources.core.limits.cpu"      = "500m"
      "prometheus.resources.core.limits.memory"   = "500Mi"
      "prometheus.resources.core.requests.cpu"    = "100m"
      "prometheus.resources.core.requests.memory" = "100Mi"
      "prometheus.retention"                      = "48h"
    }
    version = "0.1.1"
  }
}
```

2. Upgrade Rancher to 2.5.2 using helm stable repo

```
helm upgrade rancher rancher-stable/rancher \
  --namespace cattle-system \
  --set hostname=rancher.example.com \
  --set ingress.tls.source=secret \
  --version 2.5.2
```

3. Update Terraform provider to 1.10.6

4. Update Terraform resource to use new cluster monitoring version and apply

```
resource "rancher2_cluster" "customer" {
  name = var.customer
  enable_cluster_monitoring = true
  cluster_monitoring_input {
    answers = {
      "exporter-kubelets.https"                   = "true"
      "exporter-node.enabled"                     = "true"
      "exporter-node.ports.metrics.port"          = 9796
      "exporter-node.resources.limits.cpu"        = "200m"
      "exporter-node.resources.limits.memory"     = "200Mi"
      "grafana.persistence.enabled"               = "false"
      "operator-init.enabled"                     = "true"
      "operator.resources.limits.memory"          = "250Mi"
      "prometheus.persistence.enabled"            = "false"
      "prometheus.resources.core.limits.cpu"      = "500m"
      "prometheus.resources.core.limits.memory"   = "500Mi"
      "prometheus.resources.core.requests.cpu"    = "100m"
      "prometheus.resources.core.requests.memory" = "100Mi"
      "prometheus.retention"                      = "48h"
    }
    version = "0.1.4"
  }
}
```

5. Terraform succeeds

**Result:**
Cluster stuck in error state
```
[ERROR] error syncing 'c-qx2k5': handler cluster-monitoring-handler: failed to deploy monitoring: stale "cluster-monitoring" App in p-wknqk Project is still on terminating, requeuing
```

**Other details that may be helpful:**
Terraform v0.12.28

**Environment information**
- Rancher version: 2.5.2
- Installation option: HA

**Cluster information**
- Cluster type: Imported GKE
- Machine type and specifications: Cloud 4 CPU/15 GB
- Kubernetes version (use `kubectl version`):

```
Rancher cluster:
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.3", GitCommit:"1e11e4a2108024935ecfcb2912226cedeafd99df", GitTreeState:"clean", BuildDate:"2020-10-14T18:52:19Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.2", GitCommit:"59603c6e503c87169aea6106f57b9f242f64df89", GitTreeState:"clean", BuildDate:"2020-01-18T23:22:30Z", GoVersion:"go1.13.5", Compiler:"gc", Platform:"linux/amd64"}

GKE clusters:
v1.15.12-gke.20
```

- Docker version (use `docker version`):

```
Client: Docker Engine - Community
 Version:           19.03.5
 API version:       1.40
 Go version:        go1.12.12
 Git commit:        633a0ea
 Built:             Wed Nov 13 07:25:41 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.5
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.12
  Git commit:       633a0ea
  Built:            Wed Nov 13 07:24:18 2019
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.2.10
  GitCommit:        b34a5c8af56e510852c35414db4c1f4fa6172339
 runc:
  Version:          1.0.0-rc8+dev
  GitCommit:        3e425f80a8c931f88e6d94a8c831b9d5aa481657
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

**Comment by maggieliu** [comment] 2020-11-18 19:26
@izaac @sowmyav27 Can you see if we can reproduce this?

**Comment by chad-barensfeld-exa** [comment] 2020-11-18 21:24
FYI, just tried disabling the monitoring first, then enabling it with new version (instead of upgrading) and it works. So something weird going on with upgrading only.

**Comment by slickwarren** [comment] 2020-12-29 16:30
I was able to produce this
 error with the following: 
* rancher v2.4.5 -> 2.5.2 
* monitoring v0.1.1 -> 0.1.4
* rancher2(terraform) 1.9.0 -> 1.10.6
with errors in Workload: prometheus-operator-monitoring-operator -- 
```
 1 operator.go:994] Sync "cattle-prometheus/cluster-monitoring" failed: creating config failed: loading additional scrape configs from Secret failed: secret prometheus-cluster-monitoring-additional-scrape-configs could not be found
level=info ts=2020-12-29T16:09:26.704610075Z caller=operator.go:1094 component=prometheusoperator msg="sync prometheus" key=cattle-prometheus/cluster-monitoring
E1229 16:09:26.751327
"
```
This error was not reported in the UI, but is in the logs for this workload.  None of the monitoring metrics appear to be working, but no errors are reported and each container looks healthy.

<img width="1344" alt="Screen Shot 2020-12-29 at 8 17 30 AM" src="https://user-images.githubusercontent.com/16691014/103298046-686c5780-49ae-11eb-8d32-6da25d3d0362.png">

<img width="1313" alt="Screen Shot 2020-12-29 at 8 19 19 AM" src="https://user-images.githubusercontent.com/16691014/103298148-93ef4200-49ae-11eb-851b-b9b3e4b8ce3e.png">
I also tested the fix, disabling -> reenabling monitoring, which does in fact fix monitoring and the issue is no longer there.

**Comment by rawmind0** [comment] 2021-02-09 11:46
Issue reproduced, cluster monitoring is not updating properly at this scenario.

Submitted PR https://github.com/rancher/terraform-provider-rancher2/pull/578 to properly update Rancher cluster/project monitoring V1. This scenario has been tested successfully using this PR. The patch will be included at next tfp release.

**Comment by rawmind0** [comment] 2021-02-10 15:51
The fix is already merged and will be included in the next terraform provider release.

**Comment by slickwarren** [comment] 2021-02-23 03:57
This has been tested following the exact steps from [December](https://github.com/rancher/rancher/issues/30136#issuecomment-752147339), but instead of using terraform 10.6.0, the latest build of tfp was used using the [instructions in the readme](https://github.com/rancher/terraform-provider-rancher2), along with [these instructions for using custom binaries with tf](https://www.hashicorp.com/blog/automatic-installation-of-third-party-providers-with-terraform-0-13). This results in no error occurring before, during or after the upgrade, and the monitoring upgrade able to complete successfully. 
<img width="1316" alt="Screen Shot 2021-02-22 at 7 31 23 PM" src="https://user-images.githubusercontent.com/16691014/108800326-a669a000-7547-11eb-9324-099255f158ac.png">
After being unable to find any failures related to monitoring upgrade, I also verified that monitoring was operating normally by checking all of our normal p0 tests for monitoring v1.

**Closed by slickwarren** 2021-02-23 03:57 UTC
Labels: [zube]: QA Working
