### ISSUE TITLE
[BUG] When MCM is disabled, the webhook won't start

### ISSUE THREAD

**Issue by cbron** [rancher/rancher#39446] opened 2022-10-28 14:06 UTC
See here: https://github.com/rancher/rancher/issues/38952#issuecomment-1288413593
Specifically: 

> In rancher, it only creates RoleTemplate CRD when multi-cluster-management is enabled ([ref](https://github.com/rancher/rancher/blob/40932d62cdeb2f4594009436468c444c3378553d/pkg/api/norman/server/managementstored/setup.go#L108)). 
> However, rancher webhook uses RoleTemplate ([ref](https://github.com/rancher/webhook/blob/152e737b9f83ee70f434da2524e0ac48c8b98155/pkg/auth/roleTemplate.go#L14)), so it can't start successfully in our case.

This should not affect <2.7.0.

**Comment by KevinJoiner** [comment] 2022-10-28 16:01
## Root Cause
Webhook attempts to use roleTemplate CRD when MCM is disabled. If MultiClusterManagement is disabled then this CRD does not exist in the cluster and rancher-webhook will fail all requests received.
## What was fixed, or what change has occurred
Webhook now checks if mcm is enabled before using roleTemplates.
## Areas or cases that should be tested

### Install Rancher with MCM disabled.
1.  `docker run -d --restart=unless-stopped -e  -p 8080:80 -p 9443:443  --privileged rancher/rancher:v2.7-head --features=multi-cluster-management=false,multi-cluster-management-agent=false`
2.  Login to Rancher.
3.  Verify rancher-webhook is running `k get pod -n cattle-system rancher-webhook`
4.  Verify the rancher-webhook does not contain the following error. `the server could not find the requested resource (get roletemplates.meta.k8s.io)`
    `k logs -n cattle-system <rancher-webhook-xxxxx>`
5. Verify that the webhook allows a request by editing the description for the local cluster
    `k edit cluster.management.cattle.io local`

### Install Rancher with MCM enabled and verify CRTB endpoint work.
1.  `docker run -d --restart=unless-stopped -e  -p 8080:80 -p 9443:443  --privileged rancher/rancher:v2.7-head`
2.  Login to Rancher.
3.  Verify rancher-webhook is running `k get pod -n cattle-system rancher-webhook`
4.  Verify the rancher-webhook does not contain the following error. `the server could not find the requested resource (get roletemplates.meta.k8s.io)`
    `k logs -n cattle-system <rancher-webhook-xxxxx>`
5. Verify that the webhook allows a request by editing the description for the local cluster
    `k edit cluster.management.cattle.io local`
6. Provision a downstream cluster.
7. Create a new test-user/
8. Add test-user as a cluster member to the newly provisioned downstream cluster.
9. Verify that the user was successfully added to the cluster.
    
## What areas could experience regressions
Creating CRTBs with MCM enabled.

## Are the repro steps accurate/minimal?
1.  `docker run -d --restart=unless-stopped -e  -p 8080:80 -p 9443:443  --privileged rancher/rancher:v2.7-rc-4 --features=multi-cluster-management=false,multi-cluster-management-agent=false`
2.  login to Rancher server
3.  View errors produced in rancher-webhook that state `the server could not find the requested resource (get roletemplates.meta.k8s.io)`
    `k logs -n cattle-system <rancher-webhook-xxxxx>`

**Comment by anupama2501** [comment] 2022-10-31 23:03
Verified on v2.7-head `6b4cf88` , rancher-webhook chart: `v0.3.0-rc5`
docker install 
mcm flag disabled:
1. Create rancher server with the mcm flag disabled `docker run -d --restart=unless-stopped  -p 80:80 -p 443:443 --privileged  rancher/rancher:v2.7-head --features=multi-cluster-management=false,multi-cluster-management-agent=false`
2. Verified rancher-webhook deployment and pods are active and no errors seen in the pod
3. Verified allows a request by editing local cluster `k edit cluster.management.cattle.io local`
mcm flag enabled:
1. Rancher comes up active 
2. Created an rke1 node driver 1 node all roles and rke2 node driver cluster
3. Created a standard user u1 and added the user in the downstream cluster as cluster owner
4. Created a few more crtb from `https://<rancherURL>/v3/clusterroletemplatebindings` in both of the downstream clusters.
5. Verified no errors seen in rancher-webhook pod, rancher logs
Repeated same steps on an HA cluster as well as follows
```
helm install rancher rancher-latest/rancher --version 2.7.0-rc8  --set rancherImageTag=v2.7-head --namespace cattle-system --set hostname=<redacted> --set 'extraEnv[0].name=CATTLE_FEATURES' --set 'extraEnv[0].value=multi-cluster-management=false'`
```
No errors were noticed in the rancher logs.


Upgrade:
MCM disabled
1 . Installed rancher on v2.6.9 with mcm flag disabled `docker run -d --restart=unless-stopped  -p 80:80 -p 443:443 --privileged  rancher/rancher:v2.6.9 --features=multi-cluster-management=false,multi-cluster-management-agent=false`
2. Verified rancher-webhook was active
3.  Upgraded rancher server to v2.7-head with the flag `--features=multi-cluster-management=false,multi-cluster-management-agent=false`
4. Verified rancher-webhook deployment and pods are active and no errors seen in the pod
5. Verified allows a request by editing local cluster `k edit cluster.management.cattle.io local`

**Comment by anupama2501** [comment] 2022-11-01 04:57
awaiting confirmation for any additional test cases to be validated. Issue can be closed otherwise.

**Comment by snasovich** [comment] 2022-11-01 17:34
Also adding that the original issue that led to creation of this one was validated so this issue no longer blocked it: https://github.com/rancher/rancher/issues/38952#issuecomment-1297929501

**Comment by anupama2501** [comment] 2022-11-07 17:14
Closing as the validations look good.

**Closed by anupama2501** 2022-11-07 17:14 UTC
Labels: kind/bug, status/blocker, [zube]: To Test, status/release-blocker, team/area1
