### ISSUE TITLE
Downstream clusters are deleted upon upgrade that are managed in API-created Fleet workspaces

### ISSUE THREAD

**Issue by nickgerace** [rancher/rancher#34744] opened 2021-09-15 17:01 UTC
This occurs on upgrade from 2.5.9 to 2.6.0. Clusters that are in Fleet workspaces created in GUI survive upgrade. Clusters are in Fleet workspaces create via the API do not survive upgrade (v3 Cluster is deleted and Rancher will deprovision nodes, if applicable).

SURE-3379
SURE-3329

**Comment by nickgerace** [comment] 2021-09-27 17:16
## QA Validation

This comment contains the reproduction and validation scenarios for this issue.

### Setup

1. Start with Rancher `v2.5.9` (or `v2.5.8`)
1. Create one Fleet workspace through kubectl and call it `fleet-kubectl`
1. Create another Fleet workspace through the GUI and call it `fleet-dashboard`
1. Provision at least three downstream clusters (provider does not matter, but you can vary it to be sure)
1. Move one cluster to one of the new workspaces, and move another cluster to the other
1. Leave the remaining cluster in `fleet-default`
1. Wait for clusters to reach "Active" state

### Reproduction

1. Upgrade to `v2.6.1-rc3` or `v2.6-head`
1. Observe all v3 management clusters that have corresponding v1 provisioning clusters not in `fleet-default` or `fleet-local` being deleted
1. Move cluster from `fleet-default` to either of the new workspaces and observe the v3 management cluster being deleted

### Validation

1. Observe all clusters eventually reaching an "Active" state (may take awhile due to provisioning v2's initial setup which finishing setting up Fleet resources towards the end of the entire upgrade process)
1. Move all three clusters around between the three workspaces (including `fleet-default`) and wait for them to reach an "Active" state (you can do this multiple times)
1. Observe all clusters eventually reaching an "Active" state (you might see the following issue, but it is transient: https://github.com/rancher/rancher/issues/34937)

### Optional Validation

You can create `GitRepo` CR(s) before and after upgrade, but you may have to edit them based on the workspace. It may be best to create `GitRepo` CR(s) _after_ validation as a result.

**Comment by izaac** [comment] 2021-09-27 23:27
I was not able to reproduce this yet these are my details after following the above documented steps:

- 3 clusters single node all roles RKE1 EC2
- All clusters are assigned to the `fleet-default` fleet workspace by default.
- I created a fleet workspace using kubectl `fleet-kubectl` (see the yaml below)
- I created a fleet workspace using the Dashboard UI `fleet-dashboard`
- I moved two clusters using the Dashboard UI in `v2.5.9` one to a the `fleet-kubectl` and the other to `fleet-dashboard`
- Upgrade was done to `v2.6.0` 
- My expectation was to find any of the downstream clusters deleted from Rancher but none of them were affected.

```yaml
apiVersion: management.cattle.io/v3
kind: FleetWorkspace
metadata:
  name: fleet-kubec
```

I am probably missing a detail somewhere. I will try next to configure the GitRepo CR for each workspace before upgrading next time on clusters with 2+ nodes.

**Comment by izaac** [comment] 2021-09-28 14:23
Reproduced on upgrade from `v2.5.9` to `v2.6.0`

Steps are the same as described above just add:

- Move (`Assign To:`) a Fleet Cluster from the `fleet-dashboard` to the `fleet-kubectl`  workspace.
- Cluster and nodes are removed from Rancher

**Comment by izaac** [comment] 2021-09-28 19:43
Rancher version: `v2.6-head (09/28/2021)` _4df101e_

I reproduced this too with `v2.6.1-rc3` but using a newer `v2.6-head` build I no longer see the clusters and its nodes getting deleted.

I was able to move the cluster between workspaces as expected.

**Closed by izaac** 2021-09-28 19:43 UTC
Labels: internal, area/fleet, [zube]: QA Working, release-note, status/final-release-blocker
