### ISSUE TITLE
docker inspect network settings are broken

### ISSUE THREAD

**Issue by tknecht** [rancher/rancher#6975] opened 2016-12-08 01:01 UTC
**Rancher Version:**
1.2
**Docker Version:**
Docker version 1.12.1, build 23cf638
**OS and where are the hosts located? (cloud, bare metal, etc):**
Linux <hostname> 4.4.0-53-generic #74-Ubuntu SMP Fri Dec 2 15:59:10 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
HA rancher, external DB
**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle
**Steps to Reproduce:**

Service uses "Managed Network"

docker inspect <container id> looks like this:

"NetworkSettings": {
            "Bridge": "",
            "SandboxID": "1e93ef50449173de0ddfc6033ae5e7829739ce30371c144172aa45f0f71517f1",
            "HairpinMode": false,
            "LinkLocalIPv6Address": "",
            "LinkLocalIPv6PrefixLen": 0,
            "Ports": {},
            "SandboxKey": "/var/run/docker/netns/1e93ef504491",
            "SecondaryIPAddresses": null,
            "SecondaryIPv6Addresses": null,
            "EndpointID": "",
            "Gateway": "",
            "GlobalIPv6Address": "",
            "GlobalIPv6PrefixLen": 0,
            "IPAddress": "",
            "IPPrefixLen": 0,
            "IPv6Gateway": "",
            "MacAddress": "",
            "Networks": {
                "none": {
                    "IPAMConfig": null,
                    "Links": null,
                    "Aliases": null,
                    "NetworkID": "9e2963ef217f7663786dacbff026ef285fb0ebe0a5830fd0e86dddf39346a476",
                    "EndpointID": "39f07cc1f46eea5b8f5496a0396bd11a383a7f3f6b09f0385f8517bd951e5276",
                    "Gateway": "",
                    "IPAddress": "",
                    "IPPrefixLen": 0,
                    "IPv6Gateway": "",
                    "GlobalIPv6Address": "",
                    "GlobalIPv6PrefixLen": 0,
                    "MacAddress": ""

**Results:** 

Rancher Setting is Managed but Inspect shows Bridged and the rest is broken as well. 
No ports, no ips, no service links, nothing, ...

**Expected:**

To work as expected based on docker standards. 
It worked fine on 1.2RC5

**Comment by ajacques** [comment] 2016-12-19 21:54
I can confirm that this issue is happening after my migration to v1.2 for me. 

I use docker-gen to generate NGINX configurations which needs a valid value for ```NetworkSettings.Networks.IPAddress```

Any way to fix this issue?

**Comment by leodotcloud** [comment] 2016-12-19 23:57
@tknecht @ajacques What you are seeing is the correct behavior. In this 1.2 release, we changed introduced the infrastructure catalog and as part of it, we switched to CNI interface to interact with network plugins. The way CNI works is it sets the container network to none (similar to `--net=none`) and the network plugin sets up networking directly. Because of this docker inspect doesn't show the networking details. Docker uses libnetwork but Rancher uses CNI.

For much more detailed information: http://blog.kubernetes.io/2016/01/why-Kubernetes-doesnt-use-libnetwork.html

If this answers your question, please close the issue.

**Comment by ajacques** [comment] 2016-12-20 00:10
@leodotcloud Is there a way to maintain the previous behavior? Previously each container would have a 172.x IP address (on the docker0 bridge adapter) and a 10.x (Rancher networking) address. This worked since docker inspect would still show an IP address in the 172.x subnet and other services on my host could route traffic inward from the host into a Docker container.

Ultimately I don't need a specific IP address from a specific subnet, but without an IPAddress in docker inspect then a few management tools that I have are broken.

**Comment by leodotcloud** [comment] 2016-12-20 04:44
@ajacques You would have to use 'Bridge' networking option from the UI and add the label `io.rancher.container.network: true` to get both the IP addresses.

**Comment by ajacques** [comment] 2016-12-20 16:44
@leodotcloud Thanks for responding. Just tried that out:
```
UI:
    [...]
    network_mode: bridge
    labels:
      io.rancher.container.pull_image: always
      io.rancher.container.network: 'true'
```
And I'm still getting:
```
"Networks": {
    "bridge": {
        "IPAMConfig": null,
        "Links": null,
        "Aliases": null,
        "NetworkID": "80c81e6ffe5a7a768e4db5fbbfad68649ab725b605c5be85cb394431e987e36c",
        "EndpointID": "",
        "Gateway": "",
        "IPAddress": "",
        "IPPrefixLen": 0,
        [...]
    }
}
```

And ip addr still only has the single 10.x IP address.

**Comment by leodotcloud** [comment] 2016-12-21 23:29
@ajacques Yes you are right, it's not working as I was hoping to from the UI. Usually this label is used while launching the container from the CLI of the host. 

See: http://docs.rancher.com/rancher/v1.2/en/quick-start-guide/#create-a-container-through-native-docker-cli

So if you want to get the old behavior, you would have to define your services in a docker-compose, set this label on the containers and launch these from the command line. But you would lose a lot of features offered by the Rancher, like scheduling the containers across multiple hosts.

**Comment by pwFoo** [comment] 2016-12-23 11:58
Label isn't a workaround to get docker-gen working. 
Maybe rancher-gen could work? But need to rewrite my services / reverse proxy from docker-gen to rancher-gen to test it...

**Comment by leodotcloud** [comment] 2017-03-17 20:30
@ajacques Looks like you have updated your scripts. I am closing this issue, please feel free to reopen this or open a new one if you have more questions.

**Closed by leodotcloud** 2017-03-17 20:30 UTC
