### ISSUE TITLE
[2.6.1-rc5] Harvester cloud provider is failing in RKE2 cluster with external Harvester cluster

### ISSUE THREAD

**Issue by janeczku** [rancher/rancher#34969] opened 2021-09-29 14:34 UTC
Rancher: 2.6.1-rc5
Harvester: 0.3-rc1

Create RKE2 cluster with Harvester node driver (default cluster config) using Harvester cloud credentials of type `external`.

**Describe the bug**

The `harvester-cloud-provider` pods are crashing

```
  Warning  FailedMount       21m (x2 over 30m)    kubelet            Unable to attach or mount volumes: unmounted volumes=[cloud-config], unattached volumes=[kube-api-access-rt5wf cloud-config]: timed out waiting for the condition
  Warning  FailedMount       12m (x8 over 32m)    kubelet            Unable to attach or mount volumes: unmounted volumes=[cloud-config], unattached volumes=[cloud-config kube-api-access-rt5wf]: timed out waiting for the condition
  Warning  FailedMount       4m8s (x23 over 34m)  kubelet            MountVolume.SetUp failed for volume "cloud-config" : hostPath type check failed: /var/lib/rancher/rke2/etc/config-files/cloud-provider-config is not a file
```

The file `/var/lib/rancher/rke2/etc/config-files/cloud-provider-config` does not exist on the nodes.

The cluster object is missing the content of the cloud-provider-config:

```
apiVersion: provisioning.cattle.io/v1
kind: Cluster
metadata:
  annotations:
    field.cattle.io/creatorId: user-f8qjl
  creationTimestamp: "2021-09-29T10:49:33Z"
  finalizers:
  - wrangler.cattle.io/provisioning-cluster-remove
  generation: 2
  managedFields:
  - apiVersion: provisioning.cattle.io/v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:finalizers:
          .: {}
          v:"wrangler.cattle.io/provisioning-cluster-remove": {}
      f:spec:
        .: {}
        f:cloudCredentialSecretName: {}
        f:kubernetesVersion: {}
        f:rkeConfig:
          .: {}
          f:chartValues:
            .: {}
            f:rke2-calico: {}
          f:etcd:
            .: {}
            f:snapshotRetention: {}
            f:snapshotScheduleCron: {}
          f:localClusterAuthEndpoint: {}
          f:machineGlobalConfig:
            .: {}
            f:cni: {}
            f:disable-kube-proxy: {}
            f:etcd-expose-metrics: {}
            f:profile: {}
          f:machinePools: {}
          f:machineSelectorConfig: {}
          f:registries: {}
          f:upgradeStrategy:
            .: {}
            f:controlPlaneConcurrency: {}
            f:controlPlaneDrainOptions:
              .: {}
              f:timeout: {}
            f:workerConcurrency: {}
            f:workerDrainOptions:
              .: {}
              f:timeout: {}
      f:status:
        .: {}
        f:clusterName: {}
        f:conditions: {}
        f:observedGeneration: {}
    manager: rancher
    operation: Update
    time: "2021-09-29T10:49:34Z"
  name: v0.3.0-rc1
  namespace: fleet-default
  resourceVersion: "847394"
  uid: e9c6dedd-8169-4ffa-8e2e-6c6fb37655ea
spec:
  cloudCredentialSecretName: cattle-global-data:cc-dv4rw
  kubernetesVersion: v1.21.5+rke2r1
  rkeConfig:
    chartValues:
      rke2-calico:
        calicoctl:
          image: rancher/mirrored-calico-ctl
          tag: v3.19.2
        certs:
          node:
            cert: null
            commonName: null
            key: null
          typha:
            caBundle: null
            cert: null
            commonName: null
            key: null
        felixConfiguration:
          featureDetectOverride: ChecksumOffloadBroken=true
        global:
          clusterCIDRv4: ""
          clusterCIDRv6: ""
          systemDefaultRegistry: ""
        imagePullSecrets: {}
        installation:
          calicoNetwork:
            bgp: Disabled
            ipPools:
            - blockSize: 24
              cidr: 10.42.0.0/16
              encapsulation: VXLAN
              natOutgoing: Enabled
          controlPlaneTolerations:
          - effect: NoSchedule
            key: node-role.kubernetes.io/control-plane
            operator: Exists
          - effect: NoExecute
            key: node-role.kubernetes.io/etcd
            operator: Exists
          enabled: true
          imagePath: rancher
          imagePrefix: mirrored-calico-
          kubernetesProvider: ""
        ipamConfig:
          autoAllocateBlocks: true
          strictAffinity: true
        tigeraOperator:
          image: rancher/mirrored-calico-operator
          registry: docker.io
          version: v1.17.6
    etcd:
      snapshotRetention: 5
      snapshotScheduleCron: 0 */5 * * *
    localClusterAuthEndpoint: {}
    machineGlobalConfig:
      cni: calico
      disable-kube-proxy: false
      etcd-expose-metrics: false
      profile: null
    machinePools:
    - controlPlaneRole: true
      etcdRole: true
      machineConfigRef:
        kind: HarvesterConfig
        name: nc-v0.3.0-rc1-pool1-xrnpq
      name: pool1
      quantity: 1
      workerRole: true
    machineSelectorConfig:
    - config:
        cloud-provider-name: harvester
        protect-kernel-defaults: false
    registries: {}
    upgradeStrategy:
      controlPlaneConcurrency: 10%
      controlPlaneDrainOptions:
        timeout: 0
      workerConcurrency: 10%
      workerDrainOptions:
        timeout: 0
```

**Comment by yasker** [comment] 2021-09-29 16:14
@noahgildersleeve Can you confirm the issue is reproducible?

**Comment by yasker** [comment] 2021-09-29 17:11
@janeczku I just had setup a brand new setup with Harvester v0.3.0-rc1 and Rancher v2.6.1-rc5. I cannot reproduce the issue. I have the fields needed in my cluster object.

**Comment by guangbochen** [comment] 2021-09-30 02:57
Currently, we don't support automatically load `cloud-provider-config` config from the external Harvester cluster as it might encounter a CROS site issue, as a temporary workaround u may need to add it via `Edit as YAML` and run this [script](https://github.com/harvester/cloud-provider-harvester/blob/master/deploy/generate_addon.sh) to generate the config.yaml of each guest RKE2 cluster, thanks.

**Comment by yasker** [comment] 2021-09-30 14:54
Harvester team will check if it's possible to support it for v1.0.0/Rancher v2.6.2

**Comment by yasker** [comment] 2021-10-04 23:33
@janeczku Can you help to file an issue in harvester/harvester and link here? It will make it easy for us to track this.

**Comment by Jono-SUSE-Rancher** [comment] 2023-10-30 20:41
Closing as the external cloud credentials support will be deprecated via https://github.com/harvester/harvester/issues/3319.

**Closed by Jono-SUSE-Rancher** 2023-10-30 20:41 UTC
Labels: kind/bug, team/ui, [zube]: Need Info, area/harvester, status/awaiting-harvester
