### ISSUE TITLE
When etcd/controlplane/worker node gets removed from custom cluster , it fails to clean up resulting in the nodes rejoining the cluster as Worker nodes on a reboot

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#17893] opened 2019-02-06 20:55 UTC
Rancher server - v2.1.6

Steps to reproduce the problem:
Create a custom cluster with 1 control plane node , 3 etcd nodes and 2 worker nodes.
Once cluster gets to active state , remove 1 of the etcd nodes from the cluster.

As part of removing this etcd node , I dont see the clean up of etcd container and data happen on the etcd host

When the cleanup does not happen , we are not able to add the same host to the cluster as an etcd node again.

Following errors seen in rancher server logs when rke tried to remove the etcd node:

```
2019/02/06 19:35:32 [INFO] cluster [c-5fjh2] provisioning: [hosts] Cordoning host [<ip>]
2019/02/06 19:35:32 [ERROR] cluster [c-5fjh2] provisioning: [hosts] Can't find node by name [3.16.217.30]
2019/02/06 19:35:32 [INFO] cluster [c-5fjh2] provisioning: [dialer] Setup tunnel for host [<ip>]
2019/02/06 19:35:32 [ERROR] cluster [c-5fjh2] provisioning: [reconcile] Couldn't clean up etcd node [3.16.217.30]: Not able to reach the host: Can't establish dialer connection: node.management.cattle.io "c-5fjh2/m-fc71c0d4d3a9" not found
```

**Comment by sangeethah** [comment] 2019-02-17 02:11
Tested with latest build from master:

Create a custom cluster with 1 control plane node , 3 etcd nodes and 2 worker nodes.
Once cluster gets to active state , remove 1 of the etcd nodes from the cluster.

etcd node gets removed from the cluster successfully.
But etcd data in `/var/lib/etcd` continues to be present and etcd container in the host is constantly in restarting state:

rancher server logs:

```
2019/02/17 01:16:32 [ERROR] cluster [c-f46mz] provisioning: [hosts] Can't find node by name [18.188.161.35]
2019/02/17 01:16:32 [INFO] cluster [c-f46mz] provisioning: [dialer] Setup tunnel for host [18.188.161.35]
2019/02/17 01:16:35 [INFO] cluster [c-f46mz] provisioning: [dialer] Setup tunnel for host [18.188.161.35]
2019/02/17 01:16:38 [INFO] cluster [c-f46mz] provisioning: [dialer] Setup tunnel for host [18.188.161.35]
2019/02/17 01:16:41 [ERROR] cluster [c-f46mz] provisioning: [reconcile] Couldn't clean up etcd node [18.188.161.35]: Not able to reach the host: Can't establish dialer connection: node.management.cattle.io "c-f46mz/m-af1c1210f7b2" not found
```

**Comment by galal-hussein** [comment] 2019-02-21 19:17
The issue is caused because the agent pod exits after the node is deleted from the UI, so rke fails to connect and clean the node properly, this behavior doesn't only happen with etcd but all roles as well.
The workaround for now is to [clean](https://gist.github.com/superseb/2cf186726807a012af59a027cb41270d) the node manually before adding it back to Rancher.

The proposed solution is to delay the agent deletion until rke up finish the removal and the node is no longer referenced in the clusters.

**Comment by alena1108** [comment] 2019-02-21 19:23
Moving out of 2.2 due to the code freeze being close and the impactful nature of the fix

**Comment by aemneina** [comment] 2019-06-04 18:10
I have a user who hits this because their kubelets are still running. Is the plan to clean up all k8s infra containers on delete? Inquiring minds want to know. 

@alena1108 @galal-hussein

**Comment by deniseschannon** [comment] 2020-02-07 21:30
@sangeethah how are you removing the etcd node from the cluster?

**Comment by sangeethah** [comment] 2020-02-07 21:32
@deniseschannon etcd node gets removed from rancher UI

**Comment by danglam105** [comment] 2020-04-26 10:50
Hi, what is the status of this issue? I'm encountering this in Rancher 2.4.2
I tried to add an all roles node to my cluster as the 2nd node but had error ([#1236](https://github.com/rancher/k3s/issues/1236)) (I used Strato VPS), then I deleted the 2nd node from Rancher UI but after that etcd and kubeapi-server containers of 1st node was still trying to connect to the 2nd node

**Comment by maggieliu** [comment] 2020-10-06 17:35
Closing this in favor of https://github.com/rancher/rancher/issues/26545.

**Closed by maggieliu** 2020-10-06 17:36 UTC
Labels: [zube]: Team Red Backlog, internal, kind/bug-qa, priority/0
