### ISSUE TITLE
DNS lookup fails for all containers launched with rancher

### ISSUE THREAD

**Issue by bilal** [rancher/rancher#1771] opened 2015-08-09 22:34 UTC
Containers are not able to resolve hosts for linked services and all DNS lookups are failing with Rancher 0.32 and rancher agent instance v0.3.1 (rancher/agent-instance:v0.3.1) and rancher agent v0.7.11 (rancher/agent:v0.7.11). 

*Steps to reproduce:*

 Launch any container with Rancher server 0.32. Execute shell and try pinging an external host (e.g., google.com) or a linked service. The rancher-agent on each host is not affected by this issue and is able to resolve hosts. 

*Other Info:*

Docker version: 1.6.2
Host provider: AWS EC2

*Error logs from rancher agent:*

09/08/2015 03:17:27rancher-dns: no process found
09/08/2015 03:17:27[[scripts.sh:198] docker_env
09/08/2015 03:17:27[[scripts.sh:26] '[' -e /.dockerenv ']'
09/08/2015 03:17:27[[[scripts.sh:27] docker_env_vars
09/08/2015 03:17:27[[[scripts.sh:19] '[' -e /.dockerenv ']'
09/08/2015 03:17:27[[[scripts.sh:20] grep CATTLE_
09/08/2015 03:17:27[[[scripts.sh:20] xargs -0 '-I{}' echo export '"{}"'
09/08/2015 03:17:27[[[scripts.sh:20] cat /proc/1/environ
09/08/2015 03:17:27[[scripts.sh:27] eval export '"CATTLE_CONFIG_URL=http://HOST:PORT/v1"' export '"CATTLE_AGENT_INSTANCE_AUTH=Basic' 'BASIC-AUTH"' export '"CATTLE_HOME=/var/lib/cattle"'
09/08/2015 03:17:27[[[scripts.sh:27] export CATTLE_CONFIG_URL=http://HOST:PORT/v1 export 'CATTLE_AGENT_INSTANCE_AUTH=Basic AUTH' export CATTLE_HOME=/var/lib/cattle
09/08/2015 03:17:27[[[scripts.sh:27] CATTLE_CONFIG_URL=http://HOST:PORT/v1
09/08/2015 03:17:27[[[scripts.sh:27] CATTLE_AGENT_INSTANCE_AUTH='Basic AUTH'
09/08/2015 03:17:27[[[scripts.sh:27] CATTLE_HOME=/var/lib/cattle
09/08/2015 03:17:27[[scripts.sh:199] script_env
09/08/2015 03:17:27[[scripts.sh:123] '[' -n http://HOST:PORT/v1 ']'
09/08/2015 03:17:27[[scripts.sh:124] return
09/08/2015 03:17:27[[scripts.sh:201] export CATTLE_HOME=/var/lib/cattle
09/08/2015 03:17:27[[scripts.sh:201] CATTLE_HOME=/var/lib/cattle
09/08/2015 03:17:27[[scripts.sh:202] export CATTLE_CONFIG_URL=http://HOST:PORT/v1
09/08/2015 03:17:27[[scripts.sh:202] CATTLE_CONFIG_URL=http://HOST:PORT/v1
09/08/2015 03:17:27[[scripts.sh:203] export CATTLE_STORAGE_URL=
09/08/2015 03:17:27[[scripts.sh:203] CATTLE_STORAGE_URL=
09/08/2015 03:17:27[apply.sh:21] DNS=
09/08/2015 03:17:27[[apply.sh:23] awk '{print $2}'
09/08/2015 03:17:27[[apply.sh:23] grep '^nameserver'
09/08/2015 03:17:27[[apply.sh:23] sed 's/^# nameserver/nameserver/'
09/08/2015 03:17:27[[apply.sh:23] cat /etc/resolv.conf
09/08/2015 03:17:27[apply.sh:23] for address in '$(cat /etc/resolv.conf  | sed '\''s/^# nameserver/nameserver/'\'' | grep ^nameserver | awk '\''{print $2}'\'')'
09/08/2015 03:17:27[apply.sh:24] '[' 172.31.0.2 = 169.254.169.250 ']'
09/08/2015 03:17:27[apply.sh:28] '[' -z '' ']'
09/08/2015 03:17:27[apply.sh:29] DNS='"172.31.0.2"'
09/08/2015 03:17:27[apply.sh:35] sed -i 's/PARENT_DNS/"172.31.0.2"/' content-home/etc/cattle/dns/answers.json
09/08/2015 03:17:27[apply.sh:37] stage_files
09/08/2015 03:17:27[scripts.sh:91] local monit=false
09/08/2015 03:17:27[scripts.sh:93] '[' -d content-home ']'
09/08/2015 03:17:27[scripts.sh:94] find content-home -name '*.sh' -exec chmod +x '{}' ';'
09/08/2015 03:17:27[scripts.sh:95] sed 's/^/INFO: HOME -> /'
09/08/2015 03:17:27[scripts.sh:95] tar xvf - --no-overwrite-dir -C /var/lib/cattle
09/08/2015 03:17:27[scripts.sh:95] tar cf - -C content-home .
09/08/2015 03:17:27[scripts.sh:98] '[' -d content ']'
09/08/2015 03:17:27[scripts.sh:116] '[' false = true ']'
09/08/2015 03:17:27[apply.sh:39] ip addr add 169.254.169.250/32 dev eth0
09/08/2015 03:17:27[apply.sh:39] true
09/08/2015 03:17:27[apply.sh:40] grep -q 169.254.169.254
09/08/2015 03:17:27[apply.sh:40] ip route show
09/08/2015 03:17:27[apply.sh:44] reload_dns
09/08/2015 03:17:27[apply.sh:7] '[' '!' -e /etc/init.d/rancher-dns ']'
09/08/2015 03:17:27[[apply.sh:12] pidof rancher-dns
09/08/2015 03:17:27[apply.sh:12] PID=870
09/08/2015 03:17:27[apply.sh:14] '[' -z 870 ']'
09/08/2015 03:17:27[apply.sh:18] killall -HUP rancher-dns

**Comment by bilal** [comment] 2015-08-10 03:19
After further investigation it seems like the issue is tied to the version of docker on the client hosts and not to the rancher version. I run can reproduce the problem with docker version 1.6.2 but I'm unable to reproduce it with docker version 1.7.1.

**Comment by ibuildthecloud** [comment] 2015-08-10 04:32
@bilal Thanks for pointing this out.  We do all our testing on 1.7.x at the moment so I don't doubt that we could have introduced a regression in 1.6.

**Comment by silviupanaite** [comment] 2015-08-10 11:44
This problem is replicated Docker version 1.7.0, all new containers that I have linked are not working in DNS lookup.
Old containers that are running are not affected.

**Comment by alena1108** [comment] 2015-08-10 14:58
@silviupanaite could you please share:

1) The details of your stack - exported docker-compose.yml would be helpful.
2) The output of answers.json file from the network agent container running on the host having problems. The path to the file is: /var/lib/cattle/etc/cattle/dns/answers.json
3) If you see any errors in agent log (/var/log/rancher/agent.log), could you also include it to the bug

**Comment by silviupanaite** [comment] 2015-08-10 23:54
connector-fullcontact:
  restart: always
  environment:
    NODE_ENV: beta
    REDISCLOUD_URL: redis://none:none@redis-outboxpro:6379
  tty: true
  cpu_shares: 512
  image: docker.unifiedinbox.com:4433/outboxpro/nodejs
  links:
  - redis-outboxpro:redis-outboxpro
  volumes:
  - /connector-fullcontact/data/ue-connector-fullcontact:/usr/share/node/app
  - /connector-fullcontact/logs:/var/log/node
  stdin_open: true
redis-outboxpro:
  tty: true
  image: redis
  stdin_open: true
test-balancer2:
  restart: always
  ports:
  - 8884:5000
  - 8885:5000
  - 8886:5000
  - 8887:5000
  - 8888:5000
  labels:
    io.rancher.loadbalancer.target.connector-twitter: 8885=5000
    io.rancher.loadbalancer.target.connector-linkedin: 8886=5000
    io.rancher.loadbalancer.target.connector-fullcontact: 8887=5000
    io.rancher.loadbalancer.target.connector-weibo: 8883=5000
    io.rancher.loadbalancer.target.connector-facebook: 8888=5000
    io.rancher.loadbalancer.target.connector-xing: 8884=5000
  tty: true
  image: rancher/load-balancer-service
  links:
  - connector-fullcontact:connector-fullcontact
  - connector-linkedin:connector-linkedin
  - connector-facebook:connector-facebook
  - connector-twitter:connector-twitter
  - connector-xing:connector-xing
  - connector-weibo:connector-weibo
  stdin_open: true
connector-twitter:
  restart: always
  environment:
    NODE_ENV: beta
    REDISCLOUD_URL: redis://none:none@redis-outboxpro:6379
  tty: true
  cpu_shares: 512
  image: nodejs
  links:
  - redis-outboxpro:redis-outboxpro
  volumes:
  - /connector-twitter/data/ue-connector-twitter:/usr/share/node/app
  - /connector-twitter/logs:/var/log/node
  stdin_open: true
connector-xing:
  restart: always
  environment:
    NODE_ENV: beta
    REDISCLOUD_URL: redis://none:none@redis-outboxpro:6379
  tty: true
  cpu_shares: 512
  image: docker.unifiedinbox.com:4433/outboxpro/nodejs
  links:
  - redis-outboxpro:redis-outboxpro
  volumes:
  - /connector-xing/data/ue-connector-xing:/usr/share/node/app
  - /connector-xing/logs:/var/log/node
  stdin_open: true
connector-facebook:
  restart: always
  environment:
    NEW_RELIC_APDEX: '0.01'
    NEW_RELIC_APP_NAME: connector-fb
    NEW_RELIC_LICENSE_KEY: db4aadc9771c9195fb7abcef180ae9b63b5a905c
    NODE_ENV: beta
    REDISCLOUD_URL: redis://none:none@redis-outboxpro:6379
  tty: true
  cpu_shares: 512
  image: nodejs
  links:
  - redis-outboxpro:redis-outboxpro
  volumes:
  - /connector-facebook/data/ue-connector-fb:/usr/share/node/app
  - /connector-facebook/logs:/var/log/node
  stdin_open: true
connector-linkedin:
  restart: always
  environment:
    NEW_RELIC_APDEX: '0.01'
    NEW_RELIC_APP_NAME: connector-in
    NEW_RELIC_LICENSE_KEY: db4aadc9771c9195fb7abcef180ae9b63b5a905c
    NODE_ENV: beta
    REDISCLOUD_URL: redis://none:none@redis-outboxpro:6379
  tty: true
  cpu_shares: 512
  image: nodejs
  links:
  - redis-outboxpro:redis-outboxpro
  volumes:
  - /connector-linkedin/data/ue-connector-in:/usr/share/node/app
  - /connector-linkedin/logs:/var/log/node
  stdin_open: true
connector-weibo:
  restart: always
  environment:
    NODE_ENV: beta
    REDISCLOUD_URL: redis://none:none@redis-outboxpro:6379
  tty: true
  cpu_shares: 512
  image: nodejs
  links:
  - redis-outboxpro:redis-outboxpro
  volumes:
  - /connector-weibo/data/ue-connector-weibo:/usr/share/node/app
  - /connector-weibo/logs:/var/log/node
  stdin_open: true

2. no dns file

3.  
08:27:06,927 ERROR cattle [140568136493648] [utils.py:278] Failed to call (['/var/lib/cattle/config.sh', u'host-iptables'],)
2015-08-10 05:22:06,674 ERROR agent [140568136536944] [publisher.py:26] Error [], Request [{"name": "reply.3581326572721852989", "resourceType": "agent", "resourceId": "1a21", "previousNames": ["ping"], "time": 1439184126000, "

**Comment by alena1108** [comment] 2015-08-11 00:23
@silviupanaite Absence of answers.json file is very suspicious, especially knowing that the containers from the previous version continue to run w/o any problem. Are these "successful" containers running on the same host with the services container that fail to resolve DNS? If yes, could you double check that you've tried to pull the "answers.json" file from the container created from "rancher/agent-instance:v0.3.1" image? 

If all the containers that failed to resolve DNS, are running on a different host from the containers that can resolve DNS successfully, then there might be a problem with that particular host/agent on it. If thats the case, could you upload the entire agent.log file from the day when upgrade was performed, and give us a reference to it.

Need this info to narrow down the failure either to DNS answers.json being misconfigured, or network agent having problems

**Comment by silviupanaite** [comment] 2015-08-11 07:26
Yes I hadn't pulled the right container, also these are container running on the same host, tried a different host, got the same problem.
{
    "default": {
        "recurse": [
            "213.186.33.99"
        ]
    },
    "10.42.154.9": {
        "a": {
		"redis.": {"answer": ["10.42.154.9"]},
		"redis.rancher.internal.": {"answer": ["10.42.154.9"]}
    	}

    },

    "10.42.129.161": {
        "a": {
		"redis-outboxpro.": {"answer": ["10.42.50.159"]},
		"redis-outboxpro.rancher.internal.": {"answer": ["10.42.50.159"]},
		"connector-twitter.": {"answer": ["10.42.129.161"]},
		"connector-twitter.rancher.internal.": {"answer": ["10.42.129.161"]}
    	}

    },

    "10.42.97.166": {
        "a": {
		"database.": {"answer": ["10.42.179.148"]},
		"database.rancher.internal.": {"answer": ["10.42.179.148"]},
		"ruby-daemon.": {"answer": ["10.42.97.166"]},
		"ruby-daemon.rancher.internal.": {"answer": ["10.42.97.166"]}
    	}

    },

    "10.42.50.159": {
        "a": {
		"redis-outboxpro.": {"answer": ["10.42.50.159"]},
		"redis-outboxpro.rancher.internal.": {"answer": ["10.42.50.159"]}
    	}

    },

    "10.42.35.122": {
        "a": {
		"mongodb.": {"answer": ["10.42.171.76"]},
		"mongodb.rancher.internal.": {"answer": ["10.42.171.76"]},
		"daemon.": {"answer": ["10.42.97.166"]},
		"daemon.rancher.internal.": {"answer": ["10.42.97.166"]},
		"apache-php.": {"answer": ["10.42.35.122"]},
		"apache-php.rancher.internal.": {"answer": ["10.42.35.122"]},
		"redis.": {"answer": ["10.42.154.9"]},
		"redis.rancher.internal.": {"answer": ["10.42.154.9"]},
		"database.": {"answer": ["10.42.179.148"]},
		"database.rancher.internal.": {"answer": ["10.42.179.148"]}
    	}

    },

    "10.42.171.76": {
        "a": {
		"database.": {"answer": ["10.42.179.148"]},
		"database.rancher.internal.": {"answer": ["10.42.179.148"]},
		"mongodb.": {"answer": ["10.42.171.76"]},
		"mongodb.rancher.internal.": {"answer": ["10.42.171.76"]}
    	}

    },

    "10.42.179.148": {
        "a": {
		"mysql.": {"answer": ["10.42.179.148"]},
		"mysql.rancher.internal.": {"answer": ["10.42.179.148"]}
    	}

    },

    "10.42.140.2": {
        "a": {
		"unifiedinbox.": {"answer": ["10.42.35.122"]},
		"unifiedinbox.rancher.internal.": {"answer": ["10.42.35.122"]}
    	}

    },

    "": {}
}

**Comment by silviupanaite** [comment] 2015-08-11 08:46
this is the network agent errors:
7/18/2015 1:09:03 PM[config.sh:122] rm /var/lib/cattle/download.Je0ZL6v/download
7/18/2015 1:09:03 PM[[[config.sh:124] ls -1 /var/lib/cattle/download.Je0ZL6v
7/18/2015 1:09:03 PM[[config.sh:124] basename iptables-2-57d6c642b0fe838d32afc550f929c743365f9bfa3f31850fe73e4149e76c1f77
7/18/2015 1:09:03 PM[config.sh:124] local dir=iptables-2-57d6c642b0fe838d32afc550f929c743365f9bfa3f31850fe73e4149e76c1f77
7/18/2015 1:09:03 PM[config.sh:125] '[' '!' -e /var/lib/cattle/download.Je0ZL6v/iptables-2-57d6c642b0fe838d32afc550f929c743365f9bfa3f31850fe73e4149e76c1f77 ']'
7/18/2015 1:09:03 PM[config.sh:132] cd /var/lib/cattle/download.Je0ZL6v
7/18/2015 1:09:03 PM[config.sh:134] '[' '!' -e iptables-2-57d6c642b0fe838d32afc550f929c743365f9bfa3f31850fe73e4149e76c1f77/SHA1SUMSSUM ']'
7/18/2015 1:09:03 PM[config.sh:134] '[' '!' -e iptables-2-57d6c642b0fe838d32afc550f929c743365f9bfa3f31850fe73e4149e76c1f77/SHA1SUMS ']'
7/18/2015 1:09:03 PM[config.sh:139] sha1sum -c iptables-2-57d6c642b0fe838d32afc550f929c743365f9bfa3f31850fe73e4149e76c1f77/SHA1SUMSSUM
7/18/2015 1:09:03 PM[config.sh:140] sha1sum -c iptables-2-57d6c642b0fe838d32afc550f929c743365f9bfa3f31850fe73e4149e76c1f77/SHA1SUMS
7/18/2015 1:09:03 PM[config.sh:143] '[' -n '' ']'
7/18/2015 1:09:03 PM[config.sh:150] content_root=/var/lib/cattle/download/iptables/iptables-2-57d6c642b0fe838d32afc550f929c743365f9bfa3f31850fe73e4149e76c1f77
7/18/2015 1:09:03 PM[config.sh:152] '[' -e /var/lib/cattle/download.Je0ZL6v/iptables-2-57d6c642b0fe838d32afc550f929c743365f9bfa3f31850fe73e4149e76c1f77/uptodate ']'
7/18/2015 1:09:03 PM[config.sh:160] '[' -e /var/lib/cattle/download/iptables/iptables-2-57d6c642b0fe838d32afc550f929c743365f9bfa3f31850fe73e4149e76c1f77 ']'
7/18/2015 1:09:03 PM[config.sh:161] rm -rf /var/lib/cattle/download/iptables/iptables-2-57d6c642b0fe838d32afc550f929c743365f9bfa3f31850fe73e4149e76c1f77
7/18/2015 1:09:03 PM[[config.sh:164] dirname /var/lib/cattle/download/iptables/iptables-2-57d6c642b0fe838d32afc550f929c743365f9bfa3f31850fe73e4149e76c1f77
7/18/2015 1:09:03 PM[config.sh:164] mkdir -p /var/lib/cattle/download/iptables
7/18/2015 1:09:03 PM[config.sh:165] mv /var/lib/cattle/download.Je0ZL6v/iptables-2-57d6c642b0fe838d32afc550f929c743365f9bfa3f31850fe73e4149e76c1f77 /var/lib/cattle/download/iptables/iptables-2-57d6c642b0fe838d32afc550f929c743365f9bfa3f31850fe73e4149e76c1f77
7/18/2015 1:09:03 PM[config.sh:252] '[' false '!=' true ']'
7/18/2015 1:09:03 PM[config.sh:253] apply
7/18/2015 1:09:03 PM[config.sh:180] check_applied
7/18/2015 1:09:03 PM[config.sh:170] local current=/var/lib/cattle/download/iptables/iptables-2-57d6c642b0fe838d32afc550f929c743365f9bfa3f31850fe73e4149e76c1f77/../current
7/18/2015 1:09:03 PM[config.sh:171] '[' -e /var/lib/cattle/download/iptables/iptables-2-57d6c642b0fe838d32afc550f929c743365f9bfa3f31850fe73e4149e76c1f77/../current ']'
7/18/2015 1:09:03 PM[[config.sh:171] basename /var/lib/cattle/download/iptables/iptables-2-57d6c642b0fe838d32afc550f929c743365f9bfa3f31850fe73e4149e76c1f77
7/18/2015 1:09:03 PM[config.sh:171] '[' iptables-2-57d6c642b0fe838d32afc550f929c743365f9bfa3f31850fe73e4149e76c1f77 = iptables-2-57d6c642b0fe838d32afc550f929c743365f9bfa3f31850fe73e4149e76c1f77 ']'
7/18/2015 1:09:03 PM[config.sh:172] return 0
7/18/2015 1:09:03 PM[config.sh:180] '[' -e /var/lib/cattle/download/iptables/iptables-2-57d6c642b0fe838d32afc550f929c743365f9bfa3f31850fe73e4149e76c1f77/check.sh ']'
7/18/2015 1:09:03 PM[config.sh:192] '[' '!' -e /var/lib/cattle/download/iptables/iptables-2-57d6c642b0fe838d32afc550f929c743365f9bfa3f31850fe73e4149e76c1f77/apply.sh ']'
7/18/2015 1:09:03 PM[config.sh:197] '[' '!' -x /var/lib/cattle/download/iptables/iptables-2-57d6c642b0fe838d32afc550f929c743365f9bfa3f31850fe73e4149e76c1f77/apply.sh ']'
7/18/2015 1:09:03 PM[config.sh:198] chmod +x /var/lib/cattle/download/iptables/iptables-2-57d6c642b0fe838d32afc550f929c743365f9bfa3f31850fe73e4149e76c1f77/apply.sh
7/18/2015 1:09:03 PM[config.sh:201] VERSION=2-57d6c642b0fe838d32afc550f929c743365f9bfa3f31850fe73e4149e76c1f77
7/18/2015 1:09:03 PM[config.sh:202] info 'Running /var/lib/cattle/download/iptables/iptables-2-57d6c642b0fe838d32afc550f929c743365f9bfa3f31850fe73e4149e76c1f77/apply.sh'
7/18/2015 1:09:03 PM[scripts.sh:33] echo INFO: 'Running /var/lib/cattle/download/iptables/iptables-2-57d6c642b0fe838d32afc550f929c743365f9bfa3f31850fe73e4149e76c1f77/apply.sh'
7/18/2015 1:09:03 PM[config.sh:203] pushd /var/lib/cattle/download/iptables/iptables-2-57d6c642b0fe838d32afc550f929c743365f9bfa3f31850fe73e4149e76c1f77
7/18/2015 1:09:03 PM[config.sh:204] ./apply.sh
7/18/2015 1:09:03 PM[[scripts.sh:198] docker_env
7/18/2015 1:09:03 PM[[scripts.sh:26] '[' -e /.dockerenv ']'
7/18/2015 1:09:03 PM[[[scripts.sh:27] docker_env_vars
7/18/2015 1:09:03 PM[[[scripts.sh:19] '[' -e /.dockerenv ']'
7/18/2015 1:09:03 PM[[[scripts.sh:20] cat /proc/1/environ
7/18/2015 1:09:03 PM[[[scripts.sh:20] xargs -0 '-I{}' echo export '"{}"'
7/18/2015 1:09:03 PM[[[scripts.sh:20] grep CATTLE_
7/18/2015 1:09:03 PM[[scripts.sh:27] eval export '"CATTLE_CONFIG_URL=http://xx.com/v1"' export '"CATTLE_AGENT_INSTANCE_AUTH=Basic' 'MTc5NjYwMDU5QjNFRkQzMzQ5QjI6emNXc3ZqUDJRZXh4SkFMVHpjbjZpZVRhWDVEczVIZVN4VXVCem9zSA=="' export '"CATTLE_HOME=/var/lib/cattle"'
7/18/2015 1:09:03 PM[[[scripts.sh:27] export CATTLE_CONFIG_URL=http://xx.com/v1 export 'CATTLE_AGENT_INSTANCE_AUTH=Basic MTc5NjYwMDU5QjNFRkQzMzQ5QjI6emNXc3ZqUDJRZXh4SkFMVHpjbjZpZVRhWDVEczVIZVN4VXVCem9zSA==' export CATTLE_HOME=/var/lib/cattle
7/18/2015 1:09:03 PM[[[scripts.sh:27] CATTLE_CONFIG_URL=http://xx.com/v1
7/18/2015 1:09:03 PM[[[scripts.sh:27] CATTLE_AGENT_INSTANCE_AUTH='Basic MTc5NjYwMDU5QjNFRkQzMzQ5QjI6emNXc3ZqUDJRZXh4SkFMVHpjbjZpZVRhWDVEczVIZVN4VXVCem9zSA=='
7/18/2015 1:09:03 PM[[[scripts.sh:27] CATTLE_HOME=/var/lib/cattle
7/18/2015 1:09:03 PM[[scripts.sh:199] script_env
7/18/2015 1:09:03 PM[[scripts.sh:123] '[' -n http://rancher.unifiedinbox.com/v1 ']'
7/18/2015 1:09:03 PM[[scripts.sh:124] return
7/18/2015 1:09:03 PM[[scripts.sh:201] export CATTLE_HOME=/var/lib/cattle
7/18/2015 1:09:03 PM[[scripts.sh:201] CATTLE_HOME=/var/lib/cattle
7/18/2015 1:09:03 PM[[scripts.sh:202] export CATTLE_CONFIG_URL=http://rancher.unifiedinbox.com/v1
7/18/2015 1:09:03 PM[[scripts.sh:202] CATTLE_CONFIG_URL=http://xx.com/v1
7/18/2015 1:09:03 PM[[scripts.sh:203] export CATTLE_STORAGE_URL=
7/18/2015 1:09:03 PM[[scripts.sh:203] CATTLE_STORAGE_URL=
7/18/2015 1:09:03 PM[apply.sh:5] echo 1
7/18/2015 1:09:03 PM[apply.sh:6] echo 0
7/18/2015 1:09:03 PM[apply.sh:7] echo 0
7/18/2015 1:09:03 PM[apply.sh:9] iptables-restore -c
7/18/2015 1:09:03 PM[apply.sh:11] stage_files
7/18/2015 1:09:03 PM[scripts.sh:91] local monit=false
7/18/2015 1:09:03 PM[scripts.sh:93] '[' -d content-home ']'
7/18/2015 1:09:03 PM[scripts.sh:94] find content-home -name '*.sh' -exec chmod +x '{}' ';'
7/18/2015 1:09:03 PM[scripts.sh:95] tar cf - -C content-home .
7/18/2015 1:09:03 PM[scripts.sh:95] tar xvf - --no-overwrite-dir -C /var/lib/cattle
7/18/2015 1:09:03 PM[scripts.sh:95] sed 's/^/INFO: HOME -> /'
7/18/2015 1:09:03 PM[scripts.sh:98] '[' -d content ']'
7/18/2015 1:09:03 PM[scripts.sh:116] '[' false = true ']'
7/18/2015 1:09:03 PM[[[config.sh:205] pwd
7/18/2015 1:09:03 PM[[config.sh:205] basename /var/lib/cattle/download/iptables/iptables-2-57d6c642b0fe838d32afc550f929c743365f9bfa3f31850fe73e4149e76c1f77
7/18/2015 1:09:03 PM[config.sh:205] echo iptables-2-57d6c642b0fe838d32afc550f929c743365f9bfa3f31850fe73e4149e76c1f77
7/18/2015 1:09:03 PM[config.sh:206] popd
7/18/2015 1:09:03 PM[config.sh:255] '[' -z '' ']'
7/18/2015 1:09:03 PM[config.sh:256] applied iptables
7/18/2015 1:09:03 PM[config.sh:211] info Sending iptables applied 2-57d6c642b0fe838d32afc550f929c743365f9bfa3f31850fe73e4149e76c1f77
7/18/2015 1:09:03 PM[scripts.sh:33] echo INFO: Sending iptables applied 2-57d6c642b0fe838d32afc550f929c743365f9bfa3f31850fe73e4149e76c1f77
7/18/2015 1:09:03 PM[config.sh:212] put 'http://xx.com/v1//configcontent//iptables?version=2-57d6c642b0fe838d32afc550f929c743365f9bfa3f31850fe73e4149e76c1f77'
7/18/2015 1:09:03 PM[scripts.sh:72] call_curl -X PUT 'http://xx.com/v1//configcontent//iptables?version=2-57d6c642b0fe838d32afc550f929c743365f9bfa3f31850fe73e4149e76c1f77'
7/18/2015 1:09:03 PM[scripts.sh:43] local 'curl=curl -s --connect-timeout 3'
7/18/2015 1:09:03 PM[scripts.sh:44] '[' '' = false ']'
7/18/2015 1:09:03 PM[scripts.sh:46] '[' -n 'Basic MTc5NjYwMDU5QjNFRkQzMzQ5QjI6emNXc3ZqUDJRZXh4SkFMVHpjbjZpZVRhWDVEczVIZVN4VXVCem9zSA==' ']'
7/18/2015 1:09:03 PM[scripts.sh:47] curl -s --connect-timeout 3 -H 'Authorization: Basic MTc5NjYwMDU5QjNFRkQzMzQ5QjI6emNXc3ZqUDJRZXh4SkFMVHpjbjZpZVRhWDVEczVIZVN4VXVCem9zSA==' -X PUT 'http://xx.com/v1//configcontent//iptables?version=2-57d6c642b0fe838d32afc550f929c743365f9bfa3f31850fe73e4149e76c1f77'
7/18/2015 1:09:03 PM[config.sh:260] shift 1
7/18/2015 1:09:03 PM[config.sh:225] '[' 0 -gt 0 ']'
7/18/2015 1:09:03 PM[config.sh:1] cleanup
7/18/2015 1:09:03 PM[config.sh:9] EXIT=0
7/18/2015 1:09:03 PM[config.sh:11] '[' -e /var/lib/cattle/download.Je0ZL6v ']'
7/18/2015 1:09:03 PM[config.sh:12] rm -rf /var/lib/cattle/download.Je0ZL6v
7/18/2015 1:09:03 PM[config.sh:15] return 0
7/18/2015 1:09:03 PM[apply.sh:24] '[' -e /dev/shm ']'
7/18/2015 1:09:03 PM[apply.sh:25] touch /dev/shm/agent-instance-started

**Comment by alena1108** [comment] 2015-08-11 16:59
@silviupanaite I don't see any errors in the agent.log file. But I also don't see any entry for connector-fullcontact service (the one your exported yml file lists) in the answers.json file. Is this file is taken from the same host where the service's instances are running? It should look this way: on the host, where there is at least one instance of connector-fullcontact is running, answers.json file should contain a record:

```
"<ip of  connector-fullcontact container>": {
    "a": {
  // self link
   "connector-fullcontact.": {"answer": ["<ips of all the containers in connector-fullcontact>"]},
    "connector-fullcontact.rancher.internal.": {"answer": ["ips of all the containers in connector-fullcontact"]},
   // link to redis-outboxpro - this service was under connector-fullcontac links in the compose.yml file you've provided
    "redis-outboxpro.": {"answer": ["10.42.154.9"]},
    "redis-outboxpro.rancher.internal.": {"answer": ["10.42.154.9"]},
    // other services linked to  connector-fullcontact
    }
```

After you ensure that all the records connector-fullcontact is supposed to resolve, exist in answers.json file, try to resolve them by executing "dig <dnsName>" command from connector-fullcontact instance, to make sure that the DNS service replies with the right set of records.

Then you can test the connectivity by pinging the ip addresses of the services from your connector-fullcontact instance.

Let us know which step fails exactly  - records are missing, dig doesn't return anything, or ip addresses are not pingable.

**Comment by silviupanaite** [comment] 2015-08-11 19:53
The answers.json looks good, but dns is not resolving, got empty response, also the ip is pingable.

**Comment by alena1108** [comment] 2015-08-11 20:21
@silviupanaite just to double check. If your container has ip address 10.42.35.122, answers.json file has this record:

"10.42.35.122": {
    "a": {
    "mongodb.": {"answer": ["10.42.171.76"]},
    "mongodb.rancher.internal.": {"answer": ["10.42.171.76"]},
    "daemon.": {"answer": ["10.42.97.166"]},
    "daemon.rancher.internal.": {"answer": ["10.42.97.166"]},
    "apache-php.": {"answer": ["10.42.35.122"]},
    "apache-php.rancher.internal.": {"answer": ["10.42.35.122"]},
    "redis.": {"answer": ["10.42.154.9"]},
    "redis.rancher.internal.": {"answer": ["10.42.154.9"]},
    "database.": {"answer": ["10.42.179.148"]},
    "database.rancher.internal.": {"answer": ["10.42.179.148"]}
    }

}
And when you do "dig mongodb" from 10.42.35.122, you get an empty response? And it happens just for some of the instances on the host, and for the rest of the instances - on the same host - everything works fine?

If everything above is true, there is one more thing we can check -  /etc/resolv.conf file content on the instance you are trying to resolve the service name from. It should point to 169.254.169.250

If everything above is true, you might want to try to restart network-agent instance (you can do it from the Rancher UI)

**Comment by silviupanaite** [comment] 2015-08-11 20:42
Restarting the network-agent fixed the issue. Thank you

**Comment by alena1108** [comment] 2015-08-11 21:41
@silviupanaite thank you for the quick follow ups. Please update this bug if the problem ever happens again on any of your hosts. 

Although its restart fixed the problem, the root cause of the bug - network agent not responding on the DNS requests after the upgrade - is not clear. In case it happens for other users again, lets keep this bug open for a some time, @deniseschannon. Plus it makes a good debug reference for all dns related issues :)

**Comment by deniseschannon** [comment] 2015-09-08 17:48
@silviupanaite I'll close this for now as it's been open for about a month. If you have these issues again, please re-open and add comments.

**Closed by deniseschannon** 2015-09-08 17:48 UTC
