### ISSUE TITLE
string not being replaced by their translation in web UI in en-US, Mac OS Safari

### ISSUE THREAD

**Issue by mimizone** [rancher/rancher#13096] opened 2018-04-25 21:51 UTC
**Rancher versions:**
rancher/server: v2.0.0-beta4-rc3
rancher user interface: v2.0.37

**Steps to Reproduce:**
- Mac OS X 10.13.2
- Safari Version 11.0.2 (13604.4.7.1.6)
- Mac OS X UI in English
- Github login, pick english-US language
- go to a cluster page and projects

**Results:**
- a few strings are not converted to the targeted language and shown as for example `%projectGroup.label%*`
- it is everywhere across the UI
- in any other browser version or operating system it works fine
- in any other language (tried french and japanese) it works fine on Safari and others

example of the problem:
<img width="333" alt="screen shot 2018-04-25 at 11 21 52 am" src="https://user-images.githubusercontent.com/46967/39274814-0642fca4-4898-11e8-8239-9c4a216f0248.png">

**Comment by tfiduccia** [comment] 2018-04-25 22:30
@mimizone - I cannot reproduce your issue.  We do have a backend that turns off/on the language tags.  Click anywhere in rancher that isn't a field to bring the browser to the font, then hit Shift+L.  Sometimes people accidentally turn it on.

**Comment by tfiduccia** [comment] 2018-04-25 22:42
Closing - he had an old cached version of the file, so new fields were not showing up properly.

**Comment by mimizone** [comment] 2018-04-25 22:42
@tfiduccia I saw your message too late. Clearing the entire cache of Safari solved the problem. I was advised by vincent on slack that the en-us.json file may be the older version and that a bug that omits specifying the version of the file makes safari load the older version.

**Closed by tfiduccia** 2018-04-25 22:42 UTC
Labels: version/2.0
