### ISSUE TITLE
Error displayed when credentials are changed in an EKS cluster can be made better

### ISSUE THREAD

**Issue by sowmyav27** [rancher/rancher#29104] opened 2020-09-23 04:28 UTC
**What kind of request is this (question/bug/enhancement/feature request):** bug

**Steps to reproduce (least amount of steps as possible):**
- As an admin user create a hosted EKS cluster.
- Assign user1 as the cluster owner of the cluster.
- Login as user1.
- As user1, create a new cloud credential cred1
- Edit cluster, change the. cred to the new cred1
- Click on Configure --> make edits to cluster and click on Save.
Error seen on UI: 
<img width="1073" alt="Screen Shot 2020-09-22 at 7 17 50 PM" src="https://user-images.githubusercontent.com/26032343/93966660-174b2880-fd1a-11ea-8919-08dfc2910a7d.png">

**Expected Result:**
Can this error be made better (not have "undefined")

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): master-head - commit id: `ad014cdc8e`
- Installation option (single install/HA): HA

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): hosted EKS
- Kubernetes version (use `kubectl version`): 

```
1.17
```

**Comment by thedadams** [comment] 2020-10-26 23:49
IN the UI, the error message that is displayed is constructed as ```str = `${ err.get('message')  }: ${  err.get('opt.url') }`;```, however the returned API error doesn't have an `opt` field.

**Comment by sadiapoddar** [comment] 2020-11-23 23:04
reproduced with 2.5.2
steps.
1. Created a hosted EKS cluster as an admin
2. user1 was assigned the "cluster owner" role
3. logged in as use1 and created the new cloud credential  
4. Edited cluster using the new credential
5. When saved, notice the error message on UI
<img width="1338" alt="Screen Shot 2020-11-23 at 3 00 47 PM" src="https://user-images.githubusercontent.com/72409237/100025186-1fb4f380-2d9d-11eb-9789-8b648b265c93.png">

**Comment by sadiapoddar** [comment] 2020-12-02 20:06
Verified on master-5ebc964 and not seeing the fix. 

1. Created a hosted EKS cluster as an admin
2. user1 was assigned the "cluster owner" role
3. logged in as use1 and created the new cloud credential
4. Edited cluster using the new credential
5. When saved, notice the error message on UI
<img width="1392" alt="Screen Shot 2020-12-02 at 11 59 42 AM" src="https://user-images.githubusercontent.com/72409237/100925054-545c3580-3496-11eb-9433-9aad19c56d71.png">
Reopening the bug.

**Comment by westlywright** [comment] 2020-12-02 20:21
@sadiapoddar I dont think this should be reopened. The Ticket was to fix the `undefined` in the error message. The ticket is targeted at 2.5.4 so it wont be in 2.5.2. From the image you posted based on your test of `master-5ebc964` I do not see `undefined` in the message.

**Comment by sadiapoddar** [comment] 2020-12-02 20:30
@westlywright 
Hi Wes, I thought the fix would be the user1 will be able to save the configuration, there will be no error. Since user1 has the cluster ownership. So we don't allow user1 to use a new credential to edit the cluster? 
The fix is just changing the error message to take out the undefined?

**Comment by sadiapoddar** [comment] 2020-12-02 21:49
After consulting with @sowmyav27, the fix is as it's expected to fix the error message. So closing the bug.

**Comment by sadiapoddar** [comment] 2020-12-02 21:51
Verified on v2.5-head, db350a63, and master-head, 5ebc964,
The fix is just taking out the "undefined" word
<img width="1392" alt="Screen Shot 2020-12-02 at 11 59 42 AM" src="https://user-images.githubusercontent.com/72409237/100935834-7c9f6080-34a5-11eb-8bed-ad62918d995a.png">

**Closed by sadiapoddar** 2020-12-02 21:51 UTC
Labels: [zube]: QA Next up, area/kontainer-engine, area/ui, kind/bug-qa, team/ui
