### ISSUE TITLE
kube-apiserver can not connection 172.21.0.9:6443

### ISSUE THREAD

**Issue by ystyle** [rancher/rancher#12669] opened 2018-04-12 17:20 UTC
**Rancher versions:**
rancher/server: preview
rancher/agent: v2.0.0-beta2

**Infrastructure Stack versions:**
healthcheck: 
ipsec:
network-services: flannel
scheduler:
kubernetes (if applicable): v1.10.1

**Docker version: (`docker version`,`docker info` preferred)**
17.03.2-ce
**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
ubuntu 16.04 4.4.0-91-generic
**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
Bare-metal ([tencent cloud](https://cloud.tencent.com/))
**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
single node rancher
**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**
Kubernetes
**Steps to Reproduce:**
```shell
sudo docker run -d --restart=unless-stopped -p 80:80 -p 443:443 rancher/server:preview
sudo docker run -d --privileged --restart=unless-stopped --net=host -v /etc/kubernetes:/etc/kubernetes -v /var/run:/var/run rancher/agent:v2.0.0-beta2 --server https://x40.143.x05.6x --token h7pnkmrhqp5l8f95xl9gwft6chpdbh2wmvbnxlwrksbr52r7k5zmxr --ca-checksum da9201bbc0c5b288b359db2ca694c2c8c1ba303b5822165776329d83f90b730f --worker
```
**Results:**
rancher/agent log 
```
time="2018-04-12T16:35:43Z" level=info msg="Option customConfig=map[address:172.21.0.9 internalAddress: roles:[etcd controlplane]]"
time="2018-04-12T16:35:43Z" level=info msg="Option etcd=true"
time="2018-04-12T16:35:43Z" level=info msg="Option controlPlane=true"
time="2018-04-12T16:35:43Z" level=info msg="Option worker=false"
time="2018-04-12T16:35:43Z" level=info msg="Option requestedHostname=VM-0-9-ubuntu"
time="2018-04-12T16:35:43Z" level=info msg="Connecting to wss://140.143.205.67/v3/connect/register with token h7pnkmrhqp5l8f95xl9gwft6chpdbh2wmvbnxlwrksbr52r7k5zmxr"
time="2018-04-12T16:35:43Z" level=info msg="Connecting to proxy" url="wss://140.143.205.67/v3/connect/register"
time="2018-04-12T16:35:43Z" level=info msg="waiting for node to register"
time="2018-04-12T16:35:45Z" level=info msg="Starting plan monitor"
time="2018-04-12T16:52:04Z" level=error msg="client connection failed: client 12" error="read tcp 172.21.0.9:55496->172.21.0.9:6443: use of closed network connection"
time="2018-04-12T16:52:04Z" level=error msg="client connection failed: client 13" error="read tcp 172.21.0.9:55498->172.21.0.9:6443: use of closed network connection"
time="2018-04-12T16:52:04Z" level=error msg="client connection failed: client 14" error="read tcp 172.21.0.9:55500->172.21.0.9:6443: use of closed network connection"
time="2018-04-12T16:52:04Z" level=error msg="client connection failed: client 18" error="read tcp 172.21.0.9:55508->172.21.0.9:6443: use of closed network connection"
time="2018-04-12T16:52:04Z" level=error msg="client connection failed: client 16" error="read tcp 172.21.0.9:55504->172.21.0.9:6443: use of closed network connection"
time="2018-04-12T16:52:04Z" level=error msg="client connection failed: client 11" error="read tcp 172.21.0.9:55494->172.21.0.9:6443: use of closed network connection"
time="2018-04-12T16:52:04Z" level=error msg="client connection failed: client 17" error="read tcp 172.21.0.9:55506->172.21.0.9:6443: use of closed network connection"
```

rancher/server log at last

```
2018/04/12 17:03:11 [INFO] Provisioning cluster [cluster-fkwcx]
2018/04/12 17:03:11 [INFO] Creating cluster [cluster-fkwcx]
2018/04/12 17:03:11 [INFO] cluster [cluster-fkwcx] provisioning: Building Kubernetes cluster
2018/04/12 17:03:11 [INFO] cluster [cluster-fkwcx] provisioning: [dialer] Setup tunnel for host [172.21.0.9]
2018/04/12 17:03:11 [INFO] cluster [cluster-fkwcx] provisioning: [network] Deploying port listener containers
2018/04/12 17:03:12 [INFO] cluster [cluster-fkwcx] provisioning: [network] Port listener containers deployed successfully
2018/04/12 17:03:12 [INFO] cluster [cluster-fkwcx] provisioning: [network] Running control plane -> etcd port checks
2018/04/12 17:03:12 [INFO] cluster [cluster-fkwcx] provisioning: [network] Successfully started [rke-port-checker] container on host [172.21.0.9]
2018/04/12 17:03:12 [INFO] cluster [cluster-fkwcx] provisioning: [network] Running control plane -> worker port checks
2018/04/12 17:03:12 [INFO] cluster [cluster-fkwcx] provisioning: [network] Successfully started [rke-port-checker] container on host [172.21.0.9]
2018/04/12 17:03:12 [INFO] cluster [cluster-fkwcx] provisioning: [network] Running workers -> control plane port checks
2018/04/12 17:03:12 [INFO] cluster [cluster-fkwcx] provisioning: [network] Removing port listener containers
2018/04/12 17:03:12 [INFO] cluster [cluster-fkwcx] provisioning: [remove/rke-etcd-port-listener] Successfully removed container on host [172.21.0.9]
2018/04/12 17:03:13 [INFO] cluster [cluster-fkwcx] provisioning: [remove/rke-cp-port-listener] Successfully removed container on host [172.21.0.9]
2018/04/12 17:03:13 [INFO] cluster [cluster-fkwcx] provisioning: [network] Port listener containers removed successfully
2018/04/12 17:03:13 [INFO] cluster [cluster-fkwcx] provisioning: [certificates] Attempting to recover certificates from backup on host [172.21.0.9]
2018/04/12 17:03:13 [INFO] cluster [cluster-fkwcx] provisioning: [certificates] Successfully started [cert-fetcher] container on host [172.21.0.9]
2018/04/12 17:03:17 [INFO] cluster [cluster-fkwcx] provisioning: [certificates] Certificate backup found on host [172.21.0.9]
2018/04/12 17:03:17 [INFO] cluster [cluster-fkwcx] provisioning: [reconcile] Rebuilding and updating local kube config
2018/04/12 17:03:17 [INFO] cluster [cluster-fkwcx] provisioning: Successfully Deployed local admin kubeconfig at [management-state/rke/rke-052685977/kube_config_cluster.yml]
2018/04/12 17:03:17 [INFO] cluster [cluster-fkwcx] provisioning: [reconcile] host [172.21.0.9] is active master on the cluster
2018/04/12 17:03:17 [INFO] cluster [cluster-fkwcx] provisioning: [reconcile] Reconciling cluster state
2018/04/12 17:03:17 [INFO] cluster [cluster-fkwcx] provisioning: [reconcile] This is newly generated cluster
2018/04/12 17:03:17 [INFO] cluster [cluster-fkwcx] provisioning: [certificates] Deploying kubernetes certificates to Cluster nodes
2018/04/12 17:03:22 [INFO] cluster [cluster-fkwcx] provisioning: Successfully Deployed local admin kubeconfig at [management-state/rke/rke-052685977/kube_config_cluster.yml]
2018/04/12 17:03:22 [INFO] cluster [cluster-fkwcx] provisioning: [certificates] Successfully deployed kubernetes certificates to Cluster nodes
2018/04/12 17:03:23 [INFO] cluster [cluster-fkwcx] provisioning: Pre-pulling kubernetes images
2018/04/12 17:03:23 [INFO] cluster [cluster-fkwcx] provisioning: Kubernetes images pulled successfully
2018/04/12 17:03:23 [INFO] cluster [cluster-fkwcx] provisioning: [etcd] Building up etcd plane..
2018/04/12 17:03:23 [INFO] cluster [cluster-fkwcx] provisioning: [etcd] Successfully started [rke-log-linker] container on host [172.21.0.9]
2018/04/12 17:03:23 [INFO] cluster [cluster-fkwcx] provisioning: [remove/rke-log-linker] Successfully removed container on host [172.21.0.9]
2018/04/12 17:03:23 [INFO] cluster [cluster-fkwcx] provisioning: [etcd] Successfully started etcd plane..
2018/04/12 17:03:23 [INFO] cluster [cluster-fkwcx] provisioning: [controlplane] Building up Controller Plane..
2018/04/12 17:03:23 [INFO] cluster [cluster-fkwcx] provisioning: [sidekick] Sidekick container already created on host [172.21.0.9]
2018/04/12 17:03:24 [INFO] cluster [cluster-fkwcx] provisioning: [healthcheck] Start Healthcheck on service [kube-apiserver] on host [172.21.0.9]
2018/04/12 17:03:24 [INFO] cluster [cluster-fkwcx] provisioning: [healthcheck] service [kube-apiserver] on host [172.21.0.9] is healthy
2018/04/12 17:03:24 [INFO] cluster [cluster-fkwcx] provisioning: [controlplane] Successfully started [rke-log-linker] container on host [172.21.0.9]
2018/04/12 17:03:25 [INFO] cluster [cluster-fkwcx] provisioning: [remove/rke-log-linker] Successfully removed container on host [172.21.0.9]
2018/04/12 17:03:25 [INFO] cluster [cluster-fkwcx] provisioning: [healthcheck] Start Healthcheck on service [kube-controller-manager] on host [172.21.0.9]
2018/04/12 17:03:25 [INFO] cluster [cluster-fkwcx] provisioning: [healthcheck] service [kube-controller-manager] on host [172.21.0.9] is healthy
2018/04/12 17:03:25 [INFO] cluster [cluster-fkwcx] provisioning: [controlplane] Successfully started [rke-log-linker] container on host [172.21.0.9]
2018/04/12 17:03:25 [INFO] cluster [cluster-fkwcx] provisioning: [remove/rke-log-linker] Successfully removed container on host [172.21.0.9]
2018/04/12 17:03:25 [INFO] cluster [cluster-fkwcx] provisioning: [healthcheck] Start Healthcheck on service [kube-scheduler] on host [172.21.0.9]
2018/04/12 17:03:25 [INFO] cluster [cluster-fkwcx] provisioning: [healthcheck] service [kube-scheduler] on host [172.21.0.9] is healthy
2018/04/12 17:03:26 [INFO] cluster [cluster-fkwcx] provisioning: [controlplane] Successfully started [rke-log-linker] container on host [172.21.0.9]
2018/04/12 17:03:26 [INFO] cluster [cluster-fkwcx] provisioning: [remove/rke-log-linker] Successfully removed container on host [172.21.0.9]
2018/04/12 17:03:26 [INFO] cluster [cluster-fkwcx] provisioning: [controlplane] Successfully started Controller Plane..
2018/04/12 17:03:26 [INFO] cluster [cluster-fkwcx] provisioning: [authz] Creating rke-job-deployer ServiceAccount
2018/04/12 17:03:26 [INFO] cluster [cluster-fkwcx] provisioning: [authz] rke-job-deployer ServiceAccount created successfully
2018/04/12 17:03:26 [INFO] cluster [cluster-fkwcx] provisioning: [authz] Creating system:node ClusterRoleBinding
2018/04/12 17:03:26 [INFO] cluster [cluster-fkwcx] provisioning: [authz] system:node ClusterRoleBinding created successfully
2018/04/12 17:03:26 [INFO] cluster [cluster-fkwcx] provisioning: [certificates] Save kubernetes certificates as secrets
2018/04/12 17:03:29 [INFO] cluster [cluster-fkwcx] provisioning: [certificates] Successfully saved certificates as kubernetes secret [k8s-certs]
2018/04/12 17:03:29 [INFO] cluster [cluster-fkwcx] provisioning: [state] Saving cluster state to Kubernetes
2018/04/12 17:03:29 [INFO] cluster [cluster-fkwcx] provisioning: [state] Successfully Saved cluster state to Kubernetes ConfigMap: cluster-state
2018/04/12 17:03:29 [INFO] cluster [cluster-fkwcx] provisioning: [worker] Building up Worker Plane..
2018/04/12 17:03:29 [INFO] cluster [cluster-fkwcx] provisioning: [sidekick] Sidekick container already created on host [172.21.0.9]
2018/04/12 17:03:30 [INFO] cluster [cluster-fkwcx] provisioning: [healthcheck] Start Healthcheck on service [kubelet] on host [172.21.0.9]
2018/04/12 17:03:30 [INFO] cluster [cluster-fkwcx] provisioning: [healthcheck] service [kubelet] on host [172.21.0.9] is healthy
2018/04/12 17:03:30 [INFO] cluster [cluster-fkwcx] provisioning: [worker] Successfully started [rke-log-linker] container on host [172.21.0.9]
2018/04/12 17:03:30 [INFO] cluster [cluster-fkwcx] provisioning: [remove/rke-log-linker] Successfully removed container on host [172.21.0.9]
2018/04/12 17:03:30 [INFO] cluster [cluster-fkwcx] provisioning: [healthcheck] Start Healthcheck on service [kube-proxy] on host [172.21.0.9]
2018/04/12 17:03:30 [INFO] cluster [cluster-fkwcx] provisioning: [healthcheck] service [kube-proxy] on host [172.21.0.9] is healthy
2018/04/12 17:03:31 [INFO] cluster [cluster-fkwcx] provisioning: [worker] Successfully started [rke-log-linker] container on host [172.21.0.9]
2018/04/12 17:03:31 [INFO] cluster [cluster-fkwcx] provisioning: [remove/rke-log-linker] Successfully removed container on host [172.21.0.9]
2018/04/12 17:03:31 [INFO] cluster [cluster-fkwcx] provisioning: [worker] Successfully started Worker Plane..
2018/04/12 17:03:31 [INFO] cluster [cluster-fkwcx] provisioning: [sync] Syncing nodes Labels and Taints
2018-04-12 17:03:38.060487 I | mvcc: store.index: compact 1916
2018-04-12 17:03:38.061851 I | mvcc: finished scheduled compaction at 1916 (took 861.043µs)

```

etcd log 

```
ubuntu@VM-0-9-ubuntu:~$ docker logs etcd
2018-04-12 16:36:35.887944 I | etcdmain: etcd Version: 3.1.12
2018-04-12 16:36:35.888062 I | etcdmain: Git SHA: 918698add
2018-04-12 16:36:35.888082 I | etcdmain: Go Version: go1.8.7
2018-04-12 16:36:35.888093 I | etcdmain: Go OS/Arch: linux/amd64
2018-04-12 16:36:35.888106 I | etcdmain: setting maximum number of CPUs to 1, total number of available CPUs is 1
2018-04-12 16:36:35.888174 I | embed: peerTLS: cert = /etc/kubernetes/ssl/kube-etcd-172-21-0-9.pem, key = /etc/kubernetes/ssl/kube-etcd-172-21-0-9-key.pem, ca = , trusted-ca = /etc/kubernetes/ssl/kube-ca.pem, client-cert-auth = true
2018-04-12 16:36:35.888873 I | embed: listening for peers on https://0.0.0.0:2380
2018-04-12 16:36:35.888941 I | embed: listening for client requests on 0.0.0.0:2379
2018-04-12 16:36:35.948345 I | warning: ignoring ServerName for user-provided CA for backwards compatibility is deprecated
2018-04-12 16:36:35.948562 I | etcdserver: name = etcd-VM-0-9-ubuntu
2018-04-12 16:36:35.948609 I | etcdserver: data dir = /var/lib/rancher/etcd
2018-04-12 16:36:35.948624 I | etcdserver: member dir = /var/lib/rancher/etcd/member
2018-04-12 16:36:35.948635 I | etcdserver: heartbeat = 100ms
2018-04-12 16:36:35.948645 I | etcdserver: election = 1000ms
2018-04-12 16:36:35.948672 I | etcdserver: snapshot count = 10000
2018-04-12 16:36:35.948694 I | etcdserver: advertise client URLs = https://172.21.0.9:2379,https://172.21.0.9:4001
2018-04-12 16:36:35.948715 I | etcdserver: initial advertise peer URLs = https://172.21.0.9:2380
2018-04-12 16:36:35.948729 I | etcdserver: initial cluster = etcd-VM-0-9-ubuntu=https://172.21.0.9:2380
2018-04-12 16:36:36.055473 I | etcdserver: starting member 2e01e823c390516f in cluster ba3037dfd6d856a4
2018-04-12 16:36:36.055499 I | raft: 2e01e823c390516f became follower at term 0
2018-04-12 16:36:36.055507 I | raft: newRaft 2e01e823c390516f [peers: [], term: 0, commit: 0, applied: 0, lastindex: 0, lastterm: 0]
2018-04-12 16:36:36.055511 I | raft: 2e01e823c390516f became follower at term 1
2018-04-12 16:36:36.296273 I | warning: ignoring ServerName for user-provided CA for backwards compatibility is deprecated
2018-04-12 16:36:36.296796 I | warning: ignoring ServerName for user-provided CA for backwards compatibility is deprecated
2018-04-12 16:36:36.296816 I | etcdserver: starting server... [version: 3.1.12, cluster version: to_be_decided]
2018-04-12 16:36:36.296852 I | embed: ClientTLS: cert = /etc/kubernetes/ssl/kube-etcd-172-21-0-9.pem, key = /etc/kubernetes/ssl/kube-etcd-172-21-0-9-key.pem, ca = , trusted-ca = /etc/kubernetes/ssl/kube-ca.pem, client-cert-auth = true
2018-04-12 16:36:36.298479 I | etcdserver/membership: added member 2e01e823c390516f [https://172.21.0.9:2380] to cluster ba3037dfd6d856a4
2018-04-12 16:36:36.959681 I | raft: 2e01e823c390516f is starting a new election at term 1
2018-04-12 16:36:36.959860 I | raft: 2e01e823c390516f became candidate at term 2
2018-04-12 16:36:36.959910 I | raft: 2e01e823c390516f received MsgVoteResp from 2e01e823c390516f at term 2
2018-04-12 16:36:36.959938 I | raft: 2e01e823c390516f became leader at term 2
2018-04-12 16:36:36.959955 I | raft: raft.node: 2e01e823c390516f elected leader 2e01e823c390516f at term 2
2018-04-12 16:36:36.960390 I | etcdserver: setting up the initial cluster version to 3.1
2018-04-12 16:36:36.963863 N | etcdserver/membership: set the initial cluster version to 3.1
2018-04-12 16:36:36.963936 I | etcdserver/api: enabled capabilities for version 3.1
2018-04-12 16:36:36.963995 I | etcdserver: published {Name:etcd-VM-0-9-ubuntu ClientURLs:[https://172.21.0.9:2379 https://172.21.0.9:4001]} to cluster ba3037dfd6d856a4
2018-04-12 16:36:36.964051 I | embed: ready to serve client requests
2018-04-12 16:36:36.964400 I | embed: serving client requests on [::]:2379
2018-04-12 16:52:29.019193 W | etcdserver: apply entries took too long [715.12409ms for 1 entries]
2018-04-12 16:52:29.021035 W | etcdserver: avoid queries with large range/delete range!
2018-04-12 16:52:35.012614 W | etcdserver: apply entries took too long [449.967118ms for 1 entries]
2018-04-12 16:52:35.012689 W | etcdserver: avoid queries with large range/delete range!
2018-04-12 17:01:32.888868 I | mvcc: store.index: compact 532
2018-04-12 17:01:32.890208 I | mvcc: finished scheduled compaction at 532 (took 659.592µs)
2018-04-12 17:06:32.903929 I | mvcc: store.index: compact 867
2018-04-12 17:06:32.904858 I | mvcc: finished scheduled compaction at 867 (took 544.871µs)
2018-04-12 17:11:32.920448 I | mvcc: store.index: compact 1202
2018-04-12 17:11:32.921431 I | mvcc: finished scheduled compaction at 1202 (took 622.389µs)
2018-04-12 17:16:32.936225 I | mvcc: store.index: compact 1533
2018-04-12 17:16:32.937370 I | mvcc: finished scheduled compaction at 1533 (took 741.949µs)
```

**Comment by superseb** [comment] 2018-04-13 11:29
What is the UI showing for your cluster? The logs provided don't show a real indication for failure. I see you have capital letters in you hostname, there this open issue for that here: https://github.com/rancher/rancher/issues/12499

**Comment by ystyle** [comment] 2018-04-13 11:48
![chrome_2018-04-13_19-45-07](https://user-images.githubusercontent.com/4478635/38733076-30ad065e-3f53-11e8-968d-495ba181b942.png)

yes, i has capital letters in you hostname , but the hostname can't be change , [tencent cloud](https://cloud.tencent.com/) use hostname to verify `sudo`  comand permission

**Comment by superseb** [comment] 2018-04-13 12:03
Ok, this issue has to be fixed. Can you try the following workaround:

- Add `--node-name vm-0-9-ubuntu` to the `docker run` command when adding the node

**Comment by ystyle** [comment] 2018-04-13 12:40
Good, it works

**Comment by superseb** [comment] 2018-04-13 12:42
Ok closing as duplicate of https://github.com/rancher/rancher/issues/12499, where it will be fixed.

**Closed by superseb** 2018-04-13 12:42 UTC
Labels: status/more-info, version/2.0
