### ISSUE TITLE
CPU Utilization wrong in container view

### ISSUE THREAD

**Issue by janrueckert** [rancher/rancher#2158] opened 2015-09-28 00:20 UTC
Running some benchmarks I noticed, that the cpu usage in the container view differs from that in host view. The host view showed the usage correctly in relation to 100%. The container view showed the maximum usage in relation to the cores installed but the usage in relation to 100%.

Usage on host: http://i.imgur.com/nrLq6GV.png
Usage on container: http://i.imgur.com/v3wfFKg.png

**Comment by vincent99** [comment] 2015-09-29 18:52
YThe intended behavior is like you'd see in `top`, if more than one core is in use then it will exceed 100%.  So the scale should go to 100% * number_of_cores as it does on the container screen.

The bug is either the scale is set wrong for the host version, or the number of CPUs isn't being provided in the host stats socket.  Will look into it.

**Comment by janrueckert** [comment] 2015-10-01 22:46
I found the corresponding lines. Should the label of the Y-axis be 100% * number_of_cores or 100% just like in host view? For my part I would prefer 100% and the usage / number_of cores.

**Comment by vincent99** [comment] 2015-10-03 01:05
My intention was that it go to e.g. 800% for 8 cores, as you would see in `top`.  The bug is that there's a flag to see if the scales were set that's set by the memory data point, but the first point doesn't include cpu data because it's all a delta from the previous point.  So the CPU scale is never actually getting set correctly.  Will be fixed in the next release.

**Comment by vincent99** [comment] 2015-10-09 19:55
@deniseschannon I think this was actually in last week's release but I forgot to mark it as resolved.  You'll need a host with multiple cores (Packet works well).

**Comment by deniseschannon** [comment] 2015-10-09 20:46
Verified that the % for hosts/containers are matching when host has multiple cores.

v0.41.0-rc1

**Closed by deniseschannon** 2015-10-09 20:46 UTC
Labels: area/stats, area/ui, kind/bug, status/resolved, status/to-test
