### ISSUE TITLE
Istio Traffic Graph UI elements partly hidden

### ISSUE THREAD

**Issue by bashofmann** [rancher/rancher#27747] opened 2020-06-26 11:25 UTC
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
* Activate Istio in a cluster
* Activate Istio Proxy Injection in a namespace
* Deploy a workload into this namespace
* Go to workloads Traffic Graph

**Result:**
The drop down controls of the embeded Kiali traffic graph are partly hidden.

<img width="1490" alt="Bildschirmfoto 2020-06-26 um 13 22 31" src="https://user-images.githubusercontent.com/243056/85852054-2a4c6c00-b7b0-11ea-9e25-3cb0c86cabd1.png">
<img width="1495" alt="Bildschirmfoto 2020-06-26 um 13 22 40" src="https://user-images.githubusercontent.com/243056/85852069-2f112000-b7b0-11ea-878e-65fd6183f76c.png">

**Other details that may be helpful:**
I first noticed this on Rancher 2.4.5 with Istio 1.4.10. I think it was still working correctly with 2.4.3.

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): 2.4.5
- Istio version: 1.4.10
- Installation option (single install/HA): HA
- Browser: Chrome 84.0.4147.56

**Comment by rancher-max** [comment] 2020-06-26 18:29
To clarify a little bit, the notable section is what I have outlined in red:

<img width="1342" alt="image" src="https://user-images.githubusercontent.com/55997940/85889415-4811d500-b7a0-11ea-8e5a-d7cc5b90fe93.png">

**Comment by rayandas** [comment] 2022-12-22 13:29
Validated it on Rancher 2.6.9. The issue is not reproducible. It has been fixed. Hence closing the issue.

**Closed by rayandas** 2022-12-22 13:29 UTC
Labels: area/istio, [zube]: Next Up, team/infracloud
