### ISSUE TITLE
Rancher crashing in syncTaints

### ISSUE THREAD

**Issue by gregsidelinger** [rancher/rancher#33478] opened 2021-07-04 18:40 UTC
**What kind of request is this (question/bug/enhancement/feature request):** bug

**Steps to reproduce (least amount of steps as possible):**
In an RKE cluster managed by rancher:
  * Add a new worker node to cluster.  I'm using none node pool nodes.
  * Stop the cattle-node-agent daemonsets from talking to rancher.  I set the CATTLE_SERVER var to a bad name and kill all existing pods.
  * Stop the cattle-cluster-agent` kubectl scale deployment cattle-cluster-agent --replicas=0`
  * Wait for rancher to loose connectivity to the cluster.
  * Add a taint to the new node from the rancher console
  * Start the cattle-cluster-agent` kubectl scale deployment cattle-cluster-agent --replicas=1`

**Result:**
Watch the rancher pods in the rancher cattle-system namespace  in the rancher cluster till one of them crashes.
Here is the stack trace from the pod that crashed.
```
E0703 04:13:27.891195       7 runtime.go:78] Observed a panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer dereference)
goroutine 7274 [running]:
k8s.io/apimachinery/pkg/util/runtime.logPanic(0x3d822e0, 0x7623260)
	/go/pkg/mod/k8s.io/apimachinery@v0.20.0/pkg/util/runtime/runtime.go:74 +0x92
k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
	/go/pkg/mod/k8s.io/apimachinery@v0.20.0/pkg/util/runtime/runtime.go:48 +0x82
panic(0x3d822e0, 0x7623260)
	/usr/local/go/src/runtime/panic.go:969 +0x166
github.com/rancher/rancher/pkg/controllers/managementuser/nodesyncer.(*nodesSyncer).syncTaints(0xc0923aeb00, 0xc02372f960, 0x16, 0xc017e1a900, 0xc000600000, 0x7f6cd0b8d2f0, 0x0, 0xc017e1a900)
	/go/src/github.com/rancher/rancher/pkg/controllers/managementuser/nodesyncer/nodetaints.go:34 +0x11e
github.com/rancher/rancher/pkg/generated/norman/management.cattle.io/v3.(*nodeController).AddHandler.func1(0xc02372f960, 0x16, 0x45de300, 0xc017e1a900, 0xc08cd33b20, 0x3, 0x3, 0xc08cd33b38)
	/go/src/github.com/rancher/rancher/pkg/generated/norman/management.cattle.io/v3/zz_generated_node_controller.go:156 +0x63
github.com/rancher/norman/controller.(*genericController).AddHandler.func1(0xc02372f960, 0x16, 0x5018f20, 0xc017e1a900, 0x20, 0x4174020, 0xc0cd432d90, 0xc0c4eeb980)
	/go/pkg/mod/github.com/rancher/norman@v0.0.0-20210225010917-c7fd1e24145b/controller/generic_controller.go:62 +0x221
github.com/rancher/lasso/pkg/controller.SharedControllerHandlerFunc.OnChange(0xc074d631d0, 0xc02372f960, 0x16, 0x5018f20, 0xc017e1a900, 0xc0cd432d90, 0x0, 0x1, 0xc0cd432d70)
	/go/pkg/mod/github.com/rancher/lasso@v0.0.0-20200905045615-7fcb07d6a20b/pkg/controller/sharedcontroller.go:29 +0x4e
github.com/rancher/lasso/pkg/controller.(*sharedHandler).OnChange(0xc021834510, 0xc02372f960, 0x16, 0x5018f20, 0xc017e1a900, 0xc049c32c01, 0x0)
	/go/pkg/mod/github.com/rancher/lasso@v0.0.0-20200905045615-7fcb07d6a20b/pkg/controller/sharedhandler.go:65 +0x14a
github.com/rancher/lasso/pkg/controller.(*controller).syncHandler(0xc0217ff550, 0xc02372f960, 0x16, 0xc032a4ef90, 0xc08cd33d50)
	/go/pkg/mod/github.com/rancher/lasso@v0.0.0-20200905045615-7fcb07d6a20b/pkg/controller/controller.go:210 +0xd1
github.com/rancher/lasso/pkg/controller.(*controller).processSingleItem(0xc0217ff550, 0x3a62f40, 0xc06c00af90, 0x0, 0x0)
	/go/pkg/mod/github.com/rancher/lasso@v0.0.0-20200905045615-7fcb07d6a20b/pkg/controller/controller.go:192 +0xd7
github.com/rancher/lasso/pkg/controller.(*controller).processNextWorkItem(0xc0217ff550, 0x203001)
	/go/pkg/mod/github.com/rancher/lasso@v0.0.0-20200905045615-7fcb07d6a20b/pkg/controller/controller.go:169 +0x51
github.com/rancher/lasso/pkg/controller.(*controller).runWorker(0xc0217ff550)
	/go/pkg/mod/github.com/rancher/lasso@v0.0.0-20200905045615-7fcb07d6a20b/pkg/controller/controller.go:158 +0x2b
k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0xc046e5e140)
	/go/pkg/mod/k8s.io/apimachinery@v0.20.0/pkg/util/wait/wait.go:155 +0x5f
k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0xc046e5e140, 0x4fecfa0, 0xc032a4f050, 0x1, 0xc01660ef00)
	/go/pkg/mod/k8s.io/apimachinery@v0.20.0/pkg/util/wait/wait.go:156 +0xa3
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc046e5e140, 0x3b9aca00, 0x0, 0x1, 0xc01660ef00)
	/go/pkg/mod/k8s.io/apimachinery@v0.20.0/pkg/util/wait/wait.go:133 +0x98
k8s.io/apimachinery/pkg/util/wait.Until(0xc046e5e140, 0x3b9aca00, 0xc01660ef00)
	/go/pkg/mod/k8s.io/apimachinery@v0.20.0/pkg/util/wait/wait.go:90 +0x4d
created by github.com/rancher/lasso/pkg/controller.(*controller).run
	/go/pkg/mod/github.com/rancher/lasso@v0.0.0-20200905045615-7fcb07d6a20b/pkg/controller/controller.go:129 +0x31f
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x168 pc=0x2ab2b7e]

goroutine 7274 [running]:
k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
	/go/pkg/mod/k8s.io/apimachinery@v0.20.0/pkg/util/runtime/runtime.go:55 +0x105
panic(0x3d822e0, 0x7623260)
	/usr/local/go/src/runtime/panic.go:969 +0x166
github.com/rancher/rancher/pkg/controllers/managementuser/nodesyncer.(*nodesSyncer).syncTaints(0xc0923aeb00, 0xc02372f960, 0x16, 0xc017e1a900, 0xc000600000, 0x7f6cd0b8d2f0, 0x0, 0xc017e1a900)
	/go/src/github.com/rancher/rancher/pkg/controllers/managementuser/nodesyncer/nodetaints.go:34 +0x11e
github.com/rancher/rancher/pkg/generated/norman/management.cattle.io/v3.(*nodeController).AddHandler.func1(0xc02372f960, 0x16, 0x45de300, 0xc017e1a900, 0xc08cd33b20, 0x3, 0x3, 0xc08cd33b38)
	/go/src/github.com/rancher/rancher/pkg/generated/norman/management.cattle.io/v3/zz_generated_node_controller.go:156 +0x63
github.com/rancher/norman/controller.(*genericController).AddHandler.func1(0xc02372f960, 0x16, 0x5018f20, 0xc017e1a900, 0x20, 0x4174020, 0xc0cd432d90, 0xc0c4eeb980)
	/go/pkg/mod/github.com/rancher/norman@v0.0.0-20210225010917-c7fd1e24145b/controller/generic_controller.go:62 +0x221
github.com/rancher/lasso/pkg/controller.SharedControllerHandlerFunc.OnChange(0xc074d631d0, 0xc02372f960, 0x16, 0x5018f20, 0xc017e1a900, 0xc0cd432d90, 0x0, 0x1, 0xc0cd432d70)
	/go/pkg/mod/github.com/rancher/lasso@v0.0.0-20200905045615-7fcb07d6a20b/pkg/controller/sharedcontroller.go:29 +0x4e
github.com/rancher/lasso/pkg/controller.(*sharedHandler).OnChange(0xc021834510, 0xc02372f960, 0x16, 0x5018f20, 0xc017e1a900, 0xc049c32c01, 0x0)
	/go/pkg/mod/github.com/rancher/lasso@v0.0.0-20200905045615-7fcb07d6a20b/pkg/controller/sharedhandler.go:65 +0x14a
github.com/rancher/lasso/pkg/controller.(*controller).syncHandler(0xc0217ff550, 0xc02372f960, 0x16, 0xc032a4ef90, 0xc08cd33d50)
	/go/pkg/mod/github.com/rancher/lasso@v0.0.0-20200905045615-7fcb07d6a20b/pkg/controller/controller.go:210 +0xd1
github.com/rancher/lasso/pkg/controller.(*controller).processSingleItem(0xc0217ff550, 0x3a62f40, 0xc06c00af90, 0x0, 0x0)
	/go/pkg/mod/github.com/rancher/lasso@v0.0.0-20200905045615-7fcb07d6a20b/pkg/controller/controller.go:192 +0xd7
github.com/rancher/lasso/pkg/controller.(*controller).processNextWorkItem(0xc0217ff550, 0x203001)
	/go/pkg/mod/github.com/rancher/lasso@v0.0.0-20200905045615-7fcb07d6a20b/pkg/controller/controller.go:169 +0x51
github.com/rancher/lasso/pkg/controller.(*controller).runWorker(0xc0217ff550)
	/go/pkg/mod/github.com/rancher/lasso@v0.0.0-20200905045615-7fcb07d6a20b/pkg/controller/controller.go:158 +0x2b
k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0xc046e5e140)
	/go/pkg/mod/k8s.io/apimachinery@v0.20.0/pkg/util/wait/wait.go:155 +0x5f
k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0xc046e5e140, 0x4fecfa0, 0xc032a4f050, 0x1, 0xc01660ef00)
	/go/pkg/mod/k8s.io/apimachinery@v0.20.0/pkg/util/wait/wait.go:156 +0xa3
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc046e5e140, 0x3b9aca00, 0x0, 0x1, 0xc01660ef00)
	/go/pkg/mod/k8s.io/apimachinery@v0.20.0/pkg/util/wait/wait.go:133 +0x98
k8s.io/apimachinery/pkg/util/wait.Until(0xc046e5e140, 0x3b9aca00, 0xc01660ef00)
	/go/pkg/mod/k8s.io/apimachinery@v0.20.0/pkg/util/wait/wait.go:90 +0x4d
created by github.com/rancher/lasso/pkg/controller.(*controller).run
	/go/pkg/mod/github.com/rancher/lasso@v0.0.0-20200905045615-7fcb07d6a20b/pkg/controller/controller.go:129 +0x31f
```

**Expected Result:**
Rancher should not crash.

**Other details that may be helpful:**
We ran into this issue when rancher was down for a while and  after bringing it back up the cluster autoscaler had removed some nodes without rancher getting updated.  This caused rancher to start crashing as the clusters it managed where trying to connect.

It looks like syncTaint does not validate nil is not returned by nodehelper.GetNodeForMachine.  And GetNodeForMachine returns nil when a node can not be looked up if for example it was deleted from the Kubernetes cluster but not rancher.
https://github.com/rancher/rancher/blob/v2.5.7/pkg/controllers/managementuser/nodesyncer/nodetaints.go#L30-L34

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): 2.5.7
- Installation option (single install/HA): HA

**Comment by anupama2501** [comment] 2021-07-16 04:42
I'm not able to repro the issue:

Rancher server v2.5.8 

1. Created an rke1 node driver cluster with 1 etcd, 1 worker and 1 cp
2. Register another worker node in the cluster
3. Deleted the daemon set `cattle-node-agent` from cluster --> system project created above.
4. Scale down the `cattle-cluster-agent` to 0 
```
kubectl scale deployment cattle-cluster-agent --replicas=0 -n cattle-system --kubeconfig -kubecongig.yaml
```
5. Edit the cluster and a taint to the new worker node.
6. Scale up the `cattle-cluster-agent` as
```
kubectl scale deployment cattle-cluster-agent --replicas=1 -n cattle-system --kubeconfig -kubecongig.yaml
```
7. Panics mentioned are not observed in the rancher pods in local cluster


On master-head 8073489

Followed the same steps as above and didn't see panics in rancher pods.

**Comment by Jono-SUSE-Rancher** [comment] 2021-07-22 17:45
QA is unable to reproduce this issue with the PR that Dan merged. We should be fine to target this for 2.6 @anupama2501. Did you need something else for us to confirm/close it?

**Comment by anupama2501** [comment] 2021-07-27 15:05
@gregsidelinger 
Would you be able to let us know if you are still seeing this issue on master-head as I'm unable to reproduce the issue after scaling down `cattle-cluster-agent` and adding taints to the worker node and scaling back `cattle-cluster-agent` up ?

**Comment by sowmyav27** [comment] 2021-08-20 06:10
Closing this issue. We ave been unable to reproduce it. Will reopen or log a new issue if we see it.

**Closed by sowmyav27** 2021-08-20 06:10 UTC
Labels: [zube]: To Test, QA/XS, QA/need-info

**Comment by gregsidelinger** [comment] 2021-08-24 16:05
The issue does not happen in master as I submitted at patch that was merged in to address it, https://github.com/rancher/rancher/pull/33515.  So the issue is closed as far as I'm concerned.
