### ISSUE TITLE
[2.4 Backpoart] RFE: Flag to change the number of Helm Version Histories we keep for Charts deployed by Rancher

### ISSUE THREAD

**Issue by maggieliu** [rancher/rancher#28736] opened 2020-09-03 17:46 UTC
related to: https://github.com/rancher/rancher/issues/28728

**Comment by dramich** [comment] 2020-09-14 17:18
Duplicate of https://github.com/rancher/rancher/issues/28765

**Closed by dramich** 2020-09-14 17:18 UTC
Labels: [zube]: Team Blue Backlog
