### ISSUE TITLE
start_on_create: false is not reflected in stack's configuration

### ISSUE THREAD

**Issue by oddperfect** [rancher/rancher#9642] opened 2017-08-09 23:28 UTC
**Rancher versions:**
rancher/server: v1.6.2
rancher/agent: v1.2.2

**Infrastructure Stack versions:**
healthcheck: v0.3.1
ipsec: holder
network-services: 
scheduler: 
kubernetes (if applicable): NA

**Docker version: (`docker version`,`docker info` preferred)**
1.12

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
Ubuntu 16.04

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
Azure Virtual Machine

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
single node, internal DB

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle

**Steps to Reproduce:**
In Rancher UI, create a stack where you for rancher-compose you include "start_on_create: false".
After creation, click on menu for stack and click on "View Config".

**Results:**
Rancher-compose config shows "start_on_create: true". Should be "start_on_create: false".
NOTE: This affects terraform after creating a stack, it uses this rancher-compose on the next apply and this issue causes the stack to start the containers that should not be created.

**Comment by deniseschannon** [comment] 2017-08-09 23:47
Duplicate of https://github.com/rancher/rancher/issues/7287

**Closed by deniseschannon** 2017-08-09 23:47 UTC
