### ISSUE TITLE
v2.0.5 openLDAP does not bind

### ISSUE THREAD

**Issue by iwilltry42** [rancher/rancher#14456] opened 2018-07-09 09:13 UTC
**Rancher versions:**
rancher/rancher: v2.0.5

**Steps to reproduce:**
Configure OpenLDAP via UI

**Expected:**
binds correctly, TestAndApply successful

**Result:**
UI Feedback `Authentication Failed`
From the debug logs: 
```
2018/07/09 08:33:09 [DEBUG] configApplyInput &{{{ } {      0 0001-01-01 00:00:00 +0000 UTC <nil> <nil> map[] map[] [] nil [] } {{ } {      0 0001-01-01 00:00:00 +0000 UTC <nil> <nil> map[] map[] [] nil [] } openLdapConfig true unrestricted []} [someIP] 389 false  CN=abs,OU=Service Accounts,OU=Service,OU=Users,DC=xyz,DC=local supersecurepass 0 ou=Users,dc=xyz,dc=local uid|sn|givenName|sAMAccountName sAMAccountName person cn memberOf  ou=Verteilung Groups,dc=trivago,dc=local cn group cn entryDN entryDN member 5000 true} myname mypass}
2018/07/09 08:33:09 [DEBUG] Now generating Ldap token
2018/07/09 08:33:09 [DEBUG] Now creating Ldap connection
2018/07/09 08:33:09 [DEBUG] Binding username password
2018/07/09 08:33:09 [ERROR] API error response 401 for POST /v3/openLdapConfigs/openldap?action=testAndApply. Cause: LDAP Result Code 1 "Operations Error": 000004DC: LdapErr: DSID-0C090A22, comment: In order to perform this operation a successful bind must be completed on the connection., data 0, v3839
```
**Further Information:**
Configuring the same connection via Active Directory plugin, I get the following logs:
```
2018/07/09 09:01:30 [DEBUG] Now generating Ldap token
2018/07/09 09:01:30 [DEBUG] Now creating Ldap connection
2018/07/09 09:01:30 [DEBUG] Bind service account username password
2018/07/09 09:01:30 [DEBUG] Binding username password
```
Here, line 3 says `Bind service account username password` which seems to be missing before the authentication step in OpenLDAP

**Comment by dembaca** [comment] 2018-07-09 12:52
Same here: no BIND before SEARCH. Here is the log output of the OpenLDAP side:
```
Jul  9 14:33:50 ldap02 slapd[16259]: conn=1000 fd=19 ACCEPT from IP=10.4.X.X:52642 (IP=0.0.0.0:389)
Jul  9 14:33:50 ldap02 slapd[16259]: conn=1000 op=0 SRCH base="o=XXX,ou=People,dc=accounts,XXXX" scope=2 deref=0 filter="(&(objectClass=inetOrgPerson)(uid=dembaca))"
Jul  9 14:33:50 ldap02 slapd[16259]: conn=1000 op=0 SRCH attr=dn isMemberOf objectClass inetOrgPerson uid cn AccountActivated
Jul  9 14:33:50 ldap02 slapd[16259]: conn=1000 op=0 SEARCH RESULT tag=101 err=32 nentries=0 text=
Jul  9 14:33:50 ldap02 slapd[16259]: conn=1000 fd=19 closed (connection lost)
```

**Comment by carolynhu** [comment] 2018-07-09 20:24
Hi @iwilltry42, we cannot reproduce this issue. What's the info you filled here?
<img width="1249" alt="screen shot 2018-07-09 at 1 23 56 pm" src="https://user-images.githubusercontent.com/29208297/42474103-631ac218-837b-11e8-857a-fa94b8ae4d49.png">
your service account username and password?

**Comment by iwilltry42** [comment] 2018-07-09 21:43
Hi @carolynhu,
For the test and authentication fields I used my personal account details.
With and without logon domain prefix, it doesn't work.
With the same details it works using the Active Directory Plugin though.

**Comment by cjellick** [comment] 2018-07-10 21:55
We believe we got to the bottom of this issue and why we didn't catch it in QA. Utlimately, our test openldap server was allowing anonymous binds, so it was not erroring out where a typical production openldap server would. We disallowed anonymous binds in our server and where able to reproduce  the problem.

**Comment by deniseschannon** [comment] 2018-07-10 22:11
@iwilltry42 @dembaca We just released v2.0.6-rc1 if you'd like to test it out to see that it's working your openldap servers, that'd be great.

**Comment by deniseschannon** [comment] 2018-07-10 22:11
@iwilltry42 @dembaca We just released v2.0.6-rc1 if you'd like to test it out to see that it's working your openldap servers, that'd be great.

**Comment by iwilltry42** [comment] 2018-07-11 06:19
Hi there, I just tested the OpenLDAP Authentication Provider with v2.0.6-rc1 and the exact same settings as before and it works like a charm.
Thanks a lot :)

**Comment by cjellick** [comment] 2018-07-11 15:52
Re-opening so that our QA can verify as part of the v2.0.6 QA and release cycle

**Comment by cjellick** [comment] 2018-07-11 15:53
Thanks for trying it out @iwilltry42

**Comment by cjellick** [comment] 2018-07-11 15:56
Actually @deniseschannon I see now that you are closing the these user reported LDAP issues as the users verify the fix in the RCs. I'll go ahead and close this.

**Closed by cjellick** 2018-07-11 15:56 UTC
Labels: area/authentication, kind/bug, status/resolved, status/to-test, version/2.0
