### ISSUE TITLE
Service stuck in "activating" state when both the service and the service that is volume mounted expose the same ports.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#888] opened 2015-05-22 03:02 UTC
Server version - V0.21.2

Steps to reproduce the problem:

Create environment.
Create service1 with launch config - {
        "imageUuid": WEB_IMAGE_UUID,
        "labels": {'io.rancher.service.sidekick': "port-conflict"},
        "ports": ["9898:80/tcp"]}
Create service2 with launch config - 
        "imageUuid": SSH_IMAGE_UUID,
        "labels": {'io.rancher.service.sidekick': "port-conflict"},
        "ports": ["9898:20/tcp"]}
 
activate environment.

This results in both services being stuck in "activating" state forever.

Since this conflict in allocation requirement can never be resolved , API should error out.

**Comment by alena1108** [comment] 2015-05-22 04:07
Again, the same root cause as in:

https://github.com/rancherio/rancher/issues/557
https://github.com/rancherio/rancher/issues/768
https://github.com/rancherio/rancher/issues/727

When instance fails to start due to allocation error, or any other error. We just keep on retrying.

**Comment by alena1108** [comment] 2015-05-22 04:19
The situation is recoverable - user can remove the conflicting service and re-add it with non-conflicting ports. But we can def add more validation on the API side upfront.

**Comment by will-chan** [comment] 2015-05-26 21:48
Is there anyway to provide feedback to the user?

**Comment by will-chan** [comment] 2015-06-08 17:27
This should be related to the propagation of the error back to the user.

**Comment by deniseschannon** [comment] 2015-12-03 22:59
Pre-duplicate of https://github.com/rancher/rancher/issues/820

Essentially, we need better error message when service will fail to scale due to lack of open ports or invalid container info.

**Closed by deniseschannon** 2015-12-03 22:59 UTC
Labels: area/service, kind/bug
