### ISSUE TITLE
If I have a space in my catalog library name, the catalogs are broken

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#3469] opened 2016-01-29 20:27 UTC
Version - 0.57.0-rc2

Steps:
1.  Go to settings and add catalog Name = Tani Library, URL = https://github.com/tfiduccia/qa-catalog
2.  Save
3.  Go to Catalog and click on one of my catalogs

Results - First you can tell something is wrong because the images are not showing up on main catalog page.  Then if you click on one of them you get an error page.  
![image](https://cloud.githubusercontent.com/assets/11514927/12687240/db2eef22-c68b-11e5-98ce-131f17497054.png)

Expected:  We should either not allow them to put spaces in Catalog Name or fix it so it works.

**Comment by demarant** [comment] 2016-01-30 00:42
isn't this a dupe of #3124 ?

**Comment by vincent99** [comment] 2016-03-08 18:53
Yes, #3124

**Closed by vincent99** 2016-03-08 18:53 UTC
Labels: area/catalog, area/ui, kind/bug
