### ISSUE TITLE
unable to pass in HTTP proxy info when running HA environment

### ISSUE THREAD

**Issue by aemneina** [rancher/rancher#5392] opened 2016-07-11 21:26 UTC
**Rancher Version:**
1.0.2/1.1.0

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
HA specific

**Steps to Reproduce:**
Running single rancher server, one can pass in http proxy info via environmental variables. This doesnt work with rancher, preventing the fetching of the latest catalog items.

**Workaround:** 
exec into rancher-ha-cattle and add specific proxy info there. EX for git:
manually entered: 
git config --global http.proxy http://x.x.x.x
git config --global https.proxy http(s)://x.x.x.x

**Expected:**
A way to pass this through the rancher-ha.sh script?

**Comment by deniseschannon** [comment] 2016-07-12 15:58
Duplicate of https://github.com/rancher/rancher/issues/5315

**Closed by deniseschannon** 2016-07-12 15:58 UTC
Labels: area/ha, priority/-1
