### ISSUE TITLE
[BUG] RKE2/K3S registration command not working on airgap setup

### ISSUE THREAD

**Issue by rishabhmsra** [rancher/rancher#44682] opened 2024-03-06 08:36 UTC
**Rancher Server Setup**
- Rancher version: v2.8.3-rc2
- Installation option (Docker install/Helm Chart): docker airgap
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc):
- Proxy/Cert Details:

**Information about the Cluster**
- Kubernetes version: v1.28.6+rke2r1/v1.28.6+k3s2
- Cluster Type (Local/Downstream): 
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider): Custom

**User Information**
- What is the role of the user logged in? (Admin/Cluster Owner/Cluster Member/Project Owner/Project Member/Custom) Admin
  - If custom, define the set of permissions:

**Describe the bug**

- In Airgap setup RKE2 and K3s custom clusters registration command on nodes is failing with below error:
```
curl: (22) The requested URL returned error: 500 
```

**To Reproduce**

- Create v2.8.3-rc2 docker airgap setup.
- Create nodes on AWS for RKE2 or K3s custom cluster.
- SSH into bastion node and then SSH into node created for custom cluster above.
- Run the registration command and observe that it fails with `curl: (22) The requested URL returned error: 500`

**Result**
- Cluster registration command fails.

**Expected Result**

- Cluster registration command should run successfully.

**Comment by chiukapoor** [comment] 2024-03-06 12:28
## `system-agent-install.sh` Request Chronology
* The `system-agent-install.sh` file is fetched from Rancher Server by the custom node during registration in the Airgap setup.
* The request lands on the [server.go](https://github.com/rancher/rancher/blob/v2.8.3-rc2/pkg/capr/installer/server.go#L17) file in the installer package, triggering the `LinuxInstallScript` function. This, in turn, calls the `installScript` function.
* An [If condition](https://github.com/rancher/rancher/blob/v2.8.3-rc2/pkg/capr/installer/installer.go#L33) within the `installScript` function checks if `setting.Get()` is equal to `setting.Default`.
* Here `setting.Get()` is [CATTLE_SYSTEM_AGENT_INSTALL_SCRIPT](https://github.com/rancher/rancher/blob/v2.8.3-rc2/package/Dockerfile#L55) and `setting.Default` is [SystemAgentInstallScript](https://github.com/rancher/rancher/blob/v2.8.3-rc2/pkg/settings/setting.go#L99)
* Upon the success of the above `if` condition, the `system-agent-install.sh` is searched locally at `/usr/share/rancher/ui/assets/`. If the condition fails, the script is searched at the URL provided by the environment variable [CATTLE_SYSTEM_AGENT_INSTALL_SCRIPT](https://github.com/rancher/rancher/blob/v2.8.3-rc2/package/Dockerfile#L55)

## Cause of issue
* The introduction of PR #43776 removes the URL for `system-agent-install.sh` from `SystemAgentInstallScript`. [Reference diff](https://github.com/rancher/rancher/pull/43776/files#diff-b2f1f4f0c50b7452d729bccde70315eb06368408c5062c97febbe7dd6f87e2ed)
* This breaks the `if condition` [logic](https://github.com/rancher/rancher/blob/v2.8.3-rc2/pkg/capr/installer/installer.go#L35-L48) which looks for the `system-agent-install.sh` locally and is essential for registration of custom nodes in Airgap setup.

## Fix

**Comment by Oats87** [comment] 2024-03-07 13:08
@chiukapoor 

To resolve this issue in the short term, let's do this:

1. Re-add the system-agent install script asset URL to the default value in `pkg/settings/settings.go`, you are already doing that in the PR here: https://github.com/rancher/rancher/pull/44688/files
2. Enhance that PR 44688 with granular in the codebase in `pkg/settings/settings.go` with a comment to indicate why we are duplicating the value of the install script asset
3. Add a comment in the Dockerfile where we define the environment variable `CATTLE_SYSTEM_AGENT_INSTALL_SCRIPT` that indicates that the value should match the value in `pkg/settings/settings.go` to reference the local version that we download during build/package time
4. Backport/forward port the PR once approved/merged across our actively maintained release lines (2.7, 2.9)

**Comment by chiukapoor** [comment] 2024-03-07 14:42
> @chiukapoor
> 
> To resolve this issue in the short term, let's do this:
> 
> 1. Re-add the system-agent install script asset URL to the default value in `pkg/settings/settings.go`, you are already doing that in the PR here: https://github.com/rancher/rancher/pull/44688/files
> 2. Enhance that PR 44688 with granular in the codebase in `pkg/settings/settings.go` with a comment to indicate why we are duplicating the value of the install script asset
> 3. Add a comment in the Dockerfile where we define the environment variable `CATTLE_SYSTEM_AGENT_INSTALL_SCRIPT` that indicates that the value should match the value in `pkg/settings/settings.go` to reference the local version that we download during build/package time
> 4. Backport/forward port the PR once approved/merged across our actively maintained release lines (2.7, 2.9)

Will PR https://github.com/rancher/rancher/pull/44688 suffice as a fix, considering we do not need to duplicate the value of the install script asset across the codebase?

**Comment by snasovich** [comment] 2024-03-07 16:08
Thank you, @Oats87 .
@chiukapoor @rishabhmsra , FYI created https://github.com/rancher/rancher/issues/44713 / https://github.com/rancher/rancher/issues/44714 for back/forwardporting so please link back/forwardport PRs to those issues.

**Comment by Oats87** [comment] 2024-03-07 16:16
> > @chiukapoor
> > To resolve this issue in the short term, let's do this:
> > 
> > 1. Re-add the system-agent install script asset URL to the default value in `pkg/settings/settings.go`, you are already doing that in the PR here: https://github.com/rancher/rancher/pull/44688/files
> > 2. Enhance that PR 44688 with granular in the codebase in `pkg/settings/settings.go` with a comment to indicate why we are duplicating the value of the install script asset
> > 3. Add a comment in the Dockerfile where we define the environment variable `CATTLE_SYSTEM_AGENT_INSTALL_SCRIPT` that indicates that the value should match the value in `pkg/settings/settings.go` to reference the local version that we download during build/package time
> > 4. Backport/forward port the PR once approved/merged across our actively maintained release lines (2.7, 2.9)
> 
> Will PR #44687 suffice as a fix, considering we do not need to duplicate the value of the install script asset across the codebase?

I don't believe it's a satisfactory permanent fix. I would prefer we do minimal changes (i.e. revert what was changed) and then revisit the topic when we have time to thoroughly test it.

**Comment by snasovich** [comment] 2024-03-08 15:07
The workaround for this issue before the code fix is available is to set `CATTLE_SYSTEM_AGENT_INSTALL_SCRIPT` env var to empty.

**Comment by chiukapoor** [comment] 2024-03-11 06:15
- v2.8 [PR](https://github.com/rancher/rancher/pull/44688)
- v2.7 backport [PR](https://github.com/rancher/rancher/pull/44749)
- v2.9 forward port [PR](https://github.com/rancher/rancher/pull/44750)

**Comment by markusewalker** [comment] 2024-03-11 21:33
Reopening this issue as we will need to ensure proper QA validations have been handled.

**Comment by snasovich** [comment] 2024-03-13 02:21
Reopening for QA validations again, somehow it got closed again.

**Closed** 2024-03-15 07:15 UTC
Labels: kind/bug, [zube]: To Test, status/release-blocker, team/hostbusters, team/infracloud, status/to-test

**Comment by vincebrannon** [comment] 2024-03-26 08:31
> The workaround for this issue before the code fix is available is to set `CATTLE_SYSTEM_AGENT_INSTALL_SCRIPT` env var to empty.

**Please note** that the workaround listed in the issue only applies for new nodes. The issue is that the delivered system-agent-install script to the nodes (in both custom and provisioned cases) is rendered incorrectly before the workaround is applied. Once the workaround is applied, any new retrieval of the installation script will have be rendered correctly; however, notably, in the case of a provisioned cluster (where machines are created by Rancher), the data will be outdated.
