### ISSUE TITLE
Custom driver UI doesn't load

### ISSUE THREAD

**Issue by radu-stefanache** [rancher/rancher#6313] opened 2016-10-18 14:15 UTC
**Rancher Version:**
**_v1.2.0-pre4-rc2_**
**Docker Version:**
_**1.12.2**_
**OS and where are the hosts located? (cloud, bare metal, etc):**
_**CentOS 7.2.1511**_
**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
_**single node**_

**Steps to Reproduce:**
Add custom docker-machine driver via the UI.
Download URL: `https://github.com/radu-stefanache/docker-machine-driver-interoutevdc/releases/download/v0.1.5/docker-machine-driver-interoutevdc_linux-amd64.tar.gz`
Custom UI URL: `https://raw.githubusercontent.com/radu-stefanache/ui-driver-interoutevdc/v0.0.4a/dist/component.js``

I've hosted the files on a local webserver as well though that didn't help.
**Results:** 
The Custom UI does not load. If I don't provide a custom UI URL, the driver options are displayed properly but it's not what I need since the custom UI is querying an API based your selections.

Another thing to mention is the fact that while you input the driver details the focus keeps changing to the 1st text input box, the Download URL so if you want to type something in the custom UI box the prompt will jump to the 1st field/text input box.
**Expected:**
Custom UI loads (like it did in 1.1.x).

**Comment by deniseschannon** [comment] 2016-10-18 14:40
v1.2.0-pre4-rc2 is not recommended and has lists of known issues esp around machine drivers. 

If you're willing to try bleeding edge, can you try upgrading to v1.2.0-pre4-rc4 and see if you can reproduce?

**Comment by radu-stefanache** [comment] 2016-10-18 14:55
Hi Denise,

tested with ```v1.2.0-pre4-rc4``` just a minute ago and I got the same issue.
If I specify the UI url, it does not load, if I don't specify it I get the driveroptions displayed.

The focus issue still exists.

**Comment by deniseschannon** [comment] 2016-10-18 14:57
Thanks for testing it out with our latest RC.

**Comment by tfiduccia** [comment] 2016-10-19 19:15
This is two bugs.  I'm going to enter a separate bug about the typing being redirected.  The UI Url is being passed and is in the API properly, so probably not a UI bug.

**Comment by vincent99** [comment] 2016-10-19 22:00
Hosting the JS on GitHub doesn't work (and didn't in 1.1 either) because they send `Content-Type: text/plain` and `X-Content-Type-Options:nosniff`.  This makes modern browsers refuse to execute the response because it says it's text, not code.

```
Refused to execute script from 'http://a.b.c.d:8080/v2-beta/proxy/https://raw.githubusercontent.com/radu-stefanache/ui-driver-interoutevdc/v0.0.4a/dist/component.js' because its MIME type ('text/plain') is not executable, and strict MIME type checking is enabled.
```

If you like random 3rd party services, you can replace `raw.githubusercontent.com` with `cdn.rawgit.com` as they send the Content-Type the browser is looking for.

**Comment by radu-stefanache** [comment] 2016-10-20 08:25
Hello,

the raw.github was added as a pointer to the code I am using. When I am adding the driver I am hosting the content (component.js) on a local apache host.

Meanwhile I've tried the cdn.rawgit.com and the issue is the same, component.js doesn't get loaded.

**Comment by radu-stefanache** [comment] 2016-11-01 14:14
@vincent99 & @deniseschannon : Guys, I see rc6 is out and I'm facing the same issue. The UI doesn't load even if I store the content on a local apache host. Is there anything I'm missing?

Thanks!

**Comment by radu-stefanache** [comment] 2016-11-08 09:50
@vincent99 I've tested it with the master image, it loads the javascript code so I can set the driver options correctly but when trying to deploy I get this: ``` Error: No machine name specified" resourceId=1ph1```

By looking at the driver config, all the fields are correct.
![rancher-interoutevdc](https://cloud.githubusercontent.com/assets/13762415/20094340/b4197528-a598-11e6-9c39-53744fe547cb.png)

**Comment by westlywright** [comment] 2016-11-09 21:35
@radu-stefanache With the sweeping changes to the v2-beta Rancher api the types for the machine have changed. After the next Rancher UI release If you pull in the following updates from the [ui-driver-skel](https://github.com/rancher/ui-driver-skel/blob/master/component/component.js#L16-L25) repo you should be good to go. Again you'll need to wait for the next UI release cause there were a couple changes to Ranchers UI required to fix the issue fully.

 I cloned your ui repo and was able to successfully post the host config to Ranchers API. The machine did not launch on Interroute due to an error about the Zone ID not being found. This does not seem to me a Rancher UI issue though.

**Comment by radu-stefanache** [comment] 2016-11-10 09:27
@westlywright : Thanks! I will keep an eye on the UI repo. Thanks again for the help!

**Comment by radu-stefanache** [comment] 2016-11-10 16:23
@westlywright : So, I've redeployed rancher from the master branch and recompiled the ```component.js``` file.Tried a few times and I get this error:
![image](https://cloud.githubusercontent.com/assets/13762415/20184852/fdcb2426-a761-11e6-9249-a7449f10a055.png)

I will give it another try on Monday most probably but I just wanted to keep you updated!

**Comment by vincent99** [comment] 2016-11-10 17:00
This has nothing to do with the original problem anymore... The data sent to the driver is up to your UI component.  What the driver does with it is up to the driver and asynchronous, long after the UI is done.

In this case it's trying to create a SSH key pair and one with that name already exists, possibly because on previous failures it didn't clean them up.

**Comment by tfiduccia** [comment] 2016-11-10 19:47
@radu-stefanache 
Verified this works on our side, so closing issue.  You can reopen if you encounter another error.
Version - master 11/10

**Closed by tfiduccia** 2016-11-10 19:47 UTC
Labels: area/ui, kind/bug, status/resolved, status/to-test

**Comment by radu-stefanache** [comment] 2016-11-10 20:53
@tfiduccia : I believe we'll have to reopen it. I did some more tests and it looks like this:
If I deploy one instance, it works fine, no issues at all but if I deploy multiple instances I get the error I've mentioned. 

The ssh keypairs do not exist, I can assure you about it. If my understanding is correct, the ui-driver I've created sets the driver config options but the deployment is handled by rancher. I am using the docker-machine driver on other projects and works fine so I believe the issue is with rancher once you want to deploy multiple instances at the same time.

Now, more info on this just to prove my point. Here's the output from the failing call (same as in the previous screenshot):
```bash
time="2016-11-10T20:43:34Z" level=info msg="stdout: Running pre-create checks..." resourceId: =1ph7
time="2016-11-10T20:43:34Z" level=info msg="stdout: (testyzx1) Checking if SSH key pair (testyzx1) already exists..." resourceId: =1ph7
time="2016-11-10T20:43:34Z" level=info msg="stdout: Running pre-create checks..." resourceId: =1ph6
time="2016-11-10T20:43:34Z" level=info msg="stdout: (testyzx1) Checking if SSH key pair (testyzx1) already exists..." resourceId: =1ph6
time="2016-11-10T20:43:34Z" level=info msg="stdout: Running pre-create checks..." resourceId: =1ph8
time="2016-11-10T20:43:34Z" level=info msg="stdout: (testyzx1) Checking if SSH key pair (testyzx1) already exists..." resourceId: =1ph8
time="2016-11-10T20:43:34Z" level=info msg="stdout: (testyzx1) Checking if instance (testyzx1) already exists..." resourceId: =1ph7
time="2016-11-10T20:43:34Z" level=info msg="stdout: (testyzx1) Checking if instance (testyzx1) already exists..." resourceId: =1ph6
time="2016-11-10T20:43:34Z" level=info msg="stdout: (testyzx1) Checking if instance (testyzx1) already exists..." resourceId: =1ph8
time="2016-11-10T20:43:34Z" level=info msg="stdout: Creating machine..." resourceId: =1ph7
time="2016-11-10T20:43:34Z" level=info msg="stdout: Creating machine..." resourceId: =1ph6
time="2016-11-10T20:43:34Z" level=info msg="stdout: Creating machine..." resourceId: =1ph8
time="2016-11-10T20:43:34Z" level=info msg="stdout: (testyzx1) Registering SSH key pair..." resourceId: =1ph8
time="2016-11-10T20:43:35Z" level=info msg="stdout: (testyzx1) Creating Interoute VDC instance..." resourceId: =1ph8
time="2016-11-10T20:43:35Z" level=info msg="stdout: (testyzx1) Registering SSH key pair..." resourceId: =1ph6
time="2016-11-10T20:43:35Z" level=info msg="stdout: (testyzx1) Registering SSH key pair..." resourceId: =1ph7
time="2016-11-10T20:43:37Z" level=info msg="stdout: The default lines below are for a sh/bash shell, you can specify the shell you're using, with the --shell flag." resourceId: =1ph6
time="2016-11-10T20:43:37Z" level=info msg="stdout: " resourceId: =1ph6
time="2016-11-10T20:43:37Z" level=info msg="stdout: The default lines below are for a sh/bash shell, you can specify the shell you're using, with the --shell flag." resourceId: =1ph7
time="2016-11-10T20:43:37Z" level=info msg="stdout: " resourceId: =1ph7
time="2016-11-10T20:43:37Z" level=info msg="stderr: Error creating machine: Error in driver during machine creation: CloudStack API error 431 (CSExceptionErrorCode: 4350): A key pair with name 'testyzx1' already exists for this account." resourceId=1ph6
time="2016-11-10T20:43:37Z" level=info msg="starting cleanup..." machine name=testyzx1
time="2016-11-10T20:43:37Z" level=info msg="stderr: Error creating machine: Error in driver during machine creation: CloudStack API error 431 (CSExceptionErrorCode: 4350): A key pair with name 'testyzx1' already exists for this account." resourceId=1ph7
```

And here's me trying to deploy the same thing using docker-machine:
```bash
Running pre-create checks...
(testyzx1) Checking if SSH key pair (testyzx1) already exists...
Error with pre-create check: "SSH key pair (testyzx1) already exists."
```

So, if the ssh keypair exists, docker-machine exits while in our it's different.

**Comment by radu-stefanache** [comment] 2016-11-14 11:41
Full log attached.
[rancher-log.txt](https://github.com/rancher/rancher/files/589105/rancher-log.txt)

**Comment by vincent99** [comment] 2016-11-14 16:00
Those are basically the same message... Rancher 1.2.0-* ships with docker-machine built [from a particular commit in master](https://github.com/rancher/machine-package/blob/master/scripts/package#L51) to include a variety of fixes that we need that are not in 0.8.x.  The beginning part of the error is ours, and the exact formatting of the end is  probably just more verbose in almost-0.9 than 0.8. You can try that commit yourself if you want (or I presume 0.9.0-rc1 released over the weekend).

Again, the UI constructs the options map and sends them to the server.  The server executes the docker-machine binary, which runs the  unmodified downloaded driver with the options that were provided. So we cannot do anything other than display it if your driver says it failed. If you want to validate that the name is available  In advance you'd have to write code in the UI component to talk to the Cloudstack API and check for it.

**Comment by radu-stefanache** [comment] 2016-11-14 16:19
I've recompiled the docker-machine driver using the machine version that you pointed out.The results are the same, manually all works fine, rancher just fails.

Another thing I find odd is the fact that all hosts are named by Rancher ```foobar1``` so in the logs you can see that you have 3 instances (in rancher they appear as ```1ph1, 1ph2, 1ph3```) but all are named```foobar1``` and that's why the 1st one gets deployed and the other 2 fail with that error.

Does it make any sense now?

**Comment by vincent99** [comment] 2016-11-14 18:07
Yes from the log the server is being told to create 3 of the same name (`Cmd slice: [create... foobar1]`).  All of them do pre-create check and find a key with that name doesn't exist yet, then the first one to create the key wins and the other 2 fail.

You can look at the browser dev tools to see what `hostname` was sent to `POST /v2-beta/hosts`. I presume they'll all be the same, though the loop to create multiple machines is pretty straightforward (https://github.com/rancher/ui/blob/master/app/mixins/driver.js#L148-L156).

**Comment by radu-stefanache** [comment] 2016-11-15 09:23
Hi Vincent, thanks for the explanation.I'm just trying to get things straight and this hopefully my last post to this thread :-)

By using the ```ui-driver-skel``` template, the ui options map is constructed using the code in my repo but the name should be set by the Rancher UI, correct ? (hence this: https://github.com/rancher/ui-driver-skel/blob/master/component/template.hbs#L27 ).

In the previous version I would set the name ```foobar``` and drag the slider to, let's say 4, and Rancher would create ```foobar1```, ```foobar2```, ```foobar3```, ```foobar4``` . Did the behavior change in ```1.2``` ?

**Comment by vincent99** [comment] 2016-11-23 18:08
@radu-stefanache Do you have the current UI source you're trying to use up somewhere?  The source in radu-stefanache/ui-driver-interoutevdc does not appear to be updated with the changes @westlywright indicated.

Using master (or currently `1.2.0-pre4-rc12`) + your machine driver binary + a fresh copy of the skeleton (built with just `--name=interoutevdc` to make the driver name match) sends the appropriate unique hostnames for qty>1 (I put in name 'foo' and qty 3):

![image](https://cloud.githubusercontent.com/assets/753917/20573414/e2f83b24-b16c-11e6-919c-5ce79f415af0.png)

So if there's a problem, it's going to involve your code that I don't have a working copy of to look at.

**Comment by radu-stefanache** [comment] 2016-11-24 10:18
@vincent99 : I did some tests now and works fine. Thanks for the help and effort!
