### ISSUE TITLE
Bug: vSphere node provisioning results in  x509 error (Rancher 2.1.10)

### ISSUE THREAD

**Issue by patrick0057** [rancher/rancher#21306] opened 2019-07-03 14:22 UTC
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
Create a new node in a vSphere cluster and download RancherOS vmware iso from URL with private CA.

**Result:**
You get an x509 error.

**Other details that may be helpful:**
This was working in 2.1.8, tls-ca has been checked and confirmed correct for the URL in question.

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): 2.1.10
- Installation option (single install/HA): HA

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): Provider vSphere
- Machine type (cloud/VM/metal) and specifications (CPU/memory):VPS

**Comment by cjellick** [comment] 2019-07-03 16:10
Can you provide relevant logs from the rancher server? Since it's a private CA, how are you ensuring it is known/trusted?

cc @dramich

**Comment by contain-me-not** [comment] 2019-07-03 16:22
we confirmed the trust via `openssl s_client` from the rancher pod using `cacerts.pem`.

**Comment by contain-me-not** [comment] 2019-07-03 16:27
the specific error is `Error creating machine: Error in driver during machine creation: Get https://artifactory.mydomain.com/rancheros/rancheros-vmware-v1.4.3.iso: x509: certificate signed by unknown authority; Timeout waiting for ssh key`

rancher log
```
rancher-54986d986-mjrv9 rancher 2019/07/03 16:24:29 [INFO] stdout: Creating CA: /management-state/node/nodes/kube-dev-03-w2/certs/ca.pem
rancher-54986d986-mjrv9 rancher 2019/07/03 16:24:29 [INFO] stdout: Creating client certificate: /management-state/node/nodes/kube-dev-03-w2/certs/cert.pem
rancher-54986d986-mjrv9 rancher 2019/07/03 16:24:30 [INFO] stdout: Running pre-create checks...
rancher-54986d986-mjrv9 rancher 2019/07/03 16:24:33 [INFO] stdout: Creating machine...
rancher-54986d986-mjrv9 rancher 2019/07/03 16:24:33 [INFO] stdout: (kube-dev-03-w2) Image cache directory does not exist, creating it at /management-state/node/nodes/kube-dev-03-w2/cache...
rancher-54986d986-mjrv9 rancher 2019/07/03 16:24:33 [INFO] stdout: (kube-dev-03-w2) Downloading /management-state/node/nodes/kube-dev-03-w2/cache/boot2docker.iso from https://artifactory.elliottmgmt.com/artifactory/rancher-config/rancheros/rancheros-vmware-v1.4.3.iso...
rancher-54986d986-mjrv9 rancher 2019/07/03 16:24:35 [INFO] stdout: The default lines below are for a sh/bash shell, you can specify the shell you're using, with the --shell flag.
rancher-54986d986-mjrv9 rancher 2019/07/03 16:24:35 [INFO] stdout:
rancher-54986d986-mjrv9 rancher 2019/07/03 16:24:35 [INFO] Generating and uploading node config kube-dev-03-w2
rancher-54986d986-mjrv9 rancher 2019/07/03 16:24:50 [ERROR] NodeController c-92dw5/m-4789w [node-controller] failed with : Error creating machine: Error in driver during machine creation: Get https://artifactory.mydomain.com/rancheros/rancheros-vmware-v1.4.3.iso: x509: certificate signed by unknown authority
rancher-54986d986-mjrv9 rancher 2019/07/03 16:24:50 [INFO] Generating and uploading node config

```

**Comment by contain-me-not** [comment] 2019-07-03 16:28
the specific error is `Error creating machine: Error in driver during machine creation: Get https://artifactory.mydomain.com/rancheros/rancheros-vmware-v1.4.3.iso: x509: certificate signed by unknown authority; Timeout waiting for ssh key`

rancher log
```
rancher-54986d986-mjrv9 rancher 2019/07/03 16:24:29 [INFO] stdout: Creating CA: /management-state/node/nodes/kube-dev-03-w2/certs/ca.pem
rancher-54986d986-mjrv9 rancher 2019/07/03 16:24:29 [INFO] stdout: Creating client certificate: /management-state/node/nodes/kube-dev-03-w2/certs/cert.pem
rancher-54986d986-mjrv9 rancher 2019/07/03 16:24:30 [INFO] stdout: Running pre-create checks...
rancher-54986d986-mjrv9 rancher 2019/07/03 16:24:33 [INFO] stdout: Creating machine...
rancher-54986d986-mjrv9 rancher 2019/07/03 16:24:33 [INFO] stdout: (kube-dev-03-w2) Image cache directory does not exist, creating it at /management-state/node/nodes/kube-dev-03-w2/cache...
rancher-54986d986-mjrv9 rancher 2019/07/03 16:24:33 [INFO] stdout: (kube-dev-03-w2) Downloading /management-state/node/nodes/kube-dev-03-w2/cache/boot2docker.iso from https://artifactory.mydomain.com/rancheros/rancheros-vmware-v1.4.3.iso...
rancher-54986d986-mjrv9 rancher 2019/07/03 16:24:35 [INFO] stdout: The default lines below are for a sh/bash shell, you can specify the shell you're using, with the --shell flag.
rancher-54986d986-mjrv9 rancher 2019/07/03 16:24:35 [INFO] stdout:
rancher-54986d986-mjrv9 rancher 2019/07/03 16:24:35 [INFO] Generating and uploading node config kube-dev-03-w2
rancher-54986d986-mjrv9 rancher 2019/07/03 16:24:50 [ERROR] NodeController c-92dw5/m-4789w [node-controller] failed with : Error creating machine: Error in driver during machine creation: Get https://artifactory.mydomain.com/rancheros/rancheros-vmware-v1.4.3.iso: x509: certificate signed by unknown authority
rancher-54986d986-mjrv9 rancher 2019/07/03 16:24:50 [INFO] Generating and uploading node config

```

**Comment by dramich** [comment] 2019-07-03 16:38
I believe this is related to https://github.com/rancher/rancher/issues/21013 based off the logs from the server.

**Comment by contain-me-not** [comment] 2019-07-03 16:50
seems unrelated at first, but possible if `cacerts.pem` is needed, but not available in `jail`.  how do we confirm?

**Comment by awolde** [comment] 2019-07-03 18:18
Getting similar issue while tryin to spin up a cluster to a new vsphere box with self signed cert.
``` NodeController c-p7scl/m-vb5bq [node-controller] failed with : Error with pre-create check: "Post https://14.7.62.14:443/sdk: tls: failed to parse certificate from server: x509: cannot parse dnsName \"vsphere-box.\""```

**Comment by cjellick** [comment] 2019-07-16 13:52
@contain-me-not @awolde how are you getting cacerts.pem into the rancher server container?

**Comment by cjellick** [comment] 2019-07-16 13:53
Presumably, the solution to this will be to include cacert.pem (I think they are doing it like this https://rancher.com/docs/rancher/v2.x/en/installation/ha/helm-rancher/tls-secrets/) in the jail, but that could potentially be a security concern in and of itself. Need to discuss proper fix with @vincent99 and @ibuildthecloud.

**Comment by awolde** [comment] 2019-07-16 18:51
@cjellick All I did was run the docker run command to start Rancher, and try to deploy to vsphere.

**Comment by contain-me-not** [comment] 2019-07-17 11:43
rancher is air gapped so I used this to install:
```
helm template ./rancher-2.1.10.tgz --output-dir . --is-upgrade --name rancher --namespace cattle-system --set hostname=rancher-dev.my-domain.com --set ingress.tls.source=secret --set privateCA=true

kubectl apply -R -f ./rancher

kubectl -n cattle-system create secret generic tls-ca --from-file=cacerts.pem
```

**Comment by dramich** [comment] 2019-07-17 21:21
@contain-me-not Are you able to test v2.1.11 to see if this still remains? The issue I referenced above is fixed in that version.

**Comment by contain-me-not** [comment] 2019-07-22 14:55
I upgraded to v2.1.11 and am getting the same behavior.

One nuance in our Rancher installation that may or may not be relevant:
The Rancher ingress itself is using a self-signed certificate.  However, it is fronted by an f5 load balancer that provides a private CA certificate.  The rancher URL is pointing to the f5 LB and is using the private CA cert.  The web server hosting the ISO is using a certificate from the same private CA.

**Comment by bmdepesa** [comment] 2019-07-24 20:49
rancher/rancher:master-head

* Setup webserver w/ self signed certs to host rancheros-vmware.iso
* Reproduced in 2.2.5
```
2019/07/24 20:04:21 [ERROR] NodeController c-6wrpj/m-5tlt4 [node-controller] failed with : Error creating machine: Error in driver during machine creation: Get https://<host>/rancheros-vmware.iso: x509: certificate signed by unknown authority
```
* Deployed Rancher w/ additional cacerts
* Created vsphere cluster w/ iso from ssl webserver
* iso is downloaded successfully
```
2019/07/24 20:36:10 [INFO] (brandon-test1) Downloading /management-state/node/nodes/brandon-test1/cache/boot2docker.iso from https://<host>/rancheros-vmware.iso...
2019/07/24 20:36:12 [INFO] stdout: (brandon-test1) 0%!.(MISSING)..10%!.(MISSING)..20%!.(MISSING)..30%!.(MISSING)..40%!.(MISSING)..50%!.(MISSING)..60%!.(MISSING)..70%!.(MISSING)..80%!.(MISSING)..90%!.(MISSING)..100%!(NOVERB)
2019/07/24 20:36:12 [INFO] (brandon-test1) 0%!.(MISSING)..10%!.(MISSING)..20%!.(MISSING)..30%!.(MISSING)..40%!.(MISSING)..50%!.(MISSING)..60%!.(MISSING)..70%!.(MISSING)..80%!.(MISSING)..90%!.(MISSING)..100%!(NOVERB)
2019/07/24 20:36:12 [INFO] stdout: (brandon-test1) Generating SSH Keypair...
2019/07/24 20:36:12 [INFO] (brandon-test1) Generating SSH Keypair...
2019/07/24 20:36:13 [INFO] stdout: (brandon-test1) Creating VM...
```
I have an unrelated permissions issue with vsphere, once resolved and I can completely create the cluster, this will be closed.

**Comment by bmdepesa** [comment] 2019-07-29 21:41
rancher/rancher:master-head 7/29

* The iso downloads successfully, but the cluster fails to provision with error: `Error creating machine: Error running provisioning: error selecting docker: (ssh command error:`

```2019/07/29 20:17:12 [INFO] stdout: Provisioning with rancheros...
2019/07/29 20:17:12 [INFO] Provisioning with rancheros...
2019/07/29 20:17:47 [INFO] stdout: The default lines below are for a sh/bash shell, you can specify the shell you're using, with the --shell flag.
2019/07/29 20:17:47 [INFO] The default lines below are for a sh/bash shell, you can specify the shell you're using, with the --shell flag.
2019/07/29 20:17:47 [INFO] stdout:
2019/07/29 20:17:47 [INFO]
2019/07/29 20:17:47 [INFO] Generating and uploading node config brandon-vsphere1
2019/07/29 20:17:48 [ERROR] NodeController c-4qfwf/m-7rclp [node-controller] failed with : Error creating machine: Error running provisioning: error selecting docker: (ssh command error:```

The cluster is able to provision on v2.2.6

**Comment by bmdepesa** [comment] 2019-07-30 00:45
rancher/rancher:master-head 1125aa9c

The above was from an unrelated error with vsphere node template docker engine install version.

* ```docker run -v /root/state:/var/lib/rancher -d -p 80:80 -p 443:443 --restart=unless-stopped -v /root/certs/ca-additional.pem:/etc/ssl/certs/ca-additional.pem rancher/rancher:v2.1-head```
* In vsphere node template, set docker engine version to 17.0.3 to workaround docker error
* Provisioned vsphere cluster with rancheros iso coming from self-hosted webserver
* Cluster provisions successfully

**Closed by bmdepesa** 2019-07-30 00:45 UTC
Labels: [zube]: Reopened, area/certificate, area/cluster, internal, kind/bug, team/az
