### ISSUE TITLE
Storage tab is not working

### ISSUE THREAD

**Issue by andrewboss** [rancher/rancher#6370] opened 2016-10-23 03:44 UTC
*Describe your issue here*
Not able to access Storage tab under Host view. Brings up an fail page.
![snip20161023_2](https://cloud.githubusercontent.com/assets/4097432/19624014/5209c8f2-98db-11e6-94c9-949e1064346b.png)

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v1.1.4` Cattle: `v0.165.8.4` UI: `v1.1.14` |
|Access|`github` `admin`|
|Orchestration|`Cattle`|
|Route|`environments.new`|

**Comment by andrewboss** [comment] 2016-10-23 03:46
Error when accessing Storage tab
![snip20161023_3](https://cloud.githubusercontent.com/assets/4097432/19624021/b0705ba4-98db-11e6-8bad-f53615dc3f7d.png)

**Comment by deniseschannon** [comment] 2016-10-23 04:00
Duplicate of https://github.com/rancher/rancher/issues/5982

Already fixed in master.

**Closed by deniseschannon** 2016-10-23 04:00 UTC
