### ISSUE TITLE
Keycloak Group no longer shown in Project Member view

### ISSUE THREAD

**Issue by OlliL** [rancher/rancher#21080] opened 2019-06-24 12:59 UTC
Hi,

we have a Rancher 2.2.4 Setup with a SAML Connected Keycloak. In the past (maybe 2.2.3 or 2.2.2) we where able to see Keycloak Groups in the Members View of a Project. With 2.2.4 this is no longer possible. We can add the Keycloak Group as a Project Member, select the role and so on. But after the Member is added, the newly added Member is not shown in the UI. Local Users are always shown. The added Member is also working. It is just a display issue. But - without being able to see a member, I'm not able to delete it via UI as well....

Adding the Keycloak Group:

![image](https://user-images.githubusercontent.com/4688427/60020105-9cffa480-968f-11e9-8264-7ccc5a87b6a2.png)

Trying to display all Members afterwards - only one local user is shown:

![image](https://user-images.githubusercontent.com/4688427/60020178-c15b8100-968f-11e9-994c-f0cf4d539deb.png)

When calling the REST API directly, the Keycloak Group as well as the local user are shown:

```
{
	"annotations": {
		"lifecycle.cattle.io/create.cluster-prtb-sync_c-nb4mv": "true",
		"lifecycle.cattle.io/create.mgmt-auth-prtb-controller": "true"
	},
	"baseType": "projectRoleTemplateBinding",
	"created": "2019-06-17T10:44:24Z",
	"createdTS": 1560768264000,
	"creatorId": null,
	"groupId": null,
	"groupPrincipalId": null,
	"id": "p-9j9k4:creator-project-owner",
	"labels": {
		"cattle.io/creator": "norman"
	},
	"links": {
		"remove": "…/v3/projectRoleTemplateBindings/p-9j9k4:creator-project-owner",
		"self": "…/v3/projectRoleTemplateBindings/p-9j9k4:creator-project-owner",
		"update": "…/v3/projectRoleTemplateBindings/p-9j9k4:creator-project-owner"
	},
	"name": "creator-project-owner",
	"namespaceId": null,
	"projectId": "c-nb4mv:p-9j9k4",
	"roleTemplateId": "project-owner",
	"type": "projectRoleTemplateBinding",
	"userId": "u-v7cw6plf4n",
	"userPrincipalId": "local://u-v7cw6plf4n",
	"uuid": "df7e7263-90ec-11e9-9cf8-005056b5f6e5"
}, {
	"annotations": {
		"lifecycle.cattle.io/create.cluster-prtb-sync_c-nb4mv": "true",
		"lifecycle.cattle.io/create.mgmt-auth-prtb-controller": "true"
	},
	"baseType": "projectRoleTemplateBinding",
	"created": "2019-06-24T12:52:17Z",
	"createdTS": 1561380737000,
	"creatorId": "u-eniqa6cs6n",
	"groupId": null,
	"groupPrincipalId": "keycloak_group:///DevCluster1.Robots",
	"id": "p-9j9k4:prtb-snb54",
	"labels": {
		"cattle.io/creator": "norman"
	},
	"links": {
		"remove": "…/v3/projectRoleTemplateBindings/p-9j9k4:prtb-snb54",
		"self": "…/v3/projectRoleTemplateBindings/p-9j9k4:prtb-snb54",
		"update": "…/v3/projectRoleTemplateBindings/p-9j9k4:prtb-snb54"
	},
	"name": "prtb-snb54",
	"namespaceId": null,
	"projectId": "c-nb4mv:p-9j9k4",
	"roleTemplateId": "project-member",
	"type": "projectRoleTemplateBinding",
	"userId": null,
	"userPrincipalId": null,
	"uuid": "e583d733-967e-11e9-8503-005056b5aab8"
}

```

So I guess it is an UI issue that the "keycloak groups" are no longer shown....

**Comment by alena1108** [comment] 2019-06-24 20:38
@OlliL thank you for reporting the issue; we are aware of it, and will get it fixed in v2.2.5: https://github.com/rancher/rancher/issues/20825. 

Closing the issue as a duplicate of https://github.com/rancher/rancher/issues/20825

**Closed by alena1108** 2019-06-24 20:38 UTC
