### ISSUE TITLE
Upgrades consider themselves finished after first batch of containers / no batch

### ISSUE THREAD

**Issue by itslukej** [rancher/rancher#10238] opened 2017-10-29 14:04 UTC
When starting an upgrade on a service (in this case, mine has 10 containers), it will say that it's finished at 12 containers (upgraded two) or not upgrade any at all (and still say it's finished)

Reproduce steps:
1. Create a service with multiple containers (10 in my case)
2. Upgrade the service (I did 2 containers every 60 seconds)
3. Watch either:
a) The upgrade consider itself finished after ~5 seconds
b) It upgrade two containers and then say it's finished

I can also reproduce this on v1.6.10

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v1.6.8` Cattle: `v0.183.16` UI: `v1.6.23` |
|Access|`localauth` `admin`|
|Orchestration|`Cattle`|
|Route|`stacks.index`|

**Comment by tfiduccia** [comment] 2017-10-31 17:55
@itslukej - I am not able to reproduce your problem.  I created a service with scale of 10, Upgraded with:
Batch size = 2
Batch Interval = 60
Added an Environment variable foo=bar

All 10 services upgraded and only 2 at a time every 60 seconds.  Once that was done, Finish Upgrade only takes second to remove old containers (which is correct).

Can you please let me know when you upgraded, which fields did you change in the service?

**Comment by itslukej** [comment] 2017-10-31 18:01
@tfiduccia The only field I changed was the source for a rancher secret

**Comment by tfiduccia** [comment] 2017-10-31 18:21
@itslukej - I changed the source for a secret and it still doesn't seem to have a problem for me and it still is working as designed.  Here is a picture of what my upgrade page.
![image](https://user-images.githubusercontent.com/11514927/32241458-65947232-be2d-11e7-9fa9-92f3e54193e0.png)
Here is a picture of part of the service details page, after the upgrade but before finish upgrade.
![image](https://user-images.githubusercontent.com/11514927/32241521-9e024b94-be2d-11e7-8236-831566a923c5.png)

**Comment by itslukej** [comment] 2017-12-17 00:55
Hi, I'm still expriencing this, is there any more details i can give to help?

**Comment by superseb** [comment] 2018-09-10 13:34
Most likely fixed in https://github.com/rancher/rancher/issues/12084

**Closed by superseb** 2018-09-10 13:34 UTC
Labels: area/cattle, status/more-info
