### ISSUE TITLE
Rancher-Gatekeeper app fails in a hardened cluster

### ISSUE THREAD

**Issue by sgapanovich** [rancher/rancher#36846] opened 2022-03-11 01:04 UTC
**Rancher Server Setup**
- Rancher version: v2.6-head bab14a3
- Installation option (Docker install/Helm Chart): Helm
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): rke1

**Information about the Cluster**
- Kubernetes version: v1.22.6
- Cluster Type (Local/Downstream): local

**Describe the bug**

Rancher-gatekeeper chart (app) fails in a hardened cluster with gatekeeper-update-crds-hook-xxxx pod error `Error: container has runAsNonRoot and image will run as root (pod: "gatekeeper-update-crds-hook--1-dbjkr_cattle-gatekeeper-system(eceaf4c0-0724-4390-857f-83dc76e87d83)", container: crds-upgrade)`

**To Reproduce**
 
1. create a HA clutser
2. install Rancher
3. harden the cluster https://rancher.com/docs/rancher/v2.5/en/security/rancher-2.5/1.6-hardening-2.5/
4. install rancher gatekeeper app

**Screenshots**

![gatekeeper](https://user-images.githubusercontent.com/40282141/157781672-b672c9b7-dd5a-4090-8201-0abc704e6f36.jpg)

**Comment by AshleyDumaine** [comment] 2022-04-12 20:34
I was able to work around this on my hardened cluster by modifying the [rancher-gatekeeper chart](https://github.com/rancher/charts/tree/dev-v2.6/charts/rancher-gatekeeper) with this patch:
```
diff --git a/charts/rancher-gatekeeper/100.0.1+up3.6.0/templates/namespace-post-install.yaml b/charts/rancher-gatekeeper/100.0.1+up3.6.0/templates/namespace-post-install.yaml
index ca54d15a..0f27b3d6 100644
--- a/charts/rancher-gatekeeper/100.0.1+up3.6.0/templates/namespace-post-install.yaml
+++ b/charts/rancher-gatekeeper/100.0.1+up3.6.0/templates/namespace-post-install.yaml
@@ -20,6 +20,8 @@ spec:
         app: '{{ template "gatekeeper.name" . }}'
         release: '{{ .Release.Name }}'
     spec:
+      securityContext:
+        runAsUser: 1000
       restartPolicy: OnFailure
       {{- if .Values.postInstall.labelNamespace.image.pullSecrets }}
       imagePullSecrets:
diff --git a/charts/rancher-gatekeeper/100.0.1+up3.6.0/templates/upgrade-crds-hook.yaml b/charts/rancher-gatekeeper/100.0.1+up3.6.0/templates/upgrade-crds-hook.yaml
index 4331785f..c8104438 100644
--- a/charts/rancher-gatekeeper/100.0.1+up3.6.0/templates/upgrade-crds-hook.yaml
+++ b/charts/rancher-gatekeeper/100.0.1+up3.6.0/templates/upgrade-crds-hook.yaml
@@ -68,6 +68,8 @@ spec:
     metadata:
       name: gatekeeper-update-crds-hook
     spec:
+      securityContext:
+        runAsUser: 1000
       serviceAccountName: gatekeeper-admin-upgrade-crds
       restartPolicy: Never
       containers: 
```

**Comment by mitul777** [comment] 2022-07-22 04:32
**Unable to reproduce the issue. Please see details below.**

**Rancher installation details:** 2.6.6, Amazon EC2, RKE1

**Steps followed:** 

- Install hardened HA cluster
- Install OPA Gatekeeper version 100.1.0+up3.7.1 on local cluster 

**Results:**
 Gatekeeper installed successfully

**Comments:**
I see in the charts that something similar to the suggested workaround https://github.com/rancher/rancher/issues/36846#issuecomment-1097190831 is already present in the newer versions of the charts. Most likely came from the upstream charts. So please retest and advise if the issue still persists

**Comment by rishabhmsra** [comment] 2022-07-28 12:18
Validated on rancher v2.6.7-rc3 and unable to reproduce the error:

Steps followed:
- Created a hardened HA setup(3 nodes all roles) with local cluster -> RKE1 k8s v1.24
- Installed OPA gatekeeper chart `100.2.0+up3.8.1` on local cluster.

Result:
- Chart installed successfully, hence closing the issue.

**Closed by rishabhmsra** 2022-07-28 12:18 UTC
Labels: kind/bug, [zube]: QA Working, team/area3, feature/charts-opa-gatekeeper, team/infracloud
