### ISSUE TITLE
Deploying kubernetes environment from local repository fails.

### ISSUE THREAD

**Issue by omegarus** [rancher/rancher#6406] opened 2016-10-27 09:47 UTC
**Rancher Version:**
v1.2.0-pre4-rc5
**Docker Version:**
1.11.2
**OS and where are the hosts located? (cloud, bare metal, etc):**
Ubuntu 14.04/VMware
**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
Single node with one host.
**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Kubernetes 1.4 infra-catalog qa branch.
**Steps to Reproduce:**
I'am  trying to deploy kubernetes environment completely offline.
I save/load all images necessary to run ranche + kubernetes to my local registry. Also cloned infra-catalog to local git server and set url with DEFAULT_CATTLE_CATALOG_URL env. Changed image tags in docker-compose.yaml to the local ones.
Like this for example:

```
data:
    image: local-registry.local:5000/busybox
    entrypoint: /bin/true
    net: none
    volumes:
    - /data
    labels:
        io.rancher.container.start_once: 'true'
```

local-registry.local:5000 added to infrastructure ---> registries in this environment.
**Results:** 
rancher server error log:

```
2016-10-27 09:19:44,224 ERROR [a577f365-aaa1-4140-8106-9ec372cca4c3:3937] [instance:182->instanceHostMap:176] [instance.start->(InstanceStart)->instancehostmap.activate] [] [utorService-125] [c.p.e.p.i.DefaultProcessInstanceImpl] Agent error for [compute.instance.activate.reply;agent=1]: InstanceActivate: failed to activate instance: DoInstanceActivate: failed to create container: CreateContainer: failed to create container: Error response from daemon: Error parsing reference: "local-registry.local:5000/busybox:latest:latest" is not a valid repository/tag
2016-10-27 09:19:44,224 ERROR [a577f365-aaa1-4140-8106-9ec372cca4c3:3937] [instance:182] [instance.start->(InstanceStart)] [] [utorService-125] [i.c.p.process.instance.InstanceStart] Failed to Starting for instance [182]
2016-10-27 09:19:44,226 ERROR [a577f365-aaa1-4140-8106-9ec372cca4c3:3937] [instance:182] [instance.start] [] [utorService-125] [c.p.e.p.i.DefaultProcessInstanceImpl] Agent error for [compute.instance.activate.reply;agent=1]: InstanceActivate: failed to activate instance: DoInstanceActivate: failed to create container: CreateContainer: failed to create container: Error response from daemon: Error parsing reference: "local-registry.local:5000/busybox:latest:latest" is not a valid repository/tag
2016-10-27 09:19:44,234 ERROR [:] [] [] [] [utorService-125] [i.c.p.e.e.i.ProcessEventListenerImpl] Agent error for [compute.instance.activate.reply;agent=1]: InstanceActivate: failed to activate instance: DoInstanceActivate: failed to create container: CreateContainer: failed to create container: Error response from daemon: Error parsing reference: "local-registry.local:5000/busybox:latest:latest" is not a valid repository/tag
```

Looks like a parsing problem.
On rancher v 1.1.4 everything works as expected.

**Expected:**
Kubernetes environment to deploy without a problems.

**Comment by deniseschannon** [comment] 2016-10-27 17:09
Can you do a simple test on whether or not regular services can be launched from this registry (outside of the kubernetes stack)?

I am trying to isolate if it's a registry issue.

**Comment by omegarus** [comment] 2016-10-30 07:21
If i do Infrastructure ---> Containers ---> Add container
Select Image: local-registry.local:5000/mysql:latest
Got same error in logs:
```
2016-10-30 07:14:33,438 ERROR [be4bec5e-c0d1-4dea-9237-9c05d270aec0:22242] [instance:727] [instance.start] [] [ServiceReplay-1] [c.p.e.p.i.DefaultProcessInstanceImpl] Agent error for [compute.instance.activate.reply;agent=1]: InstanceActivate: failed to activate instance: DoInstanceActivate: failed to create container: CreateContainer: failed to create container: Error response from daemon: Error parsing reference: "local-registry.local:5000/mysql:latest:latest" is not a valid repository/tag
2016-10-30 07:14:33,459 ERROR [:] [] [] [] [ServiceReplay-1] [i.c.p.e.e.i.ProcessEventListenerImpl] Agent error for [compute.instance.activate.reply;agent=1]: InstanceActivate: failed to activate instance: DoInstanceActivate: failed to create container: CreateContainer: failed to create container: Error response from daemon: Error parsing reference: "local-registry.local:5000/mysql:latest:latest" is not a valid repository/tag

```
docker pull local-registry.local:5000/mysql:latest
on same host working as expected.

**Comment by MaxVoronov** [comment] 2016-10-31 22:38
Hi @deniseschannon,
I also have same problem. Here is my case:

**Rancher Version:**
v1.2.0-pre4-rc4
**Docker Version:**
1.12.2, build bb80604
**OS and where are the hosts located? (cloud, bare metal, etc):**
Ubuntu 16.04.1 LTS (with KVM)
**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
Single node, internal DB
**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle
**Steps to Reproduce:**
We are using latest GitLab version as docker registry and it added to _Infrastructure_ > _Registries_ . For test I set only one container:
```
version: '2'
services:
  nginx:
    container_name: nginx
    image: local-registry.example.com:8889/project/stack:nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - /var/www/current:/usr/share/nginx/html
    command: nginx -g daemon off;
```
**Result:**
Rancher error:
`Removing bad service instance: InstanceActivate: failed to activate instance: DoInstanceActivate: failed to create container: CreateContainer: failed to create container: Error response from daemon: Error parsing reference: "local-registry.example.com:8889/project/stack:nginx:latest" is not a valid repository/tag`

**Expected:**
Works fine if I run docker-compose manually.

**Comment by alena1108** [comment] 2016-11-01 19:01
@mrajashree given it is happening not only on k8s, but also on cattle, can you check if there is a bug in a way we validate the image for private repos?

**Comment by deniseschannon** [comment] 2016-11-01 19:22
@StrongMonkey Can you check, but I believe this was fixed with https://github.com/rancher/cattle/pull/2101.

I think it's a duplicate of https://github.com/rancher/rancher/issues/6311

**Comment by StrongMonkey** [comment] 2016-11-01 19:25
confirmed it is a duplicated of #6311.

**Comment by StrongMonkey** [comment] 2016-11-01 22:31
appears to be a bug in agent. Reopen to track it until agent PR is merged.

**Comment by soumyalj** [comment] 2016-11-11 18:50
Verified with v1.2.0-pre4-rc7. Created a local registry ```localhost:5000``` and pushed an ubuntu image to this registry on host1. On host2, configured --insecure-registry ipaddress of host1:5000.
Created a container on host2 using image ```ipaddress:5000/ubuntu ```successfully.

**Closed by soumyalj** 2016-11-11 18:50 UTC
Labels: kind/bug, status/resolved, status/to-test
