### ISSUE TITLE
Add SSL certificate wrongly giving invalid private key

### ISSUE THREAD

**Issue by marufbd** [rancher/rancher#13315] opened 2018-05-06 10:11 UTC
**Rancher versions:**
rancher/server or rancher/rancher: 2.0.0

Same private key in project-> resources-> certificates-> add new works on version 2.0.0-beta3.

But on stable release version 2.0.0 it says invalid private RSA key.

I am running rancher with this:
`sudo docker run -d --restart=unless-stopped -p 80:80 -p 443:443 rancher/rancher --acme-domain my_domain`

whereas on this version same private key works
`sudo docker run -d --restart=unless-stopped -p 80:80 -p 443:443 rancher/server:preview`

**Comment by superseb** [comment] 2018-05-06 11:44
Duplicate of https://github.com/rancher/rancher/issues/13156, can be added via the API as workaround.

**Closed by superseb** 2018-05-06 11:44 UTC
