### ISSUE TITLE
[cli] Unauthorized action [401] with command catalog & ssh

### ISSUE THREAD

**Issue by Kamaradeivanov** [rancher/rancher#5639] opened 2016-08-05 14:40 UTC
**Rancher Version:**
Rancher-server : 1.1.2
Rancher-cli : 0.0.1

**Docker Version:**
1.12.0

**OS and where are the hosts located? (cloud, bare metal, etc):**
Ubuntu16.4 on OpenStack Mitaka

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle

**Steps to Reproduce:**
Execute the Rancher CLI:
`rancher --url http://rancher.test8080/v1 --access-key XXXXXXXXXXXXXXX --secret-key XXXXXXXXXXXX catalog`
`rancher --url http://rancher.test8080/v1 --access-key XXXXXXXXXXXXXXX --secret-key XXXXXXXXXXXX ssh node1`

**Results:** 
I got respectively : 
`FATA[0001] Bad response statusCode [401]. Status [401 Unauthorized]. Body: [code=Unauthorized, message=Unauthorized] from [http://rancher.test:8080/v1-catalog/schemas]`
`FATA[0001] {"id":"XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX","type":"error","links":{},"actions":{},"status":401,"code":"Unauthorized","message":"Unauthorized","detail":null}`

**Expected:**
All others command work with my access/secret  key.
I can create host on OpensStack Mitaka, export config of existing Stack/Service, run a service.
Maybe catalog and ssh commands doesn't take credential values.

**Comment by deniseschannon** [comment] 2016-08-25 22:59
@Kamaradeivanov Can you try again with v0.1.0 and can you tell me what kind of access key that you have? Is it an environment one or account one?

**Comment by Jazb** [comment] 2016-09-02 01:01
I'm with version 0.1.0-RC3, and get the same error as mentioned with the version v1.1.3 of rancher.
I've used both the user keys, such as the environment and there is no variation in error

**Comment by deniseschannon** [comment] 2016-09-02 21:36
I am able to use CLI v0.1.0 with v1.1.3 of Rancher using either environment API keys or account API keys. 

Does your setup have authentication turned on?

**Comment by Jazb** [comment] 2016-09-02 22:01
Yes,  I have with local authentication

**Comment by Jazb** [comment] 2016-09-05 01:04
I am using a racher provider OpenStack Public Cloud

rancher host create -d openstack --openstack-username linets-exp --openstack-password PASSWORD--openstack-tenant-name USER --openstack-auth-url https://cloud.exampple.com:5000/v2.0 --openstack-flavor-name beebop.medium --openstack-image-id 1c72972c-36fa-446d-9207-34758eca651c --openstack-net-name linets-exp_net --openstack-floatingip-pool "IPv4" --openstack-ssh-user coreos --openstack-sec-groups default,manage

This create the VM Perfecte, but to do rancher ssh $machine, the response it is a 401 unautorized

**Comment by Kamaradeivanov** [comment] 2016-09-05 09:31
Hi, 
Like Jazb, the problem is still here with Rancher-CLI v0.1.0 and Rancher-server 1.1.2 when using both api : Account & Environment API Keys.

**Comment by danbruder** [comment] 2016-09-14 14:16
I have the same issue with Rancher CLI v0.1.0-rc3 and Rancher Server 1.1.3

**Comment by Kamaradeivanov** [comment] 2016-09-29 13:00
Hi,
Just to say that I also have this problem with hosts deployed with Rancher CLI v0.1.0 on Rancher Server 1.1.3. I have used both openstack and the generic machine-driver to deploy hosts.

**Comment by deniseschannon** [comment] 2016-11-10 00:52
Do you guys have github authentication on? I'm wondering if your issue is related to this one:

https://github.com/rancher/rancher/issues/6568

**Comment by deniseschannon** [comment] 2016-11-15 18:33
@Kamaradeivanov @Jazb @danbruder Do you have Github on?

**Comment by Kamaradeivanov** [comment] 2016-11-16 12:05
Hi Denise,
Sorry for the delay and no we dont use git, we are actualy using a local authentication

**Comment by danbruder** [comment] 2016-11-22 17:44
I'm not using github either.

**Comment by deniseschannon** [comment] 2016-11-30 23:10
Verified fixed with Rancher CLI v0.4.0-rc1, and rancher in v1.2.0-rc2.

`rancher catalog` is duplicate of https://github.com/rancher/rancher/issues/6367. Fixed in v0.4.0-rc1. 

`rancher ssh host` is now working but you can only ssh in hosts created with docker-machine

**Closed by deniseschannon** 2016-11-30 23:10 UTC
Labels: area/cli
