### ISSUE TITLE
Drain: Do not retry on timeout exceeded failure.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#15550] opened 2018-09-12 18:52 UTC
**Rancher versions:** Latest build from master

**Steps to Reproduce:**

Scenario 1:
Drain a node without enabling option - " Even if there are DaemonSet-managed pods." 

We see the drain action being attempted multiple times.

<img width="1266" alt="screen shot 2018-09-12 at 11 38 44 am" src="https://user-images.githubusercontent.com/4266958/45445918-7a604a00-b680-11e8-9c54-39f682cf183d.png">

```
2018/09/12 18:39:18 [ERROR] nodeDrain: [santestw1] in cluster [c-llcc5] : 
 santestw1
error: DaemonSet-managed pods (use --ignore-daemonsets to ignore): cattle-node-agent-j8tcf, nginx-ingress-controller-zrqfx, canal-zr42p
 <nil>
2018/09/12 18:39:19 [ERROR] nodeDrain: [santestw1] in cluster [c-llcc5] : 
 santestw1
error: DaemonSet-managed pods (use --ignore-daemonsets to ignore): cattle-node-agent-j8tcf, nginx-ingress-controller-zrqfx, canal-zr42p
 <nil>
2018/09/12 18:39:20 [ERROR] nodeDrain: [santestw1] in cluster [c-llcc5] : 
 santestw1
error: DaemonSet-managed pods (use --ignore-daemonsets to ignore): cattle-node-agent-j8tcf, nginx-ingress-controller-zrqfx, canal-zr42p
 <nil>
2018/09/12 18:39:21 [ERROR] nodeDrain: [santestw1] in cluster [c-llcc5] : 
 santestw1
error: DaemonSet-managed pods (use --ignore-daemonsets to ignore): cattle-node-agent-j8tcf, nginx-ingress-controller-zrqfx, canal-zr42p
 <nil>
2018/09/12 18:39:22 [ERROR] nodeDrain: [santestw1] in cluster [c-llcc5] : 
 santestw1
error: DaemonSet-managed pods (use --ignore-daemonsets to ignore): cattle-node-agent-j8tcf, nginx-ingress-controller-zrqfx, canal-zr42p
 <nil>
2018/09/12 18:39:23 [ERROR] nodeDrain: [santestw1] in cluster [c-llcc5] : 
 santestw1
error: DaemonSet-managed pods (use --ignore-daemonsets to ignore): cattle-node-agent-j8tcf, nginx-ingress-controller-zrqfx, canal-zr42p
 <nil>
2018/09/12 18:39:23 [ERROR] nodeDrain: [santestw1] in cluster [c-llcc5] : 
 santestw1
error: DaemonSet-managed pods (use --ignore-daemonsets to ignore): cattle-node-agent-j8tcf, nginx-ingress-controller-zrqfx, canal-zr42p
 <nil>
```
Scenario 2:
Drain a node by changing the timeout to a very small value (say 5 secs) so that it cannot complete the drain action.
We see the drain action being attempted multiple times.

In this case , we would ideally want the drain to stop once it hits these errors for the first time:

```


2018/09/12 18:23:58 [ERROR] nodeDrain: [santestw2] in cluster [c-llcc5] : pod/kube-dns-7588d5b5f5-xkhl5

 santestw2
error: Drain did not complete within 5s
 Operation cannot be fulfilled on nodes.management.cattle.io "m-brhmb": the object has been modified; please apply your changes to the latest version and try again
2018/09/12 18:24:04 [ERROR] nodeDrain: [santestw2] in cluster [c-llcc5] : pod/kube-dns-7588d5b5f5-xkhl5

 santestw2
error: Drain did not complete within 5s
 <nil>
2018/09/12 18:24:11 [ERROR] nodeDrain: [santestw2] in cluster [c-llcc5] : pod/kube-dns-7588d5b5f5-xkhl5

 santestw2
error: Drain did not complete within 5s
 <nil>
```

**Comment by sangeethah** [comment] 2018-09-14 17:38
Tested with latest build from master:

Scenario 1:
Drain a node without enabling option - "Even if there are DaemonSet-managed pods."
Drain action is attempted once and reports failure.

<img width="1057" alt="screen shot 2018-09-14 at 9 32 08 am" src="https://user-images.githubusercontent.com/4266958/45563070-131dd380-b801-11e8-88e5-0ca50ca41048.png">

Scenario 2:
Drain a node by changing the timeout to a very small value (say 5 secs) so that it cannot complete the drain action.
I am presented with the following message:

<img width="1037" alt="screen shot 2018-09-14 at 10 01 38 am" src="https://user-images.githubusercontent.com/4266958/45564427-3e0a2680-b805-11e8-9f67-71c5b15e20d6.png">


But drain seems to get attempted anyways and gets completed .
We expect the Drain to not get attempted after this 1 failure.

**Comment by kinarashah** [comment] 2018-09-17 14:37
@alena1108 @sangeethah Related to timeout issue, I have confirmed we don't attempt drain more than once, looks like there's a bug in kubectl code. It'd be fixed in 1.12. 
https://github.com/kubernetes/kubernetes/pull/64378

**Comment by alena1108** [comment] 2018-09-17 16:33
@sangeethah @kinarashah just to summarize - we fixed to not retry drain when timeout is hit, on our side. But there seems to be an issue on k8s side that even when drain times out, the pods continue being evicted. That bug is fixed in k8s 1.12. Marking the issue as has dependency, and we'll have to either document it, or hide the timeout option from the UI

**Closed** 2019-04-09 00:16 UTC
Labels: kind/bug, status/autoclosed, status/has-dependency, status/reopened, team/ca
