### ISSUE TITLE
Add restrictions on system stacks based on roles

### ISSUE THREAD

**Issue by sshipway** [rancher/rancher#4807] opened 2016-05-16 01:24 UTC
**Rancher Version:** 1.1.0-dev1

It should be made possible to move a stack between the Normal and System pages.  

This function should probably be available to Owners and possibly Members only - but not Restricted Members.  Maybe an additional menu item in the Stack menu under 'Edit'?

System stacks should also be protected in some way, EG make them read-only for Restricted Members

**Comment by deniseschannon** [comment] 2016-05-17 18:33
Requesting the ability to make a stack into a system stack is a duplicate of this request. 

https://github.com/rancher/rancher/issues/3577

But making system stacks protected/restricted access is a different enhancement.

**Comment by deniseschannon** [comment] 2018-08-22 04:37
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.

**Closed by deniseschannon** 2018-08-22 04:37 UTC
Labels: area/access-control, kind/enhancement, status/autoclosed
