### ISSUE TITLE
[BUG] Rancher cli kubectl token login fails randomly when kubeconfig-generate-token=false

### ISSUE THREAD

**Issue by samjustus** [rancher/rancher#40857] opened 2023-03-13 16:55 UTC
**Rancher Server Setup**
Rancher version: [2.6.9](https://suse.lightning.force.com/lightning/r/a1T5q0000004CRMEA2/view)
Number of nodes: 3
Node OS version: RHEL7

**Describe the bug**
Rancher cli kubectl token login fails randomly when kubeconfig-generate-token=false
The customer is unable to provide logs due to their company's security policy
Set `LOGLEVEL=debug` on the RMS and attempted reproduction steps but did not find any outstanding errors related to this issue.

**To Reproduce**

(more detailed steps in Jira comments)

Set 'kubeconfig-generate-token=false' on the Rancher Management Server
Delete the current `~/.rancher/cli2.json` config file
Attempt to authenticate to the RMS using `rancher login https://<RANCHER_SERVER_URL> -t my-secret-token`{}
Intermittently receive the following error until authentication succeeds:
"FATA[0017] error logging in: code: [ServerError] message:[Failed to create cluster auth token for cluster [c-m-f6z6hsf5], cluster auth endpoint may fail: timed out waiting for the condition]"

**Result**
Attempts to authenticate to the RMS using the Rancher CLI intermittently result in the following error:

"FATA[0017] error logging in: code: [ServerError] message:[Failed to create cluster auth token for cluster [c-m-f6z6hsf5], cluster auth endpoint may fail: timed out waiting for the condition]"

**Expected Result**
Attempts to authenticate to the RMS using the Rancher CLI should succeed consistently

**Additional context**
See attached strace files taken on the client using the Rancher CLI 
SURE-5802
SURE-5796 (related)

**Comment by PennyScissors** [comment] 2023-08-29 17:35
Posting the PR template for QA here as this issue was fixed in 2.7-head already, and we couldn't find a PR associated with the fix.

## Testing

1. Create a Rancher 2.7.7-rcX cluster
2. Enable OpenLDAP in it
3. Create a downstream RKE2 cluster (Make sure to enable Authorized Endpoint under the Networking tab)
4. Set "kubeconfig-generate-token" to false in global settings (go to https://<rancher-server-url>/v3/settings/kubeconfig-generate-token hit edit, set the value to false and send the request to update it)
5. Download the downstream cluster's kubeconfig and verify it by running and kubectl command. It will prompt you to input your auth provider. Select ldap.
6. Delete the cli configuration located in "~/.rancher/cli2.json"
7. Attempt to run another kubectl command

### Regressions Considerations

Trying this on other providers other than LDAP (what was used in original issue on JIRA) might be good

**Comment by edwin-bruurs** [comment] 2023-10-12 11:45
Any updates on this? We see the same behaviour in our environment using the same configuration as mentioned above, except that we use Rancher version 2.7.6 with kubeconfig-generate-token=true.

I'm willing to share more information if needed.

**Comment by prachidamle** [comment] 2023-10-17 18:20
@PennyScissors has found that this issue was reproducible only prior to this https://github.com/rancher/rancher/pull/42062 getting merged.

**Comment by sowmyav27** [comment] 2023-10-17 18:56
@ronhorton Can we test the original issue using these versions
1. Rancher v2.7.5 using CLI 2.7.0
2. Rancher v2.7.9(RC) using CLI 2.7.7
3. Rancher v2.8.0-RC1 using CLI v2.8.0-rc2

**Comment by ronhorton** [comment] 2023-10-23 21:26
**Rancher v2.7.5 using CLI 2.7.0:**         `error - FATA[0000] failed to parse kubeconfig token when issuing kubectl commands via CLI; login works`

**Rancher v2.7.9(RC) using CLI 2.7.7-rc2:**  `no error`

**Rancher v2.8.0-RC1 using CLI 2.8.0-rc2:** `no error`

Test Steps:
1. created downstream cluster rke2
2. enabled openldap
3. created project and added testuser2 as project member
4. logged in successfully as testuser2 (from CLI)
5. listed projects as user

**Comment by MKlimuszka** [comment] 2023-11-16 21:32
Closing as cannot reproduce.

**Closed by MKlimuszka** 2023-11-16 21:32 UTC
Labels: kind/bug, team/area1, team/area3, JIRA
