### ISSUE TITLE
[BUG] GUID un migration script is stuck in running which makes nested users unable to login

### ISSUE THREAD

**Issue by anupama2501** [rancher/rancher#42612] opened 2023-08-31 19:34 UTC
**Rancher Server Setup**
- Rancher version: `v2.7.4` >> `v2.7.5` >> `v2.7-head e056631`
- Installation option (Docker install/Helm Chart): Docker install
   - If Helm Chart, Kubernetes Info: k3s
         Cluster Type (RKE1, RKE2, k3s, EKS, etc):
         Node Setup: 1 node 
         Version: `v1.26.4+k3s1`
- Proxy/Cert Details: `self-signed`

**Information about the Cluster**
- Kubernetes version: 
- Cluster Type (Local/Downstream): `Downstream infrastructure provider 1 worker, 1 etcd + cp`
`k3s`

**Describe the bug**
Nested users post migration are not able to login. The status of the config map is stuck on Running and not updated. This happened only once on an upgrade from v2.7.4 >> v2.7.5 >> v2.7-head and not seen happening on an upgrade from v2.7.4 >> v2.7.5 >> v2.7.6. 

**To Reproduce**

1. Deploy Rancher 2.7.4
2. Enable AD Auth
3. Add user3[nested user] as Cluster owner
4. Login as user3 and Verify as cluster owner you can add another user as cluster member to the cluster.
5. Download kubeconfig as user3 and Verify kubeconfig can be used to run kubectl commands successfully on the cluster
6. provide user1 permissions to be project members
7. Upgrade Rancher to 2.7.5
8. Confirm that user3 cannot login
9. Upgrade Rancher to 2.7-head

**Result**
Unable to login as nested users post upgrade and the config map has the status `Running`. 

**Expected Result**
Expected the migration to finish and the users to be able to login.

**Additional context**

- Happened only once and not seen again. 1 out of 5 times. Below are the results:
- Not noticed for non nested users/ non nested groups
- Not noticed for nested groups
- Seen for nested users once out of 3 times
Some error logs:
```
2023/08/31 16:27:58 [DEBUG] LDAP Refetch principals base DN : {093aabc0dea08d4a95a40464f9f4808b}
2023/08/31 16:27:58 [ERROR] Error refreshing token principals, skipping: LDAP Result Code 34 "Invalid DN Syntax": 0000208F: NameErr: DSID-03100225, problem 2006 (BAD_NAME), data 8350, best match of:
	'093aabc0dea08d4a95a40464f9f4808b'
```
Config map details:
```
k describe cm ad-guid-migration -n cattle-system
Name:         ad-guid-migration
Namespace:    cattle-system
Labels:       cattle.io/creator=norman
Annotations:  <none>

Data
====
ad-guid-migration-status:
----
Running
statusLastUpdated:
----
2023-08-31T00:31:51Z

BinaryData
====

Events:  <none>
```

Only 1 user's GUID has been converted to DN and rest all users still have GUID:
```
  - activedirectory_user://a00f7304a4c4ba41ad0879aaaa90a9fc
  - activedirectory_user://4e30351df2e5e54d8189c01477f2eda2
  - activedirectory_user://ed3db1541347114888291bd40433d205
  - activedirectory_user://a00f7304a4c4ba41ad0879aaaa90a9fc
  - activedirectory_user://093aabc0dea08d4a95a40464f9f4808b
  - activedirectory_user://CN=duser2,OU=redacted
  - activedirectory_user://093aabc0dea08d4a95a40464f9f4808b
  - activedirectory_user://ed3db1541347114888291bd40433d205
```

**Comment by nflynt** [comment] 2023-08-31 19:36
It's very strange that the migration script seems to have not logged anything to the rancher pod, as usually we'd expect to at least see some info logs indicating that the migration has begun. If we're positive the script is no longer running (to be sure of this: restart Rancher once), then to troubleshoot:

1. Remove the `ad-guid-migration` configmap, so that it no longer has "Running" status
2. Either restart rancher, or run the unmigration script manually to try again.

**Comment by prachidamle** [comment] 2023-09-05 18:49
@anupama2501 are we able to reproduce this for nested users always?

**Comment by anupama2501** [comment] 2023-09-05 21:01
Hi @prachidamle I was only able to reproduce this once out of 5 times but not always. Attempted with nested and non nested users and groups. Added the details in the ticket for the same.

**Comment by crobby** [comment] 2023-09-08 18:15
It's unclear based on the logs of how this situation came up (insufficient information outside of debug logs), but it was resolved by doing the following steps:
1) kubectl delete configmap -n cattle-system ad-guid-migration
2) Restart the Rancher container
After doing those steps, the migration ran successfully.

**Comment by prachidamle** [comment] 2023-09-12 18:31
This could not be reproduced again and root cause is  unclear, moving it to next 2.7 milestone.

**Comment by MKlimuszka** [comment] 2023-11-01 21:22
Closing since we haven't seen it again. @anupama2501 , reopen if you reproduce this.

**Closed by MKlimuszka** 2023-11-01 21:22 UTC
Labels: kind/bug, kind/bug-qa, [zube]: Next Up, team/area3
