### ISSUE TITLE
test_virtual_machine.py's test_virtual_machine_case_sensitivity fails on H2 database

### ISSUE THREAD

**Issue by cjellick** [rancher/rancher#3331] opened 2016-01-19 20:59 UTC

**Comment by alena1108** [comment] 2016-03-15 22:32
@cjellick I can't reproduce it on the latest (release 63). The test runs fine for me locally on H2. Could you retry and see if the issue persists for you?

**Comment by cjellick** [comment] 2016-03-17 15:56
@alena1108 this was failing very obviously in cattle builds. I believe @ibuildthecloud fixed it. I'd like to just close. You good with that?

**Comment by alena1108** [comment] 2016-03-17 16:33
sure, closing

**Closed by alena1108** 2016-03-17 16:33 UTC
Labels: kind/bug, status/to-test
