### ISSUE TITLE
V2.1.6 upgrade to v2.2.1 failed，unable to recognize "management-statefile_path_redacted"

### ISSUE THREAD

**Issue by cjellick** [rancher/rancher#19273] opened 2019-03-29 17:24 UTC
see https://forums.rancher.com/t/v2-1-6-upgrade-to-v2-2-1-failed-unable-to-recognize-management-statefile-path-redacted/13790

**Comment by sangeethah** [comment] 2019-03-29 23:17
@galal-hussein , we have seen  similar issue when upgrading rancher-server from 2.1.6->2.2.0 which is tracked in https://github.com/rancher/rancher/issues/19059 . In this case this error seen was temporary and the cluster was able to recover automatically from this state  within the next few minutes.

**Comment by MightyDjinn** [comment] 2019-03-31 00:57
I saw this error as well, but for us it turned out to be a blip in dns resolution.

**Comment by sowmyav27** [comment] 2019-04-01 17:44
tried to reproduce this issue.
Verified on an upgrade setup from `v2.1.6` to `v2.2.1`.
Steps taken:
1. On rancher v2.1.6, a HA setup, created a cluster with 3 nodes(all roles) type - hosted-Amazon EC2.
2. Upgraded to rancher:v2.2.1.

Observations:
1. Cluster went to `Unavailable` state.
2. It changed to `Provisioning` state with the below error message. This was for a couple of seconds.
<img width="1551" alt="Screen Shot 2019-04-01 at 10 06 54 AM" src="https://user-images.githubusercontent.com/26032343/55348018-127e1f00-546b-11e9-90bf-900a9f7e9ded.png">

3. It transitioned to `Unavailable` state and finally to `Active` state after few seconds.

**Comment by alena1108** [comment] 2019-04-01 21:34
Closing as a duplicate of https://github.com/rancher/rancher/issues/19273

**Closed by alena1108** 2019-04-01 21:34 UTC
Labels: kind/bug, status/to-reproduce, team/ca, version/2.0
