### ISSUE TITLE
Airgapped Windows worker nodes in RKE2 clusters are not able to successfully provision

### ISSUE THREAD

**Issue by rosskirkpat** [rancher/rancher#37695] opened 2022-05-11 18:59 UTC
**Rancher Server Setup**
- Rancher version: v2.6.5
- Installation option (Docker install/Helm Chart): any
- Proxy/Cert Details: Rancher is airgapped using a publicly untrusted certificate (either self-signed or signed by a private CA)

**Information about the Cluster**
- Kubernetes version: RKE2 v1.22/v1.23
- Cluster Type (Local/Downstream): downstream
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider): custom or vsphere node driver

- Please describe a brief synopsis of the issue and outcome.

When Rancher is airgapped, Windows worker nodes in RKE2 clusters will not be able to successfully provision. This issue occurs when a custom CA certificate is required when making calls in Go on Windows when a restconfig needs to be built and it requires a custom CA certificate, which is part of the system-agent installation flow for RKE2 Windows. 

https://github.com/kubernetes/client-go/blob/v0.24.0/rest/config.go#L387
https://github.com/kubernetes/client-go/blob/v0.24.0/rest/url_utils.go#L82

Our current idea on the issue is that the difference in functionality between Linux and Windows is due to Go for Windows not having access to the System CA Certificate Store until go1.18. We are exploring what is required to bump Rancher and its dependencies to go1.18 (including system-agent and wins) to properly address the issues with custom CA certificates.

Please see the attached issues and PRs
https://github.com/golang/go/issues/16736
https://go-review.googlesource.com/c/go/+/353589

The community of SIG Windows has requested the fix to be backported to go1.17. There has not been any movement on that request in about a month.

- Is the issue resolved? 

Not as of the release of Rancher v2.6.5.

- What is the status of the issue?

The issue has been triaged and design regarding a proper solution is planned after the 2.6.5 release.

- Is there a workaround available?

No, there are currently no workarounds available.

- When will this be fixed?

We plan to have this addressed in Rancher v2.6.6.

**Comment by deniseschannon** [comment] 2022-06-17 20:34
A fix was introduced in RKE2 that was part of the May patches and is now available and should be ready to test air gap again.

**Comment by slickwarren** [comment] 2022-07-19 21:07
tested on v2.6.7-rc3 in an airgapped setup:
* using v1.23.7+rke2r1, windows node is not able to register. Looking into the logs, rancher-wins has finished however rke2 never starts. 
I have a setup available for the next 24 hours that the dev could use, otherwise they would need to get their own setup.

**Comment by snasovich** [comment] 2022-07-26 18:53
Closing this as a duplicate of https://github.com/rancher/windows/issues/161 - all testing/validation will be there.

**Closed** 2022-07-26 18:54 UTC
Labels: kind/bug-qa, [zube]: Done, QA/S, [zube]: Waiting for Rancher RC, team/area2
