### ISSUE TITLE
[BUG] Edit ConfigMap With RancherUI

### ISSUE THREAD

**Issue by LaoZhang-best** [rancher/rancher#43568] opened 2023-11-17 05:59 UTC
like this “https://github.com/rancher/rancher/issues/43125#issue-1936924558”

**Comment by mohag** [comment] 2023-11-23 11:57
Also see rancher/dashboard#10066

**Comment by richard-cox** [comment] 2023-11-23 13:33
Closing as duplicate of issue in description

**Closed by richard-cox** 2023-11-23 13:33 UTC
Labels: kind/bug
