### ISSUE TITLE
Imported EKS Cluster -  Worker Nodes have issue connecting after Scaling/Resizing nodes

### ISSUE THREAD

**Issue by ghost** [rancher/rancher#16369] opened 2018-10-30 17:11 UTC
**What kind of request is this (question/bug/enhancement/feature request):** bug

**Steps to reproduce (least amount of steps as possible):**

1. Create EKS clusters and import the clusters into rancher v2.0.8.
2. Upgrade to rancher v2.1.0
3. Resize worker nodes from t2.medium to t2.large (CloudFormation Template)

**Result:**
The new nodes seem to have an issue connecting to the cluster. The issue seems to be related to the cattle agent nodes not being able to resolve the hostname of CATTLE_SERVER. 

**Other details that may be helpful:**
Scaling down from 3 to 0 and scaling back up to 3 seems to fix the issue. For production this is not a good solution.

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI):
**rancher/rancher v2.0.8 upgraded to v2.1.0**
- Installation option (single install/HA): **HA**

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): Imported
- Kubernetes version (use `kubectl version`): **1.10.3**

**Comment by cjellick** [comment] 2018-10-30 19:49
Do you have any logs?

**Comment by massimo-cannavo** [comment] 2018-11-05 17:40
Not able to reproduce the issue. Unable to fetch logs. Closing issue, can be reopened once the issue has been reproduced and logs have been acquired.

**Comment by massimo-cannavo** [comment] 2018-11-05 22:42
The issue that I encountered in #16454 seems to be the same DNS issue that I saw from the imported EKS cluster. I remember that in the EKS issue, we would delete stuff from the cattle-system namespace and try to add them back. Not sure if this is related, I believe RKE was also used.

**Closed** 2019-04-19 21:34 UTC
Labels: area/eks, area/imported-cluster, internal, kind/bug
