### ISSUE TITLE
Users without admin access cannot deploy stacks from catalog after upgrade

### ISSUE THREAD

**Issue by dnadave** [rancher/rancher#3170] opened 2016-01-05 23:45 UTC
Upgraded to 0.51.0 and now users who are not admins cannot deploy stacks from the catalog.  They can get to the launch page and successfully click on launch.  The Stacks view then shows the stack as activating, but it never progresses past that point and nothing shows up in docker ps.

Rancher 0.51.0 on OpenSuSE Leap 42.1

**Comment by deniseschannon** [comment] 2016-01-06 19:35
I am unable to reproduce as users in my setup are able to deploy stacks from catalog. 

What version did you upgrade from?

**Comment by deniseschannon** [comment] 2016-01-06 19:38
Also, which catalog item did they deploy?

**Comment by dnadave** [comment] 2016-01-06 19:40
0.4x.0.  I think 0.47.0, but I don't remember.  It's definitely a problem
on my system as they cannot successfully deploy anything.

We're using our own catalog.  I'll send you a copy, shortly.

**Comment by dnadave** [comment] 2016-01-06 19:45
Here's an archive of the catalog entry:

[rancher-catalog.zip](https://github.com/rancher/rancher/files/80269/rancher-catalog.zip)

We're still working on getting the health check stuff to work.  It's quite broken as it stands now.

**Comment by dnadave** [comment] 2016-01-06 23:23
I upgraded by following the instructions on http://docs.rancher.com/rancher/upgrading/ where you create a data container and then link to that after pulling a new image.  Could there be permissions problems with the external database?

Also, I keep getting the following error posted to StdErr:

2016/01/06 13:10:40 http: multiple response.WriteHeader calls

**Comment by dnadave** [comment] 2016-01-07 00:35
When I switch to these users' environment, I do not see any hosts added.  Why do they not see the global host that was added?

**Comment by dnadave** [comment] 2016-01-07 00:49
I added hosts to their environments and the hosts show up as reconnecting.  I should point out that we are running the agents on the same host as the server.  Previously, when I set up a host, it showed up for everyone.  Now, it only shows up for me as the admin and none of the users can set up a working host.

**Comment by vincent99** [comment] 2016-01-07 00:53
Multiple users can have access to the same environment(s), but hosts are own by a single environment and cannot (and never could be) shared between them.

**Comment by dnadave** [comment] 2016-01-07 00:55
This is a problem.  We have a single server with multiple users connecting to it.  When we were using StackEngine, this was not a problem.

**Comment by dnadave** [comment] 2016-01-07 00:56
If you're going to have it set up that way, then each user needs to have access to the default environment by DEFAULT and not to their OWN ENVIRONMENT by default.

**Comment by dnadave** [comment] 2016-01-07 00:56
You should be able to set up a global host.

**Comment by deniseschannon** [comment] 2016-01-07 03:51
You can easily add users to the default environment by managing it so that all users could have access to it. The "Default" environment is really just an environment named "Default" that can be changed to "dev", "test", "lab", etc. It wouldn't make sense to have the default login be the environment named "Default" that could change. It makes more sense to have people be invited to the "Default" environment. 

There are many different levels of access that Rancher has. 

Level 1: Account Type: http://docs.rancher.com/rancher/configuration/access-control/#account-types
Admins vs. Users 

Level 2: For each environment, you can set who has access to the environment. 
http://docs.rancher.com/rancher/configuration/environments/

As your original issue was the fact that "users" couldn't launch catalog items, I thought you meant users in the "Users vs. Admins" context. There is no issue in launching catalog items for those users and therefore I'l be closing this issue.

**Closed by deniseschannon** 2016-01-07 03:51 UTC
Labels: kind/question
