### ISSUE TITLE
AKS Cluster alerting on unhealthy controller-manager/scheduler

### ISSUE THREAD

**Issue by amagura** [rancher/rancher#23451] opened 2019-10-15 18:25 UTC
**What kind of request is this (question/bug/enhancement/feature request):**
Question/Bug

**Steps to reproduce (least amount of steps as possible):**
1. Create a cluster in AKS (through Rancher)
2. Create an alert in Rancher for one of your workloads
3. Wait anywhere from 10 to 45 minutes.  
2. At some point, the alert system will start alerting that the Controller-Manager and Scheduler are unhealthy.

![alerting](https://user-images.githubusercontent.com/5353903/66858008-b467e380-ef45-11e9-8c81-833c1f648157.png)

**Result:**

Cluster, eventually, starts alerting that Controller-Manager and Scheduler are unhealthy.

**Other details that may be helpful:**
I have two AKS clusters, presently, both appear to be running fine.  When I run `kubectl get cs` on both of them, I get the following:

```
NAME                 STATUS      MESSAGE                                                                                     ERROR
controller-manager   Unhealthy   Get http://127.0.0.1:10252/healthz: dial tcp 127.0.0.1:10252: connect: connection refused   
scheduler            Unhealthy   Get http://127.0.0.1:10251/healthz: dial tcp 127.0.0.1:10251: connect: connection refused   
etcd-0               Healthy     {"health": "true"}                
```

However, only one of the clusters is currently alerting that the controller-manager/scheduler is unhealthy.  

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): v2.3.0/v2.3.0
- Installation option (single install/HA): Single

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): Hosted
- Machine type (cloud/VM/metal) and specifications (CPU/memory): Cloud
- Kubernetes version (use `kubectl version`):

```
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.6", GitCommit:"96fac5cd13a5dc064f7d9f4f23030a6aeface6cc", GitTreeState:"clean", BuildDate:"2019-08-19T11:13:49Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.6", GitCommit:"96fac5cd13a5dc064f7d9f4f23030a6aeface6cc", GitTreeState:"clean", BuildDate:"2019-08-19T11:05:16Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}
```

- Docker version (use `docker version`):

```
Client:
 Version:           18.09.9
 API version:       1.39
 Go version:        go1.11.13
 Git commit:        039a7df9ba
 Built:             Wed Sep  4 16:57:28 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.9
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.11.13
  Git commit:       039a7df
  Built:            Wed Sep  4 16:19:38 2019
  OS/Arch:          linux/amd64
  Experimental:     false
```

---

Is this related to #17344 and #11496 and can it be disregarded as part of the AKS <=> Rancher interaction bug?

**Comment by amagura** [comment] 2019-10-15 18:30
This is now happening to both of my AKS clusters.

**Comment by sowmyav27** [comment] 2019-10-15 21:58
**Reproduced this issue in `rancher:v2.3.0`**

**Steps:**

- Deploy an AKS cluster with default settings from the Rancher UI.
- Deploy workloads.
- Setup an Alert for the workload. (Condition: On a workload(4 pods), is less than 90% available. Under advance options -- All the times = 1s) to Slack channel
- The alert does not get triggered when the workload is available < 90%.
- After sometime, Go to Cluster --> Tools--> Alerts 
- The kube components - Controller Manager and Scheduler are seen in `Alerting` state.
- No alerts to Slack are seen.

<img width="1246" alt="Screen Shot 2019-10-15 at 2 53 29 PM" src="https://user-images.githubusercontent.com/26032343/66873005-40850580-ef5c-11e9-882d-f7267effd03c.png">

**Comment by amagura** [comment] 2019-11-13 17:26
This is happening on all of my AKS based clusters.

**Comment by deniseschannon** [comment] 2020-11-15 21:42
Duplicate of https://github.com/rancher/rancher/issues/11496

We are planning on addressing the clusters using component status with this issue: https://github.com/rancher/rancher/issues/11496#issuecomment-727641496

**Closed by deniseschannon** 2020-11-15 21:42 UTC
