### ISSUE TITLE
Monitoring v2 installation in a hardened cluster fails when no project is chosen

### ISSUE THREAD

**Issue by bashofmann** [rancher/rancher#29980] opened 2020-11-09 16:53 UTC
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
* Create a cluster with PodSecurityPolicies activated and choose `restricted` as the default policy
* Go to Cluster Explorer -> Apps & Marketplace
* Install the Monitoring app without choosing a project to install it in (the "Project" field is optional)

**Result:**
* The `cattle-monitoring-system` namespace is created
* Because the new namespace is not attached to a project, Rancher does not apply the default PodSecurityPolicy to the namespace
* The `rancher-monitoring-crd-create` pod does not start because of a PSP error

When you add the `cattle-monitoring-system` namespace to a project, the default policy is applied, the job starts and the installation continues successfully.

**Other details that may be helpful:**
General PSP support for monitoring was added with https://github.com/rancher/rancher/issues/28536.

I only tested monitoring, this also may affect other apps.

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): 2.5.2-rc7
- Installation option (single install/HA): HA

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): Custom
- Kubernetes version (use `kubectl version`): 1.19.3, with PodSecurityPolicies activated

gz#12824

**Comment by aiyengar2** [comment] 2020-11-09 19:15
@bashofmann good catch, this should affect only `rancher-monitoring` and [`rancher-cis-benchmark`](https://github.com/rancher/charts/pull/595) since it affects all charts that use `generateCRDCharts.assumeOwnershipOfCRDs`). 

We need to add a PSP here: https://github.com/rancher/charts/tree/dev-v2.5-source/scripts/chart-templates/crd-assume-ownership/templates

**Comment by Tejeev** [comment] 2020-11-10 10:12
Is there any reason we might see this on a cluster where the pod security policy is not restricted?

**Comment by bashofmann** [comment] 2020-11-10 11:22
I think this fails at the moment as soon as PodSecurityPolicies are activated, regardless what the configured default policy is.

**Comment by aiyengar2** [comment] 2020-11-11 18:44
@Tejeev I don't think this bug has to do with the type of PSP, based on:

> Because the new namespace is not attached to a project, Rancher does not apply the default PodSecurityPolicy to the namespace

The lack of any PSP in that namespace for the `rancher-monitoring-crd` Job to use is probably the issue.

**Comment by Rancheroo** [comment] 2020-11-13 00:43
I have found this issue in Rancher Managed Clusters where the PSP is unrestricted.

WORKAROUND
The issue was that when installing the Monitoring v2 chart it was installing the cattle-monitoring-system namespace and not assigning to the System Project.
When manually assinging the cattle-monitoring-system namespace to the System Project (using the Classic Rancher UI) and waiting for a minute the CRDs install and then the workloads start to deploy
![image](https://user-images.githubusercontent.com/56899019/99013700-3725fc80-25a5-11eb-98c2-97279e44a05d.png)

> Install the Monitoring app without choosing a project to install it in (the "Project" field is optional)
The is option is only available when installing Monitoring on the Local RKE Rancher cluster
Should this option exist when installing on managed (Downstream) Clusters
or is the default the System Project? 
Why in some cases is the System Project not assigned?

![image](https://user-images.githubusercontent.com/56899019/99013497-bff06880-25a4-11eb-82b5-e29555334dfc.png)

**Comment by jiaqiluo** [comment] 2020-11-19 18:17
The bug is reproduced on v2.5.2 single install setup 

The steps are the same as the issue provides, and the result is also the same. 

```
>  k -n cattle-monitoring-system describe job rancher-monitoring-crd-create | grep -i error
  Warning  FailedCreate  2m19s (x5 over 4m49s)  job-controller  Error creating: pods "rancher-monitoring-crd-create-" is forbidden: PodSecurityPolicy: unable to admit pod: []
```

**Comment by jiaqiluo** [comment] 2020-11-19 21:37
The bug fix is validated on v2.5.2 with the new Monitoring chart `v9.4.202`

The steps are the same as the issue provides, and Monitoring is installed successfully and functional. 
All pods are installed successfully. 
```
> k get pods -n cattle-monitoring-system
NAME                                                      READY   STATUS    RESTARTS   AGE
alertmanager-rancher-monitoring-alertmanager-0            2/2     Running   0          15m
prometheus-rancher-monitoring-prometheus-0                4/4     Running   1          15m
pushprox-kube-controller-manager-client-z7kgz             1/1     Running   0          15m
pushprox-kube-controller-manager-proxy-864f7bdd58-r6v7n   1/1     Running   0          15m
pushprox-kube-etcd-client-8kvmh                           1/1     Running   0          15m
pushprox-kube-etcd-proxy-566676cc9d-95fdn                 1/1     Running   0          15m
pushprox-kube-proxy-client-42mg4                          1/1     Running   0          15m
pushprox-kube-proxy-client-b6wkz                          1/1     Running   0          15m
pushprox-kube-proxy-client-wvs5z                          1/1     Running   0          15m
pushprox-kube-proxy-client-xmcrq                          1/1     Running   0          15m
pushprox-kube-proxy-proxy-69f45565c4-s8sst                1/1     Running   0          15m
pushprox-kube-scheduler-client-m49bd                      1/1     Running   0          15m
pushprox-kube-scheduler-proxy-b76dcf98d-6q5hj             1/1     Running   0          15m
rancher-monitoring-grafana-6c9bc449d4-ngt97               3/3     Running   0          15m
rancher-monitoring-kube-state-metrics-5c549477ff-95f46    1/1     Running   0          15m
rancher-monitoring-operator-68477c5c9b-bg6xk              2/2     Running   0          15m
rancher-monitoring-prometheus-adapter-7587895bfc-fzz8v    1/1     Running   0          15m
rancher-monitoring-prometheus-node-exporter-5rlnq         1/1     Running   0          15m
rancher-monitoring-prometheus-node-exporter-wg48n         1/1     Running   0          15m
rancher-monitoring-prometheus-node-exporter-zxjj6         1/1     Running   0          15m
```

**Closed** 2020-11-19 21:42 UTC
Labels: [zube]: To Test, internal

**Comment by aiyengar2** [comment] 2020-11-20 01:47
Thank you @bashofmann for contributing the fix!

**Comment by alex-isv** [comment] 2023-07-28 18:16
This issue is not fixed. Using the latest Monitoring (102.0.1+up40.1.2) with Rancher 2.7.4 and without assigning Monitoring to the project, it won't install due to the PSP set as unrestricted. If moving ns to default or system, the installation will work.
