### ISSUE TITLE
`cloud-controller-manager` pod is in `Crashloopbackoff` state in an RKE2 cluster

### ISSUE THREAD

**Issue by sowmyav27** [rancher/rancher#36869] opened 2022-03-13 01:45 UTC
**Rancher Server Setup**
- Rancher version: 2.6-head commit id `f904267`
- Installation option (Docker install/Helm Chart): docker install

**Information about the Cluster**
- Kubernetes version: `v1.21.10+rke2r1`
- Cluster Type (Local/Downstream): RKE2 EC2 node driver cluster - 3 etcd, 2 cp and 3 worker nodes

**User Information**
- What is the role of the user logged in? (Admin/Cluster Owner/Cluster Member/Project Owner/Project Member/Custom) admin

   
**Describe the bug**
`cloud-controller-manager` pod is in `Crashloopbackoff` state in an RKE2 cluster

**To Reproduce**
- deploy an EC2 node driver cluster RKE2
- `cloud-controller-manager` pod is in `Crashloopbackoff` state in an RKE2 cluster
- Logs of the pod:
```


I0313 01:39:46.481343 1 serving.go:354] Generated self-signed cert in-memory
--
Sun, Mar 13 2022 7:09:47 am | W0313 01:39:47.186008 1 authentication.go:419] failed to read in-cluster kubeconfig for delegated authentication: open /var/run/secrets/kubernetes.io/serviceaccount/token: no such file or directory
Sun, Mar 13 2022 7:09:47 am | W0313 01:39:47.186063 1 authentication.go:316] No authentication-kubeconfig provided in order to lookup client-ca-file in configmap/extension-apiserver-authentication in kube-system, so client certificate authentication won't work.
Sun, Mar 13 2022 7:09:47 am | W0313 01:39:47.186074 1 authentication.go:340] No authentication-kubeconfig provided in order to lookup requestheader-client-ca-file in configmap/extension-apiserver-authentication in kube-system, so request-header client certificate authentication won't work.
Sun, Mar 13 2022 7:09:47 am | W0313 01:39:47.186092 1 authorization.go:225] failed to read in-cluster kubeconfig for delegated authorization: open /var/run/secrets/kubernetes.io/serviceaccount/token: no such file or directory
Sun, Mar 13 2022 7:09:47 am | W0313 01:39:47.186115 1 authorization.go:193] No authorization-kubeconfig provided, so SubjectAccessReview of authorization tokens won't work.
Sun, Mar 13 2022 7:09:47 am | I0313 01:39:47.201558 1 controllermanager.go:142] Version: v1.22.1-k3s1
Sun, Mar 13 2022 7:09:47 am | I0313 01:39:47.202610 1 secure_serving.go:200] Serving securely on 127.0.0.1:10258
Sun, Mar 13 2022 7:09:47 am | I0313 01:39:47.202838 1 tlsconfig.go:240] "Starting DynamicServingCertificateController"
Sun, Mar 13 2022 7:09:47 am | I0313 01:39:47.204059 1 leaderelection.go:248] attempting to acquire leader lease kube-system/cloud-controller-manager...

```

Note: This is seen on 2.6.3 also

**Comment by snasovich** [comment] 2022-03-14 18:45
This is somewhat likely to end up being RKE2 issue, we need to confirm this.
@brandond @Oats87 @briandowns , is this something you guys have seen in RKE2?

**Comment by brandond** [comment] 2022-03-14 18:50
Did you enable the ec2 cloud provider? You mentioned using the ec2 node driver, but the rke2 cloud-controller-manager would only be running if you hadn't enabled the ec2 cloud provider. I'm also not seeing any errors in the log you attached since it seems to be running; you may want to collect the `kubectl describe pod` output, along with the the logs from the `--previous` pod?

**Comment by snasovich** [comment] 2022-03-14 19:02
@sowmyav27 , could you please follow up on the clarification requests above?

**Comment by brandond** [comment] 2022-03-15 00:16
Is that the complete output from the previous contaienr? How long did it run before crashing, or did it crash immediately? Does every run terminate with that error eventually? Based on the output you posted earlier it looked like the current container was running just fine.

> you may want to collect the `kubectl describe pod` output
Can you collect this as well?

**Comment by sowmyav27** [comment] 2022-03-16 06:22
@brandond Yes, current container is running fine. In the last two times i tried, i saw 2 restarts on the container, but when I initially logged this bug, it kept restarting ~60 times when i noticed.
- Currently 2 restarts in last 12 mins. Maybe it did restart initially before coming back up Active
<img width="1400" alt="Screen Shot 2022-03-16 at 11 49 49 AM" src="https://user-images.githubusercontent.com/26032343/158528699-b53ba012-dac1-432b-a8f2-266c1bdfbadd.png">
- `kubectl describe pod output` - 

```
kubectl describe pod cloud-controller-manager-sowmya-ec2-1-pool1-ac20c24b-pzc7v  -n kube-system
Name:                 cloud-controller-manager-sowmya-ec2-1-pool1-ac20c24b-pzc7v
Namespace:            kube-system
Priority:             2000000000
Priority Class Name:  system-cluster-critical
Node:                 sowmya-ec2-1-pool1-ac20c24b-pzc7v/<>
Start Time:           Wed, 16 Mar 2022 06:07:05 +0000
Labels:               component=cloud-controller-manager
                      tier=control-plane
Annotations:          kubernetes.io/config.hash: 55f9f17b4e5074258f7eac3205f91cef
                      kubernetes.io/config.mirror: 55f9f17b4e5074258f7eac3205f91cef
                      kubernetes.io/config.seen: 2022-03-16T06:04:55.178372671Z
                      kubernetes.io/config.source: file
                      kubernetes.io/psp: global-unrestricted-psp
Status:               Running
IP:                   <>
IPs:
  IP:           <>
Controlled By:  Node/sowmya-ec2-1-pool1-ac20c24b-pzc7v
Containers:
  cloud-controller-manager:
    Container ID:  containerd://68bff6d6c6a28a76a3eb083cbfa8248ba2b5f3b7f9e975c5e8adfa83a2cbe260
    Image:         index.docker.io/rancher/rke2-cloud-provider:v0.0.3-build20211118
    Image ID:      docker.io/rancher/rke2-cloud-provider@sha256:a3fe814abb2f4cdb41583a5175453ec63667cce9e653a7b1a821d2c96a278c52
    Port:          <none>
    Host Port:     <none>
    Command:
      cloud-controller-manager
      --allocate-node-cidrs=true
      --authentication-kubeconfig=/var/lib/rancher/rke2/server/cred/cloud-controller.kubeconfig
      --authorization-kubeconfig=/var/lib/rancher/rke2/server/cred/cloud-controller.kubeconfig
      --bind-address=127.0.0.1
      --cloud-provider=rke2
      --cluster-cidr=10.42.0.0/16
      --configure-cloud-routes=false
      --kubeconfig=/var/lib/rancher/rke2/server/cred/cloud-controller.kubeconfig
      --node-status-update-frequency=1m0s
      --port=0
      --profiling=false
    State:          Running
      Started:      Wed, 16 Mar 2022 06:07:35 +0000
    Last State:     Terminated
      Reason:       Error
      Exit Code:    255
      Started:      Wed, 16 Mar 2022 06:07:19 +0000
      Finished:     Wed, 16 Mar 2022 06:07:21 +0000
    Ready:          True
    Restart Count:  2
    Requests:
      cpu:     200m
    Liveness:  http-get https://127.0.0.1:10258/healthz delay=15s timeout=15s period=10s #success=1 #failure=8
    Environment:
      FILE_HASH:  cf89be8b3f937eedb634114b4debcc68ac0d6a10afba6842053340edebaf4ced
      NO_PROXY:   .svc,.cluster.local,10.42.0.0/16,10.43.0.0/16
    Mounts:
      /etc/ca-certificates from dir1 (rw)
      /etc/ssl/certs from dir0 (rw)
      /usr/local/share/ca-certificates from dir2 (rw)
      /usr/share/ca-certificates from dir3 (rw)
      /var/lib/rancher/rke2/server/cred/cloud-controller.kubeconfig from file0 (ro)
      /var/lib/rancher/rke2/server/tls/client-rke2-cloud-controller.crt from file1 (ro)
      /var/lib/rancher/rke2/server/tls/client-rke2-cloud-controller.key from file2 (ro)
      /var/lib/rancher/rke2/server/tls/server-ca.crt from file3 (ro)
Conditions:
  Type              Status
  Initialized       True 
  Ready             True 
  ContainersReady   True 
  PodScheduled      True 
Volumes:
  dir0:
    Type:          HostPath (bare host directory volume)
    Path:          /etc/ssl/certs
    HostPathType:  DirectoryOrCreate
  dir1:
    Type:          HostPath (bare host directory volume)
    Path:          /etc/ca-certificates
    HostPathType:  DirectoryOrCreate
  dir2:
    Type:          HostPath (bare host directory volume)
    Path:          /usr/local/share/ca-certificates
    HostPathType:  DirectoryOrCreate
  dir3:
    Type:          HostPath (bare host directory volume)
    Path:          /usr/share/ca-certificates
    HostPathType:  DirectoryOrCreate
  file0:
    Type:          HostPath (bare host directory volume)
    Path:          /var/lib/rancher/rke2/server/cred/cloud-controller.kubeconfig
    HostPathType:  File
  file1:
    Type:          HostPath (bare host directory volume)
    Path:          /var/lib/rancher/rke2/server/tls/client-rke2-cloud-controller.crt
    HostPathType:  File
  file2:
    Type:          HostPath (bare host directory volume)
    Path:          /var/lib/rancher/rke2/server/tls/client-rke2-cloud-controller.key
    HostPathType:  File
  file3:
    Type:          HostPath (bare host directory volume)
    Path:          /var/lib/rancher/rke2/server/tls/server-ca.crt
    HostPathType:  File
QoS Class:         Burstable
Node-Selectors:    <none>
Tolerations:       :NoExecute op=Exists
Events:
  Type     Reason   Age                From     Message
  ----     ------   ----               ----     -------
  Normal   Pulled   16m                kubelet  Container image "index.docker.io/rancher/rke2-cloud-provider:v0.0.3-build20211118" already present on machine
  Normal   Created  16m                kubelet  Created container cloud-controller-manager
  Normal   Started  16m                kubelet  Started container cloud-controller-manager
  Warning  BackOff  13m (x2 over 13m)  kubelet  Back-off restarting failed container
  Normal   Pulled   13m (x2 over 13m)  kubelet  Container image "index.docker.io/rancher/rke2-cloud-provider:v0.0.3-build20211118" already present on machine
  Normal   Created  13m (x2 over 13m)  kubelet  Created container cloud-controller-manager
  Normal   Started  13m (x2 over 13m)  kubelet  Started container cloud-controller-manager
```

**Comment by brandond** [comment] 2022-03-16 18:23
Hmm. The logs from the failed container just show that it got an EOF from the apiserver, which is what I would expect to see when the local apiserver is restarted following an upgrade or configuration change. Do you have access to any of the logs from the node where it was continuously restarting?

**Comment by jakefhyde** [comment] 2022-03-30 18:27
@sowmyav27 Could you provide the information to Brad when you have the chance?

**Comment by Sahota1225** [comment] 2022-04-06 20:36
@slickwarren will try to reproduce the issue and see if it still happens

**Comment by slickwarren** [comment] 2022-04-12 01:19
I am unable to reproduce this on 2.6-head (b44d54a) when deploying single-node rke2 clusters on either 1.22 or 1.21 k8s versions. closing the issue for now. 

cloud-controller-manager was using `rancher/rke2-cloud-provider:v0.0.3-build20211118` image

**Closed by slickwarren** 2022-04-12 01:19 UTC
Labels: kind/bug-qa, [zube]: QA Working, dependency-rke2, status/release-blocker, team/area2
