### ISSUE TITLE
Docker Machine 0.5.0 support

### ISSUE THREAD

**Issue by will-chan** [rancher/rancher#2576] opened 2015-11-05 23:59 UTC
- Add docker machine 0.5.0 to Rancher
- Add ability for users to configure Docker Engine when adding hosts.  This can be a global config.
- Add whitelist support for drivers

**Comment by wlan0** [comment] 2015-11-17 00:41
Going to wait before upgrading to docker machine v0.5.0 because of https://github.com/docker/machine/issues/2314

**Comment by cjellick** [comment] 2015-12-04 17:26
We missed engine-install-url

**Comment by cjellick** [comment] 2015-12-08 15:03
basically a dupe of #2839 and the other machine flag additions we did

**Comment by sangeethah** [comment] 2015-12-09 00:53
Tested with latest build from master - Dec 8.

Following arguments are now supported by create_machine which gets passed down to docker-machine:

engineOpts
engineInsecureRegistry
engineRegistryMirror
engineLabel
engineStorageDriver
engineInstallUrl

**Comment by sangeethah** [comment] 2015-12-09 01:08
Closing this issue since support for docker machine 0.5.2 and to be able to pass docker engine options when creating docker machines is already implemente.

New issue is logged to Add whitelist support for drivers -  #2962

**Closed by sangeethah** 2015-12-09 01:08 UTC
Labels: kind/feature, release/v1.0.0, status/resolved, status/to-test
