### ISSUE TITLE
Support mounting certs on fluentd

### ISSUE THREAD

**Issue by paynejacob** [rancher/rancher#29784] opened 2020-10-27 17:03 UTC
The helm chart needs to expose a way for users to mount a volume with certificates for some outputs.

Example:

[Splunk](https://banzaicloud.com/docs/one-eye/logging-operator/plugins/outputs/splunk_hec/) asks for paths to the certificate files.  The certificates must exist in the Fluentd filesystem.  The helm chart creates all of logging CRs where fluentd is configured, users need an option to mount a volume on the Fluentd containers.

**Comment by paynejacob** [comment] 2020-10-27 18:49
This is going to require the upstream chart adding support for fluend mounting volumes.

**Comment by nickgerace** [comment] 2020-10-28 21:45
Filed an issue upstream: https://github.com/banzaicloud/logging-operator/issues/608

**Comment by nickgerace** [comment] 2020-12-16 19:32
Confirmed that the upstream issue being resolved solves this. Logging Operator 3.8.3 (our current version) includes this change.

**Comment by nickgerace** [comment] 2020-12-16 23:20
Marking as Done since Logging Operator 3.8.3 contains the fix.

**Closed** 2020-12-16 23:19 UTC
Labels: [zube]: To Test, area/logging
