### ISSUE TITLE
io.rancher.scheduler.affinity:host_label puts all containers on one host

### ISSUE THREAD

**Issue by roflmao** [rancher/rancher#8080] opened 2017-03-07 13:59 UTC
**Rancher Versions:**
Server: 1.4.1
healthcheck: 0.2.3
ipsec: 0.4.5
network-services:
scheduler: 0.6.3
kubernetes (if applicable):

**Docker Version:**
1.10.3

**OS and where are the hosts located? (cloud, bare metal, etc):**
bare metal

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
Single node rancher

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle

**Steps to Reproduce:**
When using io.rancher.scheduler.affinity:host_label to schedule containers to a set of hosts, rancher puts all containers on one machine when scaling up. Should be balanced between labeled hosts.

**Results:** 
Scale only scales on one host with label.

**Comment by tfiduccia** [comment] 2017-03-07 17:23
@roflmao - this was fixed in 1.5.  This will now do a count of how many containers are on the hosts and put the next one on the host with the least amount of containers.  Just to be clear this is not a on per service basis.  If you have more containers on host1, for whatever reason, when you start the service, the next set of containers will go to host2 until they are even.

**Comment by roflmao** [comment] 2017-03-13 11:39
@tfiduccia  is this backported to 1.4.2?

**Comment by deniseschannon** [comment] 2017-03-13 20:36
@roflmao Nope. 1.4.2 only had a UI update

**Comment by cjellick** [comment] 2017-05-10 16:29
@roflmao Can you provide the logs of the scheduler container along with the id of a container that you expected to go to a different host and the uuids of the hosts? And the UUID of the host where it did land and the UUID of a host where you expected it to land?

You can find host uuid by clicking View in API in the menu for a host and then just searching for uuid on the page?

Also, once you provide that information, could you restart the scheduler container and see if the problem persists or if it corrects itself?

**Comment by Eriken** [comment] 2017-05-11 11:00
We were able to sort the problem by labeling new hosts and then recreating the service.

We will open this again if we experience the issue again.

**Comment by roflmao** [comment] 2017-05-12 08:57
@cjellick 

Label set on 3 hosts. Only one host is chosen when we scale up to 2 and 3 instances.

uuid of host which gets all three containers: "uuid": "74c067cb-e8dd-4120-b6aa-fa6070202366"
uuid host 2: "uuid": "c9f07c88-b595-43f8-901d-c003ab355e74"
uuid host 3: "uuid": "17c164a6-a4c9-4e58-912d-84083bc90ab9"

rancher 1.5.9
rancher/scheduler:v0.7.5	

scheduler log:

```
time="2017-05-12T08:50:49Z" level=info msg="Received event: Name: scheduler.prioritize, Event Id: bae881de-a419-4e1b-a9a3-9b2d13e6b188, ResourceId : 1i74766" 
time="2017-05-12T08:50:49Z" level=info msg="Reply: Name: reply.5477203518743420644, PreviousIds: [bae881de-a419-4e1b-a9a3-9b2d13e6b188], ResourceId: 1i74766, Data: map[prioritizedCandidates:[328e3303-5352-4621-89e3-0d89b43b99e7 9eddadd1-f755-4097-b3eb-a27da7108cd1 13565e88-1403-467f-b707-21f084a0ef3d 6a056fb9-6070-4764-8d03-79a24b205ae1 42f6fb8e-5e43-44d5-a663-fb81c80c8ee5 17393336-89d6-4f69-b873-6e3402089589 416d8f72-338a-4aab-ac50-2a621232dc9b c265c460-270b-46ca-aba1-95d9cedd5b50 f54f0cbd-980e-43b4-b1de-69543ced00cc 3795fa5c-a718-4a20-ba55-56c6cf8027a9 2d9d1e72-ea29-49c9-9c75-f62f4212fc75 037fd3fe-415f-49f1-881c-c3875ff7eabc 090a8487-4746-4652-9039-3100bdb1f02f 17cb5082-7456-4a13-b4c8-d265f1263f71 f33b7d70-4f41-4ec4-9826-d0609678d78d 74c067cb-e8dd-4120-b6aa-fa6070202366 d3e8b7d2-9609-4e93-8db0-c72e63c9070e 3edeb63c-84e4-4621-996b-90c99556b1c1 17c164a6-a4c9-4e58-912d-84083bc90ab9 6e1cc851-f90a-40fe-8e23-306641d69a2f 59b43a82-dd74-4489-866d-b39ac2936473 1982945a-8752-4877-af5e-5c5c7938222b 23a87538-fcb6-4af2-83fe-c1980008fc3a 4d0e21e9-b006-4cbf-b32b-b8d9e9feba09 bd1fe627-9cf3-4b47-bb7e-303650f0c0b9 3a55b2f2-d147-4aaa-b9e0-227c52cb4251 ff26d4c7-cfd6-4e05-a7bd-c15b7c1703d9 d678fbe7-18c6-425f-b5f9-f026e08237dd 3ccd3ec3-29f7-4f32-8da1-f82c10c6bd90 c9f07c88-b595-43f8-901d-c003ab355e74]]." 
time="2017-05-12T08:50:49Z" level=info msg="Received event: Name: scheduler.reserve, Event Id: 17ee05fb-5d9a-42fb-8814-52bef35bfa89, ResourceId : 1i74766" 
time="2017-05-12T08:50:49Z" level=info msg="Reserving [{Resource:instanceReservation Amount:1}] for 74c067cb-e8dd-4120-b6aa-fa6070202366. Force=false" 
time="2017-05-12T08:50:49Z" level=info msg="New pool amount on host 74c067cb-e8dd-4120-b6aa-fa6070202366: instanceReservation total: 1000000 used: 15." 
time="2017-05-12T08:50:49Z" level=info msg="Reply: Name: reply.5477203518743420644, PreviousIds: [17ee05fb-5d9a-42fb-8814-52bef35bfa89], ResourceId: 1i74766, Data: map[]." 
time="2017-05-12T08:50:49Z" level=info msg="Received event: Name: scheduler.reserve, Event Id: 30e56bcc-42aa-4e51-98f3-779b85723ca3, ResourceId : 1i74766" 
time="2017-05-12T08:50:49Z" level=info msg="Reserving [] for 74c067cb-e8dd-4120-b6aa-fa6070202366. Force=false" 
time="2017-05-12T08:50:49Z" level=info msg="Reply: Name: reply.5477203518743420644, PreviousIds: [30e56bcc-42aa-4e51-98f3-779b85723ca3], ResourceId: 1i74766, Data: map[]." 
time="2017-05-12T08:50:54Z" level=info msg="Received event: Name: scheduler.prioritize, Event Id: 320ac2a3-7beb-4244-8c1f-d417685fdf35, ResourceId : 1i74767" 
time="2017-05-12T08:50:54Z" level=info msg="Reply: Name: reply.6779302253629983312, PreviousIds: [320ac2a3-7beb-4244-8c1f-d417685fdf35], ResourceId: 1i74767, Data: map[prioritizedCandidates:[2d9d1e72-ea29-49c9-9c75-f62f4212fc75 328e3303-5352-4621-89e3-0d89b43b99e7 42f6fb8e-5e43-44d5-a663-fb81c80c8ee5 17393336-89d6-4f69-b873-6e3402089589 3795fa5c-a718-4a20-ba55-56c6cf8027a9 6a056fb9-6070-4764-8d03-79a24b205ae1 c265c460-270b-46ca-aba1-95d9cedd5b50 f54f0cbd-980e-43b4-b1de-69543ced00cc 416d8f72-338a-4aab-ac50-2a621232dc9b 037fd3fe-415f-49f1-881c-c3875ff7eabc 13565e88-1403-467f-b707-21f084a0ef3d 9eddadd1-f755-4097-b3eb-a27da7108cd1 17cb5082-7456-4a13-b4c8-d265f1263f71 090a8487-4746-4652-9039-3100bdb1f02f f33b7d70-4f41-4ec4-9826-d0609678d78d d3e8b7d2-9609-4e93-8db0-c72e63c9070e 74c067cb-e8dd-4120-b6aa-fa6070202366 3edeb63c-84e4-4621-996b-90c99556b1c1 17c164a6-a4c9-4e58-912d-84083bc90ab9 6e1cc851-f90a-40fe-8e23-306641d69a2f 59b43a82-dd74-4489-866d-b39ac2936473 1982945a-8752-4877-af5e-5c5c7938222b 23a87538-fcb6-4af2-83fe-c1980008fc3a 4d0e21e9-b006-4cbf-b32b-b8d9e9feba09 d678fbe7-18c6-425f-b5f9-f026e08237dd 3a55b2f2-d147-4aaa-b9e0-227c52cb4251 bd1fe627-9cf3-4b47-bb7e-303650f0c0b9 ff26d4c7-cfd6-4e05-a7bd-c15b7c1703d9 3ccd3ec3-29f7-4f32-8da1-f82c10c6bd90 c9f07c88-b595-43f8-901d-c003ab355e74]]." 
time="2017-05-12T08:50:54Z" level=info msg="Received event: Name: scheduler.reserve, Event Id: f2f30022-598b-4cc7-92f4-6c1309dcc65c, ResourceId : 1i74767" 
time="2017-05-12T08:50:54Z" level=info msg="Reserving [{Resource:instanceReservation Amount:1}] for 74c067cb-e8dd-4120-b6aa-fa6070202366. Force=false" 
time="2017-05-12T08:50:54Z" level=info msg="New pool amount on host 74c067cb-e8dd-4120-b6aa-fa6070202366: instanceReservation total: 1000000 used: 16." 
time="2017-05-12T08:50:54Z" level=info msg="Reply: Name: reply.6779302253629983312, PreviousIds: [f2f30022-598b-4cc7-92f4-6c1309dcc65c], ResourceId: 1i74767, Data: map[]." 
time="2017-05-12T08:50:54Z" level=info msg="Received event: Name: scheduler.reserve, Event Id: 05a2f04f-9646-47de-8d42-bb0e79d9527f, ResourceId : 1i74767" 
time="2017-05-12T08:50:54Z" level=info msg="Reserving [] for 74c067cb-e8dd-4120-b6aa-fa6070202366. Force=false" 
time="2017-05-12T08:50:54Z" level=info msg="Reply: Name: reply.6779302253629983312, PreviousIds: [05a2f04f-9646-47de-8d42-bb0e79d9527f], ResourceId: 1i74767, Data: map[]." 
```
Restarting, downscaling and upscaling: (still all on one host)

```
time="2017-05-12T08:56:12Z" level=info msg="Received event: Name: scheduler.release, Event Id: dddac109-d368-4d85-8014-386c5059e4d1, ResourceId : 1iir74767" 
time="2017-05-12T08:56:12Z" level=info msg="Releasing [] for 74c067cb-e8dd-4120-b6aa-fa6070202366" 
time="2017-05-12T08:56:12Z" level=info msg="New pool amounts on host 74c067cb-e8dd-4120-b6aa-fa6070202366:" 
time="2017-05-12T08:56:12Z" level=info msg="Reply: Name: reply.5218384436860030947, PreviousIds: [dddac109-d368-4d85-8014-386c5059e4d1], ResourceId: 1iir74767, Data: map[]." 
time="2017-05-12T08:56:13Z" level=info msg="Received event: Name: scheduler.release, Event Id: a976517a-27d2-4770-94c4-9bc827ede09c, ResourceId : 1iir74766" 
time="2017-05-12T08:56:13Z" level=info msg="Releasing [] for 74c067cb-e8dd-4120-b6aa-fa6070202366" 
time="2017-05-12T08:56:13Z" level=info msg="New pool amounts on host 74c067cb-e8dd-4120-b6aa-fa6070202366:" 
time="2017-05-12T08:56:13Z" level=info msg="Reply: Name: reply.8009225608075047147, PreviousIds: [a976517a-27d2-4770-94c4-9bc827ede09c], ResourceId: 1iir74766, Data: map[]." 

time="2017-05-12T08:56:54Z" level=info msg="Received event: Name: scheduler.prioritize, Event Id: f61a2544-4a96-475d-b1bd-a8fe6c6307b6, ResourceId : 1i74768" 
time="2017-05-12T08:56:54Z" level=info msg="Reply: Name: reply.3900132389023748414, PreviousIds: [f61a2544-4a96-475d-b1bd-a8fe6c6307b6], ResourceId: 1i74768, Data: map[prioritizedCandidates:[2d9d1e72-ea29-49c9-9c75-f62f4212fc75 328e3303-5352-4621-89e3-0d89b43b99e7 6a056fb9-6070-4764-8d03-79a24b205ae1 3795fa5c-a718-4a20-ba55-56c6cf8027a9 13565e88-1403-467f-b707-21f084a0ef3d 17393336-89d6-4f69-b873-6e3402089589 42f6fb8e-5e43-44d5-a663-fb81c80c8ee5 f54f0cbd-980e-43b4-b1de-69543ced00cc c265c460-270b-46ca-aba1-95d9cedd5b50 416d8f72-338a-4aab-ac50-2a621232dc9b 037fd3fe-415f-49f1-881c-c3875ff7eabc 9eddadd1-f755-4097-b3eb-a27da7108cd1 17cb5082-7456-4a13-b4c8-d265f1263f71 090a8487-4746-4652-9039-3100bdb1f02f f33b7d70-4f41-4ec4-9826-d0609678d78d d3e8b7d2-9609-4e93-8db0-c72e63c9070e 74c067cb-e8dd-4120-b6aa-fa6070202366 3edeb63c-84e4-4621-996b-90c99556b1c1 17c164a6-a4c9-4e58-912d-84083bc90ab9 59b43a82-dd74-4489-866d-b39ac2936473 1982945a-8752-4877-af5e-5c5c7938222b 6e1cc851-f90a-40fe-8e23-306641d69a2f 23a87538-fcb6-4af2-83fe-c1980008fc3a 4d0e21e9-b006-4cbf-b32b-b8d9e9feba09 3a55b2f2-d147-4aaa-b9e0-227c52cb4251 ff26d4c7-cfd6-4e05-a7bd-c15b7c1703d9 d678fbe7-18c6-425f-b5f9-f026e08237dd bd1fe627-9cf3-4b47-bb7e-303650f0c0b9 3ccd3ec3-29f7-4f32-8da1-f82c10c6bd90 c9f07c88-b595-43f8-901d-c003ab355e74]]." 
time="2017-05-12T08:56:54Z" level=info msg="Received event: Name: scheduler.reserve, Event Id: 0be7e81c-9019-432b-b4b7-7c6ce39a7b50, ResourceId : 1i74768" 
time="2017-05-12T08:56:54Z" level=info msg="Reserving [{Resource:instanceReservation Amount:1}] for 74c067cb-e8dd-4120-b6aa-fa6070202366. Force=false" 
time="2017-05-12T08:56:54Z" level=info msg="New pool amount on host 74c067cb-e8dd-4120-b6aa-fa6070202366: instanceReservation total: 1000000 used: 17." 
time="2017-05-12T08:56:54Z" level=info msg="Reply: Name: reply.3900132389023748414, PreviousIds: [0be7e81c-9019-432b-b4b7-7c6ce39a7b50], ResourceId: 1i74768, Data: map[]." 
time="2017-05-12T08:56:54Z" level=info msg="Received event: Name: scheduler.reserve, Event Id: 6b5cf358-d4cd-4435-a71b-ef227ab5c58d, ResourceId : 1i74768" 
time="2017-05-12T08:56:54Z" level=info msg="Reserving [] for 74c067cb-e8dd-4120-b6aa-fa6070202366. Force=false" 
time="2017-05-12T08:56:54Z" level=info msg="Reply: Name: reply.3900132389023748414, PreviousIds: [6b5cf358-d4cd-4435-a71b-ef227ab5c58d], ResourceId: 1i74768, Data: map[]." 
time="2017-05-12T08:57:01Z" level=info msg="Received event: Name: scheduler.prioritize, Event Id: 03cd7921-3739-4887-9723-21575268e9f1, ResourceId : 1i74769" 
time="2017-05-12T08:57:01Z" level=info msg="Reply: Name: reply.4329923906396737095, PreviousIds: [03cd7921-3739-4887-9723-21575268e9f1], ResourceId: 1i74769, Data: map[prioritizedCandidates:[9eddadd1-f755-4097-b3eb-a27da7108cd1 6a056fb9-6070-4764-8d03-79a24b205ae1 c265c460-270b-46ca-aba1-95d9cedd5b50 416d8f72-338a-4aab-ac50-2a621232dc9b 037fd3fe-415f-49f1-881c-c3875ff7eabc 3795fa5c-a718-4a20-ba55-56c6cf8027a9 13565e88-1403-467f-b707-21f084a0ef3d 17393336-89d6-4f69-b873-6e3402089589 42f6fb8e-5e43-44d5-a663-fb81c80c8ee5 f54f0cbd-980e-43b4-b1de-69543ced00cc 2d9d1e72-ea29-49c9-9c75-f62f4212fc75 328e3303-5352-4621-89e3-0d89b43b99e7 17cb5082-7456-4a13-b4c8-d265f1263f71 090a8487-4746-4652-9039-3100bdb1f02f f33b7d70-4f41-4ec4-9826-d0609678d78d d3e8b7d2-9609-4e93-8db0-c72e63c9070e 3edeb63c-84e4-4621-996b-90c99556b1c1 74c067cb-e8dd-4120-b6aa-fa6070202366 17c164a6-a4c9-4e58-912d-84083bc90ab9 59b43a82-dd74-4489-866d-b39ac2936473 1982945a-8752-4877-af5e-5c5c7938222b 6e1cc851-f90a-40fe-8e23-306641d69a2f 23a87538-fcb6-4af2-83fe-c1980008fc3a 4d0e21e9-b006-4cbf-b32b-b8d9e9feba09 3a55b2f2-d147-4aaa-b9e0-227c52cb4251 bd1fe627-9cf3-4b47-bb7e-303650f0c0b9 ff26d4c7-cfd6-4e05-a7bd-c15b7c1703d9 d678fbe7-18c6-425f-b5f9-f026e08237dd 3ccd3ec3-29f7-4f32-8da1-f82c10c6bd90 c9f07c88-b595-43f8-901d-c003ab355e74]]." 
time="2017-05-12T08:57:01Z" level=info msg="Received event: Name: scheduler.reserve, Event Id: d0edc0ec-bc3d-41eb-bd1b-a89e23c75a3a, ResourceId : 1i74769" 
time="2017-05-12T08:57:01Z" level=info msg="Reserving [{Resource:instanceReservation Amount:1}] for 74c067cb-e8dd-4120-b6aa-fa6070202366. Force=false" 
time="2017-05-12T08:57:01Z" level=info msg="New pool amount on host 74c067cb-e8dd-4120-b6aa-fa6070202366: instanceReservation total: 1000000 used: 18." 
time="2017-05-12T08:57:01Z" level=info msg="Reply: Name: reply.4329923906396737095, PreviousIds: [d0edc0ec-bc3d-41eb-bd1b-a89e23c75a3a], ResourceId: 1i74769, Data: map[]." 
time="2017-05-12T08:57:01Z" level=info msg="Received event: Name: scheduler.reserve, Event Id: 85206046-3133-4f7b-97f7-15f4ec9d43e2, ResourceId : 1i74769" 
time="2017-05-12T08:57:01Z" level=info msg="Reserving [] for 74c067cb-e8dd-4120-b6aa-fa6070202366. Force=false" 
time="2017-05-12T08:57:01Z" level=info msg="Reply: Name: reply.4329923906396737095, PreviousIds: [85206046-3133-4f7b-97f7-15f4ec9d43e2], ResourceId: 1i74769, Data: map[]." 

```

**Comment by cjellick** [comment] 2017-05-15 16:21
@roflmao Do the three hosts with the label have an equal total number of containers? Of those three hosts, the scheduler is still going to always pick the host with the fewest number of containers.* The logs indicate that this is what is happening in your case.

To force spread amongst those hosts, you could add a soft anti-affinity label as demonstrated here: https://docs.rancher.com/rancher/v1.1/en/cattle/scheduling/#example-1

* Note: there's a [known bug](https://github.com/rancher/rancher/issues/8639) that can cause counts of containers on hosts to get out of sync. I don't know if this is also impacting your environment or not, but if the three hosts have the same number of containers and the one host is still getting all of the containers in your service, then this could be the root cause as well.

**Comment by Eriken** [comment] 2017-05-18 18:22
@cjellick 
using 
`io.rancher.scheduler.affinity:container_label_ne: io.rancher.stack_service.name=$${stack_name}/$${service_name}` 

seemed to solve it. We assumed rancher would deploy evenly on all available host before duplicating services on hosts.

Thanks.

**Comment by cjellick** [comment] 2017-05-19 18:15
Cool. We probably _should_ do an implicit soft anti-affinity for services (which would cause it to do what you expected when it could)

**Comment by loganhz** [comment] 2018-10-12 06:50
Thanks for your report!

With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.

If you think we should keep this issue open, please let me know.

**Closed by loganhz** 2018-10-12 06:50 UTC
Labels: area/scheduler, kind/bug, version/1.6
