### ISSUE TITLE
Rancher HA - Failed to open project management: Can not create a stack, check API key Rancher

### ISSUE THREAD

**Issue by kraucer** [rancher/rancher#6329] opened 2016-10-19 14:39 UTC
**Rancher Version:**
v1.2.0-pre3
**Docker Version:**
1.10.3
**OS and where are the hosts located? (cloud, bare metal, etc):**
RHEL 7.3
**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
HA Rancher in testing on single node, with external DB
**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle
**Steps to Reproduce:**
1) http://docs.rancher.com/rancher/v1.2/en/installing-rancher/installing-server/multi-nodes/
2) docker run -d --restart=always --name rancher-server -p 8080:8080 -e CATTLE_DB_CATTLE_MYSQL_HOST=$ip_server -e CATTLE_DB_CATTLE_MYSQL_PORT=3306 -e CATTLE_DB_CATTLE_MYSQL_NAME=cattle -e CATTLE_DB_CATTLE_USERNAME=cattle -e CATTLE_DB_CATTLE_PASSWORD=cattle rancher/server:v1.2.0-pre3
3) docker run -d --restart=always --name nginx_proxy -p 80:80 -p 443:443 --link=rancher-server nginx_proxy

**Results:** 
command "docker -f logs rancher-ha" shows the error messages:
time = "2016-10-18T09: 31: 13Z" level = error msg = "Failed to open project management: Can not create a stack, check API key [279E88DEA199DEA5E619] is [http://192.168.169.1:18080/v1 / projects / 1A7 / schemas] "
time = "2016-10-18T09: 31: 13Z" level = fatal msg = "Failed to read project: Can not create a stack, check API key [279E88DEA199DEA5E619] is [http://192.168.169.1:18080/v1/ projects / 1A7 / schemas] "
time = "2016-10-18T09: 31: 13Z" level = info msg = "Can not launch agent right now: exit status 1" 

**Expected:**
No show fatal errors

**Comment by ymc-dabe** [comment] 2016-10-20 18:13
I can confirm this issue for:
- Upgrading (a fresh) 1.1.4 to 1.2.0-pre3
- Installing 1.2.0-pre3 from scratch in ha-mode

**Comment by kraucer** [comment] 2016-10-26 11:24
Tk's ymc-dabe. I will test the new version and send feedback.

**Comment by kraucer** [comment] 2016-10-26 11:37
@ymc-dabe has some version (same old) in the HA to work's fine?

**Comment by ymc-dabe** [comment] 2016-10-26 12:16
@kraucer The current stable (1.1.4) is working just great in ha-mode.

btw.: 1.2.0-pre4-rc4 was failing in ha-mode with different errors. I'll try to check if 1.2.0-pre4-rc5 works (or just wait for 1.1.2 to get released, which should be in a few days).

**Comment by kraucer** [comment] 2016-10-28 10:24
When I run the script in version 1.1.4 this error occurred:
time="2016-10-19T08:21:50Z" level=info msg="Waiting for server to be available" component=cert
time="2016-10-19T08:21:50Z" level=info msg="Can not launch agent right now: Server not available at http://192.168.169.2:18080/ping:" component=service 

Note that it looks for the agent on the IP 192.168.169.2 when it should be the IP 192.168.169.1

[root@dockersrv kraucer]# ifconfig
docker0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
inet 192.168.169.1  netmask 255.255.255.0  broadcast 0.0.0.0

Do you have any tips or additional script to share with me?

Best regards,

**Comment by ymc-dabe** [comment] 2016-10-28 10:40
@kraucer I followed http://docs.rancher.com/rancher/v1.1/en/installing-rancher/installing-server/multi-nodes/ for a three nodes setup and it worked out of the box with 1.1.4.
In a three node setup you need to run the ha-script on three different servers. The waiting message is normal during startup is normal and will go away once all the zookeeper instances start seeing each other and the admin UI on port 18080 gets available. Once it is reachable you can check the initialization of the "System HA"-Stack on port 18080. After the initialization is done and the "System HA" stack is ready you will be able to access rancher on port 80 (hence 18080 will still remain working).

**Comment by kraucer** [comment] 2016-10-31 13:09
@ymc-dabe test in version 1.1.4, error:

time="2016-10-19T08:21:50Z" level=info msg="Waiting for server to be available" component=cert
time="2016-10-19T08:21:50Z" level=info msg="Can not launch agent right now: Server not available at http://192.168.169.2:18080/ping:" component=service

Note that it looks for the agent on the IP 192.168.169.2 when it should be the IP 192.168.169.1

Same error reported here: https://forums.rancher.com/t/rancher-ha-can-not-launch-agent-right-now-server-not-available-at-http-172-19-10-2-18080-ping/3109

**Comment by vincent99** [comment] 2017-09-19 07:55
Closing due to age, and the way HA works was completely changed after 1.1.x.

**Closed by vincent99** 2017-09-19 07:55 UTC
Labels: kind/question
