### ISSUE TITLE
[custom cluster] unable to register rke2 nodes to custom cluster -> /etc/ssl/certs/ca-certificates.crt = `none`

### ISSUE THREAD

**Issue by slickwarren** [rancher/rancher#35710] opened 2021-12-01 22:29 UTC
**Rancher Server Setup**
- Rancher version: v2.6-head (46eb9d4)
- Installation option (Docker install/Helm Chart):docker
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc):
- Proxy/Cert Details:self signed certs (docker install)

**Information about the Cluster**
- Kubernetes version:1.21.6-rke2r1
- Cluster Type (Local/Downstream):downstream
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider): custom

**Describe the bug**

* when registering a downstream node with a custom cluster, the command fails due to  /etc/ssl/certs/ca-certificates.crt = `none`

**To Reproduce**
 
* deploy a custom rke2 1.21.6 cluster through rancher and get the registration command (check the `insecure` option before copying the command)
* deploy a node and run the registration command on it

**Result**
```
curl: (60) server certificate verification failed. CAfile: /etc/ssl/certs/ca-certificates.crt CRLfile: none
More details here: http://curl.haxx.se/docs/sslcerts.html

curl performs SSL certificate verification by default, using a "bundle"
 of Certificate Authority (CA) public keys (CA certs). If the default
 bundle file isn't adequate, you can specify an alternate file
 using the --cacert option.
If this HTTPS server uses a certificate signed by a CA represented in
 the bundle, the certificate verification probably failed due to a
 problem with the certificate (it might be expired, or the name might
 not match the domain name in the URL).
If you'd like to turn off curl's verification of the certificate, use
 the -k (or --insecure) option.
[ERROR]  000 received while testing Rancher connection. Sleeping for 5 seconds and trying again
```

**Expected Result**

node should register with rancher. 

**Screenshots**

**Additional context**

* registration command from rancher in the UI is `curl --insecure -fL https://<rancher-server>/system-agent-install.sh | sudo  sh -s - --server https://<rancher-server> --label 'cattle.io/os=linux' --token <token> --ca-checksum <checksum> --etcd --controlplane --worker`
  * also manually tried with -k, which results in the same error
* docker install for rke1 is working fine
* this setup is ~2 days old and this was working yesterday.  
* also tested on a fresh setup and encounter the same error

**Comment by thedadams** [comment] 2021-12-02 21:39
Unable to reproduce this. I have tried several different setups with different imported clusters. All of them were able to provision correctly.

**Comment by slickwarren** [comment] 2021-12-03 00:59
I was also unable to reproduce this using v2.6-head (46eb9d4)
I will leave the setup overnight and see if anything different occurs after 24 hours

**Comment by brudnak** [comment] 2021-12-03 01:26
unable to reproduce using `v2.6-46eb9d411b6afd0d75a323743adf5fddf4255219-head`

however, noticed these:

- https://github.com/rancher/windows/issues/122
- https://github.com/rancher/rancher/issues/35729

**Comment by brudnak** [comment] 2021-12-03 23:20
closing - unable to reproduce

**Closed by brudnak** 2021-12-03 23:20 UTC
Labels: status/blocker, kind/bug-qa, [zube]: QA Working, area/provisioning-rke2

**Comment by boot-vue** [comment] 2022-02-17 14:28
same problem  `2.6.3`   

private ca

self signed ssl

```bash
curl --insecure -fL https://{host}/system-agent-install.sh | sudo  sh -s - --server https://{host} --label 'cattle.io/os=linux' --token rt4krwlccw62t6tsc8z42ktqtlpn226c4nnktn9qzgkfjmwdc4v94b --ca-checksum 55a9028c0f8bf81e1754d5e37229ebe69978f7c100c267fdd41add7823bbf0bd --etcd --controlplane --worker
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 27621    0 27621    0     0  1586k      0 --:--:-- --:--:-- --:--:-- 1586k
[INFO]  Label: cattle.io/os=linux
[INFO]  Role requested: etcd
[INFO]  Role requested: controlplane
[INFO]  Role requested: worker
[INFO]  Using default agent configuration directory /etc/rancher/agent
[INFO]  Using default agent var directory /var/lib/rancher/agent
[INFO]  Determined CA is necessary to connect to Rancher
[INFO]  Successfully downloaded CA certificate
[INFO]  Value from https://{host}/cacerts is an x509 certificate
curl: (60) SSL: no alternative certificate subject name matches target host name 'xxxxxxxxxx'
More details here: https://curl.haxx.se/docs/sslcerts.html

curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.
[ERROR]  000 received while testing Rancher connection. Sleeping for 5 seconds and trying again
curl: (60) SSL: no alternative certificate subject name matches target host name 'xxxxxxx'
More details here: https://curl.haxx.se/docs/sslcerts.html

curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.
[ERROR]  000 received while testing Rancher connection. Sleeping for 5 seconds and trying again

```

**Comment by jostmart** [comment] 2022-10-06 09:09
This exact problem exist when installing on Windows servers. curl are an alias, and curl.exe does not read CA certificates from the certificate store. From what I can see, curl.exe are looking for certificates in a file on disk, parallell to where curl.exe are placed. I have tested with the latest curl.exe release and a home-rolled ca-certificates file, that works fine. But I had to modify the path to curl.exe in the install.ps1 and deploy install.ps1 file to my windows servers manually.

**Comment by UnknowViewer** [comment] 2023-07-14 14:39
The same error occurred on Kubernetes version=`1.25` and Rancher verion=`2.7.5`, but it seems not a REAL ERROR output. After executing the node join command, several ERROR msg printed but it'll keep retrying, but it turns back to normal seconds later, with nearly 5-6 ERROR retrying msg.

**Comment by tariksimsek** [comment] 2023-08-23 06:50
> The same error occurred on Kubernetes version=`1.25` and Rancher verion=`2.7.5`, but it seems not a REAL ERROR output. After executing the node join command, several ERROR msg printed but it'll keep retrying, but it turns back to normal seconds later, with nearly 5-6 ERROR retrying msg.
 
I am also having issue with same versions for rke2 and cluster is not being created

**Comment by latheefp** [comment] 2024-11-16 18:57
any solution for this issue, .i am still facing the same.


`root@proxy:~# curl --insecure -fL https://rancher.local.egrand.in/system-agent-install.sh | sudo  sh -s - --server https://rancher.local.egrand.in --label 'cattle.io/os=linux' --token nxlqdn7r49q7vpx67g4zxk4vc6jq69xdb24dx54xlwpvhgfmcfk9dz --ca-checksum 8fd0db8f802c6e4b24ddf95f5b368a8e82ba9e810ce5c96dc81dee91e5c3600d --etcd --controlplane
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 33684    0 33684    0     0  5456k      0 --:--:-- --:--:-- --:--:-- 6578k
[INFO]  Label: cattle.io/os=linux
[INFO]  Role requested: etcd
[INFO]  Role requested: controlplane
[INFO]  CA strict verification is set to true
[INFO]  Using default agent configuration directory /etc/rancher/agent
[INFO]  Using default agent var directory /var/lib/rancher/agent
[INFO]  Successfully downloaded CA certificate
[INFO]  Value from https://rancher.local.egrand.in/cacerts is an x509 certificate
curl: (60) SSL certificate problem: self-signed certificate
More details here: https://curl.se/docs/sslcerts.html

curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.
[ERROR]  000 received while testing Rancher connection. Sleeping for 5 seconds and trying again
curl: (60) SSL certificate problem: self-signed certificate
More details here: https://curl.se/docs/sslcerts.html

curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.
[ERROR]  000 received while testing Rancher connection. Sleeping for 5 seconds and trying again
curl: (60) SSL certificate problem: self-signed certificate
More details here: https://curl.se/docs/sslcerts.html

curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.
[ERROR]  000 received while testing Rancher connection. Sleeping for 5 seconds and trying again
curl: (60) SSL certificate problem: self-signed certificate
More details here: https://curl.se/docs/sslcerts.html

curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.
[ERROR]  000 received while testing Rancher connection. Sleeping for 5 seconds and trying again
curl: (60) SSL certificate problem: self-signed certificate
More details here: https://curl.se/docs/sslcerts.html`
