### ISSUE TITLE
[2.2.8] mobile  view - individual role hamburger menu not showing options

### ISSUE THREAD

**Issue by mikhail-arundo** [rancher/rancher#22933] opened 2019-09-18 20:15 UTC
Bug:
individual role hamburger menu not showing options

Screenshot:
https://screencast.com/t/sfNN1ifbVd

Chrome 76, Mohave (macOs)
Version: 2.2.8

**Comment by tfiduccia** [comment] 2019-10-09 18:50
duplicate of #16794

**Closed** 2019-10-09 18:50 UTC
