### ISSUE TITLE
UI: updating imported cluster omits localCluserAuthEndpoint, causing it to be nil

### ISSUE THREAD

**Issue by rmweir** [rancher/rancher#23913] opened 2019-11-05 21:15 UTC
**What kind of request is this (question/bug/enhancement/feature request):**
bug

**Steps to reproduce (least amount of steps as possible):**
1. create imported cluster
2. edit cluster by adding a description

**Result:**
Cluster request is sent with a cluster state that is missing the **outter** localClusterAuthEndpoint.

**Expected**:
Cluster request should contain a localClusterAuthEndpoint.

**Comment by codyrancher** [comment] 2019-11-12 23:29
@deniseschannon we're planning to not "fix" this one.

After investigating this issue I found the following:
1. localClusterAuthEndpoint is being purposefully deleted when the cluster is not RKE. This seems to be due to the fact that this feature is supposed to be an RKE only feature. (https://github.com/rancher/rancher/issues/16486)
1. Currently there isn't a good way to detect if an imported cluster is RKE or not.
1. Even though it looks like we could actually prevent the deletion without any adverse effects, we're not 100% certain. We'd like to avoid the possibility of introducing a new regression.
1. Lastly https://github.com/rancher/rancher/issues/23783 is being resolved in such a way that the side effects of our deletion won't cause a problem.

Please resolve this if you're comfortable with the above.

**Comment by deniseschannon** [comment] 2019-11-13 17:27
Since the panic is resolved in the backend and it seems the frontend is working as expected. We'll close this.

**Closed by deniseschannon** 2019-11-13 17:27 UTC
Labels: [zube]: Final Review, kind/bug, team/ui
