### ISSUE TITLE
[BUG] Cluster provisioning with non-built-in node drivers fail randomly

### ISSUE THREAD

**Issue by nnoethling** [rancher/rancher#42302] opened 2023-08-03 11:02 UTC
**Rancher Server Setup**
- Rancher version: v2.7.3
- Installation option (Docker install/Helm Chart):
   - Helm on RKE2
- Proxy/Cert Details: 
   - No proxy set

**Information about the Cluster**
- Kubernetes version: v1.25.9+rke2r1
- Cluster Type (Local/Downstream):
   - Local

**Describe the bug**

Provisioning of non-built-in node driver clusters fail sporadically and reproducible due to 404 not found error.
Rancher machine cannot download driver from rancher assets

Rancher machine pod logs:
```
Downloading driver from https://rancher-demo-27.devops.lab/assets/docker-machine-driver-otc
2023-08-03T10:57:38.816931346Z Doing /etc/rancher/ssl
2023-08-03T10:57:40.744198155Z downloaded file docker-machine-driver-otc failed sha256 checksum
2023-08-03T10:57:40.747065253Z download of driver from https://rancher-demo-27.devops.lab/assets/docker-machine-driver-otc failed
```

It seems the non-built-in node drivers are not downloaded on all pods of rancher. 
This results in 404 not found error while downloading the driver from rancher into the cluster provisioner
Missing driver can be seen the in rancher pods:

_Pod 1 (contains all drivers needed)_
```
Rancher pod 1 # ls -la  /usr/share/rancher/ui/assets | grep docker-machine
-rwxr-xr-x 1 root root 11685574 Aug  3 10:32 docker-machine-driver-cloudscale
-rwxr-xr-x 1 root root 39034880 Apr 24 15:52 docker-machine-driver-harvester
-rwxr-xr-x 1 root root  8654688 Apr 24 15:52 docker-machine-driver-linode
-rwxr-xr-x 1 root root  8749056 Aug  3 07:58 docker-machine-driver-nutanix
-rwxr-xr-x 1 root root 10715282 Aug  3 10:06 docker-machine-driver-otc
```
_Pod 2 (non-built-in drivers missing)_
```
Rancher pod 2 # ls -la  /usr/share/rancher/ui/assets | grep docker-machine
-rwxr-xr-x 1 root root 39034880 Apr 24 15:52 docker-machine-driver-harvester
-rwxr-xr-x 1 root root  8654688 Apr 24 15:52 docker-machine-driver-linode
```

Running the curl command to download the driver multiple times result in sporadic 404 errors:
```
~ curl -k https://your.rancher.domain/assets/docker-machine-driver-linode     
Warning: Binary output can mess up your terminal. Use "--output -" to tell
Warning: curl to output it to your terminal anyway, or consider "--output
Warning: <FILE>" to save to a file.
~ curl -k https://your.rancher.domain/assets/docker-machine-driver-cloudscale 
404 page not found
~ curl -k https://your.rancher.domain/assets/docker-machine-driver-cloudscale 
404 page not found
~ curl -k https://your.rancher.domain/assets/docker-machine-driver-cloudscale 
Warning: Binary output can mess up your terminal. Use "--output -" to tell
Warning: curl to output it to your terminal anyway, or consider "--output
Warning: <FILE>" to save to a file.
~ curl -k https://your.rancher.domain/assets/docker-machine-driver-cloudscale 
404 page not found
~ curl -k https://your.rancher.domain/assets/docker-machine-driver-cloudscale 
404 page not found
```

**To Reproduce**
1. Use a rancher which has multiple rancher pod replicas
2. Enable a non-built-in driver like cloudscale, nutanix or telekom cloud
3. Provision a cloud using one of this node drivers
4. See the provisioning failing as the driver download fails from your.rancher.domain/assets/...

**To Reproduce on cli**
1. Use a rancher which has multiple rancher pod replicas
2. Enable a non-built-in driver like cloudscale, nutanix or telekom cloud
3. run `curl https://your.rancher.domain/assets/docker-machine-driver-cloudscale`
4. There will sporadically appear an **404 not found** Error

**Result**

Provisioning of nodes fails sporadically as the driver cannot be downloaded from the rancher pods.

**Expected Result**

Provisioning (and driver download) should work 100% of the time

**Additional context**
To provision clusters using non-built-in node drivers, Rancher seems to download the driver to the rancher pods
Then it provides the driver binary for the provisioner under the subfolder /assets/docker-machine-driver-...

**Workaround**
A workaround can be to scale down the rancher deployment to 1 replica.
This is not what you want for an production environment.

**Comment by jakefhyde** [comment] 2023-08-03 16:43
Closing as duplicate of https://github.com/rancher/rancher/issues/38481.

**Closed by jakefhyde** 2023-08-03 16:43 UTC
Labels: kind/bug
