### ISSUE TITLE
[monitoring v2]  `pushprox-kube-etcd-client` daemonset is in crashloopbackoff, targets are down on SELinux with RPM enabled

### ISSUE THREAD

**Issue by slickwarren** [rancher/rancher#36105] opened 2022-01-11 16:12 UTC
**Rancher Server Setup**
- Rancher version: v2.6.3
- Installation option (Docker install/Helm Chart): Helm
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc):rke1
- Proxy/Cert Details: self signed certs

**Information about the Cluster**
- Kubernetes version: v1.22.5
- Cluster Type (Local/Downstream): downstream
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider): custom

**User Information**
- What is the role of the user logged in? (Admin/Cluster Owner/Cluster Member/Project Owner/Project Member/Custom)
  - If custom, define the set of permissions:
standard user, cluster owner

   
**Describe the bug**

when installing monitoring, `pushprox-kube-etcd-client` fails to complete during the install. 

**To Reproduce**
 
* bring up a 2.6.3 rancher server
* provision a downstream cluster with SElinux + RPM enabled, RHEL 8.4
* install monitoring on the cluster v100.1.0+up19.0.3

**Result**
* `pushprox-kube-etcd-client` is in `crashloopbackoff`
* checking the logs of this pod, we see that there is some permissions error `find: /etc/source/: Permission denied`

**Expected Result**

monitoring should work without errors on SELinux

**Comment by MKlimuszka** [comment] 2022-02-15 20:48
@ronhorton, I can't tell how bad this is by reading the ticket. Should this be a 2.6.4 blocker? Do you know if it is a regression?

**Comment by ronhorton** [comment] 2022-02-15 22:58
@MKlimuszka It's not happening in `2.6-head Commit ID 4d41423`
I will try to reproduce in 2.6.3

I'm running `rhel 8.4 with k8s v1.21`
Logs for `pushprox-kube-etcd-client` is running with no errors. 
![Screen Shot 2022-02-15 at 5.56.15 PM.png](https://zube.io/files/rancher/f3a5d4c70807644c19349e502d918f70-screen-shot-2022-02-15-at-5-56-15-pm.png)

**Comment by aiyengar2** [comment] 2022-02-24 03:01
> @ronhorton, I can't tell how bad this is by reading the ticket. Should this be a 2.6.4 blocker? Do you know if it is a regression?

I don't believe this code has changed since release; based on reading https://rancher.com/docs/rancher/v2.5/en/security/selinux/, which says `As of v2.5.8, the rancher-selinux RPM only contains policies for the rancher-logging application.`, I suspect we will need to fix https://github.com/rancher/rancher-selinux in order to add in policies that allow the Monitoring chart to grab certs from `/etc/kubernetes/ssl` to be used by PushProx to scrape etcd.

I'm not sure if this falls under `team/area3` work @MKlimuszka @SheilaghM, but I will look into it tomorrow. Reaching out to @cmurphy for more context.

**Comment by aiyengar2** [comment] 2022-03-01 18:04
Note: in order to see the fixes introduced by the PRs above, you will need to manually set `global.seLinux.enabled=true` on the Helm chart and ensure your etcd nodes have downloaded the rancher-selinux RPM that contains the fixes shipped in https://github.com/rancher/rancher-selinux/pull/11.

**Comment by ronhorton** [comment] 2022-03-04 16:24
This is still happening with `2.6-head Commit ID 8ece6ae`

1. created downstream rhel cluster ami-0ecaf76771eb5cb31
2. installed monitoring v2

pushprox-kube-etcd-client is in crashloop 
![Screen Shot 2022-03-04 at 11.20.54 AM.png](https://zube.io/files/rancher/abb7553882a99e5e4b8d618fdcc5762d-screen-shot-2022-03-04-at-11-20-54-am.png)

**Comment by aiyengar2** [comment] 2022-03-04 16:56
This issue will be blocked from testing until we cut a tag in https://github.com/rancher/rancher-selinux.

Currently, it also seems like Drone builds are failing on CentOS 8 in a flakey manner as seen in https://drone-publish.rancher.io/rancher/rancher-selinux/61, which is preventing us from cutting a tag.

A fix seems to be proposed in https://github.com/rancher/rancher-selinux/pull/10/commits/d6f016f703d1c255b74229cd25e32729afd74bd2 that will make the builds more reliable. Once that is merged, we will cut a tag, at which point QA will be unblocked for testing.

**Comment by cmurphy** [comment] 2022-03-04 17:46
`v0.3-rc1.testing.1` is tagged and available from the testing RPM repo.

**Comment by ronhorton** [comment] 2022-03-10 13:33
**rejected** Tested in `2.6-head Commit ID f2a4147` with `v0.3-rc1.testing.1`

1. created rhel machines in ec2
2. ran bash snippet to use testing repo
3. ran yum rpm command `Upgraded: rancher-selinux-0.3~rc1-1.el8.noarch`
4. imported cluster to rancher
5. installed monitoring

`pushprox-kube-etcd-client immediately went into crashloop`

**Comment by ronhorton** [comment] 2022-03-10 23:33
**Pass** verified in `v2.6.4-rc8`

1. created rhel machines in ec2
2. ran bash snippet to use testing repo
3. ran yum rpm command `Upgraded: rancher-selinux-0.3~rc1-1.el8.noarch`
4. imported cluster to rancher
5. installed monitoring
6. changed monitoring yaml to selinux enabled: true (default is false)

`pushprox-kube-etcd-client daemonset no longer goes into crashloop`

**Closed** 2022-03-10 23:34 UTC
Labels: status/blocker, priority/0, kind/bug-qa, area/monitoring, [zube]: QA Working, team/area3
