### ISSUE TITLE
longhorn multi-cluster app - longhorn should be deployed to longhorn-system namespace.

### ISSUE THREAD

**Issue by meldafrawi** [rancher/rancher#19803] opened 2019-04-24 22:44 UTC
**What kind of request is this (question/bugt):** 

bug

**Steps to reproduce (least amount of steps as possible):**

deploy longhorn as multi-cluster app

**Result:**

namespace with name longhorn-**prefix** .

**Other details that may be helpful:**

the namespace should be named **longhorn-system**

**Environment information**

- Rancher version: v2.2.2
- Installation option: single node

**Cluster information**

- Cluster type: Imported
- Machine type: cloud
- Kubernetes version:
```
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.0", GitCommit:"641856db18352033a0d96dbc99153fa3b27298e5", GitTreeState:"clean", BuildDate:"2019-03-25T15:53:57Z", GoVersion:"go1.12.1", Compiler:"gc", Platform:"linux/amd64"}

Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.5", GitCommit:"2166946f41b36dea2c4626f90a77706f426cdea2", GitTreeState:"clean", BuildDate:"2019-03-25T15:19:22Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}

```

- Docker version (use `docker version`):

```
Client:
 Version:           18.09.5
 API version:       1.39
 Go version:        go1.10.8
 Git commit:        e8ff056
 Built:             Thu Apr 11 04:43:57 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.5
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.8
  Git commit:       e8ff056
  Built:            Thu Apr 11 04:10:53 2019
  OS/Arch:          linux/amd64
  Experimental:     false
```

**Comment by yasker** [comment] 2019-04-24 23:04
@alena1108 pointed me to https://github.com/rancher/rancher/issues/17913

**Comment by yasker** [comment] 2019-04-24 23:06
Linked to https://github.com/rancher/longhorn/issues/487

**Comment by alena1108** [comment] 2019-04-30 19:08
@yasker 
> pointed me to #17913 , though not sure if it's the exactly same

It is exactly the same issue. Once the fix for 17913 is in, you would be able to specify a namespace. If the namespace exists, it will be used. If not, it will be created. Closing as a duplicate of #17913.

**Closed by alena1108** 2019-04-30 19:08 UTC
