### ISSUE TITLE
etcd backup | error taking a snapshot on a custom rke1 RHEL 8.4 cluster

### ISSUE THREAD

**Issue by sgapanovich** [rancher/rancher#36812] opened 2022-03-09 01:27 UTC
**(!)** _couldn't reproduce it with new custom RKE1 RHEL 8.4 clusters using 1.20.15 and 1.21.9 k8s_

**Rancher Server Setup**
- Rancher version: v2.6-head bb75b06
- Installation option (Docker install/Helm Chart): Helm
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): rke1
- Proxy/Cert Details:

**Information about the Cluster**
- Kubernetes version: 1.21.9 
- Cluster Type (Local/Downstream): Downstream
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider): custom rke1 RHEL 8.4 

  
**Describe the bug**

Snapshot (etcd backup) fails (automatic and manual) with the following errors logged

```
2022/03/08 23:39:12 [WARNING] [etcd] Failed to take one-time snapshot on host [REDACTED], exit code [1]: time="2022-03-08T23:39:12Z" level=fatal msg="exit status 1: {\"level\":\"warn\",\"ts\":\"2022-03-08T23:39:12.243Z\",\"caller\":\"clientv3/retry_interceptor.go:62\",\"msg\":\"retrying of unary invoker failed\",\"target\":\"endpoint://client-c1b020a6-230b-41f1-9b91-376af4a0e0d9/REDACTED:2379\",\"attempt\":0,\"error\":\"rpc error: code = DeadlineExceeded desc = context deadline exceeded\"}\nREDACTED:2379 is unhealthy: failed to commit proposal: context deadline exceeded\nError: unhealthy cluster\n"

2022/03/08 23:39:12 [ERROR] error syncing 'c-bcg85/c-bcg85-rl-987b7': handler etcdbackup-controller: [etcd-backup] failed to perform etcd backup: failed to perform etcd backup: timed out waiting for the condition, requeuing
2022/03/09 00:02:50 [ERROR] Unknown error: Operation cannot be fulfilled on preferences.management.cattle.io "cluster": the object has been modified; please apply your changes to the latest version and try again

```

**To Reproduce**
 
1. Provision a custom rke1 RHEL 8.4 cluster
2. One snapshot is taken automatically (it errored out)
3. Take a snapshot manually

**Result**
Snapshot errors out with time out

**Expected Result**

Snapshot is taken and saved 

**Screenshots**

![screen](https://user-images.githubusercontent.com/40282141/157353597-42fe414e-72cf-4b8e-bf72-1103e3a3f549.jpg)

**Comment by snasovich** [comment] 2022-03-09 22:20
@sgapanovich , is this reproducible on 2.6.3?
cc: @sowmyav27

**Comment by sgapanovich** [comment] 2022-03-09 23:25
@snasovich i left a comment in the issue that it wasn't reproducible even in the same cluster with the same setup 
```
(!) couldn't reproduce it with new custom RKE1 RHEL 8.4 clusters using 1.20.15 and 1.21.9 k8s
```
I haven't tried on 2.6.3

**Comment by sowmyav27** [comment] 2022-03-10 02:15
@sgapanovich Can you validate on 2.6.3 to see if its a regression or not ?

**Comment by sgapanovich** [comment] 2022-03-10 21:40
@snasovich couldn't reproduce the issue in 2.6.3 with 4 RHEL 8.7 clusters ( 1.19 1.20 1.21 1.22 k8s versions )
tried manually and automatic snapshot
![clusters](https://user-images.githubusercontent.com/40282141/157759238-d4b8d286-263f-4e26-a2d2-5c96869bda84.jpg)


was not able to create a 1.18 RHEL 8.7 custom cluster and created an issue since it persists in 2.6-head https://github.com/rancher/rancher/issues/36844

**Comment by snasovich** [comment] 2022-03-10 22:30
Moving to 2.6.5 milestone as it didn't happen on 2.6-head retest, so might be one-time setup issue. Will try to repro again as part of work on 2.6.5.

**Comment by Josh-Diamond** [comment] 2022-04-04 18:42
Ticket #36812 - Test Results

Note - Unable to test on RHEL 8.4 with k8s `v1.18.20`; Blocked by #36844:
 `v2.6.3`
<img width="1284" alt="RHEL-2 6 3-118-failure" src="https://user-images.githubusercontent.com/46494969/161596135-55da2c50-8a4a-4d15-8365-249241761699.png">

`v2.6-30344dbefa64aadcb2346c39f9bd8896dda6e7fc-head`:
<img width="1372" alt="RHEL-2 6-head-118-failure" src="https://user-images.githubusercontent.com/46494969/161609677-2a992fd5-b3f4-42bf-b4ea-08624bd9c7a0.png">



Reproduction Failure - with Helm on rancher `v2.6.3`:
1. Fresh install of rancher `v2.6.3`
2. Provision downstream RKE1 Custom RHEL 8.4 with k8s `v1.19.16`
3. Provision downstream RKE1 Custom RHEL 8.4 with k8s `v1.20.15`
4. Provision downstream RKE1 Custom RHEL 8.4 with k8s `v1.21.10`
5. Once provisioned, take a manual snapshot of each cluster
6. Reproduction Failure - All snapshots successfully captured

Screenshots:

K8s `v1.19.16`:
<img width="1288" alt="RHEL-2 6 3-119-success" src="https://user-images.githubusercontent.com/46494969/161597319-7cd39aea-8051-4dea-83b7-cb3adf1a23c9.png">


K8s `v1.20.15`:
<img width="1289" alt="RHEL-2 6 3-120-success" src="https://user-images.githubusercontent.com/46494969/161597408-d6107bc5-9921-4140-b944-4447e239c6ff.png">


K8s `v1.21.10`:
<img width="1291" alt="RHEL-2 6 3-121-success" src="https://user-images.githubusercontent.com/46494969/161597460-57bbda5e-3763-4206-af47-c5ce3aec82a9.png">



Verified - with Helm on rancher `v2.6-30344dbefa64aadcb2346c39f9bd8896dda6e7fc-head`:
1. Fresh install of rancher `v2.6-head`
2. Provision downstream RKE1 Custom RHEL 8.4 with k8s `v1.19.16`
3. Provision downstream RKE1 Custom RHEL 8.4 with k8s `v1.20.15`
4. Provision downstream RKE1 Custom RHEL 8.4 with k8s `v1.21.10`
5. Provision downstream RKE1 Custom RHEL 8.4 with k8s `v1.22.7`
6. Once provisioned, take a manual snapshot of each cluster
7. Verified - All snapshots successfully captured

Screenshots:

K8s `v1.19.16`:
<img width="1372" alt="RHEL-2 6-head-119-success" src="https://user-images.githubusercontent.com/46494969/161609851-986f849e-b23a-4611-a01e-92153cc066bc.png">


K8s `v1.20.15`:
<img width="1370" alt="RHEL-2 6-head-120-success" src="https://user-images.githubusercontent.com/46494969/161609994-8c682c11-d61e-4e68-99fb-00febf19b0e4.png">


K8s `v1.21.10`:
<img width="1372" alt="RHEL-2 6-head-121-success" src="https://user-images.githubusercontent.com/46494969/161610051-9fd117ce-efd2-4284-bbc2-8183bed8bca6.png">


K8s `v1.22.7`:
<img width="1374" alt="RHEL-2 6-head-122-success" src="https://user-images.githubusercontent.com/46494969/161610088-c332ef78-fea4-4436-b68f-c77233f62092.png">


Additional information:
Will resume testing on RHEL 8.4 with K8s `v1.18.20` when unblocked by #36844

**Comment by slickwarren** [comment] 2022-04-13 20:44
we can close this since everything was validated minus 1.18 k8s. we can test this in the linked ticket above.

**Closed by slickwarren** 2022-04-13 20:44 UTC
Labels: area/etcd, kind/bug-qa, team/area2, [zube]: Blocked
