### ISSUE TITLE
Upgrading services (UI): if a service is set to always run 1 container per host, then only 1 (total) replacement container is launched.

### ISSUE THREAD

**Issue by ebr** [rancher/rancher#2522] opened 2015-11-03 16:19 UTC
Steps to reproduce:

  - create a service with an option to "always run 1 container per host"
    - (i am setting service's affinity to a host label - have not tested if this is relevant)
  - launch the service on >1 hosts
  - upgrade the service via web UI (not sure if rancher-cli is similarly affected; likely not)
  - only 1 new container is started
  - all other containers of the service are stopped.
  - upon "completing" the upgrade, all other containers are cleaned up, only 1 container remains, regardless of original scale
  - manually scaling up works to recover from the issue, but then the `io.rancher.scheduler.global: 'true'` label is removed from the service, the scale is set to a manual value, and there isn't a way to revert it to run 1 container per host, since this option is not settable during an upgrade or just by editing the service.

**Comment by vincent99** [comment] 2015-11-03 17:20
Duplicate of https://github.com/rancher/rancher/issues/2459, fixed in master

**Closed by vincent99** 2015-11-03 17:20 UTC
