### ISSUE TITLE
Adding private registry in GUI prone to causing cluster creation issues

### ISSUE THREAD

**Issue by janeczku** [rancher/rancher#19325] opened 2019-04-02 10:29 UTC
**What kind of request is this (question/bug/enhancement/feature request):**
Enhancement

**Steps to reproduce (least amount of steps as possible):**
1. Click on Add Cluster
2. Select EC2 or other node driver
3. Enter Cluster name
4. Configure node pool
5. Click Show Advanced Options -> Private Registries
6. Click Add Private Registry
7. Enter URL and credentials for private registry where user application images are stored
8. Remove checkbox for "default registry"
9. Click Create
10. Note the validation error that says "You need to make one registry the default".
11. Re-enable the checkbox for "default registry".
12. Click Create

**Result:**
Cluster creation fails because RKE tries to pull the images from the private registry.

<img width="1392" alt="Screenshot 2019-04-02 at 12 08 00" src="https://user-images.githubusercontent.com/3813921/55395897-e03ff080-5542-11e9-841f-20862d5321e8.png">

The first private registry entered in GUI defaults to being the `system default registry`.

<img width="1390" alt="Screenshot 2019-04-02 at 12 08 59" src="https://user-images.githubusercontent.com/3813921/55395885-d6b68880-5542-11e9-85f8-2afa58b89f13.png">

User is forced to mark a registry as `default registry` even though he might not want system images being pulled from his private registry.

<img width="1397" alt="Screenshot 2019-04-02 at 12 59 49" src="https://user-images.githubusercontent.com/3813921/55398112-04ea9700-5548-11e9-8265-e70ee9e82e2d.png">

**Expected Result:**

1. When adding a private registry in GUI the `Default Registry` checkbox should not default to being enabled.

2. User should not be forced to mark a registry as `Default Registry` in order to create the cluster.

3. The `Default Registry` option header should be changed to clarify the ramifications of this option. Users that are unfamiliar with underlying RKE configuration concepts, find it unexpected that checking this box means that they will ensure RKE system images are made available in that registry. Suggestions:
- `System Default Registry` (matching the name of the corresponding global setting)
- `Default Registry for System Images`
- `RKE Image Registry`

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): v2.2.0

**Comment by davidnuzik** [comment] 2019-04-17 18:16
Version: Master (4/17/19)

The Private Registries section has been refactored.

Now when you create a cluster and expand the "Private Registries" pane you will see the following (when add private registry):
![image](https://user-images.githubusercontent.com/45179589/56310797-90942400-6101-11e9-8efc-9ef84837ea8d.png)

Now, "System Default Registry" is UNCHECKED by default. Notice it is renamed too -- it used to just be called "Default Registry".

However, I tried creating a cluster with fake url, user, password (and leave System Default Registry unchecked) and now I see that we don't send `privateRegistries` at all in the config (rancherKubernetesEngineConfig)

Here's how it worked in v2.2.1 when I put in a fake entry (not actual private registry):
![image](https://user-images.githubusercontent.com/45179589/56310948-d05b0b80-6101-11e9-91d8-ce2b50a3cbf8.png)

And here is what I see in master (notice that `privateRegistries` is completely missing:
![image](https://user-images.githubusercontent.com/45179589/56310983-e4067200-6101-11e9-9aa6-6b70806e41ca.png)

Perhaps this was expected because my private registry was fake? Even if so I would expect the UI to notify me. It is concerning that we did not send a privateRegistry entry at all. I do not think this is expected and will reopen the issue.

Note, when I inspect the API there is no private registry entry as well (UI never sent it).

**Comment by davidnuzik** [comment] 2019-04-17 18:17
The schema appears correct to me.
```
{
"baseType": "schema",
"id": "privateRegistry",
"links": {
"self": "…/v3/schemas/privateRegistry"
},
"pluralName": "privateRegistries",
"resourceFields": {
"isDefault": {
"create": true,
"default": false,
"type": "boolean",
"update": true
},
"password": {
"create": true,
"nullable": true,
"type": "password",
"update": true
},
"url": {
"create": true,
"nullable": true,
"type": "string",
"update": true
},
"user": {
"create": true,
"nullable": true,
"type": "string",
"update": true
}
},
"type": "schema",
"version": {
"group": "management.cattle.io",
"path": "/v3",
"version": "v3"
}
}
```

**Comment by davidnuzik** [comment] 2019-04-19 20:33
Version: Master 4/19/19

Confirmed this is now fixed. We are including prviateRegistries in the config now when we create a cluster. I did still notice though that when I submit with a fake URL it appears to be looking for system images. Since both the UI appear correct and the API appear correct my guess is this is some backend issue.

```
privateRegistries: [{isDefault: false, type: "privateRegistry", url: "https://test1.test.com",…}]
0: {isDefault: false, type: "privateRegistry", url: "https://test1.test.com",…}
isDefault: false
password: "supersecret"
type: "privateRegistry"
url: "https://test1.test.com"
user: "davidnuzik"
```

![image](https://user-images.githubusercontent.com/45179589/56443027-a2afc700-62a7-11e9-8a5c-70fba44566f3.png)

**Comment by davidnuzik** [comment] 2019-04-19 22:44
Created issue #19734 to track the issue we are seeing from the backend per my comment above. The backend should not be trying to pull system images as we have not set the cluster private registry as default.

#19734 needs to be fixed before I can validate and close this UI issue.

**Comment by jira-sync-svc** [comment] 2019-04-25 20:23
➤ David Nuzik commented:

Closed blocking issue #19734 (Github) it is actually a non-issue and is not blocking.

**Comment by jira-sync-svc** [comment] 2019-04-29 20:21
➤ David Nuzik commented:

Questions:
Why can we have non-default registry?
Why can we have multiple registries?

Note:
We should always pull system-images for this registry. This is expected.

**Comment by janeczku** [comment] 2019-04-29 22:31
My understanding is that the cluster registries setting in the GUI is the equivalent to the private_registries config stanza in RKE.

According to the documentation the expected behavior for private_registries is:

- Adding a non-default registry configures all nodes in the cluster such that they are able to pull images from the private registry. This would include pulling images for workloads pertaining to projects that don’t have a project-level registry configuration. System images will not be pulled from a non-default registry.

- Specifying a default registry makes it so that system images are pulled from that registry instead of Docker Hub.

> RKE supports the ability to configure multiple private Docker registries. By passing in your registry and credentials, it allows the nodes to pull images from these private registries.

> RKE supports specifying a default registry from the list of private registries to be used with all system images .

https://rancher.com/docs/rke/latest/en/config-options/private-registries/

**Comment by janeczku** [comment] 2019-04-29 22:35
If thats not the expected behavior we need to fix documentation and GUI copy to make clear that these registries are exclusively used for system images. And that they are not the cluster level equivalent to project registries (what most users currently think it is).

**Comment by alena1108** [comment] 2019-05-02 20:06
Although RKE supports supplying multiple private registries, it is really an overhead to do the same from Rancher UI. Having multiple registries on RKE was mostly to address the case when part of the addons are coming from registry1, and another part from registry2. Based on the fact that:

* The registry is used for system images only
* In the majority of the use cases, the system images are stored in one registry (usually mirrored from rancher repo where **all** system images are stored)

it would make sense to
* let user configure only one private registry per cluster
* Make it a default by default
* Put a helper comment in the UI indicating how this registry is going to be used (for system images only)

@westlywright @janeczku thoughts?

**Comment by janeczku** [comment] 2019-05-02 21:34
I agree with the suggestion from @alena1108 
I haven't yet seen a use case where Rancher system images are mirrored across multiple private registries, so changing this 1 configurable system registry per cluster would make sense. 

On a related note: There is also a global "default system registry" setting and its unclear what the relationship with the cluster default registry would be.

**Comment by westlywright** [comment] 2019-05-02 21:34
> let user configure only one private registry per cluster

The UI currently has this restriction

> Make it a default by default

UI changed the label to add clarification that Default was going to be used for system images and we removed this restriction of the Default being on by Default.  

> Put a helper comment in the UI indicating how this registry is going to be used (for system images only)

UI changed the checkbox label to `System Default Registry`

@alena1108 After reading through the docs and @janeczku comments I think we should make a change here. I think the label should be changed back to `Default Registry`. My understanding is default does not equate to system images only but  system images as well as being one of the places RKE will look for non-system images as well. Is my understanding correct?  

I agree we should add some clarification to the UI copy, in the header of the private registries component, that explains the difference between the two. The copy doesn't need to be very in depth but if my understanding above is correct then something to that effect would suffice.

**Comment by janeczku** [comment] 2019-05-02 22:10
@westlywright 

> My understanding is default does not equate to system images only but system images as well as being one of the places RKE will look for non-system images as well

AFAIK, the private registry settings (default or not) will only ever be applied to images pulled/deployed by RKE (aka system images).
When there is a registry marked as default, RKE will rewrite *all* system images configured under the `system_images` stanza by simply prepending the default registry hostname to the image. E.g. `rancher/rke-tools:v0.1.24` becomes `private.registry.com:5000/rancher/rke-tools:v0.1.24`

This also shows that we actually have to make the 'default' option a user configurable
setting. Otherwise we would break stuff when user has customised `system_images` in the cluster yaml with fully qualified images that already have the registry hostname.

e.g. given user has a cluster yaml like so
```
system_images:
  etcd: private.registry.com:5000/rancher/coreos-etcd:v3.2.24
  alpine: private.registry.com:5000/rancher/rke-tools:v0.1.24
```

If we were to defaulting to the single private registry to default, then RKE would rewrite these images to invalid names like  `private.registry.com:5000/private.registry.com:5000/rancher/coreos-etcd:v3.2.24`.

https://github.com/rancher/rke/blob/471146b25ca8293c90779c3fa58ecc4bbfaae21f/cluster/defaults.go#L344-L349

**Comment by alena1108** [comment] 2019-05-04 04:00
@janeczku @westlywright 

> This also shows that we actually have to make the 'default' option a user configurable
setting. Otherwise we would break stuff when user has customised system_images in the cluster yaml with fully qualified images that already have the registry hostname.

Custom system images are not allowed to be passed from Rancher API (or yml) today. They can are being injected by the provisioner code internally. But lets say in the future we let user pass [custom system images via yaml](https://github.com/rancher/rancher/issues/18029):  in this case, he can modify private registries from the yml as well, and drop the default flag or/and and additional private registry(ies).

Given the above, I think it's fine for now to make the only one private registry the UI is going to set, to be default.

> On a related note: There is also a global "default system registry" setting and its unclear what the relationship with the cluster default registry would be.

The registry set on a cluster level should override the global level registry. If cluster level registry is not passed, the one from the global level should be derived.

**Comment by janeczku** [comment] 2019-05-06 10:01
I think what @alena1108  suggested is fine then. Wasn't aware of the fact that we do not allow passing custom system images via yml. According to our docs we actually support *any* cluster yml options, so I am opening a ticket to fix the doc issue.
> Using a config file allows you to set any of the options available in an RKE installation.

https://rancher.com/docs/rancher/v2.x/en/cluster-provisioning/rke-clusters/options/#config-file

**Comment by davidnuzik** [comment] 2019-05-06 16:18
If we are going to fix this to only allow 1 private registry and it therefore is default we should of course also just remove the default checkbox completely in my opinion -- or if we think it should be there then we can just disable it suppose but that seems a little odd to me. Also this begs the question why is this even an option in the API (default option)?
```
isDefault": {
"create": true,
"default": false,
"type": "boolean",
"update": true
},
```

If we're not sure if cluster registry overrides default system registry -- shouldn't we find out? And shouldn't there be helper text in the UI to explain this? Will this possibly confuse any end-users? I think it needs to be very clear what/how the system default registry, cluster registry, project registry works (and which has precedence, etc) if not in the UI then in docs.

**Comment by davidnuzik** [comment] 2019-05-20 21:19
Version: Master (v2.3) (5/20/19)

I can confirm this is fixed in the UI now. Now you have a radio button option to pick if you are enabling a private registry for the cluster or not with the default of course being disabled. There is helper text that explains all images required for cluster provisioning will be pulled from the registry. We hope this will make it much more clear.

![image](https://user-images.githubusercontent.com/45179589/58052302-51466200-7b09-11e9-8276-1e7f3033cc3b.png)

When Enabled:
![image](https://user-images.githubusercontent.com/45179589/58052323-5e635100-7b09-11e9-9aa8-f4624562804b.png)

Inspecting the http and API looks good. We weren't setting isDefault to true before and now are doing this in the UI (we are overriding default in the API which is false).
```
privateRegistries: [{isDefault: true, type: "/v3/schemas/privateRegistry", url: "https://test.com", user: "testuser"}]
0: {isDefault: true, type: "/v3/schemas/privateRegistry", url: "https://test.com", user: "testuser"}
isDefault: true
type: "/v3/schemas/privateRegistry"
url: "https://test.com"
user: "testuser"
```

You may have noticed that we still have "Private Registries" plural. I have opened a separate issue for this because it's a simple fix in en-us translations and not directly related to the main issue here. See https://github.com/rancher/rancher/issues/20343

**Closed by davidnuzik** 2019-05-20 21:19 UTC
Labels: [zube]: To Test, area/rke, area/ui, kind/enhancement, status/reopened, status/resolved, status/to-test, status/triaged, team/az
