### ISSUE TITLE
panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by jippi** [rancher/rancher#2932] opened 2015-12-06 12:10 UTC
Using `rancher/server:v0.49.0-rc1`

```
time="2015-12-06T12:09:03Z" level=info msg="Initializing event router" workerCount=10
time="2015-12-06T12:09:03Z" level=info msg="Connection established"
time="2015-12-06T12:09:15Z" level=info msg="Creating Machine" eventId="bdb34231-4a18-4ece-98bf-248df96f384b" resourceId=1ph3
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x80 pc=0x497616]

goroutine 49 [running]:
github.com/rancher/go-machine-service/handlers.CreateMachine(0xc8203d6000, 0xc8200be000, 0x0, 0x0)
	/source/gopath/src/github.com/rancher/go-machine-service/handlers/create.go:42 +0x3e6
github.com/rancher/go-machine-service/events.(*Worker).DoWork(0xb6a080, 0xc82038a000, 0x386, 0x600, 0xc820490e70, 0xc8200be000, 0xc8203e8480)
	/source/gopath/src/github.com/rancher/go-machine-service/events/listener.go:197 +0x7c2
created by github.com/rancher/go-machine-service/events.(*EventRouter).run
	/source/gopath/src/github.com/rancher/go-machine-service/events/listener.go:142 +0xa33

goroutine 1 [IO wait]:
net.runtime_pollWait(0x7faa5c592480, 0x72, 0xc82000a140)
	/usr/local/go/src/runtime/netpoll.go:157 +0x60
net.(*pollDesc).Wait(0xc8200cc1b0, 0x72, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:73 +0x3a
net.(*pollDesc).WaitRead(0xc8200cc1b0, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:78 +0x36
net.(*netFD).Read(0xc8200cc150, 0xc8203cd000, 0x1000, 0x1000, 0x0, 0x7faa5c58a050, 0xc82000a140)
	/usr/local/go/src/net/fd_unix.go:232 +0x23a
net.(*conn).Read(0xc8200ce008, 0xc8203cd000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/net.go:172 +0xe4
bufio.(*Reader).fill(0xc8204181e0)
	/usr/local/go/src/bufio/bufio.go:97 +0x1e9
bufio.(*Reader).Read(0xc8204181e0, 0xc820492040, 0x2, 0x8, 0xc82038a200, 0x0, 0x0)
	/usr/local/go/src/bufio/bufio.go:207 +0x260
github.com/gorilla/websocket.(*Conn).readFull(0xc8204c20f0, 0xc820492040, 0x2, 0x8, 0x0, 0x0)
	/source/Godeps/_workspace/src/github.com/gorilla/websocket/conn.go:542 +0xa9
github.com/gorilla/websocket.(*Conn).advanceFrame(0xc8204c20f0, 0x600, 0x0, 0x0)
	/source/Godeps/_workspace/src/github.com/gorilla/websocket/conn.go:566 +0x159
github.com/gorilla/websocket.(*Conn).NextReader(0xc8204c20f0, 0xc8200b9ad0, 0x0, 0x0, 0x0, 0x0)
	/source/Godeps/_workspace/src/github.com/gorilla/websocket/conn.go:706 +0x76
github.com/gorilla/websocket.(*Conn).ReadMessage(0xc8204c20f0, 0x9ccb88, 0x0, 0x0, 0x0, 0x0, 0x0)
	/source/Godeps/_workspace/src/github.com/gorilla/websocket/conn.go:769 +0x55
github.com/rancher/go-machine-service/events.(*EventRouter).run(0xc8204c87e0, 0x0, 0xc8200b9d70, 0x19, 0x0, 0x0)
	/source/gopath/src/github.com/rancher/go-machine-service/events/listener.go:129 +0x8d9
github.com/rancher/go-machine-service/events.(*EventRouter).Start(0xc8204c87e0, 0x0, 0x0, 0x0)
	/source/gopath/src/github.com/rancher/go-machine-service/events/listener.go:54 +0xe3
main.main()
	/source/main.go:41 +0x838

goroutine 5 [chan receive]:
github.com/rancher/go-machine-service/locks.locker()
	/source/gopath/src/github.com/rancher/go-machine-service/locks/locks.go:61 +0xda
created by github.com/rancher/go-machine-service/locks.init.1
	/source/gopath/src/github.com/rancher/go-machine-service/locks/locks.go:7 +0x59

goroutine 21 [IO wait]:
net.runtime_pollWait(0x7faa5c592600, 0x72, 0xc82000a140)
	/usr/local/go/src/runtime/netpoll.go:157 +0x60
net.(*pollDesc).Wait(0xc8200cc290, 0x72, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:73 +0x3a
net.(*pollDesc).WaitRead(0xc8200cc290, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:78 +0x36
net.(*netFD).Read(0xc8200cc230, 0xc82011c000, 0x1000, 0x1000, 0x0, 0x7faa5c58a050, 0xc82000a140)
	/usr/local/go/src/net/fd_unix.go:232 +0x23a
net.(*conn).Read(0xc8200ce020, 0xc82011c000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/net.go:172 +0xe4
net/http.noteEOFReader.Read(0x7faa5c5928b0, 0xc8200ce020, 0xc8200ea058, 0xc82011c000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/http/transport.go:1370 +0x67
net/http.(*noteEOFReader).Read(0xc8200c8500, 0xc82011c000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	<autogenerated>:126 +0xd0
bufio.(*Reader).fill(0xc8200d85a0)
	/usr/local/go/src/bufio/bufio.go:97 +0x1e9
bufio.(*Reader).Peek(0xc8200d85a0, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/bufio/bufio.go:132 +0xcc
net/http.(*persistConn).readLoop(0xc8200ea000)
	/usr/local/go/src/net/http/transport.go:876 +0xf7
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:685 +0xc78

goroutine 22 [select]:
net/http.(*persistConn).writeLoop(0xc8200ea000)
	/usr/local/go/src/net/http/transport.go:1009 +0x40c
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:686 +0xc9d
time="2015-12-06T12:09:17Z" level=info msg="Setting log level" logLevel=info
time="2015-12-06T12:09:17Z" level=info msg="Starting go-machine-service..." gitcommit="a542649"
time="2015-12-06T12:09:19Z" level=info msg="Initializing event router" workerCount=10
time="2015-12-06T12:09:19Z" level=info msg="Connection established"
``

**Comment by deniseschannon** [comment] 2015-12-06 16:17
Duplicate of #2925

**Closed by deniseschannon** 2015-12-06 16:17 UTC
