### ISSUE TITLE
Not able start containers on one of the hosts. Container stuck in "networking" state.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#1279] opened 2015-06-18 01:24 UTC
Server version - V0.24.0

I am having my server up and running for the last couple of days and did not have any problems with deploying containers on all the 3 hosts.

Now i see that containers do not start on one of the hosts and they are stuck in "networking" state forever.

server logs:

```
2015-06-18 01:23:29,888 DEBUG [b632ee2a-0a70-4b4d-baab-57acf29e35b5:40818] [instance:1124->nic:1117] [instance.start->(InstanceStart)->nic.activate->(AgentInstanceApplyItems)] [] [orService-15457] [i.c.p.e.memory.InMemoryEventService ] Subscribing to [reply.1023549831396078860] 
2015-06-18 01:23:30,007 INFO  [:] [] [] [] [orService-15448] [.p.c.v.i.ConfigItemStatusManagerImpl] Failed update [configscripts, services, agent-instance-scripts, monit, agent-instance-startup, node-services, ipsec, healthcheck, ipsec-hosts, hosts, iptables, healthcheck] on [agent:4], exit code [122] output [Lock failed] 
2015-06-18 01:23:30,407 DEBUG [:] [] [] [] [ecutorService-4] [i.c.p.e.memory.InMemoryEventService ] Subscribing to [reply.1880279993338241397] 
2015-06-18 01:23:30,407 DEBUG [:] [] [] [] [ecutorService-4] [i.c.p.e.memory.InMemoryEventService ] Subscribing to [reply.4229095503167041183] 
2015-06-18 01:23:30,407 DEBUG [:] [] [] [] [ecutorService-4] [i.c.p.e.memory.InMemoryEventService ] Subscribing to [reply.5228646090445904128] 
2015-06-18 01:23:30,409 DEBUG [:] [] [] [] [orService-15430] [i.c.p.e.memory.InMemoryEventService ] Subscribing to [reply.7079087477302877788] 
2015-06-18 01:23:30,410 DEBUG [:] [] [] [] [orService-15430] [i.c.p.e.memory.InMemoryEventService ] Subscribing to [reply.7474412938204754412] 
2015-06-18 01:23:30,410 DEBUG [:] [] [] [] [orService-15454] [i.c.p.e.memory.InMemoryEventService ] Subscribing to [reply.8983018701297129234] 
2015-06-18 01:23:30,884 INFO  [:] [] [] [] [orService-15459] [i.c.p.a.s.s.impl.AgentServiceImpl   ] Timeout waiting for response to [config.update] id [ac690df9-3c33-4064-8c2c-0022a87c9e65] 
2015-06-18 01:23:30,885 INFO  [:] [] [] [] [orService-15430] [i.c.p.a.s.s.impl.AgentServiceImpl   ] Timeout waiting for response to [delegate.request] id [45d77e23-a02b-4398-b4e5-e4567adb4d5e] 
2015-06-18 01:23:31,884 INFO  [:] [] [] [] [orService-15448] [.p.c.v.i.ConfigItemStatusManagerImpl] Timeout updating item(s) [healthcheck, ipsec-hosts, hosts, iptables] on [agent:4] 
2015-06-18 01:23:31,885 INFO  [:] [] [] [] [orService-15430] [i.c.p.a.s.s.impl.AgentServiceImpl   ] Timeout waiting for response to [delegate.request] id [72c83c98-662c-48fd-9bc9-e8d77e2749ba] 
2015-06-18 01:23:31,885 INFO  [:] [] [] [] [orService-15457] [i.c.p.a.s.s.impl.AgentServiceImpl   ] Timeout waiting for response to [config.update] id [e096b75f-bb0c-40cf-88f0-80764f3733e5] 
^X2015-06-18 01:23:33,885 INFO  [:] [] [] [] [orService-15457] [.p.c.v.i.ConfigItemStatusManagerImpl] Waiting on [agent:4] on [healthcheck], not in sync requested [2323] != applied [2285] 
2015-06-18 01:23:33,885 INFO  [:] [] [] [] [orService-15457] [.p.c.v.i.ConfigItemStatusManagerImpl] Waiting on [agent:4] on [ipsec-hosts], not applied requested [1181] > applied [1158] 
2015-06-18 01:23:33,885 INFO  [:] [] [] [] [orService-15457] [.p.c.v.i.ConfigItemStatusManagerImpl] Waiting on [agent:4] on [hosts], not applied requested [2457] > applied [2419] 
2015-06-18 01:23:33,885 INFO  [:] [] [] [] [orService-15457] [.p.c.v.i.ConfigItemStatusManagerImpl] Waiting on [agent:4] on [iptables], not applied requested [1201] > applied [1178] 
2015-06-18 01:23:33,885 INFO  [:] [] [] [] [orService-15457] [.p.c.v.i.ConfigItemStatusManagerImpl] Waiting on [agent:4] on [healthcheck], not applied requested [2323] > applied [2285] 
2015-06-18 01:23:33,887 DEBUG [b632ee2a-0a70-4b4d-baab-57acf29e35b5:40818] [instance:1124->nic:1117] [instance.start->(InstanceStart)->nic.activate->(AgentInstanceApplyItems)] [] [orService-15454] [i.c.p.e.memory.InMemoryEventService ] Unsubscribing from [reply.5061115068953299803] 
2015-06-18 01:23:33,887 DEBUG [b632ee2a-0a70-4b4d-baab-57acf29e35b5:40818] [instance:1124->nic:1117] [instance.start->(InstanceStart)->nic.activate->(AgentInstanceApplyItems)] [] [orService-15454] [i.c.p.e.memory.InMemoryEventService ] Unsubscribing from [reply.4445236185742763467] 
2015-06-18 01:23:33,887 DEBUG [b632ee2a-0a70-4b4d-baab-57acf29e35b5:40818] [instance:1124->nic:1117] [instance.start->(InstanceStart)->nic.activate->(AgentInstanceApplyItems)] [] [orService-15454] [i.c.p.e.memory.InMemoryEventService ] Unsubscribing from [reply.850527565514350693] 
2015-06-18 01:23:33,887 DEBUG [b632ee2a-0a70-4b4d-baab-57acf29e35b5:40818] [instance:1124->nic:1117] [instance.start->(InstanceStart)->nic.activate->(AgentInstanceApplyItems)] [] [orService-15454] [i.c.p.e.memory.InMemoryEventService ] Unsubscribing from [reply.8412979575777313250] 
2015-06-18 01:23:33,887 DEBUG [b632ee2a-0a70-4b4d-baab-57acf29e35b5:40818] [instance:1124->nic:1117] [instance.start->(InstanceStart)->nic.activate->(AgentInstanceApplyItems)] [] [orService-15454] [i.c.p.e.memory.InMemoryEventService ] Unsubscribing from [reply.1360980762125349702] 
2015-06-18 01:23:34,006 INFO  [:] [] [] [] [orService-15430] [.p.c.v.i.ConfigItemStatusManagerImpl] Failed update [configscripts, services, agent-instance-scripts, monit, agent-instance-startup, node-services, ipsec, healthcheck, ipsec-hosts, hosts, iptables, healthcheck] on [agent:4], exit code [122] output [Lock failed] 

```
agent.log

```
2015-06-18 01:17:42,663 INFO agent [140706751392336] [utils.py:424] Request: {"id":"914a0afc-25d2-4fac-905e-25d092af1da2","name":"delegate.request","replyTo":"reply.2276618286559130674","resourceId":null,"resourceType":null,"publisher":null,"transitioning":null,"transitioningMessage":null,"transitioningInternalMessage":null,"previousIds":null,"previousNames":null,"data":{"instanceData":{"created":1434348507000,"domain":null,"data":{"fields":{"imageUuid":"docker:rancher/agent-instance:v0.3.1","networkIds":[],"vnetIds":[1],"privileged":true,"transitioningMessage":"Post-network","transitioningProgress":95,"dockerHostIp":"130.211.161.183","dockerIp":"172.17.0.6","dockerPorts":{"4500/udp":"4500","500/udp":"500"},"primaryIpAddress":"10.42.181.71"},"ipsec":{"1":{"isakmp":500,"nat":4500}},"dockerInspect":{"State":{"Pid":5038,"OOMKilled":false,"Dead":false,"Paused":false,"Running":true,"FinishedAt":"0001-01-01T00:00:00Z","Restarting":false,"Error":"","StartedAt":"2015-06-15T06:08:53.645298045Z","ExitCode":0},"Config":{"Env":["CATTLE_CONFIG_URL=http://146.148.50.103:8080/v1","CATTLE_AGENT_INSTANCE_AUTH=Basic MUEzNzg3MzNCMkI0MTk1NDQ5NDE6dmpRalZFUXlaUmljRVNiekNWYkNKYW1YdXNmRThudUhydW9jUW9jUg==","HOME=/","PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"],"Hostname":"eb1aabcbb383","Entrypoint":null,"PortSpecs":null,"Memory":0,"OnBuild":null,"OpenStdin":false,"MacAddress":"02:37:3c:9f:67:c8","Cpuset":"","User":"","AttachStderr":false,"AttachStdout":false,"NetworkDisabled":false,"WorkingDir":"","Cmd":["/etc/init.d/agent-instance-startup","init"],"StdinOnce":false,"AttachStdin":false,"Volumes":{},"MemorySwap":0,"Tty":false,"CpuShares":0,"Domainname":"","Image":"rancher/agent-instance:v0.3.1","Labels":{"io.rancher.container.system":"NetworkAgent","io.rancher.container.uuid":"5d2c928d-ac01-40a1-98ac-35b9345c85f7","io.rancher.container.ip":"10.42.181.71/16"},"ExposedPorts":{"4500/udp":{},"500/udp":{}}},"HostsPath":"/var/lib/docker/containers/eb1aabcbb3832f1bbf74a9d4391a547f457243321c049a2fdbe55e028f5cbb50/hosts","Args":["init"],"Driver":"aufs","ExecDriver":"native-0.2","Path":"/etc/init.d/agent-instance-startup","HostnamePath":"/var/lib/docker/containers/eb1aabcbb3832f1bbf74a9d4391a547f457243321c049a2fdbe55e028f5cbb50/hostname","VolumesRW":{},"RestartCount":0,"Name":"/5d2c928d-ac01-40a1-98ac-35b9345c85f7","Created":"2015-06-15T06:08:53.388897965Z","ResolvConfPath":"/var/lib/docker/containers/eb1aabcbb3832f1bbf74a9d4391a547f457243321c049a2fdbe55e028f5cbb50/resolv.conf","Volumes":{},"ExecIDs":null,"ProcessLabel":"","NetworkSettings":{"Bridge":"docker0","GlobalIPv6PrefixLen":0,"LinkLocalIPv6Address":"fe80::37:3cff:fe9f:67c8","GlobalIPv6Address":"","IPv6Gateway":"","PortMapping":null,"IPPrefixLen":16,"LinkLocalIPv6PrefixLen":64,"MacAddress":"02:37:3c:9f:67:c8","IPAddress":"172.17.0.6","Gateway":"172.17.42.1","Ports":{"4500/udp":[{"HostPort":"4500","HostIp":"0.0.0.0"}],"500/udp":[{"HostPort":"500","HostIp":"0.0.0.0"}]}},"AppArmorProfile":"","Image":"3b0ebcadd8a7ee5a9b4ef203f14337853acdd5294592f00da6e52fe78341dd65","LogPath":"/var/lib/docker/containers/eb1aabcbb3832f1bbf74a9d4391a547f457243321c049a2fdbe55e028f5cbb50/eb1aabcbb3832f1bbf74a9d4391a547f457243321c049a2fdbe55e028f5cbb50-json.log","HostConfig":{"ContainerIDFile":"","Memory":0,"Dns":null,"PidMode":"","DnsSearch":null,"Privileged":true,"Ulimits":null,"CpusetCpus":"","CgroupParent":"","RestartPolicy":{"MaximumRetryCount":0,"Name":""},"PublishAllPorts":false,"ReadonlyRootfs":false,"CpuShares":0,"NetworkMode":"","LxcConf":null,"Devices":null,"Binds":null,"MemorySwap":0,"ExtraHosts":null,"VolumesFrom":null,"CapDrop":null,"Links":null,"IpcMode":"","PortBindings":{"4500/udp":[{"HostPort":"4500","HostIp":"0.0.0.0"}],"500/udp":[{"HostPort":"500","HostIp":"0.0.0.0"}]},"SecurityOpt":null,"CapAdd":null,"LogConfig":{"Type":"json-file","Config":null}},"MountLabel":"","Id":"eb1aabcbb3832f1bbf74a9d4391a547f457243321c049a2fdbe55e028f5cbb50"},"dockerContainer":{"Status":"Up Less than a second","Created":1434348533,"Image":"rancher/agent-instance:v0.3.1","Labels":{"io.rancher.container.system":"NetworkAgent","io.rancher.container.uuid":"5d2c928d-ac01-40a1-98ac-35b9345c85f7","io.rancher.container.ip":"10.42.181.71/16"},"Ports":[{"IP":"0.0.0.0","Type":"udp","PublicPort":4500,"PrivatePort":4500},{"IP":"0.0.0.0","Type":"udp","PublicPort":500,"PrivatePort":500}],"Command":"/etc/init.d/agent-instance-startup init","Names":["/5d2c928d-ac01-40a1-98ac-35b9345c85f7"],"Id":"eb1aabcbb3832f1bbf74a9d4391a547f457243321c049a2fdbe55e028f5cbb50"}},"token":"HEUilOLXbb5e6JyYwbhEvuy7M5RWwmTNSKsooYjeB7MMcJ1qzjYtTOFU8nzqQmys4lx2iEHt635aDk64BRZq3Q","description":null,"name":"Network Agent","id":4,"state":"running","startCount":null,"accountId":5,"healthState":null,"removed":null,"externalId":"eb1aabcbb3832f1bbf74a9d4391a547f457243321c049a2fdbe55e028f5cbb50","hostname":null,"kind":"container","systemContainer":"NetworkAgent","agentId":4,"memoryMb":null,"userdata":null,"offeringId":null,"compute":null,"firstRunning":1434348534000,"uuid":"5d2c928d-ac01-40a1-98ac-35b9345c85f7","allocationState":"active","nativeContainer":false,"networkContainerId":null,"registryCredentialId":null,"instanceTriggeredStop":"restart","zoneId":1,"imageId":4,"removeTime":null},"event":{"id":"31a5efe7-ad9d-474b-b17f-47906820ed87","name":"config.update","replyTo":"config.update.reply","resourceId":"4","resourceType":"agent","publisher":null,"transitioning":null,"transitioningMessage":null,"transitioningInternalMessage":null,"previousIds":null,"previousNames":null,"data":{"configUrl":"http://146.148.50.103:8080/v1","items":[{"name":"healthcheck","requestedVersion":null,"apply":false,"increment":false,"checkInSyncOnly":true},{"name":"ipsec-hosts","requestedVersion":null,"apply":false,"increment":false,"checkInSyncOnly":true},{"name":"hosts","requestedVersion":null,"apply":false,"increment":false,"checkInSyncOnly":true},{"name":"iptables","requestedVersion":null,"apply":false,"increment":false,"checkInSyncOnly":true}]},"time":1434590262612,"timeoutMillis":2000,"transitioningProgress":null,"context":null}},"time":1434590262613,"timeoutMillis":2000,"transitioningProgress":null,"context":null} 
2015-06-18 01:17:42,712 INFO agent [140706751392336] [utils.py:424] Response: {"name": "reply.2276618286559130674", "transitioningProgress": null, "resourceType": null, "resourceId": null, "id": "c5bc3fc1-6316-441c-8c49-f56b1c67d118", "transitioningMessage": "Update failed", "time": 1434590262000, "previousNames": ["delegate.request"], "transitioning": "yes", "data": {"name": "config.update.reply", "transitioningProgress": null, "resourceType": "agent", "resourceId": "4", "id": "9a001f8f-55cb-4eea-94b9-e8af03455cf9", "transitioningMessage": "Update failed", "time": 1434590262000, "previousNames": ["config.update"], "transitioning": "yes", "data": {"output": "Lock failed", "exitCode": 122}, "previousIds": ["31a5efe7-ad9d-474b-b17f-47906820ed87"]}, "previousIds": ["914a0afc-25d2-4fac-905e-25d092af1da2"]} [0.00588393211365] seconds 
```

**Comment by justyns** [comment] 2015-06-19 00:14
Just as a note..  I had the same issue (1 of 3 new containers stuck in 'Networking' state), and stopping that container via the UI then starting it fixed it for me.    Unfortunately I did not check the logs before this to see if they had anything useful.   I will if it happens again.

**Comment by cjellick** [comment] 2015-06-19 23:19
@ibuildthecloud Is investigating this. Seems related to something in docker and not caused by the new proxy.

**Comment by Berndinox** [comment] 2015-06-29 13:17
Got the Same issue, just a reboot of the underlying coreos host does sometimes fix this issue...

**Comment by will-chan** [comment] 2016-03-05 00:44
Closed as Obsolete

**Closed by will-chan** 2016-03-05 00:44 UTC
Labels: area/agent, kind/bug
