### ISSUE TITLE
Host losing network connectivity after been restarted.

### ISSUE THREAD

**Issue by omegarus** [rancher/rancher#8852] opened 2017-05-24 07:28 UTC
**Rancher versions:**
rancher/server:v1.5.9
rancher/agent:v1.2.2

**Infrastructure Stack versions:**
healthcheck:v0.2.3
ipsec:v0.0.7
network-services:v0.1.2
scheduler:v0.5.1
kubernetes (if applicable):v1.5.4-rancher1-4

**Docker version: (`docker version`,`docker info` preferred)**
```#docker info
Containers: 13
Running: 11
Paused: 0
Stopped: 2
Images: 10
Server Version: 1.12.5
Storage Driver: aufs
Root Dir: /var/lib/docker/aufs
Backing Filesystem: extfs
Dirs: 69
Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
Volume: local
Network: host null bridge overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: apparmor
Kernel Version: 3.19.0-77-generic
Operating System: Ubuntu 14.04.5 LTS
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 15.67 GiB
Name: host2
ID: GJ37:EDR5:XSCJ:HXFA:4A3Z:JEKQ:AMIX:5NAJ:553P:CTLO:BKJQ:MHG4
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Insecure Registries:
127.0.0.0/8
# docker version
Client:
Version:      1.12.5
API version:  1.24
Go version:   go1.6.4
Git commit:   7392c3b
Built:        Fri Dec 16 02:30:42 2016
OS/Arch:      linux/amd64
 
Server:
Version:      1.12.5
API version:  1.24
Go version:   go1.6.4
Git commit:   7392c3b
Built:        Fri Dec 16 02:30:42 2016
OS/Arch:      linux/amd64
```
**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
```
#cat /etc/os-release
NAME="Ubuntu"
VERSION="14.04.5 LTS, Trusty Tahr"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 14.04.5 LTS"
VERSION_ID="14.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
#uname -r
3.19.0-77-generic
```
**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
VMware
**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
Single node rancher server + 2 hosts
**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**
Kubernetes
**Steps to Reproduce:**
Add two hosts to rancher server and wait to kubernetes stack been installed. Then deploy traefik ingress controller as DaemonSet:
```
kind: DaemonSet
apiVersion: extensions/v1beta1
metadata:
  name: traefik-ingress-controller
  namespace: kube-system
  labels:
    k8s-app: traefik-ingress-lb
spec:
  template:
    metadata:
      labels:
        k8s-app: traefik-ingress-lb
        name: traefik-ingress-lb
    spec:
      terminationGracePeriodSeconds: 60
      hostNetwork: true
      containers:
      - image: traefik
        name: traefik-ingress-lb
        resources:
          limits:
            cpu: 200m
            memory: 30Mi
          requests:
            cpu: 100m
            memory: 20Mi
        ports:
        - name: http
          containerPort: 80
          hostPort: 80
        - name: admin
          containerPort: 8081
        securityContext:
          privileged: true
        args:
        - -d
        - --web
        - --web.address=:8081
        - --kubernetes
```
Now restart on of the hosts. 
**Results:**
One of the hosts (sometimes two) loosing network connectivity after restart. 

I tried to flush iptables to default state with this commands: 
```
iptables -F
iptables -X
iptables -t nat -F
iptables -t nat -X
iptables -t mangle -F
iptables -t mangle -X
iptables -P INPUT ACCEPT
iptables -P FORWARD ACCEPT
iptables -P OUTPUT ACCEPT
```
Tried to remove all containers and restart docker-engine, tried to flush routing tables and then ifdown/ifup eth0. Nothing helped. Only restart of host vm helped.
With rancher 1.4.1 i don't have this problem.

**Comment by omegarus** [comment] 2017-05-25 13:13
After investigation i found a pattern for this behavior. Issue updated

**Comment by omegarus** [comment] 2017-06-20 09:34
Ok i found the problem. Some how then i set `hostNetwork: true` in pod manifest then it scheduled to any host it changing MAC address of host eth0 nic to somthing like `02:e1:8c:xx:xx:xx`.
Here is examples:
Proper mac address:
```
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP group default qlen 1000
    link/ether 00:50:56:01:08:0f brd ff:ff:ff:ff:ff:ff
    inet 10.0.0.88/24 brd 10.0.217.255 scope global eth0
       valid_lft forever preferred_lft forever
```
Mac address changed after pod with `hostNetwork: true` configuration being scheduled to node:
```
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP group default qlen 1000
   link/ether 02:e1:8c:bb:bc:1c brd ff:ff:ff:ff:ff:ff
    inet 10.0.0.88/24 brd 10.0.217.255 scope global eth0
       valid_lft forever preferred_lft forever
```
I'am using VMware vShield it's not passing out packets from unknown mac address.
If i'am restoring proper mac address back with this command `ifconfig eth0 hw ether $(ethtool -P eth0 | awk '{print $3}')` everything working good.

**Comment by leodotcloud** [comment] 2017-06-20 14:09
@omegarus Can you please collect logs using: https://github.com/leodotcloud/rancher-logs-collector and also share the database dump of cattle? You can DM me on https://slack.rancher.io.

**Comment by leodotcloud** [comment] 2017-06-21 17:29
@omegarus 
Only containers launched on the managed networking go through the CNI plugin cycle to setup networking.
Summary of how CNI plugin works:
- Container is launched/started
- Runtime calls the CNI plugin
- CNI plugin invokes the IPAM plugin and figures out the IP address information.
- CNI plugin creates the veth pair, configures the MAC address and IP address.

All this is NOT applicable for a container with `--net=host` mode. Can you please check the `kubelet` logs and also `ipsec-cni-*` container logs to see what's going on?

From what you are describing, I am suspecting the MAC address could have been somehow modified by the CNI plugin?

**Comment by omegarus** [comment] 2017-06-22 09:34
@leodotcloud I sent you logs in slack.

**Comment by leodotcloud** [comment] 2017-06-22 20:08
@omegarus Since I don't have the complete set of logs, it's kind of hard to correlate anything. What I am looking for is which container ID was assigned this MAC address: `02:e1:8c:bb:bc:1c`. And then figure out why the CNI plugin was invoked by Kubernetes. Also could you please check if this issue is reproducible always? With only one particular image or with any image (like ubuntu:14.04)?

**Comment by omegarus** [comment] 2017-06-27 07:15
@leodotcloud I'am using ubuntu 14.04 vms installed from scratch for hosts and server. This problem always happens then i deploy traefik with hostNetwork: true. I tried in two different environments vCloud and vSphere in both mac address has been changed after traefik deploy. I can't use any other images except ubuntu 14.04 right now.

**Comment by leodotcloud** [comment] 2017-09-17 06:06
@omegarus The MAC address of the host being changed is exactly same as: https://github.com/rancher/rancher/issues/9678. Are you still having issues even with the fix?

**Comment by superseb** [comment] 2017-10-23 08:34
Please reply if you are still experiencing issues with this.

**Closed by superseb** 2017-10-23 08:34 UTC
Labels: area/networking, kind/question
