### ISSUE TITLE
Stuck during upgrade

### ISSUE THREAD

**Issue by alex88** [rancher/rancher#4290] opened 2016-04-05 06:06 UTC
Rancher Version: 1.0.0
Docker Version: 1.10.1
OS: Rancher OS
Steps to Reproduce:
 - have a cluster with all instances' port 80 used by something (load balancer in my case)
 - start wordpress stack from catalog
 - wordpress container fails to start since scheduler isn't able to find an host with port 80 free
 - try to run upgrade and remove host 80 port binding
 - upgrade runs but instance is still failing
 - cancel upgrade

Results: Service keeps in "Finishing-upgrade" trying to run a container which never starts since can't be scheduled, trying to scale service to 0 returns error 500

```
2016-04-05 05:58:17,934 ERROR [:] [] [] [] [tp639313753-240] [i.g.i.g.r.handler.ExceptionHandler  ] Exception in API for request [io.github.ibuildthecloud.gdapi.request.ApiRequest@7a9d77df] io.cattle.platform.engine.process.impl.ProcessCancelException: State [finishing-upgrade] is not valid
```

Rancher tries continuously to create a new container

Expected: Upgrade should be marked as "done" and container still not starting but with old configuration

**Comment by alex88** [comment] 2016-04-05 06:12
This seems to be a more general issue, when you cancel an upgrade and the containers have `restart: always` and they fail to start the upgrade never ends

**Comment by tfiduccia** [comment] 2016-04-05 17:23
Version - master 4/5
Verified that this is happening in current master build.  The upgrade simply does not happen at all, I got this error in the UI:
![image](https://cloud.githubusercontent.com/assets/11514927/14291372/2ad52760-fb18-11e5-9546-27e88b975d39.png)

**Comment by JulianKingman** [comment] 2016-04-06 03:29
I'm getting a similar issue. I tried cancelling an upgrade because of an error with volume configuration, but it keeps trying to rebuild it with the same faulty volume, leaving it stuck at "Finishing-Upgrade (In Progress)"

**Comment by JulianKingman** [comment] 2016-04-12 23:10
In my case it turned out to be volume permission issues. I never really solved it, check your logs, you may be able to trace the issue like I did.

**Comment by alex88** [comment] 2016-04-12 23:11
@JulianKingman no logs here other than the one I've posted, btw no volumes too :)

**Comment by JulianKingman** [comment] 2016-04-13 00:48
Too bad, good luck :)

**Comment by alena1108** [comment] 2016-05-31 17:53
@JulianKingman 

>> I'm getting a similar issue. I tried cancelling an upgrade because of an error with volume configuration, but it keeps trying to rebuild it with the same faulty volume, leaving it stuck at "Finishing-Upgrade (In Progress)"

In this situation when you tried to upgrade the config to the one that had errors, you would have to:

1) cancel upgrade
2) rollback
3) finish upgrade

Canceling upgrade itself won't roll you back to the old "correct" config.

@alex88 
>> This seems to be a more general issue, when you cancel an upgrade and the containers have restart: always and they fail to start the upgrade never ends.

"restart" is ignored by Rancher. If the container is a part of the service, we always try to keep it running (and restart if it got stopped or failed to start) unless startOnce flag it set to true.

The real bug here is - there is no way to "fix" the service in "finishing upgrade" state when scheduling instances fail due to inability to match the constraint. We should allow to change the scale for the service in finishing-upgrade state

Resolving as a duplicate of https://github.com/rancher/rancher/issues/4240 as it has the same root cause.

**Closed by alena1108** 2016-05-31 17:53 UTC
Labels: area/service, kind/bug
