### ISSUE TITLE
/var/log/containers/fluentd-whpx4_cattle-logging_fluentd-c913ecb0b58544438444c39aa1e8b64c39862abd97a0eb6ffb6354d3e8e86209.log unreadable. It is excluded and would be examined next time.

### ISSUE THREAD

**Issue by jiuchongxiao** [rancher/rancher#14178] opened 2018-06-23 05:52 UTC
在rancher2.0.2 logging module，tartget out es cluster，seen fluentd logs。one node fluentd logs:
2018-06-22 06:58:46 +0000 [warn]: #0 /var/log/containers/fluentd-whpx4_cattle-logging_fluentd-c913ecb0b58544438444c39aa1e8b64c39862abd97a0eb6ffb6354d3e8e86209.log unreadable. It is excluded and would be examined next time.

version info:

[root@node93 efk-test]# docker version
Client:
 Version:         1.13.1
 API version:     1.26
 Package version: docker-1.13.1-63.git94f4240.el7.centos.x86_64
 Go version:      go1.9.4
 Git commit:      94f4240/1.13.1
 Built:           Fri May 18 15:44:33 2018
 OS/Arch:         linux/amd64

Server:
 Version:         1.13.1
 API version:     1.26 (minimum version 1.12)
 Package version: docker-1.13.1-63.git94f4240.el7.centos.x86_64
 Go version:      go1.9.4
 Git commit:      94f4240/1.13.1
 Built:           Fri May 18 15:44:33 2018
 OS/Arch:         linux/amd64
 Experimental:    false

[root@node93 efk-test]# kubectl version
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.3", GitCommit:"2bba0127d85d5a46ab4b778548be28623b32d0b0", GitTreeState:"clean", BuildDate:"2018-05-21T09:17:39Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.3", GitCommit:"2bba0127d85d5a46ab4b778548be28623b32d0b0", GitTreeState:"clean", BuildDate:"2018-05-21T09:05:37Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}

i upded the docker container postion（before update the postion is /var/lib/docker  and the after update position is /ultrapower/docker）details：
vi /lib/systemd/system/docker.service
new add parameter： --graph=/ultrapower/docker
ExecStart=/usr/bin/dockerd-current --graph=/ultrapower/docker

notice: i did not use sys link

why dispear the issue? and  how to solve it ? please help me ,thank you !

**Comment by superseb** [comment] 2018-06-23 07:45
Duplicate of https://github.com/rancher/rancher/issues/13304

**Closed by superseb** 2018-06-23 07:45 UTC

**Comment by jiuchongxiao** [comment] 2018-06-23 07:50
@superseb  i think the issue is not same #13304 ,because the descripe notice:
notice: i did not use sys link
