### ISSUE TITLE
Cant edit Load Balancer

### ISSUE THREAD

**Issue by Ilya-Kuchaev** [rancher/rancher#3040] opened 2015-12-16 14:46 UTC
Edit Load Balancer
Validation failed in API: name is not unique

Component	Version
Rancher	v0.50.0
Cattle	v0.126.0
User Interface	v0.74.0
Rancher Compose	v0.6.2

**Comment by deniseschannon** [comment] 2015-12-16 17:42
Duplicate of https://github.com/rancher/rancher/issues/3033

**Closed by deniseschannon** 2015-12-16 17:42 UTC

**Comment by deniseschannon** [comment] 2015-12-16 18:11
@Ilya-Kuchaev Can you just confirm that this is an upgraded setup? 

Also, are the services that you are trying to edit from the previous release? You are able to start new load balancers and edit them.
