### ISSUE TITLE
Helm Catalog answers not added correctly, subcharts not working

### ISSUE THREAD

**Issue by wyattjsmith1** [rancher/rancher#14608] opened 2018-07-18 16:40 UTC
Hi, I am trying to install Gitlab from their catalog [here](https://docs.gitlab.com/ee/install/kubernetes/gitlab_chart.html). The Helm chart requires a few arguments, which according to [this](https://rancher.com/docs/rancher/v2.x/en/concepts/catalogs/) and [this](https://github.com/rancher/rancher/issues/13372) tells me I should be putting the parameters in as Answers. Like this: 
![args](https://user-images.githubusercontent.com/17460119/42895104-b6db3fc4-8a6d-11e8-9971-0169b05f0a39.png)

When doing this, however, I receive this error telling me an argument is not set:
![errormessage](https://user-images.githubusercontent.com/17460119/42895147-d8bee942-8a6d-11e8-8342-42516794164d.png)

One thing I find strange is that the file `gitlab/values.yaml` is never updated in the preview area.

It is very possible I am doing something wrong, but I feel like I have thoroughly read the documentation and am putting the variables in the correct place. Thanks for any help.

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v2.0.6` UI: `v2.0.61` |
|Access|`local` `admin`|
|Route|`apps-tab.detail`|

**Comment by chrisingenhaag** [comment] 2018-07-19 18:15
I can confirm that behavior. When installing cert-manager via library I got errors and values are not applied correctly.

When I press edit yaml before first installation to add an additional answer I get the following validation errors on client side. After installation when I go back into Upgrade certmanager installation I only see the answers I gave in the UI-Form.

![rancher-library-value-errors](https://user-images.githubusercontent.com/518234/42961858-5b715c08-8b90-11e8-9518-1ee3b1460d51.png)

I also tried to give answers completely via "from yaml file". But these answers are also ignored.

**Comment by wyattjsmith1** [comment] 2018-07-21 19:41
It appears as though another user has the same issue with the gitlab image. It looks like something changed between RKE 0.1.9 and 0.2.3 that caused this issue.
https://docs.gitlab.com/ee/install/kubernetes/gitlab_chart.html#comment-3989398151

**Comment by bitfisher** [comment] 2018-07-24 09:04
Using own certificate as stated in [GitLab TLS Docs](https://gitlab.com/charts/gitlab/blob/0-3-stable/doc/installation/tls.md#option-2-use-your-own-wildcard-certificate) doesn't work either.


It results in same error _"Please set cermanager-issuer.email"_!

It seems like requirements condition doesn't get honored.

**Comment by wyattjsmith1** [comment] 2018-08-12 00:36
@bitfisher I noticed that too and reported it. It looks like that is because Rancher was setting all answers to be strings. Certain values such as configureCertmanager required booleans, but that became `"false"`. Strings can be converted to booleans, with an empty string being false, and any other string being true. This has been reverted here https://github.com/rancher/rancher/pull/15043. 

I am wondering if Rancher is not handling subchart values correctly as certmanager-issuer is a reference to a subchart.

**Comment by wyattjsmith1** [comment] 2018-08-13 17:08
One thing that could help is if there was some way to print the `.Values` variable that helm uses in its charts. Does anyone know if there is a way to display this?

I know there is a preview for all the template files including an `answers.yaml`, but that doesn't appear to be working correctly.

**Comment by donifer** [comment] 2018-08-15 01:55
Having the exact same issue trying to install Gitlab too.

**Comment by cjellick** [comment] 2018-08-23 02:04
co-assigning myself to help keep track of all these helm input-type issues

**Comment by cjellick** [comment] 2018-09-10 16:05
@strongmonkey my take is that this issue would be resolved by our changes that address the set-string issue. can you review and give me your opinion?
If that is correct, please move it along with the other issue

**Comment by StrongMonkey** [comment] 2018-09-10 17:09
This issue is the duplicate of https://github.com/rancher/rancher/issues/13158. We will be adding two feature on the answer side to address this kind of issue:
1. Allow user to put values.yaml file to override default values.yaml. User can choose to put string by quoting the value or boolean and number(which yaml converter will guess them).
2. Allow user to put enhanced answer types which can be specified with a type(string, boolean, int) in API.

**Comment by courcelm** [comment] 2018-10-17 19:08
Subcharts just introduced in Istio chart (https://github.com/istio/istio.git) is also problematic:

Here is the error produced in Rancher 2.1.0:
Installing
Helm template failed. Error: found in requirements.yaml, but missing in charts/ directory: sidecarInjectorWebhook, security, ingress, gateways, mixer, nodeagent, pilot, grafana, prometheus, servicegraph, tracing, galley, kiali, certmanager, nodeagent : exit status 1

**Comment by loganhz** [comment] 2019-02-14 15:50
Close in favor of https://github.com/rancher/rancher/issues/13158

**Closed by loganhz** 2019-02-14 15:50 UTC
Labels: kind/bug, priority/0, status/ready-for-review, status/resolved, team/cn, version/2.0
