### ISSUE TITLE
Rancher canal network provider has wrong MTU

### ISSUE THREAD

**Issue by alexandrem** [rancher/rancher#13984] opened 2018-06-13 17:44 UTC
Rancher: 2.0.2

Creating a cluster with Canal seems to leave the default MTU at 1500.

However, calico+flannel should have 1450 for the 50 bytes vxlan overhead, as documented in https://docs.projectcalico.org/v3.1/usage/configuration/mtu

Example container:
```bash
# ip -d link
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN mode DEFAULT qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
3: eth0@if7: <BROADCAST,MULTICAST,UP,LOWER_UP,M-DOWN> mtu 1500 qdisc noqueue state UP mode DEFAULT 
    link/ether 2e:88:0a:f0:64:ff brd ff:ff:ff:ff:ff:ff
    veth 
```

This is a veth to the `docker0` interface that has 1500 MTU, but it should respect the flannel.1 1450 host interface instead.

```
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN mode DEFAULT group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00 promiscuity 0 addrgenmode eui64 numtxqueues 1 numrxqueues 1 gso_max_size 65536 gso_max_segs 65535 
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP mode DEFAULT group default qlen 1000
    link/ether fa:16:3e:4c:a6:72 brd ff:ff:ff:ff:ff:ff promiscuity 0 addrgenmode eui64 numtxqueues 1 numrxqueues 1 gso_max_size 65536 gso_max_segs 65535 
3: docker0: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc noqueue state DOWN mode DEFAULT group default 
    link/ether 02:42:96:c3:98:89 brd ff:ff:ff:ff:ff:ff promiscuity 0 
    bridge forward_delay 1500 hello_time 200 max_age 2000 ageing_time 30000 stp_state 0 priority 32768 vlan_filtering 0 vlan_protocol 802.1Q bridge_id 8000.2:42:96:c3:98:89 designated_root 8000.2:42:96:c3:98:89 root_port 0 root_path_cost 0 topology_change 0 topology_change_detected 0 hello_timer    0.00 tcn_timer    0.00 topology_change_timer    0.00 gc_timer  134.54 vlan_default_pvid 1 vlan_stats_enabled 0 group_fwd_mask 0 group_address 01:80:c2:00:00:00 mcast_snooping 1 mcast_router 1 mcast_query_use_ifaddr 0 mcast_querier 0 mcast_hash_elasticity 4 mcast_hash_max 512 mcast_last_member_count 2 mcast_startup_query_count 2 mcast_last_member_interval 100 mcast_membership_interval 26000 mcast_querier_interval 25500 mcast_query_interval 12500 mcast_query_response_interval 1000 mcast_startup_query_interval 3125 mcast_stats_enabled 0 mcast_igmp_version 2 mcast_mld_version 1 nf_call_iptables 0 nf_call_ip6tables 0 nf_call_arptables 0 addrgenmode eui64 numtxqueues 1 numrxqueues 1 gso_max_size 65536 gso_max_segs 65535 
4: flannel.1: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1450 qdisc noqueue state UNKNOWN mode DEFAULT group default 
    link/ether 02:23:2e:e5:d3:a4 brd ff:ff:ff:ff:ff:ff promiscuity 0 
    vxlan id 1 local 10.130.179.96 dev eth0 srcport 0 0 dstport 8472 nolearning ageing 300 noudpcsum noudp6zerocsumtx noudp6zerocsumrx addrgenmode eui64 numtxqueues 1 numrxqueues 1 gso_max_size 65536 gso_max_segs 65535 
5: cali3f0ed62327c@if3: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP mode DEFAULT group default 
    link/ether ee:ee:ee:ee:ee:ee brd ff:ff:ff:ff:ff:ff link-netnsid 0 promiscuity 0 
    veth addrgenmode eui64 numtxqueues 1 numrxqueues 1 gso_max_size 65536 gso_max_segs 65535 
6: calia2b582fff19@if3: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP mode DEFAULT group default 
    link/ether ee:ee:ee:ee:ee:ee brd ff:ff:ff:ff:ff:ff link-netnsid 1 promiscuity 0 
    veth addrgenmode eui64 numtxqueues 1 numrxqueues 1 gso_max_size 65536 gso_max_segs 65535 
7: calid5d19988e17@if3: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP mode DEFAULT group default 
    link/ether ee:ee:ee:ee:ee:ee brd ff:ff:ff:ff:ff:ff link-netnsid 2 promiscuity 0 
    veth addrgenmode eui64 numtxqueues 1 numrxqueues 1 gso_max_size 65536 gso_max_segs 65535
```

Not having the correct MTU can cause intermittent tcp retransmission errors and poor performance.

The fix can be simply done in RKE canal config map template: https://github.com/rancher/rke/blob/master/templates/canal.go by adding `"mtu": "1450"` to the cni_network_conf plugins.

Ideally this should become a template variable that we define in Rancher type objects somewhere.

**Comment by loganhz** [comment] 2018-10-08 15:18
cc @galal-hussein

**Comment by xiaoluhong** [comment] 2018-11-01 10:13
Currently, RKE does not support configuring `MTU`，which can be configured manually：

1. Edit `configmaps `through kubectl
`kubectl edit configmaps -n kube-system canal-config`

2. Add `"mtu": "1450" `under `"type": "calico"`
<img width="355" alt="image" src="https://user-images.githubusercontent.com/20707603/47845974-7986a180-de01-11e8-978e-70d13dfac70a.png">

3. Delete the canal pod and let it be recreated

`kubectl get pod -n kube-system |grep canal |awk '{print $1}' | xargs kubectl delete -n kube-system  pod`

4. Create the application to view the MTU value

**Comment by krwrang** [comment] 2018-11-21 08:04
> Currently, RKE does not support configuring `MTU`，which can be configured manually：

I tested this and after killing the Canal pods and waiting them to be recreated, looking at `ifconfig` the calico interfaces on the hosts still show `MTU:1500`. Only newly created deployments with calico interfaces use the new MTU of 1450. Any insight on this?

**Comment by krishofmans** [comment] 2018-11-21 09:06
@krwrang yes, I tested that too, I forgot to mention it back on this ticket. It worked but we had to roll through all our nodes in the cluster, restarting them. 
For us the issue was 2 sites, ipsec vpn, therefore we had to lower the mtu to make all packages pass. Before some http requests bigger than 450 bytes disappeared.

**Comment by xiaoluhong** [comment] 2018-11-21 12:13
@krwrang  
Sorry, the operation error has closed the issue, which has been reopened.  I tested it on v2.0.8 to v2.1.1.  
Correct one of my mistakes , you don't need to add double quotes to 1450 , should be written as `"mtu": 1450 `

**Comment by pbaezab** [comment] 2018-11-27 14:45
My problem is MTU in 1450. The default 1500 is OK for me. 

Terraform + RKE no set MTU then canal setup in 1450. I change in config map, as is https://github.com/rancher/rke/blob/master/templates/calico.go actually.

**Comment by pbaezab** [comment] 2018-12-24 14:51
> My problem is MTU in 1450. The default 1500 is OK for me but I run canal.
> 
> Terraform + RKE no set MTU then canal setup in 1450. I change in config map, as is https://github.com/rancher/rke/blob/master/templates/calico.go actually.

My config calico+flannel and I am not can change this. Then, finally I set eth0 in MTU 1550 for flannel.1. Automatically flannel mtu is 1500.

The main problem,  azure or openstack load balance, not talking correctly with origin mtu and target mtu (eth0+flannel.1)

**Comment by sboulkour** [comment] 2019-05-06 14:17
Hey there, I tried the `canal-config` update by adding `"mtu": 1450` as specified by @xiaoluhong and tried a node reboot : cali* interfaces still show 1500 mtu, and flannel a 1450 mtu. So I see no difference.
```
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
2: ens192: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP group default qlen 1000
3: docker0: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc noqueue state DOWN group default 
8: flannel.1: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1450 qdisc noqueue state UNKNOWN group default 
13: calib099535858f@if3: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default 
16: cali3b506582fdd@if3: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default 
23: calibdd81c39377@if3: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default
[...]
```

**Comment by leodotcloud** [comment] 2019-06-28 20:10
@galal-hussein we need a way to pass the MTU setting from rkeconfig.yml.

**Comment by leodotcloud** [comment] 2019-06-28 20:15
Related: https://github.com/coreos/flannel/issues/1011

Just changing the MTU value in the configmap and recreating the flannel pods, doesn't reset the MTU on the flannel.1 interface.

The workaround is to change the mtu value of the primary network interface using `ifcfg-*` scripts.

**Note:** It's very important to have the same MTU (Lowest MTU value of all the nodes)  configured on ALL the nodes of the kubernetes cluster, otherwise there is a high possibility of running into some weird networking problems.

**Comment by rossigee** [comment] 2019-11-14 02:03
fwiw, I found I had to update the `/etc/cni/net.d/calico-kubeconfig` on the host node, add the 'mtu' attribute there, and reboot the machine in order to get the cali* interfaces to have a custom MTU.

As @sboulkour notes, simply adding it to the K8S ConfigMap for 'canal-config' didn't affect the cali* interfaces.

**Comment by deniseschannon** [comment] 2019-12-18 18:25
With the ability to configure MTU (https://github.com/rancher/rancher/issues/24096), this issue can be resolved by setting your own MTU.

**Comment by aleksey005** [comment] 2020-01-17 12:15
After upgrade from 2.3.3 to 2.3.4

```
This cluster is currently Updating.
Failed to validate cluster: Network plugin [flannel] does not support configuring MTU
```

**Comment by superseb** [comment] 2020-01-17 13:11
Can you share the `View in API` output from the cluster? (redact any sensitive info)

And was this auto triggered or did you upgrade the Kubernetes version or something else on this cluster?

**Comment by superseb** [comment] 2020-01-17 13:13
Also, please try if adding mtu to the network plugin resolves the issue:

```
  network:
    mtu: 0
    plugin: flannel
```

**Comment by aleksey005** [comment] 2020-01-17 15:08
I have already updated the clusters, so I do not have the actual api output. I clicked edit in and found this line installed

```
   network:
     mtu:
     plugin: flannel
```

And everything was updated wonderfully.

**Comment by superseb** [comment] 2020-01-17 15:10
Can you share anything about how the clusters were provisioned (on what Rancher version it was initially provisioned) or any automation that you might have used around the cluster? I ran a v2.3.3 -> v2.3.4 upgrade test with a custom cluster and flannel and didn't reproduce.

**Comment by aleksey005** [comment] 2020-01-17 15:22
These clusters have been working for more than a year and have been updated with each new release, unfortunately I do not remember which version I started with, but probably relevant 2.0 after a month since it was released. Clusters run on virtual machines on Ubuntu 18.04 and I have no more such clusters on the flannel.

I think this is a UI error because if you try to put 0 in the form, it automatically changes to 1 and this can only be fixed through editing YAML.

**Comment by superseb** [comment] 2020-01-17 15:23
Thanks for the info! I will run some more tests and create a new issue for it.

**Comment by aleksey005** [comment] 2020-01-17 15:45
> And was this auto triggered or did you upgrade the Kubernetes version or something else on this cluster?> 

Yes, I updated the version of kubernetes from 16.3 (skipping one intermediate) to 17.0 (although the release description states that this is version 17.0 by default, nevertheless it is shown as experimental).

**Comment by deniseschannon** [comment] 2020-02-03 22:09
I'm closing this issue as we have introduced the ability to set your own MTU as of v2.3.4. If this doesn't satisfy what is needed for your use case, please open a new issue.

MTU is specific to each person's environment, so there is no way for us to predict what the value should be on everyone's setup.

**Closed by deniseschannon** 2020-02-03 22:09 UTC
Labels: [zube]: Final Review, area/networking, area/rke, internal, kind/bug
