### ISSUE TITLE
Rancher services api does not correctly filter services

### ISSUE THREAD

**Issue by nhumrich** [rancher/rancher#5664] opened 2016-08-08 23:41 UTC
**Rancher Version:**
1.1.2

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle

**Steps to Reproduce:**

Call the environments/services api with a filter, for example

```
myurl.com/v1/projects/1a111/environments/1e11/services/?name=something
```

**Results:** 
the data key in the json contains all services in the stack. It is not filtering by name at all

**Expected:**
The data key should be a list containing only one item, the item matching my query

**Comment by deniseschannon** [comment] 2016-08-09 15:03
Duplicate of https://github.com/rancher/rancher/issues/5321

**Closed by deniseschannon** 2016-08-09 15:03 UTC
