### ISSUE TITLE
`no data found for resource with given identifier` for network, templates, etc. when creating a vsphere rke2 cluster

### ISSUE THREAD

**Issue by slickwarren** [rancher/rancher#36004] opened 2022-01-03 21:42 UTC
**Rancher Server Setup**
- Rancher version: v2.6-head (375b0e6)
- Installation option (Docker install/Helm Chart): docker
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc):
- Proxy/Cert Details:

**Information about the Cluster**
- Kubernetes version: v1.21.7
- Cluster Type (Local/Downstream): downstream
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider):vsphere cloud provider

**Describe the bug**

vsphere is not loading anything in the UI. it appears that fields like network, templates, tags, etc. are not returning any data. 

**To Reproduce**
 
* create valid vsphere credentials 
* use those credentials to create an rke2 cluster

**Result**
* user is unable to enter information for networks, templates, etc. 
* failed to fetch fields show a loading icon indefinitely

**Expected Result**

* networks and other fields should load with appropriate data. 

**Screenshots**

<img width="555" alt="Screen Shot 2022-01-03 at 12 30 59 PM" src="https://user-images.githubusercontent.com/16691014/147983434-8acfaca2-c285-4b9b-bba1-b9a7ed21cbb8.png">

<img width="185" alt="Screen Shot 2022-01-03 at 1 41 46 PM" src="https://user-images.githubusercontent.com/16691014/147983473-0e933019-9a0f-4716-9d13-47079965e024.png">

**Additional context**

* found while testing https://github.com/rancher/rancher/issues/34910
* it seems as though this might be some sort of timing issue. After doing a hard refresh on the page 1x, some (but not all) of the resources causing issues were resolved. Waiting another few minutes and doing another refresh resolved all of the issues.

**Comment by doflamingo721** [comment] 2022-02-08 14:16
**This issue is not active on rancher v2.6-head**

Steps followed:
1. Rancher Server version: 2.6-head
2. Create valid vSphere credentials.
3. Create  a downstream RKE2 cluster with the vSphere credentials.

Result:
After providing the credentials, the values in other fields are getting populated correctly.

Screenshot: 

![Screenshot from 2022-02-08 16-00-22](https://user-images.githubusercontent.com/34883075/153004259-35956d31-a6f8-4d75-a328-8595b695c328.png)

**Comment by vivek-infracloud** [comment] 2022-02-17 13:56
### This issue is not active on rancher v2.6-head

**Steps followed:**

1. Rancher Server version: 2.6-head 
2. Create valid vSphere credentials.
3. Create a downstream RKE2 cluster with the vSphere credentials.

Result:
After providing the credentials, the values in other fields are getting populated correctly.

**Comment by vivek-infracloud** [comment] 2022-02-17 13:57
Based on above validation, the issue is not active on v2.6-head. Hence, closing the issue.

**Closed by vivek-infracloud** 2022-02-17 13:57 UTC
Labels: area/vsphere, kind/bug-qa, [zube]: To Test, team/infracloud
