### ISSUE TITLE
CIS Scan - UI/UX for Profiles

### ISSUE THREAD

**Issue by maggieliu** [rancher/rancher#25327] opened 2020-02-08 00:29 UTC
CIS Profiles: rancher/rancher#25325 
* User can select from two profiles to run the scan "Permissive" vs "Hardened"
* Permissive run contains Rancher suggested skips and they cannot be unskipped
* User can add skipped tests and unskip them
* There should be a UI distinction between "Rancher Skips" and "User Skips"
* ON the report, need to show the Profile used to run the scan

**Comment by sowmyav27** [comment] 2020-03-06 22:47
**Verified on latest master-head - ui tag: `latest2`**

- Click on Run Scans --> Select a profile and click on "Run"
- Error `Cannot read property 'profile' of undefined` is seen in the console

<img width="1900" alt="Screen Shot 2020-03-06 at 2 44 46 PM" src="https://user-images.githubusercontent.com/26032343/76128476-489c1b00-5fb9-11ea-82cf-108a76251075.png">

**Comment by codyrancher** [comment] 2020-03-09 23:22
Can you give this a try again? This should've been resolved by a change that already went in.

**Comment by izaac** [comment] 2020-03-09 23:50
@codyrancher for the requirement:

> There should be a UI distinction between "Rancher Skips" and "User Skips"

How can I differentiate them in the UI ?

**Comment by codyrancher** [comment] 2020-03-09 23:56
@izaac I'm making the assumption that the N/A state is Rancher Skips.

@leodotcloud is my assumption correct?

**Comment by izaac** [comment] 2020-03-10 18:17
Reopening as the requirement: `There should be a UI distinction between "Rancher Skips" and "User Skips"` is not yet met.

**Comment by davidnuzik** [comment] 2020-03-10 18:47
I am seeing what Sowmya reported again in latest https://github.com/rancher/rancher/issues/25327#issuecomment-595997155 however with a different message now like this:

```
clusterscan.js:126 Uncaught (in promise) TypeError: Cannot read property 'toUpperCase' of undefined
    at n.<anonymous> (clusterscan.js:126)
    at n.i.get (metal.js:3614)
    at $e (metal.js:2720)
    at t.r.compute (glimmer.js:648)
    at t.value (glimmer.js:388)
    at e.value (runtime.js:553)
    at e.t.initialize (reference.js:453)
    at e.t.peek (reference.js:428)
    at Function.n.initialize (runtime.js:902)
    at Object.evaluate (runtime.js:874)
```

To reproduce just run default CIS scan and click to view details.

master-2408-head `e78e43fea`

**Comment by codyrancher** [comment] 2020-03-10 23:54
Because of the decision that's outlined here https://github.com/rancher/rancher/issues/25863#issuecomment-597374753 U don't think we need to evaluate *There should be a UI distinction between "Rancher Skips" and "User Skips"* any longer.

**Comment by izaac** [comment] 2020-03-11 16:18
@maggieliu are we updating this story after the UI changes discussed? As of now all the requirements outlined here are met in the latest 2.4 master-head builds. But wanted to check first before closing.

**Comment by izaac** [comment] 2020-03-11 16:41
Rancher version: `2.4 master-head (03/10/2020)` commit id: 570461823

Validated the requirements were met without considering the UI distinction requirements between Rancher Skips and User Skips as mentioned.

**Closed by izaac** 2020-03-11 16:41 UTC
Labels: [zube]: To Test, area/scan-tool, kind/feature, team/ui

**Comment by maggieliu** [comment] 2020-03-11 16:42
@izaac Cody will create a new ticket for the additional UI changes. You can go ahead and close this one.
