### ISSUE TITLE
rancher-agent crashes (possibly non-robust parser)

### ISSUE THREAD

**Issue by feliksik** [rancher/rancher#1369] opened 2015-06-30 19:05 UTC
starting rancher agent mostly goes fine, but not this time. 
I suspect the server gave an unexpected result on the queried URL, and the parser could be more robust and/or give a better error. 

sudo docker run -d --privileged -v /var/run/docker.sock:/var/run/docker.sock rancher/agent:v0.7.9 http://demo.mydomain.com/v1/scripts/2F1B9D5A2938BDDBA17D:1435687200000:k8Jokj23kmKJsw30PC0OSl3Wmd3w
```

INFO: Running Agent Registration Process, CATTLE_URL=http://demo.mydomain.com/v1
INFO: Checking for Docker version >= 1.6.0
INFO: Found Server version: 1.6.2
INFO: docker version: Client version: 1.6.0
INFO: docker version: Client API version: 1.18
INFO: docker version: Go version (client): go1.4.2
INFO: docker version: Git commit (client): 4749651
INFO: docker version: OS/Arch (client): linux/amd64
INFO: docker version: Server version: 1.6.2
INFO: docker version: Server API version: 1.18
INFO: docker version: Go version (server): go1.4.2
INFO: docker version: Git commit (server): 7c8fca2-dirty
INFO: docker version: OS/Arch (server): linux/amd64
INFO: docker 
INFO: Containers: 2
INFO: docker 
INFO: Images: 28
INFO: docker 
INFO: Storage Driver: overlay
INFO: docker 
INFO: Backing Filesystem: extfs
INFO: docker 
INFO: Execution Driver: native-0.2
INFO: docker 
INFO: Kernel Version: 4.0.5
INFO: docker 
INFO: Operating System: CoreOS 681.2.0
INFO: docker 
INFO: CPUs: 1
INFO: docker 
INFO: Total Memory: 593.9 MiB
INFO: docker 
INFO: Name: demo-rancher-client.c.careful-parser-780.internal
INFO: docker 
INFO: ID: OZMD:5QU4:VRQY:AOHZ:U6JN:UXW4:ANT6:LOZ4:O7X6:GQVD:OOYT:FIEB
INFO: Attempting to connect to: http://demo.mydomain.com/v1
INFO: http://demo.mydomain.com/v1 is accessible
INFO: Inspecting host capabilities
INFO: System: true
INFO: Host writable: true
INFO: Token: xxxxxxxx
INFO: Running registration
Traceback (most recent call last): 
  File "./register.py", line 32, in <module> 
    print "export CATTLE_ACCESS_KEY={}".format(r.accessKey) 
  File "/usr/local/lib/python2.7/dist-packages/gdapi.py", line 110, in __getattr__ 
    return getattr(self.__dict__, k)AttributeError: 'dict' object has no attribute 'accessKey'
```

**Comment by cjellick** [comment] 2015-07-06 18:45
@feliksik We're looking into this.
Still having the problem? Is it happening consistently? Has it happened on more than one host?

**Comment by feliksik** [comment] 2015-07-10 14:30
@cjellick it was happening consistenly on that host. But I have seen it only on one, so far. In fact, I looks like there is frequently something odd with registering a new host. Would it make sense to run the agent with other debug level (>INFO)? How?

**Comment by ibuildthecloud** [comment] 2015-07-10 14:40
There is a file /var/lib/rancher/state/.registration_key (or something close to that, not by a computer now).   Can you rename that and try again?  Don't delete it because it I'd like to debug this further, but I'm guessing that may fix things.

**Comment by cjellick** [comment] 2015-07-15 00:01
@ibuildthecloud i just experienced this after an ellaborate series of rancher container removes, starts, stops, restarts, mixed with some host reboots.

Let me know what you want to debug.

**Comment by sangeethah** [comment] 2015-07-24 15:04
Tested with rancher-server build- v0.29.0-rc2.

Sever version - v0.25.0
Rancher server deployed behing a proxy.
Rancher agent was started with "NO_PROXY" not set to the rancher server's ip address.
Rancher agent was able to connect successfully.

Upgrade to V0.29.0-rc2

After upgrade, rancher agent gets stuck in "reconnecting" state , since we do not allow for the agent to connect to server using a proxy anymore.

I rerun the Rancher agent command with "NO_PROXY" set to the rancher server's ip address. Rancher agent was able to connect back successfully without any issues.

When i had tested the same scenario with V0.28.0 , i hit the issue mentioned in the bug and agent would continue to be stuck in "reconnecting" issue . Closing this issue , since i did not hit the issue anymore.

Please reopen the issue, if you are still able to reproduce this issue.

**Closed by sangeethah** 2015-07-24 15:04 UTC
Labels: area/agent, kind/question, status/resolved
