### ISSUE TITLE
Feature request: Clone / Move services across Stacks

### ISSUE THREAD

**Issue by ahfeel** [rancher/rancher#4253] opened 2016-03-31 17:37 UTC
It would be great to be able to clone and / or move services across different stack. There's a lot of usecases for this, may it be duplicating a backup or monitoring or whatever service.

**Comment by xlight** [comment] 2016-12-08 02:33
+1

**Comment by kilmarnock** [comment] 2016-12-12 10:13
+1
Maybe a duplicate of  #3887

**Comment by easylo** [comment] 2017-01-11 09:56
+1

**Comment by vincent99** [comment] 2017-01-11 16:46
Yes, #3887

**Closed by vincent99** 2017-01-11 16:46 UTC
Labels: area/service, area/ui, kind/enhancement
