### ISSUE TITLE
Project member is not able to see namespaces in the projects using kubectl

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#11072] opened 2018-01-22 23:09 UTC
Rancher versions: 2.0 master 1/21

Steps to reproduce the problem:
Create user - user1.
Create a cluster - c1 and project p1.
Add "user1" as "project member" of p1.

Using kubectl , user1 is able to create namespace in project p1.
But he is not able to list any of the existing namespaces in p1 including the ones he has created.

**Comment by deniseschannon** [comment] 2018-01-22 23:19
Duplicate of https://github.com/rancher/rancher/issues/11062

**Closed by deniseschannon** 2018-01-22 23:19 UTC
Labels: kind/bug, version/2.0
