### ISSUE TITLE
NSenter fails to execute

### ISSUE THREAD

**Issue by cloudnautique** [rancher/rancher#3919] opened 2016-03-10 21:10 UTC
Rancher Version:
v0.63.0-rc2
Docker Version:
1.10.2
OS: 
Ubuntu 14.04
Steps to Reproduce: 
Deploy a global service.
at 60+ nodes in an environment add 10 + nodes at a time.

Results: 
As hosts register and pick up the global service containers, you start to see: 
```
Failed null, exit code [1] output [nsenter: failed to execute /var/lib/cattle/events/config.update: No such file or directory
]

```
in the logs.
Expected:

Containers/Nodes register without error messages.

**Comment by ibuildthecloud** [comment] 2016-03-18 23:26
Closing as a duplicate of https://github.com/rancher/rancher/issues/835

**Closed by ibuildthecloud** 2016-03-18 23:26 UTC
Labels: kind/bug, kind/performance, priority/1
