### ISSUE TITLE
private registry for workload cluster - let RancherUI freeze

### ISSUE THREAD

**Issue by curx** [rancher/rancher#25147] opened 2020-01-29 10:17 UTC
**What kind of request is this (question/bug/enhancement/feature request):**
bug

**Steps to reproduce (least amount of steps as possible):**

* run a rancher deployment
* add workload cluster
* go to Global > Cluster > Workload Cluster > Edit settings 
* private registry settings > Cluster is updateing

**Result:**
RancherUi is freeing (greyed)

![grafik](https://user-images.githubusercontent.com/875914/73347729-64105980-4288-11ea-9515-1de27190a0a6.png)

On the workload cluster the dockersecret is visible a the namespace cattle-system, only:
```
kubectl --namespace cattle-system get secrets cattle-private-registry
NAME                      TYPE                             DATA   AGE
cattle-private-registry   kubernetes.io/dockerconfigjson   1      40h
```

**Cluster information**
- rancher v2.3.4

gz#11072

gz#8083

**Comment by axeal** [comment] 2020-02-17 15:08
I have also reproduced this in v2.3.4 and v2.3.5, Rancher appears to be creating a badly formatted kubernetes.io/dockerconfigjson secret which the UI then fails to parse.

**Comment by deniseschannon** [comment] 2020-03-03 18:18
@axeal When do you add in a private registry?

**Comment by curx** [comment] 2020-03-03 20:33
@deniseschannon 

after added a workload cluster without a registry, reconfigure the private registry settings for this cluster with a valid registry. immediately the secret cattle-private-registry is setup in cattle-system and then go to the workload cluster > resources > registry credentials and the ui is freezed.

Hth,
Thorsten

**Comment by deniseschannon** [comment] 2020-03-04 22:48
Thanks @crux!

**Comment by maggieliu** [comment] 2020-04-16 17:58
QA and @westlywright both cannot reproduce this issue. Circling back with support to get a reproduction scenario.

**Comment by maggieliu** [comment] 2020-04-22 16:58
Additional Infor:

Rancher 2.3.3

There are two private registries at play here, the first is non-protected test one that was set up and the second is a password protected production ready registry

The issue itself is that you are getting auth errors when migrating from the old test registry to the newer production one, a change you are making in the private registry setting in cluster.yml

The workloads affected by this change have an error that reads as effectively 'Auth error, failed to pull image' - this includes the cattle cluster and node agents which are deploying first

---

Other environments that have been built form scratch with the production ready registry and the same credentials work from the start and have no issues

---

This only seems to affect the environment where you are migrating registry

---

You are using RHEL underneath and have sent over some logs for me to look through as well as some of the configuration files form RHEL docker that I have requested

**Comment by rancher-max** [comment] 2020-05-01 01:14
@maggieliu Can we get a bit of clarification on this part: `a change you are making in the private registry setting in cluster.yml`

My thought is that the registry change is done in the global settings as well as (or instead of?) the cluster settings. Changing the registry in the cluster.yml did not affect the cattle-system images, per: https://github.com/rancher/rancher/issues/20029#issuecomment-525072609 as these are always fetched from global `system-default-registry` setting. If there was no setting present for `system-default-registry`, then it fetched directly from docker.io.

I believe the user may be hitting that linked issue that is fixed in Rancher v2.3.4.


**I was able to reproduce this with the following in Rancher v2.3.3:**
1. Create Custom Cluster using private registry that is NOT password protected
2. Update Global setting `system-default-registry` to use the password protected private registry
3. Update private registry in cluster to use the password protected private registry

This triggers update for cattle-cluster-agent, cattle-node-agent, and kube-api-auth, which all fail  due to  `ImagePullBackOff`.

**Comment by leflambeur** [comment] 2020-05-06 16:15
Hey @rancher-max - in the cluster.yml you can set a default private registry - https://rancher.com/docs/rke/latest/en/config-options/private-registries/#default-registry

I would have expected that the cluster-scope private registries overwrote the global-scoped in the case of multi-tenancies unless I'm mistaken

Your replication is pretty exact though so probably answers it

Originally I believed this to be one big issue but it looks like this is multiple in that case (the images failing to pull can be discounted likely now)

The other issue is that if you change the cluster-scope registry credentials from non-protected to protected then when you navigate to System -> Registry Credentials the UI freezes - this occurs in 2.3.5

Originally I thought the reason it froze was because it got mangled, demonstrated by the UI then not being able to interpret it and then the images would fail but this does not seem the case - the UI freezing seems to be independent of the images not pulling

**Comment by rancher-max** [comment] 2020-05-07 21:05
@leflambeur Thanks for your updates! **I am able to recreate all of what was said above in Rancher v2.3.5**

**Steps are the same as previously noted:**
1. Create Custom Cluster using private registry that is NOT password protected
2. Update Global setting system-default-registry to use the password protected private registry
3. Update private registry in cluster to use the password protected private registry

**Results:**
- `cattle-cluster-agent`, `cattle-node-agent`, and `kube-api-auth` all fail to update and give `ImagePullBackOff`. These are ALL of the workloads present in `cattle-system` namespace
- Navigating to System Project --> Resources --> Secrets --> Registry Credentials causes the UI to freeze. Error in the console is: `Error: <ui@helper:t::ember689> helper requires value attribute.` at line 42 in -format-base.js. There are no network errors associated with this request (2 GET calls are made and both return 200)


**My assumption:**
I'm guessing that this is somehow all related, and fixing the main issue of "_I would have expected that the cluster-scope private registries overwrote the global-scoped in the case of multi-tenancies_" will fix both problems.

**Comment by rancher-max** [comment] 2020-05-07 23:04
A workaround is to remove the global `system-default-registry` and then edit the cluster again, setting the private registry (with username and password) to trigger an update. 

I believe that setting a global `system-default-registry` that is password protected will always fail and is not supported.

**Comment by axeal** [comment] 2020-08-04 13:37
As requested in the ticket, just updating below with my reproduction steps for the frozen UI in v2.3.4, although I see Max has subsequently reproduced:

1. Provision a single node custom cluster via Rancher v2.3.4
2. Edit the custom cluster to add a private registry URL: registry.example.com, username: username, password: password
3. Observe the System project -> secrets -> registry credentials view freezes
4. Observe following contents of the secret:
```
kubectl -n cattle-system get secret cattle-private-registry -o jsonpath="{.data.\.dockerconfigjson}" | base64 -d
{"username":"username","password":"password"}
```

By comparison, create the secret manually, observe the System project registry credentials view does not freeze and contents of the secret is as follows:

```
kubectl create secret docker-registry -n cattle-system cattle-private-registry --docker-server registry.example.com --docker-username=username --docker-password=password
kubectl -n cattle-system get secret cattle-private-registry -o jsonpath="{.data.\.dockerconfigjson}" | base64 -d
{"auths":{"registry.example.com":{"username":"username","password":"password","auth":"dXNlcm5hbWU6cGFzc3dvcmQ="}}}
```

**Comment by janeczku** [comment] 2020-08-10 13:17
**Reproduced in v.2.4.5: Cluster gets stuck in updating state after updating the private registry credentials or switching to a new registry.**

1. Create custom cluster with private registry enabled using authentication (registry.acme.com/docker-local)
2. Provision at least 5 nodes to reliably reproduce (possible race condition)
3. After the cluster provisioned, edit the cluster settings and update the registry information (registry.acme.com/docker). note: It could also be a different registry hostname.

Result:

- Cluster stuck forever in `updating` state.
- On multiple nodes the agent deployment is stuck in upgrading with ImagePullBackoff because it fails to do an authenticated pull from the new registry.
- Inspecting the Docker config (`/var/lib/kubelet/config.json`) on these nodes shows that the new registry configuration has not been applied (it still references registry.acme.com instead of registry-new.acme.com).

<img width="915" alt="Screenshot 2020-08-10 at 14 54 07" src="https://user-images.githubusercontent.com/3813921/89786591-7f53ff80-db1c-11ea-9626-2f70c424bae1.png">

**Comment by lisakh** [comment] 2020-11-20 22:01
After dockerhub download limits being in place adding private registry to an existing cluster is very highly needed feature. We run into this problem as well.

Rancher v2.4.8, Kubernetes 1.18.12, Docker 19.03.13, Debian 10, 14 nodes, 3 masters.

**Comment by cardoso81priscila** [comment] 2020-12-23 04:09
@cardoso81priscila
![20201130_163940](https://user-images.githubusercontent.com/75869019/102958396-82440100-44bb-11eb-9303-06861fe6ab49.jpg)

**Comment by cardoso81priscila** [comment] 2020-12-23 04:10
#28944

**Comment by axeal** [comment] 2020-12-24 13:05
There are two conflated issues here:

**Original issue tracked in this GitHub issue**
The original issue for which this GitHub issue was filed, related to a UI bug noted in Rancher v2.3.4, when attempting to view the System project registry credentials in the Rancher UI for a cluster with a private registry configured in the cluster settings. This was originally reported when enabling a private registry configuration for a cluster without one initially configured, and I also reproduced this scenario https://github.com/rancher/rancher/issues/25147#issuecomment-668601575 In further testing I was also able to reproduce this in v2.3.4 when configuring a Private Registry on a cluster at initial provisioning. 

Tests in Rancher v2.4.0, v2.4.8 and v2.5.3 show that this bug is no longer present in Rancher v2.4+, and I think this GitHub issue can be closed.

For the record an error observed in the browser Javascript console when the issue occurred in v2.3.4 was as below:

```
Uncaught (in promise) Error: <ui@helper:t::ember355> helper requires value attribute.
    at n.compute (-format-base.js:42)
    at t.compute (glimmer.js:791)
    at t.value (glimmer.js:384)
    at e.value (runtime.js:552)
    at e.t.initialize (reference.js:454)
    at e.t.peek (reference.js:429)
    at Function.n.initialize (runtime.js:901)
    at Object.evaluate (runtime.js:873)
    at e.t.evaluate (runtime.js:72)
    at e.t.evaluateSyscall (runtime.js:3471)
```

**Separate issue: Nodes fail to update, with cluster stuck in Upgrading state when attempting to update private registry details in Rancher provisioned cluster**
In comments on this issue a second bug has been reported on, in which nodes fail to update and the cluster becomes stuck in an upgrading state, when attempting to update private registry details in a Rancher provisioned cluster. I have also reproduced this behaviour and have opened a separate GitHub issue in https://github.com/rancher/rancher/issues/30628 to track this independently of the original issue filed here.

**Comment by deniseschannon** [comment] 2021-01-05 20:39
So from my understanding the original issue is fixed and the second issue is filed as a separate ticket.

**Comment by aaronRancher** [comment] 2021-01-06 22:08
Was able to reproduce this issue in Rancher `v2.3.4` using the steps above:
- Provision a single node custom cluster via Rancher v2.3.4
- Edit the custom cluster to add a private registry URL: registry.example.com, username: username, password: password
- Observe the System project -> secrets -> registry credentials view freezes
- Observe following contents of the secret:
```
kubectl -n cattle-system get secret cattle-private-registry -o jsonpath="{.data.\.dockerconfigjson}" | base64 -d
{"username":"username","password":"password"}
```
Result:
UI is inaccessible.
![Screen Shot 2021-01-06 at 10 57 30 AM](https://user-images.githubusercontent.com/57409052/103822351-305bb900-502d-11eb-9eb1-bf8a3917142e.png)

This bug is not reproduced on Rancher `v2.4-4544-head` and `master-head` `version 3af8dfa`:
System `Secrets` and `Registry Credentials` page is accessible.
![Screen Shot 2021-01-06 at 2 41 18 PM](https://user-images.githubusercontent.com/57409052/103822519-892b5180-502d-11eb-95d6-9465eb6dc6d9.png)

Closing this issue. Will continue to track the node update issue as a separate issue:  #30628

**Closed by aaronRancher** 2021-01-06 22:08 UTC
Labels: [zube]: To Test, area/cluster, internal, kind/bug, priority/0
