### ISSUE TITLE
Error while provisioning vSphere node driver cluster on env 7 for RKE1 and RKE2

### ISSUE THREAD

**Issue by rishabhmsra** [rancher/rancher#36691] opened 2022-03-01 17:36 UTC
**Rancher Server Setup**
- Rancher version: v2.6-head (e93a53c)
- Installation option (Docker install/Helm Chart): Docker

**Information about the Cluster**
- Kubernetes version: `v1.22.6-rancher1-2`
- Cluster Type (Local/Downstream):
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider): vSphere node driver (`1-node, all role`)

**Describe the bug**
- While provisioning a downstream vSphere node driver cluster getting following error:
```
2022/03/01 09:05:48 [INFO] Generating and uploading node config rishabh-worker2
2022/03/01 09:05:48 [INFO] Generating and uploading node config rishabh-etcd1
2022/03/01 09:05:48 [ERROR] error syncing 'c-gdts8/m-zfmxq': handler node-controller: Error creating machine: Error detecting OS: Too many retries waiting for SSH to be available.  Last error: Maximum number of retries (60) exceeded, requeuing
2022/03/01 09:05:48 [INFO] Generating and uploading node config rishabh-worker1
2022/03/01 09:05:48 [ERROR] error syncing 'c-gdts8/m-lxt9l': handler node-controller: Error creating machine: Error detecting OS: Too many retries waiting for SSH to be available.  Last error: Maximum number of retries (60) exceeded, requeuing 
```

**To Reproduce**

1. In `vSphere env 7` Created a VM using `sk-ubuntu-focal-amd64-esxi7` template.
2. Deployed rancher v2.6-head(e93a53c)
3. Using these two VM template - `ctw-cloud-ubuntu20` , `sk-ubuntu-focal-amd64-esxi7`, created a RKE1, single node, vSphere node driver cluster using k8s `v1.22.6-rancher1-2` (out-of-tree)
4. Cluster provisioning get stuck with message : `Waiting for etcd, controlplane and worker nodes to be registered`
5. Attaching the cluster yaml and rancher server logs:
[rancher-logs.txt](https://github.com/rancher/rancher/files/8163624/rancher-logs.txt)
[ootree-cluster-yaml.txt](https://github.com/rancher/rancher/files/8163599/ootree-cluster-yaml.txt)

**Comment by snasovich** [comment] 2022-03-09 20:33
@rishabhmsra , could you check if this is still reproducible on rebuilt vSphere testing environment?

**Comment by samkulkarni20** [comment] 2022-03-10 16:49
@Jono-SUSE-Rancher @rosskirkpat @slickwarren @Oats87 Posting the latest vsphere7 env findings here:
After reviewing & comparing the setup that Vivek created during the meeting yesterday we see below observations/outstanding issues:
1. The new templates i.e. sk-ubuntu-from-ovf-v1 & ubuntu-vm-esxi7-2 work with RKE1/RKE2 clusters when used with Rancher v2.6.3 server. The same templates fail when using v2.6-head Rancher server. IMO, this indicates that the env is ok, but something has changed after 2.6.3 release in Rancher vsphere node provisioning solution, which is causing this failure. Error:
```
[ERROR] error syncing 'c-lgdkp/m-g2ct4': handler node-controller: Error creating machine: Error in driver during machine creation: Panic in the driver: runtime error: invalid memory address or nil pointer dereference, requeuing
```
2. The vm ips keep changing even if there's no vm restart. I've seen this happen with a vm created with ova template only so far.
3. On RKE & RKE2 clusters created using Rancher v2.6.3, the volume mount is still failing with below error:
```
AttachVolume.Attach failed for volume "pvc-4f1485a1-d1cf-42f0-b1cf-a815c1b3134e" : rpc error: code = Internal desc = failed to attach disk: "524fe47a-8206-414c-bb48-09916f03e963" with node: "rke2-intree-test1-all-bdb4c425-qfmkw" err failed to attach cns volume: "524fe47a-8206-414c-bb48-09916f03e963" to node vm: "VirtualMachine:vm-564 [VirtualCenterHost: engqa-7-wrangler.fremont.rancherlabs.com, UUID: 4208e138-77d2-696b-293b-844e0e40e6ec, Datacenter: Datacenter [Datacenter: Datacenter:datacenter-3, VirtualCenterHost: engqa-7-wrangler.fremont.rancherlabs.com]]". fault: "(*types.LocalizedMethodFault)(0xc00039c660)({\n DynamicData: (types.DynamicData) {\n },\n Fault: (types.CnsFault) {\n BaseMethodFault: (types.BaseMethodFault) <nil>,\n Reason: (string) (len=16) \"VSLM task failed\"\n },\n LocalizedMessage: (string) (len=32) \"CnsFault error: VSLM task failed\"\n})\n". opId: "42aaec29"
```

**Comment by sowmyav27** [comment] 2022-03-11 20:25
@slickwarren Can you confirm if you saw this error reported [here](https://github.com/rancher/rancher/issues/36691#issuecomment-1064277818) "On RKE & RKE2 clusters created using Rancher v2.6.3, the volume mount is still failing with below error:"

**Comment by slickwarren** [comment] 2022-03-11 21:15
I have not tested volume mounts with the new setup, but I have not seen this issue in the past.

**Comment by slickwarren** [comment] 2022-03-15 00:26
still seeing this issue as of commit 80465bd

**Comment by anupama2501** [comment] 2022-03-15 03:58
Unable to create rke1 clusters on vsphere 99974f0

**Comment by rishabhmsra** [comment] 2022-03-17 15:49
Seeing panic error on vSphere 6.7 env as well.
On rancher `v2.6.4-rc9` provisioned a RKE1 single node, vSphere node driver cluster using k8s `v1.23.4-rancher1-1`. It's erring out with below rancher server logs :
```
2022/03/17 08:21:00 [ERROR] error syncing 'c-d8snx/m-97t7x': handler node-controller: Error creating machine: Error in driver during machine creation: Panic in the driver: runtime error: invalid memory address or nil pointer dereference, requeuing
```

**Comment by rosskirkpat** [comment] 2022-03-18 18:52
This is fixed in v2.6.4-rc10 and was available for testing on 2.6-head after this [drone-publish build ](https://drone-publish.rancher.io/rancher/rancher/7504) finished on Mar 16, 2022 at around 9pm ET.

**Comment by sirredbeard** [comment] 2022-03-18 20:55
Testing template is pending, after outstanding regressions are addressed.

**Comment by rosskirkpat** [comment] 2022-03-19 23:30
Testing Template for @sowmyav27 and @slickwarren to accompany moving this issue back to `To Test`

### Root cause

This panic (below) was a multi-faceted problem:

- mkisofs not existing in a rancher jail for rke1 vsphere clusters (https://github.com/rancher/rancher/pull/36850)
- mkisofs not being in the proper path for rancher (needs to be `/usr/bin/mkisofs` inside the jail, https://github.com/rancher/rancher/pull/36927)
- mkisofs exec.command needed a path set for it to function inside the jail (https://github.com/rancher/rancher/pull/36927)


```console
[ERROR] error syncing 'c-lgdkp/m-g2ct4': handler node-controller: Error creating machine: Error in driver during machine creation: Panic in the driver: runtime error: invalid memory address or nil pointer dereference, requeuing
```
 
### What was fixed, or what changes have occurred

- mkisofs not existing in a rancher jail for rke1 vsphere clusters (https://github.com/rancher/rancher/pull/36850)
    - mkisofs was added to the jailer.sh script as well as the package/Dockerfile
- mkisofs not being in the proper path for rancher (needs to be `/usr/bin/mkisofs` inside the jail, https://github.com/rancher/rancher/pull/36927)
    - mkisofs now exists in each rancher jail in `/opt/jail/$NAME/usr/binmkisofs`
- mkisofs exec.command needed a path set for it to function inside the jail (https://github.com/rancher/rancher/pull/36927)
    - the exec.Command for mkisofs now uses the PATH set by the rancher-machine command

### Areas or cases that should be tested

RKE1 vsphere provisioning clusters in the following scenarions:

- new vsphere rke1 cluster in Rancher v2.6.4
- Rancher v2.6.3 -> v2.6.4 upgrade and check downstream rke1 vsphere clusters
- Rancher v2.6.3 -> v2.6.4 upgrade and then upgrading an existing downstream rke1 vsphere cluster
- on v2.6.4, upgrading an existing rke1 cluster and then replacing or adding nodes

### What areas could experience regressions?

The versions of rancher/machine with the regression do not exist in a stable Rancher release.

### Are the repro steps accurate/minimal?

Yes, the standard procedure for testing rke1 vsphere clusters will verify that the bug is fixed.


Please note, there is no Windows support in the RKE1 vsphere node driver. 

This is fixed in v2.6.4-rc10 and was available for testing on 2.6-head after this drone-publish build finished on Mar 16, 2022 at around 9pm ET.

**Comment by samkulkarni20** [comment] 2022-03-22 04:33
Removing label `team/infracloud` since Team 4 is taking this up.

**Comment by slickwarren** [comment] 2022-03-22 17:09
Tested on v2.6-head (024e6fa):
* provision rke1 1.23 cluster -- pass
  * tested single node-per-role -- pass
* provision rke2 1.23 cluster -- pass

**Closed by slickwarren** 2022-03-22 17:09 UTC
Labels: alpha-priority/0, [zube]: QA Next up, status/release-blocker, team/area4
