### ISSUE TITLE
[rke2] unable to deploy production-ready setup with RKE2 linux node driver (3etcd, 2cp, 3worker)

### ISSUE THREAD

**Issue by slickwarren** [rancher/rancher#37252] opened 2022-04-08 22:21 UTC
**Rancher Server Setup**
- Rancher version: v2.6-head (4a5a926)
- Installation option (Docker install/Helm Chart): helm
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): rke1, v1.3.9
- Proxy/Cert Details: valid certs

**Information about the Cluster**
- Kubernetes version: v1.22.8+rke2r1
- Cluster Type (Local/Downstream): downstream
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider): linode node driver

**User Information**
- What is the role of the user logged in? (Admin/Cluster Owner/Cluster Member/Project Owner/Project Member/Custom): admin

   
**Describe the bug**
when deploying a cluster using linode rke2 driver, the cluster fails to come up. Some nodes are failing due to an error. 

**To Reproduce**
* deploy an rke2 cluster using 1.22.8+rke2r1 with 3etcd, 2cp, 3workers. 

**Result**
some nodes are in this state:
```

 CreateError: Downloading driver from https://<rancher_server>/assets/docker-machine-driver-linode Doing /etc/rancher/ssl docker-machine-driver-linode docker-machine-driver-linode: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), statically linked, stripped Running pre-create checks... (ctw-rke2l-c-cf141e4e-nk4gr) Generating a secure disposable linode-root-pass... Creating machine... (ctw-rke2l-c-cf141e4e-nk4gr) Creating Linode machine instance... Error creating machine: Error in driver during machine creation: [408] Please try again The default lines below are for a sh/bash shell, you can specify the shell you're using, with the --shell flag
```

and the cluster never registers any worker nodes. 

**Expected Result**
linode should work with RKE2 when using multiple nodes in the setup

**Screenshots**
<img width="1508" alt="Screen Shot 2022-04-08 at 3 14 11 PM" src="https://user-images.githubusercontent.com/16691014/162541598-b1b363ce-bced-4bf5-8de5-b7ad122fa52c.png">

**Additional context**
a single node rke2 cluster came up fine with the same k8s version

**Comment by thedadams** [comment] 2022-04-15 21:44
### Root cause
The root cause here was the Linode API not being about to handle the number of requests we were making.

### What was fixed, or what changes have occurred
The error is still likely to occur, but Rancher will not retry if the request to create the machines fails for some reason.

### Areas or cases that should be tested
Provisioning an RKE2 cluster in Linode as described in the description.

### What areas could experience regressions?
Creating machines.

### Are the repro steps accurate/minimal?
Yes.

**Comment by timhaneunsoo** [comment] 2022-04-18 15:43
Closing this issue as duplicate of [36939](https://github.com/rancher/rancher/issues/36939)

**Closed by timhaneunsoo** 2022-04-18 15:43 UTC
Labels: area/machine, kind/bug-qa, [zube]: To Test, area/provisioning-v2, area/provisioning-rke2, feature/rancher-machine, team/area2
