### ISSUE TITLE
core dns is in CrashLoopBackOff state in Rancher in an upgraded cluster from 1.15 to 1.16

### ISSUE THREAD

**Issue by sowmyav27** [rancher/rancher#26270] opened 2020-03-26 02:30 UTC
**What kind of request is this (question/bug/enhancement/feature request):** bug

**Steps to reproduce (least amount of steps as possible):**

Actions performed on the cluster:

- Upgrade cluster k8s version from 1.15 to 1.16
- Upgrade cluster using kubelet - max-pods value
- Add worker nodes
- Power off/power on worker nodes

**Actual Result:**
The coredns pods have NOT upgraded to `rancher/coredns-coredns:1.6.2`.
They are in a CrashLoopBackOff state

**Other details that may be helpful:**
**Note:**
No specific steps to reproduce this issue

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): master-head - commit id: `e78331527`
- Installation option (single install/HA): single

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): rke do
- Kubernetes version (use `kubectl version`):

```
1.15.11 to 1.16.8
```

**Comment by mrajashree** [comment] 2020-03-30 22:10
Tried the steps a few times, unable to repro with master-head commit id `e6856fd`

**Comment by deniseschannon** [comment] 2020-04-17 00:41
Moving this out until it's reproduced. @sowmyav27 If you hit it, please provide a setup to @mrajashree

**Comment by SheilaghM** [comment] 2021-04-13 20:07
Closing. These versions are no longer supported and we are unable to reproduce.

**Closed** 2021-04-13 20:07 UTC
Labels: [zube]: Done, kind/bug-qa
