### ISSUE TITLE
Alert Driver chart install not being registered by the UI

### ISSUE THREAD

**Issue by nickwsuse** [rancher/rancher#40483] opened 2023-02-07 18:52 UTC
**Setup**
- Rancher version: v2.6-head ID: 8245868
- Browser type & version: Chrome Version 109.0.5414.119 (Official Build) (arm64)

**Describe the bug**

After installing the Alert Drivers chart, if you go back to the chart's page it doesn't appear to be installed as the action button still says `Install` and none of the versions listed show that they're the currently installed version. If you check the namespace that the chart was installed in, you can see that the pods exist and are running, but for some reason the UI is not registering that the chart is actually installed.

If you click the `Install` button, it'll take you through the install process again. If you try to install the chart in the same namespace again, you'll get an error stating that the chart is already installed.

**To Reproduce**

1. Set up a v2.6-head Rancher instance
2. In either the local or a downstream cluster, go to the Apps page
3. Install the Monitoring chart first
4. Go back to the Apps page
5. Open the Alert Drivers chart
6. Click install
7. Set the namespace to the `cattle-monitoring-system` namespace
8. Check either of the checkboxes (I left SMS checked)
9. Finish the install of the chart
10. See successful install in the shell
11. Go back to Apps > Alerting Drivers

**Result**
The UI shows that the Alerting Drivers chart isn't installed even though it was successfully installed, and therefore you're unable to upgrade or edit the install

**Expected Result**
The UI shows the chart is installed if it actually is (in this case it is, or at least appears to be from my checking)

**Screenshots**
![image](https://user-images.githubusercontent.com/107147272/217337814-a8a1d0ef-4fea-4129-8525-ab590df7b1a3.png)

![image](https://user-images.githubusercontent.com/107147272/217338268-cdc51adf-c358-49ae-a5ef-33efcadcd069.png)

**Additional context**
This is occurring on v2.7-head as well

**Comment by aiyengar2** [comment] 2023-02-09 23:03
@nwmac @nickwsuse this is as designed. The annotation should not be added as it is not a singleton:

> Otherwise it is assumed that the Helm chart can be installed multiple times in a cluster.

This is true for Alerting Drivers.

---

## Context

### What is Alerting Drivers?

The Alerting Drivers Helm chart is intended to help users deploy [non-native notification mechanisms such as those listed in the Alertmanager docs](https://prometheus.io/docs/operating/integrations/#alertmanager-webhook-receiver). Currently we support, Sachet for SMS or prom2teams for Microsoft Teams.

Once you have Alerting Drivers installed, updating your Alertmanager configuration to add a [Webhook Receiver](https://prometheus.io/docs/alerting/latest/configuration/#webhook_config) where the `url` points to the Service deployed by the chart is all you need to get **any** Alertmanager (cluster or project level) to point to **any** driver deployed by Alerting Drivers.

### Why is Alerting Drivers Not A Singleton?

While our Rancher UI supports creating receivers on the **cluster** Alertmanager to point to the Alerting Drivers Helm chart in the `cattle-monitoring-system` namespace, it's a perfectly valid solution for a user to deploy a separate version of the Alerting Drivers Helm chart in a project-specific namespace (i.e. `default`) and configure their Project Alertmanager to point a webhook receiver towards that deployment.

In a multi-tenant environment where each project is owned by a different team, this allows individual tenants to configure Alerting Drivers independently with their Project Monitoring stack.

**Comment by aiyengar2** [comment] 2023-02-09 23:11
To upgrade an existing instance of Alerting Drivers, two possible paths should be tested (and addressed by UI if there are any issues):
1. You should be able to go to the Installed Apps page and click on the three dots, click Edit/Upgrade, and upgrade the namespace-specific installed app
2. If you selected the Alerting Drivers app on the catalog, clicked on install, and selected a namespace where Alerting Drivers is already installed into, you should reach a page where you can `Edit as YAML` the release or use the `questions.yml` to configure the chart. Here, two things need to be checked
  a. When you trigger the install / upgrade, it should successfully work. Specifically, it should trigger a `helm upgrade`, not a `helm install` since UI should be detecting that the chart has already been installed onto this namespace
  b. If you initially overrode values for the chart on an install, UI should be pulling in those overridden values in the `Edit as YAML` page. On an in-place upgrade, it should not be reverting back to defaults.

**Comment by prachidamle** [comment] 2023-02-10 00:25
Moving tis to-test to ensure user experience is correct after install for the above cases mentioned in here https://github.com/rancher/rancher/issues/40483#issuecomment-1424962774

**Comment by nwmac** [comment] 2023-02-10 09:17
@aiyengar2 Thanks - when I try and install Alerting Drivers more than once in different namespaces, it fails with:

```
Error: INSTALLATION FAILED: rendered manifests contain a resource that already exists. Unable to continue with install: ClusterRole "rancher-alerting-drivers-admin" in namespace "" exists and cannot be imported into the current release: invalid ownership metadata; annotation validation error: key "meta.helm.sh/release-namespace" must equal "default": current value is "neil-test"
```

**Comment by prachidamle** [comment] 2023-04-24 20:35
@mitulshah-suse Can your team take a look at this?

**Comment by mitulshah-suse** [comment] 2023-04-25 10:15
There are 2 parts to this issue.

**Chart setup:**
Based on the above discussion, it appears that the chart is expected to install successfully on multiple namespaces. If that is the case, the chart itself has multiple cluster scoped resources like ClusterRoles which would block the installation as seen in the comment above. https://github.com/rancher/rancher/issues/40483#issuecomment-1425473768
The possible solutions to this would be 

- either move the clusterroles and other cluster scoped resources to a separate chart which is marked as a prerequisite for this chart and only installed once. 
- or append namespace names to such resources, so that different ones are created each time and they dont conflict with each other.

**UI setup**
The UI also does not seem to recognize whether the chart is currently installed in a particular namespace or not. It simply seems to run `helm install` on all the namespaces even if its an upgrade for a particular namespace which is also causing failures.

**Comment by mitulshah-suse** [comment] 2023-04-26 05:02
Below screenshot has list of resources being created. As you can see there are a few cluster-scoped resources in the list.
Additionally there is another template for hardened clusters as well which has more such resources.

![image](https://user-images.githubusercontent.com/109796209/234473979-a8a52c96-894e-44ac-ad3c-dfee95867a37.png)

@prachidamle Please advise on which approach from the above https://github.com/rancher/rancher/issues/40483#issuecomment-1521535013 is preferable.

**Comment by prachidamle** [comment] 2023-05-10 00:02
Checked with @aiyengar2 and he suggested converting cluster scoped resources to namespaced resources would be a good appraoch to take here @mitulshah-suse @doflamingo721

**Closed** 2023-05-30 21:20 UTC
Labels: kind/bug, area/alerting, [zube]: QA Working, team/area3, team/infracloud
