### ISSUE TITLE
Grafana Etcd Graph for memory isn't restricted to etcd nodes

### ISSUE THREAD

**Issue by cloudnautique** [rancher/rancher#19694] opened 2019-04-18 00:33 UTC
The etcd grafana graph tile for memory shows all nodes in the cluster not just the etcd nodes. This needs to be pared down.

![Screen Shot 2019-04-17 at 5 31 28 PM](https://user-images.githubusercontent.com/1989084/56329125-d7504100-6136-11e9-8d57-7040ebfd9982.png)

**Comment by mallardduck** [comment] 2024-03-22 18:24
hey @MKlimuszka - I've done some testing on both RKE1 and RKE2 and confirmed the issue isn't present today. Granted I'm using modern/current versions of the runtimes, Rancher and rancher-monitoring. So a lot could have changed since 2019 that caused this to be fixed in that time span. Tested and confirmed working on both 2.7.x and 2.8.x rancher.

Granted, in testing K3S i found this dashboard wasn't enabled at all out of the box - per the chart logic - so I assume that's out of scope. I did do some "hacky" testing with this on k3s out of curiosity, even if that's beyond the current scope of "supported" at this time. Expectedly it produced unreliable results however different than the ones in this bug report.

**Closed** 2024-03-26 16:42 UTC
Labels: kind/bug, area/monitoring, status/to-reproduce, [zube]: Unscheduled, team/observability&backup
