### ISSUE TITLE
Unable to provision RKE2 clusters using Amazon cloud provider with k8s 1.22

### ISSUE THREAD

**Issue by davidnuzik** [rancher/rancher#35618] opened 2021-11-19 22:35 UTC
**Summary:**

I'm unable to provision any ec2 RKE2 clusters with Amazon cloud provider option.

-----

**Environment:**
Rancher version: v2.6-head `b736007` (also seen on `9740d7a` build from earlier today) 11/19/2021
Rancher cluster type: single-node docker install and HA helm install both attempted
 
Downstream cluster type: RKE2 w/ ec2 node driver and amazon cloud provider
Downstream K8s version: v1.21.6+rke2r1

**Steps to Reproduce:**
1. Provision an RKE2 cluster with ec2 node driver. Set up amazon cloud provider.
2. The cluster is stuck in provisioning state forever. It is stuck on step `waiting on probes: calico`
3. Try provisioning an ec2 rke2 cluster but without cloud provider. This works.
 
**Expected Result:**
I expected to be able provision an RKE2 cluster using the amazon cloud provider.

**Actual Result:**
I cannot provision an RKE2 cluster using the amazon cloud provider. This was working recently, just yesterday.

**Additional Info:**
I attempted to do my due diligence. I didn't spot anything in rancher server logs of use. When I downloaded the SSH key to remove in to the node and investigate the SSH key does not work (and I don't think I made any mistakes using the rancher provided key).

**Comment by thedadams** [comment] 2021-11-23 21:53
RKE2 PR: https://github.com/rancher/rke2/pull/2163

**Comment by thedadams** [comment] 2021-11-24 00:43
It was decided that the best way to fix this issue was through RKE2 (the PR is linked).

There is a work-around for this issue: add the environment variable `CATTLE_MACHINE_PROVISION_IMAGE` to `rancher/machine:v0.15.0-rancher72`. This will not set the hostname on the EC2 nodes and this will allow provisioning to continue. This can be used until the RKE2 fix is available.

NOTE: this is only for RKE2 clusters provisioned from Rancher with the AWS cloud provider enabled. All other provisioning is unaffected.

**Comment by snasovich** [comment] 2021-11-24 03:55
@thedadams , thank you. Depending on which RKE2 version the fix is going into and whether it's included in 2.6.3 release's KDM, we may want to add this workaround to release notes hence `release-note` label.

**Comment by rancher-max** [comment] 2021-12-01 04:57
Gave this a quick check using KDM branch `dev-v2.6` on rancher v2.6.3-rc3. I was able to provision a v1.21.7-rc2+rke2r1 cluster using aws cloud provider.

After ssh'ing to a node, I see the following config:
```yaml
# $ sudo cat /etc/rancher/rke2/config.yaml.d/50-rancher.yaml
{
  "advertise-address": "<redacted>",
  "agent-token": "<redacted>",
  "cloud-provider-name": "aws",
  "cni": "calico",
  "disable-kube-proxy": false,
  "etcd-expose-metrics": false,
  "etcd-snapshot-retention": 5,
  "etcd-snapshot-schedule-cron": "0 */5 * * *",
  "node-ip": [
    "<redacted>"
  ],
  "node-label": [
    "rke.cattle.io/machine=7e6f0cba-7972-437f-b6d1-66a6fb1f94cb"
  ],
  "private-registry": "/etc/rancher/rke2/registries.yaml",
  "protect-kernel-defaults": false,
  "tls-san": [
    "<redacted>"
  ],
  "token": "<redacted>"
}
```

The cluster is healthy in the rancher UI and running successfully. I'll leave this open so that we can validate with v1.22 when that is functional as well.

**Comment by davidnuzik** [comment] 2021-12-07 17:14
(Waiting for https://github.com/rancher/rancher/issues/35683 so we can test 1.22.x)

**Comment by sowmyav27** [comment] 2021-12-10 01:58
Moving it out of 2.6.3 since 1.22 is experimental in this release. And 1.21RKE2 version works.

**Comment by davidnuzik** [comment] 2022-02-01 23:12
Putting this on pause for https://github.com/rancher/dashboard/issues/5023

**Comment by davidnuzik** [comment] 2022-02-02 16:59
**My checks Failed**
 
**Reproduction Steps:**

Not required.

-----
 
**Validation Environment:**

Rancher version: v2.6-head `da382a8` 2/1/2022
Rancher cluster type: single-node docker install
Docker version: 20.10
 
Downstream cluster type: rke2
Downstream K8s version: v1.22.6+rke2r1 marked as (experimental) in KDM / the dashboard UI
 
**Validation steps:**

1. Create an RKE2 cluster using the EC2 node driver. Pick Amazon as the cloud provider and provide the necessary IAM role.
2. The cluster still is stuck in a Provisioning state with same issue - waiting for probes: calico
 
**Additional Info:**
As normal, I checked web requests/responses and these appear nominal as well. (fleet-default POST includes IAM role and provisioning.cattle.io.clusters contained cloud-provider-name in rkeConfig). I suspect this to be a backend issue still.

**Comment by thedadams** [comment] 2022-02-02 20:54
@davidnuzik I know what the problem is here. I will reopen the issue.

**Comment by davidnuzik** [comment] 2022-02-02 21:41
Thanks @thedadams I just updated my prior comment too, but sounds like you already know the issue. Let me know if there is anything I can do; appreciate it.

**Comment by thedadams** [comment] 2022-02-02 21:47
This issue is waiting for an RKE2 release. It should be noted that it was me who is doing the work (and did the work that didn't fix it the first time).

**Comment by snasovich** [comment] 2022-02-15 20:34
Given the timing on issues linked above the expectation is for these fixes to be available in Feb k8s patches releases of RKE2. No additional changes are believed to be needed on Rancher side.

**Comment by Auston-Ivison-Suse** [comment] 2022-03-08 20:46
**Reproduction Setup**
- Rancher version: v2.6-head(3df76e4)
- Downstream clusters: rke2, k8s version: v1.21.10+rke2r1 & v1.22.7+rke2r1

**Results of testing**
After following the reproduction steps in the original issue I found that the 1.22.7 k8s version did not successfully provision where as the 1.21.10 did successfully provision. 

Moved to reopen after reproducing the issue again.

**Closed** 2022-03-09 16:41 UTC
Labels: kind/bug-qa, [zube]: QA Working, release-note, dependency-rke2, area/provisioning-rke2, team/area2
