### ISSUE TITLE
Can't remove RKE2 cluster if Harvester Cloud Credential is deleted

### ISSUE THREAD

**Issue by FrankYang0529** [rancher/rancher#36294] opened 2022-01-27 08:17 UTC
**Rancher Server Setup**
- Rancher version: v2.6.3
- Installation option (Docker install/Helm Chart): Docker

**Information about the Cluster**
- Kubernetes version: v1.21.8+rke2r2
- Cluster Type (Local/Downstream): Harvester

**User Information**
- What is the role of the user logged in? Admin

**Describe the bug**

Users can remove cloud credentials if there is an RKE2 cluster based on it. After that, we will get an error message in the `machine-provision-remove` handler.

Also, if users only delete the Harvester cluster CR but remain the cloud credential, we can remove the RKE2 cluster without error. However, associated VMs in the Harvester cluster can't be removed together.

**To Reproduce**
1. Import Harvester Cluster.
2. Create a Cloud Credential.
3. Create an RKE2 cluster based on Harvester.
4. Remove the Harvester cloud credential.
5. Remove the RKE2 cluster.

**Result**
RKE2 cluster status is stuck in `Removing` and there is an error message in the `machine-provision-remove` handler.

```
2022/01/27 03:15:33 [ERROR] error syncing 'fleet-default/rke2-in-aws-pool1-7c09ec84-8jv8n': handler machine-provision-remove: secrets "cc-k4t8n" not found, requeuing
```

**Expected Result**
* Prevent users from deleting Cloud Credentials or Harvester cluster CR if there is an RKE2 cluster based on it.
* Remove cluster-agent in Harvester if users remove Harvester cluster CR in Rancher.

**Related issue**
https://github.com/harvester/harvester/issues/1799

**Comment by FrankYang0529** [comment] 2022-02-15 10:05
@thedadams, I try this case for AWS. There are also error logs like the following.

```
[ERROR] error syncing 'fleet-default/rke2-in-aws-pool1-7c09ec84-msbq6': handler machine-provision-remove: secrets "cc-dbsgw" not found, requeuing
```

Reproduce steps:
1. Create AWS credential.
2. Create an RKE2 cluster on AWS.
3. After the provisioning job is done, delete the credential.
4. Remove the RKE2 cluster.


https://user-images.githubusercontent.com/4927361/154038942-85d70c67-d88f-4f94-a80c-78518c1cbf87.mov

**Comment by thedadams** [comment] 2022-02-16 01:15
### Root cause
The root cause was that cloud credentials could be deleted even when there was a provisioning cluster that was using the cloud credential.

### What was fixed, or what changes have occurred
Now, a user cannot delete a cloud credential if it is being used by a provisioning cluster.

### Areas or cases that should be tested
1. Create a cloud credential
2. Provision an RKE2/K3S cluster
3. Try to delete the cloud credential. An error should be returned.
4. Delete the RKE2/K3S cluster
5. Try to delete the cloud credential. This should be successful now.

### What areas could experience regressions?
Deleting cloud credentials

### Are the repro steps accurate/minimal?
Yes

**Comment by noahgildersleeve** [comment] 2022-02-24 02:01
Tested in Harvester `master-bfd6a8a9-head` and Rancher `948355c`. You can still delete the cloud credential without an error when there is a cluster created with it.
## Verification steps
1. Import Harvester into Rancher
2. Create a cloud credential for Harvester
3. Create a new RKE2 cluster
4. Delete the cloud credential being used for the RKE2 cluster

If you go into the cluster config now you get an error that the secret is missing
![Screenshot from 2022-02-23 17-59-39](https://user-images.githubusercontent.com/83787952/155443035-66925421-babd-4f53-8fa6-d97fee653704.png)

**Comment by thedadams** [comment] 2022-02-24 02:14
@noahgildersleeve how are you deleting the cloud credential? Through the UI?

**Comment by noahgildersleeve** [comment] 2022-02-25 02:35
I'm re-testing this with v2.6.4-rc4 because my image for the deploy might have been old.

**Comment by noahgildersleeve** [comment] 2022-02-25 21:34
Tested in rancher `v2.6.4-rc4` with Harvester `master-bfd6a8a9-head`. Verified as fixed with previous steps
## Verification steps

1. Import Harvester into Rancher
2. Create a cloud credential for Harvester
3. Create a new RKE2 cluster
4. Delete the cloud credential being used for the RKE2 cluster
5. Validate that you get an error
![Screenshot from 2022-02-25 13-31-46](https://user-images.githubusercontent.com/83787952/155806018-e723bf3b-624a-4676-8694-842376d4fab0.png)

**Closed by noahgildersleeve** 2022-02-25 21:34 UTC
Labels: kind/bug, [zube]: QA Working, area/harvester, team/area2
