### ISSUE TITLE
Rancher error sync rke2 etcd snapshot and showing 0 byte size

### ISSUE THREAD

**Issue by MKlimuszka** [rancher/rancher#40248] opened 2023-01-23 16:41 UTC
Rancher Cluster:
Rancher version: 2.6.9 (upgraded from 2.6.4)
Number of nodes: N/A
Node OS version: SLES15 SP3

Downstream Cluster:
Number of Downstream clusters: N/A
Node OS: SLES15 SP3
RKE/RKE2/K3S version: RKE2
Kubernetes version: 1.24.7
CNI: N/A

Longhorn:
No Longhorn

Issue description:
Customer facing an issue with RKE2 cluster snapshot.
The snapshot is taken and being shown on the list but with 0 byte size
ETCD throwing continuous errors trying to sync.

Business impact:
critical as the customer does not have a backup to rely on.

Troubleshooting steps:
edit yaml file to disable it and re-enable it again but no luck.
SSH into master node
The snapshot exists on the master nodes with the right time and size

Repro steps:
Create an RKE2 cluster
Take snapshot for that cluster
Check the list of snapshots
The snapshots appearing on the UI but with 0 byte size and wrong date (age of snapshot)

Workaround:
Is workararound available and implemented? NO

Actual behavior:
The snapshots of RKE2 should appears on the list with the right time and appropriate size
ETCD throwing errors not syncing with downstream cluster

Expected behavior:
The snapshots of RKE2 should appears on the list with the right time (age) and appropriate size.

Files, logs, traces:
[ERROR] error syncing 'kube-system/rke2-etcd-snapshots': handler snapshotbackpopulate: error while retrieving cluster local from cache via index: Index with name by-cluster does not exist, requeuing
[ERROR] error syncing 'kube-system/rke2-etcd-snapshots': handler snapshotbackpopulate: error while retrieving cluster c-m-frtz2drj from cache via index: Index with name by-cluster does not exist, requeuing

SURE-5650

**Comment by MKlimuszka** [comment] 2023-01-23 16:42
Possible related bug: https://github.com/rancher/rancher/issues/39703

This needs to be reproduced in 2023-Q1-2.6x, 2023-Q1-2.6x, and if it cannot be reproduced in those, 2.6.9

**Comment by eliyamlevy** [comment] 2023-02-27 17:47
@MKlimuszka I was _**not**_ able to reproduce issue on either 2.7-head or 2.6-head. Worked with @ronhorton to recreate the same setup, except we used SLES15 SP4 instead of SLES15 SP3.

**Comment by eliyamlevy** [comment] 2023-02-27 20:16
However, I was able to reproduce in Rancher `v2.6.9` on an RKE2 cluster `v1.24.9+rke2r2`. 

<img width="1425" alt="Screen Shot 2023-02-27 at 3 12 06 PM" src="https://user-images.githubusercontent.com/31217626/221673361-41b658ce-9c49-425e-a17c-a071fcbd05e2.png">
As shown above the snapshot does not have a status or size.


<img width="383" alt="Screen Shot 2023-02-27 at 3 12 18 PM" src="https://user-images.githubusercontent.com/31217626/221673800-8b774f33-8eae-4129-8739-812c01629d5f.png">
 When I clicked on the file it did have the correct timestamp.


<img width="664" alt="Screen Shot 2023-02-27 at 3 11 53 PM" src="https://user-images.githubusercontent.com/31217626/221673852-8d60ff1f-9df0-457a-b644-aacd277d91c7.png">
When SSHing on to the node, the backup size seemed correct.

**Comment by snasovich** [comment] 2023-03-01 00:04
Reopening for potential additional investigations.

**Comment by niusmallnan** [comment] 2023-03-01 01:08
For SLES OS, if `/usr/local` is a mount point, it may cause the rke2 cli not to be placed in the expected directory.

This may be a clue https://github.com/rancher/rancher/issues/40624

**Comment by snasovich** [comment] 2023-03-02 18:41
After additional testing this issue does indeed seem to be only reproducible on cases where there are multiple Rancher replicas, so closing it.
Will reopen if it turns out to not be so.

**Closed by snasovich** 2023-03-02 18:41 UTC
Labels: kind/bug, internal, area/backup-recover, [zube]: To Triage, team/area2

**Comment by snasovich** [comment] 2023-03-02 21:57
@Martin-Weiss , nothing wrong with having multiple Rancher replicas (and in fact, the default is 3 for HA setups), but there is a bug in all currently released versions (more info in this PR: https://github.com/rancher/rancher/pull/39622) that has the fix tested for inclusion in 2.6.11/2.7.2.

**Comment by Martin-Weiss** [comment] 2023-03-03 07:32
> @Martin-Weiss , nothing wrong with having multiple Rancher replicas (and in fact, the default is 3 for HA setups), but there is a bug in all currently released versions (more info in this PR: #39622) that has the fix tested for inclusion in 2.6.11/2.7.2.

Ok - cool - so the message is not “reduce to replica=1” ;-) - we “just” need to wait until next rancher release for the fix.. Thanks!!

**Comment by Velociraptor85** [comment] 2024-04-22 14:18
I have the same situation on an rancher 2.8.2 managing 1.26 also after updating to 1.27.10+rke2r1

**Comment by Andrew920** [comment] 2024-04-23 09:30
I'm also experiencing this problem. Tested in rancher 2.8.2 and 2.8.3 with kubernetes version  v1.27.10 +rke2r1 and  v1.27.12 +rke2r1 with 3 masters and 3 workers. The error persists no matter if s3 is turned on or off. And the files are saved successfully locally and on s3. Is there any work arround? Cloud upgrading kubernetes to version 1.28 solve this?

**Comment by harridu** [comment] 2024-07-01 20:50
I've got this problem for Rancher v2.8.4 for 2 managed clusters. Obviously Rancher and the managed cluster disagree about the backups. Is there some way to resync without messing around with the numbers of backups, the backup schedule, manually removing files, etc., all indicating that the real problem is not understood yet?
