### ISSUE TITLE
Not able to enable Istio in cluster. Istio-pilot workload stuck in "Updating" state.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#20702] opened 2019-06-06 15:02 UTC
Rancher Server version - Build from mater Jun 6 
Steps to reproduce the problem:
Create a DO cluster with 3 nodes all roles ( 1 CPU/2GB Mem).
Enable Istio.
Fails to get enabled , with following error message presented to user
```
“Please make sure you have at least one node with 2048 MiB of memory available to deploy Pilot workload.”
```
Add 1 more Worker node ( 2 CPU/4GB Mem).
Enable Istio.
Stuck on trying to enable isto.

![Screen Shot 2019-06-06 at 8.00.00 AM.png](https://zube.io/files/rancher/a3c5518e8ff48960203c5d6402009bad-screen-shot-2019-06-06-at-8-00-00-am.png)

![Screen Shot 2019-06-06 at 8.00.23 AM.png](https://zube.io/files/rancher/a92cfb36e6bb580e39f7c080f4c88b7a-screen-shot-2019-06-06-at-8-00-23-am.png)

Is this cluster configuration not sufficient for deploying Istio workloads ? If not, Why did our initial check to make sure that there is sufficient resources fail to detect this ?

**Comment by loganhz** [comment] 2019-06-06 16:03
In this case, Pilot memory reservation is set to `2048MB` and the worker nodes' memory `2048MB`.
It means even one pod with memory reservation deployed into one node. Then k8s is not able to schedule Pilot pod.

UI cannot understand why k8s doesn't schedule all the pods on `santestnew2` to `santestnew3` 
And leave `santestnew2` for Pilot pod only.

There is no way in UI to 100% ensure  all workloads can be deployed successfully.
Unless we migrate all of the k8s scheduler code into UI. 
But we need to invest a lot of time for it.

**Comment by sangeethah** [comment] 2019-06-06 16:07
@loganhz  I Added 1 more Worker node ( 2 CPU/4GB Mem) before I enabled the istio again.
Why is this worker node not being considered ?

**Comment by loganhz** [comment] 2019-06-06 16:14
That one doesn't have enough CPU. Only 0.5 left.

Ideally, Pods  on `santestnew2` should go to `santestw1`. And Polit can be deployed to `santestnew2`

This is what UI assume to happen. But k8s scheduler doesn't do that

**Comment by rayandas** [comment] 2022-12-22 13:31
Validated the issue on Rancher 2.6.9 the issue is not reproducible. hence closing this issue.

**Closed by rayandas** 2022-12-22 13:31 UTC
Labels: kind/bug-qa, area/istio, [zube]: Working, team/infracloud
