### ISSUE TITLE
instances using convoy in "starting" loop after docker restart on host 

### ISSUE THREAD

**Issue by dkiser** [rancher/rancher#3641] opened 2016-02-17 21:56 UTC
When restarting Docker service on a Rancher Host, containers on that host utilizing the `convoy-gluster` volume driver are stuck in a perpetual "starting" state with rancher-agent logs shown below.

1) crate glusterfs from catalog
2) create convoy-gluster from catalog
3) launch service with convoy-gluster backed volume
4) systemctl restart docker on Rancher host with said container
5) container in perpetual starting state with errors shows below in `rancher-agent`
6) delete and re-create of sevice on same host works (presumably because it was after `convoy-gluster` containers started)

Could there be some race condition in this case causing the start of the container to use an older referenced uuid for volume info?

**rancher-agent log entry after systemctl docker restart**

```
2016-02-17 21:32:48,342 ERROR agent [139948994872176] [event.py:112] Error in request : 26dc773b-1cb7-4375-a139-e64f4be427f8
Traceback (most recent call last):
  File "/var/lib/cattle/pyagent/cattle/agent/event.py", line 95, in _worker_main
    resp = agent.execute(req)
  File "/var/lib/cattle/pyagent/cattle/agent/__init__.py", line 15, in execute
    return self._router.route(req)
  File "/var/lib/cattle/pyagent/cattle/plugins/core/event_router.py", line 13, in route
    resp = handler.execute(req)
  File "/var/lib/cattle/pyagent/cattle/agent/handler.py", line 34, in execute
    return method(req=req, **req.data.__dict__)
  File "/var/lib/cattle/pyagent/cattle/plugins/docker/compute.py", line 481, in instance_activate
    self._do_instance_activate(instance, host, progress)
  File "/var/lib/cattle/pyagent/cattle/plugins/docker/compute.py", line 559, in _do_instance_activate
    client.start(container_id)
  File "/var/lib/cattle/pyagent/dist/docker/utils/decorators.py", line 21, in wrapped
    return f(self, resource_id, *args, **kwargs)
  File "/var/lib/cattle/pyagent/dist/docker/api/container.py", line 343, in start
    self._raise_for_status(res)
  File "/var/lib/cattle/pyagent/dist/docker/client.py", line 142, in _raise_for_status
    raise errors.APIError(e, response, explanation=explanation)
APIError: 500 Server Error: Internal Server Error ("Cannot start container a0fa8ff22cfcfd54c18777e60449d31f1f39ed05c268351e0160c433f8a9ce54: Unable to setup mount point, neither source nor volume defined")
```

**docker info**

```
Containers: 29
Images: 1919
Server Version: 1.9.1
Storage Driver: devicemapper
 Pool Name: docker-253:0-46007121-pool
 Pool Blocksize: 65.54 kB
 Base Device Size: 10.74 GB
 Backing Filesystem:
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 34.27 GB
 Data Space Total: 107.4 GB
 Data Space Available: 73.1 GB
 Metadata Space Used: 86.9 MB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.061 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.107-RHEL7 (2015-10-14)
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 3.10.0-327.3.1.el7.x86_64
Operating System: CentOS Linux 7 (Core)
CPUs: 24
Total Memory: 62.86 GiB
Name: **SCRUBBED
ID: **SCRUBBED**
WARNING: bridge-nf-call-iptables is disabled
WARNING: bridge-nf-call-ip6tables is disabled
```

**rancher info**

```
Component Version
Rancher v0.59.0
Cattle  v0.148.0
User Interface  v0.90.0
Rancher Compose v0.7.2
```

**Comment by clintbeacock** [comment] 2016-03-10 16:41
I see this has been released from the 1.0 Milestone.

Is there any workaround in the meantime, as this prevents applications from coming back online in the event of any docker restarts, such as on a server reboot.

**Comment by iangcarroll** [comment] 2016-04-13 12:36
It looks like #3670 is a duplicate of this one, but #3670 has a lot more discussion so this one should probably be closed.

**Comment by michaellopez** [comment] 2016-04-28 13:48
I'm getting this for NFS too. Same steps to reproduce, just replace gluster with nfs, basically. What's weird is that I have another service that uses NFS mounts too, and that starts up properly after a system reboot.

```sh
$ docker start b03fd52327fe
Error response from daemon: Cannot start container b03fd52327fe: Unable to setup mount point, neither source nor volume defined
Error: failed to start containers: [b03fd52327fe]

$ docker inspect b03fd52327fe
...
"Mounts": [
        {
            "Name": "test",
            "Source": "/var/lib/rancher/convoy/convoy-nfs-bd8e9f43-dfe2-4c1c-9161-b4a4541e7c1a/mnt/test",
            "Destination": "/data",
            "Driver": "convoy-nfs",
            "Mode": "",
            "RW": true
        },
        {
            "Name": "e27d2186593f82228765e52c82ee9b034525b5e32f2c03156b6893160ec2a517",
            "Source": "",
            "Destination": "/usr/local/etc/service",
            "Driver": "local",
            "Mode": "",
            "RW": true
        }
    ],
...
```
As you can see, `Source` for one of the volumes is empty...I think that this is the cause for this error.

I'm still investigating and doing a diff against my other service that works like it should...

**Comment by will-chan** [comment] 2017-02-01 21:33
Closing due to inactivity, please reopen if you think this is still relevant to current releases & important

**Closed by will-chan** 2017-02-01 21:33 UTC
Labels: kind/bug
