### ISSUE TITLE
Alerting for failing etcd backups

### ISSUE THREAD

**Issue by axeal** [rancher/rancher#23711] opened 2019-10-28 07:36 UTC
**What kind of request is this (question/bug/enhancement/feature request):**

Feature Request

**Steps to reproduce (least amount of steps as possible):**

The user would like to be able to configure alerts for failing etcd backups, e.g. when etcd backups fail to push to S3 etc.

**Comment by superseb** [comment] 2019-10-31 10:40
This seems to be a duplicate of https://github.com/rancher/rancher/issues/17299

**Closed** 2019-11-01 15:01 UTC
Labels: area/alerting, area/backup-recover, internal, kind/feature
