### ISSUE TITLE
After deleting certificate, can't reuse the name

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#2993] opened 2015-12-10 23:12 UTC
Version - Master 12/10

Steps:
1.  Create a Certificate and name it - cert1
2.  Delete the certificate
3.  Create another cert and name it - cert1

Results:
Validation failed in API: name is not unique

Expected:
After certificate is deleted and no longer visible on screen, I should be able to use the name again.

**Comment by alena1108** [comment] 2016-01-04 19:22
@ibuildthecloud this issue is caused by removed records being visible for api.show.removed.for.seconds time (5 seconds by default). So when we validate for duplicates, we validate against the records that a) non-removed b) have been removed for less than 5 seconds:

https://github.com/rancher/cattle/blob/9fc3843b03db5a903522edd1e91d54b33c332a6b/code/framework/api/src/main/java/io/cattle/platform/api/resource/AbstractObjectResourceManager.java#L300

Not sure if its by design, could you confirm.

**Comment by will-chan** [comment] 2016-03-09 18:39
Closing as not a common use case and waiting more than 5 seconds will allow you to recreate with same name.

**Closed by will-chan** 2016-03-09 18:39 UTC
Labels: area/api, kind/bug, release/v1.0.0, status/wontfix
