### ISSUE TITLE
Rancher returns 404 from agent when cluster is not built by RKE

### ISSUE THREAD

**Issue by brechsteiner** [rancher/rancher#15172] opened 2018-08-22 05:56 UTC
**Rancher versions:**
rancher/server or rancher/rancher: v2.0.7
rancher/agent or rancher/rancher-agent: v2.0.7

**Infrastructure Stack versions:**
kubernetes (if applicable): v1.11.2

**Docker version: (`docker version`,`docker info` preferred)**
rancher/rancher: 18.06.0-ce
kubernetes nodes: 17.03.2-ce

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
Debian GNU/Linux 9.5 (stretch) / 4.9.110-3+deb9u3

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
KVM

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
single node rancher with nginx reverse proxy

**Steps to Reproduce:**
Setup: 
```
|kubernetes nodes (imported cluster)| --> |nginx reverse proxy| --> |single node rancher (in a docker)|
```
nginx-conf-snippet:
```
location ~ .* {
                proxy_http_version 1.1;
                proxy_set_header Upgrade $http_upgrade;
                proxy_set_header Connection "Upgrade";
                proxy_read_timeout 900s;
                proxy_buffering off;
                proxy_pass https://rancher;
                proxy_redirect default;
        }
```
**Results:**
I periodically see from every kubernetes node (imported cluster) http 404 on my nginx reverse proxy.
`"GET /v3/connect/config HTTP/2.0" "TLSv1.2/ECDHE-RSA-AES256-GCM-SHA384 " 404 0 "-" "Go-http-client/2.0" "-"`

gzrancher/rancher#10522

**Comment by superseb** [comment] 2018-08-22 07:19
What NGINX version are you running, what is the complete config? What cluster are you importing? What is the agent logging when the NGINX logging happens?

**Comment by brechsteiner** [comment] 2018-08-22 12:19
nginx version: nginx/1.12.2
```
server {
        listen  443 ssl http2 ;
        listen  [::]:443 ssl http2 ;
        
        server_name rancher.example.com ;
        ssl_certificate /etc/dehydrated/certs/rancher.example.com/fullchain.pem;
        ssl_certificate_key /etc/dehydrated/certs/rancher.example.com/privkey.pem;
        
        ssl_stapling on;
        ssl_stapling_verify on; 
        ssl_trusted_certificate /etc/dehydrated/certs/rancher.example.com/fullchain.pem;

        add_header Strict-Transport-Security "max-age=31536000; includeSubDomains; preload" always;
        add_header X-Frame-Options DENY always;
        add_header X-Content-Type-Options "nosniff" always;
        
        access_log /var/log/nginx/rancher-ssl-access.log main;
        error_log /var/log/nginx/rancher-ssl-error.log;

        location ~ .* {
                proxy_http_version 1.1;
                proxy_set_header Upgrade $http_upgrade;
                proxy_set_header Connection "Upgrade";
                proxy_read_timeout 900s;
                proxy_buffering off;
                proxy_pass https://rancher;
                proxy_redirect default;
        }
}
```
imported cluster: bare-metal, debian 9.5, docker 17.03.2-ce, kubernetes v1.11.2
agent-logs:
```
time="2018-08-22T06:18:40Z" level=info msg="Connecting to wss://rancher.example.com/v3/connect with token 2xl8vfnmtszwnfsft4jvzmxg499m7qf67tjpd9grsfhwnllbbr225i"
time="2018-08-22T06:18:40Z" level=info msg="Connecting to proxy" url="wss://rancher.example.com/v3/connect"
time="2018-08-22T06:18:40Z" level=error msg="Failed to connect to proxy" error="websocket: bad handshake"
time="2018-08-22T06:18:40Z" level=error msg="Failed to connect to proxy" error="websocket: bad handshake"
time="2018-08-22T06:18:50Z" level=info msg="Connecting to wss://rancher.example.com/v3/connect with token 2xl8vfnmtszwnfsft4jvzmxg499m7qf67tjpd9grsfhwnllbbr225i"
time="2018-08-22T06:18:50Z" level=info msg="Connecting to proxy" url="wss://rancher.example.com/v3/connect"
time="2018-08-22T06:18:50Z" level=error msg="Failed to connect to proxy" error="websocket: bad handshake"
time="2018-08-22T06:18:50Z" level=error msg="Failed to connect to proxy" error="websocket: bad handshake"
time="2018-08-22T06:19:00Z" level=info msg="Connecting to wss://rancher.example.com/v3/connect with token 2xl8vfnmtszwnfsft4jvzmxg499m7qf67tjpd9grsfhwnllbbr225i"
time="2018-08-22T06:19:00Z" level=info msg="Connecting to proxy" url="wss://rancher.example.com/v3/connect"
time="2018-08-22T06:19:01Z" level=info msg="Starting plan monitor"
```

**Comment by superseb** [comment] 2018-08-22 13:11
OK makes sense. The imported cluster will have node agent, and the config that it's trying to retrieve is only applicable to RKE built clusters. If it's not an RKE built cluster, it will return 404. I believe that is what you are seeing. Is there any functional impact?

**Comment by brechsteiner** [comment] 2018-08-22 15:22
It has no functional impact for me, it only triggers a lot of alerts in my log monitoring. It would be nice when the agent would no longer call this URL on a non-RKE cluster.

**Comment by john-bakker** [comment] 2019-01-15 13:32
Sebastiaan, is there an update on this already?

**Comment by vedant-khandelwal** [comment] 2019-07-29 12:50
Looks like this hasn't been fixed in Rancher v2.2.4?

**Comment by dawidmalina** [comment] 2020-01-29 18:00
Any updates on this topic? We are having the same issue. Is it possible to workarround this somehow?

**Comment by dnoland1** [comment] 2020-06-05 20:20
Seeing this in latest version - v2.4.4 running on top of k3s cluster. Sample ingress log:
```
10.100.100.219 - - [05/Jun/2020:17:27:19 +0000] "GET /v3/connect/config HTTP/1.1" 404 0 "-" "Go-http-client/2.0" 646 0.000 [cattle-system-rancher-80] [] 172.16.1.160:80 0 0.000 404 0492195fbb3039b6e4db8472150a49b3
```

**Comment by superseb** [comment] 2020-07-06 10:51
The 404 is a way to easily identify custom clusters (that need a nodeconfig) from non custom clusters (that don't need it). Easiest way to fix this is to change the 404 Not Found response to 204 No Content, that way to keep the identification on the server and client side based on the response code. According to RFC7231, this is valid. The other option would be either a 200 OK and empty body, which then needs to be checked (but according to RFC, requests with empty body should be 204), or do 200 OK and add data in the body to indicate nothing has to be done, which then is checked by the client. So I think changing it to 204 No Content should be OK.

**Comment by deniseschannon** [comment] 2021-01-05 22:41
This seems to be fixed based on this commit by Darren and was fixed as of 2.5.0:

https://github.com/rancher/rancher/commit/079c473dea8d6b47043d1a4ace158c86b03b1bee

**Comment by bmdepesa** [comment] 2021-01-28 23:27
Reproduced in `rancher/rancher:v2.4.4`

* Single node docker install behind nginx reverse proxy
* Create a GKE cluster in Google cloud and import into Rancher
* All 3 nodes periodically make a request which returns 404, logs are over the course of 5 minutes
```
node1 - - [28/Jan/2021:23:16:03 +0000] "GET /v3/connect/config HTTP/2.0" 404 0 "-" "Go-http-client/2.0"
node2 - - [28/Jan/2021:23:16:10 +0000] "GET /v3/connect/config HTTP/2.0" 404 0 "-" "Go-http-client/2.0"
node1 - - [28/Jan/2021:23:16:13 +0000] "GET /v3/connect/config HTTP/2.0" 404 0 "-" "Go-http-client/2.0"
node3 - - [28/Jan/2021:23:16:13 +0000] "GET /v3/connect/config HTTP/2.0" 404 0 "-" "Go-http-client/2.0"
node2 - - [28/Jan/2021:23:16:22 +0000] "GET /v3/connect/config HTTP/2.0" 404 0 "-" "Go-http-client/2.0"
node3 - - [28/Jan/2021:23:16:33 +0000] "GET /v3/connect/config HTTP/2.0" 404 0 "-" "Go-http-client/2.0"
node1 - - [28/Jan/2021:23:16:42 +0000] "GET /v3/connect/config HTTP/2.0" 404 0 "-" "Go-http-client/2.0"
node2 - - [28/Jan/2021:23:18:22 +0000] "GET /v3/connect/config HTTP/2.0" 404 0 "-" "Go-http-client/2.0"
node3 - - [28/Jan/2021:23:18:33 +0000] "GET /v3/connect/config HTTP/2.0" 404 0 "-" "Go-http-client/2.0"
node1 - - [28/Jan/2021:23:18:42 +0000] "GET /v3/connect/config HTTP/2.0" 404 0 "-" "Go-http-client/2.0"
node2 - - [28/Jan/2021:23:20:23 +0000] "GET /v3/connect/config HTTP/2.0" 404 0 "-" "Go-http-client/2.0"
node3 - - [28/Jan/2021:23:20:33 +0000] "GET /v3/connect/config HTTP/2.0" 404 0 "-" "Go-http-client/2.0"
```

* Tested with `rancher/rancher:v2.5.5`
* Single node docker install behind nginx reverse proxy
* Create a GKE cluster in Google cloud and import into Rancher
* 404 is only seen twice, immediately after registering, from a single node of the 3-node cluster, over a period of 2 hours
```
node1 - - [28/Jan/2021:22:44:39 +0000] "GET /v3/connect/config HTTP/2.0" 404 0 "-" "Go-http-client/2.0"
node1 - - [28/Jan/2021:22:44:48 +0000] "GET /v3/connect/config HTTP/2.0" 404 0 "-" "Go-http-client/2.0"
```

@superseb would we expect these 404's to completely disappear, or are these expected in some other case?

**Closed** 2021-02-08 17:36 UTC
Labels: [zube]: QA Working, area/rke, internal, kind/bug

**Comment by bmdepesa** [comment] 2021-02-08 17:53
The repeating requests are no longer occurring. We do see 2 requests initially on the cluster registration, opened another issue: https://github.com/rancher/rancher/issues/31186 to track this.
