### ISSUE TITLE
Slow upgrade / any action and high CPU utilization

### ISSUE THREAD

**Issue by tholcman** [rancher/rancher#7751] opened 2017-02-09 06:35 UTC
**Rancher Versions:**
Server: 1.3.4
*Cattle: 0.175.10*
healthcheck: 0.2.0
ipsec: 0.0.2
network-services: 0.0.8
scheduler: 0.3.0
kubernetes (if applicable):

**Docker Version:** 1.13.0

**OS and where are the hosts located? (cloud, bare metal, etc):** ~50 hosts Ubuntu16, Bare Metal ~250 containers in 5 services.

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)** External DB r3.large, 2 Rancher hosts c4.xlarge (4 cores)

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)** Cattle v0.175.10

**Steps to Reproduce:**
Run rolling upgrade/finish/rollback on any service or perform almost ANY action on containers

**Results:** 
It takes hours to rotate ~50 containers
both Rancher "masters" have CPU Utilization 100%
When running basic java prfiler:
`./jvmtop.sh 9 --profile -n 50`
we got:
```
 JvmTop 0.8.0 alpha - 06:15:02,  amd64,  4 cpus, Linux 4.4.0-59-, load avg 12.90
 http://code.google.com/p/jvmtop
 Profiling PID 9:         io.cattle.platform.launcher.Main 
  23.02% (     2.13s) org.yaml.snakeyaml.resolver.Resolver.resolve()
  15.21% (     1.63s) org.yaml.snakeyaml.emitter.Emitter.writePlain()
  14.23% (     1.52s) ....yaml.snakeyaml.representer.SafeRepresenter$Represent()
   5.87% (     0.63s) ....yaml.snakeyaml.representer.Representer.representJava()
   5.78% (     0.62s) org.mariadb.jdbc.internal.util.buffer.ReadUtil.readFully()
   4.10% (     0.44s) org.yaml.snakeyaml.emitter.Emitter.writeIndent()
   3.97% (     0.43s) org.yaml.snakeyaml.emitter.Emitter.writeIndicator()
   3.41% (     0.37s) org.yaml.snakeyaml.emitter.Emitter.analyzeScalar()
...
```

It spends more 70% of CPU time encoding and decoding YAMLs!!!!!!

**Comment by Toonix** [comment] 2017-02-10 13:11
My CPU is also to high

```
Mem: 1963288K used, 68780K free, 315940K shrd, 77808K buff, 426008K cached
CPU:  77% usr  15% sys   0% nic   1% idle   1% io   0% irq   4% sirq
Load average: 8.09 8.63 8.83 4/465 6012
  PID  PPID USER     STAT   VSZ %VSZ %CPU COMMAND
116308116307 root     S    3663m 184%  69% java -XX:+UseConcMarkSweepGC -XX:+CMSClassUnloadingEnabled -Xms128m -Xmx1g -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=/var/lib/cattle/logs -Dlogback.bootstrap.leve
116324116306 102      S    1348m  68%  25% /usr/sbin/mysqld --basedir=/usr --datadir=/var/lib/mysql --plugin-dir=/usr/lib/mysql/plugin --user=mysql --log-error=/var/log/mysql/error.log --pid-file=/var/run/mysqld/
116462116308 root     S     332m  17%   3% websocket-proxy

```

and i still have the problem that rancher crashes total...

**Comment by chauffer** [comment] 2017-02-12 12:53
Any idea regarding this issue, please?

**Comment by aemneina** [comment] 2017-02-12 17:36
@tholcman was this an upgraded setup? What do you see under the admin -> processes tab?

**Comment by chauffer** [comment] 2017-02-12 17:47
@aemneina:

@tholcman is my co-worker, rancher is not upgraded, all there is in Admin -> processes is timed out `volumestoragepoolmap.remove` processes; clicking on them to view on API returns a 404:

```
{
"id": "c60f8c1f-06fc-4ddd-9ec2-fc73435c51e0",
"type": "error",
"links": { },
"actions": { },
"status": 404,
"code": "Not Found",
"message": "Not Found",
"detail": null,
"baseType": "error"
}
```

**Comment by tholcman** [comment] 2017-02-13 01:34
When there is no running service upgrade / scaling / whatever there are just about 25 of these processes and processors are quiet (2-2,5 CPU utilization).
```
...
1pi210943	volumestoragepoolmap.remove	volumeStoragePoolMap:1vspm7306	TIMEOUT	3 days ago		267257 sec
...
```

But if you run upgrade / start new services / scale +-10 there is `service.upgrade` and some `instance.stop` `instance.create`- I think pretty normal behavior.

But during upgrade the CPU utilization jumps to almost 100% even if we have really powerful configuration (2 instances, each with 16 CPU cores)!!! With smaller instances there were some Timeouts of `instance.stop` and `instance.start` After a while `message (Need to restart service reconcile)` appears next to the service and upgrade stops for a while and whole Rancher acts weird. But I think this is just consequence not a cause.

As I have written in my first comment almost whole CPU is consumed by YAML encoding and decoding!!! When rancher needs to decode and encode YAMLs?

**Comment by Toonix** [comment] 2017-02-13 07:30
I habe 10 Stacks running, when I stop 3 Stack my CPU drops to normal values. 

My Audit Logs produced over the weekend 3863820 entries...pretty hight isn't it?

**Comment by Toonix** [comment] 2017-02-13 12:38
I had to optimize the mysql DB, it's now better but the question is still the same..why does Rancher write so many Audit Logs? 

I can now run about 20 Containers before the mysql process and java process goes really up again.

**Comment by tholcman** [comment] 2017-02-14 04:42
@aemneina  Any progress?

I think this is not `kind/question` but serious bug which prevents using Rancher 1.2+ in larger deployments! Probably it is causing other bugs (Those with `Timeout getting IP` which breaks rolling upgrade until you restart `metadata.network-services`).

As I said CPU is eaten by encoding/decoding YAMLs, it is probably caused by requests like
```
$IP - E36520F4F2CE263C051F [14/Feb/2017:04:13:25 +0000] "GET /v1/configcontent/metadata-answers HTTP/1.1" 200 313636 "-" "Go-http-client/1.1"
$IP - ADB832433F71475DDFC4 [14/Feb/2017:04:13:25 +0000] "GET /v1/configcontent/metadata-answers HTTP/1.1" 200 314714 "-" "Go-http-client/1.1"
$IP - D75BBF22200CB87A0768 [14/Feb/2017:04:13:25 +0000] "PUT /v1/configcontent/metadata-answers?version=27126-8b84aebc80dd7a28cb0d0e082d379dd7 HTTP/1.1" 200 0 "-" "Go-http-client/1.1"
```

Can I help you to identify problem somehow? Are the Rancher/Cattle going to get rid of those `/v1/` calls and if so when?

**Comment by aemneina** [comment] 2017-02-14 22:27
I believe those calls to metadata are expected in an environment that has a lot of updates/churn. Do you only experience that when making changes to services? Are your services in a healthy state?

**Comment by aemneina** [comment] 2017-02-14 22:28
Are all those hosts/containers within the same environment, or are they segmented across a few environments?

**Comment by tholcman** [comment] 2017-02-15 02:41
Currently we have ~100 hosts, in 3 environments. When there is no upgrade or any change running, the CPUs of Rancher are quiet.

In `Environment1` we have 50 hosts, 5 services each with 50 containers. When I run upgrade on one service (50 containers) one-by-one it takes 30 minutes. And it utilize 32 CPU cores of Rancher almost to 100%. 

If Rancher is on weaker instances then upgrade stuck trying to start one container  again and again. The messege `Need to restart service reconcile` appear on service and Error `Timeout getting IP address` on container. And it stays in this state until restart of metadata.network-services on host where container gets `Timeout getting IP address`.

When there is some disaster, no disaster, just some stumble it might kill metadata on almost all hosts then Rancher is useless, unable to do ANYTHING!!! Even with 32 CPU cores. And I am not talking about slowness. On Rancher 1.1 same upgrade took 4-5 minutes on 8 CPU cores!

I can understand need of metadata service to know about changes in environment. But the bad thing is that encoding and decoding of YAMLs it cannot take so much CPU!!!

**Comment by qamalbcgdv** [comment] 2017-02-23 08:50
I am running 1.4.1 with similar setup, roughly 100 nodes and 5 environments. I am also getting these 100% CPU and slowness, all in all it has around 1700 containers in all 5 environments.

**Comment by underyx** [comment] 2017-02-23 15:35
@aemneina could we maybe have this issue reclassified from 'question' to 'bug'? Definitely seems like a software defect to me, and a pretty severe one, too.

**Comment by aemneina** [comment] 2017-02-23 16:20
@underyx done. Looks like some improvements could happen here.

**Comment by underyx** [comment] 2017-02-23 16:40
@aemneina how would you feel about us adding 50 instances to a try.rancher.com environment to let you experience the problem firsthand? Let me know if that would be helpful for you.

**Comment by ibuildthecloud** [comment] 2017-02-23 19:07
@underyx The purpose of try is really for us to experience these pains first hand.  But don't worry I already am aware of these issues and most will be address in 1.5 with more improvements coming in 1.6.  1.5 will be released in a week.

My current use case I'm testing is 1 environment with 50 hosts and 10000 services of scale 1.

**Comment by ibuildthecloud** [comment] 2017-02-23 19:11
@underyx if you want to give me a reproducable test case I can run to ensure it works fine that would be great.

**Comment by veered** [comment] 2017-07-05 20:18
Has this been addressed in newer versions of Rancher?

**Comment by Toonix** [comment] 2017-07-05 20:36
in my case it was a problem with the external dns rfc2136. 

I could fix it with this here: https://github.com/rancher/external-dns/pull/54

**Comment by veered** [comment] 2017-07-05 21:32
@Toonix Does that PR affect the performance of the metadata service? Or were you experiencing high CPU usage for different reasons?

**Comment by Toonix** [comment] 2017-07-05 21:49
High CPU around 80%, it also filled my database like crazy. I had dns update continuesly witch got all logged in audit too. Instead of one update all 60 seconds or so..the service looped and got worse when I had more then 10 Stacks with public ports...the mysql Database where after some day over 5GB big.

**Comment by veered** [comment] 2017-07-05 22:05
Good to know! I think this is a different issue than the one that @tholcman and I are having though

**Comment by veered** [comment] 2017-07-06 17:21
I wonder if replacing the existing YAML parser Rancher uses SnakeYAML w/ a faster parser would help. Given @tholcman's comment ("It spends more 70% of CPU time encoding and decoding YAMLs!!!!!!"), this seems quite possible.

This parser claims to be faster: https://github.com/reprezen/kaizen-openapi-parser

**Comment by jlukic** [comment] 2017-07-11 19:36
@ibuildthecloud can you confirm that this should be improved in the released `1.6`?

**Comment by aemneina** [comment] 2017-07-11 21:02
Just a note here, upgrading the network-services stack and setting cpu share (on metadata service) to <= 300 will mitigate large CPU spikes. Test this out if you plan on rolling this out to your production system. This as a temporary workaround might be appealing. Note this will slow deployment as metadata wont have unlimited CPU cycles to consume or process its changes.

**Comment by veered** [comment] 2017-07-11 21:11
@aemneina That's a really good idea! We'll try it out and let you know how it goes

**Comment by furkanmustafa** [comment] 2017-07-19 01:34
I believe that the log above is consisting a couple issues, not a single one.

I am also experiencing a meaningless long delay on container start stage. And my setup is rather small, really small. 8 hosts, 4 stacks. Upgrading only a single container service, which is waiting at the stage "Starting".

I fell like this has begun after we started using `rancher-nfs`, but this particular service does not have a volume.

Also just in case it helps; Delayed Processes list is filled with `volumestoragepoolmap.remove` and has around total ~150 processes delayed. But there were never that much volume operations done on this environment.

I hope this input helps figuring out at least one of the issues here.

**Comment by vkruoso** [comment] 2017-11-06 16:24
Any news on that? Running v1.5.10 with just one host and one environment, 5 stacks with <60 services and containers. That issue really causes problems at the production machines when it happens.

**Comment by superseb** [comment] 2018-08-28 10:43
Closing as stale, if you encounter issues with performance, please file a new issue with details so we can investigate.

**Closed by superseb** 2018-08-28 10:43 UTC
Labels: kind/bug
