### ISSUE TITLE
Hyperlink in /apps points to http:// on SSL enabled load balancers

### ISSUE THREAD

**Issue by larkly** [rancher/rancher#3342] opened 2016-01-20 12:52 UTC
Rancher 0.51.0

When creating a non-SSL load balancer, the defined port is hyperlinked in the UI /apps, to allow easy access to the service. When creating an SSL load balancer, it does the same, but still applies http://, which wouldn't work on an SSL-only service.

**Comment by deniseschannon** [comment] 2016-01-23 04:23
Duplicate of https://github.com/rancher/rancher/issues/3182

This will be fixed in the next release.

**Closed by deniseschannon** 2016-01-23 04:23 UTC
