### ISSUE TITLE
CA check fails if CA PEM ends with LF

### ISSUE THREAD

**Issue by m451** [rancher/rancher#13831] opened 2018-06-03 14:22 UTC
This is a re-open of issue #13615 . The author closed the issue because he found a workaround. Still I believe this should be considered a bug and fixed.

**Rancher versions:**
rancher/server or rancher/rancher: 2.0.0
rancher/agent or rancher/rancher-agent: 2.0.0

**Infrastructure Stack versions:**
healthcheck: default
ipsec: default
network-services: default
scheduler: default
kubernetes (if applicable): default

**Docker version: (`docker version`,`docker info` preferred)**
Client:
 Version:      18.05.0-ce-rc1
 API version:  1.37
 Go version:   go1.9.5
 Git commit:   33f00ce
 Built:        Thu Apr 26 01:03:26 2018
 OS/Arch:      linux/amd64
 Experimental: false
 Orchestrator: swarm

Server:
 Engine:
  Version:      18.05.0-ce-rc1
  API version:  1.37 (minimum version 1.12)
  Go version:   go1.9.5
  Git commit:   33f00ce
  Built:        Thu Apr 26 01:01:34 2018
  OS/Arch:      linux/amd64
  Experimental: false

Containers: 1
 Running: 1
 Paused: 0
 Stopped: 0
Images: 2
Server Version: 18.05.0-ce-rc1
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 773c489c9c1b21a6d78b5c538cd395416ec50f88
runc version: 4fc53a81fb7c994640722ac585fa9ca548971871
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.15.0-22-generic
Operating System: Ubuntu 18.04 LTS
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 11.73GiB
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
NAME="Ubuntu"
VERSION="18.04 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
vSphere VM

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
single node rancher, internal DB

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**
Kubernetes

**Steps to Reproduce:**
1. Choose option 2.B from https://rancher.com/docs/rancher/v2.x/en/installation/single-node-install/ when installing rancher. This is: have rancher use a custom, self-signed certificate from a self-signed, private CA.
2. Create the required certificates as documented in the documentation mentioned above. This is: PEM encoded base64 certificates with intermediate (if any) certificates included in the certificate file.
3. By default most SSL tools will append a tailing [LF](https://en.wikipedia.org/wiki/Newline) character at the end of the cacert.pem, cert.pem and key.pem files. This should be considered "normal behaviour".
4. Start rancher providing those certificates e.g.:

```
sudo docker run -d --restart=unless-stopped \
-p 80:80 -p 443:443 --name rancher \
-v /path/to/cert.pem:/etc/rancher/ssl/cert.pem \
-v /path/to/rancher/key.pem:/etc/rancher/ssl/key.pem \
-v /path/to/rancher/cacerts.pem:/etc/rancher/ssl/cacerts.pem \
rancher/rancher:latest
```
5. Login to rancher server web-portal and create a cluster (this was tested with the vSphere driver but should be repreduceable with any driver).

**Results:**
The cluster creation will fail. Checking the logs of the rancher-agents (controller and/or worker nodes) will show that they are unable to start because the ca-certificate checksum provided by the rancher server at https://rancherserver/v3/settings/cacerts doesn't match the checksum the rancher-agent calculated. This seems to happen because the tailing LF is incorrectly included in the checksum calculation of the rancher-agent (that uses the cacert.pem) but that tailing LF is (correctly) removed in the JSON data provided by  https://rancherserver/v3/settings/cacerts and thus the both calculated checksums do not match.

I guess the problem occures because of how the agent CA check is beeing performed currently [(simply copy the CA file and create a checksum on it)](https://github.com/rancher/agent/blob/f6754c45534a07bb3d18f0a30e7b42a75df4640f/package/run.sh#L76)

The tailing LF (or really any tailing control-characters) should NOT be included when caluclating the  certificate checksums.

**Comment by jomeier** [comment] 2018-06-07 20:49
Yes. That's a bug. Very hard to find. 

truncate -s -2 <cacertsfile> removes the last two bytes. Worked for me.

**Comment by cjellick** [comment] 2018-08-31 23:46
TODO:
revert the revert
properly trim on input


testing:
cert with no new lines at end
cert with one new line at end
cert with more than one new line at end
same with the above but at the beginning
all the above scenarios with single-node rancher container and deployed in HA mode in K8S
all those scenarios on upgrade as well

PS
Make sure that our helm template for HA deploys is getting certs into rancher by simply binding mounting the file(s) into the container. If it is doing anything special or different by creating cert resources directly in k8s, call it out bc it may need to change

**Comment by cjellick** [comment] 2018-09-18 18:08
Ping @superseb. Can you test this out to see if it addresses your concerns? If it works, comment back on this issue.

**Comment by cjellick** [comment] 2018-09-18 18:12
@maxkorp To validate.
Max, don't close this issue until @superseb approves as well.
Also, with this one, it is especially important to document how you reproduced and the scenarios you tested.
It is also very important with this bug to verify that we DO NOT break installations that are upgrading and have a previously working self-signed cert.

**Comment by maxkorp** [comment] 2018-09-19 20:52
Verified that this is working as of v2.1.0-rc2, but with questions below

### Short form process
To test, I created 6 single node rancher instances 
For each version (2.0.8 and 2.1.0-rc2), I created 1 with a cert with no trailing newline, 1 with 1 trailing newline, and 1 with 2 trailing newlines. 

### Short form results
Here are the results for spinning up a cluster on Digital Ocean

|                     | v2.0.8      | v2.1.0-rc2 |
|---------------------|-------------|------------|
| No trailing newline | Works       | Works      |
| 1 trailing newline  | Works       | Works      |
| 2 trailing newlines | ***Fails*** | Works      |

I tried with more than 2 newlines, and those also failed. 
Was a single trailing newline expected to fail?

Upon upgrading the v2.0.8 instances to v2.1.0-rc2, I created checked the existing clusters and also created new clusters

|                     | Existing Cluster | Creating New Cluster |
|---------------------|------------------|----------------------|
| No trailing newline | Works            | Works                |
| 1 trailing newline  | Works            | Works                |
| 2 trailing newlines | Fails*           | Works                |

The existing working clusters continued to work, and the existing failed clusters remained failed. Talking in person with @nathan-jenan-rancher and @cjellick (before the fix was merged) we determined that this was acceptable, as the odds of people keeping failed clusters around was slim, and since they would have never worked, new ones could simply be provisioned without any loss of data.

### Long form process part 1

For each instance, I spun up a node, and then created certs in `/root` of the node
```sh
{

cat > ca-config.json <<EOF
{
  "signing": {
    "default": {
      "expiry": "8760h"
    },
    "profiles": {
      "kubernetes": {
        "usages": ["signing", "key encipherment", "server auth", "client auth"],
        "expiry": "8760h"
      }
    }
  }
}
EOF

cat > ca-csr.json <<EOF
{
  "CN": "Kubernetes",
  "key": {
    "algo": "rsa",
    "size": 2048
  },
  "names": [
    {
      "C": "US",
      "L": "Portland",
      "O": "Kubernetes",
      "OU": "CA",
      "ST": "Oregon"
    }
  ]
}
EOF

cfssl gencert -initca ca-csr.json | cfssljson -bare ca

}


{

cat > admin-csr.json <<EOF
{
  "CN": "admin",
  "key": {
    "algo": "rsa",
    "size": 2048
  },
  "hosts": [
      "104.248.186.79",
      "104.248.186.80",
      "104.248.186.81",
      "104.248.176.203",
      "104.248.186.76",
      "104.248.186.78"
  ],
  "names": [
    {
      "C": "US",
      "L": "Portland",
      "O": "system:masters",
      "OU": "Kubernetes The Hard Way",
      "ST": "Oregon"
    }
  ]
}
EOF

cfssl gencert \
  -ca=ca.pem \
  -ca-key=ca-key.pem \
  -config=ca-config.json \
  -profile=kubernetes \
  admin-csr.json | cfssljson -bare admin

}

mv ca.pem cacerts.pem
mv admin.pem cert.pem
mv admin-key.pem key.pem

rm *.json
rm *.csr
rm ca-key.pem
```

I then edited `cacerts.pem` using `nano -L` (prevents nano autoinserting newlines), to edit to the appropriate number of trailing newlines, and checked linecount with `wc -l cacerts.pem` to make sure that the 0 trailing had 1 less line (and the 2 had 1 more line) than the single trailing newline version.

I spun up rancher as following (using v2.1.0-rc2 instead of v2.0.8 where appropriate)
```sh
docker run -d --restart=unless-stopped \
    -p 80:80 -p 443:443 \
    -v /root/cert.pem:/etc/rancher/ssl/cert.pem \
    -v /root/key.pem:/etc/rancher/ssl/key.pem \
    -v /root/cacerts.pem:/etc/rancher/ssl/cacerts.pem \
    -e CATTLE_AGENT_IMAGE=rancher/rancher-agent:master \
    rancher/rancher:v2.0.8
```
In each instance, I spun up a single node cluster on digital ocean. 

### Long form results part 1

|                     | v2.0.8      | v2.1.0-rc2 |
|---------------------|-------------|------------|
| No trailing newline | Works       | Works      |
| 1 trailing newline  | Works       | Works      |
| 2 trailing newlines | ***Fails*** | Works      |

All of the 2.1.0-rc2 clusters spun up successfully, and on 2.0.8, no trailing newline and a single newline worked, but any more than 1 caused failures with the following error

```log
[controlPlane] Failed to bring up Control Plane: Failed to verify healthcheck: Failed to check https://localhost:6443/healthz for service [kube-apiserver] on host [redacted: cluster-node-ip]: Get https://localhost:6443/healthz: can not build dialer to [redacted], log: I0919 20:34:00.673710 1 logs.go:49] http: TLS handshake error from [redacted: rancher-node-ip]: EOF
```

### Long form process part 2

I then upgraded all 3 2.0.8 instances to 2.1.0-rc2

```sh
oldname=`docker ps -q`
docker stop $oldname 
docker create --volumes-from $oldname --name rancher-data rancher/rancher:v2.0.8
docker run -d --volumes-from rancher-data \
    --restart=unless-stopped \
    -p 80:80 -p 443:443 \
    -v /root/cert.pem:/etc/rancher/ssl/cert.pem \
    -v /root/key.pem:/etc/rancher/ssl/key.pem \
    -v /root/cacerts.pem:/etc/rancher/ssl/cacerts.pem \
    -e CATTLE_AGENT_IMAGE=rancher/rancher-agent:master \
    rancher/rancher:v2.1.0-rc2
```

For each, I gave time for the existing clusters come back up, and in the meanwhile I created a new cluster in DO as before.

### Long form results part 2

|                     | Existing Cluster | Creating New Cluster |
|---------------------|------------------|----------------------|
| No trailing newline | Works            | Works                |
| 1 trailing newline  | Works            | Works                |
| 2 trailing newlines | Fails*           | Works                |

As expected, new clusters for each can be created without issue. Both working clusters continued to work, and the failed cluster remained failed. As discussed above, that was determined to be appropriate.

### Questions
- Was 2.0.8 expected to fail with a single trailing newline?
- Is there any testing missing in regards to different versions of `CATTLE_AGENT_IMAGE`?
- Is any testing necessary in regards to leading whitespace? We trim that now as well, but that seems like an uncommon issue, since no tools that I could find generate anything with any leading whitespace

**Comment by maxkorp** [comment] 2018-09-19 22:02
@superseb Can you take a look at this when you get a chance?

**Comment by superseb** [comment] 2018-10-02 20:55
Tested this with current `master` (10/2), all my testcases worked. Created certs with multiple newlines at the end, and additional test with carriage return character. Generated checksum was OK in all cases.

Yes failed clusters never worked so it's fine to assume they are not in business. As long as upgrades on existing clusters work, and it seems so, seeing your tests.

**Comment by cjellick** [comment] 2018-10-02 21:45
Thanks @superseb! Closing the isue

**Closed by cjellick** 2018-10-02 21:45 UTC
Labels: kind/bug, priority/0, status/resolved, status/to-test, status/to-validate, team/az, version/2.0
