### ISSUE TITLE
Pods are stuck with message Waiting to Find IP

### ISSUE THREAD

**Issue by galal-hussein** [rancher/rancher#4419] opened 2016-04-15 00:14 UTC
I am running into a problem in Kubernetes where sometimes the pods are stuck in terminating or creating status whille the kubelet docker continuously giving the following error:
```
E0415 00:05:14.797122   30297 manager.go:1858] Failed to create pod infra container: RunContainerError; Skipping pod "nginx_default(ffafa7e4-029c-11e6-9a27-0286285ab4f0)"
E0415 00:05:14.797296   30297 pod_workers.go:138] Error syncing pod ffafa7e4-029c-11e6-9a27-0286285ab4f0, skipping: failed to "StartContainer" for "POD" with RunContainerError: "InspectContainer: Failed to find IP for d120f3d41e6baa3d84f569fcc32abd0794426a704a179c3a2a7ff630dd4f3f77"
E0415 00:05:14.986563   30297 generic.go:229] PLEG: Ignoring events for pod nginx/default: Failed to find IP for d120f3d41e6baa3d84f569fcc32abd0794426a704a179c3a2a7ff630dd4f3f77
I0415 00:05:15.006770   30297 rancher_docker.go:78] Waiting to find IP for d120f3d41e6baa3d84f569fcc32abd0794426a704a179c3a2a7ff630dd4f3f77
I0415 00:05:15.522705   30297 rancher_docker.go:78] Waiting to find IP for d120f3d41e6baa3d84f569fcc32abd0794426a704a179c3a2a7ff630dd4f3f77
I0415 00:05:16.009332   30297 rancher_docker.go:78] Waiting to find IP for d120f3d41e6baa3d84f569fcc32abd0794426a704a179c3a2a7ff630dd4f3f77
I0415 00:05:16.037606   30297 rancher_docker.go:78] Waiting to find IP for d120f3d41e6baa3d84f569fcc32abd0794426a704a179c3a2a7ff630dd4f3f77
I0415 00:05:16.539579   30297 rancher_docker.go:78] Waiting to find IP for d120f3d41e6baa3d84f569fcc32abd0794426a704a179c3a2a7ff630dd4f3f77
I0415 00:05:16.551580   30297 rancher_docker.go:78] Waiting to find IP for d120f3d41e6baa3d84f569fcc32abd0794426a704a179c3a2a7ff630dd4f3f77
I0415 00:05:17.053683   30297 rancher_docker.go:78] Waiting to find IP for d120f3d41e6baa3d84f569fcc32abd0794426a704a179c3a2a7ff630dd4f3f77
I0415 00:05:17.068038   30297 rancher_docker.go:78] Waiting to find IP for d120f3d41e6baa3d84f569fcc32abd0794426a704a179c3a2a7ff630dd4f3f77
I0415 00:05:17.568082   30297 rancher_docker.go:78] Waiting to find IP for d120f3d41e6baa3d84f569fcc32abd0794426a704a179c3a2a7ff630dd4f3f77
I0415 00:05:17.584320   30297 rancher_docker.go:78] Waiting to find IP for d120f3d41e6baa3d84f569fcc32abd0794426a704a179c3a2a7ff630dd4f3f77
I0415 00:05:18.080864   30297 rancher_docker.go:78] Waiting to find IP for d120f3d41e6baa3d84f569fcc32abd0794426a704a179c3a2a7ff630dd4f3f77 
``` 
The mentioned ID is for the docker container:
```
d120f3d41e6b        gcr.io/google_containers/pause:2.0   "/pause"                 6 minutes ago       Up 6 minutes                                                       k8s_POD.cf58006d_nginx_default_ffafa7e4-029c-11e6-9a27-0286285ab4f0_9e19cf89
```

The problem is that i can't always reproduce the problem but i had this issue several times with different situations.

Rancher Version: 1.0.0

K8s is running on top of two 2G machines on digitalocean machine.

**Comment by AlmaasAre** [comment] 2016-05-05 10:02
Running Rancher 1.0.1 + K8s on AWS and get the same error message

**Comment by liyimeng** [comment] 2016-05-10 13:02
Running Rancher 1.0.1 + K8s on Ubuntu 16.04 and get the same error message if hostnetwork=true for a pod.

**Comment by alena1108** [comment] 2016-05-27 23:02
@liyimeng network-mode=Host bug was fixed in Rancher dev2: https://github.com/rancher/rancher/issues/4534

@AlmaasAre @galal-hussein in your case, was it the default network, or host network as well?

**Comment by galal-hussein** [comment] 2016-05-27 23:50
@alena1108 it was the default network.

**Comment by AlmaasAre** [comment] 2016-05-29 15:57
Default

**Comment by alena1108** [comment] 2016-05-31 17:18
@AlmaasAre if the environment is still around, could you check one thing. In Rancher DB, see if you can find a container with external_id = docker container id:

```
select * from instance where external_id=<docker container id>
```

We back populate all the containers started either by docker natively, or via kubernetes, to Rancher. And these containers' external ids = docker container ids. When container starts in kubernetes, we also get the ip address assigned to the container by Rancher. This particular bug is caused by inability to locate container in Rancher based on docker container id.

**Comment by alena1108** [comment] 2016-05-31 17:31
Also if the container with the externalId = docker container id does exist, could you locate it using rancher API and see if the "primaryIpAddress" field is set.

**Comment by AlmaasAre** [comment] 2016-06-01 09:37
Im sorry @alena1108 , i don't have the environment still up and running. But might check it out later. Thanks for answer :)

**Comment by alena1108** [comment] 2016-06-01 17:38
@AlmaasAre thank you, please update this bug if you hit it again. 

@galal-hussein  ^^ :)

**Comment by alena1108** [comment] 2016-09-19 22:12
https://github.com/rancher/rancher/issues/5902

**Comment by alena1108** [comment] 2016-09-23 17:06
Closing as a duplicate of #5902

**Closed by alena1108** 2016-09-23 17:06 UTC
Labels: area/kubernetes, kind/bug
