### ISSUE TITLE
Incompatibility with image names containing multiple forward slashes

### ISSUE THREAD

**Issue by zambon** [rancher/rancher#5484] opened 2016-07-20 18:37 UTC
**Rancher Version:** 1.1.1

**Docker Version:** 1.11.2

**OS and where are the hosts located? (cloud, bare metal, etc):**

* Ubuntu 16.04 64-bit
* SoftLayer - Virtual machines

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**

* Single node rancher
* External database
* Single host (proxy + rancher + db in a Docker Compose file)

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)** Cattle

**Steps to Reproduce:**

1.  Click `INFRASTRUCTURE` -> `Containers`.

1.  Click the `Add Container` button.

1.  In `Select Image`, use an image that has multiple forward slashes (`/`) in their name. E.g.:

    * `myregistry.xyz/foo/bar/image:0.1.0`
    * `myregistry.xyz/super/long/foo/bar/image:0.1.0`

1.  Fill in remaining required fields.

1.  Click `Create`.

**Results:** 

1. UI shows error message: `Validation failed in API: imageUuid`
![validation-error](http://i.imgur.com/2uABdGV.png)

**Expected:**

Compatibility with images that have multiple forward slashes (`/`) in their names.

**Comment by deniseschannon** [comment] 2016-07-22 16:50
Duplicate of https://github.com/rancher/rancher/issues/5025

**Closed by deniseschannon** 2016-07-22 16:50 UTC
Labels: area/service, kind/bug
