### ISSUE TITLE
RKE2 | Custom Windows 2022 cluster | Windows worker is "Unavailable" after snapshot restore

### ISSUE THREAD

**Issue by sgapanovich** [rancher/rancher#36748] opened 2022-03-03 23:03 UTC
**Rancher Server Setup**
- Rancher version: v2.6-head 39befda
- Installation option (Docker install/Helm Chart): Helm
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): RKE2
- Proxy/Cert Details:

**Information about the Cluster**
- Kubernetes version: v1.21.7 and v1.22.10
- Cluster Type (Local/Downstream): Downstream
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider): Custom

   
**Describe the bug**

Windows worker node(s) becomes "Unavailable" with "Kubelet stopped posting node status." message 

**To Reproduce**
 
1. Provision RKE2 custom Windows 2022 cluster (1 linux etcd + cp, 1 linux worker + 2 Windows 2022 workers)
2. Wait for the cluster to provision
3. Navigate to Cluster Management 
4. Take Snapshot of the etcd (three dots menu on the cluster)
5. Wait for the snapshot to be created 
6. Restore "Restore Snaphot" -> Etcd only

**Result**
Tried 3 different clusters. In two of those only 1 windows node became unavailable but in the third cluster all two workers became unavailable.
Tried having nodes with separate roles (etcd and cp) - same result 

**Expected Result**

All nodes are in active and working state after restore

**Screenshots**

![unavailable](https://user-images.githubusercontent.com/40282141/156667427-71248597-e3e3-4bcd-a9e6-4bcdfc964c24.jpg)

kubelet is not running on the node
when trying to start it - it run for a few seconds
![kubelet](https://user-images.githubusercontent.com/40282141/156667556-9578232d-af63-4f31-8ee9-dfc929bd2e59.jpg)

**Additional context**

**when `kubectl get node`**
```
conditions:
  - lastHeartbeatTime: "2022-03-03T22:10:39Z"
    lastTransitionTime: "2022-03-03T22:12:40Z"
    message: Kubelet stopped posting node status.
    reason: NodeStatusUnknown
    status: Unknown
    type: MemoryPressure
  - lastHeartbeatTime: "2022-03-03T22:10:39Z"
    lastTransitionTime: "2022-03-03T22:12:40Z"
    message: Kubelet stopped posting node status.
    reason: NodeStatusUnknown
    status: Unknown
    type: DiskPressure
  - lastHeartbeatTime: "2022-03-03T22:10:39Z"
    lastTransitionTime: "2022-03-03T22:12:40Z"
    message: Kubelet stopped posting node status.
    reason: NodeStatusUnknown
    status: Unknown
    type: PIDPressure
  - lastHeartbeatTime: "2022-03-03T22:10:39Z"
    lastTransitionTime: "2022-03-03T22:12:40Z"
    message: Kubelet stopped posting node status.
    reason: NodeStatusUnknown
    status: Unknown
    type: Ready
```

**Rancher logs**
```
2022/03/03 22:12:23 [INFO] Handling backend connection request [c-m-msqrtvgq]
W0303 22:12:23.376225 32 reflector.go:442] github.com/rancher/rancher/go/pkg/mod/github.com/rancher/client-go@v1.22.3-rancher.1/tools/cache/reflector.go:168: watch of *v1.Secret ended with: an error on the server ("unable to decode an event from the watch stream: tunnel disconnect") has prevented the request from succeeding
W0303 22:12:23.376433 32 reflector.go:442] github.com/rancher/rancher/go/pkg/mod/github.com/rancher/client-go@v1.22.3-rancher.1/tools/cache/reflector.go:168: watch of *v1.ServiceAccount ended with: an error on the server ("unable to decode an event from the watch stream: tunnel disconnect") has prevented the request from succeeding
W0303 22:12:23.376654 32 reflector.go:442] github.com/rancher/rancher/go/pkg/mod/github.com/rancher/client-go@v1.22.3-rancher.1/tools/cache/reflector.go:168: watch of *v1.Role ended with: an error on the server ("unable to decode an event from the watch stream: tunnel disconnect") has prevented the request from succeeding
W0303 22:12:23.376836 32 reflector.go:442] github.com/rancher/rancher/go/pkg/mod/github.com/rancher/client-go@v1.22.3-rancher.1/tools/cache/reflector.go:168: watch of *v1.Namespace ended with: an error on the server ("unable to decode an event from the watch stream: tunnel disconnect") has prevented the request from succeeding
W0303 22:12:23.376838 32 reflector.go:442] github.com/rancher/rancher/go/pkg/mod/github.com/rancher/client-go@v1.22.3-rancher.1/tools/cache/reflector.go:168: watch of *v1.ResourceQuota ended with: an error on the server ("unable to decode an event from the watch stream: tunnel disconnect") has prevented the request from succeeding
W0303 22:12:23.376887 32 reflector.go:442] github.com/rancher/rancher/go/pkg/mod/github.com/rancher/client-go@v1.22.3-rancher.1/tools/cache/reflector.go:168: watch of *v1.ClusterRoleBinding ended with: an error on the server ("unable to decode an event from the watch stream: tunnel disconnect") has prevented the request from succeeding
2022/03/03 22:12:24 [INFO] Handling backend connection request [stv-cluster-c-m-msqrtvgq]
I0303 22:12:46.445297 32 trace.go:205] Trace[1856044629]: "Reflector ListAndWatch" name:github.com/rancher/rancher/go/pkg/mod/github.com/rancher/client-go@v1.22.3-rancher.1/tools/cache/reflector.go:168 (03-Mar-2022 22:12:03.193) (total time: 43252ms):
Trace[1856044629]: ---"Objects listed" 43252ms (22:12:46.445)
Trace[1856044629]: [43.252175226s] [43.252175226s] END
I0303 22:12:46.445935 32 trace.go:205] Trace[75811888]: "Reflector ListAndWatch" name:github.com/rancher/rancher/go/pkg/mod/github.com/rancher/client-go@v1.22.3-rancher.1/tools/cache/reflector.go:168 (03-Mar-2022 22:12:03.035) (total time: 43410ms):
Trace[75811888]: ---"Objects listed" 43410ms (22:12:46.445)
Trace[75811888]: [43.410276704s] [43.410276704s] END
2022/03/03 22:12:46 [INFO] [snapshotbackpopulate] rkecluster fleet-default/rhel122: processing configmap kube-system/rke2-etcd-snapshots
I0303 22:12:46.450192 32 trace.go:205] Trace[1398562026]: "Reflector ListAndWatch" name:github.com/rancher/rancher/go/pkg/mod/github.com/rancher/client-go@v1.22.3-rancher.1/tools/cache/reflector.go:168 (03-Mar-2022 22:12:03.199) (total time: 43250ms):
Trace[1398562026]: ---"Objects listed" 43250ms (22:12:46.450)
Trace[1398562026]: [43.250663856s] [43.250663856s] END
I0303 22:12:46.451737 32 trace.go:205] Trace[753672252]: "Reflector ListAndWatch" name:github.com/rancher/rancher/go/pkg/mod/github.com/rancher/client-go@v1.22.3-rancher.1/tools/cache/reflector.go:168 (03-Mar-2022 22:12:03.149) (total time: 43302ms):
Trace[753672252]: ---"Objects listed" 43302ms (22:12:46.451)
Trace[753672252]: [43.302648437s] [43.302648437s] END
I0303 22:12:46.451900 32 trace.go:205] Trace[742760657]: "Reflector ListAndWatch" name:github.com/rancher/rancher/go/pkg/mod/github.com/rancher/client-go@v1.22.3-rancher.1/tools/cache/reflector.go:168 (03-Mar-2022 22:12:03.118) (total time: 43332ms):
Trace[742760657]: ---"Objects listed" 43332ms (22:12:46.451)
Trace[742760657]: [43.332992701s] [43.332992701s] END
I0303 22:12:46.451737 32 trace.go:205] Trace[971905992]: "Reflector ListAndWatch" name:github.com/rancher/rancher/go/pkg/mod/github.com/rancher/client-go@v1.22.3-rancher.1/tools/cache/reflector.go:168 (03-Mar-2022 22:12:02.961) (total time: 43490ms):
Trace[971905992]: ---"Objects listed" 43490ms (22:12:46.451)
Trace[971905992]: [43.490083996s] [43.490083996s] END
I0303 22:12:46.719634 32 trace.go:205] Trace[780757849]: "Reflector ListAndWatch" name:github.com/rancher/rancher/go/pkg/mod/github.com/rancher/client-go@v1.22.3-rancher.1/tools/cache/reflector.go:168 (03-Mar-2022 22:12:03.577) (total time: 43142ms):
Trace[780757849]: ---"Objects listed" 43142ms (22:12:46.719)
Trace[780757849]: [43.142167239s] [43.142167239s] END
2022/03/03 22:12:46 [INFO] [snapshotbackpopulate] rkecluster fleet-default/rhel122: processing configmap kube-system/rke2-etcd-snapshots
I0303 22:12:54.905072 32 trace.go:205] Trace[2109130654]: "Reflector ListAndWatch" name:github.com/rancher/rancher/go/pkg/mod/github.com/rancher/client-go@v1.22.3-rancher.1/tools/cache/reflector.go:168 (03-Mar-2022 22:12:44.904) (total time: 10000ms):
Trace[2109130654]: [10.000954349s] [10.000954349s] END
E0303 22:12:54.905106 32 reflector.go:139] github.com/rancher/rancher/go/pkg/mod/github.com/rancher/client-go@v1.22.3-rancher.1/tools/cache/reflector.go:168: Failed to watch *v1.Node: failed to list *v1.Node: Get "https://XXXX/k8s/clusters/c-m-msqrtvgq/api/v1/nodes?resourceVersion=109801&timeout=10s": context deadline exceeded
I0303 22:13:56.542803 32 trace.go:205] Trace[1602264513]: "Reflector ListAndWatch" name:github.com/rancher/rancher/go/pkg/mod/github.com/rancher/client-go@v1.22.3-rancher.1/tools/cache/reflector.go:168 (03-Mar-2022 22:13:46.542) (total time: 10000ms):
Trace[1602264513]: [10.000719583s] [10.000719583s] END
E0303 22:13:56.542831 32 reflector.go:139] github.com/rancher/rancher/go/pkg/mod/github.com/rancher/client-go@v1.22.3-rancher.1/tools/cache/reflector.go:168: Failed to watch *v1.Node: failed to list *v1.Node: Get "https://XXXX/k8s/clusters/c-m-msqrtvgq/api/v1/nodes?resourceVersion=109801&timeout=10s": context deadline exceeded
I0303 22:14:42.020467 32 trace.go:205] Trace[331678667]: "Reflector ListAndWatch" name:github.com/rancher/rancher/go/pkg/mod/github.com/rancher/client-go@v1.22.3-rancher.1/tools/cache/reflector.go:168 (03-Mar-2022 22:14:32.019) (total time: 10001ms):
Trace[331678667]: [10.001042789s] [10.001042789s] END
E0303 22:14:42.020500 32 reflector.go:139] github.com/rancher/rancher/go/pkg/mod/github.com/rancher/client-go@v1.22.3-rancher.1/tools/cache/reflector.go:168: Failed to watch *v1.Node: failed to list *v1.Node: Get "https://XXXX/k8s/clusters/c-m-msqrtvgq/api/v1/nodes?resourceVersion=109801&timeout=10s": context deadline exceeded
```

**Comment by phillipsj** [comment] 2022-03-09 15:39
### Root cause 

I wasn't able to reproduce with the latest 2.6-head 47c2238. I believe this could have been firewall or src/dst check related. 

### What was fixed, or what changes have occurred 

Lots of improvements have occurred in the last 6 days that may have fixed this issue. 

### Areas or cases that should be tested 

The case above should be tested.

### What areas could experience regressions?

NA

 ### Are the repro steps accurate/minimal?

The same steps listed above were used. 

1. Taking resotre
![restore](https://user-images.githubusercontent.com/1568133/157475494-67c10873-0295-41fa-bd39-1790333cdbb0.png)

2. Selecting restore

![restore](https://user-images.githubusercontent.com/1568133/157475601-af787301-a1ac-4805-adb9-9dc43d929470.png)

3. Restore complete
![restored-nodes-healthy-in-cm](https://user-images.githubusercontent.com/1568133/157475655-d8c7e5b7-8da8-4e55-8cbe-12b603745a89.png)

4. Checked in cluster explorer and ran kubectl get node command.

![kubectl-command](https://user-images.githubusercontent.com/1568133/157475719-725320b9-d1a1-46f9-879c-3d33f4dfbe0e.png)

**Comment by sirredbeard** [comment] 2022-03-29 15:46
Upstream issue. https://github.com/k3s-io/k3s/issues/5348

**Comment by brandond** [comment] 2022-03-29 18:54
The upstream issue documents that agent nodes cannot join etcd-only nodes. This has never worked; agents must join a control-plane node (one running an apiserver) although we did not really document this anywhere since (initially at least) etcd-only and control-plane only nodes were supposed to be managed by Rancher, which (as I understand it) already enforces this restriction since it is shared with RKE1.

**Comment by sirredbeard** [comment] 2022-04-04 16:23
Order in which nodes are joined, e.g. control plane needs to be up first.

Rancher used to enforce with RKE1, unknown RKE2.

etcd issue with RKE2 has been fixed, will need to wait until pulled into KDM, then test, and investigate further.

**Comment by sirredbeard** [comment] 2022-04-19 15:25
Pending an RC which is waiting on upstream. Release planned 21 Apr.

**Comment by sirredbeard** [comment] 2022-04-26 15:30
Jamie will dev validate if assigned by QA because he did not work on these issues (fix was by RKE2 team), based on KDM RC for RKE2.

**Comment by phillipsj** [comment] 2022-04-27 15:46
@slickwarren this is a different error 

Rancher: v2.6-7db4fe4e81939a5f6b420f303478a169cc35588a-head
RKE2: v1.22.9-rc4+rke2r1

![image](https://user-images.githubusercontent.com/1568133/165557618-7d064e89-7485-440e-ac5b-08a05a4e4abe.png)

Here are the error messages:

```
[Applyinator] Running command: /bin/sh [-c if [ -z $(command -v rke2) ] && [ -z $(command -v rke2-killall.sh) ]; then echo rke2 does not appear to be installed; exit 0; else rke2-killall.sh; fi] error executing instruction 0: exec: "/bin/sh": file does not exist
Connecting to proxy
url=wss://192.168.1.125:9345/v1-rke2/connect
Failed to connect to proxy
error=dial tcp 192.168.1.125:9345: connectex: No connection could be made because the target machine actively refused it
Remotedialer proxy error
error=dial tcp 192.168.1.125:9345: connectex: No connection could be made because the target machine actively refused it.

**Comment by phillipsj** [comment] 2022-04-27 16:11
If this needs to be applied to workers, we need to create a Windows equivalent for stopping rke2.

**Comment by thedadams** [comment] 2022-04-27 16:15
@phillipsj The reason it is getting applied to all nodes that the cluster-agent will get scheduled onto worker nodes if no control-plane nodes are available. This causes issues because Rancher will try to communicate with the downstream cluster through the cluster-agent tunnel, but the api-server isn't running (because the control planes are shutdown).

In the linux-only case, it is easier to shut everything down so that caches/listers will resync when the cluster-agent reconnects rather than erroring out because the api-server is not running.

If this is not correct, then definitely happy to discuss other options.

**Comment by phillipsj** [comment] 2022-04-27 20:31
This is blocking validating the Windows fix. https://github.com/rancher/rancher/issues/37499

**Comment by phillipsj** [comment] 2022-05-03 12:55
The blocker has been removed and I just tested this morning with the latest 2.6-head. Everything restored just fine with a Windows worker present.

![image](https://user-images.githubusercontent.com/1568133/166456582-6ebb7fbc-6e5d-4574-b606-42e0cc201d84.png)

**Closed** 2022-05-03 16:06 UTC
Labels: area/windows, area/etcd, kind/bug-qa, status/dev-validate, status/release-blocker, team/area4, [zube]: QA Review
