### ISSUE TITLE
ETCDSnapshot CRs not cleaned up/not following `etcd-snapshot-retention` value

### ISSUE THREAD

**Issue by BenB196** [rancher/rancher#38711] opened 2022-08-24 13:10 UTC
**Environmental Info:**
RKE2 Version:

`v1.23.9+rke2r1`

Node(s) CPU architecture, OS, and Version:

`Linux k8s01-rancher 5.4.0-124-generic rancher/rke2#140-Ubuntu SMP Thu Aug 4 02:23:37 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux`

Cluster Configuration:

3 server nodes, Etcd snapshot enabled.

**Describe the bug:**

ETCDSnapshot CRs are not cleaned up when there are things like failures.

**Steps To Reproduce:**

- Installed RKE2: `curl -sfL https://get.rke2.io | sudo INSTALL_RKE2_VERSION=v1.23.9+rke2r1 sh -`
- Configure RKE2 with ETCD support (In my case using S3) (Make sure that you configure it incorrectly so that the backup fails)
```yaml
server: https://<snipped>:9345
token: <snipped>
tls-san:
  - <snipped>
  - <snipped>
  - <snipped>
node-name: k8s01-rancher
secrets-encryption: true
disable:
  - rke2-ingress-nginx
etcd-disable-snapshots: false
etcd-snapshot-name: "etcd-snapshot-rancher"
etcd-snapshot-schedule-cron: "0 */1 * * *"
etcd-snapshot-retention: 20
etcd-s3: true
etcd-s3-endpoint: "<s3_compatible_endpoint>"
etcd-s3-access-key: "<snipped>"
etcd-s3-secret-key: "<snipped>"
etcd-s3-bucket: "rke-rancher-backups-<snipped>"
audit-policy-file: "/etc/rancher/rke2/audit-policy.yaml"
```
- Wait for the backup to run (and then fail)
- Let it fail for a while
- See that there are now >20 fails Snapshot CRs
![image](https://user-images.githubusercontent.com/8277432/186426238-87d6f29f-64ce-410a-9c42-2701d3855adf.png)
- Fix snapshot configuration
- Wait for the backup to run (and then succeed)
- See that there are still the failed Snapshot CRs, but also the successful ones
![image](https://user-images.githubusercontent.com/8277432/186426482-771d80bc-937e-47d5-8a51-b74fb82d9e36.png)

**Expected behavior:**

I expect that at most there should only ever be `etcd-snapshot-retention` number of ETCDsnapshot CRs for a given node.

**Actual behavior:**

I see ETCDsnapshot CRs continue to grow past the `etcd-snapshot-retention`.

**Additional context / logs:**

**Comment by BenB196** [comment] 2023-01-22 13:44
Still relevant (that I'm aware)

**Comment by FredNass** [comment] 2023-02-03 16:44
Same here. /var getting full and rke2 server becoming unstable with /lib/rancher/rke2/server/db/snapshots having 170+ snapshots despite  "etcd-snapshot-retention": 100 and snapshots being pushed to S3. This one is nasty.

**Comment by brandond** [comment] 2023-02-03 17:51
@FredNass that is not the same issue. If you are seeing actual snapshots being retained on the RKE2 node itself in violation of your retention settings, please open an issue in the RKE2 repo. This issue is regarding EtcdSnapshot Custom Resources in the Rancher management cluster.

**Comment by FredNass** [comment] 2023-02-03 18:16
@brandond You're right, sorry. I will.

**Comment by BenB196** [comment] 2023-06-16 15:22
Any chance this ticket could be re-opened? It is still an issue with 2.7.4

**Comment by felipe-colussi** [comment] 2023-08-08 19:02
@BenB196 , I'm taking a look into this issue. 
Wile testing I noticed that rancher keeps up to 3 times more ETCDSnapshots  that the expected amount (etcd-snapshot-retention * nodes). 

The Failed s3 snapshots, the local snapshots and the s3 snapshots each have their on limit. 

Can you confirm to me if the problem that u are having is this one?

If you have jq u can run the following commands to list respectively: number of local snapshots number of s3 snapshots and number of failed s3 snapshots. 

```
kubectl get ETCDSNapshot  -n fleet-default -o json |  jq '.items[].metadata|select(.annotations."etcdsnapshot.rke.io/storage"=="local")|.name' | wc -l; 
kubectl get ETCDSNapshot  -n fleet-default -o json |  jq '.items[]|select(.metadata.annotations."etcdsnapshot.rke.io/storage"=="s3" and .snapshotFile.status!="failed")|.metadata.name' | wc -l;
kubectl get ETCDSNapshot  -n fleet-default -o json |  jq '.items[]|select(.metadata.annotations."etcdsnapshot.rke.io/storage"=="s3" and .snapshotFile.status=="failed")|.metadata.name' | wc -l; 

```

**Comment by BenB196** [comment] 2023-08-08 21:49
Hi @felipe-colussi

Here are the outputs of the commands you requested:

```shell
:~$ kubectl get ETCDSNapshot  -n fleet-default -o json |  jq '.items[].metadata|select(.annotations."etcdsnapshot.rke.io/storage"=="local")|.name' | wc -l;
0
```

```shell
:~$ kubectl get ETCDSNapshot  -n fleet-default -o json |  jq '.items[]|select(.metadata.annotations."etcdsnapshot.rke.io/storage"=="s3" and .snapshotFile.status!="failed")|.metadata.name' | wc -l;
45216
```

```shell
:~$ kubectl get ETCDSNapshot  -n fleet-default -o json |  jq '.items[]|select(.metadata.annotations."etcdsnapshot.rke.io/storage"=="s3" and .snapshotFile.status=="failed")|.metadata.name' | wc -l;
0
```

Note: Based on the above, I don't think the current hypothesis is accurate.

For reference:

- This Rancher setup currently manages 9 Kubernetes clusters (including itself)
- Of the 9 clusters, 5 are RKE2 clusters (including the Rancher cluster) and 4 are AWS EKS clusters (imported as generic clusters).
- Of the 5 RKE2 clusters, 1 is 3 nodes (the Rancher cluster), 3 are 4 nodes, and 1 is 6 nodes
- All RKE2 clusters have an S3 backup schedule of `etcd-snapshot-schedule-cron: "0 */1 * * *"` with `etcd-snapshot-retention` being set to either `10` or `20` depending on the cluster.
    - The above configuration is set on all control nodes.
    - Each cluster has 3 control/etcd/worker nodes and any remaining nodes are purely just worker nodes.

**Comment by felipe-colussi** [comment] 2023-08-09 18:09
I do believe that I found your problem. 

Probably the ETCDSnapshots are being marked to be deleted but rancher is not doing the sync-up to delete them.

Just to double check: 

* Did you configured the snapshot Backup through RKE2 instead of rancher? 

Please run the following commands (fell free to remove/edit the names, if possible let me know what kind of installation/import you used for each one) : 

*  Get number of ETCDSnapshots marked as Missing  per cluster (if there is none or few of them please remove the `|select(.status.missing==true)|`):

```
 kubectl get ETCDSnapshots -n fleet-default -o json | jq '.items[]|select(.status.missing==true)|.metadata.labels."rke.cattle.io/cluster-name"' |(tr ' ' '\n' | sort | uniq -c | awk '{print $2"@"$1}')

```

* Check if any cluster have  a machine-plan secret (if you changed names on the previous command  use the same names here). 

```
kubectl get secrets --field-selector type=rke.cattle.io/machine-plan -n fleet-default -o json | jq '.items[].metadata.labels."rke.cattle.io/cluster-name"'

```

If my hypotheses is right you won't have a machine-plan for the nodes with more ETCDSnapshots that the limit.

**Comment by BenB196** [comment] 2023-08-09 18:42
Hi @felipe-colussi yes, the backups are configured via RKE2 and not through Rancher.

Running:

```
 kubectl get ETCDSnapshots -n fleet-default -o json | jq '.items[]|select(.status.missing==true)|.metadata.labels."rke.cattle.io/cluster-name"' |(tr ' ' '\n' | sort | uniq -c | awk '{print $2"@"$1}')
```

I get:

```
"k8s-<cluster_1>"@10079
"k8s-<cluster_2>"@12999
"k8s-<cluster_3>"@11754
"k8s-<cluster_4>"@10144
```

Running

```
kubectl get secrets --field-selector type=rke.cattle.io/machine-plan -n fleet-default -o json | jq '.items[].metadata.labels."rke.cattle.io/cluster-name"'
```

I get nothing returned.

**Comment by felipe-colussi** [comment] 2023-08-10 17:53
@BenB196.

**Short explanation of the problem:** 

When RKE2 creates or deletes an etcd snapshots it populates an configmap called `rke2-etcd-snapshots` on the downstream cluster.
Rancher monitors that configMap creating `ETCDSnapshots` on the local cluster and marking them as "missing" once they are not on the configmap anymore.  Those are used to keep references to the restore object and for restoring snapshot through rancher (only for clusters created by rancher).
To avoid some concurrency problems and not lose valid snapshots the deletion of the `ETCDSnapshots` also depends on some data from `rke.cattle.io/machine-plan`. As the machine-plan is not created for imported clusters the ETCDSnaphsots aren't being deleted.

We are looking for a good way of fixing it. 


**Workaround:** 

All `ETCDSnapshots` marked as "Missing" can be safety deleted. 

I spent some time trying to figure out what would happen if you deleted over 40K objects at once, and unfortunately I wasn't able to find out. 

After talking with the team we figured out that would be safer to run a script that delete some of them and waits for some time to avoid hammering down Kubernetes API. 

You can run something on those lines: 

```

#/bin/bash
mapfile -t my_array < <( kubectl get ETCDSnapshots -n fleet-default -o json | jq '.items[]|select(.status.missing==true)|.metadata.name' |tr -d '"' | head -n 3000)

deleteafterx=15

deleteargs=0
etcds=""
for name in "${my_array[@]}"; do
  deleteargs=$((deleteargs+1))
  etcds=$etcds"$name "
  if (( $deleteargs > $deleteafterx )); then
    kubectl delete -n fleet-default ETCDSnapshot $etcds --wait=true
    deleteargs=0
    etcds=""
    sleep 5
  fi
done
kubectl delete -n fleet-default ETCDSnapshot $etcds

```

If you choose to run the script please monitor the output.

The script is also on the safer side, the delete is limited and have a 5s sleep to make sure it will not affect kubernetes on any way. 

Fell free to edit it, the values that you can tweak around are: 
`sleep 5` delay between kubectl delete execution.
`deleteafterx` the number of names passed on the kubectl delete
`head -n 3000` you can even remove it, this will make the script run only in 3000 objects.

**Comment by BenB196** [comment] 2023-08-10 20:41
Hi @felipe-colussi thanks for the explanation as well as the script! I've run it a few times now and it has been successful in remove a good chunk of the resources already. I'll continue to run the script to clean up the remaining objects.

Do you think it would be a reasonable thing to have this script run nightly to prevent this issue from getting this bad again until a formal fix is implemented in Rancher?

**Comment by BenB196** [comment] 2023-08-11 13:09
@felipe-colussi one additional update here, I finished running the script, but noticed that there were still ~10k resources remaining. Looking into this a bit more, it seems like the same issue happens with the local snapshots as well.

Running:

```shell
:~$ kubectl get ETCDSnapshots -n fleet-local -o json | jq '.items[]|select(.status.missing==true)|.metadata.name' |tr -d '"' | wc -l
10410
```

(Replacing `-n fleet-default` with `-n fleet-local`)

I updated the script to just use `--all-namespaces` instead to deal with this.

**Comment by felipe-colussi** [comment] 2023-08-11 18:50
@BenB196.

Sorry I didn't had the snapshots enabled on my local cluster, and I didn't noticed  that they would be stored on a different namespace.

That script won't work just changing by changing `-n fleet-local ` to `--all-namespaces`. The  `delete ... --all-namespaces` won't work.   You probably will need to change the namespace to the one you need or use a variable namespace.  

If you didn't use the sleep something on this lines will do: 

```
#/bin/bash
mapfile -t my_array < <( kubectl get ETCDSnapshots --all-namespaces -o json | jq '.items[] | select(.status.missing==true) | .metadata.name + " " + .metadata.namespace'| tr -d '"' | head -n 3000)

for data in "${my_array[@]}"; do
  arr=( $data )
  kubectl delete ETCDSnapshots "${arr[0]}" -n "${arr[1]}"
done

```

About running it every night: it would be OK, is not the prettiest solutions but it will have the job done.

Today I'll talk with the team, and probably will try to find a better workaround that doesn't include running a bash script every-night.

**Comment by felipe-colussi** [comment] 2023-08-11 19:55
For internal tracking: 

The scope of this issue will be limited to  “Stop storing ETCDSnapshots for imported clusters”

**Comment by felipe-colussi** [comment] 2023-08-15 12:31
## Validation Template

## Root Cause

We had no way of setting the trace-level for rancher-agent . 

## What was fixed, or what change have occurred

Now is possible to to add trace-level using   Agent Environment Vars. 
 `CATTLE_TRACE` or `RANCHER_TRACE` must be  set to `true`

## Areas or cases that should be tested

- Using rancher Create a RKE2 cluster  with ETCD snapshots configured, this should work normally.
- Create a RKE2 cluster with ETCDSnapshots configured directly on the RKE2. This should not create ETCDSnapshots on rancher.


## What areas could experience regressions

None. 

## Are the repro steps accurate/minimal?

Yes. After checking the scope of the Issue was limited to not storing  ETCDSnapshots for imported RKE2 clusters.

**Comment by susesgartner** [comment] 2023-09-22 17:52
Ticket # - Test Results - Pass ✅ 
---

Verified with (HA Helm or Docker) on Rancher `v2.8`:

Scenario 1 -
1. Installed RKE2 with etcd support and S3 snapshots
2. Confirmed that the cluster could be imported with no issues
3. Confirmed that no snapshots were created on the rancher side.

**Closed by susesgartner** 2023-09-22 17:52 UTC
Labels: kind/bug, [zube]: QA Working, area/provisioning-v2, team/area2
