### ISSUE TITLE
[RKE2 s3 snapshot] 2 copies of snapshot are created and snapshots are not backed up in S3 bucket

### ISSUE THREAD

**Issue by timhaneunsoo** [rancher/rancher#36941] opened 2022-03-17 15:48 UTC
**Rancher Server Setup**
- Rancher version: v2.6-head
- Installation option (Docker install/Helm Chart):
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): RKE2
- Proxy/Cert Details:

**Information about the Cluster**
- Kubernetes version: v1.21.10+rke2r2
- Cluster Type (Local/Downstream):
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider): AWS EC2

**User Information**
- What is the role of the user logged in? (Admin/Cluster Owner/Cluster Member/Project Owner/Project Member/Custom)
  - If custom, define the set of permissions:
Admin

   
**Describe the bug**

Snapshot action seems to take two copies of the snapshot, with one being empty. Non of the snapshots are begin backed up in S3 bucket

**To Reproduce**
 
Create RKE2 Cluster
- in etcd configuration, set `Backup Snapshots to S3` to `Enable` and fill out S3 bucket information

**Result**
When taking snapshot, nothing is uploaded to the S3 bucket

**Expected Result**

A backup of the snapshot should be uploaded to the S3 bucket

**Screenshots**

![image](https://user-images.githubusercontent.com/97477402/158838888-fe901d08-09ce-4061-978d-3513d25c5891.png)
![image](https://user-images.githubusercontent.com/97477402/158838922-c77cbbf4-56a7-410b-a2a6-d465c3b404cd.png)

**Additional Context**
Not sure if this is relevant but when I go to `Edit Config` and go to etcd configuration where the fields for the S3 bucket are, the `Backup Snapshots to S3` is set to `Enable` but the rest of the fields are empty
![image](https://user-images.githubusercontent.com/97477402/158839623-40ce2067-3c26-46c0-b1f9-d4f57f57daa3.png)

**Comment by snasovich** [comment] 2022-03-21 20:52
For snapshots to be stored in S3 we require deeper changes; that's why moving to 2.6.5.

**Comment by Oats87** [comment] 2022-03-31 11:25
Analyzing this issue, there seems to be a few things causing issues.

Regarding two snapshots being created, this is expected behavior when using S3 snapshots. This is because we have a reference to both a local snapshot and the snapshot in S3. We should likely have a dashboard enhancement to display the snapshot storage location i.e. local vs. S3.

Regarding S3 snapshots not showing up, this is being caused due to some changes within the planner around the way we handle S3 credential rendering.

We have two methods of rendering S3 credentials -- the first is argument, and the second is environment variable. 

We recently switched to always using environment variable for S3 credentials. This poses an issue for when we are rendering the configuration file for K3s/RKE2 in general (for the recurring snapshots) as we discard the credentials and never render them into the config file for the K8s engine. 

On the one-time snapshots/restore cases, it appears that we are attempting to set the environment variables but they are not being properly used. The RKE2 CLI states:
```
   --s3-access-key value, --etcd-s3-access-key value    (db) S3 access key [$AWS_ACCESS_KEY_ID]
   --s3-secret-key value, --etcd-s3-secret-key value    (db) S3 secret key [$AWS_SECRET_ACCESS_KEY]
```
and we are correctly setting that environment variable here:
https://github.com/rancher/rancher/blob/dafffc295b7139f94eefe8ab68cb7fec63641d3a/pkg/provisioningv2/rke2/planner/s3args.go#L57

Coincidentally, what we *used* to do is:

```
1. recurring etcd snapshot creation (i.e. rendered into the k3s/rke2 config file so they consume and use the credentials)
prefix: "etcd-"
env: false

2. one-time etcd snapshot creation
prefix: ""
env: true

3. etcd snapshot restore
prefix: "etcd-"
env: true
```

What we do now is 
```
prefix: "etcd-"
env: true
```

More research will need to be done to determine why one-time etcd snapshots are not being uploaded to S3.

**Comment by Oats87** [comment] 2022-04-05 15:41
S3 snapshots should now work.

There is a separate UI enhancement that is necessary, namely the issue https://github.com/rancher/dashboard/issues/5553 which will be how we distinguish between S3 and local snapshots. Until then, it is going to be very difficult to properly test this issue.

**Comment by timhaneunsoo** [comment] 2022-04-08 19:39
Will test once [5553](https://github.com/rancher/dashboard/issues/5553) is complete

**Comment by rak-phillip** [comment] 2022-04-12 20:21
@Oats87 @timhaneunsoo UI should be ready test with rancher/dashboard#5553

**Comment by timhaneunsoo** [comment] 2022-04-12 21:22
### Test Environment: ###
Rancher version: v2.6-head b0b5179
Rancher cluster type: HA
Docker version: 20.10

Downstream cluster type: RKE2 EC2 AWS Node driver

----------

### Testing: ###

Tested this issue with the following steps:
1. Create RKE2 Cluster
2. in etcd configuration, set `Backup Snapshots` to S3 to `Enable` and fill out S3 bucket information

**Result** - Low Pass

The UI changes are now distinguishing between local and S3 snapshots, but there still seems to be no files uploaded to the S3 bucket.
![image.png](https://zube.io/files/rancher/887d945f311dcd95686ce39bf0fb78a6-image.png)

**Comment by timhaneunsoo** [comment] 2022-04-14 17:42
My mistake, there was an issue with authentication.

The etcd snapshot backups are now successfully uploaded to the S3 bucket.

![image.png](https://zube.io/files/rancher/79b0d3a5ee3f66ae4f4201994b0e94df-image.png)

![image.png](https://zube.io/files/rancher/4777dbfcba4a2007bfb95a23a06add1e-image.png)

**Closed** 2022-04-14 17:42 UTC
Labels: kind/bug-qa, [zube]: Reopened, area/provisioning-rke2, status/release-blocker, team/area2
