### ISSUE TITLE
If service container create fails, the service keeps trying and creating multiple versions

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#557] opened 2015-04-17 19:58 UTC
v0.16.3
Steps:
1.  Create an environment
2.  Add a Service, Scale set to 1 but with invalid container info

Results:
Service will keep trying and display looks like it's creating more then 1 container.

![image](https://cloud.githubusercontent.com/assets/11514927/7209865/6633cd3a-e501-11e4-84a8-912dfcef2f51.png)

Expected:
Service to stop and container to remove

**Comment by alena1108** [comment] 2015-04-17 20:42
@ibuildthecloud Darren, what do you think should be the best strategy to do the cleanup if something fails during the service activate? I remember when we initially discussed it, we agreed its ok just to keep on trying as there is no way for us to determine if the container failed to start due to misconfiguration, or data center failures (network being down, etc). So the service will be in Activating state, and will try to launch the "scale" number of containers over and over again.

I can implement cleaning up all the containers, and moving service state back to Inactive if something had failed (and update transitioning message on the service indicating the failure). 

@will-chan @vincent99 would like to get your opinion too as I know we handle it differently for other cattle resources (machine moves to error state, failed container moves to removed state)

**Comment by vincent99** [comment] 2015-04-17 21:06
Sidebar: the most common way to get into this situation seems like it would be an invalid imageUuid.  It would be nice to have an action to attempt to validate them before the user submits a container in the UI in the first place.

In general I think any resource where you do a create, get back a 201/202 and it might fail to create later should have an `error` state.  That's part of #384 and would include most of the major resources (Machine, Container, Load Balancer, Cluster, Service, etc), though only Machine has it today.

Trying to create over and over again constantly forever seems not ideal.  Maybe retry a few times with a small but increasing delay, cleaning up the failed containers after each try?  If after `N` tries you don't have any active containers give up and move the service to `state=error`.

**Comment by alena1108** [comment] 2015-04-17 21:07
@vincent99 I will move image validation to API filters then.

**Comment by vincent99** [comment] 2015-04-17 21:10
@alena1108 I don't think it's that simple.. The format of the uuid might be valid but you don't know that image actually exists until we try to pull it from the registry (using the appropriate credentials, etc).

**Comment by alena1108** [comment] 2015-04-17 22:06
@vincent99 I will try to pull the image before invoking the handlers - thats what I've meant. If the image is invalid, API will throw a client visible error

**Comment by alena1108** [comment] 2015-04-17 22:10
But we should definitely address the generic containers cleanup problem

**Comment by deniseschannon** [comment] 2015-12-03 22:58
Pre-duplicate of https://github.com/rancher/rancher/issues/820

Essentially, we need better error message when service will fail to scale due to lack of open ports or invalid container info.

**Closed by deniseschannon** 2015-12-03 22:58 UTC
Labels: area/service, kind/bug
