### ISSUE TITLE
Cannot connect to web kubectl shell.

### ISSUE THREAD

**Issue by biolounge** [rancher/rancher#6930] opened 2016-12-05 13:38 UTC
**Rancher Version:**
v1.2
**Docker Version:**
Server:
 Version:      1.12.3
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   6b644ec
 Built:
 OS/Arch:      linux/amd64
**OS and where are the hosts located? (cloud, bare metal, etc):**
AWS EC2 (Centos 7)

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
Single master rancher with external DB
**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Kubernetes
**Steps to Reproduce:**
Create kubernetes environment and add nodes to it

**Results:** 
kubectl web shell interface is not accessible.
Shell: kubernetes-kubectld-1
Closed

Catalog listing is also not working.
Catalog-> list
redirects to stacks page

**Comment by superseb** [comment] 2016-12-05 19:05
Can you verify if this is the same issue? https://github.com/rancher/rancher/issues/6861

**Comment by biolounge** [comment] 2016-12-06 08:34
Looks like same.

**Comment by tfiduccia** [comment] 2016-12-09 18:27
Duplicate of #6861, closing in favor of that.

**Closed by tfiduccia** 2016-12-09 18:27 UTC
