### ISSUE TITLE
[BUG] k3s node driver clusters is stuck on provisioning with the error validating data: failed to download openapi

### ISSUE THREAD

**Issue by anupama2501** [rancher/rancher#46062] opened 2024-07-08 21:56 UTC
**Rancher Server Setup**
- Rancher version: Upgraded from 2.8.5 >> v2.9-head `1c2b815c8`
- Installation option (Docker install/Helm Chart): Helm and Docker
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc):
- Proxy/Cert Details:

**Information about the Cluster**
- Kubernetes version: v1.28.10+k3s1, v1.30.2+k3s2

- Cluster Type (Local/Downstream): Downstream node driver k3s cluster - Linode and AWS

**User Information**
- What is the role of the user logged in? (Admin/Cluster Owner/Cluster Member/Project Owner/Project Member/Custom)
Admin

**Describe the bug**
k3s node driver cluster created on an upgraded rancher server are stuck in provisioning state and are not coming active.

**To Reproduce**
1. Create a rancher server v2.8.5
2. Created a k3s AWS node driver cluster - 3 nodes 1 role each
3. Upgrade rancher server to 2.9-head 
4. Create a linode k3s cluster version `v1.30.2+k3s2` - all roles

**Result**
k3s Cluster does not come up active 

**Expected Result**
Expected the cluster to come up active

**Additional context**
Following error log is produced on the cluster 
```
Error while applying agent YAML, it will be retried automatically: exit status 1, error: error validating "./management-statefile_path_redacted": error validating data: failed to download openapi: Get "https://localhost:443/k8s/clusters/c-m-tvlvrscw/openapi/v2?timeout=32s": net/http: request canceled (Client.Timeout exceeded while awaiting headers); if you choose to ignore these errors, turn validation off with --validate=false
```

### Note: 

- I noticed this only when the downstream cluster is created with Linode providers and not on AWS cloud providers on rancher HA helm install 
- Notice this for when the downstream k3s cluster is created on AWS and Linode cloud providers on docker install.
- Do not notice this when rancher server is created on v2.9-head[fresh install] and issue is only noticed on an upgrade of rancher server from v2.8.5 to v2.9-head
- Issue is not seen on rke2 and rke1 node driver clusters.

**Comment by susesgartner** [comment] 2024-07-09 00:42
This can also occurs when provisioning downstream clusters on 2.8 and then upgrading to 2.9. Its not consistent but I did encounter this once when doing some upgrade validations.

**Comment by Oats87** [comment] 2024-07-09 19:27
I have determined that the root cause for this issue is logic that is fundamentally flawed that was merged as part of PR: https://github.com/rancher/rancher/pull/45510

It is causing impersonation setup to take longer than we want, hence why the requests are hanging the way that they.

**Comment by markusewalker** [comment] 2024-07-10 16:57
Validated that this is addressed on `v2.9-head` https://github.com/rancher/rancher/commit/3a6de11e4de9a4edaaf971ee5b91c6cc6f141200.

**ENVIRONMENT DETAILS**
- Rancher install: Docker
- Rancher version:
     - Fresh install: `v2.8.5`
     - Upgrade: `v2.9-head` https://github.com/rancher/rancher/commit/3a6de11e4de9a4edaaf971ee5b91c6cc6f141200

**TEST RESULT**
|#|Scenario|Result
|---|---|---|
|1|Upgrade Rancher 2.8 -> 2.9-head with downstream K3s node driver clusters|:white_check_mark:|
|2|Upgrade downstream K3s node driver clusters on upgraded Rancher|:white_check_mark:|
|3|Provision downstream K3s node driver cluster on upgraded Rancher|:white_check_mark:|

**VALIDATION STEPS**

**Scenario 1**
1. Setup Rancher v2.8.
2. Provisioned the following K3s v1.27 clusters:
     - 1 node all roles
     - etcd/cp node + 1 worker node
     - 1 etcd, 1 cp, 1 worker
3. Upgraded Rancher v2.8 -> v2.9-head.
4. Validated all clusters and nodes are `Active`.

______

**Scenario 2**
1. Following scenario 1, upgraded the K3s v1.27 clusters to `v1.30.2+k3s2`.
2. Validated that the clusters and nodes upgraded and are `Active`.

_______

**Scenario 3**
1. Following scenario 1, provisioned a K3s v1.30.2+k3s2 cluster (1 node all roles).
2. Validated the clsuter and nodes came up as `Active`.

**Closed by markusewalker** 2024-07-10 16:57 UTC
Labels: kind/bug, status/release-blocker, team/hostbusters

**Comment by XXMY** [comment] 2025-04-12 15:31
I encountered the same issue in version 2.9.3 and spent 12 hours on it. The method that finally worked was to restart the Rancher Server cluster's deployment. At the same time, when importing the agent cluster, I set the environment variable: `CATTLE_FEATURES=embedded-cluster-api=false,fleet=false,multi-cluster-management=false,multi-cluster-management-agent=true,provisioningprebootstrap=false,provisioningv2=false,rke2=false,ui-sql-cache=false`
