### ISSUE TITLE
[2.5 backport] istio v2 cannot deploy in a hardened cluster

### ISSUE THREAD

**Issue by cbron** [rancher/rancher#33173] opened 2021-06-13 23:16 UTC
https://github.com/rancher/rancher/issues/28622

**Comment by dhruvmewada15** [comment] 2022-02-04 12:57
**Steps followed:**

- Rancher Server: 2.5.12
- Created a 3 node single role downstream hardened cluster (1 cp, 1 etcd, 1 worker)
- Installed Monitoring chart from Apps and Marketplace : 16.6.1+up16.6.0
- Installed Istio chart from Apps and Marketplace : 1.10.400

**Result:**
The Istio got installed successfully. The issue is not Active

**Comment by vivek-infracloud** [comment] 2022-02-10 06:51
**Validated on rancher v2.5.12** 

Steps followed to validate the issue.

1. Created rancher server v2.5.12
2. Created a 3 node single role downstream **hardened cluster** (1 cp, 1 etcd, 1 worker). Followed [this](https://rancher.com/docs/rancher/v2.5/en/security/rancher-2.5/1.6-hardening-2.5/) hardening guide.

- > Make sure worker node amounts to more than 6 CPUs.
3. Installed Monitoring chart from Apps and Marketplace : 16.6.1+up16.6.0
4. Installed Istio chart from Apps and Marketplace : 1.10.400

**Result:**
**The Istio installs successfully.**

**Comment by vivek-infracloud** [comment] 2022-02-10 06:51
Based on above validation, the issue is not active. Hence, closing the issue.

**Closed by vivek-infracloud** 2022-02-10 06:51 UTC
Labels: [zube]: QA Working, feature/charts-istio, team/area3, team/infracloud
