### ISSUE TITLE
rancher cannot create catalog from private helm-chart catallog which from harbor？

### ISSUE THREAD

**Issue by bobo200128** [rancher/rancher#20140] opened 2019-05-10 01:35 UTC
**harbor  1.7.5**  
sudo ./install.sh --with-notary --with-clair --with-chartmuseum

**rancher 2.2.1**

http://***.***.***.***/chartrepo/helm

**problem:**
in rancher,create catalog failed.the log is

Helm template failed. Error: stat template-dir: no such file or directory : exit status 1

**Desired solution：**
can create catalog from private helm chart

**Comment by bobo200128** [comment] 2019-05-10 03:34
**add**
helm serve can resolve the problem.
But I think there are better ways

**Comment by superseb** [comment] 2019-05-10 08:52
Duplicate of https://github.com/rancher/rancher/issues/18535

**Closed by superseb** 2019-05-10 08:52 UTC
