### ISSUE TITLE
Monitoring - Cluster Metrics is reporting only 1 out of 3 nodes

### ISSUE THREAD

**Issue by IsNull** [rancher/rancher#19187] opened 2019-03-26 16:58 UTC
**What kind of request is this (question/bug/enhancement/feature request):**

Bug

**Steps to reproduce (least amount of steps as possible):**

* Create a 3 node cluster
* Enable monitoring

**Result:**

Monitoring generally works, Cluster metrics are only showing data from node-3. All other metrics are reported from all the nodes:

### Cluster Dashboard

<img width="1268" alt="Screenshot 2019-03-26 at 17 40 13" src="https://user-images.githubusercontent.com/439313/55016093-6366c100-4fee-11e9-87ce-e1ac8cb33ac8.png">

### Cluster Metrics 

<img width="1219" alt="Screenshot 2019-03-26 at 17 41 00" src="https://user-images.githubusercontent.com/439313/55016101-65c91b00-4fee-11e9-95e1-12c5c11be79b.png">

### Etcd Metrics

<img width="1281" alt="Screenshot 2019-03-26 at 17 47 26" src="https://user-images.githubusercontent.com/439313/55016566-51d1e900-4fef-11e9-8cbd-02b75a6268ae.png">

Note that all 3 nodes have an even amount of workloads running.

Node 1 and 2 which are not reporting data look like this:

<img width="1405" alt="Screenshot 2019-03-26 at 17 55 45" src="https://user-images.githubusercontent.com/439313/55017161-724e7300-4ff0-11e9-853d-61d7f033bc25.png">

Grafana however shows this:

<img width="1535" alt="Screenshot 2019-03-26 at 18 03 31" src="https://user-images.githubusercontent.com/439313/55017678-7e870000-4ff1-11e9-9463-d0da70c00384.png">

**Other details that may be helpful:**

**Environment information**

The cluster is a RKE deployed on AWS VMs using Rancher.

* rancher/rancher:latest (2.2)
* Kubelet v1.11.6
* Docker 17.3.2

**Comment by loganhz** [comment] 2019-03-26 23:17
@IsNull Can you check it in Prometheus UI to see if there is any metrics target is red? Can you check if the node exporter is deployed in those 2 nodes? You can check it in the system project apps cluster-monitoring app.

Another thing is that now we need the node exporter pod open in your firewall on each nodes. You need to make sure Prometheus can access the node exporter pod via internal IP. It will be improved in https://github.com/rancher/rancher/issues/17957

**Comment by loganhz** [comment] 2019-03-26 23:17
@n313893254 Can we fallback to the gauge instead of showing the `Loading` ?

**Comment by IsNull** [comment] 2019-03-27 08:04
Prometheus shows two unhealthy targets

<img width="1529" alt="Screenshot 2019-03-27 at 08 51 22" src="https://user-images.githubusercontent.com/439313/55058950-dcf1c400-506d-11e9-99e9-e962d7194786.png">

<img width="1530" alt="Screenshot 2019-03-27 at 08 51 04" src="https://user-images.githubusercontent.com/439313/55058954-e0854b00-506d-11e9-9e3c-37cf56887a60.png">

As far as I can tell from the workload by node view, the node exporter runs on all nodes. 

Its probably a firewall issue, below is the (automatically created) security group:

<img width="514" alt="Screenshot 2019-03-27 at 09 01 47" src="https://user-images.githubusercontent.com/439313/55059339-fc3d2100-506e-11e9-929f-6fed2f21dec5.png">

I try to open the ports and report back.

**Comment by IsNull** [comment] 2019-03-27 08:11
Ok, the issue is resolved when inbound ports 10254 & 9796 are opened for the other rancher nodes.

Since rancher automatically configured the security groups when the cluster was installed, it would probably a good idea to automatically open the new required ports. If that is not possible, some kind of check and warning in the ui about it would probably make it much easier to grasp why its not working.

**Comment by cjellick** [comment] 2019-03-29 18:57
@deniseschannon we need to update this in the docs.
We need to update the rancher-nodes security group

**Comment by cjellick** [comment] 2019-03-29 18:57
@loganhz can you confirm which ports need to be opened for monitoring?

**Comment by loganhz** [comment] 2019-03-29 23:19
The node exporter port which user input when enable monitoring. The default port is 9796. But users can change it to any port.

If we implement #17957 , we don't need any port.

**Comment by jiaqiluo** [comment] 2019-04-01 20:33
The issue is reproduced on Rancher v2.2.1
Steps:
- run Rancher v2.2.1 in single installed mode
- add an EC2 cluster with 4 nodes(1 etcd, 1 control plane, 2 workers) with Rancher-generated security group
- enable the cluster monitoring when the cluster is active

Result:
The same result as the issue describes.

**Comment by davidnuzik** [comment] 2019-04-09 23:11
v2.2.2-rc7

I followed the same exact steps that @jiaqiluo suggested in order to try to reproduce the issue in v2.2.2-rc7.

- Run Rancher (v2.2.2-rc7) in single installed mode
- add an EC2 cluster with 4 nodes(1 etcd, 1 control plane, 2 workers) with Rancher-generated security group
![image](https://user-images.githubusercontent.com/45179589/55840290-cfadee00-5adf-11e9-9059-dbcaa83f2980.png)
- enable the cluster monitoring when the cluster is active

I seem to have reproduced what was originally reported:
![image](https://user-images.githubusercontent.com/45179589/55840875-e3f2ea80-5ae1-11e9-8ef5-15103354c4bc.png)

When I check grafana everything looks fine.
![image](https://user-images.githubusercontent.com/45179589/55840901-f705ba80-5ae1-11e9-8312-a2c5c6e7ce95.png)

I am not certain how to access prometheus but am happy to help further if I can provide any additional information @loganhz

**Comment by davidnuzik** [comment] 2019-04-09 23:13
When I check the SG 10254 & 9796 are NOT open.

**Comment by BalaBalaYi** [comment] 2019-04-23 01:57
Create a 6 nodes cluster:
![image](https://user-images.githubusercontent.com/23303886/56546783-e8250a80-65ad-11e9-9b9c-b042dd9017a5.png)

Enable cluster monitoring and enter grafana.
Shows only 6 node in node selector:
![image](https://user-images.githubusercontent.com/23303886/56546859-28848880-65ae-11e9-8738-a33e65cfe0b3.png)

Shows only 1 node in node selector:
![image](https://user-images.githubusercontent.com/23303886/56546886-3b975880-65ae-11e9-83d2-52d105592776.png)

**Comment by loganhz** [comment] 2019-04-23 02:14
@BalaBalaYi https://github.com/rancher/rancher/issues/19187#issuecomment-476891083

**Comment by BalaBalaYi** [comment] 2019-04-23 02:52
@loganhz  The metrics target in prometheus is red (only 1 is fine):
![image](https://user-images.githubusercontent.com/23303886/56549573-ad26d500-65b5-11e9-90e8-bc04ddae2303.png)

**Comment by BalaBalaYi** [comment] 2019-04-23 03:05
@loganhz My current security group is configured depends on https://rancher.com/docs/rancher/v2.x/en/installation/requirements/

Should i changed the configuration and add 10254 & 9796 with ingress rules?

**Comment by alena1108** [comment] 2019-04-24 03:03
@loganhz recapping of what we talked about offline. In 2.2.3 where node exporter still needs to expose itself via node port service, we should:

- [ ] Add the default port to AWS and Azure default SG
- [ ]  Improve documentation around what needs to be done for other providers or/and custom ports, to expose the access to the ports.

In 2.3, we are going to consider moving away from using the node port service, and use a cluster ip service instead. The progress will be tracked in https://github.com/rancher/rancher/issues/17957

**Comment by loganhz** [comment] 2019-05-04 05:52
Waiting for https://github.com/rancher/machine/pull/21 merged and released. And updated it in 2.2 and master branch.

**Comment by westlywright** [comment] 2019-05-06 16:53
Available in master and `2.2.55`

**Comment by davidnuzik** [comment] 2019-05-20 20:40
Note: Because this was recently reproduced and confirmed, reproduction steps are not included in this comment.

This issue resolved a few things:

https://github.com/rancher/ui/pull/2838 which basically falls back to the standard dashboard view if monitoring is not ready and healthy.

https://github.com/rancher/rancher/pull/20138 `Add default monitoring node exporter port into aws node driver security group` which was an important fix so that when we provision a cluster with ec2 node driver the rancher-generated security group now opens a required port.
https://github.com/rancher/ui/pull/2956 is the same thing but basically for azure
There was no need to make changes for other node drivers we include with Rancher; we updated docs to be more clear what ports need to be open, etc.

-------------------------------------------
Version: Master (v2.3) (5/20/19)

**Dashboard fallback tests**
_This tests the changes made to let dashboards fall back to standard view when monitoring is not ready or is not healthy._

I tested this by deleting the `prometheus-cluster-monitoring` pod. The UI immediately sees that monitoring is not healthy and quickly switches back to the standard cluster view. When the pod recovers and is back up the UI quickly switches back to the monitoring cluster dashboard.

**AWS EC2**
_This tests the change made so that when you create an ec2 cluster and use rancher-generated security group the appropriate ports are opened now and cluster metrics are shown for all schedulable nodes now._ This is a backend change that you can check in AWS web console.

Confirmed when you create an ec2 cluster, the security group now includes 9796 TCP.
![image](https://user-images.githubusercontent.com/45179589/58049654-3b816e80-7b02-11e9-9333-196f2d17896b.png)

I brought this cluster up (3 nodes each with all roles) and enabled monitoring. I confirmed that we see metrics for ALL 3 NODES both in the Rancher UI (hover over charts shows all 3 nodes) and Grafana UI (node selector shows all 3 nodes and hover over charts shows all 3 nodes).

**Azure**
_This test does the same, but for Azure. Basically with Azure, in the UI, we now include the required ports by default._ This is a frontend change that you can check in Azure web console.

Confirmed when you create an azure template we now also include `9796/tcp` under "Open Port" in the "Instance" section. This was not there before (I compared to v2.2.2) and would cause the issue where we don't get metrics for all schedulable nodes.
![image](https://user-images.githubusercontent.com/45179589/58047948-5356f380-7afe-11e9-915e-0d0420afd7f3.png)
(Note I accidentally highlighted wrongly in screenshot, it's `9796/tcp`)

I brought this cluster up (3 nodes each with all roles) and enabled monitoring. I confirmed that we see metrics for ALL 3 NODES both in the Rancher UI (hover over charts shows all 3 nodes) and Grafana UI (node selector shows all 3 nodes and hover over charts shows all 3 nodes).

I confirmed that in the Azure web console that port 9796 TCP is indeed open.
![image](https://user-images.githubusercontent.com/45179589/58049270-48ea2900-7b01-11e9-8632-04db32da6cf6.png)

**Other**
I also tested using DigitalOcean RKE and with GKE (defaults), AKS (defaults), EKS (defaults, rancher-generated VPC & Subnet; note there is a known bug for grafana icons not showing up). Just for good measure. This issue was not seen in these areas before but I briefly tested each to make sure monitoring is still working correctly and we see data for all nodes.

For each test and testing the other clusters I did basic smoke testing of monitoring as well, checking cluster dashboard, node dashboard, workload/pod/container charts and etc.

**Closed by davidnuzik** 2019-05-20 20:40 UTC
Labels: [zube]: To Test, area/monitoring, kind/bug, status/blocker, status/ready-for-review, status/reopened, status/resolved, status/to-test, status/triaged, team/cn

**Comment by mshivanna** [comment] 2020-02-02 04:37
If anyone is experience this issue on custom nodes open up port 9796.

`firewall-cmd --permanent --add-port=9796/tcp`
It would be good if this is update in the documentation here https://rancher.com/docs/rancher/v2.x/en/installation/options/firewall/
