### ISSUE TITLE
Failed authentication attempts with remote registries aren't obvious

### ISSUE THREAD

**Issue by discoposse** [rancher/rancher#4917] opened 2016-05-25 21:41 UTC
*Describe your issue here*

When using incorrect credentials for Docker Registry, there was no attempt to check during setup.  Only on launch of the containers does it show an error when initializing the network agent that throws a 401 or 500 error and the message contains some wording about docker registry username error. 

During setup of registry, the credentials should be attempted first before confirming the registry is attached.
---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v1.1.0-dev2` Cattle: `v0.161.5` UI: `v1.1.2` |
|Access|`github` `admin`|
|Orchestration|`Cattle`|

**Comment by deniseschannon** [comment] 2016-05-26 06:04
Duplicate of https://github.com/rancher/rancher/issues/300

**Closed by deniseschannon** 2016-05-26 06:04 UTC
