### ISSUE TITLE
Graphs are not working

### ISSUE THREAD

**Issue by roderik** [rancher/rancher#4539] opened 2016-04-23 20:49 UTC
https://www.dropbox.com/s/ru8jm6nsa8gjh43/Screenshot%202016-04-23%2022.46.59.png?dl=0

Rancher Version: v1.0.1

Docker Version: 
```
Containers: 15
 Running: 4
 Paused: 0
 Stopped: 11
Images: 10
Server Version: 1.11.0
Storage Driver: overlay
 Backing Filesystem: extfs
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: host bridge null
Kernel Version: 4.4.0-21-generic
Operating System: Ubuntu 16.04 LTS
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 7.796 GiB
Name: one-docker
ID: HV6W:LBQK:IQLK:42SB:QIUO:K7X7:MNQG:RAQT:CNZI:W7DR:QKPP:ZMIY
Docker Root Dir: /var/lib/docker
Debug mode (client): false
Debug mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
```
OS: Ubuntu 16.04

**Comment by deniseschannon** [comment] 2016-04-23 21:45
Duplicate of https://github.com/rancher/rancher/issues/4406

v1.0.1 only support Docker 1.10.3. 

But there are also known issues about Ubuntu 16.04 and Docker 1.10.3. 
https://github.com/rancher/rancher/issues/4491

**Closed by deniseschannon** 2016-04-23 21:45 UTC
