### ISSUE TITLE
  Prepare rancher-gke-operator chart for 2.7.0

### ISSUE THREAD

**Issue by MKlimuszka** [rancher/rancher#38957] opened 2022-09-16 16:43 UTC
rancher-gke-operator chart needs to be updated the charts for 2.7 by

- File a PR removing the doNotRelease flag form the package.yaml; in this PR, you will also want to make any changes that need to be made to update the chart to the version you intend to release in 2.7. For example, for a charts like rancher-aks-operator / rancher-gke-operator / rancher-eks-operator, you will need to create a new branch in upstream for Rancher 2.7, cut the first release for that chart, and introduce those changes in to the package.yaml as well before removing the doNotRelease flag

- To make your chart available for 2.7, almost every chart will also have to modify the Rancher Version annotations that scope it to 2.6, i.e. https://github.com/rancher/charts/blob/2e058e93ee01f2980e4750148842dd7f04262b38/charts/fleet-agent/100.0.5%2Bup0.3.11/Chart.yaml#L8

- Once the PR is merged, ensure that the brand new chart is smoke tested by QA/dev

**Comment by sowmyav27** [comment] 2022-09-28 00:44
On 2.7-head,

- Deploy a GKE cluster
- Navigate to Local cluster's cluster explorer --> Apps --> Installed charts
- Verify GKE operator and CRD versions are
```
rancher-gke-operator:
- 101.0.0+up1.1.4
rancher-gke-operator-crd:
- 101.0.0+up1.1.4
```

**Comment by Josh-Diamond** [comment] 2022-10-04 19:09
Ticket #38957 - Test Results - ✅ 
---

With Docker on a single-node instance:

Verified on rancher `v2.7-eab28ddaeeb772894c35a7e86b0e37d3cb484b8c-head`:
1. Fresh install of rancher `v2.7-head`
2. Provision a downstream GKE hosted cluster w/ k8s `v1.22`
3. Provision a downstream GKE hosted cluster w/ k8s `v1.24`
4. Verified - Both clusters successfully provision
5. Verified - `rancher-gke-operator:101.0.0+up1.1.5-rc1` ; `rancher-gke-operator-crd:101.0.0+up1.1.5-rc1`

**Comment by Josh-Diamond** [comment] 2022-10-04 19:11
Awaiting confirmation that `101.0.0+up1.1.5-rc1` is expected for rancher-gke-operator and rancher-gke-operator-crd, and not `101.0.0+up1.1.4` before closing this out

**Closed** 2022-10-04 23:25 UTC
Labels: kind/enhancement, priority/0, [zube]: Reopened, team/area2, team/infracloud, area/charts

**Comment by vivek-infracloud** [comment] 2022-10-05 07:41
rancher-gke-operator and rancher-gke-operator-crd version is `101.0.0+up1.1.5-rc1`

![Screenshot from 2022-10-05 13-09-57](https://user-images.githubusercontent.com/83208989/194006706-e750902c-19c5-4ab1-b10a-daa7aa826feb.png)

**Comment by mitulshah-suse** [comment] 2022-10-05 08:42
The chart was bumped as part of https://github.com/rancher/charts/pull/2124
Issue: [rancher/rancher#37927](https://github.com/rancher/rancher/issues/37927)
Don't have further info on that issue. Needs to be confirmed with @KevinJoiner

**Comment by KevinJoiner** [comment] 2022-10-05 13:47
Yes, currently `101.0.0+up1.1.5-rc1` is the expected chart version for both `rancher-gke-operator` and `rancher-gke-operator-crd` for `release/v2.7`. Before the release of `v2.7`, the version will need to be updated to `101.0.0+up1.1.5`

This issue aims to verify that `rancher-gke-operator` charts are installable on `v2.7`. Not specifically what version is installed since the version may change if an issue is reopened and the RC needs to be bumped again.
