### ISSUE TITLE
Validate Deis Workflow on Kubernetes

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#5180] opened 2016-06-17 17:04 UTC
Validate Deis Workflow on Kubernetes

**Comment by galal-hussein** [comment] 2016-06-17 17:53
I installed Deis workflow from this [guide](https://deis.com/docs/workflow/installing-workflow/), and the installation resulted in creating several rcs and pods, one of them is failing with the following error:

deis-builder
```
6/17/2016 8:50:44 PM2016/06/17 17:50:44 Cleaner error listing namespaces (Get https://10.43.0.1:443/api/v1/namespaces: read tcp 172.17.0.8:57455->10.43.0.1:443: read: connection reset by peer)
6/17/2016 8:50:44 PM2016/06/17 17:50:44 Cleaner error listing namespaces (Get https://10.43.0.1:443/api/v1/namespaces: read tcp 172.17.0.8:57461->10.43.0.1:443: read: connection reset by peer)
6/17/2016 8:50:45 PM2016/06/17 17:50:45 Cleaner error listing namespaces (Get https://10.43.0.1:443/api/v1/namespaces: read tcp 172.17.0.8:57467->10.43.0.1:443: read: connection reset by peer)
6/17/2016 8:50:45 PM2016/06/17 17:50:45 Cleaner error listing namespaces (Get https://10.43.0.1:443/api/v1/namespaces: read tcp 172.17.0.8:57472->10.43.0.1:443: read: connection reset by peer)
6/17/2016 8:50:45 PM2016/06/17 17:50:45 Cleaner error listing namespaces (Get https://10.43.0.1:443/api/v1/namespaces: read tcp 172.17.0.8:57477->10.43.0.1:443: read: connection reset by peer)
6/17/2016 8:50:45 PM2016/06/17 17:50:45 Cleaner error listing namespaces (Get https://10.43.0.1:443/api/v1/namespaces: EOF)
6/17/2016 8:50:45 PM2016/06/17 17:50:45 Cleaner error listing namespaces (Get https://10.43.0.1:443/api/v1/namespaces: EOF)
6/17/2016 8:50:46 PM2016/06/17 17:50:46 Cleaner error listing namespaces (Get https://10.43.0.1:443/api/v1/namespaces: EOF)
6/17/2016 8:50:46 PM2016/06/17 17:50:46 Cleaner error listing namespaces (Get https://10.43.0.1:443/api/v1/namespaces: read tcp 172.17.0.8:57502->10.43.0.1:443: read: connection reset by peer)
6/17/2016 8:50:46 PM2016/06/17 17:50:46 Readinesscheck error listing namespaces (Get https://10.43.0.1:443/api/v1/namespaces: EOF)
```

**Comment by prachidamle** [comment] 2016-06-17 22:40
@galal-hussein I cannot reproduce this using the latest. 
deis pods all are running and in READY state for my k8s cluster:

Prachis-MacBook-Pro:.kube prachi$ kubectl --namespace=deis get pods
NAME                          READY     STATUS    RESTARTS   AGE
deis-builder-riozz            1/1       Running   6          9m
deis-controller-yp6yx         1/1       Running   5          9m
deis-database-5shkp           1/1       Running   4          9m
deis-logger-fluentd-lj0td     1/1       Running   0          9m
deis-logger-jyckk             1/1       Running   0          9m
deis-minio-44zg4              1/1       Running   0          9m
deis-monitor-grafana-g7zkc    1/1       Running   0          9m
deis-monitor-influxdb-7twpr   1/1       Running   0          9m
deis-monitor-stdout-02al7     1/1       Running   0          9m
deis-monitor-telegraf-ijp5q   1/1       Running   0          9m
deis-registry-unqtz           1/1       Running   5          9m
deis-router-k9pt6             1/1       Running   0          9m
deis-workflow-manager-a7wvk   1/1       Running   0          9m

Details about my setup:
1) I only had 1 host added to Rancher.
2) This was the k8s template my setup used to create the kubernetes stack: 
https://github.com/rancher/qa-catalog/tree/master/templates/kubernetes/1

My observation is, the pods keep on restarting for a while until they move to READY state.
As you said, deis-builder-riozz  pod took the longest(6 restarts) to be READY. But it did succeed in the end.

**Comment by prachidamle** [comment] 2016-06-17 22:42
@galal-hussein did you test deis on the same setup as heapster?

**Comment by galal-hussein** [comment] 2016-06-17 22:50
@prachidamle It was another setup, rancher version v1.1.0-dev5-rc3, i will test again and let you know.

**Comment by prachidamle** [comment] 2016-06-17 22:52
@galal-hussein can you ensure you are testing with latest k8s system templates:
2) This was the k8s template my setup used to create the kubernetes stack: ("v1.2.4-rancher6")
https://github.com/rancher/qa-catalog/tree/master/templates/kubernetes/1

**Comment by galal-hussein** [comment] 2016-06-17 23:26
@prachidamle I did, but now i am having another problem with the deis-router pod, the kubectl describe shows the following:

```
kubectl --namespace=deis describe pods deis-router-k3nih
Name:		deis-router-k3nih
Namespace:	deis
Node:		node1/46.101.243.55
Start Time:	Sat, 18 Jun 2016 01:16:30 +0200
Labels:		app=deis-router
Status:		Pending
IP:		
Controllers:	ReplicationController/deis-router
Containers:
  deis-router:
    Container ID:	
    Image:		quay.io/deis/router:v2.0.0
    Image ID:		
    Ports:		8080/TCP, 6443/TCP, 2222/TCP, 9090/TCP
    QoS Tier:
      memory:		BestEffort
      cpu:		BestEffort
    State:		Waiting
      Reason:		ContainerCreating
    Ready:		False
    Restart Count:	0
    Liveness:		http-get http://:9090/healthz delay=1s timeout=1s period=10s #success=1 #failure=3
    Readiness:		http-get http://:9090/healthz delay=1s timeout=1s period=10s #success=1 #failure=3
    Environment Variables:
      POD_NAMESPACE:	deis (v1:metadata.namespace)
Conditions:
  Type		Status
  Ready 	False 
Volumes:
  deis-router-token-yrh9t:
    Type:	Secret (a volume populated by a Secret)
    SecretName:	deis-router-token-yrh9t
Events:
  FirstSeen	LastSeen	Count	From			SubobjectPath	Type		Reason			Message
  ---------	--------	-----	----			-------------	--------	------			-------
  19s		19s		1	{default-scheduler }			Warning		FailedScheduling	pod (deis-router-k3nih) failed to fit in any node
fit failure on node (node1): PodFitsHostPorts

  18s	18s	1	{default-scheduler }		Normal	Scheduled	Successfully assigned deis-router-k3nih to node1
  17s	17s	1	{kubelet node1}			Warning	FailedSync	Error syncing pod, skipping: failed to "StartContainer" for "POD" with RunContainerError: "runContainer: API error (500): failed to create endpoint k8s_POD.7f676988_deis-router-k3nih_deis_85c450a4-34e1-11e6-860e-027ba3dc5851_266acbee on network bridge: Bind for 0.0.0.0:9090 failed: port is already allocated\n"

  4s	4s	1	{kubelet node1}		Warning	FailedSync	Error syncing pod, skipping: failed to "StartContainer" for "POD" with RunContainerError: "runContainer: API error (500): failed to create endpoint k8s_POD.7f676988_deis-router-k3nih_deis_85c450a4-34e1-11e6-860e-027ba3dc5851_b0660880 on network bridge: Bind for 0.0.0.0:9090 failed: port is already allocated\n"
```
I think the problem is that the following container is using the same port:
```
# docker ps | grep 9090
afcfce10aad5        rancher/agent-instance:v0.8.3          "/etc/init.d/agent-in"   About a minute ago   Up About a minute   0.0.0.0:80->80/tcp, 0.0.0.0:443->443/tcp, 0.0.0.0:2222->2222/tcp, 0.0.0.0:9090->9090/tcp   r-kubernetes-loadbalancers_lb-aad3e5bf434e211e6860e027ba3dc585_1
```

**Comment by alena1108** [comment] 2016-06-17 23:34
@galal-hussein just add one more host, or remove this LB (if it was created using ingress, remove the ingress)

**Comment by galal-hussein** [comment] 2016-06-18 00:09
I added a host but the deis-router and deis-logger-fluentd  were failing to start, after removing the host and the loadbalancer manually all pods were up and running:

```
$ kubectl --namespace=deis get pods
NAME                          READY     STATUS    RESTARTS   AGE
deis-builder-c10p2            1/1       Running   4          23m
deis-controller-p18eb         1/1       Running   0          3m
deis-database-b4xk8           1/1       Running   2          23m
deis-logger-fluentd-wbo48     1/1       Running   0          23m
deis-logger-n0gmi             1/1       Running   0          3m
deis-minio-9su0a              1/1       Running   0          23m
deis-monitor-grafana-dyn2j    1/1       Running   0          23m
deis-monitor-influxdb-ccyk8   1/1       Running   0          23m
deis-monitor-stdout-to5pm     1/1       Running   0          3m
deis-monitor-telegraf-81toz   1/1       Running   0          23m
deis-registry-dhaoe           1/1       Running   2          23m
deis-router-ohs4b             1/1       Running   0          3m
deis-workflow-manager-mt31i   1/1       Running   0          23m
```

**Comment by sangeethah** [comment] 2016-06-18 00:37
@prachidamle , seems like deis is not able to start successfully when there is more than 1 host in the setup.

**Comment by alena1108** [comment] 2016-06-18 05:05
@galal-hussein any logs on the start failure?

**Comment by prachidamle** [comment] 2016-06-22 17:57
Update:

I tried to start deis workflow on a kubernetes cluster having 2 hosts and I am able to see that the 
deis-builder pod fails to go to READY state and shows following error:

6/22/2016 10:21:11 AM2016/06/22 17:21:11 Cleaner error listing namespaces (Get https://10.43.0.1:443/api/v1/namespaces: EOF)


Looking at the deis/builder code (https://github.com/deis/builder/blob/master/pkg/cleaner/cleaner.go), it looks like the builder code is trying to contact the kubernetes api server to list the namespaces.

However it is using "https://10.43.0.1:443" to talk to kubernetes api server.

This looks like some gateway address, and it most likely resolves to the k8s api-server when both builder and api-server are running on same host. [since this works on a single host cluster]

But in my setup, kubernetes api-server and deis/builder containers are on different hosts and that is when the error is seen.

I will try to see where deis/builder gets this k8s api-server addess from - or if it can be fed the k8s api-server address (like kubelet)

**Comment by prachidamle** [comment] 2016-06-22 22:13
<img width="991" alt="screen shot 2016-06-22 at 3 12 47 pm" src="https://cloud.githubusercontent.com/assets/1470602/16285582/e04c8b64-388b-11e6-9008-225ee4d63299.png">

**Comment by prachidamle** [comment] 2016-06-23 00:15
@ibuildthecloud If I see the above pod in rancher api http://104.197.225.39:8080/v1/projects/1a5/containers/1i145

I see there is a bunch of "environment" variables set for this pod container:
"environment": {
"KUBERNETES_PORT_443_TCP": "tcp://10.43.0.1:443",
"KUBERNETES_SERVICE_PORT_HTTPS": "443",
"DEIS_MINIO_PORT_9000_TCP_ADDR": "10.43.84.34",
"DEIS_MONITOR_GRAFANA_PORT_80_TCP_ADDR": "10.43.125.213",
"KUBERNETES_SERVICE_PORT": "443",
....
"KUBERNETES_SERVICE_HOST": "10.43.0.1",
"GIT_LOCK_TIMEOUT": "10", }

Here I see the KUBERNETES_SERVICE_HOST (10.43.0.1) and KUBERNETES_SERVICE_PORT(443)
which this pod seems to use to communicate with kubernetes apiserver.

This seems wrong to me, since our  kubernetes apiserver is listening on 6443 for https

If I try to connect to via curl to https://kubernetes:6443/api/v1/namespaces it works

To me it seems like we need to set the above environment variables to right values when we deploy any k8s pod.

Do we set any of these environment variables?

**Comment by prachidamle** [comment] 2016-06-24 18:11
Update: 
@ibuildthecloud figured out that connecting to 10.43.0.1 address from pods running on different host(other than the host where kube-apiserver is running) does not work because the kube-apiserver's 10.42 address is not set to the kubernetes service

kubectl describe svc kubernetes
Name:                   kubernetes
Namespace:              default
Labels:                 component=apiserver,provider=kubernetes
Selector:               <none>
Type:                   ClusterIP
IP:                     10.43.0.1
Port:                   https   443/TCP
Endpoints:              172.17.0.6:6443
Session Affinity:       None
No events.

since 172.17.0.6 is accessible within the host, deis pods work with single host setup but fail to contact the apiserver if there are multiple hosts.

**Comment by prachidamle** [comment] 2016-06-24 18:14
Update:
I am able to assign the 10.42 address to the kube-apiserver using some fixes in  /entry.sh and now I see this:


> kubectl describe service kubernetes
Name:                   kubernetes
Namespace:              default
Labels:                 component=apiserver,provider=kubernetes
Selector:               <none>
Type:                   ClusterIP
IP:                     10.43.0.1
Port:                   https   443/TCP
Endpoints:              10.42.173.108:6443
Session Affinity:       None
No events.

However now connection to kube-apiserver is throwing 401 (unauthorized), possibly due to some servicetoken error

root@deis-builder-dkk2w:/# curl -v --cacert /var/run/secrets/kubernetes.io/serviceaccount/ca.crt -H "Authorization: Bearer $(cat /var/run/secrets/kubernetes.io/serviceaccount/token)" https://10.43.0.1:443/api/v1/namespaces
*   Trying 10.43.0.1...
* Connected to 10.43.0.1 (10.43.0.1) port 443 (#0)
* found 1 certificates in /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
* found 692 certificates in /etc/ssl/certs
* ALPN, offering http/1.1
* SSL connection using TLS1.2 / ECDHE_RSA_AES_128_GCM_SHA256
*        server certificate verification OK
*        server certificate status verification SKIPPED
*        common name: kubernetes (matched)
*        server certificate expiration date OK
*        server certificate activation date OK
*        certificate public key: RSA
*        certificate version: #3
*        subject: CN=kubernetes
*        start date: Fri, 24 Jun 2016 08:09:04 GMT
*        expire date: Mon, 22 Jun 2026 08:09:04 GMT
*        issuer: O=cattle
*        compression: NULL
* ALPN, server accepted to use http/1.1
> GET /api/v1/namespaces HTTP/1.1
> Host: 10.43.0.1
> User-Agent: curl/7.47.0
> Accept: */*
> Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJrdWJlcm5
ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2U
iOiJkZWlzIiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9zZWNyZXQubmFtZSI6ImRlaXMtYnV
pbGRlci10b2tlbi1wb2U0cyIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VydmljZS1hY2N
vdW50Lm5hbWUiOiJkZWlzLWJ1aWxkZXIiLCJrdWJlcm5ldGVzLmlvL3NlcnZpY2VhY2NvdW50L3NlcnZ
pY2UtYWNjb3VudC51aWQiOiIzMmYxNGZlYi0zOWU0LTExZTYtYTI3YS0wMmIwODc0YzE5Y2MiLCJzdWI
iOiJzeXN0ZW06c2VydmljZWFjY291bnQ6ZGVpczpkZWlzLWJ1aWxkZXIifQ.nUE4Kivjf5lPz77M2Ta1
vW-VEX-zkvFIerIsrsZbkvgSLSIczlrK4Avk1uFL9uuzdYfrJYtBQvDyZa_cBvxnzT8xp7aheOqarK-W
H_VMVjWdQ2hEsG19aMgRFWoTaBqj_WiweAwiKH_6B_4HUYIJji4HD16Sl0n7a7FstB-VGGVhRBWvEM_M
vIsxYfWz-UgldRwNQxID1dSnQ0bErG70dTB-8CxBh-tte3RLsErohAxi0FkYnLuZDu9ATMuXpD34JAv1
fHYjm9Id-GI7uHQcAl8eCry9sHlKainccOphBAa_dIyPwQnoZADOpUL87R5CpFqpBaH0Dp1Vhf1PB5WW
5A
>
< HTTP/1.1 401 Unauthorized
< Content-Type: text/plain; charset=utf-8
< Date: Fri, 24 Jun 2016 18:13:51 GMT
< Content-Length: 13
<
Unauthorized
* Connection #0 to host 10.43.0.1 left intact

**Comment by prachidamle** [comment] 2016-06-24 18:53
deis-builder pod shows error authenticating now
24/2016 11:52:45 AM2016/06/24 18:52:45 Cleaner error listing namespaces (the server has asked for the client to provide credentials (get namespaces))
6/24/2016 11:52:45 AM2016/06/24 18:52:45 Cleaner error listing namespaces (the server has asked for the client to provide credentials (get namespaces))
6/24/2016 11:52:45 AM2016/06/24 18:52:45 Cleaner error listing namespaces (the server has asked for the client to provide credentials (get namespaces))
6/24/2016 11:52:45 AM2016/06/24 18:52:45 Cleaner error listing namespaces (the server has asked for the client to provide credentials (get namespaces))
6/24/2016 11:52:45 AM2016/06/24 18:52:45 Cleaner error listing namespaces (the server has asked for the client to provide credentials (get namespaces))
6/24/2016 11:52:46 AM2016/06/24 18:52:46 Cleaner error listing namespaces (the server has asked for the client to provide credentials (get namespaces))
6/24/2016 11:52:46 AM2016/06/24 18:52:46 Cleaner error listing namespaces (the server has asked for the client to provide credentials (get namespaces))
6/24/2016 11:52:46 AM2016/06/24 18:52:46 Cleaner error listing namespaces (the server has asked for the client to provide credentials (get namespaces))
6/24/2016 11:52:46 AM2016/06/24 18:52:46 Cleaner error listing namespaces (the server has asked for the client to provide credentials (get namespaces))
6/24/2016 11:52:46 AM2016/06/24 18:52:46 Cleaner error listing namespaces (the server has asked for the client to provide credentials (get namespaces))
6/24/2016 11:52:47 AM2016/06/24 18:52:47 Cleaner error listing namespaces (the server has asked for the client to provide credentials (get namespaces))
6/24/2016 11:52:47 AM2016/06/24 18:52:47 Cleaner error listing namespaces (the server has asked for the client to provide credentials (get namespaces))
6/24/2016 11:52:47 AM2016/06/24 18:52:47 Cleaner error listing namespaces (the server has asked for the client to provide credentials (get namespaces))

**Comment by prachidamle** [comment] 2016-06-27 21:18
Update:

The above "Cleaner error listing namespaces (the server has asked for the client to provide credentials (get namespaces))" was due to invalid service tokens on the k8s cluster.

With a clean k8s cluster, this error is not seen and all deis pods are seen running and "READY"

However, validating the deis usecase (mentioned here https://deis.com/docs/workflow/quickstart/deploy-an-app/,) failed with :

Prachis-MacBook-Pro:.kube prachi$ deis pull deis/example-go -a linear-painting
Creating build... Error: 
400 Bad Request
detail: unable to ping registry endpoint https://10.43.203.76:80/v0/
v2 ping attempt failed with error: Get https://10.43.203.76:80/v2/: tls: oversized record received with length 20527
 v1 ping attempt failed with error: Get https://10.43.203.76:80/v1/_ping: tls: oversized record received with length 20527

**Comment by prachidamle** [comment] 2016-06-27 22:31
@galal-hussein can you validate the deis workflow by using the kubernetes templates from my catalog 

https://github.com/prachidamle/my-rancher-catalog


To validate the deis workflow:
1. Change the docker daemon start options on your hosts to use ""--insecure-registry=10.0.0.0/8""
Some useful links on how to change docker daemon options:
https://docs.docker.com/engine/admin/systemd/#http-proxy
https://docs.docker.com/engine/admin/configuring/

2. Verify that your docker hosts are running with ""--insecure-registry=10.0.0.0/8"" by doing this:
systemctl -l  status docker.service

3. Add my Catalog via UI:  library: https://github.com/prachidamle/my-rancher-catalog

4. Enable kubernetes on rancher UI

5. After k8s cluster is up, install deis worflow using helmc

6. Check that all deis pods are up and READY

7. After this, validate the deis workflow mentioned here https://deis.com/docs/workflow/quickstart/deploy-an-app/ . Change the first step to: deis register http://deis.104.197.211.144.nip.io/v2/

**Comment by prachidamle** [comment] 2016-06-27 22:39
Marking as "status/to-test" to test with my personal catalog

**Comment by galal-hussein** [comment] 2016-06-28 00:40
@prachidamle The test with your personal catalog failed to get all deis pods up and ready, the following pods failed:

- deis-builder
- deis-logger-fluentd
- deis-router

Logs:

deis-builder:
```
et namespaces))
6/28/2016 3:37:25 AM2016/06/28 00:37:25 Cleaner error listing namespaces (the server has asked for the client to provide credentials (get namespaces))
6/28/2016 3:37:25 AM2016/06/28 00:37:25 Cleaner error listing namespaces (the server has asked for the client to provide credentials (get namespaces))
6/28/2016 3:37:26 AM2016/06/28 00:37:26 Cleaner error listing namespaces (the server has asked for the client to provide credentials (get namespaces))
6/28/2016 3:37:26 AM2016/06/28 00:37:26 Cleaner error listing namespaces (the server has asked for the client to provide credentials (get namespaces))
6/28/2016 3:37:26 AM2016/06/28 00:37:26 Cleaner error listing namespaces (the server has asked for the client to provide credentials (get namespaces))
6/28/2016 3:37:26 AM2016/06/28 00:37:26 Readinesscheck error listing namespaces (the server has asked for the client to provide credentials (get namespaces))
6/28/2016 3:37:26 AM2016/06/28 00:37:26 Cleaner error listing namespaces (the server has asked for the client to provide credentials (get namespaces))
6/28/2016 3:37:27 AM2016/06/28 00:37:27 Cleaner error listing namespaces (the server has asked for the client to provide credentials (get namespaces))
6/28/2016 3:37:27 AM2016/06/28 00:37:27 Cleaner error listing namespaces (the server has asked for the client to provide credentials (get namespaces))
6/28/2016 3:37:27 AM2016/06/28 00:37:27 Cleaner error listing namespaces (the server has asked for the client to provide credentials (get namespaces))
6/28/2016 3:37:27 AM2016/06/28 00:37:27 Cleaner error listing namespaces (the server has asked for the client to provide credentials (get namespaces))
6/28/2016 3:37:27 AM2016/06/28 00:37:27 Cleaner error listing namespaces (the server has asked for the client to provide credentials (get namespaces))
6/28/2016 3:37:28 AM2016/06/28 00:37:28 Cleaner error listing namespaces (the server has asked for the client to provide credentials (get namespaces))
6/28/2016 3:37:28 AM2016/06/28 00:37:28 Cleaner error listing namespaces (the server has asked for the client to provide credentials (get namespaces))
6/28/2016 3:37:28 AM2016/06/28 00:37:28 Cleaner error listing namespaces (the server has asked for the client to provide credentials (get namespaces))
6/28/2016 3:37:28 AM2016/06/28 00:37:28 Cleaner error listing namespaces (the server has asked for the client to provide credentials (get namespaces))
6/28/2016 3:37:28 AM2016/06/28 00:37:28 Cleaner error listing namespaces (the server has asked for the client to provide credentials (get namespaces))
6/28/2016 3:37:29 AM2016/06/28 00:37:29 Cleaner error listing namespaces (the server has asked for the client to provide credentials (get namespaces))
6/28/2016 3:37:29 AM2016/06/28 00:37:29 Cleaner error listing namespaces (the server has asked for the client to provide credentials (get namespaces))
6/28/2016 3:37:29 AM2016/06/28 00:37:29 Cleaner error listing namespaces (the server has asked for the client to provide credentials (get namespaces))
6/28/2016 3:37:29 AM2016/06/28 00:37:29 Cleaner error listing namespaces (the server has asked for the client to provide credentials (get namespaces))
6/28/2016 3:37:29 AM2016/06/28 00:37:29 Cleaner error listing namespaces (the server has asked for the client to provide credentials (get namespaces))
6/28/2016 3:37:30 AM2016/06/28 00:37:30 Cleaner error listing namespaces (the server has asked for the client to provide credentials (get namespaces))
6/28/2016 3:37:30 AM2016/06/28 00:37:30 Cleaner error listing namespaces (the server has asked for the client to provide credentials (get namespaces))
6/28/2016 3:37:30 AM2016/06/28 00:37:30 Cleaner error listing namespaces (the server has asked for the client to provide credentials (get namespaces))
6/28/2016 3:37:30 AM2016/06/28 00:37:30 Cleaner error listing namespaces (the server has asked for the client to provide credentials (get namespaces))
6/28/2016 3:37:30 AM2016/06/28 00:37:30 Cleaner error listing namespaces (the server has asked for the client to provide credentials (get namespaces))
6/28/2016 3:37:31 AM2016/06/28 00:37:31 Cleaner error listing namespaces (the server has asked for the client to provide credentials (get namespaces))
6/28/2016 3:37:31 AM2016/06/28 00:37:31 Cleaner error listing namespaces (the server has asked for the client to provide credentials (get namespaces))
6/28/2016 3:37:31 AM2016/06/28 00:37:31 Cleaner error listing namespaces (the server has asked for the client to provide credentials (get namespaces))
6/28/2016 3:37:31 AM2016/06/28 00:37:31 Cleaner error listing namespaces (the server has asked for the client to provide credentials (get namespaces))
6/28/2016 3:37:31 AM2016/06/28 00:37:31 Cleaner error listing namespaces (the server has asked for the client to provide credentials (get namespaces))
6/28/2016 3:37:32 AM2016/06/28 00:37:32 Cleaner error listing namespaces (the server has asked for the client to provide credentials (get namespaces))
6/28/2016 3:37:32 AM2016/06/28 00:37:32 Cleaner error listing namespaces (the server has asked for the client to provide credentials (get namespaces))
```
deis-logger-fluentd
```
6/28/2016 3:35:48 AM/var/log/containers does not exist in the container.
6/28/2016 3:35:48 AMStarting fluentd with syslog configuration! -- 10.43.166.199:514
6/28/2016 3:35:48 AMStarting fluentd with syslog configuration! -- 10.43.233.104:514
6/28/2016 3:35:48 AMSleeping for 15 seconds so the logger component has time to come up
6/28/2016 3:36:04 AM2016-06-28 00:36:04 +0000 [info]: reading config file path="/opt/fluentd/conf/fluentd.conf"
6/28/2016 3:36:04 AM2016-06-28 00:36:04 +0000 [info]: starting fluentd-0.14.0.pre.1
6/28/2016 3:36:04 AM2016-06-28 00:36:04 +0000 [info]: gem 'fluent-mixin-config-placeholders' version '0.4.0'
6/28/2016 3:36:04 AM2016-06-28 00:36:04 +0000 [info]: gem 'fluent-mixin-plaintextformatter' version '0.2.6'
6/28/2016 3:36:04 AM2016-06-28 00:36:04 +0000 [info]: gem 'fluent-mixin-rewrite-tag-name' version '0.1.0'
6/28/2016 3:36:04 AM2016-06-28 00:36:04 +0000 [info]: gem 'fluent-plugin-docker_metadata_filter' version '0.1.3'
6/28/2016 3:36:04 AM2016-06-28 00:36:04 +0000 [info]: gem 'fluent-plugin-elasticsearch' version '1.5.0'
6/28/2016 3:36:04 AM2016-06-28 00:36:04 +0000 [info]: gem 'fluent-plugin-kubernetes_metadata_filter' version '0.22.0'
6/28/2016 3:36:04 AM2016-06-28 00:36:04 +0000 [info]: gem 'fluent-plugin-remote_syslog' version '0.3.2'
6/28/2016 3:36:04 AM2016-06-28 00:36:04 +0000 [info]: gem 'fluentd' version '0.14.0.pre.1'
6/28/2016 3:36:04 AM2016-06-28 00:36:04 +0000 [info]: gem 'fluentd' version '0.12.26'
6/28/2016 3:36:04 AM2016-06-28 00:36:04 +0000 [info]: adding filter pattern="kubernetes.**" type="kubernetes_metadata"
6/28/2016 3:36:04 AM2016-06-28 00:36:04 +0000 [error]: config error file="/opt/fluentd/conf/fluentd.conf" error="Invalid Kubernetes API v1 endpoint https://10.43.0.1:443: 401 Unauthorized"
6/28/2016 3:36:04 AM2016-06-28 00:36:04 +0000 [info]: process finished code=256
6/28/2016 3:36:04 AM2016-06-28 00:36:04 +0000 [warn]: process died within 1 second. exit.
```
deis-router
```
6/28/2016 3:35:07 AM2016/06/28 00:35:07 INFO: Starting nginx...
6/28/2016 3:35:07 AM2016/06/28 00:35:07 INFO: nginx started.
6/28/2016 3:35:07 AM2016/06/28 00:35:07 Error building model; not modifying certs or configuration: the server has asked for the client to provide credentials (get replicationControllers deis-router).
```

**Comment by galal-hussein** [comment] 2016-06-28 01:35
Update: 
After removing the environment and rebuilding it again, all pods ran and are in READY state, also i deployed a getting-started application on deis and it worked:

```
$ deis pull deis/example-go -a zydeco-gatepost
Creating build... done

$ curl http://zydeco-gatepost.46.101.100.143.nip.io
Powered by Deis

$ kubectl get rc,pods,services --namespace=zydeco-gatepost
NAME                           DESIRED         CURRENT       AGE
zydeco-gatepost-v2-cmd         1               1             4m
NAME                           READY           STATUS        RESTARTS   AGE
zydeco-gatepost-v2-cmd-updv7   1/1             Running       0          4m
NAME                           CLUSTER-IP      EXTERNAL-IP   PORT(S)    AGE
zydeco-gatepost                10.43.106.120   <none>        80/TCP     5m
```
@sangeethah @soumyalj  ^^

**Comment by galal-hussein** [comment] 2016-06-28 01:44
Catalog used:
https://github.com/prachidamle/my-rancher-catalog

Rancher version:
build-master:v0.20.0

Docker version:
1.11.2

**Closed by galal-hussein** 2016-06-28 01:44 UTC
Labels: kind/bug, status/resolved, status/to-test
