### ISSUE TITLE
After adding a global role as a new user default, editing the user in UI changes the GlobalRoleBinding from `user` to `user-base`

### ISSUE THREAD

**Issue by davidnuzik** [rancher/rancher#21749] opened 2019-07-24 19:39 UTC
Version: master-head (7/24/19)

**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
- Enable Auth (Azure AD in my case)
- Share a cluster template with a user ("testuser2" in our case), such as with "Owner" access type.
- Log in as the "testuser2" user so they are added to users list.
- Log in as admin, Go to "Roles" page, "Global" tab.
- Edit "Create Cluster Templates" role, Pick "Yes" for "New User Default"
- Delete the user "testuser2"
- Log in as "testuser2" (they are now re-added to the list and have the Create Cluster Temmplates role now).
- Log in as admin, Go to "Users" page, edit "testuser2"

**Result:**
The "user" role appears to be missing.
![image](https://user-images.githubusercontent.com/45179589/61823101-ee768d00-ae0f-11e9-935a-75e289691f7a.png)

This is confusing. The UI picked "Custom" and here claims our "testuser2" has only Login access (user-base) and "Create Cluster Templates". This is not true. View the user in the API. They are actually a standard user with the "user" role and now also have "Create Cluster Templates" role. UI seems to be showing they have less access than they actually do.

**Comment by westlywright** [comment] 2019-07-30 18:31
This is not a bug, at least not tied to cluster templates. When you create a user with `standard` access this is the same as the `login access` under custom. Create a standard user and view that users global roles in the API. They only have one role. So when you add this as the default the user gets the standard role + create cluster template which is exactly whats happening. The UI can only report roles the API sends. @sangeethah I think we should close this and open a different issue opening a discussion around the design of this section of the UI perhaps, but IMO it shouldn't be tied to cluster templates.

**Comment by deniseschannon** [comment] 2019-07-31 20:28
@davidnuzik can you try this same use case but use "Manage Catalogs" as an example? it's not part of the standard user.

**Comment by davidnuzik** [comment] 2019-07-31 21:25
@deniseschannon I performed the same steps, except chose to edit "Manage Catalogs"
![image](https://user-images.githubusercontent.com/45179589/62249218-be466580-b39e-11e9-9b75-74500cc27121.png)
When perform the steps and then finally log back in as admin to edit the user we see the same behavior. Thus this is a pre-existing issue:
![image](https://user-images.githubusercontent.com/45179589/62249329-fd74b680-b39e-11e9-8e7e-ab2f312d3564.png)

**Comment by deniseschannon** [comment] 2019-09-25 17:11
Re-reading this bug it seems like the issue is that when you delete the testuser, we aren't cleaning up the role bindings for the user. 

This seems like a back-end issue and going to assign it over to the backend.

**Comment by cjellick** [comment] 2019-09-25 19:44
agree, backend bug, but i also think the UI can't handle the case where  a user has the "standard" user role and any additional custom role. That is probably a bit of an edge case, may not need to fix, but I think that is the confusion that David is talking about.

**Comment by dramich** [comment] 2019-09-25 23:27
After speaking with @davidnuzik and testing I am confident the default role of User wasn't being dropped from the defaults so the roles being assigned to the users are correct. The issue is really a UI issue however the UI for this screen has been changed recently when running master. I think qa should take a look again and determine if it's really an issue still after the changes.

**Comment by bmdepesa** [comment] 2019-10-17 17:32
rancher/rancher:v2.3.1

As admin:
* Enable auth
* Allow site-access to a user
* In a separate browser, login as standard user so they are created
* As admin, view standard user's globalrolebindings
  * User has one GRB, `user`
* Edit global roles to make `Manage Catalogs` a new user default
* Delete user
* In the other window, logout and login as standard user again
* As admin, view user's globalrolebindings
  * User has 2 GRB, `user` and `catalogs-manage`
* Edit user
  * UI shows Custom, with roles: `Manage Catalogs`, `Login Access`
* Save the user
* View the user's GRB
  * User's GRB have changed to `user-base` and `catalogs-manage`

The UI is incorrectly changing the user's GRB to `user-base` after saving the user with 'Login Access'.

We verified that GRB are getting cleaned up upon user deletion.

**Comment by westlywright** [comment] 2019-10-22 23:11
Available in `latest-2.3`.

**Comment by bmdepesa** [comment] 2019-10-24 17:05
rancher/rancher:v2.3-head d23f064ad
UI: latest-2.3

* Local Auth
  * New user with Admin, Standard User, user-base has all 3 GRB, admin can still perform admin actions
  * New user with Admin has Admin GRB
  * New user with Standard user has User GRB
  * New user with User base has user-base GRB
  * New user with a role and custom roles shows all expected GRB
  * Removing custom roles removes associated GRB
  * Edit a user with some custom roles adds the associated GRB
* External auth
  * User with site access is created with User GRB
  * Editing a user's roles updates the associated GRB
  * Specifying a role as a new user default then editing the user after they are created shows Standard User and the custom roles
  * Editing a user's roles updates the GRB with the associated bindings

**Closed by bmdepesa** 2019-10-24 17:05 UTC
Labels: [zube]: To Test, kind/bug-qa, status/working, team/ui
