### ISSUE TITLE
Etcd logs are not being shipped over from RKE1 cluster to endpoint.

### ISSUE THREAD

**Issue by AmartC** [rancher/rancher#32112] opened 2021-04-13 23:21 UTC
When working with an RKE1 cluster using Rancher v2.5.7 and Kubernetes v1.20.5 with rancher-logging-3.8.201, I am able to receive general control plane logs but not etcd logs unless I take down a node (done on purpose as part of a use case being explored) and then a flurry of etcd log error messages are being received. However, the frequent health check log messages which can be observed by viewing the docker container etcd's logs are not observed.

**Comment by nickgerace** [comment] 2021-04-14 17:59
**Confirmed config with @AmartC:**

- Rancher v2.5.7
- Kubernetes v1.20.5
- Logging 3.8.201
- Ubuntu 20.04.x LTS
- Created in Ember UI via the "With RKE and new nodes in an infrastructure provider"

**Comment by nickgerace** [comment] 2021-04-14 18:42
Confirmed that etcd logs are coming in with the aforementioned configuration (https://github.com/rancher/rancher/issues/32112#issuecomment-819720701).

```
[nickgerace at rancherbook in ~/github.com/nickgerace] (0)
% kubectl logs -n cattle-logging-system  rancher-logging-rke-fluentbit-w8kt7  | grep etcd
[1] rke: [1618425646.055078067, {"log"=>"rke: [1618425644.744884652, {"filename":"/var/lib/rancher/rke/log/etcd_816ba31cd206e3093d8d61419d83717e72b7de7027a7099ba0879bc42222fd80.log","log":"{\"log\":\"2021-04-14 18:40:44.744590 I | etcdserver/api/etcdhttp: /health OK (status code 200)\\n\",\"stream\":\"stderr\",\"time\":\"2021-04-14T18:40:44.744734235Z\"}"}]"}]
[3] rke: [1618425661.055043743, {"log"=>"rke: [1618425659.740618153, {"filename":"/var/lib/rancher/rke/log/etcd_816ba31cd206e3093d8d61419d83717e72b7de7027a7099ba0879bc42222fd80.log","log":"{\"log\":\"2021-04-14 18:40:59.740198 I | etcdserver/api/etcdhttp: /health OK (status code 200)\\n\",\"stream\":\"stderr\",\"time\":\"2021-04-14T18:40:59.740523443Z\"}"}]"}]
```

Perhaps you might need to increase density or adjust your index for your output? @AmartC

**Comment by nickgerace** [comment] 2021-04-14 19:07
Closing since this was not reproducible, but will follow-up with @AmartC for their exact setup.

**Closed by nickgerace** 2021-04-14 19:07 UTC
Labels: [zube]: Working, kind/bug
