### ISSUE TITLE
Azure RKE new cluster fails to provision

### ISSUE THREAD

**Issue by erikwilson** [rancher/rancher#17402] opened 2019-01-11 18:18 UTC
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
Provision single node Azure RKE cluster

**Result:**
Errors like: `Can not find RKE state file: open /Users/erik/go/src/github.com/rancher/rancher/management-state/rke/rke-229209006/cluster.rkestate: no such file or directory`

**Rancher server logs:**
```
2019/01/11 11:01:12 [INFO] Copying certs to the remote machine...
2019/01/11 11:01:15 [INFO] stdout: Setting Docker configuration on the remote daemon...
2019/01/11 11:01:15 [INFO] Setting Docker configuration on the remote daemon...
2019/01/11 11:01:22 [INFO] stdout: Checking connection to Docker...
2019/01/11 11:01:22 [INFO] Checking connection to Docker...
2019/01/11 11:01:25 [INFO] stdout: Docker is up and running!
2019/01/11 11:01:25 [INFO] Docker is up and running!
2019/01/11 11:01:59 [INFO] Provisioning node erik-test1 done
2019/01/11 11:01:59 [INFO] Generating and uploading node config erik-test1
2019/01/11 11:01:59 [INFO] Provisioning cluster [c-vnnfz]
2019/01/11 11:01:59 [INFO] Creating cluster [c-vnnfz]
2019/01/11 11:02:00 [INFO] Handling backend connection request [c-vnnfz:m-pzcpx]
2019/01/11 11:02:04 [INFO] kontainerdriver rancherkubernetesengine listening on address 127.0.0.1:10940
2019/01/11 11:02:04 [INFO] cluster [c-vnnfz] provisioning: Initiating Kubernetes cluster
2019/01/11 11:02:04 [INFO] kontainerdriver rancherkubernetesengine stopped
2019/01/11 11:02:04 [ERROR] cluster [c-vnnfz] provisioning: Failed to validate cluster: Address for host (1) is not provided
2019/01/11 11:02:04 [ERROR] cluster [c-vnnfz] provisioning: Can not find RKE state file: open /Users/erik/go/src/github.com/rancher/rancher/management-state/rke/rke-229209006/cluster.rkestate: no such file or directory
2019/01/11 11:02:04 [ERROR] ClusterController c-vnnfz [cluster-provisioner-controller] failed with : Can not find RKE state file: open /Users/erik/go/src/github.com/rancher/rancher/management-state/rke/rke-229209006/cluster.rkestate: no such file or directory
2019/01/11 11:02:10 [INFO] error in remotedialer server [400]: read tcp [::1]:8080->[::1]:61967: i/o timeout
2019/01/11 11:02:34 [INFO] Provisioning cluster [c-vnnfz]
2019/01/11 11:02:34 [INFO] Creating cluster [c-vnnfz]
2019/01/11 11:02:39 [INFO] kontainerdriver rancherkubernetesengine listening on address 127.0.0.1:10677
2019/01/11 11:02:39 [ERROR] Cluster c-vnnfz previously failed to create
2019/01/11 11:02:39 [INFO] cluster [c-vnnfz] provisioning: Initiating Kubernetes cluster
2019/01/11 11:02:39 [INFO] kontainerdriver rancherkubernetesengine stopped
2019/01/11 11:02:39 [ERROR] cluster [c-vnnfz] provisioning: Failed to validate cluster: Address for host (1) is not provided
2019/01/11 11:02:39 [ERROR] cluster [c-vnnfz] provisioning: Can not find RKE state file: open /Users/erik/go/src/github.com/rancher/rancher/management-state/rke/rke-729246005/cluster.rkestate: no such file or directory
2019/01/11 11:02:39 [ERROR] ClusterController c-vnnfz [cluster-provisioner-controller] failed with : Can not find RKE state file: open /Users/erik/go/src/github.com/rancher/rancher/management-state/rke/rke-729246005/cluster.rkestate: no such file or directory
```

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI):
   `dev` (2dbf3b1f621c9b), UI v2.2.1
- Installation option (single install/HA):
   `single`

**Comment by galal-hussein** [comment] 2019-01-11 22:13
The problem is with docker machine, and it was fixed in our fork https://github.com/rancher/machine/commit/4246f11e2799b508f22de987a83fc0cfced992a1, tested the provisioning with this fork and it worked as expected

**Comment by bmdepesa** [comment] 2019-01-29 04:06
rancher/rancher:master 1/28
Machine | v0.15.0-rancher4-1

* Provisioned Azure cluster successfully
* Deployed catalog app
* Deployed workloads
* Ingress is functional

**Closed by bmdepesa** 2019-01-29 04:06 UTC
Labels: area/rke, kind/bug, status/resolved, status/to-test, team/ca, version/2.0
