### ISSUE TITLE
Monitoring - prometheus-auth dies after a few hours

### ISSUE THREAD

**Issue by BinchenQ** [rancher/rancher#18104] opened 2019-02-14 06:34 UTC
**What kind of request is this (question/bug/enhancement/feature request):**
bug

**Steps to reproduce (least amount of steps as possible):**
1. Enable Monitoring
2. After 1~2 hours, the Pod `cattle-prometheus/prometheus-cluster-monitoring` became red on UI

**Result:**
![image](https://user-images.githubusercontent.com/24807489/52767023-1513e900-3064-11e9-88c8-cd2141d8cec5.png)

Log of promethueus:
![image](https://user-images.githubusercontent.com/24807489/52768061-480bac00-3067-11e9-8444-3070cf2476a3.png)

Log of prometheus-agent:
![image](https://user-images.githubusercontent.com/24807489/52768076-52c64100-3067-11e9-80bc-de1c6d86788d.png)

**Other details that may be helpful:**
- VM: CentOS Linux release 7.6.1810 (Core)  2Cores8GB && 4Cores16GB
- Docker version 17.03.2-ce
- I set the default memory limit of prometheus to 1000 because of a OOMkill (one time)
- `kubectl describe pod prometheus-cluster-monitoring -n cattle-prometheus`:
```
[work@plink ~]$ kubectl -n cattle-prometheus describe pod/prometheus-cluster-monitoring-0
Name:               prometheus-cluster-monitoring-0
Namespace:          cattle-prometheus
Priority:           0
PriorityClassName:  <none>
Node:               node21/192.168.1.21
Start Time:         Thu, 14 Feb 2019 14:08:59 +0800
Labels:             app=prometheus
                    chart=prometheus-0.0.1
                    controller-revision-hash=prometheus-cluster-monitoring-5c5674949f
                    monitoring.coreos.com=true
                    prometheus=cluster-monitoring
                    release=cluster-monitoring
                    statefulset.kubernetes.io/pod-name=prometheus-cluster-monitoring-0
Annotations:        cattle.io/timestamp: 2019-02-14T06:02:34Z
                    cni.projectcalico.org/podIP: 10.42.1.16/32
                    field.cattle.io/ports:
                      [[{"containerPort":9090,"dnsName":"prometheus-cluster-monitoring-","name":"web","protocol":"TCP","sourcePort":0},{"containerPort":9190,"dn...
                    workload.cattle.io/state:
                      {"bm9kZTE1":"c-ltzt6:m-835374f3f90c","bm9kZTE2":"c-ltzt6:m-02ecdb45da19","bm9kZTIw":"c-ltzt6:m-de2958f2d346","bm9kZTIx":"c-ltzt6:m-2bd0a93...
Status:             Running
IP:                 10.42.1.16
Controlled By:      StatefulSet/prometheus-cluster-monitoring
Containers:
  prometheus:
    Container ID:  docker://3fd3fe0cffda5967323fee43ca86a96e6019db41b4758805fab0bb1fc2f1b260
    Image:         prom/prometheus:v2.5.0
    Image ID:      docker-pullable://prom/prometheus@sha256:60c989c93c8097ef7719c1b3b0f4dc54ea61b5e836c222258a5d9512fb3e6181
    Ports:         9090/TCP, 9190/TCP
    Host Ports:    0/TCP, 0/TCP
    Args:
      --web.console.templates=/etc/prometheus/consoles
      --web.console.libraries=/etc/prometheus/console_libraries
      --config.file=/etc/prometheus/config_out/prometheus.env.yaml
      --storage.tsdb.path=/prometheus
      --storage.tsdb.retention=360h
      --web.enable-lifecycle
      --storage.tsdb.no-lockfile
      --web.route-prefix=/
      --web.listen-address=127.0.0.1:9090
    State:          Running
      Started:      Thu, 14 Feb 2019 14:09:05 +0800
    Last State:     Terminated
      Reason:       Error
      Exit Code:    1
      Started:      Thu, 14 Feb 2019 14:09:01 +0800
      Finished:     Thu, 14 Feb 2019 14:09:02 +0800
    Ready:          True
    Restart Count:  1
    Limits:
      cpu:     1
      memory:  1000Mi
    Requests:
      cpu:        100m
      memory:     100Mi
    Environment:  <none>
    Mounts:
      /etc/prometheus/config_out from config-out (ro)
      /etc/prometheus/rules/prometheus-cluster-monitoring-rulefiles-0 from prometheus-cluster-monitoring-rulefiles-0 (rw)
      /etc/prometheus/secrets/exporter-etcd-cert from secret-exporter-etcd-cert (ro)
      /prometheus from prometheus-cluster-monitoring-db (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from cluster-monitoring-token-vvds7 (ro)
  prometheus-config-reloader:
    Container ID:  docker://0cfc548b3bf785496068215a014f073dd1c2468a20a5b94dbcde0b6296a1c513
    Image:         quay.io/coreos/prometheus-config-reloader:v0.26.0
    Image ID:      docker-pullable://quay.io/coreos/prometheus-config-reloader@sha256:1c4f36961c5296e5189d89ed8603791222ecfa9ed90d5dc910036ff3e3a462b8
    Ports:         9090/TCP, 9190/TCP
    Host Ports:    0/TCP, 0/TCP
    Command:
      /bin/prometheus-config-reloader
    Args:
      --log-format=logfmt
      --reload-url=http://localhost:9090/-/reload
      --config-file=/etc/prometheus/config/prometheus.yaml
      --config-envsubst-file=/etc/prometheus/config_out/prometheus.env.yaml
    State:          Running
      Started:      Thu, 14 Feb 2019 14:09:02 +0800
    Ready:          True
    Restart Count:  0
    Limits:
      cpu:     50m
      memory:  50Mi
    Requests:
      cpu:     50m
      memory:  50Mi
    Environment:
      POD_NAME:  prometheus-cluster-monitoring-0 (v1:metadata.name)
    Mounts:
      /etc/prometheus/config from config (rw)
      /etc/prometheus/config_out from config-out (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from cluster-monitoring-token-vvds7 (ro)
  prometheus-agent:
    Container ID:  docker://d6238d5a3c20bd572b3a17804bbaf17be37bacea81932b7dca4454fa3843bf1b
    Image:         rancher/prometheus-auth:v0.2.0
    Image ID:      docker-pullable://rancher/prometheus-auth@sha256:8f715bf8eb4ea41c6598ccd244da51743d14f5a5c7cb93091fdced531cf48dbe
    Ports:         9090/TCP, 9190/TCP
    Host Ports:    0/TCP, 0/TCP
    Command:
      prometheus-auth
    Args:
      --log.debug
      --proxy-url
      http://localhost:9090
      --listen-address
      $(POD_IP):9090
      --filter-reader-labels
      prometheus
      --filter-reader-labels
      prometheus_replica
    State:          Waiting
      Reason:       CrashLoopBackOff
    Last State:     Terminated
      Reason:       Error
      Exit Code:    2
      Started:      Thu, 14 Feb 2019 14:30:09 +0800
      Finished:     Thu, 14 Feb 2019 14:30:38 +0800
    Ready:          False
    Restart Count:  11
    Limits:
      cpu:     500m
      memory:  500Mi
    Requests:
      cpu:      100m
      memory:   100Mi
    Liveness:   http-get http://:web/-/healthy delay=0s timeout=3s period=5s #success=1 #failure=6
    Readiness:  http-get http://:web/-/ready delay=0s timeout=3s period=5s #success=1 #failure=120
    Environment:
      POD_IP:   (v1:status.podIP)
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from cluster-monitoring-token-vvds7 (ro)
  rules-configmap-reloader:
    Container ID:  docker://60b1a47f953f5922a1416bb10907f6485ff9b8b3e22d732eb5aa7bdc7a047925
    Image:         quay.io/coreos/configmap-reload:v0.0.1
    Image ID:      docker-pullable://quay.io/coreos/configmap-reload@sha256:e2fd60ff0ae4500a75b80ebaa30e0e7deba9ad107833e8ca53f0047c42c5a057
    Port:          <none>
    Host Port:     <none>
    Args:
      --webhook-url=http://localhost:9090/-/reload
      --volume-dir=/etc/prometheus/rules/prometheus-cluster-monitoring-rulefiles-0
    State:          Running
      Started:      Thu, 14 Feb 2019 14:09:04 +0800
    Ready:          True
    Restart Count:  0
    Limits:
      cpu:     25m
      memory:  10Mi
    Requests:
      cpu:        25m
      memory:     10Mi
    Environment:  <none>
    Mounts:
      /etc/prometheus/rules/prometheus-cluster-monitoring-rulefiles-0 from prometheus-cluster-monitoring-rulefiles-0 (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from cluster-monitoring-token-vvds7 (ro)
Conditions:
  Type              Status
  Initialized       True 
  Ready             False 
  ContainersReady   False 
  PodScheduled      True 
Volumes:
  config:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  prometheus-cluster-monitoring
    Optional:    false
  config-out:
    Type:    EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:  
  prometheus-cluster-monitoring-rulefiles-0:
    Type:      ConfigMap (a volume populated by a ConfigMap)
    Name:      prometheus-cluster-monitoring-rulefiles-0
    Optional:  false
  secret-exporter-etcd-cert:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  exporter-etcd-cert
    Optional:    false
  prometheus-cluster-monitoring-db:
    Type:    EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:  
  cluster-monitoring-token-vvds7:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  cluster-monitoring-token-vvds7
    Optional:    false
QoS Class:       Burstable
Node-Selectors:  beta.kubernetes.io/os=linux
Tolerations:     node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
Events:
  Type     Reason     Age                   From             Message
  ----     ------     ----                  ----             -------
  Normal   Pulled     21m                   kubelet, node21  Container image "quay.io/coreos/prometheus-config-reloader:v0.26.0" already present on machine
  Normal   Pulled     21m                   kubelet, node21  Container image "rancher/prometheus-auth:v0.2.0" already present on machine
  Normal   Created    21m                   kubelet, node21  Created container
  Normal   Started    21m                   kubelet, node21  Started container
  Normal   Created    21m                   kubelet, node21  Created container
  Normal   Created    21m                   kubelet, node21  Created container
  Normal   Pulled     21m                   kubelet, node21  Container image "quay.io/coreos/configmap-reload:v0.0.1" already present on machine
  Normal   Started    21m                   kubelet, node21  Started container
  Normal   Started    21m                   kubelet, node21  Started container
  Normal   Pulled     21m (x2 over 21m)     kubelet, node21  Container image "prom/prometheus:v2.5.0" already present on machine
  Normal   Started    21m (x2 over 21m)     kubelet, node21  Started container
  Normal   Created    21m (x2 over 21m)     kubelet, node21  Created container
  Warning  Unhealthy  20m (x5 over 21m)     kubelet, node21  Liveness probe failed: Get http://10.42.1.16:9090/-/healthy: net/http: request canceled (Client.Timeout exceeded while awaiting headers)
  Warning  Unhealthy  6m21s (x50 over 21m)  kubelet, node21  Readiness probe failed: Get http://10.42.1.16:9090/-/ready: net/http: request canceled (Client.Timeout exceeded while awaiting headers)
  Warning  BackOff    75s (x73 over 18m)    kubelet, node21  Back-off restarting failed container
```

**Environment information**
- Rancher version (`rancher/rancher:master): rancher/rancher:master
- Installation option (single install): single

**Cluster information**
- Cluster type (Custom): Custom
- Machine type (VM) and specifications (CPU/memory): 2Cores8GB 4Cores16GB
- Kubernetes version (use `kubectl version`):v1.13.1

**Comment by thxCode** [comment] 2019-02-18 08:17
@BinchenQ , I have set up a similar environment in AWS:
```
$ cat /etc/centos-release
CentOS Linux release 7.6.1810 (Core)

$ cat /etc/centos-release-upstream
Derived from Red Hat Enterprise Linux 7.6 (Source)

$ uname -r
3.10.0-957.1.3.el7.x86_64

$ sudo docker version
Client:
 Version:      17.03.2-ce
 API version:  1.27
 Go version:   go1.7.5
 Git commit:   f5ec1e2
 Built:        Tue Jun 27 02:21:36 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.03.2-ce
 API version:  1.27 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   f5ec1e2
 Built:        Tue Jun 27 02:21:36 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

FYI, my testing Docker intallation script: 
```
$ sudo yum update -y

$ sudo yum remove docker \
          docker-client \
          docker-client-latest \
          docker-common \
          docker-latest \
          docker-latest-logrotate \
          docker-logrotate \
          docker-engine
$ sudo yum install -y yum-utils \
  device-mapper-persistent-data \
  lvm2

$ sudo yum-config-manager \
    --add-repo \
    https://download.docker.com/linux/centos/docker-ce.repo

# https://github.com/moby/moby/issues/33930#issuecomment-312782998
$ sudo yum install -y --setopt=obsoletes=0 \
  docker-ce-17.03.2.ce-1.el7.centos \
  docker-ce-selinux-17.03.2.ce-1.el7.centos \
  docker-ce-cli-17.03.2.ce-1.el7.centos

$ sudo yum install -y containerd.io

$ sudo systemctl start docker
```

After about 6 hours and I still cannot reproduce what your facing, can you try the latest `rancher/rancher:master` again?

**Comment by BinchenQ** [comment] 2019-02-18 08:55
@thxCode OK,I will try again with the latest version.

**Comment by thxCode** [comment] 2019-02-18 10:07
I have did some cross-validations, but I am not an expert in this area.:

| `cat /etc/centos-release` | `uname -r` | `sudo docker version` | can cluster-level Monitoring work now? |
| --- | --- | --- | --- |
| CentOS Linux release 7.6.1810 (Core) | 3.10.0-957.1.3.el7.x86_64 | 17.03.2-ce | yes |
| CentOS Linux release 7.6.1810 (Core) | 3.10.0-957.1.3.el7.x86_64 | 18.06.0-ce | no |
| CentOS Linux release 7.6.1810 (Core) | 3.10.0-957.5.1.el7.x86_64 | 17.03.2-ce | no |
| CentOS Linux release 7.6.1810 (Core) | 3.10.0-957.5.1.el7.x86_64 | 18.06.0-ce | no |

@BinchenQ what is the `uname -r` of your `CentOS 7.6` worker node? At the same time, if you really want CentOS, can you follow [the requirements of rancher](https://rancher.com/docs/rancher/v2.x/en/installation/requirements/) to try `CentOS 7.5` with `Docker 17.03.2`?

**Comment by BinchenQ** [comment] 2019-02-18 10:30
@thxCode 
My node was created from a official CentOS vagrant box months ago :

**CentOS Linux release 7.6.1810 (Core)** 
uname -r : **3.10.0-862.2.3.el7.x86_64**

Docker version:
Client:
 Version:      17.03.2-ce
 API version:  1.27
 Go version:   go1.7.5
 Git commit:   f5ec1e2
 Built:        Tue Jun 27 02:21:36 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.03.2-ce
 API version:  1.27 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   f5ec1e2
 Built:        Tue Jun 27 02:21:36 2017
 OS/Arch:      linux/amd64
 Experimental: false

I had seen the requirements of rancher and I thought it would be ok higher than the CentOS 7.5 version.Isn't it ?

**Comment by thxCode** [comment] 2019-02-18 15:07
@BinchenQ  I am not sure higher host OS version will be more stable.

**Comment by thxCode** [comment] 2019-02-19 07:20
@BinchenQ, hey, I create https://github.com/rancher/system-charts/pull/16 to increase the `periodSeconds` & `timeoutSeconds` for `readiness` & `liveness` of Prometheus in cluster-level Monitoring. I have tested with the followed env, it is fine.

```
[centos@ip-172-31-10-131 ~]$ cat /etc/centos-release
CentOS Linux release 7.6.1810 (Core)
[centos@ip-172-31-10-131 ~]$ uname -r
3.10.0-957.5.1.el7.x86_64
[centos@ip-172-31-10-131 ~]$ sudo docker version
Client:
 Version:           18.09.2
 API version:       1.39
 Go version:        go1.10.6
 Git commit:        6247962
 Built:             Sun Feb 10 04:13:27 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.2
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.6
  Git commit:       6247962
  Built:            Sun Feb 10 03:47:25 2019
  OS/Arch:          linux/amd64
  Experimental:     false
```

I think you can try again after it merged.

**Comment by BinchenQ** [comment] 2019-02-19 07:25
@thxCode 
I am very grateful for what you have done.I will try again as soon as possible.

**Closed** 2019-02-20 15:38 UTC
Labels: area/monitoring, kind/bug, status/ready-for-review, status/resolved, team/cn, version/2.0
