### ISSUE TITLE
[BUG] Windows machine on vSphere fails to reconnect after graceful restart via vmware tools

### ISSUE THREAD

**Issue by jakefhyde** [rancher/rancher#39658] opened 2022-11-21 17:08 UTC
**Rancher Server Setup**
- Rancher version: v2.6.9

**Information about the Cluster**
- Kubernetes version: v1.24.4+rke2r1
- Cluster Type (Local/Downstream): Downstream
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider): Vsphere

**Describe the bug**

After a graceful restart of the windows node, the node fails to reconnect and shows the following error:
```
2022/11/16 12:58:46 [INFO] [planner] rkecluster fleet-default/windows: waiting: failing worker machine(s) windows-pool-012345678-abcde: error applying plan -- check rancher-system-agent.service logs on node for more information
```
Using OS restart-computer works fine, the issue only occurs if the machine is restarted via vmware tool (power > Restart Guest OS)
The machine version on the cluster is `rancher/machine:v0.15.0-rancher96`.

**To Reproduce**

- Create RKE2 Cluster and Linux controllers
- Deploy windows node
- Restart the windows node gracefully from vCentre (right-click the virtual machine and select Power > Restart Guest OS.)

**Result**

Windows machine on vSphere fails to reconnect after a graceful restart.

**Expected Result**

Customer should be able to do a graceful restart for windows nodes.

**Additional context**

SURE-5667

**Comment by snasovich** [comment] 2023-03-31 14:30
Since the fix is in `system-agent-installer-rke2` I believe it will be delivered in newer RKE2 releases. The goal is to have it in April 2023 patches, so changing the milestone accordingly.
@Oats87 @brandond , please correct if I'm wrong.

**Comment by snasovich** [comment] 2023-04-17 18:49
This one can be moved "To Test" once we have https://github.com/rancher/rancher/issues/41065 merged.

**Comment by markusewalker** [comment] 2023-04-26 15:30
**QA TEST PLAN**

**Scenarios**
|Scenario|Test Case|
|---|---|
|1|As a standard user, provision a downstream node driver RKE2 cluster with a Windows worker, restart the Windows worker from vSphere and validate that it restarts successfully|
|2|As a standard user, provision a downstream custom RKE2 cluster with a Windows worker, restart the Windows worker from vSphere 3 times and validate that it restarts successfully|

**Comment by markusewalker** [comment] 2023-04-26 16:09
Reproduced this issue on `v2.7.1`. See details below:

**ENVIRONMENT DETAILS**
- Rancher install: Docker
- Rancher version: `v2.7.1`
- Browser: Chrome

**TEST RESULT**
|Scenario|Test Case|Result
|---|---|---|
|1|As a standard user, provision a downstream node driver RKE2 cluster with a Windows worker node, restart the Windows worker from vSphere and validate that it restarts successfully|:x:|

**VALIDATION STEPS**

**Scenario 1**
1. As a standard user, provisioned a downstream node driver RKE2 `v1.24.11+rke2r1` cluster (1 etcd, 1 cp, 1 Linux worker, 1 Windows worker).
     - Validated that the nodes and cluster came up as `Active` in Cluster Management and Cluster Explorer.
     - Validated that all pods in the System project page are up and `Active.
2. Within vSphere infrastructure, right-clicked the Windows worker node > Power > Restart Guest OS.
3. Validated that the Windows worker node gracefully restarted in vSphere.
4. Windows worker node never goes back to a state of `Active` in Rancher:
![image](https://user-images.githubusercontent.com/52591819/234635501-91981a2a-1280-4ae9-81ef-37c9ede4f31d.png)
5. As shown in the above screenshot, the docker logs show the following message:
```
2023/04/26 16:03:50 [INFO] [planner] rkecluster fleet-default/mew-tu1: waiting: failing worker machine(s) mew-tu1-mew-windows-76c88f8444-w5wb6: error applying plan -- check rancher-system-agent.service logs on node for more information
```

I will attempt to test on the latest `v2.7-head` to see if I can validate that this issue has been fixed.

**Comment by markusewalker** [comment] 2023-04-26 17:29
Validated this against `v2.7-head` https://github.com/rancher/rancher/commit/cb834b79f2d32ae4c9eb9b9f3c745005c7c537c4. See details below:

**ENVIRONMENT DETAILS**
- Rancher install: Docker
- Rancher version: `v2.7-head` https://github.com/rancher/rancher/commit/cb834b79f2d32ae4c9eb9b9f3c745005c7c537c4
- Browser: Chrome

**TEST RESULT**
|Scenario|Test Case|Result
|---|---|---|
|1|As a standard user, provision a downstream node driver RKE2 cluster with a Windows worker node, restart the Windows worker from vSphere and validate that it restarts successfully|:white_check_mark:|
|2|As a standard user, provision a downstream node driver RKE2 cluster with two Windows worker nodes, restart the Windows worker from vSphere 3 times and validate that it restarts successfully|:white_check_mark:|

**VALIDATION STEPS**

**Scenario 1**
1. As a standard user, provisioned a downstream node driver RKE2 `v1.25.7+rke2r1` cluster (1 etcd, 1 cp, 1 Linux worker, 1 Windows worker).
     - Validated that the nodes and cluster came up as `Active` in Cluster Management and Cluster Explorer.
     - Validated that all pods in the System project page are up and `Active.
2. Within vSphere infrastructure, right-clicked the Windows worker node > Power > Restart Guest OS.
3. Validated that the Windows worker node gracefully restarted in vSphere and in Rancher.
4. Verified that there are no unforeseen error messages when checking the Rancher logs.
__________
**Scenario 2**
1. Repeated scenario 1, but used a downstream custom RKE2 `v1.24.11+rke2r1` cluster (1 etcd/cp, 1 Linux worker, 2 Windows workers) instead.
     - This scenario yielded the same successful work.
2. Restarted each Windows worker nodes two additional times; validated both gracefully restarted in vSphere and Rancher.

**Closed by markusewalker** 2023-04-26 17:29 UTC
Labels: kind/bug, internal, [zube]: QA Working, QA/M, area/provisioning-v2, area/provisioning-rke2, team/area2, JIRA
