### ISSUE TITLE
update fluentd binaries

### ISSUE THREAD

**Issue by aemneina** [rancher/rancher#20509] opened 2019-05-28 21:05 UTC
There's an incompatibility between the version of fluent we ship and newer versions where logging can slow down or crash because of the time resolution incompatibility.

Snippet from the fluentd release notes:Sub-second time

In Fluentd v0.12 or earlier, time was represented as seconds from Epoch. Events generated in a second had same time. Currently, Fluentd v0.14 generates time in nanosecond resolution. 3rd party plugins which uses Fluent::Engine.now also generates these new time objects without any updates in v0.14.

This new time object behaves as Integer for compatibility with v0.12. If you want to get sub-second data from these time, update your plugins to call time.nsec to get sub-second values (and write it to anywhere you want).

This feature is implemented only on Fluentd v0.14, and Fluentd v0.12 will crash if it receives binary data including nanosecond resolution time forwarded from Fluentd v0.14. So users should be sure to specify time_as_integer true in configuration for forward output plugin if you want to transfer data from Fluentd v0.14 to Fluent v0.12 (It is true in default at v0.14.0, but will be turned into false in default at any point of future).

**Comment by aiwantaozi** [comment] 2019-05-31 02:06
Hi, we haven't use v0.12, the first version we use is v0.14, and now we use Fluentd 1.3.3. From the description above, it's hard to reproduce,  could you provide more info like rancher server version, target info, seems like the target selected is Fluentd?

**Comment by deniseschannon** [comment] 2019-06-11 23:24
@aiwantaozi can you provide which Rancher versions have which fluentd versions?

**Comment by aemneina** [comment] 2019-06-11 23:27
Hi @aiwantaozi in the deployment we had an issue where there was a lot of logging and after some time logging stopped collecting. To resolve this we had to add time_as_integer in the fluentd logs config. Looking at the release notes for fluentd 14, that setting shouldnt have needed to be set? Not sure why that resolved the issue, I was under the impression an older version of fluentd was in use.

**Comment by aiwantaozi** [comment] 2019-06-12 02:30
Rancher version and fluentd version:
rancher version > 2.2.0, fluentd version is 1.3.3
2.0.8 < rancher version < 2.2.0, fluentd version is 1.1.3
rancher version < 2.0.8, fluentd version 0.14.

@aemneina In 2.2 you can use advanced mode to add the extra configure ```time_as_integer```. Try to reproduce in rancher 2.2.2 and deliver logs to Elasticsearch 6.x, but could not reproduce, could you provide produce step and related rancher version and logging target(Elasticsearch or Fluentd) version?

**Comment by deniseschannon** [comment] 2019-07-19 20:26
@loganhz @aiwantaozi let's update the latest fluentd within rancher 2.3 so all bugs that are fixed in fluentd are addressed in rancher.

**Comment by bmdepesa** [comment] 2019-08-20 21:19
rancher/rancher:master-head ad1679532

* Reproduced the original logging error by forwarding to fluentd 0.12.1
  * Received an error that the log statements could not be parsed
* Manually edited config to add `time_as_integer true`
* Logs were then able to retrieve

* Fluentd is now version `1.6.3`

**Closed by bmdepesa** 2019-08-20 21:19 UTC
Labels: [zube]: To Test, area/logging, internal, kind/enhancement, team/cn
