### ISSUE TITLE
Support for taint option in UI and rancher agent

### ISSUE THREAD

**Issue by dnoland1** [rancher/rancher#20473] opened 2019-05-26 05:37 UTC
**What kind of request is this (question/bug/enhancement/feature request):**
Feature request

**Description:**
When creating a custom cluster in the UI, allow the option to specify taints. When calling the rancher agent, allow a `--taint` option similar to the `--label` option. Using this option when place a taint on the Kubernetes node.

Related to this feature request to support taints in RKE: https://github.com/rancher/rke/issues/157

Upon implementation, docs at https://rancher.com/docs/rancher/v2.x/en/cluster-provisioning/custom-clusters/agent-options/ should be updated with new taint option.

**Comment by wzrdtales** [comment] 2019-05-28 12:16
Also need this!

# Use case

We have a machine learning cluster and spawn dynamically gpu nodes. The problem is, that processes are being scheduled onto these nodes that are not intended to run there. So we would like to use the ExtendedResourceTolerance Admission control, to get this behavior under control. However, without a possibility to add a taint to the node while adding it, we can't automate it properly.

@superseb Is there may be already something available to accomplish this?

**Comment by dnoland1** [comment] 2019-05-29 19:56
Possibly a duplicate of https://github.com/rancher/rancher/issues/13972

**Comment by ankur111** [comment] 2019-06-25 22:04
closed as duplicate of [#13972](https://github.com/rancher/rancher/issues/13972)

**Closed by ankur111** 2019-06-25 22:04 UTC
