### ISSUE TITLE
Cluster with RKE driver always have error in "transitioning" field while provisioning (master, v2.0.8)

### ISSUE THREAD

**Issue by ukinau** [rancher/rancher#15907] opened 2018-10-02 17:43 UTC
**Rancher versions:**
rancher/rancher: master 
rancher/rancher-agent: master

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
OpenStack + RKE

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
single node rancher

**Steps to Reproduce:**
Create cluster with RKE driver and Check "transitioning" value in cluster. You will see error in "transitioning" field always until provisioning finished.

1. Create Cluster with RKE (I used OpenStack)
2. Check Cluster Object by calling API  e.g: https://\<domain\>/v3/clusters/\<cluster name\>
3. you will see error in "transitioning" filed
```
{
 .....
"state": "provisioning",
"transitioning": "error",
"transitioningMessage": "waiting for etcd and controlplane nodes to be registered",
"type": "cluster",
"uuid": "866d6a6c-c665-11e8-aa0c-fa163ef5fb05"
}
```

When you create cluster with later rancher image than d9ac02168f2ed362cecc8947d5166218acad2fd5
 commit (like v2.0.8), your cluster always have "error" transitioning as a initial value as long as driver is RKE.

Starting with Error State always is very weird and bring some confusion to operator.
So we should not report error state  when expected provisioning is proceeding 

**Reason**
There are several reason to cause this problem. Let me describe one by one.
1. From d9ac02168f2ed362cecc8947d5166218acad2fd5 commit, judging error state logic has been changed to check if condition.reason is Error or not as well as condition value.
2. ClusterConditionProvisioned.Reason set always Error when provisioning is proceeding because cluster-provisioner will return controller.ForgetError if cluster wait for other installing procedure like https://github.com/rancher/rancher/blob/master/pkg/controllers/management/clusterprovisioner/provisioner.go#L486-L488
```
	if !etcd || !controlplane {
		return nil, &controller.ForgetError{
			Err: fmt.Errorf("waiting for etcd and controlplane nodes to be registered"),
		}
	}
```
3. Norman Condition set Error to ClusterConditionProvisioned.Reason when handler return error even if error is controller.ForgetError. 
https://github.com/rancher/rancher/blob/master/vendor/github.com/rancher/norman/condition/condition.go#L163-L168
https://github.com/rancher/rancher/blob/master/vendor/github.com/rancher/norman/condition/condition.go#L86-L96

Above 3 reasons cause the situation that always cluster provisioning start with error state and stick state to error until provisioning finished.

** Propose **
- usually controller.ForgetError is used when handler is failed but can be recognized as safe to ignore. so this is not really error. So maybe it's better if this controller.ForgetError struct can have Reason field in the same way as conditionError did in norman/condition
- Put other reason than Error to controller.ForgetError.Reason if the error is happened because of expected provisioning process like "waiting for etcd and controlplane nodes to be registered"

**Comment by cjellick** [comment] 2018-12-18 13:09
All related PRs are merged, so this is hypothetically fixed

**Comment by soumyalj** [comment] 2018-12-19 23:33
Reproduced the issue and tested in master from Dec 19th build
1. Created a cluster using DO nodes (driver machine). 
In provisioning state, the transitioning field is not in error as below:
<img width="733" alt="screen shot 2018-12-19 at 3 25 01 pm" src="https://user-images.githubusercontent.com/18536626/50254276-53fa2b00-03a2-11e9-8bfe-2bf0579bc1eb.png">

```
"state": "provisioning",
"transitioning": "yes",
"transitioningMessage": "[healthcheck] Start Healthcheck on service [kube-apiserver] on host [a.b.c.d]",
"type": "cluster",
```
@cjellick : In the pending state we still see `transitioning:error`, shouldn't we be able to remove this error too ?
```
"state": "pending",
"transitioning": "error",
"transitioningMessage": "waiting for full cluster configuration",
"type": "cluster",

```

**Comment by ukinau** [comment] 2018-12-20 18:57
@soumyalj 
Could you show me all roles of the node?
Usually pending is happened because of configuration miss like lacking of etcd node, lacking of controller node.

If you saw pending state just few sec after created cluster, it's kind of timing problem to continue until node for this cluster got created.

If you are testing with the rancher deployment which manages x hundreds cluster, nodes, pending state time will be longer than usual because NodeController, ClusterController will be busy.

**Comment by soumyalj** [comment] 2018-12-20 19:04
@ukinau : This happens with any number of nodes in a cluster . There is no role missing as the UI will not let you proceed if any of them is missing. 
Ex:
1.  One node with all roles 
2. Two nodes N1 : etcd, control ; N2: worker
3. 3 nodes with all roles in each of them

**Comment by cjellick** [comment] 2019-01-14 13:10
this and the related but 17201 are confusing me. We now have a bunch of bugs related to cluster state"
#17201 
#17282
#17281
#16884

I don't know if they're related/caused by this bug or something different

**Comment by ukinau** [comment] 2019-01-17 01:32
In my opinion, we should close this issue and then we should try to resolve other tickets one by one, otherwise this ticket will never be closed because another cluster state related problem can always be came up anytime.

**Comment by cjellick** [comment] 2019-01-30 23:56
related https://github.com/rancher/rancher/issues/17281 https://github.com/rancher/rancher/issues/17201

@ukinau I'll have a dev look at this in relation to the other issues. We will keep this open for now, but just until we investigate/fix the others

**Comment by soumyalj** [comment] 2019-02-12 23:59
Tested with master build from Feb 12. Created clusters with DO template.
The following clusters were created:
a. One node with all roles
b. Two nodes N1 : etcd, control ; N2: worker
c. 3 nodes with all roles in each of them

During provisioning, the transitioning field does not show "error".
API snippet below:

```
"state": "provisioning",
"transitioning": "yes",
"transitioningMessage": "waiting for etcd and controlplane nodes to be registered",
"type": "cluster",
"uuid": "e83c33b5-2f11-11e9-9e3d-0242ac8989"
```
Also, cluster does not go to pending state right after provisioning.  Cluster goes to "Provisioning" state as expected.

**Closed by soumyalj** 2019-02-12 23:59 UTC
Labels: kind/bug, priority/1, status/ready-for-review, status/resolved, status/to-test, status/working, team/az, version/2.0
