### ISSUE TITLE
[forwardport] Allow user to specify that a node will never be healthy in the UI

### ISSUE THREAD

**Issue by alena1108** [rancher/rancher#23983] opened 2019-11-08 00:13 UTC
Forwardport https://github.com/rancher/rancher/issues/23394

**Comment by izaac** [comment] 2019-11-26 22:37
@alena1108 I see [this issue](https://github.com/rancher/rancher/issues/23394#issuecomment-552602152) in rancher `2.4 master-head (11/26/2019)` 781cd0fdc

We might've missed to forward port that fix to master? https://github.com/rancher/rancher/issues/23394 as I see that was fixed back in `2.3-head` and originally reported by @sangeethah

**Comment by izaac** [comment] 2019-11-27 18:52
Scenarios related to `v3/settings/ignore-node-name`  worked fine.

### I've reopened the issue due to this use case failing:

- Create a bipIp node from kubectl.
- Wait for it to get synced to rancher and get to "Unavailable" state.
- Using kubectl , add label - cattle.rancher.io/node-status: ignore. ( Did this step from kubectl , since the label change done from rancher UI did not take effect)
- Label gets synced to v3/nodes.
- Delete the node from rancher server using api ip. ( Attempted from api ui since UI does not have delete option)
- Node gets deleted from rancher side as well as from kubectl.

### Expected Behavior:

- Node gets deleted from rancher side .
- But node continues to be part of the cluster and can be listed from kubectl.

**Comment by alena1108** [comment] 2019-12-03 00:51
@izaac master branch has this commit 

`Skip v1.node removal for objects with specific nodename`

https://github.com/rancher/rancher/commit/9930781c8f2be0228ab273752ad090c1f55a9d65

I'll retest to see what's going on

**Comment by alena1108** [comment] 2019-12-03 01:16
@izaac the removal scenario works for exact name match, and broken for labels scenario only. The issue exists in both master and 2.3 though, as it looks like originally it was validated on 2.3 for the name match only https://github.com/rancher/rancher/issues/23394#issuecomment-554151930

**Comment by izaac** [comment] 2019-12-03 21:35
@alena1108 

This is working now in Rancher version `2.4 master-head (03/12/2019)` 41ffb6907

`cattle.rancher.io/node-status: ignore`
Ignore label is honored when deleting the node from the UI, I still see the node with kubectl.

The only thing I've noticed is related to `v3/settings/ignore-node-name`:

According to @sangeethah in this [acceptance criteria comment](https://github.com/rancher/rancher/issues/23394#issuecomment-552036024) I see the previously ignore-node-name node re-appearing in the UI after I set the settings value of `v3/settings/ignore-node-name` to a new one.

But the expectation is for it not to appear according to the criteria:

> 6. Set v3/settings/ignore-node-name to "node1". This will NOT result in "node1" (added in step4) to get removed from UI. This should NOT result in "deletenode" ( added in step3) to show up in UI . It continues to be hidden.

So do we expect the previously nodes not showing in the UI due to ignore node name to re-appear? If that's the case I can close this issue as completed for 2.4.  I guess it makes sense to them to re-appear as the value is changed but I'm not completely sure.

**Comment by alena1108** [comment] 2019-12-03 21:37
@izaac 

> According to @sangeethah in this acceptance criteria comment I see the previously ignore-node-name node re-appearing in the UI after I set the settings value of v3/settings/ignore-node-name to a new one.

This is expected. Only newly set setting name will be respected during the validation. We have to change the test plan

**Comment by izaac** [comment] 2019-12-03 21:39
@alena1108 thanks for confirming that. I'll close this as completed.

**Closed by izaac** 2019-12-03 21:39 UTC
Labels: [zube]: To Test, kind/enhancement, team/ca

**Comment by izaac** [comment] 2019-12-03 21:43
Behavior for `v3/settings/ignore-node-name` would be that after setting a new value the previously ignored nodes in the UI will re-appear. And existing nodes matching the new ignore node name value will disappear from the UI after certain time.
