### ISSUE TITLE
xip.io ingress does not work on GKE

### ISSUE THREAD

**Issue by sheng-liang** [rancher/rancher#13340] opened 2018-05-08 02:34 UTC
**Rancher versions:** 2.0.0

**Steps to Reproduce:**
1. Create a GKE cluster
2. Create a workload
3. Expose NodePort
4. Create xip.io Ingress
5. Wait until Rancher generates xip.io URL

**Results:**
The generated xip.io URL does not work. It requires us to update the host in Ingress rules. GKE does not seem to work in that case.

**Solution:**
On GKE we can use the Ingress public IP address directly in the URL. Each Ingress has a unique public IP.

**Comment by tfiduccia** [comment] 2018-05-08 20:14
Duplicate of #13223

**Closed by tfiduccia** 2018-05-08 20:14 UTC
