### ISSUE TITLE
[BUG]  Enabling ACE after cluster creation results in ACE endpoints access not working

### ISSUE THREAD

**Issue by anupama2501** [rancher/rancher#42255] opened 2023-07-28 16:58 UTC
**Rancher Server Setup**
- Rancher version: `v2.7-head` `368e171` / `v2.7.5`
- Installation option (Docker install/Helm Chart): `Docker install`

**Information about the Cluster**
- Kubernetes version: `v1.26.4+k3s1`
- Cluster Type (Local/Downstream): Downstream Infrastructure provider RKE1/RKE2, k8s `v1.26.6+rke2r1`/`v1.26.6+k3s1`

**User Information**
- What is the role of the user logged in? (Admin/Cluster Owner/Cluster Member/Project Owner/Project Member/Custom)
  - If custom, define the set of permissions: Admin/Standard user - Cluster Owner
   
**Describe the bug**
After the cluster is created, if we edit the cluster and enable ACE endpoint from networking tab, access the ace endpoints from kubeconfig throws an `error: You must be logged in to the server (Unauthorized)`. 

**To Reproduce**
1. Create a rancher server on v2.7-head
2. Create 2 downstream clusters, either RKE2/k3s.
3. Edit the cluster and enable ACE endpoints
4. From the cluster explorer, click on the copy kubeconfig to dashboard/Download kubeconfig file.
5. Verify tokens from the downstream cluster's kubectl for clusterauthtokens and run `k get clusterauthtokens -A` , we get a resource not found error.
6. Set the kubeconfig context to ACE name, 

**Result**
Run a `kubectl get nodes` returns a `error: You must be logged in to the server (Unauthorized)`
**Expected Result**
Expected to be able to ACE endpoints.

**Additional Info:**
From the downstream cluster, if we try to get clusterauthtokens, we get a resource not found and if we try to get crds, the clusterauthtokens crd is not listed.

Workaround:
Restart rancher server and notice the downstream cluster has crd for clusterauthtoken generated and if we try to acess the ACE endpoints, the endpoints work.
It also works fine on an upgrade from v2.7.5 to v2.7-head as the rancher server is restarted, the crds are regenerated.

**Comment by Sahota1225** [comment] 2023-07-28 17:33
closing this issue as its duplicate of #41832

**Closed by Sahota1225** 2023-07-28 17:33 UTC
Labels: kind/bug, kind/bug-qa, team/area2
