### ISSUE TITLE
Cannot assign non-RKE1 Clusters to a Fleet Workspace

### ISSUE THREAD

**Issue by richard-cox** [rancher/rancher#36132] opened 2022-01-13 11:09 UTC
**Rancher Server Setup**
- Rancher version: 2-6-cd3c9d7
- Installation option (Docker install/Helm Chart): _docker_

**User Information**
- Admin
   
**Describe the bug**
Changes to the property `fleetWorkspaceName` of a `v3/cluster` are immediately reverted

**To Reproduce**
Via the Dashboard
- Import a cluster (i used a local k3d)
- Navigate to `Continuous Delivery`
- Create a new Workspace in `Advanced / Workspaces`
- Go to `Clusters`, click on the three dot menu for the downstream cluster and use the `Assign To` action to change the workspace to the new cluster
- Change the workspace selector in the header to the new workspace 

Via the API UI
- Follow above to setup up to and including creating a workspace
- Open `<rancher url)/v3/clusters/<cluster id>` in a browser
- Edit the cluster and set `fleetWorkspaceName` to the new workspace id (note - this will be the same as the _name_)

**Result**
Via the Dashboard
- The `Clusters` list is empty

Via the API UI
- The response to the edit contains the correct value
- Nav to `<rancher url)/v3/clusters/<cluster id>` and `fleetWorkspaceName` is not set to the new one

**Expected Result**
In the Dashboard
- The `Clusters` list shows the cluster

Via the API UI
- The `fleetWorkspaceName` value is retained

**Additional context**
- This feature passed QA in 2.6.3 after a UI bug was fixed - https://github.com/rancher/dashboard/issues/4799.
- During that time they noted some patchyness. On a docker install i see this all the time.
- There's a discussion in our private slack that covers the above, contact me for details
  - In the thread @prachidamle confirmed that the property looked like it was the right one to set

Update - Assigning RKE1 clusters to a Fleet Workspace works fine

SURE-4522

**Comment by TReZ42** [comment] 2022-01-14 10:15
Hi,

I have the same issue with clusters created on a Harvester cluster using Harvester Node Driver, either K3S or RKE2.

Assigning a non-default Fleet Workspace to the clusters does not apply, either through the UI or editing directly the `fleetWorspaceName` spec.

I'm interested joining your thread on slack.

Ben.

**Comment by Jono-SUSE-Rancher** [comment] 2022-02-24 17:32
@MKlimuszka can you have your team take a look at possibly fixing this for v2.6.4? If it seems impossible, sync up with me and we can discuss with @gaktive as they are backend blocked on this issue for a related dashboard issue.

**Comment by richard-cox** [comment] 2022-03-08 14:23
After discussing with @aalves08 , @aiyengar2 and @thedadams we've come to the following conclusion
- The root error is due to a sync issue caused by editing `fleetWorkspaceName` on the child `v3/cluster` and the parent `v1/mangement.cattle.io.clusters` clearing it.
- The UI cannot update `fleetWorkspaceName` in `v1/mangement.cattle.io.clusters`. Presumably for the same reasons updating labels was switch from editing v1 mgmt cluster to v3 cluster (it's worth noting the label changes are retained and not reset like `fleetWorkspaceName`).

Donnie has stated this would require a lot of effort to fix in the backend.

There isn't anything we can do in the frontend if we can't edit either norman resource.

I've reproduced the error again on both docker and helm flavours of Rancher. It's not possible to assign a cluster to a workspace in either mean the workspace feature is pretty broken.

**Comment by richard-cox** [comment] 2022-03-09 09:25
Possibly related https://github.com/rancher/rancher/issues/31883

**Comment by Shavindra** [comment] 2022-03-09 09:54
This is with the rancher version 2.6.2 - I couldn't replicate it.

https://user-images.githubusercontent.com/1387263/157416892-00d8fa5a-4b90-4ba3-8918-eadcb9b9d438.mov

This is with rancher version `v2.6-head` / `f2a4147`  - Couldn't replicate it.

https://user-images.githubusercontent.com/1387263/157416581-1389085e-8d45-47a7-87b1-504626bb65ec.mov

However, I also noticed that if the cluster/node has a pending state (E.g. 1/3 is provisioned, 2/3 is being provisioned) I can't assign the cluster. No warning is given.

I also noticed intermittently. I had to right click and refresh the page for cluster list page to update. This is not reproducible consistently.

**Comment by richard-cox** [comment] 2022-03-09 11:28
Working with @Shavindra I think we've got to the bottom of the discrepancy. This bug only affects RKE1 clusters, not RKE2. I'll update the title & description

**Comment by Tejeev** [comment] 2022-04-09 00:24
Do we have a SURE for this?

**Comment by richard-cox** [comment] 2022-04-12 14:30
@Tejeev Not at the moment, but I don't know if any customers are using RKE2. Once they are I'd expect one to be raised

**Comment by richard-cox** [comment] 2022-04-21 15:24
@Tejeev SURE-4522

**Comment by sjdrc** [comment] 2022-04-27 04:31
I'm also having this issue with imported k3s clusters

**Comment by prachidamle** [comment] 2022-05-10 22:59
Here is a summary of my understanding after following the earlier discussions on this topic:

It has been discussed to be a known complex-to-solve problem of provisioning v2 introduced in 2.6.0 and affects all imported cluster types including rke2. This does not affect rke1 or KEV2 clusters.

Gist of the problem:
- For imported clusters, first the v1 cluster object (provisioning.cattle.io.cluster) is created by provisioningv2 under a namespace (fleet-default by default if not specified)
- It is not possible to move this v1.cluster object between namespaces without deleting the cluster and recreating it newly,
- The fleet-workspace of a fleet cluster is tied tightly to this namespace where the "parent "provisioning.cattle.io.cluster object is created. So even if a user tries to change the fleet workspace name for a fleet cluster from UI, the provisioningv2 controllers revert it back the namespace where the actual v1 cluster object was created.
-The solution to this issue is not with UI or fleet but a fix to the provisioningv2's logic of handling clusters and namespaces. - - One possible solution is decoupling the cluster's namespace and the fleet workspace by assigning a separate field on v1.cluster object to indicate the fleet workspace.
- But this needs to be verified that having the actual cluster namespace different than the fleet workspace value will work w.r.t the system service accounts/secrets deployed in the downstream cluster. cc @thedadams 

 This cannot be handled by UI or fleet teams, since it is a problem for provisioning v2 controller logic around `provisioning.cattle.io.cluster`.

**Comment by snasovich** [comment] 2022-05-25 21:06
@aiyengar2 to summarize the solution we've discussed.
Meanwhile, this is moved out of the 2.6.6 milestone at least for now.

**Comment by aiyengar2** [comment] 2022-05-26 19:35
The root cause of this issue has to do with the current model that we use for creating and managing provisioningv2 resources: 
- rancher/wrangler's `apply` framework allows us to do a one-way deployment of creating or updating a set of "child" resources on re-enqueuing a "parent" resource; on re-enqueue, it effectively uses the k8s dynamic client to grab all objects with a particular set of annotations, compare it against the desired, and choose to create, update, or delete the objects depending on whether the resource is tracked in desired only, desired + existing, or existing only, respectively
- `relatedresource.Watch` allows us to watch the set of "child" resources and re-enqueue the "parent" resource on a change. This ensures that changes to the children are overridden by the controller by re-applying the desired state

In the case of a provisioned RKE1 cluster, the "parent" resource is the v3 cluster object, so changes to the v3 cluster are accepted. You would not, however, be able to modify the v1 cluster or fleet cluster object out-of-band due to this since those are "child" resources.

Similarly, for clusters imported via the dashboard UI + RKE2 provisioned clusters, the "parent" resource is the v1 cluster object; this is why modifications to the v3 cluster object (the "child" resource) are instantly wiped out.

In order to fix this, provisioning v2 needs to have a better system of allowing certain values in "child" resources to be modifiable, where only desired **defaults** are set, but are not overridden on an apply. This requires us to modify the wrangler  `apply` resource to support this type of use case, since currently you can only specify the desired set that you exactly want the "child" resources to have; there's no way to set the desired default only on a create, but not try to keep it up-to-date on modifications.

To support this type of use case, wrangler currently has the ability to define [patchers](https://github.com/rancher/wrangler/blob/3ecd23dfea3bb4c76cbe8e06fb158eed6ae3dd31/pkg/apply/apply.go#L23) per GVK (type of resource) that the apply is operating on; these patchers can look at the requested patch that the framework is trying to apply during an update and choose to "sanitize" these patches to remove certain changes deemed unnecessary to be performed on an apply, as we do by default in [`sanitizePatch`](https://github.com/rancher/wrangler/blob/3ecd23dfea3bb4c76cbe8e06fb158eed6ae3dd31/pkg/apply/desiredset_compare.go#L117-L170), which is part of the default patcher used on all GVKs in this framework.

However, defining a patcher today is fairly difficult and requires copy/pasting code since any custom patcher would also anyways need to sanitize the stuff that the default patcher does and support removing changes from [various different types of patches](https://github.com/rancher/wrangler/blob/3ecd23dfea3bb4c76cbe8e06fb158eed6ae3dd31/pkg/apply/desiredset_compare.go#L443-L447); therefore, the proposed solution we came up with was to introduce some sort of additional design in wrangler that makes it easier to define / build custom patchers that will sanitize the defaults that our default patcher already does and also allow us to do things like sanitize certain JSONPaths. An example of what such a design would look like (possibly using the [builder pattern](https://golangbyexample.com/builder-pattern-golang/) like we do in desiredSets in wrangler apply or RBAC stuff in rancher/rancher) is as follows:

```go
v3ClusterPatcher := apply.NewPatcherBuilder().IgnoreJSONPath('spec.fleetWorkspaceName').Patcher()
```

If using something like the builder pattern, some things to consider would be how we choose to define patchers on paths that point to list entries (do we wipe out the whole list? or how do we identify what needs to be changed and what can be kept) and whether we can allow certain currently ignored fields (such as `status`) to be specified to be overridden.

**Comment by kkaempf** [comment] 2022-12-16 15:49
Removing `area/fleet` and `team/fleet` as per

> This cannot be handled by UI or fleet teams, since it is a problem for provisioning v2 controller logic around provisioning.cattle.io.cluster.

**Comment by lazzio7** [comment] 2023-01-20 11:09
hi,

just adding very similar issue : 

rancher : 2.6.9
cluster:  3x v1.24.4+rke2r1
fleet contains only one local cluster

i created new workspace, and just wan to assign local cluster from fleet-local workspace to the new workspace
after: 
-> no cluster visible in fleet-local  workspace
-> no cluster visible in new workspace

no cluster visible in rancher at all.

**Comment by BJWRD** [comment] 2023-02-02 12:44
Hello,

Just adding to this Issue that this appears to affect Minikube Clusters as well.

Version: 2.7
Cluster: Minikube, v1.28.0

Synopsis:
-> Minikube cluster imported
-> New workspace created
-> Imported Minikube cluster can be located in the fleet-default workspace
-> When attempting to move the cluster to the newly created workspace nothing happens
-> No other option than to continue using the Cluster in the default fleet-default workspace

**Comment by Notumlo** [comment] 2023-03-31 13:48
Hello,

Also hitting this issue constantly.

Rancher version: 2.7.1 (but also encountered it in previous 2.6.X versions)
Clusters: Multiple k3s klusters on 1.24 (but also encountered it in previous k3s versions)

Reproduce steps:

* Have a Rancher instance on k3s.
* Bootstrap a fresh k3s cluster, for ex k3s via Rancher Desktop
* Import cluster into Rancher with all default values, wait for it to join and become active.
* Attempt to move it from workspace **fleet-default** to a custom one, nothing happens.

**Comment by manno** [comment] 2023-04-20 11:57
Related:
* https://github.com/rancher/dashboard/issues/7745#issuecomment-1488887520
* https://github.com/rancher/dashboard/issues/7734

**Comment by richard-cox** [comment] 2023-10-02 17:00
@slickwarren we're waiting on confirmation the feature flag exists before merging the dashboard issue. we couldn't see it in `-head` and are waiting confirmation from @snasovich / @Oats87

**Comment by snasovich** [comment] 2023-10-02 21:36
@richard-cox , I see it added [here](https://github.com/rancher/rancher/pull/42955/files#diff-2f6213e2bd15bb256be4ed430e664c08612e86384445be797a20d5f56d48d101R116-R121) and it should be in `v2.8-head` as well as `v2.8.0-alpha2` builds.
Could you please clarify where are you expecting to see it?

**Comment by slickwarren** [comment] 2023-10-05 23:45
blocked from validating p0 use cases by https://github.com/rancher/rancher/issues/43080

**Comment by slickwarren** [comment] 2023-10-18 18:05
tested on 2.8-head (2e6895d): 
(enable the new flag `provisioningv2-fleet-workspace-back-population` to enable this experimental feature)
create a workspace in fleet
add a gitRepo to the new workspace
add a gitRepo to the fleet-default workspace
in each of the following, observe that the fleet-default gitRepo resources are removed, and the new workspace's gitRepo resources are added

* transfer node driver rke1 cluster (should not be affected, existing behavior) -- pass
* transfer node driver rke2 cluster to new workspace -- pass
* transfer node driver k3s cluster to new workspace -- pass
* transfer custom rke2 cluster to new workspace -- pass
* transfer custom k3s cluster to new workspace -- pass

transfer all clusters back to original workspace - observe that the fleet-default gitRepo resources are added, and the new workspace's gitRepo resources are removed -- pass

disable the flag with rke2/k3s clusters added to non-fleet-default workspace -- **All rke2/k3s clusters are removed from non fleet-default workspaces** this doesn't sound ideal but since this is an experimental feature with no definition of what should happen if this is disabled, I will consult with the team if this behavior is acceptable for an initial release. 

this was tested on both rke1 non-hardened local cluster and rke2 hardened local cluster.

**Comment by kkaempf** [comment] 2023-10-19 07:55
closing as QA validated

**Closed by kkaempf** 2023-10-19 07:55 UTC
Labels: status/need-design-review, [zube]: QA Working, QA/S, area/provisioning-v2, team/area2, JIRA, status/ui-blocked

**Comment by dsmithbauer** [comment] 2024-03-05 13:32
I'm now no longer seeing the option to "Change workspace" in Continuous Delivery in Rancher MCM v2.8.2 for imported RKE2 clusters. This cluster was imported directly to the fleet-default Workspace. On prior versions I saw the option, but it always failed when trying to change the Workspace after import. Was this an unintended side effect of this change?
![image](https://github.com/rancher/rancher/assets/32399829/a0cb1ad3-c35c-4209-a7ce-0b8a916a8873)

**Comment by richard-cox** [comment] 2024-03-05 14:09
@dsmithbauer have you enabled the `provisioningv2-fleet-workspace-back-population` feature flag?

**Comment by mmartin24** [comment] 2024-03-05 14:52
@dsmithbauer , it seems you need to enable the flag that @richard-cox mentioned.

Here you can enable the flag: 
![image](https://github.com/rancher/rancher/assets/37271841/8f715bdf-8f71-439f-86c5-20b041dae79d)

Once that flag is enabled, you should be able to see it:
![image](https://github.com/rancher/rancher/assets/37271841/18f13df7-3315-47e2-82a7-41c5d133cae4)

**Comment by dsmithbauer** [comment] 2024-03-05 15:21
Thank you @mmartin24! Page had not refreshed until after I posted my comment. But I appreciate your response too!

**Comment by jhoblitt** [comment] 2024-03-15 18:24
Unlike what is suggested by the ticket title, I have cluster which are provisioned with rke[1] and then imported into rancher which have this exact same problem.  Kudos to @mmartin24 for detailing the fix.

Why isn't this feature flag enabled by default?
