### ISSUE TITLE
Can't create node template for openstack

### ISSUE THREAD

**Issue by RAalders** [rancher/rancher#13499] opened 2018-05-15 10:02 UTC
**Rancher versions:**
rancher/server or rancher/rancher: v2.0.0

**Infrastructure Stack versions:**
healthcheck:
ipsec:
network-services:
scheduler:
kubernetes (if applicable):

**Docker version: (`docker version`,`docker info` preferred)**
17.03.2-ce

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
NAME="RancherOS"
VERSION=v1.3.0
ID=rancheros
ID_LIKE=
VERSION_ID=v1.3.0
PRETTY_NAME="RancherOS v1.3.0"
HOME_URL="http://rancher.com/rancher-os/"
SUPPORT_URL="https://forums.rancher.com/c/rancher-os"
BUG_REPORT_URL="https://github.com/rancher/os/issues"
BUILD_ID=
4.9.80-rancher

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
Openstack

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
Both single node rancher and HA rancher

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**

**Steps to Reproduce:**
* Setup rancher
* Enable the openstack node driver
* Make a new openstack node template
* console log spews out "Uncaught TypeError: Cannot read property 'set' of null"
* re-open and all fields are empty

**Results:**
When making a node template fields are not saved making it impossible to spin up a openstack cluster.

full stacktrace:
```
component.js:53 Uncaught TypeError: Cannot read property 'set' of null
    at component.js:53
    at e.invoke (backburner.js:291)
    at e.flush (backburner.js:159)
    at e.flush (backburner.js:361)
    at e.end (backburner.js:471)
    at e.run (backburner.js:560)
    at e.join (backburner.js:567)
    at Function.Te.join (ember-metal.js:3918)
    at has_element.js:18
    at e.flaggedInstrument (ember-metal.js:3367)
```

**Comment by superseb** [comment] 2018-05-15 10:33
Duplicate of https://github.com/rancher/rancher/issues/13254

**Closed by superseb** 2018-05-15 10:33 UTC
