### ISSUE TITLE
Programmatically assign namespace to Rancher project

### ISSUE THREAD

**Issue by fmunteanu** [rancher/rancher#22708] opened 2019-09-08 08:11 UTC
Running Rancher HA 2.2.8, I would like to programmatically assign with `kubectl` a new namespace to a specific Rancher project. Is the `projectname System` available as annotation or do I have to reply on `field.cattle.io/projectid`?

```
kubectl annotate namespace mynamespace field.cattle.io/projectname=System
```

**Comment by superseb** [comment] 2019-09-08 16:26
This is a duplicate of https://github.com/rancher/rancher/issues/21222

**Closed by superseb** 2019-09-08 16:26 UTC
