### ISSUE TITLE
Monitoring - uninstall the monitoring v2 app causes cattle-cluster-agent restarts 

### ISSUE THREAD

**Issue by jiaqiluo** [rancher/rancher#29176] opened 2020-09-25 22:16 UTC
**What kind of request is this (question/bug/enhancement/feature request):**
bug
master-head e9a98a3

**Steps to reproduce (least amount of steps as possible):**
- as admin, install monitoring v2 in a downstream cluster 
- as admin, uninstall the monitoring app 

**Result:**

- the dashboard is reloaded and not accessible 
<img width="523" alt="Screen Shot 2020-09-25 at 3 13 03 PM" src="https://user-images.githubusercontent.com/6218999/94320449-d2093f80-ff41-11ea-916e-6ed03c9ffb32.png">

- the cluster goes to the unavailable state 
<img width="1425" alt="Screen Shot 2020-09-25 at 3 04 01 PM" src="https://user-images.githubusercontent.com/6218999/94320469-e2211f00-ff41-11ea-9800-c034324a8dac.png">

- the pod of the workload cattle-cluster-agent crashes and restarts 
<img width="1435" alt="Screen Shot 2020-09-25 at 3 04 37 PM" src="https://user-images.githubusercontent.com/6218999/94320475-e6e5d300-ff41-11ea-89de-b18a50d7b3f2.png">

logs of the crashed pod 
```
time="2020-09-25T22:03:51Z" level=error msg="Error during subscribe websocket: close sent"
E0925 22:03:51.396776       1 leaderelection.go:357] Failed to update lock: Put "https://10.43.0.1:443/api/v1/namespaces/kube-system/configmaps/cattle-agent-controllers?timeout=15m0s": context deadline exceeded
I0925 22:03:51.560057       1 leaderelection.go:278] failed to renew lease kube-system/cattle-agent-controllers: timed out waiting for the condition
E0925 22:03:51.680182       1 leaderelection.go:297] Failed to release lock: resource name may not be empty
time="2020-09-25T22:03:51Z" level=fatal msg="leaderelection lost for cattle-agent-controllers"
```

--------------

update:
the cluster keeps failing into the error state and is not usable now. 

here are the logs of the `kube-controller-manager` and `kube-scheduler` from the control plan node
[kube-controller-manager-logs.txt](https://github.com/rancher/rancher/files/5285722/kube-controller-manager-logs.txt)
[kube-scheduler-logs.txt](https://github.com/rancher/rancher/files/5285724/kube-scheduler-logs.txt)

**Comment by aiyengar2** [comment] 2020-09-28 17:26
@jiaqiluo I'm unable to reproduce this error on a Rancher cluster based on the latest master; was there a specific setup that you used for this that we could use to consistently reproduce this? I've also never encountered this with monitoring before.

From what I can tell from the logs, it's seems like you were using a 3 node cluster with 1 server and 2 agents in Digital Ocean; was there a particular VM size that you were using on these nodes?

As far as I can tell, this issue seems flakey and could be related to memory or networking issues specific to that cluster, but it's hard to pinpoint exactly what caused this error to occur.

**Comment by jiaqiluo** [comment] 2020-09-28 17:42
@aiyengar2 I will let you know if I hit it again.

**Comment by jiaqiluo** [comment] 2020-09-29 00:28
I hit this in rancher:master-head ec04f78, docker install 

The steps and results are the same as the issue describes.

**Comment by deniseschannon** [comment] 2020-10-10 15:00
@jiaqiluo Is this only docker installs or is this HA installs as well?

**Comment by jiaqiluo** [comment] 2020-10-10 21:46
@deniseschannon  I see it only in the docker install mode.

**Comment by deniseschannon** [comment] 2020-10-12 20:05
@jiaqiluo Do you know if this occurs with other apps? DO other apps cause the cattle-cluster-agent to restart?

**Comment by jiaqiluo** [comment] 2020-10-12 20:13
@deniseschannon  I have not noticed this happen when uninstalling other apps. From a conversation with @aiyengar2, the reason might be that some logic for monitoring v1 (even v1 is not enabled) tries to manipulate the same CRDs that monitoring v2 installed/uninstalled, which causes some sort of overloading or data corruption and eventually pulls the pods down.

**Comment by slickwarren** [comment] 2020-12-23 19:57
I was unable to reproduce this after installing, uninstalling, reinstalling monitoring v2 multiple (5) times.  

Rancher version: v2.5.4-rc7

steps used: 
-- install HA rancher cluster (3 node)
* add a 3 node cluster ( in my case using Linode)
* install the monitoring v2 in dashboard
* uninstall the monitoring
* re-install the monitoring
-- install docker rancher (single node)
* add a 3 node cluster ( in my case using Linode)
* install the monitoring v2 in dashboard
* uninstall the monitoring
* re-install the monitoring 

4 uninstall/reinstall attempts were made per rancher install, none of which resulted in reproducing the issue.  The cluster was in a persistent usable state throughout the tests.

**Comment by deniseschannon** [comment] 2021-01-06 00:24
@slickwarren Since this is not reproducible with the latest RC, can we close this? If you get into this setup again, please share with us and we we can investigate. 

cc: @jiaqiluo

**Comment by slickwarren** [comment] 2021-01-06 02:06
yes, thanks

**Closed by slickwarren** 2021-01-06 02:06 UTC
Labels: [zube]: To Test, kind/bug-qa
