### ISSUE TITLE
AD Groups of groups does not work

### ISSUE THREAD

**Issue by cjellick** [rancher/rancher#12987] opened 2018-04-23 18:50 UTC
A user created a group that had another group as a member. Rancher did not resolve this properly and members of the underlying group were not granted proper access

**Comment by deniseschannon** [comment] 2018-05-09 17:51
Duplicate of https://github.com/rancher/rancher/issues/8317?

**Comment by mrajashree** [comment] 2018-05-18 22:50
Can we close this or #8317 as dup?

**Comment by sangeethah** [comment] 2018-05-25 22:47
@adingilloRancher , When you are validating this issue , can you also test upgrades from AD auth enabled v2.0.2 version  to latest version to make sure there are no issues.

Also check for this specific fix in an upgraded setup:
Have AD auth enabled in v2.0.2 and provide access to a group that has many nested groups under it . 
Trying to log in as a user who are members of the nested group will fail. After upgrading to latest build , this user should have access.

**Comment by adingilloRancher** [comment] 2018-05-29 22:49
Validated ability to login with user in nested group when assigned to cluster when root group is assigned. 
Validated ability to login with user in nested group with site access restricted when root group is assigned.

Validated ability to login as nested group user post upgrade when root group is assigned.

**Closed by adingilloRancher** 2018-05-29 22:49 UTC
Labels: area/authentication, area/rbac, kind/enhancement, status/resolved, status/to-test, version/2.0
