### ISSUE TITLE
[Windows] PLEG is not healthy

### ISSUE THREAD

**Issue by thxCode** [rancher/rancher#20440] opened 2019-05-24 06:25 UTC
**What kind of request is this (question/bug/enhancement/feature request):**
bug

**Steps to reproduce (least amount of steps as possible):**
1. Start `rancher/rancher:v2.3.0-alpha3`
1. Setup a v1.14.1 Windows cluster, following [Rancher Docs](https://rancher.com/docs/rancher/v2.x/en/cluster-provisioning/rke-clusters/windows-clusters/)
1. Add a Windows worker (8G 32G) on AWS EC2 into this cluster.
1. Deploy a windows container into the cluster (See the example yaml)
1. Scale it to 10 pods and try to scale down to  9 pods

**Result:**

1. Pods cannot be removed
2. Login to the Windows node and try to do `docker rm -f`, docker rm hangs.
3. Windows node will show `PLEG is not healthy: pleg was last seen active 32m28.9290039s ago; threshold is 3m0s.`
4. In Window node docker log, it says `failed to shutdown container, and subsequent terminate also failed [error=container xxx encountered an error during WaitTimeout: hcsshim: timeout waiting for notification module=libcontainerd container=xxx namespace=moby]` It looks like we hit https://github.com/microsoft/hcsshim/issues/152

Example yaml:

```
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: test
  namespace: default
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      workload.user.cattle.io/workloadselector: deployment-default-test
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        workload.user.cattle.io/workloadselector: deployment-default-test
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: beta.kubernetes.io/os
                operator: In
                values:
                - windows
      containers:
      - image: mcr.microsoft.com/dotnet/core/samples:aspnetapp
        imagePullPolicy: Always
        name: test
        resources: {}
        securityContext:
          allowPrivilegeEscalation: false
          capabilities: {}
          privileged: false
          procMount: Default
          readOnlyRootFilesystem: false
          runAsNonRoot: false
        stdin: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        tty: true
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
```

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): master
- Installation option (single install/HA): single

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): Custom
- Machine type (cloud/VM/metal) and specifications (CPU/memory): AWS cloud provider support
- Kubernetes version (use `kubectl version`): v1.14.1
- Docker version (use `docker version`):

```
Client: Docker Engine - Enterprise
 Version:           18.09.6
 API version:       1.39
 Go version:        go1.10.8
 Git commit:        1578dcadd2
 Built:             05/04/2019 02:34:11
 OS/Arch:           windows/amd64
 Experimental:      false

Server: Docker Engine - Enterprise
 Engine:
  Version:          18.09.6
  API version:      1.39 (minimum version 1.24)
  Go version:       go1.10.8
  Git commit:       1578dcadd2
  Built:            05/04/2019 02:32:24
  OS/Arch:          windows/amd64
  Experimental:     false
```

**Comment by loganhz** [comment] 2019-05-28 07:48
Tested the following AWS AMI. AMI 2019.02.13 (`UBR 316`) and 2019.03.13 (`UBR 379`) works well. We cannot reproduce this issue.

We can reproduce it in AMI 2019.04.21 (`UBR 437`), 2019.04.26 (`UBR 437`) and 2019.05.15 (`UBR 503`) every time.

Currently default Windows image UBR is `503` on AWS and GCP. `437` on Azure. `379` on Alibaba Cloud. So it means when you provision VM on AWS, GCP and Azure with default images. You will hit this issue.

![image](https://user-images.githubusercontent.com/21168270/58459888-02c74200-815f-11e9-92e1-5f05f0daf9d2.png)

**Comment by loganhz** [comment] 2019-05-28 09:27
It looks like this issue introduced in https://support.microsoft.com/en-us/help/4490481

If your Windows Server has `April 2, 2019—KB4490481 (OS Build 17763.404)` , you will hit this issue.

**Comment by loganhz** [comment] 2019-05-28 11:03
This issue has been fixed in `May 21, 2019—KB4497934 (OS Build OS 17763.529)` https://support.microsoft.com/en-us/help/4497934

We need to wait for AWS, Google and Azure to update their default Windows Server 2019 images

**Comment by loganhz** [comment] 2019-06-14 23:45
Close it. Please see https://github.com/rancher/rancher/issues/20440#issuecomment-496469839 if you hit it

**Closed by loganhz** 2019-06-14 23:45 UTC
Labels: [zube]: Working, area/windows, kind/bug-qa, team/cn
