### ISSUE TITLE
LDAP Auth does not apply Search filter

### ISSUE THREAD

**Issue by reymonlu** [rancher/rancher#19436] opened 2019-04-08 09:57 UTC
**What kind of request is this (question/bug/enhancement/feature request):**
bug

**Steps to reproduce (least amount of steps as possible):**
Bind an LDAP server for auth
try to add Search Filter

**Result:**
The search Filter is always remove when i save my  new configuration. It always do a search request on all the LDAP entries and does not apply the filter. The filter is not present in the UI too. When i Try to add a member in a project, i show all my LDAP members not based on my filter.

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI):
2.2.0
- Installation option (single install/HA):
 HA

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported):
hosted
- Machine type (cloud/VM/metal) and specifications (CPU/memory):
metal 3 nodes (1 master and 2 workers)
4vCore and 8 Gio each
- Kubernetes version (use `kubectl version`):

```

Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.4", GitCommit:"c27b913fddd1a6c480c229191a087698aa92f0b1", GitTreeState:"clean", BuildDate:"2019-02-28T13:37:52Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.4", GitCommit:"c27b913fddd1a6c480c229191a087698aa92f0b1", GitTreeState:"clean", BuildDate:"2019-02-28T13:30:26Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}

```

- Docker version (use `docker version`):

```

 Version:           18.09.3
 API version:       1.39
 Go version:        go1.10.8
 Git commit:        774a1f4
 Built:             Thu Feb 28 06:34:04 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.2
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.6
  Git commit:       6247962
  Built:            Sun Feb 10 03:42:13 2019
  OS/Arch:          linux/amd64
  Experimental:     false

```

**Comment by deniseschannon** [comment] 2019-04-17 22:27
@tfiduccia it sounds like the search filter might not be applied after LDAP is enabled. can you check?

**Comment by tfiduccia** [comment] 2019-04-18 22:54
@deniseschannon -  There are two problems with our OpenLDAP search filters:

1.  API, userSearchFilter & groupSearchFilter are not in the schema for OpenLDAP
2.  UI, not passing groupSearchFilter (it does pass the userSearchFilter)

Both of these need to be fixed for Search Filters to work.

**Comment by deniseschannon** [comment] 2019-04-19 03:11
@mrajashree are search filters even possible with openLDAP? Or should the UI be hiding these fields?

**Comment by mrajashree** [comment] 2019-04-19 17:03
@deniseschannon I think it should be possible.

**Comment by RaphaelNeumann** [comment] 2019-05-14 19:49
I have same issue whit freeipa integration.

**Comment by alena1108** [comment] 2019-09-19 17:37
Closing as a duplicate of https://github.com/rancher/rancher/issues/18630

**Closed by alena1108** 2019-09-19 17:37 UTC
Labels: [zube]: Next Up, area/api, area/authentication, kind/bug, team/ca
