### ISSUE TITLE
When there is a delay in password validator call returning , UI report error for account creation when account creation actually succeeds.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#6499] opened 2016-11-03 00:30 UTC
Rancher Version: Build from master

Steps to reproduce the problem:
Have the api.auth.local.validate.url point to an external password validator.
Create an account by making the external password validator return success after 7 secs.

UI report error for account creation when account creation actually succeeds.

<img width="1438" alt="screen shot 2016-11-02 at 5 20 43 pm" src="https://cloud.githubusercontent.com/assets/4266958/19952381/056867e8-a122-11e6-8894-012f6d342ac2.png">

**Comment by cjellick** [comment] 2016-11-04 15:47
I'm closing as a dupe of https://github.com/rancher/rancher/issues/6475
I realize they are slightly different use cases, but I dont think they warrant separate issues. I'll make a comment in that one explaining this scenario as well.

**Closed by cjellick** 2016-11-04 15:47 UTC
Labels: kind/bug
