### ISSUE TITLE
Canal readiness probe failed with statuscode 503 for k8s 1.15

### ISSUE THREAD

**Issue by patrick0057** [rancher/rancher#23430] opened 2019-10-14 18:50 UTC
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
Create aws cluster with default options in Rancher 2.3.0

**Result:**
Once the cluster has been created, navigate to the System project, then click on Canal under the kube-system namespace.  Click on one of the canal pods then open up the Events tab.  Observe the Unhealthy warning for the readiness probe.  Screenshot pasted below of this behavior.

![image](https://user-images.githubusercontent.com/44879867/66775063-29c5ac80-ee91-11e9-8d73-af4ef7e1ae67.png)

Logs from the calico-node container:
```
2019-10-14 18:44:22.732 [INFO][8] startup.go 256: Early log level set to info
2019-10-14 18:44:22.732 [INFO][8] startup.go 272: Using NODENAME environment for node name
2019-10-14 18:44:22.732 [INFO][8] startup.go 284: Determined node name: aws3
2019-10-14 18:44:22.734 [INFO][8] k8s.go 228: Using Calico IPAM
2019-10-14 18:44:22.734 [INFO][8] startup.go 316: Checking datastore connection
2019-10-14 18:44:22.744 [INFO][8] startup.go 340: Datastore connection verified
2019-10-14 18:44:22.744 [INFO][8] startup.go 95: Datastore is ready
2019-10-14 18:44:22.772 [INFO][8] startup.go 530: FELIX_IPV6SUPPORT is false through environment variable
2019-10-14 18:44:22.778 [INFO][8] startup.go 181: Using node name: aws3
2019-10-14 18:44:22.809 [INFO][15] k8s.go 228: Using Calico IPAM
CALICO_NETWORKING_BACKEND is none - no BGP daemon running
Calico node started successfully
2019-10-14 18:44:24.038 [WARNING][33] int_dataplane.go 354: Failed to query VXLAN device error=Link not found
2019-10-14 18:44:24.074 [WARNING][33] int_dataplane.go 384: Failed to cleanup preexisting XDP state error=failed to load XDP program (/tmp/felix-xdp-563577510): stat /sys/fs/bpf/calico/xdp/prefilter_v1_calico_tmp_A: no such file or directory
libbpf: failed to get EHDR from /tmp/felix-xdp-563577510
Error: failed to open object file
2019-10-14 18:44:44.432 [WARNING][33] health.go 190: Reporter failed readiness checks name="async_calc_graph" reporter-state=&health.reporterState{name:"async_calc_graph", reports:health.HealthReport{Live:true, Ready:true}, timeout:20000000000, latest:health.HealthReport{Live:true, Ready:false}, timestamp:time.Time{wall:0xbf614e671242a664, ext:20426272735, loc:(*time.Location)(0x2b08080)}}
2019-10-14 18:45:10.016 [WARNING][33] health.go 190: Reporter failed readiness checks name="async_calc_graph" reporter-state=&health.reporterState{name:"async_calc_graph", reports:health.HealthReport{Live:true, Ready:true}, timeout:20000000000, latest:health.HealthReport{Live:true, Ready:false}, timestamp:time.Time{wall:0xbf614e6d698916e9, ext:45816765016, loc:(*time.Location)(0x2b08080)}}
2019-10-14 18:47:04.432 [WARNING][33] health.go 190: Reporter failed readiness checks name="async_calc_graph" reporter-state=&health.reporterState{name:"async_calc_graph", reports:health.HealthReport{Live:true, Ready:true}, timeout:20000000000, latest:health.HealthReport{Live:true, Ready:false}, timestamp:time.Time{wall:0xbf614e8a10a0555d, ext:160398857927, loc:(*time.Location)(0x2b08080)}}
2019-10-14 18:47:24.432 [WARNING][33] health.go 190: Reporter failed readiness checks name="async_calc_graph" reporter-state=&health.reporterState{name:"async_calc_graph", reports:health.HealthReport{Live:true, Ready:true}, timeout:20000000000, latest:health.HealthReport{Live:true, Ready:false}, timestamp:time.Time{wall:0xbf614e8f04b5ad88, ext:180198930154, loc:(*time.Location)(0x2b08080)}}
2019-10-14 18:47:50.016 [WARNING][33] health.go 190: Reporter failed readiness checks name="async_calc_graph" reporter-state=&health.reporterState{name:"async_calc_graph", reports:health.HealthReport{Live:true, Ready:true}, timeout:20000000000, latest:health.HealthReport{Live:true, Ready:false}, timestamp:time.Time{wall:0xbf614e9568781150, ext:205798872324, loc:(*time.Location)(0x2b08080)}}
2019-10-14 18:49:44.432 [WARNING][33] health.go 190: Reporter failed readiness checks name="async_calc_graph" reporter-state=&health.reporterState{name:"async_calc_graph", reports:health.HealthReport{Live:true, Ready:true}, timeout:20000000000, latest:health.HealthReport{Live:true, Ready:false}, timestamp:time.Time{wall:0xbf614eb2118552ef, ext:320413865069, loc:(*time.Location)(0x2b08080)}}
2019-10-14 18:50:04.432 [WARNING][33] health.go 190: Reporter failed readiness checks name="async_calc_graph" reporter-state=&health.reporterState{name:"async_calc_graph", reports:health.HealthReport{Live:true, Ready:true}, timeout:20000000000, latest:health.HealthReport{Live:true, Ready:false}, timestamp:time.Time{wall:0xbf614eb704b6187f, ext:340198957640, loc:(*time.Location)(0x2b08080)}}
2019-10-14 18:50:30.017 [WARNING][33] health.go 190: Reporter failed readiness checks name="async_calc_graph" reporter-state=&health.reporterState{name:"async_calc_graph", reports:health.HealthReport{Live:true, Ready:true}, timeout:20000000000, latest:health.HealthReport{Live:true, Ready:false}, timestamp:time.Time{wall:0xbf614ebd687a5ed0, ext:365799023174, loc:(*time.Location)(0x2b08080)}}
2019-10-14 18:52:24.432 [WARNING][33] health.go 190: Reporter failed readiness checks name="async_calc_graph" reporter-state=&health.reporterState{name:"async_calc_graph", reports:health.HealthReport{Live:true, Ready:true}, timeout:20000000000, latest:health.HealthReport{Live:true, Ready:false}, timestamp:time.Time{wall:0xbf614eda118b4aee, ext:480414256219, loc:(*time.Location)(0x2b08080)}}
2019-10-14 18:52:44.432 [WARNING][33] health.go 190: Reporter failed readiness checks name="async_calc_graph" reporter-state=&health.reporterState{name:"async_calc_graph", reports:health.HealthReport{Live:true, Ready:true}, timeout:20000000000, latest:health.HealthReport{Live:true, Ready:false}, timestamp:time.Time{wall:0xbf614edf04b5d5b4, ext:500198940515, loc:(*time.Location)(0x2b08080)}}
2019-10-14 18:53:10.016 [WARNING][33] health.go 190: Reporter failed readiness checks name="async_calc_graph" reporter-state=&health.reporterState{name:"async_calc_graph", reports:health.HealthReport{Live:true, Ready:true}, timeout:20000000000, latest:health.HealthReport{Live:true, Ready:false}, timestamp:time.Time{wall:0xbf614ee568774cab, ext:525798821911, loc:(*time.Location)(0x2b08080)}}
2019-10-14 18:55:04.432 [WARNING][33] health.go 190: Reporter failed readiness checks name="async_calc_graph" reporter-state=&health.reporterState{name:"async_calc_graph", reports:health.HealthReport{Live:true, Ready:true}, timeout:20000000000, latest:health.HealthReport{Live:true, Ready:false}, timestamp:time.Time{wall:0xbf614f0210ad7f44, ext:640399720623, loc:(*time.Location)(0x2b08080)}}
2019-10-14 18:55:24.432 [WARNING][33] health.go 190: Reporter failed readiness checks name="async_calc_graph" reporter-state=&health.reporterState{name:"async_calc_graph", reports:health.HealthReport{Live:true, Ready:true}, timeout:20000000000, latest:health.HealthReport{Live:true, Ready:false}, timestamp:time.Time{wall:0xbf614f0705adeec1, ext:660215199869, loc:(*time.Location)(0x2b08080)}}
2019-10-14 18:55:50.017 [WARNING][33] health.go 190: Reporter failed readiness checks name="async_calc_graph" reporter-state=&health.reporterState{name:"async_calc_graph", reports:health.HealthReport{Live:true, Ready:true}, timeout:20000000000, latest:health.HealthReport{Live:true, Ready:false}, timestamp:time.Time{wall:0xbf614f0d687ee33d, ext:685799319221, loc:(*time.Location)(0x2b08080)}}
```

**Other details that may be helpful:**
This does not happen in Rancher v2.2.8

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): Rancher v2.3.0
- Installation option (single install/HA): HA

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): AWS
- Machine type (cloud/VM/metal) and specifications (CPU/memory): VM, t2.large
- Kubernetes version (use `kubectl version`): 1.14.6

**Comment by Aisuko** [comment] 2019-10-15 07:56
I hit this issue on my HA cluster after I upgrade rancher from v2.2.8 to v2.3.0. Kubernetes version `1.15.4`. The cluster was deployed on bare metal.

```
kube-system | Warning | Unhealthy | canal-n82dt | Readiness probe failed: HTTP probe failed with statuscode: 503 | a minute ago
kube-system | Warning | Unhealthy | canal-sljs9 | Readiness probe failed: HTTP probe failed with statuscode: 503 | 2 minutes ago
kube-system | Warning | Unhealthy | canal-mdxhh | Readiness probe failed: HTTP probe failed with statuscode: 503 | 2 minutes ago
kube-system | Warning | Unhealthy | canal-w78sk | Readiness probe failed: HTTP probe failed with statuscode: 503 | 3 minutes ago
kube-system | Warning | Unhealthy | canal-wtgcq | Readiness probe failed: HTTP probe failed with statuscode: 503 | 3 minutes ago
```

**Comment by xytnba** [comment] 2019-10-16 06:14
I meet the same bug when I add a new node. The other node is not occured.

**Comment by superseb** [comment] 2019-10-16 09:22
Please let me know if this solves the issue while we investigate further:

Save the following in `crd.yml` and execute `kubectl create -f crd.yml` in the cluster

```
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: ipamblocks.crd.projectcalico.org
spec:
  scope: Cluster
  group: crd.projectcalico.org
  version: v1
  names:
    kind: IPAMBlock
    plural: ipamblocks
    singular: ipamblock
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: networksets.crd.projectcalico.org
spec:
  scope: Namespaced
  group: crd.projectcalico.org
  version: v1
  names:
    kind: NetworkSet
    plural: networksets
    singular: networkset
```

**Comment by soundinsekt** [comment] 2019-10-16 09:47
I had the same bug with a fresh 2.3.0 install and kubernetes v1.15.4.
Creating the two CRDs seems to have fixed it
thanks!

**Comment by Aisuko** [comment] 2019-10-16 10:46
It works for me.

**Comment by Aisuko** [comment] 2019-10-16 10:58
I got these events on the one cluster, another cluster works well.
```
kube-system | Warning | Unhealthy | canal-cd924 | Liveness probe failed: Get http://localhost:9099/liveness: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers) | 3 minutes ago
kube-system | Warning | Unhealthy | canal-cd924 | Readiness probe failed: Get http://localhost:9099/readiness: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers) | 3 minutes ago
kube-system | Warning | Unhealthy | canal-tz42g | Readiness probe failed: Get http://localhost:9099/readiness: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers) | 8 minutes ago
kube-system | Warning | Unhealthy | canal-tz42g | Liveness probe failed: Get http://localhost:9099/liveness: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers) | 8 minutes ago
kube-system | Warning | Unhealthy | canal-8grhd | Liveness probe failed: Get http://localhost:9099/liveness: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers) | 21 minutes ago
kube-system | Warning | Unhealthy | canal-8grhd | Readiness probe failed: Get http://localhost:9099/readiness: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers) | 21 minutes ago
kube-system | Warning | Unhealthy | canal-68m67 | Liveness probe failed: Get http://localhost:9099/liveness: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers) | 34 minutes ago
```

**Comment by superseb** [comment] 2019-10-20 18:26
The fix for this is patching the `canal` DaemonSet and creating the NetworkSet CRD (this will recreate Canal pods), this is use at your own risk until it gets verified and released (test envs only):

```
kubectl -n kube-system patch daemonset/canal -p '{"spec": {"template": {"spec": {"containers": [{"name": "calico-node", "env": [{"name": "USE_POD_CIDR", "value": "true"}]}]}}}}'
```

Save the following as `crd.yml` and run `kubectl create -f crd.yml` in the cluster:

```
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: networksets.crd.projectcalico.org
spec:
  scope: Namespaced
  group: crd.projectcalico.org
  version: v1
  names:
    kind: NetworkSet
    plural: networksets
    singular: networkset
```

**Comment by alena1108** [comment] 2019-10-20 19:00
@deniseschannon once verified and closed, we should release note the fact that the canal pods will get recreated in upgraded setups, on cluster edit.

**Comment by jiaqiluo** [comment] 2019-10-21 21:43
The bug is reproduced in a cluster with k8s `v1.15.5` in Rancher:`v2.3.1`

Once the cluster has been created, navigate to the `System project`, then click on `Canal` under the `kube-system` namespace. Click on one of the canal pods then open up the Events tab. Observe the Unhealthy warning for the readiness probe

<img width="1529" alt="Screen Shot 2019-10-21 at 2 42 13 PM" src="https://user-images.githubusercontent.com/6218999/67245504-01016200-f411-11e9-892b-6026fdfcba28.png">

Logs from the calico-node container:
```
2019-10-21 21:32:39.889 [WARNING][34] health.go 190: Reporter failed readiness checks name="async_calc_graph" reporter-state=&health.reporterState{name:"async_calc_graph", reports:health.HealthReport{Live:true, Ready:true}, timeout:20000000000, latest:health.HealthReport{Live:true, Ready:false}, timestamp:time.Time{wall:0xbf63a6dde84835bb, ext:102914726961, loc:(*time.Location)(0x2b08080)}}
2019-10-21 21:32:59.221 [WARNING][34] health.go 190: Reporter failed readiness checks name="async_calc_graph" reporter-state=&health.reporterState{name:"async_calc_graph", reports:health.HealthReport{Live:true, Ready:true}, timeout:20000000000, latest:health.HealthReport{Live:true, Ready:false}, timestamp:time.Time{wall:0xbf63a6e2b42d88f0, ext:122114305408, loc:(*time.Location)(0x2b08080)}}
2019-10-21 21:35:19.889 [WARNING][34] health.go 190: Reporter failed readiness checks name="async_calc_graph" reporter-state=&health.reporterState{name:"async_calc_graph", reports:health.HealthReport{Live:true, Ready:true}, timeout:20000000000, latest:health.HealthReport{Live:true, Ready:false}, timestamp:time.Time{wall:0xbf63a705e84342c5, ext:262914402646, loc:(*time.Location)(0x2b08080)}}
2019-10-21 21:35:39.221 [WARNING][34] health.go 190: Reporter failed readiness checks name="async_calc_graph" reporter-state=&health.reporterState{name:"async_calc_graph", reports:health.HealthReport{Live:true, Ready:true}, timeout:20000000000, latest:health.HealthReport{Live:true, Ready:false}, timestamp:time.Time{wall:0xbf63a70ab42df417, ext:282114332769, loc:(*time.Location)(0x2b08080)}}
2019-10-21 21:37:59.889 [WARNING][34] health.go 190: Reporter failed readiness checks name="async_calc_graph" reporter-state=&health.reporterState{name:"async_calc_graph", reports:health.HealthReport{Live:true, Ready:true}, timeout:20000000000, latest:health.HealthReport{Live:true, Ready:false}, timestamp:time.Time{wall:0xbf63a72de8418b71, ext:422914290197, loc:(*time.Location)(0x2b08080)}}
2019-10-21 21:38:19.221 [WARNING][34] health.go 190: Reporter failed readiness checks name="async_calc_graph" reporter-state=&health.reporterState{name:"async_calc_graph", reports:health.HealthReport{Live:true, Ready:true}, timeout:20000000000, latest:health.HealthReport{Live:true, Ready:false}, timestamp:time.Time{wall:0xbf63a732b42b3445, ext:442114152597, loc:(*time.Location)(0x2b08080)}}
2019-10-21 21:40:39.889 [WARNING][34] health.go 190: Reporter failed readiness checks name="async_calc_graph" reporter-state=&health.reporterState{name:"async_calc_graph", reports:health.HealthReport{Live:true, Ready:true}, timeout:20000000000, latest:health.HealthReport{Live:true, Ready:false}, timestamp:time.Time{wall:0xbf63a755e8461c18, ext:582914589332, loc:(*time.Location)(0x2b08080)}}
2019-10-21 21:40:59.221 [WARNING][34] health.go 190: Reporter failed readiness checks name="async_calc_graph" reporter-state=&health.reporterState{name:"async_calc_graph", reports:health.HealthReport{Live:true, Ready:true}, timeout:20000000000, latest:health.HealthReport{Live:true, Ready:false}, timestamp:time.Time{wall:0xbf63a75ab42dd4a5, ext:602114324717, loc:(*time.Location)(0x2b08080)}}```

**Comment by jiaqiluo** [comment] 2019-10-21 22:40
The bug fix is validated in Rancher:v2.3-head 8d57a1c with the metadata from `dev` branch

add a cluster with k8s `v1.15.5` with Canal

Results:
- no unhealthy warning in the event of the pod canal
- no `[WARNING][34]` in the logs of the container `calico-node`

**Comment by jiaqiluo** [comment] 2019-10-21 23:56
For this issue, I can only reproduce it in k8s 1.15 cluster, although it is reported in 1.14 cluster originally.
@alena commented a cluster edit on an upgraded setup would trigger pods to be recreated. I did not upgrade Rancher but changed the metadata to dev, then I edited the cluster to trigger a rke up, but the pods were not recreated and the issue still existed.

So the issue is reopened for more investigation

**Comment by roycec** [comment] 2019-10-22 15:22
Same here, I just updated the underlying cluster for Rancher to k82 v1.15.4. Rancher itself is still on 2.2.8

**Comment by jiaqiluo** [comment] 2019-10-22 17:24
@roycec  Do you mean you upgrade the local cluster when installing Rancher in HA mode? This bug is about Rancher-provisioned clusters. 
Also, the fix is in Rancher's metadata, so the only way to fix it is to upgrade Rancher and then upgrade the cluster.

**Comment by jiaqiluo** [comment] 2019-10-22 17:30
The bug fix is validated in v2.3-head 6d40dad33 upgraded from v2.3.1

Steps:
- run rancher v2.3.1
- add an ec2 cluster with k8s v1.15.5 with Canal
- see the readiness errors 
- upgrade Rancher to v2.3-head
- notice the rke-metadata-config uses branch dev
- edit the above cluster to upgrade it
- the readiness error is gone

**Closed by jiaqiluo** 2019-10-22 17:30 UTC
Labels: [zube]: To Test, internal, kind/bug, team/ca

**Comment by soakes** [comment] 2019-10-22 20:42
Hi Guys,

I just installed a new cluster with canal via rke and ran into this exact same bug using "latest" helm chart.

I just tried the "solution" which @superseb has kindly shared and can confirm this resolves the issue.

I have pasted the events log below for confirmation.

```
kube-system | Normal | Created | canal-wg6pv | Created container calico-node | 5 minutes ago
-- | -- | -- | -- | -- | --
kube-system | Normal | Started | canal-wg6pv | Started container calico-node | 5 minutes ago
kube-system | Normal | Pulled | canal-wg6pv | Container image "rancher/coreos-flannel:v0.11.0" already present on machine | 5 minutes ago
kube-system | Normal | Created | canal-wg6pv | Created container kube-flannel | 5 minutes ago
kube-system | Normal | Started | canal-wg6pv | Started container kube-flannel | 5 minutes ago
kube-system | Normal | Started | canal-wg6pv | Started container install-cni | 5 minutes ago
kube-system | Normal | Pulled | canal-wg6pv | Container image "rancher/calico-node:v3.7.4" already present on machine | 5 minutes ago
kube-system | Normal | Pulled | canal-wg6pv | Container image "rancher/calico-cni:v3.7.4" already present on machine | 5 minutes ago
kube-system | Normal | Created | canal-wg6pv | Created container install-cni | 5 minutes ago
kube-system | Normal | Scheduled | canal-wg6pv | Successfully assigned kube-system/canal-wg6pv to rmgr03 | 5 minutes ago
kube-system | Normal | Killing | canal-x2npx | Stopping container calico-node | 5 minutes ago
kube-system | Normal | Killing | canal-x2npx | Stopping container kube-flannel | 5 minutes ago
kube-system | Normal | SuccessfulDelete | canal | Deleted pod: canal-x2npx | 5 minutes ago
kube-system | Normal | SuccessfulCreate | canal | Created pod: canal-wg6pv | 5 minutes ago
kube-system | Normal | Created | canal-rw55m | Created container calico-node | 5 minutes ago
kube-system | Normal | Started | canal-rw55m | Started container calico-node | 5 minutes ago
kube-system | Normal | Pulled | canal-rw55m | Container image "rancher/coreos-flannel:v0.11.0" already present on machine | 5 minutes ago
kube-system | Normal | Created | canal-rw55m | Created container kube-flannel | 5 minutes ago
kube-system | Normal | Started | canal-rw55m | Started container kube-flannel | 5 minutes ago
kube-system | Normal | Pulled | canal-rw55m | Container image "rancher/calico-node:v3.7.4" already present on machine | 5 minutes ago
kube-system | Normal | Pulled | canal-rw55m | Container image "rancher/calico-cni:v3.7.4" already present on machine | 5 minutes ago
kube-system | Normal | Created | canal-rw55m | Created container install-cni | 5 minutes ago
kube-system | Normal | Started | canal-rw55m | Started container install-cni | 5 minutes ago
kube-system | Normal | Killing | canal-6xkx6 | Stopping container calico-node | 5 minutes ago
kube-system | Normal | Scheduled | canal-rw55m | Successfully assigned kube-system/canal-rw55m to rmgr01 | 5 minutes ago
kube-system | Normal | SuccessfulDelete | canal | Deleted pod: canal-6xkx6 | 5 minutes ago
kube-system | Normal | SuccessfulCreate | canal | Created pod: canal-rw55m | 5 minutes ago
kube-system | Normal | Started | canal-gsvht | Started container calico-node | 5 minutes ago
kube-system | Normal | Pulled | canal-gsvht | Container image "rancher/coreos-flannel:v0.11.0" already present on machine | 5 minutes ago
kube-system | Normal | Created | canal-gsvht | Created container kube-flannel | 5 minutes ago
kube-system | Normal | Started | canal-gsvht | Started container kube-flannel | 5 minutes ago
kube-system | Normal | Started | canal-gsvht | Started container install-cni | 5 minutes ago
kube-system | Normal | Pulled | canal-gsvht | Container image "rancher/calico-node:v3.7.4" already present on machine | 5 minutes ago
kube-system | Normal | Created | canal-gsvht | Created container calico-node | 5 minutes ago
kube-system | Normal | Pulled | canal-gsvht | Container image "rancher/calico-cni:v3.7.4" already present on machine | 5 minutes ago
kube-system | Normal | Created | canal-gsvht | Created container install-cni | 5 minutes ago
kube-system | Normal | Scheduled | canal-gsvht | Successfully assigned kube-system/canal-gsvht to rmgr02 | 5 minutes ago
kube-system | Normal | Killing | canal-lrzpb | Stopping container kube-flannel | 5 minutes ago
kube-system | Normal | SuccessfulDelete | canal | Deleted pod: canal-lrzpb | 5 minutes ago
kube-system | Normal | SuccessfulCreate | canal | Created pod: canal-gsvht | 5 minutes ago
kube-system | Warning | Unhealthy | canal-6xkx6 | Readiness probe failed: HTTP probe failed with statuscode: 503 | 6 minutes ago
kube-system | Warning | Unhealthy | canal-x2npx | Readiness probe failed: HTTP probe failed with statuscode: 503 | 6 minutes ago
kube-system | Warning | Unhealthy | canal-lrzpb | Readiness probe failed: HTTP probe failed with statuscode: 503 | 6 minutes ago
cattle-system | Normal | Pulled | cattle-cluster-agent-5768f46d46-l8v5w | Successfully pulled image "rancher/rancher-agent:v2.3.1" | 12 minutes ago
cattle-system | Normal | Created | cattle-cluster-agent-5768f46d46-l8v5w | Created container cluster-register | 12 minutes ago
cattle-system | Normal | Started | cattle-cluster-agent-5768f46d46-l8v5w | Started container cluster-register | 12 minutes ago
cattle-system | Normal | Created | cattle-node-agent-wf2w8 | Created container agent | 12 minutes ago
cattle-system | Normal | Started | cattle-node-agent-wf2w8 | Started container agent | 12 minutes ago
cattle-system | Normal | Created | cattle-node-agent-kljlt | Created container agent | 12 minutes ago
cattle-system | Normal | Started | cattle-node-agent-kljlt | Started container agent | 12 minutes ago
```

**Comment by roycec** [comment] 2019-10-22 21:30
@jiaqiluo: I understand what you mean; I've an Rancher 2.2.8 HA installation and upgraded the RKE cluster (if the term is correct) to kubernetes 1.15.4 and got the same error than the original poster, but for the 'local' cluster. Should I open a new issue then?

**Comment by jiaqiluo** [comment] 2019-10-22 23:07
@roycec sure, be free to open a new issue for it, and it looks like the `rke: v0.3.2-rc2`( https://github.com/rancher/rke/releases/tag/v0.3.2-rc2) should have the fix.
