### ISSUE TITLE
Issues with OpenStack Node driver

### ISSUE THREAD

**Issue by HelenCousins** [rancher/rancher#23094] opened 2019-09-26 10:17 UTC
We are using Rancher on our internal OpenStack.

Rancher has an OpenStack Node driver.

We have issues:

It does not appear possible to use an existing key (the config option is present, but it doesn't work).
Nodes are given Rancher-created keypairs therefore, but these are not cleaned up on cluster deletion. 
Nodes are assigned floating IPs, but these are not properly cleaned up on node/cluster deletion. (we do not believe all nodes need floating IPs, but if they have them they need to be properly deleted when the node is deleted)

We have terraform that does node creation the way we like them, it might be helpful to be able to tie our terraform into rancher cluster deployment, is this a supported option?

**Comment by dramich** [comment] 2019-09-26 17:42
Closing as duplicate of https://github.com/rancher/rancher/issues/23096

**Closed by dramich** 2019-09-26 17:42 UTC
