### ISSUE TITLE
Deleting provisioned RKE2 cluster could leave jobs/secrets around

### ISSUE THREAD

**Issue by thedadams** [rancher/rancher#35701] opened 2021-12-01 00:29 UTC
**Rancher Server Setup**
- Rancher version: 2.6-head
- Installation option (Docker install/Helm Chart):
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): Any
- Proxy/Cert Details: None

**Information about the Cluster**
- Kubernetes version: 1.21
- Cluster Type (Local/Downstream): Downstream
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider): Provisioned RKE2 cluster with any provider

**Describe the bug**

When deleting a provisioned RKE2 cluster from Rancher, there could be some secrets and a job/pod leftover after the cluster disappears. This is mostly harmless because these items will just be recreated if another cluster is create with the same name and configuration. However, Rancher should clean them up correctly.

**To Reproduce**
 
1. Provision an RKE2 cluster from Rancher
2. Wait for the cluster to become active
3. Delete the cluster
4. Wait for the cluster to disappear from the UI

**Result**
With `kubectl -n fleet-default get jobs` and `kubectl -n fleet-default get secrets` you may see some stuff leftover from the deleted cluster.

**Expected Result**

All the aforementioned items should be cleaned up from Rancher.

**Additional context**

The problem here is that the infrastructure object will go back through the controller after the infrastructure has been cleaned up. This is because a condition will get updated and the controller will pick up the change. The job and secrets will be recreated after they were already deleted and the job will kick off again. The infrastructure object, meanwhile, will be cleaned up and the leftover items never cleaned up (because they only get cleaned up when the infrastructure machine object goes through the delete controller successfully).

The solution (which I have tested) is to short-circuit the infrastructure machine deletion if the `DeleteJob` condition is set (the `DeleteJob` condition will only be set if the delete job completed or failed). Care should be taken to handle the force-delete situation with infrastructure machines.

**Comment by snasovich** [comment] 2021-12-20 19:43
Likely already fixed in 2.6.3, need to verify in 2.6.4.

**Comment by jakefhyde** [comment] 2022-01-07 01:13
Haven't been able to reproduce on `v2.6-head` after trying multiple times.

## Before removing cluster
```
❯ kubectl -n fleet-default get jobs
No resources found in fleet-default namespace.
❯ kubectl -n fleet-default get secrets
NAME                                                              TYPE                                          DATA   AGE
default-token-fv6ck                                               kubernetes.io/service-account-token           3      14m
import-token-jhyde-test                                           fleet.cattle.io/cluster-registration-values   1      6m29s
import-token-jhyde-test-8471f6c7-8940-487b-a787-17519c0311v9bxp   kubernetes.io/service-account-token           3      6m29s
jhyde-test-bootstrap-template-gpv5f-machine-plan                  rke.cattle.io/machine-plan                    10     11m
jhyde-test-bootstrap-template-gpv5f-machine-plan-token-2fphn      kubernetes.io/service-account-token           3      11m
jhyde-test-jhyde-test-240eb9df-fmsdl-machine-state                rke.cattle.io/machine-state                   1      11m
jhyde-test-kubeconfig                                             Opaque                                        2      11m
jhyde-test-rke-state                                              rke.cattle.io/cluster-state                   2      11m
```
## After removing cluster
```
❯ kubectl -n fleet-default get jobs
No resources found in fleet-default namespace.
❯ kubectl -n fleet-default get secrets
NAME                  TYPE                                  DATA   AGE
default-token-fv6ck   kubernetes.io/service-account-token   3      18m
```

@thedadams @snasovich Are there any other specific cases I should test, or can we move back to test?

**Comment by thedadams** [comment] 2022-01-07 01:15
@jakefhyde this was fixed in 2.6.3, but QA didn't have time to verify it. You can move it to "To Test"

**Comment by sgapanovich** [comment] 2022-02-16 17:38
### Repro: ###
@thedadams I was not able to reproduce the issue.
I tried:
-2.6.2 rancher | 1 downstream cluster: RKE2 aws node driver 
-2.6.1 rancher | 2 downstream clusters : RKE2 aws and do node driver
I won't post secrets before and after deletion because they are basically the same as @jakefhyde 

---------------------

### Testing: ###
Rancher version: 2.6-head 3f30288
Rancher cluster type: HA
Docker version: 20.10

Downstream clusters: RKE2 node drivers (aws, do, linode, azure) with 1.21 k8s 

```
2.6head 3f30288


----------------------BEFORE DELETING THE RKE2 CLUSTERS--------------------


kubectl get secret -n fleet-default
NAME                                                              TYPE                                          DATA   AGE
aws-bootstrap-template-84w8m-machine-plan                         rke.cattle.io/machine-plan                    11     38m
aws-bootstrap-template-84w8m-machine-plan-token-lqmsb             kubernetes.io/service-account-token           3      38m
aws-bootstrap-template-klh9t-machine-plan                         rke.cattle.io/machine-plan                    11     38m
aws-bootstrap-template-klh9t-machine-plan-token-c4tmg             kubernetes.io/service-account-token           3      38m
aws-kubeconfig                                                    Opaque                                        2      38m
aws-rke-state                                                     rke.cattle.io/cluster-state                   2      38m
aws-sergeietcdcp-de8b40e9-rspb6-machine-state                     rke.cattle.io/machine-state                   1      38m
aws-sergeiw-6be52800-b6xqb-machine-state                          rke.cattle.io/machine-state                   1      38m
default-token-cl66m                                               kubernetes.io/service-account-token           3      13h
import-token-aws                                                  fleet.cattle.io/cluster-registration-values   1      33m
import-token-aws-8355eb75-1515-400a-8b13-bbd86999eb68-toke5gd8g   kubernetes.io/service-account-token           3      33m
import-token-sergeiazure                                          fleet.cattle.io/cluster-registration-values   1      7m36s
import-token-sergeiazure-0d1faf7a-a438-4b57-9c2b-674c4abc7ckkhr   kubernetes.io/service-account-token           3      7m36s
import-token-sergeido                                             fleet.cattle.io/cluster-registration-values   1      24m
import-token-sergeido-e2afe2d5-d91a-400c-b983-70c78df1a2906gqhz   kubernetes.io/service-account-token           3      24m
import-token-sergeilinode                                         fleet.cattle.io/cluster-registration-values   1      4m3s
import-token-sergeilinode-5b640b57-45f3-4138-bc4d-33094938h5c7r   kubernetes.io/service-account-token           3      4m3s
sergeiazure-bootstrap-template-c52gk-machine-plan                 rke.cattle.io/machine-plan                    11     17m
sergeiazure-bootstrap-template-c52gk-machine-plan-token-pjrmn     kubernetes.io/service-account-token           3      17m
sergeiazure-bootstrap-template-rlrcp-machine-plan                 rke.cattle.io/machine-plan                    11     17m
sergeiazure-bootstrap-template-rlrcp-machine-plan-token-h2fx4     kubernetes.io/service-account-token           3      17m
sergeiazure-kubeconfig                                            Opaque                                        2      17m
sergeiazure-rke-state                                             rke.cattle.io/cluster-state                   2      17m
sergeiazure-sergeietcdcp-6287dde8-hkngc-machine-state             rke.cattle.io/machine-state                   1      17m
sergeiazure-sergeiw-a0d0577a-vgvjd-machine-state                  rke.cattle.io/machine-state                   1      17m
sergeido-bootstrap-template-6pb9t-machine-plan                    rke.cattle.io/machine-plan                    11     30m
sergeido-bootstrap-template-6pb9t-machine-plan-token-t8hkh        kubernetes.io/service-account-token           3      30m
sergeido-bootstrap-template-rcz74-machine-plan                    rke.cattle.io/machine-plan                    11     30m
sergeido-bootstrap-template-rcz74-machine-plan-token-x4sbr        kubernetes.io/service-account-token           3      30m
sergeido-kubeconfig                                               Opaque                                        2      30m
sergeido-rke-state                                                rke.cattle.io/cluster-state                   2      30m
sergeido-sergeietcdcp-12508118-6ppz8-machine-state                rke.cattle.io/machine-state                   1      30m
sergeido-sergeiw-f0a3e4a9-j9zx6-machine-state                     rke.cattle.io/machine-state                   1      30m
sergeilinode-bootstrap-template-v8nrr-machine-plan                rke.cattle.io/machine-plan                    11     11m
sergeilinode-bootstrap-template-v8nrr-machine-plan-token-frjxf    kubernetes.io/service-account-token           3      11m
sergeilinode-bootstrap-template-wtjwj-machine-plan                rke.cattle.io/machine-plan                    11     11m
sergeilinode-bootstrap-template-wtjwj-machine-plan-token-rkx47    kubernetes.io/service-account-token           3      11m
sergeilinode-kubeconfig                                           Opaque                                        2      11m
sergeilinode-rke-state                                            rke.cattle.io/cluster-state                   2      11m
sergeilinode-sergeietcdcp-4a2087e7-lcntg-machine-state            rke.cattle.io/machine-state                   1      11m
sergeilinode-sergeiw-a16bff52-mcbw2-machine-state                 rke.cattle.io/machine-state                   1      11m

kubectl get job -n fleet-default
No resources found in fleet-default namespace.


----------------------AFTER DELETING THE RKE2 CLUSTERS--------------------


kubectl get secret -n fleet-default
NAME                  TYPE                                  DATA   AGE
default-token-cl66m   kubernetes.io/service-account-token   3      12h

kubectl get job -n fleet-default
No resources found in fleet-default namespace.
```

I don't see any jobs or secrets left after deleting clusters (azure did take longer to be deleted than others but in about 2 minutes everything was deleted)

**Comment by sgapanovich** [comment] 2022-02-16 17:44
@thedadams I was just going to ask you if there was something else you wanted me to try. But yes, I think we can close the issue

**Closed** 2022-02-16 17:44 UTC
Labels: [zube]: QA Working, QA/XS, area/provisioning-rke2, team/area2
