### ISSUE TITLE
Bug: Rancher pod memory leak, OOM

### ISSUE THREAD

**Issue by patrick0057** [rancher/rancher#24204] opened 2019-11-22 15:41 UTC
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
Unknown at this time

**Result:**
Rancher pods getting killed OOM

**Other details that may be helpful:**
Might be related to https://github.com/rancher/rancher/issues/21361 but we scaled down all rancher node and cluster agents to 0 on all clusters except for the local cluster.

Ping me for logs, heap, thread dump and etcd snapshot.  

The only way we were able to fix this was by restoring to an etcd snapshot from before the problem started happening.

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): v2.2.8
- Installation option (single install/HA): HA

**Comment by deniseschannon** [comment] 2019-12-12 17:57
We've put some fixes in around memory leaks into 2.3.3 but have not definitively concluded that this was the root cause for this issue. We want to keep this open for now to monitor it.

**Comment by deniseschannon** [comment] 2020-02-08 19:11
We will keep this around to track to see if someone else hits the OOM with the later releases.

**Comment by harshsharma22** [comment] 2020-02-11 03:13
> We will keep this around to track to see if someone else hits the OOM with the later releases.

facing same issue in v2.3.4

**Comment by ukinau** [comment] 2020-04-13 17:28
JFYI: as I left comment in #21361. 
there is memory leak problem when you have the clusters which is not responding via rancher cluster-agent. 

> we scaled down all rancher node and cluster agents to 0
This looks like pretty much causing the issue what I described in https://github.com/rancher/rancher/issues/21361#issuecomment-612500020
https://medium.com/uckey/memory-goroutine-leak-with-rancher-kubernetes-custom-controller-with-client-go-9e296c815209

**Comment by maggieliu** [comment] 2020-11-23 19:11
Closing this in favor of https://github.com/rancher/rancher/issues/29429.

**Closed by maggieliu** 2020-11-23 19:11 UTC
Labels: [zube]: Team Red Backlog, internal, kind/bug
