### ISSUE TITLE
Edit View for Load Balancing Broken

### ISSUE THREAD

**Issue by dariusgm** [rancher/rancher#4926] opened 2016-05-26 13:27 UTC
Inside a Stack View, I click on "edit" on a Load Balancer Config. The Overlay opens, but is empty. I get a JavaScript Error in my Console:

intl.js:184 Uncaught TypeError: i.call is not a function

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v1.1.0-dev2` Cattle: `v0.161.5` UI: `v1.1.2` |
|Access|`Disabled`|
|Orchestration|`Cattle`|
|Route|`environment.index`|

**Comment by dariusgm** [comment] 2016-05-26 13:38
Related to #4914 ?

**Comment by tfiduccia** [comment] 2016-05-26 17:42
You are correct that this is a duplicate of #4914.

**Closed by tfiduccia** 2016-05-26 17:42 UTC
