### ISSUE TITLE
[BUG] cluster deploy running excessively and taking a long time to execute

### ISSUE THREAD

**Issue by rmweir** [rancher/rancher#39597] opened 2022-11-14 23:25 UTC
**Rancher Server Setup**
- Rancher version: 2.7.x
- Installation option: any
- Proxy/Cert Details: irrelevant

**Information about the Cluster**
- Kubernetes version: irrelevant
- Cluster Type (Local/Downstream): issue is seen in local cluster with at least one disconnected cluster

**User Information**
- What is the role of the user logged in? irrelevant

**Describe the bug**
With a disconnected downstream cluster, the `clusterdeploy` handler takes several seconds to time out. This is fine with only a few downstream clusters disconnected, but when the number of disconnected clusters goes over 50 or so, the worker queues will get saturated.

Reason for the slow time out is that the handler may execute code that reaches out to the disconnected downstream cluster - typically `clusterDeploy.getNodeAgentImage` which tries to list `DaemonSets`. That alone can take up to ~30 seconds due to how `TunnelServer`'s `remotedialer` mechanism works.

**To Reproduce**
See https://github.com/rancher/rancher/issues/39597#issuecomment-1816099261

**Result**

**Expected Result**
Little to no executions of cluster deploy handler while creating users. Cluster deploy handler should not probably not exceed an execution time of 1 second.

**Screenshots**
N/A
**Additional context**
N/A

**Comment by git-ival** [comment] 2022-11-15 18:34
Steps to Reproduce:

1. Setup a cluster with Rancher and the latest version of `rancher-monitoring` installed
    - Used an RKE2 cluster during testing
2. Begin creating users
3. Once you reach 4,000 - 10,000 users, view the Rancher Performance Debugging grafana dashboards in rancher-monitoring
4. Observe the "Handler Average Execution Times" graph and note the exceptionally high execution rate on cluster deploy handler
5. Stop creating users

Notes:
- The testing that revealed this issue was done using the rancher2 terraform provider (unsure if this might be relevant)
- Users were all created with the exact same roles/permissions

**Comment by rmweir** [comment] 2023-04-12 16:11
This has been reproducible when shutting down cluster nodes for downstream clusters. Handlers spend a lot of time using clusterDialer to try to reconnect. A similar issue appears to happen with the cluster-stats handler. This issue is described in more detail here https://github.com/rancher/rancher/issues/27676#issuecomment-1503897290. This issue affects this RFE  https://github.com/rancher/rancher/issues/27676.

**Comment by snasovich** [comment] 2023-08-09 18:46
@rmweir @moio , removing `team/area2` as we're not taking the lead on this one. If it needs to be changed and there is priority for us to work on this, please let us know.
FYI @cbron @Sahota1225 @daviswill2

**Comment by erkki** [comment] 2023-11-15 08:40
#43542

**Comment by moio** [comment] 2023-11-15 11:02
Thanks @erkki, we will take a look

**Comment by moio** [comment] 2023-11-17 10:18
## Reproduction steps

This issue is about the `clusterdeploy` handler "doing more work than necessary" when clusters are disconnected.

The most straightforward way to observe the issue (and verify a fix works) is by observing specific log lines that correspond to the "unnecessary work", as explained below.


### Requirements

Any Rancher instance with one downstream cluster.

One simple way to set one up is:
```sh
git clone git@github.com:moio/scalability-tests.git
cd scalability-tests
git checkout 05d0076
./bin/setup.mjs && ./bin/run_tests.mjs
```
That will use Terraform to deploy two k3d clusters to the local Docker daemon, use Helm and kubectl to deploy Rancher on the first, and then import the second. Access details will be printed.

Note: `const RANCHER_IMAGE_TAG = "vSPECIFIC_VERSION_HERE"` can be set in `./bin/setup.mjs` to test a specific image version (eg. containing a fix).

### Reproduction Instructions

 - Observe trace logs on a terminal with these instructions:

```bash
kubectl -n cattle-system get pods -l app=rancher --no-headers -o custom-columns=name:.metadata.name | while read rancherpod; do kubectl -n cattle-system exec $rancherpod -c rancher -- loglevel --set trace; done

kubectl logs --namespace cattle-system --selector app=rancher --all-containers=true --since=0 --follow | grep "clusterDeploy: doSync: found"
```

**Expected behavior**: like the following are periodically produced:
```
2023/11/16 13:14:00 [TRACE] clusterDeploy: doSync: found [1] nodes for cluster [c-m-fzblsltr]
```
This tells the `clusterdeploy` handler is working.


 - Stop downstream nodes or disconnect them from the upstream cluster in any way.

If using the above instructions:
```sh
docker pause k3d-st-downstream-0-server-0
```

 - Wait 1 minute, then check:

**Expected behavior**: cluster is reported as disconnected in the Web UI. No `clusterDeploy: doSync: found [XXX] nodes for cluster [YYY]` lines are repeatedly produced in the logging terminal while the cluster stays disconnected. Note: a few initial lines are expected but they should not repeat.

**Actual behavior**: cluster is reported as disconnected in the Web UI. `clusterDeploy: doSync: found [XXX] nodes for cluster [YYY]` lines are repeatedly produced in the logging terminal every ~15 to ~45 seconds while the cluster stays disconnected.

- Start downstream nodes again or restore the connection.

If using the above instructions:
```sh
docker unpause k3d-st-downstream-0-server-0
```

 - Wait 1 minute, then check:

**Expected behavior**: cluster is reported as active in the Web UI. `clusterDeploy: doSync: found [XXX] nodes for cluster [YYY]` appear at least a few times.

**Comment by moio** [comment] 2023-12-15 12:42
## QA Notes

A user using a debug image with this PR applied reported that it broke import of AKS downstream clusters, specifically via the Rancher Terraform provider.

I tested downstream AKS cluster import both manually and via the Rancher Terraform provider and was not able to reproduce the regression - thus I do not have evidence to believe this PR is the actual cause of the regression (if any).

Reproduction instructions:
 - deploy an AKS cluster
 - setup Azure Cloud Credentials in Rancher per https://confluence.suse.com/display/RANQA/Setup+Cloud+Credentials+in+Rancher
 - setup a Rancher API Key per https://ranchermanager.docs.rancher.com/reference-guides/user-settings/api-keys
 - import the clusters via Terraform:

```hcl
terraform {
  required_version = "1.5.6"
  required_providers {
    rancher2 = {
      source  = "rancher/rancher2"
      version = "3.2.0"
    }
  }
}

provider "rancher2" {
  api_url    = "<RANCHER_UI_URL>"
  access_key = "<API_KEY_ACCESS_KEY>"
  secret_key = "<API_KEY_SECRET_KEY>"
  # uncomment for local installations without proper https certs
  # insecure   = true
}

resource "rancher2_cloud_credential" "foo-aks" {
  name = "foo-aks"
  azure_credential_config {
    client_id       = "<CLOUD_CREDENTIAL_CLIEND_ID>"
    client_secret   = "<CLOUD_CREDENTIAL_CLIENT_SECRET>"
    subscription_id = "<CLOUD_CREDENTIAL_SUBSCRIPTION_iD>"
  }
}

resource "rancher2_cluster" "foo" {
  name        = "<DEPLOYED_AKS_CLUSTER_NAME>"
  description = "Terraform AKS cluster"
  aks_config_v2 {
    cloud_credential_id = rancher2_cloud_credential.foo-aks.id
    resource_group      = "<DEPLOYED_AKS_CLUSTER_RESOURCE_GROUP_NAME>"
    resource_location   = "<DEPLOYED_AKS_CLUSTER_LOCATION>"
    imported            = true
  }
}
```

- verify cluster is available and browseable from the main UI


Actual results:

![Screenshot 2023-12-15 at 13 29 25](https://github.com/rancher/rancher/assets/250541/e5afa87e-6750-41e3-a153-ceef0120354d)

Last row is imported via the Rancher Terraform provider.

![Screenshot 2023-12-15 at 10 10 44](https://github.com/rancher/rancher/assets/250541/bd7161d2-163a-48e1-a012-8edfba4774e4)

Check of the image version, contains this patch.

**Comment by erkki** [comment] 2023-12-16 05:33
@moio we have seen a regression in our production too, have not managed to track it down fully yet.

The symptom is that for newly imported clusters, sometimes they get stuck as clusterconnected shows disconnected. 

For some reason, clusterconnected status is not updating (another issue?) while the cluster is actually connected. 

The "fix" is to manually edit the cluster to remove the blocking clusterconnected ready false status, which makes cluster-deploy proceed, and after that the cluster is fine, including connection status.

So skipping work in cluster-deploy is doing what it is supposed to do with this patch, but somewhere there is a connection drop or lack of progress in the clusterconnected controller, which then obviously blocks cluster-deploy.

I have a feeling it is related to our cluster and production load (connections dropping?).

--- Some kind of race between two controllers?

**Comment by moio** [comment] 2023-12-18 16:49
@erkki my reading of the situation is that the `clusterconnected` controller checks on [remotedialer's sessionManager](https://github.com/rancher/remotedialer/blob/master/session_manager.go#L73) to determine whether a downstream cluster is connected or not - it will not attempt a reconnection in case of failure.

When this happens do you perhaps happen to see the following line in your logs?

```
unable to update cluster connected condition
```

**Comment by moio** [comment] 2024-01-05 13:31
@erkki I need your input to move forward as I cannot reproduce the regression in my lab.

Two questions:

1. did I get correctly that the symptom you see, for some imported clusters, is:

```
    Message:           Cluster agent is not connected
    Reason:            Disconnected
    Status:            False
    Type:              Ready
```

(from the output of `kubectl describe clusters.management.cattle.io $YOUR_STUCK_CLUSTER_ID`)

I am asking because there are several conditions with similar names, and I need to be very sure about what you are seeing.

2. if that's right, can you see the Rancher [debug level logs](https://www.suse.com/support/kb/doc/?id=000020239) and see if you find any of these lines:

`Skip updating cluster health - cluster [$YOUR_STUCK_CLUSTER_ID] not provisioned yet`

`Skip updating cluster condition ready - cluster agent for [$YOUR_STUCK_CLUSTER_ID] isn't connected yet`

`[updateClusterHealth] Failed to update cluster [$YOUR_STUCK_CLUSTER_ID]`

Those should be produced every ~15s (if they are produced at all). Full copy of the logs may also help if you can share it.

Reasoning note: I believe the problem lies in the `healthsyncer` controller - specifically [updateClusterHealth](https://github.com/rancher/rancher/blob/b421ea5e0bfeaf899bb28141db85412da68ae49e/pkg/controllers/managementuser/healthsyncer/healthsyncer.go#L150-L167) not concluding successfully, therefore not setting the `Ready` and `Waiting` conditions to true (IIUC that is the only place in the whole codebase where those conditions are cleared). Why that function is returning early, or perhaps does not run at all, I do not know yet.

If none of the above are produced, I can prepare a patch to have Rancher produce more log lines to dig deeper.

**Comment by erkki** [comment] 2024-01-09 13:03
Ack, I will try to chase this now

**Comment by moio** [comment] 2024-03-26 09:05
All concerns above addressed in https://github.com/rancher/rancher/pull/43582, which is now merged.

Passing to QA to do one last pass.

**Comment by git-ival** [comment] 2024-04-16 16:48
Followed repro steps [as described](https://github.com/rancher/rancher/issues/39597#issuecomment-1816099261) on both 2.7.10 and 2.7.12.

Test passed on fix version!
### 2.7.10 Repro:
Scaled down `cattle-cluster-agent` deployment to 0 in order to disconnect the downstream cluster:
![Pasted image 20240416004135](https://github.com/rancher/rancher/assets/85186645/1a76a986-c6e1-4cea-8ed1-693fd8865008)

Got various repeated "cluster deploy" lines:
```
2024/04/16 04:16:30 [TRACE] clusterDeploy: doSync: found [4] nodes for cluster [local]
2024/04/16 04:16:32 [TRACE] clusterDeploy: doSync: found [4] nodes for cluster [local]
2024/04/16 04:16:32 [TRACE] clusterDeploy: doSync: found [4] nodes for cluster [local]
2024/04/16 04:16:43 [TRACE] clusterDeploy: doSync: found [1] nodes for cluster [c-m-f98bsvm2]
2024/04/16 04:17:32 [TRACE] clusterDeploy: doSync: found [1] nodes for cluster [c-m-f98bsvm2]
2024/04/16 04:18:14 [TRACE] clusterDeploy: doSync: found [1] nodes for cluster [c-m-f98bsvm2]
2024/04/16 04:18:36 [TRACE] clusterDeploy: doSync: found [4] nodes for cluster [local]
2024/04/16 04:18:36 [TRACE] clusterDeploy: doSync: found [4] nodes for cluster [local]
```

Scaled up `cattle-cluster-agent` deployment to 1 in order to reconnect the downstream cluster:
![Pasted image 20240416004226](https://github.com/rancher/rancher/assets/85186645/c1bacec6-423d-4739-bd7a-9c197b4fc90f)

Got various repeated "cluster deploy" lines:
```
2024/04/16 04:38:59 [TRACE] clusterDeploy: doSync: found [4] nodes for cluster [local]
2024/04/16 04:38:59 [TRACE] clusterDeploy: doSync: found [4] nodes for cluster [local]
2024/04/16 04:40:09 [TRACE] clusterDeploy: doSync: found [1] nodes for cluster [c-m-f98bsvm2]
2024/04/16 04:41:57 [TRACE] clusterDeploy: doSync: found [4] nodes for cluster [local]
2024/04/16 04:41:57 [TRACE] clusterDeploy: doSync: found [4] nodes for cluster [local]
```

### 2.7.12 Fix:

Scaled down `cattle-cluster-agent` deployment to 0 in order to reconnect the downstream cluster:
![Pasted image 20240416013138](https://github.com/rancher/rancher/assets/85186645/4d805a06-517a-40dd-9c34-ffc6f043316c)

Got various repeated "cluster deploy" lines:
```
2024/04/16 05:15:51 [TRACE] clusterDeploy: doSync: found [1] nodes for cluster [c-m-f98bsvm2]
2024/04/16 05:16:39 [TRACE] clusterDeploy: doSync: found [1] nodes for cluster [c-m-f98bsvm2]
2024/04/16 05:17:23 [TRACE] clusterDeploy: doSync: found [1] nodes for cluster [c-m-f98bsvm2]
2024/04/16 05:17:41 [TRACE] clusterDeploy: doSync: found [4] nodes for cluster [local]
2024/04/16 05:18:08 [TRACE] clusterDeploy: doSync: found [1] nodes for cluster [c-m-f98bsvm2]
2024/04/16 05:18:51 [TRACE] clusterDeploy: doSync: found [1] nodes for cluster [c-m-f98bsvm2]
2024/04/16 05:19:36 [TRACE] clusterDeploy: doSync: found [4] nodes for cluster [local]
2024/04/16 05:19:36 [TRACE] clusterDeploy: doSync: found [4] nodes for cluster [local]
```

Ran into issues with scaling up the `cattle-cluster-agent` deployment due to the image attempting to use the fix image which did not exist in the registry. Had to edit the deployment to utilize the `2.7.12` image in order to reconnect. **Note: It seems that the Rancher deployment keeps resetting any image changes on the `cattle-cluster-agent` deployment which forces an additional agent pod to be scaled in. Had to add the `CATTLE_AGENT_IMAGE` env var to the Rancher deployment to have it stick.
![Pasted image 20240416015553](https://github.com/rancher/rancher/assets/85186645/872e1eaa-3d82-43c7-b79b-30028860c37e)


Did not find any "cluster deploy" logs in the rancher logs output after upgrading and reconnecting the `cattle-cluster-agent`.

**Closed by git-ival** 2024-04-16 16:48 UTC
Labels: kind/bug, area/scalability, [zube]: Team Area 2, team/area2/sc, team/scaling
