### ISSUE TITLE
Add a compliance checking mechanism for UI Banners settings

### ISSUE THREAD

**Issue by sunny0826** [rancher/rancher#26979] opened 2020-05-08 02:15 UTC
**What kind of request is this (question/bug/enhancement/feature request):**
bug

**Steps to reproduce (least amount of steps as possible):**
edit setting of ui-banners
![image](https://user-images.githubusercontent.com/24563928/81362767-3606a500-9114-11ea-944b-0e8b79dbbd7c.png)

**Result:**
rancher UI error.
![image](https://user-images.githubusercontent.com/24563928/81360669-030de280-910f-11ea-86c2-4cc096ffe99e.png)
This problem cannot be solved on the UI page.It can only be resolved by modifying the `etcd` data.

**Other details that may be helpful:**
data of etcd.
![image](https://user-images.githubusercontent.com/24563928/81360735-2cc70980-910f-11ea-9bc2-8a2692839dc6.png)

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI):`rancher/ranche:2.4.3`
- Installation option (single install/HA):single install

**Comment by sangeethah** [comment] 2020-05-08 02:53
We should be able to change the ui-banner using v3/settings - https://github.com/rancher/rancher/issues/26970#issuecomment-625317345

**Comment by superseb** [comment] 2020-06-08 20:15
Duplicate of https://github.com/rancher/rancher/issues/26970

**Closed by superseb** 2020-06-08 20:15 UTC
