### ISSUE TITLE
rancher k3s provisioning tests are consistently panicking and causing failed builds

### ISSUE THREAD

**Issue by rosskirkpat** [rancher/rancher#36791] opened 2022-03-07 23:58 UTC
Rancher is consistently panicking during the k3s provisioning tests in drone. I am seeing the below panics consistently since at least March 5th in drone-pr.

https://drone-pr.rancher.io/rancher/rancher/21262/1/2
https://drone-pr.rancher.io/rancher/rancher/21264/1/2
https://drone-pr.rancher.io/rancher/rancher/21258/1/2
https://drone-pr.rancher.io/rancher/rancher/21250/1/2

```console
Rancher died

Rancher logs were

	/go/src/github.com/rancher/rancher/pkg/controllers/provisioningv2/rke2/unmanaged/controller.go:112 +0x233

github.com/rancher/wrangler/pkg/generated/controllers/core/v1.FromSecretHandlerToHandler.func1({0xc00273a200, 0x33f35106e7d}, {0x47845a0, 0xc00195e280})

	/go/src/github.com/rancher/rancher/go/pkg/mod/github.com/rancher/wrangler@v0.8.11-0.20220217210408-3ecd23dfea3b/pkg/generated/controllers/core/v1/secret.go:102 +0x44

github.com/rancher/lasso/pkg/controller.SharedControllerHandlerFunc.OnChange(0xc00195e280, {0xc00273a200, 0x3fb79ee}, {0x47845a0, 0xc00195e280})

	/go/src/github.com/rancher/rancher/go/pkg/mod/github.com/rancher/lasso@v0.0.0-20220303220250-a429cb5cb9c9/pkg/controller/sharedcontroller.go:29 +0x38

github.com/rancher/lasso/pkg/controller.(*SharedHandler).OnChange(0xc000cdcdc0, {0xc00273a200, 0x20}, {0x47845a0, 0xc00195e280})

	/go/src/github.com/rancher/rancher/go/pkg/mod/github.com/rancher/lasso@v0.0.0-20220303220250-a429cb5cb9c9/pkg/controller/sharedhandler.go:75 +0x23f

github.com/rancher/lasso/pkg/controller.(*controller).syncHandler(0xc000ca58c0, {0xc00273a200, 0x20})

	/go/src/github.com/rancher/rancher/go/pkg/mod/github.com/rancher/lasso@v0.0.0-20220303220250-a429cb5cb9c9/pkg/controller/controller.go:220 +0x93

github.com/rancher/lasso/pkg/controller.(*controller).processSingleItem(0xc000ca58c0, {0x3597980, 0xc00c312210})

	/go/src/github.com/rancher/rancher/go/pkg/mod/github.com/rancher/lasso@v0.0.0-20220303220250-a429cb5cb9c9/pkg/controller/controller.go:201 +0x10e

github.com/rancher/lasso/pkg/controller.(*controller).processNextWorkItem(0xc000ca58c0)

	/go/src/github.com/rancher/rancher/go/pkg/mod/github.com/rancher/lasso@v0.0.0-20220303220250-a429cb5cb9c9/pkg/controller/controller.go:178 +0x46

github.com/rancher/lasso/pkg/controller.(*controller).runWorker(...)

	/go/src/github.com/rancher/rancher/go/pkg/mod/github.com/rancher/lasso@v0.0.0-20220303220250-a429cb5cb9c9/pkg/controller/controller.go:167

k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0x7f2c73badfb0)

	/go/src/github.com/rancher/rancher/go/pkg/mod/k8s.io/apimachinery@v0.23.3/pkg/util/wait/wait.go:155 +0x67

k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0xc0018ca540, {0x4752c40, 0xc003522120}, 0x1, 0xc001aac5a0)

	/go/src/github.com/rancher/rancher/go/pkg/mod/k8s.io/apimachinery@v0.23.3/pkg/util/wait/wait.go:156 +0xb6

k8s.io/apimachinery/pkg/util/wait.JitterUntil(0x0, 0x3b9aca00, 0x0, 0xc0, 0x440b85)

	/go/src/github.com/rancher/rancher/go/pkg/mod/k8s.io/apimachinery@v0.23.3/pkg/util/wait/wait.go:133 +0x89

k8s.io/apimachinery/pkg/util/wait.Until(0xc002d3f758, 0xc002d3f778, 0xc002d3f768)

	/go/src/github.com/rancher/rancher/go/pkg/mod/k8s.io/apimachinery@v0.23.3/pkg/util/wait/wait.go:90 +0x25

created by github.com/rancher/lasso/pkg/controller.(*controller).run

	/go/src/github.com/rancher/rancher/go/pkg/mod/github.com/rancher/lasso@v0.0.0-20220303220250-a429cb5cb9c9/pkg/controller/controller.go:135 +0x2c6
```

**Comment by paynejacob** [comment] 2022-03-09 19:36
@Oats87 with the recent work on ci has this issue been resolved?

**Comment by Oats87** [comment] 2022-03-11 17:06
@paynejacob yes it has, although it's pretty difficult to validate this as it was caused by a race

**Comment by Oats87** [comment] 2022-08-17 21:50
Closing; if it reoccurs, we will reopen the issue.

**Closed by Oats87** 2022-08-17 21:50 UTC
Labels: [zube]: To Test, alpha-priority/0, status/dev-validate, area/provisioning-v2, team/area2, area/clusterprovisioningv2
