### ISSUE TITLE
[BUG] fatal error when exercising API pagination with 10 concurrent simulated users

### ISSUE THREAD

**Issue by moio** [rancher/rancher#40892] opened 2023-03-15 13:54 UTC
**Rancher Server Setup**
- Rancher version: `release/v2.7`branch
- Installation option (Docker install/Helm Chart): Helm chart on k3d

**Information about the Cluster**
- Kubernetes version: `v1.24.10+k3s1`
- Cluster Type (Local/Downstream): local

**User Information**
- What is the role of the user logged in? Admin

**Describe the bug**

Rancher panics with log lines similar to:

```
fatal error: concurrent map writes

goroutine 41133 [running]:
github.com/rancher/wrangler/pkg/data.PutValue(...)
        /Users/SMOIOLI/go/pkg/mod/github.com/rancher/wrangler@v1.1.0/pkg/data/values.go:41
github.com/rancher/steve/pkg/resources/common.formatter.func1(0x14006c2ac30, 0x1400299f4d0)
        /Users/SMOIOLI/go/pkg/mod/github.com/rancher/steve@v0.0.0-20230222210822-3d3cc7767928/pkg/resources/common/formatter.go:104 +0x560
github.com/rancher/apiserver/pkg/types.FormatterChain.func1(0x1400442d830?, 0x140081c40e0?)
        /Users/SMOIOLI/go/pkg/mod/github.com/rancher/apiserver@v0.0.0-20230120214941-e88c32739dc7/pkg/types/server_types.go:317 +0x34
github.com/rancher/apiserver/pkg/writer.(*EncodingResponseWriter).convert(0x10986f540?, 0x14006c2ac30, {{0x140058a6c70, 0x9}, {0x14005be98c0, 0x39}, {0x10a2b1f20, 0x140048cc2b0}, {0x0, 0x0, ...}})
        /Users/SMOIOLI/go/pkg/mod/github.com/rancher/apiserver@v0.0.0-20230120214941-e88c32739dc7/pkg/writer/encoding.go:80 +0x210
github.com/rancher/apiserver/pkg/writer.(*EncodingResponseWriter).convertList(0x14002247cc8?, 0x14006c2ac30, {{0x14005be8faf, 0x6}, {0x0, 0x0}, 0x3, 0x31, {0x14002152400, 0x14, ...}, ...})
        /Users/SMOIOLI/go/pkg/mod/github.com/rancher/apiserver@v0.0.0-20230120214941-e88c32739dc7/pkg/writer/encoding.go:43 +0x17c
github.com/rancher/apiserver/pkg/writer.(*EncodingResponseWriter).BodyList(0x1400291e768, 0x14006c2ac30?, {0x10a31e6a0, 0x1400802c700}, {{0x14005be8faf, 0x6}, {0x0, 0x0}, 0x3, 0x31, ...})
        /Users/SMOIOLI/go/pkg/mod/github.com/rancher/apiserver@v0.0.0-20230120214941-e88c32739dc7/pkg/writer/encoding.go:37 +0x90
github.com/rancher/apiserver/pkg/writer.(*EncodingResponseWriter).WriteList(0x14006c2ac30?, 0x14006c2ac30, 0x0?, {{0x14005be8faf, 0x6}, {0x0, 0x0}, 0x3, 0x31, {0x14002152400, ...}, ...})
        /Users/SMOIOLI/go/pkg/mod/github.com/rancher/apiserver@v0.0.0-20230120214941-e88c32739dc7/pkg/writer/encoding.go:29 +0xb8
github.com/rancher/apiserver/pkg/writer.(*GzipWriter).WriteList(0x1400044a9e0, 0x0?, 0x3?, {{0x14005be8faf, 0x6}, {0x0, 0x0}, 0x3, 0x31, {0x14002152400, ...}, ...})
        /Users/SMOIOLI/go/pkg/mod/github.com/rancher/apiserver@v0.0.0-20230120214941-e88c32739dc7/pkg/writer/gzip.go:42 +0xec
github.com/rancher/apiserver/pkg/types.(*APIRequest).WriteResponseList(0x14002248208?, 0x14006c2ac30?, {{0x14005be8faf, 0x6}, {0x0, 0x0}, 0x3, 0x31, {0x14002152400, 0x14, ...}, ...})
        /Users/SMOIOLI/go/pkg/mod/github.com/rancher/apiserver@v0.0.0-20230120214941-e88c32739dc7/pkg/types/server_types.go:170 +0xb8
github.com/rancher/apiserver/pkg/server.(*Server).handle(0x14002136a80, 0x14006c2ac30, 0x14006c2ac30?)
        /Users/SMOIOLI/go/pkg/mod/github.com/rancher/apiserver@v0.0.0-20230120214941-e88c32739dc7/pkg/server/server.go:150 +0x688
github.com/rancher/apiserver/pkg/server.(*Server).Handle(...)
        /Users/SMOIOLI/go/pkg/mod/github.com/rancher/apiserver@v0.0.0-20230120214941-e88c32739dc7/pkg/server/server.go:101
github.com/rancher/steve/pkg/server/handler.(*apiServer).apiHandler.func1({0x10a356b20?, 0x1400802c700?}, 0x1093dd301?)
```

**To Reproduce**

 - set up a k3d cluster (I believe this is actually reproducible with any supported local cluster)
 - run Rancher from the `release/v2.7` branch (I believe this is actually reproducible with any version that uses steve with https://github.com/rancher/steve/pull/63/ merged) according to [developer instructions](https://github.com/rancher/rancher/wiki/Setting-Up-Rancher-2.0-Development-Environment)
 - log in the first time to set an admin password
 - as the admin user, repeatedly and concurrently hit the `GET /v1/configmaps?pagesize=10&page=N` Steve endpoint, varying N to simulate pagination movements. I can reliably reproduce this problem via [a k6 script simulating 10 users for 30 requests each](https://gist.github.com/moio/b9d2a18820eff7cdd62e5267f6d3a860)

```sh
wget https://gist.githubusercontent.com/moio/b9d2a18820eff7cdd62e5267f6d3a860/raw/d76e8c3f05f5995f04fb3d340c2b6637f30470db/stress_steve_new_pagination.js

k6 run -e BASEURL=https://localhost:8443 -e USERNAME=admin -e PASSWORD=adminadminadmin -e CLUSTER=local  ./stress_steve_new_pagination.js
```

([k6 is Grafana's load generation tool](https://k6.io))

Note that running Rancher with `CATTLE_REQUEST_CACHE_DISABLED=true` prevents the bug and is a valid workaround.

**Result**

**Expected Result**

No http errors reported by k6, Rancher still up.

**Comment by git-ival** [comment] 2023-07-26 04:50
Reproduced on K3s and RKE1 using `release/v2.7` branch. 

Tested on latest `2.7.5` release and could not reproduce. Closing this issue as test passed.

Observed various panic logs throughout running the pagination script on the reproduction environment. Example logs as follows:
```
goroutine 5208 [sync.Cond.Wait, 24 minutes]:
sync.runtime_notifyListWait(0xc0010fc050, 0x224)
        /usr/lib64/go/1.19/src/runtime/sema.go:517 +0x14c
sync.(*Cond).Wait(0x3ad6c00?)
        /usr/lib64/go/1.19/src/sync/cond.go:70 +0x8c
k8s.io/client-go/util/workqueue.(*Type).Get(0xc0035ef260)
        /go/pkg/mod/github.com/rancher/client-go@v1.25.4-rancher1/util/workqueue/queue.go:157 +0x9e
github.com/rancher/lasso/pkg/controller.(*controller).processNextWorkItem(0xc0005ebce0)
        /go/pkg/mod/github.com/rancher/lasso@v0.0.0-20221227210133-6ea88ca2fbcc/pkg/controller/controller.go:185 +0x2e
github.com/rancher/lasso/pkg/controller.(*controller).runWorker(0xc002ad7ea0?)
        /go/pkg/mod/github.com/rancher/lasso@v0.0.0-20221227210133-6ea88ca2fbcc/pkg/controller/controller.go:180 +0x25
k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0x6e65747865?)
        /go/pkg/mod/k8s.io/apimachinery@v0.25.4/pkg/util/wait/wait.go:157 +0x3e
k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0x7d7d7b3a2272616c?, {0x4813ee0, 0xc001504cf0}, 0x1, 0xc001831b00)
        /go/pkg/mod/k8s.io/apimachinery@v0.25.4/pkg/util/wait/wait.go:158 +0xb6
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0x7b3a22656d69546e?, 0x3b9aca00, 0x0, 0x2c?, 0x222c7d7b3a226e6f?)
        /go/pkg/mod/k8s.io/apimachinery@v0.25.4/pkg/util/wait/wait.go:135 +0x89
k8s.io/apimachinery/pkg/util/wait.Until(0x7d7b3a2265707974?, 0x225c7b3a6b222c7d?, 0x5c3a225c65707974?)
        /go/pkg/mod/k8s.io/apimachinery@v0.25.4/pkg/util/wait/wait.go:92 +0x25
created by github.com/rancher/lasso/pkg/controller.(*controller).run
        /go/pkg/mod/github.com/rancher/lasso@v0.0.0-20221227210133-6ea88ca2fbcc/pkg/controller/controller.go:148 +0x2a7

goroutine 5209 [sync.Cond.Wait, 24 minutes]:
sync.runtime_notifyListWait(0xc0010fc050, 0x212)
        /usr/lib64/go/1.19/src/runtime/sema.go:517 +0x14c
sync.(*Cond).Wait(0x3ad6c00?)
        /usr/lib64/go/1.19/src/sync/cond.go:70 +0x8c
k8s.io/client-go/util/workqueue.(*Type).Get(0xc0035ef260)
        /go/pkg/mod/github.com/rancher/client-go@v1.25.4-rancher1/util/workqueue/queue.go:157 +0x9e
github.com/rancher/lasso/pkg/controller.(*controller).processNextWorkItem(0xc0005ebce0)
        /go/pkg/mod/github.com/rancher/lasso@v0.0.0-20221227210133-6ea88ca2fbcc/pkg/controller/controller.go:185 +0x2e
github.com/rancher/lasso/pkg/controller.(*controller).runWorker(0xc002ad86a0?)
        /go/pkg/mod/github.com/rancher/lasso@v0.0.0-20221227210133-6ea88ca2fbcc/pkg/controller/controller.go:180 +0x25
k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0x7574636574?)
        /go/pkg/mod/k8s.io/apimachinery@v0.25.4/pkg/util/wait/wait.go:157 +0x3e
k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0x6974706972637365?, {0x4813ee0, 0xc0017f3710}, 0x1, 0xc001831b00)
        /go/pkg/mod/k8s.io/apimachinery@v0.25.4/pkg/util/wait/wait.go:158 +0xb6
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0x6666617274206472?, 0x3b9aca00, 0x0, 0x6c?, 0x617254746f4e6f64?)
        /go/pkg/mod/k8s.io/apimachinery@v0.25.4/pkg/util/wait/wait.go:135 +0x89
k8s.io/apimachinery/pkg/util/wait.Until(0x6f4e6f44223a226e?, 0x69206b6361725474?, 0x736574616369646e?)
        /go/pkg/mod/k8s.io/apimachinery@v0.25.4/pkg/util/wait/wait.go:92 +0x25
created by github.com/rancher/lasso/pkg/controller.(*controller).run
        /go/pkg/mod/github.com/rancher/lasso@v0.0.0-20221227210133-6ea88ca2fbcc/pkg/controller/controller.go:148 +0x2a7
```

k6 output for the reproduction environment:
![pagination-repro](https://github.com/rancher/rancher/assets/85186645/ab69cc49-2d3b-429a-993b-e58116c26815)

Test steps:
1. Set up local Rancher cluster
	- Used k8s `1.24.13` and `1.25.9`
2. Login with admin user
3. Let idle for ~5 minutes
4. Begin following rancher logs
5. Run `stress_steve_new_pagination.js` k6 test
6. Observe that there is no Rancher panic logging 

k6 output for the validation environments:
![pagination-validation](https://github.com/rancher/rancher/assets/85186645/13ca61bf-0ca7-4810-8ec4-8c23383b5359)

**Closed by git-ival** 2023-07-26 04:50 UTC
Labels: kind/bug
