### ISSUE TITLE
Cattle server crashes from bad cluster data

### ISSUE THREAD

**Issue by alexandrem** [rancher/rancher#16127] opened 2018-10-15 01:42 UTC
**Rancher versions:**
rancher/server or rancher/rancher: v2.0.7 and v2.1.0

**Steps to Reproduce:**

During a disaster recovery procedure, I had to restore a previous snapshot of etcd and relaunch Rancher on top of it.

I did a restore one evening and during the next hours (not clear when exactly), cattle server went into a continuous crash loop.

It appears that there was a single cluster resource object (and likely the related data as well) that caused a continuous crash of the Rancher controller code, making Rancher completely unusable.

I tested both on v2.0.7 (the release when the snapshot was taken) and also v2.1.0 to see if it could recover with a newer version, but it didn't help.

I managed to locate the cluster object to remove to avoid this problematic situation.
I removed all finalizers on the cluster resource and deleted it via kubectl, then Rancher cattle server has been happy ever since.

I tested multiple etcd snapshots from specific date in different hours and it would always cause this.
I also tested from a Ark backup of a day before with the same outcome.

I went through all `clusters.management.cattle.io/cluster` from the Ark backup and located the one who would trigger this. Then I simply omitted this resource file and all other were ingested back into the system and all was good.

Here's the cluster object after it was loaded when it was crashing with a few omissions

```yaml
apiVersion: management.cattle.io/v3
kind: Cluster
metadata:
  annotations:
    authz.management.cattle.io/creator-role-bindings: '{"created":["cluster-owner"],"required":["cluster-owner"]}'
    field.cattle.io/creatorId: user-cqm2z
    lifecycle.cattle.io/create.cluster-agent-controller: "true"
    lifecycle.cattle.io/create.cluster-agent-controller-cleanup: "true"
    lifecycle.cattle.io/create.cluster-provisioner-controller: "true"
    lifecycle.cattle.io/create.cluster-scoped-gc: "true"
    lifecycle.cattle.io/create.mgmt-cluster-rbac-remove: "true"
  clusterName: ""
  creationTimestamp: 2018-10-12T18:20:30Z
  finalizers: []
  generation: 1
  name: c-g6wm6
  namespace: ""
  resourceVersion: "94754365"
  selfLink: /apis/management.cattle.io/v3/clusters/c-g6wm6
  uid: 8011da9a-ce4b-11e8-b602-fa163e756dcf
spec:
  description: ""
  desiredAgentImage: ""
  displayName: OMITTED
  dockerRootDir: /var/lib/docker
  enableNetworkPolicy: false
  internal: false
  rancherKubernetesEngineConfig:
    addonJobTimeout: 30
    authentication:
      strategy: x509
    authorization: {}
    bastionHost: {}
    cloudProvider:
      name: openstack
      openstackCloudProvider:
        blockStorage:
          bs-version: ""
          ignore-volume-az: false
          trust-device-path: false
        global:
          OMITTED
        loadBalancer:
          create-monitor: false
          floating-network-id: ""
          lb-method: ""
          lb-provider: ""
          lb-version: ""
          manage-security-groups: false
          monitor-delay: 0
          monitor-max-retries: 0
          monitor-timeout: 0
          subnet-id: ""
          use-octavia: false
        metadata:
          request-timeout: 0
          search-order: ""
        route:
          router-id: ""
    ignoreDockerVersion: true
    ingress:
      provider: none
    kubernetesVersion: v1.11.1-rancher1-1
    monitoring:
      provider: metrics-server
    network:
      plugin: calico
    services:
      etcd:
        extraArgs:
          election-timeout: "5000"
          heartbeat-interval: "500"
      kubeApi: {}
      kubeController: {}
      kubelet:
        extraArgs:
          read-only-port: "10255"
      kubeproxy: {}
      scheduler: {}
    sshAgentAuth: false
    systemImages: {}
status:
  agentImage: rancher/rancher:v2.0.7
  allocatable:
    cpu: "12"
    memory: 22656984Ki
    pods: "330"
  apiEndpoint: https://10.43.0.1:443
  appliedEnableNetworkPolicy: false
  appliedPodSecurityPolicyTemplateId: ""
  appliedSpec:
    description: ""
    desiredAgentImage: ""
    displayName: OMITTED
    dockerRootDir: /var/lib/docker
    enableNetworkPolicy: false
    internal: false
    rancherKubernetesEngineConfig:
      addonJobTimeout: 30
      authentication:
        strategy: x509
      authorization: {}
      bastionHost: {}
      cloudProvider:
        name: openstack
        openstackCloudProvider:
          blockStorage:
            bs-version: ""
            ignore-volume-az: false
            trust-device-path: false
          global:
            OMITTED
          loadBalancer:
            create-monitor: false
            floating-network-id: ""
            lb-method: ""
            lb-provider: ""
            lb-version: ""
            manage-security-groups: false
            monitor-delay: 0
            monitor-max-retries: 0
            monitor-timeout: 0
            subnet-id: ""
            use-octavia: false
          metadata:
            request-timeout: 0
            search-order: ""
          route:
            router-id: ""
      ignoreDockerVersion: true
      ingress:
        provider: none
      kubernetesVersion: v1.11.1-rancher1-1
      monitoring:
        provider: metrics-server
      network:
        plugin: calico
      nodes:
      - address: 10.130.64.36
        hostnameOverride: k8s-nova-wrkr1
        nodeName: c-g6wm6:m-cztdm
        port: "22"
        role:
        - worker
        sshKey: |
          OMITTED
        user: core
      - address: 10.130.65.219
        hostnameOverride: k8s-nova-ctrl3
        nodeName: c-g6wm6:m-dlhxn
        port: "22"
        role:
        - controlplane
        - etcd
        sshKey: |
          OMITTED
        user: core
      - address: 10.130.66.144
        hostnameOverride: k8s-nova-wrkr3
        nodeName: c-g6wm6:m-rfsm7
        port: "22"
        role:
        - worker
        sshKey: |
          OMITTED
        user: core
      - address: 10.130.66.135
        hostnameOverride: k8s-nova-ctrl1
        nodeName: c-g6wm6:m-sjjrj
        port: "22"
        role:
        - controlplane
        - etcd
        sshKey: |
          OMITTED
        user: core
      - address: 10.130.65.218
        hostnameOverride: k8s-nova-wrkr2
        nodeName: c-g6wm6:m-xpj7b
        port: "22"
        role:
        - worker
        sshKey: |
          OMITTED
        user: core
      services:
        etcd:
          extraArgs:
            election-timeout: "5000"
            heartbeat-interval: "500"
        kubeApi: {}
        kubeController: {}
        kubelet:
          extraArgs:
            read-only-port: "10255"
        kubeproxy: {}
        scheduler: {}
      sshAgentAuth: false
      systemImages:
        alpine: rancher/rke-tools:v0.1.13
        calicoCni: rancher/calico-cni:v3.1.1
        calicoCtl: rancher/calico-ctl:v2.0.0
        calicoNode: rancher/calico-node:v3.1.1
        canalCni: rancher/calico-cni:v3.1.1
        canalFlannel: rancher/coreos-flannel:v0.9.1
        canalNode: rancher/calico-node:v3.1.1
        certDownloader: rancher/rke-tools:v0.1.13
        dnsmasq: rancher/k8s-dns-dnsmasq-nanny-amd64:1.14.10
        etcd: rancher/coreos-etcd:v3.2.18
        flannel: rancher/coreos-flannel:v0.9.1
        flannelCni: rancher/coreos-flannel-cni:v0.2.0
        ingress: rancher/nginx-ingress-controller:0.16.2-rancher1
        ingressBackend: rancher/nginx-ingress-controller-defaultbackend:1.4
        kubedns: rancher/k8s-dns-kube-dns-amd64:1.14.10
        kubednsAutoscaler: rancher/cluster-proportional-autoscaler-amd64:1.0.0
        kubednsSidecar: rancher/k8s-dns-sidecar-amd64:1.14.10
        kubernetes: rancher/hyperkube:v1.11.1-rancher1
        kubernetesServicesSidecar: rancher/rke-tools:v0.1.13
        metricsServer: rancher/metrics-server-amd64:v0.2.1
        nginxProxy: rancher/rke-tools:v0.1.13
        podInfraContainer: rancher/pause-amd64:3.1
        weaveCni: weaveworks/weave-npc:2.1.2
        weaveNode: weaveworks/weave-kube:2.1.2
  caCert: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUN3akNDQWFxZ0F3SUJBZ0lCQURBTkJna3Foa2lHOXcwQkFRc0ZBREFTTVJBd0RnWURWUVFERXdkcmRXSmwKTFdOaE1CNFhEVEU0TURreE5ERTNOVEF3T0ZvWERUSTRNRGt4TVRFM05UQXdPRm93RWpFUU1BNEdBMVVFQXhNSAphM1ZpWlMxallUQ0NBU0l3RFFZSktvWklodmNOQVFFQkJRQURnZ0VQQURDQ0FRb0NnZ0VCQUw5S3pCbGVBYXF1Cnk4b0NIMURucU1ENDIvU0JTVnJNb1hsVm5tQ01NS1R1QjJqbGFQUjNZdWlmL29ZZGVMVmNQTjQ2bjY3akI1NzQKR1k4b2pOU2tSNlhyUnJUbmlmTElvSXNvKzVvczRwazl2amZIVDNReU1LeFFnYVlnaHBqK0xDdnlDYVVKWTBSZwoyK3ZYOEIzVFZ3Vk9xcitEK2YvRHl3RXI0SWxSUThhSU5lUFAvSERPWEJ2bCtnM2YvQU9CNkxneW1lSnFTR1NLCjkvQlY1Y2l2U0swb1J1aFpaOWM4VldEWVg0VmIySDUweWliRXhqcUl3c0Y1RW5kQWVyNXo0VXR5aGFReFk3dG8KVXYzdS8yaWhCRzRRUHV6UHlhSFJ2NmVKZGpGaE9ab3VJS3ZKM3lkbGp0QmdYcDYrQmlNdThpdDd3a25aR2RhOQo1eVBabWlVQ0dXY0NBd0VBQWFNak1DRXdEZ1lEVlIwUEFRSC9CQVFEQWdLa01BOEdBMVVkRXdFQi93UUZNQU1CCkFmOHdEUVlKS29aSWh2Y05BUUVMQlFBRGdnRUJBSERUa2kwSkxOQTQ5bW03SS96RC9KQi9TTWI3YXM5Q0RuMmcKbExpbFQvY0F2R25vUU16T0tYT0piWlI2RUZva0RtN1NlR1pPSlpORC8rZ2RSTTRicUIyaVMwT2pmMlArUFFlYwpDb0JGUFQvTGdVVTd3Z0VadlpjbkVDaXdwMWpTUnNFTG5kWnFpeGE5NVlQRGx2RFAzUllhY1JoVCtDWEdZdmVaClUyeHIrTEM0Vy9sdVBQdTE3ZjY4bVAxUjNFRkIzVEgzT0k3ZzI1c0I5eTRhZEkzUEtsMnc3Q3Z0dVR4QjlPQ1gKanB3V1ErLy9pQThzL2QwRlN2cFlzRG5kUmhMalVuc0Q5ZlNyNithYXZBdmF0d3RGaXIvcjlPQkJkb1ZKd24zbwordEtZT3ZpL0tnM0ZoY3RaUklDS0lUMU5HdG8yaWpMZEFYN1BnVFNuZWhvRzlVRktwWWM9Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
  capacity:
    cpu: "12"
    memory: 22964184Ki
    pods: "330"
  componentStatuses:
  - conditions:
    - message: ok
      status: "True"
      type: Healthy
    name: controller-manager
  - conditions:
    - message: '{"health": "true"}'
      status: "True"
      type: Healthy
    name: etcd-0
  - conditions:
    - message: '{"health": "true"}'
      status: "True"
      type: Healthy
    name: etcd-1
  - conditions:
    - message: '{"health": "true"}'
      status: "True"
      type: Healthy
    name: etcd-2
  - conditions:
    - message: ok
      status: "True"
      type: Healthy
    name: scheduler
  conditions:
  - lastUpdateTime: 2018-10-12T18:20:30Z
    status: "True"
    type: BackingNamespaceCreated
  - lastUpdateTime: 2018-10-12T18:20:30Z
    status: "True"
    type: DefaultProjectCreated
  - lastUpdateTime: 2018-10-12T18:20:30Z
    status: "True"
    type: SystemProjectCreated
  - lastUpdateTime: 2018-10-12T18:20:30Z
    status: "True"
    type: InitialRolesPopulated
  - lastUpdateTime: 2018-10-12T18:20:53Z
    status: "True"
    type: Updated
  - lastUpdateTime: 2018-10-12T18:20:53Z
    status: "True"
    type: Provisioned
  - lastUpdateTime: 2018-10-12T18:20:53Z
    status: "True"
    type: Pending
  - lastUpdateTime: 2018-10-12T18:20:53Z
    status: "True"
    type: CreatorMadeOwner
  - lastUpdateTime: 2018-10-12T18:20:53Z
    status: "True"
    type: GlobalAdminsSynced
  - lastUpdateTime: 2018-10-12T18:21:00Z
    status: "True"
    type: NoDiskPressure
  - lastUpdateTime: 2018-10-12T18:21:00Z
    status: "True"
    type: NoMemoryPressure
  - lastUpdateTime: 2018-10-12T18:21:08Z
    status: "True"
    type: Ready
  - lastUpdateTime: 2018-10-12T18:21:08Z
    status: "True"
    type: Waiting
  - lastUpdateTime: 2018-10-12T18:21:13Z
    status: "True"
    type: SystemAccountCreated
  - lastUpdateTime: 2018-10-12T18:21:50Z
    status: "True"
    type: AgentDeployed
  driver: imported
  limits:
    cpu: 13600m
    memory: 11732Mi
    pods: "0"
  requested:
    cpu: 5230m
    memory: 6822Mi
    pods: "49"
  serviceAccountToken: eyJhbGciOiJSUzI1NiIsImtpZCI6IiJ9.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJjYXR0bGUtc3lzdGVtIiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9zZWNyZXQubmFtZSI6ImNhdHRsZS10b2tlbi01bmhyayIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VydmljZS1hY2NvdW50Lm5hbWUiOiJjYXR0bGUiLCJrdWJlcm5ldGVzLmlvL3NlcnZpY2VhY2NvdW50L3NlcnZpY2UtYWNjb3VudC51aWQiOiJkZWIxMDZkOS1iODQ2LTExZTgtOWY4Ny1mYTE2M2UxN2FhN2UiLCJzdWIiOiJzeXN0ZW06c2VydmljZWFjY291bnQ6Y2F0dGxlLXN5c3RlbTpjYXR0bGUifQ.eZ1DaXoNofHxX3O7tBflGE6xp9K3Q_nbvA0uxbRuzwmHh0HzE0iJz6D-CWPmDZB16101M2a1Mbzs7Di1GqaYMT9mokGQywvX-QJBHMjSxpvGgotWtR3b4BSCCfiaSpUxmt3MJ_hbP3GaTFTLd7bKnSidv9Ip5KEjmpb998gV49yWmsnmWKorxK4vvf2fApYf7mYby2dNudsMvbgoDSphV0lEMOLTggfzhnR3fXifE0nKtWo9wPS-bCDzgPGk0QsM91vpVuLp4Bdft3V9jCjShxB_LAzOcq0xsAp2YD2a3YBhi-Fpg8fXgtSVSM-OYiKmowSanYFec8EXgFRBwF5AUA
  version:
    buildDate: 2018-07-17T18:43:26Z
    compiler: gc
    gitCommit: b1b29978270dc22fecc592ac55d903350454310a
    gitTreeState: clean
    gitVersion: v1.11.1
    goVersion: go1.10.3
    major: "1"
    minor: "11"
    platform: linux/amd64
```

I suppose the best thing would be to locate all related resource files that the controllers look for and attempt to reproduce this in a test environment.

I can provide the other cattle resources if needed, which is probably required for investigation.

**Results:**

The crash dump:

```
panic: reflect: call of reflect.Value.Type on zero Value

goroutine 19457 [running]:
reflect.Value.Type(0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/reflect/value.go:1694 +0x1a3
github.com/rancher/rancher/vendor/github.com/rancher/norman/condition.getValue(0x531c460, 0x0, 0xc4a1688a68, 0x2, 0x2, 0x1d, 0xc4a1688af0, 0x447418)
	/go/src/github.com/rancher/rancher/vendor/github.com/rancher/norman/condition/condition.go:249 +0x1f2
github.com/rancher/rancher/vendor/github.com/rancher/norman/condition.findOrNotCreateCond(0x531c460, 0x0, 0x53ceb00, 0x5, 0x15)
	/go/src/github.com/rancher/rancher/vendor/github.com/rancher/norman/condition/condition.go:211 +0x74
github.com/rancher/rancher/vendor/github.com/rancher/norman/condition.getStatus(0x531c460, 0x0, 0x53ceb00, 0x5, 0xc49d0a5480, 0x1d)
	/go/src/github.com/rancher/rancher/vendor/github.com/rancher/norman/condition/condition.go:177 +0x50
github.com/rancher/rancher/vendor/github.com/rancher/norman/condition.Cond.IsTrue(0x53ceb00, 0x5, 0xbff6d80, 0x0, 0x1)
	/go/src/github.com/rancher/rancher/vendor/github.com/rancher/norman/condition/condition.go:20 +0x52
github.com/rancher/rancher/pkg/controllers/user/alert/watcher.(*NodeWatcher).checkNodeMemUsage(0xc4208e5420, 0xc468cd9e90, 0x0)
	/go/src/github.com/rancher/rancher/pkg/controllers/user/alert/watcher/node.go:141 +0xea
github.com/rancher/rancher/pkg/controllers/user/alert/watcher.(*NodeWatcher).checkNodeCondition(0xc4208e5420, 0xc468cd9e90, 0x0)
	/go/src/github.com/rancher/rancher/pkg/controllers/user/alert/watcher/node.go:133 +0xc9
github.com/rancher/rancher/pkg/controllers/user/alert/watcher.(*NodeWatcher).watchRule(0xc4208e5420, 0xc4357c2f98, 0x6fc23ac01)
	/go/src/github.com/rancher/rancher/pkg/controllers/user/alert/watcher/node.go:112 +0x5e3
github.com/rancher/rancher/pkg/controllers/user/alert/watcher.(*NodeWatcher).watch(0xc4208e5420, 0xc02b0c0, 0xc448add680, 0x6fc23ac00)
	/go/src/github.com/rancher/rancher/pkg/controllers/user/alert/watcher/node.go:48 +0xbb
created by github.com/rancher/rancher/pkg/controllers/user/alert/watcher.StartNodeWatcher
	/go/src/github.com/rancher/rancher/pkg/controllers/user/alert/watcher/node.go:43 +0x35c
```

**Comment by superseb** [comment] 2018-10-15 07:42
Fixed in https://github.com/rancher/rancher/issues/16000

@cjellick @alena1108 can you double check that this is the same root cause?

**Closed by superseb** 2018-10-15 07:42 UTC
