### ISSUE TITLE
Clusters deleted immediately from Cluster Management page but not from Home page

### ISSUE THREAD

**Issue by sowmyav27** [rancher/rancher#33774] opened 2021-07-21 23:42 UTC
**On master-head commit id: `b6bcfad`**

- Deploy an RKE1 cluster.
- Delete the cluster from cluster management page
- the cluster immediately goes away from this page list.
- Navigate to Home page in dashboard.
- Cluster is seen in `Removing` state - removing resources 

**Expected:**
Cluster should get removed after removing the resources. Behavior seen in Home page is the right way.

Can we defer the provisioning delete until management delete is done ?

**Comment by cbron** [comment] 2021-07-28 16:59
I think we should bump this one. Potential solution is to not delete the provisioning cluster object (in the backend) until the management cluster object is gone.

**Comment by deniseschannon** [comment] 2021-07-28 20:32
With the new cluster objects introduced with the new provisioning framework, there are multiple objects that need to be deleted and the UI is reading various cluster objects which are slowly being deleted.

**Comment by deniseschannon** [comment] 2021-07-28 20:32
Adding a finalizer could fix this, but it could trigger some status updates.

**Comment by thedadams** [comment] 2021-09-01 20:51
I believe this was fixed by https://github.com/rancher/rancher/pull/34501, but I will double-check before moving to "To Test"

**Comment by thedadams** [comment] 2021-09-01 21:31
This looks like it was indeed fixed by https://github.com/rancher/rancher/pull/34501

**Comment by davidnuzik** [comment] 2021-09-09 17:59
**My checks PASSED**
 
**Reproduction Steps:**

Not required.

-----
 
**Validation Environment:**

Rancher version: v2.6-head `a6e7905` pulled 9/9/21 10:37am Pacific
Rancher cluster type: single-node docker install
Docker version: 20.10
 
Downstream cluster type: rke1
Downstream K8s version: v1.21.4-rancher1-1
 
**Validation steps:**

1. Create an RKE1 cluster wait for it to fully come up (active state).
2. Delete the cluster from the cluster management page.
3. It goes into a removing state briefly. Go to the home page this state/status is in sync.
4. Come back to cluster management page wait for it to be removed. Once it is immediately go to home page.
5. It is indeed immediately removed from the home page.

**Comment by thedadams** [comment] 2021-09-17 23:36
This was reopened because the implementation is changing.

To clarify, deletion of the management cluster object (the one displayed on the Home page) and the provisioning cluster object (the one displayed from the "Cluster Management" page) should now be deleted within 5 seconds of each other regardless of RKE1 or RKE2 clusters.

**Comment by davidnuzik** [comment] 2021-09-21 21:13
**My checks PASSED**
 
**Reproduction Steps:**

Not required.

-----
 
**Validation Environment:**

Rancher version: v2.6-head `ba43472` pulled at 9/21/21 10:43am
Rancher cluster type: single-node docker install
Docker version: 20.10
 
Downstream cluster type: rke1 AND rke2 _(only rke1 was tested in my last comment, the new implementation/PR looks like it should handle this better. Also, it should work for either RKE1 or RKE2 clusters now as Donnie mentioned in the prior comment)._
Downstream K8s version: v1.21.5-rancher1-1 (rke1) and v1.21.4+rke2r2 (rke2)
 
**Validation steps:**

1. Create an RKE1 cluster wait for it to fully come up (active state).
2. Delete the cluster from the cluster management page.
3. It goes into a removing state briefly. Go to the home page this state/status is in sync.
4. Come back to cluster management page wait for it to be removed. Once it is immediately go to home page.
5. It is indeed immediately removed from the home page.
6. Test again but with an RKE2 cluster. This also works.

Note: In fact it seems like the cluster gets removed from the home page first (almost immediately), then the cluster management page. This seems fine to me. Basically I delete from the cluster management page check the home page and it's gone immediately, come back to the cluster management page and the cluster may still be deleting. After a few more seconds it gets removed from the cluster management page as well. The do both get deleted within approximately 5 seconds of each other based on my testing with single-node rke1/rke2 clusters.

**Closed by davidnuzik** 2021-09-21 21:13 UTC
Labels: kind/bug-qa, [zube]: QA Working
