### ISSUE TITLE
go-machine-service, rancher-compose-executor aren't managed properly by cattle

### ISSUE THREAD

**Issue by cjellick** [rancher/rancher#6092] opened 2016-09-30 16:43 UTC
go-machine-service container got to stopped state and cattle did not restart it. Similar to https://github.com/rancher/rancher/issues/5775, but not related to an upgrade.

**Rancher Version:**
1.1.4

**Docker Version:**

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
Rancher HA

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
The HA environment

**Steps to Reproduce:**
Unknown, but here are the logs of the gms container in question:

```
9/30/2016 4:32:51 AMtime="2016-09-30T03:32:51Z" level=info msg="Listening on 0.0.0.0:80"
9/30/2016 4:32:51 AMtime="2016-09-30T03:32:51Z" level=info msg="Forwarding setup to: :80"
9/30/2016 5:00:04 PMtime="2016-09-30T16:00:04Z" level=info msg="Listening on port: 80"
9/30/2016 5:00:04 PMtime="2016-09-30T16:00:04Z" level=info msg="Setting log level" logLevel=info
9/30/2016 5:00:04 PMtime="2016-09-30T16:00:04Z" level=info msg="Starting go-machine-service..." gitcommit=v0.31.7
9/30/2016 5:00:04 PMtime="2016-09-30T16:00:04Z" level=info msg="Waiting for handler registration (1/2)"
9/30/2016 5:00:16 PMtime="2016-09-30T16:00:16Z" level=fatal msg="Exiting go-machine-service: Timed out waiting for transtion."
9/30/2016 5:00:16 PMtime="2016-09-30T16:00:16Z" level=fatal msg="exit status 1"
9/30/2016 5:28:28 PMtime="2016-09-30T16:28:28Z" level=info msg="Listening on 0.0.0.0:80"
9/30/2016 5:28:28 PMtime="2016-09-30T16:28:28Z" level=info msg="Forwarding setup to: :80"
9/30/2016 5:28:29 PMtime="2016-09-30T16:28:29Z" level=info msg="Listening on port: 80"
9/30/2016 5:28:29 PMtime="2016-09-30T16:28:29Z" level=info msg="Setting log level" logLevel=info
9/30/2016 5:28:29 PMtime="2016-09-30T16:28:29Z" level=info msg="Starting go-machine-service..." gitcommit=v0.31.7
9/30/2016 5:28:29 PMtime="2016-09-30T16:28:29Z" level=info msg="Waiting for handler registration (1/2)"
9/30/2016 5:28:38 PMtime="2016-09-30T16:28:38Z" level=info msg="Initializing event router" workerCount=10
9/30/2016 5:28:38 PMtime="2016-09-30T16:28:38Z" level=info msg="Connection established"
9/30/2016 5:28:38 PMtime="2016-09-30T16:28:38Z" level=info msg="Starting websocket pings"
9/30/2016 5:28:38 PMtime="2016-09-30T16:28:38Z" level=info msg="Waiting for handler registration (2/2)"
9/30/2016 5:28:40 PMtime="2016-09-30T16:28:40Z" level=fatal msg="Exiting go-machine-service: Timed out waiting for transtion."
9/30/2016 5:28:40 PMtime="2016-09-30T16:28:40Z" level=fatal msg="exit status 1"
```

**Results:** 
Container stays in stopped state. Service is degraded

**Expected:**
Cattle should resolve the problem by resarting or replacing the stopped container.

**Comment by janeczku** [comment] 2016-10-18 12:14
Duplicate of https://github.com/rancher/rancher/issues/5775

**Comment by alena1108** [comment] 2016-10-24 17:11
I know it is not easy to reproduce, just keep an eye on it when you test HA setup

**Comment by deniseschannon** [comment] 2016-11-29 21:58
As HA has been refactored for v1.2, this is no longer applicable. They should be running automatically in regular rancher/server containers.

**Closed by deniseschannon** 2016-11-29 21:58 UTC
Labels: kind/bug, status/resolved, status/to-test
