### ISSUE TITLE
[Continuous Delivery] Fleet agent should work when running behind proxy

### ISSUE THREAD

**Issue by janeczku** [rancher/rancher#29993] opened 2020-11-10 09:33 UTC
**What kind of request is this (question/bug/enhancement/feature request):**
Enhancement

**Steps to reproduce (least amount of steps as possible):**
Import a k3s cluster that is behind an enterprise proxy (connection _from_ downstream cluster _to_ Rancher goes via proxy)

**Result:**
Fleet agent fails to register

**Expected Result:**

Admin can configure proxy settings that would allow fleet agent to connect.

**Comment by slickwarren** [comment] 2020-12-31 20:13
I was unable to reproduce this issue. Here are the steps and configuration I used: 
* rancher version: 2.5.2
* fleet version installed: v0.3.1
* k3s version: v1.19.5+k3s2

------
* create proxy on a stand-alone node with the default setup (wernight/squid)
* create rancher single node on v2.5.2
* create single node k3s
* configure k3s for proxy by editing `/etc/systemd/system/k3s.service.env`
* restart k3s
* import k3s node into rancher server

------
fleet agent was able to register and appears to operate normally (able to deploy workloads, etc.)

**Comment by janeczku** [comment] 2021-01-04 15:13
@slickwarren 

In order to properly reproduce this issue you will need to configure firewall rules that prevent direct connections from the k3s single node to the Rancher single node (as would be the case in the given enterprise proxy scenario).

Following your steps above the  agent would simply be able to open a  direct connection to Rancher, not going over the proxy.

Instead, you can run the following commands before the "restart k3s" step:
```
sudo iptables -I FORWARD -d <IP of Rancher server> -j REJECT # Blocks connection from pods
sudo iptables -I OUTPUT -d <IP of Rancher server> -j REJECT # Blocks connection from host
```

**Comment by janeczku** [comment] 2021-01-04 15:24
By adding the above step, the Rancher Cattle agent will fail to run and the Fleet agent won't be deployed at all:

```
root@jan-k3s:~# kubectl get pods -A
NAMESPACE       NAME                                     READY   STATUS             RESTARTS   AGE
kube-system     local-path-provisioner-7ff9579c6-5z5n8   1/1     Running            0          31m
kube-system     coredns-66c464876b-l9r59                 1/1     Running            0          31m
kube-system     metrics-server-7b4f8b595-8jwnv           1/1     Running            0          31m
kube-system     helm-install-traefik-f4hwf               0/1     Completed          0          31m
kube-system     svclb-traefik-492sh                      2/2     Running            0          25m
kube-system     traefik-5dd496474-n26gb                  1/1     Running            0          25m
cattle-system   cattle-cluster-agent-6db997df5-thw4s     0/1     CrashLoopBackOff   9          24m
```
```
kubectl logs -n cattle-system cattle-cluster-agent-6db997df5-thw4s
INFO: Environment: CATTLE_ADDRESS=10.42.0.8 CATTLE_CA_CHECKSUM=f6869cf7a77516bf7a3a0e3307191ac81c6fb44d9f47e1d95ab630f68d5107b6 CATTLE_CLUSTER=true CATTLE_FEATURES= CATTLE_INTERNAL_ADDRESS= CATTLE_IS_RKE=false CATTLE_K8S_MANAGED=true CATTLE_NODE_NAME=cattle-cluster-agent-6db997df5-thw4s CATTLE_SERVER=https://***Rancher Server***
INFO: Using resolv.conf: search cattle-system.svc.cluster.local svc.cluster.local cluster.local nameserver 10.43.0.10 options ndots:5
ERROR: https://***Rancher Server***/ping is not accessible (Failed to connect to ***Rancher Server***port 443: Connection refused)
```

**Comment by bashofmann** [comment] 2021-01-04 15:46
If it helps to reproduce and test this, here is a terraform module, that sets this up on aws: https://github.com/bashofmann/rancher-demo-setups/tree/master/proxysetup-k3s-to-rancher-through-proxy

This will create:
* 1 public VM with a k3s cluster and publicly available Rancher
* One VPC with a public subnet that has an internet gateway and a private subnet that does not have an internet gateway
* One proxy VM in the public subnet with tinyproxy installed
* A security group for the proxy VM that allows
    Incoming SSH traffic from all networks (port 22)
    Outgoing HTTP and HTTPS traffic to the internet (ports 80 and 443)
    Outgoing HTTPS traffic to the kubernetes apiserver on cluster vms in the private subnet (ports 6443)
    Outgoing SSH traffic to the whole VPC (port 22)
    Incoming traffic to a proxy from the whole VPC to tinyproxy (port 8888)
* 1 cluster VM in the private subnet with a k3s cluster. this is not publicly available and can only be accessed through the proxy vm
* A security group for the cluster vms that allows
      Incoming SSH trafic from the public subnet (port 22)
      Incoming HTTPS traffic to the kubernetes apiserver from the public subnet (port 6443)
      Incoming and outgoing traffic on all ports between the cluster vms in the private subnet
      Outgoing traffic to the tinyproxy in the public subnet (port 8888)

After creating the infrastructure, you can:

* log into Rancher
* import a new cluster
* Run the unsecure import command like this

Given:

````
cluster_vm_ips = [
  [
    "10.0.1.200",
  ],
]
dns_name = "rancher.3.127.229.191.xip.io"
proxy_ip = [
  "18.158.72.184",
]
proxy_private_ip = [
  "10.0.0.163",
]
````

```
> ssh -o ForwardAgent=yes ubuntu@18.158.72.184
ubuntu@ip-10-0-0-163:~$ ssh 10.0.1.200
ubuntu@ip-10-0-1-200:~$ export proxy_private_ip=10.0.0.163
ubuntu@ip-10-0-1-200:~$ export HTTP_PROXY=http://${proxy_private_ip}:8888
ubuntu@ip-10-0-1-200:~$ export HTTPS_PROXY=http://${proxy_private_ip}:8888
ubuntu@ip-10-0-1-200:~$ export NO_PROXY=127.0.0.0/8,10.0.0.0/8,172.16.0.0/12,192.168.0.0/16,.svc,.cluster.local
ubuntu@ip-10-0-1-200:~$ export KUBECONFIG=/etc/rancher/k3s/k3s.yaml
ubuntu@ip-10-0-1-200:~$ curl --insecure -sfL https://rancher.3.127.229.191.xip.io/v3/import/t5bjrwqmvv7dcssf48zgvpss7jlfr2mbrgd6dtvrh6mtxds942qlm5.yaml | kubectl apply -f -
clusterrole.rbac.authorization.k8s.io/proxy-clusterrole-kubeapiserver created
clusterrolebinding.rbac.authorization.k8s.io/proxy-role-binding-kubernetes-master created
namespace/cattle-system created
serviceaccount/cattle created
Warning: rbac.authorization.k8s.io/v1beta1 ClusterRoleBinding is deprecated in v1.17+, unavailable in v1.22+; use rbac.authorization.k8s.io/v1 ClusterRoleBinding
clusterrolebinding.rbac.authorization.k8s.io/cattle-admin-binding created
secret/cattle-credentials-276153c created
clusterrole.rbac.authorization.k8s.io/cattle-admin created
deployment.apps/cattle-cluster-agent created

ubuntu@ip-10-0-1-200:~$ kubectl get pods -A
NAMESPACE       NAME                                     READY   STATUS      RESTARTS   AGE
kube-system     metrics-server-7b4f8b595-wvwh4           1/1     Running     0          33m
kube-system     local-path-provisioner-7ff9579c6-5jbw2   1/1     Running     0          33m
kube-system     coredns-66c464876b-svlfc                 1/1     Running     0          33m
kube-system     helm-install-traefik-vdg4v               0/1     Completed   0          33m
kube-system     svclb-traefik-dc579                      2/2     Running     0          33m
kube-system     traefik-5dd496474-7qzkf                  1/1     Running     0          33m
cattle-system   cattle-cluster-agent-794595b9d6-xq6sk    0/1     Running     1          3m12s

ubuntu@ip-10-0-1-200:~$ kubectl logs -n cattle-system cattle-cluster-agent-794595b9d6-xq6sk
INFO: Environment: CATTLE_ADDRESS=10.42.0.8 CATTLE_CA_CHECKSUM=c4636037276a7b015173da57efe44d6f00080e6b8c9e0179f3ba7514d893b5b8 CATTLE_CLUSTER=true CATTLE_FEATURES= CATTLE_INTERNAL_ADDRESS= CATTLE_IS_RKE=false CATTLE_K8S_MANAGED=true CATTLE_NODE_NAME=cattle-cluster-agent-794595b9d6-xq6sk CATTLE_SERVER=https://rancher.3.127.229.191.xip.io
INFO: Using resolv.conf: search cattle-system.svc.cluster.local svc.cluster.local cluster.local eu-central-1.compute.internal nameserver 10.43.0.10 options ndots:5
ERROR: https://rancher.3.127.229.191.xip.io/ping is not accessible (Failed to connect to rancher.3.127.229.191.xip.io port 443: Connection timed out)
```

**Comment by slickwarren** [comment] 2021-01-05 22:09
@janeczku , just to confirm, this should have rancher server with a public IP, not proxied, that tries to connect to an airgapped, proxied k3s cluster?

**Comment by janeczku** [comment] 2021-01-07 15:24
@slickwarren yes, although to clarify: Rancher, by design, doesn't establish connections to the k3s cluster - it's the other way around.

The setup would look something like this:

```
                             +------------------------------------------+
                             |                       air-gapped network |
+--------------+        +----+----+                                     |
|              |        |         |                                     |
| Docker Hub   | <------+internet |              +---------------+      |
+--------------+        |proxy    |              |               |      |
+--------------+        |         | <------------+  k3s node     |      |
| Rancher Mgmt | <------+         |              |               |      |
|              |        +----+----+              +---------------+      |
+--------------+             |                                          |
                             |                                          |
                             +------------------------------------------+

```

The k3s cluster is attached to an air-gapped network segment and the Rancher Server, as well as the Container registry, are attached to either a separate private network segment or the internet.
The important part is that your test setup must prevent any direct network connections between the k3s cluster nodes and the Rancher and Registry service endpoints.
How you achieve that is up to you. The easiest way is just by firewalling egress traffic on the k3s node using iptables (see my comment above). Alternatively, you could setup two subnets on AWS and configure security groups to prevent inter-subnet communication other than via the proxy node.

On the k3s side, you wanna make sure that both k3s as well as ContainerD are configured with the proxy setting. Last time i checked this was as easy as:
1. Exporting the proxy environment variables on the k3s node prior to installation
2. Install k3s with the script which would automatically configure k3s and containerd with the proxy settings.

**Comment by janeczku** [comment] 2021-01-07 16:57
1. Setup a Rancher on a Linux machine with a public IP only
2. Setup a HTTP Proxy on Linux machine with internet access
3. Setup another Linux machine for k3s that can reach the proxy but no public IP addresses
4. Configure the proxy environment on the k3s host:
```
export HTTP_PROXY=http://<proxy-node>:8888
export http_proxy=http://<proxy-node>:8888
export HTTPS_PROXY=http://<proxy-node>:8888
export https_proxy=http://<proxy-node>:8888
export no_proxy="localhost,127.0.0.1,10.0.0.0/8,192.168.10.0/24,.svc,.cluster.local"
export NO_PROXY="localhost,127.0.0.1,10.0.0.0/8,192.168.10.0/24,.svc,.cluster.local"

* ensure neither registry or rancher server endpoints are included in the `no_proxy` list
```
5. Install k3s with the standard installation command `curl -sfL https://get.k3s.io | sh -`

**Expected & Actual result**
k3s cluster will install successfully

Now register the k3s cluster to the Rancher server by running the import `kubectl` command.

**Expected result:**
the cluster is successfully registered to Rancher and fleet

**Actual result:**
The Rancher agent running on the k3s cluster fails to connect to the Rancher server.

**Comment by slickwarren** [comment] 2021-02-10 14:09
The connection is still not working through the http proxy, likely related to this issue https://github.com/rancher/rancher/issues/24876 
lets wait on this one to land as well to test. 
* tested on v2.5-head (045ae19c9185cb124901f9e331ccaf2ad666a108)
* k3s was not added to cluster, but run command on node finished with no errors

**Comment by kinarashah** [comment] 2021-02-10 18:44
@slickwarren Fixes for the linked issue #24876 are in `v2.5-head`, imported cluster's config now has a way to set agent env vars, could you elaborate a little on what errors you saw? or it's simply not working?

**Comment by slickwarren** [comment] 2021-02-11 18:06
currently blocked by https://github.com/rancher/rancher/issues/31258

**Comment by slickwarren** [comment] 2021-02-16 19:22
currently blocked by https://github.com/rancher/rancher/issues/24876

in short, the blocker is that I'm unable to properly bring up a downstream cluster behind proxy due to the API overriding the agentEnvVars that were set by the user.

**Comment by slickwarren** [comment] 2021-02-20 23:49
Using the steps below, I was able to verify fleet agent working on v2.5-head( 96dc206633a286c5fbae8d5240fa9354a88b823b) . Fleet agent is no longer deployed by default on master head, but was able to add the k3s cluster on master-head (dbf18389c36b56983c9848c1de1832faea2fc0a6): 
* run [this terraform script](https://github.com/bashofmann/rancher-demo-setups/tree/master/proxysetup-k3s-to-rancher-through-proxy)
* meanwhile, start rancher server, initiate the import cluster through rancher
* once terraform is finished, there will be some output that [looks like this.](https://github.com/rancher/rancher/issues/29993#issuecomment-754051711) ssh into the k3s cluster: 
  * ssh -o ForwardAgent=yes ubuntu@<public_proxy_ip>
  * ssh <k3s_ip>
  * export proxy_private_ip=<private_proxy_ip>
  * export HTTP_PROXY=http://${proxy_private_ip}:8888
  * export HTTPS_PROXY=http://${proxy_private_ip}:8888
  * export NO_PROXY=127.0.0.0/8,10.0.0.0/8,172.16.0.0/12,192.168.0.0/16,.svc,.cluster.local
  * export KUBECONFIG=/etc/rancher/k3s/k3s.yaml
* update `agentEnvVars` through rancher v3 api for the imported cluster following [this format](https://github.com/rancher/rancher/issues/24876#issuecomment-781992983) for `HTTP_PROXY`, `HTTPS_PROXY`, `NO_PROXY`
  * example `{"name" : "NO_PROXY", "value" : "127.0.0.0/8,10.0.0.0/8,172.16.0.0/12,192.168.0.0/16,.svc,.cluster.local"}`
* <img width="174" alt="Screen Shot 2021-02-20 at 3 13 42 PM" src="https://user-images.githubusercontent.com/16691014/108610912-6d3a0000-738e-11eb-9610-659fca78e76d.png">
* <img width="416" alt="Screen Shot 2021-02-20 at 3 14 20 PM" src="https://user-images.githubusercontent.com/16691014/108610913-6f9c5a00-738e-11eb-8f6e-2b3b3efd2564.png">
* copy the insecure registration command from the imported cluster 
* <img width="203" alt="Screen Shot 2021-02-20 at 3 16 02 PM" src="https://user-images.githubusercontent.com/16691014/108610925-8f338280-738e-11eb-9efd-7ecc55f9a55d.png">
* on your k3s cluster (via ssh), modify the registration yaml: 
  * `curl --insecure https://<rancher_public_ip>/v3/import/<registration_yaml_name>.yaml >> rancher_registration.yaml`
* add the same environment variables that you added to this k3s cluster to the yaml in `spec:template:spec:containers:env` near the bottom of the file. This will follow the same format as the other env already in the file
  * ex: `-name: NO_PROXY \n value: "127.0.0.0/8,10.0.0.0/8,172.16.0.0/12,192.168.0.0/16,.svc,.cluster.local"`
* finally, run the modified registration cmd with `kubectl apply -f rancher_registration.yaml`
* back on the rancher server, wait for the k3s imported cluster to register
* fleet and all other normal workloads and services are deployed.  K3S imported cluster is now active through rancher server
* <img width="989" alt="Screen Shot 2021-02-20 at 3 07 56 PM" src="https://user-images.githubusercontent.com/16691014/108611161-9d829e00-7390-11eb-8ad1-20dfa1d10f7c.png">

**Comment by kinarashah** [comment] 2021-02-20 23:53
@slickwarren I know this step was required earlier, but now modifying the registration yaml should no longer be required. I have fixed it so that once the env vars are added to the cluster spec, the generated agent yaml should have them already set. 

Could you confirm that works?

**Comment by slickwarren** [comment] 2021-02-22 19:22
tested the above in [this ticket](https://github.com/rancher/rancher/issues/24876)

**Comment by slickwarren** [comment] 2021-02-22 21:41
reopening due to this issue: https://github.com/rancher/fleet/issues/290, turns out fleet-agent is still expected to deploy automatically.

**Comment by slickwarren** [comment] 2021-02-23 00:40
the fix is in fleet, tested on 2.5-head. closing.

**Comment by jiaqiluo** [comment] 2021-02-23 19:40
UI https://github.com/rancher/rancher/issues/31023

**Comment by kinarashah** [comment] 2021-02-25 00:56
Blocked by https://github.com/rancher/rancher/issues/31422

**Comment by bmdepesa** [comment] 2021-04-20 19:06
rancher/rancher:v2.5-head 31f00c1

* Create a proxy server
* Create a Rancher server that is not behind a proxy (public IP only)
* Create a node with no public IP, configured to use a proxy, and install k3s on this node
* Import the proxied k3s cluster and include the proxy information in the Agent Environment variables section
* The k3s cluster registers successfully to the Rancher server
* Deploy a GitRepo to the imported & proxied k3s cluster
* The bundle deploys successfully

Forwardport for master: https://github.com/rancher/rancher/issues/32243
Related UI issue - Registration command doesn't show after specifying agent environment variables - https://github.com/rancher/rancher/issues/32242

**Closed by bmdepesa** 2021-04-20 19:06 UTC
Labels: QA/S, [zube]: QA Working, area/fleet, internal, kind/enhancement, priority/0, release-note

**Comment by slickwarren** [comment] 2021-05-04 20:59
retested following [these instructions](https://github.com/rancher/rancher/issues/29993#issuecomment-782766995) on v2.5.8-rc18 and see fleet-agent deploy successfully on a proxied downstream k3s cluster using `rancher/fleet-agent:v0.3.5-rc9` 
<img width="1346" alt="Screen Shot 2021-05-04 at 1 58 50 PM" src="https://user-images.githubusercontent.com/16691014/117069044-dfa95380-ace0-11eb-9af6-c1695096207c.png">
