### ISSUE TITLE
Bump wins.exe dependency to v0.4.14

### ISSUE THREAD

**Issue by aiyengar2** [rancher/rancher#43577] opened 2023-11-18 00:51 UTC
Need to bump wins dependency to latest version of wins after https://github.com/rancher/wins/pull/153 is merged to fix the pipeline failures.

**Comment by aiyengar2** [comment] 2023-11-18 01:33
`v0.4.13` contains the fixes and dependency bumps

**Comment by HarrisonWAffel** [comment] 2023-11-22 14:59
This will also help address issues regarding foreign container layers included in older releases which can be difficult to handle in air-gapped environments

**Comment by HarrisonWAffel** [comment] 2023-12-07 17:19
Relates to https://github.com/rancher/windows/issues/222

**Comment by HarrisonWAffel** [comment] 2024-01-11 20:19
> This will also help address issues regarding foreign container layers included in older releases which can be difficult to handle in air-gapped environments

I can confirm that the foreign layers have been removed from the latest version of wins 

Previously the wins image had the following layers, with the first two being foreign layers pointing to the microsoft container registry 
<details closed>
<summary>
Wins v0.4.11, Windows 2019
</summary>

`crane manifest rancher/wins:v0.4.11@sha256:ce7cc9049b45ab8633638c95ba7cb195214c307fa1509c27b9298cf048bf85b8`

```
{
   "schemaVersion": 2,
   "mediaType": "application/vnd.docker.distribution.manifest.v2+json",
   "config": {
      "mediaType": "application/vnd.docker.container.image.v1+json",
      "size": 10041,
      "digest": "sha256:540ac871ab64eacacfca3db5a2708a1638da70199caa2c7e48b2d425c4b450f6"
   },
   "layers": [
      {
         "mediaType": "application/vnd.docker.image.rootfs.foreign.diff.tar.gzip",
         "size": 1877166088,
         "digest": "sha256:b111c3320c949bea81612bf4554f1b6592c2f504920b5bf57ba340a1d4d52c93",
         "urls": [
            "https://mcr.microsoft.com/v2/windows/servercore/blobs/sha256:b111c3320c949bea81612bf4554f1b6592c2f504920b5bf57ba340a1d4d52c93"
         ]
      },
      {
         "mediaType": "application/vnd.docker.image.rootfs.foreign.diff.tar.gzip",
         "size": 826398623,
         "digest": "sha256:cee64bf279e2ca8e924884a10ecb98bfa79c7f0cc8d25e73039b9aeb940815b6",
         "urls": [
            "https://mcr.microsoft.com/v2/windows/servercore/blobs/sha256:cee64bf279e2ca8e924884a10ecb98bfa79c7f0cc8d25e73039b9aeb940815b6"
         ]
      },
      {
         "mediaType": "application/vnd.docker.image.rootfs.diff.tar.gzip",
         "size": 1120,
         "digest": "sha256:ded9d14a63bd2b9ae36d068d2eea02524a04ff26fa83b5e24e5735cd947c117d"
      },
      {
         "mediaType": "application/vnd.docker.image.rootfs.diff.tar.gzip",
         "size": 1091,
         "digest": "sha256:2ad1881b1ce3bae57d591ef9eeca436e8599d5378f6ceefb78c349f8f1070b27"
      },
      {
         "mediaType": "application/vnd.docker.image.rootfs.diff.tar.gzip",
         "size": 1091,
         "digest": "sha256:4ca26d108a443d7149120bb116430b7138d37063407d7e610fdd6d8572e0e1a8"
      },
      {
         "mediaType": "application/vnd.docker.image.rootfs.diff.tar.gzip",
         "size": 1094,
         "digest": "sha256:db85dde0e296773aca72f51ba419fb2be235b185d8b86b9ac5a51af21bd26826"
      },
      {
         "mediaType": "application/vnd.docker.image.rootfs.diff.tar.gzip",
         "size": 1091,
         "digest": "sha256:ad3c08f8ae997a0f0973ed295ca5ace7c65d5fb6417edbca6ceeafa34eadebb5"
      },
      {
         "mediaType": "application/vnd.docker.image.rootfs.diff.tar.gzip",
         "size": 1083,
         "digest": "sha256:602439e632257cd5684e587eb7ad8ac80efb5c42c96718a4cb04e241b514b717"
      },
      {
         "mediaType": "application/vnd.docker.image.rootfs.diff.tar.gzip",
         "size": 1095,
         "digest": "sha256:62cc594146d844ff6a0a662fcab667e4839a3199be8201628296359330191019"
      },
      {
         "mediaType": "application/vnd.docker.image.rootfs.diff.tar.gzip",
         "size": 1119,
         "digest": "sha256:b23fbbc098817d2fdc83ded487db0a9d95e061b3d7a2a03e11bb33de39967fe0"
      },
      {
         "mediaType": "application/vnd.docker.image.rootfs.diff.tar.gzip",
         "size": 1113,
         "digest": "sha256:6b3ec83a81509d18b2b21514c01496cfdf1a50c17c61279fcdc6649e77f478ff"
      },
      {
         "mediaType": "application/vnd.docker.image.rootfs.diff.tar.gzip",
         "size": 1093,
         "digest": "sha256:b53c5434975e6346b5242a397c188176a75aca875237803d77da6da17598f649"
      },
      {
         "mediaType": "application/vnd.docker.image.rootfs.diff.tar.gzip",
         "size": 1120,
         "digest": "sha256:25cd13b9106c250ac715c7f606574a000efa44b7502d286e5c6ed9814d5f295c"
      },
      {
         "mediaType": "application/vnd.docker.image.rootfs.diff.tar.gzip",
         "size": 1097,
         "digest": "sha256:6bcad22c061485a6f9d674bd0f407d100ff8f33d3b21250af2b1c959daa7d286"
      },
      {
         "mediaType": "application/vnd.docker.image.rootfs.diff.tar.gzip",
         "size": 1114,
         "digest": "sha256:d7f3aa114190e00e47794351bd8522e32c303ce398b5bf7c564d070acbd9bcfc"
      },
      {
         "mediaType": "application/vnd.docker.image.rootfs.diff.tar.gzip",
         "size": 1093,
         "digest": "sha256:f269c7d79646a58872c5d63235407c37bc186b6f576f5ebb8f34d81602d4afe0"
      },
      {
         "mediaType": "application/vnd.docker.image.rootfs.diff.tar.gzip",
         "size": 1092,
         "digest": "sha256:b7f31c323b60eef5b76a677167ede30c92920a02f2e80ad655c13c768ca415c7"
      },
      {
         "mediaType": "application/vnd.docker.image.rootfs.diff.tar.gzip",
         "size": 12031414,
         "digest": "sha256:7d8bd5ee6c40dfa9552b4e12e3aa54d87daa52cf798e8974a39eab2fdc2fa2de"
      },
      {
         "mediaType": "application/vnd.docker.image.rootfs.diff.tar.gzip",
         "size": 12386835,
         "digest": "sha256:c32b2cb1bfe119e4a061ba5fa5f375182ef7a6e19c891ddea97ca05c63297239"
      },
      {
         "mediaType": "application/vnd.docker.image.rootfs.diff.tar.gzip",
         "size": 1081,
         "digest": "sha256:b5b2bc299120a67d736a8570ee5fe5f7044293e1ea077bf5997e747dc71854b5"
      },
      {
         "mediaType": "application/vnd.docker.image.rootfs.diff.tar.gzip",
         "size": 1094,
         "digest": "sha256:48336f8724647cfde9e05f196cd40b22b04a445d151e9f98a96ca16ef3f060fb"
      },
      {
         "mediaType": "application/vnd.docker.image.rootfs.diff.tar.gzip",
         "size": 1091,
         "digest": "sha256:7133de1b34b03a609b3ce2eb91f127442bf2f5e65f2d57058b86c42bb8cd19b1"
      },
      {
         "mediaType": "application/vnd.docker.image.rootfs.diff.tar.gzip",
         "size": 1115,
         "digest": "sha256:2fefe5396aca5585d1239f95af61cdb972d6471e2c383e1022fc87e46fce6443"
      },
      {
         "mediaType": "application/vnd.docker.image.rootfs.diff.tar.gzip",
         "size": 1082,
         "digest": "sha256:5d3970f515a2d8cf56974c453574320bf093dc9c1829a968d85262da1d34a9ef"
      },
      {
         "mediaType": "application/vnd.docker.image.rootfs.diff.tar.gzip",
         "size": 1090,
         "digest": "sha256:50afa2750befe121a8dec01972cb72f21e3ee5c3cd80e32174ed9198d14b845f"
      }
   ]
}
```
</details>

<details closed>
<summary>
Wins v0.4.11, Windows 2022
</summary>

`crane manifest rancher/wins:v0.4.11@sha256:9bd607139cefb0401fe75fefdf6f159635e982ff8d4fd950aa82da93e097ba0c`

```
{
   "schemaVersion": 2,
   "mediaType": "application/vnd.docker.distribution.manifest.v2+json",
   "config": {
      "mediaType": "application/vnd.docker.container.image.v1+json",
      "size": 10040,
      "digest": "sha256:fb25704df6c5c31bfb0ff0543ef435b867ab546ca00fb2fb12ff8ddab5d48c9e"
   },
   "layers": [
      {
         "mediaType": "application/vnd.docker.image.rootfs.foreign.diff.tar.gzip",
         "size": 1436863614,
         "digest": "sha256:97f65a0ec59e643faf84024aa713a9be059322380315fda829756bbbd96d6258",
         "urls": [
            "https://mcr.microsoft.com/v2/windows/servercore/blobs/sha256:97f65a0ec59e643faf84024aa713a9be059322380315fda829756bbbd96d6258"
         ]
      },
      {
         "mediaType": "application/vnd.docker.image.rootfs.foreign.diff.tar.gzip",
         "size": 910085953,
         "digest": "sha256:4486102fd3820ed9527fa3e7bfefa8305c2f054e65b46dffe9675755e3d8f288",
         "urls": [
            "https://mcr.microsoft.com/v2/windows/servercore/blobs/sha256:4486102fd3820ed9527fa3e7bfefa8305c2f054e65b46dffe9675755e3d8f288"
         ]
      },
      {
         "mediaType": "application/vnd.docker.image.rootfs.diff.tar.gzip",
         "size": 1300,
         "digest": "sha256:b25c040ada3d2c975e8e18d2e9a7ef3b4e63cfa8e9e1832271bd5dbc6fec1838"
      },
      {
         "mediaType": "application/vnd.docker.image.rootfs.diff.tar.gzip",
         "size": 1302,
         "digest": "sha256:40d5ac083b05665a4c99a76042e5a0f01a5c619aa51d27ffeb3938594e107ed8"
      },
      {
         "mediaType": "application/vnd.docker.image.rootfs.diff.tar.gzip",
         "size": 1322,
         "digest": "sha256:013b50b331fa3cfd5632fb17a6c571bd5bded6d181b0df900b8d4cd2a0cd67e2"
      },
      {
         "mediaType": "application/vnd.docker.image.rootfs.diff.tar.gzip",
         "size": 1325,
         "digest": "sha256:a65a81667d04fba0d5aa42ba554c5644de1680de45220fa4b507ecf81b64fe18"
      },
      {
         "mediaType": "application/vnd.docker.image.rootfs.diff.tar.gzip",
         "size": 1297,
         "digest": "sha256:78d1e550f75169cc5df31ba6d763fff1706269d8e3e72f6b19fd15fa01a958ae"
      },
      {
         "mediaType": "application/vnd.docker.image.rootfs.diff.tar.gzip",
         "size": 1299,
         "digest": "sha256:207778a23a219f6c2d1b357b23206e16b8bd0ef17f5289b53cf50a858c17ffc7"
      },
      {
         "mediaType": "application/vnd.docker.image.rootfs.diff.tar.gzip",
         "size": 1298,
         "digest": "sha256:aebffb334f4f460737837d7fb0f2996b92beb37dd21edd8551c668184ac8c621"
      },
      {
         "mediaType": "application/vnd.docker.image.rootfs.diff.tar.gzip",
         "size": 1298,
         "digest": "sha256:a24f2bef73edb76aa7386ae65ad34ff1738c703d1206dca62384b9789c172549"
      },
      {
         "mediaType": "application/vnd.docker.image.rootfs.diff.tar.gzip",
         "size": 1293,
         "digest": "sha256:1d85ae99b702f6f0c5c3df0d70e09fe37da8147ac97da4957c900c2f80988716"
      },
      {
         "mediaType": "application/vnd.docker.image.rootfs.diff.tar.gzip",
         "size": 1332,
         "digest": "sha256:27fc378fda1b9af36c5aa2cda3216a817a9fec18dab901988ae5e65f4bfacd42"
      },
      {
         "mediaType": "application/vnd.docker.image.rootfs.diff.tar.gzip",
         "size": 1296,
         "digest": "sha256:93e3aed2c22fb4bc9f236d88567060577a259f78e678c129e45bd26cafa113d0"
      },
      {
         "mediaType": "application/vnd.docker.image.rootfs.diff.tar.gzip",
         "size": 1297,
         "digest": "sha256:e8dbdc7f74c87dc4e88f040b0ad2f646982b70ca482cdad6307f3dc392f9878d"
      },
      {
         "mediaType": "application/vnd.docker.image.rootfs.diff.tar.gzip",
         "size": 1294,
         "digest": "sha256:d8f8f8ebf5b1ad33d2455de09aa7dc28bd2478f8a83137cae2efedd64a59846a"
      },
      {
         "mediaType": "application/vnd.docker.image.rootfs.diff.tar.gzip",
         "size": 1297,
         "digest": "sha256:c6c8d376f5c072767cd96f0cffc9be4bc79a0e6b064bff8f011b9d7c3c39d670"
      },
      {
         "mediaType": "application/vnd.docker.image.rootfs.diff.tar.gzip",
         "size": 1331,
         "digest": "sha256:f11397c98d1d96e202ec450402ae82e3f60e2105d43135056c435d52c02fc391"
      },
      {
         "mediaType": "application/vnd.docker.image.rootfs.diff.tar.gzip",
         "size": 12031632,
         "digest": "sha256:aaf833c04fcea7ded5f9cd99e6eea9e7f2e50c027220dca28a6d0d2e40ae2ec2"
      },
      {
         "mediaType": "application/vnd.docker.image.rootfs.diff.tar.gzip",
         "size": 12636437,
         "digest": "sha256:c2050120a83c4f53244e087da4b34a21f99e4337b61711d97b0fee502c56600a"
      },
      {
         "mediaType": "application/vnd.docker.image.rootfs.diff.tar.gzip",
         "size": 1299,
         "digest": "sha256:8e76f813986b4c83659354c880ee6414265fc5be4d0ea3fda9ab92ee0d02f427"
      },
      {
         "mediaType": "application/vnd.docker.image.rootfs.diff.tar.gzip",
         "size": 1296,
         "digest": "sha256:51c8cd8a576eb01467242f25325770c785d84597f4764167aac50e4ad10e176d"
      },
      {
         "mediaType": "application/vnd.docker.image.rootfs.diff.tar.gzip",
         "size": 1296,
         "digest": "sha256:1bc9d9431cac8c9081eb159571468898264219ea556b9ba0991aa7dcc2674f67"
      },
      {
         "mediaType": "application/vnd.docker.image.rootfs.diff.tar.gzip",
         "size": 1296,
         "digest": "sha256:db5d9788d4f09df18a68a1fd1a2a3b13c44cd1553b8dae56bd99dd40ebfa32ce"
      },
      {
         "mediaType": "application/vnd.docker.image.rootfs.diff.tar.gzip",
         "size": 1295,
         "digest": "sha256:652d8c5bdb8a978d7b82fb1932bc5d04c2315a0b6265ca6f2c7d0410795ee33b"
      },
      {
         "mediaType": "application/vnd.docker.image.rootfs.diff.tar.gzip",
         "size": 1292,
         "digest": "sha256:cd3e0227a6ec285050ce1594664945e2bc7ab7e7ac3604097dd91a6c69a32747"
      }
   ]
}
```
</details>

The new layers look like the following, notice that no foreign layers are present 

<details closed>
<summary>
Wins v0.4.14, Windows 2019
</summary>

`crane manifest rancher/wins:v0.4.14@sha256:a561cf4b2aaa85a84d4ddac0c9c4d91ac6ebc5419b242dad2537e8cffe6b164c`

```
{
   "schemaVersion": 2,
   "mediaType": "application/vnd.docker.distribution.manifest.v2+json",
   "config": {
      "mediaType": "application/vnd.docker.container.image.v1+json",
      "size": 9927,
      "digest": "sha256:684a064206b5d0df87f41f8e949b2fb795fd0d30667bc04f05682713097f2d33"
   },
   "layers": [
      {
         "mediaType": "application/vnd.docker.image.rootfs.diff.tar.gzip",
         "size": 1650620357,
         "digest": "sha256:c9226d61d3bdbf9f09821b32f5878623b8daaa5fb4f875cb63c199f87a26d57e"
      },
      {
         "mediaType": "application/vnd.docker.image.rootfs.diff.tar.gzip",
         "size": 419102156,
         "digest": "sha256:9da94e8356538054b9b2e3023814100ffe07d42ee8f8dec0ad82a450371abd52"
      },
      {
         "mediaType": "application/vnd.docker.image.rootfs.diff.tar.gzip",
         "size": 1087,
         "digest": "sha256:fa7c7ad96c5e4a35ec91605e58621b12c7ee7d6c77c9ac283456af49790f028d"
      },
      {
         "mediaType": "application/vnd.docker.image.rootfs.diff.tar.gzip",
         "size": 1091,
         "digest": "sha256:f04619d87b0580c8e9650179e40deb830405d25320cefdd7b7ef12ee825c3d83"
      },
      {
         "mediaType": "application/vnd.docker.image.rootfs.diff.tar.gzip",
         "size": 1112,
         "digest": "sha256:5536784f08d850b80e256eec53b3db88a5c33650d358bac78b1461167e7ed1d9"
      },
      {
         "mediaType": "application/vnd.docker.image.rootfs.diff.tar.gzip",
         "size": 1110,
         "digest": "sha256:35eae38025b4cf8bcd217468f7e1a8f47cf26124b30b374e72a9f8eeaf4a0c77"
      },
      {
         "mediaType": "application/vnd.docker.image.rootfs.diff.tar.gzip",
         "size": 1113,
         "digest": "sha256:b6f316fd676f639a0e4595972ecc0c6c67fdcdb5428309078446b6e83e4f4de7"
      },
      {
         "mediaType": "application/vnd.docker.image.rootfs.diff.tar.gzip",
         "size": 1129,
         "digest": "sha256:7ff97396ad2d241bcbbe953243ee6203cdeb5e5b4674a7e19a74acc5037b2b90"
      },
      {
         "mediaType": "application/vnd.docker.image.rootfs.diff.tar.gzip",
         "size": 1114,
         "digest": "sha256:8b52e7c0afdda17be86fbb88d9034cb876c043242f8781a429891816f20bcfd5"
      },
      {
         "mediaType": "application/vnd.docker.image.rootfs.diff.tar.gzip",
         "size": 1115,
         "digest": "sha256:f14efed5956388420deac3ebeae408580adaeca260fcd7cb855e495a97c5510f"
      },
      {
         "mediaType": "application/vnd.docker.image.rootfs.diff.tar.gzip",
         "size": 1085,
         "digest": "sha256:46fea8c2d9688425bd00ffa2312d407dbac46e27da108a53f0aaa998b343cd7e"
      },
      {
         "mediaType": "application/vnd.docker.image.rootfs.diff.tar.gzip",
         "size": 1118,
         "digest": "sha256:338c057a77a2451fb84bf3db1389080995e5c1ab49e24ea266f2131d74aae5d7"
      },
      {
         "mediaType": "application/vnd.docker.image.rootfs.diff.tar.gzip",
         "size": 1093,
         "digest": "sha256:e412b1f08cbb38447490a45921be2b63b3c941e847797cb9541a49638b28d005"
      },
      {
         "mediaType": "application/vnd.docker.image.rootfs.diff.tar.gzip",
         "size": 1093,
         "digest": "sha256:b63d709879bd71b37935491aa12b135c2bad24bf76b3d8d0ca5c4c308b90df51"
      },
      {
         "mediaType": "application/vnd.docker.image.rootfs.diff.tar.gzip",
         "size": 1110,
         "digest": "sha256:65f7322ba1658b512082744d6bb044213d4aef0fafc0017bc1d3ef55534ee20c"
      },
      {
         "mediaType": "application/vnd.docker.image.rootfs.diff.tar.gzip",
         "size": 1087,
         "digest": "sha256:5156dcf31a3968353b88fdea9145eb1514f1864b2c3eeca43e9fee8d7a58692f"
      },
      {
         "mediaType": "application/vnd.docker.image.rootfs.diff.tar.gzip",
         "size": 1110,
         "digest": "sha256:909ce0b7af3acfc030fd508aa11daa8c76620c1b4ba7606550aab2d3871aeae0"
      },
      {
         "mediaType": "application/vnd.docker.image.rootfs.diff.tar.gzip",
         "size": 12053858,
         "digest": "sha256:16664cad650eb824ed876fffde444ae130bfb423482e40017ac480df689ad95c"
      },
      {
         "mediaType": "application/vnd.docker.image.rootfs.diff.tar.gzip",
         "size": 12477609,
         "digest": "sha256:d6d8e25810c41c1cd8c1967c53c77cd5f3559908321c2023408a48d9d5ace8cc"
      },
      {
         "mediaType": "application/vnd.docker.image.rootfs.diff.tar.gzip",
         "size": 1097,
         "digest": "sha256:4f3ee5377e38b81ac0177989458ab4a1db2d546867af01629e65807a950a816f"
      },
      {
         "mediaType": "application/vnd.docker.image.rootfs.diff.tar.gzip",
         "size": 1113,
         "digest": "sha256:7ce9e4382754ef8794adfe14deb3111ddf8410e4aeb9e0caba529496925f7a25"
      },
      {
         "mediaType": "application/vnd.docker.image.rootfs.diff.tar.gzip",
         "size": 1113,
         "digest": "sha256:b705233acfc9d2cc869f37097fac001e4bc95ec0345addf4263d5c0d26ff2004"
      },
      {
         "mediaType": "application/vnd.docker.image.rootfs.diff.tar.gzip",
         "size": 1085,
         "digest": "sha256:2cba113c1d5983ac6b84292feafeb74f015ae99e8761c5e9b47e7deaa2d7aea1"
      },
      {
         "mediaType": "application/vnd.docker.image.rootfs.diff.tar.gzip",
         "size": 1091,
         "digest": "sha256:ade3067e7d2efc17901a16cf295e7a06a15e6b76b2f758f15f425f5a2e26875f"
      },
      {
         "mediaType": "application/vnd.docker.image.rootfs.diff.tar.gzip",
         "size": 1094,
         "digest": "sha256:d647d0bcb4609a6e5f814616096190e4a3cb2e9df5d42cbd04e84930c1e90572"
      }
   ]
}
```
</details>


<details closed>
<summary>
Wins v0.4.14, Windows 2022
</summary>

`crane manifest rancher/wins:v0.4.14@sha256:00b4f8c578bb0f4b3b956312fbb940cb3c18bf658dae60e27ce9ebef6c36385b` 

```
{
   "schemaVersion": 2,
   "mediaType": "application/vnd.docker.distribution.manifest.v2+json",
   "config": {
      "mediaType": "application/vnd.docker.container.image.v1+json",
      "size": 9923,
      "digest": "sha256:0576d739ba5214cc75ae4812b021aed9a8fea90d26e5ea13ce097089f0cd22fe"
   },
   "layers": [
      {
         "mediaType": "application/vnd.docker.image.rootfs.diff.tar.gzip",
         "size": 1388598786,
         "digest": "sha256:7c76e5cf7755ce357ffb737715b0da6799a50ea468cc252c094f4d915d426b3f"
      },
      {
         "mediaType": "application/vnd.docker.image.rootfs.diff.tar.gzip",
         "size": 511613854,
         "digest": "sha256:a97a84f9ecb04e6f34ca7d17667bf0abbd83ea39301725226a2352330b4402d3"
      },
      {
         "mediaType": "application/vnd.docker.image.rootfs.diff.tar.gzip",
         "size": 1294,
         "digest": "sha256:0ea66b9efa9ee823a20f1b6979a331cdf8927bd887ed0821303550e46e164267"
      },
      {
         "mediaType": "application/vnd.docker.image.rootfs.diff.tar.gzip",
         "size": 1326,
         "digest": "sha256:098e6322b2b5145fd7f661b7e74feb8e6e8e200ef3950cb74b888d1f6f2e272a"
      },
      {
         "mediaType": "application/vnd.docker.image.rootfs.diff.tar.gzip",
         "size": 1294,
         "digest": "sha256:d381a463a8cbae3148cb9fd3718636260245d8bd694e21a4577de31bec12c910"
      },
      {
         "mediaType": "application/vnd.docker.image.rootfs.diff.tar.gzip",
         "size": 1323,
         "digest": "sha256:58296ed7d6fa0c29a93808be23e90f1d99343566ee42b97f83e274502f791b39"
      },
      {
         "mediaType": "application/vnd.docker.image.rootfs.diff.tar.gzip",
         "size": 1297,
         "digest": "sha256:34aa50e3d8c96e46af3aa84d427c34588ebf336f12edd501d774aaba337f0e72"
      },
      {
         "mediaType": "application/vnd.docker.image.rootfs.diff.tar.gzip",
         "size": 1320,
         "digest": "sha256:2453785b35cc8a8b4acbd8bdbd62d9a86a36d888d4118628c88943b9d1f50547"
      },
      {
         "mediaType": "application/vnd.docker.image.rootfs.diff.tar.gzip",
         "size": 1330,
         "digest": "sha256:2e7c4c4c96897aa21fb2fccb79a925ea724459815d13cabacccb00886b39c86f"
      },
      {
         "mediaType": "application/vnd.docker.image.rootfs.diff.tar.gzip",
         "size": 1296,
         "digest": "sha256:b73071c633ff1742c9c0e61018d33a910fe0dd143062189d47faddcde5be6942"
      },
      {
         "mediaType": "application/vnd.docker.image.rootfs.diff.tar.gzip",
         "size": 1293,
         "digest": "sha256:82f9e43c32a00483c6422b91991122eaf5c9810632d15c36bd9a5d563860c3f6"
      },
      {
         "mediaType": "application/vnd.docker.image.rootfs.diff.tar.gzip",
         "size": 1294,
         "digest": "sha256:9e3be770adce20d5a08cb4dd6f9d524f328b843a9d6bc2ca402971c464b6ed73"
      },
      {
         "mediaType": "application/vnd.docker.image.rootfs.diff.tar.gzip",
         "size": 1298,
         "digest": "sha256:26230e3c2836ca69e9f0401e8d5a3ab604bb2578409fb893720eff700bca284b"
      },
      {
         "mediaType": "application/vnd.docker.image.rootfs.diff.tar.gzip",
         "size": 1325,
         "digest": "sha256:d25d4a9c553defb7c2dff7f575e507c8e9145e320e7399ac446f7a6f5d961b43"
      },
      {
         "mediaType": "application/vnd.docker.image.rootfs.diff.tar.gzip",
         "size": 1295,
         "digest": "sha256:2729ab1d9077620775d2fafc65f82bf12b75bdd112f2d22ead78b96f057fbdbc"
      },
      {
         "mediaType": "application/vnd.docker.image.rootfs.diff.tar.gzip",
         "size": 1297,
         "digest": "sha256:3385ecc16bf8ca7036480bd509636b35462989340135c3dd168e888c751b965f"
      },
      {
         "mediaType": "application/vnd.docker.image.rootfs.diff.tar.gzip",
         "size": 1319,
         "digest": "sha256:5b925373db36058ff029476d88525e858ea626b935ad0f540ef303f0e714691f"
      },
      {
         "mediaType": "application/vnd.docker.image.rootfs.diff.tar.gzip",
         "size": 12054049,
         "digest": "sha256:83f9bdf03b4528cbaa992d4054928c5f88e2156e251c69ae7048592dc8c2c2f9"
      },
      {
         "mediaType": "application/vnd.docker.image.rootfs.diff.tar.gzip",
         "size": 12507926,
         "digest": "sha256:f682176b25fecca4c81a76af7d35c15e8d673f5b327aeb57269f4d8d62aeaad2"
      },
      {
         "mediaType": "application/vnd.docker.image.rootfs.diff.tar.gzip",
         "size": 1324,
         "digest": "sha256:e1dbf0dacee9e020852f2b2d1c4bfc26ed8faee02434cec25b0b8878f2800b67"
      },
      {
         "mediaType": "application/vnd.docker.image.rootfs.diff.tar.gzip",
         "size": 1290,
         "digest": "sha256:e3c460487148bd64e929496e697f952237c62fe897480eedfe04bd97be0ed647"
      },
      {
         "mediaType": "application/vnd.docker.image.rootfs.diff.tar.gzip",
         "size": 1295,
         "digest": "sha256:6a302a03b08f1ee5beb352b7670386be5dceeeb5f19de60d265d3ba18ccbe5e1"
      },
      {
         "mediaType": "application/vnd.docker.image.rootfs.diff.tar.gzip",
         "size": 1293,
         "digest": "sha256:46276527f051158243d8feaecb9eb1834af55ba1f4378f38019044932d7741e5"
      },
      {
         "mediaType": "application/vnd.docker.image.rootfs.diff.tar.gzip",
         "size": 1295,
         "digest": "sha256:4362c6db9bc8b756a5552cfa2a02da53164a8fa4db6c9b6b607e4443e989b79d"
      },
      {
         "mediaType": "application/vnd.docker.image.rootfs.diff.tar.gzip",
         "size": 1297,
         "digest": "sha256:bbf3bd09be619bb7b812a388d7a7d9437c64f2f9520035b5e03309b577e32cbe"
      }
   ]
}
```
</details>

**Comment by HarrisonWAffel** [comment] 2024-01-11 20:23
Since this issue simply focuses on bumping wins in Rancher (other components are covered in issue https://github.com/rancher/windows/issues/222), and that has been done, i'm going to close this issue out

**Closed** 2024-01-11 20:23 UTC
Labels: area/windows, [zube]: Done, team/area2
