### ISSUE TITLE
Unable to create a restricted Admin user in Rancher v2.51.

### ISSUE THREAD

**Issue by allaboutopensource** [rancher/rancher#29473] opened 2020-10-12 10:24 UTC
**What kind of request is this (question/bug/enhancement/feature request):**bug

**Steps to reproduce (least amount of steps as possible):** create a restricted admin user using the Rancher GUI 

**Result:**
Internal error occurred: failed calling webhook "rancherauth.cattle.io": Post https://rancher-webhook.cattle-system.svc:443/v1/webhook/validation?timeout=10s: context deadline exceeded

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): 2.5.1
- Installation option (single install/HA): HA

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): Vmware esxi 6.7 
- Machine type (cloud/VM/metal) and specifications (CPU/memory): VM
- Kubernetes version (use `kubectl version`): [1.18
<img width="1379" alt="Screen Shot 2020-10-12 at 3 52 21 PM" src="https://user-images.githubusercontent.com/5890851/95735983-3bf44980-0ca3-11eb-9c09-8451fe98015d.png">

```
(paste the output here)
```

- Docker version (use `docker version`):

```
(paste the output here)
```

**Comment by dramich** [comment] 2020-10-16 22:25
Closing as a duplicate of https://github.com/rancher/rancher/issues/29451 as they both have the same root cause

**Closed by dramich** 2020-10-16 22:25 UTC
