### ISSUE TITLE
[Logging v2] Add option to disable automation JSON parsing

### ISSUE THREAD

**Issue by nickgerace** [rancher/rancher#34720] opened 2021-09-14 14:42 UTC
An option already exists for this in the upstream logging chart. The solution will likely involve exposing the `spec.fluentbit.filterKubernetes.Merge_Log` field on every relevant Logging CR.

SURE-3272

**Comment by paynejacob** [comment] 2021-09-24 23:19
we should include all the merge keys if we are going to add this https://docs.fluentbit.io/manual/v/1.5/pipeline/filters/kubernetes

**Comment by prachidamle** [comment] 2021-09-24 23:23
yeah, rest of the merge keys can be set to defaults but including for user configuration will be good.

**Comment by annablender** [comment] 2021-10-29 21:37
Backport PR merged! Needs testing on rancher 2.5.11

**Comment by sowmyav27** [comment] 2021-10-29 22:14
Backport issue will be tracked and validated separately.

**Comment by Jono-SUSE-Rancher** [comment] 2021-10-29 22:21
@SheilaghM - can you help me sort this out for QA? It looks like _this_ ticket is actually something that should be targeted for v2.6.3. Instead of making a backport issue, it looks like @annablender created a backport _pr_ instead. Since this is merged into the charts branch could we get a backport issue for 2.5.11 created and have the PR Anna made linked to that instead?

**Comment by Jono-SUSE-Rancher** [comment] 2021-10-29 22:24
@SheilaghM & @annablender - I might need your guys' help with this one. So we are targeting 2.5.11 next week as part of the KDM release. Sheilagh will have more details. Anyway, we need to see what the impact is of the PR that was merged into 2.5.11 - can that be reverted/rolled back?

- _This_ issue should be for v2.6.3. We need a PR for that.
- We need to make sure anything merged into 2.5.11 gets reverted
- We should create a new, backport issue for v2.5.12 and merge the PR into _that_ branch (or hold onto it until that branch is created.

**Comment by annablender** [comment] 2021-10-29 22:51
@Jono-SUSE-Rancher Sheilagh let me know! So all I did was exposed a few fields in the rancher-logging helm chart. Hopefully, that will be easy to revert.

**Comment by Jono-SUSE-Rancher** [comment] 2021-10-29 22:56
@annablender - Well I believe Sowmya confirmed that there are no PRs to charts so there shouldn't be anything released into dev-v2.5. It might be fine to just get it into 2.5.12, but we would still need a backport issue to tie into it so that QA can account for the testing.

**Comment by sowmyav27** [comment] 2021-11-08 18:29
Closing this as a backport ticket has been logged - https://github.com/rancher/rancher/issues/35393

**Closed by sowmyav27** 2021-11-08 18:29 UTC
Labels: area/logging, [zube]: Review, QA/S, kind/good-first-issue
