### ISSUE TITLE
[BUG] rancher-machine sends data to bugsnag.com without user consent

### ISSUE THREAD

**Issue by thomashoell** [rancher/rancher#40227] opened 2023-01-20 09:21 UTC
**Rancher Server Setup**
- Rancher version: 2.7.0
- Installation option: Helm

**Describe the bug**
When the creation of a vm by a machine driver fails, the error log is sent to notify.bugsnag.com. This should not happen, since it's not obvious that this is happening and it cannot be turned of (at least I didn't find a way to do so). At the very least, the Rancher telemetry setting should be honored.

We discovered this issue due to a failing cluster creation loop caused by incorrect vSphere credentials. Rancher sent a total of over 300GB of data so bugsnag within two days. This caused massive trouble with the ITSEC department, because it looked like data was being exfiltrated.

**To Reproduce**
- create a cluster using the vSphere cloud provider (other will probably work, too).
- use incorrect credentials or let it fail in any other way

**Result**
- the logs generated are being sent to notify.bugsnag.com, even with telemetry being disabled.

**Expected Result**
- nothing should be sent to bugsnag without user consent

**Screenshots**
![image](https://user-images.githubusercontent.com/4695168/213660086-ef7e0888-9bd4-44e5-bbfd-b7f43be63a2e.png)
![image](https://user-images.githubusercontent.com/4695168/213667476-41a53afb-0999-49d1-88f2-11dce3bfc646.png)

**Additional context**
It may be related to this issue: https://gitlab.com/gitlab-org/gitlab-runner/-/merge_requests/1443

**Comment by snasovich** [comment] 2023-10-16 14:53
Thank you for reporting this issue.
I see bugsnag integration is something that was implemented by original `docker/machine` authors ~8 years ago per https://github.com/docker/machine/pull/2526 as "opt-in" but then the very next day it was switched to opt-out with default key used (see https://github.com/docker/machine/pull/2556) and it's the code we've inherited when we forked `rancher/machine` from it.

To my knowledge we're not using bugsnag and will look into disabling it by default.

**Comment by jiaqiluo** [comment] 2024-01-10 21:00
Hi @thomashoell, thank you again for reporting the issue. The fix has been merged and the issue should be gone in the latest Rancher `v2.9-head`, `v2.8-head`, and `v2.7-head`. 

Could you help confirm that the issue is fixed if you can run the latest Rancher `v2.9-head`, `v2.8-head`, or `v2.7-head`?  

You can either [run Ranher as a Docker container](https://ranchermanager.docs.rancher.com/pages-for-subheaders/rancher-on-a-single-node-with-docker) or set `rancherImageTag=v2.9-head`  when [using Helm chart](https://ranchermanager.docs.rancher.com/getting-started/installation-and-upgrade/installation-references/helm-chart-options#:~:text=Always%22%2C%20%22Never%22%2C%20%22IfNotPresent%22-,rancherImageTag,-same%20as%20chart). 

Please let me know if you have any questions. 

Thanks

**Comment by Josh-Diamond** [comment] 2024-01-29 23:03
Ticket #40227 - Test Results - ✅ 
---

As mentioned [here](https://github.com/rancher/rancher/issues/43968#issuecomment-1885725395), due to the nature of this issue, QA will validate that no regressions relating to cluster provisioning were introduced, as the result of this fix.

With Docker on Rancher `v2.9-676c3eb3dfa5a5d7d359315f942b630f8d3bf479-head`:

| Scenario | Test Case | Result |
|---|---|---|
| 1. | Provision a downstream RKE1 Linode Node driver cluster | ✅ |
| 2. | Provision a downstream RKE2 Linode Node driver cluster | ✅ |
| 3. | Provision a downstream K3s Linode Node driver cluster | ✅ |
| 4. | Provision a downstream RKE1 AWS Node driver cluster | ✅ |
| 5. | Provision a downstream RKE2 AWS Node driver cluster | ✅ |
| 6. | Provision a downstream K3s AWS Node driver cluster | ✅ |
| 7. | Provision a downstream RKE1 DO Node driver cluster | ✅ |
| 8. | Provision a downstream RKE2 DO Node driver cluster | ✅ |
| 9. | Provision a downstream K3s DO Node driver cluster | ✅ |

Screenshot:
<img width="1573" alt="Screenshot 2024-01-29 at 4 02 38 PM" src="https://github.com/rancher/rancher/assets/46494969/26b599cf-15be-456f-b161-c9cf2a2db726">

**Closed by Josh-Diamond** 2024-01-29 23:03 UTC
Labels: kind/bug, area/machine, [zube]: QA Working, QA/M, team/area2
