### ISSUE TITLE
Custom UI for node driver can not be loaded 

### ISSUE THREAD

**Issue by loganhz** [rancher/rancher#12113] opened 2018-03-15 02:18 UTC
rancher/server:master 03/15

There is a whitelist in rancher server internal proxy. The request to the host which is not on the whitelist will be rejected.

https://github.com/rancher/rancher/blob/0e57efba11b316c67523459f00ebf0d1b9018352/server/server.go#L30-L39

There are two cases:

1. The custom UI for node driver which is served on a host which is not in the whitelist. UI can not load it via the rancher proxy.

2. The custom UI for a node driver such as `openstack` might send requests to the `openstack` endpoint. The endpoint can not be hard coded in rancher server source code.

**Comment by vincent99** [comment] 2018-03-16 17:01
The source URL itself isn't actually downloaded through the proxy so it doesn't need to be whitelisted.  The download domain is just whitelisted by 1.x as the only way to automatically get an entry into the list, and that never worked for most situations because people want to host them on github.

There should just be a 4th parameter added to node drivers for `proxyWhitelistDomains`, `array[string]` and the user or catalog item can provide a list of relevant domains.

**Comment by mxschmitt** [comment] 2018-03-22 08:06
In my test environment, where I deployed Rancher 2 there was some strange behavior. The URL was redirected to an invalid one. Example:
`https://example.com/component.js` => `https:/example.com/component.js`

**Comment by StrongMonkey** [comment] 2018-03-26 22:40
@loganhz this is fixed in master now. You are able to add your own whitelist proxy by adding a field `whitelistDomain` in nodedriver,

**Comment by mxschmitt** [comment] 2018-03-27 07:55
@StrongMonkey i tried test it with your changes. I built rancher from master myself, but it isn't working. Also throwing an "invalid host" error. But I think it's because of the strange redirect. Maybe you can reproduce by using:
Docker driver: `https://github.com/JonasProgrammer/docker-machine-driver-hetzner/releases/download/1.1.0/docker-machine-driver-hetzner_1.1.0_linux_amd64.tar.gz`
UI Driver: `https://storage.googleapis.com/hcloud-rancher-v2-ui-driver/component.js`
Whitelist Host: `storage.googleapis.com`

Logs: 
![image](https://user-images.githubusercontent.com/17984549/37953832-53d9fa36-31a4-11e8-8c85-fb4677dccd80.png)

Log Code Pointer:

https://github.com/rancher/rancher/blob/00999ada75af09a02cd80fe84c0366d78c23e9dc/pkg/httpproxy/proxy.go#L88-L90

=> destURL.Host is empty or nil => destPath is incorrect, that's maybe because of the strange redirect. 

Example redirect: 
From `https://<ip>/meta/proxy/https://storage.googleapis.com/hcloud-rancher-v2-ui-driver/component.js`

to: `https://<ip>/meta/proxy/https:/storage.googleapis.com/hcloud-rancher-v2-ui-driver/component.js` => status code `502`

Best regards

Max

**Comment by loganhz** [comment] 2018-03-27 09:10
@mxschmitt  I can reproduce your issue. There is a workaround might help.

Please try `http://storage.googleapis.com/hcloud-rancher-v2-ui-driver/component.js`

`https` one doesn't work. But `http` does.

**Comment by mxschmitt** [comment] 2018-03-27 09:25
Hm okay. Thank you!

I've created a PR with a fix. #12309
I tested two test cases:
- http://[...]
- https://[...]

both work fine.

**Comment by tfiduccia** [comment] 2018-03-29 23:01
Version - 2.0 master 3/29
Verified fixed

**Closed by tfiduccia** 2018-03-29 23:01 UTC
Labels: kind/bug, status/to-test, version/2.0
