### ISSUE TITLE
RKE template and revision stuck with spinners when editting a cluster

### ISSUE THREAD

**Issue by dnoland1** [rancher/rancher#26865] opened 2020-04-30 16:58 UTC
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
Unknown, but when you go to edit a cluster, the RKE templete and revisions drop downs are stuck:
![image](https://user-images.githubusercontent.com/468462/80737731-c9aef480-8ac8-11ea-84ff-582f05e1e2df.png)

**Result:**
Here's the browser console output:
```
component.js:85 Uncaught TypeError: Cannot convert undefined or null to object
    at n.flannelBackendDidChange (component.js:85)
    at x (metal.js:288)
    at e.t.flush (metal.js:416)
    at H (metal.js:856)
    at V (metal.js:882)
    at e.setProperties (metal.js:3733)
    at n.setProperties (observable.js:193)
    at t.i.update (glimmer.js:4466)
    at n.evaluate (runtime.js:1888)
    at e.r.execute (runtime.js:4280)
```

**Other details that may be helpful:**
Noticed some revisions had:
```
        network:
          plugin: canal
```
Instead of:
```
        network:
          mtu: 0
          options:
            flannel_backend_type: vxlan
          plugin: canal
```
Manually fixed this using `kubectl edit clustertemplaterevisions -n cattle-global-data ctr-xxxxx` but that didn't help workaround the issue.

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI):
v2.3.6
- Installation option (single install/HA):
HA

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported):
- Machine type (cloud/VM/metal) and specifications (CPU/memory):
- Kubernetes version (use `kubectl version`):

- Docker version (use `docker version`):

gzrancher/rancher#9826

**Comment by caiconkhicon** [comment] 2020-05-08 13:30
I also have the same issue with Rancher 2.4.2.
This is my rke template:

```
# 
# Cluster Config
# 
default_pod_security_policy_template_id: restricted
docker_root_dir: /var/lib/docker
enable_cluster_alerting: false
enable_cluster_monitoring: false
enable_network_policy: false
# 
# Rancher Config
# 
rancher_kubernetes_engine_config:
  addon_job_timeout: 30
  addons_include:
    - >-
      https://raw.githubusercontent.com/jetstack/cert-manager/v0.12.0/deploy/manifests/00-crds.yaml
  ignore_docker_version: true
  kubernetes_version: v1.17.2-rancher1-2

  network:
    mtu: 0
    plugin: canal

  services:
    etcd:
      backup_config:
        enabled: false
        interval_hours: 12
        retention: 6
        safe_timestamp: false
      creation: 12h
      extra_args:
        client-cert-auth: 'true'
        peer-client-cert-auth: 'true'
      gid: 0
      retention: 72h
      snapshot: false
      uid: 0
    kube-api:
      always_pull_images: false
      audit_log:
        configuration:
          format: json
          max_age: 30
          max_backup: 10
          max_size: 100
          path: /var/log/kube-audit/audit-log.json
        enabled: true
      event_rate_limit:
        enabled: true
      pod_security_policy: true
      secrets_encryption_config:
        enabled: true
      service_node_port_range: 30000-32767
    kube-controller:
      extra_args:
        address: 127.0.0.1
        feature-gates: RotateKubeletServerCertificate=true
        profiling: 'false'
        terminated-pod-gc-threshold: '1000'
    kubelet:
      extra_args:
        feature-gates: RotateKubeletServerCertificate=true
        tls-cipher-suites: >-
          TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305,TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305,TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384,TLS_RSA_WITH_AES_256_GCM_SHA384,TLS_RSA_WITH_AES_128_GCM_SHA256
      fail_swap_on: false
      generate_serving_certificate: true
    scheduler:
      extra_args:
        address: 127.0.0.1
        profiling: 'false'
  ssh_agent_auth: false
  upgrade_strategy:
    drain: 'false'
    max_unavailable_controlplane: '1'
    max_unavailable_worker: 10%
    node_drain_input: {}
scheduled_cluster_scan:
  enabled: true
  scan_config:
    cis_scan_config:
      debug_master: true
      debug_worker: true
      profile: permissive
  schedule_config:
    cron_schedule: 0 7 * * *
    retention: 30

```

**Comment by prachidamle** [comment] 2020-05-18 22:43
@dnoland1 I think the reason for spinning during edit cluster was related to orphaned clusterTemplateRevisions which probably were not cleared out from UI's caching. Reloading the UI would stop the spinning. So the root cause is most likely https://github.com/rancher/rancher/issues/26861

And revisions having the following seems to be unrelated and a different issue. Can you log this separately.
```
        network:
          plugin: canal
```

**Comment by westlywright** [comment] 2020-06-24 21:13
This is related but only tangentially. UI is doing a check to see if any of the cluster template revisions are the default revision of the selected cluster template as we build the list for the select. But because that is gone we're checking a null object.

**Comment by soumyalj** [comment] 2020-06-24 23:08
Reproduced the spinning issue in v2.3.3 . 

Steps:
1. Using a python test script, created 200 RKE templates with each template having 10 revisions in them. Create clusters with the templates and  delete the templates
2. After all templates were deleted, few revisions are orphaned and left around
3. Create a new template 
4. Navigate to a cluster and edit the cluster, the rke template drop down will be spinning as below:
![Screen Shot 2020-06-24 at 4 06 43 PM](https://user-images.githubusercontent.com/18536626/85636194-b8034c80-b634-11ea-8478-3ed586f01daf.png)

**Comment by soumyalj** [comment] 2020-06-26 18:10
Tested with v2.4-head(46f7940dd)

- The flannelBackendDidChange console error fix was verified with the steps below:

 1. Create a cluster template/revision (T1/R1)by editing the yaml with the below:
  ```
        network:
          plugin: canal
```
2. Create a custom cluster using the revision R1 and hit save . The console does not have flannelBackendDidChange error. 

- The spinning error in the UI does not occur, the rke template revision orphaning issue has been fixed in: https://github.com/rancher/rancher/issues/26861

**Closed** 2020-06-26 19:37 UTC
Labels: [zube]: To Test, internal, team/ui
