### ISSUE TITLE
rancher-compose fails to populate boolean parameter from environment

### ISSUE THREAD

**Issue by davidrabinowitz** [rancher/rancher#5197] opened 2016-06-19 11:21 UTC
**Rancher Version:**  0.7.4

**Docker Version:** 1.12.0-rc2, build 906eacd, happened on 0.11 as well

**OS and where are the hosts located?** rancher-compose running on Linux and Mac

**Steps to Reproduce:** Create a rancher-compose.yml file, with an boolean parameter provided by an environment variable, like this
```
  upgrade_strategy:
    start_first: ${START_FIRST}
    batch_size: 1
```

**Results:** An error occurs: yaml: unmarshal errors: line 28: cannot unmarshal !!str `false` into bool 

When running in debug I see the following yaml:
```
  upgrade_strategy:
    batch_size: 1
    start_first: "false"  # <-- notice the surrounding quotes, missing from the rest of the variable replacements
```
**Expected:** The environment variable to be read as boolean

**Comment by raviv** [comment] 2016-06-19 13:17
👍

**Comment by deniseschannon** [comment] 2016-06-19 21:06
Duplicate of https://github.com/rancher/rancher/issues/4822

In that issue, you can see the comments, but long story short is that docker-compose/libcompose/rancher-compose currently is unable to handle environment interpolation/variable substitution with booleans.

**Closed by deniseschannon** 2016-06-19 21:06 UTC
