### ISSUE TITLE
Remove MultiCluster Apps

### ISSUE THREAD

**Issue by cbron** [rancher/rancher#37321] opened 2022-04-13 17:25 UTC
MCA was deprecated in 2.5.0, and therefore will be EOL as of 2.7.0. It should be removed/disabled.
SURE-4555

**Comment by MKlimuszka** [comment] 2023-06-07 21:16
Closing as duplicate of https://github.com/rancher/rancher/issues/39525

**Closed by MKlimuszka** 2023-06-07 21:16 UTC
Labels: area/catalog, [zube]: Team Area 3, team/mapps
