### ISSUE TITLE
Rancher health checks and TCP retransmissions

### ISSUE THREAD

**Issue by m4ce** [rancher/rancher#3326] opened 2016-01-19 18:47 UTC
Hi,

after having implemented some TCP monitoring, I noticed that all the boxes running within rancher started doing TCP retransmissions as soon as the health checks kicked off.

As soon as I disable the health checks, the retransmissions stop. I've taken a tcpdump and I can confirm the retransmissions are related to the health checks.

Have you noticed this before?

Cheers,
Matteo

**Comment by alena1108** [comment] 2016-01-19 19:31
@m4ce were health check failing at the time you've observed tcp retransmission? If not, were those retransmissions observed only when health check was initializing, or even after all instances reached "healthy" state?

FYI, we delegate health checking to haproxy running inside network agent container, so just trying to figure out if the issue you see is caused by initialization stage of the health check - when instances-to-check are not fully up yet; or if there might be some bug in the third party software we use.

**Comment by m4ce** [comment] 2016-01-20 07:58
@alena1108, the TCP retrans are permanent, even when the health checks are healthy.

I could send you a pcap dump so that you can see what's going on if that helps.

**Comment by m4ce** [comment] 2016-01-20 08:25
From a short investigation, it looks like the issue is related to resets received for embryonic SYN_RECV sockets.

**Comment by deniseschannon** [comment] 2016-03-03 21:22
@m4ce It sounds like this isn't a Rancher issue and I'll close it. If you have more questions, please re-open.

**Closed by deniseschannon** 2016-03-03 21:22 UTC
