### ISSUE TITLE
Allow binding to a specified IP

### ISSUE THREAD

**Issue by pzduniak** [rancher/rancher#53] opened 2015-01-25 19:58 UTC
Hey, so far using rancher was a great experience, but it's missing a quite vital feature. In docker, you can bind to a specified IP by passing `-p 10.0.0.1:8080:8080`. Sending `10.0.0.1:8080` in host port field in Rancher's UI does not work. Could it get added?

**Comment by ibuildthecloud** [comment] 2015-01-25 20:39
Yes, of course.  Anything you can do with "docker run" we want to support.  This one has just been overlooked.

**Comment by deniseschannon** [comment] 2015-06-02 05:27
@cjellick Is this issue fixed with the native docker feature?

**Comment by vincent99** [comment] 2015-06-02 06:53
@deniseschannon no.. Native docker might pick up portion different IPs but we still need that exposed in the API and as options in the UI.

**Comment by pospisil** [comment] 2015-06-17 09:01
Is any progress in this issue. We use multiple IP's on our hosts, so possibility to set this in UI will be very helpfull. Now when I clone docker, the clone didn't publish any ports.

**Comment by will-chan** [comment] 2015-07-07 17:12
We are working on a fix but it might not make it into this week's release.

**Comment by cjellick** [comment] 2015-07-29 17:47
Another issue to look at while we're looking at this:
https://github.com/rancher/rancher/issues/1673

**Comment by deniseschannon** [comment] 2015-08-04 17:59
We should review this list of acceptable formats based on the docker site. 

```
-p=[]      : Publish a container᾿s port or a range of ports to the host 
               format: ip:hostPort:containerPort | ip::containerPort | hostPort:containerPort | containerPort
               Both hostPort and containerPort can be specified as a range of ports. 
               When specifying ranges for both, the number of container ports in the range must match the number of host ports in the range. (e.g., `-p 1234-1236:1234-1236/tcp`)
               (use 'docker port' to see the actual mapping)
```

**Comment by marzolfb** [comment] 2015-11-09 04:11
+1 from me on this - it is tripping me up as well. Noticed there's so milestone tag for this. Any update on it? Anyone have any ideas on creative workarounds for this for the time being?

**Comment by teon** [comment] 2015-11-23 12:17
+1

**Comment by waltermeyer** [comment] 2015-12-02 21:47
+1

**Comment by lazystone** [comment] 2015-12-09 10:54
+1
And is there any workaround for this? I tried to play with iptables, but unsuccessfully.

**Comment by cjellick** [comment] 2015-12-09 15:15
No workaround @lazystone , but we are working on proper integration with docker networking. I believe that will resolve this problem.

**Comment by martingabelmann** [comment] 2015-12-30 08:06
+1

**Comment by pwFoo** [comment] 2016-01-15 16:41
Also need this feature to bind to an internal vor external interface.

**Comment by taketnoi** [comment] 2016-02-02 06:43
+1

**Comment by CBR09** [comment] 2016-02-02 06:54
+1

**Comment by gemoya** [comment] 2016-02-22 19:12
+1
is there a expecting release with this feature?

**Comment by clescot** [comment] 2016-02-23 23:32
+1

**Comment by delin** [comment] 2016-03-05 19:59
+1

**Comment by cjellick** [comment] 2016-03-18 15:13
Valid formats: ip:hostPort:containerPort | ip::containerPort | hostPort:containerPort | containerPort

**Comment by will-chan** [comment] 2016-03-19 18:39
@vincent99 looks like we need UI before this feature is complete.

**Comment by tfiduccia** [comment] 2016-03-22 22:56
Version - master 3/22
Not completed - needs backend support.

**Comment by tfiduccia** [comment] 2016-03-24 19:44
Version - master 3/24
Verified fixed

**Closed by tfiduccia** 2016-03-24 19:44 UTC
Labels: area/networking, area/ui, kind/bug, priority/0, status/resolved, status/to-test

**Comment by danipolo** [comment] 2016-08-04 09:58
is this still solved? we have multiple public IP's and we need to route them to specific containers... How to do this?

**Comment by pwFoo** [comment] 2016-08-06 10:13
I was able to use -p <IP>:<PORT>:<CONTAINER-PORT>. So it should work fine.

**Comment by Dids** [comment] 2016-10-20 13:23
Using `0.0.0.0:port:port` doesn't work in docker-compose.yml, but works when done from the web UI. Why?

**Comment by farfeduc** [comment] 2017-05-05 06:48
I tried to to this on the last version of rancher earlier today and I couldn't get the IP field to work in the UI. Every time I set something like "192.168.0.2" inside the Host IP field in the port binding section, it binded my container to 0.0.0.0 :/

Currently I use my service in a standalone container. It would be great if rancher could use the good IP.

**Comment by drewpalmetto** [comment] 2017-10-03 15:58
i have the same issue.  i set the ip in the host IP field and the entire stack reverts back to the bound IP of the host.  (which is actually a secondary IP assigned to said host.

**Comment by bascht** [comment] 2017-10-17 14:13
@drewpalmetto Did you get this fixed? It looks like this could be a regression. I'm running into the same issue with:

```yaml
    ports:
      - '127.0.0.1:9000:9000/tcp'
```

resulting in the port `9000` being bound on the public interface.

**Comment by farfeduc** [comment] 2017-10-17 15:02
No I have not found a solution for this :/

**Comment by drewpalmetto** [comment] 2017-10-17 15:22
@bascht No, we never found a workable solution.  We ended up switching to docker enterprise.  and it works fine.

**Comment by bascht** [comment] 2017-10-18 13:12
Alright, it's a bit odd. If I try the same config for the rancher load balancer service:

![screenshot_20171018_151142](https://user-images.githubusercontent.com/51264/31720384-c063f884-b416-11e7-8d73-395f6f265997.png)

it works:

![screenshot_20171018_151129](https://user-images.githubusercontent.com/51264/31720404-ca79a5ee-b416-11e7-8220-745e91830681.png)
