### ISSUE TITLE
IPsec silent failure

### ISSUE THREAD

**Issue by SamMousa** [rancher/rancher#9794] opened 2017-08-30 07:18 UTC
**Rancher versions:**
rancher/server: 1.6.7
rancher/agent: 1.2.5

**Infrastructure Stack versions:**
healthcheck: 0.3.1
ipsec: 0.11.7
network-services: 0.7.7
scheduler: 0.8.2
kubernetes (if applicable):

**Docker version: (`docker version`,`docker info` preferred)**
````
Server:
 Version:      17.06.0-ce
 API version:  1.30 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   02c1d87
 Built:        Fri Jun 23 21:17:03 2017
 OS/Arch:      linux/amd64
 Experimental: false
````
**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
Ubuntu

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
KVM vps

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
Single node rancher, internal DB

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle

**Steps to Reproduce:**
Unclear

**Problem:**
At some point my healthcheck infrastructure was stuck in the initializing state, I opened a shell in my ipsec container and tried to ping the other ipsec containers which failed. Restarting the ipsec container resolved the issue.

**Idea:**
The issue of a failing ipsec is hard to debug since the service appears healthy. My suggestion is to have the ipsec container try to ping the other ipsec containers and if it fails to reach any host it should die.
That way we can at least detect something is wrong and when it gets restarted / recreated ipsec might work again.

**Comment by truongdo** [comment] 2017-09-03 14:27
I also have the same problem that after few days running smoothly, a container can't ping other containers on other hosts. After restarting all IPsec containers, the connection works again.

**Comment by guodong** [comment] 2017-09-04 05:22
@truongdo what os are you using?

**Comment by truongdo** [comment] 2017-09-04 05:37
@guodong some of rancher nodes are running Ubuntu 14.04 LTS (3.13.0), Debian GNU/Linux 9 and  Ubuntu 16.04.2 LTS. And the rancher server are running Debian GNU/Linux 8.2.

**Comment by leodotcloud** [comment] 2017-09-06 13:28
@SamMousa @truongdo Can you please collect logs from your setup using: `https://github.com/rancher/rancher-logs-collector` and share them with me? Also next time it happens can you please ping me directly on https://slack.rancher.io?

**Comment by truongdo** [comment] 2017-09-06 14:15
@leodotcloud  absolutely, it happens few times/month. So I guess I can get the logs for you soon.

**Comment by truongdo** [comment] 2017-09-21 01:06
@leodotcloud I think the IPSec enhancement in the Rancher 1.6.8 fixed this issue. I haven't encountered any network loss in the last 2 weeks.

**Comment by c58** [comment] 2017-09-21 07:44
I have the same issue. Restart ipsec fixes the issue. Will collect logs next time as @leodotcloud suggested.

**Comment by truongdo** [comment] 2017-09-23 06:54
I and @leodotcloud had a discussion via slack about this issue, here is the summary:

### My setup:
1. Rancher server: 1.6.8. The rancher server host has 2GB of memory.
2. I have 2 VPS located in Singapore and LA
### Problem:
After few days working normally, the IPSec on those 2 hosts cannot communicate anymore.
Restarting IPSec containers solved the problem.

### What we see from the log files
When the connection problem occurred,
1. The IPSec container on the VPS LA (IPSec LA) keep sending 5 packages to the IPSec in Singapore (IPSec Sing) without getting any response. In fact, the IPSec Sing does get the package, but the response packages from the IPSec Sing couldn't make it the IPSec LA -> The IPSec LA deleted the connection to the IPSec Sing, causing the connection lost.
2. We couldn't pinpoint the exact cause of losing packages. It might due to there was a network interruption at that time, which is very likely because of the far distance between those 2 hosts.

### Possible solution
As @leodotcloud suggested, instead of deleting the connection after 5 times of failure, IPSec container should continue to retry because there might be just a short network interruption.

**Comment by cirola2000** [comment] 2017-10-17 14:04
We have the same issue using v1.6.10 here.

Here's how to reproduce it: 
1. On your host, check the container ID of the **net:holder** service (```docker ps | grep net:holder | cut -d" " -f 1```)
2. Bring down the virtual network interface that starts with "veth"+container ID (```ifconfig veth8a504d1 down```)
3. If you wait for maybe 3 or more minutes and bring the interface up again, your host heath check will fail and you'll have to restart IPSec service.

**Comment by superseb** [comment] 2017-10-17 14:08
@leodotcloud Is this handled by https://github.com/rancher/rancher/issues/9971 ?

**Comment by cirola2000** [comment] 2017-10-20 08:29
Since it's quite a critical issue, we've came up with small turnaround. The following script check whether there is at least one IPsec active connection, and restart the service case not. 

```
#!/bin/bash

swanState=$(swanctl --list-sas | grep "ESTABLISHED" )

if [ -z "$swanState" ]; then

  echo "It seems that there is no active IPsec connections! Restarting service..."
 
  pid=$(ps -ef | awk '/[r]ancher/{print $2}') 
  cmd=$(ps xo command | grep rancher-net | head -1)

  kill -15 $pid
  $cmd

fi
```

We are running it every 5 mins, and it seems to work fine.

**Comment by leodotcloud** [comment] 2017-10-21 00:38
Closing this in favor of #9971.

**Closed by leodotcloud** 2017-10-21 00:38 UTC
Labels: area/networking
