### ISSUE TITLE
Catalog app questions fail if include a comma

### ISSUE THREAD

**Issue by wmolyneux** [rancher/rancher#14551] opened 2018-07-16 09:44 UTC
**Rancher versions:**
rancher/rancher: 2.0

**Steps to Reproduce:**

- Create a simple rancher catalog app that asks a question requiring a value with a comma.
- Deploy the catalog app entering a value with a comma in it for the answer to the questions. e.g. example1,example2

**Results:**
Helm chart fails to execute given the error: 
Helm template failed. Error: failed parsing --set data: key "example2" has no value (cannot end with ,) : exit status 1

**Notes**
Using the '\' character (e.g. example1\,example2) in the answer to the question will correctly deploy the catalog app.

**Comment by loganhz** [comment] 2018-08-01 05:42
It still happens in v2.0.6

**Comment by azbpa** [comment] 2018-08-02 08:48
Facing the same issue trying to setup StorageOS using their [Helm chart](https://github.com/storageos/helm-chart) though Rancher 2.0 (with Custom Catalog).  The property `cluster.join` requires a comma separated list

**Comment by guangbochen** [comment] 2018-08-17 03:42
use quotation is required now for the variable that contains a comma; this is also an expected behavior at the helm.
![image](https://user-images.githubusercontent.com/4569037/44246759-79b7cd80-a212-11e8-93e2-0a8be241052c.png)

**Comment by guangbochen** [comment] 2018-09-06 00:54
related to #13158

**Comment by cjellick** [comment] 2018-09-12 01:17
I'm going to attach this to the other issues related to the helm refactor and move it along with them

**Comment by cjellick** [comment] 2018-09-12 01:18
@StrongMonkey can you just review this issue and decide if you think it could/should be fixed by your refactor?

**Comment by cjellick** [comment] 2018-09-13 23:58
I was moving this along as pat of @StrongMonkey's refactor of rancher and helm's type conversion logic. But that featured was moved out of the release because it was deemed too big to put in the release so late. 

Right now, the workaround is to properly quote the string. But, the refactor should at least present some other options for addressing this.

**Comment by cjellick** [comment] 2018-09-13 23:59
@deniseschannon did you move this to-test because you just want it addressed through documentation? If so, then it can be tested and closed as such, but there is no actual fix for this.

**Comment by cjellick** [comment] 2018-09-14 00:00
@sangeethah before anyone tests this, please confirm @deniseschannon's intention when moving it.

**Comment by guangbochen** [comment] 2018-09-14 13:44
It is required to use the double quotation for now, moving it to the next release.

**Comment by manschutz-samsung** [comment] 2019-01-30 22:50
Here's an example of a complex string that fails: `http://server1,server2:1234/?foo=bar`

To correct, add backslashes before colons and commas: `http\://server1\,server2\:1234/?foo=bar`

I think that properly resolves as a string instead of appearing as multiple key:value pairs separated by commas.

I'd suggest rancher merges the values.yaml and the answers.yaml, then applies using the helm file operations instead of with `--set` command line arguments. That will have many attack/breakage vectors.

**Comment by deniseschannon** [comment] 2019-04-09 00:08
@guangbochen is this fixed in v2.2.0?

**Comment by guangbochen** [comment] 2019-04-09 14:16
Yes, in rancher v2.2 user can now use real YAML formatted input with the `Edit as YAML`, and it should support comma separated values.

**Comment by deniseschannon** [comment] 2019-04-19 04:08
Please try out v2.2 and let me know if anyone still has issues.

**Closed by deniseschannon** 2019-04-19 04:08 UTC
Labels: area/catalog, kind/bug, team/cn

**Comment by marcstreeter** [comment] 2019-05-03 14:48
I noticed this error when installing the Wordpress MultiCluster App.  It was pure chance though because I was using the password generated when pressing the 'Generate' button for `Wordpress Password` under the `Wordpress Settings` section.  I read this forum and noticed that the password it generated had a comma. I removed the comma (as I had saved the password elsewhere and was using it each successive attempt to create a WordPress blog app) and it fully deployed.  It was even more by chance though if you really think about it...because I never even intended to use Wordpress this is the first time I deployed an App through Rancher, because I'm a totally new user.

**Comment by deniseschannon** [comment] 2019-05-03 22:20
@marcstreeter it sounds like you hit this issue: https://github.com/rancher/rancher/issues/19737

**Comment by mathisonryan** [comment] 2019-11-19 19:46
I have a Jenkins job that does rancher app installs in order to dynamically bring up an environment based off of environment config.  To pass in unique values to each app, we have been using --values to pass through a values file.  However, we recently needed to have one of the values be a json object {"key1":"val1","key2":"val2"} so it can be mapped to a json file.  When I try this I continually  get _"(cannot end with ,)"_ no matter what I do.  I have have wrapped in it "", '' and have used both --values and --answers.  Is there any way for me to pass in this string from rancher app install.
