### ISSUE TITLE
Rancher logs have multiple Info level `ensuring designated init node` logs

### ISSUE THREAD

**Issue by sowmyav27** [rancher/rancher#36773] opened 2022-03-06 22:28 UTC
**Rancher Server Setup**
- Rancher version: 2.6-head commit id: `4df2214`
- Installation option (Docker install/Helm Chart): docker install

**Information about the Cluster**
- Kubernetes version: `v1.22.7+rke2r1`
- Cluster Type (Local/Downstream): Downstream - RKE2 DO 3 etcd, 2 control plane and 3 worker nodes

**User Information**
- What is the role of the user logged in? (Admin/Cluster Owner/Cluster Member/Project Owner/Project Member/Custom) : admin

   
**Describe the bug**
Rancher logs have multiple Info level `ensuring designated init node` logs

**To Reproduce**

1. Deployed RKE2 cluster
2. Multiple times these logs are seen in Rancher server. 
3. No snapshots are in progress

**Result**
Rancher logs:
```
2022/03/06 22:19:32 [INFO] [planner] rkecluster fleet-default/sow-issue-2: waiting: provisioning worker node(s) sow-issue-2-pool3-56c65785bc-w2xcc: waiting for probes: calico
2022/03/06 22:19:44 [INFO] rkecluster fleet-default/sowmya-restore-1: ensuring designated init node: sowmya-restore-1-pool1-acab8e03-tklhw
2022/03/06 22:19:45 [ERROR] Error during subscribe websocket: close sent
2022/03/06 22:20:11 [INFO] rkecluster fleet-default/sowmya-restore-1: ensuring designated init node: sowmya-restore-1-pool1-acab8e03-tklhw
2022/03/06 22:20:14 [INFO] rkecluster fleet-default/sowmya-restore-1: ensuring designated init node: sowmya-restore-1-pool1-acab8e03-tklhw
2022/03/06 22:20:27 [INFO] rkecluster fleet-default/sowmya-new-etcd-snapshot-backup-restore: ensuring designated init node: sowmya-new-etcd-snapshot-backup-restore-pool1-a57751e3-vt5pf
2022/03/06 22:20:37 [INFO] rkecluster fleet-default/sowmya-new-etcd-snapshot-backup-restore: ensuring designated init node: sowmya-new-etcd-snapshot-backup-restore-pool1-a57751e3-vt5pf

2022/03/06 22:21:05 [INFO] rkecluster fleet-default/sowmya-new-etcd-snapshot-backup-restore: ensuring designated init node: sowmya-new-etcd-snapshot-backup-restore-pool1-a57751e3-vt5pf
2022/03/06 22:21:06 [INFO] rkecluster fleet-default/sowmya-new-etcd-snapshot-backup-restore: ensuring designated init node: sowmya-new-etcd-snapshot-backup-restore-pool1-a57751e3-vt5pf
```

**Expected Result**
Question: Why do these logs appear multiple times in the rancher logs? There is no manual and recurring snapshots occurring.

**Comment by jiaqiluo** [comment] 2022-03-07 17:45
Hi @sowmyav27, based on the code, the `ensuring designated init node` log is expected to see multiple times when restoring a snapshot. Could you double-check if there are snapshot restoring happening when you see the above logs?

**Comment by sowmyav27** [comment] 2022-03-08 06:21
@jiaqiluo Restore isnt working currently in the scenarios i have been testing. So no, there were no snapshot restores in process.

**Comment by jiaqiluo** [comment] 2022-03-08 19:26
Hi, @sowmyav27. Thanks for the confirmation! 
I have double-checked the code and confirmed with other engineers that those logs would show up only when a snapshot restore is processing. I can not find why you see those logs when you are provisioning clusters, and there is no manual/scheduled snapshot restore that happens. 

Also, I could not reproduce this issue on v2.6-head 3df76e4

For now, I will leave the issue as it is, and if you or anyone else hit this issue, please leave a comment and raise the issue again.

**Comment by jiaqiluo** [comment] 2022-03-08 23:38
Moved this to "To Test" so it will show under QA's radar

**Comment by snasovich** [comment] 2022-03-09 16:01
Moving back to review until the linked PR is merged.

**Comment by Oats87** [comment] 2022-03-09 16:32
### Root cause
The v2prov planner was receiving an `ErrSkip` from the init node manipulation functions with multiple etcd/controlplane node clusters during re-election/designation of an init node. This was fine for initial provisioning/health correcting a cluster, but posed problems in etcd snapshot functionality as it was short circuiting the logic and thus causing the provisioner to get stuck. 

### What was fixed, or what changes have occurred
The helper function for clearing the init node mark (label) will no longer always return an `ErrSkip`, and will instead now return `nil` if no change is made to the labels.

### Areas or cases that should be tested
The area of the issue. 

### What areas could experience regressions?
N/A. I don't see much potential for regression here unless there was a pre-existing reliance somewhere in the code on the faulty logic. 

### Are the repro steps accurate/minimal?
I think so

**Comment by sowmyav27** [comment] 2022-03-13 04:56
**On 2.6-head commit id: `f904267`**

- Deployed an EC2 node driver RKE2 cluster.
- No snapshots were taken
- `ensuring designated init node` message is not seen on the cluster
- And during restore this message is seen a few times.
- Logging a new [issue](https://github.com/rancher/rancher/issues/36870) to move these logs into debug level

**Closed** 2022-03-17 00:16 UTC
Labels: kind/bug-qa, [zube]: To Test, area/rke2, team/area2
