### ISSUE TITLE
templatecontents are not cleaned up after removing template

### ISSUE THREAD

**Issue by superseb** [rancher/rancher#16076] opened 2018-10-11 14:15 UTC
Removing templates and templateversion was covered in https://github.com/rancher/rancher/issues/15212. 

But it seems that templatecontents are left behind.

Quick test script:
```
#!/bin/bash

# Get all templateversions and save
kubectl get templateversions -o json | jq -r '.items[] | .spec.files[], .spec.readme' | sort -u > versions
# Get all icons and save
kubectl get templates -o json  | jq -r '.items[].spec.icon' | sort -u >> versions

# Get all templatecontents and save
kubectl get templatecontents -o json | jq -r .items[].metadata.name  | sort -u > contents

# Show count of dangling templatecontents
DIFF=$(grep -F -x -v -f versions contents)
#echo $DIFF
grep -F -x -v -f versions contents | wc -l
```

**Comment by erikwilson** [comment] 2019-02-15 23:52
This should be fixed as part of rancher/rancher/issues/14322 PR (https://github.com/rancher/rancher/pull/17596). We are no longer using template contents to store data, and remove the collection upon startup.

**Comment by erikwilson** [comment] 2019-02-20 23:52
Since we are no longer using template contents, the best way to test this fix is to follow the instructions for testing rancher/rancher/issues/14322

**Comment by cjellick** [comment] 2019-02-22 15:42
rest are assigned to @bmdepesa. ill just assign this one over too

**Comment by bmdepesa** [comment] 2019-02-25 22:10
rancher/rancher:master 2/25

* Reproduced original issue (+ steps in #14322)
* Upgraded to master
* There were no templatecontents remaining

**Closed by bmdepesa** 2019-02-25 22:10 UTC
Labels: kind/bug, status/to-test, team/az, version/2.0
