### ISSUE TITLE
Add functionality to specify limit of app revisions stored

### ISSUE THREAD

**Issue by cnuber** [rancher/rancher#20654] opened 2019-06-04 13:35 UTC
There is currently no limit to the number of apprevision objects that will be stored for an app deployed through the Rancher Catalog.  Over time this can lead to performance issues in the etcd store and likely Rancher itself.  For users that wish to deploy their custom applications as Rancher Catalog Apps this number of objects can increase rapidly with continuous deployment.
**What kind of request is this (question/bug/enhancement/feature request):**
enhancement
**Steps to reproduce (least amount of steps as possible):**
1.  Deploy an app via the Rancher Catalog.
2. Upgrade/Modify the app
**Result:**
A new apprevision object is created for the app.  
**Other details that may be helpful:**
The desired functionality would be to have the ability to set a limit for the number of apprevisions that can be stored for an app when deploying it.  The ability to delete old app revisions from the Rancher UI and CLI is also desired.
**Environment information**
- Rancher version 2.2.3
- Installation option (single install/HA): Single and HA

gz#14990
gz#16168
gz#15715
gz#14921

**Comment by ebauman** [comment] 2020-10-01 16:03
This brought down a Rancher cluster because of an insane number of app revisions.

"Something" happened to cause a failure in a monitoring deployment in a downstream cluster. I was not able to determine the RCA of that. 
However, the outcome was that the redeploying of our monitoring tools caused 274,000 apprevisions to clog up etcd. This, in turn, caused an OOM issue in kube-apiserver because of all the watches.

We need to cap the apprevisions to prevent this failure scenario.

**Comment by evhan** [comment] 2021-01-20 20:09
The same happened to us, ~2GB of apprevisions built up for apps that are updated regularly for CI purposes, which brought etcd to its knees. We were surprised to find that old apprevisions are never pruned. Beyond just allowing this to be configured, I think it would be good if there were a default limit in place as well, something like 10 revisions.

**Comment by abh** [comment] 2021-01-21 09:16
Our cattle-prometheus / monitoring app keeps getting redeployed / changed — over some months it built up ~100k revisions which, yes, also made the cluster unusable until we shutdown rancher and “by hand” got etcd purged of this.

**Comment by superseb** [comment] 2021-03-16 18:51
Discussed to fix this:
- Add a post action to install/upgrade to fetch existing revisions and remove anything over the max amount of revisions configured (hardcoded or configurable)

**Comment by genexpr** [comment] 2021-11-08 20:16
Also, will need to establish the rules for validating the max number of stored app revisions. Would zero be allowed?

**Comment by StrongMonkey** [comment] 2021-11-08 20:55
1. We can trigger the purge process during next install/upgrade. By doing that we can avoid delete stuff upon upgrade if user doesn't trigger any install/upgrade action. If there is a currently flapping app(keep installing/upgrading), it will be cleaned on the next upgrade triggered by rancher.
2. Yes I think we should forward-port.
3. Zero should probably default to 10(or the default value).

**Comment by genexpr** [comment] 2021-11-15 20:48
Just to confirm, @StrongMonkey, we definitely want a forward-port of this change to v2.6, right?

**Comment by StrongMonkey** [comment] 2021-11-15 20:49
Yes, for upgrade scenario we should forward-port this.

**Comment by genexpr** [comment] 2021-11-16 21:59
# QA Testing
## Root cause

A cluster's database (etcd) stores app revisions for any created or updated app. On each app update, Rancher launches a new version of the app, replacing the old one. It also stores a new item in etcd – information on new app revision. These app revisions tend to accumulate over time. Rancher never cleans them up, which causes etcd to be overflown with app revision data and have performance problems, as a result. If etcd – the cluster database – crashes or works slowly, so does the cluster.

### What was fixed, or what changes have occurred

We now limit the maximum number of app revisions stored in the cluster database. The limit, `MaxRevisionCount`, is configured in the app when it is created. Any app revisions above the limit are deleted on any change to the app (upgrade or rollback). The oldest versions are deleted to maintain the maximum count and not one revision more. if `MaxRevisionCount` is not set or set to a number less than 1, then the default limit is 10. 

### Areas or cases that should be tested

1. A brand new app with MaxRevisionCount set.
2. A brand new app with MaxRevisionCount not set.
3. An existing app that already has many app revisions without a configured `MaxRevisionCount`. By default, the limit of stored app revisions is 10. On any change to the app, Rancher must remove the oldest revisions to maintain the maximum limit of 10. So if the app has 20 revisions, by default, the max is 10. On the next update, Rancher will create a 21st revision and then delete 11 of the oldest to ensure there are at most 10 and no more.

### What areas could experience regressions?

Note that there is an old existing bug where an upgrade to an app creates two revisions, not one.
[#35443](https://github.com/rancher/rancher/issues/35443)
This means you might exceed the max limit with fewer upgrades, but this is not directly related to the problem this issue fixes.

### Steps

In v2.5 Cluster Manager and any project, create a new app (for example, the `redis` app) and set the value for `MaxRevisionCount`. It is not available in the UI but only in the initial request (use the API view to configure it). For example, set the value to 4.

Rollback to any previous version (the same one will work), which will create a new revision. Check the number of app revisions (by either looking at the number of revisions to which you can rollback in the UI or running `kubectl get apprevisions -A` in the kubectl shell. This number should never exceed the `MaxRevisionCount` for this app you had set before.

Keep making new revisions to verify that the oldest revisions are deleted to make "room" for new app revisions until you hit the max. You will come to a point where only 4 versions will exist at a time (if you had set the max to 4).

**Comment by Tejeev** [comment] 2021-12-01 06:03
Is there anything to limit the number of cataloguetemplaterevisions?  I saw  34997 management.cattle.io/catalogtemplateversions on a customer cluster that was seeing oom events on their Rancher cluster and it seems excessive.  Would it make sense to have the ability to limit all revisions of things to some history length to prevent similar problems with other types of revisions?

**Comment by jmcsagdc** [comment] 2021-12-02 00:25
Reproduced in 2.6.2 - allowed to create an apparently endless number of revisions. I stopped at 16

Verified fixed in 2.6.3-rc3 where the default max is 10 and they are trimmed according to age with the oldest leaving first.

Steps summary:
1. Use the old UI, click to *local* cluster, Apps and deploy something like redis or longhorn into Default
2. Go to the local cluster > Default and see your deployed app. Click the ellipsis menu and upgrade
3. Click the drop-down and change versions (repeat as much as you want)
4. Go to the Cluster Dashboard and click the Kubectl icon to get the shell and execute the `kubectl get apprevisions -A` command and count your revisions

EXPECTED:
Max 10 should appear, oldest removed first past that.

The scenarios listed above tested successfully as well:

1. A brand new app with MaxRevisionCount set.
2. A brand new app with MaxRevisionCount not set.
3. An existing app that already has many app revisions without a configured MaxRevisionCount

So if you use the API to reset to lower maximum values like 4 or 3, the next time you create a revision, the oldest X above your max are removed when the newer one is added where you end with your max number used.

Upgrading the deployed app

![upgrade-app](https://user-images.githubusercontent.com/15971368/144335501-11b05130-8819-4fb8-ba98-32267880942a.jpg)

Screenshot of 2.6.2 (old) behavior:

![262-no-limit](https://user-images.githubusercontent.com/15971368/144333546-6e3b543f-abb3-4322-a627-00b998f9c2c9.jpg)

2.6.3-rc3 max set to 10

![263rc3-max-set-10](https://user-images.githubusercontent.com/15971368/144333647-5ddbd3b8-3ce0-4271-a7c6-83927e176677.jpg)

Change the setting via API

![api-setting](https://user-images.githubusercontent.com/15971368/144334295-fdf4609f-2386-450d-8974-3ee1dd0f207a.jpg)

2.6.3-rc3 max getting reduced and the purges after new upgrade/rollbacks

![reduced-max](https://user-images.githubusercontent.com/15971368/144334021-5d5873c1-1371-4db7-ab91-64eebb3743c9.jpg)

**Comment by abh** [comment] 2021-12-02 01:13
Thank you @genexpr, @Jono-SUSE-Rancher, @deniseschannon, @sowmyav27 for following up on this and seeing this issue through. And in particular thanks to @jmcsagdc for the careful and comprehensive testing to make sure it's comprehensively fixed.

**Comment by jmcsagdc** [comment] 2021-12-03 01:10
**Rancher Server Setup**
- Rancher version: 2.6.2 - 2.6.3-rc3
- Installation option (Docker install/Helm Chart):
   terraform single-vm rancher in AWS
- Proxy/Cert Details: self-signed

**Describe the bug**
if i install the redis app in 2.6.2 and upgrade to 2.6.3, max revisions is set to 0 and I can't upgrade or rollback the app

**To Reproduce**

1. Use the old UI, click to local cluster, Apps and deploy something like redis or longhorn into Default
2. Go to the local cluster > Default and see your deployed app. Click the ellipsis menu and upgrade
3. Click the drop-down and change versions (repeat as much as you want)
4. Go to the Cluster Dashboard and click the Kubectl icon to get the shell and execute the `kubectl get apprevisions -A` command and count your revisions 
5. Repeat until you have over 10 revisions
6. upgrade to 2.6.3-rc3
7. try to upgrade and rollback your app

**Result**
Rollback causes error (see screenshot and gif)
Upgrade does nothing (see gif)
Max revisions is set to 0 (zero)

**Expected Result**
It seems like the max-revisions should be set to 10 and upgrade/rollback should work.

**Screenshots**
The previously installed redis app has max revisions set to 0

![max-0](https://user-images.githubusercontent.com/15971368/144499278-ae7ba841-fc86-4601-bcbf-f9a4c8654f2e.jpg)

If you install longhorn into local at this point, longhorn's max-revisions is set to 10

![new-longhorn](https://user-images.githubusercontent.com/15971368/144499289-23961bcd-93eb-4603-aaf2-83fe24733600.jpg)

The error and behavior

![rollback-error](https://user-images.githubusercontent.com/15971368/144499280-b73e02d5-f0fa-43a6-ab67-c580982100a0.jpg)
![upgrade-rollback-fails](https://user-images.githubusercontent.com/15971368/144499282-c1153a6b-135d-4d6d-93c1-3ddac74708d6.gif)

Manually adjusting the redis from 0 to something else via the api is blocked:
![manual-adjust-after-upgrade](https://user-images.githubusercontent.com/15971368/144500784-713760af-355e-4ad8-9e1f-91e656039f6e.jpg)

**Comment by jmcsagdc** [comment] 2021-12-03 01:12
added this to https://github.com/rancher/rancher/issues/35726 and closing this ticket in favor of continuing the work in older bug

**Comment by jmcsagdc** [comment] 2021-12-03 01:17
Will run the following cases:

1. preupgrade 0 apprevisions then upgrade Rancher, and try setting new max limit for app
2. preupgrade 0 apprevisions then upgrade Rancher and try upgrading app
3. and same cases with longhorn as the app instead of redis to see if it is all charts or some that show this

**Comment by sowmyav27** [comment] 2021-12-03 19:55
`Rancher max version exceeded` issue should be fixed by - https://github.com/rancher/rancher/issues/35680

**Comment by genexpr** [comment] 2021-12-14 00:24
There has been a code change to this issue. Now, before Rancher decides to remove extra app revisions, it always sorts all revisions for an app by creation timestamp – starting with the oldest revision. This way, it can guarantee to remove the **oldest** revision(s).

For QA: please check that the oldest revision(s) is always evicted and replaced with a new one on app upgrade/rollback.
With kubectl, you can sort the listing of app revisions like this:
`kubectl get apprevisions -A --sort-by={metadata.creationTimestamp} --no-headers`

For example, if the oldest one is removed, then the second oldest from before is now the oldest one.

**Comment by jmcsagdc** [comment] 2021-12-14 16:55
Verified fixed in v2.6-04520c0ab56440fe8a0e9b3dc1ceb26e8f5ad416-head

1. The sort and ejection is as expected (screenshot)
2. App rollback, upgrade works repeatedly as expected
3. API changes to the limit of revisions works as expected - Adjusting up or down the setting behaves as expected
4. Upgrade from 2.5 to 2.6 with an installed app like longhorn allows upgrade, rollback, etc.
5. removing and Adding app behaves appropriately
6. Initial value for setting is 10 revisions (as expected)

![head-fix-upgrade-rollback-sort](https://user-images.githubusercontent.com/15971368/146043322-da645565-db12-4f94-97ad-bbc81b8f9213.jpg)

**Closed by jmcsagdc** 2021-12-14 16:55 UTC
Labels: kind/enhancement, area/catalog, internal, [zube]: QA Working, QA/XS, feature/apps-mgmt

**Comment by pyfdtic** [comment] 2022-01-05 09:16
are this param `maxRevisionCounts` support on old rancher version ? like 2.4.X or  2.5.X

**Comment by genexpr** [comment] 2022-01-05 15:10
@pyfdtic, yes, this parameter will be available in 2.5.12, once it's out.

**Comment by vynguyenchantal** [comment] 2022-09-26 13:20
Hi!
1. I'm using Rancher 2.4.17, rancher nodes crashed due to too many apprevisions. Is there an available utility written by someone to cleanup OLD apprevisions?
2. I'm in the process of upgrading to Rancher 2.6.3. How do I define the `maxRevisionCounts`?
Thank you!

**Comment by vynguyenchantal** [comment] 2022-09-26 13:32
Hi again!
Looking in Rancher 2.6.3 UI, the Rollback on the app (right-click the vertical 3 dots) isn't available but it's available for Workloads (i.e. DaemonSets, Deployments, StatefulSets, etc). I deployed the app twice and I clicked Rollback, The Roll Back <app_name> does NOT show any revisions.
