### ISSUE TITLE
Default values for service links are being prepended with stack namespaces, fails validations

### ISSUE THREAD

**Issue by schuylr** [rancher/rancher#7383] opened 2017-01-11 19:01 UTC
**Rancher Versions:**
Server: 1.2.2

![screen shot 2017-01-11 at 1 59 20 pm](https://cloud.githubusercontent.com/assets/12628715/21862240/5a06ee62-d806-11e6-8a47-50dcf49819ec.png)

Normally it would just use "etcd" as the service name but it is populating with `stack-name/service-name` when the value was previously blank. The `/` fails validation in the API.

Apologies if this is a duplicate.

**Comment by tfiduccia** [comment] 2017-01-11 19:39
@schuylr 
I'm not able to reproduce this issue.  Can you give me more information?  What type of environment are you using?  Is this a catalog stack?

**Comment by schuylr** [comment] 2017-01-11 19:59
@tfiduccia It's a cattle environment. Try editing or clicking "upgrade" on an existing service that used a blank value previously.

In my example, I normally left the "As Name" field blank for "etcd", since it resolves to that automagically. However now when editing or upgrading, it populates this into the "As Name" field.

Here's screenshots walking through what happens:

1. Click "Edit Service", add a new Service Link, leave the "As Name" empty. Clicking "Update" works.

![screen shot 2017-01-11 at 2 57 49 pm](https://cloud.githubusercontent.com/assets/12628715/21864141/7125947e-d80e-11e6-8094-5940304b4e95.png)

2. Click "Edit Service" again, notice the "As Name" field has now been unhelpfully populated with "janitor/cleanup". This fails when clicking "Update"

![screen shot 2017-01-11 at 2 58 02 pm](https://cloud.githubusercontent.com/assets/12628715/21864178/9939ddd0-d80e-11e6-9924-86ef58a1d128.png)

![screen shot 2017-01-11 at 2 58 11 pm](https://cloud.githubusercontent.com/assets/12628715/21864181/9c2f4200-d80e-11e6-861a-f4a286e59d08.png)

**Comment by tfiduccia** [comment] 2017-01-11 20:06
@schuylr - Oh yes, I see what you mean.  We did have a previous report of this and it was fixed in 1.3.  I retested to make sure and was able to reproduce it in 1.2.2 and no longer able to reproduce in 1.3.

**Closed by tfiduccia** 2017-01-11 20:06 UTC

**Comment by schuylr** [comment] 2017-01-11 20:11
Thanks!
