### ISSUE TITLE
Certificates private key not valid error

### ISSUE THREAD

**Issue by guy-menlo** [rancher/rancher#13379] opened 2018-05-09 09:28 UTC
**Rancher versions:**
rancher/server or rancher/rancher: 2.0
rancher/agent or rancher/rancher-agent: 2.0

**Steps to Reproduce:**

I'm trying to install an SSL cert for a workload. However when I copy the lets encrypt cert in, private and public key, I get an error the "Private Key is invalid. Please make sure it is a RSA key."

The private key and certificate are valid.

**Comment by OBenned** [comment] 2018-05-09 09:41
Try converting your private key to RSA: openssl rsa -in server.key -out server_new.key
That did it for me

**Comment by guy-menlo** [comment] 2018-05-09 09:49
My Key is already an RSA file.

**Comment by superseb** [comment] 2018-05-09 13:27
Duplicate of https://github.com/rancher/rancher/issues/13156

**Closed by superseb** 2018-05-09 13:27 UTC
