### ISSUE TITLE
Tracking: Upstream etcd v3.5 issues

### ISSUE THREAD

**Issue by phillipsj** [rancher/rancher#37157] opened 2022-04-01 14:38 UTC
**Describe the bug**
 Upstream etcd posted that there are issues with v3.5 and that everyone should stay on 3.4.x and only upgrade once 3.5.3 is released. 

https://groups.google.com/a/kubernetes.io/g/dev/c/B7gJs88XtQc/m/rSgNOzV2BwAJ

**Comment by rosskirkpat** [comment] 2022-04-07 16:52
The upstream [issue](https://github.com/etcd-io/etcd/issues/13766) has been closed and a new release of etcd, v3.5.3, is being tracked [here](https://github.com/etcd-io/etcd/issues/13894)

There is a [fix](https://github.com/etcd-io/etcd/pull/13854) in upstream etcd merged in main and a [backport](https://github.com/etcd-io/etcd/pull/13854) to the release-3.5 branch.

We should prepare for an etcd bump once this release is out (currently unknown ETA). However, the issue with data inconsistency will not necessarily be fixed in it's entirety in the 3.5.3 release per this [comment](https://github.com/etcd-io/etcd/issues/13894#issuecomment-1091184961)

> It would be great to have automatic way to prevent data inconsistencies in the future, however this is not required immediate release.

**Comment by rosskirkpat** [comment] 2022-04-07 18:51
cc: @deniseschannon @Jono-SUSE-Rancher @kinarashah @sirredbeard 

It looks like the upcoming v3.5.3 release of etcd will not have a full fix for the data inconsistency issue. We should discuss what our plan looks like for 2.6.5

**Comment by serathius** [comment] 2022-04-08 08:20
Sorry for confusion in wording of the message you quoted, v3.5.3 will fully the data inconsistency issue. What we are not planning is automatic testing/reproduction as this will be done manually.

**Comment by rosskirkpat** [comment] 2022-04-08 16:40
Thank you for the clarification @serathius! That's great to hear.

**Comment by kinarashah** [comment] 2022-04-26 19:42
etcd bump to v3.5.3 is getting updated as a part of https://github.com/rancher/rancher/issues/37388 for RKE1 clusters.

**Closed** 2022-05-02 21:24 UTC
Labels: kind/bug, area/etcd, [zube]: Done, alpha-priority/1, area/k8s-support, feature/k8s-version, team/area2, [zube]: Team Area 2
