### ISSUE TITLE
Initialization scripts for node agent

### ISSUE THREAD

**Issue by alexandrem** [rancher/rancher#14393] opened 2018-07-04 16:49 UTC
I'm thinking about the best way to add some initialization steps for nodes being provisioned by Rancher without changing too much code.

**Use case**

I'd like to execute some pre-provision steps before docker and kubelet is installed on the node.

A typical use case is to prepare the disk for the Docker daemon storage, e.g using an ephemeral drive attached to a cloud instance (e.g /dev/vdb), partition and format the volume and add the systemd drop-in unit for the Docker service.

Another initialization step would be adding a custom time server on the host when running in a on-prem air gap environment, since the preconfigured time servers in public cloud images (e.g ubuntu or CoreOS) aren't reachable.

**Approach**

The simplest way would be to customize the `run.sh` script that gets executed by the rancher-agent before the agent binary. However, I'm trying to think about a generic approach to be flexible for different steps to be executed on the node.

In the past, I've been doing these kind of things via user data and CoreOS ignition.

It's not really practicable to do this with Rancher and the way the docker-machine provisioning works for multi tenancy.

**Comment by alexandrem** [comment] 2018-07-04 17:08
To give more insights, as a Rancher operator I want to simplify to the provisioning of nodes on some providers (e.g openstack) and automate some initialization steps that must occur on every host.

To goal is to simply nodes provisioning for all users in an on-premise environment.

Having a default openstack node template "userDataFile" with a URI could be useful, as long as it's filled automatically by default and no one can overwrite it. Seems a bit hacking to implement though.

**Comment by alexandrem** [comment] 2018-07-04 17:47
It seems like `userDataFile` cannot really be used for that purpose, since the docker-machine client wants a local file.

This and both the `keypairName` and `privateKeyFile` are useless in Rancher multi-tenant context.

**Comment by superseb** [comment] 2018-07-04 18:01
Duplicate of https://github.com/rancher/rancher/issues/13720

**Closed by superseb** 2018-07-04 18:01 UTC

**Comment by superseb** [comment] 2018-07-04 18:02
Not so sure if you want to execute steps after provisioning or in the agent? I think both can be covered in https://github.com/rancher/rancher/issues/13720

**Comment by alexandrem** [comment] 2018-07-05 04:17
Ideally it would be before docker is installed and running.

Which after some more digging and analysis made me realize that the cattle-node-agent is not the best place neither, since kubelet is already running at this point with some other daemonset containers being initalized or already running.

I guess it's possible to do at the same time as the agent, but it's annoying having to reload the docker systemd unit and I'm not sure what's going to happen with the existing containers if the storage path changes. Taking this into consideration, one would probably rather consider deploying his own privileged daemonset to achieve the same results, yet it's not ideal.

I suppose we can move this discussion in #13720 to elaborate on different approaches.
