### ISSUE TITLE
[BUG] Helm chart 2.8.0 not found in rancher-stable repo

### ISSUE THREAD

**Issue by santimar** [rancher/rancher#43780] opened 2023-12-13 10:53 UTC
**Describe the bug**
Rancher 2.8.0 has been released a week ago, and I expected to find it in the `rancher-stable` helm repo, but I can find it only in `rancher-latest` right now

**To Reproduce**
```
> helm search repo rancher-latest
NAME                  	CHART VERSION	APP VERSION	DESCRIPTION                                       
rancher-latest/rancher	2.8.0        	v2.8.0     	Install Rancher Server to manage Kubernetes clu...

> helm search repo rancher-stable
NAME                  	CHART VERSION	APP VERSION	DESCRIPTION                                       
rancher-stable/rancher	2.7.9        	v2.7.9     	Install Rancher Server to manage Kubernetes clu...
```

If this behavior is intended, how can I know when a release is promoted to `rancher-stable` helm repo?

**Comment by dan05011991** [comment] 2023-12-13 19:05
This is not a bug, this is intentional. Rancher releases only move to stable after X amount of time. I don't know what the conditions are, I'd guess before a few patches get released. 

I'll let the devs confirm.

**Comment by Oats87** [comment] 2023-12-14 16:41
Yes, can confirm this is intentional as 2.8.0 is not a marked a stable release. Closing issue.

**Closed by Oats87** 2023-12-14 16:41 UTC
Labels: kind/bug
