### ISSUE TITLE
Node Not always removed from GUI

### ISSUE THREAD

**Issue by gregkeys** [rancher/rancher#14687] opened 2018-07-23 01:00 UTC
**Rancher versions:**
Rancher v2.0.6

Deleting a Node does not always remove it from the rancher node list.
it's removed from kubernetes but rancher is stuck in a remove state.
![node_rm](https://user-images.githubusercontent.com/3282427/43052292-21abd69c-8dd9-11e8-9865-a7b7ff9b9655.png)

This particular Node has been in remove state for 5 days, the node does not exists in kubernetes or in aws

**Comment by superseb** [comment] 2018-07-23 06:56
Duplicate of https://github.com/rancher/rancher/issues/11991

**Closed by superseb** 2018-07-23 06:56 UTC
