### ISSUE TITLE
Dangerous DNS behaviour

### ISSUE THREAD

**Issue by bacheson** [rancher/rancher#3100] opened 2015-12-21 17:08 UTC
v0.50.0

I have SERVICE1 in STACKA. I also have SERVICE1 in STACKB.

Within STACKB nslookup SERVICE1 is resolving to the service in STACKA. 

The containers all have network=host and the container network enabled. Basically the stacks are not being respected. Is this expected behaviour?

**Comment by bacheson** [comment] 2015-12-21 17:21
Ok this is even more interesting. I've enabled managed networking on all services. This re-produces another baffling situation:

StackA
-service1
-service2
-service3

StackB
-service2

in StackA
  1) nslookup service2 -> StackA:service2
  2) stop service2
  3) nslookup service2 -> StackB:service2

This is extremely dangerous behaviour.

**Comment by deniseschannon** [comment] 2015-12-22 21:54
This is a known issue and duplicate of https://github.com/rancher/rancher/issues/2873. I will close in favor of the other one.

**Closed by deniseschannon** 2015-12-22 21:54 UTC

**Comment by liubaishui** [comment] 2015-12-25 12:29
I have the same error.

**Comment by Rucknar** [comment] 2016-01-06 11:08
+1
