### ISSUE TITLE
rancher v1.1.0+ rancher compose do not support chinese

### ISSUE THREAD

**Issue by Irving23** [rancher/rancher#5533] opened 2016-07-25 03:29 UTC
rancher v1.0.1  rancher compose support chinese
but rancher v1.1.0 rancher compose do not support chinese

**Comment by deniseschannon** [comment] 2016-07-25 04:25
Duplicate of https://github.com/rancher/rancher/issues/5414

This is due to the parser that was changed in libcompose.

**Closed by deniseschannon** 2016-07-25 04:25 UTC
