### ISSUE TITLE
rancher unsets http_proxy|https_proxy|HTTP_PROXY|HTTPS_PROXY Env Variables

### ISSUE THREAD

**Issue by HenryTheSir** [rancher/rancher#7207] opened 2016-12-28 10:15 UTC
Rancher Version:
1.2.2 with rancher/metadata:v0.6.8 and rancher/network-manager:v0.2.19
Docker Version:
1.12.5
OS and where are the hosts located? (cloud, bare metal, etc):
VMware - Ubuntu 16.04.01
Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)
Single Node Rancher with External DB
Environment Type: (Cattle/Kubernetes/Swarm/Mesos)
Cattle
Steps to Reproduce:
Deploy any container with ENV Variable for http_proxy|https_proxy|HTTP_PROXY|HTTPS_PROXY either in docker image itself or in Rancher GUI.
Results:
ENV Variable is null if container is launched. (Starting from the same image direct on the commandline works just fine and sets the ENV Variables)
Expected:
Either the possibilty to set the Variables in Rancher GUI or to set these Variables in the Docker Image so that the running container has these ENV Variables set.

**Comment by HenryTheSir** [comment] 2016-12-28 12:51
Additional: If I try to set env https_proxy=xyz in an running container it gets set but seconds later it is unset again.

**Comment by DenverJ** [comment] 2017-01-03 05:23
We are having this issue as well and it will affect anyone who needs to use a proxy without configuring it in the agent. From what I can see this has been fixed with [rancher/agent#114](https://github.com/rancher/agent/pull/114) mentioned above. How do the github releases for the rancher agent relate to the Docker Hub releases? Looking at the github releases for the rancher agent this issue is fixed in v0.5.0 but the version scheme doesn't seem to match Docker hub. I can confirm that this has been fixed in 1.3.0-rc* releases.

**Comment by aemneina** [comment] 2017-01-04 07:39
The issue is present in 1.2.2, but fixed in 1.3.0.

**Comment by aemneina** [comment] 2017-01-04 07:40
as @HenryTheSir states here's the original issue: https://github.com/rancher/rancher/issues/7095 closing this out.

**Closed by aemneina** 2017-01-04 07:40 UTC
