### ISSUE TITLE
Confirm existence of S3 credentials before saving RKE template

### ISSUE THREAD

**Issue by panlith** [rancher/rancher#23629] opened 2019-10-23 14:16 UTC
**What kind of request is this (question/bug/enhancement/feature request):**
RFE

**Steps to reproduce (least amount of steps as possible):**
-On Rancher 2.3.1 create RKE template and select S3 as backup target for etcd snapshots.
-Do not provide any credentials(or even no input at all in any of the S3 related fields).
-Hit Create

**Result:**
Template gets created even S3 credentials are missing.

Upon RKE template creation with etcd snapshot target set to S3, while no S3 credentials have been provided, there is nothing to prevent user to save the template. Adding checks if S3 fields have values would be beneficial at this point, rather than end up applying the RKE template with no credentials.

Same check mechanism should also cover the case of cloned revision of an existing RKE template(where S3 credentials were provided this time), preventing the user to save the cloned template without providing S3 credentials(especially the secret key since its omitted due to clone operation).

**Comment by alena1108** [comment] 2019-10-23 23:26
@panlith it's an intended behavior. Credentials became non-required field as a part of letting user leverage IAM on the etcd node for etcd snapshot backups to s3 
 https://github.com/rancher/rancher/issues/21314

Proper credentials validation is done when either api or secret key is passed https://github.com/rancher/rancher/issues/20889

We can perhaps add some tooltip in the UI to make sure user is aware of this functionality. I'm going to close this issue; please open a UI enhancement request if you think the tooltip would be useful.

**Closed by alena1108** 2019-10-23 23:26 UTC
Labels: internal, kind/feature
