### ISSUE TITLE
Failed to find system chart fleet-crd will try again in 5 seconds: configmaps "rancher-charts-plx5s" not found

### ISSUE THREAD

**Issue by 504274990** [rancher/rancher#29926] opened 2020-11-04 09:45 UTC
**What kind of request is this (question/bug/enhancement/feature request):**
question

**Steps to reproduce (least amount of steps as possible):**
When I newly deployed rancher, some errors appeared in the rancher log

**Result:**
```
2020/11/04 09:38:46 [ERROR] Failed to find system chart fleet-crd will try again in 5 seconds: configmaps "rancher-charts-plx5s" not found
2020/11/04 09:38:51 [ERROR] Failed to find system chart fleet-crd will try again in 5 seconds: configmaps "rancher-charts-plx5s" not found
2020/11/04 09:38:56 [ERROR] Failed to find system chart fleet-crd will try again in 5 seconds: configmaps "rancher-charts-plx5s" not found
2020/11/04 09:39:01 [ERROR] Failed to find system chart fleet-crd will try again in 5 seconds: configmaps "rancher-charts-plx5s" not found
2020/11/04 09:39:06 [ERROR] Failed to find system chart fleet-crd will try again in 5 seconds: configmaps "rancher-charts-plx5s" not found
```

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): v2.5.1
- Installation option (single install/HA):  HA

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): Hosted
- Machine type (cloud/VM/metal) and specifications (CPU/memory):  VM 4C/16G
- Kubernetes version (use `kubectl version`):  v1.18.10

```
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.10", GitCommit:"62876fc6d93e891aa7fbe19771e6a6c03773b0f7", GitTreeState:"clean", BuildDate:"2020-10-15T01:52:24Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.10", GitCommit:"62876fc6d93e891aa7fbe19771e6a6c03773b0f7", GitTreeState:"clean", BuildDate:"2020-10-15T01:43:56Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
```

- Docker version (use `docker version`):

```
Client: Docker Engine - Community
 Version:           19.03.13
 API version:       1.40
 Go version:        go1.13.15
 Git commit:        4484c46d9d
 Built:             Wed Sep 16 17:02:52 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.13
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       4484c46d9d
  Built:            Wed Sep 16 17:01:20 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.3.7
  GitCommit:        8fba4e9a7d01810a393d5d25a3621dc101981175
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683

```

**Comment by badsector3** [comment] 2020-11-06 00:04
I have the  same issue. Deployed rancher via Helm chart on k3s

`2020/11/05 23:51:12 [ERROR] Failed to find system chart fleet will try again in 5 seconds: configmaps "rancher-charts-kzq5x" not found`

I provided my own TLS:
`helm install rancher rancher-latest/rancher \
  --namespace cattle-system \
  --set hostname=hostname.example.com \
  --set ingress.tls.source=secret`

Rancher UI doesnt work. I cannot use cert-manager as cluster behind firewall and no way  to open ports. 
I added hostname.example.com to  /etc/hosts to be able to login to it but no luck.
Default configuration.
`k3s version v1.18.9+k3s1 (630bebf9)`
`rancher-2.5.1	v2.5.1`

**Comment by rajivml** [comment] 2020-12-26 12:06
I am also facing the same issue 

2020/12/26 12:05:34 [ERROR] Failed to find system chart fleet will try again in 5 seconds: configmaps "rancher-charts-zxh66" not found
2020/12/26 12:05:39 [ERROR] Failed to find system chart fleet will try again in 5 seconds: configmaps "rancher-charts-zxh66" not found
2020/12/26 12:05:44 [ERROR] Failed to find system chart fleet will try again in 5 seconds: configmaps "rancher-charts-zxh66" not found
2020/12/26 12:05:49 [ERROR] Failed to find system chart fleet will try again in 5 seconds: configmaps "rancher-charts-zxh66" not found

**Comment by StrongMonkey** [comment] 2020-12-28 16:55
I believe this is potentially fixed in rancher v2.5.3 by this PR https://github.com/rancher/rancher/pull/30024. I am not able to reproduce this anymore.

**Comment by StrongMonkey** [comment] 2020-12-28 16:57
Assign QA to test for now. If any of you reproduce this in v2.5.3 please make a comment here.

**Comment by Ellenqs** [comment] 2020-12-31 01:52
This issue can not be reproduced. 

Environment information:

Rancher version (rancher/rancher/rancher/server image tag or shown bottom left in the UI): v2.5.1
Installation option (single install/HA): HA

Cluster information:

Cluster type (Hosted/Infrastructure Provider/Custom/Imported): custom

Result:

Can not see the error and was able to create git repo and push it to clusters.

**Comment by Ellenqs** [comment] 2021-01-07 18:04
Validate on v2.5-head, works fine, so closed.

**Closed by Ellenqs** 2021-01-07 18:04 UTC
Labels: [zube]: To Test
