### ISSUE TITLE
Container statistics not working after rancher upgrade from v1.0.2 to v1.1.0

### ISSUE THREAD

**Issue by demarant** [rancher/rancher#5326] opened 2016-07-04 13:06 UTC
**Rancher Version:** 
v1.1.0

**Docker Version:** 
1.10.3

```
[marinis@prod-mil-06 ~]$ docker info
Containers: 14
 Running: 10
 Paused: 0
 Stopped: 4
Images: 12
Server Version: 1.10.3
Storage Driver: devicemapper
 Pool Name: vg_docker-docker--pool
 Pool Blocksize: 524.3 kB
 Base Device Size: 10.74 GB
 Backing Filesystem: xfs
 Data file:
 Metadata file:
 Data Space Used: 9.789 GB
 Data Space Total: 33.97 GB
 Data Space Available: 24.18 GB
 Metadata Space Used: 3.105 MB
 Metadata Space Total: 37.75 MB
 Metadata Space Available: 34.64 MB
 Udev Sync Supported: true
 Deferred Removal Enabled: true
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Library Version: 1.02.107-RHEL7 (2015-12-01)
Execution Driver: native-0.2
Logging Driver: json-file
Plugins:
 Volume: local
 Network: bridge null host
Kernel Version: 3.10.0-327.13.1.el7.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 7.64 GiB
Name: prod-mil-06.pecs.eea
ID: YF4E:KR4V:SAIO:PH46:J7UO:Q23O:OE7O:2AYA:N7TP:LS36:DKPV:KNSP
WARNING: bridge-nf-call-iptables is disabled
WARNING: bridge-nf-call-ip6tables is disabled

```

**OS and where are the hosts located? (cloud, bare metal, etc):** 
CentOS 7 on private/public OpenStack.
Linux prod-mil-06.pecs.eea 3.10.0-327.13.1.el7.x86_64 #1 SMP Thu Mar 31 16:04:38 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
[single rancher node](https://github.com/eea/eea.docker.rancher/blob/master/docker-compose.yml)

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle

**Steps to Reproduce:**
Upgrade to Rancher 1.1.0 from 1.0.2 and look at a container page, the web sockets statistics charts are not appearing. The web sockets connection stats for Hosts works instead.

**Results:** 
the web sockets statistics charts are not appearing. In the browser inspect you see that it tries to upgrade the connection over and over, see screenshot. The stats works on the other hand on hosts.

![rancher-container-stats](https://cloud.githubusercontent.com/assets/320440/16561318/d51195f2-41f8-11e6-9c10-8ed69d52ad1a.jpeg)

**Expected:**
To have the stats working on container as well.

**Comment by deniseschannon** [comment] 2016-07-12 17:19
We've been unable to reproduce this issue. We started up CentOS boxes and are able to see our container stats. 

I know this is Docker 1.11 issue, but it was working with Docker 1.10.3 previously as well.

**Comment by demarant** [comment] 2016-07-16 09:58
@deniseschannon
Thanks, since stats are fed via websockets, maybe it is caused by https://github.com/rancher/rancher/issues/5452 ?

**Comment by deniseschannon** [comment] 2016-08-18 06:22
@demarant Are you still facing this with the latest stable release v1.1.2?

**Comment by demarant** [comment] 2016-09-15 06:29
@deniseschannon 
we are still on 1.1.0 since the release notes of 1.1.1 and 1.1.2 did not mention anything about websockets issues.. it is only v1.1.3 that specifically mention a fix for websockets but mostly for kubernetes, we are using cattle only.

I see lot of issues about container stats not working...I saw this issue https://github.com/rancher/rancher/issues/5253 I will see if time-sync between rancher server and the nodes is the issue.

p.s.
unfortunatly I cannot upgrade Rancher that often anymore because in my last upgrade lot of production VMs went busted by indefinitely spawned rancher-agents upgrades that filled-up the entire disk...
I plan an upgrade to 1.2, but before doing that I need to have a staging rancher server with enough stacks and VMs to simulate a production update and see how it behaves.

**Comment by triton086** [comment] 2016-09-20 01:33
@deniseschannon 
@demarant 

changing Storage Driver from devicemapper to overlay fixed the stats issue.

**Comment by aemneina** [comment] 2016-11-04 15:52
closing issue... please file a new one if you encounter this on the latest or latest stable.

**Closed by aemneina** 2016-11-04 15:52 UTC
Labels: kind/question
