### ISSUE TITLE
 No such container

### ISSUE THREAD

**Issue by phiedulxp** [rancher/rancher#10340] opened 2017-11-15 12:14 UTC
*Describe your issue here*
level=error msg="Can not inspect containers" error="Error: No such container:

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v1.6.10` Cattle: `v0.183.22` UI: `v1.6.23` |
|Access|`localauth` `admin`|
|Orchestration|`Cattle`|
|Route|`hosts.index`|

**Comment by superseb** [comment] 2017-11-15 12:57
Need a bit more context here, is this a duplicate of https://github.com/rancher/rancher/issues/7803 ?

**Comment by superseb** [comment] 2018-02-16 00:04
Closing due to inactivity.

**Closed by superseb** 2018-02-16 00:04 UTC
Labels: area/agent, status/more-info
