### ISSUE TITLE
[main] [UI] [BUG] Not able to set drain options while draining a node

### ISSUE THREAD

**Issue by vardhaman22** [rancher/rancher#48376] opened 2024-12-11 03:15 UTC
**Rancher Server Setup**
- Rancher version: head
- Installation option (Docker install/Helm Chart):
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): RKE
- Proxy/Cert Details:

**Information about the Cluster**
- Kubernetes version: v1.30.7-rancher1-1
- Cluster Type (Local/Downstream):
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider): Downstream

**User Information**
- What is the role of the user logged in? (Admin/Cluster Owner/Cluster Member/Project Owner/Project Member/Custom) Admin
  - If custom, define the set of permissions:

**Describe the bug**

From the list of nodes, select any node and try to drain it. UI box does not have the default options selected and user can not set those options either.
**To Reproduce**

try to drain a node and set the drain options in the UI box
**Result**
can not set any options for node draining 
**Expected Result**

user should be able to set drain options

**Screenshots**

![drain_error](https://github.com/user-attachments/assets/ea7ec6bc-c34b-4353-9ecf-4ea13e956667)

**Additional context**

**Comment by snasovich** [comment] 2024-12-11 14:29
Closing as duplicate of https://github.com/rancher/dashboard/issues/12632

**Closed by snasovich** 2024-12-11 14:29 UTC
Labels: kind/bug
