### ISSUE TITLE
rancher-load-images.sh help information and case parameters are inconsistent

### ISSUE THREAD

**Issue by wanshaoyuan** [rancher/rancher#22594] opened 2019-09-02 14:29 UTC
Rancher-load-images.sh help information and case parameters are inconsistent

![image](https://user-images.githubusercontent.com/16741882/64121256-e592b700-cdd0-11e9-9e5b-213a28d21f2f.png)

**Comment by axeal** [comment] 2019-09-02 15:37
This is a duplicate of https://github.com/rancher/rancher/issues/20779

**Closed** 2019-09-02 18:33 UTC
