### ISSUE TITLE
Containers using the same EBS named volume should not end up in different hosts.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#6721] opened 2016-11-22 00:56 UTC
Rancher-server version - v1.2.0-pre4-rc10

Steps to reproduce the problem:
Deploy rancher-ebs.
Create a volume -"abc" under "rancher-ebs" storage pool.
Create a service with scale=2 using volume abc from rancher-ebs volume driver.
Containers get created successfully on 2 different hosts.
But the volume -"abc" from both the containers are not shared since they are from 2 different EBS volumes.
There are 2 EBS volumes created ( 1 for each of the hosts)

**Comment by LLParse** [comment] 2017-03-20 22:14
The error is that more than one EBS volume was provisioned in the first place. The scheduling that occurs after this error is irrelevant.

Duplicate of https://github.com/rancher/rancher/issues/6714

**Closed by LLParse** 2017-03-20 22:14 UTC
Labels: area/scheduler, area/storage, kind/bug
