### ISSUE TITLE
Access and control host from UI

### ISSUE THREAD

**Issue by jas99** [rancher/rancher#2215] opened 2015-10-02 08:33 UTC
If you add authorization keys of cloud hosts it not no point to restrict user not to access (start, stop, change machine type or ssh) directly from UI. 
Let me know what you guys think about it and your reasons to put under infrastructure.

Thx

**Comment by lavvy** [comment] 2015-10-02 12:49
+1

**Comment by deniseschannon** [comment] 2015-10-02 17:07
I believe this is a duplicate of #2202. 

Step 1: Add to API
Step 2: Add to UI

**Closed by deniseschannon** 2015-10-02 17:07 UTC

**Comment by jas99** [comment] 2015-10-02 23:19
@deniseschannon The issue is similar but missing one key thing. Change machine type. Lets say in ec2 from small to medium instance.

**Comment by vincent99** [comment] 2015-10-02 23:31
Changing instance type is not a feature of `docker-machine` as far as I'm aware.  The other things mentioned can be done for any driver through machine.

**Comment by jas99** [comment] 2015-10-03 01:44
@vincent99 Hi thr
You are right, that is because cloud api call will be required. I think it will be very convenient. I have only worked on AWS but think all other cloud might have similar feature.

**Comment by jas99** [comment] 2015-10-03 02:04
I think this make more sense of what i am saying #2227
