### ISSUE TITLE
feat: Improve UI to show (failed) Pod Reason/Status-Details

### ISSUE THREAD

**Issue by ichtestemalwieder** [rancher/rancher#24884] opened 2020-01-07 19:44 UTC
Problem: 
Rancher does not Show the very important information of the reason - and in general details -  of failed pods. You have to look this up manually in the YAML. The status is the "one and only thing" I care about most, and this information is not found in the UI. 

**List of failed Pods:** 
![image](https://user-images.githubusercontent.com/54768881/71923532-7a495f00-318d-11ea-9c66-6495d6d99ee8.png)

**Pod Detail View (of failed pod) => No detail Information about failed Status available.** 
![image](https://user-images.githubusercontent.com/54768881/71923613-aebd1b00-318d-11ea-9388-cf4241d9d129.png)

**Status can only be found in YAML:** 
![image](https://user-images.githubusercontent.com/54768881/71923670-d0b69d80-318d-11ea-99db-d0fb2d61a6fc.png)

**Solution:** 
The status should be shown directly in the UI.

**Comment by tryhardest** [comment] 2020-01-10 08:16
+1

**Comment by loganhz** [comment] 2020-01-10 09:40
Hi @ichtestemalwieder is there an easy way to create a failed pod? It will be great if you can share your yaml

**Comment by ichtestemalwieder** [comment] 2020-01-10 18:58
@loganhz, thanks for your answer. 

Background: Kubernetes stores Events only for an hour by default (https://github.com/kubernetes/kubernetes/issues/52521). 

Within this hour you can find in the Rancher UI under "Status" the reason about the faild Pod. But after the hour has passed (as can be seen in the screenshot above), the Rancher UI does not make it possible in anyway to find the reason for the failed pod. 

Fix: Please see the kubectl output below, you can find information about the pod (even afther the hour) in the `Status/Reason/Message` fields. And these should somehow be used to display the status in the UI. I am new to kubernetes maybe there is more or even better inormation, I do not know about. So this should be discussed with someone how knows more;-) 


```
> kubectl describe pod keycloak-796d4f6bc6-24m7c
Name:           keycloak-796d4f6bc6-24m7c
Namespace:      default
Priority:       0
Node:           etw2/
Start Time:     Wed, 01 Jan 2020 01:38:45 +0000
Labels:         pod-template-hash=796d4f6bc6
                workload.user.cattle.io/workloadselector=deployment-default-keycloak
                workloadID_ingress-11cdb1de408ca49a88715b279e8234a8=true
Annotations:    cattle.io/timestamp: 2020-01-01T01:38:31Z
                field.cattle.io/ports: [[{"containerPort":8080,"dnsName":"keycloak","kind":"ClusterIP","name":"web","protocol":"TCP"}]]
                workload.cattle.io/state: {"ZXR3Mg==":"c-gxgtk:m-hkq42"}
Status:         Failed
Reason:         OutOfcpu
Message:        Pod Node didn't have enough resource: cpu, requested: 200, used: 900, capacity: 1000
IP:             
IPs:            <none>
Controlled By:  ReplicaSet/keycloak-796d4f6bc6
Containers:
  keycloak:
    Image:      jboss/keycloak
    Port:       8080/TCP
    Host Port:  0/TCP
    Requests:
      cpu:     200m
      memory:  300Mi
    Environment:
      DB_VENDOR:                 h2
      PROXY_ADDRESS_FORWARDING:  true
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-xc742 (ro)
Volumes:
  default-token-xc742:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  default-token-xc742
    Optional:    false
QoS Class:       Burstable
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
Events:          <none>
```


YAML to reproduce is below: 
Please note, that I bound the pod to a specific host (`nodeName`) and then requested  more CPU than this machine has.  This leads to a failed scheduling loop. 

When doing this, you will realize another bug/problem with Rancher UI. As new pods are being scheduled very fast, the UI becomse unresponsive. Try to open the "context menu with right click" (ony the workloads screen) will  be impossible.  To stop the scheduling cllick on the deployment and then click on "Config Scale: - (Minus)" and scale to zero (this also requires several clicks as it seems unresponsive). 

Note: You have to wait an hour bevor the events get deleted. 
But as stated above the `Status/Reason/Message` Fields can be seen directly from the first second on. 


```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: debian-deployment
  labels:
    app: debian
spec:
  selector:
    matchLabels:
      app: debian
  template:
    metadata:
      labels:
        app: debian
    spec:
      containers:
      - name: debian
        image: debian
        resources:
          requests:
            cpu: "20"
      nodeName: etw5

```

**Comment by loganhz** [comment] 2020-01-11 00:35
![image](https://user-images.githubusercontent.com/21168270/72195059-967a2400-344b-11ea-8fd6-0e29c34d7e53.png)

Thanks @ichtestemalwieder ! Please check if the screenshot is what you wanted.

For the re-creating failed pod too fast issue, it looks like it is by design. I think you need to scale it to zero to stop it. And then you could use Rancher UI or kubectl to remove those failed pods. Didn't find a way to limit it in Kubernetes side. Maybe you can google it. :)

For the action menu one, could you file another issue please?

**Comment by ichtestemalwieder** [comment] 2020-01-12 20:44
@loganhz. Thanks so much. Absolutely great, love it, is super informative. You can see with one view what the status is.  Thanks! 
(Sorry, as I am quite new here: I assume this issue will be closed automatically with the merge/releaes of the fix? In case I have to close it, please let me know.)

**Comment by loganhz** [comment] 2020-01-12 23:20
Rancher QA will validate and close it.

**Comment by aaronRancher** [comment] 2020-01-16 18:14
The feature is verified with Rancher server `rancher\rancher:master-head` `version 8e320d045`

Using Rancher server `rancher\rancher:v2.3.0`:
Reason for failure is not shown.
![Screen Shot 2020-01-16 at 11 11 49 AM](https://user-images.githubusercontent.com/57409052/72551060-4affb580-3851-11ea-9b4d-1c589bc0ecc6.png)

Using Rancher server `rancher\rancher:master-head` `version 8e320d045`:
Reason for failure is shown.
![Screen Shot 2020-01-16 at 11 11 25 AM](https://user-images.githubusercontent.com/57409052/72551073-54891d80-3851-11ea-9c12-fefa8cb54f82.png)

**Closed by aaronRancher** 2020-01-16 18:14 UTC
Labels: [zube]: To Test, enhancement, team/cn, team/ui
