### ISSUE TITLE
rancher-server restart resets everything

### ISSUE THREAD

**Issue by strowi** [rancher/rancher#11008] opened 2018-01-20 13:40 UTC
**Rancher versions:**
rancher/server: rancher/server:stable

**Docker version: (`docker version`,`docker info` preferred)**
[root@rancher00 nginx]# docker info
Containers: 2
 Running: 2
 Paused: 0
 Stopped: 0
Images: 7
Server Version: 17.06.2-ce
Storage Driver: overlay
 Backing Filesystem: extfs
 Supports d_type: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 6e23458c129b551d5c9871e5174f6b1b7f6d1170
runc version: 810190ceaa507aa2727d7ae6f4790c76ec150bd2
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.75-rancher
Operating System: RancherOS v1.1.3
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 7.798GiB
Name: rancher00.fra.XXXX.net
ID: EL63:YCRB:RLC5:2UGS:K4KW:ZTXV:5SX2:JMEN:JXVZ:PJCI:PKPV:G44M
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
[root@rancher00 nginx]# cat /etc/os-release 
4.9.75-rancher

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
Proxmox VM on DRBD

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
internal DB

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle

**Steps to Reproduce:**
- Setup Rancher, with the following docker-compose
 (in compliance with http://rancher.com/docs/rancher/v1.6/en/installing-rancher/installing-server/#launching-rancher-server---single-container-non-ha):

```version: '2'

services:
  rancher-server:
    image: rancher/server:stable
    container_name: rancher-server
    restart: unless-stopped
    ports:
      - "8080:8080"
    volumes:
      - /srv/rancher-server/cattle:/var/lib/cattle
      - /srv/rancher-server/mysql:/var/lib/mysql
      - /srv/rancher-server/cattle:/var/log/cattle
    labels:
      io.rancher.container.system: 'true'

  rancher-nginx:
    image: nginx:alpine
    container_name: rancher-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /srv/rancher-server/nginx:/etc/nginx/conf.d:ro
      - /srv/rancher-server/ssl:/etc/ssl:ro
    depends_on:
      - rancher-server
    labels:
      io.rancher.container.system: 'true'
```
- add Hosts/Containers
- reboot

**Results:**
All Information, Hosts, Containers gone.
DataDir still present.

Anyone have a clue as to why all the data is gone after a reboot?

**Comment by superseb** [comment] 2018-01-26 14:58
In RancherOS `/home` and `/opt` are persistent by default, the rest will not be. This means that the directories are emptied on reboot, and Rancher's settings are gone. (http://rancher.com/docs/os/v1.1/en/system-services/system-docker-volumes/)

Mount another disk on `/srv` or use a persistent dir to keep the settings.

Closing as not a bug, let me know if you have any other questions.

**Closed by superseb** 2018-01-26 14:58 UTC

**Comment by xorpierre** [comment] 2019-02-08 11:50
we just experienced this....thats not only non-sensible but absolutely stupid to use as a default
