### ISSUE TITLE
Monitoring improvements

### ISSUE THREAD

**Issue by cloudnautique** [rancher/rancher#23239] opened 2019-10-04 21:53 UTC
This issue focuses on improvements addressing the main issues users are seeing with the current implementation and functionality provided by Rancher monitoring. 

Primary Issues:
1. Can’t add metadata to alerts for integration into other monitoring systems.
1. Users can not ship metrics to other systems.
1. Users can not scrape custom endpoints at the cluster level.

To address:

Need to add the following capabilities to Rancher monitoring:

* Ability to specify custom configuration to the prometheus rules file.
	- This needs to support alert rules/groups
	- This needs to support recording rules/groups
	- Users need to be able to create new rules for their own use
	- Users need to be able to edit Rancher provided rules, so they can add labels / metadata etc.
* Custom Grafana dashboards, leveraging both configmaps and dashboard list.
* Ability to specify custom scrape configs to the prometheus config yaml.
* Allow specifying remote read/write configurations to prometheus so that data can be written to remote syncs for other monitoring tools or long term storage.
* Deploy AlertManager with HA configuration.
* Allow enabling Thanos side car for users looking to aggregate. rancher/system-charts#95

* A user should be able to monitor etcd in the local HA cluster, or imported RKE cluster. (#18619)

Constraints:
1. Leverage the prometheus operator for deployments.
1. Allow users to leverage operator CRDs.
1. Rancher installation of the Prometheus operator should not use the same api groups as the upstream operator.
1. A user must be able to leverage monitoring in a CIS compliant cluster. This may require the user to deploy additional exporters.

gzrancher/rancher#8007

gz#6800

**Comment by ekristen** [comment] 2019-10-28 13:12
Yes please. I don't want to have to run multiple prometheus setups on my cluster just so that I can have the data integrated elsewhere. These above objectives would be great.

1. I have a PR open to enable thanos support (would be great to get that merged)
2. Support for additionalScrapeConfigs is already in place technically, but the problem is that it gets formatted weird due to monitoring only being able to be configured by form, need to please add configure via YAML to the UI.

Ultimately what I'm doing in the mean time is customizing the system-charts and hosting it myself to meet my own needs, but this in practice is tricky each time that Rancher does an update. I have conflicts in the version number since 0.0.x is being used, I have to redo my patches with all the changes that Rancher makes, etc ...

**Comment by marcinbojko** [comment] 2019-10-28 13:18
@ekristen - any quick workaround to force cluster level monitor to honor custom metrics from project level monitoring?

**Comment by ekristen** [comment] 2019-10-28 13:26
if you are looking to just enable auto scraping of pods that announce metrics via prometheus.io/scrape then simply go to the system project and secrets and locate the Prometheus additional scrape config entry and edit it. Inside find the Prometheus-is-scrape entry and under the Kubernetes_sd_config remove the namespace restrictions that limit it to the ingress and kube-system and save, the operator will redeploy and it will start discovering in all namespaces.

**Comment by marcinbojko** [comment] 2019-10-28 13:33
@ekristen  - thanks! I'll try to change this into rancher2 terraform provided answer!

**Comment by LinAnt** [comment] 2019-11-06 10:01
For dashboards, I think using the same workflow as the stable grafana helmchart would be preferable.

Basically a grafana watches namespaces and detects configmaps (secrets) labeled with a specific label. The configmap contains the dashboard/dashboards, and this get mounted into the grafana pods.

This enables developers to easliy bundle their dashboards with the rest of the yaml for their application.

The same goes for Datasources. We run loki in our clusters and using config maps / secrets is way more convenient than patching the current configuration.
https://github.com/rancher/rancher/issues/19125

**Comment by cloudnautique** [comment] 2019-11-06 23:44
@LinAnt as an admin is there an easy way to figure out where dashboards/configs are coming from? I see that the searched namespaces can be restricted so there can be some controls put around the access.

**Comment by Tejeev** [comment] 2019-11-25 20:40
Will we be passing custom labels to Prometheus?
If I test by adding a label to a pod (`test: "test"`) and then try running a query that should return the pod in Prometheus (`kube_pod_container_status_restarts_total{test="test"}`) , it does not.
If I run the a wider query that returns the pod, I do not see the label in it's definition.
`kube_pod_container_status_restarts_total`
`kube_pod_container_status_restarts_total{container="agent",endpoint="http",host_ip="178.62.42.110",instance="10.42.2.15:8080",job="expose-kubernetes-metrics",namespace="cattle-system",node="wk1",pod="cattle-node-agent-9pl5c",service="expose-kubernetes-metrics"}`

**Comment by adampl** [comment] 2019-11-27 14:47
@ekristen 
> 2. Support for additionalScrapeConfigs is already in place technically, but the problem is that it gets formatted weird due to monitoring only being able to be configured by form, need to please add configure via YAML to the UI.

What do you mean by "technically"? How to set this field to make it work?

**Comment by ekristen** [comment] 2019-11-27 14:58
@marcinbojko @adampl I've just had to fork the system charts to make it work the way I want for now unfortunately. :(

https://github.com/ekristen/system-charts/tree/release-v2.3

This has a modified version of 0.0.5, specifically designed to enable thanos and change the default scrape config for the prometheus.io/scrape label to target all namespaces.

Set this variable `prometheus.scrapeConfigPodNamespaces` to nothing and it'll scrape all namespaces for pods that expose metrics.

**Comment by adampl** [comment] 2019-11-27 15:16
@ekristen Well, scraping custom pod metrics is already supported, just add an annotation to the pod (or pod template) like this: `field.cattle.io/workloadMetrics: '[{"path":"/metrics","port":12345,"schema":"HTTP"}]'`. I'm looking for a way to scrape metrics from _outside_ of the Kubernetes cluster.

**Comment by ekristen** [comment] 2019-11-27 15:51
@adampl that's interesting, I wasn't aware of that method.  I would still prefer standard working out of the box. As for getting additionalScrapeConfigs working, if you write the YAML then copy and paste it into the value field, I've had success with that.

**Comment by adampl** [comment] 2019-11-27 16:10
@ekristen Yes, and as you said, the UI breaks the format. I created an issue for this: #24274

Regarding the annotation, you can set it through the UI too, though it didn't quite work for me:
https://rancher.com/docs/rancher/v2.x/en/project-admin/tools/monitoring/#example
If I recall correctly, it messed the service assigned to the workload, so I prefer the YAML method.

**Comment by marcinbojko** [comment] 2019-12-04 08:39
@ekristen  Were you able to overcome 0.0.5/0.0.6 templates problems? Looks like my manually created ingress to prometheus cluster monitoring stopped to works (502, bad gateway). Did i miss something or in 0.0.6 we still cannot add ingress to our custer-prometheus?

**Comment by B3DTech** [comment] 2019-12-05 18:22
I'd love the ability to easily do remote writes to my VictoriaMetrics server for long term storage and central dashboarding.  I hate running multiple Prometheuses, but love the direct integration into Rancher - as do our Devs.  Glad it's a planned feature improvement.

**Comment by Tejeev** [comment] 2019-12-11 12:13
There are two issues addressing remote monitoring:
 [Enhancement] Prometheus Monitoring Remote Write #20624
 Support external prometheus in rancher monitoring #17370

**Comment by junneyang** [comment] 2020-03-02 11:50
> config

not work...

**Comment by iwin4aids** [comment] 2020-04-17 03:52
> if you are looking to just enable auto scraping of pods that announce metrics via prometheus.io/scrape then simply go to the system project and secrets and locate the Prometheus additional scrape config entry and edit it. Inside find the Prometheus-is-scrape entry and under the Kubernetes_sd_config remove the namespace restrictions that limit it to the ingress and kube-system and save, the operator will redeploy and it will start discovering in all namespaces.

Same as I do now, but I don't like this workaroud while the prometheus "lpv persistent solution" is not working for me, currently the config file located at _/etc/prometheus/config_out_  is a volatile empty dir in k8s.

**Comment by maggieliu** [comment] 2020-07-06 20:00
Closing this ticket in favor of the new 2.5 scope is available [here](https://github.com/rancher/rancher/issues/26549).

**Closed by maggieliu** 2020-07-06 20:00 UTC
Labels: [zube]: Team Blue Backlog, area/monitoring, internal, kind/enhancement
