### ISSUE TITLE
Azure AD Authentication : User not able to login when MFA is enabled

### ISSUE THREAD

**Issue by kvaes** [rancher/rancher#5952] opened 2016-09-12 12:06 UTC
**Rancher Version:** 1.1.3

**Docker Version:** 1.12.1

**OS and where are the hosts located? n/a

**Setup Details: n/a

**Environment Type: System Level 

**Steps to Reproduce:**  
- Setup Rancher
- Integrate with Azure AD
- create a user
- grant user rights in Rancher
- login with user (OK)
- enable MFA with same user
- login with user (NOK - Error from Azure: 400)

**Results:**  Error from Azure: 400

**Expected:**  Redirect to MFA authentication sequence

**Context:**  By default I enable all global administrators of Azure AD with MFA. This is a basic security measure to protect the most critical accounts.

**Comment by tfiduccia** [comment] 2016-09-13 18:05
duplicate of #5772

**Closed by tfiduccia** 2016-09-13 18:05 UTC
