### ISSUE TITLE
"(Waiting: allocated [container:1i43])" While creating a new stack

### ISSUE THREAD

**Issue by TimPelgrim** [rancher/rancher#7055] opened 2016-12-14 15:00 UTC
While creating a new stack the containers remain in an Activating state with the message: ` (Waiting: allocated [container:1i##])`. 

When looking in the error logs I see these Java error messages:

```
2016-12-14 14:57:45,028 ERROR [:] [] [] [] [ecutorService-4] [.e.s.i.ProcessInstanceDispatcherImpl] Unknown exception running process [service.update:926] on [20] java.lang.NumberFormatException: null
       	at java.lang.Long.parseLong(Long.java:552) ~[na:1.8.0_72]
       	at java.lang.Long.valueOf(Long.java:803) ~[na:1.8.0_72]
       	at io.cattle.platform.servicediscovery.deployment.impl.planner.GlobalServiceDeploymentPlanner.<init>(GlobalServiceDeploymentPlanner.java:35) ~[cattle-iaas-service-discovery-server-0.5.0-SNAPSHOT.jar:na]
       	at io.cattle.platform.servicediscovery.deployment.impl.planner.ServiceDeploymentPlannerFactoryImpl.createServiceDeploymentPlanner(ServiceDeploymentPlannerFactoryImpl.java:34) ~[cattle-iaas-service-discovery-server-0.5.0-SNAPSHOT.jar:na]
       	at io.cattle.platform.servicediscovery.deployment.impl.DeploymentManagerImpl.getPlanner(DeploymentManagerImpl.java:285) ~[cattle-iaas-service-discovery-server-0.5.0-SNAPSHOT.jar:na]
       	at io.cattle.platform.servicediscovery.deployment.impl.DeploymentManagerImpl.deploy(DeploymentManagerImpl.java:247) ~[cattle-iaas-service-discovery-server-0.5.0-SNAPSHOT.jar:na]
       	at io.cattle.platform.servicediscovery.deployment.impl.DeploymentManagerImpl.reconcileDeployment(DeploymentManagerImpl.java:134) ~[cattle-iaas-service-discovery-server-0.5.0-SNAPSHOT.jar:na]
       	at io.cattle.platform.servicediscovery.deployment.impl.DeploymentManagerImpl$1.doWithLock(DeploymentManagerImpl.java:123) ~[cattle-iaas-service-discovery-server-0.5.0-SNAPSHOT.jar:na]
       	at io.cattle.platform.servicediscovery.deployment.impl.DeploymentManagerImpl$1.doWithLock(DeploymentManagerImpl.java:117) ~[cattle-iaas-service-discovery-server-0.5.0-SNAPSHOT.jar:na]
       	at io.cattle.platform.lock.impl.AbstractLockManagerImpl$3.doWithLock(AbstractLockManagerImpl.java:40) ~[cattle-framework-lock-0.5.0-SNAPSHOT.jar:na]
       	at io.cattle.platform.lock.impl.LockManagerImpl.doLock(LockManagerImpl.java:33) [cattle-framework-lock-0.5.0-SNAPSHOT.jar:na]
       	at io.cattle.platform.lock.impl.AbstractLockManagerImpl.lock(AbstractLockManagerImpl.java:13) [cattle-framework-lock-0.5.0-SNAPSHOT.jar:na]
       	at io.cattle.platform.lock.impl.AbstractLockManagerImpl.lock(AbstractLockManagerImpl.java:37) [cattle-framework-lock-0.5.0-SNAPSHOT.jar:na]
       	at io.cattle.platform.servicediscovery.deployment.impl.DeploymentManagerImpl.activate(DeploymentManagerImpl.java:117) ~[cattle-iaas-service-discovery-server-0.5.0-SNAPSHOT.jar:na]
       	at io.cattle.platform.servicediscovery.deployment.impl.DeploymentManagerImpl.activate(DeploymentManagerImpl.java:103) ~[cattle-iaas-service-discovery-server-0.5.0-SNAPSHOT.jar:na]
       	at io.cattle.platform.servicediscovery.process.ServiceUpdateActivate$1.run(ServiceUpdateActivate.java:73) ~[cattle-iaas-service-discovery-server-0.5.0-SNAPSHOT.jar:na]
       	at io.cattle.platform.activity.ActivityService.run(ActivityService.java:43) ~[cattle-activity-log-0.5.0-SNAPSHOT.jar:na]
       	at io.cattle.platform.servicediscovery.process.ServiceUpdateActivate.handle(ServiceUpdateActivate.java:70) ~[cattle-iaas-service-discovery-server-0.5.0-SNAPSHOT.jar:na]
       	at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl.runHandler(DefaultProcessInstanceImpl.java:448) ~[cattle-framework-engine-0.5.0-SNAPSHOT.jar:na]
       	at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl$4.execute(DefaultProcessInstanceImpl.java:399) ~[cattle-framework-engine-0.5.0-SNAPSHOT.jar:na]
       	at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl$4.execute(DefaultProcessInstanceImpl.java:393) ~[cattle-framework-engine-0.5.0-SNAPSHOT.jar:na]
       	at io.cattle.platform.engine.idempotent.Idempotent.execute(Idempotent.java:42) ~[cattle-framework-engine-0.5.0-SNAPSHOT.jar:na]
       	at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl.runHandlers(DefaultProcessInstanceImpl.java:393) ~[cattle-framework-engine-0.5.0-SNAPSHOT.jar:na]
       	at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl.runLogic(DefaultProcessInstanceImpl.java:495) ~[cattle-framework-engine-0.5.0-SNAPSHOT.jar:na]
       	at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl.runWithProcessLock(DefaultProcessInstanceImpl.java:326) ~[cattle-framework-engine-0.5.0-SNAPSHOT.jar:na]
       	at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl$2.doWithLockNoResult(DefaultProcessInstanceImpl.java:243) ~[cattle-framework-engine-0.5.0-SNAPSHOT.jar:na]
       	at io.cattle.platform.lock.LockCallbackNoReturn.doWithLock(LockCallbackNoReturn.java:7) [cattle-framework-lock-0.5.0-SNAPSHOT.jar:na]
       	at io.cattle.platform.lock.LockCallbackNoReturn.doWithLock(LockCallbackNoReturn.java:3) [cattle-framework-lock-0.5.0-SNAPSHOT.jar:na]
       	at io.cattle.platform.lock.impl.AbstractLockManagerImpl$3.doWithLock(AbstractLockManagerImpl.java:40) ~[cattle-framework-lock-0.5.0-SNAPSHOT.jar:na]
       	at io.cattle.platform.lock.impl.LockManagerImpl.doLock(LockManagerImpl.java:33) [cattle-framework-lock-0.5.0-SNAPSHOT.jar:na]
       	at io.cattle.platform.lock.impl.AbstractLockManagerImpl.lock(AbstractLockManagerImpl.java:13) [cattle-framework-lock-0.5.0-SNAPSHOT.jar:na]
       	at io.cattle.platform.lock.impl.AbstractLockManagerImpl.lock(AbstractLockManagerImpl.java:37) [cattle-framework-lock-0.5.0-SNAPSHOT.jar:na]
...
``` 

What could cause this kind of problem? And more important, how might I be able to fix it?

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v1.2.0` Cattle: `v0.174.3` UI: `v1.2.34` |
|Access|`github` `admin`|
|Orchestration|`Cattle`|
|Route|`stack.index`|

**Comment by sergey-koba-mobidev** [comment] 2016-12-29 22:27
Having the same problem +1

**Comment by InAnimaTe** [comment] 2017-01-11 18:42
See also: #7181 

This seems to be happening a lot more in 1.3.0 as well. Impacts fresh deploys, upgrades, even deletions. Taking upwards of 10 minutes to deploy a LB atm.

**Comment by habitullence** [comment] 2017-01-13 13:38
Yep, deploys completely stuck for me as well.

**Comment by aemneina** [comment] 2017-05-12 18:29
Anyone able to reproduce this in newer versions of rancher? There have been major changes since 1.2.x... will close this out. Let me know if this still exists in 1.5.9+ and we can revisit.

**Closed by aemneina** 2017-05-12 18:29 UTC
