### ISSUE TITLE
[BUG] High memory usage on v2.7.5

### ISSUE THREAD

**Issue by gionn** [rancher/rancher#42191] opened 2023-07-24 08:50 UTC
**Rancher Server Setup**
- Rancher version: v2.7.5
- Installation option (Docker install/Helm Chart): Helm Chart
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): v1.23.17-eks-a5565ad
- Proxy/Cert Details:

**Describe the bug**

After upgrading Rancher from v2.6.13 to v2.7.5, we didn't face any problems right after the upgrade, but within 7 days we had to switch our main node group from t3.large (8 GB of memory per node) to t3.xlarge (16 GB of memory per node) otherwise we were not able to get healthy rancher pods (all crashing in a variety of OOMKilled, Evicted, ContainerStatusUnknown)

Current situation with healthy pods:
```
$ kubectl top pod -n cattle-system
NAME                                   CPU(cores)   MEMORY(bytes)
eks-config-operator-57f94d69dd-gsdf8   2m           176Mi
rancher-c875bc68b-sftq2                179m         5505Mi
rancher-c875bc68b-wkrjl                659m         8383Mi
rancher-c875bc68b-xspj4                232m         6442Mi
rancher-webhook-648db6b695-j7ptw       44m          1287Mi
```

Rancher manage ~20 clusters, most of them running on `v1.27.3-eks-a5565ad`, a single one on an old `v1.21.14-eks-a5565ad`.

**To Reproduce**

**Result**

**Expected Result**

**Screenshots**

**Additional context**

**Comment by moio** [comment] 2023-07-24 13:38
@gionn do you have Rancher logs available for me to have a look?

It could be related to another case I am trying to troubleshoot.

**Comment by gionn** [comment] 2023-07-24 14:09
Attached:
[rancher.log.gz](https://github.com/rancher/rancher/files/12146713/rancher.log.gz)

I see a lot of:

```
33 warnings.go:80] Use tokens from the TokenRequest API or manually created secret-based tokens instead of auto-generated secret-based tokens.
```

In the meantime, not sure if really related or another bug, but I’ve found a lot of secrets created inside namespaces like cluster-fleet-default-xxx:

```
kubectl get secret -A | wc -l
   26193
```

I’ve deleted manually the most big namespaces, and now the secrets count are way lower to:

```
kubectl get secret -A | wc -l
     784
```

Thanks.

**Comment by moio** [comment] 2023-07-24 14:42
TokenRequest API warnings seem to depend on a feature in beta activated on EKS clusters https://github.com/kubernetes/kubernetes/pull/117591

This will be default on 1.28, and I expect Rancher to be updated by that time (versions later than 1.26 are not officially  supported https://www.suse.com/suse-rancher/support-matrix/all-supported-versions/rancher-v2-7-5/)

I think that is a red herring (annoying but not harmful).

**Comment by moio** [comment] 2023-07-26 08:22
I am looking for evidence to find some new paths:

- how are secrets and configmap counts going?
- can you capture heap and goroutine profiles with the script below:


```sh
TS=`date -u +"%Y-%m-%d_%H%M"`
pprofs=( goroutine heap )
for pod in $(kubectl -n cattle-system get pods --no-headers -l app=rancher -o custom-columns=":.metadata.name"); do
  echo "getting profile for $pod..."
  for pp in ${pprofs[@]}; do
    echo "--> generating $pp..."
    kubectl -n cattle-system exec $pod -c rancher -- curl -s http://localhost:6060/debug/pprof/$pp -o $pp
  done
  echo "--> taring it up..."
  kubectl -n cattle-system exec $pod -c rancher -- tar -czf debug-pprof.tar.gz $pprofs
  kubectl -n cattle-system cp -c rancher $pod:debug-pprof.tar.gz $pod-debug-pprof-$TS.tar.gz
  echo saved debug profile $pod-debug-pprof-$TS.tar.gz
done
```

(Ideally take one, wait some hours, then another one and possibly a third after a while - so that we can observe if there are any trends. Also: attach logs at the points in time of the profiles)

Thanks for all the cooperation so far!

**Comment by gionn** [comment] 2023-07-26 14:03
> how are secrets and configmap counts going?

those seems stable around ~900

the today interesting discovery is:

<img width="192" alt="Screenshot 2023-07-26 at 15 24 10" src="https://github.com/rancher/rancher/assets/71768/0f461283-e733-47ef-a8cd-3d3d649e1cd2">

I decided to try my luck searching recently created roles with:

```
kubectl -n fleet-default get role | grep 2023-07-26T13
request-2gxxd                                                    2023-07-26T13:12:50Z
request-2gzst                                                    2023-07-26T13:16:51Z
request-2tgps                                                    2023-07-26T13:19:51Z
request-5b9k2                                                    2023-07-26T13:05:50Z
request-6t66h                                                    2023-07-26T13:10:50Z
request-8hglb                                                    2023-07-26T13:15:51Z
request-btg75                                                    2023-07-26T13:03:49Z
request-d6dj5                                                    2023-07-26T13:13:50Z
request-dclcv                                                    2023-07-26T13:07:50Z
request-fxd87                                                    2023-07-26T13:18:50Z
request-gbmkb                                                    2023-07-26T13:11:52Z
request-ghv8j                                                    2023-07-26T13:02:49Z
request-k8nr7                                                    2023-07-26T13:09:50Z
request-nw69p                                                    2023-07-26T13:14:51Z
request-rwr5q                                                    2023-07-26T13:01:49Z
request-tk4zc                                                    2023-07-26T13:17:50Z
request-vjcn6                                                    2023-07-26T13:04:49Z
request-vx9lw                                                    2023-07-26T13:08:50Z
request-vxgbn                                                    2023-07-26T13:00:49Z
request-wxwvb                                                    2023-07-26T13:06:50Z
```

then describe one of them to get the cluster-id:

```
kubectl -n fleet-default describe role request-2tgps
Name:         request-2tgps
Labels:       fleet.cattle.io/managed=true
              objectset.rio.cattle.io/hash=80a80cf7e216ead3e31063519b01376cebba648d
Annotations:  objectset.rio.cattle.io/applied:
                H4sIAAAAAAAA/5SST4/TMBDFvwqac7LbNH+aRuIEEgckkFaIC+ph4rykoY4d7HE5VPnuyKmA1YogOHpeZub93uRGE4Q7FqbmRmyMFZbRGh+ftv0KJR7y4Eb7oFhE42G0j2NHDSkdvM...
              objectset.rio.cattle.io/id: cluster-registration
              objectset.rio.cattle.io/owner-gvk: fleet.cattle.io/v1alpha1, Kind=ClusterRegistration
              objectset.rio.cattle.io/owner-name: request-2tgps
              objectset.rio.cattle.io/owner-namespace: fleet-default
PolicyRule:
  Resources                        Non-Resource URLs  Resource Names  Verbs
  ---------                        -----------------  --------------  -----
  clusters.fleet.cattle.io/status  []                 [c-47cgc]       [patch]
```

Then I jumped to `https://myrancher/dashboard/c/c-47cgc/explorer` to discover which was the cluster and indeed fleet-agent was in permanent crash loop (sorry but I nuked the cluster before even looking at that pod logs).

Now I don't have any new leaks (roles are not increasing anymore), will monitor if creating new clusters would trigger it again in the coming days.

Ideas for a cleanup script to get rid of this mess? Will try to come up with something.

**Comment by manno** [comment] 2023-07-26 16:33
We did just release Fleet 0.7.1-rc.1 which should clean up clusterregistration resources automatically: https://github.com/rancher/rancher/pull/42237

Not sure if you can test that. It is in https://github.com/rancher/charts/tree/dev-v2.7/assets/fleet and you'd also need to install the fleet-crd chart first.

**Comment by gionn** [comment] 2023-07-27 07:28
Ok, I was probably doing something wrong with the cleanup script at the very first try.

After discovering that I still had ~47k ClusterRegistration objects, I've executed the cleanup script in the rancher cluster web console (to reduce latency) and passing as a second parameter the total count of objects / 10 (chunk size):

```
./delete_old_resources.sh fleet-default 5000
```

After ~1 hour, the count of ClusterRegistration got down to ~4700. Now the remaining ClusterRegistrations seems mostly ones without any `clusterLabels` attached, so the script is not handling them.

Memory usage seems improving 🎉 (I had to kill those rancher pods because otherwise the memory usage was still high):

```
kubectl -n cattle-system top pod
NAME                                   CPU(cores)   MEMORY(bytes)
eks-config-operator-57f94d69dd-gsdf8   1m           48Mi
rancher-c875bc68b-d28cw                37m          1089Mi
rancher-c875bc68b-jlr9b                49m          1662Mi
rancher-c875bc68b-qkmr8                68m          3099Mi
rancher-webhook-648db6b695-j7ptw       13m          1101Mi
```

Those blank ClusterRegistration looks like:
```yml
apiVersion: fleet.cattle.io/v1alpha1
kind: ClusterRegistration
metadata:
  creationTimestamp: '2023-05-18T03:49:58Z'
  generateName: request-
  generation: 1
  managedFields:
    - apiVersion: fleet.cattle.io/v1alpha1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:generateName: {}
        f:spec:
          .: {}
          f:clientID: {}
          f:clientRandom: {}
      manager: fleetagent
      operation: Update
      time: '2023-05-18T03:49:58Z'
    - apiVersion: fleet.cattle.io/v1alpha1
      fieldsType: FieldsV1
      fieldsV1:
        f:status:
          .: {}
          f:clusterName: {}
          f:granted: {}
      manager: fleetcontroller
      operation: Update
      subresource: status
      time: '2023-05-18T03:49:59Z'
  name: request-2b2l8
  namespace: fleet-default
  resourceVersion: '245132085'
  uid: b5f28f55-5900-4a06-b8a4-3b6504e380fe
spec:
  clientID: 8k9949v9jk8bb2ddqthlw55fnzpdtkfqq28rz8w9w2cm6vrnr2qj4p
  clientRandom: <randomValue>
status:
  clusterName: c-t5wsm
  granted: true
```

At this point I could try testing the `0.7.1-rc.1`if it's going to help also in cleaning up this resources, can you confirm @manno?

I also need some confirmation that I just need to run manually an helm upgrade with --reuse-values for both fleet-crd and fleet charts - as far I know those charts are handled directly by rancher and I have no idea what happens if I try to upgrade them manually.

Thanks!

**Comment by moio** [comment] 2023-07-27 07:40
> At this point I could try testing the 0.7.1-rc.1if it's going to help also in cleaning up this resources, can you confirm @manno?

Yes. 0.7.1-rc.1 contains a mechanism which does the equivalent of the cleanup script, directly integrated in Fleet. 

> I also need some confirmation that I just need to run manually an helm upgrade with --reuse-values for both fleet-crd and fleet charts

I will be posting test instructions later this morning, thanks for your openness to try out the RC!

**Comment by moio** [comment] 2023-07-27 10:37
Installation instructions (from a machine with `kubectl` access to the upstream cluster):

```sh
export TAG=v0.7.1-rc.1

# update CRDs
curl https://raw.githubusercontent.com/rancher/fleet/$TAG/charts/fleet-crd/templates/crds.yaml | kubectl apply -f -

# edit the fleet-controller ConfigMap on the upstream cluster (to change the fleet-agent image downstream to the test version)
kubectl get configmap -n cattle-fleet-system fleet-controller -o yaml | sed -E "s#[0-9A-Za-z\.\-\/]+/fleet-agent:v[0-9A-Za-z\.\-]+#rancher/fleet-agent:$TAG#g" | kubectl apply -f -

# edit the fleet-controller deployment (to change the fleet-controller image to the test version)
kubectl set image -n cattle-fleet-system deployment/fleet-controller fleet-controller=rancher/fleet:$TAG
```

That will update fleet-controller and propagate the changes to all fleet-agent in downstream clusters - you should see the new image being used all over in a matter of minutes.

Garbage-collection / cleanup jobs should work regularly, so please keep the pods under monitoring and let us know how memory usage goes in the next hours and days.

Thanks once again for the precious collaboration

**Comment by gionn** [comment] 2023-07-27 13:32
Upgraded to v0.7.1-rc.1, I can see downstream clusters running fleet-agent v0.7.1-rc.1 🎉 

Here the logs of fleet-controller within the first 10 minutes of uptime: 
[fleet-controller-559575569-v8hnh_fleet-controller.log.zip](https://github.com/rancher/rancher/files/12183963/fleet-controller-559575569-v8hnh_fleet-controller.log.zip)

I have still a lot of stale (?) ClusterRegistrations which doesn't have any clusterLabels attached, I was thinking to just script the deletion of them if you think it's safe?

<img width="1910" alt="Screenshot 2023-07-27 at 15 29 42" src="https://github.com/rancher/rancher/assets/71768/a6f70b66-fc46-40b1-9cbb-485f86e59ca5">

**Comment by pgonin** [comment] 2023-07-27 14:36
Give it some time to let the cleanup kick in

**Comment by manno** [comment] 2023-07-27 15:04
If the clusters are properly registered, they might not clean up automatically, since we only clean up after a successful registration. We might need another PR to do what the workaround script does during controller startup to remedy the situation with existing deployments.

**Comment by moio** [comment] 2023-07-28 09:03
@gionn one way to proceed is to run the cleanup script one more time:

https://github.com/rancherlabs/support-tools/pull/231

That and having  v0.7.1-rc.1 in place is expected to result in no more excessive ClusterRegistrations (and related resources including Secrets), and no more excessive RAM usage.

Can you verify that?

**Comment by moio** [comment] 2023-07-28 09:04
This is a potential duplicate of [#1651](https://github.com/rancher/fleet/issues/1651)

**Comment by gionn** [comment] 2023-07-28 09:53
> @gionn one way to proceed is to run the cleanup script one more time:

Tried multiple times but it is not triggering anymore any deletion and ClusterRegistrations still around ~4700 overnight.

As far I understood, that script iterate on the registrations sorted by clusterName and deletes the duplicates except the last (newer) one but right now all the ClusterRegistrations left are all with an unique clusterName, hence the script is not deleting anything.

(I've joined rancher-users slack, you can ping me there if you want)

**Comment by moio** [comment] 2023-07-31 08:20
Hey @gionn thanks!

I think it is fair to close this issue, as the main reported symptoms are addressed. We are still researching ways to embed a more effective auto-cleanup, and that might include something functionally similar to your script, in one of the next versions going forward.

We will reserve the right to poke you in future when we have something to test - if you are OK with that!

And of course, this issue can be re-opened (or a new one can be opened) if symptoms are back.

Have a great day!

**Closed by moio** 2023-07-31 08:20 UTC
Labels: kind/bug
