### ISSUE TITLE
`error syncing 'rancher-partner-charts'` error in rancher logs

### ISSUE THREAD

**Issue by sowmyav27** [rancher/rancher#35886] opened 2021-12-16 06:19 UTC
**on 2.6-head commit id: `39cecf0`**

- This is a rancher server upgraded from 2.5.11 to 2.6head. (helm install rancher, one downstream custom 1.20 cluster)
- Error in rancher logs:
```
2021/12/16 06:12:50 [ERROR] error syncing 'rancher-partner-charts': handler helm-clusterrepo-ensure: git -C /var/lib/rancher-data/local-catalogs/v2/rancher-partner-charts/8f17acdce9bffd6e05a58a3798840e408c4ea71783381ecd2e9af30baad65974 fetch origin 3c716f07771d78dd3555c60283b46c6db49a0121 error: exit status 128, detail: error: RPC failed; HTTP 502 curl 22 The requested URL returned error: 502
fatal: the remote end hung up unexpectedly
, requeuing
2021/12/16 06:12:50 [ERROR] error syncing 'rancher-partner-charts': handler helm-clusterrepo-ensure: git -C /var/lib/rancher-data/local-catalogs/v2/rancher-partner-charts/8f17acdce9bffd6e05a58a3798840e408c4ea71783381ecd2e9af30baad65974 fetch origin 3c716f07771d78dd3555c60283b46c6db49a0121 error: exit status 128, detail: fatal: unable to access 'https://git.rancher.io/partner-charts/': The requested URL returned error: 502
, requeuing
```

**Comment by Arau** [comment] 2022-02-18 11:35
+1 on 2.6.3 clean install from Helm chart. 

```
error syncing 'rancher-partner-charts': handler helm-clusterrepo-ensure: git -C /var/lib/rancher-data/local-catalogs/v2/rancher-partner-charts/8f17acdce9bffd6e05a58a3798840e408c4ea71783381ecd2e9af30baad65974 fetch origin 61cb9992ff8139e51f66e78ab3a1149f16318671 error: exit status 128, detail: fatal: unable to access 'https://git.rancher.io/partner-charts/': The requested URL returned error: 502
```

**Comment by MKlimuszka** [comment] 2022-03-08 17:45
These are network/internet errors, so it may have been outside the cluster that was being tested. We can have a dev validate this though.

**Comment by PennyScissors** [comment] 2022-11-10 00:30
Closing this as I couldn't reproduce it upgrading from v2.6.9 to v2.7-head. This is likely a one off network/internet issue as @MKlimuszka mentioned. We use github pages to host our repos and they are known to be unstable at times, causing errors when the Rancher tries to pull the repos.

**Closed by PennyScissors** 2022-11-10 00:30 UTC
Labels: kind/bug-qa, [zube]: Next Up, team/area3
