### ISSUE TITLE
Update the node driver from "Packet" to "Equinix Metal"

### ISSUE THREAD

**Issue by deniseschannon** [rancher/rancher#33758] opened 2021-07-26 04:49 UTC
We should update our node driver name from Packet to Equinix Metal on the page that lists the node drivers. 

The icon and name to select this particular node driver to create a cluster has already been updated.

**Comment by vincent99** [comment] 2021-07-26 05:31
I changed the display labels because they're just labels, but the actual name of the driver has consequences like backward compatibility problems.

**Comment by bashofmann** [comment] 2021-09-09 12:17
It's also not working anymore in 2.6.0 for RKE1 clusters:

![Bildschirmfoto 2021-09-09 um 14 09 03](https://user-images.githubusercontent.com/243056/132683218-bd1b229c-30fd-49e4-83df-6f5c44f3719f.png)

JS error:

```
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'io.cattle.nodedriver/ui-field-hints')
``

Plus the version of the driver we are linking is very old, the current version is https://github.com/equinix/docker-machine-driver-metal/releases/tag/v0.5.0.

If I add this as an additional node driver, I can create RKE1 clusters with it.

**Comment by deniseschannon** [comment] 2021-09-10 13:43
Can we investigate why Packet/Equinix Metal isn't working for RKE1 node drivers?

**Comment by anupama2501** [comment] 2021-09-14 17:57
reproduced on v2.6-head `6a0a991`

1. From cluster management page --> Drivers --> Node drivers --> activate `Packet` 
2. Navigate to  Node Templates, it displays below error and the `Packet equinix` is not even shown in the list of node templates with an error displayed
<img width="500" alt="Screen Shot 2021-09-14 at 10 55 46 AM" src="https://user-images.githubusercontent.com/38144301/133309118-7203fd57-1709-4960-922d-457276fe0f88.png">


**Following errors are seen in the console logs:**
```
Refused to apply style from 'https://redacted/meta/proxy/https:/packethost.github.io/ui-driver-packet/1.0.2/component.css' because its MIME type ('text/html') is not a supported stylesheet MIME type, and strict MIME checking is enabled.
load-script.js:45 
GET https://redacted/meta/proxy/https:/packethost.github.io/ui-driver-packet/1.0.2/component.js net::ERR_ABORTED 404 (Not Found)
```

As mentioned by @bashofmann, if we add the same URL as a custom node driver from the node drivers page, it works and able to create a node template:
<img width="500" alt="Screen Shot 2021-09-14 at 10 53 36 AM" src="https://user-images.githubusercontent.com/38144301/133308897-8e90ac1c-bcff-4990-ba86-c3311b21cd79.png">

**Comment by deniseschannon** [comment] 2021-09-14 18:48
As part of this issue, we should update driver version to the new version:
https://github.com/equinix/docker-machine-driver-metal/releases/tag/v0.5.0.

This should be an easy update/replacement in here:
https://github.com/rancher/rancher/blob/release/v2.6/pkg/data/management/machinedriver_data.go#L117

Can a UI ticket be filed to update where it says "Packet" to "Equinix Metal"? And to update the logo (if it hasn't been updated already) to the Equinix Metal one? 

We should make a backport issue to fix this in 2.5.10.

**Comment by cbron** [comment] 2021-09-15 15:41
Unlikely we'll get this in for 2.6.1 as resources are used up right now and its 2 days before code freeze.

**Comment by displague** [comment] 2021-10-19 17:33
GitHub Pages support was disabled on the packethost org and the redirect to equinix/docker-machine-driver-metal and equinix/ui-driver-metal is no longer working.  We've created a CNAME referring to the new GH Pages (on equinix/ui-driver-metal): https://rancher-drivers.equinixmetal.net/1.0.2/component.js.  This is the same file that was served with the now broken URL.

A 'metal' components.js has not been finalized nor tagged yet.

I've updated the release binaries on equinix/docker-machine-driver-equinix to include both a Packet and a Metal binary in new releases from 0.6.0+.  For example, the archive named https://github.com/equinix/docker-machine-driver-metal/releases/download/v0.6.0/docker-machine-driver-metal_linux-amd64.zip contains both a packet and a metal docker machine driver.  The rancher/rancher unzip code looks like it will handle this as it simply ignores any files that don't match the expected name.  

These binaries function the same way and are backwards compatible.  The "metal" binary will expect `--metal` arguments and `METAL_` environment variables, while the Packet binary continues to expect `--packet` and `PACKET_`.

**Comment by nickgerace** [comment] 2021-11-01 21:51
@displague was your [PR to rancher/rancher](https://github.com/rancher/rancher/pull/35271) a partial or total fix for this issue? I merged your changes after @vincent99 and I spoke internally and with approvals, but I want to know if our QA team can proceed to test this yet. Is anything else needed?

**Comment by displague** [comment] 2021-12-01 20:18
@nickgerace #35271 should have corrected the problems and should be in a QA'able state. 

I left a comment on https://github.com/rancher/rancher/issues/34742#issuecomment-984020997 (hopefully not preempting QA)

**Comment by snasovich** [comment] 2021-12-08 04:04
@jakefhyde , please dev validate this one. Thank you.

**Comment by jakefhyde** [comment] 2021-12-08 20:28
Setup
-
docker install on `v2.6-head`

Validation
-
- Confirmed Equinix Metal is available in the list of node drivers and disabled by default:
![activate-node-driver](https://user-images.githubusercontent.com/33796120/145278644-6214aedd-3fa6-4c8e-8ca6-feda58ca1e4b.png)
- Confirmed the node driver successfully activates:
![activated-node-driver](https://user-images.githubusercontent.com/33796120/145278723-b0049b2b-132e-4016-85d1-3e9bc950832d.png)
- Confirmed the Equinix Metal node driver is available in the list of available node drivers when creating a cluster:
![selecting-node-driver](https://user-images.githubusercontent.com/33796120/145278907-a1510f19-796b-4de1-892d-b8753248f1d8.png)
- Confirmed the cluster create page shows Equinix Metal as the cluster type:
![add-cluster-equinix](https://user-images.githubusercontent.com/33796120/145279257-1248cc01-b249-401b-b6ff-7bc850972ab6.png)

**Comment by deniseschannon** [comment] 2021-12-08 22:48
I am concerned about the upgrade path for people previously using Packet in older versions and then upgrading to ensure that this still works. 

@displague Would you be able to help with testing this as we don't have an active packet account since the acquisition.

**Comment by jakefhyde** [comment] 2021-12-09 18:37
Thanks to @bashofmann I was able to successfully provision a downstream cluster on `v2.6-head` with equinix metal:
![clusters](https://user-images.githubusercontent.com/33796120/145455736-27bc411e-7204-4392-b260-a15566efe445.png)
![dashboard](https://user-images.githubusercontent.com/33796120/145455738-be336030-f7ec-4a92-b0a3-6e3f53093abf.png)

**Comment by deniseschannon** [comment] 2021-12-09 21:05
@jakefhyde What about the upgrade? Can you try deploying in a previous version that still shows Packet and then upgrade to see if it's still working?

**Comment by jakefhyde** [comment] 2021-12-10 00:06
I was able to provision using a node template created in `2.6-head` and then downgrading to a rancher version which still showed packet (`v2.6.0`), as versions which still listed the node driver as packet would not allow creating a node template. 
![v2 6 0-packet](https://user-images.githubusercontent.com/33796120/145491482-cae733fd-3e65-459b-b2f5-ebbb22f4757e.png)
Upgrading to `v2.6-head`:
![2 6-head-packet](https://user-images.githubusercontent.com/33796120/145491522-5c6ab346-7b77-431e-bbc8-1e6e3ca6da96.png)

I also verified that the upgrade from `v2.5.9` would work, as the UI still showed Packet as the provider in `v2.5.9`:
![v2 5 9](https://user-images.githubusercontent.com/33796120/145493913-7852458a-29f3-4669-ae98-6f1e24e45837.png)
Upgrading to `v2.6-head`:
![v2 5 9- v2 6-head](https://user-images.githubusercontent.com/33796120/145493987-95ac8884-7f74-4244-a01c-ba02919cca39.png)

**Comment by jakefhyde** [comment] 2021-12-10 06:20
Validated that updating the k8s version for equinix cluster will properly reconcile.

## v2.6.0 RKE v1.20.12
### Provisioned
![v2 6 0-v1 20 12](https://user-images.githubusercontent.com/33796120/145526944-6adbf278-ae0a-4803-bf00-7116a3f9f928.png)
## v2.6.3-rc4 RKE v1.21.7
### Updating
![updating](https://user-images.githubusercontent.com/33796120/145526511-1cb7ed13-da1d-4f91-baff-2b0d1c906013.png)
### Updated
![updated](https://user-images.githubusercontent.com/33796120/145526509-a806f351-504a-4720-8f53-1af285df1d6d.png)

**Comment by sowmyav27** [comment] 2021-12-10 06:39
Thankyou @jakefhyde for the validations.

**Closed** 2021-12-10 06:39 UTC
Labels: [zube]: QA Working, status/dev-validate, feature/node-drivers, team/area2
