### ISSUE TITLE
[2.8]Rancher RoleTemplate CRD does not validate roles properly

### ISSUE THREAD

**Issue by samjustus** [rancher/rancher#44356] opened 2024-02-06 16:05 UTC
backport rancher/rancher#40584

**Comment by dasarinaidu** [comment] 2024-05-01 17:28
**Observation 1:** Update an existing RoleTemplate with blank verbs -> RoleTemplate is not updating but the Error message is NOT coming from webhook. 

**Steps:**

1. Create a project role template `kubectl create -f roleTemplate.Yaml`
2. Try to update the same role template `kubectl edit roleTemplate test-rt-good'
3. While editing YAML - delete the verbs and Save

**Actual:**
a. The roletemplate edit is not saving -- Good
b. User getting an error -- Good
c. The error message does not have correct information


**Expected:**
a. The error message should be from webhook and it should be same like ApiGroups and Resources


**Actual Error message:**

```
error: roletemplates.management.cattle.io "test-rtp1" is invalid
A copy of your changes has been stored to "/var/folders/ct/xxxxxxxxxxxxx/T/kubectl-edit-xxxxxxxx.yaml"
error: Edit cancelled, no valid changes were saved.
```
**Expected Error:**
```
error: roletemplates.management.cattle.io "test-rt-good" could not be patched: admission webhook "rancher.cattle.io.roletemplates.management.cattle.io" denied the request: roletemplate.rules[0].resources: Required value: resource rules must supply at least one resource
You can run `kubectl replace -f /var/folders/ct/sdgdfg/T/kubectl-edit-gdfgsdg.yaml` to try this update again.
```


**Note:** This is happening with when user pass blank verbs. I am getting proper webhook error message when I pass blank for ApiGroups and Resources

**Comment by dasarinaidu** [comment] 2024-05-01 17:48
**Observation 2: Create a RoleTemplate for a Project/Cluster with blank verbs -> RoleTemplate is not creating but the Error message is NOT coming from webhook.**

**Steps:**

1. Create a project roletemplate, make sure to delete all the verbs from the yaml file
2. kubectl create -f roleTemplate.Yaml

**Actual:**
a. The roletemplate is not created -- Good
b. User getting an error -- Good
c. The error message does not have correct information

Expected:
a. The error message should trigger from webhook and it should be same like ApiGroups and Resources

Actual Error message:

The RoleTemplate "test-rtp1" is invalid: rules[0].verbs: Required value

**Expected Error:**

`The RoleTemplate "test-rt-apiGroups-Blank" is invalid: metadata.name: Invalid value: "test-rt-apiGroups-Blank": a lowercase RFC 1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*')`

Note: This is happening with when user pass blank verbs. I am getting proper webhook error message when I pass blank for ApiGroups and Resources

**Comment by andreas-kupries** [comment] 2024-05-02 11:18
> **Actual:** a. The roletemplate edit is not saving -- Good b. User getting an error -- Good c. The error message does not have correct information
> 
> **Expected:** a. The error message should be from webhook and it should be same like ApiGroups and Resources
> 
> **Actual Error message:**
> 
> ```
> error: roletemplates.management.cattle.io "test-rtp1" is invalid
> A copy of your changes has been stored to "/var/folders/ct/xxxxxxxxxxxxx/T/kubectl-edit-xxxxxxxx.yaml"
> error: Edit cancelled, no valid changes were saved.
> ```

Based on the `A copy of your changes has been stored ...` part of the error, plus the `Edit cancelled` I suspect that the `kubectl edit` command performed its own basic validation on the change without ever submitting it to the kube API. In other words, I suspect that the our webhook never saw the edit, and thus could not generate its own error for it.

And that it doesn't do such pre-validation for the api groups and resources.

Verification likely needs a way to inspect the requests actually arriving at the kube API, and/or our webhook.

If it is true that the `edit` generates the error then I see no way for us to change that.

**Comment by andreas-kupries** [comment] 2024-05-02 11:20
Observation 2 may be the same issue as O1, this time `kubectl create` doing pre-validation.
I recommend to do the same inspection as for O1, i.e. does the request actually reach the webhook ?
If not then the error message has to come from some other part of the system.

**Comment by andreas-kupries** [comment] 2024-05-02 13:44
## Validation Template

## Root Cause

The webhook provided some validation for the rules field of RoleTemplate CRD, however this validation was only a subset of the validations done by kube for rules in builtin rbac objects.

## What was fixed, or what change have occurred

Webhook validation was changed to use kube API functions to perform the `rules` validations, making them equal to what kube itself does for other `rules` fields in builtic rbac objects.

## Areas or cases that should be tested

### RT

- Creation with one or more rules without verbs or apiGroups or resources => error
- Edits or patches removing all verbs, or apiGroups, or resources from one or more rules => error

## What areas could experience regressions

Existing RT validation.

## Are the repro steps accurate/minimal?

AFAIK yes.

**Comment by dasarinaidu** [comment] 2024-05-03 04:59
**Observation 3: Rancher Upgraded from v2.8.3->v2.8-head  is deleting user created RoleTemplates**

**Steps:**

1. Create rancher v2.8.3
2. Create RoleTemplates _kubectl create -f roleTemplate.Yaml_
3. Upgrade rancher from v2.8-head
4. Check for the RoleTemplate which we created on v2.8.3

**Actual:**
All the user created RoleTemplates are deleted as soon as the rancher is upgraded to v2.8.3

**Expected:**
All the RoleTemplates should not be deleted by system





2024/05/03 04:30:50 [INFO] driverMetadata: refreshing data from upstream https://releases.rancher.com/kontainer-driver-metadata/dev-v2.8/data.json
2024/05/03 04:30:50 [INFO] Retrieve data.json from local path /var/lib/rancher-data/driver-metadata/data.json
W0503 04:30:50.726638      53 warnings.go:80] cluster.x-k8s.io/v1alpha3 Cluster is deprecated; use cluster.x-k8s.io/v1beta1 Cluster
2024/05/03 04:30:50 [ERROR] error syncing 'c-m-755scwb6/crtb-krjrd': handler cluster-crtb-sync: couldn't ensure roles: couldn't create clusterRole noapigroup: ClusterRole.rbac.authorization.k8s.io "noapigroup" is invalid: rules[0].apiGroups: Required value: resource rules must supply at least one api group, requeuing
2024/05/03 04:30:50 [ERROR] error syncing 'c-m-755scwb6/crtb-lhddr': handler cluster-crtb-sync: couldn't get role template allexist: roletemplates.management.cattle.io "allexist" not found, handler mgmt-auth-crtb-controller: roletemplates.management.cattle.io "allexist" not found, handler auth-prov-v2-crtb: roletemplates.management.cattle.io "allexist" not found, requeuing
2024/05/03 04:30:50 [ERROR] error syncing 'c-m-755scwb6/crtb-6zj7k': handler cluster-crtb-sync: couldn't ensure roles: couldn't create clusterRole noresnonrls: ClusterRole.rbac.authorization.k8s.io "noresnonrls" is invalid: rules[0].resources: Required value: resource rules must supply at least one resource, requeuing
2024/05/03 04:30:50 [ERROR] error syncing 'c-m-755scwb6/crtb-62t92': handler cluster-crtb-sync: couldn't get role template noverbnresources: roletemplates.management.cattle.io "noverbnresources" not found, handler mgmt-auth-crtb-controller: roletemplates.management.cattle.io "noverbnresources" not found, handler auth-prov-v2-crtb: roletemplates.management.cattle.io "noverbnresources" not found, requeuing
2024/05/03 04:30:50 [ERROR] error syncing 'c-m-755scwb6/crtb-lhddr': handler cluster-crtb-sync: couldn't get role template allexist: roletemplates.management.cattle.io "allexist" not found, handler mgmt-auth-crtb-controller: roletemplates.management.cattle.io "allexist" not found, handler auth-prov-v2-crtb: roletemplates.management.cattle.io "allexist" not found, requeuing
2024/05/03 04:30:50 [ERROR] error syncing 'c-m-755scwb6/crtb-62t92': handler cluster-crtb-sync: couldn't get role template noverbnresources: roletemplates.management.cattle.io "noverbnresources" not found, handler mgmt-auth-crtb-controller: roletemplates.management.cattle.io "noverbnresources" not found, handler auth-prov-v2-crtb: roletemplates.management.cattle.io "noverbnresources" not found, requeuing
2024/05/03 04:30:50 [ERROR] error syncing 'c-m-755scwb6/crtb-lhddr': handler cluster-crtb-sync: couldn't get role template allexist: roletemplates.management.cattle.io "allexist" not found, handler mgmt-auth-crtb-controller: roletemplates.management.cattle.io "allexist" not found, handler auth-prov-v2-crtb: roletemplates.management.cattle.io "allexist" not found, requeuing
2024/05/03 04:30:50 [ERROR] error syncing 'c-m-755scwb6/crtb-62t92': handler cluster-crtb-sync: couldn't get role template noverbnresources: roletemplates.management.cattle.io "noverbnresources" not found, handler mgmt-auth-crtb-controller: roletemplates.management.cattle.io "noverbnresources" not found, handler auth-prov-v2-crtb: roletemplates.management.cattle.io "noverbnresources" not found, requeuing
2024/05/03 04:30:50 [ERROR] error syncing 'c-m-755scwb6/crtb-lhddr': handler cluster-crtb-sync: couldn't get role template allexist: roletemplates.management.cattle.io "allexist" not found, handler mgmt-auth-crtb-controller: roletemplates.management.cattle.io "allexist" not found, handler auth-prov-v2-crtb: roletemplates.management.cattle.io "allexist" not found, requeuing
2024/05/03 04:30:50 [ERROR] error syncing 'c-m-755scwb6/crtb-62t92': handler cluster-crtb-sync: couldn't get role template noverbnresources: roletemplates.management.cattle.io "noverbnresources" not found, handler mgmt-auth-crtb-controller: roletemplates.management.cattle.io "noverbnresources" not found, handler auth-prov-v2-crtb: roletemplates.management.cattle.io "noverbnresources" not found, requeuing
2024/05/03 04:30:50 [ERROR] error syncing 'c-m-755scwb6/crtb-lhddr': handler cluster-crtb-sync: couldn't get role template allexist: roletemplates.management.cattle.io "allexist" not found, handler mgmt-auth-crtb-controller: roletemplates.management.cattle.io "allexist" not found, handler auth-prov-v2-crtb: roletemplates.management.cattle.io "allexist" not found, requeuing
2024/05/03 04:30:50 [ERROR] error syncing 'c-m-755scwb6/crtb-62t92': handler cluster-crtb-sync: couldn't get role template noverbnresources: roletemplates.management.cattle.io "noverbnresources" not found, handler mgmt-auth-crtb-controller: roletemplates.management.cattle.io "noverbnresources" not found, handler auth-prov-v2-crtb: roletemplates.management.cattle.io "noverbnresources" not found, requeuing
2024/05/03 04:30:50 [INFO] clusterDeploy: redeployAgent: redeploy Rancher agents due to agent env vars mismatched for [c-m-755scwb6], was [[{CATTLE_SERVER_VERSION v2.8.3 nil} {CATTLE_INSTALL_UUID 9d9cb574-3930-4f50-aaf6-283a31f50e99 nil} {CATTLE_INGRESS_IP_DOMAIN sslip.io nil}]] and will be [[]]
2024/05/03 04:30:50 [INFO] Creating system token for u-4jvkwiliqe, token: agent-u-4jvkwiliqe
W0503 04:30:50.896900      53 warnings.go:80] cluster.x-k8s.io/v1alpha3 MachineSet is deprecated; use cluster.x-k8s.io/v1beta1 MachineSet
2024/05/03 04:30:51 [ERROR] error syncing 'c-m-755scwb6/crtb-lhddr': handler cluster-crtb-sync: couldn't get role template allexist: roletemplates.management.cattle.io "allexist" not found, handler mgmt-auth-crtb-controller: roletemplates.management.cattle.io "allexist" not found, handler auth-prov-v2-crtb: roletemplates.management.cattle.io "allexist" not found, requeuing
2024/05/03 04:30:51 [ERROR] error syncing 'c-m-755scwb6/crtb-62t92': handler cluster-crtb-sync: couldn't get role template noverbnresources: roletemplates.management.cattle.io "noverbnresources" not found, handler mgmt-auth-crtb-controller: roletemplates.management.cattle.io "noverbnresources" not found, handler auth-prov-v2-crtb: roletemplates.management.cattle.io "noverbnresources" not found, requeuing
2024/05/03 04:30:51 [INFO] Starting provisioning.cattle.io/v1, Kind=Cluster controller
2024/05/03 04:30:51 [INFO] Starting cluster.x-k8s.io/v1alpha3, Kind=Cluster controller
2024/05/03 04:30:51 [INFO] Starting cluster.x-k8s.io/v1alpha3, Kind=MachineHealthCheck controller
2024/05/03 04:30:51 [INFO] Starting cluster.x-k8s.io/v1alpha3, Kind=MachineSet controller
2024/05/03 04:30:51 [INFO] Starting rke.cattle.io/v1, Kind=CustomMachine controller
2024/05/03 04:30:51 [INFO] Starting rke.cattle.io/v1, Kind=ETCDSnapshot controller
2024/05/03 04:30:51 [INFO] Starting rke.cattle.io/v1, Kind=RKEBootstrap controller
2024/05/03 04:30:51 [INFO] Starting rke.cattle.io/v1, Kind=RKEBootstrapTemplate controller
2024/05/03 04:30:51 [INFO] Starting rke.cattle.io/v1, Kind=RKECluster controller
2024/05/03 04:30:51 [INFO] Starting rke.cattle.io/v1, Kind=RKEControlPlane controller
2024/05/03 04:30:51 [INFO] Starting rke-machine.cattle.io/v1, Kind=Amazonec2Machine controller
2024/05/03 04:30:51 [INFO] [machineprovision] fleet-default/dastest1-pool1-a249cd57-kbmrb: reconciling machine job
2024/05/03 04:30:51 [INFO] Starting rke-machine.cattle.io/v1, Kind=Amazonec2MachineTemplate controller
2024/05/03 04:30:51 [INFO] Starting rke-machine.cattle.io/v1, Kind=AzureMachine controller
2024/05/03 04:30:51 [INFO] Starting rke-machine.cattle.io/v1, Kind=AzureMachineTemplate controller
2024/05/03 04:30:51 [INFO] Starting rke-machine.cattle.io/v1, Kind=DigitaloceanMachine controller
2024/05/03 04:30:51 [INFO] Starting rke-machine.cattle.io/v1, Kind=DigitaloceanMachineTemplate controller
2024/05/03 04:30:51 [INFO] Starting rke-machine.cattle.io/v1, Kind=HarvesterMachine controller
2024/05/03 04:30:51 [INFO] Starting rke-machine.cattle.io/v1, Kind=HarvesterMachineTemplate controller
2024/05/03 04:30:51 [INFO] Starting rke-machine.cattle.io/v1, Kind=LinodeMachine controller
2024/05/03 04:30:51 [INFO] Starting rke-machine.cattle.io/v1, Kind=LinodeMachineTemplate controller
2024/05/03 04:30:51 [INFO] Starting rke-machine.cattle.io/v1, Kind=VmwarevsphereMachine controller
2024/05/03 04:30:51 [INFO] Starting rke-machine.cattle.io/v1, Kind=VmwarevsphereMachineTemplate controller
2024/05/03 04:30:51 [INFO] Starting rke-machine-config.cattle.io/v1, Kind=HarvesterConfig controller
2024/05/03 04:30:51 [INFO] Starting rke-machine-config.cattle.io/v1, Kind=LinodeConfig controller
2024/05/03 04:30:51 [INFO] Starting rke-machine-config.cattle.io/v1, Kind=VmwarevsphereConfig controller
2024/05/03 04:30:51 [ERROR] error syncing 'c-m-755scwb6/crtb-62t92': handler cluster-crtb-sync: couldn't get role template noverbnresources: roletemplates.management.cattle.io "noverbnresources" not found, handler mgmt-auth-crtb-controller: roletemplates.management.cattle.io "noverbnresources" not found, handler auth-prov-v2-crtb: roletemplates.management.cattle.io "noverbnresources" not found, requeuing
2024/05/03 04:30:51 [ERROR] error syncing 'c-m-755scwb6/crtb-lhddr': handler cluster-crtb-sync: couldn't get role template allexist: roletemplates.management.cattle.io "allexist" not found, handler mgmt-auth-crtb-controller: roletemplates.management.cattle.io "allexist" not found, handler auth-prov-v2-crtb: roletemplates.management.cattle.io "allexist" not found, requeuing
2024/05/03 04:30:51 [INFO] [planner] rkecluster fleet-default/dastest1: configuring bootstrap node(s) dastest1-pool1-58dbb556c9xcjc8b-bfx62: waiting for plan to be applied
2024/05/03 04:30:51 [ERROR] error syncing 'c-m-755scwb6/crtb-62t92': handler cluster-crtb-sync: couldn't get role template noverbnresources: roletemplates.management.cattle.io "noverbnresources" not found, handler mgmt-auth-crtb-controller: roletemplates.management.cattle.io "noverbnresources" not found, handler auth-prov-v2-crtb: roletemplates.management.cattle.io "noverbnresources" not found, requeuing
2024/05/03 04:30:51 [ERROR] error syncing 'c-m-755scwb6/crtb-lhddr': handler cluster-crtb-sync: couldn't get role template allexist: roletemplates.management.cattle.io "allexist" not found, handler mgmt-auth-crtb-controller: roletemplates.management.cattle.io "allexist" not found, handler auth-prov-v2-crtb: roletemplates.management.cattle.io "allexist" not found, requeuing
2024/05/03 04:30:52 [INFO] Updating global catalog system-library
2024/05/03 04:30:52 [ERROR] error syncing 'c-m-755scwb6/crtb-krjrd': handler cluster-crtb-sync: couldn't get role template noapigroup: roletemplates.management.cattle.io "noapigroup" not found, handler mgmt-auth-crtb-controller: roletemplates.management.cattle.io "noapigroup" not found, handler auth-prov-v2-crtb: roletemplates.management.cattle.io "noapigroup" not found, requeuing
2024/05/03 04:30:52 [ERROR] error syncing 'c-m-755scwb6/crtb-6zj7k': handler cluster-crtb-sync: couldn't get role template noresnonrls: roletemplates.management.cattle.io "noresnonrls" not found, handler mgmt-auth-crtb-controller: roletemplates.management.cattle.io "noresnonrls" not found, handler auth-prov-v2-crtb: roletemplates.management.cattle.io "noresnonrls" not found, requeuing
2024/05/03 04:30:52 [INFO] [planner] rkecluster fleet-default/dastest1: configuring bootstrap node(s) dastest1-pool1-58dbb556c9xcjc8b-bfx62: waiting for plan to be applied
2024/05/03 04:30:53 [INFO] Refreshing driverMetadata in 1440 minutes
2024/05/03 04:30:53 [INFO] driverMetadata: refreshing data from upstream https://releases.rancher.com/kontainer-driver-metadata/dev-v2.8/data.json
2024/05/03 04:30:53 [INFO] Retrieve data.json from local path /var/lib/rancher-data/driver-metadata/data.json
2024/05/03 04:30:53 [INFO] Loaded configuration from https://releases.rancher.com/kontainer-driver-metadata/dev-v2.8/data.json in [0x84317a0]
2024/05/03 04:30:53 [INFO] getReleaseConfig: reloading config for rke2
2024/05/03 04:30:54 [INFO] Loaded configuration from https://releases.rancher.com/kontainer-driver-metadata/dev-v2.8/data.json in [0x84317a0]
2024/05/03 04:30:54 [INFO] getReleaseConfig: reloading config for k3s
2024/05/03 04:30:54 [INFO] Creating token for user user-xm42h
time="2024-05-03 04:30:54" level=info msg="Telemetry Client v0.6.2"
time="2024-05-03 04:30:54" level=info msg="Listening on 0.0.0.0:8114"
2024/05/03 04:30:54 [INFO] kontainerdriver azurekubernetesservice listening on address 127.0.0.1:36467
2024/05/03 04:30:54 [INFO] kontainerdriver googlekubernetesengine listening on address 127.0.0.1:34841
2024/05/03 04:30:54 [INFO] kontainerdriver amazonelasticcontainerservice listening on address 127.0.0.1:40891
2024/05/03 04:30:54 [INFO] kontainerdriver googlekubernetesengine stopped
2024/05/03 04:30:54 [INFO] dynamic schema for kontainerdriver googlekubernetesengine updating
2024/05/03 04:30:54 [INFO] kontainerdriver azurekubernetesservice stopped
2024/05/03 04:30:54 [INFO] dynamic schema for kontainerdriver azurekubernetesservice updating
2024/05/03 04:30:54 [INFO] kontainerdriver amazonelasticcontainerservice stopped
2024/05/03 04:30:54 [INFO] dynamic schema for kontainerdriver amazonelasticcontainerservice updating
2024/05/03 04:30:55 [INFO] Catalog sync done. 0 templates created, 7 templates updated, 0 templates deleted, 0 templates failed
2024/05/03 04:30:56 [INFO] Loaded configuration from https://releases.rancher.com/kontainer-driver-metadata/dev-v2.8/data.json in [0x84317a0]
2024/05/03 04:30:56 [INFO] Loaded configuration from https://releases.rancher.com/kontainer-driver-metadata/dev-v2.8/data.json in [0x84317a0]
2024/05/03 04:30:56 [ERROR] error syncing 'c-m-755scwb6/crtb-lhddr': handler cluster-crtb-sync: couldn't get role template allexist: roletemplates.management.cattle.io "allexist" not found, handler mgmt-auth-crtb-controller: roletemplates.management.cattle.io "allexist" not found, handler auth-prov-v2-crtb: roletemplates.management.cattle.io "allexist" not found, requeuing
2024/05/03 04:30:56 [ERROR] error syncing 'c-m-755scwb6/crtb-62t92': handler cluster-crtb-sync: couldn't get role template noverbnresources: roletemplates.management.cattle.io "noverbnresources" not found, handler mgmt-auth-crtb-controller: roletemplates.management.cattle.io "noverbnresources" not found, handler auth-prov-v2-crtb: roletemplates.management.cattle.io "noverbnresources" not found, requeuing
2024/05/03 04:30:57 [INFO] [planner] rkecluster fleet-default/dastest1: configuring bootstrap node(s) dastest1-pool1-58dbb556c9xcjc8b-bfx62: waiting for plan to be applied
2024/05/03 04:30:57 [INFO] Redeploy Rancher Agents is needed for c-m-755scwb6: forceDeploy=false, agent/auth image changed=true, private repo changed=false, agent features changed=false

**Comment by andreas-kupries** [comment] 2024-05-03 10:43
# Investigation Report
## Summary

- I failed to reproduce the issue
- The detailed steps taken can be found below
- I assumed that `2.8.4-alpha1` is `2.8-head`
- As I did not really know how to install and upgrade Rancher from Helm I went with the official documentation at
  - https://ranchermanager.docs.rancher.com/getting-started/installation-and-upgrade/install-upgrade-on-a-kubernetes-cluster, and
  - https://ranchermanager.docs.rancher.com/getting-started/installation-and-upgrade/install-upgrade-on-a-kubernetes-cluster/upgrades
- As the description only said a role template with no details I made my own role template
  - I suspect that the issue can be found in the differences between my RT and whatever RT was used by QA.

## Session

  1. Added various rancher helm repos to my setup
     1. `helm repo add rancher-stable https://releases.rancher.com/server-charts/stable`
     1. `helm repo add rancher-latest https://releases.rancher.com/server-charts/latest`
     1. `helm repo add rancher-alpha https://releases.rancher.com/server-charts/alpha`
  1. Determined available versions
     1. `helm search repo --devel --versions | grep rancher | grep '2\.8\.' | sort -d -k 2 | tail -5`
     1. Found `rancher-stable/rancher 2.8.3` and `rancher-alpha/rancher 2.8.4-alpha1`
     1. Used the latter for `2.8-head`.
  1. Continued setup
     1. `helm repo add jetstack https://charts.jetstack.io`
     1. `helm install cert-manager jetstack/cert-manager --namespace cert-manager --create-namespace --set installCRDs=true`
     1. `kubectl get pods --namespace cert-manager`
     1. `kubectl create namespace cattle-system`
     1. `helm install rancher rancher-stable/rancher --namespace cattle-system --set hostname=HOST --set bootstrapPassword=admin --set ingress.tls.source=rancher --version 2.8.3`
  1. Waiting for deployment
     1. `kubectl -n cattle-system rollout status deploy/rancher`
  1. Creation and addition of a role template
     1. Inspect
     	1. `kubectl get roletemplates`
     1. Get system RT
     	1. `k get roletemplates persistentvolumeclaims-manage -o yaml > persistentvolumeclaims-manage.yaml`
     	1. Attached [persistentvolumeclaims-manage.yaml.txt](https://github.com/rancher/rancher/files/15198800/persistentvolumeclaims-manage.yaml.txt)
     1. Made copy, edited copy
	 1. `cp persistentvolumeclaims-manage.yaml user1-rt.yaml`
	 1. `emacs user1-rt.yaml`
	     1. Edited display name, name
	     1. Removed builtin, generation, labels, managedFields, resourceVersion, uid, creation timestamp
	 1. Attached [user1-rt.yaml.txt](https://github.com/rancher/rancher/files/15198805/user1-rt.yaml.txt)
     1. Upload of user RT, verify presence
	 1. `kubectl create -f user1-rt.yaml`
	 1. `kubectl get roletemplates |grep persistentvolumeclaims-manage`
	      > persistentvolumeclaims-manage                11m
	      > user-copy-of-persistentvolumeclaims-manage   28s
  1. Upgrading deployment
     1. Ensure non-interference from old charts, images
     	1. `helm repo remove rancher-stable`
     	1. `helm repo remove rancher-latest`
     1. `helm upgrade rancher rancher-alpha/rancher --namespace cattle-system --set hostname=HOST --set bootstrapPassword=admin --set ingress.tls.source=rancher --version 2.8.4-alpha1`
  1. Waiting for redeployment
     1. `kubectl -n cattle-system rollout status deploy/rancher`
  1. Checking role templates, immediately after
	 1. `kubectl get roletemplates |grep persistentvolumeclaims-manage`
	      > persistentvolumeclaims-manage                24m
	      > user-copy-of-persistentvolumeclaims-manage   12m
  1. Checking role templates ~16 minutes later
	 1. `kubectl get roletemplates |grep persistentvolumeclaims-manage`
	      > persistentvolumeclaims-manage                40m
	      > user-copy-of-persistentvolumeclaims-manage   29m

The user RT is not removed, not immediately, not later.

**Comment by dasarinaidu** [comment] 2024-05-03 14:19
I created a new ticket for the Observation 3. 
https://github.com/rancher/rancher/issues/45365

**Comment by dasarinaidu** [comment] 2024-05-03 18:35
Observation 4: [BUG] : Wrong Inherit RoleTemplates throwing Internal Error exception from webhook https://github.com/rancher/rancher/issues/45371

Note: This is an existing issue

**Comment by dasarinaidu** [comment] 2024-05-03 19:47
Observation 5 : [BUG] : Inherit RoleTemplates throwing Error exception from webhook without roletemplate name
https://github.com/rancher/rancher/issues/45372

**Comment by dasarinaidu** [comment] 2024-05-07 13:55
I have completed validations on Rancher Version : v2.8-b12e35523bdfe1b39779e1064f4827a8899913a8-head (rancher/rancher-webhook:v0.4.4-rc1). I m closing the card with above observations.

**Closed by dasarinaidu** 2024-05-07 13:55 UTC
Labels: kind/bug, priority/2, area/rbac, [zube]: QA Working, QA/M, team/collie
