### ISSUE TITLE
RKE2 & RKE1 with calico and project network isolation breaks ingress controller to pod communication

### ISSUE THREAD

**Issue by bashofmann** [rancher/rancher#33979] opened 2021-08-05 13:56 UTC
**Rancher Server Setup**
- Rancher version: v2.5.9 and v2.6.0-rc1
- Installation option (Docker install/Helm Chart): Helm
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): v1.21.3+k3s1
- Proxy/Cert Details: no proxy, Let's Encrypt certificate

**Information about the Cluster**
- Kubernetes version: RKE2: v1.21.3+rke2r1 and RKE: v1.20.9-rancher1-1
- Cluster Type (Local/Downstream): downstream
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider): tested with custom and digital ocean infrastructure provider

**Describe the bug**
When you create an RKE1 or RKE2 cluster with calico as a CNI (default for RKE2) and activate project network isolation. The communication between the ingress controller and the Pods does not work anymore.

**To Reproduce**
* Create a multi node RKE2 custom cluster
* Choose default Calico CNI
* Activate project network isolation
* Create a workload (e.g.) an nginx and an ingress
* Try to reach the ingress

**Result**
The nginx ingress controller will get a gateway timeout when communication with the pod:

```
curl 35.158.100.209 -H 'Host: nginx.example'
<html>
<head><title>504 Gateway Time-out</title></head>
<body>
<center><h1>504 Gateway Time-out</h1></center>
<hr><center>nginx</center>
</body>
</html>
```

**Expected Result**
The communication works out of the box.

**Additional context**
The communication works out of the box, if you choose canal as a CNI. Rancher automatically creates a `hn-nodes` NetworkPolicy in every namespace, which should allow communication from the ingress controller. The policy works fine for canal, but not for calico.
If I understand it correctly, Rancher creates the policy from the node's podCIDRs:

```
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  creationTimestamp: "2021-08-05T13:28:45Z"
  generation: 3
  name: hn-nodes
  namespace: default
  ownerReferences:
  - apiVersion: v1
    kind: Namespace
    name: default
    uid: f6372a0d-28e0-4538-b649-ae8dd62355d8
  resourceVersion: "3157"
  uid: e31fe0a2-0f2c-43de-877b-450fb8b0cd01
spec:
  ingress:
  - from:
    - ipBlock:
        cidr: 10.42.0.0/32
    - ipBlock:
        cidr: 10.42.1.0/32
    - ipBlock:
        cidr: 10.42.2.0/32
  podSelector: {}
  policyTypes:
  - Ingress
```

With Calico the communication only works, if I create such a policy from the `projectcalico.org/IPv4VXLANTunnelAddr`:

```
kubectl get nodes -o yaml | grep projectcalico.org/IPv4VXLANTunnelAddr
      projectcalico.org/IPv4VXLANTunnelAddr: 10.42.0.0
      projectcalico.org/IPv4VXLANTunnelAddr: 10.42.32.0
      projectcalico.org/IPv4VXLANTunnelAddr: 10.42.212.0
```

A working policy

```
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-ingress-controller
  namespace: default
spec:
  ingress:
  - from:
    - ipBlock:
        cidr: 10.42.0.0/32
  - from:
    - ipBlock:
        cidr: 10.42.212.0/32
  - from:
    - ipBlock:
        cidr: 10.42.32.0/32                
  podSelector: {}
  policyTypes:
  - Ingress
```

In not quite sure though, if adding this allows to much or is too broad.

**Comment by ryansann** [comment] 2021-08-05 18:36
This may not be a bug- @bashofmann are you using xip.io generated hostnames for ingress? If so, would you mind trying with nip.io instead? xip.io has been down for a while. You can do something like grab an ingress ip and do <ip>.nip.io and forward that to a workload you have deployed

**Comment by bashofmann** [comment] 2021-08-05 18:38
I haven't been using `xip.io` generated hostnames. And I can reach the ingress controller, but the ingress controller can't reach the pods and responds with a 504. As soon as I create the NetworkPolicy with the correct cidrs, everything works.

**Comment by ryansann** [comment] 2021-08-05 23:04
I see what you mean @bashofmann. Looks like this only happens when traffic traverses nodes, i.e. the ingress that's hit is on a different node than the pod it forwards to. I think I see the issue, working on a fix for this.

**Comment by ryansann** [comment] 2021-08-09 17:44
This PR for the fix has been opened. These changes fix the PNI `hn-nodes` NetworkPolicies for Calico on RKE1 and RKE2 clusters.

These changes can be validated by deploying a few clusters and ensuring that traffic can reach workloads through ingress controllers.

I tested this by deploying 4 clusters with PNI enabled:
- RKE2 Calico (1 control plane, 1 worker)
- RKE2 Canal (1 control plane, 1 worker)
- RKE Calico (1 control plane, 1 worker)
- RKE Canal (1 control plane, 1 worker)

NOTE: When testing ingress, the traffic needs to traverse nodes. i.e. if the you're hitting the ingress controller on the control plane node, the pod in the destination workload needs to be running on the worker node.

**Comment by deniseschannon** [comment] 2021-08-16 19:19
@bashofmann If you have time, can you check if you can still reproduce this in v2.6.0-rc3?

**Comment by aaronRancher** [comment] 2021-08-17 00:07
This issue is reproduced on Rancher v2.5.9 with the following steps:
- Deploy a multinode RKEv1 cluster.
- Choose Calico CNI
- Select PNI
- After cluster becomes available, create a workload (e.g.) an nginx and an ingress
- Try to reach the ingress

Result:
```
> curl <IP> -H "Host: nginx.example"
<html>
<head><title>504 Gateway Time-out</title></head>
<body>
<center><h1>504 Gateway Time-out</h1></center>
<hr><center>nginx</center>
</body>
</html>
```

On Rancher `v2.6-head` `version 3c3645d`:

```
> curl <IP> -H "Host: nginx.example"
<html>
<head>
<title>Welcome to nginx!</title>
<style>
    body {
...
```

**Comment by bashofmann** [comment] 2021-08-17 08:51
@deniseschannon works for me with `v2.6-head 78b78cb`. I also tested and verified that it still works with canal.

I also tested with cilium as a CNI, and the same issue exists there, because cilium needs a different way of configuring it. I opened up a separate issue for cilium: https://github.com/rancher/rancher/issues/34275.

**Comment by aaronRancher** [comment] 2021-08-18 00:33
Tested an upgrade use case with the following steps:
Bring up Rancher `v2.5.9`
Deploy a multinode RKEv1 cluster.
Choose Calico CNI
Select PNI
After cluster becomes available, create a workload (e.g.) an nginx and an ingress
Upgrade Rancher to `v2.6-head` `version 72986b2`
Try to reach the ingress

Result:
Ingress is accessible.
```
> curl <IP> -H "Host: nginx.example"
<html>
<head>
<title>Welcome to nginx!</title>
<style>
    body {
...
```

**Closed by aaronRancher** 2021-08-18 00:33 UTC
Labels: [zube]: QA Working, release-note, status/final-release-blocker
