### ISSUE TITLE
[RFE] Add Env var setting to swap registry

### ISSUE THREAD

**Issue by samjustus** [rancher/rancher#38550] opened 2022-08-08 17:33 UTC
This can literally just be an env var that we inject at build time. The public drone pipeline won't use it, and the internal one will. The unknowns here are if we have to put it to a lower level, like in the dockerfile to trigger changes in things like rancher-machine or provisioning. 

SURE-5046

**Comment by cbron** [comment] 2022-09-13 21:25
Duplicate of: https://github.com/rancher/rancher/issues/38808

**Closed by cbron** 2022-09-13 21:25 UTC
Labels: kind/feature, [zube]: Review, team/area1
