### ISSUE TITLE
Deis is failing on Kubernetes 1.3

### ISSUE THREAD

**Issue by galal-hussein** [rancher/rancher#5595] opened 2016-07-29 20:16 UTC
**Rancher Version:**
v1.2.0-pre1
**Docker Version:**
1.10.3
**OS and where are the hosts located? (cloud, bare metal, etc):**
ubuntu
**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
single node rancher
**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Kubernetes 1.3
**Steps to Reproduce:**
Run the installation workflow for deis from their official [guide](https://deis.com/docs/workflow/installing-workflow/)
**Results:** 
The following pods are stuck in pending state and no containers being created:
- deis-builder
- deis-controller
- deis-database
- deis-logger-fluentd
- deis-minio
- deis-monitor-telegraf
- deis-registry

```
 kubectl --namespace=deis get pods
NAME                          READY     STATUS              RESTARTS   AGE
deis-builder-h1x39            0/1       ContainerCreating   0          28m
deis-controller-3xqxt         0/1       CrashLoopBackOff    10         28m
deis-database-ga041           0/1       ContainerCreating   0          28m
deis-logger-fluentd-x9let     1/1       Running             0          28m
deis-logger-fluentd-zx66o     0/1       ContainerCreating   0          28m
deis-logger-redis-bohlq       1/1       Running             0          28m
deis-logger-tnzt6             1/1       Running             3          28m
deis-minio-fvff8              0/1       ContainerCreating   0          28m
deis-monitor-grafana-z9ly1    1/1       Running             0          28m
deis-monitor-influxdb-0hhcg   1/1       Running             0          28m
deis-monitor-telegraf-2oten   1/1       Running             2          28m
deis-monitor-telegraf-n8rdb   0/1       ContainerCreating   0          28m
deis-nsqd-o55m0               1/1       Running             0          28m
deis-registry-gsn9i           0/1       ContainerCreating   0          28m
deis-router-dwc8v             1/1       Running             0          28m
deis-workflow-manager-e7x3d   1/1       Running             0          28m
```

**Comment by robeastham** [comment] 2016-10-17 00:40
Any news on this? I just spent quite a while getting a Rancher Server up and running with the intention of running DEIS Workflow on it (aka Deis 2.0). I then found this bug :-)

I'm on the current recommended release v1.2.0-pre3. I haven't actually tried to get DEIS running on Rancher K8S yet because it looks like this bug is still open.

The bug looks to be related to Kubernetes environments on Rancher only being available in v1.3.0 flavour. The setup documentation for DEIS Workflow mentions an incompatibility between DEIS and Kubernetes v1.30 through to v1.3.3 here:

https://deis.com/docs/workflow/installing-workflow/system-requirements/

It appears to have been fixed in in v1.3.4 of Kubernetes:

https://github.com/deis/workflow/issues/372

Sounds like it is not a problem in Kubernetes 1.4.0 either. 

I'm guessing the above is already known, but thought I'd mention it in case no one else has connected the dots and this does turn out to be the reason for this bug.

**Comment by wlan0** [comment] 2016-10-17 21:04
@robeastham Thanks for stating what you did above. You were right about deis not working because of kubectl incompatibility. Starting from Rancher-1.2, we'll be supporting Kubernetes 1.4 and kubectl 1.4. 

I tested deis workflow on rancher kubernetes 1.4, with a remote kubectl 1.4 client and it worked just fine. I did all the steps except creating an app (i had an issue with the deis registry proxy, but that problem might be only in my setup, and not a bug). 

We are waiting for this issue to be resolved before upgrading our default kubectl to 1.4. https://github.com/kubernetes/kubernetes/issues/3358. Once the fix for this issue is a part of a kubectl release, we'll be able to add kubectl 1.4.X as a part of rancher deployment. Until then, you can setup your own remote kubectl client pointing to rancher kubernetes.

**Comment by robeastham** [comment] 2016-10-17 22:54
@wlan0 Thanks for the update and it's great to hear that Rancher and Deis interoperability is on the radar. 

Just wondering, are you sure this will work as a workaround with v1.2.0-pre3:
> Until then, you can setup your own remote kubectl client pointing to rancher kubernetes.

Perhaps I misunderstood, but I got the impression that this bug was not related to which client was being used to access the K8S cluster on Rancher and was more to do with K8S v1.3.0->v1.33 secret bug I linked to. I'm new to K8S though and so perhaps I've missed something?

I tried rolling back to v1.1.4 of Rancher Server today, since that does come with K8S 1.2, which I believe should work with Deis Workflow. Sadly I seem to be getting corrupted nginx _location config files after a reboot and so that backward version step appears to be another dead end. 

I noticed that v1.2.0-pre4-rc3 and v1.2.0-pre4-rc4 were both released today. Anyone have any view on the stability of these two releases when compared to  v1.2.0-pre3?

Also when is final v.1.2.0 expected to land. No pressure. Just wondering :-)

**Comment by wlan0** [comment] 2016-10-18 00:18
@robeastham Yes, the issue was with kubernetes secret management, and not just the client version. 

I tested it only with 1.4 and I'm new to deis. Sorry that I mislead you. 

You need atleast k8s 1.3.4 or above to get deis to work. 

There is unfortunately another bug that is preventing deis from working fully - https://github.com/deis/workflow/issues/442. 

Deis workflow currently uses hostport https://github.com/deis/charts/blob/master/workflow-v2.7.0/tpl/deis-registry-proxy-daemon.yaml#L43, 

and CNI and hostport dont play along well (https://github.com/kubernetes/kubernetes/issues/31307, https://groups.google.com/forum/#!msg/kubernetes-sig-network/lEP8lA1KKEs/zOlLqsBrBQAJ) 

Since v1.2.0 is going to be released on Oct 28th, and the CNI hostport issue wont be fixed within then, I'm moving this to v.1.3.0

**Comment by felixbuenemann** [comment] 2016-10-19 20:06
The deis registry proxy can be disabled if docker is run with `--insecure-registry=10.0.0.0/8` (or whatever is used for the k8s service IP range). See bacongobbler's comment on deis/registry#64 for details on how to remove the registry proxy.

**Comment by bacongobbler** [comment] 2016-10-20 21:11
Hey @galal-hussein and @robeastham! In the future please feel free to post any issues with Deis at https://github.com/deis/workflow so we're not bothering the Rancher team to debug our issues. Hehe :smile: 

@felixbuenemann is correct that this is indeed a symptom of deis/registry#64 and at this time it is an issue related to kubernetes manifests that request a hostport are not fulfilled on operating systems that use CNI networking as @wlan0 already mentioned earlier. We finally identified this issue yesterday ourselves with our professional services team. It's not just a RancherOS issue, but a CoreOS issue as well. When we do acceptance testing for our releases, we only test the four most common deployments:

 - AWS with kube-up (uses an Ubuntu AMI)
 - GKE with kube-up (uses Debian)
 - Vagrant with kube-up (uses Fedora)
 - Minikube (uses a custom ISO)

The comment @felixbuenemann mentioned with the workaround so Deis can run on top of Rancher/CoreOS would be https://github.com/deis/registry/issues/64#issuecomment-254916941.

**Comment by wlan0** [comment] 2016-10-20 21:16
Thanks @bacongobbler for painting the complete picture on the issue!

**Comment by superseb** [comment] 2017-10-27 17:07
This can be closed

**Closed by superseb** 2017-10-27 17:07 UTC
Labels: area/kubernetes, kind/bug
