### ISSUE TITLE
Error deploying services that use the same convoy-nfs container

### ISSUE THREAD

**Issue by nunofgs** [rancher/rancher#5404] opened 2016-07-12 13:46 UTC
**Rancher Version:**
1.1.0.

**Docker Version:**
1.10.3.

**OS and where are the hosts located? (cloud, bare metal, etc):**
AWS.

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
Single node rancher.

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle.

**Steps to Reproduce:**
1. Make sure you have a correctly deployed convoy-nfs stack.
2. Create a new stack and use this `docker-compose.yml`:

```yml
nginx:
  image: nginx:latest
  volumes:
    - myvol:/foobar
  volume_driver: convoy-nfs

hello:
  image: tutumcloud/hello-world
  labels:
    io.rancher.container.start_once: 'true'
  volumes:
    - myvol:/foobar
    - anothervol:/foobiz
  volume_driver: convoy-nfs
```

If you'll notice above, both services use the same `myvol` volume.

**Results:** 

The containers will never start up and will be stuck in "Starting..." state. Here's what the volume page looks like:

<img width="1343" alt="screen shot 2016-07-12 at 14 28 22" src="https://cloud.githubusercontent.com/assets/92085/16769138/42b085ea-483f-11e6-8f6a-8cb304ec307e.png">

If I navigate to "Admin" -> "Processes", there is an error: "Volume already exists 'myvol'" (paraphrasing as I do not have it in front of me).

**Expected:**

Both containers should start up and use the same convoy-nfs volume without issue.

**Comment by nunofgs** [comment] 2016-07-12 13:49
I have found a workaround for this issue:

1. When creating the stack, untick "Start services after creating".
2. Start one of the services and wait until it becomes "Active".
3. Start the other service.

Both services will now be using the same volume successfully.

_Note:_ this workaround should **not** be needed and this is definitely a bug in my opinion.

**Comment by cjellick** [comment] 2016-07-12 15:33
Agree, it is a bug. Must be a race condition in volume creation. Will dig into it.

**Comment by cjellick** [comment] 2016-10-03 16:25
@deniseschannon is this a dupe of #4460?

**Comment by deniseschannon** [comment] 2016-10-04 04:26
Yes, this looks like a duplicate of #4460. Closing in favor of that one.

**Closed by deniseschannon** 2016-10-04 04:26 UTC
Labels: area/storage, kind/bug
