### ISSUE TITLE
[BUG] COREDNS deployment manifest `replicas: 1` in kontainer-driver-metadata will make cluster unstable during upgrade

### ISSUE THREAD

**Issue by orz-nil** [rancher/rancher#42787] opened 2023-09-13 09:25 UTC
**Rancher Server Setup**
- Rancher version: v2.7.5

**Information about the Cluster**
- Kubernetes version: 1.25.12
- Cluster Type Downstream: 
   - type: Custom rke1
   - Infrastructure Provider: aws

**Describe the bug**

During cluster version upgrade, the `coredns` deployment manifest will change the replicas to 1, because the manifest template in `kontainer-driver-metadata` data.json set  `replicas: 1`

in our production cluster:  `coredns-autoscaler` set coredns replicas `114`. 
- When doing the cluster upgrade from 1.24.15 to 1.25.12, coredns deploy scale down the replicas to 1, then all coredns pod state change to Terminating. 
- Then `coredns-autoscaler` changes the replicas to the right size. coredns deploy scale-up and create new pods.
- each of the version upgrades, we get this 1~2 mins DNS downtime
**To Reproduce**

**Result**
coredns pod recreate makes cluster unstable
**Expected Result**

delete `replicas: 1` from data.json in `kontainer-driver-metadata` repo,  which breaks the coredns' rolling upgrade

**Screenshots**

<details>

```
coredns-654c6cf984-22rcj                                          0/1     Terminating       0               41d
coredns-654c6cf984-2dk89                                          0/1     Terminating       0               16d
coredns-654c6cf984-2pns8                                          0/1     Terminating       0               36d
coredns-654c6cf984-2wsgg                                          0/1     Terminating       0               14d
coredns-654c6cf984-44c9l                                          0/1     Terminating       0               2d15h
coredns-654c6cf984-4cj49                                          0/1     Terminating       0               13d
coredns-654c6cf984-5dwmm                                          0/1     Terminating       0               27d
coredns-654c6cf984-6bqlp                                          0/1     Terminating       0               16d
coredns-654c6cf984-6mnxl                                          0/1     Terminating       0               7d
coredns-654c6cf984-6xdmf                                          0/1     Terminating       0               5d8h
coredns-654c6cf984-74lbm                                          0/1     Terminating       0               5d9h
coredns-654c6cf984-7f25c                                          0/1     Terminating       0               41d
coredns-654c6cf984-7khfq                                          0/1     Terminating       0               41d
coredns-654c6cf984-7mrb9                                          0/1     Terminating       0               8h
coredns-654c6cf984-7sb56                                          0/1     Terminating       0               23d
coredns-654c6cf984-8dgj4                                          0/1     Terminating       0               13d
coredns-654c6cf984-8jkv5                                          0/1     Terminating       0               7d
coredns-654c6cf984-8mn4t                                          0/1     Terminating       0               19d
coredns-654c6cf984-8v4fv                                          0/1     Terminating       0               8d
coredns-654c6cf984-8wqpc                                          0/1     Terminating       0               27d
coredns-654c6cf984-9496t                                          0/1     Terminating       0               37d
coredns-654c6cf984-9hsxx                                          0/1     Terminating       0               2d8h
coredns-654c6cf984-b2ltm                                          0/1     Terminating       0               26d
coredns-654c6cf984-bhtqv                                          0/1     Terminating       0               16h
coredns-654c6cf984-bk6r2                                          0/1     Terminating       0               33d
coredns-654c6cf984-bpbr5                                          0/1     Terminating       0               20d
coredns-654c6cf984-bzhkd                                          0/1     Terminating       0               7d
coredns-654c6cf984-c2hch                                          0/1     Terminating       0               5h24m
coredns-654c6cf984-cbhfc                                          0/1     Terminating       0               41d
coredns-654c6cf984-ctwsr                                          0/1     Terminating       0               14d
coredns-654c6cf984-cvzfs                                          0/1     Terminating       0               6d10h
coredns-654c6cf984-cxt7v                                          0/1     Terminating       0               4d10h
coredns-654c6cf984-d5689                                          0/1     Terminating       0               37d
coredns-654c6cf984-d9vzg                                          0/1     Terminating       0               3d20h
coredns-654c6cf984-dk9st                                          0/1     Terminating       0               3h58m
coredns-654c6cf984-dw8m2                                          0/1     Terminating       0               9h
coredns-654c6cf984-f6ckj                                          0/1     Terminating       0               14d
coredns-654c6cf984-flzn6                                          0/1     Terminating       0               22d
coredns-654c6cf984-gkbxj                                          0/1     Terminating       0               32h
coredns-654c6cf984-gtn6t                                          0/1     Terminating       0               41d
coredns-654c6cf984-h45ht                                          0/1     Terminating       0               37d
coredns-654c6cf984-h4kw6                                          0/1     Terminating       0               2d8h
coredns-654c6cf984-hzkrv                                          0/1     Terminating       0               41d
coredns-654c6cf984-j5cf6                                          0/1     Terminating       0               2d8h
coredns-654c6cf984-j9zpk                                          0/1     Terminating       0               26d
coredns-654c6cf984-k4db6                                          0/1     Terminating       0               41d
coredns-654c6cf984-kf6pp                                          0/1     Terminating       0               12d
coredns-654c6cf984-kn8rn                                          0/1     Terminating       0               15d
coredns-654c6cf984-lmkkt                                          0/1     Terminating       0               19d
coredns-654c6cf984-lvbcq                                          0/1     Terminating       0               2d15h
coredns-654c6cf984-lwngb                                          0/1     Terminating       0               7d
coredns-654c6cf984-m5bvl                                          0/1     Terminating       0               41d
coredns-654c6cf984-m782p                                          0/1     Terminating       0               19d
coredns-654c6cf984-mlvfg                                          0/1     Terminating       0               7d
coredns-654c6cf984-msbpz                                          0/1     Terminating       0               13d
coredns-654c6cf984-n7cb8                                          0/1     Terminating       0               9d
coredns-654c6cf984-ndlm9                                          0/1     Terminating       0               11d
coredns-654c6cf984-nfxtw                                          0/1     Terminating       0               6d7h
coredns-654c6cf984-njcbp                                          0/1     Terminating       0               27d
coredns-654c6cf984-p2ztz                                          0/1     Terminating       0               8d
coredns-654c6cf984-pd9ql                                          0/1     Terminating       0               37h
coredns-654c6cf984-ptwrl                                          0/1     Terminating       0               12d
coredns-654c6cf984-qdvcs                                          0/1     Terminating       0               3h32m
coredns-654c6cf984-qh7xs                                          0/1     Terminating       0               7d
coredns-654c6cf984-rqt7b                                          0/1     Terminating       0               41d
coredns-654c6cf984-rstxv                                          0/1     Terminating       0               41d
coredns-654c6cf984-s7wpl                                          0/1     Terminating       0               37d
coredns-654c6cf984-s9d4t                                          0/1     Terminating       0               31h
coredns-654c6cf984-smg7r                                          0/1     Terminating       0               7d
coredns-654c6cf984-sxfw6                                          0/1     Terminating       0               6d8h
coredns-654c6cf984-t546p                                          0/1     Terminating       0               10d
coredns-654c6cf984-tjpgn                                          0/1     Terminating       0               14d
coredns-654c6cf984-tp2cz                                          0/1     Terminating       0               26d
coredns-654c6cf984-tqd27                                          0/1     Terminating       0               16d
coredns-654c6cf984-vkxgp                                          0/1     Terminating       0               16d
coredns-654c6cf984-w75ft                                          0/1     Terminating       0               9d
coredns-654c6cf984-wnnwj                                          0/1     Terminating       0               8d
coredns-654c6cf984-x25rh                                          0/1     Terminating       0               6d10h
coredns-654c6cf984-x2q2t                                          0/1     Terminating       0               40d
coredns-654c6cf984-xm9xv                                          0/1     Terminating       0               41d
coredns-654c6cf984-xwrft                                          0/1     Terminating       0               18h
coredns-654c6cf984-zgsg8                                          0/1     Terminating       0               7d
coredns-654c6cf984-zsb44                                          0/1     Terminating       0               27d
coredns-654c6cf984-zxs7q                                          0/1     Terminating       0               4d7h
coredns-8555bc696-227wn                                           0/1     Init:0/1          0               38s
coredns-8555bc696-24c77                                           0/1     Init:0/1          0               40s
coredns-8555bc696-24hlr                                           0/1     Init:0/1          0               42s
coredns-8555bc696-276bs                                           0/1     Init:0/1          0               43s
coredns-8555bc696-2jjvp                                           0/1     Init:0/1          0               39s
coredns-8555bc696-2q256                                           0/1     Init:0/1          0               40s
coredns-8555bc696-2qj6d                                           0/1     Terminating       0               35s
coredns-8555bc696-2xztp                                           0/1     Init:0/1          0               42s
coredns-8555bc696-2z8hv                                           0/1     Init:0/1          0               40s
coredns-8555bc696-4fc4x                                           0/1     Init:0/1          0               38s
coredns-8555bc696-4pjpv                                           0/1     Init:0/1          0               37s
coredns-8555bc696-4pk5m                                           0/1     Init:0/1          0               36s
coredns-8555bc696-5km9d                                           0/1     Init:0/1          0               43s
coredns-8555bc696-5lckq                                           0/1     Init:0/1          0               37s
coredns-8555bc696-5rc7q                                           0/1     Init:0/1          0               41s
coredns-8555bc696-6fplj                                           0/1     Init:0/1          0               42s
coredns-8555bc696-6kkbk                                           0/1     Init:0/1          0               42s
coredns-8555bc696-6lgct                                           0/1     Init:0/1          0               37s
coredns-8555bc696-6rgzr                                           0/1     Init:0/1          0               38s
coredns-8555bc696-6s76z                                           0/1     Init:0/1          0               44s
coredns-8555bc696-6svgp                                           0/1     Init:0/1          0               37s
coredns-8555bc696-6vx5g                                           0/1     Init:0/1          0               40s
coredns-8555bc696-6x7t5                                           0/1     Terminating       0               44s
coredns-8555bc696-7dgtc                                           0/1     Init:0/1          0               43s
coredns-8555bc696-7g4vr                                           0/1     Init:0/1          0               42s
coredns-8555bc696-7j99h                                           0/1     Init:0/1          0               37s
coredns-8555bc696-7lxln                                           0/1     Init:0/1          0               41s
coredns-8555bc696-7vxsc                                           0/1     Init:0/1          0               39s
coredns-8555bc696-85tm6                                           0/1     Init:0/1          0               43s
coredns-8555bc696-8hqp4                                           0/1     Init:0/1          0               41s
coredns-8555bc696-8mdpt                                           0/1     Init:0/1          0               37s
coredns-8555bc696-96ldv                                           0/1     Init:0/1          0               38s
coredns-8555bc696-96ltk                                           0/1     Init:0/1          0               41s
coredns-8555bc696-98bdq                                           0/1     Init:0/1          0               43s
coredns-8555bc696-9t6bd                                           0/1     Init:0/1          0               38s
coredns-8555bc696-b74wd                                           0/1     Init:0/1          0               40s
coredns-8555bc696-b948h                                           0/1     Init:0/1          0               42s
coredns-8555bc696-bbpjf                                           0/1     Init:0/1          0               39s
coredns-8555bc696-bctzt                                           0/1     Init:0/1          0               41s
coredns-8555bc696-c729g                                           0/1     Terminating       0               36s
coredns-8555bc696-cfjsr                                           0/1     Init:0/1          0               44s
coredns-8555bc696-ctxn2                                           0/1     Init:0/1          0               42s
coredns-8555bc696-d4gf2                                           0/1     Init:0/1          0               36s
coredns-8555bc696-d64lc                                           0/1     Init:0/1          0               41s
coredns-8555bc696-dhnb7                                           0/1     Terminating       0               35s
coredns-8555bc696-dkkz5                                           0/1     Init:0/1          0               37s
coredns-8555bc696-dttjw                                           0/1     Init:0/1          0               44s
coredns-8555bc696-dvcz5                                           0/1     Init:0/1          0               37s
coredns-8555bc696-dwj2t                                           0/1     Init:0/1          0               37s
coredns-8555bc696-dztgd                                           0/1     Init:0/1          0               44s
coredns-8555bc696-dzvqm                                           0/1     Init:0/1          0               39s
coredns-8555bc696-f2tvm                                           0/1     Init:0/1          0               44s
coredns-8555bc696-f6cbw                                           0/1     Init:0/1          0               36s
coredns-8555bc696-fblgn                                           0/1     Init:0/1          0               43s
coredns-8555bc696-fclm5                                           0/1     Init:0/1          0               38s
coredns-8555bc696-fkp9t                                           0/1     Init:0/1          0               41s
coredns-8555bc696-gj8kh                                           0/1     Init:0/1          0               42s
coredns-8555bc696-gln8n                                           0/1     Init:0/1          0               38s
coredns-8555bc696-gnpsg                                           0/1     Init:0/1          0               44s
coredns-8555bc696-gtt5b                                           0/1     Init:0/1          0               38s
coredns-8555bc696-gtwfv                                           0/1     Init:0/1          0               36s
coredns-8555bc696-h5zcj                                           0/1     Init:0/1          0               37s
coredns-8555bc696-hhh7f                                           0/1     Init:0/1          0               41s
coredns-8555bc696-hs8hj                                           0/1     Init:0/1          0               38s
coredns-8555bc696-hx99x                                           0/1     Init:0/1          0               37s
coredns-8555bc696-jqppq                                           0/1     Init:0/1          0               43s
coredns-8555bc696-jrbcd                                           0/1     Init:0/1          0               40s
coredns-8555bc696-jrc62                                           0/1     Terminating       0               44s
coredns-8555bc696-jx9mn                                           0/1     Terminating       0               35s
coredns-8555bc696-jzbcb                                           0/1     Init:0/1          0               38s
coredns-8555bc696-k96xv                                           0/1     Init:0/1          0               38s
coredns-8555bc696-khllm                                           0/1     Init:0/1          0               43s
coredns-8555bc696-kvjsm                                           0/1     Init:0/1          0               38s
coredns-8555bc696-kwshz                                           0/1     Init:0/1          0               37s
coredns-8555bc696-l5hq7                                           0/1     Init:0/1          0               37s
coredns-8555bc696-ld6gj                                           0/1     Init:0/1          0               38s
coredns-8555bc696-ldlmc                                           0/1     Init:0/1          0               42s
coredns-8555bc696-ltcbc                                           0/1     Init:0/1          0               39s
coredns-8555bc696-m2d9c                                           0/1     Init:0/1          0               43s
coredns-8555bc696-m4d2m                                           0/1     Terminating       0               44s
coredns-8555bc696-m4mt8                                           0/1     Init:0/1          0               38s
coredns-8555bc696-mjpcs                                           0/1     Init:0/1          0               37s
coredns-8555bc696-mndqz                                           0/1     Init:0/1          0               43s
coredns-8555bc696-mp9j4                                           0/1     Init:0/1          0               43s
coredns-8555bc696-mspcq                                           0/1     Init:0/1          0               41s
coredns-8555bc696-mtrzz                                           0/1     Init:0/1          0               37s
coredns-8555bc696-n4fbq                                           0/1     Init:0/1          0               38s
coredns-8555bc696-nk4pp                                           0/1     Init:0/1          0               38s
coredns-8555bc696-nnhh8                                           0/1     Init:0/1          0               39s
coredns-8555bc696-ns2q9                                           0/1     Init:0/1          0               37s
coredns-8555bc696-nwgcx                                           0/1     Init:0/1          0               36s
coredns-8555bc696-p76mq                                           0/1     Terminating       0               44s
coredns-8555bc696-p7w5g                                           0/1     Init:0/1          0               39s
coredns-8555bc696-pbgr2                                           0/1     Init:0/1          0               41s
coredns-8555bc696-pbz54                                           0/1     Init:0/1          0               40s
coredns-8555bc696-pdwx7                                           0/1     Init:0/1          0               39s
coredns-8555bc696-pltkr                                           0/1     Init:0/1          0               38s
coredns-8555bc696-pwlhz                                           0/1     Init:0/1          0               39s
coredns-8555bc696-qcc5w                                           0/1     Init:0/1          0               43s
coredns-8555bc696-qfddt                                           0/1     Init:0/1          0               36s
coredns-8555bc696-qk79r                                           0/1     Init:0/1          0               39s
coredns-8555bc696-ql7pq                                           0/1     Init:0/1          0               39s
coredns-8555bc696-r4kr7                                           0/1     Init:0/1          0               39s
coredns-8555bc696-r8mwq                                           0/1     Init:0/1          0               39s
coredns-8555bc696-rbxvv                                           0/1     Init:0/1          0               43s
coredns-8555bc696-rhxgk                                           0/1     Init:0/1          0               42s
coredns-8555bc696-rpxng                                           0/1     Init:0/1          0               42s
coredns-8555bc696-rrv4c                                           0/1     Init:0/1          0               42s
coredns-8555bc696-s4xpj                                           0/1     Init:0/1          0               42s
coredns-8555bc696-s57hv                                           0/1     Init:0/1          0               42s
coredns-8555bc696-s9cqn                                           0/1     Init:0/1          0               38s
coredns-8555bc696-sd6jp                                           0/1     Init:0/1          0               42s
coredns-8555bc696-sh6xb                                           0/1     Init:0/1          0               40s
coredns-8555bc696-shn4f                                           0/1     Init:0/1          0               38s
coredns-8555bc696-sk7hv                                           0/1     Init:0/1          0               41s
coredns-8555bc696-smmvh                                           0/1     Init:0/1          0               43s
coredns-8555bc696-sslmd                                           0/1     Init:0/1          0               39s
coredns-8555bc696-t5vwz                                           0/1     Init:0/1          0               39s
coredns-8555bc696-t7xhx                                           0/1     Init:0/1          0               39s
coredns-8555bc696-tdm6p                                           0/1     Terminating       0               36s
coredns-8555bc696-tx7rj                                           0/1     Init:0/1          0               40s
coredns-8555bc696-v5thr                                           0/1     Init:0/1          0               36s
coredns-8555bc696-v6rnn                                           0/1     Init:0/1          0               43s
coredns-8555bc696-vfpkk                                           0/1     Init:0/1          0               43s
coredns-8555bc696-vrgv7                                           0/1     Init:0/1          0               46s
coredns-8555bc696-vwqsj                                           0/1     Init:0/1          0               43s
coredns-8555bc696-w8cmw                                           0/1     Init:0/1          0               42s
coredns-8555bc696-wfgk2                                           0/1     Init:0/1          0               40s
coredns-8555bc696-wkj4f                                           0/1     Init:0/1          0               38s
coredns-8555bc696-wvjv2                                           0/1     Terminating       0               36s
coredns-8555bc696-xkv7q                                           0/1     Init:0/1          0               43s
coredns-8555bc696-xzth4                                           0/1     Init:0/1          0               36s
coredns-8555bc696-z898x                                           0/1     Init:0/1          0               36s
coredns-8555bc696-z8qg7                                           0/1     Init:0/1          0               38s
coredns-8555bc696-z9fbl                                           0/1     Terminating       0               35s
coredns-8555bc696-zbgpg                                           0/1     Init:0/1          0               36s
coredns-8555bc696-zdtkn                                           0/1     Init:0/1          0               39s
coredns-8555bc696-zk5sl                                           0/1     Init:0/1          0               44s
coredns-8555bc696-znkt9                                           0/1     Init:0/1          0               42s
coredns-8555bc696-zrrnd                                           0/1     Init:0/1          0               41s
coredns-autoscaler-546d98f96c-g8mpk                               1/1     Running           0               3d8h
coredns-autoscaler-6cf8bf6b89-dl8kw                               0/1     Running           0               46s
```
</details>
**Additional context**

**Comment by orz-nil** [comment] 2023-12-27 02:22
This change has already been applied in coredns.go
https://github.com/rancher/kontainer-driver-metadata/pull/83

but it is back in the new template file
https://github.com/rancher/kontainer-driver-metadata/pull/552/files#diff-d1fe5e14eae7a6cf7b8255243f32fe6945de755286f0b7b70ee50b0e13d56724R96
all new versions which ">=1.21.9-rancher1-2" used this template. 
please drop this line again.

**Comment by orz-nil** [comment] 2024-02-26 09:36
pls remove this [`replicas`](https://github.com/rancher/kontainer-driver-metadata/blob/release-v2.8/pkg/rke/templates/coredns_v1.8.3.go#L96
). This makes cluster upgrades very painful

**Comment by orz-nil** [comment] 2024-03-04 09:21
add: there are some deprecated things in the template( both in deploy `coredns` and `coredns-autoscaler`). maybe we can change them at the same time.
```
Warning: spec.template.spec.nodeSelector[beta.kubernetes.io/os]: deprecated since v1.14; use "kubernetes.io/os" instead
Warning: spec.template.metadata.annotations[seccomp.security.alpha.kubernetes.io/pod]: deprecated since v1.19, non-functional in a future release; use the "seccompProfile" field instead
```

**Comment by jiaqiluo** [comment] 2024-03-05 21:26
For the reference, below is how K8s supports the `Seccomp` feature:

In clusters whose k8s version is < 1.19, the seccomp annotation is used to set the seccomp profile. The annotation `seccomp.security.alpha.kubernetes.io/pod`, which is used in the `coredns` deployment, sets the seccomp profile for the containers of an entire pod.  ([Original seccomp proposal](https://github.com/kubernetes/design-proposals-archive/blob/master/node/seccomp.md)) 

In clusters whose k8s version is  >= 1.19 and < 1.27, the seccomp support is graduated to GA with the annotation being deprecated, and a pod version skew strategy is added to synchronize the deprecated annotations with the new API Server fields.  ( [KEP](https://github.com/kubernetes/enhancements/blob/master/keps/sig-node/135-seccomp/README.md) , [PR1](https://github.com/kubernetes/kubernetes/pull/91408) and [PR2](https://github.com/kubernetes/kubernetes/issues/91286) )

In our case, the annotation `seccomp.security.alpha.kubernetes.io/pod: docker/default` is synced to the Pod's `securityContext` field
```
apiVersion: v1
kind: Pod
metadata:
  annotations:
    seccomp.security.alpha.kubernetes.io/pod: docker/default
Spec:
  securityContext:
    seccompProfile:
      type: RuntimeDefault
```

In clusters whose k8s version is  >= 1.27, the seccomp annotations are marked as non-functional. [PR](https://github.com/kubernetes/kubernetes/pull/114947)

**Comment by snasovich** [comment] 2024-04-08 18:05
This is now planned to go out together with https://github.com/rancher/rancher/issues/45041

**Comment by orz-nil** [comment] 2024-04-18 06:52
Thank you very much, waiting for version 1.27.13 to be released.

**Comment by vivek-shilimkar** [comment] 2024-04-24 12:40
Tested the issue on rancher v2.8. After k8s version upgrade the cluster is stable and the issue is fixed. Hence closing the issue.

**Closed by vivek-shilimkar** 2024-04-24 12:40 UTC
Labels: kind/bug, area/rke, QA/S, area/upgrade, team/hostbusters, team/infracloud, area/kdm, feature/kdm
