### ISSUE TITLE
User login timeout after restoring etcd snapshot on downstream RKE1 cluster

### ISSUE THREAD

**Issue by timhaneunsoo** [rancher/rancher#36786] opened 2022-03-07 22:07 UTC
**Rancher Server Setup**
- Rancher version: v2.6.3-patch2-rc2
- Installation option (Docker install/Helm Chart):
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): RKE 1.3.7
- Proxy/Cert Details:

**Information about the Cluster**
- Kubernetes version:
- Cluster Type (Local/Downstream): local HA
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider):

**User Information**
- What is the role of the user logged in? (Admin/Cluster Owner/Cluster Member/Project Owner/Project Member/Custom)
  - If custom, define the set of permissions: Admin and Standard User

   
**Describe the bug**

After restoring an etcd snapshot of RKE1 aws node driver cluster, and then deleting a manual snapshot user is logged out and and is instantly logged out when logging back in. Currently unsure of actual point of error because the first time, the user got logged out instantly, but on a second Rancher server it happened after a couple hours (2-3 hours). The standard user got logged out first and admin was able to log in. When trying to click on the cluster created by the standard user, then admin was also logged out.

**To Reproduce**
 
1. Deploy local HA Rancher using RKE 1.3.7
2. Create RKE aws node driver cluster
3. Create a manual snapshot of cluster
4. Create any workload
5. Create another manual snapshot of cluster
6. Restore first manual snapshot
7. After restore, delete the saved snapshot

**Result**
After those steps I faced the issue, first time was immediately after, second time was a couple hours after.
**Expected Result**

User should not be immediately logged out and able to use Rancher as expected.

**Screenshots**

**Additional context**

The error in the kube-apiserver log was
```
E0307 21:25:57.984207       1 status.go:71] apiserver received an error that is not an metav1.Status: &errors.errorString{s:"context canceled"}: context canceled
E0307 21:25:57.984525       1 writers.go:117] apiserver was unable to write a JSON response: http: Handler timeout
E0307 21:25:57.985764       1 status.go:71] apiserver received an error that is not an metav1.Status: &errors.errorString{s:"http: Handler timeout"}: http: Handler timeout
E0307 21:25:57.986898       1 writers.go:130] apiserver was unable to write a fallback JSON response: http: Handler timeout
E0307 21:25:57.988282       1 timeout.go:135] post-timeout activity - time-elapsed: 3.758505ms, GET "/apis/management.cattle.io/v3/namespaces/user-2ng4g/preferences" result: <nil>
```

The kubelet log showed
```
E0307 18:49:24.944882    5214 configmap.go:200] Couldn't get configMap cattle-system/impersonation-helm-op-user-kubeconfig-n89bl: object "cattle-system"/"impersonation-helm-op-user-kubeconfig-n89bl" not registered
E0307 18:49:24.944933    5214 secret.go:195] Couldn't get secret cattle-system/helm-operation-pswmf: object "cattle-system"/"helm-operation-pswmf" not registered
E0307 18:49:24.944990    5214 secret.go:195] Couldn't get secret cattle-system/pod-impersonation-helm-op-pj656-token-8qdr2: object "cattle-system"/"pod-impersonation-helm-op-pj656-token-8qdr2" not registered
E0307 18:49:24.944882    5214 configmap.go:200] Couldn't get configMap cattle-system/impersonation-helm-op-admin-kubeconfig-bcvrb: object "cattle-system"/"impersonation-helm-op-admin-kubeconfig-bcvrb" not registered
E0307 18:49:24.945201    5214 nestedpendingoperations.go:335] Operation for "{volumeName:kubernetes.io/configmap/08cadfbe-ad7e-4ee3-9583-139e37b57945-user-kubeconfig podName:08cadfbe-ad7e-4ee3-9583-139e37b57945 nodeName:}" failed. No retries permitted until 2022-03-07 18:49:25.945168711 +0000 UTC m=+296.092849135 (durationBeforeRetry 1s). Error: MountVolume.SetUp failed for volume "user-kubeconfig" (UniqueName: "kubernetes.io/configmap/08cadfbe-ad7e-4ee3-9583-139e37b57945-user-kubeconfig") pod "helm-operation-2w9z5" (UID: "08cadfbe-ad7e-4ee3-9583-139e37b57945") : object "cattle-system"/"impersonation-helm-op-user-kubeconfig-n89bl" not registered
E0307 18:49:24.945567    5214 nestedpendingoperations.go:335] Operation for "{volumeName:kubernetes.io/secret/08cadfbe-ad7e-4ee3-9583-139e37b57945-data podName:08cadfbe-ad7e-4ee3-9583-139e37b57945 nodeName:}" failed. No retries permitted until 2022-03-07 18:49:25.945544784 +0000 UTC m=+296.093225193 (durationBeforeRetry 1s). Error: MountVolume.SetUp failed for volume "data" (UniqueName: "kubernetes.io/secret/08cadfbe-ad7e-4ee3-9583-139e37b57945-data") pod "helm-operation-2w9z5" (UID: "08cadfbe-ad7e-4ee3-9583-139e37b57945") : object "cattle-system"/"helm-operation-pswmf" not registered
E0307 18:49:24.945652    5214 nestedpendingoperations.go:335] Operation for "{volumeName:kubernetes.io/secret/08cadfbe-ad7e-4ee3-9583-139e37b57945-pod-impersonation-helm-op-pj656-token-8qdr2 podName:08cadfbe-ad7e-4ee3-9583-139e37b57945 nodeName:}" failed. No retries permitted until 2022-03-07 18:49:25.94563349 +0000 UTC m=+296.093313902 (durationBeforeRetry 1s). Error: MountVolume.SetUp failed for volume "pod-impersonation-helm-op-pj656-token-8qdr2" (UniqueName: "kubernetes.io/secret/08cadfbe-ad7e-4ee3-9583-139e37b57945-pod-impersonation-helm-op-pj656-token-8qdr2") pod "helm-operation-2w9z5" (UID: "08cadfbe-ad7e-4ee3-9583-139e37b57945") : object "cattle-system"/"pod-impersonation-helm-op-pj656-token-8qdr2" not registered
E0307 18:49:24.945717    5214 nestedpendingoperations.go:335] Operation for "{volumeName:kubernetes.io/configmap/08cadfbe-ad7e-4ee3-9583-139e37b57945-admin-kubeconfig podName:08cadfbe-ad7e-4ee3-9583-139e37b57945 nodeName:}" failed. No retries permitted until 2022-03-07 18:49:25.94570174 +0000 UTC m=+296.093382152 (durationBeforeRetry 1s). Error: MountVolume.SetUp failed for volume "admin-kubeconfig" (UniqueName: "kubernetes.io/configmap/08cadfbe-ad7e-4ee3-9583-139e37b57945-admin-kubeconfig") pod "helm-operation-2w9z5" (UID: "08cadfbe-ad7e-4ee3-9583-139e37b57945") : object "cattle-system"/"impersonation-helm-op-admin-kubeconfig-bcvrb" not registered
```

**Comment by snasovich** [comment] 2022-05-18 19:18
Putting it into @jakefhyde 's queue to try to reproduce and understand the root cause of it.
This is a lower priority as the issue is intermittent and definitely not something that started happening due to changes in `v2.6.3-patch2`, so the release-blocker is removed and the milestone is set as 2.6.x.

**Comment by snasovich** [comment] 2023-01-05 21:47
@slickwarren @timhaneunsoo , was this observed again by you or anyone else on QA team recently?

**Comment by slickwarren** [comment] 2023-01-06 19:11
I have not seen this again, but will leave to @timhaneunsoo to close it

**Comment by jakefhyde** [comment] 2023-01-18 23:53
@thaneunsoo Can you verify if this is still an issue?

**Comment by thaneunsoo** [comment] 2023-01-20 17:07
I tested this on v2.7-head f2bde24 and I am also not able to reproduce this anymore. Will be closing this issue for now as no one is seeing this issue and will keep and eye out for this issue if it ever comes back.

**Closed by thaneunsoo** 2023-01-20 17:07 UTC
Labels: priority/2, kind/bug-qa, [zube]: QA Working, QA/XS, team/area2
