### ISSUE TITLE
Request to index.yaml on git.rancher.io fails with AirGap usage

### ISSUE THREAD

**Issue by sharksforarms** [rancher/rancher#14070] opened 2018-06-19 17:16 UTC
**Rancher versions:**
rancher/server or rancher/rancher: v2.0.0
rancher/agent or rancher/rancher-agent: v2.0.0

**Infrastructure Stack versions:**
healthcheck:
ipsec:
network-services:
scheduler:
kubernetes (if applicable):

**Docker version: (`docker version`,`docker info` preferred)**
Version 18.03.1-ce

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
CentOS7

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
Single node rancher

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**

**Steps to Reproduce:**
Install using AirGap instructions, goto Add Cluster and see logs on `rancher/rancher`

**Results:**
`E0619 1 generic_controller.go:204] CatalogController library [catalog] failed with : Get https://git.rancher.io/charts/index.yaml: dial tcp: lookup git.rancher.io on ... i/o timeout`

This is an air gaped system so it doesn't have access to git.rancher.io

**Comment by superseb** [comment] 2018-06-20 20:55
Duplicate of https://github.com/rancher/rancher/issues/13700

**Closed by superseb** 2018-06-20 20:55 UTC
