### ISSUE TITLE
UI unable to launch project level app with custom rancher versions

### ISSUE THREAD

**Issue by dramich** [rancher/rancher#21008] opened 2019-06-20 16:04 UTC
When using a project level catalog, if a template has a defaultVersion but that version is not available in the versionLinks due to the rancher version not supporting it, clicking `view details` on the app will cause the UI will go back to the apps page instead of showing details of the app to launch. 

Based off feedback from Wes, the UI is not handing back an error in this case and is not properly handling if the defaultVersion does not exist in the versionLinks. 

This does work at the global level but the UI will not auto select a version if the defaultVersion does not exist. 

This was found during testing of [this](https://github.com/rancher/rancher/pull/19630). In order to repro use [this](https://github.com/rancher/integration-test-charts) catalog which has the required `rancher_min_version` and `rancher_max_version` set. The rancher server version must also be set to a valid version, such as v2.3.0.

**Comment by sowmyav27** [comment] 2019-07-23 23:04
closing this as a duplicate of https://github.com/rancher/rancher/issues/21634

**Closed by sowmyav27** 2019-07-23 23:04 UTC
Labels: [zube]: To Test, area/ui, kind/bug, priority/0, status/blocker, team/ui
