### ISSUE TITLE
RKE2 version is not displaying it is an RC for imported clusters

### ISSUE THREAD

**Issue by slickwarren** [rancher/rancher#34470] opened 2021-08-25 21:45 UTC
**Rancher Server Setup**
- Rancher version:v2.6-head (b7c440b)
- Installation option (Docker install/Helm Chart):docker
   - If Helm Chart, Kubernetes Info:
         Cluster Type (RKE1, RKE2, k3s, EKS, etc):rke2
         Node Setup:
         Version:v1.21.4-rc1+rke2r1
- Proxy/Cert Details:

**Information about the Cluster**
- Kubernetes version:v1.21.4-rc1+rke2r1
- Cluster Type (Local/Downstream):downstream and local
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider):imported

**Describe the bug**

when using an RC k8s version with rke2, the version is showing as a release version instead through the UI

**To Reproduce**
 
* setup a cluster using rke2, with v1.21.4-rc1+rke2r1 and install rancher onto it

* alternatively, setup rancher on a docker install
* setup an rke2 cluster using v1.21.4-rc1+rke2r1 and import it into rancher

**Result**
the version for these clusters shows up as v1.21.4+rke2r1

**Expected Result**

the rke2 version should display

**Screenshots**

<img width="679" alt="Screen Shot 2021-08-25 at 1 53 30 PM" src="https://user-images.githubusercontent.com/16691014/130868686-a00a04ed-48a5-47b2-ae7a-861bab344f77.png">

**Additional context**

* from Max: 
```
Looks like in my local cluster, it has spec.rke2Config.kubernetesVersion: v1.21.4+rke2r1, which is not showing in the api actually only with Edit Yaml, and in the other one showing rc version it has (in both api and through Edit Yaml): spec.kubernetesVersion: v1.21.4-rc1+rke2r1.

The rke2 version is v1.21.4-rc1+rke2r1, but the kubernetes version should always be v1.21.4+rke2r1.
```

**Comment by snasovich** [comment] 2021-09-21 18:18
@deniseschannon , based on your comment above, can this be closed as "Functions as Designed", especially since RC versions are not going to be referenced in release KDM versions?

**Comment by deniseschannon** [comment] 2021-09-23 04:38
Agreed, I don't believe this would end up in a problem for our end users as we would allow provide non-RC versions in a KDM release.

**Closed by deniseschannon** 2021-09-23 04:38 UTC
Labels: kind/bug-qa, [zube]: To Triage, area/import-rke2, dependency-rke2
