### ISSUE TITLE
Cloning of LB services created from API fails

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#1973] opened 2015-09-04 17:22 UTC
Sever version - Build from master - Sep 4

Had a LB service with ssl enabled listener and certs.

<img width="858" alt="screen shot 2015-09-04 at 10 21 11 am" src="https://cloud.githubusercontent.com/assets/4266958/9690033/c93949c2-52ee-11e5-88ad-2ff3eb3ce4f0.png">

Tried to clone this LB service . I get redirected to /static/fail page with following contents:

Error
Cannot read property 'set' of null
Reload to try again or log out

**Comment by vincent99** [comment] 2015-09-08 21:32
works for me... can I see this one somewhere?

**Comment by sangeethah** [comment] 2015-09-08 23:57
This issue is not reproducible when LB instance is created using UI.
I am able to see this issue when

**Comment by deniseschannon** [comment] 2015-09-22 16:57
@vincent99 Can you look at #2059 because I believe it's the same issue but his use case is simpler. Basically, any LB created using API seems to fail when cloning. 

This is probably a duplicate of https://github.com/rancher/rancher/issues/1700 that we ended up closing cause we couldn't reproduce.

**Comment by vincent99** [comment] 2015-10-08 17:00
This was caused by balancers created with rancher-compose not having a `loadBalancerConfig` object in them (for stickiness options and such).

**Comment by deniseschannon** [comment] 2015-10-09 20:13
Verified in v0.41.0-rc1 using rancher-compose to create a LB. Cloning the LB has no issue.

**Closed by deniseschannon** 2015-10-09 20:13 UTC
Labels: area/ui, kind/bug, status/resolved, status/to-test
