### ISSUE TITLE
[v2.0.6] Validation failed in API: PersistentVolume is invalid

### ISSUE THREAD

**Issue by mostworld77** [rancher/rancher#14776] opened 2018-07-26 11:23 UTC
rancher: 2.0.6
Docker version 1.13.1
Fresh installed on Centos 7.5

----
Steps to Reproduce:
----
Rancher->Storage->Add Persistent Volume:

Name: **rancher-volume**
Capacity: **10 GiB**
Volume Plugin: **Local Node Disk**
Path: **/opt/rancher-volume**
Access Modes: **Single Node Read-Write**

----
Results:
----
Validation failed in API: PersistentVolume "rancher-volume" is invalid: metadata.annotations: Required value: Local volume requires node affinity

**Comment by superseb** [comment] 2018-07-26 11:32
Duplicate of https://github.com/rancher/rancher/issues/13864

**Closed by superseb** 2018-07-26 11:32 UTC
