### ISSUE TITLE
preview: can't change password for current user

### ISSUE THREAD

**Issue by utrack** [rancher/rancher#12652] opened 2018-04-12 05:47 UTC
**Rancher versions:**
rancher/server: v2.0.0-beta1
rancher/agent: ---

**Steps to Reproduce:**
Go to User -> Settings -> Change password, try to change password

**Results:**
Server Error
`json: cannot unmarshal string into Go struct field User.me of type bool`

**Comment by tfiduccia** [comment] 2018-04-12 06:11
Version - 2.0 master 4/11
I can't reproduce this error in v2.0.0-beta1.  Are you logged in as admin or as a local user?  
Also to change password you should be going to preferences or editing the user.  Which way are you trying?

**Comment by utrack** [comment] 2018-04-12 06:56
I'm using a `preview` tag from Docker when installing Rancher - it reports itself as b1 that came out some days ago (?), so my version can be a little bit older.
I'm logged in as a default `admin` user.

Editing the user via Users fails silently - no errors, but the password is unchanged.
I get an unmarshalling error when editing myself through preferences.

**Comment by superseb** [comment] 2018-04-12 07:14
Sounds like a duplicate of https://github.com/rancher/rancher/issues/12550, can you verify if the workaround solves your issue?

**Closed by superseb** 2018-04-12 07:14 UTC
