### ISSUE TITLE
Support catalog visibility per environment

### ISSUE THREAD

**Issue by will-chan** [rancher/rancher#3158] opened 2015-12-31 01:17 UTC
Support ability to control catalog item visibility per environment.

**Comment by sshipway** [comment] 2016-01-18 04:27
+1

Catalogues should be enabled per-Environment and not globally.  This allows use to have a 'stable' catalogue for our production environments, and an unsupported catalogue for others -- even a catalogue for just a single team's environments.  Otherwise, we cannot devolve administration of catalogue items to separate groups without potentially causing chaos in our production environments.

**Comment by demarant** [comment] 2016-01-18 13:35
+1
@sshipway, @will-chan  I even think Stack versions should be enabled/disabled per environment. You can have a Stack version v1.0-rc1 which is deployable only on Development and Test environment and than once the v1.0 is realeased it should be possible to have it deployable on all environments. A Catalog by itself may contains a mix of release candidates and stable version  of the same Stack, therefore I don't think only the entire Catalog would be enough. Basically once a Stack as a new version, an admin would need to enable for the specific environments. By default Stack would be disabled...

**Comment by vincent99** [comment] 2016-01-18 18:04
@demarant. I don't see any reason to involve Rancher in that..  Catalogs are git repos for a reason, and you already have restrictions on who can change them.  If you want different versions, just keep 2 or more repos/branches and promote by merging between them.

**Comment by demarant** [comment] 2016-01-18 19:47
@vincent99
Good point, i guess that should work

**Comment by sshipway** [comment] 2016-01-18 20:32
Or, how about Catalogue items being able to specify Branch?  Thus, your Prod environment would include your Catalogue repo Master branch, and your Dev environment would use the Development branch...

**Comment by tfiduccia** [comment] 2017-03-02 17:58
Version - v1.5.0-rc2 - Regression completed.  Need UI to support multiple environments.

**Comment by cjellick** [comment] 2017-05-17 16:56
Determined with @deniseschannon  that this is a dupe of #8702, but will leave open for now so that @tfiduccia @amy @deniseschannon can see and decide how to handle.

**Comment by tfiduccia** [comment] 2017-05-17 17:37
Version - master 5/17
Verified feature added - I'm going to close this one in favor of #8702.  Plus it's implemented and any issues will be entered separately.

**Closed by tfiduccia** 2017-05-17 17:37 UTC
Labels: area/catalog, area/ui, kind/feature, release/1.6.x, status/to-test
