### ISSUE TITLE
Support for Docker 1.10 under CoreOS

### ISSUE THREAD

**Issue by sshipway** [rancher/rancher#4238] opened 2016-03-31 03:41 UTC
Rancher Version: 1.0

Docker Version: 1.10.x

OS: CoreOS

Steps to Reproduce:  Create several Hosts using Docker 1.10.x.  Let them run for a while.

Results:  Some Host states will become 'Reconnecting' and will need to have the agent restarted before they become 'Active'.

Expected: Hosts remaining Active

Is Docker 1.10.x supported by Rancher?  Currently, it seems to cause random networking issues, relating to load balancers and rancher-agent, resulting in Hosts being permanently 'Reconnecting' and load balancers sometimes being stuck in 'Initialising'.  CoreOS stable uses Docker 1.9.1 but Beta and ALpha are on 1.10.3.

**Comment by vincent99** [comment] 2016-03-31 03:46
1.10 is supported, and in fact Add Hosts screen now defaults to explicitly installing 1.10.x so that everyone doesn't start installing 1.11 the second it's released.

So we've been using it for all the 1.0 QA, and I don't think that (by itself, anyway) is the issue.

**Comment by sshipway** [comment] 2016-03-31 04:04
Maybe the issue is specific to CoreOS+1.10?  There have been CoreOS-specific issues in the past.  CoreOS also has the irritating habit of auto-updating itself and rebooting, unless you turn it off.

**Comment by thaJeztah** [comment] 2016-03-31 04:11
I've seen some issues from CoreOS; one was related to CoreOS hard-coding the IP address of the bridge, which can actually change IP address. Also, they build their own Docker packages with some modifications, and (IIRC) at some point used a version of Go to compile Docker that was known to cause issues in a networking library used by Docker.

If you have more information, or a way to reproduce, I suggest to report your issue at CoreOS

**Comment by sshipway** [comment] 2016-03-31 04:20
Sadly I can't reproduce at will, and it seems to be the combination of Rancher with CoreOS.  Now that CoreOS use Docker 1.9.1 in their stable branch, I'm sticking to Stable - this is probably one of the reasons that the beta branch is still beta.

However, since so many people use CoreOS, it is probably something that Rancher should bear in mind when doing testing.

**Comment by ibuildthecloud** [comment] 2016-03-31 04:40
@sshipway I've seen this issue and it is specific to CoreOS.  Testing of 1.0 on CoreOS beta did not go well.  We will investigate, but tbh CoreOS is a second tier in terms of priority.  First is RHEL, Ubuntu, and RancherOS.  Not that we have anything against CoreOS but we've had one major issue in that CoreOS stable is never running the version of Docker we prefer.  Right now we focus support on Docker 1.10.3.  This is largely due to performance issues seen in 1.9.  But the odd thing is that 1.10 in CoreOS performed horribly for us which makes me suspect they've done something different with their docker.

**Comment by deniseschannon** [comment] 2016-03-31 18:40
Related Forums Post: https://forums.rancher.com/t/rancher-v1-0-0-cross-host-networking-fails/2231/5

**Comment by sshipway** [comment] 2016-04-01 00:43
Further investigation shows that couple of my CoreOS hosts were still using the Rancher agent v0.8.3 instead of the latest 0.11.0.  This may also have been part of the issue (though I'm not sure why they were not automatically upgraded by Rancher?)

**Comment by deniseschannon** [comment] 2016-04-04 17:40
@sshipway That is strange that they weren't automatically upgraded, as they should have been. 

Side note: I did some testing with CoreOS and Docker 1.10.3 (fresh install with v1.0.0) and had no issues with networking, but when I did the same kind of tests on CoreOS and Docker 1.9.1 (also fresh install with v1.0.0), I had all kinds of networking issues. 

I haven't tried with an upgraded setup. Do you only have CoreOS hosts in your environment or any other providers?

**Comment by vincent99** [comment] 2016-04-04 18:21
The agent container's *image* is not automatically updated.  The *code running inside* the agent container **is**.  Replacing itself with a new container/different tag rather problematic if anything goes wrong.

**Comment by deniseschannon** [comment] 2016-04-04 18:49
Also, to confirm, @sshipway you are talking about `rancher/agent` containers, correct?

**Comment by sshipway** [comment] 2016-04-04 21:48
Yes, rancher/agent containers.  It's good to know that the internal code is upgraded even though the 'docker ps' still shows the older image name; this also means that using an older image is not a problem as it will be (presumably) upgraded automatically to the latest version anyway.

I have completely rebuilt my setup with the latest 'stable' coreos OVAs (which run Docker 1.9.1) and now I'm getting the network issues again -- hosts stuck in 'reconnecting' until I restart the agent, load balancers stuck in 'initialising', and so on.

Which CoreOS version are you using in test?  If I know the version used for testing I can make sure to use it here.

I don't know if it is connected, but I see a lot of cadvisor errors in the rancher-agent logs.
````
2016-04-03 23:46:17,486 ERROR agent [139775182212144] [event.py:112] Error in request : ba5a8e26-d935-4f5e-ae63-9fb7f75cebc7
Traceback (most recent call last):
  File "/var/lib/cattle/pyagent/cattle/agent/event.py", line 95, in _worker_main
    resp = agent.execute(req)
  File "/var/lib/cattle/pyagent/cattle/agent/__init__.py", line 15, in execute
    return self._router.route(req)
  File "/var/lib/cattle/pyagent/cattle/plugins/core/event_router.py", line 13, in route
    resp = handler.execute(req)
  File "/var/lib/cattle/pyagent/cattle/plugins/core/event_handlers.py", line 32, in execute
    type.on_ping(event, resp)
  File "/var/lib/cattle/pyagent/cattle/plugins/docker/compute.py", line 126, in on_ping
    self._add_instances(ping, pong)
  File "/var/lib/cattle/pyagent/cattle/plugins/docker/compute.py", line 138, in _add_instances
    running, nonrunning = self._get_all_containers_by_state()
  File "/var/lib/cattle/pyagent/cattle/plugins/docker/compute.py", line 171, in _get_all_containers_by_state
    for c in client.containers(all=True):
  File "/var/lib/cattle/pyagent/dist/docker/api/container.py", line 69, in containers
    res = self._result(self._get(u, params=params), True)
  File "/var/lib/cattle/pyagent/dist/docker/utils/decorators.py", line 47, in inner
    return f(self, *args, **kwargs)
  File "/var/lib/cattle/pyagent/dist/docker/client.py", line 112, in _get
    return self.get(url, **self._set_request_timeout(kwargs))
  File "/var/lib/cattle/pyagent/dist/requests/sessions.py", line 480, in get
    return self.request('GET', url, **kwargs)
  File "/var/lib/cattle/pyagent/dist/requests/sessions.py", line 468, in request
    resp = self.send(prep, **send_kwargs)
  File "/var/lib/cattle/pyagent/dist/requests/sessions.py", line 576, in send
    r = adapter.send(request, **kwargs)
  File "/var/lib/cattle/pyagent/dist/requests/adapters.py", line 449, in send
    raise ReadTimeout(e, request=request)
ReadTimeout: UnixHTTPConnectionPool(host='localhost', port=None): Read timed out. (read timeout=2)
````

**Comment by deniseschannon** [comment] 2016-04-05 16:55
@sshipway The rancher/agent need to be upgraded to the latest version, but the rancher/agent-instances do not need to be.

Can you re-run the registration agent on the hosts that are still running the old version of the rancher/agent?

We have done our testing with Docker 1.10.3, which is CoreOS Alpha, as we always test with the latest version of Docker. I haven't seen any issues with our tests with that version.

**Comment by sshipway** [comment] 2016-04-06 01:18
Re-running the registration agent correctly loaded the latest version; however I've since removed all the VMs and restarted from scratch.
For testing purposes, I had some CoreOS hosts and some RancherOS hosts in the cluster; when I removed the RancherOS ones then the CoreOS hosts stopped dropping out into 'reconnecting' state, though this may have only been coincidence.
I have also noticed in some cases CoreOS generates a lot of coredumps in the root fs which hits 100% and this causes odd behaviour, but I think this is a symptom rather than a cause

**Comment by hwinkel** [comment] 2016-04-16 09:23
just fyi: I'm running now 7 CoreOS alpha 1010.1.0 hosts with docker 1.10.3 and have no network issues. Also GlusterFS is deployed and operates over different datacenter (private and DO) We have about 200 Mbit/s throughput with large 1GB test files over the IPsec Overlay. So far network related features running as expected (LB etc) but the Network setup is not very sophisticated yet. 

For maintenance reasons we will focus on Host OS like CoreOS or rancherOS (and waiting for 0.44) Maintaining the underlaying RHELs and Ubuntus feels like herding pets.

**Comment by deniseschannon** [comment] 2016-04-18 06:23
@hwinkel FYI, RancherOS 0.4.4 has been released, but we haven't done any official announcements.

**Comment by deniseschannon** [comment] 2016-06-16 22:43
With a v1.1.0-dev4 setup, I tested with CoreOS stable (1010.5.0) and ran our validation tests. None of the hosts went into reconnecting. Previous versions would have gone into reconnecting.

Closing this for now. @sshipway If you see further issues, please open a new ticket.

**Closed by deniseschannon** 2016-06-16 22:43 UTC
Labels: area/networking, kind/bug, status/to-test
