### ISSUE TITLE
UI doesn't display anything after clicking "Add Environment"

### ISSUE THREAD

**Issue by wjimenez5271** [rancher/rancher#8461] opened 2017-04-10 12:35 UTC
**Rancher Versions:**
Server: 1.5.3
healthcheck:
ipsec:
network-services:
scheduler:
kubernetes (if applicable):

**Docker Version:**
1.12.6

**OS and where are the hosts located? (cloud, bare metal, etc):**
Ubuntu/DigitalOcean

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
single node rancher/embeded DB

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle

**Steps to Reproduce:**
Disable "Rancher Certified Library" & "Community Contributed Catalogs" in the settings page and then try to add an environment under "Manage Environments" 

**Results:** 
UI shows no items other than menu bar after clicking "Add Environment"

**Comment by wjimenez5271** [comment] 2017-04-10 12:36
@loganhz suggested it might be related to https://github.com/rancher/ui/blob/1.5-fixes/app/models/projecttemplate.js#L81

**Comment by tfiduccia** [comment] 2017-04-10 17:13
Yes this was a duplicate of #8367.  If the orchestration template is missing by disabling the catalog, a blank page come up.  This happens with community as well because swarm and mesos are now in community instead of Rancher Certified library.

**Comment by deniseschannon** [comment] 2017-04-25 03:49
This was added in v1.5.6, but @tfiduccia can you confirm in master?

**Comment by tfiduccia** [comment] 2017-04-26 23:08
Version - master 4/26
Verified fixed

**Closed by tfiduccia** 2017-04-26 23:08 UTC
Labels: area/environment, area/ui, kind/bug, status/to-test
