### ISSUE TITLE
[CIS] Check for PSP compatibility in target cluster

### ISSUE THREAD

**Issue by MKlimuszka** [rancher/rancher#39851] opened 2022-12-09 22:48 UTC
Parent ticket: https://github.com/rancher/rancher/issues/39366

Kubernetes 1.25 drops support for PSP, so additional checks need to be added.

Rancher team 3 is following the proposal outlined in "Kubernetes v1.25 PSP to PSA migration proposal document"

Every chart that ships with a PSP must be changed to add a new condition checking for the PSP capability in the target cluster:

**Capabilities check for Helm**

```{{- if .Capabilities.APIVersions.Has "policy/v1beta1/PodSecurityPolicy" }}```

This change allows the charts to still work with PSPs in Kubernetes versions prior to v1.25, and work in Kubernetes v1.25 or higher by skipping installation of PSPs.

Charts that need updating: 
- rancher-cis-benchmark 

If a cluster role in a chart contains PSP's along with other permissions extra work may be needed to achieve the intended behavior of that role.

**Comment by MKlimuszka** [comment] 2022-12-20 15:41
We do, however, need to make sure the behavior is appropriate.

**Comment by doflamingo721** [comment] 2023-01-02 12:22
@prachidamle @MKlimuszka Following is the behaviour seen on 1.25 clusters:
1. **RKE**:
- **rke-profile-permissive-1.23**: The scans are working as expected. The scan is passing with the expected behaviour.
![209547832-616d4b31-3be3-47a2-9cb3-ff7a853085b0](https://user-images.githubusercontent.com/34883075/210229876-4e3d7d59-2541-4809-a099-7891daebd100.png)

- **rke-profile-hardened-1.23**: The scans are working as expected. There are some tests which fail mentioned in the screenshot below. The reason for their failures is because these tests run PSP related audit commands and in k8s 1.25 there isn't a PSP resource found.

![Screenshot from 2022-12-29 15-00-08](https://user-images.githubusercontent.com/34883075/210229235-72b539b0-5058-4b6c-b19e-f2f9b5632a37.png)

2. **K3s**:
- **k3s-profile-permissive-1.23**: The scans are working as expected. The scan is passing with the expected behaviour.
![Screenshot from 2022-12-27 15-21-35](https://user-images.githubusercontent.com/34883075/210229756-a869f0f5-cc16-4276-be61-864391bef003.png)

- **k3s-profile-hardened-1.23**: The scans are working as expected. The scan is passing with the expected behaviour.
![Screenshot from 2022-12-27 16-26-48](https://user-images.githubusercontent.com/34883075/210229665-c9db9669-2355-424d-936c-e026b2aea994.png)

3. **RKE2**:
- **rke2-profile-permissive-1.23**: The scans are working as expected. The scan is passing with the expected behaviour.
![Screenshot from 2022-12-27 15-21-58](https://user-images.githubusercontent.com/34883075/210230023-fd056b86-b8db-499c-9bf2-961c468d9b3e.png)

- **rke2-profile-hardened-1.23**: We were not able to verify the scan results for hardened rke2 cluster because the cluster provisioning for rke2 hardened cluster was failing consistently. For k8s 1.25, the 1.6 cis-profile was showing incorrect while cluster provisioning. Also after changing the profile to 1.23, the cluster provisioning was stuck on updating state. There is already an issue logged for this [here](https://github.com/rancher/rancher/issues/39148).

**Comment by vardhaman22** [comment] 2023-02-15 08:35
tested running scan for profile **rke2-profile-hardened-1.23** on **rke2-hardened cluster**  k8s: v1.25.6+rke2r1. 
The scan **failed** but all the failure cases have audit commands which try to do operation on **psp** so that is expected.
![rke2-cis-hardened](https://user-images.githubusercontent.com/115442970/218974775-1fec0989-1f07-4434-852c-b0152a27332e.png)
@prachidamle @MKlimuszka 
cc: @mitulshah-suse

**Comment by martyav** [comment] 2023-04-04 20:50
@MKlimuszka I'm on the docs team, helping with the 2.7.2 release notes. If the linked PRs are merged, why is this still open? Is there more to be done?

**Comment by mitulshah-suse** [comment] 2023-04-05 05:11
The comments above need to be documented in the release notes as expected failures for CIS scans on 1.25 clusters.
https://github.com/rancher/rancher/issues/39851#issuecomment-1430941043
https://github.com/rancher/rancher/issues/39851#issuecomment-1368903719

**Comment by prachidamle** [comment] 2023-04-07 15:27
@ronhorton can we close this as CIS chart has been tested with k8s 1.25?

**Comment by ronhorton** [comment] 2023-04-07 15:37
**Pass** We've tested this thoroughly ;) 
Going out with rancher `2.7.2`

**Closed** 2023-04-07 15:37 UTC
Labels: kind/enhancement, priority/0, [zube]: To Test, release-note, team/infracloud, feature/charts-cis-benchmark, area/charts

**Comment by martyav** [comment] 2023-05-16 19:18
@ronhorton Working on release notes. Are the expected failures described above for RKE and RKE2 still valid, or can this be moved to bug fixes?
