### ISSUE TITLE
rancher export/rancher up round trip doesn't work with secrets

### ISSUE THREAD

**Issue by TimLudwinski** [rancher/rancher#9489] opened 2017-07-26 16:33 UTC
**Rancher versions:**
rancher/server: v1.6.5
rancher/agent: N/A
 rancher/CLI: v0.6.2

**Infrastructure Stack versions:**
healthcheck: N/A
ipsec: N/A
network-services: N/A
scheduler: N/A
kubernetes (if applicable):

**Docker version: (`docker version`,`docker info` preferred)**
 17.03.x-ce

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
```
PRETTY_NAME="Debian GNU/Linux 8 (jessie)"
NAME="Debian GNU/Linux"
VERSION_ID="8"
VERSION="8 (jessie)"
ID=debian
HOME_URL="http://www.debian.org/"
SUPPORT_URL="http://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
```
`3.10.0-229.14.1.el7.x86_64`

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
Custom

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
 Single Node with Bind Mounted Database

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**
 Cattle (with Secrets)

**Steps to Reproduce:**

    rancher export zaim-backend
    cd zaim-backend
    sed -i "s|    image: dockerregistry1.infra.idef:5000/zaim_sample_processor:0.1.\d*|    image: dockerregistry1.infra.idef:5000/zaim_sample_processor:0.1.68|" docker-compose.yml
    sed -i "s|      mode: '444'|      mode: 444|" docker-compose.yml # This fixes issue 9094
    rancher up -u

See configs here: https://github.com/rancher/rancher/issues/9094

**Results:**

```
INFO[0000] [webserver]: Creating
INFO[0000] [cronjobs]: Creating
INFO[0000] [processor]: Creating
INFO[0000] [webserver]: Created
INFO[0000] [processor]: Created
INFO[0000] [cronjobs]: Created
INFO[0000] [webserver]: Starting
INFO[0000] [cronjobs]: Starting
INFO[0000] [processor]: Starting
ERRO[0000] Failed Starting webserver : Failed to find secret
ERRO[0000] Failed Starting cronjobs : Failed to find secret
ERRO[0000] Failed to start: cronjobs : Failed to find secret
ERRO[0000] Failed Starting processor : Failed to find secret
ERRO[0000] Failed to start: processor : Failed to find secret
ERRO[0000] Failed to start: webserver : Failed to find secret
FATA[0000] Failed to find secret
```

**Comment by joshwget** [comment] 2017-07-26 16:38
Export for secrets doesn't work correctly at the moment, so I think this is a duplicate of #9059.

**Closed** 2017-07-26 19:03 UTC
