### ISSUE TITLE
Rancher should clean up ssh keypairs it creates when deleting a downstream ec2 cluster

### ISSUE THREAD

**Issue by davidnuzik** [rancher/rancher#34729] opened 2021-09-14 21:23 UTC
**Is your feature request related to a problem? Please describe.**
I'm frustrated whenever Rancher leaves behind objects in Azure, aws, etc.
Specifically with ec2, if you create any ec2 cluster with Rancher (just about any version of Rancher I believe) it will create ec2 keypairs (ssh keys). When you then delete the ec2 cluster, Rancher does not delete/clean up these ssh keypair(s) it created. 

**Describe the solution you'd like**
If it's possible (which I assume it is), I would like Rancher to know what aws ssh keypair it created to provision an ec2 cluster. When the cluster needs to be tore down (or failed to create), Rancher should check if the aws ssh keypair (IT CREATED) exists in aws and if so delete it since it is no longer needed.

If the operator had defined an aws ssh keypair to use when creating the cluster - then in this case Rancher did NOT create the keypair, and therefore it should NOT get flagged for deletion when deleting the downstream cluster in Rancher. Perhaps as an extra means of protection we would check that the keypair has a rancher-generated name scheme as well before deleting.

If there are edge cases that make us nervous about making this feature enabled by default, then I propose we make this a feature flag that is disabled by default. The operator could enable the feature flag allowing rancher to delete these objects it creates. This feature flag in rancher could have a description calling out that this behavior is destructive and could have unintended consequences if intending to utilize these objects rancher creates post cluster deletion.

**Describe alternatives you've considered**
None I can think of. Today I must manually delete my ssh keypairs in aws.

**Additional context**
We should never leave behind any resources after deleting a cluster Rancher created.
The QA internal aws account has many thousands of ssh keys because Rancher does not clean these up. Additionally consider these issues that are somewhat related:
https://github.com/rancher/rancher/issues/16798
https://github.com/rancher/rancher/issues/23488

**Additional comments**
Rancher also leaves behind at least a few objects when deleting a rancher-created Azure cluster.

SURE-4680

**Comment by davidnuzik** [comment] 2021-09-14 21:39
If this is something we don't want to do because (however unlikely) someone might re-use these keys later perhaps we could make this more of a feature that you could _opt-in to_ - for example it could be a feature flag? It would be disabled by default and the description could explain that it's destructive and will remove resources rancher creates in clouds like aws, azure, etc.

Perhaps the feature expands and it also deletes all the stuff we leave behind when tearing down Azure clusters as well.

**Comment by HarrisonWAffel** [comment] 2022-08-08 17:44
This issue may have been partially/fully resolved for AWS by https://github.com/rancher/machine/pull/190

When deleting key-pairs For AWS instances, rancher-machine was attempting to [describe the VM instance](https://docs.aws.amazon.com/cli/latest/reference/ec2/describe-instances.html) to see the key-pair reference stored in the cloud. This call ensures that the key-pair attached to the instance is deleted, even if its name has been changed. This works fine for a running or recently terminated instance, but in the case where an instance is never created it resulted in an error which orphaned key-pairs (and in the process suppressed useful error messages).

When creating VM's, rancher-machine will generate a `config.json` file which contains instance metadata as well as related resources. The change made for the above PR was to use the name of the locally stored key-pair if the instance could not be described, as we expect the name of the key-pair stored within AWS to equal the name of the local reference. 

From what I can determine, the above change addresses both the scenario in which an instance fails to create (tested and confirmed), as well as the scenario in which the instance is not returned from the VM describe request (which could occur if the instance was manually terminated / unexpectedly terminated more than 1 hour ago). 


I am still looking into resource orphaning on other cloud-providers, such as Azure.

**Comment by HarrisonWAffel** [comment] 2022-08-08 20:46
In regards to Azure resources, I did identify one resource that is not being cleaned up properly - Availability sets. Apparently this has been a reported issue for some time that did not receive any attention: https://github.com/rancher/rancher/issues/35055. The root-cause of this orphaned resource is a conditional which is fast-failing due to the use of `&&` as opposed to `||`.

**Comment by HarrisonWAffel** [comment] 2022-08-08 23:33
This test template focuses on the EC2 key-pair issue, a separate test-template will be written for #35055 when the machine PR is merged 

### Root cause
When deleting AWS key-pairs, Rancher attempts to describe the EC2 instance being deleted so that it can get the most up-to-date information on what key-pair is being used. However, in the case when this call is not successful, or when an instance was never created due to some other issue, key-pairs would not be deleted.

### What was fixed, or what changes have occurred
In the scope of https://github.com/rancher/rancher/issues/38422 the logic for deleting key-pairs was updated. Now, when an instance cannot be returned from the AWS API, machine will use the name of locally stored key-pair name (located within `config.json`) in the API request to delete key-pairs. 

### Areas or cases that should be tested
The removal of EC2 key-pairs from the AWS console after both successful, and unsuccessful, provisioning attempts. 

1. Successful provisioning
a. Provision an EC2 cluster using default settings (1 node, all roles)
b. In the AWS Console, make note of the key-pair associated with the instance. This can be found in the `instance details` section of the UI after you select the instance within the AWS console
c. After the instance has been fully created, delete the instance 
d. Check to see that the key-pair created for that instance has been deleted. 

2. Unsuccessful provisioning 
a. Create a new node-template for AWS and specify a non-existing IAM user in the `IAM Instance Profile Name` section of the UI
b. Create a new cluster with this template (1 node, all roles) 
c. Observe that the instance fails to create, due to invalid IAM user
d. Ensure that no key-pairs are orphaned within the AWS console as rancher machine attempts to create additional instances. 
e. Delete the invalid cluster from the Rancher UI 
f. Double check that no additional key-pairs can be found in the AWS console.

**Comment by jameson-mcghee** [comment] 2022-08-09 21:19
I was able to verify on v2.6-head Commit ID cd97f6f that when an RKE1 or RKE2 downstream EC2 cluster is deleted, all associated ssh keypairs are also removed from AWS. @HarrisonWAffel, I did observe something odd during testing, however. I also tested this on v2.6.6, and confirmed that the ssh keypairs for EC2 clusters deleted from there are also cleaning up their associated keypairs.
I dont think that the above is a concern, and the primary functionality of this ticket is working, so I am going to closed this ticket as Done, but I did want to note the somewhat strange behavior.
cc @sowmyav27 @slickwarren 

v2.6-head clusters:
![image.png](https://zube.io/files/rancher/c88789b831495e4e457390e77c03695a-image.png)

v2.6.6 cluster:
![image.png](https://zube.io/files/rancher/f95a804c40c4b02ceae39b49b8e94eb6-image.png)

v2.6.6 and v2.6-head keypairs:
![image.png](https://zube.io/files/rancher/7bd6be837c03cf424f2a98151212f6da-image.png)

Keypairs after v2.6-head clusters deleted:
![image.png](https://zube.io/files/rancher/dd226134ea370e0a95c19e5d73a94c8f-image.png)

Keypairs after v2.6.6 clusters deleted:
![image.png](https://zube.io/files/rancher/efe7fccc61f2b6958f86ed2e623f929a-image.png)

**Comment by HarrisonWAffel** [comment] 2022-08-09 21:54
@jameson-mcghee Thanks for testing this one out. In regards to the 2.6.6 behavior, key-pairs for successfully created clusters have been getting properly cleaned up in prior versions of Rancher. The change that was included in #38422 ensured that key-pairs for instances that were not properly created, either due to misconfiguration or some other API error, did have their key-pairs cleaned up. Correct me if I've misunderstood your statement, but the behavior on 2.6.6 seems expected

**Comment by sowmyav27** [comment] 2022-08-09 22:06
Reopening for checks related to the fix - ensuring the keys are deleted when there is a failure to provision cluster in rancher

**Comment by jameson-mcghee** [comment] 2022-08-10 14:22
I was previously able to verify on v2.6-head Commit ID cd97f6f that when an RKE1 or RKE2 downstream EC2 cluster is deleted, all associated ssh keypairs are also removed from AWS (see previous comment and screenshots). This was preexisting functionality, and is still working correctly.

I was also able to confirm that when a cluster is unsuccessful in provisioning, there are no ssh keypairs created/abandoned in AWS. I confirmed this following the information in the Test Template on RKE1 and RKE2 clusters.
Therefore I am closing this ticket, because it is functioning as designed.
cc @HarrisonWAffel 

![image.png](https://zube.io/files/rancher/8e60e73c5327a4fd0c1842d165d1628b-image.png)
![image.png](https://zube.io/files/rancher/d6b9a793b14dc587f1c7e3e3edaa630b-image.png)

**Closed** 2022-08-10 14:22 UTC
Labels: area/machine, internal, [zube]: To Test, feature/rancher-machine, team/area2, JIRA, v2.6.7
