### ISSUE TITLE
Fail to add my own laptop to rancher server

### ISSUE THREAD

**Issue by masterkorp** [rancher/rancher#5214] opened 2016-06-21 17:33 UTC
**Rancher Version:** v1.1.0-dev5
**Docker Version:** Docker version 1.11.2, build b9f10c9
**OS and where are the hosts located? (cloud, bare metal, etc):** Arch Linux OS up to date on my personal laptop

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)** Single node rancher setuo

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)** Did not get to that point yet

**Steps to Reproduce:**
Following quick start quick guide, start the rancher server.

Bootstrap the host with:
```
sudo docker run -e CATTLE_AGENT_IP="192.168.5.8"  -d --privileged -v /var/run/docker.sock:/var/run/docker.sock -v /var/lib/rancher:/var/lib/rancher rancher/agent:v1.0.2 http://127.0.0.1:8080/v1/scripts/022B6BE40F23DA80DC14:1466528400000:GT2ykuiFB5RDwkCqP7OGJgI8
```

**Results:**  The containers exists right after startup:

```
-> % docker ps -a
CONTAINER ID        IMAGE                  COMMAND                  CREATED              STATUS                     PORTS                              NAMES
3ba8dcfd25ec        rancher/agent:v1.0.2   "/run.sh http://127.0"   7 seconds ago        Exited (1) 6 seconds ago                                      clever_bhaskara
c4b3acead043        rancher/server         "/usr/bin/s6-svscan /"   About a minute ago   Up About a minute          3306/tcp, 0.0.0.0:8080->8080/tcp   rancher_server
```

When doing docker logs I get the following error:
```
-> % docker logs -f 3ba8dcfd25ec
Error response from daemon: 400 Bad Request: malformed Host header
```

**Expected:** The rancher should start without any problem.

**Comment by deniseschannon** [comment] 2016-06-21 20:34
Duplicate of https://github.com/rancher/rancher/issues/4728

**Closed by deniseschannon** 2016-06-21 20:34 UTC
