### ISSUE TITLE
UI: certificate rotation for RKE clusters

### ISSUE THREAD

**Issue by alena1108** [rancher/rancher#16795] opened 2018-11-30 19:36 UTC
This ticket is to keep track of UI component of the certificate rotation feature for rke clusters

Backend issue: https://github.com/rancher/rke/issues/450

**Comment by alena1108** [comment] 2018-12-21 21:38
@westlywright The API has been merged into master - we have a rotate certs action on a cluster now. @galal-hussein is the backend developer for the feature.

**Comment by davidnuzik** [comment] 2019-01-03 22:34
I encounter a 500 error upon POST when clicking on "Rotate Certificates" for a cluster (Digital Ocean in my case) with a message of "unmarshaling input error: unexpected end of JSON input" in the server response. And I see the same in rancher server docker logs.

**Comment by westlywright** [comment] 2019-01-04 19:37
@davidnuzik after rancher/rancher#2250 is merged you will be able to use the rotate certs api from the UI but you will see errors in the UI. I've already filed a bug (rancher/rancher#17317) because the growl errors you see in the upper right of the UI are due to an incorrect response from the UI.

So I think we can cl0se this ticket by verifying via the network tab in dev tools.
Launch an RKE based cluster
When the cluster is ready select the `Rotate Certificates` action in the actions dropdown
Select radio or use dropdown etc. and save
In the network tab verify the action request does not error out and returns something like `Rotating <service-name-or-all> certificates`

Once the api is returning the correct JSON we won't see the errors in the UI.

**Comment by davidnuzik** [comment] 2019-01-04 20:41
Thanks @westlywright 
Version: master 2.2 (1/4/19)
Confirmed new feature. There is a new modal for rotating cluster certificates. You do this by clicking on the action menu for a cluster. I validated HTTP and confirmed that on the backend we try to rotate certs per what was chosen in the modal. There is an error in the UI with the JSON and this is tracked in #17317 as Wes mentioned.

**Closed by davidnuzik** 2019-01-04 20:41 UTC
Labels: area/ui, kind/feature, priority/0, status/resolved, status/to-test, team/az, version/2.0
