### ISSUE TITLE
Host IP of exposed port not updated after container moved to other host

### ISSUE THREAD

**Issue by mmkaminski** [rancher/rancher#9351] opened 2017-07-14 14:54 UTC
**Rancher versions:**
rancher/server: 1.5.6 from "enterprise"
rancher/agent: rancher/agent:v1.2.2

**Infrastructure Stack versions:**
healthcheck: rancher/healthcheck:v0.2.3
ipsec: rancher/net:holder
network-services: rancher/network-manager:v0.7.4
scheduler: 
kubernetes (if applicable): N/A

**Docker version: (`docker version`,`docker info` preferred)**

Client:
 Version:         1.12.6
 API version:     1.24
 Package version: docker-common-1.12.6-16.el7.x86_64
 Go version:      go1.7.4
 Git commit:      3a094bd/1.12.6
 Built:           Tue Mar 21 13:30:59 2017
 OS/Arch:         linux/amd64

Server:
 Version:         1.12.6
 API version:     1.24
 Package version: docker-common-1.12.6-16.el7.x86_64
 Go version:      go1.7.4
 Git commit:      3a094bd/1.12.6
 Built:           Tue Mar 21 13:30:59 2017
 OS/Arch:         linux/amd64

Containers: 25
 Running: 22
 Paused: 0
 Stopped: 3
Images: 44
Server Version: 1.12.6
Storage Driver: devicemapper
 Pool Name: docker-253:0-12616020-pool
 Pool Blocksize: 65.54 kB
 Base Device Size: 10.74 GB
 Backing Filesystem: xfs
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 24.44 GB
 Data Space Total: 107.4 GB
 Data Space Available: 14.42 GB
 Metadata Space Used: 29.43 MB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.118 GB
 Thin Pool Minimum Free Space: 10.74 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 WARNING: Usage of loopback devices is strongly discouraged for production use. Use `--storage-opt dm.thinpooldev` to specify a custom block storage device.
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.135-RHEL7 (2016-11-16)
Logging Driver: journald
Cgroup Driver: systemd
Plugins:
 Volume: local
 Network: null overlay bridge host
 Authorization: rhel-push-plugin
Swarm: inactive
Runtimes: docker-runc runc
Default Runtime: docker-runc
Security Options: seccomp selinux
Kernel Version: 3.10.0-514.16.1.el7.x86_64
Operating System: Red Hat Enterprise Linux
OSType: linux
Architecture: x86_64
Number of Docker Hooks: 2
CPUs: 4
Total Memory: 15.14 GiB
Name: gro-demo03u-d.local.dtrts.com
ID: DVED:VFTC:TLMY:I4LE:CK2L:X5NK:RPTX:VOW5:Y6H3:X62W:UA6A:J5GX
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://registry.access.redhat.com/v1/
Insecure Registries:
 cert-registry:5000
 dev-registry:5000
 dmz-registry:5000
 127.0.0.0/8

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
NAME="Red Hat Enterprise Linux Atomic Host"
VERSION="7.1"
ID="rhel"
ID_LIKE="fedora"
VERSION_ID="7.1"
PRETTY_NAME="Red Hat Enterprise Linux"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:redhat:enterprise_linux:7.1:GA:atomic-host"
HOME_URL="https://www.redhat.com/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"

REDHAT_BUGZILLA_PRODUCT="Red Hat Enterprise Linux 7"
REDHAT_BUGZILLA_PRODUCT_VERSION=7.1
REDHAT_SUPPORT_PRODUCT="Red Hat Enterprise Linux"
REDHAT_SUPPORT_PRODUCT_VERSION=7.1

3.10.0-514.16.1.el7.x86_64

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
vSphere

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
single node external DB

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle

**Steps to Reproduce:**
Occasionally, after an update and node switch the service will still report being on the old node. This causes the entire service to be unreachable until another upgrade is processed and the system correctly updates the service's host. Please see sequential screen grabs.

<img width="734" alt="1" src="https://user-images.githubusercontent.com/28441203/28217291-a30ab5b4-6882-11e7-8fd6-4466783909d0.png">
<img width="718" alt="2" src="https://user-images.githubusercontent.com/28441203/28217304-a6826aa2-6882-11e7-86df-5a865ba9a168.png">
<img width="947" alt="3" src="https://user-images.githubusercontent.com/28441203/28217307-a8fb8d5e-6882-11e7-995a-904d13cba409.PNG">
<img width="378" alt="4" src="https://user-images.githubusercontent.com/28441203/28217316-ad9fa156-6882-11e7-876f-6fc0e975ec7a.PNG">
<img width="589" alt="5" src="https://user-images.githubusercontent.com/28441203/28217319-b0538340-6882-11e7-88d0-30a115ccca4c.PNG">
<img width="682" alt="6" src="https://user-images.githubusercontent.com/28441203/28217324-b2ec24a4-6882-11e7-9674-bfa30ae55214.png">
<img width="510" alt="7" src="https://user-images.githubusercontent.com/28441203/28217325-b510d996-6882-11e7-8b95-ccaff76d3e75.PNG">
<img width="953" alt="8" src="https://user-images.githubusercontent.com/28441203/28217330-b6ec5a10-6882-11e7-938f-3e36416d89d2.PNG">

**Results:**
This happens intermittently.

**Comment by leodotcloud** [comment] 2017-07-18 01:22
From your screenshots looks like the HOST_IP is correct, just that it's not accessible. Very likely this is fixed by this: https://github.com/rancher/plugin-manager/commit/b97e4318d1468dfd08bafeb32c1030d97a85af0d

Can you please check with the latest version of `rancher/server`?

**Comment by superseb** [comment] 2017-08-11 14:05
Is this when upgrading from the UI or CLI? And just to make sure, this is not an UI problem which is solved by refreshing the page?

My first tests don't reproduce this problem just yet.

**Comment by leodotcloud** [comment] 2017-09-09 07:39
@mmkaminski Please open a new issue if you are still having problems. Closing this one.

**Closed by leodotcloud** 2017-09-09 07:39 UTC
Labels: area/cattle, status/more-info
