### ISSUE TITLE
Deleting a Workload created by a Catalog Not Reflected in UI without Hard Refresh

### ISSUE THREAD

**Issue by ekristen** [rancher/rancher#14936] opened 2018-08-03 14:12 UTC
**Rancher versions:**
rancher/server or rancher/rancher: 2.0.6

Possibly related to https://github.com/rancher/rancher/issues/14476

If you pause and then delete a workload from Rancher that was created by a catalog entry, upon navigating back to the catalog entry, the workload still appears under the listing. After hard refresh the workload disappears.

**Steps to Reproduce:**
1. Launch catalog entry
2. Pause orchestration on workload
3. Delete the workload
4. Navigate to the Catalog Apps -> The catalog you deleted the workload from, at this point the workload should still appear under the workloads, but you will not be able to interact with it as the API will tell you it is not found.

**Comment by loganhz** [comment] 2018-08-23 01:52
I can not reproduce this issue in rancher/rancher:master 22/08.
It looks like it is a websocket issue and has been fixed now.

**Comment by tfiduccia** [comment] 2018-08-27 18:28
@ekristen - I also cannot reproduce.  Can you reproduce with a catalog that is in our library and let us know which catalog and which workload you deleted?

**Comment by ekristen** [comment] 2018-09-07 14:12
I will upgrade to 2.0.8 and test. I believe @loganhz is correct it was a websocket issue that was fixed already.

**Comment by tfiduccia** [comment] 2018-09-10 18:48
Version - 2.1 master 9/10
Verified fixed :)

**Closed by tfiduccia** 2018-09-10 18:48 UTC
Labels: area/catalog, kind/bug, status/to-test, version/2.0
