### ISSUE TITLE
rancher scheduling port failed

### ISSUE THREAD

**Issue by demohi** [rancher/rancher#4776] opened 2016-05-12 05:49 UTC
Hi,

#### docker-compose.yml

```yaml
test:
  restart: always
  image: "test"
  privileged: true
  ports:
    - 8000
```

#### rancher-compose.yml

```yaml
test:
  scale: 2
```

I define a inside port in docker-compse.yml. When I scale it to 2, It should scheduling two random port,but I found rancher scheduling two same port and get a Error

```
Error (Scheduling failed: host needs ports 63050/tcp available) 
Host:
```

When use the rancher ui get config ,I found the docker-compose config 

```yaml
test:
  ports:
  - 63050:8000/tcp
  image: test
  privileged: true
```

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v1.0.1` Cattle: `v0.159.7` UI: `v1.0.5` |
|Access|`Disabled`|
|Route|`authenticated.project.apikeys`|

**Comment by deniseschannon** [comment] 2016-05-12 06:12
This is a duplicate of https://github.com/rancher/rancher/issues/4178.

There is a lengthy discussion in that thread, but tl;dr

This is by design, random ports are assigned by service (not by each individual container in the service).

**Closed by deniseschannon** 2016-05-12 06:12 UTC
