### ISSUE TITLE
Fail to upgrade rancher to 2.5.5

### ISSUE THREAD

**Issue by felixng-umh** [rancher/rancher#30766] opened 2021-01-11 01:45 UTC
Give the following error when upgrage to rancher 2.5.5 :
Error: UPGRADE FAILED: chart requires kubeVersion: < 1.20.0 which is incompatible with Kubernetes v1.18.9-eks-d1db3c

**Comment by jangjaelee** [comment] 2021-01-11 09:54
The same error occurs in AWS EKS v1.17 (Kubernetes v1.17.12-eks-7684af)

**Comment by jangjaelee** [comment] 2021-01-11 10:00
In Rancher v2.5.1 to v2.5.4 error occurs such as bwlow

eks-user:~/environment/fargate $ helm install rancher rancher-stable/rancher --namespace cattle-system --set hostname=rancher-test.awx.kr --version 2.5.4
Error: unable to build kubernetes objects from release manifest: unable to recognize "": no matches for kind "Issuer" in version "cert-manager.io/v1"

eks-user:~/environment/fargate $ helm install rancher rancher-stable/rancher --namespace cattle-system --set hostname=rancher-test.awx.kr --version 2.5.3
Error: unable to build kubernetes objects from release manifest: unable to recognize "": no matches for kind "Issuer" in version "cert-manager.io/v1"

eks-user:~/environment/fargate $ helm install rancher rancher-stable/rancher --namespace cattle-system --set hostname=rancher-test.awx.kr --version 2.5.2
Error: unable to build kubernetes objects from release manifest: unable to recognize "": no matches for kind "Issuer" in version "cert-manager.io/v1"

eks-user:~/environment/fargate $ helm install rancher rancher-stable/rancher --namespace cattle-system --set hostname=rancher-test.awx.kr --version 2.5.1
Error: failed to download "rancher-stable/rancher" at version "2.5.1" (hint: running `helm repo update` may help)

**Comment by Yipin-Qi** [comment] 2021-01-11 11:38
This issue occurs in EKS v1.18.9-eks-d1db3c. The root cause seems to be the hardcoded kubeversion in the Chart.yaml file.
I am looking for a fix, meanwhile I found the below workaround:

Execute the command to download the rancher serverchart:
1. helm pull rancher-stable/rancher
2. unzip this tgz file (rancher-2.5.5.tar)
3. vi rancher/Chart.yaml
4. Change the parameter for kubeversion from 1.20.0 to 1.20.0-eks  (kubeVersion: < 1.20.0-eks)
5. Install the rancher server from the local directory not from the offical chart repo

**Comment by bashofmann** [comment] 2021-01-11 13:27
I found this related issue in helm/helm with more details: https://github.com/helm/helm/issues/3810.

**Comment by mattfarina** [comment] 2021-01-11 14:27
The issue is that EKS is identifying its version as a prerelease in semver terms. When you have the `-` and some data after it that's a prerelease. I notice that GKE does the same. You can see the spec at https://semver.org/#spec-item-9.

A fix that works cross provider would be to set `kubeVersions: < 1.20.0-0`. The `-0` on the end does two things:
1. If forces the version range system to consider prereleases.
2. Prereleases are ascii based and `0` is the lowest possible ascii value allowed in a prerelease. So, it's less than the lowest one.

**Comment by maxisam** [comment] 2021-01-11 19:02
I can't upgrade from 2.5.3 to 2.5.5 but I can upgrade to 2.5.4.  Mine is on-premise powered by vmware.


8 warnings.go:77] apiextensions.k8s.io/v1beta1 CustomResourceDefinition is deprecated in v1.16+, unavailable in v1.22+; use apiextensions.k8s.io/v1 CustomResourceDefinition
[ERROR] unable to update feature unsupported-storage-drivers in initialize features: rpc error: code = Unavailable desc = transport is closing

**Comment by brettmorien** [comment] 2021-01-11 19:35
FYI, v2.5.5-RC1 has nearly all the same functionality and fixes, but doesn't have the version restriction. If you need 2.5.5, RC1 is a good stopgap.

**Comment by deniseschannon** [comment] 2021-01-12 07:09
We've updated the v2.5.5 helm chart to fix the kubeversion so that it will work with the "pre-releases" that Helm uses for semver comparison.

Please update your helm repos and try to deploy the latest 2.5.5 charts.

**Closed** 2021-01-12 07:09 UTC

**Comment by marthydavid** [comment] 2021-01-12 11:07
It's still failing on latest k3s with:
```bash
$ helm upgrade --install rancher rancher-stable/rancher \
  --namespace cattle-system \
  --set hostname=myown.site\
  --set ingress.tls.source=letsEncrypt \
  --set letsEncrypt.email=my@email.address
Error: UPGRADE FAILED: chart requires kubeVersion: < 1.20.0-0 which is incompatible with Kubernetes v1.20.0+k3s2
```

```bash
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.1", GitCommit:"c4d752765b3bbac2237bf87cf0b1c2e307844666", GitTreeState:"clean", BuildDate:"2020-12-18T12:09:25Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.0+k3s2", GitCommit:"2ea6b16315c093d739c370f8f035ad3fa5eb5d11", GitTreeState:"clean", BuildDate:"2020-12-22T02:10:12Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
```

```bash
$ helm pull rancher-stable/rancher
$ md5sum rancher-2.5.5.tgz
c8ce986ba2b6e1b223814539edbe26a8  rancher-2.5.5.tgz
```

**Comment by bashofmann** [comment] 2021-01-12 11:11
This is supposed to fail. Rancher 2.5.5 does not support Kubernetes 1.20.

**Comment by marthydavid** [comment] 2021-01-12 15:00
> This is supposed to fail. Rancher 2.5.5 does not support Kubernetes 1.20.

My bad.

**Comment by jangjaelee** [comment] 2021-01-28 01:40
> In Rancher v2.5.1 to v2.5.4 error occurs such as below.
> 
> eks-user:~/environment/fargate $ helm install rancher rancher-stable/rancher --namespace cattle-system --set hostname=rancher-test.awx.kr --version 2.5.4
> Error: unable to build kubernetes objects from release manifest: unable to recognize "": no matches for kind "Issuer" in version "cert-manager.io/v1"
> 
> eks-user:~/environment/fargate $ helm install rancher rancher-stable/rancher --namespace cattle-system --set hostname=rancher-test.awx.kr --version 2.5.3
> Error: unable to build kubernetes objects from release manifest: unable to recognize "": no matches for kind "Issuer" in version "cert-manager.io/v1"
> 
> eks-user:~/environment/fargate $ helm install rancher rancher-stable/rancher --namespace cattle-system --set hostname=rancher-test.awx.kr --version 2.5.2
> Error: unable to build kubernetes objects from release manifest: unable to recognize "": no matches for kind "Issuer" in version "cert-manager.io/v1"
> 
> eks-user:~/environment/fargate $ helm install rancher rancher-stable/rancher --namespace cattle-system --set hostname=rancher-test.awx.kr --version 2.5.1
> Error: failed to download "rancher-stable/rancher" at version "2.5.1" (hint: running `helm repo update` may help)

I solved them.
It was necessary to install CRDs(CustomResourceDefinitions).

``
Install the CustomResourceDefinitions and cert-manager itself:

# Kubernetes 1.16+
$ kubectl apply -f https://github.com/jetstack/cert-manager/releases/download/v1.1.0/cert-manager.yaml

# Kubernetes <1.16
$ kubectl apply --validate=false -f https://github.com/jetstack/cert-manager/releases/download/v1.1.0/cert-manager-legacy.yaml
``

**Comment by softshipper** [comment] 2021-02-05 21:20
When I try to install
```
helm install \
  cert-manager jetstack/cert-manager \
  --namespace cert-manager \
  --version v1.1.0 \
  --set installCRDs=true
```
it shows me:
```
WARNING: You should switch to "https://charts.helm.sh/stable" via:
WARNING: helm repo add "stable" "https://charts.helm.sh/stable" --force-update
Error: rendered manifests contain a resource that already exists. Unable to continue with install: ServiceAccount "cert-manager-cainjector" in namespace "cert-manager" exists and cannot be imported into the current release: invalid ownership metadata; label validation error: missing key "app.kubernetes.io/managed-by": must be set to "Helm"; annotation validation error: missing key "meta.helm.sh/release-name": must be set to "cert-manager"; annotation validation error: missing key "meta.helm.sh/release-namespace": must be set to "cert-manager"
``` 

What am I doing wrong?

**Comment by jlact** [comment] 2021-02-09 16:25
This fails to install still:
`Error: chart requires kubeVersion: < 1.20.0-0 which is incompatible with Kubernetes v1.20.0`

With kube versions:
`Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.4", GitCommit:"d360454c9bcd1634cf4cc52d1867af5491dc9c5f", GitTreeState:"clean", BuildDate:"2020-11-14T14:49:35Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.7", GitCommit:"14f897abdc7b57f0850da68bd5959c9ee14ce2fe", GitTreeState:"clean", BuildDate:"2021-01-22T17:29:38Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}`

**Comment by Goeger** [comment] 2021-02-15 14:55
We get the same error with 2.5.5 on a newly installed system.

```
rancher-user:~$ helm template rancher ./rancher-2.5.5.tgz --output-dir . \
  --namespace cattle-system \
  --set hostname=rancher.mydomain.com \
  --set rancherImage=registry.mydomain.com/rancher/rancher \
  --set ingress.tls.source=secret \
  --set systemDefaultRegistry=registry.mydomain.com \
  --set useBundledSystemChart=true \
  --set rancherImageTag=v2.5.5
Error: chart requires kubeVersion: < 1.20.0-0 which is incompatible with Kubernetes v1.20.0
```
```
rancher-user:~$ kubectl version
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.6", GitCommit:"fbf646b339dc52336b55d8ec85c181981b86331a", GitTreeState:"clean", BuildDate:"2020-12-18T12:09:30Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.6", GitCommit:"fbf646b339dc52336b55d8ec85c181981b86331a", GitTreeState:"clean", BuildDate:"2020-12-18T12:01:36Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
```
```
rancher-user:~$ helm version
version.BuildInfo{Version:"v3.5.2", GitCommit:"167aac70832d3a384f65f9745335e9fb40169dc2", GitTreeState:"dirty", GoVersion:"go1.15.7"}
```
```
rancher-user:~$ which kubectl
/usr/bin/kubectl
```
With version 2.5.4 we do not get this error.

**Comment by cbron** [comment] 2021-02-15 15:47
This restriction has been removed in the upcoming Rancher 2.5.6.

**Comment by reddiablo85** [comment] 2021-04-13 19:49
This is still an issue for the rancher-stable charts for 2.4.15 
Had to remove the kubeVersion line from the chart.yaml to get it to work

**Comment by liuxuzxx** [comment] 2021-12-01 10:22
when I install rancher use helm,the error is:
```sh
Error: INSTALLATION FAILED: chart requires kubeVersion: < 1.22.0-0 which is incompatible with Kubernetes v1.22.3
```

**Comment by brianbturner82** [comment] 2022-02-22 23:02
I see the following trying to create a Helm template of 2.6.3:

Error: chart requires kubeVersion: < 1.23.0-0 which is incompatible with Kubernetes v1.23.0

Using kubectl 1.21.5

**Comment by thicongtu2** [comment] 2022-03-01 03:15
chart requires kubeVersion: < 1.23.0-0 which is incompatible with Kubernetes v1.23.3-2+d441060727c463

`Client Version: version.Info{Major:"1", Minor:"23+", GitVersion:"v1.23.3-2+d441060727c463", GitCommit:"d441060727c4632b67d09c9118a36a8590308676", GitTreeState:"clean", BuildDate:"2022-01-26T22:01:35Z", GoVersion:"go1.17.6", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"23+", GitVersion:"v1.23.3-2+d441060727c463", GitCommit:"d441060727c4632b67d09c9118a36a8590308676", GitTreeState:"clean", BuildDate:"2022-01-26T21:57:05Z", GoVersion:"go1.17.6", Compiler:"gc", Platform:"linux/amd64"}`

stuck at here

**Comment by bashofmann** [comment] 2022-03-01 09:13
@thicongtu2 You are trying to install Rancher on Kubernetes 1.23, but Rancher is not compatible with Rancher 1.23 yet.

Support for 1.23 is tracked here: https://github.com/rancher/rancher/issues/35739.
