### ISSUE TITLE
[ui] bug - services type default and upgrade do not populate

### ISSUE THREAD

**Issue by ekristen** [rancher/rancher#8501] opened 2017-04-13 14:26 UTC
Version: Rancher 1.5.4 

If you use the catalog and you set a default in on your services type, and that service is available, it does not populate. 

Also if you choose a service in the dropdown and then perform an upgrade, the dropdown returns to "choose a service" instead of remembering the option that it was first deployed with.

**Comment by ekristen** [comment] 2017-05-05 14:45
This is a pretty big bug when it comes to using rancher catalog templates reliably.

**Comment by ekristen** [comment] 2017-05-17 13:10
ping -- @joshuacox @tfiduccia

**Comment by ekristen** [comment] 2017-06-06 17:10
Any traction on this? This bug makes it pretty difficult to regularly use catalog templates that use service dropdowns, each time you have to ensure that the dropdown is reselected back to the proper service.

**Comment by ekristen** [comment] 2017-07-12 19:37
Confirmed that this bug is still present in 1.5.10

**Comment by ekristen** [comment] 2017-07-27 20:49
Using the default value for `type: service` in the catalog also does not populate the value correctly.

**Comment by ekristen** [comment] 2017-09-19 15:55
This bug is still present in 1.6.9

**Comment by cjellick** [comment] 2017-09-19 16:50
@ekristen I don't really understand what you are saying. Would you be able to provide more detailed steps to reproduce, including a sample catalog (can just attach the relevant catalog files if you dont want to post a full catalog on github)

**Comment by ekristen** [comment] 2017-09-19 17:04
Ah, yes sorry about that. Give me 10 and I'll give you screenshots + a catalog.

**Comment by ekristen** [comment] 2017-09-19 17:19
I've put together this catalog. https://github.com/ekristen/rancher-catalog-bug-8501

It has two entries S3 Server and Redis. Realistically there is no dependency between the two, but its two public images that I can use to demonstrate the bug in the UI.

* Step 1 - Deploy Redis
* Step 2 - Deploy S3 Server

On Step two when you click on Details, you'll see there is a **Redis Server** dropdown. It is not populated. If you look at https://github.com/ekristen/rancher-catalog-bug-8501/blob/master/templates/s3-server/0/rancher-compose.yml#L38 you can see that the *default* is set to **redis/server**, which is a valid service.

* Step 3 - Select the redis server from the dropdown and click launch. Once that is activated, move on to step 4.
* Step 4 - Click Up to Date
* Step 5 - Select v0 (current)

Scroll down and you will see that the previously selected redis/server is **not populated** in the dropdown. This happens regardless if you are doing a true upgrade or selecting the current template. You must then re-select the service and click upgrade.

![screen shot 2017-09-19 at 11 19 06 am](https://user-images.githubusercontent.com/48329/30605703-63907d0e-9d2c-11e7-9d6b-68484390ad15.png)

![screen shot 2017-09-19 at 11 19 32 am](https://user-images.githubusercontent.com/48329/30605708-6d454f32-9d2c-11e7-83dc-74c4e02b2dd6.png)

**Comment by cjellick** [comment] 2017-09-19 17:25
@vincent99 would you know offhand if this is an issue in the UI or in cattle/rancher-compose-executor?
Or is this an explicit design decision made for some reason to not select a service?

**Comment by cjellick** [comment] 2017-09-19 17:26
Also, thanks for the details @ekristen

**Comment by ekristen** [comment] 2017-09-19 17:34
Anytime. Thanks for taking a look.

**Comment by vincent99** [comment] 2017-10-09 09:04
Sounds like a UI bug finding the matching entry, but this needs to be redone to use names instead of IDs for 2.0 anyway since the association is done by name and ones which don't currently match anything are now allowed.

**Comment by loganhz** [comment] 2018-03-08 06:39
fixed in https://github.com/rancher/rancher/issues/11320

**Closed by loganhz** 2018-03-08 06:39 UTC
Labels: area/ui, kind/bug, version/1.6
