### ISSUE TITLE
Support successfulJobsHistoryLimit and failedJobsHistoryLimit for cron job

### ISSUE THREAD

**Issue by blackholegalaxy** [rancher/rancher#17841] opened 2019-02-03 14:28 UTC
**What kind of request is this (question/bug/enhancement/feature request):**

Enhancement / feature request

**Description:**

We use a cron job, defined in rancher, to make some cleanup in our files, on a 6h basis. We ended up quickly to have a huge list of pods in the rancher UI. Of course it's useful for log reading. But deleting them all, from time to time, is quite annoying.

**Could you consider adding an option, when creating/editing cron job, to only keep the latest X pods, or delete the pods older than X days?**

**Environment information**
- Rancher version: 2.1.5
- Installation option: single install

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): GKE
- Machine type (cloud/VM/metal) and specifications (CPU/memory): standard-2
- Kubernetes version (use `kubectl version`): 1.11.6

**Comment by loganhz** [comment] 2019-02-04 04:50
@blackholegalaxy  Could you check if `successfulJobsHistoryLimit` and `failedJobsHistoryLimit`is provided in your cron job?

https://kubernetes.io/docs/tasks/job/automated-tasks-with-cron-jobs/#jobs-history-limits
https://stackoverflow.com/questions/36384873/kubernetes-job-cleanup/43115763#43115763

**Comment by blackholegalaxy** [comment] 2019-02-04 11:46
No I wasn't aware of these options. Could we then add UI elements for these?

**Comment by loganhz** [comment] 2019-02-04 11:47
sure

**Comment by davidnuzik** [comment] 2019-04-30 22:49
Version: Master (4/30/19)

I see the new addition of Successful Jobs History Limit and Failed Jobs History Limit in the Job Configuration section (for cron job workload type)

![image](https://user-images.githubusercontent.com/45179589/56997083-6d369380-6b5b-11e9-98f5-7be47d231b2d.png)

I submitted a cron job workload for testing and inspected HTTP headers and they appear correct (cronJobConfig)
```
failedJobsHistoryLimit: 1
successfulJobsHistoryLimit: 3
```

HTTP response fails to load - something to do with gzip?
Schema was hard to find. In my case I found `v3/project/c-qxmkm:p-nbnbp/schemas/cronJob` but there is no mention of failedJobsHistoryLimit and successfulJobsHistoryLimit -- perhaps I am looking in the wrong place. The view on the workload details page (that shows pods) looks good and is correct (Job Configuration section, etc).

I can confirm that the UI looks good but this does not quite appear to be working correctly.

My Successful Jobs History Limit is 3 and yet pods keep getting created. My guess is that either the server did take my settings and I'm looking in the wrong area to validate schema (because the API for the workload looks good) or something else is going on (maybe I do not understand all the requirements to configure this correctly). Why is the server response payload corrupt? Chrome cant show it to me.

![image](https://user-images.githubusercontent.com/45179589/56998233-70338300-6b5f-11e9-8092-6ca320ce41e7.png)

My request payload appeared correct to me, but the response is not viewable.
```
cronJobConfig: {type: "cronJobConfig", concurrencyPolicy: "Allow", failedJobsHistoryLimit: 1,…}
concurrencyPolicy: "Allow"
failedJobsHistoryLimit: 1
jobConfig: {}
schedule: "0-59/3 0-23 * * *"
successfulJobsHistoryLimit: 3
suspend: false
type: "cronJobConfig"
```

**Comment by davidnuzik** [comment] 2019-05-03 19:18
I can now see the server response without any issues and so I am no longer concerned about this.

What I am concerned about is when I run `kubectl describe cronjobs` I do not see the `Successful Job History Limit:` or `Failed Job History Limit:` entries.

I could be mistaken as I'm still a little green with kubectl -- but I think this was expected. @loganhz if you have time, could you take a look at this? I think this is not working correctly. From UI/API perspective all is well but perhaps there is an issue on backend? I should see these limits when I describe the cronjob I would think.

**Comment by davidnuzik** [comment] 2019-05-03 19:19
If this is helpful, this is what I see when I describe the cronjob. I had thought it would show the successful/failed job history limit entry.

```
> kubectl describe cronjobs -n cron
Name:                       hello
Namespace:                  cron
Labels:                     cattle.io/creator=norman
Annotations:                field.cattle.io/creatorId: user-hkvv9
Schedule:                   */2 * * * *
Concurrency Policy:         Allow
Suspend:                    False
Starting Deadline Seconds:  <unset>
Selector:                   <unset>
Parallelism:                <unset>
Completions:                1
Active Deadline Seconds:    30s
Pod Template:
  Labels:       <none>
  Annotations:  cattle.io/timestamp: 2019-05-03T19:10:40Z
  Containers:
   hello:
    Image:      busybox
    Port:       <none>
    Host Port:  <none>
    Args:
      /bin/sh
      -c
      date; echo Hello from the Kubernetes cluster
    Environment:     <none>
    Mounts:          <none>
  Volumes:           <none>
Last Schedule Time:  Fri, 03 May 2019 19:18:00 +0000
Active Jobs:         <none>
Events:
  Type    Reason            Age    From                Message
  ----    ------            ----   ----                -------
  Normal  SuccessfulCreate  6m27s  cronjob-controller  Created job hello-1556910720
  Normal  SawCompletedJob   6m17s  cronjob-controller  Saw completed job: hello-1556910720
  Normal  SuccessfulCreate  4m27s  cronjob-controller  Created job hello-1556910840
  Normal  SawCompletedJob   4m17s  cronjob-controller  Saw completed job: hello-1556910840
  Normal  SuccessfulCreate  2m27s  cronjob-controller  Created job hello-1556910960
  Normal  SawCompletedJob   2m17s  cronjob-controller  Saw completed job: hello-1556910960
  Normal  SuccessfulDelete  2m17s  cronjob-controller  Deleted job hello-1556910720
  Normal  SuccessfulCreate  27s    cronjob-controller  Created job hello-1556911080
  Normal  SawCompletedJob   17s    cronjob-controller  Saw completed job: hello-1556911080
  Normal  SuccessfulDelete  17s    cronjob-controller  Deleted job hello-1556910840
```

**Comment by loganhz** [comment] 2019-06-04 07:19
Please try this. There is an example YAML for cron job. If we set the successfulJobsHistoryLimit to 3, it only shows 3 history pods

https://kubernetes.io/docs/tasks/job/automated-tasks-with-cron-jobs/

**Comment by davidnuzik** [comment] 2019-06-14 23:07
Thanks Logan, I think I was just doing it incorrectly when I tried to do it myself via the UI.
I got this working (succesfulJobsHistoryLimit) but am not certain if I am testing failedJobsHistoryLimit correctly. Could you take a look at that section below?

**Version: Master (v2.3) (6/14/19)**

**successfulJobHistoryLimit test:**

Imported k8s docs example YAML:
https://kubernetes.io/docs/tasks/job/automated-tasks-with-cron-jobs/
```
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: hello
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: hello
            image: busybox
            args:
            - /bin/sh
            - -c
            - date; echo Hello from the Kubernetes cluster
          restartPolicy: OnFailure
```

By default, the UI sets successfulJobsHistoryLimit to 3 and failedJobsHistoryLimit to 1
![image](https://user-images.githubusercontent.com/45179589/59542738-48547080-8ebc-11e9-98cd-9e75c5a19af5.png)

I can confirm that we only see a limit of 3 pods shown on the workload details page now (I have had 10 or so run, this job runs on every minute)
![image](https://user-images.githubusercontent.com/45179589/59542762-68842f80-8ebc-11e9-9489-5af5a29f7e43.png)


**failedJobHistoryLimit test:**

Imported k8s docs example YAML:
https://kubernetes.io/docs/tasks/job/automated-tasks-with-cron-jobs/
EXCEPT I tweak command to something I know will crash (and have no restart policy)
```
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: hello
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: hello
            image: busybox
            args:
            - /bin/sh
            - -c
            - sleep 5 && sudo kill -9 1
          restartPolicy: Never
```

failedJobsHistoryLimit is 1 by default. I edit the workload and ensure the "1" setting takes again and still I get countless pods shown in the UI in this case:
![image](https://user-images.githubusercontent.com/45179589/59543151-4be8f700-8ebe-11e9-88c5-67d3a6384759.png)

Maybe I am doing something wrong, but my expectation was to only see 1 pod since the jobs fails? Or does this not constitute as a failure?

**Comment by loganhz** [comment] 2019-06-14 23:21
@davidnuzik Maybe this help https://github.com/kubernetes/kubernetes/issues/53331#issuecomment-358274195 ?

**Comment by davidnuzik** [comment] 2019-06-14 23:26
Thanks @loganhz I will look.

**Comment by davidnuzik** [comment] 2019-06-19 19:16
I have looked at https://github.com/kubernetes/kubernetes/issues/53331#issuecomment-358274195 and not been successful as well. This looks like an upstream issue.
As such I'm going to close the issue and consider this resolved because I validated successfulJobsHistoryLimit but cannot test failedJobsHistoryLimit due to the upstream issue.

I tried various things suggested in the kubernetes issue and was not successful. I created pods that look like they fail properly but kubernetes is not _actually_ considering them failed pods it seems.

Refer to comment https://github.com/rancher/rancher/issues/17841#issuecomment-502306478 for my notes on my successful testing of successfulJobsHistoryLimit

**Closed by davidnuzik** 2019-06-19 19:16 UTC
Labels: [zube]: To Test, area/kubernetes, area/ui, kind/enhancement, priority/0, team/ui
