### ISSUE TITLE
[Load Balancer] Ability to customize haproxy options, registering sidekicks and rolling updates

### ISSUE THREAD

**Issue by ndelitski** [rancher/rancher#2367] opened 2015-10-19 12:20 UTC
Greetings!

Actively trying to use rancher in our project, but stucked with serveral problems...
1) I have a global LB service with many connected services distributed by subdomain, and i would like to customize several haproxy options for some of them. For example i have to enable `accept-proxy` and `balance source` option if rancher balancer is behind ELB and my service accepts websocket connections with socket.io.(https://medium.com/@Philmod/load-balancing-websockets-on-ec2-1da94584a5e9) If i run my own haproxy balancer how can i auto-update backend servers with autoscaling rancher services?
2) I have a confd sidekick on each service, mounting config.json file into the main container, and why rancher-lb create a second record for my sidekick which obviously have no http interface(i might got wrong what sidekicks are)?
<img width="1144" alt="screenshot 2015-10-19 15 24 02" src="https://cloud.githubusercontent.com/assets/3070298/10577630/79c92ea2-7675-11e5-8377-68d9aa5300c9.png">
As you see every mail service have a configuration sidekick but it doesnt mean i want to round robin to it...
```
backend 4ac22b05-78f0-4483-84a4-50f69b12ba27_0_backend                          
        mode http                                                               
        balance roundrobin                                                      
        server 685b4bd9-3545-4b34-8575-3580338c82c8 10.42.173.134:8082  << main service
        server 58977033-a399-4a85-9523-ca2e64a64db6 10.42.88.195:8082   << sidekick
```
3) How to proper update services under rancher-LB without killing connections and recreaing services? 
Single LB with subdomain-splited services:
<img width="344" alt="screenshot 2015-10-19 14 52 23" src="https://cloud.githubusercontent.com/assets/3070298/10577122/1547161e-7671-11e5-9b93-3839636d2f42.png">
I know these ways to update a service:
 - buggy in-service update. It only kills service
 - update from webapp to webapp2 doesn't make sense because i need to edit docker-compose and service name will change. I have a CI server continuously delivering container versions based on branch names, and then i need to update service with same image, same name, not changing master-1 to master-2
 - Fully recreate service stack and LB stack. `rancher-compose rm && rancher-compose up` - for service and lb
 - Using rancher-api directly. Kill all containers in service, then rancher-compose up. Like as It doesn't break service links

**Comment by alena1108** [comment] 2015-10-19 16:45
@ndelitski thanks for bringing up the issues!

1) custom params for haproxy would be addressed as a part of https://github.com/rancher/rancher/issues/2171

2) Sounds like a bug; only instance of a primary service should be registered to the LB. Will run the test, and update the ticket. 

3) InService upgrade is in the works; looks like it would satisfy most of your requirements - no services recreating, no links recreating:

https://github.com/rancher/rancher/issues/1874

**Comment by alena1108** [comment] 2015-10-19 17:31
@ndelitski filed a separate ticket to keep track of issue 2):

https://github.com/rancher/rancher/issues/2371

**Comment by deniseschannon** [comment] 2015-10-19 18:03
@ndelitski Let me know if all the issues that @alena1108  provided would satisfy your issues. Cause I don't know if there is anything else open specific in this issue.

**Comment by ndelitski** [comment] 2015-10-19 18:42
@deniseschannon yep, all issues are referenced correctly! Is it known when customizing haproxy feature  #2171 will be available? It is very critical for us

**Comment by deniseschannon** [comment] 2015-10-19 19:04
There is no specific timeline, but it most likely will be in the next couple of weeks.

**Closed by deniseschannon** 2015-10-19 19:04 UTC

**Comment by yunspace** [comment] 2016-02-10 05:01
I'm trying to follow the resolution of this ticket and it's quite confusing. #2171 is closed as a duplicate of #1871 which is closed in relation to #2179 which is currently open. So is there a way to enable `accept-proxy` yet?

**Comment by vincent99** [comment] 2016-02-10 05:21
An option to add lines to the `defaults` and `global` section of the haproxy config was added a while ago.  I think you could use `ssl-default-bind-options accept-proxy` in the defaults section if it you want it for only (and all) SSL ports, but otherwise these don't help you.  Additional work to be able to customize individual frontend/backends is in #2179.

**Comment by yunspace** [comment] 2016-02-10 12:35
Hi @vincent99 this would suit my needs perfectly as my load balancer listens to `443` only. Whilst we wait for #2179, I'm also using `jamessharp/docker-nginx-https-redirect` to redirect my port `80` HTTP traffic to my `443` HTTPS load balancer.

However when I  tried out the default flags you mentioned and restart my Load Balancer, they fail to startup: 

```
2/10/2016 11:31:59 PM[scripts.sh:99] tar cf - -C content .
2/10/2016 11:31:59 PMINFO: ROOT -> ./
2/10/2016 11:31:59 PMINFO: ROOT -> ./etc/
2/10/2016 11:31:59 PMINFO: ROOT -> ./etc/haproxy/
2/10/2016 11:31:59 PMINFO: ROOT -> ./etc/haproxy/certs/
2/10/2016 11:31:59 PMINFO: ROOT -> ./etc/haproxy/certs/default.pem
2/10/2016 11:31:59 PMINFO: ROOT -> ./etc/haproxy/certs/certs.pem
2/10/2016 11:31:59 PMINFO: ROOT -> ./etc/haproxy/haproxy.cfg
2/10/2016 11:31:59 PMINFO: ROOT -> ./etc/monit/
2/10/2016 11:31:59 PMINFO: ROOT -> ./etc/monit/conf.d/
2/10/2016 11:31:59 PMINFO: ROOT -> ./etc/monit/conf.d/haproxy
2/10/2016 11:31:59 PMINFO: ROOT -> ./etc/default/
2/10/2016 11:31:59 PMINFO: ROOT -> ./etc/default/haproxy
2/10/2016 11:31:59 PM[scripts.sh:102] '[' true = true ']'
2/10/2016 11:31:59 PM[scripts.sh:103] reload_monit
2/10/2016 11:31:59 PM[[scripts.sh:68] pidof monit
2/10/2016 11:31:59 PM[[scripts.sh:68] true
2/10/2016 11:31:59 PM[scripts.sh:68] local monit=
2/10/2016 11:31:59 PM[scripts.sh:69] '[' -n '' ']'
2/10/2016 11:31:59 PM[apply.sh:8] awk '/BEGIN.*PRIVATE KEY/{i++}{print > "/etc/haproxy/certs/server"i".pem"}' /etc/haproxy/certs/certs.pem
2/10/2016 11:31:59 PM[apply.sh:9] rm /etc/haproxy/certs/certs.pem
2/10/2016 11:31:59 PM[apply.sh:10] '[' '!' -s /etc/haproxy/certs/default.pem ']'
2/10/2016 11:31:59 PM[apply.sh:12] grep -q 'version 1.6'
2/10/2016 11:31:59 PM[apply.sh:12] haproxy -v
2/10/2016 11:31:59 PM[apply.sh:20] reload_haproxy /etc/haproxy/haproxy.cfg
2/10/2016 11:31:59 PM[scripts.sh:169] CONFIG=/etc/haproxy/haproxy.cfg
2/10/2016 11:31:59 PM[scripts.sh:171] '[' '!' -f /var/run/haproxy.pid ']'
2/10/2016 11:31:59 PM[[scripts.sh:176] cat /var/run/haproxy.pid
2/10/2016 11:31:59 PM[scripts.sh:176] haproxy -p /var/run/haproxy.pid -f /etc/haproxy/haproxy.cfg -sf 507
2/10/2016 11:32:00 PM[ALERT] 040/123159 (524) : parsing [/etc/haproxy/haproxy.cfg:34] : unknown keyword 'ssl-default-bind-options' in 'defaults' section
2/10/2016 11:32:00 PM[ALERT] 040/123159 (524) : Error(s) found in configuration file : /etc/haproxy/haproxy.cfg
2/10/2016 11:32:00 PM[WARNING] 040/123200 (524) : config : 'option forwardfor' ignored for proxy 'default' as it requires HTTP mode.
2/10/2016 11:32:00 PM[ALERT] 040/123200 (524) : Fatal errors found in configuration.
2/10/2016 11:32:00 PM[scripts.sh:179] return 1
2/10/2016 11:32:00 PM[config.sh:222] CATTLE_SCRIPT_DEBUG=true
2/10/2016 11:32:00 PM[config.sh:222] ./apply.sh
2/10/2016 11:32:00 PM[[scripts.sh:184] script_env
2/10/2016 11:32:00 PM[[scripts.sh:109] '[' -n http://rancher.republicwealth.com.au:8080/v1 ']'
2/10/2016 11:32:00 PM[[scripts.sh:110] return
2/10/2016 11:32:00 PM[[scripts.sh:186] export CATTLE_HOME=/var/lib/cattle
2/10/2016 11:32:00 PM[[scripts.sh:186] CATTLE_HOME=/var/lib/cattle
2/10/2016 11:32:00 PM[[scripts.sh:187] export CATTLE_CONFIG_URL=http://rancher.republicwealth.com.au:8080/v1
2/10/2016 11:32:00 PM[[scripts.sh:187] CATTLE_CONFIG_URL=http://rancher.republicwealth.com.au:8080/v1
2/10/2016 11:32:00 PM[[scripts.sh:188] export CATTLE_STORAGE_URL=http://rancher.republicwealth.com.au:8080/v1
2/10/2016 11:32:00 PM[[scripts.sh:188] CATTLE_STORAGE_URL=http://rancher.republicwealth.com.au:8080/v1
2/10/2016 11:32:00 PM[apply.sh:5] rm -rf /etc/haproxy/certs/default.pem /etc/haproxy/certs/server1.pem
2/10/2016 11:32:00 PM[apply.sh:6] stage_files
2/10/2016 11:32:00 PM[scripts.sh:77] local monit=false
2/10/2016 11:32:00 PM[scripts.sh:79] '[' -d content-home ']'
2/10/2016 11:32:00 PM[scripts.sh:84] '[' -d content ']'
2/10/2016 11:32:00 PM[scripts.sh:85] for i in 'content/etc/init.d/*'
2/10/2016 11:32:00 PM[scripts.sh:86] '[' -f 'content/etc/init.d/*' ']'
2/10/2016 11:32:00 PM[scripts.sh:91] for i in 'content/etc/monit/conf.d/*'
2/10/2016 11:32:00 PM[scripts.sh:92] '[' -f content/etc/monit/conf.d/haproxy ']'
2/10/2016 11:32:00 PM[scripts.sh:93] monit=true
2/10/2016 11:32:00 PM[scripts.sh:94] chmod 600 content/etc/monit/conf.d/haproxy
2/10/2016 11:32:00 PM[scripts.sh:98] find content -name '*.sh' -exec chmod +x '{}' ';'
2/10/2016 11:32:00 PM[scripts.sh:99] sed 's/^/INFO: ROOT -> /'
2/10/2016 11:32:00 PM[scripts.sh:99] tar xvf - --no-overwrite-dir -C /
2/10/2016 11:32:00 PM[scripts.sh:99] tar cf - -C content .
2/10/2016 11:32:00 PMINFO: ROOT -> ./
2/10/2016 11:32:00 PMINFO: ROOT -> ./etc/
2/10/2016 11:32:00 PMINFO: ROOT -> ./etc/haproxy/
2/10/2016 11:32:00 PMINFO: ROOT -> ./etc/haproxy/certs/
2/10/2016 11:32:00 PMINFO: ROOT -> ./etc/haproxy/certs/default.pem
2/10/2016 11:32:00 PMINFO: ROOT -> ./etc/haproxy/certs/certs.pem
2/10/2016 11:32:00 PMINFO: ROOT -> ./etc/haproxy/haproxy.cfg
2/10/2016 11:32:00 PMINFO: ROOT -> ./etc/monit/
2/10/2016 11:32:00 PMINFO: ROOT -> ./etc/monit/conf.d/
2/10/2016 11:32:00 PMINFO: ROOT -> ./etc/monit/conf.d/haproxy
2/10/2016 11:32:00 PMINFO: ROOT -> ./etc/default/
2/10/2016 11:32:00 PMINFO: ROOT -> ./etc/default/haproxy
2/10/2016 11:32:00 PM[scripts.sh:102] '[' true = true ']'
2/10/2016 11:32:00 PM[scripts.sh:103] reload_monit
2/10/2016 11:32:00 PM[[scripts.sh:68] pidof monit
2/10/2016 11:32:00 PM[[scripts.sh:68] true
2/10/2016 11:32:00 PM[scripts.sh:68] local monit=
2/10/2016 11:32:00 PM[scripts.sh:69] '[' -n '' ']'
2/10/2016 11:32:00 PM[apply.sh:8] awk '/BEGIN.*PRIVATE KEY/{i++}{print > "/etc/haproxy/certs/server"i".pem"}' /etc/haproxy/certs/certs.pem
2/10/2016 11:32:00 PM[apply.sh:9] rm /etc/haproxy/certs/certs.pem
2/10/2016 11:32:00 PM[apply.sh:10] '[' '!' -s /etc/haproxy/certs/default.pem ']'
2/10/2016 11:32:00 PM[apply.sh:12] grep -q 'version 1.6'
2/10/2016 11:32:00 PM[apply.sh:12] haproxy -v
2/10/2016 11:32:00 PM[apply.sh:20] reload_haproxy /etc/haproxy/haproxy.cfg
2/10/2016 11:32:00 PM[scripts.sh:169] CONFIG=/etc/haproxy/haproxy.cfg
2/10/2016 11:32:00 PM[scripts.sh:171] '[' '!' -f /var/run/haproxy.pid ']'
2/10/2016 11:32:00 PM[[scripts.sh:176] cat /var/run/haproxy.pid
2/10/2016 11:32:00 PM[scripts.sh:176] haproxy -p /var/run/haproxy.pid -f /etc/haproxy/haproxy.cfg -sf 507
2/10/2016 11:32:00 PM[ALERT] 040/123200 (539) : parsing [/etc/haproxy/haproxy.cfg:34] : unknown keyword 'ssl-default-bind-options' in 'defaults' section
2/10/2016 11:32:00 PM[ALERT] 040/123200 (539) : Error(s) found in configuration file : /etc/haproxy/haproxy.cfg
2/10/2016 11:32:00 PM[WARNING] 040/123200 (539) : config : 'option forwardfor' ignored for proxy 'default' as it requires HTTP mode.
2/10/2016 11:32:00 PM[ALERT] 040/123200 (539) : Fatal errors found in configuration.
2/10/2016 11:32:00 PM[scripts.sh:179] return 1
2/10/2016 11:32:00 PM[config.sh:1] cleanup
2/10/2016 11:32:00 PM[config.sh:9] EXIT=1
2/10/2016 11:32:00 PM[config.sh:11] '[' -e /var/lib/cattle/download.aOIXuR4 ']'
2/10/2016 11:32:00 PM[config.sh:12] rm -rf /var/lib/cattle/download.aOIXuR4
2/10/2016 11:32:00 PM[config.sh:15] return 1
2/10/2016 11:32:00 PM
The system is going down NOW!
2/10/2016 11:32:00 PM
Sent SIGTERM to all processes
2/10/2016 11:32:01 PM
Sent SIGKILL to all processes
2/10/2016 11:32:01 PM
Requesting system reboot
```

**Comment by yunspace** [comment] 2016-02-10 13:29
I tried putting the config in `global` and get another error:

     2/11/2016 12:27:03 AM[ALERT] 040/132703 (539) : parsing [/etc/haproxy/haproxy.cfg:14] : unknown option 'accept-proxy' on global statement 'ssl-default-bind-options'.

**Comment by vincent99** [comment] 2016-02-10 15:58
Yeah I didn't actually try it; the docs say `Please check the "bind"
keyword to see available options.` but sort of imply only the OpenSSL-relates ones work.  You'll need the rest of #2179 then.

Are you trying to do SSL at the container instead of the balancer for some reason?  Since you're just doing port 443 you would normally have a HTTP (instead of TCP) listener and do SSL termination at the balancer.  That will add the X-Forwarded-For header to the http request sent to the backend (in plaintext, but AES-encrypted over the managed overlay network).

**Comment by yunspace** [comment] 2016-02-13 01:55
I am doing SSL termination at the balancer on port 443. But since the Rancher Load Balancer doesn't redirect HTTP to HTTPS, I'm using another nginx service to do the following redirect:

    server {
        listen         80;
        return 301 https://$host$request_uri;
    }

**Comment by raphink** [comment] 2016-02-25 15:34
@yunspace how do you make it so that it behaves as if the LB was doing it?

I've tried several options without success:
1) `rancher/load-balancer-service` cannot be used as a sidekick
2) `rancher/load-balancer-service` cannot have sidekicks
3) putting an nginx with redirection behind the LB doesn't seem to work. I've used something like:

```yaml
lb:
  ports:
  - 443:80                                                    
  - 80:80
  labels:
    io.rancher.loadbalancer.ssl.ports: '443'
    io.rancher.loadbalancer.target.hello: 443=80              
    io.rancher.loadbalancer.target.https-redirect: 80=80      
  image: rancher/load-balancer-service
  links:
  - hello                                                     
  - https-redirect                                            
  
hello:
  image: tutum/hello-world
                                                              
https-redirect:
  image: pronto/nginx-redirect:latest
  environment:
    REDIRECT_TO_URL_PREFIX: "https://<URL_OF_THE_SERVICE>"
```

but it doesn't work as expected.

The only way I've found to get it to work was to edit manually `haproxy.conf` from the LB, and kill `haproxy` to get it restarted. Obviously, that's not an acceptable way to do it, and I see no way of automating it, since sidekicks cannot be coupled with LBs.

**Comment by yunspace** [comment] 2016-02-26 14:44
Why would you have your nginx-redirect sit behind your load balancer? The idea is that your nginx-redirect listens to `80` and redirect to your load-balancer which listens to `443` only.

```
https-redirect:
  ports:
  - 80:80/tcp
  labels:
    io.rancher.scheduler.global: 'true'
    io.rancher.container.pull_image: always
    io.rancher.service.hash: 998411a61d0f799981e2f1f51b30570a82690423
  tty: true
  image: jamessharp/docker-nginx-https-redirect:latest
  stdin_open: true
ssl-load-balancer:
  ports:
  - 443:443
  external_links:
  labels:
  tty: true
  image: rancher/load-balancer-service
  stdin_open: true
```

**Comment by raphink** [comment] 2016-02-26 17:52
@yunspace for this to work, you need both services to be marked as global. Otherwise, you can't have them resolve to the same domain name and ensure that it will work.

**Comment by yunspace** [comment] 2016-02-28 11:04
@raphink yes they are both global. I just left them out since too many labels to paste. Thx for pointing this out
