### ISSUE TITLE
When glusterfs-server is scaled up , the newly created glusterfs-server instances donot have the newly created volumes.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#2786] opened 2015-11-23 23:01 UTC
Server version - v0.47.0-rc1

Deployed "Gluster FS" and "Convoy Gluster” stacks with 2 hosts in my setup as part of convoy storage pool.

I had a scale of 3 for  glusterfs-server" service. Scaled this service to scale of 5. 2 new instances got deployed and are in "running" state with all sidekick instances created.

I am also able to see that the 2 new instances have joined the storage pool  by executing gluster peer status on the existing instances which lists the new instances as being connected. 

But new volumes created in this storage pool are not being seen when accessing the /data/glusterfs/brick1/mygluster1_vol

Should we expect to have access to the new volumes created from the newly scaled up instances?

**Comment by cloudnautique** [comment] 2015-11-23 23:06
This is expected and by design.

**Comment by cloudnautique** [comment] 2015-11-23 23:07
Missed the last line, will take a look

**Comment by cloudnautique** [comment] 2015-11-24 17:59
@sangeethah, I tried to reproduce, and might be missing something. The volume mygluster1_vol is created on creation of the stack. Once it is created it is static. It will not change by anything we do with the stack. When adding additional nodes, the result is you get a gluster pool + N nodes(as you saw with the peer probes) The directory is created in `/data/glusterfs/brick1`, but is unused. It is not part of the initial volume, and will not show any data from the volume. 

In trying to reproduce this, if I do
`gluster volume list` on the new nodes, I see the initial volume.

If I add a new volume to the new nodes and do
`gluster volume list` I see the two volumes (initial + new) on both the new and original containers.

This is all working as expected.

**Comment by will-chan** [comment] 2015-11-24 18:28
can we close this if this is as designed?

**Comment by cloudnautique** [comment] 2015-11-24 18:33
I'm good with closing.

**Closed** 2015-11-25 17:42 UTC
Labels: kind/bug, status/wontfix

**Comment by galindro** [comment] 2016-01-20 23:50
"(...) he volume mygluster1_vol is created on creation of the stack. Once it is created it is static (...)"

@cloudnautique why the volumes created are static? Could you provide more details about it?
