### ISSUE TITLE
Fleet is in an error state in Rancher Hardened Cluster

### ISSUE THREAD

**Issue by sowmyav27** [rancher/rancher#38248] opened 2022-07-11 20:25 UTC
**Rancher Server Setup**
- Rancher version: `2508215`
- Installation option (Docker install/Helm Chart): Rancher HA Helm install
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): RKE1
- Proxy/Cert Details: Rancher geenrated

**Information about the Cluster**
- Kubernetes version: 1.24 local RKE1 cluster

**User Information**
- What is the role of the user logged in? (Admin/Cluster Owner/Cluster Member/Project Owner/Project Member/Custom) admin

   
**Describe the bug**
Fleet is in an error state in Rancher

**To Reproduce**

- Navigate to Rancher local cluster --> System project
- Fleet pod is in an error state.
- Fleet app in Apps and Marketplace is also in an error state.

**Result**
- Fleet controllers show error: `"rancher/fleet:v0.3.10-rc1": rpc error: code = Unknown desc = Error response from daemon: manifest for rancher/fleet:v0.3.10-rc1 not found: manifest unknown: manifest unknown`

**Comment by izaac** [comment] 2022-07-14 20:01
Fleet is now trying to deploy `v0.3.10-rc2` in the latest `v2.6-head` But now the controller pod is throwing this error:

`CreateContainerConfigError (container has runAsNonRoot and image has non-numeric user (fleet), cannot verify user is non-root (pod: "fleet-controller-66588fdfcb-dlbtl_cattle-fleet-system(834465e0-0228-4cab-81ec-2271a6fc784f)", container: fleet-controller))`

**Comment by mattfarina** [comment] 2022-07-14 20:46
I was unable to reproduce the problem here. Can you please provide some more detail so we can replicate the problem.

What I did was to start with Rancher Desktop 1.4.1 running k3s 1.23.8.

The install commands were...

```console
kubectl create namespace cattle-system
```

```console
kubectl apply -f https://github.com/cert-manager/cert-manager/releases/download/v1.7.1/cert-manager.crds.yaml
```

```console
helm install cert-manager jetstack/cert-manager \
  --namespace cert-manager \
  --create-namespace \
  --version v1.7.1
```

```console
helm install rancher rancher-latest/rancher \
  --namespace cattle-system \
  --set hostname=rancher.my.org \
  --set bootstrapPassword=admin --set rancherImageTag=v2.6-head
```

I did make sure cert manager and rancher came up before proceeding to next steps.

The following images are the state fleet was in when it came up...
<img width="1602" alt="Screen Shot 2022-07-14 at 4 36 21 PM" src="https://user-images.githubusercontent.com/62991/179080610-f73ad77e-0915-4df5-a936-3e146bd55531.png">
<img width="1602" alt="Screen Shot 2022-07-14 at 4 35 57 PM" src="https://user-images.githubusercontent.com/62991/179080621-71bb9a69-fa15-4261-a425-681493205a2d.png">

**Comment by izaac** [comment] 2022-07-14 21:31
Seems that the last error happens with Hardened clusters. On regular non hardened clusters I see fleet correctly deployed.

**Comment by prachidamle** [comment] 2022-07-15 03:47
@manno @mattfarina this commit seems to be the root cause https://github.com/rancher/fleet/commit/7a894f65a37c384c48d159ee56a76c7adb49b607 

This commit changed the UID in the image and seems to have introduced this error for hardened clusters:

```CreateContainerConfigError (container has runAsNonRoot and image has non-numeric user (fleet), cannot verify user is non-root (pod: "fleet-controller-66588fdfcb-dlbtl_cattle-fleet-system(834465e0-0228-4cab-81ec-2271a6fc784f)", container: fleet-controller))```

**Comment by mattfarina** [comment] 2022-07-15 14:27
An update: a change has been merged to fix this issue which happens in hardened environments.

I've assigned this to @prachidamle as she plans on cutting the tag that will have this fix in it.

**Comment by rancher-max** [comment] 2022-07-15 22:39
I notice the same thing with the gitjob pod as well, but I believe the revert should fix this as well as there doesn't appear to be anything in the gitjob repo directly that would affect this. The error is effectively the same though just on this other pod and different username:
```
state:
      waiting:
        message: 'container has runAsNonRoot and image has non-numeric user (gitjob),
          cannot verify user is non-root (pod: "gitjob-6465546d97-hk9vv_cattle-fleet-system(38aef962-c656-4e32-aeb3-6004d6e34c02)",
          container: gitjob)'
        reason: CreateContainerConfigError
```

**Comment by prachidamle** [comment] 2022-07-19 08:26
@macedogm gitjob image also needs a fix to revert this change in UID, since it fails for hardened cluster:
Can we revert this: [https://github.com/rancher/gitjob/commit/997c1a98bd5d3f991fb058400b63d5a8b8338406#diff-c55d1ee74f32cd4b9eeeceaec9[…]f52e761acb158a5b0b0e088c7725c9ca](https://github.com/rancher/gitjob/commit/997c1a98bd5d3f991fb058400b63d5a8b8338406#diff-c55d1ee74f32cd4b9eeeceaec981a180f52e761acb158a5b0b0e088c7725c9ca)

**Comment by macedogm** [comment] 2022-07-19 08:43
@prachidamle can you please review https://github.com/rancher/gitjob/pull/62?

**Comment by izaac** [comment] 2022-07-19 20:19
@prachidamle @macedogm on the latest Rancher `v2.6.7-rc3` 
Fleet `v0.3.10-rc3`
GitJob `v0.1.29-rc1`

GitJob is pulling the latest `v0.1.29-rc1` but also `v0.1.28` see the following screenshot:

![Screen Shot 2022-07-19 at 1 15 06 PM](https://user-images.githubusercontent.com/27659/179840720-893993fe-706f-477c-bb8d-6716fd59e438.png)

**Comment by izaac** [comment] 2022-07-19 20:57
Please disregard the last comment, I think that environment was @prachidamle test env for hardened

**Closed** 2022-07-20 17:10 UTC
Labels: status/blocker, kind/bug-qa, [zube]: To Test, area/fleet, team/area3
