### ISSUE TITLE
Rancher UI is not operational if there is some error listing Kubernetes resources

### ISSUE THREAD

**Issue by prachidamle** [rancher/rancher#4581] opened 2016-04-27 22:03 UTC
[kubernetes-container.txt](https://github.com/rancher/rancher/files/239460/kubernetes-container.txt)

Rancher Version: local setup post 1.0.1

Docker Version: 1.10.3

Results: 
1) My kubernetes api-server container has some panic errors, I dont know how to reproduce that state. But I have attached the container logs

2) When this happened, the rancher UI stopped being operational. In developer tools, I see the listing kubernetes replicationcontrollers and pods error out with 500 Internal Server error. Attached screenshot.
<img width="1439" alt="screen shot 2016-04-27 at 2 47 52 pm" src="https://cloud.githubusercontent.com/assets/1470602/14869561/1296287a-0c89-11e6-853e-614c9bee2089.png">

Request URL:http://localhost:8080/r/kubernetes/api/v1/replicationcontrollers
Request URL:http://localhost:8080/r/kubernetes/api/v1/pods

Expected: Other aspects of the UI should be operational, even if K8s resources cannot be listed

**Comment by deniseschannon** [comment] 2016-04-27 23:35
Duplicate of https://github.com/rancher/rancher/issues/4450

**Closed by deniseschannon** 2016-04-27 23:35 UTC
Labels: area/kubernetes, area/ui
