### ISSUE TITLE
IP Address (Public (on Host) IP/Port) is not taken over correctly

### ISSUE THREAD

**Issue by egobude** [rancher/rancher#4606] opened 2016-04-29 13:02 UTC
When i setup a new stack via rancher ui with a custom docker-compose.yml the ip address is not taken over correctly. When i try to update the container in the ui the ip address is missing in the "Public (on Host) IP/Port" field.

Example docker-compose.yml: 

    backend:
      image: nginx
      ports:
      - 1.2.3.4:81:80

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v1.0.0` Cattle: `v0.159.2` UI: `v0.100.3` |
|Access|`localauth` `admin`|
|Route|`service.containers`|

**Comment by deniseschannon** [comment] 2016-05-05 20:32
Duplicate of https://github.com/rancher/rancher/issues/4425

**Closed by deniseschannon** 2016-05-05 20:32 UTC
