### ISSUE TITLE
[BUG] Logs do not appear when installing a chart from `apps & marketplace`

### ISSUE THREAD

**Issue by slickwarren** [rancher/rancher#38436] opened 2022-07-26 22:12 UTC
**Rancher Server Setup**
- Rancher version: v2.6.7-rc3
- Installation option (Docker install/Helm Chart): docker
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc):n/a
- Proxy/Cert Details:n/a

**Information about the Cluster**
- Kubernetes version: any (tested with 1.23.8-rancher1-1 and rke2r1)
- Cluster Type (Local/Downstream): downstream
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider): any (tested with linode, harvester)

**User Information**
- What is the role of the user logged in? (Admin/Cluster Owner/Cluster Member/Project Owner/Project Member/Custom): standard user, cluster owner

**Describe the bug**
logs are not appearing whenever a user installs a chart 

**To Reproduce**
* on a downstream cluster, go to apps & marketplace
* install an app
* wait for logs to appear with the status of the chart install

**Result**
loading screen takes longer than normal and logs never appear

**Expected Result**
logs should appear when a user is installing a chart

**additional comments:**
does not occur on 2.6.5

**Comment by MKlimuszka** [comment] 2022-08-02 16:10
Closing as cannot reproduce according to QA

**Closed by MKlimuszka** 2022-08-02 16:10 UTC
Labels: kind/bug-qa, team/area3, [zube]: Team Area 3, area/charts, v2.6.7
